### ISSUE TITLE
Azerty keyboards: many keys do nothing

### ISSUE THREAD

**Issue by laurentj** [servo/servo#10006]
Servo build: commit 075ce980a24d1e31ad704915681ef3f7edd03ccb , release build, on linux Kubuntu 15.04 64bits, fr_FR with an azerty keyboards

On input elements, many keys do nothing. So I can't type ":", "/", "!", "&", "*", "µ", "$", "£", "<", ">" and so on. I cannot type numbers, and most of signs that are on the first line of the keyboard. It seems I can type some of these characters but there are on some others keys. ex: ":" -> shift+",". The layout is like a mix between AZERTY  (all letter seem ok) and QWERTY.. Strange.

**Comment by paulrouget** [comment]
Virtual key codes are fun. See https://github.com/servo/servo/issues/4144
