### ISSUE TITLE
reddit.com: console is flooded with "WARNING: insert rect Rect(…) outside bounds, dropped." messages

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10012]
If reddit.com is loaded without browserhtml, we get it ~20 times, and the page load normally.

If loaded within browserhtml, the page never ends up loading completely, and the the warning is printed many times per seconds. Also, the reflow counter keeps going up.

**Comment by metajack** [comment]
cc @pcwalton @glennw 

Let's just remove these. I believe they were just for debugging.

**Comment by paulrouget** [comment]
Filing a follow-up for the loading issue: https://github.com/servo/servo/issues/10027
