### ISSUE TITLE
Long wikipedia articles are cut off after a few screenfuls

### ISSUE THREAD

**Issue by jruderman** [servo/servo#10023]
```
./mach run -r -- "https://en.wikipedia.org/w/index.php?title=First_Crusade&oldid=709277350"
```

After I scroll down through a few sections, I get to a sudden area that's just white.

[Meta for wikipedia is #2554]

**Comment by frewsxcv** [comment]
Gif of this:

![untitled](https://cloud.githubusercontent.com/assets/416575/14061836/35264d52-f361-11e5-91bb-eaadfcc9e771.gif)

**Comment by nox** [comment]
I can't reproduce this anymore.
