### ISSUE TITLE
Memory consumption keeps growing for no good reason (osx)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10029]
OSX.

Just moving the mouse hover the window makes the memory consumption grow.

Most likely this: https://github.com/tomaka/glutin/pull/733

**Comment by kaksmet** [comment]
This only happens with webrender for me.

**Comment by pcwalton** [comment]
75%-80% of the CPU time is in Mac event handling code (either wakeup from one thread or processing the events). Lovely.

**Comment by pcwalton** [comment]
By the way, this is always going to take more CPU time than Gecko, because Gecko does not sync to vblank via `swap_buffers()` (the only way to reliably avoid tearing IME) and therefore we have to do more drawing than Gecko does. I don't see any other alternative other than risking tearing.

**Comment by paulrouget** [comment]
@pcwalton how are your comments relevant to the memory consumption?

**Comment by pcwalton** [comment]
@paulrouget Sorry, commented on wrong bug. These comments were meant for #9844.

**Comment by pcwalton** [comment]
@paulrouget Can you run with `-Z gc-profile` and see if GCs are occurring? From my local tests it seems the issue is that we aren't GCing, and therefore mouse events are piling up.

**Comment by paulrouget** [comment]
> @paulrouget Can you run with -Z gc-profile and see if GCs are occurring? From my local tests it seems the issue is that we aren't GCing, and therefore mouse events are piling up.

No GC here apparently.

**Comment by jdm** [comment]
I tried https://gist.github.com/jdm/1d2e71157887849c7ba2 but didn't notice any difference in terms of memory usage when flailing my mouse around an instance of about-mozilla.html. That being said; I didn't notice unbounded memory usage either - it generally hovered between 90-105mb.

**Comment by jdm** [comment]
@amccreight does the previous gist look like the hinting you were talking about?

**Comment by amccreight** [comment]
Yes, though I'm not too familiar with how it is actually supposed to be used.

**Comment by jdm** [comment]
We should verify the behaviour now.

**Comment by pcwalton** [comment]
@paulrouget Want to try again?

**Comment by paulrouget** [comment]
Moving the mouse hover the window: +0.1Mb every `0s

Moved the mouse for 20 seconds over the window.
Memory grew from 53.1Mb to 53.3Mb.
This is a lot better than before.

But I don't see any gc logs with `-Z gc-profile`.

**Comment by pcwalton** [comment]
I think we don't necessarily need GC heuristics here if dramatic memory increase isn't seen anymore, because a GC *should* happen once a lot of memory starts being used.

Can we demote this issue to a lower priority level?

**Comment by paulrouget** [comment]
> Can we demote this issue to a lower priority level?

Yes. As far as I am concerned, it's fixed.
