### ISSUE TITLE
Update to servo-glutin 0.4.11

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10028]
This is apparently not trivial.

core-graphics has been updated to 0.3. Which requires serde 0.7. But then webrender doesn't compile anymore:

```
webrender_traits-e24a580db67dabe6/master/src/api.rs:32:32: 32:32 error: the trait `serde::de::Deserialize` is not implemented for the type
 `core_graphics::font::CGFont` [E0277]
/webrender_traits-e24a580db67dabe6/master/src/api.rs:32 #[derive(Serialize, Deserialize)]
```

@nox what do you recommend?

**Comment by nox** [comment]
Bumping core-graphics requires bumping Serde. My [Serde bump](https://github.com/nox/servo/compare/serde) is almost ready, just blocked by https://github.com/cybergeek94/mime_guess.

**Comment by paulrouget** [comment]
Addressed: https://github.com/servo/glutin/pull/79
