### ISSUE TITLE
./mach run -b doesn't work on OS X 10.9

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#10031]
```
-[NSWindow setTitleVisibility:]: unrecognized selector sent to instance 0x7fc4d8d0fc00
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
```

NSWindow's [titleVisibility](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindow_Class/#//apple_ref/occ/instp/NSWindow/titleVisibility) property is "Available in OS X v10.10 and later."

**Comment by jdm** [comment]
cc @pcwalton 
I'm running 10.9.5 so I can test things too.

**Comment by kaksmet** [comment]
This was fixed by https://github.com/servo/glutin/pull/85
