### ISSUE TITLE
Tor access to servo.org

### ISSUE THREAD

**Issue by burdges** [servo/servo#10043]
It's impossible to access servo.org from Tor browser because the site used CloudFlare as a CDN, which gives Tor users an unsolvable CAPTCHA.

I think CloudFlare has configuration options that remove the CAPTCHA problem for Tor users, but not sure the details.  Apparently CloudFlare is the only CDN that creates these issues for Tor users.  In particular, their competitors like Akamai do not find Tor to be an issue.  It's supposedly all due to CloudFlare using an incorrect model of web abuse designed around Email detection as opposed to the web.

**Comment by jdm** [comment]
If this is a site configuration issue (rather than a limitation of Servo the browser engine), please file it at https://github.com/servo/servo.org/issues.

**Comment by burdges** [comment]
Done : https://github.com/servo/servo.org/issues/20
