### ISSUE TITLE
On OSX servo shows CJK chars as squares

### ISSUE THREAD

**Issue by bobchao** [servo/servo#10045]
![2016-03-17 12 12 45](https://cloud.githubusercontent.com/assets/168931/13836178/98c08b9a-ec39-11e5-8818-7b479f1c44b7.png)

``` html
<ul>
  <li>C 中文</li>
  <li>J 日本語</li>
  <li>K 한국어</li>
</ul>
```

**Comment by bobchao** [comment]
On Linux it works well (humm, not that "well" on the layout part but at least it shows the chars correctly)

![photo186463213883336655](https://cloud.githubusercontent.com/assets/168931/13836220/fdb3c558-ec39-11e5-9dbe-7d1a0c67b010.jpg)

**Comment by frewsxcv** [comment]
Possibly related to https://github.com/servo/servo/issues/7762

**Comment by hiroshiyui** [comment]
I can reproduce such square (or so-called "tofu") font issue on my system, which runs:

* Arch Linux x86-64, Linux kernel 4.4.5
* KDE Plasma 5.5.5
* Servo (built from latest source code on Git)

Just found that if I change my fonts fallback order in Fontconfig, to set the first candidate font from "Noto Sans" to "Noto Sans CJK TC", almost all CJK characters are shown as expected.

**Comment by Arthur2e5** [comment]
This problem is in a form somehow like this [libgdiplus bug](https://bugzilla.xamarin.com/show_bug.cgi?id=39418) (well, in the `"Sans"` case), where libgdiplus didn't consider any possible extra fontconfig substitutes and only used the first match. Some system-based fallback is necessary…

As a temporary hack, perhaps `last_resort_font_families()` can be set according to glyph coverage instead? It looks like OS X users can try stealing Arial Unicode MS from Windows for now, but there's nothing except for font name hacks for FreeType users.

**Comment by mmatyas** [comment]
Does not work for me on Xubuntu and GNOME 15.10:

![kepernyokep_2016-05-05_14-28-48](https://cloud.githubusercontent.com/assets/4354863/15043522/147fcaba-12ce-11e6-95cb-606593f95d7e.png)

**Comment by Arthur2e5** [comment]
@mmatyas If you are reporting such cases on LInux, mentioning the output of `fc-match Sans` can help confirm @hiroshiyui's report.

**Comment by mmatyas** [comment]
`fc-match Sans` returns `DejaVuSans.ttf: "DejaVu Sans" "Book"` for me.
Here's the full output of `fc-match -a "sans-serif"`: http://pastebin.com/afMmsaUT, hope this helps.

**Comment by SaschaNaz** [comment]
CJK also is being displayed as squares on Windows nightly build. Should I open a new issue for Windows build?

![image](https://cloud.githubusercontent.com/assets/3396686/17657132/d4469d42-62fb-11e6-8a3c-f41b1495eb66.png)

**Comment by imiuka** [comment]
i'm quite sure the root cause for this issue is https://github.com/servo/servo/issues/17267

**Comment by nox** [comment]
The characters are displayed correctly on macOS.

**Comment by mmatyas** [comment]
Still failing on Ubuntu 16.04 and also on Solus 3 as of 2017-10-01, using the 64bit Linux build from servo.org

![kepernyokep_2017-10-01_23-06-31](https://user-images.githubusercontent.com/4354863/31058973-45322d50-a6fd-11e7-9861-db803d370491.png)

**Comment by Artoria2e5** [comment]
Probably nox's working report is caused by ja.wp somehow making a Japanese font the first (and only, for now) option. Make some other test cases to reopen it I guess?

**Comment by jdm** [comment]
Yeah, some links to reproduce the problem would be great.

**Comment by tigercosmos** [comment]
@jdm I think `Labels` should also add  `Linux`. (#19228)

**Comment by jdm** [comment]
I've tested some of the earlier examples on macOS and they appear to render correctly. Please file new issues with testcases or links to sites that do not non-english characters correctly.
