### ISSUE TITLE
textarea text overflow

### ISSUE THREAD

**Issue by yoava333** [servo/servo#10053]
when rendering this page this is what I get in servo compared to chrome/firefox
![textarea problem](https://cloud.githubusercontent.com/assets/1495026/13845214/1f70f65e-ec47-11e5-90cc-ad8be7e7578e.png)

code to reproduce this issue:
```html
<textarea cols="20" rows="5">This is a sentence that is more than 20 cols, for showing that this is a real problem.</textarea>
```

I'm using release build of e273517fe06720afe0ef74815cce5e007df7dc3d

**Comment by yoava333** [comment]
Another issue which is similar in nature. tell me if it's supposed to be a different issue
if the textarea overflows in rows, there's also no scrolling.

![textarea problem2](https://cloud.githubusercontent.com/assets/1495026/13845770/ca85a0be-ec4a-11e5-84e5-7521c893afbc.png)

code to reproduce:

```html
<textarea cols="20" rows="5">This
is
a
sentence
that
is
more
than
5
rows,
showing
this
is
a
real                                           
problem.</textarea>       
```

**Comment by paulrouget** [comment]
Can you file a different issue for that?

**Comment by yoava333** [comment]
@paulrouget done
