### ISSUE TITLE
Failed to unpack package `unicase v1.0.1`

### ISSUE THREAD

**Issue by nenadg** [servo/servo#10051]
Caused by:
      corrupt gzip stream does not have a matching checksum

mach output is as follow:

    nenadg@camacho:~/Documents/code/servo> ./mach build --dev --verbose
    cargo build -v
     Downloading websocket v0.15.0
     Downloading net2 v0.2.19
     unable to get packages from source
    
    Caused by:
     failed to unpack package `unicase v1.0.1`

    Caused by:
      corrupt gzip stream does not have a matching checksum
    Build completed in 3.56s

OS: openSUSE Leap 42.1 (x86_64)

**Comment by mbrubeck** [comment]
I think this is probably a bug in Cargo itself, or the Cargo repo—either that, or it's functioning correctly and caught a rare case of network corruption.  You can try removing the files from the `.cargo` directory to force it to download again.
