### ISSUE TITLE
Panic with -w parameter

### ISSUE THREAD

**Issue by veirus** [servo/servo#10052]
OS: Windows 8.1 x64
Running Servo with -w parameter produce window that doesn't draw anything except white rectangle and eventually it crashes.

Examples:
  1. http://pastebin.com/DAihMSXs
  2. http://pastebin.com/pEXzhhRA
  3. http://pastebin.com/SQuLvaV6

**Comment by Manishearth** [comment]
I don't think webrender is supposed to work on windows yet. @glennw ?

**Comment by veirus** [comment]
I see. Guess i should close it for now.
