### ISSUE TITLE
Support for B2G OS (community effort) and long term plans

### ISSUE THREAD

**Issue by EGhiorzi** [servo/servo#10060]
As well known, Mozilla has discontinued Firefox OS development for smartphones. A community effort to keep B2G alive is moving its first steps. Still some long-term planning may be in place.

B2G is powered by Gecko, and it seems Gecko will be replaced by Servo in the long run. Previously, as far as I know, Servo was supporting a Gonk porting, but recent events may have changed that. What is Servo's long term strategy for B2G support, if any (either official or unofficial)? Can B2G community relies on Servo, or should an alternative be found?

B2G discussions are currently undergoing on this etherpad: <https://public.etherpad-mozilla.org/p/firefox_is_not_dead-brainstorming>

**Comment by pcwalton** [comment]
(1) I think this is better discussed on the mailing list.

(2) When this is discussed on the mailing list, I think we shouldn't start from the premise that "it seems Gecko will be replaced by Servo in the long run", as this is not the case.

**Comment by jdm** [comment]
I agree with Patrick on both counts. Please send a message to [the mailing list](https://www.mozilla.org/en-US/about/forums/#dev-servo).
