### ISSUE TITLE
fonts blurry after scrolling/zooming

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#10067]
Fonts are often blurry after scrolling which is quite annoying in my opinion.

**Comment by paulrouget** [comment]
Can you take a screenshot before / after scrolling?
Does it happen only with webrender?

**Comment by matthiaskrgr** [comment]
It seems to be fine with webrender enabled however the default (no -w) seems to blur.
![scroll_cmp](https://cloud.githubusercontent.com/assets/476013/13866562/fb5695c4-ecb6-11e5-921e-f24baf3bdcac.png)

**Comment by matthiaskrgr** [comment]
Also applies to zooming btw.

**Comment by nox** [comment]
Is this still true?

**Comment by paulrouget** [comment]
> Is this still true?

> It seems to be fine with webrender enabled however the default (no -w) seems to blur.

Now we only use WebRender.
