### ISSUE TITLE
Make sure appveyor.yml at least running a single testcase

### ISSUE THREAD

**Issue by lygstate** [servo/servo#10080]
For example, open a demo html and output & compare

**Comment by edunham** [comment]
The current `appveyor.yml` runs `mach build` and `mach test-unit`, https://github.com/servo/servo/blob/master/appveyor.yml#L44 . This means it uses [mach](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/mach) to run [the unit tests](https://github.com/servo/servo/tree/master/tests/unit)
