### ISSUE TITLE
Don't crash when calling `nodes_from_point` without a document element

### ISSUE THREAD

**Issue by emilio** [servo/servo#10093]
Right now, the function `Document::nodes_from_point` is called when using `document.elementsFromPoint`.

That function asserts that there should be a document element to run, and crashes if not. It should return an empty vector in that case, preferrably issuing a `debug!()` message.

Code:
 * `components/script/dom/document.rs` (the function `nodes_from_point`).

**Comment by rilut** [comment]
I'd love to work on this

**Comment by ecoal95** [comment]
That was fast, it's yours!

Don't forget to mention (in the case I don't review that PR) that there are no new passing tests due to the reasons described in #10091 :)

**Comment by rilut** [comment]
@ecoal95 Hi, actually I think `document.elementsFromPoint` haven't crashed yet, even with the assertion. But, one thing that I've found suspicious is

> │ FAIL [expected PASS] No viewport available
>  │   → assert_array_equals: Should have returned [] lengths differ, expected 0 got 2

As you said, this subtest isn't using an iframe and I'm curious whether it can be fixed.

**Comment by ecoal95** [comment]
Yes, exactly, `createHTMLDocument` doesn't create a new iframe, but it does append an `<html>` node and a `<body>` node, which are our two nodes.

It seems that we should check if the document is in the viewport before doing hit test.

**Comment by ecoal95** [comment]
Note that the assertion should be changed regardless, that's not what that test is testing (no viewport != no document element).

**Comment by jdm** [comment]
You probably want `document.browsing_context().is_some()` instead.

**Comment by jdm** [comment]
Are you still working on this, @rilut?

**Comment by rilut** [comment]
@jdm Yes, I'll get it done on Thursday after exam

**Comment by jdm** [comment]
Ok, thanks! No rush, just wanted to make sure it wasn't abandoned.

**Comment by rilut** [comment]
@jdm sure! Thanks for your consideration
