### ISSUE TITLE
Read preferences from a file

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10098]
As of today, to set a preference, we need to use `--pref xxx.enabled`.

Now that we can use a profile directory (https://github.com/servo/servo/pull/10087), it would be great to be able to store preferences in a file.

**Comment by jdm** [comment]
I guess they would be applied on top of the ones in resources/prefs.json. We could probably do this by reading both files as JSON objects (eg. BTreeMap), then using the `extend` method on the base preferences to merge the second set in.

**Comment by jdm** [comment]
Code: `components/util/prefs.json`

**Comment by matthewbentley** [comment]
Can I take this as a first contribution? I looked at the code (especially #10087 and the content of `components/util/prefs.rs` and `components/util/opts.rs`), and the code shouldn't be bad. I'm assuming I would add a `--pref-file <filename>` option? The only thing I'm not so sure about is test(s), but I can start by looking at existing tests.

**Comment by jdm** [comment]
@matthewbentley Please do! Instead of taking a new argument, we should look for a `prefs.json` file in the optional profile directory that can already be specified as a command line option.

**Comment by jdm** [comment]
In terms of tests, I would write unit tests that demonstrate that the merging of preferences works as expected in `tests/unit/util/prefs.rs`; I don't think we can easily test the actual reading of the files.

**Comment by timvandermeij** [comment]
Fixed by #10114?
