### ISSUE TITLE
Do more speculative parallel computation, e.g. tokenizing

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1009]
Tokenization is one of the examples discussed in [this paper](http://research.microsoft.com/pubs/118795/pldi026-vaswani.pdf) on speculative parallelism.  You can jump into the middle of a character stream, look at a few nearby characters, and guess the lexer state.

There's a [cool library for speculation](http://hackage.haskell.org/package/speculation) in Haskell.  Here's the basic API in untested pseudo-Rust:

``` .rs
fn speculate<A: Eq, B>(guess: A,
                       check: &fn() -> A,
                       work:  &fn(x: &A) -> B)
                           -> B {
    // Check the guess in parallel
    let (port, chan) = comm::stream();
    do spawn { chan.send(check()); }

    // Do work assuming the guess was correct
    let speculative_result = work(guess);

    // Use or re-do that work as appropriate
    let real_value = port.recv();
    if real_value == guess {
        speculative_result
    } else {
        work(real_value)
    }
}
```

The trick of course is to find a cheap way to make a guess which is correct often enough for it to be worthwhile.

If we're doing a lot of speculation we may want a priority scheduler so that it doesn't starve out "real work".

**Comment by nox** [comment]
@cynicaldevil is working on speculative parsing, and this issue isn't very much actionable. Closing.
