### ISSUE TITLE
Implement the Fullscreen API

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10102]
https://fullscreen.spec.whatwg.org/

**Comment by saurvs** [comment]
I'd like to begin work on this.

**Comment by farodin91** [comment]
I would look into this.

**Comment by farodin91** [comment]
@jdm Any tipp to get rendering a single element?

**Comment by jdm** [comment]
That's probably something that would require webrender integration. @glennw might know.

**Comment by farodin91** [comment]
@glennw I haven't an idea for a start point. Any Tipp?

**Comment by farodin91** [comment]
I'll start soon to work on it.
