### ISSUE TITLE
Using viewport percentage lengths (e.g. vh, vw) causes unnecessary style recalc on resize

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#10104]
As mentioned in https://github.com/servo/servo/pull/9876#issuecomment-198583704, Servo currently does more work than necessary to recalculate `vh`/`vw`/`vmin`/`vmax` units when the window size changes. Currently, during parsing, if a stylesheet contains any of these viewport percentage units, we add a `dirty_on_viewport_size_change` to the stylesheet.  When the viewport size changes, if any stylesheet has this flag set, we dirty all nodes and recalculate their styles.

Instead, we could dirty only nodes that match rules containing viewport percentages. During selector matching, `Stylist::push_applicable_declarations` could set a flag on any node whose applicable declarations contain one of these units.  This would require adding a method to DeclaredValue and the various SpecifiedValue types that determines whether the value includes a viewport percentage length.

**Comment by SimonSapin** [comment]
> Instead, we could dirty only nodes that match rules containing viewport percentages.

The descendants of these nodes may also be affected through CSS inheritance, and likely need to be dirtied as well.

**Comment by roysohan** [comment]
I am a beginner but i want to contribute, and the folks said that e-easy tags are the best place to start. So how do I contribute to this issue.

**Comment by jrasanen** [comment]
Hi @roysohan. Checkout [wiki](https://github.com/servo/servo/wiki) and especially [Quickstart to Hacking Servo](https://github.com/servo/servo/blob/master/HACKING_QUICKSTART.md). For any questions regarding Servo, #servo IRC channel on irc.mozilla.org is a fine place. For Rust related questions there is #rust and #rust-beginner channels.

**Comment by mbrubeck** [comment]
Note: This issue is tagged "less easy", which means that it might not be suitable for a brand new contributor, but could be good as a next step after one or more easy issues.  This is mainly because it could require making a large number of small changes; it will probably be tedious but hopefully not too complicated.  If you are patient and have enough time, you could probably start out with this issue.

One way to solve this issue would be to add a trait for asking whether a given CSS value has any viewport percentage lengths:

```rust
trait HasViewportPercentage {
    fn has_viewport_percentage(&self) -> bool;
}
```

Implement this trait for the [Length](http://doc.servo.org/style/values/specified/enum.Length.html) type, returning `true` if it is a Length::ViewportPercentage and `false` otherwise.  Then implement it for any other types in [style::values::specified](http://doc.servo.org/style/values/specified/index.html) that can contain Length values; it should return `true` if *any* field of the type contains a Length::ViewportPercentage.  For example:

```rust
impl HasViewportPercentage for LengthOrNone {
    fn has_viewport_percentage(&self) -> bool {
        match *self {
            Length(length) => length.has_viewport_percentage(),
            None => false
        }
    }
}
```

Next, look at each [SpecifiedValue type](http://doc.servo.org/servo/index.html?search=SpecifiedValue).  (Many of these are aliases to common types, so there are fewer than it appears.)  If the type has any fields that might contain Length values, then it should impl the trait and return `true` if any of those values is a `Length::ViewportPercentage`:

```rust
impl HasViewportPercentage for line_height::SpecifiedValue {
    fn has_viewport_percentage(&self) -> bool {
        match *self {
            line_height::SpecifiedValue::LengthOrPercentage(ref val) => val.has_viewport_percentage(),
            line_height::SpecifiedValue::Number(_) => false,
            line_height::SpecifiedValue::Normal => false,
        }
    }
}
```

Once all of those impls are written, we can impl HasViewportPercentage for [PropertyDeclaration](http://doc.servo.org/style/properties/enum.PropertyDeclaration.html).  The implementation will look something like this:

```rust
impl HasViewportPercentage for PropertyDeclaration {
    fn has_viewport_percentage(&self) -> bool {
        match *self {
            // For the properties whose SpecifiedValues can contain lengths,
            // check the SpecifiedValue:
            MarginTop(DeclaredValue::Value(val)) => val.has_viewport_percentage()),
            MarginRight(DeclaredValue::Value(val)) => val.has_viewport_percentage()),
            MarginBottom(DeclaredValue::Value(val)) => val.has_viewport_percentage()),
            MarginLeft(DeclaredValue::Value(val)) => val.has_viewport_percentage()),
            PaddingTop(DeclaredValue::Value(val)) => val.has_viewport_percentage()),
            /// ...etc.

            // For other properties, return false:
            _ => false,
        }
    }
}
```

Fortunately we don't need to write or maintain this giant `match` expression by hand.  Instead, it can be generated by the Mako preprocessor from source code in [properties.mako.rs](https://github.com/servo/servo/blob/df808bed20a097719992f3c355bd164c4abc8913/components/style/properties.mako.rs#L5842-L5848).  This will require adding a new boolean field to the each "longhand" property in the Mako template, specifying whether it implements HasViewportPercentage.

Whew.  I hope that's enough for someone to get started.  Once you've done all that, you will still need to add code in [selector_matching.rs](https://github.com/servo/servo/blob/master/components/style/selector_matching.rs) to flag elements that match rules containing viewport percentages.  I can answer questions about that part when we get there.

**Comment by KiChjang** [comment]
@roysohan Could you confirm that you are currently working on this issue?

**Comment by roysohan** [comment]
I am quite busy, but will try starting to contribute, any hints on which file to start.

Also I am low on bandwidth, so can you suggest how to contribute in low bandwidth condition

I am a college student, and I have exams, I have started learning rust as a hobby, and someone suggested on rust irc channels that I should be contributing to servo for better understanding.
So the problem is I cannot commit myself. I am extremely sorry for that.

But I will contribute little by little. And this is my first time. So I need your guide and support on where to start, how to do, and which files to edit. I think slowly under your guidance I may learn something.

I apologise for not being able to commit myself fully.

**Comment by jdm** [comment]
Note - @roysohan is looking into other issues instead, so this one is still available.

**Comment by Shiroy** [comment]
I'm working on this issue.

If I understand well, the `HasViewportPercentage` trait is used to easily identify which node is currently using a vh/vw unit so we must only dirty these nodes when the viewport size change ?

And dirtying these nodes is done somewhere in [selector_matching.rs](https://github.com/servo/servo/blob/master/components/style/selector_matching.rs) ?

**Comment by mbrubeck** [comment]
> If I understand well, the `HasViewportPercentage` trait is used to easily identify which node is currently using a vh/vw unit so we must only dirty these nodes when the viewport size change ?

Yes.

> And dirtying these nodes is done somewhere in selector_matching.rs ?

During selector matching, either `push_applicable_declarations` or one of the functions that calls it (`style::traversal::recalc_style_at` might be the easiest place to do this) should set a flag on any node whose applicable declarations contain a viewport percentage, or whose parent has the flag set.  This will require adding a new `DIRTY_ON_VIEWPORT_SIZE_CHANGE` flag to the `script::dom::node::NodeFlags` type, and a new method to set this flag in the `style::dom::TNode` trait.  (The new method will be very similar to the `TNode::set_dirty` method.)

Then, finally, in [`LayoutThread::handle_reflow`](https://github.com/servo/servo/blob/master/components/layout/layout_thread.rs#L1068-L1089), instead of marking all nodes as dirty when the viewport size changes, call a new function that only dirties nodes with this new flag.

**Comment by mbrubeck** [comment]
> This will require adding a new `DIRTY_ON_VIEWPORT_SIZE_CHANGE` flag to the `script::dom::node::NodeFlags`…

Note: I’m not sure whether it makes more sense to add this to `NodeFlags` or to somewhere else like `layout::data::LayoutDataFlags`.

**Comment by mbrubeck** [comment]
Also, we should make sure that this speeds up window resizing significantly, and doesn't slow down selector matching too much (especially because selector matching happens much more often than window resizing).

We could do some of this testing before writing any new code, by measuring to see whether adding vh/vw units to a page's stylesheets makes it spend a significant amount more time in style recalc during window resizing.  The built-in profiling option (`--profile 10`) can help answer this.

**Comment by mbrubeck** [comment]
As a simple test I took a static copy of the mozilla.org home page, and profiled resizing the window.  Then I did the same after adding an unused `vw` rule to one of its stylesheets.  As expected, this caused style recalc to run on every resize.  The style recalc type was an average of about 18ms on my laptop, which is a both a large portion of the total layout time and long enough to impact frame rates.

There's still the question of how much we care about frame rate of window resizing, and whether optimizing this particular case is worth the complexity.

**Comment by Shiroy** [comment]
Ok.

I'm still integrating the `HasViewportPercentage` trait. I have some difficulties to identify which type should implement this trait, especially higher level type like : 

```rust
struct A
{
    b : B;
}

struct B
{
    l: Length;
}
```

Both A and B should implement the trait.

I don't know any way to automatically generate the type that should implement the trait. An algorithm would be to generate a type dependency graph and with this graph, print all the type that depend directly or indirectly depend of a `Length'.

I don't know if there is a tool that can already do that.

**Comment by Shiroy** [comment]
@mbrubeck I get this match. Does it look correct ?

```rust
fn has_viewport_percentage(&self) -> bool {
        match *self {
                PropertyDeclaration::MarginTop(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MarginRight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MarginBottom(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MarginLeft(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PaddingTop(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PaddingRight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PaddingBottom(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PaddingLeft(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::OutlineOffset(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Top(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Right(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Bottom(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Left(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Width(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Height(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MinWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MaxWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MinHeight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MaxHeight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::TextIndent(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Perspective(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
        _ => false
        }
    }
```

**Comment by mbrubeck** [comment]
It looks like there might be some missing still, such as BorderTopWidth, OutlineWidth, FontSize, Transform...

> I don't know any way to automatically generate the type that should implement the trait.

I don't know of any existing tools to help with this either, sorry.  Maybe it's possible to write a Rust compiler plugin to do it, but I don't have any experience with that myself.

**Comment by SimonSapin** [comment]
> It looks like there might be some missing still, 

Even if you fix this now, there’s a risk more properties will be added later that would need to be in that `match` but we forget to add them.

So I’d rather have this match have an arm for every single property, without a `_` catch-all pattern (this `match` can be auto-generated by the Mako template), and have some implementations of the trait that simply return `false`.

We can (probably) leave it to the optimizer to inline and simplify all this.

**Comment by Shiroy** [comment]
> (this `match` can be auto-generated by the Mako template)

The `match` I paste above is already generated by Mako.

**Comment by SimonSapin** [comment]
Ok, good. My point remains that I’d prefer to have one arm for every property in this `match`, even if most of them call implementations on the `HasViewportPercentage` trait that always return `false`.

**Comment by Shiroy** [comment]
This is the new match I get :
```rust
impl HasViewportPercentage for PropertyDeclaration {
    fn has_viewport_percentage(&self) -> bool {
        match *self {
                PropertyDeclaration::MarginTop(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MarginRight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MarginBottom(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MarginLeft(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PaddingTop(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PaddingRight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PaddingBottom(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PaddingLeft(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::BorderTopWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::BorderRightWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::BorderBottomWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::BorderLeftWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::OutlineWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::OutlineOffset(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Top(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Right(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Bottom(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Left(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Width(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Height(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MinWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MaxWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MinHeight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::MaxHeight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::LineHeight(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::VerticalAlign(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::BackgroundPosition(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::BackgroundSize(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::FontSize(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::LetterSpacing(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::WordSpacing(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::TextIndent(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::BorderSpacing(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::ColumnWidth(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::ColumnGap(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::BoxShadow(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Clip(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::TextShadow(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Filter(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Transform(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::TransformOrigin(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::Perspective(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
                PropertyDeclaration::PerspectiveOrigin(DeclaredValue::Value(val)) => val.has_viewport_percentage(),
        _ => false
        }
    }
}
```

@SimonSapin if I understand your point, you want the compiler to generate an error if a new property does not implement the trait to make sure that the developer have taken this trait into account when he implemented the property ?

**Comment by SimonSapin** [comment]
@Shiroy Yes, exactly. It should be an explicit choice for every property rather than an implicit default.

Additionally, I’d really rather not add more data to the Mako template if at all possible. The whole thing is a hack that has survived too long. (Generating more code with a Mako `% for` loop based on existing data is fine.)

To reduce the verbosity of many `impl`s that always return `false`, you could instead have a marker trait and a generic `impl` similar to this one in `values.rs`:

```rust
    pub trait ComputedValueAsSpecified {}

    impl<T> ToComputedValue for T where T: ComputedValueAsSpecified + Clone {
        type ComputedValue = T;

        #[inline]
        fn to_computed_value<Cx: TContext>(&self, _context: &Cx) -> T {
            self.clone()
        }
    }
```

**Comment by Shiroy** [comment]
If I understand well this code, `ComputedValueAsSpecified` acts as marker and because of the templated `impl`, the compiler will know that every type which implements this marker trait, will also implement the `ToComputedValue` trait using the `to_computed_value()` provided by the templated  `impl`

**Comment by SimonSapin** [comment]
That’s correct. And I’m suggesting to do something similar with a `NeverHasViewportPercentage` marker trait and `impl<T: HasViewportPercentage> HasViewportPercentage for T { fn has_viewport_percentage(&self) -> bool { false } }` instead of adding more python/Mako parameters in the template.

Long-term we’d like to replace the Mako template with a Rust syntax extension, so any logic that is not there is that much less that will need to be ported.

**Comment by Shiroy** [comment]
I encounter some difficulties to implement that system because of conflicts in trait implementation.

For now I will stay on the current system for benchmarking and I will add the new trait just before submitting the pull request.

**Comment by jdm** [comment]
@Shiroy Have you made progress? Any questions?

**Comment by Shiroy** [comment]
@jdm Not much. It's the mid term exam period and I don't have enough time for servo now. If someone else want the issue, please give it.

I'll come back when I'll have more free time.

**Comment by jdm** [comment]
Ok, just let us know if you start working on this again!

**Comment by shinglyu** [comment]
I'm interested in this.

**Comment by KiChjang** [comment]
Have at it!

**Comment by shinglyu** [comment]
(@shinglyu add to my dashboard)

**Comment by jdm** [comment]
@shinglyu Is this something you're still working on?

**Comment by shinglyu** [comment]
Yes, sorry for the delay

**Comment by shinglyu** [comment]
I already have a rough picture of how to do it, but @Shiroy 's patch does not apply on the latest master, so I have to do it manually.

**Comment by shinglyu** [comment]
Status: I reused part of @Shiroy 's patch, and followed @SimonSapin 's suggestion to create a marker trait for `NoViewportPercentage`. 

https://github.com/shinglyu/servo/commits/viewport-percent-recalc

I'll finish implementing the actual `HasViewportPercentage` trait for properties that may use viewport length, then I'll actually set them and use them in `recalc_style_at`

**Comment by shinglyu** [comment]
I have a patch now: https://github.com/servo/servo/compare/master...shinglyu:viewport-percent-recalc

I still need to do some testing and profiling to make sure it does improve the performance.
