### ISSUE TITLE
browserhtml: need to press delete 2 times to remove single character from address bar

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#10119]
Not sure what happens but a single delete is apparently not sufficient, as if there was some kind of invisible character inserted after every letter.

I tried to capture the bug via screen recording.
![output](https://cloud.githubusercontent.com/assets/476013/13951568/287ab372-f032-11e5-9666-44d7538df12a.gif)

**Comment by paulrouget** [comment]
Dupe: https://github.com/browserhtml/browserhtml/issues/930
