### ISSUE TITLE
Page is half transparent if used with --no-titlebar

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10115]
See also: https://github.com/servo/servo/issues/9877

```html
<style>
  html, body {
    background: white;
  }
  iframe {
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border-width: 0;
    background-color: white;
  }
</style>
<iframe mozbrowser="true" style="">
</iframe>
<script>
  setTimeout(() => document.querySelector("iframe").src = "https://fr-fr.facebook.com/", 1000);
</script>
```

Result:

with `-b`:

<img width="897" alt="screen shot 2016-03-22 at 06 45 37" src="https://cloud.githubusercontent.com/assets/373579/13943136/58606d58-effa-11e5-84de-573b276436ab.png">

without `-b`:

<img width="873" alt="screen shot 2016-03-22 at 06 45 54" src="https://cloud.githubusercontent.com/assets/373579/13943137/5860c37a-effa-11e5-980a-21bb8d1a3807.png">

**Comment by pcwalton** [comment]
I think this is actually a specific manifestation of a texture cache corruption problem in WR that Facebook happens to expose and isn't really related to transparent backgrounds. It's just that it looks particularly bad on a non-opaque window.

**Comment by paulrouget** [comment]
This is fixed now.

**Comment by paulrouget** [comment]
(fixed after wr update)
