### ISSUE TITLE
Catch panics in c-to-rust callbacks

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10116]
SpiderMonkey callbacks in particular: we should recover from the panic, return false, have SM pass the uncatchable exception up its callstack, and propagate it back up on the other side.

http://static.rust-lang.org/doc/master/std/panic/fn.recover.html
http://static.rust-lang.org/doc/master/std/panic/fn.propagate.html

**Comment by jdm** [comment]
See also my ramblings in #6462.

**Comment by jdm** [comment]
Fixed by #11803.
