### ISSUE TITLE
Add a script to shrink test-wpt output to only unexpected results

### ISSUE THREAD

**Issue by nox** [servo/servo#10129]
No idea if this issue should live in saltfs, wpt itself or here.

Cc @metajack.

**Comment by Ms2ger** [comment]
I imagine we'd want a separate kind of logger; cc @jgraham

**Comment by jgraham** [comment]
Yeah, you would want to implement a mozlog formatter.

Not having an easy way to tell if a test ran at all, or see log output, seems rather problematic though. My suspicion is that whatever the use case here is, you're trying to solve the wrong problem.

**Comment by nox** [comment]
@jgraham https://github.com/servo/servo/wiki/Meeting-2016-03-21#automating-failureintermittent-finding

**Comment by jgraham** [comment]
So it seems like you might just want `--log-errorsummary=<file>`. That produces a line-by-line json view of only the test failures and critical/error level log messages. It's not ideal for humans but is the right thing to use if you're implementing a bot (it's what treeherder uses for autoclassification, for example)

**Comment by nox** [comment]
Is that usable to update expectations too?

**Comment by jgraham** [comment]
No, you still need the raw log for that. Although conceivably someone could perhaps implement log updating based on the error summary in the future.

**Comment by nox** [comment]
And does it include unexpected PASS?

**Comment by jgraham** [comment]
Yes (this conversation would maybe be shorter on irc, or by pointing you at https://dxr.mozilla.org/mozilla-central/source/testing/mozbase/mozlog/mozlog/formatters/errorsummary.py )

**Comment by jgraham** [comment]
(sorry "test failures" was very lax language. I meant "unexpected test results")

**Comment by nox** [comment]
Cc @mateon1 who is doing a lot of fuzzing and shrinking.

**Comment by nox** [comment]
Never mind, I can't read.

**Comment by nox** [comment]
This was more or less done, with @jdm's intermittent stuff. Closing.
