### ISSUE TITLE
rust.png in reftests is missing

### ISSUE THREAD

**Issue by jdm** [servo/servo#10128]
It's used in inline_margin_multiple_fragments_a.html and filter_inline_a.html but it's 404. We should replace references to it with one of the other images in http://mxr.mozilla.org/servo/source/tests/wpt/mozilla/tests/css/ .

**Comment by jdm** [comment]
`./mach test-wpt tests/wpt/mozilla/tests/css/inline_margin_multiple_fragments_a.html`

**Comment by jrasanen** [comment]
Hi,

why doesn't `./mach test-wpt tests/wpt/mozilla/tests/css/inline_margin_multiple_fragments_a.html` fail if its 404? I replaced the image with an existing one but the test gives no indication whether its 200 or 404.

Thanks!

**Comment by jdm** [comment]
filter_inline_a.html still needs to be addressed.

**Comment by jrasanen** [comment]
Fixing

**Comment by jrasanen** [comment]
Opened pull request #10146
