### ISSUE TITLE
Document::location should be null for documents without a browsing context.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10141]
Blocks #2968.

* Spec: <https://html.spec.whatwg.org/multipage/#dom-document-location>.
* Code: `components/script/dom/document.rs` and `components/script/dom/webidls/Document.webidl`.
* Test: `html/browsers/history/the-location-interface/document_location.html`.

**Comment by jdm** [comment]
Cc @slayerjain

**Comment by stjepang** [comment]
I'll take this one.

**Comment by jdm** [comment]
Blocking this off for @slayerjain, sorry.

**Comment by slayerjain** [comment]
@jdm thank you so much for this! :)

**Comment by slayerjain** [comment]
I'm finally done with my little vacation thingy :) . must i edit this file as well : components/script/dom/webidls/Document.webidl ?
