### ISSUE TITLE
Implement CORS preflight fetch concept

### ISSUE THREAD

**Issue by jdm** [servo/servo#10145]
Code: `components/net/fetch/methods.rs` (see `preflight_fetch` function)
Spec: https://fetch.spec.whatwg.org/#cors-preflight-fetch
Tests: need to be written in `tests/unit/net/fetch.rs` (`./mach test-unit -p net`)

The spec looks long, but the building blocks necessary should be present in that file already.

**Comment by jdm** [comment]
Apparently @KiChjang is working on this already.

**Comment by KiChjang** [comment]
Sorry! I've started working on this already on a local branch.
