### ISSUE TITLE
Scheme check for local_urls_only is backwards

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10147]
Step 2 in `main_fetch`; should find some way to test it.

**Comment by jdm** [comment]
Looks like testing it involves setting the `local_urls_only` flag in Request to true and writing a unit test. I haven't found the actual specification that does that yet.

Code: `components/net/fetch/methods.rs`
Tests: `tests/unit/net/fetch.rs` (`./mach test-unit -p net`)
Spec: https://fetch.spec.whatwg.org/#dfnReturnLink-0

**Comment by Ms2ger** [comment]
> what's the "local-URLs-only flag" for?

> CSS/SVG
> they haven't really defined their fetching model yet, though, but this is what I think they'll need to define "SVG as image" and "SVG as gradient" and such
> although maybe they're a little closer now, but nothing to the level of detail I'd like

**Comment by stjepang** [comment]
I'll take this issue.
