### ISSUE TITLE
Need a mapping from document's stylesheets to owner nodes

### ISSUE THREAD

**Issue by jdm** [servo/servo#10143]
There are a few choices I can think of:
* a second vector in Document that is kept in sync with the `stylesheets` vector
* Each `Stylesheet` object contains a reference to the node (either via `Trusted` types or a weak reference; not sure)

This will be necessary for later steps for #10133.

**Comment by Ms2ger** [comment]
Another option:

* The `stylesheets` field stores `(JS<Node>, Arc<Stylesheet>)` in the vector

**Comment by jdm** [comment]
I like that a lot better.

**Comment by ConnorGBrewster** [comment]
I am currently working on this

**Comment by SimonSapin** [comment]
CC @tschneidereit

**Comment by tschneidereit** [comment]
What I did in my explorations around this was store `CSSStyleSheet`s on the
document and have the connection be through `StyleSheet`s `owner_node`:
https://github.com/tschneidereit/servo/tree/cssom

I'm not sure this is the best approach, though, what @Ms2ger proposes might
make more sense.

**Comment by timvandermeij** [comment]
Fixed by #10202?

**Comment by jdm** [comment]
Yep!
