### ISSUE TITLE
Bad GIF rendering

### ISSUE THREAD

**Issue by mrjbq7** [servo/servo#10153]
The header GIF on this page:

http://aggregate.org/MAGIC/

A direct URL is here:

http://aggregate.org/IMG/ukwidesig.gif

This screenshot shows Google Chrome (above) with Servo (below):

<img width="633" alt="weird_gif" src="https://cloud.githubusercontent.com/assets/24195/13993924/ae61e62e-f0df-11e5-84f3-d8b5e9275b1a.png">

Using `./mach run http://aggregate.org/MAGIC/` on OS X 10.11.

**Comment by jdm** [comment]
@mrjbq7 Is this using webrender or without?

**Comment by mrjbq7** [comment]
Dev build of master (b59bd294e177d84a2f54cec987f76a5fb97365f1) just now.  Not sure how to tell...?

**Comment by jdm** [comment]
@mrjbq7 Did you use the `-w` flag?

**Comment by mrjbq7** [comment]
No.

**Comment by mrjbq7** [comment]
@jdm ``./mach run -w http://aggregate.org/MAGIC/`` has the same problem.

**Comment by blacksvk** [comment]
I found more gifs relevant to this issue. They are rendered wrong in servo.
http://siemensmania.cz/images/phones/cfx65.gif
http://siemensmania.cz/images/phones/a65.gif
https://www.pcforum.sk/styles/white/imageset/sticky_read_locked.gif
https://www.pcforum.sk/styles/white/imageset/announce_read_locked.gif

**Comment by philipc** [comment]
This requires interlace support for gifs, reported as https://github.com/PistonDevelopers/image-gif/issues/25

**Comment by nox** [comment]
I can't reproduce this anymore.
