### ISSUE TITLE
Webrender doesn't clip overflowing transformed content

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10164]
<img width="454" alt="screen shot 2016-03-24 at 10 02 31" src="https://cloud.githubusercontent.com/assets/373579/14012688/a7de134a-f1a7-11e5-8dbd-1e3ea48e2ae7.png">

```html
<style>
  .red {
    width: 200px;
    height: 200px;
    overflow: hidden;
    transform: scale(0.5);
    background: red;
  }
  .green {
    height: 100px;
    width: 200px;
    transform: translateX(-100px);
    background-color: green;
  }
</style>

<div class="red">
  <div class="green"></div>
</div>
```

**Comment by paulrouget** [comment]
Now, with the latest WR, the test case looks like this:

<img width="182" alt="screen shot 2016-03-31 at 09 53 29" src="https://cloud.githubusercontent.com/assets/373579/14169177/99d9238c-f726-11e5-9762-b2bc032bbb61.png">

… but the actual bug in browserhtml is fixed (progressbar not being clipped).

**Comment by mbrubeck** [comment]
This seems to be fixed on master.
