### ISSUE TITLE
Can't set preferences to false in WPT tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#10161]
The syntax is `prefs: [name:value]`, but all the WPT test harness does is pass `--pref name` to Servo as a command line argument. We should probably support a `--pref name=value` syntax to allow this.

**Comment by jdm** [comment]
Code: `components/util/opts.rs` and `tests/wpt/harness/wptrunner/executors/executorservo.py`.

**Comment by awalGarg** [comment]
I'd like to work on this! :)

**Comment by awalGarg** [comment]
@jdm here are my changes as per our discussion in IRC: https://github.com/servo/servo/compare/master...awalGarg:fix10161

the current test just sets `dom.mozbrowser.enabled` to `false`, but `resources/prefs.json` already sets it to false. if I locally toggle the preference in `resources/prefs.json`, I can see the test passing and failing so I can confirm that this working, but I am not sure how to show that in the test. Is there any other preference which defaults to `true`? All the boolean preferences in prefs.json in current master are set to false only.

**Comment by jdm** [comment]
You can see all the default preference values in prefs.json. I think it's best to create a new `dom.testbinding.preference_value.true` preference.

**Comment by awalGarg** [comment]
@jdm done and PR'd. Thanks!
