### ISSUE TITLE
Implement fetching file URLs

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10166]
Code: `components/net/fetch/methods.rs`.
Spec: <https://fetch.spec.whatwg.org/#concept-basic-fetch>.

**Comment by dagnir** [comment]
I'd like to work on this

**Comment by dagnir** [comment]
I might have spoken to soon.  I didn't see that "file" is unspecified >.<.  I probably don't have enough exp for this

**Comment by jdm** [comment]
In this case it would require replicating the existing behaviour in file_loader.rs.

**Comment by awalGarg** [comment]
I'd like to take this one!

**Comment by jdm** [comment]
Great!

**Comment by jdm** [comment]
@awalGarg Any progress? Are you still working on this?
