### ISSUE TITLE
Annotate test failures with bugs

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10172]
It would be useful to annotate the `.ini` files with `bug` fields to track the issue we have for them. If there is no issue yet, we should investigate what's causing the failure and file an issue.

Reserved for @GuillaumeGomez.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by nox** [comment]
Not really actionable. We already do that, and this issue isn't going to make us remember it if we forget.
