### ISSUE TITLE
Create an HTTP global state object

### ISSUE THREAD

**Issue by jdm** [servo/servo#10175]
We pass around stuff like the cookie storage, the HSTS list, the HTTP authentication cache, etc. in `http_loader.rs`. This also means that the unit tests have a lot of repeated initialization code that creates these objects even when they're not used. I propose we wrap them up in a struct and give it a argument-less constructor to make reading the code easier and require fewer changes when adding additional global HTTP state.

Code: `components/net/http_loader.rs`, `components/net/resource_thread.rs`, `tests/unit/net/http_loader.rs`

**Comment by notriddle** [comment]
You would still be passing around that one object, right?

**Comment by jdm** [comment]
Yes.

**Comment by ConnorGBrewster** [comment]
Should this state object include things like `LoadData`, or only things that can be initialized without any parameters?

**Comment by jdm** [comment]
LoadData is a per-request object, so it would not be included.

**Comment by ConnorGBrewster** [comment]
@jdm ok makes sense, currently I have:
```
hsts_list
cookie_jar
auth_cache
```
included in the http global state object, should anything else be included/excluded?

**Comment by ConnorGBrewster** [comment]
Issue resolved in PR #10188.
