### ISSUE TITLE
Browser.html integration breaks ability to build non-head Servo

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#10170]
In #9873, we added a git dependency on a branch in browserhtml that is force-pushed over every time they publish a new version. This setup means that if you build a non-head version of Servo, you get:
`Unable to update https://github.com/browserhtml/browserhtml?branch=gh-pages#120c8113`

We need to either back this out or find another way to bring in browserhtml - our repo history is totally broken by this change.

CC @metajack @Ms2ger

**Comment by metajack** [comment]
@gozala Can you switch the bhtml side to push new revisions instead of force pushing over them?

**Comment by paulrouget** [comment]
We need to change our deploy script. I'd suggest that:

1) before `npm build`: `mkdir dist`, `git clone gh-pages dist`, `rm -r dist/*` (that won't delete `.git`)
2) after build: `git add -A`, `git commit` …
3) remove `--force`

**Comment by perlun** [comment]
Should be closable by now, since it's fixed in browserhtml.
