### ISSUE TITLE
Rename style struct types to eliminate the T

### ISSUE THREAD

**Issue by bholley** [servo/servo#10185]
See discussion here [1].

This has a few steps. Each one should occur in a separate commit that builds, so that we're sure that we got it right. Each step should build on both servo (./mach build) and geckolib (./mach build-geckolib).

(1) Rename struct ComputedValues in components/style/properties.mako.rs to ServoComputedValues.
(2) Rename trait TComputedValues in components/style/properties.mako.rs to ComputedValues.
(3) Rename all the style structs in components/style/properties.mako.rs from Foo to ServoFoo. See [2].
(4) Rename all the style struct traits in components/style/properties.mako.rs from TFoo to Foo. See [3].

[1] https://github.com/servo/servo/pull/10155/#issuecomment-200944103
[2] https://github.com/servo/servo/blob/5c749127cc4e56a89ceb19f2cbe44693cedd4eba/components/style/properties.mako.rs#L6124
[3] https://github.com/servo/servo/blob/5c749127cc4e56a89ceb19f2cbe44693cedd4eba/components/style/properties.mako.rs#L6069

**Comment by bholley** [comment]
CC @SimonSapin

**Comment by perlun** [comment]
Looking into this now, have read the initial thread as well., Should be `ComputedValuesMap` also be renamed, or retained as-is?

**Comment by SimonSapin** [comment]
I’m the one who suggested the `ServoFoo` pattern, but I see in #10210 that it affects a lot more than I anticipated. (I made a remark in passing and didn’t really think this through.) Would it work to avoid adding that prefix everywhere? Maybe use modules when names would otherwise collide?

Sorry I’m being capricious :]

**Comment by bholley** [comment]
I think we should just add the prefix. We already did it for ServoLayoutNode, ServoLayoutDocument, ServoThreadSafe*, ServoSelectorImpl, etc. Using modules is a pain because there are tons of |use| statements for ComputedValues, which makes it nontrivial to get right.

#10210 actually looks less disruptive than I thought, TBH. ;-)

**Comment by nox** [comment]
@bholley What is the prefixing needed btw? For example rust-selectors defines an Element and we do too, and there is no problem.

**Comment by bholley** [comment]
> For example rust-selectors defines an Element and we do too, and there is no problem.

There is a problem, because this is exactly what caused style::dom::TElement to have a "T" in its name. :-P

Namespacing works great as a general tool to avoid naming collisions between unrelated things, but it's a pain for types that are frequently used throughout the same code, because you can't |use| the types. So you end up needing to prefix everything with the module name as well as |::|, which is more crud than if you'd just given type types different names. And then you still can't easily grep for them across multiple files, some of which |use| and others of which qualify.

Moreover, the confusion is extra-strong in this case because these types are used throughout properties.mako.rs (both within style and geckolib), where the code-generation makes it extra-difficult to figure out which of the 3 things |ComputedValues| refers to in your scope.

Simple naming and text-processing have a lot of value, especially for people unfamiliar with the code and/or the language.

**Comment by perlun** [comment]
> Simple naming and text-processing have a lot of value, especially for people unfamiliar with the code and/or the language.

I agree, qualifying in both categories (unfamiliar with the code base as well as the language). :wink:

**Comment by SimonSapin** [comment]
Alright. These are good points, I retract my comment above.

**Comment by nox** [comment]
> Namespacing works great as a general tool to avoid naming collisions between unrelated things, but it's a pain for types that are frequently used throughout the same code, because you can't |use| the types. So you end up needing to prefix everything with the module name as well as |::|, which is more crud than if you'd just given type types different names. And then you still can't easily grep for them across multiple files, some of which |use| and others of which qualify.

You can `use as` though.

**Comment by bholley** [comment]
> You can use as though.

That's true, but that effectively pushes the burden of renaming onto the consumer. It might make sense if there were just one or two files that needed both types, but basically every consumer in this case needs to import both the struct and the trait.

**Comment by Wafflespeanut** [comment]
fixed by #10210, #10277, #10324, #10488

**Comment by perlun** [comment]
Thanks @Wafflespeanut for cleaning up!
