### ISSUE TITLE
Publish the CSS support list during doc builds

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#10196]
In #9333, a script was added that prints out all of the properties support by Servo as JSON. In this project, we would edit the file https://github.com/servo/servo/blob/master/etc/ci/upload_docs.sh to run that script (via `python components/style/list_properties.py`) and store the output as a JSON file in the documentation tree so that it is uploaded after each build lands in master.

For extra brownie bonus points, adding a HTML file with some nice CSS styles to display that list to the https://github.com/servo/servo/tree/master/etc/doc.servo.org directory would be a really nice bonus! We could then link to that directly from servo.org.

This would fully close #3954.

**Comment by larsbergstrom** [comment]
cc @SimonSapin

**Comment by jrasanen** [comment]
@larsbergstrom so:

1. Save the JSON of supported properties to ./target/doc/servo/ in upload_docs.sh
2. Create ./etc/doc.servo.org/properties.html which reads the json file and outputs supported properties nicely


I could do this one.

**Comment by larsbergstrom** [comment]
@jrasanen That sounds like a great plan! Please let us know here if you have any questions :-)

**Comment by SimonSapin** [comment]
It’s also possible to generate static HTML at the same time as we generate JSON. There’s even a templating system (Mako) originally designed to generate HTML already being used in the relevant script.

**Comment by jrasanen** [comment]
@SimonSapin thanks, noted! I've used Mako before so will look into that.

**Comment by jrasanen** [comment]
Added a PR. Ping @larsbergstrom & @SimonSapin
