### ISSUE TITLE
Text is not displayed properly

### ISSUE THREAD

**Issue by Shiroy** [servo/servo#10207]
On this website, text display is a mess.

![site](https://cloud.githubusercontent.com/assets/1006143/14061981/68ec8fa6-f38f-11e5-9195-db24879c4f0a.png)

The source code of the page is here : https://gist.github.com/Shiroy/d2ddfbe46d9bfcfd9d5b
It should run as is. If not, please let me know and I will upload a tar with the assets.

**Comment by nox** [comment]
The text is ok now, but I encountered #18689. Closing this issue.
