### ISSUE TITLE
Implement insertAdjacentElement and insertAdjacentText

### ISSUE THREAD

**Issue by nox** [servo/servo#10205]
https://dom.spec.whatwg.org/#dom-element-insertadjacentelement
https://dom.spec.whatwg.org/#dom-element-insertadjacenttext

Files:
 * components/script/dom/element.rs
 * components/script/webidls/Element.webidl

**Comment by nox** [comment]
@GuillaumeGomez and @Michelangelo both wanted an easy bug, so I filed that for them.

The first one to actually start working on it gets it, the other one gets the right to harass me until I find a second ticket. Cheers!

**Comment by GuillaumeGomez** [comment]
I start working on it.

**Comment by nox** [comment]
Great! Ping me on IRC if you need help.
