### ISSUE TITLE
Implement WebGLRenderingContext.flush()

### ISSUE THREAD

**Issue by emilio** [servo/servo#10213]
See the [general info for WebGL bugs](https://github.com/servo/servo/issues/10209#user-content-general-info) to see the spec and get a grasp how the code is structured.

You should uncomment the corresponding function in [`WebGLRenderingContext.webidl`](https://github.com/servo/servo/blob/master/components/script/dom/webidls/WebGLRenderingContext.webidl#L560), and implement it in `components/script/dom/webglrenderingcontext.rs`.

A new `WebGLCommand` variant called `Flush` should be created at:
 * https://github.com/servo/webrender_traits/blob/master/src/webgl.rs#L48

It's implementation in the `apply()` function should be something in the lines of:

```rust
Flush => gl::flush(),
```

**Comment by ConnorGBrewster** [comment]
I am working on this.

**Comment by emilio** [comment]
Fixed by https://github.com/servo/servo/issues/10215
