### ISSUE TITLE
Stop re-exporting webrender_traits WebGL types from canvas_traits

### ISSUE THREAD

**Issue by emilio** [servo/servo#10211]
Right now we [re-export](https://github.com/servo/servo/blob/master/components/canvas_traits/lib.rs#L40-L41) from `canvas_traits` the `webrender_traits` type `WebGLCommand` as `CanvasWebGLMessage`, and another `webrender_traits` types as well.

This was done during webrender development to avoid extra rebase pain, but webrender has landed a while ago.

We should remove that re-export, and use those types from `webrender_traits` whenever possible.

Code:
 * [`components/canvas_traits/lib.rs`](https://github.com/servo/servo/blob/master/components/canvas_traits/lib.rs#L40-L41)

**Comment by jfhumann** [comment]
I'd like to work on this.

**Comment by emilio** [comment]
It's yours!

Ping me here or on irc (`emiliocobos`) if you have any doubts :)

**Comment by ConnorGBrewster** [comment]
This is fixed in #10291.

**Comment by emilio** [comment]
True, thanks for the heads up!
