### ISSUE TITLE
Implement WebGLRenderingContext.finish()

### ISSUE THREAD

**Issue by emilio** [servo/servo#10212]
This should be a straight-forward WebGL command to implement.

See the [general info for WebGL bugs](https://github.com/servo/servo/issues/10209#user-content-general-info) to see the spec and get a grasp how the code is structured.

You should uncomment the corresponding function in [`WebGLRenderingContext.webidl`](https://github.com/servo/servo/blob/master/components/script/dom/webidls/WebGLRenderingContext.webidl#L559), and implement it in `components/script/dom/webglrenderingcontext.rs`.

`glFinish()` is an synchronous call, so we should wait for the WebGL thread to return. We already do this in some other functions, like [`DrawingBufferWidth`](https://github.com/servo/servo/blob/master/components/script/dom/webglrenderingcontext.rs#L185), creating an IPC channel.

A new `WebGLCommand` variant called `Finish(IpcSender<()>)` should be created at:
 * https://github.com/servo/webrender_traits/blob/master/src/webgl.rs#L48

It's implementation in the `apply()` function should be something in the lines of:

```rust
Finish(sender) => { gl::finish(); sender.send(()); }
```

(you might want to create an auxiliary function if you prefer, to keep the code uniform).

**Comment by ConnorGBrewster** [comment]
I am working on this.

**Comment by emilio** [comment]
Cool, it's yours!

Let me know it I can help you with anything :)

**Comment by emilio** [comment]
Fixed by https://github.com/servo/servo/issues/10215
