### ISSUE TITLE
Implement WebGLRenderingContext.detachShader()

### ISSUE THREAD

**Issue by emilio** [servo/servo#10216]
This WebGL command will be a bit harder to implement.

See the [general info for WebGL bugs](https://github.com/servo/servo/issues/10209#user-content-general-info) to see the spec and get a grasp how the code is structured.

You should uncomment the corresponding function in [`WebGLRenderingContext.webidl`](https://github.com/servo/servo/blob/master/components/script/dom/webidls/WebGLRenderingContext.webidl#L551), and implement it in `components/script/dom/webglrenderingcontext.rs`.

The function should look similar to `AttachShader`, and the validation should similar to that done in `WebGLProgram::attach_shader` (just in inverse order).

The GLES 2.0 spec for `glAttachShader` can be found here:
 * https://www.khronos.org/opengles/sdk/docs/man/xhtml/glAttachShader.xml

A new `WebGLCommand` variant called `DetachShader(u32, u32)` should be created at:
 * https://github.com/servo/webrender_traits/blob/master/src/webgl.rs#L48

It's implementation in the `apply()` function should be similar to the one of `AttachShader`.

**Comment by ConnorGBrewster** [comment]
I would like to work on this

**Comment by emilio** [comment]
Sure, it's yours! :)

**Comment by ConnorGBrewster** [comment]
When checking to make sure it is valid to detach the shader, do we need to check if the shader passed in is the one currently stored in the `fragment_shader` or `vertex_shader` slots?

**Comment by ConnorGBrewster** [comment]
Implemented in #10215

**Comment by emilio** [comment]
Yup! That's true! :)
