### ISSUE TITLE
Can't set string preferences that contain equals signs from the command line

### ISSUE THREAD

**Issue by jdm** [servo/servo#10220]
The code added in #10204 splits the `name=value` syntax on the = sign. This will truncate the preference value if it contains an equals sign (`--pref name=some=value`). We can make an automated test for this by adding a similar API to TestBinding that returns the string value of a given preference.

Code: `components/utils/prefs.rs`

**Comment by awalGarg** [comment]
> This will truncate the preference value if it contains an equals sign

nope. @Manishearth spotted that and I switched it to use `splitn` instead, so it would split only on the first `=`. So `name=some=value` would be split as `[name, some=value]`. https://github.com/servo/servo/blob/master/components/util/opts.rs#L797

But adding the string version of the API still holds, I guess.

**Comment by jdm** [comment]
Whoops, looks like I should have read closer.
