### ISSUE TITLE
WebRender atlas corruption (missing letters on github.com).

### ISSUE THREAD

**Issue by eddyb** [servo/servo#10228]
After scrolling a bit on the GitHub landing page, I ended up in this state:
![image](https://cloud.githubusercontent.com/assets/77424/14067977/a68d94a6-f47d-11e5-9644-89e64721683a.png)

I don't know what to make of it, other than the obvious missing letters and right side looking like a portion of the atlas - you can see at the bottom, the hamburger and magnifying glass icons, from browser.html.

**Comment by Manishearth** [comment]
cc @glennw @pcwalton 

I've sometimes seen similar font atlasing issues on browser.html, where strings like "Google" become "Goog e" in the browser.html url bar

**Comment by jdm** [comment]
Might be related to #10020.

**Comment by Manishearth** [comment]
This is google. I can't find the broken atlas pieces on the page though; so it might not be the same bug.

![screenshot from 2016-04-01 11 50 24](https://cloud.githubusercontent.com/assets/1617736/14199229/26d115f4-f800-11e5-8ea6-3f5c36b6f208.png)

**Comment by paulrouget** [comment]
Maybe https://github.com/servo/webrender/pull/253 improved the situation (at least for the weird gradients).

**Comment by Manishearth** [comment]
Still occurs with patch applied

**Comment by Manishearth** [comment]
Typing two ls results in a single darker l coming up. I suspect that the offset is just a bit off (and kerning in the two-l case makes it shift back a bit)

**Comment by nox** [comment]
I can't reproduce this anymore.
