### ISSUE TITLE
Implement WebGLRenderingContext.generateMipmap()

### ISSUE THREAD

**Issue by emilio** [servo/servo#10226]

**Comment by ConnorGBrewster** [comment]
I am working on this.

**Comment by ConnorGBrewster** [comment]
Currently it looks like WebGLTexture will need quite a bit of additions to fully support this. In the spec there are conditions that are checked such as perfect square dimensions, proper formatting, etc...; however, there is currently no place where that data is stored. Looking at Gecko, they have a `ImageInfo` class to store this data.

**Comment by emilio** [comment]
@ConnorGBrewster: 

> It looks like generateMipmap will require significant additions to WebGLTexture. Mainly, to check the requirements for the texture before generating mipmaps, there needs to be a way to get info about the texture such as width and height. It looks like Gecko has a ImageInfo class. Should I implement it similar to how Gecko has it implemented?

Well, probably we don't need such a big ammount of complexity for now (Gecko has texture generation from video and a lot of other WebGL 2 stuff that we don't care about in the near term).

I think our textures are mostly inmutable right now, and can be generated either from images or canvases, or through `createTexture()`.

I *think* for now it'd be easier to store the data directly inside the `WebGLTexture` object, and if we should move that data (and just that data) around we could make the switch to a different struct later.

**Comment by ConnorGBrewster** [comment]
@emilio I might have to move the image info to a struct because each layer/face of the 3d texture has its own set of image info. This requires storing the data in an array, and I think it would be cleaner to move the data to a struct due to this.

**Comment by emilio** [comment]
@ConnorGBrewster I see, go for it then!

**Comment by emilio** [comment]
Closed by https://github.com/servo/servo/pull/10215
