### ISSUE TITLE
Hackernews (webrender) - missing letters in the bottom navigation links

### ISSUE THREAD

**Issue by bobthekingofegypt** [servo/servo#10233]
The navigation links at the bottom of hackernews have missing letters when viewed with webrender enabled.  This is consistent behaviour, the same letters are missing each time I have tried.  No issue without -w flag.

```
./mach run -r -- -w  https://news.ycombinator.com
```

_servo on top, chrome below_
![hacker-news-missing-letters](https://cloud.githubusercontent.com/assets/332141/14076448/a47dcd78-f4d9-11e5-8cea-b13caae195d1.png)

**Comment by paulrouget** [comment]
Do you think you could reduce that to a simpler test case? See https://github.com/servo/servo/wiki/WebCompatBug

Thank you!

**Comment by bobthekingofegypt** [comment]
Sure

```html
<style>
body  { font-family:Verdana, Geneva, sans-serif; font-size:10pt; }
</style>
<center>
  Guidelines
</center>
```

Works fine if you use px, em, rem.  Guidelines is missing the 'i' if you use pt.

**Comment by jdm** [comment]
This may be related to #10228.

**Comment by mrobinson** [comment]
I'm not seeing this any longer. Can anyone confirm this is still an issue?

**Comment by paulrouget** [comment]
Can't reproduce either.
