### ISSUE TITLE
pointer cursor not displayed when mouse is over links

### ISSUE THREAD

**Issue by bobthekingofegypt** [servo/servo#10236]
Servo doesn't appear to implement cursor: pointer; (or any of the other weird ones http://www.w3schools.com/cssref/pr_class_cursor.asp).

This is visible on hackernews, reddit and other sites with links.  Hover over any link in chrome and firefox and you will see the pointer icon, but nothing in servo.  Problematic especially on hackernews where there is no other visual feedback that main headings are links.

```html
<style>
  a {
    cursor: pointer;
  }

  div {
    background-color: #000;
    height: 100px;
    width: 100px;
    cursor: pointer;
  }
</style>
<a href="http://google.com">this is a test</a>
<div>so is this</div>
```

**Comment by paulrouget** [comment]
That works for me (osx).

Which OS? With or without webrender? With or without browserhtml?

**Comment by frewsxcv** [comment]
Sorta similar: https://github.com/servo/servo/issues/9084

**Comment by bobthekingofegypt** [comment]
@paulrouget I keep leaving off the bit of information you want.

OS - Linux
happens with webrender and without, with browserhtml using webrender and without.

**Comment by blacksvk** [comment]
On Windows 8.1 x64 some of the cursors are working and others are not. This is good testpage: http://elektronotdienst-nuernberg.de/bugs/cursor.html

Cursors that are not working on Windows 8.1 x64 : move, ne-resize, nw-resize, se-resize, sw-resize, alias, cell, copy, none, vertical-text, all-scroll, nwsw-resize, nwse-resize, zoom-in, zoom-out.

Also custom pointer (in cur, png or gif format) are not working

**Comment by est31** [comment]
Now that https://github.com/servo/glutin/pull/83 is merged, can you check again?

If it still doesn't work: can you try the cursors example from https://github.com/tomaka/glutin/ and check whether all cursors match? Then we know whether its an upstream bug or not.

**Comment by bobthekingofegypt** [comment]
@est31 Pointer cursor is now working fine for me with latest master.
