### ISSUE TITLE
Hackernews - input elements inherit parent containers alignment

### ISSUE THREAD

**Issue by bobthekingofegypt** [servo/servo#10234]
This isn't specific to hacker news in anyway, not sure if I should just not use the sites name in the title or not but anyway.

If you put an input box inside a container with text-alignment on it then servo will apply that alignment to the content of the input box.

![hn-input-align](https://cloud.githubusercontent.com/assets/332141/14077615/37b7d97a-f4e5-11e5-846f-e8eb6061cf51.png)

*chrome, firefox and then servo*
![input-align](https://cloud.githubusercontent.com/assets/332141/14077620/3f9c2218-f4e5-11e5-9f4a-daa0ac9abcea.png)

Test case
```html
<style>
  div { text-align: center; }
</style>
<div><input value="banana" /></div>
```

**Comment by jdm** [comment]
Should be an easy fix - add a rule to `resources/servo.css` that sets the text alignment to left for `input` elements (and bonus points for setting it to the right using the `:dir(rtl)` selector).

**Comment by canaltinova** [comment]
I would like to work on this issue.

**Comment by jdm** [comment]
@canaltinova Go for it!
