### ISSUE TITLE
regression: layout issue since b29719e

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10237]
Regression: https://github.com/servo/servo/pull/10085/commits/b29719e36bdf2867b1391bbc3b017675975e27ae

Affects browerhtml.

test case:
```html
<style>
  .red {
    left: 50%;
    position: absolute;
    top: 40px;
    width: 480px;
    margin-left: -240px;
    background: red;
  }
  .green {
    display: block;
    width: 410px;
    height: 34px;
    line-height: 34px;
    background: green;
    border: none
  }
</style>

<div class="red">
  <input class="green">
</div>
```

Screenshot:

<img width="527" alt="qofzqxo" src="https://cloud.githubusercontent.com/assets/373579/14077986/1d84b4ee-f4f2-11e5-85e7-24453f01b45c.png">

**Comment by pcwalton** [comment]
Well, this is strange, because there are neither block formatting contexts nor floats here.

**Comment by pcwalton** [comment]
This is because the float speculation doesn't defend against negative inline margins. I have a fix.
