### ISSUE TITLE
Webrender - can't scroll up after reaching the bottom of the page

### ISSUE THREAD

**Issue by bobthekingofegypt** [servo/servo#10235]
If I load up a page I can scroll up and down fine using the mouse wheel.  But if I run with -w I can scroll fine until I hit the bottom of the page.  Once I've hit the bottom of the page I cannot scroll back up again, works fine without webrender.

Reproduced using hackernews, reddit, anything I've tried.

OS is linux, standard X setup for mouse.  Not sure what other info I can give for this one.

**Comment by admshao** [comment]
same for me

**Comment by mmatyas** [comment]
Happens to me too, scrolling works fine until you reach the bottom of the page.

**Comment by frewsxcv** [comment]
Fixed by https://github.com/servo/webrender/pull/264
