### ISSUE TITLE
Implement CSS Transition Events (transitionend)

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#10245]
https://drafts.csswg.org/css-transitions/#transition-events

Aside from web compatibility, this is also important for writing reliable automated tests that use transitions.

**Comment by saurvs** [comment]
I'm working on this.

**Comment by jdm** [comment]
For what it's worth, places to start looking for the actual transition-related code:
* https://github.com/servo/servo/blob/a9eb08dbaa5a9f394aa6c3e563796658826a83b3/components/style/matching.rs#L451 seems to be code that deals with determining if an animation is finished
* we would need to add a way to send messages to the script thread (maybe like the `animations_sender` member of `SharedStyleContext`) with a pipeline, node, and event type - this message would cause a new event of the desired type to be dispatched at the target node that is inside the document associated with the given pipeline

**Comment by saurvs** [comment]
The spec says that only the completion of a css transition generates a corresponding dom event.

**Comment by jdm** [comment]
Unassigning under the assumption that this is not being worked on given the lack of response in #10393.

**Comment by jdm** [comment]
@saurvs indicated that they're continuing to work on this.

**Comment by KiChjang** [comment]
@saurvs Is this still being worked on?

**Comment by saurvs** [comment]
@KiChjang I was busy for a while. I'd like to finish it now.

**Comment by KiChjang** [comment]
@saurvs What's the status of this?

**Comment by saurvs** [comment]
@KiChjang Sorry, I'd couldn't figure out the surrounding code for sending the event, and can't make progress. I hope my code about the DOM of the transition event https://github.com/servo/servo/pull/10393 is useful.
