### ISSUE TITLE
Image with border radius 50% is not circle

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#10258]
Tested on Windows 8.1 x64. Test html: http://testujem.eu/servo/circle-image.html

![circle](https://cloud.githubusercontent.com/assets/10187350/14101329/215b152a-f594-11e5-8a7b-fd60320784d4.png)

**Comment by notriddle** [comment]
Actually, if you replace the `width:100%;height:100%` with `width:144px;height:144px`, Servo renders it correctly. The bug is with percentage calculation.

**Comment by notriddle** [comment]
p.s. Before I start working on an actual fix, could I have this assigned?
