### ISSUE TITLE
Curved border looks pixelated, not anti-aliased

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#10259]
Tested on Window 8.1 x64. Test html: http://testujem.eu/servo/circle-image.html
Comparison with Firefox 45:
![border1](https://cloud.githubusercontent.com/assets/10187350/14101512/49c71dfa-f595-11e5-898d-f5335ec2e767.png)
500% zoomed:
![border2](https://cloud.githubusercontent.com/assets/10187350/14101519/5372cbba-f595-11e5-805a-e8ac71d49dac.png)

**Comment by nox** [comment]
I cannot reproduce this anymore.
