### ISSUE TITLE
AppVeyor fails to check out the git branch

### ISSUE THREAD

**Issue by notriddle** [servo/servo#10251]
```
Build started
git clone -q --branch=auto https://github.com/servo/servo.git C:\projects\servo
git checkout -qf d83da7d52b3fdb66b98f3c43eb5e4c32a1a1c51c
fatal: reference is not a tree: d83da7d52b3fdb66b98f3c43eb5e4c32a1a1c51c
Command exited with code 128
```

**Comment by jdm** [comment]
This happens surprisingly frequently. I'm not really sure what we can do about it.

**Comment by notriddle** [comment]
I'm not sure; just giving this issue a number and a place to discuss solutions, because yeah it does seem to happen awfully frequently.

**Comment by larsbergstrom** [comment]
I believe that this is https://github.com/servo/homu/issues/23

**Comment by emilio** [comment]
My guess is this is not an issue anymore, since we no longer gate on appveyor, feel free to reopen if it is.

**Comment by seManeiro** [comment]
Hi guys i am getting this error


warning: unable to access 'node_modules/npm/node_modules/libcipm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/http-proxy-agent/node_modules/agent-base/node_modules/es6-promisify/node_modules/es6-promise/lib/es6-promise/promise/.gitattributes': Filename too long
fatal: cannot create directory at 'node_modules/npm/node_modules/libcipm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/https-proxy-agent/node_modules/agent-base/node_modules/es6-promisify/node_modules/es6-promise/lib/es6-promise/promise': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
Command exited with code 128

**Comment by notriddle** [comment]
That is a completely unrelated issue. Please open a new one.
