### ISSUE TITLE
Sliding text bug

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#10262]
When you have defined a:hover and text-align:justify in css, text will move everytime you enter mouse over link. Tested on Windows 8.1 x64. Test HTML: http://testujem.eu/servo/slide.html

![slide2](https://cloud.githubusercontent.com/assets/10187350/14104284/ab44181c-f5a4-11e5-90a1-6ef7e8a0a60b.gif)

**Comment by mbrubeck** [comment]
Also filed as #10499.  Closing this bug because the other one has some existing discussion.
