### ISSUE TITLE
Significant (for you) update drafted from Houdini CSS WG

### ISSUE THREAD

**Issue by mbonaci** [servo/servo#10264]
It goes like this:
There is currently no way to efficiently and nicely tease out size information of blocks and text on the web. Currently DOM nodes have to be attached somewhere in the DOM to get size information, and multiple (potentially expensive) queries to clientHeight / clientWidth (which trigger synchronous layout) have to be called.
**Measure API:**
A measure API should be more powerful than clientWidth / clientHeight as it should reveal information such as baselines, and also potentially faster, as a full layout and paint shouldn't be triggered.
Fingers crossed:
https://wiki.css-houdini.org/explaining-css-layout#measurebox-tree

**Comment by mbrubeck** [comment]
Thanks for the note.  I'm closing this as it's not a Servo issue per se, but we'll be following the Houdini project.
