### ISSUE TITLE
Create a script_runtime module

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10271]
`script_thread.rs` contains the implementation of the main script thread (where `Window`s/`Document`s live), as well as a number of things that are shared between that thread and web worker threads (`dedicatedworkerglobalscope.rs` and `workerglobalscope.rs`). In particular:

* `ScriptThread::new_rt_and_cx`
* `ScriptThread::get_reports`
* `ScriptChan`
* `ScriptPort`
* `StackRootTLS`
* `CommonScriptMsg`
* `ScriptThreadEventCategory`

All of those should move to a new file (`components/script/script_runtime.rs`).

**Comment by creativcoder** [comment]
Ill take that.

**Comment by jdm** [comment]
Go for it!
