### ISSUE TITLE
Make it possible to disable the JITs

### ISSUE THREAD

**Issue by jdm** [servo/servo#10278]
Sometimes it's nicer to debug without the JIT getting in the way. Gecko uses the `setIon` and `setBaseline` methods of `JS::RuntimeOptionsRef` to configure this per-runtime. We should allow disabling them based on preference values.

**Comment by jdm** [comment]
Looks like this is also possible using `JS_SetGlobalJitCompilerOption` with `JSJitCompilerOption::JSJITCOMPILER_ION_ENABLE` and `JSJitCompilerOption::JSJITCOMPILER_BASELINE_ENABLE`.

**Comment by pcwalton** [comment]
Also make sure to call `set_ion_(false)` and `set_baseline_(false)`.

**Comment by jdm** [comment]
Those are methods available via [RuntimeOptionsRef](https://github.com/servo/rust-mozjs/blob/master/src/jsapi_linux_32.rs#L3647).

**Comment by stjepang** [comment]
I'd like to implement this.
