### ISSUE TITLE
All alternate stylesheets are applied

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#10284]
Affects: 4chan.org/g/ (the background is wrong)

Alternate stylesheets should be mutually exclusive.

```html
<link rel="stylesheet"           href="preferred.css" title="preferred">
<link rel="alternate stylesheet" href="alternate.css" title="alternate">
<div>foobar</div>
```

preferred.css
```css
div {
    border: 4px solid green;
}
```

alternate.css
```css
div {
    background-color: red;
}
```

Firefox:
![expected](https://cloud.githubusercontent.com/assets/1777894/14141219/1d60cb6e-f67e-11e5-9236-bb3839765ce4.png)
Servo:
![servo](https://cloud.githubusercontent.com/assets/1777894/14141220/21609212-f67e-11e5-959d-8a0e5c5e8d25.png)

Relevant spec:
https://html.spec.whatwg.org/multipage/#link-type-stylesheet
https://drafts.csswg.org/cssom/#concept-css-style-sheet-alternate-flag
https://drafts.csswg.org/cssom/#css-style-sheet-collections

**Comment by jdm** [comment]
Looks like `string_is_stylesheet` in `htmllinkelement.rs` needs to be more restrictive than it currently is.

**Comment by Mylainos** [comment]
I would like to take this one.

**Comment by jdm** [comment]
Please do!

**Comment by Mylainos** [comment]
Should we ignore alternate stylesheets or should we provide a way to change to it ?

**Comment by jdm** [comment]
Let's ignore them for now.

**Comment by Mylainos** [comment]
Ok

**Comment by Mylainos** [comment]
Does the reftest and the reference should be in the same folder ?

**Comment by jdm** [comment]
Yep!

**Comment by Mylainos** [comment]
Did I need to add tests/wpt/metadata/MANIFEST.json to the commit ?

**Comment by jdm** [comment]
Yes.
