### ISSUE TITLE
Dictionary sequences in dictionaries

### ISSUE THREAD

**Issue by zakorgy** [servo/servo#10282]
Hi I'm working at the University of Szeged in the team on the webbluetooth project, and as i can see dictionaries are supported in the servo, but i got a minor issue when i try to build with the following webdil described in the link  https://gist.github.com/zakorgy/a2aa0536665ff1d204f7eac231bd1ed4  .

The error message:
 
 error: the trait `js::conversions::FromJSValConvertible` is not implemented for the type 
 `dom::bindings::codegen::Bindings::BluetoothBinding::BluetoothScanFilter` [E0277]
/servo/target/debug/build/script-9e51ba05bda884ba/out/Bindings/BluetoothBinding.rs:202
match FromJSValConvertible::from_jsval(cx, rval.handle(), ()) {

 My question is,  dictionary sequences are currently not supported  in dictionaries, or is this something, that should work? Or can i try implement myself the FromJSValConvertible for the BluetoothScanfilter?

**Comment by jdm** [comment]
I can reproduce this with:
```
dictionary TestDictionary {
  sequence<SimpleDictionary> seqDict;
};
dictionary SimpleDictionary {
  boolean booleanValue = false;
};
```
