### ISSUE TITLE
Review GitHub organization teams & permission

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#10290]
Right now, as a holdover from the VERY old days of GitHub, nearly all Servo reviewers plus some random others have `Admin` permissions. There are also two security groups. I'd like to:
- [x] Get us down to one, much smaller, group with `Write`
- [ ] Use Protected Branches (https://github.com/blog/2137-protected-branches-improvements) to make it so that only Organization Admins & bors-servo can push to master on our repositories
- [x] Make sure the set of Organization (and thus Repo) Admins is very, very small. 
- [x] Document what the permissions should be when a new repository is moved to or forked in the Servo GH Organization

cc @edunham

**Comment by Ms2ger** [comment]
Move me to the Write group, please.

**Comment by saneyuki** [comment]
I'd like to edit `Assignee` and `Labels` of issues. Could you permit me to edit them?

**Comment by larsbergstrom** [comment]
@edunham 

Admin perms should be:
larsbergstrom
metajack
edunham
Manishearth

Everybody else should just have Write (which I believe gives the ability to change assignee & labels).

**Comment by larsbergstrom** [comment]
Related to this is the list of owners at https://github.com/orgs/servo/people, which I think should be the ones I mentioned above. The wrinkle in this is that according to https://help.github.com/articles/permission-levels-for-an-organization/, the only people who can transfer in repos are the Owners! And that's something that others (e.g. pcwalton/glennw) have had to do in the past.

For convenience, https://help.github.com/articles/repository-permission-levels-for-an-organization/ is the repo permission levels, which does indicate that Write is sufficient for changing assignee & labels.

**Comment by edunham** [comment]
Added a "check the repo's permissions" section to https://github.com/servo/servo/wiki/Adding-a-repo-to-Homu documenting a guess at the correct perms to hand out when setting up new stuff, based on how Servo/Servo is.

**Comment by edunham** [comment]
The last remaining thing is "set up branch protection". Branch protecting every repo in the org is not feasible right now because Homu is not working on all repos. Additionally, it's unclear whether we want to add Homu to every repo that's ever been forked to the org. Superseding this with https://github.com/servo/servo/issues/17626 for next steps.

Please re-open if there's additional tasks here not captured by #17626.
