### ISSUE TITLE
Can't open links in duckduckgo

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10309]
**Edit:** requires https://github.com/servo/servo/issues/10311

(flagging as P1 as ddg is the search engine used in browserhtml)

Url I use: https://duckduckgo.com/?q=example

Below some JS code from the duckduckgo page. It fails at `f.open()` with `f is undefined`.

Took me a while, but apparently, the test `((ie || ip || ir || is || im) && e.indexOf("http") != -1 && kg != "p" && (!kd || kd == 1))` basically means "if a known browser, if url starts with http, if search terms in url, if want to hide referrer" (not sure about `kd` and referrer).

We enter this block, and then ddg creates a hidden iframe and open the link from there.

So to make it work, we either want to be able to skip the test and go directly to `w.location = …` or support `iframe.contentDocument` and `window.open` from within an iframe. I'm wondering if it's normal that we enter this block (Servo is not a known browser, and I don't think by default ddg is supposed to hide the search terms from the referrer url).

I'm not sure,  but I think ddg in Chrome doesn't use this hidden iframe thing and use `w.location`.

I'll need help from some ddg folks. My question: is it normal that Servo goes through the hidden iframe code path?

``` js
function nug(e, g) {
    var b, c, f, a;
    fl = 0;
    fn = 0;
    a = "";
    if (window.getSelection) {
        a = window.getSelection().toString()
    } else {
        if (document.selection) {
            a = document.selection.createRange();
            a = a.text
        }
    }
    var h = a == DDG.last_selection ? 1 : 0;
    DDG.last_selection = a;
    if (!h) {
        return false
    }
    if (g) {
        window.open(e)
    } else {
        if (w.postMessage && !is && !ip && !is_konqueror && kg != "p" && (!kd || kd == 1)) {
            b = document.getElementById("iframe_hidden");
            b.contentWindow.postMessage("ddg:" + e, location.protocol + "//" + location.hostname)
        } else {
            if ((ie || ip || ir || is || im) && e.indexOf("http") != -1 && kg != "p" && (!kd || kd == 1)) {
                if (d.getElementById("iframe_hidden")) {
                    d.body.removeChild(d.getElementById("iframe_hidden"))
                }
                c = "<html><head><meta name='referrer' content='origin'></head><body><script language='JavaScript'>parent.window.location.href=\"" + e + '";<\/script></body></html>';
                b = d.createElement("iframe");
                b.id = "iframe_hidden";
                d.body.appendChild(b);
                f = b.document;
                if (b.contentDocument) {
                    f = b.contentDocument
                } else {
                    if (b.contentWindow) {
                        f = b.contentWindow.document
                    }
                }
                f.open();
                f.writeln(c);
                f.close()
            } else {
                w.location = e
            }
        }
    }
}
```

**Comment by paulrouget** [comment]
Pinging @nilnilnil

**Comment by nilnilnil** [comment]
It's because since Servo is a non-known browser, we have no way of asserting that meta referrer is appropriately implemented, so we use the iframe method to preserve user privacy instead. If Servo implements meta referrer (with the origin option), we'd be happy to add Servo to the list that would skip this block.

**Comment by paulrouget** [comment]
@nilnilnil Thank you! I'll come back to you once we got that implemented.

**Comment by jdm** [comment]
@paulrouget To answer [your question](http://logs.glob.uno/?c=mozilla%23servo#c439080), #11238 implements a per-document referrer control that is obtained via child `<meta>` elements and is used in navigation, iframes, XHR, and scripts. I suspect DDG will also want support for referrer policies delivered via content attributes, which will happen in a separate PR.

**Comment by nox** [comment]
So I read the JS code again, and I'm not sure how referrer policy is going to help here: doesn't DDG use referrer policy through an iframe, using `contentWindow`, too?

**Comment by paulrouget** [comment]
The goal is to support enough of the referrer policy for ddg to allow using `window.location` and not go through the iframe/postMessage hack.

**Comment by paulrouget** [comment]
@nilnilnil , can you comment on that:

> @paulrouget To answer [your question](http://logs.glob.uno/?c=mozilla%23servo#c439080), #11238 implements a per-document referrer policy that is obtained via child `<meta>` elements and is used in navigation, iframes, XHR, and scripts. I suspect DDG will also want support for referrer policies delivered via content attributes and HTTP headers, which will happen in a separate PR.

I'd like to know if we implemented enough to add servo to the white list.

**Comment by metajack** [comment]
What's the status here?

**Comment by nox** [comment]
Ping on this?

**Comment by fabricedesre** [comment]
This works for me with the current build.

**Comment by paulrouget** [comment]
Confirmed.
