### ISSUE TITLE
Min width on table is not working

### ISSUE THREAD

**Issue by ocerman** [servo/servo#10306]
Test HTML:
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<style>
		table{
			min-width: 100%;
		}
		
		tr{
			background: #cbd1d8;
		}
	</style>
</head>

<body>
	<table>
		<tr><td>Test</td></tr>
	</table>
</body>

</html>
```

![table](https://cloud.githubusercontent.com/assets/10187350/14172523/be196164-f738-11e5-9597-de9324a1de42.png)

**Comment by frewsxcv** [comment]
Might be related to https://github.com/servo/servo/issues/783

**Comment by nox** [comment]
This still happens.

**Comment by Tau5** [comment]
I've checked on the latest version and this is FIXED

Tested under Linux x64 (Fedora 40)
Servo version `Servo 0.0.1-fa05214`

![fixed](https://github.com/user-attachments/assets/ec97715a-7bee-4a97-b9fe-dfa3cb08a03d)

**Comment by mrobinson** [comment]
This is likely fixed by the change from the legacy layout system to the new one.
