### ISSUE TITLE
Compiling WebRender shaders on ARM

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#10310]
I'm trying to use WebRender on ARM Linux (on an Odroid XU3), and I've already hacked Servo to

- load the correct files (es2_common.{fs,vs}.glsl),
- use ES3 (Api::OpenGlEs, (3, 0)), and
- changed the shader headers (`#version 130` should be supported on this board)

However, I'm getting the following error when I start Servo:

```
compile "/home/odroid/Servo/resources/shaders/quad.vs.glsl"
Failed to compile shader: 0:173(19): error: `uAtlasParams' undeclared
0:173(19): error: type mismatch
0:173(2): error: operands to arithmetic operators must be numeric
thread '<main>' panicked at '-- Shader compile failed - exiting --', /home/mmatyas/Servo/servo-arm/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:962
stack backtrace:
   1: 0xb696017f - sys::backtrace::tracing::imp::write::h100267e2e2ffc754Ocv
   2: 0xb6965013 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44475
   3: 0xb6964b93 - panicking::default_handler::h97bb925f4d429c68k2z
   4: 0xb694e59f - sys_common::unwind::begin_unwind_inner::hf0a92b8118d8a4ed21t
   5: 0xb6000db7 - sys_common::unwind::begin_unwind::h17372011683458955000
   6: 0xb6002643 - device::Device::compile_shader::hc6aca6a8175c5e3f4Ci
   7: 0xb60035c7 - device::Device::load_program::h84e4484ecbe0f939U4i
   8: 0xb5ffe423 - device::Device::create_program::h3236010d25cb7ee1Q1i
   9: 0xb60123bb - renderer::Renderer::new::hc19dd89049569480WCs
  10: 0xb53ec5cb - main::h9cc0aa5bb4f2f2aeqaa
  11: 0xb696477b - sys_common::unwind::try::try_fn::h9391211778621015551
  12: 0xb695f4a3 - __rust_try
  13: 0xb695f4a3 - __rust_try
  14: 0xb695f4a3 - __rust_try
  15: 0xb695f4a3 - __rust_try
...
```

I know WebRender isn't fully supported on ARM yet, I was just wondering what could be the problem. Any ideas?

**Comment by larsbergstrom** [comment]
Yeah, sorry, but you will also need this commit from @glennw: 
https://github.com/glennw/servo/commit/e9723c3eccba08b924e555b04611946a7bd18d5a

**Comment by mmatyas** [comment]
Thanks, this did work, and I could run WR on Odroid. The performance is horrible though, what could be the cause of that? (I don't know how it performs on Android due to the build errors I've also reported)

There's also some text rendering issue:

![screenshot-servo the parallel browser engine - servo-1](https://cloud.githubusercontent.com/assets/4354863/14489677/d47c9c74-016e-11e6-9693-f22440d8b459.png)

**Comment by larsbergstrom** [comment]
I have a fix here for the wr-stats:
https://github.com/larsbergstrom/webrender/commit/1aceb99c79670a9db21ad89f9e511910aec41bdf

In order for events to work, you may need:
https://github.com/larsbergstrom/servo/commit/4e7f7ac9b8459f51adcbe028d0dab832170ad17a
Though I thought that on linux it'd be fine with the default implementation.

The only thing I can think of on ARM linux that is probably getting you is this:
https://github.com/servo/servo/blob/f335586ff538004c708d836876b359704ebed86a/python/servo/build_commands.py#L207

By default, Rust will often use soft/emulated floats, which are incredibly slow. I would definitely r+ a patch that made appropriate hardfloat flags the default on arm32/arm64 :-)

**Comment by mmatyas** [comment]
I've applied both patches (though I'm not sure what the second does), but unfortunately this just scaled up the screen:

![pic3](https://cloud.githubusercontent.com/assets/4354863/14557040/803b5298-02fb-11e6-8ad5-226510072651.png)

Then I tried to build using the RUSTFLAG you linked, but #10517 happened :(

**Comment by mmatyas** [comment]
I've managed to build with ` -C target-feature=+neon` using `opt-level = 2`, but Servo is still slow.

**Comment by larsbergstrom** [comment]
@glennw 

Do you know how to debug situations such as the recent one on MacOS where the shaders are being run on the CPU instead of the GPU? @mmatyas is seeing really high CPU usage on ARM right now, and while they work on getting better symbolic info into the binary and out of the profiler, I was wondering if you have any pointers for them on how to rule out accidental fallbacks to OpenGL CPU execution of the shaders.

**Comment by mmatyas** [comment]
I've been doing some profiling using ARM Streamline, a few things I've noticed:
- Very high CPU usage: on every redraw, all 8 cores run 100%.
- High CPU Contention: many threads are runnable but waiting, about 20-40% of the threads on average
- No SIMD at all: even after compiling with the flags I've mentioned I couldn't detect SIMD instructions at all. To my surprise, after checking the code, I've noticed the `simd` package is only used on x86_64 and AArch64. The dependencies still should have picked up the `CFLAGS` & co., I guess they got overridden, need additional flags or just simply not optimized for NEON.
- It seems the GPU (Mali-T628) is not used for computing at all, and there is no shader activity either

**Comment by mmatyas** [comment]
Just tried the latest build, the wr-stats fonts are now readable... until a redraw, when the whole Servo window turns white.

**Comment by mmatyas** [comment]
Actually, the whole screen is white on start.

**Comment by mmatyas** [comment]
The white screen got fixed, and the numbers are visible too. Here's a screenshot:

![screenshot-wikipedia - servo](https://cloud.githubusercontent.com/assets/4354863/15014116/5a788ffe-1204-11e6-883a-7693b85c90cf.png)

**Comment by larsbergstrom** [comment]
@mmatyas Awesome! This is on the Odroid XU3?

Now, we just need to land the webrender update in the Servo repository and we should be able to close this, right?

**Comment by larsbergstrom** [comment]
Also, that is a *lot* of CPU compository time (cc @glennw - this is WR1). I suspect there's something going wrong there, but we'll need to profile to figure it out.

**Comment by mmatyas** [comment]
Yes, this is on the XU3. WR does run, but the performance is still very slow, even with the recent NEON patches.

**Comment by metajack** [comment]
Is performance better with WR1 than the standard CPU renderer? Or worse?

**Comment by larsbergstrom** [comment]
@mmatyas Do you have the ARM profiler to try and look into it? You will need to first uncomment:
https://github.com/servo/servo/blob/master/components/servo/Cargo.toml#L30
and then rebuild, to have even basic symbol info. Stack frames will still be busted, because Rust defaults to no-frame-pointer and doesn't have anything to easily turn frame pointers back on, AFAIK, but it's often enough to see if a soft float or other emulated instruction is slipping through.

**Comment by mmatyas** [comment]
Non-WebRender mode (with `-G es2`) is way better and actually usable for browsing. The scrolling is smoother than in Chromium, for example. WR however runs about 1 fps or less, using the SIMD/hard-float patches (#10900, #10916), Lars' shader patches from this issue, and `-mfloat-abi=hard -mfpu=neon` CFLAGS. I've [did some profiling](https://github.com/servo/servo/issues/10310#issuecomment-214713192), but I can take a closer look.

**Comment by mmatyas** [comment]
PS. Unfortunately, I can't provide Streamline screenshots due to license reasons :(

**Comment by larsbergstrom** [comment]
It *may* be faster once https://github.com/servo/servo/pull/11123 lands - it was causing some really bad performance issues for WR!

**Comment by mmatyas** [comment]
Applied #11123, but it's still slow :(

**Comment by mmatyas** [comment]
After the recent developments, WebRender now works correctly on ARM, and it's very fast!

A minor problem: the `wr-stats` has some display issues again, as you can see on the screenshot at servo/webrender#408.
