### ISSUE TITLE
Implement URL.searchParams

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10335]
https://github.com/servo/servo/blob/f335586ff538004c708d836876b359704ebed86a/components/script/dom/webidls/URL.webidl#L23

https://url.spec.whatwg.org/#interface-urlsearchparams

**Comment by Manishearth** [comment]
This should be useful here: http://doc.servo.org/url/struct.Url.html#method.query_pairs

**Comment by stjepang** [comment]
Can I try this?

**Comment by paulrouget** [comment]
Sure!

**Comment by Manishearth** [comment]
Let us know if you need help!
