### ISSUE TITLE
Setting xhr.responseType throws exception

### ISSUE THREAD

**Issue by Gozala** [servo/servo#10346]
Here is a an example html file to reproduce it:

```html
<script defer='defer'>
  var xhr = new XMLHttpRequest();
  xhr.open('GET', 'package.json', false);
  xhr.responseType = 'json';
</script>
```

**Comment by jdm** [comment]
This is [following the spec](https://xhr.spec.whatwg.org/#the-responsetype-attribute), since you're not allowed to set the responseType attribute for synchronous requests in a Window global.
