### ISSUE TITLE
Write a test for setting string preferences from WPT tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#10348]
We have a test for boolean preferences in `preferences.html`, but we should verify that string preferences also work. This will require adding a similar API to `TestBinding`, and updating the `preferences.html.ini` file to include the new preferences value.

Code: `components/script/dom/webidls/TestBinding.webidl`, `components/script/dom/testbinding.rs`, `tests/wpt/mozilla/tests/mozilla/preferences.html`, `tests/wpt/mozilla/metadata/mozilla/preferences.html.ini`
Test: `./mach test-wpt tests/wpt/mozilla/tests/mozilla/preferences.html`

**Comment by amarant** [comment]
I have a try here #10362
