### ISSUE TITLE
./mach run -b doesn't accept additional params

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#10357]
For all of the `./mach run` modes, you can pass in additional parameters after a `--`, e.g. `./mach run -r -w -- -Zsome-debug-option`. When run with `-b`, this isn't possible.

Code: https://github.com/servo/servo/blob/5333f564cd2f97ad78d2edc53f3791461b4b9244/python/servo/post_build_commands.py#L128

Just need to add `params` to `args` somewhere in that branch

**Comment by autrilla** [comment]
#10363 I *think* this is what you want, but it seems too trivial

**Comment by Manishearth** [comment]
Yep, that's correct.

**Comment by timvandermeij** [comment]
Fixed by #10363?
