### ISSUE TITLE
Documents without a browsing context should have a null location

### ISSUE THREAD

**Issue by jdm** [servo/servo#10367]
According to the [specification](https://html.spec.whatwg.org/multipage/browsers.html#dom-document-location), our implementation of `Document::Location` is incomplete.

Code: `components/script/dom/document.rs`
Test: `./mach tests/wpt/web-platform-tests/domparsing/DOMParser-parseFromString-html.html`

The expected test results will need to be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) once the change is made.

**Comment by nehagup** [comment]
I think I'm gonna enjoy working on this. :)

**Comment by slayerjain** [comment]
Am i not done with this one?

**Comment by jdm** [comment]
Ack, sorry @nehagup. I forgot about #10257 :( I'll file a new one for you.

**Comment by nehagup** [comment]
Ah...Sure!No issues :)
