### ISSUE TITLE
Dispatch error event when link elements get invalid network response

### ISSUE THREAD

**Issue by jdm** [servo/servo#10374]
Specification: https://html.spec.whatwg.org/multipage/semantics.html#concept-link-obtain (starting at "Once the attempts to obtain the resource")
Code: `components/script/dom/htmllinkelement.rs` (see `AsyncResponseListener` implementation for `StylesheetContext`)
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/document-metadata/the-link-element/link-style-error-01.html`

We should check whether the status received in `response_complete` is an error, and also check whether the Metadata value stored in `headers_available` contains a `Content-Type` value which is anything besides `text/stylesheet`. If either of these are true, we should call `fire_simple_event` on the original `HTMLLinkElement` element.

cc @nehagup

**Comment by autrilla** [comment]
I'll give this a shot :)

**Comment by Wafflespeanut** [comment]
@nehagup Any updates on this?

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by askeing** [comment]
I'd like to try it

**Comment by KiChjang** [comment]
You got it!
