### ISSUE TITLE
IFrame session history navigation APIs should act like network loads

### ISSUE THREAD

**Issue by jdm** [servo/servo#10386]
There's no reason that `iframe.goBack()` should be expected to be a synchronous operation with the previous page ready for rendering when the call completes - the browser could throw away session history to reduce memory usage, or the previous page may be impossible to cache safely. Navigating through session history should trigger load events like regular navigations.

**Comment by nox** [comment]
Cc @asajeffrey

**Comment by asajeffrey** [comment]
@jdm is this still an issue now that we have document unloading?

**Comment by jdm** [comment]
I'm not sure if I was referring to a test or implementation issue, but I think what we have now makes sense.
