### ISSUE TITLE
Implement WebGLRenderingContext.getActiveUniform()

### ISSUE THREAD

**Issue by emilio** [servo/servo#10397]
See the [general info for WebGL bugs](https://github.com/servo/servo/issues/10209#user-content-general-info) to see the spec and get a grasp how the code is structured.

This should be pretty similar to #10379.

@saurvs wanted to work on this.

**Comment by saurvs** [comment]
@emilio I've opened the first PR for `gleam` https://github.com/servo/gleam/pull/74

**Comment by anholt** [comment]
I've been working on #12852
