### ISSUE TITLE
asm.js type error: Disabled by javascript.options.asmjs in about:config

### ISSUE THREAD

**Issue by metajack** [servo/servo#10401]
Getting this running Octane. We probably need to enable asm.js in Servo.

**Comment by metajack** [comment]
cc @tschneidereit @nox

**Comment by nox** [comment]
Were that present in SM39, or are you pinging me because that is blocked on SMUP? Or is that a question I should answer myself? :)

**Comment by metajack** [comment]
I pinged @tschneidereit since it seems this error message is overly specific to Firefox, and probably should be fixed.

I pinged @nox since you are working on smup and might want to add this to your list.

After talking with @jdm I think I may just fix it in Servo myself :)

**Comment by tschneidereit** [comment]
I tried fixing it in [the obvious way](https://gist.github.com/tschneidereit/e3a14c57074f855739e0ec8092d09bfd) yesterday, but that somehow didn't work. I'm somewhat inclined to leave it at that until after the SMUP.

Filed [bug 1262208](https://bugzilla.mozilla.org/show_bug.cgi?id=1262208) about the warning message.

**Comment by nox** [comment]
Is anyone working on a smup?

**Comment by tschneidereit** [comment]
> Is anyone working on a smup?

Yes, @fitzgen is. He's very close to getting a usable mozjs using unmodified upstream, at which point he'll do the actual smup.

**Comment by nox** [comment]
Nice! Happy to hear that.

**Comment by nox** [comment]
Any news on this..?

**Comment by jdm** [comment]
Updating spidermonkey is still in progress. What sort of news are you looking for?

**Comment by nox** [comment]
@jdm Some sort of ETA for the SM upgrade, more or less.

**Comment by jdm** [comment]
Keep an eye on https://github.com/servo/mozjs/pull/119 and https://github.com/servo/servo/pull/17143.

**Comment by atouchet** [comment]
Is this still an issue?

**Comment by atouchet** [comment]
SpiderMonkey has since been updated and I do not run into this issue when running Octane.
