### ISSUE TITLE
octane progress bar not repeating correctly

### ISSUE THREAD

**Issue by metajack** [servo/servo#10412]
Servo seems to keep stretching it, but Firefox repeats the pattern instead.

STR:
1. Go to http://chromium.github.io/octane/?auto=1 in servo and watch
2. Compare to the same page in firefox

Images attached to demonstrate the difference.
![octane-firefox](https://cloud.githubusercontent.com/assets/28357/14285571/4de25c96-fb09-11e5-9a82-813d56f54e16.png)
![octane-servo](https://cloud.githubusercontent.com/assets/28357/14285572/4de2b11e-fb09-11e5-868f-c2d29f410a4a.png)

**Comment by mbrubeck** [comment]
The progress bar uses `linear-gradient` and `background-size`.

**Comment by pyfisch** [comment]
This is caused by #16657. The `background-size` is currently ignored for gradients.

**Comment by nox** [comment]
The progress bar is still badly rendered.

**Comment by pyfisch** [comment]
The progress bar now repeats correctly.

**Comment by jdm** [comment]
Thanks for checking!
