### ISSUE TITLE
Fix transform_text and/or its test cases

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1041]
There are some [commented-out failing tests](https://github.com/kmcallister/servo/blob/a9ed37189bc667df3f00db066583e230a414775f/src/components/gfx/text/util.rs#L175-L229) for `transform_text` in `src/components/gfx/text/util.rs`.  Someone who understands this algorithm should fix `transform_text` and/or the test cases.

**Comment by nox** [comment]
These were reenabled a long time ago.
