### ISSUE TITLE
Copy all the JS runtime options from Gecko

### ISSUE THREAD

**Issue by jdm** [servo/servo#10415]
For example, everything in Gecko that is configured via a `javascript.options` preference: https://dxr.mozilla.org/mozilla-central/rev/d9f50aa0a1aaf90499b85c31e0f329b762e80fdd/js/xpconnect/src/XPCJSRuntime.cpp#1535

**Comment by jdm** [comment]
https://dxr.mozilla.org/mozilla-central/rev/d9f50aa0a1aaf90499b85c31e0f329b762e80fdd/modules/libpref/init/all.js#1145

**Comment by jdm** [comment]
https://gist.github.com/jdm/1d2e71157887849c7ba2

**Comment by jdm** [comment]
https://dxr.mozilla.org/mozilla-central/source/dom/base/nsJSEnvironment.cpp#2546

**Comment by metajack** [comment]
I'm working on this. I should have a patch in tomorrow.

**Comment by metajack** [comment]
Fixed by #10445
