### ISSUE TITLE
Why does it takes longer to Servo to load firefox.com than Firefox?

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10425]
To load firefox.com in Firefox, it takes 2.4s (`performance.timing.loadEventEnd - performance.timing.navigationStart`). In Servo, it takes 10s (time between `iframe.src = "http://firefox.com"` and `mozbrowserloadend`).

Do we know the reasons?

I guess the lack of speculative HTML parsing (#3847) is one of the reasons. Anything else?

**Comment by frewsxcv** [comment]
Relevant to https://github.com/servo/servo/issues/8940

**Comment by Manishearth** [comment]
It should be speculative HTML parsing and fetching. If a website has a bunch of external scripts (e.g. twitter) it takes forever to load since the scripts load one after another with fetches in between. Firefox probably fetches them all in parallel whilst loading.

**Comment by metajack** [comment]
We know one concrete reason, which is that we start loading resources later due to not having speculative HTML parsing.

Another reason is that if you have a warm cache in Firefox, you're probably skipping a lot of the network requests outright, and Servo currently has no cache.

There are probably more reasons, but right now we don't know what they are.

I am hoping @nox's work getting the performance tab up in devtools will help us diagnose other issues.

**Comment by paulrouget** [comment]
> I am hoping @nox's work getting the performance tab up in devtools will help us diagnose other issues.

What about `window.performance.timing`? That would help a lot.
Filed https://github.com/servo/servo/issues/10428

**Comment by paulrouget** [comment]
http://firefox.com redirects to https://firefox.com. So I suspect https://github.com/servo/servo/issues/11008#issuecomment-217243111

**Comment by jdm** [comment]
Good catch! My profile trace reports 4.5s spent in the same step that #11008 hangs in.

**Comment by jdm** [comment]
That said, on subsequent runs I can't reproduce the long connection time :/

**Comment by metajack** [comment]
@jdm reports that speculative HTML parsing is not the top issue on any profile he's investigated, so I think we should focus our efforts elsewhere. It's not yet the lowest hanging fruit.

**Comment by nox** [comment]
I cannot reproduce this anymore.

**Comment by nox** [comment]
```html
<iframe style="width:700px;height:500px" mozbrowser="true" src=""></iframe>
<script>
  var now;
  var iframe = document.querySelector("iframe");
  setTimeout(() => {
    iframe.addEventListener("mozbrowserloadstart", () => { console.log("start") });
    iframe.addEventListener("mozbrowserloadend", () => {
        console.log(new Date().getTime() - now);
        console.log("end");
    });
    setTimeout(() => {
      now = new Date().getTime();
      iframe.src = "http://firefox.com"
    }, 1000);
  }, 1000);
</script>
```

```
± ./mach run -r --pref dom.mozbrowser.enabled firefox.html
start
1634
end
```

**Comment by paulrouget** [comment]
Agreed. It's a lot better than before. Closing.
