### ISSUE TITLE
Implement window.performance.timing

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10428]
https://developer.mozilla.org/en-US/docs/Web/API/Performance/timing

https://w3c.github.io/navigation-timing/#the-performancetiming-interface

This would be really useful to page loading performance, like #10425.

**Comment by izgzhen** [comment]
Looks like we only have three readonly attributes `unloadEventStart`, `loadEventStart` and `loadEventEnd` left unimplemented. Is there already someone working on it? If not, I am interested in helping this out :)

**Comment by jdm** [comment]
Nobody's working on it, and I think #10452 is counting on using them, so this would be really useful :)

**Comment by izgzhen** [comment]
@jdm Great. I believe investigation on this can help me to understand the lifecycle better.

**Comment by izgzhen** [comment]
I found that current `navigation_Start` is counted as second but it should be millisecond according to [spec](http://www.w3.org/TR/hr-time-2/#dom-domhighrestimestamp).

> A DOMHighResTimeStamp should represent a time in milliseconds accurate to 5 microseconds

Also, the previous implementation looks rather imprecise (i.e. `time::get_time().sec * 1000;`). I will improve it as well.

**Comment by izgzhen** [comment]
I bumped into an awkward problem here.

I need to set the timing property of `document` after the `load` event targeting the window is completed. I didn't find any convenient way to register a callback function for completion of listener (which is also a callback function, though). Now the only solution I can come up with is hard coding here https://doc.servo.org/src/script/dom/eventtarget.rs.html#213 the logic to inspect the event type and target, then do something with the target. Anyway, I wonder if this can be done more sensibly?

**Comment by timvandermeij** [comment]
Fixed by #10538?

**Comment by izgzhen** [comment]
@timvandermeij The basic need is satisfied. But some other properties are still left unimplemented.

**Comment by shinglyu** [comment]
@izgzhen : Good work! Do you plan to implement `navigationStart` in the near future? #10452 will need that.

**Comment by KuoE0** [comment]
Hi, I intent to try on this three attributes:

- requestStart
- responseStart
- responseEnd

Did anyone already work on them?

**Comment by jdm** [comment]
Those should be fine to work on. The response properties can probably be set in the `ParserContext` methods in servohtmlparser.rs, and the request can be noted in ScriptThread::start_page_load.

**Comment by nox** [comment]
@KuoE0 Ping on this?

**Comment by KuoE0** [comment]
Hi, I'm stiil working on this. I want to implement the 3 attributes I mentioned above. If you are interesting on this, there are many attributes haven't be implemented!

2016年6月2日 21:35 於 Anthony Ramine <notifications@github.com> 寫道：

@KuoE0 Ping on this?

**Comment by jdm** [comment]
The most recent effort to implement this was in #11792. It looks like it was on the right track, but it needs to be rebased and update some expected test results.

**Comment by nox** [comment]
This was done.
