### ISSUE TITLE
Update crates that use byteorder to use 0.5

### ISSUE THREAD

**Issue by emilio** [servo/servo#10437]
As discussed in https://github.com/servo/servo/pull/10433#issuecomment-206387444.

Crates with the old dependency include:

- [x] bincode                                                                                 
- [x] image
- [x] immeta
- [x] ipc-channel
- [x] jpeg-decoder
- [x] wayland-window
- [x] websocket

cc @saurvs

**Comment by kaksmet** [comment]
jpeg-decoder 0.1.3 (which uses byteorder 0.5) has been published.

**Comment by jaysonsantos** [comment]
immeta 0.3.2 is published with new version

**Comment by jaysonsantos** [comment]
Image already merged on https://github.com/PistonDevelopers/image/pull/525 I just asked if they have an ETA

**Comment by jaysonsantos** [comment]
wayland-window 0.2.3is also published with new byteorder

**Comment by jaysonsantos** [comment]
rust-websocket 0.16.2 also published with new byteorder

**Comment by jaysonsantos** [comment]
image 0.9.0 also done

**Comment by jaysonsantos** [comment]
bincode 0.5.3 done

**Comment by jaysonsantos** [comment]
servo/ipc-channel is ok on master, who could generate a new version of it?

**Comment by jdm** [comment]
Opened https://github.com/servo/ipc-channel/pull/65. Will publish when it's merged.

**Comment by jdm** [comment]
Apparently we use ipc-channel via git, so it should now be possible to update all of the crates to the newest versions.

**Comment by jaysonsantos** [comment]
Nice

**Comment by jdm** [comment]
Note for anybody doing this: `./mach cargo-update -p library_name` is the correct way to upgrade.

**Comment by saurvs** [comment]
I can update the lock files and remove the exception for `byteorder` from `tidy.py`

**Comment by jdm** [comment]
Fixed by #10565.
