### ISSUE TITLE
Resume interrupted bootstrap downloads

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#10441]
We have some `urllib2` python code that downloads the Cargo, Rust, and Rust target lib files located here:
https://github.com/servo/servo/blob/master/python/servo/bootstrap_commands.py#L32-L63

Currently, this code does not support interrupted downloads. The job of this issue is to implement resumption of failed downloads.

CC @mbrubeck

**Comment by autrilla** [comment]
I'm interesting in working on this. Where should partially-downloaded files be placed?

**Comment by larsbergstrom** [comment]
Most of the programs that I've seen have taken the destination filename and added ".part" or done something similar to that. Making this change would require also refactoring the `download_file` function to pass in the destination filename and `destination_bytes` to pass in a temporary file name.

@Ms2ger what do you think?

**Comment by mbrubeck** [comment]
Temporary files should be somewhere within the `self.context.sharedir` directory (defaults to `.servo`, can be set using the `tools.cache-dir` config key).  Since this is where the bootstrap commands also store most of the final files, just appending a suffix should work fine for those.

**Comment by autrilla** [comment]
I opted for .part at #10442

**Comment by Wafflespeanut** [comment]
fixed by #10442
