### ISSUE TITLE
Disallow uses of `unwrap` in constellation.rs, compositor.rs, and pipeline.rs

### ISSUE THREAD

**Issue by jdm** [servo/servo#10446]
Three options:
* shell script that greps for `unwrap` in those files and runs on travis
* rustc lint that disallows calling any method named `unwrap` in files marked `#[disallow(unwrap)]`
* a warning from highfive if any line in those files contains `unwrap`

**Comment by matthiaskrgr** [comment]
````- sh -c "! grep "\.unwrap(" components/compositing/compositor.rs components/compositing/pipeline.rs components/compositing/constellation.rs" ````
could be directly written into travis.yml as a job.

If that is sufficient, feel free to assign to me.

**Comment by matthiaskrgr** [comment]
Or do you really want ".*unwrap.*"?
There is also .unwrap_or_else([...]), I was not sure if that should match or not.

**Comment by jdm** [comment]
Unwrap_or_else is fine, since it doesn't actually panic like unwrap does. And yes, I would be ok with using shell scripts for this, but we should make a separate script in `etc/ci/` and invoke that from .travis.yml as well as places like https://github.com/servo/saltfs/blob/45a0596d2e7470187121b529d49796fd2668e850/buildbot/master/master.cfg#L112 .

**Comment by notriddle** [comment]
Could we add it to tidy?

**Comment by Wafflespeanut** [comment]
Yep, this could be given to tidy (it already checks all the lines in Rust source files). It shouldn't add any painful overhead. @jdm Why don't we go for tidy here?

**Comment by jdm** [comment]
I guess it seemed so specifically targeted (three files) that it seemed like the wrong tool to reach for.

**Comment by Wafflespeanut** [comment]
Yes, but (with the bulk of unwraps we have everywhere) won't the count increase, as we clean the other files in the near future?

**Comment by Wafflespeanut** [comment]
Oh, never mind, we'll add it later :)

**Comment by asajeffrey** [comment]
I would be very happy to see this, for stopping regressions to #10124 and friends.
