### ISSUE TITLE
Intermittent failure of /_mozilla/mozilla/iframe_contentDocument.html

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#10454]
Unexpected subtest result in /_mozilla/mozilla/iframe_contentDocument.html:
  │ FAIL [expected PASS] Iframe contentDocument test.
  │   → iframe.contentDocument.getElementById(...) is null
  │ 
  │ test_contentWindow@http://web-platform.test:8000/_mozilla/mozilla/iframe_contentDocument.html:11:19
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1

**Comment by jdm** [comment]
Hasn't been seen in months; isn't disabled. Closing.
