### ISSUE TITLE
Build on NixOS

### ISSUE THREAD

**Issue by sindikat** [servo/servo#10468]
I am trying to build Servo on NixOS, with Nix version 1.11.2. I installed the following packages — `bzip2, cmake, freeglut, freetype, glib, gperf, mesa, which, xorg.libX11, xorg.libXcursor, xorg.xrandr` — although these might not be all dependencies. Anyway, 

```
Error running mach:

    ['build', '--dev']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory

  File "/home/sindikat/progs/servo/python/servo/build_commands.py", line 235, in build
    env=env, cwd=self.servo_crate(), verbose=verbose)
  File "./python/servo/command_base.py", line 69, in call
    return subprocess.call(*args, shell=sys.platform == 'win32', **kwargs)
  File "/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
```

I have no idea, how to continue from that.

**Comment by jdm** [comment]
Cc @eddyb

**Comment by eddyb** [comment]
@sindikat did you install those packages to your user/system profiles, instead of using a `default.nix` file? 
Because it won't really work. Here's the `default.nix` I have in my servo checkout:

```nix
let
   pkgs = import <nixpkgs> {};
in pkgs.stdenv.mkDerivation rec {
  name = "servo-env";
  buildInputs = with pkgs; with xlibs; [
    cmake freetype x11 mesa expat
    pkgconfig libXxf86vm libXmu
  ] ++ (with python27Packages; [virtualenv pip dbus]);
  SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
  LD_LIBRARY_PATH = with pkgs; with xlibs; stdenv.lib.makeLibraryPath [
    mesa zlib libX11 libXcursor libXxf86vm libXi
  ];
}
```

You can either run commands through `nix-shell`, e.g. `nix-shell --run './mach build -d'` or just enter `nix-shell` and work from in there.

There is a bundled virtualenv which breaks, so what I did (because I couldn't even figure out where to submit a bug report) is:
Open `.cargo/git/checkouts/mozjs-*/master/mozjs/python/virtualenv/virtualenv.py` in your editor.
Find and replace this line:
```diff
-     prefixes = [sys.prefix]
+     prefixes = [sys.prefix, "/nix"]
```
`sudo chown root:root .cargo/git/checkouts/mozjs-*/master/mozjs/python/virtualenv/virtualenv.py`
(the `chown` prevents `cargo` from overwriting it)

**Comment by sindikat** [comment]
Installing `cargo` into system profile allowed to make a progress, but the build still failed.

I tried to use `nix-shell` with your `default.nix` and changed the line in `.../virtualenv.py`. But now `tenacious` doesn't compile, and I don't know how to proceed:

    unused manifest key: package.publish
       Compiling tenacious v0.1.2
       Compiling harfbuzz-sys v0.1.2
       Compiling openssl-sys v0.7.8
       Compiling gl_generator v0.5.1
       Compiling x11-dl v2.4.0
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:18:5: 18:34 error: unresolved import `rustc::traits::ProjectionMode`. Could not find `traits` in `rustc` [E0432]
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:18 use rustc::traits::ProjectionMode;
                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:18:5: 18:34 help: run `rustc --explain E0432` to see a detailed explanation
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:22:5: 22:14 error: unresolved import `rustc::ty`. There is no `ty` in `rustc` [E0432]
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:22 use rustc::ty;
                                                                                                                 ^~~~~~~~~
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:22:5: 22:14 help: run `rustc --explain E0432` to see a detailed explanation
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:24:5: 24:17 error: unresolved import `rustc::infer`. There is no `infer` in `rustc` [E0432]
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:24 use rustc::infer;
                                                                                                                 ^~~~~~~~~~~~
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:24:5: 24:17 help: run `rustc --explain E0432` to see a detailed explanation
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:140:15: 140:21 error: the type of this value must be known in this context
    /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/tenacious-0.1.2/src/lib.rs:140         match ty.sty {
                                                                                                                            ^~~~~~
    error: aborting due to previous error
    Build failed, waiting for other jobs to finish...
    Could not compile `tenacious`.
    
    To learn more, run the command again with --verbose.
    [Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
    Build completed in 74.15s

**Comment by eddyb** [comment]
@sindikat ahh, I forgot, you have to let it download `cargo` and `rustc` and then `patchelf` it. I haven't automated it beyond this:
```sh
#!/bin/sh

# HACK(eddyb) patch binaries and libs so NixOS can run them.
NIX_LIB=~/.nix-profile/lib
PATCH="patchelf --set-rpath $NIX_LIB:"$(echo $(pwd)/.servo/rust/*/*/rustc/lib)
PATCH_BIN="$PATCH --interpreter $NIX_LIB/ld-linux-x86-64.so.2"
(cd .servo/rust/*/*/rustc &&
    $PATCH_BIN bin/rustc &&
    $PATCH_BIN bin/rustdoc &&
    find lib -name '*.so' | xargs -n 1 $PATCH)

# HACK(eddyb) patch cargo so NixOS can run it.
$PATCH_BIN .servo/cargo/*/*/bin/cargo
```

**Comment by sindikat** [comment]
Ok, I ran the script and also installed some other packages just in case, and now `nix-shell --run './mach build --dev'` barfs at installing `harfbuzz-sys`:

    make[1]: *** [/home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/harfbuzz-sys-0.1.2/harfbuzz/config.h.in] Error 127
    make: *** [all] Error 2
    thread '<main>' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f", "makefile.cargo",
                                &format!("-j{}" , env:: var ( "NUM_JOBS" ) .
                                         unwrap (
                                         ))]).status().unwrap().success()', /home/sindikat/progs/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/harfbuzz-sys-0.1.2/build.rs:14
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

Anyway, thanks for your time and effort :D

**Comment by eddyb** [comment]
@sindikat Maybe the `buildInputs` list is missing `stdenv`? It's hard to tell, you want to have all the deps in `default.nix` - I guess `nix-shell --pure` is a way to make sure.

**Comment by sorpaas** [comment]
Probably it is better to use system rust and cargo?

**Comment by eddyb** [comment]
@sorpaas Only if they match the exact nightly Servo needs.

**Comment by grahamc** [comment]
While this doesn't build on NixOS, it does let me run the precompiled nightly with `nix-build . && ./result/runservo.sh`:

```nix
{ pkgs ? import <nixpkgs> {} }:
let

  rpath = with pkgs; pkgs.stdenv.lib.makeLibraryPath [
    dbus
    zlib
    freetype
    mesa
    mesa_drivers
    mesa_noglu

    openssl
    expat
    xorg.libX11
    xorg.libXmu
    xorg.libXcursor
    xorg.libXi
    xorg.libXext

  ] + ":${stdenv.cc.cc}/lib64";

  lpath = with pkgs; pkgs.stdenv.lib.makeLibraryPath [
    xorg.libXcursor
    xorg.libXi
    xorg.libXext
    xorg.libXxf86vm
  ] + ":${stdenv.cc.cc}/lib64";


in pkgs.stdenv.mkDerivation {
  name = "servo";
  src = ./servo-latest.tar.gz;

  buildInputs = with pkgs; [
    makeWrapper
  ];

  installPhase = ''
    ls -la
    patchelf \
      --set-rpath "${rpath}" \
      --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
      ./servo

    cp -r . $out

    wrapProgram $out/servo \
      --set LD_PRELOAD "$(cat $NIX_CC/nix-support/dynamic-linker)" \
      --set LD_LIBRARY_PATH "\$LD_LIBRARY_PATH:${lpath}"

    substituteInPlace $out/runservo.sh \
      --replace ./servo $out/servo
  '';
}
```

**Comment by eddyb** [comment]
I've updated my comment with a `default.nix` for `nix-shell --pure --run './mach build -r'`.
Which means it should work regardless of your system or user configuration.

**Comment by nox** [comment]
@eddyb So was this resolved? Can I close this issue? What remains to do?

**Comment by est31** [comment]
I tried to compile servo on Nix os 20.03 but couldn't get it recognize the installed gstreamer.

**Comment by petabyteboy** [comment]
I used the following shell.nix:

```
with import <nixpkgs> {};

clangStdenv.mkDerivation rec {
  name = "servo-env";
  buildInputs = [
    # Native dependencies
    fontconfig freetype openssl libunwind
    xlibs.libxcb x11

    gst_all_1.gstreamer
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-bad

    rustup

    # Build utilities
    cmake dbus gcc git pkgconfig which llvm autoconf213 perl yasm
    (python2.withPackages (ps: with ps; [virtualenv pip dbus]))
    (python3.withPackages (ps: with ps; []))
  ];

  LIBCLANG_PATH = llvmPackages.clang-unwrapped.lib + "/lib/";

  # Allow cargo to download crates
  SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt";

  # Enable colored cargo and rustc output
  TERMINFO = "${ncurses.out}/share/terminfo";
}
```

and ran `nix-shell --pure --run "./mach build -d"`

**Comment by petabyteboy** [comment]
> I tried to compile servo on Nix os 20.03 but couldn't get it recognize the installed gstreamer.

You probably used gstreamer 2.x while servo is using gstreamer 1.x which is confusingly available in the gst_all_1.* attributes.

**Comment by L-as** [comment]
FWIW that doesn't work for me on aarch64:
```
  ERROR: Failed building wheel for cffi
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```

**Comment by mkg20001** [comment]
I tried it and had to make some changes

- removed python2, using python3.withPackages
- added m4
- also `--pure` broke, had to just run `nix-shell --run "./mach build -r --with-layout-2020"`

```nix
with import <nixpkgs> {};

clangStdenv.mkDerivation rec {
  name = "servo-env";
  buildInputs = [
    # Native dependencies
    fontconfig freetype openssl libunwind
    xlibs.libxcb x11

    gst_all_1.gstreamer
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-bad

    rustup

    # Build utilities
    cmake dbus gcc git pkgconfig which llvm autoconf213 perl yasm m4
    (python3.withPackages (ps: with ps; [virtualenv pip dbus]))
  ];

  LIBCLANG_PATH = llvmPackages.clang-unwrapped.lib + "/lib/";

  # Allow cargo to download crates
  SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt";

  # Enable colored cargo and rustc output
  TERMINFO = "${ncurses.out}/share/terminfo";
}
```

**Comment by mkg20001** [comment]
It would make sense to put this in `etc/shell.nix` and then mention it for nix/nixOS people, so they can just run `nix-shell etc/shell.nix` and run mach inside it

Then I think this issue should be done?
