### ISSUE TITLE
Fix str_to_string test

### ISSUE THREAD

**Issue by Shiroy** [servo/servo#10474]
Since the commit [efa84862af9ba2659120fa16687c8d3b294a88e2](https://github.com/servo/servo/commit/efa84862af9ba2659120fa16687c8d3b294a88e2), the test `tests/compiletest/plugin/compile-fail/str_to_string.rs` fails which prevent Travis from running successfully.

**Comment by Ms2ger** [comment]
@Manishearth @KiChjang
