### ISSUE TITLE
Store a Box<Iterator> instead of Box<CollectionFilter> in HTMLCollection

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#10477]
Currently, the code in `HTMLCollection` assumes that we have a function that takes in an element and the root node and returns a boolean to filter out child nodes of the root. This is not sufficient and does not cover all use cases (as seen in #10086, it does not allow any manipulation of the ordering of the iterator items). Instead, what we should do is store a `Box<Iterator>` and use that as a source of getting the next element in the `HTMLCollection`.

Code: `components/script/dom/htmlcollection.rs` (and more files that uses HTMLCollection#new or HTMLCollection#create)

**Comment by slayerjain** [comment]
can i try this?

**Comment by perlun** [comment]
@KiChjang, looked at this very briefly, but it seems like we must specify the associated type as well. What should be the type in that case?

```
/Users/per/git/servo/components/script/dom/htmlcollection.rs:57:17: 57:35 error: the value of the associated type `Item` (from the trait `core::iter::Iterator`) must be specified [E0191]
/Users/per/git/servo/components/script/dom/htmlcollection.rs:57     filter: Box<Iterator + 'static>,
                                                                                ^~~~~~~~~~~~~~~~~~
/Users/per/git/servo/components/script/dom/htmlcollection.rs:57:17: 57:35 help: run `rustc --explain E0191` to see a detailed explanation
```

**Comment by KiChjang** [comment]
@perlun For now, I think it makes sense to have `Iterator<Item = Root<Node>>`.

**Comment by xudifsd** [comment]
if we use iterator then we would not need `root` anymore, right?

**Comment by xudifsd** [comment]
I've read the code and the spec, correct me if I'm wrong.

The problem you had in #10086 is that current implementation of `HTMLCollectionMethods` is relied on `FollowingNodeIterator` and `PrecedingNodeIterator`, which are in [tree order](https://dom.spec.whatwg.org/#concept-tree-order), but tree order is at odds with order requirement of table rows.

If I understand this right, `Box<Iterator>` is not sufficient, which only provides scan-once functionality. To implement `HTMLCollectionMethods`, we should be able to create preceding and following iterator on the fly, maybe passing two fns should be enough?

**Comment by KiChjang** [comment]
I'm not sure why `Root<Node>` isn't needed if we use an iterator. The nodes being iterated over should not be GC'd.

Note that you can mutate iterators and the result will still be an iterator, e.g. `iter.skip(3).filter(|x| > 5)` is still an iterator.

**Comment by xudifsd** [comment]
Well, I was wondering getting rid of `root` because I thought since we can get all needed elements from iterator, it would be nice to remove it.

Ah, so we can do reverse iteration by using `iter.reverse().next()`? I am trying to understand how to implement `HTMLCollectionMethods::Item` with only one-way & scan-once iterator.

**Comment by KiChjang** [comment]
I don't understand the 'one-way' and 'scan-once' terminology. Rust iterators are lazy evaluated (i.e. nothing is mutated/operated upon until you explicitly use .next()/.peek()/.collect()). For the use case I mentioned, I imagine using `.partition()` would be the way to go.

**Comment by xudifsd** [comment]
I mean in Java, Iterator can only move in one direction, it can not move backwards, and I assume this also applies to Rust. And from current implementation of `HTMLCollectionMethods::Item` we need to move backwards as in `HTMLCollection::elements_iter_before()`. I don't know how can we implement that function with `Box<Iterator>`.

**Comment by KiChjang** [comment]
As you've said before, `iter.reverse()` is indeed still an iterator, so boxing it would allow us to iterate backwards.

**Comment by Ms2ger** [comment]
I am skeptical that using an `Iterator` is the right design for `HTMLCollection`. Maybe @smaug---- has better ideas.

**Comment by smaug----** [comment]
FWIW, Gecko has different implementations of HTMLCollection. The normal case, used for element.children for example, keeps an array nodes, initially empty and populated on demand.
In case of dom mutation, the collection may be marked dirty, and next access will then need to re-populate itself. (HTMLCollection for commonly used DOM features is rather performance critical)

HTMLTableElement.rows has very different implementation. It plays with sub-HTMLCollections: tries to find elements first from thead.rows, then tbodies' rows, then from children of table elements (there is an internal HTMLCollection collection for those) and then tfoot's rows.  This implementation is way slower than the generic HTMLCollection implementation. For example indexing elements in the collection is O(n) in generic cases , not O(1) like in the normal HTMLCollection implementation.
(I noticed a difference in Gecko's .rows implementation comparing to the spec. Will file a implementation or spec bug.)

So, iterator for the generic case sounds like way too slow. You really want O(1) for indexing.
Iterator might be ok for some less commonly used cases.

**Comment by bzbarsky** [comment]
You also need O(1) `length`, which is not trivial to do with an iterator.  Basically, at a bare minimum you need to efficiently support this common pattern:

    for (var i = 0; i < collection.length; ++i) {
      doSomething(collection[i]);
    }

It's all the more common because `HTMLCollection` does not have `map()` or `forEach()` or anything like that...

**Comment by nox** [comment]
We can probably reuse the design I did for ChildrenList in our NodeList implementation.

https://github.com/servo/servo/blob/master/components/script/dom/nodelist.rs

**Comment by puhrez** [comment]
@KiChjang  So given @smaug---- is this still a desired refactor? If so I'd love to get on it with the help of who ever is mentoring :)

**Comment by KiChjang** [comment]
This is still a desired refactoring, but I'm unsure of what data structure that fits the requirements. Essentially, we need a data structure that has:
* O(1) indexing
* O(1) length

and iterators by itself cannot guarantee those two. We could use some caching but I'm unsure how it works.

**Comment by Ms2ger** [comment]
Not going to happen as filed, then.
