### ISSUE TITLE
small questions when building on freebsd

### ISSUE THREAD

**Issue by kworr** [servo/servo#1047]
Hi all. I'm trying to hack around a bit but I have some difficulties with your build system.

First of all, I'm doing this on FreeBSD. We still inherit old GCC v4.2.1 so gcc/g++ bails off when building rust:

    gmake[3]: Entering "/home/arcade/work/servo/build/x86_64-unknown-freebsd/src/compiler/rust/x86_64-unknown-freebsd/llvm/lib/Support"
    llvm[3]: Compiling APFloat.cpp for Release+Asserts build
    cc1plus: error: unrecognized command line option "-Wcovered-switch-default"
    rm: /home/arcade/work/servo/build/x86_64-unknown-freebsd/src/compiler/rust/x86_64-unknown-freebsd/llvm/lib/Support/Release+Asserts/APFloat.d.tmp: No such file or directory

How can I set build to use clang or gcc46 instead? I tried to create config section for freebsd in `configure` and set them with CC/CXX but it looks like settings are not propagated to subprojects.

Or can I skip building rust? We have 0.8 in ports:

    > rust -v
    rust 0.8
    host: x86_64-unknown-freebsd
    > which rust
    /usr/local/bin/rust

**Comment by jdm** [comment]
All of this has changed with the introduction of Cargo; let us know if this is still a problem!
