### ISSUE TITLE
Button text isn't centered vertically

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#10487]
This is because Servo treats `<button>` as a regular old inline-block, while Gecko, Blink, and WebKit don't. They have some sort of special handling for `<button>` height. I couldn't find this anywhere in the HTML5 spec.

This breaks ups.com.

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<button style="height: 50px; padding: 0 6px; background: lavender">Continue</button>
```

**Comment by pcwalton** [comment]
I've been pointed to this magic: http://lxr.mozilla.org/mozilla-central/source/layout/forms/nsHTMLButtonControlFrame.cpp#373

**Comment by Ms2ger** [comment]
We should probably get something into the spec. @zcorpan?

**Comment by pcwalton** [comment]
I suspect (but haven't confirmed) that this affects YouTube as well.

**Comment by zcorpan** [comment]
There's https://www.w3.org/Bugs/Public/show_bug.cgi?id=23893 but please file a new issue on html. Looking quickly at the Gecko code it seems like there's quite a bit of magic going on...

**Comment by Ms2ger** [comment]
https://github.com/whatwg/html/issues/1024

**Comment by nox** [comment]
Still not done.

**Comment by CYBAI** [comment]
whatwg/html#4143 landed in spec that it defines button layout at https://html.spec.whatwg.org/#button-layout

**Comment by zcorpan** [comment]
Test
`html/rendering/widgets/button-layout/anonymous-button-content-box.html`
in
https://github.com/web-platform-tests/wpt/pull/14824

**Comment by pwnorbitals** [comment]
I think it’s fixed by https://github.com/whatwg/html/pull/4143, is there any work left ?
