### ISSUE TITLE
Change task startup so we get some parallelism

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#1049]
Right now, we start from a task that is pinned to the main thread, in order to support the windowing system. However, spawning the constellation from that pinned thread leaves the constellation and its subtasks pinned to it as well, with the exception of those unlinked tasks spawned for pipeline isolation.

The workaround is to start up with a normal work-stealing task, which has both a task that is pinned to the main thread for the compositor and another (that will be a normal work-stealing task) for the constellation.

**Comment by jdm** [comment]
Not an issue after the switch away from green tasks, as I understand it.
