### ISSUE TITLE
Reflect HTMLInputElement content attributes

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#10491]
There is a slew of IDL attributes on HTMLInputElement which simply requires a setter and getter defined on them.

Spec: https://html.spec.whatwg.org/multipage/forms.html#dom-input-accept
Code: `components/script/dom/htmlinputelement.rs`, `components/script/webidls/HTMLInputElement.webidl`

**Comment by amarant** [comment]
I volunteer to take it.

**Comment by KiChjang** [comment]
Of course!

**Comment by KiChjang** [comment]
This issue still isn't complete yet; #10505 added the necessary WebIDL bindings, but did not update `parse_plain_attribute`. There are also different behaviours and default values when setting/getting these attributes.

I'll investigate and work more on this.

**Comment by amarant** [comment]
Ok, thanks for the help.
