### ISSUE TITLE
Android build fails with LLVM error

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#10517]
The Android build fails with the following error:

```
LLVM ERROR: Constant Island pass failed to converge!
Build failed, waiting for other jobs to finish...
error: Could not compile `cssparser`.

Caused by:
  Process didn't exit successfully: `rustc /home/mmatyas/Servo/servo-x64/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/cssparser-0.5.5/src/lib.rs --crate-name cssparser --crate-type lib -C opt-level=3 -C codegen-units=4 --cfg feature="heap_size" --cfg feature="serde" --cfg feature="serde_macros" --cfg feature="serde-serialization" --cfg feature="heapsize_plugin" --cfg feature="heapsize" -C metadata=a00db9153a066bec -C extra-filename=-a00db9153a066bec --out-dir /home/mmatyas/Servo/servo-x64/servo/target/arm-linux-androideabi/release/deps --emit=dep-info,link --target arm-linux-androideabi -C ar=arm-linux-androideabi-ar -C linker=/home/mmatyas/Servo/servo-x64/servo/components/servo/./fake-ld.sh -L dependency=/home/mmatyas/Servo/servo-x64/servo/target/arm-linux-androideabi/release/deps -L dependency=/home/mmatyas/Servo/servo-x64/servo/target/arm-linux-androideabi/release/deps --extern heapsize_plugin=/home/mmatyas/Servo/servo-x64/servo/target/release/deps/libheapsize_plugin-00846447151e4ac3.so --extern serde_macros=/home/mmatyas/Servo/servo-x64/servo/target/release/deps/libserde_macros-c550fbd19e352e36.so --extern encoding=/home/mmatyas/Servo/servo-x64/servo/target/arm-linux-androideabi/release/deps/libencoding-8b01435d6d00d080.rlib --extern matches=/home/mmatyas/Servo/servo-x64/servo/target/arm-linux-androideabi/release/deps/libmatches-030a774745cc4f96.rlib --extern heapsize=/home/mmatyas/Servo/servo-x64/servo/target/arm-linux-androideabi/release/deps/libheapsize-6b0058e51ea0ec07.rlib --extern serde=/home/mmatyas/Servo/servo-x64/servo/target/arm-linux-androideabi/release/deps/libserde-3a777b14c091f0d1.rlib --cap-lints allow -C link-args=-fuse-ld=gold -C target-feature=+neon` (exit code: 1)
```

I've tried on multiple systems, on Ubuntu 15.10 and 14.04, using Android NDK r10d. Here's a Travis log: https://travis-ci.org/mmatyas/servo-nightly/jobs/122117906

**Comment by eddyb** [comment]
Error comes [from an ARM-specific pass](https://github.com/llvm-mirror/llvm/blob/942c2d35cfac5ee48baf6d55357e628ee9ba515f/lib/Target/ARM/ARMConstantIslandPass.cpp#L474) which [can have its threshold increased](https://github.com/llvm-mirror/llvm/blob/942c2d35cfac5ee48baf6d55357e628ee9ba515f/lib/Target/ARM/ARMConstantIslandPass.cpp#L56-L58), presumably by setting:
```sh
RUSTFLAGS="-C llvm-args=-arm-constant-island-max-iteration=100"
```

However, comments indicate this is an extreme case - could you get the output of that `rustc` command with `--emit=llvm-ir`?

**Comment by mmatyas** [comment]
Running `RUSTFLAGS="-C llvm-args=-arm-constant-island-max-iteration=100" ./mach build -r --android` results in

```
rustc: Unknown command line argument '-arm-constant-island-max-iteration=100'.  Try: 'rustc -help'
rustc: Did you mean '-mips-constant-islands-small-offset=100'?
```

and adding `--emit=llvm-ir` to the failing `rustc` command in the first post results in

```
cfgspec:1:9: 1:21 error: unexpected token: `serde_macros`
cfgspec:1 feature=serde_macros
                  ^~~~~~~~~~~~
```

**Comment by eddyb** [comment]
Oh, I didn't check the LLVM branch Rust uses, which [hardcodes that limit](https://github.com/rust-lang/llvm/blob/25c7dc370359433ca02f29919dfa36f94432155e/lib/Target/ARM/ARMConstantIslandPass.cpp#L460) (so the option was added since the last Rust LLVM update).

**Comment by eddyb** [comment]
Looks like https://llvm.org/bugs/show_bug.cgi?id=25339 which has been fixed late February and Rust needs a LLVM update to get the fix. cc @alexcrichton

**Comment by alexcrichton** [comment]
Ah yeah it should be fine to backport the fix to our LLVM branch (currently [2016-03-13](https://github.com/rust-lang/llvm/tree/rust-llvm-2016-03-13)) at the time of this writing.

**Comment by mmatyas** [comment]
Just a note, the error also occurred when I tried to cross compile to ARM with `RUSTFLAGS=' -C target-feature=+neon'`.

**Comment by fabricedesre** [comment]
Is someone actively working on the LLVM backport?

**Comment by mmatyas** [comment]
Looks like this got fixed, so I'm closing the issue.
