### ISSUE TITLE
input's height is affected by parent's line-height

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#10532]
Test case:

``` html
<div style="line-height: 100px;">
    <input placeholder="foobar">
</div>
```

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/1777894/14442512/6fb63d48-003a-11e6-907e-1ee5f1112ebc.png)

Servo:
![servo](https://cloud.githubusercontent.com/assets/1777894/14442510/6a70a40e-003a-11e6-83f8-d46a65e54fdc.png)

**Comment by jdm** [comment]
I guess we should set this in servo.css as well.

**Comment by Sendoushi** [comment]
I never know how to start to contribute back... I guess it's my time!
This seems simple for me to solve! I'll try to do this today or tomorrow.

**Comment by jdm** [comment]
Great! Ask questions here if anything is confusing :)

**Comment by Sendoushi** [comment]
https://github.com/servo/servo/pull/10553

**Comment by kaksmet** [comment]
This only seems partially fixed.

### Servo
![servo](https://cloud.githubusercontent.com/assets/1777894/15154475/04ff36ac-16de-11e6-8651-c3ae9cbc2af4.png)

### Firefox
![firefox](https://cloud.githubusercontent.com/assets/1777894/15154480/07e98e80-16de-11e6-9bba-5f83cc0b40d9.png)

```html
foo
<div style="line-height: 100px;">
    <input placeholder="bar">
</div>
baz
```

**Comment by aethanyc** [comment]
I'm interested in this bug. I would like to give it a try.

**Comment by shinglyu** [comment]
@aethanyc is a layout expert!

**Comment by aethanyc** [comment]
The screenshot in https://github.com/servo/servo/issues/10532#issuecomment-218216432 seems like a bug in old version of firefox.

I open `tests/wpt/mozilla/tests/css/input_line_height.html` in Firefox 49, Chome, and Safari, and they all rendered like servo. We should close this bug.

**Comment by jdm** [comment]
Hooray!

**Comment by aethanyc** [comment]
I want to correct my previous comment, it's not the old Firefox bug. If the html does not specify `<!DOCTYPE html>`, the `line-height` will be ignore just like https://github.com/servo/servo/issues/10532#issuecomment-218216432 shown.  Both Chrome and Webkit do the same.  I guess this is for web-compat.  I guess servo does not worry about web-compat for now :)

**Comment by jdm** [comment]
Ah, that's a different matter, in that case. We do actually care about web compatibility!

**Comment by nox** [comment]
This looks ok now.
