### ISSUE TITLE
Empty span does not show border

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#10533]
Test case:
```html
<span>foo</span><br>
<span></span><br>
<span>bar</span>

<style>
span {
    border-left: 5px solid;
}
</style>
```

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/1777894/14443362/060e03ee-003f-11e6-8bdc-597f4aa6c4af.png)

Servo:
![servo](https://cloud.githubusercontent.com/assets/1777894/14443357/ffba941c-003e-11e6-8622-56f14d74a9ed.png)

**Comment by mbrubeck** [comment]
This is somewhat similar to #7681.  In an inline flow, fragments are responsible for drawing borders.  But the flow for the empty `span` doesn't have any fragments of its own.  Maybe `build_display_list_for_inline` needs a special case for empty inline flows.

**Comment by mbrubeck** [comment]
Actually, this is not just a display list issue; layout of the empty flow is often wrong too.  (For example if you remove the `br` elements from the test case above.)

**Comment by pcwalton** [comment]
Perhaps the right solution is to force creation of an inline fragment in flow construction if an empty span with certain styles (e.g. borders) is present?

**Comment by mbrubeck** [comment]
cc #2001
