### ISSUE TITLE
Replace  Fallible<()> return values with ErrorResult

### ISSUE THREAD

**Issue by zakorgy** [servo/servo#10541]
I found some Falible<()> return values in these files:
<pre>
script/dom/canvasrenderingcontext2d.rs
script/dom/element.rs
script/dom/htmliframeelement.rs
script/dom/websocket.rs
</pre>
As I noticed there is a 'pub type ErrorResult = Fallible<()> ; ' in script/dom/error.rs and used frequently.
Maybe these return return values should be replaced by ErrorResult for consistency.

**Comment by xudifsd** [comment]
I can work on this one

**Comment by KiChjang** [comment]
Alright!
