### ISSUE TITLE
Remove containing_page_pipeline_id

### ISSUE THREAD

**Issue by jdm** [servo/servo#10569]
There's a field in HTMLIFrameElement called `containing_page_pipeline_id` that I want to remove, since it isn't used outside of the file it's defined in. Its use in the `Navigate` method can be replaced with `window.pipeline()` instead.

Code: `components/script/dom/htmliframeelement.rs`

**Comment by ConnorGBrewster** [comment]
I would like to work on this one.

**Comment by KiChjang** [comment]
@ConnorGBrewster Do you mind working on less easy issues now? I'd like to reserve this for people who are completely new to the Servo codebase (or even Rust).

**Comment by ConnorGBrewster** [comment]
@KiChjang yup that is fine!

**Comment by sliz1** [comment]
I would like to take this one if it's still available :)

**Comment by jdm** [comment]
@sliz1 Please do!
