### ISSUE TITLE
Create a simple history storage

### ISSUE THREAD

**Issue by jdm** [servo/servo#1056]
No need for permanent storage, and no need to solve all the incompatibilities between browsers and the session history spec. We just want something we can update when we navigate to new pages and query from layout for styling visited links.

**Comment by nox** [comment]
@jdm We have a history now, don't we?

**Comment by KiChjang** [comment]
I'm very certain that we have a history nowadays, @asajeffrey and @cbrewster has been doing excellent work on that direction.
