### ISSUE TITLE
Use the document base url when resolving worker URLs

### ISSUE THREAD

**Issue by jdm** [servo/servo#10577]
According to [the specification](https://html.spec.whatwg.org/multipage/workers.html#dom-worker) (step 2), we need to be [using the base URL](https://html.spec.whatwg.org/multipage/infrastructure.html#parse-a-url). This means calling `global.api_base_url()` instead of `global.get_url()` as the code currently does.

Code: `components/script/dom/worker.rs`
Test:
```html
<base href="resources/"></base>
<script>
  var w = new Worker("worker.js");
</script>
```
Visit this from a web server (eg. `python -m SimpleHTTPServer`) with a `resources/` directory that contains a `worker.js` file that calls `console.log`.

There does not appear to be an automated test for this yet, so we'll need to [write a  test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests)! It belongs in `/tests/wpt/web-platform-tests/workers/constructors/Worker/`.

**Comment by creativcoder** [comment]
I'd like to work on it

**Comment by jdm** [comment]
Given your experience with Servo, I'd prefer to leave this for someone else making their first contribution.

**Comment by creativcoder** [comment]
Okay. that is fine. I guess ill, find something more adventurous to fiddle with.

This is available for anyone to work on.

**Comment by zubron** [comment]
I'd like to work on this issue if it's still available.

**Comment by notriddle** [comment]
Have at it!

**Comment by Ms2ger** [comment]
Hey @zubron, you need any help here?

**Comment by zubron** [comment]
Hi @Ms2ger - thanks for checking in. Apologies for not submitting sooner but it took me a bit longer that I had hoped to get the test working. I'm just about to submit the PR for this now :)
