### ISSUE TITLE
Use the document base url when resolving image URLs

### ISSUE THREAD

**Issue by jdm** [servo/servo#10574]
According to [the specification](https://html.spec.whatwg.org/multipage/embedded-content.html#update-the-image-data) (step 5.1), we need to be [using the base URL](https://html.spec.whatwg.org/multipage/infrastructure.html#parse-a-url). This means calling `document.base_url()` instead of `window.get_url()` as the code currently does.

Code: `components/script/dom/htmlimageelement.rs`
Test:
```html
<base href="resources/"></base>
<img src="image.png">
```
Visit this from a web server (eg. `python -m SimpleHTTPServer`) with a `resources/` directory that contains an `image.png` file.

There does not appear to be an automated test for this yet, so we'll need to [write a reference test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests)! It belongs in `tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/`.

**Comment by amarant** [comment]
Can I try this one ?

**Comment by jdm** [comment]
Please do!

**Comment by timvandermeij** [comment]
Fixed by #10634?
