### ISSUE TITLE
reddit.com rendering regression

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10571]
Reddit use to render more or less ok, but now, all the text is gone.

<img width="912" alt="screen shot 2016-04-13 at 18 00 32" src="https://cloud.githubusercontent.com/assets/373579/14500269/ad8ed5cc-01a1-11e6-8067-00cbb39284aa.png">

**Comment by metajack** [comment]
cc @pcwalton 
I noticed this last week as well. Also, this site takes minutes to load, and the progress bar in browserhtml never completed. I got quite a few webrender exceeding its draw budget (70ms!) while the whole page was still white except for the progress bar. Once the page drew something like in paul's screenshot, I started getting `RROR:js::rust: Error at https://www.redditmedia.com/ads/display/300x250#{"keywords": ["s.frontpage", "s.loggedout", "s.sfw"], "origin": "https://www.reddit.com"}:6:1: window.parent.frames[frame] is undefined` in a loop.

**Comment by paulrouget** [comment]
(Make sure to run browserhtml with these parameters `http://localhost:6060/index.html?progressbar=standalone&raf=timer` to work around some known progressbar issues)

**Comment by pcwalton** [comment]
@metajack Let's keep the network issues and WR rendering issues in separate bugs. I suspect the network issues are just speculative HTML parsing as usual. This bug should be about the text only.

**Comment by metajack** [comment]
@pcwalton opened #11008 and #11009 for those.

**Comment by pcwalton** [comment]
Blocking: https://github.com/servo/servo/pull/10903

**Comment by pcwalton** [comment]
Minimal test case:

    <!DOCTYPE html>
    <style>
    div {
        float: right;
        width: 300px;
        height: 15px;
        background: green;
    }
    section {
        margin-right: 300px;
        overflow: hidden;
        height: 80px;
        background: blue;
    }
    </style>
    <div></div>
    <section></section>

Pretty embarrassing that we don't have tests for this!

**Comment by pcwalton** [comment]
This is basically fixed now by #11125, but I'm holding off on closing because there's a crash (#10903, has a patch) on Reddit still.

**Comment by paulrouget** [comment]
Both #11125 and #10903 are fixed now. Closing.
