### ISSUE TITLE
Use the document base url when resolving iframe URLs

### ISSUE THREAD

**Issue by jdm** [servo/servo#10576]
According to [the specification](https://html.spec.whatwg.org/multipage/embedded-content.html#otherwise-steps-for-iframe-or-frame-elements) (step 1), we need to be [using the base URL](https://html.spec.whatwg.org/multipage/infrastructure.html#parse-a-url). This means calling `document.base_url()` instead of `window.get_url()` as the code currently does.

Code: `components/script/dom/htmliframeelement.rs`
Test:
```html
<base href="resources/"></base>
<iframe href="page.html">
```
Visit this from a web server (eg. `python -m SimpleHTTPServer`) with a `resources/` directory that contains a `page.html` file that is not empty.

There does not appear to be an automated test for this yet, so we'll need to [write a reference test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests)! It belongs in `tests/wpt/web-platform-tests/html/semantics/embedded-content/the-iframe-element/`.

**Comment by sliz1** [comment]
I would like to try this one if it's still available to learn a bit more about writing tests, but it's cool if @Liamsi is already working on it. :)

**Comment by Liamsi** [comment]
No, I didn't start working on it (still in the office). Feel free to work on it (and to assign it to @sliz1).

**Comment by jdm** [comment]
Go for it :)
