### ISSUE TITLE
Use the document base url when resolving stylesheets

### ISSUE THREAD

**Issue by jdm** [servo/servo#10575]
According to [the specification](
https://html.spec.whatwg.org/multipage/semantics.html#concept-link-obtain) (step 2), we need to be [using the base URL](https://html.spec.whatwg.org/multipage/infrastructure.html#parse-a-url). This means calling `document.base_url()` instead of `window.get_url()` as the code currently does.

Code: `components/script/dom/htmllinkelement.rs`
Test:
```html
<base href="resources/"></base>
<link rel="stylesheet" href="stylesheet.css"></link>
```
Visit this from a web server (eg. `python -m SimpleHTTPServer`) with a `resources/` directory that contains a `stylesheet.css` file with something like `body { background-color: green }`.

There does not appear to be an automated test for this yet, so we'll need to [write a reference test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests)! It belongs in `tests/wpt/web-platform-tests/html/semantics/document-metadata/the-link-element/`.

**Comment by canaltinova** [comment]
I would like to work on this.

**Comment by KiChjang** [comment]
Sure thing!

**Comment by canaltinova** [comment]
When i try to add a ref test in this directory, the command inserting 5453 lines to MANIFEST.json file. It seems not right. I'm using this command:
`./mach create-wpt --reftest tests/wpt/web-platform-tests/html/semantics/document-metadata/the-link-element/stylesheet-with-base.html --reference tests/wpt/web-platform-tests/html/semantics/document-metadata/the-link-element/stylesheet-with-base-ref.html` 

It seems trying to add all tests in `web-platform-tests` to manifest.json

**Comment by KiChjang** [comment]
I don't think you need --reference once you have --reftest (or was it the other way around?).

**Comment by jdm** [comment]
Both arguments are necessary, and sometimes that's what happens. Don't worry about all of the additions to MANIFEST.json if the new test is able to run.

**Comment by canaltinova** [comment]
Oh thanks, I tried also without arguments but didn't worked either. New test is able to run with first command. I'm creating a pr now :)
