### ISSUE TITLE
Use the document base url when resolving form action URLs

### ISSUE THREAD

**Issue by jdm** [servo/servo#10580]
According to [the specification](https://html.spec.whatwg.org/multipage/forms.html#attributes-for-form-submission), we need to be [using the base URL](https://html.spec.whatwg.org/multipage/infrastructure.html#parse-a-url). This means calling `document.base_url()` instead of `window.get_url()` as the code currently does (specifically, `make_url_or_base_getter`, which is used for the `action` and `formaction` attributes in elements like `HTMLFormElement`).

Code: `components/script/dom/macros.rs`
Test:
```html
<base href="resources/"></base>
<form action="target.html">
```
Visit this from a web server (eg. `python -m SimpleHTTPServer`) with a `resources/` directory that contains a `target.html` file that isn't empty.

There does not appear to be an automated test for this yet, so we'll need to [write a  test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests)! It belongs in `tests/wpt/metadata/html/semantics/forms/the-form-element/`. Specifically, it should have an iframe that contains a form with a base url, and the form should be submitted via JavaScript (`form.submit()`). The resulting page should notify the parent page that it was successful (`window.parent.some_success_function()`).

**Comment by Mylainos** [comment]
I would like to take this one please.

**Comment by jdm** [comment]
Go ahead!

**Comment by Mylainos** [comment]
So I need to add a .html in `tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/` and a .ini in `tests/wpt/metadata/html/semantics/forms/the-form-element/` ?

**Comment by jdm** [comment]
There should be no need for the ini if the test passes. Those files are used for annotation test results that are anything besides PASS.

**Comment by Mylainos** [comment]
I don't understand what should I put in `some_success_function()`. Is it something like that?
```
test(function(){
      assert_equals(...);
    }, ...);
```
Should I use this?
```
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
```

**Comment by jdm** [comment]
Assuming there is a `var t = async_test();` in the global scope, this could work:
```js
function some_success_function() {
    t.step_func_done();
}
```

**Comment by jdm** [comment]
@Mylainos Are you still working on this? Any questions?

**Comment by Mylainos** [comment]
@jdm I've a problem with the iframe.

**Comment by ferdypruis** [comment]
Is there a patch available for the bug itself?

**Comment by jdm** [comment]
Most recent attempt to solve this in #11219, which had some comments that needed addressing in https://github.com/servo/servo/pull/11219#issuecomment-223318881.

**Comment by rjgoldsborough** [comment]
I'll take a crack at this one, please

**Comment by jdm** [comment]
Please do! Ask questions about anything that's unclear!
