### ISSUE TITLE
Finish hooking up the XML parser

### ISSUE THREAD

**Issue by jdm** [servo/servo#10581]
#10371 was one attempt for this, but we don't think it was right (and no test changes were observed). We need to figure out what the missing pieces are at this point.

**Comment by jdm** [comment]
@ConnorGBrewster This would be a valuable task if you're interested.

**Comment by ConnorGBrewster** [comment]
@jdm yeah I can work on this one!

**Comment by jdm** [comment]
The basic goal here is to ensure that documents that have an [appropriate XML content type](http://stackoverflow.com/a/2965701/3830) end up being treated as XML documents (see `ScriptThread::load`). It would be useful to figure out what's currently broken in `tests/wpt/web-platform-tests/domparsing/DOMParser-parseFromString-xml.html`, for example.

**Comment by ConnorGBrewster** [comment]
Fixed in #10647
