### ISSUE TITLE
Windows build fails when finding '\' in module name (script BlobBinding)

### ISSUE THREAD

**Issue by zwn** [servo/servo#10596]
After locally fixing #10595 I get the following error:
```
C:\servo\target\debug\build\script-ea40c6ed2faaa354\out/Bindings/mod.rs:14:11: 14:12 error: unknown start of token: \\
C:\servo\target\debug\build\script-ea40c6ed2faaa354\out/Bindings/mod.rs:14 pub mod C:\servo\components\script\dom\webidls\BlobBinding;
```
It does not feel right to use absolute path name for a module name.

**Comment by jdm** [comment]
Looks like the implementation of `getModuleForObject` in `Configuration.py` needs to be modified to use `os.path.separator` instead of hardcoding `/`.

**Comment by Wafflespeanut** [comment]
Code: `components/script/dom/bindings/codegen/Configuration.py`

**Comment by zwn** [comment]
:+1: That did it. Now I have finally completed the build. I'll prepare PR hopefully later tonight.
