### ISSUE TITLE
Incorrect is_rect_valid checks in CanvasRenderingContext2D::drawImage.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10600]
Blocks #10597.

Nothing in the spec seems to support throwing `IndexSizeError`s with empty rectangles. The spec may have changed since we implemented it, though.

Unfortunately, there seem to be some tests that will start failing with this change (https://github.com/w3c/web-platform-tests/issues/2835). We probably need to write some more tests too.
- Spec: https://html.spec.whatwg.org/multipage/#dom-context-2d-drawimage.
- Code: `components/script/dom/canvasrenderingcontext2d.rs`.
- Test: at least `2dcontext/conformance-requirements/2d.voidreturn.html`.

**Comment by n0max** [comment]
Hi, I like to work on this.

The tests
`/2dcontext/conformance-requirements/2d.voidreturn.html`
`/2dcontext/drawing-images-to-the-canvas/2d.drawImage.zerosource.html`
are expected to fail and with the changes they pass.

What additional tests are required?

**Comment by jdm** [comment]
Running `./mach test-wpt tests/wpt/web-platform-tests/2dcontext` should not show any unexpected failures (only passes) with these changes.

**Comment by n0max** [comment]
I meant both tests are already changed for the current spec and set to FAIL in https://github.com/servo/servo/blob/17fe437fb72694763f0f7f1b4701127ebc2ef5aa/tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/2d.drawImage.zerosource.html.ini
and https://github.com/servo/servo/blob/234951e4b6d66891cd0cc9705f42e3ca16d9e3d5/tests/wpt/metadata/2dcontext/conformance-requirements/2d.voidreturn.html.ini 

Running `./mach test-wpt tests/wpt/web-platform-tests/2dcontext` shows
```
  ▶ Unexpected subtest result in /2dcontext/conformance-requirements/2d.voidreturn.html:
  └ PASS [expected FAIL] void methods return undefined

  ▶ Unexpected subtest result in /2dcontext/drawing-images-to-the-canvas/2d.drawImage.zerosource.html:
  └ PASS [expected FAIL] drawImage with zero-sized source rectangle draws nothing without exception
```

When I change the ini files to PASS the test runs without failures.
