### ISSUE TITLE
Typdefs are not generated in unions

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#10605]
Suppose I have the following:
```webidl
typedef (A or B or C) Foo;

DOMString bar(Foo or DOMString? qux);
```

The codegen currently does not generate `FooOrString` as expected - it would instead generate `AorBorCorDOMString`, and ignoring the typedef altogether.

**Comment by amarant** [comment]
I stumbled on that yesterday, and have a fix for it. I can make a PR later.
