### ISSUE TITLE
CanvasRenderingContext2D currentColor support is broken

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10601]
Blocks #10597.

At least for the not-rendered case. `style.GetPropertyValue(DOMString::from("color"))` returns the empty string, and parsing that fails.

* Spec: around <https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-height>.
* Code: `components/script/dom/canvasrenderingcontext2d.rs`.
* Test: `2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.removed.html`.

**Comment by craftytrickster** [comment]
I think I might be able to do this one.
