### ISSUE TITLE
Automatically build when packaging (with option to skip rebuild)

### ISSUE THREAD

**Issue by edunham** [servo/servo#10614]
https://github.com/servo/servo/blob/master/python/servo/post_build_commands.py#L268

@mbrubeck created this TODO in https://github.com/servo/servo/pull/8891/commits/53871321a3b22f14e31868405a9f98b31b529acc

**Comment by autrilla** [comment]
I'm interested in helping with this. `get_binary_path` on `command_base.py` is not going to help, because if the Android build is not found, it simply exits. I don't think exiting in this function is desirable in any case, it should raise an exception is nothing is found, and the calling function should be the one in charge of exiting or continuing appropriately. What do you think?

**Comment by edunham** [comment]
@autrilla The current logic appears to correctly handle cases where the android release has never been built -- in other words, the error message gets printed, which means that code at that location does get run. I think that the TODO line is in the correct place for where a build should be run; automatically rebuilding after a failed [attempt to package](https://github.com/servo/servo/blob/master/python/servo/post_build_commands.py#L274) could loop indefinitely on a misconfigured system.

In any case, I agree that it would be nice for `get_binary_path` to raise an informative error, with appropriate error handling everywhere it's called from.

**Comment by autrilla** [comment]
@edunham The error message that gets printed is not "Servo build not found. Please run `./mach build` to compile Servo." (the one on `post_build_commands.py`, but "No Servo binary found. Please run `./mach.build` and try again.", the one on `get_binary_path` on `command_base.py`. Line 268 on `post_build_commands.py` never gets executed, at least on my end.

**Comment by edunham** [comment]
@autrilla you're totally right; I didn't read the message closely. Definitely need to fix command_base.

**Comment by edunham** [comment]
@autrilla thanks for fixing this!
