### ISSUE TITLE
Make `mach_bootstrap.py` use a dependency resolver

### ISSUE THREAD

**Issue by edunham** [servo/servo#10611]
https://github.com/servo/servo/blob/bbdaf2262058fde6a938ccb47266e61b388d9727/python/mach_bootstrap.py#L184-L189

There are a variety of dependency resolvers suggested in the linked issue, https://github.com/pypa/pip/issues/988 

Steps: 
- [ ] Read https://github.com/pypa/pip/issues/988 and find a dependency resolver that looks good
    (for a value of "good" that includes works as expected, doesn't bring in too many extra dependencies of its own, actively maintained, has other projects are using it)
- [ ] Comment on this issue to discuss the proposed solution and address any concerns that it raises
- [ ] Refactor `mach_bootstrap.py` to use the selected resolver, and PR

**Comment by brainwane** [comment]
Regarding pip's dependency resolver: please [try the beta of the new resolver in pip 20.2](https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020) and see whether that helps?

**Comment by brainwane** [comment]
[Please try the beta of 20.3](https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020) and let us know if it helps!

**Comment by jdm** [comment]
Fixing that todo is a relatively low priority issue at the moment; in particular, it's tricky to figure out what version of pip actually gets used in our CI right now. Still, it's good to know that it's an option.
