### ISSUE TITLE
Can't enable logs on Android

### ISSUE THREAD

**Issue by alopatindev** [servo/servo#10624]
I was trying to apply something like `RUST_LOGS=debug` on Android (debug) build without success.

Is [this doc](https://github.com/servo/servo/wiki/Building-for-Android#viewing-rust_log-output) outdated? The first doubt was that the change might should be in main.**rs** not main.**cpp**

Trying this

```
diff --git a/components/servo/main.rs b/components/servo/main.rs
index 08ed645..64598d5 100644
--- a/components/servo/main.rs
+++ b/components/servo/main.rs
@@ -194,9 +194,9 @@ mod android {

     pub fn setup_logging() {
         use self::libc::{STDERR_FILENO, STDOUT_FILENO};
-        //use std::env;
+        use std::env;

-        //env::set_var("RUST_LOG", "servo,gfx,msg,util,layers,js,std,rt,extra");
+        env::set_var("RUST_LOG", "debug");
         redirect_output(STDERR_FILENO);
         redirect_output(STDOUT_FILENO);
```

—nothing changes, still none of `info!`, `debug!` or `println!` printing anything to `adb logcat`.

Calling `android_glue::write_log` directly doesn't print anything either. Because it calls `__android_log_write` with hardcoded log level `3` (ANDROID_LOG_DEBUG) that never worked for me (because "Debug logs are compiled in but [stripped at runtime](https://developer.android.com/reference/android/util/Log.html)") even with `android:debuggable="true"`. 

Changing it to `4` the direct call of `android_glue::write_log` is working but still `info!`, `debug!` and `println!` are not printing anything.

Does it work for anyone? How and on which device? Thanks!

P.S.: initially I wanted to enable logging on release builds (is that possible either?), so that [profiling thing](https://github.com/servo/servo/wiki/Profiling) could work. That would probably help to solve issues https://github.com/servo/servo/issues/7221 and https://github.com/servo/servo/issues/7211

**Comment by fabricedesre** [comment]
Closing as `env::set_var("RUST_LOG", "debug");` is now the default on android and logs are redirected to logcat properly.
