### ISSUE TITLE
compute_damage should use automatically-generated lists of CSS properties

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#10622]
[layout::incremental::compute_damage](https://github.com/servo/servo/blob/0c51259e4064e76ac180210c724af61bf15f8640/components/layout/incremental.rs#L165-L168) is supposed to check every CSS property, and set damage flags based on which properties have changed.  But we have no automatic test to make sure this contains every property, or that it is updated when new properties are added.

This information should instead be generated based on data in properties.mako.rs (or its eventual replacement, see #2028).

(As a further follow-up after this is done, it would also be very useful to statically enforce access to these properties based on their incremental layout category.  For example, only properties that set RECONSTRUCT_FLOW should be accessible during flow construction.  Properties that set only the REPAINT flag should not be accessible to layout code except for the display list builder.)

**Comment by nox** [comment]
Cc @emilio
