### ISSUE TITLE
Absolutely-positioned inlines don't respect line height if positioned next to a float

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#10625]
Fun one. Failing test case:

    <!DOCTYPE html>
    <div style="float: left; padding: 0 0 0 1px;"></div>
    <span style="position: absolute; right: 0; top: 0; line-height: 100px;">X</span>

This should have an X positioned 100px down the page on the right side, but in Servo the X is at the top right corner of the page.

Reduced from http://reddit.com/r/rust (the Edit link at the top).

**Comment by pcwalton** [comment]
Flow tree:

    ┌ Post layout flow tree
    │  ├─ Block(117a59a10) sc=StackingContextId(FragmentBody, 0) pos=LogicalRect(i1024px×b768px, @ (i0px,b0px)), floatspec-in=L 0px R 0px, floatspec-out=L 9px R 0px, overflow=Overflow { scroll: Rect(1024px×768px at (0px,0px)), paint: Rect(1024px×768px at (0px,0px)) } children=1 abs-descendents=1 damage=BUBBLE_ISIZES
    │  │  ├─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(7) [] border_box=LogicalRect(i1024px×b768px, @ (i0px,b0px)) damage=STORE_OVERFLOW
    │  │  ├─ Block(117a59790) sc=StackingContextId(FragmentBody, 0) pos=LogicalRect(i1024px×b0px, @ (i0px,b8px)), floatspec-in=L 0px R 0px, floatspec-out=L 9px R 0px, overflow=Overflow { scroll: Rect(1008px×0px at (8px,0px)), paint: Rect(1008px×0px at (8px,0px)) } children=2 damage=BUBBLE_ISIZES
    │  │  │  ├─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(4) [] border_box=LogicalRect(i1008px×b0px, @ (i8px,b0px)) margin=LogicalMargin(i:8px..8px b:8px..8px) damage=STORE_OVERFLOW
    │  │  │  ├─ Block(117a59010) sc=StackingContextId(FragmentBody, 4705382800) pos=LogicalRect(i1px×b0px, @ (i8px,b0px)), floatspec-in=L 0px R 0px, floatspec-out=L 1px R 0px, overflow=Overflow { scroll: Rect(1px×0px at (0px,0px)), paint: Rect(1px×0px at (0px,0px)) } damage=BUBBLE_ISIZES
    │  │  │  │  └─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(0) [] border_box=LogicalRect(i1px×b0px, @ (i0px,b0px)) border_padding=LogicalMargin(i:1px..0px b:0px..0px) damage=STORE_OVERFLOW
    │  │  │  ├─ Inline(117a711d0) sc=StackingContextId(FragmentBody, 0) pos=LogicalRect(i1008px×b0px, @ (i8px,b0px)), floatspec-in=L 1px R 0px, floatspec-out=L 1px R 0px, overflow=Overflow { scroll: Rect(0px×0px at (0px,0px)), paint: Rect(0px×0px at (0px,0px)) } children=1 damage=BUBBLE_ISIZES
    │  │  │  │  ├─ SpecificFragmentInfo::InlineAbsoluteHypothetical(3) [] border_box=LogicalRect(i0px×b0px, @ (i0px,b0px)) damage=STORE_OVERFLOW
    │  │  │  │  ├─ Block(117a59290) sc=StackingContextId(FragmentBody, 4705382944) pos=LogicalRect(i11.55px×b0px, @ (i1012.45px,b0px)), floatspec-in=L 1px R 0px, floatspec-out=L 1px R 0px, overflow=Overflow { scroll: Rect(11.55px×15.983333333333333px at (0px,0px)), paint: Rect(11.55px×15.983333333333333px at (0px,0px)) } children=1 damage=BUBBLE_ISIZES
    │  │  │  │  │  ├─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(2) [] border_box=LogicalRect(i11.55px×b0px, @ (i0px,b0px)) damage=STORE_OVERFLOW
    │  │  │  │  │  ├─ Inline(117a71010) sc=StackingContextId(FragmentBody, 4705382944) pos=LogicalRect(i11.55px×b0px, @ (i0px,b0px)), floatspec-in=L 1px R 0px, floatspec-out=L 1px R 0px, overflow=Overflow { scroll: Rect(11.55px×15.983333333333333px at (0px,0px)), paint: Rect(11.55px×15.983333333333333px at (0px,0px)) } damage=BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW
    │  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(1) ["X"] border_box=LogicalRect(i11.55px×b15.983333333333333px, @ (i0px,b0px)) damage=STORE_OVERFLOW | REFLOW_OUT_OF_FLOW | REFLOW

I think it's pretty likely that the InlineAbsoluteHypothetical is to blame.

**Comment by notriddle** [comment]
Are you, @pcwalton, working on this, or can I take it?

**Comment by pcwalton** [comment]
Feel free to grab it!
