### ISSUE TITLE
Make is::<T> return true for anything that derives from T as well

### ISSUE THREAD

**Issue by jdm** [servo/servo#10638]
It currently only checks for "is this object exactly a T", but that's never how I interpret it when reading code. This bites us when code checks for `is::<Document>` and the object is an XMLDocument.

cc @nox

**Comment by jdm** [comment]
Wait, the implementation in http://mxr.mozilla.org/servo/source/components/script/dom/bindings/inheritance.rs#17 looks like it does this already...

**Comment by ConnorGBrewster** [comment]
@jdm the issue I was having with XML parsing, was not from this. It was a couple of things, but ultimately updating the xml5ever dependency fixed the issue with parsing the xhtml tests.
