### ISSUE TITLE
`tidy` package needs cleanup to work on external deps

### ISSUE THREAD

**Issue by edunham** [servo/servo#10639]
In order to easily run `tidy` from dependencies' CI for https://github.com/servo/servo/issues/10636, we need a bit more Python packaging work: 

- [x] Declare an entry point, so that `tidy` can be run in the current directory by simply invoking `servo-tidy` on the command line. This'll involve adding something like the following to `setup()` in `setup.py` (note that the `tidy:scan` syntax might be wrong, though, so please test)

```
entry_points={
        'console_scripts': [
            'servo-tidy=tidy:scan',
        ],
    },
```

 - [x] Explicitly state the dependency on `flake8`, so it's installed with the package. See http://python-packaging.readthedocs.org/en/latest/dependencies.html for how. 

 - [x] Don't attempt to import wpt `tools.lint`  in https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py#L605 unless the `tests/wpt/web-platform-tests` directory exists in the current project. 

- [x] bump the minor version

@askeing, want to take this one?

**Comment by askeing** [comment]
@edunham I'd like to try this one, thx :)
