### ISSUE TITLE
Add `tidy` to dependencies' CI

### ISSUE THREAD

**Issue by edunham** [servo/servo#10636]
Creating a new issue to follow up on https://github.com/servo/servo/issues/861, since the packaging-tidy discussion took over that thread. 

The `servo_tidy` package is now available on pip at https://pypi.python.org/pypi/servo_tidy/0.0.1 . Currently changes to it need to be deployed manually (secrets are in the "servo build machine secrets" doc), but we can automate the process once it becomes clearer how often we'll need to bump the version.

From examining [the cargo.toml](https://github.com/servo/servo/blob/master/components/servo/Cargo.toml), I get this list of external dependencies that we should try to get `tidy` run on:
 Ours (do these first)
- [ ] https://github.com/servo/gaol/pull/26  ~~[NEEDS TO BE TIDIED]~~  
- [ ] https://github.com/servo/ipc-channel/pull/67 [NEEDS TO BE TIDIED]  
- [ ] https://github.com/servo/mozjs  
- [ ] https://github.com/servo/rust-azure/pull/222 [license and line length issues]  
- [ ] https://github.com/servo/rust-freetype/pull/39 [needs libc version pinned]  
- [ ] https://github.com/servo/rust-layers/pull/233  [license issues]  
- [ ] https://github.com/servo/rust-mozjs/pull/255  [license and line length issues]  
- [ ] https://github.com/servo/webrender  
- [x] https://github.com/servo/webrender_traits/pull/42

Others' (Discuss adding lint to their CI, or alternately run it ourselves)
- [ ] https://github.com/Ygg01/xml5ever  
- [ ] https://github.com/aweinstock314/rust-clipboard  
- [ ] https://github.com/browserhtml/browserhtml?branch=gh-pages  
- [ ] https://github.com/emilio/angle?branch=servo  
- [ ] https://github.com/ende76/brotli-rs  
- [ ] https://github.com/energymon/energymon-rust.git  
- [ ] https://github.com/energymon/energymon-sys.git  
- [ ] https://github.com/huonw/simd  
- [ ] https://github.com/jdm/tinyfiledialogs

**Comment by jdm** [comment]
I'm kind of ambivalent about asking authors of crates that are unrelated to Servo (except that we make use of them) to install our Servo-specific linter. For the license checks in particular, I wonder if we could make use of the crates.io API and fetch that data for local evaluation?

**Comment by edunham** [comment]
@jdm Good point. Do you think it'd be an appropriate compromise to ask the crate authors whether they'd be interested in running our lints, and if they aren't, run our own nightly check on clones of their repos to stay informed of how they compare? I expect that some maintainers will welcome the extra tests while others may disagree with the opinions enforced by the lints.

**Comment by jdm** [comment]
Most of our lints are for enforcing our code style rules (along with some common code nits). I don't think we gain any useful information by doing so, given how little we end up contributing to many of the crates we depend upon.

Another thing to point out is that Cargo.lock has the complete graph of our dependencies, which is a much larger list.

**Comment by Wafflespeanut** [comment]
This is gonna be fun! :smile:

**Comment by edunham** [comment]
The boilerplate for making `tidy` run in a non-python and containers+mac test suite is, in `.travis.yml`, 

```
before_script:
    - export PATH=$HOME/.local/bin:/Users/travis/Library/Python/2.7/bin:$PATH
    - pip install servo_tidy --user `whoami`

script:
    - servo-tidy
```

**Comment by UK992** [comment]
@edunham not that tidy's license validation logic and config file landed, it is possible to update ``servo_tidy`` on pip?

**Comment by edunham** [comment]
@UK992 thanks for the reminder! Pushed new version to PyPI and wrote down how to do it this time, https://github.com/servo/servo/wiki/Infrastructure#tidy-on-pypi

**Comment by jdm** [comment]
This work isn't going to happen.
