### ISSUE TITLE
Layout shouldn't try to lay out anything inside an <svg> element as HTML

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#10646]
We don't support SVG, but we sure shouldn't display anything for this document:

    <!DOCTYPE html>
    <svg><style>Uh</style></svg>

Let's just have the flow constructor ignore anything under an `<svg>` element.

This breaks fivethirtyeight.com.

**Comment by Swatinem** [comment]
I would like to take this on…
Will drop by later in IRC to ask for guidance :-)

**Comment by jdm** [comment]
I would have guessed the `new` method for `BaseFlow`, but I don't see a way to figure out if it's an `<svg>` from inside of it.

**Comment by jdm** [comment]
We might just be able to use `svg > * { display: none }` in servo.css.
