### ISSUE TITLE
Support Dates in webidl code gen

### ISSUE THREAD

**Issue by peterjoel** [servo/servo#10675]
Code gen currently doesn't support webidl files that contain Date types.

There are actually two parts to this. Firstly, support dates in general: currently they trigger an error `TypeError: Need conversion for argument type 'Date'`. Secondly, if a date is used as a distinguishing argument for a constructor, then there will be a different Rust compile error in the code generated by [this line](https://github.com/servo/servo/blob/155e4052d150179ea8423a7ea626a84e25409718/components/script/dom/bindings/codegen/CodegenRust.py#L445) because `JS_ObjectIsDate` isn't imported.

To test this, I added an extra constructor [to this test binding](https://github.com/servo/servo/blob/master/components/script/dom/webidls/TestBinding.webidl#L75) like this:

```
[Constructor,
 Constructor(sequence<unrestricted double> numberSequence),
 Constructor(unrestricted double num),
 Constructor(Date d)
]
```

This will test both of the points above.

**Comment by Ms2ger** [comment]
What do you need it for?

**Comment by peterjoel** [comment]
@Ms2ger I don't specifically need it. I noticed that [this line](https://github.com/servo/servo/blob/155e4052d150179ea8423a7ea626a84e25409718/components/script/dom/bindings/codegen/CodegenRust.py#L445) would generate invalid code, and thought I'd try to fix it. From there, I found that dates were not working at all.

**Comment by nox** [comment]
There are no `Date` in the WebIDL spec. Closing.
