### ISSUE TITLE
Implement uniformMatrix*v

### ISSUE THREAD

**Issue by autrilla** [servo/servo#10671]
Part of #10209.

**Comment by KiChjang** [comment]
Previous work (#11065) has stalled, this is open for anyone else to claim.

**Comment by anholt** [comment]
I'm testing a branch for this now.

**Comment by anholt** [comment]
Unmergeable branch at https://github.com/anholt/servo/commit/35f49c0e31f94fe71132b92c93f01d0de2c96b34

**Comment by anholt** [comment]
Merged in:

    commit 61debe5c01996f667b352951bb7cc6c8dab7b2a9
    Author: Eric Anholt <eric@anholt.net>
    Date:   Sat Sep 17 19:40:42 2016 +0100
    
        webgl: Implement uniformMatrix*fv.
