### ISSUE TITLE
Report for loops using iter() and iter_mut() unnecesarily

### ISSUE THREAD

**Issue by jdm** [servo/servo#10683]
Rust allows using `for foo in &bar` instead of `for foo in bar.iter()`, and `for foo in &mut bar` instead of `for foo in bar.iter_mut()`. Let's add a check to `check_rust` that warns about instances of `.iter()` and `.iter_mut()` that could be replaced. There are a lot of existing instances of this pattern that will need replacing, too.

Note: patterns like `for foo in bar.iter().enumerate()` (ie. places where the return value of `iter()` is further refined) cannot be replaced and shouldn't be reported.

Code: `python/tidy/servo_tidy/tidy.py`
Tests: add a test to `python/tidy/servo_tidy_tests/test_tidy.py` and run it via `./mach test-tidy --self-test`

**Comment by aeischeid** [comment]
Since I was touching the check_rust method earlier I think I have the sense for how to do this. 

"places where the return value of iter() is further refined..." - I am only a little bit familiar with Rust syntax. Are there cases where the return val might be further refined but .iter() is followed by a space character?

**Comment by jdm** [comment]
That shouldn't be possible, no.

**Comment by aeischeid** [comment]
think I may be close on defining the rule and the test cases, but stuck on why the tests are failing when I don't expect them to. see commit in my branch https://github.com/aeischeid/servo/commit/57f54833c3b54f2d3f778481d7f41d9fee3e43b9

**Comment by Wafflespeanut** [comment]
I'm removing the easy label, since this can't be fixed straightaway (given the conclusion we've arrived at #11116). Maybe we should have a todo list in the issue mentioning which types need the `Iterator` trait for us to go about fixing this.

**Comment by nox** [comment]
We have some types that have an `iter` method but don't even implement `IntoIterator`. I think that's a job better left to Clippy. Closing.
