### ISSUE TITLE
CSS.escape test failures

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10685]
These need investigation:
```
  ▶ Unexpected subtest result in /cssom-1_dev/html/escape.htm:
  │ FAIL [expected PASS] Null bytes
  └   → The string contains invalid characters.
  ▶ Unexpected subtest result in /cssom-1_dev/html/escape.htm:
  │ FAIL [expected PASS] Various tests
  │   → assert_equals: expected "\\1 \2 \1e \1f " but got "\\\x01\\x02\\x1e\\x1f"
  │ 
  │ @http://web-platform.test:8000/cssom-1_dev/html/escape.htm:71:1
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1226:20
  │ test@http://web-platform.test:8000/resources/testharness.js:427:9
  └ @http://web-platform.test:8000/cssom-1_dev/html/escape.htm:70:1
```

Possibly the spec changed; I don't know if the Servo implementation or the test needs changing. (If the latter, submit to <https://github.com/w3c/csswg-test>.)

**Comment by mskrzypkows** [comment]
The spec didn't change. There is InvalidCharacter error in [css.rs](https://github.com/servo/servo/blob/master/components/script/dom/css.rs#L20)
Investigating why '\0' is invalid.

**Comment by mskrzypkows** [comment]
Added commit to rust-cssparser, another change I'll do for servo, when the commit will be merged.

**Comment by mskrzypkows** [comment]
Patch is merged, should I wait for new version of rust-cssparser to use it in servo?

**Comment by Ms2ger** [comment]
I published cssparser; you should be able to `./mach cargo-update -p cssparser`.
