### ISSUE TITLE
webgl: Implement a type safe wrapper for WebGL-related validations

### ISSUE THREAD

**Issue by emilio** [servo/servo#10693]
See the discussion in https://github.com/servo/servo/pull/10443#issuecomment-211566609

Basically, doing our WebGL validations using a more strongly-typed system is worth it, not just because of improved readability, but also for improved safety.

Probably a good API for this is not trivial to design.

As an example, I proposed the following two patterns:
### `Validator`

``` rust
trait AsGLError {
    fn as_gl_error(&self) -> WebGLError;
}

trait Validator {
    type Input;
    type Error: std::error::Error + AsGLError;
    type Validated;

    // NB: if something from Self::Input should be used
    // afterwards, it should be returned in Self::Validated,
    // this could prevent accidentally accessing invalid data.
    fn validate(Self::Input) -> Result<Self::Validated, Self::Error>;
}
```
### `Validable`

``` rust
trait Validable {
    type Valid;
    type Error: std::error::Error + AsGLError;
    fn validate(self) -> Result<Self::Valid, Self::Error>;
}

impl Validable for TexImage2DParams { ... }
```

These are just quick examples, and some other approach might be taken. I plan to do this once I have a bit more free time, probably after these two weeks, but I might jump into it sooner if I find the time.

Nontheless, if any contributor wants to do it I'm more than happy to assign it to him and help him :-)

cc @jdm

**Comment by nox** [comment]
@emilio Did #11724 fix this? If not, what remains to be done?

**Comment by nox** [comment]
I don't think this is useful to keep open.
