### ISSUE TITLE
Report lines that start with a logical operator (&& or ||)

### ISSUE THREAD

**Issue by jdm** [servo/servo#10692]
The code style we follow recommends that operators go at the end of the first line when splitting across multiple lines. We should add a check to `check_rust` that looks for lines that start with optional whitespace followed by `&&` or `||`.

Code: `python/tidy/servo_tidy/tidy.py`
Test: we should add a test to `python/tidy/servo_tidy_tests/` and run it via `./mach test-tidy --self-test`

**Comment by mbrubeck** [comment]
There are a number of places where we have `||` at the start of a line but it is the beginning of a closure, not an operator.  I'm not sure if there's a good way to detect this, besides rustfmt.

**Comment by jdm** [comment]
Blech. Maybe limit this check to && to start.

**Comment by Wafflespeanut** [comment]
Am I right that the only place where we should avoid checking `||` is when it's inside a parentheses? Looking at the code, almost all the closures already have whitespaces around them, other than the ones like, `thing(|| ...`

**Comment by frewsxcv** [comment]
```rust
let a = || ();
```

Is a valid Rust statement (`a` is a closure that returns a unit type `()`). It doesn't fall within parenthesis.

**Comment by Wafflespeanut** [comment]
Yeah, and it does have spaces around `||`. If tidy suggests that we should write `a = || ()`, instead of `a = ||()` (or something else), isn't that better? I was thinking of situations where tidy shouldn't enforce having whitespace around `||`, and `closure_getting_fn(|| ...)` seemed to be the only place.

**Comment by zwn** [comment]
I'll start with '&&'.

**Comment by zwn** [comment]
@jdm Thanks for a great task description!

**Comment by SimonSapin** [comment]
Is it really a useful thing to enforce? Python recommends the opposite https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

Also, are we re-inventing half of rustfmt in Python without a proper Rust parser?

**Comment by jdm** [comment]
@SimonSapin Consistent style is useful, and we've traditionally requested operators be on the previous line. rustfmt doesn't satisfy our needs yet, and I want to minimize the number of stylistic things that I look out for in reviews.

**Comment by Wafflespeanut** [comment]
#10751 fixes `&&`. Are we planning to make a move on `||`?

**Comment by jdm** [comment]
I think it's worth seeing if any instances are reported.

**Comment by webmaven** [comment]
Have any instances of ```||``` been reported since April 27th?

**Comment by jdm** [comment]
Nobody's looked into writing the check. I've seen some valid uses in the code, though, so I don't think it's worth leaving this open.
