### ISSUE TITLE
Remove extra definition of WHITESPACE under components/util/str.rs

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#10709]
`HTML_SPACE_CHARACTERS` already does the same job and it looks like it is being used more than `WHITESPACE`

Code: `components/util/str.rs`, and all other files that reference `util::str::WHITESPACE`

**Comment by zakorgy** [comment]
Can I try this one?

**Comment by KiChjang** [comment]
Sure thing!

**Comment by KiChjang** [comment]
Fixed in #10745.
