### ISSUE TITLE
Initial canvas creation relies on DOM width and height attributes, but layout relies on computed width and height

### ISSUE THREAD

**Issue by jdm** [servo/servo#10705]
Tests like `texture-size-limit.html` in the webgl suite use `<canvas id="example" width="32" height="32" style="width: 40px; height: 40px;"></canvas>` and this screws us up in a delightful fashion, since `HTMLCanvasElement::get_size` uses `Width()` and `Height()`. This is a cause of assertions where the pixel data retrieved from webgl doesn't match the stride * height that layout expects.

cc @emilio

**Comment by Ms2ger** [comment]
We're unfortunately supposed to scale for code like that.
