### ISSUE TITLE
Report lines that are missing a space after `:`

### ISSUE THREAD

**Issue by jdm** [servo/servo#10702]
For members of structures, we want to catch any lines like `member_name:5`. We should add a rule to `check_rust` to enforce this code style.

Code: `python/tidy/servo_tidy/tidy.py`
Test: add a test to `python/tidy/servo_tidy_tests/test_tidy.py` and run with `./mach test-tidy --self-test`

**Comment by aeischeid** [comment]
Totally new to Servo, but looking for a way to contribute. Novice with Python, but looks like this would be more heavy on the regex with lots of similar python examples to work from.

I would guess not, but as part of this would you want fixes for the lines this would report on too?

**Comment by aeischeid** [comment]
`member_name:5` should be `member_name: 5` ?

**Comment by KiChjang** [comment]
No need for fixes, we just test-tidy to report on such occurrences. And yes to your second question.

**Comment by jdm** [comment]
Well, we can't merge the new check if there are any existing incorrect lines, so yes, fixes may be required.

**Comment by aeischeid** [comment]
is this a valid struct in rust for the test? 

``` rust
struct member {
    member_name:"Foo"
    member_id:5
}

**Comment by KiChjang** [comment]
Oh, sorry, I misunderstood, I thought you meant using the test-tidy tool to fix the code that has problems. You'll have to manually fix those lines that have problems. And that looks like a good test case.

**Comment by aeischeid** [comment]
Got it close I think. Not catching the strings quite right yet for reason unknown to me. 

`./mach test-tidy` passed, so it looks like there are no lines to fix

**Comment by timvandermeij** [comment]
Fixed by #10713?

**Comment by jdm** [comment]
Yep!
