### ISSUE TITLE
Tidy needs smarter license validation logic

### ISSUE THREAD

**Issue by edunham** [servo/servo#10716]
Currently right [here](https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py#L130), we're blindly comparing a file's license against those listed in https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/licenseck.py. This causes tidy to needlessly fail a repo when the copyright year differs from one in a valid license header. I haven't found an example yet, but it would also cause spurious failure if the lines weren't wrapped to 80chars like in the examples.

A more robust variation of this logic would be: 

* take every line until the first blank line of the file after the 5th line (to account for a #! and editor configs)
* in that block, remove the comment stuff. This could be done either by removing all `^/*`, `^ *`, `^# `, and `^// `, or by blindly removing the first 2 characters of each line then removing any spaces that are the first character of a line
* replace all newlines with spaces
* Call the license valid if either of the following strings occurs in what's left:
```
Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option. This file may not be copied, modified, or distributed except according to those terms.

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
```

**Comment by aneeshusa** [comment]
+1, this also makes the license check to be orthogonal to the shebang check; right now one of the license header options hard-codes a python shebang, but these should be checked separately.
