### ISSUE TITLE
Implement the "focusevent" argument to Document::createEvent

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10739]
Blocks #2185, #10734.

This will involve writing a `new_uninitialized` function on `FocusEvent` and calling it from `Document::CreateEvent`.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createevent>, <https://w3c.github.io/uievents/#focusevent>.
* Code: `components/script/dom/document.rs`, `components/script/dom/focusevent.rs`.
* Test: `dom/nodes/Document-createEvent.html`.

**Comment by SunyDays** [comment]
Can I take it or I must to wait review of my first PRs?

**Comment by jdm** [comment]
Go for it!
