### ISSUE TITLE
Implement the "closeevent" argument to Document::createEvent

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10737]
Blocks #2185, #10734.

This will involve writing a `new_uninitialized` function on `CloseEvent` and calling it from `Document::CreateEvent`.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createevent>, <https://html.spec.whatwg.org/multipage/#closeevent>.
* Code: `components/script/dom/document.rs`, `components/script/dom/closeevent.rs`.
* Test: `dom/nodes/Document-createEvent.html`.

**Comment by KuoE0** [comment]
I'd like to try on this issue! Are there some references I can study? Thanks!

**Comment by Ms2ger** [comment]
Go for it! You can look at existing `Event` classes like `UIEvent`.

**Comment by mrmiywj** [comment]
@KuoE0 Hi, what's your progress? If you don't have time, I will try this.

**Comment by KuoE0** [comment]
Hi @mrmiywj, I want to work on this. But if you already finished on this, feel free to take it. Sorry, I was busy on other works recently.
