### ISSUE TITLE
Implement the "storageevent" argument to Document::createEvent

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10736]
Blocks #2185, #10734.

This will involve writing a `new_uninitialized` function on `StorageEvent` and calling it from `Document::CreateEvent`.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createevent>, <https://html.spec.whatwg.org/multipage/#storageevent>.
* Code: `components/script/dom/document.rs`, `components/script/dom/storageevent.rs`.
* Test: `dom/nodes/Document-createEvent.html`.

**Comment by mskrzypkows** [comment]
I'd like to take this one.

**Comment by Ms2ger** [comment]
Go for it!
