### ISSUE TITLE
Implement the :read-only and :read-write pseudo-classes

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10732]
Blocks #2968.

* Spec: <https://html.spec.whatwg.org/multipage/#selector-read-only>.
* Code: `components/style/selector_impl.rs`, `components/layout/wrapper.rs`, `components/script/dom/element.rs`.
* Test: `html/semantics/selectors/pseudo-classes/readwrite-readonly.html`.

But note <https://lists.w3.org/Archives/Public/www-style/2016Apr/0294.html>.

**Comment by yoava333** [comment]
I'd like to try this one

**Comment by jdm** [comment]
OK!

**Comment by yoava333** [comment]
I finished with an initial implementation, but I have two issues:
1. we don't have support for several input type (e.g. image, range, color...), which are defaulted to input text. that means that my logic for read-write, which operates on input text type is wrong when dealing with those elements.
2. we don't support contenteditable, which is supposed to be read-write

What do you suggest to do in those situations?

**Comment by Ms2ger** [comment]
It's fine to only support the pseudo-classes for cases where we already implement the read/writability

**Comment by jdm** [comment]
Fixed by #10834.
