### ISSUE TITLE
Implement Node::isSameNode

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10746]
Blocks #2185.

Fixing this bug will allow you to say you implemented one of the most useless features in the Web platform.

* Spec: <https://dom.spec.whatwg.org/#dom-node-issamenode>.
* Code: `components/script/dom/node.rs`, `components/script/dom/webidls/Node.webidl`.
* Test: to be [written](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) (at `dom/nodes/Node-isSameNode.html`).

**Comment by amarant** [comment]
Can I take this one ?

**Comment by jdm** [comment]
Sure :)
