### ISSUE TITLE
Implement Node::rootNode

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10747]
Blocks #2185.

* Spec: <https://dom.spec.whatwg.org/#dom-node-rootnode>.
* Code: `components/script/dom/node.rs`, `components/script/dom/webidls/Node.webidl`.
* Test: `dom/nodes/rootNode.html`.

**Comment by ineol** [comment]
I would like to take this one please.

**Comment by Ms2ger** [comment]
Go for it!
