### ISSUE TITLE
Implement the "svgevents" argument to Document::createEvent

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10741]
Blocks #2185, #10734.

This will involve adding "svgevents" to the "htmlevents" match condition in `Document::CreateEvent`.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createevent>.
* Code: `components/script/dom/document.rs`.
* Test: `dom/nodes/Document-createEvent.html`.

**Comment by SunyDays** [comment]
I'd like to work on this issue.

**Comment by KiChjang** [comment]
Go for it!
