### ISSUE TITLE
Implement the "progressevent" argument to Document::createEvent

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10740]
Blocks #2185, #10734.

This will involve writing a `new_uninitialized` function on `ProgressEvent` and calling it from `Document::CreateEvent`.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createevent>, <https://xhr.spec.whatwg.org/#progressevent>.
* Code: `components/script/dom/document.rs`, `components/script/dom/progressevent.rs`.
* Test: `dom/nodes/Document-createEvent.html`.

**Comment by SunyDays** [comment]
Can I take it?

**Comment by jdm** [comment]
@SunyDays Since you've fixed a few of these already, could you leave the rest for other new contributors?

**Comment by SunyDays** [comment]
Of course. I'll see something else.

**Comment by sliz1** [comment]
I would like to take this :)

**Comment by Ms2ger** [comment]
Go for it!
