### ISSUE TITLE
Implement Element::hasAttributes

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10748]
Blocks #2185.

* Spec: <https://dom.spec.whatwg.org/#dom-element-hasattributes>.
* Code: `components/script/dom/element.rs`, `components/script/dom/webidls/Element.webidl`.
* Test: to be written (at `dom/nodes/Element-hasAttributes.html`).

**Comment by canaltinova** [comment]
I would like to work on this one.

**Comment by jdm** [comment]
Please do!
