### ISSUE TITLE
DOMImplementation::createDocument should set content type based on namespace

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10743]
Blocks #2185.

This will involve passing the appropriate argument to the `XMLDocument` constructor.

* Spec: <https://dom.spec.whatwg.org/#dom-domimplementation-createdocument>.
* Code: `components/script/dom/domimplementation.rs`.
* Test: `./mach test-wpt dom/nodes/DOMImplementation-createDocument.html`.

**Comment by cjkenn** [comment]
I'd like to take this on if no one else has...

**Comment by jdm** [comment]
Please do! Ask questions about anything that's confusing :)

**Comment by cjkenn** [comment]
#10830
