### ISSUE TITLE
Canvases without contexts should not draw anything

### ISSUE THREAD

**Issue by jdm** [servo/servo#10755]
In `build_fragment_type_specific_display_items` we have code that deals with obtaining the pixels of a canvas element. In the event that the canvas has no context (ie. `canvas.getContext('2d')` hasn't been called) we currently synthesize a vector of opaque white pixels. This doesn't match what any other browser does, and we should just ignore it instead.

Code: `components/layout/display_list_builder.rs`
Test: a [reference](http://testthewebforward.org/docs/reftests.html) test needs to be [written](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) and added to `tests/wpt/mozilla/tests/css/`.

```html
<style>
div {
  width: 20px;
  height: 20px;
  background-color: green;
}
</style>
<div><canvas width="20" height="20"></canvas></div>
```

**Comment by daoshengmu** [comment]
I wanna try this bug. I take this.

**Comment by jdm** [comment]
Please do!

**Comment by daoshengmu** [comment]
Sorry, I am very new to servo. I know I need to ignore this while  ```canvas_fragment_info.ipc_renderer``` get ```None``` message. 

Could you tell me what I should put at the ```None``` case of ```canvas_fragment_info.ipc_renderer```.

**Comment by Ms2ger** [comment]
@jdm I think we actually synthesize transparent black, per

> When its canvas context mode is none, a canvas element has no rendering context, and its bitmap must be fully transparent black with an intrinsic width equal to the numeric value of the element's width attribute and an intrinsic height equal to the numeric value of the element's height attribute, those values being interpreted in CSS pixels, and being updated as the attributes are set, changed, or removed.

**Comment by jdm** [comment]
@Ms2ger No, the code in question definitely creates a vector of 0xFF bytes.

**Comment by jdm** [comment]
@daoshengmu I think we can probably just return immediately from that code.
