### ISSUE TITLE
Support [] default value for sequences

### ISSUE THREAD

**Issue by jdm** [servo/servo#10763]
Adding `void passOptionalSequenceWithDefault(optional sequence<long> seq = []);` or `dictionary Foo { sequence<DOMString> = []; };` yields `TypeError: Can't handle non-null default value here`.

**Comment by tigercosmos** [comment]
@jdm could you explain more?

**Comment by jdm** [comment]
If we add `void passOptionalSequenceWithDefault(optional sequence<long> seq = []);` to `components/script/dom/webidls/TestBinding.webidl`, we get a TypeError when executing CodegenRust.py, and it comes from https://dxr.mozilla.org/servo/rev/edb2db55b7fd72370a90fc65c5984d6b7e0f792f/components/script/dom/bindings/codegen/CodegenRust.py#674.

**Comment by KiChjang** [comment]
@tigercosmos Are you interested in working on this?

**Comment by tigercosmos** [comment]
Not now. Please take it.

**Comment by saschanaz** [comment]
Fixed by #22084
