### ISSUE TITLE
Use `optional` for the Blob constructor

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10779]
Blocks #2185.

To match https://github.com/w3c/FileAPI/issues/33

* Spec: <https://w3c.github.io/FileAPI/#blob>.
* Code: `components/script/dom/blob.rs`, `components/script/dom/webidls/Blob.webidl`.
* Test: `FileAPI/blob/Blob-constructor.html`.

**Comment by yoava333** [comment]
I'd like to take this

**Comment by jdm** [comment]
It's yours!
