### ISSUE TITLE
Intermittent TIMEOUT in /webgl/conformance-1.0.3/conformance/rendering/gl-scissor-test.html

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#10772]
▶ TIMEOUT [expected OK] /webgl/conformance-1.0.3/conformance/rendering/gl-scissor-test.html
      │ 
      │ DESCRIPTION: Check if glScissor setting works.
      │ test antialias: false
      │ PASS context exists
      │ 
      │ test with clear
      │ checking rect: effective width or height is zero
      │ PASS should be black
      │ ERROR:js::rust: Error at http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1034:4: gl.readPixels is not a function
      │ 
      │ FAIL successfullyParsed should be true (of type boolean). Was undefined (of type undefined).
      │ TEST COMPLETE
      │ thread 'PaintWorker' panicked at 'assertion failed: (data.len() as i32) >= stride * size.height', /Users/servo/.cargo/git/checkouts/rust-azure-97bcec2370a94878/master/src/azure_hl.rs:710
      │ stack backtrace:
      │    1:        0x1022d42d8 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
      │    2:        0x1022da5b5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
      └    3:        0x1022da1ce - std::panicking::default_hook::h08ad3bb09872855b

**Comment by jdm** [comment]
#10727.
