### ISSUE TITLE
Intermittent TIMEOUT in /webgl/conformance-1.0.3/conformance/misc/instanceof-test.html

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#10773]
▶ TIMEOUT [expected OK] /webgl/conformance-1.0.3/conformance/misc/instanceof-test.html
      │ 
      │ DESCRIPTION: WebGL instanceof test.
      │ Tests that instanceof works on WebGL objects.
      │ 
      │ PASS gl instanceof WebGLRenderingContext is true
      │ PASS gl.createBuffer() instanceof WebGLBuffer is true
      │ PASS gl.createFramebuffer() instanceof WebGLFramebuffer is true
      │ PASS gl.createProgram() instanceof WebGLProgram is true
      │ PASS gl.createRenderbuffer() instanceof WebGLRenderbuffer is true
      │ PASS gl.createShader(gl.VERTEX_SHADER) instanceof WebGLShader is true
      │ PASS gl.createTexture() instanceof WebGLTexture is true
      │ PASS gl.getUniformLocation(program, "color") instanceof WebGLUniformLocation is true
      │ PASS gl.getActiveAttrib(program, 0) instanceof WebGLActiveInfo is true
      │ PASS gl.getActiveUniform(program, 0) instanceof WebGLActiveInfo is true
      │ 
      │ Tests that those WebGL objects can not be constructed through new operator
      │ 
      │ PASS new WebGLRenderingContext threw an error
      │ PASS new WebGLActiveInfo threw an error
      │ PASS new WebGLBuffer threw an error
      │ PASS new WebGLFramebuffer threw an error
      │ PASS new WebGLProgram threw an error
      │ PASS new WebGLRenderbuffer threw an error
      │ PASS new WebGLShader threw an error
      │ PASS new WebGLTexture threw an error
      │ PASS new WebGLUniformLocation threw an error
      │ PASS new WebGLShaderPrecisionFormat threw an error
      │ PASS successfullyParsed is true
      │ TEST COMPLETE
      │ thread 'PaintWorker' panicked at 'assertion failed: (data.len() as i32) >= stride * size.height', /Users/servo/.cargo/git/checkouts/rust-azure-97bcec2370a94878/master/src/azure_hl.rs:710
      │ stack backtrace:
      │    1:        0x1071482d8 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
      │    2:        0x10714e5b5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
      │    3:        0x10714e1ce - std::panicking::default_hook::h08ad3bb09872855b
      │    4:        0x106ab5c7f - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
      │    5:        0x107135eb8 - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
      │    6:        0x10636cce4 - std::sys_common::unwind::begin_unwind::h51df842978a11a26
      │    7:        0x106887a52 - azure::azure_hl::DrawTarget::create_source_surface_from_data::hff8d4d6dfe1b29ec
      │    8:        0x10654b285 - gfx::paint_context::PaintContext::draw_image::h7d445cf491e66337
      │    9:        0x10655d5c2 - gfx::display_list::DisplayItem::draw_into_context::h4ecad61f8b46d0f9
      │   10:        0x10655d424 - gfx::display_list::DisplayList::draw_item_at_index_into_context::h27cfe9bc00cb8d1e
      │   11:        0x1065749eb - gfx::paint_thread::WorkerThread::main::h768ba2c99b634f72
      │   12:        0x106572910 - std::sys_common::unwind::try::try_fn::h2abe2b2077979cc1
      └   13:        0x10714753b - __rust_try

**Comment by jdm** [comment]
Should be fixed by #10727.
