### ISSUE TITLE
Put each undefined symbol on its own line in check_dynamic_symbols.py

### ISSUE THREAD

**Issue by nox** [servo/servo#10797]
See the current output of the script in https://github.com/servo/servo/pull/10756#issuecomment-213076077.

Files:
 * `etc/ci/check_dynamic_symbols.py`

**Comment by askeing** [comment]
Does this for modifying the output of "Unexpected dynamic symbols in binary ..."?
If that's true, may I have a try? :)

**Comment by aneeshusa** [comment]
@askeing yes indeed. Go for it!
