### ISSUE TITLE
Implement alert dialogs and support mozbrowsershowmodalprompt API

### ISSUE THREAD

**Issue by jdm** [servo/servo#10812]
Now that we have support for the [tinyfiledialogs](https://github.com/jdm/tinyfiledialogs-rs) library, we can make use of it by invoking it from `Window::Alert`. There are a few parts to this:
* make the dialog box pop up
* send a synchronous message to the constellation instructing it to process an alert command
* if there is no parent for the pipeline requesting the alert, respond with a request for the originating script thread to show the dialog box
* otherwise, send a request to the root pipeline to trigger a mozbrowsershowmodalprompt event on the iframe that contains the pipeline that requested it
* when the root script thread responds that the event was dispatched, notify the original script thread that the action was completed
* do not display a dialog box

Code: `components/script/dom/window.rs`, `components/script/Cargo.toml`, `components/compositing/constellation.rs`, `components/script_traits/lib.rs`
Test: [write one](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) that demonstrates an iframe element receiving the appropriate event in `tests/wpt/mozilla/tests/mozilla/mozbrowser`

**Comment by ConnorGBrewster** [comment]
I would like to work on this one!

**Comment by jdm** [comment]
Go for it!
