### ISSUE TITLE
Allow setting withCredentials in synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by jdm** [servo/servo#10839]
The specification was recently changed to allow this for maximal web compatibility: https://github.com/whatwg/xhr/pull/67 . We need to update our implementation to account for this.

Specification: https://xhr.spec.whatwg.org/#the-open()-method
Code: `components/script/dom/xmlhttprequest.rs` (see `fn Open`)
Tests: `./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest/` (presumably some expected test results will need to be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations))

**Comment by jdm** [comment]
Depending on how quickly this is fixed, upstream may adjust the tests that we use first: https://github.com/w3c/web-platform-tests/issues/2894

**Comment by vramana** [comment]
@jdm Can I work on this?

**Comment by KiChjang** [comment]
Yes, definitely!
