### ISSUE TITLE
Make Servo not thrash the Dock on OSX when running tests

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#10836]
In headless mode, Servo's performance is currently gated by the Dock, as we thrash it in parallel at full speed. To avoid doing so, we should be able to call `[NSApp setActivationPolicy:NSApplicationActivationPolicyAccessory];` in our `applicationDidFinishLaunching:`

This would have a huge performance improvement on our dev boxes and build machines, plus should let us also scale up to a mac pro (they have no benefit right now, due to being gated on the dock).

**Comment by larsbergstrom** [comment]
fyi @pcwalton this should really help our test-{wpt,css} times on OSX

**Comment by frewsxcv** [comment]
For reference, [here's the relevant section in the AppKit docs.](https://developer.apple.com/library/mac/documentation/AppKit/Reference/NSRunningApplication_Class/#//apple_ref/c/tdef/NSApplicationActivationPolicy)

**Comment by frewsxcv** [comment]
Just made this change in servo-glutin:

```diff
diff --git a/src/api/cocoa/mod.rs b/src/api/cocoa/mod.rs
index 74811ca..9be8a0d 100644
--- a/src/api/cocoa/mod.rs
+++ b/src/api/cocoa/mod.rs
@@ -365,7 +365,7 @@ impl Window {
             if app == nil {
                 None
             } else {
-                app.setActivationPolicy_(NSApplicationActivationPolicyRegular);
+                app.setActivationPolicy_(NSApplicationActivationPolicyAccessory);
                 app.finishLaunching();
                 Some(app)
             }
```

[Here's the line upstream](https://github.com/tomaka/glutin/blob/e46781979499e47e04697fe96994dfe96b7f1e59/src/api/cocoa/mod.rs#L368)

It appears to work as expected. The next step would be to find a way to incorporate this into the glutin API. As usual, I'd rather try to merge this upstream before doing hackity hacks in servo-glutin. If anyone has ideas, please share!

**Comment by frewsxcv** [comment]
Summary of options:

### `NSApplicationActivationPolicyRegular`

```
Ran 4696 tests finished in 911.0 seconds.
```

* **Does** appear in Dock.app
* **Does** take window focus for every test

### `NSApplicationActivationPolicyAccessory`

```
Ran 4696 tests finished in 866.0 seconds.
```

* **Does not** appear in Dock.app
* **Does** take window focus for every test

### `NSApplicationActivationPolicyProhibited`

```
Ran 4696 tests finished in 860.0 seconds.
```

* **Does not** appear in Dock.app
* **Does not** take window focus for every test

----------

So I'd strongly vote for the last option. As an OS X user, having the tests take focus every half second is extremely frustrating and results in me not running the test suite as often as I should.

Also, r? https://github.com/servo/cocoa-rs/pull/121

**Comment by ConnorGBrewster** [comment]
@frewsxcv I agree with the last option, it is nearly impossible to do anything else on my computer while tests are running since the window focus is taken during every test.

**Comment by metajack** [comment]
@tomaka Do you have suggestions here for how we can do this with a minimum of impact on glutin?

**Comment by frewsxcv** [comment]
I asked @tomaka on IRC this morning briefly and they responded that we should modify [this struct](https://github.com/tomaka/glutin/blob/e46781979499e47e04697fe96994dfe96b7f1e59/src/api/cocoa/mod.rs#L183-L184) as it's passed to the [`Window::new`](https://github.com/tomaka/glutin/blob/e46781979499e47e04697fe96994dfe96b7f1e59/src/api/cocoa/mod.rs#L278-L280) constructor.

**Comment by tomaka** [comment]
Like @frewsxcv said.

Then in `os/macos` add a `WindowBuilderExt` trait (similar to [this](https://github.com/tomaka/glutin/blob/e46781979499e47e04697fe96994dfe96b7f1e59/src/os/unix.rs#L43-L49)) that allows modifying this setting.

**Comment by frewsxcv** [comment]
I can take care of this later today if no one gets to it before me.

**Comment by frewsxcv** [comment]
> Then in os/macos add a WindowBuilderExt trait (similar to this) that allows modifying this setting.

I don't really know what you mean by this. As in updating the activation policy value at runtime? If so, why is it going on the `WindowBuildExt` trait?

**Comment by frewsxcv** [comment]
Nevermind, I understand.

**Comment by frewsxcv** [comment]
Opened a PR: https://github.com/tomaka/glutin/pull/769/files?diff=unified
