### ISSUE TITLE
Unexpected getrandom error when running ./mach build --release

### ISSUE THREAD

**Issue by sydbarrett74** [servo/servo#10845]
I'm attempting to build the latest servo snapshot using the Bash on Ubuntu on Windows environment with Windows 10 x64 build 14328. When I run `BACKTRACE=1 ./mach build --dev`, I get the error shown in the attached PNG image. I had to do a screenshot because GitHub's text editor wants to interpret certain character sequences as emoji.

Please advise.
![servo build output](https://cloud.githubusercontent.com/assets/6467403/14804730/e788b36a-0b33-11e6-98d4-4d5930480b74.PNG)

**Comment by frewsxcv** [comment]
https://github.com/rust-lang/rust/issues/32788

**Comment by sydbarrett74** [comment]
I'm going to update Windows to 10.0.14332 and see if the problem persists.

**Comment by lygstate** [comment]
No problems now, it's can be treat as fixed.

**Comment by frewsxcv** [comment]
Closing this for now, but we can reopen if it's still an issue
