### ISSUE TITLE
Move abstract parser infrastructure out of servohtmlparser.rs

### ISSUE THREAD

**Issue by jdm** [servo/servo#10856]
This includes `ParserRoot`, `ParserField`, `MutNullableParserField`, `TrustedParser`, and `ParserRef`. Let's move them to `components/script/parse/mod.rs` instead.

Code: `components/script/dom/servohtmlparser.rs`, `components/script/parse/mod.rs`

**Comment by broesamle** [comment]
I would take it as my first rust experience...

Please correct me if I'm wrong but it does not look extremely urgent, to me.

**Comment by jdm** [comment]
@broesamle Please do! You are correct that this is not an urgent task; that being said, if you won't be able to work on it for a few days, we'd prefer to leave it available for somebody else.
