### ISSUE TITLE
Add file handling functionality to Blob object

### ISSUE THREAD

**Issue by izgzhen** [servo/servo#10851]
**NOTE**: This is an issue assigned to myself

Spec: https://w3c.github.io/FileAPI/#blob

As noted before, current Blob object can only refer to in-memory data ([`DataSlice`](https://doc.servo.org/script/dom/blob/struct.DataSlice.html)), and the [`FileReader`](https://doc.servo.org/script/dom/filereader/struct.FileReader.html) will also only operate in this way. In order to support reading from file system, another internal data structure might need to be added to the `Blob`. It might be a file handler created at the time of object construction.

About snapshot state:

> If a File object is a reference to a byte sequence originating from a file on disk, then its snapshot state should be set to the state of the file on disk at the time the File object is created.
> 
> Note: This is a non-trivial requirement to implement for user agents, and is thus not a must but a should [RFC2119]. User agents should endeavor to have a File object’s snapshot state set to the state of the underlying storage on disk at the time the reference is taken. If the file is modified on disk following the time a reference has been taken, the File's snapshot state will differ from the state of the underlying storage. User agents may use modification time stamps and other mechanisms to maintain snapshot state, but this is left as an implementation detail.

Working at [branching here](https://github.com/izgzhen/servo/tree/blob)

**Comment by Manishearth** [comment]
As mentioned in email, we need to be careful about process isolation here. The script task should never be reading files directly, nor should it be possible for the script task to ask another process to read an arbitrary file for it. Instead, the script task should ask the resource task to spawn a file dialog, and the resource task should return some handle through which the script task can refer to the file.

**Comment by izgzhen** [comment]
@Manishearth Thanks for guidance, I will see what I can do here

**Comment by izgzhen** [comment]
@Manishearth Can we reopen this? ...
