### ISSUE TITLE
Windows build -r Error

### ISSUE THREAD

**Issue by Byramklc** [servo/servo#10875]
```
$ ./mach build -r
    Updating git repository `https://github.com/servo/mozjs`
   Compiling js v0.1.2 (https://github.com/servo/rust-mozjs#efe805af)
   Compiling style v0.0.1 (file:///C:/msys64/home/PC/servo/components/style)
   Compiling caseless v0.1.1
   Compiling openssl-sys-extras v0.7.8
   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#3122a1e1)
   Compiling webrender v0.1.0 (https://github.com/servo/webrender#8d778dac)
   Compiling azure v0.4.3 (https://github.com/servo/rust-azure#bb2fab86)
   Compiling openssl v0.7.8
   Compiling layers v0.2.4 (https://github.com/servo/rust-layers#3cb5df49)
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#3122a1e1)`
Process didn't exit successfully: `C:/msys64/home/PC/servo/target\release\build\mozjs_sys-736cac28b49f9dab\build-script-build` (exit code: 101)
--- stdout
cd /home/PC/servo/target/release/build/mozjs_sys-736cac28b49f9dab/out && \
PYTHON="""" \
MOZ_TOOLS="/" CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure --disable-jemalloc --disable-shared-js --disable-export-js
loading cache ./config.cache
checking host system type... x86_64-pc-mingw64
checking target system type... x86_64-pc-mingw64
checking build system type... x86_64-pc-mingw64
checking for mawk... no
checking for gawk... gawk
checking for perl5... no
checking for perl... /usr/bin/perl
checking for gcc... gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether gcc accepts -g... yes
checking for c++... g++
checking whether the C++ compiler (g++  ) works... yes
checking whether the C++ compiler (g++  ) is a cross-compiler... no
checking whether we are using GNU C++... yes
checking whether g++ accepts -g... yes
checking for ranlib... ranlib
checking for ml64... no
checking for as... /mingw64/bin/as
checking for ar... ar
checking for ld... link
checking for strip... strip
checking for windres... windres
checking for w32api version >= 3.14... yes
checking for windres version >= 2.14.90... (GNU
checking for Windows SDK being recent enough... yes
checking how to run the C preprocessor... gcc -E
checking how to run the C++ preprocessor... g++ -TP -E -nologo
checking for sb-conf... no
checking for ve... no
checking for a BSD compatible install... /usr/bin/install -c
checking whether ln -s works... no
checking for tar archiver... checking for gnutar... no
checking for gtar... no
checking for tar... tar
tar
checking for minimum required perl version >= 5.006... 5.022001
checking for full perl installation... yes
checking for python2.7... /home/PC/servo/python/_virtualenv/bin/python2.7
Creating Python environment
Using real prefix '/usr'
New python executable in C:/msys64/home/PC/servo/target/release/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv/bin/python2.7
Not overwriting existing python script C:/msys64/home/PC/servo/target/release/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv/bin/python (you must use C:/msys64/home/PC/servo/target/release/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv/bin/python2.7)
ERROR: The executable C:/msys64/home/PC/servo/target/release/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/home/PC/servo/target/release/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv' (should be u'C:/msys64/home/PC/servo/target/release/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv')
ERROR: virtualenv is not compatible with this system or executable
------ config.log ------
configure:2998: checking whether g++ accepts -g
configure:3032: checking for ranlib
configure:3064: checking for ml64
configure:3064: checking for as
configure:3118: checking for ar
configure:3153: checking for ld
configure:3188: checking for strip
configure:3223: checking for windres
configure:3734: checking for w32api version >= 3.14
configure:3748: gcc -c   conftest.c 1>&5
configure:3764: checking for windres version >= 2.14.90
configure:3812: checking for Windows SDK being recent enough
configure:3839: checking how to run the C preprocessor
configure:3919: checking how to run the C++ preprocessor
configure:4059: checking for sb-conf
configure:4059: checking for ve
configure:4121: checking for a BSD compatible install
configure:4174: checking whether ln -s works
configure:4196: checking for tar archiver
configure:4202: checking for gnutar
configure:4202: checking for gtar
configure:4202: checking for tar
configure:4239: checking for minimum required perl version >= 5.006
configure:4249: checking for full perl installation
configure:4267: checking for python2.7
makefile.cargo:77: recipe for target 'all' failed

--- stderr
makefile.cargo:60: extraneous text after 'else' directive
/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: line 3772: test: (GNU: integer expression expected
Traceback (most recent call last):
  File "/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 475, in <module>
    manager.ensure()
  File "/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 128, in ensure
    return self.build()
  File "/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 371, in build
    self.create()
  File "/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 147, in create
    raise Exception('Error creating virtualenv.')
Exception: Error creating virtualenv.
make: *** [all] Error 1
thread '<main>' panicked at 'assertion failed: result.success()', C:/msys64/home/PC/servo/.cargo\git\checkouts\mozjs-06d7f04b6dbb8a8e\master\build.rs:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by nox** [comment]
Did you follow the build instructions from the README file?

**Comment by Byramklc** [comment]
Yes

`$ ./mach build --dev
   Compiling bitflags v0.4.0
   Compiling getopts v0.2.14
   Compiling heapsize v0.3.5
   Compiling ref_slice v0.1.0
   Compiling language-tags v0.2.0
   Compiling glob v0.2.10
   Compiling gcc v0.3.26
   Compiling libc v0.2.4
   Compiling color_quant v1.0.0
   Compiling backtrace v0.2.1
   Compiling browserhtml v0.1.4 (https://github.com/browserhtml/browserhtml?branch=gh-pages#0ca50842)
   Compiling bitflags v0.3.3
   Compiling brotli v0.3.20 (https://github.com/ende76/brotli-rs#c243045b)
   Compiling openssl v0.7.8
   Compiling miniz-sys v0.1.7
   Compiling gdi32-sys v0.1.1
   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#3122a1e1)
   Compiling backtrace-sys v0.1.3
   Compiling make-cmd v0.1.0
   Compiling inflate v0.1.0
   Compiling odds v0.2.12
   Compiling byteorder v0.5.1
   Compiling nodrop v0.1.6
   Compiling encoding_index_tests v0.1.4
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling lazy_static v0.1.16
   Compiling cfg-if v0.1.0
   Compiling matches v0.1.2
   Compiling utf-8 v0.6.0
   Compiling unicode-bidi v0.2.3
   Compiling tenacious v0.2.0
   Compiling ref_filter_map v1.0.1
   Compiling khronos_api v1.0.0
   Compiling mac v0.0.2
   Compiling arrayvec v0.3.16
   Compiling encoding v0.2.32
   Compiling servo-skia v0.20130412.6
   Compiling fnv v1.0.0
   Compiling azure v0.4.3 (https://github.com/servo/rust-azure#bb2fab86)
   Compiling winapi-build v0.1.1
   Compiling heapsize_plugin v0.1.4
   Compiling angle v0.1.0 (https://github.com/emilio/angle?branch=servo#eefe3506)
   Compiling typeable v0.1.2
   Compiling httparse v1.1.0
   Compiling void v0.0.5
   Compiling simd v0.1.0 (https://github.com/huonw/simd#03de1cd0)
   Compiling num-traits v0.1.32
   Compiling script v0.0.1 (file:///C:/msys64/home/PC/servo/components/script)
   Compiling threadpool v1.0.0
   Compiling unreachable v0.0.2
   Compiling ws2_32-sys v0.2.0
   Compiling smallvec v0.1.5
   Compiling serde_codegen v0.7.2
   Compiling memchr v0.1.10
   Compiling js v0.1.2 (https://github.com/servo/rust-mozjs#efe805af)
   Compiling dwmapi-sys v0.1.0
   Compiling aho-corasick v0.5.1
   Compiling phf_shared v0.7.13
   Compiling num-integer v0.1.32
   Compiling lzw v0.10.0
   Compiling phf v0.7.13
   Compiling cmake v0.1.14
   Compiling num-iter v0.1.32
   Compiling regex-syntax v0.2.5
   Compiling winapi v0.2.6
   Compiling rustc-serialize v0.3.19
   Compiling shared_library v0.1.2
   Compiling pkg-config v0.3.5
   Compiling openssl-sys v0.7.8
   Compiling libz-sys v1.0.0
   Compiling expat-sys v2.1.2
   Compiling harfbuzz-sys v0.1.2
   Compiling num-complex v0.1.32
   Compiling servo-freetype-sys v2.4.11
   Compiling hbs-builder v0.2.0
   Compiling servo-fontconfig-sys v2.11.3
   Compiling debug_unreachable v0.0.6
   Compiling futf v0.1.1
   Compiling gif v0.8.0
   Compiling tendril v0.2.1
   Compiling serde v0.7.0
   Compiling quasi v0.9.0
   Compiling user32-sys v0.1.2
   Compiling servo v0.0.1 (file:///C:/msys64/home/PC/servo/components/servo)
   Compiling rand v0.3.14
   Compiling deque v0.3.1
   Compiling num-bigint v0.1.32
   Compiling num-rational v0.1.32
   Compiling uuid v0.2.0
   Compiling phf_generator v0.7.13
   Compiling string_cache v0.2.12
   Compiling phf_macros v0.7.13
   Compiling phf_codegen v0.7.13
   Compiling xml5ever v0.1.1 (https://github.com/Ygg01/xml5ever#a51a6df1)
   Compiling html5ever v0.5.1
   Compiling mime_guess v1.6.0
   Compiling num v0.1.32
   Compiling immeta v0.3.2
   Compiling enum_primitive v0.1.0
   Compiling serde_json v0.7.0
   Compiling hbs-pow-sys v0.2.0
   Compiling traitobject v0.0.1
   Compiling hbs-common-sys v0.2.0
   Compiling unicode-normalization v0.1.2
   Compiling log v0.3.5
   Compiling mime v0.2.0
   Compiling idna v0.1.0
   Compiling servo-fontconfig v0.2.0
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#3122a1e1)`
Process didn't exit successfully: `C:/msys64/home/PC/servo/target\debug\build\mozjs_sys-736cac28b49f9dab\build-script-build` (exit code: 101)
--- stdout
cd /home/PC/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/out && \
PYTHON="""" \
MOZ_TOOLS="/" CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure --disable-jemalloc --disable-shared-js --disable-export-js
creating cache ./config.cache
checking host system type... x86_64-pc-mingw64
checking target system type... x86_64-pc-mingw64
checking build system type... x86_64-pc-mingw64
checking for mawk... no
checking for gawk... gawk
checking for perl5... no
checking for perl... /usr/bin/perl
checking for gcc... gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether gcc accepts -g... yes
checking for c++... g++
checking whether the C++ compiler (g++  ) works... yes
checking whether the C++ compiler (g++  ) is a cross-compiler... no
checking whether we are using GNU C++... yes
checking whether g++ accepts -g... yes
checking for ranlib... ranlib
checking for ml64... no
checking for as... /mingw64/bin/as
checking for ar... ar
checking for ld... link
checking for strip... strip
checking for windres... windres
checking for w32api version >= 3.14... yes
checking for windres version >= 2.14.90... (GNU
checking for Windows SDK being recent enough... yes
checking how to run the C preprocessor... gcc -E
checking how to run the C++ preprocessor... g++ -TP -E -nologo
checking for sb-conf... no
checking for ve... no
checking for a BSD compatible install... /usr/bin/install -c
checking whether ln -s works... no
checking for tar archiver... checking for gnutar... no
checking for gtar... no
checking for tar... tar
tar
checking for minimum required perl version >= 5.006... 5.022001
checking for full perl installation... yes
checking for python2.7... /home/PC/servo/python/_virtualenv/bin/python2.7
Creating Python environment
Using real prefix '/usr'
New python executable in C:/msys64/home/PC/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv/bin/python2.7
Also creating executable in C:/msys64/home/PC/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv/bin/python
ERROR: The executable C:/msys64/home/PC/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/home/PC/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv' (should be u'C:/msys64/home/PC/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/out/_virtualenv')
ERROR: virtualenv is not compatible with this system or executable
------ config.log ------
configure:2998: checking whether g++ accepts -g
configure:3032: checking for ranlib
configure:3064: checking for ml64
configure:3064: checking for as
configure:3118: checking for ar
configure:3153: checking for ld
configure:3188: checking for strip
configure:3223: checking for windres
configure:3734: checking for w32api version >= 3.14
configure:3748: gcc -c   conftest.c 1>&5
configure:3764: checking for windres version >= 2.14.90
configure:3812: checking for Windows SDK being recent enough
configure:3839: checking how to run the C preprocessor
configure:3919: checking how to run the C++ preprocessor
configure:4059: checking for sb-conf
configure:4059: checking for ve
configure:4121: checking for a BSD compatible install
configure:4174: checking whether ln -s works
configure:4196: checking for tar archiver
configure:4202: checking for gnutar
configure:4202: checking for gtar
configure:4202: checking for tar
configure:4239: checking for minimum required perl version >= 5.006
configure:4249: checking for full perl installation
configure:4267: checking for python2.7
makefile.cargo:77: recipe for target 'all' failed

--- stderr
makefile.cargo:60: extraneous text after 'else' directive
/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: line 3772: test: (GNU: integer expression expected
Traceback (most recent call last):
  File "/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 475, in <module>
    manager.ensure()
  File "/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 128, in ensure
    return self.build()
  File "/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 371, in build
    self.create()
  File "/home/PC/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 147, in create
    raise Exception('Error creating virtualenv.')
Exception: Error creating virtualenv.
make: *** [all] Error 1
thread '<main>' panicked at 'assertion failed: result.success()', C:/msys64/home/PC/servo/.cargo\git\checkouts\mozjs-06d7f04b6dbb8a8e\master\build.rs:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`

**Comment by Byramklc** [comment]
Python re install and problem fixed
