### ISSUE TITLE
HTMLAnchorElement getters don't work until the href setter is called

### ISSUE THREAD

**Issue by jdm** [servo/servo#10876]
HTMLAnchorElement::reinitialize_url returns early if `self.url` is null, but that means that it doesn't call `set_url`, which means that it stays null.

**Comment by jdm** [comment]
```html
<a href="http://google.com?hi>anchor</a>
<script>
var a = document.querySelector('a');
console.log(a.search);
a.href = "http://google.com?hi";
console.log(a.search);
</script>

**Comment by jdm** [comment]
I believe the right thing to do here is add an `attribute_mutated` override that looked for `href` modifications and calls `self.set_url`. See `htmliframeelement.rs` for a good model.

Code: `components/script/dom/htmlanchorelement.rs`
Test: We should [create a test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) that exercises each of the [getters and setters](https://github.com/servo/servo/blob/7ae63b121334b77b0592fd10570926c8b8cfd11c/components/script/dom/webidls/HTMLHyperlinkElementUtils.webidl) individually in `tests/wpt/web-platform-tests/html/semantics/links/links-created-by-a-and-area-elements/`.

**Comment by axitkhurana** [comment]
@jdm would like to work on this one :)

**Comment by jdm** [comment]
@axitkhurana Great! Please ask questions if anything's unclear :)

**Comment by axitkhurana** [comment]
Seems like @broesamle had some time to work on it while I had an unexpectedly busy Thurday/Friday, I'll pick another one @jdm

**Comment by KiChjang** [comment]
Oh! Sorry @axitkhurana, this is not supposed to happen.

@broesamle, I would ask of you to leave a comment on the issue next time when you work on it. You have stolen work away from another person who had been assigned an issue.

**Comment by broesamle** [comment]
Hi @axitkhurana 
apologies for that! It was certainly not my intention to get in the way of your work! While working on it, I was not aware, that it would affect our work directly. 

In fact, I am only testing the getters and setters individually, not accounting for an unset `href`.

#10877 mentions that the test files would eventually end up in the same location:
> Test: We should write one. Since it will overlap with the tests proposed in #10876, I'm fine with this living in tests/wpt/mozilla/tests/mozilla and being removed when #10876 is fixed, if this issue is fixed first.

>  I would ask of you to leave a comment on the issue 

I could have written some more than relying on the automatic comment github puts:  
> broesamle referenced this issue 2 days ago
Open
Fixes #10877 #10903

**Comment by jdm** [comment]
Yeah, these issues are independent, so I don't think that anything was done wrong here.

**Comment by axitkhurana** [comment]
Apologies in that case @jdm, should have read the the changes in PR first, thanks for clarifying @broesamle !

**Comment by axitkhurana** [comment]
@jdm : Sorry, I've been busy with work and won't be able to work on this until this weekend, feel free to un-assign if you feel I'm blocking

**Comment by mrmiywj** [comment]
@jdm 
I'll try to pick this up.

**Comment by jdm** [comment]
OK!

**Comment by mrmiywj** [comment]
@jdm 
Hi, I just complete the work. But I'm not sure what the test in `ests/wpt/web-platform-tests/html/semantics/links/links-created-by-a-and-area-elements/` means, which is created by @broesamle .
And I code failed on this test. Maybe I need to fix it, I don't know why. Maybe I should call getter before the setting called?

**Comment by jdm** [comment]
Just so you know, you can run the test files under tests/wpt/web-platform-tests with `./mach test-wpt tests/wpt/web-platform-tests/path/to/test.html`. If you're adding a new test, like you did in your PR, you should use `./mach create-wpt tests/wpt/web-platform-tests/path/to/test.html` as described in [the documentation](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests).

**Comment by mrmiywj** [comment]
Hmm, yep I know this. The test in my PR is jut  a test. What's the point is
that my code fails when the test tries to modify the node's attribute like
`hash`, `search`, etc. I can not find what causes it. Is there any problems
with my code?

2016-05-15 3:01 GMT+08:00 Josh Matthews <notifications@github.com>:

> Just so you know, you can run the test files under
> tests/wpt/web-platform-tests with ./mach test-wpt
> tests/wpt/web-platform-tests/path/to/test.html. If you're adding a new
> test, like you did in your PR, you should use ./mach create-wpt
> tests/wpt/web-platform-tests/path/to/test.html as described in the
> documentation
> <https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests>
> .
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/servo/servo/issues/10876#issuecomment-219237344>
>



-- 
杨文杰
Wenjie Yang

Department of Computer Science
School of Electronic Information and Electrical Engineering
Shanghai Jiao Tong University
Tel:+86-18317007232
E-mail:jsyangwenjie@gmail.com

**Comment by jdm** [comment]
Can you describe how your code fails, exactly? What do you expect to happen, and what actually happens?

**Comment by mrmiywj** [comment]
Yep,
After reading through the code, I think the problem is that if no setter has ever called, the `self.url` will be None, so that I plan to call `self.set_url()` in `attribute_mutated` if I found that `self.url` is None. But it cannot be borrowed at this function, since there must be a muted borrowing somewhere else.
And I doubt whether it works. Since `attribute_mutated` is called when an attribute is changed or removed. It still can happen after a getter.
Thanks!
