### ISSUE TITLE
Time-profiling output to a CSV file upon exit for automated Servo testing

### ISSUE THREAD

**Issue by rzambre** [servo/servo#10886]
This will allow the user to use the existing -p option to direct the time-profiling output to a CSV file upon termination of Servo. So the -p option can take two types of arguments: either a number of a file name. If it is a number, then the number will be used as the interval for printing out profiling output to the terminal (as it is currently implemented). If it is a file name, the time-profiling data will be printed out to the file upon Servo's termination.

This new addition to the -p option will be essential for running automated Servo tests and runs. The best way to make use of this function is by calling Servo with these options:

./mach run -r -x -o out.png -p out.csv <url>

**Comment by rzambre** [comment]
@larsbergstrom I have a working implementation of both the features here: https://github.com/rzambre/servo/tree/intCSVprofiling. The formatting of the interval profiling is the same as it is now.

However, when I use the -p option alone without specifying a number or a file name, I'm still getting the bad-certificate error.

**Comment by aneeshusa** [comment]
Can I request that this output TSV (tab-separated values) instead of CSV? I encounter less problems with TSV since tabs aren't so common as compared to commas.
