### ISSUE TITLE
Treat 404 responses when downloading rustc differently from network errors

### ISSUE THREAD

**Issue by jdm** [servo/servo#10882]
```
16:03 <fridsun> $ ./mach build --release
16:03 <fridsun> looking for rustc at /c/Users/yang/Documents/workspace-rust/servo/.servo/rust/2016-04-24/rustc-nightly-x86_64-unknown/rustc/bin/rustc
16:03 <fridsun> Downloading Rust compiler...
16:03 <fridsun> Error downloading Rust compiler; are you connected to the internet?
```

**Comment by jdm** [comment]
A 404 response indicates that the platform isn't recognized or unsupported, so we should display a better error message in that case.

**Comment by askeing** [comment]
I'd like to do it, thx :)

**Comment by jdm** [comment]
@askeing Please do :)

**Comment by askeing** [comment]
@jdm, I found we already handle the HTTPError.
https://github.com/servo/servo/blob/master/python/servo/bootstrap_commands.py#L66-L71

It seems like we only have to catch HTTPError before URLError, and then print more information when get e.code is 404 (ex: host_triple).
Is that right?

**Comment by jdm** [comment]
Interesting. Maybe I misdiagnosed the failure that was reported in the original description.

**Comment by jdm** [comment]
I would be surprised if the order of exceptions mattered, but maybe I don't know python and/or urllib2 well enough?

**Comment by askeing** [comment]
The `URLError` seems like catch all problems without HTTP status code. So we should check `HTTPError` for HTTP specific errors, and then check `URLError` for others. 
ref: https://docs.python.org/2/library/urllib2.html#urllib2.URLError

After re-order the exceptions, downloading `not-support host triple` will get `403` status from server:
```
Download failed (403): Forbidden - https://static-rust-lang-org.s3.amazonaws.com/dist/2016-04-24/rustc-nightly-x86_64-unknown.tar.gz
```
Maybe we just have to re-order exceptions and add the link of [support platforms](https://doc.rust-lang.org/book/getting-started.html#platform-support) ?

Do you have any suggestions?
