### ISSUE TITLE
mach update-css has confusing semantics

### ISSUE THREAD

**Issue by perlun** [servo/servo#10884]
I ran the following, after changing some code that caused tests that previously passed to fail:

```
$ ./mach update-css /tmp/foo
```

Then I tried with `git diff`. It didn't show me anything; I assumed the command hadn't worked. It was only when @jdm told me to `git show` that I realized it had behind-the-scenes creates a new commit with the `.ini` file changes in.

This is a confusing behavior and IMHO a bad default. _If_ we really want it to automagically commit code (which I think is questionable to begin with), it should at least not just keep silent about it. The `git commit` output should be shown if we retain the current behavior. (but I'd vote for just leaving the files dirty since that'd be how I'd guess it would work by just looking at it from the outside.)

Looked a bit but I couldn't immediately find where in this code this happens.

**Comment by KiChjang** [comment]
I recall seeing a similar issue before... @Wafflespeanut might know more.

**Comment by Wafflespeanut** [comment]
Yeah, that was `update-wpt`. We should do something similar to what we did for #9666 (i.e., pass `--no-patch` argument by default)

Code: `python/servo/testing_commands.py`
