### ISSUE TITLE
Display a helpful message when invoking test-wpt with a tests/wpt/css-tests/ path

### ISSUE THREAD

**Issue by jdm** [servo/servo#10883]
This is incorrect and an easy and confusing mistake to make.

**Comment by jdm** [comment]
Maybe we could even just invoke the correct command silently.

**Comment by jdm** [comment]
We should consider if there are useful things we could do with update-wpt vs update-css as well.

**Comment by perlun** [comment]
I think we have similar issues in other areas as well:

```
$ ./mach test-css tests/wpt/mozilla/tests/css/button_css_width.html
Running tests in web-platform-tests

Unsupported test type wdspec for product servo
Ran 0 tests finished in 0.0 seconds.
  • 0 ran as expected. 0 tests skipped.
```

Do you want me to file a separate issue about that?

**Comment by jdm** [comment]
That could be covered by this as well.

**Comment by talklittle** [comment]
I'll attempt a PR for this. I'm thinking to silently invoke the correct command by looking for the presence of paths in the command args, and if any paths are specified, re-dispatch the command through `mach test`, which is already smart enough to delegate to the correct test suite.

**Comment by jdm** [comment]
That seems sensible, but let's print a warning as well to help people learn from their mistakes.
