### ISSUE TITLE
Figure out how to unit test the trace-dump.js code

### ISSUE THREAD

**Issue by fitzgen** [servo/servo#10905]
Is there an existing test suite for random JS we could use? Some thing like xpcshell in m-c?

Would it be easier to vendor the trace-dump.js code, where it would live in its own third party repo and have its own unit tests there? Then we would periodically update servo's copy from upstream but not run the upstream's tests as part of servo's suite.

**Comment by jdm** [comment]
We do not have a JS shell yet, there's we haven't had any random JS that needed testing before now.

**Comment by fitzgen** [comment]
> We do not have a JS shell yet, and we haven't had any random JS that needed testing before now.

So do you think the vendoring approach would be easier/better, then?

**Comment by jdm** [comment]
Well, we could plausibly do unit tests via a WPT test that loads the script using a chrome:// URL if trace-dump.js lived in resources/. Vendoring may be less work; it's not really clear to me how often people will want to modify the file.

**Comment by fitzgen** [comment]
@jdm:

I made a separate repo with unit tests in mocha+chai that can be run with node, as well as travis ci integration here: https://github.com/fitzgen/servo-trace-dump

Right now, that repo has a little shell script to copy the trace-dump.js and trace-dump.css files over to their path in your servo checkout, but we could also make that repo a submodule. Thoughts on copying files over vs proper submodule?

Also, should this repo live under the servo organization?

**Comment by fitzgen** [comment]
Once we figure ^ out, I will make a PR with the latest changes for `trace-dump.js`.

**Comment by jdm** [comment]
I think we try to avoid submodules as much as possible. Copying should be fine.
