### ISSUE TITLE
Make etc/ci/manifest_changed.sh work on release builders

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#10909]
The `etc/ci/manifest_changed.sh` script does not work properly on release builders because it looks for the development version of servo.

Here is an example error (from http://build.servo.org/builders/linux-rel/builds/672/steps/shell_2/logs/stdio):
```
Binary path /home/servo/buildbot/slave/linux-rel/build/target/debug/servo does not exist
```

There are actually two fixes needed:

- Add
```
set -o errexit
set -o nounset
set -o pipefail
```
to our CI bash scripts so they fail if any command fails.
- Fix the script so that it doesn't look for a binary (I think the `--binary` option should do this).

**Comment by jdm** [comment]
Note that the script doesn't directly reference a binary - it invokes a mach command that defaults to debug but can accept a `--release` argument as well.

**Comment by askeing** [comment]
after `set -o errexit`, we should handle the first `test-wpt` error, and then try `test-wpt --release`.
may I have a try?

**Comment by aneeshusa** [comment]
@askeing Go for it!

From my understanding, we shouldn't need any binary at all to update the manifests. Ideally, the SKIP_TESTS argument should automatically turn off looking for a binary, but I have no idea where that argument is processed. I'd prefer a solution that doesn't depend on the binary if possible.

Possible files to investigate command line args for this:
- `python/servo/testing_commands.py` (`create_parser_wpt()`)
- `tests/wpt/harness/wptrunner/wptcommandline.py` (`create_parser()`)

**Comment by askeing** [comment]
@aneeshusa 
The `SKIP_TESTS` doesn't really skip the tests, 
it will still run the `run_wpt.py` with `'test_list': ['SKIP_TESTS']`.
And then `run.py` will call `wptcommandline.check_args(kwargs)` when setting defaults.
https://github.com/servo/servo/blob/master/tests/wpt/harness/wptrunner/wptcommandline.py#L314-L317
