### ISSUE TITLE
Handle XML parsing error properly

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#10925]
According to https://w3c.github.io/DOM-Parsing/#methods when a parsing error occurs while parsing XML, we need to:
 * create a new document
 * append a new element with local name `parsererror` and namespace `http://www.mozilla.org/newlayout/xml/parsererror.xml` to the document
 * stop parsing and return the document

The test `tests/wpt/web-platform-tests/domparsing/DOMParser-parseFromString-xml.html` checks for this; however, it expects `<foo>` to result in a parsing error. Due to the new xml5 standard `<foo>` will not cause a parsing error.

Code: `components/script/parse/xml.rs`

**Comment by ConnorGBrewster** [comment]
I am working on this

**Comment by Ms2ger** [comment]
I'm not at all convinced we should do this.

**Comment by ConnorGBrewster** [comment]
@Ms2ger any reason in specific?

**Comment by Ms2ger** [comment]
The test assumes a draconian xml parser, which we don't have, so there's not much point in trying to pass it.

**Comment by ConnorGBrewster** [comment]
@Ms2ger ok makes sense, I will close this then.
