### ISSUE TITLE
Rename check_no_unwrap.sh to check_no_panic.sh

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#10930]
The `etc/ci/check_no_unwrap.sh` script checks that we don't call `unwrap()`, but after #10902 will also check for `panic!()`. It should be renamed to `etc/ci/check_no_panic.sh` to reflect the expanded scope.

We'll also need to update the `etc/ci/buildbot_steps.yml` file.

Blocked on servo/saltfs#316, #10902.

**Comment by zeusintuivo** [comment]
Is this solved or repeated, ...confusing.

**Comment by jdm** [comment]
It's not solved yet, since the PR to address it is blocked on changes being made in another repository.

**Comment by zeusintuivo** [comment]
I have made a feature fix for it here just in case 
https://github.com/zeusintuivo/servo/tree/feature/10930
