### ISSUE TITLE
Serialize Shorthands Correctly

### ISSUE THREAD

**Issue by craftytrickster** [servo/servo#10933]
Shorthand properties (such as margin) need special serialization treatment when being converted to strings. For example, 

```css
margin-top: 10px; margin-right: 10px; margin-bottom: 10px; margin-left: 10px;
```

gets displayed as 

```css
margin: 10px;
```
This cannot be implemented until after https://github.com/servo/servo/pull/9410 is completed, since it is dependent on the changes made there.

**Comment by DDEFISHER** [comment]
Could I do this?

**Comment by jdm** [comment]
Still waiting on #9410.

**Comment by craftytrickster** [comment]
This one is now unblocked.
@DDEFISHER are you still planning to work on this?

**Comment by DDEFISHER** [comment]
@craftytrickster if you don't mind I would like to

**Comment by craftytrickster** [comment]
Sure, just letting you know you're unlocked now.

**Comment by craftytrickster** [comment]
@DDEFISHER If you haven't made substantial progress on this one yet, I would like to pick it up if you do not mind.

**Comment by DDEFISHER** [comment]
@craftytrickster Sorry for not getting back to you quicker. I would not mind you picking it up.

**Comment by craftytrickster** [comment]
Hi @DDEFISHER , no need to apologize. Since I did not hear from you and since it has been quite some time since I opened the issue, I went ahead and did a lot of work on this one over the past few days, I am nearly finished already putting together the PR. I hope you do not mind.

**Comment by DDEFISHER** [comment]
no problem

**Comment by emilio** [comment]
@craftytrickster thanks for keeping up with this!

**Comment by craftytrickster** [comment]
@emilio , likewise, thanks for the help on this
