### ISSUE TITLE
panicking when loading agar.io

### ISSUE THREAD

**Issue by lhirlimann** [servo/servo#10952]
[ludo@Oulanl servo]$ ./mach run --release http://www.agar.io
ERROR:js::rust: Error at http://agar.io/js/a.js?a&ad_box_:0:0: document.write is not a function

ERROR:js::rust: Error at http://staticxx.facebook.com/connect/xd_arbiter.php?version=42#cb=f381742319487ba&domain=agar.io&origin=http%3A%2F%2Fagar.io%2Ff7bb7fb0cb1716&relation=parent&error=unknown_user:47:1880: window.name is undefined

ERROR:js::rust: Error at http://agar.io/js/master.js:2:23299: o is undefined

ERROR:js::rust: Error at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.fr.0JX4waWGXC4.O/m=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCOmGNu6CSHv8uZNgXAzhVDn7pAJ9Q/cb=gapi.loaded_0:10:32: c is undefined

thread 'ImageCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
  10:     0x561b5dbb8392 - <unknown>
  11:     0x561b5dbe26aa - <unknown>
  12:     0x561b5f07f86b - <unknown>
  13:     0x561b5f07f7fd - <unknown>
  14:     0x561b5dbe2afdthread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
thread 'PaintWorker' panicked at 'assertion failed: thread::panicking() || result == 0', /home/ludo/servo/.cargo/git/checkouts/ipc-channel-3840821e54ea11a6/master/platform/linux/mod.rs:95
thread 'PaintWorker' panicked at 'assertion failed: thread::panicking() || result == 0', /home/ludo/servo/.cargo/git/checkouts/ipc-channel-3840821e54ea11a6/master/platform/linux/mod.rs:95
thread 'PaintWorker' panicked at 'assertion failed: thread::panicking() || result == 0', /home/ludo/servo/.cargo/git/checkouts/ipc-channel-3840821e54ea11a6/master/platform/linux/mod.rs:95
 - <unknown>
  15:     0x561b5f086194 - <unknown>
  16:     0x7fd14b9f2589 - <unknown>
  17:     0x7fd14b5115cc - <unknown>
  18:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
  10:     0x561b5e5d3827 - <unknown>
  11:     0x561b5e5d435b - <unknown>
  12:     0x561b5d6e617d - <unknown>
  13:     0x561b5d6edcfe - <unknown>
  14:     0x561b5d6c04c4 - <unknown>
  15:     0x561b5d6f7ffc - <unknown>
  16:     0x561b5d6a8065 - <unknown>
  17:     0x561b5f0873b4 - <unknown>
  18:     0x561b5f07f86b - <unknown>
  19:     0x561b5f086dfb - <unknown>
  20:     0x7fd14b426720 - <unknown>
  21:     0x561b5d6a6268 - <unknown>
  22:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
  10:     0x561b5e5d3827 - <unknown>
  11:     0x561b5e5d435b - <unknown>
  12:     0x561b5e3593bf - <unknown>
  13:     0x561b5e357127 - <unknown>
  14:     0x561b5f07f86b - <unknown>
  15:     0x561b5f07f7fd - <unknown>
  16:     0x561b5e357841 - <unknown>
  17:     0x561b5f086194 - <unknown>
  18:     0x7fd14b9f2589 - <unknown>
  19:     0x7fd14b5115cc - <unknown>
  20:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
  10:     0x561b5e5d3827 - <unknown>
  11:     0x561b5e5d435b - <unknown>
  12:     0x561b5e3593bf - <unknown>
  13:     0x561b5e357127 - <unknown>
  14:     0x561b5f07f86b - <unknown>
  15:     0x561b5f07f7fd - <unknown>
  16:     0x561b5e357841 - <unknown>
  17:     0x561b5f086194 - <unknown>
  18:     0x7fd14b9f2589 - <unknown>
  19:     0x7fd14b5115cc - <unknown>
  20:                0x0 - <unknown>
stack backtrace:
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5d91de6f - <unknown>
   7:     0x561b5ed0f650 - <unknown>
   8:     0x561b5e35710d - <unknown>
   9:     0x561b5f07f86b - <unknown>
  10:     0x561b5f07f7fd - <unknown>
  11:     0x561b5e357841 - <unknown>
  12:     0x561b5f086194 - <unknown>
  13:     0x7fd14b9f2589 - <unknown>
  14:     0x7fd14b5115cc - <unknown>
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5d91de6f - <unknown>
   7:     0x561b5ed0f650 - <unknown>
   8:     0x561b5e35710d - <unknown>
   9:     0x561b5f07f86b - <unknown>
  10:     0x561b5f07f7fd - <unknown>
  11:     0x561b5e357841 - <unknown>
  12:     0x561b5f086194 - <unknown>
  13:     0x7fd14b9f2589 - <unknown>
  14:     0x7fd14b5115cc - <unknown>
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!  ', /home/ludo/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs :6196: 
    0x561b5d91de6f - <unknown>
   7:     0x561b5ed0f650 - <unknown>
   8:     0x561b5e35710d - <unknown>
   9:     0x561b5f07f86b - <unknown>
  10:     0x561b5f07f7fd - <unknown>
  11:     0x561b5e357841 - <unknown>
  12:     0x561b5f086194 - <unknown>
  13:     0x7fd14b9f2589 - <unknown>
  14:     0x7fd14b5115cc - <unknown>
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
  10:     0x561b5e5d3827 - <unknown>
  11:     0x561b5e5d435b - <unknown>
  12:     0x561b5e3593bf - <unknown>
  13:     0x561b5e357127 - <unknown>
  14:     0x561b5f07f86b - <unknown>
  15:     0x561b5f07f7fd - <unknown>
  16:     0x561b5e357841 - <unknown>
  17:     0x561b5f086194 - <unknown>
  18:     0x7fd14b9f2589 - <unknown>
  19:     0x7fd14b5115cc - <unknown>
  20:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5d91de6f - <unknown>
   7:     0x561b5ed24060 - <unknown>
   8:     0x561b5d6ba0eb - <unknown>
   9:     0x561b5d6b9f77 - <unknown>
  10:     0x561b5d6b9f77 - <unknown>
  11:     0x561b5d6bbdd1 - <unknown>
  12:     0x561b5d6a8113 - <unknown>
  13:     0x561b5f0873b4 - <unknown>
  14:     0x561b5f07f86b - <unknown>
  15:     0x561b5f086dfb - <unknown>
  16:     0x7fd14b426720 - <unknown>
  17:     0x561b5d6a6268 - <unknown>
  18:                0x0 - <unknown>
thread panicked while panicking. aborting.
Servo exited with return value -4
[ludo@Oulanl servo]$

**Comment by jdm** [comment]
lldb shows me that there are 2051 threads currently active when I lose the ability to spawn more. The vast majority that I see are LayoutWorker and PaintWorker, which I find really interesting.

**Comment by jdm** [comment]
This happens because an iframe sets location.hash to an empty string, which causes us to reload the page and create a new pipeline to do so. This repeats endlessly.

**Comment by jdm** [comment]
We're missing step 6 of https://html.spec.whatwg.org/multipage/browsers.html#navigate which would cause us to abort the navigation in this case.

**Comment by jdm** [comment]
Rather, the implementation in `handle_navigate` relies on a fragment existing, which doesn't match the specification.

**Comment by jdm** [comment]
This is also visible at `https://login.comcast.net/login`. The same facebook iframe as agar.io is responsible for an endless chain of page loads.
