### ISSUE TITLE
Return WindowProxy from HTMLIFrameElement::contentWindow

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10966]
Depends on https://github.com/servo/servo/issues/10965.

**Comment by julienw** [comment]
This is necessary for the tests in https://quirks.spec.whatwg.org/ (eg http://w3c-test.org/quirks-mode/blocks-ignore-line-height.html) to work.

**Comment by jdm** [comment]
This was fixed by #11214.

**Comment by julienw** [comment]
From http://w3c-test.org/quirks-mode/blocks-ignore-line-height.html I get this error with latest master:
```
ERROR:js::rust: Error at http://w3c-test.org/quirks-mode/blocks-ignore-line-height.html:9:9: q is null
```

Their code is
```
        var q = document.getElementById('quirks').contentWindow;
```
where "quirks" is an iframe.

So are you sure the specific bug here is fixed ?

**Comment by Ms2ger** [comment]
Yes. This issue was purely about refactoring. There's another bug for your issue, but I can't find it right now.

**Comment by jdm** [comment]
That's the issue where cross-origin iframes return null for contentWindow/contentDocument, but I'm having trouble finding the issue tracking that.
