### ISSUE TITLE
Implement incumbent, entry, current settings objects / globals / realms

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10963]
Incumbent in particular is needed for security checks (`iframe.contentDocument`, for example).

**Comment by jdm** [comment]
Note to self: find the WIP branch that was trying to implement these concepts.

**Comment by jdm** [comment]
This is not the WIP branch, but included a very minimal `AutoEntryScript` that kept a stack of pipeline IDs that were executing script: https://github.com/jdm/servo/tree/postmessage

**Comment by mrmiywj** [comment]
Mind if I try this and the related issues?
Any reference resource?

**Comment by KiChjang** [comment]
FWIW:
https://html.spec.whatwg.org/multipage/webappapis.html#incumbent-settings-object
https://html.spec.whatwg.org/multipage/webappapis.html#current-settings-object
https://html.spec.whatwg.org/multipage/webappapis.html#entry-settings-object

**Comment by jdm** [comment]
@mrmiywj This is not something I would feel comfortable having someone work on without dsicussing the necessary work and implementation plan first.

**Comment by jdm** [comment]
Also https://github.com/servo/servo/commit/e3873c2c43ab00896fa6e6aa8f1daa414f8ea2fe is a more recent implementation of the sort of thing we need here.

**Comment by mrmiywj** [comment]
Thx! I will take a look on it.
