### ISSUE TITLE
Support WindowProxy return values in bindings

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10965]
Right now, we return the `Window` and grab its `WindowProxy` in bindings code; this is confusing. We should support returning `WindowProxy` (`BrowsingContext`) objects directly from DOM methods.

**Comment by farodin91** [comment]
@Ms2ger would like to work on this one:)

**Comment by jdm** [comment]
My assumption is that we'll need to add something to Bindings.conf that associates the WindowProxy webidl type with the BrowsingContext native type. That may require adding code to Configuration.py to interpret that and code to CodegenRust.py to use the stored configuration data. I don't have any more specific ideas, though.

**Comment by Ms2ger** [comment]
Note that this can't be a normal `interface`, because we don't want to generate bindings for it.
