### ISSUE TITLE
Embedding support for Android

### ISSUE THREAD

**Issue by pocmo** [servo/servo#10967]
Embedding support seems to have a high priority on desktop. It would be nice to have decent support for Android too. Maybe as a "drop-in" replacement for Android's [WebView](http://developer.android.com/reference/android/webkit/WebView.html) (ServoView)?

I looked a bit at the code but it seems like the only touch point with Android's Java APIs is MainActivity and from there everything disappears into "native land".

**Comment by themihai** [comment]
iOS support would be nice too. webkit provides a DOM API (Objective-C) . Does Servo embedding framework provide a such API? 
 Is there any official doc with the current state of the embedding API?

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/DisplayWebContent/Tasks/DOMObjCBindings.html

**Comment by themihai** [comment]
@jdm  Does Servo use/need JIT if JavaScript is not used? I'm not very familiar with the code base so apologies if I'm talking nonsense.  I was thinking to manipulate the DOM directly through an API/binding like webkit provides for Objective-C.

**Comment by pocmo** [comment]
A potential iOS version should get its own bug. This is not really a discussion about Android embedding. :)

**Comment by paulrouget** [comment]
It's not a drop-in replacement of a WebView, but a ServoView component is now available since #21199.
