### ISSUE TITLE
How browser.html scrollbars will be solved?

### ISSUE THREAD

**Issue by lukaszpolowczyk** [servo/servo#10988]
How servo scrollbars will be solved?

At this time, Firefox scrollbar is a XUL element. In browser.html there are only pure HTML.

Everyone HTMLElement will have Shadow DOM with the scrollbar?

I was interested because I create extension, and I would like to be able to control this element and not enough to swap colors of buttons. I want to add a scrollbar new features like markers, context menus, extra actions.

Ability to add additional features is very important.

**Comment by metajack** [comment]
cc @paulrouget @tschneidereit @gozala

**Comment by Gozala** [comment]
I'd say customizable scrollbars is out of scope for now. So far we're just leveraging native scrollbars & have not built any extension system either.

**Comment by tschneidereit** [comment]
I concur, customizable scrollbars aren't something we're planning to support in the foreseeable future. As @Gozala says we're also not planning to support an extensions mechanism for now. That doesn't mean this kind of customization could never be relevant: embedding applications might want something like this. Still, anything in this direction will only become relevant at some unknown point in the future, so I'll close this issue for now.
