### ISSUE TITLE
WebRender missing frame budget on reddit

### ISSUE THREAD

**Issue by metajack** [servo/servo#11009]
I get several messages like this loading reddit.com in browser.html:

```
Render took 71.75146300000051ms & will cause frame drop
Render took 72.84053300000232ms & will cause frame drop
Render took 72.38800099999935ms & will cause frame drop
Render took 72.78471999999601ms & will cause frame drop
```

Most of these were when the page was still all white, so perhaps this is a problem with the progress bar?

**Comment by paulrouget** [comment]
We do have an issue with the progressbar. We are working on it, but in the meantime, use browserhtml with `http://localhost:6060/index.html?progressbar=standalone&raf=timer`.

**Comment by paulrouget** [comment]
I think this is a browserhtml specific issue, nothing to do with servo.

**Comment by metajack** [comment]
Ok. We can reopen if we discover otherwise.
