### ISSUE TITLE
Children of nodes with 'pointer-events: none' set don't receive event if they have 'pointer-events: all' set

### ISSUE THREAD

**Issue by Gozala** [servo/servo#11003]
Here is a code to reproduce it:

```
servo "data:text/html,<div style='pointer-events: none'><button style='pointer-events: all' onmousedown='document.body.style.background=\'red\'' onmouseup='document.body.style.background=null'>Click me</button></div>"
```

Clicking a button should make window background go red, but it does not.

**Comment by paulrouget** [comment]
iirc, `all` is a a SVG-related value. You want to use `auto`.

**Comment by Gozala** [comment]
> iirc, all is a a SVG-related value. You want to use auto.

It seems that `pointerEvents: auto` does work. This bug is still valid though as `pointeEvens: all`  does work in all other engines.

**Comment by nox** [comment]
This is still an issue.

**Comment by jdm** [comment]
Duplicate of #7375.
