### ISSUE TITLE
reddit.com takes much too long to load

### ISSUE THREAD

**Issue by metajack** [servo/servo#11008]
With `./mach run --release --browserhtml` I waited a few minutes and the progress bar never finished the page load.

This is suspected to be caused #3847.

**Comment by paulrouget** [comment]
Can you make sure to use a very recent version of browserhtml and use it with `"http://localhost:6060/index.html?progressbar=standalone&raf=timer"`.

**Comment by metajack** [comment]
I tried that. No there is no progress bar, and after several minutes of waiting, the only thing I get is the title bar updates with the reddit title. No other content is displayed.

I ran with `./mach run --release -- -b -w --pref dom.mozbrowser.enabled 'http://localhost:6060/index.html?progressbar=standalone&raf=timer'`

**Comment by metajack** [comment]
Ok, after a few more minutes, the broken page (as in the screenshot above) was displayed.

**Comment by jdm** [comment]
My investigations suggest that #3847 is totally not the long pole here. More information as it arrives.

**Comment by paulrouget** [comment]
Does it take that much time without browserhtml?

**Comment by jdm** [comment]
Yes. I'm profiling non-browserhtml Servo and the time spent loading reddit.com is highly variable (but usually ridiculous).

**Comment by jdm** [comment]
Yeah, biggest issue here is that the SSL connection for the initial page load can have huge variables. I've seen everthing from 1s to 10s before any the response body starts appearing; my tests show that connecting to http://www.reddit.com yields extremely quick response times, but when it redirects to https the load time goes off the deep end.

**Comment by metajack** [comment]
Do you see similar variation with Firefox or Chrome? Or does this seem to be caused by our stack specifically?

**Comment by jdm** [comment]
The data is a bit confusing. `wget` and `curl` show similar latency to Servo on both OS X and Linux; Firefox and Chrome do not, and spoofing Servo's UA doesn't make a difference.

**Comment by jdm** [comment]
One operating theory is that this is an OpenSSL vs. NSS thing, but Chrome uses BoringSSL and I'm not sure how to check what stack `wget` and `curl` binaries are using.

**Comment by ekr** [comment]
I would be surprised if this were OpenSSL versus NSS. What do wireshark traces show/

**Comment by jdm** [comment]
The remote server sends us the `new session ticket, change cipher spec, encrypted handshake message`, we send `Application Data`, the server ACKs it, then there's an 8 second gap before the remote server sends a series of `Application Data` messages: http://joshmatthews.net/reddit.pcapng

**Comment by jdm** [comment]
I'll see what the equivalent Firefox trace looks like.

**Comment by ekr** [comment]
OK, then this is something on the server side. Probably a throttling mechanism.

**Comment by ekr** [comment]
Can you duplicate it on any other site?

**Comment by jdm** [comment]
So far the only odd HTTPS result I've found is that it took 150s to start receiving the HTTP response body from https://html.spec.whatwg.org/, but only 273ms from https://html.spec.whatwg.org/multipage/.

**Comment by ekr** [comment]
This sounds like it's something local to reddit. I would consider reaching out to them to ask
