### ISSUE TITLE
Servo does not do TLS hostname verification

### ISSUE THREAD

**Issue by brson** [servo/servo#11016]
Servo is built on hyper, which does [not yet do TLS hostname verification](https://github.com/hyperium/hyper/issues/472). I believe without this TLS is essentially insecure.

@sfackler is working on this problem now, which will be solved by a combination of https://github.com/sfackler/rust-openssl-verify to add verification for OpenSSL and https://github.com/sfackler/rust-native-tls which is a platform-specific TLS backend that uses the native stacks on OS X and Windows (and also does hostname verification).

**Comment by brson** [comment]
cc @pcwalton @metajack

**Comment by jdm** [comment]
This is a duplicate of #4954. Thanks for filing!
