### ISSUE TITLE
Add dbus dev to the dependecies list

### ISSUE THREAD

**Issue by dati91** [servo/servo#11030]
After https://github.com/servo/servo/pull/10632 we need to update the [README](https://github.com/servo/servo/blob/master/README.md) dependecies

For Debain-based linuxes: `libdbus-1-dev`

But I'm not sure about the other distros.

**Comment by aneeshusa** [comment]
For Arch, I believe this would be the `libdbus` package, but this is a transitive dependency of `systemd` and should already be installed since systemd is the only supported init system.

**Comment by jdm** [comment]
Looks like Fedora is probably `dbus-devel`.

**Comment by aneeshusa** [comment]
Fedora is done: #11438.

**Comment by jdm** [comment]
We're probably good here, then.
