### ISSUE TITLE
WebRender + Canvas repaints cause huge memory leak.

### ISSUE THREAD

**Issue by Zaggy1024** [servo/servo#11062]
I've made a simple test page for this issue, and when any of the three actions in the JS is performed (setting canvas size, clearing canvas or drawing randomized lines) in a fast loop (works with setInterval and requestAnimationFrame), the memory usage goes up to a gigabyte in somewhere around a minute.

I also tested it with WebRender disabled and it seems not to occur then. The command I used to launch it was "./mach run -r -w [filename]".

[CanvasTest.zip](https://github.com/servo/servo/files/253290/CanvasTest.zip)

**Comment by Zaggy1024** [comment]
Forgot to say, my system specs are:

Windows 10 64-bit
Intel i7 5820K
GeForce GTX 970, driver version 10.18.13.6472

This may or may not be limited to Windows, as @ConnorGBrewster says its memory usage on his system is staying at 70-80 MB.

**Comment by emilio** [comment]
cc @glennw, might we be forgetting of dropping webrender textures or other resources associated to 2d canvases when the canvas is flushed?

With WebGL this might not happen, since the code path used for webrender its radically different.

**Comment by emilio** [comment]
Yep, that's the case I think, webrender images allocated with WebRender's `alloc_image`/`update_image` are never removed from WebRender's resource cache.

@glennw: I can take the time for doing the image deallocation patches, is there anything special that could prevent that?

I can think of a few races that might happen, like webrender not having rendered yet the old frame before we deallocate the image or something like that, but haven't done any analysis so I better go do it and see if there's any crash like that.
