### ISSUE TITLE
Idea: Introduce `SendOrWarn` utility trait to DRY out Sender+warn logic

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#11070]
_Disclaimer: bikesheds lie ahead_

Looking around the codebase, I see [this pattern quite frequently](https://gist.github.com/frewsxcv/253ad060cd988cf8ae7ab07dc98d9aee):

``` rust
if let Err(e) = self.constellation_chan.send(msg) {
    warn!("Compositor resize to constellation failed ({}).", e);
}
```

It might be nice if this was DRY'd out such that it looked something like:

``` rust
self.constellation_chan.send_or_warn(msg);
```

Here is what a new trait might look like:

``` rust
use std::sync::mpsc;
use std::fmt;

trait SendOrWarn<M: fmt::Debug> {
    fn send_or_warn(&self, msg: M);
}

impl<M> SendOrWarn<M> for Sender<M>
    where M: fmt::Debug
{
    fn send_or_warn(&self, msg: M) {
        if let Err(e) = self.send(msg) {
            warn!("Sending message to '{:?}' failed ({}).", self, e);
            // FIXME: Can't do this because 'msg' is moved.
            // warn!("Sending '{:?}' message to '{:?}' failed ({}).",
            //       &msg, self, e);
        }
    }
}
```

Anyways, just experimenting and throwing out ideas. No feelings hurt if this gets closed.

**Comment by frewsxcv** [comment]
cc @asajeffrey since (I think?) this is related to the constellation hardening effort

**Comment by asajeffrey** [comment]
Might be a good idea. My main reluctance is that we've lost the message text. We could:
```rust
self.constellation_chan.send_or_warn(msg, "blah blah");
```
or:
```rust
self.constellation_chan.send(msg).or_warn("blah blah");
```
This last one isn't a million miles away from my original:
```rust
self.constellation_chan.send(msg).or_else(|| warn!("blah blah"));
```
which @nox was not too happy about, as that's using a combinator for a side-effect.

**Comment by nox** [comment]
+1 to a higher-level wrapper that properly convey intent.

**Comment by emilio** [comment]
Related conversation on IRC: http://logs.glob.uno/?c=mozilla%23servo&s=12+May+2016&e=12+May+2016#c428479

**Comment by nox** [comment]
I think our current code is good enough.
