### ISSUE TITLE
pip should be updated when the virtualenv is first created

### ISSUE THREAD

**Issue by autrilla** [servo/servo#11074]
Judging by several reports on IRC, people who have old versions of pip on their systems (OS X ships with 1.4.1, apparently) can't install mach 0.6. To solve this, we could simply update pip whenever we create the virtualenv.

**Comment by metajack** [comment]
Does that just replace the one in the virtualenv or hte system one? If the former, +1.

**Comment by autrilla** [comment]
It updates the one in the virtualenv, as long as the virtualenv is active.

**Comment by campaul** [comment]
I'm interested in working on this. I think I've already got a working solution (on my system it upgrades pip from 7.1.2 to 8.1.2), but I want to verify what happens on a system that's old enough to fail installing mach before I submit a PR.

**Comment by campaul** [comment]
I spoke too soon. I tried on my mac and the upgrade command failed. The only difference I noticed between systems was on my mac`_get_exec(*PIP_NAMES)` is returning the system pip instead of the one in the virtualenv. I'm going to continue investigating.

**Comment by campaul** [comment]
I'm going to assume the system pip issue was just a problem with configuration on my machine. I forced it to use the correct path and was able to reproduce the failure with old pip and fix it with an upgrade. On that note though, would changing `pip = _get_exec(*PIP_NAMES)` to just `pip = find_executable("pip")` be a good idea? Since the virtualenv is already active by then it should always point to the correct pip executable and be more robust to strange system configurations like mine.

**Comment by autrilla** [comment]
@campaul I'm not sure whether mach should be doing that, but it doesn't seem right to me. mach should *always* use the virtualenv and never use the system Python, especially considering it's installing packages, which it won't be able to do if it uses the system Python unless ran with root privileges, which will in turn break your system Python.

As long as the virtualenv is active, it should be fine to use `find_executable`, yes. I'm on the fence regarding using `activate_this.py` vs just calling pip, considering we control how the virtualenv is created and we know what names the pip executables will have. Considering most existing code relies on the virtualenv being active, I suggest we keep it that way for now.

**Comment by campaul** [comment]
The system pip issue I was having is actually https://github.com/servo/servo/issues/8968. I'll follow up in that ticket and make a PR that just upgrades pip for now.

**Comment by campaul** [comment]
#11149 is my PR that fixes this (sort of, it's still being tweaked). #8968 is a different but related issue.

**Comment by Wafflespeanut** [comment]
No one's working on this right now. But, there's an open PR.
