### ISSUE TITLE
Move Image and ImageMetadata types from msg crate to net_traits crate

### ISSUE THREAD

**Issue by jdm** [servo/servo#11077]
These types are already re-exported from the net_traits crate so there are very few places referring to the original types directly. I don't see any need to keep them there.

Code: `components/msg/constellation_msg.rs`, `components/net_traits/image/base.rs`

**Comment by kevgs** [comment]
Hi. I'm new to Rust.

What about WebDriverCommandMsg::TakeScreenshot(PipelineId, IpcSender<Option<Image>>) from constellation_msg.rs which uses Image? If we move Image to net_traits msg will need to export it. But net_traits already exports msg and that will result in cyclic dependency.

**Comment by jdm** [comment]
You're right; I didn't notice that. I think we can still move ImageMetadata, though.

**Comment by kevgs** [comment]
#11083

**Comment by kevgs** [comment]
This is my PR for this issue #11083

**Comment by kevgs** [comment]
Here is commit https://github.com/servo/servo/commit/33fa63a3c5f2f2df27b68ca67cf46bf9788d8723

**Comment by jdm** [comment]
Thanks!
