### ISSUE TITLE
Move ConvertPipelineIdFromWebRender to compositing

### ISSUE THREAD

**Issue by jdm** [servo/servo#11082]
It's defined in `msg`, but only used in `compositing`.

Code: `components/msg/constellation_msg.rs`, `components/compositing/compositor.rs`

**Comment by saneyuki** [comment]
@jdm 

I'll take this.

But `ConvertPipelineIdFromWebRender` is pair of `ConvertPipelineIdToWebRender` which is used in `components/layout/webrender_helpers.rs` and `components/layout/layout_thread.rs`.

Should we move this into `compositing` really?

**Comment by saneyuki** [comment]
> But ConvertPipelineIdFromWebRender is pair of ConvertPipelineIdToWebRender which is used in components/layout/webrender_helpers.rs and components/layout/layout_thread.

Sorry, I missed #11081.
Okay, I'll work this
