### ISSUE TITLE
Fixed width buttons cause extra space on their right.

### ISSUE THREAD

**Issue by Zaggy1024** [servo/servo#11085]
In this test case there is a huge gap between the last button and the right of the div when in there should be no gap at all.

I believe this bug is what causes this rendering issue on reddit.com: http://i.imgur.com/1tPkaBw.png The text "prev" (indented using "text-indent: 50px" so as to be hidden in overflow) should not be visible and the two buttons should be nicely aligned with the right side of the box.

There are a few other spacing problems in this test case that I haven't looked at, specifically a small space under the buttons, and a large gap at the bottom of the text div on the left.

[button_text_clipping.zip](https://github.com/servo/servo/files/254143/button_text_clipping.zip)

**Comment by Zaggy1024** [comment]
For reference, this is how the test case renders:
Servo: http://i.imgur.com/ZhtDLfc.png
Firefox: http://i.imgur.com/kqPBxuk.png

**Comment by mbrubeck** [comment]
This is fixed.
