### ISSUE TITLE
Move ConvertPipelineIdToWebRender to layout_traits

### ISSUE THREAD

**Issue by jdm** [servo/servo#11081]
It's defined in the `msg` crate but only used in `layout` and `compositing`.

Code: `components/msg/constellation_msg.rs`, `components/layout_traits/lib.rs`

**Comment by kevgs** [comment]
Here is my PR #11084

**Comment by kevgs** [comment]
Here is the patch https://github.com/servo/servo/commit/9a8c81773a7dc51301e52ce3f02f8ea55984365a
