### ISSUE TITLE
Some TP5 sites take too long to load

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#11087]
## Steps to reproduce
1. Download `tp5n.zip` from https://wiki.mozilla.org/Buildbot/Talos/Tests#tp5 (tp5n contains several scrapped websites from Alexa 500 Top list, which is used in Talos' page load test.)
2. Serve the pages with `python -m SimpleHTTPServer`
3. Run servo with Linux's `timeout` command: `timeout 300s ./mach run -z -x -o output.png <url>`
## Expected

All pages are loaded within 5 min (= 300s)
## Actual

There pages takes more then 5 minute and was killed:

```
Test timeout: http://localhost:8000/page_load_test/163.com/www.163.com/index.html
Test timeout: http://localhost:8000/page_load_test/aljazeera.net/aljazeera.net/portal.html
Test timeout: http://localhost:8000/page_load_test/bild.de/www.bild.de/index.html
Test timeout: http://localhost:8000/page_load_test/chinaz.com/chinaz.com/index.html
Test timeout: http://localhost:8000/page_load_test/digg.com/digg.com/news/story/New_logo_for_Mozilla_Firefox_browser.html
Test timeout: http://localhost:8000/page_load_test/guardian.co.uk/www.guardian.co.uk/index.html
Test timeout: http://localhost:8000/page_load_test/homeway.com.cn/www.hexun.com/index.html
Test timeout: http://localhost:8000/page_load_test/ifeng.com/ifeng.com/index.html
Test timeout: http://localhost:8000/page_load_test/imdb.com/www.imdb.com/title/tt1099212/index.html
Test timeout: http://localhost:8000/page_load_test/indiatimes.com/www.indiatimes.com/index.html
Test timeout: http://localhost:8000/page_load_test/mashable.com/mashable.com/index.html
Test timeout: http://localhost:8000/page_load_test/naver.com/www.naver.com/index.html
Test timeout: http://localhost:8000/page_load_test/noimpactman.typepad.com/noimpactman.typepad.com/index.html
Test timeout: http://localhost:8000/page_load_test/people.com.cn/people.com.cn/index.html
Test timeout: http://localhost:8000/page_load_test/reuters.com/www.reuters.com/index.html
Test timeout: http://localhost:8000/page_load_test/slideshare.net/www.slideshare.net/jameswillamor/lolcats-in-popular-culture-a-historical-perspective.html
Test timeout: http://localhost:8000/page_load_test/sohu.com/www.sohu.com/index.html
Test timeout: http://localhost:8000/page_load_test/store.apple.com/store.apple.com/us@mco=Nzc1MjMwNA.html
Test timeout: http://localhost:8000/page_load_test/thepiratebay.org/thepiratebay.org/top/201.html
Test timeout: http://localhost:8000/page_load_test/uol.com.br/www.uol.com.br/index.html
Test timeout: http://localhost:8000/page_load_test/wsj.com/online.wsj.com/home-page.html
Test timeout: http://localhost:8000/page_load_test/xinhuanet.com/xinhuanet.com/index.html
```

Related: #10452, https://github.com/shinglyu/servo-perf/issues/1

CC @larsbergstrom @rzambre

**Comment by shinglyu** [comment]
One side note: I used `-x -o output.png` and added the following useragent script:

```
var timeout = 5;
window.setTimeout(function(){
  console.log("[PERF] Timeout after " + timeout + " min. Force stop");
  printPerfTiming();
  window.close();
}, timeout * 60 * 1000)
```

But both didn't kill servo in 5 minutes, the `timeout` command killed it from outside.

**Comment by shinglyu** [comment]
@larsbergstrom Are we actively fixing this problem? It is causing ~25/51 TP5 tests to fail intermittently.

**Comment by jdm** [comment]
Are those same pages available where other people can replicate the problem?

**Comment by larsbergstrom** [comment]
@shinglyu I was looking in the perf bug (https://github.com/shinglyu/servo-perf/issues/1) at some of the listed sites. It appears we're continuing to do useful work the whole time (downloading more resources, etc.) so I suspect that there's something going on here inside of either Servo's network stack that's causing it to be really slow or where we re-do way too much work every time we load a new resource, and these pages just have a LOT of resources.

**Comment by metajack** [comment]
cc @nox

I wonder if this is going to end up being similar to #8342.

**Comment by metajack** [comment]
@jdm I believe shing put them on bitbucket or somewhere else since he doesn't have access to the mozilla org. It's probably time to make private servo org repos and host our things there.

**Comment by shinglyu** [comment]
@jdm: You can download them here: http://people.mozilla.org/~jmaher/taloszips/zips/tp5n.zip These are the pages used in Gecko's talos test.

**Comment by shinglyu** [comment]
If you click on the "Job Details" tab in treeherder stage, you can see a list of timeout pages: https://treeherder.allizom.org/#/jobs?repo=servo&selectedJob=30
![](https://cloud.githubusercontent.com/assets/3250983/15569822/86947432-2365-11e6-8abd-9e68cdf716d5.png)

Here is a list of the test I run: https://github.com/shinglyu/servo-perf/blob/master/page_load_test/20160526.manifest

The one starts with `#` is know to be taking too long, so I disable them to save some testing time. I'll re-enable them once I have a smarter way to skip them.

**Comment by pwnorbitals** [comment]
Is this still reproducible ?

**Comment by jdm** [comment]
We don't run TP5 any more, so it's not worth leaving this open.
