### ISSUE TITLE
build error: failed to run custom build command for `dbus v0.3.3`

### ISSUE THREAD

**Issue by broesamle** [servo/servo#11128]
```
error: failed to run custom build command for `dbus v0.3.3`
Process didn't exit successfully: `/home/helge/Development/servo/target/release/build/dbus-556f3a8185acdb67/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\"` did not exit successfully: exit code: 1\n--- stdout\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n"', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I suspect a bad/interrupted download my have put the package db into an inconsistent state especially because of this `dbus-1 was not found in the pkg-config search path`

(however, deleting the target completely and build again gives me the same library: `dbus v0.3.3`)
How would I re-initialize the package management system used locally within servo?

**Comment by jdm** [comment]
It's actually complaining that you don't have the native dbus-1 library. You'll want to install that via your operating system's package manager.

**Comment by broesamle** [comment]
well ... but it built before and apt-get tells me its already up to date ... ill test with a fresh clone of my fork in a separate dir

**Comment by jdm** [comment]
You'll specifically need the development package, which is usually something like `dbus-1-devel` depending on the naming scheme of your distribution.

**Comment by broesamle** [comment]
Thank you for pointing that out...Things are running nicely again :-)

**Comment by MartyIX** [comment]
(I installed `sudo apt install libdbus-glib-1-dev` to fix the issue on my Ubuntu 16.04)

**Comment by batisteo** [comment]
For Fedora: `sudo dnf install dbus-devel`

**Comment by mk-tool** [comment]
@MartyIX 
Thanks. I encountered an error like below and I could fix under Ubuntu18.04.

```
error: failed to run custom build command for `dbus v0.3.4`
```
