### ISSUE TITLE
Text being clipped after window resize

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#11120]
Visualisation of the issue using testcase from #10499:
![clipping](https://cloud.githubusercontent.com/assets/1777894/15129831/968e4cce-1644-11e6-9cc7-85b80e08e48a.gif)
Hovering the link triggers #11024, which corrects the issue.

This happens both with and without webrender.

**Comment by kilobtye** [comment]
I met the same issue. And it's not just text.

After some debugging, I found the overflow size is not updated after window resize. I tried to add STORE_OVERFLOW to layout_thread::reflow_all_nodes and the issue is gone.

Don't know if it is a proper solution, since I'm new to servo.

**Comment by jdm** [comment]
@mbrubeck ^

**Comment by mbrubeck** [comment]
@kilobtye:

> After some debugging, I found the overflow size is not updated after window resize. I tried to add STORE_OVERFLOW to layout_thread::reflow_all_nodes and the issue is gone.

That sounds correct to me.  Could you submit a PR, please?

Thanks!
