### ISSUE TITLE
Work queue implementation should special-case single-threaded version

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#11133]
In https://github.com/servo/servo/blob/master/components/util/workqueue.rs, we still have a bit of overhead (atomic ref count bumps, extra thread, etc.) in the case where there is only 1 thread. Consider removing all of that and having a special case for the sequential path.

**Comment by saneyuki** [comment]
@larsbergstrom Can I take this?

**Comment by larsbergstrom** [comment]
@saneyuki Please do, and thank you for working on this!

**Comment by jdm** [comment]
@saneyuki Have you made any progress here? Any questions?

**Comment by saneyuki** [comment]
@jdm 

I have not begun this yet (Sorry, I'm very busying now...)
I'll try in this week end.

**Comment by jdm** [comment]
@saneyuki Are you still working on this? It might be nice to let someone else tackle it, otherwise.

**Comment by metajack** [comment]
Is the idea here to get rid of our dual implementation of the traversal and just use a work queue with a single worker instead?

cc @pcwalton @avadacatavra

**Comment by pcwalton** [comment]
I'm not sure this is still valid.

**Comment by saneyuki** [comment]
@jdm sorry, I'm not working on this. I'll unassigned me.

**Comment by cynicaldevil** [comment]
Can I take up this issue? I have coded a bit in Rust, but I haven't touched the multithreading part of this language yet. I can start work on this after I read the topic and get familiar with it (probably within 2-3 days).

**Comment by jdm** [comment]
@cynicaldevil I would say yes, but the past few comments suggest that it's not clear what we're trying to accomplish here yet.

**Comment by pcwalton** [comment]
I'm not sure what this is suggesting that we do beyond "use `sequential.rs` when there's only one thread" (which is something we already do, incidentally).

**Comment by nox** [comment]
That module is long dead.
