### ISSUE TITLE
When the Servo window gains focus, it should update the mouse coordinate

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11130]
This is important for browserhtml. We need this to build automated tests.

in `ports/glutin`, the mouse coordinate is updated when receiving a glutin mousemove event.

When Servo starts, as the mouse moves, `mouse_pos` is updated. Then Servo loses focus. User moves the mouse. When Servo gains focus, the mouse is likely not at `mouse_pos` anymore. That means:
1. `mouseover` is not triggered and `:hover` styles are not applied for element below the mouse
2. if a click occurs before the mouse is moved, the clicked is triggered for the element that was under the latest known coordinate (right before losing focus)

We should update `mouse_pos` when gaining focus, and fire a mousemove event if it changed.

There is a `Focused(bool)` glutin event, but it doesn't come with new mouse coordinates.

**Comment by tschneidereit** [comment]
In addition, a `mouseout` event (with the current coordinates) should be fired upon losing focus, and any `:hover` states reset.

**Comment by paulrouget** [comment]
> In addition, a mouseout event (with the current coordinates) should be fired upon losing focus, and any :hover states reset.

That will happens automatically. When I'm talking about mousemove, I'm talking about `WindowEvent::MouseWindowMoveEventClass`.

**Comment by paulrouget** [comment]
If someone can tell me how to get the mouse coordinates from a `didBecomeKey` notification, i can take care of the rest (is `NSEvent::locationInWindow(nil)` supposed to work?).

/cc @pcwalton

**Comment by paulrouget** [comment]
We get a `NSAppKitDefined` nsevent before getting the focus notification. So maybe we can use that to get a `nsevent` instance and do `nsevent.locationInWindow()`.

**Comment by paulrouget** [comment]
When a Firefox window is unfocused, the chrome still get mouse events.

I think this is done with NSTackingArea:
- http://mxr.mozilla.org/mozilla-central/source/widget/cocoa/nsCocoaWindow.mm#3086
- http://mxr.mozilla.org/mozilla-central/source/widget/cocoa/nsCocoaWindow.mm#2406
- https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSTrackingArea_class/
- https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/EventOverview/TrackingAreaObjects/TrackingAreaObjects.html

**Comment by paulrouget** [comment]
First thing first, a click should not rely on the previous mousemove coordinate, but on the actual coordinate.

In Glutin:

In `src/events.rs`, we need to change `MouseInput(ElementState, MouseButton)` to MouseInput(ElementState, MouseButton, Option<(i32, i32)>)`. `Option<(i32, i32)>` will hold the new coordinates.

In `src/api/cocoa/mod.rs`, `MouseInput` events should include the coordinates (see how we retrieve the coordinates in `NSRightMouseDragged`). For other platforms, we can just use `None` for now.

In Servo:

In `ports/glutin/window.rs`, for `Event::MouseInput` events, if coordinates are present, `self.mouse_pos` should be updated and a `WindowEvent::MouseWindowMoveEventClass` should also be fired in addition to any event `handle_mouse` will eventually fire.

**Comment by mrmiywj** [comment]
@paulrouget 
I'll pick this up.

**Comment by metajack** [comment]
@mrmiywj Have at it!

**Comment by jdm** [comment]
@mrmiywj Have you made any progress on this?

**Comment by mrmiywj** [comment]
@jdm 
Yep, I've finished my finals and will go on work on servo.

**Comment by mrmiywj** [comment]
@paulrouget 
I read through all your solutions, does it mean that I need to modify glutin's source code?

**Comment by paulrouget** [comment]
@mrmiywj Yes. I think the proper way of doing it is what I described here: https://github.com/servo/servo/issues/11130#issuecomment-218705665 - that would partially address this issue.

**Comment by mrmiywj** [comment]
@paulrouget 
But, will the Glutin's maintainer approve our modification of its APIs?

**Comment by paulrouget** [comment]
> But, will the Glutin's maintainer approve our modification of its APIs?

This should not a be a problem.

**Comment by mrmiywj** [comment]
@paulrouget 
I've pushed a PR to glutin to fix this issue. Could you review it?

**Comment by paulrouget** [comment]
@mrmiywj thanks for landing the first part. Now we need a glutin update in Servo with the changes I'm describing in the second part of https://github.com/servo/servo/issues/11130#issuecomment-218705665
