### ISSUE TITLE
Implement base URL for Document

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11144]
Currently `Document` only has `URL`, the spec says we need both a `base URL` and a `URL`.

Spec: https://dom.spec.whatwg.org/#concept-document-base-url
Code: `components/script/dom/document.rs`

**Comment by jdm** [comment]
There's `Document::base_url`...

**Comment by ConnorGBrewster** [comment]
@jdm haha wow... @KiChjang and I somehow missed that.

**Comment by KiChjang** [comment]
That's https://html.spec.whatwg.org/multipage/infrastructure.html#document-base-url, which is different than the one defined by the [DOM spec](https://dom.spec.whatwg.org/#concept-document-base-url)

**Comment by jdm** [comment]
The one in the DOM spec has a default value unless set otherwise, which is what the HTML specification does. They're the same concept.
