### ISSUE TITLE
Make Node::BaseURI use the document's base URL

### ISSUE THREAD

**Issue by jdm** [servo/servo#11145]
`Document::base_url()` exists, and it should be used here.

Specification: https://dom.spec.whatwg.org/#dom-node-baseuri
Code: `components/script/dom/node.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/infrastructure/urls/terminology-0/document-base-url.html`

I would expect some test results to change, so they should be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) accordingly.

**Comment by mrmiywj** [comment]
@jdm 
I will pick this up

**Comment by KiChjang** [comment]
You got it!
