### ISSUE TITLE
iframe doesn't clip its content anymore

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11151]
This breaks browserhtml (can't scroll, overflowing content visible when zooming out, chrome buttons are covered by content).

```html
<style>
  iframe {
    display: block;
    width: 500px;
    height: 500px;
    border: 2px solid green;
  }
</style>
<iframe src="http://duckduckgo.com/?q=foobar"></iframe>
```

<img width="912" alt="screen shot 2016-05-12 at 09 34 52" src="https://cloud.githubusercontent.com/assets/373579/15207210/d667c35c-1824-11e6-89e3-372c8c617c18.png">

**Comment by paulrouget** [comment]
Might be related: https://github.com/servo/servo/issues/11150

**Comment by pcwalton** [comment]
More minimal test case:

    <style>
      iframe {
        display: block;
        width: 500px;
        height: 500px;
        border: 2px solid green;
      }
    </style>
    <iframe src="data:text/html,<body style='overflow: hidden; overflow-y: auto;'><div style='background: blue; height: 2000px'>"></iframe>

**Comment by pcwalton** [comment]
Regression started with `overflow: scroll` support: https://github.com/servo/servo/pull/10717

**Comment by paulrouget** [comment]
This is now fixed. But in browser.html, the iframe is not clipped when zoomed out. I'll file a different issue.

**Comment by paulrouget** [comment]
Follow up: https://github.com/servo/servo/issues/11358
