### ISSUE TITLE
mozbrowsererror detail.type is undefined

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11152]
It's supposed to be "fatal". 

I believe it has to do with `type_` here: https://github.com/servo/servo/blob/e2a5b1cb710b4c5d19d0493e2a304152c42feabe/components/script/dom/htmliframeelement.rs#L323

/cc @asajeffrey

**Comment by asajeffrey** [comment]
Hmm, something is up with the JS bindings, I thought `type_` was supposed to map to `type` (which is a reserved word in Rust, hence the underscore).

**Comment by asajeffrey** [comment]
IRC chat with @emilio http://logs.glob.uno/?c=mozilla%23servo&s=12+May+2016&e=12+May+2016#c427769

TL;DR:  `<emiliocobos> ajeffrey: Probably an easy bug to fix, I'll try to have something soon`

**Comment by asajeffrey** [comment]
Should be fixed by #11155.
