### ISSUE TITLE
Windows build: No Rust compiler binary available for this platform.

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11169]
I have problem building servo on Windows 8.1 x64, while running ./mach build. Seems like it cannot download rust compiler.

![rust](https://cloud.githubusercontent.com/assets/10187350/15240751/0366ebb8-18ec-11e6-993e-3e50602e23ad.png)

**Comment by KiChjang** [comment]
Are you using MSYS or MinGW or Cygwin?

**Comment by blacksvk** [comment]
Sorry, my bad, I fotgot to switch to MinGW shell. You can close/delete this issue.
