### ISSUE TITLE
vertical-align causes text to overlap with line above

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#11164]
``` html
foobar
<br>
foo
<span style="vertical-align: 90%;">bar</span>
```
### Firefox

![firefox](https://cloud.githubusercontent.com/assets/1777894/15232195/dd0c7e2a-189f-11e6-8c67-1c8af20c3edf.png)
### Servo

![servo](https://cloud.githubusercontent.com/assets/1777894/15232193/da76a01e-189f-11e6-8b53-84954ad3c96b.png)

**Comment by kaksmet** [comment]
@mbrubeck If you could point me in the right direction I would like to try fixing this.

**Comment by mbrubeck** [comment]
The code involved is in [`InlineFlow::set_block_fragment_positions`][1], and possibly in the code that runs before it that mutates `line.inline_metrics`, like [`new_inline_metrics_for_line` and `new_block_size_for_line`][2].

[1]: https://github.com/servo/servo/blob/1e8ddba3e84617d2e0e01d2e7fbf8548abed518f/components/layout/inline.rs#L1005
[2]: https://github.com/servo/servo/blob/1e8ddba3e84617d2e0e01d2e7fbf8548abed518f/components/layout/inline.rs#L403-L424

**Comment by kaksmet** [comment]
I won't be able to get this done any time soon.
So if someone else wants to fix this, please go ahead.

**Comment by jdm** [comment]
This displays as expected in a recent build.
