### ISSUE TITLE
Floated text is displayed on the wrong line

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#11163]
I encountered this while writing a test for #11142.

``` html
<!DOCTYPE html>
<div style="width: 400px; border: 2px solid green">
    WWWWWWWWWWWW <span style="float: right;">WWWWWWWWWWWW</span>
    WWWWWWWWWWWW <span style="float: right;">WWWWWWWWWWW</span>
    WWWWWWWWWWWW
</div>
```
### Firefox

![firefox](https://cloud.githubusercontent.com/assets/1777894/15231590/69e2cd62-189c-11e6-93fd-6efdcf120ed8.png)
### Servo

![servo](https://cloud.githubusercontent.com/assets/1777894/15231576/50376c1a-189c-11e6-9fdc-5c529a1e9f80.png)

**Comment by stshine** [comment]
This is #13683, let's track it there.
