### ISSUE TITLE
No option is shown in select

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11170]
![select](https://cloud.githubusercontent.com/assets/10187350/15247438/9208abae-1914-11e6-95cc-fdd9ca166b24.png)

```
<!DOCTYPE html>
<html><body>
    <select>
        <option>Option 1</option>
        <option>Option 2</option>
    </select>
</body></html> 
```

**Comment by jdm** [comment]
Yes, `<select>` is completely unimplemented at the moment.

**Comment by nox** [comment]
Closing as duplicate of #3551.
