### ISSUE TITLE
How to prevent Servo shutdown on Escape when iframe is focused

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11194]
For browserhtml, when we get a keypress event and key is the Escape key, we call `event.preventDefault()` to prevent Servo to shutdown.

When the user presses escape when an iframe is focused, the event doesn't go through the browserhtml document, so the compositor handles the keyevent and shuts down Servo.

I think the proper way to handle this is to let the event go through the containing pipeline if the iframe is a mozbrowser iframe, to allow the container the stop the propagation during the capturing phase, or, in our case, `preventDefault()` the event during the bubbling phase. Then the event would not go back the compositor right away.

Another option, a lot simpler, is to just not quit the application on Escape when the focused pipeline is not the top level pipeline. Not sure how that could work, maybe just not send back the key event to the compositor if the pipeline is not the top one:  https://github.com/servo/servo/blob/2c674d0397927ef6563feb70e54f46815af55600/components/script/dom/document.rs#L1129

Also, it's a bit annoying we have to prevent the escape event to reach the glutin window object. Maybe the best way is just to have an option (in `resources/prefs.json`) to allow/disallow shut down on escape (that we would disable for browserhtml).

Please advise.

**Comment by jdm** [comment]
Having a preference that disables shut down on escape sounds like the most sensible choice to me.
