### ISSUE TITLE
compositing should not depend on num-traits

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11198]
The `extern crate` was removed in #11192; we also need to remove the dependency in `components/compositing/Cargo.toml`.

**Comment by jdm** [comment]
After making this change, run `./mach cargo-update -p compositing` to ensure all the `Cargo.lock` files are updated.

**Comment by canaltinova** [comment]
I would like to take this.

**Comment by jdm** [comment]
Please do!
