### ISSUE TITLE
Remove --no-ssl option

### ISSUE THREAD

**Issue by jdm** [servo/servo#11197]
This option has not actually been implemented for a long time, so it would be nice if we didn't lie to users and say that it exists.

Code: `components/utils/opts.rs`

No need for any automated tests here; run `./mach run -- -h` to see the full set of options that are reported before and after the change.

**Comment by mrmiywj** [comment]
@jdm 
I'll pick this up.

**Comment by KiChjang** [comment]
@mrmiywj Do you mind leaving this to other new contributors?

**Comment by evrimoztamur** [comment]
Addressed by https://github.com/servo/servo/pull/11209.
