### ISSUE TITLE
Write a mach command to generate the contents of pub_domains.rs

### ISSUE THREAD

**Issue by jdm** [servo/servo#11216]
It was committed as part of #4519 with no documentation as to how it was created. It should be documented, and have an easy way to regenerate it as the list of official TLDs gets updated in the future.

**Comment by fduraffourg** [comment]
May I work on this?
If so, can you explain more specifically what you expect for the documentation: doc on the source code or somewhere else? And to explain just how to regenerate the list or something else?

**Comment by jdm** [comment]
@fduraffourg Part of the reason I filed this was that I'm not sure where it came from :) If you can find a reasonable source in https://github.com/mozilla/gecko-dev/ that might be a good start.

**Comment by fduraffourg** [comment]
I was thinking of https://publicsuffix.org/ which is maintained by Mozilla.
It's used by Firefox, Chrome, Opera and IE for "Restricting cookie setting" (https://publicsuffix.org/learn/), so I suppose it's appropriate.

**Comment by jdm** [comment]
That does seem sensible.

**Comment by fduraffourg** [comment]
The list is now 7900 items long. From the list specification it also contain wildcard domains (33 of them) and exceptions for wildcard domains (9 of them):
https://publicsuffix.org/list/

The current code iter over every list item to compare it with the domain to check. It can take up to a few ms to process (without taking care of wildcard and exceptions)!

By using a HashSet this lookup is reduced to a few dozens of ns. But as far as I know, we can't construct the HashSet at compile time with a macro (the same way as `vec!` does for `Vec`). This means that the list must be loaded at runtime and passed to the function that uses it.

We could do the same as for the HSTS list, load it inside a CoreResourceManager and pass it to `Cookie::new_wrapped` and `HttpState`. It changes the signature of a lot of functions (mostly on the `HttpState` which must pass the list multiple times before reaching `Cookie::new_wrapped()`).

What do you think would be best? Just simply update the list without touching the existing code (and ignoring wildcard and exception), or try to use a HashSet with all the modifications it implies?

**Comment by fduraffourg** [comment]
What a coincidence: when fetching the last code I ran on `components/net/content_blocker.rs` (2h old commit) which seems to hold the solution I wanted!

It seems that using `lazy_static!` would be a good solution to allow the use of HashSet without touching other structures or functions.

I will work on a PR with this.

**Comment by jdm** [comment]
Sounds great!
