### ISSUE TITLE
Make test-tidy --faster be the default behaviour and add --all parameter

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#11217]
`./mach test-tidy --faster` runs the WPT lint if there is a change to the WPT test files, and `./mach test-tidy` runs the WPT lint on **all WPT files** regardless of whether there's a change. We should instead make `./mach test-tidy --faster` the default behaviour and add an option to run the WPT lint on all WPT files.

Code: `python/tidy/servo_tidy/tidy.py`, `python/servo/testing_commands.py`

**Comment by mitchhentges** [comment]
I think I've got this

**Comment by aneeshusa** [comment]
This isn't finished yet; still need to land a saltfs PR to update our CI configuration and then another PR to actually change the default.
