### ISSUE TITLE
Profiling Parsing

### ISSUE THREAD

**Issue by rzambre** [servo/servo#11218]
Ideally we'd like to know how much time Servo spends in its pipeline stages. Currently we have profiling set up for Styling, Primary Layout Passes, Compositing, Painting and Image Saving. We'd like to get profiling numbers in stages like Parsing, Javascript and resource fetching (network). This issue is focusing only on profiling Parsing. Although some profiling code in script_thread.rs exists, it cannot be used along with the existing -p option. The -profile-script-tasks debug option needs to be used by itself. Also, among the tasks being profiled within script_thread.rs, Parsing doesn't seem to be profiled. The profiling in script_thread.rs is being done slightly differently than how profiling for styling, layout, etc. is being done. Let me know if you have ideas about how to go about doing this. I'll keep hacking around as well :)

**Comment by jdm** [comment]
I have a branch which provides profiling information for HTML parsing, JS evaluation, and HTTP connections. I'll polish it up.

**Comment by fitzgen** [comment]
See also #10908, which exists to explore ways to automate finding areas where we do not have profiling coverage.

**Comment by rzambre** [comment]
@jdm that's great, thanks :)
