### ISSUE TITLE
ConnectionEstablishedTask needs updating

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11227]
The spec at https://html.spec.whatwg.org/multipage/#feedback-from-the-protocol no longer has our step 1 (protocols) and 5 (cookies). I believe those are now handled at https://fetch.spec.whatwg.org/#websocket-protocol. We should review how to update our code to match that.

Code: `components/script/dom/websocket.rs`.

**Comment by nox** [comment]
That was fixed a long time ago.
