### ISSUE TITLE
implement servo --version , and include the compilation date

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11241]
In the browserhtml team, we use servo nightly builds, and it's always difficult to know which version of servo one is currently using.

Could we have a `--version` option, that would return something like:

```
$ servo --version
Servo 0.0.1 - compiled 2016-05-27
```

**Comment by campaul** [comment]
I'm interested in working on this.

**Comment by paulrouget** [comment]
@campaul Thanks! Command line options are defined here: https://github.com/servo/servo/blob/master/components/util/opts.rs

**Comment by jdm** [comment]
The only idea I have for including the build date is to write it to a file in `build.rs` and use that file via the `include_str!` macro.

**Comment by campaul** [comment]
I'm using `env!("CARGO_PKG_VERSION");` to get the version number, so I was thinking I could do something similar and have mach set an environment variable with the current date.

**Comment by jdm** [comment]
That might work too!
