### ISSUE TITLE
Handle panics for all pipeline-associated threads

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11246]
(Preliminary list)

* [x] script
* [x] web workers
* [ ] canvas2d
* [ ] webgl
* [ ] layout
* [ ] layout threadpool
* [ ] paint
* [ ] paint threadpool
* [ ] some networking threads?

**Comment by Ms2ger** [comment]
CC @asajeffrey

**Comment by asajeffrey** [comment]
IRC conversation: http://logs.glob.uno/?c=mozilla%23servo&s=18+May+2016&e=18+May+2016#c432300

TL;DR: get all threads to use `spawn_named_with_send_on_panic`.

**Comment by aneeshusa** [comment]
Does it also make sense to do this for other threads? Specifically, I was thinking of doing this for the time and memory profiling threads, which currently have a few panics in them. (I'd also like to remove those panics at some point...)

**Comment by asajeffrey** [comment]
@aneeshusa yes, we should get all threads using `spawn_named_with_send_on_panic` if possible (of course, this may not be possible for threads that are created by libraries out of our control).

**Comment by jdm** [comment]
I'm not sure that it makes sense to report panics to the embedding that aren't the related to a particular pipeline.

**Comment by asajeffrey** [comment]
It would be nice to have some way to get crash reports for any thread panic, not just pipeline threads. I believe that is what @paulrouget is expecting.

**Comment by Ms2ger** [comment]
Filed #11291 for that.

**Comment by asajeffrey** [comment]
Fixed by #12468

**Comment by asajeffrey** [comment]
Closed by #12468.
