### ISSUE TITLE
requestAnimationFrame runs at 1 FPS

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11260]
… on my computer at least.

Most likely related to https://github.com/servo/servo/pull/11205

**Comment by paulrouget** [comment]
Actually… 0 FPS, unless I resize the window.

**Comment by paulrouget** [comment]
`requestAnimationFrame` doesn't run on my macbook. But it does run on my macbook pro.

**Comment by paulrouget** [comment]
This is the code I use:

```html
<script>
  var x = 0;
  setInterval(() => {
    console.log(x);
    x = 0;
  }, 1000);
  function foo() {
    x++;
    requestAnimationFrame(foo);
  }
</script>

<button onclick="foo()">Start rAF</button>
```

**Comment by nox** [comment]
@pcwalton With the change in #11205, when is `tick_animations_for_pipeline` called again for an animation frame requested by the animation callback itself?

In `run_the_animation_frame_callbacks`, `self.animation_frame_list.borrow().is_empty()` won't be true anymore, so `NoAnimationCallbacksPresent` isn't sent to the constellation.
https://github.com/servo/servo/blob/dea610986dbf4a1e5898cbe6b57832784e786f3a/components/script/dom/document.rs#L1335

Thus in `change_running_animations_state`, `.animation_callbacks_running` isn't set back to `false`.
https://github.com/servo/servo/blob/dea610986dbf4a1e5898cbe6b57832784e786f3a/components/compositing/compositor.rs#L788

Thus on the next `AnimationCallbacksPresent` message sent, `self.tick_animations_for_pipeline(pipeline_id)` won't be called anymore.
https://github.com/servo/servo/blob/dea610986dbf4a1e5898cbe6b57832784e786f3a/components/compositing/compositor.rs#L778-L782

Can that be an issue?

**Comment by pcwalton** [comment]
I'm pretty sure this is a race, which also causes frames to randomly drop on my machine.

**Comment by nox** [comment]
@pcwalton But is it related to what I described?

**Comment by pcwalton** [comment]
Give me a bit to think about it :)

**Comment by pcwalton** [comment]
When I do the tab switch animation, I get a bunch of `DelayedCompositeTimeout` composites. This is probably what's causing the races/jank. There should be none of them.

**Comment by pcwalton** [comment]
A lot of the jank is https://github.com/browserhtml/browserhtml/issues/1042

**Comment by paulrouget** [comment]
I can't reproduce anymore. Not sure what happened.

**Comment by paulrouget** [comment]
Do we still want to investigate this potential race?
Otherwise, let's close this issue.

**Comment by pcwalton** [comment]
Let's close it. The race I thought might have been there turned out not to be a race upon further inspection.
