### ISSUE TITLE
Implement window.openURLInDefaultBrowser()

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11292]
We want to be able to open links in the default browser. This will be used for the crash reporter in browserhtml (see https://github.com/servo/servo/pull/11286 and https://github.com/browserhtml/browserhtml/issues/1001 for context).

**Comment by paulrouget** [comment]
I was thinking of using this: https://crates.io/crates/webbrowser

**Comment by paulrouget** [comment]
We don't want this method to be available for normal content window. So we want to add it to the global only if 1) `dom.mozbrowser.enabled == true` 2) it's the top level window.

Would adding a method to `Window.webidl / window.rs` work? Not sure how to make the method available only for top level windows. Is it possible the dynamically add the method to the global?

**Comment by Ms2ger** [comment]
We need something like <https://developer.mozilla.org/en-US/docs/Mozilla/WebIDL_bindings#Func>; not sure if we have it yet.

**Comment by paulrouget** [comment]
If we do that, even content windows will have the method.

**Comment by nox** [comment]
Taking this.

**Comment by jdm** [comment]
The support for Func at least partially exists due to #10081; I didn't intentionally strip out support for it when porting Gecko's relevant code.
