### ISSUE TITLE
rowspan is not working

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11297]
Cells with rowspan have same size like cells without rowspan.
![rspan](https://cloud.githubusercontent.com/assets/10187350/15427401/1ce09810-1e95-11e6-8a1d-44579fd77c5f.png)

```
<!DOCTYPE html>
<html><body>
    <style>td{ border: 1px solid black;}</style>
    <table>
        <tr><td rowspan="2">TD1</td><td>TD2</td></tr>
        <tr><td>TD3</td></tr>
    </table>
</body></html>
```

**Comment by jdm** [comment]
The test passes after #14518. Thanks for reporting it @blacksvk!

**Comment by mbrubeck** [comment]
Note that there's still some remaining work to get the cell heights correct.  I'll have a PR for that soon.

**Comment by blacksvk** [comment]
@jdm It seems it is not working again in today's windows build.
