### ISSUE TITLE
Constellation panic caused by assertions

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11309]
We allow `assert!` and `assert_eq!` in the constellation. If these assertions fail, they will cause the constellation to crash, without providing any way for the user to submit a crash report. See, e.g. #11298.

If we decide not to allow such assertions, we should add a check to etc/ci/check_no_unwrap.sh (@aneeshusa).

**Comment by asajeffrey** [comment]
The easiest thing to do would be to replace `assert` by `debug_assert`, anyone running a debug build can probably work out how to submit a crash report from a raw panic. This would just hide a failed assert though, should we try to throw a `mozbrowsererror` event instead? (@paulrouget)

**Comment by nox** [comment]
We made constellation panic way less, and the general motto for constellation is to panic there. I think this can be closed now.
