### ISSUE TITLE
qz.com causes rendering glitches in browser.html

### ISSUE THREAD

**Issue by Gozala** [servo/servo#11305]
As you can see from attached picture part of the browser.html becomes transparent and you can see through a desktop background. Also note that window corners at the bottom are no longer rounded, that one is different issue that I see with almost every single page I load.

<img width="807" alt="screen shot 2016-05-20 at 11 13 07 am" src="https://cloud.githubusercontent.com/assets/21236/15437485/34b296f0-1e7c-11e6-9c5d-828e9b1d1da1.png">

/cc @paulrouget

**Comment by paulrouget** [comment]
The radius issue is https://github.com/servo/servo/issues/9983

**Comment by paulrouget** [comment]
Reduced test case (option `-b- is required to reproduce):

```html
<style>
  body {
    background: red;
  }
  iframe {
    background: blue;
    display: block;
    width: 500px;
    height: 500px;
  }
</style>

<iframe mozbrowser="true"></iframe>

<script>
  setTimeout(() => {
    document.querySelector("iframe").src = "http://qz.com";
  }, 1000);
</script>
```

The green part is my desktop background:

<img width="658" alt="screen shot 2016-05-21 at 10 35 09" src="https://cloud.githubusercontent.com/assets/373579/15447349/c85209ae-1f3f-11e6-87da-b815fef1f590.png">

**Comment by nox** [comment]
I can't reproduce this anymore.
