### ISSUE TITLE
CSS properties background-size & background-position don't seem to work.

### ISSUE THREAD

**Issue by Gozala** [servo/servo#11304]
Here is the an html file that can be used to reproduce the issue:

``` js
<style>
.progress {
  display: block;
  width: 100%;
  height: 40px;
  overflow: hidden;

  background-color: inherit;
  background-image: linear-gradient(135deg, #4A90E2 calc(100% - 40px), transparent calc(100% - 40px));
  background-size: 0;
  background-position: 0 20px;
  background-repeat: no-repeat;
}

.progress .value {
  display: block;
  width: calc(100% + 40px);
  height: inherit;
  background-color: inherit;
  background-image: inherit;
  outline: 1px solid red;
}

</style>
<div class="progress" max="100" value="80">
  <div class="value" style="transform: translateX(-20%)"></div>
</div>
```

above page in servo renders as:

<img width="798" alt="screen shot 2016-05-20 at 9 54 22 am" src="https://cloud.githubusercontent.com/assets/21236/15435410/d822b0e2-1e70-11e6-87ad-f6c6030384fe.png">

In other engines it renders as:

<img width="851" alt="screen shot 2016-05-20 at 9 55 16 am" src="https://cloud.githubusercontent.com/assets/21236/15435438/f8bce890-1e70-11e6-80a7-ee03835eb5f0.png">

Difference is that other engines take `background-size: 0` into account and there for outer elements background is not displayed while inner element's is.

Now removing `background-size` property reveals another issue, which is `background-position` is also not taken into account. In servo removing `background-size` has no effect. while in other engines it renders as follows:

<img width="849" alt="screen shot 2016-05-20 at 10 04 24 am" src="https://cloud.githubusercontent.com/assets/21236/15435623/3dd13dc2-1e72-11e6-8e02-71036391b6b9.png">

One more odd behavior observed in servo is revealed by resizing window, when window size is increased at some point `.progress` element seems to overflow under something not sure under what or why though.

**Comment by pyfisch** [comment]
Also `background-repeat` is not supported.

**Comment by nox** [comment]
This still happens.

**Comment by pyfisch** [comment]
This now renders in servo like in other engines. See #19554.
