### ISSUE TITLE
Text within rotated div is displayed incorrectly

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11300]
![rotate](https://cloud.githubusercontent.com/assets/10187350/15427978/06355638-1e99-11e6-8f17-f9036b1f7176.png)

```
<!DOCTYPE html>
<html><body style="font-size: 4em; padding: 1em;">
    <div style="transform: rotateZ(45deg); border: 1px solid red; display: inline-block;">Servo</div>
</body></html>
```

**Comment by pcwalton** [comment]
I think what's going on here is that the transform is being propagated down to both the div and the text fragment (or the outer div and the inner inline-block, or something like that). So it effectively double-counts.

See https://github.com/servo/servo/pull/9503 — the fix will likely be similar

**Comment by vvuk** [comment]
I'll take this

**Comment by vvuk** [comment]
This is fixed by WIP commit 411ac54e6c0926a but there's a further, likely separate, issue with filters -- the following testpage:

```
<!DOCTYPE html>
<html>
  <body style="font-size: 4em; padding: 1em;">
    <div style="clip: rect(0px, 30px, 50px, 0px); position: absolute; top: 5px; left: 5px; border: 1px solid red; display: inline-block;">Servo</div>
    <div style="opacity: 0.5; border: 1px solid red; display: inline-block;">Servo</div>
    <div style="transform: rotateZ(45deg); border: 1px solid red; display: inline-block;">Servo</div>
    <div style="filter: invert(75%); border: 1px solid red; background: red; display: inline-block;">Servo</div>
  </body>
</html>
```

Looks like this in Firefox and in Servo:
![servo-clip](https://cloud.githubusercontent.com/assets/194965/15446243/4fff980c-1ee7-11e6-8dec-ae1d60751870.png)

If I remove the filter div, the rest of the content shows up.  This happens both with and without my changes (though the effects of the filter are double-appliied without my changes). I should probably treat that as a separate issue?

**Comment by pcwalton** [comment]
Let's do it as a separate issue.

**Comment by vvuk** [comment]
Okay -- that commit should be ready for r? @pcwalton .  I've got a commit in front for an annoying windows build issue, or I'd make a PR.  Also I didn't have any good ideas on how to make a test for perspective/clip.. perspective's probably doable, but clip would probably look the same regardless...

**Comment by pcwalton** [comment]
@vvuk 

> I've got a commit in front for an annoying windows build issue, or I'd make a PR.

You can submit the PR by doing:

    $ git checkout -b fix-rotated-div
    $ git rebase -i origin/master
    (delete line representing the commit that works around the windows issue)
    $ git push vvuk fix-rotated-div

That will make a new PR, while keeping your old setup around in the master branch. To get back to your old workspace just use `git checkout master`.

**Comment by pcwalton** [comment]
Commit looks good other than those nits.

**Comment by jdm** [comment]
Latest attempt in https://github.com/servo/servo/pull/14078 still fails to pass the test.

**Comment by nox** [comment]
This was fixed!
