### ISSUE TITLE
When Downloading Host rust library for target x86_64-pc-windows-gnu... interrupted, re-download would be failed

### ISSUE THREAD

**Issue by lygstate** [servo/servo#11319]
Hope the download of rust library for target x86_64-pc-windows-gnu can be resume

**Comment by jdm** [comment]
@lygstate What's the error message received when the resume fails?

**Comment by lygstate** [comment]
@jdm Network connection Error, it's because my network is very slow,  and very easy to shutdown.

**Comment by zeusintuivo** [comment]
I have researched and documented an effective way to have windows environments set up for 32 and 64 bits in Windows 7. I assume this will work in all windowses. 
Please see documentation I posted in this ticket. #12356

**Comment by lygstate** [comment]
seems stable now
