### ISSUE TITLE
Add a test for recomputing overflow when viewport size changes

### ISSUE THREAD

**Issue by jdm** [servo/servo#11328]
I believe https://github.com/servo/servo/pull/11294 should be possible to test by using an iframe and changing its width. Would you like to give this a try, @kilobtye?

**Comment by kilobtye** [comment]
I find there is already a test that should test this issue.
[resize_after_load](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/iframe/resize_after_load.html)

Tried it with older servo version before my pr. It fails sometimes, and passes sometimes. 

I think the reason maybe one more layout can happen after we change iframe width, and makes this test pass. I don't know why the result is not stable.

**Comment by nox** [comment]
So this can be closed, right?
