### ISSUE TITLE
Report use statements that use {} with only one entry

### ISSUE THREAD

**Issue by jdm** [servo/servo#11320]
Our desired code style is:
```rust
use something::foo::Bar;
```
not
```rust
use something::foo::{Bar};
```
Let's report these lines automatically as part of test-tidy.

Code: `python/tidy/servo_tidy/tidy.py`
Test: Add one to `test_rust` in `python/tidy/servo_tidy_tests/test_tidy.py`, which checks `python/tidy/servo_tidy_tests/rust_tidy.rs`. Run with `./mach test-tidy --self`.

**Comment by mbrubeck** [comment]
There's no longer any natural way to format a list of imports from the same module, where just one of the imports needs to wrap to the next line:

```rust
// ERROR: use statement contains braces for single import
use script_layout_interface::restyle_damage::{BUBBLE_ISIZES, REFLOW, REFLOW_OUT_OF_FLOW};
use script_layout_interface::restyle_damage::{RESOLVE_GENERATED_CONTENT};

// ERROR: use statement is not in alphabetical order
use script_layout_interface::restyle_damage::{BUBBLE_ISIZES, REFLOW, REFLOW_OUT_OF_FLOW};
use script_layout_interface::restyle_damage::RESOLVE_GENERATED_CONTENT;
```

Could we either revert this change, or change the alphabetization rule to ignore braces?

**Comment by jdm** [comment]
Ignoring braces will require reformatting the whole tree. Reverting this change will be less work.
