### ISSUE TITLE
Resize of github.com before rendering completes causes scrambled text, graphics

### ISSUE THREAD

**Issue by mikedilger** [servo/servo#11323]
Using current master, built fresh today, on a gentoo linux x86_64 system, running this:
````
./mach run --release -- -w http://github.com
````
seems to work fine if it is not resized until after the first render completes.
![screenshot_2016-05-22_13-13-57](https://cloud.githubusercontent.com/assets/1669069/15451606/c94c62d8-201f-11e6-900f-1f84dc917db0.png)

But if you resize it (I resize from bottom right corner) before rendering completes, the text and some graphics get quite scrambled.
![screenshot_2016-05-22_13-14-42](https://cloud.githubusercontent.com/assets/1669069/15451607/cb7647ea-201f-11e6-807e-e1a7a8e4115c.png)

EDIT: It may not be related to "before rendering completes".  It seems to be hit or miss.  I cannot consistently reproduce it, but I can reproduce it about 1 out of every 6 tries or so.

**Comment by metajack** [comment]
I assume this is webrender specific. Have you tried without `-w`?

cc @glennw @pcwalton

**Comment by mikedilger** [comment]
Without the -w I can't get it to happen, so yes probably webrender.

**Comment by kilobtye** [comment]
I can confirm this issue. And I would like to look into this issue.

**Comment by metajack** [comment]
@kilobtye Feel free to investigate. It's likely caused by the texture caches getting misused in webrender I think. Ping gw (@glennw) and @pcwalton in IRC if you have specific questions.

**Comment by kilobtye** [comment]
Thanks @metajack , it is about texture cache.
This issue is caused by text-shadow. Resize changes font-size and does text-shadow. Then
1. texture blur allocates textures but does not free.
2. texture becomes full and grows its size and messes up.
I will submit a PR to fix a bug in 2, that should fix this issue.

**Comment by metajack** [comment]
Excellent sleuthing!
