### ISSUE TITLE
Remove CompositorEventListener trait?

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11339]
Only `IOCompositor` implements it now, and I doubt we'll reintroduce other implementations.

**Comment by pcwalton** [comment]
Yeah, feel free to do this if it's feasible.

**Comment by kyleheadley** [comment]
I can take this, I need to learn about the PR system anyway. It sounds like this is just to reorganize? I'll move the trait code into the struct impl and test.

cc @asajeffrey

**Comment by Ms2ger** [comment]
Though I notice there's one advantage: it erases the `Window` type parameter.

**Comment by kyleheadley** [comment]
I attempted to remove the trait object all together, but the cef port (at least) depends on the dynamic dispatch. I'm looking into altering cef, but that may be beyond the scope of this issue.
