### ISSUE TITLE
Flexbox `order` should change only visual order, not accessibility tool order

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#11336]
The spec https://www.w3.org/TR/css-flexbox-1/#order-accessibility says

> The order property does not affect ordering in non-visual media (such as speech). Likewise, order does not affect the default traversal order of sequential navigation modes (such as cycling through links, see e.g. tabindex [HTML5]).

We actually sort the items array in https://github.com/servo/servo/blob/master/components/layout/flex.rs#L391 . I'm afraid that will make it hard for screen readers (do we have any?) to get the original DOM order.

**Comment by jdm** [comment]
We don't support them yet, but screen readers will interact with the DOM, not layout information.

**Comment by shinglyu** [comment]
Hmm, screen reader may be a bad example. The spec may be refering to `@media speech { ... }`. I'm not sure if that uses layout information.

**Comment by nox** [comment]
Pretty sure this kind of stuff is supposed to follow DOM too. Closing.
