### ISSUE TITLE
Can't see text in github comment box

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#11354]
![screenshot from 2016-05-24 10 38 42](https://cloud.githubusercontent.com/assets/1617736/15492699/b6afe5c8-219b-11e6-974f-312488389acc.png)

It's possible to write/submit comments on github in servo, but you can't see what you're typing.

**Comment by notriddle** [comment]
Seems this bug has been fixed?

![comment-in-servo](https://cloud.githubusercontent.com/assets/1593513/20314826/c8442b30-ab18-11e6-8e2d-9e3f549c84bc.png)
