### ISSUE TITLE
Maximising a window breaks fonts

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#11356]
This is similar to https://github.com/servo/servo/issues/11355, but seems to be more universal.

Regardless of the renderer/graphics card used, when maximising the window (on webrender) all the text breaks:

![](https://cloud.githubusercontent.com/assets/1617736/15493249/52a4a6a4-21a0-11e6-8015-e932d62fb221.png)

**Comment by nox** [comment]
@Manishearth Does this still happen?

**Comment by Manishearth** [comment]
haven't noticed this in a while
