### ISSUE TITLE
Add a mach command for updating the WPT manifest

### ISSUE THREAD

**Issue by jdm** [servo/servo#11369]
Telling people to run `./mach test-wpt --manifest-update SKIP_TESTS` when they want to have MANIFEST.json get regenerated automatically is annoying. Let's add a `update-manifest` command that does that instead. See the implementation of `cargo-update` vs `update-cargo` in `devenv_commands.py` for an example of delegating to an existing command.

Code: `python/servo/testing_commands.py`

**Comment by DDEFISHER** [comment]
Can I take this?

**Comment by jdm** [comment]
@DDEFISHER Yes, please!
