### ISSUE TITLE
CSS filters cause rest of content to be erased

### ISSUE THREAD

**Issue by vvuk** [servo/servo#11385]
Using a CSS filter causes the rest of the page content to disappear, maybe as if the filtered content is being painted on the page without proper clipping.  Testcase:

```
<!DOCTYPE html>
<html>
  <body>
    Servo<br>
    <div style="filter: invert(75%); background: red; display: inline-block;">Servo</div>
  </body>
</html>
```

**Comment by vvuk** [comment]
If I set a `background: blue` on the body element, it looks like the filter is being applied to an entire tile (512x512).  The yellow outline bits that show up in the first "Servo" word are the result of inverting the antialised edges of black "Servo" rendered on top of blue.  (Without the blue background, the first Servo word does not show up at all.)

![servo-filter](https://cloud.githubusercontent.com/assets/194965/15541305/ea0663c0-2259-11e6-852f-aec80117c360.png)

**Comment by vvuk** [comment]
While a stacking context is created for the filtered element, a layer isn't -- so the filter ends up applying to the entire layer (since it's not otherwise constrained).  @pcwalton tells me it's not worth fixing layerization issues due to the impending switch to WebRender.  Indeed, with `-w`, this looks better, though text doesn't render properly:
![servo-filter](https://cloud.githubusercontent.com/assets/194965/15552284/b8882c56-2287-11e6-9a82-4c07bba6abbb.png)

**Comment by mrobinson** [comment]
This doesn't seem to be an issue any longer, so I'm going to close this one.
