### ISSUE TITLE
Have ./mach test-tidy consider ignored directories

### ISSUE THREAD

**Issue by rebstar6** [servo/servo#11386]
If a change is made to the ignored directories in python/tidy/servo_tidy/tidy.py and then run ./mach test-tidy, that change is not included (it still runs on the added ignored directory).

Example at https://github.com/servo/servo/pull/11238/commits/5b01814ddb0d465e653692856273f841e780f2d4 - on my local machine, the new tests are still tidy-checked even though I ignore the directory.

**Comment by jdm** [comment]
The problem is `get_file_list` in `tidy.py`. The `only_changed_files` branch (which corresponds to `--faster`) ignores the `exclude_dirs` argument. We should also fix the `elif exclude_dirs` branch to use `exclude_dirs` instead of `ignored_dirs`.

**Comment by jdm** [comment]
I reproduced the problem by adding an entry of `os.path.join(".", "components", "whee"),` to `ignored_dirs`, then running:
```shell
mkdir components/whee
echo "fn main() {}" >components/whee/foo.rs
./mach test-tidy --faster
```

**Comment by h4xr** [comment]
Hello, I was trying to work on this issue and was able to figure out a fix.
If no one else is working on this, I will like to take up the issue.
