### ISSUE TITLE
Create a mapping between original DOM text and compressed layout text

### ISSUE THREAD

**Issue by burg** [servo/servo#114]
When a user selects text (in the Future™), what's exposed to JS code are the offsets into original text nodes represented by the rendered text that was selected. For example, JavaScript would see any whitespace or newlines that got compressed during `TextRun` scanning.

In order to implement text selection correctly, there must be a mapping between original DOM text node offsets and compressed text offsets. In Gecko, this is implemented by the `gfxSkipChars` and `gfxSkipCharsIterator` structures.

More information:

* http://dom.spec.whatwg.org/#ranges
* https://developer.mozilla.org/en-US/docs/DOM/Selection

**Comment by mbrubeck** [comment]
This is now done using the various byte-range-to-glyph-slice mapping functions.

**Comment by perlun** [comment]
Wow, that was an old one! 👏
