### ISSUE TITLE
Implement HTMLFormElement Element getter

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11405]
This is just a getter that returns the form element at the given index. `HTMLFormControlsCollection.IndexedGetter` should be used.

---
Spec: https://html.spec.whatwg.org/multipage/forms.html#dom-form-item
Code: `components/script/dom/webidl/HTMLFormElement.webidl` `components/script/dom/htmlformelement.rs` `components/script/dom/htmlformcontrolscollection.rs`

**Comment by jdm** [comment]
Interestingly, there are tests for the named getter (ie. `form.someElement`), but I don't see any for the indexed getter (ie. `form[3]`) in tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/ . We should [write one](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) when implementing this feature.

**Comment by mrmiywj** [comment]
I'll pick this up.

**Comment by jdm** [comment]
Same as other issues; we'll leave this one available for others so you can focus on one or two at a time.

**Comment by catchmrbharath** [comment]
I will work on this.

**Comment by jdm** [comment]
Go ahead!

**Comment by frewsxcv** [comment]
@catchmrbharath Have you already started on this? It looks like @mrmiywj accidentally worked on this in https://github.com/servo/servo/issues/11697.

**Comment by catchmrbharath** [comment]
Thats ok. I had some basic code, but I was stuck on something.
