### ISSUE TITLE
Implement Window.status

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11407]
Blocks #2968.

Test expectations should be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) for `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.html`.

---
Spec: https://html.spec.whatwg.org/multipage/browsers.html#dom-window-status ([webidl](https://html.spec.whatwg.org/multipage/browsers.html#the-window-object:dom-window-status))
Code: `components/script/dom/webidl/Window.webidl` `components/script/dom/window.rs`

**Comment by catchmrbharath** [comment]
I would like to work on this.

**Comment by jdm** [comment]
@catchmrbharath Please do!

**Comment by catchmrbharath** [comment]
@jdm I implemented window.status, but the test corresponding to the change is failing. I am not sure why! Can you take a look?

**Comment by jdm** [comment]
Looks like you got your answer on IRC.
