### ISSUE TITLE
Implement window.alert()

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11402]
We currently have support for `window.alert(DOMString message)` but we do not have `window.alert()` implemented. It should do the same thing as the former, except pass an empty string as the message.

Note: since both methods have the same name, `window.alert()` will be generated as `fn Alert_(&self)`.

---
Spec: https://html.spec.whatwg.org/multipage/webappapis.html#dom-alert (Step 4)
Code: `components/script/dom/webidl/Window.webidl` `components/script/dom/window.rs`

**Comment by jdm** [comment]
We'll need to [update the test results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) for `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.html` after implementing this.

**Comment by mrmiywj** [comment]
I'd like to pick this up after my finals.

**Comment by jdm** [comment]
I'm inclined to leave this available for other people at the moment. We can mark it assigned when you've got the time to work on it.

**Comment by KiChjang** [comment]
I wonder if the WebIDL specifying window.alert() has the message parameter as optional?

**Comment by jdm** [comment]
It does not.

**Comment by ab22** [comment]
Hi, I would like to work on this.

**Comment by ConnorGBrewster** [comment]
@ab22 go for it!

**Comment by ab22** [comment]
Hey guys .. quick question. I'm gettning an error when running `./mach update-wpt /tmp/servo.log` so I decided to manually update the .ini file. Since I'm not familiar with mach, I'm not sure if [this](https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/dom/interfaces.html.ini#L5028-L5029) is the right file to edit. 

I changed FAIL to PASS. Should that be enough?

**Comment by mrmiywj** [comment]
@ab22 Yes. 
But just delete the passed tests item in that file, not change FAIL to PASS
