### ISSUE TITLE
Implement HTMLCanvasElement.probablySupportsContext

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11403]
Blocks #2968.

This just checks if `HTMLCanvasElement.GetContext` would return `None`, if so `probablySupportsContext` should return false, otherwise it will return true.

---
Spec: https://html.spec.whatwg.org/multipage/scripting.html#dom-canvas-probablysupportscontext
Code: `components/script/dom/webidl/HTMLCanvasElement.webidl` `components/script/dom/webidl/htmlcanvaselement.rs`

**Comment by jdm** [comment]
We'll need to [update the test results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) for `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.html`.

**Comment by mrmiywj** [comment]
I'll pick this up after my finals.

**Comment by jdm** [comment]
@mrmiywj We generally prefer people to focus on one or two issues at a time, rather than reserving several.

**Comment by emilio** [comment]
No longer blocking, since this is no longer in the spec, see #11461 and https://github.com/whatwg/html/pull/1459.
