### ISSUE TITLE
Failing to compile dbus and x11

### ISSUE THREAD

**Issue by mikezaby** [servo/servo#11411]
I am trying to compile servo but it's failing in x11 and dbus packages.

The errors:
```
error: failed to run custom build command for `x11 v2.5.1`
Process didn't exit successfully: `/home/miza/projects/servo/target/debug/build/x11-6c84dccffcbd24b3/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"x11\"` did not exit successfully: exit code: 1\n--- stdout\nPackage x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'x11\' found\n"', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build completed in 0:00:01.376296
```
```
error: failed to run custom build command for `dbus v0.3.3`
Process didn't exit successfully: `/home/miza/projects/servo/target/debug/build/dbus-7f7af798babde0c1/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\"` did not exit successfully: exit code: 1\n--- stdout\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n"', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build completed in 0:00:05.081256
```

I am using Debian Stable and I think I have installed the required dev packages: 
`libx11-dev`, `libdbus-1-dev`, `libdbus-glib-1-dev`

**Comment by jdm** [comment]
@mikezaby Can you verify that by running the appropriate apt-get command to install them?

**Comment by mikezaby** [comment]
I said `I think` because i am not sure if there are any other dependency that I don't know.
The packages that I mentioned before are installed.
```
libdbus-1-dev is already the newest version.
libdbus-glib-1-dev is already the newest version.
libx11-dev is already the newest version.
```

**Comment by mbrubeck** [comment]
If you run `pkg-config --cflags dbus-1` at the shell, does it print out anything?  Is the `$PKG_CONFIG_PATH` variable set in your environment?  Are you passing any 

For some reason the pkg-config command is failing when run by these build scripts.

**Comment by mikezaby** [comment]
This issue is reloved, I had installed brew in my user, that had installed and overide the system pkg-config. I removed the brew and now it compiles normaly.
Sorry for the false alarm :disappointed:

**Comment by r105m** [comment]
[x@x servo]$ pkg-config --cflags dbus-1
Package dbus-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `dbus-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dbus-1' found

---
[ww@imnb servo]$ yum list installed | grep dbus
...
dbus.x86_64                         1:1.6.12-17.el7    @anaconda/7.3            
dbus-glib.x86_64                    0.100-7.el7        @anaconda/7.3            
dbus-libs.x86_64                    1:1.6.12-17.el7    @anaconda/7.3            
dbus-python.x86_64                  1.1.1-9.el7        @anaconda/7.3            
dbus-x11.x86_64                     1:1.6.12-17.el7    @anaconda/7.3            
dleyna-connector-dbus.x86_64        0.2.0-1.el7        @anaconda/7.3            
python-slip-dbus.noarch             0.4.0-2.el7        @anaconda/7.3
