### ISSUE TITLE
Support responsive images

### ISSUE THREAD

**Issue by jdm** [servo/servo#11416]
This is a large piece of work that probably depends on making our image loading code better reflect the actual specification model. For more context on what responsive images are, see [the specification introduction](https://html.spec.whatwg.org/multipage/embedded-content.html#introduction-3).

Components:
- [x] [`<picture>`](https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element)
- [x] [`<source>`](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element)
- [x] [sizes attribute](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-sizes) (see #10989 for prior work)
- [x] [srcset attribute](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset) (see #10829 for prior work)
- [x] [relevant mutations](https://html.spec.whatwg.org/multipage/embedded-content.html#relevant-mutations) processing
- [x] [update the source set](https://html.spec.whatwg.org/multipage/embedded-content.html#update-the-source-set) as part of the image selection process
- [x] [environment changes](https://html.spec.whatwg.org/multipage/embedded-content.html#img-environment-changes) processing

**Comment by Jayflux** [comment]
Does servo support base64 encoded images?
`<img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" />`
etc?

**Comment by jdm** [comment]
It should

**Comment by iamneha** [comment]
#18313

**Comment by atouchet** [comment]
Is this issue supposed to be closed?

**Comment by KiChjang** [comment]
I don't believe so; environment changes has yet to be landed.

**Comment by atouchet** [comment]
Is this done now?

**Comment by jdm** [comment]
In general yes. More specific issues for test failures or particular cases that don't work should be filed when encountered.
