### ISSUE TITLE
Some webdriver_handlers functions ignore their pipeline id argument

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11415]
All these functions are called with the top-level browsing context and the pipeline id of the browsing context they care about. Some functions (and the `Parent` branch of `handle_get_frame_id`) just use the top-level browsing context instead.

Are we already able to write tests for these functions?

CC @jgraham @asajeffrey

**Comment by asajeffrey** [comment]
We can test using the wdspec tests (https://github.com/w3c/web-platform-tests/tree/master/webdriver). The current wptrunner includes a servo wdspec test runner (don't think it's made its way to the servo copy though).

**Comment by asajeffrey** [comment]
The webdriver code probably needs rewritten to use FrameId rather than PipielineId. The selection of top-level browsing context makes a big difference in the context of browser.html: #11256.

**Comment by asajeffrey** [comment]
Fixed by #16997, which replaced the uses of pipeline ids by top-level browsing context ids.
