### ISSUE TITLE
Implement CSSOM APIs for hierarchical stylesheet investigation and manipulation

### ISSUE THREAD

**Issue by jdm** [servo/servo#11420]
For more information, see the [specification introduction](https://drafts.csswg.org/cssom/#css-object-model).

Components:
- [ ] [StyleSheet](https://drafts.csswg.org/cssom/#the-stylesheet-interface)/[CSSStyleSheet](https://drafts.csswg.org/cssom/#the-cssstylesheet-interface)
- [ ] [StyleSheetList](https://drafts.csswg.org/cssom/#the-stylesheetlist-interface)
- [ ] [CSSRuleList](https://drafts.csswg.org/cssom/#the-cssrulelist-interface)
- [ ] [CSSRule](https://drafts.csswg.org/cssom/#the-cssrule-interface)
- [ ] [CSSStyleRule](https://drafts.csswg.org/cssom/#the-cssstylerule-interface) (and other derivatives of `CSSRule`)
#10765 was an attempt at this, but it got stuck on hooking up the actual relationships between the various DOM objects which is the most interesting part of this project.

**Comment by Manishearth** [comment]
I've completed said "interesting part of the project" (all the above interfaces know about each other), now all that's left is working on individual attributes. Not sure if this needs to be closed.

**Comment by jdm** [comment]
We have these now, and can open new issues for any particular missing pieces.
