### ISSUE TITLE
Implement HTML5 form validation

### ISSUE THREAD

**Issue by jdm** [servo/servo#11444]
Specification: https://html.spec.whatwg.org/multipage/forms.html#constraints, https://html.spec.whatwg.org/multipage/forms.html#the-constraint-validation-api
#8747 laid the groundwork for this. #10843 is an attempt at implementing it that had a number of issues preventing it from being merged (see final comment).

Prerequisite for #10781.

**Comment by bobthekingofegypt** [comment]
If this is still free I'd like to take a look at it.

**Comment by jdm** [comment]
@bobthekingofegypt It is!

**Comment by KiChjang** [comment]
@bobthekingofegypt Could we hear some feedback on how this is going so far? Any roadblocks that you've came across?

**Comment by bobthekingofegypt** [comment]
Hello @KiChjang 

Not much to report yet, I had hoped to get some good progress when I was off at the end of last week but life got in the way.  Hopefully I'll have some time this weekend.

So far all I have really done is play around with whats was there and some ideas for how I want to lay things out.  Took me a bit of time to work out why I couldn't use the atom macro for minlength but I eventually found the static string file in string-cache but no roadblocks yet.  Also the 3 minute compilation time takes some getting used to.

**Comment by KiChjang** [comment]
@bobthekingofegypt Is this still being worked on?

**Comment by bobthekingofegypt** [comment]
@KiChjang Sorry, I just haven't had the time to make any proper progress yet.  I should have probably stuck to smaller tasks, every time a week passes I have to just remind myself what I was doing instead of making progress.  

Feel free to reassign it if someone else wants to pick it up.

**Comment by jdm** [comment]
This is intended to be worked on by a group of students this term. Please talk to me before anybody starts to work on it!

**Comment by ofekd** [comment]
@jdm Can I join the effort?

**Comment by jdm** [comment]
@ofekd Sorry, I think that would make evaluating their work for academic credit too complicated.

**Comment by jdm** [comment]
I can CC you on other issues you might be interested in, however!

**Comment by biosunbj** [comment]
Hi @jdm 
We are trying to implement the validation methods in validitystate.rs, do we have to check the HTML attribute for each element, such as "required", to make sure the element needs to be validated with the methods in validitystate.rs? Thank you.

**Comment by biosunbj** [comment]
I read the Form validation student project on Wiki, it seems that the last group has already finished the initial steps and the first subsequent step, should we start from the second one, add code to interactive_validation in the htmlformelement.rs file?

**Comment by jdm** [comment]
Yes, please start from the second step.

**Comment by jdm** [comment]
Latest effort was in https://github.com/servo/servo/pull/14566. It stalled after the review, which pointed out some issues that need to be addressed.

**Comment by gpoesia** [comment]
Can I take this one? Is it fine to take the code from #14566, rebase it and start by addressing the comments?

**Comment by jdm** [comment]
@gpoesia That would be great!

**Comment by gpoesia** [comment]
@jdm is there currently any better way of reporting validation problems (step 4 in https://html.spec.whatwg.org/multipage/forms.html#interactively-validate-the-constraints) than writing to stdout?

**Comment by jdm** [comment]
Nope!

**Comment by pshaughn** [comment]
This is presumably why the 'invalid' case in WPT html/semantics/forms/form-submission-0/form-submission-algorithm.html isn't firing any oninvalid events.

**Comment by teapotd** [comment]
@highfive assign me

**Comment by pshaughn** [comment]
Interactions with #25705 exist; hopefully what I've written there is compatible with the direction this is going in.
