### ISSUE TITLE
Add log2 function that accepts a u32

### ISSUE THREAD

**Issue by danlrobertson** [servo/servo#11440]
We currently cast a `u32` value to `f32` in order to use [`f32::log2`](https://doc.rust-lang.org/std/primitive.f32.html#method.log2) in  [`validate_common_tex_image_parameters`](https://github.com/servo/servo/blob/master/components/script/dom/webglrenderingcontext.rs#L346) (See [lines 400 - 408](https://github.com/servo/servo/blob/master/components/script/dom/webglrenderingcontext.rs#L400-L408)). We should be able to implement a efficient `log2` function for `u32` using [`u32::leading_zeros`](http://doc.rust-lang.org/1.2.0/std/primitive.u32.html#method.leading_zeros). I think it would be reasonable for this function to be defined in `webglrenderingcontext.rs` or somewhere in `components/util/`.

If you have any questions please let me know! I'm happy to help whoever decides to tackle this issue.

Relevant files:
`components/script/dom/webglrenderingcontext.rs`

CC @emilio

**Comment by kevgs** [comment]
I'll take this one.

**Comment by emilio** [comment]
Nice, add a comment here if you have any doubts! :)

**Comment by KiChjang** [comment]
Fixed by #11458.
