### ISSUE TITLE
Storage, resource threads race with shutdown to write out their data

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11467]
When receiving an `Exit` message, they try to write out their data to the config dir, but nothing guarantees that they manage to do that before the process exits.

**Comment by jdm** [comment]
Oops. I guess the code that sends the Exit messages should wait for a response.

**Comment by jdm** [comment]
We'll want to make the `Exit` messages take a new `Sender<()>` value, and use that to send a reply after the files are finished being written. See how `CoreResourceMsg::Synchronize` is used by `resource_thread.rs` for an example.

Code: `components/constellation/constellation.rs` (`handle_exit`), `components/net_traits/lib.rs`, `components/net/resource_thread.rs`, `components/net_traits/storage_thread.rs`, `components/net/storage_thread.rs`

**Comment by ab22** [comment]
Sounds like fun but I'm worried I might get stuck with obvious stuff from Rust that I'm not used to yet. I'm willing to take this if it that's ok. :)

**Comment by jdm** [comment]
@ab22 Go ahead! Feel free to ask questions here.

**Comment by ab22** [comment]
I've got the code ready but .. How would I go to test it?

**Comment by KiChjang** [comment]
In this case, if the code compiles (i.e. `./mach build -d` does not report amy errors), then it is good enough.
