### ISSUE TITLE
Make Document::DefaultView return a null value when there's no browsing context

### ISSUE THREAD

**Issue by jdm** [servo/servo#11469]
This requires updating `Document.webidl` to indicate that a [nullable return value](http://heycam.github.io/webidl/#idl-nullable-type) is allowed, then modifying the implementation to check `self.browsing_context()` and return an appropriate value.

**Code**: `components/script/dom/webidls/Document.webidl`, `components/script/dom/document.rs`
**Test**: `./mach test-wpt tests/wpt/web-platform-tests/html/browsers/the-window-object/Document-defaultView.html` should show newly-passing tests, so the expected results will need to be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations).

**Comment by kevgs** [comment]
I'll take this one.

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear.
