### ISSUE TITLE
FileManager::idmap should not be a RefCell

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11466]
We should just store a plain `HashMap` and remove the `borrow()` / `borrow_mut()` calls.

* Code: `components/net/filemanager_thread.rs`

**Comment by jdm** [comment]
No need to run any tests for this; if it compiles, it's good.

**Comment by rwakulszowa** [comment]
Hey, I think I could try to fix this one, unless someone has already started working on it, obviously.

**Comment by Ms2ger** [comment]
Go for it!
