### ISSUE TITLE
gradients within rectangles are rendered wrong

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11486]
Gradients within squares are OK, but gradients within rectagles are rendered wrong.
![gradient](https://cloud.githubusercontent.com/assets/10187350/15626954/b84ae54a-24d4-11e6-9214-efb1ad848cde.png)

```
<!doctype html>
<html>
	<style>
		.gradient{
			width: 200px;
			height: 100px;
			background: linear-gradient(to right bottom,black 50%,lightgray 50%);
		}
	</style>
	<body>	
		<div class="gradient"></div>
	</body>
</html>
```

**Comment by emilio** [comment]
Is that screenshot with WebRender (`-w` switch) or default servo? Does it happen with the other renderer?

**Comment by blacksvk** [comment]
^ That's the default one = without -w switch.

With -w switch:
![gradient2](https://cloud.githubusercontent.com/assets/10187350/15627152/6d37733c-24db-11e6-90ee-5aba69c47ab3.png)

**Comment by metajack** [comment]
@blacksvk I just wanted to let you know that you are filing some great bugs. These are extremely helpful and very much appreciated.

**Comment by emilio** [comment]
Indeed!

I'm looking into this btw.

**Comment by blacksvk** [comment]
@metajack thx, np. I like the idea of Servo project, I'm just trying to be helpful
