### ISSUE TITLE
Kerning is affected by whether an element is floating or not

### ISSUE THREAD

**Issue by mitchhentges** [servo/servo#11482]
When testing with the text "xe", the two characters vary in distance depending on whether the element is floating or not, and if the previous sibling is floating.

This is making it challenging to fix #1516, because the test reference uses floating containers. If "float" affects kerning, then the reference example is different than the test example.
![2016-05-28-105423_800x600_scrot](https://cloud.githubusercontent.com/assets/7784737/15626331/c3d1d8a4-24c2-11e6-8e36-af7cee56df47.png)

**Comment by metajack** [comment]
Wow, nicely spotted.

cc @mbrubeck

**Comment by nox** [comment]
Is this still true? I can't find steps to reproduce in any of the related issues.

**Comment by mitchhentges** [comment]
I'm not sure, it's been a "little" bit since I saw this last haha.
If memory serves correctly, this should reproduce the issue (you might need to fenaggle the positioning of the fixed element):
```
<html>
<head></head>
<body>
    <span style="background-color: #0f0; float: left;">text</span>
    <span style="background-color: #f00; float: left;">xe</span>
    <span style="background-color: #aa0;position:fixed;top: 26px;left: 32px;">xe</span>
</body>
</html>
```

**Comment by mrobinson** [comment]
I'm not seeing this any longer in both legacy and non-legacy layout.
