### ISSUE TITLE
duckduckgo.com is rendered like blank page

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11489]
Right menu appears for the moment, then disappears. Result is blank page.
![ddg](https://cloud.githubusercontent.com/assets/10187350/15627704/954468e2-24ec-11e6-9c23-5755d8a0cafe.gif)

**Comment by metajack** [comment]
Part of #9915.

**Comment by atouchet** [comment]
DuckDuckGo now loads. Should this be closed?

**Comment by metajack** [comment]
It does seem to work just fine now.
