### ISSUE TITLE
Vertical-align is ignored in div with display: table-cell

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11492]
Vertical-align is ignored in div with display: table-cell within div with display:table
![cell](https://cloud.githubusercontent.com/assets/10187350/15633638/c1484258-25b2-11e6-9467-38f69d565860.png)
```
<!doctype html>
<html><body style="font-size: 2em;">
	<div style="display: table; height: 4em;">
		<div style="display: table-cell; vertical-align: middle; background: lightblue;">
			Servo
		</div>
	</div>
</body></html>
```
This issue affects github.com: that's why "This repository" tag within searchbox is not aligned correctly.
![gith](https://cloud.githubusercontent.com/assets/10187350/15633647/0bb917d6-25b3-11e6-904a-9cf5e8b8af05.png)

**Comment by adamncasey** [comment]
I think this'll be fixed when https://github.com/servo/servo/pull/12593 lands

![capture](https://cloud.githubusercontent.com/assets/720498/17159429/25365cc2-5395-11e6-97a5-9db2c24c9fe6.PNG)

**Comment by notriddle** [comment]
Can confirm that the test case and the "This Repository" pill on Github are fixed in master.
