### ISSUE TITLE
Implement more DOMParser::parseFromString arguments

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11505]
Blocks #2968.

We should add support for "application/xml" and "application/xhtml+xml"; we should probably leave "image/svg+xml" unsupported for now.

* Spec: <https://w3c.github.io/DOM-Parsing/#widl-DOMParser-parseFromString-Document-DOMString-str-SupportedType-type>.
* Code: `components/script/dom/domparser.rs`, `components/script/dom/webidls/DOMParser.webidl`.
* Test: `domparsing/DOMParser-parseFromString-xml.html`, `html/browsers/the-window-object/Document-defaultView.html` (once #11502 lands).

**Comment by afluth** [comment]
I would like to try taking this on.

**Comment by KiChjang** [comment]
Sure thing! Ask any questions if you're stuck :)
