### ISSUE TITLE
Review Piston copyright

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11501]
https://github.com/PistonDevelopers/piston/pull/1080 landed a rather curious copyright notice. We should make sure we still want to depend on piston projects with this in place.

**Comment by Manishearth** [comment]
That seems to apply only to license changes? There will still be a solid license, and if they decide to change it we can always fork, which was a danger even without that voting system.

**Comment by nox** [comment]
They can't decide to change without rewriting all the code of contributors that don't want a license change. That particular 95% agreement scares the hell out of me.

**Comment by bvssvni** [comment]
The copyright notice has been removed. People got scared and thought this was weird.
