### ISSUE TITLE
Check if the script thread outlives web worker threads

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11512]
This may be a problem now that we use the parent runtime support.

CC @tschneidereit @nox @jdm

**Comment by tschneidereit** [comment]
Hmm, maybe. I know too little about the lifetime of script threads vs workers to judge this. Ideally we'd have some script thread and JSRuntime whose lifetime is guaranteed to equal the process' lifetime, and make that be the parent for all other JSRuntimes in the process. Might be worth it to create a runtime not used for any actual content just for that. With low heap size and a compacting GC run after its creation, perhaps.

**Comment by jdm** [comment]
For something like browser.html a long-lived runtime for the root page is easy and sensible. For non-browser.html it's much harder to conceptualize what a long-lived script thread would do. A small per-content process runtime that is unrelated to any script thread and usable as the parent for all other runtimes makes the most sense to me.

**Comment by nox** [comment]
I've started to write something in rust-mozjs to go that way.

**Comment by nox** [comment]
https://github.com/servo/rust-mozjs/pull/267
