### ISSUE TITLE
The Million Dollar Homepage renders incorrectly

### ISSUE THREAD

**Issue by cmr** [servo/servo#11510]
Running `./mach run -r -- http://milliondollarhomepage.com/` on a recent build on Linux gives this:
![2016-05-30-231635_800x600_scrot](https://cloud.githubusercontent.com/assets/704250/15650527/92da6e40-26bc-11e6-8160-250c6e51a095.png)

It also dumps this on the console:

```
ERROR:js::rust: Error at http://milliondollarhomepage.com/index_files/:0:9429: Invalid screen name

ERROR:js::rust: Error at http://milliondollarhomepage.com/index_files/info.json:0:5: __twttr.setFollowersCountAndFollowing is not a function
```

but I anticipate those aren't super relevant, as it _does_ partially render the page.

Seems like it's mostly an ungodly `<map>` over [this image](http://milliondollarhomepage.com/index_files/image-map.png).

**Comment by Kelnozz** [comment]
related with #10153?

**Comment by cmr** [comment]
Well it's a png, so...

**Comment by Kelnozz** [comment]
![2016-05-30-162606_361x25_scrot](https://cloud.githubusercontent.com/assets/8824364/15651988/6715a57e-2683-11e6-848f-793d36e3baf4.png)
![2016-05-30-162747_251x57_scrot](https://cloud.githubusercontent.com/assets/8824364/15651996/7c3fa5ee-2683-11e6-8408-5fd1d20fe842.png)

**Comment by jdm** [comment]
The display of the image pixels now looks correct. It's the rest of the page layout that is wrong now.

**Comment by nox** [comment]
It looks correct now.
