### ISSUE TITLE
Implement an image loading model that conforms to the specification

### ISSUE THREAD

**Issue by jdm** [servo/servo#11517]
The goal of this work is to implement the [update the image data](https://html.spec.whatwg.org/multipage/embedded-content.html#update-the-image-data) algorithm in its entirety. It's a big algorithm that doesn't necessarily break down into substeps very well, except for the bits that delegate to sub-algorithms that deal with responsive images (like `selecting an image source`).
1. [x] move all network requests into the DOM (#7708)
2. [ ] make use of the pending and current request data structures in `HTMLImageElement`
3. [ ] get [tests](`tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/img.complete.html`) for `HTMLImageElement.complete` passing
4. [ ] support responsive images (#11416)

**Comment by Coder206** [comment]
@jdm I am interested in helping out for this issue

**Comment by KiChjang** [comment]
@Coder206 This requires a large amount of effort to get it right, and cannot be separated into independent pieces of chunks that can easily be fit into PRs. Are you still certain you are able to work on this?

**Comment by Coder206** [comment]
@KiChjang Thanks for the heads up! It's actually a busy time for me, so that wouldn't have mixed too well. I will work on simpler code for the time being, to get the hang of it, I didn't realize how big of an endeavor it really was. I think it was a little too early for me to start an E-Hard...

**Comment by gterzian** [comment]
is anyone working on this at the moment, or planning to? I could be interested otherwise...

**Comment by jdm** [comment]
@gterzian That would be great! I think the best place to start would be to get the following working:
* sketch out a `update_the_image_data` method that follows [the specification's algorithm](https://html.spec.whatwg.org/multipage/embedded-content.html#update-the-image-data). In particular, implement concepts for [abort the image request](https://html.spec.whatwg.org/multipage/embedded-content.html#abort-the-image-request) and get the sync/async split that happens in step 6 working.
This means that something like `img.src = "foo"; img.src = "bar"` should only trigger one request, because the code that actually processes that runs in the stable state that step 6 mentions which happens after the JS stops executing.

**Comment by gterzian** [comment]
@jdm thanks for the additional guidance! Ok I think we're almost done with the Blob cloning, so I'll start with this once it's done...

**Comment by gterzian** [comment]
I will start looking into this now, perhaps add the 'assigned' label? 😄
