### ISSUE TITLE
focus / blur events aren't dispatched on `window` and `document` objects

### ISSUE THREAD

**Issue by Gozala** [servo/servo#11526]
Here is an example to reproduce it:

https://output.jsbin.com/picawu/3

This is either regression since `focus` / `blur` used to be dispatched on the `document`, or  it could be that @paulrouget had a patch for this that did not end up in upstream.

P.S.: Webkit dispatches focus / blur only on `window` while gecko dispatches them on both `window` and `document`.

**Comment by jdm** [comment]
@Gozala When do you expect these to be fired for browser.html?

**Comment by Gozala** [comment]
> @Gozala When do you expect these to be fired for browser.html?

I expect `blur` events to be dispatched when servo window looses a focus (say you switch to your editor window), then if you switch back to servo window I'd expect `focus` event should be dispatched.

**Comment by jdm** [comment]
This sounds like #9482, in that case.
