### ISSUE TITLE
Fire a basic mozbrowseropenwindow event for target=_blank rel="noopener noreferrer" links

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11539]
See https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowseropenwindow

Implementing `mozbrowseropenwindow` for `window.open` and `<a target=_blank>` is pretty complex (support for WindowProxy, setting the right owner and openers, creating the iframe in servo that would be passed to the event and attached to the DOM by browserhtml…).

For browserhtml, we don't need the whole mechanism just yet, we need it for a specific case: `<a target="_blank" rel="noopener noreferrer">`.

We would like, in this case, to get a simple `mozbrowseropenwindow` without the `frameElement`.

**Comment by paulrouget** [comment]
@asajeffrey is looking at this.

**Comment by asajeffrey** [comment]
I am indeed. My WIP is https://github.com/asajeffrey/servo/commit/82b5eee6ca8c62ffebb68a8a1771b99d05c96f41, hopefully that'll turn into a PR soon.

**Comment by asajeffrey** [comment]
IRC conversation http://logs.glob.uno/?c=mozilla%23servo&s=31+May+2016&e=31+May+2016&c444400#c444400

**Comment by asajeffrey** [comment]
Is the `details.name` field meant to be the browsing context name (that is the `target` attribute of the anchor)? If so, can we rename this to `details.target`? If not, I don't know what value to put here.

**Comment by paulrouget** [comment]
It's strWindowName as described here: https://developer.mozilla.org/en-US/docs/Web/API/Window/open so yes, it's target.

**Comment by asajeffrey** [comment]
Any chance we could rename `name` to `target`? `name` is very generic.

**Comment by paulrouget** [comment]
> Any chance we could rename name to target? name is very generic.

We don't support Gecko anymore, so I guess it's ok as long as MDN is updated.

**Comment by asajeffrey** [comment]
Thanks! Should `mozbrowseropentab` have a `details.target` field too?

**Comment by asajeffrey** [comment]
PR submitted.

**Comment by asajeffrey** [comment]
BTW, we now have the machinery in Servo for browser.html to support named browsing contexts, it would need to keep track of a name-to-iframe mapping, and use that to decide whether to respond to a `mozbrowseropenwindow` event by opening a new tab or recycling an existing one.

**Comment by paulrouget** [comment]
> BTW, we now have the machinery in Servo for browser.html to support named browsing contexts, it would need to keep track of a name-to-iframe mapping, and use that to decide whether to respond to a mozbrowseropenwindow event by opening a new tab or recycling an existing one.

Maybe that should be handled at the browserhtml level.

And there's also the issue of the referrer and the opener.

We could go for the gecko approach where `mozbrowseropenwindow` event comes with an iframe that is already initialized with all the proper stuff (url already set, right browsing context, loaded in the right process, …), and that browserhtml would append to the dom.

There's also the Electron approach, where in the case of new window / new tab, referrer is set by hand (referrer = url of the iframe that is triggering the event), and it just doesn't support opener.

But I'm not 100% it's what we want to do with Servo. There's probably a smarter way to deal with all of that. We do have some ideas.

But let's have this conversation later :)

**Comment by paulrouget** [comment]
For full support in browserhtml, we also need https://github.com/servo/servo/pull/11554

**Comment by asajeffrey** [comment]
The iframe might be tricky to supply, just because we need to do some inter-process communication go get it built in the browser.html process rather than the process containing the hyperlink. Serialising the url is no problem.

Similarly, referrer is probably easy to set because it's a url, but opener is tricky because it's a `WindowProxy`, which we currently don't support.

Anyway, we can now do the basic non-iframe, non-referrer, non-opener case!

**Comment by paulrouget** [comment]
> Anyway, we can now do the basic non-iframe, non-referrer, non-opener case!

Works for me.
