### ISSUE TITLE
Intermittent timeout in /css21_dev/html4/at-charset-074.htm , /css21_dev/html4/at-charset-072.htm

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#11541]
https://github.com/servo/servo/pull/11221#issuecomment-222909412

**Comment by izgzhen** [comment]
Okay these two failed tests... 🙈 I was really confused at that time because I didn't remember that these two were broken in building of PR 11221

**Comment by jdm** [comment]
Not seen in several months and the tests are disabled. Closing.
