### ISSUE TITLE
keyup / keydown is not dispatched for modifier keys

### ISSUE THREAD

**Issue by Gozala** [servo/servo#11547]
Here is a page to reproduce the issue:

https://output.jsbin.com/difoze

When `control` key pressed text `Control` should appear and when it's released `Control` text should disappear (same with other keys). In servo all keys will appear / disappear except for modifiers like control, meta, shift

**Comment by Gozala** [comment]
It seems that behavior regressed further since my report, now we don't keydown evens for any of the modifiers keys either.

**Comment by jdm** [comment]
LLDB confirms that the modified keys do not even reach `Document::dispatch_key_event`.

**Comment by jdm** [comment]
In fact, we are not even getting WindowEvent::KeyEvent messages for the modifier keys, so the problem lies in glutin.

**Comment by jdm** [comment]
Nevermind, the culprit is `handle_window_event` in ports/glutin/window.rs. It explicitly handles modifier keys differently.

**Comment by jdm** [comment]
All that being said, this code has not been touched in at least 1.5 years. I don't understand how this could have regressed.

**Comment by jdm** [comment]
Case in point: #11594 should fix this issue, but the keycode mappings never existed. I suspect the actual issue in browser.html is that your keybindings became more strict or something.
