### ISSUE TITLE
SubmittedFrom, ResetFrom variants have repetitive names

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11557]
`components/script/dom/htmlformelement.rs` has
```rust
pub enum SubmittedFrom {
    FromFormSubmitMethod,
    NotFromFormSubmitMethod
}

pub enum ResetFrom {
    FromFormResetMethod,
    NotFromFormResetMethod
}
```

The suffixes are not particularly useful and should be removed.

**Comment by Coder206** [comment]
@Ms2ger Do you just want to remove these enums?

**Comment by Ms2ger** [comment]
No, rename the variants, for example from `FromFormResetMethod` to just `FromForm`

**Comment by rafaqtro** [comment]
i'd like to do it

**Comment by KiChjang** [comment]
Certainly!
