### ISSUE TITLE
Slow-then-fast memory leak with changing image size

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1155]
When I view `longcat.html`, system memory usage grows by about 2.5 MB/s for the first 10 seconds, and thereafter by about 80 MB/s.  Killing Servo with `^C` works after a multi-second pause in which my entire X session is frozen.

I'm using CPU rendering (`-c`) and can't test with GPU at the moment due to driver issues.

This happens with some other image-size-changing demos, but not with `filmstrip.html`, which is re-running layout but not changing image sizes.

**Comment by nox** [comment]
@pcwalton Is this issue still relevant?

**Comment by mrobinson** [comment]
I think we can close this and just reopen a new issue with newer details if we see it again. It's so old that a lot of the current information is probably no longer relevant.
