### ISSUE TITLE
Fire a mozbrowserclose event when a page calls window.close()

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11560]
At the moment we close the constellation when a page calls `window.close()`. In the mozbrowser case, we should fire a `mozbrowserclose` event.

cc @paulrouget (you may want to set a priority for this)

**Comment by paulrouget** [comment]
Not high priority as this is not a thing we use in browserhtml yet.

**Comment by paulrouget** [comment]
Not needed anymore.
