### ISSUE TITLE
Clipping issues in webrender 

### ISSUE THREAD

**Issue by Gozala** [servo/servo#11562]
Here is an example to reproduce the issue:

https://jsbin.com/fonumu

It renders as follows:

<img width="189" alt="screen shot 2016-06-02 at 11 37 22 am" src="https://cloud.githubusercontent.com/assets/21236/15756507/69fefab2-28b6-11e6-87ab-d7e0dd42b416.png">

Issue is that image is not clipped properly, I believe it's related to the exception case @pcwalton mentioned in his webrender talk at rust meetup:

> - Typically, all display items can be batched together to minimize state changes.
> - Exceptions are if we run out of texture space in an atlas or have a clipping region that isn't a (rounded) rectangle.

**Comment by paulrouget** [comment]
Works now.
