### ISSUE TITLE
Intermittent failure in css-transforms-1_dev/html/transform-abspos-002.htm and css-transforms-1_dev/html/transform-abspos-007.htm

### ISSUE THREAD

**Issue by jdm** [servo/servo#11561]
```
  ▶ FAIL [expected PASS] /css-transforms-1_dev/html/transform-abspos-002.htm
  └   → /css-transforms-1_dev/html/transform-abspos-002.htm 71f0313eedfbfcce0b0fcc5ae55f34b1daa3b8d8
/css-transforms-1_dev/html/reference/transform-abspos-ref.htm 78d197606924062e8dd2a773c977afcecf8940f8
Testing 71f0313eedfbfcce0b0fcc5ae55f34b1daa3b8d8 == 78d197606924062e8dd2a773c977afcecf8940f8
```

Non-reference:
<img width="301" alt="screen shot 2016-06-02 at 2 31 00 pm" src="https://cloud.githubusercontent.com/assets/27658/15756300/a6f49f40-28ce-11e6-9c7f-d026eaa418e7.png">
Reference:
<img width="322" alt="screen shot 2016-06-02 at 2 31 21 pm" src="https://cloud.githubusercontent.com/assets/27658/15756310/b0fb881e-28ce-11e6-874e-402d279404d4.png">

**Comment by jdm** [comment]
The new intermittent failures were caused by #11035.

**Comment by notriddle** [comment]
I haven't been able to reproduce this failure since #12543 landed (ran Servo in chaos mode for about 30 runs, and while I actually have managed to hit a race condition, it ended in a Spidermonkey crash, not an incorrect reftest).

Running it with just --repeat 100 doesn't fail at all.

**Comment by nox** [comment]
Disabled in https://github.com/servo/servo/pull/12942.

**Comment by jdm** [comment]
Test files don't exist any more.
