### ISSUE TITLE
Remove references to DOMSettableTokenList

### ISSUE THREAD

**Issue by nox** [servo/servo#11578]
This interface doesn't exist anymore and was removed from the DOM spec.

Files:
* components/script/dom/webidls/HTMLAnchorElement.webidl
* components/script/dom/webidls/HTMLAreaElement.webidl
* components/script/dom/webidls/HTMLElement.webidl
* components/script/dom/webidls/HTMLIFrameElement.webidl
* components/script/dom/webidls/HTMLLinkElement.webidl
* components/script/dom/webidls/HTMLOutputElement.webidl
* components/script/dom/webidls/HTMLTableCellElement.webidl
* tests/wpt/metadata/dom/interface-objects.html.ini
* tests/wpt/metadata/dom/interfaces.html.ini
* tests/wpt/web-platform-tests/dom/historical.htm

**Comment by nox** [comment]
This entails looking at the definitions of the WebIDL interfaces in the various specs and updating them to not reference `DOMSettableTokenList` anymore.

**Comment by kevgs** [comment]
I'll take this one.

**Comment by nox** [comment]
Blocks #2185.

**Comment by timvandermeij** [comment]
Fixed by #11606?

**Comment by nox** [comment]
Yes.
