### ISSUE TITLE
Properly implement options in EventListener methods

### ISSUE THREAD

**Issue by nox** [servo/servo#11581]
According to [the spec](https://dom.spec.whatwg.org/#interface-eventtarget), the methods `addEventListener` and `removeEventListener` shouldn't take just a boolean, but also should accept some specific dictionaries.

Files:
* components/script/dom/eventtarget.rs
* components/script/dom/webidls/EventTarget.webidl

**Comment by GuillaumeGomez** [comment]
I take it.

**Comment by KiChjang** [comment]
This is a duplicate of #9785, and last I heard, there wasn't consensus on whether or not this is a good idea. cc @Ms2ger
