### ISSUE TITLE
Fix the type of HTMLIFrameElement.sandbox

### ISSUE THREAD

**Issue by nox** [servo/servo#11598]
It should be a `DOMTokenList` and not a `DOMString` according to [the spec](https://html.spec.whatwg.org/multipage/embedded-content.html#htmliframeelement).

```webidl
[SameObject, PutForwards=value] readonly attribute DOMTokenList sandbox;
```

In a first commit, the field `sandbox` on `HTMLIFrameElement` should be renamed to `sandbox_allowance`.

In a second commit, a new field `sandbox` of type `MutNullableHeap<JS<DOMTokenList>>` should be added and `HTMLIFrameElement::Sandbox` should be changed in something similar to `Element::ClassList`.

Files:
* components/script/dom/htmliframeelement.rs
* components/script/dom/webidls/HTMLIFrameElement.webidl
* tests/wpt/metadata/dom/lists/DOMTokenList-coverage-for-attributes.html.ini
* tests/wpt/web-platform-tests/dom/lists/DOMTokenList-coverage-for-attributes.html

**Comment by nox** [comment]
Blocks #2185.

**Comment by canaltinova** [comment]
I would like to work on this.

**Comment by KiChjang** [comment]
Sure thing!
