### ISSUE TITLE
Do not use u8 in HTMLIFrameElement::sandbox

### ISSUE THREAD

**Issue by nox** [servo/servo#11599]
The field `sandbox` of `HTMLIFrameElement` should be changed to `Cell<Option<SandboxAllowance>>`.

**Comment by Coder206** [comment]
@nox I am on this one.

**Comment by nox** [comment]
Ok.

**Comment by Coder206** [comment]
@nox I am going to be a little busy this month and the beginning of the next, I will do my best to get this issue solved between all the other things I have going on. Just to confirm, the issue is at this file (at line 66): https://github.com/servo/servo/blob/master/components/script/dom/htmliframeelement.rs

**Comment by nox** [comment]
Yes exactly!

**Comment by Coder206** [comment]
@nox Please see this fix: #11765

It is a combination of your issue and @asajeffrey

**Comment by nox** [comment]
Please do 2 separate PRs.

**Comment by Coder206** [comment]
@nox Ok, I had trouble getting GitHub Desktop to do that, it just wanted to add to the last PR...

**Comment by nox** [comment]
Just make a new branch with only the commit for that fix and make a PR out of it.

**Comment by Coder206** [comment]
@nox Ok perfect, will do momentarily

**Comment by Coder206** [comment]
@nox I just re cloned the repo as there were many errors and two PRs to mess with, I am just compiling to make sure it is running error free on my end, then I am going to PR the fix for your issue.

**Comment by Coder206** [comment]
@nox I am very sorry for saying I was going to remake a PR "momentarily" and now here we are 10 hours later. There were a few unexpected events in my day. It is my goal to have it done for this weekend, hopefully tonight.

**Comment by Coder206** [comment]
@nox I just made the change you requested and I am getting errors on the same file, where you expecting some errors?

**Comment by Coder206** [comment]
@nox You mean the sandbox_allowance field (https://github.com/servo/servo/blob/master/components/script/dom/htmliframeelement.rs#L70)

**Comment by jdm** [comment]
Yes.
