### ISSUE TITLE
Properly implement the getElementsByTagName method on Document and Element

### ISSUE THREAD

**Issue by nox** [servo/servo#11596]
These two methods don't pass the tests that use non-HTML elements.

See the two tests "Element in non-HTML namespace, prefix, uppercase name" and "Element in non-HTML namespace, prefix, lowercase name".

We should think about how to implement efficiently the step 2 of [the spec](https://dom.spec.whatwg.org/#concept-getelementsbytagname).

See methods `Document::GetElementsByTagName`, `Element::GetElementsByTagName`, `HTMLCollection::by_tag_name` and `HTMLCollection::by_atomic_tag_name`.

These two last methods should be documented and probably renamed to something a bit more descriptive.

Files:
- components/script/dom/document.rs
- components/script/dom/element.rs
- components/script/dom/htmlcollection.rs
- tests/wpt/metadata/dom/nodes/Document-getElementsByTagName.html.ini
- tests/wpt/metadata/dom/nodes/Element-getElementsByTagName.html.ini
- tests/wpt/web-platform-tests/dom/nodes/Document-Element-getElementsByTagName.js
- tests/wpt/web-platform-tests/dom/nodes/Document-getElementsByTagName.html
- tests/wpt/web-platform-tests/dom/nodes/Element-getElementsByTagName.html

**Comment by nox** [comment]
The tests in tests/wpt/web-platform-tests/dom/nodes/case.html seem also related.

**Comment by nox** [comment]
Blocks #2185.

**Comment by kevgs** [comment]
I'll take this one.

**Comment by KiChjang** [comment]
Certainly! Ask questions here or on `#servo` at `irc.mozilla.org` if you're stuck.

**Comment by kevgs** [comment]
I have a question. As I understand this spec https://dom.spec.whatwg.org/#concept-getelementsbytagname this assertion is incorrect because element has prefix https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/dom/nodes/Document-Element-getElementsByTagName.js#L165

Am I right?

**Comment by kevgs** [comment]
Also, what do you mean by 'implement efficiently', efficiently means performance?

**Comment by nox** [comment]
> Also, what do you mean by 'implement efficiently', efficiently means performance?
Yeah, I mean performance-wise.

I'll take a look for your other question.

**Comment by nox** [comment]
@kevgs You are right, spec is unclear and Safari and Firefox disagree with each other.

**Comment by kevgs** [comment]
Why it's unclear? Spec requires comparing qualified names. And qualified name 'is its local name if its namespace prefix is null, and its namespace prefix, followed by ":", followed by its local name, otherwise'.

**Comment by kevgs** [comment]
Current code ignores namespace prefix. I think we should take it into account.

**Comment by nox** [comment]
It's unclear because there is a split between UAs that follow the spec, and UAs that don't. This usually mean that the spec is not clear and should be changed.

**Comment by kevgs** [comment]
What is UA? :)

And should I change the code to check for namespace prefix too? And fix tests.

**Comment by nox** [comment]
Sorry. :) A UA is a User Agent. Firefox, Chrome, Safari... You shouldn't do anything until the spec makes it clear which behaviour we should follow. I will report our findings on whatwg/dom soon.

**Comment by kevgs** [comment]
So, there is nothing to do with this issue until the spec got fixed?

**Comment by nox** [comment]
@kevgs After asking WHATWG, the spec is correct and the test is wrong. Feel free to fix the test then!

**Comment by KiChjang** [comment]
Last attempt at #11705.

**Comment by jdm** [comment]
Most recent attempt in #12844.

**Comment by mskrzypkows** [comment]
I can try this task if it's not urgent :-)

**Comment by nox** [comment]
It isn't, feel free!

**Comment by mskrzypkows** [comment]
What is a difference between `HTMLCollection::by_tag_name` and `HTMLCollection::by_qual_tag_name`? Maybe we should modify the second method?
