### ISSUE TITLE
Throw when accessing IDL members on arbitrary objects with platform prototypes

### ISSUE THREAD

**Issue by nox** [servo/servo#11600]
See the test tests/wpt/web-platform-tests/dom/collections/HTMLCollection-as-proto-length-get-throws.html.

We probably don't implement the various "if O is not a platform object that implements interface I, throw a TypeError" steps that [the WebIDL spec](http://heycam.github.io/webidl/#es-interfaces) defines.

**Comment by nox** [comment]
Blocks #2185.

**Comment by Ms2ger** [comment]
This was fixed for Gecko in <https://bugzilla.mozilla.org/show_bug.cgi?id=785941>; the bug in Servo is probably similar.
