### ISSUE TITLE
Rename SharedMouseAndKeyboardEventInit to EventModifierInit

### ISSUE THREAD

**Issue by nox** [servo/servo#11611]
[The spec](https://w3c.github.io/uievents/#event-modifier-initializers) says that `KeyboardEventInit` and `MouseEventInit` should both inherit from `EventModifierInit`, not `SharedMouseAndKeyboardEventInit`.

The file components/script/dom/webidls/SharedMouseAndKeyboardEventInit.webidl should be renamed to components/script/dom/webidls/EventModifierInit.webidl and all references to `SharedMouseAndKeyboardEventInit` changed to `EventModifierInit`, in code and in the test.

Files:
* components/script/dom/webidls/KeyboardEvent.webidl
* components/script/dom/webidls/MouseEvent.webidl
* components/script/dom/webidls/SharedMouseAndKeyboardEventInit.webidl
* tests/wpt/web-platform-tests/html/dom/interfaces.html

**Comment by shuky19** [comment]
On it

**Comment by jdm** [comment]
@shuky19 Have you made any progress? Do you have any questions?

**Comment by zeusintuivo** [comment]
I would like to give this a shot with progress has been made yet?

**Comment by jdm** [comment]
@zeusintuivo Go for it!

**Comment by zeusintuivo** [comment]
I going for it

**Comment by zeusintuivo** [comment]
working on pull request now

**Comment by zeusintuivo** [comment]
I have made a feature fix for it. Waiting for Master to be working again to make PR:
https://github.com/zeusintuivo/servo/tree/feature/11611

**Comment by zeusintuivo** [comment]
Master is not working...can not build. I am following IRC channel #servo
