### ISSUE TITLE
Implement URL.domainToUnicode

### ISSUE THREAD

**Issue by nox** [servo/servo#11629]
The implementation of [URL.domainToUnicode](https://url.spec.whatwg.org/#dom-url-domaintounicode) can just use [url::quirks::domain_to_unicode](http://servo.github.io/rust-url/url/quirks/fn.domain_to_unicode.html).

The operation needs to be uncommented in components/script/dom/webidls/URL.webidl and a new static method `DomainToUnicode` needs to be implemented in components/script/dom/url.rs.

The test expectations also need to be changed.

```
./mach test-wpt --no-pause --log-raw raw.log /url/interfaces.html
./mach update-wpt --no-patch raw.log
```

Files:
* components/script/dom/url.rs
* components/script/dom/webidls/URL.webidl
* tests/wpt/metadata/url/interfaces.html.ini

**Comment by nox** [comment]
@SimonSapin Do we test this in rust-url?
@Ms2ger @jdm Do we want additional tests in WPT? Can't see one apart from the usual interfaces.html test.

**Comment by achals** [comment]
I'll work on this if no one else already is.

**Comment by KiChjang** [comment]
You got it!
