### ISSUE TITLE
Implement Element.insertAdjacentHTML

### ISSUE THREAD

**Issue by nox** [servo/servo#11622]
See [the spec](https://w3c.github.io/DOM-Parsing/#dom-element-insertadjacenthtml).

In a first commit, extract the matching of `where_` from `Element::insert_adjacent` and introduce a new enum `AdjacentPosition`. This enum should then be passed instead of `where_` to `Element::insert_adjacent`. This requires updating its two callers `InsertAdjacentElement` and `InsertAdjacentText`.

```rust
enum AdjacentPosition {
    BeforeBegin,
    AfterEnd,
    AfterBegin,
    BeforeEnd
}

impl AdjacentPosition {
    pub fn parse(position: &str) -> Fallible<AdjacentPosition> { ... }
}
```

In a second commit, use `AdjacentPosition` and `Element::insert_adjacent` to implement `Element::InsertAdjacentHTML` correctly.

```webidl
partial interface Element {
    ...
    [Throws]
    void insertAdjacentHTML(DOMString position, DOMString text);
}
```

```rust
impl ElementMethods for Element {
    ...
    fn InsertAdjacentHTML(DOMString position, DOMString text) -> ErrorResult { ... }
}
```

Files:
* components/script/dom/element.rs
* components/script/dom/webidls/Element.webidl
* tests/wpt/metadata/domparsing/insert-adjacent.html.ini
* tests/wpt/metadata/domparsing/insert_adjacent_html.html.ini
* tests/wpt/web-platform-tests/domparsing/insert-adjacent.html
* tests/wpt/web-platform-tests/domparsing/insert_adjacent_html.html

**Comment by nox** [comment]
Just noticed that `Element::insert_adjacent` also doesn't do a ASCII case-insensitive match, that is wrong and whoever implements this should fix that bug while at it.

**Comment by GuillaumeGomez** [comment]
I take it.
