### ISSUE TITLE
Use the document base URL when setting the url of an HTMLAnchorElement

### ISSUE THREAD

**Issue by nox** [servo/servo#11628]
In `HTMLAnchorElement::set_url`, the document's base URL (`document.base_url()`) should be used instead of the document's URL (`document.url()`).

The code should be fixed, and the expectations updated:

```
./mach test-wpt --no-pause --log-raw raw.log /url/a-element.html
./mach update-wpt --no-patch raw.log
```

Files:
* components/script/dom/htmlanchorelement.rs
* tests/wpt/metadata/url/a-element.html.ini

**Comment by awestroke** [comment]
I'd like to do this

**Comment by jdm** [comment]
@awestroke Please do! Ask questions about anything that's unclear.
