### ISSUE TITLE
Android runtime error

### ISSUE THREAD

**Issue by dati91** [servo/servo#11633]
The [current](https://github.com/servo/servo/commit/1bc94c132e6820293c2178bf95991518b1e8a677) android release is failing with the following error:
`D/RustAndroidGlueStdouterr(18547): thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: MissingHomeVariable', ../src/libcore/result.rs:785`

**Comment by dati91** [comment]
CC @larsbergstrom

**Comment by dati91** [comment]
[This](https://github.com/whitequark/rust-xdg/blob/master/src/xdg.rs#L239) error seems to be related to this issue.

**Comment by dati91** [comment]
https://github.com/servo/servo/blob/master/components/util/prefs.rs#L183
I think this call caused the error on android.
If i replace it with `let mut path = resources_dir_path();` it starts normally.

**Comment by jdm** [comment]
Yes, it's the xdg::BaseDirectories::with_profile being unwrapped in default_config_dir that's triggering the error you see. You could avoid it by setting $HOME to something, I assume.

**Comment by mbrubeck** [comment]
Probably we should have Android-specific implement implementations of the functions in the `basedir` module, since Android does not use XDG:

https://github.com/servo/servo/blob/master/components/util/basedir.rs
