### ISSUE TITLE
Rendering issues on resize

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#11647]
This only happens with browserhtml when resizing quickly.

<img width="1173" alt="screen shot 2016-06-06 at 9 00 45 pm" src="https://cloud.githubusercontent.com/assets/9086315/15844733/e25b2c44-2c29-11e6-97c0-51cdf665d6bc.png">

This may only affect OS X, I don't have a linux installation so I cannot test.

**Comment by metajack** [comment]
That's one for the scrap book! :)

**Comment by notriddle** [comment]
[Not able to reproduce on Linux.](https://drive.google.com/open?id=0B1b9bjDyA5tmT1RxNEd2NHV6U2M)

**Comment by ConnorGBrewster** [comment]
@notriddle hmm looks like it is still partly there in that video, it just corrects itself a bit faster. Are you running in release?

**Comment by notriddle** [comment]
If you watch the video, the title bar is reacting the same way as the window is; slower, if anything.

**Comment by ConnorGBrewster** [comment]
Also I have noticed that the window does not re-render during resize until I either move my mouse or let go of my mouse.

**Comment by cbrewster** [comment]
I can no longer reproduce this.
