### ISSUE TITLE
[hittest] Link hitboxes are not updated after scrolling on duckduckgo

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11648]
`./mach run -d -w https://duckduckgo.com/\?q\=rust+langauge`
Scroll down and hover over links. The link rectangles are not updated after the scroll.
This happens both inside and outside of browserhtml.
This only happens with webrender.

**Comment by paulrouget** [comment]
Could is be a regression due to https://github.com/servo/servo/pull/11537 ?

**Comment by pcwalton** [comment]
Minimal test case:

    <!DOCTYPE html>
    <html style="overflow: scroll"><body style="padding-top: 1200px"><a href="http://example.com">Mouse over me</a></body></html>
