### ISSUE TITLE
Performance of twitter login page is abysmal

### ISSUE THREAD

**Issue by jdm** [servo/servo#11659]
Trying to type my username into the input box is a multi-second affair, with the display not updating for long periods of time. A profile trace shows 2.3 seconds for a "Painting" operation, with "PaintingPerTitle" operations taking >1s.

`./mach run https://twitter.com/login`

http://www.joshmatthews.net/twitter-login-trace.html

**Comment by metajack** [comment]
cc @pcwalton 

With those kind of timings, this may be diagnosable with Instruments.app.

**Comment by jdm** [comment]
Instruments reports 16.7% under PaintContext::draw_box_shadow (for 6 separate threads). Of that, 15.8% under PaintContext::blur_if_necessary, which ends up spending 12.2% under mozilla::gfx::AlphaBoxBlur::Blur, which is entirely spent in mozilla::gfx::AlphaBoxBlur::BoxBlur_SSE2.

**Comment by jdm** [comment]
I can't test with webrender due to #11658.

**Comment by pcwalton** [comment]
I don't think it would be a good use of time to fix the non-WR path. Let's fix the WR crash.

**Comment by nox** [comment]
This doesn't seem to happen anymore.
