### ISSUE TITLE
Do not fire a blur event when calling .focus() on a focused element

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11651]
```html
<input></input>
<script>
  var input = document.querySelector("input");
  input.addEventListener("blur", e => console.log("blur"));
  input.addEventListener("focus", e => console.log("focus"));
  setTimeout(() => input.focus(), 1000);
  setTimeout(() => input.focus(), 2000);
</script>
```

Output:

```
focus
blur
focus
```

**Comment by nox** [comment]
@paulrouget Yes, it seems like it's all that is needed. Marking as E-Easy.

**Comment by davideGiovannini** [comment]
I would like to work on this issue,

**Comment by jdm** [comment]
@davideGiovannini Please do!

**Comment by davideGiovannini** [comment]
I added the check in htmlelement.rs
```rust
    fn Focus(&self) {
        // TODO: Mark the element as locked for focus and run the focusing steps.
        // https://html.spec.whatwg.org/multipage/#focusing-steps
        if self.upcast::<Element>().focus_state() {
            return;
        }
        let document = document_from_node(self);
        document.begin_focus_transaction();
        document.request_focus(self.upcast());
        document.commit_focus_transaction(FocusType::Element);
    }
```
and now when I start servo with a page containing the snippet provided by @paulrouget  the output is `just:
```
focus
```
but if i click again on the input field when it is already focused I still get:
```
blur
focus
```
instead of getting nothing (since the item is already on focus).

It looks like in this case the focus is being activated from some other part of the code

**Comment by davideGiovannini** [comment]
I think I fixed it now.
I added the check:
```rust
    pub fn commit_focus_transaction(&self, focus_type: FocusType) {
        if self.focused != self.possibly_focused.get().r(){
         /* method body */
        }
    }
```
to the method `dom::document::Document.commit_focus_transaction`.

**Comment by nox** [comment]
What does it print with that check? Double `focus`?

**Comment by davideGiovannini** [comment]
- it prints `focus` at the start
- nothing when clicking the input field when it already has focus
- blur when the input field loses focus (clicking outside)
- focus when  the input field regains focus (clicking inside the input field) 

I'm currently running `./mach test-wpt` to see if everything is still ok
