### ISSUE TITLE
Cursor not correctly positioned in an empty input

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11653]
```html
<input></input>
```
looks like this:
<img width="157" alt="screen shot 2016-06-07 at 10 56 18" src="https://cloud.githubusercontent.com/assets/373579/15851776/8922eea8-2c9e-11e6-95bd-1e9702ac8467.png">

when
```html
<input value="x"></input>
```
looks like this:
<img width="182" alt="screen shot 2016-06-07 at 10 56 28" src="https://cloud.githubusercontent.com/assets/373579/15851785/94486d62-2c9e-11e6-87d6-a0a46452dca2.png">

**Comment by metajack** [comment]
I noticed this yesterday. It looks like it is translated down and we're seeing only the top of the bar.
