### ISSUE TITLE
box-shadow is not rendered correctly within position: fixed div

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11662]
```html
<!doctype html>
<html><body>
	<div style="width: 100%; position: fixed; top: 100px; left: 0;">
		<div style="background: lightgrey; height: 40px; box-shadow: 0 0 30px 30px darkblue;"></div>
	</div>
</body></html>
```
![sh](https://cloud.githubusercontent.com/assets/10187350/15865814/7debed3a-2cdc-11e6-9f6d-9c674c38a87a.png)

**Comment by splav** [comment]
I had some free time today and made an attempt find the bug. (I've committed only one trivial E-easy change for now). After two hours of investigation I've some minor results.
I would like to continue if it's not very urgent. The thing is the tiles have some margin for the blur being seamless and a) this margin should be filled by gradient and it's not (for seamless blur) b) the tile should be blitted without this margins. 
Now I'm trying to get the difference between fixed and absolute positioned divs cases.
If there are some docs for gfx component - it will be great. I'll be also glad for any guidance.
BTW for now servo is one of the best logically structured projects I've ever met :)

**Comment by jdm** [comment]
Thanks for looking into this! You're welcome to continue doing so; everyone else has their own things that they're working on. Perhaps @pcwalton has some ideas about the margin issue.

**Comment by jdm** [comment]
Note, the original screenshot is taken without webrender enabled. Running Servo with `-w` shows this:
<img width="801" alt="screen shot 2016-06-21 at 5 38 50 pm" src="https://cloud.githubusercontent.com/assets/27658/16247297/179d5978-37d7-11e6-98d6-c4ae9c7b3552.png">

**Comment by splav** [comment]
I think found the error in the create_draw_target_for_blur_if_necessary function in https://github.com/servo/servo/blob/master/components/gfx/paint_context.rs#L1571
```
        let tile_box_bounds =
            geometry::f32_rect_to_au_rect(self.page_rect.to_untyped()).intersection(box_bounds)
                                                         .unwrap_or(Rect::zero())
                                                         .inflate(side_inflation, side_inflation);
```
The thing is page_rect and the box_bounds are in different coordinate systems. In particular case the box_bounds are Rect(1040px×280px at (-120px,-120px))
and page_rects are Rect(512×280 at (0,0)) and Rect(512×280 at (512,0)) for two corresponding tiles.
The stacking_context overflow rect is Rect(1040px×280px at (-120px,-120px)).

In this case the following hard-coded transform
```
let tile_rect = self.page_rect.to_untyped().translate(&Point2D::new(-120f32, -120f32));
let tile_box_bounds =
            geometry::f32_rect_to_au_rect(tile_rect).intersection(box_bounds)
                                                         .unwrap_or(Rect::zero())
                                                         .inflate(side_inflation, side_inflation);
```
is enough. What should be the proper fix? May be the display list origin is relevant to this case - it is also (-120,-120)  (I also do not really understand why - may be it is the original error).

**Comment by jdm** [comment]
Do you know anything about the previous question, @mrobinson?

**Comment by splav** [comment]
@jdm, BTW with webrender from master rendering is correct.

**Comment by jdm** [comment]
Oh, if that's the case then it's not worth spending time trying to fix this. Does master look different than my last screenshot?

**Comment by splav** [comment]
./mach run -d -- -w ../box-shadow.html 
with master webrender and webrender_traits:
![screenshot_20160624_081324](https://cloud.githubusercontent.com/assets/182050/16328522/23e2ec04-39ec-11e6-911d-603d2a3bbb30.png)

Are you saying that CPU render will be deprecated soon and there is no need to fix it and learn how it works?

**Comment by jdm** [comment]
That is what @pcwalton has implied in similar issues.
