### ISSUE TITLE
box-shadow is not rendered correctly via webrender

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11661]
```
<!doctype html>
<html><body style="padding: 60px;">
    <div style="width: 300px; height: 40px; background: white; box-shadow: 0px 0px 20px 5px darkblue;"></div>
</body></html>
```

Without webrender:
![b1](https://cloud.githubusercontent.com/assets/10187350/15865184/1bf56db0-2cda-11e6-9a92-f9217869fbc2.png)
With webrender:
![b2](https://cloud.githubusercontent.com/assets/10187350/15865194/21f2b650-2cda-11e6-9a9c-d98f2fd7afb8.png)

**Comment by stshine** [comment]
Rendering is correct is current master.
