### ISSUE TITLE
Intermittent crash in /css21_dev/html4/border-conflict-element-001d.htm

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11663]
```
  ▶ CRASH [expected FAIL] /css21_dev/html4/border-conflict-element-001d.htm
  │ 
  └ Shutting down the Constellation after generating an output file or exit flag specified
```

Note: no stack trace. http://build.servo.org/builders/mac-rel-css/builds/1472

**Comment by jdm** [comment]
Nothing seen in several months, and it's not disabled. Closing.

**Comment by Manishearth** [comment]
Seen in https://github.com/servo/servo/pull/16596#issuecomment-296888868

**Comment by jdm** [comment]
This issue doesn't match any tests that we run anymore.
