### ISSUE TITLE
GetCookiesForUrl handler should use a read lock instead of a write lock

### ISSUE THREAD

**Issue by jdm** [servo/servo#11674]
We call `cookie_jar.write()` when we only need to read values from it, which could reduce performance if there are a bunch of HTTP requests occurring simultaneously.

Code: `components/net/resource_thread.rs` (`ResourceChannelManager::start`)
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/dom/documents/resource-metadata-management/document-cookie.html` (just a sanity check to make sure that reading cookies still works; it should continue to pass)

**Comment by sjmelia** [comment]
I'd like to pick this one up please

**Comment by jdm** [comment]
@sjmelia Go for it :) Please ask questions about anything that's unclear.

**Comment by sjmelia** [comment]
Great!

I think we need the write lock because each retrieved Cookie updates its last_access time when read, in order to fulfil RFC6265:

https://github.com/servo/servo/blob/c519739b7bcf408f2f671a89729aa30f39dd67a1/components/net/cookie_storage.rs#L101

Have I got the wrong end of the stick?

**Comment by jdm** [comment]
Oh, darn. You're totally right!
