### ISSUE TITLE
Use error-chain?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11678]
Our error reporting is currently a bit ad hoc, perhaps https://crates.io/crates/error-chain would help?

cc @brson

**Comment by asajeffrey** [comment]
One idea I had today is to buffer up any uses of warn! so that we can report them along with a panic backtrace as part of crash reporting.

**Comment by brson** [comment]
That would be sweet. One thing to note is that the advantages of error-chain come mostly when many crates are using it - that way they all know how to work together to propagate backtraces (or conceivably any other metadata you might want to carry along). I'd love for a bigger project to try it out, but it is basically a prototype, and I'd expect people to improve on the ideas it presents with experience.

This could be an opportunity for me to hack on servo again...

**Comment by asajeffrey** [comment]
Cool. I am vaguely thinking that we want to integrate logging with panicking, so we get a spectrum of how to deal with unexpected states:

* info! hey you might want to know about this.
* warn! this looks fishy, but I'm going to carry on and see if things work out.
* error! this is definitely an error, and should be reported.
* panic! this is definitely an error, and there's no way for the current thread to recover.

When an error! or panic! occurs, we should generate an error report (using the `mozbrowsererror` event @paulrouget), with the backtrace and perhaps the most recent N warn!s (for some value of N).

At the moment, we're rather liberal with panic! which gives us problems because script threads are shared among pipelines.

**Comment by asajeffrey** [comment]
A conversation with @brson in London: error-chain makes most sense when servo is being used as a library, e.g. in embedding scenarios. We can push this off for the moment, but we may want to come back later.
