### ISSUE TITLE
tidy warns about problems even in quoted strings inside attributes

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#11679]
In particular, the quoted string `"__TEXT,__info_plist"` causes tidy to fail complaining about the lack of a space before the comma. This impacts #11646.

**Comment by jdm** [comment]
I could swear that tidy has code to strip the contents out of strings. Is that inside of an attribute?

**Comment by pcwalton** [comment]
@jdm Yeah, it's inside an attribute. I'll update the title.
