### ISSUE TITLE
Implement CanvasRenderingContext2d.fillText

### ISSUE THREAD

**Issue by sole** [servo/servo#11681]
Spec: https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-filltext
Code: `components/script/dom/canvasrenderingcontext2d.rs`, `components/script/dom/weibidls/CanvasRenderingContext2D.webidl`, `components/canvas/canvas_paint_thread.rs`

(I hope I identified correctly the code files - followed the style in #5411)

**Comment by nox** [comment]
This was not actually implemented, we just print an error.

**Comment by Manishearth** [comment]
Relevant code from Gecko

 - [overall algorithm](https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/dom/canvas/CanvasRenderingContext2D.cpp#4240-4493)
 - [bidi processor](https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/dom/canvas/CanvasRenderingContext2D.cpp#3977,3978-4237) (goes through `nsBidiPresUtils::ProcessText`)

**Comment by jdm** [comment]
Relevant parts of Servo/Azure that may be useful:
* [convert_text_run_to_glyphs](https://github.com/servo/servo/blob/19495a76e49f2bfde67b80ff7d104d8594377738/components/layout/display_list/builder.rs#L2939-L2966)
* [DrawTarget::fill_glyphs](https://github.com/servo/rust-azure/blob/1ca68f302f5e914e2c63b0ec5b72af8f761f977d/src/azure_hl.rs#L828-L842)
* [AzCreateScaledFontForNativeFont(https://github.com/servo/rust-azure/blob/1ca68f302f5e914e2c63b0ec5b72af8f761f977d/src/azure-c.cpp#L551)
* some subset of [flush_clump_to_list](https://github.com/servo/servo/blob/19495a76e49f2bfde67b80ff7d104d8594377738/components/layout/text.rs#L148)

**Comment by jdm** [comment]
raqote has simple APIs for drawing text based on font-kit. Now that we have a working raqote-based canvas implementation, we should try enabling raqote's `text` cargo feature and using it: https://github.com/jrmuizel/raqote/blob/846374c6d48a39c8d080389ef43eb0ce215932ff/examples/capabilities.rs#L124-L142 .

**Comment by jdm** [comment]
Code: https://github.com/servo/servo/blob/dcdf910a259005bbdd993089d12f9f7eca9a26db/components/canvas/canvas_data.rs#L496-L501

**Comment by mikrut** [comment]
Hello @jdm! I may try to deal with this one, but I'm an amateur in both Servo and Rust and maybe will need someone more experienced to answer my questions. If that's a problem, I'll look for some simpler issue to start with.

Some of the questions are:
- Should such canvas context properties as **font**, **textAlign**, **textBaseline** and **direction** be implemented to resolve this issue? Or an implementation of **fillText** alone would be enough for now? (Using some default font and alignment, leaving the implementation of those properties for later.)
- It's almost clear what to do with _raqote_, but do you have any ideas on how to implement it for an _azure_ backend? I haven't found there anything to work with text except for maybe **fill_glyphs** function (but I'm not sure if that's a right starting point).

**Comment by jdm** [comment]
* Starting with a default font is fine; it will be easier to focus on supporting the content properties after the main text rendering works
* We don't care about the azure backend, so all it needs is the minimum set of changes to allow that backend to compile. We intend to remove that code soon.

**Comment by kaiakz** [comment]
@mikrut Hi! How about your progress? 
I would like to deal with this one as well. May I join you?  :smiley:

**Comment by mikrut** [comment]
So far I've implemented only very basic functionality: https://github.com/mikrut/servo/commits/fill_text
Looks like there are problems in raqote with text transform (rotations especially): https://github.com/jrmuizel/raqote/issues/111 However, text scaling works and if it's not rotated, it can be shrinked to fit the **max_width** parameter.
@kaiakz, of course, please join :slightly_smiling_face: However, I'm not sure how to organize our work on this issue. Maybe I'll try to fix that bug with rotations in raqote if I find out how to do it.

**Comment by kaiakz** [comment]
I finished a simple implementation of fill_text() by raqote too.  
![Screenshot_20200215_011452](https://user-images.githubusercontent.com/51747223/74553146-ad9fba80-4f91-11ea-9455-05c6a403fcd7.png)
 I am writing the [text-preparation-algorithm](https://html.spec.whatwg.org/multipage/canvas.html#text-preparation-algorithm), the replacement of whitespace is OK.
We need to improve those methods. But sadly I find that both font-kit and raqote doesn't have a good API documentation.

**Comment by kaiakz** [comment]
Does anyone know how to get [CanvasTextDrawingStyles](https://html.spec.whatwg.org/multipage/canvas.html#canvastextdrawingstyles)? 
@mikrut I prefer dealing with **max_width** parameter by `font_kit` side to by raqote with text transform. `font_kit` provides a lot of useful APIs.

**Comment by kaiakz** [comment]
> However, text scaling works and if it's not rotated, it can be shrinked to fit the **max_width** parameter.

It means that you can't scale the text and rotate the text at the same times, right?

**Comment by mikrut** [comment]
The thing is that you can't use raqote draw_text when there is a rotating transformation applied to the canvas: text is drawn incorrectly in that case (characters are rotated incorrectly). However, you still can use scaling.

**Comment by kaiakz** [comment]
@mikrut 
I have merged your code, you did a great job! I found that you implement the `measure_text` and use it to calculate the width.
In [raqote](https://github.com/jrmuizel/raqote/blob/58cf1a43c02555cfa74571a6c12ed896d39d2dc9/src/draw_target.rs#L203) `draw_text` will call `draw_glyphs`: it creates a canvas, then `font.rasterize_glyph` handles the canvas(included transform, i think maybe `font-kit` causes the problem), finally the `self.composite` draws it.

**Comment by mikrut** [comment]
Regarding `measure_text`: I think that it's better to move that method to raqote itself, as currently I had to copy-paste some lines from their `draw_text` in order to implement it. I think that on this weekend I'll finally have some time to deal with it.
I think you are right about those details, I just haven't looked that deep. Basic example which illustrates problems with rotation:
```
<canvas id="dest" height="100" width="100"></canvas>
<script>
var destCanvas = document.getElementById('dest');
var destCtx = destCanvas.getContext('2d');

destCtx.setTransform(1, 0.5, -0.5, 1, 30, 10);
destCtx.fillStyle="#0FF";
destCtx.fillText('Rotated', 10, 0);
</script>
```

**Comment by kaiakz** [comment]
@mikrut 
When I merged your code, I modified a few lines: 

1. use `CanvasData`'s `get_transform()` instead of `self.drawtarget.get_transform()`

2.


> Regarding `measure_text`: I think that it's better to move that method to raqote itself, as currently, I had to copy-paste some lines from their `draw_text` in order to implement it.

Maybe is not necessary to move, since `CanvasRenderingContext2d.measureText` is important. Use `font-kit`'s `font.metrics()` to retrieve various metrics.
Although I rewrote it as a closure function in `canvas_data.rs`.

**Comment by kaiakz** [comment]
I am sure that `raqote` has the wrong usage of the transformation matrix, so I sent a PR. The bug will be fixed after merged. 
Is there anything else II can do? Keep improving the methods (for example, make `ctx.font` works...) or just send the initial implementation as PR? What's your opinion?
![image](https://user-images.githubusercontent.com/51747223/74600379-c2806900-50cb-11ea-9341-46dd2f275fd9.png)

**Comment by mikrut** [comment]
You've done a great work, @kaiakz
> Is there anything else II can do?

I think we should ask @jdm about it. :slightly_smiling_face:

**Comment by jdm** [comment]
It would be good to get the font style properties working first, in my opinion. As for updating the raqote in servo, you can use [Cargo overrides](https://doc.rust-lang.org/nightly/cargo/reference/overriding-dependencies.html) for local unpublished changes, or run ` cargo update -p raqote` to update the git revision to a new published one.

**Comment by kaiakz** [comment]
@jdm 

> It would be good to get the font style properties working first, in my opinion.

I wonder if there is any place to store some info: when I set `ctx.font="40px Arial"`, how can I get the `font` property? I would be appreciate that you can give me any tips.

**Comment by jdm** [comment]
You will need to implement the `font` [getter and setter](https://github.com/servo/servo/blob/f63b404e0cbf30380c4043700861110d06e548bb/components/script/dom/webidls/CanvasRenderingContext2D.webidl#L213) by storing appropriate information in [CanvasContextState](https://github.com/servo/servo/blob/master/components/script/canvas_state.rs#L80).

Per [the specification](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-font), we should use the existing CSS font parsing code. In particular, we should follow the example of Firefox's code which uses the same Rust CSS implementation but is written in C++:
* https://searchfox.org/mozilla-central/source/dom/canvas/CanvasRenderingContext2D.cpp#3191-3258
* https://searchfox.org/mozilla-central/source/dom/canvas/CanvasRenderingContext2D.cpp#2243-2299
* https://searchfox.org/mozilla-central/rev/cc0f9906505d0ffa0d3a29a80142379e21cb5fb2/servo/ports/geckolib/glue.rs#4042-4072

**Comment by kaiakz** [comment]
@jdm Maybe the implementation of `font` is difficult for me, but I am still willing to try it. :smile:

**Comment by utsavoza** [comment]
> You will need to implement the `font` [getter and setter](https://github.com/servo/servo/blob/f63b404e0cbf30380c4043700861110d06e548bb/components/script/dom/webidls/CanvasRenderingContext2D.webidl#L213) by storing appropriate information in [CanvasContextState](https://github.com/servo/servo/blob/master/components/script/canvas_state.rs#L80).
> 
> Per [the specification](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-font), we should use the existing CSS font parsing code. In particular, we should follow the example of Firefox's code which uses the same Rust CSS implementation but is written in C++:
>

@jdm, is there a way for canvas paint thread to communicate with the font thread in order to load a particular font from its computed values (stored in canvas context state and probably canvas paint state) based on the value provided via the `font` setter? 

In comparison with the Firefox's implementation, I am not sure about the steps after getting the resolved font styles and how they correspond in Servo: https://searchfox.org/mozilla-central/source/dom/canvas/CanvasRenderingContext2D.cpp#3235-3273

**Comment by jdm** [comment]
We will either need to provide a font cache thread channel to the canvas paint thread when it's created, or we will need to obtain the font data we need from the layout thread after we have resolved the CSS value and then send a string to the canvas paint thread that represents the font that will be loaded using font-kit.

**Comment by utsavoza** [comment]
The second approach seems feasible but as per the [review comment in the previous PR](https://github.com/servo/servo/pull/25782#discussion_r383307992) I think we'd eventually want to load font from bytes obtained from a font template in the font cache thread and then pass the `font_kit::Font` instance to the canvas thread that we can use directly with raqote APIs. 

The problem, however, that I am facing is that I am currently storing resolved font style as `Option<ServoArc<ComputedValues>>` in the canvas context state. But I am not really sure if there's a way to load the font from the computed [`Font`](https://doc.servo.org/style/properties/style_structs/struct.Font.html) type [obtained from `ComputedValues`](https://doc.servo.org/style/properties/struct.ComputedValues.html#method.get_font) that we can eventually use to create a `font_kit::Font` instance.

**Comment by jdm** [comment]
A draft PR would be useful.

**Comment by utsavoza** [comment]
@jdm, I've raised a [draft PR](https://github.com/servo/servo/pull/26697) with the changes made so far. The code to parse and resolve the CSS value is mostly ported from [Firefox's implementation](https://github.com/servo/servo/issues/11681#issuecomment-586763530). It's the steps after getting the resolved values that are confusing in context of Servo as we are dealing with multiple `Font` types here.
