### ISSUE TITLE
Add a keyboard shortcut to reload the current page

### ISSUE THREAD

**Issue by jdm** [servo/servo#11686]
We would like Ctr+R/Apple+R to reload the current page (with a preference to disable this behaviour, too). We'll need to:

1. add a new `WindowEvent` variant
1. add a handler to `Window::handle_key` that enqueues the new event type (guarded by a preference check like the one for handling escape)
1. add a new `ConstellationMsg` variant
1. add a handler for the new window event in `Compositor::handle_window_message` that sends the new message to the constellation (see `on_navigation_window_event` for a good model)
1. add a new `ConstellationControlMsg` variant that includes a `PipelineId` argument
1. add a handler for the new constellation message in `Constellation::handle_request_from_compositor` that gets the root pipeline and sends the new message to its script channel (see `Constellation::handle_key_msg` for an example), passing the root pipeline id
1. add a handler for the new message sent from the constellation to `ScriptThread::handle_msg_from_constellation` that replicates the behaviour of `handle_reload` in `devtools.rs`

There's no way to write an automated test for this as far as I know, so testing manually will be our only option here.

Code: `components/compositing/windowing.rs`, `ports/glutin/window.rs`, `components/compositing/compositor.rs`, `components/constellation/constellation.rs`, `components/script/script_thread.rs`, `components/msg/constellation_msg.rs`, `components/script_traits/lib.rs`

**Comment by mrmiywj** [comment]
I'll pick this up.

**Comment by paulrouget** [comment]
We don't want this to affect browserhtml. So maybe we should rename the preference `shell.quit-on-escape.enabled` to `shell.builtin-key-shortcuts.enabled`, and allow quit on escape and reload on ctrl-r only if that pref is enabled.

https://github.com/servo/servo/blob/2cfef1391f53723aadb3f5225e3eaf3d155002d4/resources/prefs.json#L61

**Comment by jdm** [comment]
@mrmiywj Go for it :)

**Comment by mrmiywj** [comment]
Hmm, `WindowEvent::Refresh` does not matched the event here?
