### ISSUE TITLE
Handle pipeline lookup failure in webdriver

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11712]
At the moment, `script/webdriver_handlers.rs` uses `get_browsing_context` to lookup the current pipeline id, which panics on failure. This is not ideal, we should return a webdriver error instead.

Related: #11695 and https://www.w3.org/Bugs/Public/show_bug.cgi?id=29691

cc: @jgraham

**Comment by craftytrickster** [comment]
Is this assumption correct? 

You want to change the return type of `get_browsing_context` from                             

```rust
Root<BrowsingContext>
```

to
```rust
Root<Result<BrowsingContext, ExcitingNewErrorType>>
```

And then when `get_browsing_context` is consumed by the webdriver_handler, if an error occurs, we can return a `WebDriverJSError`?

**Comment by asajeffrey** [comment]
Something like that. Possibly `Result<Root<BrowsingContext>,ExcitingNewError>>` or `Option` rather than `Result`.

**Comment by craftytrickster** [comment]
If you want to return an Option on the below, it might be worth it to remove `get_browsing_context` completely, since the caller can easily just get an option by doing `context.find(pipeline_id)` by themselves.

If you want to keep the method, then I suggest returning a Result instead of an Option because it is something that really shouldn't be Optional, and if it is missing, then it is a clear error.

What do you think? 

```rust
pub fn get_browsing_context(context: &BrowsingContext,
                            pipeline_id: PipelineId)
                            -> Root<BrowsingContext> {
    context.find(pipeline_id).expect("ScriptThread: received an event \
            message for a layout channel that is not associated with this script thread.\
            This is a bug.")
}
```

**Comment by ConnorGBrewster** [comment]
I would think using `.find` would make more sense than keeping that function. Also I don't think a result type should be made when there aren't multiple errors that could occur. In this instance, either the `BrowsingContext` is found or it isn't so an `Option` would make more sense to me.

**Comment by craftytrickster** [comment]
I made some changes that might address this issue, let me know if anything is missing please.
