### ISSUE TITLE
Hover in servo-starters moves the text below it

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#11729]
Opening https://starters.servo.org/ in servo (webrender), and hovering on the red links in the open issues section causes an underline to appear (expected). This underline pushes the text below it down a few pixels (unexpected).

**Comment by canaltinova** [comment]
The reduced test case: 
```html
<html>
    <body>
        <a href="#" style="border-bottom: 20px solid red;">foo</a>
        <div>bar</div>
    </body>
</html>
```
I would like to work on this issue.
It should look like the left Firefox window but right now servo looks like right one:

![screenshot](https://cloud.githubusercontent.com/assets/466239/17771822/0ba50d24-654e-11e6-8750-dc720f261f8a.jpg)

**Comment by Manishearth** [comment]
Sure, go ahead!
