### ISSUE TITLE
ICE after modifying dependencies

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1173]
Add a `debug!` statement or some other code in a dependency library file, such as `src/support/opengles/rust-opengles/gl2.rs`.  Then run `make`.  `rustc` often produces this error:

~~~
task '<unnamed>' failed at 'lookup_item: id not found: 6111', /home/keegan/proj/servo/servo/src/compiler/rust/src/librustc/metadata/decoder.rs:92
error: internal compiler error: unexpected failure
This message reflects a bug in the Rust compiler. 
We would appreciate a bug report: https://github.com/mozilla/rust/wiki/HOWTO-submit-a-Rust-bug-report
note: the compiler hit an unexpected failure path. this is a bug
~~~

This seems to happen a lot more often after the 2013-10-31 Rust upgrade.

It's fixed by `make clean` but that eats up 2 or 3 minutes.

**Comment by jdm** [comment]
Dependencies are managed by Cargo now; I haven't seen this in some time.
