### ISSUE TITLE
Replace RefCell in SCRIPT_THREAD_ROOT with Cell

### ISSUE THREAD

**Issue by jdm** [servo/servo#11732]
Since the value inside the RefCell is copyable (it's a raw pointer inside of an Option wrapper), we can use Cell instead of a RefCell (which only needs to be used for values that do not implement the `Copy` trait).

Code: `components/script/script_thread.rs`

No need to run tests; if `./mach build` reports no errors then the changes are good.

**Comment by DarinM223** [comment]
Can I work on this? Thanks!

**Comment by ConnorGBrewster** [comment]
@DarinM223 go for it!
