### ISSUE TITLE
"Send is too large for port" on single-page HTML spec

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#11741]
```
ERROR:constellation::constellation: Panic: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Send is too large for port") }) }
```

**Comment by samlh** [comment]
See also https://github.com/servo/servo/issues/10390

**Comment by nox** [comment]
This still happens, but probably for different reasons than #10390 given there is no intensive usage of canvas in the HTML spec.

**Comment by nox** [comment]
For people wondering, the page we are talking about is https://html.spec.whatwg.org/.

**Comment by KiChjang** [comment]
Wait a minute, wasn't this due to ipc-channel having a limited message size?

**Comment by jdm** [comment]
Yes: https://github.com/servo/ipc-channel/issues/98

**Comment by jdm** [comment]
The ipc-channel issue was fixed.
