### ISSUE TITLE
Font issues in WebRender caused by pixel snapping

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#11751]
This test case:
```html
<div style="font: 13px 'Helvetica Neue'; padding: 0.5px;">illisible</div>
```

Renders like this on Linux with WebRender enabled (`./mach run -w`):

![illisible](https://cloud.githubusercontent.com/assets/5920/16079521/c72f86d2-32b8-11e6-8681-61835b3fed30.png)

This happens because the glyph positions are snapped to full pixels before rendering, which can change the letter spacing dramatically. @pcwalton mentioned that this could be fixed by instead rounding the fractional part of the glyph position to the nearest quarter pixel, and generating up to four rasterized glyphs per character: one for each possible quarter-pixel offset, with the fractional offset included as "padding" so the rasterized glyph can be positioned on a whole pixel boundary.

**Comment by kilobtye** [comment]
Related to #11355.
