### ISSUE TITLE
https://slashdot.org yields blank page

### ISSUE THREAD

**Issue by est31** [servo/servo#11753]
Running servo with commit 0cfae3a3e .

When visiting `https://slashdot.org`, the website starts building up, but then suddenly goes blank almost immediately before rendering completion.

The appearance is very similar to #11489 , dunno if its related.

It **only** is reproducible with release mode (-r flag on mach run), the debug mode doesn't show the bug.

I'm running mach run with the -w flag (webrenderer enabled).

**Comment by est31** [comment]
I'm living in germany and therefore I get a "please accept that we store cookies" dialog. The screen goes blank before that dialog is rendered completely, but the same dialog is used on sourceforge.net and on that page the dialog fails to render as well, but the page does not go blank.

**Comment by est31** [comment]
Also note that when the screen has went blank, servo can't be closed anymore; clicking the x button doesn't have any effect. Ctr-C works though.

**Comment by est31** [comment]
Hrmm close doesn't work on debug mode either, will file it as separate bug.

**Comment by ConnorGBrewster** [comment]
I also have this issue when running `./mach run -d https://google.com` when a popup comes up asking to switch the default search engine to Google. The whole page goes blank except the popup.

**Comment by est31** [comment]
Still reproducible with 5478e605aef93cc384b709688cc68e3ed854a68b . Any ways to debug it?

**Comment by est31** [comment]
Still reproducible with 369d5cf1242632efeb56278e18a5ea25a3c933a5.

**Comment by atouchet** [comment]
I tried testing this and the issue I ran into is that as soon as Slashdot loads it redirects to https://trc.taboola.com/slashdot/log/3/available?ri=... which results in a blank page.

**Comment by nox** [comment]
This doesn't seem to happen anymore.
