### ISSUE TITLE
Implement indexed access on select elements

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11763]
This also includes the `length` attribute.

It is probably simpler not to involve the `select.options` collection for now, and just implement the getter directly.

* Spec: <https://html.spec.whatwg.org/multipage/#dom-select-item>.
* Code: `components/script/dom/htmlselectelement.rs`, `components/script/dom/webidls/HTMLSelectElement.rs`.
* Test: `/html/semantics/forms/the-select-element/common-HTMLOptionsCollection.html`, `FileAPI/blob/Blob-constructor.html`.

**Comment by kevgs** [comment]
I'll take this one.

**Comment by ConnorGBrewster** [comment]
@kevgs it's all yours!

**Comment by kevgs** [comment]
I have some troubles. I guess I need to add one field to HTMLSelectElement struct. But I don't understand what type it should have.

**Comment by Ms2ger** [comment]
There should be no need to add any fields. You just need to uncomment the two lines in the WebIDL file and implement the Rust methods.

**Comment by KiChjang** [comment]
@kevgs Is this still being worked on?

**Comment by tomjakubowski** [comment]
I'm happy to take a look at this one.

**Comment by KiChjang** [comment]
@tomjakubowski Go for it!

**Comment by kevgs** [comment]
Sorry, right now I'm mostly afk and offline. I will be happy to work on something else when I'm be able to.

08.07.2016, 13:58, "Keith Yeung" <notifications@github.com>:
> @kevgs Is this still being worked on?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

--
Eugene

**Comment by KiChjang** [comment]
@tomjakubowski Are you still working on this?

**Comment by mskrzypkows** [comment]
Is the issue free to take? I can work on it.

**Comment by KiChjang** [comment]
@mskrzypkows It's all yours, since @tomjakubowski is unresponsive.

**Comment by mskrzypkows** [comment]
As I implement length attribute, I have one doubt: can we set value of length attribute? Shouldn't it be read only? It's because length is counted dynamically.
https://github.com/servo/servo/blob/master/components/script/dom/webidls/HTMLSelectElement.webidl#L18

**Comment by KiChjang** [comment]
@mskrzypkows See https://html.spec.whatwg.org/multipage/forms.html#dom-select-length.

**Comment by mskrzypkows** [comment]
OK, I see.

**Comment by mskrzypkows** [comment]
I've added draft. While removing nodes I need to handle fallible and None objects. How should I handle them: https://github.com/mskrzypkows/servo/commit/c3a03a850e287a570530ebbdf2af2943c0d5da36#diff-df123336552d1d03d6b506d9c8577d0eR196 ?

**Comment by mskrzypkows** [comment]
I need to add children nodes in SetLength method. Please give me some hint, how to create new node which I can add by parent's AppendChild method in htmlselectelement.rs.

**Comment by jdm** [comment]
`HTMLOptionElement::new` constructs a new HTMLOptionElement. You can call `parent.AppendChild(element.upcast())` to append it.

**Comment by mskrzypkows** [comment]
Thanks @jdm !
