### ISSUE TITLE
Improve network monitor integration

### ISSUE THREAD

**Issue by jdm** [servo/servo#11773]
https://github.com/servo/servo/pull/11593 made the network monitor appear when using the [Firefox developer tools](https://github.com/servo/servo/wiki/Devtools) with Servo. There are some known problems with the output that it shows, however:
* we do not report requests that are redirected (like visiting `https://reddit.com` and getting redirected to `https://www.reddit.com`)
* the response panel is empty
* we do not report timing data for "waiting" and "receiving"

I'm not sure how to solve the problem with the response panel yet, but the others will require modifying the code in `http_loader.rs` to send more notifications to the developer tools server. For the missing requests, we should be creating a new request ID each time and sending the information about the request and response sooner. For the missing timing data, we will need to time how long receiving the full HTTP response body takes and send a message to the developer tools that reports it.

Code: `components/net/http_loader.rs`, `components/devtools_traits/lib.rs`, `components/devtools/lib.rs`, `components/devtools/actors/network_event.rs`

cc @mrmiywj This might be interesting to you.

**Comment by mrmiywj** [comment]
Thanks!
It looks attractive to me.

**Comment by mrmiywj** [comment]
@jdm 
Recently I'm working on this issue. But I still have some questions.
You said that

> For the missing requests, we should be creating a new request ID each time and sending the information about the request and response sooner.

But actually, I found that [components/net/http_loader.rs L967](https://github.com/servo/servo/blob/master/components/net/http_loader.rs#L967) every time the browser sends out a request, it will also generate a (msg, response). What's the purpose of `creating a new request ID` you said? Just send them to the devtools is not enough?

**Comment by jdm** [comment]
@mrmiywj Note that we don't send the message to the devtools until https://github.com/servo/servo/blob/master/components/net/http_loader.rs#L1061 . In between there are several places where we restart the loop and never send the message. The purpose of creating a new request ID would be to ensure that each message the devtools receives for a separate request gets a separate ID.
