### ISSUE TITLE
mach interferes with CTRL+C running under debugger

### ISSUE THREAD

**Issue by nickolay** [servo/servo#11770]
1. Run `./mach run -d --debug`
2. (Optional) run the process with `r<ENTER>`
3. Hit CTRL+C

Actual results:
* lldb exits
* "mach interrupted by signal or user action. Stopping."
* the console stops echoing input until `reset` (OS X 10.9.5, iTerm2)

Expected: break in lldb.

There was a similar bug fixed in Mozilla's mach: https://bugzilla.mozilla.org/show_bug.cgi?id=996823

I think a similar fix needs to be applied here: https://github.com/servo/servo/blob/master/python/servo/command_base.py#L92

(I wonder if no-one uses OS X or if it's somehow specific to my setup?)

**Comment by jdm** [comment]
I encounter this problem all the time on OS X, I've just never done anything about it.
