### ISSUE TITLE
Integrate developer tools with fetch algorithm

### ISSUE THREAD

**Issue by jdm** [servo/servo#11774]
The code in `components/net/fetch/methods.rs` does not report any information about the requests and responses to the developer tools. Since XMLHttpRequest now relies on the fetch code instead of `components/net/http_loader.rs`, this means that they no longer appear in the developer tools output. The code in `methods.rs` should accept an optional sender to communicate with the devtools server like `http_loader.rs` does, and replicate the notifications that that code sends.

Code: `components/net/fetch/methods.rs`, `components/net/http_loader.rs`, `components/net/resource_thread.rs`

**Comment by avadacatavra** [comment]
@jdm can I work on this?

**Comment by jdm** [comment]
@avadacatavra Yes please!
