### ISSUE TITLE
Add a `./mach build-stable` sub-command

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#11806]
For Stylo (and probably other things in the future) we want to be able to build some crates on stable Rust. To avoid regressing this, we need to test it on CI. mach could bootstrap a stable Rust compiler the same way it does nightly.

While I work on removing or making optional the use of unstable features, I’d like some help with the bootstrap. That is:

* Add an empty crate in `ports/stable-rust`. (Later that crate will depend on the `style` crate and other things.)
* Add `ports/stable-rust/.gitignore` with contents `/target`
* Add a `rust-stable-version` file at the root of the repository with the contents `1.9.0`.
* In `python/servo`, add a `build-stable` sub-command to mach.
  * When bootstraping, it should look at `rust-stable-version` instead of `rust-nightly-date` and fetch corresponding tarballs from https://static.rust-lang.org/dist/ . (This probably doesn’t need compiler docs or cross-compilation target std, only host std and rustc.)
  * When running `cargo build`, it should set up the `PATH` and other environment variables to use the stable compiler instead of the nightly one. The `CARGO_TARGET_DIR` environment variable should be set to the path to the `ports/stable-rust/target` directory.
  * To check this this works correctly, temporarily add something like `#![feature(plugin)]` to the crate and see that the build fails with `error: #[feature] may not be used on the stable release channel`
* Have CI run this sub-command and reject PRs if it fails. (**FIXME**: decide which builder should run this, and fill in instructions. Does it involve changes to https://github.com/servo/saltfs ?)

**Comment by metajack** [comment]
Regarding which builder to use, we'll need one builder for each platform to run this. Those changes can be handled in the followup that adds build-stable to our buildbot setup in servo/saltfs.

**Comment by SimonSapin** [comment]
Given that all of the relevant code is already built and tested on multiple platforms with a nightly compiler, I only want to check that it builds with a stable compiler on one platform to make sure we don’t accidentally introduce more usage of unstable features. I don’t think it’s necessary to run `build-stable` on more than one platform.

**Comment by SimonSapin** [comment]
Edited the the original message to mention separate `CARGO_TARGET_DIR`, per Alex’s advice.

**Comment by gpoesia** [comment]
I'd like to take this (it would be my first PR in servo, so I'd need some guidance). I think I mostly get how to do it, except for the CI-related part, for which I have no idea. Is there any documentation on how CI is set up in servo? Thanks!

**Comment by Wafflespeanut** [comment]
Good to know! Feel free to ping us here or at "servo" channel at IRC if you've got any questions. And, the CI changes would be the final step of the PR which might probably require submitting another PR to https://github.com/servo/saltfs/ for utilizing the newly implemented command in the buildbot (@aneeshusa knows better about this).

**Comment by aneeshusa** [comment]
@gpoesia Yup, the CI changes will come last. This will boil down to adding one new line to our `steps.yml` file that lists all of the build commands. We're in the middle of testing a move of this file from the `saltfs` repo to this repo, so ping me when you're done and I'll let you know the right place to add it.

**Comment by SimonSapin** [comment]
It’s OK to submit multiple PRs separately for a related set of changes (as long as they each build and pass tests individually). In this case in particular the CI bits can be left for later.

**Comment by gpoesia** [comment]
Thanks! @aneeshusa I've just submitted the first PR (without the CI part). Should we do the CI integration now, or would it be better to wait for the move (in case it's not landed yet)?

**Comment by aneeshusa** [comment]
For now, let's land the CI integration into saltfs; it'll get moved later. In the `buildbot/master/files/config/steps.yml` file, you need to add a command that invokes the new `build-stable` command. I believe `linux-dev` is still the fastest builder, so add it to that builder; I think a debug build should be fine.

**Comment by SimonSapin** [comment]
@gpoesia How is it going? How can I help?

**Comment by gpoesia** [comment]
@SimonSapin Thanks for the review!
@aneeshusa Now that that one was accepted, the followup PR is here: https://github.com/servo/saltfs/pull/427
