### ISSUE TITLE
Animations/transitions of transform: rotate don't work

### ISSUE THREAD

**Issue by emilio** [servo/servo#11808]
They don't work on current trunk as far as I know, unlike translate and scale.

Minimal test case:

```html
<!doctype html>
<meta charset="utf-8">
<style>
  div {
    border-radius: 100px;
    width: 200px;
    height: 200px;
    line-height: 200px;
    margin: 100px;
    background-color: red;
    text-align: center;
    font-family: sans-serif;
    font-weight: bold;
    color: white;
    transform: rotate(90deg);
    transition: transform 3s linear;
  }

  div:hover {
    transform: rotate(180deg);
  }
</style>
<div>Hello Servo!</div>
```

Found while writing a minimal demo for animations. Haven't diagnosed it yet, but I'm filling this so we don't forget about it.

**Comment by notriddle** [comment]
[Probably because it's just not implemented](https://github.com/servo/servo/blob/master/components/style/animation.rs#L828), as shown by @glennw's TODO note.
