### ISSUE TITLE
Show buildbot result on Treeherder

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#11810]
By submitting buildbot result to Treeherder, we can see the status of the tests and infrastructure at a glance, and it will be easier to spot intermittent failures. 

But I don't know how long we'll be sticking to the buildbot setup, so probably not worth doing right now.

**Comment by SimonSapin** [comment]
https://github.com/servo/servo/issues/22325 tracks moving from Buildbot to Taskcluster, and we now have integration with Treeherder to show Taskcluster Tasks.
