### ISSUE TITLE
Use get_mut instead of get-remove-set in XHR send()

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#11811]
In https://github.com/servo/servo/blob/b9b289c4be50402facddd38c2ce2db2f1a05519c/components/script/dom/xmlhttprequest.rs#L637-654, we `.get()` a header, mutate it, `.remove()` it, and then `.set()` the new value. This is due to https://github.com/hyperium/hyper/issues/821, which is now fixed.

The code should be changed to mutate in place, by calling `.get_mut()` and mutating the value directly. This also requires a bump of our hyper version.

Tests in `tests/wpt/web-platform-tests/XMLHttpRequest` should continue to pass (`./mach test-wpt --release --include tests/wpt/web-platform-tests/XMLHttpRequest`, on a release build)

**Comment by Manishearth** [comment]
This bug is blocked on hyper getting a version bump.

**Comment by Manishearth** [comment]
Hyper has been published. Be sure to bump the hyper version using `./mach update-cargo -p hyper`

**Comment by DarinM223** [comment]
Can I pick this up? Thanks!

**Comment by KiChjang** [comment]
It's yours!
