### ISSUE TITLE
Sequential layout bug with (possibly) RTL direction

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#11818]
When we use the sequential layout traversal, there's an error with overconstrained_block.html and div_align.html.

Discovered while testing #11713

**Comment by avadacatavra** [comment]
It seems like there are two main issues:

1. In the sequential code, RTL isn't set properly
  * boxes 2 and 4 should both be RTL, but only 2 is
  * if you set all 4 blocks to be RTL, only 1 and 2 are
2. Neither parallel or sequential match the Firefox reference
  * But parallel mode with a single thread does (y1 screenshot)

[Screenshots](https://www.dropbox.com/sh/j9g80z6q2exjr8s/AABbuA6YlK5ytS0WjBVkSBRXa?dl=0)

**Comment by avadacatavra** [comment]
@mbrubeck

**Comment by pcwalton** [comment]
This could have something to do with dirty bits. Perhaps we are checking different dirty bits in parallel mode and sequential mode and incorrectly bailing out earlier in the latter?

**Comment by metajack** [comment]
Would disabling incremental layout make the problem go away in that case? That seems like an easy test.

**Comment by pcwalton** [comment]
Yes, it's worth a shot!

**Comment by avadacatavra** [comment]
Here's the test run in sequential mode with incremental layout disabled. Didn't go away :(

<img width="1224" alt="screenshot 2016-07-21 11 12 39" src="https://cloud.githubusercontent.com/assets/11877868/17017570/26d4c1be-4f34-11e6-8b92-4544c7f49679.png">

**Comment by notriddle** [comment]
When I force it to combine sequential restyle with parallel layout, I get both outputs depending on whether Satan manages to get into my computer before Hades blocks the entry off.

![screen_race_a](https://cloud.githubusercontent.com/assets/1593513/17273772/0d266760-5676-11e6-97ab-1f3858eeef3c.png)

![screen_race_b](https://cloud.githubusercontent.com/assets/1593513/17273775/1361c7dc-5676-11e6-8f3f-0e40da275c52.png)

Both of these screenshots were produced by running this command:

    ./mach run -d -y2 tests/wpt/mozilla/tests/css/overconstrained_block.html

And I used this patch:

```diff
diff --git a/components/layout_thread/lib.rs b/components/layout_thread/lib.rs
index 403f30a..b023187 100644
--- a/components/layout_thread/lib.rs
+++ b/components/layout_thread/lib.rs
@@ -1155,17 +1155,8 @@ impl LayoutThread {
                     self.profiler_metadata(),
                     self.time_profiler_chan.clone(),
                     || {
-                // Perform CSS selector matching and flow construction.
-                match self.parallel_traversal {
-                    None => {
-                        sequential::traverse_dom::<ServoLayoutNode, RecalcStyleAndConstructFlows>(
-                            node, &shared_layout_context);
-                    }
-                    Some(ref mut traversal) => {
-                        parallel::traverse_dom::<ServoLayoutNode, RecalcStyleAndConstructFlows>(
-                            node, &shared_layout_context, traversal);
-                    }
-                }
+                sequential::traverse_dom::<ServoLayoutNode, RecalcStyleAndConstructFlows>(
+                    node, &shared_layout_context);
             });
 
             // TODO(pcwalton): Measure energy usage of text shaping, perhaps?
```

I don't think there's anything interesting about the combination of parallel layout and sequential restyle, except for how it forces the race to go.
