### ISSUE TITLE
Update to euclid 0.7

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#11813]
We made a semver-breaking version bump of https://crates.io/crates/euclid for a change (requires `T: Clone` of serde impls) that is technically breaking but probably doesn’t affect any users. Therefore, updating likely only involves updating `Cargo.toml` files. I’ve made the changes in this repository at https://github.com/servo/servo/compare/euclidup, but to satisfy `./mach test-tidy` the dependencies also need to be updated:

* [x] https://github.com/servo/rust-azure/
* [x] https://github.com/servo/io-surface-rs
* [x] https://github.com/kaksmet/jpeg-decoder
* [x] https://github.com/servo/rust-layers
* [x] https://github.com/ecoal95/rust-offscreen-rendering-context/
* [x] https://github.com/servo/skia
* [ ] https://github.com/servo/webrender
* [ ] https://github.com/servo/webrender_traits

**Comment by Coder206** [comment]
@SimonSapin I don't see the euclid 0.7 dependency in the Cargo.toml file at https://github.com/servo/app_units

Does it need to be added?

**Comment by jdm** [comment]
https://github.com/servo/app_units/commit/e0252280dbd9b6c3c1053a299d0e6f126d6e39b0 removed it.

**Comment by Coder206** [comment]
@SimonSapin Are there any tests required before submitting code?

**Comment by jdm** [comment]
If it builds, that's good enough.

**Comment by Coder206** [comment]
@jdm Cool.

**Comment by SimonSapin** [comment]
Since the euclid dependency was removed from app_units, there is nothing to do in that repository for this issue.

**Comment by SimonSapin** [comment]
Or rather, the only thing to do is update `app_units` in Servo to pick up that removal.

**Comment by kaksmet** [comment]
`jpeg-decoder` 0.1.5 removed it's dependency on euclid.

**Comment by nox** [comment]
https://github.com/emilio/rust-offscreen-rendering-context/pull/58

**Comment by cflewis** [comment]
I think this can be closed, @nox seems to have got them.

**Comment by nox** [comment]
Yes.
