### ISSUE TITLE
Failure in building release version with debug symbols on

### ISSUE THREAD

**Issue by rzambre** [servo/servo#11828]
Platform: Mac OSX 10.11

After commenting out [lines 30 and 31](https://github.com/servo/servo/blob/master/components/servo/Cargo.toml#L30-31) in the Cargo.toml under components/servo, `./mach build -r` compiles all the way until layout_thread but results in this failure:

> Assertion failed: (std::all_of(Expr.begin(), Expr.end(), [](const DIExpression *E) { return E && E->isBitPiece(); }) && "conflicting locations for variable"), function addMMIEntry, file /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.h, line 137.

https://pastebin.mozilla.org/8879047

The release version with the debug symbols on was building successfully yesterday (June 21).  I'm not sure what to make of the error message. What could be causing this error?

**Comment by jdm** [comment]
When you say yesterday, were you required to download a new rustc version since then? This is an assertion in LLVM, which makes it a problem with rustc.

**Comment by jdm** [comment]
Oh, this could simply be an existing rustc bug that was exposed by #11804 I suppose.

**Comment by rzambre** [comment]
Yeah, I'm thinking this is an existing bug that got exposed by some recent commits. The successful build was on a fresh clone of Servo and rustc version hasn't changed since 6/14/16. Should I open an issue in rust?

**Comment by jdm** [comment]
Yes please!

**Comment by rzambre** [comment]
Here: rust-lang/rust#34434

cc @larsbergstrom

**Comment by rzambre** [comment]
Closing this issue since Servo release can be built with debug-symbols on.
