### ISSUE TITLE
DXR Clang build fails on /usr/bin/ld: cannot find -load

### ISSUE THREAD

**Issue by klibby** [servo/servo#11823]
Attempting to build servo on Ubuntu 14.04.3 LTS, to get a searchable index under DXR (dxr.mozilla.org), and it's bombing out (full log is available at https://jenkins-dxr.mozilla.org/job/servo/7/console):

14:35:46 /bin/bash ./libtool  --tag=CC   --mode=link clang -Xclang -load -Xclang /builds/dxr-build-env/dxr/dxr/plugins/clang/libclang-index-plugin.so -Xclang -add-plugin -Xclang dxr-index -Xclang -plugin-arg-dxr-index -Xclang /builds/dxr-build-env/src/servo/servo  -fPIC -O3   -o png-fix-itxt contrib/tools/png-fix-itxt.o  -lm -lz -lm 
14:35:46 libtool: link: clang -Xclang -Xclang /builds/dxr-build-env/dxr/dxr/plugins/clang/libclang-index-plugin.so -Xclang -add-plugin -Xclang dxr-index -Xclang -plugin-arg-dxr-index -Xclang /builds/dxr-build-env/src/servo/servo -fPIC -O3 -o png-fix-itxt contrib/tools/png-fix-itxt.o  -load -lz -lm
14:35:46 libtool: compile:  clang -Xclang -load -Xclang /builds/dxr-build-env/dxr/dxr/plugins/clang/libclang-index-plugin.so -Xclang -add-plugin -Xclang dxr-index -Xclang -plugin-arg-dxr-index -Xclang /builds/dxr-build-env/src/servo/servo -DHAVE_CONFIG_H -I. -I/builds/dxr-build-env/src/servo/servo/.cargo/git/checkouts/rust-png-f44ec0131d7a5ba6/master/png-sys/libpng-1.6.16 -fPIC -O3 -MT pngwutil.lo -MD -MP -MF .deps/pngwutil.Tpo -c /builds/dxr-build-env/src/servo/servo/.cargo/git/checkouts/rust-png-f44ec0131d7a5ba6/master/png-sys/libpng-1.6.16/pngwutil.c -o pngwutil.o >/dev/null 2>&1
14:35:46 make[1]: Leaving directory `/builds/dxr-build-env/src/servo/servo/target/release/build/png-sys-c0fc68e5ccc34308/out'
14:35:46 
14:35:46 --- stderr
14:35:46 clang: warning: argument unused during compilation: '-Xclang -Xclang'
14:35:46 clang: warning: argument unused during compilation: '-Xclang -add-plugin'
14:35:46 clang: warning: argument unused during compilation: '-Xclang dxr-index'
14:35:46 clang: warning: argument unused during compilation: '-Xclang -plugin-arg-dxr-index'
14:35:46 clang: warning: argument unused during compilation: '-Xclang /builds/dxr-build-env/src/servo/servo'
14:35:46 /usr/bin/ld: cannot find -load
14:35:46 clang: error: linker command failed with exit code 1 (use -v to see invocation)
14:35:46 make[1]: **\* [png-fix-itxt] Error 1
14:35:46 make[1]: **\* Waiting for unfinished jobs....
14:35:46 make: **\* [all] Error 2
14:35:46 thread '<main>' panicked at 'assertion failed: cmd.stdout(Stdio::inherit()).stderr(Stdio::inherit()).status().unwrap().success()', /builds/dxr-build-env/src/servo/servo/.cargo/git/checkouts/rust-png-f44ec0131d7a5ba6/master/png-sys/build.rs:59

I'm not sure if this is properly fixed on servo's side, or DXR's (/cc @erikrose) though.

**Comment by jdm** [comment]
@nrc does this mean anything to you?

**Comment by jdm** [comment]
This doesn't look like something that Servo controls, however.

**Comment by nrc** [comment]
Looks like it's on the Clang side rather than the Rust side. I never did get DXR to index Servo properly, although I didn't see this error (I managed to index the codebase, just couldn't get DXR to make sense of the index). That was quite a while ago though.

**Comment by edunham** [comment]
Closing as "almost certainly dxr's problem" and "probably went away or someone would have said something in the past year". If either of these assumptions is incorrect -- if there's an action you'd like a Servo infrastructure person to take on this issue -- please feel free to re-open.

**Comment by dylanmckay** [comment]
In case anybody else encounters this same bug.

I've encountered this exact same error whilst indexing LLVM trunk with DXR.

My `dxr.config` looks like this

```ini
[llvm-project_llvm]
source_folder = /code/llvm
build_command = mkdir -p build && cd build && cmake -G "Unix Makefiles" -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR ../ && make
```

Which means this really is likely DXR's fault somewhere.
