### ISSUE TITLE
Script compilation failed with no reason

### ISSUE THREAD

**Issue by GuillaumeGomez** [servo/servo#11829]
![screenshot from 2016-06-23 12-16-13](https://cloud.githubusercontent.com/assets/3050060/16299793/609294fc-393c-11e6-94d1-2c3d5c4cb31c.png)

cc @nox

**Comment by nox** [comment]
@alexcrichton Any idea what could trigger that?

**Comment by GuillaumeGomez** [comment]
![screenshot from 2016-06-23 14-49-41](https://cloud.githubusercontent.com/assets/3050060/16303589/bb3b1df6-3951-11e6-9874-9a27d4b7a1f7.png)

Another weird error.

**Comment by alexcrichton** [comment]
The first screenshot looks like it's missing the output of the `--verbose` run (a copy/paste should be fine as well as opposed to a screenshot). The second one looks like it may just be a standard ICE

**Comment by GuillaumeGomez** [comment]
Irestarted the first one with `--verbose` and it compiled fine.

**Comment by nox** [comment]
Closing this.
