### ISSUE TITLE
Build issue with xcode 8.0 command line tools

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#11846]
Linker errors: http://pastebin.com/BB0AHW3P

**Comment by jbg** [comment]
`CFLAGS=-stdlib=libstdc++ CXXFLAGS=-stdlib=libstdc++ LDFLAGS=-stdlib=libstdc++ ./mach build` worked for me.

**Comment by crazymykl** [comment]
@jbg's steps are not sufficient for me. (Also, 8.0 is no longer beta, so the issue title could use an update.)

**Comment by saneyuki** [comment]
(Of course, we need to face to this issue...)

if you cannot wait fix this, and you still have a old xcode (~7.3) in your machine's `/Library/Developer/CommandLineTools/`, you can avoid this with`xcode-select --switch /Library/Developer/CommandLineTools/`.

**Comment by cbrewster** [comment]
Building now works with Xcode 8
