### ISSUE TITLE
Implement referrer policy delivery via noreferrer link relation

### ISSUE THREAD

**Issue by rebstar6** [servo/servo#11862]
See https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery, https://html.spec.whatwg.org/multipage/semantics.html#link-type-noreferrer for details.

Reference #10311 for servo referrer policy implementation thus far. Note that new referrer policy tests may be required for this.

**Comment by jdm** [comment]
This will be very similar to the implementation of #11861.

**Comment by TheKK** [comment]
Hi, can I take this one?

**Comment by KiChjang** [comment]
Sure thing!

**Comment by jdm** [comment]
@TheKK We'll need to store an optional referrer policy field in the element types that support it, then allow use that value when creating PendingAsyncLoad values instead of the one from the document.

**Comment by TheKK** [comment]
Well, I got some some rough idea and questions after some research. Let me elaborate them below:

- I found that `Document::load_sync` and `Documen::prepare_load_async` pass itself into these two method. If I get it right, I should add at least `Option<ReferrerPolicy>` into their arguments, so we don't take referrer policy from `Document` directly. But this might affect others related issue. Is it okay to modify?

- about referrer policy delivery, how do I choose a `<a>`'s policy when the site has already set one in `<meta>`?

**Comment by jdm** [comment]
Modifying the arguments for load_async and prepare_load_sync should be fine. As for when the policy should apply, the spec implies that the policy set via a content attribute should override the one present in the document. I've filed https://github.com/whatwg/html/issues/1531 about making this explicit.

**Comment by TheKK** [comment]
I got some troubles with wpt. I modified `web-platform-tests/referrer-policy/spec.src.json` and did generate test for `<a>` with delivery method `rel-noreferrer`. But after I run these test I only got

```shell
$ ./mach test --release tests/wpt/web-platform-tests/referrer-policy/no-referrer-when-downgrade/rel-noreferrer 
Running tests in web-platform-tests

Unsupported test type wdspec for product servo
Ran 0 tests finished in 0.0 seconds.
  • 0 ran as expected. 0 tests skipped.

Tests completed in 3.11s
```

I'm sure the directory is not empty. Any hint?

**Comment by jdm** [comment]
@TheKK Why did you need to modify spec.src.json? As for the question about mozbrowseropenwindow, we can make any changes to it that we want.

**Comment by jdm** [comment]
Ah, looking at spec.src.json I see now. You probably need to run `./mach manifest-update` to ensure that `MANIFEST.json` contains the new tests.

**Comment by TheKK** [comment]
@jdm, thanks. those tests works now but all failed. Seems like `document.write` and `document.referrer` have not ready yet. Anyway, I'll figure out if I could validate my changes in current condition.

About the mozbrowseropenwindow, what do you mean "change"? Aren't those properties unalterable?

**Comment by jdm** [comment]
mozbrowseropenwindow is a Mozilla-specific event, and it's only used by browser.html, so we can make whatever changes we want to it in consultation with them.

As for the failing tests, document.write is indeed a missing feature that won't be implemented soon. document.referrer should be straightforward to implement; I'll file an issue for that.

**Comment by TheKK** [comment]
The activation behavior for `<area>` has not yet constructed. Is that okay to file and work on it myself?

**Comment by jdm** [comment]
I would prioritize that below the unfinished pieces of referrer-policy, personally.

**Comment by TheKK** [comment]
`<area>` is included in rel-noreferrer deliver method, so if its `follow_hyperlink()` is empty then we have nothing to do with the delivery implementation. Otherwise we could separate `<area>`'s implementation into the other issue and it won't block this one anymore.

What do you think?

**Comment by jdm** [comment]
Yeah, I would deal with `<area>`'s implementation elsewhere.

**Comment by TheKK** [comment]
Cool! Here's my progress so far: TheKK/servo@889d2c5a19c41af55dd67804ec2a2b6790d7c864. `<a>` and `<link>` should works fine. I'll deal with mozbrowseropenwindow and corresponding test tomorrow.

Only one question here, is that okay to call methods in `HTMLAnchorElementMethods` or `DOMTokenListMethods`?

**Comment by jdm** [comment]
Yep, using those methods is fine.

**Comment by TheKK** [comment]
I'm starting play with wpt tests and seems like it's quite a long way to go.

Also, I try to inject referrer information into `mozbrowseropenwindow` today and it's pretty straight. But I can't find which code catch this event and perform the rest of actions. My concern here is that referrer URL handling algorithm has already existed in `net/http_loader` and I'd like to reuse (if necessary) this logic.

Any idea?

**Comment by jdm** [comment]
The code that deals with the event is part of browser.html, which is in a separate repository under mozilla/.

**Comment by metajack** [comment]
Browser.html's home is under the [browserhtml org](https://github.com/browserhtml/browserhtml)

**Comment by TheKK** [comment]
@jdm I'm not sure about that. Since the fact that `tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowser_click_fires_openwindow.html` run without browser.html but the iframe still be changed by some one. Is there something I didn't catch?

**Comment by jdm** [comment]
The mozbrowser tests use the same APIs as browser.html.

**Comment by TheKK** [comment]
I think I need some advice. I'm trying to test HTMLAnchordElement by creating an `<a>` inside `<iframe>` then activate `<a>` (since anchor target is missing feature now). Here's part of them:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Referrer-Policy: Referrer Policy is set to 'no-referrer'</title>
  </head>
  <body>
    <script>
  var iframe = document.createElement("iframe");

  iframe.addEventListener('load', function() {
  var a = iframe.contentWindow.document.createElement('a');
  a.innerHTML = 'go';
  a.href = 'jdfkldfj';
  iframe.contentWindow.document.body.appendChild(a);
  });

  document.body.appendChild(iframe);
      </script>
    <div id="log"></div>
  </body>
</html>
```

The weird thing here is that the result is different between running `./mach run -r` and running `./mach test --release`. While running this as test it says iframe.contentWindow is null, but it's not when running directly.

Do you have any idea, or is there any better way to construct this test?

**Comment by jdm** [comment]
Odd, I think I would expect the reverse - running directly would yield a file:// URL, and I believe our files are considered cross-origin to each other, which running under the test harness should yield same-origin URLs.

**Comment by jdm** [comment]
I recommend loading an actual page where you don't need to manipulate the child's DOM.

**Comment by TheKK** [comment]
Some questions about test case:

- Do https related test cases always fail (timeout) currently?

- In `tests/wpt/mozilla/tests/mozilla/referrer-policy/spec.src.json`, since we only implement `meta-referrer` and `rel-noreferrer`, should I generate tests for other deliver method?

- About section **subresource_path** in `tests/wpt/mozilla/tests/mozilla/referrer-policy/spec.src.json`, shouldn't we use `/_mozilla/mozilla/referrer-policy/generic/subresource/document.py` as subresource instead? As I know the **/web-platform-test/** version use postMessage() which would cause testing failure.

```json
  "subresource_path": {
    "iframe-tag": "/referrer-policy/generic/subresource/document.py"
  }
```

**Comment by jdm** [comment]
* Yes, we don't support HTTPS in tests yet. 
* We generate tests for unimplemented methods because we can mark them as expected failures.
* Huh. Probably!
* We can make changes to the upstream tests; what are the changes you want to make?

**Comment by TheKK** [comment]
TheKK/servo@2d1259fd
About the changes I made, all of them are workaround to prevent using postMessage(). Most of changes are under`tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/commom.js`. What's your opinion push those to upstream?

**Comment by jdm** [comment]
Ah, I understand now. We should make those changes in our local copy of the testsuite and leave the upstream ones alone.
