### ISSUE TITLE
MutableHandle<PropertyDescriptor> misused by mutating fields of .get() copies.

### ISSUE THREAD

**Issue by eddyb** [servo/servo#11868]
[Example in `script::dom::browsingcontext`](https://github.com/servo/servo/blob/8dcb12a019885d8333f35f43e43d3f2e0c56573a/components/script/dom/browsingcontext.rs#L269).
This looks bad, and `CodegenRust.py` generates a bunch more, but I have no idea what impact it has.
Also not sure what other types this happens with, I stumbled onto it during an unrelated refactoring.

The only solution I can think of is implementing `{,Mutable}Handle::get` only for pointers and `Value`.
That is, assuming there is no need to copy the whole `PropertyDescriptor` structure out.

**Comment by jdm** [comment]
To elaborate - we could create a trait in https://github.com/servo/rust-mozjs/blob/master/src/rust.rs and implement that trait for `*mut T`. We could then add that trait to the bounds for [RootedGuard::get](https://github.com/servo/rust-mozjs/blob/3de4ff3d52361a47a17e3b4fcb02c779b99d93d4/src/rust.rs#L431-L433), [Handle::get](https://github.com/servo/rust-mozjs/blob/3de4ff3d52361a47a17e3b4fcb02c779b99d93d4/src/rust.rs#L475-L479), and [MutableHandle::get](https://github.com/servo/rust-mozjs/blob/3de4ff3d52361a47a17e3b4fcb02c779b99d93d4/src/rust.rs#L511-L515) and see what needs to be changed to keep Servo building.

**Comment by avadacatavra** [comment]
It looks like this causes an issue for xows, so if no one else takes it, I probably will
