### ISSUE TITLE
Implement referrer policy for WorkerGlobalScope

### ISSUE THREAD

**Issue by rebstar6** [servo/servo#11863]
See spec at https://w3c.github.io/webappsec-referrer-policy/. All servo referrer policy implementation thus far is just for documents. See #10311 for reference.

**Comment by jdm** [comment]
This requires storing a `ReferrerPolicy` value in `WorkerGlobalScope`, hooking it up to the HTTP header (#11860), and adding an API to `GlobalRef` that retrieves the global's policy from either the window (via the document) or the worker (via a new public method on `WorkerGlobalScope`).

**Comment by aravind-pg** [comment]
I'd like to take this on. Can you elaborate a bit on how the hooking up to the HTTP header would work? It's not obvious to me how that connection runs, looking at the places where `WorkerGlobalScope::new` is called. Also, is it sufficient simply to add that new API to `GlobalRef` -- does it not need to be called anywhere, or is that for later?

**Comment by jdm** [comment]
The header would be obtained from the result of `load_whole_resource` from the `Metadata` value it returns. We would also want to call the new API, yes - see `XMLHttpRequest::new_inherited` for a great place to start.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/12473#issuecomment-244749066 is the latest information about what's required for this task. Specifically, we don't have any tests that verify referrer policies for subresource requests initiated from inside workers.

**Comment by jdm** [comment]
I have written up the specifics about the desired tests at #14837.
