### ISSUE TITLE
Implement referrer policy delivery via referrer attribute

### ISSUE THREAD

**Issue by rebstar6** [servo/servo#11861]
See https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery-referrer-attribute for details

Reference #10311 for servo referrer policy implementation thus far.

**Comment by jdm** [comment]
This will be very similar to the implementation of #11862.

**Comment by TheKK** [comment]
I'd like to work on this one, Could you assign it to me :)

**Comment by jdm** [comment]
Please do!

**Comment by TheKK** [comment]
It's kind of shame, I found that my test for HTMLAnchorElement in #12493 was totally wrong. Before sending PR, should I open issue for it first?

**Comment by jdm** [comment]
No need for an issue if you've got a fix ready!

**Comment by nox** [comment]
@TheKK Are you still working on this?
