### ISSUE TITLE
Font rendering issue on button hover on app.getlaps.com

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#11874]
`./mach run -d -w https://app.getlaps.com`
Before hovering over `CREATE ACCOUNT`:
<img width="912" alt="screen shot 2016-06-26 at 2 21 37 pm" src="https://cloud.githubusercontent.com/assets/9086315/16364669/15d13098-3baa-11e6-9541-88d6b7f4705c.png"> 
Hovering over `CREATE ACCOUNT`:
<img width="912" alt="screen shot 2016-06-26 at 2 21 39 pm" src="https://cloud.githubusercontent.com/assets/9086315/16364671/18fe683a-3baa-11e6-894b-c7518fe65dee.png">

**Comment by nox** [comment]
The cert expired. Closing.
