### ISSUE TITLE
Underline color is not same as text color

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#11870]
![aborder](https://cloud.githubusercontent.com/assets/10187350/16362565/468154ea-3bb2-11e6-93b1-5bf09ffbc966.png)
```
<!doctype html>
<html><body>
	<style>
		a{
			font-size: 2em;
			color: red;
			text-decoration: underline;
		}
	</style>
	<a href="#">Servo</a>
</body></html>
```

**Comment by KiChjang** [comment]
I can look at this.

**Comment by gpoesia** [comment]
I took at look at it and simply removing the check in components/layout/display_list_builder.rs:build_display_list_for_text_fragment, "if shadow_blur_radius.is_some()", makes at least this test work (also with strikethrough and overline, which had the same issue). I couldn't see the reason for that code fragment not to always run. Is there any?

**Comment by KiChjang** [comment]
My initial thoughts were that this is caused by styling, not necessarily layout. The relevant style is `-servo-text-decorations-in-effect`, located in `components/style/properties/inherited_text.mako.rs`.
