### ISSUE TITLE
Implement the Headers API

### ISSUE THREAD

**Issue by jdm** [servo/servo#11897]
Specification: https://fetch.spec.whatwg.org/#headers-class
Documentation: http://doc.servo.org/servo/script/dom/index.html#adding-a-new-dom-interface

This is assigned to our RGSoC team, so please talk with me before starting to work on any part of it.

**Comment by jdm** [comment]
Blocks #11894.

**Comment by timvandermeij** [comment]
Fixed in #12634?

**Comment by jdm** [comment]
Almost, but it's still missing the iterable declaration.
