### ISSUE TITLE
Implement the Response API

### ISSUE THREAD

**Issue by jdm** [servo/servo#11896]
Specification: https://fetch.spec.whatwg.org/#response-class
Documentation: http://doc.servo.org/servo/script/dom/index.html#adding-a-new-dom-interface

This is assigned to our RGSoC team, so please talk with me before starting to work on any part of it.

**Comment by jdm** [comment]
Blocks #11894.

**Comment by KiChjang** [comment]
Is this done?

**Comment by jdm** [comment]
Yes; we can file individual issues for specific missing/broken things.
