### ISSUE TITLE
Asynchronous changes to IFrame visibility property do not cause a change.

### ISSUE THREAD

**Issue by samuknet** [servo/servo#11891]
The visibility property can successfully be set on an IFrame, but it appears any asynchronous updates to the property do not cause a change.  

The problem can be replicated by a simple example which toggles an IFrames visibility property from 'hidden' to 'visible' periodically, using setInterval. See: [https://samuknet.github.io/test_cases/iframePropertyToggle/index.html](https://samuknet.github.io/test_cases/iframePropertyToggle/index.html) for example.

The problem is summed up with this code:

```
 // Expecting to see a flashing IFrame which periodically appears and then re-appears
        window.addEventListener('DOMContentLoaded', function() {
            var fr = document.querySelector('#f'); // An IFrame
            toggleProperty(); // This call works and causes a change
            setInterval(toggleProperty, 1000);
            function toggleProperty() {
                // Asynchornous changes to the property do not cause a change
                fr.style.visibility = fr.style.visibility === 'hidden' ? 'visible' : 'hidden' ;
            }
        });


```

This appears to only apply to IFrames as everything works expected when using a div. Also, the problem appears to apply not just to the 'visibility' property but 'opacity' too.

**Comment by notriddle** [comment]
It's not related to subsequent-ness. It's related to async-ness. If you remove the "initial" call to `toggleProperty()` in your test case, you'll notice that it doesn't blink at all.

**Comment by nox** [comment]
This was fixed.
