### ISSUE TITLE
browser.html breaks on first page load

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#11905]
In a recent build (starting in the last week or so), if I run servo with -b to get browser.html, and I navigate to a page, I get a spew of messages like this in the terminal:

```
ERROR:js::rust: Error at file:///Users/jturner/Source/servo/target/release/build/browserhtml-0964734a748088d9/out/components/main.js:10:3406: e is undefined

ERROR:js::rust: Error at file:///Users/jturner/Source/servo/target/release/build/browserhtml-0964734a748088d9/out/components/main.js:10:3406: e is undefined

ERROR:js::rust: Error at file:///Users/jturner/Source/servo/target/release/build/browserhtml-0964734a748088d9/out/components/main.js:10:3406: e is undefined

ERROR:js::rust: Error at file:///Users/jturner/Source/servo/target/release/build/browserhtml-0964734a748088d9/out/components/main.js:10:3406: e is undefined
```

This can go for pages for only a few dozen times depending on the page I load.  After this happens, the loading indicator appears to freeze and I can no longer click on the location box for browser.html.  I've tried facebook.com, google.com, youtube.com, and yahoo.com and they all give me the same result.

I'm on OS X 10.11.5.

**Comment by jdm** [comment]
The JS errors are caused by browser.html and should be filed upstream.

**Comment by jonathandturner** [comment]
@jdm - this has potentially strong impact for Servo's upcoming tech demo.  At the very least it should have a tracking issue here.  I've gone ahead and filed a bug on the browser.html repo as well (https://github.com/browserhtml/browserhtml/issues/1106)

**Comment by jonathandturner** [comment]
(that is, of course, assuming it repros for other people and it's not just something funky with my setup)

**Comment by larsbergstrom** [comment]
Load did not get stuck for me (OSX 10.11, servo as of 7b2080c5b7c933f74c0d92249a66f8602340ebbe), but I did see all those errors.
