### ISSUE TITLE
Facebook blinks and is unusable

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#11903]
In the last week or so, I noticed a regression where Facebook started to blink on the main page.  Each time it blinked, it took away your ability to input your login, rendering the page unusable (or practically unusable)

I have a video of this if anyone is interested. 

I'm on OS X 10.11.5.

**Comment by pcwalton** [comment]
This is because Servo is spawning 2,000+ threads when opening that site

**Comment by pcwalton** [comment]
Facebook is opening an infinite loop of iframes to https://www.facebook.com/intern/common/referer_frame.php. This is causing Servo to exhaust resources.

**Comment by jdm** [comment]
That would be fixed by https://github.com/servo/servo/pull/11321.

**Comment by ConnorGBrewster** [comment]
This is still not fixed by #11321/#11934

**Comment by nox** [comment]
Is this still true?

**Comment by jonathandturner** [comment]
@nox - hard to tell, Facebook doesn't seem to be working anymore in the latest nightly.

**Comment by atouchet** [comment]
I am not able to reproduce this issue.

**Comment by dralley** [comment]
Seems like it can be closed?
