### ISSUE TITLE
Scrolling on DDG's html results page and bing results page broken under browser.html

### ISSUE THREAD

**Issue by tschneidereit** [servo/servo#11908]
With current servo and browser.html, [DuckDuckGo results pages that contain a Wikipedia header](https://duckduckgo.com/html/?q=mozilla) have broken scrolling. Instead of the page scrolling, the contents of the Wikipedia header jumps to the right and down.

The same thing happens on [bing.com result pages](http://www.bing.com/search?q=mozilla).

//CC @pcwalton.

**Comment by glennw** [comment]
Looks like it is selecting the wrong layer to try and scroll. Now to work out where the layer selection is going wrong...

**Comment by glennw** [comment]
I think there's probably two problems here. Logging the scroll layers that get created on that page shows:

Layer::new (0,0) 1024×700 PipelineId(0, 0) ServoStackingContextId(FragmentBody, 0)
Layer::new (0,0) 1024×700 PipelineId(0, 0) ServoStackingContextId(FragmentBody, 0)
Layer::new (0,27) 1024×4075.75 PipelineId(1, 0) ServoStackingContextId(FragmentBody, 0)
Layer::new (0,27) 1024×4075.75 PipelineId(1, 0) ServoStackingContextId(FragmentBody, 0)
Layer::new (0,27) 1024×4075.75 PipelineId(1, 0) ServoStackingContextId(FragmentBody, 139984034185664)
Layer::new (0,27) 1024×4075.75 PipelineId(1, 0) ServoStackingContextId(FragmentBody, 139984034188208)
Layer::new (104,124) 644×153.76666 PipelineId(1, 0) ServoStackingContextId(FragmentBody, 139984034265312)

The first problem is that the layer select picks the small layer - which is probably a coordinate system issue. The second problem is that the small layer doesn't seem to get scrolled along with its parent layer either.

**Comment by glennw** [comment]
I think what might be happening is that there are several scroll layers being created (on the first few levels of the flow tree in the iframe) due to overflow: auto. But then, I think content gets added to the first of those scroll layers and the layer detection logic then picks the bottom most layer to scroll, which contains no actual render items.

@pcwalton I don't really understand what's going on here - any ideas?

**Comment by glennw** [comment]
Relevant PR: https://github.com/servo/webrender/pull/300

**Comment by paulrouget** [comment]
This works now.
