### ISSUE TITLE
Fire load event for external stylesheets

### ISSUE THREAD

**Issue by jdm** [servo/servo#11912]
https://github.com/servo/servo/commit/f3cdba6b8bbd51eedb05bdb4c21073f4fe41e9a8 made `<link>` elements receive a `load` event after the stylesheet was finished loading. https://github.com/servo/servo/commit/543703e3d8d7dde5efd280fb01e42061287c7002 regressed this, and the test added in https://github.com/servo/servo/commit/f3cdba6b8bbd51eedb05bdb4c21073f4fe41e9a8 didn't catch this because it uses `t.step_func` instead of `t.step` - the former returns a function but doesn't execute it, while the latter executes the function argument. We should fire a simple event named `load` in `StylesheetContext::response_complete`, and fix the test.

Code: `components/script/dom/htmllinkelement.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/document-metadata/the-link-element/link-load-event.html`

**Comment by jdm** [comment]
Note that if #11913 merges before this work begins, it's expected that the 404 test in `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/document-metadata/the-link-element/link-load-event.html` will start failing. This is because the existing failure is currently hidden by the missing load event.

**Comment by crazymykl** [comment]
I'd like to try my hand at this one.
