### ISSUE TITLE
Add a default link style

### ISSUE THREAD

**Issue by jdm** [servo/servo#11915]
```html
<a>hi there</a>
```
looks like
<img width="72" alt="screen shot 2016-06-28 at 6 45 30 pm" src="https://cloud.githubusercontent.com/assets/27658/16434909/83226f88-3d60-11e6-88df-fc8df0e31ccc.png">
in master. We should style our links blue and underlined by default like other browsers.

Code: `resources/servo.css`

**Comment by notriddle** [comment]
We do have default link styling. Look at this code:

```html
<a href="#">hi there</a>
```

![screenshot from 2016-06-28 15-58-46](https://cloud.githubusercontent.com/assets/1593513/16435223/42b3a186-3d49-11e6-93d0-fc4ec354f683.png)

The underline is black, which is a bug. That bug is #11870

**Comment by notriddle** [comment]
And the `<a>Hi there</a>` example that you gave looks identical in Chrome and Firefox.
