### ISSUE TITLE
External stylesheets still apply even if the Content-Type is incorrect

### ISSUE THREAD

**Issue by jdm** [servo/servo#11910]
`StylesheetContext::headers_available` fires an `error` event at the `<link>` element if the `Content-Type` header is incorrect, but when `StylesheetContext::response_complete` is executed, we go ahead and parse the contents as a stylesheet anyways. We should modify the `link-style-error-01.html` test to fail if the `load` event is received to catch this.

Code: `components/script/dom/htmllinkelement.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/document-metadata/the-link-element/link-style-error-01.html`

**Comment by jdm** [comment]
The test change relies on #11912 being fixed first, or else the test won't have a `load` event to watch for.

**Comment by crazymykl** [comment]
Since I took the prereq, I may as well take this as well.

**Comment by jdm** [comment]
Great!

**Comment by crazymykl** [comment]
This can also be closed, I accidentally bungled the syntax to make it happen automatically.

**Comment by KiChjang** [comment]
Fixed in #11919.
