### ISSUE TITLE
Moire demo circles do not move around.

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#11939]
This is one of the demos linked on `about:newtab` in bhtml.
![moire_issue](https://cloud.githubusercontent.com/assets/9086315/16472884/70584178-3e25-11e6-82ca-4933a7a0f9b6.gif)

**Comment by ConnorGBrewster** [comment]
This can be temporarily be fixed by changing:
```
.object {
    position: absolute;
    width: 100%;
    height: 100%;
}
```
to
```
.object {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
}
```

**Comment by ConnorGBrewster** [comment]
Adding P1 as I assume we want all the linked demos on the newtab page to work properly. Feel free to change it if it shouldn't be P1.

**Comment by glennw** [comment]
This seems to happen whether using webrender or not - some layout regression perhaps?

**Comment by asajeffrey** [comment]
The demo works if you run it with `--nonincremental-layout`.

**Comment by cbrewster** [comment]
Not an issue anymore.
