### ISSUE TITLE
Places render backwards on Duck Duck Go

### ISSUE THREAD

**Issue by this-jacob** [servo/servo#11936]
![screen shot 2016-06-29 at 2 28 05 pm](https://cloud.githubusercontent.com/assets/8703799/16467777/09c929f0-3e06-11e6-96d1-94db49224060.png)
![screen shot 2016-06-29 at 2 30 40 pm](https://cloud.githubusercontent.com/assets/8703799/16467788/144cb82e-3e06-11e6-9097-b371c1eefea2.png)

Place information on Duck Duck Go searches render mirrored

**Comment by gpoesia** [comment]
I tried reproducing it, but it looks fixed on master:
![ddg_places](https://cloud.githubusercontent.com/assets/1392193/16561919/1e8c47c6-41d2-11e6-8325-64788e4eb62e.png)

**Comment by junktext** [comment]
So, for what it's worth, I'm also getting the backwards "Places" suggestion text. Although, I'm not using the Servo engine as instead I am using the default Gecko engine for Firefox on Ubuntu 15.10 (64-bit). I've went ahead and informed the DuckDuckGo developers about this bug as well.

Lastly, this seems to be a Firefox glitch. Google Chrome didn't give me any problems.

Details: https://duck.co/forum/thread/22577/places-text-on-ddg-is-rendered-backwards-on-fire

**Comment by nox** [comment]
I assume this doesn't happen anymore and something weird in DDG itself was going on. See https://github.com/duckduckgo/duckduckgo/issues/214.
