### ISSUE TITLE
Switch to Dropbox's crate for Brotli encoding/decoding

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#11933]
https://github.com/servo/servo/search?utf8=%E2%9C%93&q=brotli

https://blogs.dropbox.com/tech/2016/06/lossless-compression-with-brotli/

https://github.com/dropbox/rust-brotli

I haven't done any benchmarks; I'm ignorantly assuming the Dropbox one has better performance. Though if someone felt compelled to, they could do benchmarks. [Relevant thread about brotli-rs performance](https://github.com/ende76/brotli-rs/issues/24).

This might be a candidate for an E-Easy task.

**Comment by johannhof** [comment]
Sounds interesting, I can look into that.

@frewsxcv what kind of benchmarks did you have in mind? Simply comparing the two libraries or is there a good way to bench the respective Servo functions that use Brotli? From a quick glance it seems that Servo only runs high-level browser benchmarks.

**Comment by johannhof** [comment]
Because it was the quickest thing I could come up with I took the two bench tests from brotli-rs (https://github.com/ende76/brotli-rs/blob/master/benches/lib.rs) to rust-brotli, and rust-brotli seems faster:

```
test bench_alice      ... bench:   1,573,111 ns/iter (+/- 440,450)
test bench_alice_old  ... bench:  10,522,060 ns/iter (+/- 2,299,023)
test bench_monkey     ... bench:      22,604 ns/iter (+/- 5,375)
test bench_monkey_old ... bench:      84,901 ns/iter (+/- 47,822)
```

I guess it's not a surprise as this was discussed already in the brotli-rs issue.
