### ISSUE TITLE
Quitting servo+browser.html doesn't always really quit

### ISSUE THREAD

**Issue by tschneidereit** [servo/servo#11937]
This is a bit of a weird one: sometimes trying to quit the application causes all interactions to cease, while the window stays visible. Resizing it results in a black rectangle though.

STR:
1. click on any tile
2. cmd+t
3. click on another tile
4. ctrl+tab twice
5. click on the close button

**Comment by guillaume-uH57J9** [comment]
Same behavior here with the latest nightly build, with Debian GNU/Linux, GNOME 3

5627530f8e72955c75799b2c50ef3f752fe70d44  servo-latest.tar.gz
5da8408654f3b96264407cf163bb64fe43a7d7bd  servo/servo

**Comment by moosingin3space** [comment]
Confirmed the same behavior on Ubuntu 14.04.4 with Unity.

**Comment by paulrouget** [comment]
Not relevant anymore.
