### ISSUE TITLE
Package script for Linux/Windows puts runservo.sh in wrong location

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11944]
https://github.com/servo/servo/blob/master/python/servo/package_commands.py#L177

`'runservo.sh'` should be `'/runservo.sh'` otherwise the script ends up in `/target` instead of in the package.

**Comment by hgallagher1993** [comment]
Ya I'll take it

**Comment by ConnorGBrewster** [comment]
@hgallagher1993 its all yours!

**Comment by ConnorGBrewster** [comment]
@hgallagher1993 so sorry, but this is needed for the tech demo/preview today. I probably should've mentioned that in the description.

**Comment by hgallagher1993** [comment]
I actually had it fixed about 12 or more hours ago but it was getting late (where I am) so I didn't bother making the pull request...ohh well :-)

**Comment by ConnorGBrewster** [comment]
@hgallagher1993 once again, I am so sorry about that. I really do feel bad. Feel free to take on something else though!
