### ISSUE TITLE
Twitter still doesn't work

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#11947]
<img width="1282" alt="screen shot 2016-06-30 at 12 23 07 pm" src="https://cloud.githubusercontent.com/assets/1617736/16479326/32326750-3ebd-11e6-88bb-93f8057fcb5e.png">

I can open my notifications and settings and all, but I can't tweet or read tweets.

Perhaps we should link to mobile twitter in the demo newtab page instead?

cc @metajack

**Comment by nox** [comment]
<img width="1058" alt="capture d ecran 2017-10-02 a 10 24 48" src="https://user-images.githubusercontent.com/123095/31069249-f0315e66-a75b-11e7-9a49-35e726684b8d.png">
