### ISSUE TITLE
Github's hamburger doesn't show

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#11958]
When Github is opened in a window with a smaller width, the sign up/sign in buttons are stuffed into a hamburger menu. The icon for the menu doesn't show in Servo.

To repro:
- `./mach run -r -b -- --resolution 800x600`
- Open github
- 😢 when you can't log in

**Comment by Manishearth** [comment]
(I fixed this for the demo by setting the default resolution to 1024x740)

**Comment by metajack** [comment]
Where did 740 come from?

**Comment by Manishearth** [comment]
It was a number that worked. IIRC 720 didn't.

I could bump it to 768 if you think that's better.

**Comment by metajack** [comment]
768 would be less odd, but there is not technical reason I can immediately think of for it to be any particular value :)

**Comment by nox** [comment]
I can't seem to reproduce this anymore.
