### ISSUE TITLE
Transparent Rects demo gets hidden when opening the browser.html sidebar

### ISSUE THREAD

**Issue by tschneidereit** [servo/servo#11961]
Instead of continuing to play the demo or at least show a frozen version of the last frame, we only show the background color.

STR:
1. Open Servo with browser.html
2. Click on the "Demo: Transparent Rects" tile
3. Click on the hamburger menu in the top-right corner

**Comment by ConnorGBrewster** [comment]
This doesn't happen when running without webrender

**Comment by nox** [comment]
I don't remember where the demos are so I can't reproduce it.

**Comment by jdm** [comment]
https://cdn.rawgit.com/servo/servo.org/gh-pages/bhtml-newtab/newtab.html

**Comment by atouchet** [comment]
This is no longer reproducible as Browser.html was removed.
