### ISSUE TITLE
Escape key on wikipedia.org quits servo

### ISSUE THREAD

**Issue by Gozala** [servo/servo#11965]
Steps to reproduce:

1. Load browser.html
2. Click wikipedia tile
3. Hit escape key

**Comment by Gozala** [comment]
Or even simpler steps to reproduce will be:

```
servo -w --pref shell.quit-on-escape.enabled=false https://wikipedia.org
```

And hit escape key

**Comment by Coder206** [comment]
@Gozala I was not able to load Wikipedia from the icon, Servo seems to be in a loop with constellation.

**Comment by jdm** [comment]
The simpler steps to reproduce are invalid; `servo -w --pref shell.builtin-key-shortcuts.enabled=false https://wikipedia.org` does not show the problem.

**Comment by jdm** [comment]
I also can't reproduce the problem described in the original steps.

**Comment by paulrouget** [comment]
@Gozala https://github.com/browserhtml/browserhtml/pull/1098/files

**Comment by Gozala** [comment]
@paulrouget It's changed again to `shell.builtin-key-shortcuts.enabled`

**Comment by Gozala** [comment]
This should fix it on browser.html side https://github.com/browserhtml/browserhtml/pull/1133
