### ISSUE TITLE
Spinner demo: squares are missing

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11970]
Half the squares are missing in the spinning demo. This is now on the front page, so I'm marking this P1. cc @ConnorGBrewster

**Comment by asajeffrey** [comment]
Related to #11873? cc @notriddle

**Comment by ConnorGBrewster** [comment]
I tried running the demo with the changes in #11873, didn't have an effect.

**Comment by asajeffrey** [comment]
Oh well, I tried :(

**Comment by ConnorGBrewster** [comment]
![spinning_issue 6 49 05 pm](https://cloud.githubusercontent.com/assets/9086315/16503343/e1025d00-3ecf-11e6-987a-f5ff4c8bbfb8.gif)

**Comment by asajeffrey** [comment]
Duplicate of #11759

**Comment by ConnorGBrewster** [comment]
Removing P1 as this will not be on the newtab page browsterhtml/browserhtml#1139

**Comment by asajeffrey** [comment]
Fixed by #11873:

![screenshot from 2016-06-30 16-51-44](https://cloud.githubusercontent.com/assets/403333/16505813/70072b34-3ee4-11e6-98e8-22aaebb8244b.png)

**Comment by nox** [comment]
This was fixed, right?
