### ISSUE TITLE
Create new folder when packaging on linux

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11983]
Right now we take the `target/[relase|debug]` and remove everything but servo and bhtml and when we copy resources and add the run script. We should instead create a new temporary folder, copy servo, bhtml, resources, runscript to the new directory and create the `tar.gz` from that. After the `tar.gz` is created, the temporary folder should be deleted. This is similar to how packaging is done on the mac. The script should also check for the temporary folder when starting the packaging and delete it if it exists. If you don't do this, there will be errors with copying since `shutil.copytree` will not overwrite existing.

**Comment by Coder206** [comment]
@ConnorGBrewster I would like to try solving this issue.

**Comment by aneeshusa** [comment]
It would be nice to do some locking of the packaging directory to prevent simultaneous builds, but I would not consider part of the E-easy (can be done in a follow-up).

**Comment by Coder206** [comment]
Not sure where to start. Would I be able to use Rust to write the code and implement @ConnorGBrewster's issue?

**Comment by ConnorGBrewster** [comment]
@Coder206 the packaging script is in `python/servo/package_commands.py`, if you look there there are android, OS X, and other branches for packaging. The other branch (which will be used for only linux in the future) currently makes changes to the [debug|release] folders when making the package. I would rather create a new directory and copy the needed files to the new directory than altering the  [debug|release] folders. You can look at the mac branch as an example as it creates a new directory called `dmg` and copies the needed files to their respective locations there.

**Comment by Coder206** [comment]
@ConnorGBrewster Ok perfect. That makes sense! Thanks :)

**Comment by ConnorGBrewster** [comment]
@Coder206 any progress on this?

**Comment by Coder206** [comment]
@ConnorGBrewster Yes, I was beginning to understand how everything works. However, it will be at least a week before a PR is submitted. I understand if you want to give this to someone else to get it done quicker.

**Comment by ConnorGBrewster** [comment]
@Coder206 no worries, this isn't a huge priority right now.

**Comment by Coder206** [comment]
@ConnorGBrewster I made modification to `python/servo/package_commands.py` that reflect what you asked above based on OSX's code. I had a few questions: 

1. When you say copy "servo", should the script copy the whole directory? 
2. To test my code to make sure it works, is `python package_commands.py` the way to do that?

**Comment by jdm** [comment]
`Copy servo` means copy the servo binary.

**Comment by jdm** [comment]
I'm pretty sure the correct way to test it is `./mach package`.

**Comment by Coder206** [comment]
@jdm Thanks
