### ISSUE TITLE
The nightly upload script should also copy the newest binary to the name "servo-latest"

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#11987]
After uploading a nightly build with a specific date in its filename, we should also create a file named "servo-latest" (with the appropriate extension, e.g. `.tar.gz`) for easy linking. This change should be made here:
https://github.com/servo/servo/blob/master/etc/ci/upload_nightly.sh#L15

**Comment by imjacobclark** [comment]
I'll pick this issue up.

**Comment by Wafflespeanut** [comment]
Good to know! :)

**Comment by imjacobclark** [comment]
Initial pull request for this raised: https://github.com/servo/servo/pull/12004.

Let me know of any feedback on approach, concerns or changes that I need to make.
