### ISSUE TITLE
Servo deosn't load web pages on proxy.

### ISSUE THREAD

**Issue by iampritishpatil** [servo/servo#11994]
On ubuntu 16.04 the nightly build from download.servo.org on 1st July 2016 doesn't take system proxy and fails to load any webpages.

**Comment by moiSurGitHub** [comment]
I confirm
it's ok if I use proxychains at the beginning of the command
`proxychains ./runservo.sh`

**Comment by nox** [comment]
Closing as duplicate of #18673.
