### ISSUE TITLE
Keyboard keys AZERTY are badly mapped

### ISSUE THREAD

**Issue by dascritch** [servo/servo#11991]
When i am on the start page, i want to put and URL, but I cannot, as keys are not correctly mapped.

OS : Kubuntu 14.04 LTS , arch 64 . Keyboard layout : AZERTY, 105 keys

Letters seems corrects, but symbols keys are bad : 

numeric rank:
«²», «&» , «é», «"», «(», «è», «_», «ç», «à», «)» are not mapped

right side of the two upper letter ranks : none of them

On lower rank, after VBN letters : 
hitting «?» gives a «<» , non numpad «.» gives a «:» , «/» and «§» are mapped to nothing,

**Comment by Ms2ger** [comment]
Thanks for filing; this should be fixed by #11950.

**Comment by dascritch** [comment]
Cool !
Keep me informed, so I can test it.

**Comment by guillaume-uH57J9** [comment]
Same thing on Debian GNU/Linux with the latest nightly build, but I suspect this should be tested again with the next one

**Comment by jdm** [comment]
Tracked by #4144. Thanks for reporting it!
