### ISSUE TITLE
wikipedia icon is not rendered properly

### ISSUE THREAD

**Issue by nt1m** [servo/servo#11993]
<img width="165" alt="favicon-rendered-strange" src="https://cloud.githubusercontent.com/assets/1795135/16513479/65822cbe-3f65-11e6-87ff-8fbe85733a3b.png">

**Comment by philipc** [comment]
Duplicate of #10305 . Fixed in the image crate but the dependency needs updating still.

**Comment by ConnorGBrewster** [comment]
Thank you for the report! 😄 
Closing as dupe
