### ISSUE TITLE
Getting servo use MSVC-ABI

### ISSUE THREAD

**Issue by lygstate** [servo/servo#11997]
On windows MSVC-ABI are more user friendly

**Comment by upsuper** [comment]
To fix this, I think we would need to build a font backend based on GDI and DirectWrite, rather than FreeType.

**Comment by metajack** [comment]
Besides the font backend, we'll also need @vvuk's work on the build system changes since we'll want to shed the whole dependency on msys2.

**Comment by lygstate** [comment]
seems fixed
