### ISSUE TITLE
Servo Nightly hangs on Wikipedia

### ISSUE THREAD

**Issue by defyrlt** [servo/servo#12017]
So I downloaded Servo today, and tried to simply go to Wikipedia by clicking on the second button of the home page (IDK if it's `http` or `https` there). After a second or two it just hangs, like it's trying to load the page, but it's not.

```
[user@localhost servo]$ ./servo --version
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libssl.so.1.0.0: no version information available (required by ./servo)
Servo 0.0.1-4f81384
```

After the first failure I did this

```
[user@localhost servo]$ RUST_BACKTRACE=1 ./runservo.sh 2>&1 | tee -a servo.log`
```

and tried to go to Wikipedia again. And here's the output - [gist](https://gist.github.com/defyrlt/4325046155013a365003dad4eded9721). Here's the output without `RUST_BACKTRACE` - [gist](https://gist.github.com/defyrlt/919b8ba590af77eeacf141de3b09c8cc).

**Comment by Manishearth** [comment]
Try to update your openssl. What does `openssl version` say for you?

**Comment by defyrlt** [comment]
```
$ openssl version
OpenSSL 1.0.2h  3 May 2016
$ sudo pacman -S openssl
warning: openssl-1.0.2.h-1 is up to date -- reinstalling
```

**Comment by Manishearth** [comment]
Hm. @jdm, know anything about this?

**Comment by Manishearth** [comment]
Dupe: https://github.com/servo/servo/issues/12015, in this case it doesn't even start.

**Comment by evotopid** [comment]
I'm also on Arch Linux. For me launching `./rustservo` results in no window showing at all ([output](https://gist.github.com/evotopid/e5f128691fb866bbcf346c86f245f557)) while `./servo` opens an empty window and seems to be stuck ([output](https://gist.github.com/evotopid/24d00e6c39d8796bd7e26f4b69e6a131)).

There is no panic in this case though.

**Comment by varjagg** [comment]
Experiencing lock up on rendering https://en.wikipedia.org/wiki/Servo_%28layout_engine%29 nightly, but only when referred from google.com. Referrals from duckduckgo render properly.

**Comment by heftig** [comment]
I believe the symbol versioning in openssl is a debianism.

**Comment by nox** [comment]
Is this still an issue?

**Comment by leoschwarz** [comment]
I still get these messages on startup with the latest (pre-built) nightly on Arch Linux:

```
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libssl.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libssl.so.1.0.0: no version information available (required by ./servo)
```

And frequent freezes (only resolved by killing servo) when scrolling on Wikipedia, but I'm failing to create a meaningful log output. (I tried with `RUST_LOG="debug" RUST_BACKTRACE=1` but all I get is tons of `INFO:script::dom::window: script: waiting on layout` until this stops also.)

**Comment by nox** [comment]
We updated openssl since then.
