### ISSUE TITLE
background tabs eat cpu

### ISSUE THREAD

**Issue by sigio** [servo/servo#12012]
I had a tab open with 'spheres' from the demo-page, and was reading hackernews in another tab on the foreground when I noticed servo was eating 170% cpu...
Maybe suspend or reduce-performance on unfocussed tabs.

**Comment by paulrouget** [comment]
> Maybe suspend or reduce-performance on unfocussed tabs.

This is supposed to be supported, but apparently, browserhtml doesn't throttle the tab.

See https://github.com/browserhtml/browserhtml/issues/1188

**Comment by paulrouget** [comment]
Should be better now.
