### ISSUE TITLE
ReferenceError: navigator.mozSettings API is not available

### ISSUE THREAD

**Issue by poppingtonic** [servo/servo#12014]
This happens when I load the [Servo announcement blog post](https://blog.servo.org/2016/06/30/servo-nightlies/)
![image](https://cloud.githubusercontent.com/assets/5781617/16516116/a8f10e98-3f7e-11e6-87f5-1d747b31f330.png)

**Comment by Manishearth** [comment]
Looks like a bhtml bug? cc @paulrouget

**Comment by jdm** [comment]
Yeah, I've filed this upstream as https://github.com/browserhtml/browserhtml/issues/1153.
