### ISSUE TITLE
Incorrect layout of drop-down menus on byuu.org

### ISSUE THREAD

**Issue by Screwtapello** [servo/servo#12021]
http://byuu.org has a bar across the top with pure CSS drop-down menus. In Firefox, the menu is a single line tall, and when I hover over a top-level menu, the items within appear hovering over the page content.

In Servo, the bar is tall enough to contain the menu with the most children, and each top-level menu is high enough from the bottom to fit all its children beneath it. When I hover over a top-level menu item, the items within appear below the menu label, but it does not hover over the page content.

**Comment by stshine** [comment]
Looks like this is fixed.
