### ISSUE TITLE
emberjs.com crashes Servo.app

### ISSUE THREAD

**Issue by locks** [servo/servo#12028]
I downloaded Servo.app 0.0.1 today from https://servo-builds.s3.amazonaws.com/index.html.
When visiting the [Ember.js website](http://emberjs.com/), the app crashes with the
[following crash log](https://github.com/servo/servo/files/343248/crashlog.txt).

**Comment by jdm** [comment]
I couldn't reproduce this in a local debug build on OS X.

**Comment by Aaron1011** [comment]
I couldn't reproduce this either, running Arch Linux.
