### ISSUE TITLE
Typing quickly results in garbage input

### ISSUE THREAD

**Issue by whitequark** [servo/servo#12039]
I was running the Transparent Rectangles demo fullscreen, which caused it to run at ~27FPS (as reported on stdout). During that, I started typing "github" in the URL bar. I type pretty quickly, evidently too quickly for Servo because that's what this resulted in:
![2362](https://cloud.githubusercontent.com/assets/54771/16520593/9a25a020-3f80-11e6-8336-55f68a04e2ec.png)

**Comment by ConnorGBrewster** [comment]
After doing a bit of research into this issue, I believe the issue is on the browser.html end with `setSelectionRange`

**Comment by paulrouget** [comment]
I hit this bug pretty often. bhtml race maybe. bhtml issue: https://github.com/browserhtml/browserhtml/issues/1189

**Comment by ConnorGBrewster** [comment]
I believed this is fixed https://github.com/browserhtml/browserhtml/pull/1166

**Comment by jdm** [comment]
Closing, in that case.
