### ISSUE TITLE
travis-ci.org does not render in Servo

### ISSUE THREAD

**Issue by alex** [servo/servo#12036]
This is using the nightly. Accessing `https://travis-ci.org` simply displays:

![screen shot 2016-07-01 at 7 25 32 am](https://cloud.githubusercontent.com/assets/772/16520289/278f9070-3f5d-11e6-9d8a-ed7ed61bfd2f.png)

**Comment by ConnorGBrewster** [comment]
Thank you for reporting this!
Possibly related to the issue on #11928?

**Comment by alex** [comment]
This is fixed now.
