### ISSUE TITLE
Opening http://github.com/whitequark/solvespace results in a hang

### ISSUE THREAD

**Issue by whitequark** [servo/servo#12041]
On the screen there's just pre-JS GitHub content and then a black screen if I switch from and back to Servo's window. Nothing interesting on stdout: just

```
ERROR:js::rust: Error at https://assets-cdn.github.com/assets/frameworks-6fe6a7604ec4c2601272849e1b99a3a9aa12c79b3e25be0360f8d114768e7578.js:6:6359: history is not defined
```

which seems to always happen when using github.

**Comment by jdm** [comment]
Tracked by #5669. Thanks for reporting!

**Comment by jdm** [comment]
Sorry, misread the subject of the issue.

**Comment by nox** [comment]
This does not hang anymore.
