### ISSUE TITLE
Scrolling jumps on the end of some pages sometimes

### ISSUE THREAD

**Issue by hannni** [servo/servo#12058]
On some sites (e.g. news.ycombinator.com) servo jumps when starting to scroll again. It always jumps when scrolling back upwards again, and only sometimes when scrolling downwards past the page.

I'm using OS X 10.11

Video of the said behaviour.
https://www.youtube.com/watch?v=GLUYH4MKnr4

**Comment by paulrouget** [comment]
Overscroll issue.

**Comment by mrobinson** [comment]
@paulrouget Is this still an issue now that everything had switched to WebRender?

**Comment by paulrouget** [comment]
That was originally a WR bug. But I haven't seen this problem in a while.
