### ISSUE TITLE
Layout issues in Glowing Bear

### ISSUE THREAD

**Issue by lorenzhs** [servo/servo#12056]
The layout is a bit off on https://latest.glowing-bear.org, which uses Bootstrap layout stuff. The checkboxes should be aligned with the input fields.

![screenshot from 2016-07-01 15-40-40](https://cloud.githubusercontent.com/assets/142205/16523163/366d61cc-3fa2-11e6-9dd2-e82da53e78f2.png)

It also does really weird things with the accordion menu sometimes (but that's really hacky and I'm actually surprised that it works in other browsers)

~~I can't test it any further because for some reason keys do weird things in the password box (clear, select all, various others). I use a nonstandard keyboard layout (neo2).~~

~~I've managed to enter the password now, but it doesn't connect (secure websocket connection with a Letsencrypt certificate, which is trusted by the system). The server receives the connection and sends the HTTP1.1 upgrade thingy, but then never hears back from Servo. Should I file a separate issue for that, or is it known?~~ moved to #12070

**Comment by jdm** [comment]
Websockets are supposed to work, so please file that separately!

**Comment by lorenzhs** [comment]
Right, will do. I'll see if I can pinpoint it down a bit.

**Comment by nox** [comment]
<img width="1136" alt="capture d ecran 2017-10-04 a 09 41 27" src="https://user-images.githubusercontent.com/123095/31164620-382f0456-a8e8-11e7-9890-d99b5ff5c11e.png">

**Comment by lorenzhs** [comment]
The checkbox labels are still a bit off but this is much better. Thank you! :)
