### ISSUE TITLE
Error running servo on windows: ./python/servo/post_build_commands.py line 161

### ISSUE THREAD

**Issue by samal84** [servo/servo#12051]
Tried building servo on Windows 7 and got this error on running ./mach run -r:
/home/rasmuss/source/servo/target/release/build

```
Error running mach:

    ['run', '-r']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command. Consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 84] Accessing a corrupted shared library

  File "./python/servo/post_build_commands.py", line 161, in run
    raise e
```

Build console output attached.
[console-output.txt](https://github.com/servo/servo/files/343534/console-output.txt)

**Comment by metajack** [comment]
I've not seen that error before. Interesting.

You'll want to pass an HTML page or URL to it or use `-b` to use browser.html. I'm not sure what the message about a corrupted shared library could be, but I recommend rebuilding. You can get a clean slate by doing `git clean -fxxd` and then `./mach build -r`. If it occurs again and there were no weird build errors, let us know and we'll continue to investigate.

**Comment by samal84** [comment]
Did `git clean -fxxd` and `./mach build -r` and got the same results:
[console-output.txt](https://github.com/servo/servo/files/344932/console-output.txt)

The whole MSYS2 environment is brand new. I just installed it to build servo two days ago, and I followed the official servo build docs.

**Comment by zeusintuivo** [comment]
I have researched and documented an effective way to have windows environments set up for 32 and 64 bits in Windows 7. I assume this will work in all windowses. 
Please see documentation I posted in this ticket. #12356

**Comment by samal84** [comment]
Closing this as I see you made a whole new build system for Windows since I made this issue.
