### ISSUE TITLE
Add Servo version to About Servo

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#12052]
I am not sure how to do this, but it would be nice.

**Comment by Kyle-Mendes** [comment]
![image](https://cloud.githubusercontent.com/assets/6400039/16523303/bdbb9770-3f70-11e6-9ff5-6087c29bf19f.png)

I'm seeing the version number in the about on Mac. 

Is this the "About Servo" location that you were talking about? Or does it exist somewhere else?

**Comment by metajack** [comment]
We really need the nightly date there. And also probably in `--version`.

**Comment by netsgnut** [comment]
If we want the version to be displayed there, the compilation script should update `CFBundleShortVersionString` from `Info.plist`?

**Comment by ConnorGBrewster** [comment]
@netsgnut we should do that as well, but this unfortunately does not update the About Servo window.

**Comment by ConnorGBrewster** [comment]
One option is to add a `Credits.rtf` file to `Resources`. In this file we could put the package date, servo cargo version, and commit hash. `Version 0.0.1` will still be there, but this would be a simple temporary fix. Actually adjusting the version shown on the about window itself, will be a bit more involved.

**Comment by aneeshusa** [comment]
@metajack I do not want the nightly date there because that breaks deterministic builds. However, with #12136, we can use `util::servo_version()`, which includes the git revision of the build, and should be precise enough for debugging.

**Comment by ConnorGBrewster** [comment]
Work in progress: https://github.com/ConnorGBrewster/servo/tree/mac_about_version
<img width="396" alt="screen shot 2016-07-01 at 9 24 47 pm" src="https://cloud.githubusercontent.com/assets/9086315/16538012/594d8426-3fd2-11e6-9b41-462e41c0f3d9.png">

**Comment by aneeshusa** [comment]
I like it, but I think having two different version shown may be confusing/users won't know which one to report. I'd lean towards just using the version with the git hash.

**Comment by ConnorGBrewster** [comment]
@aneeshusa good point, I will just change that to the commit hash.

**Comment by metajack** [comment]
@aneeshusa I'm fine with the git revision. My main concern is that "0.0.1" contains no useful information right now.

**Comment by cbrewster** [comment]
Fixed in #12250
