### ISSUE TITLE
Tabs aren't cropped in the browser.html tab view in the nightly build 

### ISSUE THREAD

**Issue by hannni** [servo/servo#12059]
The tab content is also outside of the bounding box where it should be in

I'm using OS X 10.11

Screenshot: http://imgur.com/Q1Bxibo

**Comment by metajack** [comment]
This was a recent regression.

cc @paulrouget @tschneidereit

**Comment by tschneidereit** [comment]
This is a regression in Servo, reported as #11957.

**Comment by jdm** [comment]
I think this is the same as #11957?
