### ISSUE TITLE
Servo flickers when switching from the address bar to the browser content.

### ISSUE THREAD

**Issue by hannni** [servo/servo#12063]
I'm using OS X 10.11

video: https://youtu.be/FFHr6UZ_KGQ

**Comment by ConnorGBrewster** [comment]
Thank you for reporting this!

**Comment by paulrouget** [comment]
The overlay opacity doesn't appear to be properly animated.

**Comment by hannni** [comment]
Bug doesn't persist anymore on current nightly build
