### ISSUE TITLE
Missing steps in installations for ubuntu 16.04

### ISSUE THREAD

**Issue by cablegunmaster** [servo/servo#12062]
**What did I Do:**
git clone this.
cd servo
./mach --release

**Result**:
Pip failed to execute properly: Could not open requirements file: [Errno 2] No such file or directory: '/home/user/Development/servo/tests/wpt/harness/requirements.txt'

Am I missing steps to make it work? 
I read issue about ubuntu 6xxx issue about libcheese it seems to be not related. 
Installed all the  thought to be related packages but no requirements.txt file found.

**Comment by jdm** [comment]
`tests/wpt/harness/requirements.txt` is present in the repository; is it present in your local clone?

**Comment by jdm** [comment]
Also, did you run `./mach build`? `./mach --release` is not actually a command...

**Comment by cablegunmaster** [comment]
close issue. -_-;;

low space on my disk >.> kinda self explainatory.
