### ISSUE TITLE
Replace instances of unwrap with expect

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#12065]
With the crash reporter in place, we end up with lots of issues with titles like
`called`Result::unwrap()`on an`Err`value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }` or `called`Result::unwrap()`on an`Err`value: "SendError(..)"`.

Even though we plan to reduce unwrap usage, for now we could change many of these to `expect` to make crash report titles more useful when sorting out crashes.

cc @asajeffrey

**Comment by asajeffrey** [comment]
We should find a way to get the filename / line into the crash reports. For uses of `panic!` or `error!` this is probably fairly straightforward, not so easy for `unwrap` or `expect` because those are functions, not macros.

**Comment by aneeshusa** [comment]
This may also mask `unwrap()`s that would have been caught by `check_no_unwrap.sh` when it expands to cover more files, since we allow `expect()`s. We should leave TODO comments or otherwise mark `unwrap()`s that were converted to `expect()`s for the sake of making crash report titles more useful, but that should more handled more robustly in the future.

**Comment by asajeffrey** [comment]
If we wanted to be bold, we could ban both unwrap and expect everywhere, and require explicit uses of `panic!`. This would make it much easier to get filename / line numbers.

**Comment by aneeshusa** [comment]
@asajeffrey I think using `panic!` by itself is too verbose. How about using https://github.com/canndrew/unwrap, which has an `unwrap!` macro? It's almost as ergonomic as regular unwrap, but retains filename/line number information as well as the function from which it was called.

**Comment by asajeffrey** [comment]
The verboseness would discourage people from panicking, which is good :) But there are 1500 uses of `unwrap()` in our code, which I really don't fancy tackling :(

**Comment by nox** [comment]
I think we can close it, it's not actionable and we have been replacing the most infuriating `unwrap` calls since it was filed, AFAIK.
