### ISSUE TITLE
Weird font rendering issue on github.com

### ISSUE THREAD

**Issue by sgrif** [servo/servo#12064]
<img width="1025" alt="screen shot 2016-07-01 at 4 25 59 pm" src="https://cloud.githubusercontent.com/assets/1529387/16524470/b87e15e8-3fa8-11e6-9ab3-8e83a59af07c.png">

Interestingly, the exact pattern it showed was different each time I refreshed the page, and it is no longer occurring when I refresh the page. It was heavily artifacted the first 2-3 times though. I'm on a slower than normal connection so it might have to do with network timing (cache hits explaining why it's no longer occurring)

**Comment by ConnorGBrewster** [comment]
@sgrif thanks for reporting this! I have had this for quite a while. dupe of #11917

**Comment by sgrif** [comment]
No worries. Figured there was no way this one wasn't already known, but a cursory search brought up nothing.
