### ISSUE TITLE
using tab for username/pass entry causes submit

### ISSUE THREAD

**Issue by nickpsecurity** [servo/servo#12071]
Decided to load Hacker News as first site given I saw Servo there. Went to login page. Typed username. Hit tab to go to password field. Automatically submitted the form with bad login. I used mouse to highlight and delete both field to see if it was reproducible. Typed username, hit tab, and form submitted. 

Using Servo on Ubuntu 16.04 (bare metal) with -c option recommended in "can't launch" issue since it otherwise wouldn't run. Did nothing else different.

**Comment by jdm** [comment]
We know that sequential focus navigation using tab isn't supported yet, but it certainly shouldn't cause the form to be submitted. Thanks for reporting this!

**Comment by simartin** [comment]
This is due to "Key::Tab => KeyReaction::TriggerDefaultAction," in components/script/textinput.rs, and removing it solves the issue.

I propose to accept this issue and see if I can add a test for this.

**Comment by simartin** [comment]
Short status update: code fix is ready and tested manually, now working on a unit test
