### ISSUE TITLE
Get issue reports to include the servo build id

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#12083]
When we fire a `mozbrowsererror`, we should include the servo build id or some other identifying information, and get that included in the issue report. cc @ConnorGBrewster

**Comment by ConnorGBrewster** [comment]
@asajeffrey we could just add a `String` field on `MozBrowserEvent::Error` for the version and just use `env!` like the `--version` flag does (https://github.com/servo/servo/blob/d76ffa8fd8b9311ef13eb477c55fc0b7dce753f5/components/servo/main.rs#L65).

**Comment by ConnorGBrewster** [comment]
Even better we can avoid sending the version in that message and just add it in at https://github.com/ConnorGBrewster/servo/blob/master/components/script/dom/htmliframeelement.rs#L356
