### ISSUE TITLE
Tweakers.net More menu is clipped

### ISSUE THREAD

**Issue by notriddle** [servo/servo#12089]
![In Servo the menu is cut off](http://i.imgur.com/qHMSdT5.png)

![In Firefox it is not](http://i.imgur.com/At0icla.png)

**Comment by NiLSPACE** [comment]
This is fixed for me.

**Comment by NiLSPACE** [comment]
@notriddle this is fixed for me.

**Comment by NiLSPACE** [comment]
cc @jdm. It seems @notriddle is inactive.
