### ISSUE TITLE
background errors on Github load

### ISSUE THREAD

**Issue by nickpsecurity** [servo/servo#12087]
Posting this in case it's important. Opened Servo. Pasted the following into address bar:

https://github.com/servo/servo/issues

Results in this output in terminal:

"Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
ERROR:js::rust: Error at file:///home/anon/Downloads/servo/build/browserhtml-3e3805f69808f24d/out/components/main.js:7:13639: e.matches[e.items[e.selected]] is undefined

ERROR:js::rust: Error at https://assets-cdn.github.com/assets/frameworks-6fe6a7604ec4c2601272849e1b99a3a9aa12c79b3e25be0360f8d114768e7578.js:6:6359: history is not defined

ERROR:js::rust: Error at https://assets-cdn.github.com/assets/frameworks-6fe6a7604ec4c2601272849e1b99a3a9aa12c79b3e25be0360f8d114768e7578.js:1:18383: Could not find module github/inspect"

Note: navigator.mozSettings error pops up pretty much any time I use the browser. Might be significant in and of itself.

**Comment by ConnorGBrewster** [comment]
Thank you for reporting this!
`navigator.mozSettings` is tracked in browserhtml/browserhtml#1153 and `history` in #5669/#10992
