### ISSUE TITLE
Unable to run sh file in Fedora 24

### ISSUE THREAD

**Issue by Coder206** [servo/servo#12080]
I am receiving an error when trying to run Servo from the nightly binaries:

`./runservo.sh`

[dev@localhost servo]$ ./runservo.sh
./runservo.sh: line 1: ./mach: No such file or directory
[dev@localhost servo]$ ls
build  resources  **runservo.sh**  servo

**Comment by ConnorGBrewster** [comment]
@Coder206 can you paste the contents of `runservo.sh` here?

**Comment by Coder206** [comment]
@ConnorGBrewster  ./servo -w -b --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref shell.builtin-key-shortcuts.enabled=false ./build/browserhtml-3e3805f69808f24d/out/index.html

**Comment by ConnorGBrewster** [comment]
@Coder206 hmm that looks ok. I am just confused why `./mach` is showing up

**Comment by Coder206** [comment]
@ConnorGBrewster Sorry this is reminiscent of a test I was trying to do to get the binary working.
