### ISSUE TITLE
Mention that Linux nightlies are 64-bit

### ISSUE THREAD

**Issue by kripken** [servo/servo#12084]
The announcement and download pages don't say they are 64-bit (and won't run on 32-bit).

**Comment by aneeshusa** [comment]
Anyone who wants to work on this should submit PRs to [servo/download.servo.org](https://github.com/servo/download.servo.org), which has the download page, and [servo/blog.servo.org](https://github.com/servo/blog.servo.org), which has the announcement as a blog post.

**Comment by Coder206** [comment]
I give this one a shot.

**Comment by edunham** [comment]
@Coder206 Thank you! Both are now merged; might see a couple minutes of propagation time on the download page.

**Comment by Coder206** [comment]
@edunham Thanks :)
