### ISSUE TITLE
Facebook signup button not displayed properly

### ISSUE THREAD

**Issue by bheesham** [servo/servo#12091]
Build: nightly - July 1, 2016.
Website: https://facebook.com/

Servo:
<img src="http://i.imgur.com/BtLXOyh.png" alt="Facebook signup button in Servo">

Chrome:
<img src="http://i.imgur.com/TwoS11H.png" alt="Facebook signup button in Chrome">

**Comment by ConnorGBrewster** [comment]
I have seen this on text inputs, and buttons on GitHub as well.

**Comment by bheesham** [comment]
Ah. Are there related issues for this then?

**Comment by ConnorGBrewster** [comment]
@bheesham not that I can recall, I have been meaning to file one for a while.

**Comment by nox** [comment]
<img width="263" alt="capture d ecran 2017-10-04 a 10 16 25" src="https://user-images.githubusercontent.com/123095/31165920-18db5370-a8ed-11e7-8955-9892e838889f.png">
