### ISSUE TITLE
GitHub login page not rendered properly

### ISSUE THREAD

**Issue by nickpsecurity** [servo/servo#12092]
![github screenshot forgot password](https://cloud.githubusercontent.com/assets/17504074/16528733/40cad690-3f84-11e6-948b-ca1ea00f8191.png)

Renders "forgot password" link in a weird way. Ubuntu 16.04 bare-metal running pre-packaged binary of Servo.

**Comment by Aaron1011** [comment]
I'd like to work on this.

**Comment by Aaron1011** [comment]
I believe I've narrowed the issue down to this:

```
<!DOCTYPE html>
<html>
<body>

<p>Password <a style="float: right;">Forgot password?</a></p>
<input style="width: 100%;" />

</body></html>
```

Here's what it looks like in Firefox 47:

![Firefox](https://i.imgur.com/8YYhGKe.png)

And here's the latest Servo:

![Server](http://i.imgur.com/5BQdPex.png)

From what I can tell, the root issue appears to be the large vertical gap that appears between the `<p>` and `<a>` elements which shoot be aligned vertically.

**Comment by KiChjang** [comment]
Unassigning due to inactivity for over 3 months.

**Comment by stshine** [comment]
Duplicate of #13683.
