### ISSUE TITLE
Reddit favicon displays with noise.

### ISSUE THREAD

**Issue by bheesham** [servo/servo#12094]
Build: nightly - 1 July 2016
Website: https://reddit.com/

The favicon above is for Mibbit, the second favicon is for reddit.
<img src="https://i.imgur.com/dgyMHvK.png" alt="Mibbit and reddit favicon">

**Comment by metajack** [comment]
That is a very interesting bug! Pinging the right people who might be able to track it down.

cc @paulrouget @pcwalton @glennw

**Comment by jdm** [comment]
This might be fixed by upgrading the image decoding library to pull in recent ICO decoding fixes.

**Comment by mbrubeck** [comment]
> This might be fixed by upgrading the image decoding library to pull in recent ICO decoding fixes.

Confirmed.
