### ISSUE TITLE
reddit.com stops loading with "e.postMessage is not a function" errors

### ISSUE THREAD

**Issue by hgallagher1993** [servo/servo#12106]
So this is my first issue created and first tangible contribution to Servo so if I've left anything needed out please say so :-)

First of all I'm not using the nightly, I cloned the Servo repository today (I don't know how to get the exact version number) and built in release mode and when I went to reddit [It only loaded some of the page and then loads no more](http://i.imgur.com/jYMuEVJ.png), the errors that are printed to the command window when reddit is loading are:

ERROR:js::rust: Error at https://www.redditstatic.com/gtm.aX_QHhLRPyo.js:0:4344: e.postMessage is not a function

ERROR:js::rust: Error at https://www.redditstatic.com/display.PGSStRgaC6w.js:0:4344: e.postMessage is not a function

Then when the page has loaded to what is in the screenshot this message keeps getting printed until Servo is closed

ERROR:js::rust: Error at https://www.redditmedia.com/ads/display/300x250#{"keywords":["s.brandlift.google","s.frontpage","k.wheel","k.us government","k.government","s.programmatic","s.loggedout","s.sfw"],"origin":"https://www.reddit.com","properties":{"age_hours":0,"pageType":"frontpage-listing"}}:6:1: window.parent.frames[frame] is undefined

Running on Mint 17.3 Cinnamon v.2.8.8 64-bit, kernel 3.16.0-25-generic...core i3 - 2310M, Intel 2nd generation integrated graphics

**Comment by jdm** [comment]
Testing the front page today, I see the whole thing load and none of those errors appear in the console. I certainly remember this being the case in the past, so I'm going to call this fixed. Thanks for reporting it!
