### ISSUE TITLE
Support building flatpak packages

### ISSUE THREAD

**Issue by moosingin3space** [servo/servo#12102]
This will make cross-distro packaging somewhat less of a headache.

I'd like to claim this issue -- just filing it here for tracking.

**Comment by aneeshusa** [comment]
I think this is a useful addition and would accept this, but I am not sure we want to have this as a Servo-supported packaging option. I think it may make more sense for this to be community-supported - I'd rather see native distro packaging (e.g. by Fedora) as the officially supported packing option (as well as our `.tar.gz`). Supporting every packaging format out there is not something I think is a good use of our resources. Thoughts?

**Comment by aneeshusa** [comment]
The other thing is that AFAIK the main problem that is causing cross-platform incompatibility with our package is the `libcrypto` and `libssl` library versions. We are planning to move to NSS, and once we do that I think our `.tar.gz` will run out of the box in most places.

**Comment by moosingin3space** [comment]
Flatpak is designed for upstream packaging - my thought is that it would make it more convenient to install on non-Ubuntu distributions as most either support it or have packages for flatpak.

**Comment by moosingin3space** [comment]
Oops accidental click.

**Comment by kxra** [comment]
@aneeshusa 

> I think it may make more sense for this to be community-supported - I'd rather point to native distro packaging (e.g. by Fedora) as the officially supported packaging option

This makes sense to me, but that won't be for a while since it isn't close to stable yet, right? 

> (as well as our .tar.gz for nightlies).

This makes less sense to me. Why wouldn't you want people to be able to use Flatpak to get nightly builds and keep them up to date?

**Comment by nox** [comment]
So, should we do this or not?

**Comment by jdm** [comment]
I don't think it's something that we're going to invest time in creating. I imagine we would accept PRs that caused us to generate flatpaks, but I don't think we need to track that work in our issue tracker.

**Comment by okias** [comment]
Ok, if anyone interested (but only running classic X11 session, no XWayland or Wayland support yet), you can give a shot to https://github.com/servo/servo/pull/28088

Have fun

**Comment by okias** [comment]
> Hi @okias I've attempted to use your changes to build a Flatpak bundle but I'm getting an error (checked out https://github.com/servo/servo/commit/8e1ce879d51a058b5991a9aca06e4e3200857206):

Hey, there was some discussion about dropping mach for generic builds and using `cargo` directly, so I waited a bit before I'll continue with the work. I plan to get back to it soon.

**Comment by yookoala** [comment]
Made a repo to build the manifest for building / installing flatpak:
https://github.com/yookoala/servo-flatpak/

If you're looking for solution to build and install Servo's demo browser as flatpak, please try this out.
