### ISSUE TITLE
Update gentoo linux setup instructions 

### ISSUE THREAD

**Issue by scitecwri** [servo/servo#12107]
In https://github.com/servo/servo/blob/master/README.md

Add  media-fonts/fira-sans media-fonts/dejavu to emerge list for Gentoo Linux

**Comment by Obikawa** [comment]
Is this related to issue #12139 ?

Also, when I saw the installation instruction, i chose a more fitting, Gentoo specific way to install those dependencies, which is to add them to a new set and emerge said set instead.

**Comment by Eijebong** [comment]
Same on arch, seems like you need the ttf-fira-sans package for servo to work.

**Comment by nox** [comment]
@Eijebong Think you could do a PR for that?

**Comment by Eijebong** [comment]
I'd have to try it again but yeah, sure. I'll do it tomorrow unless someone else wants to do it :p

**Comment by dralley** [comment]
I don't think this is still necessary, the issue can most likely be closed.
