### ISSUE TITLE
Pick wrong link on Reddit

### ISSUE THREAD

**Issue by dumindu** [servo/servo#12105]
https://youtu.be/USXWZOldhVo
### Way to reproduce
1. open servo
2. click on Reddit icon on new tab page
3. edit link to reddit.com/r/rust
4. click on the 4th link on the list
### current result

open 5th link on the list
### expected result

should open the correct link

**Comment by moosingin3space** [comment]
I encountered this same issue on HN, but it is inconsistent.

**Comment by paulrouget** [comment]
That's … interesting. Links are swapped? So it's not a hittest issue.

**Comment by nox** [comment]
See manual test case in https://github.com/servo/servo/issues/18164#issuecomment-328722355.

**Comment by dralley** [comment]
This appears to be fixed with both Hacker News and the minimal test case in the linked issue.
