### ISSUE TITLE
No HiDPI support under Gnome 3.20

### ISSUE THREAD

**Issue by stoatally** [servo/servo#12110]
According to issue #500 HiDPI/retina display support has been implemented at least to some extent, however it does not work on my Arch Linux computer running Gnome 3.20:

[![Example](http://i.imgur.com/MrRGCTq.png)](http://i.imgur.com/MrRGCTq.png)

**Comment by moosingin3space** [comment]
Have you tried the `--device-pixel-ratio=2.0` argument? (replacing `2.0` with any scale factor)

**Comment by stoatally** [comment]
Yeah, that argument works, it's just not automatic, not sure if anyone cares at this point.

**Comment by moosingin3space** [comment]
I think I know how to make it automatic on Gnome, but it wouldn't be portable to other DEs. Can a core team member comment on whether a Gnome-specific fix would be acceptable?

**Comment by ConnorGBrewster** [comment]
Thank you for the report, this is being tracked in #12054.
