### ISSUE TITLE
Android should unpack the resources/ folder on first run

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#12129]
Servo has a `resources` folder, which we place into the `assets` folder when building the apk (see: https://github.com/servo/servo/blob/master/support/android/build-apk/src/main.rs#L84-L96 ).

On first launch on the device, we should attempt to unpack that folder into the same location as where the application has been installed.

**Comment by zhuowei** [comment]
Should this be done in Java or in Rust code?

**Comment by larsbergstrom** [comment]
My thought was that this could be done in Java at startup. That is, the Java code that runs when the app is launched can check to see if the assets have already been unpacked. If not, it could go ahead and do so.

**Comment by zhuowei** [comment]
thanks! Also, how should it know when to re-extract the resources folder after an update?

**Comment by larsbergstrom** [comment]
@zhuowei Great question! I didn't have any thoughts on this. I'd imagine you could either:
1) Store the resources in a versioned folder
2) Emit a version file 

@mbrubeck Do you have any advice/tips here on best practices for resource extraction and ensuring it's all done correctly when an APK is upgraded?

**Comment by meecoffee** [comment]
android nighlty apk？long time passed

**Comment by jdm** [comment]
@meecoffee Please follow the progress in #12130. There's no point in publishing a nightly that doesn't actually work well.
