### ISSUE TITLE
Double escaping in rendering https://security.googleblog.com/

### ISSUE THREAD

**Issue by alex** [servo/servo#12126]
Servo:

![screen shot 2016-07-01 at 4 03 47 pm](https://cloud.githubusercontent.com/assets/772/16533259/70d31eb2-3fa5-11e6-8a38-e4e8e3fecf61.png)

Chrome:

![screen shot 2016-07-01 at 4 03 44 pm](https://cloud.githubusercontent.com/assets/772/16533258/70d09ec6-3fa5-11e6-996f-b2db09a39dbc.png)

**Comment by Ms2ger** [comment]
They do something... special:
```html
<script type='text/template'>
                          <span class="byline-author">Posted by Quan To, Program Manager, Android Security</span><br />
<br />
```

Probably one of the script errors is related
```
ERROR:js::rust: Error at https://security.googleblog.com/:4:7: document.write is not a function

ERROR:js::rust: Error at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.nl.dkNeZpYUkMk.O/m=debug_error/exm=plusone/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNlBSMYL7yr3ukzFRSlcyUIbsY3lw/cb=gapi.loaded_1:14:29: _.d is not a function


ERROR:js::rust: Error at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.nl.dkNeZpYUkMk.O/m=ytsubscribe/exm=debug_error,plusone/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNlBSMYL7yr3ukzFRSlcyUIbsY3lw/cb=gapi.loaded_2:1:1: _.Sm is undefined

ERROR:js::rust: Error at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.nl.dkNeZpYUkMk.O/m=auth/exm=debug_error,plusone,ytsubscribe/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNlBSMYL7yr3ukzFRSlcyUIbsY3lw/cb=gapi.loaded_3:38:212: _.pf is not a function

ERROR:js::rust: Error at https://apis.google.com/js/plusone.js:44:876: a is undefined
```

**Comment by alex** [comment]
Perhaps this is just a specific case of #3704 then?

**Comment by jdm** [comment]
I suspect the `<script type='text/template'>` is visible on the page when it shouldn't be. We should fix that if it's the case.

**Comment by nox** [comment]
I don't think that's the issue at hand, otherwise the actual article would also be printed somewhere, no?

**Comment by nox** [comment]
Browsing the blog still reproduces this issue, btw.

**Comment by jdm** [comment]
I bet this would be fixed by #17896.

**Comment by krk** [comment]
The issue cannot be reproduced with the latest, dd2deeabca7eeb40e6a8fe0c1ee4550d64e0c235

**Comment by jdm** [comment]
Thanks!
