### ISSUE TITLE
python.org badly misrendering

### ISSUE THREAD

**Issue by alex** [servo/servo#12124]
Servo:

![screen shot 2016-07-01 at 4 01 42 pm](https://cloud.githubusercontent.com/assets/772/16533217/25e20576-3fa5-11e6-9608-5ef9340d225f.png)

Chrome:

![screen shot 2016-07-01 at 4 01 50 pm](https://cloud.githubusercontent.com/assets/772/16533218/25ee65f0-3fa5-11e6-9ea6-4d4fb0e7a39d.png)

**Comment by paulrouget** [comment]
This is not really actionable.

Can you break down the different problems in different issues with reduced test cases?
See https://github.com/servo/servo/wiki/WebCompatBug

**Comment by jdm** [comment]
@paulrouget The action is breaking it down into minimal testcases ;)
