### ISSUE TITLE
Can't submit bug reports with bug reporter

### ISSUE THREAD

**Issue by stratacast** [servo/servo#12121]
The built in servo bug reporter tries to compile a large amount of bug report information into the URL, so github produces an error of too large of a URL, so I can't submit errors.

I got an "assertion failed: address != MAP_FAILED" error testing a youtube video, and got the error as well as a backtrace.

![servo submit report](https://cloud.githubusercontent.com/assets/14900584/16532585/b200a008-3f87-11e6-9c1d-73ad75a925a9.png)

EDIT: I magically got one to work after I posted this, but it failed 9 of 10 tries. Here is the URL

https://github.com/servo/servo/issues/new?title=called%20%60Result%3A%3Aunwrap()%60%20on%20an%20%60Err%60%20value%3A%20IdnaError&body=%0Acalled%20%60Result%3A%3Aunwrap()%60%20on%20an%20%60Err%60%20value%3A%20IdnaError%0A%23%23%23%20URL%3A%0Ahttps%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DmXK8exz609Y%0A%23%23%23%20Backtrace%3A%0A%60%60%60%0Aframe%20%230%20%20-%200x000055d263427a0d%20-%20backtrace%3A%3Abacktrace%3A%3Atrace%3A%3Ahccde8df28b4db2a2%0Aframe%20%231%20%20-%200x000055d263427995%20-%20backtrace%3A%3Acapture%3A%3ABacktrace%3A%3Anew%3A%3Ah42f95930bb8c5ee8%0Aframe%20%232%20%20-%200x000055d2625f9379%20-%20_%3CF%20as%20alloc..boxed..FnBox%3CA%3E%3E%3A%3Acall_box%3A%3Ahc555946005547ceb%0Aframe%20%233%20%20-%200x000055d26341e818%20-%20util%3A%3Apanicking%3A%3Ainitiate_panic_hook%3A%3A_%24u7b%24%24u7b%24closure%24u7d%24%24u7d%24%3A%3A_%24u7b%24%24u7b%24closure%24u7d%24%24u7d%24%3A%3Ahc61828c8a9f6df01%0Aframe%20%234%20%20-%200x000055d263525dcc%20-%20std%3A%3Apanicking%3A%3Arust_panic_with_hook%3A%3Ah983af77c1a2e581b%0Aframe%20%235%20%20-%200x000055d2635403e1%20-%20std%3A%3Apanicking%3A%3Abegin_panic%3A%3Ahe426e15a3766089a%0Aframe%20%236%20%20-%200x000055d26352763a%20-%20std%3A%3Apanicking%3A%3Abegin_panic_fmt%3A%3Ahdddb415186c241e7%0Aframe%20%237%20%20-%200x000055d26354037e%20-%20rust_begin_unwind%0Aframe%20%238%20%20-%200x000055d26357697f%20-%20core%3A%3Apanicking%3A%3Apanic_fmt%3A%3Ahf4e16cb7f0d41a25%0Aframe%20%239%20%20-%200x000055d2623f8822%20-%20core%3A%3Aresult%3A%3Aunwrap_failed%3A%3Ahf81255c6633560f3%0Aframe%20%2310%20-%200x000055d26249c1d7%20-%20_%3Cscript..dom..htmlimageelement..HTMLImageElement%20as%20script..dom..virtualmethods..VirtualMethods%3E%3A%3Aattribute_mutated%3A%3Ah16a0ae8a7220214f%0Aframe%20%2311%20-%200x000055d26242a03d%20-%20script%3A%3Adom%3A%3Aelement%3A%3AElement%3A%3Apush_attribute%3A%3Ah5dd2c038977ee96b%0Aframe%20%2312%20-%200x000055d26242996f%20-%20script%3A%3Adom%3A%3Aelement%3A%3AElement%3A%3Apush_new_attribute%3A%3Ahaf1b86a9a73fbde5%0Aframe%20%2313%20-%200x000055d2623ee261%20-%20script%3A%3Adom%3A%3Aelement%3A%3AElement%3A%3Aset_attribute%3A%3Aha048dbd45e19292e%0Aframe%20%2314%20-%200x000055d26242c0f8%20-%20script%3A%3Adom%3A%3Aelement%3A%3AElement%3A%3Aset_string_attribute%3A%3Ahc855c809a2045471%0Aframe%20%2315%20-%200x000055d2620cab6d%20-%20_%3Cscript..dom..htmlimageelement..HTMLImageElement%20as%20script..dom..bindings..codegen..Bindings..HTMLImageElementBinding..HTMLImageElementMethods%3E%3A%3ASetSrc%3A%3Ah1164c66e72df0d36%0Aframe%20%2316%20-%200x000055d2620caae7%20-%20std%3A%3Apanicking%3A%3Atry%3A%3Acall%3A%3Ahaf35748432c56501%0Aframe%20%2317%20-%200x000055d26354a5db%20-%20__rust_try%0Aframe%20%2318%20-%200x000055d26354a57e%20-%20__rust_maybe_catch_panic%0Aframe%20%2319%20-%200x000055d2620ca963%20-%20script%3A%3Adom%3A%3Abindings%3A%3Acodegen%3A%3ABindings%3A%3AHTMLImageElementBinding%3A%3Aset_src%3A%3Ahbb2b188b68906b89%0Aframe%20%2320%20-%200x000055d26275b232%20-%20CallJitSetterOp%0Aframe%20%2321%20-%200x000055d261e7c0a8%20-%20script%3A%3Adom%3A%3Abindings%3A%3Autils%3A%3Acall_setter%3A%3Ahd77e5ce489309de4%0Aframe%20%2322%20-%200x000055d261e7bf85%20-%20script%3A%3Adom%3A%3Abindings%3A%3Autils%3A%3Ageneric_call%3A%3Ahde0488eddacd8648%0Aframe%20%2323%20-%200x000055d262ae1590%20-%20CallJSNative%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fjscntxtinlines.h%3A235%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%202js6InvokeEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FInterpreter.cpp%3A476%0Aframe%20%2324%20-%200x000055d262ae26f0%20-%202js6InvokeEP9JSContextRKN2JS5ValueES5_jPS4_NS2_13MutableHandleIS3_E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FInterpreter.cpp%3A528%0Aframe%20%2325%20-%200x000055d262ae28f7%20-%202js12InvokeSetterEP9JSContextRKN2JS5ValueES3_NS2_6HandleIS3_E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FInterpreter.cpp%3A649%0Aframe%20%2326%20-%200x000055d262af9761%20-%20SetExistingProperty%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FNativeObject.cpp%3A2352%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%202js17NativeSetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_I4jsidEENS3_INS2_5ValueEEESA_NS_13QualifiedBoolERNS2_14ObjectOpResult%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FNativeObject.cpp%3A2386%0Aframe%20%2327%20-%200x000055d262ade0d7%20-%20SetProperty%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FNativeObject.h%3A1494%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%20SetPropertyOperation%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FInterpreter.cpp%3A284%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%20Interpret%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FInterpreter.cpp%3A2604%0Aframe%20%2328%20-%200x000055d262ae10fc%20-%202js9RunScriptEP9JSContextRNS_8RunState%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FInterpreter.cpp%3A426%0Aframe%20%2329%20-%200x000055d262ae3447%20-%20_ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_16AbstractFramePtrEPS9_%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FInterpreter.cpp%3A684%0Aframe%20%2330%20-%200x000055d262ae3546%20-%202js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5Value%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fvm%2FInterpreter.cpp%3A717%0Aframe%20%2331%20-%200x000055d26299e219%20-%20Evaluate%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fjsapi.cpp%3A4467%0Aframe%20%2332%20-%200x000055d26299e641%20-%20Evaluate%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fjsapi.cpp%3A4503%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%202JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEE%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%40%20%2Fhome%2Fservo%2F.cargo%2Fgit%2Fcheckouts%2Fmozjs-fa11ffc7d4f1cc2d%2Fmaster%2Fmozjs%2Fjs%2Fsrc%2Fjsapi.cpp%3A4561%0Aframe%20%2333%20-%200x000055d261e76058%20-%20_%3C%26%27a%20T%20as%20script..dom..window..ScriptHelpers%3E%3A%3Aevaluate_script_on_global_with_result%3A%3Ah6003189afa9633b6%0Aframe%20%2334%20-%200x000055d2623f40d7%20-%20script%3A%3Adom%3A%3Ahtmlscriptelement%3A%3AHTMLScriptElement%3A%3Aexecute%3A%3Ahb1197b49bf035429%0Aframe%20%2335%20-%200x000055d261e585e0%20-%20script%3A%3Adom%3A%3Adocument%3A%3ADocument%3A%3Afinish_load%3A%3Ahea8fb9e3713be828%0Aframe%20%2336%20-%200x000055d2624ae1ee%20-%20_%3Cscript..dom..htmllinkelement..StylesheetContext%20as%20net_traits..AsyncResponseListener%3E%3A%3Aresponse_complete%3A%3Ah71d7672a3472afa1%0Aframe%20%2337%20-%200x000055d2624abfbb%20-%20_%3Cscript..network_listener..ListenerRunnable%3CA%2C%20Listener%3E%20as%20script..script_thread..Runnable%3E%3A%3Ahandler%3A%3Ah724ec798d0dfe84e%0Aframe%20%2338%20-%200x000055d2626042c4%20-%20script%3A%3Ascript_thread%3A%3AScriptThread%3A%3Ahandle_msg_from_script%3A%3Ahfac8a5d67415fa31%0Aframe%20%2339%20-%200x000055d26265590f%20-%20script%3A%3Ascript_thread%3A%3AScriptThread%3A%3Ahandle_msgs%3A%3A_%24u7b%24%24u7b%24closure%24u7d%24%24u7d%24%3A%3Ahcc3e5fcf08d42e0c%0Aframe%20%2340%20-%200x000055d26263caf7%20-%20script%3A%3Ascript_thread%3A%3AScriptThread%3A%3Ahandle_msgs%3A%3Ahf9fbf9949e23273b%0Aframe%20%2341%20-%200x000055d2625f7a67%20-%20std%3A%3Apanicking%3A%3Atry%3A%3Acall%3A%3Ah99112171a9854ab3%0Aframe%20%2342%20-%200x000055d26354a5db%20-%20__rust_try%0Aframe%20%2343%20-%200x000055d26354a57e%20-%20__rust_maybe_catch_panic%0Aframe%20%2344%20-%200x000055d2625f8cdd%20-%20_%3CF%20as%20alloc..boxed..FnBox%3CA%3E%3E%3A%3Acall_box%3A%3Ah4410a344b31b72da%0Aframe%20%2345%20-%200x000055d26353e5a4%20-%20std%3A%3Asys%3A%3Athread%3A%3AThread%3A%3Anew%3A%3Athread_start%3A%3Ah9c883b6d445ece46%0Aframe%20%2346%20-%200x00007f54ba6a26f9%20-%20start_thread%0Aframe%20%2347%20-%200x00007f54ba1c2b5c%20-%20clone%0Aframe%20%2348%20-%200x0000000000000000%20-%20%3Cunknown%3E%0A%0A%60%60%60%0A

**Comment by ConnorGBrewster** [comment]
We should set a max backtrace length when generating the github issue link.

**Comment by nox** [comment]
Probably same issue as #12122. Closing.

**Comment by jdm** [comment]
#12122 is an error report for a particular site. This is an error report for the browser.html error reporter, which belongs in https://github.com/browserhtml/browserhtml/issues instead.
