### ISSUE TITLE
How to test transitions/animations?

### ISSUE THREAD

**Issue by emilio** [servo/servo#12120]
As animation support increases, it'd be great to have some sort of testing support for it.

We can't test them deteministically right now. Gecko has a "test mode" in their refresh driver that allows them to fake the times, advance the clocks, etc. as well as an API to get the computed style for an element in a given point of time.

We don't have that infra, and though it seems like a good amount of work, I think it's worth doing.

**Comment by emilio** [comment]
So the idea I'm thinking about is adding a pref or something as we do to test our crash handler, but adding:

1. A test mode to the constellation that allows us to trigger animation ticks on-demand.
2. A pref-guarded API that allows us to "move" the clock by a delta, and trigger an animation tick.

I think that should be enough to be able to write a bunch of animation tests under `tests/mozilla`.

CC'ing @Ms2ger and @jdm just in case they have thoughts on this or maybe a better way to do it :)

**Comment by jdm** [comment]
No better idea!

**Comment by metajack** [comment]
:+1:

**Comment by emilio** [comment]
A potential implementation of this lives in #12392
