### ISSUE TITLE
Emberjs.com is missing nearly all the text

### ISSUE THREAD

**Issue by moosingin3space** [servo/servo#12132]
![screenshot from 2016-07-01 13 32 51](https://cloud.githubusercontent.com/assets/830082/16533857/8ad6a140-3f90-11e6-8942-af1436a46b1d.png)

Screenshot taken on Ubuntu 14.04.4. The console output was:

```
Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
DEBUG: -------------------------------
DEBUG: Ember  : 2.4.1
DEBUG: jQuery : 2.1.3
DEBUG: -------------------------------
ERROR:js::rust: Error at :0:1: document.write is not a function
```

When I scrolled down the page, no text was displayed.

**Comment by fabricedesre** [comment]
Pretty sure this is because of the missing support for `document.write`

**Comment by metajack** [comment]
wat? @wycats why is the text dependent on document.write? :)

**Comment by nox** [comment]
WAIT, I DID THIS

<img width="1136" alt="capture d ecran 2017-10-04 a 09 58 25" src="https://user-images.githubusercontent.com/123095/31165235-9bdbdcfc-a8ea-11e7-8ef0-10b762706d29.png">
