### ISSUE TITLE
Address bar rendering wrong case

### ISSUE THREAD

**Issue by munyari** [servo/servo#12131]
Typing in the address bar and servo acts as if I am holding down the shift key. When I type `servo.org` I get `SERVO>ORG`, which is corrected to `servo>ORG` (`.` and `>` share the seem key on my keyboard). In the console:

```
Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
ERROR:js::rust: Error at file:///user/builds/servo/build/browserhtml-3e3805f69808f24d/out/components/main.js:7:13639: e.matches[e.items[e.selected]] is undefined
```

**Comment by mbrubeck** [comment]
Thanks for the report. What operating system are you using, and what keyboard layout (for example "U.S. English" or "French AZERTY" etc.)?

**Comment by munyari** [comment]
Arch Linux, Linx 4.6.2-1-ARCH, U.S. keyboard. Servo version was the latest nightly

**Comment by Coder206** [comment]
I am experiencing similar behavior to with bhtml's auto correct.

**Comment by halfpastfive** [comment]
Hi ! 
I have the same issue on OS X.

OS : OSX 10.11.3
Keyboard : french (azerty) 
build : latest nightly
In fact, the keyboard stays in qwerty,  but with an incorrect key mapping (even for qwerty).

**Comment by nox** [comment]
This was fixed a while ago.
