### ISSUE TITLE
Servo Multiple monitors

### ISSUE THREAD

**Issue by bitpacket** [servo/servo#12142]
Hi its looking really slick

I have a 3 monitor mac setup using macOS Sierra

1x 27" LED Cinema Display (2560x1440)
1x 27" Thunderbolt Display(2560x1440)
1 x 15" macbookpro retina in scaled mode (virtual res of 1680x1050)

when I drag the windows from the macbookpro to the large displays the window increases in size by around double and the window controls stop working. I can drag but nothing else until I put it back onto the macbookpro screen... It looks like its the display controller as the displays keep the window at the same scale on drag until the screen leaves the macbookpro, once the screen is on the larger LED or thunderbolt displays it doubles the window size.

have attached some screen grabs

![screen shot 2016-07-02 at 10 42 25 am](https://cloud.githubusercontent.com/assets/10970184/16536106/e2acf8fe-4041-11e6-9e8e-98598eac7d6a.png)
![screen shot 2016-07-02 at 10 42 54 am](https://cloud.githubusercontent.com/assets/10970184/16536107/e2adcec8-4041-11e6-9f49-c4b55a5d68c5.png)
<img width="1673" alt="screen shot 2016-07-02 at 10 43 18 am" src="https://cloud.githubusercontent.com/assets/10970184/16536105/e2ac05de-4041-11e6-9376-c687f19693e0.png">

**Comment by jdm** [comment]
This is being tracked in #12010. Thanks for reporting it!
