### ISSUE TITLE
thread '<unnamed>' panicked at 'Failed to rasterize the glyph?'

### ISSUE THREAD

**Issue by kilobyte** [servo/servo#12143]
Reproducible crash on Linux amd64, Debian unstable:
Go to https://angband.pl/doc/alluni.txt then scroll down.  It's a test of all simple printable non-combining/etc Unicode characters.  Somewhere around U+3A00 servo crashes:
[backtrace.txt](https://github.com/servo/servo/files/344278/backtrace.txt)

Sometimes there's a lockup while loading the file, in that case there's no message nor a backtrace, the window becomes black when it would be redrawn.

**Comment by kilobtye** [comment]
Does not panic on my ubuntu 16.04 machine.

But I noticed many characters are displayed as two or three �(U+FFFD). I don't know if this is a known issue? I think maybe somehow the text is cut in the middle of a utf-8 character, causing a  2 or 3 bytes utf-8 character became 2 or 3 invalid utf-8 characters.

**Comment by kilobyte** [comment]
Tried in fresh VMs: crash on Debian stretch (upcoming release), no crash on jessie (stable).

**Comment by kilobyte** [comment]
Current nightly build doesn't crash for me, but I guess it's not because of this bug having been fixed, but because most codepoints fail to render, showing a replacement symbol instead (I have fonts for everything but Tangut, Sutton, and plane 2 CJK installed, and Firefox renders them correctly).  In particular, the region around U+3A00 that used to crash doesn't render.

**Comment by nox** [comment]
I can't reproduce the crash anymore, closing this in favour of #17267 for the replacement character issues.

**Comment by kilobyte** [comment]
It's likely the crash is not fixed, merely covered by the other bug.  But yeah, Servo's codebase has changed a lot since the report, if the problem is still there we can reopen then.

That test file is worth keeping, even if it doesn't include any combining character tests.
