### ISSUE TITLE
Explicitly specify MIME types in etc/ci/upload_nightly.sh

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#12153]
We should explicitly specify the MIME type when we upload our nightly builds to S3 instead of letting s3cmd guess. AFAIK, we can just use `application/octet-stream` for all of our nightlies.

Example warning (from http://build.servo.org/builders/mac-nightly/builds/7/steps/shell_2/logs/stdio):
```
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
```

Docs: http://s3tools.org/usage

Files:
- etc/ci/upload_nightly.sh

No need for a test.

**Comment by jimberlage** [comment]
I'll work on this if you want.

**Comment by ConnorGBrewster** [comment]
@jimberlage please do!
