### ISSUE TITLE
Add basic linting for etc/ci/ shell scripts

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#12158]
Some good places to start:
- Check that all lines are 80 characters or less (Servo uses 120 for Rust code, but shell scripts IMO don't need that much horizontal space)
- Check for the correct shebang and bash options at the top (see the [shell section of the style guide](https://github.com/servo/servo/blob/master/docs/STYLE_GUIDE.md#shell-scripts))

Came up while reviewing #12156.
I would like for this to be part of tidy so it is checked during `./mach test-tidy`.

Files:
- python/tidy/servo_tidy/tidy.py

Add one or more tests in the python/tidy/servo_tidy_tests/ directory as well.

**Comment by jimberlage** [comment]
Why don't I work on this, since my PR was the one to miss the style guidelines 😄

**Comment by aneeshusa** [comment]
Go for it! Beware though, you'll need to fix up all of the other scripts that were added previously (I think many of those also fail to conform to these guidelines) :)

**Comment by jimberlage** [comment]
I've got most things tidied up, but I do have one question - how do you want to deal with license checks for shell scripts?  Right now we have this:

```
jberlage$ ./mach test tidy --tidy-all
Checking files for tidiness...
./components/servo/fake-ld.sh:1: incorrect license
./etc/ci/check_no_unwrap.sh:1: incorrect license
./etc/ci/lockfile_changed.sh:1: incorrect license
./etc/ci/manifest_changed.sh:1: incorrect license
./etc/ci/upload_docs.sh:1: incorrect license
./etc/ci/upload_nightly.sh:1: incorrect license
  Progress: 100% (8667/8667)
Running the WPT lint...
  Progress: 100% (19686/19686)
Tests completed in 57.76s
```

I'm not sure what license should be used, if any.

**Comment by jimberlage** [comment]
@aneeshusa any thoughts?

**Comment by aneeshusa** [comment]
I think MPL 2.0 should be fine (with the `/usr/bin/env bash` shebang - I think you'll need to add that variation to the license checker). cc @larsbergstrom about licensing
