### ISSUE TITLE
URL bar autocomplete is annoying

### ISSUE THREAD

**Issue by suhr** [servo/servo#12174]
When you press arrow key (←) to fix a typo it makes completed text persistent so you have to remove it.
Then you type text in the middle of word, it autocompletes the end.
Also it blinks while it really should not to.

Servo/browserhtml: nightly build.

Additional info: Yandex is a good example how proper autocomplete looks like. Everything is instant, completion is grey and becomes a text only when you push → or Tab.

**Comment by LifeIsStrange** [comment]
Maybe that I say something stupid but you should probably take some code and ideas from this library:
https://github.com/algolia/places
Or even use it, and you will benefit of free updates.

**Comment by suhr** [comment]
@LifeIsStrange Yandex style autocomplete is better tbh.

**Comment by mason-larobina** [comment]
My experience: typing faster than the auto-complete handler will insert characters in the wrong place.

For example typing my last name "larobina" frequently results in "larobian" or "larobian spencer" despite not pressing ←, → or Tab.

**Comment by ConnorGBrewster** [comment]
@mason-larobina that issue is tracked over on browserhtml/browserhtml#1157. Hopefully we can have a fix for it soon.

**Comment by mason-larobina** [comment]
Awesome, thanks Connor!

**Comment by jdm** [comment]
I believe every issue mentioned here is belongs in the issue tracker for https://github.com/mozilla/browser.html/, which is responsible for the UI of Servo nightlies. Thank you for reporting them!
