### ISSUE TITLE
New tab order.

### ISSUE THREAD

**Issue by mason-larobina** [servo/servo#12177]
Opening a new tab counter-intuitively places the new tab index at 0.

For example with the following tabs open and tab index 1 active:

```
0: google.com
1: reddit.com [active]
```
Pressing `Ctrl+T` (open new tab) results in:

```
0: new-tab [active]
1: google.com
2: reddit.com
```

And a subsequent `Ctrl+W` (close tab) does nothing.

I would have expected the following behaviour on `Ctrl+T`:

```
0: google.com
1: reddit.com
2: new tab [active]
```

And `Ctrl+W` to return to the original state:

```
0: google.com
1: reddit.com
```

Thanks!

(I'm loving the publishing of the servo nightly binaries).

**Comment by ConnorGBrewster** [comment]
@mason-larobina glad to hear you are enjoying the nightlies!
The Crtl-W doing nothing is an issue I have ran into, bhtml stops listening for key command, my usual workaround is to activate/deactivate the url bar and the key commands work again.

As for the newtab, it is currently set up to always have the newtab at the top, might be something you want to open an issue about over at [browserhtml](https://github.com/browserhtml/browserhtml), as I personally would like it to behave how you expect it to.

**Comment by mason-larobina** [comment]
Gotcha, I'll move it over to browserhtml.

Thanks!
