### ISSUE TITLE
Image cache thread uses unwrap unnecessarily

### ISSUE THREAD

**Issue by jdm** [servo/servo#12173]
There are various uses in `handle_cmd` where we unwrap the result of a `send()` - we should just ignore the result with `let _ =` instead. This prevents the image cache thread from panicking if it tries to communicate with another thread that has panicked.

Code: `components/net/image_cache_thread.rs`

No need for automated tests here; if it builds, that's good enough.

**Comment by andrebeat** [comment]
I have created a PR to fix this.
