### ISSUE TITLE
OpenGL related crashes on OSX Yosemite with Intel card

### ISSUE THREAD

**Issue by lqd** [servo/servo#12179]
The Servo and Github links on Servo's start page are crashing the app, on OSX 10.10.5 and mid-2011 macbook air (Intel HD Graphics 3000)

Crash report: https://gist.github.com/lqd/7dad172f5c6b998bb9adb1b2295eab2a

**Comment by lqd** [comment]
Log from run-servo:
Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
ERROR:js::rust: Error at https://assets-cdn.github.com/assets/frameworks-f2de4c863a487a877150989f965232bacfde178abf9c1963d9f84c5c19916f0c.js:6:2035: history is not defined

ERROR:js::rust: Error at https://assets-cdn.github.com/assets/frameworks-f2de4c863a487a877150989f965232bacfde178abf9c1963d9f84c5c19916f0c.js:1:18383: Could not find module github/inspect

Abort trap: 6
logout

**Comment by lqd** [comment]
After building servo locally, I was able to make it crash with a debug build, and there was nothing more in the console.
And actually, all the errors in my previous comment were either printed at launch (first 2) or when loading github (js errors), that is, way before the crash.

At some point during my testing there also was this message in the console "Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322"

I wasn't able to repro the crash easily, and I tried with and without bhtml, with and without webrender. It does happen with webrender (which is somewhat expected since it seems GL-related), with or without bhtml — the screen isn't black nor has artifacts, and it beachballs a lot before the crash (but that doesn't seem to happen with the released nightly however, only my debug build)

Don't hesitate if there's something more I can do to help debug the issue.

**Comment by emilio** [comment]
Hi @lqd, thanks for your super-complete report! :)

I think @pcwalton could be interested on this, it seems to happen in [`deinit_texture`](https://github.com/servo/webrender/blob/1ce30fe66de3782100755ca6e088bd6a595d45bd/src/device.rs#L1193) in webrender.

**Comment by nox** [comment]
Does this still happen, @lqd?

**Comment by lqd** [comment]
Tried it again n the same computer/gpu, using the latest packaged nightly (Servo 0.0.1-82cc22f), but on osx 10.12.6 this time: neither of those 2 links crash anymore :)

**Comment by nox** [comment]
Nice! Closing.
