### ISSUE TITLE
Unable to execute ./runservo.sh on Ubuntu 16.04

### ISSUE THREAD

**Issue by jc00ke** [servo/servo#12181]
I downloaded today's nightly and got the following error:

```
➜ servo ./runservo.sh 
Failed to execute process './runservo.sh'. Reason:
exec: Exec format error
The file './runservo.sh' is marked as an executable but could not be run by the operating system.
```

```
Linux kendrick 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lfairy** [comment]
It works when you add `#!/bin/sh` to the beginning of the file. Not sure why that line isn't there already.

**Comment by nzod** [comment]
The shebang line is already present.
It does take a minute to start up but executing runservo.sh works for me. (Ubu 16.04)

**Comment by Jan-Kow** [comment]
@jc00ke Why do you type in ``servo`` in front? What happens if you just type ``./runservo.sh``?

**Comment by Jan-Kow** [comment]
@nzod Thought that to but it looks like he's trying to run the servo executable and ``. /runservo.sh`` as an argument :D

Sounds pretty strange but try use another shell, just like Ubuntu's integrated Terminal or XTerm. I looked up the error on google and found out that this happens to many scripts when trying to execute them using fish-shell.

**Comment by jc00ke** [comment]
`servo` is the dir name in my `fish` shell.

@Jan-Kow is correct, it's something with `fish`

```
➜ servo echo $SHELL 
/usr/bin/fish
➜ servo file runservo.sh 
runservo.sh: ASCII text
➜ servo cat runservo.sh 
./servo -w -b --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref shell.builtin-key-shortcuts.enabled=false ./build/browserhtml-3e3805f69808f24d/out/index.html
➜ servo ./runservo.sh 
Failed to execute process './runservo.sh'. Reason:
exec: Exec format error
The file './runservo.sh' is marked as an executable but could not be run by the operating system.
➜ servo sed -i '1i#!/bin/bash' runservo.sh
➜ servo file runservo.sh 
runservo.sh: Bourne-Again shell script, ASCII text executable
➜ servo ./runservo.sh 
Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
➜ servo 
```

I've never seen an executable script w/o a `#!` line and it looks like it was added in #12020 so I'll close.

fish-shell/fish-shell#1281
