### ISSUE TITLE
Avoid many uses of unwrap in font_cache_thread.rs

### ISSUE THREAD

**Issue by jdm** [servo/servo#12188]
There are many uses of `unwrap()` on the result of sending data to another thread. We should replace those with `let _ =` instead, since we don't need to care if the target thread no longer exists. This will avoid the font cache thread panicking if another thread that it is communicating with panics.

Code: `components/gfx/font_cache_thread.rs`

No need for automated tests; if it compiles, that's good enough.

**Comment by hgallagher1993** [comment]
Ya I'll pick this one up

**Comment by ConnorGBrewster** [comment]
@hgallagher1993 its all yours! (for real this time 😉)

**Comment by hgallagher1993** [comment]
@jdm I'm just looking at this issue now and I'm just wondering if I have this right. There's a few `result.send(...blah...).unwrap()` in the match statement of `impl FontCache` (line 160), I just have to change them ones to `let _ = result.send(...blah...);`?

@ConnorGBrewster Thanks, I'll have this one finished post haste :sunglasses:

**Comment by jdm** [comment]
@hgallagher1993 Yes, that's exactly right.
