### ISSUE TITLE
Basic `display: flex` layout is not supported

### ISSUE THREAD

**Issue by shepmaster** [servo/servo#12191]
A very basic usage of flexbox doesn't seem to work, contrary to what #7154 / #7312 seem to indicate.
## To reproduce

Save this HTML and open it:

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Flexbox Example</title>
  </head>
  <body>
    <div class="container" style="display: flex">
      <div class="item" style="color: red">Item1</div>
      <div class="item" style="color: blue">Item2</div>
      <div class="item" style="color: green">Item3</div>
    </div>
  </body>
</html>
```
## What I expected:

**Chrome 54.0 (canary)**
<img width="128" alt="flexbox-chrome-54 0-canary" src="https://cloud.githubusercontent.com/assets/174509/16543378/c93714f0-409f-11e6-93d6-7c7cc43e551c.png">
**Firefox 47.0**
<img width="143" alt="flexbox-firefox-47 0" src="https://cloud.githubusercontent.com/assets/174509/16543380/c93a40a8-409f-11e6-88ba-add2ae181916.png">
**IE 11**
![flexbox-ie11](https://cloud.githubusercontent.com/assets/174509/16543382/c93f0ba6-409f-11e6-84f5-d566f0ac6c1e.png)
**Safari 9.1**
<img width="200" alt="flexbox-safari-9 1" src="https://cloud.githubusercontent.com/assets/174509/16543379/c93a3c66-409f-11e6-961f-1fb819a42662.png">
## What happened:

**Servo**
<img width="95" alt="flexbox-servo" src="https://cloud.githubusercontent.com/assets/174509/16543381/c93bc5b8-409f-11e6-912c-b593d23f517a.png">

_Note_ I did not enable flexbox support. Please see below for what it looks like with the appropriate preferences enabled.

**Comment by jdm** [comment]
Flex box support is disabled by default and needs to be enabled via preference.

**Comment by shepmaster** [comment]
Ah, I [see now](https://github.com/servo/servo/blob/307844a8c17aedc369388baf4d98b0f82c3b695b/resources/prefs.json).  Running

```
./servo --pref layout.flex.enabled --pref layout.flex-direction.enabled /tmp/index.html
```

Produces this:

<img width="758" alt="flexbox-servo-prefs" src="https://cloud.githubusercontent.com/assets/174509/16543498/bb578ef4-40a5-11e6-9061-48a8f334d4f8.png">

Feel free to repurpose / close this issue as you see fit. I guess I should look for a "does Servo support X" resource before filing anything else.

**Comment by jdm** [comment]
Let's scope this issue to the incorrect rendering that's present when flexbox layout is enabled.

**Comment by metajack** [comment]
cc @shinglyu

**Comment by emilio** [comment]
This should be closed now flexbox is on by default, thanks @stshine for all the flexbox work! :)
