### ISSUE TITLE
Servo displays upper level Thai character in wrong place. 

### ISSUE THREAD

**Issue by veer66** [servo/servo#12193]
On Ubuntu 16.04, Servo nightly, that I downloaded on 2016-07-03, displays upper level Thai characters in the incorrect place. Moreover it choose incorrect glyph too. 

Update: Servo on Mac OS X 10.11.5. has this issue too.

The text is "ยินดี". It is supposed to display    ี  on top of ด but it displays     ิ   on top of น, which is incorrect glyph and incorrect placement. 

![servo_thai_bug](https://cloud.githubusercontent.com/assets/370688/16543811/3fe750fe-4115-11e6-9a00-c4992b423352.png)

An URL for the test case is http://file.veerkesto.net/servo_test/simple-thai.html

**Comment by khaledhosny** [comment]
It seems that two different fonts are used here, so it can be a bug in the font selected by Servo. Can you try to use the same font in both tests?

**Comment by veer66** [comment]
Here you are.
![Uploading tlwg_typist.png…](ยินดี in Tlwg Typist and Tlwg Typo)

**Comment by veer66** [comment]
Here you are:

ยินดี in Tlwg Typist and Tlwg Typo

![tlwg_typist](https://cloud.githubusercontent.com/assets/370688/16611341/e296f774-438a-11e6-8809-e8968e76def4.png)

**Comment by kengggg** [comment]
Confirm @veer66, the incorrect rendering presents in Servo 0.0.1 on Mac OS X 10.11.5.

<img width="1160" alt="screenshot 2016-07-06 15 10 30" src="https://cloud.githubusercontent.com/assets/541454/16611613/a74b9b50-438c-11e6-9f94-4af24cc2b137.png">

Additional information:

The given word **ยินดี** represents by 

`0x0E22` `0x0E34` `0x0E19` `0x0E14` `0x0E35`

But it seems servo has rendered **ยินดี** as **ยินิด** that represents by  

`0x0E22` `0x0E34`  `0x0E19` `0x0E34` `0x0E14`
