### ISSUE TITLE
Inconsistent rendering for paragraph

### ISSUE THREAD

**Issue by di1** [servo/servo#12206]
Individual character colored differently (in single paragraph) than firefox. Servo on Mac, prebuilt developer preview.

http://devday.in

<img width="791" alt="screen shot 2016-07-04 at 11 34 47 am" src="https://cloud.githubusercontent.com/assets/9478611/16552067/83ad29c8-41db-11e6-916b-53c1974bb3c5.png">
<img width="908" alt="screen shot 2016-07-04 at 11 34 58 am" src="https://cloud.githubusercontent.com/assets/9478611/16552072/8b68af3e-41db-11e6-8f96-0395e16d2cff.png">

Let me know if it needs further info

**Comment by nox** [comment]
The wrong font issue is fixed by https://github.com/servo/servo/pull/12208 by the colouring is probably something else.

**Comment by nox** [comment]
I can't seem to reproduce this and the DEVDAY website changed anyway.
