### ISSUE TITLE
./mach test-tidy doesn't ignore files underneath ignored directories

### ISSUE THREAD

**Issue by jdm** [servo/servo#12225]
There's a check in `get_file_list` in `tidy.py` for whether the given file is in a directory that is in the ignored directories list. However, this only catches things like `a/b/c.py` if `a/b/c` is in the list - if the list contains `a/b`, then it doesn't get ignored as it should.

To reproduce this problem, make a change to `tests/wpt/harness/wptrunner/executors/executorservo.py`, since `tests/wpt/harness` is in the list of ignored directories.

Code: `python/tidy/servo_tidy/tidy.py`
Test: `./mach test-tidy --self-test` (add a test to `test_file_list` in `python/tidy/servo_tidy_tests/test_tidy.py`)

**Comment by Wafflespeanut** [comment]
Damn. I swear I'd thought about this before :expressionless:

**Comment by cynicaldevil** [comment]
I'll take it!

**Comment by Wafflespeanut** [comment]
Go ahead! Feel free to ping us at the #servo channel in IRC or comment here in case you need any help :)

**Comment by cynicaldevil** [comment]
Should I submit the PR with two commits(one for the fix and another for the test) or is a single one just fine?

**Comment by Wafflespeanut** [comment]
That's certainly up to you. We generally ask people to squash commits only if/when a future commit fixes the previous commit.
