### ISSUE TITLE
Bug Reports via GET too long for NGINX, 414, should probably be a POST

### ISSUE THREAD

**Issue by Min1123** [servo/servo#12222]
Attempting to play a video on YouTube caused an error, a report button was displayed with a stacktrace in the app, but when I clicked on it, it tried to submit the bug, but the URI was too long on the GET to NGINX, so NGINX rejected it with a 414 code.

This should probably be marshaled to something and sent to a POST endpoint instead.

**Comment by jdm** [comment]
Please file this at https://github.com/mozilla/browser.html/ instead, since that's where the code that controls the error reporter is located.
