### ISSUE TITLE
Automatically report "else {" that is not on the same line as the previous }

### ISSUE THREAD

**Issue by jdm** [servo/servo#12234]
Our style guide says that `} else {` is preferred over
```rust
}
else {
```
We should add a check to `regex_rules` in `tidy.py` that looks for the regex `^\s*else {` (ie. a line that starts with optional whitespace followed by `else {`).

Code: `python/tidy/serv_tidy/tidy.py`
Test: `./mach test-tidy --self-test` (add a new test to `rust_tidy.rs` and `test_tidy.py`)

**Comment by TravisDean** [comment]
I'm working on fixing this now.

**Comment by jdm** [comment]
Great!
