### ISSUE TITLE
Rewrite a match with an empty branch to an `if let`

### ISSUE THREAD

**Issue by jdm** [servo/servo#12236]
In `create_constellation` there is some code that sends a message about an initial URL if it exists. We should rewrite it to use `if let` instead of a `match` expression.

Code: `components/servo/lib.rs`

No need for tests; if it compiles, that's good enough for a PR.

**Comment by hgallagher1993** [comment]
I'll pick this up...thanks for the merge a few minutes ago :wink:

**Comment by perlun** [comment]
@hgallagher1993 I have started looking into it actually, but didn't write here. 😊

**Comment by perlun** [comment]
(Sorry for not claiming it properly. Will do better next time.)
