### ISSUE TITLE
Can I use Servo as C library?

### ISSUE THREAD

**Issue by silvioprog** [servo/servo#12235]
Hello,

Can I use Servo in a C library as an alternative to [CEF](https://bitbucket.org/chromiumembedded/cef)?

Thank you!

**Comment by larsbergstrom** [comment]
Yes! There are some basic instructions here on how to build and use the CEF interfaces exposed by Servo:
https://github.com/servo/servo/tree/master/ports/cef

Please feel free to open additional issues for things that don't work in that scenario.

**Comment by silvioprog** [comment]
Awesome, I'm going to get it. Thank you! :-)
