### ISSUE TITLE
Servo chokes on www.slate.com

### ISSUE THREAD

**Issue by ekr** [servo/servo#12247]
The page half-loads and I see repeated complaining about:
ERROR:js::rust: Error at :0:0: QuotaExceededError: The quota has been exceeded.

**Comment by jdm** [comment]
Interesting; that exception is only thrown by Servo's crypto.getRandomValues() implementation.

**Comment by ekr** [comment]
I haven't traced through the code, but what about? https://github.com/servo/servo/blob/e8cf789fc56dfbc4bfd6145d3bd1a30aa9459c95/components/script/dom/storage.rs#L95

**Comment by jdm** [comment]
Whoops, missed that in the DXR results.

**Comment by nox** [comment]
AFAICT in `StorageThread::set_item`, we set `current_total_size` to the sum of the local and session storages' sizes, and then we use that to update the total size of the `storage_type` storage, accounting for the other kind of storage twice.
