### ISSUE TITLE
Support for native keybindings on input fields

### ISSUE THREAD

**Issue by Gozala** [servo/servo#12278]
This has being one of the issues that ppl raised on hacker news, in response to nightlies announcement. Most native keybindings (at least on Mac) do not work on input fields in servo. Example being

Alt+LeftArrow / Alt+RightArrow - Jump to previous / next word in the input.
Control+Alt+B / Control+Alt+F - Jump to previous / next word in the input.
CMD+LeftArrow / CMD+RightArrow - Jump to beginning / end of the input.
Control+Alt+A / Control+Alt+E - Jump to the beginning / end of the input.

All of the above with `+Shift` doing same + modifying selection.

**Comment by jdm** [comment]
This requires adding further cases to the match in `handle_keydown_aux`. Additionally, we should add new tests to `tests/unit/script/textinput.rs`.

Code: `components/script/textinput.rs`
Tests: `./mach test-unit -p script`

**Comment by jimberlage** [comment]
Mind if I work on this?

**Comment by jdm** [comment]
@jimberlage Please do!

**Comment by jimberlage** [comment]
@Gozala am I correct in in assuming that Control+Alt+A / Control+Alt+E are Windows keybindings?  I'm on a mac so I can't test effectively.

**Comment by Gozala** [comment]
Nope they're on osx 

Typed on tiny keyboard

**Comment by ConnorGBrewster** [comment]
I believe on mac it is just Ctrl+A and Ctrl+E (no alt)

**Comment by Gozala** [comment]
Oh you're right. Not sure where alt's came from :)

Typed on tiny keyboard

**Comment by nox** [comment]
@jdm How are we going to support keyboard shortcut changes through System Preferences on OS X?

**Comment by jdm** [comment]
Write some code using cocoa-rs at some point.

**Comment by paulrouget** [comment]
How does it work in Gecko? Do we use some widget code?

**Comment by jdm** [comment]
My understanding is that Gecko uses native widgets.

**Comment by jdm** [comment]
There was a solution for this in #12549, but it has some review comments that need to be addressed after rebasing that work.

**Comment by jdm** [comment]
@clementmiao Would this interest you?

**Comment by clementmiao** [comment]
@jdm although don't have much experience doing this, willing to give it a shot.
