### ISSUE TITLE
servo compile error

### ISSUE THREAD

**Issue by EnriqueV** [servo/servo#12279]
hello i'm triying compile servo in my macbook but i have this error: 
errorerrorerror: : : errorcan't find crate for `std`can't find crate for `std`can't find crate for `std`:  [ [ [E0463E0463E0463]can't find crate for `std`]] [
Could not compile `azure`

**Comment by izgzhen** [comment]
Can you provide more details? For examples, when you `./mach build -d`, the compiler and `std` should be downloaded at that time, I am not sure if this process is okay on your side.

Also, in case some thing might be wrong with local environment, you can `clone` another clean source and try again.

**Comment by izgzhen** [comment]
PR #12271 might be related, not sure though

**Comment by jdm** [comment]
Yes, 12271 fixes this.

**Comment by KiChjang** [comment]
Fixed by #12271.
