### ISSUE TITLE
IFrame CSS Transform Rotate displays improperly

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12286]
Animating a rotation CSS transform on an IFrame displays improperly:

<img width="1027" alt="IFrame CSS Transform Rotate" src="https://cloud.githubusercontent.com/assets/9294710/16614203/be14293a-4367-11e6-8b69-c17419b02c4f.png">

Code:
```
window.addEventListener('DOMContentLoaded', () => {
                var fr = document.querySelector('iframe');
                var rot = 0;
                requestAnimationFrame(animate);
              
                function animate() {
                    requestAnimationFrame(animate);
                    document.body.style.background = 'none'; // This line required for the rotation to occur
                    rot = (rot + 1) % 360;
                    fr.style.transform = 'rotate(' + rot + 'deg)';
                }
});
```
Online test case [here](https://samuknet.github.io/test_cases/iframeCSSRotate/).

**Comment by jdm** [comment]
Non-webrender behaviour is really terrible. Webrender behaviour is much better, but the clipping rect doesn't appear to be transformed.

**Comment by pcwalton** [comment]
Fascinating.

**Comment by glennw** [comment]
I started looking into this, but got sidetracked by the workweek I was at. I'll continue looking into it this week (should be easier to fix now that WR2 has landed).

**Comment by glennw** [comment]
This will be fixed when https://github.com/servo/webrender/pull/361 lands in servo master.

**Comment by glennw** [comment]
Fixed by https://github.com/servo/servo/pull/13002
