### ISSUE TITLE
Large images are not rendered, sometimes

### ISSUE THREAD

**Issue by Gozala** [servo/servo#12281]
Issue was originally reported under browserhtml/browserhtml#1158 by @yump

> 1. Go to [this picture of an owl on the Wikimedia commons](https://commons.wikimedia.org/wiki/File:Tyto_alba_-British_Wildlife_Centre,_Surrey,_England-8a_%281%29.jpg).
> 2. Try opening the "other resolutions".
> 
> On my machine, the 1504x1880 image never renders (blank white page), and the 819x1024 image sometimes doesn't render.
> 
> OS: Fedora 23, Ubuntu libssl loaded with LD_LIBRARY_PATH.
> 
> Graphics: GTX 660 with Nvidia blob 367.27

**Comment by wdv4758h** [comment]
I try it with master (9e726b4d83fc169c38f176b9958cfb1b66363e8f), built in release mode.
I can see the largest image (1504x1880) most of the time (sometime the page don't jump to the image).

running commands:
* `./servo "https://commons.wikimedia.org/wiki/File:Tyto_alba_-British_Wildlife_Centre,_Surrey,_England-8a_(1).jpg"`
* `./servo -w "https://commons.wikimedia.org/wiki/File:Tyto_alba_-British_Wildlife_Centre,_Surrey,_England-8a_(1).jpg"`

OS: Arch Linux
Hardware: Dell XPS 13

**Comment by nox** [comment]
I can't reproduce this anymore.
