### ISSUE TITLE
Check for duplicates and sorting in prefs.json/package-prefs.json

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#12283]
Follow-up from #12205.

We should add code to tidy (`python/tidy/servo_tidy/tidy.py`) that checks if a JSON object a) has no duplicate keys and b) has its keys in sorted order. Both can be achieved with Python's `json` module, using a [custom `object_pairs_hook`](https://docs.python.org/2/library/json.html#repeated-names-within-an-object) since out of the box Python is more lenient than the RFC and allows duplicates. We should apply this to both the `resources/prefs.json` and `resources/package-prefs.json` files.

Another piece of this might include checking for duplicates at runtime in the Rust prefs parser (`pub fn read_prefs_from_file` in `components/utils/prefs.rs`), but that can also be done separately. This would warrant an extra Rust test for this behavior.

**Comment by tallowen** [comment]
Hey - I'd like to work on this!

**Comment by Wafflespeanut** [comment]
Go ahead! Feel free to ping us at the #servo channel in IRC or comment here in case you need any help!

**Comment by aneeshusa** [comment]
One thing I forgot to mention - please also add tests for this in `python/tidy/servo_tidy_tests/` and and hook them up to run in `python/tidy/servo_tidy_tests/test_tidy.py`. You can check using `./mach test-tidy --self-test`.

**Comment by tallowen** [comment]
hey @aneeshusa - what do you think is the appropriate behavior in the rust loader when duplicate keys are seen? Throw an error? Log a warning?

**Comment by aneeshusa** [comment]
This is not yet complete (one open PR and still need to check for sorting in tidy).

**Comment by aneeshusa** [comment]
The previous PR (#12347) stalled, so this is again open to contributors.

**Comment by Blanen** [comment]
I might actually be interested in this.

Question though, this issue is labeled python, but the PR you just mentioned changed rust parts. Also, you mention in that PR that you want error handling in certain Rust functions. Is this issue thus mislabeled as python? At the moment I'm only familiar with Python and not with Rust( Although interested in learning it)

**Comment by aneeshusa** [comment]
@Blanen there are both Python and Rust parts to this issue. What's left to do:

- Python: check that json files have their keys in sorted order in `def check_json` in `python/tidy/servo_tidy/tidy.py`, and add a test for this as well
- Rust: check for duplicates (but not sorting) in `pub fn read_prefs_from_file` in `components/utils/prefs.rs`, with a new test as well

You're welcome to work on a PR for any part by itself! Let me know if you want to work on something and I'll assign you.

**Comment by Blanen** [comment]
@aneeshusa Hey, thanks for the respone. I can probably do the python stuff next week some time. Then I'll just quietly start on the Rust stuff after that( so don't assign me to that yet).

Also, I looked into testing but it didn't mention this. What are the testing criteria or guidelines or standards?

**Comment by santagada** [comment]
This seems to be mislabeled, the missing part is the Rust duplicate checker and test. @Blanen if you are not taking this because it is rust can I take it?

**Comment by Blanen** [comment]
@santagada You can take the rust part. There's a little left in Python as @aneeshusa said.

**Comment by aneeshusa** [comment]
Some of the Python part has been done (checking for duplicates), but we still need a check + test(s) for sorting; @Blanen, you can work on this. @santagada, you can work on the Rust duplicate checker + test(s).

Thanks for being willing to share.

Testing:
  - For Python, we are changing tidy so add/change test file(s) under `python/tidy/servo_tidy_tests/`, and edit `python/tidy/servo_tidy_tests/test_tidy.py` to use them.
  - For Rust, the testing scheme will depend on how you handle errors but I believe you should be able to add unit tests.

**Comment by Manishearth** [comment]
@Blanen @santagada Are you still working on this?

**Comment by aneeshusa** [comment]
Looks like @santagada filed a PR that I still need to review, oops.

**Comment by santagada** [comment]
yep

**Comment by Blanen** [comment]
@Manishearth 
Yea, it's done, mostly, need to make the test now.

Question though, I now have it check the key order by 1<A<B<a is this like you want it, or would you rather want it to do 1<A<a<B ?

**Comment by aneeshusa** [comment]
@Blanen it looks like all our existing json files use only lowercase letters for keys, so IMO it doesn't matter; use whatever takes the smallest amount of code (likely whatever `<` does by default). Also, feel free to open a WIP PR even if you're not done!

**Comment by Wafflespeanut** [comment]
Previous work on #13789. This is open for anyone to hop into :)

**Comment by kivikakk** [comment]
I'll jump in here! 🐍

**Comment by Wafflespeanut** [comment]
Cool!

**Comment by kivikakk** [comment]
PR is up! ✨

**Comment by Wafflespeanut** [comment]
There's an open PR #13270, which closes this.

**Comment by jdm** [comment]
Didn't #14092 address this? Shouldn't we close #13270?

**Comment by Wafflespeanut** [comment]
Silly me. #14092 addresses the ordering, whereas #13270 checks duplicates in runtime. But, tidy now has both the things. The latter should be closed :disappointed:
