### ISSUE TITLE
Declare externs with &c_char instead of *c_char

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1230]
This would catch the common mistake of

~~~ .rs
c_function(foo.with_c_str(|x| x))
~~~

It's almost always necessary (though not always sufficient) that the string argument outlive the C call.

`strcat` says this will just work with no additional wrapper code.

**Comment by Yoric** [comment]
Is this bug still valid? @abustany , are you still working on it?

**Comment by abustany** [comment]
I'm not working on that issue at the moment, feel free to take it!

**Comment by frewsxcv** [comment]
@Yoric Are you actively working on this?

**Comment by Yoric** [comment]
@frewsxcv Not at the moment.

**Comment by ioctaptceb** [comment]
Is anyone currently working on this? I am new to Rust and this looks easy enough to get into it..

Let me know!

**Comment by frewsxcv** [comment]
Go for it @ioctaptceb !

**Comment by frewsxcv** [comment]
Still working on this @ioctaptceb ? Need any help?

**Comment by Ms2ger** [comment]
With `CStr::as_ptr()` returning a raw pointer, I'm no longer convinced we should do this.
