### ISSUE TITLE
Support for backward selections

### ISSUE THREAD

**Issue by Gozala** [servo/servo#12300]
Servo does not seem to support selections in 'backward' direction. This causes unfortunate behavior in browser.html (see browserhtml/browserhtml#1171).

I also have create simpler test case:
https://Gozala.jsbin.com/caqoya

After `Shift + LeftArrow` you should see:

<img width="561" alt="screen shot 2016-07-06 at 2 47 30 pm" src="https://cloud.githubusercontent.com/assets/21236/16635748/9b4c9100-4388-11e6-8c4b-6daa19559aca.png">

But instead you'll see:

<img width="561" alt="screen shot 2016-07-06 at 2 47 16 pm" src="https://cloud.githubusercontent.com/assets/21236/16635757/a3113800-4388-11e6-9090-cb776431e37d.png">

**Comment by ConnorGBrewster** [comment]
Hmm I cannot seem to reproduce this, running in Servo produces the output seen in the first image

**Comment by Gozala** [comment]
> Hmm I cannot seem to reproduce this, running in Servo produces the output seen in the first image

I'm running latest servo nightly as follows:

```
/Applications/Servo.app/Contents/MacOS/servo -w -b --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref  shell.builtin-key-shortcuts.enabled=false https://Gozala.jsbin.com/caqoya
```

And see behavior described in the issue.

**Comment by ConnorGBrewster** [comment]
Ahh I see the issue now! The insertion point is at the wrong end of the selection

**Comment by ConnorGBrewster** [comment]
As it turns out, `textinput.rs` stores the selection direction but never does anything with it.
