### ISSUE TITLE
Remove util::ipc (OptionalIpcSender / OptionalOpaqueIpcSender / OpaqueSender)

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#12312]
This seems to be a performance optimization for the non-multiprocess case; it's not clear to me that it ever pulled its weight. Note that most of Servo uses plain `IpcSender`s where these types could have been used.

CC @pcwalton

**Comment by djc** [comment]
So I have the simple parts of this done. However, I ran into an issue where in `gfx::paint_thread::PaintThread` the `select!` macro is used over `layout_to_paint_port`, which is now of the IPC variety, and `chrome_to_paint_port`, which is an mpsc channel. Not sure how best to resolve this.

**Comment by jdm** [comment]
You want [this useful method](http://doc.servo.org/ipc_channel/router/struct.ROUTER.html#method.route_ipc_receiver_to_new_mpsc_receiver).
