### ISSUE TITLE
Add Windows dependencies for video-metadata-rs

### ISSUE THREAD

**Issue by GuillaumeGomez** [servo/servo#12316]
For the moment, it seems that windows is giving trouble for ffmpeg dependencies (used by video-metadata-rs). You can find the dependencies [here](https://ffmpeg.zeranoe.com/builds/). I repackaged them myself for adding tests on appveyor (my appveyor script file is [here](https://github.com/GuillaumeGomez/video-metadata-rs/blob/master/appveyor.yml)).

cc @metajack 
cc @vvuk 
cc @larsbergstrom

**Comment by UK992** [comment]
I  successfully build Servo after installing ```mingw-w64-x86_64-ffmpeg``` package via MSYS Pacman.

**Comment by jdm** [comment]
@UK992 Thanks for testing! What about with https://github.com/servo/servo/pull/12186 applied?

**Comment by UK992** [comment]
@jdm i forgot to mention, tested with #12186 applied. without this package installed, hit on same error as mention in this PR.

**Comment by larsbergstrom** [comment]
@UK992 Thank you *so* much for helping test this!

**Comment by GuillaumeGomez** [comment]
So, do I need to anything?

**Comment by larsbergstrom** [comment]
@GuillaumeGomez Can you add that mingw package to the readme.md instructions in your PR? I will deploy it to the Windows CI builder.

**Comment by larsbergstrom** [comment]
I have deployed this to the Windows builder.

**Comment by GuillaumeGomez** [comment]
@larsbergstrom: Done.
