### ISSUE TITLE
There are several changes to tests in css-tests that have not been upstreamed

### ISSUE THREAD

**Issue by jdm** [servo/servo#12326]
https://github.com/servo/servo/commits/master/tests/wpt/css-tests shows a number of Servo PRs that made changes to test files. This is bad, because there's no automatic synchronization that occurs; they just get overwritten the next time we pull changes from upstream.

cc @Ms2ger

**Comment by Ms2ger** [comment]
Cc @mbrubeck

**Comment by nox** [comment]
@jdm Is this still an issue?

**Comment by jdm** [comment]
Yes. I plan to investigate it after #16175.

**Comment by gsnedders** [comment]
OK, things I think need upstreamed (these are basically all the change except simple updates, tools changes, and whitespace only changes):

- [ ] 8d90aa0b88735ad597adc47ba3dbdd71cc598279
- [ ] 2d9d31ee04553446546763e88ff8fedd01aba63e
- [ ] bb3d3db333feedb03821e91a71ab4f5cafe115b3

**Comment by gsnedders** [comment]
So I think we can close this?

**Comment by jdm** [comment]
That is a delightful outcome. Thanks for checking!
