### ISSUE TITLE
Add ability to WPT-test file uploads and fetches

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#12322]
We should perhaps have a command line option or environment variable that specifies a file to upload, and use that for writing Servo-specific WPT tests that upload files and test that they get fetched properly.

**Comment by Manishearth** [comment]
We should also be adding more tests to WPT proper for things like blob URI-ifying slices and similar things.

**Comment by jdm** [comment]
I recommend adding a webidl method or attribute that triggers the same code as selecting one via the usual user input mechanism, and limiting its visibility with a preference.

**Comment by Manishearth** [comment]
Oh, right, we can do that now.

Yes, this works. Something like `Window.setFile()` (or `inputelement.setFile()`), which sets the file that is to be opened.

**Comment by izgzhen** [comment]
Cool, I'll see what I can do

**Comment by izgzhen** [comment]
Which `prefs.json` should be modified for this case in tree?
