### ISSUE TITLE
Generate markers for list items

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#1232]
We have code that will generate them as blocks, but we need to generate the markers per the spec:
http://www.w3.org/TR/CSS21/generate.html#lists

There is also a css-display draft spec that has a clearer explanation. Per @SimonSapin, we should not expose the CSS properties but should use this draft as ideas for the implementation:
http://dev.w3.org/csswg/css-counter-styles/

**Comment by mbrubeck** [comment]
Basic support was implemented in #5067. More specific issues can be filed for any remaining features.
