### ISSUE TITLE
Implement Runnable trait name method for DetailsNotificationRunnable

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12332]
Implement the `Runnable` trait `name` method for `DetailsNotificationRunnable`. The method should return the string: `DetailsNotificationRunnable`.

See `StorageEventRunnable` in `components/script/dom/storage.rs` as an example.
 
---
Code: `components/script/dom/htmldetailselement.rs`

No test changes are needed, it just needs to compile successfully.

**Comment by ChangWanHong** [comment]
I'll take it! But, as I understand, there is no 'name' method in 'Runnable'. Do I have to write 'name' declaration for 'Runnable' first?

**Comment by KiChjang** [comment]
@ChangWanHong Did you pull changes from the latest master branch?

**Comment by ChangWanHong** [comment]
Oh. I missed that point! Thx.
I'll upload patch soon as possible.
