### ISSUE TITLE
Cannot compile on manjaro linux

### ISSUE THREAD

**Issue by mrmiywj** [servo/servo#12337]
Recently I check to Manjaro linux. But it fails when I tried to compile servo. 
The main reason is due to the compilation of `script` crate is stuck because of limitation of memory. But  my memory is 2.5 GB. I thought it was enough.

**Comment by jdm** [comment]
What if you run `./mach build -j1`?

**Comment by nox** [comment]
@mrmiywj Does this still happen?

**Comment by nox** [comment]
In general, there is not much we can do for build errors due to lack of RAM, closing for now.
