### ISSUE TITLE
Implement Runnable trait name method for PlannedNavigation

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12333]
Implement the `Runnable` trait `name` method for `PlannedNavigation`. The method should return the string: `PlannedNavigation`.

See `StorageEventRunnable` in `components/script/dom/storage.rs` as an example.
 
---
Code: `components/script/dom/htmlformelement.rs`

No test changes are needed, it just needs to compile successfully.

**Comment by DarinM223** [comment]
Can I work on this? Thanks!

**Comment by KiChjang** [comment]
@DarinM223 I'd rather leave this for a newcomer. Do you mind looking for harder issues?

**Comment by DarinM223** [comment]
Ok I won't pick this up then.

**Comment by sappharx** [comment]
I can tackle this one
