### ISSUE TITLE
Fail to download rust compiler for building servo

### ISSUE THREAD

**Issue by upsuper** [servo/servo#12336]
When I execute `./mach build -d`, it shows
> looking for rustc at /c/mozilla-source/servo/.servo/rust/2016-06-24/rustc-nightly-x86_64-unknown/rustc/bin/rustc
> Downloading Rust compiler...
> Download failed (403): Forbidden - https://static-rust-lang-org.s3.amazonaws.com/dist/2016-06-24/rustc-nightly-x86_64-unknown.tar.gz
> No Rust compiler binary available for this platform. Please see https://github.com/servo/servo/#prerequisites

**Comment by KiChjang** [comment]
What target triplet are you using to compile Servo?

**Comment by upsuper** [comment]
Ideally x86_64-pc-windows-msvc.

**Comment by upsuper** [comment]
Oh, I see, the target is not recognized properly. It worked yesterday.

**Comment by upsuper** [comment]
OK, it's my fault. I was using the MSYS2 Shell rather than the MinGW Shell... Then it works.
