### ISSUE TITLE
Acid3 requirements

### ISSUE THREAD

**Issue by jdm** [servo/servo#1233]
http://acid3.acidtests.org/

**Comment by Manishearth** [comment]
I think we mainly need `document.write` to work now -- @kmcallister , how close are we to this?

**Comment by metajack** [comment]
Why did you close this?

**Comment by Ms2ger** [comment]
I don't see a reason to track this; it's a crappy test.

**Comment by DavidBruant** [comment]
> I don't see a reason to track this; it's a crappy test.

@Ms2ger Why?

Even after the [September 2011 changes](http://en.wikipedia.org/wiki/Acid3#September_2011_test_changes) ?
