### ISSUE TITLE
Implement Runnable trait name method for DocumentProgressHandler

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12335]
Implement the `Runnable` trait `name` method for `DocumentProgressHandler`. The method should return the string: `DocumentProgressHandler`.

See `StorageEventRunnable` in `components/script/dom/storage.rs` as an example.
 
---
Code: `components/script/dom/document.rs`

No test changes are needed, it just needs to compile successfully.

**Comment by KiChjang** [comment]
It's yours!
