### ISSUE TITLE
Implement Runnable trait name method for FileReaderEvent

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12334]
Implement the `Runnable` trait `name` method for `FileReaderEvent`. The method should return the string: `FileReaderEvent`.

See `StorageEventRunnable` in `components/script/dom/storage.rs` as an example.
 
---
Code: `components/script/dom/filereader.rs`

No test changes are needed, it just needs to compile successfully.

**Comment by cynicaldevil** [comment]
I'll take it!

**Comment by KiChjang** [comment]
Go for it!
