### ISSUE TITLE
Implement Runnable trait name method for FireSimpleEventTask

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12346]
Implement the `Runnable` trait `name` method for `FireSimpleEventTask`. The method should return the string: `FireSimpleEventTask`.

See `StorageEventRunnable` in `components/script/dom/storage.rs` as an example.
 
---
Code: `components/script/dom/htmlmediaelement.rs`

No test changes are needed, it just needs to compile successfully.

**Comment by MovingtoMars** [comment]
I'll take this please.
