### ISSUE TITLE
Implement Runnable trait name method for DedicatedMediaSourceFailureTask

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12349]
Implement the `Runnable` trait `name` method for `DedicatedMediaSourceFailureTask`. The method should return the string: `DedicatedMediaSourceFailureTask`.

See `StorageEventRunnable` in `components/script/dom/storage.rs` as an example.
 
---
Code: `components/script/dom/htmlmediaelement.rs`

No test changes are needed, it just needs to compile successfully.

**Comment by pierre-alain-b** [comment]
I will take it!
