### ISSUE TITLE
Implement Runnable trait name method for ImageResponseHandlerRunnable

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12345]
Implement the `Runnable` trait `name` method for `ImageResponseHandlerRunnable`. The method should return the string: `ImageResponseHandlerRunnable`.

See `StorageEventRunnable` in `components/script/dom/storage.rs` as an example.
 
---
Code: `components/script/dom/htmlimageelement.rs`

No test changes are needed, it just needs to compile successfully.

**Comment by gpoesia** [comment]
I'll take this.
