### ISSUE TITLE
Investigate test failures in formdata.htm

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#12341]
The XHR `responseText` is empty on all responses when running the WPT test. We should investigate what's wrong here. Possible areas of failure include: 1) the Python script is not returning values properly, 2) XHR is not serializing `FormData` properly.

cc @Scorpil 

Code: `components/script/dom/formdata.rs`, `components/script/dom/xmlhttprequest.rs`
Spec: https://xhr.spec.whatwg.org/#the-send()-method
Test: `components/wpt/web-platform-tests/XMLHttpRequest/formdata.htm`

**Comment by Scorpil** [comment]
@KiChjang tanks, will investigate.

**Comment by KiChjang** [comment]
Feel free to contact us at #servo on `irc.mozilla.org`, or leave a comment here if you have any questions.

**Comment by KiChjang** [comment]
This appears to be a missing implementation for the `send` function in XHR. We currently do not send any `BodyInit` requests, and in order to implement that, we'll need to fix #10605 first.

**Comment by KiChjang** [comment]
cc @Manishearth

**Comment by Manishearth** [comment]
We now have proper file support too, so after the union issue it should be straightforward to make formdata serialize with files inside it.

**Comment by jdm** [comment]
Sounds like we know the solution and it's not possible to implement it yet.

**Comment by KiChjang** [comment]
This is still blocked on #9490.

**Comment by nox** [comment]
#9490 landed.

**Comment by KiChjang** [comment]
The test linked is no longer failing on master.
