### ISSUE TITLE
Servo in macOS Sierra 10.12 cannot scrolling in webpage after open website 5 seconds.

### ISSUE THREAD

**Issue by doanga2007** [servo/servo#12351]
Servo in macOS Sierra 10.12 cannot scrolling in webpage after open website 5 seconds.

**Comment by metajack** [comment]
Does this happen on every website you try? Are there any errors printed? Is it possible you could record a short video of this behavior?

**Comment by ConnorGBrewster** [comment]
I am on Sierra as well, I cannot seem to reproduce the issue. @doanga2007 are you using the trackpad for scrolling or a mouse wheel?

**Comment by doanga2007** [comment]
@metajack VDO to behavior of problem : https://youtu.be/7isfAN6x5DQ

@ConnorGBrewster I using mouse wheel for scrolling.

**Comment by KiChjang** [comment]
This looks to me that the scrolling behaviour breaks after scrolling off the edge and bouncing back.

**Comment by doanga2007** [comment]
@KiChjang Yes , I found problem same as KlChjang comment.

**Comment by doanga2007** [comment]
Lastest news : Servo in macOS Sierra 10.12 can scrolling in webpage after open website but html5test.com and html6test.com websites cannot scrolling in webpage after scrolling off the edge and bouncing back.

VDO : http://www59.zippyshare.com/v/sTLj2XTI/file.html

**Comment by nox** [comment]
I can't reproduce this anymore.
