### ISSUE TITLE
Implement Runnable trait name method for PauseIfNotInDocumentTask

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12350]
Implement the `Runnable` trait `name` method for `PauseIfNotInDocumentTask`. The method should return the string: `PauseIfNotInDocumentTask`.

See `StorageEventRunnable` in `components/script/dom/storage.rs` as an example.
 
---
Code: `components/script/dom/htmlmediaelement.rs`

No test changes are needed, it just needs to compile successfully.

**Comment by buddja** [comment]
Hey guys could i take this one as my first contribute?

**Comment by ConnorGBrewster** [comment]
@buddja please do!

**Comment by andrewdavidmackenzie** [comment]
I saw there were a few similar issues (I was looking for my first PR opportunity also).

It made me wonder was there not a rust macro to get the Struct name, and that could be used as a default trait implementation for that method - and boom! you get them all done automatically?

**Comment by KiChjang** [comment]
There is a default trait method for the name() function, which returns "generic runnable".

**Comment by ConnorGBrewster** [comment]
@andrewdavidmackenzie it would probably be possible to make a macro to do this, but since there aren't a ton of `Runnable`s I am not sure it would be worth doing that. For now manual implementations will work fine.

**Comment by ice9js** [comment]
I'd like to get on this if I may.

**Comment by ConnorGBrewster** [comment]
@ice9js go for it!
