### ISSUE TITLE
white-space: pre-wrap and pre-line cause infinite loop

### ISSUE THREAD

**Issue by kilobtye** [servo/servo#12369]
Test case:
```html
<!doctype html>
<html>
<style>
div {
   width: 70px;
   white-space: pre-wrap; // or pre-line
}
</style>
<div>This is a loooooooong line
Line 2
</div>
</html>
```

fatal runtime error: out of memory
Servo exited with return value -4

**Comment by emilio** [comment]
Hm... I think I've seen something similar (https://github.com/servo/servo/issues/6997). Probably not completely related, I'm going to give it a shot.

Thanks for reporting it! :)
