### ISSUE TITLE
Implement Range

### ISSUE THREAD

**Issue by jdm** [servo/servo#1236]
Needed for #1233.

http://dom.spec.whatwg.org/#interface-range

**Comment by frewsxcv** [comment]
@saneyuki Still working on this?

**Comment by saneyuki** [comment]
@frewsxcv 

No. I'm not working this now.

@dzbarsky and @nox worked to implement some parts of this, but I'm not sure about their current status.

**Comment by nox** [comment]
deleteContents() is not implemented yet.

**Comment by nox** [comment]
And the stringifier.

**Comment by mbrubeck** [comment]
#9795 and #9796 finished those last two items.
