### ISSUE TITLE
Margins of inline pseudo elements(:before and :after) are ignored.

### ISSUE THREAD

**Issue by splav** [servo/servo#12367]
Minimal case:
```
<!DOCTYPE html><html><head><style type="text/css">
  span:before { content:"a"; margin-right:5em; }
  span:after { content:"c"; margin-left:5em; }
</style></head>
<body><span>b</span></body>
</html>
```
Servo:
![servo_inline_pseudo_margins](https://cloud.githubusercontent.com/assets/182050/16710061/5dcf6246-4633-11e6-917e-4a3fcc358476.png)
Firefox:
![firefox_inline_pseudo_margins](https://cloud.githubusercontent.com/assets/182050/16710062/5ddef1ca-4633-11e6-9846-87fb4bcaea43.png)

If there are no objections, I would like to try to investigate it myself.
Any thoughts/ideas are welcome.

**Comment by notriddle** [comment]
Random guess: [fragment merging](https://github.com/servo/servo/blob/master/components/layout/fragment.rs#L2047).
