### ISSUE TITLE
Window gets moved when attempting to highlight text

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#12363]
This does _not_ apply to browserhtml. Just the standard development `./mach run -d` chrome. This might only affect Mac?

![untitled](https://cloud.githubusercontent.com/assets/416575/16708570/89cced18-45c6-11e6-84a0-d2350a6286c1.gif)

**Comment by frewsxcv** [comment]
Not necessarily highlighting text. Just any sort of click+dragging.

**Comment by StefanYohansson** [comment]
@frewsxcv I can't reproduce here. I'll post tomorrow the test results on Mac and Windows.

OS: Apricity (4.6.3-1-ARCH)
UI: gnome 3
command: `./mach run -d https://news.ycombinator.com/`

**Comment by jdm** [comment]
I can reproduce on OS X.

**Comment by sviter** [comment]
Is it still valid?

**Comment by jdm** [comment]
Yes.

**Comment by cbrewster** [comment]
Cannot reproduce anymore
