### ISSUE TITLE
Implement Document.referrer

### ISSUE THREAD

**Issue by jdm** [servo/servo#12389]
This is required for #10311. We should store an `Option<String>` value in `Document` that is obtained from the `Referer` HTTP header (if present) when the document is created in `ScriptThread::load`.

Spec: https://html.spec.whatwg.org/multipage/dom.html#dom-document-referrer
Code: `components/script/dom/document.rs`, `components/script/script_thread.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/referrer-policy` may show new results with this change.

**Comment by canaltinova** [comment]
Hi, I would like to work on this.

**Comment by canaltinova** [comment]
@TheKK I didn't see the other issue before attempting to claim it. Sorry about that. If you want to work on it's all yours :)

**Comment by TheKK** [comment]
@canaltinova It's fine to take it :)

**Comment by jdm** [comment]
Great!
