### ISSUE TITLE
Servo crash when DejaVu font is not installed

### ISSUE THREAD

**Issue by ariasuni** [servo/servo#12399]
On my system, the DejaVu font is not the default font nor installed. However, when loading a page, even if the DejaVu font is not required nor requested by the CSS, Servo crash. This bug affects the nightly and the git version that I just built.

**Comment by nox** [comment]
Does this still happen?

**Comment by ariasuni** [comment]
This doesn’t happen anymore with the Servo nightly available at <https://download.servo.org/>.
