### ISSUE TITLE
Failing to build Servo on OS X El Capitan due to lack of openssl

### ISSUE THREAD

**Issue by changm** [servo/servo#12394]
When following the instructions on README, I'm getting compilation errors complaining about openssl:

src/c_helpers.c:1:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>

I tried the brew link --force openssl, but that didn't work. I found this other thread referring to other solutions: https://github.com/sfackler/rust-openssl/issues/255.

Using https://github.com/sfackler/rust-openssl/issues/255#issuecomment-192867841 fixed it for me. It may be worth investigating why this happened or just add another line in README about other options to fix the openssl issue.

**Comment by ConnorGBrewster** [comment]
After `brew link --force openssl` did you try `./mach clean` before rebuilding?

**Comment by changm** [comment]
That worked, thanks! I kept trying to do ./mach clobber (too used to gecko heh). Maybe we can add this bit to the README? Thanks!
