### ISSUE TITLE
Box builder should perform "split-inline" cleanup

### ISSUE THREAD

**Issue by burg** [servo/servo#124]
When a display:block box is added as a child of an inline flow, it should cause the inline to split into two inline flows. If a node corresponds to the split inline flow (it's not anonymous), then we should probably update the node's aux data to point to both inline flows, or have some sort of continuation from one flow to the next.

This should be implemented in `LayoutTreeBuilder::simplify_children_of_flow`.

**Comment by pcwalton** [comment]
We've had {ib} splits for a long time. Closing.
