### ISSUE TITLE
Need better description for mach subcommands

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#12402]
Currently the mach subcommand descriptions are not very clear, especially the following ones:

```
test-css              Run the web platform tests
test-wpt              Run the web platform tests
test-wpt-failure      Run the web platform tests
update-css            Update the web platform tests
update-wpt            Update the web platform tests
```

Perhaps someone who knows the difference can update them?

**Comment by yoyo930021** [comment]
I try it!
what is test-wpt-failure doing?
test-wpt diff?

**Comment by jdm** [comment]
`test-wpt-failure` runs a very small test harness that verifies that failures in tests are reported correctly. `test-wpt` is the regular test suite.

**Comment by yoyo930021** [comment]
test-css                  Run the css tests
test-wpt                 Run the web platform tests that the regular test suite
test-wpt-failure     Run the small test harness that verifies that failures
                                in tests are reported correctly
update-css            Update the css tests
update-wpt            Update the web platform tests

is ok?

**Comment by Wafflespeanut** [comment]
Can you please open a PR with your changes so that we can make our comments there? :)

**Comment by yoyo930021** [comment]
@Wafflespeanut Thank 
I PR.
