### ISSUE TITLE
Extensive startup time

### ISSUE THREAD

**Issue by w-barath** [servo/servo#12417]
I followed the instructions - I downloaded the servo tarball then

```
$ tar xzvf ~/Downloads/servo-latest.tar.gz 
$ cd servo
$ ./runservo.sh
```

And then my CPU use went to 100% for an extensive period of time, but nothing happened.

So I interrupted with CTRL-C and checked my environment, ie DISPLAY=:0.0 etc. and I ran runservo.sh.  Again CPU to 100% for an extensive period of time, this time I ran top to see what was going on, and servo was at 100%, and again nothing happening on screen.

So I interrupted with CTRL-C yet again and this time I ran:

```
$ strace -f runservo.sh &>servo.strace.log
```

And because I know strace slows things down a lot, this time I did not interrupt it and instead went off to do some work.  When I came back 20m later I saw servo had actually loaded up something similar to a mobile web browser app on my desktop.  It was not remotely real-time interactive so I again halted with CTRL-C and ran it again, expecting it to take several minutes to start, but this time it started in 2-3 seconds.

What's this bug report about then?

Each of the first 2 invocations where I ended up hitting CTRL-C to halt the process, I was on the fence as to whether my next step should be:

```
$ cd ..; rm -rf servo*
```

So, perhaps some sort of first-start warning to the effect of " Okay, starting servo for the first time.  Kiss your battery life goodbye and say hello to the hairdryer of doom for the next several minutes as we spin our wheels silently in the background apparently doing nothing... but it will be worth the wait."

**Comment by w-barath** [comment]
I was unable to reproduce the startup delay as my main user so I created a new one:

```
$ sudo adduser servo
```

then I switched user:

```
$ sudo su servo
```

then I timed the startup:

```
$ time ./runservo.sh
```

and I got the following response after clicking the app close button as soon as it appeared:

> libGL error: failed to open drm device: Permission denied
> libGL error: failed to load driver: i965
> Unhandled error occured 
> ReferenceError: navigator.mozSettings API is not available
> 
> real	1m38.253s
> user	1m52.288s
> sys	0m6.224s
> 

I checked the strace log I made earlier and although I found a reference to ~/.config/servo I could find no such created folder on my accout or the newly created 'servo' account, so I have no clue where servo is storing its config preferences or cache or state data which results in the dramatic differences in startup time.  

Perhaps it would be wise to place these in ~/.config/servo and ~/.cache/servo, as expected.

**Comment by notriddle** [comment]
The `sudo su` failure is a normal direct rendering failure. The display is owned by your regular user, so servo running as the servo user can't access it.

Also, servo doesn't store its cache or preferences anywhere. It doesn't support either, yet.

**Comment by nox** [comment]
@w-barath Does it still happen for you?

**Comment by dralley** [comment]
Outdated
