### ISSUE TITLE
error: failed to run custom build command for `openssl-sys-extras v0.7.14`

### ISSUE THREAD

**Issue by pahakalle** [servo/servo#12425]
**im using mac el capitan**

**the error i get:**

Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys-extras v0.7.14`
Process didn't exit successfully: `/Users/admin/github/servo/target/release/build/openssl-sys-extras-5c7e4d8925825f00/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("x86_64-apple-darwin")
debug=false opt-level=3
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-o" "/Users/admin/github/servo/target/release/build/openssl-sys-extras-5c7e4d8925825f00/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
ExitStatus(ExitStatus(256))

command did not execute successfully, got: exit code: 1

--- stderr
src/openssl_shim.c:1:10: fatal error: 'openssl/hmac.h' file not found
#include <openssl/hmac.h>
         ^
1 error generated.
thread 'main' panicked at 'explicit panic', /Users/admin/github/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.28/src/lib.rs:840
note: Run with `RUST_BACKTRACE=1` for a backtrace.

[Warning] Could not generate notification! Optional Python module 'pyobjc' is not installed.
Build completed in 0:24:28

**Comment by Scorpil** [comment]
Have you linked your openssl? It's mentioned in README: https://github.com/servo/servo/#prerequisites

**Comment by pahakalle** [comment]
ok for some reason it didn't link it at the first time. but running the command again fixed the issue. thanks for the help 😄
