### ISSUE TITLE
Allow mozbrowser events to be targeted at the window

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#12420]
#11248 requires throwing a mozbrowsererror event at the root window rather than at an iframe (because we may not know which iframe caused the error). At the moment, mozbrowser events can only be targeted at iframes, we should fix this so they can target other elements.

**Comment by asajeffrey** [comment]
cc @Gozala @paulrouget

**Comment by Gozala** [comment]
Issue on the browser.html side https://github.com/browserhtml/browserhtml/issues/1182
