### ISSUE TITLE
Publish documentation for the master branch of all Servo-maintained crates

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#12433]
Right now, we have documentation on doc.servo.org for servo/servo master, and all dependencies, at whatever version master is using. This is useful, but if we want other people to use our crates, we should publish the most current documentation for them, even if we've not updated Servo to use the most current version.

[We already do this for rust-url.](https://servo.github.io/rust-url/url/index.html) It would be good to do that for all our crates.

Possible things to consider: https://github.com/huonw/travis-cargo; https://crates.fyi/crates/

**Comment by aneeshusa** [comment]
The way this is done in `rust-url` is uploading from Travis using an encrypted env var. See its [`.travis.yml`](https://github.com/servo/rust-url/blob/master/.travis.yml) for the dispatch and its [`Makefile`](https://github.com/servo/rust-url/blob/master/Makefile) for the actual doc creation + upload code.

`travis-cargo` seems to use the same flow but includes other things we don't need, so I'd like to avoid the extra dependency for now.

**Comment by nox** [comment]
Do we really need this, now we have docs.rs?

**Comment by nox** [comment]
Let's close it.
