### ISSUE TITLE
Add license field to Cargo.toml files

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#12434]
Currently our Cargo.toml files don't contain licensing information. They should all say `license = "MPL-2.0"`.

**Comment by asajeffrey** [comment]
We should also write a tidy check for licensing in the Cargo.toml files. cc @jdm @aneeshusa

**Comment by frewsxcv** [comment]
> We should also write a tidy check for licensing in the Cargo.toml files.

Relevant issues:

* https://github.com/servo/servo/issues/861
* https://github.com/servo/servo/issues/10716
* https://github.com/servo/servo/issues/5786
