### ISSUE TITLE
Add a build check that fixed intermittents stay fixed

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#12435]
We might want to add something like an `etc/ci/check-fixed-intermittents.sh` that makes sure that any fixed intermittents in #12424 stay fixed. Something like:

```
./mach test-wpt --repeat 100 --release <list of fixed intermittents>
```

cc @aneeshusa @ConnorGBrewster

**Comment by asajeffrey** [comment]
IRC conversation: http://logs.glob.uno/?c=mozilla%23servo&s=13+Jul+2016&e=13+Jul+2016#c479357

TL;DR: Opera used 300 repetitions; might be worth running this nightly rather than on every merge?

cc @jgraham

**Comment by aneeshusa** [comment]
How about doing 10 repetitions for regular builds as a spot check, and 300 (or 100, etc.) on a nightly build to stress test?

**Comment by asajeffrey** [comment]
For the regular build, is 10 much better than 1? Perhaps we should just leave the regular build alone, and add a stress test to a nightly build.

**Comment by aneeshusa** [comment]
Not fixed until https://github.com/servo/saltfs/pull/453 lands.

**Comment by aneeshusa** [comment]
Also, since this is running nightly, we need to set up notifications on build failure.

**Comment by cbrewster** [comment]
Can this be closed now?

**Comment by aneeshusa** [comment]
This has been configured and is running nightly, so closing.

However, it seems the `mac-rel-intermittent` hasn't passed in quite a while: http://build.servo.org/builders/mac-rel-intermittent
We may want to add alerting for these builds.
