### ISSUE TITLE
Key handling seems to be broken

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#12450]
It acts really weird:
When I press first key -> nothing happends,
When I press second key -> first key is processed,
When I press third key -> second key is processed,
etc...
Some keys seems to not work at all, like `:`.
![keys2](https://cloud.githubusercontent.com/assets/10187350/16854887/388d8696-4a13-11e6-869e-edd4f40668ef.gif)
Tested on Windows 8.1 x64

**Comment by KiChjang** [comment]
Could this be an issue with browserhtml instead?

**Comment by jdm** [comment]
What keyboard layout are you using, what keyboard model, and what operating system?

**Comment by blacksvk** [comment]
It is not only browserhtml problem, I have same problem when I run servo without browserhtml.

OS: Windows 8.1 x64
Keyboard: Chicony KU-0833 USB keyboard
Layout: I'm using EN-US and SK-QWERTY, I tried both of them, and It does not matter which layout am I using, the problem still exists

**Comment by stshine** [comment]
Is this #12937?

**Comment by jdm** [comment]
Yes.
