### ISSUE TITLE
Implement flex-grow

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#12455]
https://drafts.csswg.org/css-flexbox/#flex-grow-property

https://css-tricks.com/almanac/properties/f/flex-grow/

meta: #12453

**Comment by shinglyu** [comment]
I'll start working on this.

**Comment by shinglyu** [comment]
Looks like it's partially (how partial?) implemented in https://github.com/servo/servo/pull/12298

**Comment by stshine** [comment]
This is fixed by #12230 and #13590.
