### ISSUE TITLE
Implement DedicatedWorkerGlobalScope.close

### ISSUE THREAD

**Issue by jdm** [servo/servo#12466]
We need to add an API to WorkerGlobalScope to mark the worker as closed (see `WorkerGlobalScope::is_closing`), and then use that from the new `DedicatedWorkerGlobalScope::Close` method that needs to be added.

Specification: https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-dedicatedworkerglobalscope-interface and https://html.spec.whatwg.org/multipage/workers.html#dom-dedicatedworkerglobalscope-close
Code: `components/script/dom/webidls/DedicatedWorkerGlobalScope.webidl`, `components/script/dom/dedicatedworkerglobalscope.rs`, `components/script/dom/workerglobalscope.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/workers/WorkerGlobalScope_close.htm` (the test currently fails; it should pass after these changes)

**Comment by fabricedesre** [comment]
Taking

**Comment by KiChjang** [comment]
You got it!

**Comment by fabricedesre** [comment]
My laptop fan just died so please unassign me until I fix that. Waiting 8min for a 1 line change is really not practical 😞 ...

**Comment by mephisto41** [comment]
Can I take this?

**Comment by jdm** [comment]
@mephisto41 Please do!
