### ISSUE TITLE
Servo in macOS Sierra 10.12 cannot select text cursor with mouse.

### ISSUE THREAD

**Issue by doanga2007** [servo/servo#12479]
Servo in macOS Sierra 10.12 cannot select text cursor with mouse.

VDO to behavior of problem : https://youtu.be/CIN11DMEJLY

**Comment by jdm** [comment]
We don't support text selection on any platform yet.

**Comment by doanga2007** [comment]
@jdm Thanks You to answer problem.

**Comment by jdm** [comment]
Closing in favour of #4409. Thanks for reporting it!
