### ISSUE TITLE
Using test-wpt with a relative URL starting with / no longer works

### ISSUE THREAD

**Issue by jdm** [servo/servo#12481]
```
godot2:servo jdm$ ./mach test-wpt /FileAPI/url/url_xmlhttprequest_img.html
Warning: /FileAPI/url/url_xmlhttprequest_img.html is not a wpt test. Delegating to test-None.
/FileAPI/url/url_xmlhttprequest_img.html is not a valid test path or suite name
```
We should fix this, since the WPT logs spit out URLs that look like that.

**Comment by aravind-pg** [comment]
I'm getting a somewhat similar warning with plain old `mach update-manifest` as well:
```
Warning: SKIP_TESTS is not a wpt test. Delegating to test-None.
SKIP_TESTS is not a valid test path or suite name
```

Definitely something new, and I can reproduce it on master as well. Could these be related?

**Comment by aravind-pg** [comment]
Hmm I think this was probably introduced by #11604, the only PR to touch testing_commands.py in a while.

**Comment by ConnorGBrewster** [comment]
@aravind-pg indeed! It looks like #11604 did cause the breakage.

**Comment by ConnorGBrewster** [comment]
It looks like here https://github.com/servo/servo/pull/11604/commits/b0d76ae8920776302fbd49cc308789f79c748406#diff-a139f7c2483c6cf4f78098b575503c04R347 we try to get the suite for the path, but `suite_for_path` does not check for relative URLs starting with /
