### ISSUE TITLE
<input> layout wrong with transform

### ISSUE THREAD

**Issue by kilobtye** [servo/servo#12491]
Test case:

``` html
<!doctype html>
<style>
input {
  margin: 20px;
  transform: translateX(-10px);
  overflow: auto;
}
</style>
<input value="abcde">
```

Screenshot:
![screenshot from 2016-07-18 20-52-33](https://cloud.githubusercontent.com/assets/4321081/16915365/b250fa12-4d29-11e6-8250-d2e6c0dd32a6.png)
Does not happen without overflow: auto, see #12364

**Comment by jdm** [comment]
This works now.
