### ISSUE TITLE
Servo Nightly consuming all memory, bringing system to a halt (Mac OS X 10.11.5)

### ISSUE THREAD

**Issue by sole** [servo/servo#12519]
I downloaded Nightly yesterday, tried a few things and then closed it with the "quit Servo" menu option. Then I left my laptop unattended for a while, and when I came back an hour and a half later, there was a Mac OS pop up saying that all memory on the system had been exhausted and every application had been paused. I could open Activity Monitor to see who was the culprit of this exhaustion and... it seems that it was Servo (!?)

<img width="912" alt="screen shot 2016-07-19 at 18 31 31" src="https://cloud.githubusercontent.com/assets/5609/16980437/da52fdb4-4e5d-11e6-99db-33b9da4dfc03.png">

I don't know if it wasn't actually shut down, but the fact is that it was trying to use 64 GB of memory, which seems 'a little bit' excessive.

**Comment by nox** [comment]
@sole Does it still happen?

**Comment by dralley** [comment]
This should probably be closed.

**Comment by nox** [comment]
Yes.
