### ISSUE TITLE
Windows builds with updated msys/mingw gcc segfault while building skia

### ISSUE THREAD

**Issue by jdm** [servo/servo#12512]
```
mkdir -p `dirname /c/projects/servo/target/debug/build/servo-skia-d260e1da355c4a73/out/src/core/SkDistanceFieldGen.o` && g++ -c -O3 -DSK_RELEASE -DGR_RELEASE=1 -DSK_A32_SHIFT=24 -DSK_R32_SHIFT=16 -DSK_G32_SHIFT=8 -DSK_B32_SHIFT=0 -DGR_GL_USE_NEW_SHADER_SOURCE_SIGNATURE=1 -I"/include" -I"/include" -Iinclude/config -Iinclude/core -Iinclude/effects -Iinclude/gpu -Iinclude/images -Iinclude/pathops -Iinclude/pipe -Iinclude/ports -Iinclude/utils -Isrc/core -Isrc/image -Isrc/opts -Isrc/ports -Isrc/sfnt -Isrc/utils -Ithird_party/etc1 -Ithird_party/ktx -iquote src/gpu -I/usr/include/freetype2 -std=gnu++0x -Wno-deprecated-declarations -D_WIN32_WINNT=0x0600 -DSK_BUILD_FOR_WIN32 -DSK_INCLUDE_FREETYPE -Iinclude/utils/win -I/mingw64/include/freetype2 -msse2 -mfpmath=sse -o /c/projects/servo/target/debug/build/servo-skia-d260e1da355c4a73/out/src/core/SkDistanceFieldGen.o src/core/SkDistanceFieldGen.cpp
--- stderr
src/core/SkDistanceFieldGen.cpp: In function 'bool generate_distance_field_from_image(unsigned char*, const unsigned char*, int, int)':
src/core/SkDistanceFieldGen.cpp:332:13: internal compiler error: Segmentation fault
 static bool generate_distance_field_from_image(unsigned char* distanceField,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://sourceforge.net/projects/msys2> for instructions.
make: *** [makefile.cargo:776: /c/projects/servo/target/debug/build/servo-skia-d260e1da355c4a73/out/src/core/SkDistanceFieldGen.o] Error 1
make: *** Waiting for unfinished jobs....
thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f", "makefile.cargo",
                            &format!("-j{}" , env :: var ( "NUM_JOBS" ) .
                                     unwrap (
                                     ))]).status().unwrap().success()', C:/projects/servo/.cargo\registry\src\github.com-1ecc6299db9ec823\servo-skia-0.20130412.10\build.rs:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
cargo build -v
Build completed in 0:25:16
Command exited with code 101
```

**Comment by larsbergstrom** [comment]
I suspect this is related to having a newer GCC version. The Windows builder has no problem, but is on gcc 5.3.0-5, whereas the latest pull is GCC 6.1.0-1.

I can reproduce this ICE on my local windows box with that GCC.

**Comment by marcusball** [comment]
I'm also getting this error on a fresh install of Windows 10, and followed the setup instructions exactly.

**Comment by larsbergstrom** [comment]
@marcusball I'm seeing it, too, and have changed the title to reflect that things are pretty broken. I suspect we're going to have to figure out what the right `pacman` incantation is to pin gcc to an older version, at least until the migration to building with the MSVC stack lands.

**Comment by larsbergstrom** [comment]
Oh, ick, it looks like mingw doesn't support installing older versions of packages without direct access to the files:
http://stackoverflow.com/questions/33969803/how-to-obtain-older-versions-of-packages-using-msys2

**Comment by marcusball** [comment]
The issue appears to be stemming from servo-skia `0.20130412.8` which is a dependency of the `azure` crate. Newer versions of servo-skia seem to be working, though.

**Comment by larsbergstrom** [comment]
Hrm, I seem to get the same error with `.11`:
```
C:/msys64/home/lars/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.20130412.11/src/core/SkDistanceFieldGen.cpp: In function 'bool generate_distance_field_from_image(unsigned char*, const unsigned char*, int, int)':
C:/msys64/home/lars/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.20130412.11/src/core/SkDistanceFieldGen.cpp:332:13: internal compiler error: Segmentation fault
 static bool generate_distance_field_from_image(unsigned char* distanceField,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by marcusball** [comment]
Ah, yes. We probably have different system setups. I have Visual Studio installed, so [changes from literally two days ago](https://github.com/servo/skia/commit/714d13598ec8f54e8993b46a9fd9565e10230385) mean that my system is now using MSVC to compile skia `>= .11`. For me, skia `.11` will compile, however only after a patch to the subsequent dependency of `expat-sys`, as that was throwing a bunch of unresolved external symbol errors.

**Comment by marcusball** [comment]
An interesting behavior, that may just be a red herring, is that, if you modify line 316, just above the function at which this error is occurring, and change `#define DUMP_EDGE 0` to have a value of `1`, then this particular file will compile; however, it'll fail with a similar error on a subsequent file. This makes me think it's something weird going on with the `pack_distance_field_val` method, just above the method referenced by the error. I'm suspicious of the float-to-byte casting in `pack_distance_field_val`, which is the last actual operation before the definition of `generate_distance_field_from_image`, as well as the usage of the output of the `pack` method to do some weird pointer logic (which gets removed if the define change) inside the `generate` method. 

I tried changing some of the code, but, in basic tests, I didn't make any headway. Though, as I said, I'm just throwing out observations; not sure if they're significant.
