### ISSUE TITLE
Windows package is missing files

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#12523]
The Windows package (seen here: https://download.servo.org/nightly/windows/servo-latest.tar.gz) is missing some contents:

1) servo.exe is not packaged

2) there is a runservo.sh instead of runservo.cmd or runservo.bat

We plan to switch to an MSI (see https://github.com/servo/servo/pull/11967), but it'd be nice to just have a working package of some form for right now.

**Comment by rmsEfx** [comment]
What should I need to be installed to run runservo.sh on Win 7 64bit?

**Comment by rmsEfx** [comment]
First try:
`$ cd c:\servo

$ dir
build  resources  runservo.sh

$ sh runservo.sh
runservo.sh: line 2: ./servo: No such file or directory
`

**Comment by Croydon** [comment]
This is done.
