### ISSUE TITLE
env::current_exe().expect() panic when running in Gecko reftest

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#12520]
When I run Stylo-enabled firefox in reftest (`./mach reftest`), firefox crashes because the code in [components/util/resource_files.rs](https://github.com/servo/servo/blob/master/components/util/resource_files.rs#L39) failed to get the `env::current_exe()`. This function is called when `properties.mako.rs` wants to find if a PropertyDeclaration is experimental, by getting the `prefs.json` from `resources` ([example](https://github.com/servo/servo/blob/master/components/style/properties/properties.mako.rs#L968)).

I removed all the `::util::prefs::PREFS.get()` call and it does not crash anymore.

The reftest runner runs Firefox by `subprocess.Popen` inside a python `threading.Thread`, not sure if it's related to the way it's called.

@Manishearth any insight into this?

**Comment by Manishearth** [comment]
current_exe() might not work if the outer program is not a Rust one.

We should just fallback to default prefs there.

**Comment by shinglyu** [comment]
OK, I'll try submitting a patch for that.
