### ISSUE TITLE
Style sharing candidate cache code is probably not working as intended.

### ISSUE THREAD

**Issue by emilio** [servo/servo#12534]
We basically end up never sharing in normal websites.

Just tested with the following patch applied:

```diff
diff --git a/components/style/dom.rs b/components/style/dom.rs
index ee40e8a..a94ecf2 100644
--- a/components/style/dom.rs
+++ b/components/style/dom.rs
@@ -16,6 +16,7 @@ use selector_impl::{ElementExt, SelectorImplExt};
 use selectors::Element;
 use selectors::matching::DeclarationBlock;
 use sink::Push;
+use std::fmt::Debug;
 use std::ops::BitOr;
 use std::sync::Arc;
 use string_cache::{Atom, Namespace};
@@ -45,7 +46,7 @@ impl OpaqueNode {
     }
 }
 
-pub trait TRestyleDamage : BitOr<Output=Self> + Copy {
+pub trait TRestyleDamage : BitOr<Output=Self> + Copy + Debug {
     fn compute(old: Option<&Arc<ComputedValues>>, new: &ComputedValues) -> Self;
     fn rebuild_and_reflow() -> Self;
 }
diff --git a/components/style/traversal.rs b/components/style/traversal.rs
index 76f8539..4bc7b2f 100644
--- a/components/style/traversal.rs
+++ b/components/style/traversal.rs
@@ -228,6 +228,7 @@ pub fn recalc_style_at<'a, N, C>(context: &'a C,
                 }
             }
             StyleSharingResult::StyleWasShared(index, damage) => {
+                panic!("\n\nSharing Style! {}, {:?}", index, damage);
                 style_sharing_candidate_cache.touch(index);
                 node.set_restyle_damage(damage);
             }
```

And I've never been able to hit this panic within normal browsing.

Just did a test run locally with this patch applied of `./mach test-css`, and the results were:

```
Ran 9977 tests finished in 3659.0 seconds.
  • 9362 ran as expected. 132 tests skipped.
  • 601 tests timed out unexpectedly
  • 14 tests passed unexpectedly
```

Presumably the unexpected passes are due to font or similar issues. All the 601 tests that crashed (or at least, everyone of them I could see) were svg tests under `/css-transforms-1_dev/html/svg-*`.

I'll take a look to see if there's something obvious we're doing bad. AIUI the objective of this cache is to share style between huge amounts of siblings, right?

Another experiment, probably more relevant that the CSS test suite. Ideally this file should hit the style sharing candidate cache:

```html
<!doctype html>
<style>
  div { display: block; background: red; margin: 5px; width: 50px; height: 50px; }
</style>
<div></div>
<div></div>
<div></div>
<!-- x500 -->
<div></div>
```

Yet it doesn't, **even without UA stylesheet**. Tomorrow I'll probably experiment more.

cc @pcwalton

**Comment by emilio** [comment]
I'm looking into this.

**Comment by pcwalton** [comment]
> AIUI the objective of this cache is to share style between huge amounts of siblings, right?

@emilio Yes. This has regressed multiple times :(

**Comment by emilio** [comment]
I have an alternative design for it that hopefully doesn't block on all
pseudo-classes (or on most applicable declarations that we didn't handle
for what it's worth).

I'll post some update soon :-)

**Comment by emilio** [comment]
@pcwalton: So I gave a shot at the attributes stuff, but that doesn't prevent other whole kind of pathological cases, unfortunately.

What I'm thinking though (I'd want to like your opinion), is the following: What about getting all the rules that might affect two siblings of the same type (that is, those with `+` and `~` combinators in their rightmost selector, `:{first, last, nth}-{child, of-type}`, etc? And make the cache optimistic, then reject matching that subset?

Does that sound plausible to you? It seems like would prevent a lot of early-rejections we do to ensure we always work.
