### ISSUE TITLE
Escape injected URLs in servohtmlparser

### ISSUE THREAD

**Issue by johannhof** [servo/servo#12542]
In #12539 we almost introduced an XSS vulnerability by injecting the unescaped URL into the neterror.html page. We do the same injection for displaying images. We should find a way to escape these.

**Comment by jdm** [comment]
"for displaying images"?

**Comment by johannhof** [comment]
I was referring to https://github.com/servo/servo/blob/master/components/script/dom/servohtmlparser.rs#L115. Am I misreading that code?

**Comment by jdm** [comment]
Nope! I was forgetting about it.

**Comment by nox** [comment]
Wait, why do we need this at all? Why not just use DOM to build a proper `img` tag etc?
