### ISSUE TITLE
Implement FileReader::readAsArrayBuffer

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#12555]
Blocks #10778.
- Spec: https://w3c.github.io/FileAPI/#readAsArrayBuffer.
- Code: `components/script/dom/filereader.rs`.
- Test: `FileAPI/idlharness.html`, `FileAPI/idlharness.worker`, `FileAPI/reading-data-section/FileReader-multiple-reads.html`, `FileAPI/reading-data-section/filereader_readAsArrayBuffer.html`, `FileAPI/reading-data-section/filereader_result.html`.

This will probably involve some JSAPI usage.

**Comment by cynicaldevil** [comment]
could I try my hand this too? I have already picked an easy issue but that won't take too much time to complete.

**Comment by KiChjang** [comment]
@cynicaldevil Sure! This looks like an interesting issue for you. Find us here or on `irc.mozilla.org` at #servo if you have any questions.

**Comment by jdm** [comment]
One relevant JSAPI piece is probably [JS_NewArrayBuffer](https://github.com/servo/rust-mozjs/blob/master/src/jsapi_linux_64.rs#L9914).

**Comment by cynicaldevil** [comment]
Ok, I think I know how to implement it. Imo, it requires [JS_NewArrayBufferWithContents](http://doc.servo.org/js/jsapi/fn.JS_NewArrayBufferWithContents.html), which requires a context object as one of the parameters. I only have a rough idea of what a context is, and I don't know which one to pass here.

**Comment by jdm** [comment]
`self.global().r().get_cx()` will get youo the JSContext pointer you're looking for.

**Comment by jdm** [comment]
It's probably safer to use `JS_NewArrayBuffer`, obtain the pointer to the [array buffer data](http://doc.servo.org/js/jsapi/fn.JS_GetArrayBufferData.html), then copy the data from the file reader source into the destination.

**Comment by cynicaldevil** [comment]
I have encountered another small issue: The `FileReaderMethods` trait [here](http://doc.servo.org////src/script/home/servo/buildbot/slave/doc/build/target/debug/build/script-4d3bb93218cab884/out/Bindings/FileReaderBinding.rs.html#1076-1095) does not have a `readAsArrayBuffer` method signature, so even though I have implemented it for `FileReader` I cannot build it. The file which I linked is auto-generated, so I am unable to add the signature manually.

**Comment by izgzhen** [comment]
@cynicaldevil Drop the comment sign https://github.com/servo/servo/blob/master/components/script/dom/webidls/FileReader.webidl#L13 should solve your problem.

btw, the blob code are mostly written by me so if you have any related problems, feel free to ping me ;)

**Comment by cynicaldevil** [comment]
@izgzhen Thanks, will do :)

**Comment by cynicaldevil** [comment]
I have implemented most of `readAsArrayBuffer` now, [here](https://github.com/cynicaldevil/servo/commit/5b1e1f51c9f65c180c562f3fc748be43727afd20).
I have used the `BlobOrString` enum instead of `DOMString`, and when I try to build it, I get errors stating certain methods were not implemented for `BlobString`. Where and how do I implement them?

**Comment by izgzhen** [comment]
First, I just found there is some difference between [current version of `FileReader` IDL spec](https://w3c.github.io/FileAPI/#APIASynch) and the one in the servo source:

```diff
diff --git a/components/script/dom/webidls/FileReader.webidl b/components/script/dom/webidls/FileReader.webidl
index 45ae6ea..c4f2d70 100644
--- a/components/script/dom/webidls/FileReader.webidl
+++ b/components/script/dom/webidls/FileReader.webidl
@@ -4,16 +4,13 @@
 
  // http://dev.w3.org/2006/webapi/FileAPI/#APIASynch
 
-//typedef (DOMString or ArrayBuffer) FileReaderResult;
 [Constructor, Exposed=(Window,Worker)]
 interface FileReader: EventTarget {
 
   // async read methods
-  //[Throws]
-  //void readAsArrayBuffer(Blob blob);
-  [Throws]
+  void readAsArrayBuffer(Blob blob);
+  void readAsBinaryString(Blob blob);
   void readAsText(Blob blob, optional DOMString label);
-  [Throws]
   void readAsDataURL(Blob blob);
 
   void abort();
@@ -22,15 +19,16 @@ interface FileReader: EventTarget {
   const unsigned short EMPTY = 0;
   const unsigned short LOADING = 1;
   const unsigned short DONE = 2;
+
+
   readonly attribute unsigned short readyState;
 
   // File or Blob data
-  //readonly attribute FileReaderResult? result;
-  readonly attribute DOMString? result;
+  readonly attribute (DOMString or ArrayBuffer)? result;
 
-  readonly attribute DOMException? error;
+  readonly attribute DOMError? error;
 
-  // event handler attributes
+  // event handler content attributes
   attribute EventHandler onloadstart;
   attribute EventHandler onprogress;
   attribute EventHandler onload;
```

You may want to update this first. Sorry for not reminding you of this possible problem.

**Comment by izgzhen** [comment]
And since there is no binding support yet, I am afraid that union type of `ArrayBuffer` and `DOMString` might not work. but anyway you should not use `Blob`, since blob doesn't support this thing now either :(

Well ... I am not very sure about how to handle this condition

**Comment by jdm** [comment]
(DOMString or object)?

**Comment by izgzhen** [comment]
Really? Oh, maybe because DOMString is a primitive so it can work

**Comment by cynicaldevil** [comment]
So which type should I use then?

**Comment by jdm** [comment]
Does `(DOMString or object)?` work? If not, you'll need to just use `any` instead of a union.

**Comment by KiChjang** [comment]
I'm more inclined to comment out the `ArrayBuffer` part here and file a follow-up issue to fix it once we have bindings support for it.

**Comment by jdm** [comment]
@KiChjang The point of this issue is to support ArrayBuffer results from FileReader...

**Comment by KiChjang** [comment]
@jdm We can support DOMString results first before we support ArrayBuffer results, yes?

**Comment by jdm** [comment]
We already do.

**Comment by cynicaldevil** [comment]
Sorry for the long delay in replying, I was facing some issues with my laptop.
@jdm I looked up the docs [here](http://doc.servo.org/script/dom/bindings/codegen/UnionTypes/index.html), `DOMStringOrObject`  doesn't exist. Wouldn't it be better to add support for `BlobOrString` by implementing the reqd. traits?

**Comment by Ms2ger** [comment]
The union type will be generated automatically when you use it in IDL.

**Comment by cynicaldevil** [comment]
I am getting an assertion error in implementing the `DOMString or object` type. The error occurs [here](https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py#L4006) according to the backtrace.

**Comment by Ms2ger** [comment]
That just means "not yet implemented". You could try to implement it; otherwise I'll try to look at it next week.

**Comment by cynicaldevil** [comment]
@Ms2ger I want to try it. Could you give me some advice/tips to help me?

**Comment by Ms2ger** [comment]
Start out by removing the assertion you hit, and add the `type.isObject()` case to the if-else chain right above that. `name` should be `Object` and `typeName` should be `*mut JSObject`. With a bit of luck, we'll generate (mostly) working code with that change.

**Comment by cynicaldevil** [comment]
I have run into a little hurdle in the codegen part. I have to import `JSObject` in `Uniontypes.rs` to use it for the `Object` type, and I know that the `Uniontypes.rs` file is generated from [here](https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py#L6905), but I cannot figure out how to add the `use` statement for `JSObject` to it.

**Comment by jdm** [comment]
Add an entry to the `imports` list inside the `UnionTypes` method.

**Comment by cynicaldevil** [comment]
@jdm That's what I thought first, but then I opened the auto-generated `UnionTypes.rs` file and saw that it contained many other imports too, so I thought it had something to do with the `getDescriptors()` or `getDictionaries()` method.

**Comment by cynicaldevil** [comment]
@jdm I looked at the UnionTypes method again; it is a bit different from the other ones as it has a recursive call, and I can't figure out how it works.

**Comment by jdm** [comment]
@cynicaldevil There's the static method which calls the non-static function called the same thing in the same file.

**Comment by cynicaldevil** [comment]
I created a new method to convert the objects of type `StringOrObject` into `FileReaderResult` [here](https://github.com/cynicaldevil/servo/commit/6ac32ec3f30bcbe840d06d4d42254899b9fcb92b#diff-86a64de2e20a4f0e05816b3c9256087eR205). But then I realised that I need to convert the object back to `StringOrObject` type [here](https://github.com/cynicaldevil/servo/commit/6ac32ec3f30bcbe840d06d4d42254899b9fcb92b#diff-86a64de2e20a4f0e05816b3c9256087eR361). I wanted to ask if I am still on the right track here and how I should proceed now..

**Comment by jdm** [comment]
Yes, in order to store the js value it needs to live in a Heap object, but that's not something we should return to the bindings. The one main problem I see in the current code is that convertToFileReaderResult isn't safe - Heap values need to be created with a default value, then initialized with the real JS value afterwards, like https://dxr.mozilla.org/servo/source/components/script/dom/bindings/callback.rs#103 . I think it would make more sense to inline `convertToFileReaderResult` in the caller, rather than having a separate method for it.

**Comment by nonoyek** [comment]
Is there anyway to make it work? Can i implement the "readAsArrayBuffer" manually? need to use it for my project.. stuck half way.. need help guyss..
