### ISSUE TITLE
Browserhtml content not resized when window is resized.

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12550]
From the latest nightly: (7/21/2016)
<img width="1407" alt="screen shot 2016-07-21 at 10 21 08 pm" src="https://cloud.githubusercontent.com/assets/9086315/17046530/a3aa253c-4f91-11e6-8018-2c7663169aab.png">

There are also black lines at the top and bottom of the windows that were not previously there.

**Comment by jonathandturner** [comment]
I've noticed this is true for the view port also.  

![screen shot 2016-08-05 at 5 11 05 pm](https://cloud.githubusercontent.com/assets/547158/17453346/a2d6c954-5b2f-11e6-919d-443ea794d455.png)

**Comment by ConnorGBrewster** [comment]
Dupe of #12835 (it has better info)
