### ISSUE TITLE
Implement Runnable::name for WebSocket Runnables.

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12551]
Each Runnable in `websocket.rs` needs to implement the `Runnable::name` method. It needs to return the name of the Runnable as a `&'static str`.

Runnables:
`ConnectionEstablishedTask`
`BufferedAmountTask`
`CloseTask`
`MessageReceivedTask`

---
code: `components/script/dom/websocket.rs`
example: https://dxr.mozilla.org/servo/source/components/script/dom/document.rs#2919
No tests are needed, it just need to compile.

**Comment by cynicaldevil** [comment]
I'll take it!

**Comment by jdm** [comment]
It's yours!
