### ISSUE TITLE
./mach test-tidy --self-test failing

### ISSUE THREAD

**Issue by simartin** [servo/servo#12564]
There are two failures:
test_file_list (servo_tidy_tests.test_tidy.CheckTidiness) ... FAIL
test_toml (servo_tidy_tests.test_tidy.CheckTidiness) ... FAIL

The first one is a consequence of https://github.com/servo/servo/pull/12313/commits/6c6bfdb523f5068a13422f91ed0766e6dc4575d5, the second of https://github.com/servo/servo/commit/9fa54af34794df663d02634860b8a6586f47f81b

I'm working on a patch so the issue can be assigned to me

**Comment by jdm** [comment]
Does this not run in .Travis.yml?

**Comment by simartin** [comment]
It does but does not fail the build... See https://github.com/servo/servo/pull/12567
