### ISSUE TITLE
Implement HTMLLIElement#value

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#12575]
In order to parse the value attribute value as an integer, the `parse_plain_attribute` function from the `VirtualMethods` trait should be implemented accordingly.

Spec: https://html.spec.whatwg.org/multipage/semantics.html#dom-li-value
Code: `components/script/dom/htmllielement.rs`, `components/script/dom/webidls/HTMLLIElement.webidl`
Test: tests/wpt/web-platform-tests/html/semantics/grouping-content/the-li-element/grouping-li.html

**Comment by vrod** [comment]
Can I take this one too?

**Comment by KiChjang** [comment]
Yes, that's fine.
