### ISSUE TITLE
Write a test for HTMLDialogElement#open

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#12574]
Spec: https://html.spec.whatwg.org/multipage/forms.html#dom-dialog-open
Code: `components/script/dom/htmldialogelement.rs`, `components/script/dom/webidls/HTMLDialogElement.webidl`
Test: None yet, will need to write one (`./mach create-wpt tests/wpt/web-platform-tests/html/semantics/interactive-elements/the-dialog-element/dialog-open.html`)

**Comment by vrod** [comment]
I'll take this one.

**Comment by KiChjang** [comment]
Sure thing!

**Comment by KiChjang** [comment]
Oops, I just realized that HTMLDialogElement#open has already been implemented, but it lacks a WPT test.
