### ISSUE TITLE
bluetooth: min BlueZ version 

### ISSUE THREAD

**Issue by beaufortfrancois** [servo/servo#12584]
For info, the Chromium team has increased BlueZ min version to `5.41` as the awesome BlueZ team fixed some GATT related bugs but more importantly introduced a brand new `ServicesResolved` property that makes device services discovery much more reliable. See http://git.kernel.org/cgit/bluetooth/bluez.git/commit/doc/device-api.txt?id=4ed99044f49af9ef21c89b283399112cddfe68c0

@dati91 @larsbergstrom

**Comment by nox** [comment]
That doesn't seem like an actionable issue. Closing.
