### ISSUE TITLE
Utilise cancel listener for reading content from file manager

### ISSUE THREAD

**Issue by izgzhen** [servo/servo#12589]
See `net/blob_loader.rs` for where the cancel listener is introduced, and it is currently not utilised.

After #12577 is landed, this would be a problem since we can choose to cancel early rather than keep reading.

But here is actually some problem to do that -- the `CancellationListener` defined in `resource_thread.rs` can't be sent over some ipc-channel to the `FileManager`.

**Comment by izgzhen** [comment]
cc @Manishearth

**Comment by Manishearth** [comment]
The File manager and resource thread should be communicating via regular mpsc channels, not IPC.

AIUI this shouldn't be a problem -- we should be doing exactly the same thing as http_loader, right?

**Comment by izgzhen** [comment]
Not exactly the same -- file manager lives in another thread, while http_loader (corresponding to blob_loader) is in the CoreResourceThread. I think I need to open another `mpsc` channel rather than reusing the same `IpcSender` which is also shared with script ends.

**Comment by Manishearth** [comment]
Oh, right.

Is this necessary? We probably should be uniform across the loaders. Each operation spawns a new thread anyway, so this won't load the core thread.

**Comment by izgzhen** [comment]
>  Each operation spawns a new thread anyway, so this won't load the core thread.

Can you elaborate on it?

**Comment by Manishearth** [comment]
As in, we should do the same thing http_loader is doing for blob requests, and furthermore handle file manager messages directly on the core resource manager. Have a message variant "ToFileManager(FileManagerMsg)" which can get sent to the core resource manager, which will spawn a thread to handle that message. The file manager is then just a field in the resource manager. We keep the msg handling impls in file_manager.rs
