### ISSUE TITLE
Error navigator.bluetooth.requestDevice(...).then is not a function

### ISSUE THREAD

**Issue by beaufortfrancois** [servo/servo#12583]
First of all, **thanks for working on Web Bluetooth support on Servo**!

As you can see in the screenshots below, I was able to select a Bluetooth device from Servo but as soon as I hit "select" button, I get nothing but a JS error. Any idea what is happening in Servo 0.0.1-2d01788? 

```
ERROR:js::rust: Error at https://googlechrome.github.io/samples/web-bluetooth/battery-level.html:2:3: 
navigator.bluetooth.requestDevice(...).then is not a function
```

![screenshot from 2016-07-25 10-37-11](https://cloud.githubusercontent.com/assets/634478/17095834/d65ab164-5256-11e6-92a2-b3ebde517afd.png)
![screenshot from 2016-07-25 10-37-21](https://cloud.githubusercontent.com/assets/634478/17095835/d65f8a04-5256-11e6-8ca9-9e935988f667.png)

cc @larsbergstrom @dati91

**Comment by dati91** [comment]
Hi!

Servo doesn't support Promises (yet).
You can call function like [this](https://github.com/servo/servo/blob/master/tests/html/bluetooth_battery_level.html).

**Comment by beaufortfrancois** [comment]
Makes sense! Thank you @dati91 ;)

**Comment by beaufortfrancois** [comment]
See https://github.com/servo/servo/commit/e04b7ee485380008612f5284b289fd1b769fe8d1

**Comment by dati91** [comment]
We have a PR about the tests here: https://github.com/servo/servo/pull/12556

**Comment by beaufortfrancois** [comment]
May I let you take care of changing all `optinalServices` occurences to `optionalServices` in this PR?

**Comment by dati91** [comment]
Yeah, already on it :) thanks for noticing it

**Comment by beaufortfrancois** [comment]
FYI, https://plus.google.com/+FrancoisBeaufort/posts/gfPULNowQv7

**Comment by beaufortfrancois** [comment]
Closing this non-bug.
