### ISSUE TITLE
Reduce dependency on shared mutable state in util::opts

### ISSUE THREAD

**Issue by djc** [servo/servo#12581]
As I'm familiarizing myself with the Servo code base, I came across the `util::opts` module. Having the option state there and having numerous crates depend on that state seems like bad design, creating a weirdly tight coupling between these crates (including `compositing`, `gfx`, `layout`, `net` and a few others) and the `util::opts` module.

In 29c7c5bec33521cb23c5fba478bd5431f15f52ed, I already severed the dependency of the `canvas` crate on `util::opts`. With #12560, I'm trying to remove the usage of the `layout_threads` option from the `layout_thread` crate.

**Comment by nox** [comment]
The situation on that regard could still be improved.

**Comment by dralley** [comment]
Will layout 2020 address this?

**Comment by jdm** [comment]
This is unrelated to layout 2020. However, this is tracked in more detail in #22854.
