### ISSUE TITLE
Link to anchor identified by name attribute within same page not doing anything

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12587]
I was wondering if links to anchors within the same page are currently implemented? 

An example would be when there is some sort of "Jump to bottom" or "Jump to top" feature at the beginning/end of a long body of text:

```
<a href="#end">Jump to end</a>
<div>
Lipsum....
Lots of text making a scroll...
...
...
<a name="end">End of text</a>
</div>
```

With the above example (with dummy text long enough to cause the page to have a scroll), clicking the "Jump to end" link in Servo does nothing.

Online test case [here](https://samuknet.github.io/test_cases/anchorInPage/).

Also, navigating directly to [https://samuknet.github.io/test_cases/anchorInPage#end](https://samuknet.github.io/test_cases/anchorInPage#end) in Servo does cause the page to be 'already scrolled' to the end of the text.

Thanks

**Comment by jdm** [comment]
They're supposed to work, yes.

**Comment by samuknet** [comment]
okay thanks :) For me, the link in this example [here](https://samuknet.github.io/test_cases/anchorInPage/) is not working in Servo. Any ideas?

**Comment by jdm** [comment]
I stepped through the code, and I don't have a good answer yet. `Document::find_fragment_node` is called when processing the navigation that's initiated by clicking the link, and that calls `Document::get_anchor_by_name` which correctly looks at the two anchors in the document. The first one does not have a `name` attribute as expected, but the second is reported to have a `name` attribute with an empty value, so it doesn't match the fragment we're looking for.

**Comment by sole** [comment]
Perhaps giving `h1` the `id` the value the anchor name was supposed to use could work? As in `<h1 id="#end">`? 🤔

**Comment by jdm** [comment]
As a workaround that's worth trying. This particular instance looks like a Rust compiler bug to me, so thanks for finding it!

**Comment by samuknet** [comment]
Have just tried the id="end" and that doesn't work either unfortunately, if this helps

**Comment by jdm** [comment]
I've stepped through the `id` case as well, and that actually finds the element and instructs the compositor to scroll the view to it. I suspect that the big FIXME in `ScriptThread::scroll_fragment_point` is hitting us here, since the result of the bounding box calculation is (0, 0, 0, 0). Could you file a separate issue for this case, since it a different problem?

**Comment by samuknet** [comment]
For the "anchor identified by ID attribute" case: https://github.com/servo/servo/issues/12590

**Comment by jdm** [comment]
Ah, my mistake; I'm not sure why lldb is showing me the values it is, but my original diagnosis of a miscompilation was incorrect. Both the id and name codepaths find the node and hit the problem described in #12590. I'm going to close this issue in favour of that one to avoid confusing things.
