### ISSUE TITLE
Mac test-css taking an extra hour and 10 minutes

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#12596]
Looking at mac-rel-css, test-css is taking 1 hour 35 minutes on a macpro.

That's based on the reporting from: http://build.servo.org/builders/mac-rel-css/builds/2210:

```
    git update ( 5 secs )
        stdio
    shell 'pkill -x ...' ( 0 secs )
        stdio
    compile compile ( 17 mins, 30 secs )
        stdio
    test test ( 1 hrs, 35 mins, 16 secs )
        stdio
        test-css.log
        css-errorsummary.log
    compile_1 compile warnings ( 2 mins, 6 secs )
        stdio
        warnings (92)
    shell_1 'bash ./etc/ci/lockfile_changed.sh' ( 0 secs )
        stdio
    shell_2 'bash ./etc/ci/manifest_changed.sh' ( 48 secs )
        stdio
```

_But_ the stdout: http://build.servo.org/builders/mac-rel-css/builds/2210/steps/test/logs/stdio says 1286 seconds, or 21.4 minutes.

```
Ran 9977 tests finished in 1286.0 seconds.
  • 9977 ran as expected. 132 tests skipped.

program finished with exit code 0
elapsedTime=1296.938549
```

What in the world is going on? Crash dump reporting appears to be disabled. I didn't see any other apps running on the system that seemed like obvious culprits.

cc @edunham

**Comment by edunham** [comment]
The mac pro is out of rotation now and we haven't seen the isseu in awhile, so closing. Please reopen if this is still actionable.
