### ISSUE TITLE
Provide a Homebrew's binary packages for servo nightly

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#12600]
https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Bottles.md

Nightly builds are provided as dmg, and with the browserhtml UI. It would be nice to be able to install and use Servo without browserhtml, as a Homebrew package.

The package could be updated every day along Servo nighty.

I used to provide builds via homebrew: https://github.com/paulrouget/homebrew-servo/blob/master/Formula/ This was a quick hack, not sure if we should re-use this, but it's here.

**Comment by paulrouget** [comment]
Relevant scripts:

- https://github.com/servo/saltfs/blob/a781db87fcd1d4e512be092775e239c0d6377369/buildbot/master/files/config/steps.yml#L25
- https://github.com/servo/servo/blob/master/etc/ci/upload_nightly.sh

**Comment by paulrouget** [comment]
Log from IRC:

@larsberg> paul: nightly upload scripts are split between https://github.com/servo/servo/blob/master/etc/ci/upload_nightly.sh (which does the actual publishing of a file to s3) and the various *-nightly rules in https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/steps.yml

13:43 <@larsberg> the latter is what configures the exact build to perform and the packaging step to call and then delegates to upload_nightly to do the actual publish

**Comment by HarryLovesCode** [comment]
@paulrouget Is Homebrew the correct choice for this? I'm not sure if you're aware, but there is a tool called "Cask" which you can find [here](https://github.com/caskroom/homebrew-cask). The syntax would go from:

```
brew install servo
```

to

```
brew cask install servo

==> Downloading https://download.servo.org/nightly/mac/servo-latest.dmg
######################################################################## 100.0%
==> No checksum defined for Cask servo, skipping verification
==> Moving App 'Servo.app' to '/Applications/Servo.app'
🍺  servo was successfully installed!
```

You can find the current script [here](https://github.com/caskroom/homebrew-cask/blob/7b49abdea1cb631678afce21c35dbb330bc77c13/Casks/servo.rb). The description for Cask's repository is as follows:

> Homebrew-Cask extends Homebrew and brings its elegance, simplicity, and speed to the installation and management of GUI macOS applications such as Google Chrome and Adium.

**Comment by nox** [comment]
@jdm Should we also close that one?

**Comment by jdm** [comment]
Yeah, I don't see any reason to track this work.
