### ISSUE TITLE
Image opacity on hover not changing

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12602]
When there is an image setup for its opacity to increase to 1 on hover, hovering over the image does not cause its opacity to change. 

When a property such a 'border: 5px solid black' is added into the hover state, the opacity and border properties change as expected on hover.

```
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
body {
	font-family: helvetica;
}
img {
	opacity: 0.5; /* Opacity must be set to anything other than 1 for the white rectangle to appear */
}

img:hover {
	opacity: 1;
	/*border: 5px solid red; */ /* Adding something like this makes the image display as expected on hover
}
</style>
</head>

<body>

<img src="servo.png" />
<p>Hovering over the image should set the opacity to full, however nothing happens.  Adding a property such as 'border' onto the :hover state makes the opacity change on hover as expected.</p>
</body>
</html>
```

This could be related to https://github.com/servo/servo/issues/11891.

Online test case [here](https://samuknet.github.io/test_cases/imageOpacityHover).

**Comment by jdm** [comment]
This is another issue caused by incremental layout. Running with `-i` make it work as expected.

**Comment by jdm** [comment]
I thought it would be enough to add `get_effects.opacity` to the REPAINT block in `compute_damage`; it wasn't. Then I thought it would be enough to expand the `transform_needs_layer` check for opacity changing to and from 1.0, which would change the layerization behaviour. That made the testcase work, but if the opacity value is changed to 0.9 instead of 1.0 it breaks again.

**Comment by jdm** [comment]
My other suspicion was that forcing the display list to always be rebuilt in `compute_abs_pos_and_build_display_list` would fix this, but there was no change.

**Comment by jdm** [comment]
```diff
diff --git a/components/script_layout_interface/restyle_damage.rs b/components/script_layout_interface/restyle_damage.rs
index c100509..fa53bc2 100644
--- a/components/script_layout_interface/restyle_damage.rs
+++ b/components/script_layout_interface/restyle_damage.rs
@@ -168,7 +168,7 @@ fn compute_damage(old: Option<&Arc<ServoComputedValues>>, new: &ServoComputedVal
         get_box.float, get_box.display, get_box.position, get_counters.content,
         get_counters.counter_reset, get_counters.counter_increment,
         get_inheritedbox._servo_under_display_none,
-        get_list.quotes, get_list.list_style_type,
+        get_list.quotes, get_list.list_style_type, get_effects.opacity,

         // If these text or font properties change, we need to reconstruct the flow so that
         // text shaping is re-run.
```
This change makes opacity values of both 1.0 and otherwise work. RECONSTRUCT_FLOWS is the flag that's necessary; I want to figure out why that's the case.

**Comment by jdm** [comment]
```diff
diff --git a/components/layout/construct.rs b/components/layout/construct.rs
index 809ecaa..e79301b 100644
--- a/components/layout/construct.rs
+++ b/components/layout/construct.rs
@@ -1460,6 +1460,7 @@ impl<'a, ConcreteThreadSafeLayoutNode: ThreadSafeLayoutNode>
                             // TODO: Add code to find and repair the ScannedText fragments?
                             return false
                         }
+                        SpecificFragmentInfo::Image(_) => return false,
                         _ => {
                             if node.is_replaced_content() {
                                 properties::modify_style_for_replaced_content(&mut style);
diff --git a/components/script_layout_interface/restyle_damage.rs b/components/script_layout_interface/restyle_damage.rs
index c100509..88136fd 100644
--- a/components/script_layout_interface/restyle_damage.rs
+++ b/components/script_layout_interface/restyle_damage.rs
@@ -241,7 +241,7 @@ fn compute_damage(old: Option<&Arc<ServoComputedValues>>, new: &ServoComputedVal
         get_effects.box_shadow, get_effects.clip, get_inheritedtext.text_shadow, get_effects.filter,
         get_effects.transform, get_effects.backface_visibility, get_effects.transform_style,
         get_effects.transform_origin, get_effects.perspective, get_effects.perspective_origin,
-        get_effects.mix_blend_mode, get_inheritedbox.image_rendering,
+        get_effects.mix_blend_mode, get_inheritedbox.image_rendering, get_effects.opacity,

         // Note: May require REFLOW et al. if `visibility: collapse` is implemented.
         get_inheritedbox.visibility
```
This also works, and only sets the REPAINT flag. I need to figure out why making image fragments non-repairable avoids the issue, however.

**Comment by jdm** [comment]
If the image fragment doesn't get repaired, we construct a flow for the image element in `construct_flows_at`, and we later build a display list. If the image fragment gets repaired, we don't build a display list. I haven't determined what the relationship is yet.

**Comment by jdm** [comment]
I had a theory that we were incorrectly clearing the REPAINT bit from the restyle damage in `construct_flows_at` for the case where the flow was repaired, but that did not make any difference.

**Comment by splav** [comment]
Actually there is another bug in this case for current master with -i switch the text under the image disappears.
