### ISSUE TITLE
Image with opacity gets clipped when nearby text input 'overflows' with characters

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12601]
The issue occurs when there is a text input near an image and the text input is 'filled up' with characters.  As soon as the text input overflows a white rectangle clips the corner of the image. This happens as soon as the text field has a character entered that makes it's size too small to display all the characters.

Additionally, the issue only occurs when the image has a CSS property set to anything other than 1.  Also, the image needs to be within a certain 'closeness' to the text input in order for the issue to occur.

<img width="256" alt="noclip" src="https://cloud.githubusercontent.com/assets/9294710/17134550/dd205da6-5322-11e6-88c9-efd46fad5694.png">
###### Above: The image is not clipped as the text field has not 'overflowed' with characters</small>
<img width="256" alt="clip" src="https://cloud.githubusercontent.com/assets/9294710/17134549/dd1e4e62-5322-11e6-99bd-b34d384e7abb.png">
###### Above: The image has been clipped as soon as a character is entered that makes the input text too long for the size.

Example:
```
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
body {
	text-align: center;
}

img {
	opacity: 0.9; /* Opacity must be set to anything other than 1 for the white rectangle to appear */
}
</style>
</head>

<body>

<img src="https://pbs.twimg.com/profile_images/621055164510658560/Cj-wqR55.png" />
<input type="text" size="35" value="One character over the size causes the issue" /> <!-- Removing characters so that the text input is not filled up stops the issue from occuring. !-->
</body>
</html>
```

Online test case [here](https://samuknet.github.io/test_cases/opacityImageClip).

**Comment by jdm** [comment]
The testcase does not reproduce the problem if I run with webrender enabled.

**Comment by samuknet** [comment]
@jdm My bad! I omitted the flag somehow 😊
