### ISSUE TITLE
Implement HTMLAreaElement#download attribute

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#12607]
The implementation of this attribute should be straightfoward and use the `make_getter!` and `make_setter!` macros defined in `macros.rs`.

Spec: https://html.spec.whatwg.org/multipage/embedded-content.html#htmlareaelement
Files: `components/script/dom/htmlareaelement.rs`, `components/script/dom/webidls/HTMLAreaElement.webidl`
Test: None yet, will need to create one using `./mach create-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/the-area-element/area-download.html`

**Comment by Coder206** [comment]
@KiChjang Thanks, I would like to work on this one.

**Comment by KiChjang** [comment]
You got it!

**Comment by Coder206** [comment]
@KiChjang Was this what you were looking for in "components/script/dom/htmlareaelement.rs"?

`//https://html.spec.whatwg.org/multipage/embedded-content.html#htmlareaelement
    make_getter!(Download, "download");

    //https://html.spec.whatwg.org/multipage/embedded-content.html#htmlareaelement
    make_setter!(SetDownload, "download");`

**Comment by KiChjang** [comment]
Yes, but the spec links need to be changed to `https://html.spec.whatwg.org/multipage/#htmlareaelement` (without the `.html` part), otherwise tidy will complain.

**Comment by Ms2ger** [comment]
Should we do this before implementing the appropriate behaviour? CC @jdm

**Comment by Coder206** [comment]
@KiChjang Ok, great. I tried compiling and there was an error: 

`error: no rules expected the token `"download"``

I made modifications to the webidl file as well, I uncommented the download attribute. 

Is there something I am doing wrong here?

Code: 

Rust: https://pastebin.mozilla.org/8887262
WebIDL: https://pastebin.mozilla.org/8887263

**Comment by KiChjang** [comment]
It looks like servo/string_cache doesn't have an atom for "download". You'll need to first make a PR for string_cache, adding "download" to `static_atom_list.rs`.

**Comment by Coder206** [comment]
@KiChjang Ok thanks

**Comment by jdm** [comment]
Yeah, we have a policy of trying to avoid implementing attributes that affect the behaviour of the element without implementing the relevant behaviour.

**Comment by Coder206** [comment]
@jdm So we would need to implement the download attribute's behaviour as well?

**Comment by jdm** [comment]
Right, but we don't have any support for saving files instead of navigating to them yet, so it's a much more complicated project.

**Comment by jdm** [comment]
Additionally our `<area>` implementation is nonexistent, so that in itself is a large, complicated project.

**Comment by KiChjang** [comment]
Apologies @Coder206, it looks like this feature isn't intended at this time. Thanks for digging into it!

**Comment by Coder206** [comment]
@KiChjang It's fine!
