### ISSUE TITLE
Step annotations for files related to WebBluetooth

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#12614]
cc @zakorgy

**Comment by zakorgy** [comment]
Cant his issue also contain the following WebBluetooth related files? ` bluetooth.rs`, `bluetoothremotegattdescriptor.rs`, `bluetoothremotegattserver.rs` `bluetoothremotegattservice.rs`.
These files includes the following list of functions, which has no annotations yet.
- [ ] requestDevice
- [ ] getDescriptor
- [ ] getDescriptors
- [ ] readValue (characteristic)
- [ ] writeValue (characteristic)
- [ ] readValue (descriptor)
- [ ] writeValue (descriptor)
- [ ] connect
- [ ] disconnect
- [ ] getPrimaryService
- [ ] getPrimaryServices
- [ ] getCharacteristic
- [ ] getCharacteristics
- [ ] getIncludedService
- [ ] getIncludedServices

**Comment by KiChjang** [comment]
Yes, title is changed accordingly.

**Comment by zakorgy** [comment]
@KiChjang would you please reopen this issue? #13184 only fixes the requestDevice part.

**Comment by dati91** [comment]
https://github.com/servo/servo/issues/14324

**Comment by nox** [comment]
The two unchecked methods have step annotations now.
