### ISSUE TITLE
Use a reentrant mutex in constellation logging

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#12619]
We have a `Mutex` protecting the `constellation_chan` in constellation logging, for no particularly good reason. It may be the source of double-panic in #12553.

cc @jdm

**Comment by Ms2ger** [comment]
Why would it be unnecessary? Senders aren't Sync.

**Comment by asajeffrey** [comment]
Yes, I realized on trying it that the problem is that locks aren't re-entrant, which means that if any logging generates log entries, we get a panic. Really the issue needs a new title!

**Comment by asajeffrey** [comment]
Some IRC discussion about reentrant locking at https://botbot.me/mozilla/rust-internals/2016-07-28/?msg=70402734

We may be able to use some of the `parking_lot` and `thread-id` crates here. cc @Amanieu

**Comment by asajeffrey** [comment]
Renamed the issue.
