### ISSUE TITLE
Extract common parts of starting content process

### ISSUE THREAD

**Issue by jdm** [servo/servo#12622]
The `spawn_multiprocess` method has two branches for starting a content process sandboxed or not. We set common arguments on the resulting command, and copy over environment variable values (and #12563 adds some more of these). We should create a helper function that encapsulates these common operations and call it from both branches instead of duplicating the code.

Code: `components/constellation/pipeline.rs`

No need for running any tests; if it compiles, that's good enough for a PR.

**Comment by nc4rrillo** [comment]
@jdm mind if I take this one?

**Comment by jdm** [comment]
@nc4rrillo Please do!

**Comment by nc4rrillo** [comment]
I'm running into some difficulty. Gaol/libstd have different types for `Command` (L499 vs L516), making it unclear how I can write a function to extract the common functionality. 

I _was_ able to get it to work using a macro, I'm just not sure if that's an acceptable solution. Another possibility is maybe implementing a trait for both types and having a generic helper function be constrained on that. 

Thoughts? @jdm

**Comment by jdm** [comment]
Yeah, I think the trait is the best solution.
