### ISSUE TITLE
Uncatchable panic with no backtrace

### ISSUE THREAD

**Issue by jdm** [servo/servo#12626]
STR:
1. `./mach run https://samuknet.github.io/test_cases/iframeCSSRotate/ --debug`
2. `b rust_panic`
3. `run`
4. then wait 30s, then press escape
5. in the terminal:
```
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }
```
with no backtrace, and the breakpoint doesn't get hit before servo exits.

**Comment by jdm** [comment]
RUST_LOG=constellation::constellation showed me:
```
    DEBUG:constellation::constellation: constellation exiting
    DEBUG:constellation::constellation: Pipeline PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) } exited.
    DEBUG:constellation::constellation: constellation got key event message
    DEBUG:constellation::constellation: constellation got key event message
    DEBUG:constellation::constellation: constellation got key event message
    DEBUG:constellation::constellation: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) } exited.
    DEBUG:constellation::constellation: Exiting image cache.
    DEBUG:constellation::constellation: Exiting core resource threads.
    DEBUG:constellation::constellation: Exiting storage resource threads.
    DEBUG:constellation::constellation: Exiting file manager resource threads.
    DEBUG:constellation::constellation: Exiting bluetooth thread.
    DEBUG:constellation::constellation: Exiting service worker manager thread.
    DEBUG:constellation::constellation: Exiting font cache thread.
    DEBUG:constellation::constellation: Asking compositor to complete shutdown.
    DEBUG:constellation::constellation: Sending log entry Warn("Panic hook called."). 
```
Panics that occur after the constellation disappears are now more challenging to diagnose. I'm also concerned that `rust_panic` isn't being hit.

**Comment by jdm** [comment]
cc @asajeffrey

**Comment by asajeffrey** [comment]
@jdm: we could log the backtrace when the panic happens, rather than expecting the constellation to do it, we just need to make sure that the panic isn't printed twice.

**Comment by emilio** [comment]
FWIW, That's the kind of problem I tried to solve with #12591, though arguably something that works out of the box would be a much better solution.

**Comment by asajeffrey** [comment]
IRC chat with @jdm: http://logs.glob.uno/?c=mozilla%23servo&s=29+Jul+2016&e=29+Jul+2016#c491961

Summary: `println!` the backtrace if `RUST_BACKTRACE` is set.
