### ISSUE TITLE
Settle on a thread id implementation

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#12641]
I added a `ThreadId` type to `util`, it would be nice to have just one thread id implementation. cc @emilio

**Comment by nox** [comment]
@asajeffrey This issue can probably be made into a E-Easy one.

**Comment by kunalmohan** [comment]
Hi! Can I work on this issue?

**Comment by jdm** [comment]
@asajeffrey Do you remember what this issue was referring to?

**Comment by asajeffrey** [comment]
Hmm, this is a blast from the past... I think the problem at the time was that there were a lot of notions of thread id kicking around. We seem to have got rid of most of them, just the one in reentrant locking left. Is there a crate we could use instead of rolling our own thread ids in this case?

**Comment by jdm** [comment]
https://crates.io/crates/thread-id seems popular.

**Comment by jdm** [comment]
Then again, there's https://doc.rust-lang.org/stable/std/thread/struct.ThreadId.html in the standard library now.
