### ISSUE TITLE
Update README Install Documentation. 

### ISSUE THREAD

**Issue by jesusalc** [servo/servo#12673]
Just like it says. We need to update the Install docs, with more robust data.

**Comment by KiChjang** [comment]
Is there anything in particular that you think we should add?

**Comment by jesusalc** [comment]
If you look at https://github.com/servo/servo/issues/12356  You can see a very well documented Ubuntu 14.04.04 32bit and 64bit, Windows 7 32bit and 64bit documentation. Which looks very through to me. Also, there seem to be many tickets about "servo not building" or l related. Some of these issues could bring documentation to specific versions and situations. Which can make the documentation more complete.

**Comment by nox** [comment]
We regularly add missing requirements and steps when there are build failures filed here and we found out there was a missing dependency. This issue itself isn't very actionable because I don't know when it can be considered fixed. Closing it.
