### ISSUE TITLE
Linux: Nightly build doesn't run due to libav version mismatch.

### ISSUE THREAD

**Issue by benwaffle** [servo/servo#12687]
Servo wants `libavformat.so.54` and `libavutil.so.52`, but arch has `libavformat.so.57` and `libavutil.so.55`

**Comment by emilio** [comment]
Hi, thanks for reporting this! It seems like a version conflict, could you check if building servo yourself works?

cc @larsbergstrom, do you how other browsers handle this? I assume firefox compiles libav themselves, but I don't know about others.

also, cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
It should target `.so` files, not `.so.version`. This is really disturbing.

**Comment by KiChjang** [comment]
Can we see a full log of the error?

**Comment by Bedotech** [comment]
It happen in ubuntu 16.04 too:
```
./servo: error while loading shared libraries: libavformat.so.54: cannot open shared object file: No such file or directory
```

**Comment by nicompte** [comment]
If that helps, here is the log for a dev build on ubuntu 15.10:

```
error: failed to run custom build command for `dbus v0.3.3`
process didn't exit successfully: `/home/nicompte/test/servo/target/debug/build/dbus-7f7af798babde0c1/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\"` did not exit successfully: exit code: 1\n--- stdout\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n"', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x56477e89c69f - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:     0x56477e8a3d2b - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
   3:     0x56477e8a2de5 - std::panicking::default_hook::hbbe7fa36a995aca0
   4:     0x56477e8a339e - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   5:     0x56477e8a3201 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   6:     0x56477e8a312a - std::panicking::begin_panic_fmt::h20f5943904e5791d
   7:     0x56477e8a309e - rust_begin_unwind
   8:     0x56477e8da05f - core::panicking::panic_fmt::h19323e466869c656
   9:     0x56477e87e6f5 - core::result::unwrap_failed::hf09b4eeb9952b395
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x56477e87e2be - _<core..result..Result<T, E>>::unwrap::h24277db7fa8497ab
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:726
  11:     0x56477e87f177 - build_script_build::main::he5071e1b00fcfe0e
                        at /home/nicompte/test/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.3.3/build.rs:4
  12:     0x56477e8a3068 - std::panicking::try::call::h5df3ac2979db3c90
  13:     0x56477e8ab8b6 - __rust_maybe_catch_panic
  14:     0x56477e8a248e - std::rt::lang_start::hfe9ab243c60ffb9b
  15:     0x56477e87f223 - main
  16:     0x7f3a30748abf - __libc_start_main
  17:     0x56477e87dee8 - _start
  18:                0x0 - <unknown>

Build completed in 0:00:56
```

**Comment by emilio** [comment]
@nicompte: That build seems like it failed because you didn't have the dbus dependency, doesn't seem related, but if it persists after installing all the dependencies on the readme, please file another issue and mention me, thanks! :)

@larsbergstrom: what should we do here? I propose cfg'ing out the media support for Linux until we find a proper solution (which may involve compiling ourselves the media stack I'm afraid).

**Comment by MartyIX** [comment]
I've just noticed that *This week in Servo* mentions https://github.com/servo/servo/pull/12186/files. Maybe it's related, maybe it's not.

**Comment by GuillaumeGomez** [comment]
@MartyIX: That's the origin yes.

**Comment by metajack** [comment]
What does Gecko do here? Do they just bundle ffmpeg?

**Comment by emilio** [comment]
@metajack: Gecko has libmozavformat, that in practice yes, is building libav themselves if I'm not wrong.

**Comment by romanlevin** [comment]
https://download.servo.org/ should be updated to save people the googling.

**Comment by nox** [comment]
What does `pkg-config --libs libavformat` say for people encountering that bug?

**Comment by flipflop97** [comment]
@nox 
```bash
$ pkg-config --libs libavformat
-lavformat
```

**Comment by nox** [comment]
@flipflop97

No `-L` flag? Where is your libavformat? I suspect you have an out-of-date `libavformat.so` symlink pointing to a file that doesn't exist anymore.

**Comment by flipflop97** [comment]
```bash
$ whereis libavformat
libavformat: /usr/lib/libavformat.so /usr/include/libavformat /usr/share/man/man3/libavformat.3.gz

$ file /usr/lib/libavformat.so
/usr/lib/libavformat.so: symbolic link to libavformat.so.57.41.100

$ file /usr/lib/libavformat.so.57.41.100 
/usr/lib/libavformat.so.57.41.100: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7fb4b51356ebe7017af3b62e23fdef3a0f52c2df, stripped
```

Everything seems to be ok to me, `libavformat.so` points to the right file.

**Comment by nox** [comment]
Could anyone post the actual failure they get when building, pasting the whole build log of `./mach build`?

**Comment by benwaffle** [comment]
no errors when building from source

**Comment by heftig** [comment]
Gecko's `libmozav*` libraries contain a vp8/9 subset of ffmpeg. To load system ffmpeg for other codecs, they have a `FFmpegRuntimeLinker` which uses `dlopen` and can load a whole bunch of different versions.

**Comment by emilio** [comment]
FWIW, my intention is to disable the dependency, at least temporarily, in https://github.com/servo/servo/issues/12863

**Comment by emilio** [comment]
This should be fixed for now, thanks to all of you for reporting it! :)

#12769 is the tracking issue for knowing what to do with media support in Servo, if you're interested.

Thanks again!
