### ISSUE TITLE
Handle 3- and 4- valued <position>s in style

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#12690]
background-position can take values like `right 50% bottom 10px`. We currently only parse the two-valued form, which takes one value each for the horizontal and vertical position.

Relevant spec: https://drafts.csswg.org/css-backgrounds-3/#position

Probably can represent it something like:

```rust
struct Position {
   horiz_keyword: HorizontalKeyword, // center, left, right, defaults to left
   horiz_position: LengthOrPercentage, // defaults to 0%
  // same for vertical
}
```

`<position>` when serialized only serializes to its two/four value forms (not three-valued ones, so `left <omit> top 10px` is serialized as `left 0% top 10px`. Aside from this, whenever serializing we should always try to omit unnecessary values.

(The basic-shape spec mentions that keywords are a stand-in for percentages and should never be serialized directly, but this doesn't match existing behavior. The background spec doesn't directly mention serialization steps for position)

**Comment by Manishearth** [comment]
The serialization is actually unspecced, https://github.com/w3c/csswg-drafts/issues/368

**Comment by Manishearth** [comment]
Gecko actually just stores these as two calc values on the computed side. The specified side needs more info for serialization though. Maybe.

**Comment by Manishearth** [comment]
Willing to mentor anyone who wants to look into this.

**Comment by canaltinova** [comment]
I want to work on this.

There are 2 Position structs right now. One is computed and other one is specified. 
Should we change these structs as you mentioned in your first comment or should we calculate them to reflect `left x top x` position like Gecko does, I suppose?

> Aside from this, whenever serializing we should always try to omit unnecessary values.

I don't understand what you mean by this exactly. You mean we should serialize this `right 0% left 20px`  as `left %100 left 20px`?

**Comment by Manishearth** [comment]
I think we want the specified Position to be the way I listed above. The computed one can be left as-is -- the keyword specified values can be computed into `calc()`s, which is what gecko does.

Ignore omitting unnecessary values for now.
