### ISSUE TITLE
Borders of inline elements are wrong for broken lines

### ISSUE THREAD

**Issue by splav** [servo/servo#12699]
Minimal test:
```
<!doctype html>
<html><body>
<style>
div {
  width: 5em;
}
span {
  border-left: yellow solid 0.5em;
  border-right: yellow solid 0.5em;
}
</style>
<div>
  <span>Very long text</span>
</div>
</body></html>

```
Servo:
![screenshot_20160803_010231](https://cloud.githubusercontent.com/assets/182050/17346998/963fef44-591e-11e6-8a98-129e7472886d.png)
Firefox:
![firefox](https://cloud.githubusercontent.com/assets/182050/17346999/9c60f260-591e-11e6-9a07-b1429ead5917.png)

**Comment by splav** [comment]
As it interferes with my PR https://github.com/servo/servo/pull/12669 I would like to take this, at least in the part of extra borders, not sure about the positioning logic for now.

**Comment by jdm** [comment]
Go for it!
