### ISSUE TITLE
Remove package-prefs.json

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#12707]
As far as I can tell, `package-prefs.json` is used to replace `prefs.json` on Mac when Servo is packaged with browserhtml.

On Linux, a shell script is created with the prefs set via the command line.
I'm not sure about Windows.

It should either be used on the 3 platforms, or not used at all.

Also, I'm not sure to see the benefit of this file, especially because it duplicates preference location, one might miss to update this file while updating `prefs.js`.

I think for now, we should remove it and, on Mac, do what we do on Linux.

Or maybe `package-prefs.json` should be renamed `browserhtml-prefs.json`, and be just extra values merged with `prefs.js` at build time.

**Comment by jdm** [comment]
Sounds like another way of dealing with #11966.
