### ISSUE TITLE
Fedora FFmpeg Dependency Exception

### ISSUE THREAD

**Issue by Coder206** [servo/servo#12726]
Fedora does not include FFmpeg like the other Linux distros do. So the instructions need to be modified to get FFmpeg from RPMFusion. 

I will be self assigning myself to this one.

Tags to add please: E-easy, C-assigned, P-Linux, I-panic

**Comment by Coder206** [comment]
@KiChjang Thanks

**Comment by genodeftest** [comment]
Since #12729 states that FFmpeg is not going to be included, this bug can be closed.
