### ISSUE TITLE
Fails to 'mach build --dev' and 'mach build --release' on Alpine Linux

### ISSUE THREAD

**Issue by ElijahCaine** [servo/servo#12721]
When building Servo on Alpine Linux the following output occurs when `mach build --dev` and `mach build --release` are run:
```
/tmp/servo # ./mach build --dev
Error running mach:

    ['build', '--dev']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory

  File "/tmp/servo/python/servo/build_commands.py", line 244, in build
    env=env, cwd=self.servo_crate(), verbose=verbose)
  File "./python/servo/command_base.py", line 73, in call
    return subprocess.call(*args, shell=sys.platform == 'win32', **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
```

I would take a crack at this myself but there's not a ton of helpful output like which file/directory can't be found.

The following packages are installed before the above command is run: **curl, file, gnupg, sudo, git, python, virtualenv,** and **Rust Nightly** using `curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly`.

Is this a known bug? I can't tell if it's a bug unique to Alpine, this release of Rust, or something else entirely.

**Comment by jdm** [comment]
Line 244 is invoking `cargo build`; it's surprising that that's not working. Any change in the output if you use `./mach build -d -v`?

**Comment by ElijahCaine** [comment]
@jdm As my Magic-8-Ball says "Not looking good."

```
/tmp/servo # ./mach build -d -v
looking for rustc at /tmp/servo/.servo/rust/2016-07-25/rustc-nightly-x86_64-unknown-linux-gnu/rustc/bin/rustc
Downloading Rust compiler...
Downloading Rust compiler: 100.0%
Extracting Rust compiler...
Rust compiler ready.
Downloading Host rust library for target x86_64-unknown-linux-gnu...
Downloading Host rust library for target x86_64-unknown-linux-gnu: 100.0%
Extracting Rust stdlib for target x86_64-unknown-linux-gnu...
Rust x86_64-unknown-linux-gnu libs ready.
Downloading Cargo nightly...
Downloading Cargo nightly: 100.0%
Extracting Cargo nightly...
Cargo ready.
cargo build -v
Error running mach:

    ['build', '-d', '-v']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory

  File "/tmp/servo/python/servo/build_commands.py", line 244, in build
    env=env, cwd=self.servo_crate(), verbose=verbose)
  File "./python/servo/command_base.py", line 73, in call
    return subprocess.call(*args, shell=sys.platform == 'win32', **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
```

**Comment by SimonSapin** [comment]
@ElijahCaine try `./mach env`. The `PATH=…` line should include one directory whose path ends in `cargo/2016-07-30/cargo/bin`. Does this directory contain a `cargo` executable? Can you run it, say with `…/cargo/2016-07-30/cargo/bin/cargo --version`?

Note that there is no need to install Rust yourself. By default mach will automatically download the appropriate Rust version.

**Comment by ElijahCaine** [comment]
@SimonSapin The PATH variable claimed to have an executable at `/tmp/servo/.servo/cargo/2016-07-30/cargo/bin`. When I checked there was one, but my Alpine (or something else in my environment) was having problems executing it:
```
/tmp/servo # ./mach env
export PATH=/tmp/servo/.servo/rust/2016-07-25/rustc-nightly-x86_64-unknown-linux-gnu/rustc/bin:/tmp/servo/.servo/rust/2016-07-25/rustc-nightly-x86_64-unknown-linux-gnu/bin:/tmp/servo/.servo/cargo/2016-07-30/cargo/bin:/tmp/servo/.servo/cargo/2016-07-30/bin:/tmp/servo/python/_virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export LD_LIBRARY_PATH=/tmp/servo/.servo/rust/2016-07-25/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib:/tmp/servo/.servo/rust/2016-07-25/rustc-nightly-x86_64-unknown-linux-gnu/lib:
/tmp/servo # ls -alh /tmp/servo/.servo/cargo/2016-07-30/cargo/bin/cargo 
-rwxr-xr-x    1 100      101        10.6M Jul 30 02:44 /tmp/servo/.servo/cargo/2016-07-30/cargo/bin/cargo
/tmp/servo # /tmp/servo/.servo/cargo/2016-07-30/cargo/bin/cargo --version
sh: /tmp/servo/.servo/cargo/2016-07-30/cargo/bin/cargo: not found
```
This problem might go a bit deeper than I am equipped to dig, but let me know if this problem has come up before or any ideas on how to address it.

**Comment by SimonSapin** [comment]
If you have a working Cargo already in `$PATH`, try copying `servobuild.example` to `.servobuild` in your servo tree and changing `system-cargo` to `true` in `.servobuild`.

**Comment by ElijahCaine** [comment]
@SimonSapin I get the same error when using my system cargo and the following error when trying to run my system cargo:
```
/tmp/servo # /usr/local/bin/cargo 
sh: /usr/local/bin/cargo: not found
```
I could have sworn it installed correctly, but I guess I was mistaken. Other binaries (like python) get run just fine.
I'm going to try starting from scratch and see if it's something weird that gets resolved when I "Turn it off and on again".

**Comment by ElijahCaine** [comment]
This seems to be an issue with Alpine and linking against musl which is outside the scope of servo, so I'm gonna close it. Thanks for the help @SimonSapin and @jdm :smile:
