### ISSUE TITLE
Update bindings generator to support default ByteString values in a dictionary

### ISSUE THREAD

**Issue by malisas** [servo/servo#12737]
The [Web IDL ByteString spec](http://heycam.github.io/webidl/#idl-ByteString) previously said:
> There is no way to represent a constant ByteString value in IDL.

But in response to [an issue](https://github.com/whatwg/fetch/issues/348) I filed, it has now been changed to say:
> There is no way to represent a constant ByteString value in IDL, although ByteString dictionary member and operation optional argument default values can be specified using a string literal.

**Conclusion: Servo's bindings generator should be updated to support default ByteString values in a dictionary.**

More about string literals: [here](http://heycam.github.io/webidl/#string-literal)
This blocks #11896

**Comment by Ms2ger** [comment]
@malisas: are you planning to work on this? Feel free to ping me or jdm if you need help.

**Comment by malisas** [comment]
Sure, I'll give it a shot!

**Comment by jdm** [comment]
There will be two parts to this - allowing default values for ByteStrings in the parser, and generating appropriate Rust code for Bytestring values with default values in the code generator. As a good testcase for this work, I suggest adding a ByteString dictionary member with a default value to `TestBinding.webidl`, as well as a method that accepts an optional ByteString argument with a default value.

Code: `components/script/dom/bindings/codegen/parser/WebIDL.py`, `components/script/dom/bindings/codegen/CodegenRust.py`

**Comment by jdm** [comment]
Relevant code in CodegenRust.py is in the `isDOMString()` and `isUSVString()` branches of `getJSToNativeConversionInfo`.
