### ISSUE TITLE
Starting Servo on Windows takes a long time

### ISSUE THREAD

**Issue by changm** [servo/servo#12730]
STR:
1) Compile a release version of servo
2) Start servo
3) Whistle while waiting.

It is significantly slower to start up than on OS X. Tested on the same machine via bootcamp.

**Comment by paulrouget** [comment]
How do you start Servo?

What is slow exactly? For the window to show up or loading the initial document?

**Comment by changm** [comment]
I was starting servo with just ./mach run -w http://www.nytimes.com

Everything about Servo is slower than on mac. Waiting for the window to show up is slower. Loading the initial document is slower. It's much much slower.

**Comment by paulrouget** [comment]
> Waiting for the window to show up is slower

Could it be a glutin issue? Can you try running the window example of https://github.com/tomaka/glutin see if it's slow as well?

**Comment by Coder206** [comment]
@paulrouget I noticed a similar experience as @changm. I tried the demo, works instantly.

**Comment by paulrouget** [comment]
> I tried the demo, works instantly (fast launch).

You mean the glutin example?

**Comment by Coder206** [comment]
@paulrouget Yes, glutin example loaded instantly.

**Comment by UK992** [comment]
For slow window show up, could be problem with git. For some reason with mach run git starts working, sometimes it takes 100% disk usage and took few minutes to open window.

**Comment by jdm** [comment]
FYI, we use git to set up an environment variable with the current commit hash so Servo can make use of it.

**Comment by Coder206** [comment]
Thanks @jdm and @UK992

**Comment by Coder206** [comment]
This seems to be corrected when running with MSVC

**Comment by jonathandturner** [comment]
Does this still repro?  I haven't seen slow startup times on recent Windows nightlies. 

https://download.servo.org/nightly/windows-msvc/servo-latest.msi

**Comment by atouchet** [comment]
I don't know what exactly is considered to be "a long time" but when launched from an SSD I find that Servo takes roughly 2-3 seconds to startup.

**Comment by jonathandturner** [comment]
@atouchet - are you on Windows native or in a VM?  I see some slowness, but I was attributing that to me running Windows in a VM.

**Comment by atouchet** [comment]
@jonathandturner Windows native.

**Comment by changm** [comment]
I just tried the tech demo from https://github.com/servo/servo/issues/12730#issuecomment-280121591. That seems to work fine. I'll try building servo again and see what I find.

**Comment by nox** [comment]
Seems like this is ok to close now.
