### ISSUE TITLE
TravisCI is currently not reporting status correctly back to to GitHub for `auto` pushes

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#12739]
For one example, see:
https://github.com/servo/libexpat/pull/18

It still has status for the original PR when first opened:
https://travis-ci.org/servo/libexpat/builds/149873201

But when homu did a push to the 'auto' branch and travis ran
it, it saw the push, knows it was associated with the PR, but did
*not* appear to report it back to github:
https://travis-ci.org/servo/libexpat/builds/149882277

**Comment by larsbergstrom** [comment]
Travis have confirmed and provided proof that they are sending the web hooks and notifying GitHub correctly.

We have reached out to support@github for more information on what is going on here.

**Comment by larsbergstrom** [comment]
After working with GitHub and Travis, we suspect that Homu is not correctly validating the Travis status messages. That process is described here:
https://docs.travis-ci.com/user/notifications/#Authorization-for-Webhooks

And that code is in homu at:
https://github.com/servo/homu/blob/master/homu/server.py#L617-L627

**Comment by larsbergstrom** [comment]
The current status is that mail is out to Travis and we are waiting to hear back on what we need to do to fix up our usage of their Webhooks (or if something broke on their side). We will continue to manually verify build results and merge PRs until this is fixed.

**Comment by edunham** [comment]
Proposed solution: 

When an invalid signature is received, query Travis for the latest auto build status. If build title matches, assume status is accurate and act accordingly.

**Comment by Manishearth** [comment]
A simpler workaround is to switch the travis hooks to status hooks. We need to switch on the status webhook for homu in the settings of all repos, and use a `[repo.FOO.status.travis] context = 'continuous-integration/travis-ci/push'`. This works, and is not affected by the git issue about statuses -- homu listens for all status changes (otherwise homu appveyor builds would be broken too)

In the long run I'd prefer to use @edunham's solution though.

**Comment by larsbergstrom** [comment]
@Manishearth Will that work? I believe we've been having some issues here because of the way we use Travis (testing on the `auto` branch), as this means that the status reported back to github is not in any way associated with the PR itself. This hasn't been an issue for us with our current model b/c we're just using the status from Travis itself.

I'm not sure if AppVeyor is really working or if we're just actually reading the status from the GitHub PR, which will always be of when the last commit was pushed.

Or am I misunderstanding the `continuous-integration/travis-ci/push` bit?

**Comment by Manishearth** [comment]
Check out the /status route in server.py, the fact that the status isn't related to the PR doesn't matter -- we check the sha.

**Comment by Manishearth** [comment]
(The `/push` context happens for every branch Travis is allowed to test, on every push to the branch. `auto` is one of them.)

**Comment by larsbergstrom** [comment]
I think we should go ahead and try this - it will be a little while for Travis to get a "real" fix for this `Authorization` header problem.

**Comment by Manishearth** [comment]
Is it working now?

A nice thing with this mode is that we can turn on test exemption if some repos want it (lets wait for the dust to settle first)

**Comment by aneeshusa** [comment]
Seems to be working, and homu is already using test exemption (which is a really nice feature I din't know about!).
