### ISSUE TITLE
CSS Transition with multiple properties with one invalid property does not work

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12747]
In Servo, when transitioning multiple properties, if there is one unrecognized property in the supplied list then none of the other transitions specified will be applied.

For example:

```
#myDiv {
    transition: 0.5s width ease-in-out, 0.5s non-existent-property ease-in-out;
}
```

In this example,  there are no transitions on the `width` propertiey as the list of transitions has a single unrecognised property in, namely `non-existent-property.`

The location of the unrecognised property does not change anything.  So for example, the following does not work for the same reason:

```

#myDiv {
    transition: 0.5s non-existent-property ease-in-out, 0.5s width ease-in-out; 
}
```

FF/Chrome appear to be a bit more fault tolerant and will just ignore the part of the transition list with the invalid property but will correctly apply transitions to the other (valid) properties specified.

Online test case [here](https://samuknet.github.io/test_cases/cssMultipleTransitionsWithInvalidProperty).

**Comment by jdm** [comment]
Presumably this is caused by `parse_one_transition` in `components/style/properties/shorthand/box.rs` returning an error if `transition_property` fails to parse, and the use of `try!` with `parse_comma_separated`. @SimonSapin what's the right way to continue parsing after a parsing error?

**Comment by samuknet** [comment]
thanks @jdm  - If you reckon this will be a good first contrib. after some more poking then I'd love to have a go (with some guidance!)

**Comment by nox** [comment]
@emilio @SimonSapin Was this fixed?

**Comment by nox** [comment]
I'm dumb, there is a demo. It's fixed.
