### ISSUE TITLE
Outdated FFmpeg version

### ISSUE THREAD

**Issue by flipflop97** [servo/servo#12743]
OS: Arch Linux with latest updates including FFmpeg

when running the 5 Aug 2016 nightly I get the following error:
./servo: error while loading shared libraries: libavformat.so.54: cannot open shared object file: No such file or directory

The issue is fixed by installing the older (54) version of this FFmpeg library manually using the AUR package aur/ffmpeg-compat-54

Is it possible to use a more recent version of this library so that using the AUR package is not necessary?

**Comment by jdm** [comment]
This is tracked in #12687. Thanks for reporting it!
