### ISSUE TITLE
requestAnimationFrame seems to break CSS transitions

### ISSUE THREAD

**Issue by Gozala** [servo/servo#12749]
I have created a following test case that you can try as `servo -w https://Gozala.jsbin.com/vujonov`

When "Request animation frames" is checked animation css transition is not performed, instead just last frame is drawn when transition is complete. If it is unchecked transitions are performed as expected. Checkbox just toggles `requestAnimationFrame` loop that seems to cause a bug in CSS transitions.

P.S.: It does not seems to matter if we do anything on animation frames or not.

**Comment by emilio** [comment]
The problem is that the constellation doesn't send `TickAnimations` messages to layout if there's a `requestAnimationFrame` loop. I don't know how easy/hard to fix this is yet.
