### ISSUE TITLE
Update SelectorMap code when fixing TODOs in matches_simple_selector

### ISSUE THREAD

**Issue by pradeep90** [servo/servo#1275]
When we add support for case-sensitivity, document type, quirks mode, etc., the SelectorMap would need to reflect the same.

This logic affects the way we `insert` rules in the SelectorMap - We need to extract `IDSelector`, `ClassSelector`, or `LocalNameSelector` from the Rule and store them. This would involve knowing about the document type, case-sensitivity, etc.

It also affects how we lookup rules in the SelectorMap - we need to lookup node's ID, classes, and element name in the keys. This depends upon the case-sensitivity, etc. as well.

**Comment by mbrubeck** [comment]
I think this is complete.
