### ISSUE TITLE
Add Link to DXR in IRC 

### ISSUE THREAD

**Issue by Coder206** [servo/servo#12759]
I wasn't sure where to place this issue so I decided in the projects main repository but it's subject is the Internet Relay Chat #servo. Not sure what tags could fit here either.

I was clicking the links in #servo and noticed the link http://mxr.mozilla.org/servo/ is outdated and should be replaced with https://dxr.mozilla.org/servo/

I learned this because there was a redirect when I visited MXR, but this does not provide an intuitive means for someone navigating these links.

**Comment by Ms2ger** [comment]
Done, thx

**Comment by Coder206** [comment]
@Ms2ger Great! Thank you as well :)
