### ISSUE TITLE
Build error on OS X 10.11.6

### ISSUE THREAD

**Issue by tungpham** [servo/servo#12756]
./march build --release 

error: failed to run custom build command for `video-metadata v0.1.3 (https://github.com/GuillaumeGomez/video-metadata-rs#44c8d547)`
process didn't exit successfully: `/Users/XXXXXX/servo/target/release/build/video-metadata-c11275da9e1a70d4/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Couldn't find libavformat: `"pkg-config" "--libs" "--cflags" "libavformat"` did not exit successfully: exit code: 1
--- stdout
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found

**Comment by metajack** [comment]
Did you use brew to install ffmpeg?

**Comment by tungpham** [comment]
yes i use brew to install ffmpeg after seeing the error. But the error still persist

**Comment by tungpham** [comment]
i had to set the PKG_CONFIG_PATH to /usr/local/lib/pkgconfig
