### ISSUE TITLE
Hit test on fixed DIV incorrectly offset when page is scrolled

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12763]
The problem occurs when there is a div with CSS `position: fixed`.  In this test, there is a `cursor:pointer` style and a `:hover{ background-color: red} ` style to indicate that the DIV has been hovered over.

These styles initially work when the page first loads - hovering over the DIV makes the cursor become a pointer and changes the background colour of it.

 However, when the document is scrolled down by any amount, the pointer cursor and background colour no longer work on hover.  Scrolling the document back to the very top makes them work again.

The problem appears to be specific to 'position: fixed'.  
Demo:
![demo](https://cloud.githubusercontent.com/assets/9294710/17477305/80962680-5d5c-11e6-9dad-b0f93eec629f.gif)

One subtlety is that scrolling the page down any amount which isn't the full height of the DIV means that the hover styles (cursor pointer and background colour) do work but only on a top portion of the div.  For example, scrolling down the page approximately half the height of the div means that the hover styles only work as expected on the top half of the div, but nothing happens when hovering over the bottom half.

It feels as if the DIV's hit test coordinates are scrolling along with the rest of the page just as it would if it didn't have `position: fixed` set.

Online test case [here](https://samuknet.github.io/test_cases/fixedDivHitTest/).

**Comment by emilio** [comment]
On it.
