### ISSUE TITLE
./mach build failing on Mac

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12761]
Running ./mach build -r on OS X El Capitan is giving me a host of errors: http://pastebin.com/DXuzX9He
The errors appear to be coming predominantly from 'mozjs'.
Could be related to https://github.com/servo/servo/issues/12686?

**Comment by djc** [comment]
Maybe take a look at https://groups.google.com/forum/#!topic/mozilla.dev.servo/7nJr7P-ZG5Y.

**Comment by samuknet** [comment]
Thanks - this worked for me.  

`./mach clean`
then 
`./mach build` made everything work as before.

**Comment by Jayflux** [comment]
Im still getting this

**Comment by jdm** [comment]
What is the output that you see?

**Comment by Jayflux** [comment]
https://github.com/servo/servo/issues/14483#issuecomment-265552017
its ok, i think its because i didn't have some pre reqeusites installed
