### ISSUE TITLE
No sane way to pull source now and build offline later

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#12774]
STEPS TO REPRODUCE:

1. git pull servo
2. Go offline
3. Try to compile.

EXPECTED RESULTS: Things compile.

ACTUAL RESULTS: The build process starts downloading things like updated compilers and various cargo stuff, and hence fails.

It's pretty common for me to have bandwidth but not CPU cycles at one point in time and CPU cycles but not bandwidth later.  So I could really use a mach command that does the "git pull (or git fetch) and grab all the compilers and cargo modules the build will need" build but doesn't try to actually compile...

**Comment by jdm** [comment]
Seems like #12775 would address this.

**Comment by aneeshusa** [comment]
Fixed in #12821 with the new `./mach fetch` command.
