### ISSUE TITLE
Create a ./mach test-perf command

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#12792]
Since the [page load performance test runner](https://github.com/servo/servo/tree/master/etc/ci/performance) is now in tree, we can create a mach command that runs it on the locally built Servo binary. 

Some thing so consider:
* The test runner whet through a big rewrite during the review, so expect some corner case to be broken. 
* It only makes sense to run performance on release build, so show an error if there is only the debug build
* Currently the nightly tests are running on my private server, we need to make sure the command can be run in the CI without manual setup.

This sounds like a easy to less-easy task, if someone is interested please give it a try first.

**Comment by asajeffrey** [comment]
This would be very nice to have, especially if we could use it to compare performance between branches.

**Comment by metajack** [comment]
It would be nice if this worked like arewecompressedyet.com where branches can be tried and various results compared easily. I assume this is possible with perfherder, but it's just so easy to use arewecompressedyet that everyone does it for almost all changes.

**Comment by shinglyu** [comment]
@metajack I think that might be something we can bring up with the Perfherder team, AFAIK they are still seeking ideas to improve the Perfherder UI. It will also benefit the Platform team.

**Comment by shinglyu** [comment]
From #12405 :

This is a followup for #11107 . There are a few things that needs to be done:
- [ ] Create a script to download tp5.zip and put it in the correct folder
- [ ] Create a `test-perf` command in `test_commands.py` to bootstrap the test env and run.
- [ ] Pretty print the test result for human to read (currently a json) (Some of the work is done in #12946)
- [ ] Figure out what kind of log format we want. Maybe use mozlog?
- [x] Deprecate the `shinglyu/servo-perf` repo and redirect people to the in-tree folder in the README.md file.

**Comment by zack1030** [comment]
I am trying.

**Comment by jdm** [comment]
Great!
