### ISSUE TITLE
Doges disappear unless they are large and perfectly upright

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#12802]
When I run the dogemania demo from Sam and Sole:
`./mach run -r -w https://mozdevs.github.io/servo-experiments/experiments/dogemania/`

The doges rotate in, but disappear in their final position if they are not large and perfectly upright.

Also, the fps counter does not display.

@glennw @pcwalton Would it be possible to try and take a look at what's going on here? Sam is doing his intern demo in two weeks (August 25th), and it would be awesome for him to be able to show this in Servo.

**Comment by glennw** [comment]
@larsbergstrom Yep, I'll take a look this week. Would this or https://github.com/servo/servo/issues/12286 be a higher priority? (It may well be that they have the same root cause anyway).

**Comment by glennw** [comment]
The <h1> text is not displaying due to a layout bug - the local clip rect has a height of 0. It might be possible to work around this by enclosing the text in a positioned div, and placing the transform on that, or something similar.

**Comment by glennw** [comment]
@larsbergstrom This appears to be a layout bug. The style.css of the supplied test case has:

```
body {
	overflow: hidden;
	width: 100%;
	height: 100%;
}
```

This breaks the layout code in Servo, which calculates the height of the scene to be 0px.

This can be worked around by making the above style apply to both the html and body element, such as:

```
html, body {
	overflow: hidden;
	width: 100%;
	height: 100%;
}
```

When I do this, I see all the images rotate in correctly and remain on screen :)

My suggestion would be to:
 * Verify this is a reasonable workaround for the demo.
 * Add a reduced test case based on the above information and re-label this as a layout bug.

**Comment by glennw** [comment]
@larsbergstrom Oh, the h1 text FPS counter not displaying is also a layout bug - by the time it arrives at webrender, the dimensions of the clip rect are zero. It's probably possible to work around this by changing how the text is specified (e.g. use an absolutely positioned div with fixed size) for now.

**Comment by notriddle** [comment]
Minimal test case:
