### ISSUE TITLE
Update ipc-channel to 0.5

### ISSUE THREAD

**Issue by jdm** [servo/servo#12806]
@jrmuizel asked we if could apply the upgrade to this repository and others like webrender. We appear to be using a mixture of crates.io versions and specific git revisions. Would @nox like to deal with this?

**Comment by nox** [comment]
We use ipc-channel 0.4 for now because ipc-channel includes the serde bump to 0.8. Which repositories use Git revisions for ipc-channel? That was a very short-lived thing that @Ms2ger cleaned the next day it was committed.

**Comment by nox** [comment]
@jdm To bump to serde 0.8, we need a hyper bump, but @seanmonstar wants to wait a bit for the async design to be reworked before he releases hyper 0.10 (which includes the serde bump). I guess I could maintain a fork of it for now but that means rewriting our own code relying on hyper with the async API that is soon to disappear.

**Comment by seanmonstar** [comment]
Regarding hyper, I'd rather split the serde impls into a separate crate, so that breaking changes in serde doesn't mean breaking change in hyper.

**Comment by nox** [comment]
I wonder if serde could have a mechanism to delegate operations to some kind of transient wrapper specified through a new attribute on specific fields. Cc @erickt.

**Comment by erickt** [comment]
@nox: Perhaps `#[serde(serialize_with=..., deserialize_with=...)]` will do what you want? See https://github.com/serde-rs/serde/blob/9d015a29420687a744e6fa1c5150ec218c16cf78/testing/tests/test_annotations.rs#L659 for an example.

**Comment by nox** [comment]
Sounds good. Will try to make a serde_hyper crate tomorrow that provides such functions and documentation for users who wish to serialise Hyper types. Does that sound good with you @seanmonstar?

**Comment by seanmonstar** [comment]
That seems excellent!

**Comment by nox** [comment]
For the record: https://github.com/nox/hyper_serde

**Comment by Ms2ger** [comment]
Fixed in #12828
