### ISSUE TITLE
Paste not working

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#12805]
In the latest nightly on OS X, copy the url "https://mozdevs.github.io/servo-experiments/experiments/dogemania/" from another browser, and paste it into the url bar in servo.

Behavior:

Nothing happens.

Expected:

The url pastes correctly.

**Comment by larsbergstrom** [comment]
Yeah, unfortunately I had to remove our clipboard support in https://github.com/servo/servo/pull/12507, as it's GPL, which is a big no-no for Servo.

**Comment by KiChjang** [comment]
Should we keep this issue open? I don't suppose there are other clipboard crates that we can use, but we could develop these on our own.

**Comment by notriddle** [comment]
Maybe we can use this?

https://github.com/jwilm/alacritty/tree/master/copypasta

**Comment by quininer** [comment]
Now rust-clipboard is not GPL! https://github.com/aweinstock314/rust-clipboard/commit/f5cfc0c652ede9ff0b804a9bd3b246bffc43d8cb

**Comment by larsbergstrom** [comment]
Seems legit, based on your patch here:
https://github.com/aweinstock314/rust-clipboard/commit/29f757c31d852abd4c7eb2636d414b30dc8dd21f

Which seems to rely on an MIT-licensed x11 clipboard implementation.

Awesome!
