### ISSUE TITLE
Include stdout/stderr output in default filtered view from failed WPT tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#12808]
This would fix the common case of people adding `println!()` and getting confused when they don't see any change in the output. Usually we need to add `--log-mach -` to see the result, but you always need someone more experienced to tell you that if you're new.

**Comment by jdm** [comment]
We should do this for passing tests as well. Let's make the default experience of test-wpt as intuitive as possible.

**Comment by jdm** [comment]
The code for this lives in tests/wpt/grouping_formatter.py.

**Comment by jdm** [comment]
I think `test_end` is where the change needs to happen; we currently only get the output from a test if it had unexpected results.

**Comment by nox** [comment]
What's missing here?

**Comment by jdm** [comment]
Nothing.
