### ISSUE TITLE
Homu doesn't kick off tests anymore and does not merge anything

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#12825]
CC @aneeshusa @Manishearth @larsbergstrom @metajack @edunham 

Both in Servo and travis-backed repos:
* https://github.com/servo/euclid/pull/156
* https://github.com/servo/servo/pull/12822

**Comment by jdm** [comment]
If the last Travis run was against the same revision as the requested merge, home has a shortcut mode that doesn't bother redoing the build. This is a good thing.

**Comment by Manishearth** [comment]
That's not what's happening here -- in that case it explicitly says "test exempted" and merges

**Comment by larsbergstrom** [comment]
Fixed! The problem is that the `homu` directory had permissions `root:root` but the service is supposed to run as the `servo` user. I cleaned things up manually, and @aneeshusa is going to work on a PR to ensure our salt rules set up things perfectly from a clean directory.
