### ISSUE TITLE
Support 'letter spacing' property in gecko-lib

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#12823]
#12795 adds the glue for word spacing property. Now, we need a similar one for letter spacing, which is nothing but a length (as opposed to `LengthOrPercentage`).

Things to be done:
 - Add `'letter spacing'` to the `skip_longhands` parameter so that we don't ignore the implementation
 - Add a new method `set_letter_spacing` just above `set_word_spacing` (it should `set_value` if there's `Some(value)`, or set it to zero if there's `None`)
 - Finally, `impl_coord_copy` for the now implemented letter spacing, so that we add the necessary sugar for the thing to work with gecko.

Code: `components/style/properties/gecko_mako.rs`

**Comment by Wafflespeanut** [comment]
Never mind, this requires testing against stylo, and so it won't be good for newcomers.

**Comment by Wafflespeanut** [comment]
Yo @KiChjang, any news on this?

It's not urgent, but this staying open kinda bugs me :stuck_out_tongue:

**Comment by KiChjang** [comment]
@Wafflespeanut I'm still dealing with transition events. If you want to work on it, do it before I submit a PR for transition event, because this will be next up in my plate.

**Comment by KiChjang** [comment]
Oops, too late: #13056.
