### ISSUE TITLE
replace RUSTFLAGS and editbin.exe with some python code

### ISSUE THREAD

**Issue by metajack** [servo/servo#12829]
Until https://github.com/rust-lang/cargo/issues/2986 is addressed, we need to handle the windows subsystem ourselves. This is currently done with RUSTFLAGS manipulation. https://github.com/servo/servo/pull/11756 uses editbin.exe for MSVC bulids.

We should do this with Python in such a way that it works for both kinds of builds. Perl code that does this can be found here: https://searchcode.com/codesearch/view/8568397/

**Comment by metajack** [comment]
cc @vvuk @larsbergstrom

**Comment by metajack** [comment]
@vvuk found an existing bit of python that does this:
http://stackoverflow.com/questions/2435816/how-do-i-poke-the-flag-in-a-win32-pe-that-controls-console-window-display/14806704#14806704

**Comment by vvuk** [comment]
This actually isn't that easy -- setting the flag is, but we can easily do that only for servo.exe.

For tests, cargo builds a whole pile of test .exe's, and we don't really know all the binary names in mach.  So we can't flip the bit.  Tests shouldn't have custom build.rs (do they?) so maybe RUSTFLAGS will work in that case?

**Comment by metajack** [comment]
Shouldn't those tests be using console mode anyway?
