### ISSUE TITLE
Scrolling down page with IFrame 'scrolls' the IFrame contents

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12827]
When there is an IFrame on a page with a scroll, the IFrame contents remain on the page and scroll when the page is scrolled:

![iframescroll](https://cloud.githubusercontent.com/assets/9294710/17624722/c46cdc8e-609d-11e6-9134-d8e347a65144.gif)
Online test case [here](https://samuknet.github.io/test_cases/iframeOnScrollingPage/index.html). 

This bug is blocking us on our ['doge times reading view' demo](https://mozdevs.github.io/servo-experiments/experiments/readingView/) where we are using IFrames to display ads. 

https://github.com/mozdevs/servo-experiments/issues/2

**Comment by jdm** [comment]
This doesn't reproduce if webrender is not enabled.

cc @pcwalton

**Comment by glennw** [comment]
I'm working on this now - fixing this properly is a prerequisite for fixing things like https://github.com/servo/servo/issues/12286 without hacks.

**Comment by glennw** [comment]
This is fixed when https://github.com/servo/webrender/pull/355 lands and gets updated in servo.

**Comment by glennw** [comment]
Fixed by https://github.com/servo/servo/pull/12932
