### ISSUE TITLE
cannot run servo

### ISSUE THREAD

**Issue by prasanthp96** [servo/servo#12820]
I have downloaded and extracted the servo file from website and when i run the runscript.sh file, there is an error message `./servo: error while loading shared libraries: libavformat.so.54: cannot open shared object file: No such file or directory
`
operating system - Ubuntu 16.04 x64 GNOME 
Need help.
![screenshot from 2016-08-12 01-12-30](https://cloud.githubusercontent.com/assets/11797131/17602345/e7011c02-6029-11e6-8909-0ea0e2d64965.png)

**Comment by sciencefyll** [comment]
Just downloaded the latest-build.tar.gz from the servo.org site, and I have the exact same issue using Arch linux.

**Comment by jdm** [comment]
This is tracked in #12687. Thanks for reporting it!
