### ISSUE TITLE
Servo does no reflect window resize on vw & vh

### ISSUE THREAD

**Issue by Gozala** [servo/servo#12835]
Latest nightly no longer reflects window size changes onto `vw` and `vh`, here is a simple expample

https://Gozala.jsbin.com/kudihem

To reproduce resize a window. Green square should resize with it, but it is not.

and it's source: https://jsbin.com/kudihem/edit?html,css,output

**Comment by jdm** [comment]
Do you know when this regressed?

**Comment by Gozala** [comment]
@jdm no just noticed it today, but it could have being earlier.

**Comment by jdm** [comment]
@Gozala What is the testcase supposed to do that doesn't work in Servo?

**Comment by ConnorGBrewster** [comment]
@jdm It regressed ~3 weeks ago

**Comment by Gozala** [comment]
> @Gozala What is the testcase supposed to do that doesn't work in Servo?

Updated issue description to answer this.

**Comment by jdm** [comment]
I wonder if https://github.com/servo/servo/pull/11890 is the cause, given the timeframe.

**Comment by emilio** [comment]
Also looking, though I can't find an easy way to make an automated test for this unfortunately, probably inside an iframe?

**Comment by jdm** [comment]
Viewport tests can often use iframes, yes.
