### ISSUE TITLE
Nonincremental layout makes a div disappear

### ISSUE THREAD

**Issue by jdm** [servo/servo#12836]
Run `./mach run https://gozala.jsbin.com/kudihem -i` and there's a brief flash of green, then there's only white after that.

**Comment by notriddle** [comment]
Removing the None-ing out in `swap_out` (in construct.rs) makes this problem go away. However, I'm pretty sure there's a deeper bug in here if we're reusing flows in "non-incremental" layout.

**Comment by nox** [comment]
The sample is gone.
