### ISSUE TITLE
Hit test regression on browser.html newtab page

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#12833]
Found on latest nightly (8/11/16)
Steps to reproduce:
1. Open browser.html
2. Try to click on the Hacker News tile
3. It takes you to the Moire Demo

If you move the mouse around, you can see that the hit test is off.

**Comment by jdm** [comment]
I suspect https://github.com/servo/servo/pull/12777 or https://github.com/servo/servo/pull/12813 could be the culprit.

**Comment by emilio** [comment]
Looking

**Comment by emilio** [comment]
I bet I know what's happening, building release now to confirm because bhtml on debug mode hangs on my machine (plus #12840, that didn't help, but I just disabled that in the meantime).
