### ISSUE TITLE
Incorrect clipping of nested stacking contexts.

### ISSUE THREAD

**Issue by emilio** [servo/servo#12842]
Found while writing a test for #12841.

Should render the two equal-sized rectangles, but actually the inner one is clipped incorrectly:

```html
<!doctype html>
<style>
  .outer-sc {
    transform: translate(-50px, -50px);
    position: absolute;
    width: 250px;
    height: 250px;
    top: 250px;
    left: 250px;
    background: blue;
  }
  .outer-sc:hover {
    background: red;
  }
  .inner-sc {
    transform: translate(50px, 50px);
    position: absolute;
    width: 250px;
    height: 250px;
    top: 250px;
    left: 250px;
    background: green;
  }
  .inner-sc:hover {
    background: yellow;
  }
  html, body { margin: 0; padding: 0; }
</style>
<div class="outer-sc">
  <div class="inner-sc">
  </div>
</div>
```

**Comment by emilio** [comment]
Seems independent on whether WR is enabled or not, but the display list contains the inner item correctly.

**Comment by emilio** [comment]
After investigation, it seems that stacking contexts don't take into account children transforms when computing overflow, which is wrong. I have a WIP patch for simple fixes, but I need to take into account more complex transformations other than translation and scaling.

**Comment by glennw** [comment]
@emilio When this is fixed, we can close https://github.com/servo/servo/issues/9578
