### ISSUE TITLE
Resizing on Windows recalculates but clips page

### ISSUE THREAD

**Issue by SaschaNaz** [servo/servo#12866]
![image](https://cloud.githubusercontent.com/assets/3396686/17653666/e0687af0-62d3-11e6-8749-17dbfc709af2.png)

Maximizing the window and waiting reproes this bug on Windows 10.

**Comment by jdm** [comment]
This might be the same problem as #12835, but I'm not sure.

**Comment by SaschaNaz** [comment]
I think this is fixed now.
