### ISSUE TITLE
Intermittent crash in /encoding/textdecoder-labels.html

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#12874]
This is something new in the `Xlib:  extension "XFree86-VidModeExtension" missing on display ":0"` family. I couldn't find a similar one.

    ▶ CRASH [expected OK] /encoding/textdecoder-labels.html
    │ 
    │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
    │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
    │ stack backtrace:
    │    0:     0x7f19d4183fad - backtrace::backtrace::trace::h36e5966500ba9bd9
    │    1:     0x7f19d41846c2 - backtrace::capture::Backtrace::new::h3a3d5e9defd7d407
    │    2:     0x7f19d2c5bb1a - servo::install_crash_handler::handler::h57fd71c5829cfe7c
    │    3:     0x7f19d3df71f3 - AsmJSFaultHandler
    │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
    │    4:     0x7f19d063a32f - <unknown>
    │    5:     0x7f19d27e9e69 - <unknown>
    │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
    │ stack backtrace:
    │    0:     0x7f19d4183fad - backtrace::backtrace::trace::h36e5966500ba9bd9
    │    1:     0x7f19d41846c2 - backtrace::capture::Backtrace::new::h3a3d5e9defd7d407
    │    2:     0x7f19d2c5bb1a - servo::install_crash_handler::handler::h57fd71c5829cfe7c
    │    3:     0x7f19d0085caf - <unknown>
    │    4:     0x7f19d2c5bbab - servo::install_crash_handler::handler::h57fd71c5829cfe7c
    │    5:     0x7f19d3df71f3 - AsmJSFaultHandler
    │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
    │    6:     0x7f19d063a32f - <unknown>
    └    7:     0x7f19d27e9e69 - <unknown>

**Comment by jdm** [comment]
What terrible backtraces those are :(
