### ISSUE TITLE
Add Instructions for Contributing to Servo Using The Janitor

### ISSUE THREAD

**Issue by Coder206** [servo/servo#12879]
I have been using The Janitor (https://janitor.technology) for some time now. It's evident it would greatly simplify the process when creating the environment to new comers to Servo.

I think it would be great to have a link to [https://janitor.technology](url) in the ReadMe.md file.

Tags to add please: E-Easy, A-Documentation, C-Assigned

**Comment by larsbergstrom** [comment]
Done, and thanks for working on this!

**Comment by Coder206** [comment]
@larsbergstrom Thanks :)

**Comment by KiChjang** [comment]
Closing due to https://github.com/servo/servo/pull/12882#issuecomment-242140190.
