### ISSUE TITLE
What is buildbot_steps.yml for?

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#12888]
In https://github.com/servo/servo/pull/12688, I've added the scripts to etc/ci/buildbot_steps.yml, but apparently, saltfs' buildbot/master/files/config/steps.yml is the one that needs to be updated.

Can someone explain what etc/ci/buildbot_steps.yml is for?

**Comment by larsbergstrom** [comment]
We are in the process of switching over to in-tree steps.yml:
https://github.com/servo/saltfs/blob/aa9171bb5f095b7710afca717920dbc36ebdc989/buildbot/master/files/config/factories.py#L299

But I *think* that we're still primarily using the builders that point at the older hard-coded rules. Is that right @edunham @shinglyu @aneeshusa ?

**Comment by aneeshusa** [comment]
Yeah, we're still using the hard-coded rules (which live in the saltfs repo) right now.
