### ISSUE TITLE
img onload is dispatched instead of onerror on failed requests

### ISSUE THREAD

**Issue by Gozala** [servo/servo#12885]
Here is an example illustrating the issue:

https://Gozala.jsbin.com/yugoqil

You should see `Load failed!` message but in servo you see `Load complete.` instead. If you look at the source code https://Gozala.jsbin.com/yugoqil/edit?html,js,output you'll see that's because `onload` event handler on `<img>` is called instead of expected `onerror`.

**Comment by paulrouget** [comment]
PR WIP: https://github.com/servo/servo/pull/12921

**Comment by paulrouget** [comment]
Should work with tomorrow's nightly.
