### ISSUE TITLE
servo reliably crashes when cycling through images

### ISSUE THREAD

**Issue by jrmuizel** [servo/servo#12883]
Load the following url:
http://people.mozilla.org/~jmuizelaar/jeffslideshow/fast.html

After around 20s servo will crash in a variety of different locations including:
- "Too many open files" from the unwrap in find_image_or_metadata
- index out of bounds: the len is 0 but the index is 0 from find_image_or_metadata calling visit_new_type

**Comment by metajack** [comment]
Oh man, I'm really happy to have a better example for too many fds. We've been chasing that one in intermittents for a while (assuming it's the same issue).

**Comment by jrmuizel** [comment]
It looks like we're leaking fds as described here:
https://github.com/servo/ipc-channel/pull/96

**Comment by nox** [comment]
Sample is gone.

**Comment by metajack** [comment]
@jrmuizel Do you have an archive of the sample?

**Comment by jrmuizel** [comment]
I still have a copy. I'll put it up tomorrow.

**Comment by dralley** [comment]
No reproducer, but it seems like the underlying fd leak issue was fixed.

**Comment by jdm** [comment]
Yep.
