### ISSUE TITLE
README OS Links are Broken on Nexus 6P

### ISSUE THREAD

**Issue by Coder206** [servo/servo#12907]
When using the links in the `README.md` file on my Nexus 6P, nothing happens. When using a desktop computer, the links work as expected, redirecting me to the section of the document.

@Ms2ger I am wondering if there is a better way to make the links work on every device.

This issue relates to code I wrote from #12880 
The file affected is `README.md`

I'd like to hear some feedback from people to better understand the proportions of the issue.

Tags to add please: A-Documentation

**Comment by KiChjang** [comment]
It doesn't look like it's a problem with README.md but a problem with all mobile browsers. I'm not sure whether we should look further into this since we don't (and would probably never) support compilation on a mobile device.

**Comment by Coder206** [comment]
@KiChjang What about compilation for Android devices? I personally often use my mobile device to surf Servo on GitHub. I think it's important if Servo is advertised like this: "Servo is a modern, high-performance browser engine designed for both application and embedded use"

**Comment by KiChjang** [comment]
@Coder206 In which case, you'd use a desktop/laptop to cross-compile to android. I don't think anyone would use their mobile device to compile servo...

**Comment by Coder206** [comment]
@KiChjang I realize that it may (and probably should) not be the device used to compile, I still feel like it's important to support mobile devices. 

I am wondering if using the `a` element instead of the header trick would solve the issue.

**Comment by KiChjang** [comment]
@Coder206 I wasn't clear enough when I said that it's not a README.md problem perhaps. It means that all mobile browsers do not scroll to fragments after clicking on the link. If you're still wondering whether you can fix it just by using the `<a>` element, it isn't possible and I have a branch here that changed the OSX link to the `<a>` tag https://github.com/KiChjang/servo/tree/readme.

In short, this is a problem arising from mobile browser apps, and not a Servo issue.

**Comment by Coder206** [comment]
@KiChjang Thanks for clarifying this and for testing with your branch. Shall we close the issue then?
