### ISSUE TITLE
Use typedefs for background-position

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#12902]
For background-position (https://github.com/servo/servo/blob/9785e520aec4d8a821659d4811713ee43bfe82af/components/style/properties/longhand/background.mako.rs#L90), we have created a newtype:

```
pub struct T(pub Position);
pub struct SpecifiedValue(pub Position);
```

and then manually implemented ToCss, ToComputedValue, and parsing by forwarding to the child type.

In such cases instead we can use `pub type T = Position`, `pub type SpecifiedValue = Position`, and eliminate most of the impls.

code: components/style/properties/longhand/background.mako.rs
tests: none, this is a refactoring.
example of similar change: https://github.com/servo/servo/pull/12878/commits/b42ef703c37b889a4a23548aa23bd57a0d69b882

**Comment by hsinewu** [comment]
I would like to work on this issue. Thanks.

**Comment by KiChjang** [comment]
You got it!

**Comment by hsinewu** [comment]
I have some trouble with it.
Provided example link seems to be not working.
I need instructions about derive errors.
Thanks.

**Comment by Manishearth** [comment]
Yeah, that PR was rebased. The commit you want is https://github.com/Manishearth/servo/commit/b42ef703c37b889a4a23548aa23bd57a0d69b882


you will need to remove the derive attributes off the typedefs, typedefs only create new names, not types, so the traits implemented on the inner type still apply.

**Comment by hsinewu** [comment]
For some reason I got E0425 unresolved name on both computed_value::T and SpecifiedValue.
I did make the type alias pub though.
What should I do?

btw, how can I locate the source files & lines where compile errors occurred?
Seems like impls are scattered around somewhat.
The output message given by compiler pointed to ../debug/build/.../out/properties.rs, which doesn't quite look like something I would ever modify.

**Comment by Manishearth** [comment]
Please pastebin your patches so we can see what you're doing.


properties.rs is generated from the mako.rs files. Open that file and look at the context of the relevant lines (and use grep) to find the mako.rs file affected.

Note that `computed_value::T` and `SpecifiedValue` are no longer type constructors. So wherever you see something like `SpecifiedValue(foo)`, you want to replace that with just `foo`. The reverse is true too, wherever there's a `spec.0` where `spec` is `SpecifiedValue`, it should be replaced by just `spec`

**Comment by hsinewu** [comment]
Thanks a lot!
Your information is exactly what I need.

I can build and pass test-tidy now.
I'll send PR soon.
