### ISSUE TITLE
Flush the style sharing candidate chache if we've missed due to the parent.

### ISSUE THREAD

**Issue by emilio** [servo/servo#12913]
We process all children of the same parent sequentially, so once we've missed due to a `Parent` mismatch, we can flush the cache safely before inserting the new element if appropriate.

Code:

 * `components/style/matching.rs`

Tests:

 * Not needed, if passes existing tests and review, it's fine.

**Comment by pathway27** [comment]
I'll have a go at this. I'm kind of new at rust, but looking at the code, is this change for the element_matches_candidate function?

**Comment by emilio** [comment]
Cool! I think it'd be easier if you modify this other chunk of the code, otherwise you're not going to be able to flush the cache https://github.com/servo/servo/blob/master/components/style/matching.rs#L748.

Assigned then! Let me know if you need any help :)

**Comment by KiChjang** [comment]
@pathway27 Are you still working on this?

**Comment by pathway27** [comment]
Sorry, some other obligations came up, please un-assign me.

**Comment by Manishearth** [comment]
@6112 would you like to work on this?

**Comment by 6112** [comment]
Sure, I can work on this.

**Comment by Manishearth** [comment]
Cool. Feel free to ask @emilio any questions you may have!

**Comment by 6112** [comment]
@emilio 
Should we also exit the loop if there's a parent mismatch at https://github.com/servo/servo/blob/master/components/style/matching.rs#L752 ? Or should we still keep running through the loop, and only clear the cache after we're done iterating?

**Comment by emilio** [comment]
Yes, in general, if we've flushed the cache the last parent mismatch and
we've had another one, we should be pretty confident we're not matching
anyway, so I think breaking early is fine :)
