### ISSUE TITLE
Lazily compute and cache the classnames of elements in the style sharing cache.

### ISSUE THREAD

**Issue by emilio** [servo/servo#12912]
When #12668 lands, we can compute the `StyleSharingCandidate` class names the same way as we're computing the `CommonStyleAffectingAttributes` instead of once per test.

Code:
 * `components/style/matching.rs`

Tests:
 * Not needed, if it passes tests and review, it's fine.

**Comment by ashrko619** [comment]
I'd like to work on this :)

**Comment by emilio** [comment]
Hi! The mentioned bug landed, so it's yours!

Let me know if you need any help :)

**Comment by ashrko619** [comment]
Hi, 
I need a bit of help on where exactly the changes should go. This is the first time am dealing with Rust code. Thanks :)

**Comment by emilio** [comment]
No problem!

So, in the file `components/style/matching.rs`, we have a function that compares classes between two elements, called [`have_same_class`](https://github.com/servo/servo/blob/master/components/style/matching.rs#L379-L388).

That function currently takes two elements and compares the two vectors. The key point here is that one element comes straight from the cache, and we might be computing its class attribute a lot of times even when we know it shouldn't change.

So what we'd have to do is adding a field to the `StyleSharingCandidate` struct, something like our current [`common_style_affecting_attributes`](https://github.com/servo/servo/blob/master/components/style/matching.rs#L191), but for classes.

This field should be an `Option<Vec<Atom>>`, that is, an optional vector of strings (atoms are the optimized representation for commonly used strings in Servo).

We should add this field, and then write `have_same_class` in the same way `have_same_common_style_affecting_attributes` is written, that is, something like:

```rust
if candidate.class_attribute.is_none() {
    // compute the class attribute
}
return candidate.class_attribute.unwrap() == element_class_attribute
```

I hope that helps, thanks!
