### ISSUE TITLE
create "mach bootstrap" for MSVC builds to download dependencies

### ISSUE THREAD

**Issue by vvuk** [servo/servo#12914]
MSVC Windows builds have a number of dependencies and environment setup.  We should create "mach bootstrap" that will automatically download cmake, ninja, openssl, etc. and put them in the .servo dir alongside the compiler and cargo.  mach should also set up the proper env vars before building.

The current dependencies and an env setup script are here: http://people.mozilla.org/~vladimir/misc/servo/
cmake and python 2.7 are expected to already be installed.

**Comment by UK992** [comment]
i've try this https://github.com/UK992/servo/tree/msvc-dependencies ... can you check if its ok?

**Comment by metajack** [comment]
I'd very much like it if we either

1) Probed for vcvars.bat and ran it if it hasn't already been run.
or
2) Detected whether vcvars.bat had been run and if not, probe for the location and print out an error with a suggestion of how to fix.

In both cases if the probe failed we should recommend they download VS.
