### ISSUE TITLE
Absolute positioned div hyperlinks not clickable

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12923]
When there is an absolutely positioned div with some image hyperlinks, the first three of the images are not recognized as links by Servo and clicking them does nothing (see test case).

Online test case [here](https://samuknet.github.io/test_cases/absoluteDivHyperlinks/).

The div is positioned with CSS `bottom: 0` which seems to be causing the problem.  When the position of the div is set to `top: 0` instead, a slightly different variation of the issue occurs.

Seems to be an issue with the hit testing?  I don't think this problem is specific to hyperlinks with images.

**Comment by nox** [comment]
This works now.
