### ISSUE TITLE
Remove the mako zip file and use proper python dependencies

### ISSUE THREAD

**Issue by emilio** [servo/servo#12958]
```
<emilio> SimonSapin: btw, do you remember why do we have the mako zip file in-tree? Couldn't we pull it as a dependency like we do with everything else?
<•SimonSapin> emilio: because we didn’t have any other Python code in the tree at the time, and that seemed less fragile than requiring virtualenv
<•SimonSapin> but now that we have a virtualenv we could very well install Mako there
<•SimonSapin> and remove the zip file
<emilio> SimonSapin: I see, I'll fill an issue about that, thanks!
<•SimonSapin> make sure to pin some required version number
```

Should be easy enough, though I'm not too versed in our python infra. @Wafflespeanut would you be interested in mentoring this if nobody does it on their own?

**Comment by SimonSapin** [comment]
Files involved:

* `python/requirements.txt`: add `Mako == 0.9.1`. The latest is 1.0.4 but I don’t know if it has breaking changes.
* `components/style/properties/Mako-0.9.1.zip`: remove
* `components/style/build.rs`: make it use `python/_virtualenv/bin/python`, except on Windows where it’s something like `python/_virtualenv/Scripts/python.exe` but I’m not sure.

**Comment by Wafflespeanut** [comment]
I can help :)

**Comment by crypto-universe** [comment]
Hi! I'd like to do this task! It is more or less clear what to do. How to verify result? Just compile stage1 compiler?

**Comment by KiChjang** [comment]
@crypto-universe If `./mach build -d` doesn't throw any errors and that you can find the generated .rs files from .mako.rs (e.g. properties.rs exists, which is built from properties.mako.rs) under `target/` then it's working.
