### ISSUE TITLE
Track only the number of important declarations in a declaration block

### ISSUE THREAD

**Issue by emilio** [servo/servo#12959]
Once #12943 lands, `DeclarationBlock` will have two fields, `normal_count` and `important_count` that track the amount of declarations with a given priority are in that block.

We should be able to remove one of the two fields, and compute the other one in terms of the length of the `declarations` vector and the other, simplifying the code that computes it.

Code:

 * `components/style/properties/properties.mako.rs`

Tests:

 * No need to write new ones, the existing tests should cover it. You'll have to modify `test/units/style` to take the change into account.

**Comment by SimonSapin** [comment]
Run `./mach test-unit` to try changes to `tests/unit`.

**Comment by cers** [comment]
I'd like to give it a go, but this would be my first foray into servo (and indeed rust).

Should the field be removed completely, or should the calculation of it just be moved to the end of the parsing, when it can be calculated by subtracting the important ones from the total?

If completely removed, then I guess some consideration is needed to components/script/dom/element.rs and components/style/selector_matching.rs, which both seem to reference the normal_count of a style rule/block.

**Comment by emilio** [comment]
Sure, it's yours! :)

Yes, the idea is removing it completely, and yes, the calculations in element.rs and selector_matching.rs should be modified appropriately.

If you have any more doubts, don't hesitate in reaching out :)
