### ISSUE TITLE
Change the separator used in rust path

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#12961]
[This](https://github.com/servo/servo/blob/master/python/servo/command_base.py#L286) is wrong, because, in Windows, we'll then be using a mixture of forward and backslashes. It hasn't caused any error so far, surprisingly enough. But, let's fix it anyway, by replacing with `os.path.join` :)

**Comment by tp6vup54** [comment]
Please give me this, I'll take care of it, thanks! cc @tp6vup54

**Comment by Wafflespeanut** [comment]
It's yours! :)
