### ISSUE TITLE
Implement HTMLTimeElement.dateTime

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#12967]
The harder part here isn't implementing the WebIDL getters and setters, but rather parsing the dateTime value in a machine-readable equivalent.

Spec: https://html.spec.whatwg.org/multipage/semantics.html#dom-time-datetime
Files: `components/script/dom/webidls/HTMLTimeElement.webidl`, `components/script/dom/htmltimeelement.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/text-level-semantics/the-time-element/001.html`

**Comment by saurvs** [comment]
Can't we just use [lifthrasiir/rust-chrono](https://github.com/lifthrasiir/rust-chrono), as it provides [parse_from_rfc3339](https://lifthrasiir.github.io/rust-chrono/chrono/datetime/struct.DateTime.html#method.parse_from_rfc3339) ?

**Comment by Ms2ger** [comment]
How certain are you that that function exactly matches the HTML standard? :)

**Comment by saurvs** [comment]
The HTML standard [says](https://html.spec.whatwg.org/multipage/infrastructure.html#dates-and-times) that it's date-time format is a subset of ISO8601 but also specifies it's own parsing rules (RFC3339 does the same thing). So in that case we'll have to write our own parser :). I'd like to work on it.

**Comment by KiChjang** [comment]
Also note that I've filed a bug on WHATWG about the "machine equivalent" wording here: whatwg/html#1702.

@saurvs In any case, you have dibs on the issue!

**Comment by saurvs** [comment]
When I run ```./mach test-wpt tests/wpt/web-platform-tests/html/semantics/text-level-semantics/the-time-element/001.html``` I get the following error. I'm not sure what's wrong?

```
STDERR: Socket error on port 8443
STDERR: Socket error on port 8000
STDERR: Socket error on port 8001
STDERR: Traceback (most recent call last):
  File "/Users/Saurav/repos/servo/tests/wpt/web-platform-tests/tools/serve/serve.py", line 146, in create_daemon
    ssl_config, **kwargs)
  File "/Users/Saurav/repos/servo/tests/wpt/web-platform-tests/tools/serve/serve.py", line 342, in start_ws_server
    ssl_config = None)
  File "/Users/Saurav/repos/servo/tests/wpt/web-platform-tests/tools/serve/serve.py", line 303, in __init__
    self.port = ports[0]
IndexError: list index out of range
Error running mach:

    ['test-wpt', 'tests/wpt/web-platform-tests/html/semantics/text-level-semantics/the-time-element/']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

EnvironmentError: http server on port 8000 failed to start

  File "/Users/Saurav/repos/servo/python/servo/testing_commands.py", line 359, in test_wpt
    return self.run_test_list_or_dispatch(kwargs["test_list"], "wpt", self._test_wpt, **kwargs)
  File "/Users/Saurav/repos/servo/python/servo/testing_commands.py", line 380, in run_test_list_or_dispatch
    return correct_function(**kwargs)
  File "/Users/Saurav/repos/servo/python/servo/testing_commands.py", line 365, in _test_wpt
    return self.wptrunner(run_file, **kwargs)
  File "/Users/Saurav/repos/servo/python/servo/testing_commands.py", line 403, in wptrunner
    return run_globals["run_tests"](**kwargs)
  File "/Users/Saurav/repos/servo/tests/wpt/run_wpt.py", line 13, in run_tests
    return run.run_tests(paths=paths, **kwargs)
  File "/Users/Saurav/repos/servo/tests/wpt/run.py", line 36, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "/Users/Saurav/repos/servo/tests/wpt/harness/wptrunner/wptrunner.py", line 157, in run_tests
    test_environment.ensure_started()
  File "/Users/Saurav/repos/servo/tests/wpt/harness/wptrunner/environment.py", line 212, in ensure_started
    raise EnvironmentError("%s server on port %d failed to start" % (scheme, port))
```

**Comment by KiChjang** [comment]
Did you have any server running while you're trying to `./mach test-wpt`?

**Comment by saurvs** [comment]
Well I `Ctrl-D`-ed to terminate a running wpt test. It's fixed now.

Although I'm having trouble getting the two of the tests to pass. Apparently `datetime` should be reflected by `dateTime` and I'm not sure how to do that.

**Comment by KiChjang** [comment]
@saurvs The `make_getter!` and `make_setter!` macros defined in macros.rs should help you with that.

**Comment by KiChjang** [comment]
@saurvs Are you still working on this?

**Comment by saurvs** [comment]
@KiChjang Yes. Tests are going on in my college. I should submit a PR by the end of this week.

**Comment by KiChjang** [comment]
@saurvs The end of the week never came...

**Comment by chajath** [comment]
Any takers of this issue yet? If not I'd like to have it as my starter task

**Comment by jdm** [comment]
@chajath Go for it! Please ask questions if anything is unclear!

**Comment by chajath** [comment]
Continuing on the discussion. I see several places where we depend on now-deprecated `time` package. Should we move on to `rust-chrono` consistently across all packages while we are at it?

**Comment by jdm** [comment]
@chajath That would be great!

**Comment by chajath** [comment]
So, adding DateTime as DOMString with make_getter! / make_setter! macros trivially solve all the test cases in 001.html so far. But as the original issue description mentions the harder part is to actually make dateTime reflect content in a machine parsable way.

Would it be still worth it to check in dateTime DOMString attribute?

**Comment by chajath** [comment]
So I've been reading the spec over and over again, and I'm not sure what should happen if the present datetime is not a machine-readable string. Is the purpose of parsing the date time to validate that string is in one of the 10 acceptable format? And reject a value and throw an error otherwise?
