### ISSUE TITLE
Implement HTMLDataElement#value

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#12966]
We already have convenient macros defined for reflecting content attributes. Look into `make_getter` and `make_setter` for accomplishing this task.

Spec: https://html.spec.whatwg.org/multipage/semantics.html#dom-data-value
Files: `components/script/dom/webidls/HTMLDataElement.webidl`, `components/script/dom/htmldataelement.rs`
Test: None yet, but one that tests for the behaviour of the `value` IDL attribute should be [created](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) under `tests/wpt/web-platform-tests/html/semantics/text-level-semantics/the-data-element/` (Use `./mach create-wpt <path>` for creating WPT tests)

**Comment by ofekd** [comment]
I would like to work on this :)

**Comment by KiChjang** [comment]
It's yours!
