### ISSUE TITLE
Support SVG element

### ISSUE THREAD

**Issue by jdm** [servo/servo#12974]
Spec: https://www.w3.org/TR/SVG11/struct.html#SVGElement

Goals:
* create a `SVGElement` type that is created by the parser
* support the `width` and `height` attributes
* use these attributes to create a new fragment in layout with the appropriate width and height

Blocks #12973.

**Comment by jdm** [comment]
cc @jrmuizel

**Comment by Ms2ger** [comment]
For the `SVGElement` type, we'll need to:

* add `components/script/dom/webidls/SVGElement.webidl` based on <https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement>
* add `[Pref="..."]` to the interface
* add an implementation of the interface at `components/script/dom/svgelement.rs`
* add a case to `create_element` in `components/script/dom/create.rs`, behind a `PREFS.get("...").as_boolean().unwrap_or(false)` check, for svg-namespaced elements with the `svg` local name, that creates the new `SVGElement` class.

**Comment by splav** [comment]
I would like to take this one.

**Comment by jdm** [comment]
Great! Please ask questions about anything that's unclear.

**Comment by Wafflespeanut** [comment]
@splav Any news on this?

**Comment by splav** [comment]
@Wafflespeanut the fragment creation is the only thing left. I think I'll finish it today or tomorrow.

**Comment by Wafflespeanut** [comment]
Glad to hear :)
