### ISSUE TITLE
Can't compile dev and release in parallel

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#12984]
STEPS TO REPRODUCE:
1. Pull servo
2. `./mach fetch`
3. In one terminal, `./mach build --dev`
4. In another terminal, `./mach build --release`

EXPECTED RESULTS: Both build in parallel

ACTUAL RESULTS: The release build says "`Blocking waiting for file lock on the git checkout`" until the dev build finishes.

I would expect all the git stuff to be done if mach fetch has run.

**Comment by jdm** [comment]
I suspect this is an implementation limitation in Cargo.

**Comment by metajack** [comment]
`./mach fetch` and the cargo infrastructure to support offline compilation are pretty new. The lock was required back when multiple cargo's might be doing git operations, but in this case it seems like all the right stuff is already segregated or disabled, so in this case parallel execution could be allowed.

I suggest filing a feature request on cargo to disable the lock in this mode.

**Comment by bzbarsky** [comment]
Looks like cargo has loosened up its locking some (see <https://github.com/rust-lang/cargo/issues/3594#issuecomment-275721585>) and this is no longer an issue.
