### ISSUE TITLE
Disabling SSL verification for experimental purposes

### ISSUE THREAD

**Issue by rzambre** [servo/servo#12982]
In the past when I had to disable SSL verification (to use with Googles' web-page-replay framework) to collect repeatable page-load measurements, I had to comment out https://github.com/servo/servo/blob/9c713cb4688f1a1729ada64846fac2d8426b1ef4/components/net/http_loader.rs#L67-L70 and it worked fine.

I see that create_http_connector() has moved to components/net/connector.rs and so commented out https://github.com/servo/servo/blob/master/components/net/connector.rs#L32-L36. The build was successful but I'm still seeing "certificate verify failed" on Servo. Some websites I'm seeing this message on are:

* http://www.facebook.com
* http://www.google.com
* http://www.twitter.com
* http://www.etsy.com

ehow.com and ebay.com however work well with those lines commented out.

@larsbergstrom @seanmonstar anything else I need to hack out to disable SSL verification?

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/master/components/net/connector.rs#L55 perhaps?

**Comment by rzambre** [comment]
Yupp, that worked pretty well. Stupid me didn't scroll down enough. Thanks!
Solution to disable SSL verification: comment out  https://github.com/servo/servo/blob/master/components/net/connector.rs#L32-L36 + https://github.com/servo/servo/blob/master/components/net/connector.rs#L55
