### ISSUE TITLE
Change starting line of scripts from 0 to 1

### ISSUE THREAD

**Issue by nox** [servo/servo#12996]
The first line of a script should be line 1, not line 0.

The `0` in the `CompileOptionsWrapper::new` call in `ScriptHelpers::evaluate_script_on_global_with_result` in `components/script/dom/window.rs` should be changed to `1`.

**Comment by cjm00** [comment]
I'd like to work on this issue but am new to contributing to open source projects and would appreciate having someone to ask questions about the process.

**Comment by jdm** [comment]
@cjm00 You're welcome to ask questions here, or our [mailing list](https://www.mozilla.org/en-US/about/forums/#dev-servo), or our [IRC channel](https://wiki.mozilla.org/IRC) (#servo).
