### ISSUE TITLE
Remove unnecessary clone from ServiceWorkerManager::prepare_activation

### ISSUE THREAD

**Issue by jdm** [servo/servo#12999]
Right before returning from `prepare_activation`, we clone `scope_url` and pass the result to a function. This is redundant; we should be able to pass `scope_url` without cloning it.

Code: `components/script/serviceworker_manager.rs`

No need for automated tests; if it builds, it's good enough for a PR.

Note: This is reserved for the upcoming Taiwan Code Sprint; please do not work on it.

**Comment by wdv4758h** [comment]
I'm trying :)
