### ISSUE TITLE
Switching from building without debug-mozjs to building with fails to link

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#12995]
STEPS TO REPRODUCE:
1. `./mach build --dev`
2. `./mach build --dev --debug-mozjs`

EXPECTED RESULTS: build works

ACTUAL RESULTS: Link failures like this:

> Undefined symbols for architecture x86_64:
>   "js::oom::maxAllocations", referenced from:
>       js::oom::IsSimulatedOOMAllocation() in libjs-dd291aac52e4d65e.rlib(jsglue.cpp.o)

**Comment by nox** [comment]
Caused by https://github.com/servo/mozjs/issues/97.

**Comment by nox** [comment]
This is still true.

**Comment by nox** [comment]
There are no link errors anymore but it still takes forever to (re)build.

**Comment by nox** [comment]
Actually, nothing more can be done here, it does reuse artefacts from one debug-mozjs build to the next one and it doesn't fail to link.
