### ISSUE TITLE
Servo's code should be beautiful

### ISSUE THREAD

**Issue by brson** [servo/servo#130]
Servo is Rust's showpiece. The maintainability of Servo reflects very strongly on Rust's own design, and its claims about 'programming in the large'.

Additionally, browser engines are notoriously complex and difficult to contribute to for various reasons. Surely many developers could be tempted to contribute to a browser engine with a modern design, and in a potentially much more pleasant language.

When people look at Servo's code they should like what they see and want to participate.

**Comment by nox** [comment]
Old meta-issue with no real book-keeping, we can probably close this.
