### ISSUE TITLE
Stop using a fake PipelineId value when calling handle_network_event

### ISSUE THREAD

**Issue by jdm** [servo/servo#13000]
There's a TODO comment in the code that handles `ChromeToDevtoolsControlMsg::NetworkEvent` explaining that we should use a real pipeline ID value, rather than `PipelineId::fake_root_pipeline_id()`. Since both `HttpRequest` and `HttpResponse` contain pipeline ID values, we can now do this.

Code: `components/devtools/lib.rs`, `components/devtools_traits/lib.rs`

Note: This is reserved for the Taiwan Code Sprint; please don't work on it.

**Comment by wdv4758h** [comment]
I'll try it out.
