### ISSUE TITLE
Store Stylesheets in Stylist

### ISSUE THREAD

**Issue by pradeep90** [servo/servo#1300]
Right now, each Stylesheet is just dropped at the end of `add_stylesheet`.

We would probably need this to support dynamic style - #976 

If this is fine, we can modify `Rule` to refer to the parent StyleRule's corresponding `Selector` and the parent's `PropertyDeclaration`s instead of copying them over.

@SimonSapin Do you have any thoughts on this?

**Comment by jdm** [comment]
We definitely keep Stylesheet objects around now, so this issue doesn't really make sense to leave open.
