### ISSUE TITLE
PropertyDeclarationBlock should have Arc<~[PropertyDeclaration]> instead of ~[PropertyDeclaration]

### ISSUE THREAD

**Issue by pradeep90** [servo/servo#1301]
Right now, `Rule` has `Arc<~[PropertyDeclaration]>`

However, the original `~[PropertyDeclaration]` is copied from StyleRule's `PropertyDeclarationBlock` into its every Rule as a new Arc object. 

This means that we have N Arcs wrapping copies of the same object instead of N references to the same Arc object.

**Comment by eefriedman** [comment]
This was fixed.
