### ISSUE TITLE
console should be a namespace, not an interface instance

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#13010]
In particular, `console.log` should not require a particular `this` value.

**Comment by bzbarsky** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1270601 and https://bugzilla.mozilla.org/show_bug.cgi?id=989619

**Comment by Ms2ger** [comment]
Would be nice to have a spec too ;)

**Comment by bzbarsky** [comment]
There's most of a spec.  See https://github.com/heycam/webidl/pull/121 but note the issue described in https://github.com/whatwg/console/issues/3#issuecomment-219549472 which we solved in Gecko by adding an extended attribute for namespaces to opt in to the "have an extra object on the proto chain" behavior and using it for console.
