### ISSUE TITLE
Fixed divs are missing with webrender enabled

### ISSUE THREAD

**Issue by jdm** [servo/servo#13015]
```
<div style="position: fixed">
<span>hi there</span>
</div>
```
yields a white screen with webrender enabled.

cc @glennw

**Comment by glennw** [comment]
I'm unable to reproduce this issue - the test displays the same for me with or without webrender enabled. @jdm Is it possible this was tested before https://github.com/servo/servo/pull/13002 landed (which may have inadvertently fixed this problem)?

**Comment by jdm** [comment]
Probably! I'll verify when I'm in front of a computer.

**Comment by jdm** [comment]
Verified.
