### ISSUE TITLE
servo crashes during startup when forwarding X over SSH

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#13018]
STEPS TO REPRODUCE:
1.  ssh from a Mac to a Linux box.
2. git clone servo.
3. `./mach build --dev`
4. `./mach run --dev`

EXPECTED RESULTS: It works.

ACTUAL RESULTS: A window pops up, then disappears and the terminal shows:

> Xlib:  extension "XFree86-VidModeExtension" missing on display "localhost:10.0".
> libGL error: failed to load driver: swrast

and then a stack backtrace (twice) and then:

> Servo exited with return value -4

The stack backtrace shown is:

> Stack trace for thread "main"
> stack backtrace:
>   0:     0x7fd3153c83c1 - backtrace::backtrace::libunwind::trace
>                        at /home/bzbarsky/mozilla/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
>                         - backtrace::backtrace::trace<closure>
>                        at /home/bzbarsky/mozilla/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
>   1:     0x7fd3153c8f70 - backtrace::capture::{{impl}}::new
>                         at /home/bzbarsky/mozilla/servo/target/debug/build/backtrace-3bc1ff360ebb00cb/out/capture.rs:79
>    2:     0x7fd314845372 - servo::install_crash_handler::handler
>                         at /home/bzbarsky/mozilla/servo/components/servo/main.rs:70
>    3:     0x7fd311dbecaf - <unknown>
>    4:     0x7fd312bee8bd - XQueryExtension
>    5:     0x7fd312be2be1 - XInitExtension
>    6:     0x7fd313139348 - <unknown>
>    7:     0x7fd313137138 - <unknown>
>    8:     0x7fd313137c06 - <unknown>
>    9:     0x7fd317ca1cac - glutin::api::x11::ffi::glx_extra::{{impl}}::SwapIntervalSGI
>                         at /home/bzbarsky/mozilla/servo/target/debug/build/servo-glutin-f4f2d36f8da8f49a/out/glx_extra_bindings.rs:558
>   10:     0x7fd317c9163d - glutin::api::glx::{{impl}}::finish
>                         at /home/bzbarsky/mozilla/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.6.1/src/api/glx/mod.rs:250
>   11:     0x7fd317caad24 - glutin::api::x11::window::{{impl}}::new
>                         at /home/bzbarsky/mozilla/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.6.1/src/api/x11/window.rs:642
>   12:     0x7fd317cb02f0 - glutin::platform::platform::api_dispatch::{{impl}}::new
>                         at /home/bzbarsky/mozilla/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.6.1/src/platform/linux/api_dispatch.rs:197
>   13:     0x7fd317cb0c4c - glutin::window::{{impl}}::build
>                         at /home/bzbarsky/mozilla/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-glutin-0.6.1/src/window.rs:233
>   14:     0x7fd317c28891 - glutin_app::window::{{impl}}::new
>                         at /home/bzbarsky/mozilla/servo/ports/glutin/window.rs:166
>   15:     0x7fd317c2ee55 - glutin_app::create_window
>                         at /home/bzbarsky/mozilla/servo/ports/glutin/lib.rs:48
>   16:     0x7fd3148458e7 - servo::main
>                         at /home/bzbarsky/mozilla/servo/components/servo/main.rs:138
>   17:     0x7fd31976b656 - __rust_maybe_catch_panic

@glennw, is this setup expected to work?

**Comment by bzbarsky** [comment]
Oh, those two lines about Xlib/libGL are shown _before_ the window appears.  So we manage to get the window up after those, at least.

**Comment by metajack** [comment]
I believe this used to work pre-WR as we had people doing display on windows X servers from linux dev machines.

I think we should fix bugs in our use of libGL if possible, but we should probably not go out of our way to make networked display work. The linux world seems headed quickly for Wayland now, and I'd rather us put effort there.

**Comment by kriston** [comment]
This is a problem using VNC as well.  In this case I am using TigerVNC where GLX isn't available.  The stack trace is attached.

[servo-crash.txt](https://github.com/servo/servo/files/862725/servo-crash.txt)

**Comment by dralley** [comment]
Given the slow and steady march towards Wayland (and the fact that X11 forwarding was always far more complicated in practice than theory due to the crazy mishmash of extensions) should this be left open or closed as wontfix?

**Comment by kriston** [comment]
Do we really think Wayland is any closer than it was three years ago?

**Comment by jdm** [comment]
Servo is usable on Wayland, so yes.

**Comment by bzbarsky** [comment]
OK, so how do I use Wayland to forward a display to my Mac from a Linux box?  And what about the VNC crash described in https://github.com/servo/servo/issues/13018#issuecomment-288523388 ?

And the real question above, I suspect, is not "does Servo run on Wayland" but "are people actually running Wayland?"

**Comment by dralley** [comment]
Well, it's the default environment on the GNOME version of recent editions of every distribution (Debian, RHEL/CentOS, Ubuntu, Fedora).

Forwarding with Wayland should be possible with Waypipe although all of this software is pretty young so bugs and glitches are likely.  https://gitlab.freedesktop.org/mstoeckl/waypipe/
