### ISSUE TITLE
Make DOMTokenList iterable

### ISSUE THREAD

**Issue by jdm** [servo/servo#13019]
Blocked on #12819. We're missing `iterable<DOMString?>;` from `DOMTokenList.webidl`. I believe that adding it _should_ be all that's necessary to make iteration over DOMTokenList values like the `classList` attribute of `Element` work.

Code: `components/script/dom/webidls/DOMTokenList.webidl`, `components/script/dom/domtokenlist.rs`
Test: [create a test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) in `tests/wpt/web-platform-tests/dom/lists` that tests the properties of the iterating over a [DOMTokenList](https://dom.spec.whatwg.org/#interface-domtokenlist)

**Comment by yoyo930021** [comment]
I try it.

**Comment by yoyo930021** [comment]
I have a question.
header is key-value,
but DOMString is only have a String.

`get_value_at_index` `get_key_at_index` function how to write?

**Comment by izgzhen** [comment]
Not currently. Looks like they are only required for pair iterator now. But you may want to track the following threads for related discussions:

- https://github.com/servo/servo/issues/13021
- https://github.com/servo/servo/pull/13081

**Comment by jdm** [comment]
@yoyo930021 Are you still working on this?

**Comment by yoyo930021** [comment]
I dont know how to do this.
for only one value.

**Comment by jdm** [comment]
@yoyo930021 Did the original instructions I presented not work?

**Comment by tizianasellitto** [comment]
@jdm  I don't know if @yoyo930021 is still working on this but I tried a solution [here](https://github.com/tizianasellitto/servo/commit/69d9777efb54956fc1f75457b8114a456f50a499). Please, just ignore this if he wants to keep working on it.

I'm not sure for-of loop test is what you need.

**Comment by yoyo930021** [comment]
@tizianasellitto 
give you to do.
Thanks.

**Comment by jdm** [comment]
@tizianasellitto That looks great! However, that's a regular for loop, not a for of loop. You'll want to use `for (var class of elementClasses)` instead; I recommend pushing each element found into a second array, then using `assert_array_equals`.
