### ISSUE TITLE
Check the return value of JS_SplicePrototype

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13011]
Noticed in review of #13009. I hope we can assert it never fails, because I don't have a clue what do otherwise.

CC @jdm @bzbarsky

**Comment by bzbarsky** [comment]
Hmm.  For non-singletons it just calls JS_SetPrototype, so can fail in the same cases.  But all globals are singletons (see `GlobalObject::createInternal` which passes `SingletonObject` as the `NewObjectKind`).

For singletons it can fail on OOM, looks like.  For example, the shape allocation can fail.

Gecko just treats failure to JS_SplicePrototype the same way it treats any other failure in setting up the object, including failure to allocate the object to start with.  Presumably servo would want to do the same...

**Comment by Ms2ger** [comment]
If it's just OOM for globals, a panic would be fine.

**Comment by bzbarsky** [comment]
Again, do whatever you do if the JS_NewGlobalObject or the various property-definition stuff fails.

**Comment by nox** [comment]
I took care of that in #13030.
