### ISSUE TITLE
Make FormData iterable

### ISSUE THREAD

**Issue by jdm** [servo/servo#13020]
Blocked on #12819. We're missing `iterable<USVString, FormDataEntryValue>;` from `FormData.webidl`, which will require implementing the `Iterable` trait for `FormData`. See #12998 for an example of doing this.

Code: `components/script/dom/webidls/FormData.webidl`, `components/script/dom/formdata.rs`
Test: [create a test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) in `tests/wpt/web-platform-tests/XMLHttpRequest` that tests the properties of the iterating over a [FormData](https://xhr.spec.whatwg.org/#interface-formdata)

**Comment by wdv4758h** [comment]
I'll try this one :smile_cat:
