### ISSUE TITLE
Wrong referrer policy used in cors_preflight_request

### ISSUE THREAD

**Issue by jdm** [servo/servo#13026]
The specification for [step 1](https://fetch.spec.whatwg.org/#cors-preflight-fetch) says we should use `request`'s referrer policy. There's an obvious copy/paste typo that uses the default request policy for the new `preflight` variable instead.

Code: `components/net/fetch/methods.rs`
Test: modify `test_cors_preflight_fetch` in `tests/unit/net/fetch.rs` by setting the original referrer policy used to `origin` and setting a URL referrer a path (`a.html`), and checking that the referrer header that the server receives does not contain the path. Run the test with `./mach test-unit -p net`.

**Comment by wdv4758h** [comment]
I'll take this :smile:

**Comment by jdm** [comment]
Go for it! Ask questions if anything is unclear!

**Comment by shinglyu** [comment]
@jdm: So by setting the policy as `origin`, a Referrer URL `foo.com/a.html` will become `foo.com` in the header, right?

**Comment by jdm** [comment]
@shinglyu: Exactly.
