### ISSUE TITLE
New request in cors_preflight_fetch uses incorrect boolean argument

### ISSUE THREAD

**Issue by jdm** [servo/servo#13025]
Every other argument to `Request::new` in step 1 is based off the corresponding value from `request`, but we pass `false` for `is_service_worker_global_scope`. We should use the same value from the original request instead.

Code: `components/net/fetch/methods.rs`

No need for a test; we don't have any code that can observe this yet. If it builds, it's good for a PR.

**Comment by hsinewu** [comment]
I would like to work on this, thank you!

**Comment by jdm** [comment]
Go for it! Ask questions if anything is unclear!

**Comment by hsinewu** [comment]
Thank you, I'm still studying the code but
looks like I'll have to unwrap Rc<request> somehow

If you can point out some similar code snippet that I can refer to, it will definitely be helpful to me, and make the code more consistent.
I'll have to read some more documents for now.

**Comment by hsinewu** [comment]
Ok, I'm a bit confused, what is the right way to access request parameter, is it just request or &request?
Looking at http_network_fetch at line:964, it uses &request.
But in the body of cors_preflight_fetch it uses just request.

I have no idea which is the right way, but maybe either way would be fine I guess?
I'll try it without & for now.

**Comment by KiChjang** [comment]
@hsinewu Unwrapping `Rc<T>` to `T` is unnecessary, because `Rc<T>` automatically derefs into `&T` (i.e. you can simply treat it as a `&T`). So you can simply just use `request.is_service_worker_global_scope`.

**Comment by hsinewu** [comment]
@KiChjang  Sounds very straightforward, thanks for your comment!
