### ISSUE TITLE
Integrate mp4parse

### ISSUE THREAD

**Issue by jdm** [servo/servo#13024]
The goal of this issue is to replicate the work of #12186, using a library that won't have the same distribution problems that ffmpeg does.

https://crates.io/crates/mp4parse

**Comment by jdm** [comment]
@splav Is this something you would be interested in?

**Comment by splav** [comment]
Taking this one.

**Comment by est31** [comment]
Same could be done with my `ogg_metadata` crate: https://crates.io/crates/ogg-metadata

@jdm does that sound reasonable and is wanted by servo?

It may not be from mozilla, it may not be included into firefox, it may not be as well tested (running on millions of computers), and it may not be as much famous as mp4parse, but it was designed to do the same things, just for the ogg format.

There has been discussions in the past that mp4parse and ogg_metadata are to be integrated into video-metadata, I guess those are obsolete now?

**Comment by jdm** [comment]
@est31 Absolutely!

**Comment by jdm** [comment]
We're using mp4parse now.
