### ISSUE TITLE
Convert imports in generate_imports into one per line

### ISSUE THREAD

**Issue by jdm** [servo/servo#13036]
Right now there's a long list in `CodegenRust.py` like:
```python
        'js::jsapi::{Handle, HandleId, HandleObject, HandleValue, HandleValueArray}',
        'js::jsapi::{INTERNED_STRING_TO_JSID, IsCallable, JS_AtomizeAndPinString}',
```
These are in alphabetical order, which is great. However, adding new imports to this list is a pain, because we need to re-wrap all the subsequent lines that become too long. We should convert it to a list of one import per line, so it's easy to add new ones and they remain in alphabetical order.

**Comment by KiChjang** [comment]
This is located in `components/script/dom/bindings/codegen/CodegenRust.py`, under the `CGBindingsRoot` class.

**Comment by ashrko619** [comment]
Do you mean like this?
```
'js::jsapi::Handle',
'js::jsapi::HandleId',
'js::jsapi::HandleObject',
```

**Comment by jdm** [comment]
@ashrko619 Sorry, this is reserved for the Taiwan Code Sprint.

**Comment by jdm** [comment]
It's yours!
