### ISSUE TITLE
Implement WebGLRenderingContext::isEnabled

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#13040]
Part of #10209.

Assigned to @ofekd.

**Comment by ofekd** [comment]
I have the code written but I can't verify the tests are passing, because of this:

```
> ./mach test-wpt tests/wpt/web-platform-tests/webgl/conformance-1.0.3/conformance/state/gl-enable-enum-test.html                       
Running 1 tests in web-platform-tests

Unsupported test type wdspec for product servo
Ran 1 tests finished in 0.0 seconds.
  • 1 ran as expected. 1 tests skipped.

```

Tried running `update-manifest`. Anyone knows how to fix it?

**Comment by KiChjang** [comment]
Check if the test is enabled?

**Comment by ofekd** [comment]
@KiChjang I've read the documentation but probably missed it, where are tests enabled/disabled?

**Comment by jdm** [comment]
If you're on linux, I bet it's caused by https://dxr.mozilla.org/servo/source/tests/wpt/metadata/webgl/conformance-1.0.3/__dir__.ini#2

**Comment by ofekd** [comment]
thanks @jdm, submitted PR #13337
