### ISSUE TITLE
DIV with translateY in container with overflow hidden and set height gets clipped

### ISSUE THREAD

**Issue by samuknet** [servo/servo#13053]
The problem occurs when there is an element with a translateY set in a container with CSS `overflow: hidden` and after the containers set `height` property exceeds a certain amount.  

Depending on the positioning of the element and the height of the container, the element gets clipped from the top down.  The clipping rect increases in height as the `height` of the container increases.

It seems for this to occur it requires all three of:
1. `height` being set on the container element
2. `overflow:hidden` being set on the container element
3. `transform: translateY(..)` being set on the element which gets clipped
### Example

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: helvetica;
    }
    .container {
      overflow: hidden;
      height: 1000px;
      border: 1px solid black;
    }
    .this-gets-clipped {
      width: 400px;
      text-align: center;
      margin: auto;
      font-size: 200%;
      margin-top: 490px;
      transform: translateY(-50%);
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="this-gets-clipped">
      This text gets clipped
    </div>
  </div>
</body>

</html>
```
### Result in Servo using ./mach run -r -w

<img width="1025" alt="screen shot 2016-08-26 at 11 07 49" src="https://cloud.githubusercontent.com/assets/9294710/18001981/5a4269ba-6b7d-11e6-9c15-2d8ba4f8ce0b.png">

In this example:
- Increasing the height of `.container` gradually clips more of the text, up to the point where the text is completely hidden.
- The issue doesn't occur when `overflow:hidden` is not present on `.container` or when height is smaller than a certain amount.
- The issue doesn't occur when `transform:translateY(-50%)` is not set on the DIV that gets clipped

Online test case [here](https://samuknet.github.io/test_cases/overflowHiddenTransformClipping/).

**Comment by glennw** [comment]
This occurs without webrender too - it's probably a layout bug to do with calculating the overflow rect for a div that contains transformed children.

**Comment by mrobinson** [comment]
I'm not seeing this issue any longer. Feel free to reopen if it's still a problem.
