### ISSUE TITLE
"Home" and "End" keys don't scroll to top/bottom of page

### ISSUE THREAD

**Issue by StringEpsilon** [servo/servo#13082]
Like the title says. 

Steps to reproduce:
- Open reddit.com
- scroll down a bit
- Press "home"
- Press "end"

Expectation:
You are now at the bottom of the page.

Actual:
You are still where you manually scrolled to.

OS:
Arch Linux, 64 bit.

Servo version: Latest nightly build as of 08/27/2016 @ 12:41pm (UTC)

**Comment by paulrouget** [comment]
This should not be too hard to implement. See `fn handle_key()` in `ports/glutin/window.rs`.

**Comment by jdm** [comment]
This isn't appropriate for E-easy unless we also explain how to do the relevant scrolling as well.

**Comment by paulrouget** [comment]
You're right. I thought that'd be an easy one, but it doesn't appear to be that straight forward.

webrender [expects a delta](https://github.com/servo/webrender_traits/blob/4d5036748208733dbdad43b7faec27ccccbce9a6/src/api.rs#L180) (`Point2D<f32>`). Do we want to change that to:

```rust
enum ScrollAction {
    Delta(Point2D<f32>),
    ToStart
    ToEnd,
}
```

Does it make sense?

Or do we want to pass `f32::INFINITY` and `f32::NEG_INFINITY` ?

**Comment by glennw** [comment]
Having an enum sounds good. The Start/End types should probably allow you to specify x and/or y direction though?

So perhaps something like:

```
enum ScrollLocation {
  Delta(f32),
  Start,
  End,
}
```

and then:

```
struct ScrollRequest {
  vertical: ScrollLocation,
  horizontal: ScrollLocation,
}
```

Or something like that?

**Comment by samuknet** [comment]
Once we have decided these `ScrollRequest` details, would this be something I could potentially work on?  Thanks!

**Comment by paulrouget** [comment]
> Once we have decided these ScrollRequest details

We should do what Glenn is suggesting.

> would this be something I could potentially work on?

Go for it. Thank you!

I'm not sure how much I can help here, but feel free to ask questions.

**Comment by samuknet** [comment]
Ok this sounds good.  Should the `ScrollRequest` struct also contain a `phase` field of type `TouchEventType`? From what I can see from the code, this would make sense. 

I was wondering where is the code that calls WebRenders [`fn scroll`](https://github.com/servo/webrender_traits/blob/4d5036748208733dbdad43b7faec27ccccbce9a6/src/api.rs#L180)?  My thinking is that  `fn scroll_window()` in `ports/glutin/window.rs` dispatches this event but I can't tell where the `WindowEvent::Scroll` event gets picked up and 'translated' into the call for webrenders `fn scroll`? 

So, this detail aside, I'm thinking the general things to be done are:
* add two more match arms to [`fn handle_key`](https://github.com/servo/servo/blob/master/ports/glutin/window.rs#L846) in `ports/glutin/window.rs` to queue scroll start and scroll end requests in a similar way to the existing scroll up/down code.
* Modify `WindowEvent::Scroll` to be made up of the `ScrollRequest` struct described above. 
* Refactor `fn scroll` in webrender_traits to accept the new `ScrollRequest` struct

**Comment by paulrouget** [comment]
> Or alternately the new ScrollRequest could also encapsulate the TypedPoint2D

I think it makes sense.

> So, this detail aside, I'm thinking the general things to be done are […]

Looks about right.

> How far the Delta -> ScrollRequest refactoring should go?

I'm not sure. Where ever there's an easy access to the page size. Which might be in WebRender.

@glennw ?

**Comment by glennw** [comment]
Yes, I'd pass that through all the way to WR I think (which means declaring the type in webrender_traits).

**Comment by samuknet** [comment]
One thing I have noticed is that other browsers' implementation of Home/End scrolling operates on the element which currently has focus as opposed to the element which the mouse is currently over.

If we were to implement this in the same way that Page Up/Page Down key scrolling is implemented, the behavior would not quite be identical to other existing implementations.  Is this an acceptable way to differ from other implementations?

Otherwise we would have to request the scroll on the element which currently has focus and go from there.  Most of this implementation would appear to be the refactor with the `ScrollRequest` struct though I imagine depending on which way we go, it could be a very different refactor.

**Comment by paulrouget** [comment]
As far as I understand the current code, Key::up, Key::down, Key::pageup and Key::pagedown, all send a scroll event, with the current position of the mouse. Moving the mouse hover a scrollable area (without clicking) and pressing Key::down will scroll the scrollable area.

I would recommend to follow this (wrong) behavior for now, and file a follow-up issue to scroll the focused element with a scroll operation is initiated from a key.

**Comment by KiChjang** [comment]
Is this fixed?

**Comment by jdm** [comment]
I don't recall see any PR get opened for this work.

**Comment by KiChjang** [comment]
Unassigning this, since there's nobody working on it.

**Comment by gterzian** [comment]
@samuknet How is it going with this issue? Let me know if you are still working on it, otherwise I might try to give it a shot 😄

**Comment by samuknet** [comment]
Hey @gterzian :)

I got a working version of it which seems to work pretty well - see:
https://github.com/samuknet/servo/tree/home-end-key-scroll
https://github.com/samuknet/webrender/tree/home-end-key-scroll

I got to the stage where I wanted to neaten up a few of the loose ends and simplify some of the new match arms and various other things - so in short, it is functionally working but not entirely done.

There are a few glitches/usability issues that occur when using the home/end key to scroll, but these are separate issues - these are:
https://github.com/servo/servo/issues/13290
https://github.com/servo/servo/issues/13291

In implementing it I had to do quite a heavy refactor which goes right the way through from event handling to webrenders `scroll` function.  This implementation works although I'm so not sure how far it is off being a PR and whether the way I've refactored is the right way to go - @paulrouget @glennw? 

So feel free to give it your own shot - or alternately we could work on getting this fork PR'ed by fixing any issues anyone can find.

**Comment by gterzian** [comment]
@samuknet Sounds like a lot of good work. 👍  

Have you considered opening a PR with your work, even if it's still a work in progress? That way others can give you feedback in a more structured way (they can comment on specific diffs for example). 

I personally think it's never too early to open up a PR. 😄

**Comment by samuknet** [comment]
Cheers - sure, will go over again and PR in the next few days or so.

**Comment by paulrouget** [comment]
@samuknet do you want to keep working on this? Do need any help? Or do you want someone else to take over?

**Comment by samuknet** [comment]
@paulrouget 
I have got a working implementation but there are a few things which may not be done in the best way, so I'm going to submit a PR, if that sounds good?  The home/end key scrolling is working as expected.

I currently have servo using my `webrender` fork however I'm unsure how to get servo to use my `webrender_traits` fork? Am I right in thinking this is what I need to do? So my PR's would be done in the order of webrender_traits, then webrender, then Servo. 

Currently I have just `webrender_traits` directly in the `webrender` fork but am unsure how to use a my webrender traits fork.

**Comment by jdm** [comment]
You should be able to make a single PR for both WR and WR_traits changes,then make a PR for servo after that merges and use `./mach cargo-update -p webrender` (possibly the same for webrender_traits, too).

**Comment by samuknet** [comment]
I've updated my webrender fork branch ('home-end-key-scroll') to be up to date with the latest webrender, and I am using  `paths = [..]` in config to select webrender and webrender_traits, however when building Servo I get the error:

`Package webrender_traits v0.8.0 (file:///Users/sam/servo/servo_fork/webrender/webrender) does not have these features: serde_macros`.

I noticed this is a problem mentioned [here](https://github.com/servo/webrender/pull/430), but I couldn't find a fix.

I've also tried the `Cargo.toml` [replace] method, using:
``
[replace]
"webrender:0.6.0" = { path = '/Users/sam/servo/servo_fork/webrender/webrender/' }
"webrender_traits:0.6.0" = { path = '/Users/sam/servo/servo_fork/webrender/webrender_traits/' }
``
 but this didn't work either.

Any ideas?

Thanks 😃

**Comment by paulrouget** [comment]
Does it work better with `webrender:0.8.0` instead of `webrender:0.6.0`?

**Comment by gterzian** [comment]
@samuknet I had this problem before as well I remember, I think you need to update your servo repo, and then as @paulrouget says indeed replace webrender in `Cargo.toml` and please make sure it's version `0.8.0`

**Comment by samuknet** [comment]
I've tried this, I still get the error unfortunately.  I removed `paths=[..]` in config and added the `[replace]` in `Cargo.toml` with 0.8.0 although I get the same error.

**Comment by paulrouget** [comment]
You use a clone of webrender from servo/webrender?

And in components/servo/Cargo.toml, you added:

```
[replace]
"webrender:0.8.0" = { path = '/Users/sam/servo/servo_fork/webrender/webrender/' }
"webrender_traits:0.8.0" = { path = '/Users/sam/servo/servo_fork/webrender/webrender_traits' }
```

?

**Comment by gterzian** [comment]
I had exactly this problem here: https://github.com/servo/servo/issues/13249#issuecomment-252425439

But that should have been fixed in Servo by now(https://github.com/servo/servo/issues/13249#issuecomment-252442418), @samuknet are you 100% sure you are building your webrender fork using the latest version of the servo repo?

**Comment by samuknet** [comment]
@gterzian Thanks, I think I've got it now.  I had to make changes to my old work to account for the latest Servo code.

So now is the procedure to submit a webrender PR alongisde the Servo PR?

**Comment by jdm** [comment]
Yep!
