### ISSUE TITLE
Remove unneeded clone in the style system cache

### ISSUE THREAD

**Issue by emilio** [servo/servo#13089]
Was added in #12912, but we don't need to `clone().unwrap()` the vector. Using `as_ref()` should be enough.

Code:  
 * [`components/style/matching.rs`](https://github.com/servo/servo/blob/master/components/style/matching.rs#L391).

Tests:
 * No need for adding new tests, if it passes review and existing tests is fine.

**Comment by ashrko619** [comment]
I'd like to fix this. I worked on #12912, did not know about ```as_ref()``` :)

**Comment by emilio** [comment]
Sure, it's yours! :)
