### ISSUE TITLE
Make Servo's profile compatiable with Gecko profiler UI

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#13103]
Gecko has a useful Profiler visualizer: https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler

It might be interesting to make servo's profiler format work with Gecko's, so we can reuse all their goodies. 

It's just a vague idea, comments are welcome!

cc @yoyo930021

**Comment by fitzgen** [comment]
Right now, we only have tracing data, no sampling, so call trees aren't really an option.

We do have https://github.com/servo/servo/wiki/Profiling#generating-timelines, FWIW.

**Comment by shinglyu** [comment]
Thanks for the info!

**Comment by nox** [comment]
Should we be producing output that can be fed to perf.html instead now?

**Comment by jdm** [comment]
Same problem about tracing vs. sampling, but yes.
