### ISSUE TITLE
"./mach clippy" doesn't work

### ISSUE THREAD

**Issue by wdv4758h** [servo/servo#13117]
I'm finding commands to run [rust-clippy](https://github.com/Manishearth/rust-clippy), and I find out it is already integrated with `mach` (`./mach clippy`).
But when I'm trying to run it, it fails :cry: 

error message : 

```
error: feature names may not contain slashes: `plugins/clippy`
```

![servo-clippy](https://cloud.githubusercontent.com/assets/2716047/18075779/9681dda4-6eaa-11e6-9701-9eb0d326dc76.png)

**Comment by Manishearth** [comment]
Huh, that seems like a breaking change in cargo

**Comment by Manishearth** [comment]
Does it work with `--features=plugins/clippy` instead of `--features=script/plugins/clippy` in devenv_commands.py?

**Comment by wdv4758h** [comment]
Nope, another error:
```
error: Package `servo v0.0.1 (file:///home/wdv4758h/zone/servo/components/servo)` does not have these features: `plugins`
```

**Comment by Manishearth** [comment]
Filed https://github.com/rust-lang/cargo/issues/3058

This can be fixed by just making servo depend on plugins too; but I'd rather avoid that.

**Comment by Manishearth** [comment]
Alright, turns out that functionality wasn't supposed to work.

In that case, we should add plugins as a dependency to `servo`, and give it a `clippy` feature that turns on `plugins/clippy`

**Comment by frewsxcv** [comment]
Fixed in https://github.com/servo/servo/issues/14134
