### ISSUE TITLE
Add a "mach" option to only run Rust code checking

### ISSUE THREAD

**Issue by wdv4758h** [servo/servo#13118]
Some people will use something like [cargo-check](https://github.com/rsolomo/cargo-check) to run correctness checking without the code translation. If one just want to make sure the Rust code won't make compiler angry, it should run faster.

To do this, we just need to pass `-Zno-trans` to rustc. So, I think we can add a `mach` option like `./mach build --check` to do this.

**Comment by Manishearth** [comment]
You'll also need to specify the package; `./mach build --check -p script` or whatever. `-Zno-trans` only works on the last crate in the tree.

**Comment by nox** [comment]
`./mach check` is a thing now.
