### ISSUE TITLE
Implement Navigator.cookieEnabled

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13124]
You'll need to copy the NavigatorCookies implementation from https://html.spec.whatwg.org/multipage/webappapis.html#navigator and interface from https://html.spec.whatwg.org/multipage/webappapis.html#navigatorcookies

I think this should return the result of running `is_cookie_averse` on the associated document object, but I'm not 100% sure.

 - spec: https://html.spec.whatwg.org/multipage/webappapis.html#dom-navigator-cookieenabled
 - files: https://github.com/servo/servo/blob/master/components/script/dom/navigator.rs , https://github.com/servo/servo/blob/master/components/script/dom/webidls/Navigator.webidl
 - test: https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/html/dom/interfaces.html

**Comment by ashrko619** [comment]
I'd like to work on this  :)

**Comment by Ms2ger** [comment]
I think this should just return true.

**Comment by ashrko619** [comment]
Here-https://w3c.github.io/webappsec-suborigins/#cookies, cookie-averse does not necessarily mean cookies are disabled. So I too think that it should just return true.

**Comment by ashrko619** [comment]
@Manishearth What should be done in the tests?
For now I have added the interface in the interfaces.html and have also removed the corresponding expected FAIL lines from interfaces.html.ini.

**Comment by Manishearth** [comment]
You shouldn't have to add the interface to interfaces.html (because it is NoInterfaceObject), just run it and remove the FAIL lines.
