### ISSUE TITLE
Implement HTMLOptionsCollection

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#13129]
In order to test for this new behaviour, HTMLSelectElement#{options, length} may be implemented at the same time, to ensure that we are getting a valid HTMLOptionsCollection.

Spec: https://html.spec.whatwg.org/multipage/infrastructure.html#htmloptionscollection
Files: `components/script/dom/htmloptionscollection.rs` (new), `components/script/dom/webidls/HTMLOptionsCollection.webidl` (new), `components/script/dom/htmlselectelement.rs`, `components/script/dom/webidls/HTMLSelectElement.webidl`
Test: `tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/common-HTMLOptionsCollection.html` (may need to be extended to ensure we test the options attribute properly)

cc @splav

**Comment by splav** [comment]
Ok, taking this.

**Comment by splav** [comment]
Hello, sorry for this taking so much time. The beginning of September was very crazy for me, so I basically had no free to time for working on Servo at all. Now it's getting normal and I'm back on track.
