### ISSUE TITLE
We do a lot of testing of ineffective dependencies

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#13125]
STEPS TO REPRODUCE with revision 8695552052074b0aacd764c28d2183f283e7b4fd:

1. `./mach build -d --debug-mozjs` (this last part may not be needed)
2. `./mach run -d tests/html/bindings_perf.html`

EXPECTED RESULTS: Load the page.

ACTUAL RESULTS: Load the page, then assert about "Testing a completely ineffective dependency?", then the content process crashes and the browser is in an unusable state.

//cc @emilio

**Comment by bzbarsky** [comment]
Note that I get this same assertion on the wikipedia front page too.

**Comment by emilio** [comment]
Stupid assertion added by me yesterday.

**Comment by emilio** [comment]
s/Stupid/too strict/
