### ISSUE TITLE
reloading a page should not create a new pipeline

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#13123]
If I'm not mistaken, reloading a page creates a new pipeline, and I don't think it should.
I'm not sure. But at least it should not create a new history entry when `reload()` is called.

Today it's possible to load a page, reload it, a do `iframe.goBack()`.

So either re-use the pipeline or drop the old pipeline.

**Comment by metajack** [comment]
@ms2ger do you have time to look at this?

**Comment by ConnorGBrewster** [comment]
It looks like we just need a method to replace the `Frame`'s current entry with the new `Pipeline` after the page is loaded again. https://html.spec.whatwg.org/multipage/browsers.html#entry-update

@Ms2ger I could take this one if needed
