### ISSUE TITLE
Create Rule Hash lazily, before selector matching

### ISSUE THREAD

**Issue by pradeep90** [servo/servo#1312]
Currently, we eagerly add each stylesheet to the Rule Hash as we receive it.

However, Gecko builds its Rule Hash only before starting Selector Matching (and rebuilds it only if there is a change to the sheets)

So, we would need to:
- store the stylesheets in Stylist #1300 
- build the Rule Hash only before we call match_subtree
  - collect all the Rules from the sheets 
  - sort them before inserting them into the Rule Hash
- When selector-matching a node, merge the pre-sorted rules that match from ID hash, Class hash, etc. (right now, we don't pre-sort. We just sort all the rules that match.)

**Comment by nox** [comment]
This can be closed, many things changed since 2013 and most importantly since Stylo is a thing.
