### ISSUE TITLE
A reflow for script query will sometimes supress needed for display reflows.

### ISSUE THREAD

**Issue by emilio** [servo/servo#13131]
Reduced test case:

```html
<!doctype html>
<style>
  .container div {
    width: 50px;
    height: 50px;
    background: blue;
  }
  .container div:nth-child(2) {
    background: red;
  }
</style>
<div class="container">
  <div></div>
</div>
<script>
  let container = document.querySelector('.container');
  window.onload = function() {
    container.insertBefore(document.createElement('div'), container.firstChild);
    container.firstChild.offsetTop;
    // console.log(container.children.length);
  }
</script>
```

If you remove `container.firstChild.offsetTop`, then it'd work as expected.

I'm looking into this, though unfortunately doesn't seem easy to fix quickly, so I don't know how much time I can spend looking into this.

**Comment by emilio** [comment]
Actually it was easy to fix, I have a fix.

**Comment by pcwalton** [comment]
Just to be clear, the failure here is that the page is not painted.

**Comment by emilio** [comment]
Yeah, for the record, the page is not painted because the `Query` reflow suppressed the painting, and the next `ForDisplay` reflow was suppressed by script.
