### ISSUE TITLE
Implement OpenEndedDictionary

### ISSUE THREAD

**Issue by jeenalee** [servo/servo#13144]
A good portion of web platform tests for `dom::headers`, `dom::request`, and `dom::response` are failing due to missing OpenEndedDictionary implementation. 

These failing tests throw the message, `(some) dict is not iterable`. 

OpenEndedDictionary is a future IDL construct, and there is an ongoing discussion about it [here](https://github.com/whatwg/fetch/issues/164).

**Comment by jdm** [comment]
Gecko's solution to this is the `MozMap` type (https://dxr.mozilla.org/mozilla-central/source/dom/webidl/Headers.webidl?q=path%3Aheaders.webidl&redirect_type=single#11).

**Comment by Ms2ger** [comment]
I'm looking into this.
