### ISSUE TITLE
How will in page links be handled by joint_session?

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#13150]
I'm talking about: `<a href="#foo"> … <h1 id="foo">`

As for now, each history entry has its own pipeline. But when we will support anchors, the previous history entry might be the same document. Pressing back will not switch to the previous pipeline, but keep the same pipeline and scroll.

I'd just like to know, more or less, what will change at the constellation level. Will we just keep the `FrameState`, reference the same pipeline twice, and add a `scroll_position` attribute?

/cc @ConnorGBrewster

**Comment by paulrouget** [comment]
Same question about the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API).

**Comment by ConnorGBrewster** [comment]
Yes, the `FrameState` will hold information about the `scroll_position` or the fragment it should scroll to. It will also store some information about the state for the entry in the `BrowsingContext`; however, that is a bit more complex as the `state` has to be stored in its script thread, but as far as the constellation is concerned, we will just add fields to `FrameState` to track fragments/state.

**Comment by paulrouget** [comment]
Thanks. That's all I wanted to know.
