### ISSUE TITLE
Bad font display on Windows

### ISSUE THREAD

**Issue by SaschaNaz** [servo/servo#13168]
![image](https://cloud.githubusercontent.com/assets/3396686/18225577/d6c367d2-7230-11e6-8cf4-a52baf4fdcff.png)

Korean characters are 'encrypted' on Windows. The page in this screenshot is [Daum](http://daum.net/).

**Comment by lygstate** [comment]
are that fixed now？

**Comment by SaschaNaz** [comment]
It still has several glitches but yes.

![image](https://cloud.githubusercontent.com/assets/3396686/20462324/87d54a0e-af5d-11e6-9cdf-5576d62efb26.png)
