### ISSUE TITLE
Intermittent failure of /_mozilla/webgl/conformance-1.0.3/conformance/ogles/GL/build/build_001_to_008.html and /_mozilla/webgl/conformance-1.0.3/conformance/ogles/GL/build/build_009_to_016.html

### ISSUE THREAD

**Issue by emilio** [servo/servo#13165]
First seen in #13159.

**Comment by jdm** [comment]
```
  ▶ ERROR [expected OK] /webgl/conformance-1.0.3/conformance/ogles/GL/build/build_001_to_008.html
  └   → gl.getProgramInfoLog is not a function
```

**Comment by Wafflespeanut** [comment]
Also,

    ▶ ERROR [expected OK] /webgl/conformance-1.0.3/conformance/ogles/GL/build/build_009_to_016.html
    └   → gl.getProgramInfoLog is not a function

**Comment by emilio** [comment]
All these `gl.whatever` is not a function make me think that this might be related to the latest changes in object prototypes that have been introduced. The WebGL tests use `eval()` exhaustively, and I'm wondering if something like https://github.com/servo/servo/pull/13017 could be the root cause.

cc @nox

**Comment by emilio** [comment]
Gah, turns out I shouldn't look at these issues by night, and those are actually unimplemented functions... I'll investigate more when I have the time.
