### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by samuknet** [servo/servo#13164]
Servo can't load [this image](https://samuknet.github.io/test_cases/imageNotLoading/brokenImage.jpeg).  When included in a webpage, the image does not display and the error event is being fired on the 'img' element.

What is it about this image that means Servo can't load it? It works in FF/Chrome.  

This [test page](https://samuknet.github.io/test_cases/imageNotLoading/) shows this image not loading (alongside some working images) and the reported error.

**Comment by kaksmet** [comment]
That jpeg is using a chroma subsampling ratio currently not supported by the jpeg-decoder crate (which servo uses to decode jpegs). I filed an [issue](https://github.com/kaksmet/jpeg-decoder/issues/48) for this in jpeg-decoder.

**Comment by iamrohit7** [comment]
@kaksmet Can this be closed now?

**Comment by jdm** [comment]
@iamrohit7 If Servo can load the image, yes. If not, it sounds like we need to upgrade the version of the image crate that we're using.

**Comment by kaksmet** [comment]
@iamrohit7 I'll publish jpeg-decoder 0.1.9 shortly. When servo updates to it this issue can be closed.
