### ISSUE TITLE
Github issue & pull request lists are squashed to the left

### ISSUE THREAD

**Issue by samlh** [servo/servo#13166]
![image](https://cloud.githubusercontent.com/assets/118173/18222378/fbfae5ca-714a-11e6-89ee-4b852f57364c.png)

**Comment by notriddle** [comment]
Minimal test case:

```html
<!DOCTYPE html>
<style>
#c {
  display: table;
  width: 100%;
  table-layout: fixed;
}
#d {
  float: left;
  width: 100%;
}
</style>
<div id=c><div id=d>Test text</div></div>
```

![firefox-with-minimal-case](https://cloud.githubusercontent.com/assets/1593513/18234806/d3356f40-72c4-11e6-9b95-0aa440259074.png)
![servo-with-minimal-case](https://cloud.githubusercontent.com/assets/1593513/18234807/d79e101e-72c4-11e6-977f-0a3c1d68204d.png)
