### ISSUE TITLE
Add support for parsing and serialization of <single-transition>

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#13162]
Specs: https://drafts.csswg.org/css-transitions/#transition-shorthand-property
MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/transition
The transition CSS property is a shorthand property for transition-property, transition-duration, transition-timing-function, and transition-delay.
As specified at the specs, we need to parse and serialize transition property. To do this, we should create a struct like this to keep its values such as delay, duration, property and timing function:

```rust
struct SingleTransition {
    property: Option<TransitionProperty>,
    duration: Option<Time>,
    delay: Option<Time>,
    timing_function: Option<TransitionTimingFunction>,
}
```

When I search for TranstionProperties I find this enum: style::properties::animated_properties::TransitionProperty or it can be stored as enum like this:
```rust
enum TransitionProperty {
    All,
    Property(String),
}
```

Also I find TransitionTimingFunction in: style::properties::longhands::transition_timing_function::computed_value::TransitionTimingFunction It can be used as well. But I want to hear @Manishearth's opinions about these.

Also transition property can be like this: `transition: margin-left 4s, color 1s;`, should we store them as 2 structs or find a way to store them in one struct?

Note: assigned to me.

cc @Manishearth

**Comment by Manishearth** [comment]
> Also I find TransitionTimingFunction in: style::properties::longhands::transition_timing_function::computed_value::TransitionTimingFunction It can be used as well.

You can move intermediate types out of the longhands code into `values/*/transition.rs` if you need. That's what values/ is _for_, intermediate types.

> Also transition property can be like this: transition: margin-left 4s, color 1s;, should we store them as 2 structs or find a way to store them in one struct?

That's the transition property, which is a vector of single-transitions. We're not implementing that, because if we were to implement that we'd have to handle the stylo glue or the servo layout code.

Right now we'll only add single-transition to the values module.

**Comment by Manishearth** [comment]
Btw, spec is at https://drafts.csswg.org/css-transitions/#transition-shorthand-property, the MDN page is just developer documentation. The spec may be more nuanced regarding serialization.

**Comment by Manishearth** [comment]
Uh, I was wrong, for some reason I thought that `transition` was a longhand. It's a shorthand, and we already implement it.

Do you want to try `mask` instead?

**Comment by canaltinova** [comment]
Sure, I can try :)
