### ISSUE TITLE
Return an enum instead of a boolean from dispatch_event

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13196]
Perhaps `enum { Canceled, NotCanceled }`.

**Comment by jdm** [comment]
Code: `components/script/dom/eventtarget.rs`, `components/script/dom/eventdispatcher.rs`

**Comment by aochagavia** [comment]
This change requires editing (EventTargetMethods)[https://doc.servo.org/script/dom/bindings/codegen/Bindings/EventTargetBinding/trait.EventTargetMethods.html], which is a generated binding. Where should one make the changes so they are reflected in the generated code?

**Comment by aochagavia** [comment]
Also, would `EventStatus` be a good name for the new enum?

**Comment by jdm** [comment]
Yes, the method defined in `EventTarget.webidl` and generated in `EventTargetMethods` cannot be modified to return an enum, so we will need to convert the enum value to a boolean at that point.

**Comment by jdm** [comment]
I'm marking this assigned under the assumption that you're working on fixing this :)

**Comment by aochagavia** [comment]
@jdm I have put up a PR on https://github.com/servo/servo/pull/13397
