### ISSUE TITLE
The pipeline visibility logic is wrong

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#13191]
By visibility, I'm talking about `pipeline.visible`, introduced in #10225.

The way it works today is:
- if iframe.setVisibility() is called, all the inner *current* pipelines are updated
- if a new inner pipeline is created, its visible property is inherited from its parent

This is wrong. This breaks if current pipeline is updated. It should work that way:
- if iframe.setVisibility() is called, all the inner pipelines are updated (not just the current ones)
- if a new inner pipeline is created, its visible property is inherited from the previous pipeline, or if none, from its parent

**Comment by paulrouget** [comment]
STR:

- load a page
- rAF runs
- call `iframe.setVisiblity(false)`
- rAF frozen (good)
- click on a link
- rAF runs (wrong)

**Comment by jmr0** [comment]
This makes sense - basically we want pages to behave according to the visibility of the iframe when we navigate to them? Happy to take a look at this.

**Comment by paulrouget** [comment]
> basically we want pages to behave according to the visibility of the iframe when we navigate to them?

Yes.

> Happy to take a look at this.

Thank you! Let me know if you need any help.
