### ISSUE TITLE
HTML Image Map

### ISSUE THREAD

**Issue by samuknet** [servo/servo#13197]
Image maps with the `<map>` and `<area>` tags are not currently implemented - this is something listed in the remaining work wiki doc.

Online test case [here](https://samuknet.github.io/test_cases/imageMap/).

**Comment by jdm** [comment]
This is intended as a project for a group of students at NCSU this term. Please don't work on it without talking with me first!

**Comment by nox** [comment]
Clicking works, but there remains #18757.
