### ISSUE TITLE
Adding Documentation for MSVC

### ISSUE THREAD

**Issue by Coder206** [servo/servo#13206]
In the light of #12916's completion, it's important to let the contributors know how to setup their Windows environments for Servo. 

Files to modify: Anything with documentation (ie, README.md)

cc @larsbergstrom

**Comment by larsbergstrom** [comment]
Thanks! I'm trying this out right now, and here's what I've got for some initial steps. I've only tried it on one non-clean Virtual Machine so far, though...

# Windows MSVC pre-setup
- Install Git for Windows (https://git-scm.com/download/win)
DO allow it to add git.exe to the PATH (default settings for the installer are fine)
- Install Visual Studio 2015 Community Edition (https://www.visualstudio.com/)
You MUST add "Visual C++" to the list of installed components. It is not on by default.
- Install Python for Windows (https://www.python.org/downloads/release/python-2711/)
The windows x86-64 MSI installer is fine.
You should change the installation to install the "Add python.exe to Path" feature.
- Install virtualenv
In a normal Windows Shell (cmd.exe or "Command Prompt" from the start menu), do:
```
pip install virtualenv
```
If this does not work, you may need to reboot for the changed PATH settings to take effect.

# Clone servo

- Open a normal Windows shell (cmd.exe, or "Command Prompt" from the start menu)
- Make a clone of Servo:
```
git clone https://github.com/servo/servo
```

# Build servo

```
cd servo
mach.bat build
```

**Comment by Boddlnagg** [comment]
I'm trying this right now, but it's failing to compile `mozjs_sys`:
```
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#7cd66925)`
process didn't exit successfully: `D:\Code\servo\target\release\build\mozjs_sys-661d4efe7c7ca939\build-script-build` (ex
it code: 101)
--- stderr
makefile.cargo:98: *** recipe commences before first target.  Stop.
thread 'main' panicked at 'assertion failed: result.success()', D:\Code\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2
d\master\build.rs:43
stack backtrace:
   0:     0x7ff7538547ea - std::rand::thread_rng::hf605c918a7eb7363
   1:     0x7ff753852f82 - std::rt::lang_start::haaae1186de9de8cb
   2:     0x7ff75385392d - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   3:     0x7ff753841be3 - __ImageBase
   4:     0x7ff7538439c0 - __ImageBase
   5:     0x7ff7538572e1 - _rust_maybe_catch_panic
   6:     0x7ff7538529ba - std::rt::lang_start::haaae1186de9de8cb
   7:     0x7ff75385bfa8 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
   8:     0x7ffff0cf8363 - BaseThreadInitThunk
```

**Comment by retep998** [comment]
Note that it is not enough to simply have `python.exe` in my `PATH`, I also had to make sure the `scripts` folder was in my `PATH` so I could run pip to install virtualenv and for mach to see virtualenv.

Also I am disappointed that there is no `mach.ps`.

**Comment by Boddlnagg** [comment]
Selecting the "Add to PATH" option in the Python installer added both the Python installation's root directory and the `scripts` directory. I just needed to logoff and log in to Windows again for these changes to take effect.

**Comment by retep998** [comment]
`Finished debug [unoptimized + debuginfo] target(s) in 2395.9 secs`

I guess it worked.

**Comment by retep998** [comment]
Okay, after commenting out my `.cargo/config`, servo now actually runs, and then is totally useless. Loading any page does get the title, but the page itself is totally blank.
![](http://i.imgur.com/CfX6xPr.png)
Furthermore, it sits around eating up 2 CPU cores while doing absolutely nothing.
![](http://i.imgur.com/78WOIcp.png)
If I close servo, the process continues to run and starts eating up _all_ my CPU cores.
![](http://i.imgur.com/iqC5eY9.png)

**Comment by Coder206** [comment]
@retep998 You need to specify a URL.

**Comment by retep998** [comment]
@Coder206 I did `cmd /c mach.bat run -d http://www.purple.com`. Is that not enough?

**Comment by Coder206** [comment]
@retep998 That should do it. I stand corrected mine is expecting like yours. Win 10?

**Comment by UK992** [comment]
@retep998 I suspect this is because of dummy font settings in gfx.

**Comment by retep998** [comment]
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10586 N/A Build 10586
```
AMD Radeon R9 380 with up to date drivers with full OpenGL 4.5 support.

**Comment by Coder206** [comment]
@retep998 Thanks, this seems to be a general Windows or perhaps just Windows 10 issue.

**Comment by Boddlnagg** [comment]
By looking at `makefile.cargo:98` in `mosjs-sys` I found the line
```
$(message You must either have the Native Win32 python installed in C:/python27, or set NATIVE_WIN32_PYTHON to point to the appropriate python.exe.)
```
which is unfortunately never shown when building, because it ends up in stdout instead of stderr, so it won't be forwarded by cargo.

Setting `NATIVE_WIN32_PYTHON` then actually fixed the issue :smiley:
Now I'm also at the point where running servo shows an empty white window with the correct title, but nothing else. I'm running Windows 10 Home.

**Comment by larsbergstrom** [comment]
Thanks, everybody! It looks like the instructions are correct (though need a fix for @Boddlnagg's issue, potentially) enough to put on the website.

That said, as @retep998 and @Coder206 have noticed and I can confirm, the MSVC build currently does not complete loading and is blank. We'll have to look into that :-)

**Comment by Coder206** [comment]
@larsbergstrom I think I had issues with storage space on my VM. What are your thoughts (or anyone's) about adding a recommended disk space?

**Comment by retep998** [comment]
With regards to disk space... for a simple dev build, with no tests, and no release build, and not counting space taken up in the cargo cache...
![](http://i.imgur.com/0rF0vc6.png)

**Comment by Coder206** [comment]
@retep998 Thanks for doing this. I think this is why I had issues compiling (ie compiling "script" failed)

**Comment by larsbergstrom** [comment]
Yeah, I think that a "low disk space warning" (as a separate issue) might be worthwhile. Right now, when we run out of space, the script build fails in a way that is both opaque and non-trivial to recover from - you typically have to do a clean build.

**Comment by Coder206** [comment]
@larsbergstrom Success on clean Windows 10 machine

**Comment by Jayflux** [comment]
You don't need Visual Studio.
You can get Visual C++ as stand alone from here:
http://landinghub.visualstudio.com/visual-cpp-build-tools
Choose default install options

**Comment by Coder206** [comment]
@Jayflux I like that much better, it saves lots of space

**Comment by Jayflux** [comment]
Failing for me
https://pastebin.mozilla.org/8909561

**Comment by larsbergstrom** [comment]
Can you do `set PATH` and paste the results in here? I'm worried that there is another, more evil, python that is first in your `PATH`. Mine looks like:
```
C:\Users\larsberg>set PATH
Path=C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\WiX Toolset v3.10\bin
```

**Comment by Jayflux** [comment]
```
C:\Users\Jason\workspace\servo>set PATH
Path=C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Windows\Microsoft.NET\Framework64\;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Oracle\VirtualBox;C:\Program Files\Sublime Text 3;C:\Program Files (x86)\Skype\Phone\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Git\cmd;C:\Users\Jason\AppData\Roaming\npm;C:\Program Files (x86)\Nmap
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```

**Comment by Jayflux** [comment]
```NATIVE_WIN32_PYTHON```  hasn't worked for me

**Comment by aochagavia** [comment]
The instructions worked for me as well.

@Coder206 Is there an open issue for the problem of seeing a white screen instead of the contents of the website? I am experiencing the same problem on Windows 10 Educational (Version 10.0.10586) with an Intel HD Graphics 4000.

**Comment by Coder206** [comment]
@aochagavia No there is no issue for it

**Comment by aochagavia** [comment]
Should I create a new one?

**Comment by Coder206** [comment]
I would think it would be a good idea. Thanks for doing this @aochagavia!

**Comment by vvuk** [comment]
in mozjs makefile.cargo, there's a line: ```SRC_DIR = $(shell pwd)```  I wonder if for you, pwd is giving c:\......, and for me, it's giving c:/....

For me ```%MOZTOOLS_PATH%\pwd``` gives ```/c/proj/r```; but that's with a local MOZTOOLS_PATH.  You should see whatever mach does to set up $PATH/$MOZTOOLS_PATH and what pwd it finds.

**Comment by Jayflux** [comment]
@vlad are there any steps to working out what pwd is giving me?
These commands don't run in the console

**Comment by Jayflux** [comment]
Followed @larsbergstrom's walkthrough on a windows 10 VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Build doesn't happen, i get this:
![servo error win](https://cloud.githubusercontent.com/assets/936006/18531372/ec2ffdce-7acd-11e6-9f70-318a2c0b770f.jpg)

**Comment by Jayflux** [comment]
@vvuk 
cmder:
```
C:\Users\Jason\workspace\servo (master)
λ .servo\msvc-dependencies\moztools\bin\pwd.exe
/c/Users/Jason/workspace/servo
```

CMD
```
C:\Users\Jason\workspace\servo>.servo\msvc-dependencies\moztools\bin\pwd.exe
/c/Users/Jason/workspace/servo

C:\Users\Jason\workspace\servo>
```

**Comment by Jayflux** [comment]
> By looking at makefile.cargo:98 in mosjs-sys I found the line

> $(message You must either have the Native Win32 python installed in C:/python27, or set NATIVE_WIN32_PYTHON to point to the appropriate python.exe.)
which is unfortunately never shown when building, because it ends up in stdout instead of stderr, so it won't be forwarded by cargo.

> Setting NATIVE_WIN32_PYTHON then actually fixed the issue :smiley:
Now I'm also at the point where running servo shows an empty white window with the correct title, but nothing else. I'm running Windows 10 Home.

@Boddlnagg I did the same thing but its still failling for me  :sob: :sob:
Looks like its hardcoded to c:\python27 which will fail for some, as its an uppercase P on installation (or at least for me it was)

**Comment by Boddlnagg** [comment]
@Jayflux Did you set it to the path containing `python.exe` or actually to point to `python.exe` itself? It must be the latter.

**Comment by Jayflux** [comment]
@Boddlnagg  i pointed directly to the python.exe itself and i still get the same error
Ok didn't know about the case insensitivity, good to know

**Comment by Jayflux** [comment]
I'm going to try doing this again, uninstalling the Visual C++ build tools and instead using the Visual Studio full install, to see if that has anything to do with it

**Comment by Jayflux** [comment]
Turns out the issue was me using http://landinghub.visualstudio.com/visual-cpp-build-tools instead of installing Visual Studio
