### ISSUE TITLE
Freeze when scrolling on Hacker News

### ISSUE THREAD

**Issue by telotortium** [servo/servo#13207]
I downloaded the Linux Servo nightly today (Servo 0.0.1-5b0a199) and discovered a freeze when testing Hacker News. Specifically, I ran

```
./servo -w -b --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref shell.builtin-key-shortcuts.enabled=false ./build/browserhtml-5c846c4e388d17ec/out/index.html -t 1 -y 1
```

to get the test home page, went to Hacker News, and then navigated to https://news.ycombinator.com/item?id=12454634, which was on the front page at the time. I then scrolled up and down the page for a while, clicking and trying (and failing, by the way) to select text. After about a minute, Servo reliably freezes to the point where even clicking the close button on the window frame won't close Servo -- a CTRL-C is necessary.

I opened up GDB to get a stack trace at the point where the program is frozen and got the following:

```
(gdb) bt
#0  0x00007ffff615a8ad in recvmsg () at ../sysdeps/unix/syscall-template.S:81
#1  0x000055555720376e in ipc_channel::platform::os::recv::h75e0ed8058ae5a0b ()
#2  0x000055555720026d in ipc_channel::platform::os::OsIpcReceiver::recv::h2caa24c58466d017 ()
#3  0x00005555571eeada in webrender_traits::api::RenderApi::get_scroll_layer_state::h78d23aea56881ce2 ()
#4  0x000055555586136b in _$LT$compositing..compositor..IOCompositor$LT$Window$GT$$GT$::send_webrender_viewport_rects::hc6c671c94fa2a618 ()
#5  0x000055555585120d in _$LT$compositing..compositor..IOCompositor$LT$Window$GT$$GT$::handle_events::h6225eb67728054da ()
#6  0x000055555586daa6 in servo::main::hfe34ed8cad3380a8 ()
#7  0x000055555723c977 in __rust_maybe_catch_panic ()
#8  0x0000555557233812 in std::rt::lang_start::haaae1186de9de8cb ()
#9  0x00007ffff5b91f45 in __libc_start_main (main=0x55555586fe80 <main>, argc=14, 
    argv=0x7fffffffc848, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffc838) at libc-start.c:287
#10 0x000055555582d94a in _start ()
```

I've also attached the result of `RUST_LOG="debug` passed through `ts`.

[servo.txt](https://github.com/servo/servo/files/462551/servo.txt)

**Comment by nox** [comment]
This doesn't freeze anymore.
