### ISSUE TITLE
Missing support for ms932, koi8-ru encoding labels

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13232]
Blocks #5601.
- Spec: https://encoding.spec.whatwg.org/#names-and-labels.
- Test: `/encoding/textdecoder-labels.html`.

This was fixed in https://github.com/lifthrasiir/rust-encoding/commit/40717f559ee43466ed98f3cf700e194333743b45 for v0.3 (which is unfinished). Not sure if it's worth fixing in the 0.2 branch or if we should just wait for 0.3 to be finished.

CC @SimonSapin @lifthrasiir

**Comment by nox** [comment]
@SimonSapin Are we supposed to switch to `encoding_rs`?

**Comment by SimonSapin** [comment]
I want to do that eventually, yes. I just hasn’t been pressing so far.

**Comment by dralley** [comment]
Since it's 4 years later and the ```encoding_rs``` switched happened quite a while ago, can this be closed?

**Comment by jdm** [comment]
We now pass /encoding/textdecoder-labels.html.
