### ISSUE TITLE
Bugs in the iso-2022-jp decoder?

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13239]
Blocks #5601.

Test: `/encoding/iso-2022-jp-decoder.html`.

I can't assess the correctness of the test, but it seems likely the underlying bug, if any, is in rust-encoding,

CC @SimonSapin @lifthrasiir

**Comment by lifthrasiir** [comment]
I believe this hit [WHATWG rewrite](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27256) (Encoding is not yet very up to date in that regard). Specifically `1B 24` (a lone escape sequence) should be an error in the rewritten algorithm but Encoding happily passes that.

**Comment by nox** [comment]
Is it the test or the spec or the code that should change?

**Comment by SimonSapin** [comment]
Fixed in #19073.
