### ISSUE TITLE
Implement parsing for mask shorthand

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13235]
I implemented all of the mask longhands in https://github.com/servo/servo/pull/13213. This means that we can parse things like `mask-image: url(foo)` or `mask-repeat: no-repeat`.

However, I deliberately left out the `mask` shorthand; so `mask: url(foo) no-repeat` doesn't work yet.

To make this work, we need to create a file `shorthands/mask.mako.rs` similar to https://github.com/servo/servo/blob/master/components/style/properties/shorthand/background.mako.rs

The mask and background shorthands are quite similar. They both encompass a set of array properties, of which there is a size, a position, an image, and a repeat. There are additional properties for both.

An important difference is that the mask shorthand doesn't have a concept akin to `background-color`. Whereas `mask` is a simple comma-separated list where each element is a bunch of longhands (where all mask longhands are allowed), `background` is a list of its component longhands where only the last element in the list is allowed to have a color. This should simiplify parsing a bit.

Spec: https://drafts.fxtf.org/css-masking-1/#the-mask

Grammar for single array element: `<mask-layer> = <mask-image> <mask-mode>? || <mask-position> [ / <mask-size> ]? ||<mask-repeat> || <mask-origin> || <mask-clip> || <mask-composite>`

The spec has more detailed steps on how to parse it, for example mask-origin with no defined mask-clip sets both.

You should be able to copy the background shorthand fine and start work from there, though.

This will need to be built with `./mach build-geckolib`, since mask is disabled for non-geckolib. I'll handle testing it on stylo. You can temporarily make the mask longhands not use `products="gecko"` to write unit tests.

**Comment by Manishearth** [comment]
cc @canaltinova 

when you're done with the transform one.

If someone else is interested in picking this up, please ask beforehand.

**Comment by 6112** [comment]
I'd like to pick this up. Also, how can I add tests for this?

**Comment by Manishearth** [comment]
This is a bit involved and may require prior parser experience -- have you contributed to servo before? If not, you might want to go for an easier issue first (https://github.com/servo/servo/issues?q=is%3Aissue+is%3Aopen+label%3AE-easy)

Also @canaltinova is finished with the transform stuff, so I think they'll be working on this next -- I'd opened this bug for them to work on 😄

If they plan to do something else, this is free to be taken.

**Comment by Manishearth** [comment]
Looks like @canaltinova is already working on this.

**Comment by Manishearth** [comment]
@canaltinova regarding your question in IRC, this happens because `mask-position` and `mask-size` are reexports of `background-*`.

https://github.com/servo/servo/compare/master...Manishearth:mask-fixes fixes it up so that you can import them as `mask_size::single_value::...`, etc, which will probably be useful for keeping the codegen simple. Feel free to roll in that patch.

(Otherwise, you can just import what you need from `background_size` and `background_position`, but that complicates the codegen)

**Comment by canaltinova** [comment]
Thanks for the help! It solved single_value problem. But although `SpecifiedValue` is defined in both property, I was still get this error for both: 
```
error: unresolved name `mask_size::SpecifiedValue`
let mut mask_size = mask_size::SpecifiedValue(Vec::new());
```
So I changed `pub type SpecifiedValue = background_size::SpecifiedValue;` to 
`﻿pub use ::properties::longhands::background_size::SpecifiedValue;`
And it worked. But I have no idea why the first one didn't work 😃

**Comment by Manishearth** [comment]
Oh, that's because typedefs don't import the constructor. `SpecifiedValue(...)` is basically a struct constructor, which is imported in function space (and you get both with a pub use), but with a typedef you don't get the constructor. It's silly but I'm not sure if it can be fixed.

**Comment by canaltinova** [comment]
Oh, now I get it. Thanks! I think it should be solved but I don't know, maybe intended?

**Comment by Manishearth** [comment]
Yeah, I'll ask around. The whole "value space type space" stuff has always annoyed me.
