### ISSUE TITLE
Implement AddEventListenerOptions: once

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13242]
Blocks #2185.
- Spec: https://dom.spec.whatwg.org/#dom-addeventlisteneroptions-once.
- Code: `components/script/dom/eventdispatcher.rs`, `components/script/dom/webidls/EventTarget.webidl`.
- Test: `/dom/events/AddEventListenerOptions-once.html`.

Depends on #11612.

**Comment by jdm** [comment]
@ofekd Does this look interesting?

**Comment by KiChjang** [comment]
@jdm Is this not blocked on #11612?

**Comment by jdm** [comment]
Whoops, I missed that. Sorry!

**Comment by nox** [comment]
Cc @deg4uss3r

**Comment by deg4uss3r** [comment]
@nox Will try! I'll start famalizing myself with the probelm and the code bases 
listed. Should have an update or many questions this weekend.
