### ISSUE TITLE
Decode UTF-8 with replacement in DedicatedWorkerGlobalScope::run_worker_scope.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13247]
Blocks #2968.

`String::from_utf8(bytes).unwrap()` will panic if the input is not well-formed UTF-8. We should use `String::from_utf8_lossy()` instead. (It should not be necessary to copy the string, though we may need to reorganize the code a little bit.)

* Spec: <https://html.spec.whatwg.org/multipage/#fetch-a-classic-worker-script>.
* Code: `components/script/dom/dedicatedworkerglobalscope.rs`.
* Test: `./mach test-wpt /workers/semantics/encodings/004.worker`.

**Comment by Jenselme** [comment]
I'll gladly have a look at this.

**Comment by jdm** [comment]
@Jenselme Please do! Ask questions if anything is unclear.

**Comment by Jenselme** [comment]
> It should not be necessary to copy the string

I think I have a working solution [here](https://github.com/Jenselme/servo/commit/44afd3030e220581f754a88b7de88fb14b7150ca) However, I rely on `Cow::into_owned` which according to [the documentation](https://doc.rust-lang.org/std/borrow/enum.Cow.html#method.into_owned) *Clones the data if it is not already owned.* From what I understand, the data is already owned so it won't copy. Am I correct or should I dig deeper not to rely on this?

**Comment by Ms2ger** [comment]
I'm thinking

```rust
let (metadata, bytes) = match load_whole_resource(...
    Ok(result) => result,
};
let url = metadata.final_url;
let source = String::from_utf8_lossy(&bytes);
```

**Comment by Jenselme** [comment]
@Ms2ger that was it. Thanks for you response. PR opened: #13306
