### ISSUE TITLE
Incorrect URLs after navigating in bhtml

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#13254]
<img width="1344" alt="screen shot 2016-09-12 at 9 45 50 pm" src="https://cloud.githubusercontent.com/assets/9086315/18459818/566c6b20-7932-11e6-9cb4-17d74323b309.png">
Steps to reproduce:
- Click on Github on the newtab page
- Click on the Business link at the top
- Click on the URL bar and the wrong URL is displayed.

**Comment by paulrouget** [comment]
I see `about:blank`.

/cc @Gozala

**Comment by cbrewster** [comment]
Can no longer reproduce this.
