### ISSUE TITLE
[Browser API] Implement iframe.capturePage()

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#13264]
Something like: Promise<Blob> capturePage(DOMRectInit source, DOMRectInit destination)

We can use a `WindowAndPng` compositor target.

**Comment by jdm** [comment]
@jmr0 Does this look interesting to you?

**Comment by jmr0** [comment]
@jdm Yep! Happy to hear more about it.

**Comment by jdm** [comment]
It's going to require:
* Adding an API to BrowserElement.webidl
* Communicating with the compositor to initiate a WindowAndPng composite
* Sending the image data to the iframe that initiated it (probably by including a pipeline in the original request, then sending the response via the constellation to the parent of that pipeline)
* Possibly creating an ImageData value with the result, or something

**Comment by jmr0** [comment]
Had a million things vying for my attention but I'm finally getting this started. @paulrouget what would source and destination correspond to in this case?

**Comment by paulrouget** [comment]
@jmr0 source is a rect (origin + size), the region that needs to be captured in the age. Dest is a size (in the first comment, I say it's a rect, which doesn't really make sense). If dest is different than source's size, the bitmap will be stretched. Similar to: https://developer.mozilla.org/en/docs/Web/API/CanvasRenderingContext2D/drawImage

Maybe you can use DOMRect: https://github.com/servo/servo/blob/master/components/script/dom/webidls/DOMRect.webidl

If stretching is difficult, we can ignore the dest argument for now.

**Comment by jmr0** [comment]
Let me know if what I have in mind so far makes sense:

* CapturePage of frame element issues message for compositing, and stores a handle to a promise that's returned to the client unresolved
* Compositor sends image data (through constellation message to parent pipeline)
* Function in frame element receives image data, turns into ImageData and resolves promise with it

One thing I'm unsure about is where to best perform cropping/stretching. I see the canvas paint thread has its own cropping function -- should similar logic live in the frame element?

**Comment by jdm** [comment]
Those steps sound sensible! Cropping and stretching logic should probably be in the frame element to avoid doing extra work in the compositor.

**Comment by nox** [comment]
@jmr0 Are you still looking into this?

**Comment by paulrouget** [comment]
We shipped the first alpha of browserhtml we are planning to move away from the Browser API. Closing.
