### ISSUE TITLE
Add a unit test verifying that SpecificFragmentInfo is at most one word in size

### ISSUE THREAD

**Issue by jdm** [servo/servo#13262]
It has a comment that reads `/// Keep this enum small. As in, no more than one word. Or pcwalton will yell at you.`. We should enforce this with a unit test that will prevent any mistakes from occurring.

**Comment by jdm** [comment]
We can add this to `tests/unit/layout/size_of.rs`.

**Comment by fflorent** [comment]
I'd like to take this one if you don't mind :).

Florent

**Comment by jdm** [comment]
Please do!
