### ISSUE TITLE
Implement XHR progress event changes

### ISSUE THREAD

**Issue by jdm** [servo/servo#13276]
https://github.com/whatwg/xhr/pull/90

**Comment by jdm** [comment]
Also https://github.com/w3c/web-platform-tests/issues/3729 .

**Comment by jdm** [comment]
@charlesvdv Would you be interested in this? The relevant code is in `components/script/dom/xmlhttprequest.rs`, and the `web-platform-tests` issue shows tests that should pass after updating the implementation.

**Comment by charlesvdv** [comment]
@jdm I will try it! Thanks a lot!
