### ISSUE TITLE
Cargo crashes on build (Windows 10)

### ISSUE THREAD

**Issue by Jayflux** [servo/servo#13272]
Following instructions from:
https://github.com/servo/servo/issues/13206#issuecomment-245742164

And using a clean windows VM, the build starts, then when it gets to 'cargo ready', it crashes
The only difference is i use http://landinghub.visualstudio.com/visual-cpp-build-tools instead of the full Visual Studio download

![cargo crash](https://cloud.githubusercontent.com/assets/936006/18532531/88853a08-7ad4-11e6-8d2a-86761c2eb429.jpg)

```
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ Edge (win 10, virtualbox)
OS Name Microsoft Windows 10 Enterprise Evaluation
Version 10.0.14393 Build 14393
```

@larsbergstrom @vvuk

**Comment by Coder206** [comment]
@Jayflux I am going to fire up my VM and my local Win10 build to see if I can reproduce.

**Comment by Coder206** [comment]
@Jayflux I am getting a successful build on my native repository.

**Comment by Jayflux** [comment]
@Coder206 could you try downloading the same VM? and using http://landinghub.visualstudio.com/visual-cpp-build-tools ?

I've noticed everyone else seems to be on Windows 10 home, and I'm using Windows 10 Pro/Enterprise

**Comment by Coder206** [comment]
I was able to reproduce @Jayflux's error when I removed Visual Studio 2015 Community and replaced it with Visual C++ Build Tools on the default settings.

**Comment by Coder206** [comment]
Windows 10 Home with Visual C++ Default: 

`C:\Users\Patrick\Documents\mozilla\servo\servo>mach.bat build -d
   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#87c47526)
   Compiling servo v0.0.1 (file:///C:/Users/Patrick/Documents/mozilla/servo/servo/components/servo)
   Compiling rand v0.3.14
   Compiling num_cpus v0.2.13
   Compiling freetype v0.1.0 (https://github.com/servo/rust-freetype#d564ff90)
   Compiling memchr v0.1.11
   Compiling miniz-sys v0.1.7
   Compiling backtrace-sys v0.1.4
   Compiling tinyfiledialogs v0.1.0 (https://github.com/jdm/tinyfiledialogs#41d4268b)
   Compiling aho-corasick v0.5.3
   Compiling shared_library v0.1.5
   Compiling cmake v0.1.17
   Compiling bincode v0.6.0
   Compiling ogg_metadata v0.3.0
   Compiling openssl-sys-extras v0.7.14
   Compiling immeta v0.3.4
   Compiling openssl v0.7.14
   Compiling audio-video-metadata v0.1.2
   Compiling script v0.0.1 (file:///C:/Users/Patrick/Documents/mozilla/servo/servo/components/script)
   Compiling servo-freetype-sys v4.0.2
   Compiling fontsan v0.3.2 (https://github.com/servo/fontsan#08bfa604)
   Compiling heartbeats-simple-sys v0.3.1
   Compiling azure v0.8.0 (https://github.com/servo/rust-azure#9fb666b2)
   Compiling num-bigint v0.1.35
   Compiling js v0.1.3 (https://github.com/servo/rust-mozjs#4d4466f6)
   Compiling deque v0.3.1
   Compiling expat-sys v2.1.4
   Compiling rayon v0.4.0
   Compiling harfbuzz-sys v0.1.6
   Compiling servo-skia v0.20130412.23
   Compiling angle v0.1.1 (https://github.com/servo/angle?branch=servo#832ffd74)
   Compiling jpeg-decoder v0.1.6
   Compiling num-rational v0.1.35
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#87c47526)`
process didn't exit successfully: `C:\Users\Patrick\Documents\mozilla\servo\servo\target\debug\build\mozjs_sys-661d4efe7c7ca939\build-script-build` (exit code: 101)
--- stdout
[[ /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure -ot /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure.in ]] && touch /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure || true
[[ /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure -ot /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure.in ]] && touch /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure || true
! [[ /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure.in -ot /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure ]] && touch /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure || true
! [[ /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure.in -ot /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure ]] && touch /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure || true
if [[ /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure -nt C:\Users\Patrick\Documents\mozilla\servo\servo\target\debug\build\mozjs_sys-661d4efe7c7ca939\out/config.status ]] ; then \
  cd C:\Users\Patrick\Documents\mozilla\servo\servo\target\debug\build\mozjs_sys-661d4efe7c7ca939\out && \
  PYTHON="python" MOZ_TOOLS="" \
  CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
  /c/Users/Patrick/Documents/mozilla/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --without-intl-api --build-backends=RecursiveMake --disable-shared-js || (cat config.log && exit 1) ; \
fi
makefile.cargo:120: recipe for target 'maybe-configure' failed

--- stderr
C:/Users/Patrick/AppData/Local/Temp/make2224-5.sh: line 2: cd: C:UsersPatrickDocumentsmozillaservoservotargetdebugbuildmozjs_sys-661d4efe7c7ca939out: No such file or directory
cat: config.log: No such file or directory
mozmake: *** [maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', C:\Users\Patrick\Documents\mozilla\servo\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\master\build.rs:43
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build FAILED in 0:02:18`

**Comment by Jayflux** [comment]
@vvuk @larsbergstrom

**Comment by vvuk** [comment]
Is this a 32-bit or a 64-bit VM?

**Comment by Jayflux** [comment]
@vvuk 64-bit VM

**Comment by jonathandturner** [comment]
Does this still repro?

**Comment by nox** [comment]
Let's say it doesn't.
