### ISSUE TITLE
Support cloning steps for textarea/input

### ISSUE THREAD

**Issue by jdm** [servo/servo#13282]
https://github.com/whatwg/html/pull/1784

**Comment by nox** [comment]
This can probably be made into an E-Easy issue given we already have the infrastructure for cloning steps.

**Comment by tigercosmos** [comment]
just leave a note:

https://html.spec.whatwg.org/multipage/form-elements.html

> The cloning steps for textarea elements must propagate the raw value and dirty value flag from the node being cloned to the copy.
