### ISSUE TITLE
Use the CII Best Practices badge

### ISSUE THREAD

**Issue by mylainos** [servo/servo#13285]
The **Core Infrastructure Initiative (CII) Best Practices badge** is a way for Free/Libre and Open Source Software (FLOSS) projects to show that they follow best practices. Projects can voluntarily self-certify, at no cost, by using this [web application](https://bestpractices.coreinfrastructure.org/) to explain how they follow each best practice.

 These best practices have been created to:
1. encourage projects to follow best practices,
2. help new projects discover what those practices are, and
3. help users know which projects are following best practices (so users can prefer such projects).

What do you think of using this Linux Foundation Collaborative Project for servo ?

Furthermore if we help the servo's dependencies to have it too, it will help the Rust community and improve the global security of servo.

**Comment by nox** [comment]
I don't think this is much useful, and it looks weird to me to self-award ourselves with an arbitrary badge. Closing.
