### ISSUE TITLE
overflow:auto changes z order

### ISSUE THREAD

**Issue by mstange** [servo/servo#13298]
If you have a position:absolute element without a z-index, that element should be on top of a non-positioned scrollable element.

This testcase should be green, not red: http://jsbin.com/zofidasibu/1

``` html
<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<title>The position:absolute element should be on top of the overflow:auto element</title>

<style>

body {
  margin: 0;
}

.scrollbox {
  margin: 50px;
  width: 200px;
  height: 200px;
  overflow: auto;
  background: red;
}

.overlay {
  position: absolute;
  left: 50px;
  top: 50px;
  width: 200px;
  height: 200px;
  background: lime;
}

</style>

<div class="overlay"></div>

<div class="scrollbox"></div>
```

cc @pcwalton

**Comment by glennw** [comment]
@pcwalton @mrobinson I guess this is due to the way servo creates stacking contexts for overflow regions? We should fix this properly, in terms of WR API and servo display list generation.

**Comment by mrobinson** [comment]
Yep, the issue here is that overflow:scroll should not create a stacking context. Instead, it should just create a scrolling layer. This issue is on my long-term todo list.

**Comment by glennw** [comment]
@mrobinson Do you have a sense of how much work is involved to fix this behaviour? Do you think we could bump up the priority on this? I'd like to get it resolved soon, since it is going to affect the public webrender APIs.

**Comment by glennw** [comment]
@mrobinson is working on this now :)
