### ISSUE TITLE
Overscrolling and 'bouncing' the page with arrow keys causes rendering glitch.

### ISSUE THREAD

**Issue by samuknet** [servo/servo#13291]
When scrolling beyond the top or bottom of a page with the up/down arrow keys, holding down the arrow key causes a graphical glitch to occur when the page does the bounce effect.

To replicate, just load a page with a scroll like [this one](https://samuknet.github.io/test_cases/anchorInPage/index.html) and hold down the up arrow key to scroll beyond the top edge of the page.

![scrollarrowkeys](https://cloud.githubusercontent.com/assets/9294710/18589281/e58e39fe-7c21-11e6-8938-ca2ced37f4eb.gif)

**Comment by nox** [comment]
I can't reproduce this.
