### ISSUE TITLE
Null iframe in XOW test

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#13301]
CC @asajeffrey (and I forgot who else to cc...)

Test is in https://github.com/avadacatavra/servo/tree/xow-spec/tests/wpt/web-platform-tests/origin

ERROR:script::dom::bindings::error: Error at http://web-platform.test:8000/origin/cross-origin-objects.sub.html:12:1 B is null

<img width="1015" alt="screenshot 2016-09-06 19 42 44" src="https://cloud.githubusercontent.com/assets/11877868/18597950/47a9b9d2-7c05-11e6-87dc-557f642522f0.png">

**Comment by ConnorGBrewster** [comment]
cc @ConnorGBrewster

**Comment by jdm** [comment]
This is caused by #3924, and will be fixed by #8600.

**Comment by jdm** [comment]
It can be worked around by waiting for the load event for the iframes in question.

**Comment by ConnorGBrewster** [comment]
Fixed by #13996?

**Comment by jdm** [comment]
Yep.
