### ISSUE TITLE
Support TrueType font files that contain multiple fonts

### ISSUE THREAD

**Issue by matprec** [servo/servo#13317]
Hello,

i'd like to know how servo handles truetype font files with multiple fonts, since webrender always (hardcoded) chooses [the first font](https://github.com/servo/webrender/blob/master/webrender/src/platform/linux/font.rs#L62) in the font data given to it.
Is it some kind of preprocessing where the font data is manually split up?

Thanks in advance!

**Comment by jdm** [comment]
@glennw Do you know the answer? Do we just do the wrong thing?

**Comment by glennw** [comment]
My guess is we just do the wrong thing and other fonts are not supported yet - @pcwalton ?

**Comment by pcwalton** [comment]
I doubt we do the right thing here.

**Comment by MSleepyPanda** [comment]
I could create a patch for WR, but i'm not _that_ familiar with the servo/gfx code to update the font handling.
Actually i'd like to contribute, but it would take some time.

**Comment by mrobinson** [comment]
cc @mukilan This will be fixed by our changes. :D
