### ISSUE TITLE
Implement minlength attribute for text inputs

### ISSUE THREAD

**Issue by jdm** [servo/servo#13313]
Spec: https://html.spec.whatwg.org/multipage/forms.html#attr-fe-minlength

This applies to both `HTMLInputElement` and `HTMLTextAreaElement`.

Code: `components/script/dom/htmltextareaelement.rs`, `components/script/dom/htmlinputelement.rs`, `components/script/dom/webidls/HTMLTextAreaElement.webidl`, `components/script/dom/webidls/HTMLInputElement.webidl`
Tests: we'll need to [write](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) a new one in `tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/` (use `maxlength.html` as an example). Also, unit tests in `tests/unit/script/textinput.rs` would be valuable (`./mach test-unit -p script`).

See #7323 for the PR that implemented maxlength.

**Comment by Phrohdoh** [comment]
I'm going to give this a shot!

**Comment by KiChjang** [comment]
Great!

**Comment by jdm** [comment]
Related: https://github.com/whatwg/html/issues/1796
