### ISSUE TITLE
JS engine crash while implementing IndexedSetter.

### ISSUE THREAD

**Issue by splav** [servo/servo#13327]
I'm working on https://github.com/servo/servo/issues/13129
The WIP branch is https://github.com/splav/servo/tree/HTMLOptionsCollection%2313129
How to reproduce: 
`./mach test-wpt tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/common-HTMLOptionsCollection.html`

Crash log with debug info:

[crash_debug.txt](https://github.com/servo/servo/files/481164/crash_debug.txt)

**Comment by splav** [comment]
There are two lines doing almost the same thing with comments in the failing test - first leads to crash, second works fine.

**Comment by jdm** [comment]
Somehow we have an ObjectOpResult that gets used that hasn't been initialized. However, https://github.com/splav/servo/commit/264d027b40a6c35dbdc23172235592221031209a#diff-60d01595cff328c165842fea9e4ccbc2R4856 calls the `failNoNamedSetter` method, which is [supposed to initialize it](https://dxr.mozilla.org/mozilla-central/rev/f0f15b7c6aa77a0c5750918aa0a1cb3dc82185bc/js/public/Class.h#164), so there's something mysterious going on.

**Comment by splav** [comment]
The thing is that the diff part is for NamedSetter. And the error is in
IndexedSetter. I'm not at computer now, and can't check, but it could be an
error in IndexedSetter binding generator part, that I havn't changed.

20 сент. 2016 г. 12:41 AM пользователь "Josh Matthews" <
notifications@github.com> написал:
