### ISSUE TITLE
Servo does not build with Visual C++ Build Tools

### ISSUE THREAD

**Issue by Jayflux** [servo/servo#13325]
**Description**
Microsoft have released Visual C++ as stand alone, so you don't need to install the whole of Visual Studio if you need just the C Compiler.
It would be good if we can have servo build on this for the MVSC builds, however they seem to fail.
It does build fine after installing Visual Studio (with the Visual C++ option), but not when you swap it out for visual-cpp-build-tools

**What is the failure?**
On my host machine i get this
https://pastebin.mozilla.org/8909561

inside a VM I get this:
https://github.com/servo/servo/issues/13272

**Steps to reproduce**
Install Servo following the instructions from:
https://github.com/servo/servo/issues/13206#issuecomment-245742164

But instead of installing Visual Studio, install http://landinghub.visualstudio.com/visual-cpp-build-tools

**Expected Result**
Servo should build normal

**Actual Result**
Servo fails in one of the 2 ways mentioned above

@larsbergstrom @vvuk @AndrewPardoe

**Comment by vvuk** [comment]
The host machine failure is weird -- it's basically because the directory path is being printed with backslashes, which are then not quoted.  But that shouldn't be happening.. that's coming from a "pwd -W", which should print as c:/foo/bar.  In this case though it's showing up as c:\\foo\\bar.

**Comment by Jayflux** [comment]
@vvuk do you know how http://landinghub.visualstudio.com/visual-cpp-build-tools would have any affect on that? I've narrowed it down to that but not sure what's in it that would affect the backslashes problem

**Comment by vvuk** [comment]
I take that back -- the issue isn't from pwd.   In the mozjs makefile.cargo, there's a few places where it attempts to move OUT_DIR into a /-delimited path.  One of these either isn't being hit, or isn't running properly.

Note that you can just clone mozjs-sys and try a cargo build in there from a VS command prompt, after making sure the mozilla-build tools are in the PATH.  You can poke at the OUT_DIR bits and see what's being generated incorrectly.

**Comment by AndrewPardoe** [comment]
Let me find someone to investigate. This week is kind of busy at CppCon so my search may have noticeable latency.

**Comment by Jayflux** [comment]
> So it turns out that you can’t until Preview 5 of VS “15” gets released. So step one is wait a couple weeks J Step two is to just install the build tools in the VS “15” installer.

> One thing you can do from your side is to check which dependent dll is missing.
You can use dependency walker tool to figure it out.
