### ISSUE TITLE
Return the error codes instead of implicitly returning None

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#13344]
Some of the methods in `testing_commands.py` have a returning pattern like,

``` python
result = call(...)
if result != 0:
    return result
```

Instead of doing that check and implicitly returning `None`, we could just return the result, since `0` and `None` have the same boolean evaluation in python.

Code: `python/servo/testing_commands.py`

**Comment by bubbles231** [comment]
I would like to take this issue.

**Comment by Wafflespeanut** [comment]
Great!

**Comment by uber1geek** [comment]
I wanted to work on this issue as well :)

**Comment by Wafflespeanut** [comment]
Sorry, @bubbles231 claimed this first. Feel free to poke other unclaimed easy issues, or comment here (or ping us at the `#servo` channel in the IRC) if you want help :)

**Comment by bubbles231** [comment]
So maybe I am confused here but 0 != None.

**Comment by bubbles231** [comment]
Sorry if you fell that I am not smart enough to contribute. I won't touch the code again.

**Comment by Wafflespeanut** [comment]
I meant that they both have similar boolean evaluation (i.e) how the `__nonzero__` magic method is implemented. In other words,

``` python
if None: print 'Hello'
# doesn't print anything
if 0: print 'Hello'
# doesn't print anything
```

Hence, there's no great reason to prefer `None` instead of `0` :)

**Comment by bubbles231** [comment]
un assign me please

**Comment by uber1geek** [comment]
I am still interested in taking up this issue :)

**Comment by Wafflespeanut** [comment]
@bubbles231 Thanks for letting us know!

@uber1geek It's yours then! :)

**Comment by uber1geek** [comment]
@Wafflespeanut Return result seems good, I was thinking if we just make it an empty value. it will evaluate to false and that solves the issue imo.

**Comment by KiChjang** [comment]
I'm not sure what you're trying to get at here. This is what I think is being proposed:
```python
return call(..)
```

**Comment by Wafflespeanut** [comment]
@uber1geek Any updates on this?

**Comment by nivekuil** [comment]
I'd like to claim this. Added a PR.
