### ISSUE TITLE
servo/angle binding repo should go the same way with SpiderMonkey

### ISSUE THREAD

**Issue by saneyuki** [servo/servo#13352]
https://github.com/servo/angle is still in chaos, and to follow an upstream is a bit hard way.

SpiderMonkey is managed in 2 repository, https://github.com/servo/mozjs and https://github.com/servo/rust-mozjs to upgrade continuously. So we should follow its way.

**Comment by saneyuki** [comment]
I created a new repository to re-organize the binding for angle: https://github.com/saneyuki/rust-angle

**Comment by saneyuki** [comment]
> I created a new repository to re-organize the binding for angle: https://github.com/saneyuki/rust-angle

- Motivation
  1. servo/angle 's commit history is chaos, and it mixes upstream patches and our patches. it was hard to find our base revision of google's upstream.
  2. To do the same style with rust-mozjs/mozjs, I cherry-picked patches from servo/angle by hand.
- The current status of this repository is:
  - re-apply patches to make it same degree with https://github.com/servo/angle/commit/832ffd74ac892682dfcaea27dc518130a72e280c from [the difference](https://github.com/servo/angle/compare/master...servo:servo)

**Comment by nox** [comment]
@saneyuki How far are we on this?

**Comment by atouchet** [comment]
@SimonSapin does the mozangle crate address this at all?

**Comment by SimonSapin** [comment]
I’d say it does, yes.

* https://github.com/servo/mozangle/blob/master/gfx/angle/checkout/out/gen/angle/id/commit.h identifies a commit in https://github.com/mozilla/angle
* https://github.com/servo/mozangle#updating-angle has instruction on how to update from mozilla-central
* https://github.com/servo/mozangle/blob/master/gfx/angle/update-angle.py has instructions on how to update from upstream (intended for mozilla-central, but should also work if we need to pick up some other patch without waiting).
