### ISSUE TITLE
Report tidy error for space after (

### ISSUE THREAD

**Issue by jdm** [servo/servo#13350]
We want to automatically report code like `some_function( argument)` as a style guide violation. This can be added to our list of regexes (`regex_rules`) that we perform on every Rust source file.

Code: `python/tidy/servo_tidy/tidy.py`
Test: modify `python/tidy/servo_tidy_tests/rust_tidy.rs` to add the error, and update `test_rust` in `python/tidy/servo_tidy_tests/test_tidy.py`. Run the test with `./mach test-tidy --self-test`.

**Comment by Mylainos** [comment]
I would like to work on this one !

**Comment by jdm** [comment]
Please do!
