### ISSUE TITLE
If mozbrowser, give a chance to the top level pipeline to interrupt key events

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#13353]
Key events are sent straight to the focused pipeline. Which makes sense.

But in the case of browserhtml, we want to be able to catch the event before it goes to the focused pipeline, and maybe cancel its propagation, and once the key event is consumed by the focused pipeline, we also want it to bubble back to the top level pipeline and check the value of event.preventDefault.

For example, if the user press Cmd-R, we want this event to be consumed by the focused pipeline, and if `preventDefault` is false, then we would reload the tab.

Another example is `Cmd-W`, we maybe don't want this to go through the focused pipeline (to prevent the content to cancel tab closing).

**Comment by jdm** [comment]
I guess this is about duplicating the logic that exists for the compositor, which gets all of the non-prevented key events after the focused pipeline has finished with them.

**Comment by paulrouget** [comment]
I'd like to work on that.

**Comment by jdm** [comment]
Great!

**Comment by paulrouget** [comment]
Let's call mozbrowser's pipeline script thread P1, and focused nested iframe pipeline script thread P2.

Constellation can get a KeyEvent message from both the compositor and the script thread, and the event comes with a response channel.

The path of the key event in this case would be:

- ports' window,
- compositor
- constellation
- P1
  - DOM event capture phase, reaching the iframe node
  - DOM event is *not* sent down the iframe
  - in HTMLiframe::handle_event, DOM event is translated into a KeyEvent
  - send KeyEvent back to constellation
  - constellation send to P2, creating a new DOM event
  - preventDefault value of P2's DOM event is sent back to constellation via a response channel
  - constellation let P1 know about the preventDefault value
  - finish event propagation in mozbrowser pipeline, copying P2's preventDefault value to P1's event (up to browserhtml to reset preventDefault to false if needed)
- constellation get back the preventDefault value, send it back to response channel
- compositor get back the preventDefault, via response channel, send back to ports' window according

Hope it makes sense :)

**Comment by paulrouget** [comment]
@jdm does it sound like the right approach? I'm not 100% sure it's necessary to use a response channel. I imagine it's also possible to just use another message.

**Comment by jdm** [comment]
If key focus is inside P2, P1 will never see the key event in the current code because it is sent directly to P2. Is the idea that the constellation would check whether the focused pipeline has a mozbrowser ancestor and send the key event to P1 instead?

**Comment by paulrouget** [comment]
>  Is the idea that the constellation would check whether the focused pipeline has a mozbrowser ancestor and send the key event to P1 instead?

The constellation would check if the root pipeline is a mozbrowser pipeline (we don't want to handle the case where there's a non-root mozbrowser pipeline, it's not supported, and I don't believe it will ever be).

If it is a mozbrowser pipeline, it sends the event to the mozbrowser pipeline.

Then to the focused pipeline.

2 things to note:

1. if in the mozbrowser pipeline, `event.stopPropagation()` is called in the capture phase, the event is not send to the focused pipeline
2. if in the focused pipeline `preventDefault` is set to true, the event in the mozbrowser pipeline will also be set to true.

> Keep in mind that events do not bubble out of an iframe and into the containing page.

Yes. I'm not planning to change that. The event will stay in 2 documents, and won't propagate anywhere else.

**Comment by jdm** [comment]
Ok, that scheme sounds workable. In the current code, if the event is canceled by the focused pipeline then the script thread just doesn't tell the compositor about the event at all; we may need to change that.

**Comment by paulrouget** [comment]
The problem with this approach is that the top pipeline script thread is blocked until the focused pipeline consumes the event. See what gecko does here: https://github.com/browserhtml/browserhtml/issues/317#issuecomment-94056689

I'm not very happy about that… maybe we should not use DOM events for this.

**Comment by paulrouget** [comment]
Putting that on hold for now. We are working on a better Browser API that would solve this.

**Comment by paulrouget** [comment]
We shipped the first alpha of browserhtml we are planning to move away from the Browser API. Closing.
