### ISSUE TITLE
Fail gracefully when no fonts are found

### ISSUE THREAD

**Issue by aochagavia** [servo/servo#13369]
As noted by @larsbergstrom on https://github.com/servo/servo/issues/13257#issuecomment-248780914, Servo displays a white screen on Windows (when built with MSVC) because it can't find any fonts (see https://github.com/servo/servo/issues/13257 for context).

IMO failing to load fonts should trigger some kind of error instead of displaying an uninformative blank screen. Some alternatives come to mind:

1. Show a message box telling that no fonts could be found and close the browser afterwards.
2. Attempt to download and use a web font from a hard-coded url.

I would like to tackle this, but first I would like to have some feedback. The first option seems attractive to me because being unable to find the fonts should never happen (although I don't have enough experience to back this claim).

**Comment by retep998** [comment]
If no fonts are found on a Windows system, then you're in deeply screwed territory, so I'm in favor of the first option.

**Comment by aochagavia** [comment]
I discovered that the font loading issue was actually caused by https://github.com/servo/servo/issues/13371 (font-related functionality is not implemented for Windows + MSVC). At this point I feel more inclined to just close this issue and do nothing, since I cannot think of any real-world scenario where fonts are unavailable (feel free to reopen, though, in case there is one).

**Comment by larsbergstrom** [comment]
I agree with @retep998, but I think the problem here is more that the code is not yet implemented than that we are failing to load them. I believe that we're failing to even attempt it in this path! :-) So I think we should revisit this once we have a real font loading story in place on MSVC.
