### ISSUE TITLE
Check whether the document has scripting enabled when compiling event handlers

### ISSUE THREAD

**Issue by jdm** [servo/servo#13363]
There's a TODO about checking whether scripting is enabled. We can now do that using `document.is_scripting_enabled()`, so we should.

Code: `components/script/dom/eventtarget.rs` (`get_compiled_event_handler`)

I haven't thought of a way to test this, so no need to spend time figuring that out.

**Comment by jdm** [comment]
Oh, and the full text of 1.2 is `If document does not have a browsing context, or if scripting is disabled for document's browsing context, then return null.`, so we can check the presence of a browsing context via a method on Document as well.

**Comment by Phrohdoh** [comment]
I'll take this on if someone else hasn't claimed it already.

**Comment by KiChjang** [comment]
It's yours!

**Comment by KiChjang** [comment]
Relevant spec: https://html.spec.whatwg.org/multipage/webappapis.html#getting-the-current-value-of-the-event-handler

**Comment by jdm** [comment]
There was an attempt to fix this in #13365, but it got stuck after we came up a way to test the changes: https://github.com/servo/servo/pull/13365#issuecomment-248823338

**Comment by TooManyBees** [comment]
I'd like to pick this up.

**Comment by KiChjang** [comment]
Sure thing!
