### ISSUE TITLE
windows nightly build cant type password correctly

### ISSUE THREAD

**Issue by tyoc213** [servo/servo#13366]
Hi there, I have downloaded nightly build maybe 1 or at most 2 days, when I enter to github and try to join with this user and password I have this behaviour
- If I type a uppercasse letter, I need to hit the key for a second time for a dot in the password to show
- Even that I carefully see that the count of dots of my password match, on submit I cant log in.

Yes my password uses uppercase, lower case and numbers and others.

**Comment by tyoc213** [comment]
Well in fact write in almost all text inputs cause some trouble... maybe a lag? or a double typing of the same word, also I some times write a s, then hit s again because I dont see it and I end up with 3 s like "sss" instead of 1 or 2 (which was the strokes I made).

Windows 10 home, core i7-4710HQ

**Comment by elahn** [comment]
This is describing #12937 however, in some cases you may also be hitting #14494.

**Comment by KiChjang** [comment]
FTR, this also used to happen in Linux, but was fixed on current nightly.

**Comment by ark-** [comment]
Also getting this problem in nightly windows build. Using Windows 7 x64.

It seems like there is a window where key presses are not accepted, if you type during this time then the key press is lost.

**Comment by atouchet** [comment]
Is this still an issue? I believe Windows text input should be working fine now.

**Comment by ark-** [comment]
I think it is fixed on my Windows 8.1 machine. Though tabbing between input fields does not work. Not sure if that should be a new issue?

**Comment by KiChjang** [comment]
@ark- Not a new issue - we don't have tabbing support. Work is tracked in #3982.

**Comment by atouchet** [comment]
Closing this as fixed.
