### ISSUE TITLE
Implement font rendering on Windows (MSVC)

### ISSUE THREAD

**Issue by aochagavia** [servo/servo#13371]
The dummy implementation in `components/gfx/platform/mod.rs` should be replaced by a real one:

``` rust
#[cfg(all(target_os = "windows", target_env = "msvc"))]
pub use platform::dummy::{font, font_context, font_list, font_template};
```

Currently, the lack of a proper implementation causes Servo to show a blank screen upon being launched (see https://github.com/servo/servo/issues/13257).

**Comment by aochagavia** [comment]
I wold like to help with this but have no idea where to begin. Would it be possible to use FreeType on (Windows, MSVC)? What are other browsers out there doing?

**Comment by retep998** [comment]
Other browsers, such as Firefox Chrome IE Edge are all using DirectWrite to render text. It is possible to use freetype, but it's not recommended.

**Comment by aochagavia** [comment]
After investigating a little bit, I think I don't have enough time to implement this in the short term. The main problem I see is that I would need to get familiar with font rendering in the first place, which seems to be a very complex topic.

For anyone trying to implement this, maybe the [directwrite](https://crates.io/crates/directwrite) crate can be a starting point.

**Comment by aochagavia** [comment]
Today I investigated a little bit more and implemented some functionality on top of the directwrite crate (you can check out the [diff](let (mut index, mut exists) = (0u32, 0);)). This seems to be the way to go. Take a look at the examples directory to see the new code in action.

So far, two big blockers are:

1. I have never used the Windows API before
1. I have never used COM objects before

This means that, though the current implementation seems to work, I am unsure about memory safety and absence of memory leaks. Feel free to take a look at it and point out any issues.

**Comment by Boddlnagg** [comment]
@aochagavia  The link you provided seems to be wrong ...

**Comment by aochagavia** [comment]
@Boddlnagg Thanks for the heads up! I just fixed the link.

**Comment by metajack** [comment]
You might be interested in this: https://gist.github.com/metajack/e75da24fa22d7bbbc6d454513161f8c5

I wrote this quite a while ago, but shows how to use COM from Rust (including implementing your own objects) and implements some of the functionality needed by webrender.

**Comment by lygstate** [comment]
Is this the sole blocker for msvc?

**Comment by llde** [comment]
What about using RustType for font rendering?
