### ISSUE TITLE
JS testers does not work on Servo Windows build

### ISSUE THREAD

**Issue by SaschaNaz** [servo/servo#13379]
[Kangax ES5 test](http://kangax.github.io/compat-table/es5/) does not load properly and [a simple JS detector](http://isjavascriptenabled.com/) does not work.

![image](https://cloud.githubusercontent.com/assets/3396686/18757873/ac314f3e-8130-11e6-9017-e8089ad37252.png)

![image](https://cloud.githubusercontent.com/assets/3396686/18757878/b1d6b65e-8130-11e6-9276-6eddf307432f.png)

**Comment by jdm** [comment]
http://isjavascriptenabled.com/ relies on document.write, which is tracked in #3704.

**Comment by jdm** [comment]
The Kangax site also relies on document.write.

**Comment by nox** [comment]
This seems to work now.
