### ISSUE TITLE
Media element network response processing code should invoke failure steps if there's no metadata

### ISSUE THREAD

**Issue by jdm** [servo/servo#13375]
#12671 made this change but wasn't finished, and a bunch of test results needed [updating](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations). It would be great to resurrect that work!

**Comment by gterzian** [comment]
I would like to give it a go

**Comment by jdm** [comment]
@gterzian Please do! Ask questions here if anything is unclear.

**Comment by jdm** [comment]
To run the media tests, use `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements`.

**Comment by gterzian** [comment]
@jdm ok, thanks! I'll ask away if there is anything...

**Comment by gterzian** [comment]
@jdm When you say that some tests need updating, do you have any particular test in mind? I checked `tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements` and couldn't find one that tested the meta data...

**Comment by gterzian** [comment]
@jdm unrelated to this particular issue, but, what would be the quickest way to get feedback on some code change? `./mach build --dev` takes pretty long on my machine :)

**Comment by jdm** [comment]
I am not aware of a quicker mechanism, unfortunately.
