### ISSUE TITLE
Extract panic-catching for JS engine callbacks into a separate function

### ISSUE THREAD

**Issue by jdm** [servo/servo#13377]
All of our generated code contains inline code like this:
```rust
let result = panic::catch_unwind(AssertUnwindSafe(|| {
    ...
};
match result {
    Ok(result) => result,
    Err(error) => {
        store_panic_result(error);
        return false;
    }
}
```
This comes from CodegenRust.py. We should extract this pattern into a useful function in `utils.rs` that accepts two argument, and has two generic types: the first argument is a type that implements the Fn trait, and the second argument is the generic return type for the function (either `()` or `false`). This will turn our generated code into something like `wrap_panic(|| { ... }, false)` instead.

Code: `components/script/dom/bindings/utils.rs`, `components/script/dom/bindings/codegen/CodegenRust.py`

**Comment by jdm** [comment]
To see the generated output, take a look at any source file in `target/debug/build/script-[hash]/out/Bindings`.

**Comment by Mylainos** [comment]
Do you mean `components/script/dom/bindings/utils.rs` and `components/script/dom/bindings/codegen/CodegenRust.py` ?

**Comment by jdm** [comment]
Exactly.

**Comment by Mylainos** [comment]
Can I try this one ?

**Comment by jdm** [comment]
Please do!

**Comment by Mylainos** [comment]
I have some problems with tidy, I will fix this and send a pull request tomorrow.
