### ISSUE TITLE
Review usage of UnsafeNode

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#13403]
`UnsafeNode` is essentially a 2-tuple of usize representing pointer addresses. It can be properly transmuted into a proper `LayoutJS<Node>`, which is wildly unsafe.

**Comment by metajack** [comment]
It shouldn't appear outside parallel.rs right? transmute is unsafe, and all of layout except parallel.rs is `deny(unsafe)` I thought.

**Comment by KiChjang** [comment]
Pinging @nox since he was the one to want a review of UnsafeNode.

**Comment by nox** [comment]
@jack My hands are full these days, but I think this should definitely be done ASAP.

**Comment by nox** [comment]
Cc @Ms2ger @jdm

**Comment by nox** [comment]
`UnsafeNode` is gone.
