### ISSUE TITLE
Replace instances of old ServiceWorker specification URL with new one

### ISSUE THREAD

**Issue by jdm** [servo/servo#13408]
The old specification URL is https://slightlyoff.github.io/ServiceWorker/spec/service_worker/ and there are various places in `components/script` that use it. We should rewrite all of these instances to use the new specification instead: https://w3c.github.io/ServiceWorker/ . We can also remove the specification exception in https://dxr.mozilla.org/servo/source/python/tidy/servo_tidy/tidy.py#72 . Since all links should exist in comments, all that's necessary is to run `./mach test-tidy` before submitting a PR.

**Comment by vigneshsarma** [comment]
I would like to give it a go.

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear :)

**Comment by vigneshsarma** [comment]
Before I submit the PR, 

1. Why is it that it is ok to remove the line https://dxr.mozilla.org/servo/source/python/tidy/servo_tidy/tidy.py#72? I don't really understand what's going on here.

2. I also found references to this url in `tests/wpt/web-platform-tests/service-workers/stub-*`, `tests/wpt/web-platform-tests/service-workers/cache-storage/` and some other files in `tests`. Should I update them also?

**Comment by jdm** [comment]
1. That's the list of URLs hostnames that point to known specifications, which tidy.py uses to validate that certain files and methods contain comments linking to a specification that they're implementing. Since no specification exists at slightlyoff.github.io/ServiceWorker/ any more, we don't want people accidentally adding links to it after this point.
2. Yes, that would be helpful! The whole web-platform-tests directory is a clone of https://github.com/w3c/web-platform-tests/, but any changes we make will automatically be duplicated upstream.
