### ISSUE TITLE
Make ServiceWorkerContainer::register return a Promise

### ISSUE THREAD

**Issue by jdm** [servo/servo#13409]
Specification: https://w3c.github.io/ServiceWorker/#service-worker-container and https://w3c.github.io/ServiceWorker/#service-worker-container-register-method
Code: `components/script/dom/webidls/ServiceWorkerContainer.webidl`, `components/script/dom/serviceworkercontainer.rs`

The implementation of `ServiceWorkerContainer::Register` was written before #12830, which added support for Promise values in DOM APIs. We can rewrite the code to remain synchronous but return a resolved Promise so that our implementation becomes compatible with existing tests.

**Comment by jdm** [comment]
Use `./mach run tests/html/service-worker/index.html` to verify the changes (the test will require updating to use Promises appropriately).

**Comment by Coder206** [comment]
@jdm May I?

**Comment by jdm** [comment]
@Coder206 Sure, go ahead.

**Comment by Coder206** [comment]
@jdm I apologize for the delay, I am having trouble building Servo on all my instances. 

I noticed there are steps in the code (`components/script/dom/serviceworkercontainer.rs`). However, some steps are missing, do you want me to add them based on `https://w3c.github.io/ServiceWorker/#service-worker-container-register-method`?

Also, should the command above for verifying be failing when running?

**Comment by KiChjang** [comment]
@Coder206 No, the issue here is sufficiently scoped to only modifying `ServiceWorkerContainer::register`. All other functions that are not relevant to the issue should not be touched.

**Comment by KiChjang** [comment]
After reading the new spec, it looks like the majority of the function body of `register` needs to be rewritten, and extracted into a new method called `start_register`.

**Comment by jdm** [comment]
I disagree. I don't think it's worth changing the goal posts here to adjust to the new specification changes; the goal of this issue to to change the implementation of Register to return a `Promise<ServiceWorker>` value instead of `Fallible<Root<ServiceWorker>>`.

**Comment by Coder206** [comment]
@jdm Thanks for all your time, patience and help for this issue! I learnt lots! :-)
