### ISSUE TITLE
Investigate a Lazy<T> DOM member type instead of MutNullableHeap<T>

### ISSUE THREAD

**Issue by jdm** [servo/servo#13402]
We have a pattern of lazy initialization of lots of DOM members. It would be nice if there were some way to make this pattern clearer for people reading DOM code.

**Comment by jdm** [comment]
This refers to our use of `.or_init()` for performing said lazy initialization.

**Comment by KiChjang** [comment]
It's not just that. Consider our existing implementation of `HTMLFormElement#elements`:
```rust
fn Elements(&self) -> Root<HTMLFormControlsCollection> {
        if let Some(elements) = self.elements.get() {
            return elements;
        }

        #[derive(JSTraceable, HeapSizeOf)]
        struct ElementsFilter {
            form: Root<HTMLFormElement>
        }
        impl CollectionFilter for ElementsFilter {
            fn filter<'a>(&self, elem: &'a Element, _root: &'a Node) -> bool {
                let form_owner = match elem.upcast::<Node>().type_id() {
                    NodeTypeId::Element(ElementTypeId::HTMLElement(t)) => {
                        match t {
                            HTMLElementTypeId::HTMLButtonElement => {
                                elem.downcast::<HTMLButtonElement>().unwrap().form_owner()
                            }
                            HTMLElementTypeId::HTMLFieldSetElement => {
                                elem.downcast::<HTMLFieldSetElement>().unwrap().form_owner()
                            }
                            HTMLElementTypeId::HTMLInputElement => {
                                let input_elem = elem.downcast::<HTMLInputElement>().unwrap();
                                if input_elem.type_() == atom!("image") {
                                    return false;
                                }
                                input_elem.form_owner()
                            }
                            HTMLElementTypeId::HTMLObjectElement => {
                                elem.downcast::<HTMLObjectElement>().unwrap().form_owner()
                            }
                            HTMLElementTypeId::HTMLOutputElement => {
                                elem.downcast::<HTMLOutputElement>().unwrap().form_owner()
                            }
                            HTMLElementTypeId::HTMLSelectElement => {
                                elem.downcast::<HTMLSelectElement>().unwrap().form_owner()
                            }
                            HTMLElementTypeId::HTMLTextAreaElement => {
                                elem.downcast::<HTMLTextAreaElement>().unwrap().form_owner()
                            }
                            _ => {
                                debug_assert!(!elem.downcast::<HTMLElement>().unwrap().is_listed_element());
                                return false;
                            }
                        }
                    }
                    _ => return false,
                };

                match form_owner {
                    Some(form_owner) => form_owner == self.form,
                    None => false,
                }
            }
        }
        let filter = box ElementsFilter { form: Root::from_ref(self) };
        let window = window_from_node(self);
        let elements = HTMLFormControlsCollection::new(window.r(), self.upcast(), filter);
        self.elements.set(Some(&elements));
        elements
    }
```
where `self.elements` has the type `MutNullableHeap<JS<HTMLFormControlsCollection>>`. We wouldn't be able to use `form.elements` directly in the Rust code, but instead we must already remember to use the WebIDL interface function `form.Elements()` instead.

**Comment by jdm** [comment]
From an ergonomic perspective, I agree that it would be nice to be able to use `self.elements` in a low-effort way. From a safety perspective, the type system helps here because `self.elements.get()` returns an optional value, so it's at least more work to do the wrong thing (ie. unwrapping).

**Comment by nox** [comment]
We could wrap `mitochondria::OnceCell`.

**Comment by KiChjang** [comment]
The other issue that I also had with `self.elements` is that if it does return a `None`, it's not very self-evident where I *can* actually obtain a value for `self.elements`, until I read the entire source code where I finally find the `self.Elements()` method.

**Comment by jdm** [comment]
[LazyCell](https://crates.io/crates/lazycell) basically encapsulates our current setup in a crate.

**Comment by KiChjang** [comment]
@sendilkumarn Does this interest you?

**Comment by sendilkumarn** [comment]
I would love to. Let me have a look. Thanks

**Comment by sendilkumarn** [comment]
Instead of `MutNullableHeap` we have to change`MutNullableJS`.

We will have to change `or_init` with `borrow_with`, the latter returns &T.

I am looking for an option to define `HeapSizeOf` for the `lazycell` objects.

**Comment by nox** [comment]
I would prefer if we used mitochondria, given I maintain it, and thus we can change it faster if needs be.

**Comment by sendilkumarn** [comment]
Okayes let me have a look at that 👍

**Comment by sendilkumarn** [comment]
Is there any place to find out how to define the `HeapSize` ?

**Comment by nox** [comment]
There is no need to implement `HeapSize` for `mitochondria::OnceCell`, given `MutNullableJS` needs to be preserved as a wrapper of the `mitochondria` cell, and `JS<>`-like types don't own what they point to.

See this in js.rs:

```rust
impl<T: DomObject> HeapSizeOf for MutNullableJS<T> {
    fn heap_size_of_children(&self) -> usize {
        // See comment on HeapSizeOf for JS<T>.
        0
    }
}
```

**Comment by sendilkumarn** [comment]
> given MutNullableJS needs to be preserved as a wrapper of the mitochondria cell

Aren't we removing `MutNullableJS` reference?

**Comment by nox** [comment]
@sendilkumarn Using either `mitochondria` or `lazycell`, that doesn't change the fact that we need a wrapper about that, we can't just use these cells and put a `JS<T>` inside, that would require unsafe code.

**Comment by sendilkumarn** [comment]
Is this still required, since we have removed or_init almost everywhere ? 

Note: sorry was slightly held up in between

**Comment by KiChjang** [comment]
Yes, this still does not exist yet.

**Comment by sendilkumarn** [comment]
What needs to be done now?

**Comment by KiChjang** [comment]
Was there a PR that changes all existing usages of MutNullableJS<T> to something akin to a LazyCell<T>?

**Comment by sendilkumarn** [comment]
no I guess not. 
something like `MutNullableJS <OnceCell <T>>` is it? 
if we are using mitochondria

**Comment by nox** [comment]
`OnceCell<JS<T>>`, but yeah.

**Comment by sendilkumarn** [comment]
Okay then I will start to work on this. `OnceCell<JS<T>>`

**Comment by sendilkumarn** [comment]
`MutNullableJS`  set methods can mutate the value. Do you guys think moving to  moving to `MoveCell` rather than `OnceCell` makes sense. 

I started with node,  Implemented a new `MoveCell<Option<JS <T>>>` , so far I havent faced any issues. But with `OnceCell`  we have problems with mutating since it can be set only once.

**Comment by nox** [comment]
`Lazy<T>` (what this issue is about) is specifically about initialising once instead of needing something similar to `MutNullableJS`. That's why `OnceCell<JS<T>>` should be used here.

**Comment by nox** [comment]
In my opinion it should be actually named `OnceJS<T>` or something similar rather than `Lazy<T>`, because with "lazy" structures, you don't usually need to pass the closure you want to be executed in case it wasn't initialised when you want to access it.

**Comment by sendilkumarn** [comment]
> Lazy<T> (what this issue is about) is specifically about initialising once instead of needing 

That means it is not a complete replacement of `MutNullableJS` right ? Then I can send the first level of PR with only `OnceCellJS` implemented. 

But how to find out, places where they are lazily initialised 🤔 

> In my opinion it should be actually named OnceJS<T> 

As far as the name is concerned, yes I agree and I named it as `OnceCellJs<T>`

**Comment by nox** [comment]
> That means it is not a complete replacement of MutNullableJS right ? Then I can send the first level of PR with only OnceCellJS implemented.

Yes. This idiom currently uses `MutNullableJS` because that's the only thing we currently have, that's all. :)
