### ISSUE TITLE
Implement Location.replace

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#13413]
This would allow us to click links on Google search.

Should be a straightfoward implementation - refer to the implementation of `fn Assign` if it's not clear.

Spec: https://html.spec.whatwg.org/multipage/browsers.html#dom-location-replace
Files: `components/script/dom/webidls/Location.webidl`, `components/script/dom/location.rs`
Test: `tests/wpt/web-platform-tests/html/browsers/history/the-location-interface/location_replace.html`

**Comment by stshine** [comment]
I'd like to have a try.

**Comment by jdm** [comment]
Please do!
