### ISSUE TITLE
Make Location::Assign throw an error if URL parsing fails

### ISSUE THREAD

**Issue by jdm** [servo/servo#13420]
Step 2 of https://html.spec.whatwg.org/multipage/browsers.html#dom-location-assign says we should [throw an exception](http://doc.servo.org/script/dom/bindings/index.html#throwing-exceptions), but the current implementation does not do that.

Code: `components/script/dom/location.rs`, `components/script/dom/webidls/Location.webidl` (add a `[Throws]` annotation)
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/browsers/history/the-location-interface/location_assign.html`

**Comment by SecurityInsanity** [comment]
I think I'll take a whack at this.

**Comment by jdm** [comment]
Great! Please ask questions here if anything is unclear!
