### ISSUE TITLE
Create a way of getting a serialized single value out of a declaration block

### ISSUE THREAD

**Issue by birtles** [servo/servo#13423]
See discussion in [bugzilla bug 1302949](https://bugzilla.mozilla.org/show_bug.cgi?id=1302949#c17).

We are using Servo to parse animation values into a declaration block. However, the Web Animations API provides a means of inspecting those values so we need to serialize them back again. In [bug 1302949](https://bugzilla.mozilla.org/show_bug.cgi?id=1302949) we just rely on the string having a certain shaping and picking bits off it but this is not particularly reliable.

Basically the setup is as follows:
* Input: property / value pairs where both property names and values are strings. Properties may be shorthand properties. Values may include variable references.
* We parse these into declaration blocks (PropertyDeclarationBlock), one for each property value. If we have a shorthand property like 'margin', the block will represent all the expanded values.
* Then we later serialize these such that each block produces a single value.

e.g. 'margin': '10px 20px' &rarr; `PropertyDeclarationBlock` containing "margin-left: 20px, margin-top: 10px, etc." &rarr; "10px 20px".

@Manishearth said he would be interested in looking into this 😉

**Comment by Manishearth** [comment]
Is it okay if you have to explicitly specify the property when serializing? Or would you prefer it get figured out automatically?

i.e. do you want `(declarationblock, propertyname) -> String` or just `(declarationblock) -> String`

**Comment by birtles** [comment]
Passing in the property name should be fine.

2016/09/30 23:21 "Manish Goregaokar" <notifications@github.com>:
