### ISSUE TITLE
Push build time to perfherder

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#13430]
Push servo's build time data to perfherder so we can track. 

Incremental build time for big crates like style, layout might also be interesting, but that wastes the build machine time just to get the build time data.

**Comment by shinglyu** [comment]
We can modify this script to do it: https://github.com/servo/servo/blob/master/etc/ci/performance/submit_to_perfherder.py

**Comment by shinglyu** [comment]
This is a easy task, but you need perfherder access right to test it or you need to setup your local perfherder server, so I'm not sure if we want to mark it as E-easy or not.

**Comment by nox** [comment]
Any progress on this?

**Comment by jdm** [comment]
No.

**Comment by mrobinson** [comment]
I suspect that this is no longer possible since Servo is outside of the Mozilla corral now.
