### ISSUE TITLE
Navigating to the same URL with a fragment needs to interact with session history

### ISSUE THREAD

**Issue by jdm** [servo/servo#13437]
Currently, `ScriptThread::handle_navigate` short-circuits if the pre-fragment URL is the same. It scrolls to the chosen fragment then returns without performing any actual load. This means that the session history in the constellation doesn't know anything about the navigation.

cc @ConnorGBrewster for suggestions

**Comment by ConnorGBrewster** [comment]
The plan is to add a field to `FrameState` that would store info for this. When navigating to a fragment it will add a new entry to the `Frame` without causing a new load.
