### ISSUE TITLE
trait `js::conversions::ToJSValConvertible: core::marker::Sized` not satisfied

### ISSUE THREAD

**Issue by malisas** [servo/servo#13465]
The compiler produces the following error:

```
error[E0277]: the trait bound `js::conversions::ToJSValConvertible: core::marker::Sized` is not satisfied
  --> /home/malisa/git_repos/malisa-servo/servo/components/script/body.rs:71:21
   |
71 |             promise.resolve_native(promise.global().r().get_cx(), val);
   |                     ^^^^^^^^^^^^^^ trait `js::conversions::ToJSValConvertible: core::marker::Sized` not satisfied
   |
   = note: `js::conversions::ToJSValConvertible` does not have a constant size known at compile-time
```

when I try to compile this code:

```
let val: &ToJSValConvertible = match r {
    FetchedData::Text(s) => &USVString(s),
    FetchedData::Json(ref j) => j,
    FetchedData::BlobData(ref b) => b,
    FetchedData::FormData(ref f) => f,
};
promise.resolve_native(promise.global().r().get_cx(), val);
```

**Comment by jdm** [comment]
The problem is that resolve_native takes a generic value bounded by `ToJSValConvertible`, and instead of passing a concrete type to it we're trying to pass a trait object. I'm not sure if there's a way to get the ergonomic code we want (eg. the snippet) in the previous comment without creating a new method on `Promise` that accepts an `&ToJSValConvertible` argument instead.

**Comment by nox** [comment]
Can't we just implement `ToJSValConvertible` for `&ToJSValConvertible`? https://play.rust-lang.org/?gist=aabe46af9b3ba6b7138b3acc5c66d6f5&version=stable&backtrace=1

**Comment by Ms2ger** [comment]
It's certainly possible, but would probably involve a virtual call... Might still be worth it.

**Comment by nox** [comment]
We can just make `ToJSValConvertible` be `?Sized` if we really want to be able to support trait objects, no?

**Comment by nox** [comment]
Should this issue be closed? Not sure how it's actionable.

**Comment by jdm** [comment]
Yeah, no pressing need to fix this.
