### ISSUE TITLE
Fix origin/clip behavior in mask and background shorthands in style

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#13466]
In both specs, if one <geometry-box> value is present then it sets both mask-origin and mask-clip to that value. If two <geometry-box> values are present, then the first sets mask-origin and the second mask-clip. But in both parsing process,  we are setting just origin if one <geometry-box> value is present. This effects just parsing functions, serialization functions' behaviors are correct.
Files: `components/style/properties/shorthand/mask.mako.rs` and 
`components/style/properties/shorthand/background.mako.rs`

Specs:
https://drafts.fxtf.org/css-masking-1/#the-mask
https://drafts.csswg.org/css-backgrounds-3/#the-background

**Comment by canaltinova** [comment]
I'm going to work on that issue after mask pr lands.

**Comment by canaltinova** [comment]
@Manishearth Hi!
It is trickier than I expected. Determining if "one value present" is the easy part, but in that case, you can not assign clip directly like `clip = origin;` because they are different `SpecifiedValue` enums.
So a few options came to my mind to solve this issue,
I can create parsed value by hand(but you didn't recommend me this before) or I can create a parser and parse it as `mask_clip::single_value::parse(context, input))`. But I don't think creating a parser by hand is a good idea either. 
Maybe we can change longhands and make them use same enum with each other. And we can assign them easily without creating a parsed value or parser by hand. Or maybe there is another way that I don't know. What do you think?

**Comment by Manishearth** [comment]
They can't use the same enum in the mask case, since `mask-clip` can be `no-clip` but not `mask-origin`. Having a `From` impl and converting is okay with me.
