### ISSUE TITLE
In dev (aka debug) builds, do not change the subsystem to Windows

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#13487]
By default, Rust binaries on Windows use the `console` subsystem. This is great because we get output to stdout/stderr for rust logging, but terrible for the user experience because a console window pops up if you run the application.

Today, we switch the subsystem to `windows` unconditionally here:
https://github.com/servo/servo/blob/master/python/servo/build_commands.py#L262

In this work, if we are doing a `is_dev` build, we should not make that call to `editbin`, so that it is easier to debug issues.

**Comment by larsbergstrom** [comment]
This has been taken in #13488.

**Comment by tobbi** [comment]
Since #13488 is closed, this can be closed as well, can't it?

**Comment by larsbergstrom** [comment]
Great catch, thanks!
