### ISSUE TITLE
Navigation items at the top of nbc.com overlap one another horizontally

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#13495]
The text is all smushed together—layout considers the floats to have the wrong widths. Each item seems to have `float: left` and the elements inside form stacking contexts in various ways.

**Comment by stshine** [comment]
Here is a minimal test case:
```html
<!DOCTYPE html>
<html>
    <head>
        <style>
         ul {
             position: absolute;
         }
         li {
             float: left;
             list-style-type: none;
         }
        </style>
    </head>
    <body>
        <span id="container">
            <ul>
                <li>Alpha</li>
                <li>Beta</li>
                <li>Garmma</li>
            </ul>
        </span>
    </body>
</html>
```

**Comment by stshine** [comment]
What's interesting most here is that this only happens when <ul> are wrapped in a inline element. Looks like a bug in the interaction of out-of-flow block and inline-block split.

**Comment by stshine** [comment]
I'd like to work on this.

**Comment by pcwalton** [comment]
Go for it! I suspect it's inline hypothetical box related.

**Comment by nox** [comment]
This still happens.
