### ISSUE TITLE
Intermittent timeout (Connection reset by peer in FontCacheThread::font_template) in /2dcontext/drawing-paths-to-the-canvas/drawFocusIfNeeded_005.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#13492]
```
▶ TIMEOUT [expected FAIL] /css21_dev/html4/white-space-normal-002.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ failed to receive response to font request: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread LayoutWorker worker 2/12, at ../src/libcore/result.rs:799)
  │ stack backtrace:
  │    0:     0x7f9465296f3d - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:     0x7f94652975c2 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:     0x7f9463dde32d - servo::main::_{{closure}}::h911afab4cc009f33
  │    3:     0x7f9465875705 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
  │    4:     0x7f94658755d2 - std::panicking::begin_panic::hfbeda5aad583dc32
  │    5:     0x7f9465875510 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
  │    6:     0x7f9465875491 - rust_begin_unwind
  │    7:     0x7f94658b1f1c - core::panicking::panic_fmt::h4395919ece15c671
  │    8:     0x7f946503faf4 - core::result::unwrap_failed::h3191a47cbfbe2a26
  │    9:     0x7f9465062ad0 - gfx::font_cache_thread::FontCacheThread::find_font_template::hc43bc4dfd5ffdc42
  │   10:     0x7f9465064043 - gfx::font_context::FontContext::layout_font_group_for_style::h01f9ffa61c2005ba
  │   11:     0x7f9464f6e2c2 - layout::text::font_metrics_for_style::h72c8d7dca9a84d50
  │   12:     0x7f9464f49002 - layout::fragment::Fragment::calculate_line_height::h182689e7f93954f5
  │   13:     0x7f9464f4b907 - layout::fragment::Fragment::inline_metrics::hbc62de89447e8d4a
  │   14:     0x7f9464f4fb3f - layout::inline::LineBreaker::new_block_size_for_line::ha0fed9ad333c3b8e
  │   15:     0x7f9464f5244b - _<layout..inline..InlineFlow as layout..flow..Flow>::assign_block_size::h7968f0caf80f48a1
  │   16:     0x7f9464f58a8e - _<layout..traversal..AssignISizes<'a> as layout..parallel..ParallelPreorderFlowTraversal>::run_parallel::h174aa7955422975d
  │   17:     0x7f9464f58f19 - layout::parallel::assign_inline_sizes::ha895aa936b7997a8
  │   18:     0x7f946411f373 - _<std..panic..AssertUnwindSafe<F> as core..ops..FnOnce<()>>::call_once::h92e6ab92d967950b
  │   19:     0x7f94640cc2b0 - std::panicking::try::do_call::h61ee89652c7f18dc
  │   20:     0x7f946587e086 - __rust_maybe_catch_panic
  │   21:     0x7f94640f3a2c - _<F as alloc..boxed..FnBox<A>>::call_box::h0444ca8d98004df8
  │   22:     0x7f9465873d40 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  │   23:     0x7f9461ce8183 - start_thread
  │   24:     0x7f94617ff37c - clone
  │   25:                0x0 - <unknown>
  └ ERROR:servo: failed to receive response to font request: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
```

Same symptom as #12987.

**Comment by Wafflespeanut** [comment]
▶ CRASH [expected PASS] /css21_dev/html4/text-transform-applies-to-009.htm
    │ 
    │ VMware, Inc.
    │ Gallium 0.4 on softpipe
    │ 3.3 (Core Profile) Mesa 12.0.1
    │ failed to receive response to font request: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread LayoutWorker worker 2/12, at ../src/libcore/result.rs:799)
    │ stack backtrace:
    │    0:     0x7f18aba9476d - backtrace::backtrace::trace::h0e60ef08c7c34e9f
    │    1:     0x7f18aba94df2 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
    │    2:     0x7f18aa5d562d - servo::main::_{{closure}}::h911afab4cc009f33
    │    3:     0x7f18ac073175 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
    │    4:     0x7f18ac073042 - std::panicking::begin_panic::hfbeda5aad583dc32
    │    5:     0x7f18ac072f80 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
    │    6:     0x7f18ac072f01 - rust_begin_unwind
    │    7:     0x7f18ac0af98c - core::panicking::panic_fmt::h4395919ece15c671
    │    8:     0x7f18ab83d524 - core::result::unwrap_failed::h3191a47cbfbe2a26
    │    9:     0x7f18ab860300 - gfx::font_cache_thread::FontCacheThread::find_font_template::hc43bc4dfd5ffdc42
    │   10:     0x7f18ab861873 - gfx::font_context::FontContext::layout_font_group_for_style::h01f9ffa61c2005ba
    │   11:     0x7f18ab76bcf2 - layout::text::font_metrics_for_style::h72c8d7dca9a84d50
    │   12:     0x7f18ab7467b2 - layout::fragment::Fragment::calculate_line_height::h182689e7f93954f5
    │   13:     0x7f18ab7490b7 - layout::fragment::Fragment::inline_metrics::hbc62de89447e8d4a
    │   14:     0x7f18ab74d2ef - layout::inline::LineBreaker::new_block_size_for_line::ha0fed9ad333c3b8e
    │   15:     0x7f18ab74fbfb - _<layout..inline..InlineFlow as layout..flow..Flow>::assign_block_size::h7968f0caf80f48a1
    │   16:     0x7f18ab75625e - _<layout..traversal..AssignISizes<'a> as layout..parallel..ParallelPreorderFlowTraversal>::run_parallel::h174aa7955422975d
    │   17:     0x7f18ab7566e9 - layout::parallel::assign_inline_sizes::ha895aa936b7997a8
    │   18:     0x7f18aa916923 - _<std..panic..AssertUnwindSafe<F> as core..ops..FnOnce<()>>::call_once::h92e6ab92d967950b
    │   19:     0x7f18aa8c3860 - std::panicking::try::do_call::h61ee89652c7f18dc
    │   20:     0x7f18ac07baf6 - __rust_maybe_catch_panic
    │   21:     0x7f18aa8eafdc - _<F as alloc..boxed..FnBox<A>>::call_box::h0444ca8d98004df8
    │   22:     0x7f18ac0717b0 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
    │   23:     0x7f18a84df183 - start_thread
    │   24:     0x7f18a7ff637c - clone
    │   25:                0x0 - <unknown>
    │ ERROR:servo: failed to receive response to font request: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
    └ Pipeline failed in hard-fail mode.  Crashing!
