### ISSUE TITLE
Flexbox bug: "Cards" are too wide on nbc.com

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#13494]
On nbc.com the boxes that contain information about each show ("cards") are too wide—their width incorrectly spans the whole page.

This looks like a flexbox bug: we need to support the `flex-basis: 33.33%` rule.

**Comment by stshine** [comment]
I can't see the website because of network issue, but the flexbox related properties are still marked as experimental. To test flexbox you need to add following to prefs.json or specify them in command line:
```
  "layout.flex.enabled": true,
  "layout.flex-flow.enabled": true,
  "layout.flex-direction.enabled": true,
  "layout.flex-wrap.enabled":true,
  "layout.flex-grow.enabled":true,
  "layout.flex-shrink.enabled":true,
  "layout.justify-content.enabled":true,
  "layout.align-items.enabled":true,
  "layout.align-self.enabled":true,
  "layout.align-content.enabled":true,
```

**Comment by stshine** [comment]
Yeah, with these prefs enabled the card widths are normal.

**Comment by pcwalton** [comment]
Ah, OK, so not a bug.
