### ISSUE TITLE
Clean up CompositorTask

### ISSUE THREAD

**Issue by saneyuki** [servo/servo#1351]
`run_compositor` has some closure functions in his large body, and variables has very long lifetime. This code is not clearly. So I propose to clean up `run_compositor`.
My plan is these:
* Create `IOCompositor` struct.
* split up some closure functions in `run_compositor` to IOCompositor`'s methods.

But I seem this change has some disadvantage:
* `IOCompositor` struct would be almost mutable. This causes needless mutable state for some variables which need not to be mutable. (e.g. command line options).
* It may be causes some needless member accesses. (I don't know this is realistic problem).

@pcwalton how do you think about these disadvantage?

If there're no problem, I'll start this work.

**Comment by mbrubeck** [comment]
The remaining items are done or no longer apply.
