### ISSUE TITLE
Should be able to interleave scroll frame contents with unscrolled elements from outside the scroll frame

### ISSUE THREAD

**Issue by mstange** [servo/servo#13529]
This will probably be addressed by @mrobinson's "scroll frames shouldn't build stacking contexts" work, but I made a testcase so I may as well file a bug for it.

In this testcase, during scrolling, the blue element should be underneath the yellow circle, but the green element should be on top of the yellow circle: https://jsfiddle.net/mstange/e52gpo6j/1/

``` html
<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<title>Scroll frame contents can be interleaved by unscrolled elements</title>

<style>

.scrollbox {
  margin-left: 100px;
  width: 300px;
  height: 400px;
  overflow: auto;
  border: 1px solid black;
}

.scrolledContent {
  padding: 200px 0;
  height: 1000px;
}

.layer {
  height: 40px;
  margin: 10px;
  border: 1px solid rgba(0, 0, 0, 0.3);
}

.bottom {
  background-color: blue;
}

.middle {
  background-color: rgba(255, 255, 0, 0.9);
  position: absolute;
  top: 50px;
  left: 30px;
  width: 150px;
  height: 150px;
  border-radius: 100%;
}

.top {
  background-color: lime;
  position: relative;
  z-index: 1;
}

</style>

<div class="scrollbox">
  <div class="scrolledContent">
    <div class="layer bottom"></div>
    <div class="layer top"></div>
  </div>
</div>

<div class="layer middle"></div>
```

**Comment by glennw** [comment]
@mrobinson We're considering whether to remove the non-WR backend. Would doing that simplify your scroll root / stacking context work?

**Comment by mrobinson** [comment]
@glennw Yes, most of the complication is turning the scrolling root annotations into layers, so removing the legacy path would probably mean half the work.
