### ISSUE TITLE
Make ./mach cargo-update update cargo if outdated

### ISSUE THREAD

**Issue by nox** [servo/servo#13526]
If Cargo is bumped in Servo but one's build artifacts predates that bump, running `./mach cargo-update` will use the previous version of Cargo without emitting any warning or info message. This can results in an incomplete crate bump like in #13444. The command `./mach cargo-update` should first check whether Cargo is up-to-date and update it if needed, like what `./mach build` does.

**Comment by GuillaumeGomez** [comment]
I take it.
