### ISSUE TITLE
Scroll frames should not be containing blocks for position:absolute descendants

### ISSUE THREAD

**Issue by mstange** [servo/servo#13530]
In this testcase, the cyan circle should not scroll with the scroll frame contents: https://jsfiddle.net/mstange/r96r1pqh/1/

Additionally, it should not be clipped by the scroll frame. And it should be composited in the same opacity group as the scrolled contents.

``` html
<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<title>Opacity does not create a containing block for position:absolute descendants, the clip on the opacity should only apply to the descendants that have opacity as their containing block, and all elements in the opacity should share the same opacity group.</title>

<style>

.scrollbox {
  margin-left: 100px;
  width: 300px;
  height: 400px;
  overflow: auto;
  border: 1px solid black;
}

.scrolledContent {
  padding: 200px 0;
  height: 1000px;
}

.opacity {
  opacity: 0.8;
}

.layer {
  height: 40px;
  margin: 10px;
  border: 1px solid rgba(0, 0, 0, 0.3);
}

.bottom {
  background-color: blue;
}

.middle {
  background-color: cyan;
  position: absolute;
  top: 50px;
  left: 30px;
  width: 150px;
  height: 150px;
  border-radius: 100%;
}

.top {
  background-color: magenta;
  position: relative;
  z-index: 1;
  margin-left: -50px;
}

</style>

<div class="scrollbox">
  <div class="scrolledContent opacity">
    <div class="layer bottom"></div>
    <div class="layer middle"></div>
    <div class="layer top"></div>
  </div>
</div>
```

**Comment by glennw** [comment]
@mrobinson I tested this against master and it doesn't seem to be working for me?

**Comment by mrobinson** [comment]
Hrm. This seems to be working for me:
![absolutelypositioneddescendants](https://cloud.githubusercontent.com/assets/13536/24391585/48954a3c-1390-11e7-8eda-ae8756b0a561.gif)

Perhaps that's some kind of platform / build-type specific issue?

**Comment by glennw** [comment]
Interesting. I'll try a fresh build again tomorrow and see if I can still repro. The gif looks great!

**Comment by glennw** [comment]
@mrobinson I tested this again - pasted the repro case above into a file, and loaded in current Servo master - and it doesn't seem to work. Perhaps the test repro above is incorrect? Or something really weird is happening with my build?

**Comment by glennw** [comment]
@mrobinson Oh, never mind - I just realized it was an issue with my local build. This all works now, great news!
