### ISSUE TITLE
Write tests for parsing of background shorthand in style

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#13548]
Writing parse tests for background shorthand is very similar to mask shorthand tests since parsing implementation is pretty much same. We wrote unit tests for mask shorthand in #13336. 
To write this, we need to add file to `tests/unit/style/parsing/background.rs`, then we can simply copy and paste tests from `tests/unit/style/parsing/mask.rs` and change mask longhands to background longhands to cover all background cases.

You can see all background longhands here:
https://github.com/servo/servo/blob/master/components/style/properties/shorthand/background.mako.rs#L9-L10
You can use `./mach test-unit -p style` command to run the tests.

Spec: https://drafts.csswg.org/css-backgrounds-3/#the-background

**Comment by b-lambert** [comment]
I would be interested in taking this on!

**Comment by jdm** [comment]
Please do! Ask questions here about anything that is unclear.

**Comment by b-lambert** [comment]
Cool, feel free to assign me to it.

**Comment by jdm** [comment]
@b-lambert Have you made any progress? Do you have any questions?

**Comment by b-lambert** [comment]
Negative, had to put this on back-burner. If someone else wants to take it on, feel free. :)

**Comment by jdm** [comment]
I'll mark this as unassigned, in that case. If you do pick it up again, please let us know :)

**Comment by awesomeaniruddh** [comment]
I'd like to tackle this!

**Comment by jdm** [comment]
Please do!

**Comment by jdm** [comment]
@awesomeaniruddh Have you made any progress here? Do you have any questions?

**Comment by linclark** [comment]
I can take this one. I already have a start with a `background_shorthand_should_parse_all_available_properties_when_specified` test.

**Comment by canaltinova** [comment]
@linclark,  It looks like @awesomeaniruddh is not working anymore. So go ahead! You can ask here if you have any questions.

**Comment by linclark** [comment]
Thanks! I pushed up a PR. If I missed any cases, let me know and I'd be happy to add them.
