### ISSUE TITLE
Can't build in OpenSUSE: need glu-devel to compile

### ISSUE THREAD

**Issue by thuibr** [servo/servo#13542]
This package is not found in YAST, however. I am running a fresh install of OpenSUSE Leap 42.1. Without it, I receive a fatal error:

`fatal error: GL/glu.h: No such file or directory
 #include <GL/glu.h>
`

The package can be found here:
https://software.opensuse.org/package/glu-devel

**Comment by j-koreth** [comment]
My apoligies for the discrepancy I have opened a pull request to fix it
