### ISSUE TITLE
Figure out what to do for complex colors that aren't represented as such on the Gecko side

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13547]
See https://github.com/servo/servo/pull/13539#discussion_r81461072

Some color values like `background-color` and `flood-color` allow `currentColor` (and we parse them as such), but they are not represented as `StyleComplexColor` on the Gecko side. We should figure out why (perhaps fixing Gecko, or parsing them differently on our side), and map the currentcolor value suitably. We currently just use the zero value

cc @emilio @heycam

**Comment by nox** [comment]
This was done for Stylo.
