### ISSUE TITLE
Use hyper::method::Method in dom/request.rs

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#13543]
I believe only hyper was imported because of the many different types that are named methods in the file. We can instead rename the import by doing `use hyper::method::Method as HttpMethod;` and update the paths in the file accordingly.

File: `components/script/dom/request.rs`
No need for any tests; if it compiles, it's good enough for a PR.

**Comment by thuibr** [comment]
Hello. I'd like to claim this ticket.

**Comment by KiChjang** [comment]
Sure thing!
