### ISSUE TITLE
Create packages (.tar.gz) under debug/release as appropriate

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#13551]
Currently, some of our packagers create the generated package (.tar.gz file) in the `target/` directory. We should have all packages be created under `target/release/` or `target/debug/`, depending on how servo was built.

Files:
- python/servo/package_commands.py
- etc/ci/upload_nightly.sh

No need to a write a test, but this should be manually tested by running `./mach package`, ensuring that the package appears in the correct place, and running the `upload_nightly.sh` script to make sure it finds the right package. (Hint: you can prefix the `s3cmd` lines in the upload script with `echo` to see what will happen without actually trying to upload the package.)

**Comment by Coder206** [comment]
I would like to continue the quest ;)

**Comment by birryree** [comment]
I'm new to the Servo project but have a lot of Python and build tooling experience, so I'd be happy with giving this a crack.

**Comment by aneeshusa** [comment]
@birryree It's yours! Let us know if you have any questions.

**Comment by jdm** [comment]
@birryree Have you made any progress on this? Any questions?

**Comment by birryree** [comment]
@jdm - Sorry, had been sick for part of the last couple weeks. I just got around to creating an environment for building servo on Linux and I know where my changes should go in.

I do have a question though - do we want similar changes to apply to non-Linux systems? I mainly work on macos and the resulting `dmg` is packaged under `/target` as well. I can also probably make changes for Windows-based builds.

**Comment by jdm** [comment]
@birryree It would be great to fix those at the same time!
