### ISSUE TITLE
Servo nightly package has the wrong path for browserhtml

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#13552]
The package I download just now (`./servo -v == Servo 0.0.1-7da20f2
`) has the wrong path for browserhtml package. 

The `runservo.sh` says `./build/browserhtml-5c846c4e388d17ec/out/index.html`, but the unzipped folder looks like: 

```
.
├── build
│   ├── build-script-build
│   ├── out
│   └── output
```

I can't reproduce this locally, so I'd appreciate if someone can check the CI environment.

**Comment by paulrouget** [comment]
(Looks ok on osx)

**Comment by aneeshusa** [comment]
Likely a bug in #12850, I'll take a look.

**Comment by aneeshusa** [comment]
I checked the latest Linux nightly (which includes the PR for this) to confirm and it looks like this is working.
