### ISSUE TITLE
Enable flexbox layout by default

### ISSUE THREAD

**Issue by jdm** [servo/servo#13576]
When the first prototype flexbox code was merged, we hid it behind a bunch of preferences that defaulted to disabled. Now that we have a more complete implementation, it's time to enable it by default and remove all of the configurability.

There are a few parts to this:
- find the flexbox-related properties in `properties/shorthand/position.mako.rs`, `
  components/style/properties/longhand/position.mako.rs`,
  `components/style/properties/longhand/column.mako.rs`, and
  `components/style/properties/shorthand/column.mako.rs`
  and remove the `experimental=True` (which automatically hides it behind a `layout.[property-name].enabled` preference)
- remove the appropriate preferences from `resources/prefs.json` and `resources/package-prefs.json`
- remove `tests/wpt/mozilla/meta/css/__dir__.ini` and `tests/wpt/metadata-css/css-flexbox-1_dev/__dir__.ini`

**Comment by Haggus** [comment]
I will work on this issue :)

**Comment by jdm** [comment]
@Haggus Please do! Ask questions if anything is unclear!

**Comment by Haggus** [comment]
@jdm I do have few questions. Inside `components/style/properties/longhand/position.mako.rs`, I see properties like `justify-content`, `align-items`, `align-content`, and `align-self`

1. Are those part of flexbox props?
2. Also, for future reference, how could I find out

**Comment by jdm** [comment]
Those are properties listed in https://drafts.csswg.org/css-flexbox/ so they count. Looks like my initial suggestion of looking in the shorthand and longhand `column.mako.rs` files was incorrect; those properties are related to CSS multicolumn layout, which is separate from flexbox.

**Comment by stshine** [comment]
Column flexbox is still not implemented, but that's maybe not be a big deal, whatever. Remeber to have SimonSpain to review the tricky `display: flex` part.

**Comment by stshine** [comment]
#13590

**Comment by jdm** [comment]
Sorry @Haggus, another team member submitted #13590 without seeing this issue first :(

**Comment by Haggus** [comment]
@jdm No problem, I'll work on another one.

**Comment by jdm** [comment]
Fixed in #14111.
