### ISSUE TITLE
Transformed clips don't work

### ISSUE THREAD

**Issue by jrmuizel** [servo/servo#13578]
http://people.mozilla.org/~jmuizelaar/servo/clipped-rotate-clipped-rotate.html renders incorrectly.

@pcwalton

**Comment by jrmuizel** [comment]
FWIW, this is blocking our current WebRenderLayerManager/Gecko integration work

**Comment by kvark** [comment]
Related - https://github.com/servo/webrender/issues/427

**Comment by jrmuizel** [comment]
Looks fixed.
