### ISSUE TITLE
Invert conditional and return early for AddEventListener/RemoveEventListener

### ISSUE THREAD

**Issue by jdm** [servo/servo#13586]
The code in `EventTarget::AddEventListener` and `EventTarget::RemoveEventListener` currently looks like:
```rust
fn AddEventListener(...) {
    if let Some(listener) = listener {
        ....
    }
}
```
That is, it does nothing if the value is null. We can improve the readability of the code by doing this transformation:
```rust
fn AddEventListener(...) {
    let listener = match listener {
        Some(l) => l,
        None => return,
    };
    ...
}
```
Since that allows the rest of the code to be de-indented one level.

Code: `components/script/dom/eventtarget.rs`

No need to run any tests; if the code compiles, that should be good enough.

**Comment by slester** [comment]
I would like to work on this one as well!
