### ISSUE TITLE
Run CSS Multicolumn tests automatically

### ISSUE THREAD

**Issue by jdm** [servo/servo#13587]
We have some support for CSS properties from the [Multi-column specification](https://drafts.csswg.org/css-multicol-1/) but we don't run the tests. We should fix that!

1. Add new entries to `tests/wpt/include_css.ini` for the `css-multicol-1_dev` folder under `tests/wpt/css-tests`
2. Add a new `tests/wpt/metadata-css/css-multicol-1_dev/__dir__.ini` file that enables the appropriate preferences (`layout.{column-gap|column-width|column-count|columns}.enabled`) based on [similar files elsewhere](https://dxr.mozilla.org/servo/source/tests/wpt/mozilla/meta/css/__dir__.ini)
3. Run `./mach test-css tests/wpt/css-tests/css-multicol-1_dev/html4/ --log-raw /tmp/testlog`
4. Run `./mach update-css /tmp/testlog`

The resulting PR should include a lot of new ini files added to `tests/wpt/metadata-css/css-multicol-1_dev/` that contain expected test results.

**Comment by slester** [comment]
I'd like to give this a whirl!

**Comment by Ms2ger** [comment]
Go for it! Note that you should use update-css, not update-wpt in step 4.
