### ISSUE TITLE
Split length values into their own file

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13584]
[`components/style/values/computed/mod.rs`](https://github.com/servo/servo/blob/aea9545e16fd6ea4a6b1234d1b969457313a5fa7/components/style/values/computed/mod.rs) and [`components/style/values/specified/mod.rs`](https://github.com/servo/servo/blob/aea9545e16fd6ea4a6b1234d1b969457313a5fa7/components/style/values/specified/mod.rs) are huge. Those modules have submodules (`position` and `basic_shape`) for groups of CSS values related to particular properties, and we should add more.

A lot of the length-related stuff could be moved into a new module `length` in `values/specified/length.rs` (same for computed). Lengths are imported everywhere (and it's convenient to import directly from `style::values`, so we should reexport the moved types in `mod.rs` (via `pub use length::SomeType`).

The types that this would include would basically be anything in those files with `Length`, `Calc`, or `Percentage` in its name, as well as `CharacterWidth`. The `impl`s related to those would need to be moved too.

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by KiChjang** [comment]
@shubheksha Is this still being worked on?

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by kivikakk** [comment]
I'll do this now. :)

**Comment by kivikakk** [comment]
Curious if it makes sense to move `BorderRadiusSize` along with these. It's not a length as such, so inclined not to.
