### ISSUE TITLE
Have test-stylo run style crate tests too

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13595]
Currently, `./mach test-stylo` runs tests from `tests/unit/stylo`.

There are some more stylo-specific tests in [the structs files](https://github.com/emilio/servo/blob/c7e1a575a5225ccfb00a38fb50e052d986c0a78d/components/style/gecko_bindings/structs_debug.rs). These tests [are run when generating bindings](https://github.com/emilio/servo/blob/c7e1a575a5225ccfb00a38fb50e052d986c0a78d/components/style/binding_tools/regen.py#L546).

This works because the structs files are self contained. This is going to change soon, so we will have to run these tests as part of the style crate (compiled in geckolib mode).

Actual implementation is straightforward, we just need to call `cargo test -p style` with the right environment (the same that is used for `stylo_tests` in `./mach test-stylo`)

File: https://github.com/emilio/servo/blob/c7e1a575a5225ccfb00a38fb50e052d986c0a78d/python/servo/testing_commands.py#L247 , specifically https://github.com/emilio/servo/blob/c7e1a575a5225ccfb00a38fb50e052d986c0a78d/python/servo/testing_commands.py#L259

Testing: `./mach test-stylo` should continue to pass after this, and it should run far more tests (there will probably be `structs::` in the names of the new tests)

Feel free to let me or @Wafflespeanut know if you have questions~

**Comment by awesomeaniruddh** [comment]
I'd like to tackle this!

**Comment by Manishearth** [comment]
I'm sorry, I fixed this in https://github.com/servo/servo/commit/3d7c997a4f9e0960180075c1334fccd575bf221b since I needed it for a different PR, and forgot to close this issue.
