### ISSUE TITLE
Regression in CEF build time

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#13591]
As of http://build.servo.org/builders/linux-rel-css/builds/23, the CEF build now rebuilds the entire tree. This is due to:
https://github.com/servo/servo/commit/19a5a30113c3b58d69b6010c79db35b9bd8978c9#diff-4b02cf15724590179b4a5025f1a81a0dR223

With that line, I believe that the default release build and the CEF build have different `-C` flags. There are a few options here:
1) Move the CEF build to the other build flavor
2) Build CEF with that flag

It seems like #2 might be useful if we think we will start testing CEF, but #1 is definitely the easy one :-)

CC @nox @emilio

**Comment by larsbergstrom** [comment]
Oh, duh, #1 won't work because we set this flag in both linux-rel builders :-)

**Comment by emilio** [comment]
Thanks for taking care of this Lars! I meant to get to this today but I
couldn't finally :/

**Comment by larsbergstrom** [comment]
np! It was so easy that even I could do it :-)
