### ISSUE TITLE
Write a python script to generate type assertions for Servo_* functions

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13598]
This is the first step towards fixing #12992

https://github.com/emilio/servo/blob/c7e1a575a5225ccfb00a38fb50e052d986c0a78d/components/style/gecko_bindings/bindings.rs#L802 contains a bunch of `Servo_*` function declarations. These functions are defined in `ports/geckolib/glue.rs`.

We need a way of testing that the functions have the same signatures. This can be done by writing code that will not compile if they don't.

The main step here will be to write a python script in `gecko_bindings` that reads bindings.rs (assume it is in the same directory), and writes a `type_assertions.rs` file in the same directory. This file just contains code like the following:

```rust
fn assert_types() {
    [Servo_Foo, bindings::Servo_Foo];
    [Servo_Bar, bindings::Servo_Bar];
}
```

for each function in bindings.rs with a `Servo_*` signature. Be sure to include the generated file in your pull request.

This file can be `include!()`ed into a test in `tests/unit/stylo`, where all of the imports have been set up correctly. (This part isn't part of this bug, but feel free to work on it and ask me questions if you have any).

I'll hook it up to the main bindgen script later.

**Comment by Rafagd** [comment]
Is this what you want? https://github.com/servo/servo/pull/13603

**Comment by Wafflespeanut** [comment]
In the future, please claim the relevant issue before working on it, so that we can reduce duplicate efforts :)

**Comment by Rafagd** [comment]
I'll do it.
