### ISSUE TITLE
Make manifest_changed.sh check the CSS tests as well

### ISSUE THREAD

**Issue by jdm** [servo/servo#13607]
Right now the script invokes the `test-wpt` command, which verifies that the MANIFEST.json file for the WPT tests is valid. We should run the same set of commands for `test-css`, which would verify that the CSS tests' MANIFEST.json is valid too. This would have caught the syntax error seen in #13599.

Code: `etc/ci/manifest_changed.sh`

**Comment by jdm** [comment]
I lied; this wouldn't have caught the problem in #13599. It's still better than not doing it, however!

**Comment by jgraham** [comment]
The problem there might be caught by running the harness with `--list-test-groups`, although it's kind of only by accident that will work.

**Comment by shubheksha** [comment]
I'd like to work on this.

**Comment by jdm** [comment]
Please do!

**Comment by Manishearth** [comment]
This is more nuanced than we originally thought. Closing.
