### ISSUE TITLE
Build for ARM

### ISSUE THREAD

**Issue by galvesribeiro** [servo/servo#13606]
Hello,

Is it possible to build Servo for ARMv6l without VFP and targeting Linux Framebuffer (like /dev/fb) ?

Thanks!

**Comment by nox** [comment]
This issue is not actionable, closing it. But someone could indeed answer your question. Cc @larsbergstrom.

**Comment by galvesribeiro** [comment]
Sad that there is no interest from the core team to get it working on those devices... :(

**Comment by nox** [comment]
I'm pretty sure we would be happy helping along anyone who want to tackle this, it's just that none of us have the time to do it for now. I'm sure this will be revisited in the future.
