### ISSUE TITLE
Not rendering well on Fedora

### ISSUE THREAD

**Issue by jorrete** [servo/servo#13618]
Hi,
Not sure if it's servo or browserhtml issue but the initial page it's not rendering well on fedora 24.

![captura de pantalla de 2016-10-06 17-23-06](https://cloud.githubusercontent.com/assets/1777042/19158822/78fb8674-8bea-11e6-8dc8-a43466a34e4c.png)

It seems that its not rendering some parts of input boxes (rounded corners?).

Also regarding to the "Demo sites":
- Evil Ad, Only shows the ad not the colors dots.
- Moire, slow.
- Spheres, nothing and freezing servo.
- Transparent.., like 42fps but on mouse movement freezes servo.

My machine it is an Inte i7-3770 IvyBridge with no gf card and using the integrated gpu. I attach a screenshot of my about:support page in case it has useful information regarding to the gpu.

![captura de pantalla de 2016-10-06 17-37-29](https://cloud.githubusercontent.com/assets/1777042/19159290/290f8b4a-8bec-11e6-8a17-b71ecf1430e1.png)

I think it's common configuration on desktop linux machines (integrated intel gpu).

Thanks.

PD: 
Tested in today's nightly and from source of couple of days ago.

**Comment by emilio** [comment]
Also happens in Arch for me, probably is not system-dependent, but an issue with webrender. I've seen quite a lot of backgrounds not rendered, but the CPU back-end seems to work well. cc @glennw 

Thanks for reporting this!

**Comment by emilio** [comment]
It seems Linux and Intel-driver specific after a few people that tested it over IRC.

**Comment by anholt** [comment]
General best approach for failure like this is to capture using apitrace, replay against a software rasterizer or a working driver to ensure that the trace works correctly there, and file a bug with the trace attached at https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa

**Comment by glennw** [comment]
Interesting, since I develop on Linux + Intel and have never seen this! If anyone can send an apitrace with the problem to me, I can test it on my machine to see if it's a likely mesa issue, as @anholt mentioned above. Thanks!

**Comment by splav** [comment]
On AMD using Mesa driver the round corners are fine, Evil ad is fine, Spheres - fine. Moire hangs, sometimes showing only one circles series sometimes two series. Transparent - hangs.

**Comment by glennw** [comment]
I was wrong - I'm seeing the same browser.html issue on my system this morning too (must have regressed recently). I'll look into it today (I don't see it on any other websites - probably a transform issue which browser.html makes use of).

**Comment by emilio** [comment]
I've seen that also in https://twitter.com if that helps.

**Comment by glennw** [comment]
I minimized the border case and created an issue here: https://github.com/servo/webrender/issues/434

**Comment by nox** [comment]
Given that WR PR landed, I think we can close this.
