### ISSUE TITLE
Broken layout on Waffle's page

### ISSUE THREAD

**Issue by notriddle** [servo/servo#13622]
![screenie](https://cloud.githubusercontent.com/assets/1593513/19168094/5e51d8ae-8bc3-11e6-9f88-997940b97950.png)

https://wafflespeanut.github.io/blog/2016/10/05/and-i-thought-it-was-easy-dot-dot-dot/

This looks like an incremental restyle bug, because it doesn't show up until the page finishes loading, and it flakes back and forth when you mouse over it.

**Comment by pcwalton** [comment]
I bet this is related to #13630

**Comment by notriddle** [comment]
According to `git bisect`, this is a regression introduced by #13401.

**Comment by notriddle** [comment]
Fixed by #13685
