### ISSUE TITLE
Stylo: Implement -moz-text-align-last

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13638]
Please go through [the guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide) if you wish to hack on stylo.

[`text-align-last`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last) is a keyword property ([implementation guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide#implementing-a-simple-keyword-property)) with the set of possible values being `auto | start | end | left | right | center | justify`. `auto` is the default.

In Firefox, this property is called `-moz-text-align-last` (so we will implement it with that name), but behaves the same way. The constant prefix is [`NS_STYLE_TEXT_ALIGN`](https://dxr.mozilla.org/mozilla-central/rev/4b9944879c9a60a9aba4a744a7401bc38e0f39c4/layout/style/nsStyleConsts.h#863)

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/inherited_text.mako.rs

Testcase: https://gist.github.com/Manishearth/daaecff21aecb46d5d0b50bbfcd9c130 . It should look the same in Stylo as it does in vanilla Firefox after the changes have been made.

**Comment by awesomeaniruddh** [comment]
I'd like to take a stab at this!

**Comment by jdm** [comment]
Great! Please ask questions about anything that's unclear in the description or the guide!

**Comment by awesomeaniruddh** [comment]
I added the following code to `inherited_text.mako.rs`:
```
${helpers.single_keyword("-moz-text-align-last",
                         "auto start end left right center justify",
                         products="gecko",
                         gecko_constant_prefix="NS_STYLE_TEXT_ALIGN",
                         animatable=False)}
```

and I'm getting a build error on stylo. What am I doing wrong?

**Comment by Manishearth** [comment]
What is the build error?

**Comment by awesomeaniruddh** [comment]
```
 0:10.38 Exception in thread Thread-3:
 0:10.38 Traceback (most recent call last):
 0:10.38   File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
 0:10.38     self.run()
 0:10.38   File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
 0:10.38     self.__target(*self.__args, **self.__kwargs)
 0:10.38   File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
 0:10.38     task = get()
 0:10.38 TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())
```

**Comment by Manishearth** [comment]
Are you getting a build error without your changes?

**Comment by Manishearth** [comment]
Did you run `./mach bootstrap`? This might be an outdated dependency.

**Comment by awesomeaniruddh** [comment]
I did run `./mach bootstrap`. I am getting the error even without my changes even though I wasn't previously.

**Comment by Manishearth** [comment]
Hmm. Could you post the contents of the `mozconfig` file here? It may have changed.

Also, try `./mach clobber && ./mach bootstrap && ./mach build -j3`

**Comment by Wafflespeanut** [comment]
It should simply be `"text-align-last"` instead of `"-moz-text-align-last"`, but that error isn't related to your code. This is from gecko's `mach`. What's your OS? What's in your `mozconfig` file? And, I presume you just ran `./mach build`?

**Comment by Manishearth** [comment]
> It should simply be "text-align-last" instead of "-moz-text-align-last"

Incorrect; Gecko only supports the prefixed version. I plan to overhaul this code later so that you have better control over prefixes, but for now we must directly specify it with the prefix.

**Comment by Wafflespeanut** [comment]
We should be having another argument pointing to the right struct field, `gecko_ffi_name='mTextAlignLast'`

**Comment by awesomeaniruddh** [comment]
My mozconfig:
```
export LDFLAGS=-Wl,-no_compact_unwind
mk_add_options AUTOCLOBBER=1
ac_add_options --enable-stylo
ac_add_options --enable-warnings-as-errors
ac_add_options --enable-rust
ac_add_options --enable-artifact-builds
```

**Comment by Manishearth** [comment]
Not sure if artifact builds work with stylo. Could you remove the last option?

**Comment by awesomeaniruddh** [comment]
I ran `./mach clobber && ./mach bootstrap && ./mach build -j3` and got this:
```
0:08.76 Traceback (most recent call last):
 0:08.76   File "/Users/awesomeaniruddh/rust/stylo-flat/configure.py", line 107, in <module>
 0:08.76     sys.exit(main(sys.argv))
 0:08.76   File "/Users/awesomeaniruddh/rust/stylo-flat/configure.py", line 26, in main
 0:08.76     sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
 0:08.76   File "/Users/awesomeaniruddh/rust/stylo-flat/python/mozbuild/mozbuild/configure/__init__.py", line 256, in run
 0:08.76     raise InvalidOptionError('Unknown option: %s' % without_value)
 0:08.76 mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-warnings-as-errors
 0:08.81 *** Fix above errors and then restart with               "/Applications/Xcode.app/Contents/Developer/usr/bin/make -f client.mk build"
 0:08.81 make: *** [configure] Error 1
```

**Comment by Manishearth** [comment]
Remove the warnings-as-errors line as well I guess.

**Comment by Wafflespeanut** [comment]
This is what I have in my `mozconfig`

    mk_add_options AUTOCLOBBER=1
    ac_add_options --enable-stylo
    ac_add_options --enable-debug
    ac_add_options --disable-optimize
    ac_add_options --enable-warnings-as-errors
    ac_add_options --enable-rust

What happens if you use this?

**Comment by awesomeaniruddh** [comment]
I ran the build for 48 minutes and it failed with this message:
```
48:02.42 libdombindings_test_s.a.desc
48:02.60 make[3]: *** [compile] Error 2
48:02.60 make[2]: *** [default] Error 2
48:02.62 make[1]: *** [realbuild] Error 2
48:02.62 make: *** [build] Error 2
48:02.63 403 compiler warnings present.
48:02.85 /usr/local/bin/terminal-notifier -title Mozilla Build System -group mozbuild -message Build failed
```

Gonna run it with your mozconfig now.

**Comment by Manishearth** [comment]
Could you scroll up and find the actual error? Or pastebin as much of the output as you can.

**Comment by awesomeaniruddh** [comment]
It actually built successfully with your mozconfig!

**Comment by Manishearth** [comment]
cool, now try with those changes 😄 

You may need `gecko_ffi_name="mTextAlignLast"` if it says it can't find the field.

**Comment by awesomeaniruddh** [comment]
The terminals spits this out when running `./mach build -d`:
https://gist.github.com/awesomeaniruddh/d88e7e67df727ce8f0d4098b58b61906

**Comment by Wafflespeanut** [comment]
We don't have to build servo here (though, if you want, you need to install the dependencies specified in the readme). Please make your changes to servo inside stylo, build stylo and make sure you don't get an error :)

**Comment by Manishearth** [comment]
Right, you should be building stylo-flat, with `./mach build`.

However, it looks like a package is missing -- could you scroll up and pastebin as much of the output as you can? The actual build error is above.

**Comment by awesomeaniruddh** [comment]
Stylo builds successfully. I ran that command because the PR template told me to make sure that command didn't result in any errors. This is the full log:
https://gist.github.com/awesomeaniruddh/7a52e1eaa45cfc506f77c281fdebaa87

**Comment by Manishearth** [comment]
Oh, sorry. Ignore the PR template, this is for stylo.

Yeah, openssl headers need to be installed. See https://github.com/servo/servo/#on-os-x--1011-el-capitan-you-also-have-to-install-openssl

But that's only necessary for a pure-servo build. Stylo doesn't need openssl.

Alright, since you have this working, does the testcase run with your changes?

**Comment by awesomeaniruddh** [comment]
Yep.
