### ISSUE TITLE
mach should fail and warn if it detects mingw64 python

### ISSUE THREAD

**Issue by metajack** [servo/servo#13644]
If you fail to follow the instructions and rename `/mingw64/bin/python2.7.exe` and `/mingw64/bin/python2.exe` (or if you upgrade mingw64 and they reappear) then mysterious errors will occur.

We should change the `mach` script and `mach_bootstrap.py` so that they detect this case and fail and print an error. The logic will be slightly different in each case since in the `mach` script we'll already be executing under the bad python presumably, so we'll need to check the path to python2 or python2.7.exe is not under `/mingw64/bin`.

**Comment by UK992** [comment]
I would like to work on it.

**Comment by Wafflespeanut** [comment]
Cool!
