### ISSUE TITLE
Wiki of Bots: Gh-Pages Owner Link Update

### ISSUE THREAD

**Issue by Coder206** [servo/servo#13648]
The wiki of `Bots` (https://github.com/servo/servo/wiki/Bots) has a link for the `gh-pages` that gives a 404.

This is the link with no endpoint: 

![page-shot-2016-10-7 servo servo](https://cloud.githubusercontent.com/assets/7758155/19208289/9f3cf8b8-8cc6-11e6-9967-9afdf5cd112e.png)

Tags I think are appropriate please: A-Documentation

**Comment by jdm** [comment]
I suspect that's a link that only works for members of that team.
