### ISSUE TITLE
Use `.set` instead of manual `.set_value()` in gecko.mako.rs

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13657]
For [word-spacing and letter-spacing](https://github.com/servo/servo/blob/804317c8858a096eb99e1ff0baf860dbdfcbb04d/components/style/properties/gecko.mako.rs#L1531), we explicitly call `coord.set_value()` after matching on the type.

However, `nsStyleCoord` can have the method `.set()` called on it directly with `LengthOrPercentage` and `Au`.

Instead of [matching on the `lop` in `set_word_spacing`](https://github.com/servo/servo/blob/804317c8858a096eb99e1ff0baf860dbdfcbb04d/components/style/properties/gecko.mako.rs#L1544) we should just call `self.gecko.mWordSpacing.set(lop)`. We do something similar [in `set_vertical_position`](https://github.com/servo/servo/blob/804317c8858a096eb99e1ff0baf860dbdfcbb04d/components/style/properties/gecko.mako.rs#L868)

For `set_letter_spacing` we should do the [same as `set_column_width`](https://github.com/Manishearth/servo/blob/cb157b568f2406647370f16b22f9ba6b8535a6b9/components/style/properties/gecko.mako.rs#L1840)

File: [`components/style/properties/gecko.mako.rs`](https://github.com/servo/servo/blob/804317c8858a096eb99e1ff0baf860dbdfcbb04d/components/style/properties/gecko.mako.rs#L1531)

Tests: None, but `./mach build-geckolib` should pass.

**Comment by shubheksha** [comment]
I'd like to work on this!

**Comment by Manishearth** [comment]
go ahead!
