### ISSUE TITLE
Stylo: Implement font-kerning

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#13667]
Please go through the [guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide) before working on this issue.

[`font-kerning`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning) is a keyword property which takes one of the following values: `auto | normal | none`. The default value is `auto`. The linked MDN has more information about this.

The constant prefix you should be using is [`NS_FONT_KERNING`](https://dxr.mozilla.org/servo/rev/fe6fac4ee2af33c0fc61381c86c351982d4b73fd/components/style/gecko_bindings/structs_debug.rs#45-47)

You will need to manually implement the glue, see https://github.com/servo/servo/pull/13570/files for an example of this.

Code: `servo/components/style/properties/longhand/font.mako.rs`

- Use the example from the MDN page.
- Build stylo and screenshot how the example looks before your changes.
- Make your changes, build stylo and screenshot how it looks after.
- Open a PR with your changes and attach the screenshots

**Comment by Manishearth** [comment]
Make sure the MDN example has visible kerning. You may need to tweak the font to get this to work.
