### ISSUE TITLE
Stylo: Implement font-variant-position

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#13669]
Please go through the [guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide) before working on this issue.

[`font-variant-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-position) is a keyword property which takes one of the following values: `normal | sub | super`. The default value is `normal`. The linked MDN has more information about this.

The constant prefix you should be using is [`NS_FONT_VARIANT_POSITION`](https://dxr.mozilla.org/servo/rev/fe6fac4ee2af33c0fc61381c86c351982d4b73fd/components/style/gecko_bindings/structs_debug.rs#100-102)

Code: `servo/components/style/properties/longhand/font.mako.rs`

- Use the example from the MDN page.
- Build stylo and screenshot how the example looks before your changes.
- Make your changes, build stylo and screenshot how it looks after.
- Open a PR with your changes and attach the screenshots

**Comment by NamsooCho** [comment]
I have intend to work on this issue.
It seems like an intro. to Servo.

**Comment by Wafflespeanut** [comment]
Great! Please let us know if you're stuck somewhere :)

**Comment by Manishearth** [comment]
https://github.com/Manishearth/stylo-flat/pull/1/files
