### ISSUE TITLE
Floats fails to interact with inline elements in the simplest case

### ISSUE THREAD

**Issue by stshine** [servo/servo#13683]
Minimal test case:

``` html
<!DOCTYPE html>
<html>
    <body>
        <span>Bar</span>
        <div style="float: left;">Foo</div>
    </body>
</html>
```

The `Foo` item does not float upside in servo.

**Comment by stshine** [comment]
cc @pcwalton

**Comment by pcwalton** [comment]
Wow, how do we not have a reftest for this?

**Comment by stshine** [comment]
That also surprised me.

**Comment by stshine** [comment]
That also surprised me.

**Comment by stshine** [comment]
This happens because during in-order traversal the parent block calls into child `InlineFlow`'s `assign_block_size_for_inorder_child_if_necessary()` method, which is default method of `Flow` trait that only recalculate height when there is speculated floats. Need to understand in-order traversal and floating better to give out a proper fix.
IMO the name 'assign_block_size_for_inorder_child_if_necessary' is confusing since a child flow called this method on itself. Maybe rename it to `assign_block_size_inorder` ?

**Comment by notriddle** [comment]
That's only part of the problem. I tried hard-wiring `might_have_floats_in` to `true`, and it made no difference. In the block placement pass (which is also responsible for float placement, because float placement depends on block placement and block placement also depends on float placement), the block position of a floating box is assigned to `cur_b`, and `cur_b` is always assigned to the bottom of the previous flow's border box, even if it's an inline flow. This means, in the test case given, Bar gets placed, then Foo gets placed immediately below it.

**Comment by pcwalton** [comment]
As I mentioned on IRC, we need a new type of inline fragment that represents the float ceiling for an inline float (say, `InlineFloatCeiling`). It'd be similar to `InlineAbsoluteHypothetical`. When the LineBreaker goes to lay out this fake fragment, it'd trigger `place_float` for the appropriate float.

**Comment by notriddle** [comment]
Does construct need to place floats sometimes inline sometimes block? Or can it always place floats in an inline flow?

**Comment by pcwalton** [comment]
I think it's fine to place floats as block flows unless they're actually in the middle of an inline. But it may be simpler to handle the case in this bug as though it were such a float in the middle of an inline.

**Comment by pcwalton** [comment]
In other words, there should never be a need to create a brand new inline flow *just* to place a float.

**Comment by stshine** [comment]
Damn, it took three weeks even before I realize the actual complexity of this problem...

**Comment by notriddle** [comment]
Isn't @pcwalton rewriting the entire float subsystem? I've been holding off on doing anything float-related until he's done with it.

**Comment by pcwalton** [comment]
Yes, I'm working on this.

**Comment by stshine** [comment]
Oh, I came up with my naive implementation today which just unfortunately considered the last line(and borrow checker hit me so hard :/), and after some experiments and read https://github.com/dbaron/inlines-and-floats @pcwalton mentioned yesterday on irc, I realized where the actual problem lies. This work is still very valuable to me since it helped me much in understanding how inline and floats work.  I will try to finish my work for educational purpose(and things somehow get simpler when you realize that you have to write a large chunk of code), and look forward to @pcwalton's patch, it would be simply awesome if it can solve this problem in a natural way!

**Comment by notriddle** [comment]
@pcwalton ... how's it going?

**Comment by stshine** [comment]
@notriddle he is on pto till monday.

**Comment by nox** [comment]
This still happens.

@pcwalton Are you still working on this..?

**Comment by pcwalton** [comment]
I think this will be easier to resolve with the reflow revamp @mbrubeck is experimentally working on.

**Comment by mrobinson** [comment]
This appears to be working in non-legacy layout, so I'm going to go ahead and close this one. This is part of our effort to start closing bugs that only affect legacy layout. Apologies for the noise.
