### ISSUE TITLE
Make ServoParser store a VecDeque for its pending input

### ISSUE THREAD

**Issue by nox** [servo/servo#13690]
One should wait for https://github.com/servo/servo/pull/13675 to land first.

The field `ServoParser::pending_input` should be a `DOMRefCell<VeqDeque<String>>`, this lets us use `VecDeque::pop_front` instead of `Vec::remove` in `ServoParser::take_next_input_chunk`.

Files:
 * components/script/dom/servoparser/mod.rs

**Comment by gterzian** [comment]
Ok I'd like to take a pass :)

**Comment by nox** [comment]
Sure! Be sure to wait for #13675 or at least to base your work on top of it.

**Comment by gterzian** [comment]
@nox cheers 👍

**Comment by gterzian** [comment]
By the way I am still working on this one https://github.com/servo/servo/issues/13249#issuecomment-253247742, so if anything wants to take this one, please just let me know...

**Comment by gterzian** [comment]
@nox https://github.com/servo/servo/pull/13785 😄
