### ISSUE TITLE
Implement string-valued text-overflow in Servo

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13709]
Part of #13702

In #13701, we added support for parsing the full range of values that `text-overflow` supports. However, [this is disabled in Servo mode](https://github.com/Manishearth/servo/blob/ea765688cbc7a7f5e223cf060f2bf1341dfa0ae5/components/style/properties/longhand/text.mako.rs#L15)

While supporting the two-value form of text-overflow (e.g. `text-overflow: "..." clip`) is cumbersome, it should be pretty straightforward to support the one-value form.

Steps:
- Remove the conditional in https://github.com/Manishearth/servo/blob/ea765688cbc7a7f5e223cf060f2bf1341dfa0ae5/components/style/properties/longhand/text.mako.rs#L15 , and use the `<%helpers:longhand ...` one unconditionally.
- Try compiling it. Layout will probably fail in [`push_fragment_to_line()` in `components/layout/inline.rs`](https://github.com/servo/servo/blob/b9bd15ebb0e84b48d5b0e7d1e952a911960d4fef/components/layout/inline.rs#L691), because `text_overflow::clip`/`text_overflow::ellipsis` are now `text_overflow::Side::Clip`/`text_overflow::Side::Ellipsis`, and what used to be an enum is now a struct. Match on `fragment.style().get_text().text_overflow.first` instead, and use  the new names for the variants.
- Make it possible to pass arbitrary strings to [`transform_into_ellipsis()`](https://github.com/servo/servo/blob/b9bd15ebb0e84b48d5b0e7d1e952a911960d4fef/components/layout/fragment.rs#L1013) as an argument. In `push_fragment_to_line()` add an extra match arm that is similar to the ellipsis one, but pushes a string. In the ellipsis one, pass "…".
- Test that the [lorem ipsum example on MDN works](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)

Relevant layout code: [`components/layout/inline.rs`](https://github.com/servo/servo/blob/b9bd15ebb0e84b48d5b0e7d1e952a911960d4fef/components/layout/inline.rs#L691) , [`components/layout/fragment.rs`](https://github.com/servo/servo/blob/b9bd15ebb0e84b48d5b0e7d1e952a911960d4fef/components/layout/fragment.rs#L1013)

Tests: None, but we will add some when this is done.

**Comment by Manishearth** [comment]
@notriddle @jdm does this look like E-easy material? I tried to break it into steps to make it easier to work on.

**Comment by jdm** [comment]
I would call it E-less easy.

**Comment by cynicaldevil** [comment]
I'll take a look at this one.

**Comment by Manishearth** [comment]
Cool! Let us know if you need help!

**Comment by Manishearth** [comment]
@cynicaldevil Any updates? I got a ping from you yesterday but you weren't around when I came back online. Feel free to ask any questions here.

**Comment by cynicaldevil** [comment]
@Manishearth I get a `Could not find Side in style::computed_values::text_overflow` error for both match arms. I don't know what's wrong, because the `text-overflow` module *does* contain a `Side` enum, according to `mako.rs`.

**Comment by Manishearth** [comment]
`style::properties::text_overflow` contains it. The computed value module does not.

**Comment by cynicaldevil** [comment]
Negative on that as well.

**Comment by Manishearth** [comment]
Could you put your code somewhere and pastebin the error?

**Comment by Manishearth** [comment]
Also, did you remove the conditional as was mentioned in the first point above?

**Comment by Manishearth** [comment]
https://github.com/Manishearth/servo/blob/ea765688cbc7a7f5e223cf060f2bf1341dfa0ae5/components/style/properties/longhand/text.mako.rs#L15 should not be there anymore, you need to change it to unconditionally use the `helpers:longhand` version

**Comment by cynicaldevil** [comment]
Yes, I'd removed the conditional statement.

**Comment by cynicaldevil** [comment]
`https://github.com/cynicaldevil/servo/commit/74c89e61eece0df4d19ba76996de4ce0238e08bc`
Error:
```
error[E0433]: failed to resolve. Could not find `text_overflow` in `style::properties`
   --> /home/nikhil/workspace/mozilla/servo/components/layout/inline.rs:692:13
    |
692 |             properties::text_overflow::Side::Clip => {}
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `text_overflow` in `style::properties`

error[E0433]: failed to resolve. Could not find `text_overflow` in `style::properties`
   --> /home/nikhil/workspace/mozilla/servo/components/layout/inline.rs:693:13
    |
693 |             properties::text_overflow::Side::Ellipsis => {
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `text_overflow` in `style::properties`
```

**Comment by Manishearth** [comment]
It's `properties::longhands::text_overflow`, sorry.

**Comment by cynicaldevil** [comment]
Copied from IRC:
 I tried to do something like this; but the `ref string` is forcing a borrow of `fragment` which is not being returned. I don't get why this is happening.
```
        let passed_str: Option<&str> = match fragment.style().get_text().text_overflow.first {
            longhands::text_overflow::Side::Clip => None,
            longhands::text_overflow::Side::Ellipsis => {
                need_ellipsis = fragment.margin_box_inline_size() > available_inline_size;
                Some("...")
            }
            longhands::text_overflow::Side::String(ref string) => {
                need_ellipsis = fragment.margin_box_inline_size() > available_inline_size;
                Some(string)
            }
        };
```

**Comment by jdm** [comment]
What's the error message that you get?

**Comment by cynicaldevil** [comment]
```
error[E0505]: cannot move out of `fragment` because it is borrowed
    |
691 |         let passed_str: Option<&str> = match fragment.style().get_text().text_overflow.first {
    |                                              -------- borrow of `fragment` occurs here
...
704 |             self.push_fragment_to_line_ignoring_text_overflow(fragment, layout_context);
    |                                                               ^^^^^^^^ move out of `fragment` occurs here

```

**Comment by jdm** [comment]
Can you scope passed_str so that it is dropped before line 704?

**Comment by cynicaldevil** [comment]
I can't do that, because I have to pass it to a function call which occurs after line 704.

**Comment by jdm** [comment]
In that case it's not possible to hold on to a pointer derived from `fragment` after it gets moved.

**Comment by Manishearth** [comment]
There's no need to try and borrow it in this case, just store an `Option<String>`.  The function it gets passed to calls `.to_owned()` on it anyway.
