### ISSUE TITLE
webgl: uninitialized data leak from renderbufferStorage()

### ISSUE THREAD

**Issue by anholt** [servo/servo#13710]
The FBO support I'm going to propose to merge won't do zero-initialization of renderbuffers initially.  This will certainly leak other graphics content from the process, but may also leak general user memory contents, depending on the driver implementation.  Since renderbuffers don't take in initial data like we do for textures, it's not easy to fix.  I came up with three possible solutions:
### Zero-initialize at creation using glClear().

This is invasive to the GL state: we need to make a new FBO, bind it, attach this renderbuffer to it, set the clear color/depth/stencil value, clear it, then restore the previous FBO state and clear color when we're done.
### Zero-initialize at first bind.

We could skip the FBO generation part of the previous solution if we delayed clearing until an FBO was bound with the renderbuffer attached.  All operations interacting with FBO contents (draws and readback) will check framebuffer status, and we go walking the attachments at that point, so we could just say "oh, an uninitialized RB at status check time?  Let's set the clear state, clear it, and restore clear state."
### Backing using textures instead

I had a thought that we could maybe just use GL textures to back WebGL renderbuffers, so we could zero-initialize in the same way as we do for WebGL textures.  However, unless we were to use packed depth/stencil, we couldn't represent stencil RBs as textures.

**Comment by glennw** [comment]
Relevant reference in gecko code - https://dxr.mozilla.org/mozilla-central/source/dom/canvas/WebGLTypes.h#36

**Comment by anholt** [comment]
After a few reference follows, found https://dxr.mozilla.org/mozilla-central/source/dom/canvas/WebGLFramebuffer.cpp#1149 -- looks like the "Zero Initialize at first bind" option.

**Comment by nox** [comment]
What's the status on this? @anholt Did your changes land in the end?

**Comment by anholt** [comment]
My FBO support landed, so this issue exists (unless someone else has fixed it since then).

**Comment by nox** [comment]
Should we go for the same strategy as Gecko?

**Comment by anholt** [comment]
Yeah, I think the gecko strategy would be easiest.

**Comment by nox** [comment]
https://dxr.mozilla.org/mozilla-central/source/dom/canvas/WebGLFramebuffer.cpp#1222

**Comment by jdm** [comment]
Tests are still disabled since they don't pass yet.
