### ISSUE TITLE
Remove ResponseAction

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13717]
It seems to be mostly, if not entirely, redundant with `FetchResponseMsg`.

**Comment by KiChjang** [comment]
This looks like it's not even being referenced/used anywhere else except for one file location. We'll need to be careful about how we translate the existing enum to `FetchResponseMsg`, however.
Code: `components/net/image_cache_thread.rs`
No need for tests; if it compiles, it's good for a PR.

**Comment by deror1869107** [comment]
Hi! I would like to work on this issue.

**Comment by KiChjang** [comment]
Go right ahead! Ask questions here or on `irc.mozilla.org` at #servo if you have any!
