### ISSUE TITLE
Remove / fix CollectMemoryReports from compositor

### ISSUE THREAD

**Issue by glennw** [servo/servo#13735]
These don't report anything useful one the rust-layers removal lands. Fix it to report something useful or remove it.

**Comment by jdm** [comment]
Let's go ahead and remove all of the code in `compositor.rs` related to:
* sending the `RegisterReporter` message
* sending the `UnregisterReporter` message
* the `mem_profiler_chan` member of `IOCompositor` (we can move the code that sends the ProfilerMsg::Exit message into `Constellation::handle_exit` instead)

Code: `components/compositing/compositor.rs`, `components/constellation/constellation.rs`

**Comment by MichaelKohler** [comment]
I'll take this one :)

**Comment by jdm** [comment]
Wonderful! Please ask questions if anything's unclear!
