### ISSUE TITLE
Support scrolling to fragment point with webrender.

### ISSUE THREAD

**Issue by glennw** [servo/servo#13736]

**Comment by larsbergstrom** [comment]
Gonna need this for the all-important *actual* ACID2 pass (http://acid2.acidtests.org/#top ), which I think was why @june0cho originally prioritized the work on it in the old renderer. Probably not a huge deal, unless we need to report ACID2 status again for some reason :-)

**Comment by glennw** [comment]
@mrobinson I held off on this, since the old functionality relied on layer IDs etc that have all been changed with your scroll root / display list changes. Are those changes at a point now where this could be re-implemented? Is it something you have time to work on?

**Comment by mrobinson** [comment]
@glennw Sure. I was taking a look at this the other day. I think that this could be done pretty easily with ScrollRootIds.
