### ISSUE TITLE
Remove image_data field from CanvasPixelData

### ISSUE THREAD

**Issue by glennw** [servo/servo#13734]
This can be done once the removal of the old render system lands.

**Comment by jdm** [comment]
Code: `components/canvas_traits/lib.rs`

**Comment by dbrgn** [comment]
I'll give this a stab as part of the Swiss Hackathon :)

**Comment by jdm** [comment]
Great!

**Comment by dbrgn** [comment]
The tests seem to take ages to compile and run. Is there a way I can run a subset of the tests specific to this issue?

**Comment by jdm** [comment]
If this builds, I would be fine with making a PR and running the tests on our build machines instead.

**Comment by dbrgn** [comment]
[This](https://github.com/dbrgn/servo/commit/94183ffafed0d6ec2d82f1aa76aab8301a2cf703) is the current state, but now it complains about this:

```rust
error: no field `image_data` on type `canvas_traits::CanvasPixelData`
   --> /home/danilo/Projects/servo/components/script/dom/htmlcanvaselement.rs:210:35
    |
210 |                     => pixel_data.image_data.to_vec(),
    |                                   ^^^^^^^^^^ did you mean `image_key`?

error: aborting due to previous error
```

I'm not sure I can remove that as well...

**Comment by jdm** [comment]
Hum. I believe we need to use the webrender API to retrieve the pixel data using the image key? @glennw Any suggestions how to do that?

**Comment by glennw** [comment]
@jdm This is more a question for @emilio  :)

**Comment by emilio** [comment]
@jdm If it's completely needed, in the case of the webgl context you should be able to use the same path that readPixels (sending a command to WR). In the 2d canvas case it would need to use the draw target, there's code that does that also. 

I'm not in front of my computer right now, I'll try to give more details when I am if needed :)

**Comment by emilio** [comment]
But I believe the pixels in the 2d display item can go away with WR too.

**Comment by dbrgn** [comment]
The thing is that I don't really understand the code I was editing (I'm not very familiar with Canvas), so I'm not sure if I'm the right person to remove things from here :)

**Comment by emilio** [comment]
So this ended up not being as trivial as I thought because we were using `LayoutMsg`s to get the pixels from script.

**Comment by emilio** [comment]
@dbrgn Mind if I take this one?

**Comment by dbrgn** [comment]
@emilio sure, go on!

**Comment by jdm** [comment]
Sorry @dbrgn! I assumed this would be less complex than it turned out to be.

**Comment by dbrgn** [comment]
No problem :) But at least I got to know the build process a bit.
