### ISSUE TITLE
Invert conditional and return early for report_pending_exception

### ISSUE THREAD

**Issue by jdm** [servo/servo#13746]
We check if an exception is pending and do nothing if it is not. We can remove a level of indentation if we invert the check and return immediately.

Code: `components/script/dom/bindings/error.rs`

No need to run any tests; if it builds, that's good enough for a PR.

**Comment by fhartwig** [comment]
I would like to do this.

**Comment by KiChjang** [comment]
Great! Ask questions here or on `#servo` at `irc.mozilla.org` if you're unsure of what to do.
