### ISSUE TITLE
Switch to mozilla-ca-certs crate instead of manually extracting certs from mozilla-central

### ISSUE THREAD

**Issue by jdm** [servo/servo#13749]
This was created by @jld and looks like it might be a nice improvement if we can integrate it with openssl: https://crates.io/crates/mozilla-ca-certs

**Comment by nox** [comment]
Cc @avadacatavra

**Comment by jdm** [comment]
If we're going to do this, https://github.com/rustls/webpki-roots is probably a better choice since it looks like it's actually kept up to date.

**Comment by dvtkrlbs** [comment]
I can take a stab at this
