### ISSUE TITLE
Implement parsing/serialization for text-combine-upright property

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13769]
See: https://developer.mozilla.org/en-US/docs/Web/CSS/text-combine-upright

It has a grammar `none | all | [ digits <integer>? ]`

This property is similar to [`z-index`](https://github.com/servo/servo/blob/master/components/style/properties/longhand/position.mako.rs#L15); it will be an `enum {None, All, Digits(u32)}`. You can copy the longhand block for z-index as a starting point, though the `number_of_zero()` function isn't necessary.

The property should be added to https://github.com/servo/servo/blob/master/components/style/properties/longhand/text.mako.rs

For this to compile, you may need to temporarily add the property name to `stub_longhands` in `gecko.mako.rs`. Alternatively, you can compile Servo directly (`cd servo; ./mach build -d` if you are in a stylo clone)

Parser docs are at https://doc.servo.org/cssparser/parser/struct.Parser.html if you need them.

Let me know if you have any questions!

Assigned to @joewalker

**Comment by upsuper** [comment]
Hmmm, but Gecko doesn't support `digits` yet... Do you have a way to pref it off?

**Comment by upsuper** [comment]
And because of lack of implementation interest, `digits` is now at-risk for this level of spec, and it is unclear whether it will be kept in its current form. Probably just implementing `none | all` is enough.

**Comment by Manishearth** [comment]
it works behind `layout.css.text-combine-upright-digits.enabled` , no?

**Comment by Manishearth** [comment]
Oh, it isn't.

In this case this is a basic keyword property like the last one. @joewalker do you still want to work on this, or would you like something more complicated to look into? (background-blend-mode is interesting, the style bits are easy but the gecko glue is trickier)

**Comment by upsuper** [comment]
No. That pref only enables the parsing of the property. No layout support yet.

(That's why I said adding parser support without actually implementing in layout is harmful.)

**Comment by joewalker** [comment]
It's probably not fair to keep this C-assigned. I may get to it, but anyone should feel free to take it off me.

**Comment by pyfisch** [comment]
@highfive: assign me

**Comment by canaltinova** [comment]
It's implemented in #14771. Closing this.
