### ISSUE TITLE
Implement "list of options" concept on HTMLSelectElement

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#13763]
https://html.spec.whatwg.org/#concept-select-option-list

Add a new `list_of_options` (or maybe just `options`) function on [`HTMLSelectElement`](https://github.com/servo/servo/blob/master/components/script/dom/htmlselectelement.rs) and use it everywhere appropriate in that file [instead of doing things like this](https://github.com/servo/servo/blob/a80abf6c1dd0f14b40499d55129a53d397c3a3cd/components/script/dom/htmlselectelement.rs#L97).

**Comment by Manishearth** [comment]
Also, we currently do `node.traverse_preorder()....`

We should be looking for direct children (and direct children of direct `optgroup` children) only.

**Comment by Manishearth** [comment]
This might need you to construct a custom iterator type. Not sure if it's really easy.

**Comment by frewsxcv** [comment]
PR opened: #14085
