### ISSUE TITLE
location.replace is not implemented

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#13768]
Ran into a page which didn't work because `location.replace` doesn't exist.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/13418/

**Comment by jdm** [comment]
Duplicate of #13413. Thanks for filing!

**Comment by bzbarsky** [comment]
For what it's worth, I did search issues for location.replace before filing....  The title of the other one is not very discoverable.
