### ISSUE TITLE
We don't preserve the original declared value of `Image` if it's not a valid URI.

### ISSUE THREAD

**Issue by emilio** [servo/servo#13779]
See #13778. Right now we try to parse it as a `rust-url` `Url`, but if we fail we replace the url with `about:invalid`, which is wrong. We should preserve it, specially taking into account stylo and its integration with the developer tools.

cc @bholley @Manishearth @SimonSapin

**Comment by nox** [comment]
What is this about, and did it change with Stylo?

**Comment by SimonSapin** [comment]
This is fixed, we do preserve the original string in `SpecifiedUrl` now.
