### ISSUE TITLE
.snap version for Ubuntu and other Linux distribution

### ISSUE THREAD

**Issue by pharaone** [servo/servo#13773]
Why you don't create a snap of servo?

**Comment by jdm** [comment]
The reason is that we're not putting much effort into making Servo available beyond download.servo.org at the moment. That being said, we have accepted PRs to add other distribution methods like homebrew if other people agree to maintain them.

**Comment by nox** [comment]
Closing this for the same reason we closed all similar tickets. Feel free to make your own snap package and add references to this in a PR to `README.md`.
