### ISSUE TITLE
Better heuristics for build parallelism

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#13770]
Doing a `./mach build -r` on current tip I'm seeing:

> % uptime
> 10:38  up 33 days, 10:24, 1 user, load averages: 20.93 25.02 15.41

I see a number of rustc processes and clang processes all running at once (8 or so of each) for part of the compile while SpiderMonkey is being built.  But even when there are no clang processes and only 4-5 rustc processes the load average is still in the 20s.  Presumably each rustc is using multiple threads.

This is a 4-core machine, so the main effect of all this is to make it impossible to do anything else while compiling servo.  Probably slows down the compile too, due to thrashing.

**Comment by metajack** [comment]
As a workaround you can do -j1 or -j4 or whatever to control the max parallelism. Unfortunately there is no way currently to have cargo and gcc/clang share the same process pool, so even with -j4 you could end up with 4 invocations of a crate compile each compiling C code with -j4.

I believe the default parallelism value is set to $num_cores, but if you are hyperthreaded it may be double that.

I have not noticed significant performance degradation of the rest of my system from default compiles except on Windows.

**Comment by nox** [comment]
We are all aware that building Servo is very expensive, no need keeping this open.

**Comment by bzbarsky** [comment]
The problem is not "expensive".   Compiling Firefox is "expensive" but doesn't lock up the computer like this.

The problem here is that the servo build process starts way, way more threads than there are hardware execution threads, which is broken.

**Comment by nox** [comment]
Seems like what you want is a better, tuned-down -j flag passed automatically without you having to remember passing it.

**Comment by SimonSapin** [comment]
Cargo now implements a "jobserver" compatible with GNU make to limit overall parallelism. (See `NUB_JOBS` in http://doc.crates.io/environment-variables.html) Does SpiderMonkey’s build system not pick up the relevant environment variable?

**Comment by nox** [comment]
http://logs.glob.uno/?c=mozilla%23servo&s=5+Oct+2017&e=5+Oct+2017#c763401

**Comment by bzbarsky** [comment]
This is not just a SpiderMonkey issue.  See initial description: even the pure-rustc section had a load average of 20 back when I filed this.

I'm testing this now with a current tip, just in case.  I get load averages of around 60 (on a 4-core, hyperthreading machine).  There are ~6 rustc live at a time, plus ~20 clang invocations spread across spidermonkey and osmesa.

**Comment by SimonSapin** [comment]
I’m pretty sure the jobserver was added after this bug was originally filed. @bzbarsky, could you try and see if this also happens with `./mach build-geckolib`? IIRC that only compiles Rust code, so we should be able to tell if the jobserver is buggy or if the issue is only with subprocesses started from build script (compiling C/C++ code).

**Comment by bzbarsky** [comment]
With `./mach build-geckolib` the load average is at about 3-4.  I typically see only one rustc process running, using "250-400%" CPU (so figure 2.5-4 cores).

It's also a _much_ shorter build than all of servo, of course; looks like about 2 mins for a debug build when I just tried.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/cargo/pull/4110
> Unfortunately crates are unlikely to see an immediate benefit of this once
implemented. Most crates are run with a manual `make -jN` and this overrides the
jobserver in the environment, creating a new jobserver in the sub-make. If the
`-jN` argument is removed, however, then make will share Cargo's jobserver and
properly limit parallelism.

**Comment by metajack** [comment]
That sounds very easy to fix.

**Comment by Eijebong** [comment]
Here's a list of PRs to use the new cargo jobserver (cc @nox):
- [ ] https://github.com/servo/libfontconfig/pull/34
- [ ] https://github.com/servo/rust-harfbuzz/pull/81
- [ ] https://github.com/alexcrichton/backtrace-rs/pull/71
- [ ] https://github.com/alexcrichton/libz-sys/pull/26
- [ ] https://github.com/servo/osmesa-src/pull/21
- [ ] https://github.com/servo/mozjs/pull/123

**Comment by SimonSapin** [comment]
This appears to be completed.
