### ISSUE TITLE
Consider refcounting the document Url.

### ISSUE THREAD

**Issue by emilio** [servo/servo#13790]
We clone it a zillion times, which is probably not a problem in most cases, but can become a bottleneck when the document URL is a data-uri.

We should also look into doing the same for the base url, etc.

What do you think about this @jdm, @Ms2ger, @nox? Seems like an easy work.

**Comment by craftytrickster** [comment]
I think @jdm would agree with you :) 

https://github.com/servo/servo/issues/9782

**Comment by Ms2ger** [comment]
I'd probably be fine with that, depending on how exactly it ends up looking.

**Comment by adrm** [comment]
I would like to contribute to servo and learn rust. Could I take this issue?

**Comment by emilio** [comment]
Sure, let us know if you need any help! :)

**Comment by KiChjang** [comment]
@adrm Are you still working on this?

**Comment by adrm** [comment]
I'm willing to start on it next week. If you need to close it ASAP please feel free to take it from me. Sorry for being unresponsive this time.

**Comment by KiChjang** [comment]
@emilio I think this is solved by urlmageddon, yes?

**Comment by nox** [comment]
We now use `ServoUrl` which contains an `Arc`.
