### ISSUE TITLE
Webdriver screenshot command timeout

### ISSUE THREAD

**Issue by kanaka** [servo/servo#13826]
I'm running servo nightly 20161013 on Ubuntu 14.04.5.

I start servo like this:
```
./servo --webdriver 7000 --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref shell.builtin-key-shortcuts.enabled=false build/browserhtml-5c846c4e388d17ec/out/index.html
```

Then I make the following webdriver calls:

```
curl -v -X POST -d '{"desiredCapabilities": {}}' http://localhost:7000/session
SESSION_ID=...
curl -v -X POST -d '{"url":"http://github.com"}' http://localhost:7000/session/${SESSION_ID}/url
curl -v http://localhost:7000/session/${SESSION_ID}/screenshot -o screenshot.png.b64
```

The second call successfully loads github.com, but the third call to take a screenshot times out after 49 seconds with `HTTP/1.1 408 Request Timeout` and the output (caputure in the file) is:
```
{"error":"timeout","message":"Taking screenshot timed out"}
```

I.e. I believe it is hitting [this](https://github.com/servo/servo/blob/f4ed2c6875e4f766b4de93263a25431424215f73/components/webdriver_server/lib.rs#L794) error for some reason.

Note that the same sequence of webdriver calls works with phantomjs and slimerjs.

**Comment by jdm** [comment]
I can reproduce this by running `./servo http://joshmatthews.net --webdriver 7000`, getting the session ID and then taking a screenshot. Very interesting.

**Comment by jdm** [comment]
Nevermind, the screenshot took longer than I expected to finish, but it did. I definitely waited for >1.5 minutes doing the same operation on github, however.

**Comment by jdm** [comment]
No, actually the "screenshot" I received was the request timeout JSON.

**Comment by jdm** [comment]
Aha - the constellation believes the document has not finished loading, because the code in Window::reflow that sends the idle message is never reached, since it's guarded by code that assumes we only care about taking screenshots in certain situations that are used when running automated tests.

**Comment by kanaka** [comment]
@jdm Awesome! I would verify this right now but at some point after b8874ff7d197af8e0c7c23c6aced4d8a8fce1648 (Aug 28), `./servo -z ...` started throwing `Could not open dynamic library \`OsMesa\`` and I'm in the process of bisecting that at the moment.

**Comment by jdm** [comment]
Sounds like you're hitting #13515, which can be worked around with https://github.com/servo/servo/issues/13515#issuecomment-250592787 .
