### ISSUE TITLE
transform with translateZ & rotateY is rendered incorrectly

### ISSUE THREAD

**Issue by Gozala** [servo/servo#13822]
Here is an example https://jsbin.com/qokayi/edit?html,css,js,output you can try out by running

```
servo -w https://output.jsbin.com/qokayi
```

Values of the input is applied as `translateZ`. As you decrease the number rendering becomes increasingly incorrect. With a number like `-3000` no blue box is rendered at all.

**Comment by Gozala** [comment]
#13819

**Comment by glennw** [comment]
cc @kvark

**Comment by glennw** [comment]
Findings so far:

There's at least two bugs in play here. The first one is what I was expecting. There are some known issues with clipping + scroll regions + 3d transforms. @mrobinson is working on the "proper" fixes / refactoring for this stuff now. However, it's going to take a couple of weeks (estimated). I *think* I can make some temporary changes that work around the bug in these cases and continue to pass all tests.

The second bug appears to be in Servo itself - the overflow: hidden in this case makes the display item get removed from the display list altogether. I'm looking into this part now.

**Comment by glennw** [comment]
The second problem is that ```switch_coordinate_system_if_necessary``` in ```block.rs``` doesn't work correctly for non-2d transforms.

I'm not sure that this can be worked around, without fixing it properly once and for all. I'll discuss this bug (and the other two linked bugs) with @mrobinson and we'll work out exactly what the best way forward is.
