### ISSUE TITLE
Write parse tests for linear gradients

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#13837]
We have parse tests for radial gradients' parsing. Linear gradients are simpler than radial ones and probably require lesser tests.
To add parse tests, you can add a new test function to `tests/unit/style/parsing/image.rs` and with `assert_roundtrip_with_context!` macro, compare the left gradient with right parsed ones. Implementation is pretty much same with radials except examples.

Linear gradient examples can be found at: https://drafts.csswg.org/css-images/#funcdef-linear-gradient

To run test you can use `./mach test-unit -p style` command.

**Comment by jdm** [comment]
@AVGP Please do! Ask questions here if anything is unclear!

**Comment by AVGP** [comment]
What's up with Travis? Is this DNS-DDoS fallout?

**Comment by canaltinova** [comment]
Yeah, probably because of DNS attack. Also highfive is not working properly.
