### ISSUE TITLE
Remove URL.domainToASCII and URL.domainToUnicode

### ISSUE THREAD

**Issue by nox** [servo/servo#13835]
They were removed from the spec.

https://twitter.com/urlstandard/status/788712433934270464

Files:
 * components/script/dom/url.rs
 * components/script/dom/webidls/URL.webidl

**Comment by Ms2ger** [comment]
We should ensure there is a test that these methods are not supported. `url/historical.html` and `url/historical.worker.js` are perfect.

**Comment by ddrmanxbxfr** [comment]
I'd like to work on this issue.

@Ms2ger Just to make sure I test the good thing. An unsupported method means that both will be undefined right ?

**Comment by jdm** [comment]
@ddrmanxbxfr That is correct!
