### ISSUE TITLE
Implement parsing/serialization for -webkit-text-stroke property

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13849]
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke

The grammar is `<integer> <color>`, which means that it must be an integer followed by a color.

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs. This bug requires familiarity with Rust.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/inherited_text.mako.rs

**Comment by AgostonSzepessy** [comment]
I'd like to try this one.

**Comment by Manishearth** [comment]
Go ahead!

**Comment by AgostonSzepessy** [comment]
@Manishearth I have a a few questions about implementing `<color>`. For `<rgb()>` should I use `cssparser::RGBA` with `A` set to 1, and for `<rgba()>` should I use `cssparser::RGBA`? For `<deprecated-system-color>` should I create an `enum` with all the values listed on MDN? Also, is there a data structure for storing HSL and HSLA or do I need to create one?

**Comment by Manishearth** [comment]
You don't need to implement color, it already exists as a type, like Length. See how backgroubd-color in background.mako.rs does it.

**Comment by AgostonSzepessy** [comment]
@Manishearth I'd like to make sure that I'm implementing this correctly. I have

```
pub struct StrokeValues {
    pub length: Length,
    pub color: Color,
}

pub enum SpecifiedValue {
    Default,
    Specified(StrokeValues),
}

pub mod computed_value {
    use super::StrokeValues;
    pub struct T(Option<StrokeValues>);
}
```
In `computed_value`, should I be using a struct instead of a tuple struct, or is what I have correct?

**Comment by Manishearth** [comment]
I'm sorry. I just realized that this is a shorthand, not a longhand, and we won't need this implemented till the longhands are. Feel free to pick up a different open bug.

**Comment by chenpighead** [comment]
Hi @Manishearth, I'm wondering maybe we could implement both shorthand and longhand in this issue, if we do want this property eventually.

**Comment by Manishearth** [comment]
Yes,

**Comment by chenpighead** [comment]
Hi @AgostonSzepessy, are you still planning to work on this?

**Comment by AgostonSzepessy** [comment]
@chenpighead No, you can take this issue if you want.

**Comment by chenpighead** [comment]
Ok, thanks. I'll start to work on this next week.

**Comment by chenpighead** [comment]
I've finished the parsing/serialization part. Will continue to work on gecko glue and feature verification on Stylo.

**Comment by Wafflespeanut** [comment]
Well, you can open a PR (with a note of WIP at the top) :)

**Comment by chenpighead** [comment]
@Wafflespeanut, thank you for the pointer. I'll use WIP note next time. :)
