### ISSUE TITLE
Implement parsing/serialization for text-emphasis-style

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13853]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/inherited_text.mako.rs

The syntax is: `none | [ [ filled | open ] || [ dot | circle | double-circle | triangle | sesame ] ] | <string>`

This means it can be `none`, a quoted string, or  `[ [ filled | open ] || [ dot | circle | double-circle | triangle | sesame ] ]`. The `||` means "at least one of in any order", which means that it can be just `filled` or `open`, just `dot` or `circle` or `double-circle` or `triangle` or `sesame`, or one keyword of both kinds, in any order.

The specified value should probably store the keyword pairs as something like

```rust
struct Keyword {
    fill: Option<bool>,
    shape: Option<ShapeKeyword>
}
// Shape is an enum with the dot/circle/etc keywords
```

The computed value can just store a struct with a `bool` and `ShapeKeyword` field. The information of which ones of the fill/shape were specified is important for serialization of specified values, but not for computed. Unspecified fills default to "filled" and unspecified shapes default to "circle" (except in vertical writing modes, but we'll tackle this later).

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs. Familiarity with Rust required for working on this.

**Comment by upsuper** [comment]
FWIW, in Gecko, we truncate the `<string>` to only one [grapheme cluster](https://drafts.csswg.org/css-text/#grapheme-cluster) when generating its computed value.

**Comment by canaltinova** [comment]
I would like to work on this.
