### ISSUE TITLE
Implement parsing/serialization for font-feature-settings

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13852]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings

The grammar is `normal | <feature-tag-value>#` where `<feature-tag-value> = <string> [ <integer> | on | off ]?`, which means that it must be the keyword `normal`, or a comma separated list of feature tag values. Each feature tag value will be a string, which may be followed by an integer, the keyword `on`, or the keyword `off`.

[`parse_comma_separated`](https://doc.servo.org/cssparser/parser/struct.Parser.html#method.parse_comma_separated) will help with parsing the list of feature tag values. I suggest creating a `FeatureTagValue` struct that has a parse method and a ToCss implementation.

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs.

**Comment by rwakulszowa** [comment]
I think I can try to implement this one

**Comment by Manishearth** [comment]
Alright. Let me know if you have questions!

**Comment by rwakulszowa** [comment]
Hey, is this one of the cases where specified and computed values are the same? (like [here](https://github.com/servo/servo/blob/275278be44b96b683bee40a8d8a6462198ec9e39/components/style/properties/longhand/font.mako.rs#L15-L17) )

Also, is there a nice way to store a "non-negative" integer in this module, or should I just use u32 or something like that?

**Comment by Manishearth** [comment]
Yep, the two are the same.

Just use `Number` with `parse_non_negative` https://doc.servo.org/style/values/specified/struct.Number.html#method.parse_non_negative

**Comment by Manishearth** [comment]
Oh, wait, integer, not number.

Use https://doc.servo.org/cssparser/struct.Parser.html#method.expect_integer and just return an error if it's negative.

**Comment by rwakulszowa** [comment]
Ok, my initial attempt [landed](https://github.com/rwakulszowa/servo/commit/54c81d98b47db3201c06481c65eff633d32d64f2). Oddly enough, it compiles :)
There's 1 TODO where I need help figuring out how to capture the parsed integer properly - using `if let Ok(val) = input.expect_integer() ` causes a compiler error "cannot mutably borrow in a pattern guard"
I'm probably doing something dumb :/

Where do I put the tests? The properties test directory structure is weird. I've found some tests for font properties, but they were all commented out.

**Comment by Manishearth** [comment]
> using if let Ok(val) = input.expect_integer() causes a compiler error "cannot mutably borrow in a pattern guard"

You need to `if let Ok(value) = input.try(|input| input.expect_integer()) {}`, and use `else if let` for the next one:

```rust
            pub fn parse(input: &mut Parser) -> Result<FeatureTagValue, ()> {
                let tag = try!(input.expect_string()).into_owned();

                if let Ok(value) = input.try(|input| input.expect_integer()) {
                    // handle integer, throw if it is negative
                    if value >= 0 {
                        Ok(FeatureTagValue{ tag: tag, value: value })
                    } else {
                        Err(())
                    }
                } else if let Ok(_) = input.try(|input| input.expect_ident_matching("off")) {
                    // off is an alias for '0'
                    Ok(FeatureTagValue{ tag: tag, value: 0 })
                } else {
                    // remainders (empty value and "on" keyword) are aliases for '1'
                    Ok(FeatureTagValue{ tag:tag, value: 1 })
                }
            }
```

`if let` and `if` don't mix well right now, but this will get fixed once we have nonlexical lifetimes.

Also, currently you're probably using `./mach build`. This is okay, but in the final patch you will want to have `products="none"` in the longhand. Once you do this the property will stop being used in `./mach build`, and will only be used in `./mach test-unit -p style`.

> Where do I put the tests?

tests/unit/style/parsing/mod.rs or create a module within it.

> attempt landed. 

fwiw "landed" usually means "landed on master" (or some other common integration branch)

**Comment by rwakulszowa** [comment]
Thanks, it worked well!

I fixed some bugs, added some tests, and they pass. Now the question is, should I add some tests for `to_css`, and if so, where do i add them?
I also wanted to add some expect-error kinda tests, but I couldn't find any `assert_err` or anything like that. Is there an idiomatic way to handle this in Rust?

**Comment by Manishearth** [comment]
`assert!(something.is_err())`?

For `to_css` use `assert_roundtrip`, which parses a given string, serializes it, and checks that it's the same as the second string.

**Comment by rwakulszowa** [comment]
Thanks.
By the way, do you think it would make sense to create a macro to expect parsing failure? The current one `unwrap`'s in the end, so it's quite useless for this purpose. Or maybe there's some other way to handle this?
I can create an `easy` issue and guide whoever picks it.

**Comment by Manishearth** [comment]
I don't really see the need, you can `parse("css text", function_name).unwrap()`. The others are macros since they involve multiple steps.
