### ISSUE TITLE
Implement keyword values in border-width

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13869]
Please see the [property hacking guide first](https://github.com/servo/servo/wiki/Property-hacking-guide). Familiarity with Rust required. This is not implementing a new property, just extending an existing one.

For `border-foo-width` (e.g. `border-top-width`), we currently support length values. However, this struct supports keywords too.

We currently parse it as `<length>`, but the full syntax is `<length> | thin | medium | thick`. Now, the keyword values map to integer lengths (Firefox maps them to `1px`, `3px` and `5px` respectively, you can use `Length::Absolute(1).to_computed_value(context)` to get these in `Au`). So you will have to change the `SpecifiedValue` struct so that it can store thin/medium/thick keyword values (as well as lengths), and change `to_computed_value` so that it replaces the keyword values with the stuff specified.

You should be able to test this in Servo directly, just create a div and give it different keyword borders.

**Comment by Manishearth** [comment]
@heycam Gecko stores the constants 1/3/5 in the pres context. Should we be storing them in the computed value context (and fetching them from Gecko in stylo mode)? For this bug I'm just hardcoding them, but we might eventually want to do something else.

**Comment by aethanyc** [comment]
I would like to work on this.

**Comment by Manishearth** [comment]
Great! Let us know if you have questions!

**Comment by heycam** [comment]
Hard coding is fine for now. For Gecko, we probably should just change them to be constants defined somewhere rather than exposed through the `nsPresContext`.

**Comment by aethanyc** [comment]
Any bug filed on gecko for moving those `border-width` constants from `nsPresContext` to elsewhere?

**Comment by heycam** [comment]
There isn't AFAIK. Please feel free to file one!

**Comment by Manishearth** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1312155
