### ISSUE TITLE
Stylo: implement column-rule-style

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13868]
Please go through [the guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide) if you wish to hack on stylo.

[`column-rule-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/column-rule-style)  is a keyword property with the set of possible values being `none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset`. `none` is the default. The constant prefix is [`NS_STYLE_BORDER_STYLE`](https://dxr.mozilla.org/mozilla-central/rev/f0f1aaf051d6798e1e73d1feee07ca847333167a/layout/style/nsStyleConsts.h#408) and the field name is [`mColumnRuleStyle`](https://dxr.mozilla.org/mozilla-central/rev/f0f1aaf051d6798e1e73d1feee07ca847333167a/layout/style/nsStyleStruct.h#3484). We will implement it as `-moz-column-rule-style` in gecko. The example on the MDN page should work once implemented.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/column.mako.rs

**Comment by neeharv** [comment]
I'll take a crack at this.

**Comment by KiChjang** [comment]
Sure thing!

**Comment by Manishearth** [comment]
Any updates?

**Comment by neeharv** [comment]
I'm having a little trouble getting my local changes to compile and run. Is
there an irc channel where I can get help with that or should I post my
issues here?

**Comment by Manishearth** [comment]
#servo on Mozilla's IRC network.

**Comment by KiChjang** [comment]
Unassigning due to inactivity.

**Comment by KiChjang** [comment]
@Razican I think this is a much better issue for you to get started on hacking servo.

**Comment by Razican** [comment]
@KiChjang ok, sure, I'll start with it. Thanks!

**Comment by Razican** [comment]
I'm being unable to make the example in MDN work :/ This is what I see:
![screenshot from 2016-11-27 18-37-54](https://cloud.githubusercontent.com/assets/597469/20650526/bb47e5c2-b4d0-11e6-9795-7e94760b5d86.png)

I implemented this in `components/style/properties/longhand/column.mako.rs`:
```rust
${helpers.single_keyword("column-rule-style",
                        "none hidden dotted dashed solid double groove ridge inset outset",
                        products="gecko",
                        gecko_constant_prefix="NS_STYLE_BORDER_STYLE",
                        animatable=False)}
```

I'm using Linux, not sure if that could affect. In Firefox I see the example like this:
![screenshot from 2016-11-27 18-40-24](https://cloud.githubusercontent.com/assets/597469/20650533/fbe228cc-b4d0-11e6-8f16-73295fadd84f.png)

**Comment by Manishearth** [comment]
Is this in Servo or Stylo?

Also, it might help to extract the example into an independent HTML page.

**Comment by Razican** [comment]
@Manishearth I'm using the stylo git repo. I also tried [the example alone](https://mdn.mozillademos.org/en-US/docs/Web/CSS/column-rule-style$samples/Examples?revision=1047988), and the same happens.

**Comment by Manishearth** [comment]
Oh. The example uses `-moz-column-rule-style`, but the snippet above implements it as `column-rule-style`. Change the example to use `column-count` and `column-rule-style`

**Comment by Razican** [comment]
Perfect, now it works. I'll pull request ASAP.
