### ISSUE TITLE
Implement parsing/serialization for scroll-snap-points-x and scroll-snap-points-y

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13871]
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-points-x

The grammar is `none | repeat(<length>)`. This means that it can either be `none`, or a function `repeat()` containing a length.

[`expect_function`](https://doc.servo.org/cssparser/parser/struct.Parser.html#method.expect_function) and [`parse_nested_block`](https://doc.servo.org/cssparser/parser/struct.Parser.html#method.parse_nested_block) will help with parsing the function. An example of this being used is [here](https://github.com/servo/servo/blob/4216224f9cc7f3430db2b59f4d77061824ba7a1e/components/style/properties/longhand/effects.mako.rs#L374), where it parses the `rect(...)` function.

You should make the `<%helpers:longhand>` block for `scroll-snap-points-y` just reexport the contents of `scroll-snap-points-x`

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs. This bug requires familiarity with Rust.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs

**Comment by iamrohit7** [comment]
I would like to work on this.

**Comment by Manishearth** [comment]
Go ahead, and let us know if you have any questions!

cc @canaltinova

**Comment by iamrohit7** [comment]
@Manishearth Should this be implemented as a Servo feature or a Stylo feature(should `products="gecko"` be specified)? Also, what exactly do you mean by `reexport the contents of scroll-snap-points-x`?

**Comment by Manishearth** [comment]
`products="none"`, with parse tests. I mean that `scroll-snap-points-y` should just `pub use  properties::longhands::scroll_snap_points_x::SpecifiedValue as SpecifiedValue` (etc etc). Use Rust reexports to copy over all the types from scroll-snap-points-x.

**Comment by iamrohit7** [comment]
@Manishearth @emilio just suggested in IRC to implement with products="gecko"

**Comment by Manishearth** [comment]
That's only if you want to handle the gecko glue. In that case, you'll need a stylo build (https://github.com/servo/servo/wiki/Stylo-hacking-guide for build instructions) and the ability to test it. I'm not sure if `scroll-snap-points` can be tested without simultaneously implementing scroll-snap-type

**Comment by iamrohit7** [comment]
@Manishearth I used helpers.single_keyword to generate the code for scroll-snap-type and it generates code which modifies a non-existent mScrollSnapType. Should I implement the Gecko glue myself or implement scroll-snap-type as a shorthand?

**Comment by Manishearth** [comment]
You have to do `scroll-snap-type-x` and `scroll-snap-type-y` (using single_keyword), and adding a shorthand for `scroll-snap-type`, yes.

**Comment by Manishearth** [comment]
You can forgo doing the shorthand, but then the MDN example will have to be tweaked to explicitly use `scroll-snap-type-x` and `scroll-snap-type-y`. You can do this pretty easily, just copy the html/css into a new webpage.
