### ISSUE TITLE
Implement parsing/serialization for image-orientation

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13877]
https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation

The grammar is `from-image | <angle> | [<angle>? flip]`. This means that it can be the keyword `from-image`, an [`Angle`](https://doc.servo.org/style/values/specified/struct.Angle.html), the keyword `flip`, or an angle followed by the keyword `flip`. One way to store it would be as a struct with an `Option<Angle>` field and a boolean flip field, with the `None/false` case representing `from-image`

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs. This bug requires familiarity with Rust.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/inherited_box.mako.rs

**Comment by cers** [comment]
I would like to take a stab at this

**Comment by Manishearth** [comment]
Go ahead!

cc @heycam @canaltinova

**Comment by KiChjang** [comment]
@cers Are you still working on this?

**Comment by cers** [comment]
I am, but I must admit there appear to be some points about either the style system or rust (or both) that I don't quite grasp yet.

Would it be more appropriate to discuss particulars on IRC (as they might pertain more to Rust than to the actual bug), or is it valuable to have such a discussion here?

**Comment by Manishearth** [comment]
IRC is fine.

**Comment by Wafflespeanut** [comment]
@cers Any news?

**Comment by dpyro** [comment]
I take the next stab at it!

**Comment by Wafflespeanut** [comment]
Great! Please  ask questions if you're unclear about something.

**Comment by dpyro** [comment]
@Wafflespeanut Here is what I have so far. I am not sure if the helper metadata is completely correct or how to test this properly.
