### ISSUE TITLE
Implement parsing/serialization for font-size-adjust

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13875]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust

The grammar is `none | <number>`. This means that it can either be the keyword `none`, or a number.

[`values::specified::Number`](https://doc.servo.org/style/values/specified/struct.Number.html) will help with storing and parsing then number.

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/font.mako.rs

**Comment by chenpighead** [comment]
I'd like to work on this.

**Comment by Manishearth** [comment]
Go ahead! 

cc @canaltinova @heycam (in case I'm not around to mentor)

**Comment by Manishearth** [comment]
Unassigning, please let us know if you're still working on this

**Comment by chenpighead** [comment]
Sorry for taking it so long. Just started reading the docs yesterday. Will start to work on a patch from today.

**Comment by Manishearth** [comment]
Okay, thanks!

**Comment by chenpighead** [comment]
Still work on some compile errors while running "./mach build -p style"...

**Comment by chenpighead** [comment]
Oops, just figure that it's a gecko property. Does that means I need to also implement the Gecko bits like set_property and copy_property_from and others as necessary?

**Comment by Manishearth** [comment]
No, implement it with `products="none"`. If you wish to implement it as a gecko property, feel free to try! You'll need to use http://hg.mozilla.org/incubator/stylo to build, though (build steps in https://github.com/servo/servo/wiki/Stylo-hacking-guide), and copy your patches over to a servo clone later.

cc @shinglyu

**Comment by chenpighead** [comment]
That's exactly what the compile errors come from. After I add products="none", everything goes well now. I'll stick with servo only for now.

**Comment by chenpighead** [comment]
@Manishearth, while running "./mach test-unit -p style", I bump into an error as follows:

error[E0308]: mismatched types
   --> /Users/jeremy/servo/components/style/lib.rs:155:5
    |
155 |     include!(concat!(env!("OUT_DIR"), "/properties.rs"));
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected mutable reference, found enum `core::result::Result`
    |
    = note: expected type `&mut cssparser::Parser<'_, '_>`
    = note:    found type `core::result::Result<_, _>`
    = note: this error originates in a macro outside of the current crate 

I'm wondering if I should do something more to pass the unit test? Seems that even setting products="none", the newly added property would still be tested.

**Comment by chenpighead** [comment]
Oops, after I rebase to the latest master, `./mach test-unit -p style` is running successfully and the tests are all passed. No idea what really happened though.

**Comment by Manishearth** [comment]
> Seems that even setting products="none", the newly added property would still be tested.

Yes, `products=none` means that it only gets compiled while testing. `./mach build -p style` will not build this code for products=none.

You probably need some `try!()`s somewhere

**Comment by chenpighead** [comment]
The gecko stuff work is pending due to a git-cinabar issue: https://github.com/glandium/git-cinnabar/issues/95 

I'll start to work on gecko once I could successfully clone the stylo repo. :-/

**Comment by Manishearth** [comment]
https://github.com/manishearth/stylo-flat can be used in the meantime. Or https://github.com/Manishearth/gecko-dev/tree/stylo-tip

**Comment by chenpighead** [comment]
Nice!! If git-cinabar issue is not fixed today, I'll try `stylo-flat` then. Thank you. :-)

**Comment by chenpighead** [comment]
Looks like both stylo and stylo-flat repo are not updated recently. Since my patch (#14125) and other dependencies (ex. #14089) are not merged into stylo's servo yet, I'm not able to test my patches for now. Will verify my patches once the repo has been updated.

**Comment by Manishearth** [comment]
Just apply those patches on the servo directory. The update will happen when the hg repo is synced.
