### ISSUE TITLE
Implement parsing/serialization for font-synthesis

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#13876]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis

The grammar is `none | [ weight || style ]`. This means that it can either be the keyword `none`, or _at least one of the keywords `weight` or `style`. So it can be `none`, `weight style`, `style weight`, `weight` or `style`. You can store it as a simple struct with boolean fields for `weight` and `style`

The `match_ignore_ascii_case!` macro will be useful for parsing, see [this code](https://github.com/servo/servo/blob/bb271ef4afea02b6b1b5d207e773d1fedccd2906/components/style/properties/longhand/font.mako.rs#L162-L167) for an example of usage. Just try to parse it as one of the three keywords, and in case it's weight or style, check if the other keyword is also there using `input.try(|input| input.expect_ident("other keyword"))`.

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs. This bug requires familiarity with Rust.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/font.mako.rs

**Comment by iamrohit7** [comment]
I would like to work on this.

**Comment by Manishearth** [comment]
Go ahead!
