### ISSUE TITLE
Write Step 1 of the Response API `Clone()` method

### ISSUE THREAD

**Issue by jeenalee** [servo/servo#13888]
Response is implemented in `components/script/dom/response.rs`. Step 1 in `Clone()` method is currently missing. While the lower level details are not fully implemented yet, the higher level building blocks required for Step 1 (`self.BodyUsed()` and `self.is_locked()`) are available.

The changes will replace the `TODO` line under Step 1 in `components/script/dom/response.rs`:
```rust
// https://fetch.spec.whatwg.org/#dom-response-clone
fn Clone(&self) -> Fallible<Root<Response>> {
    // Step 1
    // TODO: This step relies on body and stream, which are still unimplemented.
```

According to the [Fetch spec](https://fetch.spec.whatwg.org/#dom-response-clone), Step 1 should:
> 1. If context object is disturbed or locked, then throw a TypeError. 

Throwing a JavaScript `TypeError` in Servo looks like [this](https://github.com/servo/servo/blob/master/components/script/dom/response.rs#L159).

Please read [here](https://github.com/servo/servo/blob/master/tests/wpt/README.md#running-the-tests) about running tests. You can run only the Response API related tests through:
```
./mach test-wpt tests/wpt/web-platform-tests/dom/fetch/api/response/
```
After implementing Step 1, if additional tests start passing, you will have to [update the test expectations](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations).

This will be a great first bug, and I can mentor who's interested!

**Comment by lautat** [comment]
Looks like a perfect first bug to me. I'll work on this issue. Any mentoring would be appreciated.

**Comment by KiChjang** [comment]
Fantastic! Leave a comment here or chat with us in #servo at `irc.mozilla.org` if you have any questions :).

**Comment by jeenalee** [comment]
@lautat Awesome! Please don't hesitate to ask questions!
