### ISSUE TITLE
Use graphemes in text-emphasis-style

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#13894]
Gecko always truncate string values into a single grapheme cluster. We are currently storing a single letter in  a string. We should do the same. 
Current code is:
```rust
let string = s.chars().next().as_ref().map(ToString::to_string).unwrap_or_default();
```
We should use something like this instead:
```rust
let string = s.graphemes().next().unwrap_or("");
```
You can see @Manishearth's note about it here: https://github.com/servo/servo/pull/13860/files#r84568328

To use [graphemes](https://unicode-rs.github.io/unicode-segmentation/unicode_segmentation/trait.UnicodeSegmentation.html#tymethod.graphemes) function, we need to add a `unicode-segmentation` dependency to style crate. Style crate's cargo file is [here](https://github.com/servo/servo/blob/master/components/style/Cargo.toml). After adding dependency, and adding `extern crate unicode_segmentation;` to [lib.rs](https://github.com/servo/servo/blob/master/components/style/lib.rs), graphemes() function can be used after adding`use unicode_segmentation::UnicodeSegmentation;` 

File: `components/style/properties/longhand/inherited_text.mako.rs`

**Comment by TooManyBees** [comment]
I can pick this up

**Comment by jdm** [comment]
Great! Please ask questions here if anything is unclear!

**Comment by TooManyBees** [comment]
I'm wondering what a good test for this would be. I assume something that tests that that a string doesn't get truncated in the middle of a grapheme (like षि), but putting a unit test with that grapheme in `tests/unit/style/parsing/inherited_text.rs` but got an error unwrapping an Err (I think it was from the `parse_longhand!` macro, but I can't tell).

**Comment by Manishearth** [comment]
Check if षि  is considered to be a single grapheme by the library. Also try ज्ञ which is three code points but a single grapheme (and is not _exactly_ logically constructed from those code points)

Yes, `parse_longhand` unwraps the result of a parse. There might be something wrong with your test text or the parse code.

**Comment by TooManyBees** [comment]
I posted a [WIP pull request](https://github.com/servo/servo/pull/13914) with my code.

The code I was using for the test is
```rust
let devanagari_string = parse_longhand!(text_emphasis_style, "षि");
let devanagari_string_struct = SpecifiedValue::String("षि".to_string());
assert_eq!(devanagari_string, devanagari_string_struct);
```

Trying with ज्ञ also panics in the same spot. I'll start checking the library to see what it considers graphemes.

**Comment by Manishearth** [comment]
`षि` is not a valid value for `text-emphasis-style`, it must be `"षि"`. You need to do `let devanagari_string = parse_longhand!(text_emphasis_style, "\"षि\"");`

**Comment by TooManyBees** [comment]
My mistake, that did it. Thanks for the help.
