### ISSUE TITLE
Fix linear gradient's specified form

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#13892]
Currently linear gradient is not preserving the current corner directions if just one corner is specified. We should fix thix. The specified form of the linear gradient should preserve the corners and it should convert to angle in ToComputedValue implementation.

To give a  more details, you need to convert [this](https://github.com/servo/servo/blob/dee1a65a6983188a125f820b8bc9505f4909e171/components/style/values/specified/image.rs#L231) enum's `HorizontalDirection` and `VerticalDirection` to `Option<HorizontalDirection>` and `Option<HorizontalDirection>` and set it [here](https://github.com/servo/servo/blob/dee1a65a6983188a125f820b8bc9505f4909e171/components/style/values/specified/image.rs#L262-L279) directly without converting to Angle. 

This corner to angle conversion should be moved to ToComputedValue implementation, to do this you should remove [this](https://github.com/servo/servo/blob/dee1a65a6983188a125f820b8bc9505f4909e171/components/style/values/specified/image.rs#L289) line and write the implementation in `components/style/values/computed/image.rs` [GradientKind implemetation](https://github.com/servo/servo/blob/5f2e7af864e3d190957f58b317bf56cce8a84795/components/style/values/computed/image.rs#L181-L208) should give a hint to how to do it.

Also you can see [this part](https://github.com/servo/servo/wiki/Property-hacking-guide#tocomputedvalue-conversions) of the Property hacking guide to see how to implement a ToComputedValue conversion.

It may require some additional changes but compile errors will give you hint about that. And of course you can ask here if you have any questions.

**Comment by canaltinova** [comment]
@AVGP Are you still working on this? You can ask here if you have any questions.

**Comment by AVGP** [comment]
Absolutely, sorry that it takes me so long, just swamped with work but
should get a chance later this week

Am 07.11.2016 10:04 vorm. schrieb "Nazım Can Altınova" <
notifications@github.com>:

**Comment by KiChjang** [comment]
@AVGP next week never came...

**Comment by DominoTree** [comment]
I'd like to give this one a shot

**Comment by canaltinova** [comment]
@DominoTree Sure, go ahead! Btw, the links were showing wrong lines because of code changes over time. Updated them. You can ask here if something is unclear.

**Comment by DominoTree** [comment]
@canaltinova I've been hacking on this some but I'm having trouble wrapping my head around it as a whole.  Could you take a look at https://github.com/servo/servo/compare/master...DominoTree:master and see if it looks like I'm moving in the right direction or if anything jumps out at you?  Right now, I'm trying to figure out the `parse` method.

**Comment by canaltinova** [comment]
@DominoTree Looks like you're in the right path! You need to also remove AngleOrCorner from [here](https://github.com/servo/servo/compare/master...DominoTree:master#diff-cbedc7e16a657ba5014039823e619c1dR16) and create an AngleOrCorner enum in computed part like this one(Sorry I forgot to mention that):
```rust
pub enum AngleOrCorner {
    Angle(Angle),
    Corner(HorizontalDirection, VerticalDirection),
}
```

In this way we have 2 `AngleOrCorner` enums, one is computed and one is specified. Computed AngleOrCorner should be like the old specified one as above. You can undo your changes in `components/layout/display_list_builder.rs` after you changed that. We don't change the behavior of the computed AngleOrCorner. You need to convert `specified::AngleOrCorner` to `computed::AngleOrCorner` in `ToComputedValue` implementation.

```rust
+            //TODO: do I need to worry about this?
+            AngleOrCorner::Corner(horizontal, vertical) => {
+                specified::AngleOrCorner::Corner(horizontal, vertical)
+            }
```

This is mostly true, you need to change the line to `specified::AngleOrCorner::Corner(Some(horizontal), Some(vertical))` because we changed the horizontal and vertical direction to `Option` in specified.

You can open a WIP PR if you like and we can help you more. It's a bit hard to point a line in this way :)
