### ISSUE TITLE
Inline absolute hypothetical boxes at end of lines are incorrect

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#13915]
Minimal test case:

    <!DOCTYPE html>
    <div style="position: absolute;">
        Wikipedia<span style="top: 50%; position: absolute; margin-left: 1px;">X</span>
    </div>

The X should not overlap the rest of the text.

This breaks Google search results (the drop downs).

I think what's happening is that the inline absolute hypothetical box is getting placed on the next line when it shouldn't.

**Comment by splav** [comment]
May be related to this very old issue: https://github.com/servo/servo/issues/874
