### ISSUE TITLE
Running ./mach test-unit generates files in tree

### ISSUE THREAD

**Issue by aethanyc** [servo/servo#13929]
After running `./mach test-unit -p style`, some files generated under `tests/unit/style/target/`. Could we make them generated under `target/` or some where properly? Otherwise `./mach test-tidy` will scan those auto-generated files such as `tests/unit/style/target/debug/build/style-caa51859d4634c6c/out/properties.rs`, and produces much noise.

**Comment by Wafflespeanut** [comment]
It's already in `target`. When I tried to reproduce this, it seemed to be using `servo/target/debug/build/style-8deb288d0c4a7300/out/properties.rs`.

**Comment by aethanyc** [comment]
@Wafflespeanut I think you're right.  My Emacs with flycheck or something tries to do syntax checking and build the crate in tree. Thanks!
