### ISSUE TITLE
Appveyor windows gnu build is failing

### ISSUE THREAD

**Issue by jdm** [servo/servo#13939]
I'm not sure when this changed, but I guess the appveyor build folder isn't a git repo, for some reason?

```
if %BUILD_ENV%==gnu  bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./mach build -d -v && ./mach test-unit"
Error running mach:
    ['build', '-d', '-v']
The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You should consider filing a bug for this issue.
If filing a bug, please include the full output of mach, including this error
message.
The details of the failure are as follows:
CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 127
  File "/c/projects/servo/python/servo/build_commands.py", line 217, in build
    env = self.build_env(target=target, is_build=True)
  File "/c/projects/servo/python/servo/command_base.py", line 485, in build_env
    'git', 'rev-parse', '--short', 'HEAD'
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
```

**Comment by jdm** [comment]
https://ci.appveyor.com/project/servo/servo/history shows that this suddenly broke two days ago. I think something on appveyor's end changed behind our backs?

**Comment by larsbergstrom** [comment]
I think that @metajack was looking into this and there's something related to `PATH` changes. This is under investigation with the appveyor support staff.

**Comment by jdm** [comment]
Logs of @metajack's investigations: http://logs.glob.uno/?c=mozilla%23servo&s=4+Nov+2016&e=4+Nov+2016&h=appveyor#c555103

**Comment by UK992** [comment]
well this problem is locally reproducable, it's caused by updating git from 2.9.* to 2.10.*, use official git over msys git solve the problem. in this appveyor case just removing git from pacman's packages list.

**Comment by Ms2ger** [comment]
Does that mean that we'll break again if AppVeyor update the git version they provide out of the box?

**Comment by larsbergstrom** [comment]
No. the provided windows git fine. Mingw git broken. See PR removing.

On Nov 9, 2016, at 2:53 AM, Ms2ger <notifications@github.com> wrote:

Does that mean that we'll break again if AppVeyor update the git version
they provide out of the box?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/servo/servo/issues/13939#issuecomment-259362568>, or mute
the thread
