### ISSUE TITLE
`./mach test-unit` should also run with `feature = "gecko"`

### ISSUE THREAD

**Issue by canova** [servo/servo#13933]
In #13914, we added a crate for a longhand but currently, it only runs in stylo build. To avoid the `unused_extern_crates` error, we added `#[allow(unused_extern_crates)]` It can be changed with `#[cfg(feature = "gecko")]` but it gives error during `./mach test-unit` because unit tests run for all properties. To fix that, `./mach test-unit` should run with `feature = "gecko"` flag.

**Comment by emilio** [comment]
Or even with both features.

**Comment by canaltinova** [comment]
Yes, that's more accurate.

**Comment by nox** [comment]
@emilio Do we still care about that, now that Stylo is one of the most battle-tested parts of Servo?

**Comment by mrobinson** [comment]
I think this doesn't make much sense any longer now that Stylo is no longer part of Servo in 2 different ways: Servo is downstream of the Stylo repository and the Stylo repository is downstream of Gecko.
