### ISSUE TITLE
Don't check untracked file in test-tidy

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#13938]
When I run `./mach test-tidy` I'm usually overwhelmed by the untracked files, e.g. logs, temporary script, temporary test cases etc. I usually use `grep` to filter out those I'm actually interested, but I usually missed some and find it out later in CI checks. Since we are not going to check-in untracked files, should we skip checking their tidiness? 

I propose we don't run the tidy check on untracked files, but if we specify `--all` flag, we check both the unchanged files and untracked files.

What do you think? @larsbergstrom @jdm @aneeshusa ?

**Comment by shinglyu** [comment]
I have a almost-ready patch, but I think we should better discuss it before I submit the PR.

**Comment by jdm** [comment]
This makes sense to me.

**Comment by aneeshusa** [comment]
+1 from me for this.

**Comment by larsbergstrom** [comment]
Definitely +1 here - thanks for doing this!
