### ISSUE TITLE
Shutdown segfault on perf-rainbow.html in JS engine

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#1395]
It seems to happen when there are a *lot* of DOM nodes. When optimization is off I see an "out of memory" error, so incorrect handling of OOMs coupled with a too-small heap size may be the culprit.

    Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
    Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000004

    VM Regions Near 0x4:

    Thread 13 Crashed:
    0   libjs-2b1863329f7b31d9-0.1.dylib	0x0000000110f84cd3 js::GetGlobalForObjectCrossCompartment(JSObject*) + 3 (Barrier.h:172)
    1   libscript-8411a418a19aff3-0.1.dylib	0x000000011144971e dom::bindings::utils::global_object_for_js_object::hc2df57262ca3220aA::v0.1 + 62
    2   libscript-8411a418a19aff3-0.1.dylib	0x0000000111473eb5 dom::node::Node::reap_layout_data::hf899d032d7a0b270TOa9::v0.1 + 245
    3   libscript-8411a418a19aff3-0.1.dylib	0x00000001115a289e script_task::shut_down_layout::hf7828b1acf2fceeaaS::v0.1 + 814
    4   libscript-8411a418a19aff3-0.1.dylib	0x00000001115a187f script_task::ScriptTask::handle_exit_pipeline_msg::h4ce7224197d3ed6hday::v0.1 + 287
    5   libscript-8411a418a19aff3-0.1.dylib	0x000000011159b2ea script_task::ScriptTask::handle_msgs::h1b4bdcddf522b453hdaS::v0.1 + 5546
    6   libscript-8411a418a19aff3-0.1.dylib	0x0000000111599d28 script_task::ScriptTask::start::h9e4bb013ce729a1hdaR::v0.1 + 56
    7   servo                         	0x000000010fba0595 script_task::ScriptTask::create::anon::expr_fn::hdaSaZ + 1205
    8   libstd-6c65cf4b443341b1-0.9-pre.dylib	0x000000010fd1e9c5 task::spawn::spawn_raw::anon::expr_fn::a1 + 1125
    9   libstd-6c65cf4b443341b1-0.9-pre.dylib	0x000000010fd7c5de rt::task::__extensions__::build_start_wrapper::anon::anon::expr_fn::aF + 78
    10  libstd-6c65cf4b443341b1-0.9-pre.dylib	0x000000010fd7a6e3 rt::task::__extensions__::run::anon::expr_fn::aF + 67
    11  librustrt.dylib               	0x0000000111949c33 rust_try + 19 (rust_builtin.cpp:489)
    12  libstd-6c65cf4b443341b1-0.9-pre.dylib	0x000000010fd7a407 rt::task::Task::run::h199ab8d6eb226980nBaC::v0.9$x2dpre + 119
    13  libstd-6c65cf4b443341b1-0.9-pre.dylib	0x000000010fd7c18a rt::task::__extensions__::build_start_wrapper::anon::expr_fn::aw + 154

**Comment by jdm** [comment]
I can't reproduce this.
