### ISSUE TITLE
Make test-tidy check for alphabetical ordering of #![feature(...)] statements

### ISSUE THREAD

**Issue by jdm** [servo/servo#13954]
We try to keep our lists ordered:

``` rust
#![feature(box_patterns)]
#![feature(box_syntax)]
#![feature(conservative_impl_trait)]
#![feature(custom_derive)]
#![feature(nonzero)]
```

These only exist in files named `lib.rs`, and it would be nice to have `./mach test-tidy` verify that they are in alphabetical order.

**Comment by iamrohit7** [comment]
@wafflespeanut: I am working on this. I have a questions to ask.

`#![feature(feature1, feature2, `feature3)]
 #![feature(feature4)]`

How do I handle cases like this?

**Comment by jdm** [comment]
@iamrohit7 Sort the single-line features internally (ie. the `feature1, feature2, feature3` should be sorted alphabetically), then sort the multiline features treating them and single features. So
```rust
#![feature(jkl)]
#![feature(abc, ghi, def)]
```
would become
```rust
#![feature(abc, def, ghi)]
#![feature(jkl)]
```
Does that make sense?

**Comment by iamrohit7** [comment]
@jdm So, feature4 should always be greater than feature3? Or is it just enough to be greater than feature1?

`#![feature(abc, def, ghi)]`
`#![feature(cde)]`

This should be fine, right?

**Comment by Wafflespeanut** [comment]
I don't quite get your question, but you're right about the example.

**Comment by jdm** [comment]
It should be possible to sort the multiline features as regular strings without doing any processing of the contents.
