### ISSUE TITLE
Calling current_styles before or during styling

### ISSUE THREAD

**Issue by k-bx** [servo/servo#13962]
Calling current_styles before or during styling
### URL:

https://blog.devteam.space/new-macbook-pro-is-not-a-laptop-for-developers-anymore-d0d4b1b8b7de?gi=7649b9baeae5#.tpt1vssco
### Servo Version:

Servo 0.0.1-b4a882f
### Backtrace:

```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(10), index: PipelineIndex(10) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(10), index: PipelineIndex(11) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(11) }>: stop_parsing not implemented, full speed ahead!
WARNING: <main>: Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(10), index: PipelineIndex(3) }).
WARNING: <main>: Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(10), index: PipelineIndex(5) }).
WARNING: <main>: Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(10), index: PipelineIndex(1) }).
WARNING: <main>: Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(10), index: PipelineIndex(7) }).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(11) }>: FIXME: </script> not fully implemented
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(11) }>: stop_parsing not implemented, full speed ahead!
WARNING: <main>: Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(10), index: PipelineIndex(3) }).
WARNIN
...
```

This report was generated by the browser.html issue reporter.

**Comment by emilio** [comment]
cc @bholley

**Comment by emilio** [comment]
So I investigated this a bit, and I couldn't dig a lot more because I can't make it crash in debug builds, but it seems deterministic (that's good), and related with the reflow we issue when the hash is changed.

I suspect the reflow may be suppressed and the next restyle we find something unexpected. I may investigate a bit more later.

**Comment by emilio** [comment]
Nope, the reflow is actually due to a script query. No idea what can trigger it exactly though :(

**Comment by bholley** [comment]
I'm still refactoring this code a bit, so give me a few days and we'll see if the problem persists.

**Comment by korrat** [comment]
Is this still an issue?

**Comment by k-bx** [comment]
No, it's ok now on latest nightly (images didn't show though, but that's a different problem I guess)
