### ISSUE TITLE
Add a tidy check for spaces between function names and (

### ISSUE THREAD

**Issue by jdm** [servo/servo#13980]
Code like `fn foo (..)` and `something (...)` should be flagged by `./mach test-tidy`, since typical Rust style is to avoid adding spaces between function names and the opening parenthesis.

Code: `python/tidy/servo_tidy/tidy.py` (add a new rule to `regex_rules`)
Test: add incorrect code to `python/tidy/servo_tidy_tests/rust_tidy.rs`, then update `python/tidy/servo_tidy_tests/test_tidy.py` and run `./mach test-tidy --self`.

**Comment by dsprenkels** [comment]
I would like to (retrospectively) work on this issue.
