### ISSUE TITLE
Add a `mach` argument to enable debug assertions

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#14009]
Follow up from #13387.

`mach` currently honors the `SERVO_ENABLE_DEBUG_ASSERTIONS` environment variable to enable debug assertions. To make this option more discoverable and better documented, add a `mach` flag that does the same thing.

IMO, we can also remove the code that checks for and acts on the environment variable.

Files:
- python/servo/build_commands.py
- etc/ci/buildbot_steps.yml (pass the new flag for the `linux-rel-wpt` and `linux-rel-css` builders)

Tests:
- I can't think of a good automated test, so manual testing is probably fine.

cc @emilio @Ms2ger

**Comment by iamrohit7** [comment]
I will work on this. I have a question. There are two places where `SERVO_ENABLE_DEBUG_ASSERTIONS` is referenced in `python/servo/build_commands.py`, in `def build` and `def build_cef`. Should the flag be added to both build and build-cef?

**Comment by jdm** [comment]
Yep!

**Comment by aneeshusa** [comment]
Since we're removing the environment variable, we also need a follow-up PR to saltfs to revert [the PR adding the env var](https://github.com/servo/saltfs/pull/480/files) to the build environment.

**Comment by aneeshusa** [comment]
Still need a follow-up to saltfs.
