### ISSUE TITLE
Support non-follow redirect modes for RequestInit

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14018]
(As requested by jdm in #13742.)

**Comment by jdm** [comment]
Steps:
* add `request_mode` member to [RequestInit](https://github.com/servo/servo/blob/7c6793fc28423e518a0ceaae1176048fcb2caa3a/components/net_traits/request.rs#L115)
* update [Request::from_init](https://github.com/servo/servo/blob/7c6793fc28423e518a0ceaae1176048fcb2caa3a/components/net_traits/request.rs#L247) to set the requests' `redirect_mode` based on the initializer
* update [request_init_from_request](https://github.com/servo/servo/blob/7c6793fc28423e518a0ceaae1176048fcb2caa3a/components/script/fetch.rs#L43) to set the new field based on the same field in the `Request` object

Tests:
I would expect new test results to occur when running `./mach test-wpt tests/wpt/web-platform-tests/fetch/api/` after making these changes. They will need to be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) to account for the differences.

**Comment by rnestler** [comment]
I would like to give this a try as part of the Swiss hackathon :smiley:.

**Comment by rnestler** [comment]
@jdm
>  - add request_mode member to RequestInit 

There is already the  [`pub mode: RequestMode`](https://github.com/servo/servo/blob/7c6793fc28423e518a0ceaae1176048fcb2caa3a/components/net_traits/request.rs#L129) field in `RequestInit` or did you mean to add a field `redirect_mode`?

**Comment by jdm** [comment]
Yes, I meant redirect_mode. Sorry!
