### ISSUE TITLE
Conversion to (DOMString or object) is broken

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14019]
```rust
pub enum StringOrObject {
    String(DOMString),
    Object(*mut JSObject),
}

impl ToJSValConvertible for StringOrObject {
    unsafe fn to_jsval(&self, cx: *mut JSContext, rval: MutableHandleValue) {
        match *self {
            StringOrObject::String(ref inner) => inner.to_jsval(cx, rval),
            StringOrObject::Object(ref inner) => inner.to_jsval(cx, rval),
        }
    }
}

impl FromJSValConvertible for StringOrObject {
    type Config = ();
    unsafe fn from_jsval(cx: *mut JSContext,
                         value: HandleValue,
                         _option: ())
                         -> Result<ConversionResult<StringOrObject>, ()> {
        if value.get().is_object() {

        }

        match StringOrObject::TryConvertToString(cx, value) {
            Err(_) => return Err(()),
            Ok(Some(value)) => return Ok(ConversionResult::Success(StringOrObject::String(value))),
            Ok(None) => (),
        }


        throw_not_in_union(cx, "Object");
        Err(())
    }
}

impl StringOrObject {
    unsafe fn TryConvertToString(cx: *mut JSContext, value: HandleValue) -> Result<Option<DOMString>, ()> {
        Ok(Some(match FromJSValConvertible::from_jsval(cx, value, StringificationBehavior::Default) {
            Ok(ConversionResult::Success(strval)) => strval,
            Ok(ConversionResult::Failure(error)) => {
                return Ok(None);
            }
            _ => { return Err(()); },
        }))
    }

    unsafe fn TryConvertToObject(cx: *mut JSContext, value: HandleValue) -> Result<Option<*mut JSObject>, ()> {
        Ok(Some(value.get().to_object()))
    }
}
```

We don't currently use the conversion in that direction, so this is not particularly urgent, but probably good to fix anyway.

**Comment by igalic** [comment]
has something about this code changed in the past 16 days?
i'm getting:
```
warning: method is never used: `TryConvertToObject`, #[warn(dead_code)] on by default
    --> /home/igalic/src/me/servo/target/debug/build/script-a73982dc54bb4631/out/UnionTypes.rs:2132:5
     |
2132 |     unsafe fn TryConvertToObject(cx: *mut JSContext, value: HandleValue) -> Result<Option<*mut JSObject>, ()> {
     |     ^

rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/Support/SmallVector.cpp:36: void llvm::SmallVectorBase::grow_pod(void*, size_t, size_t): Assertion `NewElts && "Out of memory"' failed.
error: Could not compile `script`.
```

(i should probably also file that failure as bug against rustc https://gist.github.com/igalic/9ba4fba112fb036a466ef917f786fe74)

**Comment by Ms2ger** [comment]
This warning is not related to your error.

**Comment by rajivjhaimin** [comment]
@Ms2ger  @igalic 
I have also faced the similar warning while building servo in ubuntu 16.04 LTS.

` Compiling constellation v0.0.1 (file:///home/rjreloaded/servo/components/constellation)
warning: method is never used: `TryConvertToObject`, #[warn(dead_code)] on by default
    --> /home/rjreloaded/servo/target/debug/build/script-1ce5c7d50e394457/out/UnionTypes.rs:2132:5
     |
2132 |     unsafe fn TryConvertToObject(cx: *mut JSContext, value: HandleValue) -> Result<Option<*mut JSObject>, ()> {
     |     ^

warning: unreachable expression, #[warn(unreachable_code)] on by default
   --> /home/rjreloaded/servo/components/script/dom/htmlmediaelement.rs:451:13
    |
451 |             ResourceSelectionMode::Children(panic!())
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

`
After the warning, the compilation process stops. @Ms2ger kindly Guide me through it.

**Comment by KiChjang** [comment]
@rajivjhaimin If it wasn't clear enough in his last message, warnings are never the reason for a compilation failure.

**Comment by Xanewok** [comment]
Specific case of #17011.

**Comment by Xanewok** [comment]
This should be fixed by https://github.com/servo/servo/pull/20265.
