### ISSUE TITLE
Windows MSVC Build Cargo Error With VirtualBox

### ISSUE THREAD

**Issue by Coder206** [servo/servo#14032]
I made a VM of Windows 10 Education Edition and downloaded the dependencies from the [README.md] (https://github.com/servo/servo/blob/master/README.md). I tried running `mach.bat build -d` and then I received the message below:

![msvc](https://cloud.githubusercontent.com/assets/7758155/19953220/e5e3f1b0-a141-11e6-889c-2a6ddeb773b2.PNG)

**Comment by KiChjang** [comment]
A backtrace here would be helpful.

**Comment by Coder206** [comment]
@KiChjang I can't get a backtrace when running `mach.bat build -d RUST_BACKTRACE=1`, it just gives the popup and stops with `BUILD FAILED in 00:00:08`

**Comment by Coder206** [comment]
`cargo.exe build -V` is displayed with the error when running `mach.bat build -d --verbose`

**Comment by Coder206** [comment]
Since it was made in VirtualBox, did you want me to upload the VM for further investigation?

**Comment by nox** [comment]
@Coder206 Does this still happen?

**Comment by Coder206** [comment]
@nox Let me spin up a new VM for Windows 10 Education/Home and see if I reproduce.

**Comment by Coder206** [comment]
@nox I am unable to reproduce this with the latest Windows

**Comment by nox** [comment]
Cool! Closing it then.
