### ISSUE TITLE
mach hangs on Fedora 24

### ISSUE THREAD

**Issue by AgostonSzepessy** [servo/servo#14031]
I tried building servo on a 64 bit Fedora laptop using `./mach build --dev`, but `mach` hangs instead of building servo. `mach` hangs even when invalid arguments are passed in as well: `./mach aslkdfjlksafjlksadjfklas` hangs as well.

When I kill `mach`, the following is displayed:

```
^CTraceback (most recent call last):
  File "./mach", line 25, in <module>
    main(sys.argv)
  File "./mach", line 21, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/home/agoston/Documents/stuff/servo/python/mach_bootstrap.py", line 213, in bootstrap
    _activate_virtualenv(topdir)
  File "/home/agoston/Documents/stuff/servo/python/mach_bootstrap.py", line 155, in _activate_virtualenv
    process.wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

Processor type: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
RAM: 7702 MB

**Comment by Coder206** [comment]
Please note all my Fedora 24 systems are running fine but when I kill the process the error above shows too.

**Comment by KiChjang** [comment]
This is the line where it hangs:
```python
        process = Popen([pip, "install", "-q", "-r", req_path], stdout=PIPE, stderr=PIPE)
        process.wait()
```

In other words, it looks like running `pip install -q -r (stuff)` caused it to hang. Perhaps it has to do with permissions? Check the file permission on ./mach and on your pip executable.

**Comment by KiChjang** [comment]
Also, there may be confusion between python2 and python3 if you have both installed.

**Comment by Coder206** [comment]
For the record mine is 2.7.11

**Comment by AgostonSzepessy** [comment]
My pip permissions:

```
-rwxr-xr-x. 1 root root 204 Feb 22  2016 /usr/bin/pip
-rwxr-xr-x. 1 root root 204 Feb 22  2016 /usr/bin/pip2
-rwxr-xr-x. 1 root root 204 Feb 22  2016 /usr/bin/pip2.7
-rwxr-xr-x. 1 root root 205 Feb 22  2016 /usr/bin/pip3
-rwxr-xr-x. 1 root root 205 Feb 22  2016 /usr/bin/pip3.5
```

I also tried running it with `python2` and `python2.7` but the same thing happened as before.

**Comment by KiChjang** [comment]
If I'm not mistaken, a permission of `204` means that you as `other users` do not have the right to execute pip. You'll need to `sudo chmod 205 /usr/bin/pip /usr/bin/pip2.7 /usr/bin/pip2`.

**Comment by nox** [comment]
@AgostonSzepessy @Coder206 Does it still happen for you?

**Comment by Coder206** [comment]
@nox I haven't looked into this since my last comment. I can set up a VM with Fedora 26 (or 24) to see whether this still occurs.

**Comment by Coder206** [comment]
@nox I compiled Servo on both F24 and F26, `mach` does not hang.

**Comment by nox** [comment]
Nice! Thanks for trying! Closing.
