### ISSUE TITLE
Make HTTP redirect fetch return an error if redirecting to non-HTTP(S)

### ISSUE THREAD

**Issue by jdm** [servo/servo#14069]
Step 4 of the [http redirect fetch](https://fetch.spec.whatwg.org/#concept-http-redirect-fetch) specification says that we should return an error if we try to redirect to a non-HTTP(S) URL. Our corresponding implementation has a TODO in `http_redirect_fetch`. We should check the [scheme](http://doc.servo.org/url/struct.Url.html#method.scheme) of `location_url` and return `Response::network_error` if it doesn't match.

Code: `components/net/fetch/methods.rs`
Test:
`./mach test-wpt tests/wpt/web-platform-tests/fetch/api/redirect/redirect-schemes.html` should pass after this change. We should remove [the test expectation file](https://dxr.mozilla.org/servo/source/tests/wpt/metadata/fetch/api/redirect/redirect-schemes.html.ini) in that case.

**Comment by rschlaefli** [comment]
I would like to try this as part of the hackathon :)

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear! The testing situation might be complicated until https://github.com/servo/servo/pull/14070 merges.

**Comment by rschlaefli** [comment]
I think I solved it but I'm getting timeouts and "not run" in the test suite. Might this be because of the other issue?

**Comment by jdm** [comment]
Probably! Try applying the changes in that PR and see if the test results make more sense?

**Comment by jdm** [comment]
@rschlaefli Want to make a pull request with your changes?

**Comment by 46bit** [comment]
Hi, I just found Servo. It looks like this is up-for-grabs so I've made the patch above.
