### ISSUE TITLE
Use MediaQueryListEvent for media query list change events

### ISSUE THREAD

**Issue by jdm** [servo/servo#14064]
https://github.com/servo/servo/pull/13453 implemented the window.matchMedia and MediaQueryList APIs. However, the [specification](https://drafts.csswg.org/cssom-view/#evaluate-media-queries-and-report-changes) related to the "change" event was [unclear](https://github.com/w3c/csswg-drafts/issues/681), so we didn't notice that we should use a specific event interface instead of Event.

* [create](http://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface) the missing [MediaQueryListEvent](https://drafts.csswg.org/cssom-view/#dom-mediaquerylistevent-mediaquerylistevent) interface (use existing event types like `PageTransitionEvent` as a model)
* modify `WeakMediaQueryListVec::evaluate_and_report_changes` to use the new event type and set its properties according to [the specification](https://drafts.csswg.org/cssom-view/#evaluate-media-queries-and-report-changes)

Code: `components/script/dom/webidls/MediaQueryListEvent.webidl`, `components/script/dom/mod.rs`, `components/script/dom/mediaquerylistevent.rs`, `components/script/dom/mediaquerylist.rs`

Tests:
* modify `tests/wpt/mozilla/tests/css/matchMedia.html` to assert that the change event received is `instanceof MediaQueryListEvent` (ensure `./mach test-wpt tests/wpt/mozilla/tests/css/matchMedia.html` passes)
* add the new interface to the list in `tests/wpt/mozilla/tests/mozilla/interfaces.html` (make sure `./mach test-wpt tests/wpt/mozilla/tests/mozilla/interfaces.html` passes)

**Comment by ajnirp** [comment]
I'd like to work on this

**Comment by jdm** [comment]
Please do! Ask questions if anything is unclear.

**Comment by jdm** [comment]
@ajnirp Are you intending to complete this?

**Comment by ajnirp** [comment]
Sorry, I lost access to my personal laptop! Yes I will complete this, hopefully before Monday night.

**Comment by bd339** [comment]
I noticed this under Potentially Open Issues and would like to take it on, if @ajnirp is OK with that?

**Comment by jdm** [comment]
Yes, I think that's fine.

**Comment by bd339** [comment]
I'm having some difficulty with matchMedia.html. 3 tests are failing even without my changes and I'm not sure what needs to be an instanceof MediaQueryListEvent (I don't see any events in there?)

**Comment by jdm** [comment]
rmListener and dupListener are event listener callbacks. The `x` argument is the event object.

**Comment by jdm** [comment]
Similarly, all the calls to `addListener` that have an inline callback are event listener callbacks.

**Comment by bd339** [comment]
Thank, I was just confused by e.g. the `x == mql1` and `mql instanceof MediaQueryList` checks.
