### ISSUE TITLE
Make FetchMetadata reflect all possible response types

### ISSUE THREAD

**Issue by jdm** [servo/servo#14068]
https://fetch.spec.whatwg.org/#concept-response-type describes all the possible types of responses that can be returned from the `Fetch` API. We have equivalent types in our [fetch network stack implementation](https://github.com/servo/servo/blob/dae007fd1634bcf1545e67abaa7746fa95f10e94/components/net_traits/response.rs#L16). However, the code that reports the results of our network response to the DOM API loses some information in the process, so the DOM code only deals with `error`, `opaque`, and `default` [right now](https://github.com/servo/servo/blob/dae007fd1634bcf1545e67abaa7746fa95f10e94/components/script/fetch.rs#L129-L147).

Steps:
* modify the [FilteredMetadata](https://github.com/servo/servo/blob/dae007fd1634bcf1545e67abaa7746fa95f10e94/components/net_traits/lib.rs#L222) enum to contain `OpaqueRedirect` and `Cors(Metadata)` variants, and rename `Transparent` to `Basic`
* modify [Response::metadata](https://github.com/servo/servo/blob/dae007fd1634bcf1545e67abaa7746fa95f10e94/components/net_traits/response.rs#L266-L269) to return the new variants as appropriate by matching on `response.response_type`
* modify the code in [fetch.rs](https://github.com/servo/servo/blob/dae007fd1634bcf1545e67abaa7746fa95f10e94/components/script/fetch.rs#L143-L147) to deal with the new variants and set the `response_type` member to the appropriate value
* update the code in [xmlhttprequest.rs](https://github.com/servo/servo/blob/dae007fd1634bcf1545e67abaa7746fa95f10e94/components/script/dom/xmlhttprequest.rs#L871-L873) to deal with the new variants identically to the existing ones

Tests:
`./mach test-wpt tests/wpt/web-platform-tests/fetch/api` should report new passing tests after these changes. The expected test results will need to be [update](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations)

**Comment by MichaelKohler** [comment]
I'll give this a try as part of the Swiss hackathon :)

**Comment by KiChjang** [comment]
Awesome!

**Comment by jdm** [comment]
@MichaelKohler Are you intending to complete this?

**Comment by MichaelKohler** [comment]
I didn't have enough time to start. If somebody else wants to do this, go for it! I can't really say when I'd have time to do this.

**Comment by 46bit** [comment]
I'd like to take this one on.

**Comment by KiChjang** [comment]
Go right ahead!

**Comment by jdm** [comment]
@46bit Have you made any progress with this?

**Comment by 46bit** [comment]
@jdm I'm back from holiday and will be working on it late this week.

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by bd339** [comment]
I could work on this, if it's available.

**Comment by jdm** [comment]
@bd339 Please do!
