### ISSUE TITLE
Remove unnecessary `allow(unsafe_code)` in MediaQueryList

### ISSUE THREAD

**Issue by jdm** [servo/servo#14065]
There are a few instances of `#[allow(unsafe_code)]` in `components/script/dom/mediaquerylist.rs` that are no longer necessary since they don't make use of unsafe code. Let's remove them!

**Comment by dns2utf8** [comment]
I take this

**Comment by dns2utf8** [comment]
Cool, do I need to do anything now?

**Comment by jdm** [comment]
Nope!
