### ISSUE TITLE
Clean up EventRunnable::handler

### ISSUE THREAD

**Issue by nox** [servo/servo#14062]
The [two `clone` calls](https://github.com/servo/servo/blob/f447040ea98d5a92f95d6dd3116939544441b5d8/components/script/dom/event.rs#L333-L334) are unnecessary and can be removed, because both `EventBubbles` and `EventCancelable` are `Copy`.

**Comment by jdm** [comment]
@rjgoldsborough In future, please leave a comment when you start working on an issue!

**Comment by rjgoldsborough** [comment]
ah, shoot, sorry
