### ISSUE TITLE
Style needs a way to get font metrics while computing style data.

### ISSUE THREAD

**Issue by emilio** [servo/servo#14079]
This right now isn't implemented (see https://github.com/servo/servo/issues/7462), and I'm afraid it might be a pain to do for Stylo.

Basically, if we find an `ex` or a `ch` unit, we need to get the font metrics of the first available font for that style in order to compute the value.

This is not too common, but I think a lot of the font code is lazy in Gecko so calling it from multiple threads can be a very huge pain, and can impose a significant synchronization cost for pages that use this units.

In servo it's also a pain to implement too, since all the font code is on `gfx` and only layout has access to a `FontContext` right now.

cc @heycam @bholley @Manishearth @SimonSapin and @upsuper (I think I haven't left anyone :))

**Comment by emilio** [comment]
IRC conversation with @upsuper: http://logs.glob.uno/?c=mozilla%23layout&s=7+Nov+2016&e=7+Nov+2016#c23995

This sounds like a pretty decent amount of work...

**Comment by emilio** [comment]
cc @nox, who has also done font stuff

**Comment by bholley** [comment]
How common are these units? Could we just acquire a mutex, call into Gecko, and cache the result in TLS?

CC @dbaron @pcwalton

**Comment by upsuper** [comment]
Firstly, I think it is probably hard not to do them lazily, because font metrics rely on all kinds of font information, including font family, size, style, variant, etc. It is simply infeasible to generate all possible font metrics in advance.

I think the main problem here is that we probably want a global shared metrics cache, and that cache is usually implemented in a fashion that changes the order when accessed. (At least that is the case of Gecko.)

Not sure how common would those units be. I myself hardly use them, but I wouldn't be surprised if some websites want to heavily rely on those units.

**Comment by upsuper** [comment]
An alternative way would be doing restyling in two phases. In the first phases we compute all things which do not rely on dimensions, and we generate a list of font metrics we need. And in the second phase we resolve all dimension-related properties.

**Comment by pcwalton** [comment]
How about a reader-writer lock cache? I think a RW lock may be fast enough since these units are not *that* common.

An alternative would be per thread caches to eliminate the synchronization cost.

**Comment by bholley** [comment]
Yeah, RWLock might be fine too, especially with parking lot. Roughly isomorphic to a TLS cache + mutex from an architectural perspective, so I think we should try these approaches before doing anything much more complicated.

**Comment by emilio** [comment]
I added infra for this in #14174, though it still needs a bunch of work of moving code from gfx into style, or into another crate lower in the dependency chain.

**Comment by nox** [comment]
@emilio Is this still true?

**Comment by emilio** [comment]
It is, and we need to get it fixed sooner rather than later.
