### ISSUE TITLE
Has pixel coords fix introduced new error.

### ISSUE THREAD

**Issue by maxcr** [servo/servo#14073]
`cannot access` has changed to `0(33) : error C1009: "has_pixel_coords" is not member of struct "Image"`

**Comment by glennw** [comment]
See https://github.com/servo/servo/issues/14061#issuecomment-258523140

**Comment by glennw** [comment]
@maxcr There's a fix in the merge queue for this now (https://github.com/servo/servo/pull/14074).

**Comment by maxcr** [comment]
<3 u
