### ISSUE TITLE
Fix namespaces of elements created in XML documents

### ISSUE THREAD

**Issue by nox** [servo/servo#14095]
Step 6 of [the spec](https://dom.spec.whatwg.org/#dom-document-createelement) is not correctly implemented, and elements created in XML documents also get the HTML namespace where they shouldn't.

Files:
 * components/script/dom/document.rs
 * tests/wpt/metadata/dom/nodes/Node-properties.html.ini
 * tests/wpt/web-platform-tests/dom/nodes/Node-properties.html

**Comment by nox** [comment]
Blocks #2185.

**Comment by oldmanmike** [comment]
I would like to take this one!

**Comment by nox** [comment]
Sure!

**Comment by linclark** [comment]
I saw this listed as potentially open on https://starters.servo.org/. If it is available, I'd like to give it a shot.

**Comment by jdm** [comment]
That sounds fine to me. @oldmanmike, if you'd like to work on something else let us know and we'll find another issue for you.

**Comment by oldmanmike** [comment]
Sure, I'd be willing to pass this one off to @linclark!

**Comment by linclark** [comment]
Thanks! I posted my work-in-progress. I ran into two issues, which I explain in the PR.

**Comment by jdm** [comment]
#14401 has a WIP solution, and there are some review comments that need to be addressed.

**Comment by enizor** [comment]
I would like to work on this issue!

**Comment by enizor** [comment]
I used @linclark's changes to understand the unpassed tests and his thoughts about modifying the doctype when XML documents are created. 

The tests are failing on 
```
PASS expected FAIL xmlElement.namespaceURI
PASS expected FAIL detachedXmlElement.namespaceURI 
```
I think that these tests are supposed to pass, and the `expected: FAIL` was added for some reason in #13210 (some form of acknowledgement? ). Deleting tests/wpt/metadata/dom/nodes/Node-properties.html.ini would do the trick in that case. What are your thoughts on this ?

Another question : Steps 3 and 6 of the [spec](https://dom.spec.whatwg.org/#dom-document-createelement) (about the _is_ attribute) aren't implemented. Is there a reason for this? Is it the matter of another issue?

**Comment by jdm** [comment]
Yes, the contents of the ini files reflect the status of the test on the master branch of Servo. PASS expected FAIL means that the test now passes correctly. Deleting the ini file is the correct thing to do.

**Comment by jdm** [comment]
The `is` member is specific to [Custom Elements](https://html.spec.whatwg.org/multipage/scripting.html#custom-elements) which we don't support yet.

**Comment by jdm** [comment]
@enizor Have you made any progress with this?

**Comment by enizor** [comment]
I have a lot of trouble understanding the origin of the failed test pointed out in the PR.

I looked for other failed tests and found [Document-createElement.html](https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/dom/nodes/Document-createElement.html). 

I changed the test as only HTML documents have the HTML namespace now.
 ```
assert_equals(elt.namespaceURI,
-                        desc == "XML document" ? null : HTMLNS, "namespaceURI")
+                        desc == "HTML document" ? HTMLNS : null, "namespaceURI")
```

All the tests results from Document-createElement.html are then expected.

I will take another look in the Document-constructor.html fail this week-end

**Comment by jdm** [comment]
@Ms2ger You're more familiar with the namespace stuff; could you answer the previous comment?

**Comment by enizor** [comment]
Nevermind my previous comment, I realised that I misunderstood the HTML namespace usage. No changes for Document-createElement are needed.

**Comment by jdm** [comment]
@enizor How is it going? Still working on this?

**Comment by enizor** [comment]
I still don't understand the test fail. I had some trouble running the tests (`mach test` is dependant of your last `mach build`, and not the current branch, right?) as the compilation is quite slow on my laptop. I think I should give up on this issue and try some stuff on my side, to make sure I understand more about the project and its tools. Then I may be able to tackle issues with a better efficiency!

**Comment by jdm** [comment]
Yeah, `./mach test` relies on the previous completed build. I'll mark this as unassigned given you previous comment.

**Comment by cu1t** [comment]
Hi everyone! I'm new to both rust and servo, but would like to try working on this issue as it is currently not assigned to anyone.

**Comment by jdm** [comment]
Go ahead! Please ask questions if anything is unclear!

**Comment by cu1t** [comment]
A bit unsure how to proceed here. As mentioned above and in @linclark's pull request, required changes result in `Document-constructor.html` test to fail:
```
var doc = new Document();
var a = doc.createElement("a");
a.href = "http://example.org/?\u00E4";
console.log(a.href, "http://example.org/?%C3%A4");
```
I'm not very familiar with the specs, but after giving them some look I tend to think that it is test at fault here. Created document will have `contentType` set to "application/xml", `self.is_html_document` will also be false -> empty namespace for createElement. So during element creation this should be treated just as XML. I don't see why this should encode URL then? I'm not 100% on this though, so should I perhaps raise issue at https://github.com/w3c/web-platform-tests?
