### ISSUE TITLE
Make parse functions implement from Parse trait in style

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#14101]
There is a [Parse trait](https://github.com/servo/servo/blob/41df7056610e474a9a2efe4c807f480e976d0c1d/components/style/parser.rs#L89) in style crate. This trait will make it easy to write more generic values in the future. And it would be great if we convert parse functions to this implementation. You can find relevant parse functions with dxr[1]
Of course some of them are already implemented from this trait(like [this one](https://dxr.mozilla.org/servo/source/components/style/values/specified/image.rs#320)). Simply ignore that cases.

[1] https://dxr.mozilla.org/servo/search?q="fn+parse("+-ParserContext

**Comment by Manishearth** [comment]
To be clear, this only applies for stuff in `style::values::specified`.

**Comment by impowski** [comment]
I can take it.

**Comment by Manishearth** [comment]
Go ahead!
