### ISSUE TITLE
Intermittent CRASH in /webgl/conformance-1.0.3/conformance/ogles/GL/matrixCompMult/matrixCompMult_001_to_004.html

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14103]
▶ CRASH [expected ERROR] /webgl/conformance-1.0.3/conformance/ogles/GL/matrixCompMult/matrixCompMult_001_to_004.html
    │ 
    │ VMware, Inc.
    │ Gallium 0.4 on softpipe
    │ 3.3 (Core Profile) Mesa 12.0.1
    │ called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread main, at ../src/libcore/result.rs:837)
    │ DESCRIPTION: WebGL GLSL conformance test: matrixCompMult_001_to_004.html
    │ 
    │ test: matrixMultComp_mat2_frag.test.html
    │ loading: ../default/default.vert
    │ loading: matrixMultComp_mat2_frag_ref.frag
    │ loading: ../default/default.vert
    │ loading: matrixMultComp_mat2_frag.frag
    │ loaded: ../default/default.vert
    │ loaded: matrixMultComp_mat2_frag.frag
    │ 
    │ ERROR:script::dom::bindings::error: Error at :0:0 NotSupportedError: The operation is not supported.
    │ loaded: matrixMultComp_mat2_frag_ref.frag
    │ loaded: ../default/default.vert
    │ 
    │ ERROR:script::dom::bindings::error: Error at :0:0 NotSupportedError: The operation is not supported.
    │ stack backtrace:
    │    0:     0x7f7fe3a29e9d - backtrace::backtrace::trace::h16372ee7bf1517e5
    │    1:     0x7f7fe3a2a532 - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
    │    2:     0x7f7fe34cd5cd - servo::main::_{{closure}}::h8e9c5971861a4720
    │    3:     0x7f7fe50f9604 - std::panicking::rust_panic_with_hook
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:452
    │    4:     0x7f7fe50f94c4 - std::panicking::begin_panic<collections::string::String>
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
    │    5:     0x7f7fe50f93e9 - std::panicking::begin_panic_fmt
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
    │    6:     0x7f7fe50f9377 - std::panicking::rust_begin_panic
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
    │    7:     0x7f7fe5135ddd - core::panicking::panic_fmt
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
    │    8:     0x7f7fe4fe81cf - core::result::unwrap_failed::h97cf4d1c2597280e
    │    9:     0x7f7fe4fea9b0 - webrender_traits::api::RenderApi::get_scroll_layer_state::h5740fb21860a3fa4
    │   10:     0x7f7fe34be2b0 - _<compositing..compositor..IOCompositor<Window>>::send_viewport_rects::h0f2b4cbb3ef7750f
    │   11:     0x7f7fe34c0fd4 - _<compositing..compositor..IOCompositor<Window>>::handle_browser_message::h8125314813eff943
    │   12:     0x7f7fe34b0155 - _<servo..Browser<Window>>::handle_events::h923020c5bef422cb
    │   13:     0x7f7fe34cc045 - servo::main::h918959923860ea9a
    │   14:     0x7f7fe5101c6a - panic_unwind::__rust_maybe_catch_panic
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
    │   15:     0x7f7fe50f862a - std::panicking::try<(),fn()>
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
    │                          - std::panic::catch_unwind<fn(),()>
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
    │                          - std::rt::lang_start
    │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
    │   16:     0x7f7fe0de0f44 - __libc_start_main
    │   17:     0x7f7fe34a0c19 - <unknown>
    │   18:                0x0 - <unknown>
    │ ERROR:servo: called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
    └ Pipeline failed in hard-fail mode.  Crashing!

**Comment by jdm** [comment]
Merging with #13479.
