### ISSUE TITLE
Remove dependency of canvas_traits on azure.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14108]
The `canvas_traits` crate contains definitions of a number of data structures, as well as methods to convert those data structures into Azure's data structures. There conversion methods are only used in the code for the 2D canvas implementation in the `canvas` crate. In order to simplify the dependency tree, we should move those conversion methods to the `canvas` crate.

Note that implementing methods on a type from another crate will require defining a trait.

Code:
* `components/canvas_traits/lib.rs`
* `components/canvas/canvas_paint_thread.rs`

**Comment by nox** [comment]
AFAICT, the trait should just be:

```rust
pub trait ToAzureStyle {
    type Target;
    fn to_azure_style(self) -> Self::Target;
}
```

The preexisting traits (`ToAzColor` and `ToAzFloat`) can then be expressed in terms of `ToAzureStyle`.

**Comment by Ms2ger** [comment]
(Except for `to_azure_pattern`, which takes an extra argument.)

Also, to be clear: the goal is to remove the `extern crate azure;` from `components/canvas_traits/lib.rs`, and the mention of `azure` in the `Cargo.toml` next to it.

**Comment by justinaustin** [comment]
I would like to work on this issue. Thanks!

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear!

**Comment by justinaustin** [comment]
I don't know if this is the place to ask, but is there a quick way to just build the canvas and canvas_traits components?

**Comment by Wafflespeanut** [comment]
@justinaustin Are you working on this?

**Comment by justinaustin** [comment]
I won't be able to finish it with finals coming up. Apologies!

**Comment by Wafflespeanut** [comment]
No worries! Thanks for letting us know.

**Comment by Naruto8** [comment]
Excuse me.. I want to start contributing, never did before. I always get confused (low on confidence) so can anyone help me  work on this issue?

**Comment by KiChjang** [comment]
@Naruto8 Sure we can! Ask us anything here or join us at #servo on `irc.mozilla.org` if you have any questions!

**Comment by Naruto8** [comment]
I am still learning rust how much time will this require?

**Comment by KiChjang** [comment]
It shouldn't take long if you have an idea of where to look for and what to change. Is there any specific problem that you came across?

**Comment by Naruto8** [comment]
I am finally starting to understand a bit.... Those two files need to be merged into the canvas crate? And for that we need to define a trait (why?)?

**Comment by KiChjang** [comment]
The purpose of this issue is to move all functions that convert Servo-defined data structures to Azure data structures into `components/canvas/canvas_paint_thread.rs`. This includes the impls of `FillOrStrokeStyle`, `LineCapStyle`, `LineJoinStyle`, `CompositionStyle`, `BlendingStyle` and `CompositionOrBlending`.

Note that the structs themselves are not moved. This is why you need to define a trait in `components/canvas/canvas_paint_thread.rs`, because Rust forbids defining impls for structs defined on another crate (if not for this, Rust would have to scan through all known crates in existence to know about all the impls for the struct). Does that make sense?

**Comment by Naruto8** [comment]
So all I need is to add the below traits in `components/canvas/canvas_paint_thread.rs`:
```
pub trait ToAzureStyle {
    type Target;
    fn to_azure_style(self) -> Self::Target;
}

pub trait ToString {
    fn to_string(self) -> &str;
}
```
Also move the trait `ToAzColor` to `components/canvas/canvas_paint_thread.rs`?

**Comment by KiChjang** [comment]
Yes, but defining the traits is not enough. You still need to implemenet the traits on the structs that I've listed on my previous post. Here's an example:
```rust
impl ToAzureStyle for LineCapStyle {
    type Target = CapStyle;
    fn to_azure_style(self) -> Self::Target {
        match self {
            LineCapStyle::Butt => CapStyle::Butt,
            LineCapStyle::Round => CapStyle::Round,
            LineCapStyle::Square => CapStyle::Square,
        }
    }
}
```

**Comment by KiChjang** [comment]
#14547 was an attempt at this, but the changes did not compile.

**Comment by zaynetro** [comment]
I'd like to work on this issue

**Comment by jdm** [comment]
Please do! Ask questions if anything is unclear!
