### ISSUE TITLE
Move bluetooth-helpers.js into mozilla test directory

### ISSUE THREAD

**Issue by jdm** [servo/servo#14112]
I only noticed via https://github.com/w3c/web-platform-tests/pull/4178/ that bluetooth-helpers.js was added to tests/wpt/web-platform-tests/bluetooth/ rather than tests/wpt/mozilla/tests/mozilla/bluetooth/.

cc @zakorgy @dati91

**Comment by dati91** [comment]
We have an [open PR about wpt test fixs](https://github.com/servo/servo/pull/13918), maybe we can add this change to that?

**Comment by jdm** [comment]
Sure!

**Comment by jdm** [comment]
Fixed by #13918.
