### ISSUE TITLE
StringError("Bogus destination port.") every time Servo quits, possibly interfering with -o out.png functionality

### ISSUE THREAD

**Issue by rzambre** [servo/servo#14117]
Platform: Mac OS X 10.11.6

After running

> ./mach run -r <any-url> 

and when I try to quit Servo, I see  a bunch of the following errors (on all urls):

> called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at ../src/libcore/result.rs:837)

This is possibly interfering with the functionality of ```-x -o out.png``` flags.

Related to #14002

**Comment by jdm** [comment]
This may be the same panic seen with more backtrace in #14118!

**Comment by rzambre** [comment]
Even with the StringError, the out.png file actually gets created. Opening the file shows a seemingly right output image but I'm not sure if this error is interfering the with the completeness of writing to the out.png file.

**Comment by jdm** [comment]
I would not expect it to actually have a material effect, since it should only occur after we're already trying to shut down.

**Comment by rzambre** [comment]
That makes sense! I'll close this issue since it deals with the functionality of the -o flag.
