### ISSUE TITLE
Keep Property hacking guide wiki page up-to-date

### ISSUE THREAD

**Issue by chenpighead** [servo/servo#14128]
An example would be that we're using `style_traits::ToCss` instead of cssparser::ToCss after #14089.

There could be more, such like when should we setting `products="gecko|servo|nont"`? What should we do if we're adding a longhand property (e.g. font-synthesis) that is included in a shorthand property (e.g. font)?

**Comment by Wafflespeanut** [comment]
Thanks. I've revised the former, and the latter depends on types (some are implemented in servo, some on gecko, and some are unimplemented in both). So, we'll mention it in the issue next time :)
