### ISSUE TITLE
Intermittent CRASH in /css21_dev/html4/min-width-tables-001.htm and /html/semantics/embedded-content/the-iframe-element/iframe-with-base.html

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14161]
Looks similar to #10481

    ▶ CRASH [expected PASS] /css21_dev/html4/min-width-tables-001.htm
    │ 
    │ VMware, Inc.
    │ Gallium 0.4 on softpipe
    │ 3.3 (Core Profile) Mesa 12.0.1
    │ Shutting down the Constellation after generating an output file or exit flag specified
    │ called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at ../src/libcore/result.rs:837)
    │ stack backtrace:
    │    0:        0x10e8ae5ee - backtrace::backtrace::trace::h16372ee7bf1517e5
    │    1:        0x10e8ae8dc - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
    │    2:        0x10d756944 - servo::main::_{{closure}}::h0451350d2b9d9cf7
    │    3:        0x10f147173 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
    │    4:        0x10f147044 - std::panicking::begin_panic::ha6a0d553db9869ff
    │    5:        0x10f146f62 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
    │    6:        0x10f146ec7 - rust_begin_unwind
    │    7:        0x10f173c90 - core::panicking::panic_fmt::he441b2ea2036b98a
    │    8:        0x10ef5c9e0 - core::result::unwrap_failed::h88381ff2d9927dee
    │    9:        0x10ef5d37d - profile_traits::mem::ProfilerChan::send::h55388501bf4fad43
    │   10:        0x10d8fc5c4 - std::panicking::try::do_call::hefc99e00c410e98d
    │   11:        0x10f14819a - __rust_maybe_catch_panic
    │   12:        0x10d924cc5 - _<F as alloc..boxed..FnBox<A>>::call_box::h91e7a07dcdec9fae
    │   13:        0x10f146024 - std::sys::thread::Thread::new::thread_start::h9fa66f6812e81e10
    │   14:     0x7fff82030059 - _pthread_body
    │   15:     0x7fff8202ffd6 - _pthread_start
    │ ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }
    │ Pipeline failed in hard-fail mode.  Crashing!
    └ thread panicked while processing panic. aborting.

**Comment by Wafflespeanut** [comment]
Same problem

    ▶ CRASH [expected PASS] /html/semantics/embedded-content/the-iframe-element/iframe-with-base.html
    │ 
    │ VMware, Inc.
    │ Gallium 0.4 on softpipe
    │ 3.3 (Core Profile) Mesa 12.0.1
    │ Shutting down the Constellation after generating an output file or exit flag specified
    │ called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at ../src/libcore/result.rs:837)
    │ stack backtrace:
    │    0:        0x1049e9eae - backtrace::backtrace::trace::h16372ee7bf1517e5
    │    1:        0x1049ea19c - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
    │    2:        0x1038730b4 - servo::main::_{{closure}}::h8b4c8cbeb6eecb16
    │    3:        0x1052ab8d3 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
    │    4:        0x1052ab7a4 - std::panicking::begin_panic::ha6a0d553db9869ff
    │    5:        0x1052ab6c2 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
    │    6:        0x1052ab627 - rust_begin_unwind
    │    7:        0x1052d83f0 - core::panicking::panic_fmt::he441b2ea2036b98a
    │    8:        0x1050c0d50 - core::result::unwrap_failed::h88381ff2d9927dee
    │    9:        0x1050c16ed - profile_traits::mem::ProfilerChan::send::h0a061b58cddb953e
    │   10:        0x103a188e4 - std::panicking::try::do_call::hd1dba29212e2691d
    │   11:        0x1052ac8fa - __rust_maybe_catch_panic
    │   12:        0x103a40fd5 - _<F as alloc..boxed..FnBox<A>>::call_box::h0964622c77ad3e77
    │   13:        0x1052aa784 - std::sys::thread::Thread::new::thread_start::h9fa66f6812e81e10
    │   14:     0x7fff82030059 - _pthread_body
    │   15:     0x7fff8202ffd6 - _pthread_start
    │ ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }
    │ Pipeline failed in hard-fail mode.  Crashing!
    └ thread panicked while processing panic. aborting.

**Comment by timvandermeij** [comment]
Fixed by #14165?

**Comment by jdm** [comment]
We'll say yes.
