### ISSUE TITLE
Meta-bug: make Servo ready for daily practical use

### ISSUE THREAD

**Issue by DemiMarie** [servo/servo#14169]
This is a meta-bug for making Servo ready for use as one's main browser.

**Comment by Wafflespeanut** [comment]
I guess it's gonna take a while to get there :smile: 

cc @larsbergstrom @jdm

**Comment by DemiMarie** [comment]
Any updates :smile: ?

**Comment by jdm** [comment]
I don't think it's worth keeping this open until we have firm criteria for what "daily practical use" means.
