### ISSUE TITLE
Stylo: implement -moz-orient

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#14198]
Please go through [the guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide) if you wish to hack on stylo.

[`-moz-orient`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-orient) is a keyword property ([implementation guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide#implementing-a-simple-keyword-property)) with the set of possible values being `inline | block | horizontal | vertical`. `inline` is the default. The field name is [`mOrient`](http://searchfox.org/mozilla-central/rev/4b6cab91f93c73ae591dafaea40fd5704b41810e/layout/style/nsStyleStruct.h#2824), and the enum prefix is [`StyleOrient`](http://searchfox.org/mozilla-central/rev/4b6cab91f93c73ae591dafaea40fd5704b41810e/layout/style/nsStyleConsts.h#237).

The testcase on the MDN page must work in stylo once this property is implemented.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs

**Comment by choudhary001** [comment]
I would like to give this a try. Thanks!

**Comment by Manishearth** [comment]
Go ahead!

**Comment by Wafflespeanut** [comment]
@choudhary001 Are you still working on this?

**Comment by choudhary001** [comment]
Yes, I am going through the documentation. Will try to submit a PR by next week if thats okay.

**Comment by choudhary001** [comment]
I tried to build servo but it is failing with a lot of errors. I have attached the output of `./mach build --dev --verbose`. Could anyone help me with the build errors?
[build-error.txt](https://github.com/servo/servo/files/637626/build-error.txt)

**Comment by Wafflespeanut** [comment]
Oh, it's got nothing to do with your changes. Try and flush your `target` directory with `./mach clean` (or just remove it entirely) and try again :)

**Comment by Wafflespeanut** [comment]
@choudhary001 ping

**Comment by choudhary001** [comment]
@Wafflespeanut Hey it will take some time for me submit changes as my laptop's hard disk has crashed and i need to get it fixed. If it is urgent then maybe someone else can take it up.
Thanks and sorry for the delay.

**Comment by Wafflespeanut** [comment]
Well, it's not urgent. But, it's an easy issue, and newcomers long for easy issues. We're pinging only to make sure that it's being worked on. I'll remove the "C-assigned" tag for now, so that someone else can work on this. If no one has fixed this when you're back, or if you want me to find another easy issue for you, please feel free to ping me :smile:

**Comment by RockyTV** [comment]
I'd like to have a try at implementing this issue, if that's okay...

**Comment by Wafflespeanut** [comment]
Please go ahead! :)

**Comment by KiChjang** [comment]
@RockyTV Have you already started work on this? It looks like @ctjhoa has already submitted a PR for this issue. Would you care to work on #14108 instead?
