### ISSUE TITLE
Implement ToCss serialization for CSSRules

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#14195]
For CSSOM, we need to be able to serialize the variants of [`CSSRule`](https://doc.servo.org/style/stylesheets/enum.CssRule.html). While https://github.com/servo/servo/pull/14190 adds a `ToCss` implementation for `StyleRule`, the other variants cannot be serialized yet. These implementations should be added.

Less easy, because serialization isn't always specced and you have to reverse-engineer it from the grammar.

cc @canaltinova

**Comment by Manishearth** [comment]
Some of these are specced at https://drafts.csswg.org/cssom/#serialize-a-css-rule

If you come up with serialization steps, we should try and get them merged into the spec too.

**Comment by canaltinova** [comment]
I'll work on this.
