### ISSUE TITLE
crash in rule_tree::pop_from_free_list

### ISSUE THREAD

**Issue by bholley** [servo/servo#14213]
Loading http://spectrum.ieee.org/video/geek-life/tools-toys/this-water-jet-cutter-can-slice-through-anything-steel-glass-or-steak in Servo, I hit the following:

https://pastebin.mozilla.org/8928296

The stack from lldb is a bit more illuminating: https://pastebin.mozilla.org/8928301

Basically, we're finalizing the Window on the script thread, and then we end up in alloc::arc::{{impl}}::drop<std::sync::mutex::Mutex<layout::query::LayoutThreadData>>

That seems to suggest that we're dropping an Arc to layout data on the script thread, which seems problematic.

LayoutRPCImpl looks questionable: https://github.com/servo/servo/blob/f48b3fe2197a59b29bc711fb1b5496cbb97bd330/components/layout/query.rs#L85

And we send it over to the layout thread here: https://github.com/servo/servo/blob/9467fbe26d25dfc633d5ab8973fe459d14eff9dc/components/layout_thread/lib.rs#L629

We've got an Arc<Mutex<T>>, so from the Type system's perspective this is all kosher. Do we need to mark StrongRuleNode as non-Send? Or should we remove the assertion?

CC @emilio @jdm

**Comment by emilio** [comment]
Ok, I was worried for a second this could be dropping node's data inside script.

We're finalizing the window after layout, which I think it's... not quite the expected, and probably should be investigated a bit more.

Probably the assertion should be removed, but I think it's not quite the expected thing in any case.

**Comment by jdm** [comment]
I'll defer to people like @emilio and @pcwalton here.

**Comment by nox** [comment]
Original page doesn't panic anymore, and #14278 is supposed to have fixed the problem. Closing this.
