### ISSUE TITLE
Logical properties aren't cascading correctly

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#14222]
Wikipedia in stylo has odd margins due to logical properties being used in the Firefox user agent stylesheet.

Turns out that in my implementation, the logical properties cascade independently. However, the spec says

> A computed value that has logical and physical properties is determined by applying the CSS cascade to declarations of both.

A minimal testcase follows. When correctly implemented, it should show two dissimilar boxes. In Servo/Stylo, it shows the same box twice, because the `block-size` declaration overrides the `height` one (same for inline-size) even though it has lower specificity (since there is no `block-size` decl of higher specificity).

<details>

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <style type="text/css">
      div {
        block-size: 100px;
        inline-size: 10px;
        background-color: red;
      }
      #foo {
        height: 20px;
        width: 200px;
      }
    </style>
</head>
<body>
<div id=foo></div>
<br>
<div></div>
</body>
</html>
```

</details>

I think a simple fix would be to have the logical properties use the bitfield setters of the physical ones. We already sort by specificity before applying, so just skipping properties we have seen should be enough. I think.

thoughts? @emilio 

I'll look into this tomorrow.

cc @heycam

**Comment by emilio** [comment]
Yes, using the same field or checking for both properties works.
