### ISSUE TITLE
requestAnimationFrame not synchronized with render

### ISSUE THREAD

**Issue by MortimerGoro** [servo/servo#14235]
Hi,

There are some flickering issues in WebGL demos. Some tests:

* On slower computers more noticeable than on faster ones: tested on Macbook Pro 2011 and a new desktop with GTX 1060.
* If the window is not focused the flickering increases

The rendering to the WebGL Context texture itself is ok. In the WIP WebVR implementation, I'm able to render to the texture at 90fps, submit the texture to the HMD and there aren't flickering issues.

This seems to be synchronization problem between Servo, Webrender and the JS requestAnimationFrame callbacks. I have created a minimal testcase that reproduces this, which runs this set of gl commands in a requestAnimationFrame loop:

```
gl.viewport(0, 0, gl.viewportWidth, gl.viewportHeight);
gl.clearColor(0.0, 1.0, 0.0, 1.0);
gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
gl.clearColor(1.0, 0.0, 0.0, 1.0);
gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
gl.clearColor(0.0, 0.0, 0.0, 1.0);
gl.flush();
```

This simple code must always render a red canvas, because the last gl.clear(..) call uses a red color. But in servo sometines flickers with a green color, which is related to the previous gl.clear(..) call with a green color. 

I have added some logs in Servo & WR, these are the results:

The red frames are the one with those logs:

```
JS animation begin
Apply WebGL Command: None => CanvasWebGLMsg::Viewport(..)
Apply WebGL Command: None => CanvasWebGLMsg::ClearColor(..)
Apply WebGL Command: None => CanvasWebGLMsg::Clear(..)
Apply WebGL Command: None => CanvasWebGLMsg::ClearColor(..)
Apply WebGL Command: None => CanvasWebGLMsg::Clear(..)
Apply WebGL Command: None => CanvasWebGLMsg::ClearColor(..)
Apply WebGL Command: None => CanvasWebGLMsg::Flush(..)
Glutin present begin
webrender build scene begin
webrender build scene end
webrender render begin
webrender render end
JS animation end
Glutin present end

```

The green frames are the ones with:

```
JS animation begin
Apply WebGL Command: None => CanvasWebGLMsg::Viewport(..)
Apply WebGL Command: None => CanvasWebGLMsg::ClearColor(..)
Apply WebGL Command: None => CanvasWebGLMsg::Clear(..)
webrender build scene begin
webrender build scene end
webrender render begin
Glutin present begin
webrender render end
Apply WebGL Command: None => CanvasWebGLMsg::ClearColor(..)
Apply WebGL Command: None => CanvasWebGLMsg::Clear(..)
Apply WebGL Command: None => CanvasWebGLMsg::ClearColor(..)
Apply WebGL Command: None => CanvasWebGLMsg::Flush(..)
JS animation end
Glutin present end
```
It's seems clear that there are synchronization problems. 

Is this a known problem and expected to be fixed?

**Comment by larsbergstrom** [comment]
cc @glennw

**Comment by emilio** [comment]
It's probably a known problem, we need to sync requestAnimationFrame callbacks per spec before painting...

But we don't do it right now. I have #13864 that conforms a bit more to the order the spec requires. That may help something, but I think we'd still trigger a paint before running animation frame callbacks.

**Comment by MortimerGoro** [comment]
@emilio I have tried #13864 but still the same problem
