### ISSUE TITLE
Changing background color on twitter causes lots of layout time

### ISSUE THREAD

**Issue by jrmuizel** [servo/servo#14240]
This page should have a flashing background color but Servo's layout can't keep up.

https://people-mozilla.org/~jmuizelaar/webrender/sites/twitter-refresh-reduce.html

@pcwalton

**Comment by hcorion** [comment]
Woah, seizure warning maybe?

**Comment by nox** [comment]
@jrmuizel The sample is gone, do you still have it somewhere?

**Comment by jdm** [comment]
Testcase is no longer available.
