### ISSUE TITLE
Space Jam planet out of place

### ISSUE THREAD

**Issue by metajack** [servo/servo#14242]
<img width="1136" alt="screenshot 2016-11-15 21 57 51" src="https://cloud.githubusercontent.com/assets/28357/20335423/b078401a-ab7f-11e6-846a-b744cd7555c8.png">

The Warner Studio Store planet is moved over to the left for some reason.

**Comment by mbrubeck** [comment]
This is caused by #11297.

**Comment by sviter** [comment]
It's work now for me
