### ISSUE TITLE
First launch on macbook pro Sierra

### ISSUE THREAD

**Issue by jespersh** [servo/servo#14259]
I downloaded the Servo nightly for Mac (from https://download.servo.org/nightly/mac/servo-latest.dmg) and dragged the icon to applications then from applications to the bar and right click opened and was met by... This "window".

Nightly version: Servo 0.0.1-f14e733

![screenshot 2016-11-17 14 33 21](https://cloud.githubusercontent.com/assets/1004198/20391254/dfaf320e-acd2-11e6-935b-6846f7957fb0.png)

Clicked around a bit, then it closed by itself.
I reopened and was met by a new window
![screenshot 2016-11-17 14 36 55](https://cloud.githubusercontent.com/assets/1004198/20391370/6094cf96-acd3-11e6-8386-2b8d6e5a9b5c.png)

By moving my mouse around it seems like there's a set of 3x3 tiles. Can click them and it would appear something else loads, but the same kind of white/black nothingness.

Can't figure out where the logs are placed if any

**Comment by paulrouget** [comment]
Could it be this? https://github.com/servo/servo/issues/13953

**Comment by paulrouget** [comment]
@jespersh macbook or macbook pro?

**Comment by jespersh** [comment]
Macbook Pro
Quite possible. I can't figure out how to produce logs to verify a coalition

**Comment by jespersh** [comment]
If I use ./servo -M -S, then I get the errors from the logs in #12753
About that it cannot connect to com.apple.fonts and cannot find LucidaGrande locally

**Comment by glennw** [comment]
@paulrouget I don't have access to a mac that can run sierra sorry. Perhaps @pcwalton might have some ideas?

**Comment by jespersh** [comment]
I am available on #servo

**Comment by paulrouget** [comment]
Duped in favor of #13953

**Comment by paulrouget** [comment]
Actually - I'm not 100% sure it's the same issue. I tried with my macbook pro with Sierra, I don't have any problem.

**Comment by paulrouget** [comment]
@jespersh can you try with the integrated and the discrete gpu see if it makes a difference?

**Comment by jespersh** [comment]
Graphics info for tracking:
  Chipset Model:	Intel Iris Graphics 6100
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x162b
  Revision ID:	0x0009

**Comment by jespersh** [comment]
> @jespersh can you try with the integrated and the discrete gpu see if it makes a difference?

For reference outside of IRC, this macbook pro only has an integrated graphics card. Model is in previous comment

**Comment by paulrouget** [comment]
This appears to work for me now. See https://github.com/servo/servo/issues/13953#issuecomment-265806653

Closing. If anyone is still experimenting this graphic glitch, feel free to comment/re-open.
