### ISSUE TITLE
Upgrade dist on Travis CI

### ISSUE THREAD

**Issue by upsuper** [servo/servo#14257]
In #14244, I'm adding libbindgen as a build dependency for geckolib.

libbindgen requires libclang 3.8 to work, however, in the current version of Linux distribution we use on Travis CI (which is Ubuntu 14.04LTS), version of libclang is 3.4. libclang 3.8 is included in Ubuntu 16.04LTS (xenial). Could we upgrade the dist to that version?

**Comment by SimonSapin** [comment]
Looks like the default is 12.04 and we can opt into 14.04, but I don’t see anything about 16.04. Can we get clang from another source than official Ubuntu repositories?

https://docs.travis-ci.com/user/ci-environment/
https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by upsuper** [comment]
We probably can do [what rust-bindgen currently does](https://github.com/servo/servo/pull/14244#issuecomment-261201975).

**Comment by nox** [comment]
I don't think this has been an issue in the end. Closing.
