### ISSUE TITLE
assertion failed: self.suspended_since.get  .is_some  

### ISSUE THREAD

**Issue by adamtoms** [servo/servo#14264]
Opened new tab, searched using address bar then clicked back button to left. 

Wont let me copy the warning messages either.

assertion failed: self.suspended_since.get  .is_some   ### URL: ### Servo Version: Servo 0.0.1-f14e733 ### Backtrace:     WARNING: Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId 1 , index ..
<img width="1010" alt="screen shot 2016-11-17 at 16 53 27" src="https://cloud.githubusercontent.com/assets/5364511/20398717/621f90c2-ace6-11e6-997f-698628188f4a.png">
.     This report was generated by the browser.html issue reporter.

**Comment by nox** [comment]
```
± gg -F 'self.suspended_since.get'
components/script/timers.rs:182:        assert!(self.suspended_since.get().is_none());
components/script/timers.rs:217:        match self.suspended_since.get() {
components/script/timers.rs:234:        if self.suspended_since.get().is_some() {
components/script/timers.rs:245:        let additional_offset = match self.suspended_since.get() {
components/script/timers.rs:258:        if self.suspended_since.get().is_some()
```

This assertion is entirely gone. Closing.
