### ISSUE TITLE
Switch from rust-openssl to rust-native-tls?

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#14265]
Effectively, this would remove the OpenSSL dependency on MacOS and Windows; it changes these platforms to use Security Framework and schannel (respectively).

Repos:

* https://github.com/sfackler/rust-openssl
* https://github.com/sfackler/rust-native-tls

Example of how to accomplish this: https://github.com/seanmonstar/reqwest/blob/master/src/tls.rs

**Comment by frewsxcv** [comment]
I'd be happy to open a pull request for this if desired.

**Comment by kaksmet** [comment]
There have been a discussion about which TLS library to use on the [mailing list](https://groups.google.com/forum/#!topic/mozilla.dev.servo/3mfkRehXAo4) that may be of interest.

**Comment by avadacatavra** [comment]
I'm going to close this--there should be another discussion thread about TLS libraries soon. The general plan is to work towards removing the openssl dependency and move towards a rust based library
