### ISSUE TITLE
`Stylist::set_device` shoud check stylesheet media queries

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#14279]
In `components/style/selector_matching.rs`, the `set_device` method of `Stylist` recursively finds `@media` rules inside stylesheets and checks if the evaluation of any media query has changed. But stylesheets can also have media queries (for example `<style media="(min-width: 400px)">…</style>`) and these are currently not checked. This MQ is stored in the `media` attribute of the `Stylesheet` struct.

Before fixing this, it would be best to write a test that is currently buggy. On way to do this might be to have an iframe whose width changes, and have JS code inside it that uses `getComputedStyle` before and after the change to observe the value of some property affected by a stylesheet media query. With `selector_matching.rs` as in current master, the value after should be the same as before because style has not be recomputed when it should have. Changing `selector_matching.rs` to check `stylesheet.media` should fix that bug and make the test pass.

**Comment by iamrohit7** [comment]
I would like to work on this.

**Comment by jdm** [comment]
@iamrohit7 Please do! Ask questions if anything is unclear.

**Comment by iamrohit7** [comment]
Is this a WPT test that I need to add?

**Comment by SimonSapin** [comment]
The `tests/wpt/README.md` file contains directions, with a "Writing new tests" section. Tests from CSSWG are in `tests/wpt/css-tests`, but since it’s not as easy to send upstream new such tests, we usually create them in `tests/wpt/mozilla`. So a command like this should create a file and add it to the manifest:

```
./mach create-wpt tests/wpt/mozilla/tests/css/stylesheet_media_queries.html

**Comment by SimonSapin** [comment]
And to use `testharness.js`: http://testthewebforward.org/docs/testharness-library.html
