### ISSUE TITLE
Support for DOM Document's missing attributes/methods

### ISSUE THREAD

**Issue by brunoabinader** [servo/servo#1428]
Spec:
http://dom.spec.whatwg.org/#interface-document

Most of `Document.webidl` attributes and methods are currently commented. Some work is already ongoing (see issue #934 & issue #1391 ).

**Comment by dralley** [comment]
I'm guessing this can be closed?

**Comment by jdm** [comment]
This issue doesn't serve a useful purpose any more. Better to file issues for individual missing attributes or methods.
