### ISSUE TITLE
Fix border-image-outset parsing

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14295]
#14261 replaced  `LengthOrNumber` with `Either<Length, Number>`. While making that change, I somehow didn't notice that `border-image-outset` actually takes only a non-negative number.

We should add a new method `parse_non_negative_number` to the existing `LengthOrNumber` which should do something like [this](https://github.com/Wafflespeanut/servo/blob/6ac3fcbfeb6e36ced0b20d6e6483f07513d842c6/components/style/values/mod.rs#L135-L139) (only difference is that we'll be making use of `Length, Number` instead of `A, B` and use `parse_non_negative` for `Number`).

Once that's done, we should make `border-image-outset` parsing code [here](https://github.com/Wafflespeanut/servo/blob/6ac3fcbfeb6e36ced0b20d6e6483f07513d842c6/components/style/properties/longhand/border.mako.rs#L245) to make use of that method instead of the default `parse`.

**Comment by emilio** [comment]
Please add a test for it too. You can use the existing parsing/serialization tests in `tests/unit/style/`.

**Comment by jcdyer** [comment]
I'll take this one on.

**Comment by Wafflespeanut** [comment]
It's yours! Feel free to ping us at the #servo channel in IRC or comment here in case you need any help! :)

**Comment by jcdyer** [comment]
Ok, I've got a first-pass fix.  All the other tests in the test file run against the shorthand, but I'm testing against the longhand.  If that's not desirable, I can update it.
