### ISSUE TITLE
Prefer Either type for UrlOrNone

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14298]
We have an enum `UrlOrNone` [here](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/values/specified/mod.rs#L518). This should really be a type alias of `Either<SpecifiedUrl, None_>` instead. We already have a similar alias for `LengthOrNone` [here](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/values/specified/length.rs#L947), which should help. Once that's been done, the `ToCss` and the `parse` impls can then be removed.

**Comment by thiagopnts** [comment]
I'll be working on this one

**Comment by KiChjang** [comment]
Go right ahead!
