### ISSUE TITLE
Prefer Either type for column-gap

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14297]
Declare a new type alias `LengthOrNormal` in both [computed](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/values/computed/length.rs) and [specified](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/values/specified/length.rs) modules (it should make use of the `Normal` unit struct declared [here](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/values/mod.rs#L98)). We already have a similar type `LengthOrNone` in those modules (which makes use of `None_`), so that should help.

Once that's done, move on to the `column-gap` code [here](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/properties/longhand/column.mako.rs#L172). Instead of using `helpers:longhand`, we should use `helpers.predefined_type`. The caller would be very similar to [what we do](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/properties/longhand/effects.mako.rs#L874-L878) for `perspective`, with the only additional argument `parse_method='parse_non_negative_length'`.

<s>Note that this should wait on #14296 to be merged.</s>

**Comment by AgostonSzepessy** [comment]
I'd like to try this one.

**Comment by Wafflespeanut** [comment]
Okay, but please wait until #14296 lands, since `parse_non_negative_length` won't be available before that.

**Comment by Wafflespeanut** [comment]
@AgostonSzepessy The PR has merged (in case you haven't noticed). Feel free to work on it :)

**Comment by AgostonSzepessy** [comment]
@Wafflespeanut Thanks for letting me know!

In `/components/style/values/specified/length.rs` `LengthOrNumber` implements `parse_non_negative`. Will I also have to do that for `LengthOrNormal` or does `Either` take care of that?

**Comment by Wafflespeanut** [comment]
Yeah, it's now a generic  [`parse_non_negative_length`](https://github.com/Wafflespeanut/servo/blob/dc7c1c62706d56d9e83c1edc665b95abd93181b8/components/style/values/specified/length.rs#L346) for `Either<Length, T>`. You can use it directly :)

**Comment by Wafflespeanut** [comment]
@AgostonSzepessy Any news?

**Comment by AgostonSzepessy** [comment]
@Wafflespeanut Sorry, I've been pretty busy with the end of the semester in school and exams are coming up, so I won't be able to work on it for about 2 weeks. If you want, you can unassign me.

**Comment by Wafflespeanut** [comment]
No worries!

**Comment by DominoTree** [comment]
I'll take this one!

**Comment by Wafflespeanut** [comment]
@DominoTree  Great! Feel free to ping us at the #servo channel in IRC or comment here in case you need any help!

**Comment by DominoTree** [comment]
I opened a PR, - [components/layout/multicol.rs](https://github.com/servo/servo/blob/master/components/layout/multicol.rs#L103) needed a tweak to make it work with LengthOrNormal but I think it's sorted.

**Comment by DominoTree** [comment]
Think that finally did it :)
