### ISSUE TITLE
Several tests timeout on build machines under load.

### ISSUE THREAD

**Issue by glennw** [servo/servo#14301]
Specifically:

mozbrowserlocationchange_event.html
reload.html
many-draw-calls.html

Each of these tests runs several asynchronous operations and can time out when many tests are running in parallel.

**Comment by nox** [comment]
* `many-draw-calls.html` and `mozbrowserlocationchange_event.html` are marked as timeout.
 * `reload.html` is an intermittent crash (#15988).
 * `mozbrowserlocationchange_event.html` is an intermittent crash (#14338).

No reason to keep this issue open.
