### ISSUE TITLE
Each script thread should own a layout thread factory

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14328]
At the moment, when a script thread wants to create a new layout thread, it sends a message to one of the existing layout threads asking for it to spawn. It would be simpler just to provide the script thread with a layout thread factory, and would also deal with the corner case where a script thread has no attached layouts, but is asked to create a layout thread.

cc @jdm

**Comment by Ms2ger** [comment]
Please don't do anything here before I manage to land #13996.

**Comment by asajeffrey** [comment]
Will do.

**Comment by asajeffrey** [comment]
Even better, as @emilio said, we could just have one layout thread per script thread #14885, which would remove the need for the script thread to be spawning new layout threads.

**Comment by asajeffrey** [comment]
Closing in favour of #14885.
