### ISSUE TITLE
Property declaration block serialization should check for importance

### ISSUE THREAD

**Issue by emilio** [servo/servo#14329]
See https://drafts.csswg.org/cssom/#serialize-a-css-declaration-block (step 3.3.2.4):

> If there is one or more CSS declarations in current longhands have their important flag set and one or more with it unset, continue with the steps labeled shorthand loop.

Just creating it since it doesn't seem to be tracked. There's a `TODO` in declaration_block.rs line 99 in this regard.

cc @Manishearth @SimonSapin and @canaltinova (who could be interested in working on this)

I don't have a clear estimate of how easy or hard this can be. Probably not too much, but should be backed with tests.

**Comment by canaltinova** [comment]
I can give this one a try

**Comment by canaltinova** [comment]
To test this one properly, looks like `CSSStyleRule.style` needs to be implemented. There is an open PR for it. I'm waiting that one for merge.

**Comment by Manishearth** [comment]
You should be able to test it with `element.style`
