### ISSUE TITLE
Scrolling on pinterest.com is buggy

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#14336]
A few things:

1. scrolling the page scrolls a "shadow copy" of the text at the bottom, so it becomes doubled up
2. after switching windows and coming back, the bottom bar of text has moved up like so
![screen shot 2016-11-22 at 9 06 05 pm](https://cloud.githubusercontent.com/assets/1565842/20551669/9089ce2c-b0f7-11e6-9aad-f4ca72a877f0.png)
3. also the background has now stopped scrolling
4. scrolling now moves the text up and down, but there is no more 2nd copy

@pcwalton @glennw

**Comment by nox** [comment]
Scrolling seems ok now, or at least not in any way more broken than elsewhere, thanks to #18769. Closing.
