### ISSUE TITLE
Prefer "Either" type for column-width

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14350]
- Declare a new type alias `LengthOrAuto` in both [computed](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/values/computed/length.rs) and [specified](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/values/specified/length.rs) modules (it should make use of the `Auto` unit struct declared [here](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/values/mod.rs#L97)). We already have a similar type `LengthOrNone` in those modules (which makes use of `None_`), so that should help.
- Once that's done, move on to the `column-width` code [here](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/properties/longhand/column.mako.rs#L10). Instead of using `helpers:longhand`, we should use `helpers.predefined_type`. The caller would be very similar to [what we do](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/properties/longhand/effects.mako.rs#L874-L878) for `perspective`, with the only additional argument `parse_method='parse_non_negative_length'`.
- Next stop is to autogenerate the gecko glue. For that to work, we need to `impl GeckoStyleCoordConvertible for Auto` [here](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/gecko/values.rs). It should make use of `CoordDataValue::Auto` (should be pretty straightforward).
- Moving on, we already have a [list of predefined types](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/properties/gecko.mako.rs#L489). With your new `impl`, the `LengthOrAuto` can now go into that dictionary with the value `impl_style_coord`. Then, we can safely remove `column-width` [here](https://github.com/servo/servo/blob/72e4c6dc21c132d49cf0a5f68a3ba45d16cc8322/components/style/properties/gecko.mako.rs#L2247) and the corresponding methods following it (`set_` and `impl_coord_copy`).

This would best serve as a good second bug (i.e., for people who've already worked on easy bugs in `style` crate and have some beginner's experience in Rust). Feel free to ask any questions though :)

**Comment by Razican** [comment]
Hi! I would like to work in this issue, if it's OK :)

**Comment by KiChjang** [comment]
@Razican I've highlighted another issue that you can work on. This should better be left as a second bug rather than a first bug.

**Comment by jcdyer** [comment]
I'll take this one one.  I just did a good starter bug in the same part of the code base.

**Comment by Wafflespeanut** [comment]
Great! :)

**Comment by jcdyer** [comment]
Had a little trouble with the gecko glue, but I think I figured it out.
