### ISSUE TITLE
inline-block causes twitter layout problems

### ISSUE THREAD

**Issue by jrmuizel** [servo/servo#14352]
https://people-mozilla.org/~jmuizelaar/bugs/twitter-reduce.html renders wrong in Servo. This is a reduced version of https://people-mozilla.org/~jmuizelaar/webrender/sites/twitter.html

Removing the "display: inline-block" from the Icon class fixes the layout.

@pcwalton

**Comment by stshine** [comment]
duplicate of #13683.
