### ISSUE TITLE
Update property hacking guide wiki

### ISSUE THREAD

**Issue by chenpighead** [servo/servo#14369]
Since `column-width` has been used as an example for [property hacking guide](https://github.com/servo/servo/wiki/Property-hacking-guide), maybe we should consider update wiki once #14350 has been done. Maybe updating 'column-width' as an `helpers.predefined_type` example and adding another 'not predefined_type' example could be an option.

Second thoughts, we could just update 'column-width' to another property without waiting. #14350 should not block this issue I think.

cc @Wafflespeanut

**Comment by Wafflespeanut** [comment]
We [already have an example](https://github.com/servo/servo/wiki/Stylo-hacking-guide#implementing-a-predefined-type-property) for `predefined_type`.  I'll replace `column-width` once the issue's resolved. Thanks for reminding :)

**Comment by nox** [comment]
IMO this wiki page should just be killed, given how outdated it got.

Cc @emilio @bholley.

**Comment by emilio** [comment]
Agreed, just did that.
