### ISSUE TITLE
Transitory initial width and height for windows in iframes

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14364]
When an iframe is first created, its `window_size` is set to `None`. This is later set by `Constellation::handle_iframe_size_message` (https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L1312) in response to a `FrameSize` event from the compositor, which contains the size calculated by webrender in `RenderNotifier::pipeline_size_changed` (https://github.com/servo/servo/blob/master/components/compositing/compositor.rs#L334).

This is fine, except that it means script may be able to see a transitory zero value for the calculated height and width, if it queries the window size before webrender has reported.

Reported by @Ms2ger on irc: http://logs.glob.uno/?c=mozilla%23servo&s=24+Nov+2016&e=24+Nov+2016#c568181

**Comment by nox** [comment]
@asajeffrey Are you still working on this?

**Comment by asajeffrey** [comment]
Not actively. cc @cbrewster
