### ISSUE TITLE
get_primary_service doesn't check blocklist or allowed services

### ISSUE THREAD

**Issue by jdm** [servo/servo#14409]
The spec annotation steps in #14407 helped me realize that get_primary_service and get_primary_services implement the same algorithm but have different behaviour. The spec says that the service returned from get_primary_service should not be blocklisted and should be in the list of allowed services.

cc @dati91 @zakorgy

**Comment by jdm** [comment]
get_included_service seems to also be missing these checks.

**Comment by dati91** [comment]
We check for blocklist [here](https://github.com/servo/servo/blob/master/components/script/dom/bluetoothremotegattserver.rs#L104) and for the allowed services [here](https://github.com/servo/servo/blob/master/components/bluetooth/lib.rs#L670).

**Comment by jdm** [comment]
What is the purpose of checking the blocklist in get_primary_services, in that case?

**Comment by jdm** [comment]
Disregard that question, I read the code and it makes more sense.
