### ISSUE TITLE
Implement backoff to a fake refresh driver if the page abuses requestAnimationFrame()

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#14417]
We see too many pages, like nytimes.com, that perpetually run `requestAnimationFrame()` callbacks that do nothing. In Servo, because we try to synchronize rAF precisely with VBLANK, we have to actually draw something in order to perform `requestAnimationFrame()`. This means that pages like NYT are constantly drawing and eating CPU.

I propose that we detect this kind of abuse—repeated rAF without any changes that actually necessitate redraw—and switch to a timeout that approximates the screen's refresh rate until the page is actually changed during the rAF.

I know that @paulrouget noticed this problem several months ago and at the time I said I couldn't do anything about it. But I didn't think of this solution back then :)

**Comment by nox** [comment]
Seems like this could be made into an interesting mentored project, if anyone is willing to do that.

**Comment by nox** [comment]
Cc @emilio @jdm @Manishearth

**Comment by jdm** [comment]
This code already exists because pcwaltom wrote it
