### ISSUE TITLE
Can't do Android builds on MacOS

### ISSUE THREAD

**Issue by newchief** [servo/servo#1442]
I tried on Linux and MacOSX with no luck. I tried to use NDK and SDK installed in $HOME, then I also tried to build with NDK and SDK moved to /opt, still the same.
Some facts:
1. when I take sources from official rust reopsitory, I am able to build rustc with Android target support
2. I am able to build rustc (and whole servo) from servo repository when I build without Android target support
3. I am following building suggestions from wiki page
4. Seems like system headers from /usr/include are taken instead of ndk_standalone ones
Error message on MacOSX is:
  CC(target) obj.target/libuv/src/unix/tty.o
  CC(target) obj.target/libuv/src/unix/udp.o
  CC(target) obj.target/libuv/src/unix/proctitle.o
  CC(target) obj.target/libuv/src/unix/linux-core.o
../../../../../../../../src/compiler/rust/src/libuv/src/unix/linux-core.c:33:23: warning: sys/prctl.h: No such file or directory
../../../../../../../../src/compiler/rust/src/libuv/src/unix/linux-core.c:34:25: warning: sys/sysinfo.h: No such file or directory
../../../../../../../../src/compiler/rust/src/libuv/src/unix/linux-core.c:52:30: warning: linux/if_packet.h: No such file or directory
...errors that follow are consequences of missing headers.

These missing headers are absent in MacOSX as they are Linux specific and are present in ndk_standalone.
Similar problem on Linux: when compiling this part of rustc, it chokes on pthread.h taken from /usr/include which differs from the one shipped with ndk_standalone.

**Comment by larsbergstrom** [comment]
This should be working now.
