### ISSUE TITLE
stylo: rust-bindgen checkout under servo doesn't like to be built due to servo's workspace

### ISSUE THREAD

**Issue by heycam** [servo/servo#14455]
Since #14381, running `setup_bindgen.sh` tells me this:

```
/z/incubator-stylo/servo/components/style/binding_tools $ ./setup_bindgen.sh 
Cloning into 'rust-bindgen'...
remote: Counting objects: 12505, done.
remote: Total 12505 (delta 0), reused 0 (delta 0), pack-reused 12505
Receiving objects: 100% (12505/12505), 7.74 MiB | 688.00 KiB/s, done.
Resolving deltas: 100% (9133/9133), done.
Checking connectivity... done.
error: current package believes it's in a workspace when it's not:
current:   /z/incubator-stylo/servo/components/style/binding_tools/rust-bindgen/Cargo.toml
workspace: /z/incubator-stylo/servo/Cargo.toml

this may be fixable by adding `components/style/binding_tools/rust-bindgen` to the `workspace.members` array of the manifest located at: /z/incubator-stylo/servo/Cargo.toml
```

I fixed this by putting an empty `[workspace]` section in the rust-bindgen checkout's `Cargo.toml`.  Now, I know that build time bindgen will solve this, but for the moment, what's the right solution here that we can check in?  I guess it's kind of bad practice to be checking out other repos like this directly inside the servo checkout.  So maybe we just need check out rust-bindgen elsewhere, outside of the servo checkout (or ask stylo developers to do this)?

Any thoughts, @emilio @SimonSapin @bholley @upsuper?

**Comment by emilio** [comment]
Probably the best solution is making bindgen use workspaces itself (to build at the same time both `libbindgen` and the executable), or cloning it elsewhere.

Looks like an edge case cargo could be interested in fixing though? cc @alexcrichton

**Comment by upsuper** [comment]
Isn't the easiest solution just adding `[workspace]` to rust-bindgen's `Cargo.toml`? That file shouldn't be updated frequently, so we shouldn't have much conflict there before we have build time bindgen.

Alternatively, we can probably check-in that change to rust-bindgen as a temporary workaround, or remove the `Cargo.toml` and `Cargo.lock` from the vendored servo in s-i?

**Comment by alexcrichton** [comment]
Oh this is an expected error with Cargo at least, and yeah either adding it to the same workspace or adding `[workspace]` should fix it.

**Comment by SimonSapin** [comment]
I’d prefer to to add rust-bindgen to servo’s top-level workspace, because that will add rust-bindgen and all of its dependency graph to the shared `Cargo.lock` file.

If I understand correctly, this would required either:
* we commit this addition to the repository and the presence of rust-bindgen’s source (or at least its `Cargo.toml` file?) likely becomes necessary (whereas currently it’s a `.gitignore`’d directory where a script can run `git clone`).
* or running the script will add to `Cargo.lock` changes that everyone has to be careful not to commit.

**Comment by upsuper** [comment]
Since rust-bindgen is now a build-dependency of geckolib, I think this is no longer an issue.
