### ISSUE TITLE
Implement "browsing context names" concept.

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#14453]
Concepts:

* https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-names

DOM APIs:

* [`name` attribute on `<iframe>`](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-iframe-name)
* [`name` attribute on `Window`](https://html.spec.whatwg.org/multipage/browsers.html#dom-name)
* [Named access on `Window`](https://html.spec.whatwg.org/multipage/browsers.html#named-access-on-the-window-object)

Disabled WPT tests:

* https://github.com/servo/servo/issues/12568

**Comment by jdm** [comment]
@paavininanda This would be a useful feature to add support for. There are a few parts to it that can be done separately:
* add the basic support for getting and setting Window.name
  * update Window.webidl to uncomment the name attribute
  * store a string member in components/script/dom/windowproxy.rs
  * have Window::GetName and Window::SetName interact with the window proxy
* support HTMLIFrameElement.name
  * uncomment the attribute from HTMLIFrameElement.webidl
  * have the getter and setter interact with the window proxy for the window inside the iframe
* notify the constellation whenever a window's name is updated
  * when setting from the iframe, send a message to the child window to ensure it receives the new name
  * when setting from the window, send a message to the parent iframe to ensure it receives the new name

**Comment by paavininanda** [comment]
@jdm I would like to take up this issue. 
Now for the SetName function, do i need to check any validity for `U+005F LOW LINE characters` ? Because I could't find any example where window.name="something" would throw an error in Chrome.

**Comment by jdm** [comment]
No. There are no checks anywhere whether the name matches the restrictions of a valid browsing context name.
