### ISSUE TITLE
Implement parsing/serialization for background-position-x/y properties

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#14458]
`background-position` is a longhand currently. We need to implement `background-position-x/y` longhands and make `background-position` a shorthand instead.

But currently [`Position`](https://doc.servo.org/style/values/specified/position/struct.Position.html) struct seems insufficient for this properties. We might need to add VerticalPosition and HorizontalPosition structs like these:
```rust
pub struct VerticalPosition {
    pub keyword: Option<VerticalKeyword>,
    pub position: Option<LengthOrPercentage>,
}
pub struct HorizontalPosition {
    pub keyword: Option<HorizontalKeyword>,
    pub position: Option<LengthOrPercentage>,
}
```
And we can change main Position struct afterwards:
```rust
pub struct Position {
    pub horizontal: Option<HorizontalPosition>,
    pub vertical: Option<VerticalPosition>,
}
```
Currently `Keyword` enum is used by both vertical and horizontal keywords. We need to add x/y-start and x/y-end as well. It might be better to split these enums but I'm not sure about it.
Well, we can reduce the structs without splitting the Keyword enums:
```rust
pub struct SubPosition {
    pub keyword: Option<Keyword>,
    pub position: Option<LengthOrPercentage>,
}
pub struct Position {
    pub horizontal: Option<SubPosition>,
    pub vertical: Option<SubPosition>,
}
```
Another option is to leave Position struct like this and make a new struct for position-x/y properties. But this is probably not a good choice.

I want to work on this, second structure looks better to me but I couldn't decide about it, any advice about this?

cc @Manishearth

**Comment by Manishearth** [comment]
I think we reuse the position struct for other things though. I'd create a new type.

**Comment by Manishearth** [comment]
Also, HorizontalKeyword/VerticalKeyword makes more sense imo

**Comment by canaltinova** [comment]
Can't we fix other reusages for this implementation? Creating a new type seems more straightforward but looks like it increases the code duplication.

**Comment by Manishearth** [comment]
I guess? Make sure that the basic-shape stuff still works.

**Comment by canaltinova** [comment]
Okay, I'll try to do this with HorizontalKeyword/VerticalKeyword then. Thanks!
