### ISSUE TITLE
Implement domain and path checks from https-cookie-alone-01

### ISSUE THREAD

**Issue by jdm** [servo/servo#14477]
https://www.ietf.org/id/draft-ietf-httpbis-cookie-alone-01.txt defines some steps to choose when cookies are valid choices to be evicted by a newer cookie. #14445 implemented some parts of this specification (specifically, ensuring that insecure cookies cannot evict secure cookies), but we still need to implement the more specific domain and path-matching checks.

**Comment by KiChjang** [comment]
Taking a look at this.
