### ISSUE TITLE
Build failing on OSX Yosemite 

### ISSUE THREAD

**Issue by Jayflux** [servo/servo#14483]
I'm not sure if there's already a ticket open for this, but builds are failing for me, even after ```mach clean```

https://gist.github.com/Jayflux/e38e6a950a988ac6fbfc2e40f15c1902

**Comment by Manishearth** [comment]
cc @fitzgen @jdm seems like a mozjs build failure

**Comment by Ms2ger** [comment]
Looks like you don't have yasm

**Comment by frewsxcv** [comment]
Make sure to install all the dependencies specified in the README: https://github.com/servo/servo#on-os-x-homebrew

**Comment by Jayflux** [comment]
ahh ok guys, will try that and get back to you thanks

**Comment by Jayflux** [comment]
This is now working thanks
