### ISSUE TITLE
Build Failing MSVC for mozjs_sys

### ISSUE THREAD

**Issue by Impally** [servo/servo#14487]
OS: Win 64 Python: 2.7.11 and Visual Studio: 2015 Community Edition

   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#f7917c48)
   Compiling script v0.0.1 (file:///D:/Projects/servo/components/script)
   Compiling openssl-sys-extras v0.7.14
   Compiling png v0.5.2
Build failed, waiting for other jobs to finish...
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#f7917c48)`
process didn't exit successfully: `D:\Projects\servo\target\debug\build\mozjs_sys-64ea4645edcc97f1\build-script-build` (exit code: 101)
--- stderr
makefile.cargo:101: *** recipe commences before first target.  Stop.
thread 'main' panicked at 'assertion failed: result.success()', D:\Projects\servo\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\f7917c4\build.rs:43
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build FAILED in 0:00:06

**Comment by Impally** [comment]
@larsbergstrom Was told to tag you for help.  Just pulled and am trying to build for the first time, any help would be appreciated, thanks.

**Comment by Impally** [comment]
Related to: https://github.com/servo/servo/issues/9989
All the build tools require VS and Python to be installed in the default locations on Windows.  Having Python in the path was not enough for mozjs.

**Comment by hsyan2008** [comment]
@Impally @jdm I have the same error on gentoo
error: failed to run custom build command for `mozjs_sys v0.50.0`                       
process didn't exit successfully: `/home/saxon/workspace/git/servo/target/release/build/mozjs_sys-9f6058514363d1bf/build-script-build` (exit code: 101)
...
...
thread 'main' panicked at 'assertion failed: result.success()', /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/build.rs:53:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

What can i do for ?

**Comment by jdm** [comment]
@hsyan2008 Please use http://gist.github.com/ to paste the full log; those lines are not enough to determine the problem.

**Comment by hsyan2008** [comment]
@jdm 
error: failed to run custom build command for `mozjs_sys v0.50.0`
process didn't exit successfully: `/home/saxon/workspace/git/servo/target/release/build/mozjs_sys-9f6058514363d1bf/build-script-build` (exit code: 101)            
--- stdout                                                 
[[ /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/configure -ot /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/configure.in ]] && touch /home/saxon/.carg
o/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/configure || true
[[ /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/old-configure -ot /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/old-configure.in ]] && touch /home/sax
on/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/old-configure || true
! [[ /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/configure.in -ot /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/configure ]] && touch /home/saxon/.ca
rgo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/configure || true
! [[ /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/old-configure.in -ot /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/old-configure ]] && touch /home/s
axon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/old-configure || true
if [[ /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/configure -nt /home/saxon/workspace/git/servo/target/release/build/mozjs_sys-b3e5d1cf4df64347/out/config.status ]] ; then \
  cd /home/saxon/workspace/git/servo/target/release/build/mozjs_sys-b3e5d1cf4df64347/out && \
  PYTHON="python" MOZ_TOOLS="" \                                                                                                                                
  CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \       
  /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --build-backends=RecursiveMake --enable-sm-promise --disable-shared-js || (cat conf
ig.log && exit 1) ; \                                            
fi                                                                                                                                                              
Creating Python environment         
Using real prefix '/usr'                                                                                                                                        
New python executable in /home/saxon/workspace/git/servo/target/release/build/mozjs_sys-b3e5d1cf4df64347/out/_virtualenv/bin/python
Installing setuptools, pip, wheel...done.                                                                                                                       
running build_ext                   
copying build/lib.linux-x86_64-2.7/psutil/_psutil_linux.so -> psutil                                                                                               
copying build/lib.linux-x86_64-2.7/psutil/_psutil_posix.so -> psutil
                                                                                                 
Reexecuting in the virtualenv                          
checking for a shell... /bin/sh                                                                                                                           
checking for host system type... x86_64-pc-linux-gnu
checking for target system type... x86_64-pc-linux-gnu                                  
checking for the Android toolchain directory... not found 
checking whether cross compiling... no
checking for pkg_config... /usr/bin/pkg-config
checking for pkg-config version... 0.29.2
checking for yasm... /usr/bin/yasm
checking yasm version... 1.3.0
checking for the target C compiler... /usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/gcc
checking whether the target C compiler can be used... INFO: checking for a shell...
INFO: /bin/sh
INFO: checking for host system type...
INFO: x86_64-pc-linux-gnu
INFO: checking for target system type...
INFO: x86_64-pc-linux-gnu
INFO: checking for the Android toolchain directory...
INFO: not found
INFO: checking whether cross compiling...
INFO: no
INFO: checking for pkg_config...
DEBUG: pkg_config: Trying pkg-config
INFO: /usr/bin/pkg-config
INFO: checking for pkg-config version...
DEBUG: Executing: `/usr/bin/pkg-config --version`
INFO: 0.29.2
INFO: checking for yasm...
DEBUG: yasm: Trying yasm
INFO: /usr/bin/yasm
INFO: checking yasm version...
DEBUG: Executing: `/usr/bin/yasm --version`
INFO: 1.3.0
INFO: checking for the target C compiler...
DEBUG: _cc: Trying gcc
INFO: /usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/gcc
INFO: checking whether the target C compiler can be used...
DEBUG: Creating `/tmp/conftest.TBB2Bv.c` with content:
DEBUG: | #if defined(_MSC_VER)
DEBUG: | #if defined(__clang__)
DEBUG: | %COMPILER clang-cl
DEBUG: | %VERSION _MSC_FULL_VER
DEBUG: | #else
DEBUG: | %COMPILER msvc
DEBUG: | %VERSION _MSC_FULL_VER
DEBUG: | #endif
DEBUG: | #elif defined(__clang__)
DEBUG: | %COMPILER clang
DEBUG: | #  if !__cplusplus || __cpp_static_assert
DEBUG: | %VERSION __clang_major__.__clang_minor__.__clang_patchlevel__
DEBUG: | #  endif
DEBUG: | #elif defined(__GNUC__)
DEBUG: | %COMPILER gcc
DEBUG: | %VERSION __GNUC__.__GNUC_MINOR__.__GNUC_PATCHLEVEL__
DEBUG: | #endif
DEBUG: |
DEBUG: | #if __cplusplus
DEBUG: | %cplusplus __cplusplus
DEBUG: | #elif __STDC_VERSION__
DEBUG: | %STDC_VERSION __STDC_VERSION__
DEBUG: | #elif __STDC__
DEBUG: | %STDC_VERSION 198900L
DEBUG: | #endif
DEBUG: Executing: `/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/gcc -E /tmp/conftest.TBB2Bv.c`

--- stderr
gmake: *** 没有指明目标并且找不到 makefile。 停止。
DEBUG: <truncated - see config.log for full output>
DEBUG: | %VERSION _MSC_FULL_VER
DEBUG: | #endif
DEBUG: | #elif defined(__clang__)
DEBUG: | %COMPILER clang
DEBUG: | #  if !__cplusplus || __cpp_static_assert
DEBUG: | %VERSION __clang_major__.__clang_minor__.__clang_patchlevel__
DEBUG: | #  endif
DEBUG: | #elif defined(__GNUC__)
DEBUG: | %COMPILER gcc
DEBUG: | %VERSION __GNUC__.__GNUC_MINOR__.__GNUC_PATCHLEVEL__
DEBUG: | #endif
DEBUG: |
DEBUG: | #if __cplusplus
DEBUG: | %cplusplus __cplusplus
DEBUG: | #elif __STDC_VERSION__
DEBUG: | %STDC_VERSION __STDC_VERSION__
DEBUG: | #elif __STDC__
DEBUG: | %STDC_VERSION 198900L
DEBUG: | #endif
DEBUG: Executing: `/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/gcc -E /tmp/conftest.TBB2Bv.c`
Traceback (most recent call last):
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/../../configure.py", line 93, in <module>
    sys.exit(main(sys.argv))
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/../../configure.py", line 22, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 260, in run
    func(*args)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 302, in _value_for
    return self._value_for_depends(obj)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/util.py", line 922, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 329, in _value_for_depends
    return func(*resolved_args)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 518, in wrapper
    ret = template(*args, **kwargs)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/build/moz.configure/checks.configure", line 53, in wrapped
    ret = func(*args, **kwargs)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/build/moz.configure/toolchain.configure", line 515, in valid_compiler
    info = check_compiler(wrapper + [compiler] + flags, language)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/build/moz.configure/toolchain.configure", line 297, in check_compiler
    info = get_compiler_info(compiler, language)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 773, in wrapped
    return new_func(*args, **kwargs)
  File "/home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/build/moz.configure/toolchain.configure", line 260, in get_compiler_info
    if line.startswith('%'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 6: ordinal not in range(128)
gmake: *** [makefile.cargo:140：maybe-configure] 错误 1
thread 'main' panicked at 'assertion failed: result.success()', /home/saxon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/build.rs:53:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...

**Comment by jdm** [comment]
Try running `export LANG=C` before building.

**Comment by hsyan2008** [comment]
@jdm Working fine for me, thanks very much!

**Comment by EricXu1990** [comment]
@jdm Thanks very much !
