### ISSUE TITLE
Keyboard input drop on Windows build

### ISSUE THREAD

**Issue by SaschaNaz** [servo/servo#14494]
Repro:
1. Type `github.com/servo/servo` on the address bar
2. Expected the exact string but found `github.com/serv/serv`

I know this is [an old known bug](https://github.com/servo/servo/issues/12125#issuecomment-235662934) but I couldn't find a separate GitHub issue for this.

**Comment by elahn** [comment]
Confirmed on Windows 10.0.14393 x64.

**Comment by BladeMight** [comment]
Yes, I have that too on Win7x64.

**Comment by atouchet** [comment]
This may be the same issue as #13366.

**Comment by elahn** [comment]
@atouchet that issue describes #12937, but this issue may also be involved in some cases.

**Comment by SaschaNaz** [comment]
This issue does not repro on today's build.

**Comment by jdm** [comment]
Thanks!
