### ISSUE TITLE
determine_request_referrer seems to be missing "TLS-protected" checks

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14506]
But note https://github.com/w3c/webappsec-referrer-policy/issues/82

**Comment by Ms2ger** [comment]
I expect we will need to do this check in the script thread before starting the fetch.

**Comment by nox** [comment]
Cc @avadacatavra

**Comment by pshaughn** [comment]
Spec updates have changed phrasing around considerably; they are now mostly asking "if environment's HTTPS state is modern". We don't have enough information coming in through determine_request_referrer's arguments to really answer that. As phrased in the spec, it depends on having the "environment settings object", which is not an actual struct in Servo as far as I'm aware.

**Comment by jdm** [comment]
We store the HTTPS state information in [the document](https://github.com/servo/servo/blob/12693b51f510761d5dd58a9103596a192edb803c/components/script/dom/document.rs#L327). We will need to propagate that information as part of net_traits::Request.

**Comment by splav** [comment]
@highfive: assign me

**Comment by jdm** [comment]
We will want to add the HTTPS state of the requester to [Request](https://github.com/servo/servo/blob/e26e864c61370b27a9868a059d91bcb360ce8b09/components/net_traits/request.rs#L318), so it can be passed to determine_request_referrer. It can be taken from the [requesting document](https://github.com/servo/servo/blob/e26e864c61370b27a9868a059d91bcb360ce8b09/components/script/dom/document.rs#L308) when creating a new request (and we should make this an automatic part of [fetch_async(https://github.com/servo/servo/blob/e26e864c61370b27a9868a059d91bcb360ce8b09/components/script/dom/document.rs#L1760) like the existing CSP support.
