### ISSUE TITLE
Implement Request::origin correctly

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14504]
`RequestInit` stores a `Url` rather than an origin, which seems weird. We also don't handle `Client` at all (we should do that in the script thread anyway). Some code in <https://github.com/Ms2ger/servo/tree/origin-request>.

Also kinda depends on implementing `Document`s origins correctly.

**Comment by brainlessdeveloper** [comment]
#16508

**Comment by nox** [comment]
```
    pub origin: ImmutableOrigin,
```
