### ISSUE TITLE
Add a test to verify that TrustedPromise does not implement Clone

### ISSUE THREAD

**Issue by jdm** [servo/servo#14500]
It is not a safe operation to clone a TrustedPromise, but it's really easy to derive Clone on the type and make it possible. We should add a test in https://dxr.mozilla.org/servo/source/tests/compiletest/plugin/compile-fail like:
```rust
fn cloneable<T: Clone>() {
}

fn main() {
    cloneable::<TrustedPromise>();
}
```

**Comment by Verlet64** [comment]
I'm a little green with Rust, but this seems a good place to start. I can take it on.

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear, and be sure to verify that the test works by deriving a Clone implementation for `TrustedPromise`.

**Comment by Verlet64** [comment]
@jdm I did it, but I would like some advice on the naming of the file before I submit any pull request etc. At the moment, it's the very verbose trustedpromise_mustnot_derive_clone.rs and though it conveys exactly what the test is for...it's very verbose, and if I'm honest doesn't seem to quite fit the naming convention the project has gone for. 

Help from more experienced hands would be much appreciated here. 

Thanks.

**Comment by jdm** [comment]
Perhaps `not_cloneable.rs`?

**Comment by Verlet64** [comment]
That sounds fine. 

I'll clean up then and go through the pull request checklist.
