### ISSUE TITLE
Update skia & azure; consider using skia directly

### ISSUE THREAD

**Issue by vvuk** [servo/servo#14503]
The Skia and Azure that are used by servo are from 2013.  They aren't used by much (Canvas, I think?), but they're still very out of date.  We should update them, or, likely a better option would be to create Skia bindings (perhaps via bindgen) and use Skia directly.  Having Skia bound in the rust ecosystem is useful beyond just Servo.

**Comment by jdm** [comment]
Perhaps we should move to https://github.com/DiamondLovesYou/skia-rs .

**Comment by vvuk** [comment]
Nothing to move to :( It looks like abandonware.  I'm making good progress for using bindgen with Skia; we can (and should) still write a higher level rust-y interface on top of it, but it may not be necessary right away.

**Comment by nox** [comment]
Did we take a decision for this?

**Comment by dralley** [comment]
Azure is dead
