### ISSUE TITLE
Same-origin checks in determine_request_referrer seem broken

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14505]
We compare the origin of the current URL (correct) with the referrer source (rather than the request's origin).

The request's origin is not implemented correctly at this point either (#14504), so not sure if it's useful to try to fix this issue before that's done.

**Comment by nox** [comment]
Cc @avadacatavra

**Comment by pshaughn** [comment]
#14504 has closed so maybe we can do this now.

**Comment by pshaughn** [comment]
I think #14507 is actually the only remaining case where we're doing this wrong, but I confess I'm not fully confident of that.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/b939b3806f698443e94cd33b8a3dac17a0fe62bb/components/net/http_loader.rs#L218-L220 is still wrong. We'll need to pass in the request's origin as another argument to that function.
