### ISSUE TITLE
Migrate from rust-websocket to ws-rs

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#14517]
rust-websocket appears to not be maintained anymore. Possibly migrate to ws-rs? This is sorta blocking the rust-openssl bump: https://github.com/servo/servo/pull/14484

https://github.com/cyderize/rust-websocket

https://github.com/housleyjk/ws-rs

**Comment by frewsxcv** [comment]
Actually, ws-rs is still using rust-openssl 0.7.x, so this can be done independently of the rust-openssl bump.

**Comment by shssoichiro** [comment]
I can work on this issue.

**Comment by shssoichiro** [comment]
Wanted to give an update: I'm making progress on this, but Servo's websocket code is tightly coupled with the `websocket` crate, so it's taking longer than expected. I hope to have an initial PR sometime this week.

**Comment by jdm** [comment]
Fantastic! Thanks for tackling it!

**Comment by shssoichiro** [comment]
Another update: It took longer than expected, but I'm finally victorious over the borrow checker and have this in a state where it compiles. There are a few failing tests, but they should be fairly easy to fix (once I comprehend the new output format for the WPTs).

**Comment by shssoichiro** [comment]
I've run into a bit of a problem in trying to fix `/websockets/interfaces/WebSocket/events/020.html` to work with this. When `ws` encounters an error on opening a connection before the connection is opened, it gives us two options: either log an error and return `Ok`, or panic. To fix this test, we need it to return an `Err` so we can handle it.

**Comment by jdm** [comment]
Sounds like we should file an issue upstream (and/or submit a PR if you're feeling adventurous).
