### ISSUE TITLE
Allow for redirects after a CORS-preflight

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14519]
https://github.com/whatwg/fetch/commit/0d9a4db8bc02251cc9e391543bb3c1322fb882f2
https://github.com/whatwg/fetch/issues/204
https://github.com/w3c/web-platform-tests/issues/2520

Code is in `components/net/fetch/methods,rs`, `fn main_fetch()`.

**Comment by Ms2ger** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=918767

**Comment by jdm** [comment]
@ferjm This is another network issue that you could work on.

**Comment by jdm** [comment]
I would like @avadacatavra to review the future PR that fixes this.

**Comment by ferjm** [comment]
It seems that Servo is already passing the [WPTs proposed for this](https://github.com/w3c/web-platform-tests/pull/4102).
- [fetch/api/redirect/redirect-count-cross-origin.html](https://gyazo.com/9ec9a1b1d5aa62f9bc8afcec0cda2f3a)
- [fetch/api/redirect/redirect-count-cross-origin-worker.html](https://gyazo.com/0f18db8fa478d5d3d79e3b953f889b10)

@jdm should I just wait for the tests to land and pull them from upstream?

**Comment by jdm** [comment]
Huh, I guess so!

**Comment by annevk** [comment]
Does Servo fail http://web-platform.test:8000/cors/redirect-preflight.htm then? It's not entirely clear to me the referenced WPT tests above actually test this.

**Comment by jdm** [comment]
Yes, it does.

**Comment by jdm** [comment]
Whoops, I mean that Servo passes redirect-preflight.htm.

**Comment by annevk** [comment]
That means Servo has the same bug as browsers do today and does not allow redirects after a preflight (likely resulting in a new preflight). So this still needs changes to the networking code.

**Comment by ferjm** [comment]
Ah, I missed the [comments](https://github.com/w3c/web-platform-tests/pull/4102#issuecomment-281350530) about the redirect-preflight.htm test. Thanks for the pointer @annevk. I'll work on the fix.

**Comment by ferjm** [comment]
Closed #14519 via #15889
