### ISSUE TITLE
Implement Subresource Integrity (SRI)

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14523]
https://w3c.github.io/webappsec-subresource-integrity/

**Comment by DominoTree** [comment]
I'm gonna start looking into this one

**Comment by jdm** [comment]
Great! Please ask questions if anything's unclear!

**Comment by mrnayak** [comment]
I am going to work on Implementing SRI fetch step.

**Comment by DominoTree** [comment]
@mrnayak I have been working on this some but if you'd like to take over this issue that's fine with me :)

**Comment by mrnayak** [comment]
Thanks @DominoTree, I can try to finish this.

**Comment by mrnayak** [comment]
Request verification algorithms part of the spec is still not implemented. This implementation probably needs #4577. We can reopen current issue or have a new issue for implementation of Request verification algorithms part of Subresource Resource Integrity.

**Comment by jdm** [comment]
A separate issue for that makes sense to me.
