### ISSUE TITLE
Block scripts with media/CSV mime types

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14520]
<https://fetch.spec.whatwg.org/#should-response-to-request-be-blocked-due-to-mime-type?>

**Comment by iamrohit7** [comment]
I would like to work on this.

**Comment by jdm** [comment]
This corresponds to part of step 16 of `main_fetch`. Please do!

**Comment by jdm** [comment]
The work in #14770 was on the right track but the author disappeared.
