### ISSUE TITLE
X11 with HighDPI screen renders at quarter-resolution

### ISSUE THREAD

**Issue by sstangl** [servo/servo#14525]
Recently-built Servo on Fedora 24 (X11, not Wayland) with a HighDPI display (Lenovo W540) creates a window with dimensions halved from expected values, so the window is extremely small and very difficult to read. On this system, xclock has the same behavior.

Servo version: Servo 0.0.1-5b389a2-dirty

**Comment by glennw** [comment]
We don't currently detect hidpi screens on Linux / glutin. You can manually run with --device-pixel-ratio=2 to set the scale appropriate for your screen.

**Comment by nox** [comment]
Closing as duplicate of #12054.
