### ISSUE TITLE
Review the creation of a new Response for the internal response

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14522]
Spec says

> Let internalResponse be response, if response is a network error, and response’s internal response otherwise.

We do

```rust
        let network_error_res;
        let internal_response = if let Some(error) = response.get_network_error() {
            network_error_res = Response::network_error(error.clone());
            &network_error_res
        } else {
            response.actual_response()
        };
```

It's not clear to me what the effect of that is.

**Comment by dpyro** [comment]
This substitutes `response.clone()` with `Response::network_error(error.clone())`. @KiChjang would be the relevant person to know the benefits of this.

**Comment by KiChjang** [comment]
@dpyro That's not the problem here. Nowhere in the code did we actually did `response.clone()`. The more pressing concern here is whether the `network_error_res` binding is necessary, and whether we could simply just call `.actual_response()` to capture the intent adequately as outlined in the spec.

**Comment by dpyro** [comment]
Doing some digging: In `main_fetch` before this code, `response` is created within the function and mutated into either `None`, `Response::network_error(…)`, `basic_fetch(…)`, or `http_fetch(…)`. 

- `None` is trivial.
- `Response::network_error(…)` sets `response.internal_response = None`.
- `basic_fetch(…)` either constructs a new `Response` and modifies `response.body` and `response.headers` or it returns a `Response::network_error(…)`.
- `http_fetch(…)` [does use a *response* and *actualResponse*](https://fetch.spec.whatwg.org/#http-fetch), so I am not certain here.

**Comment by nox** [comment]
I've patched stuff in this code, and to me it is correct and there is nothing else to be done with this issue. Closing.
