### ISSUE TITLE
Implement X-Content-Type-Options: nosniff

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#14521]

**Comment by dpyro** [comment]
On it. Looking into the fetch standard and the servo fetch implementation now.

**Comment by KiChjang** [comment]
Spec links:
https://fetch.spec.whatwg.org/#x-content-type-options-header
https://fetch.spec.whatwg.org/#should-response-to-request-be-blocked-due-to-nosniff?
https://fetch.spec.whatwg.org/#concept-main-fetch Step 16

**Comment by KiChjang** [comment]
This would most likely require [defining a new header using the `header!` macro](http://hyper.rs/hyper/v0.9.12/hyper/header/index.html#defining-custom-headers) provided by hyper. Note that `X-Content-Type-Options` is also a single-value header.

**Comment by dpyro** [comment]
Update: So far I’ve created an implementation and am currently testing and verifying it.
