### ISSUE TITLE
Replace MutJS<T> and MutNullableJS<T> with Cell<JS<T>> and Cell<Option<JS<T>>>

### ISSUE THREAD

**Issue by jdm** [servo/servo#14562]
I'm not convinced whether we should do this yet or not, but it's the next logical step after the changes in 1327ebd52f53f5f6637a12fab6cf0cad0aa0be6f. The documentation for `MutJS<T>` mentions GC barriers, but there are none in the code because they are unnecessary for `JS<T>` types. The only use of `MutJS<T>` is the debug assertions that verify that it's not being used by layout threads; everything else is just getting and setting the value inside the UnsafeCell. `MutNullableJS<T>` has some utility methods that we can define directly on `Cell<Option<JS<T>>>`, so we shouldn't lose any expressiveness.

The argument for this change is that it replaces less commonly-used types with more commonly understood ones. The argument against it is that we lose some debug assertions and add an extra level of generic types to some relatively common code.

**Comment by nox** [comment]
`JS<T>` isn't `Copy`. I don't want to make it `Copy` as long as the lint is broken, which it is currently.

**Comment by nox** [comment]
I don't see `Dom<T>` (formerly `JS<T>`) becoming `Copy` any type soon, and since this issue was failed we made even more libstd-dogfooding types illegal in tidy. Closing this issue.
