### ISSUE TITLE
duckduckgo.com shows a blank screen

### ISSUE THREAD

**Issue by jdm** [servo/servo#14572]
The devtools show that it's got the expected DOM tree, but nothing appears.

**Comment by jdm** [comment]
@mrobinson I see a lot of stacking context and scroll root entries in the display list when I use `-Z dump-display-list`, and this makes me suspicious; are there any good strategies for figuring out what's going on here?

**Comment by mrobinson** [comment]
@jdm Haven't yet had a chance to look at this one, but I will try to get to it in the next several days.

**Comment by cbrewster** [comment]
Appears to work now using servo from master. I am unsure if this was a change on duckduckgo's end or a fix in servo.

**Comment by jdm** [comment]
Shrug!
