### ISSUE TITLE
Fix logical keywords in Vertical/Horizontal Positions

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#14579]
#14509 brings `VerticalPosition` and `HorizontalPosition` structs. Logical keywords should behave differently from normal keywords in `Keyword` enum because they are depending on the writing mode. Also it can be done for `Position` but current spec is not allowing logical keywords for it yet. 
I'm wiling to work on that but I need some additional information about logical keywords/properties.
Any suggestions for them?

cc @Manishearth

**Comment by Manishearth** [comment]
The computed value context already contains a writing mode struct. `context().style().writing_mode` I think. So you parse it as a logical property and map to physical at compute time.

**Comment by Manishearth** [comment]
Spec doesn't say what the mapping is. Given that it is an incomplete draft, I'd wait for that to happen.

**Comment by canaltinova** [comment]
Okay then, we'll wait.

**Comment by nox** [comment]
Stylo landed, so I'm pretty sure this can be closed safely.
