### ISSUE TITLE
Initial document load should handle redirects manually

### ISSUE THREAD

**Issue by jdm** [servo/servo#14596]
Right now, page loads are initiated by a ScriptThread, and the final response is received by the same ScriptThread which creates a Window, Document, and starts the HTML parser. This breaks our same-ish origin threading model if a same-origin load secretly redirects to a cross-origin URL behind the scenes. The spec says that the fetch should use the `manual` redirect mode, meaning that the load initiator should receive a 3xx response and make a fetch for the resulting URL, which would allow us to handle this case correctly. Additionally, it would likely make the most sense to have this happen in the Constellation, which would then dispatch the final network response to the appropriate script thread.

cc @asajeffrey

**Comment by jdm** [comment]
Blocks ##5236.

**Comment by jdm** [comment]
Relevant pieces of code to understand the current state of the world - Constellation::new_pipeline, ScriptThread::start_page_load, uses of InProgressLoad in script_thread.rs, ScriptThread::handle_page_headers_available.

**Comment by jdm** [comment]
https://html.spec.whatwg.org/multipage/browsers.html#process-a-navigate-fetch step 7 describes this.

**Comment by jdm** [comment]
@cynicaldevil is going to work on this.

**Comment by cynicaldevil** [comment]
This is what I've thought: in the `RedirectMode::Follow` match arm in `http_loader.rs`, I send a message to consellation with all the info required to know whether the redirect is to a same-origin page or not, then handle the case in constellation and send a dispatch to `script_thread` if needed, and then call `http_redirect_fetch` from there. Am I going in the right direction?

**Comment by jdm** [comment]
Sorry for not being clear - the code that initiates a document fetch should be using RedirectMode::Manual, not RedirectMode::Follow. Additionally, it seems like it would make more sense for that code to live in the constellation, not the script thread.

**Comment by cynicaldevil** [comment]
So I changed the request to use Redirect::Manual by adding another line for `redirect_mode` parameter [here](https://github.com/servo/servo/blob/b5c94bad371114ab9f03e910f66c00a042997fc2/components/script/script_thread.rs#L2046).
Now, if I receive a response which has been filtered with `ResponseType` OpaqueRedirect, I send a message to the constellation to handle the redirects until I find a response which does not redirect, and then send the final response back to `script_thread`?

**Comment by jdm** [comment]
Not precisely. My proposal has a couple parts to it:
* make the fetch request use RedirectMode::Manual
* expose a way to initiate an HTTP redirect fetch (which calls http_loader::http_redirect_fetch instead of fetch_methods::fetch in resource_thread)
* make the code in script_thread.rs deal with redirections by using this newly-exposed API according to step 7 of https://html.spec.whatwg.org/multipage/browsers.html#process-a-navigate-fetch
At this point we should be back to the status quo, where pages that redirect are followed when loading a document. Following this:
* move the code that initiates the document fetch and deals with redirections out of script_thread.rs and into constellation/
* when a non-redirecting response is encountered, send this response to the proper script thread to start the process of parsing the response

Does that make sense? There's no need to consult with the constellation; all of the code to deal with the network response should either reside in script_thread.rs or in the constellation code.

**Comment by cynicaldevil** [comment]
Ah yes, I get it now. Thanks!

**Comment by cynicaldevil** [comment]
Right, I think I have something. I haven't moved the redirection part to constellation yet, I wanted to make sure the tests pass. I ran some tests in `tests/wpt/web-platform-tests/cors/`, which pass. What additional tests should I run?

**Comment by jdm** [comment]
The tests under /cors/ only test cross-origin XMLHttpRequests, not document loads. You could try tests/wpt/web-platform-tests/html/browsers/browsing-the-web/navigating-across-documents instead.
