### ISSUE TITLE
Implement Document.open() and Document.close()

### ISSUE THREAD

**Issue by jdm** [servo/servo#14591]
Blocks #13942.

Spec: https://html.spec.whatwg.org/multipage/webappapis.html#dom-document-open, https://html.spec.whatwg.org/multipage/webappapis.html#dom-document-close

**Comment by dpyro** [comment]
I will give this a go.

**Comment by dpyro** [comment]
Cancelling my go based on @KiChjang’s advice.

**Comment by jdm** [comment]
This also hits us on Google Maps.

**Comment by nox** [comment]
Should we implement `window.open` at the same time? I feel like implementing only the version of `document.open` that takes 2 arguments will break other sites trying to call the 3 arguments version.

**Comment by jdm** [comment]
Pragmatically, I don't think it makes sense to try to solve the issues with `window.open` at the same time.

**Comment by jdm** [comment]
Those sites that use the three argument version are already broken by it not existing, so I don't think the effect will be any worse.

**Comment by Ms2ger** [comment]
We can add the 3-argument overload and unconditionally throw on the Rust side; that's probably better than WebIDL's default of ignoring stray arguments.

**Comment by nox** [comment]
Seems like my job suddenly became easier to do: https://github.com/whatwg/html/issues/1698
