### ISSUE TITLE
script_thread::Documents should be script_thread::Windows

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14619]
We have to attach the GC dispose to Window because it needs to clean up the gc context.

**Comment by jdm** [comment]
This isn't part of #14312 anymore.

**Comment by asajeffrey** [comment]
Might be worth making this change anyway, since `Documents` is only storing the documents that are the main document of a `Window`, so the code is a bit ugly because of that. It might be easier just to store the `Window` objects. This is just code tidiness though, now that #14312 doesn't depend on GC any more.

**Comment by asajeffrey** [comment]
Argh, there's an annoying case for this, which is when the initial `about:blank` is replaced by the final document in a `Window`. This is the only case where a `Window` can end up changing `Document`. Since the two `Document`s have different `pipeline_id`s, we can't use `pipeline_id`s as a unique id for `Window` objects. So I think we should just leave this as-is.
