### ISSUE TITLE
parser_inserted fields should probably be resetted when unbound from the tree.

### ISSUE THREAD

**Issue by emilio** [servo/servo#14616]
There are a few elements (currently script and link, also style with #14540) that track whether they've been injected by the parser.

The link element's field is never set back to false, and the script field should probably be set to false also after unbinding from the tree.

Presumably somebody could write an script that grabs a loaded link element, then re-inserts it with a different `href`, and that probably shouldn't be script blocking.

Is that right?

cc @Ms2ger and @jdm, which probably know more about script-blocking loads than I.

**Comment by Ms2ger** [comment]
Should review what, if anything, the spec says, and what other browsers do.

**Comment by nox** [comment]
It's not reset after unbinding because the spec doesn't say it should be reset. I reviewed most of that when doing parser changes and `document.write`, and I'm 99.44% sure this should not be done. Closing this issue.
