### ISSUE TITLE
MozJS build error, when building Servo on Mac

### ISSUE THREAD

**Issue by gterzian** [servo/servo#14626]
On Mac OS 10.11.6, I can currently only successfully build Servo when manually rewinding MozJS to this commit https://github.com/servo/mozjs/commit/cdf21f7c5596cb6e02eb9afdfc51841deea84a1f  in  [Cargo.lock](https://github.com/servo/servo/blob/master/Cargo.lock#L1620).

If I leave things unchanged, I get  `configure: error: Building ICU requires either yasm or a GNU assembler. If you do not have either of those available for this platform you must use --without-intl-api`

Which might relate to this commit https://github.com/servo/mozjs/commit/78037f9416f96005489f6960bd58f8fb3d2daa1a @emilio 

Also worth noting, is that when I try to build using this commit (I tried because it's the one just before the one mentioned above)https://github.com/servo/mozjs/commit/590a67245e58757f863643b3aa11e1eeebbea5a4, I get 
`ld: symbol(s) not found for architecture x86_64` @nox

**Comment by emilio** [comment]
You need to install yasm, it was added to the dependency requirements.

**Comment by gterzian** [comment]
ok, thanks! @emilio

**Comment by emilio** [comment]
Closing this then, thanks for the report! :)

**Comment by emilio** [comment]
Oh, for the record, the PR that updated mozjs and added the yasm dependency is https://github.com/servo/servo/pull/13836
