### ISSUE TITLE
Bluetooth maps don't need to store mutable JS values

### ISSUE THREAD

**Issue by jdm** [servo/servo#14649]
The `device_instace_map` in `Bluetooth` stores `MutJS<BluetoothDevice>` values, but it looks like they don't need to be mutable. It can use `JS<BluetoothDevice>` instead. Similarly, `BluetoothDevice`, `BluetoothRemoteGATTDescriptor`, `BluetoothRemoteGATTCharacteristic`, `BluetoothRemoteGATTServer`, and `BluetoothRemoteGATTService`.

Code: `components/script/dom/bluetooth.rs`, `components/script/dom/bluetoothdevice.rs`, `components/script/dom/bluetoothremotegattdescriptor.rs`, `components/script/dom/bluetoothremotegattcharacteristic.rs`, `components/script/dom/bluetoothremotegattserver.rs`, `components/script/dom/bluetoothremotegattservice.rs`

No need for tests; if it compiles, it's good enough for a PR.

**Comment by malfunc** [comment]
I'll take it

**Comment by KiChjang** [comment]
You got it!

**Comment by prampey** [comment]
@jdm However, the other bluetooth components use MutableJS types under _different_ variable names. For example, `BluetoothDevice` has `attribute_instance_map` while `BluetoothRemoteGATTService` has `device`. Do we have to remove the mutability of all these variables?

**Comment by jdm** [comment]
Yes, please!

**Comment by prampey** [comment]
@jdm, This is what I get when I try to build after changing values only for `device_instace_map` in `Bluetooth`.
```
error: no method named `get` found for type `&dom::bindings::js::JS<dom::bluetoothdevice::BluetoothDevice>` in the current scope
   --> /Users/prudhvirampey/Downloads/servo/components/script/dom/bluetooth.rs:469:80
    |
469 |                     return promise.resolve_native(promise_cx, &existing_device.get());
    |                                                                                ^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope; the following traits define an item `get`, perhaps you need to implement one of them:
    = help: candidate #1: `std::collections::hash::Recover`
    = help: candidate #2: `core::slice::SliceExt`
    = help: candidate #3: `core::slice::SliceIndex`
    = help: candidate #4: `collections::btree::Recover`
    = help: candidate #5: `range::RangeIndex`
    = help: candidate #6: `string_cache::atom::StaticAtomSet`

error: no associated item named `new` found for type `dom::bindings::js::JS<_>` in the current scope
   --> /Users/prudhvirampey/Downloads/servo/components/script/dom/bluetooth.rs:475:55
    |
475 |                 device_instance_map.insert(device.id, JS::new(&bt_device));
    |                                                       ^^^^^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope; the following traits define an item `new`, perhaps you need to implement one of them:
    = help: candidate #1: `dom::bindings::callback::CallbackContainer`
    = help: candidate #2: `std::sys_common::thread_info::NewThread`
    = help: candidate #3: `core::iter::ZipImpl`
    = help: candidate #4: `aho_corasick::Transitions`
    = help: candidate #5: `solicit::http::session::Stream`
    = help: candidate #6: `range::RangeIndex`
    = help: candidate #7: `html5ever::tendril::Atomicity`

error: no method named `get` found for type `&dom::bindings::js::JS<dom::bluetoothdevice::BluetoothDevice>` in the current scope
   --> /Users/prudhvirampey/Downloads/servo/components/script/dom/bluetoothdevice.rs:196:27
    |
196 |                 if device.get().Gatt().Connected() {
    |                           ^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope; the following traits define an item `get`, perhaps you need to implement one of them:
    = help: candidate #1: `std::collections::hash::Recover`
    = help: candidate #2: `core::slice::SliceExt`
    = help: candidate #3: `core::slice::SliceIndex`
    = help: candidate #4: `collections::btree::Recover`
    = help: candidate #5: `range::RangeIndex`
    = help: candidate #6: `string_cache::atom::StaticAtomSet`
```
It seems that `JS<T>` and `MutJS<T>` have different methods implemented in `components/script/dom/bindings/js.rs`.

**Comment by jdm** [comment]
@prampey Instead of `JS::new`, use `JS::from_rooted`, and instead of `.get()` use `.` (the first error can just be `&existing_device`, or `&*existing_device` if necessary).

**Comment by prampey** [comment]
@jdm `JS::from_rooted` doesn't exist. So I decided to use `JS::from_ref` to create a JS datatype from the given reference. Is that cool? (Compiled quietly)
The second one seemed to have compiled without problems.
The third one gives me the following error:
```
error[E0277]: the trait bound `dom::bindings::js::JS<dom::bluetoothdevice::BluetoothDevice>: js::conversions::ToJSValConvertible` is not satisfied
   --> /Users/prudhvirampey/Downloads/servo/components/script/dom/bluetooth.rs:469:36
    |
469 |                     return promise.resolve_native(promise_cx, &*existing_device);
    |                                    ^^^^^^^^^^^^^^ the trait `js::conversions::ToJSValConvertible` is not implemented for `dom::bindings::js::JS<dom::bluetoothdevice::BluetoothDevice>`
```
For both the solutions you proposed.

**Comment by jdm** [comment]
My mistake, from_ref is correct. For the third, you'll need `&**existing_device`.

**Comment by prampey** [comment]
@jdm Okay, it works. 
Please correct me if I'm wrong. 
So initially, `&Existing_device.get()` returned a type `Root<BluetoothDevice>` which was type coerced to `BluetoothDevice`? 
And now `&**existing_device` dereferences ` existing_device` to type `BluetoothDevice` and dereferences that further to get a reference to what?

**Comment by jdm** [comment]
`existing_device.get()` returned a `Root<BluetoothDevice>`, and the `&` allowed it to be automatically dereferenced into `&BluetoothDevice`. Since `existing_device` is now `&JS<BluetoothDevice>`, the two `*`s turn dereference it into `BluetoothDevice`, and the `&` makes it `&BluetoothDevice` again.

**Comment by prampey** [comment]
@jdm Thanks for the clarification! I'm done with the cleanup. I'll be sending in a PR.
