### ISSUE TITLE
Github wiki search doesn't work

### ISSUE THREAD

**Issue by jdm** [servo/servo#14659]
When visiting https://github.com/servo/servo/wiki in Servo, you can type in the "Find a page" input box, but the links below it never update.

**Comment by jdm** [comment]
@Wafflespeanut This might be a fun thing for you to investigate. I bet we're not dispatching the right events.

**Comment by nox** [comment]
This still doesn't work.

**Comment by krk** [comment]
This can be reproduced in a14b952fa3eedec86e6308213c525538bcb20827

**Comment by krk** [comment]
This can be reproduced in a14b952fa3eedec86e6308213c525538bcb20827

**Comment by jdm** [comment]
Fixed by #26901!
