### ISSUE TITLE
What should the intermediate state of a reloaded document be?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14666]
If a document is discarded, then reloaded by traversing to it, what should its state be after the traversal, but before the load is complete? This is a similar case to the initial `about:blank` state. cc @jdm

**Comment by jdm** [comment]
What do you mean by state, exactly? I believe traditionally browsers will treat the existing document as active until the response headers for the new document are received, at which point the new document is made active.

**Comment by asajeffrey** [comment]
Things like which document is returned by iframe.contentDocument.

**Comment by asajeffrey** [comment]
The spec https://html.spec.whatwg.org/multipage/#traverse-the-history-by-a-delta says that we should queue a task to traverse the document, https://html.spec.whatwg.org/multipage/#traverse-the-history says:

> If entry no longer holds a Document object, then navigate the browsing context to entry's URL to perform an entry update of entry, and abort these steps.

https://html.spec.whatwg.org/multipage/browsers.html#entry-update traverses the history after the dcoument is loaded.

**Comment by asajeffrey** [comment]
Closed by #14312
