### ISSUE TITLE
Rewrite Crypto::GetRandomValues to use typed array API

### ISSUE THREAD

**Issue by jdm** [servo/servo#14673]
Instead of using `array_buffer_view_data`, this method should use [ArrayBufferView::from](https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs#L66) and return an error value if a typed array cannot be extracted from the JS object. We'll need to declare the value using the `typedarray!` macro (see [the tests](https://github.com/servo/rust-mozjs/blob/master/tests/typedarray.rs) for examples).

Code: `components/script/dom/crypto.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/WebCryptoAPI/`

Note: this relies on https://github.com/servo/rust-mozjs/pull/323 before the ArrayBufferView type exists.

**Comment by deror1869107** [comment]
Should 
fn data(&mut self) -> (*mut T::Element, u32)
in [https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs#L85](typedarray.rs)
be a public function?

**Comment by deror1869107** [comment]
I would like to work on this issue!

**Comment by prampey** [comment]
Hi. I'd like to work on this.

**Comment by jdm** [comment]
Looks like @deror1869107 claimed it first. Thanks for the interest!
