### ISSUE TITLE
Ensure repeating timers are cancelled when their document is discarded

### ISSUE THREAD

**Issue by jdm** [servo/servo#14678]
Otherwise they'll repeat forever once we make #14677 not panic any more.

**Comment by bzbarsky** [comment]
And prevent new setTimeout/Interval calls from creating new timers?

**Comment by jdm** [comment]
@bzbarsky Are you thinking of inactive documents rather than discarded ones?

**Comment by asajeffrey** [comment]
jdm: is the problem that some documents can be discarded without being frozen first?

**Comment by jdm** [comment]
Oh, I think my fears may be unjustified - it looks like repetition is handled by the script thread, rather than the timer scheduling thread.

**Comment by bzbarsky** [comment]
@jdm I'm thinking of both, I think.  The spec around this stuff is somewhere between useless and vague, but in practice you want to prevent setTimeout/setInterval both when a document is navigated away from (becomes inactive) and when its browsing context is destroyed (per spec doesn't seem to become inactive).

**Comment by asajeffrey** [comment]
@jdm: are your fears unjustified enough that we can close this issue?

**Comment by jdm** [comment]
Yes.

**Comment by asajeffrey** [comment]
@jdm: thanks!
