### ISSUE TITLE
Rewrite websocket array buffer handling to use typed array APIs

### ISSUE THREAD

**Issue by jdm** [servo/servo#14675]
[The current implementation](https://dxr.mozilla.org/servo/source/components/script/dom/websocket.rs#610-618) uses the JSAPI to create an array buffer, get its buffer and populate it with the received websocket message. We should be using the [ArrayBufferU8::create](https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs#L120) API instead (see [FileReader::perform_readasarraybuffer](https://dxr.mozilla.org/servo/rev/1b069de6b26db99f8b7964e8542f2b04e78094ce/components/script/dom/filereader.rs#272) for an example).

Code: `components/script/dom/websocket.rs`
Tests: `./mach test-wpt tests/wpt/websockets/`

**Comment by dpyro** [comment]
I will give it a try!

**Comment by KiChjang** [comment]
Alright!

**Comment by dpyro** [comment]
[I’ve rewritten the handling to use `Uint8Array::create`.](https://github.com/dpyro/servo/blob/9bd1fabd8a9b56ef8d70032dbcff8e29454fa7f9/components/script/dom/websocket.rs#L610) It compiles and passes `./mach test-wpt tests/wpt/web-platform-tests/websockets/` but I am unsure that it actually verifies the modified behavior is correct/equivalent.

**Comment by jdm** [comment]
Great work! Two notes, though:
* Does ArrayBuffer::create work instead? That would be equivalent with the previous code.
* You can remove the code which extracts the buffer pointer and fills it with data; passing `Some(data)` to the creation function has the same effect.

**Comment by Ms2ger** [comment]
Also, feel free to go ahead and create a PR; that might make discussion easier.

**Comment by jdm** [comment]
Huh, I'm surprised that https://github.com/dpyro/servo/commit/9bd1fabd8a9b56ef8d70032dbcff8e29454fa7f9#diff-c13bae09b178a30151ecebdc13c30a26R619 passes tests, however. Additionally, https://github.com/dpyro/servo/commit/9bd1fabd8a9b56ef8d70032dbcff8e29454fa7f9#diff-c13bae09b178a30151ecebdc13c30a26R613 shouldn't compile, since the last argument is supposed to be a mutable handle.
