### ISSUE TITLE
Rewrite TextDecoder::Decode to use typed array API

### ISSUE THREAD

**Issue by jdm** [servo/servo#14674]
Instead of using `array_buffer_view_data`, this method should use [ArrayBufferView::from](https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs#L66) and return an error value if a typed array cannot be extracted from the JS object. We'll need to declare the value using the `typedarray!` macro (see [the tests](https://github.com/servo/rust-mozjs/blob/master/tests/typedarray.rs) for examples).

Code: `components/script/dom/textdecoder.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/encoding/`

Note: this relies on https://github.com/servo/rust-mozjs/pull/323 before the ArrayBufferView type exists.

**Comment by zaynetro** [comment]
I'd like to work on this issue
