### ISSUE TITLE
Rewrite WebGLRenderingContext to use typed array APIs

### ISSUE THREAD

**Issue by jdm** [servo/servo#14676]
We need to replace uses of `array_buffer_view_data_checked`, `array_buffer_view_data`, `array_buffer_view_to_vec_checked`, `array_buffer_view_to_vec`, and `array_buffer_to_vec`. This may mean adding an additional `ArrayBufferViewU16` type to the list in rust-mozjs, but the rest should be straightforward replacements with things like `ArrayBuffer::from` and `ArrayBufferView::from` (after https://github.com/servo/rust-mozjs/pull/323 merges).

Code: `components/script/dom/webglrenderingcontext.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/webgl/`

**Comment by deror1869107** [comment]
I would like to work on this issue!

**Comment by deror1869107** [comment]
There is no JSContext in the [fn validate_tex_image_2d_data](https://github.com/servo/servo/blob/master/components/script/dom/webglrenderingcontext.rs#L425)
which is required by ArrayBufferView::From.
How can I fix this problem? thx

**Comment by KiChjang** [comment]
Does `self.global().get_cx()` work?

**Comment by jdm** [comment]
You can add a `*mut JSContext` argument to the method, since all of the callers should have access to one already.

**Comment by deror1869107** [comment]
Sorry for that I was busy before.
I can work for it now!
It seems that there should be type ArrayBufferViewU16 in the rust/moz.js
Could you please create an issue on rust/moz.js for this? Thanks

**Comment by deror1869107** [comment]
Change 
[code](https://github.com/servo/servo/blob/master/components/script/dom/webglrenderingcontext.rs#L456)
'''
} else if array_buffer_view_data_checked::<u8>(data).is_some(){
    1
}
'''
To
'''
typedarray!(in(cx) let typedarray_u8: ArrayBufferView = data);
// some line
} else if typedarray_u8.is_ok() {
    1
}
'''
Is it right?

**Comment by jdm** [comment]
That looks right.

**Comment by deror1869107** [comment]
@jdm 
So I need ArrayBufferViewU16 in rust/mozjs to replace the function array_buffer_view_data_checked::<u16>. 

But I don't know how to add this to rust/mozjs.

**Comment by jdm** [comment]
You can add it to the list of typed arrays at https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs#L272, and then use a [Cargo override](http://doc.crates.io/specifying-dependencies.html#overriding-with-local-dependencies) to use your locally-modified version inside Servo.

**Comment by deror1869107** [comment]
It seems that I need to write C++ functions which are binding with two rust functions UnwrapUint16ArrayBufferView and GetUint16ArrayBufferViewLengthAndData.

Where can I implement these function?

**Comment by Ms2ger** [comment]
It look like we shouldn't be using `ArrayBufferView` for this at all, just `Uint8Array` and `Uint16Array`.

**Comment by deror1869107** [comment]
The trait bound in ArrayBufferViewContents is u8, u16, i8, i16, f16, f32 primitive type.

It means that there would be some function call like
```
typed_array_or_sequence_to_vec::<i32>(cx, data, ConversionBehavior::Default)
```

But I have to change them to Uint8, Uint16, Int8, Int16, Float16, Float32 which are TypedArrayElementType.

Therefore I can rewrite fn typed_array_or_sequence_to_vec with  TypedArray.

**Comment by deror1869107** [comment]
TypedArray only uses TypedArrayElement type to be created.

But the generic type parameters of typed_array_or_sequence_to_vec::<T> are primitive type now.

How can I use primitive type to create an TypedArray? thx
