### ISSUE TITLE
Figure out how to do Critic reviews without merging fixup commits

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1468]
When we enabled Critic we switched to this policy:

> In order to help critic track your changes, please do *not* make in-place history rewrites

But this introduces an additional round-trip between author and reviewer:

> **Reviewer**: This code looks good, please squash.
> **Author**: [force-pushes squashed commits]
> **Reviewer**: r+

I think the additional delay and overhead is unfortunate.  One solution would be to teach `bors` to squash commits based on `rebase --autosquash`-style tags in the commit subjects.

**Comment by larsbergstrom** [comment]
@jgraham Do you think we should still do this? We might have some folks interested in doing some bors-hacking.

**Comment by Ms2ger** [comment]
IMO, bors shouldn't merge, but rather `rebase --autosquash` on master and add an empty commit on top with PR number and reviewer. (Bonus points if we can also make it list the critic review.) That would make our history a lot easier to navigate.

**Comment by jgraham** [comment]
Not sure about the empty commit thing (it could just edit the existing commit messages, for example), but I think what Ms2ger suggests seems quite sensible.

**Comment by Ms2ger** [comment]
Hmm, editing all commit messages seems even better.

**Comment by frewsxcv** [comment]
Considering we don't use Critic anymore, this conversation is quite a bit dated.
