### ISSUE TITLE
Naming of the constellation's frame tree

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14690]
The naming of frames isn't as spec-compliant as it could be: `prev` is the past, `next` is the future, `FrameState` is a session history entry, `Frame` is the session history of a browsing context.

**Comment by cbrewster** [comment]
Along with this, we call `FrameState`s `entry`s and sometimes `state`s, we should figure out a consistent naming for this.

**Comment by cbrewster** [comment]
We have done a bit of renaming already, are there any other things left to rename?

**Comment by asajeffrey** [comment]
In my braver moments, I have thought that `PipelineId` should really be `DocumentId` or `WindowId`. But I think we're probably not going to do that.

**Comment by nox** [comment]
Was this done? If you specified all the renames you want, this could be E-Easy.

**Comment by asajeffrey** [comment]
We did most of the worst offenders. There's still `PipelineId` but I don't think we should touch this right now.
