### ISSUE TITLE
Split off Frame from constellation.rs

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14691]
In the same way as EventLoop and Pipeline get their own modules in the constellation, so should Frame.

**Comment by deror1869107** [comment]
Is the only thing should be done to move the code "struct Frame..." from constellation.rs to frame.rs?

**Comment by deror1869107** [comment]
I'd like to work on this issue!

**Comment by Ms2ger** [comment]
Yep, the struct and the impl blocks; go ahead!
