### ISSUE TITLE
Split logging out from constellation.rs

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14694]
We should spit the logging types out of constellation.rs.

**Comment by nox** [comment]
What are the "logging types"? Seems like this could be an E-Easy issue, care to give more details?

**Comment by asajeffrey** [comment]
I doubt this is E-easy I'm afraid. Logging in servo is a bit of a mess :/

The "logging types" are `FromScriptLogger` (https://github.com/servo/servo/blob/64aadee62c1e0f100ad79ab50a56cd1f84285eeb/components/constellation/constellation.rs#L403) and `FromCompositorLogger` (https://github.com/servo/servo/blob/64aadee62c1e0f100ad79ab50a56cd1f84285eeb/components/constellation/constellation.rs#L440).

The logging story (and the crash reporting story which is tightly coupled) should really be part of the embedding API. cc @paulrouget

**Comment by paulrouget** [comment]
Aren't this code only about crash reporting?

**Comment by asajeffrey** [comment]
Crash reporting and logging in general. Anything WARNING or above gets included in crash reports.
