### ISSUE TITLE
Add HTTP connector to HttpState, instead of creating one in http_network_fetch

### ISSUE THREAD

**Issue by jdm** [servo/servo#14697]
Right now we are not pooling HTTP connections, because we create a new pool for every connection. If we add the pool to the `HttpState` structure, we can use it from `http_network_fetch` instead of creating it.

Code: `components/net/resource_thread.rs`, `components/net/http_loader.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest` (this will ensure that network connections keep working after the change)

**Comment by mattnenterprise** [comment]
I would like to work on this.

**Comment by KiChjang** [comment]
Go for it! Ask any questions here or on `irc.mozilla.org` at #servo if you have any questions!
