### ISSUE TITLE
Document deadlock-freedom of the constellation, since IPC buffer send is blocking

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14704]
If a script thread busy-loops, but the constellation keeps sending it messages, eventually it will exhaust the IPC buffer. This will then block the constellation, oh dear.

IPC conversation with @antrik and @pcwalton http://logs.glob.uno/?c=mozilla%23servo&s=23+Dec+2016&e=23+Dec+2016#c583154

**Comment by nox** [comment]
So what do you plan to do here? This issue doesn't sound actionable except replying "yes" or "no".

**Comment by antrik** [comment]
I wonder whether this is a real issue? Since Linux only buffers one message, I would expect this to be pretty visible there if it is...

Anyway, to sum up the situation: yes, `ipc-channel` blocks the sender when there are too many pending messages -- which is as little as one on Linux. (And for large messages, also with the upcoming Windows back-end.)

`ipc-channel` is not meant as a buffering mechanism. If such a mechanism is required, it needs to be implemented explicitly outside of `ipc-channel`.

**Comment by asajeffrey** [comment]
@antrik hmm, this is a bit of a problem: the constellation assumes sending on a channel is non-blocking. Could we add a `try_send` to ipc-channel?

**Comment by antrik** [comment]
I forgot to mention that for long messages, with some back-ends even a single send can block in the middle , while it waits for the receiver to get the previous packages. So no, we can't really do `try_send()`... Adding async sending would be more complex than that.

See https://github.com/servo/ipc-channel/pull/165 for some pretty relevant discussion.

**Comment by asajeffrey** [comment]
Ouch. So ipc channels have no way to provide a non-blocking send?

The only workaround I can see involves providing the constellation with a thread pool that it can use to send messages to the script threads.

**Comment by asajeffrey** [comment]
Oh and just to make things more fun, we're using a lot of one-shot ipc-channels for getting results back from the constellation, and sending can block on those too, sigh. This is slightly less worrying because we're not executing arbitrary user JS code before the script thread calls recv, so the send is less likely to block and potentially cause deadlock. It's still not great though.

**Comment by antrik** [comment]
@asajeffrey wouldn't it be easier to have a dedicated thread per receiver (or per receiving process), to put the received messages in a queue, for the script thread to consume as it sees fit?

In fact, the queue should be trivial to implement, by simply forwarding the messages to the thread over an `mpsc` channel... Which happens to be precisely what the existing `Router` mechanism in `ipc-channel` does! So just add a router for the script thread (if it doesn't use one already...), and bam! -- problem solved :-)

(There is one downside to having the queue on the receiver side: a malicious sender could DOS the receiver by flooding it with messages until it runs out of memory...)

**Comment by antrik** [comment]
@asajeffrey for the reply channels, it's only a problem if the messages can typically get larger than the fragment size -- which is usually `224 KiB` on Linux `x86_64`, for example.

(In fact the current Unix implementation only blocks once the message exceeds *twice* the fragment size...)

**Comment by asajeffrey** [comment]
Ah, good point there is already a router between the IPC channel and the script thread. Using an extra thread seems quite a lot of overhead, but it does solve the problem. It does mean that the deadlock-freedom of the constellation depends on routers guaranteeing that `send` is non-blocking, I guess the action here is to document that somewhere!

**Comment by asajeffrey** [comment]
OK, I added some documentation, I think I got the can-block-on relationship right :/ https://github.com/asajeffrey/servo/commit/dd1ec8f2f1b7c42cb929448dfe3dc286beb7cf3a

The one that always surprises me is that the constellation can block on layout, which is only true when taking the screenshots for reftests.
