### ISSUE TITLE
Cookie::appropriate_for_url should check for wss schemes in addition to https

### ISSUE THREAD

**Issue by jdm** [servo/servo#14702]
Really, we should have an `is_scheme_secure(&ServoUrl)` abstraction, because this gets used in #14491 as well.

Code: `components/net/cookie.rs`

No way to write an automated test for this, unfortunately, since we can't run SSL tests yet.

**Comment by iamrohit7** [comment]
I would like to work on this.

**Comment by ConnorGBrewster** [comment]
@iamrohit7 it's all yours!
