### ISSUE TITLE
Consider precomputing Element#tagName.

### ISSUE THREAD

**Issue by zmike** [servo/servo#1471]
According to jgraham:

It looks like someone didn't finish the namespace implementation for elements
At the moment they store something called tag_name
But they should store local_name and tag_name should be computed

**Comment by mbrubeck** [comment]
If this is still something we want to fix, it would involve taking the logic from [Element::TagName][1] and performing it when the element is created (for example in `Element::new_inherited_with_state`) and storing the result in a new field of the Element struct.  Then `TagName` could just return the value of that field.

[1]: https://github.com/servo/servo/blob/bcea0ada27de694cd0c465d04fd35eba70503d62/components/script/dom/element.rs#L1291-L1303

**Comment by Ms2ger** [comment]
Note that the computed value needs to be updated if the owner document changes.

**Comment by bzbarsky** [comment]
Right.

I really do think the way Gecko does this (with a shared nodeinfo struct) is pretty good,  I don't know to what extent the sharing would be a problem for Servo...
