### ISSUE TITLE
Our resize story for iframes is not great.

### ISSUE THREAD

**Issue by emilio** [servo/servo#14719]
Right now, we handle resizes asynchronously, even when they're set explicitly by the user. This has observable effects for same-origin iframes, and not-interoperable behavior.

See, for example, #14556.

Right now, when the width attribute changes, we do the following:

 * We run layout, build the display list, including the iframe display item, which contains the pipeline id.
 * WebRender flattens the display list and, if the size changed, calls the render notifier in the compositor...
 * Which sends to the constellation the resize.
 * Which in turns sets the window's `window_size` field, and trigger a reflow.

That's (I think) fine for cross-origin iframes, since there are no visible effects from the web page's point of view (apart from a moment with the straneous styling). I'm not sure how Gecko handles cross-origin iframe resizing, maybe the resize needs to be synchronous as well? @bzbarsky may know better than I.

Concretely: what happens when an iframe is resized as a consequence of a style/layout change (e.g., because it uses a percentage width?). Is it different for same and cross-origin iframes (I guess so)? I might investigate it tomorrow, but today's christmas :)

But for same-origin iframes, it seems we can't do all this async story all that straight away.

cc @pcwalton, and also @asajeffrey and @jdm, which know about the effort that was needed to make same-origin frames share script threads, given it's probably a similar effort for layout threads.

**Comment by bzbarsky** [comment]
The way Gecko handles this is as follows:

1.  A layout or style flush on a document will perform a layout flush on its parent.  This is needed to make media queries work right in cases where the parent has a relayout scheduled that hasn't happened yet.  We do this across origins too, but I think this could be restricted to same-origin within the web security model, where all access is symmetric.  With asymmetric access (chrome to content in Firefox), you have to flush up the chain if you don't want chrome code to observe content not resizing properly.  See nsDocument::FlushPendingNotifications in Gecko.
2. When an `<iframe>` element reflows, it just schedules a relayout on the child document to happen async.  This is a somewhat recent change; see https://bugzilla.mozilla.org/show_bug.cgi?id=881832

Most of the discussion above seems about item 2, but item 1 seems to be what servo is missing.

**Comment by emilio** [comment]
Well, the discussion above applies to both (I think, just came from a Christmas dinner so my thinking may not be the best), because the way resizes end up arriving to script.

Mainly, I think you can change the size of an iframe, and force a reflow in that iframe via script (e.g. offsetTop) before the iframe knows it's been resized.

**Comment by emilio** [comment]
Indeed, if you force a flush in both documents in the test in #14556, the test still fails, because of the async window size update.

**Comment by jdm** [comment]
Addressing this would likely make fixing #15688 easier.

**Comment by asajeffrey** [comment]
One thing which would help matters is if we associated the window size with the frame rather than with the pipeline.

**Comment by cbrewster** [comment]
@asajeffrey #16506 has a commit with the first step of associating window size with frame rather than pipeline
