### ISSUE TITLE
Iframes always load with about:blank in history

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#14720]
If the iframe has a `src` attribute, once the website loads in the iframe, the `about:blank` should be replaced in the session history.

https://html.spec.whatwg.org/multipage/embedded-content.html#process-the-iframe-attributes
> Similarly, if the nested browsing context's session history contained only one Document when the process the iframe attributes algorithm was invoked, and that was the about:blank Document created when the nested browsing context was created, then any navigation required of the user agent in that algorithm must be completed with replacement enabled. 

Sample:

iframe.html:
```
<iframe src="https://www.servo.org"></iframe>
```
```
/mach run -d iframe.html
```

Traverse the history backwards using the keyboard shortcut and the iframe will traverse back to `about:blank`.

**Comment by cbrewster** [comment]
cc @asajeffrey 
One solution is to wait until `Url`s are stored in `FrameState` and then when an iframe is loading a new Url, check the Frame `prev` see if it has a single entry with the url `about:blank`, if so, enable replacement.

**Comment by Ms2ger** [comment]
Not sure that's quite enough; we might need to store the "is initial about:blank document" flag.

**Comment by cbrewster** [comment]
@Ms2ger you're right, otherwise subsequent `about:blank` loads would be replaced as well. I think we could store this flag on the `Frame` itself.

**Comment by asajeffrey** [comment]
We could check to see if the old URL is about: blank and prev is empty? Not sure what is meant to happen if the iframe "really" contains about: blank.

**Comment by cbrewster** [comment]
If it "really" contains about:blank it just does a normal navigation without replacement enabled

**Comment by asajeffrey** [comment]
So an iframe which starts with src=about:blank is treated differently from one which starts with no src?

**Comment by cbrewster** [comment]
@asajeffrey I believe so

**Comment by Ms2ger** [comment]
https://html.spec.whatwg.org/multipage/#process-the-iframe-attributes seems quite clear on that point; I don't understand where the confusion arises.
