### ISSUE TITLE
Update http_network_or_cache_fetch to current Fetch standard

### ISSUE THREAD

**Issue by mattnenterprise** [servo/servo#14742]
http_network_or_cache_fetch looks to be out of date with what is currently in the [standard](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch). It should be updated to reflect what the current standard contains.

**Comment by mattnenterprise** [comment]
@jdm i can go ahead and do this.

**Comment by jdm** [comment]
Great! Anything in particular you're focusing on?

**Comment by mattnenterprise** [comment]
Currently I only see 20 steps in the code, but the spec contains 25. I would like to add the additional steps, or at least add a TODO where they should be added in the code.

**Comment by KiChjang** [comment]
Some notes (all step numbers are based on current version of the spec):
* Step 2 on the spec is new;
* Step 7 is new;
* Step 9 needs update;
* Step 13 needs update;
* Step 22 is new;
* Step 23 is new.

**Comment by Ms2ger** [comment]
Relevant: https://github.com/Ms2ger/servo/tree/http_network_or_cache_fetch
