### ISSUE TITLE
Gradients render in the wrong direction

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#14745]
Notice the `Sign Up` and `Sign up for GitHub` buttoms.

Servo:
<img width="1058" alt="screen shot 2016-12-27 at 4 04 41 pm" src="https://cloud.githubusercontent.com/assets/9086315/21510260/84121e0c-cc4e-11e6-9ae7-71ad5cee6684.png">
Firefox:
<img width="1295" alt="screen shot 2016-12-27 at 4 05 53 pm" src="https://cloud.githubusercontent.com/assets/9086315/21510259/841087a4-cc4e-11e6-9bbb-2e8348cf1f4d.png">

**Comment by DominoTree** [comment]
I was doing some work in this area a couple of weeks ago - I'll see if I can hunt this down.
