### ISSUE TITLE
Inline box's border is rendered incorrectly

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#14750]
If we set a box as `display:inline`, its border will not be shown correctly.

![selection_084](https://cloud.githubusercontent.com/assets/3250983/21512544/a4addb60-cce9-11e6-9c5a-974b5224d8bf.png)
(left: servo, right: firefox aurora)

There is a 5 px padding/margin around the "ABC"s, so clearly the `border: 5px` is processed, but the `dotted black` attribute is not processed correctly.

This is the testcase:

```
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css" media="screen">
      #inline{
        display: inline;
        border: 5px dotted black;
      }
      .red {
        background-color: red;
      }
      .green {
        background-color: green;
      }
      .blue {
        background-color: blue;
      }
    </style>
  </head>
  <body>
    <span>Foo Bar</span>
    <div id="inline">
      <span class="red">ABC</span>
      <span class="green">ABC</span>
      <span class="blue">ABC</span>
    </div>
    <span>Foo Bar</span>
  </body>
</html>
```

**Comment by shinglyu** [comment]
`display: block` and `display: inline-block` works as expected.

**Comment by DominoTree** [comment]
I'll take a stab at this one

**Comment by KiChjang** [comment]
@DominoTree Do you mind working on one issue at a time?

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear!

**Comment by DominoTree** [comment]
Finally got some time to play with this a bit - I think this is an issue with spacing being miscalculated - the inner divs seem to be rendered on top of the border

<img width="267" alt="screen shot 2017-01-14 at 5 31 45 pm" src="https://cloud.githubusercontent.com/assets/5438118/21958643/d962fb34-da80-11e6-9a38-6bce4286ab75.png">
<img width="244" alt="screen shot 2017-01-14 at 5 34 52 pm" src="https://cloud.githubusercontent.com/assets/5438118/21958642/d961c91c-da80-11e6-8739-4bcd5efa6006.png">

**Comment by nox** [comment]
It got slightly better:

<img width="401" alt="capture d ecran 2017-10-07 a 12 51 26" src="https://user-images.githubusercontent.com/123095/31307159-44158038-ab5e-11e7-9b34-6b1a6390532c.png">

**Comment by nox** [comment]
@DominoTree Are you still working on this?

**Comment by dralley** [comment]
Still broken

**Comment by Loirooriol** [comment]
Fixed in layout 2020:

 - 2013:
   ![](https://github.com/user-attachments/assets/7b241ec9-58dc-416a-a3d4-434aaa9464f1)
 - 2020:
   ![](https://github.com/user-attachments/assets/6f5a6fda-d851-49a3-98d3-35ba514e5022)
 - Firefox:
   ![](https://github.com/user-attachments/assets/0ae7b753-6a4c-40cc-8159-218dd7fa9abc)
