### ISSUE TITLE
`overflow` with CSS-wide keywords is incorrectly serialized from CSSOM

### ISSUE THREAD

**Issue by upsuper** [servo/servo#14752]
The following test page:
```html
<!DOCTYPE html>
<style>
div { overflow: inherit; }
</style>
<script>
let decl = document.styleSheets[0].cssRules[0].style;
document.write(decl.cssText);
</script>
```

Stylo (and probably Servo) just shows "inherit" while other browsers (including Gecko) shows "overflow: inherit;".

I looked into code in `PropertyDeclarationBlock::to_css`, but don't find any issue there. And it only happens for CSS-wide keywords (`inherit`, `initial`, `unset`), but not other keywords (`hidden`, `visible`, etc.). And it only happens to `overflow`. It doesn't seem to me any other shorthand has the same issue.

**Comment by upsuper** [comment]
It seems the issue is in `declaration_block::append_serialization`.

**Comment by canaltinova** [comment]
I can take a look at this if you're not working currently.

**Comment by upsuper** [comment]
I'm not working on this currently.

**Comment by canaltinova** [comment]
Okay. I'll work on it :)
