### ISSUE TITLE
contentWindow is null right after iframe src is set

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#14767]
Test case (after: #14764 see https://github.com/servo/servo/pull/14764#issuecomment-269555670)
```
<body>
<script>
iframe = document.createElement("iframe");
iframe.src = "about:blank";
document.body.appendChild(iframe);
console.log("contentWindow: " + iframe.contentWindow);
</script>
</body>
```
Servo:
```
contentWindow: null
```
Safari, Firefox, Chrome:
```
contentWindow: [object Window]
```
I am not sure the best way to go about fixing this... Do we need to synchronously create the new document on the script thread when a new iframe load is triggered in all cases? Unless `about:blank` is a special case here that is the only case that should be loaded synchronously.
cc @asajeffrey @jdm @Ms2ger

**Comment by jdm** [comment]
Doesn't this work on master right now? Appending the iframe to the document for the first time creates a nested browsing context which makes iframe.contentWindow available synchronously. This is what the standard says should happen.

**Comment by cbrewster** [comment]
@jdm yes but the synchronous load happens twice (once for the new nested BC and once for the src attribute). Should both of these loads be synchronous? If not, then this becomes an issue

**Comment by jdm** [comment]
I do not believe the second load of about:blank (due to the src attribute) should be synchronous.

**Comment by cbrewster** [comment]
If that's the case, then the test above fails (as my pr makes subsequent about:blanks load be asynchronous). The script_thread document lookup returns `None`

**Comment by jdm** [comment]
I argue that #14764 should not be merged without figuring out how to address that :)

**Comment by jdm** [comment]
In case it's unclear, the second load being asynchronous should not prevent contentWindow from returning the window that was created for the nested browsing context that was created synchronously when the iframe was appended to the document.

**Comment by cbrewster** [comment]
@jdm should `contentWindow` return the `window` from the first `about:blank` window or the second `about:blank`?

**Comment by jdm** [comment]
I'm surprised that we're creating a new script thread for that; I thought we had code that special-cased about:blank so it was treated as same-origin.

**Comment by jdm** [comment]
In general, until we have the process the response headers for a request (and therefore create a new document, etc.) we should be returning the window/document that already exists.

**Comment by cbrewster** [comment]
It seems there might be a couple issues here then... 
1. We shouldn't update the `PipelineId` on the iframe until it's corresponding `Document` has been created and added the the script thread.
2. `about:blank` I believe will load same-origin on master, but I think thats it is in the same logic that does the synchronous load. Do you know where the logic would be that determines if a new script thread is crated depending on same/cross origin?

**Comment by cbrewster** [comment]
Ok I think I am getting closer to the answer here! 😄 
I think I may have a misunderstanding of where the "synchronous" part of the load actually happens. I assume it means the scrip thread is halted until the load is completed? I am not sure where in the code this is actually happening.

The special case code for making sure `about:blank` is treated as same origin is https://dxr.mozilla.org/servo/source/components/constellation/constellation.rs#1418-1427. We create a `Pipeline` directly rather than going through `new_pipeline`. This logic needs to remain for all `about:blank` loads; however, the synchronous part only needs to happen for the initial `about:blank` load.

**Comment by cbrewster** [comment]
This seems to be a few different issues, once I get it all panned out I'll open some more specific issues. For now I'll close this
