### ISSUE TITLE
Various structs in the style system are underdocumented

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#14765]
Context, StyleContext, SharedStyleContext, ThreadLocalStyleContext.  What purposes do they serve?  When should one expect to use/need them?

There is no real documentation on any of these, and even grep is of limited utility for something like "Context".

@emilio @bholley

**Comment by bzbarsky** [comment]
Oh, and I guess the two things I'd like are:

1)  Document these things.
2)  Stop checking in undocumented code.  ;)

**Comment by shinglyu** [comment]
We could make `./mach test-tidy` show a warning if any struct or function is undocumented.

**Comment by jdm** [comment]
That's usually the role of `#![warn(missing_documentation)]` instead.

**Comment by emilio** [comment]
I plan to add the `deny(missing_docs)` lint. Turns out documenting the existing stuff is a hardish job now :)

**Comment by emilio** [comment]
FWIW (not even halfway through):

```
61 files changed, 1565 insertions(+), 549 deletions(-)
```

**Comment by emilio** [comment]
I think we can consider this fixed with https://github.com/servo/servo/pull/14801, https://github.com/servo/servo/pull/14802, and https://github.com/servo/servo/pull/14819.

Still a few things missing, I guess I'll send an email to dev-servo as a PSA.
