### ISSUE TITLE
Implement ArrayBuffer and ArrayBufferView variants of WebSocket::Send

### ISSUE THREAD

**Issue by jdm** [servo/servo#14761]
https://dxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/websockets/binary/004.html fails with:
```
WebSockets: Send/Receive ArrayBuffer, size greater than network array buffer
----------------------------------------------------------------------------
Expected PASS, got FAIL
assert_equals: expected (number) 100000 but got (undefined) undefined
```
This corresponds to `assert_equals(e.data.byteLength, datasize);` in the test, where `e.data` is supposed to be an ArrayBuffer object. `console.log(e.data)` shows `[object ArrayBuffer]`, while `console.log(e.data.byteLength)` shows `undefined`, and `console.log(Object.getPrototypeOf(e.data))` shows the empty string. I am very confused by these results.

**Comment by jdm** [comment]
I figured it out - all of the arraybuffer tests provide arraybuffers as input, but we haven't implemented that yet so they get converted to strings. This means that the tests all send input which is the stringified arraybuffer object, so they receive a string like `[object ArrayBuffer]` instead of binary data that gets converted into an arraybuffer object.

**Comment by jdm** [comment]
This needs to wait until #5014, unfortunately. I don't think we can handle overloads of webidl methods that include object types.

**Comment by Ms2ger** [comment]
We probably could, but would need to handle interface types manually... Not sure if the distinction would be detectable.

**Comment by jdm** [comment]
Duplicate of #20347.
