### ISSUE TITLE
Make per-document initial computed values actually work in servo

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#14773]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1298588 I'm doing some of the work, and making them work with stylo, but there are some outstanding servo issues:

1. build_shared_layout_context needs to get the per-document structs from somewhere.  Which means they need to live somewhere.
2. All the media query bits.

These may not be urgent because it's possible that in servo right now the initial computed values can't actually change.

**Comment by nox** [comment]
@emilio Wasn't this done?

**Comment by emilio** [comment]
This is not done in servo, no.
