### ISSUE TITLE
Set origin header in http_network_or_cache_fetch

### ISSUE THREAD

**Issue by jdm** [servo/servo#14787]
There's a TODO comment pointing at https://github.com/hyperium/hyper/pull/691, but that was closed in favour of https://github.com/hyperium/hyper/commit/01843f882265a894c7051dc2ecf5cf09f2c2e8e7. We should be able to address the TODO now.

Code: `components/net/http_loader.rs`

**Comment by rabisg** [comment]
I would like to work on this

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear.

**Comment by rabisg** [comment]
PR Link: https://github.com/servo/servo/pull/14811

**Comment by jdm** [comment]
The work in #14811 looked great, but it needs some review comments addressed. Anybody is welcome to finish off that effort!

**Comment by samgiles** [comment]
Oops, sorry I picked this up quickly in the ref'd PR.
