### ISSUE TITLE
Request mode doesn't have websocket option

### ISSUE THREAD

**Issue by mattnenterprise** [servo/servo#14785]
`RequestMode` in `components/net_traits/request.rs` could possibly have the value of "websocket" according to the [spec](https://fetch.spec.whatwg.org/#concept-request-mode). Currently `RequestMode` doesn't have the option of being websocket so it should be added.

**Comment by dowoncha** [comment]
Is it as simple as adding WebSocket to the RequestMode enum?

**Comment by jdm** [comment]
Yes.

**Comment by dowoncha** [comment]
PR Link #14895

**Comment by dowoncha** [comment]
Adding the WebSocket enum variant now triggers implementation error in dom/request.rs. Tried to add match case in dom/request.rs but since variant isn't included in bindings, cannot add it in. Ideas?
