### ISSUE TITLE
Change some of the `match` to `if let`

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14788]
`git grep -E ' ((Ok|Err)\((_|\(\))\)|None) => \{\}'` throws a lot of files. Some of these stuff can be changed to [`if let`](https://doc.rust-lang.org/book/if-let.html), since the counterparts have no purpose to serve us. Not everything can be changed, because some of the patterns in the neighborhood have guards or nested variants, for example.

PS: This should really be done with clippy, but well...

**Comment by jlevesy** [comment]
Hey ! I would like to work on this one !

**Comment by Wafflespeanut** [comment]
Awesome!
