### ISSUE TITLE
Parse arbitrary expressions for @font-face declarations

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#14799]
There's no requirement that a valid `@font-face` rule to have its descriptors parse as per their corresponding grammar.

Thus, `@font-face {src: blah blah blah}` is valid, even though `blah blah blah` isn't valid grammar for the `src` descriptor. Similarly, unknown descriptors should also parse fine. The grammar of descriptors comes into account whilst using an `@font-face` rule, but a rule with invalid descriptors should still parse and be considered part of the CSSOM.

Test: css-conditional-3_dev/xhtml1/001.xht

I'm not sure if the test is matching the spec here. At https://github.com/servo/servo/blob/b06f4aec67ff93b1d667a5817084b0952e56664e/tests/wpt/css-tests/css-conditional-3_dev/xhtml1/001.xht#L192 it tries to insert `@font-face { font-family: foo; src: url('http://www.example.com/foo'; }`. `url('http://www.example.com/foo'` is missing a closing brace, which isn't a valid `expr` (https://www.w3.org/TR/CSS21/grammar.html#grammar) afaict, [and the spec only allows for `expr`s](https://drafts.csswg.org/css-fonts-3/#descriptordeclaration) in descriptor values. Firefox and Chrome seem to be fine with this and seemingly accept arbitrary token streams, however.

cc @heycam

**Comment by jdm** [comment]
https://drafts.csswg.org/css-syntax/#consume-url-token may explain why Firefox and Chrome behave that way.

**Comment by Manishearth** [comment]
It says that an unfinished URI is a parse error though? Hm. 

Grammar is a bit more specific on what a URI is.

**Comment by jdm** [comment]
If you look at the definition of a parse error, it's less straightforward than it sounds.
