### ISSUE TITLE
ReCAPTCHA layout is very wonky

### ISSUE THREAD

**Issue by jdm** [servo/servo#14805]
Loading https://admin.phacility.com/auth/register/:
In Firefox:
<img width="399" alt="screen shot 2016-12-31 at 11 27 59 am" src="https://cloud.githubusercontent.com/assets/27658/21578390/351beb6a-cf4c-11e6-852f-ab310506de18.png">
In Servo:
<img width="587" alt="screen shot 2016-12-31 at 11 27 15 am" src="https://cloud.githubusercontent.com/assets/27658/21578389/2769be48-cf4c-11e6-9a2d-ec15d83774ae.png">

**Comment by jdm** [comment]
Turns out it's a table.

**Comment by nox** [comment]
I'm pretty sure the old captcha is not available anymore to reproduce this issue. Closing.
