### ISSUE TITLE
Implement Window.getSelection

### ISSUE THREAD

**Issue by jdm** [servo/servo#14803]
https://hypothes.is/assets/client/scripts/injector.bundle.js (which is used in http://wiki.c2.com/?AntiPatternsCatalog) checks for the presence of getSelection and assumes that the browser is IE if it isn't present, so it loads https://github.com/tcr/IERange which uses IE-only APIs.

Spec: http://w3c.github.io/selection-api/#dom-window-getselection

**Comment by iamrohit7** [comment]
I would like to work on this.

**Comment by jdm** [comment]
I'm hesitant to add support for getSelection until we actually support selecting webpage content (input textboxes don't count; they don't appear to change the return value of getSelection). That's tracked in #7492.

**Comment by iamrohit7** [comment]
@jdm If someone can mentor me, I'd love to work on that too.

**Comment by nox** [comment]
Let's close this in favour of #7492.
