### ISSUE TITLE
Can't use latest gmail

### ISSUE THREAD

**Issue by jdm** [servo/servo#14812]
Following the steps in #14782 with the patch from #14480 applied, I am brought to the "Do you really want to use HTML Gmail?" page. If I click the "Take me to the latest Gmail" button, I end up at the same page.

**Comment by jdm** [comment]
If I set the user agent to "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:53.0) Gecko/20100101 Firefox/53.0", then I do not see that screen. Nice.

**Comment by miller-time** [comment]
This happened to me yesterday using Nightly `72.0a1 (2019-11-27) (64-bit)` on Ubuntu Mate `19.10 (eoan)`.

Tried again today and it seems to be working... Same version of Nightly, same browser instance even - I just refreshed the page and tried again.

**Comment by jdm** [comment]
This is an issue specific to Servo and unrelated to Firefox Nightly. Also Servo has updated its user agent in the past three years so I'm going to go ahead and close this :)

**Comment by miller-time** [comment]
Haha I didn't notice the year was 2017, sorry! I found it slightly interesting that this was happening in Firefox and also Servo.

Sorry for the poke on a very old issue 😆
