### ISSUE TITLE
Build Failure on Windows 10

### ISSUE THREAD

**Issue by SLMT** [servo/servo#14810]
I got the following error while building Servo using this command: `.\mach.bat build -d`
```
Pip failed to execute properly:
Output:
Error: Command "python setup.py egg_info" failed with error code 1 in C:\Users\SLMT\AppData\Local\Temp\pip-build-fcayjlgs\mozprofile\
```

My Python was installed via Anaconda, here is the version I used:
```
(py27) f:\Rust\servo> python -V
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)
```

and here is the version of my pip:

```
(py27) f:\Rust\servo>pip -V
pip 9.0.1 from G:\DevelopmentSoftwares\Anaconda3\envs\py27\lib\site-packages (python 2.7)
```

I searched this error on Google, and found [this post](http://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c) on Stackoverflow, but this didn't work for me.

**Comment by lygstate** [comment]
Remove python/virtualenv works.

**Comment by nox** [comment]
Superseded by #18775.
