### ISSUE TITLE
Remove duplicate code in mach

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14815]
[This span of code](https://github.com/servo/servo/blob/62ff467be855f222829ec961a104a0fdd3e083b0/python/servo/post_build_commands.py#L100-L103) is [already available](https://github.com/servo/servo/tree/62ff467be855f222829ec961a104a0fdd3e083b0/python/servo/package_commands.py#L126-L130
) as a function in `package_commands.py`. Let's move that function to `command_base.py` and use it in both `post_build_commands.py` and `package_commands.py`

**Comment by teosz** [comment]
I intend to work on this. Thank you!
