### ISSUE TITLE
Build fails on MacOS 10.11

### ISSUE THREAD

**Issue by algorev** [servo/servo#14826]
Build output with RUST_BACKTRACE=1, no XCode, only CLT, on an iMac 2013 with 16Gib of RAM:

TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("x86_64-apple-darwin")
debug=false opt-level=3
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-o" "/Users/Famille_Pintado/stuff/servo/target/release/build/openssl-87c538093dbe2342/out/src/c_helpers.o" "-c" "src/c_helpers.c"
cargo:warning=src/c_helpers.c:1:10: fatal error: 'openssl/ssl.h' file not found
cargo:warning=#include <openssl/ssl.h>
cargo:warning=         ^
cargo:warning=1 error generated.
ExitStatus(ExitStatus(256))

command did not execute successfully, got: exit code: 1

--- stderr
thread 'main' panicked at 'explicit panic', /Users/Famille_Pintado/stuff/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.40/src/lib.rs:1006
stack backtrace:
   1:        0x10b6028fc - std::sys:: imp ::backtrace::tracing:: imp ::write::h36c82bddc32ee014
   2:        0x10b6078ce - std::panicking::default_hook::{{closure}}::h5befc2c9c6395cdf
   3:        0x10b607570 - std::panicking::default_hook::hc066c0e0f8dcf194
   4:        0x10b607cd6 - std::panicking::rust_panic_with_hook::hb2f44ed7df6389fd
   5:        0x10b5eab44 - std::panicking::begin_panic::h91eb2e947cddccf8
   6:        0x10b5f627e - gcc::fail::hbd0e42f6e077c40c
   7:        0x10b5f5e38 - gcc::run::hfb7c1a81f22633ef
   8:        0x10b5ee005 - gcc::Config::compile::hfb931778eda21592
   9:        0x10b5e9993 - build_script_build::main::h7fe184d3fc4c954a
  10:        0x10b60a4da - __rust_maybe_catch_panic
  11:        0x10b608086 - std::rt::lang_start::hba46b5e984e5d783

Build FAILED in 0:00:07

Had to format it a little, Github was rendering :: imp::s as ::imp::

**Comment by algorev** [comment]
Log with verbose option, replaced the session name with "bob":
[buildlog.txt](https://github.com/servo/servo/files/681351/buildlog.txt)

**Comment by jdm** [comment]
You're missing the openssl setup that's required in https://github.com/servo/servo/blob/master/README.md#on-os-x--1011-el-capitan-you-also-have-to-install-openssl

**Comment by algorev** [comment]
Oh, thanx, it worked!
