### ISSUE TITLE
error on loading apple.com

### ISSUE THREAD

**Issue by ron-wolf** [servo/servo#14820]
Ran `servo http://apple.com`; page is blank; console prints repeatedly with occasional pauses:
```
ERROR:script::dom::bindings::error: Error at http://images.apple.com/v/home/cz/built/scripts/main.built.js:1916:23 a is undefined
```

**Comment by jdm** [comment]
This corresponds to `var c;c=a.next;`, where `a` is `var a=this._items[b];` and `b` is `var b=this.getCurrentItemIndex();`. Nothing clearly wrong yet.

**Comment by atouchet** [comment]
I'm able to load the page although it does have a number of visible issues.

**Comment by nox** [comment]
I can't reproduce this anymore, but I do hit #14779 now. Closing this issue.
