### ISSUE TITLE
Unminify JS and dump it to a file before executing it

### ISSUE THREAD

**Issue by jdm** [servo/servo#14824]
Issues like #14820 are annoying to debug because we don't have introspection tools like Firefox's JS debugger. We should add a command line option to Servo that causes the browser to create a directory for each page that is loaded, and every script that gets compiled first is run through an unminifier, then stored in a file in the directory before being evaluated. This means that the error messages will references lines and columns in the unminified JS, and we can be confident that we're looking at the same files that Servo evaluated.

**Comment by jdm** [comment]
https://github.com/beautify-web/js-beautify

**Comment by jdm** [comment]
I recommend making the command line flag described here [invoke](http://doc.servo.org/std/process/struct.Command.html) the `js-beautify` command that can be installed with `pip install jsbeautifier`.

**Comment by jdm** [comment]
Suggested plan of attack:
* write out the scripts unminified from `components/script/dom/htmlscriptelement.rs` to the current working directory
* make `Window::new` create a directory for the document url in `components/script/dom/window.rs`, and make `HTMLScriptElement` use that directory
* add a command line flag that controls this behaviour to `components/config/opts.rs`
* invoke the beautifier before writing out and storing the script data

**Comment by charlesvdv** [comment]
I'm interested to try tackling this issue.

**Comment by jdm** [comment]
@charlesvdv Sorry, there's a student I'm in contact with who I would like to give the right of first refusal. Please hold off unless I say otherwise!

**Comment by jdm** [comment]
If you'd like a suggestion for something else that might be similarly interesting, I can take a look. Let me know!

**Comment by nox** [comment]
@jdm Shouldn't we use sourcemaps when available, instead?

**Comment by jdm** [comment]
Maybe! I'm not sure if we can get information about them without evaluating the minified JS, though.
