### ISSUE TITLE
Some shorthand serializations print unspecified properties too

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#14832]
Some shorthands are printinting default longhand values if the longhands are not specified. And some shorthands are just ignoring not specified shorthand properties. I think we should make the serialization same for all. Firefox generally prefers adding initial values to serialization but Chrome just ignores these ones. I'm in favour of just ignoring unspecified longhands. What do you think?

**These are the shorthands that print unspecified longhands(as far as I find):**

- background (gecko prints all properties but chrome prints just specified ones)
- border-image (gecko prints all properties but chrome prints these as separate longhands. I don't know why)
- transition (gecko prints all properties but chrome prints just specified ones)
- animation (gecko prints all properties but chrome prints just specified ones)
- columns (other browsers print all properties too)
- list-style (gecko prints all properties but chrome prints just specified ones)
- mask (gecko prints all properties but chrome prints just specified ones)
- outline (just width and style property prints default value, color doesn't printed.)
- -moz-outline-radius (gecko serializes this as four sides shorthand. We should do this too, I think.)
- flex-flow (gecko prints all properties but chrome prints just specified ones)

cc @Manishearth @emilio @Wafflespeanut

**Comment by Manishearth** [comment]
cc @heycam who may know what we should be doing here


I suspect the spec doesn't impose any requirements here, serialization is usually underspecced.

What do you mean by "chrome prints these as separate longhands"?

**Comment by canaltinova** [comment]
@Manishearth Chrome serializes this: `border-image: url("servo.png");` like this: 
```
border-image-source: url("servo.png"); border-image-slice: initial; border-image-width: initial; border-image-outset: initial; border-image-repeat: initial;
```

**Comment by Manishearth** [comment]
I guess that's just a bug (@domenic?)

**Comment by domenic** [comment]
I leave all CSS questions for @TabAtkins. I believe he was working on specifying serializations recently, in fact.

**Comment by tabatkins** [comment]
Kinda, yes.  I've got an action on myself to specify the serialization of every property in CSS.  I have not yet started on this, but it's a required part of one of the Houdini APIs, so I should do it soon... ^_^

**Comment by upsuper** [comment]
Also see w3c/csswg-drafts#1068.

**Comment by upsuper** [comment]
And see the simplification in serialization code we can do in #15779 after #15761.

**Comment by nox** [comment]
Given Stylo landed, I'm fairly sure this was taken care of some way or another. Closing.
