### ISSUE TITLE
Allow setting numeric preferences from the command line

### ISSUE THREAD

**Issue by jdm** [servo/servo#14842]
The code to process `--pref name=value` command line arguments currently recognizes boolean values as special, and otherwise defaults to treating the value as a string. We should check if the value can be parsed as a number and set a numeric preference if possible.

Code: `components/config/opts.rs`

@charlesvdv Want to fix this?

**Comment by jdm** [comment]
Also, it might be useful to make it possible to write automated tests for our command line argument processing code.

**Comment by asajeffrey** [comment]
This came up in the context of #14312 which is using an opt rather than a pref for this reason.

**Comment by charlesvdv** [comment]
I'm interested ! Thanks @jdm !
