### ISSUE TITLE
No window appears on macOS using latest Nightly

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#14852]
Possibly due to the recent changes in the packaging scripts.

**Comment by cbrewster** [comment]
The problem is that using a relative browserhtml path (`../Resources/browserhtml/index.html` set in `prefs.json`) doesn't work. The previous solution was the `run-servo` script.

**Comment by jdm** [comment]
Is this https://github.com/servo/servo/pull/14817#issuecomment-269983553 or something else?
