### ISSUE TITLE
Better handling of about:blank and iframes

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#14856]
We now have `about:blank` loading synchronously; however, only the **initial about:blank** should be loaded synchronously. There are also a few other issues I have uncovered while looking into #13716.

1. Only the initial `about:blank` should be loaded synchronously
2. `about:blank` should still be treated as same-origin and share the source pipeline's event loop.
3. An iframe should only update its current pipeline id after the corresponding pipeline has matured.
4. Constellation should remove any in progress loads during an iframe navigation

cc @asajeffrey @jdm

**Comment by asajeffrey** [comment]
A simpler(?) way to handle `about:blank` being loaded in the same script thread as its parent would be to change `new_pipeline` to use the parents `event_loop` when loading `about:blank`.

**Comment by cbrewster** [comment]
@asajeffrey updating the active pipeline id of the iframe seems very tricky. We cannot set it right after the document is created and inserted into a script thread's documents as the iframe may be located in another script thread. Also updating it after the constellation gets the activate document message and then sends the framed content changed message to the script thread seems to have other issues. Possibly it is setting it too late?

Any ideas?

**Comment by cbrewster** [comment]
I'm kinda of spinning in the mud on #14764. Might need to take a different approach. Here are the current issues that need fixed:

 * Differentiate between initial and non-initial `about:blank`s.
 * Keep initial `about:blank` loads synchronous
 * Load non-initial `about:blank` asynchronously but still go through the script thread so the right script thread can be shared.
 * Wait until the new load matures before updating the current pipeline id on the iframe.
 * Cancel the load event for initial `about:blank` loads when the nesting browsing context is created without a `src` (This will prevent 2 load events from firing see #15727).
 * Constellation should keep track of whether a pipeline or history entry represents an initial `about:blank` load. If so, any later navigations must have replacement enabled (see #14720).

The major pain point is dealing with timing between the constellation/script and figuring out the proper times to fire load events.
