### ISSUE TITLE
Combine UpdatePipelineId and FramedContentChanged

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#14854]
`UpdatePipelineId` is sent when an iframe's pipeline becomes active during a history traversal
`FramedContentChanged` is sent when an iframe's pipeline has become active after a load

These two seem to be doing similar things. The only difference is `FramedContentChanged` triggers a reflow. Should we be doing this in both cases? If so, these two messages can be combined.

cc @asajeffrey

**Comment by asajeffrey** [comment]
Agreed.

**Comment by cbrewster** [comment]
Done in #16506
