### ISSUE TITLE
Need to adjust end of iteration check for decimal animation-iteration-count

### ISSUE THREAD

**Issue by hiikezoe** [servo/servo#14858]
This is a follow-up issue of #14851.

In #14851, we allow decimal value for animation-iteration-count, as a result, the iteration duration of the final iteration is not reached to the end of duration of the final iteration if the iteration-count is not integer.  So, IIUC, a check 'now < state.started_at + state.duration' [1] in update_animation_state will miss the end of iteration check inside KeyframesAnimationState::tick().

[1] https://github.com/servo/servo/blob/4216c16879efb6e87b3ba3b7b4d5c2aeb8e2739d/components/layout/animation.rs#L79

CC @emilio

**Comment by nox** [comment]
@emilio Is this still relevant?

**Comment by mrobinson** [comment]
Yep, this is still an issue. Hopefully this is something that should be pretty straight-forward to fix once the animations and transitions code has been reworked.
