### ISSUE TITLE
Make tidy fall back to the default os.walk if git isn't available

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#14855]
Right now, if we run `./mach test-tidy` it relies on `git` to get the changed files from the last merge. This will result in an error if we're not in a git repo (like stylo, which is based on mercurial). Tidy should check whether git is available, and if it's not (`subprocess.check_output('git status')` will throw a `fatal: ...` in that case), `only_changed_files` should be set to `False`.

Code: `python/tidy/servo_tidy/tidy.py`

**Comment by anryko** [comment]
I'll do this.

**Comment by jdm** [comment]
I think there's already a solution proposed in #14853.

**Comment by anryko** [comment]
heh, ok.
