### ISSUE TITLE
Handle alternate stylesheets

### ISSUE THREAD

**Issue by mrnayak** [servo/servo#14881]
Servo seems to ignore alternate stylesheet. This was done to fix #10284.  This change has caused timeout error in #14865.

**Comment by emilio** [comment]
So [the spec](https://html.spec.whatwg.org/multipage/semantics.html#link-type-stylesheet) apparently requires us to fetch the resource even though we don't apply it?

**Comment by mrnayak** [comment]
I guess so. Applying alternate style-sheet is left to user. I found chrome and firefox fetch all alternate style sheets.

**Comment by jdm** [comment]
I am surprised by this, given the list under ["The appropriate times to obtain the resource are"](https://html.spec.whatwg.org/multipage/semantics.html#link-type-stylesheet:concept-link-obtain).

**Comment by jdm** [comment]
Actually, that text seems to imply that it should always be fetch regardless of its alternative status, but it should additionally be fetched again when that status changes. @charlesvdv does this sound like something you'd like to work on?

**Comment by charlesvdv** [comment]
If I understand well, I have to change what's been made by https://github.com/servo/servo/issues/10284 to handle the alternate stylesheet (and not ignore) and fetch them without actually apply the style on the page ?

**Comment by jdm** [comment]
That is correct!

**Comment by charlesvdv** [comment]
ok great I will do it 👍
