### ISSUE TITLE
One layout thread per script thread?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14885]
At the moment, every document gets its own layout thread, which is wasteful as most of them are frozen. Can we have one layout thread per script thread instead? 

This is related to #14719. cc @emilio

**Comment by emilio** [comment]
I think yes, also, that's the only way to properly handle iframe resizes from layout's point of view.

**Comment by asajeffrey** [comment]
It may be a bit tricky to do iframe resizes this way, since the iframe's parent may be in a different process. The constellation is probably going to need to mediate, which may cause issues for synchronous size queries.

**Comment by emilio** [comment]
Yeah, but visible effects are only on same-origin iframes, check out boris's comment in the other issue.

**Comment by asajeffrey** [comment]
True, but we might have an A:B:A situation, where the root document and its grandchild are same-origin, but the grandchild is in a cross-origin iframe, so its size depends on a layout thread in another process.

**Comment by emilio** [comment]
Yeah, but in that case the two same-origin iframes can't have any relationship right? (You can't reach via script the contentDocument of the other, for example, right?)

**Comment by jdm** [comment]
`window.frames[0].contentDocument` is totally valid.

**Comment by emilio** [comment]
Even cross-origin? huh

**Comment by asajeffrey** [comment]
It allows a grandchild to access it's same-origin grandparent even if it's parent is cross-origin.

**Comment by nox** [comment]
@asajeffrey Are you actually still working on this?

**Comment by asajeffrey** [comment]
Not actively. @emilio?

**Comment by emilio** [comment]
This would be nice, but requires singificant rework I'm not actively looking into.

**Comment by mrobinson** [comment]
I think this is pretty much fixed by #31346. Not only is there one layout thread per script thread, they are the same thread. Maybe in the future they will be two. It's possible.
