### ISSUE TITLE
`yahoo.com` crashes on Android

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#14880]
Servo crashes on start when I try to open `yahoo.com`:

```
D/RustAndroidGlueStdouterr(14544): WARN:servo: Panic hook called.
D/RustAndroidGlueStdouterr(14544): ERROR:servo: Failed to get window position.
D/RustAndroidGlueStdouterr(14544): Failed to get window position. (thread <unnamed>, at /buildslave/rust-buildbot/slave/nightly-dist-rustc-arm-android/build/src/libcore/option.rs:715)
E/Gecko   (14544): mozalloc_abort: Redirecting call to abort() to mozalloc_abort
F/libc    (14544): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 14560 (m.mozilla.servo)
D/RustAndroidGlueStdouterr(14544): fatal runtime error: failed to initiate panic, error 9
```

Commit 143dfc879e609603839502d61bc064fba96cc80f, tested on an Odroid XU3 running Android 4.4.4.

**Comment by jdm** [comment]
This is the unwrap at https://dxr.mozilla.org/servo/rev/94d62a2afbbbb08d0225dd45fd8a8480d4bdf98d/ports/glutin/window.rs#811 . This returns a None value on Android: https://github.com/servo/glutin/blob/01c528f085c2489cea88ae2c247a3411ce07ea0b/src/api/android/mod.rs#L171

**Comment by jdm** [comment]
This is still the case in a more recent upstream revision, too: https://github.com/tomaka/winit/blob/bc0dd0f854bca9d3a526814b53508dcfd25a74e2/src/platform/android/mod.rs#L160

**Comment by nox** [comment]
Is this still happening?

**Comment by pwnorbitals** [comment]
No confirmation for two years. Issue should be confirmed or closed imho

**Comment by jdm** [comment]
Our android builds don't rely on winit any more, so this can be closed.
