### ISSUE TITLE
Add a tidy check for use statements with extraneous spaces

### ISSUE THREAD

**Issue by jdm** [servo/servo#14898]
We prefer this:
```rust
use foo::bar::{Something, SomethingElse};
```
to this:
```rust
use foo::bar::{ Something, SomethingElse };
```
We should add a check to tidy for this; probably verifying that the line starts with `use` for simplicity.

Code: `python/tidy/servo_tidy/tidy.py`
Tests: `python/tidy/servo_tidy_tests/rust_tidy.rs`, `python/tidy/servo_tidy_tests/test_tidy.py`, and run `./mach test-tidy --self-test`

**Comment by vwvww** [comment]
I want to work on this issue.

**Comment by jdm** [comment]
Great! Please ask questions here if anything is unclear.

**Comment by jdm** [comment]
@vwvww Did you make any progress on this? Are you still working on it?

**Comment by vwvww** [comment]
@jdm Sorry, I was busy on personal works so I could not get into this issue... I'll restart working on this issue today.

**Comment by jdm** [comment]
Go ahead and make a PR with those changes; they look good to me.
