### ISSUE TITLE
Serializing origins

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#14892]
IRC conversation with @bzbarsky: http://logs.glob.uno/?c=mozilla%23servo&s=6+Jan+2017&e=6+Jan+2017#c588833

Origin objects have object identity, which can be observed in at least two ways: a) we create new opaque origins, then check their identity, and b) `document.domain` allows origin objects to be mutated.

This is fine for threads which share an address space, not so good for serializing origins from script to the constellation. In particular, we need to store origins in the session history, so that if an `about:blank` page is reloaded, it does so with the same origin as it had before.

**Comment by Ms2ger** [comment]
Did we end up moving to process-global counters rather than uuids for opaque origins? We would probably need to revert that if we want to send origins across processes.

**Comment by asajeffrey** [comment]
We did move away from uuids and we would have to move back if we wanted them to be global.

**Comment by asajeffrey** [comment]
This is needed in a few places: anywhere we're sending origins to the contstellation, and anywhere where a helper thread needs to know the origin that its acting on behalf of, notably fetch.
