### ISSUE TITLE
Add a tidy check for lines that start with =

### ISSUE THREAD

**Issue by jdm** [servo/servo#14890]
Servo's code style says that we prefer this:
```rust
let some_long_var_name =
    some_long_expression_that_does_not_fit_on_the_previous_line;
```
instead of this:
```rust
let some_long_var_name
    = some_long_expression_that_does_not_fit_on_the_previous_line;
```
It should be possible to catch this if a Rust source line begins with an `=`.

Code: `python/tidy/servo_tidy/tidy.py`
Tests: `python/tidy/servo_tidy_tests/rust_tidy.rs`, `python/tidy/servo_tidy_tests/test_tidy.py`, and run `./mach test-tidy --self-test`

**Comment by g1smo** [comment]
I'd like to try this one.

**Comment by jdm** [comment]
Please do! Ask questions here if anything is unclear!
