### ISSUE TITLE
Documents are never fully deactivated

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#14906]
We `fully_activate` documents when a thaw message is sent but never `fully_deactivate` them when a freeze message is sent.

cc @asajeffrey

**Comment by asajeffrey** [comment]
Oops, this sounds like a victim of rebasing. I must have resolved merge conflicts incorrectly.

**Comment by cbrewster** [comment]
`handle_freeze_msg` should `fully_deactivate` the document (you will need to adjust the code to get the document instead of the window.

Relevant code: https://dxr.mozilla.org/servo/rev/50bba770d6073bba6e6e219dbc3687087a864a42/components/script/script_thread.rs#1355-1390

**Comment by prampey** [comment]
@cbrewster Hi. I'd like to work on this issue.

**Comment by cbrewster** [comment]
@prampey it's all yours! Thank you!

**Comment by prampey** [comment]
@cbrewster Okay, so I added in this line in `handle_freeze_msg`:
`window.Document().fully_deactivate();`
Is that fine?

**Comment by cbrewster** [comment]
@prampey I would prefer if you changed:
```
let window = self.documents.borrow().find_window(id);
```
to
```
let document = self.documents.borrow().find_document(id);
```
and then access the window through the document `document.window()`.
This is just for the sake of keeping it consistent with `handle_thaw_msg`.

Thank you for working on this!

**Comment by prampey** [comment]
@cbrewster Oh yeah! Code looks more concise now. So this it:
```
let document = self.documents.borrow().find_document(id);
        if let Some(document) = document {
            document.window().freeze();
            document.fully_deactivate();
            return;
        }

```

**Comment by cbrewster** [comment]
@prampey looks good!

**Comment by prampey** [comment]
@cbrewster Awesome. I'll send in the PR.

**Comment by prampey** [comment]
#15016
