### ISSUE TITLE
Should Cargo.toml use default_features or default-features?

### ISSUE THREAD

**Issue by fkautz** [servo/servo#14915]
The manifest format calls for default-features. Servo uses default_features instead.

Does default_features resolve to default-features? If not, default_features should be updated to default-features in all Cargo.toml files.

**Comment by fkautz** [comment]
Relevant documentation: http://doc.crates.io/manifest.html is the source of information for default-features formatting.

**Comment by jdm** [comment]
Even if it does work, I think we should change it for consistency and clarity.

**Comment by fkautz** [comment]
https://github.com/servo/servo/pull/14917

**Comment by fkautz** [comment]
#14917 was merged, closing.
