### ISSUE TITLE
Root element with table display doesn't account for CSS width and height

### ISSUE THREAD

**Issue by jdm** [servo/servo#14948]
```html
<html style="display: table; width: 100%; height: 100%; border: 1px solid black">
<body>
  <h1>CSS FPS</h1>
</body>
</html>
```
Servo:
<img width="1138" alt="screen shot 2017-01-10 at 1 28 26 pm" src="https://cloud.githubusercontent.com/assets/27658/21819184/b289ed7e-d738-11e6-9b1e-6d41cffe90d1.png">
Firefox:
<img width="1554" alt="screen shot 2017-01-10 at 1 28 41 pm" src="https://cloud.githubusercontent.com/assets/27658/21819193/ba36833e-d738-11e6-841b-33f9763b5c24.png">

**Comment by charlesvdv** [comment]
I'm interrested to try fix this!
