### ISSUE TITLE
Fully implement parsing/serialization for mask-repeat and background-repeat for geckolib

### ISSUE THREAD

**Issue by upsuper** [servo/servo#14954]
https://developer.mozilla.org/en-US/docs/Web/CSS/mask-repeat
https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat

The grammar is `<repeat-style>#` where `<repeat-style>` is `repeat-x | repeat-y | [ repeat | space | round | no-repeat ]{1,2}`.

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs. This bug requires familiarity with Rust.

Files:
* mask-repeat: https://github.com/servo/servo/blob/master/components/style/properties/longhand/svg.mako.rs
* background-repeat: https://github.com/servo/servo/blob/master/components/style/properties/longhand/background.mako.rs

**Comment by upsuper** [comment]
(This issue may account for up to 240 failures in Gecko's style system tests.)

**Comment by fkautz** [comment]
I'll take this on. Please assign this to me.

**Comment by Manishearth** [comment]
@fkautz is working on this

**Comment by jdm** [comment]
@fkautz Did you make any progress on this? Are you still working on it?

**Comment by faineance** [comment]
@highfive: assign me

**Comment by Manishearth** [comment]
Since there has been no response for a week, feel free to take this! @fkautz we can find something else for you to work on if you do find time later.

**Comment by fkautz** [comment]
@Manishearth @highfive feel free to take it, got caught up with way too much work. Sorry for the delay.

**Comment by jdm** [comment]
@faineance: have you made any progress?

**Comment by faineance** [comment]
Yeah I just have probably mostly incorrect beginnings, I should have time this weekend to finish it off.
https://github.com/servo/servo/compare/master...faineance:master

**Comment by jdm** [comment]
@faineance How's it going?

**Comment by jdm** [comment]
Unassigning due to lack of response.

**Comment by jbendig** [comment]
I'm willing to implement this if no one else is working on it.

**Comment by jdm** [comment]
Please do!
