### ISSUE TITLE
text-overflow: ellipsis - after the ellipsis character is added, it's never removed

### ISSUE THREAD

**Issue by jsnajdr** [servo/servo#14952]
STR:
1. Open this URL in Servo:
```
data:text/html,<div style='overflow:hidden;text-overflow:ellipsis'>helloworldhelloworld</div>
```
2. Resize the window to minimum width, so that the ellipsis kicks in. Several times, as the window is resized.
3. Resize the window back to original width.

Expected: ellipsis character eventually disappears, as there is no overflow any more.
Actual: several ellipsis characters are added and remain visible when the window width increases. The text is irreversibly truncated.

**Comment by Manishearth** [comment]
cc @notriddle 

IIRC we just append text to the fragment, which is probably wrong

**Comment by notriddle** [comment]
This is wrong, yeah.
