### ISSUE TITLE
Navigation keys should act on press, not release

### ISSUE THREAD

**Issue by sp3d** [servo/servo#14953]
Servo scrolls when the down arrow key is released (or when key repeat triggers), not when the key is pressed. It exits when escape is released, not when escape is first pressed. This makes the perceived latency for keyboard actions much higher and does not match the behavior of any other browser (Chrome, FF, WebKitGTK+-based, etc.) nor most applications or GUI toolkits.

This is reproducible at least under X11 on Linux.

**Comment by sp3d** [comment]
After more investigation, this bug (which is still present in master) seems subtler: based on debug printing, key processing does seem to occur on keypress for PageUp/etc., but the visual state of the window is not updated until key release. How does Servo decide when to draw a new frame?

**Comment by jdm** [comment]
In theory, the scrolling should be triggered from https://github.com/servo/servo/blob/master/ports/servo/glutin_app/window.rs#L1197. However, keyboard input actually starts in https://github.com/servo/servo/blob/master/ports/servo/glutin_app/window.rs#L386, which then passes it to the focused script thread via the constellation (https://github.com/servo/servo/blob/master/components/servo/lib.rs#L314). Any keyboard input which is not consumed by the page is then returned to the constellation (https://github.com/servo/servo/blob/master/components/script/dom/document.rs#L1296-L1297) and passed back to the embedding application (https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L1267), where it is ignored unless the state is "pressed" (https://github.com/servo/servo/blob/master/components/servo/lib.rs#L423), at which point we reach the first snippet that I linked to.

**Comment by jdm** [comment]
The actual scrolling that is initiated as a result of that keypress is https://github.com/servo/servo/blob/master/components/compositing/compositor.rs#L889, and there may be an unexpected delay introduced based on when pending_scroll_zoom_events is processed.

**Comment by sp3d** [comment]
This actually seems to have been fixed in master between March 14th and now.
