### ISSUE TITLE
Convert max-session-history command line argument into a preference

### ISSUE THREAD

**Issue by jdm** [servo/servo#14960]
Since #14863 was merged, it's now possible to use syntax like `--pref max-session-history=5` and have it work correctly. Let's convert the command line argument added in #14312 into a [preference](https://dxr.mozilla.org/servo/source/components/config/prefs.rs) by adding it to the [preferences JSON](https://dxr.mozilla.org/servo/source/resources/prefs.json) and modifying places that use the value to use the [preference API](https://dxr.mozilla.org/servo/rev/04a3242dc54c670dcdafcf1f0ac5373f2ed612f3/components/compositing/compositor.rs#1091).

Code: `components/config/opts.rs`, `components/constellation/constellation.rs`

**Comment by tydus101** [comment]
I'll be taking a look at this, thanks.

**Comment by jdm** [comment]
Great! Ask questions here if anything is unclear.

**Comment by tydus101** [comment]
Quick naming convention question: For `max_session_history` as a pref, is `dom.document.max_session_history` alright?

**Comment by jdm** [comment]
I would go with `session_history.max_length`.
