### ISSUE TITLE
Replace all try macros with `?`

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#14965]
Question mark looks stable in Rust, we can replace `try!` macros with `?`.
You can find all try! macro usages in dxr(or you can use a tool like grep): https://dxr.mozilla.org/servo/search?q="try!("

For example, we should replace `try!(formatter.write_str(c))` with this: `formatter.write_str(c)?`

**Comment by SimonSapin** [comment]
This tool https://github.com/japaric/untry does the conversion automatically. (Though the results should still be double-checked.)

**Comment by Ms2ger** [comment]
That's assuming we would want to do that; not sure we do.

**Comment by KiChjang** [comment]
@jdm has indicated that since the question_mark syntax is stable, he is ok with the changes from try! to ?. I don't think @nox has any objections as well.

**Comment by SimonSapin** [comment]
I’ve wanted to do that in `components/style`, just haven’t gotten around to.

I suspect this change will touch many files and so be somewhat disruptive. We should coordinate with other large changes landing around the same time to avoid too much bitrot.

**Comment by nox** [comment]
I, for one, welcome our new `?` overlord.

**Comment by nox** [comment]
https://github.com/servo/servo/pull/17390 happened, and this is good enough. Let's do the rest whenever we find some remaining `try!` uses.
