### ISSUE TITLE
innerHTML on a script tag escapes tag characters

### ISSUE THREAD

**Issue by jdm** [servo/servo#14975]
```html
<script type="text/template"><!-- hi --></script><script>console.log(document.querySelector('script').innerHTML)</script>
```
In Firefox, this prints `<!-- hi -->`. In Servo, it prints `&lt;-- hi --&gt;`.

**Comment by jdm** [comment]
The cause is [this match](https://github.com/servo/html5ever/blob/master/src/serialize/mod.rs#L200-L213) which says that the contents of script tags should be escaped.

**Comment by jdm** [comment]
That code matches what is written at https://html.spec.whatwg.org/multipage/syntax.html#serialising-html-fragments for "If current node is a Text node". Interestingly, outerHTML works fine, and innerHTML does not.

**Comment by jdm** [comment]
The `parent()` operation in the html5ever serializer gets the last element in the element stack. In the outerHTML case this is the element that is pushed in `start_elem`. In the innerHTML case this is the dummy initial value added in the serializer's constructor, so it's not considered to have a script element parent.

**Comment by jdm** [comment]
To fix this, in the case where the serializer is created with ChildrenOnly we should make the initial element contain the data for the actual element parent. We should add a unit test in html5ever for this case, as well as create a new [WPT test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) for Servo.

**Comment by jdm** [comment]
Actually, there's a useful `tests/wpt/web-platform-tests/html/syntax/serializing-html-fragments.html` test that already exists, and contains a relevant case: `<span><script type="test"><&></script></span>`. However, it only checks innerHTML and outerHTML of the span, rather than the script directly. Let's add another case to this that gets rid of the outer span.

**Comment by tormeh** [comment]
Can I claim this? I have no experience with Servo (except testing) and little with Rust, so if it needs to be done quickly then I'm probably not the correct person...

**Comment by jdm** [comment]
Please do! There's no rush, and the actual code changes will happen in the [html5ever](https://github.com/servo/html5ever/) repository.

**Comment by jdm** [comment]
To see how Servo uses the html5ever [serializer](https://github.com/servo/html5ever/blob/master/src/serialize/mod.rs), look at [Element::GetInnerHTML](https://github.com/servo/servo/blob/6e26197c069d8dc3e186e48e5a04ed6298b43066/components/script/dom/element.rs#L1870-L1874) and related code in the [HTML parser serialize implementation](https://github.com/servo/servo/blob/6e26197c069d8dc3e186e48e5a04ed6298b43066/components/script/dom/servoparser/html.rs#L249).

**Comment by tormeh** [comment]
Hmm... This bug is tagged with "C - has test", but when I run "cargo test" all the tests pass. Is the test wrong? And the code says that the contents of a script tag should not be escaped (i.e. let script = false;), while this thread and the title says they are. What am I missing?

**Comment by jdm** [comment]
The `has test` label means that the issue contains a minimal testcase that reproduces the problem. It still needs to be turned into a testcase that will run as part of `./mach test-wpt` (as suggested in [this comment](https://github.com/servo/servo/issues/14975#issuecomment-272187395)).

**Comment by jdm** [comment]
[This comment](https://github.com/servo/servo/issues/14975#issuecomment-272184456) explains the case in which the code does not operate correctly and chooses to escape the element contents when it should not.

**Comment by jdm** [comment]
Have you encountered any problems with fixing the issue, @tormeh?

**Comment by tormeh** [comment]
No, well, I'm new to Servo and Rust and inexperienced in HTML, git and Github. So even though the bug itself is easy, everything around it really slows me down. Which is frustrating. But I also learn quite a bit.

**Comment by jdm** [comment]
#15148 ran into some problems due to the master of html5ever being different from the version that Servo was using. This is now available for anybody to work on again.

**Comment by seanlee31** [comment]
Hi there! I would like to work on this bug. I'm new to bugzilla/servo and may need some additional help. I've looked into the code and am not sure if the main problem was caused by  [escape](https://github.com/servo/html5ever/blob/master/src/serialize/mod.rs#L200-L213) mentioned in the first comments.
Thanks!

**Comment by seanlee31** [comment]
Also as mentioned in the second comment where the [write_text](https://github.com/servo/html5ever/blob/master/src/serialize/mod.rs#L187-L215) says the content of script should be escaped. However, I cannot see that write_text has been called in any serializing methods. Where is this method being called?

**Comment by jdm** [comment]
That is correct.

**Comment by seanlee31** [comment]
I've read thru past comments from the previous developer but not sure where to begin with. Also, the problem was fixed and started to occur again due to the inconsistency in html5ever that were being used? 

Thank you for your answer!

**Comment by jdm** [comment]
No, the problem mentioned was in trying to use a local clone of html5ever in Servo, which is required in order to modify it and see the changes in Servo.

**Comment by jdm** [comment]
First: add the test that demonstrates the problem. Second: get a local clone of html5ever working. Third: fix the problem in html5ever and make the test pass.

**Comment by seanlee31** [comment]
Okay I'll add some testcases to my local servo clone just like @tormeh did. But I'm not sure how to interact the testcases in local servo clone with the local clone of html5ever you mentioned since they're two different repos?
Also, can you please assign me to this bug?
Thanks!

**Comment by jdm** [comment]
Oh, I thought I had described that earlier, but it turns out I didn't! You want a [cargo override](http://doc.crates.io/specifying-dependencies.html#overriding-with-local-dependencies).

**Comment by seanlee31** [comment]
I just read thru the tutorial but now I'm confused with the relationship between servo and html5ever..
I thought html5ever is just a cargo crate (my understanding is its like a dependency for node.js) and I cant find where the source file pf html5ever in servo source files if the browser have applied it.

Sorry for too many questions.. still trying to get along with this!

Thanks!

**Comment by jdm** [comment]
Yes, Servo uses html5ever in the code in components/script/dom/parser/.

**Comment by KiChjang** [comment]
The repository for html5ever is in github.com/servo/html5ever.

**Comment by seanlee31** [comment]
Thanks for the info! I'm having a better idea on how Servo works now! So basically it does not include the actual package of the dependencies it uses but the link to their repo with current version?

**Comment by jdm** [comment]
If I understand your question correct, the answer is yes. Cargo.lock includes the precise information about where to find the html5ever package and what version to use, and part of the build process is obtaining a copy of that source code locally and linking it with Servo's code. The cargo override is an instruction to the build system to use that particular source code instead of the one specified by Cargo.lock.

**Comment by jdm** [comment]
Have you made any progress, @seanlee31?

**Comment by jdm** [comment]
Unassigning due to lack of response.

**Comment by jdm** [comment]
@o0Ignition0o Would you be interested in fixing this?

**Comment by moonlightdrive** [comment]
I'm interested in working on this. Will probably have a few questions.

**Comment by jdm** [comment]
Sounds good!

**Comment by jdm** [comment]
@moonlightdrive Did you make any progress here?

**Comment by o0Ignition0o** [comment]
Heyh @jdm, sorry for the late response (I've somehow muted the repo even though i didn't want to) Please consider me if the issue gets unassigned again !

**Comment by moonlightdrive** [comment]
I added the tests and have servo building with a local clone of html5ever.

The problem I am facing now is finding where in html5ever I need to make the change. I thought the `serialize` function in `html5ever/src/rcdom.rs` seemed reasonable, but changes here have had no effect.

Additionally I am not clear on the difference between html5ever and xml5ever (or if that's even relevant to this issue)

**Comment by Ygg01** [comment]
Hi, I wrote `xml5ever`, I'll try to help as much as possible! Basically `html5ever` and `xml5ever` are really, really similarly looking. Think of it as twin library. I tried to make sure that things are generally located in the same space (assuming you start from project root).

For example `html5ever/src/rcdom.rs`, in xml5ever is located in [`xml5ever/src/rcdom.rs`](https://github.com/servo/html5ever/blob/master/xml5ever/src/rcdom.rs).

**Comment by jdm** [comment]
I linked to the appropriate serializer implementation in one of the earlier comments: https://github.com/servo/html5ever/blob/master/src/serialize/mod.rs

**Comment by Jayflux** [comment]
Looks like this is also a cause of https://github.com/servo/servo/issues/16532

**Comment by KiChjang** [comment]
@moonlightdrive Are you still working on this?

**Comment by moonlightdrive** [comment]
Hi, I am still working on it. Sorry I've been so slow. If this issue needs to be fixed soon I am happy to give it up and maybe take a look at another one.

**Comment by jdm** [comment]
Still making progress @moonlightdrive? Do you have any questions that we can answer?

**Comment by moonlightdrive** [comment]
I definitely have a question, or at least some confusion, but think I need to poke around a bit more to know exactly what it is.

As far as I understand, the difference between the treatment of innerHTML and outerHTML is that the former is serialized with ChildrenOnly and the latter with IncludeNode. And this bug arises due to the fact that in the ChildrenOnly case, we didn't push that script node.. so when we check the parent to see if we need to escape, we've essentially discarded that information. As has already been said.

But I don't see, in `start_elem` (where there are 2 instances of nodes being pushed to the stack) how the IncludeNode and ChildrenOnly cases are being treated differently. 

Another question: what is happening [here](https://github.com/servo/servo/blob/47f0b4155cb2925dc0702aedf1a539b5ac22a286/components/script/dom/servoparser/html.rs#L308)? Is this where `script` is pushed in the outerHTML case?

Not sure if I've been clear with my questions. Please let me know and I'll try to clarify.

**Comment by jdm** [comment]
@moonlightdrive I think you're looking too deeply here. `start_elem` is responsible for serializing a single element, and leaving a record in the `stack` member of the element that was just serialized. It doesn't know (or care) about whether it's invoked as part of ChildrenOnly or IncludeNode. 

As to your second question, yes, through invoking `start_elem` there in the IncludeNode case (as used by outerHTML), the stack ends up with a meaningful entry for the outer `<script>` tag.

**Comment by jdm** [comment]
Looking more carefully, I think I see why you're asking those questions. I think the right thing to do might be to modify the html5ever [serialize](https://github.com/servo/html5ever/blob/10b48e46b11a1d0fc4d807a0548e371c67f3e3c6/src/serialize/mod.rs#L27-L32) method to push a [meaningful stack entry](https://github.com/servo/html5ever/blob/10b48e46b11a1d0fc4d807a0548e371c67f3e3c6/src/serialize/mod.rs#L120-L124) if the traversal scope is `ChildrenOnly`, or possibly even modify Serializer::new method to do that.

**Comment by jdm** [comment]
@moonlightdrive Are you still working on this?

**Comment by moonlightdrive** [comment]
I am actually a little unclear on where (which repository) to make this change. I have tried the following:

I tried making the fix by changing the `Serializer::new` method in html5ever. I am not sure how to get the tagname for the `html_name` field, without importing types from servo. It seems like html5ever is a more general library that should not depend on servo, correct?

Also took a look at pushing to the stack in the `serialize` method when the traversal scope is `ChildrenOnly` (implemented in servo repo). Thought I need [parent](https://github.com/servo/html5ever/blob/ab2bab056005c0803669da36daab7fa0a5292f08/src/serialize/mod.rs#L91) method (to check if the `None` value should replaced by the correct thing). `parent` is private. I tried to make it public (would this be undesirable?) but ran into an issue of "can't leak private types" (have done some googling but am still new to rust and don't quite understand why this occurs).

Not sure if I've misunderstood how to implement this.

Thank you

**Comment by jdm** [comment]
Sorry for the delay in responding. Good investigation! You're right that html5ever cannot depend on Servo (especially since Servo depends on html5ever). The error about private types occurs because a public function would now have a private type in its public interface; the private type in this case is `ElemInfo` which is defined in the same file.

As for the optimal solution, I think I have a useful idea for you. Let's make the `ChildrenOnly` variant of `TraversalScope` have a `Option<LocalName>` field. `Serializer::new` can look at the `traversal_scope` member of the options that receives and extract the name if it's present, and use that for the initial ElemInfo value. Am I making sense?

**Comment by moonlightdrive** [comment]
Yeah, that makes sense! I'll take a look at implementing that solution. Thanks :)

**Comment by moonlightdrive** [comment]
I think what I actually need is a function that's part of the [Serializer trait](https://github.com/servo/html5ever/blob/master/markup5ever/serialize.rs#L25), which will push/pop elements to the stack, without doing any of the writes that [`start_elem`](https://github.com/servo/html5ever/blob/master/html5ever/src/serialize/mod.rs#L97) or `end_elem` do.

I believe (and don't have a great grasp of Rust yet) that this function should have a signature like
``` rust
// i don't know what to name this fn yet
fn start_elem_without_write<T>(&mut self, elem: T);
```

and that the implementation of this function for [`HtmlSerializer`](https://github.com/servo/html5ever/blob/master/html5ever/src/serialize/mod.rs#L96) should be something like
``` rust
fn start_elem_without_write<ElemInfo>(&mut self, elem: ElemInfo) {
  self.stack.push(elem);
}
```

but this is evidently not right. The error I am getting is: expected struct 'serialize::ElemInfo', found type parameter. I guess this type parameter is `ElemInfo`? (Based on a compiler note: expected type `serialize::ElemInfo` found type `ElemInfo`) I don't understand why this is a type parameter rather than a thing that is as struct.
