### ISSUE TITLE
Create a safe, straightforward API to capture JS stacks

### ISSUE THREAD

**Issue by jdm** [servo/servo#14987]
https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/src/jsapi.h#L5895-L6039 looks like it gives us the building blocks we need in C++. We should make it as easy to capture JS stacks as possible and use them to help us debug problems with web compatibility.

**Comment by jdm** [comment]
The idea here is that `CaptureCurrentStack` gives us a JSObject that represents a captured stack. `BuildStackString` accepts a JSObject representing a captured stack and yields a string representation of the stack. A great way to start would be to make a Rust type that captures the stack in its constructor, and has a method that returns a Rust string representation. This type will need to refer to store a [RootedGuard](https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs#L69), meaning that it refers to a rooted JS object that was created earlier in the program. This object will store the captured stack.

**Comment by jdm** [comment]
It would make the most sense to build this in the rust-mozjs repository, rather than in servo itself.

**Comment by Mrowqa** [comment]
Hi, I will work on this. I have already read the code around and this seems like quite easy task.

**Comment by jdm** [comment]
@Mrowqa Great! Please ask questions if anything is unclear!

**Comment by Mrowqa** [comment]
@jdm Is that all or do we want something more? And thank you for the help :)

**Comment by jdm** [comment]
Good enough for now!
