### ISSUE TITLE
Print JS exception stack when reporting errors

### ISSUE THREAD

**Issue by jdm** [servo/servo#14988]
This looks like it will require [ExceptionStackOrNull](https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/src/jsapi.h#L5479-L5487) and [BuildStackString](https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/src/jsapi.h#L6019-L6032).

**Comment by asajeffrey** [comment]
The stack will be stripey, alternating Rust stacks with JS stacks. Is there a way to replace each of the JS stacks (where we currently report the C/C++ stack from SM) with the JS stack?

**Comment by asajeffrey** [comment]
Also, are there privacy concerns with including the JS stack?

**Comment by jdm** [comment]
When I say reporting errors, I mean the code that calls println! to report them to the terminal. That's all.

**Comment by jdm** [comment]
Also SM doesn't have any functionality to report C++ stacks.

**Comment by asajeffrey** [comment]
OK, not included in the crash report then. False alarm.

**Comment by jdm** [comment]
I have a branch which adds a compile-time feature to enable this.

**Comment by jdm** [comment]
This is supported with the [dom-backtrace](https://github.com/servo/servo/blob/72971bd2716a7e574a4c6c3395c7a710652427b4/servobuild.example#L35) compile-time feature.
