### ISSUE TITLE
Add a flag to run command to enable software rendering

### ISSUE THREAD

**Issue by jdm** [servo/servo#14982]
We have some python code that sets up environment variables for running tests using software rendering: https://dxr.mozilla.org/servo/rev/eb72c0ec7bc1e3547aa09fbe2ad800310f42989b/python/servo/command_base.py#227-245 . We should add a `--software` flag to the [run](https://dxr.mozilla.org/servo/rev/eb72c0ec7bc1e3547aa09fbe2ad800310f42989b/python/servo/post_build_commands.py#42) command to make it easy to run Servo outside of tests using the same setup.

Code: `python/servo/post_build_commands.py`

There's no way to add automated tests for this, so manually verifying that the new flag works should be enough.

**Comment by mdevlamynck** [comment]
I'll do it.

**Comment by Wafflespeanut** [comment]
Glad to hear! :)

**Comment by mdevlamynck** [comment]
@jdm do you have a suggestion as to how to make sure servo is launched in software rendering mode ?

I've come up with theese changes (https://github.com/mdevlamynck/servo/commit/091927be4025f746c25cea9e0d93b8d41b80f79c) but to be honest I have no idea if this actually works or not.

**Comment by jdm** [comment]
@glennw Any idea about the previous question?

**Comment by mdevlamynck** [comment]
@jdm Actually, doesn't the --headless flag already provide the feature you're asking for ?

**Comment by Wafflespeanut** [comment]
Nope. That runs servo in headless mode (in addition to setting the software rendering).

**Comment by glennw** [comment]
This piece of code (https://github.com/servo/servo/blob/master/ports/glutin/window.rs#L262) prints out the GL version, renderer and vendor when running in headless mode.

We use this for debugging logs on CI machines. You could remove the if {} statement and always print this information temporarily. This will allow you to see if a hardware or software renderer is being created.

**Comment by mdevlamynck** [comment]
I did and it doesn't.

I have the feeling the ```GALLIUM_DRIVER=softpipe``` env var is only used when servo is running with osmesa (which is only used in headless mode). And it only occurred to me today that osmesa means offscreen mesa (if I'm not mistaken), which is an other way of saying headless, right ? Hence my previous question about the --headless flag.

**Comment by jdm** [comment]
@mdevlamynck That's a good point! I discussed this more with glennw, and my original description of the steps required did confuse headless and software rendering. On Linux we can get software rendering by setting LIBGL_ALWAYS_SOFTWARE=1 when running Servo; I haven't been able to find such clear instructions for enabling software rendering on other platforms yet. Why don't we start by making this work on Linux, and throw an exception for unsupported platforms?
