### ISSUE TITLE
Error with Android packaging

### ISSUE THREAD

**Issue by rzambre** [servo/servo#15000]
Following the Building for Android wiki, cross-compilation for Android on Ubuntu works well! But I'm running into this error in the last step while packaging.

>-dex:
      [dex] input: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/classes
      [dex] input: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/libs/blurdroid.jar
      [dex] Pre-Dexing /home/rzambre/servo/target/arm-linux-androideabi/release/apk/libs/blurdroid.jar -> blurdroid-e27f87b4d408b895c82cedb8547b3381.jar
       [dx] 
       [dx] PARSE ERROR:
       [dx] unsupported class file version 52.0
       [dx] ...while parsing hu/uszeged/bluetooth/BluetoothAdapterWrapper.class
       [dx] 1 error; aborting
BUILD FAILED
/home/rzambre/Android/Sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:283: null returned: 1
Total time: 1 second
Error while executing program `ant`, or missing program.
Packaging Android exited with return value 1

I made sure I have ```ant``` installed on the machine. And this is my first try at compiling for Android so I'm not inclined to try the silly solution at #13007. Here's the whole blurb:

> rzambre@rzambre:~/servo$ ./mach package --release --android
Cleaning up from previous packaging
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/rzambre/servo/target/debug/build-apk  -o /home/rzambre/servo/target/arm-linux-androideabi/release/servo.apk -t /home/rzambre/servo/target/arm-linux-androideabi/release -r /home/rzambre/servo`
Copying the file "/home/rzambre/servo/target/arm-linux-androideabi/release/libservo.so" to "/home/rzambre/servo/target/arm-linux-androideabi/release/apk/jni/armeabi/libmain.so"
rm -f ./libs/arm64-v8a/lib*.so ./libs/armeabi/lib*.so ./libs/armeabi-v7a/lib*.so ./libs/mips/lib*.so ./libs/mips64/lib*.so ./libs/x86/lib*.so ./libs/x86_64/lib*.so
rm -f ./libs/arm64-v8a/gdbserver ./libs/armeabi/gdbserver ./libs/armeabi-v7a/gdbserver ./libs/mips/gdbserver ./libs/mips64/gdbserver ./libs/x86/gdbserver ./libs/x86_64/gdbserver
rm -f ./libs/arm64-v8a/gdb.setup ./libs/armeabi/gdb.setup ./libs/armeabi-v7a/gdb.setup ./libs/mips/gdb.setup ./libs/mips64/gdb.setup ./libs/x86/gdb.setup ./libs/x86_64/gdb.setup
[armeabi] Prebuilt       : libmain.so <= jni/armeabi/
cp -f jni/armeabi/libmain.so obj/local/armeabi/libmain.so
[armeabi] Install        : libmain.so => libs/armeabi/libmain.so
install -p ./obj/local/armeabi/libmain.so ./libs/armeabi/libmain.so
/home/rzambre/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --strip-unneeded  ./libs/armeabi/libmain.so
Copying the file "libc++_shared.so" to "/home/rzambre/servo/target/arm-linux-androideabi/release/apk/libs/armeabi/libc++_shared.so"
Updated and renamed default.properties to project.properties
Updated local.properties
Updated file ./build.xml
Added file ./proguard-project.txt
Buildfile: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/build.xml
-set-mode-check:
-set-release-mode:
-release-obfuscation-check:
     [echo] proguard.config is ${proguard.config}
-pre-build:
-check-env:
 [checkenv] Android SDK Tools Revision 25.2.5
 [checkenv] Installed at /home/rzambre/Android/Sdk
-setup:
     [echo] Project Name: Servo
  [gettype] Project Type: Application
-build-setup:
[getbuildtools] Using latest Build Tools: 25.0.2
     [echo] Resolving Build Target for Servo...
[gettarget] Project Target:   Android 4.3.1
[gettarget] API level:        18
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin
    [mkdir] Created dir: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/res
    [mkdir] Created dir: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/rsObj
    [mkdir] Created dir: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/rsLibs
    [mkdir] Created dir: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/gen
    [mkdir] Created dir: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/classes
    [mkdir] Created dir: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for Servo...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'release'...
   [subant] No sub-builds to iterate on
-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.
-pre-compile:
-compile:
    [javac] Compiling 3 source files to /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] 3 warnings
-post-compile:
-obfuscate:
-dex:
      [dex] input: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/classes
      [dex] input: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/libs/blurdroid.jar
      [dex] Pre-Dexing /home/rzambre/servo/target/arm-linux-androideabi/release/apk/libs/blurdroid.jar -> blurdroid-e27f87b4d408b895c82cedb8547b3381.jar
       [dx] 
       [dx] PARSE ERROR:
       [dx] unsupported class file version 52.0
       [dx] ...while parsing hu/uszeged/bluetooth/BluetoothAdapterWrapper.class
       [dx] 1 error; aborting
BUILD FAILED
/home/rzambre/Android/Sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:283: null returned: 1
Total time: 1 second
Error while executing program `ant`, or missing program.
Packaging Android exited with return value 1

**Comment by rzambre** [comment]
I got past the above error by setting the jdk version to 1.7 instead of 1.8 but now I'm running into this error. From reading up on StackOverflow, it seems like I need to somehow set the build-tool-version to 23.0.3 but, following the wiki, I made sure I used 23.0.3 with ```tools/android```. Any ideas on what I should try out next? 

> -dex:
      [dex] input: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/bin/classes
      [dex] input: /home/rzambre/servo/target/arm-linux-androideabi/release/apk/libs/blurdroid.jar
      [dex] Pre-Dexing /home/rzambre/servo/target/arm-linux-androideabi/release/apk/libs/blurdroid.jar -> blurdroid-e27f87b4d408b895c82cedb8547b3381.jar
       [dx] Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
       [dx] 	at java.lang.ClassLoader.defineClass1(Native Method)
       [dx] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
       [dx] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       [dx] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
       [dx] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
       [dx] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
       [dx] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
       [dx] 	at java.security.AccessController.doPrivileged(Native Method)
       [dx] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
       [dx] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
       [dx] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
       [dx] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
       [dx] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
BUILD FAILED
/home/rzambre/Android/Sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/home/rzambre/Android/Sdk/tools/ant/build.xml:283: null returned: 1
Total time: 1 second
Error while executing program `ant`, or missing program.
Packaging Android exited with return value 1

**Comment by jdm** [comment]
cc @mmatyas @dati91

**Comment by dati91** [comment]
check this https://github.com/servo/servo/issues/13154#issuecomment-256931616

"[dx] Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0"
these lines mean you probably compiling with java 8 or above

**Comment by rzambre** [comment]
Thanks @dati91 ! I modified the local.properties file under release/apk/ to include ```sdk.buildtools=23.0.3``` but it seemed like that file was being regenerated when I call ```./mach package```. So I ended up just deleting the 25.0.2 folder under Android/Sdk/build-tools which I believe forced ant to use 23.0.3 and that worked :) the solution is to use Java 7 and force ant to use sdk build-tools version 23.0.3 for packaging.
