### ISSUE TITLE
Fix computation of {align,justify}-{content,items,self} (and add parsing / serialization if necessary)

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15001]
It seems there are relatively complicated rules for computed value of those 6 properties, and currently Stylo's result of them seems to be mostly wrong.

Please see Gecko's [test_align_justify_computed_values.html](https://dxr.mozilla.org/mozilla-central/rev/048240a074e841c425a4da4707cf8e353074ec1d/layout/style/test/test_align_justify_computed_values.html) as a reference.

**Comment by upsuper** [comment]
It seems some of the properties are either not implemented (`justify-{items,self}`), or not implemented for geckolib (`justify-content` and `align-content`).

**Comment by mbrubeck** [comment]
With the latest pull requests, all these properties are supported in Stylo but some are still not supported or only partially-supported in Servo.

In Stylo they are now representated by bitflags that are shared with Gecko.  If we want to use the same representation in Servo, we'll need to change the way these bitflags are implemented to not depend on Gecko bindings.

**Comment by upsuper** [comment]
@mbrubeck Although parsing and serialization are implemented, it still lacks gecko glue, and thus gecko still cannot get the computed result of these properties.

**Comment by nox** [comment]
Could you describe a bit more what is there to do, in which files, with what code?

**Comment by nox** [comment]
I took care of what remained, I think.
