### ISSUE TITLE
Attribute selector should treat values of some attributes as case-insensitive

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15006]
See [Case-sensitivity of selectors secion in the HTML spec](https://html.spec.whatwg.org/multipage/scripting.html#case-sensitivity-of-selectors), values of some attributes need to be treated as case-insensitive when applying attribute selector.

Servo currently doesn't match this requirement.

**Comment by Ms2ger** [comment]
Do we have tests?

**Comment by upsuper** [comment]
Gecko has a preliminary test for this: https://dxr.mozilla.org/mozilla-central/source/layout/style/test/test_bug357614.html

But I think it's worth writing a more complete one in wpt.

**Comment by upsuper** [comment]
It seems to have been fixed by #16915.
