### ISSUE TITLE
Move tidy's `BLOCKED_PACKAGES` list to its config

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#15014]
It was added in #14351, but it should be in `servo-tidy.toml` along with the other configurable things.

Code: `python/tidy/servo_tidy/tidy.py`

**Comment by mdevlamynck** [comment]
Hi, I'm interested in working on this, seems easy enough for a first contribution.

**Comment by Wafflespeanut** [comment]
Oh, please go ahead! :)
