### ISSUE TITLE
Implement WebIDL record types

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15012]
https://heycam.github.io/webidl/#record-type

This is the new MozMap. See also <https://bugzilla.mozilla.org/show_bug.cgi?id=1330699>. We might want to hold off until the Gecko folks write tests for us.

**Comment by nox** [comment]
This was implemented, AFAICT (`Headers.webidl` makes use of it).

**Comment by jdm** [comment]
No, that relies on the old mozmap implementation under the hood (and this is a reason I argued against this change!)

**Comment by nox** [comment]
Oh I see.

**Comment by saschanaz** [comment]
#22557 replaced MozMap with IndexMap, what remaining actionable items are here?

**Comment by jdm** [comment]
More or less all of #20318.
