### ISSUE TITLE
Network errors on page loads don't show any error page

### ISSUE THREAD

**Issue by jdm** [servo/servo#15017]
Consider the behaviour of `./mach run http://aowiejfoiawjef -d` - you get a grey screen, followed by a layout panic whenever you try to quit the browser. This occurs because `ParserContext::process_response` calls `ScriptThread::page_headers_available`, which sees that there's no metadata available and therefore doesn't call `ScriptThread::load`. This means that no parser is created when `ParserContext::process_response` returns early, so when `ParserContext::process_response_eof` is called it returns immediately rather than showing a network error.

**Comment by simartin** [comment]
I'll try to take a stab at this one

**Comment by jdm** [comment]
Great! Ask questions about anything that's unclear :)
