### ISSUE TITLE
Cannot click on anything 

### ISSUE THREAD

**Issue by blasrodri** [servo/servo#15015]
I tried downloading Servo on the website, for Mac OS. 
Every time I try to click anywhere inside the Window, I get no response.

System 
Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz

**Comment by berliner** [comment]
Same here:
macOS 10.12.2 (16C67)

**Comment by paulrouget** [comment]
I confirm. Seems to be browserhtml specific.

Looking at it.

**Comment by paulrouget** [comment]
Regression caused by #14291

**Comment by paulrouget** [comment]
This happens with or without browserhtml, at least on github.com.
We can't click on forms or links.

/cc @fiji-flo @pcwalton

**Comment by emilio** [comment]
I find surprising that no test caught this. huh.

I think I know why that is, we're translating the point multiple times in the presence of multiple stacking contexts (not necessarily nested) while hit testing.

**Comment by fiji-flo** [comment]
Indeed. That's a mistake I made when I was trying to deduplicate some shared code. So making the translated point mutable not good. I'll take care of this. I'm really sorry for causing this regression.

**Comment by emilio** [comment]
Oh, sorry, I already published https://github.com/servo/servo/pull/15047. Can be polished quite a lot (I'm on exams so I haven't had the time to do so). Feel free to do it if you want, or grab my commit and improve on it.

**Comment by fiji-flo** [comment]
Yeah, I'm already compiling my fix. I'll try to have something polished. Thanks a lot.
