### ISSUE TITLE
Bump to hyper 0.10

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#15010]
Blocked on #14203 

This removes the dependency on openssl and cookie

**Comment by fflorent** [comment]
May I take the issue if that's not too hard?

Florent

**Comment by jdm** [comment]
#14203 needs to be accomplished first, and @avadacatavra is working on that at the moment.

**Comment by avadacatavra** [comment]
@jdm per our conversation yesterday, I'm now bumping this independently of #15329

**Comment by avadacatavra** [comment]
...but this is blocked on #15325 

hyper_serde needs a bump to hyper 0.10, but current version uses serde 0.9. we need to update the serde dependencies first. @nox says this is happening Pretty Soon (TM)

**Comment by avadacatavra** [comment]
i've bumped locally to cookie 0.4 and hyper 0.10. the newest version of cookie is 0.6, but that's blocked on https://github.com/nox/hyper_serde/issues/16.

@jdm thoughts? should i do cookie 0.4/hyper 0.10 then follow up with another cookie bump?

**Comment by nox** [comment]
Let's fix this for cookie 0.6, especially now I already published hyper_serde with it.

**Comment by nox** [comment]
@avadacatavra Not sure what we did yesterday evening but I can't reproduce your issue.

**Comment by nox** [comment]
Ok, can reproduce now.

**Comment by nox** [comment]
```
Cargo.lock:1677: "hyper_serde 0.6.0 (git+https://github.com/avadacatavra/hyper_serde.git?branch=hyper-bump)",
```

**Comment by nox** [comment]
I managed to fix the issue you add, but now I discovered that rustc-serialize has been absolutely broken in cookie.

I filed a couple of PRs to fix that problem:

 * https://github.com/rust-lang-deprecated/time/pull/144
 * https://github.com/alexcrichton/cookie-rs/pull/79

**Comment by jdm** [comment]
This happened.
