### ISSUE TITLE
`font-variant` should be a shorthand of many font variant properties

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15034]
Per spec there are lots of font variant properties: https://drafts.csswg.org/css-fonts-3/#propdef-font-variant and `font-variant` is a longhand for them.

Note that `font` property should only accept the font variant accepted by CSS 2.x, so anything newly defined in CSS Fonts Module Level 3 should not get parsed when parsing the `font` shorthand.

**Comment by nox** [comment]
`font-variant` is a shorthand now.
