### ISSUE TITLE
Segmentation fault with hyperlink.

### ISSUE THREAD

**Issue by sammykim** [servo/servo#1503]
I guess it is surface release problem. When I press other link slow and continuously , it's usually fine. But I press it more quickly, it shows me segmentation fault.

The more informations are below link you can find about test case, backtrace.

https://gist.github.com/sammykim/8448346

**Comment by frewsxcv** [comment]
I just tried to replicate this with the latest Servo but was unsuccessful.

![untitled2](https://cloud.githubusercontent.com/assets/416575/7338924/d8c4695c-ec29-11e4-96cc-56cfc4696786.gif)

*...and they told me those years of playing Mario Party were wasteful....*
