### ISSUE TITLE
`font` shorthand should reset `font-size-adjust`, `font-kerning`, `font-language-override` etc. even if those longhands cannot be set via the longhand

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15033]
Per spec, many of other longhand font properties need to be reset when setting `font` shorthand.

See https://drafts.csswg.org/css-fonts-3/#propdef-font

**Comment by dbaron** [comment]
I'll have a try at working on this.

**Comment by upsuper** [comment]
The relevant code of shorthand `font` property is https://github.com/servo/servo/blob/master/components/style/properties/shorthand/font.mako.rs and the longhands are in https://github.com/servo/servo/blob/master/components/style/properties/longhand/font.mako.rs

**Comment by dbaron** [comment]
Yeah, I got that far already, along with figuring out the right Mako/Python syntax to add new shorthands conditionally on product == "gecko".  Still need to confirm whether what I'm setting them to is right... probably Monday.
