### ISSUE TITLE
`font` shorthand should be serialized to empty when some of its subproperties have non-default value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15036]
There are many subproperties of `font` shorthand which cannot present in `font` shorthand (see #15033). When any of those properties have non-default value, `font` shorthand should be serialized to empty string.

**Comment by jdm** [comment]
@zploskey What about this one? It requires modifying the implementation of `to_css_declared` in `components/style/properties/shorthand/font.mako.rs` to check if the longhand properties from #15033 are non-default values and change the serialization behaviour in that case. This will require a unit test in `tests/unit/style/properties/serialization.rs` which can be run with `./mach test-unit -p style`.

**Comment by zploskey** [comment]
@jdm That sounds doable. I'll get started. Thanks!

**Comment by zploskey** [comment]
I've written a test and enabled the commented out test for the font module that was already there, with a couple of changes. I think I've made the changes necessary to resolve this issue, but when I run `mach test-unit -p style` none of the code that is enabled for specific products in the mako template seems to be built or executed. I actually just put a panic in one of the product-specific parts and it never ran. I thought all products were supposed to be enabled in test? Are they not for some reason? Anyone else have this issue?

The tests won't be able to pass until I figure out why this is happening. Once I get that part sorted out I'll make any necessary refinements and send a pull request.

**Comment by jdm** [comment]
@Manishearth Any idea what's going on?

**Comment by Manishearth** [comment]
The `% if product == "gecko":` will not work in testing mode. I don't think there's a way around this.

Properties defined for specific products are enabled in tests. The conditional ifs are not.

**Comment by zploskey** [comment]
I guess I need to come up with an appropriate way to check if a struct has a field or not. Open to suggestions. I had been using `% if product == "gecko"`, etc.

**Comment by Manishearth** [comment]
No, you should use if product == gecko. It just means that your tests won't be able to cover that code perfectly. We have tests in gecko for this (but they're harder to run right now)

**Comment by zploskey** [comment]
In that case, I'm not sure how to test this issue at all, but I'll go ahead and open a work-in-progress pull request and let you have a look.

**Comment by Manishearth** [comment]
Sure. I might try to make the shorthand code more testable later.
