### ISSUE TITLE
Declaration must be ignored if it includes CSS-wide keyword as part, but not whole, of it

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15054]
For example the following code:
```html
<!DOCTYPE html>
<p style="font-family: test, initial"></p>
<script>
alert(document.querySelector('p').style.fontFamily);
</script>
```

The declaration of `font-family` must be dropped because [the CSS-wide keyword `initial` is not a valid `<custom-ident>`](https://drafts.csswg.org/css-values-3/#custom-idents).

There are also examples that CSS-wide keywords is accepted as something other than `<custom-ident>`:
```html
<!DOCTYPE html>
<p style="transform-origin: 11% 11% initial"></p>
<script>
alert(document.querySelector('p').style.transformOrigin);
</script>
```

In the example above, the `initial` value should not be accepted at all given the grammar.

**Comment by upsuper** [comment]
This seems to be a fundamental issue in CSS parser of Servo.

@SimonSapin could you have a look at this issue?

**Comment by SimonSapin** [comment]
#15183 fixes the font-family case. (Note though that the definition of `font-family` does not refer to `<custom-ident>`, it excludes some keywords explicitly.)

With a quick look at the parsing code for `transform-origin` I don’t understand how this can happen. I’ll look some more. But I don’t think this is "fundamental", for example `style.marginTop` is the empty string with `margin-top: 4px inital`.
