### ISSUE TITLE
font-family parsing-serialization is not idempotent with quotes

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15059]
See the following code:
```html
<!DOCTYPE html>
<p style='font-family: \"times new roman'></p>
<script>
alert(document.querySelector('p').style.fontFamily);
</script>
```

It shows `"times new roman` which is a different value from `\"times new roman`.

**Comment by upsuper** [comment]
In addition, values like `\035 simple` (which is valid) would be serialized (or parsed) to `5simple` (which is invalid since identifier cannot start with number), which is wrong.

**Comment by upsuper** [comment]
This seems to be an issue probably need to fix in the css parser in conjuction with font-family parsing code. I suspect this may need some deeper change in the parser, though I'm not completely sure.

cc @SimonSapin

**Comment by upsuper** [comment]
Some additional cases:
* `simple\02cinitial` should not be serialized to `simple,initial`
* `simple, \02cinitial` should not be serialized to `simple, ,initial`
* `\@simple` should not be serialized to `@simple`

We probably want to migrate Gecko's [test_font_family_parsing.html](https://dxr.mozilla.org/mozilla-central/source/layout/style/test/test_font_family_parsing.html) to wpt.

**Comment by SimonSapin** [comment]
I think this is because the serializer for `FontFamily` fails to use CSS escaping. I’m preparing a fix.

**Comment by SimonSapin** [comment]
I think this is correct, but it still needs tests.

```diff
diff --git a/components/style/properties/longhand/font.mako.rs b/components/style/properties/longhand/font.mako.rs
index fed23f1..013b6be 100644
--- a/components/style/properties/longhand/font.mako.rs
+++ b/components/style/properties/longhand/font.mako.rs
@@ -19,7 +19,8 @@
     impl NoViewportPercentage for SpecifiedValue {}
 
     pub mod computed_value {
-        use std::fmt;
+        use cssparser::CssStringWriter;
+        use std::fmt::{self, Write};
         use Atom;
         use style_traits::ToCss;
         pub use self::FontFamily as SingleComputedValue;
@@ -72,7 +73,16 @@
 
         impl ToCss for FontFamily {
             fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
-                self.atom().with_str(|s| dest.write_str(s))
+                match *self {
+                    FontFamily::FamilyName(ref name) => {
+                        dest.write_char('"')?;
+                        write!(CssStringWriter::new(dest), "{}", name)?;
+                        dest.write_char('"')
+                    }
+
+                    // All generic values accepted by the parser are known to not require escaping.
+                    FontFamily::Generic(ref name) => write!(dest, "{}", name),
+                }
             }
         }

**Comment by upsuper** [comment]
To test this, you can run `./mach mochitest --disable-e10s layout/style/test/test_font_family_parsing.html` with a stylo build, and see if there is still any failure.

**Comment by upsuper** [comment]
Note that in some cases, the failure may not really make much sense, e.g. `\"times new roman` and `'"times new roman'` seems to be identical, so it doesn't matter if we serialize one to the other.
