### ISSUE TITLE
Avoid include! in generated DOM bindings

### ISSUE THREAD

**Issue by jdm** [servo/servo#15052]
It works fine on mac, but on Windows and Linux it messes with the debug symbols so any line from the included file is mapped to the actual `include!`. This makes stepping through the generated DOM bindings glue impossible on non-mac platforms.

**Comment by jdm** [comment]
The problem here seems to be that we need to make use of code that is generated in the target directory we can only reach via the OUT_DIR environment variable :(

**Comment by SimonSapin** [comment]
This sounds like a compiler bug (though we can still do this work around until that bug is fixed). Have you filed it on rust-lang/rust?

**Comment by jdm** [comment]
That's #36382.

**Comment by jdm** [comment]
It seems like building with `-Z debug-macros` could be a workaround here.

**Comment by nox** [comment]
The Rust issue was fixed, so debug symbols shouldn't be wrongly reported anymore. Closing this.
