### ISSUE TITLE
Check newly written tests with the WPT / CSSWG linter.

### ISSUE THREAD

**Issue by emilio** [servo/servo#15057]
Spawn off from https://github.com/servo/servo/pull/14989#issuecomment-272987822, we should probably check that our tests pass the standard lints that WPT (or CSSWG at least) have.

See for example: https://github.com/w3c/csswg-test/pull/1155#issuecomment-262580941

What do you think @jdm @Ms2ger @jgraham?

@Wafflespeanut would you be interested in integrating it with tidy?

**Comment by frivoal** [comment]
CCing @gsnedders, the CSSWG's resident test guru.

**Comment by jdm** [comment]
We already integrate the WPT linter. I think there's some belief that the requirements of the CSSWG testsuite are more effort than they're worth in terms of upstreaming.

**Comment by gsnedders** [comment]
Given @jdm's comment, the CSS side of this will be resolved when #16175 is fixed.

**Comment by jdm** [comment]
All done!
