### ISSUE TITLE
Support shorthand property "all"

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15055]
`all` is a shorthand property defined in [css-cascade spec](https://drafts.csswg.org/css-cascade-3/#all-shorthand) to set almost all of properties at the same time to a given CSS-wide keyword. So it is mainly a style system thing, which doesn't require any layout support.

**Comment by SimonSapin** [comment]
The naive way to implement this would be literally as described: expand it at parse time to hundreds of longhand declarations and cascade all of these.

But that sounds expensive, and it’s probably possible to be smarter about it. What does Gecko do?

----

Note:

https://drafts.csswg.org/css-variables/#defining-variables
> Custom properties are **not** reset by the all property.

**Comment by emilio** [comment]
If we see the `all` property it seems we could do the following:

 * If the value is `inherit`, drop all our computed styles right now, and just clone the parent one, which is easy (except we need to `unicode-bidi` and direction if they were specified).
 * If the value is `initial`, do the same, just cloning from the default computed values instead.
 * If the value is `unset`, clone individual structs as needed from either the default computed values or the inherited values depending on whether it's a reset or an inherited struct.

**Comment by SimonSapin** [comment]
> If we see 

There’s two separate phases: parsing, which is when other shorthands are expanded into their longhands, and cascading. So far, longhand declarations expanded from the same shorthand declaration casacde separately. But maybe we can treat `all` differently and have an `All` variant in the `PropertyDeclaration` enum? (Which so far only contains longhands and custom properties.)

**Comment by emilio** [comment]
Yeah, that looks reasonable to me, and it's what I had assumed when writing my comment above.
