### ISSUE TITLE
Is components/servo dependency on browserhtml necessary?

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#15066]
Is https://github.com/servo/servo/blob/363f590019e495fffab0cc0fa0464e05d2fc96e8/components/servo/Cargo.toml#L27 necessary?

I would imagine that https://github.com/servo/servo/blob/363f590019e495fffab0cc0fa0464e05d2fc96e8/ports/servo/Cargo.toml#L40 is enough.

**Comment by Ms2ger** [comment]
I hope you're right; want to try removing it and checking if b.html still works as intended?
