### ISSUE TITLE
Reduce unnecessary allocations in parse_property_declaration_list

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15060]
`parse_property_declaration_list` has some allocator churn

[The function](﻿https://github.com/servo/servo/blob/a4551d0ceea8f2aceb68775452ea3010760f2825/components/style/properties/declaration_block.rs#L556-L578) works by iterating through the parsed declarations.

However, each iteration produces a `Vec<(PropertyDecl, Importance)>`, which is read from an immediately destroyed. These are of length 1 when dealing with longhands

We should be reducing this. There are many ways of doing so:

 - Make the `PropertyDeclarationParser` parser append to an internal vector, and iteration only yields a `Result</* importance count */ u32,  ErrorType>`
 - Use a 1-element SmallVec for [`<PropertyDeclarationParser as DeclarationParser>::Declaration`](https://github.com/servo/servo/blob/a4551d0ceea8f2aceb68775452ea3010760f2825/components/style/properties/declaration_block.rs#L531). Or some other SmallVec.
 - Restructure the iterator so that it can yield one property declaration at a time. Sounds hard and unnecessary

Any opinions on what we should do here? I like the first option.

cc @SimonSapin

**Comment by SimonSapin** [comment]
I’ve been meaning to try the first option. It probably involves adding a `&'a mut Vec<PropertyDeclaration>` field to `struct PropertyDeclarationParser<'a, 'b: 'a> { … }` in `declaration_block.rs`.

**Comment by Manishearth** [comment]
Ugh, there's a problem here. `parse_property_declaration_list` creates a `Vec<(PropertyDeclaration, Importance)>`, whereas `PD::parse` operates on an `&mut Vec<PropertyDeclaration>`.

We cannot make `PD::parse` generic because of its codesize impact.

I will make `PD::parse` it operate on a `&mut Vec<(PD, Importance)>` with the statement that it doesn't set the importance. Aside from here it's only used in keyframes (which eventually output to a PDB anyway so they can reuse this) and supports (which doesn't care).
