### ISSUE TITLE
column-{gap,width} doesn't recognize keyword values

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15088]
See the following code:
```html
<!DOCTYPE html>
<div id="test" style="column-gap: 2px;
                      column-gap: normal;
                      column-width: 4px;
                      column-width: auto;">
</div>
<script>
alert(test.style.columnGap);
alert(test.style.columnWidth);
</script>
```

In Gecko and Blink, it shows `normal` and `auto` correspondingly, while in Stylo (and presumably Servo as well), it shows `2px` and `4px` which indicates that the keyword values are treated as invalid and ignored.

I think the reason is that in "longhand/column.mako.rs", the definition of these two properties have `parse_method='parse_non_negative_length'` specified, which makes them only parse length value.

**Comment by Manishearth** [comment]
Yep, they're implemented as predefined types; and will need to be converted to full enum-like impls.
