### ISSUE TITLE
Keyword values of timing function should not be computed to bezier function

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15086]
Per [spec](https://drafts.csswg.org/css-transitions-1/#single-transition-timing-function), the computed value of timing function is same as specified value, and in both Gecko and Blink, the keyword values are perserved in computed value.

Test the following code:
```html
<!DOCTYPE html>
<div id="x"></div>
<script>
alert(getComputedStyle(x).animationTimingFunction);
x.style.animationTimingFunction = 'ease';
alert(getComputedStyle(x).animationTimingFunction);
</script>
```

In Gecko and Blink, both alerts show `ease`, while in Stylo, the first shows `ease` while the second shows `cubic-bezier(0.25, 0.1, 0.25, 1)`, which is incorrect.

cc @hiikezoe

**Comment by hiikezoe** [comment]
Yes, I've noticed this.  In my understandings, to resolve this we should pass the specified value to set_animation_timing_function() instead of computed one.  I guess we need to fix cascade_property() in helpers.mako.rs?  Or computed_value for transition_timing_function should have specified value.

**Comment by upsuper** [comment]
I guess for this value we don't need to distinguish computed value from specified value at all. They should simply have the same type.
