### ISSUE TITLE
Handle moz://a

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#15109]
Maybe show a doge picture or something :)

**Comment by SimonSapin** [comment]
If we do this, I think we should also do [about:unicorn](https://github.com/servo/servo/pull/8808).

**Comment by KiChjang** [comment]
Unfortunately, about:unicorn has been officially removed from the Fetch spec...

**Comment by Ms2ger** [comment]
We should do neither.

**Comment by nox** [comment]
Let's close this, it's not like we are going to forget that we can do something fun at this URL if we ever feel like it, but this should probably be something in a frontend app, not in Servo itself.
