### ISSUE TITLE
Windows downloadable font support may need some fleshing out

### ISSUE THREAD

**Issue by vvuk** [servo/servo#15103]
Windows downloadable font support added in #15096 has some limitations around the family/face name that may or may not need to be fixed.  Specifically, it only pulls out Mac-format (`platform_id == 1`) English names from the font container.  I'm not sure if the font family/face is relevant at all for downloaded fonts, though, because I believe the family name has to be specified in the `@font-face` rule anyway.

**Comment by codec-abc** [comment]
Leaving this as a note: People fixing this issue may want to see history of #15255 and #16078.

**Comment by mrobinson** [comment]
We no longer get font family names from fonts in platform-specific `Font` code after #32115.
