### ISSUE TITLE
Audit the truetype crate.

### ISSUE THREAD

**Issue by emilio** [servo/servo#15105]
I just took a quick look, what I saw looks reasonable and I opened https://github.com/bodoni/truetype/issues/5 to see the thoughts of the author.

This is just for tracking it, given it's a relatively exposed crate.

cc @vvuk

**Comment by vvuk** [comment]
Note that we need a very, very tiny part of TT parsing for the Windows code.  If there's any concern, it shouldn't be too much of a problem to implement just that bit.

**Comment by emilio** [comment]
Yeah, right, I was only following standard procedures we should be following for every dependency, sorry if it's too much noise.

**Comment by emilio** [comment]
We're only parsing font tables, and truetype seems to do the work quite well, I think.
