### ISSUE TITLE
Convert some low-interest debug! logging into trace!

### ISSUE THREAD

**Issue by jdm** [servo/servo#15100]
We have some uses of `debug!(...)` in the code that are rarely actually useful. They also occur _very_ frequently, and make the output of `RUST_LOG=debug` really difficult to read.

https://dxr.mozilla.org/servo/rev/1755ad7b75e056a534e12f375a6677f5c069f4c2/components/script/dom/bindings/conversions.rs#383-403
https://dxr.mozilla.org/servo/rev/1755ad7b75e056a534e12f375a6677f5c069f4c2/components/script/dom/bindings/conversions.rs#356-365
Every use in https://dxr.mozilla.org/servo/source/components/script/dom/bindings/trace.rs
https://dxr.mozilla.org/servo/rev/1755ad7b75e056a534e12f375a6677f5c069f4c2/components/script/dom/bindings/weakref.rs#58-68
Every use in https://dxr.mozilla.org/servo/source/components/remutex/lib.rs
Every use in https://dxr.mozilla.org/servo/source/components/rand/lib.rs

**Comment by DexterHaslem** [comment]
I'd like to work on this

**Comment by jdm** [comment]
Great! Ask questions here if anything is unclear!
