### ISSUE TITLE
Gray screen and GL error on ARM Linux

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#15110]
At the moment, running Servo on ARM Linux stops with a

```
gl function was not loaded (thread main, at /home/mmatyas/Servo/servo-arm/servo/target/arm-unknown-linux-gnueabihf/release/build/gleam-6ea7035333831341/out/gl_bindings.rs:11381)
ERROR:servo: gl function was not loaded
```

error on launch (tested on Odroid XU3). This can be fixed by updating `webrender` to the latest version (probably fixed by a `glutin` update there), however, Servo only produces a gray screen after that.

![50shadesofgray](https://cloud.githubusercontent.com/assets/4354863/22108105/c81d4aee-de51-11e6-91e2-5cb7d6f75934.png)

If I resize the window, it turns black.

The page seems to load correctly; if I move the mouse around, the cursor changes shape depending on the underlying page content.

cc @kvark @glennw

**Comment by glennw** [comment]
@mmatyas There is a breaking API change in the latest WR code - I'm working on updating Servo to handle this now. The grey screen is what I'd expect to see, until this API change is updated.

**Comment by mmatyas** [comment]
Ah ok, thanks for the update!

**Comment by glennw** [comment]
Update PR is here https://github.com/servo/servo/pull/15111#issuecomment-273783256 - but we need to get these other core graphics dependencies updated before it can land. You can pull this PR locally though to confirm it fixes your grey screen, if you like.

**Comment by mmatyas** [comment]
Using you patch, Servo throws a `ERROR:servo: gl function was not loaded` :(

**Comment by glennw** [comment]
If you run with RUST_BACKTRACE=1 it should show which GL function is not being loaded in the stack trace.

**Comment by mmatyas** [comment]
It seems the missing function is ClearDepth (which sound really familiar to me; haven't we had a problem with it before?). Here's the relevant part of the backtrace:

```
   5: 0xb546b7ff - gleam::ffi::missing_fn_panic
                at /home/mmatyas/Servo/servo-arm/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/gleam-0.2.30/src/lib.rs:16
   6: 0xb506ce1b - gleam::ffi::ClearDepth
                at /home/mmatyas/Servo/servo-arm/servo/target/arm-unknown-linux-gnueabihf/debug/build/gleam-6ea7035333831341/out/gl_bindings.rs:1637
   7: 0xb506b78b - gleam::gl::clear_depth
                at /home/mmatyas/Servo/servo-arm/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/gleam-0.2.30/src/gl.rs:1361
   8: 0xb5087c33 - webrender::device::{{impl}}::clear_target
                at /home/mmatyas/Servo/servo-arm/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/69f5804/webrender/src/device.rs:1862
   9: 0xb50529eb - webrender::renderer::{{impl}}::draw_target
                at /home/mmatyas/Servo/servo-arm/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/69f5804/webrender/src/renderer.rs:1128
  10: 0xb505452f - webrender::renderer::{{impl}}::draw_tile_frame
                at /home/mmatyas/Servo/servo-arm/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/69f5804/webrender/src/renderer.rs:1392
```

**Comment by glennw** [comment]
@mmatyas Hmm, ClearDepth is interesting - since the symbol has an extra 'f' on ES3 (it's glClearDepth on desktop GL, and glClearDepthf on ES3). I wonder if somehow it's building with the desktop bindings in gleam or something like that?

**Comment by mmatyas** [comment]
You're right, it seems there's only an Android check [here](https://github.com/servo/gleam/blob/master/src/gl.rs#L1378), and there's an issue for it too (servo/gleam/issues/103).

**Comment by MTRNord** [comment]
Got that Error on Windows 10 64-bit too with download at the website

**Comment by nox** [comment]
@mmatyas @MTRNord Does it still happen for any of you?

**Comment by MTRNord** [comment]
@nox It seems to work now. Didn't crash and I was able to open Github

**Comment by nox** [comment]
Thanks for the answer! @mmatyas' issue on Android should be fixed by the linked gleam issue, so I'm closing this ticket.
