### ISSUE TITLE
Implement read methods on FileReaderSync

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15114]
Blocks #10778.

* Spec: <https://w3c.github.io/FileAPI/#dfn-FileReaderSync>.
* Code: `components/script/dom/filereadersync.rs`, `components/script/dom/webidls/FileReaderSync.webidl`.
* Tests: `FileAPI/FileReaderSync.worker.html`, `FileAPI/idlharness.worker.html`.

**Comment by DonatJR** [comment]
@Ms2ger Can I have a try at this issue?

**Comment by jdm** [comment]
@DonatJR Go ahead!

**Comment by DonatJR** [comment]
Hey @jdm, I implemented 3 of the 4 methods but `readAsArrayBuffer` is giving me some troubles. Maybe you can help me out?

I'm trying to create an ArrayBuffer with the given blob like this:
``` Rust
let frs = Trusted::new(self).root();
let cx = frs.global().get_cx();

rooted!(in(cx) let mut rooted_buffer = ptr::null_mut());
unsafe {
    assert!(ArrayBuffer::create(cx, CreateWith::Slice(&blob_contents), rooted_buffer.handle_mut()).is_ok());    
}

typedarray!(in(cx) let array_buffer: ArrayBuffer = rooted_buffer.get());
```

The problem with this is that the typedarray! macro creates the ArrayBuffer with a root which does not live long enough and I am not sure how to create it with a correct root / `Rooted`-value.

Compiler error:
error[E0597]: `__root` does not live long enough

(__root is created in the `typedarray!` macro as `$crate::jsapi::Rooted::new_unrooted()`)

**Comment by jdm** [comment]
Which line is the compile error coming from?

**Comment by DonatJR** [comment]
I figured it out. The problem was me not writing the method declarations in the corresponding .webidl file so the correct function definitions could be autogenerated. My implementation actually returned a wrong type and I got it working with the correct return type / function signature. :)
