### ISSUE TITLE
implement white-space

### ISSUE THREAD

**Issue by metajack** [servo/servo#1513]
Needed for #1366.

**Comment by Manishearth** [comment]
We also have `nowrap` now (https://github.com/servo/servo/pull/3458). Close?

**Comment by SimonSapin** [comment]
http://dev.w3.org/csswg/css-text-3/#white-space-collapsing (Same set of values as 2.1)

* [x] normal
* [x] pre
* [x] nowrap
* [ ] pre-wrap
* [ ] pre-line
