### ISSUE TITLE
We never remove web fonts from the font cache.

### ISSUE THREAD

**Issue by emilio** [servo/servo#15139]
This is not only a leak, but also may produce incorrect styling. Consider the following code:

```html
<style>
@font-face {
    name: foo;
    /* ... */
}
</style>
<style>
div {
    font-family: foo, arial;
}
</style>
<div class="foo">
TEXT
</div>
<script>
let s = document.querySelector('style');
s.parentNode.removeChild(s);
</script>
```

We should render the text in Arial, but as far as I know we'd render it with the `foo` font.

I remember to have seen an issue about the font cache leak, but I couldn't find it, so I'm filling this one.

**Comment by leeoniya** [comment]
https://github.com/servo/servo/issues/12920 ?

**Comment by emilio** [comment]
Nope, more like https://github.com/servo/servo/issues/3300, but thanks for pinging me about it so I looked into it! :)

**Comment by emilio** [comment]
Though https://github.com/servo/servo/issues/12920 is relevant too, I guess. Our font code seems _really_ broken...
