### ISSUE TITLE
runservo.sh missing in nightly builds

### ISSUE THREAD

**Issue by kinclma1** [servo/servo#15135]
In recent nightly linux builds, runservo.sh is missing.

**Comment by KiChjang** [comment]
It has been replaced by `./servo`. Are you able to find it?

**Comment by kinclma1** [comment]
Thank you. Is it possible to change the instructions on https://download.servo.org/ accordingly?

**Comment by aneeshusa** [comment]
@kinclma1, there is a PR open at https://github.com/servo/download.servo.org/pull/13 which should be merged shortly.
