### ISSUE TITLE
OTS sources not found when building fontsan

### ISSUE THREAD

**Issue by sbwtw** [servo/servo#15141]
build failed when i execute ./mach build --dev
outputs:

```
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `fontsan v0.3.2 (https://github.com/servo/fontsan#ab68da17)`
process didn't exit successfully: `/home/Projects/servo/target/debug/build/fontsan-ed5410c3e88b09f8/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/.cargo/git/checkouts/fontsan-75864180be477bc9/ab68da1/src" "-DCMAKE_INSTALL_PREFIX=/home/Projects/servo/target/debug/build/fontsan-58f875ff64dc5050/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Projects/servo/target/debug/build/fontsan-58f875ff64dc5050/out/build

--- stderr
CMake Error at CMakeLists.txt:119 (add_library):
  Cannot find source file:

    ots/third_party/woff2/src/buffer.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: Cannot determine link language for target "woff2".
CMake Error: CMake can not determine linker language for target: woff2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.20/src/lib.rs:573
note: Run with `RUST_BACKTRACE=1` for a backtrace.

[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
```

**Comment by emilio** [comment]
Hi, thanks for reporting!

Could you give more info about which platform are you on?

This is a fontsan build failure, cc @nox

**Comment by nox** [comment]
Seems like `fontsan` was not properly checked out and submodules weren't fetched. Path `/home/.cargo/git/checkouts` is nonstandard. Do you have a custom `.buildservo` in your Servo tree? Did you use `cargo` directly at some point to build Servo?

**Comment by sbwtw** [comment]
hello, I'm using archlinux
`uname -a`
Linux Pandora 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
`rustc -V`
rustc 1.16.0-nightly (a52da95ce 2017-01-20)
`cargo -V`
cargo 0.15.0-dev (298a0127 2016-12-20)
`echo $HOME`
/home

i have modify my home directory to `/home`, (not /home/$USER).
and i check `~/.cargo/git/checkouts/fontsan-75864180be477bc9/ab68da1/src/ots/third_party/woff2` only have a `.git` folder

And I did not change any files after clone servo source code.

**Comment by sbwtw** [comment]
I execute `rm -rf ~/.cargo/git/checkouts/fontsan-75864180be477bc9/` and `./mach clean` and rebuild，every thing back to normal and complie successful.
Thanks..
