### ISSUE TITLE
Scripts from javascript: URLs don't get executed in the right global

### ISSUE THREAD

**Issue by nox** [servo/servo#15147]
They should get executed in the browsing context container's window, not the one that is created for navigation.

**Comment by nox** [comment]
Most remaining `script_scheduling` tests fail for that reason. They try to run `log(...)` in a global where `log` is undefined.

**Comment by saneyuki** [comment]
Is https://github.com/servo/servo/issues/15763  related to this?

**Comment by nox** [comment]
Probably yes.
