### ISSUE TITLE
WPTs for PR #15145 pass, but the harness times out

### ISSUE THREAD

**Issue by SwagColoredKitteh** [servo/servo#15159]
This WPT checks whether, when two stylesheet requests are in-flight for the same element and they arrive in the wrong order, the correct styles will still be applied. The test itself passes with the patches but the harness times out.

```html
<!doctype html>
<meta charset="utf-8">
<title>Out-of-order stylesheet loads for the same element happen correctly (issue #15101)</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<script>
async_test(function(t) {
  var link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = "resources/background-red.css?pipe=trickle(d3)";
  document.head.appendChild(link);
  link.href = "resources/background-green.css";
  t.step_timeout(function() {
    assert_equals(getComputedStyle(document.body).getPropertyValue("background-color"), "rgb(0, 128, 0)");
    t.done();
  }, 4000);
}, "out-of-order stylesheet loads for the same element happen correctly");
</script>
```

cc @jdm

**Comment by jdm** [comment]
My theory here is that the document load event doesn't get dispatched because the first CSS load is never marked complete.

**Comment by SwagColoredKitteh** [comment]
Here's the command to run this WPT: `./mach test-wpt tests/wpt/mozilla/tests/mozilla/out-of-order-stylesheet-loads.html`

**Comment by emilio** [comment]
Yes, this is a problem that should be fixed in #15145 itself IMO.

**Comment by emilio** [comment]
See https://github.com/servo/servo/pull/15145#discussion_r97392281 for an explanation.

**Comment by SwagColoredKitteh** [comment]
This is now fixed.
