### ISSUE TITLE
Serialization of border-radius and -moz-outline-radius shorthand is wrong

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15169]
For example, `border-radius: 1px 2px 3px 4px / 5px 6px 7px 8px` is incorrectly serialized as `border-radius: 1px 5px 2px 6px 3px 7px 4px 8px`.

**Comment by upsuper** [comment]
Note that, this also affects Gecko-only `-moz-outline-radius`, which uses basically the same syntax.

**Comment by jdm** [comment]
```html
<div style="border-radius: 1px 2px 3px 4px / 5px 6px 7px 8px">
<script>console.log(document.querySelector('div').style.borderRadius)</script>
```

**Comment by Aaron-Tang** [comment]
Hi, I intend to work on this issue

**Comment by upsuper** [comment]
Great! Feel free to ask any questions.

**Comment by upsuper** [comment]
In addition to the `/` separator, the serialization should also be condensed to the shortest form when possible, which means `border-radius: 1px 1px 1px 1px / 2px 2px 2px 2px` should be serialized to `border-radius: 1px / 2px`, and `border-radius: 1px 1px 1px 1px / 1px 1px 1px 1px` should be `border-radius: 1px`.

**Comment by jdm** [comment]
@Aaron-Tang have you made progress? Any questions?

**Comment by Aaron-Tang** [comment]
Sorry I haven't been able to sit down and work on it that much, I'll probably get to it this weekend. Quick question however, which part of the code should I be working on? There doesn't seem to be anything linked in the issue.

**Comment by upsuper** [comment]
Relevant code should be https://github.com/servo/servo/blob/master/components/style/properties/shorthand/border.mako.rs#L165-L181

**Comment by Aaron-Tang** [comment]
Um I have a few questions about the linked code; I'm new to rust and I'm trying to understand the code first: 

- What does "fn to_css_declared<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write" do?
- Do border_top_left_radius and the other ones have two fields (as in the example you gave above it seems that border_top_left_radius is equal to both 1px and 5px). 
- If yes how would i access the fields? Is it like accessing an array value (somelist[2] = some_value) or is there a way unique to rust to do this?

**Comment by upsuper** [comment]
* `to_css_declared` serializes the longhand property and write the result into `dest`
* `border_top_left_radius` and others are defined in [longhand/border.mako.rs](https://github.com/servo/servo/blob/b85e1f5f0caad650efe16bfdbadaebff5dcf70fa/components/style/properties/longhand/border.mako.rs#L67-L73), and their type is [`BorderRadiusSize`](https://doc.servo.org/style/values/specified/struct.BorderRadiusSize.html).

**Comment by karan1276** [comment]
.

**Comment by Wafflespeanut** [comment]
@Aaron-Tang ping?

**Comment by Aaron-Tang** [comment]
Sorry I'm still very confused on how to fix this bug. I understand that the issue now is that the to_css function gets both the height and width of the borderradius into the dest object, which is then written using write. I'm trying to figure out how to access the height and width attributes of BorderRadiusSize before this occurs so I can run checks to see if it can be shortened. I can't seem to find a way to do so. I don't think I mentioned before that I'm totally new to rust which is why a lot of this is confusing to me. Any help would be greatly appreciated.

**Comment by Wafflespeanut** [comment]
You don't really need to worry about everything. Let's go through some stuff. We know that the [parsing code](https://dxr.mozilla.org/servo/rev/d8a8e3e42eda3704d8793d398b24f2e37bded4ec/components/style/properties/shorthand/border.mako.rs#189-194) which uses the existing [`BorderRadius`](http://doc.servo.org/style/values/specified/basic_shape/struct.BorderRadius.html) implementation works just fine, but the [serializing code](https://dxr.mozilla.org/servo/rev/d8a8e3e42eda3704d8793d398b24f2e37bded4ec/components/style/properties/shorthand/border.mako.rs#203-212) directly writes these values (separated by spaces, just like the issue says), which is not what we want. The clue lies in the [existing `ToCss` implementation](https://dxr.mozilla.org/servo/rev/d8a8e3e42eda3704d8793d398b24f2e37bded4ec/components/style/values/specified/basic_shape.rs#726-746)  of `BorderRadius`.

**Comment by austinprete** [comment]
@Wafflespeanut is this issue now open for someone else to pick up? (I saw that you removed the assigned label, and the discussion has been stale for a while) If so, I'd like to work on it, though it'd probably be until next weekend before I'd have time to make progress. (Busy school week for me)

**Comment by KiChjang** [comment]
@austinprete Let us know when you start working on it then. In the meantime, this issue is still open!

**Comment by brainlessdeveloper** [comment]
Hello! I would like to work on this issue. I am new to the language: my only experience is a couple small applications that use APIs from services like Slack, Asana and my company's own backends.

I think with the comments on this wall and some effort I'll be able to tackle it, though!

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear!

**Comment by Wafflespeanut** [comment]
Wonderful. I never noticed that this addresses #12655.
