### ISSUE TITLE
`-webkit-text-stroke` shorthand is sensitive to order of value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15165]
The implementation of `-webkit-text-stroke` shorthand is wrong since it is order-sensitive, while it shouldn't, since the syntax is `<line-width> || <color>`.

The fix should be simple: just change the `parse_value` of `-webkit-text-stroke` in "components/style/properties/shorthand/inherited_text.mako.rs" to something similiar to `text-emphasis` shorthand above.

**Comment by DexterHaslem** [comment]
I'd like to work on this issue

**Comment by upsuper** [comment]
Not sure how to mentor... so cc @Manishearth

**Comment by Manishearth** [comment]
Great! The relevant code is in https://github.com/servo/servo/blob/231481570e7ffc6c036b54a15507a9b2260ffe87/components/style/properties/shorthand/inherited_text.mako.rs#L75-L98 , you basically need to use a loop like in text-emphasis (https://github.com/servo/servo/blob/231481570e7ffc6c036b54a15507a9b2260ffe87/components/style/properties/shorthand/inherited_text.mako.rs#L16)
