### ISSUE TITLE
Looking for something to work on?

### ISSUE THREAD

**Issue by jdm** [servo/servo#15162]
This issue will be used to track people who are looking for a task to work on but can't find anything fitting on http://starters.servo.org/.

*For potential contributors:*
Please leave a comment and mention any relevant requirements or previous experience.

*For Servo team members:*
When an appropriate issue has been assigned to someone who left a comment in this issue, please CC them to it and remove the original comment from this issue. This will allow us to track outstanding requests for assistance.

Requests processed: 32

**Comment by Maaarcocr** [comment]
I would like to contribute to Servo! 
I've read the book and worked on a very small, simple and not finished http library with rust (for educational purposes). 
I'm a CS student, based in London.
I don't know if I need to add anything else, I really look forward contribute to something!

**Comment by andrew-x** [comment]
Hi there, I'd like to work on something if anyone has any suggestions for a good easy introductory issue.

I have experience with python and java and limited experience with C/C++. I also have no experience with Rust but certainly don't mind learning it on the fly. Thanks!

**Comment by Seris** [comment]
Hi guys !

I'd like to contribute to Servo ! I have experience with C and Javascript, some basis in Python, PHP and Java.
I have little experience with Rust as I've been playing with it only for the last month, which is the reason I'm here ! I would like to use Rust in a concrete project !

Keep up the good work guys ! 
Thanks !

**Comment by chansuke** [comment]
Hi.I am looking for a task to contribute.I'm new to Rust but have experience with C & Ruby & golang and so on.

**Comment by 1Jamie** [comment]
hey i want to give a hand, do you have anything easy using rust i could give a go at that you could point me towards?

**Comment by bd339** [comment]
I'm looking for something to work on. Worked on a couple of issues and would like something that involves Rust code.

**Comment by charlesvdv** [comment]
@jdm I'm interrested in working on something a bit bigger as I just finished my exams.

**Comment by Wafflespeanut** [comment]
Hi @charlesvdv! How familiar are you with Rust? We have a bunch of issues that may consume 1-2 weeks or something. We also have a list of [student projects](https://github.com/servo/servo/wiki/Student-projects) which you might be interested in.

**Comment by charlesvdv** [comment]
Yes I'm familiar I've already made 2 pulls requests to servo during my exams but now I'm interrested into working on something a bit bigger.

**Comment by clementmiao** [comment]
I'm interested in contributing during my personal time outside of work at Dropbox. Previously, I've had two accepted PRs to rust-lang.

My experience with Rust is beginner, but I have gone through steve klabnik's upcoming rust lang book, and built a couple personal projects with it (hyper, iron mostly).

**Comment by abhiQmar** [comment]
I would like to contribute. Not much experience in rust, but have been a programmer for 2 years.

**Comment by simon-whitehead** [comment]
I would like to contribute. I recently opened and had merged a PR in `rust-mozjs`. I have been writing Rust for about a year now and have written quite a few personal projects in Rust in that year.

RE work to do: There is _alot_ of implied knowledge in most of these issues. I struggle to keep up with some of the conversation. I realise mentoring is a big time sink for the maintainers ... but I think at this point in Servo's life mentoring is one of the only ways to keep more people hooked.

That said, the PR I had merged in `rust-mozjs` was a very painless process so that already hooked me 😃

**Comment by Wafflespeanut** [comment]
FYI (anyone), #14787 hasn't been taken for a while.

**Comment by tmccrmck** [comment]
I would also like to something to work on. I have Rust experience.

**Comment by josephfu1994** [comment]
I am also looking for something to work on. Don't have much rust experience, but have programmed in other languages. Thanks.

**Comment by cseale** [comment]
I am another. Not a huge amount of rust experience, but trying to learn how to build languages, compilers, etc. 5 years experience.

**Comment by UnICorN21** [comment]
I'd like to contribute too. Newbie as a rust programmer, but have programmed in other languages for 3 years

**Comment by singhkaran** [comment]
I'm looking for a bug, as well. No experience with rust so a bug that would help me get my feet wet would be great.

**Comment by emilio** [comment]
If any of you want to take https://github.com/servo/rust-bindgen/issues/519, I'm happy to mentor it :)

It's not going to be servo code per se, though that crate is used in Firefox in order to generate bindings to the C++ part of the engine. It might be interesting if you're into bit-mangling :)

**Comment by cseale** [comment]
@emilio I'd be happy to take it on

**Comment by emilio** [comment]
@cseale awesome! We'll need https://github.com/servo/rust-bindgen/issues/512 to land first, but I can mark it as assigned already.

Thanks! (And wow, that was fast!)

**Comment by cseale** [comment]
@emilio not sure how I'll do at the bit mangling but might be interesting ^_^

**Comment by emilio** [comment]
@cseale Sounds great, just let me know if you need anything! (Let's move this conversation out of this issue though, since it's not the purpose of it, and our comments will be deleted :P)

**Comment by jbg** [comment]
>10 years programming in various languages, have a couple Rust projects under my belt, would like to contribute to this project.

**Comment by samliu** [comment]
I'd be interested in working on some bugs! I'm learning rust but am comfortable with a variety of other environments. My main constraint is time, ideally there is a starter bug that isn't particularly time sensitive.

**Comment by montrivo** [comment]
Hello, 
I'd like to work on a rust issue. Beginning with the language, no previous experience.

**Comment by avinash-vijayaraghavan** [comment]
im looking for something to work on in servo. im new to rust. i have experience with writing a compiler and a small os for an os class. 
avinash

**Comment by barrotsteindev** [comment]
Hello,
I am fairly new to rust and looking for an easy task to improve my skills and give back to the community.
I also have experience programming JavaScript, and would be more than happy to work on js.
Thanks in advance.

**Comment by jdhorwitz** [comment]
I am also looking to get started as well.  I have extensive JS knowledge but I would prefer to contribute to Rust codebase and gain a deeper knowledge of Rust.

**Comment by projektir** [comment]
I'm looking for something to work on. I'm new to Rust and systems development and worked with JS quite a bit.

**Comment by basic-bgnr** [comment]
started using rust since 1 year, did few pet project and nothing else. I like the language and would like to contribute to its growth.

**Comment by fitzgen** [comment]
@basic-bgnr since you have some experience with the language, and want to contribute to its growth in particular, bindgen can be a good project to hack on. It's used lots by Servo as well as by other projects across the Rust ecosystem. Here is an issue that might be a good intro to bindgen for you: https://github.com/servo/rust-bindgen/issues/548

**Comment by alanhoff** [comment]
I have ~6 months exp with Rust and wrote a [simple K/V database](https://github.com/alanhoff/rackety) with it. I would appreciate some help for initiating my contributions to Servo.

**Comment by crypto-universe** [comment]
Hi! I'd like to get some easy task. I already have one contribution, so I know how to build servo.

**Comment by emilio** [comment]
If someone with some previous experience with Servo and/or a lot of willingness to learn wants to try to tacke https://github.com/servo/servo/issues/15806, I can happily mentor it :)

**Comment by sendilkumarn** [comment]
I am also looking to get started as well.

**Comment by abhiaecs** [comment]
Hey,
I am  new to rust and looking for an easy task to improve my skills and get started in contributing to the project.

**Comment by o0Ignition0o** [comment]
Hey there,
I'm pretty new to rust too, have been working for about 3 years mainly dealing with Java, PHP, and Javascript. I'm practicing TDD as much as I can.
Would love to get involved !

**Comment by PhilHernandez** [comment]
Hello,
I'm new to rust, and I'd love to contribute to servo. I'm looking for an easy task to gain experience with contributing to open source projects. I have experience with programming in Python, Java, and Javascript. Looking forward to working on something!

**Comment by Wafflespeanut** [comment]
#15840 is up for grabs. Anyone wanna take it?

**Comment by PhilHernandez** [comment]
Hey @Wafflespeanut ,
I'd like to work on #15840 if it's still open, thanks.

**Comment by Wafflespeanut** [comment]
#15842 is up for anyone interested.

**Comment by chmln** [comment]
Looking to contribute to the Rust codebase.
Plenty of experience in JS, C/C++, Python, etc

**Comment by StefanoChiodino** [comment]
I'd like to participate! Started rust recently, mostly c# web developer by the day

**Comment by Kowasaki** [comment]
Hello!

I'm a graduate student/researcher who is interested in contributing to Servo and using/learning more about Rust! I'm proficient in JS, Python, Java, C/C++ and a beginner in Rust.

**Comment by Nefari0uss** [comment]
Hello,
Long time Firefox user and am looking to some way to contribute. Entry level developer; have BS in CSE but little experience in web dev and 0 in Rust.

I feel comfortable learning new things but JS feels like it's impossible to figure out an entry point without jumping down a rabbit hole. Guidance would be much appreciated. This [Medium](https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f#.5azsvds8t) article summarizes how I feel.

**Comment by CajetanP** [comment]
Hello everyone!
I'm very interested in the project, but I wanted to begin with understanding the code base.
Could you point me in the right direction and tell me where should I start reading?
Which source file is the "main" one or something?
It's the first web browser engine's code I'm looking at and I'm quite confused at this point.

**Comment by askalski** [comment]
Hi.
I know a lot about rendering. Both meshes (gamedev experience) and raster (mapping experience). Need SVG renderer?

**Comment by Wafflespeanut** [comment]
@CajetanP It's not a good idea to start reading from the main function. There's so much stuff to easily discourage people. Usually, people make a guess on where to look into, based on the issue of choice, and traverse the code from there. If you still want it, then the entry point for the wrapper is [here](https://dxr.mozilla.org/servo/source/ports/servo/main.rs). The browser engine's entry point is [here](https://dxr.mozilla.org/servo/source/components/servo/lib.rs).

**Comment by CajetanP** [comment]
@Wafflespeanut  So I should find an issue to solve, start by reading the source file in question and just follow along with any function calls I don't understand?

**Comment by Wafflespeanut** [comment]
Exactly! But sometimes, the issue won't list a piece of code (probably because it's low priority and no one wants to do it, or no one can't think of a solution). That said, you're always free to look around at new pieces of code, explore yourself and fix anything that you think could be changed. PRs are always welcome 😄

**Comment by CajetanP** [comment]
Thanks, I'll do my best to do something useful !

**Comment by MichaelRupertDev** [comment]
Hello! 
I'm mostly a Python dev with interest in learning Rust but no experience in it yet. Have a good amount of experience in building web apps in React and React-Native.

**Comment by athyuttamre** [comment]
Hello! I'm CS student with extensive web development experience, and marginal operating systems and distributed systems experience in C and Golang. I'm starting to pick up Rust, and am looking to contribute towards core browser dev in Rust or JavaScript!

**Comment by sendilkumarn** [comment]
Looking forward to work on an issue 😄

**Comment by niki-04** [comment]
I am interested in contributing to a significant servo bug. I have experience in python, C++. I had previously also contributed to a servo bug.

**Comment by sjml** [comment]
Hello! Former game developer here. Lots of experience with C/C++, Python, (plenty of other scripting languages), shell scripts, build systems, testing setups, etc. Don't know Rust, and have been looking for an excuse to learn it. Happy to help out, but would love some guidance as to a good spot to start.

**Comment by choudhary001** [comment]
Hey! I am learning Rust language and would like to contribute to Servo. I have already submitted a PR for one of the issues in salt stack which is under review and would like to contribute more in this project (first open source contribution :) ). I have experience in Python/Javascript as well.

**Comment by ripplejb** [comment]
I am coming from mostly Microsoft background. However, I am very comfortable with C++, JavaScript and Python. I can learn programming languages very fast. I would love to contribute. 
Saying that, I am very new to the project. I would like to know more detail about it. Specifically the goal/road map of the project.

**Comment by gravel66** [comment]
Hi, I'm a Python developer by day, but Rust has become my go-to language at night. I've been working on some small side projects in Rust for the past few months, and I'd love to contribute to Servo. Most of my previous experience has been in web development and some in networking.

**Comment by phisixersai** [comment]
Hi, I am a frontend developer and also have experience on C++, node.js and python.  Interest in learning Rust but no experience. I'd like to contribute to some servo bugs.

**Comment by emilio** [comment]
If someone would be interested in taking #16840, I'll be happy to mentor it.

**Comment by luisbg** [comment]
Hi, joining the group here of people interested in playing with Servo code :smiley:

I'm a GStreamer, Linux kernel and more developer. Having great fun with Rust. Very interested in learning the internals of Stylo.

**Comment by jesusbv** [comment]
Hi, I'm a NodeJS/Python developer, but I want to move to Rust. I have experience in C/C++  and I'd love to contribute to Servo. 
Also, experience in OOP, REST APIs(mostly web development) if that helps.

**Comment by j-haj** [comment]
I'm also interested in joining the group and am particularly interested in getting more experience with Rust. I am currently working the the Rust book and can also help with Python and C++ issues.

**Comment by allonhadaya** [comment]
Hello,

I'd love to get involved, and make some contributions. I would appreciate working on issues that could guide coming to an understanding of the organization of the code base. That being said, I'd be happy to be helpful in any way.

My background includes Java, C#, JavaScript/HTML/CSS, Golang, Elixir, Python, Shell. I'm looking forward to learning Rust, and have spent quite a bit of time with "the book" so far. I've worked on web mostly, both back and front, as well as in desktop, mobile, and embedded environments.

I appreciate your all putting so much energy towards making contribution accessible!

**Comment by photex** [comment]
Howdy!

I've predominantly been a c++ developer in my career and done a lot of desktop app development with Qt.
I've been using Rust for a little while now (small command line tools, a service and rpc implementation) and would love to contribute.

**Comment by rthomas** [comment]
Hey,

I've done a couple of PRs for `servo/core-foundation-rs`, `servo/core-graphics-rs` and `servo/core-text-rs` and I'm looking for something more to work on outside of my personal projects.

**Comment by lauryndbrown** [comment]
Hi! I'd love to help. I'm fluent in Python, Css, and HTML. I don't know Rust yet, but I'm happy to learn. I'm partial to UI-esq issues (I initially checked out browser.html, but I'm not certain it's still being used?). I'd just enjoy helping though.

**Comment by jdm** [comment]
I feel bad about this; we had a really good run of responding and helping people between January and April, but since then we have been really bad about following up with people who have replied in this issue. Most of the team is focused on the integration work we're doing with Firefox right now, unfortunately. I'm going to close this so we don't keep advertising opportunities that don't really exist at the moment; I hope to reopen it when we're more available to help. Thanks for all of the interest!
