### ISSUE TITLE
Add support for remaining keyword values of -moz-user-select property

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15197]
Currently it only parses `auto`, `text`, `none`, and `all`, but Gecko also supports `element`, `elements`, `toggle`, `tri_state`, `-moz-all`, `-moz-none`, and `-moz-text`.

**Comment by jdm** [comment]
@singhkaran The actual code changes here will be [minimal](https://dxr.mozilla.org/servo/rev/4a0b730cafd09fbd6e5cbc00727caef9b3cae315/components/style/properties/longhand/ui.mako.rs#19), but adding a unit test to `tests/unit/style/parsing/` to verify that the new keywords parse correctly would be a nice introduction to Rust.

**Comment by singhkaran** [comment]
Sounds great, I'll take it.
