### ISSUE TITLE
calc() doesn't support dividing an expression

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15192]
`calc(50px / 2)` works, but `calc(50px / (1 + 1))` doesn't work.

**Comment by Manishearth** [comment]
Division is implemented as 1 / multiplication, which we probably shouldn't do.

**Comment by nox** [comment]
@upsuper https://drafts.csswg.org/css-values/#calc-syntax says `/` should only be followed by `<number>`. Do we really want to support `50px / (1 + 1)`?

**Comment by nox** [comment]
Seems like the spec is wrong on this, both Firefox and WebKit don't mind the addition.

**Comment by nox** [comment]
https://github.com/w3c/csswg-drafts/issues/1241

**Comment by upsuper** [comment]
Yeah, dbaron is right that we should support it, especially given that Gecko already supports it, and CSSWG is going to expand that to support even more powerful expression.

**Comment by KiChjang** [comment]
The draft has been updated with an extended syntax to support different kinds of expressions.

Taking a look at this.

**Comment by KiChjang** [comment]
Blocked on #16728.

**Comment by Wafflespeanut** [comment]
#16728 seems to fix this.
