### ISSUE TITLE
"columns" shorthand is serialized to include "initial" CSS-wide keyword

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15190]
For example:
```html
<div style="columns: 3"></div>
<script>alert(document.querySelector('div').style.columns);</script>
```
Servo outputs `initial 3`, which is invalid. It should be `auto 3`.

Spec: https://drafts.csswg.org/css-multicol-1/#columns

The relevant code is: https://github.com/servo/servo/blob/master/components/style/properties/shorthand/column.mako.rs#L53-L58

**Comment by simpslandyy** [comment]
Hi, I intend to work on this issue! :)

**Comment by upsuper** [comment]
Great! Please ask questions here if there is anything unclear.

**Comment by simpslandyy** [comment]
Is the link to the relevant code where the issue is?
I've been looking around at it and trying to understand what's exactly happening, 
do you mind giving me the general idea behind this code? 
What is the method `to_css_declared` doing exactly?

**Comment by upsuper** [comment]
I thought it is, and the solution in my mind was that, if `self.column_width` is `initial`, output `auto` instead. But I realized that there are two more fundamental issues here:
1. We should not call into this function at all when any longhand of this shorthand is `initial`, which is actually #15004.
2. `column_width` should not be `initial` at all here, since `columns` shorthand should save the initial value (rather than `initial`) to `column-width` when omitted.

I think the actual relevant code of this bug is https://github.com/servo/servo/blob/master/components/style/properties/shorthand/column.mako.rs#L11-L49

This parsing function should specify `auto` instead of `None` when the corresponding part doesn't present.

**Comment by simpslandyy** [comment]
^ okay, sorry I'm not very familiar with Rust. This is my first GFB.
So this parsing function, checks if columns_width and columns_count is None, and sets them to a value if the condition evaluates to true. 

So you said, "This parsing function should specify auto instead of None when the corresponding part doesn't present."

I'm not entirely sure what you mean by that. Because at the start of the parsing function both values are initialized to None. So are those the values that need to be changed?

**Comment by upsuper** [comment]
Probably the beginning of the parsing function should not be changed, because we need that to check whether the corresponding parts are specified in the shorthand. The function should return auto for a part only when it is absent from the value.

**Comment by upsuper** [comment]
I'm going to close this issue since I think #15380 would include a more fundamental fix to this issue.
