### ISSUE TITLE
Implement serialization of transform functions

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15194]
Currently, only serialization of `translate()` function is implmeneted. We should have the rest implemented as well.

Spec: https://drafts.csswg.org/css-transforms/#serialization-of-transform-functions

The relevant code is https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs#L1183-L1237

(I think this is an easy one, but not sure. cc @Manishearth)

**Comment by upsuper** [comment]
Great! Please ask questions here if there is anything unclear.

**Comment by dpyro** [comment]
It looks like we are implementing serialization of the specified transforms, not the computed ones. If that is correct, it looks like we are discarding needed information to regenerate the original specified transforms in [parse](https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs#L1271-L1497). Should I then modify the specified data structures to retain the necessary information and drop it into the compute section?

**Comment by Manishearth** [comment]
Nah. It is okay to drop info during computing. Should parse+compute back to the same computed value.

**Comment by dpyro** [comment]
Advice requested: when should I use `ref` while matching?

```rust
enum SpecifiedOperation {
    Matrix(SpecifiedMatrix),
    Skew(specified::Angle, specified::Angle),
    Translate(TranslateKind,
              specified::LengthOrPercentage,
              specified::LengthOrPercentage,
              specified::Length),
    Scale(CSSFloat, CSSFloat, CSSFloat),
    Rotate(CSSFloat, CSSFloat, CSSFloat, specified::Angle),
    Perspective(specified::Length),
}
```

For example, currently there is: `SpecifiedOperation::Translate(kind, ref tx, ref ty, ref tz)`

**Comment by Manishearth** [comment]
Whenever the type is not copyable. The length ones and perhaps the angle ones aren't. It's okay to use an unnecessary ref.

**Comment by dpyro** [comment]
How would I properly test this using the css-tests? Currently I am trying `$ ./mach test-css css-transforms-1_dev`, but this takes a long time to run (I may try running it on my desktop instead) and outputs verbose info instead of a summary of expectations vs. pass/fails.

**Comment by Manishearth** [comment]
I don't think there's a way to step around the verbose summary -- it only outputs a list of things which have changed. You can get a shorter (but still verbose) summary via `--log-errorsummary foo.log`. You can also make a pull request containing your changes and ask one of us to trigger a run on the try server which will run all the tests.

I'm unsure if those tests actually contain any serialization tests. Create a new one in wpt if you can't find one (via `./mach create-wpt`). Or just add to the existing roundtrip parse/serialization tests in tests/unit/style.

**Comment by jdm** [comment]
The verbose summary is caused by https://github.com/servo/servo/issues/15193.

**Comment by dpyro** [comment]
I’m starting to get stuff to work! There is an issue: the current implementation expresses `Angle` in terms of radians, but [the canonical and default unit is degrees](https://drafts.csswg.org/css-values-3/#angles). Do we also need to keep track of the specified unit for serializing `Angle`s back out?

**Comment by upsuper** [comment]
Per spec, and other major browsers' behavior, I think for specified value, the original unit should be preserved. (That said, `10rad` is serialized as `10rad`, and `10deg` is serialized as `10deg`.)

This means you'll probably also need to change some of the parsing code to preserve the units. In addition to that, it seems that Servo is currently normalizing `rotate{X,Y,Z}` to `rotate3d`, `skew{X,Y}` to `skew` etc., which also loses information necessary for serialization.

For computed value... I guess it doesn't really matter, because we don't need to serialize transform functions in their original form for value returned by `getComputedStyle`. They are always resolved to matrix.

**Comment by Wafflespeanut** [comment]
Previous work and reviews are in #15508

**Comment by pyfisch** [comment]
@upsuper I would like to work on this. What is the best way to start?

**Comment by upsuper** [comment]
@pyfisch Probably you can have a look at #15508 to see where the code should go. Actually you can probably just try simplifying the code in that PR.

**Comment by pyfisch** [comment]
I am wondering why `ToCss` is necessary or why `Display` is not also implemented. If it was implemented one could use the a single `write!` instead of multiple calls to `write_str` and `to_css`.

**Comment by pyfisch** [comment]
Currently `scale()` is only implemented for two arguments. The spec mandates that a single argument is valid and the [old PR also implemented it](https://github.com/servo/servo/pull/15508/files#diff-509dba3695e8d741d1a61f433547ac67R1733). Should this be included in the new PR?

**Comment by pyfisch** [comment]
Same for skew. I have implemented them both now.

**Comment by upsuper** [comment]
I'm not sure exactly why we go that route, but I think that makes sense because CSS representation isn't necessarily the way we want to display it. Using a separate trait for the standardized way makes more sense. But I understand that using a single `write!` may make the code more compact. Probably we can add a similiar macro for `ToCss`... not sure whether it's doable...

**Comment by pyfisch** [comment]
I found an easier solution then creating a new macro: All values I use inside `format!` are wrapped inside a struct called `Css` that implements `Display` for all types that implement `ToCss`. I use it like that: `write!(dest, "translate({}, {})", Css(tx), Css(ty))`

**Comment by upsuper** [comment]
@Manishearth, are you happy with this? ^

**Comment by Manishearth** [comment]
I think for coherence reasons. We need to be able to provide our own impls of `ToCss`, so it's best to keep it a separate trait.

**Comment by Manishearth** [comment]
Oh, a `Css` struct would be fine though

**Comment by pyfisch** [comment]
```
/// Wrap CSS types for serialization with `write!` or `format!` macros.
struct Css<T>(T);
impl<T: ToCss> Display for Css<T> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.0.to_css(f)
    }
}

impl<'a, T: ToCss> Display for Css<&'a T> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.0.to_css(f)
    }
}
```

Ideally the struct works on both owned and borrowed values but implementing it like this causes (obviously) conflicting implementations. Is there a way to make work? Or is it better to only implement it for borrowed values and and borrow owned ones to use them?

**Comment by Manishearth** [comment]
Use `T: AsRef<U>`?

**Comment by Manishearth** [comment]
`impl<T: AsRef<U>, U: ToCss> Display for Css<U>`?

Though, that may fall afoul of the covered rule, hm.

**Comment by emilio** [comment]
Why not just `struct Css<'a, T>(&'a T)`? Seems like the most straight-forward way to implement this.

**Comment by Manishearth** [comment]
They want it to be usable in other cases too.

**Comment by emilio** [comment]
Who's "They", if I can ask? And what's the use case?

**Comment by Wafflespeanut** [comment]
I think having `Css<'a, T>` should just be enough. It's gonna be created/used only in `ToCss` impls, right?

**Comment by Manishearth** [comment]
"they" is @pyfisch 

Usecase was a bad way of framing it, I meant that @pyfisch wanted it to be usable for both `Css(T)` and `Css(&T)`

**Comment by emilio** [comment]
Right, but what's the use case for `Css` taking ownership of anything ever?

**Comment by Manishearth** [comment]
Just ergonomics. But yeah, not much of a use case, `Css(&T)` should be fine

**Comment by emilio** [comment]
And apologies, didn't know that usage of "they" as a gender-neutral, singular pronoun (I'd have expected a mention, "the assignee" or something like that). Didn't want to be mean :)

**Comment by pyfisch** [comment]
Thanks for your help. I looked up how `Display` works and found that it is implemented for borrowed values. I added a similar impl for ToCss. If this causes any problems I can also insert '&' chars everywhere. The PR is also uploaded.
