### ISSUE TITLE
Only use mach log formatter if there is a single test file argument

### ISSUE THREAD

**Issue by jdm** [servo/servo#15193]
The changes in #15124 have made `./mach test-wpt tests/wpt/dir` behave the same as `./mach tests-wpt tests/wpt/dir/test.html`. Ideally we would only use the mach logger for the second one, and stay with the servo formatter for the directory.

**Comment by jdm** [comment]
We should enhance the check in `run_tests` to check whether the argument ends in `.html`, `.htm`, `.js`, or `.xhtml`.

Code: `tests/wpt/run.py`

**Comment by dpyro** [comment]
I’ll work on this one, since it should be quick and is making testing #15194 unnecessarily verbose.

**Comment by jdm** [comment]
Thanks!

**Comment by nox** [comment]
@jdm How do I disable this behaviour locally? The mach output just confuses me, I always want the pretty-printed quieter one.

**Comment by jdm** [comment]
We will need to add an argument to testing_commands.py that forces the use of the human-readable logger in tests/wpt/run.py.
