### ISSUE TITLE
Value of transform should be serialized to "none" rather than empty when no operation specified

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15195]
Currently, `transform: none;` is serialized to `transform: ;` which is invalid. It should be serialized to `transform: none;` instead.

The relevant code is: https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs#L1253-L1263

**Comment by DexterHaslem** [comment]
I'd like to work on this

**Comment by upsuper** [comment]
Great! Ask questions here if anything is unclear.

**Comment by DexterHaslem** [comment]
I'm trying to write a unit test to verify the fix, but I'm struggling with creating a 'none' property value.. here is what I have tried:

    use style::properties::longhands::transform::SpecifiedValue as TransformValue;
    let declaration = PropertyDeclaration::Transform(DeclaredValue::Value(TransformValue(Vec::new())));

I get an error

    PropertyDeclaration::Transform(DeclaredValue::Value(TransformValue(Vec::new())));    
    |                                                    ^^^^^^^^^^^^^^ cannot construct with a private field


then I thought something like `PropertyDeclaration::Transform(DeclaredValue::Unset)` would be it, but thats the literal unset keyword so now I'm stuck. Does the 'transform' longhand mako need a values='none' added to it or am I completely misunderstanding?

If unclear, I basically need to represent a default transform property

**Comment by upsuper** [comment]
I guess it may be easier to write a wpt test rather than a unit test. cc @Manishearth

**Comment by Manishearth** [comment]
You can just roundtrip it -- parse the string "none", wrap in PropertyDeclaration and serialize

**Comment by Manishearth** [comment]
WPT test also fine but this seems like a very servo specific bug
