### ISSUE TITLE
outline-style should accept "auto" value in addition to border-style values

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15207]
Spec: https://drafts.csswg.org/css-ui-3/#outline-style

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/longhand/outline.mako.rs#L17-L30

(This is probably not easy enough... I don't know. cc @Manishearth)

**Comment by Manishearth** [comment]
It's easy enough.

**Comment by dashed** [comment]
I would like to take up this issue.

**Comment by Manishearth** [comment]
Great! https://github.com/servo/servo/wiki/Property-hacking-guide has some tips on writing parse/serialization code. You basically need to replace this with an enum where one variant contains BorderStyle and the other is Auto
