### ISSUE TITLE
calc() should support number in `line-height`

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15205]
e.g. `line-height: calc(1 + 1)` should work.

**Comment by Maaarcocr** [comment]
I would like to work on this, but I'm not too sure if it would be too challenging.

**Comment by jdm** [comment]
I tried to look for useful hints, but all I could find was the parsing code for line-height: https://dxr.mozilla.org/servo/rev/ba7696ebc64c1a73aee1547fcea8b75b2a1eb4b1/components/style/properties/longhand/inherited_text.mako.rs#48-69

**Comment by Wafflespeanut** [comment]
@upsuper I suppose this is specific to `line-height`? `calc` already supports parsing numbers. For some reason, we've left parsing it in `line-height`, in which case, it could be an easy issue.

@Maaarcocr Either way, you can look into the the code @jdm has suggested. `LengthOrPercentage::parse_non_negative` calls [this](https://doc.servo.org/style/values/specified/length/struct.CalcLengthOrPercentage.html#method.parse_length_or_percentage) function, which doesn't parse anything other than `length` or `percentage`. What you can do is tweak the parsing code to try parsing `CalcUnit::Number` and then fall back to whatever it has. Feel free to ask questions :)

**Comment by upsuper** [comment]
@Wafflespeanut There are two properties we support using `calc()` with number in Gecko currently. One is `line-height`, and the other is `-moz-tab-size`. There is [a pending patch in Gecko side](https://bugzilla.mozilla.org/show_bug.cgi?id=737785) to unprefix `-moz-tab-size`, which may cause some conflict, but it shouldn't be too bad.

**Comment by Wafflespeanut** [comment]
Looks like we don't support `-moz-tab-size` right now. So, let's make this specific to `line-height`.

@Maaarcocr Ping me if you're willing to work on this :)

**Comment by upsuper** [comment]
Oh, right. I somehow thought we have that... That's an easy property, though :)

**Comment by upsuper** [comment]
We support `-moz-tab-size` now :)

**Comment by upsuper** [comment]
It seems to me this has been supported since long ago, so probably what I was seeing in mochitest failure is not really because of this.
