### ISSUE TITLE
{background,mask}-position lacks comma for serialization

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15200]
`background-position: top left, top left;` is currently serialized to `background-position: top lefttop left;` which is invalid.

The relevant code is https://github.com/servo/servo/blob/master/components/style/properties/shorthand/background.mako.rs#L311-L330

(The fix is simple... but I'm just too lazy to write a test for it.)

**Comment by multhazim123** [comment]
I'd like to work on this!

**Comment by jdm** [comment]
Please do! Ask questions here if anything is unclear.

**Comment by Wafflespeanut** [comment]
@multhazim123 Hey, did you get to look into this?

**Comment by multhazim123** [comment]
Working on it.

**Comment by KiChjang** [comment]
@multhazim123 Did you run into any issues? Any questions that we can answer?

**Comment by multhazim123** [comment]
@KiChjang Not yet. Please give me a few days.

**Comment by Wafflespeanut** [comment]
No worries! :)

**Comment by upsuper** [comment]
`mask-position` has exactly the same issue as `background-position`. Could you please fix that at the same time? The relevant code is in https://github.com/servo/servo/blob/master/components/style/properties/shorthand/mask.mako.rs#L272-L315

It would be great if the two shorthands can share this logic.

**Comment by absoludity** [comment]
Hi @multhazim123 . I'm not sure if you want a hand with this, or if you've still got time? If you do still want to look at it, here's a gist with a small diff for current master which gives you a failing test... the challenge then is just getting it to pass :)

https://gist.github.com/absoludity/f05f25e4be20541a3553e881fa6a304b

If you don't have time, just let me know and I can grab it - fine either way :)

**Comment by multhazim123** [comment]
Hi. Thanks for that. Yeah, I'll be finishing this up this week.

**Comment by multhazim123** [comment]
Hi @KiChjang, I'm unable to check the relevant code. The link shows me some other line. Could you let me know which lines pls.

**Comment by upsuper** [comment]
https://github.com/servo/servo/blob/c62973b77b6ac74c0daf11b1f4c18b9dd64ae400/components/style/properties/shorthand/background.mako.rs#L233-L237
https://github.com/servo/servo/blob/c62973b77b6ac74c0daf11b1f4c18b9dd64ae400/components/style/properties/shorthand/mask.mako.rs#L227-L230

**Comment by jdm** [comment]
@multhazim123 How's it going?

**Comment by Adynatos** [comment]
Since @multhazim123 is not responding, can I take it?

**Comment by KiChjang** [comment]
@Adynatos Yes, go right ahead!
