### ISSUE TITLE
outline shorthand should not serialize initial value of outline-width to "initial"

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15206]
`outline: none` is currently serialized to `outline: initial none`, which is invalid. It should be `outline: medium none` or `outline: none`.

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/shorthand/outline.mako.rs#L56-L57

**Comment by chargadesilva** [comment]
I'll check this out

**Comment by upsuper** [comment]
Great! Feel free to ask any questions if anything is unclear.

**Comment by Wafflespeanut** [comment]
@chargadesilva Have you made any progress?

**Comment by chargadesilva** [comment]
Not yet, hoping to get to it this weekend.

Thanks!

**Comment by jdm** [comment]
Unassigning due to lack of progress. If you have time to start actively working on it and this issue is unassigned, you're welcome to return to it!

**Comment by projektir** [comment]
I'd like to take a stab at this.

**Comment by upsuper** [comment]
I'm going to close this issue since I think #15380 would include a more fundamental fix to this issue.
