### ISSUE TITLE
Value of quotes should be serialized to "none" if the list is empty

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15209]
It is basically the same issue as #15195.

Documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/quotes

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/longhand/list.mako.rs#L56-L68

**Comment by eddiequan** [comment]
Hi, I intend to work on this issue.

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear!

**Comment by Wafflespeanut** [comment]
@eddiequan Any news on this?

**Comment by eddiequan** [comment]
@Wafflespeanut Yes, I've cloned the repo and have written a fix similar to #15195 and it seems to work. I will try to get a PR in following the contribution steps by this weekend!

**Comment by Wafflespeanut** [comment]
Cool!
