### ISSUE TITLE
Setting border and border-[side] shorthands should reset longhands of border-image to their initial value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15202]
Although `border` and `border-{top,right,bottom,left,{inline,block}-{start,end}}` doesn't contain syntax for `border-image`, but per spec those shorthands should also reset the `border-image-*` longhand properties to their initial value.

Spec: https://drafts.csswg.org/css-backgrounds-3/#the-border-shorthands

Relevant code: large part of https://github.com/servo/servo/blob/master/components/style/properties/shorthand/border.mako.rs

**Comment by upsuper** [comment]
I suppose this isn't too hard... @Manishearth WDYT?

**Comment by Manishearth** [comment]
I guess we just need to declare the border-image longhands as part of them and always reset them? Sounds doable.

**Comment by upsuper** [comment]
Yes, should be just that.

**Comment by chenpighead** [comment]
Since I'm touching the codes here while fixing Gecko's [Bug 1348173](https://bugzilla.mozilla.org/show_bug.cgi?id=1348173), I can take care of this as well.

@highfive: assign me
