### ISSUE TITLE
Value of box-shadow is serialized in a wrong order

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15203]
The order should be "horizontal offset, vertical offset, blur radius, spread distance", but in the current code, it is "blur radius, spread distance, horizontal offset, vertical offset". The parsing order is correct, which means if you input `1px 2px 3px 4px`, it is serialized to `3px 4px 1px 2px`...

Spec: https://drafts.csswg.org/css-backgrounds-3/#the-box-shadow

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/longhand/effects.mako.rs#L27-L44

**Comment by niki-04** [comment]
I would like to work on this!

**Comment by upsuper** [comment]
Great! Please ask questions here if there is anything unclear.

**Comment by niki-04** [comment]
So I just started looking at the code. I am new to the language Rust. I just want to confirm what is meant by the serialization order is wrong is it the order of the try statements in the highlighted block of code. So the order of try statements is blur_radius, spread_radius, offset_x and offset_y and to correct the order of serialization we need to change it to offset_x, offset_y, blur_radius and spread_radius. Let me know if I am thinking in the right direction.

Also, could you point to some rust tutorials so I get to learn the language better.

**Comment by upsuper** [comment]
Yes, I think that is correct. And you should also add a unit test for it.

The book of Rust should be a good start: https://doc.rust-lang.org/book/

**Comment by jdm** [comment]
https://dxr.mozilla.org/servo/source/tests/unit/style/properties/serialization.rs are examples of existing unit tests verifying the behaviour of CSS serialization. You can run them with `./mach test-unit -p style`.

**Comment by Wafflespeanut** [comment]
@niki-04 Hi! Have you started working on this?

**Comment by niki-04** [comment]
@Wafflespeanut Not yet. I would get started this weekend.

**Comment by Wafflespeanut** [comment]
Good to know!

**Comment by karan1276** [comment]
.

**Comment by niki-04** [comment]
I started working on this. I did change the required code but I am getting a bit confused with the test case. I tried to look at the test cases in serialization.rs for other properties but I am not sure how to define my own property and write the test case. Any help on this would be appreciated. Also, I am not that familiar to rust.

**Comment by Wafflespeanut** [comment]
Okay, so `serialization.rs` contains tests for some of the shorthand properties (many shorthands and longhands don't have a test,`box-shadow` is one among them). As you can see, all the tests [have a basic template](https://dxr.mozilla.org/servo/source/tests/unit/style/properties/serialization.rs?q=serialization.rs&redirect_type=direct#468-482) like this,

``` rust
let mut properties = Vec::new();

let value = DeclaredValue::Value(/* custom value */);
properties.push(PropertyDeclaration::PropertyName(value));
let serialization = shorthand_properties_to_string(properties);
assert_eq!(serialization, /* "corresponding CSS serialization string" */);
```

The first step is to have a new module named `effects` (just like the other modules already there) and put your test function there with that template. For `box-shadow`, you need [this](https://doc.servo.org/style/properties/longhands/box_shadow/struct.SpecifiedValue.html) type. Once you plug in the values and run the test using `./mach test-unit -p style`, your test will fail (caused by the `assert_eq!` panic) in your function. The stdout will show you how the value is being serialized and then, you can make your changes as appropriate.

Does this help?

**Comment by niki-04** [comment]
@Wafflespeanut, thanks this helps. Also, what does the custom value mean?

**Comment by Wafflespeanut** [comment]
In your case, it should be the [specified value](https://doc.servo.org/style/properties/longhands/box_shadow/struct.SpecifiedValue.html) of `box-shadow` (which is a vector of [`Shadow`](https://doc.servo.org/style/values/specified/struct.Shadow.html)). You can define your own value using that type and check the corresponding serialization in the end.

**Comment by niki-04** [comment]
@Wafflespeanut Thanks a lot!!!. Also, one last thing shadow is a struct with values offset_x offset_y and other parameters with types Length which is an enum. I am not sure how to initialize values for those it would be great if you could give me some sort of example for initializing one of the parameter values for shadow struct. Also, do I need to initialize color and inset too?

**Comment by upsuper** [comment]
See [the document of Length](https://doc.servo.org/style/values/specified/length/enum.Length.html), there are various methods for generating a `Length` value. Probably the easiest one is `Length::from_px`. (Note: you can click types in the document to see their document, where you can find lots of useful things.)

**Comment by niki-04** [comment]
Ok so @Wafflespeanut  I did all that and wrote the test case as follows
    mod effects {
        pub use super::*;
        pub use style::properties::longhands::box_shadow::SpecifiedValue as BoxShadow;
        pub use style::values::specified::Shadow;
        #[test]
        fn box_shadow_should_serialize_correctly() {
            let mut properties = Vec::new();
            let color = Some(CSSColor {
                        parsed: ComputedColor::RGBA(RGBA { red: 1f32, green: 0f32, blue: 0f32, alpha: 1f32 }),
                        authored: None
                        });


            let shadow =  DeclaredValue::Value(Shadow {offset_x: Length::from_px(1f32), offset_y: Length::from_px(2f32), blur_radius:Length::from_px(3f32), spread_radius:Length::from_px(4f32), color:color, inset:false });
            properties.push(PropertyDeclaration:: BoxShadow(shadow));


             let serialization = shorthand_properties_to_string(properties);
             assert_eq!(serialization, "box-shadow: 1px 2px 3px 4px;");
        }
    }
But it gives me this error 
 properties.push(PropertyDeclaration:: BoxShadow(shadow));
     |                                                             ^^^^^^ expected struct `style::properties::longhands::box_shadow::SpecifiedValue`, 
found struct `style::values::specified::Shadow`

I am not sure what is wrong here as value is supposed to be a vector of Shadow. Thanks in advance!

**Comment by jdm** [comment]
It sounds like you need to rebase your changes on top of a more recent master. The style system changed to include more box types last week.

**Comment by jdm** [comment]
Sorry, ignore that comment. I totally misread the error.

**Comment by Wafflespeanut** [comment]
@niki-04 Yes, so you need to use the imported `SpecifiedValue`. As you [may have seen](https://doc.servo.org/style/properties/longhands/box_shadow/struct.SpecifiedValue.html), the specified value is actually a struct wrapper around `Vec<Shadow>`.

So, you need to do something like,

``` rust
let shadow_value = Shadow { ... };
let shadow_decl = DeclaredValue::Value(BoxShadow(vec![shadow_value]));
// rest is the same
```

and it should work :)
