### ISSUE TITLE
Use recv_timeout in TimerScheduler?

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15218]
There's a comment in there that states
```rust
        // We could do this much more directly with recv_timeout
```

and points to https://github.com/rust-lang/rfcs/issues/962 which points to https://github.com/rust-lang/rust/issues/34029 which was closed in https://github.com/rust-lang/rust/pull/35607.

**Comment by emilio** [comment]
Yeah, I implemented it just for that purpose :)

**Comment by nox** [comment]
This is doable now.

**Comment by nox** [comment]
@emilio Could this be an E-Easy issue?

**Comment by AnshulMalik** [comment]
Is this still valid?

**Comment by jdm** [comment]
The only use of recv_timeout under components/ is in paintworkletglobalscope.rs, so I do not believe so.
