### ISSUE TITLE
servo fails to start with an X error on awesome wm but runs on unity 

### ISSUE THREAD

**Issue by marianoguerra** [servo/servo#1521]
this is the error:

./servo ../src/test/html/about-mozilla.html

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1a00005
  Serial number of failed request:  29
  Current serial number in output stream:  29

**Comment by mbrubeck** [comment]
Servo should no longer be affected by this since it doesn't use glfw anymore.
