### ISSUE TITLE
{fill,stroke}-opacity should support SVG-in-OT values context-{fill,stroke}-opacity

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15211]
I don't find any formal definition of these values... but Gecko supports them... cc @heycam

**Comment by upsuper** [comment]
The spec is https://www.microsoft.com/typography/otspec/svg.htm

**Comment by nox** [comment]
What are the computed values for `context-fill-opacity` and `context-stroke-opacity`?

Should `stroke-width`, `stroke-dasharray` and `stroke-dashoffset` also support `context-value` like the spec you linked says?

**Comment by upsuper** [comment]
> What are the computed values for `context-fill-opacity` and `context-stroke-opacity`?

Seems to be some flags in `nsStyleSVG::mContextFlags`. See [nsStyleStruct.h](https://dxr.mozilla.org/mozilla-central/rev/9550eedc0bd80d404dab4e42660c629cc705c16c/layout/style/nsStyleStruct.h#3495-3514).

> Should `stroke-width`, `stroke-dasharray` and `stroke-dashoffset` also support `context-value` like the spec you linked says?

Yes.

Note that all those values are controlled by pref `gfx.font_rendering.opentype_svg.enabled`, and there is a test to ensure the effectiveness of that pref. So we probably need to follow that as well.

**Comment by nox** [comment]
Should we file an issue on the compat spec for these values to be mentioned there?

**Comment by upsuper** [comment]
Why compat spec? It is nothing about compat, it is a feature we support and don't want to unship. It is just defined in OpenType spec rather than an SVG or CSS spec.

**Comment by nox** [comment]
@upsuper All I saw was the microsoft domain and I thought it was vendor-specific, disregard that. :)

**Comment by upsuper** [comment]
That is the OpenType spec hosted on Microsoft's domain. The original draft can be found here: https://dev.w3.org/SVG/modules/fonts/SVG-OpenType.html and there is a link saying the document in Microsoft domain is the spec.

IIRC this is actually something only Gecko implements at the moment.

**Comment by KuoE0** [comment]
I'm working on this issue on [Bug 1338764](https://bugzilla.mozilla.org/show_bug.cgi?id=1338764).

**Comment by sviter** [comment]
Is it still valid?

**Comment by upsuper** [comment]
This has been fixed by #17940.
