### ISSUE TITLE
writing-mode should accept obsolete SVG 1.1 values and sideways-{lr,rl}

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15213]
The obsolete SVG 1.1 values can be easily mapped to existing values, but we probably want to add sideways values only for gecko for now.

Spec: https://drafts.csswg.org/css-writing-modes-3/#block-flow

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/longhand/inherited_box.mako.rs#L19-L24

(Maybe an easy one, cc @Manishearth)

**Comment by Manishearth** [comment]
This is tricky, since it maps to both the writing-mode and direction property. Probably not easy.
