### ISSUE TITLE
Support for Document's origin / effective script origin

### ISSUE THREAD

**Issue by brunoabinader** [servo/servo#1522]
Spec:
http://www.whatwg.org/specs/web-apps/current-work/multipage/origin-0.html#origin

This is a subtask for #1510.

**Comment by asajeffrey** [comment]
`Document` supports `origin`, and https://github.com/whatwg/html/pull/925 removed "effective script origin". The last remaining piece is allowing setting of `document.domain`, which is the remaining unimplemented part of #934.

**Comment by pyfisch** [comment]
This issue is referenced from [domimplementation.rs](https://github.com/pyfisch/servo/blob/root-background/components/script/dom/domimplementation.rs#L117) two times as a FIXME.

**Comment by asajeffrey** [comment]
@pyfisch oh good point. I'll file an E-easy to remove those comments.
