### ISSUE TITLE
File pull requests to bump 0.0.x dependencies to 0.1.0

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#15224]
The following crates in Servo’s dependency graph are on crates.io with a version number like 0.0.x:

* [ ] [clippy_lints](https://crates.io/crates/clippy_lints)
* [x] <s>device</s>
* [x] [gaol](https://crates.io/crates/gaol)
* [x] [mac](https://crates.io/crates/mac)
* [x] <s>task_info</s>
* [x] [traitobject](https://crates.io/crates/traitobject)
* [x] [unicode-xid](https://crates.io/crates/unicode-xid)
* [x] [xi-unicode](https://crates.io/crates/xi-unicode)

This is a problem because Cargo considers any two versions in this range to be incompatible.

In https://github.com/servo/servo/pull/15216 for example, one crate depends on unicode-xid 0.0.3 and  another on unicode-xid 0.0.4. Since there’s considered incompatible, Cargo compiles them both and we end up with two copies of a fairly large data table in the binary. But maybe (I haven’t checked) 0.0.4 doesn’t introduce any breaking change to public APIs. If the version number had been 0.1.3 instead of 0.0.3, it could have been incremented to 0.1.4 which Cargo considers to be compatible, and so could have been used for crates that specify a dependency to `unicode-xid = "0.1.3"`. Instead, 

So what’s to do (in my opinion) is, for each crate listed above:

* Find it on https://crates.io/
* Click the "Repository" link
* If the version number in Cargo.toml already not `0.0.something` anymore, there is nothing to do.
* Otherwise, make a pull request that increments the version number to `0.1.0`, with a link to this issue to explain why.
* Once the PR is merged, comment here and I’ll update the checklist above.

**Comment by KiChjang** [comment]
device and task_info are not found on crates.io. Are both of these crates that we use internally ourselves? I can find https://github.com/servo/devices, not sure if it's related.

**Comment by SimonSapin** [comment]
Ah, sorry. I misread `Cargo.lock`. `device` is a git dependency, indeed from that repository. `task_info` is `support/rust-task_info` is this repository. I’ve crossed them out in the list.

**Comment by nox** [comment]
https://github.com/unicode-rs/unicode-xid/pull/3
https://github.com/servo/gaol/pull/33

**Comment by seanlee31** [comment]
I would like to work on this issue.

**Comment by jdm** [comment]
Go for it! Ask questions if anything is unclear.

**Comment by jdm** [comment]
@seanlee31 Have you made any progress here?

**Comment by zploskey** [comment]
The only dependency on the list currently < 0.1 is clippy_lints. @Manishearth appears to own the source repository. Mind bumping the version to 0.1.0?

**Comment by SimonSapin** [comment]
Moving to https://github.com/Manishearth/rust-clippy/issues/1555. Thanks all :)
