### ISSUE TITLE
UI: small hitbox makes buttons hard to click

### ISSUE THREAD

**Issue by fvsch** [servo/servo#15235]
With Servo’s latest nightly on macOS, the "new tab" and "tab list" buttons are really small and close together. I don’t know how to inspect the precise element area, but just using the mouse cursor I see them as just taking the width and height of the icon.

A more reasonable UI would have the buttons further apart and each having a bigger reactive area, around 30x30 points or so.

![servo-browserhtml-buttons](https://cloud.githubusercontent.com/assets/243601/22326742/37470470-e3b4-11e6-8a4b-c0e8b9034d36.png)

Does this belong in the browserhtml/browserhtml repo, perhaps?

Looking at some images in browserhtml’s repo and wiki, some show small buttons, and other show buttons with more breathing room, but they might be mockups only.

**Comment by Manishearth** [comment]
Yes, this actually belongs on the browserhtml repo, sorry.

When you initially reported this I thought that this was a bug on some webpage.

**Comment by Manishearth** [comment]
cc @paulrouget

**Comment by fvsch** [comment]
Copied to https://github.com/browserhtml/browserhtml/issues/1264
