### ISSUE TITLE
Implement cross-origin iframe.contentWindow

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#15233]
Currently we return `None` for a cross-origin `iframe.contentWindow`.

**Comment by nox** [comment]
https://github.com/servo/servo/issues/2382

**Comment by asajeffrey** [comment]
@nox: I talked to @avadacatavra about this at MozAloha, and we agreed to separate out the XOW part (which deals with security) from implementing cross-origin window proxies (which deals with the inter-thread communication caused by the `WindowProxy` and the `Window` living in different script threads).

**Comment by nox** [comment]
Aren't cross-origin window proxies XOWs?

**Comment by asajeffrey** [comment]
There's two different things here, the XOW needs to point to an object. In the case where the `Window` is similar-origin, it can be the real `Window` object, but in the non-similar-object case, the `Window` is in another script thread, so we need an object to represent the cross-origin window,.

**Comment by asajeffrey** [comment]
Will be closed when #15536 lands.

**Comment by cbrewster** [comment]
#15536 has merged. Can this be closed?

**Comment by asajeffrey** [comment]
Yes it can.

**Comment by jdm** [comment]
We still return null for iframe.contentWindow for cross-but-similar-origin iframes.
