### ISSUE TITLE
Properly cancel fetch jobs

### ISSUE THREAD

**Issue by nox** [servo/servo#15236]
Currently we have no idea with which document a fetch job is associated, and the only way to cancel them is to shut down the script thread and use the flag inside `RunnableWrapper`. That doesn't scale for either `document.open` nor for unloading documents in general.

Cc @jdm @Ms2ger 

Blocks #14591.

**Comment by nox** [comment]
If you have any idea, I'm all ears, because that sounds like a quarter goal on its own. ://

**Comment by nox** [comment]
This also needs to integrate with DocumentLoader, which doesn't make things easier.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/7844 and https://github.com/servo/servo/pull/8523 are how we supported cancellation in the old network stack.

**Comment by nox** [comment]
I found a way to do that when implementing `document.open`, and I filed #18671 for the more general issue of not being able to abort a fetch for real.
