### ISSUE TITLE
Images with max-width show up squashed

### ISSUE THREAD

**Issue by jdm** [servo/servo#15249]
```html
<img src="https://raw.githubusercontent.com/deepsyx/home-automation/master/Schematic.png" style="max-width:100%;">
```
This takes forever to appear, and then has full height and very little width.

**Comment by jdm** [comment]
Seen in the wild at https://github.com/deepsyx/home-automation.

**Comment by stshine** [comment]
Wow this picture is big. And it squashes without `max-width`.

@highfive: assign me

**Comment by stshine** [comment]
The problem is that servo fails to parse this image correctly, get 0 width and 0 height.

**Comment by stshine** [comment]
Ignore my previous comment, sorry. It's two `i32` multiplied results an overflow; looking for a clean way to fix this.
