### ISSUE TITLE
Replace quickersort with pdqsort

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#15244]
The [style::stylist] module uses the [quickersort] crate, which provides a fast, unstable sort algorithm.  The new [pdqsort] crate provides an even faster (in almost all cases) unstable sort.  We can easily replace quickersort with pdqsort:

* In the `components/style` directory, update `Cargo.toml`, `lib.rs`, and `stylist.rs` to refer to pdqsort instead of quickersort.
* Build the code.  This should update the `Cargo.lock` file automatically.

[style::stylist]: https://github.com/servo/servo/blob/88cd8a3cf0d299a4dc066059d454fdbc395dbfeb/components/style/stylist.rs#L828-L831
[quickersort]: https://crates.io/crates/quickersort
[pdqsort]: https://crates.io/crates/pdqsort

**Comment by jdm** [comment]
@Maaarcocr would you be interested in working on this?

**Comment by Maaarcocr** [comment]
@jdm It seems like a good start! 
I will work on this, what should I do in case I encounter a problem?

**Comment by jdm** [comment]
Ask questions here or in [#servo](https://wiki.mozilla.org/IRC).

**Comment by hiei23** [comment]
i would like to work on this

**Comment by KiChjang** [comment]
@hiei23 Sorry, this issue has been assigned to someone else.
