### ISSUE TITLE
Add as_void_ptr helper method to &T

### ISSUE THREAD

**Issue by jdm** [servo/servo#15252]
There are lots of places where we write code like `&foo *const _ as *const _` (like [here](https://dxr.mozilla.org/servo/rev/f5c67fda04195bd6d8ef10a73b9158eb60dbd6d7/components/script/dom/browsingcontext.rs#94), [here](https://dxr.mozilla.org/servo/rev/f5c67fda04195bd6d8ef10a73b9158eb60dbd6d7/components/script/dom/bindings/callback.rs#84), and [here](https://dxr.mozilla.org/servo/rev/f5c67fda04195bd6d8ef10a73b9158eb60dbd6d7/components/script/dom/bindings/codegen/CodegenRust.py#3089)) where the receiver code expects a `*const c_void`. This code would be clearer if we could use `foo.as_void_ptr()` where as_void_ptr is a trait method that's implemented for every type T.

**Comment by KiChjang** [comment]
Would the T in this case be `T: DomStruct`? I don't think we can globally define methods for every type yet...

**Comment by jdm** [comment]
We can define a trait and import it everywhere that it's needed.

**Comment by jdm** [comment]
@andrew-x This may also interest you; you would get to learn about Rust traits.

**Comment by KiChjang** [comment]
Ah, I see what this is. Create a trait:
```rust
pub trait AsVoidPtr {
    fn as_void_ptr() -> *const c_void
}
```
And then implementing this trait on every `foo` struct where we use the `&foo as *const _ as *const _` pattern.

**Comment by jdm** [comment]
I'm pretty sure we can implement the trait for a generic type T, rather than specific implementations for types we care about.

**Comment by KiChjang** [comment]
Okay, so more of something like:
```rust
pub trait AsVoidPtr {
    fn as_void_ptr(&self) -> *const c_void;
}

impl<T> AsVoidPtr for T {
    fn as_void_ptr(&self) -> *const c_void {
        self as *const _ as *const _
    }
}
```

**Comment by jdm** [comment]
@chansuke Would you be interested in working on this?

**Comment by jdm** [comment]
@abhiaecs Would you like to work on this?

**Comment by abhiaecs** [comment]
Im definitely interested to work on it

**Comment by abhiaecs** [comment]
Im facing a lot of network issues can i work on this bug once the network
is back (which may take around 5-10 days)? Or can i be assigned a different
bug later on when the network issue is resolved?

**Comment by jdm** [comment]
Sure, leave another comment in #15162 when you're ready and we'll find something new for you.

**Comment by mckaymatt** [comment]
@highfive: assign me

**Comment by mckaymatt** [comment]
@jdm Is this what you are talking about?

```rust
use std::os::raw::c_void;

trait AsVoidPtr {
    fn as_void_ptr(&self) -> *const c_void;
}

impl<T> AsVoidPtr for T {
    fn as_void_ptr(&self) -> *const c_void {
        // &*self as *const _ as *const c_void
        &*self as *const _ as *const c_void
    }
}
```

I'm thinking I would put it someplace like `components/script/lib.rs`? Or maybe it's own crate `components/pointer`. Or `components/script/dom/bindings`?
