### ISSUE TITLE
components/net/ not compiling

### ISSUE THREAD

**Issue by hgallagher1993** [servo/servo#15253]
The problem is with the function `get_placeholder_image` in `image_cache_thread`. Currently there's a call to  `add_image(image.width,
                                            image.height,
                                            None,
                                            format,
data));` with 5 parameters but `add_image` in webrender_traits only expects 2. `pub fn add_image(&self,
                     descriptor: ImageDescriptor,
                     data: ImageData)`

**Comment by jdm** [comment]
The latest version of WR can't be used with servo yet. There's a PR open to address that.

**Comment by hgallagher1993** [comment]
That's cool, do you have the exact PR for me to watch? It's just I've an open PR for webrender that you actually requested changes on but I don't want to commit the changes until I've built it

**Comment by jdm** [comment]
It's https://github.com/servo/servo/pull/15111. There shouldn't be any need to wait on Servo compiling with the changes; the only use of the trait here is [empty](https://dxr.mozilla.org/servo/source/components/compositing/compositor.rs#365), so we'll just need to remove it when updating WR after the changes are merged there.
