### ISSUE TITLE
Font rendering issues on Windows for Hacker News

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#15254]
I tried out a recent nightly for Servo on Windows.  Here's Hacker News:

![hacker_news_servo_win](https://cloud.githubusercontent.com/assets/547158/22353061/972adf22-e483-11e6-946e-8875201cc068.png)

At first blush, I'm seeing kerning issues, fonts being cut off, fonts rendered off the baseline, and text row starting low.

**Comment by emilio** [comment]
Yeah, this is known, font support on windows is a work in progress by @vvuk as far as I know.

**Comment by jdm** [comment]
[Last I heard](https://github.com/servo/servo/issues/12125#issuecomment-272658388) it was supposed to be working better by now.

**Comment by glennw** [comment]
When I last talked to @vvuk about this, it seemed that the Windows font rendering was working (almost) perfectly on some machines, but not at all on others. I don't think we've identified the cause of this yet - is that right @vvuk  ?

**Comment by vvuk** [comment]
That looks like the original brokenness -- did we actually publish a more recent nightly?

**Comment by vvuk** [comment]
Here's HN with a servo debug build I just completed:
![2017-01-27 12_27_56-hacker news - servo](https://cloud.githubusercontent.com/assets/194965/22380632/1b328330-e48c-11e6-8958-0a5153ad074e.png)

**Comment by atouchet** [comment]
Is this still a valid issue? Text looks fine for me in the latest nightly build aside from some spacing issues.

**Comment by jdm** [comment]
Yeah, I think this was the wrong nightly being used.
