### ISSUE TITLE
Shorthand with variable reference should not have extra whitespace after colon for serialization

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15295]
```html
<!DOCTYPE html>
<div style="font:var(--a);"></div>
<script>
alert(document.querySelector('div').style.cssText);
</script>
```

The above code outputs `font: var(--a);` while it should be `font:var(--a);` like what it does for longhands. Otherwise, `cssText` would not be idempotent.

You can see that if the declaration is `font-size:var(--a);`, it would output `font-size:var(--a);` rather than `font-size: var(--a);`.

The relevant code is probably https://github.com/servo/servo/blob/master/components/style/properties/declaration_block.rs#L484-L486

Probably simply need to make this branch do nothing rather than write a whitespace.

**Comment by mdevlamynck** [comment]
I'd like to work on this, do you have any suggestions about how write tests for this and check for side effects ?

**Comment by upsuper** [comment]
I think it is probably good to have a wpt test for this (both shorthand and longhand cases). This is from a recent working group decision (see w3c/csswg-drafts#881) so I expect other engines do not currently do it right.

The test could be just having something in the style attribute, and compare `elem.style.cssText` with the expected output.

@Manishearth, WDYT?

**Comment by jdm** [comment]
Information about creating tests can be found [here](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) and [here](http://testthewebforward.org/docs/testharness-library.html).

**Comment by Manishearth** [comment]
Sounds good to me.
