### ISSUE TITLE
Error compiling 'openssl/hmac.h' not found on Mac OS X

### ISSUE THREAD

**Issue by samuknet** [servo/servo#15293]
Suddenly getting this error when compiling Servo:

```
cargo:warning=src/openssl_shim.c:1:10: fatal error: 'openssl/hmac.h' file not found
cargo:warning=#include <openssl/hmac.h>
cargo:warning=         ^
cargo:warning=1 error generated.
```
I've compiled Servo before but now I am getting this error regardless of what commit I'm on (have tried going back a few commits).

Am running on Mac OS X 10.12.1.

Have tried reinstalling openssl with `brew` and re-adding 
```
export OPENSSL_INCLUDE_DIR="$(brew --prefix openssl)/include"
export OPENSSL_LIB_DIR="$(brew --prefix openssl)/lib"
````

although to no avail.  Have also tried adding these exports to `.profile`, although that didn't help either.

Any ideas?

**Comment by deror1869107** [comment]
Have you tried 
```
$ ./mach clean 
```
and recompile?

I can build servo after installing openssl and doing that on macOS 10.12.3.

**Comment by deror1869107** [comment]
Have you tried 
```
$ ./mach clean 
```
and recompile?

I can build servo after installing openssl and doing that on macOS 10.12.3.

**Comment by samuknet** [comment]
@deror1869107 Yeah, I've tried `./mach clean` aswell as recloning the whole directory, still no luck unfortunately.

**Comment by freeatnet** [comment]
@samuknet What happens if you run `ls $(brew --prefix openssl)/include` or `ls $(brew --prefix openssl)/include/openssl`?

**Comment by samuknet** [comment]
@freeatnet  thanks for your response :) 
Running `ls $(brew --prefix openssl)/include/openssl` shows a bunch of header files, of which `hmac.h` is included.

<img width="659" alt="screen shot 2017-02-01 at 21 53 10" src="https://cloud.githubusercontent.com/assets/9294710/22527946/ff178060-e8c8-11e6-8a39-a58045c00fa6.png">

It's strange how this has suddenly started occurring.  I'm going to try and completely remove any trace of openssl from my machine and re-follow the build steps...

**Comment by lnishan** [comment]
It seems that there's a dependency (which use OpenSSL) that doesn't use `OPENSSL_INCLUDE_DIR` nor `OPENSSL_LIB_DIR` while building.

This issue can be resolved with:

```bash
sudo ln -s /usr/local/opt/openssl/include/openssl /usr/local/include/openssl
sudo ln -s /usr/local/opt/openssl/lib/* /usr/local/lib/
```

**Comment by samuknet** [comment]
That doesn't fix it for me unfortunately.  I think the problem is local to my machine, something to do with my virtual env config.

**Comment by nox** [comment]
@samuknet Did you manage to build it in the end?

**Comment by tadman** [comment]
The solution using from samunket worked for me:

```
export OPENSSL_INCLUDE_DIR="$(brew --prefix openssl)/include"
export OPENSSL_LIB_DIR="$(brew --prefix openssl)/lib"
cargo clean
cargo build
```

**Comment by nox** [comment]
We updated openssl and whatnot since then, AFAIR. Closing.
