### ISSUE TITLE
Determine what data to store on a session history entry

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#15308]
We need to figure out what data we need to store on a session history entry and where to store it (script or constellation). This is needed for things such as the History API or properly reloading documents that have been pruned from the history.

Right now we have:
- timestamp
- url
- pipeline id

As we move forward we need to store things such as:
- origin (possible issues with serialization/mutability)
- request type (GET, POST, etc...)
- history state
- hash change info (probably can be determined from url)
- scroll location

We need to figure out what other data we need to store and the appropriate location for them. Ideally we should reduce managing the same state in multiple places.
cc @asajeffrey

**Comment by jdm** [comment]
This sounds really similar to https://github.com/servo/servo/issues/14888#issuecomment-270952252.

**Comment by cbrewster** [comment]
Ahh indeed! Forgot about that
