### ISSUE TITLE
Implement parsing/serialization for caret-color

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15309]
https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color

The grammar is `auto | <color>`. 

See https://github.com/servo/servo/wiki/Property-hacking-guide for instructions on how to work on such bugs. This bug requires familiarity with Rust.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/ui.mako.rs

**Comment by austinprete** [comment]
I'd like to work on this issue. This will be my first contribution to Servo, if I need help is it best to comment here or to ask on IRC?

**Comment by jdm** [comment]
Whatever is more convenient for you! IRC can sometimes be quicker to respond.

**Comment by austinprete** [comment]
I might be missing something obvious or perhaps I'm not understanding how all the code interacts, (there's a lot of it, and this is my first attempt at really diving in) but it seems like the `auto` keyword will also need to be implemented in `cssparser::Color` similarly to how `currentColor` and `transparent` are. (https://github.com/servo/rust-cssparser/blob/master/src/color.rs#L290) 

Does that sound correct? From the specification listed by @upsuper it sounds like `auto` should essentially just map to `currentColor`, in which case implementing it in `cssparser` would be very simple, but I just want to make sure I'm on the right path before I begin on that.

**Comment by upsuper** [comment]
That's not correct. It should probably be parsed as `Option(Color)` with `auto` being mapped to `Option::None`. Alternatively, you can add a new enum e.g. `AutoOrColor` (although I don't think it's worth).

`auto` should not be mapped to `currentcolor` during parsing or computing. `caret-color` is stored as `StyleComplexColor` in Gecko, and when saving the computed value to Gecko style struct, you should call `StyleComplexColor::auto()`.

Hope I have nothing wrong here. cc @Manishearth

**Comment by Manishearth** [comment]
Yes, that sounds correct. An Option is fine.

**Comment by Manishearth** [comment]
`Either<Color, Auto>` will give you the parsing and serialization code for free.

**Comment by Wafflespeanut** [comment]
Yes, we should use `Either<Color, Auto>` here. The generic can be imported from `components/style/values/mod.rs`

**Comment by austinprete** [comment]
Thank you for the clarification everyone. I've been a bit busy the past couple of days but should have more time to dedicate to this over the weekend, and now I feel somewhat more confident in the direction I need to head with this.

**Comment by Wafflespeanut** [comment]
Great!

**Comment by austinprete** [comment]
I opened a PR for this issue here: https://github.com/servo/servo/pull/15465 However, since this property can be animatable, is there something I need to do additionally for that?

**Comment by Manishearth** [comment]
You need to add an Interpolate implementation. However, I'm not sure how that's supposed to work for types which can be `auto` -- @upsuper the spec says that this is animatable "as a color"; what happens if we try to animate from auto to the color?

**Comment by upsuper** [comment]
It is not interpolatable between auto and color.

**Comment by Manishearth** [comment]
Right, so do you do a discrete animation? At 50% or at 100%?

**Comment by upsuper** [comment]
I think the behavior per spec should be doing flip at 50%, but I'm less sure about Gecko's behavior. IIRC Gecko doesn't match spec on this, and thus I have no idea what Stylo should do. @birtles?

**Comment by birtles** [comment]
Discrete animation flips at 50% (which I think is not very useful, but that's what the spec says).
Gecko does this for CSS Animations but not CSS Transitions (yet). Blink is the same. Also, I think Gecko doesn't do the 50% flip for logical properties yet.

**Comment by austinprete** [comment]
From the discussion above I'm still not sure if there is a conclusion on how I should implement `Interpolate`? Also, once a decision is made about that, are there any resources/examples for how to best implement that trait?

**Comment by Manishearth** [comment]
I guess you can have it flip at 50% -- i.e. if it's between auto and a color, keep it auto till 0.5 and then flip.
