### ISSUE TITLE
Remove MutHeapJSVal

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15316]
https://github.com/servo/rust-mozjs/pull/328 makes it unnecessary. We should be able to replace all users with `Heap<JSVal>`.

**Comment by chansuke** [comment]
I'd like to work on this.

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear.

**Comment by jdm** [comment]
Note that you'll need to remove https://dxr.mozilla.org/servo/source/components/plugins/lints/ban.rs#34-39 as well, and https://dxr.mozilla.org/servo/source/tests/compiletest/plugin/compile-fail/ban.rs which tests it.

**Comment by chansuke** [comment]
@jdm Thank you!!

**Comment by sendilkumarn** [comment]
Is this up for grab ?

**Comment by KiChjang** [comment]
Yes, do you want to work on this?

**Comment by sendilkumarn** [comment]
Yeah

**Comment by chansuke** [comment]
In my understanding, [this](https://github.com/servo/rust-mozjs/pull/328/commits/00956dfbfb3dc713c5a572dcad6937bd9e343657) makes allows interior mutability when we use Heap objects,so no need the part below.

```
/// A holder that provides interior mutability for GC-managed JSVals.
///
/// Must be used in place of traditional interior mutability to ensure proper
/// GC barriers are enforced.
#[must_root]
#[derive(JSTraceable)]
pub struct MutHeapJSVal {
    val: UnsafeCell<Heap<JSVal>>,
}

impl MutHeapJSVal {
    /// Create a new `MutHeapJSVal`.
    pub fn new() -> MutHeapJSVal {
        debug_assert!(thread_state::get().is_script());
        MutHeapJSVal {
            val: UnsafeCell::new(Heap::default()),
        }
    }

    /// Set this `MutHeapJSVal` to the given value, calling write barriers as
    /// appropriate.
    pub fn set(&self, val: JSVal) {
        debug_assert!(thread_state::get().is_script());
        unsafe {
            let cell = self.val.get();
            (*cell).set(val);
        }
    }

    /// Get the value in this `MutHeapJSVal`, calling read barriers as appropriate.
    pub fn get(&self) -> JSVal {
        debug_assert!(thread_state::get().is_script());
        unsafe { (*self.val.get()).get() }
    }

    /// Get the underlying unsafe pointer to the contained value.
    pub unsafe fn get_unsafe(&self) -> *mut JSVal {
        debug_assert!(thread_state::get().is_script());
        (*self.val.get()).get_unsafe()
    }
}
```
Isn't it enough to delete the rest of `MutHeapJSVal`(e.g:"use dom::bindings::js::{JS, Root, MutHeapJSVal};") and replace it into `Heap<JSVal>`?

**Comment by sendilkumarn** [comment]
yeah. got it.

and to replace `MutHeapJSVal::new()` -> `Heap<JSVal>::default()`
