### ISSUE TITLE
Implement parsing/serialization of `grid-auto-flow`

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#15313]
[`grid-auto-flow`](https://drafts.csswg.org/css-grid/#propdef-grid-auto-flow) isn't as easy as implementing a keyword property, because it optionally takes a `dense` keyword along with `row | column`. But, it should be easy enough to write the parsing/serialization code from the existing properties in `components/style/properties/longhands/`. See the [property hacking guide](https://github.com/servo/servo/wiki/Property-hacking-guide) for more information on implementing such properties.

Code: `components/style/properties/longhands/position.mako.rs`

**Comment by galexite** [comment]
Hey! I'd like to take this.

**Comment by jdm** [comment]
Please do! Ask questions if anything is unclear.

**Comment by galexite** [comment]
Thanks, @jdm!

**Comment by galexite** [comment]
I followed text-decoration's implementation for inspiration.

**Comment by galexite** [comment]
(I'm georgewhite on IRC, by the way)
