### ISSUE TITLE
Box larger specified values to avoid memmove impact

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15322]
Currently, `PropertyDeclaration` is pretty large. This is because it has some huge variants, many of which don't get used too often. This means that things like moving the `PropertyDeclaration` are now actually expensive operations.

Here is the list of inline sizes currently in play: https://github.com/servo/servo/pull/15065#issuecomment-273038986 . We have tons of huge ones. On the other hand, nsCSSValue (gecko's specified value type) is a 16-byte struct.

It's worth boxing all but the smallest ones here. At the very least, anything above 40 bytes (we can reduce this later).

Would be nice if we could just annotate the mako templates with a parameter that autoboxes it (alternatively, lets you opt out of the boxing). Basically, make it use `DeclaredValue<Box<SpecifiedValue>>` in each variant.

cc @canaltinova

**Comment by canaltinova** [comment]
I'm working on this.

**Comment by bholley** [comment]
Awesome - thanks Nazim!
