### ISSUE TITLE
Avoid calling deduplicate in the common case of no deduplications.

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15320]
We have a function, [`deduplicate_property_declarations()`](https://github.com/servo/servo/blob/77f53aae3eee59957521ea76e95bd3e454c4ddd9/components/style/properties/properties.mako.rs#L331), which takes a property declaration block and removes declarations shadowed by newer or `!important` declarations. Currently, it unconditionally will copy all the property declarations into a new vector. We should reduce the number of times we have to do this.

It might be worth making [`PropertyDeclaration::parse()`](https://github.com/servo/servo/blob/77f53aae3eee59957521ea76e95bd3e454c4ddd9/components/style/properties/properties.mako.rs#L997) take in an additional `&mut PropertyBitField` bitfield argument and a `&mut bool`. It will use the bitfield to keep track of already-parsed properties, and set the bool to true if it finds a collision. Only when we have a collision do we call deduplicate. I'm not sure if this will improve the performance of this function, but it's worth a try.

**Comment by rwakulszowa** [comment]
Hey,
I'd like to work on this one.
I'll take a closer look at the code and start asking questions then :)
I have one question now though: is there any standard way to measure performance improvement?

**Comment by bholley** [comment]
A couple of possibilities, in order of likely difficulty:
* You can use a profiler for your OS (like Instruments on macos) and measure the time spent in StyleSheet::update_from_str, or in deduplicate_property_declarations
* You can instrument those same functions with manual time measurement code that just sums up the time spent in those functions.
* You can do a Stylo (Servo style system in Gecko) build, and use Gecko's built-in profiler (this is how I took the measurements in [1])

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1331843

**Comment by rwakulszowa** [comment]
Ok, I've got some questions:
- Adding two params to `PropertyDeclaration::parse()` will force some parsers, like the [Keyframe one](https://github.com/servo/servo/blob/77f53aae3eee59957521ea76e95bd3e454c4ddd9/components/style/keyframes.rs#L407) to create the bitvector for duplication checking, although it doesn't really need to check for duplicates, which may make the code confusing
- Wouldn't it be easier / better to just add the collision check inside the [parse_property_declaration_list()](https://github.com/servo/servo/blob/77f53aae3eee59957521ea76e95bd3e454c4ddd9/components/style/properties/declaration_block.rs#L612) based on `block.declarations` and only call `deduplicate...` if necessary? Or maybe it should be a method of a `PropertyDeclarationBlock`?
- My suggestions are based on an assumption that this is the only case where we care about deduplication, correct me if I'm wrong here

**Comment by Manishearth** [comment]
There are many things being done in the PD parser that aren't used by all callers, so this shouldn't be a blocker.

The reason we can't do it in parse_property_declaration_list is that we need to iterate all over again, and also branch based on property names (which is bad for perf and code size)

We might actually care about duplications in keyframes too, but not have code for that. I'll have to look into it.

**Comment by rwakulszowa** [comment]
What about `Custom` properties? If I understand correctly, we can't rely on a `PropertyBitField`, since it won't tell us about Custom duplicates. We would need to add another vector/set for Custom names, but that seems like an overkill. Or we could make the boolean indicate when parser detects a duplicate or any `Custom` value - is no-duplicates, no-custom-properties a common case?
Maybe there is a way to refactor the [deduplicate_property_declarations](https://github.com/servo/servo/blob/77f53aae3eee59957521ea76e95bd3e454c4ddd9/components/style/properties/properties.mako.rs#L331) to make an early exit if no duplicates are detected? Are there any additional properties of the `declarations` vec we could rely on?

**Comment by Manishearth** [comment]
Yeah, no duplicates, no custom properties is the common case.

**Comment by Manishearth** [comment]
You could also use a vector to track if custom props are being used, which would be a code path that only gets hit when you encounter one in the first place, so it's fine to do that too.

**Comment by rwakulszowa** [comment]
I've decided to use a single flag to be set if a duplicate or if any custom property is found.

I wrote 3 tests:
- 2 for the flag checking and 
- 1 for `parse_property_declaration_list` - this one would have passed before, but I haven't found a test for this function, so I added a new one

**Comment by rwakulszowa** [comment]
Oh, I forgot to mention the performance gain.
I've ran some (really) simple tests on `parse_property_declaration_list` - 7 simple properties with no duplicates. It seems to be a bit faster now (from 250k ns to 200k ns on average), but the variance is quite large. I'd say it is better, but obviously I may be doing something wrong.

**Comment by siddhanathan** [comment]
Please add the assigned label to this bug.

**Comment by rwakulszowa** [comment]
I believe this issue can be closed - deduplication will be removed (#15558)

**Comment by SimonSapin** [comment]
Closing in favor of #15558. (See discussion there.)
