### ISSUE TITLE
border-image-slice should not accept negative percentage

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15339]
We need to add `Percentage::parse_non_negative` and make `border-image-slice` use it.

**Comment by jdm** [comment]
Does this sound interesting @josephfu1994? It requires creating a unit test in `tests/unit/style/parsing/` that verifies that parsing a border-image-slice property with a negative percentage does not work. It then requires updating the parsing code in `components/style/properties/longhands/border.mako.rs` to make the test pass.

**Comment by josephfu1994** [comment]
@jdm Yes, this works for me. Thanks.
I would like to take this issue if no one is on it.

**Comment by upsuper** [comment]
@josephfu1994 ping, any progress or question here?

**Comment by upsuper** [comment]
Seems to be fixed by #16142.
