### ISSUE TITLE
Serialization of specified font-weight should preserve keyword values

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15337]
The following code would show `bold` in all other browsers, but Servo shows `700`:
```html
<!DOCTYPE html>
<div style="font-weight: bold"></div>
<script>
  alert(document.querySelector('div').style.fontWeight);
</script>
```

Servo should preserve the keywords until computed value time, which means the `SpecifiedValue` enum should include those keywords instead of only weights.

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/longhand/font.mako.rs#L200-L230

**Comment by atheed** [comment]
I'd like to claim this, if I may.

**Comment by jdm** [comment]
Please do :)
