### ISSUE TITLE
Event handlers forwarded to a window should check for the presence of a window

### ISSUE THREAD

**Issue by jdm** [servo/servo#15332]
From https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-idl-attributes:
```
If an event handler IDL attribute exposes an event handler of an object that doesn't exist, it must always return null on getting and must do nothing on setting.

This can happen in particular for event handler IDL attribute on body elements that do not have corresponding Window objects.
```
Our implementation of `define_window_owned_event_handler` does not check whether it's part of an element that is in a document that has a browsing context, and it should. This JS behaves differently in Servo vs. other browsers:
```html
<script>
var d = (new DOMParser).parseFromString('', 'text/html');
var b = d.createElement('body');
b.onload = function() {};
console.log(b.onload);
</script>
```
In Servo it logs `function() {}`, in other browsers it logs `null`.

Code: `components/script/dom/macros.rs`
Test: We should [create a test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) in `tests/wpt/web-platform-tests/html/webappapis/scripting/events/` that verifies this behaviour.

**Comment by freeatnet** [comment]
@jdm I'm a newbie at Rust (and Servo), so I'm currently assessing if this is something I can take on.
It says the code is located in [components/script/dom/macros.rs](/servo/servo/blob/master/components/script/dom/macros.rs); however, it looks to me like the `onload` handler mentioned in the test appears to in [components/script/dom/htmlelement.rs](/servo/servo/blob/master/components/script/dom/htmlelement.rs) instead (`Get`-/`SetOnload`). Am I missing something?

**Comment by jdm** [comment]
@freeatnet That's the load handler for elements that own their own handler. The handlers on the body element delegate to the window, so they are declared via the `window_event_handlers` macro at https://dxr.mozilla.org/servo/rev/da89099e26955cf5ba44031a0a536e3af4e6a0d5/components/script/dom/htmlbodyelement.rs#82.

**Comment by jdm** [comment]
```
<freeatnet> jdm, hey, re: github.com/servo/servo/issues/15332#issuecomment-277072296: I've figured that part out; however, I don't see onload in ForwardToWindow at github.com/servo/servo/blob/master…mponents/script/dom/macros.rs#L499; should it be added there?
```
Good point! This turns out to be slightly more convoluted than I remembered; you're right that Get/SetOnload in `htmlelement.rs` is the code that is responsible here.

**Comment by jdm** [comment]
For the _other_ event listeners that only appear in the ForwardToWindow branch, we also need to make a similar change as I originally thought.

**Comment by freeatnet** [comment]
@jdm I submitted #15359 ahead of claiming this, sorry. If my PR isn't entirely off base, I would like to take this on further.
