### ISSUE TITLE
<single-timing-function> value should reject out-of-range values in functions

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15344]
Specifically, for `cubic-bezier` function, the x values (first and third number) must be in [0, 1], and for `steps` value, the number must be positive (>=1). Functions with out-of-range value should be treated as invalid.

Spec: https://drafts.csswg.org/css-timing-1/#single-timing-function-production

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs#L584-L617

**Comment by AdmiralCoco** [comment]
Hello, I would like to work on this issue.

**Comment by upsuper** [comment]
Great. Feel free to ask questions if there is anything unclear.

**Comment by Wafflespeanut** [comment]
@AdmiralCoco Did you look into this?

**Comment by AdmiralCoco** [comment]
Hi @Wafflespeanut, I haven't had a chance to take a deep look at it, but I plan to work on it over the weekend and have a PR soon.

**Comment by Wafflespeanut** [comment]
Awesome!

**Comment by AdmiralCoco** [comment]
Hello again @Wafflespeanut, I wrote a few lines to check for the ranges - it looks like this, from the relevant part of code  - I wanted to check if I understood the issue correctly.

```Rust
"cubic-bezier" => {
    try!() {
        //parse
        p1x = ...
        p2x = ...
    }));
    if (p1x < 0.0 || p1x > 1.0 ) || (p2x < 0.0 || p2x > 1.0)  {
         // handle invalid range - return Err(()) ?
    }
},
"steps" => {
    try!() {
        //parse
        if step_count < 1{ 
            // return Err(())
        }
    }
}
```
Is checking for the values after they are all parsed a valid approach?

I also have a question about this part of the issue:
> Functions with out-of-range value should be treated as invalid

Does this mean we should error out as written above?

Finally, I did some searching for tests and have found some [here](https://github.com/servo/servo/blob/496447a363ca4fc5d6789241ccb0b94134917b9a/tests/wpt/css-tests/css-transitions-1_dev/html/transition-timing-function-001.htm#L77) and [here](https://github.com/servo/servo/blob/234951e4b6d66891cd0cc9705f42e3ca16d9e3d5/tests/wpt/web-platform-tests/web-animations/resources/effect-easing-tests.js#L73) - I am wondering if additional tests are necessary.
This is my first time working in servo/Rust, and I am still catching up - thanks a lot for the help.

**Comment by Wafflespeanut** [comment]
> Is checking for the values after they are all parsed a valid approach?

Yep, that's the way. We'll improve on this once you open the PR :)

> Does this mean we should error out as written above?

You're right.

> I am wondering if additional tests are necessary.

We should probably add some unit tests. You can find existing ones in `tests/unit/style/`
