### ISSUE TITLE
Serialization of specified length and time value should perserve their original unit

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15346]
e.g. `width: 1in` should be serialized as `1in` rather than `96px`. The units should dropped during computing, not parsing.

(I'm not sure whether we have a spec for this behavior... but this behavior seems to match all major browsers. Probably worth a spec issue.)

**Comment by dpyro** [comment]
Ok, I will do this!

**Comment by emilio** [comment]
Hi @dpyro, did you manage to make any progress on this?

**Comment by dpyro** [comment]
Nope @emilio, I am not able to do it right now. Please unassign me. Hopefully I will be able to contribute again later!

**Comment by emilio** [comment]
No worries, and thanks for replying!

**Comment by upsuper** [comment]
This is still a problem for time unit.

**Comment by emilio** [comment]
@luisbg, you mentioned you were interested on stylo, would you like to take this one?

**Comment by luisbg** [comment]
@emilio sure! I am currently traveling for work but I can start looking into this issue on Sunday.

Any advice on how to reproduce this bug?

**Comment by upsuper** [comment]
```html
<!DOCTYPE html>
<style>
div { animation-delay: 1ms; }
</style>
<script>
alert(document.styleSheets[0].cssRules[0].style.animationDelay);
</script>
```

Other browsers show "1ms", while Stylo and Servo would show "0.001s".

**Comment by luisbg** [comment]
@upsuper I just reproduced it, thanks for sharing. Will investigate soon.

**Comment by upsuper** [comment]
I think what you basically need to do is to extend [`values::specified::Time`](https://github.com/servo/servo/blob/7682de499ce6c7f473c8f2744c4c327a2e6eda73/components/style/values/specified/mod.rs#L559-L565) to include the original unit, rather than converting to seconds directly.

**Comment by canaltinova** [comment]
@luisbg Hi! Have you made any progress here? Is there anything that we can help?

**Comment by luisbg** [comment]
@canaltinova Hi! I got very busy at work. But I think I will have time this weekend to play with this code and figure out a solution.

Apologies for the delay. Give me a few more days and if not somebody else can take it :smile: 

Thanks for offering to help

**Comment by canaltinova** [comment]
@luisbg No problem, thanks for letting us know. You can ping me or probably other team members on IRC if you need to ask anything!
