### ISSUE TITLE
transition-duration should not accept negative time value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15343]
Spec: https://drafts.csswg.org/css-transitions/#transition-duration-property

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs#L465

We probably need `Time::parse_non_negative` as well.

**Comment by jdm** [comment]
@simon-whitehead Does this look interesting? It involves a unit test in `tests/unit/style/parsing/` that verifies that parsing a transition-duration property with a negative time value is not allowed, and modifying the parsing code to make the test pass. The tests can be run with `./mach test-unit -p style`.

**Comment by simon-whitehead** [comment]
Yes it does @jdm. There is some interesting markup scattered through this file though which I am not familiar with. Do you have resources for this? Looks good otherwise - happy to have a go at it!

**Comment by jdm** [comment]
It's a [mako template](http://www.makotemplates.org/), so it's a python-based templating language.

**Comment by simon-whitehead** [comment]
Great thanks. Good to know just so I don't break anything :) I'll get started on this tonight hopefully!

**Comment by simon-whitehead** [comment]
I will get to this in the next few days - I've just had a busy week transitioning between day jobs. Sorry for the delay!

**Comment by simon-whitehead** [comment]
Just to clarify, should I be implementing `parse_non_negative` in the PR as well. If so, should it error on positive values? @jdm @upsuper

**Comment by upsuper** [comment]
I think you should implement `parse_non_negative` rather than altering `parse`, since there are properties which do accept negative time values (e.g. `transition-delay`).

**Comment by simon-whitehead** [comment]
Sure, but the `parse` method is implemented on the `transition-duration` "type" (still trying to wrap my head around what to call these types that are declared via the mako template). Changing the logic in the specific function you linked to in the original post shouldn't change anything other than `transition-duration`, should it?

**Comment by upsuper** [comment]
Oh, you mean that one. I thought you are talking about `Time::parse`. I think the better solution would be implement a `Time::parse_non_negative` and make `transition-duration`'s `parse` use it. There are other properties which may need to parse non-negative time as well, e.g. `animation-duration`.

**Comment by simon-whitehead** [comment]
Great. That sounda like a better idea. Thanks!
