### ISSUE TITLE
border-radius and -moz-outline-radius shorthand should not accept negative values

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15345]
Spec: https://drafts.csswg.org/css-backgrounds-3/#the-border-radius

Relevant code: https://github.com/servo/servo/blob/master/components/style/values/specified/basic_shape.rs#L751-L769

Although border-radius longhands have already rejected negative values, it seems the shorthand bypasses the check.

After fixing this, I guess we want to add a check in the two constructors of `BorderRadiusSize` to ensure that we always pass non-negative values there.

**Comment by Lyjame** [comment]
Hi, I would like to work on this issue. Thanks!

**Comment by upsuper** [comment]
Great! Feel free to ask questions if there is anything unclear.

**Comment by karan1276** [comment]
Correct me if i am wrong, (this line)[https://github.com/servo/servo/blob/master/components/style/values/specified/basic_shape.rs#L755] is true if it is a short hand i.e. `parse_one_set_of_border_values` will be called for short hand parse ?

**Comment by Wafflespeanut** [comment]
You're right! :)

**Comment by karan1276** [comment]
@Wafflespeanut  thanks!

**Comment by karan1276** [comment]
I know this issue is already assigned, If @Lyjame  is still working on it feel free to close the PR.

Otherwise, please review it :)

**Comment by jdm** [comment]
I went ahead and closed the PR. Please ask first before working on issues that have already been assigned to somebody else in the future!

**Comment by upsuper** [comment]
`-moz-outline-radius` should probably be covered in the same issue.

**Comment by dcci** [comment]
@Lyjame Are you still working on this one?

**Comment by Lyjame** [comment]
No I thought that this PR was closed? Looking for another issue now :)

**Comment by upsuper** [comment]
@Lyjame, the PR from @karan1276 was closed because we thought you may still be working on this. If you are not working on it, I'll release this issue so that other people can take and work on. Are you fine with that, or are you going to continue working on this one?

**Comment by Lyjame** [comment]
@upsuper You can release it. Next time I look for an issue I'll fix it on a day much closer to when I reserve it. Sorry about that.

**Comment by Iakis** [comment]
Hello, I would like to work on this, I have limited experience with rust and itll be my first bug but would like to attempt to contribute

**Comment by Wafflespeanut** [comment]
Great!

**Comment by jdm** [comment]
@lakis Have you made any progress here?

**Comment by Iakis** [comment]
@jdm Hi sorry for the lack of updates, I currently have a solution im pretty confident in but Im having trouble setting up tests. Also, if i could just ask for clarification on what should be done when i "reject" the negative values.

**Comment by Wafflespeanut** [comment]
Negative values are supposed to return an `Err(())` just like any other CSS parse error anywhere.

**Comment by Iakis** [comment]
thanks for the reply! Im having trouble figuring out how to test it, ive read through the servo readme and quickstart guides, following the debugging instructions just opens visual studio but Im not too sure what to do,  is there another document i could refer to?

**Comment by Wafflespeanut** [comment]
We generally add unit tests for cases like this, and they all live in `tests/unit/style`. Please have a look at the existing parse tests, which will give you an idea about how they work. Finally, `./mach test-unit -p style` will make sure that the tests don't fail.

**Comment by Iakis** [comment]
Hello, I just opened up a pull request, I believe this should fix the problem. Thank you very much for helping me through my first bug
