### ISSUE TITLE
Rewrite WebVR code to use high level typed array APIs

### ISSUE THREAD

**Issue by jdm** [servo/servo#15350]
The WebVR code uses `slice_to_array_buffer_view` and the `ArrayBufferViewContents` trait. It should be rewritten to use the typed array APIs from https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs instead.

Blocks #14672.

**Comment by jdm** [comment]
@deror1869107 You might be interested in this, given your experience in #14676.

**Comment by deror1869107** [comment]
@jdm I can work on it!

**Comment by deror1869107** [comment]
I can use ```TypedArray<T>::create``` to instead of ```slice_to_array_buffer_view<T>```.

Should I have to write ```TypedArray<T>::update(obj: *mut JSObject, data: &[T])``` for TypedArray?

**Comment by jdm** [comment]
Yes, I think it makes sense to add a new API To TypedArray. It should panic if the length of the new data does not match that length of the array buffer's data.

**Comment by deror1869107** [comment]
Inorder to update the typedarrays, I have the code like ```typedarray!(in(cx) let left_proj_array: Float32Array = self.left_proj.get());``` in [VRFrameData::update](https://github.com/servo/servo/blob/master/components/script/dom/vrframedata.rs#L73).

But I have no cx in this scope, how can I get one?

**Comment by jdm** [comment]
Yes, that's fine.
