### ISSUE TITLE
Intermittent FAIL in /html/dom/dynamic-markup-insertion/document-write/iframe_005.html

### ISSUE THREAD

**Issue by wafflespeanut** [servo/servo#15377]
▶ Unexpected subtest result in /html/dom/dynamic-markup-insertion/document-write/iframe_005.html:
      │ FAIL [expected PASS] document.write external script into iframe write back into parent
      │   → assert_array_equals: lengths differ, expected 5 got 2
      │ 
      │ @http://web-platform.test:8000/html/dom/dynamic-markup-insertion/document-write/iframe_005.html:20:7
      │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
      └ @http://web-platform.test:8000/html/dom/dynamic-markup-insertion/document-write/iframe_005.html:19:5

**Comment by jdm** [comment]
cc @nox

**Comment by nox** [comment]
We don't handle delaying the load event for iframes correctly.

**Comment by nox** [comment]
This is quite weird. I don't understand how can the load event handler see only 2 items in `order`, given everything happens sequentially in that test.

**Comment by nox** [comment]
@jdm I can't reproduce it if I run only that test, and I can't log to a file the complete logs without color escape sequences when I reproduce it by running all the `document-write` tests through `./mach test-wpt`. What is the magical test-wpt command to have a log file that is actually useful and human-readable?

**Comment by jdm** [comment]
I haven't encountered that problem before. You're blazing new trails!

**Comment by nox** [comment]
I managed to log without the weird escape sequences, but now I have another problem. How can I use `RUST_LOG` with some `debug` levels in a release build? I have 0% reproducibility with debug.
