### ISSUE TITLE
Make await_stable_state use microtasks

### ISSUE THREAD

**Issue by jdm** [servo/servo#15375]
https://html.spec.whatwg.org/multipage/webappapis.html#await-a-stable-state and https://dxr.mozilla.org/servo/rev/da89099e26955cf5ba44031a0a536e3af4e6a0d5/components/script/script_thread.rs#595 do not match.

**Comment by KiChjang** [comment]
If I'm reading correctly, the only change here is to change the function from using `script_thread.chan` to queue a Runnable to instead use the microtask task source?

**Comment by jdm** [comment]
No such thing as a microtask task source in our implementation, but yes, it looks like enqueuing a microtask that invokes the given runnable should be enough.
