### ISSUE TITLE
Build the Linux version of Servo on a CentOS 7.x host as opposed to what you're using right now

### ISSUE THREAD

**Issue by birdie-github** [servo/servo#15385]
I cannot test servo in CentOS/ScientificOS/RHEL 7.0 because you require too fresh glibc and ssl libraries:

```
$ ./servo
./servo: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./servo)
./servo: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
./servo: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.1d' not found (required by ./servo)
./servo: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
```

Please downgrade your build host(s).

Please don't offer to use `LD_PRELOAD`: it doesn't work for glibc.

In a perfect world I'd ask you to build servo on CentOS 6.x for maximum compatibility but I guess it's too much to ask.

CentOS 7.0 does contain LLVM and Clang:
```
Name        : clang
Arch        : x86_64
Version     : 3.4.2
Release     : 8.el7
Size        : 19 M
Repo        : epel/x86_64
Summary     : A C language family front-end for LLVM
URL         : http://llvm.org/
License     : NCSA
Description : clang: noun
            :     1. A loud, resonant, metallic sound.
            :     2. The strident call of a crane or goose.
            :     3. C-language family front-end toolkit.
            :
            : The goal of the Clang project is to create a new C, C++, Objective C
            : and Objective C++ front-end for the LLVM compiler. Its tools are built
            : as libraries and designed to be loosely-coupled and extensible.

Name        : llvm
Arch        : x86_64
Version     : 3.4.2
Release     : 8.el7
Size        : 1.3 M
Repo        : epel/x86_64
Summary     : The Low Level Virtual Machine
URL         : http://llvm.org/
License     : NCSA
Description : LLVM is a compiler infrastructure designed for compile-time,
            : link-time, runtime, and idle-time optimization of programs from
            : arbitrary programming languages.  The compiler infrastructure includes
            : mirror sets of programming tools as well as libraries with equivalent
            : functionality.
```

**Comment by jdm** [comment]
The SSL part of this is covered by #12015. I don't know if we have an issue tracking glibc.

**Comment by larsbergstrom** [comment]
We've traditionally found that trying to build against a specific and older version of GLIBC has required us to run our tests on machines that are not the same configuration used by the core development team, meaning that e.g., they don't know how to edit the machine scripts to add new dependencies or test an OS-specific failure (though in this case, it'd "just" be the nightly build machine).

According to https://www.gnu.org/software/libc/, GLIBC 2.18 is from August of 2013, or nearly four years ago. That seems quite old and further, unless you are picking up backported CVEs, a bit scary (e.g., the `getaddrinfo` vuln from last year).

I'm unfortunately still inclined to continue to encourage people with extremely old system libraries to build a version of Servo for their testing usage from source.
