### ISSUE TITLE
web.basemark.com won't start, no error shown

### ISSUE THREAD

**Issue by Pryx** [servo/servo#15392]
Tested current master, built and tested with both release and debug option on Arch Linux.

When you go to [web.basemark.com](http://web.basemark.com) and click start, Servo shows white screen and nothing happens. Interestingly enough no error is shown.

**Comment by jdm** [comment]
When I run it I see "Could not load the requested page: connection reset".

**Comment by jdm** [comment]
`curl https://web.basemark.com` shows me the page source. When I `cargo install` the rural and rget crates (which are based on `reqwest` and rely on `hyper`, like Servo), both of those tools take over a minute to retrieve the page source. Something very strange is going on.

**Comment by nox** [comment]
@jdm I can't reproduce your issue anymore.

**Comment by atouchet** [comment]
I am able to start and complete the benchmark using a recent nightly build.

![Screenshot](https://user-images.githubusercontent.com/26315797/84837551-43edf680-afed-11ea-8aaf-22886f85bc95.png)

**Comment by jdm** [comment]
Looks like we can close it, then!
