### ISSUE TITLE
Name of custom properties are not properly escaped when serializing

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15399]
See the following test code:
```html
<!DOCTYPE html>
<p style="--weird\;name: green">hello</p>
<script>
  alert(document.querySelector('p').style.cssText);
</script>
```

Servo currently shows `--weird;name: green;` which is wrong, because it is invalid. The name should be escaped so the result should be `--weird\;name: green;`.

Blink seems to have the same issue, so it's worth a new test in wpt.

**Comment by heycam** [comment]
Fixed by #16691.
