### ISSUE TITLE
Serialization of animation and transition shorthand is wrong

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15398]
Each longhand of animation shorthand is a list, and `animation` shorthand should be serializable only when all the lists have the same length. And the serialization should be a list of each animation, rather than a list of lists for each longhand.

For example,
```css
animation-name: bounce, roll;
animation-duration: 1s, 200ms;
animation-timing-function: ease-in, linear;
animation-delay: 0s, 1s;
animation-direction: normal, reverse;
animation-fill-mode: forwards, backwards;
animation-iteration-count: infinite, 2;
animation-play-state: paused, running;
```
should be serialized to something like
```css
animation: 1s ease-in 0s normal forwards infinite paused bounce, 200ms linear 1s reverse backwards 2 running roll;
```
not
```css
animation: 1s, 200ms ease-in, linear 0s, 1s normal, reverse forwards, backwards infinite, 2 paused, running bounce, roll;
```

The relevant code is https://github.com/servo/servo/blob/master/components/style/properties/shorthand/box.mako.rs#L310-L335

(Maybe an easy issue? cc @Manishearth)

**Comment by upsuper** [comment]
The same issue applies to `transition` shorthand as well. The relevant code is https://github.com/servo/servo/blob/master/components/style/properties/shorthand/box.mako.rs#L171-L182

**Comment by Manishearth** [comment]
I guess the value should be cycled like we do for background?

**Comment by upsuper** [comment]
They should be cycled in computation, but serialization of specified value should be empty if the lengths don't match.

Your comment makes me think that our serialization code of `background` shorthand is wrong as well, e.g.
```css
background: none, url(404.png);
background-repeat: repeat-x, repeat-y, no-repeat;
```
is different as
```css
background: none, url(404.png), none;
background-repeat: repeat-x, repeat-y, no-repeat;
```

**Comment by upsuper** [comment]
Oh, hmmm, let me check first :/ I'm not completely familiar with the rules here.

**Comment by upsuper** [comment]
For computation, the value should be cycled, but for serialization of specified value, it should just return empty if the list lengths don't match each other. The same thing applies to `background`. So our `background` serialization code is wrong as well.

Gecko and Edge agree on the behavior I described above. Blink always does serialization but omits the deficient parts in the shorthand serialization, which is apparently wrong, because that's not idempotent.

**Comment by Manishearth** [comment]
@KiChjang @canaltinova @Wafflespeanut  want to look at this?

**Comment by Manishearth** [comment]
(not sure if this is easy; with extra mentoring i think it could be -- feel free to retag and mentor if you feel like that's the case)

**Comment by upsuper** [comment]
(The same issue of `background` shorthand applies to `background-position` shorthand as well, fwiw.)

**Comment by Wafflespeanut** [comment]
This might be a good second/third bug (I wouldn't particularly encourage this as a first bug though). They're all values in vectors. As Manish said, we should cycle through the longhand values in a loop, `get` the values for serialization and `break` when all the values are `None`. I can mentor this.

**Comment by upsuper** [comment]
No, we should not cycle through the longhand values. We should simply return empty if the lengths do not match.

**Comment by Wafflespeanut** [comment]
Oh cool.

**Comment by absoludity** [comment]
This *seems* to be unassigned - though I'm not sure if people are intending on grabbing it? I'm assigning to me, but I won't be put out if you're already working on it and want to unassign me :) @highfive: assign me

**Comment by upsuper** [comment]
You're right that it was not assigned. Thanks for working on this.

**Comment by upsuper** [comment]
Transition shorthand is not fixed yet.
