### ISSUE TITLE
Border shorthand incorrectly serializes when sides are not identical

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15395]
The relevant code is: https://github.com/servo/servo/blob/master/components/style/properties/shorthand/border.mako.rs#L134-L143

The comment says "If all longhands are all present, then all sides should be the same"... which is apparently false.

One can have code like `border: 3px solid green; border-left-width: 2px;` where all longhands are present, but some sides have different values.

The corresponding code should check whether all sides are identical before generating the serialization.

**Comment by upsuper** [comment]
Test code:
```html
<!DOCTYPE html>
<p style="border: 3px solid green; border-left-width: 2px;"></p>
<script>
  alert(document.querySelector('p').style.border);
</script>
```

**Comment by karlding** [comment]
I'm a newbie at Rust, but I'd like to try taking a stab at this!

Essentially, the output should only be the properties that are common between all 4 sides, right?

@highfive: assign me

**Comment by upsuper** [comment]
The output should be empty if there is anything different between the four sides. It should output something only if all four sides are completely identical in style, color, and width.

**Comment by karlding** [comment]
Alright, sounds good! Also, I don't think I saw any (unit) tests associated with this in the repo. Did I miss that, or is that covered elsewhere?

**Comment by upsuper** [comment]
I guess you're right that there is no test for this, otherwise we should have know this earlier :)

Could you add some tests for this with your pull request?

**Comment by karlding** [comment]
Sure!

Also, I noticed in ``data.py``, ``PHYSICAL_SIDES`` is defined, but in ``border.mako.rs``, it seems like there is a preference for writing out ``["top", "right", "bottom", "left"]``. Is there a reason why this isn't used?

**Comment by upsuper** [comment]
I think it's fine either way. It is probably simply because the code in `border.mako.rs` predates `PHYSICAL_SIDES`.
