### ISSUE TITLE
Check if Azure can be used off the main thread

### ISSUE THREAD

**Issue by jdm** [servo/servo#15407]
I just came across https://bugzilla.mozilla.org/show_bug.cgi?id=801176#c139 which says "So just to be clear. It -does not- matter whether a DrawTarget is or is -not- shared across multiple threads, a DrawTarget -cannot- be used -off the main thread- -ever-, currently." Since we create and use draw targets in separate threads for each 2d canvas, this sounds pretty bad!

**Comment by jdm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1264023 looks relevant.

**Comment by SimonSapin** [comment]
@nical, do you know about this?

**Comment by nical** [comment]
Yeah, basically Moz2D and (some of) its underlying backends have global caches that aren't safe to access from multiple threads. So you should define a thread that can use Moz2D and not use Moz2D elsewhere. It could be that the skia backend is less troublesome than the cairo/d2d ones, although if you are using freetype under the hood there's most likely work to do to make sure skia uses it in a threadsafe way which I think is not the default.

Skia itself should be thread-safe if you are careful about not sharing the objects. Our in-tree version of cairo is definitely not thread safe (more recent versions of cairo are but we don't use that in gecko).
So assuming you use the skia backend, don't share any data between the different threads and have fonts set up properly, One would still need to go through the Moz2D code to see where these global caches and other sources of thread-unsafety are, and whether they affect the skia backend.

If this is only about servo using a thread per canvas, it's probably a good time to multiplex that all into one thread. As long as you only have canvas rendering on that thread I believe you don't gain much from having a thread per canvas.

**Comment by jdm** [comment]
Probably one reason we haven't hit problems is that our canvases don't support text yet, so we don't do any font interactions.

**Comment by nox** [comment]
Is this still something we need to do? I'm not sure what's the long term plan with Azure.

**Comment by jdm** [comment]
For offscreen canvas it may be a necessity.

**Comment by dralley** [comment]
The Azure backend was recently removed https://github.com/servo/servo/pull/25841/files

**Comment by jdm** [comment]
Yep.
