### ISSUE TITLE
Use the entry settings object in CanvasRenderingContext2d::is_origin_clean

### ISSUE THREAD

**Issue by jdm** [servo/servo#15409]
We recently gained support for [GlobalScope::entry](http://doc.servo.org/script/dom/globalscope/struct.GlobalScope.html#method.entry), so we can use it to fix the TODO in this method.

Code: `components/script/dom/canvasrenderingcontext2d.rs`
Test: Try running `./mach test-wpt tests/wpt/web-platform-tests/2dcontext/` and see if any unexpected results appear.

**Comment by Ms2ger** [comment]
Note that the origin of an image element is not the origin of its URL; see <https://html.spec.whatwg.org/multipage/browsers.html#concept-origin>, <https://html.spec.whatwg.org/multipage/embedded-content.html#img-req-data> and <https://html.spec.whatwg.org/multipage/embedded-content.html#updating-the-image-data:img-req-data-2>. I'm not sure we can implement that part without #14962.

**Comment by jdm** [comment]
True. Let's put this on hold until then.

**Comment by sendilkumarn** [comment]
since #14962 is closed. 
we can now check against 
```rs
GlobalScope::entry().get_url().origin()
```
I will give this a shot.

**Comment by Ms2ger** [comment]
Note, again, that the origin of an image element is not the origin of its URL.

**Comment by sendilkumarn** [comment]
I have a doubt, can we decide `same/cross-origin` via `config attribute` of an `image` ?

**Comment by sendilkumarn** [comment]
Addressed that issue. so now based on cors-origin type the check is made.
