### ISSUE TITLE
Notify global object about rejected promises

### ISSUE THREAD

**Issue by jdm** [servo/servo#15412]
As part of the [microtask checkpoint](https://dxr.mozilla.org/servo/rev/fb4f421c8b9cbf80a86c9c5eb88395d7008b27a1/components/script/microtask.rs#78), we should be implementing the global [unhandledrejection event](https://html.spec.whatwg.org/multipage/webappapis.html#notify-about-rejected-promises).

**Comment by CYBAI** [comment]
Hi @jdm , I'd like to work on this one!

**Comment by jdm** [comment]
Great! We should figure out if gecko does anything special to support this.

**Comment by jdm** [comment]
https://searchfox.org/mozilla-central/source/xpcom/base/CycleCollectedJSContext.cpp#129 is where Gecko sets their callback for tracking unhandled rejections. It looks like https://searchfox.org/mozilla-central/source/dom/promise/PromiseDebugging.h and https://searchfox.org/mozilla-central/source/dom/promise/PromiseDebugging.cpp are the places that deal with them. https://searchfox.org/mozilla-central/source/dom/promise/Promise.cpp#481 is what gets called which dispatches the event at the window.

**Comment by CYBAI** [comment]
@jdm After reading the provided files above,  let me confirm what I'll need to do.

1. In [InitializeCommon in CycleCollectedJSContext.cpp](https://searchfox.org/mozilla-central/source/xpcom/base/CycleCollectedJSContext.cpp#129-131) which should be as same as `new_rt_and_cx` method for initialization in `Servo`, I'll need to register [`SetPromiseRejectionTrackerCallback`](http://doc.servo.org/mozjs/jsapi/fn.SetPromiseRejectionTrackerCallback.html) and also declare two global variable for `mUncaughtRejections` and `mConsumedRejections`.

(Not sure if making `mUncaughtRejections` and `mConsumedRejections` in [`GlobalScope`](https://github.com/servo/servo/blob/master/components/script/dom/globalscope.rs) is correct or not?)

https://github.com/servo/servo/blob/3ce3f39383c8217a30b15d27f3121f96bbe0014d/components/script/script_runtime.rs#L142

2.
- Implement `PromiseDebugging` for `Servo`
- Implement `ReportRejectedPromise` in [`promise.rs`](https://github.com/servo/servo/blob/master/components/script/dom/promise.rs)

**Comment by jdm** [comment]
Yes, I think that all makes sense. Using GlobalScope sounds like the right approach.

**Comment by CYBAI** [comment]
Thanks! I'll start to work on this when I have time!
