### ISSUE TITLE
Windows nightly hangs when loading pages

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#15428]
The currently Windows nightly hangs when loading Hacker News, Reddit, and a few of the other showcase links.

The CPU maxes out and nothing from the page is shown.

![servo_hackernews](https://cloud.githubusercontent.com/assets/547158/22709815/0cceb626-ede0-11e6-8ed3-d890fa361002.png)

**Comment by jonathandturner** [comment]
Poking around a bit more, I can't get any of the website demos from the showcase working.  It seems something is happening as the page is rendered that causes the CPU to make out and Servo to hang.

If I try to close Servo when this happens, it stays in the background eating up the CPU and must be manually killed.

**Comment by KiChjang** [comment]
> If I try to close Servo when this happens, it stays in the background eating up the CPU and must be manually killed.

I think this happens on Linux as well - whenever a panic occurs, I am not able to close Servo using the top right X as well, manually killing the process is the only option.

**Comment by jonathandturner** [comment]
@KiChjang - is there a bug for that issue?

**Comment by jdm** [comment]
Nope.

**Comment by jonathandturner** [comment]
This now appears to be fixed after https://github.com/servo/servo/pull/15681
