### ISSUE TITLE
Remove an invalid FIXME

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#15426]
There's a FIXME pointing to the animation/transition timing keyword functions serializing to cubic beziers. #14899 has fixed this, and so we can remove it.

Code: `components/style/properties/shorthand/box.mako.rs`

**Comment by z1mvader** [comment]
Hi! I'd like to take this one @highfive : assign me

**Comment by Wafflespeanut** [comment]
fixed by #15429
