### ISSUE TITLE
Servo homepage not rendered correctly

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#15432]
The servo webpage currently looks like this in servo:

![screen shot 2017-02-08 at 10 14 33](https://cloud.githubusercontent.com/assets/547158/22711812/6a7a4d7e-ede7-11e6-9d80-c61163cc056e.png)

Seems like something is going wrong with the image rendering, which is causing it to be much larger than it should be, which in turn causes the rest of the page to flow far below.

For comparison, the same page in Firefox the image is small and everything is compact in this area:

![screen shot 2017-02-08 at 10 15 26](https://cloud.githubusercontent.com/assets/547158/22711879/9c01f176-ede7-11e6-89a0-691c4358e4c8.png)

**Comment by atouchet** [comment]
Are you still seeing this issue? I am not able to reproduce this.

**Comment by jonathandturner** [comment]
Looks correct now.  Closing.
