### ISSUE TITLE
Only expose Storage/StorageEvent in Window

### ISSUE THREAD

**Issue by jdm** [servo/servo#15436]
Currently we have `Exposed=(Window,Worker)` in the storage-related webidl files. We should only expose these in the Window global, which will allow us to update the `Constructor` methods to accept a `&Window` argument instead of the generic `&GlobalScope`.

Code: `components/script/dom/webidls/Storage.webidl`, `components/script/dom/webidls/StorageEvent.webidl`, `components/script/dom/storage.rs`, `components/script/dom/storageevent.rs`
Test: remove the interface names from the list in `tests/wpt/mozilla/tests/interfaces.worker.js`, and run `./mach test-wpt /_mozilla/mozilla/interfaces.worker.html --no-pause-after-test`.

**Comment by kekkyojin** [comment]
As far as I have seen this bug wants the Worker on the .webidl files to be removed and &GlobalScoope to be replaced by &Window on the Rust source files.

@highfive: assign me

**Comment by kekkyojin** [comment]
I made the pull-request and it failed while trying to merge:

https://github.com/servo/servo/pull/15461

There is an error in Homu:

http://build.servo.org/builders/mac-dev-unit/builds/5571/steps/shell__2/logs/stdio

Is there anything I should do to fix it, @jdm?

**Comment by kekkyojin** [comment]
Response was in the pull request :)
