### ISSUE TITLE
Ars Technica text flow issues

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#15431]
In a recent servo, I saw this while browsing Ars Technica:

![screen shot 2017-02-08 at 10 08 18](https://cloud.githubusercontent.com/assets/547158/22711624/b9fad6ee-ede6-11e6-92d8-efda1ca19c27.png)

This was on a checkout from yesterday on macOS.

**Comment by nox** [comment]
This particular arstechnica issue seems to be fixed.

<img width="1136" alt="capture d ecran 2017-10-07 a 17 57 09" src="https://user-images.githubusercontent.com/123095/31309602-f69a14d8-ab88-11e7-96d0-773d1f72291c.png">
