### ISSUE TITLE
Land the test cases that should've landed with the selectors update

### ISSUE THREAD

**Issue by emilio** [servo/servo#15448]
See https://github.com/servo/servo/issues/15335 and https://github.com/servo/servo/issues/15394.

**Comment by emilio** [comment]
cc @bholley @nox @KiChjang

**Comment by nox** [comment]
Don't add a test for #15394, there are already in WPT. See the expectation changes in @KiChjang's PR.

**Comment by SimonSapin** [comment]
@nox I think #15440 only changes test expectations for `[foo~=""]` not other kinds of selectors that are also affected.

**Comment by nox** [comment]
Oh I see, never mind then.

**Comment by alexfish8** [comment]
@highfive assign me

I'll take a look.

**Comment by SimonSapin** [comment]
Rather than add a new test, see if you can extend this file:

https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/dom/nodes/selectors.js

To run the corresponding test:

```
./mach test-wpt tests/wpt/web-platform-tests/dom/nodes/ParentNode-querySelector-All.html
```

**Comment by jdm** [comment]
@alexfish8 Have you made any progress here?

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by jacksonweekes** [comment]
@highfive: assign me

**Comment by jdm** [comment]
#16228 was going in the right direction but the author stopped responding.

**Comment by jrasanen** [comment]
So add tests for #15394 and extend wpt/web-platform-tests/dom/nodes/selectors.js for #15335 ?

**Comment by mhaessig** [comment]
@highfive: assign me
