### ISSUE TITLE
"perspective" property must reject negative values

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15449]
Spec: https://drafts.csswg.org/css-transforms-2/#perspective-property

(The spec says positive, but it should be non-negative... which is an issue of the spec.)

Relevant code: https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs#L1642-L1648

(Should be an easy one, but not clear what is the best way to fix. cc @Manishearth)

**Comment by BorisChiou** [comment]
The perspective matrix uses the parameter, d, to compute the matrix [1]: "-1/d", so zero should be unacceptable. However, IIRC, in Gecko, we treat prespective(0) as prespective(inf), so we still works on zero.

[1] https://drafts.csswg.org/css-transforms-2/#PerspectiveDefined

**Comment by upsuper** [comment]
We treat `perspective(0)` as `perspective(inf)`, but we treat `perspective: 0` as `perspective: epsilon`. Anyway, that happens in later place, so style system doesn't need to handle that. It just needs to reject negative value.

**Comment by BorisChiou** [comment]
I see. Thanks for clarification.

**Comment by Manishearth** [comment]
We just need to add parse_non_negative as the predefined type parse function there.

**Comment by ioctaptceb** [comment]
@highfive: assign me!

**Comment by dcci** [comment]
Sorry if I'm missing something obvious, but what's the policy for PR timeouts? If nobody is actually working on this I'd like to try implementing it.

**Comment by jdm** [comment]
It is good form to ask the person directly before starting to work on somethng. @ioctaptceb have you made any progress?

**Comment by dcci** [comment]
ping?

**Comment by upsuper** [comment]
It seems @ioctaptceb doesn't respond after a whole week... This issue is now yours, @dcci :)

**Comment by ioctaptceb** [comment]
@dcci please go ahead!

**Comment by dcci** [comment]
I was unsure how to test this one, so I asked on IRC.
Copying for the archives:
```
14:32 <@SimonSapin> davide: then add a testharness.js test in tests/wpt/mozilla/tests/css
14:32 <@SimonSapin> see tests/wpt/README.md for instructions
14:34 <@SimonSapin> use a style="…" attribute in HTML with an invalid value, and assert in JS that element.style.perspective is the empty string
```

**Comment by KiChjang** [comment]
@dcci What's the status of this?

**Comment by n0max** [comment]
@highfive: assign me

**Comment by Wafflespeanut** [comment]
@n0max Did you start working on this? Need help?

**Comment by n0max** [comment]
I have already changed the parsing to non negative and created some test cases.
But the mozresource.pyc file was added to the MANIFEST.json and running `./mach update-manifest` don't change anything. I'm currently try to fix this.
My changes are at [commit](https://github.com/n0max/servo/commit/77807385a604f207f8ebc014403f7b4642edf775).

**Comment by Wafflespeanut** [comment]
Ah, just revert the manifest to the previous commit, `update-manifest` again and amend your changes to your current commit?

**Comment by jdm** [comment]
You will need to remove the the mozresource.pyc file before running update-manifest again.

**Comment by n0max** [comment]
Thank you, that worked.
