### ISSUE TITLE
Implement parsing webkit-prefixed gradient functions

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15441]
This is defined in the Compatibility Standard: https://compat.spec.whatwg.org/#css-image-type

The corresponding syntax is in https://www.w3.org/TR/2011/WD-css3-images-20110217/#gradients

**Comment by karan1276** [comment]
I would really like to work on this. If some one can give some extended mentoring on this it will be great. Some links to similar properties will be super awesome.

**Comment by upsuper** [comment]
This is not about property, but about another syntax for `<image>` values which is accepted by various properties.

The relevant code is https://github.com/servo/servo/blob/master/components/style/values/specified/image.rs#L102-L155

You would need to add a bunch of prefixed gradient functions there which are similar but have tricky minor difference to the unprefixed ones.

**Comment by karan1276** [comment]
Humm right, but for example in the specs they say `-webkit-linear-gradient()` must be treated as alias of `linear-gradient` so can't we just say sth like:

```
        let (gradient_kind, stops) = match_ignore_ascii_case! { try!(input.expect_function()),
            "linear-gradient" | "-webkit-linear-gradient"=> {      <--- just OR them with respective functions
                try!(input.parse_nested_block(|input| {
                        let kind = try!(GradientKind::parse_linear(context, input));
                        let stops = try!(input.parse_comma_separated(|i| ColorStop::parse(context, i)));
```

**Comment by upsuper** [comment]
No, because it says, e.g.
> -webkit-linear-gradient() must be treated as an alias of linear-gradient as defined in **[css3-images-20110217]**.

The current version of `linear-gradient` is based on what is defined in [the latest css-images-3 spec](https://drafts.csswg.org/css-images-3/#linear-gradients), which has a different syntax than what was defined in [css3-images-20110217](https://www.w3.org/TR/2011/WD-css3-images-20110217/#gradients).

**Comment by karan1276** [comment]
aah, okay

**Comment by karan1276** [comment]
Also, i just noticed `linear-gradient` and `radial-gradient` have the same code block, same for `repeating-*`. Would it be a good idea to merge them to one case clause. Or was it done intentionally?

**Comment by upsuper** [comment]
They are different... `linear-gradient`s use `parse_linear` and `radial-gradient`s use `parse_radial`. If you are able to merge them, it is probably also fine.

**Comment by karan1276** [comment]
ah! didn't see that. If they were same it made sense . I guess there is no real advantage merging them now

**Comment by nox** [comment]
Does serialisation need to preserve the prefixes?

**Comment by upsuper** [comment]
We probably need to, because there seems to be some functional difference?

It seems to me Gecko preserves the prefix in computed style (via [`nsStyleGradient::mLegacySyntax`](https://dxr.mozilla.org/mozilla-central/rev/f40e24f40b4c4556944c762d4764eace261297f5/layout/style/nsStyleStruct.h#245)). But it only serializes things to `-moz-` prefix, even if the source is `-webkit-` prefixed.

If we are not going to implement `-moz-` thing, we probably should drop that part in Gecko side in advance, and only serialize things to `-webkit-` prefix there. And it may also be worth checking what other browsers do for serialization prefixed gradient functions. If they don't preserve prefixes, we probably can just do some parse-time conversion, and then drop prefixes as well.

**Comment by nox** [comment]
> We probably need to, because there seems to be some functional difference?

The differences are only in parsing AFAICT: the token `to` isn't present in `-webkit-linear-gradient`, and the center of the gradient comes at the beginning of `-webkit-radial-gradient`, again without a `to` prefix.

As a side-note, didn't we forget to handle the `<zero>` part from https://drafts.csswg.org/css-images/#linear-gradient-syntax?

**Comment by upsuper** [comment]
The `<zero>` part is very new, probably something just resolved several days ago. IIRC, CSSWG made unitless zero usable for degree, but then they found there could be ambugity, so they decided to put that quirk explicitly in some places, and gradient is one of them.

**Comment by upsuper** [comment]
So Servo implements the unitless-zero-as-zero-degree, and Gecko never has that. But Servo should probably remove that support, and do what the current spec says instead.

**Comment by upsuper** [comment]
> The differences are only in parsing AFAICT: the token to isn't present in -webkit-linear-gradient, and the center of the gradient comes at the beginning of -webkit-radial-gradient, again without a to prefix.

Probably check with Blink/WebKit and see if they do that? @miketaylr, could you help checking this? Also this may be something worth putting into the Compat spec as well.

**Comment by nox** [comment]
@upsuper Should the prefix also be preserved for serialisation of computed values?

**Comment by nox** [comment]
```html
<div style="background-image: -webkit-linear-gradient(top, yellow, blue);">
<script>console.log(document.querySelector('div').style.backgroundImage)</script>
```

Unsurprisingly, both Safari and Chrome serialise that as the prefixed thing. No idea about Edge.

**Comment by upsuper** [comment]
Serialization of computation is done in Gecko side for Stylo, so probably doesn't really matter, but we probably want to be consistent to specified value here?

I guess we would need to fix the Gecko side code to prefer using webkit-prefix first...

**Comment by nox** [comment]
@upsuper I already have a patch ready for parsing and serialisation of both specified and computed values, do you want me to make a PR of that, so that a try run can be done on Gecko's side, maybe?

**Comment by nox** [comment]
Err, I missed the operative part: that patch only handle linear gradients for now.

**Comment by upsuper** [comment]
I probably should figure out a plan for [bug 1337655](https://bugzilla.mozilla.org/show_bug.cgi?id=1337655) first (which I totally forgot before). There may not be a significant difference on test result without having that bug resolved, so probably it isn't worth making a separate PR if you haven't finished all the gradient stuff.

**Comment by nox** [comment]
I'm on PTO tomorrow and Monday is a national holiday, so I'll file it anyway. :)

**Comment by nox** [comment]
@upsuper In #16511 I implement parsing of -webkit-radial-gradient. Now AFAIK all we need is for Gecko to drop `-moz-` and use `-webkit-`.

**Comment by upsuper** [comment]
According to [bug 1241623 comment 8](https://bugzilla.mozilla.org/show_bug.cgi?id=1241623#c8), we also need to implement the 2008 version of `-webkit-gradient` syntax in addition to `-webkit-{linear,radial}-gradient`, and there is no spec for that.

Also, `-webkit-gradient` seems to be the most expressive syntax among all, and Gecko only partially support its expressiveness (via some parse-time conversion). Servo may or may not want to follow the exactly same way as Gecko.
