### ISSUE TITLE
Type (tag name) selector doesn't recognize type with uppercase letter

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15483]
For example the following code:
```html
<!DOCTYPE HTML>
<style>
  DIV {
    display: inline-block;
    background: green;
    width: 100px;
    height: 100px;
  }
</style>
<div></div>
<DIV></DIV>
```

Per spec it should show two green blocks, while Servo (or at least Stylo) shows empty.

This is probably an issue in selectors. cc @SimonSapin

**Comment by upsuper** [comment]
It seems Servo renders this page correctly. Either this is something Stylo-specific, or this issue has been fixed at some point.

**Comment by upsuper** [comment]
Interesting that it doesn't seem to happen on our testing infra... but it fails in my local build...

**Comment by upsuper** [comment]
So it works on my mac build as well... then there is probably something weird with windows?

**Comment by upsuper** [comment]
This seems to be a bindgen bug then. `node.owner_doc().mType` returns `eXUL` while C++ code returns `eHTML`.

**Comment by upsuper** [comment]
I don't know why but it seems bindgen generates a 80 bytes useless padding for msvc build...

**Comment by emilio** [comment]
This is fixed in https://github.com/servo/servo/pull/15216. We check for field offsets too so now we should be sure we're accessing what we think we're accessing.

**Comment by upsuper** [comment]
So it isn't really ever a Stylo bug then, since Stylo build never depends on the broken bindgen. Let's close this bug.
