### ISSUE TITLE
border-spacing accepts (and ignores) anything for their second part of value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15489]
Test code:
```html
<!DOCTYPE HTML>
<div style="border-spacing: 1px rubbish"></div>
<script>
alert(`decl: ${document.querySelector('div').style.borderSpacing}`);
</script>
```

The relevant code should be https://github.com/servo/servo/blob/master/components/style/properties/longhand/inherited_table.mako.rs#L109-L141 and this is probably very similar to #15487.

**Comment by canaltinova** [comment]
This is also very similar to #15491. We need to wrap [this match](https://github.com/servo/servo/blob/78afe2b8d1dd170dc0870608aa10160b07b77a06/components/style/properties/longhand/inherited_table.mako.rs#L116-L119) with `input.try`. 
`parse_non_negative` function consumes a token but when it fails, it never gives back this token. With the usage of `input.try` we are forcing it to give this token back if parse_non_negative function fails. After this, `rubbish`(in `border-spacing: 1px rubbish`) will remain in the parser. And parser will fail if it's not exhausted. 

note: [These lines](https://github.com/servo/servo/blob/78afe2b8d1dd170dc0870608aa10160b07b77a06/components/style/properties/longhand/inherited_table.mako.rs#L122-L124) are also making sure of failing if there is still an unconsumed token. But actually upper functions that call this parse function are taking care of that. I suppose we can remove it.

`input.try` usage examples can be seen here:
https://dxr.mozilla.org/servo/search?q=input.try(&=servo

**Comment by canaltinova** [comment]
@UnICorN21 would you like to work on that?

**Comment by UnICorN21** [comment]
@canaltinova OK, thx.
@highfive: assign me
