### ISSUE TITLE
The third length in {box,text}-shadow and drop-shadow function should not accept negative value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15490]
Spec: https://drafts.csswg.org/css-backgrounds-3/#the-box-shadow

Relevant code: https://github.com/servo/servo/blob/master/components/style/values/specified/mod.rs#L608-L666

`box-shadow` can accept up to four length values, and three of them can accept negative values, while the third value, which is blur radius, should not accept negative value.

Test code:
```html
<!DOCTYPE HTML>
<div style="box-shadow: 1px 1px -1px"></div>
<script>
alert(`decl: ${document.querySelector('div').style.boxShadow}`);
</script>
```

(Note that the serialization result doesn't make sense anyway, which is #15203.)

**Comment by upsuper** [comment]
The same code also affects `text-shadow`, whose third length should be non-negative as well.

**Comment by upsuper** [comment]
Also affects `drop-shadow()` function for `filter` property.

**Comment by karan1276** [comment]
Can i do this

**Comment by jdm** [comment]
Go ahead!

**Comment by karan1276** [comment]
I was having a look at the serialization code, does it consider the possibility of `none` value ?

Also looks like it is (looping through)[https://github.com/servo/servo/blob/master/components/style/values/specified/mod.rs#L615] the something. I didn't quite get that.

I tried to write the serialized code. Would (this work)[https://gist.github.com/karan1276/8844c4643ef621faaba6ed60f1a7ebd1]

**Comment by upsuper** [comment]
> I was having a look at the serialization code, does it consider the possibility of `none` value ?

I believe this function is only for parsing a single shadow item. Most properties which use this function support multiple shadow items, and they should handle `none` before they try to invoke this function.

> Also looks like it is looping through the something. I didn't quite get that.

There is such loop because `inset`, `<length>{2,4}`, and `<color>` can be in any order in CSS.

> I tried to write the serialized code. Would this work

That doesn't work, because this code would only accept one order. It would fail to parse things like `inset 2px 2px red` or `red inset 2px 2px`.

**Comment by karan1276** [comment]
Okay nice. So to resolve this issue i am thinking of removing this [while loop](https://github.com/servo/servo/blob/master/components/style/values/specified/mod.rs#L626-L633) and replacing it with `try!(...)` and `input.try(...)` statements. 

Reason for that is, because not all lengths will use `Length::parse` ,radius will use `Length::parse_non_negative`. Also we are given that there are 2 lengths for sure, 2 more are optional.

would this be the correct approach?

**Comment by upsuper** [comment]
That sounds like the right approach.

**Comment by karan1276** [comment]
Thanks!

**Comment by karan1276** [comment]
What is the role of the function `disable_spread_and_inset` ? Is it necessary for me to check the value returned by it. I mean why would spread and inset be disabled ? [Ref this](https://github.com/servo/servo/blob/master/components/style/values/specified/mod.rs#L609)

**Comment by jdm** [comment]
There's a comment about the parse method that says `// disable_spread_and_inset is for filter: drop-shadow(...)`.

**Comment by karan1276** [comment]
right, so what exactly are filters. And why do we need them?

**Comment by jdm** [comment]
https://developer.mozilla.org/en/docs/Web/CSS/filter

**Comment by karan1276** [comment]
What should be the output of the test code? The specs says <length>{2,4}. So 3 lengths should give error right?

**Comment by upsuper** [comment]
`{2,4}` means at least 2 and at most 4. See [CSS Values spec](https://drafts.csswg.org/css-values-3/#component-multipliers).

You can put the test in https://github.com/servo/servo/tree/master/tests/unit/style/parsing there are parsing tests for many properties. Probably adding a test in `inherited_text.rs` for `text-shadow` would be enough.

**Comment by karan1276** [comment]
Cool, thanks.

I think you miss read :). I will add the test. But you gave a "test code" at the beginning of the issue:
```
<!DOCTYPE HTML>
<div style="box-shadow: 1px 1px -1px"></div>
<script>
alert(`decl: ${document.querySelector('div').style.boxShadow}`);
</script>
```

When i run this test code what result should be alerted ?

**Comment by upsuper** [comment]
I included that one for manual test to confirm the bug. It isn't for being added to the test suite.

**Comment by karan1276** [comment]
Okay, when i runt that test code i get `decl: -1px 0px 1px 1px` i am not sure if this is the correct serialization for the property. Can you confirm ?

**Comment by upsuper** [comment]
The test code should return empty in thie case, since the third value is negative, which is invalid.

**Comment by karan1276** [comment]
Right, but it should get parsed for the "spread distance" value which comes after "blur radius"

**Comment by upsuper** [comment]
No. The third value is always blur radius. The third value should never be parsed as spread distance.

**Comment by karan1276** [comment]
Okay thanks
