### ISSUE TITLE
Factor parameter in filter functions should not accept negative values

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15494]
Spec: https://drafts.fxtf.org/filters/#FilterProperty

Relevant code: https://github.com/servo/servo/blob/d8a8e3e42eda3704d8793d398b24f2e37bded4ec/components/style/properties/longhand/effects.mako.rs#L344-L351

Negative values should be rejected there.

The affected functions include `brightness()`, `contrast()`, `grayscale()`, `invert()`, `opacity()`, `sepia()`, and `saturate()`.

**Comment by jtran12** [comment]
@highfive assign me
Hi, I'm new to rust and was looking for a good first PR. I would like to work on this issue, is there anything else I need to know/get set up to get started with this?

**Comment by jdm** [comment]
Unit tests that verify the behaviour changes probably belong in a new `effects.rs` in `tests/unit/style/parsing`. You can run the tests with `./mach test-unit -p style`.

**Comment by jdhorwitz** [comment]
If someone could mentor my with this I would love to work on it, unless it is still being worked on.

**Comment by jdm** [comment]
@jtran12 Have you made any progress here?

**Comment by jtran12** [comment]
@jdm Sorry for the huge delay, I haven't made much progress due to being really busy the past few days however, I am currently trying to get my servo build up and running so I can work on the issue.

**Comment by jtran12** [comment]
I noticed all the required functions utilize `parse_factor()` Should I simply just modify that function to not accept negative values? and return `Err(())`? Also for the tests I'm not sure how to particularly implement them

**Comment by jdm** [comment]
It looks like modifying parse_factor to reject negative values would be sensible, since it's only used in that module. As for tests, take a look at ones like [the animation ones](https://dxr.mozilla.org/servo/source/tests/unit/style/parsing/animation.rs#19-20).

**Comment by jtran12** [comment]
Great thanks! I'll let you know if I run into any problems

**Comment by jtran12** [comment]
I'm not quite sure how to test my modified `parse_factor` function in `style/properties/longhand/effects.mako.rs` in the test file `tests/unit/style/parsing/effects.rs` I assume the syntax for importing the function would look something like this:

`use style::properties::longhands::animation_iteration_count::single_value::computed_value::T as AnimationIterationCount;` ?

I've looked at the animation ones and it seems to be referencing the parser but I'm not sure how it works. Any clarification would be helpful

**Comment by upsuper** [comment]
I think the easiest way would be testing that `filter::parse` returns `Err` for filters with negative factor, but `Ok` for normal values. You need to add `filter` to `use style::properties::longhands::` and probably do something like `assert!(parse(filter::parse, "invalid value").is_err());`. in the test.

**Comment by jtran12** [comment]
After following the suggestion of adding `filter `to `use style::properties::longhands::` I've gotten `assert!(parse(filter::parse, "x").is_ok());` (which shows up as an error, so it's not the correct value for input) However, I'm struggling to figure out what values would be considered correct to replace `"x"` 

I was looking at: `http://doc.servo.org/style/properties/longhands/filter/fn.parse.html`

the correct values to input in `filter::parse` are:
`context: &ParserContext,
 input: &mut Parser` ?

I'm having trouble understanding what context/input I need to put for the `filter::parse` function
I apologize as I am very new to this

**Comment by upsuper** [comment]
`filter::parse` takes those parameters, but it is relatively redundant to provide all of those in tests, so there is [a helper function `parse`](https://github.com/servo/servo/blob/0dbee36915abd926e61ca8571e11abf1f97ec830/tests/unit/style/parsing/mod.rs#L12-L17) defined in tests/unit/style/parsing/mod.rs for easily testing it.

That helper function takes a parsing function (`filter::parse` in this case) and a string, and constructs other necessary things (like `ParserContext` and `Parser`), so that we can concentrate on the thing we want to test.

So here the `"x"` is the string you want `filter::parse` to parse. In this specific issue, you should probably test something like:
```rust
assert!(parse(filter::parse, "brightness(1)").is_ok());
assert!(parse(filter::parse, "brightness(-1)").is_err());
```

**Comment by jtran12** [comment]
Thank you for the help! Your post is very informative and I've learned a lot. The tests seem to be passing now so I'm going to work on getting the pull request up 👍
