### ISSUE TITLE
Rewrite TextEncoder::Encode to use typed array API

### ISSUE THREAD

**Issue by jdm** [servo/servo#15504]
[The current implementation](https://dxr.mozilla.org/servo/source/components/script/dom/textencoder.rs) uses the JSAPI to create an array buffer, get its buffer and populate it with the encoded text. We should be using the [ArrayBuffer::create](https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs#L120) API instead (see [FileReader::perform_readasarraybuffer](https://dxr.mozilla.org/servo/rev/1b069de6b26db99f8b7964e8542f2b04e78094ce/components/script/dom/filereader.rs#272) for an example).

Code: `components/script/dom/textencoder.rs`
Tests: `./mach test-wpt tests/wpt/encoding/`

**Comment by absoludity** [comment]
@highfive: assign me
