### ISSUE TITLE
Track focused Frame instead of Pipeline

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#15507]
It would make more sense to track the focused `Frame` rather than tracking the focused `Pipeline` as we currently have to update the focused pipeline whenever a navigation or traversal matures. If we just kept track of the focused frame, we automatically know that the focused pipeline is the pipeline of the `Frame`s active entry.

cc @asajeffrey

**Comment by asajeffrey** [comment]
Indeed, this would be an improvement. Related to #14692.

**Comment by paulrouget** [comment]
Related: #17401

**Comment by mandreyel** [comment]
@highfive assign me! I don't think I'll start working on this until #21559 is merged, but it seems to be in the same problem domain so I'm calling dibs on it lest it be snatched from me by some enterprising soul in the meantime :D hope I'm not being too bold here
