### ISSUE TITLE
Pressing space in a text input causes to scroll down the scrollable page

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#15513]
Test case:
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        input { margin-bottom: 1000px; }
    </style>
</head>
<body>
    <input type="text">
</body>
</html>
```
When space is pressed in this input, scrollable page is currently scrolling down. The page shouldn't scroll in an input.

**Comment by samgiles** [comment]
I am looking at this currently.  Not sure if there is an existing bug for this, some Key Events aren't routed through a document, and instead are handled by the window.

**Comment by samgiles** [comment]
Ok, this is fairly interesting.

I'm new to terminology so I hope `ScrollRoot` is the correct terminology.

The flow of events should be (up for interpretation somewhat):

1. "space" KeyDown, maybe with "shift" modifier.
2. Fire KeyboardEvent
3. If element has focus or default prevented, stop.
4. Scroll `ScrollRoot` underneath cursor (or last clicked - this seems to be Chrome's behavior) - firing appropriate scroll events etc..

What happens at the minute:

1. "space" KeyDown, maybe with "shift" modifier.
2. Scroll `ScrollRoot` underneath cursor.
3. ..and fire KeyboardEvent. 

I guess the right thing to do is a UX problem.

**Comment by jdm** [comment]
I'm having trouble figuring out where the code that converts a space key event into a scroll action lives. Have you found that?

**Comment by samgiles** [comment]
@jdm directly from the glutin window, see PR :)
