### ISSUE TITLE
Make HTMLOptionsCollection constructor accept a HTMLSelectElement argument

### ISSUE THREAD

**Issue by jdm** [servo/servo#15521]
`HTMLOptionsCollection` objects are only ever instantiated via `HTMLSelectElement::Options`, but the constructor method for `HTMLOptionsCollection` accepts a `Node` argument rather than `HTMLSelectElement`. If we change this, it makes it harder to misuse the collection by giving it a root node that is not an `HTMLSelectElement`.

Code: `components/script/dom/htmloptionscollection.rs`, `components/script/dom/htmlselectelement.rs`

No need for testing for this change; if it compiles then it's good enough for a PR.

**Comment by simon-whitehead** [comment]
@highfive: assign me
