### ISSUE TITLE
Update syn to 0.11

### ISSUE THREAD

**Issue by nox** [servo/servo#15542]
On crates.io:

* [x] https://github.com/servo/rust-cssparser/pull/122
* [x] https://github.com/servo/heapsize/pull/75
* [x] https://github.com/servo/html5ever/pull/255
* [x] https://github.com/mystor/synstructure/pull/3

In this repo:

* deny_public_fields
* domobject_derive
* jstraceable_derive

Other:

* <strike>Replace dwrote’s dependency on serde_codegen by serde_derive
* <strike>Replace webrender’s dependency on serde_codegen by serde_derive

**Comment by SimonSapin** [comment]
I edited @nox’s message above to reflect the current state with https://github.com/servo/servo/pull/15588.

**Comment by nox** [comment]
Thanks @SimonSapin!

**Comment by nox** [comment]
I removed the bullets for removing serde_codegen from the WR stack, given the current issues to manage dwrote.

**Comment by nox** [comment]
That is done.
