### ISSUE TITLE
Use rustc builds without asserts

### ISSUE THREAD

**Issue by jdm** [servo/servo#15548]
The Rust team is making these builds available in the s3 bucket, so we need to modify the mach bootstrap command to fetch the appropriate URL to retrieve them. This is blocked until https://github.com/rust-lang/rust/pull/39754 is merged.

**Comment by jdm** [comment]
https://s3.amazonaws.com/rust-lang-ci/rustc-builds-alt/$sha/$tarball is where they will reside.

**Comment by SimonSapin** [comment]
Maybe we want this for developers building locally, but keep LLVM assertions on CI?

**Comment by SimonSapin** [comment]
Or we could have LLVM assertions in "debug" CI builds, but not release ones. Are release jobs the longest in our current CI? Could we reduce the total cycle time if they’re faster?

**Comment by SimonSapin** [comment]
On IRC:
> @mbrubeck	"mac-rel-css" jobs are currently taking about 54 minutes
> @mbrubeck	Maybe we could move the "build-geckolib" step to one of the "mac-rel-wpt" builders instead

Disabling LLVM assertions cut release compile times by a third: https://github.com/servo/servo/pull/15559#issuecomment-280003926

**Comment by SimonSapin** [comment]
Reopening since this is not yet enabled by default: #15564
