### ISSUE TITLE
Use bitflags for multikeyword properties

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15556]
Some properties like `text-decoration` have syntaxes like `overline || underline || line-through || blink`, which we represent as four booleans. This is inefficient, we should use bitflags, something like:

```rust
bitflags! {
    pub flags SpecifiedValue: u8 {
        const NONE = 0;
        const OVERLINE = 0x01,
        const UNDERLINE = 0x02,
        const LINE_THROUGH = 0x04,
        const BLINK = 0x08;
    }
}
```

and use the bitflag addition/intersection methods to construct these.

Code: https://github.com/servo/servo/blob/5a624ff9560338024c18ad0abf496fd78d5f6bb1/components/style/properties/longhand/text.mako.rs#L104

You'll need to change code in layout and gecko.mako.rs as well to make this work.

**Comment by Wafflespeanut** [comment]
Gecko 101 😄

**Comment by deror1869107** [comment]
I would like to work on this!
@highfive : assign me
