### ISSUE TITLE
Hoist seen-property check before the virtual call and remove property deduplication

### ISSUE THREAD

**Issue by bholley** [servo/servo#15558]
I did some digging to day with regards to @SimonSapin's question in #15531. I didn't have time to fully confirm my analysis with a profiler, but I think we should remove property deduplication unless there's a way to get it for free [1]. The |seen| check should mostly eliminate the cost of additional declarations in a block.

According to #15531, deduplication is primarily aimed at optimizing the cascade. But the cascade looks like this:
(1) Iterate all the declarations.
(2) For each declaration, invoke the appropriate virtual method.
(3) At the top of the virtual method, check the bitfield to see if we've seen the property. If we have, early-return.

(1) Involves walking the rule tree to find all the DeclarationBlocks. This is currently more expensive than it should be (see [2]), but eventually there should be only the minor cost of cache misses for pointer chasing. Regardless, deduplication doesn't reduce the number of DeclarationBlocks, but rather the number of declarations within a block. And those are stored in a Vec, so the cost of iterating a few extra declarations should be negligible.

(2) is a virtual call, which is where the current design really penalizes us for having additional declarations. But we can solve that by hoisting the |seen| check to the caller (this will give us a general performance benefits even ignoring the deduplication issue). If we do that, redundant declarations will get fast-rejected with negligible overhead.

Given all that, the only remaining benefit of deduplication is memory overhead. But given the price we're paying the CSS parser, I don't think it's worth it.

CC @emilio @Manishearth @rwakulszowa @heycam 

[1] According to @bzbarsky, Gecko uses a large stack-allocated property-keyed array at parse time, so new properties just overwrite the old ones - but then that array needs to be converted to a sparse representation somehow.
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1339703

**Comment by bzbarsky** [comment]
It might be good to measure how common duplicated things are and what the resulting memory overhead is....

The other thing where deduplication can help is code clarity of declaration block serialization (e.g. for .cssText).  Maybe.  That stuff is going to be complicated no mattter what...

For the curious, http://searchfox.org/mozilla-central/rev/ac8a72f2d5204ced2004c93a9c193430c63a6a71/layout/style/nsCSSDataBlock.cpp#547 is the "convert to a sparse representation" bit in Gecko.

Speaking of which, how do you plan to handle this case:

    div { color: green ! important; color: red; }

in the no-dedup world?

**Comment by bholley** [comment]
Hm, that's a good point. We may want to store two Vecs inside PropertyDeclarationBlock instead of one Vec of a (PropertyDeclaration, Importance) tuple. @SimonSapin?

**Comment by SimonSapin** [comment]
@bzbarsky The cascade already needs to deal with this. Without dedup in the parser it’ll be for the cascade the same as:

```css
div { color: green ! important; }
div { color: red; }
```

@bholley We used to have two vecs, and had switch to support CSSOM when the relative order of important and non-important declarations is preserved.

**Comment by bzbarsky** [comment]
> Without dedup in the parser it’ll be for the cascade the same as

Ah, ok.  That makes sense.

**Comment by bholley** [comment]
Regarding the total number of duplicate properties: I just instrumented a build with the following patch: https://pastebin.mozilla.org/8979391

And did some vary unscientific browsing across wikipedia, google, facebook, hackernews, and nytimes. I got the following results: https://docs.google.com/spreadsheets/d/1I3I0mNRBE-1AmRdcI6EOPyUVMjvW1rMGlQwIjHnxZG4/edit?usp=sharing

That shows around 0.5% duplication, which we should almost certainly not be optimizing for.

**Comment by bholley** [comment]
@rwakulszowa, would you be willing to try this instead of #15531?

**Comment by bholley** [comment]
One thing we'll need to handle is logical properties, which have a different cascade function but share the same computed value, and thus the same |seen| value. We may need to generate a lookup table to map from the longhand id to the appropriate bit to test in |seen|.

**Comment by SimonSapin** [comment]
If duplication in serialization is a problem, we could dedup lazily when serializing (with a `might_have_duplication` flag)

**Comment by rwakulszowa** [comment]
@bholley Well, I can try. I may need some guidance, though. If I understood correctly, three things need to be done:
- get rid of [deduplicate_property_declarations](https://github.com/servo/servo/blob/master/components/style/properties/properties.mako.rs#L345) - this shouldn't break anything, since it's just an optimization
- the virtual call - seen check thingy - I guess I may need some hints here :) Where the code is etc.
- deduplication in serialization

**Comment by bholley** [comment]
That's correct, though note that (1) is not entirely an optimization given (3).

The virtual call for (2) is at https://github.com/servo/servo/blame/master/components/style/properties/properties.mako.rs#L1945 .

**Comment by SimonSapin** [comment]
(I was wrong in saying it’s only an optimization since it affects serialization in CSSOM.)

**Comment by SimonSapin** [comment]
@bholley Given the serialization complication I think I’d rather go with #15531 (skipping deduplication when we know it’s a no-op, but not removing it entirely). I think it should get rid of most of the time spent on this. Does this sound good enough?

**Comment by bholley** [comment]
That still involves doing a fair amount of work in the case that there's a single duplicated property in a large declaration, right? Can't we just use the |seen| bitfield during serialization?

In general, the optimizations described in this bug (hoisting the |seen| check before the virtual call) are worth doing regardless of what we do about deduplication. Given that, I think it may be a significant reduction in complexity to eliminate the deduplication logic in exchange for a |seen| check during serialization.

**Comment by Manishearth** [comment]
Yeah, I support making serialization slower if that speeds up the common case of parsing but not reserializing.

**Comment by SimonSapin** [comment]
> Can't we just use the |seen| bitfield during serialization?

I don’t know if it’s that easy. In case of duplication, the latter declaration wins. But the rest of the declarations should still be serialized in forward order.

So we can do dedup in serialization only, but it’s gonna be more expensive than "just use a bitfield". (Like two passes, the first one allocating a map of seen property IDs to last indices and a set of indices to skip in the second one.)

Maybe that’s still the way to go.

**Comment by bholley** [comment]
Seems like we could do this cheaply with iterators:

vec.iter().rev().filter(...closure that filters with &mut seen).rev()

And then serialize from that.

**Comment by SimonSapin** [comment]
Oh, good idea. (You’d still need to allocate a Vec of references before doing the second `rev()`, to avoid reversing the evaluation order of the side-effectful closure in `filter`, but it still sounds better than what I had in mind.)

**Comment by SimonSapin** [comment]
I’m working on this.

**Comment by SimonSapin** [comment]
There’s a couple cases in `ports/gecko/glue.rs` where something iterates over the declarations of a block and I don’t know if deduplication is needed: `Servo_StyleSet_FillKeyframesForName`, `Servo_AnimationValues_Populate`

@Manishearth @heycam @upsuper, do you know?

**Comment by upsuper** [comment]
Probably @birtles @hiikezoe and @BorisChiou knows better about those two functions.

**Comment by hiikezoe** [comment]
I think we don't need deduplicate both of them for now.

As for Servo_StyleSet_FillKeyframesForName, the declaration block is in @keyframes.  I think @birtles tries to spec the rule which property  wins (or is merged?).  I don't remember the link now. But anyways, the declaration block comes from KeyframesAnimation::from_keyframes in servo, so it depends on the result of the function.

As for Servo_AnimationValues_Populate (it will be replaced by another function in bug1338927),  it is also for keyframes of Web Animation API.   This has already been spec-ed  how duplicated property handles, I think.

**Comment by SimonSapin** [comment]
I think it’s clear in specs that when the same block contains two valid declarations for the same property, the one later in source order wins. The question is, now that we don’t deduplicate them in the parser, how do we keep other algorithms correct? For example, serialization (`cssText` getter in CSSOM) needs full deduplication. But code that works by finding the first match (like `getPropertyValue` in CSSOM) can instead be made to iterate the vector in *reverse* order.

So for every operation like these two functions, we need to decide between:

* Iterate the vector forward, with potentially multiple declarations for the same property. Works e.g. in code where later entries overwrite earlier ones.
* Iterate the vector *backward*, with potentially multiple declarations for the same property. Works e.g. in code that stops at the first match.
* Do a preliminary pass to remove any duplication before iterating. (Most costly, but most "safe" for correctness.)

**Comment by emilio** [comment]
So I was reviewing #15721, and I'm somewhat concerned about the complexity of it. I believe deduplicating them at parse time both makes more sense and is simpler, unless we have glaring evidence of the opposite.

My reasoning is the following:

 * Keeping an `is_deduplicated` member is needed (otherwise perf would suck everywhere), and it's more complex and can be less performant than just implementing other methods guaranteeing than the input and output declaration block are deduplicated.

 * This may need mutation in places we don't expect/need too, and makes performance kind of unpredictable. The rule tree dumping code comes to mind, but there's the example of the keyframes list in Gecko too, and potentially more as we add devtools support and similar stuff, for example. With #15721, we'd need to `write` in order to dump a rule node, which conflicts with the "reduce the locking" work that Simon was also doing. Of course this specific case is trivially bypassable re-implementing `to_css` without a deduplicated property declaration block, or similar, but that is in-elegant too.

 * Keeping declaration blocks with duplication may have bigger performance implications in Gecko than in Servo, given we need to compute values potentially multiple times, but in Gecko this also involves a Servo -> Gecko computed value conversion, which is expensive, specially for stuff with urls and similar.

FWIW, I checked what Blink does and they do deduplicate at parse time[1], and they don't seem super-concerned about performance (check the setProperty[2] call here, which is a `std::find_if` call in the end).

So I don't think that the extra complexity is worth it without measurable evidence about the wins.

[1]: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/css/parser/CSSParserImpl.cpp?l=170&rcl=bab27699add969a853c0c73eb16a60d2fb1b178e
[2]: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/css/StylePropertySet.cpp?l=399&rcl=bab27699add969a853c0c73eb16a60d2fb1b178e

**Comment by bholley** [comment]
@emilio and I just chatted on IRC. Here's my take:
* We have measured results that indicate that the current deduplication implementation is hot, and thus eliminating it in the common case is a win.
* I'm not really convinced by the strategy of only deduplicating if duplicates are detected, because that creates a performance cliff when somebody adds a single duplicate to a large declaration.
* Lazy deduplication doesn't trigger additional computed value conversion, because the cascade algorithm uses a |seen| check.
* I'm perfectly happy to delay expensive work to less-common methods like dumping the rule tree or manipulating keyframes, assuming the tradeoff is "definitely do the work at parse time" vs "maybe do the work later".
* I haven't looked at the patch, so I can't speak too much to the code complexity concerns. But conceptually, it seems to me like we could just have two accessors for property declarations, one of which returns a PD that may have duplicates, and the other of which guarantees that deduplication has been performed. That doesn't seem to add an unreasonable amount of complexity at first glance, but the devil may be in the details in some way I don't understand yet.

All that said, @emilio may have a compromise proposal that gets the best of both worlds. He proposed that tracking properties with |seen| during parsing, doing regular pushes of non-seen properties (like we do now), and doing a linear find+replace when appending already-seen properties, rather than triggering a reallocation+copy of the entire PD (the current deduplication step, IIUC). Assuming the find+replace is significantly cheaper than the reallocation+copy, this would make the overhead O(number of duplicated properties) rather than O(number of declarations with at least one duplicated property). Assuming sufficiently-different time constants, this seems like the right tradeoff. Curious to hear what @SimonSapin thinks.

Whatever we do here, we should still keep the |seen|-hoisting parts of #15721, since that's a win no matter what.

**Comment by SimonSapin** [comment]
Until we decide what to do about deduplication, I’ve split out the "hoisting" part into #15745. Dealing with logical properties before the virtual call has some runtime cost, see https://github.com/servo/servo/pull/15745#issuecomment-282574622.

**Comment by SimonSapin** [comment]
Opened #15856 dedup on insertion, with bitmap + linear scan. Not re-allocation at the end of parsing a block.
