### ISSUE TITLE
When an origin is opaque set the origin header to `null`.

### ISSUE THREAD

**Issue by samgiles** [servo/servo#15569]
Once Hyper supports setting a `null` Origin header, update `try_url_origin_to_hyper_origin` in `components/net/http_loader.rs ` to set `Origin: null`.

https://github.com/hyperium/hyper/issues/1065

**Comment by samgiles** [comment]
In the meantime, we can implement the `Header` trait from Hyper for `url::Origin`.

I can work on this.

**Comment by KiChjang** [comment]
This is done in #15903.

**Comment by KiChjang** [comment]
Turns out this actually isn't fixed by #15903 yet, we need to upgrade our hyper to at least version 0.11 before we can fix this.

**Comment by tigercosmos** [comment]
Could we upgrade hyper now? Or something block?

**Comment by jdm** [comment]
We are using the last version of hyper that did not include the async I/O API changes. We want to upgrade to the version that uses async I/O, but it's more work than previous hyper upgrades.

**Comment by Eijebong** [comment]
#21644

**Comment by atouchet** [comment]
Is this fixed now?

**Comment by Eijebong** [comment]
Oh, yeah, forgot about it, thanks :p
