### ISSUE TITLE
Font rendering has streaks

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#15574]
I just pulled up the GitHub front page in the most recent Servo and noticed that the font renders with streaks/lines between some of the characters.  You can see in the image below.

![screen shot 2017-02-16 at 09 38 32](https://cloud.githubusercontent.com/assets/547158/22994517/15022dd0-f42c-11e6-84fe-9e23fd3716c3.png)

**Comment by jdm** [comment]
I do not see this on macOS:
<img width="254" alt="screen shot 2017-02-15 at 3 45 02 pm" src="https://cloud.githubusercontent.com/assets/27658/22994662/bb01a6a8-f395-11e6-8d4e-8724fd413b9f.png">

**Comment by jonathandturner** [comment]
I'm on macOS also.  Could be video card?

I'm a MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by jonathandturner** [comment]
Ah, got the repro.  Open it the GitHub window, then resize the window by resizing the left or right side.  After a bit of resizing the issue will appear.

**Comment by nox** [comment]
I can't reproduce this anymore.
