### ISSUE TITLE
Add an `as_str()` method to WebIDL enums

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15586]
The Rust code for them is generated by `CGEnum` in `components/script/dom/bindings/codegen/CodegenRust.py`.

Right now, for an enum `Foo`, we generate a `FooValues` module with a `strings` static slice that can be used as

```rust
        let content_type = DOMParserBinding::SupportedTypeValues::strings[ty as usize];
```

It would be nicer to be able to write
```rust
        let content_type = ty.as_str();
```
hiding the slice of strings from callers.

Fixing this issue requires adding this method to the generated code, and replacing the two places in the code where we currently use the slice (`components/script/dom/domparser.rs` and `components/script/dom/permissionstatus.rs`).

No need for a test; if it compiles, that's sufficient.

**Comment by gregkatz** [comment]
Hi, I'd like to take a crack at this one. I think I understand what's required, but I'm not super github savvy.

@highfive: assign me
