### ISSUE TITLE
Avoid mem::transmute when using find_enum_string_index

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15587]
Currently, we pass a slice of strings to `find_enum_string_index` and cast the index into the enum type we want. It would be safer to replace the slice of strings with a slice of pairs `(string, enum value)`, and make `find_enum_string_index` generic in its return type, returning the enum value rather than the index.

Alternatively, we can replace the string table by code like

```rust
match &*search {
    "string" => enum value,
    ...
}
```

and make LLVM decide on the implementation.

In either case, we'd probably want to wait for #15586 to land first, to avoid unnecessary churn.

**Comment by Ms2ger** [comment]
CC @nox @jdm

**Comment by gregkatz** [comment]
Hi Ms2ger,

I was thinking about about trying to fix this one, but I have a couple questions. Should find_enum_string_index still be called that if it no longer returns an index? If I take the slice of pairs approach, can I remove the slice of strings (adjusting the as_str and to_jsval to use the pairs)?

Also, I have no idea how to go about writing a test for this.

**Comment by Ms2ger** [comment]
> Should find_enum_string_index still be called that if it no longer returns an index?

Perhaps not. Maybe `find_enum_value`?

> If I take the slice of pairs approach, can I remove the slice of strings (adjusting the as_str and to_jsval to use the pairs)?

Yep, that was the idea.

> Also, I have no idea how to go about writing a test for this.

No need to; if it compiles, that should be enough.
