### ISSUE TITLE
Rewrite the ban-type lint in Python

### ISSUE THREAD

**Issue by nox** [servo/servo#15591]
> 16:30 &lt;nox> Ms2ger: I've just discovered that the ban lint is a huge lie,
> 16:30 &lt;nox> and I kinda want to kill it.
> 16:30 &lt;•Ms2ger> ban?
> 16:30 &lt;nox> Ms2ger: The thing that warns about DOMRefCell<JS<T>>.
> 16:30 &lt;nox> It is a lie, and the lie makes it such that it could very well just be a Python lint.
> 16:31 &lt;•SimonSapin> nox: how is it a lie?
> 16:31 &lt;nox> SimonSapin: See the comment in match_ty_unwrap.
> 16:31 &lt;nox> SimonSapin: It zips the given type path to the AST of the type we are unwrapping,
> 16:32 &lt;nox> SimonSapin: So use hello::not::std::Cell; Cell<JS<T>> would warn.
> 16:32 &lt;nox> I was under the impression that it was a rustc lint to avoid such things,
> 16:33 &lt;nox> but turns out it could just be written in Python like the other lints that don't have type info
> 16:33 &lt;•SimonSapin> nox: does the ast even resolve `use` at all?
> 16:33 &lt;nox> SimonSapin: No.
> 16:33 &lt;nox> SimonSapin: That's what I'm saying.
> 16:33 &lt;•SimonSapin> oh right, that’s what you’re saying :)
> 16:33 &lt;nox> :)
> 16:34 &lt;•SimonSapin> well, a false positive like that isn’t too bad
> 16:34 &lt;nox> SimonSapin: Yeah, I'm just saying that it wouldn't be more precise than a Python lint, AFAIK.
> 16:34 &lt;•SimonSapin> arguably, naming your stuff the same as std stuff can be confusing
> 16:34 &lt;•Ms2ger> Hos about with `use std::cell::Cell as StdCell`?
> 16:34 &lt;•Ms2ger> How
> 16:34 &lt;nox> Ms2ger: That wouldn't catch that.
> 16:35 &lt;nox> Be it the current lint or a Python one.
> 16:35 &lt;nox> The Python one would be stable, though.
> 16:35 &lt;•SimonSapin> sold

**Comment by jdm** [comment]
The disadvantage is that we would no longer have integration with compile-fail tests verifying some level of workingness.

**Comment by SimonSapin** [comment]
Can we have equivalent tests in Python?

**Comment by zimio** [comment]
I know python and I would like to try fixing this. I don't know how to start though. Where is the current ban-type lint and are there examples of other lints in python within the project?

**Comment by jdm** [comment]
`python/tidy` is our existing set of python lints, which can be run with `./mach test-tidy`. https://github.com/servo/servo/blob/master/components/script_plugins/ban.rs is the banning lint that's written in Rust right now, and https://github.com/servo/servo/blob/master/tests/compiletest/plugin/compile-fail/ban.rs and https://github.com/servo/servo/blob/master/tests/compiletest/plugin/compile-fail/ban-domrefcell.rs are two test that check that it's working.

**Comment by zimio** [comment]
Great! Can I have this one assigned to me?

**Comment by SimonSapin** [comment]
Done! By the way `./mach test-compiletest` runs tests for Rust lints, while `./mach test-tidy --self-test` runs tests for Python lints.
