### ISSUE TITLE
Tool to report new contributors across Servo repository

### ISSUE THREAD

**Issue by jdm** [servo/servo#15601]
This is the tracking issue for the work necessary for [this NCSU project description](https://github.com/servo/servo/wiki/Report-new-contributors-project).

**Comment by lnishan** [comment]
Can non-NCSU students take on this project?

I'm interested in getting this project started, but I wonder if this is a reserved project for NCSU students. At the moment, this project seems a lot more approachable to me compared to other ones listed in the Wiki.

**Comment by jdm** [comment]
Sorry, we will need to wait for those students to turn it down before anybody else can work on it.

**Comment by lnishan** [comment]
@jdm 
No problem! I understand :)

Thanks for replying!

**Comment by Nikhila-B** [comment]
We have two questions related to the initial steps:
 
1. **Code Base:** Is there any existing code base we are working on or sending a pull request to later? Or are we creating our own repository and creating this tool independently?

2.   **Language:**  Our plan is to use javascript to interact with the GitHub API when creating our tools. Will this be okay ? we are open to any expectations and/or recommendations.

**Comment by jdm** [comment]
There is no existing codebase. JavaScript should be fine for this, but I recommend using a library that wraps the github api for you.

**Comment by Nikhila-B** [comment]
There are two tools, we are writing in the initial steps. We were not sure if we completely understand what the first is one is about

Tool # 1: create a tool that initializes a JSON file with the known authors for a local git repository

Are we redirecting the contributors list to a file? Any kind of clarification would help.

**Comment by jdm** [comment]
The goal of the first tool is to set up a list of the known contributors, which will make the output of the second tool more meaningful in the future (otherwise it would report each contributor as a new contributor, even if that is not the case).

**Comment by Nikhila-B** [comment]
Hi Josh, we would like you take a look at our repository - we will be wrapping up the documentation tonight.

**Comment by jdm** [comment]
For future reference, the repository is https://github.com/OODD-Mozilla/ToolRepository.
