### ISSUE TITLE
Replace uses of JS_GetArrayBufferViewType with high-level API

### ISSUE THREAD

**Issue by jdm** [servo/servo#15605]
We have [code](https://dxr.mozilla.org/servo/search?q=js_getarraybuff&=servo) that invokes the JS_GetArrayBufferViewType API from SpiderMonkey. Once https://github.com/servo/rust-mozjs/pull/340 merges, we can update the version of the `js` crate (`./mach cargo-update -p js`) and replace them with the new API added to the `ArrayBufferView` type.

Tests: `./mach test-wpt tests/wpt/web-platform-tests/WebCrypto` and `./mach test-wpt tests/wpt/web-platform-tests/webgl` should verify that there's no behavioural change.

**Comment by jdm** [comment]
@samliu Does this sound interesting to you?

**Comment by samliu** [comment]
If I understand correctly, this is a cleanup task to replace `JS_GetArrayBufferViewType` usages with `ArrayBufferView`, which is an interface that reduces our dependency on this SpiderMonkey specific API.

That sounds like a great first task, please assign it to me.
