### ISSUE TITLE
Remove use of serde from core-graphics-rs

### ISSUE THREAD

**Issue by jdm** [servo/servo#15607]
The only use of the serde crate in the [core-graphics-rs](https://github.com/servo/core-graphics-rs) crate is for [CGFont](https://github.com/servo/core-graphics-rs/blob/75753f05d19febc3d5ee8cc064560e0b5edb567c/src/font.rs#L34-L48). We should remove it and make a SerializableCGFont wrapper type in Servo's code that gets used anywhere where we want to store a CGFont that needs to be serialized. Reducing the number of libraries that need to be updated when we upgrade serde in the future makes it easier to actually do that.

You'll want to make the changes in a local clone of core-graphics-rs, then build Servo using a [local override](http://doc.crates.io/specifying-dependencies.html#overriding-with-local-dependencies) before making the necessary PRs to both repositories.

No need to run tests; if it builds, that's good enough.

**Comment by jdm** [comment]
@jbg Would you like to work on this?

**Comment by jbg** [comment]
Sure!
@highfive: assign me

**Comment by jbg** [comment]
Pull requests:
 * https://github.com/servo/servo/pull/15615
 * https://github.com/servo/webrender/pull/896
 * https://github.com/servo/core-graphics-rs/pull/75

**Comment by nox** [comment]
The PRs were closed due to inactivity.

**Comment by alfredoyang** [comment]
Can I take this?

@highfive: assign me

**Comment by alfredoyang** [comment]
It looks like both servo and webrender require CGFont serialization. Should I implement SerializableCGFont on both? Or implement it on one of them and include it on another one?

**Comment by alfredoyang** [comment]
This bug includes three PRs. Servo PR depends on webrender PR and webrender PR depends on core-graphics PR.

I'm not sure how to deal these in servo.

**Comment by jdm** [comment]
We merge core-graphics first, then publish the updated crate, then update the webrender PR to include upgrading the core-graphics version in use, then merge that, then it gets included in the next update of webrender.

**Comment by nox** [comment]
It is a breaking change in core-graphics, so we need to bump it everywhere, too.
