### ISSUE TITLE
Make atom generating part of build time bindgen

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15626]
I didn't do this since atom change doesn't break things that frequently, and that script doesn't seem to be closely related to bindgen itself. But there is a recent bustage caused from this, and I guess there could potentially be more. Also the script doesn't seem to be very complicated, so we can integrate it into build_gecko.rs to make it work at build time.

I'll work on this next week.

**Comment by nox** [comment]
@upsuper Was this done?

**Comment by upsuper** [comment]
Yes, by #16762.
