### ISSUE TITLE
Additional notes on building servo on macOS Sierra

### ISSUE THREAD

**Issue by lnishan** [servo/servo#15622]
1. There seems to be a new dependency (which uses OpenSSL) that doesn't use the environment variables `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR`.  
A perhaps not-so-good solution is this:  
```bash
sudo ln -s /usr/local/opt/openssl/include/openssl /usr/local/include/openssl
sudo ln -s /usr/local/opt/openssl/lib/* /usr/local/lib/
```

2. If you happen to have turned off System Integrity Protection and re-linked gcc & g++ with the "real" ones, you need to set these 3 environment variables like so:  
```bash
env CC=clang CXX=clang++ CPP='clang -E' ./mach build --dev
```

3. The build instruction for Mac OSX includes `./mach build ...` which doesn't make sense. Not sure if the dots were mis-added and it doesn't include a build flag (--dev, --release).

**Comment by nox** [comment]
> There seems to be a new dependency (which uses OpenSSL) that doesn't use the environment variables `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR`.

What dependency?

**Comment by lnishan** [comment]
@nox 

I'm not sure which one because I only looked at the error message.

It's reported in #15293 by @samuknet .

**Comment by nox** [comment]
There is something wrong on your system, because that's not reproducible here with macOS Sierra. I don't see @samuknet mentioning any other dependency in #15293.

I wonder if that is related to the fact that you seem to have a non-standard installation of everything with what you say about "real" gcc and g++ (whatever that is).

**Comment by nox** [comment]
At the very least, there is no way the README should mention `sudo ln -s` workaround.

**Comment by lnishan** [comment]
@nox Agree on not mentioning that workaround. I do not think that's appropriate as well.

Well yes, I do have a non-standard installation.
Please correct me if I'm wrong as I do have very limited knowledge when it comes to these things.
`gcc` and `g++` were linked to `clang` `clang++` on a fresh macOS and XCode. This led to a lot of issues as I was compiling other projects from source. So I re-linked `gcc` and `g++` with the ones provided by the Homebrew package (`ln -s g++-6 g++` - in hindsight probably not a good decision but it resolved the issues I was having).

The error message indicated that it couldn't find a header file with OpenSSL which was a standard installation. I didn't set the environment variables on my first compilation and it stopped on a earlier package. After I set the environment variables, I got further but stopped at that error message.

**Comment by deror1869107** [comment]
@lnishan
 
Did you  do ```./mach clean``` after rebuilding servo with environment variables?

It was mentioned on README.md.

I can build servo successfully after ```./mach clean``` and setting the environment variables on macOS 10.12.3.

**Comment by lnishan** [comment]
@deror1869107 

I think I did, but I'm not 100% sure.
