### ISSUE TITLE
Pass the initial URL as an argument to Browser::new, not as a opts property

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#15636]
_This issue is part of an effort to improve Servo's embedding story. See https://github.com/paulrouget/servoshell/projects/2_

Starting Servo from a third party application requires setting the initial URL as an option:

```
let mut opts = opts::default_opts();
opts.url = ServoUrl::parse(url).ok();
opts::set_defaults(opts);
```

I would expect to be able to do that instead:

```
servo::Browser::new(window, url);
```

**Comment by deror1869107** [comment]
I would like to work on this!

**Comment by paulrouget** [comment]
That would be great, but I'd like first to get the confirmation from someone else that this is a valid proposal.

@Ms2ger or @jdm any opinion on this?

Ideally, Servo could run with its default options.

**Comment by Ms2ger** [comment]
I think the whole setup with `InitLoadUrl` is kinda weird, but I'd say the proposed change won't make anything worse, so let's go ahead and do it.

**Comment by paulrouget** [comment]
@deror1869107 It's yours :)

**Comment by deror1869107** [comment]
@paulrouget 

Could I replace ```Servo::Browser::new``` with ```pub fn new(window: Rc<Window>, url: Option<ServoUrl>)```?

**Comment by paulrouget** [comment]
> Could I replace Servo::Browser::new with pub fn new(window: Rc<Window>, url: Option<ServoUrl>)?

I think so.

Does the ServoUrl need to be an `Option`? Is there any reason to support `url:None`?

**Comment by deror1869107** [comment]
If url is None, it would use default url in opts::get()

**Comment by paulrouget** [comment]
Any reason to keep url in opts?

**Comment by cbrewster** [comment]
@paulrouget we used the url in opts for browserhtml https://github.com/servo/servo/blob/master/resources/package-prefs.json#L5. This allows us to not need a script like the old `runservo` to provide the bhtml url to servo.

**Comment by paulrouget** [comment]
@cbrewster We can read the pref in main() instead. `shell.homepage` would be used if the url is not passed as an argument. I'm trying to decouple the "app" logic and the "web engine" logic. I think it's up to the app to set the initial URL, and I'm not sure the initial url should be part of opts.

So basically, I would suggest that we do:

1. remove Opts::url
2. move the logic of computing the initial url from opts.rs to /ports/servo/
3. add a ServoUrl argument to Browser::new (not an Option<ServoUrl>, just ServoUrl)

Does it make sense?

**Comment by cbrewster** [comment]
@paulrouget sounds good!

**Comment by jdm** [comment]
#15699 was an attempt at fixing this; the work there had some review comments that needed to be addressed.

**Comment by sadmansk** [comment]
@jdm I could take over this issue if no one else is working on it.

**Comment by jdm** [comment]
Please do!

**Comment by sadmansk** [comment]
@paulrouget do you want there to be a check if the `ServoUrl`parameter is `None` before calling `InitLoadUrl`? Currently I'm expecting a valid `url` to be passed into `Browser::new()`. I'll open the PR and add comments to the segments I have questions about.
