### ISSUE TITLE
Can we get rid of this glutin dependency? (libservo only)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#15639]
_This issue is part of an effort to improve Servo's embedding story. See https://github.com/paulrouget/servoshell/projects/2_

On Windows (and Windows only since https://github.com/servo/skia/pull/126), Azure requires skia which require glutin. Would it be possible to avoid this dependency?

**Comment by dralley** [comment]
Azure was recently removed: https://github.com/servo/servo/pull/25841

Can this be closed?

**Comment by jdm** [comment]
Yep.
