### ISSUE TITLE
Make headless=false the default

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#15637]
_This issue is part of an effort to improve Servo's embedding story. See https://github.com/paulrouget/servoshell/projects/2_

I expect Servo headless mode to not be the default mode.

Starting Servo from a third party application requires headless to be set to false:

```
let mut opts = opts::default_opts();
opts.headless = false;
opts::set_defaults(opts);
```

**Comment by nox** [comment]
Seems like something that could be an E-Easy issue.

**Comment by paulrouget** [comment]
This has been done.
