### ISSUE TITLE
Remove support for Blob::{close, isClosed}.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15660]
See https://github.com/w3c/FileAPI/pull/68

Blocks #10778.

* Code: `components/script/dom/blob.rs`, `components/script/dom/webidls/Blob.webidl`.
* Test: `/FileAPI/historical.html`.

CC @asajeffrey

**Comment by charlesvdv** [comment]
If nobody is working on that. I'm interrested in taking this issue.

**Comment by jdm** [comment]
Please do!
