### ISSUE TITLE
Implement ImageData constructors

### ISSUE THREAD

**Issue by nox** [servo/servo#15671]
[`Constructor(unsigned long sw, unsigned long sh)`](https://html.spec.whatwg.org/multipage/#pixel-manipulation:dom-imagedata-3) and [`Constructor(Uint8ClampedArray data, unsigned long sw, optional unsigned long sh)`](https://html.spec.whatwg.org/multipage/#pixel-manipulation:dom-imagedata-4).

I wonder if `CanvasImageData.createImageData()` can be implemented at the same time.

Files:
 * components/script/dom/imagedata.rs
 * components/script/dom/webidls/ImageData.webidl

**Comment by jdm** [comment]
Tests: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/the-canvas-element/historical.html` and `./mach test-wpt tests/wpt/web-platform-tests/webgl/conformance-1.0.3/conformance/textures/tex-image-with-format-and-type.html` (for `createImageData`). We should [write](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) some new tests verifying the constructor behaviour too in the `the-canvas-element` directory, since I can't find any.

**Comment by jdm** [comment]
@montrivo Does this looks doable to you?

**Comment by montrivo** [comment]
Yes ! Thanks. @highfive: assign me

**Comment by montrivo** [comment]
By uncommenting the Constructor annotations in the webidl file, I'm getting the following error when building. This seems to be more complex than the mere constructors implementation.
```
File "components/script/dom/bindings/codegen/CodegenRust.py", line 5293, in definition_body
    self.descriptor, self.constructor)
  File "components/script/dom/bindings/codegen/CodegenRust.py", line 416, in __init__
    type, descriptor, failureCode="break;", isDefinitelyObject=True)
  File "components/script/dom/bindings/codegen/CodegenRust.py", line 868, in getJSToNativeConversionInfo
    raise TypeError("Can't handle SpiderMonkey interface arguments yet")
TypeError: Can't handle SpiderMonkey interface arguments yet
make[2]: *** [Bindings/ImageDataBinding.rs] Error 1
```

A draft for the constructors: 
```	
       pub fn Constructor(global: &GlobalScope, width: u32, height: u32) -> Fallible<Root<Self>> {
		if width == 0 || height == 0 {
			Err(Error::IndexSize)
		} else {
			Ok(Self::new(global, width, height, None))
		}
	}	
	
	pub fn Constructor_(global: &GlobalScope, data: Vec<u8>, width: u32, opt_height: Option<u32>) -> Fallible<Root<Self>> {
		let mut len = data.len() as u32;
		if len % 4 != 0 {
			Err(Error::InvalidState)
		} else {
			len /= 4;
			let height = len / width;
			if len % width != 0 {
				Err(Error::IndexSize)
			} else if opt_height.is_some() && height != opt_height.unwrap() {
				Err(Error::IndexSize)
			} else {
				Ok(Self::new(global, width, height, Some(data)))				
			}
		}
	}
```

**Comment by jdm** [comment]
The constructor that accepts a Uint8ClampedArray won't work as written yet. Instead, use an `object` argument and use the typed array APIs to interact with it (e.g. https://dxr.mozilla.org/servo/rev/261df34ced0bdcb8126994c8653ac101d1172085/components/script/dom/textdecoder.rs#88 and https://dxr.mozilla.org/servo/rev/261df34ced0bdcb8126994c8653ac101d1172085/components/script/dom/imagedata.rs#63).

**Comment by nox** [comment]
```
  ▶ Unexpected subtest result in /2dcontext/pixel-manipulation/2d.imageData.object.ctor.html:
  │ FAIL [expected PASS] ImageData does not have a usable constructor
  │   → assert_throws: function "function () { new window.ImageData(1,1); }" did not throw
  │ 
  │ @http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.ctor.html:23:1
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  │ _addTest/</<@http://web-platform.test:8000/common/canvas-tests.js:62:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  └ _addTest/<@http://web-platform.test:8000/common/canvas-tests.js:59:9

  ▶ Unexpected subtest result in /html/dom/interfaces.worker.html:
  └ PASS [expected FAIL] ImageData interface object length

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ImageData interface object length
```

The 2 `PASS` are good news, the `FAIL` isn't.

**Comment by montrivo** [comment]
`CanvasImageData.createImageData()` in `/script/dom/canvasrenderingcontext2d.rs` (two methods) seem properly implemented. Should they be modified to reuse the new constructors ? Error handling could also be enhanced and could return proper `Fallible` values instead of panicking. But this can be left to  #15823.
If not, this issue can be closed.

**Comment by jdm** [comment]
I have filed #16043 to improve it. We can go ahead and close this.
