### ISSUE TITLE
Make tidy check for merge commits

### ISSUE THREAD

**Issue by jdm** [servo/servo#15673]
Rather than always pointing them out in reviews, we can make our tools (and therefore travisCI) do this instead.

**Comment by vwvww** [comment]
Can I work on this issue..?

After some work on this issue, tidy will:
* return error(on travisCI) or warning(on local) when the number of commit that is not in github.com/servo/servo is more than one.

**Comment by Wafflespeanut** [comment]
Okay, feel free to ask any questions :)

**Comment by jdm** [comment]
@vwvww Have you made any progress?

**Comment by sadmansk** [comment]
@highfive: assign me.

I'm new to servo, but this seems like an easy enough task to give me a head start into contributing to servo.

**Comment by sadmansk** [comment]
@jdm Just wanted to clarify one thing for this issue. So the deliverables for this issue includes whether the new commits in the PR contains any merge commits. But I was looking over the previous PR that was closed, and I was wondering if the change should also make sure that all the commits in a given PR are squashed into one.

**Comment by jdm** [comment]
No, it's fine for PRs to contain more than one commit if distributing the changes make sense. I don't see any way to allow that while also reporting commits that should be squashed.
