### ISSUE TITLE
Intermittent fail in /_mozilla/css/iframe/stacking_context_position_a.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#15678]
```
  ▶ FAIL [expected PASS] /_mozilla/css/iframe/stacking_context_position_a.html
  └   → /_mozilla/css/iframe/stacking_context_position_a.html 569bf34b47c9bccff95bb7020532443b0fe40aa1
/_mozilla/css/iframe/stacking_context_position_ref.html 2282c76e6bda5a18b112e8bb029c652c46df9ada
Testing 569bf34b47c9bccff95bb7020532443b0fe40aa1 == 2282c76e6bda5a18b112e8bb029c652c46df9ada
```

**Comment by jdm** [comment]
This is kind of unnerving. 

Test:
<img width="317" alt="screen shot 2017-02-21 at 3 55 32 pm" src="https://cloud.githubusercontent.com/assets/27658/23184549/3b45feec-f84e-11e6-896c-4a1dd6d01b26.png">
Reference:
<img width="320" alt="screen shot 2017-02-21 at 3 55 42 pm" src="https://cloud.githubusercontent.com/assets/27658/23184555/404ffed8-f84e-11e6-86c4-b386bcf8edca.png">

**Comment by jdm** [comment]
(the reference should have the text showing too)

**Comment by jdm** [comment]
I wonder if the load event was triggered too soon...

**Comment by mrobinson** [comment]
This is no longer disabled in layout 2020, so I'm going to close this one.
