### ISSUE TITLE
Iframe's window size is not available synchronously in about:blank

### ISSUE THREAD

**Issue by jdm** [servo/servo#15688]
```html
<iframe></iframe>
<script>console.log(document.querySelector('iframe').contentWindow.innerWidth)</script>
```
This prints 0, because the `NewLayoutInfo` in `HTMLIFrameElement::navigate_or_reload_child_browsing_context` provides a `None` value for `window_size`, which is what is stored in the new `Window` that is created and retrieved by `Window::GetInnerWidth`.

**Comment by cbrewster** [comment]
Should we make the iframe block until it receives the window size when creating the nested browsing context?

**Comment by jdm** [comment]
What if we did getClientBoundingRect() in an iframe's bind_to_tree method? That might give us the synchronization that we need.
