### ISSUE TITLE
HashMap (and therefore DOM nodes) grew by 8 bytes

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#15704]
`HashMap` grew by 8 bytes in https://github.com/rust-lang/rust/pull/38368. `script::dom::event_target::EventTarget` contains:

```rust
    handlers: DOMRefCell<HashMap<Atom, EventListeners, BuildHasherDefault<FnvHasher>>>,
```

and DOM nodes contain `EventTarget`, so they all grew by the same amount, and unit tests in `tests/unit/script/size_of.rs` fail when updating the compiler: https://github.com/servo/servo/pull/15565#issuecomment-281833437

@jdm @Ms2ger @nox What do you think? Should we take the hit and increase the expect size in unit tests, or try to get this space back somehow?

**Comment by SimonSapin** [comment]
Is the number of handlers for a given event target expected to be small? Could we get away with a `Vec` and linear scan instead of a `HashMap`?

I’m also looking at `BTreeMap` which is smaller (24 bytes), but in the current implementation even an empty map allocates an internal `LeafNode` with space for 11 key/value pairs, which in this case is 352 bytes. (For comparison, `HashMap` grew from 40 to 48 bytes but an empty map does not allocate.)

**Comment by SimonSapin** [comment]
Correction: 40/48 is with the default `RandomState` which takes 16 bytes. `BuildHasherDefault` is zero bytes, so the `HashMap` in `handlers` grew from 24 to 32 bytes.

**Comment by nox** [comment]
I don't care either way. One day we will optimise such things extensively, but today is not the day.

**Comment by SimonSapin** [comment]
Ok. Let’s increase expected sizes in unit tests next time we rustup.
