### ISSUE TITLE
Make CSS error reporter give a URL

### ISSUE THREAD

**Issue by jdm** [servo/servo#15708]
This requires storing a URL in the [ParserContext](http://doc.servo.org/script/dom/servoparser/struct.ParserContext.html) structure, and passing it as an argument to the [report_error](http://doc.servo.org/script/dom/servoparser/struct.ParserContext.html) API, and printing it in the output.

This is marked as less easy because it will also require updating the code that creates `ParserContext` values and pass in appropriate URLs.

Code: `components/style/parser.rs`, `components/style/error_reporting.rs`
Test: We can write a unit test for this in `tests/unit/style/` (make a new `error_reporting.rs`) that creates a parser and a custom error reporter (a struct that implements the `ParseErrorReporter` trait) and asserts the the correct URL is passed. Run `./mach test-unit -p style` to run the tests.

**Comment by jdm** [comment]
To see this in action, run `RUST_LOG=style::error_reporting ./mach run http://google.com`.

**Comment by jdm** [comment]
@avinash-vijayaraghavan does this sound interesting?

**Comment by avinash-vijayaraghavan** [comment]
i can work on it to learn about rust

**Comment by jdm** [comment]
Great! Please ask questions about anything that's unclear!

**Comment by SimonSapin** [comment]
For stylesheets, the URL is available in the `Stylesheet` struct.

**Comment by avinash-vijayaraghavan** [comment]
[patch.diff.txt](https://github.com/servo/servo/files/803066/patch.diff.txt)

hi josh/simon
i have attached a diff patch for you guys to take a look. my first stab at this.
what i have done is added an **Option<&ServoUrl>** to the report_error api for **ParseErrorReporter** in **StdoutErrorReporter** and then used it while error reporting based on a match as in

fn report_error(&self, input: &mut Parser, position: SourcePosition, message: &str, servo_url : Option<&ServoUrl>) {
         if log_enabled!(log::LogLevel::Info) {
             let location = input.source_location(position);
             **match  servo_url {
                 Some(url) => info!("\n------>ServoUrl:\t{}\n{}:{} {}", url.as_str(),location.line, location.column, message),
                 None => info!("{}:{} {}", location.line, location.column, message)**
             }

im not sure how to handle the case when imp ParseErrorReporter for **CSSErrorReporter** and 
**MemoryHoleReporter** . not done anythng with the servourl in these two cases.

**Comment by KiChjang** [comment]
@avinash-vijayaraghavan Can you submit a pull request instead?

**Comment by avinash-vijayaraghavan** [comment]
@KiChjang ok
