### ISSUE TITLE
Make image cache per-document rather than global

### ISSUE THREAD

**Issue by jdm** [servo/servo#15701]
This would remove any issues related to multiple pages loading the same URL but using different request parameters, and would also avoid the need for synchronous IPC every time the image cache needs to be queried. Rather than a separate thread with an event loop, we'll want a threadsafe data structure that can be used from both the script and layout threads.

**Comment by jdm** [comment]
This would help #14993.

**Comment by jdm** [comment]
@ferjm How does this sound as larger project to work on? It's a step on the way to implementing the HTML specification's model for loading images (#11517).

**Comment by ferjm** [comment]
Sounds very interesting. Happy to work on it. Thank you @jdm

**Comment by metajack** [comment]
This comes at the cost of memory though. Is the image cache slow, or is this motivated solely by messaging races?

**Comment by jdm** [comment]
Gecko is working on removing as much synchronous IPC as possible. If we do a per-similar-origin cache, we should get the main memory benefits of sharing that a global cache provides today.

**Comment by metajack** [comment]
I guess one point is that if we're going to make it a threadsafe data structure, why restrict it to similar-origin? Why not just pass the reference to the threadsafe hashmap (or whatever) in place of the channel we currently use? This gives us one cache per content process.
