### ISSUE TITLE
-moz-alt-content parsing is wrong

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#15726]
It's only allowed as a single value for the `content` property, like `none`.  This is causing stylo test failures on layout/style/test/test_property_syntax_errors.html:

TEST-UNEXPECTED-FAIL | layout/style/test/test_property_syntax_errors.html | invalid value '-moz-alt-content 'foo'' not accepted for 'content' property - got "-moz-alt-content \"foo\"", expected ""

etc.

@SimonSapin

**Comment by SimonSapin** [comment]
For future implementations of `-moz-*` properties and values, is this kind of detail documented? Should we reverse-engineer Gecko’s code?

**Comment by bzbarsky** [comment]
It... varies.  For Gecko-internal things that are only used from UA stylesheets there may not be much public documentation.  :(

Ideally, a try push of stylo with the modified servo would show if there are problems.  But I realize that's annoying.  I don't have great process suggestions here...
