### ISSUE TITLE
Update bitflags to 1.0

### ISSUE THREAD

**Issue by nox** [servo/servo#15724]
<s>For some unknown reason bitflags was updated to 0.8 with a breaking bump for `i128` support, we don't need that, but I'm filing this issue anyway to remember that we will have to do that at some point if we still don't want dozens of dependency dupes.

Fortunately, given the 0.8 bump doesn't actually change *anything* in the interface of the generated items, these crates just need a minor bump for bitflags to be updated in them.</s>

This issue has been repurposed as a bitflags update to 1.0.

**Comment by nox** [comment]
Version 0.8 is broken four our usage. Cf. https://github.com/rust-lang-nursery/bitflags/issues/59#issuecomment-282277988.

**Comment by nox** [comment]
Never mind, the PR introducing the breakage in 0.8 also fixes the breakage.

**Comment by Eijebong** [comment]
I'll do it unless anyone else is already doing it

**Comment by Eijebong** [comment]
Copying the list since I can't edit your issue :)

[ ] clang-sys
[ ] clap
[ ] cocoa
[ ] openssl
[ ] png
[ ] syntex_syntax
[ ] webrender
[ ] websocket
[ ] xml-rs

**Comment by notriddle** [comment]
Opened <https://github.com/google/pulldown-cmark/pull/70>, since I have a Google account.

**Comment by Eijebong** [comment]
Apparently I never finished this, sorry...

bitflags 1.0 is out though so I'll try doing that instead

**Comment by Eijebong** [comment]
- [ ] https://github.com/asajeffrey/swapper once  https://github.com/budziq/rust-skeptic/issues/60 Once this is fixed (this will remove servo's dependency on pulldown-cmark, which right now still uses bitflags 0.5)

**Comment by nox** [comment]
@Eijebong https://github.com/asajeffrey/swapper/pull/3

**Comment by nox** [comment]
https://github.com/djg/cubeb-pulse-rs/pull/23

**Comment by nox** [comment]
https://github.com/sfackler/rust-openssl/pull/776

**Comment by nox** [comment]
* bitflags 0.7.0 is gone.
* bitflags 0.8.2 is blocked on openssl (https://github.com/sfackler/rust-openssl/issues/776) and mp4parse_capi (https://github.com/mozilla/mp4parse-rust/pull/127).
* bitflags 0.9.1 is blocked on clap (https://github.com/kbknapp/clap-rs/pull/1063) and the macOS stack (https://github.com/servo/servo/pull/19314).

**Comment by Eijebong** [comment]
The only things blocking this are now the openssl PR and the clap 2.28 release

**Comment by Eijebong** [comment]
bitflags 0.9.1 is gone 🎉 
sfackler/rust-openssl#776 is the only blocker now

**Comment by atouchet** [comment]
Was this done?

**Comment by jdm** [comment]
[Nope](https://github.com/servo/servo/blob/master/Cargo.lock#L167-L170).

**Comment by Eijebong** [comment]
Still blocked on hyper

**Comment by Eijebong** [comment]
Done now :)
