### ISSUE TITLE
Implement frames timing function

### ISSUE THREAD

**Issue by BorisChiou** [servo/servo#15740]
I'm working on [Frames timing function [1]](https://www.w3.org/TR/css-timing-1/#frames-timing-functions) on Gecko ([Bug 1248340](https://bugzilla.mozilla.org/show_bug.cgi?id=1248340)), so I think it's better to implement it on Servo, too, so we can make sure there is no other problem on Stylo while running the test case for Frames timing function. I think this is an easy bug, so let me take it.

[1] https://www.w3.org/TR/css-timing-1/#frames-timing-functions

**Comment by BorisChiou** [comment]
@highfive: assign me

**Comment by BorisChiou** [comment]
I almost finish this issue. After gecko patches landing, I will create a PR for reviewing.

**Comment by BorisChiou** [comment]
Waiting for wpt tests merged from gecko into https://github.com/w3c/web-platform-tests

**Comment by KiChjang** [comment]
@BorisChiou For your reference, Servo's repository comes with a fork of w3c/web-platform-tests, and is located under tests/wpt/web-platform-tests. @Ms2ger and @jgraham periodically syncs that directory, so you can freely write your tests and commit them in Servo.

**Comment by BorisChiou** [comment]
stylo: [Bug 1359719](https://bugzilla.mozilla.org/show_bug.cgi?id=1359719)
