### ISSUE TITLE
The background on the Nelnet About page doesn't extend far enough down

### ISSUE THREAD

**Issue by notriddle** [servo/servo#15748]
https://www.nelnet.com/your-student-loan-servicer

![nelnet](https://cloud.githubusercontent.com/assets/1593513/23344459/08ebde90-fc3a-11e6-8e3b-ab7610f8ac6c.png)

The white background, that's supposed to obscure the filler image, doesn't extend down like it should.

p.s. I have not tried to log in, and will not try to log in.

**Comment by nox** [comment]
![capture d ecran 2017-10-08 a 09 36 21](https://user-images.githubusercontent.com/123095/31314894-26bfd9da-ac0c-11e7-8e94-5b179ae4af22.png)
