### ISSUE TITLE
Replace manual host parsing code with parse-hosts crate

### ISSUE THREAD

**Issue by jdm** [servo/servo#15756]
https://crates.io/crates/parse-hosts
https://dxr.mozilla.org/servo/source/components/net_traits/hosts.rs

I haven't looked into the crate's API yet, but it could be a straightforward replacement.

@ferjm This might be a nice second issue to work on.

**Comment by emilio** [comment]
For the record: license of that crate is listed as "unstandard", but looking at the repo it seems "CC0", which I think it's fine.

**Comment by jdm** [comment]
I would like @avadacatavra to review the future PR that fixes this.

**Comment by ferjm** [comment]
Thank you @emilio, I agree that [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed.en) should be fine.
