### ISSUE TITLE
Windows nightly - hacker news text off row

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#15757]
I'm seeing Hacker News titles being rendered lower than the expected line.

<img width="500" alt="font_off_line" src="https://cloud.githubusercontent.com/assets/547158/23374399/fcbd5342-fd88-11e6-9c06-24ae568deb61.png">

(I'm having deja vu, so this may have been reported already, but I didn't see the issue when I looked)

**Comment by atouchet** [comment]
This appears to be fixed in the latest nightly build.

**Comment by jonathandturner** [comment]
Agreed - looks much better now.
