### ISSUE TITLE
Page Loading Error

### ISSUE THREAD

**Issue by PEmu1** [servo/servo#15755]
unknown completed load Image("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAcCAYAAAB2+A+pAAAAAXNSR0IArs4c6QAABERJREFUSA2tlltoXFUUhjOXRDOxoRAlBScUoRKs2ATxpRIfpBSVUs2NtIwQCdQG+pCiUh+kl/ECbZ/EPAhRK0JjmoYkE8EHhbZKlRZEREqlFmKhN8SH6ODUJs1MZvz+nbOGk+RMMilZsM5ee93+vfb1hCqWoYGBgcq6urqnw+Hws/ATuDbCDfC6QqFQq9BQKPQvTQa+CV/N5/NX4AtTU1O/9Pb2ZtEFUmixNpVKrSdpGwnF27DHFvuU2b9LnrNwijyptra2tD+uCDw6OvpMJBLZj1MnDg/6ndZAnmEAo3Nzcx91dnb+rHwOeGJi4hvkF0oBEHSdAV3UNDLlk/hNwZpe0Tq4DtsmLQe+W/Hd6CzBn29bW1tfjHq2JaAk+BEehr/u6Oi4HpwjWDs2NraRQezEuotBtPi9yLddfas478kFRv5JLpf7sKur66o/4H7lkZGRxmg0+gYD2SsMgLOsd5UBa/ep+gzT4Hbr/QKVimM5tfu1LDNgVIc9x5zXWt/rrl1Dpa5IMroj5tYYZY61EEqkHCiO3Pv475EvsZ8xdYdWisPfFaWplq9tLqvY+ivleRyHDZ6T5HLIFcUAZuXsRkFnxossq+JyUAJ8XG4qdlhW4bTnGOrv73+gr6/vnj+QnfkoO3MfO9Oma4vPvoWNc1R9TkSeE/ExJ+K2z15BvEAXYLkOo/ibqh+Tczwef4hmAXBVVZXO4juyi/CdF+Zl3eHiCo0L30uIp9U3mp2drUFv3X8k2FTfMC1J9QisKQEat4Tkd1hW/qQZqP5J5F+tr5Y79jzVJAlyA0XVActP9Bs8JoFYzfZ5yX7iDdhsfezXJNtUnyHpASkAeInmS8lGXJl/Ir9rfY5TI/4OGLDLHKcjZgtqvZzORNw5Ca6CdDqtUd6VgkQ7BgcH1+z24k2PAfayl/tONpv9QbID7unp0bM1LAVO62tqavZLXoauYLvhseSSVF9fvw/jw57DaXa8O8fF7cmW31RZWfk7wBEGkWYtnmKKb5XMWIZhaGioPhaLXRYwOedoG1mWPxTqKpbASCYBdWurqlmXU8lk0jafXFZFxIarq6tPEmTVDhqoEhWB1aHKN2nc4Qe8pampqV8JZFstNTc3HyPHdi/uNhW/5c9RnGpT8og/T7Xa5Q6QgK8ymcyr3d3d/5nPcq1uvoaGhs+JT8iPeL3126j2e/WNllTDun6HsXg8SPBKbW3tT1yLS/5SLIm1+DwH6AUDlR7gw4tBpV9SsZQi7+k7ON+b/5JEf43H29vbz6ApmG18fLwFsLdh/e4UCd8PAA18MksCKxrwLpJ9irjgXJPwGvpTtHppEsjurlaMR/rb2MufxoI724xqlwWWA8fsEe7a9wB5HQD3tEkfRPjoyJyYnp4+nEgk/gryMd2KwObIADYzgCTJ2xcPAJ020ATtEZZB53ZFKhvYMrHr4wC/Bu+Go4ANcwy/WO0v8P8H+qpWV2S+gQAAAABJRU5ErkJggg==")

unknown completed load Image("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAcCAYAAAB2+A+pAAAAAXNSR0IArs4c6QAABERJREFUSA2tlltoXFUUhjOXRDOxoRAlBScUoRKs2ATxpRIfpBSVUs2NtIwQCdQG+pCiUh+kl/ECbZ/EPAhRK0JjmoYkE8EHhbZKlRZEREqlFmKhN8SH6ODU

**Comment by PEmu1** [comment]
The first string was the title for the pre-filled issue report but it was too long to use. Please let me know if I need to provide any more information as I am not super familiar with the normal issue reporting process for Servo.

**Comment by jdm** [comment]
Looks like another instance of #15709. Thanks for reporting it! If there is a particular page you're loading that exhibits this error, it would be good to know as well.
