### ISSUE TITLE
Does not work "start!" button on http://www.filpizlo.com/~pizlo/splay-detail.html

### ISSUE THREAD

**Issue by tetsuharuohzeki** [servo/servo#15763]
## Env

- revision: b8b23fda5f53397be30057cb406011bbdbdc3582
- OSX 10.11.6

## Step to Reproduce

1. `./mach run --dev http://www.filpizlo.com/~pizlo/splay-detail.html` which is linked from https://webkit.org/blog/7122/introducing-riptide-webkits-retreating-wavefront-concurrent-garbage-collector/
2. Click `start!` link

## Actual Result

- Servo emit `ERROR:script::dom::bindings::error: Error at :1:1 start is not defined` to stderr.
- Servo will show "undefined" page like this.

<img width="1136" alt="ss" src="https://cloud.githubusercontent.com/assets/180104/23403898/aaec6838-fdf5-11e6-878d-159b80bc26b2.png">

**Comment by danielj41** [comment]
The original error was fixed by https://github.com/servo/servo/pull/17083. Now there are two new errors:

```
ERROR:script::dom::bindings::error: Error at http://www.filpizlo.com/~pizlo/splay-detail.html:17:3013 i.measureText is not a function
ERROR:script::dom::bindings::error: Error at http://www.filpizlo.com/~pizlo/splay-detail.html:16:21031 s._view is undefined
```

where `i` is a `CanvasRenderingContext2D`.

I can get the same behavior in Firefox by running `delete CanvasRenderingContext2D.prototype.measureText` before clicking "Start!"

**Comment by jdm** [comment]
That's tracked in https://github.com/servo/servo/issues/5411.

**Comment by simonwuelker** [comment]
Closing as the `start!` link now (commit 895b8d30eac41afbdbd20efd65c5a6e58ae3f43d) works as expected and #5411 is closed.
