### ISSUE TITLE
[meta] Improve Servo initialisation

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#15777]
_This issue is part of an effort to improve Servo's embedding story. See https://github.com/paulrouget/servoshell/projects/2_

At the moment, starting multiple instances of Servo will have 3 major issues:
- they all have to share the same initial URL because the URL is set as an option which is a global object
- beside the latest instance, pages are not rendered (black screen)
- there are as constellations as there are browsers

At least we need:
- Make `opts` not global, and/or:
- Initial URL should be decoupled from the options
- We should first start a constellation, and then attach browsers to it (https://github.com/servo/servo/issues/13994)
- be able to switch GL contexts
- Constellation should not assume one compositor (https://github.com/servo/servo/issues/13993)

**Comment by glennw** [comment]
These are some relevant WR issues:

* https://github.com/servo/webrender/issues/771 (this is being worked on).
* https://github.com/servo/webrender/issues/933

**Comment by paulrouget** [comment]
I'm going to close this as most of it is done now. Only multi-window support requires initialization related work. See #13993.
