### ISSUE TITLE
mask is too liberal in what it accepts

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15772]
`alpha padding-box url(404.png) border-box` should not be accepted for mask, but it is.

cc @canaltinova

**Comment by canaltinova** [comment]
It's not clear to me why mask-origin and mask-clip should come consecutively. Grammar of mask says they can come in any order but both firefox and chrome are not accepting it.

`<mask-layer> = <mask-reference> || <position> [ / <bg-size> ]? ||<repeat-style> || <geometry-box> || [ <geometry-box> | no-clip ] || <compositing-operator> || <masking-mode>`

First `<geometry-box>` is mask-origin and second one is mask-clip property. According to this, sequence is not important. I can make this work like firefox and chrome but I couldn't find an explanation about this in spec. Am I missing something?

**Comment by Manishearth** [comment]
@dbaron should this be a spec bug or a firefox/chrome bug?

**Comment by bzbarsky** [comment]
Does the same thing happen for background-clip/background-origin?  Gecko seems to use the same parsing code for both...

The parsing code in Gecko has this comment:

        // The spec allows a second box value (for background-clip),
        // immediately following the first one (for background-origin).

(see CSSParserImpl::ParseImageLayersItem).

Did the spec quietly change at some point?  I'm having a hard time believing that both @dbaron and I misread this in 2013 when he fixed https://bugzilla.mozilla.org/show_bug.cgi?id=570896

Note that https://bugzilla.mozilla.org/show_bug.cgi?id=1188074 exists too.  Though that claims that Chrome's behavior doesn't match ours for background...

**Comment by dbaron** [comment]
The spec [changed in January 2014](https://hg.csswg.org/drafts/rev/7e4cec622a1c9d999a90c3ec4f091c7ebd10ff1e).  I vaguely recall a discussion, although it's not linked from that changeset.

Note that I also filed https://github.com/w3c/fxtf-drafts/issues/118

**Comment by dbaron** [comment]
(But if Firefox and Chrome both match the old spec, at this point we should probably consider changing the spec back.  Do they?)

**Comment by canaltinova** [comment]
I've tried only this certain example in Chrome earlier. After trying different cases, it looks like Chrome doesn't accept sub-properties apart from mask-reference.(this was previous spec behavior, I guess) I couldn't see any issue about the mask shorthand in Chrome issue tracker either. 
(But in background shorthand, Chrome accepts non-consecutive background-origin and background-clip, Firefox doesn't.)

**Comment by upsuper** [comment]
FWIW, Chrome supports the new spec. A simple testcase:
```html
<!DOCTYPE html>
<style>
div { -webkit-mask: url(404.png) border-box repeat padding-box; }
</style>
<script>
document.write(document.styleSheets[0].cssRules[0].cssText);
</script>
```

I'm going to change Gecko's behavior to match the spec in [bug 1188074](https://bugzilla.mozilla.org/show_bug.cgi?id=1188074) also for behavior of background shorthand. So closing this issue.
