### ISSUE TITLE
Styling / layout bug when zooming.

### ISSUE THREAD

**Issue by glennw** [servo/servo#15801]
Test case:

```
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      div {
        position: absolute;
        width: 80%;
        left: 10%;
        height: 100px;
        background: red;
      }
    </style>
  </head>
  <body>
    <div></div>
  </body>
</html>
```

If you use the recently landed page zoom support (Ctrl, Shift, + and Ctrl, -) to zoom in and out of the page, it doesn't correctly calculate the size and position of the div. However, running it with ```-i``` to disable incremental layout makes it work correctly (it then matches Gecko).

It looks like maybe the % elements aren't being restyled / calculated? I confirmed that it's detecting the viewport size has changed in layout, but didn't investigate any further.

**Comment by glennw** [comment]
cc @emilio @bholley @pcwalton

**Comment by emilio** [comment]
Yeah, this is likely a layout bug (not a styling bug, given the computed styles don't change at all). We're supposed to handle it in layout_thread: https://github.com/servo/servo/blob/master/components/layout_thread/lib.rs#L1077

Either that `needs_reflow` logic is wrong, or `viewport_size_changed` is false? I can take a look tomorrow probably.
