### ISSUE TITLE
Use `if let` with as_element instead of is_element and unwrap

### ISSUE THREAD

**Issue by jdm** [servo/servo#15811]
We have code that looks like `if node.is_element() && node.as_element().unwrap().foo`, which we can write as:
```rust
if let Some(element) = node.as_element() {
    if element.foo {
        // ...
    }
}
```
This ends up being nicer to read and reason about, and contains fewer unwrap calls!

Code: `components/script/layout_wrapper.rs`

**Comment by jdm** [comment]
@barrotsteindev This is a straightforward change you could make!

**Comment by c4khatta** [comment]
@highfive: assign me Hi, can I work on this issue?

**Comment by jdm** [comment]
@c4khatta Did you make any progress here?

**Comment by vypr** [comment]
I'll take this one over since they seem to be M.I.A.

**Comment by vypr** [comment]
@highfive: assign me

**Comment by vypr** [comment]
Made #16054, should fix this. :)

**Comment by vypr** [comment]
Safe to close now. Thanks for the opportunity to contribute!
