### ISSUE TITLE
Use Option::or_else instead of transforming Some => Some

### ISSUE THREAD

**Issue by jdm** [servo/servo#15812]
We have code inside matches in ThreadSafeLayoutNodeChildrenIterator that looks like `Some(x) => Some(x)`. We can replace the `match foo` with `foo.or_else(|| ...)` where the ... is the code for the None branch. This is more idiomatic Rust code.

Code: `components/script/layout_wrapper.rs`

**Comment by jdm** [comment]
@crypto-universe This is a straightfoward change that you could make!

**Comment by crypto-universe** [comment]
Perfect, I take it! Thanks, @jdm

**Comment by crypto-universe** [comment]
@jdm check the PR, please. First of all coding rules, because I'm not familiar with them. How to break long lines, for example?
