### ISSUE TITLE
Audit how much a libc 1.0 release would impact our dependency graph

### ISSUE THREAD

**Issue by nox** [servo/servo#15824]
### angle

Dependency on `libc` was [killed](https://github.com/servo/angle/pull/18), breaking change because of `libc::c_void`.

### azure

Depends on `core-foundation` and others. To audit.

### backtrace

Uses symbols from `libc`, but does not expose any of them, no breaking change.

### backtrace-sys

Exposes only `libc::uintptr_t`, which is guaranteed to be `usize`, so the dependency can be considered private, no breaking change.

### bindgen

Depends on `clang-sys`. To audit.

### blurz

Depends on `dbus`. To audit.

### cgl

Exposes `libc` symbols that exist in `std::os::raw`, dependency can be killed with a breaking change because of `libc::c_void`.

### clang-sys

Exposes `libc::time_t`, breaking change.

### clap

Dependency can be [killed](https://github.com/kbknapp/clap-rs/pull/886), no breaking change.

### cocoa

Depends on `core-graphics`, breaking bump.

### core-foundation

Dependency can be killed with a breaking change after `core-foundation-sys`.

### core-foundation-sys

Dependency can be killed with a breaking change.

### core-graphics

Depends on `libc::pid_t`, but we may decide to redefine this in `core-graphics` itself, given the crate is only for macOS anyway. Then the dependency could be killed. Needs a breaking change anyway to accommodate for the breaking bump of `core-foundation`.

### core-text

Depends on both `core-foundation` and `core-graphics`, breaking change.

### device

Depends on `blurz`. To audit.

### dbus

To audit.

### dwrote

Does not use a single `libc` symbol, dependency can be removed right now.

### energymon

Dependency can be killed, no breaking change.

### energymon-default-sys

Dependency can be killed, breaking change because `energymon_sys::energymon` is reexported.

### energymon-sys

Dependency can be killed, breaking change because of `libc::c_void`.

### flate2

To audit.

### fontsan

To audit.

### freetype

To audit.

### gaol

To audit.

### harfbuzz-sys

To audit.

### heartbeats-simple

To audit.

### heartbeats-simple-sys

To audit.

### io-surface

To audit.

### ipc-channel

To audit.

### js

To audit.

### libz-sys

To audit.

### malloc_buf

To audit.

### memchr

To audit.

### miniz-sys

To audit.

### mio

To audit.

### mozjs_sys

To audit.

### net2

To audit.

### num_cpus

To audit.

### offscreen_gl_context

Depends on `cgl`, `core-foundation` and others. To audit.

### openssl

To audit.

### openssl-sys

To audit.

### openssl-sys-extras

To audit.

### parking_lot_core

To audit.

### rand

To audit.

### rayon

To audit.

### servo-egl

To audit.

### servo-fontconfig

To audit.

### servo-glutin

To audit.

### servo-skia

To audit.

### shared_library

To audit.

### syntex_errors

To audit.

### syntex_syntax

To audit.

### term_size

To audit.

### thread-id

To audit.

### tinyfiledialogs

To audit.

### webdriver

Exposes `backtrace` symbols, no breaking change to propagate.

### webrender

Depends on `core-graphics` and other crates. To audit.

### webrender_traits

Depends on `core-graphics` and other crates. To audit.

### x11

To audit.

### x11-dl

To audit.

**Comment by serprex** [comment]
flate2: https://github.com/alexcrichton/flate2-rs/pull/63

**Comment by pwnorbitals** [comment]
Is this still relevant ?

**Comment by jdm** [comment]
I don't think it's important to track this anymore.
