### ISSUE TITLE
Div with display: table-cell containing h1 positions text oddly

### ISSUE THREAD

**Issue by jdm** [servo/servo#15838]
```html
<div style="display: table-cell; border: 1px solid black; height: 3em;">
<h1>CSS FPS</h1>
</div>
```
Firefox:
<img width="137" alt="screen shot 2017-03-06 at 5 47 44 pm" src="https://cloud.githubusercontent.com/assets/27658/23609660/10588c94-0295-11e7-9f86-7c037bc63061.png">
Servo:
<img width="138" alt="screen shot 2017-03-06 at 5 47 54 pm" src="https://cloud.githubusercontent.com/assets/27658/23609665/165f182e-0295-11e7-9f76-cd791c2c0bbf.png">

**Comment by mrobinson** [comment]
This is correct in modern layout.
