### ISSUE TITLE
Clean up un-idiomatic code in HTMLImageElement::handle_event

### ISSUE THREAD

**Issue by jdm** [servo/servo#15832]
We should make the following changes to `HTMLImageElement::handle_event` in order to make it easier to read:
* invert the condition that check's the event's type, and return if it does not match (this removes a level of indentation)
* rewrite patterns like:
```
let foo = if let Some(x) = bar {
    x
} else {
    return;
};
```
to use a `match` statement instead (more compact)
* make `Area::hit_test` take the point argument by reference (htmlareaelement.rs)
* move the creation of the Point2D value out of the loop
* only call `GetBoundingClientRect` once
* rewrite the while loop as a for loop

Code: `components/script/dom/htmlimageelement.rs`, `components/script/dom/htmlareaelement.rs`

No need for tests; if the changes compile, then it's good enough for a PR.

**Comment by jdm** [comment]
Assigned to @snehasi and @riya16079.

**Comment by jdm** [comment]
Available for anybody.

**Comment by omakk** [comment]
@highfive: assign me
