### ISSUE TITLE
Clean up HTMLImageElement::areas

### ISSUE THREAD

**Issue by jdm** [servo/servo#15835]
`HTMLImageElement::areas` contains some code that is longer than necessary:
* we can invert the has_attribute check and return immediately (this avoids the need for an `else`)
* we can rewrite both `match` statements as a single `if`

Code: `components/script/dom/htmlimageelement.rs`

No need for automated tests; if the code compiles, that's good enough for a PR.

**Comment by ak1t0** [comment]
I would like to work on this issue.
@highfive: assign me

**Comment by hack3p** [comment]
@highfive, @ak1t0  ops, i'm sorry, I did not make it in time..
