### ISSUE TITLE
Make the second value of SpecifiedValue optional in border-spacing property

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#15840]
In [border-spacing](https://dxr.mozilla.org/servo/rev/511b82eea3eb3a4fdbd7b5fac61a0e292c474d60/components/style/properties/longhand/inherited_table.mako.rs#23-139) property, SpecifiedValue struct is currently combined of a horizontal and a vertical value. It's indeed true but it's grammar is like this:
`<length> <length>?`
That means the second length is optional and if it's omitted, first value applies to both horizontal and vertical value. In SpecifiedValue, we should preserve the optional status and don't write it in the ToCss method if it's omitted.

For example, currently:
If we write something like this: `border-spacing: 10px;` we will get this serialized text from ToCss method: `border-spacing: 10px 10px;` but we want it to be same as we specified.

To fix this, we need to change some parts: 
- Make vertical value optional in SpecifiedValue.
- Fix parsing code and make vertical value pass the `None` value instead of the same value as horizontal.
- Fix ToCss implementation for SpecifiedValue and prevent it to write vertical value if it's `None`.
- Fix ToComputedValue implementation and set the same value as horizontal if vertical value is None.

These changes should be enough. Also a test for this change would be great.

**Comment by Wafflespeanut** [comment]
I'll remove the easy tag, so that I can get someone from the other issue.

**Comment by crypto-universe** [comment]
It there a page, on which it is possible to check, if the fix was correct?

**Comment by canaltinova** [comment]
You can test this with a simple test case like this:
```html
<!DOCTYPE html>
<style>
    body {
        border-spacing: 10px;
    }
</style>
<script>
    console.log(document.styleSheets[0].cssRules[0].style.cssText);
</script>
```

But I guess we should give some time to consider to people in the "Looking for something to work on?" issue first.  They are waiting for a quite some time. Sorry about that.

**Comment by PhilHernandez** [comment]
Hello,
I'm interested on working on this for my first servo contribution/rust code.
@highfive: assign me

**Comment by PhilHernandez** [comment]
Hi,
Sorry to say I won't be able to work on this for the time being.
Please assign this to someone else, thanks.

**Comment by KiChjang** [comment]
@abhiaecs Would this be an issue that you're interested in?

**Comment by abhiaecs** [comment]
I am facing network issues :( .
I won't be able to work on this until network issues are resolved.
Thank you

**Comment by Dinika** [comment]
I'd love to give it a shot.
@highfive: assign me

**Comment by canaltinova** [comment]
It looks like this is fixed by https://github.com/servo/servo/pull/16144/commits/35496c8ae1e98f0a75b56b4a2a5c41ad101bcf01 Closing this, sorry!
