### ISSUE TITLE
Add gecko glue for caret-color

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#15842]
#15465 added parsing/serialization for `caret-color`. However, we still need to plug it into Stylo. Here's how we're gonna do it:

 - Move the `caret-color` definition from `components/style/properties/longhands/ui.mako.rs` to `pointing.mako.rs`
 - Change the `products` to `"gecko"` (so that we enable it for Stylo)
 - Now, we need to add `caret-color` to [this list](https://dxr.mozilla.org/servo/rev/0dbee36915abd926e61ca8571e11abf1f97ec830/components/style/properties/gecko.mako.rs#3038) add manually add `set` and `copy` methods for the property below (next to cursor's methods).
 - The former is `set_caret_color` whose signature is just like any other `set_foo` method. But, since `ColorOrAuto` is `Either<Color, Auto>`, we need to match over the variants [like this](https://dxr.mozilla.org/servo/rev/0dbee36915abd926e61ca8571e11abf1f97ec830/components/style/properties/gecko.mako.rs#2297), and for `Either::Second(_auto)`, we need to use [gecko's `auto` value](https://dxr.mozilla.org/servo/source/components/style/gecko_bindings/sugar/style_complex_color.rs#32).
 - Finally, [this Mako helper](https://dxr.mozilla.org/servo/rev/0dbee36915abd926e61ca8571e11abf1f97ec830/components/style/properties/gecko.mako.rs#304) should be called with `gecko_ffi_name='mCaretColor'` for `copy` method.

Once this is done, we need to ensure that the build succeeds by running `./mach build-geckolib`

**Comment by sendilkumarn** [comment]
@highfive: assign me

**Comment by Wafflespeanut** [comment]
Hi @sendilkumarn! Sorry, but this issue is for some people who've been waiting for days to get into Servo (which is why I removed the easy tag). So, I'm going to unassign this for now. I'll wait for them for a day or two before giving it away to someone else. If they don't respond over the period, then it's all yours :)

**Comment by Wafflespeanut** [comment]
(I'd better cc them here to avoid future pings)

@barrotsteindev @jdhorwitz @abhiaecs @o0Ignition0o - one of you is welcome to tackle this :)

**Comment by Wafflespeanut** [comment]
Since others haven't responded, @StefanoChiodino you wanna take a look at this?

**Comment by StefanoChiodino** [comment]
I'll try @Wafflespeanut ! Thanks!

**Comment by Wafflespeanut** [comment]
Awesome!

**Comment by sendilkumarn** [comment]
👍

**Comment by Wafflespeanut** [comment]
@StefanoChiodino any news on this?

**Comment by StefanoChiodino** [comment]
Hi, I've done about half of it but I'm hacking my way on the other half,
hoping I'm doing things right. I'll be honest, in general the rust skills
required for it are way above mine, but I'm finding it interesting.

**Comment by Wafflespeanut** [comment]
Oh, that's good to hear! Feel free to ping me if you have any questions :)

**Comment by StefanoChiodino** [comment]
Thanks! I think I'll commit my changes later on that don't compile right
now and show them to you

**Comment by StefanoChiodino** [comment]
@Wafflespeanut I've committed my latest changes to https://github.com/StefanoChiodino/servo now. Am I going the right direction please?
Also: There are a ton of temporary files in components/style/properties/tmp* that are not ignored in git. Shouldn't they be added to git.ignore?

Thanks!

**Comment by Wafflespeanut** [comment]
Not sure about the temporary files (I don't see those in https://github.com/servo/servo/compare/master...StefanoChiodino:master). Please open a PR, so that I can review it :)

**Comment by StefanoChiodino** [comment]
@Wafflespeanut yeah, I haven't committed them because they are clearly new, untracked, temporary files!

I'm definitively not done with it, I think I'll try to spend a bit more to see if I can manage to do it now with a fresh mind :)
