### ISSUE TITLE
HTMLImageElement::areas() doesn't seem very good at finding areas

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15884]
1. It only looks at *following siblings* of the `img` element to find a `map`
2. It panics if it doesn't find a `map`
3. It only looks at children (not descendants) of the `map` to find `area` elements

**Comment by sendilkumarn** [comment]
I would like to work on this issue 

Here are my few findings, correct me if I am wrong

> It only looks at following siblings of the img element to find a map

It should look at its `descendants`.

> It panics if it doesn't find a map

return none if map is not present

> 3. It only looks at children (not descendants) of the map to find area elements

again it should run through descendants to find area elements

**Comment by Ms2ger** [comment]
An `img` element is very unlikely to have descendants. I believe we should be looking at the descendants of its ["root"](https://dom.spec.whatwg.org/#concept-tree-root)

**Comment by sendilkumarn** [comment]
yeah right. Let me work on that.
