### ISSUE TITLE
HTMLImageElement::handle_event should use a for loop

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15885]
Code: `components/script/dom/htmlimageelement.rs`

It uses
```rust
           let mut index = 0;
           while index < elements.len() {
               // Use elements[index]
               index += 1;
           }
```

I don't see any reason it can't use `for element in elements {}`

Doesn't need a test; if it compiles, that's good enough.

**Comment by hgallagher1993** [comment]
I'll take this @highfive: assign me

**Comment by snehasi** [comment]
@highfive assign me
