### ISSUE TITLE
Implement parsing and stylo glue support for legacy gradients

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15895]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1345204#c1

Gecko supports legacy gradients, we should be parsing these. The comment linked to above gives an idea of what needs to be supported.

They probably need to be stored as extra variants on our gradient enum, and when sending to gecko they need to set the legacy gradient flag.

cc @canaltinova

**Comment by upsuper** [comment]
Dupe of #15441.
