### ISSUE TITLE
Make tidy check for -> () return values.

### ISSUE THREAD

**Issue by emilio** [servo/servo#15925]
https://github.com/servo/servo/pull/15924 introduced a few functions with `-> ()` in the signature, which isn't needed at all.

Unless there's some reason for doing it, tidy should fail when finding something like it.

@Wafflespeanut, I can't dig into tidy's source right now, would you be able to mentor this?

**Comment by Wafflespeanut** [comment]
Oh, cool with me :)

**Comment by upsuper** [comment]
> #15924 introduced a few functions with -> () in the signature, which isn't needed at all.

Ah, sorry about that. I thought I had removed all...

**Comment by lucantrop** [comment]
Hey, I'd like to do this one, if that's ok,
@highfive: assign me

**Comment by lucantrop** [comment]
I added the check and modified the tests in `servo_tidy_tests` and `./mach test-tidy --self-test` runs. However, `./mach test-tidy` reports the errors only when I run it as `./mach test-tidy --all`. I'm not sure if that's the desired behaviour or I just made a mistake somewhere.

**Comment by emilio** [comment]
Yeah, it's expected in the sense that `test-tidy` by default only runs on files you've modified IIRC. We run it on CI with the `--all` flag, so you should fix those errors before landing.

Thanks for working on this! :)
