### ISSUE TITLE
Character between U+0001 ~ U+001F in string should be escaped when serialized

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15947]
See the algorithm of https://drafts.csswg.org/cssom/#serialize-a-string

A simple test code:
```html
<!DOCTYPE HTML>
<p style="background-image: url(\f good)"></p>
<script>
let $p = document.querySelector('p');
alert($p.style.backgroundImage);
</script>
```
In this case, the serialized output should be `url("\f good")` rather than a string with unprintable char.

This is actually an issue in rust-cssparser. The corresponding code is https://github.com/servo/rust-cssparser/blob/0caaba170616cba326c4311967354110e4c79c8f/src/serializer.rs#L249-L267

This should be an easy one to fix. cc @SimonSapin

**Comment by ak1t0** [comment]
I would like to work on this issue.
@highfive: assign me

**Comment by upsuper** [comment]
Note that spec also says NULL character should be serialized to U+FFFD escaped as code point. But that doesn't match what Gecko and Blink do. Both browsers serialize NULL to U+FFFD itself, and we probably should do so here as well.

I've raised an issue to CSSWG in w3c/csswg-drafts#1105.

**Comment by upsuper** [comment]
FWIW the spec text has been fixed in the expected way.
