### ISSUE TITLE
Iframes are clipped when window is resized

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#15946]
Test case:
```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <iframe style="width: 100%;" src="about:blank">
</body>
</html>
```
<img width="1480" alt="screen shot 2017-03-14 at 9 59 47 pm" src="https://cloud.githubusercontent.com/assets/9086315/23933077/a54f7b42-0901-11e7-9f69-7c087818a8f3.png">

This can be seen evidently while using bhtml:
<img width="1698" alt="screen shot 2017-03-14 at 9 53 24 pm" src="https://cloud.githubusercontent.com/assets/9086315/23933081/b029c298-0901-11e7-9212-18f1b793555f.png">

**Comment by PeterBocan** [comment]
👍 Happens to me, as well.

**Comment by cbrewster** [comment]
This is fixed for me on the latest nightly
