### ISSUE TITLE
Implement parsing and serialization of contain property

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15955]
Syntax: https://developer.mozilla.org/en-US/docs/Web/CSS/contain

This property should be added to https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs

Hacking guide for adding property: https://github.com/servo/servo/wiki/Property-hacking-guide

**Comment by hgallagher1993** [comment]
@highfive: assign me

**Comment by KiChjang** [comment]
@hgallagher1993 You seem to have already claimed another issue, I'm unassigning this one until you finish the other one.

**Comment by jryans** [comment]
@highfive: assign me

**Comment by hgallagher1993** [comment]
@KiChjang Ehh. . .can you see what issue? Because the last one (I remember) I was assigned I made the pull request for and the issue was closed

**Comment by KiChjang** [comment]
@hgallagher1993 Huh, sorry. This is really odd, I check my notifications daily and I was very sure that I saw you commenting on another issue, I just can't seem to search for it...

**Comment by jryans** [comment]
@hgallagher1993 Did you already make progress on this, or should I continue here?

**Comment by hgallagher1993** [comment]
@jryans I did absolutely nothing with it, so your pull request is fine to go ahead :smile:
