### ISSUE TITLE
Implement parsing and serialization of initial-letter property

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15959]
Spec: https://drafts.csswg.org/css-inline/#sizing-drop-initials

This should be added into https://github.com/servo/servo/blob/master/components/style/properties/longhand/text.mako.rs

See https://github.com/servo/servo/wiki/Property-hacking-guide for a guide to hack on this issue.

**Comment by karan1276** [comment]
I would like to work on this. @highfive: assign me

**Comment by Wafflespeanut** [comment]
@karan1276 Have you made any progress on this?

**Comment by karan1276** [comment]
@Wafflespeanut not yet. I'll look into it tomorrow

**Comment by karan1276** [comment]
This would have been a fun issue to do, but i don't want to block it for too long. I have some other issues in the pipe. Someone else can work on this issue if they wish so.

**Comment by streichgeorg** [comment]
I would like to work on this then, tough I probably need some guidance.

@highfive: assign me

**Comment by jdm** [comment]
Please ask questions about anything that is unclear!

**Comment by Wafflespeanut** [comment]
Feel free to ask if you have any questions!

**Comment by streichgeorg** [comment]
So in the spec it says that the property takes the size, sink as numbers of lines, now for the computed value should I keep these values as numbers or do I already have to convert them to appunits.

**Comment by upsuper** [comment]
Keeping them in numbers should be the right way.
