### ISSUE TITLE
Some debugging options (-Z) are non operationnal

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#15963]
As far as I can tell: `show-compositor-borders`, `show-parallel-paint`, `paint-flashing`, `dump-layer-tree` and `msaa` options are not relevant anymore and should be removed.

**Comment by paulrouget** [comment]
Also, the `-Z help` text mentions `Must be used with -w option` multiple times. This is not necessary anymore.

**Comment by pyfisch** [comment]
@bors-servo assign me

`msaa` is still used in `ports/glutin/window.rs`.

**Comment by pyfisch** [comment]
@highfive:  assign me

`msaa` is still used in `ports/glutin/window.rs`.
