### ISSUE TITLE
Make layout viewer use a local copy of jquery

### ISSUE THREAD

**Issue by jdm** [servo/servo#15964]
It currently fetches https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js which makes it impossible to use when there's no internet connection available.

Code: `etc/layout_viewer/viewer.html`

To test, run `./mach run http://google.com -Z trace-layout`, then open `etc/layout_viewer/viewer.html` in your non-Servo browser when not connected to the internet.

**Comment by vlisivka** [comment]
@highfive: assign me
