### ISSUE TITLE
counter-reset and counter-increment should serialize empty vec to "none" rather than empty

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15977]
The code to fix is https://github.com/servo/servo/blob/d30978246162e8a9bfad42b43ab6a05c90421c6e/components/style/properties/longhand/counters.mako.rs#L270-L281

It should generate `none` rather than nothing when it's empty.

A new test should probably be added to https://github.com/servo/servo/blob/master/tests/unit/style/properties/serialization.rs; it can be run with `./mach test-unit -p style`.

**Comment by jdm** [comment]
I'm claiming this for an Outreachy candidate.

**Comment by epic11** [comment]
Hi
I would like to work on this.

@highfive: assign me
