### ISSUE TITLE
Add gecko glue for font-feature-settings property

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15975]
Servo has had parsing and serialization code for `font-feature-settings` property, but we need to add glue to make it usable in Gecko.

The existing parsing and serialization code is https://github.com/servo/servo/blob/d30978246162e8a9bfad42b43ab6a05c90421c6e/components/style/properties/longhand/font.mako.rs#L634-L742

The glue code should be added under https://github.com/servo/servo/blob/d30978246162e8a9bfad42b43ab6a05c90421c6e/components/style/properties/gecko.mako.rs#L1165-L1167

It seems to me that the existing property code in font.mako.rs also needs some tweak. The feature tag can be represented as a `u32`, so we should not use `String` for it. Also in Gecko's style struct, `gfxFontFeature::mTag` is a `u32` as well.

The target struct can be find in components/style/gecko_bindings/struct_debug.rs (GitHub doesn't display this file because it's too large). It should be `nsFont::fontFeatureSettings`. It is an `nsTArray`, but `gfxFontFeature` seems to be a POD type, so we can use `nsTArray::set_len_pod` for initializing its length.

**Comment by WholeGrainGoats** [comment]
I'd love to sink my teeth into this. It will be my first foray into an open source project so I hope it wouldn't be too troublesome if I asked some questions every now and then. Thanks!

**Comment by jdm** [comment]
Asking questions is encouraged!

**Comment by Wafflespeanut** [comment]
@WholeGrainGoats Have you made any progress? Need help with this?

**Comment by WholeGrainGoats** [comment]
@Wafflespeanut Yes, sorry for the hiatus. I'm trying to find out if I should write the functions myself or if the stylo hacking guide is saying that this glue code is automatically generated?

**Comment by Wafflespeanut** [comment]
Oh, you'd be writing two functions `set_font_feature_settings` and `copy_font_feature_settings` which will change the values of `gecko` fields (one will set the servo struct values to gecko struct, another will simply copy the values). The nearby set/copy methods in the file might give you an idea on how to approach this. Feel free to ping us if you're still unclear.

**Comment by WholeGrainGoats** [comment]
@Wafflespeanut I've looked over the code but I see that the T enum from [here](https://github.com/servo/servo/blob/d30978246162e8a9bfad42b43ab6a05c90421c6e/components/style/properties/longhand/font.mako.rs#L634-L742) has a value Normal. I looked at the MDN link [here](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings) and see that the specification calls to insert default values. My question is what would those values be, or perhaps what should be done when that case is encountered? What should I do with fontFeatureSettings in that case?

**Comment by Wafflespeanut** [comment]
Good question! Looking at [the gecko code](https://dxr.mozilla.org/mozilla-central/rev/7a3f514cf8490d271ee373a1d2999e4ea4dee2d7/layout/style/nsRuleNode.cpp#3971), it seems like an empty `nsTArray` (specifically, a null pointer) represents the value `normal` (I think). So, let's [truncate](https://dxr.mozilla.org/servo/rev/dc3765e231441b006f17c9aa4588e7f166bba45e/components/style/gecko_bindings/sugar/ns_t_array.rs#89) the array when we see a `normal` value.

**Comment by WholeGrainGoats** [comment]
@Wafflespeanut I've written the two functions you've asked for, converted the value to be a u32 for feature tag, and added the necessary changes to the parsing code to use u32. I'm having some difficulty testing this code, however. I inserted a print statement, changed one of the files to include font-feature-settings in the css, and it appears that the function is not being called. It could just be my confusion but am I supposed to personally test this code? If so, could you offer some assistance with this, or point me to some info on how this should be done?

**Comment by Wafflespeanut** [comment]
Nah, you won't be able to test it unless you have a Stylo build (sadly). Feel free to make a PR, and we'll test this in gecko's try server :)
