### ISSUE TITLE
Fix `calc()` behavior in layout when the container size is indefinite

### ISSUE THREAD

**Issue by stshine** [servo/servo#15986]
In layout, a computed value of `calc()` is represented by `CalcLengthOrPercentage` struct. 
According to https://drafts.csswg.org/css-values-3/#calc-computed-value

> Where percentages are not resolved at computed-value time, they are not resolved in calc() expressions, e.g. calc(100% - 100% + 1em) resolves to calc(1em + 0%), not to 1em. If there are special rules for computing percentages in a value (e.g. the height property), they apply whenever a calc() expression contains percentages.

So, when calculating the absolute length of a `calc()` value in a container and the container size is indefinite: When the `percentage` field is None, the result should be the `length` field; but when the `percentage` field is present, the result should be `Auto`.

But currently we do not implement this behavior. To fix this, you should:
* Add a method for `CalcLengthOrPercentage` in https://github.com/servo/servo/blob/403bfdaaeef567904c7b8d55784fd5db8f60ed8a/components/style/values/computed/length.rs#L78 that accept an `Option<Au>` as container size, and calculate the length according to above;
* Search through layout code, and for each usage of `LengthOrPercentage`, `LengthOrPercentageOrAuto`, `LengthOrPercentageOrNone`, `LengthOrPercentageOrAutoOrContent`,  calculate the length of the `Calc` variant using that method.

**Comment by emilio** [comment]
@stshine said he was fine mentoring this, but feel free to ask me any question too if you want to :)

**Comment by brizental** [comment]
I would like to work on this.
@highfive assign me.

**Comment by jdm** [comment]
Have you made any progress on this, @brizental?

**Comment by brizental** [comment]
Yes @jdm ! I was just now starting to actually tackle this problem. I had to stop and go through the codebase and get a little bit more used to Rust before. Sorry for the delay.

**Comment by Wafflespeanut** [comment]
@brizental ping?

**Comment by sbwtw** [comment]
Hello @brizental , are you still working on this? if not. I want to take this.

**Comment by KiChjang** [comment]
@sbwtw It looks like @brizental is unresponsive, feel free to tackle this issue!
