### ISSUE TITLE
Incorporate cargo-audit into CI process for checking for security vulnerabilities

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#15989]
https://github.com/RustSec/cargo-audit

**Comment by Darkspirit** [comment]
Run cargo audit in CI: https://github.com/bluejekyll/trust-dns/blob/0ff7817a587ead902f66d3a78082c9a893484738/Makefile.toml#L270

**Comment by Darkspirit** [comment]
This can be closed. Fixed by #26118.
https://dependabot.com/rust/
> **Automatic vulnerability scanning**
> Dependabot checks your dependencies against the RustSec Advisory Database, and creates PRs immediately for any vulnerable top-level or subdependencies.

**Comment by jdm** [comment]
cool!
