### ISSUE TITLE
Crash while scrolling

### ISSUE THREAD

**Issue by johnmuhl** [servo/servo#15995]
https://gist.github.com/johnmuhl/f78be7db85f74765ace7eb403bd5cba3

0. Download Servo nightly (2017-03-16)
1. Launch Servo with `./servo`
2. Enter `servo.org` in the address/search bar
(page loads fine)
3. Start scrolling down
(notice weird rendering)
4. Keep scrolling down
5. :bomb:

~~~
$ uname -a
Linux machine 4.10.2-1-default #1 SMP PREEMPT Sun Mar 12 19:54:41 UTC 2017 (bfb2d22) x86_64 x86_64 x86_64 GNU/Linux

$ lsb-release -a
LSB Version:	core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID:	openSUSE Tumbleweed
Description:	openSUSE Tumbleweed
Release:	20170213
Codename:	n/a
~~~

**Comment by cbrewster** [comment]
I was able to reproduce this with a similar panic to #15944.
Closing as a duplicate
