### ISSUE TITLE
text-shadow should not accept negative value for its third length

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15999]
I thought it should be fixed in #15611 but apparently it didn't.

It seems [`text-shadow`](https://github.com/servo/servo/blob/b1275591a08bec3888ee843d1f3638f63c5078a0/components/style/properties/longhand/inherited_text.mako.rs#L733-L782) doesn't actually use `Shadow::parse`, but it is probably better have it share the same parsing code.

If we want to keep the `SpecifiedTextShadow` struct rather than using `Shadow` (for saving memory?), it is probably better having a conversion function from `Shadow` to that, rather than having separate parsing code.

@karan1276, since you worked on #15490, would you like to have a look at this issue as well?

**Comment by karan1276** [comment]
@upsuper sure, why not.

**Comment by upsuper** [comment]
Thanks.

**Comment by karan1276** [comment]
I am going out of town for a week. Once i get back i will start work on this

**Comment by karan1276** [comment]
I was looking at the code. I have a few questions. Didn't we implement `Shadow` so properties like this can call it? or is there another use for it.
About the conversion system, how exactly should i go about it? 

The structure of `SpecifiedTextShadow` and `Shadow` is almost same. Wouldn't it be better to use the `Shadow` object and call the `Shadow::parse` method (just guessing) ?

**Comment by karan1276** [comment]
@highfive : assign me

**Comment by upsuper** [comment]
> The structure of SpecifiedTextShadow and Shadow is almost same. Wouldn't it be better to use the Shadow object and call the Shadow::parse method (just guessing) ?

That was my suggestion at the top of the issue as well.

**Comment by karan1276** [comment]
okay ill make changes and send pr. Ill probably get it wrong the first time, but lets see

**Comment by upsuper** [comment]
This seem to have been fixed.
