### ISSUE TITLE
Use case_insensitive_phf_map instead of iteration for system colors

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15994]
#15974 adds system colors, but it parses them by [iterating over an array](https://github.com/servo/servo/pull/15974/files#diff-b0d36fd12bfc6b3e55fa2cfb9f55acd7R129).

We should use the `ascii_case_insensitive_phf_map` [like cssparser](https://github.com/servo/rust-cssparser/blob/0caaba170616cba326c4311967354110e4c79c8f/src/color.rs#L182) to efficiently parse these.

**Comment by nodo** [comment]
Hi all, I am a new contributor to the project, I would be interested in working on this issue. @Manishearth what do you think?

**Comment by Manishearth** [comment]
Go ahead! I suggest you look at the cssparser code to get started.

**Comment by Wafflespeanut** [comment]
@nodo Did you get to look into this?

**Comment by nodo** [comment]
@Wafflespeanut not yet. However, I am planning to work on it this week. Would it be OK?

**Comment by Wafflespeanut** [comment]
No problem!

**Comment by nodo** [comment]
@Wafflespeanut @Manishearth  Sorry guys, I don't have enough time to dedicate to the project right now.  Feel free to re-assign the issue. I will came back to the project in a better time.

**Comment by smoqadam** [comment]
Hi, I'm new to Rust. I want to contribute in Servo. but I don't know where is the starting point? If I want to fix this issue what can I do?

**Comment by Wafflespeanut** [comment]
Hi! This issue may require more work, and it might not be a good first issue for you to tackle (given that you're new to the language). What about #15169? It has a few comments that should help you to start with. If that doesn't help, feel free to ask questions there :)

**Comment by vitvakatu** [comment]
@Wafflespeanut Hello, I'd like to work on this issue, as it's not assigned to everyone.

**Comment by Wafflespeanut** [comment]
Please do!

**Comment by jdm** [comment]
@vitvakatu Have you made any progress on this?

**Comment by jdm** [comment]
Unassigning due to lack of response.

**Comment by Manishearth** [comment]
(reserving for interns)

**Comment by jdm** [comment]
Unreserved after checking with Manish.

**Comment by omakk** [comment]
Hey @jdm, I'd like a crack at this, if that's okay. I had quick look and will probably come back with a few questions after I've looked some more :)

**Comment by jdm** [comment]
Sounds good!

**Comment by SergeevPavel** [comment]
Good day. I rewrote this code with `ascii_case_insensitive_phf_map`. Build passed without errors. But I don't know how to run relevant tests. Can anybody help me with it?

**Comment by Manishearth** [comment]
Push up a pull request; this probably will be fine as long as it builds. I'll run the pull request on the full test suite when you do.


`./mach test-unit -p style` is one way to run a relevant subset of the tests locally if you want to
