### ISSUE TITLE
Support -moz-force-broken-image-icon property

### ISSUE THREAD

**Issue by upsuper** [servo/servo#16001]
It seems this has the same syntax as `-moz-box-ordinal-group` so we can probably do this and #16000 together in one pr.

**Comment by upsuper** [comment]
Or we should unship this property in Gecko. See [bug 1348208](https://bugzilla.mozilla.org/show_bug.cgi?id=1348208).

**Comment by upsuper** [comment]
Given that we are not going to unship this property, we would need to implement it. Fortunately it should be easy.

**Comment by nox** [comment]
I did this.
