### ISSUE TITLE
ComplexSelector to_css should probably not do recursion

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#16019]
Currently it does:

        if let Some((ref next, ref combinator)) = self.next {
            next.to_css(dest)?;
            combinator.to_css(dest)?;
        }

which will run into crashes due to running out of stack; see https://bugzilla.mozilla.org/show_bug.cgi?id=475215

**Comment by emilio** [comment]
Happy to mentor this one.

**Comment by jdm** [comment]
Presumably we'll want to convert the code in https://dxr.mozilla.org/servo/rev/103e827948e4c3592ee93cbed8adf270588b559e/components/selectors/parser.rs#379-382 to use a loop instead?

**Comment by bzbarsky** [comment]
Yes, that is the general idea.  The complication is that you want to loop backwards over a singly linked list.

Gecko does the obvious thing here: use a growable array with some preallocated stack storage (so you don't have to heap-allocate in common cases), walk the linked list adding things to the array, then walk the array backwards in a loop.

**Comment by tictakk** [comment]
Hi, I'm looking to contribute to servo. Is this being worked on/assigned?

**Comment by emilio** [comment]
Please take it if you want! Reply to this mentioning @highfive, or saying you want to take it, and we'll assign it to you :)

**Comment by tictakk** [comment]
Okay, awesome. @highfive: assign me

**Comment by Wafflespeanut** [comment]
@tictakk Any news on this?

**Comment by tictakk** [comment]
@Wafflespeanut Spent the weekend finishing a school project and brushing up on Rust. I'll be expeditious as possible.

**Comment by Wafflespeanut** [comment]
Great!

**Comment by tictakk** [comment]
@emilio Hey, I think I could use some of that mentorship you mentioned. Should I be creating a vector of each child and looping to_css() one at a time?

**Comment by emilio** [comment]
Yes, that sounds right. We could consider creating a [`SmallVec`](https://github.com/servo/rust-smallvec) to avoid heap allocation in the common case :)
