### ISSUE TITLE
Incorrect serialization of :not(*)

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#16017]
Testcase (in stylo; I'm not sure how to get at this in servo proper):

    <style>
      :not(*) {}
    </style>
    <script>
      alert(document.styleSheets[0].cssRules[0].selectorText);
    </script>

This alerts `:not()` which is not a valid selector.

**Comment by bzbarsky** [comment]
I should note that `:not(|*)`, and `:not(*|*)` also serialize to `:not()`, which is rather odd: those selectors mean different things, and hence presumably are represented differently internally...

**Comment by bzbarsky** [comment]
And `:not(foo|*)` is serialized as the invalid selector `:not(foo|)`.  Testcase:

  <style>
    @namespace foo url(foo);
    a:not(foo|*), div { color: green; }
  </style>
  <script>
    alert(document.styleSheets[0].cssRules[1].selectorText);
 </script>

**Comment by pyfisch** [comment]
I am working on this.

Servo testcase for the first one:

```
<!doctype html>
<style>
     :not(*) {}
</style>
<script>
    alert(document.styleSheets[0].cssRules[0].cssText);

</script>
```

* Expected: `:not(*) {  }`
* Found: `:not() { }`

**Comment by pyfisch** [comment]
I am not working on this anymore. The problem is the serialization at https://github.com/servo/servo/blob/master/components/selectors/parser.rs#L440 but I do not understand the data structures used. `args` contains one element for `:not(*)` with an empty serialization. Somehow it should serialize to `*`.

**Comment by bzbarsky** [comment]
The problem is that the to_css function needs more context.  It thinks it's serializing a selector at toplevel, but the rules are slightly different inside not().

And even at toplevel Servo is kinda buggy around selectors involving wildcards.  See for example https://github.com/servo/servo/issues/16020

**Comment by pyfisch** [comment]
And this is really hard to debug because gdb does not work well with indirection and traits (but I am a beginner with it so I might have missed something) and all implementations for `Debug` just call `to_css` instead of showing the actual contents.

**Comment by pyfisch** [comment]
@highfive: assign me

Some stuff works: `not(*)`, `not(|*)` and `not(foo|*)` are serialized correctly. Surprisingly even a normal wildcard `*` was serialized as the empty string before. `*|foo` from #16020 require more changes.
