### ISSUE TITLE
:dir pseudoclass is not parsed

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#16018]
Testcase:

    <div>Some text</div>
    <style>
      :dir(ltr), div { color: green; }
    </style>

**Comment by bzbarsky** [comment]
Note https://bugzilla.mozilla.org/show_bug.cgi?id=1348479 -- this causes a bunch of stylo test_selectors test failures.

**Comment by Manishearth** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1341086 should fix this
