### ISSUE TITLE
ReflowWithNewlyLoadedWebFont is dead code?

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#16026]
The `script_layout_interface::message::Msg` enum has a `ReflowWithNewlyLoadedWebFont` variant, and `components/layout_thread/lib.rs` has code to handle messages of this variant. But nothing ever sends such messages, so this seems to be dead code.

Should we remove it? CC @pcwalton who added it in #7596.

**Comment by jdm** [comment]
Huh, I assumed that we had removed the sender at some point, but #7596 never actually added any code that sent the message.
