### ISSUE TITLE
servo-latest app consistently hangs on my Early 2011 MBP (El Capitan), and freezes it

### ISSUE THREAD

**Issue by vinodkd** [servo/servo#16038]
I've now tried downloading servo-latest.dmg and playing with it on 2 occasions, separated by 15 days. On both occasions, the Servo app makes my entire mac hang. 

Repro steps:
1. Follow instructions on download.servo.org and download servo-latest.dmg.
2. Install it into Applications folder as directed there.
3. Launch the app from the dock.

Once it launches, nothing is clickable, nor usable. It's a blank white window that occupies the center of the screen and does nothing. 

The only way to kill it is to power off using the physical button. On restart, it again starts and freezes; so the only way to prevent it from taking the machine with it is to force quit it (if I'm lucky, else wait for OSX to offer not to restart running apps).

FWIW, here are some details about my machine:
OSX El Capitan
Version: 10.11.6 (15G1217)
MacBook Pro (13-inch, Early 2011)
Processor: 2.3 GHz Intel Core i5
Memory: 16 GB 1333 MHz DDR3 (that's the one aftermarket change, so mentioning it).

I *want* to use Servo, which is why I'm trying it out. If there's a debug flag I can set to get a diagnostic report out, let me know. I guess I could get the source and build it, but I wanted to test the waters first by running the built binary.

**Comment by dralley** [comment]
This issue and its duplicate (https://github.com/servo/servo/issues/16457) seem like bugs being triggered in a graphics driver, or something.  Due to being 3 years old, should probably be closed in lieu of any more recent reports.
