### ISSUE TITLE
[mach] tell user when pip is running

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#16046]
Somehow while playing around with the servo repo, some installed python package went corrupted and I could no longer run ./mach.
I assume what happened is that I at some point terminated ./mach while it ran pip and was left behind with a half-installed python package.
I was able to resolve all problems by reinstalling all system python packages and removing and reinstalling all my pip-installed packages, still, that was quite annoying took an hour or two.

It would be nice if the mach script could tell the user when it is running pip and warn about not ctrl+c'ing until pip is done. :)

**Comment by mrobinson** [comment]
I think this is implemented now!
