### ISSUE TITLE
Removing TreeBuilder/TreeActions in html5ever and xml5ever.

### ISSUE THREAD

**Issue by Ygg01** [servo/servo#16042]
Currently, these traits are only used for namespacing (see servo/html5ever#258). 

This task entails:

*  removing traits  [TreeBuilderActions](https://github.com/servo/html5ever/blob/7634561c5edcea7fef024dff60fabfd2e53db4d2/src/tree_builder/actions.rs#L61)/[TreeBuilderStep](https://github.com/servo/html5ever/blob/7634561c5edcea7fef024dff60fabfd2e53db4d2/src/tree_builder/rules.rs#L36)/[XmlTreeBuilderActions](https://github.com/servo/html5ever/blob/7634561c5edcea7fef024dff60fabfd2e53db4d2/xml5ever/src/tree_builder/actions.rs#L18)/[XmlTreeBuilderStep](https://github.com/servo/html5ever/blob/7634561c5edcea7fef024dff60fabfd2e53db4d2/xml5ever/src/tree_builder/rules.rs#L22)
* moving implementations of above traits  into [TreeBuilder](https://github.com/servo/html5ever/blob/7634561c5edcea7fef024dff60fabfd2e53db4d2/src/tree_builder/mod.rs#L148)/[XmlTreeBuilder](https://github.com/servo/html5ever/blob/7634561c5edcea7fef024dff60fabfd2e53db4d2/xml5ever/src/tree_builder/mod.rs#L212) structs.
* fixing any breaks this causes in project.

I think this could make a great first issue, for new comers.

**Comment by jdm** [comment]
I think it makes more sense to file it in that repository instead.

**Comment by jdm** [comment]
In fact, closing this in favour of https://github.com/servo/html5ever/issues/258.
