### ISSUE TITLE
Make ImageData::new return Fallible instead of unwrapping a result

### ISSUE THREAD

**Issue by jdm** [servo/servo#16043]
Rather than panicking if ImageData::new_with_jsobject returns an error, we should make ImageData::new propagate the error to its callers instead.

Code: `components/script/dom/imagedata.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/2dcontext/pixel-manipulation/`

**Comment by methyl** [comment]
@highfive: assign me
