### ISSUE TITLE
Wikipedia rendering regression

### ISSUE THREAD

**Issue by fabricedesre** [servo/servo#16049]
At least I seem to remember we were rendering it much better. It seems that most of the styling doesn't apply: https://irccloud.mozilla.com/file/4aGom2Gq/servo-wikipedia.png

**Comment by jdm** [comment]
I have a build showing it was working as of a780f6f28cf5d0f4faa7ad84822692d9bab1d031, so we should definitely bisect.

**Comment by jdm** [comment]
Interestingly, I sometimes see the styling appear >40s after the initial page load.

**Comment by jdm** [comment]
Pretty confident that the regression is https://github.com/servo/servo/pull/14620/files#diff-e8cd2dd2c9989c693e87a030a1755bccR612, because it doesn't take the mime type's charset into account.

**Comment by jdm** [comment]
```
8aac575019ef95f49e47b6b1d428b3e0c1bc2c5d is the first bad commit
commit 8aac575019ef95f49e47b6b1d428b3e0c1bc2c5d
Author: Sumant Manne <sumant.manne@gmail.com>
Date:   Fri Dec 16 15:04:18 2016 -0600

    Implemented nosniff for fetch algorithm
```

We should change [this check](https://dxr.mozilla.org/servo/rev/e8b364793416465f6b4877414623dac2c52f2e6a/components/net/fetch/methods.rs#611) and [this check](https://dxr.mozilla.org/servo/rev/e8b364793416465f6b4877414623dac2c52f2e6a/components/net/fetch/methods.rs#618) to explicitly compare only the [toplevel and sublevel](http://doc.servo.org/mime/struct.Mime.html) types, not the entire MIME structure. If this does not affect the behaviour of `./mach test-wpt tests/wpt/web-platform-tests/fetch/nosniff/`, we should add additional tests to that suite that verify this case.

**Comment by fabricedesre** [comment]
I have a patch that fixes the wikipedia issue, but there is something weird with the tests: tests in wpt/web-platform-tests/fetch/nosniff/ should have caught that if I understand them (eg. https://dxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/fetch/nosniff/stylesheet.html#7) but our fetch nosniff code is not triggered during these tests. Still investigating.
