### ISSUE TITLE
Add parsing/serialization for grid-template-areas

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#16079]
Though the grammar is `none | <string>+`, there are a [few rules](https://drafts.csswg.org/css-grid/#propdef-grid-template-areas) for parsing the `<string>`, so it might not be easy.

**Comment by stshine** [comment]
Looks like we need to reimplement the tokenizer to parse this?

**Comment by nox** [comment]
Taking this.

**Comment by nox** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1361985
