### ISSUE TITLE
Implement element.innerText

### ISSUE THREAD

**Issue by ferjm** [servo/servo#16107]
Spec: https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute

May block #13942

**Comment by Jayflux** [comment]
Hey @ferjm whats your plan of action for this?

**Comment by ferjm** [comment]
Hello @Jayflux, I have a WIP patch for this that I'd like to finish next week (I'm afk today).

**Comment by ferjm** [comment]
The getter part landed in #19754
