### ISSUE TITLE
Replace pdqsort with sort_unstable

### ISSUE THREAD

**Issue by stjepang** [servo/servo#16120]
This issue is a follow-up to #15244. It can be a good first contribution for a newcomer to Servo.

Nightly Rust has recently got a new feature called `sort_unstable`, which provides an unstable sort algorithm on slices. It is unstable in the sense that it may not preserve the original order of equal elements after sorting. See [this](https://doc.rust-lang.org/nightly/unstable-book/sort-unstable.html) for more information.

As soon as we update Servo to the latest Rust nightly, we can completely remove Servo's dependency on `pdqsort` crate and simply use `sort_unstable` instead.

Also, we can probably just delete this [`sort_by_key` function](https://github.com/servo/servo/blob/545f8744126157d273158c5404d07fb09621d3ea/components/style/stylist.rs#L898) and use `sort_unstable_by_key` directly instead.

EDIT(2017-03-24): We can't do this just yet! We have to wait until the `sort_unstable` feature gets stabilized first.
EDIT(2017-10-15): `sort_unstable` was stabilized in Rust 1.20. Let's do this.

**Comment by SimonSapin** [comment]
Note that some Servo crates (in particular `style`) need to support stable Rust.

**Comment by SimonSapin** [comment]
`style` is the one crate that uses `pdqsort`, so this is blocked on https://github.com/rust-lang/rust/issues/40585 (stabilization of `unstable_sort`) and then on Firefox requiring the corresponding Rust version (see `rustc_min_version` in http://searchfox.org/mozilla-central/source/build/moz.configure/rust.configure)

**Comment by kammitama5** [comment]
I'm super green, but are you talking about essentially replacing sort_by_key with https://github.com/rust-lang/rfcs/blob/master/text/1884-unstable-sort.md. Seems interesting! If someone doesn't get to it in the next few days, I'd be happy to help out (with guidance!) :)

**Comment by stjepang** [comment]
@kammitama5  Yes, that would be basically it. :) However, we have to wait until the `sort_unstable` feature gets stabilized (several months at least).

**Comment by kammitama5** [comment]
:( Thanks! Always happy to help! Maybe in a few months, too I'll be back to work on that!

**Comment by stjepang** [comment]
Looks like Servo has upgraded to Rust 1.20, which means now we can use `sort_unstable` in place of `pdqsort`. Can we now label this with E-easy?

**Comment by emilio** [comment]
This is something that should probably be measured at least...

**Comment by SimonSapin** [comment]
If I remember correctly it’s the same algorithm. @stjepang, can you confirm?

**Comment by emilio** [comment]
If that's true then sure, this is totally fine :)

**Comment by stjepang** [comment]
Yeah, `sort_unstable` is literally just a copy-paste from `pdqsort` into `libcore`. :)

**Comment by savanu** [comment]
Can I take a crack at this?

These are the changes I plan to do:
1. Change sort_by_key under the style component to use the Rust's sort_unstable method. 
2. Remove the pdqsort crate dependency in Cargo.toml

Are there any tests related to this method? Or do I assume most things will break if the sort method does not work?

**Comment by emilio** [comment]
Please do!

Yes, that sounds about right. If it builds it's probably ok, we have tests that would break if the sorting was broken.

**Comment by savanu** [comment]
@highfive: assign me
