### ISSUE TITLE
parse_font_face_block should not reject a @font-face rule when it lacks font-family or src

### ISSUE THREAD

**Issue by upsuper** [servo/servo#16165]
`parse_font_face_block` currently rejects a `@font-face` rule if it lacks `font-family` or `src` descriptor. The spec says that makes the rule invalid, but it doesn't make it clear how to handle invalid rule (see w3c/csswg-drafts#1133).

All modern browsers agree on that the parser should accept such invalid rule, so I suppose the spec would follow this way as well. That said, Servo should change the behavior to match other browsers.

(This is the reason why many `@font-face`-related mochitests are still failing even after [bug 1345696](https://bugzilla.mozilla.org/show_bug.cgi?id=1345696).)

cc @SimonSapin

**Comment by SimonSapin** [comment]
I’ve commented on https://github.com/w3c/csswg-drafts/issues/1133#issuecomment-289721210 : it looks like other implementations are treating such rules as **not invalid**.
