### ISSUE TITLE
Fails to build mozjs_sys on Fedora 25

### ISSUE THREAD

**Issue by stransky** [servo/servo#16173]
I cloned the repo and followed build instructions but it fails to build mozjs_sys:
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#7cd72d8c)`
process didn't exit successfully: `/home/komat/Prednasky/OpenHouse2017/servo/target/release/build/mozjs_sys-c324e3230eb8bf78/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0:     0x5565ba87fdf3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h0c49f46a3545f908
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5565ba87c204 - std::sys_common::backtrace::_print::hcef39a9816714c4c
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x5565ba8830e7 - std::panicking::default_hook::{{closure}}::h7c3c94835e02f846
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x5565ba882c6b - std::panicking::default_hook::h0bf7bc3112fb107d
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x5565ba8834fb - std::panicking::rust_panic_with_hook::ha27630c950090fec
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x5565ba8833d4 - std::panicking::begin_panic::heb97fa3158b71158
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x5565ba883309 - std::panicking::begin_panic_fmt::h8144403278d84748
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x5565ba883297 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x5565ba8a809d - core::panicking::panic_fmt::h3b0cca53e68f9654
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x5565ba873ea9 - core::result::unwrap_failed::h789d03526c52f1ee
  10:     0x5565ba874f4a - build_script_build::main::ha63d64f680decc2b
  11:     0x5565ba883255 - std::panicking::try::do_call::h689a21caeeef92aa
                               at /checkout/src/libcore/ops.rs:2606
                               at /checkout/src/libstd/panicking.rs:454
  12:     0x5565ba88b19a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  13:     0x5565ba883a3a - std::rt::lang_start::hf63d494cb7dd034c
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  14:     0x7efc20ced400 - __libc_start_main
  15:     0x5565ba873069 - _start
  16:                0x0 - <unknown>

**Comment by jdm** [comment]
Given https://github.com/servo/mozjs/blob/master/build.rs, this appears to mean that the result of `find_make()` could not be located in your PATH.

**Comment by jdm** [comment]
Do you have a MAKE environment variable, by any chance?

**Comment by stransky** [comment]
You're right, $MAKE="/usr/bin/make" ./mach build --release does the trick!
