### ISSUE TITLE
Spheres and Transparent Rects Demos Broken in Latest Nightly Build

### ISSUE THREAD

**Issue by atouchet** [servo/servo#16188]
Both have their particles being stuck in the top left corner of the screen instead of how they are supposed to be rendered. This was tested in Windows 10.

Screenshots:

![Spheres](https://i.imgur.com/UHkJZ5C.png "Spheres")

![Rects](https://i.imgur.com/VPqGiaA.png "Rects")

**Comment by jdm** [comment]
This is tracked in #15689. Thanks for reporting it!
