### ISSUE TITLE
~20 seconds startup time on Android because CSS Layout & libfontconfig

### ISSUE THREAD

**Issue by MortimerGoro** [servo/servo#16195]
Hello,

I found that Servo on Android takes a lot of time to show anything on screen in most pages because CSS layout operations wait for libfontconfig initialization, which takes about 20 seconds (tested on Google Pixel). The problem seems to be that libfontconfig tries to read all system fonts on the FcInit method, and that takes a lot of time. This is done on every startup, the cache doesn't seem to work. Even if we can fix the cache, 20 seconds is a huge time for the first startup and it could ruin the initial impression for users when running servo. I also experienced some startup problems in the past on Windows, it might be related to this problem too.

On other platforms fontconfig caches can be prebuilt on the installation scripts, but this can't be done on Android with plain apks.

Some ideas to fix the issue:
- Modify libfontconfig and filter the scanned font's on startup on Android. Only load the default ones used here: https://github.com/servo/servo/blob/c025a794dd709e9e8acf6cd82e28769df954313a/components/gfx/font_cache_thread.rs#L137
- Don't block CSS layout when libconfig is not initialized and relayout when libfontconfig is ready
- I think that firefox uses libfontconfig on Android. At least a grep of the FF source shows that lib fontconfig is used by the cairo library. Maybe they had this issue too, we can research what they did.

What do you think?

**Comment by jdm** [comment]
This sounds like the same issue described in https://github.com/servo/servo/issues/12931, and https://github.com/servo/servo/issues/12931#issuecomment-281719607 described a particular reason why the cache wasn't working.
