### ISSUE TITLE
Should we permit woff2 font hints?

### ISSUE THREAD

**Issue by jdm** [servo/servo#16257]
URL font sources are ignored if they provide a hint that [does not match](https://dxr.mozilla.org/servo/rev/5ef8a0a2f7917792105cf28f6e581a92e863c3dd/components/style/font_face.rs#120) truetype, opentype, or woff. I've seen sites using woff2 as a format; do we support that?

**Comment by nox** [comment]
I whitelisted `woff2` in `FontFace::effective_sources` and https://elixir-lang.org still didn't use the correct font it was supposed to use. I conclude we don't support woff2 fonts.

**Comment by jdm** [comment]
I'm curious if anything has changed now that https://github.com/servo/servo/pull/18994 has merged.

**Comment by krk** [comment]
Test page http://filamentgroup.github.io/woff2-feature-test/test.html

Servo: `Supports WOFF2: false`
Firefox 66: `Supports WOFF2: true`

**Comment by atouchet** [comment]
I've noticed that the proper fonts from the new https://www.rust-lang.org/ don't load in Servo. Ex: https://www.rust-lang.org/static/fonts/woff2/AlfaSlabOne-Regular.latin.woff2

Would this be the reason why?

**Comment by jdm** [comment]
That seems likely.
