### ISSUE TITLE
Inner document of iframe is null

### ISSUE THREAD

**Issue by zarazek** [servo/servo#16270]
I'm getting `null` when accessing `document` property of iframe. The same code on Firefox works correctly (it returns `HTMLDocument` object).
[test.zip](https://github.com/servo/servo/files/896156/test.zip)

**Comment by KiChjang** [comment]
Can you show us the JS code that you've used to access the `document` property? My guess is that the iframe is cross-origin, which we don't support yet.

**Comment by zarazek** [comment]
I attached the file with html and js code to the first comment.

**Comment by jdm** [comment]
Yes, this behaves as described when run from a file:// URL (where every URL is cross-origin), but works as expected when run from an http:// URL (where the iframe is same-origin). This is a symptom of #15233, so I'll close it in favour of that. Thanks for reporting it!
