### ISSUE TITLE
Stringification of iframe.contentWindow object throws an exception

### ISSUE THREAD

**Issue by zarazek** [servo/servo#16271]
Exception is thrown when attempting to stringify `iframe.contentWindow` property. The same code works correctly on Firefox (it stringifies to `'[object Window]'`)

[test-2.zip](https://github.com/servo/servo/files/896216/test-2.zip)

**Comment by jdm** [comment]
This occurs when the testcase is run from a file:// URL, which means that we have a dissimilar-origin Window object, hence "ERROR:script::dom::bindings::error: Error at :0:0 SecurityError: The operation is insecure" in the output.

cc @asajeffrey

**Comment by asajeffrey** [comment]
If this is run from a file URL, then it's doing the right thing, this should throw a security error. Can you run it from http? (I usually use `python -m SimpleHTTPServer` for ad hoc http).

**Comment by jdm** [comment]
Ah, right. This is working as intended; Firefox treats file:// URLs as same-origin while Servo does not. This works as expected when run over an HTTP server.
