### ISSUE TITLE
Windows daily builds ?

### ISSUE THREAD

**Issue by nico-onmap** [servo/servo#16287]
In july 2016 I read that Windows builds were coming soon but there is still no sign of Windows builds on [servo.com](https://download.servo.org/): is it still being worked on?

Any ETA?

**Comment by hgallagher1993** [comment]
This is the last task blocking it AFAIK 16198

**Comment by jonathandturner** [comment]
Confirmed, fixing the keyboard issue is the last one blocking the nightly.

**Comment by est31** [comment]
See also #12125

**Comment by aneeshusa** [comment]
Windows nightly builds are [now released](https://blog.servo.org/2017/04/13/windows/)!
