### ISSUE TITLE
Fix marking of inorder flag for float's children in block.rs

### ISSUE THREAD

**Issue by pradeep90** [servo/servo#1628]
In `BlockFlow::assign_widths`, to compute the value of `has_inorder_children`, we currently check whether `self.base.num_floats > 0` for the case when `self.is_float()`. 

`self.base.num_floats` is always 1 for floats, because in `bubble_widths` we set `num_floats` to 1 and set `self.float.get_mut_ref().floated_children` to the actual `num_floats` value.

This sets the inorder flag of all floats' children to true, which is not correct.

Change the if-body in `assign_widths` from `self.base.num_floats > 0` to `self.float.get().floated_children` and test if everything still works.

Also, change the same thing for `has_inorder_children` in `BlockFlow::assign_height_float`.
Better yet, extract that into a method.

**Comment by mbrubeck** [comment]
I think this is fixed after a bunch of major changes to this code in recent months.
