### ISSUE TITLE
./mach test-wpt fails on Linux machines with nVidia blob installed.

### ISSUE THREAD

**Issue by glennw** [servo/servo#16290]
At some point in the build process, libGL is added to the libraries.

On machines with the nVidia blob driver installed, the nVidia libGL gets (some?) functions loaded by gleam when running in headless mode with OSMesa.

This results in all kinds of things being broken - e.g. max texture size is reported as 0 etc.

**Comment by glennw** [comment]
@emilio Do you have any ideas what may cause this?

cc @bholley

**Comment by emilio** [comment]
hmmm wat, that sounds fun. I think I have hardware to try to reproduce it and dig a bit.

**Comment by dralley** [comment]
Does this still happen?

**Comment by jdm** [comment]
Doesn't seem important to track without it actively breaking anybody's workflow right now.
