### ISSUE TITLE
Report empty title tags as a style violation

### ISSUE THREAD

**Issue by jdm** [servo/servo#16323]
It's easy to create new tests with the default `<title></title>` and forget to give the test a meaningful title. We should make `./mach test-tidy` report this as an error by adding a new method to tidy.py like `check_toml` that iterates over the lines of any html file.

Code: `python/tidy/servo_tidy/tidy.py`
Tests: add a testcase to `python/tidy/servo_tidy_tests/`, then add a method to `test_tidy.py` that verifies that the error is reported. Run it with `./mach test-tidy --self-test`.

**Comment by ZehCnaS34** [comment]
Hello! I'm working on a `check_html` method for the tidy script, and I'm wondering how you would like to handle the `img`  tag.

This is what I have so far:
![screenshot from 2017-04-11 03-56-57](https://cloud.githubusercontent.com/assets/1127553/24898450/f980d246-1e6a-11e7-8aa6-8ef7851cc191.png)

Would you like me to add a "white-list" of approved empty tags, or keep the empty image tag as an issue?

**Comment by Wafflespeanut** [comment]
No, we should fix the titles of those files which cause the error.

Also, please notify us before you begin to work on an issue so that we could (assign it to you and) reduce duplicate efforts.

**Comment by jdm** [comment]
@ZehCnaS34 That appears to be reporting empty tags besides `<title>`.

**Comment by Wafflespeanut** [comment]
Oh, nvm, looks like I misread this.

**Comment by ZehCnaS34** [comment]
@Wafflespeanut Alright, I will do so in the future. Sorry for the lack of communication!

**Comment by jdm** [comment]
No, that's not the case. You are welcome to work on it; you are just encouraged to let us know when you start working on it, rather then when you first have questions after doing some work.

**Comment by ZehCnaS34** [comment]
Do you want the test to yield an error if there is no title tag in the HTML file (Case 1), or only when there is an empty title tag? (Case 2)

Example of Case  1
```html
<!-- A.html -->
<html>
</html>
```
```html
<!-- B.html -->
<html>
  <title></title>
</html>
```
In case 1, both HTML files would raise a flag.


Example of Case 2
```html
<!-- A.html -->
<html>
</html>
```

```html
<!-- B.html -->
<html>
  <title></title>
</html>
```
In case 2, only file B.html would raise a flag.

**Comment by jdm** [comment]
I can't figure out how to solve this issue, as described in #16660.
