### ISSUE TITLE
Unable to enter credentials on a microsoft login page

### ISSUE THREAD

**Issue by NiLSPACE** [servo/servo#16346]
When going to a login page from Microsoft I'm unable to click any element, almost as if there is an invisible div on top of the page. When first going to the page I am able to enter my email address though since the input element is automatically selected.

~~I'm currently on a Windows machine, but I'll try it on Linux once I get home.~~

URL: https://login.microsoft.com/

**Comment by NiLSPACE** [comment]
I've got the same problem on Linux.

**Comment by jdm** [comment]
I made a minimal testcase that reproduces the problem:
```html
<style>
  div {
    position: fixed;
    right: 0;
  }
</style>
<div><input></div>
```
This also happens with `bottom: 0`, but not with `left: 0` or `top: 0`.

**Comment by NiLSPACE** [comment]
It seems to be similar to #16405 where the hitbox doesn't update.

**Comment by jdm** [comment]
That's a different issue, since this one does not involve scrolling.

**Comment by NiLSPACE** [comment]
This seems to be fixed now.

**Comment by jdm** [comment]
My reduced testcase is fixed as well. Thanks for checking!
