### ISSUE TITLE
Implement parsing and serialization of touch-action property

### ISSUE THREAD

**Issue by upsuper** [servo/servo#16372]
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

Gecko seems to support `none,` `auto`, `pan-x`, `pan-y`, and `manipulation`. We need to support them in stylo.

**Comment by pyfisch** [comment]
To which *.mako.rs should this property be added? I did not find one obviously correct.

**Comment by canaltinova** [comment]
It should be in `box.mako.rs`. We generally use the same struct architecture as gecko and in gecko, touch-action is in nsStyleDisplay struct. It corresponds to Box in Servo. As far as I remember there was a chart that shows which struct corresponds to which(in wiki or somewhere) but I couldn't find it.

**Comment by ferjm** [comment]
@canaltinova this might be the chart you were referring to https://public.etherpad-mozilla.org/p/aligning-style-structs

**Comment by canaltinova** [comment]
@ferjm Ah yes, this is it. Thanks!

**Comment by nox** [comment]
@pyfisch Are you working on this?

**Comment by pyfisch** [comment]
No, I just looked at it.
