### ISSUE TITLE
Support other values of pointer-events

### ISSUE THREAD

**Issue by upsuper** [servo/servo#16397]
There are several other values we need to support for `pointer-events` in stylo, which are: `visiblePainted visibleFill visibleStroke visible painted fill stroke`.

Simply adding
```rust
extra_gecko_values="visiblePainted visibleFill visibleStroke visible painted fill stroke",
```
seems to hit an assertion
```
assertion failed: `(left == right)` (left: `"visiblePainted"`, right: `"visiblepainted"`): string patterns must be given in ASCII lowercase
```
which may need some investigation.

**Comment by nox** [comment]
The spec doesn't seem to say whether these values are supposed to be case-sensitive or not.

**Comment by nox** [comment]
If they are not, we can just do:

```python
extra_gecko_values="visiblepainted visiblefill visiblestroke visible painted fill stroke"
```

**Comment by upsuper** [comment]
Yeah, we can just do that. Although it would be better if we can serialize those values to the canonical form defined in the spec, but it seems Gecko is already serializing them to lowercase form, so it is probably fine to do this for now.

We may want to fix that eventually, but that's definitely not a priority.
