### ISSUE TITLE
alignment shorthand parsing is incorrect

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#16391]
When https://github.com/servo/servo/pull/16322 landed we fixed some Gecko failures, but picked up a bunch of new ones:

> FAIL | layout/style/test/test_property_syntax_errors.html | invalid value 'center safe' not accepted for 'place-content' property
got "center safe", expected ""

> FAIL | layout/style/test/test_property_syntax_errors.html | invalid value 'unsafe start' not accepted for 'place-content' property
got "start unsafe", expected "" 

@tamamu @upsuper

**Comment by bzbarsky** [comment]
Also:

>  FAIL | layout/style/test/test_property_syntax_errors.html | invalid value 'end legacy left' not accepted for 'place-items' property
got "end left legacy", expected ""

**Comment by KWierso** [comment]
These are actually still failing on autoland (and since I merged, assuming they'd be fixed, mozilla-central). Any idea what I'd need to do to properly annotate these failures?

**Comment by KWierso** [comment]
The expectations update that landed earlier accidentally omitted the ".html" in the test name, causing it to not apply. Fixed in https://hg.mozilla.org/integration/autoland/rev/b3ef306a6bf0

**Comment by nox** [comment]
Why are these values forbidden? I can't find anything related to them in the spec.

**Comment by nox** [comment]
Oh I see, while it is a shorthand, it doesn't mean all the values from the longhands are allowed.
