### ISSUE TITLE
Incorrect rendering of "Transparent Rectangles" and "Spheres" demo

### ISSUE THREAD

**Issue by komawoyo** [servo/servo#16401]
latest servo nightly windows 8.1x64
everything is stuck in the top left corner

![image](https://cloud.githubusercontent.com/assets/18315233/24990914/d5269b42-1fdc-11e7-9059-bce2b9a44260.png)

![image](https://cloud.githubusercontent.com/assets/18315233/24990944/1adb3fe4-1fdd-11e7-9653-689e240f9bb1.png)

(note that this was not an issue in older builds)

**Comment by jdm** [comment]
This is tracked in #15689. Thanks for reporting it!
