### ISSUE TITLE
Don't make a network request when the media attribute of a link element is modified

### ISSUE THREAD

**Issue by jdm** [servo/servo#16404]
Spun off from #16399 because this is a separate issue from the panic that was being triggered.

**Comment by jdm** [comment]
According to https://html.spec.whatwg.org/multipage/links.html#link-type-stylesheet:concept-link-obtain we should only initiate the network request when one of the given conditions is true. The media attribute changing is not included in that list.

**Comment by janvi-palan** [comment]
@jdm I will take this up!
