### ISSUE TITLE
all sorts of layout problems with dell.com

### ISSUE THREAD

**Issue by zspitzer** [servo/servo#16417]
layout is is all over the place

![image](https://cloud.githubusercontent.com/assets/426404/24994567/ca7abdda-206e-11e7-8d67-5292930d91eb.png)

Also seeing the style sheet issue in #16399

**Comment by jdm** [comment]
With #16407 applied I don't see any issues with the layout:
<img width="1138" alt="screen shot 2017-04-13 at 5 33 05 pm" src="https://cloud.githubusercontent.com/assets/27658/24994683/470eeee8-206f-11e7-96b0-9a2ab07b039d.png">

**Comment by zspitzer** [comment]
just went to check, dell.com now crashes the nightly build

**Comment by jdm** [comment]
That's another instance of the panic from #17840.
