### ISSUE TITLE
text rendering problems - https://www.themonthly.com.au/

### ISSUE THREAD

**Issue by zspitzer** [servo/servo#16416]
Text rendered as X's on the https://www.themonthly.com.au/

The header image clipped (but it's a SVG, so known)

**Comment by jdm** [comment]
That's super weird!
<img width="322" alt="screen shot 2017-04-13 at 5 24 00 pm" src="https://cloud.githubusercontent.com/assets/27658/24994396/ff0d6954-206d-11e7-80d4-86b0635c16d3.png">

**Comment by jdm** [comment]
Minimal testcase:
```html
<style>
@font-face {
  font-family: "Gotham A";
  font-style: normal;
  font-weight: 800;
  src: url("data:application/x-font-woff;base64,d09GRk9UVE8AADS8AA0AAAAAWFQAAQAAAAAynAAAAiAAAAZ8AAAAAAAAAABDRkYgAAAJQAAAH8IAACgewCmgokdERUYAACkEAAAAHgAAACAA4QAER1BPUwAAKSQAAAdCAAAbRMAboxRHU1VCAAAwaAAAA$
}
p {
  font-family: 'Gotham A';
  text-transform: uppercase;
}
</style>
<p>The Nation Reviewed</p>
<p>THE NATION REVIEWED</p>
```

**Comment by jdm** [comment]
I figured this out after bashing my head against it for a bunch of hours. The code in `flush_clump_to_list` iterates through the fragment text character by character, and uses that character to determine which font to use. When a run mapping is flushed, we run `apply_style_transform_if_necessary` which performs the uppercase transformation, and later we create a TextRun using the transformed characters and the font chosen earlier. This can yield incorrect results if the transformed character is not available in the font that was selected based on the original character.

The straightforward fix for this particular testcase looks like:
```diff
diff --git a/components/layout/text.rs b/components/layout/text.rs
index b8e9456..8933972 100644
--- a/components/layout/text.rs
+++ b/components/layout/text.rs
@@ -200,6 +200,13 @@ impl TextRunScanner {

                 let (mut start_position, mut end_position) = (0, 0);
                 for (byte_index, character) in text.char_indices() {
                    let character = match text_transform {
                        text_transform::T::none => character,
                        text_transform::T::uppercase => character.to_uppercase().next().unwrap(),
                        text_transform::T::lowercase => character.to_lowercase().next().unwrap(),
                        _ => character,
                    };

                     // Search for the first font in this font group that contains a glyph for this
                     // character.
                     let font_index = fontgroup.fonts.iter().position(|font| {
``` 
However, this does not account for:
* text-transform: capitalize
* transformations that yield multiple characters where the second is not available in the font selected for the first

I suspect the first issue is more important than the second, and I'll spend some time thinking about the right way to do this.

**Comment by mrobinson** [comment]
This seems to be working on non-legacy layout, so I'm going to go ahead and close this one.
