### ISSUE TITLE
Typing in forms is slow and unresponsive

### ISSUE THREAD

**Issue by colinwyers** [servo/servo#16411]
Sometimes when I press a letter in a form, it won't respond at all (30 seconds or more), but when I press it again, it will show up... and then when I press the next letter, the previous letter shows up. Happened multiple times when attempting to enter HN username to login. URL bar also affected.

**Comment by codec-abc** [comment]
I think this is the same as #12937. A fix should have landed yesterday. Are you running the last version?

**Comment by jdm** [comment]
There is only one version on windows.

**Comment by SaschaNaz** [comment]
I think #12937 is not yet landed on nightly build, the same issue still happens on Windows.

**Comment by NiLSPACE** [comment]
That is most likely the issue: 
![image](https://cloud.githubusercontent.com/assets/1160867/24995990/537802d4-2031-11e7-9b6b-4a7b7b08066e.png)

**Comment by SaschaNaz** [comment]
And probably because #16390 is not merged yet.

**Comment by codec-abc** [comment]
Can it be closed now?

**Comment by atouchet** [comment]
Is this issue still valid? Windows text input was supposed to have been fixed back in #16390.

**Comment by SaschaNaz** [comment]
I think this can be closed.
