### ISSUE TITLE
Support non-negative parsing of lengths for Either<Length, T> types

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#16423]
In `components/style/values/specified/length.rs`, [we have this](https://dxr.mozilla.org/servo/rev/4c851925fbbd8446f6bfc36ff6836e9b24ad635b/components/style/values/specified/length.rs#583-614), which all do the same thing i.e., (try to) parse non-negative lengths. So, let's have a generic `impl<T> Either<Length, T>` which has a `parse_non_negative_length` method.

**Comment by yashmehrotra** [comment]
I would like to work on this one.
@highfive: assign me
