### ISSUE TITLE
Windows build doesn't even launch

### ISSUE THREAD

**Issue by 0xffffabcd** [servo/servo#16420]
The window appears very briefly then closes immediately after. 

I'm on Windows 10 version 1703 (OS Build 15063.13) x64.

**Comment by eddyb** [comment]
What if you run it from `cmd.exe`? And what's your graphical setup?

**Comment by SimonBuckner** [comment]
I have the same. Launch from start menu or from cmd.exe you see a window quickly flash up and then disappear. Nothing special on my setup. Dell XPS 13 with DisplayLink connected display running Windows 10 - 1607 (14393.1066).

**Comment by 0xffffabcd** [comment]
> What if you run it from cmd.exe

Same result and no debug info is printed to the console

> what's your graphical setup

Not sure what you mean but here's the dump from [dxdiag](https://gist.github.com/anonymous/6fbaa265a049239065e581a0eecca332)

**Comment by jdm** [comment]
This sounds like the same problem described in #16393.

**Comment by dralley** [comment]
Outdated
