### ISSUE TITLE
Windows nightly build fails due to missing VCRUNTIME140.dll and MSVCP140.dll

### ISSUE THREAD

**Issue by olavmrk** [servo/servo#16422]
When trying to launch the nightly build of Servo on Windows 10, a dialog box is shown:

> The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix this problem. 

Clicking OK on this error twice gives a new error:

> The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by olavmrk** [comment]
I worked around this problem by installing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145), but I guess it should be integrated into the application somehow?

**Comment by jmcomets** [comment]
I installed VC++2015 and am now getting a missing `api-ms-win-crt-runtime-l1-1-0.dll`.
Note: I'm using Windows 7.

**Comment by mestaritonttu** [comment]
[A comment](https://www.reddit.com/r/programming/comments/653rdp/servo_windows_nightly_builds_now_available/dg7z5rh/) regarding this:

this is violating Rule #1 of Windows programs: Never ever depend on the CRT DLL, statically link that in instead. Then you just depend on Kernel32 and User32 instead.

**Comment by yashpalgoyal1304** [comment]
> I installed VC++2015 and am now getting a missing `api-ms-win-crt-runtime-l1-1-0.dll`.
> Note: I'm using Windows 7.

@jmcomets https://github.com/servo/servo/issues/25787
