### ISSUE TITLE
servo crashed due to an access violation after panic (?) on windows

### ISSUE THREAD

**Issue by Trolldemorted** [servo/servo#16429]
After most likely running into https://github.com/servo/servo/issues/14637, servo crashed.

Attaching visual studio's debugger yielded this:

```
Exception at 0x00007FF6EACAA316 in servo.exe: 0xC0000005: Access violation during read at position 0x0000000000000000

>	servo.exe!00007ff6eacaa316()	Unbekannt
 	servo.exe!00007ff6e9a1e352()	Unbekannt
 	servo.exe!00007ff6eacb7862()	Unbekannt
 	servo.exe!00007ff6eab6d6f0()	Unbekannt
 	servo.exe!00007ff6eab74534()	Unbekannt
 	servo.exe!00007ff6eab72bd6()	Unbekannt
 	servo.exe!00007ff6eab6f07c()	Unbekannt
 	servo.exe!00007ff6eab729e3()	Unbekannt
 	servo.exe!00007ff6eac9d5f4()	Unbekannt
 	servo.exe!00007ff6eab338e9()	Unbekannt
 	servo.exe!00007ff6eab36699()	Unbekannt
 	servo.exe!00007ff6ea1f557c()	Unbekannt
 	servo.exe!00007ff6e9916381()	Unbekannt
 	servo.exe!00007ff6e97bb58c()	Unbekannt
 	[External Code]	
 	servo.exe!00007ff6ea89357c()	Unbekannt
 	servo.exe!00007ff6ea891fa5()	Unbekannt
 	servo.exe!00007ff6ea8800f5()	Unbekannt
 	servo.exe!00007ff6ea1f73ff()	Unbekannt
 	servo.exe!00007ff6e9e1f6d7()	Unbekannt
 	servo.exe!00007ff6e9b00408()	Unbekannt
 	servo.exe!00007ff6e9c9e5cb()	Unbekannt
 	servo.exe!00007ff6e9c9757a()	Unbekannt
 	servo.exe!00007ff6e97baa94()	Unbekannt
 	servo.exe!00007ff6ea8934a2()	Unbekannt
 	servo.exe!00007ff6e994f40a()	Unbekannt
 	servo.exe!00007ff6ea88fe8f()	Unbekannt
 	[External Code]	
```

System:
W 10 Pro N 64bit

**Comment by jdm** [comment]
What page were you loading?

**Comment by Trolldemorted** [comment]
http://www.spiegel.de/

Unfortunately it does not always crash, nor do the "layout thread unreachable" warnings pop up everytime.

**Comment by Trolldemorted** [comment]
Attempting to open the page using the urlbar is buggy as well, by the way. Most of the time pressing enter does not do anything, and now i got this error:

![otheroserror](https://cloud.githubusercontent.com/assets/10261186/25003427/a24dc8bc-204f-11e7-935d-6ba08a19efee.PNG)

unfortunately a not very elaborate one (sounds like a separate issue again). Does servo store logs in a readable format somewhere? I assume you can't do much with an "other os error".

**Comment by jdm** [comment]
I can reproduce #16409 when loading this page, so I expect it should work better in the next nightly build.

**Comment by dralley** [comment]
Outdated
