### ISSUE TITLE
Visiting Wolfram Alpha Triggers Crash

### ISSUE THREAD

**Issue by sciguyryan** [servo/servo#16438]
Hi guys.

This is another interesting one I've noticed while playing around with the Servo build. This triggers a crash as follows:

![crash - wolfram alpha](https://cloud.githubusercontent.com/assets/2759895/25011593/d5aa04f8-2065-11e7-85f4-0ae8cc665288.PNG)

To Reproduce:
First, open Servo and navigate to the following page: https://www.wolframalpha.com/ - this must be done from within Servo, not via command line or whatnot.
Second, navigate to any of the sub-sections by clicking the section headers. I clicked the one labelled "Mathematics" for this example.
Third, click the first example (immediately below the "do basic arithmetic" label). Servo will then crash and exit, giving the screen as shown above.

Interestingly going directly to the page (https://www.wolframalpha.com/input/?i=125+%2B+375&lk=3) doesn't seem to trigger this at all. It seems to function as expected, albeit with a few styling issues.

Unfortunately I was unable to click the "Report Crash" button so I couldn't get a trace for this.

This has been tested on Windows 10, 64-bit with the most recent nightly build.

If I can offer any further information please let me know.

**Comment by jdm** [comment]
I reproduced the panic on macOS, and it's #16409. That means that it should behave much better in tomorrow's build!

**Comment by sciguyryan** [comment]
This appears to have been fixed by the latest nightly build.

**Comment by jdm** [comment]
Thanks for confirming it!
