### ISSUE TITLE
Servo Tech Demo (Windows nightly build) unable to start correctly

### ISSUE THREAD

**Issue by jrp55** [servo/servo#16433]
Started from Start menu on Windows 7
![servo-start](https://cloud.githubusercontent.com/assets/12686341/25007845/bde7e59e-2059-11e7-98ab-d361e01def5a.png)

**Comment by jrp55** [comment]
Same result if run from cmd.exe

**Comment by atouchet** [comment]
Possibly related to #16393 or #16431.

**Comment by lygstate** [comment]
+1

**Comment by jdm** [comment]
Let's track this in #16431.
