### ISSUE TITLE
Text Corruption Visiting digg.com

### ISSUE THREAD

**Issue by sciguyryan** [servo/servo#16434]
Hi all.

After visiting digg.com the text within the page appears to become corrupted. This seems to occur when scrolling part way down the page to the sponsored ad - [here](https://www.rxbar.com/digg/rxbarsample?utm_source=article&utm_campaign=digg&utm_medium=SC&utm_term=article1&utm_content=001). This also seems to affect the text in the user interface. Please see the screenshots below for reference.

The first image shows the effect on the user interface: http://i.imgur.com/WWIByvn.png
The second image shows the corrupted text on the main page: http://i.imgur.com/Iwj4T3g.png
The third image shows the resulting error from attempting to load the page directly: http://i.imgur.com/ufUCs0I.png

This has been tested on Windows 10, 64-bit with the most recent nightly build. Unfortunately clicking the "submit crash report" button didn't seem to function in this instance either.

If I can offer any further information please let me know.

**Comment by sciguyryan** [comment]
This still appears to be an issue in the latest nightly and can still be reproduced with the steps above.

**Comment by pcwalton** [comment]
cc @glennw — IIRC this happens when WR runs out of texture space for whatever reason

**Comment by dralley** [comment]
Page works fine for me now - may have changed in the intervening 3 years
