### ISSUE TITLE
assertion failed: self.stylesheet.borrow().is_none() ()

### ISSUE THREAD

**Issue by CodeGradox** [servo/servo#16430]
I'm running the Servo Developer Preview for Windows on Windows 10.

When I try to access a thread (any thread, really) on 4chan.org I get the following error.

`assertion failed: self.stylesheet.borrow().is_none() ()`

I also can't seem to submit a report through the browser as I can't click the submit button.

![servo error](https://cloud.githubusercontent.com/assets/8555819/25005094/c4cf2f7c-2057-11e7-8a36-ea1c8822ba17.png)

**Comment by jdm** [comment]
This is tracked in #16399 and should be fixed by #16407.
