### ISSUE TITLE
Strange Text Behaviour on html5test.com

### ISSUE THREAD

**Issue by sciguyryan** [servo/servo#16436]
Hi guys.

This one is a little odd and I wasn't quite sure how to word the title as there really doesn't seem to be a good way of describing what happens here.

This occurs when visiting html5test.com and scrolling down to the "Elements" section after the test has been completed. This can take a few seconds.

The text appears to animate and "fall" before resetting. This appears to happen over and over again. I have recorded a gif to demonstrate what appears to be happening: 

![text behaviour](https://cloud.githubusercontent.com/assets/2759895/25010861/492948b0-2063-11e7-855d-d0ea60b82f05.gif)

There also appear to be a few other text oddities on that page - text randomly vanishing and reappearing (visible on the Forms section of the page). I'm not sure if the issues are related or not so I'm hesitant to file seperate issues for these unless someone indicates that I should do so.

This has been tested on Windows 10, 64-bit with the most recent nightly build.

If I can offer any further information please let me know.

**Comment by sciguyryan** [comment]
This seems a little better in today's nightly build. It now only seems to do this while the page is loading and stops after a short time.

**Comment by sciguyryan** [comment]
I can no longer reproduce this issue in the latest nightly build. I'm unsure which pull would have fixed this though.

Yipee!

**Comment by jdm** [comment]
Thanks for following up!
