### ISSUE TITLE
Today's latest servo for windows. can not type url and press enter to visit new site.

### ISSUE THREAD

**Issue by netroby** [servo/servo#16448]
Today's latest servo for windows. can not type url and press enter to visit new site.

**Comment by zspitzer** [comment]
the latest nightly seems to have resolved that problem (builds need timestamps!)

**Comment by netroby** [comment]
Yeah， please Add timestamp to install.msi

such as installer-20170414145608.msi

**Comment by atouchet** [comment]
There is an issue for Servo build time stamps here: https://github.com/servo/download.servo.org/issues/11
