### ISSUE TITLE
Interaction between border-radius and box-shadow can lead to top border of the box-shadow being clipped

### ISSUE THREAD

**Issue by sciguyryan** [servo/servo#16475]
The following is a comparison of the rendering between Firefox and Servo.

1. This is the reference rendering on Firefox. You can see the top border created by the box shadow clearly. ![firefox](https://cloud.githubusercontent.com/assets/2759895/25063928/ad3fb8d6-21e7-11e7-9023-ddb9f99f7537.PNG)
2. This is the rendering under Servo. You can see the top border created by the box shadow is missing. ![servo](https://cloud.githubusercontent.com/assets/2759895/25063949/e410c418-21e7-11e7-8b68-d0c930b79194.PNG)

A live example of this can be seen in the [reduced test case](https://github.com/servo/servo/files/923629/reduced.test.case.zip) included with this report. This can also be seen on the Google search box. Sorry, it had to be a zip file - github wouldn't permit me to upload the HTML version.

This has been tested on Windows 10, 64-bit with the most recent nightly build.

**Comment by jdm** [comment]
It's always easier to include the testcase inline:
```html
<style type="text/css">
div
{
  border-radius: 2px;
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.16),0 0 0 1px rgba(0,0,0,0.08);
}
</style>
<div style="margin-top: 100px; width: 50%;">text text text text</div>
```

**Comment by sciguyryan** [comment]
Good call, I'll do that in the future. I wasn't aware if that was considered a good or bad thing to do.

**Comment by jdm** [comment]
This seems to render correctly in my macOS build:
<img width="514" alt="screen shot 2017-04-15 at 11 56 28 pm" src="https://cloud.githubusercontent.com/assets/27658/25064124/32df0dbc-2237-11e7-9f81-7506c8a298c0.png">

**Comment by sciguyryan** [comment]
Windows only then? That's definitely interesting.

**Comment by emilio** [comment]
Wouldn't it be a build before #16284 landed by any chance?

**Comment by sciguyryan** [comment]
> Wouldn't it be a build before #16284 landed by any chance?

I'm afraid not, the build was yesterdays nightly build. As there doesn't seem to be a way to obtain a build ID I can't really tell you exactly which build this was.

**Comment by sciguyryan** [comment]
This appears to be fixed for me in the latest nightly. I'm not sure when this was fixed but the issue is no longer reproducible.

Does this require a test to ensure it doesn't regress again in the future?

**Comment by jdm** [comment]
In general no. Thanks for following up!
