### ISSUE TITLE
tidy: Make tidy check that opening and closing braces that begin a line do so with proper alignment.

### ISSUE THREAD

**Issue by emilio** [servo/servo#16486]
I think it makes sense if we enforce the invariant that at least a `{` or `}` that begins a line should do so with a multiple of 4 spaces to the left. That'd prevent stuff like https://github.com/servo/servo/pull/16293#discussion_r111661247 from landing.

@Wafflespeanut wanna mentor this one? or should I? (should be easy)

**Comment by coalman** [comment]
@highfive: assign me

Should have a PR soon.
