### ISSUE TITLE
Servo Windows icon isn't using recommended dimensions

### ISSUE THREAD

**Issue by atouchet** [servo/servo#16484]
Currently the Servo.ico file in Windows includes support for 16x16, 24x24, 32x32, and 64x64 dimensions. According to https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485%28v=vs.85%29.aspx 24x24 and 64x64 are used for Classic Mode which as far as I can tell is for icons in the Control Panel. For applications 16x16, 32x32, 48,48, and 256x256 is recommended.

For reference the Firefox Windows icon uses 16x16, 32x32, 48,48, and 256x256.

**Comment by atouchet** [comment]
cc @metajack who I believe added the current icon.

**Comment by metajack** [comment]
It should be extremely easy to replace the ico file with a corrected one. Just use the resources/servo.png file and resize it to the correct dimensions, combine these into the ico file, and submit a PR replacing resources/Servo.ico.

I think I used some online tool to create the .ico file from that PNG, but I don't recall which tool.

**Comment by atouchet** [comment]
@highfive: assign me
