### ISSUE TITLE
servo cannot display pages in languages other than english

### ISSUE THREAD

**Issue by antonkulaga** [servo/servo#16493]
I've tried to open several Russian websites by latest nighty, like http://samlib.ru and I got "?" signs everywhere with freezing afterwards (so, I even could not switch the encoding manually)

**Comment by meecoffee** [comment]
me too so awful

**Comment by jdm** [comment]
This issue here is that Servo assumes all pages are using the utf-8 character set, but that page uses windows-1251.

**Comment by jdm** [comment]
This is being tracked in #6414. Thanks for reporting it!
