### ISSUE TITLE
Clicking links ignoring scrolling

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#16504]
Seems like we're ignoring scrolling when we're trying to figure out which link was clicked on.  If I point to a link on the first page, and then scroll without moving my mouse, if I click on a link that's below the fold it still loads the link from the first page.

This happens on the current nightly in both macOS and Windows.

**Comment by cbrewster** [comment]
Filed here with test case #16405

**Comment by jonathandturner** [comment]
Thanks.  That's what I get for filing bugs on the way out of the door 😄
