### ISSUE TITLE
Interface button hitboxes out of place in latest nightly build

### ISSUE THREAD

**Issue by atouchet** [servo/servo#16507]
Tested in Windows 10.

Steps to reproduce:

1. Load one of the sites from the homepage links.
2. Try to click an interface button such as new tab.
3. Button doesn't do anything.

**Comment by NiLSPACE** [comment]
They are working, but it seems the hitbox is moved down a little.

**Comment by atouchet** [comment]
Ah you may be right. It appears I can still click on them by clicking underneath the button location.

**Comment by NoahConnors** [comment]
I also have this problem. Hope it gets fixed.

**Comment by mangecoeur** [comment]
Confirm issue on macOS

**Comment by atouchet** [comment]
Is this still an issue on other operating systems? I'm no longer able to reproduce it on Windows.

**Comment by atouchet** [comment]
@mangecoeur are you still experiencing this issue on macOS?

**Comment by atouchet** [comment]
Closing this as I can no longer reproduce the issue and aren't getting any confirmation that it's still a problem in other operating systems.
