### ISSUE TITLE
Put the system font stuff stashed on ComputedValues in its own struct

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#16518]
https://github.com/servo/servo/pull/16517 stashes a `cached_system_font` on the ComputedValues type. We also stash a `font_size_keyword` thing. These should be hidden away in a struct.

The system font stuff only exists in gecko mode, so it would need to be appropriately `cfg`d.

To test that this works, both `./mach build -p style -d` and `./mach build-geckolib` should pass.

**Comment by jklepatch** [comment]
@highfive: assign me

**Comment by Manishearth** [comment]
(You'll need to wait for https://github.com/servo/servo/pull/16517 to land)

**Comment by jklepatch** [comment]
@Manishearth ok
Could it be possible to have a quick chat on IRC about this issue? This is my first PR, I have a couple of questions :)

**Comment by emilio** [comment]
That PR was reverted due to thread-safety issues in Gecko, so this needs to wait a bit more. Happy to help over IRC when that re-lands, feel free to ping us directly on `#servo` in `irc.mozilla.org` :)

**Comment by jklepatch** [comment]
@emilio ok I will wait :-)

**Comment by emilio** [comment]
I think it landed now, right @Manishearth?

**Comment by Manishearth** [comment]
Yep!

**Comment by jklepatch** [comment]
cool, Ill start working on it

**Comment by Manishearth** [comment]
Are you still working on this?

**Comment by Manishearth** [comment]
Reassigning to Simran, please let us know if you're still interested on working on something and I'll find a different bug.

**Comment by jklepatch** [comment]
Ooops, sorry for dropping this..
