### ISSUE TITLE
Investigate using separate layout tasks for elements under CSS containment

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#1651]
If our layout tasks are cheap enough we might be able to spawn a new one for every element affected by CSS containment, allowing for greater parallelism and lazy block layout.

Relevant draft spec: http://dev.w3.org/csswg/css-containment/

**Comment by mrobinson** [comment]
I think we aren't interested in this any longer as we no longer have a separate layout tasks. Ideally, this is handled through rayon now.
