### ISSUE TITLE
https://people-mozilla.org/~jmuizelaar/implementation-tests/dl-test.html renders wrong

### ISSUE THREAD

**Issue by jrmuizel** [servo/servo#16534]
https://people-mozilla.org/~jmuizelaar/implementation-tests/dl-test.html should not have any space between the boxes but it does in Servo

**Comment by atouchet** [comment]
That link no longer works.

**Comment by jdm** [comment]
@jrmuizel Any chance you have those tests saved elsewhere?

**Comment by jrmuizel** [comment]
https://jrmuizel.github.io/implementation-tests/dl-test.html

**Comment by atouchet** [comment]
![Test](https://i.imgur.com/wkuA3W2.png)

This seems to be fixed now as far as I can tell.

**Comment by jrmuizel** [comment]
Indeed.
