### ISSUE TITLE
Implement 2008 syntax of WebKit gradients

### ISSUE THREAD

**Issue by nox** [servo/servo#16542]
Follow-up of https://github.com/servo/servo/issues/15441#event-1050225942.

**Comment by pyfisch** [comment]
The only thing left to do are the keywords `cover` and `contain`? This is fixed in https://github.com/pyfisch/servo/commit/3a2893793c9463c7c137751f491a8703e3bca397 (not yet merged). In the compatibility spec I did not find more differences. Anything else?

**Comment by nox** [comment]
It's not specified. See the comment linked in the issue description, that links to https://bugzilla.mozilla.org/show_bug.cgi?id=1241623.
