### ISSUE TITLE
Overflow:hidden should not apply to descendants that are absolutely positioned with an ancestor containing block

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#16547]
Failing test case:

https://people-mozilla.org/~jmuizelaar/tmp/overflow.html
```html
<div style="width: 100px; overflow:hidden; background: red">
  <div>
    Food
    <div>Mark
      <div style="position:absolute; left: 100px; background: green">Hello</div>
    </div>
  </div>
</div>
```

See https://www.w3.org/TR/CSS2/visufx.html#q11.0

"[overflow] affects the clipping of all of the element's content *except any descendant elements (and their respective content and descendants) whose containing block is the viewport or an ancestor of the element.*" (emphasis mine)

**Comment by jdm** [comment]
This will need much more information about the expected solution for `E-less easy` to apply.

**Comment by mrobinson** [comment]
I'm fairly certain this was fixed by https://github.com/servo/servo/pull/16463, just three days before this bug was filed. 😄

I verified that the test appears to be passing, but if I'm mistaken please re-open.
