### ISSUE TITLE
Mouse being all janky: click locations being off from actual locations

### ISSUE THREAD

**Issue by NoahConnors** [servo/servo#16552]
I don't know if this issue has already been addressed or if this is just a me thing, but whenever I want to click on something in the UI (not on a website), the location where I have to have my mouse is always downward from where the actual thing that I want to click on is. Say I wanted to go back a page. This is where my mouse would have to be: 
<img width="1920" alt="cursorposition" src="https://cloud.githubusercontent.com/assets/23250975/25259295/eab082fa-260a-11e7-9197-44e87e3efa27.png">

Maybe something to fix...

**Comment by jdm** [comment]
Tracking in #16507. Thanks for reporting it!
