### ISSUE TITLE
Inconsistent :hover background rendering (manual testcase)

### ISSUE THREAD

**Issue by sciguyryan** [servo/servo#16559]
Hi guys.

Using the manual test included below. Hover over the first list element and it will correctly render with a red background. We would expect the same to be true of the second but this isn't the case with Servo. It is intermittently rendered with a red background as the mouse is moved around within the visual bounds of the element but it isn't consistently kept red while the cursor is within the visual bounds of the element. If either the overflow or position rules are removed it renders correctly.

This case renders as expected in both Firefox and Chrome.

```html
<!DOCTYPE html>
<html>
<head>
    <title>testcase</title>
        <style>
        li {
            overflow: hidden;
            border-bottom: 1px solid #000;
            position: relative;
        }
        li:hover {
            background: #f00;
        }
        </style>
</head>
<body>
    <ul>
        <li>test</li>
        <li>test 2</li>
    </ul>
</body>
</html>
```

Unfortunately it isn't really possible to screenshot this effect as it only happens when hovering but I was able to provide a gif snapshot of the screen while performing the test above. 

![hover behaviour](https://cloud.githubusercontent.com/assets/2759895/25277633/68c074a2-2697-11e7-8179-a58db089adfd.gif)

This was found on the latest nightly build.

**Comment by sciguyryan** [comment]
This problem still seems to exist in the most recent Servo nightly builds.

**Comment by jdm** [comment]
This regressed at some point between 533853fdce029d7184a33f7d08bfce7cbd6248c8 and ef5c61e8338ca550b970f9de20e014c3b4165bd5.

**Comment by jdm** [comment]
This is a regression from #16336. cc @mrobinson

**Comment by mrobinson** [comment]
I think the issue here is that hit testing is no longer taking into account overflow:hidden clipping, since the previous code wasn't taking into account overflow:scroll clipping before. This should be possible to fix by testing whether the cursor position is clipped out when processing scroll roots.

**Comment by sciguyryan** [comment]
This appears to have been fixed in the latest nightlies. I'm not sure when exactly but it is no longer an issue!

Yipee!

**Comment by sciguyryan** [comment]
Does this need a new test added to cover potential regressions?

**Comment by sciguyryan** [comment]
Does this need a new test added to cover potential regressions?

**Comment by jdm** [comment]
I don't think we can test hover behavior yet.
