### ISSUE TITLE
Clean up warnings

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#16584]
We should clean up the warnings when compiling on master.
<details>

```
warning: variable does not need to be mutable
   --> /home/servo/buildbot/slave/linux-rel-css/build/target/release/build/script-40acd45dee03fa46/out/Bindings/MutationObserverBinding.rs:483:17
    |
483 |             let mut argc = 2;
    |                 ^^^^^^^^
    |
    = note: #[warn(unused_mut)] on by default

   Compiling compositing v0.0.1 (file:///home/servo/buildbot/slave/linux-rel-css/build/components/compositing)
   Compiling glutin_app v0.0.1 (file:///home/servo/buildbot/slave/linux-rel-css/build/ports/glutin)
warning: method is never used: `char_to_script_key`
   --> /home/servo/buildbot/slave/linux-rel-css/build/ports/glutin/window.rs:696:5
    |
696 |       fn char_to_script_key(c: char) -> Option<constellation_msg::Key> {
    |  _____^ starting here...
697 | |         match c {
698 | |             ' ' => Some(Key::Space),
699 | |             '"' => Some(Key::Apostrophe),
...   |
794 | |         }
795 | |     }
    | |_____^ ...ending here
    |
    = note: #[warn(dead_code)] on by default

   Compiling constellation v0.0.1 (file:///home/servo/buildbot/slave/linux-rel-css/build/components/constellation)
   Compiling layout_thread v0.0.1 (file:///home/servo/buildbot/slave/linux-rel-css/build/components/layout_thread)
   Compiling libservo v0.0.1 (file:///home/servo/buildbot/slave/linux-rel-css/build/components/servo)
   Compiling servo v0.0.1 (file:///home/servo/buildbot/slave/linux-rel-css/build/ports/servo)
warning: unused import: `servo::config`
  --> main.rs:36:5
   |
36 | use servo::config;
   |     ^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
```
</details>

**Comment by KiChjang** [comment]
I suspect the `char_to_script_key` function is actually used in a Windows build, so the correct fix there should be to add a `#[cfg(windows)]` attribute there,

**Comment by jdm** [comment]
The `let mut argc = 2` warning is in generated code, so it's also not easy to fix.

**Comment by aacunningham** [comment]
It also looks like the unused import `servo::config` is used in an Android build. I'm pretty new to the language, but I'm not sure if you can conditionally import like you can with functions.

**Comment by cbrewster** [comment]
@aacunningham You can add`#[cfg(target_os = "android")]` above the import.

**Comment by aacunningham** [comment]
@cbrewster Interesting, didn't find that in the book, but maybe I rushed through the conditional compiling section.

Then two out of three warnings are simple to solve. If I had some guidance on the best way to handle the `let mut argc = 2` issue, I could solve this.

**Comment by jdm** [comment]
Let's add `unused_mut` to the list at https://dxr.mozilla.org/servo/source/components/script/dom/bindings/codegen/CodegenRust.py?q=let+mut+argc&redirect_type=single#1852 to solve the last one.

**Comment by aacunningham** [comment]
@jdm Thanks, sounds good!

If no one has an issue, I'll start working on this and should have a PR soon.
@highfive: assign me

**Comment by aacunningham** [comment]
@cbrewster It looks like in the meantime, some new build warnings have shown up. Should I try and address them in this ticket as well, or just leave my PR to the original warnings?

If I'm addressing the new build issues, would it just be best to ask the one who committed the code if they know if it's used anywhere? My `grep`-foo is only getting me so far.

```
warning: method is never used: `origin`
  --> /home/aaronc/Coding/rust/servo/components/script/dom/dissimilaroriginlocation.rs:48:5
   |
48 | /     pub fn origin(&self) -> &MutableOrigin {
49 | |         self.window.origin()
50 | |     }
   | |_____^
   |
   = note: #[warn(dead_code)] on by default

warning: method is never used: `origin`
  --> /home/aaronc/Coding/rust/servo/components/script/dom/dissimilaroriginwindow.rs:68:5
   |
68 | /     pub fn origin(&self) -> &MutableOrigin {
69 | |         self.globalscope.origin()
70 | |     }
   | |_____^
   |
   = note: #[warn(dead_code)] on by default

warning: method is never used: `origin`
  --> /home/aaronc/Coding/rust/servo/components/script/dom/location.rs:64:5
   |
64 | /     pub fn origin(&self) -> &MutableOrigin {
65 | |         self.window.origin()
66 | |     }
   | |_____^
   |
   = note: #[warn(dead_code)] on by default
```

**Comment by jdm** [comment]
Go ahead and add `#[allow(dead_code)]` above each of those methods.

**Comment by aacunningham** [comment]
@jdm Thanks for the quick reply, will do.
