### ISSUE TITLE
Windows: Backspace does not work consistently

### ISSUE THREAD

**Issue by SaschaNaz** [servo/servo#16599]
1. Type github.com
2. Long-press backspace key
3. Deleted characters randomly reappears

![servo-backspace](https://cloud.githubusercontent.com/assets/3396686/25370986/3b23a93a-29c9-11e7-9b1b-2978488b04ef.gif)

**Comment by paulrouget** [comment]
That looks like a browser.html bug. Can you please file the issue there: https://github.com/browserhtml/browserhtml/issues ?

**Comment by SaschaNaz** [comment]
Moved: https://github.com/browserhtml/browserhtml/issues/1294
