### ISSUE TITLE
allow OpenSSL 1.0.2 on Debian Testing

### ISSUE THREAD

**Issue by TerraX-net** [servo/servo#16605]
Downloaded https://download.servo.org/nightly/linux/servo-latest.tar.gz on Debian Testing (Stretch)
> ./servo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Overview: https://packages.debian.org/search?lang=de&suite=stretch&searchon=names&keywords=libssl
Debien Jessie: libssl.so.**1.0.0** https://packages.debian.org/de/jessie-backports/amd64/libssl1.0.0/filelist
Debian Stretch: libssl.so.**1.0.2**
 https://packages.debian.org/de/stretch/amd64/libssl1.0.2/filelist

There is no 1.0.0 on Debian testing (stretch), only libssl.so, libssl.so.1.0.2 and libssl.so.1.1.

No solution:
> sudo ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
> sudo ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0

because
> ./servo
> ./servo: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version \`OPENSSL_1.0.0' not found (required by ./servo)
> ./servo: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version \`OPENSSL_1.0.1d' not found (required by ./servo)
> ./servo: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version \`OPENSSL_1.0.1' not found (required by ./servo)
> ./servo: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version \`OPENSSL_1.0.0' not found (required by ./servo)
> ./servo: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version \`OPENSSL_1.0.1' not found (required by ./servo)

Could you please allow 1.0.2 or 1.1?

**Comment by jdm** [comment]
Closing in favour of #14203.

**Comment by TerraX-net** [comment]
indeed, 1.1.0 would be the better solution, thank you :)
