### ISSUE TITLE
script thread should call runnable.main_thread_handler(self)?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#16636]
At the moment, https://github.com/servo/servo/blob/master/components/script/script_thread.rs#L1094 calls runnable.handler() rather than runnable.main_thread_handler(self). This can cause a lot of hoop-jumping with TLS because the script thread doesn't pass itself into the runnable.

**Comment by cbrewster** [comment]
Should be ok to do this, if `main_thread_handler` is not implemented, by default it will just call `handler`.

**Comment by jdm** [comment]
This change was made.
