### ISSUE TITLE
wptrunner moved upstream

### ISSUE THREAD

**Issue by jgraham** [servo/servo#16633]
wptrunner just merged from its own repo into w3c/web-platform-tests. Next time you do a sync it probably makes sense to change from using the harness in the separate harness directory to the one that will appear in `tests/wpt/web-platform/tests/tools/wptrunner`. Once you do this it will be possible to upstream wptrunner patches just like any other wpt change.

cc @nox @jdm

**Comment by jdm** [comment]
This happened.
