### ISSUE TITLE
Generated code from try builds can affect merging other PRs

### ISSUE THREAD

**Issue by jdm** [servo/servo#16632]
In #16624 we see a build failure caused by types added in #16622, which was sent to try last night but hasn't merged yet.

**Comment by SimonSapin** [comment]
It looks like generated code in the `script` crate is not re-generated when it should have been?

One way to definitely fix this is to revert #611, but that would also cause a regression in CI cycle time so I’d prefer to explore other options first.

**Comment by jdm** [comment]
Since the cmake build that runs the codegen process is synchronous ([afaik](https://github.com/servo/servo/blob/master/components/script/build.rs#L45)), I guess the culprit would be the [makefile](https://github.com/servo/servo/blob/master/components/script/CMakeLists.txt).

**Comment by jdm** [comment]
I think I have it figured out - the binding generation depends on the set of files in [the webidls/ directory](https://github.com/servo/servo/blob/master/components/script/CMakeLists.txt#L71). #16622 added files to this but didn't modify any others, so subsequent PRs do not see any reason to regenerate the bindings because of the files listed there have been modified.

**Comment by jdm** [comment]
Due to the continued bustage, I reverted the change on the builders in https://github.com/servo/saltfs/pull/651.

**Comment by SimonSapin** [comment]
@jdm Does https://github.com/servo/saltfs/pull/651 fix this or should we keep it open?

**Comment by jdm** [comment]
It does actually affect local builds where you switch branches after doing a build that adds a webidl file.

**Comment by nox** [comment]
Why are try builds even ran from the same directories as actual builds?

**Comment by jdm** [comment]
This is no longer the case in the non-buildbot world.
