### ISSUE TITLE
Update clang-sys to 0.14.1

### ISSUE THREAD

**Issue by cpeterso** [servo/servo#16653]
clang-sys v0.14.1 contains @emilio's fix (KyleMayes/clang-sys#51) for [Firefox bug 1356150](https://bugzilla.mozilla.org/show_bug.cgi?id=1356150) where build-time bindgen was broken on Ubuntu 17.04 (Zesty Zapus).

**Comment by upsuper** [comment]
Is there still something blocking us from updating Servo to use the latest bindgen?

**Comment by nox** [comment]
This was done.
