### ISSUE TITLE
sequence<any> conversion code is entirely broken

### ISSUE THREAD

**Issue by jdm** [servo/servo#16678]
Given WebIDL like `void foo(sequence<any> seq)`, our conversion code calls [FromJSValConvertible::from_jsval](https://github.com/servo/rust-mozjs/blob/560362f3e4bddf160962cea444892a3cde0affb2/src/conversions.rs#L603-L647) which appends handles to roots that only exist for a single loop iteration.

**Comment by jdm** [comment]
The only existing use of this type is in https://dxr.mozilla.org/servo/source/components/script/dom/webidls/IterableIterator.webidl#14 . #16622 encountered this problem when attempting to add a new use.

**Comment by jdm** [comment]
This is another instance that would have been prevented by https://github.com/servo/rust-mozjs/issues/153.

**Comment by emilio** [comment]
I'm to blame on that one, I think. Sorry about that :(

**Comment by jdm** [comment]
I don't think there's anything wrong with the existing sequence conversion code; it's the way that it interacts with https://github.com/servo/rust-mozjs/commit/04e9e3a47c20c4e7b396404506fd89dd91f03e57 and https://github.com/servo/rust-mozjs/issues/153 that's broken here.

**Comment by jdm** [comment]
The way to solve this is to follow Gecko's example. Pass sequence types by reference, and have a SequenceRooter stack value in the generated bindinds which ensures the sequence does not move and is registered with the GC so it can trace its contents. Additionally, just store the raw GC pointers inside the vector, rather than handles or heaps.

For future reference:
* https://dxr.mozilla.org/mozilla-central/source/obj-x86_64-pc-linux-gnu/dom/bindings/WorkerBinding.cpp#459
* https://dxr.mozilla.org/mozilla-central/rev/41958333867b0f537271dbd4cb4ba9e8a67a85a8/dom/bindings/BindingUtils.h#2135
* https://dxr.mozilla.org/mozilla-central/rev/41958333867b0f537271dbd4cb4ba9e8a67a85a8/dom/bindings/BindingUtils.h#1990

**Comment by jdm** [comment]
My outstanding question is how stuff like https://dxr.mozilla.org/mozilla-central/rev/41958333867b0f537271dbd4cb4ba9e8a67a85a8/dom/console/Console.cpp#641 is safe in the presence of a moving GC, since I don't see how the sequence values would trigger barriers correctly.

**Comment by KiChjang** [comment]
If we're going to such lengths to solve this, would it be easier to solve for `sequence<object>` instead? Or would this approach also solve the same problem?

**Comment by jdm** [comment]
This solution should generalize to object sequences as well.

**Comment by jdm** [comment]
```
<jonco> jdm: the SequenceRooter template class inherits from JS::CustomAutoRooter and instances of this class get traced on minor GC
```

**Comment by KiChjang** [comment]
i.e. We need support for CustomAutoRooter but I recall that it's ways ahead of what we can do now?

**Comment by jdm** [comment]
Yeah, CustomAutoRooter is based around:
a) C++ inheritance
b) not moving
It's exactly like `Rooted<T>` in that regard (which we support via the `rooted!` macro).

**Comment by jdm** [comment]
I believe work required is the following:
* re-implement https://dxr.mozilla.org/mozilla-central/rev/ee21e5f7f1c1726e0ed2697eb45df54cdceedd36/js/src/jspubtd.h#283 in Rust (just like [this code](https://github.com/servo/rust-mozjs/blob/1dc8aab23b9428f0a4162dd39009cd2b686e5f3a/src/rust.rs#L353-L390) reimplements the similar parts of [Rooted<T>](https://dxr.mozilla.org/mozilla-central/rev/ee21e5f7f1c1726e0ed2697eb45df54cdceedd36/js/public/RootingAPI.h#800-871,801)
* create a SequenceRooter Rust type that makes use of this new Rust CustomAutoRooter implementation (based off of the [C++ implementation](https://dxr.mozilla.org/mozilla-central/rev/ee21e5f7f1c1726e0ed2697eb45df54cdceedd36/dom/bindings/BindingUtils.h#2297))
* create a macro that can create a new SequenceRooter value [like rooted! for Rooted<T> values](https://github.com/servo/rust-mozjs/blob/master/src/rust.rs#L454-L464)
* make the bindings code generator in CodegenRust.py create a SequenceRooter that roots the vector that will hold the values in the converted sequence

**Comment by Xanewok** [comment]
As a follow up from #5014, we'd like to tackle this, and possibly related issues, as a team (@marmistrz, @mrowqa, @taki-jaro) for our bachelor thesis project.
We'll do the work described in https://github.com/servo/servo/issues/16678#issuecomment-341191799 and ask over at IRC when we have any questions/problems. Is that okay?

**Comment by jdm** [comment]
Absolutely!

**Comment by jdm** [comment]
If you don't get the responses you need from IRC, please follow up by asking the questions here.

**Comment by NeverHappened** [comment]
Oh, I've already started this one..

**Comment by jdm** [comment]
@NeverHappened I assume you are `nhpd` from https://mozilla.logbot.info/servo/20171101#c13793878-c13793985? What have you done so far?

**Comment by NeverHappened** [comment]
I'm mostly reading the code. I figured most of the places where the changes will be. Now trying to understand how to modify CGCallGenerator in python code to use the custom rooters.

**Comment by jdm** [comment]
If that's the case, I would prefer to have Xanework and their team work on this, since we've been making plans about how it fits into their academic requirements.

**Comment by NeverHappened** [comment]
Okay, no problem :)

**Comment by jdm** [comment]
Further plans from discussion with @Xanewok:
* create a FromJSValConvertibleInto trait uses an `&mut T` argument instead of returning the converted value in the return value (use `Result<(), ()>` instead)
* remove the FromJSValConvertible implementation for `HandleValue` (this will prevent `sequence<any>` from being allowed right now)
* add an implementation of FromJSValConvertibleInto for `Vec<T>` where `T: FromJSValConvertible`
* modify the code generation for sequences that contain values that require rooting to create a sequence rooter, then use FromJSValConvertibleInto to fill the empty vector with the converted values

**Comment by KiChjang** [comment]
After discussing with @Xanewok in IRC, he found out that the current conversion from a JSArray to a `Vec<JSVal>` is not broken, which can be seen [here](https://gist.github.com/Xanewok/80ed9c9fa20286cb6971f190009c90e8#file-gist-rs-L49-L55), and this makes me wonder - perhaps our bindings should just generate `Vec<JSVal>` for `sequence<any>`? The only difference I see here is that `Vec<HandleValue>` carries a vector of pointers, rather than actual `JSVal`s.

**Comment by jdm** [comment]
Let's look at some examples of how these assumptions can go wrong. If we start with that gist (and uncomment the JS_GC call), we do not observe any crashes. This is because there is an explicit root on the stack for the array value; if we make the following change, the program crashes because the root is no longer present:
```diff
--- tests/rootcrash.rs	2017-11-23 10:46:44.000000000 -0500
+++ /tmp/foo	2017-11-23 10:46:37.000000000 -0500
@@ -48,8 +48,11 @@

-        rooted!(in(cx) let mut rval = UndefinedValue());
+        let converted = {
+            rooted!(in(cx) let mut rval = UndefinedValue());

-        rt.evaluate_script(global.handle(),
+            rt.evaluate_script(global.handle(),
                            "new Array(null, {'inner': 1, 'a': 'as'}, {'inner': 2}, null, undefined);",
                            "test", 1, rval.handle_mut()).unwrap();
-        let converted = Vec::<Value>::from_jsval(cx, rval.handle(), ()).unwrap();
+            let converted = Vec::<Value>::from_jsval(cx, rval.handle(), ()).unwrap();
+            converted
+        };
         let converted = converted.get_success_value().unwrap();
```
If we make the following change so there is a JS value referencing the array (event though we have no stack root for it), the crash goes away:
```diff
--- /tmp/foo	2017-11-23 10:46:37.000000000 -0500
+++ tests/rootcrash.rs	2017-11-23 10:49:01.000000000 -0500
@@ -52,3 +52,3 @@
             rt.evaluate_script(global.handle(),
-                           "new Array(null, {'inner': 1, 'a': 'as'}, {'inner': 2}, null, undefined);",
+                           "var a = new Array(null, {'inner': 1, 'a': 'as'}, {'inner': 2}, null, undefined); a",
                            "test", 1, rval.handle_mut()).unwrap();
```
What I wish to illustrate is how volatile making assumptions about GC behaviour can be. It might appear that it is safe to create a `Vec<JSVal>` and then another `Vec<HandleValue>` from that, since the JS values we're using are all reachable from the JS that calls this code. However, here is another change we can make to the code which makes the testcase crash:
```diff
--- /tmp/foo	2017-11-23 10:46:37.000000000 -0500
+++ tests/rootcrash.rs	2017-11-23 13:29:15.000000000 -0500
@@ -52,3 +52,3 @@
             rt.evaluate_script(global.handle(),
-                           "new Array(null, {'inner': 1, 'a': 'as'}, {'inner': 2}, null, undefined);",
+                           "var a = new Array(null, {'inner': 1, 'a': 'as', 'toString': function() { a = null; return Object.prototype.toString(this); }}, {'inner': 2}, null, undefined); a",
                            "test", 1, rval.handle_mut()).unwrap();
@@ -62,13 +62,10 @@
         assert!(GetPropertyKeys(cx, obj1, JSITER_OWNONLY, ids.get()));
-        assert_eq!(ids.len(), 2);
+        assert_eq!(ids.len(), 3);

+        let s = "not a string".to_owned();
         let types: Vec<_> = converted.iter().map(|val| {
-                 if val.is_undefined()  { "undef" }
-            else if val.is_null()       { "null" }
-            else if val.is_number()     { "number" }
-            else if val.is_primitive()  { "number" }
-            else if val.is_string()     { "string" }
-            else if val.is_object()     { "object" }
-            else if val.is_symbol()     { "symbol" }
-            else                        { "whoops" }
+            let s = <String as FromJSValConvertible>::from_jsval(cx, HandleValue::from_marked_location(val), ())
+                .ok().and_then(|r| r.get_success_value().map(|s| s.to_owned()))
+                .unwrap_or(s.clone());
+            s
         }.to_owned()).collect();
```
Now the testcase invokes toString() on each member of the array, and that clears the reference from JS so there is once again nothing preventing the values from being GCed. This is why we need something like SequenceRooter, because there are too many ways for our assumptions to be violated by malicious JS code.
