### ISSUE TITLE
`mach clean-nightlies` removes geckolib rustc without cause

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#16675]
Reported by @nox on IRC, I'm the last one to touch this.

@nox, can you provide more details on what goes wrong so this can be fixed?

**Comment by jdm** [comment]
If you run `./mach build-geckolib`, then upgrade the nightly in rust-nightly-hash twice, I expect the next `./mach build` removes the stable rust compiler used by `./mach build-geckolib`. This is not a good result :)

**Comment by jdm** [comment]
Actually, judging by the implementation, it looks like clean-nightlies will just always remove the stable compiler because it never appears in the git history for rust-commit-hash.

**Comment by SimonSapin** [comment]
@aneeshusa At any point there are two "current" Rust versions for Servo, given by the `rust-commit-hash` and `rust-stable-version`. Look for `use_stable_rust` in the Python code.

**Comment by aneeshusa** [comment]
Thanks for the info, that's helpful to know. Since there are two "current" versions, what would you expect the behavior of the `--keep` flag to `mach clean-nightlies` to do? Should it keep the last `n` rust versions overall, the last `n` for nightlies and stable separately, or something else?

**Comment by SimonSapin** [comment]
The two versions are upgraded independently, so I think they should be cache-evicted independently too. Keep `n` of each. By the way, is there any use for `--keep` values other than 1 or 2?
