### ISSUE TITLE
Implement window.closed

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#16705]
To implement `window.closed`, we should call `window.maybe_browsing_context()`. If that is `None`, then the browsing context has been discarded and `true` should be returned. If it is `Some()` it should check `BrowsingContext::is_discarded()`.

spec: https://html.spec.whatwg.org/multipage/browsers.html#dom-window-closed
files: `components/script/dom/window.rs` `components/script/dom/webidls/window.webidl` `components/script/dom/browsingcontext.rs`

**Comment by synlestidae** [comment]
@highfive assign me

**Comment by synlestidae** [comment]
Figured this is a good first contribution. Not that this depends on it, but will implementing window.closed be useful before #13241? Or #13997?
