### ISSUE TITLE
Run JetStream benchmark

### ISSUE THREAD

**Issue by jdm** [servo/servo#16701]
Get JetStream working in Servo. Jetstream is here http://browserbench.org/JetStream/

This metabug is specifically just to get it running. Performance issues will be tracked in a separate metabug.

- [ ] javascript: url isn't handled correctly #16718

Part of #16717.

**Comment by metajack** [comment]
Making this a meta bug.

**Comment by metajack** [comment]
Marking this easy. The task here is to run Servo on this benchmark and file bugs for any errors you find that prevent it from running.

**Comment by bspeice** [comment]
@highfive: assign me

First up is a certificate handshake issue. Happy to provide more info/circumvent the checks if someone can point me in the right direction!
![image](https://cloud.githubusercontent.com/assets/1199853/26809448/e283d48c-4a32-11e7-8a35-e1fe7c7f8dd1.png)

**Comment by bspeice** [comment]
Also confirmed #16718, likely fixed by  #15147; The JetStream object is undefined (it's created by JetStreamDriver.js) when the test tries to kick off.

**Comment by jdm** [comment]
The benchmark now works correct!
