### ISSUE TITLE
Compatibility with openssl-devel from RedHat systems ?

### ISSUE THREAD

**Issue by Nontenda** [servo/servo#16708]
Hi everyone,

I'm trying to build servo on a Fedora 26 with openssl-devel 1.1.0e.

It appears that a function is missing, "./mach build --release" returns :
```
error[E0425]: cannot find function `EC_GROUP_get_curve_GF2m` in module `ffi`
  --> .../servo/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.10/src/ec.rs:76:22
   |
76 |             cvt(ffi::EC_GROUP_get_curve_GF2m(self.as_ptr(),
   |                      ^^^^^^^^^^^^^^^^^^^^^^^ did you mean `EC_GROUP_get_curve_GFp`?

error: aborting due to previous error
error: Could not compile `openssl`.
```

Is there any way to build it on my Fedora ?
Thank's.

**Comment by sfackler** [comment]
This should be fixed in https://github.com/sfackler/rust-openssl/pull/615. Upgrading to rust-openssl 0.9.11 should get past that error!
