### ISSUE TITLE
Atomize namespace prefixes

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#16700]
The `script::dom::element::Element` struct contains a `prefix: Option<DOMString>` field. We also have an interned / atom type `html5ever::Prefix` for namespace prefixes, which uses less memory and makes comparison faster. The field and constructors should be changed to `Option<Prefix>`. This is tedious because `Element` has many "subtypes" that also need to be adjusted. Mass edits with a tool like `sed` are tricky because not all occurrences of `prefix: Option<DOMString>` should be replaced.

**Comment by SimonSapin** [comment]
CC @nox, @jdm

**Comment by z1mvader** [comment]
I'd like to work on this one. @highfive : assign me

**Comment by z1mvader** [comment]
I started working on this issue, I changed the initial prefix type from `Option<DOMString>` to `Option<Prefix>` and started tracking the needed changes by trial and error until I got into an error in an autogenerated file `servo/target/debug/build/script-e2cc69b1ef004d7b/out/Bindings/ElementBinding.rs` when compiling the `layout` component. I checked both the tests and the component source for an `Option<DOMString>` causing problems and couldn't find it any hints?

**Comment by SimonSapin** [comment]
This is a method impl of the `ElementMethods` trait, right? This trait is generated based on [WebIDL code](https://github.com/servo/servo/blob/1b9e1cc1f2656d02c4d0c1df1edd8ffcc8d13f49/components/script/dom/webidls/Element.webidl#L18-L19).

This is one case that should not be changed to `Prefix`. This is an implementation of a DOM method that can be called from JavaScript. (Or in this case, the getter of an attribute.) `DOMString` is converted by the bindings to a JavaScript string.

Instead of changing the signature, do the type conversion inside that method:

```rust
    // https://dom.spec.whatwg.org/#dom-element-prefix
    fn GetPrefix(&self) -> Option<DOMString> {
        self.prefix.as_ref().map(|p| DOMString::from(&**p))
    }
```

`self.prefix` is `Option<Prefix>`, `.as_ref()` gives `Option<&Prefix>`, the closure in `.map()` gets a `p` parameter of type `&Prefix`, `*p` has type `Prefix`, `**p` has type `str` through `Prefix` implementing the `Deref` trait, `&**p` gives `&str`, and finally `DOMString` implements the `From<&str>` trait.
