### ISSUE TITLE
Table with border-collapse: collapse is bigger than it should be

### ISSUE THREAD

**Issue by ocerman** [servo/servo#16736]
Table with `border-collapse: collapse` is bigger than it should be.
![table](https://cloud.githubusercontent.com/assets/10187350/25737410/f762682e-3177-11e7-9605-521d5c8e5176.png)
```
<html>
	<body>
		<style>
			table{
				line-height: 4em;
				border: 4px solid green;
				border-collapse: collapse;
				width: 100%;
			}
		</style>
		<div style="width: 500px; background: lightblue; padding: 10px; ">
			<table>
				<tr><td>Servo</td></tr>
			</table>
		</div>
	</body>
</html>
```

**Comment by KiChjang** [comment]
Did some initial digging on this one, the problematic function here is `populate_collapsed_border_spacing` under `layout/table_rowgroup.rs`. Commenting out the function body seems to produce the desired result.

**Comment by KiChjang** [comment]
... and the widths are calculated in `perform_border_collapse_for_row`, under `layout/table.rs`.

**Comment by KiChjang** [comment]
Okay, that's the wrong direction; the border widths are doing OK, what is not fine is the `TableRowGroup` width... without border-collapse, it is 488px, but with it it's 500px, so clearly the width is not being calculated correctly.

**Comment by KiChjang** [comment]
Root cause: under `table.rs` and during assignment of inline sizes, the padding and borders of the table element, and the horizontal spacing are all calculated to be 0.

**Comment by KiChjang** [comment]
#17836 tries to fix the issue by setting the border width to be zero only on rows, cells and columns AND when the `collapse` CSS value is specified on `table-collapse`, but that caused other test failures, namely `tests/wpt/mozilla/tests/css/border_collapse_simple_a.html`, which shows a table with additional margins when compared with the reference.

**Comment by KiChjang** [comment]
I believe we should instead look into implementing https://www.w3.org/TR/css-tables-3/#border-collapsing to fix this issue.

**Comment by ocerman** [comment]
This still happens.

**Comment by mrobinson** [comment]
This looks correct in modern layout.
