### ISSUE TITLE
Float block is positioned incorrectly within block with text

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#16737]
When you remove text from parent div, then it is working correctly.

![float](https://cloud.githubusercontent.com/assets/10187350/25738287/83eb02ca-317c-11e7-99ff-611f8c7cddfc.png)
```
<html>
	<body>
		<div style="padding: 10px; background: darkblue; color: white; height: 16px;">
			Servo
			<div style="width: 16px; height: 16px; background: red; float: right;"></div>
		</div>
	</body>
</html>
```

**Comment by stshine** [comment]
This is #13683, and we track this bug there.

Thanks.
