### ISSUE TITLE
font-feature-settings serialization code shouldn't need a Vec<u8>.

### ISSUE THREAD

**Issue by emilio** [servo/servo#16743]
Font feature settings are 4 bytes, so we can just use a stack-allocated variable.

To build that code, you need to use `./mach build-geckolib`.

Tests are not needed, this is an optimization.

**Comment by jdm** [comment]
This is inside the "font-feature-settings" longhand in `components/style/properties/longhands/font.mako.rs`.

**Comment by emilio** [comment]
https://github.com/servo/servo/blob/e4d39b547610d43c41f44ff666777e22a1f2a3fb/components/style/properties/longhand/font.mako.rs#L1820

**Comment by emilio** [comment]
While we're there, we can refactor the code after it to use `dest.write_str` instead of `write!`, that should be slightly more efficient.

**Comment by tictakk** [comment]
@highfive: assign me

**Comment by tictakk** [comment]
Just a quick update on this, I had an unexpected work obligation come up shortly after assigning this. I should have a PR this weekend.
