### ISSUE TITLE
Enable taking stack snapshots of other threads

### ISSUE THREAD

**Issue by jdm** [servo/servo#16740]
Often when the script thread is not responding to user input, it can be challenging to figure out what it's doing instead. It would be great to build something like Gecko's background hang reporter, which provides stacks for unresponsive main threads.

**Comment by gterzian** [comment]
https://dxr.mozilla.org/mozilla-central/source/toolkit/components/backgroundhangmonitor/BackgroundHangMonitor.h

I would be interested...

**Comment by gterzian** [comment]
We could use those `ScriptThreadEventCategory` as annotations to the hang, and do something similar for other threads later...

**Comment by jdm** [comment]
As far as I know, there are five main parts required to obtain a meaningful backtrace from a thread that is not the current thread that is executing arbitrary code:
* supending the target thread
* extracting the target thread's current registers, frame pointer and stack
* creating an unsymbolicated backtrace by walking the target thread's stack and following the frame pointer
* resuming the target thread
* symbolicating the backtrace

[This](https://dxr.mozilla.org/mozilla-central/source/tools/profiler/core/platform.cpp?q=%2Bfunction%3A%22profiler_suspend_and_sample_thread%28int%2C+uint32_t%2C+ProfilerStackCollector+%26%2C+bool%29%22&redirect_type=single#3724) looks like where the most interesting bits start in Gecko's implementation. [This](https://dxr.mozilla.org/mozilla-central/source/tools/profiler/core/platform-linux-android.cpp?q=SuspendAndSampleAndResumeThread&redirect_type=direct#298) is how the suspending is done on linux; there will be other implementations for other platforms. DoFramePointerBacktrace and DoMozStackWalkBacktrace are the implementations for the stackwalking. The JS stacks that the code in MergeStacks deals with is a nice extra but not something I'm concerned about in the beginning.

Overall, this stuff is really complex and platform-dependent! I wonder if it might be easiest to try to extract the implementation from Gecko into a standalone library that we could write some Rust bindings for and use that.

**Comment by gterzian** [comment]
Ok thanks. I think I'll focus first on getting the current model with only annotations to work, and then will look more into this. 

Extracting it into a library sounds like a good idea. 

Would including such a backtrace in the overall workflow be something we could plug into the current message-based approach, or do you think it might require a significantly different design(In Gecko they seem to have on "monitor thread" for each "monitored thread")?

**Comment by jdm** [comment]
The reason for a monitoring thread might be to ensure that there is a thread that is always ready to receive the notification that a snapshot needs to be taken, especially when there are multiple processes in use.

**Comment by gterzian** [comment]
By the way, "sampling a thread" looks like it is indeed only done when a "hang" has started, see https://dxr.mozilla.org/mozilla-central/source/toolkit/components/backgroundhangmonitor/BackgroundHangMonitor.cpp#386

Looking that the linux sampling code, I think it will require doing something similar "by-hand" outside of `std::thread`(For example, the `std::thread::ThreadId` is said to "not guaranteed to correspond to a thread's system-designated identifier", so I guess we'll need to actually store the system-designated identifier, and later use it to manually suspend and profile the raw thread?).

So it indeed appears that having a kind of C++ library doing the work, with some Rust bindings, could save us a lot of hard work :)

**Comment by gterzian** [comment]
How about if we were to do something similar to the below inside the monitored thread:
https://github.com/servo/servo/blob/f03ddf6c6c6e94e799ab2a3a89660aea4a01da6f/ports/servo/main.rs#L58-L79

And then have the BHM send a [`SigTrap`](https://docs.rs/sig/1.0.0/sig/ffi/Sig/constant.TRAP.html), with the monitored component sending the backtrace in a message via a signal handler?
