### ISSUE TITLE
Close/Minimize/Maximize buttons don't work on OSX

### ISSUE THREAD

**Issue by Ksbugbee** [servo/servo#16760]
Close/Minimize/Maximize buttons don't work on OSX. They work fine when I build and run Servo, but not when I launch the application from my applications folder.

**Comment by jdm** [comment]
I think this may be a bug in [browser.html](https://github.com/mozilla/browser.html/) instad, since I believe it draws its own window button UI.

**Comment by Ksbugbee** [comment]
Ok thanks, I'll check it out! @jdm

**Comment by jdm** [comment]
@paulrouget Am I correct in my previous comment?

**Comment by paulrouget** [comment]
Yes. Please file there and I will investigate.

Thank you @Ksbugbee

**Comment by Ksbugbee** [comment]
Filed in browser.html -- Thanks @jdm @paulrouget
