### ISSUE TITLE
LayoutWrapper reads data members of derived element types

### ISSUE THREAD

**Issue by jdm** [servo/servo#1676]
For example, see `TLayoutNode::image_url` - it casts a DOM node to an HTMLImageElement and reads the `image` member. This is safe right now, since layout and script do not run concurrently, but it complicates plans for things like COW DOM, which are currently conceptually simple due to the limited number of properties that need to be protected. With concurrent script and layout, script could mutate the `image` member and race with the layout task, unless derived element types also possess shadow data members that are copy-on-write as well. We need to decide on a strategy - currently I'm in favour of making layout derive everything it needs by reading attributes, which will be protected by COW DOM.

**Comment by pcwalton** [comment]
We're not COWing anymore. I don't think this is relevant any longer.
