### ISSUE TITLE
Intermittent LLVM error "failed to build archive: Invalid data was encountered while parsing the file" on linux builders

### ISSUE THREAD

**Issue by jdm** [servo/servo#16783]
```
LLVM ERROR: Invalid data was encountered while parsing the file
```

**Comment by jankeromnes** [comment]
This seems to break `hyper-openssl` and `servo-websocket`:

    LLVM ERROR: Invalid data was encountered while parsing the file.
    Could not compile `hyper-openssl`
    LLVM ERROR: Invalid data was encountered while parsing the file.
    Could not compile `servo-websocket`

Note: I switched to LLVM 4.0, but I'm not sure if that's related.

**Comment by jdm** [comment]
Recently started seeing "failed to build archive: Invalid data was encountered while parsing the file" which may or may not be related.

**Comment by mati865** [comment]
cc https://github.com/rust-lang/rust/issues/65536

**Comment by atouchet** [comment]
I saw that this was marked as done now. Was this issue fixed?

**Comment by jdm** [comment]
Haven't seen it since the last rust upgrade!
