### ISSUE TITLE
TravisCI can't fetch rust-mozjs dependency

### ISSUE THREAD

**Issue by jdm** [servo/servo#16787]
```
$ ./mach build -d --verbose

cargo build -v

    Updating git repository `https://github.com/servo/rust-mozjs`

error: failed to load source for a dependency on `js`

Caused by:

  Unable to update https://github.com/servo/rust-mozjs#08af3654

Caused by:

  failed to fetch into /home/travis/build/servo/servo/.cargo/git/db/rust-mozjs-8611526964119dd6

Caused by:

  [9/-3] Object not found - no match for id (eb65ff7fc22c68210d1e113f76a2a1530fc1c070)

Build FAILED in 0:00:00

The command "./mach build -d --verbose" exited with 101.
```

**Comment by jdm** [comment]
Looks similar to https://github.com/rust-lang/cargo/issues/3561.

**Comment by metajack** [comment]
cc @metajack

**Comment by alexcrichton** [comment]
This may be a case where the git repo got corrupted and Cargo's not correctly detecting that, attempting to continue updating it. Is this happening repeatedly? If so, is it possible to inspect the caches? If inspection isn't possible, but it's repeatedly happening, does cleaning the caches help?

**Comment by metajack** [comment]
Clearing caches can be done with https://travis-ci.org/servo/servo/caches on the TravisCI web UI.

Closing this since there is nothing for us to do here but remediate the problem when it happens.

**Comment by alexcrichton** [comment]
@metajack if the issue here is indeed a corrupt git repo, then I'd definitely consider it a bug in Cargo if it's not handling it! If you see this happen feel free to ping me and I can try poking at it to see if I can zero in on what's happening.

**Comment by jdm** [comment]
It happens on every single travisci push for Servo...

**Comment by metajack** [comment]
@jdm I cleared the caches and the build that was failing is not going fine. Or are you saying it reoccurs even if caches are cleared?

**Comment by jdm** [comment]
No, just clarifying how often is was occurring before clearing the caches.

**Comment by alexcrichton** [comment]
Ok so sounds like it was definitely a corrupt repo somewhere. The error message [came from here](https://github.com/rust-lang/cargo/blob/c00e56dea67c394aac9bf337cdea37fb5fd8570c/src/cargo/sources/git/utils.rs#L94), bottoming out in a call to [`fetch`](https://github.com/rust-lang/cargo/blob/c00e56dea67c394aac9bf337cdea37fb5fd8570c/src/cargo/sources/git/utils.rs#L576).

This may be an error that Cargo can just recognize from that callsite, blowing away the git repo and falling back to a full clone. @jdm is there any way to inspect these repos manually?

**Comment by jdm** [comment]
https://gist.github.com/jedi4ever/7677d62f1414c28a1a8c might be a way to do it. We'll keep an eye out for it happening again in the future.

**Comment by jdm** [comment]
Looks like this might be happening in #16917 again (but for webrender).
