### ISSUE TITLE
Make no_viewport_percentage! use an absolute path for HasViewportPercentage

### ISSUE THREAD

**Issue by nox** [servo/servo#16781]
Currently to use `no_viewport_percentage!`, one needs to first import the `HasViewportPercentage` trait in scope. This is a paper cut.

**Comment by jdm** [comment]
https://dxr.mozilla.org/servo/rev/fc3a7d03f2b0c5292e7414e7555fb75ae0b1d663/components/style/values/mod.rs#57

**Comment by brisad** [comment]
Hi! First time trying to help out in a Rust project. :)
@highfive: assign me
