### ISSUE TITLE
The compositor's viewport field and the WindowEvent::Viewport message are never used

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#16809]
Any reason to keep it?

**Comment by paulrouget** [comment]
I think this made sense before webrender.

I will remove this and introduce later a way to specify the position of the viewport.

**Comment by paulrouget** [comment]
Will be taken care of in #21350

**Comment by mrobinson** [comment]
Looks like this was removed in b0afc2694cea877bf0c7d59db53198349d4fd8cd.
