### ISSUE TITLE
What is WindowEvent::Refresh for?

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#16808]
```
pub enum WindowEvent {
    /// Sent when part of the window is marked dirty and needs to be redrawn. Before sending this
    /// message, the window must make the same GL context as in `PrepareRenderingEvent` current.
    Refresh,
```

I'd like to understand when this happen and why it is necessary.

I see it is used in the CEF port but not in the Glutin port.

**Comment by glennw** [comment]
It basically just means "draw the current display list again" - sometimes this is required if the window is obscured and then exposed, depending on the OS etc.

**Comment by paulrouget** [comment]
Understood. Thank you.
