### ISSUE TITLE
Optimize the passing down of Containing Block details

### ISSUE THREAD

**Issue by pradeep90** [servo/servo#1682]
If a subtree doesn't have any absolutely positioned elements, there is no need to propagate the containing block details in that subtree.
We can implement this by having a flag for `has_abs_positioned_descendant`.

Now, we can also make the `absolute_cb_details` and `fixed_cb_details` fields in BlockFlow  `Option<ContainingBlockDetails>` to save memory.

Ideally, the only ones to store `absolute_cb_details` should be flows that lie between an absolute flow's static position and its Containing Block in the Flow Tree.

**Comment by dralley** [comment]
Seems like none of those functions (or ContainingBlockDetails) exist in the codebase anymore.  Close?
