### ISSUE TITLE
-moz-image-rect should accept string values too

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#16823]
Currently, we only parse `-moz-image-rect(url(...), ...)`. However, it is also possible to specify a quoted string in place of the URL, like `-moz-image-rect("....", ....)`. We should add support for parsing this.

This should make the following reftests in gecko pass:

```
layout/reftests/image-rect/background-test-parser.html
layout/reftests/image-rect/dom-api-computed-style.html
layout/reftests/image-rect/dom-api.html
```

https://github.com/servo/servo/wiki/Property-hacking-guide may help in understanding how parsing works (this is only a part of that doc, the rest is not too relevant). https://doc.servo.org/cssparser/parser/struct.Parser.html#method.expect_string is useful here too.

Let me know if you have questions!

Code: https://github.com/servo/servo/blob/c277beab2b9c3294ea69c6088cd0dc3b1665717e/components/style/values/specified/image.rs#L431

**Comment by nox** [comment]
I'm rewriting everything in the image module, so this shouldn't be done now.

**Comment by Manishearth** [comment]
(un-easying this. could you drive-by fix this in your rewrite?)

**Comment by nox** [comment]
I can do that yes.
