### ISSUE TITLE
osx multi-screen problem / cannot interact with website

### ISSUE THREAD

**Issue by jaroslaw-weber** [servo/servo#16832]
・browser content size change when moving browser to screen with different resolution
・cant close, change website, interact with page. The only thing I can do is scroll a page.

**Comment by jdm** [comment]
This is probably an issue in [glutin](https://github.com/servo/glutin). I wonder if the upstream version of glutin deals with this better?

**Comment by nicoabie** [comment]
@jdm old issue?

**Comment by jdm** [comment]
I'm inclined to close this and open a new one if someone comes across it.
