### ISSUE TITLE
Factor out the calculation of widths/heights and margins

### ISSUE THREAD

**Issue by pradeep90** [servo/servo#1683]
In the spec (http://www.w3.org/TR/CSS2/visudet.html - Section 10.3 and 10.6), there are separate algorithms for different situations - like block non-replaced elements, float non-replaced elements, etc.

They all have the same input and output - (left, right, width, margin-left, margin-right) - where the input is all `MaybeAuto` and the output is all `Au` (after solving the relevant constraint equation).

However, in the current Servo code, the above logic is interspersed with other stuff in a procedural manner and many of the cases aren't implemented yet.

So, it would be good to have a separate `SolveWidthConstraints` / `SolveHeightConstraints` trait that is implemented differently for each of the 8 different situations.

**Comment by frewsxcv** [comment]
Presumably completed in https://github.com/servo/servo/pull/1872
