### ISSUE TITLE
Crash when first open in Windows 10 x64

### ISSUE THREAD

**Issue by AmjadKh** [servo/servo#16842]
When I downloaded the latest version (windows version as zip file) and extracted the file, and opening servo.exe, a window appears and then immediately crash and close.
I'm using laptop 
Lenovo Ideapad 500 - 15isk, 
Windows 10 x64, 
8 GB RAM, 
AMD Radeon Graphics

**Comment by jdm** [comment]
This sounds like #16393.

**Comment by AmjadKh** [comment]
i tried servo.exe > log.txt
the content of log.txt is: 

Failed to link shader program: Type mismatch: Type of _O;vClipMaskUvBounds;p0 different between shaders.
Type mismatch: Type of _O;vClipMaskUvBounds;p1 different between shaders.
Out of resource error.

called `Result::unwrap()` on an `Err` value: Link("Type mismatch: Type of _O;vClipMaskUvBounds;p0 different between shaders.\nType mismatch: Type of _O;vClipMaskUvBounds;p1 different between shaders.\nOut of resource error.\n") (thread main, at src\libcore\result.rs:859)
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread RenderBackend, at src\libcore\result.rs:859)

**Comment by jdm** [comment]
Oh, the windows nightly on download.servo.org is very old due to https://github.com/servo/servo/issues/16560.
