### ISSUE TITLE
Use accessors instead of public fields in Stylist

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#16857]
In [Stylist struct](https://dxr.mozilla.org/servo/rev/dab2df356594bf89502fc5934d8c16a57e3fdf45/components/style/stylist.rs#61-158), we have 2 public fields named `device` and `rule_tree`. Like other fields, we should avoid using public fields and use getter and setter methods instead of accessing them directly.

**Comment by jdm** [comment]
Can we make the fields not public?

**Comment by canaltinova** [comment]
Why not? We don't set these fields except constructor in geckolib build and we already have a set_device method for servo side. So we won't need additional setters for them. All we need are `device` method that returns `&Arc<Device>`,  `device_mut` that returns `&mut Arc<Device>` and a `rule_tree` method that returns `&RuleTree` for now. After that we can make them not public, right?

Note: We should also run `./mach build-geckolib` and see if it builds.

**Comment by HeyZoos** [comment]
@highfive: assign me
