### ISSUE TITLE
Run W3C’s CSS test suites

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#1686]
Complementary to web-platform-tests (#1479), we should run (a subset of) [W3C’s CSS test suites](https://test.csswg.org/) and contribute new tests that we write.

Unfortunately, many of [CSS 2.1’s tests](https://test.csswg.org/suites/css2.1/nightly-unstable/) are not automatable (the require a human to decide whether a given rendering passes of fails) and so are not useful to us. Only few of them are reftests.

Many of these tests use the Ahem font. (#1685)

**Comment by narfg** [comment]
This issue can be closed.
