### ISSUE TITLE
Write a spec for table layout

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#1687]
Since we’re implementing table (#795), this is a once-in-a-decade opportunity to write the table layout spec that the Web needs. CSS 2.1 leaves a lot of it [largely](http://www.w3.org/TR/CSS21/tables.html#auto-table-layout) [unspecified](http://www.w3.org/TR/CSS21/tables.html#height-layout). (The non-normative algorithm there is, I quote, "a complete lie".)

A starting point is to take http://dbaron.org/css/intrinsic/ , remove everything that’s not about tables (which should correspond to what’s now in the [css-sizing](http://dev.w3.org/csswg/css-sizing/)), update it to css-sizing terminology, and try to fill in the TODOs based on what Gecko is doing.

Notes from Jan. 2014 discussions: https://github.com/mozilla/servo/wiki/Workweek-tables

Also worth looking at, though with a huge grain a salt:
http://dev.w3.org/csswg/css3-tables/
http://dev.w3.org/csswg/css3-tables-algorithms/Overview.src.htm

**Comment by mbrubeck** [comment]
https://drafts.csswg.org/css-tables-3/ recently reached FPWD. Closing this issue.
