### ISSUE TITLE
fix cross compilation issues in build_gecko.rs

### ISSUE THREAD

**Issue by froydnj** [servo/servo#16879]
There are a number of them, all stemming from `cfg!(target...)` evaluating to the target that the build script is being compiled for, not the target that our clang will be compiling for.

I'll be filing separate issues for each one, as some are easy to take care of and should be done first so we can get Stylo running on all the platforms Gecko supports on its infra, but some will require a bit more hacking to get right.  It would be *ideal* if we had rust-lang/cargo#4052 to work with, but that's likely a ways off.

**Comment by emilio** [comment]
Related: https://github.com/servo/rust-bindgen/issues/593 and https://reviews.llvm.org/D32389.

Too bad we can't use LLVM trunk ;)

**Comment by emilio** [comment]
Though I guess in this case we could use Cargo's `TARGET`?

**Comment by froydnj** [comment]
> Though I guess in this case we could use Cargo's TARGET?

That's what I was planning on doing here, yes.
