### ISSUE TITLE
URL results rendered unreadably

### ISSUE THREAD

**Issue by hlieberman** [servo/servo#16902]
In the latest servo nightly (Servo 0.0.1-15271f5), the results when typing into the URL bar are rendered as grey blocks of varying size.  The selected element, if any, renders correctly.

![screenshot from 2017-05-17 00-04-02](https://cloud.githubusercontent.com/assets/711517/26138213/7188cd5c-3a95-11e7-992e-7aefbcf0ae8b.png)

-- System Information:
Debian Release: 9.0
  APT prefers testing
  APT policy: (900, 'testing')
Architecture: amd64
 (x86_64)
Foreign Architectures: i386

Kernel: Linux 4.9.0-2-amd64 (SMP w/8 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)

**Comment by jdm** [comment]
I suspect https://github.com/servo/webrender/pull/1220 and related work. cc @kvark

**Comment by NiLSPACE** [comment]
I believe this is fixed when subpixel anti-aliasing is disabled. Could you try with `-Z disable_subpixel_aa`?

**Comment by kvark** [comment]
I can repro and confirm that running with `-Z disable-subpixel-aa` works fine.

**Comment by kvark** [comment]
I looked at it and found 2 problems:
  1. The LCD mode loading code in freetype that I wrote is incorrect. Freetype is giving us `bitmap.width` multiplied by 3, which I consider inconsistent with both the documentation and the other rendering modes. I have a fix for that.
  2. Text is blended incorrectly. This is unrelated to https://github.com/servo/webrender/pull/1220, and I don't yet have a fix for it.

**Comment by glennw** [comment]
A fix for this is https://github.com/servo/webrender/pull/1267 - once it lands in WR we'll need to also get the update in Servo before the fix is visible.

**Comment by atouchet** [comment]
Is this issue still valid? The linked WebRender fix was merged months ago.

**Comment by NiLSPACE** [comment]
It's fixed for me.
