### ISSUE TITLE
Windows nightly not updating

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#16919]
I've been waiting to see when some of the recent PRs will land in the Windows nightly and it seems to be that the nightly isn't being updated as I haven't seen them land in the last few days.

Can anyone confirm?

**Comment by jdm** [comment]
Yes. There's another issue filed several weeks ago about this. @metajack knows more details.

**Comment by atouchet** [comment]
This was filed as #16560. It would really be nice to get this dealt with. The Windows build on the Servo website is currently a month out of date.

**Comment by jonathandturner** [comment]
I'm fine closing this in lieu of #16560.
