### ISSUE TITLE
mach build complains virtualenv isn't installed when it is

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#16921]
From a fresh Windows machine I'm building Servo on, after installing python and then installing virtualenv, I'm seeing this message:

```
C:\Source\servo>c:\Python27\Scripts\pip.exe install virtualenv
Requirement already satisfied: virtualenv in c:\python27\lib\site-packages

C:\Source\servo>mach build -d
Python virtualenv is not installed. Please install it prior to running mach.
```

Are there additional steps after installing virtualenv (eg putting an additional dir in the PATH)?  If so, we should add them to the build directions.

**Comment by jonathandturner** [comment]
Looks like both c:\python27 and c:\python27\scripts need to be in the PATH.  We may want to explicitly call this out so people can easily debug this issue.

**Comment by jprusakova** [comment]
I believe you need to run mach.bat on Windows. 

Here is what I get under Cygwin on Windows 10: 
$ ./mach build -d
Python virtualenv failed to execute properly:
Output: The path /usr/bin/python2.7 (from --python=/usr/bin/python2.7) does not exist

Error:

It finds python and otherwise builds if kicked off using mach.bat: 

$ ./mach.bat build -d
    Finished dev [unoptimized + debuginfo] target(s)

**Comment by hamaluik** [comment]
I'm getting this same error on a fresh install of Debian 9

**Comment by CurtisLeeBolin** [comment]
```
$ ./mach build --dev
Python virtualenv is not installed. Please install it prior to running mach.
$ which virtualenv
/usr/bin/virtualenv
```
@jonathandturner, `virtualenv` is in path, but I am still getting their error.  Do you have any ideas?

**Comment by jdm** [comment]
@CurtisLeeBolin Be sure to install virtualenv as a pip module.

**Comment by CurtisLeeBolin** [comment]
@jdm, I figured it out.  It is looking for python 2 virtualenv.  

[Python 2 is EOL in 13 days](https://www.python.org/doc/sunset-python-2/).  Why is this still using python 2?

Disappointing, I guess I'll look for an `issue` related to the update to python 3 and add myself to the notifications.

**Comment by marmeladema** [comment]
@CurtisLeeBolin work is in progress but its not as straightforward as it sounds. Servo has a lot of dependencies that needs to be made compatible too. But Servo does compile and can be partially tested using python3 already though.

**Comment by CurtisLeeBolin** [comment]
@marmeladema, before my last comment, I had taken a look at `mach`.

```
# The beginning of this script is both valid shell and valid python,
# such that the script starts with the shell and is reexecuted with
# the right python.
```
So I tried running it directly with python 3.
```
$ python --version
Python 3.8.0
$ python mach build --dev
/home/lee/Projects/servo/python/servo/testing_commands.py:301: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if err is not 0
```
After seeing this error, I gave it a good 30 seconds with no further output.  I had assumed it hung, so I killed it with `ctrl + c`.  The error message seemed like a python 3 incompatibility. 

---

Later I saw you [promoting it builds with python3](https://github.com/servo/servo/issues/23607#issuecomment-568213149).  I gave it another shot.  It took quite some time, but more output finally showed I also needed to install `rustup`.  After installed `rustup` that long delay was gone and the building did commence.  I do currently have a build failure, but it does not seem to be python related.  I'll thumbs up your idea to give python 3 build instructions.

**Comment by dralley** [comment]
For me, ```python3 ./mach build --dev``` completes successfully (Fedora 32 Beta).

Since this issue really an extension of the various Python 3 support issues, I suggest closing it.
