### ISSUE TITLE
Avoid running mutation observer algorithms if no mutation observers exist

### ISSUE THREAD

**Issue by jdm** [servo/servo#16936]
For example, we currently iterate over all the ancestors of a node when modifying an attribute. That seems wasteful!

**Comment by jdm** [comment]
More specifically - when the MutationObserver constructor is invoked in components/script/dom/mutationobserver.rs, we should call a method on Window that sets a boolean member. MutationObserver::queue_a_mutation_record should check that member and silently return if it's not set.

@paavininanda This would be a useful task to work on. We can't write an automated test for performance improvements like this, but you could certainly measure the difference before and after using Date.now() around the JS operation.

**Comment by nupurbaghel** [comment]
@jdm I would like to take up this issue.

**Comment by jdm** [comment]
Great! Ask questions about anything that's unclear :)

**Comment by nupurbaghel** [comment]
I wanted to confirm about what the tests should include? I tried changing the attributes of paragraph tag(e.g. color) and noted the time taken for the same. Is there anything else which I need to add?

**Comment by jdm** [comment]
From IRC:
```
10:15 <jdm> nupur: the easiest way to tell if you're testing the right thing is to verify that a mutation is observed if you use the mutationobserver api
10:15 <jdm> nupur: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver
10:16 <jdm> nupur: the other thing to be aware of is that timing means more with a release build than a debug build
10:16 <jdm> nupur: because the debug build will be much slower
10:16 <jdm> nupur: so if you verify that the test does what you expect in a debug build, then you can run `./mach build --release` and `./mach run --release` to compare the real timing data
10:52 <jdm> nupur: to best understand the results, we'll want to measure:
10:53 <jdm> * one test with unchanged servo that performs a mutation but does not include a mutation observer
10:53 <jdm> * one test with unchanged servo that performs a mutation but does include a mutation observer
10:53 <jdm> * one test with your changes that performs a mutation but does not include a mutation observer
10:53 <jdm> * one test with your changes that performs a mutation but does include a mutation observer
10:55 <jdm> and those measurements should all be taken using a release build (./mach run --release test.html), after building a release build (./mach build --release)
```

**Comment by nupurbaghel** [comment]
Okay, so I understand the 4 tests. But, since we want to test on both changed and unchanged servo, we cannot have both the results together. All I can do is test all of these and let you know of the timings as obtained in my computer. I hope I am thinking in the right direction.....

**Comment by jdm** [comment]
You are correct. All we can do is include the test file in tests/html to allow other people to reproduce the results if necessary.
