### ISSUE TITLE
Demo: Spheres no longer working

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#16992]
The Spheres demo doesn't seem to work correctly.  There are no animations and the spheres appear to be stuck in the top left corner.

![screen shot 2017-05-22 at 1 43 27 pm](https://cloud.githubusercontent.com/assets/547158/26289493/b558dc4e-3ef4-11e7-9645-fbf4b799d55c.png)

Will see if I can bisect this today

**Comment by jdm** [comment]
Tracked in #15689. No need to bisect.

**Comment by jonathandturner** [comment]
Roger that, thanks @jdm
