### ISSUE TITLE
UCS-2 string representation

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#1701]
I've started working on a UCS-2 string representation at https://github.com/Ms2ger/servo/compare/mozilla:master...Ms2ger:strings. 

Blocks #282.

To do:
- [ ] autoslicing
- [ ] compile-time constant strings
- [ ] matching on constant strings
- [x] clean concatenation
- [ ] some weird issue with `DOMSlice` and lifetimes
- [x] substring matching
- [x] substring replacement
- [x] collapsing whitespace
- [x] `eq_ignore_ascii_case`
- [x] `IterBytes for LowercaseAsciiString`
- [ ] updating URLs?

**Comment by dralley** [comment]
Can this issue be closed, since the issue that was blocked has been fixed for a while now?  I assume this was addressed at some point.

**Comment by jdm** [comment]
We can reopen it if we decide to revisit our string representation, which seems unlikely.
