### ISSUE TITLE
Add an API for tests to force a webgl canvas context error

### ISSUE THREAD

**Issue by jdm** [servo/servo#17038]
Per https://github.com/servo/servo/pull/16867#issuecomment-304044721.

**Comment by emilio** [comment]
Adding a pref should be enough, happy to mentor this one.

**Comment by jdm** [comment]
More specifically, we can add code to `WebGLRenderingContext::new` that checks a [preference](https://dxr.mozilla.org/servo/source/resources/prefs.json) like "webgl.testing.context_creation_error" and returns an error immediately. We should then update `tests/wpt/mozilla/meta/mozilla/webgl/context_creation_error.html.ini` to set this preference to true so the test passes once more.

**Comment by jdm** [comment]
@jesusbv Would you like to work on this?

**Comment by SWW13** [comment]
I'd like to work on this. @jesusbv if you're interested too you can gladly take it, I'm not going to work on it till tomorrow.

**Comment by bd339** [comment]
@SWW13 are you working on this, or can I take it?

**Comment by SWW13** [comment]
Just started to look a bit around in the WebGL component, feel free to take it @bd339 ;)

**Comment by jdm** [comment]
Assigning to @bd339.
