### ISSUE TITLE
LRUCache should store its vector of entries inline

### ISSUE THREAD

**Issue by bholley** [servo/servo#17054]
We're trying to remove heap-allocations when creating ThreadLocalStyleContext, and ThreadLocalStyleContext contains two LRUCaches. This should be easy and impactful to optimize.

LRUCache lives in components/style/cache.rs. It currently uses a VecDeque to manage a circular list of entries (to avoid copying when adding elements to the front of the list), which never grows. We can avoid the heap-allocation by using an inline buffer instead of a VecDeque.

The easiest approach would probably be to make a minimal wrapper around ArrayVec called ArrayVecDeque, which tracks the current "front" of the list and exposes an iterator that iterates the entries in order.

**Comment by bholley** [comment]
CC @emilio @nox @SimonSapin @bzbarsky

**Comment by bholley** [comment]
Note that I'm filing this as an easy issue in case somebody wants to grab it and knock it out. But it's high-priority enough that I'll probably do it next week of nobody does it before then.

**Comment by kenan-rhoton** [comment]
I'm new to Servo, but I'd be willing to give this a shot during the weekend if nobody else does :)

I'll try to implement your ArrayVecDeque suggestion

**Comment by bholley** [comment]
Sounds great! Let me know if you need any help.

**Comment by bholley** [comment]
@kenan-rhoton any update on this one?

**Comment by kenan-rhoton** [comment]
I wasn't able to look at it during the weekend, but yesterday I tried to make an implementation of an ArrayVecDeque that was transparent to LRUCache and ran into a wall.

So today I've restarted it without this constraint, which has required some (mostly minimal) changes to the way the LRUCache does things.

And right now I'm trying to iron out the different problems I'm having with the Double Ended Iterators.

Also, I just realized there's a servo IRC... I might hop in with some questions.

**Comment by vitiral** [comment]
Want to make sure yall see this https://users.rust-lang.org/t/announcement-arraydeque-deque-ring-buffer-on-stack/11122

**Comment by goandylok** [comment]
A crate of mine may help: [ArrayDeque](https://crates.io/crates/arraydeque/)

**Comment by bholley** [comment]
Yeah, ArrayDeque looks like exactly what we want.

**Comment by kenan-rhoton** [comment]
Yes, thanks for the heads up, I'm putting it in
