### ISSUE TITLE
Bring back clipboard support

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#17065]
Due to licensing issues, we previously had to remove clipboard support from Servo. However, it's now available with a MIT license (https://github.com/servo/servo/issues/12805#issuecomment-299214870)!

This work involves two parts:
1) Add a reference to the new clipboard crate from crates.io (https://crates.io/crates/clipboard)
2) Bring back the code changes that enable the use of the clipboard code. This is the change that backed them out, though you may need to change this code for any API changes that have happened to the clipboard crate's public API since then:
https://github.com/servo/servo/pull/12507/commits/ecabb1823b7531944be755e192acf0b7a9b2e698

**Comment by est31** [comment]
@highfive: assign me
