### ISSUE TITLE
GC crash when Initializing TypedArrays without  a local stack root

### ISSUE THREAD

**Issue by MortimerGoro** [servo/servo#17076]
Using handle_mut() on a rooted DOMObject to initialize typed arrays should work but causes GC crashes
```rust
let gamepad = reflect_dom_object(box Gamepad::new_inherited(..),
                                 global,
                                 GamepadBinding::Wrap);
unsafe {
    let _ = Float64Array::create(global.get_cx(), CreateWith::Slice(&state.axes), gamepad.axes.handle_mut());
}
```

GC works well when a local stack root is used:
```rust
let gamepad = reflect_dom_object(box Gamepad::new_inherited(..),
                                 global,
                                 GamepadBinding::Wrap);
let cx = global.get_cx();
rooted!(in (cx) let mut array = ptr::null_mut());
unsafe {
    let _ = Float64Array::create(cx, CreateWith::Slice(&state.axes), array.handle_mut());
}
gamepad.axes.set(array.get());
```

**Comment by MortimerGoro** [comment]
cc @jdm 

I had to [revert](https://github.com/MortimerGoro/servo/commit/7a85c5b8c40d6a5a15a3d0a4613b9120ae65bcb9) all the extra extra local stack root changes we talked about in: https://github.com/servo/servo/pull/16500/files

**Comment by jdm** [comment]
Oh good, a new frightening crash.

**Comment by jdm** [comment]
I would bet money this is caused by https://github.com/servo/rust-mozjs/issues/351.

**Comment by jdm** [comment]
The underlying hole in rust-mozjs was fixed (https://github.com/servo/rust-mozjs/issues/351).
