### ISSUE TITLE
Download OpenSSL from rust-lang mirror

### ISSUE THREAD

**Issue by jdm** [servo/servo#17079]
The Rust team has an OpenSSL mirror (https://github.com/rust-lang/rust/pull/42220). We should use that instead of downloading releases directly from the openssl website: https://github.com/servo/servo/blob/45d8b0f0b61b8026a57cf5704de2f9d8b53ace45/support/android/openssl.makefile#L13

**Comment by o0Ignition0o** [comment]
I'm on it, will do it tonight !
@highfive: assign me   !

**Comment by MortimerGoro** [comment]
@o0Ignition0o I'm updating OpenSSL version in https://github.com/servo/servo/pull/17099

We'll have to sync the changes ;)

**Comment by o0Ignition0o** [comment]
@MortimerGoro just saw your commits, I'll check how I can handle it :)

**Comment by MortimerGoro** [comment]
@o0Ignition0o We have decided to do the OpenSSL update into a separate PR. So you can push a new PR using the mirror and the 1.1.0 version update.

You'll need to add this line to the openssl.sh to support compilations with the new version:
`export CROSS_SYSROOT="$ANDROID_SYSROOT"`

**Comment by o0Ignition0o** [comment]
Sure, will do. Btw @MortimerGoro I've just checked the patch notes, and everything shall be fine. Is there any way I can make sure there won't be any breaking changes induced by the 1.0.1 to 1.1.0 version bump ?

**Comment by MortimerGoro** [comment]
Servo uses the high level OpenSSLClient API https://github.com/sfackler/hyper-openssl, which internally uses a rust-openssl, a wrapper for the native API which supports OpenSSL 1.0.1 or above. OpenSSL 1.1 support was added in this commit: https://github.com/sfackler/rust-openssl/commit/43c951f743e68fac5f45119eda7c994882a1d489#diff-80398c5faae3c069e4e6aa2ed11b28c0

So everything should be ok, the dependency already handles breaking changes in 1.1. 

We can test loading some `https `pages to make sure everything is fine.

**Comment by larsbergstrom** [comment]
cc @avadacatavra who may have OpenSSL opinions :-)
