### ISSUE TITLE
Unable to scroll on https://tweakers.net

### ISSUE THREAD

**Issue by NiLSPACE** [servo/servo#17088]
On [tweakers.net](https://tweakers.net) (a Dutch tech website) I'm unable to scroll down. 

## Steps to reproduce:
- Use `servo.exe https://tweakers.net` to go to the website;
- Get past the cookie wall by pressing the blue button containing 'Ja, ik geef toestemming';
- Try to scroll down on this page.

Specs:
CPU: I7 6500U @ 2.5GHz,
RAM: 16.0GB Dual-Channel,
GPU: Intel HD Graphics 520
OS: Windows 10 PRO 1607

**Comment by danger89** [comment]
Its even worse, in my case the browser just crashes:

> ERROR:script::dom::bindings::error: Error at https://tweakimg.net/x/vendor/webtrekk/webtrekk_v4.js?1462880680:53:296 navigator.vendor is undefined
> Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322
> ERROR:script::dom::bindings::error: Error at https://s0.2mdn.net/ads/studio/cached_libs/cssplugin_1.18.0_71489205621d46cbe88348eeb8fe493f_min.js:12:15279 e.style is undefined

**Comment by NiLSPACE** [comment]
I also get those errors, but it doesn't crash for me.

**Comment by danger89** [comment]
It hangs let's say,  the app is still open. But I can not browse further.

**Comment by NiLSPACE** [comment]
I noticed this also happens on Firefox with Webrender enabled and `gfx.webrender.layers-free` set to true.

**Comment by NiLSPACE** [comment]
When I [dock](http://www.nurgo-software.com/images/AquaSnap/Docking.gif) servo to the side I am able to scroll down.

**Comment by NiLSPACE** [comment]
This is fixed now, but #19707 is still an issue.
