### ISSUE TITLE
Fix calculation of shrink-to-fit width

### ISSUE THREAD

**Issue by pradeep90** [servo/servo#1708]
17:44 < pradeep> SimonSapin: I think the function guess_width in Box_ is wrong for block boxes because it adds in margin, border, and padding to the minimum width and preferred width
17:45 < pradeep> The CSS Spec isn't clear to me, but I guess when we should use only the width. Am I correct?
17:46 < SimonSapin> pradeep: there are two things that should not be confused: min-content and min contribution http://dev.w3.org/csswg/css-sizing/#block-intrinsic
17:46 < pradeep> hmmm.. I mean the minimum and preferred width used for calculating the shrink-to-fit width for float and absolute positioning
17:46 < SimonSapin> both are used in some cases, so it depends on what you're doing
17:48 < SimonSapin> by the way, min-content is the same as "preferred minimum width", and max-content as "preferred width" http://dev.w3.org/csswg/css-sizing/#max-content-measuremax-measuremax-content-size
17:51 < SimonSapin> yeah, it's a mess
17:51 < SimonSapin> but CSS 2 does not really define any of this
17:51 < SimonSapin> other than a bit of hand-waving
17:52 < SimonSapin> css-sizing does
17:53 < pradeep> ok, I will go through that reference more deeply soon. let me describe the test case that differs between FF and Servo - 
```
<body><div style="float:left; padding:10px; margin:5px"></...>
```
17:55 < pradeep> because width is not specified, it is shrink-to-fit. But Servo calculates minimum preferred width, etc. as including padding and margin. So now, the output has padding+margin as its width.
17:56 < SimonSapin> if the used content width (ie. excluding padding and margins) is based on something that does include padding and margins, that's a bug
17:58 < SimonSapin> roughly, the min contribution is min-content plus padding, border and margins; and min-content is the max (for blocks) of the children's min contribution

Will add more details later.

**Comment by pcwalton** [comment]
This is basically working. Let's close this in favor of more specific bugs.
