### ISSUE TITLE
Enable sccache for Servo CI

### ISSUE THREAD

**Issue by luser** [servo/servo#17106]
I've been testing sccache with Servo lately, and it's working pretty well for caching crate compilation. Details are available on [this users.rlo thread](https://users.rust-lang.org/t/sccache-for-caching-rust-compilation/10960). I needed to make one change to an upstream crate, and I finally submitted [a PR to update that dependency](https://github.com/servo/servo/pull/17094) which has now been merged.

Unless large chunks of the dependency graph change frequently I would expect a pretty good cache hit rate, which should save a fair amount of time for CI builds. Additionally, once we get S3 buckets configured we can set `[build] ccache = 'sccache'` and use sccache to cache the C++ compilation from the build, which may produce better results than using ccache, since multiple builders can share the same cache.

cc/ @alexcrichton @edunham @larsbergstrom

**Comment by aneeshusa** [comment]
Using environment variables is easier than updating the .servobuild file for CI. Will installing sccache and setting `RUSTC_WRAPPER=sccache` work? Those would both happen in [saltfs](https://github.com/servo/saltfs).

**Comment by luser** [comment]
That will make it work for caching rust compiles, but not C++ compiles.

**Comment by larsbergstrom** [comment]
OMG this is amazing - thank you so much for doing this, including the testing, @luser!

One question: do you know how well this handles invalidation when rustc or cargo are updated? I was chatting with @edunham and we were thinking about doing a "merge commit by merge commit" test of `sccache` as incremental builds for the last few months, catching a few updates to see.

@metajack We're gonna HAVE to try rolling this out to see if we can shave some time off of macOS builds :-)

**Comment by aneeshusa** [comment]
Are there pre-built releases of sccache available? That would be the easiest way to deploy onto our build machines.

**Comment by aneeshusa** [comment]
Also, it looks like the `build.ccache` setting in `.servobuild` is just used to set the `CCACHE` environment variable, so we can do that directly.

**Comment by luser** [comment]
> One question: do you know how well this handles invalidation when rustc or cargo are updated?

sccache hashes the contents of all the sharedlibs under $sysroot/lib and uses that as an input to the hash used for the cache key, so it shouldn't be a problem.

**Comment by luser** [comment]
> Are there pre-built releases of sccache available? That would be the easiest way to deploy onto our build machines.

@alexcrichton has binary builds for Rust CI, so you ought to be able to use those until I get actual binary releases setup in sccache CI.

**Comment by luser** [comment]
FWIW, I've been testing enabling sccache for Rust compilation in Firefox builds, and for our stylo builds (which build a big chunk of Servo code), [it looks to save about 5 minutes per build](https://bugzilla.mozilla.org/show_bug.cgi?id=1357825#c15).

**Comment by jdm** [comment]
This has been enabled.

**Comment by aneeshusa** [comment]
According to jdm who is in person with me right now, this is not actually fixed yet.

**Comment by jdm** [comment]
This was fixed a while ago.
