### ISSUE TITLE
White lines in Moire demo

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17114]
When running the Moire demo in recent builds white lines occasionally show up. This was tested in Windows 10.

Example images:

![Image 1](https://i.imgur.com/QvgRCcy.jpg)

![Image 2](https://i.imgur.com/cbpsIXd.jpg)

![Image 3](https://i.imgur.com/aVHZXcA.jpg)

**Comment by Manishearth** [comment]
cc @glennw @jrmuizel

**Comment by Manishearth** [comment]
Thanks for the report!

**Comment by atouchet** [comment]
I'm not able to reproduce this in the latest nightly build.
