### ISSUE TITLE
Use RefCell instead of RWLock for namespace map in context

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#17131]
In #17130 we introduce a reference to the namespace map in the parser context.

Parsing is done in a single threaded fashion, so really, we only need the semantics of a RefCell at this stage, but the namespace map is in an RWLock because at other stages of the program it is accessed concurrently.

To avoid extra overhead where we reacquire the lock each time, instead of `namespaces: &RwLock<Namespaces>`, we should have `namespaces: RefCell<&mut Namespaces>`, and before parsing acquire a write lock to the namespace map to construct this refcell. `RefCell<&mut T>` has the same semantics as a refcell -- you can only mutate in `borrow_mut` mode, because `&&mut T` is semantics-wise the same as `&&T`.

**Comment by neunenak** [comment]
I'd like to give this a shot.

**Comment by Manishearth** [comment]
Let me know if you need help!

I recommend testing it with `./mach build-geckolib` since that's faster to build.

You will need to base your work off of https://github.com/servo/servo/pull/17130

**Comment by Manishearth** [comment]
`git fetch origin pull/17130/head:pr` will make a local branch `pr` that contains those changes

**Comment by KiChjang** [comment]
@neunenak Are you still working on this?

**Comment by Manishearth** [comment]
bbd85ccbda2ced5994205a4362cca92b7e4837ab
