### ISSUE TITLE
servo won't start. 

### ISSUE THREAD

**Issue by wbeyda** [servo/servo#17135]
wbeyda@Bigrig2:~/Downloads/servo$ RUST_BACKTRACE=1 ./servo 
Failed to create window.: OsError("GL context creation failed") (thread main, at /checkout/src/libcore/result.rs:859)
stack backtrace:
   0:     0x55ba6b4ada2c - backtrace::backtrace::trace::h58bdbc4722aadbf4
   1:     0x55ba6b4adb72 - backtrace::capture::Backtrace::new::hde1afc496271e12d
   2:     0x55ba69b04b5d - servo::main::{{closure}}::h1637c169f0f2e7e5
   3:     0x55ba6ba1fe4a - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:550
   4:     0x55ba6ba1fce4 - std::panicking::begin_panic<collections::string::String>
                        at /checkout/src/libstd/panicking.rs:511
   5:     0x55ba6ba1fc19 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:495
   6:     0x55ba6ba1fba7 - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:471
   7:     0x55ba6ba56ffd - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:69
   8:     0x55ba69b08232 - core::result::unwrap_failed::h9f7d141a26854746
   9:     0x55ba69b24b16 - glutin_app::window::Window::new::hcf28c872e4691344
  10:     0x55ba69b29978 - glutin_app::create_window::h7ba26e1451e086a0
  11:     0x55ba69b02356 - servo::main::h8fa98aecb40c4fa8
  12:     0x55ba6ba26eda - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  13:     0x55ba6ba20588 - std::panicking::try<(),closure>
                        at /checkout/src/libstd/panicking.rs:433
                         - std::panic::catch_unwind<closure,()>
                        at /checkout/src/libstd/panic.rs:361
                         - std::rt::lang_start
                        at /checkout/src/libstd/rt.rs:59
  14:     0x7f837639482f - __libc_start_main
  15:     0x55ba69ad1c79 - <unknown>
  16:                0x0 - <unknown>

**Comment by jdm** [comment]
Looks like the same issue as #12053 and others. We require a minimum version of OpenGL (3.0? 3.1?) that presumably you do not support.
