### ISSUE TITLE
Properly protect the master branch

### ISSUE THREAD

**Issue by nox** [servo/servo#17148]
Our current settings for the `master` branch are:
<img width="733" alt="capture d ecran 2017-06-03 a 14 22 16" src="https://cloud.githubusercontent.com/assets/123095/26753503/1ed3412e-4868-11e7-9ac5-52d0c76045ca.png">

Apparently this is not enough, given I managed to larsbors both [nightly](https://github.com/servo/servo/commit/f081380dc03dba9664877df2829097f32c40694a) and [stable](https://github.com/servo/servo/commit/8a9d9ab2f9d7d384ac0e94671fae705088c26399) rustups by mistake, without even creating a PR, amazing (I'm actually currently freaking out).

I don't think we can just enable the checks for admins, given @bors-servo is a normal user and thus wouldn't be able to push either.

Cc @larsbergstrom @metajack @jdm @edunham

**Comment by nox** [comment]
Cc @notriddle who knows his stuff with this kind of things too.

**Comment by nox** [comment]
Am not larsborsing any revert for now, given @emilio is already trying to land #17147.

**Comment by larsbergstrom** [comment]
Aha! We've been waiting for the `Include Administrators` bit to make it to servo/servo. That was one of our huge requests for them when branch protection first rolled out and it was in beta but hadn't made it to servo/servo yet. Will toggle once we're in an un-nox'd state :-)

**Comment by notriddle** [comment]
Turn on the including administrators switch. It won't break homu. That switch doesn't prevent anybody but admins from pushing; what it does is prevents admins from bypassing the checks, like you just did.

**Comment by larsbergstrom** [comment]
Yes, I was just going to figure out whether or not we want to wait to force-push a revert of his accidental update. Will chat in #servo

**Comment by larsbergstrom** [comment]
Done.
