### ISSUE TITLE
Import webgl tests separately from web-platform-tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#17140]
Per conversation in https://github.com/w3c/web-platform-tests/issues/5927. This requires:
* importing some subset of https://github.com/KhronosGroup/WebGL into tests/wpt/mozilla/tests/
* applying the patches in https://github.com/w3c/web-platform-tests/tree/a56a326675840eaec5c2543749039f312c7b6d72/webgl/tools
* adding a mach command to make it easy to update the imported tests

**Comment by foolip** [comment]
It might also be worth checking if there's any interest in applying those patches (converting to testharness.js) in the upstream test suite.

**Comment by MortimerGoro** [comment]
I want to include WebGL 2.0 conformance tests. We'll need to update to 2.0.0 conformance suite instead of 1.0.3.

As a first step I'll work on this issue. In a different PR I'll try to update to 2.0.0 using the new match command. Let's see how it goes ;)
