### ISSUE TITLE
Intermittent fail in /css21_dev/html4/bidi-box-model-029.htm /css21_dev/html4/bidi-box-model-028.htm /css21_dev/html4/bidi-box-model-033.htm /css21_dev/html4/bidi-box-model-032.htm /css21_dev/html4/bidi-box-model-030.htm /css21_dev/html4/c5507-padn-r-000.htm /css21_dev/html4/c5509-padn-l-000.htm

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#17166]
I bet the actual issue is not in these specific files but just happened to occur there in one run. But whatever.

**Comment by jdm** [comment]
The harness claims that the images for those tests do not match the reference image, but the reftest analyzer does not highlight any differing pixels.

**Comment by jdm** [comment]
In fact, I saved the images from the reftest analyzer and they have the same hash. This means that the actual pixel content of the original images that were compared was correct, but somehow the metadata was different??
