### ISSUE TITLE
Support clicking links with URL fragments for the current page

### ISSUE THREAD

**Issue by jdm** [servo/servo#1716]
https://html.spec.whatwg.org/multipage/#the-indicated-part-of-the-document

**Comment by kball** [comment]
I'd like to take a look at this.  Does anyone know if there are existing test cases somewhere in the repo?

**Comment by jdm** [comment]
There are lots of tests that contain anchors to page fragments, but I highly doubt that they end up testing the scrolling behaviour we're looking for here. I suggest writing some yourself!

**Comment by jdm** [comment]
Note: http://mxr.mozilla.org/servo/source/components/script/script_task.rs#1340 is the code that should be triggering the scrolling here. We may have fixed this unintentionally as part of #3790, but thorough testing would be valuable.

**Comment by kball** [comment]
@jdm Thanks for the rapid response! 

A very simple (manual) test indicates that not all cases are fixed.  I'll set up some more automated tests.  Do you have a recommendation as to where in the web-platform-tests they should live?

**Comment by jdm** [comment]
I'd go with https://github.com/w3c/web-platform-tests/tree/master/html/browsers/browsing-the-web/scroll-to-fragid (ie. tests/wpt/web-platform-tests/html/browsers/browsing-the-web/scroll-to-fragid).

**Comment by KiChjang** [comment]
@kball what's the status of this?

**Comment by kball** [comment]
@KiChjang Afraid life came and hit me with a club, I haven't made progress.  Feel free to grab it

**Comment by peterjoel** [comment]
I could take a stab at this one, if no one else is?

**Comment by jdm** [comment]
@peterjoel You're welcome to it!

**Comment by peterjoel** [comment]
The support looks generally pretty good for actually scrolling to elements. I have (informally) tested:

 * Block elements (`<h2 id>`, `<p id>`)
 * Inline elements (`<span id>`, `<b id>`)
 * Anchors (`<a id>` and `<a name>`, meaning the case mentioned in March 2014 by @june0cho is now working)
 * Non-printable elements (`<br id>`)

The only case I found that fails is when the fragid contains url escape sequences. e.g. when the element is `<p id="a link">` and the fragid is `a%20link`. Confirmed that the same case works ok in Chrome and Firefox.

**Comment by peterjoel** [comment]
I could do with some clarification on how percent-decoding should be applied. The algorithm (https://html.spec.whatwg.org/multipage/#the-indicated-part-of-the-document) says that the fragid should always be percent-decoded, when matching an element id, but should not be percent-decoded when matching an anchor name.

However, in Firefox and Chrome, I can see that a frag id `a%20b` will match an element with id of _either_ `a b` _or_ `a%20b`.

**Comment by peterjoel** [comment]
When linking to a `<br />`, Chrome scrolls to the line after the actual `<br/>` element, but Firefox scrolls to the line before. The whatwg spec isn't really clear on this behaviour - which is correct?

**Comment by KiChjang** [comment]
I personally lean towards mimicking Firefox's behavior.

**Comment by peterjoel** [comment]
@KiChjang Ok. Will there be a problem with pushing tests upstream in that case?

**Comment by jdm** [comment]
@peterjoel We should definitely file a issue at https://github.com/whatwg/html/ before committing code that ignores the specification and updates tests to expect non-conforming behaviour.

**Comment by peterjoel** [comment]
I would propose splitting this into two issues:

# Dealing with decoding the fragid (e.g. percent-decoding)
# Scrolling to the precise location.

The second item is (in my opinion) blocked on this whatwg issue: https://github.com/whatwg/html/issues/94

While there is a [merged PR](https://github.com/w3c/csswg-drafts/pull/81) for this, it is not completed, and doesn't cover the case of scrolling to a non-printable element. In particular it doesn't disambiguate the behaviour for `<br>`.

**Comment by jdm** [comment]
Splitting sounds fine to me.
