### ISSUE TITLE
Font rendering doesn't seem stay on the line

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#17175]
I feel like I saw this before, but it seemed more noticeable this morning.  When I open up the bhtml gallery, fonts aren't rendering on a straight line.

Here's what the servo label looks like:

<img width="193" alt="screen shot 2017-06-06 at 9 27 37 am" src="https://cloud.githubusercontent.com/assets/547158/26804074/d081d672-4a9a-11e7-8916-0079368e6f41.png">

I mean it is kinda fun... but I'm guessing that's not the intended behaviour.

**Comment by jdm** [comment]
What platform?

**Comment by jonathandturner** [comment]
That was on a macbook pro 2015, outputting to a 4k monitor.  Unfortunately I had to send it in for repairs (unrelated I'm sure 😛 ) or I could dig in a bit more.

**Comment by jdm** [comment]
I see this on my macbook as well, but only when using browser.html (ie. `-b`). When running the same site in a stock servo build, I don't see this problem appear.

**Comment by emilio** [comment]
Over #17264, @Feliix42 reports it running just with `--release`, so maybe not browser.html dependent?

**Comment by cbrewster** [comment]
I see the issue both with and without browserhtml

**Comment by atouchet** [comment]
Is this still an issue? I believe there have been some WebRender glyph positioning fixes since this report was opened.

**Comment by jonathandturner** [comment]
@atouchet - good catch.  I haven't seen this issue recently.  Closing.
