### ISSUE TITLE
Implement DOMTokenList and DOMSettableTokenList

### ISSUE THREAD

**Issue by jdm** [servo/servo#1717]
http://dom.spec.whatwg.org/#domtokenlist

Element.classList is a good usecase to work on as well.

**Comment by nox** [comment]
Blocks #2185.

**Comment by frewsxcv** [comment]
These might be merged: https://github.com/whatwg/dom/issues/119

**Comment by nox** [comment]
`DOMSettableTokenList` went on an adventure and will never come back.
