### ISSUE TITLE
Bad performance on https://loadingartist.com

### ISSUE THREAD

**Issue by NiLSPACE** [servo/servo#17170]
I've noticed that [loadingartist.com](https://loadingartist.com) is a pretty demanding website on other browsers as well, but when using Servo it first spikes at 100% CPU usage and then lowers to ~50% with occasionally scrolling being extremely slow or Servo crashing.

Specs:
CPU: I7 6700 @ 2.6GHz,
RAM: 16.0GB Single-Channel,
GPU: Intel HD Graphics 530
OS: Windows 10 Home 1703

**Comment by NiLSPACE** [comment]
It seems this is fixed now. The websites loads quick and feels really smooth.

**Comment by jdm** [comment]
Thanks for checking!
