### ISSUE TITLE
about:failure doesn't exist any more

### ISSUE THREAD

**Issue by jdm** [servo/servo#17187]
This disappeared along with the pre-fetch network stack; now basic_fetch only checks for about:blank. This explains why we sometimes end up seeing "Unexpected scheme" error pages.

**Comment by delan** [comment]
Adding a case for about:failure to scheme_fetch in components/net/fetch/methods.rs should get us most of the way, though ideally we want to have a reload button and/or keep the location bar pointing to the original url.
