### ISSUE TITLE
Implement Window viewport, scrolling, and client properties

### ISSUE THREAD

**Issue by jdm** [servo/servo#1718]
http://dev.w3.org/csswg/cssom-view/#extensions-to-the-window-interface

**Comment by farodin91** [comment]
Is some one working this?

**Comment by jdm** [comment]
Nope!

**Comment by farodin91** [comment]
I'd like to work on it.

**Comment by jdm** [comment]
You're welcome to it.

**Comment by farodin91** [comment]
I will start the next days. First i must finish my bachelor thesis.

Any tipps for interesting files, that can help?

**Comment by jdm** [comment]
Window in component/script/dom/window.rs has a `window_size` member which is updated on resizing. I believe that scrolling events are handled in Window::set_page_clip_rect_with_new_viewport, too, where the new viewport is the new rectangle of visible page (ie. scroll offsets).

I made these observations by searching for the words "resize" and "scroll" in script_task.rs, dom/window.rs, and compositor.rs. I suspect the client properties (clientX, clientY, outerWidth, outerHeight) will need to be forwarded from compositor.rs somehow.

**Comment by farodin91** [comment]
Are there any tests for innerheight and scrollX?

**Comment by jdm** [comment]
There are a number of tests for innerHeight under /tests/wpt/css-tests/cssom-1_dev/ (see http://mxr.mozilla.org/servo/search?string=innerheight). There do not appear to be any automated tests for the scroll properties, though.

**Comment by farodin91** [comment]
Finished innerWidth, innerHeight, scrollX, pageXOffset, scrollY, pageYOffset

**Comment by jdm** [comment]
:heart_eyes_cat:

**Comment by farodin91** [comment]
What is with the css property "overflow" ?

**Comment by jdm** [comment]
What do you mean?

**Comment by farodin91** [comment]
https://drafts.csswg.org/cssom-view/#overflow-directions

**Comment by jdm** [comment]
Oof. The stuff in the spec about implementing the scrolling methods is definitely more complication and could use @mbrubeck's input. Why don't you submit a PR for the completed methods so far?

**Comment by farodin91** [comment]
No problem.
Wait!
