### ISSUE TITLE
Simplify `an+b` when serializing

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#17182]
When we serialize an `an+b` value, we just print it as `an+b`.

We should be simplifying it as much as possible. This means:

 - Printing out only `b` if `a` is zero
 - Printing out only `an` if `b` is zero
 - Printing `0` if both are zero
 - Not printing `a` if it is 1

Reduced testcase:

```html
<style type="text/css">
  :nth-child(+1n+5){}
</style>
<script type="text/javascript">document.write(document.styleSheets[0].cssRules[0].selectorText</script>
```

(Same for `+1n+0`, `+0n+5`, `+0n-0`, etc)

Relevant code: https://github.com/servo/servo/blob/2da8eb0342f6701b5365116b96113c83a1599b1f/components/selectors/parser.rs#L743

Testing: `tests/wpt/web-platform-tests/cssom/selectorSerialize.html`

**Comment by jyc** [comment]
Happy to work on this!

@highfive: assign me

**Comment by jyc** [comment]
For reference, relevant spec seems to be [CSS Syntax 3](https://drafts.csswg.org/css-syntax-3/#serialize-an-anb-value), in the case of the example via [CSS OM](https://drafts.csswg.org/cssom/#serializing-selectors)!

**Comment by Manishearth** [comment]
Aha! I wasn't able to find it in the values/syntax spec where the rest of an+b is specced so I didn't dig deeper.

**Comment by jyc** [comment]
Seems like to do this we will need to have .selectorText, but jdm and bz say that should be easy to do! Going to do that now.

**Comment by Manishearth** [comment]
Use cssText for now :smile:

**Comment by Manishearth** [comment]
(but yeah work on that too!)

**Comment by jyc** [comment]
After asking @dbaron I made a quick issue on the CSS Syntax spec for the specifics of how to serialize the an+b values, because it seems Firefox, Chrome, and Safari are all slightly different (spec seems to be what Chrome does): https://github.com/w3c/csswg-drafts/issues/1504

Going to copy what Firefox does for now. Forgot about cssText, thanks for that!

**Comment by jyc** [comment]
I think this issue is not actually closed, those two commits were just parts of the fix. Going to add the new PRs now.

**Comment by jyc** [comment]
Issue not really closed, still depends on three more PRs in the series.
