### ISSUE TITLE
Dispatch load, loadstart, loadend, error events for image elements

### ISSUE THREAD

**Issue by jdm** [servo/servo#1719]
The algorithm at http://html.spec.whatwg.org/#the-img-element is really long, but we can extract out a few (incorrect) simplifications and focus on dispatching events (load, loadstart, loadend, and error). This will help pave the way to tracking document subresource loads.

**Comment by mbrubeck** [comment]
"load" events are now implemented, but the others are not.

**Comment by alex** [comment]
The lack of an `error` event firing makes it difficult to use resources like https://badssl.com/dashboard/.

Here's a simple test case for whoever comes next:

```html
<html>
   <body>
       <div id="body" />
       <script type="text/javascript">
        var onSuccess = function() {
            document.getElementById("body").textContent = "load event fired... it should not have";
        }
        var onFailure = function() {
            document.getElementById("body").textContent = "error fired... this is correct";
        }
        var img  = new Image();
        img.addEventListener("load", onSuccess, false);
        img.addEventListener("error", onFailure, false);
        img.src = "https://expired.badssl.com/";
       </script>
   </body>
</html>
```

**Comment by nox** [comment]
All of these have been implemented.
