### ISSUE TITLE
CSS Rendering glitches on Windows 10

### ISSUE THREAD

**Issue by KakuTheToaster** [servo/servo#17195]
Seems to not load pages like it is supposed to on pretty much every website
![screenshot 13](https://user-images.githubusercontent.com/28992910/26856038-ee8d62d2-4ae3-11e7-94e2-d2464f950764.png)

**Comment by jdm** [comment]
That's expected since our layout and CSS support is incomplete. Filing separate issues for each page that does not render as expected will be more useful.

**Comment by KakuTheToaster** [comment]
okay well that about every page that uses somewhat decent design (material layouts, bootstrap on some occasions, DuckDuckGo, other search engines, YouTube and much more.

**Comment by KakuTheToaster** [comment]
And please support YouTube's beta layouts as well
