### ISSUE TITLE
ScriptThread: received a resize msg for a pipeline not in this script thread. This is a bug.

### ISSUE THREAD

**Issue by WiebeCnossen** [servo/servo#17207]
ScriptThread: received a resize msg for a pipeline not in this script thread. This is a bug.
### Servo Version:
Servo 0.0.1-f388c0a
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(7), index: PipelineIndex(12) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(7), index: 
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment]
Do you know what page you were looking at?

**Comment by WiebeCnossen** [comment]
I'm afraid I don't remember. It was my first servo session and I assumed all relevant info would be included in the automatic post.

**Comment by jdm** [comment]
Ok. Thanks for reporting it!

**Comment by pwnorbitals** [comment]
Is there any way to troubleshoot this ? It's old and I'm not sure we have enough information
