### ISSUE TITLE
Tabs support: add methods to create additional top level browsing context

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#17226]
Now that #17077 has landed, and after #17200 and #16477 are fixed, we will need a way to create new top level browsing context.

We will need new Browser methods. This will impact the initialization code. And Browser will need to be renamed to something else as we will be create multiple browsers.

**Comment by gterzian** [comment]
Somewhat unrelated to this issue, but I wasn't sure where else to post it. Came across this project which is an interesting embedding use case: https://github.com/scrapinghub/splash/

They're using PyQt5, which seems to offer a kind of windowing wrapper around Webkit. 

The project has it's own "Tab" solution, implemented in Python, which wraps around a PyQt5.QWebview. It's worth taking a look to see what things they had to support themselves: https://github.com/scrapinghub/splash/blob/master/splash/browser_tab.py

As I understant the "main" event loop of the project is a Twisted event loop (Python).

**Comment by paulrouget** [comment]
Thanks.

There are a lot of embedding projects we have been studying. For example:

- [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage)
- [Mozilla Browser API](https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Chrome/API/Browser_API)
- [Electron's webview](http://electron.atom.io/docs/api/web-contents/)
- [Android's webview](https://developer.android.com/reference/android/webkit/WebView.html)
- [iOS's WKWebview](https://developer.apple.com/reference/webkit/wkwebview)

Our conclusion was to not abstract as much at these do, and stay as close to Servo as possible. A more user-friendly API will be build on top of these low level API.

**Comment by paulrouget** [comment]
> Somewhat unrelated to this issue, but I wasn't sure where else to post it

When it comes to the way the embedder and servo communicate, #15645 is a good place to discuss. Also, see #15934.

**Comment by paulrouget** [comment]
Fixed by #17425
