### ISSUE TITLE
Build process hangs indefinitely on FreeBSD

### ISSUE THREAD

**Issue by yarwelp** [servo/servo#17232]
Using master branch at 1ea4a44fad4dfd6d7ca1152e06cf07b7e927951b.

Operating System: FreeBSD 11.0

When I run `./mach build -d`, it gets to where it's compiling dependencies. It'll compile a few of them and then it will hang indefinitely and the CPU utilization for the rustc child processes drop to 0%.

I have cleaned with `./mach clean` followed by `git clean -xf` and tried to run it again multiple times, and it'll hang each time but the crates that are currently in progress when it hangs differ from time to time.

I have tried to run `./mach build -d -j 1` thinking that parallel building might be the problem but it hangs either way.

I have cleaned and then tried to build using system-wide `cargo` and `rustc`, which is known to work for other Rust projects. Same result, it hangs.

**Comment by myfreeweb** [comment]
This isn't related to Servo, this is a duplicate of https://github.com/rust-lang/rust/issues/44433

Also, Servo on FreeBSD only works since an hour ago, with my changes https://github.com/servo/servo/issues/11625 :)

**Comment by yarwelp** [comment]
Thanks @myfreeweb. I'll close this issue then.
