### ISSUE TITLE
GlobalScope::current should return Option

### ISSUE THREAD

**Issue by jdm** [servo/servo#17238]
It invokes CurrentGlobalOrNull but does not actually handle the null case and asserts in global_scope_from_global.

**Comment by brainlessdeveloper** [comment]
I would like to work on this, considering I've been working on the PR where this was originated.

**Comment by jdm** [comment]
Sure! I expect in many cases we can just attach `.expect("No current global object")` to the existing uses of the API.

**Comment by brainlessdeveloper** [comment]
Sounds good, I'll be on it in the weekend. If you think you'd like to do this earlier, I'd have no problems with that :)

**Comment by jdm** [comment]
Nope, no hurry!

**Comment by jdm** [comment]
@brainlessdeveloper Have you made progress on this?

**Comment by brainlessdeveloper** [comment]
I've been quite busy recently, I wouldn't mind if you unassign me. I have to complete #16508 too.

**Comment by moonlightdrive** [comment]
@highfive: assign me

I have a PR waiting for review, but would like to take a look at this in the meantime.. if that's alright?

**Comment by jdm** [comment]
Yes, please do. I'm going to be dealing with that PR soon; sorry for the delay.

**Comment by moonlightdrive** [comment]
@jdm no worries!

How should I verify that my changes work? Is there a particular test I should run?

**Comment by jdm** [comment]
If you make the API return Option and use expect() in every existing case, there will be no functional change.
