### ISSUE TITLE
bhtml no longer showing navigation/url bar

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#17246]
Just built the latest Servo and noticed that we're not showing the bhtml chrome any more once you click on a link in the gallery:

![screen shot 2017-06-09 at 11 17 21](https://user-images.githubusercontent.com/547158/26954661-6349a306-4d05-11e7-85d2-b9e0c863021b.png)

**Comment by jonathandturner** [comment]
It's possible this is coming from a build that had stale components.  Doing a clean build now.

**Comment by cbrewster** [comment]
Happens for me too, looking into this now

**Comment by cbrewster** [comment]
Looks like this was caused by #17077

**Comment by cbrewster** [comment]
Looks like this is just an issue with `mozbrowser` test case:

iframe.html
```
<iframe src="child.html" mozbrowser></iframe>
```

child.html
```
<p>I am the child.</p>
```

```
./mach run -d -- --pref dom.mozbrowser.enabled iframe.html
```

The load of `child.html` happens in the root browsing context.

**Comment by cbrewster** [comment]
We are sending the wrong frame tree, we end up sending the frame tree of the iframe. Looks like the code to climb the parent hierarchy in `send_frame_tree` is not working properly.

cc @asajeffrey

**Comment by asajeffrey** [comment]
Oops. Am investigating.

**Comment by asajeffrey** [comment]
Argh, off-by-one error! https://github.com/servo/servo/blob/094c2c73ec77dec51dc57d8aee272a91a52ddfb8/components/constellation/constellation.rs#L2858-L2866 should be:
```rust
        while let Some(pipeline) = self.pipelines.get(&pipeline_id) {
            browsing_context_id = pipeline.browsing_context_id; // THIS LINE WAS IN THE WRONG PLACE
            match pipeline.parent_info {
                Some((parent_id, _)) => {
                    pipeline_id = parent_id;
                },
                None => break,
            }
        }
```

**Comment by asajeffrey** [comment]
I approved #17248, which should fix this.
