### ISSUE TITLE
Reduce code duplication when adding a SessionHistoryChange

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#17249]
The constellation has quite a few occurrences of:
```rust
self.handle_load_start_msg(new_pipeline_id);
self.pending_changes.push(SessionHistoryChange {
    top_level_browsing_context_id: top_level_browsing_context_id,
    browsing_context_id: browsing_context_id,
    new_pipeline_id: new_pipeline_id,
    load_data: load_data,
    replace_instant: None,
});
```

We should create a method in the constellation called `add_pending_change` to reduce code duplication and ensure that `handle_load_start_msg` is always called when a new pending change is pushed.

code: `components/constellation/constellation.rs`

**Comment by jkl445** [comment]
@highfive: assign me
