### ISSUE TITLE
Text rendering: Characters are not in line

### ISSUE THREAD

**Issue by Feliix42** [servo/servo#17264]
I just fired up servo on ff17af064b672482e12d98ec474e2dc0013cb17f, built in `--release` mode on macOS and noticed that on https://github.com, the characters of text are not in line:

<img width="756" alt="screen shot 2017-06-10 at 13 01 25" src="https://user-images.githubusercontent.com/9332912/27002281-2e0bee54-4dde-11e7-9b1a-d572e72e8a24.png">

It's subtle, but some of the characters are a few pixel higher/lower than the rest.

**Comment by emilio** [comment]
cc @glennw, I'm not sure if this is Servo's text layout stuff, or WR's :)

**Comment by atouchet** [comment]
This is likely a duplicate of #17175.

**Comment by emilio** [comment]
That sounds like it, thanks!
