### ISSUE TITLE
Servo breaks the Windows clipboard

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17271]
Currently when Servo is running it is no longer possible to copy and paste in Windows. This issue affects all programs, not just Servo itself. For example while Servo is running it is not possible to copy a URL from Firefox to paste into Notepad. Taking a screenshot while Servo is running also currently does not work. This issue may be due to #17067 but I have not verified that.

This was previously discussed (along with some potential causes) in #16459.

**Comment by est31** [comment]
This PR will fix this: https://github.com/aweinstock314/rust-clipboard/pull/42

**Comment by est31** [comment]
Theoretically, you could also work around this in servo, but then you'd have to create a clipboard context on every single clipboard interaction, which might be expensive on X11. So I'd prefer the proper fix.

**Comment by est31** [comment]
And yes, it has been introduced by  #17067.

**Comment by aweinstock314** [comment]
I've merged https://github.com/aweinstock314/rust-clipboard/pull/42.

**Comment by est31** [comment]
I've filed #17413, but not tested it. @atouchet if you can compile servo, could you test it?

**Comment by atouchet** [comment]
@est31 I just tested the latest nightly build that includes your change and it does appear to have fixed this issue. Thanks!
