### ISSUE TITLE
EagerPseudoStyles should use an Arc rather than a Box

### ISSUE THREAD

**Issue by bholley** [servo/servo#17300]
This lives in components/style/data.rs

We copy these styles when sharing styles with pseudo-elements, and it would be much better to just bump the refcount rather than duplicating the heap-allocation.

This should be a trivial change.

**Comment by bholley** [comment]
Filed on the Gecko side as https://bugzilla.mozilla.org/show_bug.cgi?id=1371049

**Comment by brainlessdeveloper** [comment]
@highfive: assign me

**Comment by bholley** [comment]
This is a bit more subtle now that #17481 landed, so I'm going to steal this.

@highfive: assign me

**Comment by bholley** [comment]
Patches up for review in https://bugzilla.mozilla.org/show_bug.cgi?id=1371049

**Comment by brainlessdeveloper** [comment]
That's fine, sorry I was eager to take a new task and then figured out I didn't have the time.

**Comment by bholley** [comment]
No worries! Feel free to grab another issue when you have time.
