### ISSUE TITLE
Incremental layout bug in matter.js demo.

### ISSUE THREAD

**Issue by glennw** [servo/servo#17307]
A small 2d physics demo can be found here - https://gist.github.com/glennw/3435b37650405d0cb33a7397c2e27734.

Running it with Servo results in the following output:

![bug1](https://user-images.githubusercontent.com/2350882/27114047-3061215a-5104-11e7-8e8b-f6d81bbcf053.png)

However, if you run with the ```-i``` command line option to disable incremental layout, you see the correct result, which is:

![bug2](https://user-images.githubusercontent.com/2350882/27114063-41d69794-5104-11e7-81c0-11f7ebf8d44e.png)

**Comment by glennw** [comment]
cc @pcwalton @emilio in case you have any ideas.

**Comment by metajack** [comment]
cc @mbrubeck in case he wants to look

**Comment by mbrubeck** [comment]
Here's a reduced test case:

```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      #rect {
        position: absolute;
        border: 1px solid red;
        width: 40px;
        height: 40px;
      }
    </style>
  </head>
  <body>
    <div id="rect"></div>
    <script>
      var x = 10;
      var tick = function() {
        x += 4;
        var e = document.getElementById("rect");
        e.style.left = x + "px";
        window.requestAnimationFrame(tick);
      }
      requestAnimationFrame(tick);
    </script>
  </body>
</html>
```
