### ISSUE TITLE
Better document which threads can block on which other threads

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#17301]
We should document which threads are allowed to block on which other threads, to avoid deadlock.

**Comment by asajeffrey** [comment]
IRC conversation with @jdm and @cbrewster about this: http://logs.glob.uno/?c=mozilla%23servo&s=13+Jun+2017&e=13+Jun+2017#c696366

TL;DR: oh, the constellation can block on layout (e.g. https://github.com/servo/servo/blob/fe573c1ce9a7cbacf69a846ad966c429faa61703/components/constellation/constellation.rs#L2524-L2530)

**Comment by jdm** [comment]
My ideal would be if we could enforce this with the type system or a compiler plugin somehow.

**Comment by asajeffrey** [comment]
@jdm: that would be even better.

**Comment by asajeffrey** [comment]
We now at least have documentation: https://github.com/servo/servo/blob/ced2668c6c4172069ba4789b805137d7c1375ce3/components/constellation/constellation.rs#L64-L90
