### ISSUE TITLE
loading image asynchronously before page load causes failed assertion

### ISSUE THREAD

**Issue by duckinator** [servo/servo#17319]
Loading an image asynchronously (e.g. `setTimeout` or the load event of an XMLHttpRequest),  before `window.onload` is triggered causes a failed assertion in `script/document_loader.rs`.

Loading it synchronously(?) (e.g. just calling the function directly) or in `window.onload` makes it work fine.

---

This is the error I get (stack trace removed; see below):

```
assertion failed: self.load.is_none() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /home/ellen/dev/rust/servo/servo/components/script/document_loader.rs:78)
```

And sometimes this error repeating (stack trace removed; see below):

```
ERROR:servo: assertion failed: self.load.is_none()
called `Result::unwrap()` on an `Err` value: () (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }, at /checkout/src/libcore/result.rs:860)
```

---

I have created a [this test case](https://gist.github.com/duckinator/8617acf8b002fb628e70ccbc96cba01c) which consistently reproduces the issue with commit https://github.com/servo/servo/commit/8837c80540327db28a6569f0661816b998b65b9f (master as of opening this issue).

The test case gist contains full stack traces, details on running the test case, etc.

**Comment by jdm** [comment]
We should be calling `terminate()` on any existing load blocker before reassigning it in https://dxr.mozilla.org/servo/rev/c6da6ba06057ec488521edb19f33592f4e98c3d4/components/script/dom/htmlimageelement.rs#496 .

**Comment by jdm** [comment]
e.g. https://dxr.mozilla.org/servo/rev/c6da6ba06057ec488521edb19f33592f4e98c3d4/components/script/dom/htmlimageelement.rs#286

**Comment by duckinator** [comment]
Okay, so I [have it working](https://github.com/duckinator/servo/commit/2ff6fe3208226380495bfca7fbebccf726616ddf) (tested manually), but I'm not sure where the test should go.

**Comment by duckinator** [comment]
I managed to [get it working](https://github.com/duckinator/servo/commit/2ff6fe3208226380495bfca7fbebccf726616ddf) (tested manually), but I have absolutely no idea where to start with adding a test for this.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests describes how to add new test files; this one would be a non-reference test and belongs in tests/wpt/mozilla/tests/mozilla, since it's not testing any particular property of the HTML specification. Making an [async test](http://web-platform-tests.org/writing-tests/testharness-api.html) that completes when the image's onload event handler is triggered should do the trick.

**Comment by duckinator** [comment]
Rebased again. Going to try adding a test, now. 👍

**Comment by duckinator** [comment]
Added a test and opened a PR.
