### ISSUE TITLE
Over-alignment assert crash on Android (using ThinArc in Selector)

### ISSUE THREAD

**Issue by MortimerGoro** [servo/servo#17320]
After https://github.com/servo/servo/commit/27568de567b4e16cc6f570715f6d65d812100e32 landed Servo crashes with this assert failure on Android:

```
assert!(mem::align_of::<T>() <= mem::align_of::<usize>(),
           "We don't handle over-aligned types");
```

Info of involved types:
`mem::align_of::<selectors::parser::Component<servo::selector_parser::SelectorImpl>() = 8`
`mem::align_of::<usize>() = 4`

**Comment by MortimerGoro** [comment]
cc @bholley

**Comment by bholley** [comment]
Hm, that's weird. Is this a 64-bit platform which allows half-aligned words, or is there something in Component that's causing it to be over-aligned?

**Comment by MortimerGoro** [comment]
It's a 32 bit compilation (armv7): usize is 4 bytes. Component seems to use 8 byte alignment so they don't match.

Is it possible to use u64 instead of usize in ThinArc? That would fix the issue.

Another alignment issue I fixed some time ago: https://github.com/servo/servo/pull/16833

**Comment by bholley** [comment]
It's really not great to over-allocate on 32-bit, which could cause us to spill into the next jemalloc bin. It seems like we should just branch when computing |buffer| depending on whether T is over-aligned. The branch should compile away in optimized builds.

Also, this isn't related to ThinArc AFAICT. It's about Arc<HeaderSlice<H, [T]>>.
