### ISSUE TITLE
Scroll offset change for both document.body and document.documentElement

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#17342]
Take this [document](https://gist.github.com/pyfisch/eb624bffa9d21177519099ebd065a040). It tells you where in the blue rect the cursor is placed when you click it. It also prints out some debug information to the console. If you scroll it to the bottom:

* in Chrome: `document.body.scrollTop` is changed
* in Firefox: `document.documentElement.scrollTop` is changed
* in Servo: both are changed by the same value

This results in a wrong position being calculated for the mouse cursor because the scroll offset is added twice.

Ping @jdm. Maybe related to #17327.

**Comment by emilio** [comment]
The scrollTop behavior in Blink is a known Blink bug btw, and they're trying to interop, but it happens to be hard :)

https://bugs.chromium.org/p/chromium/issues/detail?id=157855

**Comment by pyfisch** [comment]
This seems to be the relevant function: https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L1709

For me it looks like it correctly switches between quirks mode  with `document.body.scrollTop` and standards mode with `document.documentElement.scrollTop`. But it somehow triggers both paths.

**Comment by pyfisch** [comment]
I have a patch that may fix it.
