### ISSUE TITLE
Make send_profile_data take profiler_chan argument by reference

### ISSUE THREAD

**Issue by jdm** [servo/servo#17363]
This will allow us to pass borrowed channel arguments to it, rather than unnecessarily cloning them.

Code: `components/profile_traits/time.rs`

**Comment by o0Ignition0o** [comment]
@highfive assign me

**Comment by jklepatch** [comment]
@highfive: assign me

**Comment by jklepatch** [comment]
oops, I sent an "assign me" message while the page wasnt refreshed, so didnt see it had already been assigned. Please ignore my message and leave the original assignee, its fine :)

**Comment by o0Ignition0o** [comment]
Hey, no problem, it has also happened to me lately :)

**Comment by o0Ignition0o** [comment]
I wonder if I should also refactor the ` pub fn profile<T, F>(category: ProfilerCategory,
                     meta: Option<TimerMetadata>,
                     profiler_chan: ProfilerChan,
                     callback: F)
                  -> T
    where F: FnOnce() -> T ` method, but I don't feel confident enough to make the call, since I don't really understand what it would imply.
