### ISSUE TITLE
Paint worklets: nondeterministic worklet scripts?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#17374]
Worklet scripts might find some source of entropy to become nondeterministic, even if (e.g.) we seed `Math.random` identically in all the worklet threads. I'm not sure what to do if registration is nondeterministic, e.g. if one thread registers `alpha: false` and another `alpha: true` for the same worklet?

**Comment by nox** [comment]
Seems like this issue should be raised with the spec, not here.

**Comment by asajeffrey** [comment]
This got resolved.
