### ISSUE TITLE
Paint worklets: timeout

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#17370]
We should timeout invoking a paint worklet (e.g. after 10ms).

**Comment by nox** [comment]
Where is the code for that? Can it be made into an E-Easy issue?

**Comment by asajeffrey** [comment]
Not sure it's E-Easy, perhaps E-Less-Easy? I'm not sure that anything about concurrent communication is E-Easy :/

The code is at: https://github.com/servo/servo/blob/e3624e62a4b247d7af5e783fcd4205d2914b6aab/components/script/dom/paintworkletglobalscope.rs#L357

The change is to replace that `recv` by a receive-with-timeout. The less-easy part is working out how to test for this behaviour.

**Comment by KiChjang** [comment]
Do we have anything similar to [Sinon fake timers](http://sinonjs.org/releases/v1.17.7/fake-timers/) in rustland? It would be great for testing this.

**Comment by asajeffrey** [comment]
I don't think we do, in general it would be really nice for testing if we could mock up channels, timers, etc., but I don't think there is such a thing :/

**Comment by nox** [comment]
I'm very much against mocking 'etc'.

**Comment by yati-sagade** [comment]
I would like to give this a shot. Let me see if I can add a timeout to the `recv()`, and then poke one of you for testing.

**Comment by asajeffrey** [comment]
@yati-sagade Cool!

**Comment by KiChjang** [comment]
@yati-sagade Are you still working on this?

**Comment by yati-sagade** [comment]
@KiChjang yes, I've a patch, but working on the test. I thought first I'd throw I `TimeoutError` in the client code (super easy to test for), but it turns out (thanks @asajeffrey for pointing out) that the [spec](https://www.w3.org/TR/css-paint-api-1/#drawing-an-image) recommends not doing that.

**Comment by asajeffrey** [comment]
@yati-sagade I filed a spec issue about this, whether there's some way to inform scripts that they are being treated as unresponsive.

For the moment, I think the thing to do is to write a reftest with a worklet that does something like `sleep(60000)`, and make sure that it is just displayed as a invalid image. The test should currently `TIMEOUT`, but be `OK` with your PR applied.

**Comment by asajeffrey** [comment]
PS: that spec issue was https://github.com/w3c/css-houdini-drafts/issues/507

**Comment by asajeffrey** [comment]
The spec issue was punted to v2 of worklets, so we'll have to work around it in our tests I'm afraid.
