### ISSUE TITLE
Paint worklets: cssText

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#17379]
We are supporting the non-standard `cssText` property, which is used by houdini-samples. This should preferably be removed, and at least hidden behind a pref.

**Comment by asajeffrey** [comment]
The matching houdin-samples issue: https://github.com/GoogleChrome/houdini-samples/issues/16.

**Comment by shinglyu** [comment]
So this is just to pref-off cssText property? Can I give it a try?

**Comment by nox** [comment]
Where is the code for that? What exactly should be done?

**Comment by asajeffrey** [comment]
At this point, houdini-samples has removed cssText, so the task is just to remove the cssText property from `CSSStyleValue.webidl` and the matching `.rs`. A good E-Easy I think.
