### ISSUE TITLE
Website titles don't show up in sidebar

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17388]
I'm not sure if this is a Servo or Browser.html issue but I don't recall running into this earlier.

![Website titles missing](https://i.imgur.com/t97Mou2.png)

Tested in Windows 10.

**Comment by paulrouget** [comment]
I confirm. Wondering if `mozbrowsertitlechange` is properly triggered.

**Comment by paulrouget** [comment]
`mozbrowsertitlechange` is correctly triggered (proof is that the titlebar is being updated).

Not sure yet what's going on. Might be a rendering issue.

**Comment by atouchet** [comment]
This appears to be fixed now.
