### ISSUE TITLE
Constellation: there should be one focused pipeline by top level browsing context id

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#17401]
At the moment, there is one global focused pipeline.

The actual focused pipeline being the focused pipeline under the last top level browsing context sent to the compositor.

**Comment by mandreyel** [comment]
How has https://github.com/servo/servo/pull/21713 affected this issue? Can you please give a few more details?

**Comment by paulrouget** [comment]
I'm not sure. I haven't looked at this for a long time, so this might not be relevent.

Looking at the PR, that might just work as long as focused_browsing_context_id is a top level browsing context.

The idea is this: there are multiple top level browsing contexts and only one is "active" (see `active_browser_id`). Let's say `top level context A` is active and a descendant `pipeline a` is focused. When switching to `top level context B` (by calling `send_frame_tree`) a descendant pipeline of B is focused. Switching back to A, we need to make sure `pipeline a` is the one getting the focus.

**Comment by mandreyel** [comment]
@paulrouget I'm sorry, I completely missed that you responded!

Hmm, I think I may be lacking some context to fully understand the issue. Since we're now tracking focused browsing contexts (introduced in the PR), which means their current pipeline is also the focused pipeline, is your proposed invariant not already ensured?

**Comment by cbrewster** [comment]
The issue here is tracking the focused browsing context per top-level browsing context. In other words, we need to track the active browsing context per browser tab. This would mean there should be multiple focused browsing contexts at once (one per top-level browsing context/browser tab).

**Comment by mandreyel** [comment]
Ah, I wasn't taking tabs into account (though I had a suspicion), since afaik it's not yet supported by Servo. So am I right that this will only become relevant when #21363 progresses?

**Comment by paulrouget** [comment]
@mandreyel Tabs are internally supported. But there's no UI for it. Every time the embedder sends a `NewBrowser` message, a new top level browsing context is created. We switch between "tabs" by send the right frame tree to WR. This happens with the `SelectBrowser` message.

**Comment by mandreyel** [comment]
Ah, that makes sense. Thanks for clearing it up. This is indeed an unsolved issue, I'll look into it later.

**Comment by mandreyel** [comment]
@highfive assign me
