### ISSUE TITLE
deny_public_fields proc macro prints misleading field name of structs

### ISSUE THREAD

**Issue by creativcoder** [servo/servo#17438]
In the new proc macro `deny_public_fields` to replace `#[privatise]`, our diagnostics isn't clear.

On introducing `pub` on `name` field of `File` struct in `components/script/dom/file.rs`
```rust
#[dom_struct]
pub struct File {
    blob: Blob,
    pub name: DOMString,
    modified: i64,
}
```
and compiling we get:

```rust
error: proc-macro derive panicked
  --> /home/creativcoder/Desktop/servo/components/script/dom/file.rs:20:1
   |
20 | #[dom_struct]
   | ^^^^^^^^^^^^^
   |
   = help: message: Field __binding_1 should not be public

```

Instead the help message should be something like: 

= help: message: Field `name` should not be public

Code that needs changes: `components/deny_public_fields/lib.rs`

Hey @jdm, If this sounds like an easy bug to you then we can tag it with `E-Easy`.

**Comment by jdm** [comment]
I suspect this would be fixed by trying to use `binding.field.ident` first, and falling back to `binding.ident` otherwise.

**Comment by jdm** [comment]
We should be able to create an automated test for this too by making https://dxr.mozilla.org/servo/source/tests/compiletest/plugin/compile-fail/privatize.rs#11 a more specific error message.

**Comment by HarveyHunt** [comment]
@highfive: assign me

**Comment by jdm** [comment]
Oh, and to run the test you use `./mach test-compiletest` if I'm not mistaken.

**Comment by HarveyHunt** [comment]
I've implemented using ```binding.field.ident``` before falling back to ```binding.ident```, as can be seen [here](https://github.com/HarveyHunt/servo/commit/390d3850655a81d52eeb715f8ede1dbf3c2ffcc9).

However, I'm not sure what is meant about creating an automated test. I've messed around with the ```ERROR``` in privatize.rs, so I now realise that the comment is matched to the compiler's output. How can I make the error message more specific without the compiler's error message also needing to be changed?

Could you explain a little more please? If it makes it easier for you, I am ```hunt``` on mozilla IRC.

**Comment by jdm** [comment]
I believe the string in the comment is a subset match, so it should be possible to make it more specific than it currently is.
