### ISSUE TITLE
Paint worklets: space leak when pipeline is closed

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#17442]
We should make sure that paint worklets don't space leak. For example, when a browsing context is discarded, we should remove any worklet global scopes it created from the thread pool.

**Comment by nox** [comment]
This issue is not actionable, we should close it.

**Comment by asajeffrey** [comment]
Renamed the issue to make it actionable. This might make a good E-Mentored issue.

**Comment by KiChjang** [comment]
@asajeffrey Can we get a little bit more information about what we're trying to solve here? Files to edit, and function names to grep for would be a good starter.

**Comment by asajeffrey** [comment]
OK, deep breath...

The problem is that when a `Worklet` is dropped, the `WorkletThreadPool` isn't informed. So the idea would be to impl `Drop` for `Worklet`, and have it go get the thread pool from the script thread, and call a `exit_worklet` method. The thread pool would build an `ExitWorklet` control message, which it would send to each of the worklet threads. Each worklet thread would then remove its instance of the worklet global scope.

`Worklet` is defined at https://github.com/servo/servo/blob/e3624e62a4b247d7af5e783fcd4205d2914b6aab/components/script/dom/worklet.rs#L78

The method to get the worklet thread pool from the script thread is https://github.com/servo/servo/blob/e3624e62a4b247d7af5e783fcd4205d2914b6aab/components/script/script_thread.rs#L702

The method to remove a worklet from the pool would be similar to the one which loads a worklet script https://github.com/servo/servo/blob/e3624e62a4b247d7af5e783fcd4205d2914b6aab/components/script/dom/worklet.rs#L279

There'd need to be an `ExitWorklet(WorkletId)` case added to the `WorkletControl` enum https://github.com/servo/servo/blob/e3624e62a4b247d7af5e783fcd4205d2914b6aab/components/script/dom/worklet.rs#L329

This in turn requires adding a case to `process_control`, which would remove the entry from `self.global_scopes` https://github.com/servo/servo/blob/e3624e62a4b247d7af5e783fcd4205d2914b6aab/components/script/dom/worklet.rs#L623

**Comment by gterzian** [comment]
@AgustinCB this one looks like a fun issue to work on(going straight to the heart of some of Rust's concurrency aspects), with mentoring available!

**Comment by AgustinCB** [comment]
Sounds fun. I'll give this one a try. Thanks!

**Comment by asajeffrey** [comment]
@AgustinCB good luck!

**Comment by AgustinCB** [comment]
Will probably finish the pr this weekend.
