### ISSUE TITLE
Low quality "Build on GitHub" icons

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17465]
From the "Build on GitHub" section of the GitHub homepage. The icons look noticeably worse in Servo than in other browsers. Also strangely they appear to be slightly off-centre as well. Possibly the same issue as #11960.

Image of the issue (Firefox top, Servo bottom):

![Icon comparison](https://i.imgur.com/eK89tMM.png)

Tested in Windows 10.

**Comment by jdm** [comment]
@glennw Could this be an issue in WR?

**Comment by atouchet** [comment]
There is a second example of this issue on https://github.com/features as well.

**Comment by atouchet** [comment]
![Icon comparison](https://i.imgur.com/NLKTs7K.png)

This is slightly improved in the latest nightly build but most of the icons are still bad looking. The only one that is noticeably different is Codeship and that now looks blurrier than in Firefox. @glennw is this due to https://github.com/servo/webrender/pull/2408? I noticed that Codeship is the only icon there larger than 512 x 512 (https://assets-cdn.github.com/images/modules/site/integrators/codeship.png).

**Comment by atouchet** [comment]
These images are no longer on the GitHub homepage.
