### ISSUE TITLE
libssl troubles in fedora 26

### ISSUE THREAD

**Issue by r105m** [servo/servo#17509]
running servo from nightly builds on fedora 26 
$ ./servo 
./servo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

------
it looks like i have poenssl 1.1:
$ openssl version
OpenSSL 1.1.0f-fips  25 May 2017

**Comment by est31** [comment]
Known bug: #12015

**Comment by jdm** [comment]
Closing since we're tracking this in the existing issue.
