### ISSUE TITLE
Servo doesn't properly render img border-radius

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17510]
Example on: https://github.com/business

The face pictures are supposed to be circles but in Servo they are squares.

Image (Servo on top, Firefox on bottom):

![border-radius](https://i.imgur.com/Vgx0ayl.png)

The offending line appears to be: `<img src="https://assets-cdn.github.com/images/modules/site/avatars/hubspot-quote.jpg" alt="" style="border-radius:25px;" width="50" height="50">`

Tested in Windows 10.

**Comment by jdm** [comment]
All of our tests for border-radius appear to use background-image, rather than image elements.

**Comment by streichgeorg** [comment]
I looked a bit into this and found that at the moment the clipping region only gets adjusted in ```build_display_list_for_background_if_applicable```, when I copy the code from there to ```build_fragment_type_specific_display_items```, the the test gets rendered correctly.

**Comment by jdm** [comment]
Sounds like a reasonable solution to me (possibly sharing the code in a `clip_for_border_radius` function).

**Comment by streichgeorg** [comment]
Should the ```border-radius``` property also affect tags like ```canvas```and ```iframe```, or only ```img``` ones?

**Comment by jdm** [comment]
Yes, it should affect every element.

**Comment by streichgeorg** [comment]
I have another one last question. How should I test this PR, and where do I put the tests?

**Comment by jdm** [comment]
I recommend adding a [reference test](http://web-platform-tests.org/writing-tests/reftests.html). You can create a new one in tests/wpt/mozilla/css/ as described in [the documentation](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests).

**Comment by atouchet** [comment]
This is fixed now.
