### ISSUE TITLE
Issue with button rounded corners on github.com/business

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17511]
In Servo these button corners are not displayed properly. Also when both browsers are in fullscreen the buttons are 10 pixels wider in Servo than in Firefox.

Image (Servo on top, Firefox on bottom):

![Button corners](https://i.imgur.com/WowoFuK.png)

Tested in Windows 10.

**Comment by emilio** [comment]
cc @glennw

**Comment by emilio** [comment]
(The 10px extra is probably a layout issue with `::before` and `::after`.

**Comment by atouchet** [comment]
This is fixed now.
