### ISSUE TITLE
Top bar on Hacker News too large

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17513]
The top orange bar on Hacker News is longer in Servo than in other browsers. Servo has it as 33 pixels tall while in other browsers it is 24 pixels. There is also additional space around the Hacker News icon in Servo (2 additional pixels on the top and left, 5 on the bottom). Finally in Servo the Hacker News icon is shown as being 20 x 20 rather than 18 x 18.

In Servo:

![Servo bar](https://i.imgur.com/YY4pj2z.png)

In Firefox:

![Firefox bar](https://i.imgur.com/ldxIJg5.png)

Tested in Windows 10.

**Comment by emilio** [comment]
I believe this is https://github.com/servo/servo/issues/14947

**Comment by jdm** [comment]
That comment thread leads us to https://github.com/servo/servo/issues/11704#issuecomment-230722674 as the real culprit.

**Comment by adamncasey** [comment]
#12609 will also help out here

**Comment by atouchet** [comment]
This is probably a duplicate of #11821.
