### ISSUE TITLE
Images become squished when browser window is resized

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17572]
Issue observed on: https://github.com/business

When resizing the Servo window from fullscreen to half the screen the "Trusted by more than 100,000 organizations" images become distorted and squished.

Example images:

Servo fullscreen:

![Servo fullscreen](https://i.imgur.com/DrTYEUs.png)

Servo narrow window:

![Servo narrow](https://i.imgur.com/A57N75i.png)

Firefox fullscreen:

![Firefox fullscreen](https://i.imgur.com/f67T2FM.png)

Firefox narrow window:

![Firefox narrow](https://i.imgur.com/JhqfT4p.png)

Tested in Windows 10.

**Comment by atouchet** [comment]
This issue also occurs on https://github.com/business/customers without the window having to be resized. The images are squished when the browser is fullscreen as well.

**Comment by stshine** [comment]
Looks like a flexbox issue :(

**Comment by atouchet** [comment]
The example images are no longer available.
