### ISSUE TITLE
Store Rc<Box<[Heap<JSVal>]>> instead of vector in FunctionTimerCallback

### ISSUE THREAD

**Issue by jdm** [servo/servo#17611]
Right now we store `Rc<Vec<Heap<JSVal>>>` in that enum variant, but it would be more clear to store a [boxed slice](https://doc.servo.org/collections/vec/struct.Vec.html#method.into_boxed_slice) instead. This would make it impossible for the vector to be modified, which is unsafe when it is storing Heap values.

Code: https://dxr.mozilla.org/servo/rev/296a215e5404eb0fd0c0a34cc1283cd0b84aaea9/components/script/timers.rs#353

No need for any automated test; if it compiles that's good enough for a PR.

**Comment by sadmansk** [comment]
I can take a look at this

**Comment by KiChjang** [comment]
Go for it!

**Comment by sadmansk** [comment]
@highfive: assign me
