### ISSUE TITLE
Enable AppVeyor for servo/unicode-bidi

### ISSUE THREAD

**Issue by behnam** [servo/servo#17629]
Can we enable AppVeyor for `servo/unicode-bidi` in regards to service bandwidth? If so, would be great to have it!

We have added `.appveyor.yml` to the master already (https://github.com/servo/unicode-bidi/pull/42):

> * Add appveyor.yml, as many packages depending on this package already require stable windows builds.

Thanks!

**Comment by jdm** [comment]
cc @edunham

**Comment by edunham** [comment]
https://ci.appveyor.com/project/servo/unicode-bidi

It's now enabled.
