### ISSUE TITLE
Move Ctrl-F12 keybindings outside of libservo

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#17647]
This code should be removed from here: https://github.com/servo/servo/blob/95a85a301f1d014c45448a4d5d4f5a8497904af6/components/compositing/compositor.rs#L1316

Catching the keybinding should be done here: https://github.com/servo/servo/blob/95a85a301f1d014c45448a4d5d4f5a8497904af6/ports/glutin/window.rs#L1293

And new WindowEvent should be created here: https://github.com/servo/servo/blob/95a85a301f1d014c45448a4d5d4f5a8497904af6/components/compositing/windowing.rs#L34

And caught here: https://github.com/servo/servo/blob/95a85a301f1d014c45448a4d5d4f5a8497904af6/components/compositing/compositor.rs#L738 where we can actually toggle the profiler.

**Comment by Tremoneck** [comment]
@highfive: assign me

**Comment by paulrouget** [comment]
@Tremoneck Thanks! Let me know if there's anything I can do to help.

**Comment by Tremoneck** [comment]
@paulrouget After moving everything over and testing, it works, but it gives a warning about an usused import, should I just remove the import, or leave it in case someone else needs said import. The message ```warning: unused import: `CONTROL`
  --> D:\git\Servo\servo\components\compositing\compositor.rs:14:59
   |
14 | use msg::constellation_msg::{Key, KeyModifiers, KeyState, CONTROL};
   |                                                           ^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default```

**Comment by jdm** [comment]
If your changes cause new warnings to appear, please make appropriate changes that make the warnings go away :)
