### ISSUE TITLE
Servo crashes reliably on refresh

### ISSUE THREAD

**Issue by lilianmoraru** [servo/servo#17645]
I downloaded `servo` from: https://download.servo.org
`servo --version`: `Servo 0.0.1-104e0b4`

Steps to reproduce the crash:
1. Go to a website, example "github.com", wait for it to load
2. Press "F5"
3. It should crash

Here are logs attached where I did this:
1. Go to `github.com`
2. Go to `feedly.com`(I initially thought that it was related to feedly, it crashed there even without a refresh, but it seems that it was not related to `feedly` specifically)
3. Pressed in the middle of the page(with the mouse) and then "F5"(after the page loaded completely)
4. Crashed

`RUST_LOG=trace ./servo`: [logs.zip](https://github.com/servo/servo/files/1133937/logs.zip)

**Comment by lilianmoraru** [comment]
Here are shorter logs that remove some of the spammy logs.
This was run like this: `RUST_BACKTRACE=full RUST_LOG=trace,webrender::clip_scroll_node=error,script::dom::window=warn ./servo`

[shorter_logs.zip](https://github.com/servo/servo/files/1133953/shorter_logs.zip)

**Comment by jdm** [comment]
I have not been able to reproduce this in a local debug build following those steps.

**Comment by sadmansk** [comment]
@lilianmoraru Which platform is this crashing on?

**Comment by lilianmoraru** [comment]
Linux Ubuntu 16.04 LTS(KDE neon).

**Comment by dralley** [comment]
Issue should probably be closed due to age.
