### ISSUE TITLE
CanvasPaintState::new should take a AntialiasMode not a boolean

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#17668]
At the moment, `CanvasPaintState::new` in `components/canvas/canvas_paint_thread.rs ` takes its anti-alias mode argument as a boolean. Really this should be an `AntiAliasMode`. See https://github.com/servo/servo/pull/17609#discussion_r126669932.

**Comment by jdm** [comment]
Duplicate of #17661.

**Comment by asajeffrey** [comment]
Ah, we both filed this!
