### ISSUE TITLE
Hover color transition only affects direct text children

### ISSUE THREAD

**Issue by jdm** [servo/servo#17669]
```html
<style>
div { transition: color 0.1s; color: black }
div:hover { color: red; }
</style>
<div><span>hi</span> there</div>
```
Due to #17667, this testcase is completely broken unless non-incremental layout (`-i`) is enabled. Even with non-incremental layout, however, the text in the span does not change color when the mouse is over any part of the containing div.

**Comment by atouchet** [comment]
This appears to be working as of the 2020-05-07 nightly build.

**Comment by jdm** [comment]
Confirmed!
