### ISSUE TITLE
Make CanvasPaintState::new accept an AntialiasMode enum argument instead of a boolean

### ISSUE THREAD

**Issue by jdm** [servo/servo#17661]
Since it ends up using AntialiasMode internally, let's make it take the same argument type. We should also change the type of argument that CanvasPaintThread::new accepts as well.

Code: `components/canvas/canvas_paint_thread.rs`

No need for automated tests; if it compiles, that's good enough for a PR.

**Comment by marti1125** [comment]
@highfive: assign me
see you on irc channel my nick is marti_

**Comment by DarkDrek** [comment]
Sorry @marti1125 since there haven't been any progress here I shamelessly did a PR for this issue.

**Comment by marti1125** [comment]
Hello @DarkDrek  I can not contact with the person who can help with issue =/ so you can take this please
