### ISSUE TITLE
Test layout against other browser engines

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1768]
Back in 2012, Brian wrote a reftest system using Firefox via Selenium to generate comparison images.  We didn't maintain it and it's now gone from the tree, but you can see the old code with `git log -- src/reftest`.

Revive this idea and integrate it with the current reftest system (which compares Servo's rendering on two related pages).  Maybe look at other frameworks for cross-browser testing and see what it would take to integrate Servo.

**Comment by mrobinson** [comment]
I think the answer to this need nowadays is the WPT.
