### ISSUE TITLE
Cleanup downcasting that only check whether it's result is `Some` or `None`.

### ISSUE THREAD

**Issue by emilio** [servo/servo#17697]
We have one occurrence of this in `components/script/webdriver_handlers.rs`:

```rust
else if let Some(_) = node.downcast::<HTMLElement>()
```

This should just be:

```rust
else if node.is::<HTMLElement>()
```

#17501 is introducing another similar use, we should clean that up too.

**Comment by sadmansk** [comment]
I could take a go at this. @highfive: assign me.

**Comment by DarkDrek** [comment]
Are you still working on this issue @sadmansk?

**Comment by sadmansk** [comment]
@DarkDrek Thanks for taking care of this! Sorry for the late reply, but I hadnt done any work on this issue so it's all good 👍
