### ISSUE TITLE
Servo over Xming is slow, unreliable

### ISSUE THREAD

**Issue by cmr** [servo/servo#1769]
On a Windows machine, using X Forwarding + Xming, I can run servo. However, it's abnormally slow (compared to other forwarded applications), and seems to like to explode more often. It also prints:

```
WARNING: Application calling GLX 1.3 function "glXCreatePixmap" when GLX 1.3 is not supported!  This is an application bug!
WARNING: Application calling GLX 1.3 function "glXDestroyPixmap" when GLX 1.3 is not supported!  This is an application bug!
```

before rendering. The system servo is running on is Linux, x64, using the Radeon open source drivers with a mesa from git.

**Comment by larsbergstrom** [comment]
You can now just run Servo on Windows, as of #9385!

I don't think we have plans to make x-forwarded Servo significantly faster.
