### ISSUE TITLE
cleanup `orientation_of_angle` once #17696 lands.

### ISSUE THREAD

**Issue by emilio** [servo/servo#17699]
#17696 is introducing a style that is unheard-of in Servo's codebase:

```rust
        if      rounded_angle < 0.25 * PI { Orientation::Angle0   }
        else if rounded_angle < 0.75 * PI { Orientation::Angle90  }
        else if rounded_angle < 1.25 * PI { Orientation::Angle180 }
        else if rounded_angle < 1.75 * PI { Orientation::Angle270 }
        else                              { Orientation::Angle0   }
```

Instead of this, we should probably use a more rusty style, either early-return in multiple lines:

```rust
if rounded_angle < 0.25 * PI {
    return Orientation::Angle0
}

if rounded_angle < 0.75 * PI {
    return Orientation::Angle90
}

// ...
```

Or in one line (not a fan, but in this case it can be argued that it looks nicer):

```rust
if rounded_angle < 0.25 * PI { return Orientation::Angle0 }
if rounded_angle < 0.75 * PI { return Orientation::Angle90 }
// ...
```

**Comment by jyc** [comment]
Makes sense I suppose, would just like to note that personally I think this sort of horizontal alignment looks pretty nice and makes things clearer to read (it is used in a lot of OCaml code). It also happens to be the code style used in Gecko's implementation of the same function. But changing it to conform to the rest of the code definitely makes sense!

**Comment by emilio** [comment]
Yeah, it's a matter of following rust conventions in general... I'd love if eventually Servo could be [rustfmt](https://github.com/rust-lang-nursery/rustfmt)'d...

**Comment by SergeevPavel** [comment]
I could take it. @highfive: assign me
