### ISSUE TITLE
tidy: Detect keywords with more than one space afterwards

### ISSUE THREAD

**Issue by emilio** [servo/servo#17700]
In `document.rs`:

```rust
            if  now.duration_since(last_time) < DBL_CLICK_TIMEOUT &&
                dist < DBL_CLICK_DIST_THRESHOLD as f64 {
```

(note the double space after the `if`).

We should write a tidy lint that catches this (and presumably also with other keywords, like `else`, `unsafe`, ... (any other?), and makes `./mach test-tidy` fail if that's the case.

@wafflespeanut, would you be able to mentor this? (I can too, though it'd take me a bit more time I presume)

**Comment by emilio** [comment]
```
00:24 <waffles> emilio: note that tidy already catches unnecessary spaces before/after braces - since unsafe/else have braces next to them, we don't have to check for anything else (apart from "if") I guess?
00:25 <emilio> waffles: sounds good. while, for, etc... too, probably
00:25 <emilio> waffles: but not loop, I guess
00:25 <waffles> emilio: there's 'let'
```

**Comment by wafflespeanut** [comment]
A lot of keywords don't necessarily have braces/paren next to them (which include `if`, `let`, `mut`, `type`, `extern`, `as`, etc. - the entire keyword list is listed here - https://doc.rust-lang.org/book/second-edition/appendix-01-keywords.html).

Let's focus on adding a generic function inside `check_rust` function in `python/tidy/servo_tidy/tidy.py` which scans lines for such keywords and yields error if there's more than one space next to the keyword.

**Comment by SergeevPavel** [comment]
@highfive: assign me
