### ISSUE TITLE
Hitting Tab Key Does Not Switch Element Focus

### ISSUE THREAD

**Issue by sciguyryan** [servo/servo#17742]
Hi guys.

I noticed this while testing something relating to element focus styles. I noticed that clicking tab on a focused element does not switch focus from the currently focused element.

The following is a simple testcase to demonstrate this:

```html
<!doctype html>
<html>
  <head>
    <title>Tab Focus Test</title>
  </head>
  <body>
    <button id="test1" onclick="alert('1');">Test 1</button>&nbsp;<button id="test2" onclick="alert('2');">Test 2</button>
    <script>
      let element1 = document.getElementById('test1');
      element1.focus();
    </script>
  </body>
</html>
```

The page will show two buttons, one automatically focused on document load. Hitting tab and clicking enter should display an alert box with "2" inside. Since the focus is not transferred a "1" is displayed instead.

**Comment by paulrouget** [comment]
dupe of #3982 ?

**Comment by sciguyryan** [comment]
Yes, seems that way. Sorry about that. I had searched for "tab" and "focus" but I didn't find that issue listed.

**Comment by paulrouget** [comment]
@sciguyryan Thanks for reporting this! It's always useful to get more reports, especially with step to reproduce and tests.
