### ISSUE TITLE
Windows compile for 32 bit target issues

### ISSUE THREAD

**Issue by ripieces** [servo/servo#17750]
Hello, I am thinking about using Servo as GUI and for scripting for some private project, however it would have to be in a 32 bit target process.

But I am not sure if the servo team plans to support 32 bit target process compiles (since Windows XP and Vista are for example probably also not supported).

I am on a 64bit machine with Windows 10 and Visual Studio Community 2017:
```
Microsoft Visual Studio Community 2017 
Version 15.2 (26430.15) Release
VisualStudio.15.Release/15.2.0+26430.15
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA927
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA927
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA927
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake
````

To compile for a 32 bit target process I tried the **x64_x86 Cross Tools Command Prompt for VS 2017**.

I tried **mach.bat build --release**

I ran into the following problems:

1) After extracting the downloads it often has a problem with moving / renaming the directory, I am guessing maybe it's still in use and some close function after extracting needs to be called in Python, but I don't know:
```
 File "C:\source\servo\python\servo\bootstrap.py", line 224, in windows_msvc
    os.rename(extracted_path, package_dir(package))
````
The problem can be worked around, by simply restarting the build process (or alternatively by moving the directory manually).

2) The i686 rustc and the Rust lib don't download (404):
```
looking for rustc at C:\source\servo\.servo\rust\f85579d4a2c342654f9b158fafd565eb159fdb59-alt\rustc-nightly-i686-pc-windows-msvc\rustc\bin\rustc.exe
Downloading Rust compiler...
Download failed (404): Not Found - https://s3.amazonaws.com/rust-lang-ci/rustc-builds-alt/f85579d4a2c342654f9b158fafd565eb159fdb59/rustc-nightly-i686-pc-windows-msvc.tar.gz
```
This I "fixed" manually by downloading the latest nightly yesterday from rust-lang.org and placing them accordingly. Not sure if this might have cause other problems, since you might be using some specific Rust version in your build system.

3) I had http://strawberryperl.com/ installed and it tried to use it and that resulted in some error too, but after uninstalling Strawberry Perl the journey went on.

4) And this is the issue that makes me wonder whether 32 bit is supported or not:
```
error[E0512]: transmute called with types of different sizes
   --> C:\source\servo\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-webvr-0.5.0\src\api\openvr\display.rs:138:35
    |
138 |         texture.handle = unsafe { mem::transmute(layer.texture_id as u64) };
    |                                   ^^^^^^^^^^^^^^
    |
    = note: source type: u64 (64 bits)
    = note: target type: *mut std::os::raw::c_void (32 bits)

error: aborting due to previous error

error: Could not compile `rust-webvr`.
Build failed, waiting for other jobs to finish...
```

**Comment by atouchet** [comment]
https://github.com/servo/servo/issues/16820#issuecomment-300923537

**Comment by ripieces** [comment]
Thanks for your reply.
I guess that means not supported :(
