### ISSUE TITLE
Enable GitHub OAuth App Access Restrictions

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#17766]
We should enable OAuth App Access Restrictions on the servo org so that we can approve/deny requests for OAuth app access.

At my work we have applications that authenticate through GitHub OAuth, and the authorization screen automatically selects all organizations I am in, including the servo org, without any ability to opt out. Even though it is read-only, I would prefer to only grant access to the necessary organizations.

Enabling OAuth App Access Restrictions prevents the servo org from being auto selected; access must be specifically requested and approved by a servo org admin. This prevents leakage.

This is the default for new organizations (seemingly since Feb 2014).

cc @metajack @edunham @larsbergstrom @manishearth

**Comment by metajack** [comment]
I'm fine with this, however it will nuke all SSH keys (including user and deploy keys) created prior to 2014. I cannot seem to find a list of these, nor is it clear if I will be presented with a list of keys after pressing the green button.

I'd rather not lock people out of the repo with no notice, so I suggest we either figure out how much this will affect or plan to do this on a quiet Friday with pre-announcements to dev-servo.

**Comment by aneeshusa** [comment]
Deploy keys are per repo and should be visible in the repo settings, or you can write a small script to hit the API and check for them on all repos in the org. I don't think we should have any, though.

I don't think there's an easy way to view SSH keys, so I think a pre-announcement and making the change on the weekend would be prudent.

**Comment by aneeshusa** [comment]
@edunham has enabled this, thanks!
