### ISSUE TITLE
Remove `stylearc` import alias

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#17768]
Currently in the style crate we do a [`pub use servo_arc as stylearc`](https://github.com/servo/servo/blob/d746abaa9e69e6cf0ad187d2b46be661bbe03a9f/components/style/lib.rs#L142-L144).

This isn't necessary, we can simply rename all imports of `stylearc` in the style crate to use `servo_arc`. We should do that.

Ensure both `./mach build-geckolib` and `./mach build -d -p style` pass. This is a pure refactoring, there should be no need to test it.

**Comment by michael-p** [comment]
I would like to try this, sounds like a good thing to get started! :)
@highfive: assign me

**Comment by michael-p** [comment]
@Manishearth I guess I should also rename all imports in other components and hence completely eliminate `stylearc` (as [this](https://github.com/servo/servo/blob/d746abaa9e69e6cf0ad187d2b46be661bbe03a9f/components/style/lib.rs#L142-L144) comment implies)? Or just rename it inside style crate, keep the `pub use servo_arc as stylearc;` there and leave all other components unchanged? I would prefer the first option :)

**Comment by Manishearth** [comment]
Yes, rename it everywhere.

**Comment by michael-p** [comment]
Thanks!
Another question: it seems I have to re-generate `components/style/gecko/generated/structs_{debug|release}.rs`. It looks like `components/style/build_gecko.rs` does that but how do I run it properly?

**Comment by Manishearth** [comment]
Oh, right, that's not straightforward.

How about you leave the alias in place for the style crate, and refactor all other uses of `stylearc` except for those files? I'll do that part, it needs modifying firefox-side code.

**Comment by michael-p** [comment]
This should probably be re-opened until the changes to the generated code as mentioned above by @Manishearth are done.

**Comment by Manishearth** [comment]
Nah, it's fine, those changes are landing as part of a different bug.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/17818 and https://bugzilla.mozilla.org/show_bug.cgi?id=1382017 removed the Gecko use cases

https://github.com/servo/servo/pull/17822 removes the actual reexport. Thanks for your help!
