### ISSUE TITLE
style: stopping passing an Arc into RestyleDamage::compute_style_difference

### ISSUE THREAD

**Issue by heycam** [servo/servo#17795]
We used to need to pass in an `&Arc<ComputedValues>` to `RestyleDamage::compute_style_difference` so that Gecko could work with it.  Since the recent `ComputedValues` refactorings, this is no longer the case, and we could change `compute_style_difference` and various other functions leading up to it to just pass a `&ComputedValues` instead.

This can only happen once https://bugzilla.mozilla.org/show_bug.cgi?id=1380133 lands.

**Comment by shivanth** [comment]
@highfive: assign me
I'm pretty new, You'll get loads of questions on IRC via titankiller

**Comment by jdm** [comment]
This is no longer blocked; have you made any progress on this, @shivanth?

**Comment by shivanth** [comment]
Looks like I am late 😈
