### ISSUE TITLE
Float Causes Table Display Bounding Box to be Offset by the Float's Width

### ISSUE THREAD

**Issue by gyroninja** [servo/servo#17833]
When a display is set to table after a float, the text (and the table_row?) after that float's width is chopped off by the same amount of pixels as the width of the float (at least approximately).
This bug is very detrimental when browsing https://4chan.org as the first few posts are mostly chopped off.
Here is a simplified document which exhibits the behavior.
```html
<style>
  html {
    display: table;
  }
  
  .fileThumb {
    float: left;
  }

  .post {
    overflow: hidden;
  }

  .op {
    background-color: #F0ECD6;
  }

  .reply {
    background-color: #D6DAF0;
  }
</style>

<p class="op fileThumb">Fixed Width Float</p>
<p class="post reply">Text content here is chopped off on the right by the width of the float</p>
```
Example Servo
![](https://i.gyazo.com/eb863f1c6be85d2f07fe870ee9d7ec8f.png)
Example Firefox
![](https://i.gyazo.com/1e4374198927400d43e7c6c3e697d699.png)
4chan Servo (look at the first reply in the thread)
![](https://i.gyazo.com/9413f84f1f2e45da1b09637ddfbfc457.png)
4chan Firefox
![](https://i.gyazo.com/5d1ae6951daa96234f403be287958b9e.png)

**Comment by mrobinson** [comment]
This seems to be working in both layout and legacy-layout now. The block positioning of the float is still different from Firefox, but we seem to match Chrome's behavior.
