### ISSUE TITLE
Text rendering is broken on Android

### ISSUE THREAD

**Issue by MortimerGoro** [servo/servo#17851]
Hello,

Text rendering is broken on Android. It worked in a fork I created some time ago. I did a git bisect and after some long compilation steps it blames a WR update:  https://github.com/servo/servo/pull/17352 `Update WR (CPU text optimizations, image format renames)`

Some images attached:

After WR update: 
![screenshot_20170725-142452](https://user-images.githubusercontent.com/1070794/28574249-aa8364fc-714d-11e7-9ce2-967d9c47bcc9.png)

Before WR update:
![screenshot_20170725-145847](https://user-images.githubusercontent.com/1070794/28574254-ad2999d8-714d-11e7-8ba9-e2d8d108f6e5.png)

**Comment by jdm** [comment]
Text rendering has since been fixed.
