### ISSUE TITLE
servo-mac9 and servo-mac5 take 14 minutes longer to compile than other mac builders

### ISSUE THREAD

**Issue by jdm** [servo/servo#17873]
They both consistently report 37 minutes for ./mach build, while other macs like servo-mac3 report 23 minutes. This tends to push our end-to-end built times to >1 hour when these machines are selected. I sshed in and didn't see any renegade processes that have caused similar slowdowns in the past.

**Comment by jdm** [comment]
cc @edunham

**Comment by edunham** [comment]
They were i5 machines with not enough RAM and now they are i7 machines with plenty :)
