### ISSUE TITLE
Stacking context parent causes mispositioning of fixed position child

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#17870]
```html
<style>
#stackingcontext {
  position: absolute;
  top: 200px;
  left: 200px;
  z-index: 2;
}

#fixed {
  background: green;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}

</style>

<div id="stackingcontext">
  <div id="fixed"></div>
</div>
```

This fixed position child here should take up the entire viewport, but instead I see this output.
![screenshot from 2017-07-26 13-58-49](https://user-images.githubusercontent.com/13536/28619876-d854aef0-720a-11e7-80e9-5d1b70e31bd8.png)

**Comment by jfernandezcorral** [comment]
In chrome it,s OK
The next is rendered ok too, with an stacking context paralell an z-index greater

`<style>
#stackingcontext {
  position: absolute;
  top: 200px;
  left: 200px;
  z-index: 2;
  width: 200px;
  height: 200px;
}
#otrostackingcontext {
  position: absolute;
  top: 100px;
  left: 100px;
  z-index: 3;
  width: 200px;
  height: 200px;
}
#fixed {
  background: green;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}

</style>
<div id="otrostackingcontext"></div>
<div id="stackingcontext">
  <div id="fixed"></div>
</div>`


![captura de pantalla 2017-08-19 a las 20 02 14](https://user-images.githubusercontent.com/15350192/29489122-7ea40190-8519-11e7-8ec9-b6eda09df9a5.png)

**Comment by jdm** [comment]
This is fixed in layout 2020:
<img width="1029" alt="Screenshot 2024-10-05 at 10 52 13 PM" src="https://github.com/user-attachments/assets/98cfaaf2-38cd-43e3-8fcc-2f930a9dd0fb">
