### ISSUE TITLE
Intermittent failure in /css-backgrounds-3_dev/html4/attachment-local-clipping-image-1.htm, css-backgrounds-3_dev/html4/attachment-local-clipping-image-2.htm, /css-backgrounds-3_dev/html4/attachment-local-clipping-image-4.htm, /css-backgrounds-3_dev/html4/attachment-local-positioning-5.htm, /css-backgrounds-3_dev/html4/attachment-local-clipping-image-3.htm, /css-backgrounds-3_dev/html4/attachment-local-clipping-image-5.htm, /css-backgrounds-3_dev/html4/attachment-local-positioning-2.htm, /css-backgrounds-3_dev/html4/attachment-local-clipping-image-6.htm 

### ISSUE THREAD

**Issue by jdm** [servo/servo#17885]
```
  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/attachment-local-clipping-image-1.htm
  └   → /css-backgrounds-3_dev/html4/attachment-local-clipping-image-1.htm fbaa4af21769c6bf524c893f2d13b4bf1109fb7e
/css-backgrounds-3_dev/html4/reference/attachment-local-clipping-image-1-ref.htm 6be295095ba954f5d6d46fad5aa728042b0f865f
Testing fbaa4af21769c6bf524c893f2d13b4bf1109fb7e == 6be295095ba954f5d6d46fad5aa728042b0f865f
```

**Comment by jdm** [comment]
Actual:
<img width="334" alt="screen shot 2017-07-26 at 8 54 04 pm" src="https://user-images.githubusercontent.com/27658/28649685-9a39c3be-7244-11e7-9d6a-5d24743f19a2.png">

Reference:
<img width="335" alt="screen shot 2017-07-26 at 8 54 29 pm" src="https://user-images.githubusercontent.com/27658/28649691-a3f652be-7244-11e7-8dee-501f8d95d32c.png">

The text moved down a line-height from the reference.

**Comment by jdm** [comment]
The same text positioning issue was observed in /css-backgrounds-3_dev/html4/attachment-local-positioning-5.htm in #17903.

**Comment by upsuper** [comment]
Maybe http://build.servo.org/builders/linux-rel-css/builds/5244 appears in #17922 is the same reason as well?

**Comment by jdm** [comment]
Yes.

**Comment by upsuper** [comment]
Suspect the same failure in http://build.servo.org/builders/linux-rel-css/builds/5368 for #18033.
