### ISSUE TITLE
Browser.html sidebar shadow has one pixel wide overly light column

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17921]
The shadow cast by the Browser.html sidebar has a one pixel wide column that is lighter than the rest of the shadow. This does not appear when the Browser.html interface is loaded in Firefox.

Example images:

The column in Servo highlighted in red (view in full size to see it more clearly):

![Servo](https://i.imgur.com/2TlFy2x.png)

The Browser.html interface in Firefox without the shadow issue:

![Firefox](https://i.imgur.com/OltnZZG.png)

Tested in Windows 10.

**Comment by jdm** [comment]
It would be great to find a minimal reproduction for this by extracting the layout from the browser.html interface.

**Comment by atouchet** [comment]
I think this demonstrates the issue:

`<!DOCTYPE html>
<html>
<head>
<style> 
div {
	background-color: rgb(39, 40, 34); 
	height: 100%; 
	position: absolute; 
	right: 0px; 
	top: 0px; 
	width: 320px; 
	box-sizing: border-box; 
	z-index: 2; 
	overflow: hidden; 
	transform: translateX(0px); 
	box-shadow: -50px 0px 80px rgba(0, 0, 0, 0.5); 
	padding-left: 16px; 
	padding-right: 16px;
}
</style>
</head>
<body>

<div></div>

</body>
</html>`

**Comment by atouchet** [comment]
This appears to be fixed now.
