### ISSUE TITLE
Issues with duckduckgo.com/feeeback

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17941]
Page tested: https://duckduckgo.com/feedback

The guide boxes on the page have an excessive amount of white space on the left side which isn't supposed to be there and this causes the text to often be bumped to two lines. When moving the mouse over the text a shadow is also rendered inside the box. Also the icons and arrows are supposed to change colour when the mouse is moved over the box but this doesn't happen in Servo unless the page has been loaded multiple times.

Example image (Servo on top, Firefox on bottom):

![duckduckgo.com/feeeback](https://i.imgur.com/WvQAPZF.png)

Tested in Windows 10.

Edit: The colour change issue appears to be the last problem left.

**Comment by BrunoBernardino** [comment]
I can confirm the [latest `master`](https://github.com/servo/servo/commit/a6369149dc5344b2b80a12fca1c43cf99c94fdc9) still has this issue, even on macOS 10.12.6 (16G29) and not on FirefoxNightly 57.0a1 (2017-08-04) (I'm not sure if it's running servo already).

This is the result for `./mach run https://duckduckgo.com/feedback`:

![duckduckgo-feedback-servo](https://user-images.githubusercontent.com/1239616/28999060-2d0128aa-7a32-11e7-8391-4ae8008d26a9.gif)

Compared with a regular Nightly Private window:

![duckduckgo-feedback-firefox](https://user-images.githubusercontent.com/1239616/28999079-7d8dddc2-7a32-11e7-8a69-de57deb0c039.gif)

**Comment by atouchet** [comment]
Scrolling on this page no longer works.

**Comment by atouchet** [comment]
This is mostly fixed in the latest nightly build. The spacing and shadow problems are gone but the colour and scrolling issues are still present.

**Comment by atouchet** [comment]
There are issues with the row shadow animations in the latest nightly build.
