### ISSUE TITLE
Happy face is missing

### ISSUE THREAD

**Issue by jdm** [servo/servo#17963]
https://qsurvey.mozilla.com/s3/FirefoxInput/#sad

**Comment by jdm** [comment]
This may be an effect of this error from the terminal:
`ERROR:script::dom::bindings::error: Error at https://www.surveygizmo.com/2017.08.02.01/runtimejs/dist/survey/js/survey.js:114:4069 e.fillText is not a function`

**Comment by BrunoBernardino** [comment]
I've confirmed that is coming from this line: https://github.com/Valve/fingerprintjs/blob/master/fingerprint.js#L283 so this is related to the `canvas` implementation in servo, I believe. I'm still investigating further, but it's the first time I'm looking at servo's source code, so if someone has thoughts or pointers, it'll probably help 😄

**Comment by jdm** [comment]
Servo does not implement the canvas text APIs yet: #11681.

**Comment by atouchet** [comment]
Was this supposed to have been fixed in #18020? I am still able to reproduce the issue.

**Comment by BrunoBernardino** [comment]
It was not @atouchet , it's only not throwing a JS exception anymore with that.

**Comment by atouchet** [comment]
The happy face appears to show up now:

![Happy face](https://i.imgur.com/pG3yqGK.png)

**Comment by jdm** [comment]
Delightful!
