### ISSUE TITLE
Minimizing and then restoring Servo window scrolls back to top of page

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17978]
Steps to reproduce.

1. Load web page that has vertical scrolling.
2. Scroll to bottom of page.
3. Minimize Servo window.
4. Restore Servo window.
5. Servo is now back at the top of the page.

Tested in Windows 10.

**Comment by zachlute** [comment]
I was not able to reproduce this with latest on Windows 10.

**Comment by atouchet** [comment]
I just re-tested this in the latest nightly build and was able to reproduce the issue. I should maybe also note that I'm using Servo with Browser.html if that makes a difference.

**Comment by BojanKogoj** [comment]
I can confirm this is happening, latest build on Windows 10

![mealyinfinitedunlin-small](https://user-images.githubusercontent.com/634075/29240061-faec9f8a-7f5d-11e7-8ed3-bae5c805217b.gif)

**Comment by atouchet** [comment]
This appears to be fixed now.

**Comment by atouchet** [comment]
And now it's a problem again.

**Comment by atouchet** [comment]
I bisected this latest regression and it first occurred in the 2017-09-15T01:23:23Z-Servo nightly build.

**Comment by atouchet** [comment]
This is no longer an issue.
