### ISSUE TITLE
Dedicated worker is not closed when associated document is destroyed

### ISSUE THREAD

**Issue by jdm** [servo/servo#17977]
```html
<iframe src="http://localhost:8000/bar2.html" onload="this.remove()"></iframe>
```
```html
<script>
var w = new Worker('work.js');
</script>
```
```js
setInterval(function() {
  console.log('hi');
}, 500);
```
This shows an empty page (since the iframe is removed), but the worker continues logging to stdout.

**Comment by jdm** [comment]
I propose to solve this the following way:
* create a `struct AutoCloseWorker(Arc<AtomicBool>)` type in globalscope.rs
* add a vector of AutoCloseWorker values as a member to GlobalScope
* when a worker is constructed (Worker::Constructor in worker.rs), invoke a method on GlobalScope that pushes a clone of `closing` into the vector
* implement a destructor for AutoCloseWorker (`impl Drop for AutoCloseWorker`) that sets the boolean to true

Together, these steps should cause a chain reaction of closing all outstanding related workers when a page (or another worker) is closed.

**Comment by nupurbaghel** [comment]
@jdm: I would like to work on this issue.

**Comment by nupurbaghel** [comment]
Implementing step 3 ( push a clone of closing into the vector ) requires vector to be mutable. So, I was trying to use Cell<Vec<AutoCloseWorker>> as a member of Global Scope. But the Cell's get( ) method requires Copy( ) to be implemented which is probably not present for the Arc<AtomicBool>. How should I proceed ?
