### ISSUE TITLE
Multiple differences between Firefox and Servo on the homepage of http://www.luzern.co/

### ISSUE THREAD

**Issue by hgallagher1993** [servo/servo#17996]
1) Block of Text is top left instead of center left and overwrites the name Luzern. [Firefox](https://i.imgur.com/jZDNsMg.png). . .[Servo](https://i.imgur.com/bS3Y1pp.png)

2) Scrolling doesn't work. When you scroll the mouse wheel down one it should bring you down 1 page. The 4 little circles to the right of the screen are the different pages and to go through them you have to manually click them.

3) Social media images show as empty squares in the footer. [Firefox](https://i.imgur.com/STwLRl5.png). . .[Servo](https://i.imgur.com/fY1Lfzk.png)

4) In the footer as well the email address and subscribe boxes don't align. [Firefox](https://i.imgur.com/Rv4ettD.png). . .[Servo](https://imgur.com/a/i4jG8)

**Comment by jdm** [comment]
It would be really helpful to reduce each of this problems into an isolated, minimal testcase that demonstrates the issue!

**Comment by dralley** [comment]
Page seems to work perfectly now.

**Comment by hgallagher1993** [comment]
Sounds good! Don't have Servo on my laptop anymore to check myself but I'll take your word for it 😄
