### ISSUE TITLE
Move `Percentage` value structs to mod.rs

### ISSUE THREAD

**Issue by canaltinova** [servo/servo#18001]
Currently `Percentage` structs are in `components/style/values/{specified,computed}/length.rs`. They have been put to this file probably because many length values are using it. But they are not related to length by themselves. We should move them to `components/style/values/{specified,computed}/mod.rs` instead and make sure all `./mach build -d`, `./mach build-geckolib` and `./mach test-unit -p style` compiles.

**Comment by DarkDrek** [comment]
I would like to do that so @highfive: assign me
