### ISSUE TITLE
Make it possible to destroy a browsing context from the embedder

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#18006]
The same way we have `NewBrowser`, we need `DestroyBrowser`. Follow-up of #17425.

**Comment by paulrouget** [comment]
@cbrewster @asajeffrey beside calling `Constellation::close_browsing_context`, what else do we need to do? What about pending changes?

**Comment by cbrewster** [comment]
AFAIK that's all you would need to do. `Constellation::close_browsing_context` will clean up any pending changes for that browsing context.
