### ISSUE TITLE
Style computed value of a URL is returning the relative URL for listStyle and listStyleImage properties

### ISSUE THREAD

**Issue by brainlessdeveloper** [servo/servo#18015]
This is a followup of [Style computed value of a URL is returning the relative URL](https://github.com/servo/servo/issues/17625).

See relevant discussion [here](https://github.com/servo/servo/pull/17812#issuecomment-318905247).

Faulty code is [in list.mako.rs](https://github.com/servo/servo/blob/10c3e2f3ac781905b43b3529253ba1bc9926d9e8/components/style/properties/longhand/list.mako.rs#L102). The implementations here use `ComputedValueAsSpecified` but should drop it in Servo and use it only for Gecko, following more or less what's been done [here](https://github.com/servo/servo/pull/17812/files) to implementations for other properties.

Print of unexpected failures in `get-computed-style-for-url.html`:
```
getComputedStyle(elem) for url() listStyleImage uses the resolved URL and elem.style uses the original URL                                                                                   
----------------------------------------------------------------------------------------------------------                                                                                   
Expected PASS, got FAIL                                                                                                                                                                      
assert_equals: expected "url(\"http://web-platform.test:8000/_mozilla/css/test.jpg\")" but got "url(\"test.jpg\")"                                                                           
testUrlsForProperty/<@http://web-platform.test:8000/_mozilla/css/get-computed-style-for-url.html:32:7                                                                                        
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20                                                                                                           
test@http://web-platform.test:8000/resources/testharness.js:497:9                                                                                                                            
testUrlsForProperty@http://web-platform.test:8000/_mozilla/css/get-computed-style-for-url.html:25:5                                                                                          
@http://web-platform.test:8000/_mozilla/css/get-computed-style-for-url.html:46:3                                                                                                             

getComputedStyle(elem) for url() listStyle uses the resolved URL and elem.style uses the original URL
-----------------------------------------------------------------------------------------------------
Expected PASS, got FAIL
assert_equals: expected "url(\"http://web-platform.test:8000/_mozilla/css/test.jpg\")" but got "url(\"test.jpg\")"
testUrlsForProperty/<@http://web-platform.test:8000/_mozilla/css/get-computed-style-for-url.html:32:7
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
test@http://web-platform.test:8000/resources/testharness.js:497:9
testUrlsForProperty@http://web-platform.test:8000/_mozilla/css/get-computed-style-for-url.html:25:5
@http://web-platform.test:8000/_mozilla/css/get-computed-style-for-url.html:47:3
```

**Comment by brainlessdeveloper** [comment]
@nox I'm trying to fix this after some months (again haha), here's my progress:

https://github.com/brainlessdeveloper/servo/commit/033a171b7240060a2ddcc41780a3748b07dd2f09

I'm stuck with the type errors because I don't completely understand where they come from and how I should go about fixing them. I need some pointers in the right directions :(

Here's a [pastebin](https://pastebin.com/BKuE6SJS) of the compiler messages if you'd like to check them out.

**Comment by jdm** [comment]
I asked on IRC, and nox gave this helpful answer:
```
09:16 <nox> jdm: The issue is in their code,
09:16 <nox> jdm: they try to derive TCV for specified::ListStyleImage,
09:16 <nox> which contains a SpecifiedUrl,
09:16 <nox> which is supposed to compute to ComputedUrl,
09:17 <nox> but #[derive(TCV)] on a non-generic type derives an impl that computes to Self.
09:17 <nox> jdm: ListStyleImage needs to become ListStyleImage<Url>,
09:17 <jdm> yeah, my question was about the intended behaviour of TCV, so that's the piece I was missing
09:17 <nox> and while at it they should remove the use of Either and just define their own enum.
```
Does that help? There should be a single ListStyleImage type that is generic over the inner value, instead of two separate ones.

**Comment by brainlessdeveloper** [comment]
Here's my progress on the issue: https://github.com/brainlessdeveloper/servo/commit/25751832acbad79e7018a637e2f2304cbe78c6fc

I'm struggling with the compiler errors arising from a missing `Parse` implementation for some of the types.

**Comment by brainlessdeveloper** [comment]
When I have more time I'll try to figure out a more detailed report.

**Comment by brainlessdeveloper** [comment]
The implementation of `Parse` for `ListStyleImageUrlOrNone` won't compile now because `ListStyleImage` is now generic. AFAIK it doesn't make sense to have `Parse` for a computed `ListStyleImage`, only for a specified one, right?

I don't know how to continue with this. Here's a [pastebin](https://pastebin.com/HRWKe7XJ) of the compiler errors.

**Comment by jdm** [comment]
I recommend moving the Parse implementation to specified/list.rs and only implementing for the specified type in particular, rather than making it a generic implementation. This should allow relaxing the `:Parse` constrain on the generic struct, which should address most/all of the compile errors.
