### ISSUE TITLE
DuckDuckGo magnifying glass icon does not change colour when mouse is moved over

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18039]
Page tested: https://duckduckgo.com/

When moving the cursor over the magnifying glass icon it should change from grey to white. However this does not happen in Servo. It does change colour when the button is clicked however. I have also run into instances where after changing colour when being clicked that it doesn't change back to grey.

This issue also only occurs with the main DuckDuckGo site and not the HTML version.

Image (Firefox top, Servo bottom):

![DuckDuckGo icons](https://i.imgur.com/fnHlbSF.png)

**Comment by atouchet** [comment]
The site design has changed and this no longer appears.

**Comment by LingMan** [comment]
The old, green design can still be accessed on the Wayback Machine: https://web.archive.org/web/20160708083505/https://duckduckgo.com/

The magnifying glass there changes color correctly with Servo 0.0.3.

However, the current design also has a magnifying glass that should change color on the search result page. That one still stays dark. Opened https://github.com/servo/servo/issues/41427 for that.
