### ISSUE TITLE
Unfork rust-xcb

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#18044]
At the moment, upgrading Rust in Servo is blocked on https://github.com/rtbo/rust-xcb/issues/40 because the compiler started rejected code that is used to accept (though I arguably shouldn’t have accepted it in the first place): https://github.com/rust-lang/rust/issues/43567. However, the maintainer seems unresponsive at the moment. To unblock I’m going to fork this crate and use it with [`[patch]` in `Cargo.toml`](http://doc.crates.io/specifying-dependencies.html#overriding-dependencies). Hopefully this is temporary.

This is a tracking issue for eventually getting a fix upstream and revert to using that crate from crates.io.

**Comment by SimonSapin** [comment]
https://github.com/rtbo/rust-xcb/pull/41 has the start of a fix but is incomplete. I fiddled with the code generation script a bit but didn’t manage to get it to generate something that compiles on Nightly.

**Comment by SimonSapin** [comment]
The fork is at https://github.com/servo/rust-xcb/compare/v0.7.6...servo_issue18044_do_not_remove

**Comment by jdm** [comment]
It is no longer in use.

**Comment by SimonSapin** [comment]
Oops, I forgot to close this. Thanks.

@ rtbo responded with a proper fix to https://github.com/rtbo/rust-xcb/issues/40 and published version 0.7.7 before #18046 landed, so we ended up never landing the use of this fork.
