### ISSUE TITLE
GitHub detects Servo as outdated version of Firefox

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18057]
GitHub when loaded with Servo has recently started showing warnings that it detects it as an outdated version of Firefox. Also as far as I can tell they are starting to limit site functionality for old browsers where certain things such as being able to sort PRs and issues no longer works.

![GitHub](https://i.imgur.com/XBUXuAJ.png)

Tested in Windows 10.

**Comment by atouchet** [comment]
I tried making a potential fix for this in #18040.

**Comment by KiChjang** [comment]
I made a comment on the PR [here](https://github.com/servo/servo/pull/18040#issuecomment-322064929) stating that this does not look like a Servo bug, but rather a bug at GH's user agent detection algorithm.

**Comment by emilio** [comment]
Well, if we choose to go around with FF's user agent (which I think it's a reasonable choice), then I don't know how they could ever guess we're Servo.

**Comment by emilio** [comment]
So this is our problem, I agree with @jdm there :)

**Comment by atouchet** [comment]
This was fixed in #18040.
