### ISSUE TITLE
Website page elements can appear on top of browser interface

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18063]
Page with issue: https://github.com/

Certain page elements appear above the browser interface.

![GitHub](https://i.imgur.com/NmKmIKm.png)

See the "or" highlighted in red in "Sign in or Sign up". You may need to zoom in to see the problem more clearly.

Tested in Windows 10.

**Comment by atouchet** [comment]
Is there a way to scroll to a precise location in Servo? Now that the outdated Firefox warning is gone I can no longer scroll to the same vertical position on the page that shows the issue.

**Comment by jdm** [comment]
If you run Servo with the devtools server enabled, you could use JS scrolling APIs from the JS console.

**Comment by atouchet** [comment]
I don't think this is still relevant with Browser.html removed.
