### ISSUE TITLE
Screen width and height are undefined

### ISSUE THREAD

**Issue by BojanKogoj** [servo/servo#18062]
There is an issue with screen width and height, first noticed on [whoishostingthis.com/tools/user-agent/](http://www.whoishostingthis.com/tools/user-agent/), screenshot (left Servo, right Firefox 55):

![screen-size-issue2](https://user-images.githubusercontent.com/634075/29250823-af51cf7c-8049-11e7-97b9-90addab756e0.PNG)

I tried to reproduce using a test script and got the following result (left Servo, right Firefox 55):

![screen-size-issue](https://user-images.githubusercontent.com/634075/29250807-55a4c75e-8049-11e7-8738-3de62a2278a2.PNG)

Test script used to reproduce:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Screen size test</title>
        <style>
            html {
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
            }
            .container {
                width: 600px;
                margin: auto auto;
            }
            h1 {
                margin: 50px 0;
                font-size: 30px;
                text-align: center
            }
            dt {
                width: 260px;
                float: left;
                font-weight: bold;
            }
            dd {
                margin-bottom: 10px;
                margin-left: 280px;
                clear: right;
                height: 20px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Screen size test</h1>
            <dl id="values">
            </dl>
            <strong id="error">If you can see this there is an issue and values are not properly loaded</strong>
        </div>
        <script>
            function setElement(name, value) {
                var dt = document.createElement('dt');
                dt.textContent = name;
                var dd = document.createElement('dd');
                dd.textContent = value;

                var outer = document.getElementById('values');
                outer.appendChild(dt);
                outer.appendChild(dd);
            }
            window.onload = function() {
                setElement('window.screen.availWidth', window.screen.availWidth);
                setElement('window.screen.availHeight', window.screen.availHeight);
                setElement('window.screen.width', window.screen.width);
                setElement('window.screen.height', window.screen.height);
                setElement('window.innerWidth', window.innerWidth);
                setElement('window.innerHeight', window.innerHeight);
                setElement('window.outerWidth', window.outerWidth);
                setElement('window.outerHeight', window.outerHeight);
                setElement('screen.colorDepth', screen.colorDepth);
                setElement('screen.pixelDepth', screen.pixelDepth);

                // Remove error message
                var err = document.getElementById('error');
                err.parentElement.removeChild(err);
            }
        </script>
    </body>
</html>

```

Tested with Servo developer preview on Windows 10.

**Comment by jdm** [comment]
Yes, those attributes are missing from our implementation of the Screen interface:
Code: https://dxr.mozilla.org/servo/rev/4d10d39e8fe841c5fe2ac58da2daaa13c10c140e/components/script/dom/webidls/Screen.webidl#8-11
Specification: https://drafts.csswg.org/cssom-view/#dom-screen-availwidth

**Comment by jdm** [comment]
The important part here is getting the screen dimensions. Glutin has a [MonitorId type](http://doc.servo.org/glutin/struct.MonitorId.html) that has a `get_dimensions` method; we can use the `Window::client_window` method as a model here (components/script/dom/window.rs) - we need to send a message to the constellation, which will forward the message to the compositor, which can call [glutin::get_primary_monitor](http://doc.servo.org/glutin/fn.get_primary_monitor.html) and return the appropriate information.

**Comment by shinglyu** [comment]
I guess I can give this a go while I wait my other bugs to be unblocked. 

Do we have to worry about other embedders? Is there a good point to abstract away glutin?

**Comment by paulrouget** [comment]
@shinglyu using a `WindowMethod` plus a glutin specific implementation in `ports` is totally fine.

**Comment by shinglyu** [comment]
@paulrouget Ah I see, so the `IOCompositor.window` can have different implementation of `WindowMethods`.

**Comment by paulrouget** [comment]
@shinglyu yep. All located in `/ports/`.

**Comment by shinglyu** [comment]
I wrote a working prototype for `screen.width` and `height` using `glutin::get_primary_monitor().get_dimensions()`. But I'm not sure how to get the `availHeight/availWidth`. Is there API for getting the available height/width? Or maybe we just implement `screen.height/width` for now?

**Comment by paulrouget** [comment]
As far as I know, winit/glutin doesn't provide the info for availableHeight/Width.
Maybe fallback to the values of height/width for now?

**Comment by shinglyu** [comment]
One thing that confuses me is that there are tests like `/cssom-view-1_dev/xhtml1/window-screen-height-mutation-throws.xht` asserting that mutating `window.screen.height` should throw an exception. But I can't reproduce that on Chrome and Firefox. Is that an outdated test?
