### ISSUE TITLE
Intermittent crash in /webgl/conformance-1.0.3/conformance/glsl/constructors/glsl-construct-bvec2.html

### ISSUE THREAD

**Issue by hiikezoe** [servo/servo#18080]
> {"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webgl/conformance-1.0.3/conformance/glsl/constructors/glsl-construct-bvec2.html", "line": 289989, "action": "test_result", "expected": "ERROR"}

**Comment by jdm** [comment]
This is #17168.
