### ISSUE TITLE
Clicking Browser.html interface buttons after loading a website causes Servo to become unresponsive

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18098]
Steps to reproduce:

1. Load a website in Servo using Browser.html.
2. Press the new site or sidebar button.
3. Servo becomes unresponsive and clicking on anything else no longer works. Scrolling still appears to work however.

This is a new regression as I did not have this problem in previous nightly builds. Tested in Windows 10.

**Comment by atouchet** [comment]
As stated in #18141 this issue apparently occurs in other operating systems as well.

**Comment by paulrouget** [comment]
I can reproduce.

Not the same issue as #18101, but could still be cause by #17425.

**Comment by atouchet** [comment]
@jdm is there any process for bisecting which PR caused a regression in Servo or do you just build each version and test them all manually? Are there downloads for individual PR builds available anywhere aside from the nightly builds?

**Comment by jdm** [comment]
There are no historical nightly downloads available as far as I am aware.

**Comment by atouchet** [comment]
I've noticed that clicking the new tab button after loading a page in Browser.html now doesn't change the title bar at all. For example before and after loading DuckDuckGo:

![Browser.html](https://i.imgur.com/YcWcgyy.png)

![Browser.html](https://i.imgur.com/MhpYk7B.png)

"DuckDuckGo - Servo" remains the title even after reloading the home screen. Is this part of the issue?

**Comment by atouchet** [comment]
2017-08-16 was the first nightly build with this issue.

**Comment by atouchet** [comment]
This is no longer relevant as Browser.html was removed.
