### ISSUE TITLE
Link hitboxes do not move when scrolling page

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18101]
Steps to reproduce:

1. Load web page that scrolls vertically and has clickable links near the bottom of the page.
2. Scroll down the page.
3. Try to click a link.
4. The link doesn't work properly.

I believe this is a recent regression as I do not recall running into this issue previously. Tested in Windows 10.

**Comment by jdm** [comment]
I can reproduce this with `./mach run -b` and visiting http://news.ycombinator.org. I cannot reproduce it with `./mach run http://news.ycombinator.org`, so it's specifically related to hit testing inside of an iframe.

**Comment by jdm** [comment]
This is a regression from #17425. cc @paulrouget

**Comment by paulrouget** [comment]
If it's because of #17425, I would bet on a Browser API breakage.

I'll look at it.

**Comment by paulrouget** [comment]
Really looks like a hittest issue though…

**Comment by atouchet** [comment]
@paulrouget do you have any idea if your PR could have also caused #18098? That issue appeared right around the same time.

**Comment by paulrouget** [comment]
@atouchet I don't know. I'll investigate later.

**Comment by paulrouget** [comment]
The hittest issue only happens with mozbrowser ifames.

**Comment by paulrouget** [comment]
In these tests:
- 
 https://github.com/servo/servo/blob/92176d1152257e57e81dcd9204d59348ce9ff519/components/constellation/constellation.rs#L2311
- https://github.com/servo/servo/blob/92176d1152257e57e81dcd9204d59348ce9ff519/components/constellation/constellation.rs#L2473

we need to resolve the actual top level browsing context.
