### ISSUE TITLE
Add `buffered` flag to PerformanceObserverInit dictionary

### ISSUE THREAD

**Issue by ferjm** [servo/servo#18108]
The [PerformanceObserver.observe](https://w3c.github.io/performance-timeline/#dom-performanceobserver-observe()) method gets a [PerformanceObserverInit](https://w3c.github.io/performance-timeline/#dom-performanceobserverinit) parameter that should include a [flag](https://w3c.github.io/performance-timeline/#dom-performanceobserverinit-buffered) indicating if the observer should consume previously buffered performance entries.

Spec: https://w3c.github.io/performance-timeline/#dom-performanceobserverinit-buffered

This depends on https://github.com/servo/servo/pull/18028

**Comment by jdm** [comment]
Code: `components/script/dom/webidls/PerformanceObserver.webidl`

**Comment by rtbo** [comment]
@highfive: assign me
