### ISSUE TITLE
Issue with Double paste on Windows 10 

### ISSUE THREAD

**Issue by Ygg01** [servo/servo#18130]
Steps to reproduce:
* Copy link e.g. `https://www.mozilla.org/`
* Paste in Servo search bar
---
Expected: https://www.mozilla.org/
Got: https://www.mozilla.org/https://www.mozilla.org/
[Link to image](https://i.imgur.com/1RHOsyQ.png)

Environment: Windows 10, browser was from https://download.servo.org with today's date. Unsure if bug exists on other platforms.

NOTE: Also Ctrl-z leaves a token in URL field.

**Comment by atouchet** [comment]
I have also run into this problem. I wrote a bit about it here: https://github.com/servo/servo/issues/16459#issuecomment-305673907. #17413 solved some of my issues with copying and pasting in Servo but it did not solve the double pasting URL problem. I am also using Windows 10.

**Comment by atouchet** [comment]
#17146 may be related to this as well.

**Comment by atouchet** [comment]
This is still happening.
