### ISSUE TITLE
nightly build button issue

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#18141]
I have tried official nightly build on windows 10, ubuntu 17.04 and MacOS10.12. And find button issues.
On Windows,  press new tab button after entering a page, and then the app crash. Some times button even not work at the beginning.
On Ubuntu, press new tab button after entering a page, and then the app crash, too.
On MacOS, buttons do not work anyway.

**Comment by atouchet** [comment]
Is this the same problem as #18098?

**Comment by tigercosmos** [comment]
@atouchet  Yes, almost the same, and not only on Windows 10.
