### ISSUE TITLE
Automatically verify that derive() lists are alphabetically ordered

### ISSUE THREAD

**Issue by jdm** [servo/servo#18172]
Rust code that looks like `#[derive(Copy,Debug, ComputeSquaredDistance)]` should be reported as a style violation. The correct ordering is `#[derive(ComputeSquaredDistance, Copy, Debug)]`.

Code: `python/tidy/servo_tidy/tidy.py`
Tests: `python/tidy/servo_tidy_tests/rust_tidy.rs`, `python/tidy/servo_tidy_tests/test_tidy.rs`. Run the tests with `./mach test-tidy --self`.

**Comment by davidcl** [comment]
@highfive: assign me (yet another new contributor)
