### ISSUE TITLE
Use `Filter buffer by name and type` algorithm implementation for all performance entry list getters

### ISSUE THREAD

**Issue by ferjm** [servo/servo#18186]
#18176 introduces the implementation of the [Filter buffer by name and type](https://w3c.github.io/performance-timeline/#filter-buffer-by-name-and-type) algorithm. According to the [spec](https://w3c.github.io/performance-timeline), this algorithm should be use for:
* [Performance.getEntries](https://w3c.github.io/performance-timeline/#getentries()-method)
* [Performance.getEntriesByType](https://w3c.github.io/performance-timeline/#getentriesbytype()-method)
* [Performance.getEntriesByName](https://w3c.github.io/performance-timeline/#getentriesbyname()-method)
* [PerformanceObserver.getEntries](https://w3c.github.io/performance-timeline/#getentries()-method-0)
* [PerformanceObserver.getEntriesByType](https://w3c.github.io/performance-timeline/#getentriesbytype()-method-0)
* [PerformanceObserver.getEntriesByName](https://w3c.github.io/performance-timeline/#getentriesbyname()-method-0)

Rigth now, the implementation for these methods is a bit more naive, so we should probably remove it and update the callers to use the [new implementation](https://github.com/servo/servo/pull/18176/files#diff-f0f83a3426dbfdaa9799c211fe72847bR56). The existing methods to be removed are:

* [get_entries](https://github.com/servo/servo/blob/master/components/script/dom/performance.rs#L37)
* [get_entries_by_type](https://github.com/servo/servo/blob/master/components/script/dom/performance.rs#L41)
* [get_entries_by_name](https://github.com/servo/servo/blob/master/components/script/dom/performance.rs#L47)

**Comment by rlustin** [comment]
@highfive: assign me
