### ISSUE TITLE
Intermittent timeout in /_mozilla/mozilla/paint_timing.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#18219]
```
  ▶ TIMEOUT [expected OK] /_mozilla/mozilla/paint_timing.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 17.2.0-devel

  ▶ Unexpected subtest result in /_mozilla/mozilla/paint_timing.html:
  └ NOTRUN [expected PASS] Performance entries observer
```
cc @ferjm

**Comment by ferjm** [comment]
Ugh...I'll investigate why it's timing out.

**Comment by ferjm** [comment]
It seems that this is still an issue https://github.com/servo/servo/pull/18280#issuecomment-325539612

**Comment by ferjm** [comment]
I think this is no longer an intermittent.

**Comment by jdm** [comment]
http://build.servo.org/intermittent-failure-tracker/search?filename=paint_timing.html&start=&end=&isQuery=true&defaultStart=19000101&defaultEnd=21000101 shows that it occurred as recently as Jan 14. Has something changed since then?

**Comment by jdm** [comment]
Nevermind, all of the failures since Jan 8 have been misclassified due to other problems in the PRs. There were no failures after Dec 6.
