### ISSUE TITLE
Prevent reentrancy in TreeWalker::accept_node and NodeIterator::accept_node

### ISSUE THREAD

**Issue by jdm** [servo/servo#18218]
accept_node implements the [filter](https://dom.spec.whatwg.org/#concept-node-filter) algorithm from the specification, but that algorithm has been updated since it was first written. We need to add an [active flag](https://dom.spec.whatwg.org/#concept-traversal-active) to both TreeWalker and NodeIterator and update it appropriately according to the specification.

Code: `components/script/dom/nodeiterator.rs`, `components/script/dom/treewalker.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/dom/traversal`

**Comment by CYBAI** [comment]
@highfive: assign me
