### ISSUE TITLE
Rust compiler download error on AArch64 Linux

### ISSUE THREAD

**Issue by cosmo0920** [servo/servo#18227]
Currently, mach cannot download rust compiler for aarch64 Linux.

### Environment

* Hardware: Jetson TX2
* OS: Ubuntu 16.04.3 LTS  aarch64

### Current problem

```log
./mach build --dev
looking for rustc at /home/nvidia/GitHub/servo/.servo/rust/13d94d5fa8129a34f5c77a1bcd76983f5aed2434-alt/rustc-nightly-aarch64-unknown-linux-gnu/rustc/bin/rustc
Downloading Rust compiler...
Download failed (404): Not Found - https://s3.amazonaws.com/rust-lang-ci/rustc-builds-alt/13d94d5fa8129a34f5c77a1bcd76983f5aed2434/rustc-nightly-aarch64-unknown-linux-gnu.tar.gz
```
### Expected

Rust compiler should be downloaded with mach on AArch64 Linux system.

**Comment by jdm** [comment]
[This code](https://github.com/servo/servo/blob/d7f7d550ab2f0f0edbcc36dab510701f21a25f7a/python/servo/command_base.py#L263-L266) tried to decide if the build is happening on a platform which has a rustc binary provided that does not include llvm assertions (`-alt`). The check needs to include non x86_64 architectures as well now, I guess.

**Comment by SimonSapin** [comment]
I think that code always had this problem. It should check full "triples".

@cosmo0920 In the meantime, you can copy `servobuild.example` to `.servobuild` and change in the latter `#llvm-assertions = false` to `llvm-assertions = true`

**Comment by cosmo0920** [comment]
> you can copy servobuild.example to .servobuild and change in the latter #llvm-assertions = false to llvm-assertions = true

Thanks for your suggestion.
I'll try this later.

**Comment by cosmo0920** [comment]
I've confirmed that downloading Rust compiler works when `llvm-assertions = true` is specified in `.servobuild`.
