### ISSUE TITLE
Blinking octocat

### ISSUE THREAD

**Issue by kpp** [servo/servo#18249]
Run `./servo http://github.com/404`, move mouse arrow over the octocat scene and you will see how it is badly rendered:

![servo](https://user-images.githubusercontent.com/467709/29737901-6b53e992-8a1f-11e7-969a-e69fb8fd3932.png)
![servo2](https://user-images.githubusercontent.com/467709/29737902-6b55427e-8a1f-11e7-96c0-618803e6b604.png)
![servo3](https://user-images.githubusercontent.com/467709/29737903-6b56d6c0-8a1f-11e7-9b76-1f86c40c980b.png)

**Comment by krk** [comment]
Layout is still wrong in a different way with 54f54d194d.

![image](https://user-images.githubusercontent.com/1447853/56642097-03a81800-6677-11e9-9c4c-22ea33f48be9.png)

**Comment by atouchet** [comment]
![](https://i.imgur.com/DEsN4QA.png)

This appears to be working correctly now in the latest Servo nightly build albeit the animation performance isn't great.
