### ISSUE TITLE
An alternative solution to build on Windows

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#18256]
As #18055 happens, I am still not able to build followed by README. Although @larsbergstrom tested it works as #18157, but I always test failed. I try to debug, but no progress.

I find an alternative solution to build on windows, and it works. I think it is worth to share, and let other developers who encountering problems while building have a new way.

Here's the steps:

1.  Download and install [Build Tools for Visual Studio 2017](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15)
2.  Install `python2.7 x86-x64` and `virtualenv`
3.  Since `mach.bat` cannot find the prompt, we should execute `Developer Command Prompt for VS 2017` manually in the Windows menu.
4. `cd to/the/path/servo`
5. `python mach build -d`

**Comment by tigercosmos** [comment]
If get error about `rustc` by `unknown`, #18145 can fix.

**Comment by shinglyu** [comment]
So the main difference you are proposing is step 3 to 5? If so (and if it's not possible to fix the vs shell anytime soon) I think it's worth adding a troubleshooting sub-section under the window build section in the README. Nice job finding an workaround.

**Comment by tigercosmos** [comment]
@shinglyu  Step 1 is also different. Instead of installing VS 2017 IDE, I install VS 2017 tool only.

**Comment by larsbergstrom** [comment]
The work that @UK992 should have made it so that we work with the VS tools only and do not need Developer Command Prompt for VS 2017. @UK992 Do you have any opinions / ideas on this?

**Comment by tigercosmos** [comment]
But if I only install VS tool 2017, use `cmd` run `mach.bat` get 
```
C:\Users\Tiger\Desktop\servo>mach.bat run
Visual Studio 2015 or 2017 is not installed.
Download and install Visual Studio 2015 or 2017 from https://www.visualstudio.com/
```
I think `mach.bat` should be modified.
