### ISSUE TITLE
Implement Node.{lookupPrefix, lookupNamespaceURI, isDefaultNamespace}

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#1826]
Spec at <http://dom.spec.whatwg.org/#locate-a-namespace-prefix> and below.

Probably wait for #1737 to happen first. Blocks #1655.

**Comment by ienzam** [comment]
Hi, I will like to work on it.

**Comment by jdm** [comment]
@ienzam Great! Let us know if you have any questions.

**Comment by ienzam** [comment]
Two questions

1. How can I test my code?
Do I need to write an integration test here - https://github.com/servo/servo/tree/master/tests/content ?
Or can I write some unit testing somewhere?

2. Where can I get more explanation about JSRef, root(), r() - any design guide or how to use them? I am mostly doing copy paste from existing code.  http://doc.servo.org/ helps a little, but not much :-(

**Comment by Ms2ger** [comment]
1. Preferably in https://github.com/w3c/web-platform-tests
2. If <http://doc.servo.org/script/dom/bindings/js/index.html> doesn't explain enough, please throw your questions at me so I can improve that.

**Comment by ienzam** [comment]
Hi, is there a way to test quickly?

My current workflow is:
1. Added one test file in tests/content
2. Edit code at components/script/dom/node.rs
3. Run
    ./mach test-content
4. Repeat from 2.

It is taking a lot of time for building servo. Is there a faster way?

**Comment by jdm** [comment]
You can run individual content tests, but there's no faster way to rebuild after making changes, unfortunately.

**Comment by jdm** [comment]
`./mach test path/to/test/file.html` will run the appropriate test harness on the provided file.

**Comment by ienzam** [comment]
Hi,
I have implemented lookupPrefix - https://github.com/ienzam/servo/commit/3dea39715fad422f27094b5e22d4ff2698c7ad20
Can you please review the code and give some feedback, if I am doing anything wrong, or how I can make it more Rust-y?

**Comment by ienzam** [comment]
Hi,
I cannot test the tests now it seems.
I am running both
```
./mach test-wpt tests/wpt/mozilla/tests/mozilla/node_lookupPrefix.html
```
and
```
./mach test-wpt tests/wpt/mozilla/tests/mozilla/node_lookupPrefix.html
```

But it is not running any tests (and also not building servo)

```
Summary
=======

Ran 0 tests
Expected results: 0
Unexpected results: 0

OK
```

What is the new way to build and run tests?

**Comment by ienzam** [comment]
Found it (autocomplete is gone :( )

    ./mach test-wpt /_mozilla/mozilla/node_lookupPrefix.html

**Comment by ienzam** [comment]
@jdm the issue is not fully fixed yet, I only implemented the first method, the other two are still left, working on it.

**Comment by jdm** [comment]
Oops!

**Comment by ienzam** [comment]
Can you please help me interpret this line (https://dom.spec.whatwg.org/#locate-a-namespace bullet point 2) -

```
 If it (element) has an attribute whose namespace is the XMLNS namespace, namespace prefix is "xmlns" and local name is (input) prefix, or if prefix is null and it has an attribute whose namespace is the XMLNS namespace, namespace prefix is null and local name is "xmlns": 
```
I am interpreting it as
```
If the element has an attribute 
whose
namespace is the XMLNS namespace
and
(
  (namespace prefix is "xmlns" and local name is input prefix)
  or
  (input prefix is null and namespace prefix is null and local name is "xmlns")
)
```
Am I correctly interpreting it?

Also cannot find any test for lookupNamespaceURI.

**Comment by Ms2ger** [comment]
I read

    (If it has an attribute whose
      (namespace is the XMLNS namespace,
       namespace prefix is "xmlns" and
       local name is prefix)), or
    (if
      prefix is null and
      it has an attribute whose
        (namespace is the XMLNS namespace,
        namespace prefix is null and
        local name is "xmlns"))

or

    If it has an attribute whose namespace is the XMLNS namespace and
    (that attribute's namespace prefix is "xmlns" and
     that attribute's local name is prefix), or
    (prefix is null and
     that attribute's namespace prefix is null and
     that attribute's local name is "xmlns")

**Comment by dzbarsky** [comment]
I have a patch and some tests for this, just need to clean them up.
