### ISSUE TITLE
An observer disconnected after a mark must receive the mark

### ISSUE THREAD

**Issue by ferjm** [servo/servo#18284]
The following test from [web-platform-tests/performance-timeline](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/performance-timeline/po-disconnect.any.js) is failing:

```javascript
async_test(function (t) {
    var observer = new PerformanceObserver(
        t.step_func(function(entryList, obs) {
          checkEntries(entryList.getEntries(),
            [{ entryType: "mark", name: "mark1"}]);
          t.done();
        })
      );
    observer.observe({entryTypes: ["mark"]});
    self.performance.mark("mark1");
    observer.disconnect();
    self.performance.mark("mark2");
  }, "An observer disconnected after a mark must receive the mark");
```

We should probably not remove the observer from the list while the [pending_notification_observers_task flag](https://github.com/servo/servo/blob/master/components/script/dom/performance.rs#L170) is set.

**Comment by jdm** [comment]
Run the test with `./mach test-wpt tests/wpt/web-platform-tests/performance-timeline/po-disconnect.html`

**Comment by pylbrecht** [comment]
I'd like to get my hands dirty on this. As I'm completely new to Servo and contributing at all, are there any resources where I can read up on performance observers, like what they are and what they have to do with the DOM? I guess [this document](https://w3c.github.io/performance-timeline/) from [#18285](https://github.com/servo/servo/issues/18285) may be relevant?

**Comment by jdm** [comment]
That is the specification that defines the PerformanceObserver API, yes. https://developer.mozilla.org/en-US/docs/Web/API/Performance_Timeline may also be useful.

**Comment by ferjm** [comment]
Thank you for your interest on this task @pylbrecht :). You may want to work on top of #18283 as `Performance.mark` is required to test the fix for this issue.

**Comment by pylbrecht** [comment]
Alright, let's do this. Thanks for the hints!
@highfive: assign me

**Comment by pylbrecht** [comment]
Unfortunately I'm somehow unable to run the test.
I ran a debug build and executed the following commands (on top of [#18283](https://github.com/servo/servo/pull/18283)):

[`./mach test-wpt tests/wpt/web-platform-tests/performance-timeline/po-disconnect.html`](https://pastebin.com/7CjJ4Ft1) 
This command confused me, because there is no `po-disconnect.html` file in that directory. But maybe I'm just not understanding how web-platform-tests are run.

[`./mach test-wpt tests/wpt/web-platform-tests/performance-timeline/`](https://pastebin.com/sBVJi7Cg)
Here the related test is not failing.

Any ideas what I'm doing wrong?

**Comment by pylbrecht** [comment]
Just to be clear: the test is expected to PASS after resolving this issue and is just expected to TIMEOUT right now, because the required module(s) are not fully implemented yet (i.e. test driven approach)?

**Comment by jdm** [comment]
Correct. The tests are shared between all multiple web browsers, so other browsers end up writing tests for features that aren't yet implemented in Servo.
