### ISSUE TITLE
Performance observer must replace observer if it's already present

### ISSUE THREAD

**Issue by ferjm** [servo/servo#18285]
It seems that we are not implementing [step 3](https://w3c.github.io/performance-timeline/#dom-performanceobserver-observe()) from the `PerformanceObserver.observe()` method spec properly.

Test: [web-platform-tests/performance-timeline/po-observe.any.js](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/performance-timeline/po-observe.any.js#L35).

**Comment by tigercosmos** [comment]
@highfive: assign me

**Comment by tigercosmos** [comment]
@ferjm,  Should I follow the [`po-observe.any.js.ini` ](https://github.com/ferjm/servo/blob/221aef9f23f27e028d3110028f5c0d8381fbcb4b/tests/wpt/metadata/performance-timeline/po-observe.any.js.ini) to write new tests?

**Comment by ferjm** [comment]
@tigercosmos you can extend [po-observe.any.js](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/performance-timeline/po-observe.any.js) directly if you consider that new tests are needed. It seems that this case is already covered by the existing tests though.

If any change is made to the existing tests you have to [update the WPT manifest](https://github.com/servo/servo/tree/master/tests/wpt#updating-the-wpt-manifest) and if there are any changes in the expected results, you have to update the [tests expectations](https://github.com/servo/servo/tree/master/tests/wpt#updating-test-expectations).

Please, note that in order to test this fix properly, you'll need to rebase your patch on top of https://github.com/servo/servo/pull/18283, which is where `Performance.mark()` and `Performance.measure()` are implemented.
