### ISSUE TITLE
Servo interface doesn't respond to window resize

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18294]
Steps to reproduce:

1. Load Servo.
2. Resize the Servo window.
3. The Servo interface and current web page do not change to match the new window size.

Tested in Windows 10. I believe this is a recent regression as I did not run into this issue previously.

Images:

Initial Servo window:

![Servo window small](https://i.imgur.com/8EbigZ9.png)

Servo window resized to fullscreen:

![Servo window big](https://i.imgur.com/PGzTLFs.png)

**Comment by BojanKogoj** [comment]
It, however, works fine if you run in from CMD with website address, such as 
`servo.exe https://en.wikipedia.org/wiki/Main_Page`

**Comment by jtracey** [comment]
Same behavior on Linux (Xubuntu 16.04). The workaround of supplying an address as a terminal argument is effective in the sense that resize works properly, but also seems to make Browser.html not appear (i.e. no address bar, hamburger menu, etc.), I don't know if it's a related issue.

**Comment by atouchet** [comment]
This bug is actually more complex than I originally thought. It turns out the window can be properly resized but only from certain sizes. If you initially resize the window horizontally to make it very thin it can then be resized larger (such as maximized) without issue.

**Comment by atouchet** [comment]
2017-08-29 was the first nightly build with this issue.

**Comment by atouchet** [comment]
This is no longer an issue.
