### ISSUE TITLE
Buildbot jobs fail intermittently with "exceptions.Exception: Actual commit (…) differs from requested commit (…)"

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#18338]
This is happening *a lot* lately. As in, every PR needs to be retried multiple times. CC @edunham @larsbergstrom @Manishearth  

Example:

https://github.com/servo/servo/pull/18336#issuecomment-326481271

http://build.servo.org/builders/mac-rel-wpt1/builds/5713

![screenshot from 2017-09-01 06-03-21](https://user-images.githubusercontent.com/291359/29954865-4662f842-8edb-11e7-88e7-a7335355240e.png)

`err.text`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/buildbot/process/buildstep.py", line 322, in startStep
    result = yield self.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "factories.py", line 39, in run
    got_rev, rev
exceptions.Exception: Actual commit (c6758e38ff77f706dd6cc2edc19854b03b285491) differs from requested commit (8c12d5bbc433aedb486b541ca925dd4065864aba)
```

**Comment by nox** [comment]
> 13:52 &lt;•SimonSapin> https://github.com/servo/servo/issues/18338 is being a pain
> 13:52 &lt;crowbot> Issue #18338: Buildbot jobs fail intermittently with "exceptions.Exception: Actual commit (…) differs from requested commit (…)" - https://github.com/servo/servo/issues/18338
> 13:52 &lt;nox> SimonSapin: AFAIK it's a garbage lockfile somewhere.
> 13:53 &lt;•SimonSapin> git lock?
> 13:53 &lt;nox> SimonSapin: http://build.servo.org/builders/mac-rel-wpt1/builds/5713/steps/git/logs/stdio
> 13:53 &lt;nox> SimonSapin: Yes.
New messages
> 13:53 &lt;nox> SimonSapin: I suspect this happened because we forced some PRs,
> 13:53 &lt;nox> and forcing stuff just stops the builds without cleaning up.
> 13:53 &lt;•SimonSapin> comment in the issue?
> 13:53 &lt;nox> So if you force during a Git checkout, nothing works anymore afterwards.
> 13:53 &lt;nox> Imma copypasta

**Comment by larsbergstrom** [comment]
There are two issues here:

1) the first step `git update` should not be green - there is this line in there:
```
fatal: Unable to create '/Users/servo/buildbot/slave/mac-rel-wpt1/build/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

I'm assuming this is the result of a `force` or otherwise cancelled build that needs to be cleaned up better.

2) It can be fixed manually with something like I did in:
https://github.com/servo/saltfs/issues/680#issuecomment-304304608

at the risk of "wow, that seems dangerous" I believe that admins can do something like:
```
salt servo-mac* cmd.run 'find /Users/servo/buildbot/slave index.lock | xargs rm'
```

And fix it up for the whole cluster. Or burn it all to the ground :-)

cc @edunham

**Comment by larsbergstrom** [comment]
@aneeshusa @edunham Any reason you can think of for this behavior? Can't `cmd.run` right now:
```
root@servo-master1:~# salt 'servo-mac1' test.ping
servo-mac1:
    True
root@servo-master1:~# salt 'servo-mac1' cmd.run 'find /Users/servo/buildbot/slave index.lock | xargs echo'
servo-mac1:
    Minion did not return. [No response]
root@servo-master1:~# 
```

**Comment by aneeshusa** [comment]
Works for me right now:
```
root@servo-master1:~# salt 'servo-mac*' cmd.run 'echo hi'
servo-mac2:
    hi
servo-mac4:
    hi
servo-mac3:
    hi
servo-mac8:
    hi
servo-mac9:
    hi
servo-mac7:
    hi
servo-mac5:
    hi
servo-mac6:
    hi
servo-mac1:
    hi
root@servo-master1:~#
```

**Comment by aneeshusa** [comment]
Depending on how long moving to Taskcluster takes (e.g. #17580, servo/saltfs#559 and co), we may want to fork Buildbot and write/backport a better git plugin that's less prone to these issues.

**Comment by aneeshusa** [comment]
Also, I think a slightly safter version of your command would be
```
root@servo-master1:~# salt 'servo-mac*' cmd.run 'find /Users/servo/buildbot/slave -path "*/.git/index.lock"'
```
followed by
```
root@servo-master1:~# salt 'servo-mac*' cmd.run 'find /Users/servo/buildbot/slave -path "*/.git/index.lock" -delete'
```

You didn't pass a `-name` or `-path` before, so that might just delete everything...

**Comment by larsbergstrom** [comment]
Aha, nice tweaks - I had noticed the `-name` thing before running it, luckily :-)

I just did:
```
ssh root@servo-mac5.servo.org 'find /Users/servo/buildbot/slave -name index.lock | xargs rm'
```

For now, which is less than awesome. I didn't know about the `-delete` arg - that's fantastic!

**Comment by jdm** [comment]
The solution is documented in https://github.com/servo/servo/wiki/Buildbot-administration, so no need to keep this open.
