### ISSUE TITLE
Remove integrity check for no-cors requests

### ISSUE THREAD

**Issue by jdm** [servo/servo#18345]
The Fetch specification has been updated to allow non-empty integrity strings for requests that are marked as no-cors: https://github.com/whatwg/fetch/pull/584

We should remove the corresponding check in our implementation:
https://dxr.mozilla.org/servo/rev/3dceb111587178cdff60041d76a2544f275e6371/components/script/dom/request.rs#326-329

Unfortunately, there's no automated test available for this yet because we are having trouble updating our copy of the upstream tests. However, you can try it yourself by running a page that evaluates this JS: `new Request("", {"mode" : "no-cors", "integrity" : "not  an empty string"});`.

**Comment by TheDan64** [comment]
@highfive: assign me

I'd be interested in taking this on. Is this just a matter of removing that is_empty check or is there more to it?

**Comment by TheDan64** [comment]
Well, I guess someone decided to complete the issue while I was working on it.

**Comment by tigercosmos** [comment]
@TheDan64 I think you can finish this, because it is you to be assigned.
