### ISSUE TITLE
Replace manual implementations of Runnable::name with automatic type name

### ISSUE THREAD

**Issue by jdm** [servo/servo#18354]
We have a [Runnable](https://doc.servo.org/script/script_thread/trait.Runnable.html) trait with a name method. This method is used to improve profiling output so we can tell at runtime which concrete runnable is being executed, so we have to duplicate the name of the type every time we create a new type that implements Runnable. We can remove all of that if we use this code for Runnable::name instead: https://gist.github.com/2210a8674dd7813cec8c7148a3a0b719

Code: `components/script/script_thread.rs`, and every implementation of Runnable that overrides the name method.

No need to run any tests for this change; if it builds, that's good enough for a PR.

**Comment by toidiu** [comment]
@highfive assign me
