### ISSUE TITLE
Perma build error for servo-mac6, causes mac-* test failures 

### ISSUE THREAD

**Issue by chenpighead** [servo/servo#18374]
So far, the servo-mac6 build slave consistently reports "cargo[63125:490151272] Metadata.framework [Error]: couldn't get the client port" on all builds, which leads to failures like [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9085) in #18365 and [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1568) in #18373

**Comment by chenpighead** [comment]
@larsbergstrom @edunham could you help handle this issue?

**Comment by larsbergstrom** [comment]
I killed the buildbot process, so at least it should be gone for a little while. Sorry about this!

**Comment by edunham** [comment]
mac6 has since been paved and replaced with a host sporting better specs.
