### ISSUE TITLE
Pathfinder demo fails due to old version of SpiderMonkey

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#18513]
I get:

    Error at http://localhost:8000/js/pathfinder/text-demo.js:1431:19 missing = in const declaration

cc @tschneidereit @fitzgen

**Comment by nox** [comment]
You should probably just not use fancy new JS features in the demo for now.

**Comment by pcwalton** [comment]
I'm just going to run it in Firefox. Servo can't remain stuck on an old JS version forever.

**Comment by tschneidereit** [comment]
> I'm just going to run it in Firefox. Servo can't remain stuck on an old JS version forever.

It won't. The smup is only blocked by Windows build system things that seem very much surmountable.

**Comment by nox** [comment]
@tschneidereit Any ETA for a smup?

**Comment by asajeffrey** [comment]
#20585

**Comment by atouchet** [comment]
SpiderMonkey has now been updated.
