### ISSUE TITLE
Plan path to switch to mime 0.3

### ISSUE THREAD

**Issue by nox** [servo/servo#18518]

**Comment by Eijebong** [comment]
@highfive: assign me

**Comment by Eijebong** [comment]
This is blocked by https://github.com/cyderize/rust-websocket/issues/132 which seems to be blocked on some other hyper bug.

**Comment by Eijebong** [comment]
Let's make a list:

- [ ] https://github.com/nox/hyper_serde/pull/20
- [ ] https://github.com/cyderize/rust-websocket/issues/132
- [ ] https://hg.mozilla.org/mozilla-central/file/tip/testing/webdriver

**Comment by Eijebong** [comment]
Done now :)
