### ISSUE TITLE
Tidy should ignore some checks in multiline strings

### ISSUE THREAD

**Issue by wafflespeanut** [servo/servo#18551]
Right now, tidy throws errors for

``` rust
assert!(foo("test
             foo-bar"));
```

(because there's a hyphen, which tidy believes as a "minus" in Rust code)

Instead, it should be ignoring the contents of multi-line strings completely. We should probably track the opening and closing of double quotes across lines.

Code: `python/tidy/servo_tidy/tidy.py`

**Comment by mdboom** [comment]
@highfive: assign me

**Comment by KiChjang** [comment]
I think it should just ignore hyphens in strings completely.

**Comment by wafflespeanut** [comment]
No, because this could then throw error on something else (like missing/extra space before/after char - stuff like that). This should ignore the contents entirely (not just hyphens).
