### ISSUE TITLE
Unnecessarily allocating an error string

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#18594]
In: https://github.com/servo/servo/blob/29517d553e6c2fddc7e3cf0c0abef58c6d0f34aa/components/script/document_loader.rs#L133

there's a line:
```rust
        self.blocking_loads.remove(idx.expect(&format!("unknown completed load {:?}", load)));
```

This allocates the error string even if the `idx` exists.

This should be replaced by `idx.unwrap_or_else(|| panic!(...))`.

**Comment by tigercosmos** [comment]
@highfive: assign me

**Comment by tigercosmos** [comment]
How do I test to know the result?

**Comment by asajeffrey** [comment]
This change is a refactoring, there shouldn't be any testable difference! If it compiles, that's good enough evidence of correctness for me to review it!
