### ISSUE TITLE
Text layout is broken in recent builds

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#18616]
Looks like something got messed up with text layout in recent builds.

![screen shot 2017-09-25 at 11 15 42 am](https://user-images.githubusercontent.com/547158/30787361-0760cf6e-a1e3-11e7-90ec-642343a210e1.png)
![screen shot 2017-09-25 at 11 15 17 am](https://user-images.githubusercontent.com/547158/30787359-07583804-a1e3-11e7-8223-4a685c2748b8.png)
![screen shot 2017-09-25 at 11 14 30 am](https://user-images.githubusercontent.com/547158/30787360-075ffea4-a1e3-11e7-8757-5333d6e64715.png)

**Comment by jonathandturner** [comment]
Going to see if I can bisect to find the offending PR

**Comment by glennw** [comment]
I suspect this will be resolved by the most recent WR update that landed. We encountered a mac driver bug in the shader compiler, which caused glyphs to be fetched incorrectly. The latest WR update includes a workaround for this bug.

**Comment by jonathandturner** [comment]
@glennw - that was fast!  Yeah looks fixed with your update.
