### ISSUE TITLE
download.servo.org serves an empty dmg for macOS

### ISSUE THREAD

**Issue by sgrif** [servo/servo#18648]
I assumed there'd be a browser in there

**Comment by ScottAbbey** [comment]
I downloaded the file at [this link](https://download.servo.org/nightly/mac/servo-latest.dmg) 32 minutes after your message and ended up with the file `servo-latest.dmg`, size 35621878 bytes.  The About Servo window says this is `Servo 0.0.1-0160aaeeea`.

**Comment by sgrif** [comment]
It appears to be working now.
