### ISSUE TITLE
Can not install xorg-dev and libfreetype6-dev on Ubuntu 16.04

### ISSUE THREAD

**Issue by dkotrada** [servo/servo#18683]
Got dependencies problems with this packages. Can I omit it while I setup my environment for servo?

**Comment by tigercosmos** [comment]
Relative to #18682

**Comment by dkotrada** [comment]
You are rightl. It is my problem only... :( 

It seems a have some corrupted pakages on my system ... Just can't find where and what...

**Comment by dkotrada** [comment]
Here is how I solved my issue. https://askubuntu.com/questions/720361/cant-install-libpng-dev

**Comment by tigercosmos** [comment]
Nice :)
