### ISSUE TITLE
Setup environment for Ubuntu 16.04 package dependency (no package libpng-dev)

### ISSUE THREAD

**Issue by dkotrada** [servo/servo#18682]
When I follow instructions for setup environment on Ubuntu 16.04 I get this message:

libfreetype6-dev : Depends on: libpng-dev

Official repositoriy doesn't have this package: libpng-dev

So I can not instal libpng-dev. So what should I do now?

**Comment by tigercosmos** [comment]
I use Ubuntu 16.04 with VMware player
```
sudo apt install git curl freeglut3-dev autoconf libx11-dev \
    libfreetype6-dev libgl1-mesa-dri libglib2.0-dev xorg-dev \
    gperf g++ build-essential cmake virtualenv python-pip \
    libssl-dev libbz2-dev libosmesa6-dev libxmu6 libxmu-dev \
    libglu1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev
```
But I did not encounter error. 

Maybe use a clean environment to try again?

**Comment by dkotrada** [comment]
problem withmy system...
