### ISSUE TITLE
Possible bug in parsing and serialization of ::lang pseudo-class

### ISSUE THREAD

**Issue by raphaelcohn** [servo/servo#18691]
Hi,

Whilst looking into `style/servo/selector_parser.rs`, I spotted this code (starting at line 437):-

```rust
let pseudo_class = match_ignore_ascii_case!{ &name,
            "lang" => {
                Lang(parser.expect_ident_or_string()?.as_ref().into())
            }
```

The only thing is, I understood that the `::lang` psuedo-class accepts "accepts a comma-separated list of one or more language ranges as its argument" - see <https://drafts.csswg.org/selectors/#lang-pseudo>. This code only accepts one. That said, the function `extended_filtering()` in the same file (around line 725) seems to then split the returned value on a comma. Surely this is at odds with the design elsewhere in the code base?

Likewise, the serialization of this `to_css()` seems to always assume that the value is valid CSS identifier - it may not be (from line 279):-

```rust
impl ToCss for NonTSPseudoClass {
    fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
        use self::NonTSPseudoClass::*;
        match *self {
            Lang(ref lang) => {
                dest.write_str(":lang(")?;
                serialize_identifier(lang, dest)?;
                return dest.write_str(")")
            }
```

Thoughts?

**Comment by emilio** [comment]
> The only thing is, I understood that the ::lang psuedo-class accepts "accepts a comma-separated list of one or more language ranges as its argument" - see https://drafts.csswg.org/selectors/#lang-pseudo. This code only accepts one. That said, the function extended_filtering() in the same file (around line 725) seems to then split the returned value on a comma. Surely this is at odds with the design elsewhere in the code base?

We implement the selector from selectors level 3, which didn't specify commas. I don't know if there's a tracking issue to update it though.

> Likewise, the serialization of this to_css() seems to always assume that the value is valid CSS identifier - it may not be (from line 279):-

That code doesn't assume it is a valid identifier, but it escapes the string as such. That does look a bit fishy, though, since we accept strings. Seems like the serialization code should be doing the same as Gecko's, which always serializes as a string.

**Comment by SimonSapin** [comment]
In serialization, what matters most is that parsing again produces the same selector. So in this case we can use either a string or an identifier.

Thanks for looking into this @raphaelcohn, closing as I think there is nothing to change here. (Until we decide to implement Selectors Level 4.)
