### ISSUE TITLE
Free the interface prototype array when Window is finalized

### ISSUE THREAD

**Issue by jdm** [servo/servo#1871]
Currently it leaks, since we just stash a pointer to the array contents in a reserved slot and forget about the original vector. We'll need a custom finalizer for Window so we can access the slot before it goes away.

**Comment by Ms2ger** [comment]
This involves implementing a `finalize_global` function that calls `Box::from_raw` on the result of `get_proto_or_iface_array` to let it drop and changing the code returned by `finalizeHook` in `CodegenRust.py` to call `finalize_global` if `descriptor.isGlobal()`.
