### ISSUE TITLE
SSL error on Android: the handshake failed

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#18731]
For any https:// page, a white page with the text "the handshake failed" is rendered instead of the expected page.

My guess is that i run into this: https://github.com/sfackler/rust-openssl/blob/67b5fd1c9750d3434adca8d700e265a5238de3be/openssl/src/ssl/error.rs#L85

Any idea what could go wrong? Maybe failing to load certificates?

**Comment by paulrouget** [comment]
Here is the full error: error:04091068:rsa routines:INT_RSA_VERIFY:bad signature

**Comment by paulrouget** [comment]
In theory, all I need to do is to make sure that `resources/cert` is correctly loaded, right? We don't rely on the local certificates?

**Comment by paulrouget** [comment]
By local I mean, Servo doesn't need the Android CA files, right?

**Comment by jdm** [comment]
Correct.

**Comment by paulrouget** [comment]
/cc @avadacatavra @larsbergstrom 
I've been told you might be able to help me.

I'm not sure how to investigate this issue.

**Comment by paulrouget** [comment]
@avadacatavra any idea what could be the issue?

more /cc: @Manishearth @eddyb I've been told you might also have some ideas?

**Comment by jdm** [comment]
@paulrouget I recommend extracting a minimal reproduction from Servo's network code so it's easier to debug.

**Comment by avadacatavra** [comment]
@paulrouget i'll look into it--i don't know much about android. minimal reproduction would be helpful

**Comment by paulrouget** [comment]
So - as I was trying to build a minimal test case, I realized that the ["official" build](https://github.com/servo/servo/wiki/Building-for-Android) doesn't have this issue. *https://* pages load properly.

So this must be an issue with the way I build/package/load Servo in my Android app.

**Comment by paulrouget** [comment]
So I'm pretty sure the `certs` file is properly loaded. When I use an empty file instead, servo just crash. With the proper content, servo runs correctly, but print the "handshake failed" message.

**Comment by paulrouget** [comment]
@MortimerGoro maybe you can help. So I get **https://** pages to work well with a regular Android build, but not with my custom build (it's really a totally different build process, we don't use anything from `support/android`, we use Xamarin and load libservo.so in C#).

I'm trying to figure out what might go wrong. The `certs` file is being read (if there's no `certs` file, it crashes, proving at least that the file is being accessed). The openssl library is compiled the same way it's done with Servo's build mechanism ([see here](https://github.com/paulrouget/servofocus/blob/master/rust/android/build.sh#L34)). I'm giving the proper permissions to the app (I think).

I'm looking for ideas of what to investigate. I must be missing something during the build process, the packaging or the way I initialise Servo. Any hint would help.

**Comment by larsbergstrom** [comment]
You've put all of the resources/ directory into /sdcard/servo?
https://github.com/servo/servo/blob/2567c40829704dcb1c7769defffb9dabfd701633/support/android/apk/app/src/main/java/com/mozilla/servo/MainActivity.java#L251

The current APK build process is much cleaner than when I originally wrote it (thanks, @MortimerGoro!) but the whole Servo experience on android is still a ton of bailing wire and duct tape, especially in terms of file installation paths, permissions, and OS integration. We aren't really planning to work on that right now, unfortunately, as we're just standing up enough support to do standalone VR/AR demos through EOY.

**Comment by paulrouget** [comment]
> You've put all of the resources/ directory into /sdcard/servo?

Yes. Resources are being read correctly.

> the whole Servo experience on android is still a ton of bailing wire and duct tape, especially in terms of file installation paths, permissions, and OS integration. We aren't really planning to work on that right now

That's totally fine. For now, I'm just experimenting with embedding Servo in a non-rust android app.

**Comment by paulrouget** [comment]
Building in 32 bits instead of 64 solves the issue.

I moved from  `aarch64-linux-android` to `arm-linux-androideabi`.
