### ISSUE TITLE
Use XML fragment serialization for innerHTML in XML documents

### ISSUE THREAD

**Issue by jdm** [servo/servo#18776]
Per https://w3c.github.io/DOM-Parsing/#serializing and https://github.com/servo/servo/blob/8dece5e74e32223d968648080bb371f3be7fbd7c/components/script/dom/element.rs#L2050-L2054 we don't support this yet.

**Comment by tigercosmos** [comment]
I would like to work on it. @jdm could you help me?

**Comment by jdm** [comment]
Sure! There's an implementation of XML serialization in [xml5ever](https://github.com/servo/html5ever/blob/master/xml5ever/src/serialize/mod.rs), so the goal here is to use that algorithm instead of the HTML one if the document associated with the element is not an [HTML document](https://doc.servo.org/script/dom/document/struct.Document.html#method.is_html_document).

**Comment by tigercosmos** [comment]
So it would like this?
```
 fn GetInnerHTML(&self) -> Fallible<DOMString> { 
     if( not html ) {
         Call xml5ever functions
     } else {
         self.serialize(ChildrenOnly) 
     }
 } 
```

**Comment by jdm** [comment]
It probably belongs in the `serialize` method, but yes.

**Comment by tigercosmos** [comment]
Where is the test for `component/script/dom/element.js`?

**Comment by jdm** [comment]
The various xhtml tests in https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/domparsing should cover this change. Use `./mach test-wpt tests/wpt/web-platform-tests/domparsing` to run the tests in that directory.
