### ISSUE TITLE
Glutin/headless mode wastes 100% of a CPU core polling for events

### ISSUE THREAD

**Issue by mateon1** [servo/servo#18770]
As the title says.
I noticed this while trying to reduce a bug.
`./mach run -r -z about:blank` uses 100% of a single CPU core, while `./mach run -r about:blank` uses 0% when nothing is happening.

[Here's a flamegraph](https://ipfs.io/ipfs/QmdHsb4B9ZJSU5BQTeZCy9FKV4jDh3hnp5jUcTxxJPaE4j/glutin.svg) (Captured in debug mode, so the stacks make sense, but the same happens in release mode)

**Comment by jdm** [comment]
Window::handle_events returns an empty vector immediately when in headless mode: https://github.com/servo/servo/blob/7188b348587b06d31f939be99dcf73392c7f3def/ports/glutin/window.rs#L667-L699

**Comment by paulrouget** [comment]
Would blocking `wait_events` for 15ms do the trick?

**Comment by mateon1** [comment]
@paulrouget 
I think so. As a temporary measure while fuzzing, I inserted a thread::sleep() for one millisecond in Servo's main loop. It reduced the CPU usage to 0.7-1.3 for about:blank.
I believe sleeping in the main loop when wait_events() returns an empty Vec is a nice solution.

```patch
     loop {
-        let should_continue = servo_wrapper.servo.handle_events(window.wait_events());
+        let events = window.wait_events();
+        if (events.is_empty()) {
+            thread::sleep(std::time::Duration::from_millis(5));
+        }
+        let should_continue = servo_wrapper.servo.handle_events(events);
         if !should_continue {
             break;
         }
     }
```

The duration can be something else, of course.
Should I make a PR?

**Comment by paulrouget** [comment]
> Should I make a PR?

Yes please. But make this change only for headless mode, here I think: https://github.com/servo/servo/blob/7188b348587b06d31f939be99dcf73392c7f3def/ports/glutin/window.rs#L667
