### ISSUE TITLE
Implement the document lifecycle

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1879]
This includes
* [x] Script scheduling including `<script async>` and `<script defer>`
* [x] Document load events like `DOMContentLoaded` and `onload`
* [ ] [Session history](http://www.whatwg.org/specs/web-apps/current-work/multipage/history.html) and its interaction with `document.open` and `document.write`

**Comment by jdm** [comment]
As far as I know we've implemented all of these pieces.
