### ISSUE TITLE
Rendering errors in Transparent Rects demo

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18801]
![Rects](https://i.imgur.com/oZbx8Fv.png)

The rects appear to have rendering issues which didn't occur previously (aside from the fact they are stuck in the top left corner which is tracked in #15689). You might need to look at the image in full size to see it clearly.

**Comment by atouchet** [comment]
I managed to get this to load without the top left corner issue.

![Rects](https://i.imgur.com/NY9KcLG.png)

Incomplete rects flicker in and out of the image.

**Comment by atouchet** [comment]
In the latest nightly build the rects have some kind of square border around them.

![Rects](https://i.imgur.com/vVh1C04.png)

Is this https://github.com/servo/webrender/issues/1943?

**Comment by atouchet** [comment]
This appears to be fixed now.

**Comment by sviter** [comment]
I still can see this issue. For me it's looks like figure in first comment.

**Comment by atouchet** [comment]
@sviter hmm strange. Could you maybe take a screenshot to compare? Also what OS and GPU are you using?

**Comment by jdm** [comment]
The fact that the rects are squished into a tiny corner is tracked in https://github.com/servo/servo/issues/15689.

**Comment by sviter** [comment]
![tr_rects_servo](https://user-images.githubusercontent.com/6523067/34219920-cff0b3e4-e5c3-11e7-812e-25c3a1b6ab4e.png)
My OS is Win 10 and GPU is  Intel® HD Graphics 505

**Comment by atouchet** [comment]
@sviter that is not the bug being tracked in this issue report. As @jdm mentioned the top left corner issue is #15689.
