### ISSUE TITLE
Lazy transcoding of DOM strings

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1880]
DOM APIs and SpiderMonkey require us to use UCS-2 strings, but the [vast majority](http://w3techs.com/technologies/overview/character_encoding/all) of content comes off the wire in UTF-8 or another ASCII-compatible encoding.  We can save memory and potentially time by storing a DOM string as UTF-8 and converting it to UCS-2 when first touched by script.

Not sure how this would interact with interning.

See #282, #1701.

**Comment by kmcallister** [comment]
This is part of [my current plan for strings in html5ever](https://github.com/kmcallister/tendril).

**Comment by pshaughn** [comment]
Is this issue talking about something that's still relevant, or is it all stuff that was later decided to just make UTF8 all the time?

**Comment by jdm** [comment]
Given that spidermonkey is adding more and more APIs that accept UTF-8, I think we can close this.
