### ISSUE TITLE
Flexbox content overruns containing box

### ISSUE THREAD

**Issue by jdm** [servo/servo#18837]
```html
<!DOCTYPE html>
<style>
  .Streams-momentsModules {
  display: flex;
  }

  .MomentCapsuleSummary {
  border: 10px solid red;
  display: flex;
  margin: 0 50px;
  width: 100%;
  }

  .MomentMediaItem {
  overflow: hidden;
  }
</style>
<div class="Streams-momentsModules">
  <div class="MomentCapsuleSummary">
    <div class="MomentMediaItem">
      <img src="https://pbs.twimg.com/media/DJqND6vWAAADD8c.jpg">
    </div>
  </div>
</div>
```

Firefox:
<img width="1065" alt="screen shot 2017-10-11 at 4 32 36 pm" src="https://user-images.githubusercontent.com/27658/31465394-d6ddcfc4-aea1-11e7-80c2-63edda84e742.png">

Servo:
<img width="973" alt="screen shot 2017-10-11 at 4 32 59 pm" src="https://user-images.githubusercontent.com/27658/31465416-e0bee4ce-aea1-11e7-8839-982ac4915642.png">

**Comment by krk** [comment]
This can be reproduced in a14b952fa3eedec86e6308213c525538bcb20827

**Comment by mrobinson** [comment]
This seems to be working with non-legacy layout now.

**Comment by mrobinson** [comment]
This seems to be working with non-legacy layout now.
