### ISSUE TITLE
Merge ./mach bootstrap-rust and ./mach bootstrap-cargo

### ISSUE THREAD

**Issue by nox** [servo/servo#18874]
They share the same version numbers now anyway.

**Comment by tigercosmos** [comment]
Is there more information about this issue?

**Comment by SimonSapin** [comment]
These sub-commands are defined in `python/servo/bootstrap_commands.py`. It’s not useful to run one without the other, so they could both be replaced with one. Note however that there’s already an existing `bootstrap` sub-command that does something else.

**Comment by tigercosmos** [comment]
How do you suggest to solve this? Is it a good way to name a new sub-command to combine them? And what should the new sub-command name?

**Comment by SimonSapin** [comment]
Though personally I don’t care much about doing that v.s. the status quo, I usually run `./mach fetch` to fetch/bootstrap everything. Maybe @nox, having filed this issue, has opinions.

**Comment by tigercosmos** [comment]
@nox How do you think?

**Comment by SimonSapin** [comment]
I’m starting to work on https://github.com/servo/servo/issues/11361. Both subcommands will probably be removed in the process, making this issue moot.
