### ISSUE TITLE
assertion failed: !self.Document().needs_reflow() ||    (!for_display && self.Document().needs_paint()) ||    self.window_size.get().is_none() || self.suppress_reflow.get()

### ISSUE THREAD

**Issue by grabstepango** [servo/servo#18901]
assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()
### Servo Version:
Servo 0.0.1-086c482
### Backtrace:
```

WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×2.0333333 at (82.23333,31046.666))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×2.0333333 at (107.7,31254.666))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×2.0333333 a
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment]
@grabstepango What page were you looking at?

**Comment by grabstepango** [comment]
@jdm It was one of wikipedia articles, can't find or reproduce it now. No idea why it wasn't populated. Is there any way I could check the history of viewed pages or reports inside servo?

**Comment by jdm** [comment]
Unfortunately no. And we choose not to automatically populate the URL field for the sake of privacy.

**Comment by grabstepango** [comment]
@jdm thanks for the info, I'm closing it. Will open again if able to reproduce.
