### ISSUE TITLE
Unfork glutin

### ISSUE THREAD

**Issue by nox** [servo/servo#18918]
Latest attempt was #17311.

**Comment by EloD10** [comment]
@paulrouget work actually on this : https://github.com/paulrouget/servoshell
So the issue is open/assigned ? Or we can work on this ?

**Comment by jdm** [comment]
Nobody is currently working on this; if you can solve the problems from https://github.com/servo/servo/pull/17311#issue-235779345 that would be very helpful!

**Comment by atouchet** [comment]
This is being worked on in #19895.
