### ISSUE TITLE
Close icon doesn't show up in Servo error reporter

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18913]
Image:

![Servo window](https://i.imgur.com/rpzpZFr.png)

A black square appears instead of the close icon. Tested in Windows 10 with Browser.html.

**Comment by atouchet** [comment]
Looking at the code in Browser.html I think the close icon is actually text and not an image: https://github.com/browserhtml/browserhtml/blob/7ae365b27f537105d079555d75b961c82d466db9/src/Browser/IssueReporter.js#L146

Servo appears to have issues rendering U+2715 then.

**Comment by paulrouget** [comment]
Could be because of https://github.com/browserhtml/browserhtml/pull/1308

**Comment by atouchet** [comment]
@paulrouget no I don't think so. This issue predates that PR.

**Comment by atouchet** [comment]
Taking a look at https://en.wikipedia.org/wiki/X_mark which lists a number of Unicode X symbols the only one that appears to show up in Servo is U+00D7.

![X marks](https://i.imgur.com/DLBlV1s.png)

**Comment by atouchet** [comment]
![X marks](https://i.imgur.com/9zuSCsg.png)

U+2715 (along with the other symbols) is now displayed in Servo.
