### ISSUE TITLE
unused import

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#18916]
On `commit eecee32a0b139096e8fe268590536b2eb5ac911d`
```
warning: unused import: `MatchingMode`
  --> C:\Users\123\Desktop\servo\components\script\dom\element.rs:92:66
   |
92 | use selectors::matching::{ElementSelectorFlags, MatchingContext, MatchingMode, RelevantLinkStatus};
   |                                                                  ^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
```

**Comment by SimonSapin** [comment]
I believe this is fixed in 4c5d6fd8345f301be4aafe2dba71cdf2de0ab01e. Thanks for the report!

**Comment by tigercosmos** [comment]
@SimonSapin  Seems not?
https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L92

**Comment by SimonSapin** [comment]
Oh indeed, sorry. I can reproduce on master, I suppose another PR re-introduced that warning.

**Comment by tigercosmos** [comment]
I will do it.
