### ISSUE TITLE
Remove cfg for windows in linux module

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#18922]
in [`components/gfx/platform/freetype/font_list.rs`](https://github.com/servo/servo/blob/master/components/gfx/platform/freetype/font_list.rs#L135), which is the module for `linux`.
There are codes `#[cfg(target_os = "linux")]` and `#[cfg(target_os = "windows")]`, and I think we should remove them since we would enter the module only if [`components/gfx/platform/mod.rs`](https://github.com/servo/servo/blob/master/components/gfx/platform/mod.rs) determines.

```
#[cfg(target_os = "linux")]
pub fn last_resort_font_families() -> Vec<String> {
    vec!(
        "Fira Sans".to_owned(),
        "DejaVu Sans".to_owned(),
        "Arial".to_owned()
    )
}

#[cfg(target_os = "windows")]
pub fn last_resort_font_families() -> Vec<String> {
    vec!(
        "Arial".to_owned()
    )
}

#[cfg(target_os = "linux")]
pub static SANS_SERIF_FONT_FAMILY: &'static str = "DejaVu Sans";

#[cfg(target_os = "windows")]
pub static SANS_SERIF_FONT_FAMILY: &'static str = "Arial";
```

**Comment by jdm** [comment]
Ah, this is left over from when Windows relied on freetype as well. Yes, this would be a nice cleanup.

**Comment by tigercosmos** [comment]
@highfive: assign me
