### ISSUE TITLE
Unable to run subsets of CSS tests after recent WPT update

### ISSUE THREAD

**Issue by glennw** [servo/servo#18931]
Running ```./mach test-css --release --processes=8 tests/wpt/css-tests/css-backgrounds-3_dev``` results in the following exception:

```
AttributeError: 'Manifest' object has no attribute 'iterdir'
```

Similarly, running on a single file results in:

```
AttributeError: 'Manifest' object has no attribute 'iterpath'
```

The last entry in the backtrace is:

```
  File "tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/manifestinclude.py", line 100, in _add_rule
    iterator = manifest.iterpath if os.path.isfile(path) else manifest.iterdir
```

**Comment by glennw** [comment]
cc @jdm

**Comment by glennw** [comment]
If I manually copy the ```iterpath``` and ```iterdir``` implementations from the WPT implementation of the ```Manifest``` class to the CSS implementation of the ```Manifest``` class, it seems to work. I'm not sure if that's an appropriate fix though.

**Comment by jdm** [comment]
That is a totally fine fix. The csswg-tests are going away, so we can do whatever it takes to help them limp along.
