### ISSUE TITLE
Make fire_mouse_event accept an enum instead of a string argument

### ISSUE THREAD

**Issue by jdm** [servo/servo#18943]
We only use the `fire_mouse_event` method for specific kinds of mouse events, so it should accept a stronly-typed enum that can be converted into an appropriate string value.

Code: `components/script/dom/document.rs`

No need for automated tests; if it builds, that's good enough for a pull request.

**Comment by mhaessig** [comment]
@highfive: assign me

**Comment by mhaessig** [comment]
@jdm There is already an `enum MouseEventType` at [`components/script_traits/lib.rs`](https://github.com/servo/servo/blob/fe16c1d5c3c9084da0ccb85af599d6ec0f8ab20b/components/script_traits/lib.rs#L418#L427
Should I modify that enum and implement a `toString` function for it so we only have one mouse event type enum?

**Comment by jdm** [comment]
@mhaessig Good find, but that enum contains additional variants that would not be used for `fire_mouse_event`, so I would rather use a separate enum for this.
