### ISSUE TITLE
Acid 2 rendering issue on MacBook5,2 w/El Capitan

### ISSUE THREAD

**Issue by easyaspi314** [servo/servo#18940]
`tests/html/acid2.html` is not rendering properly.

### Servo version
Nightly version Servo 0.0.1-ca08271345 (downloaded from the website)

### OS Version
Mac OS X 10.11.6 El Capitan

### System specs
**MacBook (13-inch, Mid 2009)** &nbsp; MacBook5,2
**Processor** &nbsp; 2.13 GHz Intel Core 2 Duo
**Memory** &nbsp; 4 GB 667 MHz DDR2 SDRAM
**Graphics** &nbsp; NVIDIA GeForce 9400M 256 MB
**Display** &nbsp; Built-in display, 13.3-inch (1280 x 800)
I know my specs suck, deal with it. 😞 

### Screenshot
![screen shot 2017-10-18 at 12 56 54 pm](https://user-images.githubusercontent.com/6258309/31731730-ed826b2e-b403-11e7-8fbf-c1a5a7aa5963.png)
Additionally, these artifacts are left when scrolling, and it seems that I can scroll indefinitely (which is strange because on Safari, the test doesn't scroll at all, even with the window resized) : 
![screen shot 2017-10-18 at 1 15 38 pm](https://user-images.githubusercontent.com/6258309/31732445-853682b4-b406-11e7-9961-3d9a2398ea7e.png)
There are also some rendering issues on the main screen:
![screen shot 2017-10-18 at 1 22 12 pm](https://user-images.githubusercontent.com/6258309/31732714-6f68f60a-b407-11e7-8335-40f596dcd7c9.png)

**Comment by mrobinson** [comment]
Going to close this one as it's in relation to the old layout system and I think it makes sense that all open Acid2 bugs are against the new one.
