### ISSUE TITLE
Use incumbent global's origin for postMessage instead of document's

### ISSUE THREAD

**Issue by jdm** [servo/servo#18969]
There is a [TODO comment](https://dxr.mozilla.org/servo/rev/7b61e3b6ee62a96f151483f4fc229fa0c03a54d8/components/script/dom/window.rs#768) in the implementation of Window::PostMessage that we can now address. This refers to step 4 of [the standard](https://html.spec.whatwg.org/multipage/web-messaging.html#dom-window-postmessage), and we can now use the [incumbent_global](https://dxr.mozilla.org/servo/rev/7b61e3b6ee62a96f151483f4fc229fa0c03a54d8/components/script/dom/bindings/settings_stack.rs#145) helper function and [get an origin](https://dxr.mozilla.org/servo/rev/7b61e3b6ee62a96f151483f4fc229fa0c03a54d8/components/script/dom/globalscope.rs#263) from that.

I would hope that running `./mach test-wpt tests/wpt/web-platform-tests/webmessaging/` would report [unexpected test results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) as a result of making this change.

**Comment by tigercosmos** [comment]
related #12715

**Comment by jdm** [comment]
Turns out we don't run the webmessaging tests yet.

**Comment by tigercosmos** [comment]
I  do not understand this. @jdm
> Turns out we don't run the webmessaging tests yet.

**Comment by KiChjang** [comment]
@jdm means that we currently do not run the tests under [this directory](https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/webmessaging).

**Comment by tigercosmos** [comment]
If someone want to work on this issue, should also change  [`/tests/wpt/web-platform-tests/lint.whitelist` ](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/lint.whitelist#L255)?
```
SET TIMEOUT: webmessaging/*
```

**Comment by KiChjang** [comment]
@tigercosmos I suggest not to work on this issue, since most of the tests fail under that directory. If we enable them haphazardly, it would consume merge times on our current build infrastructure.

**Comment by jdm** [comment]
@tigercosmos No, that's the list of allowed warnings for the style linting tool. The tests we run are controlled by https://github.com/servo/servo/blob/master/tests/wpt/include.ini.
