### ISSUE TITLE
DuckDuckGo search button colour flickering

### ISSUE THREAD

**Issue by atouchet** [servo/servo#18978]
URL: https://duckduckgo.com/

Steps to reproduce:

1. Move mouse cursor over the search button to make it turn green.
2. Move the cursor around without leaving the search button.
3. The button will then flicker various colours between white and green instead of just remaining green.

I believe this may be a somewhat recent regression as I do not remember running into it in the past. Tested in Windows 10.

**Comment by atouchet** [comment]
This may be related to #19052. I notice that the colour only flickers when the mouse is also not over the magnifying glass icon. Moving the mouse also sometimes makes the button unclickable even if the cursor is still above the search button.

**Comment by bobthekingofegypt** [comment]
I created a sample page that appears to show how the presence of border-radius causes the flickering effect.

https://gist.github.com/bobthekingofegypt/579dac0a93acb4f55a4d720294836acb

**Comment by atouchet** [comment]
This issue also affects the hamburger menu button on the same page.

**Comment by atouchet** [comment]
This appears to be fixed now.
