### ISSUE TITLE
Create a mach command that automatically removes *.orig files

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#18985]
Ever since we've added the rule to ignore *.orig files to .gitignore, my system has been accumulating *.orig files from merge conflicts. It would be nice if we can run a command on mach that removes these.

**Comment by jdm** [comment]
It's not clear to me that a mach command for this makes more sense than running `find . -name \*.orig | xargs rm -v`.

**Comment by KiChjang** [comment]
Perhaps we should also include it in `./mach clean` instead? I just want to have an automated way of cleaning up these leftover files after a rebase.

**Comment by SimonSapin** [comment]
For what it’s worth, `git mergetool` will remove relevant `.orig` files after helping resolve conflicts.

**Comment by KiChjang** [comment]
@SimonSapin Curious, that's exactly what I used, but my `.orig` files are not removed.

**Comment by SimonSapin** [comment]
Hmm, perhaps it’s kdiff3’s doing then? I use `git mergetool -t kdiff3`.

**Comment by KiChjang** [comment]
https://git-scm.com/docs/git-mergetool#_temporary_files

> Setting the `mergetool.keepBackup` configuration variable to `false` causes `git mergetool` to automatically remove the backup as files are successfully merged.
