### ISSUE TITLE
Figure out why navigation_start_precise and paint timing metrics are f64

### ISSUE THREAD

**Issue by jdm** [servo/servo#18997]
As far as I can tell, all of the code that originally provides a value for these matrics casts a u64 to an f64, and I cannot figure out why.

**Comment by avadacatavra** [comment]
I think I've figured it out:

```
error[E0277]: the trait bound `u64: num_traits::Float` is not satisfied
  --> /Users/ddh/mozilla/servo/servo-0/components/script/dom/performanceentry.rs:77:5
   |
77 | /     fn Duration(&self) -> Finite<u64> {
78 | |         Finite::wrap(self.duration)
79 | |     }
   | |_____^ the trait `num_traits::Float` is not implemented for `u64`
   |
   = note: required by `dom::bindings::num::Finite`
```

For PaintTimeMetrics, the metric is sent on to PerformancePaintTiming, which is sent to  PerformanceEntry, which uses dom::bindings::num::Finite, which apparently requires a float (and that's when I stopped digging)

* https://dxr.mozilla.org/servo/source/components/script/dom/performanceentry.rs#15
* https://w3c.github.io/performance-timeline/#dom-performanceentry-duration

**Comment by jdm** [comment]
In that case, it probably makes sense to store everything as a u64 internally and cast to an f64 in the one place that actually wants a floating point value.

**Comment by avadacatavra** [comment]
Agree -- should I lump that into https://github.com/servo/servo/pull/18670 or do it in a separate PR

**Comment by jdm** [comment]
I think separately makes sense.
