### ISSUE TITLE
Move border-image-repeat outside of mako.

### ISSUE THREAD

**Issue by mauricioc** [servo/servo#19021]
I'll start with the easy one. See Issue #19015.

**Comment by emilio** [comment]
@mauricioc any progress here? Let us know if we should unassign the issue. Thanks!

**Comment by mauricioc** [comment]
Sorry, this totally fell off my radar, I'll get back to it now. Feel free to unassign me if this isn't done by Monday :)

**Comment by mauricioc** [comment]
Closing (see last comment of PR #19668).

**Comment by atouchet** [comment]
This issue can stay open until that PR is merged.

**Comment by mauricioc** [comment]
Typically yes, but there's issue #19142 already :)
