### ISSUE TITLE
Testing Failed - "OffscreenCanvas is not defined" 

### ISSUE THREAD

**Issue by gauraangkhurana** [servo/servo#19037]
Hi Community,

Quick Intro: I am a developer trying my hands on servo for the first time (OffscreenCanvas & OffscreenCanvasRenderingContext2D).
 
I followed the exact steps given on the [page](https://github.com/servo/servo/wiki/Offscreen-canvas-project), which are:

1. create the OffscreenCanvas and OffscreenCanvasRenderingContext2d interfaces with stub method implementations
hide the new interfaces by default by adding a [Pref="dom.offscreen_canvas.enabled"] attribute to each one and add a corresponding preference to resources/prefs.json
### (Implemented the 'impl  OffscreenCanvas{ } and impl OffscreenCanvasMethods for OffscreenCanvas {} taking inspiration from HTMLCanvasElement and CanvasRenderingContext2D. )

2. enable the existing automated tests for this feature by adding the offscreen-canvas directory to tests/wpt/include.ini
add a __dir__.ini file to tests/wpt/metadata/offscreen-canvas which enables the new preference, then run the tests in that directory and update the expected test results.

When I try to run the tests, all the tests fail and the error stated is : 

```
Unexpected subtest result in /offscreen-canvas/compositing/2d.composite.canvas.copy.worker.html:
  │ FAIL [expected PASS] Untitled
  │   → OffscreenCanvas is not defined
  │ 
  │ @http://web-platform.test:8000/offscreen-canvas/compositing/2d.composite.canvas.copy.worker.js:12:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  └ @http://web-platform.test:8000/offscreen-canvas/compositing/2d.composite.canvas.copy.worker.js:10:1
```

I have been trying to debug this problem for quite some time now but haven't been able to figure out the exact reason behind it. 
Would appreciate any help offered in this case. 

Thanks in advance !!

**Comment by jdm** [comment]
It's hard to debug this without a link to the code that you're running. I saw that https://github.com/servo/servo/pull/19012 was opened, but it doesn't actually compile, so I'm not sure if it's relevant or not. I would expect the tests to fail in this manner if you are not using a build of Servo that has the OffscreenCanvas WebIDL interface present.

**Comment by gauraangkhurana** [comment]
Hey guys, had another good day working on the servo project and learning new cool things. 

So I figured what was going wrong yesterday. I am afraid, I wasn't running the the proper build before trying to run the tests. Perhaps that explains the errors.

Anyway, I was going through the code again today and made a lot of new changes to it to get the API up and running.

However, I think I would really appreciate some help now as I am stuck and can't make any sense of this particular error.

When I run `./mach build -d` , the error I see is, 

`error[E0277]: the trait bound `dom::offscreencanvas::OffscreenCanvas: dom::bindings::conversions::DerivedFrom<dom::element::Element>` is not satisfied
  --> /Users/Isha/Documents/oodd/AssignmentCode/Assignment3/OSS_Project/servo/components/script/dom/macros.rs:87:32
   |
87 |             let element = self.upcast::<Element>();
   |                                ^^^^^^ The IDL interface `dom::offscreencanvas::OffscreenCanvas` is not derived from `dom::element::Element`.
   | 
  ::: /Users/Isha/Documents/oodd/AssignmentCode/Assignment3/OSS_Project/servo/components/script/dom/offscreencanvas.rs
   |
78 |     make_uint_getter!(Width, "width", DEFAULT_WIDTH);
   |     ------------------------------------------------- in this macro invocation
   |
   = help: the trait `dom::bindings::conversions::DerivedFrom<dom::element::Element>` is not implemented for `dom::offscreencanvas::OffscreenCanvas``

DO you make any sense of this ? Kindly tell me where do you think I am going wrong.

I have also uploaded the code for you to view. I created a [pull request](https://github.com/servo/servo/pull/19046) for the same. 

Hoping to hear from you soon !!
Thanks in advance !!

**Comment by emilio** [comment]
Yes, you cannot use `make_uint_getter!` in `offscreencanvas.rs`. That macro is for elements (it assumes that the `Width` comes from the canvas HTML element).

So you probably want to define it following the spec, or just returning a dummy value for now, like:

```rust
fn Width(&self) -> u32 {
    DEFAULT_WIDTH
}
```

**Comment by gauraangkhurana** [comment]
Hey  Emilio, thanks for your suggestion. It worked like a charm.

I learnt more about the project today and made some changes to my code.
From 35 errors, I brought them down to 3 by making the appropriate changes in the files.

Unfortunately I am not able to find a solution to these 3 errors even after having spent half the day.
The issues reside in the OffscreenCanvas Constructor, as per my understanding.


Can someone please help me resolve these errors.

```
error[E0308]: mismatched types
  --> /Users/Isha/Documents/oodd/AssignmentCode/Assignment3/OSS_Project/servo/components/script/dom/offscreencanvas.rs:62:66
   |
62 |                           height: u64) -> DomRoot<OffscreenCanvas> {
   |  __________________________________________________________________^
63 | |
64 | |         //Ok(OffscreenCanvas::new())
65 | |
66 | |           }
   | |___________^ expected struct `dom::bindings::root::Root`, found ()
   |
   = note: expected type `dom::bindings::root::Root<dom::bindings::root::Dom<dom::offscreencanvas::OffscreenCanvas>>`
              found type `()`

error[E0061]: this function takes 2 parameters but 3 parameters were supplied
   --> /Users/Isha/Documents/oodd/AssignmentCode/Assignment3/OSS_Project/servo/target/debug/build/script-2e967606b2320cbe/out/Bindings/OffscreenCanvasBinding.rs:884:92
    |
884 |           let result: Result<DomRoot<OffscreenCanvas>, Error> = OffscreenCanvas::Constructor(&global, arg0, arg1);
    |                                                                                              ^^^^^^^^^^^^^^^^^^^ expected 2 parameters
    | 
   ::: /Users/Isha/Documents/oodd/AssignmentCode/Assignment3/OSS_Project/servo/components/script/dom/offscreencanvas.rs
    |
61  | /     pub fn Constructor( width: u64,
62  | |                         height: u64) -> DomRoot<OffscreenCanvas> {
63  | |
64  | |         //Ok(OffscreenCanvas::new())
65  | |
66  | |           }
    | |___________- defined here

error[E0308]: mismatched types
   --> /Users/Isha/Documents/oodd/AssignmentCode/Assignment3/OSS_Project/servo/target/debug/build/script-2e967606b2320cbe/out/Bindings/OffscreenCanvasBinding.rs:884:63
    |
884 |         let result: Result<DomRoot<OffscreenCanvas>, Error> = OffscreenCanvas::Constructor(&global, arg0, arg1);
    |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                                               |
    |                                                               expected enum `serde::export::Result`, found struct `dom::bindings::root::Root`
    |                                                               help: try using a variant of the expected type: `serde::export::Ok(<OffscreenCanvas>::Constructor(&global, arg0, arg1))`
    |
    = note: expected type `serde::export::Result<dom::bindings::root::Root<_>, dom::bindings::error::Error>`
               found type `dom::bindings::root::Root<_>`

error: aborting due to 3 previous errors

```

1. I don't follow as to how to return a Domroot<OffscreenCanvas> dummy Element.
2/3. The implementation on the [webpage](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/OffscreenCanvas) clearly states there will be two parameters. But unfortunately, it isn't working and I can't figure out the reason.

I would really appreciate your help.
Here is the [pull request ](https://github.com/servo/servo/pull/19053)for you to view my changes.

Thanks in advance !!

**Comment by jdm** [comment]
Reopening under the assumption that this was closed accidentally.

**Comment by jdm** [comment]
Your Constructor method is missing a &GlobalScope argument, and it should return a `Result<DomRoot<OffscreenCanvas>>`. You will need to define a `new` method for OffscreenCanvas that your Constructor calls. For prototyping purposes when you want to just fix compiler error, you can use `unimplemented!()` to work around problems where you're not sure what value to return at the moment.
