### ISSUE TITLE
Servo shows only white page on integrated GPU

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#19049]
I tested it on my laptop with nvidia optimus. When i run servo with integrated GPU(default option) nothing's rendered. It works fine with nVidia GPU.

![servo](https://user-images.githubusercontent.com/10187350/32134304-c487fc90-bbea-11e7-93a3-94abca6e45e0.png)

iGPU: Intel HD Graphics 4600
dGPU: nVidia GeForce GTX760M
OS: Windows 8.1 x64

Drivers:
nVidia: 387.92
Intel: 10.18.10.3308

**Comment by emilio** [comment]
cc @glennw

**Comment by BillGoldstein** [comment]
First showed up for me with 26th's nightly (so perhaps related to WEBGL2.0 ?) Win10 x64

**Comment by BillGoldstein** [comment]
Just tried Oct 31's nightly, and problem is fixed for me.

**Comment by gregkatz** [comment]
Fixed for me as well.

**Comment by blacksvk** [comment]
Fixed for me as well. This issue can be closed.
