### ISSUE TITLE
Hit detection issue with duckduckgo.com/html search button

### ISSUE THREAD

**Issue by atouchet** [servo/servo#19052]
URL: https://duckduckgo.com/html/

On the duckduckgo.com/html main page the entire search button should be clickable but in Servo it is only clickable when the mouse is above the edges of the button or above the magnifying glass icon. The button is not clickable otherwise. Tested in Windows 10 with Browser.html.

**Comment by bobthekingofegypt** [comment]
I created a sample page that appears to show how the presence of border-radius causes the hit detection issue.

https://gist.github.com/bobthekingofegypt/579dac0a93acb4f55a4d720294836acb

**Comment by atouchet** [comment]
This is fixed now although there are still some issues with the button on the search page.

**Comment by bobthekingofegypt** [comment]
Incase it comes up again and someone looks back at this, this was fixed by #19169 which contains an update to webrender.

This diff https://github.com/servo/webrender/compare/aa74cdfc...3a0ddfc5 should cover the relavant commits from the WR release.  Something in there fixed the issue.
