### ISSUE TITLE
Implement everything in htmlinputelement.rs

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#1906]
The [DOM class for `<input>`](https://github.com/mozilla/servo/blob/master/src/components/script/dom/htmlinputelement.rs#L173) is pretty empty. Let's fill it up!

**Comment by frewsxcv** [comment]
This could probably be closed in favor of #7004? I don't really see the point in keeping either of them open really

**Comment by KiChjang** [comment]
My preference is to keep issues and PRs small; so instead we may make #7004 a metabug to track all missing DOM class implementations.

**Comment by jdm** [comment]
Yeah, this doesn't really hold much value in its present state.
