### ISSUE TITLE
Download failed during build

### ISSUE THREAD

**Issue by olmanz** [servo/servo#19075]
Hello, I am new to Rust but I'm interested in contributing to this Open Source project.

I followed the instructions on README.md and cloned this repo just to check if I can run Servo (I am using Ubuntu 16.04), but when I execute

./mach check

I get the following error message:

Looking for rustc at /home/omanz/Rust/OpenSource/servo/.servo/rust/2017-10-13-alt/rustc-nightly-i686-unknown-linux-gnu/rustc/bin/rustc
Downloading https://s3.amazonaws.com/rust-lang-ci/rustc-builds-alt/dcbbfb6e807fdff9c9ba80073bb755f9d9d95e31/rustc-nightly-i686-unknown-linux-gnu.tar.gz ...
Download failed (404): Not Found - https://s3.amazonaws.com/rust-lang-ci/rustc-builds-alt/dcbbfb6e807fdff9c9ba80073bb755f9d9d95e31/rustc-nightly-i686-unknown-linux-gnu.tar.gz

That download link does not exist. Is there a known solution to this problem?

Thank you in advance.

**Comment by jdm** [comment]
What operating system are you using? That usually happens when there is a problem determining the OS.

**Comment by jdm** [comment]
Oh, you said Ubuntu 16.04. That's odd. It would be useful to see what `platform.system` and `platform.machine` report from python in this code: https://github.com/servo/servo/blob/master/python/servo/util.py#L46-L77

**Comment by SimonSapin** [comment]
This is a bug. https://github.com/servo/servo/pull/19076 should fix it. In the meantime, you can copy `servobuild.example` to `.servobuild` and set `llvm-assertions = true`.
