### ISSUE TITLE
Fix TTI logic

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#19099]
At some point in time during the review/rebase process for #18670, I seem to have deleted and missed setting the navigation start for the time to interactive metric.

In hunting down this problem, I'm also suspicious that the window logic may be faulty. I have a local experiment to fix this, but need to figure out what went wrong.

I also need to refer to gecko/chrome spec/implementation again, because the way we've implemented tti, you can't know what it is until you've been on a page for at least 10s (requires a 10s window)--this has not been the case when I try in other browsers. I'm suspicious that domInteractive is simply domContentLoaded fired (https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/domInteractive). It's possible that I missed something, and there's a performance timing metric that I should be using instead (I've been using performance.timing.domInteractive and performance.timing.ConnectStart to calculate TTI)

cc @jdm

**Comment by jdm** [comment]
The domInteractive property is very different from the Time to Interactive metric - it is when page stops being parsed, like you speculated. I don't see any way to avoid the 10s delay before the metric is available, since we require a 10s window of availability before we can classify it.

**Comment by jdm** [comment]
Firefox has not implemented TTI yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1299118

**Comment by avadacatavra** [comment]
It looks like chrome has? https://github.com/GoogleChrome/lighthouse/pull/450

**Comment by jdm** [comment]
https://github.com/GoogleChromeLabs/tti-polyfill is probably relevant. Looks like it's possible to measure TTI via JS in Chrome via the PerformanceObserver API.

**Comment by avadacatavra** [comment]
And yes, based on the spec, I don't see a way to avoid it. It looks like the chrome pr is from June 16, and then I see https://docs.google.com/document/d/1jbvwxj_GJtiTTqFM8dsVzCIy5XeKL5qtIAvuimcXb1o/edit from Dec...not sure if there's anything more recent?

**Comment by avadacatavra** [comment]
it looks like this is the most recent: https://docs.google.com/document/d/1GGiI9-7KeY3TPqS3YT271upUVimo-XiL5mwWorDUD4c/preview#

Should fix what we have and make a followup for consistently interactive
