### ISSUE TITLE
`overflow_query` in `windows.rs`

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19125]
I don't know why here only use `overflow_x`, how about `overflow_y`?
https://github.com/servo/servo/blob/88505dc2ffc31efa614e1a5070a9bc23feded30a/components/script/dom/window.rs#L1403-L1411

**Comment by jdm** [comment]
overflow_x and overflow_y share the same type, so the Point2D value actually contains overflow_x and overflow_y values.

**Comment by tigercosmos** [comment]
Got it. Thanks!
