### ISSUE TITLE
Top row of Browser.html homescreen site tiles are not clickable

### ISSUE THREAD

**Issue by atouchet** [servo/servo#19131]
Steps to reproduce:

1. Run Servo using Browser.html.
2. Try to click one of the top row of website tiles from the homescreen.
3. Nothing happens.

I believe this is a regression from the past day or so as I did not experience this behaviour previously. Tested in Windows 10.

**Comment by atouchet** [comment]
The left sides of the leftmost column tiles also have issues. They are not clickable either.

**Comment by jdm** [comment]
```html
<!DOCTYPE html>
<html>
<style>
  .tiles {
  width: 420px;
  height: 480px;
  overflow: hidden;
  position: absolute;
  left: calc(50% - 840px / 2);
  top: calc((100% + 60px) / 2 - 480px / 2);
  }
  .tile {
  cursor: pointer;
  float: left;
  width: 160px;
  }
  .tile-image {
  border: 1px solid rgba(0, 0, 0, 1.0);
  height: 100px;
  width: 160px;
  }
</style>
<div class="tiles">
  <a class="tile">
    <div class="tile-image"></div>
  </a>
  <a class="tile">
    <div class="tile-image"></div>
  </a>
  <a class="tile">
    <div class="tile-image"></div>
  </a>
  <a class="tile">
    <div class="tile-image"></div>
  </a>
</div>
```
Here's a minimal reduction of https://github.com/servo/servo.org/blob/gh-pages/bhtml-newtab/newtab.html. @mrobinson Is this something that you're able to look at?

**Comment by mrobinson** [comment]
This should be fixed soon when https://github.com/servo/webrender/pull/2040 lands and WebRender is updated. This regressed due to an unrelated change in the coordinate system of ClipScrollNodes in WebRender.

**Comment by atouchet** [comment]
This is fixed now.
