### ISSUE TITLE
webgl: Implement toDataURL()

### ISSUE THREAD

**Issue by anholt** [servo/servo#19147]
I'm starting on this, as it's the source of a lot of errors in the webgl conformance tests.  Open questions so far:

- Can I safely assume that the canvas's Width() and Height() match the offscreen_gl_context's FBO width and height?
- What do I need to do as the equivalent of 2d canvas's origin handling?

This is part of #10209

**Comment by jdm** [comment]
With respect to the origin handling, https://www.khronos.org/registry/webgl/specs/latest/1.0/#4.2 seems like the relevant section here. The note that "these rules imply that the origin-clean flag for a canvas rendered using WebGL will never be set to false" seems particularly interesting.

**Comment by anholt** [comment]
Added a citation of that spec text.

**Comment by nox** [comment]
I'm looking into this today, apparently all the `/_mozilla/webgl/conformance-1.0.3/conformance/glsl/` tests error after 20 seconds because this isn't implemented.
