### ISSUE TITLE
Move border-image-repeat outside of mako.

### ISSUE THREAD

**Issue by emilio** [servo/servo#19142]
As part of #19015

**Comment by emilio** [comment]
@chansuke, would you be interested in taking this? Sorry for the lag!

**Comment by chansuke** [comment]
@emilio Yes!Let me try this

**Comment by emilio** [comment]
Awesome, thanks! Let me know if you need any help :)

**Comment by chansuke** [comment]
@emilio Thanks.I implemented almost everything and will send a PR.I want to ask a question about [Computed value](https://drafts.csswg.org/css-backgrounds/#propdef-border-image-repeat).
The document says `two keywords, one for each axis` so I implemented like below but I'm not sure 
this is a right approach for `components/style/values/computed/border.rs`.

```
/// A computed value for the `border-image-repeat` property.
pub type BorderImageRepeat = GenericBorderImageRepeat<Stretch, Repeat, Round, Space>;
~~~~~~~~~~~
impl BorderImageRepeat {
    pub fn repeat() -> Self {
        BorderImageRepeat(RepeatKeyword::horizontal, RepeatKeyword::vertical)
    }
}
```

Or,Need an another approach for that? Thank you.

**Comment by emilio** [comment]
Hmm, I don't understand that, why would you use generics for that? There is a single keyword, so I was expecting something just like:

```rust
pub struct BorderImageRepeat(RepeatKeyword, RepeatKeyword);

impl BorderImageRepeat {
    pub fn repeat() -> Self {
        BorderImageRepeat(RepeatKeyword::Repeat, RepeatKeyword::Repeat)
    }
}
```

Anyway, feel free to open a PR so we can comment on the code itself :)

**Comment by chansuke** [comment]
@emilio Thank you for the comment:)I will fix it and send a PR.

**Comment by jdm** [comment]
Yes.
