### ISSUE TITLE
Update document URL when a new history state is pushed/replaced

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#19157]
Part of #10992

https://html.spec.whatwg.org/multipage/#dom-history-pushstate Step 10

**Comment by talklittle** [comment]
I worked on this and submitted a PR #20453 since I didn't see a `C-Assigned` label on the issue. But now I realized the issue is assigned. Sorry for not asking first.

**Comment by cbrewster** [comment]
No worries, I've been a bit busy and should've unassigned myself.
