### ISSUE TITLE
Have live collections being updated by signals, not by traversing node tree

### ISSUE THREAD

**Issue by brunoabinader** [servo/servo#1916]
Currently, ```NodeList``` relies on traversing the root node's children tree each times it needs to gather some information (i.e. ```item(index)```, or ```length()```). This is also the case for ```HTMLCollection```.

By using signals to inform collections whenever a node state change occurs (i.e. attribute change, node append/remove/clone/etc), we can then achieve O(n) for most operations.

**Comment by KiChjang** [comment]
Fixed by #8227.
