### ISSUE TITLE
CharacterData should call children_changed on the parent node consistently.

### ISSUE THREAD

**Issue by emilio** [servo/servo#19177]
Right now it only does it from `SetData`, not from `AppendData` or `ReplaceData`.

The block at:

https://github.com/servo/servo/blob/a3f2fae561de26fefb0ac0d569ce2c7a2942eee5/components/script/dom/characterdata.rs#L91-L99

Should instead move to `fn content_changed`.

Here's a test-case that will fail after #19164:

```html
<!doctype html>
<div>FAIL</div>
<script>
document.body.offsetTop;
document.querySelector('div').firstChild.replaceData(0, 4, "PASS");
</script>
```

**Comment by CYBAI** [comment]
@highfive: assign me

**Comment by emilio** [comment]
I just checked and that test-case passes, but this one does not:

```html
<!doctype html>
<style>.fail { color: green }</style>
<div class="pass">Should be green</div>
<script>
document.body.offsetTop;
document.querySelector('style').firstChild.replaceData(1, 4, "pass");
</script>
```

**Comment by tigercosmos** [comment]
@emilio Does the test already exist? or @CYBAI would need to add one?

**Comment by emilio** [comment]
It probably doesn't, so it will need to get added to web-platform-tests.

**Comment by CYBAI** [comment]
Got it. Please let me create a wpt test for it.
I think I need to add it under `tests/wpt/web-platform-tests/dom/nodes` as a `CharacterData-replaceData-pass.html`?

**Comment by tigercosmos** [comment]
I think under `tests/wpt/mozilla/tests` might be suitable. 
Since `tests/wpt/web-platform-tests/` will sync with upstream.

**Comment by emilio** [comment]
Nope, let's not add it to `mozilla/`, this test isn't testing anything specific to Servo, so `tests/wpt/web-platform-tests` should be fine, the tests are synced two-way.

**Comment by tigercosmos** [comment]
Thanks XD

**Comment by emilio** [comment]
This is also not testing a DOM API per se, but just the CSS dynamic behavior, so `web-platform-tests/css/cssom/` may be a better directory, but no big deal.

**Comment by CYBAI** [comment]
Great! Thanks for pointing to the `cssom` directory.
I think it's better to move it under it.

**Comment by tigercosmos** [comment]
@emilio  What case should I put under `mozilla`, such as `tests/wpt/mozilla/tests/css/cssom/`?
How to define "related to servo"?

**Comment by CYBAI** [comment]
IMO, internal attributes or features might be `related to Servo` but this one is related to common node changed logic. Thus, I think that's why emilio think it might be better to put it under `tests/wpt/web-platform-tests `.

**Comment by tigercosmos** [comment]
I see. Good point!
