### ISSUE TITLE
Webrender: Weird text bug

### ISSUE THREAD

**Issue by qwertychouskie** [servo/servo#19191]
https://jacobspctuneup.tk/STK/newgui/mainmenu.html

How it looks
![](http://i.imgur.com/OLCcTPj.png)

How it should look
![](http://i.imgur.com/Qab3mRL.png)

FF Nightly 2107/11/11

```
gfx.webrender.enabled:true
gfx.webrender.blob-images:true
```

**Comment by atouchet** [comment]
If this is exclusively a WebRender bug you might want to report the issue here: https://github.com/servo/webrender

**Comment by qwertychouskie** [comment]
@atouchet Opened https://github.com/servo/webrender/issues/2029, thanks.
