### ISSUE TITLE
Can't click on any of the top row of the showcase

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#19196]
You can't seem to be able to click on DuckDuckGo, GitHub, Wikipedia, or Ars Technica in recent Servo builds.

![screen shot 2017-11-13 at 12 42 09 pm](https://user-images.githubusercontent.com/547158/32704806-50ea4af8-c870-11e7-8170-bb48f37c0fec.png)

**Comment by atouchet** [comment]
I've already opened an issue for this in #19131.

**Comment by jonathandturner** [comment]
@atouchet - Ah, didn't see it. Apologies for the noise.
