### ISSUE TITLE
Resizing Servo window vertically causes second scrollbar to appear

### ISSUE THREAD

**Issue by atouchet** [servo/servo#19209]
Steps to reproduce:

1. Load site that can scroll vertically in Servo.
2. Resize the Servo window vertically to make it shorter.
3. A second scrollbar will appear.

Tested in Windows 10 with Browser.html.

Image of issue:

![Scrollbars](https://i.imgur.com/mN2MVua.png)

**Comment by nc4rrillo** [comment]
Seems  to only happen with browserhtml. I think it may be related to https://github.com/servo/webrender/pull/2018

That change fixed scrollbars appearing on iframes (which I think browserhtml uses), and I'd bet that they appear unconditionally without respecting something like `overflow: hidden` 

I've also noticed on some sites, ads have scrollbars too where they previously didn't, and those typically use iframes as well.

**Comment by atouchet** [comment]
@nc4rrillo I believe I have seen the issue come up before https://github.com/servo/webrender/pull/2018 was merged. However before https://github.com/servo/webrender/pull/2018 scrollbars didn't work properly in Windows with Browser.html so they were only visible at all after resizing the window. I didn't report the issue previously because I didn't know what the expected scrollbar behavior was supposed to be at the time.

**Comment by atouchet** [comment]
This is no longer an issue with Browser.html removed.
