### ISSUE TITLE
Report time spent in synchronous IPC to the profiler

### ISSUE THREAD

**Issue by jdm** [servo/servo#19223]
There are various parts of the code where we send a message to another thread, and as part of that message we include an `IpcSender` (or just a `Sender`) value that allows the other thread to send a response. In general the initiator of the message will immediately call `recv()` on the corresponding receiver, meaning that the thread will block until it receives a message. It would be valuable to report when this happens to the built-in [profiler](https://github.com/servo/servo/wiki/Profiling#generating-timelines) so it's easier to see how often it affects performance. We should build a wrapper around the `Receiver` and `IpcReceiver` types that automatically [profile](https://github.com/servo/servo/blob/d7b4471c8080c0916277b967994bffcade759c3a/components/profile_traits/time.rs#L112) the synchronous receive operation so it's easy to get this information in the future.

Examples of use:
* https://github.com/servo/servo/blob/504ad4de2a426c2bc70161a9190fddaa8728ead2/components/script/dom/screen.rs#L40-L42
* https://github.com/servo/servo/blob/0e62a5829b7c29ae2667a21a439aff1e89201bf3/components/script/dom/storage.rs#L57-L58
* https://github.com/servo/servo/blob/4c538b642e4bdfbf42c522c5a59c258a6d14546e/components/script/dom/webglprogram.rs#L53-L55

In general, cases of `recv()` (but not `try_recv()`) in components/script are suspect.

**Comment by jonathanKingston** [comment]
I will take this in my spare time, if that is ok?

To clarify "wrapper around the `Receiver` and `IpcReceiver` types that automatically profile" do you mean perhaps creating "servo/components/ipc/receiver.rs" and implementing the methods on `IpcReceiver` and `Receiver` with profile calls in each method?

PseudoCode:
```
impl<T> IpcReceiver<T> where T: for<'de> Deserialize<'de> + Serialize {
    pub fn recv(&self) -> Result<T, bincode::Error> {
        let receiver;
        profile(time::ProfilerCategory::IpcReceiver,
                metadata.clone(),
                sender.clone(),
                || { receiver = ipc_channel::ipc::IpcReceiver; })
    }
    ...
}
```

Then change the calls to use this instead?

If that isn't the case do you have any examples of wrapping calls?

**Comment by jdm** [comment]
That's the idea, although creating it in components/profile_traits/ probably makes more sense. Additionally, adding a `channel` function that creates a new pair of sender/wrapped receiver would make it easy to update code to use the new type.

**Comment by jdm** [comment]
Opening this up to other people to work on, since it's been three months without any activity.

**Comment by nakul02** [comment]
@jdm - I wanted to give this a try. 
Needed a little help:
I am struggling trying to find a way to get a reference to the `ProfilerChan` object defined in `servo::new` to pass into the `profile_traits::time::profile` function.

**Comment by jdm** [comment]
@nakul02 The idea would be that instead of calling `ipc::channel::new()`, we would call a different function that accepted the `ProfilerChan` object as an argument, and return a structure that contains the actual IPC receiver as well as the ProfilerChan object. We then need to make sure that the ProfilerChan is available in each place we call the new constructor function. Does that make sense?

**Comment by nakul02** [comment]
@jdm - What I've done so far is this:
https://github.com/servo/servo/compare/master...nakul02:issue_19223
So the `ProfilerChan` being available wherever the new `channel` function makes sense. Although, for the examples you've posted, `servo/components/script/dom/screen.rs` & `servo/components/script/dom/storage.rs`, I couldn't find a way to get a handle of the `ProfilerChan` object that is instantiated in `servo::new` down into either of these files. That is what I need help with.

**Comment by jdm** [comment]
GlobalScope allows retrieving the channel: https://github.com/servo/servo/blob/master/components/script/dom/globalscope.rs#L266. In both cases, you can use `self.global()` to obtain the GlobalScope associated with the DOM object.

**Comment by nakul02** [comment]
I have a WIP PR #20132 for this.
