### ISSUE TITLE
Cannot show Chinese correctly (Servo, Facebook, Yahoo, etc.)

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19228]
Tested in Ubuntu 16.04 with recent commit in master.

```
 ./mach run https://servo.org/zh-TW/index.html
```
It can show correctly on the browser top, but cannot show characters in HTML content 
![image](https://user-images.githubusercontent.com/18013815/32839438-65d8dffc-ca4f-11e7-9148-09c8c760935f.png)

It's also weird. Although many CJK pages cannot run well, some CJK pages can show correctly?

related to #18202

**Comment by tigercosmos** [comment]
Chinese Facebook
the browser top also show right, and the content scannot show Chinese.
![image](https://user-images.githubusercontent.com/18013815/32839886-e50e9342-ca50-11e7-91d9-e3d7e7400fd6.png)

**Comment by tigercosmos** [comment]
Chinese Yahoo!
Not just characters, the layout is broken as well.
![image](https://user-images.githubusercontent.com/18013815/32840262-1aa2a678-ca52-11e7-9b42-30a71fcd382e.png)

**Comment by tigercosmos** [comment]
Chinese Google
![image](https://user-images.githubusercontent.com/18013815/32840399-7aaf6fa6-ca52-11e7-98b7-1868e31f2518.png)

**Comment by jdm** [comment]
Looks like this is already covered by https://github.com/servo/servo/issues/10045.

**Comment by tigercosmos** [comment]
Can close this one

**Comment by tigercosmos** [comment]
@jdm But why some page run well, such as #6167

**Comment by jdm** [comment]
Good question!
