### ISSUE TITLE
CSS value content: url(url) do not seems to be working.

### ISSUE THREAD

**Issue by ocerman** [servo/servo#19248]
![contenturl](https://user-images.githubusercontent.com/10187350/32887258-9ae944a6-cac3-11e7-9e51-4c99a63eaba5.png)
```
<!DOCTYPE html>
<html>
	<head>
		<style>
			p:before{
				content: url(https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Coat_of_arms_of_Slovakia.svg/15px-Coat_of_arms_of_Slovakia.svg.png)
			}
		</style>
	</head>
	<body>
		<p>Lorem ipsum dolor sit amet...</p>
	</body>
</html>
```

**Comment by nox** [comment]
We don't support SVG yet.

**Comment by KiChjang** [comment]
Looking through the code, I see that we don't actually support urls in the `content` property yet for servo.

**Comment by mrobinson** [comment]
This is working in non-legacy layout.
