### ISSUE TITLE
Make typed arrays safe

### ISSUE THREAD

**Issue by jdm** [servo/servo#19241]
https://github.com/servo/servo/pull/15672 was work towards this. I don't remember the exact motivation at the moment.

**Comment by Xanewok** [comment]
https://github.com/servo/servo/pull/20267 and https://github.com/servo/rust-mozjs/pull/397 introduce support for typed arrays using Box<Heap<*mut JSObject>> variant (in addition to stack-rooting using CustomAutoRooter).

**Comment by jdm** [comment]
Good enough!
