### ISSUE TITLE
Implement EventTarget constructor

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#19283]
https://github.com/whatwg/dom/pull/467

**Comment by KiChjang** [comment]
Code: `components/script/dom/EventTarget.rs`, `components/script/dom/webidl/EventTarget.webidl`
Test: `tests/wpt/web-platform-tests/dom/events/EventTarget-constructible.any.js`

**Comment by m-novikov** [comment]
I would like to try it out. @highfive : assign me
