### ISSUE TITLE
error: no matching package named `js` found

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#19295]
When compiling Servo as a dependency, I get this error after copying Servo's Cargo.lock into my project:

```
error: no matching package named `js` found (required by `script`)
location searched: https://github.com/servo/rust-mozjs
version required: *
```

**Comment by CYBAI** [comment]
I think `js` should have been renamed to `mozjs` after #19138 merged?

**Comment by paulrouget** [comment]
Problem was on my side. Please ignore.

**Comment by paulrouget** [comment]
For the record: I was using a Cargo.lock from a version of Servo that was more recent that the one I was referencing in my Cargo.toml.
