### ISSUE TITLE
Report an error if a package has duplicates allowed but there are no duplicates

### ISSUE THREAD

**Issue by jdm** [servo/servo#19306]
In servo-tidy.toml there is a `[ignore]` section that lists package names that are allowed to have duplicate versions in Cargo.lock. However, when we remove the duplicate versions, sometimes we forget to remove the packages from the list of allowed exceptions. We should make `./mach test-tidy` report an error if there is a package listed under `[ignore]` which only has a single version present.

Code: https://github.com/servo/servo/blob/4d27ce0a6c86a82e39d000d19bc0de92a3a53c6f/python/tidy/servo_tidy/tidy.py#L317-L369
Test: add a new test similar to [this one](https://github.com/servo/servo/blob/master/python/tidy/servo_tidy_tests/test_tidy.py#L221-L234) and run them with `./mach test-tidy --self`

**Comment by m-novikov** [comment]
I will do this. @highfive : assign me
