### ISSUE TITLE
Implement document load cancellation

### ISSUE THREAD

**Issue by jdm** [servo/servo#19309]
This has two parts to it:
* make pressing escape in the default embedding cancel the ongoing load of the foreground, top-most document
* cause all ongoing subresource loads for the document to be cancelled when the document is cancelled

The easiest way to tie the loads together might be to move the cancellation sender into the [LoadType](http://doc.servo.org/script/document_loader/enum.LoadType.html) enum.

Blocked on #19274.

**Comment by gterzian** [comment]
If no one is doing this, I would be interested...

**Comment by gterzian** [comment]
I propose making this about implementing the following:

1. https://html.spec.whatwg.org/multipage/window-object.html#dom-window-stop
2. https://html.spec.whatwg.org/multipage/browsing-the-web.html#abort-a-document

and also adding a hook at the embedding level via the escape key, to perform a `window.close()`.Although currently we don't have the concept of an "foreground, top-most document", so maybe I'll end implementing it in some simple form as part of this too @paulrouget

**Comment by paulrouget** [comment]
Works for me.

**Comment by gterzian** [comment]
Also worth noting:

""abort" Event Isn't Fired When Aborting Document Load" https://github.com/whatwg/html/issues/3525

"add test for aborting a document load" https://github.com/web-platform-tests/wpt/pull/9933

**Comment by gterzian** [comment]
Also worth noting: 
When to "fail the connection" of an EventSource? https://github.com/whatwg/html/issues/3789
