### ISSUE TITLE
Failed to run custom build command for `gecko-media v0.1.0 when building servo with commit af6c2f9 on Ubuntu 16.04.3 LTS.

### ISSUE THREAD

**Issue by BruceDai** [servo/servo#19300]
error: failed to run custom build command for `gecko-media v0.1.0 (https://github.com/servo/gecko-media.git#0299b455)`
process didn't exit successfully: `/<path>/servo/target/release/build/gecko-media-59486aef098dd7b4/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/<path>/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/." "-DCMAKE_INSTALL_PREFIX=/<path>/servo/target/release/build/gecko-media-ccbcac47a43a429e/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
-- Configuring done
-- Generating done
-- Build files have been written to: /<path>/servo/target/release/build/gecko-media-ccbcac47a43a429e/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
[  1%] Built target ffvpx
[ 10%] Built target stagefright
[ 11%] Built target ffmpeg57
[ 12%] Built target tests
[ 12%] Built target speex_resampler
[ 13%] Built target cubeb
[ 14%] Built target ogg
[ 47%] Built target opus
[ 52%] Built target vorbis
[ 57%] Built target theora
[ 60%] Built target soundtouch
[100%] Built target gecko_core
[100%] Built target gecko_media_cmake
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /<path>/servo/target/release/build/gecko-media-ccbcac47a43a429e/out/libgecko_media_cmake.a
cargo:root=/<path>/servo/target/release/build/gecko-media-ccbcac47a43a429e/out
cargo:rustc-link-search=native=/<path>/servo/target/release/build/gecko-media-ccbcac47a43a429e/out
cargo:rustc-link-lib=static=gecko_media_cmake
cargo:rustc-link-lib=stdc++
cargo:rustc-link-lib=dl

--- stderr
gecko/glue/include/GeckoMedia.h:10:10: fatal error: 'stddef.h' file not found
gecko/glue/include/GeckoMedia.h:10:10: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: build_script_build::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  13: __libc_start_main
  14: _start

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by jdm** [comment]
This is tracked in https://github.com/servo/gecko-media/issues/71. I'm not sure what the solution is yet, unfortunately.

**Comment by BruceDai** [comment]
@jdm I tried to install clang on my PC with Intel CPU, the issue is fixed, and build servo successfully. I'm not sure whether my solution works for servo/gecko-media#71.
