### ISSUE TITLE
add feature for accountable refcell in domrefcell

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#19308]
Add a feature to use https://crates.io/crates/accountable-refcell in order to get more information for debugging panics

**Comment by kunalmohan** [comment]
Hi! I would like to give it a shot.
Just to make sure I'm going in the right direction, I'll have to modify `components/script/dom/bindings/cell.rs` to use the `accountable_refcell::RefCell` instead of `std::cell::RefCell`.
Questions-
1. Should I replace Ref and RefMut also?
2. Are there any other files or methods to be changed accordingly?

**Comment by jdm** [comment]
@kunalmohan To be more clear, we would like the use of accountable_refcell to be an optional build-time feature by adding a [cargo feature](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section). This will require adding the feature and optional dependency to script/Cargo.toml, adding the code that chooses the appropriate refcell type based on the feature (ie. `#[cfg(feature = "refcell_backtrace")`), then adding feature-enabling features (ie. `refcell_backtrace = ["script/refcell_backtrace"]`) that propagate the feature to:
* constellation/Cargo.toml
* servo/Cargo.toml
* ports/glutin/Cargo.toml
* ports/libsimpleservo/api/Cargo.toml
* ports/libsimpleservo/capi/Cargo.toml

This will allow us to run `./mach build --features refcell_backtrace` and cause the feature to ultimately be enabled in the script crate. Does that make sense?

**Comment by kunalmohan** [comment]
Yeah, I get the gist of it. I'll start working on this in a day or two.

**Comment by kunalmohan** [comment]
@jdm I am getting a number of errors because of a number of methods and traits that are present in `std::cell::RefCell<T>` but have not been implemented for `accountable_refcell::RefCell<T>`.
I can start working on this if you want. How do you suggest I should proceed?

**Comment by jdm** [comment]
Adding those methods to accountable_refcell would be great!

**Comment by kunalmohan** [comment]
Just to confirm, I'll have to create a local copy of the crate (in `/components/`) and use it, right?

**Comment by jdm** [comment]
Oh, no. You can clone https://github.com/jdm/accountable-refcell to a local directory and use a [cargo override](https://doc.rust-lang.org/cargo/reference/manifest.html#the-patch-section) in the Cargo.toml Servo's root directory to use your local copy instead of the released crate.

**Comment by kunalmohan** [comment]
I was wondering what `try_borrow()` should return in case of error? I was thinking of defining a new struct
```
pub struct BorrowError {
    error: StdBorrowError,
    backtrace: Backtrace
}
```
Is this a good idea?

**Comment by kunalmohan** [comment]
Also, I am having some confusion regarding the `map` method of Ref and RefMut. The `cell` field in Ref (and RefMut) store a reference to the RefCell object from which they were derived. In map function, a new `RefMut` is created which does not have a "parent" RefCell at the time. So what should be assigned to the cell field of the new Ref object?

**Comment by jdm** [comment]
Can't the new RefMut store the old RefMut's cell reference? As for try_borrow's return, I would be inclined to return the original error type with no extra backtrace. It's not clear to me that it would be useful.

**Comment by kunalmohan** [comment]
I tried storing the old RefMut's value directly but I am getting one error (which I had expected) and I cannot figure out how to get past that or any other way of storing the previous value.
![Screenshot from 2020-01-05 19-05-35](https://user-images.githubusercontent.com/44079328/71780985-71228b80-2fef-11ea-9cfb-cdfbf20c6423.png)

**Comment by kunalmohan** [comment]
Should I create a PR in https://github.com/jdm/accountable-refcell? It would be easier for you to review the code changes.

**Comment by jdm** [comment]
You don't have to create a PR yet, but pushing the changes to your fork would allow me to see them, yes.

**Comment by kunalmohan** [comment]
I have pushed the changes.

**Comment by jdm** [comment]
Ok, I see - you can fix this by changing the the `cell` members of Ref and RefMut to be `&'a RefCell<Vec<BorrowRecord>>`, and making `remove_matching_record` a free function that takes a `&RefCell<Vec<BorrowRecord>>` argument. This will make Ref and RefMut only hold on to the part of the original RefCell that they need access to, which doesn't require any type parameter that map interferes with.

**Comment by kunalmohan** [comment]
How should I then assign the `cell` field in all the borrow methods?

**Comment by jdm** [comment]
The RefCell (not StdRefCell) contains the `StdRefCell<Vec<BorrowRecord>>`, so borrow it and store that reference in Ref/RefMut's cell field.

**Comment by jdm** [comment]
Er, and yes, I did mean that cell should be `&'a StdRef<Vec<BorrowRecord>>`.

**Comment by kunalmohan** [comment]
Now this poses a problem for the `pub fn clone(orig: &Ref<'a, T>)`. Here we won't be able to get the id using `orig.cell.record()`.

**Comment by jdm** [comment]
Ok, I think we can work around that with the following redesign:
```rust
struct BorrowData {
    next_id: usize,
    borrows: Vec<BorrowRecord>,
}

struct RefCell<T: ?Sized> {
    borrows: StdRefCell<BorrowData>,
    inner: StdRefCell<T>,
}
```

The Ref/RefMut can store `&StdRefCell<BorrowData>`, and `record` and `remove_matching_record` can be methods of `BorrowData`.

**Comment by kunalmohan** [comment]
I am still facing a problem with the `map()` function for RefMut<T>(while taking ownership of the parameter passed to map, Drop is called which then throws an error as the field has been moved). I was able to implement it for Ref because of the `clone()` fn in StdRef<T>. I have pushed the changes to my fork in case you want to have a look.

Will Rc<T> be of any help here (wrapping fields of RefMut in Rc, although I am not sure if it can wrap reference in case of cell field )?

**Comment by jdm** [comment]
When I replicated your error, I realized that it ultimately comes from RefMut having a drop implementaiton, so we weren't allowed to move the `inner` value out of it. This led me to the following patch, which compiles:
```rust
diff --git a/src/lib.rs b/src/lib.rs
index 3bfec88..266a045 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -70,19 +70,20 @@ impl<T> RefCell<T> {
 /// An immutable reference to the value stored in a RefCell.
 pub struct Ref<'a, T: ?Sized + 'a> {
     inner: StdRef<'a, T>,
-    cell: &'a StdRefCell<BorrowData>,
-    id: usize,
+    data: RefBorrowData<'a>,
 }
 
 impl<'a, T: ?Sized> Ref<'a, T> {
     /// Clone the provided Ref value. This is treated as a separate borrow record from
     /// the original cloned reference.
     pub fn clone(orig: &Ref<'a, T>) -> Ref<'a, T> {
-        let id = orig.cell.borrow_mut().record();
+        let id = orig.data.cell.borrow_mut().record();
         Ref {
             inner: StdRef::clone(&orig.inner),
-            cell: orig.cell,
-            id: id,
+            data: RefBorrowData {
+                cell: orig.data.cell,
+                id: id,
+            },
         }
     }
 
@@ -91,8 +92,7 @@ impl<'a, T: ?Sized> Ref<'a, T> {
     {
         Ref {
             inner: StdRef::map(StdRef::clone(&orig.inner), f),
-            cell: orig.cell,
-            id: orig.id,
+            data: orig.data,
         }
     }
 }
@@ -117,27 +117,31 @@ impl<'a, T: ?Sized> Deref for Ref<'a, T> {
     }
 }
 
-impl<'a, T: ?Sized> Drop for Ref<'a, T> {
-    fn drop(&mut self) {
-        self.cell.borrow_mut().remove_matching_record(self.id);
-    }
-}
-
 /// A mutable reference to the value stored in the associated RefCell.
 pub struct RefMut<'a, T: ?Sized + 'a> {
     inner: StdRefMut<'a, T>,
+    data: RefBorrowData<'a>,
+}
+
+struct RefBorrowData<'a> {
     cell: &'a StdRefCell<BorrowData>,
     id: usize,
 }
 
+impl<'a> Drop for RefBorrowData<'a> {
+    fn drop(&mut self) {
+        self.cell.borrow_mut().remove_matching_record(self.id);
+    }
+}
+
 impl<'a, T: ?Sized> RefMut<'a, T> {
     pub fn map<U: ?Sized, F>(orig: RefMut<'a, T>, f: F) -> RefMut<'a, U>
     where F: FnOnce(&mut T) -> &mut U
     {
+        let RefMut { inner, data } = orig;
         RefMut {
-            inner: StdRefMut::map(orig.inner, f),
-            cell: orig.cell,
-            id: orig.id,
+            inner: StdRefMut::map(inner, f),
+            data,
         }
     }
 }
@@ -157,12 +161,6 @@ impl<'a, T: ?Sized> DerefMut for RefMut<'a, T> {
 }
 
 
-impl<'a, T: ?Sized> Drop for RefMut<'a, T> {
-    fn drop(&mut self) {
-        self.cell.borrow_mut().remove_matching_record(self.id);
-    }
-}
-
 impl<T: ?Sized> RefCell<T> {
     /// Borrow the value stored in this cell immutably. Panics if any outstanding mutable
     /// borrows of the same cell exist.
@@ -171,8 +169,10 @@ impl<T: ?Sized> RefCell<T> {
             let id = self.borrows.borrow_mut().record();
             Ref {
                 inner: r,
-                cell: &self.borrows,
-                id: id,
+                data: RefBorrowData {
+                    cell: &self.borrows,
+                    id: id,
+                },
             }
         } else {
             if let Ok(var) = env::var("RUST_BACKTRACE") {
@@ -191,8 +191,10 @@ impl<T: ?Sized> RefCell<T> {
                 let id = self.borrows.borrow_mut().record();
                 Ok(Ref {
                     inner: r,
-                    cell: &self.borrows,
-                    id: id,
+                    data: RefBorrowData {
+                        cell: &self.borrows,
+                        id: id,
+                    },
                 })
             }
             Err(e) => Err(e)
@@ -206,8 +208,10 @@ impl<T: ?Sized> RefCell<T> {
             let id = self.borrows.borrow_mut().record();
             RefMut {
                 inner: r,
-                cell: &self.borrows,
-                id: id,
+                data: RefBorrowData {
+                    cell: &self.borrows,
+                    id: id,
+                },
             }
         } else {
             if let Ok(var) = env::var("RUST_BACKTRACE") {
@@ -229,8 +233,10 @@ impl<T: ?Sized> RefCell<T> {
                 let id = self.borrows.borrow_mut().record();
                 Ok(RefMut {
                     inner: r,
-                    cell: &self.borrows,
-                    id: id,
+                    data: RefBorrowData {
+                        cell: &self.borrows,
+                        id: id,
+                    },
                 })
             }
             Err(e) => Err(e)
```

**Comment by kunalmohan** [comment]
Now coming to servo, we need to modify `ref_filter_map::ref_filter_map` crate/repository for it to take `accountable::refcell` as parameter when the feature is enabled. Currently it accepts std::cell::Ref<T> as parameter.

**Comment by jdm** [comment]
Can you give an example of code that's using it? https://github.com/SimonSapin/rust-std-candidates/blob/master/ref_filter_map/lib.rs operates on the standard library RefCell types, so it's not clear to me how it's related to this work.

**Comment by kunalmohan** [comment]
https://github.com/servo/servo/blob/5c7a4db5f4e374dee287d403d90c7bc0e07ac9d0/components/script/dom/webglvertexarrayobjectoes.rs#L97-L101
https://github.com/servo/servo/blob/5c7a4db5f4e374dee287d403d90c7bc0e07ac9d0/components/script/dom/offscreencanvas.rs#L96-L98

**Comment by kunalmohan** [comment]
Other occurrences are in `components/script/dom`:
`/element.rs`
`/document.rs`
`/htmlcanvaselement.rs`

**Comment by jdm** [comment]
Bleah. I recommend duplicating the implementation of ref_filter_map into accountable_refcell in that case.

**Comment by kunalmohan** [comment]
As you wish :)

**Comment by kunalmohan** [comment]
Wow! I got 99 total errors in a number of files all of the type ` Expression of type accountable_refcell::Ref<...> must be rooted`. Do I need to add `#[allow(unrooted_must_root)]` at all instances separately? (Just want to know if there is a shorter way before doing all that hardwork :sweat_smile:)

**Comment by jdm** [comment]
No, you can add an entry to https://github.com/servo/servo/blob/master/components/script_plugins/lib.rs#L124 and https://github.com/servo/servo/blob/master/components/script_plugins/lib.rs#L406 to extend the existing checks for core::cell::Ref to encompass accoutable_refcell::Ref as well (and RefMut, too).

**Comment by kunalmohan** [comment]
`./mach check --features refcell_backtrace` was successful. Running `./mach build -d --features refcell_backtrace` now (This will take time. dev build generally takes around 6 hrs on my system :disappointed:, release 45 min).

**Comment by kunalmohan** [comment]
I have pushed the latest changes to my fork (for accountable-refcell). Please check and let me know if anything needs to be added (any necessary tests?; I have not added any tests or documentation) or changed. I'll do so before squashing the commits and creating a PR.

**Comment by jdm** [comment]
I can't think of any missing tests off the top of my head. Go ahead and do the squashing and creating the PR!
