### ISSUE TITLE
Remove cancellation map and ResourceId

### ISSUE THREAD

**Issue by jdm** [servo/servo#19327]
These are remnants of the old network cancellation implementation, so we don't need them any more.

Code:
* https://github.com/servo/servo/blob/dc35457b4a6dec744de1e8b61bf8fb9b3947a3ba/components/net/resource_thread.rs#L305
* https://github.com/servo/servo/blob/dc35457b4a6dec744de1e8b61bf8fb9b3947a3ba/components/net_traits/lib.rs#L503
* https://github.com/servo/servo/blob/dc35457b4a6dec744de1e8b61bf8fb9b3947a3ba/components/net_traits/lib.rs#L366

No need to run tests; if it builds, it's good enough for a PR.

**Comment by Eijebong** [comment]
@highfive assign me

Going to give this a try :)
