### ISSUE TITLE
Install the AWS CLI on buildbots

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#19340]
At the moment we're using hand-crafted python files for uploading to S3, it might be easier just to install the AWS CLI https://github.com/aws/aws-cli#installation.

Boto3 doesn't support directory upload: https://github.com/boto/boto3/issues/358

See https://github.com/servo/servo/pull/16565

cc @jdm @aneeshusa

**Comment by jdm** [comment]
https://github.com/servo/saltfs/pull/756

**Comment by asajeffrey** [comment]
Fixed by https://github.com/servo/saltfs/pull/756/files
