### ISSUE TITLE
Doc build fails with "Unrecognized option: 'document-private-items'."

### ISSUE THREAD

**Issue by jdm** [servo/servo#19365]
I suspect this is coming from the geckolib documentation build, which maybe uses stable rust?

```
rustdoc: Unrecognized option: 'document-private-items'.
Try 'rustdoc --help' for more information.
rustdoc: Unrecognized option: 'document-private-items'.
Try 'rustdoc --help' for more information.
rustdoc: Unrecognized option: 'document-private-items'.
Try 'rustdoc --help' for more information.
error: Could not document `log`.
```

**Comment by SimonSapin** [comment]
Ah yes, we may want to revert https://github.com/servo/servo/pull/19338/commits/d96f0ff6a77e309682898cc7e1905a7bd0feb3cf until this option is available on the version we use for geckolib.
