### ISSUE TITLE
Remove WrappedHttpResponse abstraction

### ISSUE THREAD

**Issue by jdm** [servo/servo#19361]
This type is an extremely thin wrapper around hyper's HTTP response type and does not provide any value. We should just use the `HyperResponse` type directly everywhere instead.

Code: `components/net/http_loader.rs`

No need for any automated tests; if the changes build, they're good enough for a PR.

**Comment by tigercosmos** [comment]
@highfive: assign me

**Comment by KiChjang** [comment]
@tigercosmos I believe you said that you have exams and are bogged down by other issues, are you able to work on this issue in the near future? I would like to keep issues open for other contributors if you are not currently actively working on it.

**Comment by tigercosmos** [comment]
um… I think this one can been done fast. I will do it on Saturday. Thanks for you concern :) 
Other issue I will keep working on, but they need more time.  
If I have not done it in three days, please feel free to release it :D
