### ISSUE TITLE
google.com buttom with extra space

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19389]
test  ac6e04e
with macOS 10.12

<img width="1023" alt="2017-11-27 7 43 22" src="https://user-images.githubusercontent.com/18013815/33265186-9ee99330-d3ab-11e7-979b-96d77ae97757.png">

unlike  #16185

**Comment by dralley** [comment]
This doesn't seem to happen for me (Fedora 32), might have been fixed by now
