### ISSUE TITLE
Implement create-an-element-for-a-token algorithm

### ISSUE THREAD

**Issue by jdm** [servo/servo#19392]
`create_html_element` implements https://dom.spec.whatwg.org/#concept-create-element and is called from the parser (via Element::create in `Sink::create_element`), but the HTML specification defines https://html.spec.whatwg.org/multipage/parsing.html#create-an-element-for-the-token which is used by the HTML parsing algorithms. Steps 6 and 9 are particularly relevant for dealing with https://github.com/servo/servo/pull/19307#issuecomment-346173603.

**Comment by jdm** [comment]
@cbrewster Any chance you feel like fixing this?

**Comment by cbrewster** [comment]
@jdm Yeah I can work on this.
