### ISSUE TITLE
Address bar is not updating

### ISSUE THREAD

**Issue by sviter** [servo/servo#19407]
Go to https://news.ycombinator.com/
Click any article link
Servo will load new site but in address bar you still will see news.ycombinator.com

**Comment by atouchet** [comment]
I am not able to reproduce this.

**Comment by sviter** [comment]
Yes. No such issue on latest build. But I can reproduce it on previous

**Comment by srinivasreddy** [comment]
No such issue. My firefox version is 58.0b4 (64-bit)

**Comment by jdm** [comment]
@srinivasreddy This is specific to Servo; it is unrelated to Firefox.
