### ISSUE TITLE
which package is using to draw UI widgets such as buttons?

### ISSUE THREAD

**Issue by kingofoz** [servo/servo#19403]
Hi authors,
I know glutin is included in the project, but glutin is not drawing buttons.

**Comment by SimonSapin** [comment]
Hi. Servo doesn’t use what you’re probably thinking of as UI widgets. HTML form inputs are drawn (poorly) with CSS borders: https://github.com/servo/servo/blob/master/resources/servo.css

**Comment by kingofoz** [comment]
I see. Thank you.
