### ISSUE TITLE
Implement Public Key Pinning Extension for HTTP

### ISSUE THREAD

**Issue by gterzian** [servo/servo#19459]
Would it be useful at this stage to try to implement this? It seems a Web-Platform-Tests suite is absent as well...

spec: https://tools.ietf.org/html/rfc7469

**Comment by jdm** [comment]
Chrome is removing it, so it's probably not a good idea for Servo at this point: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/he9tr7p3rZ8

**Comment by gterzian** [comment]
Ok, thanks for the info.

**Comment by Darkspirit** [comment]
This can be closed, HPKP was [disabled](https://searchfox.org/mozilla-central/rev/3fd53c47864fedb916f0ed8f002f15456324f729/modules/libpref/init/all.js#2328-2335) in Firefox.
Such a certificate whitelist can be achieved by checking DNS TLSA records (DANE) which aren't such a footgun. Like [Encrypted SNI](https://tools.ietf.org/html/draft-ietf-tls-esni-06) ([network.security.esni.enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1590863), [Test site](https://www.cloudflare.com/ssl/encrypted-sni/), [Blog post](https://blog.cloudflare.com/encrypted-sni/)) it depends on DNSSEC ([either DNS-over-HTTPS or local verification](https://github.com/bluejekyll/trust-dns)).

**Comment by gterzian** [comment]
Ok, thanks for the info.
