### ISSUE TITLE
Bad CSS? Render on Phoronix Forums on latest Firefox Nightly

### ISSUE THREAD

**Issue by romulasry** [servo/servo#19460]
https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/992802-amd-publishes-more-dc-patches-disables-freesync-by-default

See Page 1 of 2 Filter at the top right of the image.

![image](https://user-images.githubusercontent.com/19944656/33513703-1ce5a8b0-d6fd-11e7-84a1-d20171d88f8e.png)

**Comment by jdm** [comment]
Please bugs in Firefox at https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=CSS%20Parsing%20and%20Computation. However, this looks the same in Chrome as far as I can tell, which makes it look like an intentional choice by the site authors.
