### ISSUE TITLE
EGL (without X11) build.

### ISSUE THREAD

**Issue by LongChair** [servo/servo#19479]
I have tried to cross build servo for arm64 using the explanations available here : https://mmatyas.github.io/blog/servo-short-cross-compilation-guide

I would like to build it for a minimal linux environment on an embedded device where X11 is not an option as it is very slow.

Using the link above, It seems that the resulting binary is linked to libX11.
I had read that it was possible to have Servo run on a simple egl envrionment without X11, but can't seem to achieve it.

Is there any way to achieve such a build ?

**Comment by emilio** [comment]
I disabled EGL a while ago because glutin by then was really unstable... Thinks are probably better now, so probably it's a matter of updating glutin and enabling it.

**Comment by LongChair** [comment]
Could you give me a few instructions to do so ?

**Comment by paulrouget** [comment]
>  I had read that it was possible to have Servo run on a simple egl envrionment without X11, but can't seem to achieve it.

This is what I did on Android.

Do not use Glutin. I'm not sure how to create your own GL buffer on Linux, but once you managed to do it, maybe use `gl_generator` to create the bindings necessary for Servo.

Let me know if I can help.
