### ISSUE TITLE
Servo on Linux browser.html having issues

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#19472]
Starting up a recent Servo in Linux, I see this:

![screenshot from 2017-12-04 12-12-59](https://user-images.githubusercontent.com/547158/33531031-b4cf5464-d8ec-11e7-8dff-21add0bda1af.png)

While I can click on the search box, I don't see the gallery.  I also can't seem to click on the +.

Also, the Linux build doesn't seem to be respecting hidpi, [which looks like a known issues](https://github.com/servo/servo/issues/12054)

**edit:** I should point out this is with a stock latest Ubuntu (17.10) on a 2016 Dell XPS 13.

**Comment by paulrouget** [comment]
Probably not. Closing.
