### ISSUE TITLE
Use entry global's origin in "is origin clean" check for canvas rendering

### ISSUE THREAD

**Issue by jdm** [servo/servo#19480]
`Canvas2dRenderingContext::is_origin_clean` uses the origin of the canvas's document's url's origin. https://html.spec.whatwg.org/multipage/canvas.html#the-image-argument-is-not-origin-clean says we should use the "entry settings object's origin", which is equivalent to using [entry_global](https://doc.servo.org/script/dom/bindings/settings_stack/fn.entry_global.html) and obtaining its [origin](https://doc.servo.org/script/dom/globalscope/struct.GlobalScope.html#method.origin).

Tests: `./mach test-wpt tests/wpt/web-platform-tests/2dcontext` and `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/the-canvas-element`

**Comment by tigercosmos** [comment]
@highfive: assign me
Do this now

**Comment by tigercosmos** [comment]
I am going to do this in this afternoon

**Comment by tigercosmos** [comment]
@jdm I have a PR on this
