### ISSUE TITLE
Better support for CSS backgrounds

### ISSUE THREAD

**Issue by est31** [servo/servo#19482]
This web site contains a couple of custom CSS backgrounds: http://lea.verou.me/css3patterns/

While some backgrounds are being displayed correctly, most backgrounds have bugs of varying severity.

Screenshot of the page in Firefox (everything fine):

![screenshot_20171204_192949](https://user-images.githubusercontent.com/8872119/33569340-96a481f2-d929-11e7-9545-2c2c255d3e91.png)

Screenshot in servo as of commit e4dba3abef2a4941c5a4d95d58ae0b864ad10961 :

![screenshot_20171204_192925](https://user-images.githubusercontent.com/8872119/33569378-bca1a7ae-d929-11e7-9275-2d03b638ecad.png)

**Comment by JRegimbal** [comment]
It looks to me like all the issues are with displaying CSS gradients. Can anyone confirm this?

**Comment by tigercosmos** [comment]
Yah, Looks like caused by `gradient`.

**Comment by pyfisch** [comment]
Great website, with a lot of difficult gradient test cases! I am working on this and the gradients are now rendered with only minor issues. I will submit a PR after cleaning up.

![gradient](https://user-images.githubusercontent.com/2781017/33913367-c852cec2-df99-11e7-9d7b-f30d7c5c245c.png)

**Comment by est31** [comment]
@pyfisch thank you for fixing this! :heart:

**Comment by pyfisch** [comment]
Gradients are now displayed outside the circles but this is tracked in #19649. (And should not take too long.)
