### ISSUE TITLE
Provide font tables on-demand to HarfBuzz

### ISSUE THREAD

**Issue by burg** [servo/servo#195]
We currently create a huge `hb_blob_t` of all font data, whether it's used or not. Instead, we should probably be using the `hb_face_create_for_tables` function, which given a callback with a type tag, returns the buffer of the corresponding font table.

Each font backend implements a call to retrieve a particular table. In CoreText, it's `CTFontCopyTable`. In FreeType, it seems to involve `FT_Get_Charmap_Index`.

**Comment by mbrubeck** [comment]
This is done.
