### ISSUE TITLE
./mach test-perf isn't working on mac

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#19502]
Seems like there are some tweaks needed to test-perf

I think the current problem I'm having is related to https://forums.developer.apple.com/thread/77536

See discussion at https://mozilla.logbot.info/servo/20171205#c13969788

We should figure out how to fix this in the test-perf script and document whatever configuration is necessary to make this work

**Comment by nicoabie** [comment]
@jdm don't know if this is still relevant but this is the output of my macOS 10.15.6

```
ngallinal@ITs-Mac-mini-2 servo % ./mach test-perf      
Downloading the test cases...
test_perf.sh: line 17: wget: command not found
```

**Comment by CYBAI** [comment]
Looks like this is related to OSMesa which is not supported now so I guess it should be fine to close this issue now.

I'm going to close this and please reopen it if I'm wrong 🙏
