### ISSUE TITLE
New GTK port

### ISSUE THREAD

**Issue by antoyo** [servo/servo#19501]
Hello.
I started working on a [gtk binding for servo](https://github.com/antoyo/servo-gtk) and I wonder if you were interested by my work.
If yes, what is the process to add a new port to `servo`?
Thanks.

**Comment by fabricedesre** [comment]
Not my call, but the very fact that you were able to do that port out of the main tree with just a dependency on libservo shows that these ports don't have to be in the main repository. This is a strength of the embedding model and I feel it's useful to keep them apart to not be tempted to regress on this topic.

**Comment by antoyo** [comment]
I proposed to do so because there are other [ports](https://github.com/servo/servo/tree/master/ports) in the repository, but I don't mind keeping that port in a separate repository.
But I still wonder which direction I should go, so if you are interested, maybe we could talk about this port and the servo API.

**Comment by emilio** [comment]
Maybe this is a better topic for the servo-dev@ mailing list, instead of
a GitHub issue?

Not that I particularly mind, but that way it probably gets a bit more
visibility, not lots of people watch issues.

**Comment by paulrouget** [comment]
> I proposed to do so because there are other ports in the repository

These are minimal shells around Servo. We use Glutin. I don't believe we need a specific GTK port.

Eventually, we'd like to have more advanced ports, with tabs support and a proper UI. We are _considering_ [ServoShell](https://github.com/paulrouget/servoshell/) as a candidate for Servo Nightly builds (to replace browserhtml), and in this case, your GTK port would be very much interesting. And like @fabricedesre said, this will stay outside of servo/servo, and maybe have a dedicated repo (servo/servoshell).

**Comment by mitchtbaum** [comment]
@antoyo Have you made any more progress with servo-gtk?
