### ISSUE TITLE
Usage of servo as a C lib?

### ISSUE THREAD

**Issue by sorenbug** [servo/servo#19503]
Was motioned to make an issue about this from IRC.

I'd like to use servo in my C-compatible language of choice, but currently there's no guide or opportunity to do that from what I've heard.

Could this be a goal in the future?

**Comment by antoyo** [comment]
I plan to make a C lib for [`servo-gtk`](https://github.com/antoyo/servo-gtk) when [gnome-class](https://github.com/nikomatsakis/gnome-class) will be more usable.

**Comment by jdm** [comment]
Is CEF usable from C?

**Comment by TsundereBug** [comment]
@antoyo I was more planning on using [nuklear](https://github.com/vurtun/nuklear) as my UI kit. I don't know much about GTK; could I easily make this run on nuklear as well?

**Comment by antoyo** [comment]
@TsundereBug I guess that would require a binding for nuklear, then.
I know one way to embed a window in another toolkit, but I don't think you can control it from the parent window, unfortunately.

**Comment by TsundereBug** [comment]
That's fine, I'll be writing my own hooks/layer to modify the browser view from the UI layer.

Sounds good! Can't wait for servo to be used as a lib like this.

**Comment by metux** [comment]
Why not running it as a separate server process ? For the IPC, I'd suggest 9P.

**Comment by paulrouget** [comment]
Now a C library is built by default. See target/debug/libsimpleservo.so/dylib/dll.
