### ISSUE TITLE
`let` behaves like `var` in a `for (let x of ...)` loop

### ISSUE THREAD

**Issue by jonleighton** [servo/servo#19535]
Here's a minimal test case:

``` html
<!DOCTYPE html>
<title>Servo let loop bug</title>
<meta charset=utf-8>
<script>
const items = [1, 2];
const closures = [];

for (let item of items) {
  closures.push(() => item);
}

for (let c of closures) {
  console.log(c());
}
</script>
```

Firefox prints:

```
1
2
```

Servo prints:

```
2
2
```

**Comment by jdm** [comment]
I'm curious if a released version of Firefox from June 2016 shows the same problem.

**Comment by emilio** [comment]
Yeah, this is a known bug in SM, `let` scoping rules were pretty broken, let me try to find the bug.

**Comment by emilio** [comment]
I think it is https://bugzilla.mozilla.org/show_bug.cgi?id=1069480, and was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1069480.

**Comment by emilio** [comment]
Actually, it is https://bugzilla.mozilla.org/show_bug.cgi?id=449811

**Comment by atouchet** [comment]
Is this still an issue after the SpiderMonkey update?

**Comment by jdm** [comment]
Nope!
