### ISSUE TITLE
Move list-style-image outside of mako.

### ISSUE THREAD

**Issue by emilio** [servo/servo#19557]
Part of #19015.

@fenak mentioned he wanted to work on this over there, thanks a lot! :)

**Comment by fenak** [comment]
Hi @emilio , I'm a little bit confused on the `trivial_to_compute_value!(T)`, as there's a comment saying this is wrong.

**Comment by fenak** [comment]
Another question: I see `% if product == "gecko"` in the mako templates, is that translated to `#[cfg(feature = "gecko")]` outside of it?

**Comment by emilio** [comment]
> Hi @emilio , I'm a little bit confused on the trivial_to_compute_value!(T), as there's a comment saying this is wrong. Can you shed some light on it?

Yes, so this is wrong and should be fixed, but ideally in a different PR. In particular, computed and specified urls in servo are different, and that means that the specified value should be generic over the `Url` and such, much like `values::generics::Image` is generic over `ImageUrl`.

> Another question: I see % if product == "gecko" in the mako templates, is that translated to #[cfg(feature = "gecko")] outside of it?

That's exactly right :)

**Comment by fenak** [comment]
@emilio in this case, how should I handle and `else` clause outside mako?

```
        % if product == "gecko":
        let mut value = input.try(|input| UrlOrNone::parse(context, input))?;
        if let Either::First(ref mut url) = value {
            url.build_image_value();
        }
        % else :
        let value = input.try(|input| UrlOrNone::parse(context, input))?;
        % endif

```

**Comment by emilio** [comment]
In this case, given the line is kinda repeated, I'd do something like:

```rust
let mut url = input.try(|input| UrlOrNone::parse(context, input))?;

#[cfg(feature = "gecko")]
{
        if let Either::First(ref mut url) = value {
            url.build_image_value();
        }
}
```

But otherwise you could do:

```rust
#[cfg(feature = "gecko")]
{
    // ...
}
#[cfg(not(feature = "gecko"))]
{
    // ...
}
```
