### ISSUE TITLE
servo-mac9 takes 45 minutes to compile Servo

### ISSUE THREAD

**Issue by jdm** [servo/servo#19567]
This is almost twice as slow as other mac builders, which is suspicious.

**Comment by jdm** [comment]
There's a FileStatsAgents process that regularly consumes 75-99% of CPU in bursts which doesn't happen on servo-mac8, which makes me suspicious.

**Comment by jdm** [comment]
This is still the case. After finding the pid of the FileStatsAgent process, I am running `lsof -p [pid]` on the machine and it's current progressing through /Users/administrator/Downloads/Xcode.app/Contents/Developer/Platforms/.

**Comment by jdm** [comment]
@edunham What is the purpose of the XCode.app and XCode-2.app bundles that exist in /Users/administrator/Downloads on all the mac machines? All of the suggestions for dealing with FileStatsAgent churning that I've found so far recommend deleting the files that it is focused on.

**Comment by edunham** [comment]
They are artifacts from the setup process -- when bootstrapping a new host, we download the files, then copy them to their installed locations, but we had not previously been explicitly removing the downloads. I've updated https://github.com/servo/servo/wiki/SaltStack-Administration to mention removing them and cleaned up the `.dmg` and `.app` stuff from the Downloads directories... The following logs are probably irrelevant but this is the first place I'll look if I happen to want them later. 

Before:

```
salt -E 'servo-mac*' cmd.run 'ls /Users/administrator/Downloads'
servo-mac5:
    .DS_Store
    .localized
    Command_Line_Tools_macOS_10.11_for_Xcode_8.2.dmg
    Xcode-2.app
    Xcode.app
servo-mac9:
    .localized
    Command_Line_Tools_macOS_10.11_for_Xcode_8.2.dmg
    Xcode-2.app
    Xcode.app
servo-mac4:
    .DS_Store
    .localized
    Xcode_7.2.1.dmg
servo-mac3:
    .DS_Store
    .localized
servo-mac8:
    .localized
    Command_Line_Tools_macOS_10.11_for_Xcode_8.2.dmg
    Xcode-2.app
    Xcode.app
servo-mac6:
    .DS_Store
    .localized
    Command_Line_Tools_macOS_10.11_for_Xcode_8.2.dmg
    Xcode-2.app
    Xcode.app
    iousbfamily540.4.1alog.dmg
servo-mac2:
    .DS_Store
    .localized
    About Downloads.lpdf
    command_line_tools_for_osx_10.9_for_xcode_6.1.dmg
    command_line_tools_for_osx_mountain_lion_april_2014.dmg
    xcode_5.1.1.dmg
servo-mac7:
    .localized
    Command_Line_Tools_OS_X_10.10_for_Xcode_7.2.dmg
    Xcode_7.2.1.dmg
servo-mac1:
    .localized
```

After:

```
salt -E 'servo-mac*' cmd.run 'ls /Users/administrator/Downloads'
servo-mac7:
    .localized
servo-mac3:
    .DS_Store
    .localized
servo-mac9:
    .localized
servo-mac4:
    .DS_Store
    .localized
servo-mac6:
    .DS_Store
    .localized
servo-mac8:
    .localized
servo-mac2:
    .DS_Store
    .localized
    About Downloads.lpdf
servo-mac1:
    .localized
servo-mac5:
    .DS_Store
    .localized
```

**Comment by jdm** [comment]
Thanks!

**Comment by jdm** [comment]
This has not helped the compile times, unfortunately. The fact that kernel_task is constantly using >60% CPU makes me fear that the machine's hardware is faulty, since that task is designed to regulate CPU usage when the internal temperature is reaching unsafe levels according to [this post](https://discussions.apple.com/message/30723472#message30723472).

**Comment by jdm** [comment]
I'm going to trigger the graceful shutdown operation to take the machine out of the pool of build machines, since it's significantly increasing the duration of our complete builds.

**Comment by jdm** [comment]
This no longer occurs.
