### ISSUE TITLE
Implement background-clip correctly for image backgrounds

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#19577]
Images with background-clip are off.

[Source](https://gist.github.com/pyfisch/d45929d0c53adb2b82690fd64de2b518)
Servo:
![background-clip-servo](https://user-images.githubusercontent.com/2781017/34055041-cef6e048-e1cd-11e7-9c9d-ce7e1d4781f1.png)
Firefox (expected rendering):
![background-clip-firefox](https://user-images.githubusercontent.com/2781017/34055085-08933982-e1ce-11e7-8127-76955bba3cb0.png)

**Comment by tigercosmos** [comment]
https://github.com/servo/servo/wiki/Priority-of-CSS-properties

The wiki say `clip` will be in future.
