### ISSUE TITLE
Cannot use Tab to navigate between inputs

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19596]
Steps to reproduce:

1. `./mach run https://facebook.com`
2. Click in the `email` or `phone` input
3. Try to use `tab` to jump to next input which should be `password`
4. You should see you're still in the first input.

Note: I built with master on [`3a37d80931`](https://github.com/servo/servo/commit/3a37d8093108b66fb3edc212c97551738450c402) commit which is the latest one when I'm creating this issue

**Comment by jdm** [comment]
This is tracked in #3982.

**Comment by CYBAI** [comment]
Oh, sorry, didn't notice this one. Thanks!
