### ISSUE TITLE
implement  Time type inputs

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19603]
has been implemented:
- [X] `is_valid_time_string` 
- [ ] `parse a time string`
- [ ] `parse a time component`

need to fix first before #19587(Date-time type)
part of #19172

**Comment by tigercosmos** [comment]
@highfive: assign me

**Comment by tigercosmos** [comment]
@KiChjang There's a dilemma. Currently `is_valid_time_string` is not suitable to transfer to `parse a time string` and `parse a time component`, because it deal with the string by chars. But parsing would like to return `(HH, MM, SS) = (u32, u32, u32)`.

However, Reinventing the wheel seems not a good idea.

The best relationship might be:
`parse _time_component` -> `parse_time_string` -> `is_valid_time_string`

cc. @SWW13

**Comment by tigercosmos** [comment]
@highfive: unassign me

**Comment by KiChjang** [comment]
I don't see much value in trying to reimplement `is_valid_time_string` solely in terms of `parse_time_component` and `parse_time_string`. That function today is well-optimized for its only use case, which is to validate whether the string itself is a valid time string.

**Comment by tigercosmos** [comment]
@KiChjang I would implement parse function  because date time input will use it. I cannot use valid function, because it is bind to Dom.

**Comment by tigercosmos** [comment]
@KiChjang So do you think I just implement parse function aside with valid one is fine?

**Comment by KiChjang** [comment]
Yes.

**Comment by SWW13** [comment]
@tigercosmos You could possibly reuse parts of the state machine and combine the Low, Middle and High states for parsing.
