### ISSUE TITLE
Wrong linear-gradient rendering

### ISSUE THREAD

**Issue by sviter** [servo/servo#19626]
Go to https://engineering.instagram.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881
Link to Github is rendering incorrect. Underline is made with linear-gradient.
![link servo](https://user-images.githubusercontent.com/6523067/34297134-5a988d78-e727-11e7-8a73-6a5dad29f29f.png)

**Comment by jdm** [comment]
```html
<style>
  span {
    background-image: linear-gradient(to bottom,rgba(0,0,0,.68) 50%,rgba(0,0,0,0) 50%);
    background-repeat: repeat-x;
    background-size: 2px .1em;
    background-position: 0 0.9em;
  }
</style>
<span>hi there</span>
```
Firefox shows a similar issue if I disable the `background-repeat` property, so that might be a clue.

**Comment by sviter** [comment]
If so this is #16657
