### ISSUE TITLE
All command wiki

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19623]
I don't see a wiki for all command usage. (or please tell me where?)
the wiki should list all `mach` can do and how to use.

**Comment by SimonSapin** [comment]
Such documentation should exist, but it should not live outside of the repository because that way it would be likely to quickly become outdated. However `./mach --help` already exists. If that’s missing some information, we should add it there.

**Comment by tigercosmos** [comment]
I think it is still worth to have a copy in wiki?

**Comment by KiChjang** [comment]
@tigercosmos Can you give a reason why? @SimonSapin has already stated his concerns of the wiki document being outdated.

**Comment by tigercosmos** [comment]
I just think sometime user might want to read via the website.
Some project even show the command at readme
such as https://github.com/sharkdp/fd#command-line-options

**Comment by SimonSapin** [comment]
It’s fine to document on the wiki or in the README some commands for the most common scenarios (like `./mach build`) but we should not try to make that exhaustive because incorrect docs can be worse than incomplete docs. Unless we can prevent them from becoming out of date by auto-generating them it from mach’s `@Command` declarations like `./mach --help` does.

**Comment by tigercosmos** [comment]
so, I guess we can do two things:
- add most common command in readme
- auto generate doc in `/doc`

**Comment by SimonSapin** [comment]
Regarding the second point: given that `./mach --help` already exists and that one already needs to be in a terminal anyway to use these commands, I’ve skeptical of the value of spending much time writing and maintaining code to generate that same documentation in HTML format.

**Comment by tigercosmos** [comment]
I agree. Let's just do the first point 👍

**Comment by jdm** [comment]
We've got various useful commands in the quickstart and readme documents now.
