### ISSUE TITLE
Lots of warnings: the type of this value must be known in this context

### ISSUE THREAD

**Issue by metux** [servo/servo#19637]
Hi folks,

I'm getting *a lot* of warnings like this:

> warning[E0619]: the type of this value must be known in this context
>    --> /home/nekrad/src/moz/servo/target/release/build/script-917cc22c0e8f3269/out/Bindings/XMLHttpRequestEventTargetBinding.rs:1088:74
>      |
> 1088 |     EventTargetBinding::GetConstructorObject(cx, global, >interface_proto.handle_mut());
>      |           > ^^^^^^^^^^
>      |
>      = note: this will be made into a hard error in a future version of the compiler
>
> warning[E0619]: the type of this value must be known in this context
>     --> /home/nekrad/src/moz/servo/target/release/build/script-917cc22c0e8f3269/out/Bindings/XMLHttpRequestEventTargetBinding.rs:1102:51
>      |
> 1102 |                                         interface.handle_mut());
>      |                                                   ^^^^^^^^^^
>      |
>      = note: this will be made into a hard error in a future version of the compiler

What does that mean ?

I'm using a pretty fresh rustc (updated few days ago) - did anything
vital change in the compiler/language ?

--mtx

**Comment by SimonSapin** [comment]
This is https://github.com/rust-lang/rust/issues/46906. In general, using a version other than the one specified in the `rust-toolchain` file is unsupported. If you use rustup or build with `./mach build` the correct version is downloaded automatically.

At the moment, upgrading is blocked on https://github.com/servo/servo/issues/19519.

**Comment by metux** [comment]
Okay. I had upgraded rust, hoping that #[cfg()] on if statements would be implemented now ...

Nevertheless, this issue should be fixed sooner or later.
