### ISSUE TITLE
`./mach check` fails on Fedora 26: src/task_info.c:10:10: fatal error: mach/mach_init.h: No such file or directory

### ISSUE THREAD

**Issue by jonleighton** [servo/servo#19635]
As of e2f534f681fb10d0cf917c19c92b9bb40a9e2ebd I can no longer run `./mach check` on Fedora 26. [Here is the output of `./mach check -v'](https://gist.github.com/jonleighton/56119542b8cc9fbf449210849b554862). The error is:

```
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-o" "/home/turnip/Code/servo/target/debug/build/task_info-5b509507e8510095/out/src/task_info.o" "-c" "src/task_info.c"
cargo:warning=src/task_info.c:10:10: fatal error: mach/mach_init.h: No such file or directory
cargo:warning= #include <mach/mach_init.h>
cargo:warning=          ^~~~~~~~~~~~~~~~~~
cargo:warning=compilation terminated.
```

It comes from the [`support/rust-task_info` crate](https://github.com/servo/servo/tree/master/support/rust-task_info), but I think what has happened is that before e2f534f681fb10d0cf917c19c92b9bb40a9e2ebd, `task_info` wasn't being built (it doesn't show up in the output of `./mach check -v` on the preceding commit). The change in e2f534f681fb10d0cf917c19c92b9bb40a9e2ebd seems to have made it so that `./mach check` does now try to build `task_info`, and so the failure is now showing up.

It appears that the code in the `task_info` crate is targeted at OS X, which would be why it won't build for me. I've tried to do a bit of figuring out about why `./mach check` is now trying to build it when it previously didn't, but I haven't got very far.

`./mach build` seems to work fine, so this just affects the `check` command.

cc @asajeffrey

**Comment by jonleighton** [comment]
Aha, we should only be `use`-ing the `task_info` crate on `macos` anyway: https://github.com/servo/servo/blob/bcdb82b83fcf652a29ba49cf1fe032299d26e52c/components/profile/mem.rs#L368-L369

So it seems like the [conditional compilation attribute](https://doc.rust-lang.org/reference/attributes.html#conditional-compilation) is not working properly on this earlier version of rustc.

**Comment by jonleighton** [comment]
I tried to find a Rust commit/issue relating to this, but failed

**Comment by SimonSapin** [comment]
This likely regressed in https://github.com/servo/servo/pull/19574 , which downgraded the compiler to work around a compiler bug but unfotunately downgraded Cargo at the same time. We can upgrade again when we find a proper fix for https://github.com/servo/servo/issues/19519.

In the meantime, try `./mach check -p servo`.

**Comment by asajeffrey** [comment]
Oh great. AFAICT there is currently no rustc version which can build servo successfully. We either hit this bug or #19519, sigh.

**Comment by jonleighton** [comment]
Note that it only affects `./mach check`, not `./mach build`, so the status quo isn't a total disaster

**Comment by SimonSapin** [comment]
I just checked, `./mach check -p servo` works.
