### ISSUE TITLE
Docs on creating servo-based programs

### ISSUE THREAD

**Issue by WesleyAC** [servo/servo#19639]
I am interested in using servo in a program that I'm working on, but I'm having a bit of trouble figuring out how to to this - particularly because of the build system. I've cloned servo and taken a look at `components/servo` and `ports/servo/main.rs`, and I think I understand the API.

Normally, at this point, I'd `cargo add servo` and be on my way - but I'm not sure what role `mach` plays in this, or what the suggested way(s) to consume it are.

I think that it'd be quite useful to have docs on this, but I'm not really sure where to start on this. Do folks have any suggestions for where to look to figure this out/examples? I took a look at browser.html, but I'm having a hard time figuring out where things live in that project, so it hasn't been super helpful to me.

Thanks!

**Comment by jdm** [comment]
https://github.com/paulrouget/servoshell/#build is the best model for this right now.

**Comment by jdm** [comment]
https://github.com/paulrouget/servo-embedding-example is even more what you're looking for.

**Comment by tigercosmos** [comment]
https://github.com/glennw/servo-shell

**Comment by WesleyAC** [comment]
Thanks @jdm, the servo-embedding-example repo looks really useful 👍. Would it be reasonable to add a link to it in the readme or docs?

**Comment by tigercosmos** [comment]
In my opinion, maybe not in README, because it is not an official project related to this project?
However seems good to have a `Resource` wiki with these information.
