### ISSUE TITLE
do a project

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19643]
@jdm,
I would like to do a project. Maybe part of a long-term work, or implement APIs in a module.
Something need to do in-depth study. Not just fix issue by issue.
Could you give suggestion to me. thanks! :)

**Comment by CYBAI** [comment]
AFAIK, you can check the label of ["B-interesting-project"](https://github.com/servo/servo/labels/B-interesting-project) first to see if there's any project you'd like to try.

**Comment by tigercosmos** [comment]
Sure. Maybe I can pick one.
