### ISSUE TITLE
[Wiki: Browser-Engine-Research] link Failure

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19657]
https://github.com/servo/servo/wiki/Browser-Engine-Research
some links are failed.

- Who killed my battery?: Analyzing Mobile Browser Energy Consumption
- Measuring Browser Performance
- Browsing web 3.0 in 3.0 watts

I didn't check all.

cc @rzambre

**Comment by tigercosmos** [comment]
May I have the authority to edit wiki to fix them?

**Comment by CYBAI** [comment]
For the third one, I only found its [abstraction](http://people.csail.mit.edu/rabbah/conferences/08/cgo/stmcs/keynote-abstract-bodik.txt).

**Comment by rzambre** [comment]
I have updated the broken links on the wiki page. Unfortunately, some of the documents seem to have been taken down by the authors/organizations. Or at least, I haven't been able to find them. In the list, I have annotated the documents that no longer exist. If you happen to find them, please let me know here and I will update the list.
