### ISSUE TITLE
Correct background-attachment: fixed

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#19669]
Element backgrounds with `background-attachment: fixed` should not be scrolled with the window contents. They should stay attached to the viewport all the time.

Testing this:

1. Go to https://staktrace.github.io/moz-pages/bug/1368496/
2. In the upper left corner a quadratic image should be shown.
3. Scroll a bit. The square should not move.
4. Scroll to the end of the page. The whole page should be blank. (Assuming usual screen resolution.)

(Currently something like absolute positioning is implemented.)

**Comment by paulrouget** [comment]
Is it an "easy fix"?

We run into that issue in the HoloLens landing page. Wondering if we should fix servo or add a temporary workaround in the page CSS?

**Comment by jdm** [comment]
I recommend working around it.
