### ISSUE TITLE
Move -moz-border-*-colors outside of mako.

### ISSUE THREAD

**Issue by mauricioc** [servo/servo#19671]
I'd like to take this one after #19021, since it's in the same file. Part of #19015.

**Comment by emilio** [comment]
These properties are gone in https://bugzilla.mozilla.org/show_bug.cgi?id=1429723 / https://github.com/servo/servo/pull/19446 / https://github.com/servo/servo/pull/19833.

@mauricioc I cherry-picked one of your commits for #19668 (thank you so much!). If you want to help out either with more CSS properties or with a more complex task / fix, I'll be happy to try finding something :)
