### ISSUE TITLE
Directly build WebRender display lists

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#19676]
The [*webrender_helpers.rs* file](https://github.com/servo/servo/blob/9187c9a093860d9f3c31b5a5f402458aa4a607cb/components/layout/webrender_helpers.rs#L5-L8)
starts with this comment:

> TODO(gw): This contains helper traits and implementations for converting Servo display lists
>           into WebRender display lists. In the future, this step should be completely removed.
>           This might be achieved by sharing types between WR and Servo display lists, or
>           completely converting layout to directly generate WebRender display lists, for example.

Currently two display lists are build in Servo.
First an internal one using GFX and app units is build.
Then another one using WebRender and screen pixels is derived from the internal one.
The internal display list is discarded without be used much.

This has several downsides:
* Duplicate definitions. Many types are defined both in WebRender and Servo/GFX.
* To support new features both WebRender and internal display lists need to be updated.
* Some memory and speed overhead from constructing every display list twice
* ...

I think this can be split into the following tasks:
* [x] Create a file *layout/webrender_conversions.rs*
    with a single trait called `IntoLayout`.
    The trait has a method `fn into_layout(&self) -> T`
    that returns for a CSS type or measurement its
    WebRender representation. It should be implemented
    for all Servo types that have a WebRender twin.
    There is an [old attempt at doing this](https://github.com/pyfisch/servo/blob/153b695a22314bc4620d8088e48788cd238560f4/components/layout/to_layout.rs).
    It replaces the various conversion traits found in *webrender_helpers.rs*.
* [x] Change [GFX Display List item types](https://github.com/servo/servo/blob/master/components/gfx/display_list/mod.rs)
    to use WebRender types for values, points and sizes where possible.
* [ ] Change `-Z dump-display-list` from printing GFX display lists
    to printing WebRender display lists. Luckily servo/webrender#2232
    adds display list serialization to WebRender in both an easy to read
    format (RON) but also in JSON (both using serde).
* [x] Move the background and gradient calculation from
    *display_list_builder.rs* to their own file. They do not depend on
    the other layout and the current file already has 3400+ lines.
* [ ] Directly build WebRender display lists in Servo and remove
    the GFX types entirely.

Is it a good idea to change display list building as described?
What needs to be sorted out before I start coding?

**Comment by glennw** [comment]
cc @mrobinson for comments.

**Comment by mrobinson** [comment]
This sounds like a good plan to me. I think the main barrier to the last step is https://github.com/servo/webrender/issues/2227. We need to allow holding onto unserialized WebRender display lists due to the fact that we generate display list items and then, only later, sort them according to CSS stacking context rules.

**Comment by pyfisch** [comment]
> We need to allow holding onto unserialized WebRender display lists due to the fact that we generate display list items and then, only later, sort them according to CSS stacking context rules.

I thought about using the `debug-serialization` types as unserialized display lists. They can be build from individual items and then directly serialized to a `BuiltDisplayList` after ordering.

Is this a good idea or will it be to slow/consume too much memory? 

Also `DisplayListBuilder` currently does some normalization (e.g. for gradients) that should not be skipped even if display lists are built from `debug-serialization` items.

**Comment by mrobinson** [comment]
@pyfisch I think we should avoid running through the serialization pass for this, since serialization/deserialization performance has consistently been an issue with WebRender display lists.

**Comment by mrobinson** [comment]
I think we can close this one. Layout 2020 has always used WebRender display lists directly, apart from the "stacking context tree" concept.
