### ISSUE TITLE
Browser.html tile corners no longer rendered correctly

### ISSUE THREAD

**Issue by atouchet** [servo/servo#19680]
![Tiles](https://i.imgur.com/u7pCZT6.png)

The rounded corners are now no longer clipped and instead the tiles are rendered as full rectangles. This is a recent regression as previous builds did not exhibit this issue. Tested in Windows 10.

**Comment by atouchet** [comment]
@pyfisch is this due to #19649?

**Comment by pyfisch** [comment]
Yes this is #19649.

**Comment by atouchet** [comment]
I didn't notice this previously but the tiles images aren't centred properly now either. Is that related or a separate issue?

**Comment by pyfisch** [comment]
@atouchet Thanks for catching it. That the tiles are not centered properly is caused by #19651. The `box-sizing: border-box` throws the calculations off.
