### ISSUE TITLE
Intermittent failure in /fetch/http-cache/invalidate.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#19695]
```
  ▶ Unexpected subtest result in /fetch/http-cache/invalidate.html:
  │ FAIL [expected PASS] HTTP cache invalidates after a successful response from a POST
  │   → assert_equals: Response status expected 200 but got 500
  │ 
  └ make_test/</<.code/<@http://web-platform.test:8000/fetch/http-cache/http-cache.js:163:17
```

**Comment by nox** [comment]
Any way we could get the Python stacktrace somehow? `http-cache.py` does not explicitly return a 500 error ever from that particular test, AFAICT.

**Comment by jdm** [comment]
If we're lucky it might be in the log for that build. I guess the easy way to check is to raise an exception in that file and run it locally to see.
