### ISSUE TITLE
Verify that all values in include.ini represent real directories

### ISSUE THREAD

**Issue by jdm** [servo/servo#19703]
`tests/wpt/include.ini` is a list of subdirectories of `tests/wpt/web-platform-tests.` For every entry, we should be able to verify that an actual directory exists with the same name, and report an error as part of `./mach test-tidy` otherwise.

Code: https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py (add a new check that is invoked from [scan](https://github.com/servo/servo/blob/master/python/tidy/servo_tidy/tidy.py#L1111))
Tests: add a new test that is executed as part of [./mach test-tidy --self-test](https://github.com/servo/servo/blob/master/python/tidy/servo_tidy_tests/test_tidy.py)

**Comment by stevel98** [comment]
@highfive: assign me

**Comment by stevel98** [comment]
Also, to parse `include.ini` I'm thinking of using `py.iniconfig`. However, I'm having trouble importing this because it lives in `servo/tests/wpt/web-platform-tests/tools`, which I can't import in `__init__.py` because of the hyphens in the path.

**Comment by jdm** [comment]
_mozilla is a special case that maps to tests/wpt/mozilla/tests/mozilla. The trick to importing that module is to add tests/wpt/web-platform-tests/tools to the import path; there are several other scripts that do that, possibly in tests/wpt/run_wpt.py?

**Comment by terracotaPie** [comment]
Hey @stevel98 - are you still working on this or **can I take over** :) ?

**Comment by stevel98** [comment]
Apologies, school just started and I've been really busy. It's all yours :).

**Comment by terracotaPie** [comment]
@highfive: assign me

**Comment by jdm** [comment]
Go for it @terracotaPie :)

**Comment by terracotaPie** [comment]
@jdm thanks - Gonna work on it tonight

**Comment by terracotaPie** [comment]
@jdm I was wondering if there are any restrictions on what we can include in the codebase, i.e. Can I use  [default config parser](https://docs.python.org/2/library/configparser.html)

**Comment by jdm** [comment]
@terracotaPie If that does that job, that's fine.

**Comment by terracotaPie** [comment]
@jdm Yeah it doesn't parse the file correctly but I can use simple regex
```python
    with open(ini_path) as f:
        for line in f:
            m = re.search(r"\[([A-Za-z0-9_]+)\]", line)
            if m is not None:
                test_folders.append(m.group(1))
    print(test_folders)
```

which gives me
```python
['_mozilla', '2dcontext', 'cors', 'css', 'compositing', 'CSS2', 'cssom', 'geometry', 'mediaqueries', 'selectors', 'cssom', 'dom', 'domparsing', 'encoding', 'eventsource', 'fetch', 'FileAPI', 'fullscreen', 'html', 'js', 'submission', 'Opera', 'script_scheduling', 'quirks', 'selectors', 'typedarrays', 'uievents', 'url', 'WebCryptoAPI', 'webgl', 'WebIDL', 'websockets', 'webstorage', 'workers', 'XMLHttpRequest']
```

And i understand that _mozilla is a special case, but for every other single entry we need to check if its present in "tests/wpt/web-platform-tests" right? We also need to respect the indentation as nested path?

Thanks for your time

**Comment by jdm** [comment]
Exactly.

**Comment by terracotaPie** [comment]
Damn - So I edited the path and loaded the py.iniconfig but it doesn't parse it correctly, since it doesn't expect the offsets
```python
    sys.path.append(wpt_path("web-platform-tests", "tools", "third_party", "py"))
    from py.iniconfig import IniConfig
    configss = IniConfig(ini_path)
```

Welp ill try to parse it

**Comment by jdm** [comment]
You could also see if you could reuse the test harness code that interacts with that file: https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/manifestinclude.py

**Comment by terracotaPie** [comment]
Worked nicely

**Comment by terracotaPie** [comment]
@jdm success !!! Ill submit a pull request, when I add proper messages. My work is here https://github.com/terracotaPie/servo/commit/23bfb54ab24e24c82e9b338e090a23eaf25ee115

```bash
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/_mozilla
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/animation-timing
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/cssom
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/cssom-view
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/css-values
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/old-tests/submission/Opera
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/old-tests/submission/Opera/script_scheduling
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/selectors
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/typedarrays
error /Users/terrpi/Development/servo/tests/wpt/web-platform-tests/XMLHttpRequest
```

**Comment by jdm** [comment]
This is great! Also disturbing that we're no longer running all of those tests any more 🙃
