### ISSUE TITLE
2018 Roadmap?

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#19708]
The old 2017 roadmap is still linked from https://servo.org.

https://github.com/servo/servo/wiki/Roadmap

**Comment by LifeIsStrange** [comment]
What about an Android client ? 
Currently from my understanding, servo mostly support Android but we can't use it because there is no UI.

**Comment by tigercosmos** [comment]
A new repo that does a simple UI with servo sounds good.

**Comment by LifeIsStrange** [comment]
@tigercosmos There were this project but it seems dead https://github.com/servo/servo/issues/15776
I Also believe that @MortimerGoro has an early android browser for doing his WebVR demos :)
https://blog.mozvr.com/samsung-gear-vr-support-lands-in-servo/

**Comment by aneeshusa** [comment]
cc @metajack 
An updated roadmap would be appreciated :)

**Comment by atouchet** [comment]
@jdm is the plan still to use this roadmap? It hasn't been properly updated since you added the Q1 2017 info.

**Comment by jdm** [comment]
No; the information on that page does not reflect the project's current priorities.

**Comment by atouchet** [comment]
So there are no plans to update it then? If that is the case it probably shouldn't be promoted on servo.org.

**Comment by jdm** [comment]
I have just finished updating the page with an official roadmap for 2018.

**Comment by atouchet** [comment]
Good to see the roadmap being updated!

@jdm this is probably getting a bit off topic but will the Pathfinder integration bring SVG support to Servo or does more work still need to be done for that?

**Comment by metajack** [comment]
Pathfinder brings the ability to render the primitives SVG will need. SVG parsing and display list item creation will still need to be done.

**Comment by metajack** [comment]
Also, the first integration will use Pathfinder for fonts. We'll expand from there.

**Comment by LifeIsStrange** [comment]
@metajack any update for the pathfinder integration ? It has already merged in webrender since many months.
