### ISSUE TITLE
<textarea> placeholder doesn't line break on explicit U+000D CARRIAGE RETURN (CR)

### ISSUE THREAD

**Issue by KwanEsq** [servo/servo#19717]
(Unless they're raw carriage returns in the file source, in which case they (I think) get converted during parsing)

Test case: http://kwan.perix.co.uk/mozilla/ta-ph-cr.html
![screenshot from 2018-01-07 22-47-22](https://user-images.githubusercontent.com/1735753/34655362-0508bfb4-f400-11e7-8770-4d3bcdef28c3.png)

Multiline CR in actual content was also unsupported until #19358  

Spec:
> All U+000D CARRIAGE RETURN U+000A LINE FEED character pairs (CRLF) in the hint, as well as all other U+000D CARRIAGE RETURN (CR) and U+000A LINE FEED (LF) characters in the hint, must be treated as line breaks when rendering the hint. 

https://html.spec.whatwg.org/multipage/form-elements.html#attr-textarea-placeholder

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1391044 which fixed not supporting multiline placeholder at all in Firefox and added WP tests for this
https://github.com/w3c/web-platform-tests/commit/a13e919f2c3c62cc87eb3fb4b9e139d8dec3a588

Chrome currently has the same bug, see https://bugs.chromium.org/p/chromium/issues/detail?id=791194

**Comment by nox** [comment]
@jdm Could we have a wptup to reuse https://github.com/w3c/web-platform-tests/commit/a13e919f2c3c62cc87eb3fb4b9e139d8dec3a588?
