### ISSUE TITLE
rust-lang.org redirect issue

### ISSUE THREAD

**Issue by atouchet** [servo/servo#19726]
URL: https://www.rust-lang.org/

Steps to reproduce:

1. Launch Servo with Browser.html.
2. Click Rust tile.
3. Click the "Click here to be redirected" link.
4. Instead of loading the Rust website Servo is instead redirected to the Browser.html start screen.

Tested in Windows 10.

**Comment by CYBAI** [comment]
I can reproduce it on macOS Sierra 10.12.6.

**Comment by atouchet** [comment]
This now appears to be working properly in the latest nightly build.
