### ISSUE TITLE
Remove out-of-date FIXME comments from domimplementation.rs

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#19723]
There are two FIXME comments in domimplementation.rs: https://github.com/servo/servo/blob/02f1864770c108a47b3c83c3d89293222cb6dfcf/components/script/dom/domimplementation.rs#L117 and https://github.com/servo/servo/blob/02f1864770c108a47b3c83c3d89293222cb6dfcf/components/script/dom/domimplementation.rs#L186 which refer to a closed issue #1522.

Both of these FIXME comments should be replaced by "The origin is already set".

**Comment by hindenbug** [comment]
@highfive: assign me
