### ISSUE TITLE
Can we not use automatic gitignore generation in fontconfig?

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#1972]
(There is no issue tracker for [mozilla-servo/fontconfig](https://github.com/mozilla-servo/fontconfig), so I'm posting here.

Fontconfig uses [automatic gitignore generation](https://github.com/mozilla-servo/fontconfig/blob/master/git.mk). However, this means that the submodule for fontconfig turns up in `git status`, and a `git diff` shows that it's been made a "dirty" submodule.

Could we go back to a static gitignore? Alternatively, can we put the generated object files in build/ or a similar place?

**Comment by mbrubeck** [comment]
I think this is fixed at least for the Servo build, by the switch from submodules to Cargo packages.
