### ISSUE TITLE
Update to gl_generator 0.8.0

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#19735]
It contains the fix for https://github.com/servo/servo/issues/19519. We need to update it in:

* [ ] gleam
* [ ] glx
* [x] offscreen_gl_context
* [ ] rust-webvr
* [ ] servo-glutin

**Comment by Eijebong** [comment]
Copy/pasting the list since I can't edit it ;)


- [ ] https://github.com/servo/gleam/pull/138
- [ ] glx
- [ ] offscreen_gl_context
- [ ] rust-webvr
- [ ] servo-glutin
