### ISSUE TITLE
Run reftests with explicit number of layout tasks

### ISSUE THREAD

**Issue by jdm** [servo/servo#1975]
Just as we test both CPU and GPU rendering, we should also run layout reftests with only one task as well as >1 to test parallel and sequential codepaths. Alternatively, if that doesn't make sense, we should probably force >1 task even on machines that default to 1.

**Comment by edunham** [comment]
@shinglyu Checking how badly these changes have bitrotted and moving them into [mach](https://github.com/servo/servo/tree/master/python/servo) might be of interest

**Comment by shinglyu** [comment]
@edunham : My initial investigation shows that the `./mach test-ref` was removed in https://github.com/servo/servo/issues/10125
But the old [wiki](https://github.com/servo/servo/wiki/Testing) is not updated. 

There are something in `tests/wpt` that looks like a reftest but seems not being used: https://github.com/servo/servo/tree/e273517fe06720afe0ef74815cce5e007df7dc3d/tests/wpt/harness/test/testdata/reftest

And there are many css tests in wpt that looks like a reftest. I'm still trying to figure out if they are actually ran or not.

**Comment by edunham** [comment]
@jdm Where do the layout reftests currently live, or how should one find them? (or is this issue obsoleted by the removal of test-ref?)

**Comment by jdm** [comment]
The majority of reference tests live in tests/wpt/css-tests/ and tests/wpt/mozilla/tests/css/, and are executed via https://github.com/w3c/wptrunner/blob/051a236f1443b04df93e57a468f9a8a8db40722f/wptrunner/executors/executorservo.py#L204 .

**Comment by shinglyu** [comment]
@edunham @jdm Perhaps we should add a `-j N` parameter to `test-wpt`? This will affect other non-reftest wpt tests, but I guess it's OK? 

Or maybe use `--layout-task`, which is more specific than `-j/--jobs`.
