### ISSUE TITLE
Show paragraph incorrectly in learnyouahaskell

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19767]
URL: http://learnyouahaskell.com/making-our-own-types-and-typeclasses

The paragraph shouldn't overlap the image.

In Firefox Nightly:

![image](https://user-images.githubusercontent.com/6782666/34918688-b322fb96-f991-11e7-833c-213b1b6569b3.png)

In Servo (built with 1b46e2e759):

![image](https://user-images.githubusercontent.com/6782666/34918702-d5202c50-f991-11e7-8a19-3667a4c33cae.png)

Tested in `macOS Sierra 10.12.6`.

**Comment by mrobinson** [comment]
This appears to be working in non-legacy layout, so I'm going to go ahead and close this one. This is part of our effort to start closing bugs that only affect legacy layout. Apologies for the noise.
