### ISSUE TITLE
consider `min`, `max`, `step` for range type input element

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#19773]
need consider `min`, `max`, `step` for range type input element, when they are implemented
this will continue #19761

see 
- https://html.spec.whatwg.org/multipage/input.html#range-state-(type=range):value-sanitization-algorithm
-  https://html.spec.whatwg.org/multipage/#rules-for-parsing-floating-point-number-values

**Comment by tigercosmos** [comment]
@KiChjang Could you suggest how to implement min, max, step?

**Comment by jdm** [comment]
#21952 was an in-progress attempt to solve this that stalled after the first review.

**Comment by pshaughn** [comment]
There are WPT tests for this in html/semantics/forms/the-input-element/range.html; some of the tests also need the stepUp and stepDown methods to synthetically test step behavior (#25386)

**Comment by pshaughn** [comment]
Bad tests aren't making this easier: https://github.com/web-platform-tests/wpt/issues/20929

**Comment by pshaughn** [comment]
https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number):value-sanitization-algorithm says the type=number input "may" round if a number has a step mismatch, but https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/number.html specifically wants unrounded. I'm not sure if this is a too-loose spec or a too-tight test, but either way it's easiest to just leave numbers unrounded.
