### ISSUE TITLE
Passing a single string as a sequence<DOMString> generates a Vec<DOMString>

### ISSUE THREAD

**Issue by ferjm** [servo/servo#19776]
With an interface like:

```idl
dictionary BarOptions {
  required sequence<DOMString> baz;
};

interface Foo {
  void bar(BarOptions options);
};
```

passing a single string like:

```javascript
  var foo = new Foo();
  foo.bar({ baz: "string"});
```

generates a `[DOMString("s"), DOMString("t"), DOMString("r"), DOMString("i"), DOMString("n"), DOMString("g")]`.

I believe this should throw a TypeError instead, like in https://github.com/w3c/web-platform-tests/blob/master/performance-timeline/po-observe.any.js#L12

**Comment by SimonSapin** [comment]
https://heycam.github.io/webidl/#es-sequence defines that a WebIDL `sequence<T>` is created from a JS object through its `@@iterator` method, which for strings iterate over the code points. So this behavior looks expected?

**Comment by ferjm** [comment]
I am not sure ... https://github.com/heycam/webidl/issues/266 Is DOMString a string wrapper?

**Comment by saschanaz** [comment]
Can't reproduce this:

```js
new MutationObserver(() => {}).observe(document.body, { attributeFilter: "abc" });
// TypeError: Value is not an object, as expected.
```
