### ISSUE TITLE
<tr> backgrounds aren't drawn correctly

### ISSUE THREAD

**Issue by KwanEsq** [servo/servo#19788]
Other browsers seem to render `tr { background-color: black }` the same as  `tr > th, tr > td { background-color: black }`.  Servo does not. (Not sure where that's spec'ed, or even if it is)

Testcase: http://kwan.perix.co.uk/mozilla/tableRowBackgroundTest.html
(Correct rendering emulated on hover using cell backgrounds)

Servo rendering:
![screenshot from 2018-01-16 22-50-32](https://user-images.githubusercontent.com/1735753/35016320-e4d40df4-fb0f-11e7-96e1-0f095e2b6aa8.png)

Firefox rendering:
![screenshot from 2018-01-16 22-51-31](https://user-images.githubusercontent.com/1735753/35016409-4a5a309a-fb10-11e7-87d6-c05ca1074665.png)

**Comment by emilio** [comment]
Thanks for the report @KwanEsq!

Testcase for posterity, with some superfluous tag removal:

```html
<!doctype html>
<meta charset="UTF-8">
<title>Servo table row background test</title>
<style>
  tr:not(:hover),
  tr:hover > td {
    background-color: black;
    color: white;
  }
</style>
</head>
<table>
  <tr><td>testing</td></tr>
</table>
<table>
  <tr><td>testing</td><td>testing</td></tr>
</table>
<table>
  <tr><td>testing</td><td>testing</td><td>testing</td></tr>
</table>
<table>
  <tr><td>testing</td><td>testing</td><td>testing</td><td>testing</td></tr>
</table>
```

**Comment by mbrubeck** [comment]
This behavior is specified here: https://drafts.csswg.org/css2/tables.html#table-layers

> the background covers exactly the full area of all cells that originate in the row, even if they span outside the row, but this difference in area does not affect background image positioning.

**Comment by mbrubeck** [comment]
[`TableRow::build_display_list`] is currently responsible for drawing this background.  It delegates to a `BlockFlow` method, which doesn't know about the special rules for table row/column/rowgroup/colgroup background areas.

Perhaps `FragmentDisplayListBuilding::build_display_list_for_background_if_applicable` should not draw any background for table rows (or columns, or rowgroups, or colgroups).  Instead, each table cell fragment could draw the backgrounds for each of these, in the layer order from the spec above.  The TableCell flow would need access to the styles of its containing row/column flows (or at least their background properties).

[`TableRow::build_display_list`]: https://github.com/servo/servo/blob/e19bab84cf43c43930d7493840444a8ee2af1e8b/components/layout/table_row.rs#L470-L481
