### ISSUE TITLE
Flexbox content shows incorrectly

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19784]
URL: http://flexboxfroggy.com/

The frogs are missing in servo.
Besides, the font seems wrong in servo as well.
Not sure if this one is related to #18837

In Firefox Nightly:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/6782666/34984747-ea6664b0-faec-11e7-9c51-0e259c1c72b0.png">

In Servo (built with 7de87c487b):
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/6782666/34984778-fd7eade6-faec-11e7-9a14-0a3776be78cc.png">

Tested in `macOS 10.12.6`

**Comment by CYBAI** [comment]
After more investigation for the page, I found the images for the frog and lilypad are `SVG`s.
It should be related to #9998 so I'm going to close this issue due to not related to flex.

![image](https://user-images.githubusercontent.com/6782666/35474264-cca9bc78-03c6-11e8-8652-b789589b4ce8.png)

**Comment by jdm** [comment]
Thanks for checking!
