### ISSUE TITLE
Update style-derive to syn 0.12

### ISSUE THREAD

**Issue by mystor** [servo/servo#19786]
Potentially this could allow builds of servo on nightly to get the improved error messages and other semantics which come from the new span system and `proc-macro` APIs.

`synstructure` has been updated already, although the API has changed since the last version which style-derive used. If there are any APIs or new features which you need in `synstructure` to help port the derives over, let me know. Ideally I'd like to make the `cg` module in style-derive unnecessary, as the features you need are in `synstructure`.

cc @nox

**Comment by upsuper** [comment]
So external dependencies which depend on `syn` are:
- [x] cssparser
- [x] cssparser-macros
- [x] darling_core
- [x] darling_macro
- [ ] html5ever
- [ ] serde_derive
- [ ] serde_derive_internals
- [x] synstructure

**Comment by upsuper** [comment]
The hard parts would be html5ever and serde.

**Comment by Eijebong** [comment]
Nah, html5ever is done and serde too

**Comment by Eijebong** [comment]
The hard part for me is style_derive, other servo crates are already done but I couldn't find time/motivation for style_derive...
https://github.com/servo/servo/compare/master...Eijebong:syn?expand=1 here's my work on servo crates

**Comment by upsuper** [comment]
Serde's repo is done, but the version published on crates.io hasn't been updated.

**Comment by Eijebong** [comment]
Sure, html5ever hasn't even been merged, cssparser hasn't been released either but those are the easy parts, releasing stuff is easy ;)

**Comment by upsuper** [comment]
Maybe @nox can help on the style_derive part.

**Comment by Eijebong** [comment]
I just need to find some time to do it but @nox made be buy Celeste so I'm blaming him for the update being late ;)
