### ISSUE TITLE
Measure time required before a layout query is serviced by the layout thread

### ISSUE THREAD

**Issue by jdm** [servo/servo#19795]
Servo uses a separate thread for performing layout from the thread that runs JS. When JS code triggers a synchronous layout query (such as the `getBoundingClientRectangle` API), we would like to track how long it takes before the layout thread notices the query and starts to act on it. To do this, we should include a timestamp in the query message that is sent to the layout thread, record the time since the timestamp when the message is processed, and store this data in a histogram bucket. When shutting down a layout thread, we can print the histogram data to stdout. This will show us the distribution of how long layout queries had to wait before they were acted upon throughout Servo's lifetime.

Code:
* `components/script_layout_interface/message.rs` (extract all the query messages from ReflowGoal into a separate enum, and replace them with a new variant that contains the u64 timestamp and enum value)
* `components/layout_thread/lib.rs` (treat the start of `handle_reflow` as when to record a new timestamp for having handled a query)
* `components/script/dom/window.rs`

I recommend starting with printing out the time immediately when processing a query. Once that's working, adding histogram support by adding more fields to LayoutThread to store the data and print it out in LayoutThread::exit_now will be easier.

Note: this is intended as a student project. Please talk to me before starting to working on it.

**Comment by jdm** [comment]
This is available for anybody who is interested in working on it.

**Comment by csmoe** [comment]
I'll work on it.

**Comment by jdm** [comment]
Great! Please ask questions if anything is unclear!

**Comment by csmoe** [comment]
@jdm When I tried to `./mach test unit`, it complained:
```
error: failed to load source for a dependency on `osmesa-src`                   

Caused by:
  Unable to update https://github.com/servo/osmesa-src#6d23daed

Caused by:
  error inflating zlib stream; class=Zlib (5)
```
`cargo vendor` Output:
```
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to load source for a dependency on `osmesa-src`

Caused by:
  Unable to update https://github.com/servo/osmesa-src#6d23daed

Caused by:
  error inflating zlib stream; class=Zlib (5)
```
I have searched for this error, but those discussions didn't help.

**Comment by jdm** [comment]
Does this happen as part of the regular `./mach build` too?

**Comment by csmoe** [comment]
Yes, this error can be reproduced with `./mach build -d` or `-r`

**Comment by jdm** [comment]
What operating system are you using?

**Comment by csmoe** [comment]
os: ManjaroLinux - linux kernel 4.14.20-2-MANJARO
rustc: rustc 1.25.0-nightly (15a1e2844 2018-01-20)
cargo: cargo 0.26.0-nightly (6a8eb71f6 2018-01-13)

**Comment by jdm** [comment]
That's an error message that comes from libgit2, which Cargo relies on. I have no idea what to recommend, unfortunately. You may want to file an issue in https://github.com/rust-lang/cargo/.
