### ISSUE TITLE
Code block stretched accidentally

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19794]
URL: http://learnyouahaskell.com/making-our-own-types-and-typeclasses

The code block is created by `ol` and `li` elements like following picture
![image](https://user-images.githubusercontent.com/6782666/35055447-3276317e-fbea-11e7-996b-1c26bbe74d63.png)

After scrolling down to the `Record Syntax` section in the page, then we can see the code block stretching accidentally.

In Firefox Nightly:
![image](https://user-images.githubusercontent.com/6782666/35055319-e22eb92a-fbe9-11e7-943e-fe8524118fd9.png)

In Servo (built with 4f09987611):
![image](https://user-images.githubusercontent.com/6782666/35055275-c6aab30c-fbe9-11e7-8758-2f6807c4479c.png)

Tested in `macOS 10.12.6`

**Comment by kanaka** [comment]
Viewing the page a build of 6af8258 (on Ubuntu 16.04.2) does not seem to exhibit the stretching problem for me (although page scrolling even more janky on that page than normal).

**Comment by jdm** [comment]
On macOS there is also no stretching, and scrolling is totally smooth on a nightly build (as long as the mouse doesn't scroll over the code blocks, which halt scrolling completely).

**Comment by jdm** [comment]
Filed #24028 for the scrolling issue.
