### ISSUE TITLE
Hard crash when navigating to allmusic.com

### ISSUE THREAD

**Issue by Max-E** [servo/servo#19800]
This is on 64-bit Linux Mint 18, corresponding to Ubuntu 16.04. I was able to reproduce this on git hashes 1b46e2e7597e90a41c6bfb3bd7008bdd922c93c6 and 8612a87ed28bbc4b9050e47b3bc4d49ea076a1cf. Servo was built with "./mach biulld -rv" and run with "./mach run -r -- http://allmusic.com". Here is the full command line output including backtrace:
https://pastebin.com/psBmB7iA
If you're unable to reproduce and you'd like me to try any additional troubleshooting steps, let me know.

**Comment by jdm** [comment]
Same failure reported in https://github.com/servo/servo/issues/18690, so let's track it there. Thanks for reporting it!
