### ISSUE TITLE
Implement mutation observers

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#1980]
http://dom.spec.whatwg.org/#mutation-observers

**Comment by jdm** [comment]
I propose a simple implementation where a `mutation_observers` vector is added to `Node`, and they get notified every time `Node::insert`, `Node::replace_all`, `Node::remove`, `Element::do_set_attribute`, and `Element::remove_attribute` are called. For subtree observers, this will require checking the ancestors of mutated nodes as well.

**Comment by pcwalton** [comment]
Now that we have userscripts, this should be the last missing piece blocking integration of canvg for SVG support.

**Comment by nox** [comment]
@jdm Not only nodes will need the mutation observers machinery. I would like to use them between URLSearchParams and URL too, for example.

**Comment by jdm** [comment]
Closing in favour of #6633.
