### ISSUE TITLE
Implement Element::has_css_layout_box() and related methods by inspecting the computed style

### ISSUE THREAD

**Issue by jonleighton** [servo/servo#19811]
This is a follow-up to #19803 [suggested by @emilio](https://github.com/servo/servo/pull/19803#pullrequestreview-89779418).

> Yeah, this should be enough I think... I was expecting a query that returned an `Option<Arc<ComputedValues>>`, and we'd just need to check the display value (because nodes under display: none subtrees don't have any style).
>
> That would be useful on its own to implement the other overflow_x / y and other style queries in a fast way, but this also works :)

I'll look into it once that PR is merged.

**Comment by jonleighton** [comment]
@emilio I just had a preliminary look at what this involves, and noticed that there is already a [`margin_style` query](https://github.com/servo/servo/blob/d11886e9a12c2ef7262e34de3de7595005a66080/components/script_layout_interface/rpc.rs#L36) which returns a subset of the computed styles. Do you think it would make sense to replace that with a more generic one which returns all the computed styles? Is there a danger of copying around too much data here?

**Comment by emilio** [comment]
Yes, I think it makes sense to remove `margin_style`.

And no, there's not much danger of copying too much data. Styles are stored as an `Arc<ComputedValues>`, so returning the style is literally just a refcount bump (an arc clone)
