### ISSUE TITLE
Remove the define_css_keyword_enum! and add_impls_for_keyword_enum macros.

### ISSUE THREAD

**Issue by emilio** [servo/servo#19827]
There should be no need for them since we now derive `Parse` for keywords (7036cb0077).

We should remove all the uses for those macros like 4abd1dc819 does. There are still a few though!

It's ok to remove them one by one, or to do all on the same PR (there aren't that many I think).

**Comment by AlexFJW** [comment]
@highfive: assign me

**Comment by nox** [comment]
I'm sorry, I did this in #19903, unaware of this issue.

**Comment by alexfjw** [comment]
No problem. Was a little busy the past week so I haven't really made much progress actually.

**Comment by alexfjw** [comment]
@highfive unassign me
