### ISSUE TITLE
./mach clean-cargo-cache does not properly default to cleaning ~/.cargo

### ISSUE THREAD

**Issue by nox** [servo/servo#19823]
<s>The command `./mach clean-cargo-cache` should check whether `./.servobuild`'s `cargo-home-dir` setting is defined and use that by default.</s>

Now that `cargo-home-dir` is no more, `./mach clean-cargo-cache` needs to be updated to default to `~/.cargo` if `CARGO_HOME` isn't set.

**Comment by SimonSapin** [comment]
`cargo-home-dir` is not a thing anymore. You can set `$CARGO_HOME`, like for every other Rust project.

**Comment by tigercosmos** [comment]
> ./mach clean-cargo-cache needs to be updated to default to ~/.cargo if CARGO_HOME isn't set.

Isn't it now?

**Comment by terracotaPie** [comment]
Good day guys - right now it defaults to topdir i.e.
```python
        if os.environ.get("CARGO_HOME", ""):
            cargo_dir = os.environ.get("CARGO_HOME")
        else:
            cargo_dir = path.join(self.context.topdir, ".cargo")
```

Is it ok if i propose a PR. Namely expanduser should be cross-platform and work on all python versions
```python
        if os.environ.get("CARGO_HOME", ""):
            cargo_dir = os.environ.get("CARGO_HOME")
        else:
            home_dir = os.path.expanduser("~")
            cargo_dir = path.join(home_dir, ".cargo")
```

**Comment by tigercosmos** [comment]
@terracotaPie  Looks good. Go ahead! 👍
