### ISSUE TITLE
Enable css-paint-api WPT tests and remove forked duplicates

### ISSUE THREAD

**Issue by jdm** [servo/servo#19840]
https://github.com/servo/servo/tree/master/tests/wpt/mozilla/tests/mozilla/css-paint-api is a fork we previously made of https://github.com/w3c/web-platform-tests/tree/master/css/css-paint-api. Since we can now use the vendored copy from upstream (https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/css/css-paint-api), we should remove any of the duplicated tests in our copy and [enable](https://github.com/servo/servo/blob/master/tests/wpt/include.ini) the originals.

Use `./mach test-wpt tests/wpt/web-platform-tests/css/css-paint-api` and `./mach test-wpt tests/wpt/mozilla/tests/mozilla/css-paint-api` to run the tests in the two directories.

**Comment by yurket** [comment]
Hi! I would like to contribute to this task! =)
@highfive: assign me

**Comment by yurket** [comment]
Ok, I have all upstream css tests failing on my machine by unknown reason:
```
~/!_coding/servo $ ./mach test-wpt tests/wpt/web-platform-tests/css/css-paint-api
Running 56 tests in web-platform-tests

  ▶ FAIL [expected PASS] /css/css-paint-api/geometry-background-image-tiled-001.https.html
  └   → /css/css-paint-api/geometry-background-image-tiled-001.https.html 23b755622cc81841a23cc8431a6546dfb1401c66
/css/css-paint-api/geometry-background-image-tiled-001-ref.html 62baf6e6218f072ab6f4c7bb0eb31656a3ebbe5d
Testing 23b755622cc81841a23cc8431a6546dfb1401c66 == 62baf6e6218f072ab6f4c7bb0eb31656a3ebbe5d

  ▶ FAIL [expected PASS] /css/css-paint-api/background-image-multiple.https.html
  └   → /css/css-paint-api/background-image-multiple.https.html 23b755622cc81841a23cc8431a6546dfb1401c66
/css/css-paint-api/background-image-multiple-ref.html c482ad9778dc924f902bbd44b49468f39d682de5
Testing 23b755622cc81841a23cc8431a6546dfb1401c66 == c482ad9778dc924f902bbd44b49468f39d682de5
...
```
Looks like something wrong with my setup (I'm on Gentoo), because a lot of tests have the same hash `23b755622cc81841a23cc8431a6546dfb1401c66`. 


I've run tests using `wpt  run` with my local firefox setup and tests are failing as well: 
```
 $ ./wpt run --binary /opt/firefox/firefox-bin firefox css/css-paint-api/
Using certutil /usr/bin/certutil
Using webdriver binary /media/storage/!_coding/servo/tests/wpt/web-platform-tests/_venv/bin/geckodriver
Downloading gecko prefs
 0:04.14 INFO Updating test manifest /media/storage/!_coding/servo/tests/wpt/web-platform-tests/MANIFEST.json
 0:04.14 INFO STDOUT: INFO:manifest:Skipping manifest download because existing file is recent
 0:09.04 INFO STDOUT: INFO:manifest:Updating manifest
 0:18.05 INFO STDOUT: DEBUG:manifest:Opening manifest at /media/storage/!_coding/servo/tests/wpt/web-platform-tests/MANIFEST.json
 0:24.33 INFO Using 1 client processes
 0:24.41 SUITE_START: web-platform-test - running 56 tests
 0:24.41 INFO Running reftest tests
 0:24.41 INFO Starting http server on web-platform.test:8000
 0:24.42 INFO Starting http server on web-platform.test:8001
 0:24.43 INFO Starting http server on web-platform.test:8443
 0:24.69 INFO Setting up ssl
 0:24.71 certutil Full command: /usr/bin/certutil -N -d /tmp/tmpwxBfHW.mozrunner -f /tmp/tmpwxBfHW.mozrunner/.crtdbpw
certutil 
 0:24.74 certutil 
 0:24.76 certutil 
Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

web-platform-tests                                           CT,, 

 0:24.76 INFO Application command: /opt/firefox/firefox-bin --marionette about:blank -profile /tmp/tmpwxBfHW.mozrunner
 0:24.78 INFO Starting runner
 0:25.73 pid:3792 Full command: /opt/firefox/firefox-bin --marionette about:blank -profile /tmp/tmpwxBfHW.mozrunner
pid:3792 1517088415007  Marionette      INFO    Enabled via --marionette
 0:29.49 pid:3792 1517088418762 Marionette      INFO    Listening on port 2828
 0:29.74 TEST_START: /css/css-paint-api/background-image-alpha.https.html
 0:29.95 pid:3792 1517088419231 Marionette      INFO    Testing https://web-platform.test:8443/css/css-paint-api/background-image-alpha.https.html == http://web-platform.test:8000/css/css-paint-api/background-image-alpha-ref.html
 0:30.02 pid:3792 1517088419298 Marionette      INFO    Found 10960 pixels different, maximum difference per channel 255
 0:30.06 TEST_END: FAIL, expected PASS
```

I think I'll try to run servo tests manually as described in tests' [readme](https://github.com/servo/servo/blob/master/tests/wpt/README.md), but meanwhile is there any way to get more info or logs from running `./mach test-wpt tests/wpt/mozilla/tests/mozilla/css-paint-api`? Or running tests manually is the right way?

**Comment by jdm** [comment]
Oh, you'll need to copy the [__dir__.ini](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/meta/mozilla/css-paint-api/__dir__.ini) file that enables the feature at runtime, since it's still experimental. There will still be a number of tests that fail, judging by the ini files in https://github.com/servo/servo/tree/master/tests/wpt/mozilla/meta/mozilla/css-paint-api.

**Comment by yurket** [comment]
Copied [dir.ini](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/meta/mozilla/css-paint-api/__dir__.ini) into `tests/wpt/web-platform-tests/css/css-paint-api/` folder and still all tests are failing. Will try to investigate what's the problem or will ask in irc.

**Comment by jdm** [comment]
Note, the in files needs to be under the metadata directory, not the tests directory.

**Comment by yurket** [comment]
I think I need help again)
Firstly, looks like not all tests fail, but most of them:
```
$ ./mach test-wpt tests/wpt/web-platform-tests/css/css-paint-api
...
Ran 56 tests finished in 85.0 seconds.
  • 4 ran as expected. 0 tests skipped.
  • 49 tests failed unexpectedly
  • 3 tests timed out unexpectedly
```
I added \_\_dir\_\_.ini file into newly created folder `tests/wpt/metadata/css/css-paint-api/`, enabled css-paint-api in `tests/wpt/include.ini` file:
```
diff --git a/tests/wpt/include.ini b/tests/wpt/include.ini
index 2b197be598..2e537c6c99 100644
--- a/tests/wpt/include.ini
+++ b/tests/wpt/include.ini
@@ -25,6 +25,8 @@ skip: true
     skip: false
   [css-images]
     skip: false
+  [css-paint-api]
+    skip: false
   [css-style-attr]
     skip: false
   [css-text]

```
And regenerated manifest:
```
$ ./mach update-manifest
Running tests in web-platform-tests

Ran 0 tests finished in 0.0 seconds.
  • 0 ran as expected. 0 tests skipped.
```
And still most of tests fail:
```
$ ./mach test-wpt tests/wpt/web-platform-tests/css/css-paint-api
...
Ran 56 tests finished in 98.0 seconds.
  • 4 ran as expected. 0 tests skipped.
  • 49 tests failed unexpectedly
  • 3 tests timed out unexpectedly
```
Any ideas?

**Comment by jdm** [comment]
Oh, I see the issue. The specification for CSS paint worklets was [updated](https://github.com/w3c/css-houdini-drafts/issues/410) after we forked the tests, but our implementation was not updated to account for it. Would you like to make that change, and update the forked tests to account for it? This would require moving the partial interface that includes paintWorklet from Window (in `components/script/dom/webidls/Window.webidl`) to CSS in (`components/script/dom/webidls/CSS.webidl`) and adding a static qualifier to it like the other attributes in that file. You'll also have to update the implementation to match; it will go in `components/script/dom/css.rs`, and you can move the `PaintWorklet` method in `components/script/dom/window.rs` into the impl block directly below the current one and invoke it from css.rs.

**Comment by yurket** [comment]
Sure! Gonna try at least =)

**Comment by yurket** [comment]
Ok, I've updated webidls, adjusted implementations:
```
$ git diff components/script/dom/window.rs
@@ -1027,17 +1027,17 @@ impl WindowMethods for Window {
         fetch::Fetch(&self.upcast(), input, init)
     }
 
-    // https://drafts.css-houdini.org/css-paint-api-1/#paint-worklet
-    fn PaintWorklet(&self) -> DomRoot<Worklet> {
-        self.paint_worklet.or_init(|| self.new_paint_worklet())
-    }
-
     fn TestRunner(&self) -> DomRoot<TestRunner> {
         self.test_runner.or_init(|| TestRunner::new(self.upcast()))
     }
 }
 
 impl Window {
+    // https://drafts.css-houdini.org/css-paint-api-1/#paint-worklet
+    pub fn paint_worklet(&self) -> DomRoot<Worklet> {
+        self.paint_worklet.or_init(|| self.new_paint_worklet())
+    }
+
     pub fn task_canceller(&self) -> TaskCanceller {
         TaskCanceller {
             cancelled: Some(self.ignore_further_async_events.borrow().clone()),

```
```
$ git diff components/script/dom/css.rs
@@ -6,8 +6,10 @@ use cssparser::{Parser, ParserInput, serialize_identifier};
 use dom::bindings::codegen::Bindings::WindowBinding::WindowBinding::WindowMethods;
 use dom::bindings::error::Fallible;
 use dom::bindings::reflector::Reflector;
+use dom::bindings::root::DomRoot;
 use dom::bindings::str::DOMString;
 use dom::window::Window;
+use dom::worklet::Worklet;
 use dom_struct::dom_struct;
 use style::context::QuirksMode;
 use style::parser::ParserContext;
@@ -63,4 +65,9 @@ impl CSS {
             false
         }
     }
+
+    /// <https://drafts.css-houdini.org/css-paint-api-1/#paint-worklet>
+    pub fn PaintWorklet(win: &Window) -> DomRoot<Worklet> {
+        win.paint_worklet()
+    }
 }
```
This gave me ~25 tests passing. Then I copied and adjusted .ini files for failing tests from `tests/wpt/mozilla/meta/mozilla/css-paint-api` into `tests/wpt/metadata/css/css-paint-api` and still get 3 tests failing:
```
 $ ./mach test-wpt tests/wpt/web-platform-tests/css/css-paint-api
Running 56 tests in web-platform-tests

  ▶ FAIL [expected PASS] /css/css-paint-api/geometry-with-float-size.https.html
  └   → /css/css-paint-api/geometry-with-float-size.https.html 47b36282bcdddba641fa5871cc9c7db9bf89b91b
/css/css-paint-api/geometry-with-float-size-ref.html c29beae9d20b245b02818a43923273de7a1064bc
Testing 47b36282bcdddba641fa5871cc9c7db9bf89b91b == c29beae9d20b245b02818a43923273de7a1064bc

  ▶ FAIL [expected PASS] /css/css-paint-api/hidpi/device-pixel-ratio.https.html
  └   → /css/css-paint-api/hidpi/device-pixel-ratio.https.html eeea905ccedb9e62e8660ac4c50ccf7b8fc56eb9
/css/css-paint-api/hidpi/device-pixel-ratio-ref.html 9073afa5205550a355cf5fb890919e72056aa78c
Testing eeea905ccedb9e62e8660ac4c50ccf7b8fc56eb9 == 9073afa5205550a355cf5fb890919e72056aa78c

  ▶ FAIL [expected PASS] /css/css-paint-api/parse-input-arguments-018.https.html
  └   → /css/css-paint-api/parse-input-arguments-018.https.html 4a6311c1e74b0370a563226521eb82210287fdb9
/css/css-paint-api/parse-input-arguments-018-ref.html 52dcfe9d35f3c3b02f5a307428650efbffbff92e
Testing 4a6311c1e74b0370a563226521eb82210287fdb9 == 52dcfe9d35f3c3b02f5a307428650efbffbff92e

Ran 56 tests finished in 81.0 seconds.
  • 53 ran as expected. 0 tests skipped.
  • 3 tests failed unexpectedly
```
Is it expected?

**Comment by jdm** [comment]
Those are probably new tests that were written since we forked, and I think they deal with features that we don't yet support.

**Comment by yurket** [comment]
ok, so I'll add .ini files with failing expectations for them and will prepare PR

**Comment by jdm** [comment]
Thanks for investigating!

**Comment by yurket** [comment]
Ok, I'm back on this PR.
Question: should I call `./mach test-wpt --manifest-update` after adding .ini files and changing `include.ini`? Looks like everything works without it.

**Comment by jdm** [comment]
Updating the manifest is only required when the actual test files are modified, so no.

**Comment by yurket** [comment]
Looks like *wpt* tests fully replace *mozilla*, except of 3 tests:
```
paint2d-zoom.html
geometry-border-image-005.html
geometry-background-image-003.html
```
But these 3 were [removed](https://github.com/w3c/web-platform-tests/commit/de7719144e1c7da2ca8d6a543bec428fcfd3c30f) from wpt repo. So I assume, I can remove the whole directory and meta files? 
Should I remove anything else except `tests/wpt/mozilla/tests/mozilla/css-paint-api` and `tests/wpt/mozilla/meta/mozilla/css-paint-api`? Or maybe adjust some configs?
And after removing real tests I need to run `./mach test-wpt --manifest-update`, correct?

**Comment by jdm** [comment]
Yes, I agree with your conclusions. You shouldn't need to remove any other files besides the ones you mention, and you will need to update the manifest.
