### ISSUE TITLE
Create a tool to show the build status of a PR

### ISSUE THREAD

**Issue by jdm** [servo/servo#19853]
Currently we use http://build.servo.org/grid and http://build.servo.org/console to see the build status of a particular revision across all platforms. Neither of these views are really ideal for that purpose. We should build a tool that allows users to provide a PR number, then looks in the buildbot history to find current and historical builds related to that PR. The output should be a webpage, so I would expect this tool to be written as a Flask server in Python or some equivalent in node.js, or even just entirely client-side using JavaScript and XMLHttpRequest.

To acquire the build data, we can use the buildbot [JSON API](http://build.servo.org/json/help).
1. Get the list of builders
2. For each builder, get the build data for each cached build
3. If the build data's comments includes the PR number, mark that build as important
4. For each important build, use the build's text of "successful" to determine if the build succeeded
5. For each builder, if there is a currentBuild then perform the same steps but mark any important builds as in-progress
6. Display the list of important builds and their statuses by grouping them according to the actual source revision the builds were based on, and according to the platform associated with each builder

**Comment by tigercosmos** [comment]
This is really helpful.

**Comment by jdm** [comment]
There's an initial version of this tool in https://github.com/servo/buildbotstatus/ courtesy of @ferjm. We'll file issues on improving it there.

**Comment by ferjm** [comment]
This is now live in https://servo.github.io/buildbotstatus
