### ISSUE TITLE
WOFF webfonts broken on Linux

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#19862]
See https://github.com/servo/servo/pull/19688#issuecomment-359834923 and the reftest analyzer image in https://github.com/servo/servo/pull/19688#issuecomment-360027050

All these tests use a WOFF webfont, which when run on Linux (both on the builders and on my desktop) end up showing tofu. Stuff works on OSX.

Currently not in town (only have a macbook) and I don't want to debug this over SSH, but may look into this later when I'm back.

cc @glennw @mbrubeck

**Comment by mrobinson** [comment]
This should be fixed after #31879.
