### ISSUE TITLE
DuckDuckGo divider not inline with text

### ISSUE THREAD

**Issue by atouchet** [servo/servo#19869]
URL: https://duckduckgo.com/?q=Servo&t=hw

Image of issue (Firefox top, Servo bottom):

![DuckDuckGo](https://i.imgur.com/dAx95gs.png)

The divider between "Videos" and "Meanings" isn't inline with the text in Servo. Tested in Windows 10 with Browser.html.

**Comment by sviter** [comment]
```
<!DOCTYPE html>
<style>
.zcm__sep--h:before {
 margin:0 7px;
 height:1em
}
.zcm__item,.zcm__sep--h {
 vertical-align:top;
 display:inline-block
}
.zcm__link {
 display:block;
 margin:0 7px;
 line-height:37px;
}
.zcm__sep--h {
 line-height:37px;
}
.zcm__sep--h:before {
 top:0.1em
}
.sep--before:before {
 border-left:1px solid #d0d0d0;
 display:inline-block;
 position:relative;
}
.sep--before:before {
 content:""
}
</style>
<ul class="zcm__menu zcm__dynamic has-zci" id="duckbar_new">
    <span id="duckbar_dynamic_sep" class="zcm__sep--h sep--before"></span>
    <li class="zcm__item"><a data-zci-link="meanings" class="zcm__link  js-zci-link  js-zci-link--meanings" href="#">Text</a></li>
</ul>
```
If I delete `vertical-align:top;` it's not affect FF but fix issue for Servo

**Comment by atouchet** [comment]
The divider no longer appears to be used on DuckDuckGo but I tried the manual testcase in Firefox and Servo and they appear the same to me so I guess this has been fixed.
