### ISSUE TITLE
DomRefCell::<T>::borrow_mut is not sound for all T types

### ISSUE THREAD

**Issue by nox** [servo/servo#19871]
`DomRefCell<T>` allows users to get a `&mut T` value out of it when borrowing the cell mutably. This should not be allowed for all `T` types, because it cannot be made invariably safe.

An example of unsafety is draining the vector stored inside a `DomRefCell<Vec<T>>`. Callers can keep hold of the draining iterator and run some code that triggers a GC in SpiderMonkey. But when the `Drain<T>` iterator is created, the backing vector's length is [truncated](https://doc.rust-lang.org/src/alloc/vec.rs.html#1115) to the start offset of the draining range, which means that when the vector gets traced, the items that will later be yielded by the iterator *won't* get accounted for.

Cc @jdm @asajeffrey, I want to try and just make `JSTraceable` for `DomRefCell<T>` panic if the cell is mutably borrowed.

**Comment by SimonSapin** [comment]
If a vector can get traced while `Drain` holds a `&mut` reference to it, we’re already violating language invariants.

**Comment by nox** [comment]
This was fixed by #19872.
