### ISSUE TITLE
Icons rotate incorrectly

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19879]
URL: http://hn.premii.com/#

The `bubble` icons don't rotate correctly in Servo.

![image](https://user-images.githubusercontent.com/6782666/35475010-0206e5b6-03d2-11e8-99c1-3971a9330c32.png)

Note: Servo is built with bc7dd644f6

Tested in `macOS 10.12.6`

**Comment by CYBAI** [comment]
Test case

```html
<style>
  .bubble-icon {
    display: inline-block;
    border-radius: 50%;
    padding: 1px 6px;
    min-width: 37px;
    line-height: 1.45;
    text-align: center;
    font-style: normal;
    font-size: .93rem;
    background-color: rgb(255,240,230);
    color: #ff6600;
  }

  .bubble-icon:after {
    width: 0;
    height: 0;
    position: absolute;
    margin-top: -4px;
    margin-left: 2px;
    content: '';
    display: block;
    border: 9px solid transparent;
    border-width: 6px 3px 6px 6px;
    transform: rotate(-76deg);
    border-top-color: rgb(255,240,230);
  }
</style>
<i class="bubble-icon">1</i>
```

![image](https://user-images.githubusercontent.com/6782666/35475071-dae7f4ce-03d2-11e8-80fe-3a9f8e62cc06.png)

**Comment by terracotaPie** [comment]
@highfive: assign me 

@jdm Your talk at U of T was too good - I am back

**Comment by terracotaPie** [comment]
@jdm Am I on the right track - should I dig in style/values/generics/transform.rs? Thanks in advance :)

**Comment by jdm** [comment]
Unfortunately, it appears to be more complex than simply how the transform is interpreted. Using the following testcase, it's easier to see what's going on:
```html
<style>
  .bubble-icon {
    display: inline-block;
    border-radius: 50%;
    padding: 1px 6px;
    min-width: 37px;
    line-height: 1.45;
    text-align: center;
    font-style: normal;
    font-size: .93rem;
    background-color: rgb(0,255,0);
    color: #ff6600;
  }

  .bubble-icon:after {
    width: 0;
    height: 0;
    position: absolute;
    margin-top: -4px;
    margin-left: 2px;
    content: '';
    display: block;
    border: 9px solid transparent;
    border-width: 6px 3px 6px 6px;
    border-top-color: rgb(255,0,0);
  }
</style>
<i class="bubble-icon">1</i>
```
Firefox:
<img width="60" alt="screen shot 2018-02-16 at 2 16 23 pm" src="https://user-images.githubusercontent.com/27658/36324902-fcc256e2-1323-11e8-9727-96128a170f82.png">
Servo:
<img width="64" alt="screen shot 2018-02-16 at 2 16 34 pm" src="https://user-images.githubusercontent.com/27658/36324922-065c7f84-1324-11e8-904c-d4315037674c.png">

**Comment by jdm** [comment]
This is a layout issue where the content for the :after pseudo-element isn't positioned in the place that it's expected.

**Comment by CYBAI** [comment]
@jdm Thanks for your summary!!!

**Comment by terracotaPie** [comment]
Sorry I got busy with midterms. Started working on it again

**Comment by CYBAI** [comment]
Remove `C-assigned` label due to lack of activity

**Comment by teymour-aldridge** [comment]
@highfive assign me

**Comment by mrobinson** [comment]
It turns out this is an issue for Layout 2020 as well.
