### ISSUE TITLE
Avoid `Window::GetComputedStyle` when checking for `display: none`

### ISSUE THREAD

**Issue by jonleighton** [servo/servo#19885]
This can be done after #19881 is merged. See @emilio's [comment](https://github.com/servo/servo/pull/19881#pullrequestreview-92041589):

> I'm pretty sure we can use this to simplify and make stuff faster in `canvasrenderingcontext2d.rs`, and `script_thread.rs`, which right now call directly `GetComputedStyle`.

Those two files both contain calls to `GetComputedStyle` to check for `display: none` on an element. We can refactor them to use `Node::style()` instead.

**Comment by emilio** [comment]
(Or node::has_css_layout_box, which is what they really want. They're both bogus)

**Comment by emilio** [comment]
Well, let me know if you want to take that before marking it as `E-easy` :).

**Comment by jonleighton** [comment]
I think leaving as `E-easy` is fine for now, could be a good first issue for someone :)

**Comment by emilio** [comment]
> I think leaving as E-easy is fine for now, could be a good first issue for someone :)

Sounds great!

**Comment by alexfjw** [comment]
@highfive assign me

**Comment by tigercosmos** [comment]
@alexfjw I reply your letter here. (More clear to show code)

`ComputedValue` is trying to implement `computed value` in CSS.  See https://developer.mozilla.org/zh-TW/docs/Web/CSS/computed_value
The detail reference is  https://doc.servo.org/style/properties/struct.ComputedValues.html

`GetComputedStyle`'s definition is 
https://github.com/servo/servo/blob/2a46067587d63aec176621ab3b6112ef5200a248/components/script/dom/window.rs#L826-L843

 P.S. When I encounter the new functions, I will search it for other examples like [this](https://github.com/servo/servo/search?l=Rust&q=GetComputedStyle&type=&utf8=%E2%9C%93)

If you still not know how to do, I will suggest you to ping @jonleighton or @emilio. I thought they are nice to help you. Don't be shy to ask (I ask stupid questions all the time :P)
