### ISSUE TITLE
Node::style should move to Element after #19881 lands 

### ISSUE THREAD

**Issue by emilio** [servo/servo#19886]
Right now all the callers do:

```rust
self.upcast::<Node>().style();
```

And I'm glad they do because the code panics if the node is not an element.

So we should just move `Node::style` to `Element` so it can't be misused. We should also add a documentation comment saying when it may be `None` (when the element is in a display: none subtree).

**Comment by csmoe** [comment]
@highfive assign me
I'll try to work on this.
