### ISSUE TITLE
MDN "Web Workers basic example" doesn't work

### ISSUE THREAD

**Issue by Max-E** [servo/servo#19890]
This page is supposed to demonstrate the web workers API: 
http://mdn.github.io/simple-web-worker/
on other browsers, the arithmetic happens as expected. On Servo, the product at the bottom doesn't update. Git hash tried: 1cb824d48e832b2e11b5e7341b188ad579b43111 OS: 64-bit Linux Mint 18. I used a release build.

**Comment by jdm** [comment]
This is because Servo doesn't support the "onchange" event for text inputs yet.

**Comment by jdm** [comment]
This is tracked in #9575.
