### ISSUE TITLE
Latest Servo nightly build fails to launch

### ISSUE THREAD

**Issue by atouchet** [servo/servo#19901]
Steps to reproduce:

1. Download Servo nightly build and try to run.
2. Windows security warning prompt appears as normal but Servo does not launch after clicking Run.

This is a new regression that first occurred in the [2018-01-30](http://servo-builds.s3.amazonaws.com/) nightly build. Tested in Windows 10 with Browser.html.

**Comment by jdm** [comment]
Based on the commits that were added to that build, I suspect the glutin upgrade is at all. This might be the same problem that @SimonSapin is experiencing.

**Comment by SimonSapin** [comment]
Yes, this sounds similar to https://github.com/servo/webrender/issues/2356.

**Comment by redmanmale** [comment]
Same on Win 7.

`Failed to create window.: OsError("CreateWindowEx function failed: The operation completed successfully. (os error 0)") (thread main, at libcore\result.rs:916)`
