### ISSUE TITLE
Use a macro to create null-terminated C strings

### ISSUE THREAD

**Issue by jdm** [servo/servo#19916]
When we write them by hand (eg. `b"some string\0"`), we invariably get them wrong in ways that are tricky to notice (https://github.com/servo/servo/pull/19915). We should use a macro like this instead:
```rust
macro_rules! c_str {
    ($str:expr) => {
        concat!($str, "\0").as_bytes()
    }
}
```
This would allow us to write code like `(c_str!("PEParseDeclarationDeclExpected"), Action::Skip)` instead of https://github.com/emilio/servo/blob/d82c54bd3033cc3277ebeb4854739bebe4e20f2f/ports/geckolib/error_reporter.rs#L237. We should be able to clean up all of the uses in that file.

No need to run any automated tests; if it builds with `./mach build-geckolib`, then it's good enough for a pull request.

**Comment by KiChjang** [comment]
Shouldn't the `to_geck_message` fn really return a [CStr](https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html) instead in order to at least have some type checking in place?

**Comment by KiChjang** [comment]
We can also use [from_bytes_with_nul](https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html#method.from_bytes_with_nul) for some stronger guarantees, but I don't think the overhead is worth it.

**Comment by jdm** [comment]
Returning a CStr does sound like an improvement. The macro could use CStr::from_bytes_with_nul_unchecked under the hood.

**Comment by upsuper** [comment]
Hmmm... I didn't notice this issue, and wrote a PR #19925 for fixing this...

**Comment by jdm** [comment]
@thiagopnts Given that the solution in #19925 is safer than what I propose here, we're going to go with that. Sorry for the duplication of effort!
