### ISSUE TITLE
style: Move content property out of Mako.

### ISSUE THREAD

**Issue by gootorov** [servo/servo#19936]
I'll be working on this one. Sub-issue of https://github.com/servo/servo/issues/19015.

**Comment by gootorov** [comment]
@emilio You should tick the `counters.mako.rs/counter-increment` property in https://github.com/servo/servo/issues/19015, I think it was implemented in https://github.com/servo/servo/pull/19529.

**Comment by emilio** [comment]
Nice catch, thanks!
