### ISSUE TITLE
Can't build servo_url without mozjs

### ISSUE THREAD

**Issue by anniryynanen** [servo/servo#19939]
I'm trying to use the `compositing` crate without having to include `mozjs`. My problem is that one of its dependencies, `servo_url`, doesn't compile unless `malloc_size_of` has the `servo` feature enabled. Enabling the feature creates a dependency on `mozjs`.

It seems a bit excessive for `servo_url` to depend on `mozjs`, so I'm hoping it's not intentional?

Here's the compilation error:

```
  --> [...]/.cargo/git/checkouts/servo-12bfca331f128de3/1662fd7/components/url/origin.rs:14:41
   |
14 | #[derive(Clone, Debug, Deserialize, Eq, MallocSizeOf, PartialEq, Serialize)]
   |                                         ^^^^^^^^^^^^ the trait `malloc_size_of::MallocSizeOf` is not implemented for `url::Host`
```

The root cause is that `malloc_size_of` doesn't implement traits for URLs without the `servo` feature.

**Comment by emilio** [comment]
It'd be fine I think to split that feature into multiple ones.

**Comment by anniryynanen** [comment]
I could probably make the changes myself. I'm thinking I'd add two new features to `malloc_size_of`: `url_traits` and `webrender_traits`. Does that sound ok?

**Comment by emilio** [comment]
That sounds fine, thank you!
