### ISSUE TITLE
Move text-emphasis-style outside of mako

### ISSUE THREAD

**Issue by GloverDonovan** [servo/servo#19940]
This is a sub-issue of #19015.

I'm fairly new to Rust (but not the web, nor formal languages), so feel free to tell me anything I may need to know. In the meantime, I'll be going through the [Rust book](https://doc.rust-lang.org/book/second-edition/).

**Comment by emilio** [comment]
Hi @GloverDonovan, have you made any progress here? Anything I can help with? Thanks!

**Comment by GloverDonovan** [comment]
Hi @emilio,

Don't mind me. I've been learning a lot about how Rust works (and the web specifications). I'll eventually figure out how to fix this issue, but right now I'm still learning. I'll ask on IRC if I need any help.

**Comment by NeverHappened** [comment]
Hi @emilio 
Made a pull request refactoring this.
Can you please review it?

https://github.com/servo/servo/pull/20252

**Comment by GloverDonovan** [comment]
Hi @NeverHappened,

I appreciate the effort, but it would've been nice if you asked before taking this issue. Admittedly, your pull requests looks like a lot of work, so I'm glad you took the time to work on this!

Learning Rust has been an enjoyable experience so far. I may try another Servo issue in the future.

**Comment by NeverHappened** [comment]
Hi. Sorry for that!

I was not sure that I can do this thing, that's why I didn't write about it. :(
Also because I saw nobody assigned for this

**Comment by GloverDonovan** [comment]
No problem, someone had to do it.

Cheers
