### ISSUE TITLE
selectionStart and selectionEnd default to the end of the content

### ISSUE THREAD

**Issue by jdm** [servo/servo#19958]
```html
<textarea>g
</textarea>
<script>
var t = document.querySelector('textarea');
console.log(t.selectionStart);
console.log(t.selectionEnd);
</script>
```
This shows 2, 2 in Servo, but 0, 0 in Firefox.

**Comment by jdm** [comment]
Given that the specification says `The initial state must consist of a text entry cursor at the beginning of the control.`, and step 2 of https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-textarea/input-selectionstart says `If there is no selection, return the offset (in logical order) to the character that immediately follows the text entry cursor.`, this looks like a bug in Servo's implementation.

**Comment by nupurbaghel** [comment]
I would like to work on this issue.

**Comment by KiChjang** [comment]
cc @jonleighton

**Comment by paavininanda** [comment]
@highfive assign me
