### ISSUE TITLE
Test performance on web archives of Alexa top sites

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#19959]
One of the performance dashboards at https://servo.org/dashboards/ measures Servo's performance on archives of web content. It would be good to get as much coverage as we can, for which we need help recording new web archives!

If you'd like to help out with this effort, head over to https://github.com/servo/servo-warc-tests/issues/8 and pick a web site to record. There are pointers to instructions on how to play and record new web archives, and a check list of sites that would be helpful to record.

**Comment by asajeffrey** [comment]
Pay no attention to the bot behind the curtain :) if you'd like to work on this, head over to https://github.com/servo/servo-warc-tests/issues/8

**Comment by asajeffrey** [comment]
The top ten are now done (https://github.com/servo/servo-warc-tests/issues/8) but there are still sites in the top 25 up for grabs! https://github.com/servo/servo-warc-tests/issues/37

**Comment by iurifq** [comment]
Should this issue be closed since servo/servo-warc-tests#8 has been closed?

**Comment by jdm** [comment]
See the previous comment.

**Comment by pawan92** [comment]
hey i can help out with this!

**Comment by jdm** [comment]
servo/servo-warc-tests#37 is fixed.
