### ISSUE TITLE
Move `text-emphasis-position` outside of mako

### ISSUE THREAD

**Issue by LiHaoTan** [servo/servo#19961]
Part of #19015

**Comment by emilio** [comment]
Hi @LiHaoTan, have you made any progress here? Anything I can help with? Thanks!

**Comment by LiHaoTan** [comment]
I'm sorry I have been busy for a while.

I will work on this ASAP or if I'm holding any progress I suppose anyone can take this right?

**Comment by emilio** [comment]
Yes, it's fine, let's keep it assigned to you as long as you plan to work on this, this is not particularly urgent. Thanks for the fast reply, and let me know if I can help!
