### ISSUE TITLE
Use specific debug assertion

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#19962]
As discussed in [the comment](https://github.com/servo/servo/pull/19953#discussion_r165918713) with @emilio in #19953 , we can open an issue and label it as `E-easy` to change all possible `debug_assertion` to its corresponding specific debug assertion.

Here's the current counting in `components` folder:

```sh
→ rg debug_assert! | rg == | wc -l
      67
```

```sh
→ rg debug_assert! | rg != | wc -l
      21
```

For example, we can change equal to

```diff
- debug_assert!(a == b);
+ debug_assert_eq!(a, b);
```

and not equal to

```diff
- debug_assert!(a != b);
+ debug_assert_ne!(a, b);
```

I think it will be similar to #19868

**Comment by SimonSapin** [comment]
I’m not sure we should do this. The `_eq` and `_ne` macros serialize the values with `std::fmt::Debug`, which we’ve deliberately removed in https://github.com/servo/servo/pull/19779 to reduced code size.

**Comment by emilio** [comment]
> I’m not sure we should do this. The _eq and _ne macros serialize the values with std::fmt::Debug, which we’ve deliberately removed in #19779 to reduced code size.

These are debug assertions though, they don't appear on the final binary.

**Comment by emilio** [comment]
Not all of them can be changed, for example: `debug_assert!(a == b || b == c)` cannot be simplified. But for those who can I'm fine with doing that.

**Comment by janczer** [comment]
@highfive: assign me
