### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by ProtoGeekAlpha** [servo/servo#19977]
called `Option::unwrap()` on a `None` value
### URL:
https://research.mozilla.org/2014/04/17/another-big-milestone-for-servo-acid2/
### Servo Version:
Servo 0.0.1-c784bc6
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: Message sent to closed pipeline (1,8).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: Message sent to closed pipeline (1,8).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: Message sent to closed pipeline (1,8).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: stop_parsing not implemented, full speed ahe
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment]
I haven't been able to reproduce a problem on that page yet. Were you doing anything in particular?

**Comment by ProtoGeekAlpha** [comment]
M. JDM,

¡Namaste 🙏🏽! :-) Stacie & j'espère que vous avez un amour, béni, heureux, en bonne santé, et un "Live Long et Prosper" -Votre-Selves Day ... ¡Happy 20-GrEighteen!

Merci de votre attention à cette question.

"Cette danse n'est pas pour tout le monde."

Je danse seulement avec l'interface utilisateur graphique ... j'ai dansé depuis 1973 avec des descendants de deuxième génération d'ordinateurs de m. Joseph-Marie Jacquard. Je suis seulement ici pour l'expérience pure de l'utilisateur final du gui de Servo.

En ce moment, je ne me souviens pas de ce que je faisais, pourtant, je crois que j'avais cliqué sur la flèche de retour.

je reste vraiment,
joseph
ProtoGeekAlpha
~ € ;-)

**Comment by CYBAI** [comment]
Can't reproduce te panic with latest master (4ec7dedce1) on macOS 10.13.6 either

**Comment by dralley** [comment]
If multiple people can't reproduce - close?
