### ISSUE TITLE
Support throttling task queues

### ISSUE THREAD

**Issue by jdm** [servo/servo#19997]
All of our task queues are currently based on channels, so if there's a message ready to be received it is processed immediately. It would be useful to build an extra layer of abstraction around this so support more complex interactions, like throttling the rate at which tasks in a queue are processed to reduce the priority of certain queues.

**Comment by ferjm** [comment]
The performance timeline task queue could use this https://github.com/servo/servo/blob/master/components/script/task_source/performance_timeline.rs#L5

**Comment by gterzian** [comment]
I would be very interested in this...

Would the throttling happen on a 'per tasksource' basis, or would it be more something with a logic across task sources(like prioritize one task source over the other in certain cases)?

Do you have other examples of 'more complex interactions' that could be supported?

**Comment by gterzian** [comment]
*Each task is defined as coming from a specific task source. All the tasks from one particular task source and destined to a particular event loop must always be added to the same task queue, but tasks from different task sources may be placed in different task queues.* https://html.spec.whatwg.org/multipage/#task-queue

I think we actually have only one task queue for a given script-thread/event-loop, which is a single `Receiver`, where the various task sources are basically clones of the corresponding `Sender`(and the `Sender` is also used by other script related threads to communicate back to the 'main' script thread, I think, see the [`MainThreadScriptChan`](https://github.com/servo/servo/blob/21079ad690ec2003dbb4fcabbfda32705a90e320/components/script/script_thread.rs#L426). 

A first step might be break-up the various task sources, as well as the `MainThreadScriptChan`, into their own channel with their own `port` on which the script thread can receive, similar to the current single [script_port](https://github.com/servo/servo/blob/21079ad690ec2003dbb4fcabbfda32705a90e320/components/script/script_thread.rs#L945).

Once we have that, I guess 'throttling' a task source, or other such decision, could be made inside the main [handle_msgs](https://github.com/servo/servo/blob/21079ad690ec2003dbb4fcabbfda32705a90e320/components/script/script_thread.rs#L919) function of the script thread. 

I guess we could call this a `TaskQueue`(and it could be used for HTML task sources, and also double as a queue for our own custom `MainThreadScriptChan`), with internally the sender/receiver as well as perhaps extra data that could help the script-thread make decision on things like throttling?

**Comment by gterzian** [comment]
Also, having separate queues for task sources might enable us to get rid of the `DomRefCell<HashMap<TaskSourceName, Arc<AtomicBool>>>` "task canceller" concept, https://github.com/servo/servo/blob/2fc0633f299cf4b44eeb6d0946b034e43bb591ff/components/script/dom/window.rs#L261

**Comment by gterzian** [comment]
Thanks for the input.

I think I'll start with the "annotation/vector" approach you describe, because it might require somewhat less code change. Also, it's not dependent on a `len` method of channels, so I won't be blocked by #9881
