### ISSUE TITLE
"Broken" test content-height-005.html

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#20008]
The test /css/CSS2/visudet/content-height-005.html is weird. It is a "mismatch" test and the reference is /css/CSS2/visudet/reference/content-height-005-ref.html which outputs some CSS source due to a missing tag. The text description is `Test passes if there are <strong>more than 2</strong> lines below.` but no lines are displayed in neither the test or the reference.

I believe this test just passes by accident and is broken. What should be done about this test?

(cc @frivoal You are mentioned as the author in the test. Maybe you can have a look and update the test so it works as intended?)

Test:
![content-height](https://user-images.githubusercontent.com/2781017/36047155-90b3b5ba-0ddb-11e8-9f55-2704ac5ae2bc.png)
Reference:
![content-height-ref](https://user-images.githubusercontent.com/2781017/36047275-e0e0d9b4-0ddb-11e8-8f06-c1abcafae6d1.png)

**Comment by jdm** [comment]
This is clearly just a typo in the test, based on https://github.com/w3c/web-platform-tests/commit/5021aba0034c64b1d1fd822dc377c4c67a4e395c.

**Comment by jdm** [comment]
I've opened https://github.com/w3c/web-platform-tests/pull/9468 upstream. Thanks for pointing this out! Now that we have regular syncing with upstream happening, it's not a big deal to make changes upstream that aren't directly related to Servo changes.

**Comment by frivoal** [comment]
indeed it was a typo. Thanks for finding it and submitting the patch. PR approved and merged.
