### ISSUE TITLE
Update servo and dependent crates to log 0.4.x 

### ISSUE THREAD

**Issue by glennw** [servo/servo#20023]
WebRender has switched to the latest log crate version (https://crates.io/crates/log), but this causes test-tidy issues in Servo, which has a large number of dependencies targeting 0.3.x.

The test-tidy script reports the following crates using the old log version:

```
Checking files for tidiness...
./Cargo.lock:1: duplicate versions for package `log`
	The following packages depend on version 0.3.8 from 'crates.io':
		bindgen
		blurmac
		env_logger
		gaol
		gl_generator
		html5ever
		hyper
		influent
		mime
		mio
		mozjs
		offscreen_gl_context
		plane-split
		rust-webvr
		webdriver
		ws
		xcb
		xml5ever
	The following packages depend on version 0.4.1 from 'crates.io':
		canvas
		compositing
		constellation
		debugger
		devtools
		geckoservo
		gfx
		layout
		layout_thread
		libservo
		metrics
		net
		net_traits
		profile
		profile_traits
		script
		script_layout_interface
		selectors
		servo
		servo_config
		servo_rand
		servo_remutex
		style
		stylo_tests
		webdriver_server
		webrender
		webvr
  Progress: 100% (27/27)
```

We should start the process of updating these dependencies to use the latest log crate.

In the interim, to enable a WR update, we can either:
* Downgrade log in WR back to 0.3 for now.
* Allow multiple versions of the log crate to exist via ```test-tidy```

**Comment by glennw** [comment]
@jdm or others - any comments on preferred interim workaround?

**Comment by jdm** [comment]
`hyper` is the crate that's likely to be the longest pole in that list. I don't mind updating as many as possible and adding an exception for the rest.

**Comment by Eijebong** [comment]
Yeah, hyper is the blocking one (again), I'm pretty sure updating every other one is going to be easy as there were no huge breaking changes between 0.3 and 0.4.
In the meantime, if we don't mind having 2 versions of log, log 0.3.9 is just a shim over 0.4 so it should just work.

**Comment by Eijebong** [comment]
- [ ] bindgen             
- [ ] blurmac             
- [ ] env_logger          
- [ ] gaol                
- [ ] gl_generator        
- [ ] html5ever           
- [ ] hyper               
- [ ] influent            
- [ ] mime                
- [ ] mio                 
- [ ] mozjs               
- [ ] offscreen_gl_context
- [ ] plane-split         
- [ ] rust-webvr          
- [ ] webdriver           
- [ ] ws                  
- [ ] xcb                 
- [ ] xml5ever

**Comment by atouchet** [comment]
The last two crates that need to be updated are gaol and xml5ever. xml5ever 0.12.1 which includes the log 0.4 update hasn't been published to crates.io and gaol appears to be having [issues with updates](https://github.com/servo/gaol/issues/44).

**Comment by atouchet** [comment]
This was done in #22388.
