### ISSUE TITLE
Layers overhaul

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#2003]
Layers need to be overhauled to not have a distinction between `CompositorLayer` and `ContainerLayer`.

**Comment by frewsxcv** [comment]
> fixed by 0c2538d?

FWIW, at the time of writing, there are still a couple FIXMEs with this issue number in-tree:

```
> git grep "#2003"
components/layout/block.rs:            // FIXME(#2003, pcwalton): The max is taken here so that you can scroll the page, but
components/script/script_task.rs:        // FIXME(#2003, pcwalton): This is pretty bogus when multiple layers are involved.
```

**Comment by mrobinson** [comment]
I think the block.rs comment might be invalid now, because we have a different scrolling model in the compositor now. The comment in script_task.rs looks valid, but I don't think it's necessarily related to this bug any longer.

**Comment by glennw** [comment]
No longer relevant.
