### ISSUE TITLE
WebP support request

### ISSUE THREAD

**Issue by XVilka** [servo/servo#20045]
Unlike the famous WebM hack, when videos are used as animated images, WebP is the only format supporting both animation and transparency, to be a best replacement for GIF.

See https://bugzilla.mozilla.org/show_bug.cgi?id=600919 and https://bugzilla.mozilla.org/show_bug.cgi?id=1294490 for the reference

**Comment by XVilka** [comment]
I should note that's supported everywhere now: https://caniuse.com/#feat=webp

**Comment by nonetrix** [comment]
WebP would be great also svg, then my site would be comparable to Firefox in terms of usability
