### ISSUE TITLE
Use more newtype structs!

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#2005]
Several things should be newtype structs that aren't.

**Comment by zslayton** [comment]
[This pull request](https://github.com/servo/servo/pull/2489/commits) was merged a couple of months ago and seems to address `RenderChan`. Are there others I could take a look at as a first bug?

**Comment by jdm** [comment]
I'm not aware of anything in particular. We'll file new issues for anything new we come across; this one isn't particularly useful.
