### ISSUE TITLE
Pinch to zoom support

### ISSUE THREAD

**Issue by fabricedesre** [servo/servo#20109]
When an embedder sends a sequence of touch events such as:
TouchEventType::Down, one or more TouchEventType::Move, TouchEventType::Up these are correctly used to pan the page and/or synthetized a click.

However when there are multiple TouchId tracked, they are not taken into account to provide a pinch to zoom functionality.

**Comment by paulrouget** [comment]
Isn't that the job of the embedder to track the TouchId and do the zooming?

**Comment by fabricedesre** [comment]
It's hard to let the embedder do that because the behavior can depend on whether preventDefault() was called on the touchstart event. But actually there seems to be support in `components/compositing/touch.rs` and `components/compositing/compositor.rs`, I will dig deeper to see what that was triggering in my tests.

**Comment by paulrouget** [comment]
It should work like key events. Embedder send touch events to Servo, if Servo send them back, the embedder call the zoom functions.

**Comment by jdm** [comment]
Fixed by #20749.
