### ISSUE TITLE
Kinetic scrolling support

### ISSUE THREAD

**Issue by fabricedesre** [servo/servo#20110]
When an embedder sends a sequence of touch events such as:
TouchEventType::Down, one or more TouchEventType::Move, TouchEventType::Up these are correctly used to pan the page but the scrolling is not done with a kinetic accumulator.

**Comment by paulrouget** [comment]
Isn't that the job of the OS? For example https://developer.android.com/reference/android/widget/OverScroller.html

**Comment by fabricedesre** [comment]
Right now, Servo handles non-kinetic panning based on touch events if no event handler calls preventDefault() on touchstart. I think that if we want the embedder/OS to manage kinetic scrolling, we would need to bubble up this information back to the embedder to not have it send extra move/scroll events.

On the other hand, the compositor has all the needed information to do it by itself. I agree though that this may make it harder to be consistent with the "native" kinetic scrolling.

**Comment by paulrouget** [comment]
> we would need to bubble up this information back to the embedder to not have it send extra move/scroll events.

Yes.

> On the other hand, the compositor has all the needed information to do it by itself.

We have some bouncing/overscrolling code, but it's very gimmicky.

> I agree though that this may make it harder to be consistent with the "native" kinetic scrolling.

Yes. For example, on Android, out of the box, there is not fling support. Whereas, on OSX, "momentum" scroll events are sent no matter what. If we implement kinetic scrolling support within servo, we don't want to cancel momentum events in OSX. We'd rather use the OverScroller mechanism provided by Android, and momentum events of OSX.

**Comment by fabricedesre** [comment]
We discussed further on IRC and agreed that this should rather be handled by the OS and/or the embedder.
