### ISSUE TITLE
Servo's transitions code stopped making sense after #15900.

### ISSUE THREAD

**Issue by emilio** [servo/servo#20116]
In particular, what used to update the _new_ style (as expected, since that's what you're animating), started updating the old style:

```rust
       if let Some(ref mut old) = *old_values {
           self.update_animations_for_cascade(shared_context, old,
                                              possibly_expired_animations);
       }
```

Which doesn't really make sense.

**Comment by atouchet** [comment]
d6092fae27a55345ac9fa82f4d2195130ec01318 was reverted in #21971.
