### ISSUE TITLE
Servo should only support HTTPS connections, zero without "S"

### ISSUE THREAD

**Issue by redox-questions** [servo/servo#20120]
Hello, 

first, this looks like a great future project, next-gen webbrowser, wow. 

Second, I think it should only support HTTPS connections and not plain HTTP.

If it points to the future. 

only problem: OCSP uses plain HTTP: https://moxie.org/papers/ocsp-attack.pdf

**Comment by Darkspirit** [comment]
[Revocation is broken](https://blog.cloudflare.com/high-reliability-ocsp-stapling/). Firefox for Android only fetches OCSP for EV certs (if there was no stapled OCSP response).
The CAB Forum should enforce OCSP Must-Staple for EV certs.
Servo could omit any OCSP/CRL fetching then. That would be cool. :)

**Comment by jdm** [comment]
I don't think cutting off access to non-HTTPS is feasible yet, given the huge volume of unsecured legacy web content.
