### ISSUE TITLE
Need help with Euclid update

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#20130]
I need to move from Euclid 0.16 to Euclid 0.17.

But then I get this error:

```
the trait `serde::Deserialize<'_>` is not implemented for `euclid::TypedSize2D<u32, XXX>
```

Where XXX is CSSPixel, DevicePixel and DeviceIndependentPixel.

Adding a derive to these 3 emums doesn't help.

What the right approach here?

**Comment by SimonSapin** [comment]
Euclid made serde an optional dependency. In the `Cargo.toml` of the crate that has this error, replace `euclid = "0.17"` with `euclid = {version = "0.17", features = ["serde"]}`

**Comment by paulrouget** [comment]
Thank you!

**Comment by Eijebong** [comment]
@paulrouget Are you doing the whole euclid bump in servo ? (I'd like to avoid duplicating work :p)

**Comment by paulrouget** [comment]
@Eijebong just started, as I need https://github.com/servo/euclid/pull/274 - but if you already have a PR, I'd rather wait.

**Comment by Eijebong** [comment]
I don't have a PR but we need to update it in servo and every dependency at once. If you don't do it I'll probably do it tonight.

**Comment by paulrouget** [comment]
@Eijebong I'll do it. Looks like a rabbit hole though…

**Comment by Eijebong** [comment]
It is :D Have fun
