### ISSUE TITLE
Properly implement step 3 of the inner text collection steps algorithm

### ISSUE THREAD

**Issue by ferjm** [servo/servo#20159]
Spec: https://html.spec.whatwg.org/multipage/dom.html#inner-text-collection-steps

> If node is not being rendered, then return items. For the purpose of this step, the following elements must act as described if the computed value of the 'display' property is not 'none':
    - select elements have an associated non-replaced inline CSS box whose child boxes include only those of optgroup and option element child nodes;
    - optgroup elements have an associated non-replaced block-level CSS box whose child boxes include only those of option element child nodes; and
    - option element have an associated non-replaced block-level CSS box whose child boxes are as normal for non-replaced block-level CSS boxes.

The code is currently ignoring the select/optgroup/option exceptions.

This makes a test like `<div>a<select><option></select>bc` give  `a` instead of `a\nbc` as it should.

**Comment by shanehandley** [comment]
This can be closed 👍 it refers to the old layout, and this was implement in the new layout code recently: https://github.com/servo/servo/pull/33312

**Comment by jdm** [comment]
Fixed by the recent innerText work
