### ISSUE TITLE
Colspans broken when mixed with rowspans and placed at the end of a row

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#20164]
```html
<table border>
    <tr><td rowspan=2>a</td><td>b</td><td colspan=2 >cd</td>  </tr>
    <tr>                    <td>b</td><td>c</td><td>d</td></tr>

</table>
```

gives 

<img width="100" alt="image" src="https://user-images.githubusercontent.com/1617736/36876753-4d167b68-1d6b-11e8-8b18-4ff0efd83892.png">

and

```html
<table border>
    <tr><td>a</td><td>b</td><td>c</td><td>d</td></tr>
    <tr><td rowspan=2>a</td><td>b</td><td colspan=2 rowspan=2>cd</td>  </tr>
    <tr>                    <td>b</td></tr>
    <tr><td>a</td><td>b</td><td>c</td><td>d</td></tr>
</table>
```

gives

<img width="92" alt="image" src="https://user-images.githubusercontent.com/1617736/36876761-63fef418-1d6b-11e8-8c8d-9f6eb8931042.png">

In both cases, the colspanning cell should span the widths of the cells below it, and the table should encompass all of it.

I can only seem to trigger this when the colspan is at the end of the row, and there needs to be a rowspan involved as well. Not sure what's going on here; I don't yet understand the colspan code.

I don't think this was affected by the rowspan changes; this is completely an inline-size thing
cc @mbrubeck

**Comment by Manishearth** [comment]
Replacing [this fixme](https://github.com/servo/servo/blob/master/components/layout/table.rs#L131-L132) with the code in the else branch fixes the first example, but not the second one (nor does doing the same for the other fixme).

Looks like we need to implement that recursive algorithm. Seems to be the "intermediate min-content width for span N (N > 1)" one in https://dbaron.org/css/intrinsic/ ?

**Comment by mrobinson** [comment]
This is working now in modern layout.
