### ISSUE TITLE
Navigation using nightly build

### ISSUE THREAD

**Issue by atouchet** [servo/servo#20165]
This is more of a question than an issue report but how are you supposed to load new pages using the latest nightly builds? It loads servo.org by default but I don't see any way to input a new address within Servo. I can set shell.homepage in prefs.json to a new value but that's not particularly convenient. Is there a better way to do this?

**Comment by jdm** [comment]
As of right now there is no better way to navigate in nightly builds. https://groups.google.com/d/msg/mozilla.dev.servo/U5zhsBLXovM/HbRL69zZBAAJ describes the plans for making nightlies usable again, but it may have been premature to remove the browser.html interface before the replacement was ready.

**Comment by paulrouget** [comment]
@atouchet another way, if you run servo from the command line, is to pass the url as an argument:

```
servo http://foobar.com
```

But that's not a lot better. I'm working on a fix to add support for a keybinding that would prompt the user for a new url.

**Comment by atouchet** [comment]
Alright, this is fine until URL navigation is added.
