### ISSUE TITLE
Ignore descendant nodes of replace elements during inner text collection steps

### ISSUE THREAD

**Issue by ferjm** [servo/servo#20161]
The spec says:

> Note that descendant nodes of most replaced elements (e.g., textarea, input, and video — but not button) are not rendered by CSS, strictly speaking, and therefore have no CSS boxes for the purposes of this algorithm.

This makes tests like `<audio> contents ignored ("<div><audio>abc")` or `<video> contents ignored ("<div><video>abc")` fail.

**Comment by shanehandley** [comment]
I think this one can be closed as well 👍 it's referencing a step in the `innerText` spec but we pass those WPT's with our newer implementation: https://wpt.fyi/results/html/dom/elements/the-innertext-and-outertext-properties/getter.html?label=master&label=experimental&product=servo&aligned

<img width="1018" alt="Screen Shot 2024-10-12 at 8 49 59 pm" src="https://github.com/user-attachments/assets/9e5bd01c-c6d9-440c-a34d-1d409013ae80">
