### ISSUE TITLE
WebIDL bindings are not being re-generated after switching branches

### ISSUE THREAD

**Issue by mkollaro** [servo/servo#20169]
I added an item to `components/script/dom/webidls/` and implemented it. Now when I switch back to the master branch, it complains that the implementation of this new item is missing and fails the build.

To reproduce, 
1. Grab https://github.com/servo/servo/pull/20144/commits
2. `./mach build` should be successful
3. `git checkout master`
4. `./mach build` will fail now, because `GetTexParameter` is not implemented on master, only on the other branch

```
error[E0046]: not all trait items implemented, missing: `GetTexParameter`
    --> components/script/dom/webgl2renderingcontext.rs:80:1
     |
80   | impl WebGL2RenderingContextMethods for WebGL2RenderingContext {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `GetTexParameter` in implementation
     |
    ::: /home/mkollaro/data/dev/servo/target/debug/build/script-842b2b116fc9e009/out/Bindings/WebGL2RenderingContextBinding.rs
     |
9952 |     unsafe fn GetTexParameter(&self, cx: *mut JSContext, target: u32, pname: u32) -> JSVal;
     |     --------------------------------------------------------------------------------------- `GetTexParameter` from trait
error: aborting due to previous error
error: Could not compile `script`.
```

**Comment by jdm** [comment]
The problem either lies in the script crate's [build script](https://github.com/servo/servo/blob/master/components/script/build.rs) (does it run cmake when this happens?) or in [cmake's dependencies](https://github.com/servo/servo/blob/master/components/script/CMakeLists.txt#L109).

**Comment by mkollaro** [comment]
I found that running `touch components/script/dom/webidls/WebGL2RenderingContext.webidl` fixes it. 

The problem is, I haven't modified that specific file, I only changed `WebGLRenderingContext.webidl`, the bindings for WebGL1. The WebGL2 is an extension of WebGL1, so it's not necessary to update the WebGL2 idl file in this case. But the build system doesn't recognize that it needs to update the WebGL2 bindings when WebGL1 got changed.

**Comment by jdm** [comment]
Oh, the build system doesn't understand the relationship between webIDL files. That makes sense, and is a bit of an edge case unfortunately. The solution probably means that touching any webIDL file should cause all of them to be rebuilt, which means adjusting the cmake dependencies.
