### ISSUE TITLE
Make KeyframesPercentage::parse faster.

### ISSUE THREAD

**Issue by emilio** [servo/servo#20179]
Right now it does:

https://github.com/servo/servo/blob/0eb8b1f4c0736ec25dc391d119c03d1b49644d81/components/style/stylesheets/keyframes_rule.rs#L128-L144

That's more inefficient that what it needs to be, since it really only needs to get the next token once using `next()`, and then match on `Token::Ident` and `Token::Percentage`.

No new tests need to be added for this refactoring.

**Comment by Beta-Alf** [comment]
I would like to try my hand at this.

**Comment by emilio** [comment]
Thanks! Let me know if there's any question :)

**Comment by Beta-Alf** [comment]
So I think got pretty far : https://gist.github.com/Beta-Alf/5b19d25704c930082d947b3f7c4017c0
However I seem to be unable to compare the actual identifiers to my string literals and I don't seem to be able to figure out a way to do it (that doesn't involve creating another CowRcString which would presumably be wasteful and eliminate all possible speed gains).

**Comment by emilio** [comment]
Yeah, that looks close to what I was thinking about, awesome!

A few nits:

 * The string comparison should be ascii-case-insensitive. You can use either `match_ignore_ascii_case!` or `str::eq_ignore_ascii_case`. Both should be pretty fast in this case.
 * You can use `CowRcString::as_ref` to get a `&str`.
 * You can use `match *input.next()?` to make the code a bit tidier, and return a more meaningful error on EOF.
 * For bonus points (though not required), you can return a `unexpected_token_error` in the wildcard error branch :)

Thanks for looking into this!

**Comment by Beta-Alf** [comment]
Okay, so I fixed all your nits, although I had to jump through some hoops for the borrow checker, so maybe I introduced a new nit? Either way I already learned a lot, thank you!
