### ISSUE TITLE
default_config_dir should not return an Option

### ISSUE THREAD

**Issue by jdm** [servo/servo#20174]
Every implementation returns Some, and the caller calls unwrap(), so I don't see any reason it should return an Option value.

Code: `components/config/basedir.rs`

No need to run tests; if `./mach run tests/html/about-blank.html` works for you after compiling, that's good enough for a PR.

**Comment by andreicristianpetcu** [comment]
@highfive: assign me

**Comment by petre2dor** [comment]
@jdm suggested over IRC that the same thing should be done for `default_data_dir` and `default_cache_dir`. working on that now.
