### ISSUE TITLE
Extract IPC usage from WebRender into Servo

### ISSUE THREAD

**Issue by jdm** [servo/servo#20172]
The goal of this work is to remove all references to the [ipc-channel](https://github.com/servo/ipc-channel/) crate from [WebRender](https://github.com/servo/webrender/) and move all IPC usage into the calling code in Servo instead. This will require a few parts:
* replace all uses of IPC channels in WebRender with [std::mpsc channels](https://doc.servo.org/std/sync/mpsc/fn.channel.html) instead
* [use](https://doc.rust-lang.org/cargo/reference/source-replacement.html) the modified version of WebRender in Servo
* create an IPC channel that is stored in Constellation which is used for cross-process communication with WebRender
* create a new type like webrender_api::RenderApiSender that uses an IPC channel to pass the messages to the parent
* make the IPC channel route the messages to the in-process webrender_api::RenderApiSender

Code: `components/layout_thread/lib.rs`, `components/layout_traits/lib.rs`, `components/constellation/constellation.rs`, `components/constellation/pipeline.rs`

To consider the task complete, it should be enough to demonstrate that `./mach run tests/html/about-blank.html` still renders a page after the changes are made.

**Comment by mkmodrzew** [comment]
Can I try to do that?

**Comment by jdm** [comment]
@mkmodrzew Please do! Ask questions about anything that's unclear!

**Comment by asajeffrey** [comment]
One thing that might be worth thinking about is using a dedicated thread for this rather than the constellation, which is already pretty complicated!

**Comment by mkmodrzew** [comment]
I spent some time browsing project and I've got first question:
- There is actually std::mpsc channels usage implemented in WebRender. I commented out every usage of ipc-channel there and built it without any problem, so there is no dependency with that code. Is that enough to assume that first dot is already finished?

**Comment by asajeffrey** [comment]
@mkmodrzew the place where WR does its mpsc vs ipc channel choice is in https://github.com/servo/webrender/blob/master/webrender_api/src/channel.rs#L84-L88

This uses a cfg to switch between using ipc channels and using mpsc channels. Most of the changes would be at the servo side, starting with importing WR without the `ipc` feature.

**Comment by mkmodrzew** [comment]
@asajeffrey So, as far as I understand, if before I do any change in Servo and after preventing ipc-channel in WebRender (locally, of course), any test with running browser should fail? Because I think I already did it (to try myself with this project), but tests still pass

**Comment by asajeffrey** [comment]
The change to servo is in the various Cargo.toml files, with lines like:
```
webrender_api = {git = "https://github.com/servo/webrender", features = ["ipc"]}

```
You need to remove the `features = ["ipc"]`.

**Comment by mkmodrzew** [comment]
Okay, I think I still don't get everything:
- I replaced every `webrender_api = {git = "https://github.com/servo/webrender", features = ["ipc"]}` with `webrender_api = {git = "https://github.com/servo/webrender"}`. There's no question, I just wanted to make sure if I interpreted task properly.
- Third part of the task ("create an IPC channel..."): Create should be understood as replacing one IPC method (ipc-channel) with another (std::sync::mpsc)?
- Forth part of the task ("create a new type..."): Parent as in `webrender` object?

**Comment by jdm** [comment]
For "create an IPC channel", I meant that we should add another set of IPC and non-IPC channels to [this code](https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L550-L558), so that the constellation can receive messages over the IPC channel, route them to a non-IPC receiver, and process them in [this code](https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L907-L924).

When I referred to "pass the messages to the parent", I meant the parent process. You are correct that the intended output is to forward the messages to the actual webrender object.

You can use `./mach check` to get faster information from the compiler. It skips the actual code generation and just performs type checking on all the crates.

**Comment by jdm** [comment]
@mkmodrzew Are you still making progress on this?

**Comment by mkmodrzew** [comment]
Aw, snap, totally forget. Really sorry. Is there any problem to come back to this task now?

**Comment by jdm** [comment]
Nope!

**Comment by mkmodrzew** [comment]
Okay, I spent some time trying to replace `webrender` with local copy (previously I did it with `[patch]`, which I assume isn't correct way). This is what I added to `.cargo/config`:
```
paths = ["/home/michal/projects"]

[source]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/home/michal/projects"

[source."https://github.com/servo/webrender"]
git = "https://github.com/servo/webrender"
branch = "master"
replace-with = "vendored-sources"
```
And after `./mach check` I get:
```
`error: failed to load source for a dependency on `backtrace`
(...)
Caused by:
  found a virtual manifest at `/home/michal/projects/webrender/Cargo.toml` instead of a package manifest
```

Where I made a mistake?

**Comment by jdm** [comment]
Using patch is the expected way to override webrender for local development.

**Comment by mkmodrzew** [comment]
(Sorry for lack of updates, but I tried to change Rust setup on my PCs, and it took me awhile)

**Comment by mkmodrzew** [comment]
Sorry, but this task is overwhelming me and I will probably find something less demanding

**Comment by Beta-Alf** [comment]
I would like to try my hand on this.

**Comment by jdm** [comment]
@Beta-Alf Great! Please ask questions if anything is unclear!

**Comment by KiChjang** [comment]
@Beta-Alf Have you made any progress in this?

**Comment by Beta-Alf** [comment]
Sadly no, life kinda got in the way. Still interested but unassign me so that I don't turn into a blocker.
Thanks for checking in and sorry for not keeping you guys posted.

**Comment by ntenczar** [comment]
I may take a stab at this if that's alright!

**Comment by jdm** [comment]
That would be great!

**Comment by ntenczar** [comment]
finally got around to doing a bit of fiddling with this!

Patching servo to use the latest webrender initially didn't work because of changes made a couple days ago: https://github.com/servo/webrender/pull/2969, specifically the addition of that `ColorF` as a parameter to `push_image` in servo. 

Would it make sense to just update servo to use the latest webrender in the meantime? It looks at least like this PR: https://github.com/servo/servo/pull/21412 is already attempting to do so I may ask there as well

**Comment by ntenczar** [comment]
seemed like simply adding `ColorF::WHITE` as a parameter to `build_image` (as well as using ColorF from webrender) does the job at least

**Comment by jdm** [comment]
I did some more investigation. Right now the set of webrender operations that we need to serialize with IPC inside Servo from components/layout and components/script is:
- a scrolling transaction (Transaction::scroll_node_with_id)
- setting a display list (Transaction::set_display_list)
- performing a hit test (RenderApi::hit_test)
- updating images (Transaction::delete_image, Transaction::update_image, Transaction::add_image)

We will need to define an IPC channel for sending only these operations, and have a listener on the receiving side that creates actual webrender transactions and sends them to webrender using a RenderApi.

**Comment by jdm** [comment]
https://github.com/jdm/webrender/tree/no-ipc is an old branch that removed IPC from the webrender public interface.
