### ISSUE TITLE
Make CounterBound::Integer store an Integer

### ISSUE THREAD

**Issue by nox** [servo/servo#20197]
The type [`style::counter_style::CounterBound`](https://doc.servo.org/style/counter_style/enum.CounterBound.html) should be made to store a [`style::values::specified::Integer`](https://doc.servo.org/style/values/specified/struct.Integer.html).

**Comment by nupurbaghel** [comment]
@jdm I would like to work on this. 
Do we also need to update **components/style/gecko/rules.rs** where we are converting it to 
nscssvalue.set_enum(structs::NS_STYLE_COUNTER_RANGE_INFINITE as i32) ?

**Comment by emilio** [comment]
@nupurbaghel awesome!

You also need to update rules.rs, yes, but presumably only the `set_number` path.

**Comment by jdm** [comment]
Make sure to run `./mach build-geckolib` to ensure your changes compile.
