### ISSUE TITLE
Make android install and run commands infer location of adb from SDK

### ISSUE THREAD

**Issue by jdm** [servo/servo#20219]
Whenever I do an android build for the first time, I never remember to set up my path correctly. We already know information about the location of the SDK (from `self.config['android']['sdk']`), so we should be able to notice if invoking adb fails and attempt to run it from the SDK location manually.

Code: `python/servo/post_build_commands.py`

This will be easiest for someone to attempt if they have a working [android build](https://github.com/servo/servo/wiki/Building-for-Android) already.

**Comment by talklittle** [comment]
I've got a patch ready for this, just trying to fix unrelated Mach build errors so I can check the boxes in the PR template.

https://github.com/talklittle/servo/tree/issue-20219
