### ISSUE TITLE
text flow / layout issues on OSX

### ISSUE THREAD

**Issue by cpdean** [servo/servo#20239]
I tried building from source on `master` but I got some [interesting issues](https://www.reddit.com/r/rust/comments/82u3bm/servo_is_supposed_to_do_this_right/)

I decided I probably built it wrong, so I downloaded the nightly build from the [project page](https://download.servo.org/) and when I open the .app file I have similar symptoms:

![image](https://user-images.githubusercontent.com/160099/37151696-9f2f8082-22a4-11e8-8add-19a0a5515333.png)

I'm on osx sierra ( 10.12.6 (16G1212) ) on a 13 inch 2017 macbook pro.

**Comment by emilio** [comment]
cc @glennw, maybe OSX driver bug?

**Comment by jdm** [comment]
Yeah, I can't reproduce this on my local build on macOS Sierra on a 2015 macbook pro.

**Comment by emilio** [comment]
This looks a lot like https://bugzilla.mozilla.org/show_bug.cgi?id=1444076

**Comment by kvark** [comment]
Should be "fixed" by WR update including https://github.com/servo/webrender/pull/2499

**Comment by cpdean** [comment]
@kvark I'm still having the same issue as before:

![image](https://user-images.githubusercontent.com/160099/37217403-6ae403ce-238b-11e8-9faa-0edf65330c5a.png)

I did a git pull followed by a clean, build, and opened with the newly-built binary:

```
./mach clean
...
./mach build --dev
...
- ❯❯❯ ./mach run https://www.reddit.com/r/rust/comments/82u3bm/servo_is_supposed_to_do_this_right/
Error running module
reddit.js
:
TypeError: n.fillText is not a function
Error sending debug logs to server:
parsererror
;
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Error during reddit-init.js init
TypeError: n.fillText is not a function
2018-03-09 11:16:47.256 servo[21356:600227] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x0 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 0 was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 0 was invalidated from this process.}, com.apple.inputmethod.EmojiFunctionRowItem
Error sending debug logs to server:
parsererror
;
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

```

Am I doing something wrong to test the 'fix' from webrenderer?

**Comment by kvark** [comment]
@cpdean interesting. I can see that Servo's cargo.lock has WR version that includes the "fix".
Perhaps, the [bisection](https://bugzilla.mozilla.org/show_bug.cgi?id=1444076#c2) pointed to the wrong change? @staktrace 
I wasn't able to reproduce it, hence I myself can't confirm if the revert fixes anything.

**Comment by staktrace** [comment]
I verified the revert fixed things on the Gecko try builds.

**Comment by cpdean** [comment]
I've updated osx/macos to high sierra, 10.13.3 (17D47).

After re-installing all the xcode stuff to get rust builds working again, I still have the same issue.  I've tested with both a --dev and --release build.

How do I debug what's going on here?  I'm not sure how to compare what my build is doing versus other's who aren't experiencing this issue.

**Comment by kvark** [comment]
@staktrace since you had the original issue In Gecko, could you try checking the Servo to see if the issue is visible there?

**Comment by staktrace** [comment]
I tried the macOS build from download.servo.org and I can reproduce the issue as well. I'm on macOS 10.13.3, with a Intel Iris Plus Graphics 650 1536 MB graphics card.

**Comment by kvark** [comment]
@staktrace could you record a capture and provide something for us to investigate please?

**Comment by staktrace** [comment]
@kvark How do I get a capture in servo without doing a local build?

**Comment by kvark** [comment]
@staktrace I was thinking about the old binary recorder, which can be enabled in Servo by passing `-Z wr-record`

**Comment by staktrace** [comment]
Ah, here's a recording then. I just started servo with -Z wr-record and then closed it. The default start page had the funky text so presumably the recording should have it.
[wr-record.bin.gz](https://github.com/servo/servo/files/1811089/wr-record.bin.gz)

**Comment by kvark** [comment]
@staktrace thanks! We'll need to know the WR revision here and ultimately convert it to a "real" capture (by hitting "C" within wrench when replaying it).

**Comment by staktrace** [comment]
@kvark It's whatever version of WR was in the March 12 servo-latest.dmg.

**Comment by jdm** [comment]
That would be 6611df9fdf930db4fb93a00ce2c2d3163c0bb1a1.

**Comment by jdm** [comment]
Nevermind, it should be 6dea428a429cb6410949c14279e115122f74c501.

**Comment by kvark** [comment]
I'm not able to replay the binary capture with either of those revisions :( WR binary reader only sees a single black frame.

**Comment by kvark** [comment]
Interestingly, both @staktrace and @cpdean appear to have Iris 650 video, and I can't reproduce it on Iris 550 video (apparently, OS version is less relevant here). I'll try to find another machine to repro.

**Comment by cpdean** [comment]
@kvark you are correct, my laptop has this gpu: `Intel Iris Plus Graphics 650 1536 MB`

**Comment by kvark** [comment]
I got a MBP 2017 with Iris 650, not able to reproduce the issue with latest Servo build (downloaded from download.servo.org). @cpdean is it still an issue for you?

**Comment by cpdean** [comment]
Both the latest build on download.servo.org works for me, as does a fresh pull on master with a clean build:

```
./mach clean && ./mach build --dev && ./mach run https://www.reddit.com/r/rust/comments/82u3bm/servo_is_supposed_to_do_this_right/
```

![image](https://user-images.githubusercontent.com/160099/37542284-08e1e6a6-2934-11e8-8ce7-6f6fe4cb0ce9.png)


Whatever happened, it's now resolved.  Thanks everyone!
