### ISSUE TITLE
Support memory report logs with interleaved non-report output

### ISSUE THREAD

**Issue by jdm** [servo/servo#20257]
https://github.com/servo/servo/blob/7ccc58e3ae356108a1d17fa6fdaf07af663912b6/etc/memory_reports_over_time.py#L30-L31 should just ignore any line that doesn't begin with `|`.

Running `./mach run http://wikipedia.org -m 1` should be able to demonstrate a real world case where this matters. To process the resulting log, run `python ./etc/memory_reports_over_time.py logfile` where logfile is the file that contains the stdout from the run command.

**Comment by vugarmammadli** [comment]
@highfive : assign me!
