### ISSUE TITLE
Support building script on Arch Linux

### ISSUE THREAD

**Issue by FallingSnow** [servo/servo#20268]
Arch Linux sets `python` to python 3 and `python2` to python 2.

Script's CMakeLists.txt hard codes the python command.
https://github.com/servo/servo/blob/53d9ca1bcd902a174283314f460cc8eb30f0b67d/components/script/CMakeLists.txt#L64

In order to select the correct python version
```cmake
find_package( PythonInterp 2 REQUIRED )
```
should be added to the top of the file and all python commands should be replaced with 
```cmake
${PYTHON_EXECUTABLE}
```
so the above reads
```cmake
COMMAND ${PYTHON_EXECUTABLE} -B ${bindings_src}/pythonpath.py -I ${bindings_src}/parser -I ${bindings_src}/ply 
```

P.S. This is supported by the minimum [cmake version 2.6](https://cmake.org/cmake/help/cmake2.6docs.html#module:FindPythonInterp)

**Comment by kwonoj** [comment]
It'd be good to support build script on arch ooto. Mind if I shoot small PR for it? @FallingSnow (only if you don't have plan to tackle this)

**Comment by FallingSnow** [comment]
By all means, please. I have too many other obligations to submit a PR otherwise I would have already :)

**Comment by kwonoj** [comment]
@highfive : assign me

plz. 🙏

**Comment by kwonoj** [comment]
@FallingSnow thanks, let me try to stab on this.

**Comment by kwonoj** [comment]
@highfive : assign me
