### ISSUE TITLE
Intermittent failure in /_mozilla/mozilla/worklets/test_paint_worklet.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#20292]
cc @asajeffrey 
```
  ▶ FAIL [expected PASS] /_mozilla/mozilla/worklets/test_paint_worklet.html
  └   → /_mozilla/mozilla/worklets/test_paint_worklet.html 23b755622cc81841a23cc8431a6546dfb1401c66
/_mozilla/mozilla/worklets/test_paint_worklet_ref.html 7949e80732fa0f4afdbae3b1cad96ccd75bb04f6
Testing 23b755622cc81841a23cc8431a6546dfb1401c66 == 7949e80732fa0f4afdbae3b1cad96ccd75bb04f6
```
The non-reference image was a blank page.

**Comment by asajeffrey** [comment]
Grr, I wonder if this is related to us adding timeouts to paint worklets?

**Comment by asajeffrey** [comment]
Yes it would. 

https://github.com/servo/servo/blob/master/tests/wpt/metadata/css/css-paint-api/__dir__.ini sets `dom.worklet.timeout_ms`.

https://github.com/servo/servo/blob/master/tests/wpt/mozilla/meta/mozilla/worklets/__dir__.ini does not.
