### ISSUE TITLE
Use winit where possible instead of glutin

### ISSUE THREAD

**Issue by kvark** [servo/servo#20299]
We should use `glutin` only in parts of the code that are hardcoded to GL, and stick to `winit` in other places, like window management and events. That will simplify the process of getting more graphics backends later on. `Glutin` simply re-exports `winit` types, so this is safe to do.

cc @zakorgy , who made those changes as a part of https://github.com/szeged/servo/commit/c38ba12833856af799317cc79a5cdd2e50696d10

**Comment by SimonSapin** [comment]
As far as I can tell all of the relevant code is in `ports/servo/glutin_app/window.rs`.

**Comment by kwonoj** [comment]
@highfive assign me
