### ISSUE TITLE
Loading duckduckgo.com/html crashes Servo

### ISSUE THREAD

**Issue by atouchet** [servo/servo#20313]
Steps to reproduce:

1. Load https://duckduckgo.com/html/ in Servo.
2. The browser will crash before loading the page.

This regression first occurred in the [2018-03-13](http://servo-builds.s3.amazonaws.com/) nightly build. Tested in Windows 10.

**Comment by jdm** [comment]
I don't crash on that page, but I did crash when I tried to perform a search in the nightly build.

**Comment by jdm** [comment]
I suspect this is #20271.

**Comment by atouchet** [comment]
I am no longer able to reproduce this.

**Comment by atouchet** [comment]
@jdm are you still able to reproduce the search issue?

**Comment by atouchet** [comment]
Closing this as it's no longer an issue for me. If anyone else is still experiencing the problem feel free to reopen.
