### ISSUE TITLE
Tab support (UI)

### ISSUE THREAD

**Issue by atouchet** [servo/servo#20335]
Servo builds no longer include tabbed browsing support after the removal of the Browser.html interface. @paulrouget has [mentioned](https://groups.google.com/forum/#!topic/mozilla.dev.servo/U5zhsBLXovM) bringing tab support back. Re-adding the option for tabbed browsing would help bring Servo builds back to feature parity with the Browser.html releases.

**Comment by paulrouget** [comment]
Still planned. Waiting on #20228

**Comment by fabricedesre** [comment]
Interesting... what do you mean by "chrome document" here? Is there any markup rendering attached to it?

**Comment by paulrouget** [comment]
A chrome document is nothing different from a content document. And by document, I mean a WebRender document. It's just we will display 2 web pages on the screen (not iframes) and the embedder will send to the "chrome" document some messages about the state of the browser.

The chrome document won't have any special APIs, it will just receive and send messages (via postMessage). The content browsers won't live in the chrome document (again, no iframes).

Does it make sense?

**Comment by fabricedesre** [comment]
so how will you manage the positioning of the "content" documents in the "chrome" one?

**Comment by fabricedesre** [comment]
I guess I don't understand why you need a chrome WR view/doc at all. Is it because you want to implement some logic in chrome in JS?

**Comment by paulrouget** [comment]
That's not a problem. You can always create another view and draw tabN in that new view.

We don't want to create N views for N tabs. We just reuse the same view everytime. But if you want to split the browser in 2, that's totally possible.

**Comment by paulrouget** [comment]
Blocked on #20847

**Comment by fabricedesre** [comment]
One more question @paulrouget : if one surface paints the chrome, and another the content, the chrome one can't paint eg. a prompt dialog on top of the content? And you have to rely on a 3rd rendering mechanism for that (likely native android in your case)?

**Comment by paulrouget** [comment]
> And you have to rely on a 3rd rendering mechanism for that

Correct. Same if you want to have url suggestions as you type. You can also make it so the chrome covers the whole window with a transparent area for the content document (areas can overlap).

**Comment by fabricedesre** [comment]
Right... I guess the full size chrome with transparent areas and events pass-through is what I will play with as an alternative to a `<webview>` element. I'll have to do all the window management in Rust though, and I wonder how much that will impact performance for gestures like swipes.

**Comment by paulrouget** [comment]
This should not affect the performance. This is a lower level approach than anything we had before. For swiping, the animation will be done on WR documents or GL surfaces. You might still have to send the native events to the DOM to see if it's prevented or not, but that would also be necessary for a regular webview approach.

The current embedding API is more difficult to use than a regular webview, but it offers a lot more flexibility. But if there is something you cannot do with the current approach, or something that would be slower, let me know.

Once we got this whole system in place, we will need to have hooks on layout, script and DOM, and from here, we could implement a proper <webview>.

**Comment by fabricedesre** [comment]
We'll see. A DOM transition that goes on the GPU should not be slower than this setup. And here what I am mostly worried about is the amount of messaging between the different parts. But time will tell :)

**Comment by paulrouget** [comment]
At the end it's the same code path.

**Comment by paulrouget** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1441308

**Comment by atouchet** [comment]
Tabs were re-added in #33100.
