### ISSUE TITLE
A bunch of other @counter-style code should use `Integer::parse` instead of `expect_integer`

### ISSUE THREAD

**Issue by emilio** [servo/servo#20332]
In order to handle `calc()` correctly, code like this:

```rust
    let min_length = input.expect_integer()?;
    if min_length < 0 {
        return Err(input.new_custom_error(StyleParseErrorKind::UnspecifiedError))
    }
```

Needs to become something like:

```rust
    let min_length = Integer::parse_non_negative(context, input)?;
```

(And change the relevant data structures to store `Integer` instead of `i32` / `u32`).

**Comment by emilio** [comment]
cc @upsuper

**Comment by jdm** [comment]
Code: https://github.com/servo/servo/blob/785b7c7775ae13c02556c84a16469efc6c4d71e8/components/style/counter_style/mod.rs#L529 is one example in that file.

**Comment by kwonoj** [comment]
May I try this one if anyone's not working on it yet or need to be subsequent work of #20304?

**Comment by upsuper** [comment]
I'm not sure whether there is any sensible usecase of using `calc()` in descriptors of `@counter-style`... but sure we can support it...

**Comment by emilio** [comment]
@kwonoj sure, please do! It doesn't really interfere with #20304, as long as CounterBound is not touched.

**Comment by kwonoj** [comment]
@highfive assign me
