### ISSUE TITLE
Find out what to do about WebVR vs WebXR

### ISSUE THREAD

**Issue by nox** [servo/servo#20337]
Apparently the draft for WebVR is getting retired, and all the rage is WebXR now, with `navigator.vr` becoming `navigator.xr` and a bunch of other changes. I need to find out if WebVR needs to be retired from the code too or whether it must stay as legacy.

**Comment by atouchet** [comment]
WebVR has been removed from Servo. Is this resolved now?

**Comment by jdm** [comment]
Yep.
