### ISSUE TITLE
Improve the key events sent from the embedders to Servo

### ISSUE THREAD

**Issue by fabricedesre** [servo/servo#20331]
The key events sent by the embedder to Servo are based on Glutin ones (https://doc.servo.org/src/msg/constellation_msg.rs.html#22-147), and are then mapped to DOM Key events in `components/script/dom/keyboardevent.rs`. This is not ideal because Glutin only has a really limited subset of possible DOM Keys (eg. most  of the keys in https://w3c.github.io/uievents-key/ are missing).

Would that make sense to have the embedders do themselves the mapping from their input stack to DOM Keys instead? The other option would be to add keys to the current enum, but that doesn't seem very scalable.

@paulrouget ?

**Comment by jdm** [comment]
It does seem like a good idea to define Servo's key types in terms of what web standards describe and require embedders to communicate with Servo using those keys.

**Comment by paulrouget** [comment]
> Would that make sense to have the embedders do themselves the mapping from their input stack to DOM Keys instead? 

Absolutely.

**Comment by modal17** [comment]
May I look into this?

**Comment by paulrouget** [comment]
@modal17 absolutely. Let me know if you have any questions.

**Comment by paulrouget** [comment]
Do DOM key events cover enough to print all that is needed for an IME?

I'm thinking about Chinese characters, or dead keys combo. For example when I type: `Option+e a`, I see an accented underscore which is then replaced by `á`，or `ni1` in Pinyin will show `ni` underscored then replaced with `你`, or pressing `lll Return` will show `丿丿丿` then be replaced by`彡` with a chinese keyboard. Also, navigating the temporary string with arrow keys is controlled by the input method. I'm wondering if this is all covered by https://w3c.github.io/uievents-key/#keys-composition

**Comment by fabricedesre** [comment]
Yes, what we really need is full composition support. showIME/hideIME are needed just to trigger the virtual keyboard, and then we need something similar to Gecko's nsITextInputProcessor.

**Comment by pyfisch** [comment]
I am working on this. It mostly works. I just need to refactor the built-in keyboard shortcuts.

**Comment by neimsaci** [comment]
Hi I would like to try, is someone already working?

**Comment by pyfisch** [comment]
@neimsaci Pretty sure there is no one working on this issue.

I would really appreciate if the key events are more correctly handled. However a word of caution: it involves quite a few different systems and can be a challenging issue.

**Comment by Gae24** [comment]
What's missing to close this issue?

**Comment by mrobinson** [comment]
Yeah, I think this is finished.
