### ISSUE TITLE
Implement typed array support for XMLHttpRequest's send API

### ISSUE THREAD

**Issue by jdm** [servo/servo#20343]
Now that #20267 has merged, we can uncomment the [BufferSource](https://github.com/servo/servo/blob/master/components/script/dom/webidls/XMLHttpRequest.webidl#L16) argument to allow XMLHttpRequest.send() to support sending typed arrays as the XHR body. This will require extracting the data from the typed array in [this code](https://github.com/servo/servo/blob/bedeec0cf54011e3d15bd50ba32b6b422958b483/components/script/dom/xmlhttprequest.rs#L507-L523).

Code: `components/script/dom/webidls/XMLHttpRequest.webidl`, `components/script/dom/xmlhttprequest.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/xhr/` (this should generate a bunch of new [test pass results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations))

**Comment by nupurbaghel** [comment]
This appears to be an interesting issue. I would surely like to work on it 😄

**Comment by nupurbaghel** [comment]
The BodyInit requires extracting both the data and content_type. For a typed array, I was trying to get data using [to_vec()](https://doc.servo.org/mozjs/typedarray/struct.TypedArray.html#method.to_vec) method which requires some dereferencing I think, but I was wondering how the content type should be defined here. Should we give it a value None if its absent and Int32 otherwise ?

**Comment by jdm** [comment]
https://fetch.spec.whatwg.org/#concept-bodyinit-extract does not assign a value for content_type when the input is an arraybuffer, so leaving a None value is appropriate.

**Comment by nupurbaghel** [comment]
I tried using the following code to extract data 
> Some(DocumentOrBodyInit::ArrayBuffer(ref typedarray)) => Some((typedarray.to_vec(), None))

This results in an error: cannot borrow immutable borrowed content `*typedarray` as mutable
I couldn't find a better match than the to_vec() method which requires a mutable reference of data. data() method of typed array was one other option but that is a private method.
I need some help on how to proceed 😅  
Thank you so much :)

**Comment by jdm** [comment]
If you rebase against Servo master, that problem should be gone.
