### ISSUE TITLE
Use BufferSource and DataView in bluetooth APIs

### ISSUE THREAD

**Issue by jdm** [servo/servo#20345]
Now that #20267 has merged we can remove our workarounds for various bluetooth APIs that are supposed to accept typed arrays. This will require similar clean up as #20342.

Code: [RemoveGATTDescriptor.webidl](https://github.com/servo/servo/blob/b3ae74b5c9ae7b05af10ffbd5080d34bfc5ecb49/components/script/dom/webidls/BluetoothRemoteGATTDescriptor.webidl#L16), [BluetoothDataFilterInit](https://github.com/servo/servo/blob/0c929ad3fd902f4314844787868fe891033d3b01/components/script/dom/webidls/Bluetooth.webidl#L8), [BluetoothRemoteGATTCharacteristic](https://github.com/servo/servo/blob/b3ae74b5c9ae7b05af10ffbd5080d34bfc5ecb49/components/script/dom/webidls/BluetoothRemoteGATTCharacteristic.webidl#L20)
Tests: `./mach test-wpt tests/wpt/mozilla/tests/bluetooth`

**Comment by anthgur** [comment]
Hey I'd like to work on this! Is the workflow to un-comment the lines with the given types and update all call sites to compile and pass the test suite?

**Comment by jdm** [comment]
That's the idea! There are several issues with E-less easy that have PRs you can look at for guidance.

**Comment by anthgur** [comment]
Awesome thanks! I'll get started and check in when I have some progress.

**Comment by anthgur** [comment]
@highfive assign me

**Comment by anthgur** [comment]
The DataView part of this requires bindings that aren't available yet (see #20417 and https://github.com/servo/rust-mozjs/issues/406). I'm still going to work through the BufferSource changes.

**Comment by anthgur** [comment]
@jdm note that the DataView updates are still pending here

**Comment by jdm** [comment]
Tracking DataView in #20849.
