### ISSUE TITLE
Implement support for blobs created from typed arrays

### ISSUE THREAD

**Issue by jdm** [servo/servo#20348]
Now that #20267 has merged we can implement APIs that accept typed arrays as arguments. The ArrayBuffer and ArrayBufferView types are commented out in the BlobPart union, so uncommenting them means we need to modify the blob constructor to deal with typed arrays.

Code: `components/script/dom/webidls/Blob.webidl`, `components/script/dom/blob.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/FileAPI` (there should be some new [passing tests](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations))

**Comment by christianpoveda** [comment]
@highfive assign me
