### ISSUE TITLE
Replace WebGL APIs that accept `object` argument with typed arrays instead

### ISSUE THREAD

**Issue by jdm** [servo/servo#20342]
Now that #20267 and has merged, we can remove our workarounds for WebIDL APIs that are supposed to accept typed array arguments. https://github.com/servo/servo/blob/bedeec0cf54011e3d15bd50ba32b6b422958b483/components/script/dom/webidls/WebGLRenderingContext.webidl#L491-L498, and there are a bunch of other commented out APIs that we should be able to uncomment (while removing the versions which have `object` or `object?` arguments in their place. These will require updating the implementation of the APIs as well: [the BufferData](https://github.com/servo/servo/blob/bedeec0cf54011e3d15bd50ba32b6b422958b483/components/script/dom/webglrenderingcontext.rs#L1630-L1639) implementation will be replaced with something like [this](https://github.com/servo/servo/blob/bedeec0cf54011e3d15bd50ba32b6b422958b483/components/script/dom/testbinding.rs#L454) instead.

**Comment by Xanewok** [comment]
If possible, I'd like to continue working on this for our bachelor thesis.
