### ISSUE TITLE
Implement websocket send operations for typed arrays

### ISSUE THREAD

**Issue by jdm** [servo/servo#20347]
Now that #20267 has merged we can implement WebIDL APIs that accept typed array arguments, like the two WebSocket.send methods that take ArrayBuffer and ArrayBufferView.

Spec: https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket-send
Code: `components/script/dom/webidls/WebSocket.webidl`, `components/script/dom/websocket.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/websockets`

**Comment by christianpoveda** [comment]
@highfive assign me
