### ISSUE TITLE
Update num-traits to 0.2

### ISSUE THREAD

**Issue by Eijebong** [servo/servo#20356]
- [x] https://github.com/servo/app_units/pull/43
- [x] https://github.com/servo/euclid/pull/279         
- [x] image (needs enum_primitive)
- [x] https://github.com/netvl/immeta/pull/14         
- [x] mozjs          
- [x] mp4parse       
- [x] ordered-float  
- [x] plane-split (needs euclid)
- [x] webrender

**Comment by Eijebong** [comment]
@highfive assign me

**Comment by atouchet** [comment]
Can this be closed now?

**Comment by Eijebong** [comment]
Yes https://github.com/servo/servo/pull/21372
