### ISSUE TITLE
Acid2 not pixel perfect

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#2035]
This is Gimp’s Difference blend mode of
- Servo rendering the test http://acid2.acidtests.org/#top 
- Servo rendering the reference http://acid2.acidtests.org/reference.html

With commit fe1615bc3dc3bd2f8d3fbb6f776e701b4c6dda76.

![diff](https://cloud.githubusercontent.com/assets/291359/2616767/5c9950f4-bc0a-11e3-9787-4bdac60e2920.png)

The main problem seems to be that scrolling to `#top` leaves us at a non-integer pixel position, causing anti-aliasing issues. The test because almost pixel-perfect (except the nose that’s 1px off and the eyes that seem to round alpha blending differently than the reference) if I remove this part of the test, with these additional style rules:

``` css
.intro { display: none }
#top { margin-top: 0 }
```

**Comment by mrobinson** [comment]
A lot has changed since this bug was filed. There's no more layers and display scaling can cause lots of issues unrelated to the original problems here. I think maybe this particular bug isn't so useful any longer.
