### ISSUE TITLE
Remove the overscroll code

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#20360]
By overscroll, I mean the bouncing effect when scrolling beyond the borders of the page.

We are implementing this at the embedder level. For example, on Android, we will be using an OverScroller and draw the overscroll effect directly on top of Servo.

@glennw , who could take care of this?

**Comment by glennw** [comment]
Do you mean within WR or is there overscroll code in Servo itself?

**Comment by paulrouget** [comment]
@glennw It's implemented in WR, yes.

**Comment by glennw** [comment]
@paulrouget OK - if you could open a WR issue with the details, I can gladly remove that code :)

**Comment by paulrouget** [comment]
Filed https://github.com/servo/webrender/issues/2545
