### ISSUE TITLE
The `Idle` state is not always reached at the end of css transitions

### ISSUE THREAD

**Issue by fabricedesre** [servo/servo#20379]
When a css transition is ongoing, the embedder is notified by the https://doc.servo.org/compositing/windowing/trait.WindowMethods.html#method.set_animation_state method with state value of `Animating`, and then back with the `Idle` value once the animations are done.

I have a couple of cases where we don't go back to the `Idle` state after a transition, and instead keep hammering the embedder with `Animating` notifications. This may not be too much noticeable on desktop, but it can be pretty bad on some mobile devices (and it's wrong anyway).

Just filing for now until I manage to build a simple enough test case to reproduce.

**Comment by fabricedesre** [comment]
Here's a test case:
```html
<!DOCTYPE html>
<html>

<head>
    <style>
        div {
            transition: transform 0.5s;
            position: absolute;
            top: 0;
            left: 0;
            width: 200px;
            height: 200px;
            background-color: teal;
        }

        div.moved {
            transform: translate(150px, 150px);
        }
    </style>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            window.addEventListener("click", () => {
                document.getElementById("box").classList.toggle("moved");
            });
        });
    </script>
</head>

<body>
    <div id="box"></div>
</body>

</html>
```

if you apply this patch:
```
diff --git a/ports/servo/glutin_app/window.rs b/ports/servo/glutin_app/window.rs
index b6ef3e2e3b..0cd6cfcc61 100644
--- a/ports/servo/glutin_app/window.rs
+++ b/ports/servo/glutin_app/window.rs
@@ -905,6 +905,7 @@ impl WindowMethods for Window {
     }
 
     fn set_animation_state(&self, state: AnimationState) {
+        println!("set_animation_state {:?}", state);
         self.animation_state.set(state);
     }

```
and click a couple of times to get the box back to (0, 0) you will see that `set_animation_state Animating` is printed constantly.

In `components/layout/animation.rs`, `update_animation_state` reinjects a new animation from `new_animations_receiver` at the end of the expected one, over and over in an endless loop. That stops when we switch back to the `.moved` state.

**Comment by fabricedesre** [comment]
Maybe related to issue #20116

**Comment by emilio** [comment]
#14418 didn't make sense. See the `mark_as_expired` bit there going away.

**Comment by emilio** [comment]
Our transitions story in general makes no sense, apparently.

**Comment by fabricedesre** [comment]
:cry: @emilio do you have time to spend on fixing that?

**Comment by paulrouget** [comment]
On a transition, are we supposed to wakeup the embedder loop on each frame? It looks like we do, but I thought that the point of `setAnimationState(animating)` was to avoid having to do so.

**Comment by paulrouget** [comment]
Dupe. STR from #25262

```html
<style>
  div {
    width: 200px;
    height: 200px;
    margin:200px;
    background: red;
    transition: 200ms linear transform;
  }
  div:hover {
    transform:scale(1.2);
  }
</style>
<div></div>
```

- mouse hover div
- animating then not animating (good)
- move mouse outside of the div
- animating is sent (good) but `NoAnimationsPresent` is never sent after the animation is finished

**Comment by paulrouget** [comment]
After animation is over, it is stopped, and ran again, and stopped, and ran again…

After each animation, the animation sender resend an animation. Basically after the animation is over, this is called again: https://github.com/servo/servo/blob/b7aaff499501e0f1f0d411db5059f59e4828419d/components/style/animation.rs#L405
