### ISSUE TITLE
Investigate if GetTexParameter should fail if 0 is returned.

### ISSUE THREAD

**Issue by gootorov** [servo/servo#20372]
Currently `GetTexParameter` fails if 0 is returned, but none of the specs specify that.
Specs:
[WebGL](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.8)
[GLES](https://www.khronos.org/registry/OpenGL/specs/es/2.0/es_full_spec_2.0.pdf#nameddest=section-6.1.3)
https://github.com/servo/servo/blob/730bd5ec807fec0ed65bbf85afebe3bbca64b32c/components/canvas/webgl_thread.rs#L1075-L1077
https://github.com/servo/servo/blob/730bd5ec807fec0ed65bbf85afebe3bbca64b32c/components/script/dom/webglrenderingcontext.rs#L1362-L1364

**Comment by brainlessdeveloper** [comment]
This is not the case anymore:
```rust
    fn get_tex_parameter(gl: &gl::Gl,
                       target: u32,
                       pname: u32,
                       chan: WebGLSender<i32> ) {
        let result = gl.get_tex_parameter_iv(target, pname);
        chan.send(result).unwrap();
    }
```
https://github.com/servo/servo/blob/master/components/canvas/webgl_thread.rs#L1084-L1090
I think?

**Comment by gootorov** [comment]
It was refactored, but the check was left intact:
https://github.com/servo/servo/blob/e06f0d32d0c3973d460a3035d2adfea298c8e5fe/components/script/dom/webglrenderingcontext.rs#L1408-L1414

If it's not needed, the whole thing can be simplified to `Int32Value(receiver.recv().unwrap())`.
