### ISSUE TITLE
Make DOM bindings methods not take raw JSContext pointers

### ISSUE THREAD

**Issue by jdm** [servo/servo#20377]
There's a lot of methods that accept a `*mut JSContext` argument, and these methods have to be marked unsafe because callers could pass anything to them, not just a valid JSContext pointer. I propose the following:
* create a `struct JSContext(*mut jsapi::JSContext)` type
* implement `Deref` for this new type so it's easy to obtain the inner context pointer
* add an unsafe `from_ptr` static method that returns a new instance of the type
* make the code generator declare trait methods that accept the new type instead of `*mut JSContext` ([here](https://github.com/servo/servo/blob/797fb553bbfdece69538644da89bb0c937ece997/components/script/dom/bindings/codegen/CodegenRust.py#L5546) and [here](https://github.com/servo/servo/blob/797fb553bbfdece69538644da89bb0c937ece997/components/script/dom/bindings/codegen/CodegenRust.py#L6541); both the type )
* adjust generated code to pass `JSContext::from_ptr(cx)` when necessary ([here](https://github.com/servo/servo/blob/797fb553bbfdece69538644da89bb0c937ece997/components/script/dom/bindings/codegen/CodegenRust.py#L3242-L3245))
* update all of the methods defined in `components/script/dom` that need to be changed
* remove any unnecessary uses of `#[allow(unsafe_code)]` on methods that no longer accept raw pointers

No need to run any automated tests. If it builds, it's good enough for a pull request.

**Comment by csmoe** [comment]
I will take this.

**Comment by csmoe** [comment]
@jdm Before the first step, could you give a suggestion where the `struct JScontext` should be placed?
`script/dom/mod.rs` or `script/lib.rs`?

**Comment by jdm** [comment]
@csmoe Let's go with `script/script_runtime.rs`.

**Comment by jdm** [comment]
One additional benefit to this change - we could make the Promise constructor APIs take this safe JS context type instead of a GlobalScope reference, and make all DOM APIs that return a Promise take this this type. This would make a bunch of promise-related DOM code more clear.

**Comment by oneturkmen** [comment]
hey @jdm, can you assign this to me (if still valid)?

**Comment by jdm** [comment]
@oneturkmen Yes, this is definitely still valid! Please ask questions if anything is unclear :)

**Comment by oneturkmen** [comment]
As far as I understand, the code in `CodegenRust.py` should be transformed in the following way:
- All `*mut JSContext` become just `JSContext` (this is a new safe struct).
- Turning all `CGGeneric("cx")` into `CGGeneric("JSContext::from_ptr("cx")")`.

If I am correct, is `CGGeneric` the only place that spits out code? And the only class, which call of "cx" we should transform (2nd bullet above).

**Comment by jdm** [comment]
It occurs to me - if we define the new type with `repr(transparent)`, then we can write all of our Rust FFI functions (ie. any python class that inherits from CGAbstractExternMethod and generates a `extern "C" fn foo(...)`) so that they accept the new `JSContext` rust type instead of `*mut JSContext`. That will require changing a bunch of calls in CodegenRust.py from `Argument('*mut JSContext', 'cx')` to `Argument('JSContext', 'cx')`, and then changing all of the calls to JSAPI methods from rust-mozjs (ie. ObjectIsDate, to_jsval, JS_[whatever]) that still expect `*mut JSContext` to pass `*cx` instead of `cx`.

I doubt there are many places that specifically have `CGGeneric("cx")`. You are more likely to encounter code like [this](https://github.com/servo/servo/blob/b4ed3b6f3c6f8dedde41ac28ec3afdb117f5a44a/components/script/dom/bindings/codegen/CodegenRust.py#L722) which uses `cx` in the middle of some other Rust code.

**Comment by oneturkmen** [comment]
When you say:

> ... changing all of the calls to JSAPI methods from rust-mozjs (ie. ObjectIsDate, to_jsval, JS_[whatever]) that still expect *mut JSContext to pass *cx instead of cx.

Do you mean changing in the servo/rust-mozjs repo?

**Comment by jdm** [comment]
I am inclined to leave rust-mozjs alone until we demonstrate the usefulness of this idea. This is why I suggested `implement Deref for this new type so it's easy to obtain the inner context pointer` originally, so we can use `*cx` for any code that still requires a `*mut JSContext` argument.

**Comment by oneturkmen** [comment]
So, I am currently getting more than 5K compilation errors, though one of them I cannot understand:

![image](https://user-images.githubusercontent.com/17970732/60751701-c6fe7400-9f77-11e9-84b9-611f95d3ab8d.png)

The new code defined in `script_runtime.rs` does not seem to be in use now (though I defined `Deref` for it). How can I (if I should) import it from `script_runtime.rs` to CodegenRust.py? Let me know if my question makes sense.

**Comment by jdm** [comment]
There is a big list of use statements in CodegenRust.py. you can add it there and remove the existing JSContext import.

**Comment by oneturkmen** [comment]
I changed all `use js::jsapi::JSContext` to `use crate::script_runtime::JSContext`. I also changed the calls to `cx`, from `cx` to `*cx`, and `Argument('*mut JSContext', 'cx')` to `Argument('JSContext', 'cx')`.

However, for some reason, code still expects JSContext from JSAPI. This is one example:

![image](https://user-images.githubusercontent.com/17970732/60761349-9237fe80-a003-11e9-9815-745ef71d8e13.png)

Am I missing something? (p.s. sorry for being bothersome)

**Comment by jdm** [comment]
Did you add the Deref impl for the new struct?

**Comment by jdm** [comment]
Oh wait, that's different. That'scode that is executing with a cx bound to a *mut JSContext already.

**Comment by oneturkmen** [comment]
yup, I implemented `Deref`. It seems that there is smth beyond `CodegenRust.rs` where this error originates from.

**Comment by jdm** [comment]
I recommend looking at the generated source file that is triggering the error to trace it back to the python that is generating it.

**Comment by jdm** [comment]
Also if you could push the code, it will be easier to understand what might be causing this behaviour.

**Comment by oneturkmen** [comment]
sure thing

**Comment by oneturkmen** [comment]
Btw, when you said

> changing all calls from Mozjs that still expect `*mut JSContext` to pass `*cx` instead of `cx`... 

Did you mean only in `CodegenRust.py` file or in all `/dom` files?

**Comment by jdm** [comment]
Any code that is still written to accept `*mut JSContext` will not be able to accept the new `JSContext` values by default. It will probably be easiest to start by passing `*cx` everywhere from inside CodegenRust.py, then slowly adapt callee code piece by piece to accept the new type. It's easier to review and reason about large changes like this piece by piece, rather than all at once.

**Comment by jdm** [comment]
Unassigned per private request. The work in #23657 was off to a good start, and https://github.com/servo/servo/pull/23657#issuecomment-510225906 contains the most up to date plan for how to continue making progress on it if anybody else would like to give it a try!

**Comment by marmeladema** [comment]
I am willing to give it a try @jdm

**Comment by jdm** [comment]
@marmeladema Great! Take a look at the prior work and plans and ask questions if anything is unclear :)

**Comment by marmeladema** [comment]
This issue was closed automatically by @bors-servo but we might want to continue going forward with this. Should this issue be reopened or a new one created with more specific goals?

**Comment by jdm** [comment]
We can open new issues for followups.
