### ISSUE TITLE
Implement the ANGLE_instanced_arrays WebGL extension

### ISSUE THREAD

**Issue by nox** [servo/servo#20383]
* https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays
 * https://www.khronos.org/registry/webgl/extensions/ANGLE_instanced_arrays/

Needed to run https://vr.mozilla.org/webvr-demos/demos/sechelt/?mode=vr

**Comment by jdm** [comment]
Is this done now?

**Comment by nox** [comment]
Yes
