### ISSUE TITLE
Support x86-android builds

### ISSUE THREAD

**Issue by jdm** [servo/servo#20393]
This should allow using the x86 android emulator, which is significantly more usable than the armv7 one.

**Comment by jdm** [comment]
I've got a hacky branch that I was able to run in the emulator a couple weeks ago. I'm working on rebasing it and cleaning it up.

**Comment by paulrouget** [comment]
This works.

**Comment by SimonSapin** [comment]
For posterity: the incantation is adding `--target i686-linux-android` to the build command.
