### ISSUE TITLE
GamepadButtonList::sync_from_vr should use more iterators

### ISSUE THREAD

**Issue by jdm** [servo/servo#20392]
Instead of using an index variable and unwrapping the result of calling `get`, we should use the [zip](https://doc.servo.org/core/iter/trait.Iterator.html#method.zip) iterator method to iterate over `self.list` simultaneously with `vr_buttons`.

Code: `components/script/dom/gamepadbuttonlist.rs`

No need for automated tests; if it builds, that's enough for a pull request.

**Comment by MaximilianDauner** [comment]
Hey  @highfive 
I would like to edit this issue.

**Comment by KiChjang** [comment]
@MaximilianDauner It's now assigned to you!
