### ISSUE TITLE
Remove use of tinyfiledialogs from bluetooth code

### ISSUE THREAD

**Issue by jdm** [servo/servo#20429]
Right now the engine is responsible for making UI appear to allow the user to choose an input file: https://github.com/servo/servo/blob/f467bdce1ba95e950b01f59ba284873137bca5d5/components/bluetooth/lib.rs#L369-L397

Instead, the bluetooth code should send a message to the constellation, which can talk to the embedder and receive the final selection to return to the bluetooth code. This means the bluetooth thread needs to have access to a channel which can communicate with the constellation; this can come from [BluetoothManager::new](https://github.com/servo/servo/blob/f467bdce1ba95e950b01f59ba284873137bca5d5/components/bluetooth/lib.rs#L212)  via [BluetoothThreadFactory](https://github.com/servo/servo/blob/f467bdce1ba95e950b01f59ba284873137bca5d5/components/bluetooth/lib.rs#L72-L76). [This](https://github.com/servo/servo/blob/f467bdce1ba95e950b01f59ba284873137bca5d5/components/constellation/constellation.rs#L1845-L1851) is a good model for communicating with the embedder from the constellation.

It's possible to test these changes if you're on linux and you enable the bluetooth preferences and try one of the demo WebBluetooth, but it's also possible to make these changes without testing them.

**Comment by kwonoj** [comment]
I think this is cruxwise same as https://github.com/servo/servo/issues/20428, let me try to apply same practices. @highfive assign me
