### ISSUE TITLE
Remove use of tinyfiledialogs from network code

### ISSUE THREAD

**Issue by jdm** [servo/servo#20428]
Right now the engine is responsible for making UI appear to allow the user to choose an input file: https://github.com/servo/servo/blob/34f388229df4f201302ee51a8969c0556692bf0b/components/net/filemanager_thread.rs#L39-L67

Instead, the network code should send a message to the constellation, which can talk to the embedder and receive the final selection to return to the network code. This means the FileManager needs to have access to a channel which can communicate with the constellation; this can come from [CoreResourceManager::new](https://github.com/servo/servo/blob/34f388229df4f201302ee51a8969c0556692bf0b/components/net/resource_thread.rs#L303)  via [new_resource_threads](new_resource_threads). [This](https://github.com/servo/servo/blob/f467bdce1ba95e950b01f59ba284873137bca5d5/components/constellation/constellation.rs#L1845-L1851) is a good model for communicating with the embedder from the constellation.

To test this code, verify that it's possible to submit an HTML form that includes a `<input type="select">` element after choosing a file.

**Comment by kwonoj** [comment]
@jdm mind if I try to give a shot for this?

**Comment by jdm** [comment]
Go for it!

**Comment by kwonoj** [comment]
:bowing_man:  @highfive assign me
