### ISSUE TITLE
./mach does not work if the environment variable `$PATH` contains Unicode characters

### ISSUE THREAD

**Issue by StyMaar** [servo/servo#20435]
## Problem :

On linux, when attempting to run `./mach build --dev` I got this error :

```
Traceback (most recent call last):
  File "./mach", line 94, in <module>
    main(sys.argv)
  File "./mach", line 23, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/home/stymaar/dev/servo/python/mach_bootstrap.py", line 268, in bootstrap
    _activate_virtualenv(topdir, is_firefox)
  File "/home/stymaar/dev/servo/python/mach_bootstrap.py", line 157, in _activate_virtualenv
    python = _get_exec_path(PYTHON_NAMES)   # If there was no python, mach wouldn't have run at all!
  File "/home/stymaar/dev/servo/python/mach_bootstrap.py", line 93, in _get_exec_path
    path = find_executable(name)
  File "/usr/lib/python2.7/distutils/spawn.py", line 220, in find_executable
    f = os.path.join(p, executable)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
```

## Diagnostic

It looked related to https://github.com/servo/servo/issues/10002 but the path to my servo directory only contained ASCII caracters.

The problem came because my $PATH environment variable was set to :

`/home/stymaar/.cargo/bin:/home/stymaar/bin:/home/stymaar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/stymaar/Téléchargements/node-v8.8.0-linux-x64/bin`

Notice the **Téléchargements**.

## Solution

The solution is straightforward : remove the culprit non-ASCII characters form the $PATH variable (in my case, just move the `node` installation out of the `Téléchargement` directory).

I hope this will help people that may encounter this bug in the future.

**Comment by tigercosmos** [comment]
I thought it is clearer that rename the title to "./mach does not work if ***environment variable*** $PATH contains Unicode characters". 👍

**Comment by mrobinson** [comment]
This seems to be working now, probably due to the upgrade to Python 3.
