### ISSUE TITLE
Paint worklet tests are busted

### ISSUE THREAD

**Issue by jdm** [servo/servo#20463]
Due to https://github.com/w3c/web-platform-tests/commit/0bfaa837553a7b66b84b207e702b6b403ad6d990, the reftests now rely on `/common/worklet-test.js` which introduced a use of `async` in https://github.com/w3c/web-platform-tests/commit/7988e1756539bcdf39ec2102b99e0671c44d503c. This means that our SpiderMonkey now chokes on these tests, so we have no test coverage of the CSS Paint API any longer.

cc @asajeffrey

**Comment by asajeffrey** [comment]
Grr. I get this for both worklets and SMup.

**Comment by asajeffrey** [comment]
#20585

**Comment by atouchet** [comment]
Is this still an issue?

**Comment by jdm** [comment]
Nope!
