### ISSUE TITLE
Go back/forward keybinding should not traverse history on key release

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#20478]
When using the go forward/back keybindings to traverse the session history, the constellation is flooded with traversal messages as long as the key binding is held down. We should just send a single message for a key press or at least have an interval of a second or so between subsequent messages.

I am using macOS, not sure if this is the case on other platforms.

**Comment by paulrouget** [comment]
I think it's not repeating too fast. But we get 2 events for key down and key up. So the event is sent twice.

**Comment by paulrouget** [comment]
Note to whoever might work on this: if we send reload/goForward/… messages on `KeyState::Pressed`, we need to figure out if we need to send key window events to Servo on KeyState::Released key events.

**Comment by cbrewster** [comment]
We should only send the `Navigation` event on key pressed or key repeated and not on key released.
To fix this, check the `state` in both these branches and make sure it is not equal to key released.
https://github.com/servo/servo/blob/07dd37a0cf2eb19a294b27404f1deee1ee6e8fd7/ports/servo/browser.rs#L123-L134

**Comment by piotr-szpetkowski** [comment]
Hi.
I don't have much experience in Rust, but it seems like an easy thing to do, so I'll try to tackle it.

@highfive: assign me

**Comment by paulrouget** [comment]
#21250 fixed this.
