### ISSUE TITLE
Servo should support percentages in column-gap.

### ISSUE THREAD

**Issue by emilio** [servo/servo#20498]
Gecko is gaining support for those, but Servo probably should too.

Code for this lives in `components/layout/multicol.rs`.

**Comment by emilio** [comment]
Gecko bug for this is https://bugzilla.mozilla.org/show_bug.cgi?id=1398537

**Comment by emilio** [comment]
@mbrubeck would this be something you could mentor?

**Comment by mbrubeck** [comment]
Sure!

Step 1 is to change the [type of this property][1] to `NonNegativeLengthOrPercentageOrNormal` always, not just in "gecko" mode.

Step 2 is to change the [layout code][2] to convert percentages to absolute lengths.  `LengthOrPercentage` can be converted to `Length` using [`to_pixel_length`][3].  For the containing length, use `content_inline_size`. (Jargon note: "inline size" and "width" are used interchangeably in this code, as the "inline" direction is horizontal by default.)

[1]: https://github.com/servo/servo/blob/a208d4246cf0e02a1a22196f26692bd29fb35011/components/style/properties/longhand/column.mako.rs#L34-L35
[2]: https://github.com/servo/servo/blob/a208d4246cf0e02a1a22196f26692bd29fb35011/components/layout/multicol.rs#L109-L113
[3]: http://doc.servo.org/geckolib/style/values/computed/length/enum.LengthOrPercentage.html#method.to_pixel_length
[4]: https://www.w3.org/TR/css-multicol-1/#column-gap

**Comment by git-jim** [comment]
I would like to poke around at this issue to get familiar with the codebase a bit.  I don't want that to stop someone else from working on it, too, though.  My schedule is crazy unpredictable and I am not sure how much time I'll be able to put towards it.  I just tend to learn faster if I have an objective more focused than "learn all the stuffs."

**Comment by Ramshell** [comment]
@mbrubeck 

Is it necessary to add tests for this issue? If that is the case: In which dir should it be?

**Comment by emilio** [comment]
There should be tests already for this in WPT.

In particular: css/css-align/gaps/column-gap-parsing-001.html for the parsing bits, and testing/web-platform/meta/css/css-multicol/multicol-gap-percentage-001.html for the layout bits.

**Comment by Ramshell** [comment]
@highfive: assign me
