### ISSUE TITLE
Error when building servo on virtual machine

### ISSUE THREAD

**Issue by irrationalRock** [servo/servo#20503]
Hi, I don't know if this is the right place to file this issue but I'm having problems with Servo.

When I run './mach build --dev' on my fedora virtual machine gives this error:

```
thread '<unnamed>' panicked at 'failed to shut down worker thread', /cargo/registry/src/github.com-1ecc6299db9ec823/jobserver-0.1.9/src/lib.rs:650:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Error during translation/LLVM phase.

error: Could not compile `script_traits`.
warning: build failed, waiting for other jobs to finish...
error: build failed
[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
Build FAILED in 0:57:28
```

**Comment by SimonSapin** [comment]
My random guess is that the VM is running out of either RAM or disk space. How much of each does it have? Can you try running `RUST_BACKTRACE=1 ./mach build --dev` while monitoring resource usage?

**Comment by irrationalRock** [comment]
I have around 40GB of storage and 3GB of RAM? Is that enough to run servo? I'll try your suggestion of running `RUST_BACKTRACE=1 ./mach build --dev` soon.

**Comment by SimonSapin** [comment]
3 GB is probably not enough RAM, unfortunately. Can you assign more to the VM (our smallest CI builders have 8 GB), or use a swap file or partition?

**Comment by irrationalRock** [comment]
Unfortunately, I can't assign more RAM.
I'm wondering is there any documentation that mentions what the recommended specs are to run Servo?
I think it would be helpful to add if it's not there.

**Comment by dralley** [comment]
Not a bug.  Documenting a minimum requirement for memory usage might be useful but seems like it might be difficult to quantify.
