### ISSUE TITLE
Q2 2018 roadmap update

### ISSUE THREAD

**Issue by atouchet** [servo/servo#20511]
With it being April now we're already into Q2. It would be nice to keep up with roadmap updates this time around as the roadmap was a bit neglected last year.

@jdm are the overall 2018 plans still accurate with the new mixed reality focus?

**Comment by pyfisch** [comment]
If the does not have the time to update or can not share the plans maybe it is better to remove the roadmap. 

The [projects](https://github.com/servo/servo/projects) page can also be used as a replacement, maybe these stay more up to date as the page is already used for organization and does not need to specifically written.

I would really like to have a better idea what the team at Mozilla is working on and a roadmap is a useful resource for me.

**Comment by larsbergstrom** [comment]
Thanks and sorry for the delay! Indeed, I'd like to move to the projects page for more fine-grained tracking of work and the work backlog.

I'll update the roadmap wiki with the high-level plans and a pointer to the projects page.

**Comment by larsbergstrom** [comment]
Done!

**Comment by pyfisch** [comment]
:+1: Great overview!
