### ISSUE TITLE
Implement WebGLRenderingContext.getRenderbufferParameter

### ISSUE THREAD

**Issue by nox** [servo/servo#20514]
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.7

**Comment by brainlessdeveloper** [comment]
I'll begin working on this one if that's OK

**Comment by nox** [comment]
@brainlessdeveloper Sure! Ping me here or on IRC if you need help.

**Comment by nox** [comment]
Indeed it is not, so it needs to be implemented. Do you need help with that, or do you feel like you can do it on your own? Either way is fine.

**Comment by nox** [comment]
@brainlessdeveloper Do you want some clues?

**Comment by brainlessdeveloper** [comment]
I haven't had time to work on the gleam PR, but my Servo PR is almost ready, of course, except for the fact that the implementation of the command for gleam doesn't exist.

I'll push the Servo code on my fork and see if I have time to work on the gleam PR tomorrow. Some initial pointers would be nice, yes. Thanks!

**Comment by nox** [comment]
You more or less want to do something similar as in https://github.com/servo/gleam/pull/158, where you add the method to the trait in `gl.rs` and implement it in both `gl_fns.rs` and `gles_fns.rs`.

**Comment by brainlessdeveloper** [comment]
Thanks! I'll get to it as soon as I find some time.

**Comment by brainlessdeveloper** [comment]
Here's my WIP https://github.com/brainlessdeveloper/servo/commit/094b4a99ee1a482d95c5e50bcf505cc44006d513

I think it's not missing a lot but we'll see what fails once I implement the other function for gleam.
