### ISSUE TITLE
error on ./mach build --dev

### ISSUE THREAD

**Issue by rgeraldporter** [servo/servo#20520]
See here for output: https://gist.github.com/rgeraldporter/7a96a5583c40f7eea567c680bf0231cb

I've tried all kinds of things, updated rustc, looked up and installed potential missing dependencies. Did everything in the readme of course. Any ideas?

**Comment by paulrouget** [comment]
Which OS?

What's your llvm version? (`clang --version`)

**Comment by rgeraldporter** [comment]
MacOS 10.13.3

```
08:59 $ clang --version
clang version 5.0.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 49828f21d7a2e4587b2749e0e3940bb85f932abb) (https://github.com/kripken/emscripten-fastcomp/ 0a60b19dc4b9068c52b952598a2636dc370e56ce) (emscripten 1.37.35 : 1.37.35)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Users/rob/emsdk-portable/clang/fastcomp/build_incoming_64/bin

  Registered Targets:
    js     - JavaScript (asm.js, emscripten) backend
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

**Comment by paulrouget** [comment]
I don't know much about this, but I'm surprised to see this version of clang.

Can you make it so it uses Xcode's tools?

```
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

What does `xcodebuild -find clang` say?

**Comment by rgeraldporter** [comment]
Here's what I get:

```
09:16 $ xcodebuild -find clang
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
```

thanks!

**Comment by paulrouget** [comment]
Maybe use that install of llvm instead of /Users/rob/emsdk-portable/.

**Comment by rgeraldporter** [comment]
What's the recommended way of switching to another LLVM for this? Never had to do that before.
Thanks in advance! :)

**Comment by paulrouget** [comment]
In your bashrc remove the code that modifies your PATH (/Users/rob/emsdk-portable/clang/fastcomp/build_incoming_64/ doesn't have to be in your path)
