### ISSUE TITLE
Implement gl.getParameter(gl.ALIASED_LINE_WIDTH_RANGE)

### ISSUE THREAD

**Issue by nox** [servo/servo#20535]
https://github.com/servo/servo/pull/20414 is pretty similar.

https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

**Comment by mattnenterprise** [comment]
I would like to have a go at this. I have already submitted a pull request for the gleam work at  https://github.com/servo/gleam/pull/163

**Comment by nox** [comment]
Sure!
