### ISSUE TITLE
Implement gl.getParameter(gl.BLEND_COLOR)

### ISSUE THREAD

**Issue by nox** [servo/servo#20536]
https://github.com/servo/servo/pull/20414 is pretty similar.

https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

**Comment by MaximilianDauner** [comment]
Hey,
I would like to work on that issue.

**Comment by MaximilianDauner** [comment]
Hello @nox,
I am not that familiar with servo yet.
Do I have to add new functions to servo/gleam (like alias_line_width_range) to solve that issue.
Or is there another way to get the blend color ?

**Comment by nox** [comment]
Oops sorry I didn't see your message 5 days ago.

Things are slightly hectic right now because of some CI bustage which doesn't let me merge some WebGL refactoring to help with that. I'll come back to you for when this is fixed (should be fine tomorrow). Meanwhile I'll mark this issue as assigned so that we reserve it for you.

Thanks for the help!
