### ISSUE TITLE
Image created with texImageDom (DOM to texture) is mirrored vertically

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#20540]
In a simple demo page that uses the experimental  `gl.texImageDOM` API (#18592) to render an iframe to a WebGL texture, the resulting image seems to be mirrored on the Y axis.  I'm not sure if this is a Servo bug, a WebRender bug, or a bug in my demo page...

![screenshot from 2018-04-04 14-00-09](https://user-images.githubusercontent.com/5920/38334653-c509f018-3810-11e8-8783-5f444f81d602.png)

**Comment by mbrubeck** [comment]
The example code is here: https://github.com/mbrubeck/servo/tree/teximagedom/tests/html/dom_to_texture

Run it with `./mach run --pref dom.webgl.dom_to_texture.enabled tests/html/dom_to_texture/index.html` and then press the "F" key three times to activate the `texImageDOM` code.

**Comment by glennw** [comment]
If you invert the V texture coords here:

https://github.com/mbrubeck/servo/blob/9d1d87e0da60742d66f26beaa6c6acc5806ba6a1/tests/html/dom_to_texture/index.html#L301

It will draw correctly. Not sure if we should be accounting for that internally, or if it's reasonable to expect the client to do that.

**Comment by nox** [comment]
This seems pretty weird to me that the thing is inverted, is there any precedent for letting the client to do that anywhere else in the WebGL stack?

**Comment by emilio** [comment]
There's the `FLIP_Y_AXIS` flag for texture uploads, which is slightly related.

**Comment by glennw** [comment]
In WR, we blit the contents of a frame output buffer for DOM to texture here:

https://github.com/servo/webrender/blob/9074bf86091952cfaeba9a9f81a10b539c064c9f/webrender/src/renderer.rs#L3061

Which calls ```glBlitFramebuffer``` here:

https://github.com/servo/webrender/blob/9074bf86091952cfaeba9a9f81a10b539c064c9f/webrender/src/device.rs#L1226

I *think* it's valid to invert the destination y0 and y1 values here. Assuming that's true, you could pass a flag to the blit render target function in device.rs if you want the image inverted. We could enable this for the frame output functionality above.
