### ISSUE TITLE
Frame UI in Ubuntu 17 looks unusual

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#20581]
test in master branch

The application frame UI (not webpage rendering) looks very different in Ubuntu 17, and I am sure it is not all application UI would change in Ubuntu 17, since Firefox, Chrome's UI are as same as in Ubuntu 16.

*Ubuntu 17*
![default](https://user-images.githubusercontent.com/18013815/38453004-458746e2-3a81-11e8-9342-7c5427afcdd9.png)

*Ubuntu 16*
![default](https://user-images.githubusercontent.com/18013815/38453006-505d0566-3a81-11e8-856a-09964900769d.png)

*Other application in Ubuntu 17*
you can see the frame is very "Ubuntu"
![default](https://user-images.githubusercontent.com/18013815/38453163-cc3856b6-3a83-11e8-9d48-e755f3dc6908.png)

**Comment by atouchet** [comment]
I believe that is due to issues with Wayland support.

**Comment by tigercosmos** [comment]
What is Wayland? Are there issue related opened before?

**Comment by atouchet** [comment]
Wayland is a display server protocol alternative to X11. Ubuntu switched to use it by default in 17.10. There is an open issue for it here: #9558

**Comment by dralley** [comment]
Close in favor of the Wayland metabug?

**Comment by jdm** [comment]
Yep.
