### ISSUE TITLE
Audit the checks in WebGLRenderingContext.getFramebufferAttachmentParameter

### ISSUE THREAD

**Issue by nox** [servo/servo#20593]
I'm pretty sure we don't currently implement all the checks from the spec, notably:

* > `GL_INVALID_ENUM` is generated if the attached object at the named attachment point is `GL_RENDERBUFFER` and *pname* is not `GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE` or `GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME`.
* > `GL_INVALID_ENUM` is generated if the attached object at the named attachment point is `GL_TEXTURE` and *pname* is not `GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE`, `GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME`, `GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL`, or `GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE`.
* > `GL_INVALID_ENUM` is generated if there is no attached object at the named attachment point and pname is not `GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE`.

https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.6
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGetFramebufferAttachmentParameteriv.xml

**Comment by simartin** [comment]
I propose to work on that one.

**Comment by nox** [comment]
Sure!
