### ISSUE TITLE
DissimilarOriginWindows do not send messages with real pipeline ids to the constellation

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#20604]
DissimilarOriginWindows create a new `GlobalScope` with a phony `PipelineId`. Messages sent to the constellation from script are required to send a source `PipelineId`. Messages sent with the phony `PipelineId` will not be processed by the constellation because the `Pipeline` lookup will fail.

https://github.com/servo/servo/blob/bfb9fe6159ba61f0155a5ecc5a473b2a3edd6ef6/components/constellation/constellation.rs#L1019-L1024

Also the script to constellation channel is storing the wrong `PipelineId`:

https://github.com/servo/servo/blob/bfb9fe6159ba61f0155a5ecc5a473b2a3edd6ef6/components/script/dom/dissimilaroriginwindow.rs#L62

https://github.com/servo/servo/blob/bfb9fe6159ba61f0155a5ecc5a473b2a3edd6ef6/components/script_traits/lib.rs#L789-L803

cc @asajeffrey

**Comment by asajeffrey** [comment]
IRC chat: https://mozilla.logbot.info/servo/20180410#c14586192 (and for bonus points, go back and watch me flail around trying to debug this).

**Comment by asajeffrey** [comment]
One thing we could do is only put the pipeline id into messages that need it, and stop having ScriptToConstellationChan storing a pipeline id.
