### ISSUE TITLE
If Test_case have white background, the servo draw black color background.

### ISSUE THREAD

**Issue by hyunjunekim** [servo/servo#2064]
I wonder this issue,
draw black background!

My Environment, VirtualBox with ubuntu 13.10
Test Case, test_border.html

![error](https://cloud.githubusercontent.com/assets/5849168/2645123/283698c6-bf2f-11e3-9873-04e468286fd1.png)

**Comment by mbrubeck** [comment]
Looks like the fix re-landed in servo/rust-layers#116
