### ISSUE TITLE
Command line arguments list?

### ISSUE THREAD

**Issue by necros2k7** [servo/servo#20683]
subj

**Comment by CYBAI** [comment]
Do you mean how to launch a website?

If yes, after pulling servo down and building done, just use `./mach run <url>` to launch the website you'd like to see.

Ref: [Building section in README](https://github.com/servo/servo#building)

**Comment by KiChjang** [comment]
Closing as solved.

**Comment by necros2k7** [comment]
no arguments i suppose?
