### ISSUE TITLE
./mach clean-nightlies fails on servo-mac5

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#20694]
This happens at PR #20420 for no obvious reason. Any suggestions?

See:

* http://build.servo.org/builders/mac-rel-wpt3/builds/4246
* http://build.servo.org/builders/mac-dev-unit/builds/11755

**Comment by emilio** [comment]
Yeah, it's known, has happened in a bunch of other PRs. We're trying to address it ATM.

**Comment by nox** [comment]
Cc @larsbergstrom @edunham 

I'm currently landing https://github.com/servo/servo/pull/20693/commits/d52011ceb396cc48817d8f2d8e6dd7ffe90e0aa2 to just not use `clean-nightlies` right now.

I tried to remove `servo-mac5` from the build machines pool but couldn't do it from the Web interface.

**Comment by pyfisch** [comment]
Can I try to build #20420 again? Should I rebase the PR?

**Comment by nox** [comment]
I retried it, thanks for telling me about it, I didn't notice it was stuck because of this issue.

**Comment by nox** [comment]
If there are no conflicts you shouldn't need to rebase, FYI, because our CI stuff tries PRs with a merge of master.

**Comment by pyfisch** [comment]
Don't think this is relevant any more.
