### ISSUE TITLE
Remove usage of Unicode serialisation of origins

### ISSUE THREAD

**Issue by nox** [servo/servo#20701]
https://html.spec.whatwg.org/multipage/#ascii-serialisation-of-an-origin

> There used to also be a Unicode serialization of an origin. However, it was never widely adopted.

**Comment by tigercosmos** [comment]
What do you think we could fix this? I am confused about "it was never widely adopted". Does it mean this is not important at all?

**Comment by CYBAI** [comment]
@tigercosmos I guess, maybe, it means it's rarely for people to use unicode as domain?

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/master/components/url/origin.rs#L90 is our code that allows access to this. We should presumably remove it and fix any code that relies on it.
