### ISSUE TITLE
undefined reference to hb_font_funcs_set_nominal_glyph_func on Ubuntu 16.04

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#20712]
Building the servo crate linking with `cc` fails: undefined reference to 'hb_font_funcs_set_nominal_glyph_func'

`hb_font_funcs_set_nominal_glyph_func` is part of [harfbuzz since version 1.2.3](http://www.manpagez.com/html/harfbuzz/harfbuzz-/harfbuzz-hb-font.php#hb-font-funcs-set-nominal-glyph-func) but [Ubuntu Xenial only has version 1.0.1](https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=harfbuzz).

The function is used since a recent WebRender update in servo: https://github.com/servo/servo/commit/8bd2e91cdcce4b3664cd884d881ce673575aa151#diff-923eb7a14ede052885bae45c552c1a9bR30

**Comment by jdm** [comment]
You should be able to set HARFBUZZ_SYS_NO_PKG_CONFIG=1 when building and avoid the error.

**Comment by pyfisch** [comment]
I just updated to Ubuntu 18.04 in part due to this error and now it works. I can't really test this anymore.

**Comment by ford-prefect** [comment]
@jdm that did help, thank you!

**Comment by varentsov** [comment]
put this to readme please
