### ISSUE TITLE
Keydown event emits twice for printable char with one physical keypress

### ISSUE THREAD

**Issue by kwonoj** [servo/servo#20726]
i.e typing `a` produces below keyboard events:

![image](https://user-images.githubusercontent.com/1210596/39463241-a6b3d942-4ccb-11e8-9ea7-a15594332b6b.png)

while on chromium / ff emits single keydown event:

![image](https://user-images.githubusercontent.com/1210596/39462858-5bcd91a4-4cc9-11e8-9199-5f5bc4236da2.png)

![image](https://user-images.githubusercontent.com/1210596/39462860-6110f5f2-4cc9-11e8-922c-662ec9d240b7.png)

Behavior is related to https://github.com/servo/servo/issues/20630, currently each physical keypress creates two `WindowEvent::KeyEvent` for printable key, one without actual char and one subsequent with actual char. (`window::handle_received_character`). 

This makes fixes around some keyboard event makes quite complex including previous PR https://github.com/servo/servo/pull/20327. (or #20630) - for example it is not easily create keypress event against U+000D for enter instead of `\r` which appends actual carriage return char in input field, etcs.

Peeking logics roughly, looks like it may possible
- simply forward row winit kbdEvent without creating subsequent event for keychar
- `docuement` owns the responsibility to map keycode to actual keychar, manage keypress event after emitting single keydown event

But can't say for sure around historical decisions for current codebases. I'm interested to try some changes if this is sound / feasible considerations.

**Comment by kwonoj** [comment]
Related upstream issue: https://github.com/tomaka/winit/issues/34

**Comment by paulrouget** [comment]
It would help to have a "Glutin Key To Servo Key" module as described in https://github.com/servo/servo/issues/20331 - at least to isolate the translation mechanism and properly define what we want in Servo.

**Comment by kwonoj** [comment]
Interesting. I'll followup how does #20331 proceeds and trying to figure out what's needed more. What I thought in here was slightly opposite, let document owns responsibility to create domkey from raw keyboardinput event, but that was speculative guess without any actual experiment.

**Comment by paulrouget** [comment]
And like I said in #20727, having proper IME support would help solve these kind of issues.

**Comment by kwonoj** [comment]
I'm bit unsure handling IME would resolve this issue (at least on win32, based on rough experiences) but still having proper IME support definitely related with these kind issues in any way. I realized it may need upstream winit side support, trying to make upstream changes first.

**Comment by atouchet** [comment]
I tried retesting this with https://w3c.github.io/uievents/tools/key-event-viewer.html and now only get one keydown event.

![Screenshot](https://i.imgur.com/Hb2Dx3j.png)

Is this fixed now?

**Comment by jdm** [comment]
Looks like it!
