### ISSUE TITLE
Webrender capture doesn't work in macOS nightly builds by default

### ISSUE THREAD

**Issue by jdm** [servo/servo#20746]
Pressing ctr+shift+3 in master doesn't cause any new file to appear in the working directory.

**Comment by jdm** [comment]
Nevermind, this definitely works when I run it from a local build. I'll try using a nightly build.

**Comment by jdm** [comment]
When I run a nightly build on macOS and watch my terminal output, I receive `Unable to create path '"/Volumes/Servo/Servo.app/Contents/MacOS/capture_webrender/1525444435"' for capture: Os { code: 30, kind: Other, message: "Read-only file system" }` when performing a capture.

**Comment by kwonoj** [comment]
This looks like pkged nightly try to access path application path, not allowed to write. Any suggestions for preferred path? I'll try to update path lookup.

**Comment by jdm** [comment]
Perhaps fall back to the home dir if there's an error creating the path in the working directory?

**Comment by klausenbusk** [comment]
I'm not sure if this is related, but Ctrl+Shift+3 seems to be broken on Linux64. Nothing happens when I press it, no files or errors.

Tested just now with the latest nightly and ~ 10 days ago with the newest nightly at that time.

**Comment by kwonoj** [comment]
> Is there anyway else to trigger a capture?

With current build as-is, it might be somewhat hard. I noticed keep trying (keep pressing ctrl-shift-3) one time did work sometimes, but not reliably.
