### ISSUE TITLE
intermittent sigsegv in text_util unit tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#20756]
http://build.servo.org/builders/mac-dev-unit/builds/11840/steps/test/logs/stdio

I've run the binary under a debugger and it appears to be a rustc problem, since it crashes in standard library code before actually running any test code.

**Comment by jdm** [comment]
FYI @KiChjang

**Comment by jdm** [comment]
This is https://github.com/servo/servo/blob/master/components/gfx/tests/text_util.rs

**Comment by mbrubeck** [comment]
This has happened at least four times (in builds from both #20754 and #20615).  All the instances I've seen are from the same machine, [servo-mac2](http://build.servo.org/buildslaves/servo-mac2).  cc @edunham

**Comment by jdm** [comment]
I pulled the binary off of the machine and it continued to segfault. I'm not sure if that means anything.

**Comment by jdm** [comment]
This has now been observed on servo-mac4 as well.

**Comment by jdm** [comment]
One possibility to work around this and allow merges to continue would be removing servo-mac2 and servo-mac4 from the pool of builders for mac-dev-unit at https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/master.cfg#L178.

**Comment by jdm** [comment]
If the issue is nondeterministic codegen in rustc, we could try disabling codegen-units to see if it affects the output.

**Comment by jdm** [comment]
Observed on servo-mac7 as well (http://build.servo.org/builders/mac-dev-unit/builds/11897/steps/test/logs/stdio).

**Comment by jdm** [comment]
I can reproduce the exact same issue on servo-mac2 with the following testcase:
```rust
#[test]
fn foo() {}
```
and running `rustc --test foo.rs`. This appears with the 2018-05-14 nightly; it does not appear with the 2018-04-14 (our previous pinned rust version). I'm going to get a regression range and file a bug upstream; we should revert our last rustc update to allow our CI to make progress.

**Comment by jdm** [comment]
https://github.com/rust-lang/rust/issues/50867

**Comment by jdm** [comment]
Fixed by upstream rustc.
