### ISSUE TITLE
Move compositor and layout messages out of script_traits

### ISSUE THREAD

**Issue by gterzian** [servo/servo#20758]
This enum is, I think, only used by the compositor:

https://github.com/servo/servo/blob/dc17b32cebc956385084288765c9f5a78e60ee28/components/script_traits/lib.rs#L666

Why not move it to compositing? It would be more logical, remove potential circular dependencies, and maybe even save us a `#[derive(Deserialize, Serialize)]`!

Layout relevant message enums could also be moved to `layout_thread`(these still would require `#[derive(Deserialize, Serialize)]`):

https://github.com/servo/servo/blob/dc17b32cebc956385084288765c9f5a78e60ee28/components/script_traits/lib.rs#L111

and 

https://github.com/servo/servo/blob/dc17b32cebc956385084288765c9f5a78e60ee28/components/script_traits/script_msg.rs#L32

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/fc90e613d8851b663e3304d713b2ca08aa397bf4/components/webdriver_server/lib.rs#L39 and https://github.com/servo/servo/blob/9c5bdd932e4ce8720e25241cb1bbdd85be3c92a5/components/webvr/webvr_thread.rs#L11 are the two non-compositing, non-constellation, non-servo uses that I see for ConstellationMsg.

**Comment by kunalmohan** [comment]
I would like to work on this issue if it's not a problem.

**Comment by kunalmohan** [comment]
Moving `ConstellationMsg` to compositing is creating a cyclic dependency between compositing and webvr. Since compositing depends on webvr only for `VRServiceManager`, which is just re-exported in webvr. This can be removed by importing it directly from rust-webvr. Should I do so, or is there a better way to resolve it?

**Comment by jdm** [comment]
Removing the re-export sounds fine to me.

**Comment by kunalmohan** [comment]
Moving `LayoutControlMsg` to `layout_thread` creates cyclic dependencies of layout_thread with layout, layout_traits, metrics, script, script_layout_interface and script_traits. Most of these don't involve any re-export (like above). Is there any path that I should follow to resolve them, or anything I should keep mind?

**Comment by jdm** [comment]
Could you explain how the cyclic dependencies are created? What depends on LayoutControlMsg?

**Comment by jdm** [comment]
Oh, if script_traits depends on LayoutControlMsg, then moving it into layout_thread will definitely not work.

**Comment by jdm** [comment]
There's also the complication that layout_thread_2020 now exists, so moving the layout messages is not a reasonable proposition any more. They need to be shared between both layout thread crates.

**Comment by kunalmohan** [comment]
> Oh, if script_traits depends on LayoutControlMsg, then moving it into layout_thread will definitely not work.

Yes that's the case

**Comment by kunalmohan** [comment]
The same goes with `LayoutMsg` as well.

**Comment by kunalmohan** [comment]
I was able to move `ConstellationMsg`, so, should I leave it at that only?

**Comment by gterzian** [comment]
That could certainly be useful in and of itself.
