### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by atouchet** [servo/servo#20762]
In the latest nightly builds scrolling does not work properly, it is slow or unresponsive. This regression first occurred in the [2018-05-06](http://servo-builds.s3.amazonaws.com/) nightly build. Tested in Windows 10.

**Comment by mrobinson** [comment]
It seems like this may be a regression from the Gleam/WebRender update. I don't see the scrolling issues before that commit.

cc @nox

**Comment by nox** [comment]
The gleam update changes nothing functionally, so probably a WR issue.

**Comment by nox** [comment]
Cc @glennw

**Comment by mrobinson** [comment]
I'll try bisecting the list of changes in WebRender.

**Comment by mrobinson** [comment]
Looks like the culprit is https://github.com/servo/webrender/pull/2691.
