### ISSUE TITLE
Tracking issue for upgrading rustc Nightly

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#20844]
* Upgrading from `nightly-2018-04-15` to `nightly-2018-05-03` (#20703, reverted in #20820) has uncovered https://github.com/rust-lang/rust/issues/50867, whose root cause [might be in XCode](https://github.com/rust-lang/rust/issues/50867#issuecomment-390435849). @jdm, can we upgrade our CI to XCode 8?
* Upgrading further to `nightly-2018-05-17` or later is blocked on https://github.com/rust-lang/rust/issues/50825

**Comment by jdm** [comment]
@edunham will be better able to answer the question about what's required to upgrade XCode on our mac builders.

**Comment by SimonSapin** [comment]
It turns out that XCode 8 requires macOS 10.11, so we probably need to update some (not all!) of our CI builders.

**Comment by aneeshusa** [comment]
https://github.com/servo/saltfs/issues/811 is tracking upgrading our macOS builders to macOS 10.11.

**Comment by SimonSapin** [comment]
Updating macOS might not be blocking after all, per https://github.com/rust-lang/rust/issues/50867#issuecomment-393081919 we should be able to upgrade now.
