### ISSUE TITLE
Duplicate rendering when changing viewport coordinates

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#20847]
STR:

HTML:

```html
<style>
  body {
    background: red;
    height: 2000px;
  }
</style>
```

Change this in servo:

```diff
diff --git a/ports/servo/glutin_app/window.rs b/ports/servo/glutin_app/window.rs
index 436f7518ee..4c679c8095 100644
--- a/ports/servo/glutin_app/window.rs
+++ b/ports/servo/glutin_app/window.rs
@@ -700,7 +700,7 @@ impl WindowMethods for Window {
                 let (width, height) = window.get_inner_size().expect("Failed to get window inner size.");
                 let inner_size = (TypedSize2D::new(width as f32, height as f32) * dpr).to_u32();

-                let viewport = DeviceUintRect::new(TypedPoint2D::zero(), inner_size);
+                let viewport = DeviceUintRect::new(TypedPoint2D::new(50,50), TypedSize2D::new(300,300));

                 EmbedderCoordinates {
                     viewport: viewport,
```

Result:

<img width="1136" alt="screen shot 2018-05-22 at 15 16 41" src="https://user-images.githubusercontent.com/373579/40364644-29c2ea68-5dd3-11e8-81d1-4bad39e7caf3.png">

@glennw any idea why the content doesn't stay in the top square? When we add a document (via `add_document`), are we supposed to use the size of the framebuffer of the size of the document?

**Comment by gw3583** [comment]
I don't think you should have to change any layout coordinates. Any ideas @kvark ?

**Comment by paulrouget** [comment]
I believe I need to set the document dimension in `add_document`. It appears to work better. I'm confused to why this is necessary as `set_window_parameter` is supposed to used to send the same information.

**Comment by paulrouget** [comment]
> I believe I need to set the document dimension in add_document. It appears to work better.

Less content is rendered in the bottom part, but still, there's still a red square there.

**Comment by kvark** [comment]
Document scissoring appears to be broken right now (in our own "document" example). I'm looking into it.

**Comment by paulrouget** [comment]
@kvark Updating WR doesn't look trivial (few changes in the API). Are you planning an update soon?

**Comment by kvark** [comment]
Tomorrow, according to @gw3583 :clap:

**Comment by paulrouget** [comment]
This is fixed now. Thanks!
