### ISSUE TITLE
Update type of custom element constructor

### ISSUE THREAD

**Issue by jdm** [servo/servo#20875]
https://github.com/whatwg/html/pull/3703

**Comment by tigercosmos** [comment]
I would like to try. I thought just modify the code is in `components/script/dom/customelementregistry.rs`.
```
pub constructor: Rc<Function>,
```
to 
```
pub constructor: Rc<Any>,
```

Do we have `Any` type?

**Comment by jdm** [comment]
We should store a `Rc<CustomElementConstructor>`, which is the name of the generated callback type.

**Comment by jdm** [comment]
Right. So it should be possible to import `dom::bindings::codegen::Bindings::CustomElementRegistryBinding::CustomElementConstructor` to use it the same way we use `Function`, as far as I know.
