### ISSUE TITLE
Potentially insecure sharing of event loops between differing schemes

### ISSUE THREAD

**Issue by gterzian** [servo/servo#20887]
In the context of [#same-origin-domain](https://html.spec.whatwg.org/multipage/origin.html#same-origin-domain) and how this relate to the browsing context forming a [#unit-of-related-similar-origin-browsing-contexts](https://html.spec.whatwg.org/multipage/browsers.html#unit-of-related-similar-origin-browsing-contexts) and being able to share an event loop:

I think our current implementation of [`Constellation.event_loops`](https://github.com/servo/servo/blob/b0dd1c839ab4bb8ff8114386d3432b1d5f6a5e0f/components/constellation/constellation.rs#L278) might be potentially insecure.

The spec mentions `[a browsing context that] has an active document with an origin that, through appropriate manipulation of the document.domain attribute, could be made to be same origin-domain with other members of the group[of directly reachable browsing contexts]`.

I'm reading this as basically implying that not only the host should be equal, but also the scheme. 

So perhaps the current `HashMap<Host, Weak<EventLoop>>` should use a new kind of key and look more like `HashMap<SchemeHost, Weak<EventLoop>>` where `SchemeHost` would be a new struct looking something like:
```rust
struct SchemeHost {
    scheme: str
    host: str
}
```

This is perhaps something that only comes into play with auxiliary browsing contexts, and I'm probably going to end up addressing this as part of https://github.com/servo/servo/pull/20678, yet I thought it was worthwhile discussing it separately...

**Comment by jdm** [comment]
@asajeffrey You probably have thoughts on this.

**Comment by asajeffrey** [comment]
Yes, there is possibly more sharing than necessary here, if we want to isolate http://example.com/ from https://example.com/. This makes a difference once we're using process isolation to protect against Spectre. There's a question about whether the security gain of protecting https from http is worth the overhead. I was planning on thinking about this when we're doing process isolation.

**Comment by gterzian** [comment]
Ok, thanks for the info, I will not try to change this for now...
