### ISSUE TITLE
dependencies required for mozjs

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#20888]
since recent commits, the build will fail with C++ errors. Either in Win10, or Ubuntu 16.04, as far as I know.

I add `apt install clang` and fix the Ubuntu. But I don't know how to fix Windows.

**Comment by kwonoj** [comment]
This seems related to `mozjs` now requires clang. For windows, easiest way is install llvm as instructed in mozjs (https://github.com/servo/mozjs/#building)

**Comment by kwonoj** [comment]
actually it isn't 100% true, I got some other failures in mozjs still. need dig bit more.

**Comment by tigercosmos** [comment]
d0cc9d2cd56a197fdfb72d8c0168d4cf2bb23bdb did add lib in script. I don't know why it doesn't work.

**Comment by kwonoj** [comment]
@tigercosmos actually that reveals reason why for me on windows, https://github.com/servo/servo/commit/d0cc9d2cd56a197fdfb72d8c0168d4cf2bb23bdb#diff-e6bf833f91496efdbd7e4e9ecfc7a4cdR7 points deps to llvm 4 while mozjs requires 6. I tried manually handcraft script to point local installation to llvm 6, and was able to get build working. 

Guess resolution'll be update deps to 6, while `servo-deps.s3.amazonaws.com/msvc-deps` doesn't have it updated yet?

**Comment by tigercosmos** [comment]
@kwonoj sounds reasonable. What do you think @asajeffrey?

**Comment by tigercosmos** [comment]
@jdm  Could we put the file `https://servo-deps.s3.amazonaws.com/msvc-deps/llvm-6.0.0.zip` to cloud?

**Comment by asajeffrey** [comment]
Hmm, mozjs requires llvm 6? I thought it only needed llvm 4.

We could upload llvm6 to aws, but I'm a bit concerned this might break anything that depends on old versions of clang (I seem to remember osmesa being picky?)

**Comment by tigercosmos** [comment]
@asajeffrey  could let both llvm 4 and llvm 6 on the cloud. Servo read the version in `package.py`. We could test it first.

**Comment by asajeffrey** [comment]
Could do but I'm a bit surprised llvm 6 is needed, llvm 4 works for me on my local machine, and also on the build machines.

**Comment by kwonoj** [comment]
may be related to msvc version? this is message I got on local machines for reference.


```
cargo:rustc-link-search=native=C:\github\servo\target\debug\build\mozjs_sys-e622a19cc3f27e25\out
TARGET = Some("x86_64-pc-windows-msvc")
Generting bindings ["./src/jsglue.hpp", "--rust-target", "1.19", "--rustified-enum", ".*", "--no-derive-default", "--enable-cxx-namespaces", "--generate", "function,types,vars", "--ignore-methods", "--", "-I", "C:\\github\\servo\\target\\debug\\build\\mozjs_sys-e622a19cc3f27e25\\out\\dist/include", "-x", "c++", "-fms-compatibility", "-DRUST_BINDGEN", "-DSTATIC_JS_API", "-std=c++14", "-DWIN32"].

--- stderr
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\yvals.h:297:5: error: STL1000: Unexpected compiler version, expected Clang 6 or newer.
```

**Comment by kwonoj** [comment]
Created one-liner change https://github.com/servo/servo/pull/20895 to bump.

**Comment by asajeffrey** [comment]
OK, lets see if that works on CI.

**Comment by tigercosmos** [comment]
Sorry. My fault.
