### ISSUE TITLE
https://medium.com cannot scroll down

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#20898]
I don't know why servo cannot scroll down the page at https://medium.com/

with the latest commit `./mach run -d https://medium.com/`

**Comment by CYBAI** [comment]
I also cannot scroll in [this GitLab Wiki page](https://gitlab.haskell.org/ghc/ghc/wikis/explicit-type-application). Not sure if we can have a meta-issue for this issue 🤔?

**Comment by dralley** [comment]
I **can** scroll on medium.com, I **cannot** scroll on the gitlab wiki page.  Should this issue be repurposed or just file a new one?

```
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread WRRenderBackend#0, at /home/dalley/.cargo/git/checkouts/webrender-c3596abe1cf4f320/4ba17a6/webrender/src/render_backend.rs:1597)
```

**Comment by jdm** [comment]
Let's file a new issue for the gitlab wiki that panics.
