### ISSUE TITLE
ThreeJS reports that OES_element_index_uint is not supported

### ISSUE THREAD

**Issue by jdm** [servo/servo#20921]
Any aframe scene that I load on master outputs "THREE.WebGLRenderer: OES_element_index_uint extension not supported."

**Comment by KiChjang** [comment]
Relevant spec: https://www.khronos.org/registry/webgl/extensions/OES_element_index_uint/

**Comment by KiChjang** [comment]
Sounds like this is just a matter of being able to accept `gl.UNSIGNED_INT` as the third argument to `WebGLRenderingContext.drawElements()`.

**Comment by jdm** [comment]
In theory we're supposed to support this already due to #20397.

**Comment by nox** [comment]
```html
<script>
var canvas = document.createElement("canvas");
var gl = canvas.getContext("webgl");
document.write(gl.getExtension("OES_element_index_uint"));
</script>
```

**Comment by nox** [comment]
https://github.com/WebKit/webkit/blob/3f0a3a103730b9a7fef0570ce7f68a4a93d30a78/Source/WebCore/platform/graphics/opengl/Extensions3DOpenGL.cpp#L209-L211
