### ISSUE TITLE
three.js geometry extrude splines example has JS errors

### ISSUE THREAD

**Issue by jdm** [servo/servo#20932]
https://threejs.org/examples/webgl_geometry_extrude_splines.html
```
THREE.Object3D.add: object not an instance of THREE.Object3D.
[object Window]
ERROR 2018-06-06T00:05:44Z: script::dom::bindings::error: Error at https://threejs.org/examples/webgl_geometry_extrude_splines.html:189:4 parent.add is not a function
```

**Comment by jonathanKingston** [comment]
A minimal test case is the following:
```
<!DOCTYPE html>
<html lang="en">
  <body>
    <script>
      var parent;
      var parent2;
      function init () {
        parent = 1;
        parent2 = 1;
        console.log(parent === window);
        console.log(parent2 === window);
      }
      init();
    </script>
</body></html>
```
In other browser both console logs are `false`.

I added the following PR which fixes the above case: 

I'm not sure where the best place for this test? Should it be added upstream to wpt tests? (I don't know how/if Servo handles that like Gecko does)

**Comment by jonathanKingston** [comment]
It's also worth noting this doesn't fix the demo either, something else is broken further down.
