### ISSUE TITLE
URLSearchParams returns null on Get for value that is present

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21016]
Used in https://github.com/servo/servo/blob/07ba57b864c00c820c601e420032d1ed682b6af2/tests/wpt/web-platform-tests/html/browsers/browsing-the-web/history-traversal/persisted-user-state-restoration/resources/post_name_on_load.html#L5

where `window.location.search` is `?name=foo`, but `params.get('name')` return `null`.

which currently makes the below test time out. 

https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/html/browsers/browsing-the-web/history-traversal/persisted-user-state-restoration/resume-timer-on-history-back.html

code: https://github.com/servo/servo/blob/07ba57b864c00c820c601e420032d1ed682b6af2/components/script/dom/urlsearchparams.rs#L88

spec: https://url.spec.whatwg.org/#dom-urlsearchparams-get

**Comment by sagudev** [comment]
I hit this to multiple times, will fix it.

**Comment by sagudev** [comment]
Actually it works properly in latest servo version, weird.
