### ISSUE TITLE
Implement BroadcastChannel

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21025]
test: https://github.com/servo/servo/tree/527d874bc107039156d40d25b2a76f4a28eb639e/tests/wpt/web-platform-tests/webmessaging/broadcastchannel

(and a few others using it, like tests/wpt/metadata/html/browsers/the-window-object/window-open-noopener.html)

Spec: https://html.spec.whatwg.org/multipage/#dom-broadcastchannel

Not implemented yet?

**Comment by jdm** [comment]
Correct.

**Comment by KiChjang** [comment]
I _could_ implement this in #16622, but that PR is big enough to make it a bit difficult to review already...

**Comment by gterzian** [comment]
Spec: https://html.spec.whatwg.org/multipage/#dom-broadcastchannel

**Comment by gterzian** [comment]
An idea on how to do this, based on the (still ongoing) experience of https://github.com/servo/servo/pull/23637

1. Introduce a `BroadCastChannelId`, based on a `PipelineNameSpace`. 
2. When you create a `BroadCastChannel`, store it on the `GlobalScope` in a `VecDeque<Dom<BroadCastChannel>>`. It needs to be a `Dom` because you want to keep a strong reference to it. 
3. Create an `ipc` channel, send the sender to the constellation along with the current origin of the settings/document object. The constellation stores the senders along with the id in something like a `HashMap<Origin, VecDeque<BroadCastChannelInfo>>` (Origin could be a String). 
4. Use the receiver to setup a route to receive messages from the constellation. 
5. To "broadcast" a message, send a message to the constellation from the globalscope, containing the structured-cloned message along with the Id and the origin. 
6. When the constellation receives that broadcast message, it simply iterates over the vecdequeue for that origin(excluding the source Id), and uses the stored sender to broadcast a clone of the message. 
7. The `close` method can simply remove the  `Dom<BroadCastChannel>` from the globalscope, and send a message to the constellation telling it to remove the corresponding `BroadCastChannelInfo`.

It's a good one to implement, if only because there are lots of wpt tests using it to test other things, so we would gain quite a bit of test coverage from it.

**Comment by pshaughn** [comment]
In addition to tests for the feature itself, some WPT tests expect this to be available as a tool to manage communication between browsing contexts in otherwise unrelated tests, like html/semantics/forms/form-submission-target/rel-button-target.html

**Comment by gterzian** [comment]
Ok I would like to do this one, unless someone else wants to do it and then I can review. As mentioned by @pshaughn, I think it's pretty imporant re the testsuite.
