### ISSUE TITLE
Update to syn 0.14

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#21059]
As of https://github.com/servo/servo/pull/21058, the dependency graph contains two versions of each of `syn`, `quote`, and `proc-macro2`.

* [x] https://github.com/servo/webrender/pull/2819
* [x] https://github.com/servo/html5ever/pull/345
* [x] https://github.com/servo/rust-cssparser/pull/223
* [x] FIXME: others

CC @Eijebong

**Comment by Eijebong** [comment]
Hey, the only remaining problem I can think of is updating bindgen to quote 0.6 because of doc comments. We can't generate stuff like `/// Foo bar`, it has to be `#[doc=" Foo bar"]`. I'm pretty sure I opened everything else.

 CC @emilio

**Comment by Eijebong** [comment]
Also https://github.com/servo/string-cache/pull/207

**Comment by Eijebong** [comment]
And https://github.com/rust-lang-nursery/rust-bindgen/pull/1334

**Comment by dtolnay** [comment]
https://github.com/rust-lang-nursery/rustfmt/issues/2883 would be the place to fix normalizing doc comments to `///`.

**Comment by atouchet** [comment]
syn was updated to 0.15 in #22085.
