### ISSUE TITLE
Zooming in on Android causes fonts to overlap

### ISSUE THREAD

**Issue by NiLSPACE** [servo/servo#21100]
After scrolling down the issue still persists. 
<br />

Here is a screenshot:
<details>
<summary>Screenshot</summary>

![thumbnail_screenshot_20180629-082939](https://user-images.githubusercontent.com/1160867/42077568-a6fbfcf4-7b79-11e8-9f7b-87083503644b.png)
</details>

<br />
<br />

Also, here is a bad quality GIF showing the issue:
<details>
<summary>GIF</summary>

![ezgif-2-089cd194ee](https://user-images.githubusercontent.com/1160867/42078060-61afd146-7b7b-11e8-861a-95d74f2f83db.gif)
</details>

Phone: Huawei P10 Lite.

**Comment by paulrouget** [comment]
Looks like it's working now.
