### ISSUE TITLE
Building Servo on Ubunty14 (mozjs issue)

### ISSUE THREAD

**Issue by ljgww** [servo/servo#21101]
Building servo takes time but it is mostly fine. In spite that I did not manage to make it, the fact is - code is large, so it is not unexpected to fail. I have tried to build large stuff before and run into various problems with various results (sometimes successful sometimes not). This one was almost success.

This is first time I am trying to compile something based on Rust that is large, and I am finding it somewhat better than similar size written in C/C++  (okay here are some of that c/c++ soup included).

I have cloned (at the time of writing) last servo repo from github according to instructions given on servo.org (master branch). Expecting this would be most stable to build.

Prerequisites (libs and tools) went a bit away but nothing that could not been fixed by reading troubleshooting (having a log of that too). 

However even that github claims this code builds, it did not build for me.

There are 2 problems.  Will elaborate 1st problem in another issue. Sufficient to say I had do redo:

     ./mach build --dev

number of times until this issue remained the only issue. In essence mozjs do not build and culprit seems to be some option in build script (is it that or not, I am not that competent to tell)

Last compiling log is here:  see: https://gist.github.com/ljgww/d1dac95eb1087fc779c4fbb96e2828cd#file-build_servo_ubunty14_mozjs-txt

Perhaps I can tweak script somewhere if I knew where somewhere is :)

**Comment by asajeffrey** [comment]
I'm glad you're trying out servo, sorry you're having build problems.

What version of Clang do you have? You may need to install a recent one, then set `LIBCLANG_PATH`, e.g. to `/usr/lib/llvm-6.0/lib`.

**Comment by ljgww** [comment]
looks like I have:

    llvm-3.4/ 
    llvm-3.6/

will try to go to 6.x

**Comment by ljgww** [comment]
Arrived to 3.9 (llvm-3.9)
cant go further ... (certainly not to 6.0)

**Comment by asajeffrey** [comment]
3.9 should be fine.

**Comment by ljgww** [comment]
Actually there is CLang 6.0.1 but I would need to build it. (having previous experience with Ubuntu I will try but not sure I would make it, usually if update did not come from Ubuntu, compiling from source for something new usually breaks something in Ubuntu itself.

**Comment by ljgww** [comment]
Judging from this (compiling) output:

          PYTHON="python2" MOZ_TOOLS="" \
	  CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
	  /home/lj/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.51.2/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --build-backends=RecursiveMake --enable-sm-promise --disable-shared-js || (cat config.log && exit 1) ; 

does not look to me that clang is used. I would understand this line to be trying to make libs with gcc

**Comment by asajeffrey** [comment]
Building the mozjs_sys crate uses bindgen, which uses clang.

**Comment by ljgww** [comment]
Understood. Thank you. This explains cryptic answer in another issue/thread.

**Comment by ljgww** [comment]
I have managed to download clang/llvm6 binaries (http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz) and the compiler looks like working. 

    ~/dev/rust/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04$ ./bin/clang --version
    clang version 6.0.0 (tags/RELEASE_600/final)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /home/lj/dev/rust/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/./bin

Now, this is not Ubuntu package, so I do not know how to make it to be default clang compiler (there is no installer). I am not that familiar with clang at all.

Is there some method I can explain to `mach` where to look for clang so that it goes around default clang installation and use custom binaries? (default is currently clang/llvm 3.9 on my Ubuntu)

    ~/dev/rust/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04$ clang --version
    clang version 3.9.1-4ubuntu3~14.04.3 (tags/RELEASE_391/rc2)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin

As mentioned in another thread, compiling servo with clang 3.9 does not change the outcome: compilation still fails at the same point.

Also, I did not find `./mach clean` variant - is there a way to clear what has been built so far and re-start compilation process from scratch? (of course I can always delete everything and re-download master branch)

**Comment by asajeffrey** [comment]
You can specify where to find the clang library by setting LIBCLANG_PATH to be the directory containing the clang library, e.g. for me it's
```
LIBCLANG_PATH=/usr/lib/llvm-4.0/lib ./mach  build -d
```
I'm a bit surprised compilation fails with clang 3.9, can you point me to a log?

**Comment by ljgww** [comment]
I have updated Python in the meantime and it (python) is currently unstable. 
This reflects on building servo (AFAIK)
As soon as I manage to make my Python stable I will retry compiling servo.

**Comment by ljgww** [comment]
Revisiting subject. Report on findings:

1. noticed servo has pre-compiled binaries at https://download.servo.org/ - downloaded Linux 64 bit.

verdict:
    $ ./servo 
    ./servo: error while loading shared libraries: libgstwebrtc-1.0.so.0: cannot open shared object file: No such file or directory

investigation shows missing library is available for fedora but nowhere to be found for deb.

OKay 

2. readme says that I can attempt to build it. Re-download latest master.

Experience. Mach was accepting only clang-3.4 if I tried with something more recent, wont start building tried a few. So clang-3.4 installed.

Building takes a long time and fails but seem not on rust code.

env:

    [03/24/00:51:57] $ rustc --version
    rustc 1.33.0 (2aa4c46cf 2019-02-28)
    [03/24/00:51:57] $ clang --version
    Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
    Target: x86_64-pc-linux-gnu
    Thread model: posix
    [03/24/00:51:57] $ gcc --version
    gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    $ g++ --version
    g++ (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

further

    $ ./mach bootstrap
    Dependencies were already installed!    

build (large build log here: https://gist.github.com/ljgww/a8533206fff8a6391635038e22e11f14#file-servo-build-errors-24-3-19-ubuntu-14-txt )

**Comment by julienJean99** [comment]
have you found a solution I am having the same issue. I tried to build it from source but had no luck their either.

**Comment by dralley** [comment]
It should be noted that unless you're paying money to Canonical for extended support, Ubuntu 14.04 is no longer supported: https://www.omgubuntu.co.uk/2019/04/ubuntu-14-04-end-of-life
