### ISSUE TITLE
TaskSource-specific TaskCanceller

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21119]
In order to support stuff like https://github.com/servo/servo/issues/21114, we need the ability to cancel tasks in a more granular way, at the level of 'per tasksource'. 

Currently 'cancelling' tasks is basically dependent on the [ignore_further_async_events](https://github.com/servo/servo/blob/1f9b07637ea960f6b3d4004f832951ad9b6b48ed/components/script/dom/window.rs#L251) field on `Window`, which is the basis for the `TaskCanceller` returned via [task_canceller](https://github.com/servo/servo/blob/1f9b07637ea960f6b3d4004f832951ad9b6b48ed/components/script/dom/window.rs#L1068), which is accessed via the [queue](https://github.com/servo/servo/blob/master/components/script/task_source/mod.rs#L29) method of the [TaskSource](https://github.com/servo/servo/blob/master/components/script/task_source/mod.rs#L16) trait(via the globalscope passed to that function). 

One idea I can come up with is adding a new method to `TaskSource`, something like
`fn choose_canceller<T>(&self, global: &GlobalScope) -> TaskCanceller`, and then change `queue` to read something like the below:
```
let canceller = self.choose_canceller(&global);
self.queue_with_canceller(task, canceller);
```

Then each task source will need to implement `choose_canceller`, calling the appropriate method of `GlobalScope`, which would forward the call to the window, and the window would require a flag similar to [ignore_further_async_events](https://github.com/servo/servo/blob/1f9b07637ea960f6b3d4004f832951ad9b6b48ed/components/script/dom/window.rs#L251) for each task source...

Any better ideas?

**Comment by gterzian** [comment]
And perhaps an 'easy' way to make the switch is with a default implementation that just calls `task_canceller`, and only overriding it for task source that would nee

**Comment by jdm** [comment]
That implementation makes sense to me!
