### ISSUE TITLE
New 'android-x86' CI job on (a) new server(s) at packet.net

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#21124]
Currently the `android` job specified in `etc/ci/buildbot_steps.yml` runs on `servo-linux-cross*` builders which are virtual machine on AWS EC2. Per https://github.com/servo/servo/issues/21116, we need an a non-virtual CPU so that the Android emulator can use KVM with Inter VT-x. https://www.packet.net/bare-metal/servers/ seems to be a good candidate, it is also being considered for GeckoView testing.

The `t1.small.x86`  seems small: we’ve had issues in the past with `servo-linux-cross*` having only 8 GB of RAM. `c1.small.x86` (second cheapest) looks good, the higher clock frequency will help with compilation speed. Maybe one server is enough for now?

@larsbergstrom, can you help with creating a Packet.net account and setting up billing?

@edunham, can you help with setting up a new server with Ubuntu 18.04 such that it can be configured like others with Salt? (Ubuntu 14.04 that we use on other servers is EOL next year, so we might as well already start with the latest LTS for this new server.)

Starting with an empty Salt config is fine. I’ll then fill it in with the dependencies for this new test suite (which are reduced compared to the existing `android` job because https://github.com/servo/servo/pull/21094 moved some of the bootstrapping in-tree), fix things up until the test suite can complete successfully, and then we can add all this to Buildbot.

**Comment by SimonSapin** [comment]
> help with setting up a new server with Ubuntu 18.04 such that it can be configured like others with Salt?

I may be able to manage this based on https://github.com/servo/saltfs/blob/master/docs/salt.md#setting-up-a-new-salt-minion, I’ll try and report back once billing is set up.

**Comment by larsbergstrom** [comment]
Packet.net account is created; credentials in 1password.

**Comment by SimonSapin** [comment]
`servo-linux-kvm1.servo.org` is deployed. The `install_salt.sh` script fails because "https://repo.saltstack.com/apt/ubuntu/18.04/amd64/archive/2016.3.3/SALTSTACK-GPG-KEY.pub is 404. It does exist with e.g. 16.04 instead of 18.04, or 2017.7.7 instead of 2016.3.3.

Is the Salt minion compatible with a master of a different version?

**Comment by SimonSapin** [comment]
https://docs.saltstack.com/en/latest/faq.html#can-i-run-different-versions-of-salt-on-my-master-and-minion
> When upgrading Salt, the master(s) should always be upgraded first. Backwards compatibility for minions running newer versions of salt than their masters is not guaranteed.

**Comment by SimonSapin** [comment]
Downgraded to 16.04 and submitted https://github.com/servo/saltfs/pull/850
