### ISSUE TITLE
Support preserveDrawingBuffer's WebGL context option

### ISSUE THREAD

**Issue by nox** [servo/servo#21132]
Some failures are due to it being missing.

* `/_mozilla/webgl/conformance-1.0.3/conformance/attribs/gl-vertex-attrib-render.html`
* `/_mozilla/webgl/conformance-1.0.3/conformance/buffers/buffer-data-array-buffer-delete.html`
* `/_mozilla/webgl/conformance-1.0.3/conformance/context/premultiplyalpha-test.html`

**Comment by nox** [comment]
*So* many tests are blocked on this.

**Comment by nox** [comment]
So @jdm, do we know for sure whether we actually preserve the drawing buffer or not in the current code?

**Comment by jdm** [comment]
I have some links that concusively demonstrate that we do.

**Comment by nox** [comment]
I think it would be a better compromise to at least change the code to act
as if preserved faxing buffer was always true.

Le mar. 9 oct. 2018 à 14:38, Josh Matthews <notifications@github.com> a
écrit :

**Comment by paulrouget** [comment]
I'm trying to get the babylonjs webxr demos to work, and I keep running into that issue. Example: https://gist.github.com/paulrouget/dce92c742fa8a43924304314ebd732bb

**Comment by paulrouget** [comment]
```
RUST: WARN - canvas::webgl_thread - Couldn't create shared GL context (preserveDrawingBuffer is not supported yet), using slow readback context instead.
RUST: ERROR - script::dom::webglrenderingcontext - Couldn't create WebGLRenderingContext: preserveDrawingBuffer is not supported yet
RUST: ERROR - script::dom::bindings::error - Error at https://preview.babylonjs.com/babylon.js:16:70936 WebGL not supported
```

**Comment by atouchet** [comment]
I tried marking this as done in the WebGL metabug but it appears I no longer have issue editing access. Was there a permissions change or is this an issue on my end?

**Comment by jdm** [comment]
Github introduced a new permissions level called Triage and made the Write and Maintain levels have access to push directly to the master branch. We downgraded most of the people with access to the servo organization repositories to the Triage level, but that apparently no longer includes write access to issues :<

**Comment by atouchet** [comment]
Ah, alright. It looks like it also limits project editing as well (although strangely not projects of the org itself).
