### ISSUE TITLE
Outline drawing behavior for boxes with negative sizes

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#21138]
Refer to https://github.com/w3c/csswg-drafts/issues/2892

Here's the Servo (built with bd0c001218) screenshot

#### First Case

<img width="1021" alt="default" src="https://user-images.githubusercontent.com/6782666/42417148-b1ea2946-82b4-11e8-9020-70e09538df9b.png">

HTML:
<details>

```html
<html>
  <head>
    <style>
html {
  display: table;
  height: 100%;
  width: 100%;
}

body {
  display: table-cell;
  vertical-align: middle;
}

div {
  margin: auto;
  width: 100px;
  height: 100px;
  outline: inset 100px green;
  outline-offset: -125px;
}
   </style>
  </head>
  <body>
    <div></div>
  </body>
</html>
```

</details>

#### Second Case

<img width="1014" alt="default" src="https://user-images.githubusercontent.com/6782666/42417177-7c2ea092-82b5-11e8-8aea-fc160111e9ff.png">

<details>

```html
<html>
  <head>
    <style>
html {
  display: table;
  height: 100%;
  width: 25px;
  margin: auto;
}

body {
  display: table-cell;
  vertical-align: middle;
}

div::before {
	line-height: 25px;
	font-size: 25px;
	content: "　　";
	background: white;
}
div {
	display: inline;
	outline: 25px ridge white;
	outline-offset: -40px;
	border: 25px dotted #ABABAB;
}
    </style>
  </head>
  <body>
    <div></div>
  </body>
</html>
```

</details>

**Comment by mrobinson** [comment]
This seems to be working now, even though position is wrong in legacy layout.
