### ISSUE TITLE
Update to a recent version of Gradle and to SDK 27

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21147]
I'm working on #21127 but it's getting frustrating to keep the compatibility with gradle 2 when most of the documentation found online is about the version 3 and the latest Android Studio keeps bugging with the version 2.

I have experimented a bit, and I only found an issue with the way we name and move the apk (the renaming won't work with Gradle 3). But beside, it looks possible.

@MortimerGoro do you have any concerns about migrating?

**Comment by paulrouget** [comment]
Note to self:

- we should use Java 1.8 and not use Jack
- we should use a copy task and not rename the target
- we should move back to lambdas

**Comment by paulrouget** [comment]
One of the reason I'd like to update is: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration#variant_aware

**Comment by MortimerGoro** [comment]
I agree, we should upgrade to gradle 3 and remove Jack. Also update to latest target SDK 27

**Comment by paulrouget** [comment]
> Also update to latest target SDK 27

What would it take to get that to work?

I've naively changed the version in the gradle files and it compiles.

Haven't tried to compile with VR enabled.

**Comment by MortimerGoro** [comment]
> What would it take to get that to work?

I don't expect any problem related to running Servo, just update compileSdkVersion/targetSdkVersion to 27 in the gradle build file, install the latest system SDKS and build tools and it should work.

But IIRC something changed with a version of SDK build tools that may affect Servo cloud compilation scripts
