### ISSUE TITLE
Nightly benchmark upload job consistently fails

### ISSUE THREAD

**Issue by jdm** [servo/servo#21153]
Every single job recently has failed with:
```
aws s3 sync --size-only --acl public-read ./etc/ci/performance/output s3://servo-perf
 in dir /home/servo/buildbot/slave/linux-nightly/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['aws', 's3', 'sync', '--size-only', '--acl', 'public-read', './etc/ci/performance/output', 's3://servo-perf']
 using PTY: False
Unknown options: --size-only
program finished with exit code 255
elapsedTime=0.308587
```

cc @asajeffrey

**Comment by asajeffrey** [comment]
Oh grr, have we changed which version of awscli we have installed on the build machines?

**Comment by jdm** [comment]
This probably happened when I recreated all of the build machines, which would have installed whichever version of awscli was present at that time.

**Comment by asajeffrey** [comment]
On IRC https://mozilla.logbot.info/servo/20180710#c14997995 looks like the culprit is https://github.com/servo/saltfs/commit/a7c70cfa8d378fa2e3f3e3193ac22aef317a85c8
