### ISSUE TITLE
Create a standalone library for Text to Glyphs

### ISSUE THREAD

**Issue by fasihrana** [servo/servo#21157]
Is it possible to separate out the Glyphs portion of Servo into a spatial text library?

It should probably also have a convenience function that "places" Au sized font text within a Bounded Rectangle.

I've been experimenting with webrender and I'm finding that fonts and rendering text is being a massive pain.

**Comment by SimonSapin** [comment]
CC @pcwalton and @mbrubeck for https://github.com/pcwalton/font-kit and https://github.com/pcwalton/pilcrow, which are intended to eventually replace Servo’s current code.

**Comment by fasihrana** [comment]
Okay, but is there a way to convert text to Glyphs easily in the current implementation?

**Comment by SimonSapin** [comment]
Well you can have a look at https://doc.servo.org/gfx/index.html but I don’t know how easy it would be to use outside of Servo, since it was not designed for that. (But if I have to guess I’d say probably not easy.)

**Comment by dralley** [comment]
I see font-kit is being used now, is this issue still applicable?

**Comment by jdm** [comment]
I believe https://github.com/linebender/skribo/ is the intended outcome here. In any case, we're unlikely to spend time trying to extract the relevant code from Servo at this point.
