### ISSUE TITLE
Unify Window task sources and task cancellers API

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21154]
https://github.com/servo/servo/pull/21126#discussion_r201187073

> we should do something to avoid all of the duplication of calling foo_task_source and then getting a canceller where it's easy to end up with one for a different source. Possibly the foo_task_source APIs could return both a source and a canceller at the same time.

Note there are two current use-cases:

1. A script-thread task is enqueued 'directly from the main script-thread/event-loop', like in https://github.com/servo/servo/blob/a9022be0c3e30249845ca5947ac0c0a6743c7991/components/script/dom/htmldetailselement.rs#L72 where [TaskSource.queue](https://github.com/servo/servo/blob/a9022be0c3e30249845ca5947ac0c0a6743c7991/components/script/task_source/mod.rs#L25) is called, and the task source itself is responsible for 'selecting' the right task canceller for the queued task.
2. A script-thread task is enqueued 'from code running [in parallel](https://html.spec.whatwg.org/multipage/#in-parallel)', like in https://github.com/servo/servo/blob/2bc70e738b01051a64f2183691e0abd9a0f84072/components/script/dom/filereader.rs#L491 where [queue_with_canceller](https://github.com/servo/servo/blob/a9022be0c3e30249845ca5947ac0c0a6743c7991/components/script/task_source/mod.rs#L17) is called directly from the parallel steps of the algorithm.

**Comment by gterzian** [comment]
@AgustinCB This one could be of interest to you as well, given your prior work with task-sources(or perhaps you'd rather do other things actually :) )

It's not completely clear what such "unified API" should look like, so this will require some initial exploration with the code...

**Comment by AgustinCB** [comment]
Awesome! Will give it a try. Thanks for letting me know!

**Comment by AgustinCB** [comment]
I'll have a PR for this tomorrow, hopefully.
