### ISSUE TITLE
Some reftests load an unexpected font intermittently

### ISSUE THREAD

**Issue by jdm** [servo/servo#21163]
From http://build.servo.org/builders/mac-rel-wpt4/builds/4666:
<img width="929" alt="screen shot 2018-07-11 at 4 26 50 pm" src="https://user-images.githubusercontent.com/27658/42597591-41c9f644-8527-11e8-8d9e-b611276a1a9a.png">
<img width="923" alt="screen shot 2018-07-11 at 4 26 58 pm" src="https://user-images.githubusercontent.com/27658/42597592-41d62a04-8527-11e8-9a90-f8da304de54d.png">

**Comment by mrobinson** [comment]
I'm going to close this one since we aren't running WPT on Mac any longer and we have made improvements for font matching on that platform in the meantime.
