### ISSUE TITLE
read_blob returns a reflector to an unrooted DOM object

### ISSUE THREAD

**Issue by jdm** [servo/servo#21164]
[This code](https://github.com/servo/servo/blob/master/components/script/dom/bindings/structuredclone.rs#L106) creates a Blob, which is rooted in the current stack frame, then returns its reflector's JSObject pointer. This means that the blob object is no longer rooted, and depending on what the JS engine does with the return value of `read_callback`, the pointer could be pointing at a DOM object that gets GCed by the time it's used. We should look carefully at what Firefox does here.

**Comment by gterzian** [comment]
Is this handled at the point of use? For example(where `data` is `StructuredCloneData`):

https://github.com/servo/servo/blob/914952487bcbba0a31db8aefc4a9487903721959/components/script/dom/dedicatedworkerglobalscope.rs#L310

**Comment by gterzian** [comment]
Oh you mean literally right 'in between' such a call? Perhaps this is protected by the fact that the entire thing happens inside of this

https://github.com/servo/servo/blob/master/components/script/dom/bindings/structuredclone.rs#L248

**Comment by gterzian** [comment]
Lastly, I remember reading through the actual implementation of `JS_ReadStructuredClone`(for some reason it seemed like the SpiderMonkey code was right inside the Gecko codebase), and the way it works is that the JS engine will try to internally handle the cloning, and only if it doesn't recognize the type of the clone will it invoke the `read_callback`. It seemed to all happen 'in sync' too, so there is no ayncness involved.

**Comment by jdm** [comment]
Yes, there is no risk of GC happening randomly or in parallel. It can happen as a result of any new JS allocation or certain API calls.

**Comment by gterzian** [comment]
Ok so now I remember, my implementation was perhaps a bit naive. 

In Gecko, they actually seem to keep track of cloned Blobs with this [nsTArray<RefPtr<BlobImpl>> mBlobImplArray][https://dxr.mozilla.org/mozilla-central/rev/085cdfb90903d4985f0de1dc7786522d9fb45596/dom/base/StructuredCloneHolder.h#337]

So I guess we would need some sort of `Vec<DomRoot<Blob>>`?
