### ISSUE TITLE
Implement Window.sessionStorage

### ISSUE THREAD

**Issue by jdm** [servo/servo#2117]
http://www.whatwg.org/specs/web-apps/current-work/multipage/webstorage.html#webstorage

This can also implement a version of localStorage that aliases sessionStorage, since we don't support any permanent storage in Servo right now. We'll probably need to have a `WebStorageTask` that watches for requests (either to set/get) for a given URL and accesses the appropriate storage hash based on the origin (probably the eTLD instead, but we can leave a fixme and correct that when we fix #633 as well).

**Comment by zslayton** [comment]
I'd like to try my hand at this. Is it currently being worked on?

**Comment by jdm** [comment]
@zslayton This task was basically completed, with the exception of dispatching storage events. I'll file a new issue about that in particular.
