### ISSUE TITLE
Merge run.py with run_wpt.py

### ISSUE THREAD

**Issue by jdm** [servo/servo#21201]
Back when we had two different testsuites that could be invoked in very similar ways, having separate python files in tests/wpt/ made sense. Now that there is only a single one, we should merge the two files so it's less confusing when reading the implementation of test-wpt in `python/servo/testing_commands.py`. To ensure everything still works, run `./mach test-wpt tests/wpt/mozilla/DOMParser.html`.

**Comment by ergunsh** [comment]
@highfive assign me 🎉
