### ISSUE TITLE
Restrict sharing of event-loop to Similar origin window agent

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21206]
#20678 broadens how event-loops are shared between browsing contexts to allow an [auxiliary browsing contexts](https://html.spec.whatwg.org/multipage/#auxiliary-browsing-contexts) with the same origin as it's [`opener`](https://html.spec.whatwg.org/multipage/browsers.html#opener-browsing-context) to share an event-loop with it, as they would be part of the same [unit-of-related-similar-origin-browsing-contexts](https://html.spec.whatwg.org/multipage/browsers.html#unit-of-related-similar-origin-browsing-contexts) 

A side-effect of this change is that same origin browsing contexts will share an event-loop even if not part of the same "unit-of-related-similar-origin-browsing-contexts".

We should look at restricting sharing of event-loops to inside a "unit-of-related-similar-origin-browsing-contexts" only, for example, two top-level-browsing-contexts with the same origin but without a openee/opener relationship, are not part of such an unit and thus should not share an event-loop.

A good time to look into this would be when 'process isolation' is further looked into as well.

See discussion at https://github.com/servo/servo/pull/20678#discussion-diff-202319048R273

**Comment by asajeffrey** [comment]
Also, we could look into whether it makes sense to have the process isolation barrier be coarser than an event loop. We can have multiple event loops in the same process, which might make sense if they're all from the same eTLD+1.

**Comment by gterzian** [comment]
Note that "unit-of-related-similar-origin-browsing-contexts" is gone from the spec, and has been replaced with a new concept of https://html.spec.whatwg.org/#similar-origin-window-agent

**Comment by gterzian** [comment]
This was addressed in https://github.com/servo/servo/pull/23507

**Comment by gterzian** [comment]
This was addressed in #23507
