### ISSUE TITLE
Cross-builders don't remove their build artifacts

### ISSUE THREAD

**Issue by jdm** [servo/servo#21235]
Not only do the android/arm jobs in buildbot_steps.yml not invoke the remove-build-directories script, but https://github.com/servo/saltfs/blob/master/ubuntu/files/remove-build-directories#L11 doesn't include the x86/arm/android targets that the build would generate instead of debug/release.

**Comment by jdm** [comment]
arm-unknown-linux-gnueabihf
android_aar 
armv7-linux-androideabi
gradle
aarch64-unknown-linux-gnu

**Comment by SimonSapin** [comment]
Is there a reason to remove specific sub-directories of `target/` rather than the whole thing?

**Comment by jdm** [comment]
I do not remember my original reasoning for it.

**Comment by jdm** [comment]
https://github.com/servo/saltfs/pull/870 will make the script usable on the cross builders.
