### ISSUE TITLE
[Windows] add installing lld-link.exe to the readme?

### ISSUE THREAD

**Issue by jasonwilliams** [servo/servo#21243]
Developing Servo on Windows 10 [can be painfully slow](https://github.com/servo/servo/issues/20352) using the built-in linker. 
Every build (even from the smallest change) can take around 30mins, i believe this is due to this bug:
https://github.com/rust-lang/rust/issues/37543

Thanks to help from @retep998 ive had significant speed ups using lld-link instead, so should other Servo devs be setting this up?

**Setup instructions**
* Download lld-link from https://llvm.org/builds/
* Make sure lld-link.exe is on your sytstem path
* In your local ~/.cargo/config file set this (change the triple to match your setup)
```
[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
```

Until the issue above is fixed should we recommend users install lld-link.exe instead?

**Setup**
Ryzen 7 1700 (8 Cores/16 Threads)

@larsbergstrom @vvuk @jdm @SimonSapin

**Comment by larsbergstrom** [comment]
@jasonwilliams I think we'd definitely take a change to the readme that points at this - anything that makes the dev experience better is 👍 from me!
