### ISSUE TITLE
PerformanceResourceTiming: FetchStart

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#21258]
In components/net/http_loader.rs::http_fetch we need to set fetch_start.

On getting, the fetchStart attribute MUST return as follows:

1. The time immediately before the user agent starts to fetch the final resource in the redirection, if there are HTTP redirects or equivalent.
2. The time immediately before the user agent starts to fetch the resource otherwise.

https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-fetchstart

**Comment by aditj** [comment]
Hey ! Can I take up on this? :D

**Comment by jdm** [comment]
Sure! Please ask questions if anything is unclear.

**Comment by aditj** [comment]
> Sure! Please ask questions if anything is unclear.

Actually I do have a couple of questions , 
a) So I call the FetchStart function [here](https://github.com/servo/servo/blob/9223d6248d4831a86f8172efdb9b6057f329a713/components/net/http_loader.rs#L564) but I define it [here](https://github.com/servo/servo/blob/9223d6248d4831a86f8172efdb9b6057f329a713/components/script/dom/performanceresourcetiming.rs#L155) ?
b) Should I import(use) the performanceresourcetiming if that is case or do I set the [FetchStart](https://github.com/servo/servo/blob/9223d6248d4831a86f8172efdb9b6057f329a713/components/script/dom/performanceresourcetiming.rs#L44) of an object already in the http_fetch file , if so which object?

**Comment by aditj** [comment]
I dugged into the code a little bit more and I found the Response being returned by http_fetch has a ResourceFetchTiming entry (which in turn has no of redirects , request_start ) , so maybe this is where I get the values to be set from . But I am still unclear about which PerformanceResourceTiming's fetch_start i have to set ? ( Is it something in the cache , or in some other structure )

**Comment by aditj** [comment]
Can I implement fetch_start in ResourceFetchTiming?
And is there a way to link RFT and PerformanceResourceTimings?

**Comment by aditj** [comment]
Hey! How do I know whether the Resource being fetched is the last one in the http_fetch ? Help please @jdm :sweat:

**Comment by jdm** [comment]
Sorry about the lack of response; I'll try to answer your questions in reverse order:
>How do I know whether the Resource being fetched is the last one in the http_fetch

A resource being fetched is the last one if there is no redirection. You can see this information being set in substep 2-3 and substep 4.

>Can I implement fetch_start in ResourceFetchTiming? And is there a way to link RFT and PerformanceResourceTimings?

Yes. They are linked via the PerformanceResourcetiming::from_resource_timing method, which creates a new PerformanceResourceTiming object and initializes it from the members of ResourceFetchTiming.

As you seem to have found, the timing data is collected in ResourceFetchTiming objects in the `net` crate (which doesn't know anything about PerformanceResourceTiming), then the final timings are turned into DOM values in PerformanceResourceTiming objects in the `script` crate. Does that help?

**Comment by aditj** [comment]
> As you seem to have found, the timing data is collected in ResourceFetchTiming objects in the `net` crate (which doesn't know anything about PerformanceResourceTiming), then the final timings are turned into DOM values in PerformanceResourceTiming objects in the `script` crate. Does that help?

I do have 3 questions @jdm :sweat_smile: : 
a) I create a PerformanceResourceTiming Object , but what do i do with it ? Do I submit timings using submit_timing in network_listener ? 
b) Is there a need to set up a network_listener if I am submitting the timings using submit_timing ? 
c)Also how do I get other parameters required for from_resource_timing method (namely  url, initiator_type and next_hop protocol)

**Comment by jdm** [comment]
> > On getting, the fetchStart attribute MUST return as follows:
> > 
> > 1. The time immediately before the user agent starts to fetch the final resource in the redirection, if there are HTTP redirects or equivalent.
> > 2. The time immediately before the user agent starts to fetch the resource otherwise.
> 
> But @jdm the specs say "the final resource in the redirection" , if there is no redirection then whats the point of mentioning it.

If there is no location header, the request is the final resource. We will need to store the time before starting the request, then check if there's a location header when the initial response is received; if there is no location header then that we can store the earlier time as the FetchStart value.

**Comment by jdm** [comment]
> > As you seem to have found, the timing data is collected in ResourceFetchTiming objects in the `net` crate (which doesn't know anything about PerformanceResourceTiming), then the final timings are turned into DOM values in PerformanceResourceTiming objects in the `script` crate. Does that help?
> 
> I do have 3 questions @jdm 😅 :
> a) I create a PerformanceResourceTiming Object , but what do i do with it ? Do I submit timings using submit_timing in network_listener ?
> b) Is there a need to set up a network_listener if I am submitting the timings using submit_timing ?
> c)Also how do I get other parameters required for from_resource_timing method (namely url, initiator_type and next_hop protocol)

You should not need to write code that creates a PerformanceResourceTiming object. That already happens in [this code](https://github.com/servo/servo/blob/fde83f733defe87c5450a59ab3d7bfa2bdc4a38a/components/script/network_listener.rs#L46-L55) which is called from every implementor of [this trait](https://github.com/servo/servo/blob/fde83f733defe87c5450a59ab3d7bfa2bdc4a38a/components/net_traits/lib.rs#L214), which is invoked automatically in [this code](https://github.com/servo/servo/blob/fde83f733defe87c5450a59ab3d7bfa2bdc4a38a/components/net_traits/lib.rs#L257-L266).

**Comment by aditj** [comment]
@jdm I think I was over complicating the issue  , anyways are there existing tests for fetch_start ?
And should I open a pull request for the same (without the tests that is)?

**Comment by jdm** [comment]
You can try running `./mach test-wpt tests/wpt/web-platform-tests/resource-timing` and see if any test results change. There are a bunch of tests in that directory that make use of it.
