### ISSUE TITLE
PerformanceResourceTiming: RedirectEnd

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#21257]
In components/net/http_loader.rs::http_fetch we need to set redirect_end.

On getting, the redirectEnd attribute MUST return as follows:

1. The time immediately after receiving the last byte of the response of the last redirect, if there are HTTP redirects or equivalent when fetching the resource and all the redirects or equivalent pass the timing allow check algorithm.
2. zero, otherwise.

https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-redirectend

**Comment by verma-varsha** [comment]
@highfive: assign me

**Comment by jdm** [comment]
#22561 was a good start but was incomplete.

**Comment by stmobo** [comment]
@highfive: assign me

Hi! I'm pretty new to open-source contribution, all things considered, but I look forward to working with everyone!

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by tdelacour** [comment]
@highfive assign me
