### ISSUE TITLE
PerformanceResourceTiming: domainLookupStart

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#21259]
In components/net/http_loader.rs::http_fetch we need to set domain_lookup_start (if we're using a persistent connection). Otherwise, domain lookup should be performed by hyper, which is probably out of the scope of this issue.

On getting, the domainLookupStart attribute MUST return as follows:

1. The same value as fetchStart, if a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources.
2. The time immediately after the user agent before the domain data retrieval from the domain information cache, if the user agent has the domain information in cache.
3. The time immediately before the user agent starts the domain name lookup for the resource, if the last non-redirected fetch of the resource passes the timing allow check algorithm.
4. zero, otherwise.

Spec: https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-domainlookupstart

**Comment by vuamitom** [comment]
Hi @avadacatavra ,

I've started on the code and trying to picture rough steps to complete this task, which would be like:

1. In components/net_traits/lib.rs  modify `ResourceFetchTiming` and `ResourceAttribute` to add domain_lookup_start
2. In components/net/http_loader.rs::http_fetch , set domain_lookup_start according to the logic cited above. domain_lookup_start can be set with smth like context.timing.lock().unwrap().setAttribute(....) 

Anything incorrect about this? Thanks.

**Comment by jdm** [comment]
@vuamitom Are you still working on this?

**Comment by vuamitom** [comment]
Hi @jdm I have not made any progress since my last question posted. Please feel free to re-assign if you need the issue resolved quicker.

**Comment by KaczuH** [comment]
@highfive: assign me
