### ISSUE TITLE
PerformanceResourceTiming: duration

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#21255]
In components/net/http_loader.rs::http_fetch we need to set duration for the PerformanceEntry member of PerformanceResourceTiming. This will be the difference between response_end and start_time

Spec: https://w3c.github.io/resource-timing/#dfn-duration

**Comment by haedaal** [comment]
@highfive assign me :)

**Comment by jdm** [comment]
@haedaal Are you still working on this? Do you have any questions?

**Comment by vn-ki** [comment]
@highfive assign me

**Comment by vn-ki** [comment]
@jdm Can you please give some pointers where to start? I looked into `components/net/http_loader.rs::http_fetch`. I'm not sure what to change.

**Comment by jdm** [comment]
I believe that this does not require any changes to the code in components/net; it only requires computing the difference between the responseEnd and fetchStart values in components/script/dom/performanceresourcetiming.rs and adding the interface attribute in components/script/dom/webidls/PerformanceResourceTiming.webidl. However, we do not implement responseEnd yet, so you should probably fix #21263 first.

**Comment by vn-ki** [comment]
> components/script/dom/performanceresourcetiming.rs

I can't find a file named that.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/master/components/script/dom/performanceresourcetiming.rs

**Comment by nagashayan** [comment]
@highfive assign me

**Comment by nagashayan** [comment]
I see responseEnd and fetchStart is fixed now. this should be good to go now.

**Comment by jdm** [comment]
Great!

**Comment by nagashayan** [comment]
The duration attribute MUST return a DOMHighResTimeStamp equal to the difference between responseEnd and startTime, respectively.

**Comment by nagashayan** [comment]
startTime issue https://github.com/servo/servo/issues/21254 should be completed before we can work on duration. I see the PR is here https://github.com/davidweitzenfeld/servo/pull/1 but its for forked branch. @jdm  right?

**Comment by jdm** [comment]
Indeed. If you want to cherry-pick that commit and build on top of it, that would be fine.

**Comment by nagashayan** [comment]
right! I will do that. thanks.

**Comment by nagashayan** [comment]
I started by cherry-picking on #21254 PR (in another forked repo), it seems that PR itself is not complete. starttime is not implemented in performanceresourcetiming.rs file.

**Comment by jdm** [comment]
@nagashayan Are you still working on this?

**Comment by nagashayan** [comment]
@jdm  yes, this weekend I will try to finish.

**Comment by nagashayan** [comment]
@jdm Just refreshed my memory I am waiting on 21254 issue to be resolved. I need that value to complete this PR. what do you think?

**Comment by aug2uag** [comment]
@jdm i cherry-picked the commits from David as mentioned a couple messages above and everything builds nice

no tests i don't know where to put them besides w3c_navigation_timing.js and there its completely empty at the moment plus the documentation for how to run it seems to be missing? 

if PR #24493 looks good to you please assign me, if assigned please advise whether adding a setter function in PerformanceEntry that's called from PerformanceResourceTiming to set duration is the way to go-- also webidls look up-to-date and about the tests
