### ISSUE TITLE
PerformanceResourceTiming: responseEnd

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#21263]
On getting, the responseEnd attribute MUST return as follows:

1. The time immediately after the user agent receives the last byte of the response or immediately before the transport connection is closed, whichever comes first. The resource here can be received either from relevant application caches, local resources, or from the server.
2. The time immediately before the user agent aborts the fetch due to a network error.

Spec: https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-responseend

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/481662d0a77c9f85de353107d11beca1a030698d/components/net/http_loader.rs#L1284-L1302 are two blocks of code that would need to set this attribute in the ResourceFetchTiming structure.

**Comment by vn-ki** [comment]
@jdm Which file(s) should I be looking at for this issue? 

I would assume the above linked files have to be changed, but I docs.servo.org/servo is crashing on me and I can't find ResourceFetchTiming structure.

Is there any other way to access the docs?

**Comment by CYBAI** [comment]
> Is there any other way to access the docs?

https://doc.servo.org/servo/index.html

**Comment by jdm** [comment]
Other files necessary:
* https://github.com/servo/servo/blob/master/components/net_traits/lib.rs#L444
* https://github.com/servo/servo/blob/master/components/script/dom/performanceresourcetiming.rs
* https://github.com/servo/servo/blob/master/components/script/dom/webidls/PerformanceResourceTiming.webidl

**Comment by jiachengpizza** [comment]
Hi @jdm ,
I'm learning Rust and servo code starting from this issue. I think the responseEnd timing value should be set after Line 1290 and Line 1300, after ResponseBody::Done(). Is that right?
Thanks.

**Comment by jdm** [comment]
Sorry for the delay; I was on vacation. Yes, that sounds right to me.

**Comment by tdelacour** [comment]
@highfive assign me

**Comment by tdelacour** [comment]
Hi @jdm (or whoever can help!) I've added a couple of expressions inside the `spawn()` closure in `http_loader.rs` and it now looks like this:
```
HANDLE.lock().unwrap().spawn(
        res.into_body()
            .map_err(|_| ())
            .fold(res_body, move |res_body, chunk| {
                if cancellation_listener.lock().unwrap().cancelled() {
                    *res_body.lock().unwrap() = ResponseBody::Done(vec![]);
                    let _ = done_sender.send(Data::Cancelled);
                    return future::failed(());
                }
                if let ResponseBody::Receiving(ref mut body) = *res_body.lock().unwrap() {
                    let bytes = chunk.into_bytes();
                    body.extend_from_slice(&*bytes);
                    let _ = done_sender.send(Data::Payload(bytes.to_vec()));
                }
                future::ok(res_body)
            })
            .and_then(move |res_body| {
                let mut body = res_body.lock().unwrap();
                let completed_body = match *body {
                    ResponseBody::Receiving(ref mut body) => mem::replace(body, vec![]),
                    _ => vec![],
                };
                *body = ResponseBody::Done(completed_body);
                context // <-------------- ADDED
                    .timing
                    .lock()
                    .unwrap()
                    .set_attribute(ResourceAttribute::ResponseEnd);
                let _ = done_sender2.send(Data::Done);
                future::ok(())
            })
            .map_err(move |_| {
                let mut body = res_body2.lock().unwrap();
                let completed_body = match *body {
                    ResponseBody::Receiving(ref mut body) => mem::replace(body, vec![]),
                    _ => vec![],
                };
                *body = ResponseBody::Done(completed_body);
                context // <-------------- ADDED
                    .timing
                    .lock()
                    .unwrap()
                    .set_attribute(ResourceAttribute::ResponseEnd);
                let _ = done_sender3.send(Data::Done);
            }),
    );
```
But this causes a compiler error:
```
error[E0277]: `(dyn embedder_traits::EventLoopWaker + 'static)` cannot be shared between threads safely
    --> components/net/http_loader.rs:1278:28
     |
1278 |     HANDLE.lock().unwrap().spawn(
     |                            ^^^^^ `(dyn embedder_traits::EventLoopWaker + 'static)` cannot be shared between threads safely
     |
```

I _think_ I understand, broadly, what the issue is: I'm referencing `context` within a new thread, but `context` is not threadsafe. I was able to get past the compiler by making mutable clones of the `ResourceFetchTiming` struct inside `context` and using those inside the closure, but that doesn't seem like it would accomplish... anything (the updated timing structs wouldn't be accessible anywhere outside of the closure in the spawned thread, right?)

As you can probably tell, I'm *very* new to Rust. I'm reading up on closures, moves, concurrency, send / sync, etc in the Rust book, but I could definitely use some more targeted instruction 😄

**Comment by jdm** [comment]
If you make a clone of `context.timing` outside of the closure and refer to that clone inside of it, you should be able to achieve your goal. That avoids sharing the whole context, and the timing information is already stored in an Arc wrapper (I believe), so cloning it does not actually duplicate it.

**Comment by tdelacour** [comment]
amazing, thank you!
