### ISSUE TITLE
PerformanceResourceTiming: connectEnd

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#21262]
If a persistent connection is used, connect_end will be set in components/net/http_loader.rs::http_fetch, otherwise, it will be in components/net/http_loader.rs::obtain_response

On getting, the connectEnd attribute MUST return as follows:

1. The same value as fetchStart, if a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources.
2. The time immediately after the user agent finish establishing the connection to the server to retrieve the resource, if the last non-redirected fetch of the resource passes the timing allow check algorithm.
  - The returned time MUST include the time interval to establish the transport connection, as well as other time intervals such as SSL handshake and SOCKS authentication.
  - If the transport connection fails and the user agent reopens a connection, connectEnd SHOULD return the corresponding value of the new connection.
3. zero, otherwise.

https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-connectend

**Comment by pylbrecht** [comment]
@highfive: assign me

**Comment by pylbrecht** [comment]
> If a persistent connection is used, connect_end will be set in components/net/http_loader.rs::http_fetch, otherwise, it will be in components/net/http_loader.rs::obtain_response

Does this mean that `PerformanceResourceTiming.connect_end` is set by another entity. Ergo, I can rely on
> 1. The same value as fetchStart, if a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources.

as being fulfilled?

**Comment by jdm** [comment]
No. connect_end does not exist right now; the purpose of this work is to make it exist. That being said, we do not have the ability to distinguish between persistent connections or not right now, so we will have to ignore that part of the specification.

**Comment by pylbrecht** [comment]
Alright, I gained some insights while digging through the involved code and I think I'm getting a idea of what to implement exactly.

**Comment by jdm** [comment]
The other important piece here is exposing the DOM API in components/script/dom/webidls/PerformanceResourceTiming.webidl, and make sure that the value recorded in the net code is propagated to that structure.
