### ISSUE TITLE
PerformanceResourceTiming: connectStart

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#21261]
If a persistent connection is used, connect_start will be set in components/net/http_loader.rs::http_fetch, otherwise, it will be in components/net/http_loader.rs::obtain_response

On getting, the connectStart attribute MUST return as follows:

1. The same value as fetchStart, if a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources.
2. The time immediately before the user agent start establishing the connection to the server to retrieve the resource, if the last non-redirected fetch of the resource passes the timing allow check algorithm. If the transport connection fails and the user agent reopens a connection, connectStart SHOULD return the corresponding value of the new connection.
3. zero, otherwise.

https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-connectstart

**Comment by VishalCR7** [comment]
@highfive: assign me

**Comment by VishalCR7** [comment]
@jdm : Hey! I m just getting started. Can you please explain what needs to be done and which files to look at for solving this bug. Thanks in advance :)

**Comment by VishalCR7** [comment]
@highfive : unassign me

**Comment by jdm** [comment]
Since I don't believe we can determine if a persistent connection is used or not right now, we should set connectStart in the `obtain_response` function in `components/net/http_loader.rs`, right before calling `client.request`.

**Comment by nehalem501** [comment]
@highfive: assign me

**Comment by atouchet** [comment]
In #23323 it says that this was only fixed partially. Is there more to do here?

**Comment by jdm** [comment]
Support for persistent connections doesn't exist yet, but we should file a new issue about that.
