### ISSUE TITLE
Split find_image_or_metadata API into two separate APIs

### ISSUE THREAD

**Issue by jdm** [servo/servo#21289]
`find_image_or_metadata` serves two purposes today - learn about the state of the cache right now, and reserve a spot in the cache if there is not already an entry. This makes understanding how callers use it complicated, and it makes it easy to forget to add listeners for existing incomplete cache entries. We should redesign it:
* `get_image` should return an `Option<Image>` which indicates that there is either a cached, fully loaded image, or not
* `track_image` should accept a sender argument, which will be stored in the image cache just like the `ImageCache::add_listener` API. `track_image` will return a `ImageCacheResult` enum with the following states:
* `Available(ImageOrMetadataAvailable)` (if only metadata is available)
* `LoadError`
* `Pending`
* `ReadyForRequest(PendingImageId)`

The `Available(ImageOrMetadataAvailable::Image)` and `LoadError` states will result in the sender being dropped, since no more updates for that cache entry are expected. All other states will result in the sender being stored in the cache entry. This will make it impossible for a consumer to accidentally forget to add a cache listener for any state.

**Comment by BK1603** [comment]
I'd like to work on this!

**Comment by BK1603** [comment]
@jdm
Just to let you know:
I am still working on this, i've read a lot of the codebase in order to know about what i need to know, one of the functions is done, doing the secons one and figuring out calls, will probably meed help with that

And I apologoze for taking too long :sweat_smile: 

Thanks once again for all the help

**Comment by jdm** [comment]
No need to apologise! Thanks for letting us know.

**Comment by BK1603** [comment]
@jdm,
I am not able to build servo on my machine. I have tried a lot of stuff but I still am stuck :sweat_smile: 
Here is the error code, can you help me please? :sweat_smile: 

error: linking with `cc` failed: exit code: 1

  = note: collect2: fatal error: ld terminated with signal 6 [Aborted], core dumped
          compilation terminated.
          terminate called after throwing an instance of 'std::bad_alloc'
            what():  std::bad_alloc

**Comment by jdm** [comment]
That looks like you're running out of RAM while building.

**Comment by BK1603** [comment]
@jdm, 
Even at 6.5 gigs??
I have a minimal linux installation in an 8 gigs machine, it should get at least 6.5 in all cases, how much ram do i need? 
Is this some bug? 
What do i do now? :sweat_smile:

**Comment by jdm** [comment]
We definitely exceed 6gb of used RAM at times during compilation. I don't know what to suggest :/

**Comment by BK1603** [comment]
@jdm, oh okay 
Got it
I will think of something then :sweat_smile: 
Like i will tell you soon if i am able to do sonething, else you can just unassign this issue again :sweat_smile:

I'll try something and let you know

**Comment by BK1603** [comment]
@jdm,
I tried doing a lot of stuff and ended up increasing the swap partition of my linux system, for which I had to format my laptop and reinstall everything, it does work but right now building on my laptop is like hours long, cause when the ram is completely filled up the system gets really slow, I don't think I will be able to build and debug as efficiently then :sweat_smile: 

It won't be a problem if you unassign the issue for now, I am trying out a few more things (one of them being convincing my parents for giving me the money for upgrading the RAM :sweat_smile: ), but I think they will take a lot of time, and I already have taken 15 days on this, it won't be a problem if someone else is able to fix this before me :smile: 

I hope I will be able to fix everything soon and make a PR, like I really want to do it :sweat_smile: but for now I guess I have to try and find a workaround, or get my RAM upgraded.

**Comment by jdm** [comment]
Ok! Sorry it's caused so much trouble for you!

**Comment by BK1603** [comment]
@jdm,
It's absolutely fine, I don't think it's any of ours fault :smile:

Also it was quite fun interacting there on irc and working on such a huge project, I'd say
Thanks a lot! :smile:

**Comment by germangb** [comment]
Hi @BK1603 Are you still interested in working on this issue?

**Comment by iulianR** [comment]
Hi! Is it fine if I work on this issue? Thank you!

**Comment by jdm** [comment]
@iulianR Yes please!

**Comment by iulianR** [comment]
@highfive: assign me

**Comment by iulianR** [comment]
Started working on this and I have some questions related to the sender argument for `track_image`.

The way I see it, currently `htmlimagelement.rs` and `htmlvideoelement.rs` use `add_cache_listener_for_element` when `find_image_or_metadata` returns `Pending`, which creates an `ImageResponder` and calls `add_listener` with that image listener as sender.
 
Should I rename `add_cache_listener_for_element` and have it return the `ImageResponder` which I would then pass to `track_image`, which in turn calls `add_listener`? Also, should `add_listener` still be public?

**Comment by jdm** [comment]
@iulianR Yes, that sounds like a reasonable way to structure the code. There's one other use of `add_listener` in `window.rs` right now which it's not clear if we can replace with the new APIs, so I don't think we can make it private yet.

**Comment by iulianR** [comment]
I was unable to finish it in the free days I had then and unfortunately, I do not have the required time to finish it now. It can be assigned to someone else.

**Comment by rileylyman** [comment]
Hi, I would like to take this issue. Let me know if that's okay!

**Comment by jdm** [comment]
Please do!

**Comment by julientregoat** [comment]
hey since it looks like you haven't started yet, mind if I do @rileylyman?

@highfive: assign me

**Comment by jdm** [comment]
You are welcome to take your time with it :)

**Comment by julientregoat** [comment]
hey @jdm , wrote some  code tonight, and I think I got it under a handle. can you tell me if I'm heading in the right direction? building correctly atm. plan on doing the second iteration once I finish the firt,

`https://github.com/julientregoat/servo/blob/i-21289/components/net/image_cache.rs`

**Comment by jdm** [comment]
Yes, that seems like the right idea!

**Comment by julientregoat** [comment]
@jdm Okay so I'm refactoring the functions that previously called `find_image_or_meta` atm. Currently, it looks like if any of them require access to the  image, it's generally as `Arc<Image>`. It seems like it would be better to return an `Option<Arc<Image>>` from `ImageCache::get_image`, which unwraps it from an `Arc` anyway - does that work?

Also, a few of those same functions usually do something with the `PendingImageId` in the event that the image is still pending. Would it be ok to have the enum as `ImageCacheResult::Pending(PendingImageId)`?

**Comment by jdm** [comment]
@julientregoat If the consumers want an Arc, then that seems like a reasonable change. As for the question about the Pending variant, do the functions do anything besides call add_listener? I would expect that functionality to become part of `track_image` automatically.

**Comment by julientregoat** [comment]
@jdm 
* In `LayoutContext::get_or_request_image_or_meta`, it uses the id to construct a `PendingImage` and add it to its internal `pending_images` vector.
* In `HTMLImageElement::react_to_environment_changes_sync_steps`, on `Pending` it does call `add_cache_listener_for_element`, which I recognize also calls `ImageCache::add_listener` inside like `ImageCache::track_image`, however I wasn't sure if that served a different purpose because of the extra logic within the function - seemed like custom ipc messaging & routing logic
* Same as above for `HTMLVideoElement::fetch_poster_frame`

**Comment by jdm** [comment]
Good point! Seems reasonable to include it for the time being, in that case.
