### ISSUE TITLE
Issues with URL dialog box

### ISSUE THREAD

**Issue by atouchet** [servo/servo#21294]
When Servo is first launched the URL dialog box appears fairly consistently when pressing Ctrl + L. However when trying to get the URL dialog box to appear again after the first time it often will not show up when pressing Ctrl + L again. Other odd behaviour can happen as well such as the URL box appearing when only pressing L without pressing Ctrl. This issue was introduced with #21250 (at least on Windows) as the Ctrl + L keybinding did not work on Windows prior to that commit. This was only tested in Windows 10 and I do not know if this behaviour occurs on other operating systems.

Edit: I tested this further and what is happening is that the first time pressing Ctrl + L will open the URL dialog box. Further presses of this key combination will no longer bring it up. However after the first time it is opened it will later be opened by only pressing L without Ctrl. This causes further problems as then it is no longer possible to type "l" in sites with text input boxes. Not only does this cause issues with "l" but I think it also occurs with any other keybinding used with Ctrl. For example after navigating to a new site using Ctrl + L, then pressing Q without Ctrl will close the browser.

cc @paulrouget

**Comment by paulrouget** [comment]
Very likely related to the sticky key issue describe by @dorfsmay here https://github.com/servo/servo/pull/21250#issuecomment-408137919

I think the key release that would unset the control key modifier is not caught because the popup has the focus.

**Comment by paulrouget** [comment]
Ok, I managed to reproduce on Mac. So it's affecting all the platforms.

**Comment by paulrouget** [comment]
To fix this, we should stop tracking the modifiers states as the modifiers keys are pressed, but instead rely on: https://docs.rs/winit/0.16.2/winit/struct.KeyboardInput.html#structfield.modifiers

**Comment by paulrouget** [comment]
https://github.com/servo/servo/pull/21301 should fix it.

I can't test on Linux and Windows at the moment, but it works on Mac.

**Comment by atouchet** [comment]
I have confirmed that this is now working on Windows as well.
