### ISSUE TITLE
Custom features no longer affect the build

### ISSUE THREAD

**Issue by jdm** [servo/servo#21314]
When I write `./mach build -d --features whatever`, I no longer receive an error about the `whatever` feature not existing. If I add `-v` to the build, I don't see `whatever` passed to any of the crates. This regressed sometime in the past month.

**Comment by jdm** [comment]
The actual build command being invoked is `rustup run --install nightly-2018-07-17 cargo build -v --features whatever`, so I'm really confused why this is being ignored now.

**Comment by jdm** [comment]
I believe this was regressed by #20912, which removed the use of `--manifest-path` from the cargo commands. When I create a workspace with a single default-member, `cargo build --features whatever` no longer produces an error. When I run `cargo build --manifest-path project --features whatever` (assuming the default member is named project), I receive the expected error.

cc @SimonSapin

**Comment by jdm** [comment]
This also means that we can't use --debug-mozjs, or any of the VR-related features, and no longer are building with unstable features in our CI.

**Comment by jdm** [comment]
I've filed https://github.com/rust-lang/cargo/issues/5849.

**Comment by jdm** [comment]
@SimonSapin Are you aware of a workaround here? Could we restore the previous manifest-path usage that existed before #20912?

**Comment by SimonSapin** [comment]
I’m not sure exactly. I think that reverting to using `--manifest-path` in mach would fix command-line usage of `--feature`, but then we’d need to find another way to deal with `libsimpleservo` v.s. the `servo` executable. Perhaps the former should not be in `default-members` after all, and instead we should have (more) custom logic in `mach` for Android targets.

**Comment by jdm** [comment]
Simon said they would work on this.

**Comment by SimonSapin** [comment]
Using `--manifest-path` means picking one "root" crate to build, whereas the current default is to build both `ports/servo` and `ports/libsimpleservo`.

@paulrouget What do you think of building the latter for Android targets and the former in other cases? Are there cases where we want to make the other choice? Specifically, since `ports/servo` is an empty crate on Android, do we want to support (building) libsimpleservo on non-Android? Would `./mach build --manifest-path ports/libsimpleservo` be an acceptable interface for that?

**Comment by jdm** [comment]
We could do something like the old `./mach build-geckolib`, too. We're relying on being able to build libsimpleservo for ML devices, but those aren't detected as android devices.

**Comment by SimonSapin** [comment]
What are ML devices in this context?

**Comment by paulrouget** [comment]
@SimonSapin libsimpleservo is not android specific (there's a non-jni version too), even though we only use it for Android now. We need to be able to build both ports.
