### ISSUE TITLE
Compiling slower with libsimpleservo

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21343]
I've noticed that since `libsimpleservo` has been added, it seems that the code generation takes twice as much time(and memory). It appears that there are two processes for `llvm-dysmutil`, I can only assume one for both `/ports/servo` and one for `ports/libsimpleservo`. 

Am I missing some option when compiling?

**Comment by paulrouget** [comment]
The final linking stage might be twice longer than before. And I don't see anyway to work around that.

You can compile ports/servo only: `./mach build  -p servo`.

I'm updating the README: https://github.com/servo/servo/pull/21347
