### ISSUE TITLE
Root stacking context doesn't honor the viewport origin

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21350]
In Servo, the embedder can set the viewport to any size, but also to any position.
Setting an arbitrary size works. Setting the position doesn't.

The problem could be:

1. the root stacking context bounds origin is `0x0` when it should start at the viewport origin
2. or, it's fine if the root stacking context bounds origin is `0x0`, but then, WR should honor the document origin set via `set_window_parameters`.

To reproduce the issue, apply this patch to force Servo to render the page into a 300x300 square with 50x50 as its origin:

```rust
diff --git a/components/servo/lib.rs b/components/servo/lib.rs
index 5623874408..912b7c8fa8 100644
--- a/components/servo/lib.rs
+++ b/components/servo/lib.rs
@@ -102,6 +102,7 @@ use std::path::PathBuf;
 use std::rc::Rc;
 use std::sync::mpsc::{Sender, channel};
 use webrender::RendererKind;
+use webrender_api::DeviceUintSize;
 use webvr::{WebVRThread, WebVRCompositorHandler};

 pub use gleam::gl;
@@ -191,8 +192,7 @@ impl<Window> Servo<Window> where Window: WindowMethods + 'static {
         };

         let webrender_api = webrender_api_sender.create_api();
-        let wr_document_layer = 0; //TODO
-        let webrender_document = webrender_api.add_document(coordinates.framebuffer, wr_document_layer);
+        let webrender_document = webrender_api.add_document(DeviceUintSize::new(300 as u32, 300 as u32), 0);

         // Important that this call is done in a single-threaded fashion, we
         // can't defer it after `create_constellation` has started.
diff --git a/ports/servo/glutin_app/window.rs b/ports/servo/glutin_app/window.rs
index 101161bde7..8e735637a8 100644
--- a/ports/servo/glutin_app/window.rs
+++ b/ports/servo/glutin_app/window.rs
@@ -700,7 +700,7 @@ impl WindowMethods for Window {
                 let LogicalSize { width, height } = window.get_inner_size().expect("Failed to get window inner size.");
                 let inner_size = (TypedSize2D::new(width as f32, height as f32) * dpr).to_u32();

-                let viewport = DeviceUintRect::new(TypedPoint2D::zero(), inner_size);
+                let viewport = DeviceUintRect::new(TypedPoint2D::new(50,50), TypedSize2D::new(300,300));

                 EmbedderCoordinates {
                     viewport: viewport,
```

Run Servo: `./mach run -d 'data:text/html,<style>html{background:red}</style>'`

We see that the document is position at `0x0`:

<img width="1136" alt="screen shot 2018-08-07 at 11 13 36" src="https://user-images.githubusercontent.com/373579/43766531-f414d9fc-9a32-11e8-868f-ee001cf5f295.png">

Now, manually adding the origin will properly position the document:

```rust
diff --git a/components/layout/display_list/webrender_helpers.rs b/components/layout/display_list/webrender_helpers.rs
index 987259ed5b..ea3319ff16 100644
--- a/components/layout/display_list/webrender_helpers.rs
+++ b/components/layout/display_list/webrender_helpers.rs
@@ -240,7 +240,9 @@ impl WebRenderDisplayItemConverter for DisplayItem {
                 let stacking_context = &item.stacking_context;
                 debug_assert_eq!(stacking_context.context_type, StackingContextType::Real);

-                let mut info = webrender_api::LayoutPrimitiveInfo::new(stacking_context.bounds);
+                let mut bounds = stacking_context.bounds;
+                bounds.origin = LayoutPoint::new(25.0, 25.0); // 50 / 2 (hidpi ratio)
+                let mut info = webrender_api::LayoutPrimitiveInfo::new(bounds);
                 if let Some(frame_index) = stacking_context.established_reference_frame {
                     debug_assert!(
                         stacking_context.transform.is_some() ||
```

<img width="1136" alt="screen shot 2018-08-07 at 11 13 10" src="https://user-images.githubusercontent.com/373579/43766515-eb1fd68a-9a32-11e8-9fe4-7f2bf7023912.png">

So I'm not sure if it's up to WR to shift the document based on the document origin (otherwise, why do we even send the document origin to WR?) or if it's up to servo to create a root stacking context that is translated to the viewport origin.

**Comment by kvark** [comment]
> In Servo, the embedder can set the viewport to any size, but also to any position.

Note that "viewport" term here is on your side, and it's confusing. What WR exposes is:
```rust
pub fn set_window_parameters(
        &mut self,
        window_size: DeviceUintSize,
        inner_rect: DeviceUintRect,
        device_pixel_ratio: f32,
    )
```

You see the `inner_rect` here. It works as a scissor test on the document, it helps both to limit the rendering to specific area of the window and determine the background color area affected.

WR can be wired other way, but semantically speaking you aren't providing a viewport, so the expectation of `inner_rect` moving as opposed to clipping is not grounded.

Would the current API work for you? If not, we can surely change it. Gecko has yet to start using multiple documents.

**Comment by paulrouget** [comment]
@kvark understood. Thank you.

It doesn't really matter to me which way we do it. I don't know much about layout, stacking contexts and WR. So I just need to understand what is the "right way" then I can start working on a PR.

I can set the stacking_context to start at the proper coordinate, just want to know if it's the right thing to do.

**Comment by paulrouget** [comment]
I need some help here. I see plenty of possible ways of shifting the stacking root context origin to the proper coordinates, but I really don't know where is the best place to do that.

My strategy so far has been to not hard code the root stacking context origin to `0,0` here: https://github.com/servo/servo/blob/ea86eb64be7b1a1bcee4edc33eeb45c47e408497/components/layout_thread/lib.rs#L1020

I imagine that the next step would then be to make it so `root_flow` is properly translated, but I'm really not sure I'm taking the right route here.

Can anyone give me some directions here?

**Comment by jdm** [comment]
@pcwalton Given your familiarity with layout, does the previous comment make sense?

**Comment by pcwalton** [comment]
I didn't anticipate that the origin of the root would be anything other than 0,0, no.

I believe that is the best way to do it, yes. Changing `origin` there should effectively translate everything.

**Comment by paulrouget** [comment]
The more I think about it, the more I believe this should be transparent for Servo. As in, not be part of any layout logic.

We should be able to tell WR where the document is (not just its size). I'd like to know how it works for Gecko. Waiting on https://bugzilla.mozilla.org/show_bug.cgi?id=1441308#c52

**Comment by paulrouget** [comment]
I've been experimenting with WR and I understand now that layout (Servo) needs to shift the content no matter the WR configuration. `inner_rect ` doesn't clip. It skips objects that don't need to be drawn.

More context: we need to be able to control the position of a document for 2 reasons:

- we want to use multiple WR documents the same way it's done in Gecko (for chrome and content)
- we also need to add a transparent border around the framebuffer (shrinking the drawing area)

Basically we need to be able to translate the origin of a `0x0` CSS pixel anywhere on the framebuffer.

There are 2 possible options: either Servo does the work of translating the layout, or WR translate the WR document.

---

It would be very handy if WR could have a `viewport_rect` window parameter. As in, a rect that defines where the coordinates start and where to actually clip. The framebuffer window parameter already behaves as a clipping rectangle (except for clear_color) when it's smaller that the actual framebuffer size.

The current API looks like this:
```
set_window_parameters(framebuffer_size, inner_rect, device_pixel_ratio);
```

Maybe we could have instead something like this:
```
set_window_parameters(viewport_rect, inner_rect, device_pixel_ratio);
```

`viewport_rect` would be use for clipping. And if its origin is 10x10, a 0x0 LayoutPoint would be, on the framebuffer, located at 10x10. The original `framebuffer_size` parameter could be derived from `viewport_rect` assuming `viewport_rect` is always contained within the framebuffer.

Then I think by just setting the window parameter, we could move the WR document anywhere on the framebuffer without requiring Servo to compute anything.

---

That said, I don't know if that makes sense from the point of view of WR. We could absolutely have that logic inside Servo. It would just make my life easier if WR would let me position a document anywhere I wanted on the framebuffer without worrying about doing computing on servo's side.

/cc @kvark

**Comment by kvark** [comment]
For WR internals, we can do either way: shift the content to the origin of the inner rect (or the one provided in `viewport_rect` as suggested) or not, and I don't feel strongly either way. Main thing to get is a consensus between you and @squarewave on what WR should do :)

btw, the `framebuffer_size` parameter we pass into the window parameters doesn't appear to be used much.

**Comment by squarewave** [comment]
> It would be very handy if WR could have a `viewport_rect` window parameter. As in, a rect that defines where the coordinates start and where to actually clip. The framebuffer window parameter already behaves as a clipping rectangle (except for clear_color) when it's smaller that the actual framebuffer size.

Gecko currently is happy with a 0,0 origin and everything is just shifted already.

Am I understanding correctly that what you're proposing would behave identical to how it does now if one were to simply always specify a 0,0 origin for viewport_rect? If so then I have no issues with the proposal. I can then evaluate later if it makes anything simpler/better on the Gecko side to leave this translation to WR.

**Comment by paulrouget** [comment]
@kvark with such a system in place, would a clear_color call in WR affect anything beyond viewport_rect?

**Comment by kvark** [comment]
@pauldipietro I don't think we need different semantics for clear versus non clear. We just basically need a single rect per document, which determines where on the screen it will land, and what the size of the viewport is for rendering the display lists.

**Comment by kvark** [comment]
@pauldipietro I don't think there is any complex logic in here, it's 99% plumbing. I'd start by making sure there is a single rect given for the document, and by forcing the clears and viewports to be set up based on this rect. Then we'd need to change the example to not offset the primitives by the document's origin, and to make sure through the code that the document origin isn't used for anything other than the clears/viewports on the renderer side.

**Comment by paulrouget** [comment]
@kvark can I use this `pan` property to shift the document: https://github.com/servo/webrender/blob/d7c166855108671e16d49ff88bba25e82926e862/webrender/src/render_backend.rs#L365 ?

**Comment by kvark** [comment]
The pan/zoom should be used to change the view of the document itself, not change the place of a document on screen. If you are having trouble approaching this, maybe we should call in on Vidyo/Skype and talk?

**Comment by paulrouget** [comment]
Yes. I sent you an email.

Here are the branches I'm using:

- webrender: https://github.com/servo/webrender/compare/master...paulrouget:clipping
- servo: https://github.com/servo/servo/compare/master...paulrouget:webrender-clipping

So far I only moved from a framebuffer size to a viewport rect.

Translating the document hasn't been implemented yet (I was using the pan property, which I thought would be the right thing).

**Comment by paulrouget** [comment]
@kvark: 3 questions:

Using gl.viewport() to shift the content works, but I don't know where to store the origin coordinates. Probably not under `gl::Device` as the origin differs per documents. I guess it should be stored under the `gl::Texture` struct?

As for clipping, apparently `device.set_scissor_rect(rect)` is not called all the time, or even at all in my basic HTML tests. Is that normal? Do I need to force a call to `set_scissor_rect`?

Also - as for the API: we still need the framebuffer size (coordinates are flipped, so we need to know the full size of the gl buffer for the flip), so my above proposal doesn't work anymore.

Initially we had:

```rust
set_window_parameters(framebuffer_size, inner_rect, device_pixel_ratio);
```

In https://github.com/servo/servo/issues/21350#issuecomment-412864088 you say:

> the expectation of `inner_rect` moving as opposed to clipping is not grounded.

Would it work if we were to do something like this:

```rust
set_window_parameters(framebuffer_size, inner_rect, device_pixel_ratio, bool);
```

… where the boolean defines whether the display lists coordinates are shifted by inner_rect.origin?

**Comment by kvark** [comment]
@paulrouget 

> Using gl.viewport() to shift the content works, but I don't know where to store the origin coordinates. Probably not under `gl::Device` as the origin differs per documents. I guess it should be stored under the `gl::Texture` struct?

User provides it for a document, so it should be stored in a document: https://searchfox.org/mozilla-central/rev/4587d146681b16ff9878a6fdcba53b04f76abe1d/gfx/wr/webrender/src/renderer.rs#2622

> As for clipping, apparently `device.set_scissor_rect(rect)` is not called all the time, or even at all in my basic HTML tests. Is that normal? Do I need to force a call to `set_scissor_rect`?

Yes, it is normal, no need to force it. We don't set scissor if we know for sure that the shader doesn't write outside of the designated area.

> Also - as for the API: we still need the framebuffer size (coordinates are flipped, so we need to know the full size of the gl buffer for the flip), so my above proposal doesn't work anymore.

Right, we still need to pass the framebuffer size around.

> where the boolean defines whether the display lists coordinates are shifted by inner_rect.origin?

I don't think it's worth providing run-time control over what's shifted and what not. Let's just shift everything unconditionally.

**Comment by kvark** [comment]
Created https://bugzilla.mozilla.org/show_bug.cgi?id=1531217

**Comment by paulrouget** [comment]
Fixed. Thanks a lot for your help @kvark
