### ISSUE TITLE
make check fails with several undefined references

### ISSUE THREAD

**Issue by cgjones** [servo/servo#2136]
<pre>
$ make check
...
note: /home/cjones/src/servo/obj/x86_64-unknown-linux-gnu/src/support/stb-image/rust-stb-image/libstb_image-30b28982-0.1.rlib(stb_image.o): In function `stb_image::image::load_with_depth':
/home/cjones/src/servo/src/support/stb-image/rust-stb-image/image.rs:74: undefined reference to `stbi_is_hdr'
/home/cjones/src/servo/src/support/stb-image/rust-stb-image/image.rs:74: undefined reference to `stbi_loadf'
/home/cjones/src/servo/src/support/stb-image/rust-stb-image/image.rs:58: undefined reference to `stbi_load'
/home/cjones/src/servo/obj/x86_64-unknown-linux-gnu/src/support/stb-image/rust-stb-image/libstb_image-30b28982-0.1.rlib(stb_image.o): In function `stb_image::image::load_from_memory_with_depth':
/home/cjones/src/servo/src/support/stb-image/rust-stb-image/image.rs:111: undefined reference to `stbi_is_hdr_from_memory'
/home/cjones/src/servo/src/support/stb-image/rust-stb-image/image.rs:111: undefined reference to `stbi_loadf_from_memory'
/home/cjones/src/servo/src/support/stb-image/rust-stb-image/image.rs:122: undefined reference to `stbi_load_from_memory'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
make: *** [servo-test-net] Error 101
</pre>
This is with a vanilla build of a52248f765f92d0d20e4ee6465b3a8cc5d9c0c8c on fedora core 20.

**Comment by frewsxcv** [comment]
This hasn't been reported in a while and we don't use `make` anymore
