### ISSUE TITLE
./mach build -r fails on skia although it's present

### ISSUE THREAD

**Issue by traumschule** [servo/servo#21379]
[debian buster x86]

building servo fails on skia although it is present
```
~/src/rust/servo$ ./mach build --release
   Compiling servo-skia v0.30000019.0                                                                           
error: could not find native static library `skia`, perhaps an -L flag is missing?a                      
error: aborting due to previous error
error: Could not compile `servo-skia`.                                                                          

To learn more, run the command again with --verbose.
Build FAILED in 0:02:50
~/src/rust/servo$ find target -name libskia.a
target/debug/build/servo-skia-1a7be4e76adcc9a4/out/lib/libskia.a                                                
target/debug/build/servo-skia-1a7be4e76adcc9a4/out/build/libskia.a                                              
target/release/build/servo-skia-8cb0b01a22a9f447/out/lib/libskia.a                                              
target/release/build/servo-skia-8cb0b01a22a9f447/out/build/libskia.a
$ cd ..; git clone this: https://github.com/servo/skia
$ cd skia; cp ../servo/rust-toolchain .
~/src/rust/skia$ cargo build
   Compiling servo-skia v0.30000019.1 (file:///media/user/src/rust/skia)                                
   Compiling servo-fontconfig-sys v4.0.5                                                                        
   Compiling gleam v0.6.0                                                                                       
   Compiling glx v0.2.3                                                                                         
warning: unnecessary parentheses around function argument===========>  ] 36/37: servo-skia                      
  --> src/gl_rasterization_context_glx.rs:69:32
   |
69 |                             0, (self.gl_context.size.height - self.size.height),                           
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
   |
   = note: #[warn(unused_parens)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 8m 48s  
```

**Comment by traumschule** [comment]
also cargo build fails
```
~/src/rust/servo$ cargo build --verbose
       Fresh semver v0.1.20     
       Fresh unicode-xid v0.1.0       
       Fresh void v1.0.2          
       Fresh cc v1.0.5        
...
       Fresh libloading v0.5.0                                                                                  
       Fresh miniz-sys v0.1.10
       Fresh bzip2-sys v0.1.6
   Compiling backtrace-sys v0.1.16                                                                              
     Running `rustc --crate-name backtrace_sys /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=353ef7578da4af0c -C extra-filename=-353ef7578da4af0c --out-dir /media/user/src/rust/servo/target/debug/deps -L dependency=/media/user/src/rust/servo/target/debug/deps --extern libc=/media/user/src/rust/servo/target/debug/deps/liblibc-94d34418e73f7407.rlib --cap-lints allow -L native=/home/user/src/servo/target/debug/build/backtrace-sys-90cc97353b9d4757/out/.libs -l static=backtrace`
error: could not find native static library `backtrace`, perhaps an -L flag is missing?ce-sys                   

error: aborting due to previous error

error: Could not compile `backtrace-sys`.                                                                       

Caused by:
  process didn't exit successfully: `rustc --crate-name backtrace_sys /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=353ef7578da4af0c -C extra-filename=-353ef7578da4af0c --out-dir /media/user/src/rust/servo/target/debug/deps -L dependency=/media/user/src/rust/servo/target/debug/deps --extern libc=/media/user/src/rust/servo/target/debug/deps/liblibc-94d34418e73f7407.rlib --cap-lints allow -L native=/home/user/src/servo/target/debug/build/backtrace-sys-90cc97353b9d4757/out/.libs -l static=backtrace` (exit code: 101)

~/src/rust/servo$ find target -name libbacktrace.a
target/debug/build/backtrace-sys-90cc97353b9d4757/out/.libs/libbacktrace.a
target/release/build/backtrace-sys-ebd53df377d87fdf/out/.libs/libbacktrace.a
```

**Comment by traumschule** [comment]
@paulrouget: https://paste.debian.net/1037365

> $ ./mach build -v --release
>    Compiling servo-skia v0.30000019.0
>      Running `rustc --crate-name skia /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=15143bb2ed28d2cd -C extra-filename=-15143bb2ed28d2cd --out-dir /media/user/src/rust/servo/target/release/deps -L dependency=/media/user/src/rust/servo/target/release/deps --extern euclid=/media/user/src/rust/servo/target/release/deps/libeuclid-410f7d18128c2692.rlib --extern expat_sys=/media/user/src/rust/servo/target/release/deps/libexpat_sys-91614b503f0647ec.rlib --extern gleam=/media/user/src/rust/servo/target/release/deps/libgleam-3b2b2bdd6ad6823a.rlib --extern glx=/media/user/src/rust/servo/target/release/deps/libglx-ccc826f676d8a0e4.rlib --extern libc=/media/user/src/rust/servo/target/release/deps/liblibc-1fbe24e06f99300a.rlib --extern fontconfig_sys=/media/user/src/rust/servo/target/release/deps/libfontconfig_sys-9a64054aea59ee50.rlib --extern freetype_sys=/media/user/src/rust/servo/target/release/deps/libfreetype_sys-851685321b6a9f3c.rlib --extern x11=/media/user/src/rust/servo/target/release/deps/libx11-1a87064336022931.rlib --cap-lints allow -C link-args=-fuse-ld=gold -W unused-extern-crates -L native=/home/user/src/servo/target/release/build/servo-skia-8cb0b01a22a9f447/out/lib -l static=skia -l stdc++ -l bz2 -l GL -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu`
> error: could not find native static library `skia`, perhaps an -L flag is missing?
> 
> error: aborting due to previous error
> 
> error: Could not compile `servo-skia`.
> 
> Caused by:
>   process didn't exit successfully: `rustc --crate-name skia /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=15143bb2ed28d2cd -C extra-filename=-15143bb2ed28d2cd --out-dir /media/user/src/rust/servo/target/release/deps -L dependency=/media/user/src/rust/servo/target/release/deps --extern euclid=/media/user/src/rust/servo/target/release/deps/libeuclid-410f7d18128c2692.rlib --extern expat_sys=/media/user/src/rust/servo/target/release/deps/libexpat_sys-91614b503f0647ec.rlib --extern gleam=/media/user/src/rust/servo/target/release/deps/libgleam-3b2b2bdd6ad6823a.rlib --extern glx=/media/user/src/rust/servo/target/release/deps/libglx-ccc826f676d8a0e4.rlib --extern libc=/media/user/src/rust/servo/target/release/deps/liblibc-1fbe24e06f99300a.rlib --extern fontconfig_sys=/media/user/src/rust/servo/target/release/deps/libfontconfig_sys-9a64054aea59ee50.rlib --extern freetype_sys=/media/user/src/rust/servo/target/release/deps/libfreetype_sys-851685321b6a9f3c.rlib --extern x11=/media/user/src/rust/servo/target/release/deps/libx11-1a87064336022931.rlib --cap-lints allow -C link-args=-fuse-ld=gold -W unused-extern-crates -L native=/home/user/src/servo/target/release/build/servo-skia-8cb0b01a22a9f447/out/lib -l static=skia -l stdc++ -l bz2 -l GL -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu` (exit code: 101)
> rustup run --install nightly-2018-07-17 cargo build --release -v
> Build FAILED in 0:00:12
>

**Comment by paulrouget** [comment]
In your previous command, backtrace is missing.

Doesn't look like skia specific.

**Comment by traumschule** [comment]
now all in one: https://paste.debian.net/1037384/

**Comment by paulrouget** [comment]
Worth mentioning this is happening on a 32bit linux system.

**Comment by SimonSapin** [comment]
So `-L /path` is correctly passed with a directory that contains `libFOO.a`, but rustc says it doesn’t find it. I’d try reproducing by running rustc without cargo (copy the line from the output of `cargo build -v`) and then running `strace -e file rustc` (with the rest of arguments) what files its looking at. Also run `file` on those `.a` files to see if they’re in the expected format (for example containing x86 code and not x64).

**Comment by traumschule** [comment]
I broke it down, corrected the paths and got errors for skia's use
of unstable libc. all does it maybe fail to build and fail with a path
error because of this?

```
registry=~/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/lib.rs
euclid=target/release/deps/libeuclid-410f7d18128c2692.rlib
expat=~target/release/deps/libexpat_sys-91614b503f0647ec.rlib
gleam=target/release/deps/libgleam-3b2b2bdd6ad6823a.rlib
glx=target/release/deps/libglx-ccc826f676d8a0e4.rlib
libs=target/release/deps/liblibc-1fbe24e06f99300a.rlib
x11=target/release/deps/libx11-1a87064336022931.rlib
freetype=target/release/deps/libfreetype_sys-851685321b6a9f3c.rlib
fontconfig=target/release/deps/libfontconfig_sys-9a64054aea59ee50.rlib
out=~/src/rust/servo/target/release/deps
extern="--extern euclid=$euclid  --extern expat_sys=$expat --extern gleam=$gleam --extern glx=$glx --extern libc=$lib --extern fontconfig_sys=$fontconfig --extern freetype_sys=$freetype --extern x11=$x11"
options="--crate-name skia $registry --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=15143bb2ed28d2cd -C extra-filename=-15143bb2ed28d2cd --out-dir $out -L dependency=target/release/deps $extern --cap-lints allow -C link-args=-fuse-ld=gold -W unused-extern-crates -L native=target/release/build/servo-skia-8cb0b01a22a9f447/out/lib -l static=skia -l stdc++ -l bz2 -l GL -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu"

rustc $options
```

```
error[E0658]: use of unstable library feature 'libc': use `libc` from
crates.io (see issue #27783)
--> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/lib.rs:7:1
| 7 | extern crate libc; | ^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(libc)] to the crate attributes to
enable                                      

error[E0658]: use of unstable library feature 'libc': use `libc` from
crates.io (see issue #27783)
--> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/skia.rs:9:5
| 9 | use libc::*;
  |     ^^^^
  |
  = help: add #![feature(libc)] to the crate attributes to
enable                                               

error[E0658]: use of unstable library feature 'libc': use `libc` from
crates.io (see issue #27783)
--> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/skia.rs:11:34
| 11 | pub type SkiaGrContextRef = *mut c_void;
   |                                  ^^^^^^
   |
   = help: add #![feature(libc)] to the crate attributes to
enable                                              

error[E0658]: use of unstable library feature 'libc': use `libc` from
crates.io (see issue #27783)
--> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/skia.rs:12:40
| 12 | pub type SkiaGrGLInterfaceRef = *const c_void;
   |                                        ^^^^^^
   |
   = help: add #![feature(libc)] to the crate attributes to
enable                                              

error[E0658]: use of unstable library feature 'libc': use `libc` from
crates.io (see issue #27783)
--> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/skia.rs:19:91
| 19 | pub fn SkiaGrGLInterfaceHasExtension(anInterface:
SkiaGrGLInterfaceRef, extension: *const c_char) -> bool;
|
^^^^^^ | = help: add #![feature(libc)] to the crate attributes to
enable                                              

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
```

**Comment by SimonSapin** [comment]
The variable name in `--extern libc=$lib` does not match `libs=…`, so rustc doesn’t use the libc crate from crates.io and instead falls back on the private / instable copy of it distributed together with `std`.

**Comment by traumschule** [comment]
In each cases in the -L path the direct parent of the servo root is missing.

For 'cargo build' the failing command

> rustc --crate-name backtrace_sys /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=353ef7578da4af0c -C extra-filename=-353ef7578da4af0c --out-dir /home/user/src/rust/servo/target/debug/deps -L dependency=/home/user/src/rust/servo/target/debug/deps --extern libc=/home/user/src/rust/servo/target/debug/deps/liblibc-94d34418e73f7407.rlib --cap-lints allow -L native=/home/user/src/servo/target/debug/build/backtrace-sys-90cc97353b9d4757/out/.libs -l static=backtrace

has to be 

> rustc --crate-name backtrace_sys /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=353ef7578da4af0c -C extra-filename=-353ef7578da4af0c --out-dir /home/user/src/rust/servo/target/debug/deps -L dependency=/home/user/src/rust/servo/target/debug/deps --extern libc=/home/user/src/rust/servo/target/debug/deps/liblibc-94d34418e73f7407.rlib --cap-lints allow -L native=/home/user/src/servo/target/debug/build/backtrace-sys-90cc97353b9d4757/out/.libs -l static=backtrace

Difference:

`/home/user/src/rust/servo/target/debug/build/backtrace-sys-90cc97353b9d4757/out/.libs`
instead of
`/home/user/src/servo/target/debug/build/backtrace-sys-90cc97353b9d4757/out/.libs`

Same for './mach build -r '

> rustc --crate-name skia /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=15143bb2ed28d2cd -C extra-filename=-15143bb2ed28d2cd --out-dir /home/user//src/rust/servo/target/release/deps -L dependency=/home/user//src/rust/servo/target/release/deps --extern euclid=/home/user//src/rust/servo/target/release/deps/libeuclid-410f7d18128c2692.rlib --extern expat_sys=/home/user//src/rust/servo/target/release/deps/libexpat_sys-91614b503f0647ec.rlib --extern gleam=/home/user//src/rust/servo/target/release/deps/libgleam-3b2b2bdd6ad6823a.rlib --extern glx=/home/user//src/rust/servo/target/release/deps/libglx-ccc826f676d8a0e4.rlib --extern libc=/home/user//src/rust/servo/target/release/deps/liblibc-1fbe24e06f99300a.rlib --extern fontconfig_sys=/home/user//src/rust/servo/target/release/deps/libfontconfig_sys-9a64054aea59ee50.rlib --extern freetype_sys=/home/user//src/rust/servo/target/release/deps/libfreetype_sys-851685321b6a9f3c.rlib --extern x11=/home/user//src/rust/servo/target/release/deps/libx11-1a87064336022931.rlib --cap-lints allow -C link-args=-fuse-ld=gold -W unused-extern-crates -L native=/home/user/src/servo/target/release/build/servo-skia-8cb0b01a22a9f447/out/lib -l static=skia -l stdc++ -l bz2 -l GL -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu

`/home/user/src/rust/servo/target/release/build/servo-skia-8cb0b01a22a9f447/out/lib`
instead of
`/home/user/src/servo/target/release/build/servo-skia-8cb0b01a22a9f447/out/lib`

(search for `rust/servo` to see where it is missing)

**Comment by dralley** [comment]
Skia is dead
