### ISSUE TITLE
Add a mach command to run rustfmt

### ISSUE THREAD

**Issue by jdm** [servo/servo#21374]
To make it easy to accomplish #21373, we need to make it easy to run the version of rustfmt that is part of the pinned version of rustc that Servo's build system uses. I propose a new rustfmt command added to `python/servo/devenv_commands.py` which runs `cargo fmt` on a directory provided as a command argument. We will also need to add the rustfmt preview to the pinned Rust toolchain that Servo uses (via `rustup component add rustfmt-preview --toolchain [...]`) ([docs](https://github.com/rust-lang-nursery/rustfmt#installation)).

Looks for uses of rustup in other files like `python/servo/build_commands.rs` for the recommended way to use our pinned toolchain.

**Comment by JoshBrudnak** [comment]
Hi, I would like to work on this issue, @highfive: assign me
