### ISSUE TITLE
Investigate GStreamer-based WebRTC

### ISSUE THREAD

**Issue by jdm** [servo/servo#21396]
This issue will collect all of the resources that I come across when researching whether this is the right fit for Servo's needs.

**Comment by jdm** [comment]
https://gstreamer.freedesktop.org/data/events/gstreamer-conference/2017/Matthew%20Waters%20-%20GStreamer%20WebRTC.pdf
https://webengineshackfest.org/2018/#talkModalAlexYouenn
http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html
https://github.com/centricular/gstwebrtc-demos/
https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/tests/examples/webrtc
https://developer.ridgerun.com/wiki/index.php?title=GstWebRTC_-_Building_GstWebRTC
https://twitter.com/sdroege_/status/981957825072173056

**Comment by jdm** [comment]
https://github.com/centricular/gstwebrtc-demos/issues/4

**Comment by ferjm** [comment]
https://github.com/centricular/gstwebrtc-demos/tree/master/sendrecv/gst-rust

**Comment by jdm** [comment]
https://github.com/ystreet/gst-plugins-bad/pull/5

**Comment by jdm** [comment]
Homebrew on macOS requires `brew install gst-plugins-bad --with-libnice --with-srt`.

**Comment by ferjm** [comment]
https://github.com/Manishearth/media-capture

**Comment by jdm** [comment]
The experiments were merged into master, so we can file more specific issues about missing pieces now.
