### ISSUE TITLE
debug! messages don't show up in logcat. warn! and info! do.

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21390]

**Comment by SimonSapin** [comment]
Maybe the `max_log_level` feature flag is relevant?

**Comment by paulrouget** [comment]
Rust debug is translated into a Android debug log. And from https://developer.android.com/reference/android/util/Log: "Debug logs are compiled in but stripped at runtime. Error, warning and info logs are always kept."

This only happens with a release build.

**Comment by paulrouget** [comment]
@SimonSapin that makes sense. So I guess we want to keep that behavior. I'll be using `info!` more: #21391
