### ISSUE TITLE
Host prebuilt servo binaries

### ISSUE THREAD

**Issue by cgjones** [servo/servo#2139]
Not particularly high priority while in prerelease state, but the servo build isn't particularly fast, and for users like me who want to use servo for something other than servo development, prebuilt binaries would be very convenient.  (Especially as I just realized I built servo for the wrong architecture and have to start over ...)

**Comment by movEAX** [comment]
+1

**Comment by larsbergstrom** [comment]
We currently build and host an Android nightly build. By the end of 2015, we expect to have some more stable Alpha builds (see https://github.com/servo/servo/wiki/Roadmap) and may publish builds at that time. Until we have an upgraded SpiderMonkey in place, though, we are reluctant to provide binaries for a web browser with a JS engine that is missing over 2 years of security fixes!

**Comment by alex** [comment]
I believe this can be closed now?

**Comment by aneeshusa** [comment]
Nightly builds are now available at https://download.servo.org/.
