### ISSUE TITLE
Pressing the Android back button should call servo.goBack instead of hiding the app

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21401]
… and if we can't go back, it should hide the app.

**Comment by paulrouget** [comment]
All that needs to be done here is to override [`onBackPressed`](https://developer.android.com/reference/android/app/Activity#onBackPressed()), and call `mServoView.goBack` if we can go back (see `onHistoryChanged`) or `super.onBackPressed` if we can't.

**Comment by carloabelli** [comment]
I'll try this out.

@highfive: assign me

**Comment by paulrouget** [comment]
@carloabelli you might want to look at this: https://github.com/servo/servo/wiki/Building-for-Android#working-on-the-user-interface-without-building-servo

**Comment by paulrouget** [comment]
@carloabelli did you select the build variant "mainArmv7Debug"?

**Comment by paulrouget** [comment]
@carloabelli it looks like `:servoview` is being built, not `:servoview-local`? Does Android Studio shows servoview or servoview-local in the sidebar?

**Comment by paulrouget** [comment]
also, make sure to checkout the latest version of servo.

**Comment by paulrouget** [comment]
I've updated the instructions for the command line builds: https://github.com/servo/servo/wiki/Building-for-Android#working-on-the-user-interface-without-building-servo

**Comment by carloabelli** [comment]
Okay I will try building it again tonight using the new command line instructions. I'll also make sure to get the lastest version
