### ISSUE TITLE
Build fails on macOS since gstreamer addition

### ISSUE THREAD

**Issue by cadeyrn** [servo/servo#21423]
Similar to #21418, but for macOS since the other issue is already closed.

error: failed to run custom build command for `gstreamer-sys v0.5.0`
process didn't exit successfully: `/Users/cadeyrn/localhost/servo/target/release/build/gstreamer-sys-d446d77d0aaad3cc/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gstreamer-1.0 >= 1.12"` did not exit successfully: exit code: 1
--- stderr
Package gstreamer-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-1.0' found

**Comment by jdm** [comment]
#21422 updates the readme to include homebrew instructions.

**Comment by jdm** [comment]
@kingdido999 That's strange, since gstreamer-video should be part of the dependencies installed by the full command in #21422 per https://github.com/Homebrew/homebrew-core/issues/20014 :/

**Comment by cadeyrn** [comment]
For me it worked with the instructions in #21422 (macOS Mojave Public Beta).

**Comment by kingdido999** [comment]
It works now after I redo the brew install.
