### ISSUE TITLE
Zooming a page with text is very slow and rendering is wrong

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21432]
Requires https://github.com/servo/servo/pull/21431

Here I'm zooming on `<p>foo</p>`.
On a more complex page, servo appears to freeze. Zooming too much also appears to freeze.

![screenshot_20180816-065625](https://user-images.githubusercontent.com/373579/44207149-62b6a400-a15c-11e8-9f8d-cf419e55523d.png)

**Comment by NiLSPACE** [comment]
#21100 is also still an issue.

**Comment by paulrouget** [comment]
Can't reproduce anymore.
