### ISSUE TITLE
Travis-CI config for GStreamer dependency

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#21443]
@ferjm Is it really necessary to build gstreamer from source like you do in https://github.com/servo/servo/pull/21158 in order to be able to build Servo on Travis-CI? Adding dependencies per README in https://github.com/servo/servo-with-rust-nightly/commit/91c90e4d94cc233fa7d5ed13c5ab06eae1eb1158 didn’t work: https://travis-ci.org/servo/servo-with-rust-nightly/jobs/416837548

**Comment by SimonSapin** [comment]
Ah sorry, I didn’t pay enough attention to the error message beyond "it’s pkg-config"

> Requested 'gstreamer-1.0 >= 1.12' but version of GStreamer is 1.2.4

So GStreamer is found, but not a recent enough version. What would it take to support older versions?

**Comment by jdm** [comment]
The restriction about versions comes from https://github.com/sdroege/gstreamer-rs/#linuxbsds.

**Comment by ferjm** [comment]
It seems that this was already fixed in https://github.com/servo/servo-with-rust-nightly/commit/1ada6173e621ddcc80f9cc3a28354a160079d3e5 , so I am closing this issue. Please, reopen if you still think it's valid.

**Comment by SimonSapin** [comment]
I fixed the immediate build failures by copying the config in this repo, but downloading a random tarball still doesn’t feel like a satisfying solution. Hopefully we’ll figure out something better at some point.
