### ISSUE TITLE
Download linux gstreamer binaries during mach build

### ISSUE THREAD

**Issue by jdm** [servo/servo#21446]
Telling people to execute [these steps](https://github.com/servo/servo/blob/master/.travis.yml#L20-L22) manually isn't a great solution if their distribution doesn't have a recent gstreamer available. It would be nice if we could make it Just Work by downloading those binaries automatically, similar to the way we acquire openssl for android builds.

**Comment by paddywwoof** [comment]
until this is fixed 'someone' should modify the install instructions https://github.com/servo/servo#on-debian-based-linuxes

**Comment by PsiACE** [comment]
I think we can at least add it correctly to https://github.com/servo/servo#other-dependencies first. Take `Fedora` as an example, add gstreamer to the given `dnf install` directive.

Updated instructions:
```
sudo dnf install curl libtool gcc-c++ libXi-devel \
    freetype-devel mesa-libGL-devel mesa-libEGL-devel glib2-devel libX11-devel libXrandr-devel gperf \
    fontconfig-devel cabextract ttmkfdir python python-virtualenv python-pip expat-devel \
    rpm-build openssl-devel cmake bzip2-devel libXcursor-devel libXmu-devel mesa-libOSMesa-devel \
    dbus-devel ncurses-devel harfbuzz-devel ccache mesa-libGLU-devel clang clang-libs gstreamer
```

This does not completely avoid compile-time problems, but it can reduce the number of interrupts.

**Comment by jdm** [comment]
Could you make a pull request with that change, please?

**Comment by PsiACE** [comment]
ok

**Comment by PsiACE** [comment]
Sorry, I shouldn't have referenced it in PR, and now it's been turned off by mistake.
