### ISSUE TITLE
Release selectors update

### ISSUE THREAD

**Issue by kpcyrd** [servo/servo#21455]
hey!

while preparing kuchiki for debian I've noticed it's still depending on cssparser 0.23. I've tried to prepare a patch but noticed cssparser 0.24.0 is incompatible with selectors 0.19.0. Could you release an update for selectors?

Thanks :)

**Comment by SimonSapin** [comment]
Out of curiosity, what in Debian uses Kuchiki?

**Comment by kpcyrd** [comment]
@SimonSapin There is nothing in debian yet, but I'm working towards packaging all dependencies of [badtouch] which uses kuchiki to process html.

[badtouch]: https://github.com/kpcyrd/badtouch

**Comment by SimonSapin** [comment]
I’ve published https://crates.io/crates/selectors/0.20.0 and https://crates.io/crates/kuchiki/0.7.1.

https://github.com/servo/servo/pull/21494 will close this issue but still needs to go through CI. (I didn’t wait because it only increments the version number.)

**Comment by kpcyrd** [comment]
Awesome, thank you!
