### ISSUE TITLE
Zoom keybindings don't work on Mac

### ISSUE THREAD

**Issue by cdisselkoen** [servo/servo#21457]
The [README](https://github.com/servo/servo/blob/master/README.md) indicates that `Ctrl`+`-` zooms out and `Ctrl`+`=` zooms in.  On Mac, I couldn't get these shortcuts to work at all; I tried each of `Ctrl`, `Opt`, and `Cmd` with `-` and `=` on a couple different webpages.  (I haven't tested on other OSes; maybe this problem is specific to Mac, or maybe the zoom keybindings are actually broken everywhere.)

N.B. edit 8/20/18: Not all `Cmd` key shortcuts are broken - for instance, `Cmd`+`left arrow` and `Cmd`+`right arrow` work properly on my machine.

**Comment by atouchet** [comment]
Apparently there was [a bug related to the Cmd key input in Winit](https://github.com/tomaka/winit/blob/master/CHANGELOG.md#version-0172-2018-08-19). Maybe updating to Winit 0.17.2 would help fix this.

**Comment by paulrouget** [comment]
> Maybe updating to Winit 0.17.2 would help fix this.

Tried. Doesn't work.
