### ISSUE TITLE
Read file URLs in chunks

### ISSUE THREAD

**Issue by jdm** [servo/servo#21466]
The code to [read from file URLs](https://github.com/servo/servo/blob/master/components/net/fetch/methods.rs#L483-L506) uses read_to_end to consume the entire file buffer and send it back all at once. This means the behaviour of HTTP URLs and file URLs for large files is very different.

**Comment by JacksonCoder** [comment]
I would like to work on this issue, if possible. Just to be clear, the goal is to read the file in chunks, rather than in one go?

**Comment by KiChjang** [comment]
@JacksonCoder This may be a little bit more involved. We should be using the [FetchTaskTarget](https://github.com/servo/servo/blob/99099d860d205ce52b6e885fa5d8bdfac65e4a59/components/net_traits/lib.rs#L162) as the destination for the result of the file read, calling `process_response_chunk` when necessary. You can take a look at [Step 20 of main_fetch](https://github.com/servo/servo/blob/fd64f11efe0f3d5e4cf6a906389217a7853aba4c/components/net/fetch/methods.rs#L377) for more inspiration of how you can do so.

**Comment by JacksonCoder** [comment]
Since we're returning the contents of the entire file in the `ResponseBody`, how would reading the file in chunks improve memory usage? (which is what I assume is the goal of reading it in chunks)

**Comment by jdm** [comment]
The goal is not necessarily about reducing overall memory usage, but making the behaviour match for consumers of the network response - right now, users of the file protocol will observe a single process_response_chunk message that contains the entire file. This means that any code that can deal with incremental responses (like the HTML parser) don't get any chance to make use of the incomplete body.

**Comment by JacksonCoder** [comment]
I see. So I should incrementally read the file in chunks and call `process_response_chunk` with each chunk on the `FetchTaskTarget` instance?

**Comment by JacksonCoder** [comment]
What should the ideal size be for each chunk?

**Comment by jdm** [comment]
I would try 32kb.

**Comment by JacksonCoder** [comment]
Alright, I pushed my code to [my local fork](https://github.com/JacksonCoder/servo/tree/chunk-file), under the `chunk-file` branch.

**Comment by JacksonCoder** [comment]
Should I modify tests, or just make a PR?

**Comment by jdm** [comment]
I don't think there are any tests that could observe this.
