### ISSUE TITLE
Can GetPropertyKeys fail?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#21462]
In https://github.com/servo/servo/blob/d34403047e806fa6c8c2468946f64429622ec434/components/script/dom/bindings/mozmap.rs#L61 we assert that GetPropertyKeys cannot fail. It does so if there are duplicate keys in the object, we should check to see if we ever introduce duplicates.

**Comment by saschanaz** [comment]
Currently it fails in https://w3c-test.org/fetch/api/headers/headers-record.html:

>[2019-10-12T09:50:48Z ERROR script::dom::bindings::error] Error at https://w3c-test.org/fetch/api/headers/headers-record.html:22:27 proxy [[OwnPropertyKeys]] can't report property '"a"' more 
than once

**Comment by saschanaz** [comment]
Proxies can report duplicated keys and cause errors as seen here:

https://github.com/servo/servo/blob/1f531f66ea9d1ecb33cadb2ad6442673b016907a/tests/wpt/web-platform-tests/fetch/api/headers/headers-record.html#L250-L260

This behavior is being properly tested so I think this can be closed now.

**Comment by jdm** [comment]
Thanks for checking!
