### ISSUE TITLE
Read blob URLs in chunks

### ISSUE THREAD

**Issue by jdm** [servo/servo#21467]
The code to [read from blob URLs](https://github.com/servo/servo/blob/master/components/net/fetch/methods.rs#L483-L506) uses load_blob_sync to consume the entire response buffer and send it back all at once. This means the behaviour of HTTP URLs and blob URLs for large files is very different.

**Comment by ms2300** [comment]
Can I take this on? Anything more I should know?

**Comment by jdm** [comment]
No, I filed it separately from #21466 for a reason, since you will need to use a different method for chunkin the blob bodies than the file bodies. And yes, please do :)

**Comment by ms2300** [comment]
Ahh ok, I'll let you know if I have any more questions.

**Comment by ms2300** [comment]
So I think I have the changes (in concept at least) done but am having trouble getting the mach system to build correctly. This is true both for the current master and my own branch, any help would be really appreciated.

Trace:
`
--- stderr
error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later), err: true
thread 'main' panicked at 'Should generate JSAPI bindings OK: ()', libcore/result.rs:983:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`

**Comment by jdm** [comment]
Ah, that's https://github.com/servo/servo/issues/21498 and you can try the solutions described in that issue.

**Comment by ms2300** [comment]
I just opened a pr for this ticket and am looking for feedback b/c this is most likely not the perfect way to attack the problem (I'm worried I'm not fully understanding what exactly needs to be done)

**Comment by jdm** [comment]
#21467 was a good start at addressing this issue. I left some review comments on it that any further attempt should follow.
