### ISSUE TITLE
Can jsid_to_string fail?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#21463]
In https://github.com/servo/servo/blob/d34403047e806fa6c8c2468946f64429622ec434/components/script/dom/bindings/mozmap.rs#L77 we assert that jsid_to_string is guaranteed to succeed. Is this true?

**Comment by jdm** [comment]
js_to_string returns None if the argument is a [symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) or void/empty.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/20318/ improves the situation a bit by following Gecko's path of converting the jsid to a value, but it also unwraps the from_id operation.
