### ISSUE TITLE
Implement LenientFloat WebIDL attribute

### ISSUE THREAD

**Issue by jdm** [servo/servo#2149]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=19988

Requires porting support from Gecko, both in [WebIDL.py](http://mxr.mozilla.org/mozilla-central/source/dom/bindings/parser/WebIDL.py) and [Codegen.py](http://mxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py)

**Comment by nox** [comment]
The actual interesting part is to write the specification for LenientFloat and submit that upstream, no?

**Comment by mrobinson** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=19988 is closed as WONTFIX and the version of WebIDL.py that we have does have support for `LenientFloat`, so I think this can be closed.
