### ISSUE TITLE
Fetch Worker Pool

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21491]
Would it make sense to replace this "inline" thread:

https://github.com/servo/servo/blob/544f73a9fb82c6a050b6032ed15e470354a6df47/components/net/http_loader.rs#L1110

With one, or a pool of, dedicated threads that would be receiving messages sent from `http_network_fetch`containing the stuff that is currently "moved" into the above thread spawned inline? 

Such a channel would effectively act as a queue of work for the fetch worker(s).

Perhaps it would a nice thing to do once https://github.com/servo/servo/pull/21325 merges, since `crossbeam-channel` would enable a setup with multiple receivers(one for each "fetch worker") that would ensure fair distribution of work?

**Comment by jdm** [comment]
Yes, limiting the total number of connections by creating a pool would be sensible.

**Comment by gterzian** [comment]
This seems to have happened in the meantime

https://github.com/servo/servo/blob/5bdea7dc1c80790a852a3fb03edfb2b8fbd403dc/components/net/http_loader.rs#L1286
