### ISSUE TITLE
Mozjs error

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21498]
`error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)`
`thread 'main' panicked at 'Should generate JSAPI bindings OK: ()', libcore/result.rs:945:5`

While compiling on OS X 10.13. 

Is a manual flag necessary?

**Comment by jdm** [comment]
This should have been fixed by https://github.com/servo/servo/pull/21470. Do you have the most recent version from master?

**Comment by gterzian** [comment]
Yes, this actually started happening after a rebase from master about an hour ago...

**Comment by gterzian** [comment]
Let me double check, I think I might have messed with something in `Cargo.lock`...

**Comment by gterzian** [comment]
It persists, I'm building this branch https://github.com/servo/servo/pull/21325 exactly as it is(rebased off master)

**Comment by gterzian** [comment]
Yet it also happens if I build directly from master, so it's unrelated to that branch...

**Comment by jdm** [comment]
You may need to update the version of llvm that you have installed? And possibly remove the old one?

**Comment by gterzian** [comment]
Ok, it's working now. What I did:
1. `brew install llvm`
2. `export LDFLAGS="-L/usr/local/opt/llvm/lib"` and `export CPPFLAGS="-I/usr/local/opt/llvm/include"`

I guess it will depend on what installed on people's machine to begin with...

**Comment by CYBAI** [comment]
I ran into the same issue and @gterzian 's solution saved my day! Thanks!

I can compile successfully after doing following three commands.

```sh
$ brew install llvm
$ export LDFLAGS="-L/usr/local/opt/llvm/lib"
$ export CPPFLAGS="-I/usr/local/opt/llvm/include"
```

**Comment by asajeffrey** [comment]
Just `brew install llvm` was good enough to fix it for me.

**Comment by syniuhin** [comment]
should we update https://github.com/servo/servo#on-macos-homebrew to reflect the `llvm` requirement? I also experienced this error on a fresh osx install.

**Comment by asajeffrey** [comment]
@syniuhin yes please!
