### ISSUE TITLE
Android: properly set the pixel density

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21504]
As of now, the pixel density is hard coded: https://github.com/servo/servo/blob/3d99288f2089af3ecb24825ad23b79932a29fdb6/ports/libsimpleservo/src/api.rs#L468

The same way we set the width and height of the window, we should set the density as an `init` parameter.

I think we can use this Android API to get the proper density: https://developer.android.com/reference/android/util/DisplayMetrics

**Comment by wizofe** [comment]
@highfive: assign me 
thanks mate ^_^

**Comment by paulrouget** [comment]
@wizofe let me know if you need help :)

**Comment by wizofe** [comment]
@paulrouget I may need indeed. So, if I understand correctly, I need to add/initialise a new variable on the [init](https://github.com/servo/servo/blob/3d99288f2089af3ecb24825ad23b79932a29fdb6/ports/libsimpleservo/src/api.rs#L95).

Now, how can I use the Android API? Is there any way to access the DisplayMetrics object or should I create one on my own? Step by step is appreciated :) 

Thanks for your time and help.

**Comment by paulrouget** [comment]
To compile for Android, please look at this: https://github.com/servo/servo

First thing you need is to retrieve the pixel density in Java (see the link in the first comment) in https://github.com/servo/servo/blob/master/support/android/apk/servoview/src/main/java/com/mozilla/servoview/ServoView.java - in onGLReady, pass the density along the width and height. You will need to update the constructor in Servo.java to accept the density and pass it to init. The init function is described in JNIServo.java. You will need to add an argument there as well. 

At that point, the java code should compile.

But it will crash when running servo because the rust code is not accepting the density yet.

For the rust code, the first step is to add a density argument to the init function here: https://github.com/servo/servo/blob/master/ports/libsimpleservo/src/jniapi.rs and then to https://github.com/servo/servo/blob/master/ports/libsimpleservo/src/api.rs 

In api.rs just do exactly what we do for with and height, but for the density. And replace the 2.0 value with the actual density.

At that point, once everything compiles, it should work. 

Let me know if you need more details.

**Comment by paulrouget** [comment]
> Now, how can I use the Android API?

```java
 DisplayMetrics metrics = new DisplayMetrics();
 getWindowManager().getDefaultDisplay().getMetrics(metrics);
 float density = metrics.density;
 // Pass `density` to `new Servo()` in onGLReady
```

**Comment by paulrouget** [comment]
Note to self: this should be only be done for the servoview, not the servosurface.

**Comment by paulrouget** [comment]
@wizofe did you get a chance to look at this?
