### ISSUE TITLE
Add autoconf 2.13  for Fedora

### ISSUE THREAD

**Issue by PsiACE** [servo/servo#21512]
Some versions of Fedora for x86_64(E.g Fedora 28) may not support autoconf 2.13.

Add some instructions to Readme.md to improve this situation.

**Comment by jdm** [comment]
https://www.rpmfind.net/linux/rpm2html/search.php?query=%2Fusr%2Fbin%2Fautoconf-2.13 shows noarch packages for Fedora 28; are you positive it's not available to you? Specifically: https://www.rpmfind.net/linux/RPM/fedora/28/x86_64/a/autoconf213-2.13-39.fc28.noarch.html

**Comment by PsiACE** [comment]
@jdm I will try some more because there seems to be some conflict. But at least adding to README.md makes the process painless.
