### ISSUE TITLE
Implement ChannelSplitterNode and ChannelMergerNode

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#21558]
servo-media already has support for these, we just need to add the DOM APIs.

There's a bunch of bounds checking for parameters that needs to be done here, but otherwise it should be straightforward.

I intend to implement these, but others should feel free to pick it up, it's not that hard (and I can mentor)

**Comment by KMLDS** [comment]
I'm interested in doing this (and the mentoring)!

**Comment by Manishearth** [comment]
Alright, so you'll probably want to work on one at a time.

First, have a look at the files for [GainNode.webidl](https://github.com/servo/servo/blob/master/components/script/dom/webidls/GainNode.webidl) and [gainnode.rs](https://github.com/servo/servo/blob/master/components/script/dom/gainnode.rs)

We need to add a channelsplitternode.rs module (be sure to update the mod.rs file!), and ChannelSplitterNode.webidl. The webidl file will basically look like GainNode.webidl but contain the ChannelSplitterNode/ChannelSplitterOptions definitions from https://webaudio.github.io/web-audio-api/#channelsplitternode

What's going to be different is:

 - ChannelSplitterNode doesn't have any AudioParams (GainNode has a `gain` parameter), so all the audioparam stuff can go away
 - You'll be constructing it with a [ChannelNodeOptions type](http://doc.servo.org/servo_media_audio/channel_node/struct.ChannelNodeOptions.html)
 - There are additional constraints you'll have to implement, but I'll wait till you have a pull request open for ChannelSplitterNode before explaining this.

That should mostly be it! ChannelMergerNode is basically the same thing again.

Let me know if you have questions.
 -

**Comment by KMLDS** [comment]
Thanks!  I'll dig in over the next couple of days and get back to you with questions as needed when I've had a chance to think through next steps.

**Comment by collares** [comment]
I would like to work on this! I will try to follow @Manishearth's comment.
