### ISSUE TITLE
"No space left on device" on Travis CI

### ISSUE THREAD

**Issue by gterzian** [servo/servo#21592]
https://travis-ci.org/servo/servo/jobs/423909479#L2137

Seems to happen consistently with the last few commits on https://github.com/servo/servo/pull/21583

**Comment by gterzian** [comment]
Although I guess there is not much we can do about it, other than sending them a support ticket, unless this relates to a mis-configuration of the yaml file...

**Comment by SimonSapin** [comment]
Removing caches might help for a bit, but the same might happen again later.

**Comment by gterzian** [comment]
This [issue](https://github.com/travis-ci/travis-ci/issues/8902), seemingly quite similar, referred to this as the solution https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959

**Comment by tigercosmos** [comment]
`./mach clean-cargo-cache --keep 2 --force` change to keep `1`might help a little bit?

**Comment by gterzian** [comment]
Thanks, I just gave it a try on https://github.com/servo/servo/pull/21594

**Comment by gterzian** [comment]
Doesn't seem to have had the desired effect https://travis-ci.org/servo/servo/jobs/424604312#L2122

**Comment by gterzian** [comment]
@tigercosmos thanks, I've just tried following the instructions in the FAQ in #21594
