### ISSUE TITLE
Websocket related tasks should be using a dedicated task source `websocket-task-source`

### ISSUE THREAD

**Issue by AgustinCB** [servo/servo#21590]
See [this change](https://github.com/servo/servo/pull/21583/files#diff-c13bae09b178a30151ecebdc13c30a26R271). Instead of `Networking`, we should be using a new [TaskSourceName](https://github.com/servo/servo/blob/eb6aec37e9bde5aba2a3dc6b6ce5374579219f31/components/script/task_source/mod.rs#L24) referring to `websocket-task-source`.

**Comment by gterzian** [comment]
@AgustinCB Sorry I might have pointed you in the wrong direction with https://github.com/servo/servo/issues/21589, see https://github.com/servo/servo/pull/21609#issuecomment-418579585

However I think this one is likely to be less "controversial" :)

In implementing this task-source, it would be useful to look at all the places in the spec referencing  https://html.spec.whatwg.org/multipage/web-sockets.html#websocket-task-source and ensuring the new task-source is used in the corresponding places in the Servo codebase.

Note that while this new task-source is likely to be a mostly cosmetic change at this stage, it does provide infrastructure to differentiate between the handling of networking and websocket tasks, which could prove useful to implement parts of the spec that require it(I'm not sure which parts, but the fact that a dedicated task-source has been specified would point to it being useful in a few  places at least).

@jdm could you please confirm that it would indeed be useful to do this at this stage?

**Comment by jdm** [comment]
Yes, getting the right task sources for the websocket code would be useful!

**Comment by AgustinCB** [comment]
Will probably finish the pr this weekend.
