### ISSUE TITLE
Implement media element event task source

### ISSUE THREAD

**Issue by ferjm** [servo/servo#21612]
To be used [here](https://github.com/servo/servo/blob/master/components/script/dom/htmlmediaelement.rs#L53)

https://html.spec.whatwg.org/multipage/media.html#media-element-event-task-source

**Comment by chansuke** [comment]
@ferjm I'm interested in this

**Comment by ferjm** [comment]
Great!

There's a very recent implementation of another event task source in #21609 that you can take as an example for the media element one.

If I am not wrong, what you need to do here is to:

- Add a new `media_element.rs` file to https://github.com/servo/servo/blob/master/components/script/task_source that implements the `TaskSource` [trait](https://github.com/servo/servo/blob/master/components/script/task_source/mod.rs#L40).

- Make use of the new task source in the [media element implementation](https://github.com/servo/servo/blob/master/components/script/dom/htmlmediaelement.rs). We are currently using the [DOM manipulation task source](https://github.com/servo/servo/blob/master/components/script/dom/htmlmediaelement.rs#L53) as a temporary replacement for this, so you can search for that in the code. Please, make sure that you are not removing any valid usage of the DOM manipulation task source by checking in the [spec](https://html.spec.whatwg.org/multipage/media.html) if the usage of the media element event task source is expected for each case.

Feel free to ask for any extra clarification or if you need any other help. Thanks for working on this! :)

**Comment by chansuke** [comment]
@ferjm Thanks!! I'll check these docs first:-)

**Comment by ferjm** [comment]
@chansuke how are things going here? Please, let me know if you need any assistance.

**Comment by ferjm** [comment]
The spec related to task queues and task sources in general is [here](https://html.spec.whatwg.org/multipage/webappapis.html#task-queue). And while it's a very nice background to have, I wouldn't worry too much about all those details for the purpose of this issue.

I think the implementation of `TaskSource` for the `MediaElementTaskSource` should look pretty much like the one for the [`DOMManipulationTaskSource`](https://github.com/servo/servo/blob/master/components/script/task_source/dom_manipulation.rs#L29). You can probably derive `Clone` like [here](https://github.com/servo/servo/blob/master/components/script/task_source/dom_manipulation.rs#L20). After implementing `TaskSource` you'll need to expose a way for consumers to [queue simple events](https://github.com/servo/servo/blob/master/components/script/task_source/dom_manipulation.rs#L65). You will also need to [add the new task source to the global Window](https://github.com/servo/servo/blob/master/components/script/dom/window.rs#L176) and expose a way to [get the task source](https://github.com/servo/servo/blob/master/components/script/dom/window.rs#L355).
