### ISSUE TITLE
Only mark canvas as dirty when no framebuffer is bound

### ISSUE THREAD

**Issue by jdm** [servo/servo#21691]
Per a later paragraph in https://www.khronos.org/registry/webgl/specs/latest/1.0/#2.2, we should only be presenting the webgl canvas when the default framebuffer is bound. For Servo, that means that the canvas object should not be marked dirty if there is no bound framebuffer.

**Comment by sumit0190** [comment]
@jdm Would it make sense then to redefine `mark_as_dirty` so that it checks `self.bound_framebuffer` each time, and does nothing if the `get` call returns `None`?
(Sorry if that made no sense, still trying to understand everything).

**Comment by jdm** [comment]
That seems like a good idea!

**Comment by sumit0190** [comment]
I can see a bunch of weird things with the tests - a few that should've passed failed and vice-versa - and I am only halfway done with the entire suite. This will take a while...
