### ISSUE TITLE
Constellation::load_url private browsing mode propagation to new pipeline

### ISSUE THREAD

**Issue by mandreyel** [servo/servo#21706]
Noticed [here](https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L2158-L2160) that the `is_private` property of a browsing context is not passed to a new pipeline when loading a new URL, and instead a default `false` value is used, which will [cause](https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L735-L739) `Constellation` to give `Pipeline` the public resource thread instead of the private one. Am I right in assuming this is a bug?

**Comment by paulrouget** [comment]
Sounds like it.

Maybe `new_pipeline` should not take a `is_private` parameter and select the resource thread based on the privacy of the top level browsing context. Same goes for `handle_script_new_iframe` and `BrowsingContext::new`.

**Comment by mandreyel** [comment]
@paulrouget I don't think this will work, because e.g. in `handle_new_top_level_browsing_context` or even `handle_script_new_iframe` the browsing context for the pipeline doesn't exist yet, so we can't use its `is_visible` field (since the visibility is now stored in `BrowsingContext` rather than `Pipeline` since #21559). Or have I misunderstood?
In either case, I'll land a PR soon with a minor fix, and we can go from there.

@highfive assign me
