### ISSUE TITLE
Windows nightly builds missing from http://servo-builds.s3.amazonaws.com since 2018-09-05

### ISSUE THREAD

**Issue by atouchet** [servo/servo#21709]
http://servo-builds.s3.amazonaws.com/?list-type=2&prefix=nightly/windows-msvc/

The latest version listed here is from 2018-09-05. Is there something going wrong here?

**Comment by jdm** [comment]
The default s3 index has a limited number of results. http://servo-builds.s3.amazonaws.com/?list-type=2&prefix=nightly/windows-msvc/2018-09 shows that we are uploading builds correctly, but we generate exes instead of mailing files now.

**Comment by ferjm** [comment]
I am not sure of what failed there, but I just downloaded https://download.servo.org/nightly/windows-msvc/servo-latest.msi (~92MB) and it is definitely not the bundle containing the GStreamer and Servo installers (~172MB).

**Comment by jdm** [comment]
Yes, the link to servo-latest.msi will only point at the last MSI generated; we need to replace the website link with one to servo-latest.exe now.

**Comment by atouchet** [comment]
Alright, I guess this is fine to close now then.
