### ISSUE TITLE
`WindowOrWorkerGlobalScope` webidl need update

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#21727]
`WindowOrWorkerGlobalScope` miss the following now
```
 // microtask queuing
  void queueMicrotask(VoidFunction callback);
```

see: https://html.spec.whatwg.org/multipage/webappapis.html#timerhandler

Besides some functions in `WindowOrWorkerGlobalScope` are not supported yet, which is #20700

**Comment by CYBAI** [comment]
Is this kind of duplicate with #21574 ?

**Comment by tigercosmos** [comment]
not really. one is webidl, and one is the function implementation.
but I thought combine these to one issue would be better. :)

**Comment by tigercosmos** [comment]
combine to #21574.

**Comment by CYBAI** [comment]
@tigercosmos When we'd like to implement the method, we must need to update `webidl` so I think it would be same issue. But anyway, let me update the description in #21574 for `webidl`.
