### ISSUE TITLE
Missing text in Servo Windows installer

### ISSUE THREAD

**Issue by atouchet** [servo/servo#21720]
This window comes up when trying to install Servo for Windows:

![Installer](https://i.imgur.com/hOBAH5H.png)

Presumably there is supposed to be some proper text here.

**Comment by MeFisto94** [comment]
"Bumping" as this is still the case. It's probably a simple change, but someone needs to point out what the Agreement should exactly be.

**Comment by jlin** [comment]
I tried installing today and this still exists, 

I'm not sure if the answer is as simple as "put the text from [LICENSE](https://github.com/servo/servo/blob/main/LICENSE) into this box"

I'll put a little bit of time into finding out what the Mac installer does and see if there is already some kind of preferred text to put in there.

**Comment by shakna-israel** [comment]
Still present today.

**Comment by atouchet** [comment]
I think this page may have the relevant info: https://wixtoolset.org/docs/v3/bundle/wixstdba/wixstdba_license/

I will see if I can finally get this working properly.

**Comment by atouchet** [comment]
Fixed in #33711.

The installer now displays a link to https://www.mozilla.org/en-US/MPL/2.0/ instead of using placeholder text.

![Installer screen](https://github.com/user-attachments/assets/9ff303e6-2b24-4af0-a9d8-ba8ae72fe4ae)
