### ISSUE TITLE
./mach bootstrap-gstreamer fails to run on Linux Mint 18.3

### ISSUE THREAD

**Issue by hgallagher1993** [servo/servo#21732]
```
Error running mach:

    ['bootstrap-gstreamer']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

Exception: mach bootstrap does not support LinuxMint, please file a bug

  File "/home/hugh/opensource/servo/python/servo/bootstrap_commands.py", line 77, in bootstrap_gstreamer
    return bootstrap.bootstrap(self.context, force=force, specific="gstreamer")
  File "/home/hugh/opensource/servo/python/servo/bootstrap.py", line 356, in bootstrap
    raise Exception("mach bootstrap does not support %s, please file a bug" % distro)

```

Adding 'LinuxMint' to `bootstrap` in servo/python/servo/bootstrap.py and removing `.lower()` from `distro.lower()` got it to run though

**Comment by cdeler** [comment]
Hello @jdm ,

I had a similar issue with 
```./mach build --dev```
since I also work on the Mint

I wrote a little patch to this bug. I override the distro versio and name, since the Mint is based on a stable Ubuntu, therefore it requires the same `mach` behaviour.

Could the issue be assigned for me? Then I would commit the patch.

**Comment by jdm** [comment]
We can't assign the issue to arbitrary users, but you are welcome to submit that patch. Thanks in advance!

**Comment by hgallagher1993** [comment]
Not really sure why I didn't just fix this originally, but anyway thanks for fixing @cdeler :+1:

**Comment by jdm** [comment]
You can go ahead and make a new pull request with those changes.
