### ISSUE TITLE
build cause mac crash/reboot

### ISSUE THREAD

**Issue by rustjson** [servo/servo#21745]
I am trying to build this project on master branch on two machine by running `./mach build --dev`, both down during the compiling:

```
➜  servo git:(master) ./mach build --dev
   Compiling libsimpleservo v0.0.1 (/opensource/servo/ports/libsimpleservo)
   Compiling servo v0.0.1
```

**Comment by jdm** [comment]
How much RAM does your machine have?

**Comment by rustjason** [comment]
I have two machine. the current one is :

```
8 Go 2133 MHz LPDDR3
```

**Comment by rustjason** [comment]
BTW, @jdm, sorry to ask a question not related to this thread. I wonder if I can have a small build just for the `stylo` components, what I wanted is just dig deeper of this component,  an executable file that takes `css` as input and output the `dom object attributes` would be the prefect solution.

**Comment by jdm** [comment]
It is possible to run `./mach build -p style`.

**Comment by jdm** [comment]
And it's entirely possible that building servo is causing your machine to OOM; RAM usage of the build exceeds 6GB at times.

**Comment by rustjason** [comment]
interesting, but even this cause OOM, I don't think mac got rebooted sounds normal.
Let me try to build the style only and see.

Thank you

**Comment by rustjason** [comment]
Ok, my other machine got 16G RAM

**Comment by jdm** [comment]
You may be able to pass `--features servo`
