### ISSUE TITLE
Skia is not compiled properly for android

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21758]
I haven't tested yet, but I've been told that Servo crashes while loading this page:

https://rawgit.com/takahirox/three.js/BenchmarkTest/examples/webgl_benchmark_test_basic.html

Firefox Reality + Oculus Go

**Comment by nox** [comment]
This wants to use `fillText` so it needs to be tested with `dom.canvas-text.enabled` set, AFAICT.

**Comment by takahirox** [comment]
How to reproduce:
1. Open FireFox Reality+Servo on Oculus Go (I got APK from @paulrouget)
2. Go to https://rawgit.com/takahirox/three.js/BenchmarkTest/examples/webgl_benchmark_test_basic.html
3. Toggle to Servo
4. FireFox Reality Crushes

Error log(logcat on Android Studio):
>   --------- beginning of crash
>
>09-20 16:16:59.344 15299-15533/org.mozilla.vrbrowser A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 15533 (CanvasThread)
>
>09-20 16:16:59.352 15299-15533/org.mozilla.vrbrowser I/crash-reporter: failed to capture minidump crash
>
>09-20 16:16:59.358 15299-15446/org.mozilla.vrbrowser I/VrApi: FPS=60,Prd=31ms,Tear=0,Early=0,Stale=0,VSnc=1,Lat=0,Fov=0,CPU2/GPU=4/4,1593/510MHz,OC=F,TA=E/C/C,SP=N/N/N,Mem=1804MHz,Free=897MB,PSM=0,PLS=0,Temp=29.2C/25.0C,TW=2.33ms,App=5.18ms
>
>09-20 16:16:59.438 980-991/? I/WindowManager: WIN DEATH: Window{d9fcd13 u0 org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity}
>
>09-20 16:16:59.438 980-1076/? I/VirtualDisplayAdapter: Virtual display device released because application token died: org.mozilla.vrbrowser
>
>09-20 16:16:59.441 980-1251/? I/ActivityManager: Process org.mozilla.vrbrowser (pid 15299) has died
>
>09-20 16:16:59.443 980-1251/? W/ActivityManager: Force removing ActivityRecord{1c8b58f u0 org.mozilla.vrbrowser/.VRBrowserActivity t287}: app died, no saved state
>
>09-20 16:16:59.445 980-1000/? I/DisplayManagerService: Display device removed: DisplayDeviceInfo{"OffscreenViews": uniqueId="virtual:org.mozilla.vrbrowser,10067,OffscreenViews,0", 16 x 16, modeId 9, defaultModeId 9, supportedModes [{id=9, width=16, height=16, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, density 480, 480.0 x 480.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner org.mozilla.vrbrowser (uid 10067), FLAG_PRESENTATION, FLAG_OWN_CONTENT_ONLY}
>
>09-20 16:16:59.452 980-1262/? I/WindowManager: WIN DEATH: Window{d30276f u0 org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity}

**Comment by jdm** [comment]
This may be https://github.com/servo/servo/issues/21631 which may not have been fixed correctly.

**Comment by jdm** [comment]
Yep:
```
Thread 16 "CanvasThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 9007.9240]
0xc885df54 in SkString::~SkString (this=0xbbbfa880) at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.1/src/core/SkString.cpp:294
294	    if (fRec->fLength) {
(gdb) bt
#0  0xc885df54 in SkString::~SkString (this=0xbbbfa880) at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.1/src/core/SkString.cpp:294
#1  0xc883ca4c in SkLanguage::~SkLanguage (this=<optimized out>) at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.1/include/core/SkPaintOptionsAndroid.h:25
#2  SkPaintOptionsAndroid::~SkPaintOptionsAndroid (this=<optimized out>) at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.1/include/core/SkPaintOptionsAndroid.h:59
#3  SkPaint::~SkPaint (this=<optimized out>) at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000019.1/src/core/SkPaint.cpp:152
#4  0xc87f1fe0 in mozilla::gfx::DrawTargetSkia::FillRect (this=0xba2a7840, aRect=..., aPattern=..., aOptions=...)
    at /Users/jdm/.cargo/git/checkouts/rust-azure-984e17605d95e219/1536ca6/libazure/DrawTargetSkia.cpp:422
#5  0xc87e952c in AzDrawTargetFillRect (aDrawTarget=0x0, aRect=0x0, aPattern=0x0, aDrawOptions=<optimized out>) at /Users/jdm/.cargo/git/checkouts/rust-azure-984e17605d95e219/1536ca6/src/azure-c.cpp:312
#6  0xc87e790e in azure::azure_hl::DrawTarget::fill_rect::haf17836d959474b1 (self=0xbb23c820, rect=0xbbbfa988, pattern=..., draw_options=...)
    at /Users/jdm/.cargo/git/checkouts/rust-azure-984e17605d95e219/1536ca6/src/azure_hl.rs:635
#7  0xc7f147a2 in canvas::canvas_data::CanvasData::fill_rect::h40ab68f4c40cbe21 (self=0xbb23c788, rect=0xbbbfb2fc) at components/canvas/canvas_data.rs:130
#8  0xc7dedb20 in canvas::canvas_paint_thread::CanvasPaintThread::process_canvas_2d_message::he1ea9d7cbd73aa58 (self=0xbbbfb0f8, message=..., canvas_id=...)
    at components/canvas/canvas_paint_thread.rs:108
#9  0xc7decb20 in canvas::canvas_paint_thread::CanvasPaintThread::start::_$u7b$$u7b$closure$u7d$$u7d$::h0847bc7e34ec4714 () at components/canvas/canvas_paint_thread.rs:39
#10 0xc7e61f96 in std::sys_common::backtrace::__rust_begin_short_backtrace::hba299cb70f234fdb (f=...) at /checkout/src/libstd/sys_common/backtrace.rs:136
#11 0xc7de5970 in std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h3b798ca25b1548ed () at /checkout/src/libstd/thread/mod.rs:409
#12 0xc7d57d22 in _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hbbcfbec48eab9613 (self=..., _args=0)
    at /checkout/src/libstd/panic.rs:313
#13 0xc7d59b86 in std::panicking::try::do_call::hf03313278eac6072 (data=0xbbbfb758 "") at /checkout/src/libstd/panicking.rs:310
#14 0xc99464fe in __rust_maybe_catch_panic () at libpanic_unwind/lib.rs:103
#15 0xc7d59a96 in std::panicking::try::h9f977a2d4d761fd8 (f=...) at /checkout/src/libstd/panicking.rs:289
#16 0xc7d5994e in std::panic::catch_unwind::h42e3ba5b89e39a59 (f=...) at /checkout/src/libstd/panic.rs:392
#17 0xc7de5860 in std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h9edaf6b0608caa02 () at /checkout/src/libstd/thread/mod.rs:408
#18 0xc7de97a8 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hc84b165e0ad7bdb0 (self=0xbc25b000, args=0) at /checkout/src/liballoc/boxed.rs:646
#19 0xc9935eaa in _$LT$alloc..boxed..Box$LT$$LP$dyn$u20$alloc..boxed..FnBox$LT$A$C$$u20$Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::he6fd52ba0520c552 () at /checkout/src/liballoc/boxed.rs:656
#20 std::sys_common::thread::start_thread::h9dea733992537a2a () at libstd/sys_common/thread.rs:24
#21 std::sys::unix::thread::Thread::new::thread_start::h36a7fa8dac002ff1 () at libstd/sys/unix/thread.rs:90
#22 0xeb5e96a6 in __pthread_start(void*) () from /Users/jdm/src/servo/support/android/apk/obj/local/armeabi-v7a/system/lib/libc.so
#23 0xeb5a3ffa in __start_thread () from /Users/jdm/src/servo/support/android/apk/obj/local/armeabi-v7a/system/lib/libc.so
#24 0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
I'll deal with this.
