### ISSUE TITLE
Can't compile to Android anymore (Mac)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21773]
```
error[E0063]: missing field `__bindgen_padding_0` in initializer of `mozjs_sys::root::JS::ForOfIterator`
   --> /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs-0.9.1/src/conversions.rs:604:28
    |
604 |         let mut iterator = ForOfIterator {
    |                            ^^^^^^^^^^^^^ missing `__bindgen_padding_0`
error: aborting due to previous error
```

That was solved by https://github.com/servo/rust-mozjs/commit/7f313c9d83f476b5822de19a9ced0aa8e8b0bc29 which never made it to master.

I was using this in the past: https://github.com/servo/servo/issues/21469#issuecomment-422271099

But mozjs has been updated to 0.9.1 so it doesn't work anymore.

**Comment by paulrouget** [comment]
For Linux, we only need servo/rust-mozjs@7f313c9, for mac we need both servo/rust-mozjs@7f313c9 and https://github.com/servo/mozjs/pull/148.

**Comment by SimonSapin** [comment]
I’ve seen something similar before with `__bindgen_align` the problem went away by upgrading libclang. (I think from version 4 to 6? I don’t remember exactly.) Maybe upgrading could help here as well?

**Comment by paulrouget** [comment]
So that would require a ndk update :(

**Comment by SimonSapin** [comment]
This is the libclang used by bindgen, not the NDK’s clang used to compile C++ code. (By the way @emilio, does it sound like a problem that they’re not necessarily the same version?)

**Comment by paulrouget** [comment]
This is now fixed on both Mac and Linux.
