### ISSUE TITLE
Linux Build won't run on Debian 9 (missing libssl.so.1.0.0)

### ISSUE THREAD

**Issue by n2liquid** [servo/servo#21778]
I just downloaded the latest Servo build for GNU from https://download.servo.org/, but it won't run:

```
$ ./servo
./servo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

My system has `libssl3.so`, `libssl.so.1.0.2`, and `libssl.so.1.1` under `/usr/lib/x86_64-linux-gnu`. I'm not sure what to do to get Servo to run here. Could anyone help?

**Comment by SimonSapin** [comment]
Is the `libssl1.0-dev` package installed?

**Comment by n2liquid** [comment]
Hey, Simon. It wasn't installed, but installing it didn't help. Getting the same message.

**Comment by SimonSapin** [comment]
Unfortunately, https://packages.debian.org/search?searchon=contents&keywords=libssl.so.1.0.0&mode=exactfilename&suite=stable&arch=any gives no result :/

Ah, the joys of shipping dynamiclly-linked programs. As far as I can tell we run the linker with a `-lssl` argument, then GCC resolves that *somehow* to a `.so` file on the system at build time, and embeds the basename of that file in the binary. On my Ubuntu 18.04 machine the left-hand-side of `nm target/release/servo` shows `libssl.so.1.1`, but it’s presumably `libssl.so.1.0.0` on the Ubuntu 14.04 machine that makes Nightly builds.

So that’s what’s going on, but I don’t really have a suggestion how to fix it.

**Comment by n2liquid** [comment]
> Ah, the joys of shipping dynamiclly-linked programs.

It's truly a hateful job.

I tried compiling OpenSSL's 1.0.0 release, but a weird linker error made me give up. I'll check back on Servo once this is fixed, was just curious. Actually the same thing happened maybe a year ago and I thought the same thing... :-)

Could you upload your build of `libssl.so.1.0.0` and `libcrypto.so.1.0.0`? Maybe that would be enough for it to boot and for me to check it out.

**Comment by n2liquid** [comment]
Ops, sorry, just noticed you don't have it on your system either. How easy is it to build Servo?

**Comment by jdm** [comment]
On linux we have a bootstrap command that should install all necessary packages for building, and then building only requires one command and lots of patience.

**Comment by n2liquid** [comment]
I'll give that a shot and leave it running on the background, thanks.

**Comment by arpu** [comment]
same problem on fedora 28 
installed packages are 
openssl.x86_64                             1:1.1.0h-3.fc28              @fedora 
openssl-devel.x86_64                       1:1.1.0h-3.fc28              @fedora 
openssl-libs.i686                          1:1.1.0h-3.fc28              @fedora 
openssl-libs.x86_64                        1:1.1.0h-3.fc28              @fedora

**Comment by AmarOk1412** [comment]
@arpu just tried `./mach bootstrap` on Fedora 28. (` openssl-devel-1:1.1.0i-1.fc28.x86_64 ` was already installed), Didn't have any issues.

**Comment by arpu** [comment]
looks like the poroblem is only on the binarys from https://download.servo.org/

so building from source should work

**Comment by ShalokShalom** [comment]
Hi :)

There is no libressl in our repos and I like to run the binarys. 

I get the same exact error message on my KaOS system. 

OpenSSL 1.1.1.2 is here is use currently. 

Thanks

**Comment by jdm** [comment]
@ShalokShalom Could you put the full build output in a gist and link it here, please? That seems surprising.

**Comment by ShalokShalom** [comment]
It is exactly as in the original post. There is nothing more, no build at all. 
Just this line.

**Comment by n2liquid** [comment]
So I tried running the latest Servo nightly again and now I get this error:

```
$ ./servo
./servo: error while loading shared libraries: libgstwebrtc-1.0.so.0: cannot open shared object file: No such file or directory
```

Should I open a new issue?

**Comment by Darkspirit** [comment]
It just merged...

**Comment by Darkspirit** [comment]
Yes, that sounds like a different issue. Try `apt install libgstreamer-plugins-bad1.0-0`.

**Comment by n2liquid** [comment]
It's already installed. Looks like I need `sid`, or to install a newer version of GStreamer manually?

**Comment by ShalokShalom** [comment]
I would like to give Servo a test run, while currently no way to get on my device was successful.

**Comment by ShalokShalom** [comment]
Still happens to me here.

**Comment by Darkspirit** [comment]
New Nightly just arrived: https://download.servo.org/nightly/linux/servo-latest.tar.gz

**Comment by ShalokShalom** [comment]
Thanks a lot. So its not a nightly, more a weekly?

**Comment by Darkspirit** [comment]
No, it's build every day, unless they're working on their infra.

**Comment by ShalokShalom** [comment]
Ahja, the merge happened 13 hours ago, my mistake. Thanks!

**Comment by alejandro-mosso** [comment]
hi 

To solve error:
**error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory**
You should add a mirror to /etc/apt/sources.list

Find the correct package for your architecture here:
https://packages.debian.org/search?suite=jessie&arch=any&mode=exactfilename&searchon=contents&keywords=libssl.so.1.0.0
(in my case it is amd64, and the correct library is /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0):

Then go to **Download libssl1.0.0** section, and again click on your architecture (amd64 in my case).

There you will find the mirror you have to add to /etc/apt/sources.list  for me, the mirror I have to add is:
deb http://security.debian.org/debian-security jessie/updates main 

Then run bellow commands:
sudo apt-get update
sudo apt-get install libssl1.0.0

Cheers!
