### ISSUE TITLE
three.js examples are flickery on android

### ISSUE THREAD

**Issue by jdm** [servo/servo#21796]
I tried https://threejs.org/examples/webgl_simple_gi.html, https://threejs.org/examples/webgl_animation_cloth.html, and https://threejs.org/examples/webgl_camera.html, and they are displayed jerkiness and stuttering, along with seemingly rendering past frames over top of current frames.

**Comment by paulrouget** [comment]
Note: that's with the ServoView. With the ServoSurface, it stays black: #21807

**Comment by paulrouget** [comment]
On my pixel 2, with a release build, with the servoapp:

https://threejs.org/examples/webgl_simple_gi.html i see the rendering issue, but not really jerkiness or slutter. But both https://threejs.org/examples/webgl_animation_cloth.html and https://threejs.org/examples/webgl_camera.html stay black.

**Comment by jdm** [comment]
It's much worse in a debug build than a release build, but it's still visible. jrmuizel said it looks like the frames are being drawn out of order, which would explain the visual effect.

**Comment by jdm** [comment]
This is particularly evident if I force the readback path instead of shared texture.

**Comment by jdm** [comment]
The flickering goes away if I remove the call to requestRender from ServoView::doFrame. This makes sense, since that buffer flip request is not synchronized with any corresponding webrender rendering, so for a triple-buffered Android application (for example), we'll end up swapping out for a buffer that hasn't been redrawn since the last render that was requested from ServoView::flushGLBuffers (which is invoked after webrender is finished rendering).
