### ISSUE TITLE
failed to compile: 'Unable to detect OpenSSL version'

### ISSUE THREAD

**Issue by mandreyel** [servo/servo#21791]
I couldn't get the latest master branch of Servo to compile. Apparently I have openssl 1.1.1 installed and it seems to be looking for 0.9.24 but for some reason can't determine the version number. Here's the error log:
```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/mandreyel/projects/servo/target/debug/build/openssl-9eb0a7ecfa0da8ba/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/mandreyel/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14

```

I don't remember updating openssl recently (could compile Servo just fine a week back) but I could be wrong. I tried `./mach clean` and installing the dependencies listed in the readme anew to no avail. The oldest openssl I can install via pacman on Arch is 1.0 and that doesn't solve it either (haven't tried manually installing 0.9.* yet). Any ideas?

**Comment by kenan-rhoton** [comment]
Can confirm this is also happening to me on Arch Linux

**Comment by SimonSapin** [comment]
Note that the 0.9 version number of https://crates.io/crates/openssl is not directly related to the version number of https://www.openssl.org/

**Comment by SimonSapin** [comment]
What’s the output of `cat target/*/build/openssl-sys*/output | grep cargo:version` after seeing this `Unable to detect OpenSSL version` error message?

**Comment by mandreyel** [comment]
@SimonSapin I'm at work now and running Ubuntu (on which Servo compiles with no issues) but I'll send you the log once I'm home.

**Comment by mandreyel** [comment]
@SimonSapin Here's the output: `cargo:version=111`

**Comment by SimonSapin** [comment]
Alright, this panic matches the code at https://github.com/sfackler/rust-openssl/blob/0.9.x/openssl/build.rs

It looks like we’ve updated to a version of the `openssl-sys` crate that supports OpenSSL 1.1.1, but our version of the `openssl` crate doesn’t. @sfackler, does that sound accurate? Is this fixable while staying with openssl 0.9.x?

I *think* that upgrading to openssl 0.10.x would require upgrading Hyper from 0.10.x to 0.11.x.

**Comment by sfackler** [comment]
You shouldn't need to upgrade your hyper - you can just fork hyper-openssl 0.2.7 and bump it to openssl 0.10.

**Comment by atouchet** [comment]
In case this was missed there's an open WIP PR to update hyper and openssl: https://github.com/servo/servo/pull/21644

**Comment by mandreyel** [comment]
Is there a temporary workaround for this? Still can't compile Servo on my Arch boxes :(

**Comment by sadmansk** [comment]
Facing same issue, is there a workaround?

**Comment by McSinyx** [comment]
Also happens on my Fedora 29.

**Comment by atouchet** [comment]
openssl has now been updated. Is this issue fixed now?

**Comment by mandreyel** [comment]
@atouchet Yes, it finally builds on Arch now!
