### ISSUE TITLE
ServoSurface: black screen with webGL demos 

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21807]
Both https://threejs.org/examples/webgl_simple_gi.html and https://threejs.org/examples/webgl_animation_cloth.html just show a black screen with FxReality + Servo.

**Comment by jdm** [comment]
That happens because it was ses the fillText canvas API. If you enable that preference then it shows things.

**Comment by paulrouget** [comment]
@jdm even with that pref on, I can't see anything. I only see the threejs graph.

To be clear, I'm talking about the ServoSurface, used in FirefoxReality.

**Comment by takahirox** [comment]
Seems like it renders nothing? On my test, FxR + Servo renders nothing.

https://rawgit.com/takahirox/three.js/BenchmarkTest/examples/webgl_benchmark_test_basic.html

And the background color of the three.js examples you mentioned is black, then probably the screen is black.

**Comment by jdm** [comment]
https://github.com/bjacob/webgl-tutorial/blob/master/01-red-triangle.html works, so I'm going to slowly increase the complexity until I figure out what's happening.

**Comment by jdm** [comment]
The benchmark page renders just fine with the dom.canvas-text.enabled preference enabled.

**Comment by takahirox** [comment]
How can I set  `dom.canvas-text.enabled`? about:config?

**Comment by paulrouget** [comment]
@jdm: which device?

@takahirox for now it's not possible. You have to rebuild Crow with the pref on.

**Comment by jdm** [comment]
Ocuous Go.

**Comment by jdm** [comment]
All of the demos in https://github.com/bjacob/webgl-tutorial work fine (eg. https://rawgit.com/bjacob/webgl-tutorial/master/11-per-pixel-lighting.html), with the exception of the animating ones that expect that Servo will clear the buffer (see https://github.com/servo/servo/issues/21132). Those at least still draw things, so I will continue searching for what the three.js examples do differently.

**Comment by jdm** [comment]
https://aframe.io/examples/showcase/lights/ doesn't render correctly, but it does render.

**Comment by jdm** [comment]
I have discovered how to make the three.js examples render correctly. If I comment out the `background-color: #000000` property in the `body` css rule, everything draws perfectly. I am not sure why that is only a problem on oculus, however!

**Comment by jdm** [comment]
It's something specific to three.js - adding `<style>body { background-color: #0000 }</style>` to https://raw.githubusercontent.com/bjacob/webgl-tutorial/master/01-red-triangle.html does not cause the webgl content to disappear, but adding it to http://joshmatthews.net/webgl5.html does.

**Comment by jdm** [comment]
I can replicate this with the following testcase:
```html
<style>
  body { margin: 0; background-color: #0000FF; }
  canvas { border: 5px solid red }
</style>
<canvas id="canvas" width=500 height=500></canvas>
<script>
  document.getElementById('canvas').getContext('webgl', { alpha: false });
</script>
```
This makes me believe that we're not initializing the default framebuffer correctly, and it just happens to work on desktop.

**Comment by jdm** [comment]
Other testcases that previously worked demonstrate the same issue when I pass `alpha: false` when creating the GL context.

**Comment by jdm** [comment]
I can reproduce the same problem without webgl. This page shows an image:
```html
<img src="https://www.google.ca/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png">
```
This page does not:
```html
<style>body { background-color: #0000 }<style>
<img src="https://www.google.ca/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png">
```

**Comment by jdm** [comment]
The previous testcase is incorrect; I was misled by #21919. I have determined that images that have an alpha channel (like the google one in the previous testcase) display fine, whether there is a page background colour or not. Images without an alpha channel (including WebGL canvases with `{alpha: false}`) have the page background drawn over top of them.
