### ISSUE TITLE
Windows nightly reports missing gstreamer DLLs

### ISSUE THREAD

**Issue by jdm** [servo/servo#21839]
```
16:32 <imago> Hello! I'm trying to install the nightly build of servo on windows 10 64bit to try it out but it basically is lacking gstreamer ("libgstapp-1.0.0.dll was not found"). Any tips? Thanks
16:33 <imago> Or rather, it has 3 or so .dll files missing, all to do with "libg", i assume it gstreamer/gobject related
16:38 <jdm> imago: huh, that problem should have been solved already :<
16:38 <jdm> imago: is this a nightly downloaded today?
16:38 <imago> Yeah, i tried installing it just a few min ago
```

**Comment by ferjm** [comment]
No, the zip does not contain the required GStreamer dlls. I am not sure if we can add them there directly though. Would it be acceptable to add the GStreamer installer to the zip?

**Comment by muliar** [comment]
Latest installer: [servo-latest.exe](https://download.servo.org/nightly/windows-msvc/servo-latest.exe)
Errors:
```The code execution cannot proceed because libgstapp-1.0-0.dll was not found. 
The code execution cannot proceed because libgstaudio-1.0-0.dll was not found. 
The code execution cannot proceed because libgstreamer-1.0-0.dll was not found. 
The code execution cannot proceed because libgobject-2.0-0.dll was not found. 
```

**Comment by atouchet** [comment]
@muliar do you have GStreamer installed on your C: drive?

**Comment by jdm** [comment]
They should not have to have GStreamer installed; the installer should put the files in the right place.

**Comment by muliar** [comment]
> 
> 
> @muliar do you have GStreamer installed on your C: drive?

Good point!
Servo Installer has installed gstreamer onto D:\ somehow yesterday: time modified is an evidence.

**Comment by ferjm** [comment]
Ugh, I have no idea how to do it, but I guess we'd need to inspect the registry to figure out where GStreamer was installed (and hope that GStreamer writes something there) before setting the PATH [here](https://github.com/ferjm/servo/blob/3c5c01a109eb5d673fb24a59557b85562635e307/support/windows/Servo.wxs.mako#L43).

/me reinstalls a Windows VM :(

**Comment by atouchet** [comment]
@ferjm would it be possible to dictate which drive GStreamer is installed to? I feel like the main issue here is that GStreamer sometimes installs to unexpected locations by default instead of C:. The installer from the GStreamer website does the same thing but at least with that one the directory can be changed.

**Comment by ferjm** [comment]
I don't know, I guess that's possible. The current installer already allows to manually change the installation path (through the Options menu).

I think it would be safer to get the installation path from the registry. I found that GStreamer writes the `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GStreamer1.0\x86\InstallDir` key in the registry. So we can use that value. I just need to figure out how to do it with WiX (and wait for the long VM builds).
