### ISSUE TITLE
Problem with mozjs_sys v0.61.0

### ISSUE THREAD

**Issue by russell-davidson** [servo/servo#21846]
I am trying to build servo on debian testing (buster), and all goes well until the compilation of
mozjs_sys v0.61.0
This process fails:
servo/target/debug/build/mozjs_sys-1f030f6e50ebd54f/build-script-build
When I try to run this directly from the command line, there is a missing dependency. ldd shows two such:
libproc_macro-ef273343e97c62d9.so => not found
libstd-cbdc169671953fab.so => not found
I suppose that things have got out of order somehow, and that these should have been built before this stage.
There is a huge list of errors, given in the attached file.
[crap.txt](https://github.com/servo/servo/files/2432318/crap.txt)

**Comment by nox** [comment]
There is no way `mozjs_sys`'s build system on its own is triggering this. Did you maybe try to build with a different Rust than the one Servo installs by itself?

**Comment by nox** [comment]
Cc @asajeffrey

**Comment by russell-davidson** [comment]
Thanks for your speedy reply.

I followed the instruction to do:

curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none

in order to install rust. Then:

./mach bootstrap .

and finally

./mach build --dev

I also tried ./mach check,

which gave exactly the same bunch of error messages.

Best wishes, Russell.
-- 
Russell Davidson,                  email Russell.Davidson@mcgill.ca
Department of Economics,
McGill University,
855 Sherbrooke Street West,
Montreal, Quebec                   Phone 514-398-6186
H3A 2T7                            Fax   514-398-4938

**Comment by russell-davidson** [comment]
Installing clang-3.9 via debian didn't work. I used the code in the fileE0277
clang-sys-0.23.0/ci/before_install.sh in .cargo/registry...
to install clang-3.9.0 and export LLVM_CONFIG_PATH and LD_LIBRARY_PATH
This seemed to work, at least as far as getting rid of the message about Debian clang version 3.5.2-3~bpo8+2
However, there are now quite different errors, with messages in the attached crap2.txt. The error number is E0277
Perhaps installing clang-3.9.0 by hand gave rise to this?
[crap2.txt](https://github.com/servo/servo/files/2434676/crap2.txt)

**Comment by jdm** [comment]
Those errors occur when you have a version of rustfmt installed that is outdated.

**Comment by russell-davidson** [comment]
Thanks, jdm. What should I do to get an uptodate rustfmt instead of
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none
?

**Comment by jdm** [comment]
Try following https://github.com/rust-lang-nursery/rustfmt/#installation.

**Comment by dralley** [comment]
Seems like this toolchain issue was resolved
