### ISSUE TITLE
Drop support for Arm (Armv7 should be default)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#21854]
@MortimerGoro mentioned in #21851:

> We can drop normal "arm", it's already deprecated. There aren't Android 4+ devices which support armeabi but not armeabi-v7a, so we can safely drop armeabi and save some compilation work & upload bandwidth. We can remove armeabi also from Servo cloud compilation tests if it's still there.

**Comment by SimonSapin** [comment]
Do we have any support to drop? It looks like we’re already building for ARMv7:

https://github.com/servo/servo/blob/57053e03bbfc65e1d2f283cfa8646038be9f9b06/python/servo/command_base.py#L298-L299

**Comment by paulrouget** [comment]
I haven't really looked. What about https://github.com/servo/servo/blob/57053e03bbfc65e1d2f283cfa8646038be9f9b06/python/servo/package_commands.py#L223 or support/android/fakeld/fake-ld-arm.sh or the armr reference in the different build.gradle files?
