### ISSUE TITLE
Compilation failing [branch: master]

### ISSUE THREAD

**Issue by devopsec** [servo/servo#21857]
OS version: Linux Mint 18.2
Kernel Relase: 4.15.0-29-generic
Kernel Version: #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018
rustc version: rustc 1.30.0-nightly (7061b2775 2018-08-28)
rustup version: rustup 1.13.0 (ea9259c1b 2018-07-16)
Side Note: Linux Mint is an upstream version of Ubuntu, which is supported according to servo/python/servo/bootstrap.py. consider adding to disro list check, line num: 350.

Seems rust has issues encoding arrays of type u8 that are > length 32?

Full error below:

<details>

```rust
error[E0277]: the trait bound `u8: std::convert::From<rust::MutableHandle<'_, u8>>` is not satisfied
    --> /home/anon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs-0.9.2/src/rust.rs:1205:52
     |
1205 |             wrap!(@inner $saved <> ($($acc,)* $arg.into(),) <> $($rest)*);
     |                                                    ^^^^ the trait `std::convert::From<rust::MutableHandle<'_, u8>>` is not implemented for `u8`
     | 
    ::: /home/anon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs-0.9.2/src/jsapi_wrappers.in:44:1
     |
44   | wrap!(jsapi: pub fn FinishMultiOffThreadScriptsDecoder(cx: *mut JSContext, token: *mut ::std::os::raw::c_void, scripts: MutableHandle<ScriptVector>) -> bool);
     | -------------------------------------------------------------------------------------------------------------------------------------------------------------- in this macro invocation
     |
     = help: the following implementations were found:
               <u8 as std::convert::From<bool>>
     = note: required because of the requirements on the impl of `std::convert::Into<u8>` for `rust::MutableHandle<'_, u8>`

error[E0277]: the trait bound `u8: std::convert::From<rust::MutableHandle<'_, u8>>` is not satisfied
    --> /home/anon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs-0.9.2/src/rust.rs:1348:113
     |
1348 |             wrap!(@inner $saved <> ($($declargs)* $arg: &mut MutableHandle<$gentype> , )  <> ($($acc,)* (*$arg).into(),) <> $($rest)*);
     |                                                                                                                 ^^^^ the trait `std::convert::From<rust::MutableHandle<'_, u8>>` is not implemented for `u8`
     | 
    ::: /home/anon/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs-0.9.2/src/jsapi_wrappers.in:44:1
     |
44   | wrap!(jsapi: pub fn FinishMultiOffThreadScriptsDecoder(cx: *mut JSContext, token: *mut ::std::os::raw::c_void, scripts: MutableHandle<ScriptVector>) -> bool);
     | -------------------------------------------------------------------------------------------------------------------------------------------------------------- in this macro invocation
     |
     = help: the following implementations were found:
               <u8 as std::convert::From<bool>>
     = note: required because of the requirements on the impl of `std::convert::Into<u8>` for `rust::MutableHandle<'_, u8>`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
The following warnings were emitted during compilation:

warning: src/jsglue.cpp: In function ‘void DeleteCompileOptions(JS::ReadOnlyCompileOptions*)’:
warning: src/jsglue.cpp:586:57: warning: deleting object of polymorphic class type ‘JS::OwningCompileOptions’ which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
warning:      delete static_cast<JS::OwningCompileOptions *>(aOpts);
warning:                                                          ^
warning: At global scope:
warning: cc1plus: warning: unrecognized command line option ‘-Wno-return-type-c-linkage’
warning: cc1plus: warning: unrecognized command line option ‘-Wno-c++0x-extensions’

error: Could not compile `mozjs`.
```

</details>

**Comment by jdm** [comment]
This happens when the version of rustfmt installed is too old.

**Comment by CYBAI** [comment]
Same as #21790

**Comment by jdm** [comment]
Actually I think this is caused by a version of clang that is <3.9.

**Comment by jdm** [comment]
You need to remove any mozjs* directories from tarrget/debug/build to force a rebuild.

**Comment by devopsec** [comment]
Actually upgrading to clang v6.0 was able to compile mozjs, I forgot to update new version as my default binary.

mozjs is compiling now but it looks like we're failing on mozjs_sys now...

System info:

```
cat /etc/*release 2>/dev/null
```

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial

```
clang --version
```

clang version 6.0.1-svn334776-1~exp1~20180919141756.113 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```
python --version
```

Python 2.7.12

```
rustc --version
```

rustc 1.29.1 (b801ae664 2018-09-20)

```
rustup --version
```

rustup 1.13.0 (ea9259c1b 2018-07-16)

Error info w/ backtrace below:

```
export RUST_BACKTRACE=1; ./mach build --release 2>&1 | tee debug_build.txt
```

[debug_build.txt](https://github.com/servo/servo/files/2454187/debug_build.txt)

**Comment by devopsec** [comment]
Many of the warnings have to do with signed integer overflow (strict compiler checking), first one is from mozjs_sys-0.61.0/mozjs/intl/icu/source/i18n/collationweights.cpp
But i don't think that is the root cause.

Searching for the 1st occurence of 'error' in the output we see that some of the included headers for clang v6.0 are throwing errors:

backend.mk:2160: warning: overriding recipe for target '../dist/system_wrappers/pixman.h'
backend.mk:1278: warning: ignoring old recipe for target '../dist/system_wrappers/pixman.h'
/usr/include/clang/6.0.1/include/emmintrin.h:3427:10: error: use of undeclared identifier '__builtin_ia32_cvtdq2ps'
/usr/include/clang/6.0.1/include/avxintrin.h:2228:18: error: use of undeclared identifier '__builtin_ia32_cvtdq2ps256'

What versions of clang are officially supported???
My clang versions are all straight from the official ubuntu llvm repo's
http://apt.llvm.org/xenial/

**Comment by devopsec** [comment]
Has something to do with rustfmt as indicated above. See error:

```
rustfmt --version
```

error: toolchain 'nightly-2018-10-05-x86_64-unknown-linux-gnu' does not have the binary `rustfmt`
info: backtrace:

stack backtrace:
   0:     0x565499bda3ec - backtrace::backtrace::trace::h23c45a8a47d8c8ed
   1:     0x565499bd9a42 - backtrace::capture::Backtrace::new_unresolved::h67d805582adf2cb9
   2:     0x565499bd9317 - error_chain::backtrace::imp::InternalBacktrace::new::h60044337d58b8406
   3:     0x565499bd9684 - <error_chain::State as core::default::Default>::default::hfaecc006d90727e8
   4:     0x5654996f4703 - rustup::toolchain::Toolchain::create_command::h7b855910b94ec29a
   5:     0x5654997108aa - rustup::config::Cfg::create_command_for_dir::h0a7aa75da3eb23ec
   6:     0x5654996ae7a3 - rustup_init::proxy_mode::main::h50c6ba631bebb2d6
   7:     0x565499696d44 - rustup_init::main::h43e9e2ad7678f7e3
   8:     0x56549968fa22 - std::rt::lang_start::{{closure}}::h0b18d943f72aab96
   9:     0x565499bee382 - std::rt::lang_start_internal::{{closure}}::h72602870b4a34363
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hc2917ab2c572e22d
                        at libstd/panicking.rs:310
  10:     0x565499c173c9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  11:     0x565499bfaeb5 - std::panicking::try::h3777f1f99a655493
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::hab6d1467193fc938
                        at libstd/panic.rs:374
                         - std::rt::lang_start_internal::h106bcdfb2e3beaf8
                        at libstd/rt.rs:58
  12:     0x5654996974d3 - main
  13:     0x7f84f1a6182f - __libc_start_main
  14:     0x56549966a90c - <unknown>

I am not a ruby developer so this is out of my scope.. 
Any idea what would cause these toolchain issues?

**Comment by Avanthikaa** [comment]
@devopsec I encountered the same errors during build. I changed my clang version to 6.0 but I also have the rustfmt issue. The build fails with the message `fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true` along with a list of errors. Have you found the fix for this? When I run 
`rustfmt --version` I also get the same output as you've shown.

**Comment by jdm** [comment]
To be clear- the problem is the version of llvm that is in use. rustfmt is unrelated.
