### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by devopsec** [servo/servo#21885]
Add a requirements.txt for required python modules and make part of the install process.

-- Problem:
some python modules may not be installed
instead of letting user track them down install required modules
-- Example:
on fresh build i had to install certifi module to run the bootstrap commands (specifically: ./mach bootstrap)

-- Solution:
track required python modules in a requirements.txt file and install prior to building
pipreqs only supports python >= v3, so the next best thing i found was to parse out the required modules with a regex.
-- Example (linux):
using globbing, i.e.) `shopt -s globstar`
```
grep -ozP '(?s)(from [a-zA-Z0-9_\.]+ )?import .*?(\n|\(.+?\)\n)' ./servo/python/** 2>/dev/null >imports.txt
```

-- Summary:
this is obviously a rough example as it does not account for duplicate imports or submodule imports and still has the filename in the output, but I think you get the idea.
an example of the output:
[imports.txt](https://github.com/servo/servo/files/2454040/imports.txt)
an example with filenames removed:
[imports.txt](https://github.com/servo/servo/files/2454043/imports.txt)

**Comment by SimonSapin** [comment]
The only Python-related requirement for building should be Python 2.7 and virtualenv. The `mach` script will automatically create a virtual environment and install dependencies listed in `python/requirements.txt`.

If after following the steps for building at https://github.com/servo/servo#readme you get a Python error, please copy-paste the full output together with the command you’re running. It’s possible that something is missing in `python/requirements.txt`.

**Comment by SimonSapin** [comment]
As mentioned, we already have a `requirements.txt` per this issue’s title. However this may be a relevant bug:

> on fresh build i had to install certifi module to run the bootstrap commands (specifically: ./mach bootstrap)

@devopsec, could you say more about that?

**Comment by SimonSapin** [comment]
Yes, could you please provide the full output of the failing command? (In particular if there’s a Python traceback.)

**Comment by ineol** [comment]
Hi, I ran into the same problem on Debian testing. Here is the backtrace I got.

```
$ ./mach bootstrap
Traceback (most recent call last):
  File "./mach", line 96, in <module>
    main(sys.argv)
  File "./mach", line 24, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/ineol/Code/servo/python/mach_bootstrap.py", line 232, in bootstrap_command_only
    from servo.bootstrap import bootstrap
  File "/home/ineol/Code/servo/python/servo/bootstrap.py", line 17, in <module>
    from servo.util import extract, download_file, host_triple
  File "/home/ineol/Code/servo/python/servo/util.py", line 33, in <module>
    import certifi
ImportError: No module named certifi
```
installing it through `apt install python3-certifi` fixed the problem.

**Comment by jdm** [comment]
I've suggested the proper fix at https://github.com/servo/servo/pull/22250#issuecomment-441113614 for this problem.

**Comment by dralley** [comment]
I think this can be closed as the fix was merged.  https://github.com/servo/servo/pull/22596
