### ISSUE TITLE
Slither.io very broken

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#21886]
When loading the page, at first it flashes something that looks like it may be correct rendering of start screen, then it switches to 
https://www.dropbox.com/s/w4sfvafacrsd513/Screenshot%202018-10-07%2021.59.35.png?dl=0

**Comment by notriddle** [comment]
I'm able to find one difference between Firefox and Servo that seems relevant.

According to the network inspector, Firefox is sending a POST to `https://syndication.twitter.com/jot`, getting 302 redirected to `https://platform.twitter.com/jot.html`, and GETting it.

![](https://user-images.githubusercontent.com/1593513/46896778-e8d92900-ce33-11e8-8d8f-ddc3531db0df.png)

Servo is [following the standard](https://en.wikipedia.org/wiki/HTTP_302) by re-sending the POST request to `jot.html`, according to `RUST_LOG=net=debug`, and getting back a Method Not Allowed 

```
INFO 2018-10-12T22:27:45Z: net::http_loader: POST https://platform.twitter.com/jot.html
```

So... this is a web-compatibility bug, has squat to do with canvas, and should be categorized as web compat.

**Comment by notriddle** [comment]
Apparently, the [fetch spec](https://fetch.spec.whatwg.org/#http-redirect-fetch) actually override the o.g. HTTP spec, and requests web-compatible behavior for 302 Found. And the fetch module in Servo already implements this, too.

So for some reason, Servo isn't running that code. Fun.
