### ISSUE TITLE
Assertion begin <= self.edit_point fails in text selection code

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#21891]
```text
assertion failed: begin <= self.edit_point (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/textinput.rs:308)
```

Steps to reproduce:

1. Open https://google.com (or any other document with text input)
2. Focus text input
3. Press <kbd>a</kbd>, <kbd>b</kbd>, <kbd>c</kbd>
4. Hold <kbd>Shift</kbd> and press <kbd>←</kbd> 3 times
5. Hold <kbd>Shift</kbd> and press  <kbd>→</kbd>

Expected: text is "abc" and "bc" selected
Observed (on debug build): assertion failure

**Comment by KiChjang** [comment]
cc @jonleighton
