### ISSUE TITLE
Intermittent problem on windows taskcluster

### ISSUE THREAD

**Issue by jdm** [servo/servo#21916]
```
[taskcluster:error] TASK FAILURE during artifact upload: file-missing-on-worker: Could not read file 'C:\Users\task_1539273804\repo\target\debug\msi\Servo.zip'
[taskcluster 2018-10-11T16:04:39.721Z] Uploading redirect artifact public/logs/live.log to URL https://queue.taskcluster.net/v1/task/Sp2abfm4TVKUbm11JREGDg/runs/1/artifacts/public/logs/live_backing.log with mime type "text/plain; charset=utf-8" and expiry 2019-10-11T15:34:41.565Z
[taskcluster:error] file-missing-on-worker: Could not read file 'C:\Users\task_1539273804\repo\target\debug\msi\Servo.exe'
[taskcluster:error] file-missing-on-worker: Could not read file 'C:\Users\task_1539273804\repo\target\debug\msi\Servo.zip'
[taskcluster:error] goroutine 1 [running]:
[taskcluster:error] runtime/debug.Stack(0xc042605560, 0x8ec9e0, 0xc04246e030)
[taskcluster:error] 	/home/travis/.gimme/versions/go1.10.3.src/src/runtime/debug/stack.go:24 +0xae
[taskcluster:error] main.(*TaskRun).Run.func2(0xc0422ae110, 0xc0424b9c00, 0xc0422ae118)
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:1121 +0x231
[taskcluster:error] panic(0x8ec9e0, 0xc04246e030)
[taskcluster:error] 	/home/travis/.gimme/versions/go1.10.3.src/src/runtime/panic.go:502 +0x237
[taskcluster:error] main.(*TaskRun).ExecuteCommand(0xc0424b9c00, 0x0, 0xc0424b9c00)
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:985 +0x6d2
[taskcluster:error] main.(*TaskRun).Run(0xc0424b9c00, 0xc042303d60)
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:1283 +0x1763
[taskcluster:error] main.RunWorker(0x0)
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:670 +0xe1b
[taskcluster:error] main.main()
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:418 +0x946
[taskcluster:error] 
[taskcluster:error] &os.PathError{Op:"fork/exec", Path:"C:\\Users\\task_1539273804\\command_000000_wrapper.bat", Err:0x5}
[taskcluster:error] fork/exec C:\Users\task_1539273804\command_000000_wrapper.bat: Access is denied.
```
from https://tools.taskcluster.net/groups/XoQXB29bSA201P8pSwvXXg/tasks/Sp2abfm4TVKUbm11JREGDg/runs/1/logs/public%2Flogs%2Flive.log
cc @SimonSapin

**Comment by SimonSapin** [comment]
pmoore points out on IRC that the most relevant error message is `command_000000_wrapper.bat: Access is denied`:

```
[taskcluster:error] goroutine 1 [running]:
[taskcluster:error] runtime/debug.Stack(0xc042605560, 0x8ec9e0, 0xc04246e030)
[taskcluster:error] 	/home/travis/.gimme/versions/go1.10.3.src/src/runtime/debug/stack.go:24 +0xae
[taskcluster:error] main.(*TaskRun).Run.func2(0xc0422ae110, 0xc0424b9c00, 0xc0422ae118)
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:1121 +0x231
[taskcluster:error] panic(0x8ec9e0, 0xc04246e030)
[taskcluster:error] 	/home/travis/.gimme/versions/go1.10.3.src/src/runtime/panic.go:502 +0x237
[taskcluster:error] main.(*TaskRun).ExecuteCommand(0xc0424b9c00, 0x0, 0xc0424b9c00)
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:985 +0x6d2
[taskcluster:error] main.(*TaskRun).Run(0xc0424b9c00, 0xc042303d60)
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:1283 +0x1763
[taskcluster:error] main.RunWorker(0x0)
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:670 +0xe1b
[taskcluster:error] main.main()
[taskcluster:error] 	/home/travis/gopath/src/github.com/taskcluster/generic-worker/main.go:418 +0x946
[taskcluster:error] 
[taskcluster:error] &os.PathError{Op:"fork/exec", Path:"C:\\Users\\task_1539273804\\command_000000_wrapper.bat", Err:0x5}
[taskcluster:error] fork/exec C:\Users\task_1539273804\command_000000_wrapper.bat: Access is denied.

**Comment by petemoore** [comment]
I haven't seen this before, but for some reason, generic-worker seems to have a problem writing to the task directory. I'm investigating...

**Comment by petemoore** [comment]
I got a loaner in task [`N9obQV88T729DjWUuLUf8w`](https://queue.taskcluster.net/v1/task/N9obQV88T729DjWUuLUf8w). This task was a copy of the one that failed ([XoQXB29bSA201P8pSwvXXg](https://queue.taskcluster.net/v1/task/XoQXB29bSA201P8pSwvXXg)), but did not exhibit the same failure, so indeed this seems to be an intermittent issue.

Here we see the content of the generated commands:

```batch
C:\Users\task_1539356598>type command_000000_wrapper.bat
:: This script runs command 0 defined in TaskId N9obQV88T729DjWUuLUf8w...
@echo off
set SPARSE_CHECKOUT_BASE64=LyoKIS90ZXN0cy93cHQvbWV0YWRhdGEKIS90ZXN0cy93cHQvbW96aWxsYQohL3Rlc3RzL3dwdC93ZWJnbAohL3Rlc3RzL3dwdC93ZWItcGxhdGZvcm0tdGVzdHMKL3Rlc3RzL3dwdC93ZWItcGxhdGZvcm0tdGVzdHMvdG9vbHM=
set GIT_URL=https://github.com/servo/servo.git
set GIT_REF=refs/heads/auto
set GIT_SHA=a4726ed719e13a2ee45d56e109caba0f572941b2
set RUST_BACKTRACE=1
set RUSTFLAGS=-Dwarnings
set CARGO_INCREMENTAL=0
set LIB=%HOMEDRIVE%%HOMEPATH%\gst\gstreamer\1.0\x86_64\lib;%LIB%
set TASK_ID=N9obQV88T729DjWUuLUf8w
cd "C:\Users\task_1539356598"
set errorlevel=
call C:\Users\task_1539356598\command_000000.bat 2>&1
@echo off
set tcexitcode=%errorlevel%
set > C:\Users\task_1539356598\env.txt
cd > C:\Users\task_1539356598\dir.txt
exit /b %tcexitcode%
```

```batch
C:\Users\task_1539356598>type command_000000.bat
@echo on
set PATH=%HOMEDRIVE%%HOMEPATH%\wix;%PATH%
```

The failure logs showed:

```
[taskcluster 2018-10-11T16:04:38.212Z] Executing command 0: set PATH=%HOMEDRIVE%%HOMEPATH%\wix;%PATH%
[taskcluster 2018-10-11T16:04:38.216Z]    Exit Code: -2
```

Note, that we didn't see `set PATH=...` in the logs, which suggests to me that the failure either occurred when trying to execute `command_000000_wrapper.bat` or during execution of `command_000000_wrapper.bat` prior to it calling `command_000000.bat`.

The only lines of the script I see in `command_000000_wrapper.bat` that could produce an `Access is denied.` error are:

```batch
cd "C:\Users\task_1539356598"
```

or

```batch
call C:\Users\task_1539356598\command_000000.bat 2>&1
```

If it was one of these, then either the task user did not have permission to `cd` into the task directory (in which case it wouldn't have been able to execute the wrapper script), or it didn't have permission to execute the `command_000000.bat` file.

My suspicion is that it couldn't call the wrapper script at all, since the mechanics of making the wrapper script executable are the same as making the target script executable, and these steps happen in sequential order in the same thread.

**Comment by petemoore** [comment]
@SimonSapin Shall we set [`shutdownMachineOnInternalError`](https://github.com/taskcluster/generic-worker/blob/v10.11.3/main.go#L280-L285) to `false` and wait for this to happen again?

**Comment by SimonSapin** [comment]
@petemoore Would a worker that encounters an internal error stop claiming new tasks? Then that sounds like a good plan to figure this out but perhaps when someone is watching out for similar failures rather than during a weekend, to avoid keeping machines running idle needlessly for too long.

**Comment by petemoore** [comment]
> @petemoore Would a worker that encounters an internal error stop claiming new tasks? Then that sounds like a good plan to figure this out but perhaps when someone is watching out for similar failures rather than during a weekend, to avoid keeping machines running idle needlessly for too long.

Yes, it will just stay alive, but not doing anything. The provisioner hard kills any instances still alive 96 hours after spawning them, so there is an upper limit on how long any single instance will stay idle, but this should be enough time for us to investigate.

Doing this during the week indeed sounds like a good approach. Thanks!

**Comment by petemoore** [comment]
Note, another option is making a build of generic-worker that provides more debugging information in this failure case.

**Comment by SimonSapin** [comment]
Ok, so two possible approaches:

* Set `shutdownMachineOnInternalError: false` on `servo-win2016` and wait for this error to occur again in normal CI tasks. Might take a lot longer but is also much easier (mostly passive).
* Or make an AMI with that debug build, set up a dedicated worker type with that AMI and `shutdownMachineOnInternalError: false`, and make it repeatedly run a short task in order to try and maximize chances of reproducing

**Comment by petemoore** [comment]
> Ok, so two possible approaches:
> 
>     * Set `shutdownMachineOnInternalError: false` on `servo-win2016` and wait for this error to occur again in normal CI tasks. Might take a lot longer but is also much easier (mostly passive).
> 
>     * Or make an AMI with that debug build, set up a dedicated worker type with that AMI and `shutdownMachineOnInternalError: false`, and make it repeatedly run a short task in order to try and maximize chances of reproducing

Yes, I'd propose we go with the first option, and if that doesn't work out, we can try the second.

@SimonSapin Let's actively monitor for task runs that are resolved as `exception/claim-expired` or `exception/internal-error` for servo project. If I've filled this in correctly, it should be possible by keeping a browser tab open like [this](https://tools.taskcluster.net/pulse-inspector?bindings%5B0%5D%5Bexchange%5D=exchange%2Ftaskcluster-queue%2Fv1%2Ftask-exception&bindings%5B0%5D%5BroutingKeyPattern%5D=primary.%2A.%2A.%2A.%2A.aws-provisioner-v1.servo-win2016.%23).

**Comment by SimonSapin** [comment]
Alright, I’ve disabled `shutdownMachineOnInternalError` on `servo-win2016`.

Does this inspector only show messages while the browser tab is open and the laptop not sleeping?

**Comment by petemoore** [comment]
> Alright, I’ve disabled `shutdownMachineOnInternalError` on `servo-win2016`.
> 
> Does this inspector only show messages while the browser tab is open and the laptop not sleeping?

@SimonSapin Yes, but if you don't want to miss messages, you can create a durable queue that binds to the same AMQP 0.91 exchange. The Pulse Inspector is just a web interface that binds non-durable queues to the given topic exchanges. See [`taskException` exchange reference](https://docs.taskcluster.net/docs/reference/platform/taskcluster-queue/references/events#taskException) and [RabbitMQ guidance](https://www.rabbitmq.com/tutorials/amqp-concepts.html).
