### ISSUE TITLE
Implement Audio constructor

### ISSUE THREAD

**Issue by jdm** [servo/servo#21929]
Spec:
https://html.spec.whatwg.org/multipage/media.html#the-audio-element (see NamedConstructor usage in WebIDL)
https://html.spec.whatwg.org/multipage/media.html#dom-audio

Code: `components/script/dom/webidls/HTMLAudioElement.webidl`, `components/script/dom/htmlaudioelement.rs`

Tests:
* `./mach test-wpt https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/html/semantics/embedded-content/the-audio-element`
* `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements`
* `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.https.html`
* (see https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations for dealing with unexpected results)

Now that we support actual audio output, we should implement the missing constructor that is used by many websites to create an HTMLAudioElement.

**Comment by HrushikeshBodas** [comment]
@highfive : assign me
@jdm how can I get started? I have forked and cloned the repo

**Comment by jdm** [comment]
@HrushikeshBodas There's a similar named constructor for HTMLImageElement, so you can use that as a guide - https://github.com/servo/servo/blob/819212e3b6817a60c83fe67fe758c32214f3fd11/components/script/dom/webidls/HTMLImageElement.webidl#L6 is the webidl, and https://github.com/servo/servo/blob/819212e3b6817a60c83fe67fe758c32214f3fd11/components/script/dom/htmlimageelement.rs#L1234-L1248 is the implementation that matches it. https://html.spec.whatwg.org/multipage/embedded-content.html#dom-image is the specification that describes what the implementation is supposed to do.

**Comment by jdm** [comment]
There was a question on IRC about calling setting the media element's src from this new constructor. You will need to import the HTMLMediaElementMethods trait in order to call the `SetSrc` method like so: `audio_element.upcast::<HTMLMediaElement>().SetSrc(...)`.
