### ISSUE TITLE
Android's address bar is confused by localhost

### ISSUE THREAD

**Issue by nox** [servo/servo#21948]
I first run:

```
./mach run --android --release http://localhost:8000/examples/webgl_animation_cloth.html
```

Then I tap on the address bar and press enter.

Servo then tried to load that same URL but with domain `www.localhost.com` and fails.

**Comment by jdm** [comment]
We'll need to improve [this heuristic](https://github.com/servo/servo/blob/master/support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java#L103-L107).
