### ISSUE TITLE
Evil Ad demo particle animations not working correctly

### ISSUE THREAD

**Issue by atouchet** [servo/servo#21956]
URL: https://servo.org/bhtml-newtab/webrender-demos/evil_ad/physics/with-ad.html

![Image](https://i.imgur.com/ImERqaT.gif)

This issue first occurred in the [2018-10-16](http://servo-builds.s3.amazonaws.com/) nightly build. Tested in Windows 10.

**Comment by emilio** [comment]
Is this a regression from #20757?

**Comment by atouchet** [comment]
@emilio I suspect so although I have not verified exactly which PR caused it.

**Comment by atouchet** [comment]
@emilio I've looked into this a bit more and from what I can tell the issue is that now when an animation is triggered instead of stopping when finished it enters an infinite loop. For example this is what happens after hovering the cursor over the sign up button on the GitHub homepage:

![Image](https://i.imgur.com/XC8F2pm.gif)

This is affecting a large number of sites and not just the few examples I've posted already.

**Comment by emilio** [comment]
Right, but these are transitions, not keyframes, right? I'll revert the transitions changes.

**Comment by atouchet** [comment]
I believe so. Looking at that GitHub button it uses:

```css
.btn-mktg {
    display: inline-block;
    padding: 16px 24px;
    font-size: 14px;
    font-weight: 500;
    color: #fff;
    background-color: #1277eb;
    border: 0;
    border-radius: 3px;
    transition: 0.2s;
```

**Comment by emilio** [comment]
https://github.com/servo/servo/pull/21971 should fix this by going back to the previous behavior, which is not starting transitions... Oh well

**Comment by emilio** [comment]
(Sorry for not having time to investigate more and fix all of this stuff)

**Comment by atouchet** [comment]
This is fixed now.
