### ISSUE TITLE
WebGL performance is not good on Oculus

### ISSUE THREAD

**Issue by jdm** [servo/servo#21966]
This is worrying, because the perf for [this three.js example](https://threejs.org/examples/webgl_animation_cloth.html) is _great_ on my Pixel 2, but probably only 10 FPS on my Oculus Go. We should add some logging to see what the FxR integration thinks the FPS is; maybe WR is rendering at a good FPS but the surface isn't being composited at the same speed.

**Comment by jdm** [comment]
That same example run on a pixel 1 totally freezes.

**Comment by jdm** [comment]
```
11-01 15:18:31.409 18451 18561 D simpleservo: THREE.WebGLRenderer
11-01 15:18:31.409 18451 18561 D simpleservo: 98
11-01 15:18:31.418 18451 18576 E simpleservo: Last GL operation failed: GetShaderPrecisionFormat(35633, 36338, WebGLSender(..))
11-01 15:18:31.418 18451 18561 D simpleservo: thread 'WebGLThread' panicked at 'assertion failed: `(left == right)`
11-01 15:18:31.418 18451 18561 D simpleservo:   left: `1280`,
11-01 15:18:31.418 18451 18561 D simpleservo:  right: `0`: Unexpected WebGL error: 0x500 (1280)', components/canvas/webgl_thread.rs:1231:9
11-01 15:18:31.418 18451 18561 D simpleservo: note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jdm** [comment]
That happens on multiple three.js examples, so that's not great!

**Comment by mbrubeck** [comment]
I'm not sure whether it'll help with this specific test case, but the Firefox performance team found that adding `"-Wl,-Bsymbolic"` to the linker flags provided some performance wins on devices with CPUs similar to the Oculus Go:

https://bugzilla.mozilla.org/show_bug.cgi?id=1500154

**Comment by jdm** [comment]
Moved the Pixel1 problem over to #22082.

**Comment by paulrouget** [comment]
> 10 FPS on my Oculus Go

Can you add some logs and check how often we go through https://github.com/servo/servo/blob/200cc8aa6b8a0c14b3390f1ff02a62f1fce9ac31/ports/libsimpleservo/src/jniapi.rs#L346 per seconds and how long we spend in https://github.com/servo/servo/blob/200cc8aa6b8a0c14b3390f1ff02a62f1fce9ac31/ports/libsimpleservo/src/jniapi.rs#L349 ?

**Comment by larsbergstrom** [comment]
Does this happen with a Servo-only app on the Go, too?

We have a few fixes in-flight that have a _dramatic_ impact on Firefox Reality performance for content shown in 2D while the browser UI is up, especially https://github.com/MozillaReality/FirefoxReality/pull/652, but also https://github.com/MozillaReality/FirefoxReality/pull/702. Previously/currently we are significantly taxing the device and not leaving much extra capacity for the experience.

**Comment by Manishearth** [comment]
I'm trying to reproduce this, and I'm getting flickering of the white background, but it's definitely not 10FPS.

**Comment by pwnorbitals** [comment]
Has this been reproduced since then ? I'd guess not, but worth an ask

**Comment by jdm** [comment]
We don't support android any more.
