### ISSUE TITLE
servo does not run

### ISSUE THREAD

**Issue by riko781** [servo/servo#21960]
My pc :
Linux T1700-R 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

When i'm running servo with this command ./servo
I have this return ./servo: symbol lookup error: ./servo: undefined symbol: gst_player_media_info_get_number_of_video_streams

**Comment by tigercosmos** [comment]
I try on Ubuntu 16.04 and 18.04
- 16.04: same issue
- 18/04: it works

**Comment by tigercosmos** [comment]
seems same to  #21970

**Comment by riko781** [comment]
I have to use an older version of gstreamer?

**Comment by tigercosmos** [comment]
follow travis setup might probably help

https://github.com/servo/servo/blob/304e09732ea8a47cdfcc5e9953adfc5fb754e5e0/.travis.yml#L20-L26

**Comment by riko781** [comment]
ok thanks I would try to work

**Comment by tigercosmos** [comment]
The pre-build Servo should be able to work without any setup. I guess the pre-build can work once #21970 has been solved.

**Comment by CYBAI** [comment]
See https://github.com/servo/servo/issues/21970#issuecomment-430877731

**Comment by tigercosmos** [comment]
keep tracking at #21970
