### ISSUE TITLE
point-size.html fails with osmesa

### ISSUE THREAD

**Issue by nox** [servo/servo#21981]
This test locally passes with https://github.com/servo/servo/pull/21961 if you make Servo spawn an actual window. It fails if you pass `--no-pause` to `mach`, which suggests it fails when osmesa is used.

**Comment by SimonSapin** [comment]
OSMesa is no longer used since https://github.com/servo/servo/pull/25853, is this still relevant?

**Comment by jdm** [comment]
It is not.
