### ISSUE TITLE
Support for market:// urls

### ISSUE THREAD

**Issue by ferjm** [servo/servo#21992]
Clicking on a `market://` (i.e. market://details/?id=org.mozilla.firefox&referrer=utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dmozilla-org ) url shows the `Could not load the requested page: Unexpected scheme` error page. If I am not wrong, it should open the Android's Play Store app instead.

**Comment by paulrouget** [comment]
For these urls, the embedder should interrupt loading and open the play store.

We need to call a host callback on `AllowNavigation` (see  ports/libsimpleservo/src/api.rs) and implement the callback in Java. In the callback, if it's a market url, we should return false and open the play store. 

A good way to understand how to implement this is to look at how the page title is [sent from Servo](https://github.com/servo/servo/blob/2304f02123038a2e729bc90a2e2db9a795f30158/ports/libsimpleservo/src/api.rs#L337) to [the Java app](https://github.com/servo/servo/blob/2304f02123038a2e729bc90a2e2db9a795f30158/support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java#L144) through the [JNI layer](https://github.com/servo/servo/blob/2304f02123038a2e729bc90a2e2db9a795f30158/ports/libsimpleservo/src/jniapi.rs#L360).

I can help whoever wants to work on this.

**Comment by paulrouget** [comment]
We need to parse the URL in the Java code and interrupt loading and open the play store in this case.

We need to call a Java callback from the [AllowNavigation message](https://github.com/servo/servo/blob/2304f02123038a2e729bc90a2e2db9a795f30158/ports/libsimpleservo/src/api.rs#L350).

To see how to call a callback from a servo message, see how we call onTitleChange:

1. https://github.com/servo/servo/blob/2304f02123038a2e729bc90a2e2db9a795f30158/ports/libsimpleservo/src/api.rs#L337
2. https://github.com/servo/servo/blob/2304f02123038a2e729bc90a2e2db9a795f30158/ports/libsimpleservo/src/jniapi.rs#L360
3. https://github.com/servo/servo/blob/2304f02123038a2e729bc90a2e2db9a795f30158/support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java#L145

**Comment by akshitkrnagpal** [comment]
Hey
I am new and would like to work on this. 😄 
@highfive: assign me

**Comment by paulrouget** [comment]
@akshitkrnagpal The first step is to build Servo for Android: https://github.com/servo/servo/wiki/Building-for-Android
