### ISSUE TITLE
Intermittent failure in /css/CSS2/positioning/bottom-113.xht (one of the screenshots is a big black box)

### ISSUE THREAD

**Issue by jdm** [servo/servo#22062]
Testcase:
<img width="811" alt="screen shot 2018-10-31 at 7 48 07 am" src="https://user-images.githubusercontent.com/27658/47786188-5e247500-dce1-11e8-80bc-8857309ca525.png">

Reference:
<img width="819" alt="screen shot 2018-10-31 at 7 48 18 am" src="https://user-images.githubusercontent.com/27658/47786192-62509280-dce1-11e8-91fe-064bc197017a.png">

The reference rendering is in the wrong here, and it's rather confusing.

**Comment by jdm** [comment]
I found another failure like this in /css/CSS2/normal-flow/height-050.xht. The non-reference rendering was a big black window.

**Comment by jdm** [comment]
Also seen in the reference rendering for /css/CSS2/fonts/font-148.xht.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/22158#issuecomment-437957255 has the results of my regression range calculations so far.

**Comment by jdm** [comment]
#21613 is looking pretty guilty. I've run a lot of try pushes on revisions directly before that PR and a lot of pushes on revisions after it and the evidence seems incontrovertible.

**Comment by jdm** [comment]
I spoke too soon. #21613 is absolved.

**Comment by jdm** [comment]
I'm running regression tests on servo-linux1. So far I have reproduced it on Nov 13 and have not reproduced it on Oct 1.

**Comment by jdm** [comment]
I have reproduced it on Oct 19 (2304f02123038a2e729bc90a2e2db9a795f30158).

**Comment by jdm** [comment]
Have not reproduced it on Oct 10 (35bf180dcb588f02652b2031316713f72d12be62).

**Comment by jdm** [comment]
Reproduced it on Oct 15 (f88f3122249c5284d43caeac8580012189645bfc).

**Comment by jdm** [comment]
Have not reproduced it on Oct 13 (e4657c14961db58bedd0a13ba72667bcb470f34d).

**Comment by jdm** [comment]
Bisecting between e4657c1 and f88f312, I have reproduced on a949e9e1e81c42730dab3fdaa30190a46c6da82e.

**Comment by jdm** [comment]
I am doubting the results for Oct 13, so I'm rerunning that.

**Comment by jdm** [comment]
Reproduced the problem on Oct 13 (e4657c14961db58bedd0a13ba72667bcb470f34d).

**Comment by jdm** [comment]
Could not reproduce the problem on 79f02919244201e05894176e1599e45b2ac182a1 (Oct 11).

**Comment by jdm** [comment]
Reproduced on 8902a267219b16909f132f3b6fff0ed6f1fa08c5.

**Comment by jdm** [comment]
Reproduced on fa94fc71464dd6053ae28dc5d69f9bf51a5f35e8.

**Comment by jdm** [comment]
I'm pretty sure that this is a regression from https://github.com/servo/servo/pull/21725/.

**Comment by jdm** [comment]
Cannot reproduce after >24 attempts on 69e524381043bc958586a3e9449bac58cd03c07c. This looks solid to me!

**Comment by jdm** [comment]
Sadly the changes in https://github.com/servo/servo/pull/21725 don't look suspicious, which leaves us with a potential regression range in WR from https://github.com/servo/webrender/commit/38f3b57cd9bf2c6fb736d14832fee87eb576e322 to https://github.com/servo/webrender/commit/923ee495bd9b0fda8a4a94c5a6cf42e2f0548731, which covers about two months.

**Comment by jdm** [comment]
I predict it's going to be https://github.com/servo/webrender/pull/2992 and that we'll need to fix https://github.com/servo/servo/issues/21896.

**Comment by jdm** [comment]
https://github.com/servo/webrender/commit/2d082df7871bd7dfa03e46a3304db57f64e62770 looks extremely relevant, however.

**Comment by jdm** [comment]
Verified that the regressing change is https://github.com/servo/webrender/commit/926907206c4d738eef7c2088104b1fc5cb8d1340 as expected. I'm running a lot of reftests overnight with #22219 applied to verify that it fixes the issue.

**Comment by jdm** [comment]
I obtained the log of a failed test run that included -Zdump-display-list for https://searchfox.org/mozilla-central/source/testing/web-platform/tests/css/CSS2/backgrounds/background-root-001.xht. It looks like this:
```
┌ Display List
│  ├─ ClipScrollNodes
│  │  ├─ ClipScrollNode { parent_index: ClipScrollNodeIndex(0), clip: ClippingRegion::Empty, content_rect: TypedRect(0.0×0.0 at (0.0,0.0)), node_type: Placeholder }
│  │  └─ ClipScrollNode { parent_index: ClipScrollNodeIndex(0), clip: ClippingRegion::Empty, content_rect: TypedRect(0.0×0.0 at (0.0,0.0)), node_type: Placeholder }
│  ├─ Items
│  │  ├─ PushStackingContext(StackingContext at TypedRect(800.0×600.0 at (0.0,0.0)) with overflow TypedRect(800.0×600.0 at (0.0,0.0)): StackingContextId(0)) StackingContext: StackingContextId(0) ClippingAndScrolling { scrolling: ClipScrollNodeIndex(1), clipping: None }
│  │  ├─ Rectangle @ TypedRect(800.0×600.0 at (0.0,0.0)) TypedRect(800.0×600.0 at (0.0,0.0)) StackingContext: StackingContextId(0) ClippingAndScrolling { scrolling: ClipScrollNodeIndex(1), clipping: None }
│  │  ├─ Rectangle @ TypedRect(784.0×18.633333 at (8.0,16.0)) TypedRect(784.0×18.633333 at (8.0,16.0)) StackingContext: StackingContextId(0) ClippingAndScrolling { scrolling: ClipScrollNodeIndex(1), clipping: None }
│  │  ├─ Rectangle @ TypedRect(784.0×18.633333 at (8.0,16.0)) TypedRect(784.0×18.633333 at (8.0,16.0)) StackingContext: StackingContextId(0) ClippingAndScrolling { scrolling: ClipScrollNodeIndex(1), clipping: None }
│  │  ├─ Text @ TypedRect(463.75×18.616667 at (8.0,16.016666)) TypedRect(17895698.0×17895698.0 at (-8947849.0,-8947849.0)) StackingContext: StackingContextId(0) ClippingAndScrolling { scrolling: ClipScrollNodeIndex(1), clipping: None }
│  │  └─ PopStackingContext(StackingContextId(0) StackingContext: StackingContextId(0) ClippingAndScrolling { scrolling: ClipScrollNodeIndex(1), clipping: None }
```
Which looks like the expected display list for that test file.

**Comment by jdm** [comment]
@nical Do you have any ideas why forcing the use of the scene builder thread would cause Servo to intermittently take completely black screenshots of some reftests?

**Comment by nical** [comment]
The scene builder thread makes scene building asynchronous which means that we can't set the display list and then screenshot the next frame (another scrolling/animation frame could be causing rendering to happen in between). I don't know how servo handles screenshots but this is the first place I'd look.

There's a `Transaction::notify` API that can be useful for inserting arbitrary code (such as synchronization) when a transaction reaches specific points of the pipeline including when it's been rendered which might be useful here if anything needs to be done about synchronization.

**Comment by jdm** [comment]
Complication: the transactions that set a display list are initiated in the content process and then serialized over IPC to the chrome process. In the process, this silently discards any notifiers that were added to the transaction.

**Comment by nical** [comment]
Ah, right. The notify stuff passes closures which doesn't work in a cross-process setup. The other similar mechanism is ApiMsg::ExternalEvent, that uses an opaque handle which can be used across processes. It's passed to the `RenderNotifier::external_event` hook and the meaning of the event is really up to the embedder. It's not part of the transaction but it goes through the same queues as transactions and does not race ahead of them so you could use this as a mechanism to know that the asynchronous part of scene building has happened. by assigning meanings like "render and screenshot" to ExternalEvent values.
It wouldn't be hard to add it (or something similar) to transactions themselves if it makes things easier for servo.

**Comment by jdm** [comment]
Happily, this stopped affecting us earlier this year.
