### ISSUE TITLE
Allow unused import warnings in debug builds

### ISSUE THREAD

**Issue by jdm** [servo/servo#2206]
It's nice not to get bogged down every time, but it's still good to see them. We should look for a way to conditionally deny them for opt builds.

**Comment by SimonSapin** [comment]
I think this should be a feature request on Cargo to provide a way in [`[profile.*]` sections of `Cargo.toml`](http://doc.crates.io/manifest.html#the-[profile.*]-sections) to have `--allow` flags and the like passed to rustc.
