### ISSUE TITLE
Magic Leap build in CI

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#22078]
We're currently not running any tests for the `--magicleap` build in CI. Steps to do this:

- [X] Put the ML SDK on S3, so it can be provisioned by salt.
- [x] Install the SDK on the Mac builders. (https://github.com/servo/saltfs/pull/908)
- [x] Add a CI job to run the build. (#22117 and https://github.com/servo/saltfs/pull/910)

AFAICT there's not really any way to run a smoke test, since we don't have ML hardware in CI, but at least this would keep the build alive.

**Comment by asajeffrey** [comment]
Should we also package the ML app and do a nightly release for it? Or hold off on that until we're happier with the UI?

**Comment by jdm** [comment]
I would be happy to start publishing nightly builds with #22076 merged and these checkboxes checked.

**Comment by jdm** [comment]
By which I mean, yes, #22079 would be necessary before we publish nightly builds.

**Comment by asajeffrey** [comment]
All merged now, though we're not gating on the ML build.
