### ISSUE TITLE
getShaderPrecisionFormat does not validate shaderType argument

### ISSUE THREAD

**Issue by jdm** [servo/servo#22080]
We're supposed to return InvalidEnum if the shader type is not one of FRAGMENT_SHADER or VERTEX_SHADER.

Code: `components/script/dom/webglrenderingcontext.rs`
Tests: `./mach test-wpt tests/wpt/webgl/tests/deqp/functional/gles3/negativestateapi.html`

**Comment by jdm** [comment]
Bah, I don't think we can actually run those tests right now. That's unfortunate.

**Comment by jdm** [comment]
@nox Do you remember why you added https://github.com/servo/servo/blob/master/tests/wpt/webgl/meta/deqp/__dir__.ini?

**Comment by jdm** [comment]
Ah, it appears that it's an incredibly complex test framework and all of the tests fail and are testing webgl2 things. That's a good reason.

**Comment by HrushikeshBodas** [comment]
@jdm is this still an easy-bug? 
Will it be possible for you to mentor this bug?
@highfive: assign me

**Comment by jdm** [comment]
@HrushikeshBodas Yes. Let's just ignore the test situation and see what happens when we run the full testsuite against the PR when you open it :)

**Comment by AlexCreamer** [comment]
@HrushikeshBodas Can I work on this with you?

**Comment by jabedude** [comment]
@HrushikeshBodas I'd like to help as well. Could I open the PR?

**Comment by HrushikeshBodas** [comment]
Sorry for the late response. 
Sure! Take up this issue. I can't work on this because I have end semesters going on.

**Comment by jabedude** [comment]
@highfive: assign me
