### ISSUE TITLE
DuckDuckGo search results in "forbidden"

### ISSUE THREAD

**Issue by atouchet** [servo/servo#22090]
URL: https://duckduckgo.com/html

Steps to reproduce:

1. Load https://duckduckgo.com/html
2. Search something.
3. The search result page does not appear but instead the text "forbidden" is displayed.

This issue first occurred in the [2018-11-02](http://servo-builds.s3.amazonaws.com/) nightly build. Tested in Windows 10.

**Comment by atouchet** [comment]
This issue also occurs using the https://duckduckgo.com/ version of the site.

**Comment by atouchet** [comment]
The search page seems to load normally when not navigated to from the DuckDuckGo home page. For example searching something using the Servo URL prompt still works fine.

**Comment by atouchet** [comment]
This is now only happening with the https://duckduckgo.com/html version of the site.

**Comment by jdm** [comment]
Ok, it's not the presence of the header itself. It's the presence of the :443 in the header, since when I set network.http.sendOriginHeader to 1 in Firefox the site still loads.

**Comment by jdm** [comment]
As expected, this is a regression from https://github.com/servo/servo/pull/21644.
