### ISSUE TITLE
Android nightly fails to render any web

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22114]
Composition seems to be broken in today's Android nightly (or a local build from master). I can only get half rendered views for all sites that I've tried. For example:

![screenshot_20181105-140827](https://user-images.githubusercontent.com/480202/48000290-501d8c80-e105-11e8-8304-1eebab6e78ed.png)

![screenshot_20181105-140640](https://user-images.githubusercontent.com/480202/48000311-5c094e80-e105-11e8-8d9d-f3bada88c8a7.png)

I see this on the logcat:

```
11-05 14:09:39.440  4993  5013 W simpleservo: Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }).
```

**Comment by paulrouget** [comment]
Started with 024b40b39d3848f1a1f7020bd7ed8c901817f09c

**Comment by paulrouget** [comment]
With: `"data:text/html,<style>body{background:red}</style>foobar<img src=https://servo.org/screenshot.png>" `

The image is just a black square, there is no text, the background is red.

**Comment by paulrouget** [comment]
I see nothing suspicious in the logs.

**Comment by Darkspirit** [comment]
I would suspect this line: https://github.com/servo/servo/commit/024b40b39d3848f1a1f7020bd7ed8c901817f09c#diff-d2ede298d9a75c849170d6ef285eda1eL4078

WebRender changelog: https://github.com/servo/webrender/compare/923ee495bd9b0fda8a4a94c5a6cf42e2f0548731...f0221fabc87c5b69a49689eeaa69bd5c380599f0
Probably https://github.com/servo/webrender/pull/3195#issuecomment-430746224
Try making an update that includes https://github.com/servo/webrender/pull/3239.
