### ISSUE TITLE
Missing sidebar content on planet.mozilla.org

### ISSUE THREAD

**Issue by jdm** [servo/servo#22137]
This is a regression between the 11/1 and 11/2 nightly builds.

**Comment by jdm** [comment]
From 11/1:
<img width="1136" alt="screen shot 2018-11-07 at 1 09 19 pm" src="https://user-images.githubusercontent.com/27658/48151065-6014a800-e28e-11e8-81e2-421f7b69998f.png">

From 11/2:
<img width="1136" alt="screen shot 2018-11-07 at 1 08 22 pm" src="https://user-images.githubusercontent.com/27658/48151057-5b4ff400-e28e-11e8-9527-83b1782f6b9e.png">

**Comment by jdm** [comment]
My first suspicion is the hyper upgrade from #21644.

**Comment by jdm** [comment]
The only meaningful PR that merged was the hyper upgrade.

**Comment by atouchet** [comment]
@jdm are you still able to reproduce this? This issue is fixed for me in the latest nightly build.

**Comment by jdm** [comment]
Nope!
