### ISSUE TITLE
Wikipedia incorrectly rendered

### ISSUE THREAD

**Issue by pyfisch** [servo/servo#22138]
Looks like a lot of CSS is not loaded/applied.
![](https://user-images.githubusercontent.com/2781017/48152194-7be67100-e2c3-11e8-91c5-044cefb4d169.png)

**Comment by jdm** [comment]
I can't reproduce this when loading https://en.wikipedia.org in the latest nightly on macOS.

**Comment by jdm** [comment]
<img width="1136" alt="screen shot 2018-11-07 at 1 49 55 pm" src="https://user-images.githubusercontent.com/27658/48153365-07480e00-e294-11e8-951b-09cf2a2c39cd.png">

**Comment by atouchet** [comment]
I can't reproduce this issue on Windows 10 either.

![Image](https://i.imgur.com/DbT06Rc.png)

**Comment by pyfisch** [comment]
I am using Ubuntu 18.04.

**Comment by atouchet** [comment]
@pyfisch does the issue occur if you use X11 instead of Wayland?

**Comment by pyfisch** [comment]
Yes it does.

**Comment by atouchet** [comment]
Is this a recent regression? I ran into some issues with certain pages not loading styling properly after the hyper update but I don't know if that's related to the issue here.

**Comment by pyfisch** [comment]
It is fairly recent. Is there any way to download old nightly servo builds?

**Comment by atouchet** [comment]
I am not 100% sure about Ubuntu but I get old Windows nightlies from: http://servo-builds.s3.amazonaws.com/

**Comment by atouchet** [comment]
@pyfisch does this still happen in the latest nightly build? #22144 fixed a few issues I was running into.

**Comment by pyfisch** [comment]
The problem persists. Version `Servo 0.0.1-bb2c5e3`

**Comment by pwnorbitals** [comment]
@pyfisch Can still confirm you can reproduce ?

**Comment by pyfisch** [comment]
Can no longer reproduce it.
