### ISSUE TITLE
Reduce duplication in WrappedBody::poll

### ISSUE THREAD

**Issue by jdm** [servo/servo#22145]
It should be possible to extract the duplicated code for each of the decoders into a function that is generic over the decoder argument using the Read trait.

**Comment by Briando** [comment]
Hi~ I am a newbie on this project and also not familiar with rust programming language.
I really hope to have a chance contributing this project.
Is it possible to assign this issue to me?
I think that I also need some advice while resolving this issue.

**Comment by jdm** [comment]
Sure, you're welcome to try. [This part of the Rust Book](https://doc.rust-lang.org/book/second-edition/ch10-02-traits.html#trait-bounds) describes how I was imagining we could use the `Read` trait to create a generic function that encapsulates the duplicated code.

**Comment by jdm** [comment]
The code in question is [this block](https://github.com/servo/servo/blob/0a11e10a0ffaaddfc4baed9e5b22891fdab7588c/components/net/connector.rs#L82-L110), with more being added in #22144.

**Comment by jdm** [comment]
@Briando are you still working on this?

**Comment by jdm** [comment]
WrappedBody no longer exists.
