### ISSUE TITLE
Implement GetOwnPropertyNames proxy trap

### ISSUE THREAD

**Issue by jdm** [servo/servo#2215]
https://github.com/mozilla-servo/rust-mozjs/pull/33 is relevant. So is [BaseDOMProxyHandler::getOwnPropertyNames](http://mxr.mozilla.org/mozilla-central/source/dom/bindings/DOMJSProxyHandler.cpp#255) and [CGDOMJSProxyHandler_ownPropNames](http://mxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py#9039).

**Comment by frewsxcv** [comment]
Relevant to 6390
