### ISSUE TITLE
Transparent border API for TimeWarp Layers

### ISSUE THREAD

**Issue by MortimerGoro** [servo/servo#22195]
We are going to land Oculus TimeWarp layers soon on FxR, and for aliasing reasons TimeWarp layers require a transparent border on all the textures used in the UI, the browser window included.

This is how it's implemented in Gecko compositor
https://phabricator.services.mozilla.com/D11717

**Comment by paulrouget** [comment]
That should not be too difficult. The WR document only needs to be resized and shifted. But this will require to fix https://github.com/servo/servo/issues/21350.

**Comment by paulrouget** [comment]
This is now necessary. Will be looking at this soon.

**Comment by paulrouget** [comment]
Blocked on #21350.

**Comment by paulrouget** [comment]
Fixed by https://github.com/servo/servo/pull/23002
