### ISSUE TITLE
Enable taking stack snapshots of other threads: The Linux/Android edition

### ISSUE THREAD

**Issue by gterzian** [servo/servo#22203]
Follow up on https://github.com/servo/servo/issues/16740

Code in `components/background_hang_monitor/sampler.rs`(yet to be merged from https://github.com/servo/servo/pull/21673)

The suspending/resuming of a thread is (perhaps only partly) implemented, and it is mainly accessing the instruction and frame pointers in the registers, as well as perhaps the stack walking, that needs to be (re-)implemented for Linux/Android.

I think target architectures for Linux would be `x86_64`, and for Android it would be `x86` for the emulator, and `arm` for the devices. 

It appears that [`libc`](https://docs.rs/libc/0.2.43/x86_64-unknown-linux-gnu/libc/) would be the appropriate tool in both cases. 

See also the Gecko implementation at https://dxr.mozilla.org/mozilla-central/rev/b0b856065d5b7ad2996f707e6e797d0d72afd803/tools/profiler/core/platform-linux-android.cpp#85

**Comment by nikhilm** [comment]
FWIW, I have a work in progress library (i only made it publicly viewable so i could post this, heh! still needs documentation and so on) for a sampling profiler. https://bitbucket.org/nikhilm/vignette.
It already implements Linux thread suspension and resume, and was actually inspired by the gecko implementation. I work on this really on and off, so I won't be able to fix this issue itself, but feel free to copy the code from https://bitbucket.org/nikhilm/vignette/src/master/src/lib_linux.rs

**Comment by gterzian** [comment]
@nikhilm thanks! 

Ok I'll use your implementation for linux/android, and restructure the Mac-Os one to use similar `Frame`, `Sample` and `Sampler` abstractions, and put those in separate files. 

I assume your [`PosixSemaphore`](https://bitbucket.org/nikhilm/vignette/src/master/src/lib_linux.rs?fileviewer=file-view-default#lib_linux.rs-29) beats what I was trying to do with https://github.com/servo/servo/pull/21673/files#diff-b842b7c119b3715c2ee8e59aa3df11a2R32

Also, your implementation of `Sample.collect` fills in a gap in the current linux work in progress(I only go this to work on Mac). 

For the actual resolving of the frames, we can use [`backtrace::resolve`](https://docs.rs/backtrace/0.3.9/backtrace/fn.resolve.html)
