### ISSUE TITLE
Certain tiles on Browser.html new tab page not clickable

### ISSUE THREAD

**Issue by atouchet** [servo/servo#22216]
URL: https://servo.org/bhtml-newtab/newtab.html

Steps to reproduce:

1. Load https://servo.org/bhtml-newtab/newtab.html in a window.
2. Try to click on the tiles.
3. Only the bottom and rightmost tiles can be clicked on. It appears that the first ~840 horizontal pixels cannot be clicked on. This is consistent if the window is resized.

This issue first occurred in the [2018-11-11](http://servo-builds.s3.amazonaws.com/) nightly build. Tested in Windows 10.

**Comment by jdm** [comment]
This is a regression from https://github.com/servo/servo/pull/22156.

**Comment by jdm** [comment]
Relevant source for that page: https://github.com/servo/servo.org/blob/gh-pages/bhtml-newtab/newtab.html

**Comment by jdm** [comment]
```html
<html>
<head>
    <meta charset="utf-8">
    <title>Servo about:newtab</title>
    <style>
      * {
      margin: 0;
      padding: 0;
      border-width: 0;
      }

      .tiles {
      background-color: red;
      overflow: hidden;
      }
      .tile-image {
      background-color: green;
      border: 1px solid black;
      height: 100px;
      width: 160px;
      }
    </style>
</head>
<body>
  <div id="bg" class="tiles">
    <a id="anchor" target="_blank" rel="noopener noreferrer" href="https://duckduckgo.com/html/">
      <div id="tile" class="tile-image duckduckgo"></div>
    </a>
  </div>
  <script>
    onload = function() {
      console.log(document.elementFromPoint(10, 10).id);
    };
  </script>
</body>
```
In Firefox and pre-regression Servo this prints `tile`. In nightly Servo this prints `bg`.
