### ISSUE TITLE
cannot build fedora 29

### ISSUE THREAD

**Issue by roberto68** [servo/servo#22222]
I got this msg 
`
$ ./mach bootstrap
Traceback (most recent call last):
  File "./mach", line 96, in <module>
    main(sys.argv)
  File "./mach", line 24, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/roberto/bin/servo/python/mach_bootstrap.py", line 232, in bootstrap_command_only
    from servo.bootstrap import bootstrap
  File "/home/roberto/bin/servo/python/servo/bootstrap.py", line 17, in <module>
    from servo.util import extract, download_file, host_triple
  File "/home/roberto/bin/servo/python/servo/util.py", line 33, in <module>
    import certifi
ImportError: No module named certifi
`
I'm on python Python 2.7.15

**Comment by SkyHopeFashion** [comment]
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jdm** [comment]
@SkyHopeFashion Use `python -m pip` instead.

**Comment by jsaicha-personal** [comment]
@jdm i tried running "pip install certifi " it shows requirement already satified . But still iam getting the error

**Comment by jdm** [comment]
@jsaicha-personal Is there any difference if you use `pip3` instead?

**Comment by nccssocialmedia** [comment]
@jsaicha-personal please uninstall the certifi using `pip uninstall certifi`, then  `pip install certifi` 
it worked for me correctly.

thanks
