### ISSUE TITLE
could not load requested page: opening file failed

### ISSUE THREAD

**Issue by roberto68** [servo/servo#22226]
I tried it with both dev and release version, and multiple website can I get more information besides ` full backtrace` ?

**Comment by jdm** [comment]
How are you running Servo?

**Comment by roberto68** [comment]
`./mach run --dev full backtraces https://www.github.com ` did not work out but 
`./mach run -d -- https://github.com ` worked

**Comment by roberto68** [comment]
funny github runs fine everytime but google not and got this error ` mozilla::detail::MutexImpl::lock: pthread_mutex_lock failed: Invalid argument
`

**Comment by jdm** [comment]
Could you file a separate issue for the error you see when loading google?
