### ISSUE TITLE
google.com does not load

### ISSUE THREAD

**Issue by jdm** [servo/servo#22228]
According to previous IRC discussions, this happens because the decoder receives too little data and poisons any further decoding that might happen during page load.

https://mozilla.logbot.info/servo/20181108#c15587681-c15587715

@Eijebong Could you point to the code in reqwest that deals with this properly?

**Comment by Eijebong** [comment]
Sure, https://github.com/seanmonstar/reqwest/blob/master/src/async_impl/decoder.rs

I probably won't have time this week to fix this though

**Comment by Eijebong** [comment]
We might want to rewrite the `WrappedBody` thing to something that looks a lot like the `Decoder` in reqwest

**Comment by jdm** [comment]
I have a branch that integrates a Decoder based on the one from reqwest. It loads google just fine, but a unit test I wrote to catch the problem failed. This led me to file https://github.com/dropbox/rust-brotli-decompressor/issues/4 with a patch that makes the unit test pass.

**Comment by danielrh** [comment]
https://crates.io/crates/brotli-decompressor/2.1.2 should solve this issue
