### ISSUE TITLE
Latest WPT sync is busted

### ISSUE THREAD

**Issue by jdm** [servo/servo#22235]
cc @jgraham 

I have encountered three problems so far when syncing from https://github.com/web-platform-tests/wpt/commit/adc866b0f404ad8314ea251008dea4d3c6dce11d to https://github.com/web-platform-tests/wpt/commit/c51ac7cdef9b8ca83672e673d4de52115cdca850:
* every test appears to fail when I run `./mach test-wpt`
* I can no longer run `./mach test-wpt path/to/test.html`; the tests aren't found.
* the manifest contents have been rewritten as follows:
```diff
-   "2dcontext/conformance-requirements/2d.coordinatespace-manual.html": [
+   "tests/wpt/web-platform-tests/2dcontext/conformance-requirements/2d.coordinatespace-manual.html": [
     [
-     "/2dcontext/conformance-requirements/2d.coordinatespace-manual.html",
+     "/tests/wpt/web-platform-tests/2dcontext/conformance-requirements/2d.coordinatespace-manual.html",
      {}
     ]
    ],
```

I suspect these are all related.

**Comment by jdm** [comment]
My eye is on https://github.com/web-platform-tests/wpt/pull/13618 for the bustage, but there's a lot to wade through.

**Comment by jdm** [comment]
More specifically about the failures: not every test failures, but there are a lot of failing reftests that involve at least one hash that matches badcfc8affb8500816334bafe3566a95390bd4ce. Fun fact:
<img width="922" alt="screen shot 2018-11-20 at 4 52 05 pm" src="https://user-images.githubusercontent.com/27658/48805161-a33a3680-ece4-11e8-9a3a-5573c0742a69.png">

**Comment by jdm** [comment]
I suspect that is a side-effect of the manifest rewriting, causing various test support files to load not correctly.

**Comment by jgraham** [comment]
Is https://paste.rs/WpY any use? I think `./mach test-wpt --manifest-update` isn't working for your case, but I don't know if you were relying on that anyway. That set of changes at least unblocks the update I think, but some followup might be needed to figure out why the paths end up wrong when starting the update from inside wptrunner.

**Comment by jdm** [comment]
Those changes allow me to run tests from file paths and cause the tests to pass that previously were not passing.
