### ISSUE TITLE
Broken text on Android

### ISSUE THREAD

**Issue by Darkspirit** [servo/servo#22232]
Many letters disappear when scrolling down.
Device: Motorola Moto G5, Android 8.1.0
Screencast: https://youtu.be/aLHPtEsWBQI

last good:
https://dl.servo.org/nightly/android/2018-11-18T02:08:52Z-servoapp.apk 
https://build.servo.org/builders/android-nightly/builds/968

first bad:
https://dl.servo.org/nightly/android/2018-11-19T02:09:21Z-servoapp.apk
https://build.servo.org/builders/android-nightly/builds/969

regression range:
https://github.com/servo/servo/compare/34bf312e0caa030b1bbda7b27317c7112ff051c7...eb3af18581f457a51b397aed198ce107255c3bd3

**Comment by Darkspirit** [comment]
I don't know, but I would suspect the `glutin` update (EGL stuff / context sharing?):
https://github.com/servo/servo/commit/76195e0779469f29a5e27cd882e2bbe8b2c9d6dd#diff-80ec6384e35aa56591dd045a66523c36R47 (https://github.com/tomaka/glutin/compare/ee971068a70e542b669d8699fff7b75ce1237d1f...72e8c959c4ff538857d028167b9946b8938bdeaa).

**Comment by Darkspirit** [comment]
Could [bug 1505508 - Intermittently missing glyphs on Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1505508) (GeckoView) be related?

**Comment by LifeIsStrange** [comment]
I can reproduce on my galaxy tab s2

**Comment by Manishearth** [comment]
I can verify that the breaking commit is 76195e0

**Comment by Manishearth** [comment]
I don't think this is a glutin issue, android doesn't use glutin

**Comment by jdm** [comment]
Pretty sure it's the webrender upgrade: https://github.com/servo/servo/commit/76195e0779469f29a5e27cd882e2bbe8b2c9d6dd#diff-d2ede298d9a75c849170d6ef285eda1eR4527

**Comment by Manishearth** [comment]
Yeah, I'm looking into that now. Definitely looks like a broken atlas

**Comment by Manishearth** [comment]
That patch doesn't fix it

**Comment by Manishearth** [comment]
Working on it, I've got a smaller regression range between https://github.com/servo/webrender/compare/46ee0ffd...b44b5711

**Comment by Darkspirit** [comment]
servo/webrender#3282 caused [bug 1505664](https://bugzilla.mozilla.org/show_bug.cgi?id=1505664).

**Comment by Manishearth** [comment]
Yeah, my bisection is pointing fingers at servo/webrender@ab887f2e too

**Comment by Manishearth** [comment]
I guess a WR update will fix everything?

**Comment by Manishearth** [comment]
Nope. I did the WR update, still broken.

**Comment by Manishearth** [comment]
I realized there was a problem with the way I was patching webrender -- so it's possible that servo/webrender#3327 will help after all

**Comment by Manishearth** [comment]
https://github.com/servo/webrender/pull/3327 does indeed fix this

**Comment by Manishearth** [comment]
(i was able to verify that this works, btw)

**Comment by Darkspirit** [comment]
Fixed for me too. Thank you!
