### ISSUE TITLE
Change Response's statusText default value

### ISSUE THREAD

**Issue by jdm** [servo/servo#22238]
https://github.com/whatwg/fetch/pull/836

Instead of an `OK` default, it should be the empty string instead.

Code: https://github.com/servo/servo/blob/07e334ae55623518516ddae6d758cf7650142398/components/script/dom/webidls/Response.webidl#L30
Tests: `./mach test-wpt tests/wpt/web-platform-tests/fetch/api/response/response-init-001.html`

**Comment by georgeroman** [comment]
@highfive assign me
