### ISSUE TITLE
Download button hover doesn't activate on mozilla.com/firefox

### ISSUE THREAD

**Issue by jdm** [servo/servo#22284]
https://mozilla.com/firefox

**Comment by nicoabie** [comment]
![Screen Shot 2020-07-25 at 17 45 28](https://user-images.githubusercontent.com/2797992/88466033-afee3500-ce9e-11ea-9e55-79917e76951d.png)

Seems to be fixed now, building from master commit b83433fb142a54c4987d330acae3fbd8cbd7044e
