### ISSUE TITLE
Implement HTMLMediaElement.preload attribute logic

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22289]
Spec: https://html.spec.whatwg.org/multipage/media.html#attr-media-preload

**Comment by ferjm** [comment]
Depends on #22055

**Comment by oneturkmen** [comment]
hey @ferjm, I want to try this one! Does this only concern `components/script/dom/HTMLMediaElement.rs` file?

**Comment by ferjm** [comment]
@oneturkmen sorry, I just checked that the preloading logic is already there and after #22055 everything is working as expected. So this issue is no longer valid.
