### ISSUE TITLE
Implement HTMLMediaElement.crossorigin attribute logic

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22287]
Spec: https://html.spec.whatwg.org/multipage/media.html#attr-media-crossorigin

**Comment by andrealexandre** [comment]
@highfive: assign me

**Comment by ferjm** [comment]
Thanks for your interest on this @andrealexandre. Some tips on what we can do here:

- Add the `crossOrigin` attribute to the [HTMLMediaElement](https://github.com/servo/servo/blob/a2c4eba72014d143b2b1a442441bbce0f0b2200e/components/script/dom/webidls/HTMLMediaElement.webidl#L19) webidl. It's there, but commented out.
- Add the corresponding getter and setter to the [HTMLMediaElementMethods trait implement](https://github.com/servo/servo/blob/a2c4eba72014d143b2b1a442441bbce0f0b2200e/components/script/dom/htmlmediaelement.rs#L1250).
- Based on the attribute value, modify this [RequestInit](https://github.com/servo/servo/blob/a2c4eba72014d143b2b1a442441bbce0f0b2200e/components/script/dom/htmlmediaelement.rs#L708) values to add the ones related to CORS like in [here](https://dxr.mozilla.org/servo/source/components/script/dom/htmlscriptelement.rs#293)

**Comment by andrealexandre** [comment]
Thank you @ferjm, started taking a stab at Rust for improving my skills. Decide would taking an easy issue in this project would be a nice way for me to learn and help this community.

**Comment by ferjm** [comment]
@andrealexandre how are things going with this issue? Do not hesitate to ask if you need any further help.

**Comment by andrealexandre** [comment]
@ferjm, I think I'm done with my changes, I was wondering where do I unit test my changes.

**Comment by ferjm** [comment]
Great!

I think the only affected WPTs are the ones related to the interface:
- `tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLMediaElement/crossOrigin.html`
- `tests/wpt/web-platform-tests/html/dom/interfaces.https.html`

You'll likely need to [update the test expectations](https://github.com/servo/servo/tree/master/tests/wpt#updating-test-expectations) for them.

**Comment by jackxbritton** [comment]
@highfive: assign me

**Comment by jackxbritton** [comment]
Very cool. There's plenty of discussion for me to catch up on, hoping to get an MR submitted in the next couple days.
