### ISSUE TITLE
Implement HTMLMediaElement canPlayType()

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22299]
Spec: https://html.spec.whatwg.org/multipage/media.html#dom-navigator-canplaytype

**Comment by SiddharthaMishra** [comment]
Hey, I'd like to work on this.

**Comment by ferjm** [comment]
@SiddharthaMishra great!

I haven't put too much thought on it, but it seems that we should do something very similar to what WebKit does [here](https://github.com/WebKit/webkit/blob/ae5a8bdded113530fe844e01ad9c0e72ce85dbe2/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L2364).

In a nutshell, we need to lazily check with the GStreamer registry to see if there are elements to handle the corresponding media type (and cache that response, as it cannot change at runtime). To do that you will need to expose a method in [ServoMedia](https://github.com/servo/media/blob/0c8f2d6668947ddbd67f0c0bbe137fc25ce0e355/servo-media/src/lib.rs#L57) (i.e. can_play_type) which should call a [Backend](https://github.com/servo/media/blob/0c8f2d6668947ddbd67f0c0bbe137fc25ce0e355/servo-media/src/lib.rs#L50) method that should do something like [WebKit's gstRegistryHasElementForMediaType](https://github.com/WebKit/webkit/blob/ae5a8bdded113530fe844e01ad9c0e72ce85dbe2/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp#L304). You can use [Caps::from_str](https://slomo.pages.freedesktop.org/rustdocs/gstreamer/gstreamer/caps/type.Caps.html#method.from_str) and [ ElementFactory::list_filter](https://slomo.pages.freedesktop.org/rustdocs/gstreamer/gstreamer/struct.ElementFactory.html#method.list_filter) for the implementation of that method.

Once you have that method in servo-media, you'll need to use it from [HTMLMediaElement](https://github.com/servo/servo/blob/0b5ca81f4105fcce7ebbe6a825893faadb304a9b/components/script/dom/htmlmediaelement.rs#L1385) to implement the behavior that the spec defines.

Let me know if you need any further help with the implementation.

**Comment by SiddharthaMishra** [comment]
Hey, is there a list of types that are and aren't supported so I can test it out?

**Comment by ferjm** [comment]
There is no such list, but in any case that really depends on your gstreamer installation, so you can check if you have the required elements for a specific type with `gst-inspect-1.0` (i.e. `gst-inspect-1.0 | grep mp4`. Or you can directly try playing it with `gst-play-1.0` if you have access to an example stream.

**Comment by georgeroman** [comment]
@highfive assign me
