### ISSUE TITLE
Implement HTMLMediaElement.volume attribute

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22292]
Spec: https://html.spec.whatwg.org/multipage/media.html#dom-media-volume

**Comment by lucasfantacuci** [comment]
Hi, I'm very new to the open source world.
Though I'm pretty sure that I'll need some mentoring, I'd like to help on this issue.

**Comment by lucasfantacuci** [comment]
As I could see, I have to change the HTMLMediaElement struct (in file : servo/components/script/dom/htmlmediaelement.rs)  by adding this new volume field.

Probably, I'll have to change either the HTMLMediaElement::new_inherited() function that build this object.

Will I have to handle how to retrieve this value?
Or will I have to make a check in this function?

'Cause in the specification says that : "If the new value is outside the range 0.0 to 1.0 inclusive, then, on setting, an "IndexSizeError" DOMException must be thrown instead."

**Comment by lucasfantacuci** [comment]
@highfive: assign me

**Comment by jdm** [comment]
There will be six parts to this:
* updating the HTMLMediaElement.webidl file (https://html.spec.whatwg.org/multipage/media.html#media-elements:dom-media-volume)
* add a volume member field to the HTMLMediaElement structure which represents [the playback volume](https://html.spec.whatwg.org/multipage/media.html#concept-media-volume)
* implement the new getter method on HTMLMediaElement that returns this new field
* implement the new setter method on HTMLMediaElement, checking the provided value per [the spec](https://html.spec.whatwg.org/multipage/media.html#dom-media-volume)
* signal the media player (via [this interface](https://github.com/servo/media/blob/master/player/src/lib.rs#L46)) to change the volume
* add support for the new signal in the [gstreamer backend](https://github.com/servo/media/blob/master/backends/gstreamer/src/player.rs)

@ferjm will likely need to provide a bit more guidance on the final two steps.

**Comment by lucasfantacuci** [comment]
Oh, thx Sir. I'm following the guides, and as soon as possible, I gonna create a PR.

**Comment by ferjm** [comment]
> signal the media player (via this interface) to change the volume

You'll need to add a new `set_volume` function to the [Player](https://github.com/servo/media/blob/master/player/src/lib.rs#L46) trait. There are two implementations of this trait: a [dummy one](https://github.com/servo/media/blob/master/player/src/lib.rs#L67), for the platforms where we don't have gstreamer support yet, and [the gstreamer one](https://github.com/servo/media/blob/master/backends/gstreamer/src/player.rs#L532).

For the gstreamer implementation, we have the `inner_player_proxy!` macro. You can take [set_input_size](https://github.com/servo/media/blob/master/backends/gstreamer/src/player.rs#L541) as an example of how to add the new `set_volume` to the trait implementation and to the [PlayerInner](https://github.com/servo/media/blob/master/backends/gstreamer/src/player.rs#L84) struct.

> add support for the new signal in the gstreamer backend

The `gst-player` function that changes the volume is [set_volume](https://slomo.pages.freedesktop.org/rustdocs/gstreamer/gstreamer_player/struct.Player.html#method.set_volume)

**Comment by lucasfantacuci** [comment]
Sirs, should I create any kind of test for it?

**Comment by ferjm** [comment]
There are already some [Web Platform Tests](https://github.com/servo/servo/tree/master/tests/wpt#running-the-tests) for this:

- ./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/audio_volume_check.html
- ./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/video_volume_check.html
- ./mach tests-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/event_volumechange.html

You will likely need to [update the tests expectations](https://github.com/servo/servo/tree/master/tests/wpt#updating-test-expectations) since hopefuly all or at least some of these tests will start passing.
