### ISSUE TITLE
Implement HTMLMediaElement.ended attribute

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22294]
Spec: https://html.spec.whatwg.org/multipage/media.html#dom-media-ended

This one should probably be done after #22293

**Comment by germangb** [comment]
Hi, I'd like to take a stab at this issue if you don't mind :grinning:

**Comment by germangb** [comment]
@highfive: assign me

**Comment by ferjm** [comment]
Thanks fo working on this @germangb. Here are some pointers of what I think we can do to implement this:

- Update the [HTMLMediaElement.webidl](https://github.com/servo/servo/blob/master/components/script/dom/webidls/HTMLMediaElement.webidl#L49) with the `ended` attribute.
- Implement the `HTMLMediaElementMethods.Ended` getter according to [this part of the spec](https://html.spec.whatwg.org/multipage/media.html#ended-playback). Note that we can't properly tell if the direction of playback is forwards until we fix #22293, but we can have a placeholder for that. I suggest that you add a `PlaybackDirection` enum and a `fn direction_of_playback(&self) -> PlaybackDirection` function that always returns `PlaybackDirection::Forwards` for now. Add a XXX comment referencing #22293 there, please.
- Bonus points if you can implement the "_When the current playback position reaches the end..._" part of the [spec](https://html.spec.whatwg.org/multipage/media.html#playing-the-media-resource):
    - This should happen when we receive the [EOS event](https://github.com/servo/servo/blob/5413328be2838b725cc7fe82754e75f2c289f272/components/script/dom/htmlmediaelement.rs#L1214) from the player.
    - Ignore step 1 as that's part of #22290.
