### ISSUE TITLE
Implement HTMLMediaElement.loop attribute

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22290]
Spec: https://html.spec.whatwg.org/multipage/media.html#attr-media-loop
Code: `components/script/dom/htmlmediaelement.rs`, `components/script/dom/webidls/HTMLMediaElement.webidl`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/audio_loop_base.html`

**Comment by kkpoon** [comment]
@highfive: assign me

May I try on this?

**Comment by ferjm** [comment]
This was done in #22321

**Comment by ferjm** [comment]
Ugh, I was wrong! #22321 was never merged, it is still a WIP. Sorry for the confusion!

**Comment by swarnimarun** [comment]
@highfive: assign me

Gonna give this one a shot.
