### ISSUE TITLE
Implement performance interface extension for PerformanceResourceTiming

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#22307]
[Specification](https://w3c.github.io/resource-timing/#sec-extensions-performance-interface)

Implement
- [clearResourceTimings](https://w3c.github.io/resource-timing/#dom-performance-clearresourcetimings)
- [setResourceTimingBufferSize](https://w3c.github.io/resource-timing/#dom-performance-setresourcetimingbuffersize)
- [onresourcetimingbufferfull](https://w3c.github.io/resource-timing/#dom-performance-onresourcetimingbufferfull)

**Comment by aditj** [comment]
@highfive: assign me

**Comment by aditj** [comment]
@avadacatavra little help please, where do I implement the functions exactly ? Inside /servo/components/script/dom/performanceresourcetiming.rs ?

**Comment by ferjm** [comment]
According to the [spec](https://w3c.github.io/resource-timing/#sec-extensions-performance-interface), these methods are an extension of the [Performance](https://github.com/servo/servo/blob/master/components/script/dom/webidls/Performance.webidl) interface. You will need to modify that file to add the new methods and the new event.

The implementation for this interface lives in [components/script/dom/performance.rs](https://github.com/servo/servo/blob/a04200ae795d6f177ed77e9f826a8151f48d78ec/components/script/dom/performance.rs).

The two methods and the event modify, depend or check the list of stored `PerformanceResourceTiming` entries, which IIUC are stored [here](https://github.com/servo/servo/blob/a04200ae795d6f177ed77e9f826a8151f48d78ec/components/script/dom/performance.rs#L136).

**Comment by aditj** [comment]
@ferjm Thanks for the help ! Btw will my adding a Field to the Performance structure be a problem elsewhere?

**Comment by ferjm** [comment]
That I can't tell for sure. It will likely have some side effects (hopefully good ones :)). For example, it may cause new [Web Platform Tests](https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests#the-web-platform-tests-project-) to pass or fail.

**Comment by aditj** [comment]
@ferjm Where is the crate for PerformanceBinding written at?

**Comment by ferjm** [comment]
@aditj  https://github.com/servo/servo/pull/22431#pullrequestreview-184072634

**Comment by Hyperion101010** [comment]
Please add a tick here , if it is complete https://github.com/servo/servo/issues/21253 
I am working on one of 19 issues , and came to know that there are lot of changes coming by this one 
So , it'll help everyone in understanding what tasks are complete will now.
