### ISSUE TITLE
Support media resources with multiple media tracks

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22301]
Spec: https://html.spec.whatwg.org/multipage/media.html#media-resources-with-multiple-media-tracks

This involves implementing the [AudioTrackList and VideoTrackList](https://html.spec.whatwg.org/multipage/media.html#audiotracklist-and-videotracklist-objects) interfaces and the logic of the [audioTracks](https://html.spec.whatwg.org/multipage/media.html#dom-media-audiotracks) and [videoTracks](https://html.spec.whatwg.org/multipage/media.html#dom-media-videotracks) attributes.

**Comment by sreeise** [comment]
@ferjm Hello, if you don't mind, I would like to take this on.

**Comment by jdm** [comment]
You will want to follow the steps from https://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface when adding the new interfaces.

**Comment by sreeise** [comment]
> You will want to follow the steps from https://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface when adding the new interfaces.

Gotcha, thanks for the heads up.
