### ISSUE TITLE
Thread-safe (hash)map for layout ECS

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#22334]
@pcwalton, you mentioned this would be needed for https://github.com/servo/servo/wiki/Layout-revamp-ideas.

Would `Mutex<HashMap<..>>` or `RwLock<HashMap<..>>` have a lot of contention for this use case?

https://github.com/jonhoo/rust-evmap splits up the reading and writing APIs into separate objects. Writing is not thread-safe unless you bring your own `Mutex`. This is an improvement over the standard library for use cases that have lots of reads and few writes, which might be layout.

https://crates.io/crates/chashmap internally keep its whole table in a single `RwLock`, so I don’t know how it improves over `RwLock<HashMap<..>>`. It is also unmaintained. (The author has a “Why I'm leaving Open Source” blog post.)

https://github.com/redox-os/tfs/tree/master/atomic-hashmap is documented as lock-free, but by the same author so also likely unmaintained. (And not on crates.io)

https://crates.io/crates/crossbeam documents that its “ultimate goal” is to include maps (and other things). It seems the future is not here yet :)

https://crates.io/crates/lockfree looks promising

**Comment by stjepang** [comment]
There's [`crossbeam-skiplist`](https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-skiplist), which is essentially complete and we just need to publish the initial version. However, it's an ordered map (akin to `BTreeMap`) and performance is not that great compared to hash maps.

Could you say a little bit more about your use case?

* What is the type of keys and values?
* Do keys and values implement `Copy`?
* Are keys perhaps just integers?

**Comment by SimonSapin** [comment]
So I’m not super familiar with ECS (I don’t really have practical experience using it yet) but let’s try this:

In an entity-component-system pattern, each "object" or "thing" is called entity and given a unique identifier. Components carry all the data, addressed by identifier. A component for a given entity can refer to other entities by storing their identifiers. When storage is based on flat `Vec`s, the identifier can be `(index, generation number)`, with generations allowing reuse of slots/indices after an entity is removed. If instead we have maps of some sort, IDs can be arbitrary integers. We have a number of components that describe various aspects of entities. Each entity may or may not "have" a given component. Systems are where most of the logic/code are. A given system operates on entities that have a given set of components, regardless of what other components they have or not.

This pattern is very popular in games and solves many of the issues with complex object-oriented class hierarchies. In no-GC languages, it also makes ownership semantics and memory safety very simple. A downside is that we lose a lot of type-safety: there is no help from the compiler to ensure that there are no dangling references (stored entity identifiers) when we remove an entity, or to ensure that any entity has the expected components. (But since everything is checked this causes panics at worst, not unsoundness.)

On a single thread we could pass `&mut World` around (with the world containing all the data). With multiple threads of course we need `World: Sync` and the ability to do mutation through `&World`, so this is where a thread-safe map comes in.

Keys can be arbitrary integers, or at least they’re small and `Copy`. Values are not necessarily small. For CSS layout I don’t know if we can manage to keep all values `Copy`, but for now let’s say we can’t.

It looks like `SkipMap` would be relevant, but I didn’t find high-level docs. Could you say more about its characteristics?

**Comment by gterzian** [comment]
https://github.com/slide-rs/specs is an implementation of an ECS in Rust, used in https://github.com/amethyst/amethyst

I have no experience with it, but when I read "ECS" above, I remembered having seen it being mentioned [elsewhere](https://github.com/amethyst/amethyst#extreme-multithreading)...

**Comment by stjepang** [comment]
@SimonSapin 

> It looks like `SkipMap` would be relevant, but I didn’t find high-level docs. Could you say more about its characteristics?

You can think of `SkipMap<K, V>` as equivalent to `BTreeMap<K, V>` except it's also concurrent.

Iterators to elements of the map are called `Entry<K, V>` and they increment the internal refcount of elements so that they don't get destroyed while you're reading them. Dropping an entry decrements the refcount for its element.

Operations like `insert` and `remove` internally don't touch refcounts while traversing the skip list. Instead they use `crossbeam_epoch::pin()` to prevent elements (nodes) from being destroyed while we're reading them.

This way we prevent locking and all operations on `SkipMap` are 100% lock-free. Of course, refcounting by iterators has some performance cost but it isn't *too* bad.

Let me know if I can answer any follow-up questions. :)

**Comment by SimonSapin** [comment]
One thing that I notice while looking through the code is the space overhead. Each key/value pair is in its own heap allocation, and has variable-size metadata that has at least 2 and (if I understand correctly) on average 3 pointer-sized fields.

That said it’s quite possible that getting a sound, concurrent, lock-free map out of it is worth this trade-off. But it’s something to keep in mind.

**Comment by stjepang** [comment]
> Each key/value pair is in its own heap allocation, and has variable-size metadata that has at least 2 and (if I understand correctly) on average 3 pointer-sized fields.

Yes, this is correct.

> That said it’s quite possible that getting a sound, concurrent, lock-free map out of it is worth this trade-off.

Well, if you want an ordered map that is fully generic (doesn't rely on bounds like `K: Copy, V: Copy` that would allow certain kinds of optimizations) and fully lock-free, this is pretty much the state of the art. It's as good as it gets. *shrug*

If we bend the rules, there's a lot of space for optimization:

* If `K: Copy` and `V: Copy`, then we could implement a Bw-Tree ([discussion](https://github.com/spacejam/sled/issues/62)) for a ~3.5x speedup. However, that is a monumental work requiring many months to complete.

* If `K: AsRef<[u8]>` (true for primitive types and strings), then we could implement a ~5x faster ordered map based on adaptive radix tree (not fully lock-free, but almost). It's actually quite a bit simpler data structure than a lock-free skip list. Could be great for string interning.

* If `K: Hash` and we don't need an ordered map, then a hash table with per-bucket locking could get us very far. Think performance on the order of adaptive radix tree with occasional hiccups when resizing.

* If `K: Hash + Copy` and `V: Copy`, then we can have a hash table with locks, but also do optimistic reads on lookup for more speedups.

There are surely plenty of other options I can't think of at the moment.

At this point, I think we should just take `hashbrown` and add per-bucket locking to make it concurrent. That would be a good bang-for-buck solution.

cc @Amanieu

**Comment by SimonSapin** [comment]
> Well, if you want an ordered map that is fully generic (doesn't rely on bounds like K: Copy, V: Copy that would allow certain kinds of optimizations) and fully lock-free, this is pretty much the state of the art. It's as good as it gets.

Yes, that was sort of my point :) Thanks for looking into all this.

**Comment by SimonSapin** [comment]
For what it’s worth, for the multi-threaded ECS use case we don’t need the map to be ordered and keys are something like `struct Id(NonZeroUsize);`. So we can have `K: Copy + Hash + AsRef<[u8]>`. (But `V: Copy` would be limiting.)

**Comment by SimonSapin** [comment]
We ended up not using ECS for Servo layout (in order to avoid the need for fast mutable concurrent access to a centralized shared resource).
