### ISSUE TITLE
You can't open links that redirect to pages you have visited before

### ISSUE THREAD

**Issue by Darkspirit** [servo/servo#22330]
I am not creative enough for a good title, please correct.

1. Run Servo `$ ./servo`. We are on `https://servo.org/`.
2. Ctrl+L, open `https://mozilla.org/`. A page is loaded.
3. Ctrl+L, open `http://mozilla.org/`. White page, nothing loaded. (We should have been redirected to https://mozilla.org/.)

Also happens the other way around:
1. Run Servo `$ ./servo`. We are on `https://servo.org/`.
2. Ctrl+L, open `http://mozilla.org/`. A page is loaded (after being redirected to https://mozilla.org/).
3. Ctrl+L, open `https://mozilla.org/`. White page, nothing loaded.

**Comment by Darkspirit** [comment]
1. Run Servo: `$ ./servo`. We are on `https://servo.org/`.
2. Open https://bit.ly/2Sl4GzU. It should redirect to https://servo.org/. White page, nothing is loaded.
3. Open https://mozilla.org/
4. Open http://mozilla.org/. White page, nothing loaded.
5. Open http://www.mozilla.org/en-US/privacy/firefox/, it works.

**Comment by Darkspirit** [comment]
(I've seen some css-less HTML pages before. Looks like an intermittent / different problem.)

**Comment by jdm** [comment]
This turned out to be a really subtle and interesting issue, so thanks for noticing it!

**Comment by paulrouget** [comment]
Related to #22331?

**Comment by jdm** [comment]
Not according to my solution in #22340.
