### ISSUE TITLE
Fontconfig running out of memory, Servo only renders background color of page

### ISSUE THREAD

**Issue by campadrenalin** [servo/servo#2234]
When running Servo, the following errors appear in the terminal output:

```
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf" line 14: out of memory
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf" line 23: out of memory
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf" line 32: out of memory
```

The Servo window appears, but only seems to render the background color of the page. It's not clear if text is the only missing component. Layout seems to work, based on cursor behavior.

I'm on Ubuntu 13.10 Saucy Salamander, and if it would help, I can provide a copy of the seemingly offensive 65-khmer.conf.

**Comment by dralley** [comment]
After 7 years, should this be closed?  I don't think it's still an issue.

**Comment by jdm** [comment]
Haven't seen reports of this in many years.
