### ISSUE TITLE
Support cancellation on AudioParams

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22367]
According to #21632 this is a commonly used feature.

The DOM and servo-media glue code is there, but the actual cancellation is not implemented yet.

Code: https://github.com/servo/media/blob/master/audio/src/param.rs#L410
Specs:

- https://webaudio.github.io/web-audio-api/#dom-audioparam-cancelscheduledvalues
- https://webaudio.github.io/web-audio-api/#dom-audioparam-cancelandholdattime

**Comment by GPHemsley** [comment]
There don't appear to be any self-contained tests for these two methods. The closest I could find is in [audioparam-method-chaining](https://github.com/web-platform-tests/wpt/blob/7c50c216081d6ea3c9afe553ee7b64534020a1b2/webaudio/the-audio-api/the-audioparam-interface/audioparam-method-chaining.html).

**Comment by zimio** [comment]
Hello, I would like to pick this one up. I think I should start by making a test for these two methods, no?

**Comment by zimio** [comment]
@highfive: assign me

**Comment by zimio** [comment]
@ferjm I am having problems compiling the media repo. What is the preferred method of communication where I can ask questions regarding how to solve this issue? I can't connect to IRC during regular business hours most of the time. I only have time during the evenings and weekends to work on this.

**Comment by jdm** [comment]
Want to file an issue in the media repo?

**Comment by ferjm** [comment]
@zimio make sure that you use the same [Rust toolchain required for Servo](https://github.com/servo/servo/blob/master/rust-toolchain) to build the media repo. And, as @jdm said, file an issue in that repo if you still encounter any build issue. IRC is also a good channel to get a quick answer.

**Comment by zimio** [comment]
Now I can build the latest of media, but it now gives me this error:

> (base) ➜  servo git:(master) ✗ ./mach build --dev                                                                                                         
>     Updating crates.io index
> error: failed to select a version for `lazy_static`.
>     ... required by package `servo-media-gstreamer v0.1.0 (/home/zimio/workspace/mozilla/media/backends/gstreamer)`
>     ... which is depended on by `servo-media v0.1.0 (/home/zimio/workspace/mozilla/media/servo-media)`
>     ... which is depended on by `script v0.0.1 (/home/zimio/workspace/mozilla/servo/components/script)`
>     ... which is depended on by `script_tests v0.0.1 (/home/zimio/workspace/mozilla/servo/tests/unit/script)`
> versions that meet the requirements `^1.2.0` are: 1.2.0
> 
> all possible versions conflict with previously selected packages.
> 
>   previously selected package `lazy_static v1.0.0`
>     ... which is depended on by `glutin v0.19.0`
>     ... which is depended on by `servo-skia v0.30000020.1`
>     ... which is depended on by `azure v0.35.0 (https://github.com/servo/rust-azure#5c648f2b)`
>     ... which is depended on by `canvas v0.0.1 (/home/zimio/workspace/mozilla/servo/components/canvas)`
>     ... which is depended on by `constellation v0.0.1 (/home/zimio/workspace/mozilla/servo/components/constellation)`
>     ... which is depended on by `libservo v0.0.1 (/home/zimio/workspace/mozilla/servo/components/servo)`
>     ... which is depended on by `simpleservo v0.0.1 (/home/zimio/workspace/mozilla/servo/ports/libsimpleservo/api)`
>     ... which is depended on by `simpleservo_capi v0.0.1 (/home/zimio/workspace/mozilla/servo/ports/libsimpleservo/capi)`
> 
> failed to select a version for `lazy_static` which could resolve this conflict
> Build FAILED in 0:00:05
> 

I suppose to work on this issue, I will have to update all of the things that depend of lazy_static and make them use version 1.2.0^. Am I understanding correctly?

**Comment by jdm** [comment]
Try `cargo update -p lazy_static`? It's a minor version update.

**Comment by zimio** [comment]
Thanks! that solved it.

**Comment by zimio** [comment]
I'm trying to do the wpt test but the their current documentation for doing audioparam tests is not complete I think. I can't find much information about audit. I don't know how I would make wpt for cancelvalues.

So I decided to check what was done in firefox. I found this: https://hg.mozilla.org/mozilla-central/rev/5fc85295afde

I like it. He didn't create a wpt test, just a unit-test. I couldn't find any unit test in the servo-media repo. So I guess it is all based on the examples? So maybe I should make a new example?.

For the implementation I want to make sure I got it in the right place.

So I think it is in the run method of the AutomationEvent, so when we receive a new event and run that method, if the event matches  AutomationEvent::CancelScheduledValues(time) => then I should go through the events vector, check all of the events and delete those events whose time is equal or greater than the time passed to CancelScheduledValues return true if a deletion occurred, return false if events is unchanged. 

But then I had a look a this:

`pub(crate) fn insert_event(&mut self, event: AutomationEvent) {
          if let AutomationEvent::SetValue(val) = event {
              self.val = val;
              self.event_start_value = val;
              self.dirty = true;
              return;
          }
  
          let time = event.time();
  
          let result = self.events.binary_search_by(|e| e.time().cmp(&time));
          // XXXManishearth this should handle overlapping events
          let idx = match result {
              Ok(idx) => idx,
              Err(idx) => idx,
          };
  
          // XXXManishearth this isn't quite correct, this
          // doesn't handle cases for when this lands inside a running
          // event
          if let Some(is_hold) = event.cancel_event() {
              self.events.truncate(idx);
              if !is_hold {
                  // If we cancelled the current event, reset
                  // the value to what it was before
                  if self.current_event >= self.events.len() {
                      self.val = self.event_start_value;
                  }
                  // don't actually insert the event
                  return;
              }
          }
          self.events.insert(idx, event);
          // XXXManishearth handle inserting events with a time before that
          // of the current one
      }
`

So from what I'm seeing, it is being done there now? self.events.truncate(idx);

**Comment by Manishearth** [comment]
@zimio right, the backend code is already implemented, the servo side needs to be able to call it from audioparam.rs

**Comment by zimio** [comment]
@Manishearth  I had a look at the servo side to see if it is being called and I found that it was being called.

From the servo repo:

components/script/dom/audioparam.rs 

```

    // https://webaudio.github.io/web-audio-api/#dom-audioparam-cancelscheduledvalues
    fn CancelScheduledValues(&self, cancel_time: Finite<f64>) -> DomRoot<AudioParam> {
        self.message_node(AudioNodeMessage::SetParam(
            self.param,
            UserAutomationEvent::CancelScheduledValues(*cancel_time),
        ));
        DomRoot::from_ref(self)
    }

```

And then in the media repository is this:

audio/src/node.rs 

```

            AudioNodeMessage::SetParam(id, event) => {
                self.get_param(id).insert_event(event.to_event(sample_rate))
            }

```

However we can see from the insert code here:
```

    pub(crate) fn insert_event(&mut self, event: AutomationEvent) {
          if let AutomationEvent::SetValue(val) = event {
              self.val = val;
              self.event_start_value = val;
              self.dirty = true;
              return;
          }
  
          let time = event.time();
  
          let result = self.events.binary_search_by(|e| e.time().cmp(&time));
          // XXXManishearth this should handle overlapping events
          let idx = match result {
              Ok(idx) => idx,
              Err(idx) => idx,
          };
  
          // XXXManishearth this isn't quite correct, this
          // doesn't handle cases for when this lands inside a running
          // event
          if let Some(is_hold) = event.cancel_event() {
              self.events.truncate(idx);
              if !is_hold {
                  // If we cancelled the current event, reset
                  // the value to what it was before
                  if self.current_event >= self.events.len() {
                      self.val = self.event_start_value;
                  }
                  // don't actually insert the event
                  return;
              }
          }
          self.events.insert(idx, event);
          // XXXManishearth handle inserting events with a time before that
          // of the current one
      }
```

When a cancel event is inserted, it will use truncate to delete all the events after the time passed as parameter. So from what I can read, it should work as intended. What am I missing here?

**Comment by Manishearth** [comment]
Oh, hm, looks like this got implemented at some point. Sorry about that.
