### ISSUE TITLE
Implement WaveShaperNode

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22371]
Spec: https://webaudio.github.io/web-audio-api/#waveshapernode

**Comment by dralley** [comment]
Completed (at least mostly) with https://github.com/servo/media/issues/205

I think oversampling is still not implemented, according to the comments on the PR.

However, I think the bug to support that should be filed in servo/media?

**Comment by khodzha** [comment]
actually oversampling was merged in https://github.com/servo/media/pull/332
idk if this needs any work on servo side though

**Comment by jdm** [comment]
I think we can close this issue and file followups for anything we discover is still missing.
