### ISSUE TITLE
`NamedGetter` and `NamedSetter` codegen assumes parameter named `name`

### ISSUE THREAD

**Issue by jsanders** [servo/servo#2240]
I ran into this while looking into #2117. A few places dealing with `NamedGetter` and `NamedSetter` in `CodeGenRust.py` explicitly define a variable `name` ([example](https://github.com/mozilla/servo/blob/master/src/components/script/dom/bindings/codegen/CodegenRust.py#L3586)) while the name of the parameter that actually gets passed is defined in the webidl. It seems like currently only `HTMLCollection` is using this functionality, and things work because the [getter in its webidl](https://github.com/mozilla/servo/blob/master/src/components/script/dom/webidls/HTMLCollection.webidl#L13) has `name` as the parameter name. But the [Storage webidl](http://www.whatwg.org/specs/web-apps/current-work/multipage/webstorage.html#storage-0) uses `key` as the parameter name.

The quick fix is to just change the webidl to use `name`, but I thought I'd file an issue, because this is confusing.

**Comment by dhananjay92** [comment]
I'd like to work on this. Because there's Mozilla's code that I can use as reference, I think I can do it.
Just a quick question. How do I know if my changes are working as expected? Are there any tests to run?

**Comment by Ms2ger** [comment]
Running `./mach test-wpt webstorage` should have some new passing tests after the change, at least

**Comment by dhananjay92** [comment]
Okay, cool. I am on it.

**Comment by dhananjay92** [comment]
[Here](https://github.com/servo/servo/compare/master...dhananjay92:Issue%232240) is what I have done so far. No builds errors.

I re-built and ran the test using `./mach test-wpt webstorage` both on master and the branch with changes. It gives the same result. Below is the summary of test results. Please let me know if I missed anything.

```
Summary
=======

Ran 185 tests (27 parents, 158 subtests)
Expected results: 177
Unexpected results: 8 (FAIL: 8)

Unexpected Results
==================

/webstorage/setitem.html
------------------------
FAIL localStorage[]
FAIL localStorage[] update
FAIL localStorage[undefined]
FAIL localStorage[null]
FAIL sessionStorage[]
FAIL sessionStorage[] update
FAIL sessionStorage[undefined]
FAIL sessionStorage[null]
```

**Comment by dhananjay92** [comment]
@Ms2ger Should I go ahead and do pull?!

**Comment by jdm** [comment]
@dhananjay92 Those changes aren't quite right; you want to modify dom/webidls/TestCodeGen.webidl instead of the one you did, and there's no point in modifying the C++ header - it's just left over from when I imported the code generation implementation from Firefox.

**Comment by klusark** [comment]
@dhananjay92, are you still working on this?

**Comment by dhananjay92** [comment]
@klusark Nope, not any more. Would love to, but I have very less time. You can take it. :smiley: 
BTW you've got some code already done for you. :wink:

**Comment by Yoric** [comment]
I'll try and work on this.

**Comment by Yoric** [comment]
I'll need some handholding, though, as I'm not familiar with Servo yet.

Do I understand correctly that the changes done by @dhananjay92 on the Python file are correct and that I need to implement his interface `TestIndexedGetterAndSetterAndNamedGetterInterface`?

**Comment by jdm** [comment]
I believe the python changes are correct, but the test-related changes are incorrect. Servo doesn't use any of those files.
