### ISSUE TITLE
Only send one SetDocumentState message, not an infinite number

### ISSUE THREAD

**Issue by jdm** [servo/servo#22410]
When the document is finished loading and there are no pending images to load, the script thread continues to send a SetDocumentState message every time a reflow is complete. This is unnecessary; we should not need to send more than one. We should add a boolean to Window to avoid this.

Code: https://github.com/servo/servo/blob/160f1137fb66408f98e952df8b6b93df16fd7ee1/components/script/dom/window.rs#L1549

**Comment by kingdido999** [comment]
@highfive assign me

**Comment by kingdido999** [comment]
Does the variable name `is_reflow_completed` sound good here? Or something more specific like `is_reflow_complete_message_sent`?
