### ISSUE TITLE
Use builder pattern with RequestInit

### ISSUE THREAD

**Issue by jdm** [servo/servo#22427]
If RequestInit::new accepts all of the mandatory arguments and then the builder pattern is used for customizable options, the resulting code might be easier to match against specification text like https://html.spec.whatwg.org/multipage/media.html#media-elements.

**Comment by lucasfantacuci** [comment]
It could be a great way to learn this pattern in Rust for me.

Can I work on it?

**Comment by jdm** [comment]
Sure! Look for uses of `RequestInit {` in components/ and those are the ones that we will want to replace with a constructor and builder methods.

**Comment by lucasfantacuci** [comment]
@highfive: assign me

**Comment by lucasfantacuci** [comment]
@jdm I was analyzing the code from components and I couldn't realize what are all the mandatory arguments. I can't be sure.

**Comment by jdm** [comment]
I recommend starting from the specification definition of a request (https://fetch.spec.whatwg.org/#concept-request) - anything that says "unless otherwise set" or "unless stated otherwise" is optional, so anything without that is mandatory. Then try to match the mandatory ones against the members of RequestInit.
