### ISSUE TITLE
USVString attributes incorrectly typed as DOMString

### ISSUE THREAD

**Issue by dlrobertson** [servo/servo#22454]
The following WebIDLs contain attributes with the `CEReactions` attribute that should be a `USVString`, but are implemented as a `DOMString`:

 - [HTMLIFrameElement]
 - [HTMLImageElement]
 - [HTMLInputElement]
 - [HTMLLinkElement]
 - [HTMLMediaElement]
 - [HTMLScriptElement]

The corresponding macro helpers [make_url_getter] and [make_url_setter] will also need to be updated. The update to [make_url_getter] and [Element::get_url_attribute] should be fairly straightforward. [make_url_setter] macro does not seem to be used currently and `Element::set_url_attribute` seems to not be implemented, so that will need to be implemented too.

[HTMLIFrameElement]: https://html.spec.whatwg.org/multipage/#htmliframeelement
[HTMLImageElement]: https://html.spec.whatwg.org/multipage/#htmlimageelement
[HTMLInputElement]: https://html.spec.whatwg.org/multipage/#htmlinputelement
[HTMLLinkElement]: https://html.spec.whatwg.org/multipage/#htmllinkelement
[HTMLMediaElement]: https://html.spec.whatwg.org/multipage/#htmlmediaelement
[HTMLScriptElement]: https://html.spec.whatwg.org/multipage/#htmlscriptelement
[Element::get_url_attribute]: https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L1487-L1501
[make_url_getter]: https://github.com/servo/servo/blob/master/components/script/dom/macros.rs#L96-L106
[make_url_setter]: https://github.com/servo/servo/blob/master/components/script/dom/macros.rs#L174-L184

**Comment by dlrobertson** [comment]
CC #22313

**Comment by jdm** [comment]
This probably was a spec update in https://github.com/whatwg/html/pull/1282 that we missed.
