### ISSUE TITLE
Perf script broken by change in userscripts option

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#22462]
The userscripts option is now `--userscripts=DIR` rather than `--userscripts DIR` and there are a couple of places in CI where we used it to capture perf data:
```
$ grep -r userscripts etc
etc/ci/performance/servo-warc-tests/run-warc-tests.sh:  --userscripts ${ARCHIVE_DIR}/user-agent-js \
etc/ci/performance/runner.py:        "--userscripts", ua_script_path,
```
As a result, we've not been capturing perf data for about six months.

**Comment by Coder206** [comment]
@highfive: assign me

**Comment by Coder206** [comment]
Should `"--userscripts", ua_script_path,`  be replaced by `"--userscripts=", ua_script_path,` for `etc/ci/performance/runner.py`? (just add the equal sign)

**Comment by Coder206** [comment]
Also, the `etc/ci/performance/servo-warc-tests/run-warc-tests.sh` does not exist in the `master` checkout. Is there another branch I should work on as well?

**Comment by jdm** [comment]
servo-warc-tests gets cloned from https://github.com/servo/servo-warc-tests/

**Comment by asajeffrey** [comment]
I'd go for `"--userscripts=" + ua_script_path` to avoid a space creeping into the argument list.

Good point re. run-warc-tests.sh, that'll need a PR in servo-warc-tests.
