### ISSUE TITLE
When exiting, monitored component should unregister itself

### ISSUE THREAD

**Issue by gterzian** [servo/servo#22468]
A component currently registered with the [background-hang-monitor](https://github.com/servo/servo/tree/c9229f3f99936627229edf7a616b2af915ce2416/components/background_hang_monitor) will start "hanging" after exiting, because it doesn't unregister itself, nor does it go into "waiting" mode, instead, it handles the last "exit" task, and quits. From the monitor's perspective, the component will later start hanging on that last "exit" task. 

This will require:
1. Adding a `Unregister` message https://github.com/servo/servo/blob/c9229f3f99936627229edf7a616b2af915ce2416/components/background_hang_monitor/background_hang_monitor.rs#L72
2. Adding a `unregister` method, either for [this](https://github.com/servo/servo/blob/c9229f3f99936627229edf7a616b2af915ce2416/components/msg/constellation_msg.rs#L467) or [that](https://github.com/servo/servo/blob/c9229f3f99936627229edf7a616b2af915ce2416/components/msg/constellation_msg.rs#L445) trait(I would say rather `BackgroundHangMonitor`), as well as corresponding implementations.
3. When Layout [exits](https://github.com/servo/servo/blob/c9229f3f99936627229edf7a616b2af915ce2416/components/layout_thread/lib.rs#L891), unregister it with the monitor.
4. When Script [exits](https://github.com/servo/servo/blob/c9229f3f99936627229edf7a616b2af915ce2416/components/script/script_thread.rs#L2359), do the same thing.
5. Add a [test](https://github.com/servo/servo/blob/c9229f3f99936627229edf7a616b2af915ce2416/components/background_hang_monitor/tests/hang_monitor_tests.rs) case, for example by asserting that no "hang alerts" are received from an unregistered component, which has just done a `notify_activity`, followed by unregistering itself, followed by either sleeping until the timeout is reached, or quitting.

**Comment by CYBAI** [comment]
@csmoe is working on it at #22474 so labeled as `C-assigned`.
