### ISSUE TITLE
Clarify Layout-thread exit workflow

### ISSUE THREAD

**Issue by gterzian** [servo/servo#22475]
It appears to me that the `ExitNow` message, handled [here](https://github.com/servo/servo/blob/6731ddd29f40f05ebb65fef0b1164c8632a7872a/components/layout_thread/lib.rs#L814), is in fact never received at that stage. Rather, it seems that it is only received and handled inside `prepare_to_exit`. 

If that is indeed the case, we should probably add an expectation that it is never received at the initial stage(where only a `PrepareToExit` message should be received). This could make the workflow more explicit. 

The actionable item here would be doing some investigation by adding a `panic`, running the test suite(on the server from a PR), and seeing if the message is received at all. If it is not, we can leave the panic(or maybe turn it into a `warn`) as a form of documentation and to ensure the message is not sent due to a code change later, unless the workflow is meant to be changed.

**Comment by gterzian** [comment]
Nevermind, it is actually sent at https://github.com/servo/servo/blob/6731ddd29f40f05ebb65fef0b1164c8632a7872a/components/constellation/pipeline.rs#L395

**Comment by gterzian** [comment]
It might still be useful to add a comment at https://github.com/servo/servo/blob/6731ddd29f40f05ebb65fef0b1164c8632a7872a/components/layout_thread/lib.rs#L814
 to make clear that receiving the `Exit` message at this stage only happens when layout is undergoing a "force exit".

**Comment by aditj** [comment]
@highfive: assign me
