### ISSUE TITLE
Truncate debug output for long data URLs

### ISSUE THREAD

**Issue by jdm** [servo/servo#22485]
When using RUST_LOG=net on tests like /_webgl/conformance/ogles/GL/fract/fract_001_to_006.html, the resulting logs contain many instances of gigantic data URLs. We should truncate these automatically so the logs are easier to read.

Code: https://github.com/servo/servo/blob/9ca6768a56cf29ce6563af932b9e8a9150963d39/components/url/lib.rs#L170-L174

**Comment by jdm** [comment]
To observe the difference in behaviour, run `RUST_LOG=net ./mach test-wpt /_webgl/conformance/ogles/GL/fract/fract_001_to_006.html`.

**Comment by Hyperion101010** [comment]
@highfive :assign me
Feeling excited to work on this part of firefox!

**Comment by jdm** [comment]
As a first try, why don't we limit the length of any URL debug representation to 40 characters, then append `... ([hash])` where `[hash]` is the string representation of the hash of the string (https://doc.servo.org/std/hash/trait.Hash.html#tymethod.hash).

**Comment by jdm** [comment]
This will give us URLs that look something like this: `http://google.com/foobar?whatever=5&another=120914... (126baf38a208901ab3)`.

**Comment by jdm** [comment]
@Hyperion101010 To test the changes, run the command I suggested in https://github.com/servo/servo/issues/22485#issuecomment-450660337 and see if the output looks reasonable.

**Comment by Hyperion101010** [comment]
https://github.com/servo/servo/pull/22740
i have started working, i submitted the patch kindly check
