### ISSUE TITLE
servo-tidy should allow URLs longer than 80 chars in bash scripts

### ISSUE THREAD

**Issue by staktrace** [servo/servo#22498]
servo-tidy is quite strict with its enforcement of the 80-char rule. This causes headaches if you have a URL in a bash script, for example, that's longer than 80 chars. It's hard to break that across lines and there should be a way to tell servo-tidy not to complain about that.

**Comment by Darkspirit** [comment]
Example: https://github.com/servo/servo/blob/f3ca48206e02d48fc8e9f7d340d25e2210d00723/etc/cert_generator.sh#L21-L22
