### ISSUE TITLE
Iframe's contentDocument is incorrect before load event is fired

### ISSUE THREAD

**Issue by jdm** [servo/servo#22503]
frame.html
```html
<body>
<script>
var i = document.createElement('iframe');
document.body.appendChild(i);
i.contentWindow.goodbye = function() { console.log("failure!") };
window.hello = function(parent) { console.log("got callback"); parent.i.contentWindow.goodbye() };
i.src = "page.html";
</script>
```
page.html
```html
<script>
window.goodbye = function() { console.log("success!") }
window.parent.hello(window.parent);
</script>
```
This prints `failure!` instead of `success!` when I load frame.html in Servo (a real HTTP server is required for same-origin access between the page and the iframe).

The stored pipeline id for HTMLIFrameElement isn't updated to the new pipeline until the UpdatePipelineId message is received from the constellation, so we're missing out on the expected synchronous behaviour. This is visible in tests like bailout-exception-vs-return-xml.window.js as well, which end up testing about:blank instead of the expected page.

**Comment by cbrewster** [comment]
Since frame.html and page.html are same-origin, we should be able to take a shortcut in the script thread to update the iframe's active `PipelineId`. When we create the local window proxy we check if it is inside an iframe, we could update the pipeline id then.

**Comment by jdm** [comment]
This also affects various referrer-policy tests that use iframes, preventing the checks for Message.source from succeeding (even when #22499 is implemented).

**Comment by jdm** [comment]
I'm fixing this as part of #22514.

**Comment by atouchet** [comment]
@jdm is this fixed now?

**Comment by jdm** [comment]
Yes, but I'm going to leave this open to write an automated test that verifies this.
