### ISSUE TITLE
Investigate document activity and layout thread exit issues

### ISSUE THREAD

**Issue by gterzian** [servo/servo#22507]
The spec has [a nice example](https://html.spec.whatwg.org/multipage/#fully-active) of how a document of a subframe belonging to an iframe can go from `fully-active` to just `active`, while a script could still keep a reference to the iframe. 

This is what is done in this test: https://github.com/servo/servo/blob/f3ca48206e02d48fc8e9f7d340d25e2210d00723/tests/wpt/web-platform-tests/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/active.window.js#L34

The test then calls `close` on the window of this "active" document:
https://github.com/servo/servo/blob/f3ca48206e02d48fc8e9f7d340d25e2210d00723/tests/wpt/web-platform-tests/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/active.window.js#L9

This currently results in [finish_load](https://github.com/servo/servo/blob/f3ca48206e02d48fc8e9f7d340d25e2210d00723/components/script/dom/document.rs#L1723) being called on that document, which sends a reflow message to layout. 

This then panics, because the layout thread will have already been closed, as part of the [`handle_exit_pipeline`](https://github.com/servo/servo/blob/f3ca48206e02d48fc8e9f7d340d25e2210d00723/components/script/script_thread.rs#L2326) workflow, which is triggered when the iframe is navigated here https://github.com/servo/servo/blob/f3ca48206e02d48fc8e9f7d340d25e2210d00723/tests/wpt/web-platform-tests/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/active.window.js#L43

Basically, the iframe is navigated, and it's initial pipeline closed. The subframe inside this closed pipeline is then marked as "active", but it's associated layout-thread has already been shutdown. Any subsequent reflows will trigger a panic. 

I guess there are various ways to solve this, among which:

1. Not closing the layout thread of a pipeline if it still contains children marked as "active". 
2. Not running any tasks for documents that arent't fully active, like the spec actually says to. https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model:fully-active. We could instead use something like [`Document.delayed_tasks`](https://github.com/servo/servo/blob/f3ca48206e02d48fc8e9f7d340d25e2210d00723/components/script/dom/document.rs#L418)
3. Maybe both. It appears that tasks of an active document should be kept in the queue and executed when the document becomes "fully-active" again(see https://github.com/whatwg/html/issues/4242). In that case it will need a layout thread to go with it...

**Comment by gterzian** [comment]
I think this issue could be closely related to other issues when communicating with layout fails, although I can't imagine they all hit this "there an active but not fully-active iframe" path, so I think there mush be other ways for a "dangling" pipeline with not layout thread to become possible. 

This issue proposed some band-aid for the problem: https://github.com/servo/servo/issues/23053

Related issues:
https://github.com/servo/servo/issues/26969
https://github.com/servo/servo/issues/26429


Some noted crashed while browsing:

https://github.com/servo/servo/issues/21208
https://github.com/servo/servo/issues/19092

Some intermittents:

https://github.com/servo/servo/issues/22559
https://github.com/servo/servo/issues/22584
https://github.com/servo/servo/issues/22652

Some previously fixed issues(that may have addressed the problem partly and could point to a larger solution):
https://github.com/servo/servo/issues/22955

Some previous PR that are somewhat related:
https://github.com/servo/servo/pull/24143
https://github.com/servo/servo/pull/24789

cc @jdm

**Comment by gterzian** [comment]
One thing I find notable is when this happens via the script-thread handling a message, such as `ScriptThread::handle_tick_all_animations`. 

In these situations, the script-thread actually checks for the presence of the document in `Documents`, and if the layout-thread is shut-down(via `exit_pipeline`), then the document should be removed as well. 

So maybe in such a case, the document still has a layout thread, however it's holding on to a not fully active iframe that doesn't, and then the actual call to `Window::force_reflow`(or some other API requiring communication with layout) is to the window of that frame, not that of the document which is used in the initial message-handling by the script-thread. 

The other thing is when the crash happens via a task being run, and then it could be about still running tasks for a pipeline that has already exited, but I think this was previously addressed(see linked to PRs), although there might still be a some of the left somehow.

**Comment by gterzian** [comment]
Note this can also happen when an iframe is navigated across origin: https://github.com/servo/servo/issues/27010

**Comment by mrobinson** [comment]
I wonder if this is still an issue now that layout lives just as long as the `Window`.

**Comment by gterzian** [comment]
`html/webappapis/dynamic-markup-insertion/opening-the-input-stream/active.window.js` doesn't seem to crash anymore, so we can presume the answer is "no".
