### ISSUE TITLE
Implement browsing context targetting for HTMLAreaElement

### ISSUE THREAD

**Issue by jdm** [servo/servo#22515]
We support targeting browsing contexts since #20678 (see the code in htmlanchorelement.rs that deals with the target attribute), so we should implement this missing feature. It's used in the referrer-policy/generic/subresource-test/area-navigate.html test.

**Comment by georgeroman** [comment]
@highfive assign me

**Comment by georgeroman** [comment]
I managed to make the `area-navigate` test to result in `FAIL` instead of `TIMEOUT` by simply implementing the methods in `HTMLHyperlinkElementUtils`. Is this the desired result, or I should only add support for the `target` attribute for now?

**Comment by jdm** [comment]
Oh, good catch! Please add the support for the target attribute on top of that work!

**Comment by georgeroman** [comment]
In the end I didn't manage to make the test go from `TIMEOUT` to `FAIL`, so I made a PR just with the implementation of the `target` attribute: #22850. However, I'll keep trying.
