### ISSUE TITLE
Remove 'on' prefix from event handler macros

### ISSUE THREAD

**Issue by jdm** [servo/servo#22516]
Event handlers defined in the specification have names like "onchange", but they should be declared in Servo's code with `event_handler!(change, GetOnchange, SetOnchange)`. Several instances of incorrect usage (`event_handler!(onchange, GetOnChange, SetOnchange)`) have snuck in; we should fix that.

Code: `grep 'event_handler!(on' components/script/dom/*.rs` (fix all uses outside of dom/macros.rs)
Tests: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/track` ([update](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) the expected test results)

**Comment by jkurian** [comment]
@highfive assign me

**Comment by jdm** [comment]
If you are having trouble running the tests, remove [this file](https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/semantics/embedded-content/media-elements/track/track-element/__dir__.ini) to make sure the tests are not skipped.

**Comment by VishalCR7** [comment]
@jkurian : Hi! Do you still plan to work on this bug? Should I go ahead and assign myself?

**Comment by jkurian** [comment]
Hi @VishalCR7 , you can go ahead and take this from me. I haven't had and likely wont have time to look into this for a while. Thanks for asking!

**Comment by maxheyer** [comment]
@highfive assign me

**Comment by jdm** [comment]
@maxheyer Are you still working on this? Have you made any progress?

**Comment by maxheyer** [comment]
@jdm It's not possible to compile servo on my 16GB strong Macbook. You should take this issue from me. Thanks for asking!

**Comment by pngai** [comment]
@highfive assign me
