### ISSUE TITLE
Add DOM wrappers for dealing with typed arrays

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#22526]
Currently the way to work with typed arrays is to use `Heap<*mut JSObject>` and filling them in with `Float32Array::create` (etc)

It would be nice if we had a type that encapsulated all this so we don't need to mess with JS contexts.

See also: 

https://github.com/servo/servo/blob/f3ca48206e02d48fc8e9f7d340d25e2210d00723/components/script/dom/vrframedata.rs#L74-L81

**Comment by pshaughn** [comment]
This might have enough in common with the needs of #10072 to be worth cross-referencing, since Javascript containers-of-stuff in general currently share a need to go out to unsafe code.

**Comment by Manishearth** [comment]
Good point, yeah.

**Comment by Manishearth** [comment]
There is `to_frozen_array` (recently created) already for that, fwiw.

**Comment by sagudev** [comment]
I think this was done as part of https://github.com/servo/servo/issues/31064.
