### ISSUE TITLE
Implement Element::set_url_attribute

### ISSUE THREAD

**Issue by dlrobertson** [servo/servo#22568]
`Element::set_url_attribute` the counterpart to [Element::get_url_attribute] is not implemented yet. Once implemented the macro [make_url_setter] should use the new method instead of `Element::set_string_attribute`.

Related to: https://github.com/servo/servo/pull/22563#discussion_r244288739 and https://github.com/servo/servo/issues/22454

[Element::get_url_attribute]: https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L1487-L1500
[make_url_setter]: https://github.com/servo/servo/blob/master/components/script/dom/macros.rs#L108-L119

**Comment by nox** [comment]
https://html.spec.whatwg.org/#reflecting-content-attributes-in-idl-attributes

> If a reflecting IDL attribute is a USVString attribute whose content attribute is defined to contain a URL, then on getting, if the content attribute is absent, the IDL attribute must return the empty string. Otherwise, the IDL attribute must parse the value of the content attribute relative to the element's node document and if that is successful, return the resulting URL string. If parsing fails, then the value of the content attribute must be returned instead, converted to a USVString. On setting, the content attribute must be set to the specified new value.

I don't see why we should have a `make_url_setter`, given the setter is specified to have no URL-specific behaviour.

**Comment by dlrobertson** [comment]
@nox good catch

The `make_url_setter` is needed because the given structure has a `USVString` element and the setter is `DOMString`, so we need `USVString -> DOMString`, but I guess we don't necessarily need `Element::set_url_attribute`. We could just keep the `USVString -> DOMString` evaluation in the macro `make_url_setter`.

CC @ferjm
