### ISSUE TITLE
Mac OS X: Build "mishap" on 10.14

### ISSUE THREAD

**Issue by IngwiePhoenix** [servo/servo#22565]
Hello! I was experiencing a missing-header error during my first, initial build. Appearently, some headers are only available, when you use the Mac OS X SDK. I am not too surprised, but this came out of nowhere. I managed to fix this by running this: ` CC="xcrun -sdk macosx10.14 gcc" CXX="xcrun -sdk macosx10.14 g++" ./mach build -r`.

Notice the `-sdk` flag? This one allowed me to use the SDK's `g++` (-> `clang++` -> `clang`). Maybe this can be helpful :)

Also, the initial error I got was:
```
/Users/Ingwie/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-skia-0.30000020.1/src/core/SkAdvancedTypefaceMetrics.cpp:24:9: fatal error: 'ApplicationServices/ApplicationServices.h' file not found
#import <ApplicationServices/ApplicationServices.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/skia.dir/src/core/SkAdvancedTypefaceMetrics.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/skia.dir/all] Error 2
make: *** [all] Error 2
```

Kind regards,
Ingwie.

**Comment by dralley** [comment]
Since skia has been removed, this can be closed - definitely won't occur again.

**Comment by dralley** [comment]
@jdm
