### ISSUE TITLE
Delete virtualenv when executing mach clean

### ISSUE THREAD

**Issue by zimio** [servo/servo#22588]
If you run "./mach clean" the directory "servo/python/_virtualenv" won't be deleted, which could cause an issue if your virtualenv is corrupt/broken.

**Comment by shanavas786** [comment]
I would like to give it a try.

**Comment by jdm** [comment]
@shanavas786 Great! The command implementation is at https://github.com/servo/servo/blob/721d2a8abdcc78971001928347cd1f7b96571fbb/python/servo/build_commands.py#L611-L632.
