### ISSUE TITLE
Use 'line-height' and 'vertical-align' when setting linebox element positions

### ISSUE THREAD

**Issue by burg** [servo/servo#226]
I believe that we don't parse 'vertical-align' yet.
## CSS2 Specs
- 'text-align': http://www.w3.org/TR/CSS2/text.html#propdef-text-align
- 'vertical-align': http://www.w3.org/TR/CSS2/visudet.html#propdef-vertical-align
- lineboxes: http://www.w3.org/TR/CSS2/visuren.html#line-box
## Test cases
- baseline placement: http://www.brunildo.org/test/va_lineheight.html
- inline hell: http://meyerweb.com/eric/css/inline-hades.html

**Comment by mrobinson** [comment]
Servo has support for `vertical-align`. This is working better in modern layout than legacy layout.
