### ISSUE TITLE
Ignore children of void elements when serializing

### ISSUE THREAD

**Issue by jdm** [servo/servo#22607]
#22542 fixed one instance of the serialization behaviour for void elements, but that check needs to happen in SerializationIterator::next as well. Right now it unconditionally appends all child nodes to the stack of nodes that need to be serialized; we can avoid this problem by moving the check from the `serialize` function to `rev_children_iter` instead - this will return an empty iterator for any void element.

**Comment by jdm** [comment]
@georgeroman Would you like to work on this? I would expect a bunch of additional tests to pass as a result.

**Comment by georgeroman** [comment]
Yeah, sure!
@highfive assign me
