### ISSUE TITLE
Make create_typed_array an unsafe function

### ISSUE THREAD

**Issue by jdm** [servo/servo#22600]
The function `create_typed_array` takes an unsafe pointer as an argument; that means that it's possible to pass an invalid pointer and produce a segfault outside of an `unsafe` block. The function should be marked unsafe to make this clear.

code: `components/script/dom/vrframedata.rs`

No need for automated tests; if the changes compile without any warnings, it's good enough for a PR.

**Comment by heh9** [comment]
@highfive: assign me
