### ISSUE TITLE
./mach bootstrap fails if python is not installed

### ISSUE THREAD

**Issue by ydogus** [servo/servo#22635]
Hello,
I've tried to run `./mach bootstrap` on Fedora 29 which was a minimal installation. All I get is:

> ./mach: line 9: exec: python: cannot execute: Is a directory

After installing Python manually, `./mach bootstrap` works! Maybe this is expected behavior but I thought `./mach bootstrap` would also install required Python.

**Comment by tigercosmos** [comment]
According to readme you could run the following, and there is python.
But yep, the order might be misleading. It is better to mention Python is required just like the block of macOS does.

```
sudo dnf install curl libtool gcc-c++ libXi-devel \
    freetype-devel mesa-libGL-devel mesa-libEGL-devel glib2-devel libX11-devel libXrandr-devel gperf \
    fontconfig-devel cabextract ttmkfdir python2 python2-virtualenv python2-pip expat-devel \
    rpm-build openssl-devel cmake bzip2-devel libXcursor-devel libXmu-devel mesa-libOSMesa-devel \
    dbus-devel ncurses-devel harfbuzz-devel ccache mesa-libGLU-devel clang clang-libs gstreamer1-devel \
    gstreamer1-plugins-base-devel gstreamer1-plugins-bad-free-devel autoconf213
```

**Comment by Hyperion101010** [comment]
Python is becoming a basic dependency nowadays for an OS
I guess a small patch will work for bootstrap in MacOS, but given you should always have python installed

**Comment by ShalokShalom** [comment]
It is python virtualenv and that one is not always preinstalled.

**Comment by mrobinson** [comment]
I think the README is clearer now that python and virtualenv need to be installed before running bootstrap.
