### ISSUE TITLE
Port referrer-policy test structure changes to forked tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#22663]
tests/wpt/mozilla/tests/mozilla/referrer-policy/ is an old fork of tests/wpt/web-platform-tests/referrer-policy. Ideally we would unfork them, but for the short term it would be good to apply the changes from https://github.com/web-platform-tests/wpt/pull/14634 to them to reduce the intermittent timeouts that occur.

**Comment by georgeroman** [comment]
@highfive assign me

**Comment by georgeroman** [comment]
So all the tests should be replaced by their new version? I noticed that some of the modified files are missing and the files that exist have a different structure than the old files in https://github.com/web-platform-tests/wpt/pull/14634.

**Comment by jdm** [comment]
All of the tests are generated by [this python script](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/tools/generate.py) based on [this JSON configuration](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/referrer-policy/spec.src.json). The goal of this work would be to port the changes to the various python scripts and configuration files, then regenerate the tests.

**Comment by jdm** [comment]
[This](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/tools/regenerate) is a script that should automate the regeneration.

**Comment by georgeroman** [comment]
I implemented the changes from the `js` files and regenerated the tests but it seems that no tests were modified, so I'm not sure if I did it properly.
