### ISSUE TITLE
Retrying a PR caused a taskcluster error

### ISSUE THREAD

**Issue by jdm** [servo/servo#22671]
https://github.com/servo/servo/commit/160842b8c15ef328ec380f9f69403d88372bafde
The retried PR does not appear in https://treeherder.allizom.org/#/jobs?repo=servo-auto as a result.

`InterpreterError at template.tasks[0]: object keys must be strings`

**Comment by SimonSapin** [comment]
This error message is from the taskcluster-github integration service: https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1

This service reacts to each GitHub push event, fetches `.taskcluster.yml` at the repo root in the corresponding branch, parses it, and processes the resulting object with JSON-e: https://taskcluster.github.io/json-e/#Language

The "context" (input variables) used for that processing is documented in https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1#json-e-rendering

I recently added a script to run this JSON-e processing locally for debugging, but the script contains a hard-coded list of contexts. You can run it with:

```sh
$ python/_virtualenv/bin/pip install git+https://github.com/taskcluster/json-e  # Once
$ etc/taskcluster/simulate_github_events.py
```

`template.tasks[0]` refers to part of the object obtained after JSON-e processing. Unfortunately the error message does not say more about the shape of that object or what exact input data was used to create it.

@owlishDeveloper, are there logs somewhere that would have more details about this error?

**Comment by mrobinson** [comment]
Closing this since taskcluster is no more.
