### ISSUE TITLE
[Question] Embedding into C/C++

### ISSUE THREAD

**Issue by IngwiePhoenix** [servo/servo#22681]
Hello!

I'd like to try and build something like Electron, but based on Servo. So I'd like to interface with it from C or C++. What are good ways to do this? I saw `bindgen` and `cbindgen` on the Crates registry and wondered if I could use either to ease embedding? It'd be very nice to interface with these:

- JavaScript engine
- WebView

Mainly, I enjoy working with FLTK, as it is cross-platform and, as pointed out in a previous issue ticket, also has a GL rendering method (`FL_Gl_Window`). I'd also like to know if I can extend Servo when embedding to allow it to utilize `libsass` from within HTML to allow something like `<link type="text/scss" rel="..."/>` or to extend it's JavaScript API?

Thank you :)

Kind regards,
Ingwie

**Comment by paulrouget** [comment]
To embed Servo from C, you can build libsimpleservo (`./mach build --libsimpleservo`) and dynamically load the library in C (no need to use bindgen).

This Rust code: https://github.com/servo/servo/blob/master/ports/libsimpleservo/capi/src/lib.rs exports symbols that can be used from C code.

You will need to provide a gl surface (see the `init` method) and build a loop yourself (where you call `perform_updates`).

>  I'd also like to know if I can extend Servo when embedding to allow it to utilize libsass from within HTML to allow something like <link type="text/scss" rel="..."/> or to extend it's JavaScript API?

I don't believe there's a trivial way to do that. You can inject user scripts though, but that's 100% JS.

**Comment by IngwiePhoenix** [comment]
Very cool!

Luckily, FLTK provides a loop as well as allowing one to periodically call functions during the loop.

Are there plans to make more of Servo available to C?

**Comment by paulrouget** [comment]
> Are there plans to make more of Servo available to C?

Servo internals are very extensible for now. At least dynamically. But Servo is very well compartmented. It would not be too hard to add your own component to support scss I think.

**Comment by IngwiePhoenix** [comment]
I just noticed that mozjs (SpiderMonkey) is being used inside. Now, SpiderMonkey offers a C API. Is there some kind of example on how I can interact with that very SpiderMonkey instance correctly so that I could extend the default objects within a window?

To be fair, I am new to Rust. So reading through the source and the Cargo files takes me a while. But from what I can see, I really like how it is laid out into various components which eats have their individual modules. I like this approach a lot :)

**Comment by paulrouget** [comment]
>  so that I could extend the default objects within a window?

The window JS objects (all DOM) are all implemented in Servo. SpiderMonkey is "just" the JS engine. If you want to add anything inside the DOM, this needs to be done in a Servo component.

Maybe look at the bluetooth code in components/script/dom/navigator.rs

**Comment by IngwiePhoenix** [comment]
So basically you abstract away the C API once, and sort of forget about it and write everything else in Rust?

I am reading over the suggested file, and, indeed, I can not seem to find any reference to SpiderMonkey or anything related close to it at all. It just looks like a lot of Rust structs and implementations.

But at some point, all those structs have to be given to the engine so it knows which objects to prsent to subsequently loaded scripts. Where does that happen though?

**Comment by paulrouget** [comment]
> But at some point, all those structs have to be given to the engine so it knows which objects to prsent to subsequently loaded scripts. Where does that happen though?

Maybe this is what you're looking for: https://github.com/servo/rust-mozjs

But if you want to extend the DOM, you will have to do it with a user script or a rust component.

Another option is to inject a JS script into the web page with a userscript, and that userscript would communicate with your C/C++ code with websockets.
