### ISSUE TITLE
SmallVecN where N > 0 can cause memory corruption on the stack

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#2269]
Not good.

**Comment by kmcallister** [comment]
Can you elaborate?

**Comment by SimonSapin** [comment]
@pcwalton Is this the same as https://github.com/servo/rust-smallvec/issues/4 ?

**Comment by sviter** [comment]
Is it still valid?

**Comment by jdm** [comment]
This can be dealt with separately in the smallvec repository if it's still a real issue (which sounds implausible after this much time).
