### ISSUE TITLE
Switch to taskcluster checks API

### ISSUE THREAD

**Issue by jdm** [servo/servo#22691]
https://github.com/web-platform-tests/wpt/pull/14859
https://github.com/web-platform-tests/wpt/issues/14846

**Comment by SimonSapin** [comment]
Do we need to update our version of Homu for this? Change its config?

**Comment by jdm** [comment]
https://github.com/web-platform-tests/wpt/pull/15946 merged, so this should be something that is possible now.

**Comment by SimonSapin** [comment]
Apparently this could also help with https://bugzilla.mozilla.org/show_bug.cgi?id=1548781

**Comment by SimonSapin** [comment]
I tried it, this is blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1252144.

**Comment by SimonSapin** [comment]
A work around exists: https://github.com/servo/servo/pull/24804

Landing the change would need to be coordinated with a change in Homu’s configuration.
