### ISSUE TITLE
Investigate UWP support

### ISSUE THREAD

**Issue by jdm** [servo/servo#22729]
I'll collect any resources that might be helpful here.

**Comment by jdm** [comment]
https://github.com/contextfree/winrt-rust#winrt-and-uwp

**Comment by jdm** [comment]
https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT
https://mailman.videolan.org/pipermail/x264-devel/2016-April/011628.html

**Comment by jdm** [comment]
The WACK complains about failing the AppContainer and DBCheck checks:
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-app-certification-kit-tests#appcontainercheck
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-app-certification-kit-tests#address-space-layout-randomization

**Comment by jdm** [comment]
Running the vcvars batch scripts with a `uwp` argument apparently does something different. We should figure out what that entails and make sure that anything useful is added to the native cc-rs and cmake builds.

**Comment by jdm** [comment]
https://stackoverflow.com/questions/40803170/cmake-uwp-using-cmake-to-build-universal-windows-app

**Comment by jdm** [comment]
We will need to provide the Code Generation capability to support the spidermonkey JIT: https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

**Comment by jdm** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/zw-windows-runtime-compilation?view=vs-2019

**Comment by jdm** [comment]
The `dirs` crate used by font-config and servo_config calls SHGetKnownFolderPath which is forbidden.

**Comment by jdm** [comment]
A bunch of c++ istream/ostream code is present in mozangle and shows up in the WACK forbidden symbols. We might need to make a separate ANGLE crate that wraps https://github.com/Microsoft/angle/ instead for the UWP build.

**Comment by jdm** [comment]
One of the gstreamer dependencies in [this list](https://github.com/servo/servo/blob/8e783577d24cac2983fbea1b46d5452ffa5fb44f/python/servo/build_commands.py#L737-L759) is libwinpthreads-1.dll, which the WACK complains about. According to our gstreamer friends:
```
The gstreamer binaries built with MSVC do not need libwinpthread-1.dll. 
For instance, the gst test app does not use it. The only way it can get
pulled in is if you're using a plugin that has dependencies built with
Autotools/MinGW. Which plugins are those? It should be possible to port
and build those dependencies with Meson/MSVC instead.
```

**Comment by jdm** [comment]
Latest WACK report using the UWP compiler target: https://www.joshmatthews.net/wack.html

**Comment by jdm** [comment]
backtrace-rs relies on dbghelp.dll which appears to be largely forbidden:
```
API EnumerateLoadedModules64 in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymFromAddr in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymFromAddrW in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymGetLineFromAddr64 in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymGetLineFromAddrW64 in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymGetModuleInfo64 in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymInitialize in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymInitializeW in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymLoadModule64 in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
API SymSetOptions in dbghelp.dll is not supported for this application type. simpleservo.dll calls this API.
```

**Comment by jdm** [comment]
Old versions of rand (0.4, 0.5) look like they are the cause of:
```
API SystemFunction036 in cryptbase.dll is not supported for this application type. simpleservo.dll calls this API.
```
0.4 affects hashglobe, servo_rand, tempfile, and ws. 0.5 affects phf_generator, tokio-threadpool, and uuid.

**Comment by jdm** [comment]
mozjs has a static link directive with Dbghelp and uses it in mozjs/mozglue/build/cygprofile.cpp. mozjs/mozglue/misc/StackWalk.cpp also uses imagehelp.dll methods like StackWalk64, which weren't supported in 2016 (https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/703260).

**Comment by jdm** [comment]
nspr calls a bunch of unsupported methods. Luckily, we can remove it entirely from the spidermonkey build on all platforms: https://github.com/servo/mozjs/pull/185

**Comment by jdm** [comment]
All references to linking opengl32.lib need to be removed: https://github.com/paulrouget/winapi-rs/commit/e3aaa6cade3a8c946c4dcf7e128b36fcf89b1350

**Comment by jdm** [comment]
The OpenSSL DLLs are responsible for a bunch of forbidden API usage. I'm keeping an eye on https://github.com/microsoft/vcpkg/issues/4267 which should bring up a version that supports UWP (https://github.com/openssl/openssl/pull/8917).

**Comment by jdm** [comment]
The forbidden clipboard functions will disappear from the WACK report once #23440 is fixed.

**Comment by jdm** [comment]
```
API _Query_perf_counter in msvcp140.dll is not supported for this application type. simpleservo.dll calls this API.
API _Query_perf_frequency in msvcp140.dll is not supported for this application type. simpleservo.dll calls this API.
API _Thrd_sleep in msvcp140.dll is not supported for this application type. simpleservo.dll calls this API.
API _Xtime_get_ticks in msvcp140.dll is not supported for this application type. simpleservo.dll calls this API.
```
These may come from std::chrono ([reference](https://stackoverflow.com/questions/41347313/stdchrono-calls-queryperformancefrequency-repeatedly))? There is usage of that in mozjs in the WASM code.

**Comment by MouriNaruto** [comment]
I wonder to provide you some interesting infomaton. (The talk between the maintainer from Microsoft/OpenSSL and me.)

> Also I think we should keep the compatibility for earlier version of Windows, even compiled with the latest SDK. Because some developers like me need to support several versions of Windows 10.

> Building with a new SDK still allows the binary to run on previous versions of Windows, so moving forward with the progress of the SDK doesn't prevent supporting older versions.

> But after reading the source code, I realized that some functions will be linked to the new version of dynamic libraries if I am using the new version of Windows SDK because you used the conditional compilation. (It will not overwrite functions not supported by older versions if the new version of Windows SDK is used.)

> Yes, while when using a new SDK we might be linking around newly exposed functions (specifically the ones that we override), they are already part of the previous versions of the OS. The apis weren't exposed in the Universal SDK and would fail the WACK certification, but as the SDK and WACK allow for more functions to be used they are also allowed on previous versions of the OS.

For more informaton, please read https://github.com/microsoft/openssl/issues/59

Kenji Mouri

**Comment by MouriNaruto** [comment]
Also, I wonder to provide a way to bypass the WACK check.

Here is an example. My friend use it in his UWP and publish to the Microsoft Store.
https://github.com/amamiya/SYEngine/blob/master/SYEngine/SYEngine.Shared/AutoLib.h

Also, I think maybe we can use some undocument way to get the kernel32.dll's HMOUDLE handle. (For example, the PEB stucture.)

Kenji Mouri

**Comment by jdm** [comment]
Yes, I have been following all of the openssl issues with great interest. Thank you for continuing to work on that :)

**Comment by MouriNaruto** [comment]
This is an new issue which opened by myself for the next step UWP support in OpenSSL.
Some arguments need to solve. (But there are no people reply for them in recent four days.)

https://github.com/openssl/openssl/issues/9125

Kenji Mouri

**Comment by jdm** [comment]
Need to see if we're using a version of mio that is uwp-compatible: https://github.com/tokio-rs/mio/issues/912

**Comment by jdm** [comment]
I think we can call these investigations resolved, since we're building UWP app nightlies on CI.
