### ISSUE TITLE
Implement ResizeObserver

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#22731]
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1272409
Spec: https://drafts.csswg.org/resize-observer-1/
Explainer: https://github.com/w3c/csswg-drafts/blob/master/resize-observer-1/explainer.md

**Comment by mrego** [comment]
Some related issues #31006 and #31182, maybe we should mark this as meta issue or something meanwhile.

**Comment by jdm** [comment]
I don't think it's worth leaving open.
