### ISSUE TITLE
`table-layout: fixed` works incorrectly

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#22733]
While reading [this blogpost](http://www.heydonworks.com/article/the-flexbox-holy-albatross), I found its navigation bar isn't shown correctly in Servo.

Following is the reduced test case:

<img width="1031" alt="default" src="https://user-images.githubusercontent.com/6782666/51421921-54742480-1be1-11e9-9e0f-2b78ce9b084a.png">

```html
<style>
  * {
    margin: 0;
    box-sizing: border-box;
  }

  nav ul {
    background: #802626;
    padding: 0.75em;
    display: table;
    table-layout: fixed;
    width: 100%;
    font-size: 1.125em;
  }

  nav li {
    display: table-cell;
    text-align: center;
  }

  a {
    color: #fff;
  }

  nav::after {
    content: '\0020';
    background: #fff url(http://www.heydonworks.com/wp-content/themes/heydonworks/images/spike.png) repeat-x center top;
    background-size: auto 100%;
    display: block;
    height: 0.5em;
  }
</style>

<nav>
  <div>
    <ul>
      <li><a>HeydonWorks</a></li>
      <li><a>About</a></li>
      <li><a>Tools &amp; Resources</a></li>
      <li><a>Feed</a></li>
    </ul>
  </div>
</nav>
```

Built with latest master (81ab255b70) on `macOS 10.13.6`

**Comment by CYBAI** [comment]
Tried to comment the `table-layout: fixed;` in `nav ul`; then I found it will work as same as Firefox so I think the root cause for this issue would be related to `table-layout`.

<img width="1116" alt="default" src="https://user-images.githubusercontent.com/6782666/51429009-1f99b900-1c45-11e9-8c42-c3f04d9e66c2.png">

**Comment by CYBAI** [comment]
Just tried to run [the example](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout#Example) of `table-layout` in MDN. It also worked incorrectly.

```html
<style>
table {
  table-layout: fixed;
  width: 120px;
  border: 1px solid red;
}

td {
  border: 1px solid blue;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
</style>

<table>
  <tr><td>Ed</td><td>Wood</td></tr>
  <tr><td>Albert</td><td>Schweitzer</td></tr>
  <tr><td>Jane</td><td>Fonda</td></tr>
  <tr><td>William</td><td>Shakespeare</td></tr>
</table>
```

<img width="1181" alt="default" src="https://user-images.githubusercontent.com/6782666/51429089-12c99500-1c46-11e9-89aa-f17dc5b200e1.png">

**Comment by dralley** [comment]
Can still reproduce

**Comment by mrobinson** [comment]
This seems to work fine in modern layout.
