### ISSUE TITLE
Transparent rects demo detroys magic leap responsiveness

### ISSUE THREAD

**Issue by jdm** [servo/servo#22747]
The perf is really bad in a release build, and it's quite janky when moving the laser pointer around, and almost impossible to position the 2d cursor correctly because it ends up leaping everywhere during the regular scheduled jankyness.

**Comment by asajeffrey** [comment]
I removed this demo from the ML home page, so it's not as obvious. The webrender issue is (I think) the same as https://github.com/servo/webrender/issues/2706.

**Comment by atouchet** [comment]
Magic Leap is no longer supported. Is this issue still relevant?
