### ISSUE TITLE
WebGL cloth demo does not display anything on magic leap debug build

### ISSUE THREAD

**Issue by jdm** [servo/servo#22748]

**Comment by jdm** [comment]
Same for the webgl decals demo.

**Comment by asajeffrey** [comment]
Hmm, that's new.

**Comment by jdm** [comment]
The demos work fine in release builds, but in debug builds they display nothing.

**Comment by jdm** [comment]
I'm going to try to see if this is a regression or if it's always been the case.

**Comment by jdm** [comment]
This also occurs in a build from Jan 4.

**Comment by jdm** [comment]
And in a build from Dec 3, so there's no regression, just a weird failure mode that might be related to #21841.

**Comment by asajeffrey** [comment]
Works now.
