### ISSUE TITLE
WebVR freezes the VRDisplay eye parameters when created

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#22758]
When a `VRDisplay` object is created, we get the eye parameters from the `WebVRDisplayData`, and store them in fields https://github.com/servo/servo/blob/efecb3e1a2ce2a075784b63ab247399db2dc6cf2/components/script/dom/vrdisplay.rs#L112-L119

The fields are never set after they are initialized, which means that if a device changes the eye parameters, script sees the old parameters.

For example, the render width and height are in the eye parameters, so on a device which supports resizing, script never sees the render size changing.

**Comment by asajeffrey** [comment]
Should be fixed by moving from `rust-webvr` to `webxr`.

**Comment by atouchet** [comment]
Is this fixed now?

**Comment by asajeffrey** [comment]
We don't support WebVR any more.
