### ISSUE TITLE
Add retry support for network operations in CI

### ISSUE THREAD

**Issue by jdm** [servo/servo#22754]
Intermittent network issues that prevent completing a git clone are a common enough source of failure that we should make it easy to automatically retry a failing command a certain number of times. This would be similar to the `appveyor-retry` command that Appveyor provides.

**Comment by SimonSapin** [comment]
`curl` has `--retry`, and I *think* Cargo retries a few times by default when fetching dependencies. I don’t find something similar for git, so yes a wrapper script is likely what we need.

One snag is that we can’t use a script in the repo for the purpose of cloning the repo. So if the script is not trivial enough to inline it in `.taskcluster.yml` we might need to add it to our Docker images, including [`decision-task`](https://github.com/servo/taskcluster-bootstrap-docker-images/) image.

**Comment by jdm** [comment]
https://github.com/web-platform-tests/wpt/pull/15073/files

**Comment by mrobinson** [comment]
We still see intermittent network issue on the GitHub runners, but that seems unrelated this one.
