### ISSUE TITLE
Refactor follow_hyperlink and callers to match specification algorithms

### ISSUE THREAD

**Issue by jdm** [servo/servo#22761]
The `follow_hyperlink` method in `htmlanochorelement.rs` implements [this algorithm](https://html.spec.whatwg.org/multipage/links.html#following-hyperlinks-2). Its callers are `HTMLAnchorElement::activation_behavior` and `HTMLAreaElement::activation_behavior`, which were written based on an older version of the specification and are now out of date. The goal of this work is to remove the older, duplicated steps from the activation_behavior methods and move their work into the appropriate steps of the `follow_hyperlink` function. The `TODO` for step 1 can now be implemented based on work from #22660 which added a `Element::cannot_navigate` method.

Code: `components/script/dom/htmlanchorelement.rs`, `components/script/dom/htmlareaelement.rs`
Tests: `./mach test-wpt tests/html/semantics/links/following-hyperlinks/` should continue to pass after this change.

**Comment by MaT1g3R** [comment]
Hello, I would like to work on this

**Comment by jdm** [comment]
If I emailed you about this today, go ahead! If not, I have reserved this for a student that I have been talking with and I am happy to help you find another issue to work on.

**Comment by MaT1g3R** [comment]
I tried running `./mach test-wpt tests/html/semantics/links/following-hyperlinks/` and it seems like that directory doesn't exist anymore, all I could find is `tests/wpt/web-platform-tests/html/semantics/links/following-hyperlinks/` and that test is failing with:

```shell
Running 2 tests in web-platform-tests
▶ Unexpected subtest result in /html/semantics/links/following-hyperlinks/activation-behavior.window.html:
│ FAIL [expected PASS] <a> that is not connected should be followed
│   → assert_unreached: Reached unreachable code
│
│ @http://web-platform.test:8000/html/semantics/links/following-hyperlinks/activation-behavior.window.js:26:9
│ Test.prototype.step_timeout/<@http://web-platform.test:8000/resources/testharness.js:1624:20
│ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1566:20
└ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1590:20
Ran 2 tests finished in 5.0 seconds.
• 1 ran as expected. 0 tests skipped.
• 1 tests had unexpected subtest results
```

I built servo with `./mach build --dev`, and I have not modified anything yet. Am I missing something in the build step or is this something that needs to be fixed?

As an aside, I'm using CLion with the Intellij Rust plugin, and `html5ever::LocalName` and `html5ever::Prefix` can't be resolved by the IDE in `components/script/dom/htmlanchorelement.rs`, and idea how I can fix that?

**Comment by jdm** [comment]
Yeah, my mistake providing the wrong path. You found the correct one. I didn't realize that #19234 is tracking the fact that this test currently yields intermittent failures in release builds, but in debug builds it seems to solidly fail. I am optimistic that using the `Element::cannot_navigate` API should make this test consistently start passing instead!

**Comment by jdm** [comment]
As for the question about CLion and the Intellij plugin, I can't help with that. All I can do is point you towards https://doc.servo.org/servo/index.html for non-IDE results.

**Comment by jdm** [comment]
That's certainly more complicated than any of the other refactoring that I'm asking for; you can leave that TODO alone.

**Comment by MaT1g3R** [comment]
I'm looking at https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element%3Aactivation-behaviour , does this apply to area elements as well?

**Comment by jdm** [comment]
That's https://html.spec.whatwg.org/multipage/#the-area-element:activation-behaviour instead.
