### ISSUE TITLE
Refactor bool pattern matching into if else to improve readability

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#22775]
As [suggested from clippy](https://rust-lang.github.io/rust-clippy/master/index.html#match_bool), when we have `bool patter matching`, we can use `if ... else` block instead. Using `if ... else` should have better readability.

I saw there're few bool pattern matching in Servo codebase.

```shell
→ rg "false =>" | wc -l
      12
```

For example,

https://github.com/servo/servo/blob/06c1209770855c0f4a676e5e6fb78ab39a10b6ae/components/script/dom/htmlanchorelement.rs#L581-L585

This can be

```rust
let referrer_policy = if self.RelList().Contains("noreferrer".into()) {
  Some(ReferrerPolicy::NoReferrer)
} else {
  None
};
```

**Comment by piotr-szpetkowski** [comment]
@highfive: assign me
