### ISSUE TITLE
Normalize behaviour of space vs. return for activating elements

### ISSUE THREAD

**Issue by jdm** [servo/servo#22782]
Right now, `Document::dispatch_key_event` triggers different behaviour for elements if you activate them with spacebar or return. Spacebar performs a [synthetic click activation](https://html.spec.whatwg.org/multipage/interaction.html#activation:fire-a-click-event), while Return triggers [implicit form submission](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission). This means that pressing Return with an anchor element active does not navigate to the link, and special cases the behaviour for text input elements and buttons. I propose the following:
* remove the `implicit_submission` method from the `Activatable` trait
* remove the `implicit_submission` implementation for `HTMLButtonElement` entirely
* make the `implicit_submission` implementation for `HTMLInputElement` a regular method
* treat the Space and Return cases the same in `dispatch_key_event`; remove any reference to implicit submission

This should allow implicit submissions of forms from text inputs to continue working, since there is code in HTMLInputElement::handle_event to recognize the Return key already. Activating buttons with the Return key should also work as expected, since they will receive a synthetic click event.

Code: `components/script/dom/activation.rs`, `components/script/dom/document.rs`, `components/script/dom/htmlinputelement.rs`, `components/script/htmlbuttonelement.rs`

Some tests that might be relevant:
* `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/`
* `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/forms/attributes-common-to-form-controls/`
* `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/forms/form-submission-0/`

**Comment by nishanthkarthik** [comment]
@highfive assign me

**Comment by nishanthkarthik** [comment]
@jdm This is my first issue on servo. Let me give it a shot!

**Comment by jdm** [comment]
@nishanthkarthik Have you made progress?

**Comment by nishanthkarthik** [comment]
I'm on the test cases. I expect to send a PR by this weekend

**Comment by nishanthkarthik** [comment]
@jdm I tried `dispatchEvent` with keydown event this way.

```
<!doctype html>
<meta charset="utf-8">
<title>Click action on label</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>

<div id="test"></div>
<a id="anch" href="about:blank">test</a>

<script>
async_test(function(t) {
        document.querySelector("#test").innerHTML = '<iframe src=html-anchor-navigation.html \
            id="foo" name="foo"></iframe>'

        var loaded = false;
        var iframe = document.getElementById('foo');
        iframe.onload = t.step_func(function() {
            if (!loaded) {
                loaded = true;
                var ev = new KeyboardEvent('keydown', { code: "Space" });
                var elem = iframe.contentDocument.getElementById('anc');
                elem.focus();
                elem.dispatchEvent(ev);
            } else {
                t.done();
            }
        });
    }, "space keydown should navigate away");
</script>

```

When I manually press space, it navigates away. It does not, when it is done through `dispatchEvent`. I also tried using `testdriver.js` to send the event, but it doesn't support sending it to a node in an iframe.

**Comment by jdm** [comment]
Oh, right. That makes sense, because there is no code in htmlanchorelement.rs to recognize key events and act on them.

That being said, I just tested Firefox and Chrome, and they don't actually invoke links on space, so we should not deviate from their behaviour. However, they do activate a `<button>` element on space, so we should make sure we still support that.

**Comment by jdm** [comment]
I think the right choice may be to add custom handle_event implementations for elements like `<button>` that should recognize both space and enter: https://searchfox.org/mozilla-central/rev/3e0f1d95fcf8832413457e3bec802113bdd1f8e8/dom/html/HTMLButtonElement.cpp#233-251

That will allow us to write automated tests that verify that property.

**Comment by stevenloppe** [comment]
@highfive: assign me

**Comment by dralley** [comment]
@stevenloppe Are you working on this?

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by Ersikan** [comment]
@highfive: assign me

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by garasubo** [comment]
@highfive assign me

**Comment by garasubo** [comment]
I'm sorry, but I found that one of commits were not included in the previous PR. I resubmit another PR to add this commit #24546. Could you take a look?
