### ISSUE TITLE
Integrate activation behaviour into event dispatch algorithm

### ISSUE THREAD

**Issue by jdm** [servo/servo#22783]
`synthetic_click_activation` implements an old algorithm for activating elements via synthetic mouse click events. We should rewrite it to implement [this synthetic mouse event algorithm](https://html.spec.whatwg.org/multipage/#fire-a-synthetic-mouse-event) and integrate the activation behaviour into the event dispatch algorithm [per the spec](https://dom.spec.whatwg.org/#concept-event-dispatch). This will address the comment in `Document::dispatch_key_event` about synthetic click activiation being unspecified, since it has been specified appropriately in the past 4 years.

Code: `components/script/dom/document.rs`, `components/script/dom/eventtarget.rs`, `components/script/activation.rs`

**Comment by aditj** [comment]
I'd like to work on this :grin: . If there are no problems assign me!

**Comment by aditj** [comment]
> `synthetic_click_activation` implements an old algorithm for activating elements via synthetic mouse click events. We should rewrite it to implement [this synthetic mouse event algorithm](https://html.spec.whatwg.org/#fire-a-synthetic-mouse-event) and integrate the activation behaviour into the event dispatch algorithm [per the spec](https://dom.spec.whatwg.org/#concept-event-dispatch). This will address the comment in `Document::dispatch_key_event` about synthetic click activiation being unspecified, since it has been specified appropriately in the past 4 years.
> 
> Code: `components/script/dom/document.rs`, `components/script/dom/eventtarget.rs`, `components/script/activation.rs`
Minor error : components/script/dom/activation.rs

**Comment by jdm** [comment]
@aditj Have you made progress?

**Comment by aditj** [comment]
@jdm 
Hey! Sorry for the delay I was working on one of the previous issues, I looked into the issue today, progressed a bit .
First of all, I am looking into rewriting the implementation before integrating it into the event dispatch algorithm. I have some( actually many :stuck_out_tongue: ) questions regarding the issue.
a) Do we need the following in the new synthetic_click_activation function : 
  *  source(ActivationSource) [parameter](https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/script/dom/activation.rs#L65) 
   * The [step 1-3 of the previous implementation](https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/script/dom/activation.rs#L67)
   * This [kind](https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/script/dom/activation.rs#L109) of activation check.

b) Do I need to create a composed flag inside the Event or MouseEvent Structure?(Step 4 of [spec](https://html.spec.whatwg.org/#fire-a-synthetic-mouse-event) )
c) How do I get the current state of the key input device? (Step 8 of [spec](https://html.spec.whatwg.org/#fire-a-synthetic-mouse-event) )

**Comment by jdm** [comment]
a)
* The source parameter is another way of representing the `not trusted` flag, since [this use](https://html.spec.whatwg.org/multipage/interaction.html#activation:fire-a-synthetic-mouse-event) passes it and [this use](https://html.spec.whatwg.org/multipage/webappapis.html#event-firing:fire-a-synthetic-mouse-event) does not
* It looks like steps 1-2 are not necessary; step 3 will become part of the event dispatch algorithm (see step 12 of https://dom.spec.whatwg.org/#concept-event-dispatch)
* that will also become part of the event dispatch algorithm

b) you can leave a TODO comment about setting the composed flag, since we do not support it yet.

c) Do the same as the current code, which accepts those key state values as arguments.

**Comment by aditj** [comment]
> a)
> 
> * The source parameter is another way of representing the `not trusted` flag, since [this use](https://html.spec.whatwg.org/multipage/interaction.html#activation:fire-a-synthetic-mouse-event) passes it and [this use](https://html.spec.whatwg.org/multipage/webappapis.html#event-firing:fire-a-synthetic-mouse-event) does not
> * It looks like steps 1-2 are not necessary; step 3 will become part of the event dispatch algorithm (see step 12 of https://dom.spec.whatwg.org/#concept-event-dispatch)
> * that will also become part of the event dispatch algorithm
> 
> b) you can leave a TODO comment about setting the composed flag, since we do not support it yet.
> 
> c) Do the same as the current code, which accepts those key state values as arguments.

a) I am gonna use the not_trusted flag in that case since that would be more clear and in compliance.
c) So I don't need to make a getModifierState() method for MouseEvent ?

**Comment by jdm** [comment]
c) I do not believe so.

**Comment by aditj** [comment]
@jdm About ActivationSource parameter v/s activation flag, which one would be better because the code base already uses the parameter a lot as is evident in the errors reported in the [error log](https://travis-ci.com/servo/servo/jobs/182994066#L2646-L2680) . I personally feel a flag should be used (since that would conform to the specs) but that would require changes in the aforementioned files.
Also just clarifying here , a FromClick ActivationSource would mean it is trusted, right?

**Comment by jdm** [comment]
I think it makes sense to match the specification and use the trusted flag instead. And yes, click is trusted.

**Comment by jdm** [comment]
#22981 was a PR to address this but there were review comments that still need to be addressed.

**Comment by pshaughn** [comment]
I started looking into this in #25384 and it makes sense to do the entire spec update at once. I'll look at that PR and hopefully there's not much more to do from there.

**Comment by pshaughn** [comment]
There's more to be done from #22981 to keep things synced up with spec terminology and step numbering. The essential meat of making clicks work seems close to done already, and I don't know how many of the remaining changes are functional, but untangling code/spec correspondences took a while when I was looking into #25384 so I think it's worth taking time here to reflect the spec for future maintainability. (I'm assuming that the way click events are now specified is more or less stable and there won't be another big shift.)

**Comment by pshaughn** [comment]
The terminology change and main reorganization happened in https://github.com/whatwg/html/pull/1925; I'll use that to get a roadmap of which functions need looking at.

**Comment by jdm** [comment]
Thanks for looking into this @pshaughn!

**Comment by pshaughn** [comment]
I've encountered a subtle point and advice might help. It looks like the path of an event is supposed to be a property of the event itself, rather than a local variable of the dispatch algorithm. The path gets cleared at the end of the dispatch, but it's possible for one dispatch to happen _during_ another dispatch of the same event, in which case it looks like the second dispatch is supposed to _append_ to the first one's path and then capture/bubble over the entire combined path.

What I'm not sure about are:
* why it's written this way, and indeed whether it's even an intended result as opposed to a specification oversight.
* what the outer dispatch is supposed to do next if a nested dispatch has cleared the event path. It's saying to going over the path with a simple "for each" instruction that doesn't explicitly account for the path changing as it iterates.

I'm currently leaning towards keeping the path local to the dispatch algorithm and just adding a comment about it.

**Comment by jdm** [comment]
Ah, the idea being that in an event handler content JS could end up calling `someElement.dispatchEvent(event)` on the event currently being dispatched? I think that's impossible, because of step 1 in https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent and step 1 in https://dom.spec.whatwg.org/#ref-for-dispatch-flag%E2%91%A2. Am I missing something?

As for the change from an algorithm variable to a property of the event, that appears to have occurred in https://github.com/whatwg/dom/commit/ed94c9f2f1850b2e6a9b357c6870186859da4c2d.

**Comment by pshaughn** [comment]
Thank you for finding that whatwg/dom PR. I still don't see what it's for exactly, but it must be something to do with the path crossing boundaries between shadow and light DOM. I wasn't planning on implementing anything to do with shadow DOM in this pass so I will leave it local with a comment that it might need to become a property for shadow DOM support.

**Comment by jdm** [comment]
That sounds reasonable to me.
