### ISSUE TITLE
Support default toJSON in WebIDL

### ISSUE THREAD

**Issue by jdm** [servo/servo#22781]
https://searchfox.org/mozilla-central/rev/c07aaf12f13037c1f5a343d31f8291549e57373f/dom/bindings/Codegen.py#8846-8879
https://searchfox.org/mozilla-central/rev/c07aaf12f13037c1f5a343d31f8291549e57373f/dom/bindings/Configuration.py#422-441

**Comment by jdm** [comment]
https://heycam.github.io/webidl/#es-default-tojson

**Comment by saschanaz** [comment]
Working on this
