### ISSUE TITLE
Measure the performance of uncontended RwLock

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#22790]
We've taken as a given that guarding every layout object with a RwLock is expensive, but is that actually true for uncontended objects? We have pretty much the ideal case for performance of RwLock. In a correct implementation, there will be no contention on either writes or reads, so the only overhead will be the overhead of an uncontended compare-and-swap. As long as there is no cache line contention, that should be very fast on x86. On ARM, it's about comparable to the cost of an Arc reference count bump, which uses load-linked/store-conditional. That doesn't seem bad to me at all…

Being able to just use RwLock everywhere (or, more probably, a modified of RwLock that panics if there is contention, since in correct layout code there should be none) would make a lot of the thorny layout questions go away…

**Comment by pcwalton** [comment]
cc @SimonSapin

**Comment by pcwalton** [comment]
I made an attempt to convert Servo layout over to `parking_lot` RwLock at http://github.com/pcwalton/servo/tree/rwlock. It compiles, but it'll need some more work before it actually runs. To get some early numbers I made a silly patch that adds a useless RwLock critical section before doing any layout step around a node to test performance. (The RwLock guards an unused counter, to make sure the compiler doesn't optimize it out.)

Results *with no lock* (i.e. Servo master):

    _category_                          _incremental?_ _iframe?_             _url_                  _mean (ms)_   _median (ms)_      _min (ms)_      _max (ms)_       _events_ 
    Compositing                             N/A          N/A                  N/A                       46.3838          0.3079          0.0067        598.1235              13
    Layout                                  yes          yes     https://en.wikipedia.org/wiki/          4.6356          3.1762          1.0891         30.4401              44
    Layout                                  no           yes     https://en.wikipedia.org/wiki/         76.7806         76.7806         76.7806         76.7806               1
    + Style Recalc                          yes          yes     https://en.wikipedia.org/wiki/          1.8238          0.0892          0.0077         25.7095              43
    + Style Recalc                          no           yes     https://en.wikipedia.org/wiki/         70.0522         70.0522         70.0522         70.0522               1
    | + Text Shaping                        yes          yes     https://en.wikipedia.org/wiki/          0.0038          0.0000          0.0000          0.0710              43
    | + Text Shaping                        no           yes     https://en.wikipedia.org/wiki/          7.7747          7.7747          7.7747          7.7747               1
    + Restyle Damage Propagation            yes          yes     https://en.wikipedia.org/wiki/          0.0419          0.0390          0.0161          0.1176              44
    + Restyle Damage Propagation            no           yes     https://en.wikipedia.org/wiki/          0.0386          0.0386          0.0386          0.0386               1
    + Generated Content Resolution          yes          yes     https://en.wikipedia.org/wiki/          0.0109          0.0058          0.0028          0.0903              44
    + Generated Content Resolution          no           yes     https://en.wikipedia.org/wiki/          0.0963          0.0963          0.0963          0.0963               1
    + Float Placement Speculation           yes          yes     https://en.wikipedia.org/wiki/          0.0677          0.0605          0.0371          0.1351              44
    + Float Placement Speculation           no           yes     https://en.wikipedia.org/wiki/          0.0605          0.0605          0.0605          0.0605               1
    + Primary Layout Pass                   yes          yes     https://en.wikipedia.org/wiki/          1.2343          1.0638          0.8284          3.0515              44
    + Primary Layout Pass                   no           yes     https://en.wikipedia.org/wiki/          1.1214          1.1214          1.1214          1.1214               1
    + Store Overflow                        yes          yes     https://en.wikipedia.org/wiki/          0.1277          0.0966          0.0666          0.4189              44
    + Store Overflow                        no           yes     https://en.wikipedia.org/wiki/          0.0845          0.0845          0.0845          0.0845               1
    + Display List Construction             yes          yes     https://en.wikipedia.org/wiki/          1.1212          1.6251          0.0520          2.9724              44
    + Display List Construction             no           yes     https://en.wikipedia.org/wiki/          2.2700          2.2700          2.2700          2.2700               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/w/loa         19.8855         19.8855         19.8855         19.8855               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/w/loa          1.0181          1.0181          1.0181          1.0181               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/w/loa          1.7855          1.7855          1.7855          1.7855               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/w/loa         20.9208         20.9208         20.9208         20.9208               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/wiki/          0.3656          0.3972          0.0825          0.7271               4
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/wiki/          1.3255          1.3255          1.3255          1.3255               1
    Script JS Evaluate                      no           yes     https://login.wikimedia.org/wi          0.2412          0.2412          0.2412          0.2412               1
    Script Parse HTML                       no           yes     about:blank                             3.2905          3.2905          3.2905          3.2905               1
    Script Parse HTML                       no           yes     https://en.wikipedia.org/wiki/          7.4707          2.0123          0.0003         78.4226              14
    Script Parse HTML                       no           yes     https://en.wikipedia.org/wiki/          7.8471          0.0561          0.0507         23.4343               3
    Time To First Paint                     no           yes     https://en.wikipedia.org/wiki/          0.0000          0.0000          0.0000          0.0000               1
    Time To First Contentful Paint          no           yes     https://en.wikipedia.org/wiki/          0.0000          0.0000          0.0000          0.0000               1
    Blocked at IPC Receive                  N/A          N/A                  N/A                        0.0650          0.0552          0.0279          0.1119              24

Results *with lock*:

    _category_                          _incremental?_ _iframe?_             _url_                  _mean (ms)_   _median (ms)_      _min (ms)_      _max (ms)_       _events_ 
    Compositing                             N/A          N/A                  N/A                       48.9531          0.2894          0.0072        582.2742              12
    Layout                                  yes          yes     https://en.wikipedia.org/wiki/          4.1539          2.9797          1.0746         24.5104              43
    Layout                                  no           yes     https://en.wikipedia.org/wiki/         80.5999         80.5999         80.5999         80.5999               1
    + Style Recalc                          yes          yes     https://en.wikipedia.org/wiki/          1.5152          0.1009          0.0073         19.7567              42
    + Style Recalc                          no           yes     https://en.wikipedia.org/wiki/         73.5313         73.5313         73.5313         73.5313               1
    | + Text Shaping                        yes          yes     https://en.wikipedia.org/wiki/          0.0028          0.0000          0.0000          0.0382              42
    | + Text Shaping                        no           yes     https://en.wikipedia.org/wiki/          7.4602          7.4602          7.4602          7.4602               1
    + Restyle Damage Propagation            yes          yes     https://en.wikipedia.org/wiki/          0.0410          0.0338          0.0153          0.1356              43
    + Restyle Damage Propagation            no           yes     https://en.wikipedia.org/wiki/          0.0380          0.0380          0.0380          0.0380               1
    + Generated Content Resolution          yes          yes     https://en.wikipedia.org/wiki/          0.0118          0.0049          0.0026          0.0817              43
    + Generated Content Resolution          no           yes     https://en.wikipedia.org/wiki/          0.0992          0.0992          0.0992          0.0992               1
    + Float Placement Speculation           yes          yes     https://en.wikipedia.org/wiki/          0.0758          0.0637          0.0354          0.2131              43
    + Float Placement Speculation           no           yes     https://en.wikipedia.org/wiki/          0.0734          0.0734          0.0734          0.0734               1
    + Primary Layout Pass                   yes          yes     https://en.wikipedia.org/wiki/          1.1300          1.0606          0.8014          2.2583              43
    + Primary Layout Pass                   no           yes     https://en.wikipedia.org/wiki/          1.1706          1.1706          1.1706          1.1706               1
    + Store Overflow                        yes          yes     https://en.wikipedia.org/wiki/          0.1244          0.0951          0.0644          0.3355              43
    + Store Overflow                        no           yes     https://en.wikipedia.org/wiki/          0.0946          0.0946          0.0946          0.0946               1
    + Display List Construction             yes          yes     https://en.wikipedia.org/wiki/          1.0532          1.5422          0.0515          3.0807              43
    + Display List Construction             no           yes     https://en.wikipedia.org/wiki/          2.3714          2.3714          2.3714          2.3714               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/w/loa         19.0842         19.0842         19.0842         19.0842               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/w/loa          0.7096          0.7096          0.7096          0.7096               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/w/loa          1.5619          1.5619          1.5619          1.5619               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/w/loa         20.6697         20.6697         20.6697         20.6697               1
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/wiki/          0.5179          0.5933          0.1262          1.0607               4
    Script JS Evaluate                      no           yes     https://en.wikipedia.org/wiki/          1.0009          1.0009          1.0009          1.0009               1
    Script JS Evaluate                      no           yes     https://login.wikimedia.org/wi          0.5788          0.5788          0.5788          0.5788               1
    Script Parse HTML                       no           yes     about:blank                             3.2454          3.2454          3.2454          3.2454               1
    Script Parse HTML                       no           yes     https://en.wikipedia.org/wiki/          6.9419          2.2002          0.0012         82.1983              16
    Script Parse HTML                       no           yes     https://en.wikipedia.org/wiki/          7.2854          0.1444          0.0455         21.6665               3
    Time To First Paint                     no           yes     https://en.wikipedia.org/wiki/          0.0000          0.0000          0.0000          0.0000               1
    Time To First Contentful Paint          no           yes     https://en.wikipedia.org/wiki/          0.0000          0.0000          0.0000          0.0000               1
    Blocked at IPC Receive                  N/A          N/A                  N/A                        0.0744          0.0694          0.0232          0.1629              24

As I suspected, I don't see any difference here. Layout dwarfs the cost of a single atomic operation.

There may be more atomic operations when this is deployed for real, of course, due to parents taking out write locks on their kids and so forth.

**Comment by pcwalton** [comment]
cc @jdm

**Comment by nox** [comment]
Given we are not ever supposed to wait on that lock (right?), shouldn't we be using `AtomicRefCell<T>` instead?

**Comment by pcwalton** [comment]
Probably, yeah.

**Comment by SimonSapin** [comment]
Hard to say whether the workload for layout trees is very different than for CSSOM in selector matching, but Stylo ended up unsafely bypassing some `RwLock`s:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1311469
* https://bugzilla.mozilla.org/show_bug.cgi?id=1335941

**Comment by nox** [comment]
AFAIK this is irrelevant now.
