### ISSUE TITLE
Support a test WebVR/XR display

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#22795]
For testing, it would be nice to have a WebVR/XR implementation that renders to the current window. Firefox has such a thing behind a `dom.vr.test.enabled` pref.

**Comment by asajeffrey** [comment]
The code for this is also the code needed to support immersive mode on VR devices that don't have an external display, e.g. the magicleap (#22402).

**Comment by paulrouget** [comment]
I do something like that for Firefox Reality + Servo. WebVR content is rendered directly on the screen. But it's not something that's on the Servo side.

Have you looked at the mock webvr implementation: https://github.com/servo/rust-webvr/tree/master/rust-webvr/src/api/mock

Would that help?

**Comment by asajeffrey** [comment]
Yes, I had a look at the mock VR implementation, but it's very mock. For example, we'd need something that returned the right values for the render with and height, and related display parameters.

**Comment by asajeffrey** [comment]
With this in place, we could start writing WebVR/XR reftests.
