### ISSUE TITLE
Could not load the requested page: Unexpected scheme

### ISSUE THREAD

**Issue by FruityWelsh** [servo/servo#22826]
This is the error I get when I click on the facebook logo.

Could not load the requested page: Unexpected scheme

**Comment by jdm** [comment]
The debug output in my terminal suggests this is a panic in WebRender:
```
Tried to use WebRender SpatialId before it was defined. (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(3) }, at src/libcore/option.rs:1038)
[2019-02-05T15:21:27Z ERROR servo] Tried to use WebRender SpatialId before it was defined.
```

**Comment by jdm** [comment]
I got this right after logging in while it was trying to display the homepage.
