### ISSUE TITLE
Implement deprecated PerformanceNavigation interface

### ISSUE THREAD

**Issue by jdm** [servo/servo#22828]
Spec:
https://w3c.github.io/navigation-timing/#the-performancenavigation-interface
https://w3c.github.io/navigation-timing/#extensions-to-the-performance-interface

Code: `components/script/dom/performance.rs`, `components/script/dom/webidls/performance.webidl`

This will require [adding a new DOM interface](https://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface) for PerformanceNavigation.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/6745
This page should show "log: 0" in the log table when the interface exists.

Loading twitter in Servo shows a JS error where it assumes this interface exists. Adding this implementation should make that error go away and make twitter behave better in Servo.

**Comment by ForsakenDurian** [comment]
@highfive: assign me

**Comment by ForsakenDurian** [comment]
Okay, I have no idea what to define within the DOM struct. Sorry, I'm new to this.

**Comment by jdm** [comment]
@ForsakenDurian Sorry about the delay in answering; I think it would be reasonable to make the `type` getter return `TYPE_NAVIGATE` all the time, and return `self.global().as_window().document().get_redirect_count()` for the `redirectCount` getter.

**Comment by himanish-star** [comment]
@jdm as per our discussion in the mail, can I be assigned this issue :)

**Comment by CYBAI** [comment]
@himanish-star I believe you can go ahead because this is not assigned now! :)

**Comment by himanish-star** [comment]
@CYBAI, sorry I just seemed to miss out on your comment,  starting right away :)

**Comment by ForsakenDurian** [comment]
Good luck!

**Comment by iulianR** [comment]
@highfive: assign me

**Comment by iulianR** [comment]
@himanish-star Do you mind if I pick up this issue? I had a thorough look and I'm confident I can fix this as my first issue. Thank you.
