### ISSUE TITLE
Creates a C header file for libsimpleservo API

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#22834]
The `extern "C"` functions and the `#[repr(C)]` structs in https://github.com/servo/servo/blob/master/ports/libsimpleservo/capi/src/lib.rs should be available as a `.h` file as well.

We could create the .h manually and build the .rs file with bindgen, or keep the .rs and build the .h with rusty-cheddar.

For the record, I built that .h manually for another project: https://github.com/paulrouget/libui-servo-example/blob/d65faaa9cbb36fd999d6c99be108a2d5804d40f0/main.h

**Comment by SimonSapin** [comment]
WebRender uses https://crates.io/crates/cbindgen instead of rusty-cheddar.

**Comment by paulrouget** [comment]
@SimonSapin thanks. This works well. Waiting on https://github.com/eqrion/cbindgen/pull/271
