### ISSUE TITLE
Shorthand properties of computed CSSStyleDeclaration don't return correct values

### ISSUE THREAD

**Issue by jdm** [servo/servo#22838]
```html
<div id="test" style="overflow: hidden"></div>
<script>onload = function() {
  var div = document.getElementById('test');
  console.log(getComputedStyle(div).overflow)
  console.log(getComputedStyle(div).overflowX);
};
</script>
```
In Firefox, this shows `hidden` twice. In Servo this shows an empty string, followed by `hidden`.

**Comment by jdm** [comment]
There's a comment in `processed_resolved_style_request` that looks fishy to me given Firefox's behaviour:
```
        // Firefox returns blank strings for the computed value of shorthands,
        // so this should be web-compatible.
```

**Comment by jdm** [comment]
@emilio This behaviour was introduced in 0ad2d39c30ac2827e4956224de578f2dea78916d. Firefox appears to behave differently now; do you know when that changed?

**Comment by jdm** [comment]
Mmm, maybe it was introduced in 58d452fa4e7b4b426925fe3bc525251048ae2830 instead.

**Comment by jdm** [comment]
Chrome also returns real values for shorthands, so Servo's behaviour is definitely not web compatible.

**Comment by jdm** [comment]
I think the right thing to do here is implement the same shorthand logic as [Servo_GetPropertyValue](https://searchfox.org/mozilla-central/rev/e00ea598e52bbb35f8c45abf9c2eade17962bb5e/servo/ports/geckolib/glue.rs#5677) in at least `process_resolved_style_request_internal`, possibly `process_resolved_style_request` as well.

**Comment by jdm** [comment]
Ah, I see https://github.com/w3c/csswg-drafts/issues/2529 and the note in the spec for step 5 of https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle which explicitly mentions overflow.

**Comment by emilio** [comment]
Sorry I never replied here. Shorthands are special, but firefox only serializes some (in particular, it only serializes the ones that used to be longhands).

**Comment by mjstealth** [comment]
If this issue is still open, I'd like to take it up as my first step into Servo world. I have it running locally on my mac. @jdm any thoughts?

**Comment by jdm** [comment]
@mjstealth Yes, this should be a decent starter issue! The code in https://searchfox.org/mozilla-central/rev/master/servo/ports/geckolib/glue.rs#6359-6380 is still a good model; rather than returning an empty string from https://github.com/servo/servo/blob/0d0cfd030347ab0711b3c0607a9ee07ffe7124cf/components/layout/query.rs#L945 we should use the ShorthandId inside the PropertyId value (https://github.com/servo/servo/blob/0d0cfd030347ab0711b3c0607a9ee07ffe7124cf/components/style/properties/properties.mako.rs#L1848-L1852) to create a property declaration block from the shorthand's longhand properties and call shorthand_to_css on the property declaration block.

**Comment by mjstealth** [comment]
@jdm Perfect. Thanks for the pointers. I will start digging in.

**Comment by sebsebmc** [comment]
I'm going to assign myself since @mjstealth never assigned themselves and theres not been an update in over 2.5 years.

@highfive: assign me

**Comment by sebsebmc** [comment]
@highfive: assign me

**Comment by sebsebmc** [comment]
@servo-highfive: assign me

**Comment by servo-highfive** [comment]
Hey @sebsebmc! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by sebsebmc** [comment]
Ive been running the WPT tests locally and looking for special cases where the naïve solution doesn't work. It appears that there are some properties that are settable via longhand but not settable via shorthand, and there are tests that expect the shorthand to no longer serialize correctly when these values are set, for example: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant#small-caps the test https://github.com/web-platform-tests/wpt/blob/12a51d92951f2858e1ad74a4412279e645e67a61/css/css-fonts/font-shorthand-serialization-prevention.html#L81 checks that `all-small-caps` causes the font shorthand to no longer serialize.
