### ISSUE TITLE
Implement WheelEvent interface

### ISSUE THREAD

**Issue by jdm** [servo/servo#22843]
Spec: https://w3c.github.io/uievents/#events-wheelevents
Docs: https://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface

I see `[2019-02-06T22:41:04Z ERROR script::dom::bindings::error] Error at https://assets-prod.reticulum.io/assets/js/hub-01a8e131ea6755144653.js:1:376343 WheelEvent is not defined` when creating a Hubs room.

**Comment by jdm** [comment]
We can hook this up to the [MouseWheel](https://doc.servo.org/glutin/enum.DeviceEvent.html#variant.MouseWheel) device event in [this event handling loop](https://github.com/servo/servo/blob/73ff9995fbd062887d86a37d7349caa26b95d1a5/ports/servo/glutin_app/window.rs#L442), and add a new [WindowEvent](https://github.com/servo/servo/blob/73ff9995fbd062887d86a37d7349caa26b95d1a5/components/compositing/windowing.rs#L39) kind that sends an event to the script thread like we do with mouse and keyboard events.

**Comment by robert-snakard** [comment]
@highfive: assign me

Hey @jdm. I'm taking a look at this, brand new to working on Servo, got a bunch of questions. First off,  what is "Hubs"?

**Comment by robert-snakard** [comment]
Next up I'm copying the mouseevent.rs and keyboardevent.rs files. According to the w3c documentation the attributes for the mouse event and keyboard event are readonly, however the rust code puts all these values in Cells. Do you know why that is? 

See here:
```
interface MouseEvent : UIEvent {
  readonly attribute long screenX;
  readonly attribute long screenY;
  readonly attribute long clientX;
  readonly attribute long clientY;

  readonly attribute boolean ctrlKey;
  readonly attribute boolean shiftKey;
  readonly attribute boolean altKey;
  readonly attribute boolean metaKey;

  readonly attribute short button;
  readonly attribute unsigned short buttons;

  readonly attribute EventTarget? relatedTarget;

  boolean getModifierState(DOMString keyArg);
};
```

and here:
```
#[dom_struct]
pub struct MouseEvent {
    uievent: UIEvent,
    screen_x: Cell<i32>,
    screen_y: Cell<i32>,
    client_x: Cell<i32>,
    client_y: Cell<i32>,
    ctrl_key: Cell<bool>,
    shift_key: Cell<bool>,
    alt_key: Cell<bool>,
    meta_key: Cell<bool>,
    button: Cell<i16>,
    related_target: MutNullableDom<EventTarget>,
    point_in_target: Cell<Option<Point2D<f32>>>
}
```

**Comment by robert-snakard** [comment]
Second the dom constants are generated in codegen/BindingGen.py. How do I look at the output Bindings module? There certainly is one but I can't seem to find it. A grep for "KeyboardEventBinding" just turns up the places that use it, not the file it lives in

**Comment by robert-snakard** [comment]
Second, the DOM constants are generated in `BindingGen.py`. How do I find the files generated by this script? A grep for `KeyboardEventBinding` only turned up the files that use the import, not the file that owns the enum.

**Comment by robert-snakard** [comment]
Ah, all the bindgen types are in the online documentation :thumbsup:

**Comment by jdm** [comment]
Hubs is https://hubs.mozilla.com/.

**Comment by robert-snakard** [comment]
Thanks. I'm having issues with the linker (see my question [here](https://github.com/servo/servo/issues/21970)) but I did create the event and get it to compile (on [this](https://github.com/robert-snakard/servo/tree/issue_22843) branch). Now I just have to add the hooks you described previously.

Also as far as testing goes, the only tests I found for mouseevent were the manual tests in tests/wpt/web-platform-tests/uievents/mouse/. Will a couple manual tests for wheelevent be enough? Or are there some automatic tests I haven't found yet?

**Comment by jdm** [comment]
Manual tests should be enough; Servo certainly doesn't support any automated tests for mouse input yet.

**Comment by jdm** [comment]
@robert-snakard Have you made any progress? Do you have any questions?

**Comment by robert-snakard** [comment]
Hey jdm, thanks for checking up. Life got busy the last two weeks and this had to take a back seat. Should I let someone know next time?

I forked the web platform tests repo and trying to figure that out. Working on one test to check we captured the wheel event properly and another to check we don't try to scroll after we've captured the wheel event.

As far as questions go, how should I handle that in Servo? Looking at the event loop you posted it seems we always scroll when we get a mouse event from glutin. I could just do a 
```
if (WheelEventListenerExists) { 
    sendWheelEvent();
} else {
    scroll();
}
```
But I want to know if there's a fancier / Rusty-er way to do it

**Comment by jdm** [comment]
I think that is how we will need to handle it. In order to avoid a round-trip to the script thread for every scroll event, the script thread should send a notification to the constellation when a wheel event listener exists, and the constellation should relay that to the compositor.

**Comment by jdm** [comment]
Also Servo has a complete vendored copy of the wpt repo in tests/wpt/web-platform-tests if that's easier for you. We also have bidirectional syncing of any changes made to it.

**Comment by robert-snakard** [comment]
Cool. Where's the constellation? doc.servo.org is being flaky today

**Comment by jdm** [comment]
components/constellation/constellation.rs, and components/msg/constellation_msg.rs for the messages that are sent to it.

**Comment by robert-snakard** [comment]
@jdm finished the scrolling wpt test (you can find it [here](https://github.com/robert-snakard/wpt/blob/wheel_event_wpt_test/uievents/order-of-events/mouse-events/wheel-scrolling-manual.html)) and tested it in both firefox and chrome. Both of them scroll the page even though the div has a listener on the wheel event. Going to give Servo the same behavior, send a wheel event **and** scroll, unless there's a good reason to alter behavior.

**Comment by jdm** [comment]
Even better. Thanks for verifying that behaviour!

**Comment by robert-snakard** [comment]
The pull request for the wpt tests is here https://github.com/web-platform-tests/wpt/pull/15990

**Comment by robert-snakard** [comment]
@jdm just a status update. Working on sending the wheel event from the compositor to the script thread. I've found the line where I need to send a message through the constellation. Right now working on getting all the variables I need. 

I need to get a DevicePoint for my wheel event so that I can get a pipeline_id for the constellation.

**Comment by robert-snakard** [comment]
Hey @jdm, looking at the [script_traits::CompositorEvent](https://doc.servo.org/script_traits/enum.CompositorEvent.html) right now. Why is the MouseMoveEvent have an optional Point2D? Won't the pointer always exist somewhere on the screen?

**Comment by jdm** [comment]
@robert-snakard Based on the docs, I expect that when None is passed it means that the mouse is no longer inside the window.

**Comment by robert-snakard** [comment]
@jdm code is done. WPT tests pass and creating a room on Mozilla Hubs no longer reports a WheelEvent error. About to rebase, should have the pull request for you by tonight.

**Comment by robert-snakard** [comment]
Pull request is here https://github.com/servo/servo/pull/23154
