### ISSUE TITLE
Implement CDataSection interface and createCDATASection method

### ISSUE THREAD

**Issue by jdm** [servo/servo#22846]
Spec:
* https://dom.spec.whatwg.org/#interface-cdatasection
* https://dom.spec.whatwg.org/#ref-for-dom-document-createcdatasection
* https://dom.spec.whatwg.org/#dom-document-createcdatasection
* https://dom.spec.whatwg.org/#ref-for-dom-node-cdata_section_node
* https://dom.spec.whatwg.org/#dom-node-nodename

This will require following [the documentation](https://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface) for adding a new WebIDL interface.

**Comment by georgeroman** [comment]
@highfive: assign me
