### ISSUE TITLE
 Support "noreferrer" for window.open()

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#22869]
whatwg/html#4331
web-platform-tests/wpt#15352
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1527287

**Comment by gterzian** [comment]
Code: https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/script/dom/windowproxy.rs#L398

Also note this is probably a good time to first do https://html.spec.whatwg.org/#concept-window-open-features-tokenize

**Comment by dboyan** [comment]
I have written a prototype of tokenizer: https://github.com/dboyan/servo/tree/open-feature-tokenize. Passes all but one subtests in noopener tokenizer test. Advice is welcomed, since I'm new to Rust and Servo.

After finishing up the tokenizer, noreferrer support shouldn't be very hard.

**Comment by CYBAI** [comment]
Due to @dboyan opening the PR, I'm going to add `C-assigned` for this issue.
