### ISSUE TITLE
Cleanup layout code that could use type alias enum variants. 

### ISSUE THREAD

**Issue by emilio** [servo/servo#22862]
We have a fair amount of code that imports `Foo as GenericFoo`, in order to be able to match on a type alias.

Code under `components/layout/` can be adjusted to use https://github.com/rust-lang/rust/issues/49683 (code under `components/style/` cannot, yet, until that feature is stabilized).

Example of code to clean up is:

https://github.com/servo/servo/blob/5de6d87c97050db35cfb0a575e14b4d9b6207ac5/components/layout/display_list/border.rs#L166

Where we can remove the import of:

```rust
use style::values::generics::border::BorderImageSideWidth as GenericBorderImageSideWidth;
```

And replace uses of GenericBorderImageSideWidth by just `BorderImageSideWidth`.

**Comment by ksavinash9** [comment]
@highfive: assign me

**Comment by jdm** [comment]
@ksavinash9 Have you made any progress? Are you still working on this?

**Comment by championshuttler** [comment]
Hi Can I take this up if @ksavinash9 is not working?

**Comment by jdm** [comment]
@championshuttler If you would still like to work on this, let us know :)

**Comment by kleinph** [comment]
If nobody is working on this, I would like to take it

**Comment by jdm** [comment]
@kleinph Go for it!

**Comment by CYBAI** [comment]
> code under `components/style/` cannot, yet, until that feature is stabilized

Should we keep this open for the style folder 👀?
