### ISSUE TITLE
Intermittent failure in /css/CSS2/floats-clear/clear-float-001.xht (bolded text)

### ISSUE THREAD

**Issue by jdm** [servo/servo#22865]
On macOS:
Test:
<img width="582" alt="screen shot 2019-02-11 at 10 33 24 am" src="https://user-images.githubusercontent.com/27658/52573595-80ea1d80-2de8-11e9-915f-fe4eb766e7b4.png">

Reference:
<img width="565" alt="screen shot 2019-02-11 at 10 33 30 am" src="https://user-images.githubusercontent.com/27658/52573604-86dffe80-2de8-11e9-9f40-d224a799aa11.png">

Since the tests do not include any font styling CSS, I fear this may be UB in our platform font code.

**Comment by mrobinson** [comment]
I suspect this is now fixed by the recent changes to ensure we load the right font from the MacOS font list.
