### ISSUE TITLE
Migrate Windows/Taskcluster AMI to generic-worker 13

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#22870]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1375182#c6. CC https://github.com/servo/servo/issues/22325.

**Comment by petemoore** [comment]
@SimonSapin I've mirrored this issue in [bug 1527613](https://bugzil.la/1527613) for helping us track work item dependencies in bugzilla. I would be grateful if you could close that bug when this issue is resolved.

Many thanks!

**Comment by SimonSapin** [comment]
Steps:

* [x] Edit `etc/taskcluster/windows/first-boot.ps1` and create a new AMI
* [x] Create a [servo-win2016-staging](https://tools.taskcluster.net/aws-provisioner/servo-win2016-staging/view) worker type similar to [servo-win2016](https://tools.taskcluster.net/aws-provisioner/servo-win2016/view), with:
  - The new AMI configured
  - The `secrets` key emptied (not removed as it’s apparently required by the schema)
  - `ed25519SigningKeyLocation` config added, next to `signingKeyLocation`
* [ ] Manually run tasks on this new worker type to validate the new configuration and AMI
* [ ] Move that configuration to `servo-win2016`
* [ ] Remove the now-unused AMI (or should we keep it around for a while to allow reverting?)
* [ ] Land script changes

**Comment by SimonSapin** [comment]
*Sigh.* https://tools.taskcluster.net/aws-provisioner/servo-win2016-staging/resources shows instances being created, but https://tools.taskcluster.net/provisioners/aws-provisioner-v1/worker-types/servo-win2016-staging doesn’t show any worker and my test task stays pending.

Now generating another AMI with this section uncommented:

https://github.com/servo/servo/blob/19495a76e49f2bfde67b80ff7d104d8594377738/etc/taskcluster/windows/first-boot.ps1#L56-L66

… so that I can find out the instance’s IP address in order to RDP into it and get more information.

**Comment by petemoore** [comment]
In the worker type config I see:

```
        "signingKeyLocation": "C:\\generic-worker\\generic-worker-gpg-signing-key.key",
        "ed25519SigningKeyLocation": "C:\\generic-worker\\generic-worker-ed25519-signing-key.key",
```

The first one should be `openpgpSigningKeyLocation` not `signingKeyLocation`.

**Comment by SimonSapin** [comment]
Thanks!

To record IRC discussion, another thing missing was a Secret at https://tools.taskcluster.net/secrets/worker-type%3Aaws-provisioner-v1%2Fservo-win2016-staging

**Comment by SimonSapin** [comment]
Also, `--configure-for-aws` is not the default anymore:

* https://github.com/taskcluster/generic-worker/commit/2d99a0c153baf93b02611149b0950102a394e1aa
* https://bugzilla.mozilla.org/show_bug.cgi?id=1495435#c3

**Comment by petemoore** [comment]
I've updated https://github.com/taskcluster/generic-worker/#release-notes to be explicit about these changes, sorry about that.
