### ISSUE TITLE
Mach bootstrap does not support openSUSE

### ISSUE THREAD

**Issue by SuperRoboWizard** [servo/servo#22873]
Despite there being instructions in "Setting up your environment" for openSUSE, bootstrap.py raises an error. This appears to be a twofold issue: first, openSUSE is simply not in the internal list of supported distros, and second, the Python platform.getLinuxDistribution() function returns three empty strings.
```bash
tumbleweed@sp4 ~/D/servo-dev> ./mach bootstrap
Traceback (most recent call last):
  File "./mach", line 96, in <module>
    main(sys.argv)
  File "./mach", line 24, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/tumbleweed/Downloads/servo-dev/python/mach_bootstrap.py", line 239, in bootstrap_command_only
    bootstrap(context, force)
  File "/home/tumbleweed/Downloads/servo-dev/python/servo/bootstrap.py", line 407, in bootstrap
    distro, version = get_linux_distribution()
  File "/home/tumbleweed/Downloads/servo-dev/python/servo/bootstrap.py", line 395, in get_linux_distribution
    raise Exception('mach bootstrap does not support %s, please file a bug' % distro)
Exception: mach bootstrap does not support , please file a bug
tumbleweed@sp4 ~/D/servo-dev> python3
Python 3.7.2 (default, Dec 30 2018, 16:18:15) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.linux_distribution()
__main__:1: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
('', '', '')
>>>
```

**Comment by jdm** [comment]
Mach should be using python2 not python3.

**Comment by SuperRoboWizard** [comment]
Running platform.linux_distribution() does the same thing from the python2 shell--returns a tuple of 3 empty strings.

**Comment by jdm** [comment]
It's possible the solution here is using [the distro package](https://pypi.org/project/distro/) instead of `platform.linux_distribution()`.

**Comment by SuperRoboWizard** [comment]
I can confirm that this gives the proper information.
```
Name: openSUSE Tumbleweed
Version: 20190214 (n/a)
Codename: n/a
```

**Comment by marmeladema** [comment]
`mach` now uses the `distro` package instead of relying on `platform.linux_distribution()`.
I think this issue can be closed but feel free to confirm @SuperRoboWizard
