### ISSUE TITLE
Implement optional arguments for initEvent method of Event interface

### ISSUE THREAD

**Issue by jdm** [servo/servo#22883]
https://dom.spec.whatwg.org/#event has a `initEvent` method which we implement, but our implementation is missing the optional annotations and default values.

Code: `components/script/dom/webidls/Event.webidl`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/dom/event` and then [update the expected results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations).

**Comment by JesseBellingham** [comment]
Hi, first time open source contributor here, I was hoping to pick this one up?
@highfive: assign me

Possibly a stupid question, the properties marked as historical in the documentation, these are included as needing to be implemented for this issue?

**Comment by jdm** [comment]
Correct. They are artifacts of an earlier time before the web was standardized, and there are websites that still rely on them.

**Comment by JesseBellingham** [comment]
Unassign me from this issue please.

**Comment by ksqsf** [comment]
@highfive: assign me

I'd like to tackle this one. Is there only one file that needs to be modified? It seems that Web IDLs will be fed into codegen, so I'm not sure if I ever need to actually touch Rust code...
