### ISSUE TITLE
Use origin of source document for MessageEvent resulting from postMessage

### ISSUE THREAD

**Issue by jdm** [servo/servo#22888]
Right now `Window::post_message` passes `None` as the value that will initialize `MessageEvent.origin`. [The spec](https://html.spec.whatwg.org/multipage/comms.html#dom-messageevent-origin) says this should be the origin of the source document that posted the message instead. We will want to add a new origin argument to `Window::post_message`, and store the origin in `ScriptMsg::PostMessage` as well so the code path in `DissimilarOriginWindow::post_message` also works.

This should allow tests/wpt/web-platform-tests/dom/events/EventListener-incumbent-global-1.sub.html to make more progress.

Code: `components/script/dom/window.rs`, `components/script/dom/dissimilaroriginwindow.rs`, `components/script/script_thread.rs`, `components/script_traits/lib.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/dom/events/EventListener-incumbent-global-1.sub.html`

**Comment by EllaLiu5** [comment]
Assign this to me please.

**Comment by jdm** [comment]
@EllaLiu5 Have you made any progress? Do you have any questions?

**Comment by yashpatel5400** [comment]
I'd be interested in trying this out!

**Comment by jdm** [comment]
@yashpatel5400 Did you make any progress? Are you still working on this?

**Comment by mmiecz** [comment]
Hey, it appears that no one is working on this one. If that's ok I can look into this task.

**Comment by jdm** [comment]
Please do!

**Comment by jdm** [comment]
@mmiecz Have you made any progress on this?

**Comment by mmiecz** [comment]
Yes, the test is passing now, but I still have to clean up the code ( remove unwraps, etc. ). I will create PR soon, so you can make some comments, because I am not entirely sure about the solution.

**Comment by mmiecz** [comment]
Hi, I am having some hardware problems since I’ve upgraded recently and I can’t boot to Linux where I have my servo code :( I am trying to resolve this issue right no, sorry for the delay!

**Comment by mmiecz** [comment]
I've created a PR but I see it's already done?

**Comment by gterzian** [comment]
@mmiecz Yes you're right, this was already done in https://github.com/servo/servo/pull/23637, sorry I wasn't aware an issue was open for this. 

I think you could re-use some of what you've learned so far on this related issue: https://github.com/servo/servo/issues/24454

**Comment by jdm** [comment]
Closing since this was fixed by #23637.
