### ISSUE TITLE
Implement historical returnValue attribute for Event interface

### ISSUE THREAD

**Issue by jdm** [servo/servo#22881]
https://dom.spec.whatwg.org/#event has a `returnValue` attribute which we should implement. This requires following the [spec](https://dom.spec.whatwg.org/#dom-event-returnvalue) for setting and getting the value, which should affect the `canceled` member of Event.

Code: `components/script/dom/webidls/Event.webidl`, `components/script/dom/event.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/dom/event` and then [update the expected results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations).

**Comment by pngai** [comment]
@highfive: assign me
