### ISSUE TITLE
Implement historical srcElement attribute for Event interface

### ISSUE THREAD

**Issue by jdm** [servo/servo#22880]
https://dom.spec.whatwg.org/#event contains a `srcElement` attribute which should behave exactly the same as the `target` attribute per [the spec](https://dom.spec.whatwg.org/#dom-event-srcelement).

Code: `components/script/dom/webidls/Event.webidl`, `components/script/dom/event.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/dom/event` and then [update the expected results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations).

**Comment by drexler** [comment]
@highfive: assign me

**Comment by jdm** [comment]
The PR in #22918 is almost ready, it just needs to be rebased and have the test results updated.

**Comment by stephenmuss** [comment]
I'd be happy to pick this up and try to get it over the line.

**Comment by stephenmuss** [comment]
@highfive: assign me
