### ISSUE TITLE
Add "referrer" to fetch request used in navigation

### ISSUE THREAD

**Issue by gterzian** [servo/servo#22890]
It seems that the spec is moving towards integration of [navigation](https://html.spec.whatwg.org/#navigating-across-documents) with [Fetch](https://fetch.spec.whatwg.org), as exemplified by the aptly named [process a navigate fetch](https://html.spec.whatwg.org/#process-a-navigate-fetch) and [process a navigate response](https://html.spec.whatwg.org/#process-a-navigate-response).

For example:

- Step 12 of [following-hyperlinks](https://html.spec.whatwg.org/#following-hyperlinks-2) now refers not to a "resource", but to a fetch ["request"](https://fetch.spec.whatwg.org/#concept-request). 
- [Navigate](https://html.spec.whatwg.org/#navigate) now also uses the concept of a request. 
- [Window.open](https://html.spec.whatwg.org/#window-open-steps) now also refers to a  "request" in step 14. 

Our implementation of [follow-hyperlink](https://github.com/servo/servo/blob/65370f17c98225f7e71c72ea2e0cb2d0a81487f3/components/script/dom/htmlanchorelement.rs#L591), [window.open](https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/script/dom/windowproxy.rs#L385) and navigate all use [window.load_url](https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/script/dom/window.rs#L1714), as entry point, which sends a message to the script-thread handled in [`handle_navigate`](https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/script/script_thread.rs#L3116), which results in "parallel" steps being processes in the constellation. This ["load url"](https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/constellation/constellation.rs#L2210) algorithm is, as currently implemented, not integrated with our implementation of fetch, which lives somewhere around https://github.com/servo/servo/tree/65370f17c98225f7e71c72ea2e0cb2d0a81487f3/components/net/fetch.

There is already some plumbing to integrate the constellation with fetch, in the form of https://github.com/servo/servo/blob/master/components/constellation/network_listener.rs, which might be re-used to deal with "load_url" as well...

**Comment by jdm** [comment]
I'm not sure I understand what's being proposed here. The constellation is in charge of starting fetch requests for document navigations based on the script thread sending an InitiateNavigateRequest message, so it's not clear what we should be doing differently.

**Comment by gterzian** [comment]
I'm not completely sure myself, and it appeared to me that although there is perhaps a fetch request somewhere deep inside the navigation of a document, we could expose it more clearly in the script code. 

For example, I don't think we have a way to do `If subject's link types includes the noreferrer keyword, then set request's referrer to "no-referrer".` Step 13 of https://html.spec.whatwg.org/#following-hyperlinks-2 

Same with 14.3 of https://html.spec.whatwg.org/#window-open-steps

Those two examples I think would be relevant to comply with Step 7 of https://fetch.spec.whatwg.org/#concept-main-fetch

So the answer would be "expore the fetch request to script"?

**Comment by jdm** [comment]
Right, we should expose any required configuration as part of the InitiateNavigateRequest message, and make sure that configuration is passed along any intermediate messages.

**Comment by gterzian** [comment]
Removed the "interesting-project", since this turns out to be a much smaller change than I thought, doesn't mean it's not interesting though!

**Comment by miller-time** [comment]
@highfive assign me

**Comment by miller-time** [comment]
@gterzian (or maybe @jdm) any pointers to help me get started on this? I'm reading the methods that were mentioned above, but it's not entirely clear to me what needs to be changed.

It looks like the numbered steps (in comments) for [window.open](https://github.com/servo/servo/blob/b65828d909ec9ead7412fffdee2d07c285611a0a/components/script/dom/windowproxy.rs#L385) seem to be pretty outdated, so I could start there.

**Comment by gterzian** [comment]
@miller-time Thanks for working on this one!

Re the numbering, we've actually just merged https://github.com/servo/servo/pull/23011 which already improved the situation, and I suggest you rebase off the last master as a starting point(and not that the links to the code above in this issue will link to a older version of the codebase). 

The idea is that we want to add https://fetch.spec.whatwg.org/#concept-request-referrer to the various places in the code where we navigate using `window.load_url`. 

Currently `load_url` doesn't take a `referrer` argument, and neither does it pass it along to the "fetch" code actually doing the loading of the page that is being navigated to. 

I think the first step would be to add an argument representing `referrer` to `window.load_url` and do Step 14.3 of https://html.spec.whatwg.org/#window-open-steps as well as Step 13 of https://html.spec.whatwg.org/#following-hyperlinks-2

Then you could take it further by taking a look at the various places where `referrer` is used, and see if we are currently implementing those already and if so explore whether we can pass this new `referrer` info along to that piece of code and improve compliance with the spec. 

You might want to focus on a few low hanging fruits first, and perhaps open issues for things that could be best done separately.

To see the various places where `referrer` is used in the spec, you can click on the name in bold in the spec, which will give you a list of links to other places in the spec. 

![Screen Shot 2019-03-25 at 11 38 33 AM](https://user-images.githubusercontent.com/2792687/54893884-e571bf80-4ef2-11e9-8208-b43329c4519d.png)

**Comment by miller-time** [comment]
@gterzian thanks for the additional tips!

I opened a draft PR, I hope that's okay... thought it might be helpful to see where I'm going.

> Then you could take it further by taking a look at the various places where `referrer` is used, and see if we are currently implementing those already and if so explore whether we can pass this new `referrer` info along to that piece of code and improve compliance with the spec.

> Note that this is the "fetch" spec, which is separate from the "html" spec, and fetch is mostly implemented in https://github.com/servo/servo/tree/master/components/net
> and to understand how something would travel from `window.load_url` to fetch, you'de have to follow the message send to the [constellation](https://github.com/servo/servo/blob/master/components/constellation/constellation.rs) and see how the handling of that message results in starting a fetch.

I looked at InitiateNavigateRequest, per advice of @jdm, and saw that in [constellation](https://github.com/servo/servo/blob/master/components/constellation/constellation.rs#L1231) we handle that message, which passes a req_init (RequestInit).

In [Request.from_init](https://github.com/servo/servo/blob/master/components/net_traits/request.rs#L315) we do the following:

```rust
req.referrer = if let Some(url) = init.referrer_url {
    Referrer::ReferrerUrl(url)
} else {
    Referrer::NoReferrer
};
```

So I think that will need to be changed as part of my efforts.

I skimmed the definition of [window.load_url](https://github.com/servo/servo/blob/master/components/script/dom/window.rs#L1782) and came across a MainThreadScriptMsg::Navigate message that is sent, which passes a LoadData struct. I might be able to add referrer to that. I tried to follow that message's usage, but I got to a scheduler and wasn't sure what happens next.

I was hoping that the MainThreadScriptMsg::Navigate message results in a ScriptMsg::InitiateNavigateRequest message being sent eventually. If so, then this all ties together there.

There are a lot of other uses of RequestInit, and I feel like I'm still missing... a lot.

> To see the various places where `referrer` is used in the spec, you can click on the name in bold in the spec, which will give you a list of links to other places in the spec.

That's good to know! I'll definitely do that next.

**Comment by gterzian** [comment]
Ok, sounds like you're going in the right direction. 

The `Navigate` msg is received here: https://github.com/servo/servo/blob/7a67443fcb4eea1919ed77c302e25c3052c23721/components/script/script_thread.rs#L1743

and handled as part of https://github.com/servo/servo/blob/7a67443fcb4eea1919ed77c302e25c3052c23721/components/script/script_thread.rs#L3198

I think it's the `ScriptMsg::LoadUrl` you're looking for.

**Comment by miller-time** [comment]
Thanks @gterzian 

I updated my PR - got it to build, cleaned it up. Tests pass and I haven't touched them yet... Is that good or bad?

------

I've been browsing the fetch spec...

* In the [Request](https://fetch.spec.whatwg.org/#request-class) class, there is some mention of different values for referrer:
> Returns the referrer of request. Its value can be a same-origin URL if explicitly set in init, the empty string to indicate no referrer, and "about:client" when defaulting to the global’s default. This is used during fetching to determine the value of the `Referer` header of the request being made. 

I can only find one occurrence of "about:client": 

https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/script/dom/request.rs#L554

Side note: should the branch `NoReferrer => String::from("no-referrer")` be changed to return `String::from("")`?

* The main_fetch is a little sparse, and has a TODO for handling the client's referrer policy:

https://github.com/servo/servo/blob/7a67443fcb4eea1919ed77c302e25c3052c23721/components/net/fetch/methods.rs#L142

Per the [spec](https://fetch.spec.whatwg.org/#main-fetch) it looks like I could do [some work](https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer) there. 

* In http_network_or_cache_fetch:

https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/net/http_loader.rs#L774

It looks like referrer is being handled correctly, though the numbering in comments seems slightly out-of-date per the [spec](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch). Should I try to update that?

* In cors_preflight_fetch:

https://github.com/servo/servo/blob/master/components/net/http_loader.rs#L1359

It looks like we're [correctly](https://fetch.spec.whatwg.org/#cors-preflight-fetch) copying the referrer from the request. 🎉 

* I'm not sure where to look for the implementation of the [WebSocket opening handshake](https://fetch.spec.whatwg.org/#websocket-opening-handshake)...

------

I found several TODO comments when I added an `Option<Referrer>` to `LoadData`:

https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/constellation/constellation.rs#L1951

https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/constellation/constellation.rs#L2033

https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/constellation/constellation.rs#L2095

I could use some guidance in case those should have logic for determining referrer... (on my branch, I have it set to `None` in all of those places).

------

One last question...

Should existing references to `RequestInit.referrer_url` (which is `Option<ServoUrl>`) be migrated to `RequestInit.referrer` as `Referrer::ReferrerUrl(ServoUrl)` and `RequestInit.referrer_url` removed?

**Comment by gterzian** [comment]
Thanks for all the research!

Note that `servo/components/script/dom/request.rs` is the DOM interface to a fetch request, so it's basically the DOM api to some of the things that are done "internally" as part of navigation that follows `window.load_url`. Thanks for pointing out that one, I actually wasn't aware of it yet.

>Side note: should the branch NoReferrer => String::from("no-referrer") be changed to return String::from("")?

The spec seems to indeed point in that direction. Good catch!

I think the `enum` that is quite important for your work is this one: https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/net_traits/request.rs#L65

It is used in the fetch code, as well as in the DOM request. 

Currently it looks like the `referrer` is set based on the `referrer_url` at https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/net_traits/request.rs#L315

> Should existing references to RequestInit.referrer_url (which is Option<ServoUrl>) be migrated to RequestInit.referrer as Referrer::ReferrerUrl(ServoUrl) and RequestInit.referrer_url removed? 

Yes you might want to try that and see what other parts of the code are using it and it if it can be changes relatively easily. It would seem to make sense to just do everything with the referrer. 

> though the numbering in comments seems slightly out-of-date per the spec. Should I try to update that?

Yes that's a good idea. You could try to separate it from the referrer work either by commit or by PR. I would like just adding a separate commit to the PR should be fine. 

For the websocket I think you will have to look at https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/script/dom/websocket.rs#L145

Note that the spec seems to say that the referrer should be `no-referrer` by default. 


Re the TODO's in the constellation that you've found:

- https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/constellation/constellation.rs#L2081 This relates to Step 14.3 of https://html.spec.whatwg.org/multipage/window-object.html#window-open-steps
- The two others relate to navigating and/or creating a iframe that is initially "about:blank", those operations originate at https://github.com/servo/servo/blob/25aa6501d2a65052704d408b77fad16a4518acce/components/script/dom/htmliframeelement.rs#L176 instead of `window.load_url` for "normal" navigation. It's worth looking into plugging the refferer into two workflows as well, and it might be something best done in a follow-up. 

> I updated my PR - got it to build, cleaned it up. Tests pass and I haven't touched them yet... Is that good or bad? 

I think we should expect some tests to unexpectedly for from `FAIL` to `PASS`, and we can look into that. Have you opened the PR on here already?

**Comment by miller-time** [comment]
Yep, sorry I thought you had seen it auto linked by GH

https://github.com/servo/servo/issues/23090

**Comment by miller-time** [comment]
**Updates**

> > Should existing references to RequestInit.referrer_url (which is Option) be migrated to RequestInit.referrer as Referrer::ReferrerUrl(ServoUrl) and RequestInit.referrer_url removed?
> 
> Yes you might want to try that and see what other parts of the code are using it and it if it can be changes relatively easily. It would seem to make sense to just do everything with the referrer.

[done](https://github.com/servo/servo/blob/e98db925d11dc0c3e8b649a9a16513fad699593a/components/net_traits/request.rs#L166)!

> > Side note: should the branch NoReferrer => String::from("no-referrer") be changed to return String::from("")?
> 
> The spec seems to indeed point in that direction. Good catch!

[fixed](https://github.com/servo/servo/blob/e98db925d11dc0c3e8b649a9a16513fad699593a/components/script/dom/request.rs#L557)!

> > though the numbering in comments seems slightly out-of-date per the spec. Should I try to update that?
> 
> Yes that's a good idea. You could try to separate it from the referrer work either by commit or by PR. I think that just adding a separate commit to the PR should be fine.

[fixed](https://github.com/servo/servo/blob/e98db925d11dc0c3e8b649a9a16513fad699593a/components/net/http_loader.rs#L774)!

> Note that the spec seems to say that the referrer should be no-referrer by default.

[done](https://github.com/servo/servo/blob/e98db925d11dc0c3e8b649a9a16513fad699593a/components/script/dom/websocket.rs#L208) (I think)

------

The last thing I wanted to do before requesting a review of the PR is:

> The main_fetch is a little sparse, and has a TODO for handling the client's referrer policy:
> https://github.com/servo/servo/blob/7a67443fcb4eea1919ed77c302e25c3052c23721/components/net/fetch/methods.rs#L142
> Per the [spec](https://fetch.spec.whatwg.org/#main-fetch) it looks like I could do [some work](https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer) there.

I still haven't updated any tests... or seen any test failures...

**Comment by miller-time** [comment]
By the way, figuring out exactly how the steps have changed in the spec for `http_network_or_cache_fetch` was a fun exercise. I tracked down https://github.com/servo/servo/commit/d919f55884 which told me roughly when a lot of that numbering had been written (~2 years ago), which I used to line up commit timestamps with https://github.com/whatwg/fetch/commit/cbca2c2 (my main clue that things were significantly out of date was that the referrer has been handled in step 9 for a long time, but the comment was `// Step 10`). I cloned that repo and opened fetch.bs in my browser so I could see which steps the comments were referencing (with numbers instead of just `<li>` tags).

**Comment by miller-time** [comment]
Hmm in looking at main_fetch again:

https://github.com/servo/servo/blob/e98db925d11dc0c3e8b649a9a16513fad699593a/components/net/fetch/methods.rs#L185

...I'm not sure if it makes sense to change anything in this PR.

**Comment by gterzian** [comment]
Thanks for the work! 

Just looking at fetch/method, I saw this FIXME at https://github.com/servo/servo/blob/fe07d2c575c797ad2ee88422adacea7806f5c5a1/components/net/fetch/methods.rs#L194

which points to this issue https://github.com/servo/servo/issues/14507

it's interesting because it would appear that in the case of `Referrer::Client` we might actually need to do some additional processing inside `script` and set it either to `noreferrer` or a url before sending it on to `net`(fetch)...

I'm still looking at the overall PR and haven't had a chance to review everything, and I can't suggest exactly what to do re the above. I'll keep looking into over the next couple of days, and perhaps you can too when you have a chance?

Re the tests, it might actually be that there are no tests yet for this specifically, we'll have to look into it a bit more as well...

**Comment by miller-time** [comment]
> which points to this issue #14507

nice! that issue links to the [exact same part of the spec](https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer) that I mentioned in a [previous comment](https://github.com/servo/servo/issues/22890#issuecomment-476451873). I hadn't paid close enough attention to that comment and noticed that there was a separate issue to handle that.

I'll start to poke around in the tests, but I'm actually not familiar with them at all... Any pointers for where to look?

**Comment by miller-time** [comment]
I tried running `./mach test-wpt --release` and then `./mach update-wpt` and it produced a lot of changes, including a lot of new failures. So I might need to investigate those further. For some reason I thought CI runs those tests, but it looks like it only runs `./mach test-unit`

**Comment by gterzian** [comment]
Re the tests, I think we can find relevant ones in https://github.com/servo/servo/tree/ab5a57fadf649ede43ae3f478be6df9bfa69893a/tests/wpt/web-platform-tests/referrer-policy

Re running the tests, when you run the whole suite locally you usually get a lot of timeout errors, so it's best to target a specific folder, or a single test. 

I'll run the suite on your PR via a dedicated command, to give us an indication if anything changed or not. Note that even then there can be quite a few unrelated failures occurring intermittently.

**Comment by miller-time** [comment]
@gterzian thanks! I'm starting to drill into these wpt tests. I think I found one [unexpected passing test](https://github.com/miller-time/servo/blob/master/tests/wpt/web-platform-tests/fetch/api/request/request-init-001.sub.html) already. I found a [failing test](https://github.com/miller-time/servo/blob/master/tests/wpt/web-platform-tests/referrer-policy/no-referrer-when-downgrade/attr-referrer/cross-origin/http-http/iframe-tag/keep-origin-redirect/insecure-protocol.http.html), but when I checked out master and ran:

```
./mach build --release
./mach test-wpt --release tests/wpt/web-platform-tests/referrer-policy/no-referrer-when-downgrade/attr-referrer/cross-origin/http-http/iframe-tag/keep-origin-redirect/insecure-protocol.http.html
```

...it failed there too. Just to make sure I'm on the right track... I assume I should at least run `update-wpt` on the one that is now passing; should I also update the one that's failing on master?

**Comment by gterzian** [comment]
So locally if you run a single test, you'll see the result, but not whether it's unexpected or not. However when you run say `./mach test-wpt --release tests/wpt/web-platform-tests/referrer-policy/`, it will tell you what is expected or unexpected. 

So for example the one that you found that is failing on master is probably expected to fail(you'll know if you run the entire folder). 

It appears that a lot of tests went from `PASS` to `FAIL`, in the `refferer-policy` folder, while I can also see a few going from `FAIL` to `PASS`. Looks like most failure related to the referrer being undefined. 

See  https://build.servo.org/builders/linux-rel-css/builds/11899/steps/shell__4/logs/filtered-wpt-errorsummary.log

**Comment by jdm** [comment]
Running a single rest does tell you whether it's unexpected or not. It just may not be clear if it's passing or not from the output, but that's separate from expected/unexpected.

**Comment by miller-time** [comment]
I tried changing the default from `Referrer::Client` to `Referrer::NoReferrer`.

```
$ ./mach test-wpt --release tests/wpt/web-platform-tests/referrer-policy/
...
234 tests had unexpected subtest results
```

Note: I switched to master again and ran `./mach build --release` and then those referrer-policy tests, and they all ran as expected. So I guess I need to keep trying to figure these out.

Sorry I haven't made much progress on this, I'll keep digging. Should I ping anyone on the pull request? To get any additional feedback, etc. Or do I need to finish up these wpt tests before the review? Just curious (this is only my second one).

**Comment by gterzian** [comment]
Yep so it's the `234 tests had unexpected subtest results` part that would need looking into(and indeed running the tests on master should not have unexpected test results). 

It is indeed better to try to first find out what is causing the unexpected test failures, before asking for a review(I've looked at your work and it's not obvious what is wrong from that). 

I can suggest picking a test that currently unexpectedly fails(they seem to all fail in fairly similar ways), and then adding print statements in the rust code and `console.log` in the JS, and trying to understand what is going on. If you run a single test you can see both the rust print and the js console output. 

Even though a lot of tests are failing unexpectedly, I suspect they all fail for the same reason and it could be a fairly easy fix that will become obvious once you've printed out the various state of the `referrer` at various point...

**Comment by jdm** [comment]
It may be easier to write your own manual tests first, using a script like [this](https://gist.github.com/phrawzty/62540f146ee5e74ea1ab) to print out the received referrer. This should be easier to determine if the problem lies in providing an accurate referrer, or if the problem lies in the code that acts on the requested referrer policy.

**Comment by miller-time** [comment]
So it turns out that having a bunch of small commits ended up being very helpful. By running the tests after each commit I discovered that ebb2ddf introduced all of the failures. I mishandled a lot of uses of LoadData that had a referrer_url set. I added a `None` referrer in several places and caused referrer_url to no longer be used. After fixing this, all of the referrer wpt tests passed!

**Comment by miller-time** [comment]
I've been looking into those last 3 [failing tests](https://build.servo.org/builders/linux-rel-css/builds/11965/steps/shell__4/logs/filtered-wpt-errorsummary.log).

When I changed [this line](https://github.com/servo/servo/pull/23090/commits/9eba56d15c6d2c2c3e6d9ebbcdb102df76383fb9#diff-ffcaa7c334fe34498bc7362e376be445R1786) the referrer changed from `Some(Referrer::ReferrerUrl(doc.url()))` to `None`.

In the test
> /html/browsers/history/the-history-interface/009.html

it appears that `Window::load_url` was called from `SetHref` (location.rs), which passes `None` for referrer.

https://github.com/servo/servo/blob/7726453eff252eef120eab0b6489c6f5c19a4779/components/script/dom/location.rs#L171

I think I have 2 options to fix this test:
* In `Window::load_url`, pass `Some(Referrer::ReferrerUrl(doc.url()))` if `referrer` is `None`
* Pass a referrer from the caller (location.rs)

I've poked a bit in the spec for location:
* https://html.spec.whatwg.org/multipage/history.html#location-object-setter-navigate ->
* https://html.spec.whatwg.org/multipage/history.html#location-object-navigate ->
* https://html.spec.whatwg.org/multipage/browsing-the-web.html#navigate

> If request is non-null, then set document's referrer to the serialization of request's referrer, if request's referrer is a URL record, and the empty string otherwise.
> Note: Per Fetch a request's referrer will be either a URL record or "no-referrer" at this point.

It's not clear to me how we would add a referrer in `SetHref` (location.rs), so for now I'm going with option (a) above.

All tests should pass now.
