### ISSUE TITLE
Use a smarter strategy to speed up text run shaping

### ISSUE THREAD

**Issue by burg** [servo/servo#229]
Gecko, for example, caches shaping results on a per-word basis and then copies the words into a glyph store when shaping is requested. The cache is stored with `gfx::Font` instances (i.e., tied to a particular size).

This caching reduces the size of inputs and outputs to harfbuzz, and reduces the number of shaping calls. In gecko this mainly is useful for scaling shaping with the number of unique words; in Servo it would be even more useful while we are still doing non-incremental layout (shaping entire text run over and over).

**Comment by mbrubeck** [comment]
Servo now caches shaping results per word.
