### ISSUE TITLE
Problem with mac installation

### ISSUE THREAD

**Issue by joe9111** [servo/servo#22905]
There seems to be a problem with the brew install statement:
```
$ brew bundle install --file=etc/taskcluster/macos/Brewfile
Error: No Brewfile found
```

**Comment by jdm** [comment]
That command needs to be run from the root of the Servo repository.

**Comment by learning** [comment]
@joe9111 
```
$ git clone git@github.com:servo/servo.git
$ cd servo
$ brew bundle install --file=etc/taskcluster/macos/Brewfile
```

**Comment by jsjoeio** [comment]
I ran into this issue as well. It's not very clear from the instructions that you are to do this after cloning the repo. We should update the set up instructions.

**Comment by shainamainar** [comment]
Hi, I have recently ran into this error as well, with a different error message. 
`brew bundle install --file=etc/taskcluster/macos/Brewfile`

```
Traceback (most recent call last):
        3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in '<main>'
	2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in 'require_relative'
	1: from /usr/local/Homebrew/Library/Homebrew/global.rb:12:in '<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:12:in 'require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
```

**Comment by jdm** [comment]
That sounds like https://github.com/Homebrew/homebrew-core/issues/37269. Try running `brew update-reset` like https://github.com/Homebrew/brew/issues/6565#issuecomment-561278838 suggests?

**Comment by shainamainar** [comment]
Great, that worked for me. Thanks!
