### ISSUE TITLE
Xlib:  extension "GLX" missing on display ":1".

### ISSUE THREAD

**Issue by aurora-of-earth** [servo/servo#22908]
Servo not working on Debian 10 Linux with the following error:

<pre>
Xlib:  extension "GLX" missing on display ":1".
Failed to create window.: OsError("`glXQueryExtensionsString` found no glX extensions") (thread main, at src/libcore/result.rs:997)
</pre>

**Comment by paulrouget** [comment]
Which graphic card do you use?

Which driver?

See which glx module is loaded in the Xorg logs (`grep glx /var/log/Xorg.0.log`).

**Comment by aurora-of-earth** [comment]
@paulrouget Output of <code>grep glx /var/log/Xorg.0.log</code>:

<pre>
[   216.344] (II) LoadModule: "glx"
[   216.518] (II) Loading /usr/lib/xorg/modules/linux/libglx.so
[   218.556] (II) Module glx: vendor="NVIDIA Corporation"
</pre>

- The graphics card is <b>Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)</b>

**Comment by paulrouget** [comment]
Does it work if you use the intel GPU (not the nvidia one) or if you use the nouveau driver?

**Comment by aurora-of-earth** [comment]
@paulrouget That's the output of the xorg.conf:
<pre>
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod" "sna"
   Option      "TearFree" "true"
EndSection
</pre>


I'm using the intel drivers, but I think the system is using the nvidia drivers.
The nouveau driver is also in use.
WebGL is not working on the machine and I don't understand why.

**Comment by paulrouget** [comment]
> I'm using the intel drivers, but I think the system is using the nvidia drivers

Something is misconfigured in your system. You probably have 2 GPUs and it's not using the one you think.

If it's using the intel GPU + intel driver, you should not have any problem.

If it's using the Nvidia GPU + Nvidia driver, try to switch to Nouveau see if it works.

**Comment by aurora-of-earth** [comment]
@paulrouget Sorry it was because of NVIDIA drivers interfering with intel ones.
I've fixed the problem with WebGL and servo is working.
