### ISSUE TITLE
Make window.name deal with lack of browsing context

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#22915]
whatwg/html#4366
web-platform-tests/wpt#15391

**Comment by tigercosmos** [comment]
so, seems that we need to pass this one  `servo/tests/wpt/web-platform-tests/html/browsers/the-window-object/name-attribute.window.js`
relevant code maybe here
https://github.com/servo/servo/blob/c12e341c0ce9fcd8c3f71905b9b379af802bff04/components/script/dom/htmliframeelement.rs#L484

any ideas? @CYBAI 
or I am going to pick this one

**Comment by CYBAI** [comment]
@tigercosmos Yes, as mentioned in description, the test is `html/browsers/the-window-object/name-attribute.window.js` which is added in web-platform-tests/wpt#15391.

About relevant code, as you can read from the spec update PR, the change is about `window.name`.

They're defined here

https://github.com/servo/servo/blob/7a67443fcb4eea1919ed77c302e25c3052c23721/components/script/dom/window.rs#L1156-L1164

and call the methods from `windowproxy.rs`

https://github.com/servo/servo/blob/7a67443fcb4eea1919ed77c302e25c3052c23721/components/script/dom/windowproxy.rs#L593-L599

So, you'd want to update the code here in `windowproxy`.

Go ahead!
