### ISSUE TITLE
Make media tracks aware of their associated track list

### ISSUE THREAD

**Issue by jdm** [servo/servo#22912]
Per https://github.com/servo/servo/pull/22622#discussion_r256922081 the AudioTrack, VideoTrack, and TextTrack interfaces will need to store a member pointing at the track list object that they are associated with. This will look something like `DomRefCell<Option<Dom<AudioTrackList>>>` and it will be updated when the track object is added to a list or removed from one.

Code: `components/script/dom/audiotrack.rs`, `components/script/dom/videotrack.rs`, `components/texttrack.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/track/track-element/`

**Comment by jdm** [comment]
@moonlightdrive This might be a good first issue!

**Comment by moonlightdrive** [comment]
Thanks @jdm! I'll take a look at this one

**Comment by kunalmohan** [comment]
Okay. I'll start working on this issue.

**Comment by kunalmohan** [comment]
I am a bit confused here so I just want to confirm I am thinking in the right direction here. I will have to update the `track_list` member of `struct AudioTrack` in this function, right?
https://github.com/servo/servo/blob/bac9903fbeed0a394a86c0091e727aada665433d/components/script/dom/audiotracklist.rs#L105-L107

I don't see any function that removes a track from a tracklist, so what about updating it during removal of track object?

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/bac9903fbeed0a394a86c0091e727aada665433d/components/script/dom/audiotracklist.rs#L109-L111 removes all tracks from a track list.

Also, as part of this work we should implement the setting behaviour from https://html.spec.whatwg.org/multipage/media.html#dom-videotrack-selected, which is the motivation for this issue.

**Comment by jdm** [comment]
And to explicitly answer your question: yes.

**Comment by kunalmohan** [comment]
texttracklist.rs does not have a clear() function, but has the following function:
https://github.com/servo/servo/blob/bb5cd02da30fe8ef4dcdea5cca17667cd4ac6cdb/components/script/dom/texttracklist.rs#L100-L109
Is there a need for clear() function here or should I proceed with the current code?

**Comment by kunalmohan** [comment]
> Also, as part of this work we should implement the setting behaviour from https://html.spec.whatwg.org/multipage/media.html#dom-videotrack-selected, which is the motivation for this issue.

I think the setting behaviour is already implemented here.
https://github.com/servo/servo/blob/bb5cd02da30fe8ef4dcdea5cca17667cd4ac6cdb/components/script/dom/videotracklist.rs#L73-L107
Or is there something that need to be implemented yet?

Sorry for troubling you with so many questions :sweat_smile: . Being a beginner at rust and web-platforms, I am still trying to understand the concepts implemented here.

Thanks for the help :smile:

**Comment by jdm** [comment]
The setting that I was describing is implemented in https://github.com/servo/servo/blob/bb5cd02da30fe8ef4dcdea5cca17667cd4ac6cdb/components/script/dom/videotrack.rs#L104-L112. This would not match the specification if the video track list was cleared, and then some JS invoked the selected setter on a video track that was cleared. Does that make sense?

**Comment by kunalmohan** [comment]
Yeah, that makes sense. So, on clearing a tracklist member I have updated the `track_list` member of each associated track to `None`. I think that should solve it.

**Comment by kunalmohan** [comment]
> texttracklist.rs does not have a clear() function, but has the following function:
> https://github.com/servo/servo/blob/bb5cd02da30fe8ef4dcdea5cca17667cd4ac6cdb/components/script/dom/texttracklist.rs#L100-L109
> 
> 
> Is there a need for clear() function here or should I proceed with the current code?

What about this?

**Comment by jdm** [comment]
The `remove` method isn't used yet, but it would be nice to add the same support for updating the removed track's associated list.
