### ISSUE TITLE
Use new GL-based video playback

### ISSUE THREAD

**Issue by jdm** [servo/servo#22920]
In answer to @ceyusa in https://mozilla.logbot.info/servo/20190221#c15994865-c15994866:
* obtain the relevant glutin data inside ports/servo/glutin_app
* add an API to [WindowMethods](https://github.com/servo/servo/blob/0dda1156094dae5ff47ab6fcf316cdc5547fff4c/components/compositing/windowing.rs#L130) to receive that data
* add the required data to [InitialPipelineState](https://github.com/servo/servo/blob/0dda1156094dae5ff47ab6fcf316cdc5547fff4c/components/constellation/pipeline.rs#L98)
* add the required data to Constellation so it can be added to the pipeline state
* add the required data to ScriptThreadFactory's [InitialScriptState](https://github.com/servo/servo/blob/0dda1156094dae5ff47ab6fcf316cdc5547fff4c/components/script_traits/lib.rs#L548)
* add the data to Window, so it can be obtained by HTMLMediaElement when necessary
* store the data in script's ScriptThread so it can be passed to the Window constructor

**Comment by ceyusa** [comment]
thanks!
