### ISSUE TITLE
Repacked gstreamer link for windows is broken

### ISSUE THREAD

**Issue by jdm** [servo/servo#22946]
https://queue.taskcluster.net/v1/task/KAzPF1ZYSFmg2BQKLt0LwA/runs/0/artifacts/public/repacked.zip from https://github.com/servo/servo/blob/3d32efad2a804403dc0b953cb0c42ce3d40367c1/etc/taskcluster/windows/bootstrap.ps1#L53

cc @SimonSapin

**Comment by SimonSapin** [comment]
Yes, these artifacts are kept for something like a month. Tasks that use them should re-created them as needed. `bootstrap.ps1` is only to help more quickly get a working environment to compile when manually starting up an AWS instance. It’s `first-boot.ps1` that is used when creating a new AMI.

The latest "version" of repacked `gstreamer-1.0-x86_64-1.14.3.msi` should always be at https://tools.taskcluster.net/index/project.servo.servo.repacked-msi/f4f20c713766ed6718b914b9ae57ed993a59ffe194e6ef530c8547508b4484d8, based on:

https://github.com/servo/servo/blob/fd07be1cefa7c96ec15bcb16e21dbb0558627d3d/etc/taskcluster/decisionlib.py#L519

and:

https://github.com/servo/servo/blob/fd07be1cefa7c96ec15bcb16e21dbb0558627d3d/etc/taskcluster/decision_task.py#L569
