### ISSUE TITLE
Servo should link against the correct version of gstreamer

### ISSUE THREAD

**Issue by robert-snakard** [servo/servo#22947]
On Ubuntu 16.04 servo builds against the global gstreamer library in `/usr/lib` rather than the version in `support/linux/gstreamer`. It should use Servo's version. See [the](https://github.com/servo/servo/issues/21970) comment here

**Comment by jdm** [comment]
I wonder if we're not setting up the pkg-config environment correctly?

**Comment by jdm** [comment]
In theory this is supposed to be taken care of by https://github.com/servo/servo/blob/fd07be1cefa7c96ec15bcb16e21dbb0558627d3d/python/servo/command_base.py#L612-L620.

**Comment by jdm** [comment]
@robert-snakard What does you PKG_CONFIG_PATH look like normally? It looks like we're appending to it, so if the system gstreamer was already present the local one wouldn't be selected.

**Comment by robert-snakard** [comment]
@jdm I don't think it's ever set. Unless I'm checking it wrong

```
user@0f734da98db5:~/servo (issue_22843) $ echo $PKG_CONFIG_PATH

user@0f734da98db5:~/servo (issue_22843) $ ./mach build -d
    Finished dev [unoptimized + debuginfo] target(s) in 1.36s
Build Completed in 0:00:01
user@0f734da98db5:~/servo (issue_22843) $ ./mach bootstrap-gstreamer
gstreamer is already set up
user@0f734da98db5:~/servo (issue_22843) $ echo $PKG_CONFIG_PATH

user@0f734da98db5:~/servo (issue_22843) $
```

**Comment by mrobinson** [comment]
16.04 is already at the end of life and this code has changed quite a bit, so I'm going to close this one.
