### ISSUE TITLE
Decouple font backend away from Halfbuzz, to support future rust-only backends

### ISSUE THREAD

**Issue by twitchyliquid64** [servo/servo#22959]
As it stands, the font/text/glyph subsystems are somewhat coupled to the Halfbuzz crate. Decoupling this into some abstraction would allow use of a crate like RustType, which implements font parsing entirely in Rust.

Given the attacker-controlled nature of fonts + text, using a pure rust backend would yield large security gains.

Unfortunately, RustType is no where near as feature-complete as Halfbuzz, so its RustType in its current form is not a drop in replacement. Rather, it would be nice to swap out the font system when embedding Rust in various security-critical applications (where the lack of feature parity is acceptable).

Thoughts?

**Comment by SimonSapin** [comment]
As far as I understand RustType positions glyphs by merely moving a cursor by each glyph’s advance width. It is not a replacement for HarfBuzz which does (complex) shaping.

We are however planning to move from using HarfBuzz directly to using Skribo, a project that is just getting started but will let us switch to a Rust-based shaper if and when one emerges. See https://github.com/linebender/skribo and https://raphlinus.github.io/rust/skribo/text/2019/02/27/text-layout-kickoff.html

CC @raphlinus, @pcwalton

**Comment by raphlinus** [comment]
There are a couple of developments that I think are encouraging in this space. One is [this comment](https://www.reddit.com/r/rust/comments/avjjxw/low_level_text_layout_skribo_kickoff/ehi7975/) from the Reddit thread on the skribo kickoff. It has a gist of code that doesn't do full complex script shaping but does more sophisticated positioning than rusttype does now. As I responded, I'd be quite open to that being part of skribo, so it's an option (feature-gated) for those use cases.

Second, the YesLogic people are working on a Rust native shaping engine that should actually satisfy all requirements. It's early days for it, but I'm hopeful; the team has a good track record shipping high quality text implementations.

**Comment by twitchyliquid64** [comment]
SGTM, sounds like skribo is the way to go here.

I'll add that RustType has glyph-pair kerning as well, which fwict is sufficient for Latin LTR text?

**Comment by raphlinus** [comment]
RustType (through stb_truetype-rs) only has support for the basically-obsolete `kern` table. The code snippet linked above actually handles the newer `gpos` as well. In other words, RustType is not really adequate even for Latin script, but I can see how to put together a pretty good solution for it. Ideally you'll have gsub as well for ligatures (completely missing from RustType).
