### ISSUE TITLE
Use Pathfinder for 2d canvas rendering

### ISSUE THREAD

**Issue by jdm** [servo/servo#22957]
Right now our 2d canvas rendering relies on a very old fork of Azure (https://github.com/servo/rust-azure/), which itself relies upon a _very_ old fork of Skia (https://github.com/servo/rust-azure/). The operations that the 2d canvas allows are not complicated and it should be possible to use [Pathfinder](https://github.com/pcwalton/pathfinder/) as the rendering backend instead. This would have several useful results:
* it would remove multiple large C++ codebases from Servo's dependency tree
* it would exercise Pathfinder in a real product
* it would give us hardware acceleration instead of the current software rendering

I'm marking this as "hard" not because I actually believe it will be _hard_, per se, but it's going to require a bunch of investigation and poking and prodding to understand how to fit Pathfinder into Servo's canvas rendering pipeline. It could be fun, though!

**Comment by jdm** [comment]
Note: this work should rely on the [Pathfinder 3 branch](https://github.com/pcwalton/pathfinder/tree/pf3) rather than the master branch (until pf3 merges into master).

**Comment by shanavas786** [comment]
@highfive assign me

**Comment by shanavas786** [comment]
After adding `pathfinder_gl = {git = "https://github.com/pcwalton/pathfinder", branch = "pf3"}` to `Cargo.toml` for canvas, `match build -d` fails.

```
    Updating git repository `https://github.com/pcwalton/pathfinder`
    Updating crates.io index
   Compiling png v0.14.0
   Compiling gl v0.6.5
   Compiling mozjs_sys v0.61.6
   Compiling rust-webvr v0.10.2
error[E0599]: no function or associated item named `huffman_only` found for type `encoder::deflate::CompressionOptions` in the current scope
   --> /home/sinergia/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.14.0/src/common.rs:159:66
    |
159 |             Compression::Huffman => deflate::CompressionOptions::huffman_only(),
    |                                     -----------------------------^^^^^^^^^^^^
    |                                     |
    |                                     function or associated item not found in `encoder::deflate::CompressionOptions`

error[E0599]: no function or associated item named `rle` found for type `encoder::deflate::CompressionOptions` in the current scope
   --> /home/sinergia/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.14.0/src/common.rs:160:62
    |
160 |             Compression::Rle => deflate::CompressionOptions::rle(),
    |                                 -----------------------------^^^
    |                                 |
    |                                 function or associated item not found in `encoder::deflate::CompressionOptions`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `png`.
warning: build failed, waiting for other jobs to finish...
```
But cargo successfully builds `pf3` branch in `pathfinder` repo with the same toolchain.

Am i missing something ?

**Comment by jdm** [comment]
Try runny ng `cargo update -p png`?

**Comment by shanavas786** [comment]
it didn't help

```
sinergia@sinergia:~/foss/servo$ cargo update -p png
error: There are multiple `png` packages in your project, and the specification `png` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  png:0.12.0
  png:0.14.0
sinergia@sinergia:~/foss/servo$ cargo update -p png:0.12.0
    Updating crates.io index
sinergia@sinergia:~/foss/servo$ cargo update -p png:0.14.0
    Updating crates.io index
sinergia@sinergia:~/foss/servo$ ./mach build -d
   Compiling png v0.14.0
   Compiling mozjs_sys v0.61.6
error[E0599]: no function or associated item named `huffman_only` found for type `encoder::deflate::CompressionOptions` in the current scope
   --> /home/sinergia/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.14.0/src/common.rs:159:66
    |
159 |             Compression::Huffman => deflate::CompressionOptions::huffman_only(),
    |                                     -----------------------------^^^^^^^^^^^^
    |                                     |
    |                                     function or associated item not found in `encoder::deflate::CompressionOptions`

error[E0599]: no function or associated item named `rle` found for type `encoder::deflate::CompressionOptions` in the current scope
   --> /home/sinergia/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.14.0/src/common.rs:160:62
    |
160 |             Compression::Rle => deflate::CompressionOptions::rle(),
    |                                 -----------------------------^^^
    |                                 |
    |                                 function or associated item not found in `encoder::deflate::CompressionOptions`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `png`.
warning: build failed, waiting for other jobs to finish...
    Building [=================================================>     ] 547/594

```

**Comment by jdm** [comment]
Sorry for the delay. This is caused by a mistake in the png crate, where they rely on a feature from the `deflate` crate that was introduced in a version more recent than the one listed in their Cargo.toml. Running `cargo update -p deflate` fixes the problem.

**Comment by jdm** [comment]
I filed https://github.com/PistonDevelopers/image-png/pull/106 upstream to fix it.

**Comment by shanavas786** [comment]
:+1:

**Comment by shanavas786** [comment]
I think this is a bit heavier for me. It would be better if someone can mentor.

**Comment by krk** [comment]
Servo 54f54d194df1911d1dd35a82dd87331853f985a3 can be built without errors with `pathfinder_gl`  https://github.com/pcwalton/pathfinder/commit/7cd05cd3effe96d8179adb208d093caa855d64ea version added to `components/canvas/Cargo.toml`.

**Comment by krk** [comment]
I have created a demo project by duplicating the included demo for SVG and reusing it to render `turtle graphics`, maybe it is of any use here: https://github.com/krk/pathfinder/tree/pf3-turtle

![image](https://user-images.githubusercontent.com/1447853/56854111-d2a73c00-6931-11e9-84fd-c3ccce188062.png)

Most of the turtle-renderer is copied directly from the svg-renderer demo.

**Comment by jdm** [comment]
https://github.com/pcwalton/pathfinder/blob/master/examples/canvas_minimal/src/main.rs should also be a good reference.

**Comment by jdm** [comment]
There are three main parts to this work:
* creating the GL context that pathfinder can use (we can possibly reuse the work to create a GL context for WebGL in [this code](https://github.com/servo/servo/blob/af077f8cf7feeb3ae791be133e4b3a10bf9ef614/components/canvas/webgl_thread.rs#L263-L288)
* creating a pathfinder Renderer object that can be used for all canvas operations
* making the various canvas commands use the renderer's canvas APIs

**Comment by pylbrecht** [comment]
@highfive assign me

**Comment by pylbrecht** [comment]
Relevant code as stated by @jdm in #servo:
- `components/script/dom/canvas2drenderincontext.rs` (I wouldn't expect many changes in this file)
- `components/canvas/canvas_paint_thread.rs`
- `components/canvas/canvas_data.rs` (the main canvas painting implementation)

**Comment by pylbrecht** [comment]
@jdm suggested [https://github.com/jrmuizel/raqote](https://github.com/jrmuizel/raqote) might be another option. This way we just need to replace azure with raqote.

**Comment by pylbrecht** [comment]
After skimming through [raqote]() and [canvas_data.rs](), I found some differences, which may or may not be important:
- [PathBuilder::bezier_curve_to()](https://dxr.mozilla.org/servo/source/components/canvas/canvas_data.rs#105) and [PathBuilder::ellipse()](https://dxr.mozilla.org/servo/source/components/canvas/canvas_data.rs#131) missing in raqote
- something about [shadows (?)](https://dxr.mozilla.org/servo/source/components/canvas/canvas_data.rs#282), which may be [planned functionality](https://github.com/jrmuizel/raqote/blob/master/README.md) in raqote, but is not implemented yet
- azure's [DrawTarget](https://dxr.mozilla.org/servo/source/components/canvas/canvas_data.rs#164) seems to provide more stuff than raqote's equivalent

Please note that I did not dive deep into the code yet, just been looking at function names etc.

Although I'm very tempted to just start hacking and see where I end up, it might be more reasonable to identify crucial functionality first. So, what are absolute must-haves and what can we leave open to be implemented in the future?

**Comment by jdm** [comment]
I don't know that there are any particular must-haves. It's good to know that raqote has some missing pieces that will affect us. We should file issues about the path builder methods for sure; what does "more stuff" mean, exactly?

**Comment by pylbrecht** [comment]
> what does "more stuff" mean, exactly?

At first glance: rect handling, stroke options, and shadows, but there could be more.

**Comment by jrmuizel** [comment]
- bezier_curve_to corresponds to Raqot's cubic_to
- ellipse can be also be implemented on top of cubic_to as done here: https://github.com/servo/rust-azure/blob/1ca68f302f5e914e2c63b0ec5b72af8f761f977d/libazure/PathHelpers.h
- shadows should at least be implementable outside of raqot. I'll try to put up a sample at some point.

**Comment by pylbrecht** [comment]
Progress update:
The current approach as discussed with @jdm is to abstract the painting backend (azure) in such a way, that we can introduce another backend (raqote) step by step with successful builds in between.
We realize this by implementing traits for more complex azure members (e.g. `azure_hl::DrawTarget`) and wrapping trivial types in enums (e.g. `azure_hl::Pattern`).

Work done so far:
- created `GenericDrawTarget` trait and implemented it for `azure_hl::DrawTarget`
- created `GenericPathBuilder` trait and implemented it for `azure_hl::PathBuilder`
- created enums for types, which came up by introducing the new traits

Due to life doing its thing (girlfriend back from vacation, moving to new appartment in two weeks, working on my thesis, etc.) my time is somewhat limited (again). I'm still very determined to keep working on this though, just at a slower pace, I guess.
Should I unexpectedly not be able to keep working on this, I'll definitely let you know, so someone else can get his/her hands on this.

**Comment by jdm** [comment]
Could you file a new issue tracking the raqote conversion!? It would be good to keep this one focused on Pathfinder.

**Comment by pylbrecht** [comment]
Would implementing a generic backend fall under this issue or should I move this to the new issue, as well?

**Comment by cbrewster** [comment]
If you're planning on writing a generic backend for 2d graphics you may want to consider https://github.com/linebender/piet. Currently a Raqote backend is in the works and potentially a Pathfinder backend could be implemented

**Comment by pylbrecht** [comment]
So many options.. Honestly, I feel a bit lost of what solution to approach right now.
@jdm, what do you think?

**Comment by jdm** [comment]
We don't actually want to end up with a generic backend. It's a stop along the way to replacing our current backend with raqote, which is where we want to end up in the short term.

**Comment by pylbrecht** [comment]
@jdm, alright. So I continue replacing azure with raqote, but tracking my progress in #23431 instead of here. Then I guess you can unassign me here and assign me to #23431?

**Comment by mrobinson** [comment]
Pathfinder isn't really maintained now, so I'm going to close this in favor of #30636.
