### ISSUE TITLE
Simplify VideoTrackList::set_selected

### ISSUE THREAD

**Issue by jdm** [servo/servo#22962]
It ends with several conditional calls to dispatch a change event. It should be possible to simplify the logic so we 1) deselect any currently selected track, 2) select the new track if `value` is true, 3) then dispatch the change event unconditionally.

Code: `components/script/dom/videotracklist.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements` should not report any changes in test results.

**Comment by Goncalerta** [comment]
@highfive: assign me
