### ISSUE TITLE
prefs.json: swap prefs before building

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#22970]
As of now, we swap the preferences during `mach package`. libsimpleservo reads prefs.json at compile time. So it should be done before building.

**Comment by jdm** [comment]
Sounds like we should add cargo metadata to rebuild if the pref files change, as well.

**Comment by Manishearth** [comment]
Also I _think_ the android build doesn't always swap prefs correctly, but I'm not sure.

(I'm getting weird behavior here)

**Comment by paulrouget** [comment]
#27304 partly solves this. Preferences are updated in build.rs.
