### ISSUE TITLE
Impossible to adjust cursor location in url input on ML

### ISSUE THREAD

**Issue by jdm** [servo/servo#22985]
The touchpad is used for selecting characters, and there seems to be no way to adjust the current cursor input location inside the URL if you started at the wrong input location.

**Comment by asajeffrey** [comment]
Yeah, the lack of cursor keys in the default keyboard is annoying.

**Comment by asajeffrey** [comment]
I asked a magicleap forum question. https://forum.magicleap.com/hc/en-us/community/posts/360048556391-Virtual-keyboard-cursor-keys

**Comment by atouchet** [comment]
Magic Leap is no longer supported. Is this issue still relevant?

**Comment by jdm** [comment]
Nope!
