### ISSUE TITLE
HTMLIframeElement.set_visible is unused

### ISSUE THREAD

**Issue by jdm** [servo/servo#22986]
This means that all of the checks around pipeline visibility in Servo are currently redundant, since set_visible is the only method that sends the constellation the SetVisible message.

**Comment by jdm** [comment]
The Pipeline struct does not even store any visibility state; notify_visibility just forwards that information to the compositor, but that's only called from the Pipeline constructor and the unused SetVisible message.

**Comment by jdm** [comment]
Visibility appears to be a property of the browsing context. That makes sense (like having a single foreground tab at a time), but that value is also never updated.

**Comment by jdm** [comment]
The changes in #23000 mean that we should be able to remove this method.

**Comment by jdm** [comment]
Code: `components/script/dom/htmliframeelement.rs`

If the build succeeds, that's good enough for a pull request.

**Comment by jdm** [comment]
This can also remove the SetVisible message, as well as the code that handles it in components/constellation/constellation.rs.

**Comment by fabricedesre** [comment]
Should that be used to trigger the `visibilitychange` event?

**Comment by AZWN** [comment]
@highfive: assign me
