### ISSUE TITLE
Debug servo build is intermittently unresponsive

### ISSUE THREAD

**Issue by jdm** [servo/servo#22988]
When I load https://threejs.org/examples in a debug servo build, often it works as expected. Once in a while it takes a _very_ long time before the hover styles start appearing under the mouse. There is no reported hang from the background hang monitor.

**Comment by jdm** [comment]
Judging by RUST_LOG=script::scipt_thread, it spends a really long time processing a particular network response event.

**Comment by jdm** [comment]
It appears to be hanging while reflowing after the DOMContentLoaded event, with a layout that is taking a ridiculously long time.

**Comment by jdm** [comment]
Servo appears to be issuing a reflow after every single DOM node that is parsed. This is terrible!

**Comment by jdm** [comment]
Ok, there are a bunch of problems conspiring to make this really bad:
* we unnecessarily perform a synchronous reflow in Document::maybe_dispatch_dom_content_loaded
* the page is using the innerHTML setter, which creates a document fragment and a new document which has a pointer to the original element's window
* the page uses innerHTML on every single link in the list of examples

Taken together this is what happens - for each link in the list of examples, we create a new document, parse a bit of text into it, finish parsing and fire a DOMContentLoadedEvent at the new document, then _synchronously reflow the main page_.

**Comment by asajeffrey** [comment]
Possibly related? #22926 

This sometimes shows itself in the log as a network hang, but it's actually waiting for window events.

**Comment by jdm** [comment]
This issue reflects a particular edge case involved lots of uses of innerHTML during initial document load. I wouldn't assume too broad an impact.
