### ISSUE TITLE
Trying to select letters in the ML keyboard UI is sometimes overwritten by new URLs being loaded

### ISSUE THREAD

**Issue by jdm** [servo/servo#22984]
I'm not sure what's happening here; it seemed like the laser pointer was selecting links when I was in keyboard mode.

**Comment by asajeffrey** [comment]
This could be a race condition where the browser is navigating at the same time as the URL is being entered?

**Comment by atouchet** [comment]
Magic Leap is no longer supported. Is this issue still relevant?
