### ISSUE TITLE
Promise::new crashes if no compartment has been entered

### ISSUE THREAD

**Issue by jdm** [servo/servo#22982]
This sucks, because if the code that calls Promise::new is invoked via some DOM API from JS, it works fine. If it's invoked from code that runs directly from an message from the event loop, it is not, since we do not automatically enter any compartments in that case. It would be very helpful to modify the API in such a way that the caller is forced to enter a compartment.

**Comment by AZWN** [comment]
@jdm I would be interested in working on this issue, but I am not sure if I understand it well enough. I could think of 3 ways that might solve this issue, but I am not sure of the implications of either:

- Add ```let _ac = JSAutoCompartment::new(global.get_cx(), global.reflector().get_jsobject().get());``` to ```Promise::new```
- Add ```JSAutoCompartment```  parameter to ```Promise::new``` (but this might this break the DOM API bindings??)

I am looking forward to hearing you opinion in this!

**Comment by jdm** [comment]
@AZWN I think we should make these changes:
* rename `new` to `new_unchecked` and mark it `unsafe`
* convert all existing callers to use `new_unchecked`
* add a `new` method which is safe and accepts a `&JSAutoCompartment` argument, which forces the caller to enter a compartment before calling it
