### ISSUE TITLE
DuckDuckGo search box does not bring up keyboard input on ML

### ISSUE THREAD

**Issue by jdm** [servo/servo#22983]
This may be a regression from #22871.

**Comment by asajeffrey** [comment]
Yeah, libsimpleservo ignores `HideIME` and `ShowIME` events: https://github.com/servo/servo/blob/c47575535ceb798ae3be60792c98bdd0a33f4415/ports/libsimpleservo/api/src/lib.rs#L571-L574

I filed #23969.

**Comment by atouchet** [comment]
Magic Leap is no longer supported. Is this issue worth keeping open?

**Comment by jdm** [comment]
No. Although it's highly likely that IME messages are still ignored in servoshell, we can file new platform-specific issues for supported platform.embeddings.
