### ISSUE TITLE
Don't update dom_content_loaded_event_end until the event has fired

### ISSUE THREAD

**Issue by jdm** [servo/servo#22994]
The call to `update_with_current_time_ms(&self.dom_content_loaded_event_end);` happens after this code:
```
        window
            .task_manager()
            .dom_manipulation_task_source()
            .queue_event(
                self.upcast(),
                atom!("DOMContentLoaded"),
                EventBubbles::Bubbles,
                EventCancelable::NotCancelable,
                window,
            );
```
That only queues a task to fire the event later, so the time we record does not reflect when the event is actually fired. We should use `queue` with a custom callback that fires the event and updates the time instead.

Code: `components/script/dom/document.rs`

**Comment by hundredeir** [comment]
@highfive : assign me
