### ISSUE TITLE
Perform better line-breaking that accounts for complex text

### ISSUE THREAD

**Issue by burg** [servo/servo#230]
Gecko has a decent implementation in `nsLineBreaker`. Linebreaking information is stored directly in glyph storage when text run is created.

We should probably use a pluggable line-breaking/space-providing system, to reduce coupling or take advantage of system versions.

**Comment by emilio** [comment]
@mbrubeck: This is closed after the switch to `xi-unicode`, right?

**Comment by mbrubeck** [comment]
Yes. Closed by #10913.
