### ISSUE TITLE
CPU rendering does not work when using nvidia drivers

### ISSUE THREAD

**Issue by dreamer** [servo/servo#2300]
To reproduce:

```
$ ./servo -c ../src/test/html/about-mozilla.html
```

Servo exits immediately with following message in terminal (nothing else is printed):

```
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152 (GLX)
Minor opcode of failed request:  22 (X_GLXCreatePixmap)
```

Using Fedora 20, all packages up-to-date, nvidia drivers from rpmfusion, version 331.67;
xorg-x11-drv-nvidia.x86_64  1:331.67-1.fc20

When using nouveau, it works as expected.

After some digging, I found this: https://bugzilla.mozilla.org/show_bug.cgi?id=896287
First comment in that report may indicate how to fix it:

> It's likely that this is due to this change in the 325.08 notes[1]
> 
> > Generate a BadMatch error when applications attempt to create GLX pixmaps using 
> > glXCreatePixmap() or glXCreateGLXPixmapWithConfigSGIX() and the pixmap's depth doesn't 
> > match that of the specified GLXFBConfig.
> 
> [1] https://devtalk.nvidia.com/default/topic/549155/unix-graphics-announcements-and-news/linux-solaris-and-freebsd-driver-325-08-beta-/

**Comment by mrobinson** [comment]
We no longer have a CPU render path, so I'm going to close this one.
