### ISSUE TITLE
Remove blocking communication when promoting a memory-backed blob

### ISSUE THREAD

**Issue by jdm** [servo/servo#23032]
Blob::promote has one case where it blocks on receiving a response from the file manager thread where that is not necessary. When promoting a BlobImpl::Memory, it sends the blob information to the file manager thread and waits to receive the uuid for the newly promoted blob. Since the file manager thread just creates a random uuid and returns it in the case of success, we can invert this pattern - Blob::promote can create a random uuid and send it in the `FileManagerThreadMsg::PromoteMemory` message. The file manager thread can use this id, and if it encounters a problem it just can just ignore it.

Code: `components/script/dom/blob.rs`, `components/net_traits/filemanager_thread.rs`, `components/net/filemanager_thread.rs`

The tests at `./mach test-wpt tests/wpt/web-platform-tests/FileAPI` should show no change in behaviour.

**Comment by miller-time** [comment]
@highfive assign me
