### ISSUE TITLE
Page load response timing information gets ignored

### ISSUE THREAD

**Issue by jdm** [servo/servo#23043]
In `component/script/network_listener.rs` there is this code:
```
    if initiator_type == InitiatorType::Other {
        warn!("Ignoring InitiatorType::Other resource {:?}", url);
        return;
    }
```
I've seen a bunch of logs that include top level page URLs, so we are apparently providing an incorrect initiator type somewhere.

**Comment by jdm** [comment]
Oh, I see - LayoutImageContext is returning the URL of the page, rather than the URL of the image being loaded. That's no good; we should store the URL as a member of LayoutImageContext so that we can return it.

Code: `components/script/layout_image.rs`
Test: run `RUST_LOG=script::network_listener ./mach run https://servo.org/ml-home/` and observe the warnings before and after the change.

**Comment by c410-f3r** [comment]
@highfive: assign me
