### ISSUE TITLE
Layout queries on elements in disconnected frames panics

### ISSUE THREAD

**Issue by jdm** [servo/servo#23053]
```html
<iframe></iframe>
<script>
  var i = document.querySelector('iframe');
  var d = i.contentDocument;
  var e = d.createElement('div');
  d.body.appendChild(e);
  i.remove();
  setTimeout(function() { e.getBoundingClientRect(); }, 10);
</script>
```
When we remove an iframe, we shut down its browsing context and layout thread. Layout queries assume that the layout thread always exists, however.

**Comment by jdm** [comment]
Previously found in #19170.

**Comment by jdm** [comment]
One way of fixing this would be to merge the script and layout threads.

**Comment by jdm** [comment]
I think we should fix this by [removing this `expect` call](https://github.com/servo/servo/blob/dd2deeabca7eeb40e6a8fe0c1ee4550d64e0c235/components/script/dom/window.rs#L1419-L1421) and returning `false` if the send operation fails instead.

**Comment by jdm** [comment]
Then we can [add an automated test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) based on the code I provided earlier. We will want to [assert](https://web-platform-tests.org/writing-tests/testharness-api.html) that the returned rectangle is zero-sized.

**Comment by soniasingla** [comment]
@highfive : assign me

**Comment by jdm** [comment]
That sounds reasonable.

**Comment by gterzian** [comment]
Ok I think it would be event better to make:

https://github.com/servo/servo/blob/fde47f89373726dbe63fcea2e717d139be7b389e/components/script/dom/window.rs#L2105

return `Option<&Sender<Msg>>`, 

where `None` would be returned if `!self.is_alive()`

and make every use of the layout chan go through this function, including inside `window.rs`.

**Comment by alarsyo** [comment]
@highfive: assign me
