### ISSUE TITLE
Magic Leap package is not recreated when libmlservo.a is updated

### ISSUE THREAD

**Issue by jdm** [servo/servo#23067]
I wasted a bunch of time trying to understand why my changes in libmlservo were not reflected in the build output. I finally checked the timestamps on Servo2D.mpk vs. libmlservo.a and discovered that mabu seems to not re-link the application if the static library has been updated but the package source files have not.

**Comment by CYBAI** [comment]
I saw the comment at https://github.com/servo/servo/pull/23976/files#r314382292 .
Should we close this issue ?
