### ISSUE TITLE
Remove headless check from bluetooth code

### ISSUE THREAD

**Issue by jdm** [servo/servo#23065]
There's nothing special about headless mode that should make the bluetooth code behave differently. We can remove the check for `opts::get().headless` entirely.

Code: `components/bluetooth/lib.rs`

**Comment by ejmg** [comment]
@highfive: assign me

**Comment by jdm** [comment]
Unassigning per request on IRC.

**Comment by hgallagher1993** [comment]
@highfive: assign me

**Comment by hgallagher1993** [comment]
Actually you can unassign me because I can't get servo to compile. The compilation failure is to do with GStreamer, my version is 1.8 and I can't see an easy way to upgrade it passed that...

**Comment by cdeler** [comment]
@highfive : assign me
