### ISSUE TITLE
Support XRTest for WPT webxr tests

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#23071]
The WPT webxr tests use an XRTest interface that allows for spinning up dummy webxr sessions.

https://github.com/servo/servo/blob/93dc2295f7dc7dc6436be0e524701ccf08566fb9/tests/wpt/web-platform-tests/webxr/resources/webxr_util.js#L43

We should support that so that we can test this.

May be worth hacking this into https://github.com/servo/rust-webvr/blob/master/rust-webvr/src/api/mock/ ?

cc @asajeffrey

**Comment by msub2** [comment]
@jdm This can probably be closed since we are currently running WebXR WPTs with the WebXR Test API.
