### ISSUE TITLE
Implement StyleSheet.ownerNode

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#23082]
As @emilio mentioned in https://github.com/servo/servo/pull/23073#pullrequestreview-217996814 , we don't support `ownerNode` yet.

Spec: https://drafts.csswg.org/cssom/#dom-stylesheet-ownernode

https://github.com/servo/servo/blob/0ff87c8137030ece065f283552c28f4837cef5f3/components/script/dom/webidls/StyleSheet.webidl#L11

We need to uncomment it and implement it in `components/script/dom/stylesheet.rs` (basically just need to reuse the method added in #23073 ).

(But somehow I'm confused that the spec said it's an `Element or ProcessingInstruction` but we only have `Element` in `CSSStyleSheet`. Maybe we can only always return an `Element` for now? 🤔)

**Comment by CYBAI** [comment]
@sbansal3096 maybe you'd be interested in this one?

**Comment by sbansal3096** [comment]
Yeah, sure. I am.willing to give it a shot.

**Comment by sbansal3096** [comment]
@CYBAI Do I have to implement the new ownerNode function in the same fashion that is been used for other properties like title? If so, then where should I use the new function that I created in my last pull request?
https://github.com/servo/servo/blob/0ff87c8137030ece065f283552c28f4837cef5f3/components/script/dom/stylesheet.rs#L38

**Comment by CYBAI** [comment]
@sbansal3096 Yes. When you uncomment the property in WebIDL, compiler will give you the hint ;) In this case, you'll need to implement `GetOwnerNode` for `StyleSheetMethods`. Then, you can reuse the method you created in last PR in the `GetOwnerNode`.

If my explanation is not clear, feel free to let me know :)

**Comment by CYBAI** [comment]
The work in #23096 is almost there and only need to address @emilio 's suggestions in https://github.com/servo/servo/pull/23096#discussion_r274079177 and https://github.com/servo/servo/pull/23096#discussion_r274080860.

@sbansal3096 Feel free to reopen and finish that PR if this is not fixed when you have time!
