### ISSUE TITLE
Servo build fails on MacOS Sierra

### ISSUE THREAD

**Issue by fredfeng** [servo/servo#23087]
I first followed the instructions for brew:
brew bundle install --file=etc/taskcluster/macos/Brewfile
pip install virtualenv

Since my MacOS is 10.13.4 (High Sierra), I also ran the following commands:
brew install openssl

export OPENSSL_INCLUDE_DIR="$(brew --prefix openssl)/include"
export OPENSSL_LIB_DIR="$(brew --prefix openssl)/lib"

./mach check

But the `check` command didn't pass:
...
    Checking crossbeam-deque v0.6.1
   Compiling quote v0.6.3
    Checking crossbeam-deque v0.2.0
    Checking futf v0.1.4
    Checking ordered-float v1.0.0
    Checking immeta v0.4.0
    Checking generic-array v0.9.0
    Checking generic-array v0.12.0
    Checking core-foundation v0.6.2
error: failed to run custom build command for `gobject-sys v0.7.0`
process didn't exit successfully: `/servo/target/debug/build/gobject-sys-ab01c00524d1de76/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gobject-2.0 >= 2.32"` did not exit successfully: exit code: 1
--- stderr
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found

warning: build failed, waiting for other jobs to finish...
    Building [===========================>                           ] 310/590: osmesa-src(build), mozangle(build)

Any hints will be highly appreciated!

**Comment by jdm** [comment]
@fredfeng Does https://github.com/servo/servo/issues/23015#issuecomment-475162473 help at all?

**Comment by fredfeng** [comment]
Yes, it works. Thanks so much!

I tried this:
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
