### ISSUE TITLE
Windows python support should be made easier

### ISSUE THREAD

**Issue by TheGoddessInari** [servo/servo#23083]
On my systems (as many are), I have both Python 2 and 3 installed with 3 being the default.

I personally symlink python 2.x to python2 and python2.7 on the PATH, but the Windows python versions provide its own solution to this: `py -2`, which is installed by default.

Even manually running mach via python 2.7 runs into quite a few blockers, including the 
`''':' && if [ ! -z "$MSYSTEM" ] ; then exec python "$0" "$@" ; else which python2.7 > /dev/null 2> /dev/null && exec python2.7 "$0" "$@" || exec python "$0" "$@" ; fi`
 block at the top of mach getting very confused and not allowing execution, and `python/mach_bootstrap.py` trying to explicitly override your python choice (again!), when it could just run the equivalent of `python -m pip` and `python -m virtualenv` from whatever version of python you're trying to run it with already.

In the case of `python/mach_bootstrap.py`, for instance, this results in a Python 3.x virtualenv if python 3.x is the default on my PATH, even running mach via python 2.x and having python2 and python2.7 binaries resolvable on the PATH.

For whatever reason mach is still using Python 2, it should better support the fact that mach is already being run from a python interpreter and shouldn't need to try to make guesses on what the user's path/environment is and override the execution. 

`py -2` should probably also be the default from `mach.bat`.

I nearly gave up on Servo because of the above problems because it wasn't clear what was going wrong, especially with the `python/mach_bootstrap.py` issue.

**Comment by tigercosmos** [comment]
There’s room for improvement. We would be glad if you can help improve the code.
Do you finally build the servo successfully? I know it is always hard to set up the environment and build on Windows.

**Comment by TheGoddessInari** [comment]
I can certainly look into it soon. Currently it doesn't get through all of the dependencies **for me** because `cmake-rs` needs updating for VS2019, but at least mach is working as expected with workarounds.

I have some other ideas on how to (possibly) make Windows support easier (that I could presumably also work on), but that depends on some other infrastructure updates anyway.

How opposed would servo be on optionally seeing (via cmake) if vcpkg is installed and working on Windows before dragging in prebuilt binaries for end users? Or would that add too much non-determinism for the build process? 

vcpkg lets Windows people add and manage compiled packages for other things to include in their build process. Right now, I think the main thing missing from vcpkg is gstreamer, which I can always try to get included. I think the downside with vcpkg is that there's no standard path on which it'd be installed or detectable.

**Comment by tigercosmos** [comment]
I conservatively thought that the Servo team might not want to change the infra of building, since it would take a risk. However, I encourage you to talk to the members of the team on IRC if you really want to do something cool.

**Comment by jdm** [comment]
I would be interested in learning more about how vcpkg could make building on Windows easier.

**Comment by TheGoddessInari** [comment]
vcpkg represents a development-minded package manager from Microsoft on that builds many things from source. It's pretty easy to use and extensible. It makes the most sense on Windows, at least if I can help them make sure they're discoverable from cmake. Since it's from Microsoft and open source, it's about as official as it gets for the platform.

It wouldn't necessarily make building easier in all cases, but **would** make it easier to keep things consistent. If someone's set up a development environment on their machine, presumably it'd be useful to ensure that the same MSVC version is used for all C, C++, and Rust bits and everything is ABI and linker compatible.

Of course, none of it applies (much) to MSYS2 or other things that are sufficiently UNIX-y.

I'd noticed servo downloading binaries for things like OpenSSL, which vcpkg can provide. Just as an optional thing to be able to pull library and header availability from would be nice. If I'm compiling things with cargo with the MSVC ABI, I'm already using cl.exe under the hood and it can be a good idea to make as much as possible compiled in the same fashion.

As I said, I think the only major piece missing that servo uses is gstreamer, but I can always file pull requests for that too.

**Comment by TheGoddessInari** [comment]
I just realized as for vcpkg, there's a vcpkg crate which entirely simplifies things, and one of servo's dependencies already uses.

I'll definitely try to get gstreamer on there regardless as it could be useful.

As a sidenote, Rust infrastructure seems to be a lot more responsive than anything node-related. That's very reassuring to someone who's been run ragged trying to get bugs fixed elsewhere for ages.
