### ISSUE TITLE
Links to deprecated Rust documentation in HACKING_QUICKSTART.md 

### ISSUE THREAD

**Issue by tdelacour** [servo/servo#23088]
I was reading through `HACKING_QUICKSTART.md` today while trying to get my dev environment set up. I noticed in [this](https://github.com/servo/servo/blob/master/docs/HACKING_QUICKSTART.md#some-basic-rust) section, the links to "match" and "pattern" both link to the deprecated "first edition" Rust book. 

Not sure if this ought to be another issue, but I also spent some time stuck getting `servo` to build for the first time before discovering that I needed to run this: `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"`, which isn't mentioned in the `README.md`. I'm not sure how particular that is to my experience, but it does seem like `pkg-config` on OSX does not know how to find `libffi` by default, and the `servo` build script requires this to work in order to check the version of `gstreamer`. 

I'd actually really appreciate it if this issue was assigned to me, if that's alright, as I am just starting here and I think it would be a solid way to get acquainted with the PR process for `servo`. Thanks!

**Comment by paulrouget** [comment]
Go ahead and submit a PR to fix the link in HACKING_QUICKSTART.

> Not sure if this ought to be another issue, but I also spent some time stuck getting servo to build for the first time before discovering that I needed to run this: export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

Probably better to file another issue to investigate why you have to do that.

**Comment by paulrouget** [comment]
re PKG_CONFIG_PATH. Just saw that: https://github.com/servo/servo/issues/23087 - and https://github.com/servo/servo/issues?utf8=✓&q=is%3Aissue+is%3Aopen+PKG_CONFIG_PATH

**Comment by tdelacour** [comment]
@paulrouget aha ok yeah those issues do seem to be the same. Must've not searched very well first...

Will address the links later today. Thanks!
