### ISSUE TITLE
Windows build is broken with GStreamer 1.15

### ISSUE THREAD

**Issue by jdm** [servo/servo#23104]
The package has apparently renamed `libffi-7.dll` to `ffi-7.dll`, so [this code](https://github.com/servo/servo/blob/7b8a898ac2ffef5ced8202dfd8bb40e37b972334/python/servo/build_commands.py#L622) fails. We should either tell developers to install a specific version of GStreamer or update it to support both old and newer versions.

**Comment by UK992** [comment]
in 1.15.1 `libz.dll` is renamed to `libz-1.dll`
in 1.15.2 all dlls needed by servo are named without prefix `lib`

**Comment by jdm** [comment]
Thanks, that's helpful. My changes in #23126 should be able to accommodate that.
