### ISSUE TITLE
[layout] [question] What is the function of a ClipScrollNode ?

### ISSUE THREAD

**Issue by twitchyliquid64** [servo/servo#23107]
Heya,

I've been trying to understand the layout code, and a concept I see come up a bit in layout and also in webrender is `ClipScrollNodes`. What is it exactly? Why do we need it?

**Comment by jdm** [comment]
The general idea is that a ClipScrollNode represents a region that can be clipped and scrolled, such as a CSS element with `overflow: scroll` applied and content that overflows its block size.
