### ISSUE TITLE
"libgstgl-1.0-0.dll not found" when starting Servo Tech Demo on Windows 10

### ISSUE THREAD

**Issue by dmos62** [servo/servo#23125]
When starting Servo Tech Demo on Windows 10 the following error is thrown immediately:

```
servo.exe - System Error
The code execution cannot proceed because libgstgl-1.0-0.dll was not found. Reinstalling the program may fix the problem.
```

After closing the dialog, the browser does not start. This is the latest developper preview as served by download.servo.org today.

**Comment by jdm** [comment]
It's possible we need to install a newer version of gstreamer on our Windows CI.

**Comment by jdm** [comment]
Aha, we're missing libgstgl-1.0-0.dll from [this list](https://github.com/servo/servo/blob/cd8b9cab22ba375628b9f47ed0b589397817e145/python/servo/build_commands.py#L621).
