### ISSUE TITLE
Switch to upstream glutin osmesa support

### ISSUE THREAD

**Issue by jdm** [servo/servo#23131]
There's an [OsMesaContextExt](https://github.com/tomaka/glutin/blob/e291a1960ef4c2f3789115c8c442669a04a7aa42/glutin/src/platform/linux/mod.rs#L289-L296) trait that can be imported which allows creating a software rendering context that integrates with glutin. That might allow us to remove a bunch of OsMesa-specific code inside Servo.

**Comment by SimonSapin** [comment]
Glutin is no longer used since https://github.com/servo/servo/pull/25853.
