### ISSUE TITLE
Use pregenerated certs and keys for WPT

### ISSUE THREAD

**Issue by jdm** [servo/servo#23133]
We should [set the following defaults](https://github.com/servo/servo/blob/681c0ebf4b5a4b5abf0843986036e3594cc193b8/tests/wpt/run.py#L51-L79) for running WPT tests:
* `--ca-cert-path=tests\wpt\web-platform-tests\tools\certs\cacert.pem`
* ` --host-key-path=tests\wpt\web-platform-tests\tools\certs\web-platform.test.key`
* `--host-cert-path=tests\wpt\web-platform-tests\tools\certs\web-platform.test.pem`
* `--ssl-type=pregenerated`

The best way to test that these changes are valid is to run `./mach test-wpt tests/wpt/mozilla/tests/mozilla/secure.https.html`. If it reports no unexpected results, then they are working.

**Comment by soniasingla** [comment]
@highfive : assign me
