### ISSUE TITLE
Implement DocumentFragment XML serialization

### ISSUE THREAD

**Issue by jdm** [servo/servo#23134]
[This branch](https://github.com/servo/servo/blob/fcd6beb60819ef2960f70d10e82fa31ba56cc99b/components/script/dom/servoparser/html.rs#L167-L176) does nothing if a DocumentFragment is encountered during XML serialization, but we should be running the [appropriate XML serialization algorithm](https://w3c.github.io/DOM-Parsing/#dfn-xml-serializing-a-documentfragment-node). Like in #23130, we will want to check for a DocumentFragment in the SerializationIterator constructor and push all of the immediate child nodes.

**Comment by jdm** [comment]
Testcase:
```html
<script>
var df = new DocumentFragment;
df.push(document.createElement('div'));
df.push(document.createElement('span'));
console.log(new XMLSerializer.serializeToString(df))
</script>

**Comment by 5h1rU** [comment]
Did you mean?
```js
var df = new DocumentFragment;
df.append(document.createElement('div'));
df.append(document.createElement('span'));
console.log(new XMLSerializer().serializeToString(df))
```
 Seems like push is not a valid method here.
> Testcase:
> 
> ```
> <script>
> var df = new DocumentFragment;
> df.push(document.createElement('div'));
> df.push(document.createElement('span'));
> console.log(new XMLSerializer.serializeToString(df))
> </script>
> ```

**Comment by jdm** [comment]
I did, yes. Good catch!

**Comment by jackxbritton** [comment]
@highfive: assign me
