### ISSUE TITLE
Synchronous network fetch does not create performance resource timing entry

### ISSUE THREAD

**Issue by jdm** [servo/servo#23150]
All of our async network fetch code ends up calling the `submit_timing` helper function in order to register the resource timing information for the network load. However, the dedicated worker initial script fetch and the worker global importScripts API use the `load_whole_resource` helper API, which blocks until a response is complete and returns the response data. In the handler for `FetchResponseMsg::ProcessResponseEOF` in `load_whole_resource`, the resource timing information is discarded without being used. To fix this, we should:
* make a new SyncFetchResponse structure that contains the resource timing, metadata, and response body
* have `load_whole_resource` return this new structure
* extract the guts of `submit_timing` into a helper `submit_timing_data` function that does not use any generics, but accepts the required arguments
* make `submit_timing` call `submit_timing_data`
* make all callers of `load_whole_resource` call `submit_timing_data` with the required resource timing arguments that are now available

**Comment by jdm** [comment]
We could go a step further and make `load_whole_resource` accept a function pointer that it will call with the resource timing information, to avoid this problem in the future. This would allow all of the callers to pass `submit_timing_data`, and it would be impossible to forget this if any new callers appear later.

**Comment by pylbrecht** [comment]
I'd like to work on that! I don't see good old @highfive, so would you assign me?

**Comment by pylbrecht** [comment]
I looked into this, but I still have some trouble sorting things out. I'll probably hit you up on IRC anyway, but here are some questions that came to my mind:
> - make a new SyncFetchResponse structure that contains the resource timing, metadata, and response body
> - have load_whole_resource return this new structure

The `Metadata` struct returned by `load_whole_resource()` already has a member `timing` of type `ResourceFetchTiming`. Can't we just use that instead of making a new struct?

> - make all callers of load_whole_resource call submit_timing_data with the required resource timing arguments that are now available

I guess the callers of `load_whole_resource()` should call `submit_timing_data()` with the arguments made available through returns of `load_whole_resource()` in the first place, correct?

**Comment by jdm** [comment]
> The `Metadata` struct returned by `load_whole_resource()` already has a member `timing` of type `ResourceFetchTiming`. Can't we just use that instead of making a new struct?

Good point!

> I guess the callers of `load_whole_resource()` should call `submit_timing_data()` with the arguments made available through returns of `load_whole_resource()` in the first place, correct?

Yes.

**Comment by pylbrecht** [comment]
Thank you, that assures my approach so far.
Are there any tests existing tests I can use to verify? I feel like some of the ones that failed while working on #23145 may matter here?

**Comment by jdm** [comment]
To answer your question, https://github.com/servo/servo/pull/23323#issuecomment-489716941 shows a test that should demonstrate different behaviour after your changes. That's `/resource-timing/idlharness.any.worker.html`.
