### ISSUE TITLE
Set PKG_CONFIG_PATH automatically when necessary from mach

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#23177]
From #23015 , we found `PKG_CONFIG_PATH` is required for building Servo.
So, I sent another PR (#23175) to add the README note.

We should be able to set the env var automatically from `mach` when there's no existing one.

We can do it like following line

https://github.com/servo/servo/blob/3e81a5afe938570ee4a0321e2c0269ed582e3adf/python/servo/command_base.py#L620

As @ferjm mentioned in [IRC](https://mozilla.logbot.info/servo/20190408#c16183483), we only need to set the `PKG_CONFIG_PATH` environment variable when the `pkg-config` check fails. So, we can do the check once, then set env var if the check fails. If it still fails, then we will throw the error because it might be related to other issues.

**Comment by o0Ignition0o** [comment]
Oh I just posted in a closed issue, sorry about that: https://github.com/servo/servo/issues/23015#issuecomment-519580410 :/
