### ISSUE TITLE
Update CustomElementConstructor type and exception

### ISSUE THREAD

**Issue by jdm** [servo/servo#23202]
The IDL for CustomElementConstructor was changed in https://github.com/whatwg/html/pull/4525. We should update that as well as the exception used by [this code](https://github.com/servo/servo/blob/17204544d975a44f813b96ed3e0eae3b688596bc/components/script/dom/customelementregistry.rs#L668).

To test these changes, we will need the tests in https://github.com/web-platform-tests/wpt/pull/16328.

**Comment by gatoWololo** [comment]
Cool. I think I understand this. I can do it.

**Comment by gatoWololo** [comment]
> We should update that as well as the exception used by this code.

I have found 2 places where we need to change from `Error::InvalidState` to `Error::Type`. The one you pointed out above. and
https://github.com/servo/servo/blob/1e158bbfaed2bed6c739d14dbd1cd4ba5cacfe82/components/script/dom/bindings/htmlconstructor.rs#L185


> To test these changes, we will need the tests in web-platform-tests/wpt#16328.

The tests are already in Servo [here](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/custom-elements/upgrading/Node-cloneNode.html) and [here](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/custom-elements/upgrading/upgrading-parser-created-element.html), and they are the latest version using TypeError.

After changing to `Error::Type` and running:
`./mach test ./tests/wpt/web-platform-tests/custom-elements/upgrading/upgrading-parser-created-element.html`
`./mach test ./tests/wpt/web-platform-tests/custom-elements/upgrading/Node-cloneNode.html`

I can confirm all the `[expected FAIL]` tests related to `TypeError`, now pass :)

My only question: I'm not sure what `String` to pass to `Error::Type(String)`?
Currently, I have something like:
```rust
        if !same {
            return Err(Error::Type("Returned element is not SameValue as the upgraded element".to_string()));
```
Is this what's expected? Or is there somewhere specific to get the correct string from?

**Comment by jdm** [comment]
Strings are implementation-defined, so that one seems fine.
