### ISSUE TITLE
Support Visual Studio 2019

### ISSUE THREAD

**Issue by jdm** [servo/servo#23219]
This requires at minimum:
* updating cmake-rs to the most recent version
* updating [the cmake package](https://github.com/servo/servo/blob/a14b952fa3eedec86e6308213c525538bcb20827/python/servo/packages.py#L6) to a more recent version like 3.14

**Comment by jdm** [comment]
The cmake issue can be worked around by installing a newer version so that it's available in the user's PATH.

**Comment by jdm** [comment]
Hit C++ errors when building mozjs and gave up for the time being.

**Comment by saschanaz** [comment]
It seems this is wontfixed in Bugzilla side: https://bugzilla.mozilla.org/show_bug.cgi?id=1536765

**Comment by paulrouget** [comment]
About HoloLens: MS recommends VS 2017 for now.

**Comment by paulrouget** [comment]
I've learned that we can now compile with 2019 with `--features vslatestinstalled`. What's the status of that?

**Comment by jdm** [comment]
Several of us only have MSVC 2019 installed and build with it exclusively. We should make this mandatory soon.

**Comment by paulrouget** [comment]
For the record, to use VS 2019:

- uninstall VS 2017 then install VS 2019
- in `python/servo/packages.py` replace set llvm version to `9.0.0` 
- remove `support/hololens/ServoApp/ServoApp.vcxproj.user`

This should be enough.

**Comment by mrobinson** [comment]
I think we have successfully been using Visual Studio 2019.
