### ISSUE TITLE
Build fails on macOs Sierra

### ISSUE THREAD

**Issue by nagashayan** [servo/servo#23218]
Build is failing with exception `Your system's gstreamer libraries are out of date`

when I run 

` ./mach build --dev ...`

on macOS 10.12.6

```
The details of the failure are as follows:

Exception: Your system's gstreamer libraries are out of date (we need at least 1.12). If you're unable to install them, let us know by filing a bug!

  File "/Users/n115/rust/servo/python/servo/build_commands.py", line 286, in build
    env = self.build_env(target=target, is_build=True)
  File "/Users/n115/rust/servo/python/servo/command_base.py", line 616, in build_env
    if self.needs_gstreamer_env(target):
  File "/Users/n115/rust/servo/python/servo/command_base.py", line 562, in needs_gstreamer_env
    raise Exception("Your system's gstreamer libraries are out of date 
```

But the exception is misleading I have installed gstreamer 1.14 and even symlinked new version to old. 

So when I started digging deeper I found

sys.platform is 'darwin' for macOS. 

```
Python 2.7.15 (default, Jun 17 2018, 13:05:56) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.platform)
darwin
>>> exit()
```
so in `command_base.py needs_gstreamer_env()` doesn't handle this condition and just throws exception.

**Comment by nagashayan** [comment]
@highfive assign me. if you think this issue is valid.

**Comment by jdm** [comment]
@nagashayan [This code](https://github.com/servo/servo/blob/a14b952fa3eedec86e6308213c525538bcb20827/python/servo/bootstrap.py#L49) runs fine for me on macOS 10.12.6, which causes [this code](https://github.com/servo/servo/blob/a14b952fa3eedec86e6308213c525538bcb20827/python/servo/command_base.py#L541-L542) to return immediately without checking the platform type. You should figure out why your pkg-config doesn't believe you have installed the appropriate version.

**Comment by CYBAI** [comment]
@nagashayan Could you check if you have `PKG_CONFIG_PATH` environment variable in your machine? Maybe the failure is related to [this note](https://github.com/servo/servo#note-please-make-sure-the-required-pkg_config_path-environment-variable-is-set-the-same-as-the-one-provided-from-brew-info-libffi-check-this-comment-for-more-details) 🤔

**Comment by nagashayan** [comment]
hey sorry about it, pretty new here! Yes it was PKG_CONFIG_PATH. configured and build succeeded.

**Comment by nagashayan** [comment]
close the issue.
