### ISSUE TITLE
Make decision task create actions.json artifact

### ISSUE THREAD

**Issue by jdm** [servo/servo#23217]
https://docs.taskcluster.net/docs/manual/using/actions
https://firefox-source-docs.mozilla.org/taskcluster/taskcluster/actions.html
https://searchfox.org/mozilla-central/source/taskcluster/taskgraph/actions

This will allow us to support treeherder's job cancellation, as long as the people who need to cancel jobs have the right scopes present in their accounts.

**Comment by mrobinson** [comment]
We no longer use taskcluster, so cleaning this up.
