### ISSUE TITLE
Support GL video in Magic Leap

### ISSUE THREAD

**Issue by jdm** [servo/servo#23224]
I believe there are three parts to this work:
* expose the RenderUnix implementation to Android platforms ([here](https://github.com/servo/media/blob/5462b0542b47c606399e3c2b7c4a4db35ae4466e/backends/gstreamer/render.rs#L13) and [here](https://github.com/servo/media/blob/5462b0542b47c606399e3c2b7c4a4db35ae4466e/backends/gstreamer/render-unix/lib.rs#L10))
* pass the GL context information from the embedding to the script thread
  * add appropriate members to [InitOptions](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/ports/libsimpleservo/api/src/lib.rs#L42) and initialize them from [these pointers](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/ports/libmlservo/src/lib.rs#L99-L101)
  * add the GL data to the [ServoCallbacks](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/ports/libsimpleservo/api/src/lib.rs#L549) struct
  * add a method to the [WindowMethods](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/compositing/windowing.rs#L141) trait which returns the GL data
  * add the GL data to the [InitialConstellationState](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/constellation/constellation.rs#L379), obtained via the new trait method in the Servo [constructor](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/servo/lib.rs#L183)
  * add the GL data to the [InitialPipelineState](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/constellation/pipeline.rs#L102)
  * add the GL data to the [UnprivilgedPipelineContent](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/constellation/pipeline.rs#L478)
  * add the GL data to the [InitialScriptState](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/script_traits/lib.rs#L553)
  * add the GL data to a [thread local](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/script/script_thread.rs#L160) in the script thread and initialize it from the ScriptThread [constructor]((https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/script/script_thread.rs#L1056-L1060))
* call the [set_gl_params](https://github.com/servo/media/blob/5462b0542b47c606399e3c2b7c4a4db35ae4466e/player/lib.rs#L94) API with the GL data stored in the thread local from [this code](https://github.com/servo/servo/blob/eac2607a06db56a468cae357a9ab0ed6a4945d82/components/script/dom/htmlmediaelement.rs#L1203)

cc @xclaesse @ceyusa

**Comment by ferjm** [comment]
Most part of this work will likely happen in #22920

**Comment by jdm** [comment]
Bah, I can't believe I forgot that I filed that.

**Comment by asajeffrey** [comment]
Closed by #23929.
