### ISSUE TITLE
Servo doesn't detect virtualenv?

### ISSUE THREAD

**Issue by theDragonFire** [servo/servo#23231]
Hello, I am attempting to install Servo. I have run `./mach bootstrap`, and it has completed successfully as far as I can tell. However, when I try to run `./mach run github.com`, it gives me the message that `Python virtualenv is not installed. Please install it prior to running mach.` I have installed virtualenv using `pip install virtualenv`, but it still gives me the same error.

**Comment by georgeroman** [comment]
The default of `pip` is probably set to `python3`, but you need to install `virtualenv` for `python2`. Try running `pip2 install virtualenv` or `python2 -m pip install virtualenv`.

**Comment by theDragonFire** [comment]
This worked. Thanks.
