### ISSUE TITLE
Add webidl annotation to pass InCompartment argument to DOM methods

### ISSUE THREAD

**Issue by jdm** [servo/servo#23257]
Based on the work in #23253:

Let's add a new `in_compartment` property to [this configuration](https://github.com/servo/servo/blob/ec680de0635932201655318a3acf446c40b14e03/components/script/dom/bindings/codegen/Bindings.conf) - for a given interface, this property will be a list of method/property names that expect to receive `InCompartment` arguments.

We will need to store this `in_compartment` in [this code](https://github.com/servo/servo/blob/ec680de0635932201655318a3acf446c40b14e03/components/script/dom/bindings/codegen/Configuration.py#L223-L227) so we can query it later during code generation.

The easiest place to start is with methods in [this code](https://github.com/servo/servo/blob/ec680de0635932201655318a3acf446c40b14e03/components/script/dom/bindings/codegen/CodegenRust.py#L6680-L6690). We can treat this similarly to deciding whether to provide a `*mut JSContext` argument or not, by making the caller tell us whether this is a method that should provide an InCompartment argument or not.

**Comment by jdm** [comment]
It's easiest to start small here - make the fetch method from Window.webidl take an InCompartment object, and adjust the code generation until everything lines up.

**Comment by Eijebong** [comment]
Should all the methods asserting `AlreadyInCompartment ` use that ?

**Comment by jdm** [comment]
That's the idea behind this work, yes.
