### ISSUE TITLE
Create a helper API for entering a DOM object's compartment

### ISSUE THREAD

**Issue by jdm** [servo/servo#23266]
Writing code like `JSAutoCompartment::new(global.get_cx(), global.reflector().get_jsobject().get());` isn't great. We should create a wrapper API that accepts a DomObject reference, then gets the JSContext from the object's global and uses the object's reflector to return a JSAutoCompartment value. It could look like `fn enter_compartment(object: &DomObject) -> JSAutoCompartment`, and we could fix up code in `components/script/dom/filereader.rs`, `components/script/dom/dedicatedworkerglobalscope.rs`, `components/script/dom/worker.rs` that currently uses `JSAutoCompartment::new` to use this instead.

Code: `components/script/compartments.rs`

**Comment by KaczuH** [comment]
@jdm I would like to try this issue. I just need a small explanation. Your proposed solution `enter_compartment`. Should it be a standalone function or method on one of structs in `components/script/compartments.rs`? Or maybe you had something else in mind?

**Comment by jdm** [comment]
I was imagining a standalone function.

**Comment by KaczuH** [comment]
@highfive assign me
