### ISSUE TITLE
libstd docs are missing from doc.servo.org

### ISSUE THREAD

**Issue by jdm** [servo/servo#23274]
Searching for std::vec does not find anything meaningful, for example.

**Comment by jdm** [comment]
And yet https://doc.servo.org/std/vec/struct.Vec.html exists, so maybe this is a problem with rustdoc?

**Comment by craftytrickster** [comment]
I believe this can be closed. I'm able to search for std::vec fine.

**Comment by jdm** [comment]
thanks!
