### ISSUE TITLE
Increase concurrent windows taskcluster jobs

### ISSUE THREAD

**Issue by jdm** [servo/servo#23278]
With the introduction of the windows x86 job, they appear to be sequential. There's no dependency between them; is there some limitation for the number of available windows workers that we need to change somewhere, @SimonSapin ?

**Comment by SimonSapin** [comment]
I’ve changed `maxCapacity` from 1 to 6 in https://tools.taskcluster.net/aws-provisioner/servo-win2016/edit. Feel free to tweak this (and `minCapacity` and `idleTimeoutSecs`) some more.

**Comment by jdm** [comment]
This appears to be working correctly. Thanks!
