### ISSUE TITLE
Intermittent reftest failures due to font selection choices

### ISSUE THREAD

**Issue by jdm** [servo/servo#23290]
Test:
<img width="414" alt="Screen Shot 2019-04-29 at 10 48 40 AM" src="https://user-images.githubusercontent.com/27658/56904505-5f561500-6a6c-11e9-8a5e-c0fe0d56ebae.png">
Reference:
<img width="380" alt="Screen Shot 2019-04-29 at 10 48 56 AM" src="https://user-images.githubusercontent.com/27658/56904519-6715b980-6a6c-11e9-9f16-4f97ef94878d.png">

https://searchfox.org/mozilla-central/source/testing/web-platform/tests/css/CSS2/syntax/at-charset-001.xht
https://searchfox.org/mozilla-central/source/testing/web-platform/tests/css/CSS2/syntax/at-charset-001-ref.xht
https://searchfox.org/mozilla-central/source/testing/web-platform/tests/css/CSS2/syntax/support/at-charset-001.css

It's not clear to me how this can happen, but it does.

**Comment by jdm** [comment]
<img width="803" alt="Screen Shot 2019-05-09 at 11 02 43 PM" src="https://user-images.githubusercontent.com/27658/57499686-95866680-72ae-11e9-87b5-49998821b68a.png">
<img width="803" alt="Screen Shot 2019-05-09 at 11 02 47 PM" src="https://user-images.githubusercontent.com/27658/57499689-97502a00-72ae-11e9-9073-1221a3de4c09.png">

**Comment by jdm** [comment]
This is a relatively common intermittent failure on taskcluster mac jobs; this will only get worse as we add more of them.

**Comment by jdm** [comment]
The info added to #23375 has yielded interesting output like the following:
```
"[2019-05-14T23:50:05Z INFO  gfx::font] couldn't find font for 'T' (54) in families [FontGroupFamily { font_descriptor: FontDescriptor { template_descriptor: FontTemplateDescriptor { weight: FontWeight(400.0), stretch: FontStretch(NonNegative(Percentage(1.0))), style: Normal }, variant: Normal, pt_size: 16px }, family_descriptor: FontFamilyDescriptor { name: Generic(Atom('serif' type=static)), scope: Any }, loaded: true, font: None }]"
```
I find this highly suspect!

**Comment by jdm** [comment]
I have a theory that this occurs when the macos font backend's FontHandle::new_from_template is called with a None pt_size argument. This chooses 0.0 for a point size, then FontTemplateData::ctfont instantiates the font with a point size of 0.1, but all queries for the font use 0.0 and won't find it. This could explain why the fallback behaviour is triggered.

**Comment by jdm** [comment]
This can happen if FontTemplate::instantiate is called, rather than FontContext::create_font, which happens in FontContext::descriptor.

**Comment by jdm** [comment]
Theory busted - we store the unclamped point size in the hashmap, not the clamped one :(

**Comment by jdm** [comment]
Still hitting this:
<img width="817" alt="Screen Shot 2019-10-03 at 4 31 12 PM" src="https://user-images.githubusercontent.com/27658/66161877-3decec80-e5fb-11e9-9a00-6f8fd0f52ad1.png">
<img width="807" alt="Screen Shot 2019-10-03 at 4 31 17 PM" src="https://user-images.githubusercontent.com/27658/66161882-3fb6b000-e5fb-11e9-9e25-033546022575.png">

**Comment by nox** [comment]
How come this is happening way more often all of a sudden?

**Comment by jdm** [comment]
Historically it seems to affect us in clusters of repeated failures Dunno why.

**Comment by mrobinson** [comment]
I suspect this is due to our incomplete support for the `@font-face` tag causing us to use the fallback list which is not in a deterministic order.

**Comment by mrobinson** [comment]
I think we can close this for now as we've addressed many sources of intermittency in the font backend and we are tackling more currently.
