### ISSUE TITLE
Infinite Hanging at "Environment Initialized for: x64"

### ISSUE THREAD

**Issue by kingoftheconnors** [servo/servo#23295]
On Windows 10, I'm trying to start servo and it hangs on `[vcvarsall.bat] Environment initialized for: 'x64'` FOREVER!

When using CTRL-C to interrupt, I get this traceback.
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Traceback (most recent call last):
  File "mach", line 96, in <module>
    main(sys.argv)
  File "mach", line 26, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "C:\Users\Connor\Documents\GitHub\servo\python\mach_bootstrap.py", line 273, in bootstrap
    _activate_virtualenv(topdir, is_firefox)
  File "C:\Users\Connor\Documents\GitHub\servo\python\mach_bootstrap.py", line 204, in _activate_virtualenv
    _process_exec([python, "-m", "pip", "install", "-I", "-r", req_path])
  File "C:\Users\Connor\Documents\GitHub\servo\python\mach_bootstrap.py", line 103, in _process_exec
    process.wait()
  File "C:\Python27\lib\subprocess.py", line 693, in wait
    _subprocess.INFINITE)
```

Why does servo run into a situation where it waits infinitely?

**Comment by jdm** [comment]
@kingoftheconnors What command are you running that triggers this?

**Comment by jdm** [comment]
Also, how long have you waited for more output?

**Comment by kingoftheconnors** [comment]
7 minutes at max so far. I'll let you know if it gets copiously high.

This happens on `mach.bat build` and `mach.bat check`
I haven't checked any others.

**Comment by kingoftheconnors** [comment]
Alright. For some reason it started working. My current theory is that the path hadn't updated on the command line, and closing and reopening it (sometime between now and four hours ago) did the trick.

Thank you for your concern and being so prompt!

**Comment by Seanmclem** [comment]
I needed to reference the path, `./mach.bat build --dev`

after about 5 minutes it passed the message, so I just had to be patient.
