### ISSUE TITLE
Support the new Japanese era (Reiwa) 

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#23314]
URL: https://reiwa-yet.glitch.me/

Bugzilla for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1543641

In Firefox Nightly:
<img width="1680" alt="FirefoxNightly" src="https://user-images.githubusercontent.com/6782666/57116424-02ba6900-6d90-11e9-821b-1653eb067127.png">

In Servo
<img width="1680" alt="Servo" src="https://user-images.githubusercontent.com/6782666/57116411-eb7b7b80-6d8f-11e9-9603-7c350c7b037b.png">

**Comment by KiChjang** [comment]
This looks like a JavaScript engine issue rather than a browser issue, since `Intl.DatTimeFormat` is defined in https://www.ecma-international.org/ecma-402/2.0/#sec-intl-datetimeformat-constructor. Closing as this can be supported by simply upgrading to the latest SM version.

**Comment by jdm** [comment]
Let's leave it open to track the fact that it's broken until we upgrade to a version that fixes it.

**Comment by CYBAI** [comment]
@KiChjang Thanks for pointing it! What @jdm said is what I think :)

**Comment by saschanaz** [comment]
Seems this is fixed.

**Comment by jdm** [comment]
<img width="249" alt="Screen Shot 2019-07-05 at 10 40 09 PM" src="https://user-images.githubusercontent.com/27658/60750405-df6d8f00-9f75-11e9-9db7-e673ced0740b.png">
Not in the latest macOS nightly build that I tried.

**Comment by saschanaz** [comment]
Oops, I tried this on Windows and it says Yes.

**Comment by atouchet** [comment]
I tried it on Windows and it says Yes for me as well briefly before the page crashes in the latest nightly build.

**Comment by saschanaz** [comment]
@atouchet Same here, it's #23531.

**Comment by atouchet** [comment]
I can get this page to load without crashing now.

![](https://i.imgur.com/cesom7q.png)

@jdm are you using a release with the latest SpiderMonkey updates?

**Comment by CYBAI** [comment]
Works for me on macOS 10.14.5 too!

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/6782666/61990893-d7d86c00-b083-11e9-9378-4c7c228f59b7.png">

I supposed it's fixed by smup at #23587 👀
Wait for @jdm 's confirmation to close this issue! 😄

**Comment by CYBAI** [comment]
I just tried to go through the bugzilla and the [comment 23](https://bugzilla.mozilla.org/show_bug.cgi?id=1543641#c23) said it's fixed for version 67 and our #23587 was for smup 67.

So, I believe it's fixed for Servo as well! Let me close this issue then 😄 Thanks!
