### ISSUE TITLE
WPT sync error?

### ISSUE THREAD

**Issue by gterzian** [servo/servo#23317]
Is there a reason why this PR is still marked as "do not merge yet"? https://github.com/web-platform-tests/wpt/pull/15224

I think there was an error syncing when the PR here merged, see https://github.com/servo/servo/pull/22802#issuecomment-471649694

Maybe that's the problem?

**Comment by jdm** [comment]
Shoot, I indeed missed the sync error reported in the servo PR.

**Comment by jdm** [comment]
Fixed by manually merging the remote PR after verifying that the contents were identical.
