### ISSUE TITLE
XMLHttpRequest resource timing information uses incorrect URL

### ISSUE THREAD

**Issue by jdm** [servo/servo#23329]
Rather than returning the XHR's global's URL, it should be returning the URL that was used to create the XHR. We can store another ServoUrl member in XHRContext and return that from the `resource_timing_information` method.

Code: `components/script/dom/xmlhttprequest.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/resource-timing/`

**Comment by sreeise** [comment]
Hey @jdm I can work on this if that is ok.

@highfive: assign me
