### ISSUE TITLE
Performance interface's timing member should be an attribute

### ISSUE THREAD

**Issue by jdm** [servo/servo#23330]
Per https://w3c.github.io/navigation-timing/#extensions-to-the-performance-interface we should have a `timing` attribute in our WebIDL interface, not a method.

Code: `components/script/dom/webidls/Performance.webidl`, `components/script/dom/performance.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/navigation-timing/`

**Comment by garyemerson** [comment]
@highfive: assign me

Just got setup to build the project, excited to contribute! Looks like just the Performance.webidl would need to be changed, right? I'll try that out and see if it builds.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/23367 had a patch that looked good, but needed some test results to be updated before the author disappeared.

**Comment by bcamp** [comment]
@highfive: assign me

Looks like #23332 went in and the test no longer needs updating.

**Comment by jdm** [comment]
There was a partial solution in #23773, but it exposed some issues which need to be resolved per my latest comment there.

**Comment by stephenmuss** [comment]
I'd be happy to have a crack.

@highfive: assign me

**Comment by jdm** [comment]
Unassigning due to lack of activity.

**Comment by tomasdivito** [comment]
I will take a look :)

@highfive: assign me

**Comment by shnmorimoto** [comment]
@highfive: assign me
