### ISSUE TITLE
Implement worker origin member of WorkerLocation

### ISSUE THREAD

**Issue by jdm** [servo/servo#23331]
Spec: https://html.spec.whatwg.org/multipage/workers.html#dom-workerlocation-origin
Code: `components/script/dom/webidls/WorkerLocation.webidl`, `components/script/dom/workerlocation.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/workers/`

You can use `Location::origin` from `components/script/dom/location.rs` as a model for this.

**Comment by dralley** [comment]
@highfive: assign me

**Comment by dralley** [comment]
Actually, never mind, there's already a PR for this but it was never assigned : /  https://github.com/servo/servo/pull/23335

**Comment by jdm** [comment]
Yeah, sorry about that!
