### ISSUE TITLE
New mac taskcluster builders don't have gstreamer installed until first build completed

### ISSUE THREAD

**Issue by jdm** [servo/servo#23366]
servo-mac4 was added to the pool and was selected for a WPT job. It proceeded to crash on every test with this output:
```
  ▶ CRASH [expected PASS] /css/CSS2/positioning/abspos-overflow-003.xht
  │ 
  │ dyld: Library not loaded: /Users/worker/homebrew/opt/gst-plugins-bad/lib/libgstwebrtc-1.0.0.dylib
  │   Referenced from: /Users/worker/tasks/task_1557510542/repo/target/release/servo
  └   Reason: image not found
```
This is because it has not had homebrew installed, since that runs as part of the build task.

**Comment by jdm** [comment]
I worked around this by cancelling the WPT job and retrying the PR a couple times until the other builders were busy running tests and the new builder was able to claim a build job. This isn't really sustainable for the future as we add more builders, however.

**Comment by jdm** [comment]
And another interesting problem - when the new builder had a build job and set up homebrew, it installed gstreamer 1.16 while the other builders have gstreamer 1.14. This led to this error when an older machine tried to run tests:
```
  ▶ CRASH [expected OK] /eventsource/shared-worker/eventsource-url.htm
  │ 
  │ dyld: Library not loaded: /Users/worker/homebrew/opt/gst-plugins-bad/lib/libgstwebrtc-1.0.0.dylib
  │   Referenced from: /Users/worker/tasks/task_1556974932/repo/target/release/servo
  └   Reason: Incompatible library version: servo requires version 1601.0.0 or later, but libgstwebrtc-1.0.0.dylib provides version 1405.0.0
```

**Comment by SimonSapin** [comment]
For dependencies not being installed, should we have a `Brewfile` for building and another for running Servo? `./mach bootstrap-android` does something similar.

Re incompatible versions, does Homebrew support version pinning? (Or installing older versions at all?)

**Comment by jdm** [comment]
Homebrew does not have a way to specify older versions to install. The only way I can think of is to pin a specific base revision of the Homebrew core repository and check that out before starting the Homebrew installation.

**Comment by jdm** [comment]
This was fixed.
