### ISSUE TITLE
Permissions prompt support in Servo

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#23376]
Currently Servo cannot trigger permissions prompts. This is going to be necessary to be able to expose `getUserMedia()` and some of the XR stuff.

This will likely be somewhere in the embedder API.

Ideally, for `getUserMedia()` we can have a "pick your device" menu as well (may need a separate API)

cc @paulrouget

**Comment by jdm** [comment]
There is some overlap with the work for https://github.com/servo/servo/issues/23057, too.

**Comment by paulrouget** [comment]
Where is the code that scan for media devices? In Servo or in the embedder?

**Comment by Manishearth** [comment]
It's currently in Gstreamer. This can be changed to make it an embedder hook.

The primary goal of this issue is to have some ability to throw up a permissions prompt, we can extend that for `getUserMedia()`'s media selection later. I bring it up now so that whatever we design can be extended with selection dropdowns/etc.

**Comment by gatoWololo** [comment]
Hello,

I started looking at this issue. I followed jdm's link to #23057, I see how #20428 and #20429 moved use of tinyfiledialogs to the embedder.

I saw `components/script/dom/permissions.rs` has the functions `permission_request(...)` and `prompt_user(...)`. Is this not the

> Currently Servo cannot trigger permissions prompts

that this issue refers to? If so, what's the difference and where should it go? Thanks.

**Comment by jdm** [comment]
Manish's statement wasn't completely correct. Servo does partially support the DOM Permissions API, but only displays prompts for bluetooth-related permissions checks and only on Linux. We will need to add DOM Permissions API integration into Servo's GetUserMedia implementation, but first we should create the right infrastructure for that by fixing #23057, which is really the issue that I intended to send you.

**Comment by gatoWololo** [comment]
Cool, I'll look at #23057 then.

**Comment by Manishearth** [comment]
We're going to need hooks for permissions prompts in embedder stuff for Hololens, at least cc @paulrouget 

Immersive mode is supposed to trigger permissions prompts in many cases.

**Comment by paulrouget** [comment]
I like the prompt service we have in Gecko: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/windowwatcher/nsIPromptService.idl

Would that work for your use cases (getUserMedia and immersive mode)?

**Comment by Manishearth** [comment]
Probably yeah. We'd need some kind of embedder API and a native implementation for the hololens.

**Comment by paulrouget** [comment]
WIP https://github.com/paulrouget/servo/tree/prompt
Still need to figure out how to properly block on the dialogs for the UWP port.
