### ISSUE TITLE
Support type=module script element

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#23370]
whatwg/html#443

Spec: Step 24.6 of https://html.spec.whatwg.org/multipage/#prepare-a-script

Gecko initialization for module hooks
https://searchfox.org/mozilla-central/source/dom/script/ScriptLoader.cpp#990-1006

**Comment by CYBAI** [comment]
@jdm While reading how Gecko implements `module` scripts, I found Gecko will do a module hooks initialization at https://searchfox.org/mozilla-central/source/dom/script/ScriptLoader.cpp#141 . I think we should have a top level module hook in following function? Thanks.

https://github.com/servo/servo/blob/965f57e3f8011dd7bdc61b438f95eeb87748319d/components/script/script_runtime.rs#L345

**Comment by jdm** [comment]
Yes, that seems reasonable to me.
