### ISSUE TITLE
README update for macOS

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#23394]
seems we need this now due to recent commits
```
brew bundle install --file=etc/taskcluster/macos/Brewfile-gstreamer 
```

**Comment by tigercosmos** [comment]
@CYBAI  could you double check about this?

**Comment by CYBAI** [comment]
I think it's

```
brew bundle install --file=etc/taskcluster/macos/Brewfile
```

which is already in [README](https://github.com/servo/servo#macos) now 🤔

Do you get any issue while installing with that command? 👀

**Comment by tigercosmos** [comment]
`etc/taskcluster/macos/Brewfile` doesn't include `gstreamer`, which is moved to `etc/taskcluster/macos/Brewfile-gstreamer`

**Comment by jdm** [comment]
Yes, we need to update the instructions in the way you recommend.

**Comment by tigercosmos** [comment]
It would be an easy one.

**Comment by CYBAI** [comment]
> `etc/taskcluster/macos/Brewfile` doesn't include `gstreamer`, which is moved to `etc/taskcluster/macos/Brewfile-gstreamer`

Oops, I didn't pull the latest code so I didn't notice that 😂 Thanks for catching it!

**Comment by jdm** [comment]
Rather than having someone else update the readme, I'm going to go ahead and do it.
