### ISSUE TITLE
Generate linux bundle for Gstreamer 1.16

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#23391]
part of #23390

Keeping track of the work necessary to build GST 1.16

**Comment by Manishearth** [comment]
Going off of the steps in https://github.com/servo/servo/wiki/How-to-generate-GStreamer-binaries-for-CI:

Changes:

 - Do not install libnice
 - Install ffmpeg 4.1.1 instead of 3.2
 - command is `
meson  -Dpython=disabled -Dlibav=enabled -Dugly=disabled -Dbad=enabled -Ddevtools=disabled  -Drtsp-server=disabled -Domx=disabled -Dvaapi=disabled -Dsharp=disabled -Dintrospection=disabled -Dgst-plugins-bad:webrtc=disabled -Dgst-plugins-bad:iqa=disabled --prefix=/opt/gst build --libdir=lib`

Todo: figure out how to get webrtc to work

**Comment by Manishearth** [comment]
Okay, the above steps work aside from webrtc. @ferjm Do you think we should go ahead with this and start the migration, or wait for me to figure out webrtc?

**Comment by Manishearth** [comment]
The binaries (without webrtc) are at http://servo-deps.s3.amazonaws.com/gstreamer/gstreamer-1.16-x86_64-linux-gnu.20190514.tar.gz

**Comment by Manishearth** [comment]
WIP webrtc build command:

```
meson  -Dpython=disabled -Dlibav=enabled -Dugly=disabled -Dbad=enabled -Ddevtools=disabled  -Drtsp-server=disabled -Domx=disabled -Dvaapi=disabled -Dsharp=disabled -Dintrospection=disabled  -Dgst-plugins-bad:iqa=disabled -Dgst-editing-services=disabled -Dlibnice=enabled -Dgst-plugins-bad:webrtc=enabled -Dlibnice:crypto-library=openssl -Dlibnice:tests=disabled --prefix=/opt/gst build --libdir=lib 
```

**Comment by Manishearth** [comment]
It worked!

gst_editing_services still doesn't disable, but that's fine

**Comment by Manishearth** [comment]
New steps:

 - Do not install libnice
 - Install ffmpeg 4.1.1 instead of 3.2
 - After running `meson`, but before running `ninja`, `cd subprojects/gst-plugins-base` and `git cherry-pick 5f19e83f14bf29a31b76684181396080aa228113`. Unnecessary once that's backported
 - command is `meson  -Dpython=disabled -Dlibav=enabled -Dugly=disabled -Dbad=enabled -Ddevtools=disabled  -Drtsp_server=disabled -Domx=disabled -Dvaapi=disabled -Dsharp=disabled -Dintrospection=disabled  -Dgst-plugins-bad:iqa=disabled -Dgst-editing-services=disabled -Dlibnice=enabled -Dgst-plugins-bad:webrtc=enabled -Dlibnice:crypto-library=openssl -Dlibnice:tests=disabled --prefix=/opt/gst build --libdir=lib`


It's published at http://servo-deps.s3.amazonaws.com/gstreamer/gstreamer-1.16-x86_64-linux-gnu.20190514-webrtc.tar.gz

**Comment by Manishearth** [comment]
Deploying at https://github.com/servo/saltfs/pull/961

**Comment by Manishearth** [comment]
Ah, it's `-Dges` now

**Comment by Manishearth** [comment]
Couple tips for future upgrades:

 - `meson configure` gives you a nice list of options
 - the meson build log is long, but save it. If a package fails to build, check _why_ meson wanted to build the package (from the log). In some cases this may involve reading through meson.build files. Almost all of my problems were solved by this kind of exploration

**Comment by Manishearth** [comment]
Once https://github.com/servo/servo/pull/23377 passes I'll close this issue and move all my findings to the wiki page

**Comment by Manishearth** [comment]
Wiki page updated. It also now uses Xenial instead (trusty also has old vpx binaries, and I don't want to go down that rabbit hole if we're not using trusty on CI anyway)

**Comment by ferjm** [comment]
If we are not generating the binaries for Trusty anymore, we need to move servo-media CI to Xenial as well.

**Comment by Manishearth** [comment]
Good point, we should do that
