### ISSUE TITLE
In Websocket, use IPC router as opposed to a thread for each websocket

### ISSUE THREAD

**Issue by gterzian** [servo/servo#23408]
When a websocket is [created](https://github.com/servo/servo/blob/ce93e017c65ba8e987226c843df7fc923af5957a/components/script/dom/websocket.rs#L145), a dedicated thread is spawned to handle incoming messages from [the resource thread](https://github.com/servo/servo/blob/c449cbb8eacd2e42b450a2a06af4d94bda2bc103/components/net/resource_thread.rs).

Instead an [`ipc_channel::router::ROUTER`](https://github.com/servo/ipc-channel/blob/dde1461af315dd02c3788b5fce01e8cca02b50f2/src/router.rs) could be used, which will result in a single thread being used to route all messages for all websockets used in a script-thread, as opposed to one per websocket. 

An example of how that is done is found in the [event-source](https://github.com/servo/servo/blob/ce93e017c65ba8e987226c843df7fc923af5957a/components/script/dom/eventsource.rs#L568), although using a `NetworkListener` is probably uncessary, instead the work done inside the closure passed [here](https://github.com/servo/servo/blob/ce93e017c65ba8e987226c843df7fc923af5957a/components/script/dom/websocket.rs#L219) could be done in the closure passed to the router. 

There might be a reason why the websocket is not using the router, but I can't see it for now. It's worth a try...

**Comment by jdm** [comment]
To test the changes, run `./mach test-wpt tests/wpt/web-platform-tests/websocket`. There should be no change in behaviour before and after.

**Comment by TheOriginalAlex** [comment]
I'd like to take this on as a first ticket.

**Comment by gterzian** [comment]
@bors-serve assign TheOriginalAlex 

@TheOriginalAlex Let us know how it goes!
