### ISSUE TITLE
Why does servo depend on opengl32.dll

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#23418]
I'm trying to understand why libsimpleservo depends on opengl32.dll.

So far, I identified 2 reasons:
- skia depends on glutin which depends on opengl
- offscreen_gl_context links with opengl

But even if I remove glutin from skia and disable the link to opengl in offscreen_gl_context, I still end up with a dependency on opengl32.dll.

I'm missing something, any clue?

/cc @jdm

**Comment by paulrouget** [comment]
In target/debug/build/winapi-ad7f77e1676cc694/output, I see:

```
cargo:rustc-link-lib=dylib=opengl32
```

Any idea how I can work around that?

**Comment by jdm** [comment]
It looks like it's already turned off for https://github.com/retep998/winapi-rs/blob/a7ef2bca086aae76cf6c4ce4c2552988ed9798ad/build.rs#L442-L445 . Presumably when we're using the forthcoming UWP compilers we'll want to disable it for that too. I think we'll just to suppress it manually in the short term.

**Comment by paulrouget** [comment]
skia, offscreen gl, and winapi link to OpenGL.
