### ISSUE TITLE
Implement <form>.requestSubmit()

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#23417]
whatwg/html#4597
web-platform-tests/wpt#16743

Firefox Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1552301

**Comment by pshaughn** [comment]
#24617 should come first, so we have a submitter field available to populate.

**Comment by pshaughn** [comment]
24617 is fixed so this should be pretty simple now.

**Comment by jdm** [comment]
More specifically, the [requestSubmit](https://html.spec.whatwg.org/multipage/forms.html#the-form-element:dom-form-requestsubmit) API was added to the specification, and its desired behaviour is documented [here](https://html.spec.whatwg.org/multipage/forms.html#dom-form-requestsubmit). https://github.com/web-platform-tests/wpt/pull/16743 added tests for the new API that Servo currently fails.

To fix this issue, we need to:
* add the missing IDL from the spec to component/script/dom/webidls/HTMLFormElement.webidl
* implement the missing method in HTMLFormElementMethods in components/script/dom/htmlformelement.rs based on the description from the specification using the existing form submission infrastructure in that file
* verify that the failing tests no longer fail with the changes, and [update the test expectations](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) to ensure they continue to pass in the future

**Comment by muodov** [comment]
I'd like to try fixing this. I have experience with WPT, and we've recently implemented `requestSubmit()` in a JS sandbox at work, so I have some understanding of how it should work.
But I'm new to Servo and Rust, so it might take some time. The steps described by @jdm seem clear though.
I'll try to hack on this tomorrow.

**Comment by jdm** [comment]
Please ask questions if there are any surprises!

**Comment by muodov** [comment]
@highfive: assign me
