### ISSUE TITLE
de-dupe winapi

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#23430]
Servo uses 2 version of winapi. 0.2 and 0.3.

We need to dedupe it. It doesn't look trivial.

**Comment by Eijebong** [comment]
It would be trivial if mio released a new version... We've been waiting for more than a year now.

**Comment by jdm** [comment]
@paulrouget If we need to dedupe it for the Hololens work, go ahead and make a fork of mio and add a Cargo replacement that uses it.

**Comment by Eijebong** [comment]
If you need anything else, just ping me (kind of got some experience with that ;))

**Comment by paulrouget** [comment]
I'll give it a try tomorrow. I think there's a bit more than just mio.

**Comment by atouchet** [comment]
I believe iovec and mio are the main blockers. It would also help to merge #23405 to get rid of the term dependency.

**Comment by Eijebong** [comment]
Yeah mio is the main blocker but then you'll probably have to fix tokio stuff too. I did all the preparation work last year hoping for a mio release (which was promised Q1 2018). I think you could use mio master's branch which does have breaking changes for the next version now, but I'm not sure what kind of impact it'll have over the rest of the deps.

**Comment by Eijebong** [comment]
#23449

**Comment by paulrouget** [comment]
Fixed by #23449
