### ISSUE TITLE
Use raqote for 2D canvas rendering

### ISSUE THREAD

**Issue by pylbrecht** [servo/servo#23431]
While working on #22957, @jdm mentioned the possiblity to use [https://github.com/jrmuizel/raqote](https://github.com/jrmuizel/raqote) as a canvas rendering backend.
As stated in [https://github.com/servo/servo/issues/22957#issuecomment-493991851](https://github.com/servo/servo/issues/22957#issuecomment-493991851), this issue is for tracking progress of the conversion to raqote.

Remaining missing pieces:
* [x] LinearGradient/RadialGradient (https://docs.rs/raqote/0.6.4/raqote/struct.Gradient.html)
* [x] ColorBurn support (https://github.com/jrmuizel/raqote/issues/81)
* [x] Path::transformed_copy_to_buiilder (https://github.com/jrmuizel/raqote/issues/82)
* [x] Shadows (https://github.com/jrmuizel/raqote/issues/83)
* [x] `snapshot` API (might just be `SourceSurface::Raqote(self.snapshot_data_owned())`
* [x] `ellipse` path API

**Comment by pylbrecht** [comment]
The current approach is to temporarily make the rendering backend generic, so it can be replaced step by step with successful builds in between. I'm just too anxious about replacing such a huge chunk of code all at once, so @jdm helped me out with the idea of making the backend generic for refactoring purposes.
This is my road map so far:
- [x] [add a `GenericDrawTarget` trait](https://github.com/pylbrecht/servo/commit/b1cd1e89a53b72ba6ffd957b48a51cb22563dcd0)
- [x] [`impl GenericDrawTarget for azure_hl::DrawTarget`](https://github.com/pylbrecht/servo/commit/a450144f3259a5d2a8e60d8521eb6f414d61b0b8)
- [x] [implement a `GenericPathbuilder`](https://github.com/pylbrecht/servo/commit/b639b1dfc20996587fdcc0a3feac920543eafc01)
- [x] [Make `CanvasPaintState` use generic types](https://github.com/pylbrecht/servo/commit/012e55056ef6eb609dd77f58c00c5d4b82dd809a)
- [ ] Make `CanvasData` use `GenericDrawTarget`
- [ ] `impl GenericDrawTarget for raqote::DrawTarget`
- [ ] ...

Currently the build errors due to making `CanvasData` use `GenericDrawTarget` instead of `azure_hl::DrawTarget` keep me on my toes. Feels like I'm starting to *really* get to know Rust.

**Comment by pylbrecht** [comment]
I won't be making any progress this week, because I'm moving into a new appartment on Thursday and currently I'm like `loop { Box::new(stuff) }`.

**Comment by pylbrecht** [comment]
I'm back online and will continue working on this on the upcoming weekend.

**Comment by pylbrecht** [comment]
Unfortunately I could not continue hacking this weekend, because my new router is giving me a hard time denying outgoing ssh connections and I could not figure out why so far (I'm coding remotely on my vps, because building servo melts my Macbook Air). I'm confident I'm gonna win the battle against my provider's cheap hardware in upcoming week though. I'll keep you updated!

**Comment by pylbrecht** [comment]
Alright, thanks to @jdm's work it looks like I just have to replace all `unimplemented!()` in `components/canvas/raqote_backend.rs` with working code. This will keep me entertained for a while, but just for completeness: is there anything else?

**Comment by jdm** [comment]
I think it's that and giving real types to the Raqote variants in the various enums.

**Comment by pylbrecht** [comment]
Ah yeah, the enums. Thanks, I missed that!

**Comment by pylbrecht** [comment]
I'm afraid I have to step back from working on this for now. I'm in the final weeks of my thesis and it's eating up all my time and effort. I'm not happy leaving this in such an unfinished state, but my thesis has to come first.
So if anyone wants to continue working on this for the time being, I'm glad to hand it over. Otherwise I continue where I left off once my thesis is handed in (08/12/2019) or get my hands on another issue.

**Comment by pylbrecht** [comment]
I handed in my thesis on Monday and am now available again.
I see @Eijebong is working on this now (https://github.com/servo/servo/pull/23936). Am I free to look for another issue then?

**Comment by Eijebong** [comment]
If you want to continue working on this you can take it back from where I left it :) I'm probably not going to work on it for quite some time because of syn 1.0 anyway

**Comment by pylbrecht** [comment]
I just want to work on *any* issue, so I honestly don't mind. I'm on vacation until Sunday anyway, so I will look into your changes when I'm back. If I feel confident to take it from there, I'm happy to continue working on this. Otherwise I'm gonna pick something else. I'll drop a comment here in any case though.

**Comment by pylbrecht** [comment]
I will branch off of @Eijebong's latest changes and continue working on this starting this week.

**Comment by CYBAI** [comment]
Fixed by #23936

**Comment by Eijebong** [comment]
It's not really fixed, there's still lots of work on it

**Comment by CYBAI** [comment]
> It's not really fixed, there's still lots of work on it

Oops, sorry, let me reopen it!

**Comment by pylbrecht** [comment]
I think this got accidentally merged. There's still work to do!

**Comment by CYBAI** [comment]
> I think this got accidentally merged. There's still work to do!

Let's reopen it?

**Comment by pylbrecht** [comment]
Thanks, I'll open yet another PR. 😄

**Comment by pylbrecht** [comment]
I got my last two exams coming up, so I won't be able to work on this until next Monday.

**Comment by jdm** [comment]
Submitted https://github.com/jrmuizel/raqote/pull/87 for the missing path transform API.

**Comment by SimonSapin** [comment]
Is the raqote backend complete? I feel that this issue should maybe stay open until it passes WPT, or maybe even is enabled by default
