### ISSUE TITLE
Can't run macOS nightlies on macOS <10.13

### ISSUE THREAD

**Issue by jdm** [servo/servo#23432]
Trying to run the nightlies yields on macOS Sierra yields: "You have macOS 10.12.6. The application requires macOS 10.13 or later."

This is presumably caused by our TC mac builders running 10.13.6, and they are the machines that generate the nightly builds.

**Comment by Darkspirit** [comment]
Please wontfix?!

[10.12 Sierra](https://en.wikipedia.org/wiki/MacOS_Sierra)
> Support status: Partially supported. Extended support ends in **September 2019**.

[10.13 High Sierra](https://en.wikipedia.org/wiki/MacOS_High_Sierra) was released 2017 and supports 10 year old devices. Support ends next year.
> macOS High Sierra will run on the following Macintosh computers:
> iMac: Late 2009 or later
> MacBook: Late 2009 or later
> MacBook Pro: Mid 2010 or later
> MacBook Air: Late 2010 or later
> Mac Mini: Mid 2010 or later
> Mac Pro: Mid 2010 or later

> Support status: Partially supported. Extended support ends in September 2020.

**Comment by jdm** [comment]
I was unaware that 10.12's life was nearly over, and I am inclined to agree. I have upgraded my environment to 10.14.
