### ISSUE TITLE
Extract OS clipboard integration into embedding layer

### ISSUE THREAD

**Issue by jdm** [servo/servo#23440]
Rather than implicitly supporting the OS clipboard everywhere by creating a ClipboardContext in the constellation, this is really something that should be supported separately by each Servo embedder.

We should:
* remove the GetClipboardContents/SetClipboardContents constellation messages
* add GetClipboardContents and SetClipboardContents messages to `EmbedderMsg`
* make the code that uses the clipboard provider in `textinput.rs` use Window's `send_to_embedder` method instead
* add new methods for getting/setting the clipboard contents to `HostTrait`
* call these new methods from the embedding API's `handle_servo_events`
* make the code that processes the new embedder clipboard messages call these new methods
* move the constellation's `ClipboardContext` creation to the `Browser` structure
* handle the new embedder clipboard messages in the glutin port's `handle_servo_events` by using the stored `ClipboardContext`

Code:
* `components/script/clipboard_provider.rs`
* `components/script/textinput.rs`
* `components/constellation/constellation.rs`
* `components/embedder_traits/lib.rs`
* `components/script_traits/script_msg.rs`
* `ports/glutin/browser.rs`
* `ports/libsimpleservo/api/src.rs`

There are no automated tests for this; it's enough to manually test that copying and pasting inside of a `<input>` inside the desktop Servo build still works before and after these changes.

**Comment by mmiecz** [comment]
Hi, this looks like good first task to get to know Servo! @jdm can you assign this one to me, please?

**Comment by mmiecz** [comment]
I've been looking into this task for some time, and I am not really sure how to call `Windows` `send_to_embedder` method from `textinput.rs`.
Are there any similar use-cases where I can look and see how I should approach this?

**Comment by jdm** [comment]
@mmiecz The implementation of `send_to_embedder` sends a `ScriptMsg::ForwardToEmbedder` message to the constellation. The current implementation of the clipboard provider uses a channel to the constellation, so you should be able to send the ForwardToEmbedder message directly in clipboard_provider.rs instead.

**Comment by jdm** [comment]
@mmiecz Are you still working on this?

**Comment by mmiecz** [comment]
@jdm Yes, I’ve done the sending to embedder, and removing the constellation part, and the clipboard is functional. I am not at home right now, but I will issue a PR soon
