### ISSUE TITLE
Gstream version check MacOS

### ISSUE THREAD

**Issue by hrvolapeter** [servo/servo#23447]
This is not entirely problem of Servo but `pkg-conf`.

The build script uses following code to verify version:
```
pkg-config --atleast-version=1.12 gstreamer-1.0 
```
However this fails even if pkg-config reports version 1.16 see:
```
pkg-config gstreamer-1.0 --modversion
```
and output 
```
1.16.0
```

The expected behavior is for pkg-config to end without error. I went around the problem by disabling the check in the bootstrap.py file

Versions:
gstreamer: 1.16.0
pkg-config: 0.29.2
MacOS: 10.14.4

**Comment by jdm** [comment]
This is a known issue with the version of libffi that is required by GStreamer 1.16. You need to follow the instruction at https://github.com/servo/servo#note-please-make-sure-the-required-pkg_config_path-environment-variable-is-set-the-same-as-the-one-provided-from-brew-info-libffi-check-this-comment-for-more-details .

**Comment by mrobinson** [comment]
I think we can close this because we no longer use Homebrew GStreamer on MacOS.
