### ISSUE TITLE
Embedding Servo without JavaScript

### ISSUE THREAD

**Issue by skyne98** [servo/servo#23450]
Hey there, everyone!

I have a question about embedding Servo with a specific use-case in mind. Is it possible with the current APIs to fully exclude the JavaScript engine and use internal APIs for Servo to be used as a GUI framework of sorts? I think Servo already has a lot going for it in the HTML and CSS support land, and directly using familiar HTML5 and DOM APIs should make it very approachable and easy to use.
Also, in theory, excluding JavaScript all together should reduce the memory usage for the application that would want to use it as a frontend. This will make Servo sort of like `Electron` for the Rust ecosystem.

Have you thought about such a use-case?
Thank you for your time!

**Comment by jdm** [comment]
This is a use case that has been proposed before, but it's not one that we are spending any effort to support. The JS engine is deeply tied into our DOM implementation.

**Comment by skyne98** [comment]
@jdm thanks for you response! What do you think about how hard will it be to try to decouple the APIs from a specific langauge / environment, making them available from pure rust?
I expected it to be like this from the very beginning, as there should have been some plans about changing the JS engine to something else in the future. Maybe a pure rust alternative? This would have required decoupling.
Also, it would be such a waste of available tech for the whole of rust community, if it won't ever be available from rust directly.

**Comment by jdm** [comment]
When I say the JS engine is tied into Sevro's DOM, I mean that the memory safety strategy for the DOM representation relies on the presence of a JS engine garbage collector in order to free the memory allocated by Rust for DOM objects. Disentangling the GC from from the DOM is not something we as a team are going to spend any time on.
