### ISSUE TITLE
Make it so that Skia, on Windows, can use egl, not wgl

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#23466]
Maybe a feature.

**Comment by jdm** [comment]
Looking at how we use Azure and Skia, I don't actually think we rely on the GL code at all. I think we can add a cargo feature to Azure and remove Skia from the build entirely.

**Comment by jdm** [comment]
This should be addressed by https://github.com/servo/skia/pull/177 and https://github.com/servo/rust-azure/pull/300.

**Comment by Darkspirit** [comment]
In Firefox, SkiaGL is disabled, and even forbidden for WebRender: https://hg.mozilla.org/mozilla-central/rev/e79c7b512fd6

**Comment by jdm** [comment]
New plan, given the issues in servo/rust-azure#300: I'm doing enough work for #23451 to allow removing Azure entirely from the build by enabling a Cargo feature when building Servo. This will allow us to quickly make progress in our UWP builds without having to wait for the complete canvas reimplementation to occur.

**Comment by jdm** [comment]
Fixed by removing all trace of skia when building with `--features raqote_backend`.
