### ISSUE TITLE
unresolved import `webrender_api::DevicePixel`

### ISSUE THREAD

**Issue by zaynkorai** [servo/servo#23474]
Trying to build Servo on Ubuntu(Debian)
./mach build --dev

facing following issue

```error[E0432]: unresolved import `webrender_api::DevicePixel`
  --> components/style_traits/lib.rs:37:9
   |
37 | pub use webrender_api::DevicePixel;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `DevicePixel` in the root```

```warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.66.0 (https://github.com/servo/mozjs?rev=e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9#e21c05b4)```

**Comment by jdm** [comment]
Did you change the version of webrender that is use by servo?

**Comment by zaynkorai** [comment]
nope I haven't touched anything. just following official documentation

**Comment by zaynkorai** [comment]
nope I haven't touched anything. just following official documentation
resolved that issue in my case, just updated the gcc version.
But now while at the end of compilation
```
Compiling servo v0.0.1 (/home/zayn/rus/servo/ports/glutin)
Building [=====================================================> ] 635/636: servo(bin)
```


### its failing with following error


```error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" ```

**Comment by jdm** [comment]
Can you [gist](https://gist.github.com/) the full output?

**Comment by zaynkorai** [comment]
here is [gist](https://gist.github.com/zaynkorai/f225ef23bbf14eb24757f157cbdda6d5#file-servo-logs-output) output

**Comment by CYBAI** [comment]
Looks like this is related to #21970.

Could you check the workaround from https://github.com/servo/servo/issues/21970#issuecomment-493589603 or https://github.com/servo/servo/issues/21970#issuecomment-467798721 ?

Btw, due to duplicate with #21970 , let's close this one and track issue there.

Thanks for reporting issue! :)
