### ISSUE TITLE
Make prepare_for_composite return void

### ISSUE THREAD

**Issue by jdm** [servo/servo#23492]
It's declared to return bool, but all implementations return true. This means that the code that checks whether it returns false in compositor.rs is unused.

Code: `components/compositing/compositor.rs`, `components/compositing/windowing.rs`, `ports/glutin/headed_window.rs`, `ports/glutin/headless_window.rs`, `ports/libsimpleservo/api/src/lib.rs`

**Comment by oneturkmen** [comment]
@highfive: assign me

**Comment by oneturkmen** [comment]
@jdm, will start on this in a few days, right after #22854 (WIP).
