### ISSUE TITLE
Implement various checks on the Location setters

### ISSUE THREAD

**Issue by gterzian** [servo/servo#23522]
Spec: https://html.spec.whatwg.org/multipage/history.html#location

See all attributes that say "Can be set, to navigate to the given URL.". 

Code: See all the `Set_` methods at https://github.com/servo/servo/blob/7a5ce048d2e6740c91187c12abebce132f90bfaa/components/script/dom/location.rs#L78

As well as `set_url_component` which is used by those methods: https://github.com/servo/servo/blob/7a5ce048d2e6740c91187c12abebce132f90bfaa/components/script/dom/location.rs#L45

Currently failing tests(and maybe others):
- https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter.html.ini
- https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html.ini
- https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken-weird.html.ini

And the actual tests are found in https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/html/browsers/history/the-location-interface

A start was made at https://github.com/servo/servo/pull/23368/files#diff-45df5e6ab4c1d79fae956506be147b62R244

and https://github.com/servo/servo/pull/23368/files#diff-c1196726ff21e3563c663b049214dafeL21

Note the only gotcha is that the `ServoUrl` contains an `Arc`, so you can't manipulate it directly when you do the initial parse to then perform the check, as that will actually change the url of the window. So instead you'll need to get a copy, as is for example done at https://github.com/servo/servo/pull/23368/files#diff-45df5e6ab4c1d79fae956506be147b62R244 (or you need to perform the checks without manipulating the current url)

**Comment by gterzian** [comment]
As a bonus you can also return a security error when the spec says to, see for how that is done:

https://github.com/servo/servo/blob/d180f76011a4eedfe3be1776b78c1fd55d7ace52/components/script/dom/location.rs#L61

**Comment by braddunbar** [comment]
I'd like to work on this!

**Comment by gterzian** [comment]
Thanks, let us know how it goes! @braddunbar

**Comment by gterzian** [comment]
@braddunbar How is this going? let us know if you have any questions, you can also just open the PR with a work in progress and ask questions from there...

**Comment by braddunbar** [comment]
Good! I’ll send a pull this weekend.

**Comment by jdm** [comment]
There was a PR that was just missing some specification link comments in #23670, then the author stopped responding.

**Comment by UxioAndrade** [comment]
@jdm Hi, I would like to work on this. Do you think this would be a nice issue for a first contribution?

**Comment by gterzian** [comment]
@UxioAndrade Absolutely! (Sorry for answering in lieu of @jdm)

If you look at https://github.com/servo/servo/pull/23670, you can see that most of the work has already been done(thank you @braddunbar ), and there are just a few last comments that need to be addressed. 

If it's not clear what those last comments are, let us know.

**Comment by UxioAndrade** [comment]
@gterzian Great, thank you!

**Comment by utsavoza** [comment]
Hey @gterzian @UxioAndrade, is it ok for me to take up this issue if we are not making progress on this currently?

**Comment by gterzian** [comment]
Yes it would be great to finally close this one, there is not much work left I think(see the open PR). Perhaps give @UxioAndrade a couple of days to respond? In any case, there is always more work to do on this project!

**Comment by utsavoza** [comment]
Sure.

**Comment by gterzian** [comment]
For posterity, I think the `easy less` label was a bit of an understatement, since the spec is actually a bit complicated.
