### ISSUE TITLE
Loading github.com crashes Servo 

### ISSUE THREAD

**Issue by atouchet** [servo/servo#23531]
Steps to reproduce:

1. Load https://github.com/ in Servo.
2. The browser will crash before loading the page.

Tested with the latest nightly build in Windows 10. I'm not sure when this behaviour started happening.

**Comment by dralley** [comment]
Works for me, on Linux, commit 4c776f33d407c1

Possibly Windows-specific, or maybe it's been fixed already.

**Comment by atouchet** [comment]
I retested this with the 2019-06-11 Windows nightly build and was still able to reproduce the crash.

**Comment by mateon1** [comment]
I can confirm this crash on the latest Windows build.
Servo closes with a segfault when visiting some sites, it doesn't print any backtrace, and `RUST_LOG=DEBUG` is unhelpful.

Tested sites:
github.com - crashes on load
reddit.com - crashes on load
google.com - crashes on search
news.ycombinator.com - does not crash

```
matin@NIX MSYS /c/Program Files/Mozilla Research/Servo Tech Demo
$ ./servo https://reddit.com/
Segmentation fault

matin@NIX MSYS /c/Program Files/Mozilla Research/Servo Tech Demo
$ ./servo https://google.com/
[2019-06-15T10:58:50Z ERROR script::dom::bindings::error] Error at https://www.google.com/:300:1418 document.f.q is undefined
[2019-06-15T10:58:56Z ERROR script::dom::bindings::error] Error at https://www.google.com/:2:1 q is not defined
Segmentation fault

matin@NIX MSYS /c/Program Files/Mozilla Research/Servo Tech Demo
$ ./servo --version
Servo 0.0.1-09f9273b2
```
(commit 09f9273b2)

**Comment by mateon1** [comment]
Okay, so I just spent most of the hour manually reducing a saved reddit.com page to a smaller testcase, after painfully working through webpack requires, snipping and substituting tons of code, I managed to reduce it to a single JS call...

```html
<script>
Object.getOwnPropertyNames(window)
</script>
```

The above testcase crashes the current Windows nightly with a segfault.

**Comment by jdm** [comment]
I suspect this is a regression from https://github.com/servo/servo/pull/23163.

**Comment by jdm** [comment]
I can reproduce a crash in the nightly build, but it takes a surprising amount of time to manifest.

**Comment by jdm** [comment]
Sigh. Can't use a debug-mozjs build on Windows; can't reproduce the crash on non-Windows.

**Comment by saschanaz** [comment]
![image](https://user-images.githubusercontent.com/3396686/60402703-091d6380-9bce-11e9-9d44-43d133be1476.png)

Somehow `symbol->description()` points to the wrong address.

**Comment by jdm** [comment]
Also observed when trying to search for anything from the Google homepage.

**Comment by atouchet** [comment]
This appears to be fixed now.

**Comment by jdm** [comment]
This was fixed by https://github.com/servo/servo/pull/23852.
