### ISSUE TITLE
DomRefCell<T> already borrowed: BorrowMutError when handling execution of a script in WebDriver

### ISSUE THREAD

**Issue by georgeroman** [servo/servo#23535]
When processing an execute script command with `window.open()` as the target script (`curl -v -X POST -d '{"script": "window.open()"}' "http://localhost:7002/session/$SESSIONID/execute/sync"`), the WebDriver server panics with the following error:

`DomRefCell<T> already borrowed: BorrowMutError (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at src/libcore/result.rs:999)`

This is where the script execution is handled: https://github.com/servo/servo/blob/a634f0502417421c78f3d05e493a12f0b19d83a0/components/script/webdriver_handlers.rs#L89

**Comment by georgeroman** [comment]
It looks like this only happens when running servo in headless mode.

**Comment by georgeroman** [comment]
I did some debugging and I've found this:
```
#18 0x000055555a1cf4ed in core::result::unwrap_failed (msg=..., error=...) at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/macros.rs:18
#19 0x0000555557e83bc8 in core::result::Result<T,E>::expect (self=..., msg=...) at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/result.rs:827
#20 0x00005555574ce2fd in script::dom::bindings::cell::DomRefCell<T>::borrow_mut (self=0x7fff98bfc220) at components/script/dom/bindings/cell.rs:86
#21 0x000055555952dc53 in script::script_thread::ScriptThread::load (self=0x7fff98bfc220, metadata=..., incomplete=...) at components/script/script_thread.rs:2964
```
This is where the panic happens:
https://github.com/servo/servo/blob/8f11b52d9a80a51ddf80212817b87efc20bef8d6/components/script/script_thread.rs#L2964-L2966

**Comment by jdm** [comment]
Yes, that does look like the cause.
