### ISSUE TITLE
Too many share libs on certain android devices.

### ISSUE THREAD

**Issue by aydinkim** [servo/servo#2359]
There is an error on certain devices. (more specifically, Odroid-q2, hardkernel. android 4.1.1, "for developer" device like Raspberry Pi)

12-19 08:05:06.505: E/HAL(2409): Cannot load library: link_image[1891]:  1248 could not load needed library 'libion.so' for 'gralloc.odroidq2.so' (alloc_info[271]:  1248 too many libraries when loading libion.so)

It looks like that the number of shared libraries is exceeded the android's OS limitation.
http://www.phonesdevelopers.com/1710076/

What should we do for this?

**Comment by larsbergstrom** [comment]
We statically link everything now.
