### ISSUE TITLE
[hololens] ServoApp_TemporaryKey.pfx can't be used

### ISSUE THREAD

**Issue by jdm** [servo/servo#23619]
When trying to create an app package from this project, I get this error: "Cannot import the key file 'ServoApp_TemporaryKey.pfx'. The key file may be password protected. To correct this, try to import the certifiacte manually into the current user's personal certificate store."

**Comment by paulrouget** [comment]
I believe the key is necessary for release builds. I removed the password. Hopefully it works for others now.

**Comment by jdm** [comment]
This works now.
