### ISSUE TITLE
[Hololens] Recent EGL issues

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#23612]
/cc @jdm 

2 issues:
- I think mozangle now links or make the wrong version of libegl available (https://github.com/servo/mozangle/commit/45ee552b3efd81eaf05ad79fa3fe1146bed23e15)
- after reverting above commit, servo tries to link with EGL.lib (not sure from where) while MS Angle provides libEGL.lib (notice the `lib` prefix). That was not a problem before (I had to locally copy libEGL.lib to EGL.lib to work around that)

**Comment by jdm** [comment]
I suspect the EGL.lib linking comes from https://github.com/servo/rust-offscreen-rendering-context/blob/443b70613afc4f11e8d9de6ea8c9ae4bb495067f/build.rs#L19.

**Comment by jdm** [comment]
Fixed in #23621
