### ISSUE TITLE
Running Servo on fedora 30 doesn't start up (error while loading shared libraries: libpcre.so.3)

### ISSUE THREAD

**Issue by emilio** [servo/servo#23624]
Apparently this is a Debian-specific file.

**Comment by jdm** [comment]
Yuck. Is there any good way to figure out where that dependency is coming from?

**Comment by emilio** [comment]
So I was trying to figure out using `lddtree ./target/debug/servo`, but it doesn't show up that dependency, then I realized that running the servo binary itself runs fine, but `./mach run` doesn't... I'll take a look to see if there's some LD path munging going wrong or what not.

**Comment by emilio** [comment]
Ahá, this fixes it:

```diff
diff --git a/python/servo/command_base.py b/python/servo/command_base.py
index d39576fe9c..1f99c18488 100644
--- a/python/servo/command_base.py
+++ b/python/servo/command_base.py
@@ -625,7 +625,7 @@ install them, let us know by filing a bug!")
             # Always build harfbuzz from source
             env["HARFBUZZ_SYS_NO_PKG_CONFIG"] = "true"
 
-        if self.needs_gstreamer_env(target):
+        if False and self.needs_gstreamer_env(target):
             gstpath = self.get_gstreamer_path()
             extra_path += [path.join(gstpath, "bin")]
             libpath = path.join(gstpath, "lib")
```

**Comment by jdm** [comment]
Hmm, I guess the Linux gstreamer bundle that we download with mach when the system gstreamer isn't new enough is debian-specific, in that case.

**Comment by emilio** [comment]
So presumably needs_gstreamer_env is failing. We decide whether our gstreamer is new enough using:

```python
def check_gstreamer_lib():
    return subprocess.call(["pkg-config", "--atleast-version=1.14", "gstreamer-1.0"],
                           stdout=PIPE, stderr=PIPE) == 0
```

That returns false on my system, but it is clearly working without patching the libraries so there's something else going on. My gstreamer stuff looks like:

```
$ pkg-config --list-all  | rg gstreamer                                                                                                                                                                                                    
gstreamer-dataprotocol-0.10    GStreamer data protocol library - Data protocol for plug-ins
gstreamer-check-0.10           GStreamer check unit testing - Unit testing helper library for GStreamer modules
gstreamer-base-0.10            GStreamer base classes - Base classes for GStreamer elements
gstreamer-net-0.10             GStreamer networking library - Network-enabled GStreamer plug-ins and clocking
gstreamer-0.10                 GStreamer - Streaming media framework
gstreamer-controller-0.10      GStreamer controller - Dynamic parameter control for GStreamer elements
```

I'm not familiar with how gstreamer is versioned but there's something fishy going on.

**Comment by emilio** [comment]
Oh, ok, so I was missing `gstreamer1-devel`. Installing that "fixes" it, by making Servo. But there's still something worth fixing here I think.

 * The built packages downloaded by `bootstrap-gstreamer` do not work in other non-Debian distros.
 * It may be possible to have all the libraries required for _running_ servo without the development packages, and in that case `needs_gstreamer_env` will still incorrectly claim you need to override LD_LIBRARY_PATH.

**Comment by jdm** [comment]
In the short term, we should raise an exception if the system gstreamer can't be used and we're running on a non-debian linux distribution.

**Comment by dralley** [comment]
Fedora 30 is going to be EOL shortly, and this seems to have either been fixed or stopped being an issue on Fedora 31+.  Recommend closing.
