### ISSUE TITLE
Add f64 version of transform.to_transform_3d_matrix

### ISSUE THREAD

**Issue by saschanaz** [servo/servo#23622]
DOMMatrix on Firefox 69 now uses `double`, but when parsing CSS through `new DOMMatrix("matrix(...)")` it depends on `transform.to_transform_3d_matrix()` and then loses precision. (And thus failing relevant WPT tests.)

https://github.com/mozilla/gecko-dev/blob/da14c413ef663eb1ba246799e94a240f81c42488/dom/base/DOMMatrix.cpp#L778

https://github.com/mozilla/gecko-dev/blob/a7a4c4c9df4b7b96c8d35b9f642c8b00a041092f/layout/style/ServoCSSParser.cpp#L55

https://github.com/mozilla/gecko-dev/blob/ea4843bd849cef3ecf281f8826626eea42550bda/servo/ports/geckolib/glue.rs#L6329

https://github.com/servo/servo/blob/b4fb2cda087a4467742681cc27291c803d0dc825/components/style/values/generics/transform.rs#L525-L561

Could we add a f64 version of the API so that we won't lose precision?

Example:

```js
new DOMMatrix("matrix(0.3333333333333333, 0, 0, 0, 0, 0)").m11
// expected: 0.3333333333333333
// actual: 0.3333333432674408
```

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1560705

**Comment by jdm** [comment]
@emilio Any opinion on this question?

**Comment by emilio** [comment]
@saschanaz fwiw you can edit that code directly in Firefox, I'd file a bug in the "CSS Parsing and Computation" component. I'm happy to help out or write the patch.

**Comment by emilio** [comment]
That being said we parse matrix as a matrix of `CSSFloat`s which is a f32 under the hood, so I'm not sure how fixing just that function would help.

**Comment by saschanaz** [comment]
>we parse matrix as a matrix of `CSSFloat`s which is a f32 under the hood

In that case the parser should support f64 first... So this Number should be modified to use f64, right?

https://github.com/servo/servo/blob/b4fb2cda087a4467742681cc27291c803d0dc825/components/style/values/specified/mod.rs#L158-L168

Looks like it will cause a large downstream changes.

**Comment by emilio** [comment]
Presumably, and yes, not only that but also will double memory usage in most places. We store a lot of these...
