### ISSUE TITLE
Hololens repo migration (please delete servo/HLServo)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#23621]
Hololens work is, for now, happening under Servo's `hl` branch. This includes the servo changes and the Hololens app (under `/support/`).

The project `paulrouget/HLServo` has been moved under `servo/HLServo` to make the issue migration possible. The issues have been migrated, and now the repo `servo/HLServo` is useless.

Please someone delete the project.

**Comment by larsbergstrom** [comment]
I have archived https://github.com/servo/HLServo
