### ISSUE TITLE
Add a CI test that verifies that `mach check` works

### ISSUE THREAD

**Issue by jdm** [servo/servo#23659]
We keep breaking it when playing around with cargo features. We should stop breaking it!

**Comment by SimonSapin** [comment]
There’s a bunch of logic in `./mach build` before calling `cargo build`. Most of it should likely apply to `./mach check` as well.

**Comment by SimonSapin** [comment]
Also `./mach doc` has similar logic that should be unified with both `build` and `check`. Compare:

https://github.com/servo/servo/blob/84786add227f2c0a675f4bcca708ac8a70011f6c/python/servo/build_commands.py#L307-L308

https://github.com/servo/servo/blob/84786add227f2c0a675f4bcca708ac8a70011f6c/python/servo/post_build_commands.py#L267
