### ISSUE TITLE
Servo on Windows panicks on WPT css/geometry/interfaces.html

### ISSUE THREAD

**Issue by saschanaz** [servo/servo#23663]
Accessing https://w3c-test.org/css/geometry/interfaces.html causes Servo fail on Windows.

```
Exception thrown at 0x00007FF69D748BD9 in servo.exe: 0xC0000005: Access violation reading location 0x0000000000000005.
```

**Comment by jdm** [comment]
This is very likely the same problem as #23531.

**Comment by saschanaz** [comment]
Confirmed that it throws on the same line.
