### ISSUE TITLE
[HoloLens] write openxr backend for rust-webvr

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#23679]
@jdm iirc, you have a WIP rust binding for the openxr library. Is it available somewhere?

**Comment by jdm** [comment]
I will push it today.

**Comment by jdm** [comment]
https://github.com/servo/rust-webvr/compare/openxr

**Comment by jdm** [comment]
The sample UWP app that integrates with OpenXR looks like a useful reference on top of my existing work: https://github.com/microsoft/OpenXR-SDK-VisualStudio/blob/master/samples/BasicXrApp/OpenXrProgram.cpp

**Comment by jdm** [comment]
Also https://www.khronos.org/registry/OpenXR/specs/0.90/refguide/OpenXR-0.90-web.pdf for a technical overview of the lifecycle.

**Comment by jdm** [comment]
I suspect my initial attempt to use [GraphicsBindingOpenGLWin32KHR](https://github.com/Ralith/openxrs/commit/64fce8f43271ddcac971c506d22012fa35b9bdbc#diff-c3a4cf8ef14ebc90ea17ece540dd6ec4R57) to create the session is incorrect and we need to use the D3D graphics binding instead, per the sample app: https://github.com/microsoft/OpenXR-SDK-VisualStudio/blob/03fd06d786c789c4c0743bb336e2d0e3b7bb2a86/samples/BasicXrApp/CubeGraphics.cpp#L222-L238

**Comment by jdm** [comment]
I added some missing d3d11 bindings to openxr-rs in https://github.com/servo/openxrs/tree/d3d11 and updated the rust-webvr branch to port the d3d11 initialization code from the sample app. See the latest commit at https://github.com/servo/rust-webvr/compare/openxr.

**Comment by atouchet** [comment]
Is this still relevant?

**Comment by jdm** [comment]
Nope!
