### ISSUE TITLE
DOMMatrix rotate() gives wrong value

### ISSUE THREAD

**Issue by saschanaz** [servo/servo#23688]
```js
new DOMMatrix().rotate(90, 0, 0);
// Gives
// [ 1,  0,  0,  0,
//   0,  0, -1,  0,
//   0,  1,  0,  0,
//   0,  0,  0,  1]
// ... while the expected value is:
// [ 1,  0,  0,  0,
//   0,  0,  1,  0,
//   0, -1,  0,  0,
//   0,  0,  0,  1]
```

Relevant code:

https://github.com/servo/servo/blob/7a1db0e8eaef9f615bedc08e23254bd79510de08/components/script/dom/dommatrixreadonly.rs#L302-L308

Could this be a euclid bug, as it seems it internally uses 3D rotation matrix designed for column-major matrices while being row-major?

https://drafts.csswg.org/css-transforms-2/#Rotate3dDefined

https://github.com/servo/euclid/blob/ee39c3c7ee3da9b61386f98f3f955d2b43855873/src/transform3d.rs#L591

**Comment by jdm** [comment]
This sounds very much like https://github.com/servo/euclid/issues/331.

**Comment by saschanaz** [comment]
Hmm. @Manishearth could this be fixed before the big change?

**Comment by Manishearth** [comment]
We should replace all our uses of `.post_mul` with `.pre_mul` and vice versa, and then also replace all uses of `.to_row_major_array()` with `.to_column_major_array()`. Except in cases where it's doing the right thing already.

Basically, all the functions have the opposite meaning here, compare with the spec and make sure you do the opposite operation.

**Comment by saschanaz** [comment]
Yes, that multiplication should be pre but it's not the cause in this specific case because I'm rotating an identity matrix.

**Comment by Manishearth** [comment]
Yeah then the issue is the coordinate mapping. All the `.mXY` functions should be accessing `.mYX`. `ToFloat32Array()` already does the correct thing, in this case.

How did you actually inspect the value of the matrix here? By default it just stringifies to `[object DOMMatrix]`.

**Comment by saschanaz** [comment]
I did `ToFloat32Array` as the stringifier is not implemented yet.

**Comment by Manishearth** [comment]
Curious, Firefox returns `[6.123234262925839e-17,1,0,0,-1,6.123234262925839e-17,0,0,0,0,1,0,0,0,0,1]` for the same call, which is incorrect.

**Comment by Manishearth** [comment]
Also curious, from a quick look it seems like the code does what it should here.

**Comment by saschanaz** [comment]
The Firefox implementation is flawed, it should be fixed soon in Nightly: https://bugzilla.mozilla.org/show_bug.cgi?id=1560480

**Comment by Manishearth** [comment]
Ah, I see. Nice find!

**Comment by Manishearth** [comment]
So the interesting thing is `new DOMMatrix().translate(1, 2, 3).toFloat32Array()` returns identical results in Chrome and Servo. `.toFloat32Array()` is not broken (and that's clear from the code, too). It's the `rotate()` function specifically.

**Comment by saschanaz** [comment]
I think we should use [transposed matrix of this](https://drafts.csswg.org/css-transforms-2/#Rotate3dDefined):

![image](https://user-images.githubusercontent.com/3396686/60556221-3f4c1600-9d7b-11e9-861e-367bdbfc41b5.png)

From what I see euclid currently uses it as-is.

**Comment by Manishearth** [comment]
Yeah, looking closely it looks like _that_ function in euclid was written with column vectors in mind.

What a mess.

Temporary fix would be to transpose the output of euclid.

**Comment by Manishearth** [comment]
We should also link to https://github.com/servo/euclid/issues/354 when we do that

**Comment by Manishearth** [comment]
Uh, also we use the same things in our css transforms code :frowning:

**Comment by Manishearth** [comment]
And this code is used by Gecko too. cc @emilio
