### ISSUE TITLE
Error libgstwebrtc while starting Servo build

### ISSUE THREAD

**Issue by eakarpov** [servo/servo#23684]
error while loading shared libraries: libgstwebrtc-1.0.so.0: cannot open shared object file: No such file or directory

OS: Ubuntu 18.04

I tried to install the libgstwebrtc package, but it is being installed with errors.

**Comment by CYBAI** [comment]
Thanks for filing the issue!

I found there's a related comment in https://github.com/servo/servo/issues/21970#issuecomment-493463653. Could you check that thread to see if they work for you? Thanks.

Btw, I'm going to close this one and let's track this issue in that thread :)
