### ISSUE TITLE
Implement the new syntax (= {}) for dictionary defaulting

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#23703]
See heycam/webidl#750

```
This implements two things:
- A syntax for specifying "default dictionary" using {}.
- The requirement that trailing optional dictionaries be thus specified.
```

(Copied from [bugzilla#1562680](https://bugzilla.mozilla.org/show_bug.cgi?id=1562680))

Related spec update PR in `html` and `dom`:
- whatwg/html#4745
- whatwg/dom#771

**Comment by saschanaz** [comment]
Working on this...
