### ISSUE TITLE
No cut functionality in clipboard.

### ISSUE THREAD

**Issue by mmiecz** [servo/servo#23735]
When I was refactoring clipboard code, I've noticed that there is no cut functionality, only copy and pase.
Currently, when using cut shortcut ( `CTRL + x` ) on selected text, given text is not being, copied but erased, and `x` letter is being inserted instead.

Since I was working on clipboard before, I think I can implement this functionality, if there is a need :)

**Comment by jdm** [comment]
Yes, that would be helpful!
