### ISSUE TITLE
Appveyor is broken after gstreamer packaging changes

### ISSUE THREAD

**Issue by jdm** [servo/servo#23749]
Same symptoms as https://github.com/servo/servo/issues/23747 except that it's our own CI.

**Comment by jdm** [comment]
Hmm, we're installing both the devel and non-devel packages already :<

**Comment by jdm** [comment]
```
ackaging gstreamer DLLs
ERROR: could not find required GStreamer DLL: avfilter-7.dll
ERROR: could not find required GStreamer DLL: avformat-58.dll
ERROR: could not find required GStreamer DLL: avcodec-58.dll
ERROR: could not find required GStreamer DLL: avutil-56.dll
ERROR: could not find required GStreamer DLL: swresample-3.dll
```
https://github.com/servo/servo/blob/5bc34e3e4dfb6502b462dd407ce414f9ea6f573f/appveyor.yml#L53-L56

**Comment by saschanaz** [comment]
I can get the files from ffmpeg Windows build and copy-paste them into gstreamer directory, but then it fails again with:

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
    Finished dev [unoptimized + debuginfo] target(s) in 17.85s
Packaging gstreamer DLLs
ERROR: could not find required GStreamer DLL: gstlibav.dll
Packaging MSVC DLLs
Build FAILED in 0:00:18
```

**Comment by jdm** [comment]
One interesting difference between our Taskcluster CI and Appveyor is that appveyor installs the MSIs with /quiet, meaning that any default options will be automatically used. Taskcluster extracts all of the files from the MSI and repackages them in a ZIP which is later unpacked in the directory that Servo's build uses. This suggests to me that the MSI contains a choice to install the ffmpeg DLLs which is not enabled by default.

**Comment by saschanaz** [comment]
Ah, your right! The installer has a disabled-by-default option named "GStreamer 1.0 libav wrapper" which installs the required files.
