### ISSUE TITLE
Include log target in vslogger output

### ISSUE THREAD

**Issue by jdm** [servo/servo#23755]
Right now the logging from the VSLogger handler only shows the [message and the level](https://github.com/servo/servo/blob/d52692241e2e3c57223e8ca4936dc3c7e5945719/ports/libsimpleservo/capi/src/vslogger.rs#L20), but not the [target](https://docs.rs/log/0.4.7/log/struct.Record.html#method.target). Including this will make it easier to make sense of the log output.

**Comment by angelortiz1007** [comment]
I've modified the fn log() function to now include "record.target" as shown below.   I have the following questions:

1. Is the formatting acceptable, or should the record.target() be the first output variable?
2. What is the best way to test this change and verify a log is being created properly?

    fn log(&self, record: &Record) {
        if self.enabled(record.metadata()) {
            let log = format!("RUST: {} - {} - {}\r\n\0", record.level(),
                                                          record.target(),
                                                          record.args());
            unsafe {
                OutputDebugStringA(log.as_ptr());
            };
        }
    }

**Comment by jdm** [comment]
The easiest way to test the change is to change the VSLogger's `enabled` method to return `true` and look at the Output window's contents before and after your changes - Servo produces a bunch of logging by default, so it should be easy to compare.

**Comment by jdm** [comment]
And yes, that formatting seems fine to me.

**Comment by angelortiz1007** [comment]
Thanks Josh, I’ll document the test case when I commit the changes.

 

If I do a:

Mach build -r –uwp

 

Also, “cargo test” is the way to test, correct?

**Comment by jdm** [comment]
You will need to do:
* `mach build -r --uwp`
* when that build completes, rebuild the visual studio project in release configuration
* when that build completes, run the video studio project in x64 local machine configuration

This will cause the UWP app to run using the latest changes to the Servo engine.

**Comment by angelortiz1007** [comment]
Issue implemented.  See https://github.com/servo/servo/pull/23783
