### ISSUE TITLE
Support refining VSLogger filter by module

### ISSUE THREAD

**Issue by jdm** [servo/servo#23754]
Right now we include log messages in the output based strictly on their level (https://github.com/servo/servo/blob/d52692241e2e3c57223e8ca4936dc3c7e5945719/ports/libsimpleservo/capi/src/vslogger.rs#L15). It would be good to support initializing VSLogger with a list of accepted modules and filter against the log record's [target](https://docs.rs/log/0.4.7/log/struct.Metadata.html#method.target) to decide whether to display it or not.

This would require making the list of accepted modules part of the API initialization in [this code](https://github.com/servo/servo/blob/d52692241e2e3c57223e8ca4936dc3c7e5945719/ports/libsimpleservo/capi/src/lib.rs#L76-L115) via the CInitOptions structure.

**Comment by angelortiz1007** [comment]
Can the list of "accepted" modules be listed?

**Comment by jdm** [comment]
@angelortiz1007 We're effectively trying to achieve the same effect as the [Android port's logging](https://github.com/servo/servo/blob/c57e9bb93834aedf9a22bebc45589b3d622b9e98/ports/libsimpleservo/jniapi/src/lib.rs#L64-L87) - a list of accepted modules is a list of strings that will be parsed as Rust module paths. The VSLogger should store a vector of strings that it uses to decide if a log record's target matches.

**Comment by jdm** [comment]
I would expect:
* storing a vec as a member of VSLogger, initialized to the empty vec
* adding a method to VSLogger that allows setting that vec member
* calling that method from [init_logger](https://github.com/servo/servo/blob/005320c08c9dc0a87ada445f66549c2140891975/ports/libsimpleservo/capi/src/lib.rs#L77)
* passing the desired list of modules as an argument to init_logger
* adding a member to [CInitOptions](https://github.com/servo/servo/blob/005320c08c9dc0a87ada445f66549c2140891975/ports/libsimpleservo/capi/src/lib.rs#L56) which stores a C array of strings, which get converted into a vector of Rust strings
* initializing the hololens' [CInitOptions member](https://github.com/servo/servo/blob/005320c08c9dc0a87ada445f66549c2140891975/support/hololens/Servo.cpp#L47) with a desired C array of module names

**Comment by angelortiz1007** [comment]
**storing a vec as a member of VSLogger, initialized to the empty vec**
pub struct VSLogger {
    pub module_vec: Vec<String>,
}

**adding a method to VSLogger that allows setting that vec member**
impl VSLogger {
    pub fn init_vslogger(&self) {
        //self.module_vec = Vec::new();
    }

    pub fn add_module_to_filter(&self, _mystring: std::string::String) {
        //self.module_vec.push(_mystring);
    }
}

**calling that method from init_logger**
This is where I'm having trouble with RUST.
#[cfg(target_os = "windows")]
fn init_logger(_module_list: String) {
    use log::LevelFilter;
    use std::sync::Once;
    use vslogger::VSLogger;

    // let mut mod_list = String::from("mod1");
    // vslogger.init_vslogger();
    // vslogger.add_module_to_filter(module_list);

    static LOGGER: VSLogger = VSLogger { module_vec: vec![] };
    static LOGGER_INIT: Once = Once::new();
    LOGGER_INIT.call_once(|| {
        log::set_logger(&LOGGER)
            .map(|_| log::set_max_level(LevelFilter::Debug))
            .unwrap();
    });
}

Doing a mach build -d --uwp I get the following error and don't know how to get around it.
error[E0010]: allocations are not allowed in statics
   --> ports\libsimpleservo\capi\src\lib.rs:225:54
    |
225 |     static LOGGER: VSLogger = VSLogger { module_vec: vec![] };
    |                                                      ^^^^^^ allocation not allowed in statics

**Comment by jdm** [comment]
Interesting. I think you will need to conver it to a lazy static instead. Look for other examples in the code of `lazy_static`, which relies on the [lazy_static](https://docs.rs/lazy_static/1.3.0/lazy_static/) crate.

**Comment by angelortiz1007** [comment]
JDM,  
Here is what I have and I still seem to be missing something due to the error.

[vcvarsall.bat] Environment initialized for: 'x64'
   Compiling simpleservo_capi v0.0.1 (C:\git-mozilla\servo-angelortiz1007\ports\libsimpleservo\capi)
error: no rules expected the token `LOGGER_INIT`
   --> ports\libsimpleservo\capi\src\lib.rs:230:5
    |
230 |     LOGGER_INIT.call_once(|| {
    |     ^^^^^^^^^^^ no rules expected this token in macro call

warning: unused import: `log::LevelFilter`
   --> ports\libsimpleservo\capi\src\lib.rs:220:9
220 |     use log::LevelFilter;
    |         ^^^^^^^^^^^^^^^^
    = note: `#[warn(unused_imports)]` on by default
error: aborting due to previous error
error: Could not compile `simpleservo_capi`.

#[cfg(target_os = "windows")]
fn init_logger(_module_list: String) {
    use log::LevelFilter;
    use std::sync::Once;
    use vslogger::VSLogger;

    // let mut mod_list = String::from("mod1");
    // vslogger.init_vslogger();
    // vslogger.add_module_to_filter(module_list);
    lazy_static! {
     static ref LOGGER: VSLogger = VSLogger { module_vec: vec![] };
     static ref LOGGER_INIT: Once = Once::new();
    LOGGER_INIT.call_once(|| {
        log::set_logger(&LOGGER)
            .map(|_| log::set_max_level(LevelFilter::Debug))
            .unwrap();
    });}
}

**Comment by jdm** [comment]
The call_once call still belongs where it originally lived before your changes.

**Comment by angelortiz1007** [comment]
Yep, did that too. :(  Here is the output:
   Compiling layout_thread_2013 v0.0.1 (C:\git-mozilla\servo-angelortiz1007\components\layout_thread)
error[E0277]: the trait bound `init_logger::LOGGER: log::Log` is not satisfied
   --> ports\libsimpleservo\capi\src\lib.rs:232:25
    |
232 |         log::set_logger(&LOGGER)
    |                         ^^^^^^^ the trait `log::Log` is not implemented for `init_logger::LOGGER`
    |
    = note: required for the cast to the object type `dyn log::Log`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `simpleservo_capi`.

To learn more, run the command again with --verbose.
Build FAILED in 0:31:19

**Comment by angelortiz1007** [comment]
Will continue to work through this over the weekend.

**Comment by jdm** [comment]
This was fixed by #24107.
