### ISSUE TITLE
mach: update-manifest misses local changes

### ISSUE THREAD

**Issue by gterzian** [servo/servo#23775]
I've noticed a few times that if you make a change to an existing test, `./mach update-manifest` does nothing locally. Later, it fails on CI(example: https://tools.taskcluster.net/groups/Sl1yBFfwRP6Vh2ELmd8Hxw/tasks/CebOEynkQruZJ-A0FGfYrQ/runs/0/logs/public%2Flogs%2Flive.log#L525).

Not sure how I fixed it last time, or whether this happens intermittently, but this time I can guarantee that I tried it a few times locally, I even deleted `MANIFEST.json` and rebuild it, yet it was rebuild without taking into account the latest changes(https://github.com/servo/servo/pull/23637/commits/0f53873de56a3e44ff64c70d3b77b23bee4a6c64#diff-684fc482ea12f526b30118a7d4cfa714R33).

**Comment by jdm** [comment]
I'm hopeful hat this has been fixed by https://github.com/web-platform-tests/wpt/pull/17785.

**Comment by CYBAI** [comment]
It's been synced in https://github.com/servo/servo/pull/23767/files?file-filters%5B%5D=.py#diff-dca0930be0d5a55410bfecf0b0ab7a31 👀

**Comment by mrobinson** [comment]
Has this been an problem since the sync? If not, I guess we can close this issue.

**Comment by jdm** [comment]
Nope.
