### ISSUE TITLE
Check for user activation in WebXR

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#23787]
`requestSession()` is not supposed to work in immersive mode if it isn't triggered by user activation. We should also update `simulateUserActivation()` from https://github.com/servo/servo/pull/23786 when implementing this.

**Comment by paulrouget** [comment]
is there a DOM specification about that? I remember vaguely something about user clicks vs. js clicks.

**Comment by paulrouget** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted

**Comment by paulrouget** [comment]
Properly classifying events as trusted doesn't look difficult. Not sure where to store this property to make it accessible from any DOM call though.

Is it possible to "tag" a js call?

Gecko appears to use a static  ([`sUserInputEventDepth`](https://dxr.mozilla.org/mozilla-central/source/dom/events/EventStateManager.cpp#4125)) to track if a js call runs as the consequence of an user input.

**Comment by jdm** [comment]
Making it a property of ScriptThread and adding a static method might makes sense.
