### ISSUE TITLE
Set CORS preflight requests' `mode` to `cors`.

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#23780]
Spec: whatwg/fetch#916
WPT: web-platform-tests/wpt#17874

**Comment by ghostd** [comment]
I started to work on this, but to make the test pass we need to also implement the 'Sec-*' headers, but the specification is still in discussion:
https://github.com/w3c/webappsec-fetch-metadata/issues/58
https://github.com/whatwg/fetch/pull/993
https://github.com/whatwg/fetch/pull/1000

I can provide a PR with the current work, but that won't change the status of the tests.

**Comment by jdm** [comment]
That still sounds like a good improvement.
