### ISSUE TITLE
Rendering Issues in Wayland/Sway

### ISSUE THREAD

**Issue by azer** [servo/servo#23799]
I'm a Wayland/Linux user and experience issues running Servo in my system; Sway + Arch Linux. 

You can see the screenshot below;
* The window locates itself in a centered position instead of using the whole space. Normally, Servo should have used 50% of the width and full height of the screen, as expected in a system with tiling window managing.
* It's not able to render Google, due to a binding error can be seen in the screenshot.

![](https://cldup.com/9f18UDB6HN.png)

**Comment by edrex** [comment]
seems like the dpi issues mentioned at https://github.com/servo/servo/issues/9558#issuecomment-439814081, maybe. HiDPI display?

**Comment by okias** [comment]
@azer can you retest? I just run Servo on GNOME-Shell & Wayland session and it works somehow #27518 (check screenshots)

**Comment by nostdm** [comment]
I have the same issue on sway/wayland (v1.5) with 4K display and latest servo build from master:

![image](https://user-images.githubusercontent.com/16334589/99890900-ed4fad00-2c5b-11eb-9e2a-b6a187b25071.png)

It seems to not render the content properly inside the wayland window. 

The sway compositor has the following information about the window:

```
{
              "id": 762,
              "name": "Google - Servo",
              "rect": {
                "x": 8,
                "y": 46,
                "width": 1904,
                "height": 990
              },
              "focused": false,
              "focus": [
              ],
              "border": "normal",
              "current_border_width": 3,
              "layout": "none",
              "orientation": "none",
              "percent": 1.0,
              "window_rect": {
                "x": 3,
                "y": 0,
                "width": 1898,
                "height": 987
              },
              "deco_rect": {
                "x": 634,
                "y": 0,
                "width": 634,
                "height": 38
              },
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 1024,
                "height": 770
              },
              "window": null,
              "urgent": false,
              "marks": [
              ],
              "fullscreen_mode": 0,
              "nodes": [
              ],
              "floating_nodes": [
              ],
              "sticky": false,
              "type": "con",
              "pid": 2292033,
              "app_id": null,
              "visible": false,
              "max_render_time": 0,
              "shell": "xdg_shell",
              "inhibit_idle": false,
              "idle_inhibitors": {
                "user": "none",
                "application": "none"
              }
            },
```

**Comment by jdm** [comment]
The most likely improvement here would probably come from https://github.com/servo/servo/issues/26394.

**Comment by jdm** [comment]
This should be fixed now.
