### ISSUE TITLE
Create NuGet package for ANGLE with ARM64 support

### ISSUE THREAD

**Issue by jdm** [servo/servo#23809]
The official Microsoft ANGLE NuGet package has x64, x86, and ARM support. We need ARM64 as well, and https://github.com/microsoft/angle/pull/144 is just sitting there waiting. I propose we make our own fork of that repository, merge that pull request and https://github.com/microsoft/angle/pull/154 and then publish the resulting binaries as our own NuGet package.

https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio
https://docs.microsoft.com/en-us/nuget/create-packages/native-packages
https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package
https://shed.globalgraphics.com/2018/03/15/creating-a-native-c-nuget-package-for-the-mako-sdk/

**Comment by jdm** [comment]
https://github.com/servo/ms-angle/tree/servo-master

https://github.com/microsoft/angle/issues/99#issuecomment-265009259

**Comment by jdm** [comment]
https://www.nuget.org/packages/ANGLE.WindowsStore.Servo/2.1.13

Time to update our documentation!

**Comment by jdm** [comment]
Nevermind, I need to update the package reference in the project file.

**Comment by palxex** [comment]
Never mind, could you please add armv7 in the nuget package? MS package is x86/x64/armv7, and yours' x86/x64/arm64, if one package could get x86/x64/armv7/arm64 altogether that could be great :)

**Comment by jdm** [comment]
The most recent version of the package may actually include it? I feel like our gstreamer friends made the same request.

**Comment by palxex** [comment]
> The most recent version of the package may actually include it? I feel like our gstreamer friends made the same request.

Just checked [2.1.20 on nuget.org](https://www.nuget.org/packages/ANGLE.WindowsStore.Servo/2.1.20), seems it adds x86 than before( x64/arm64 only ). My question is, whether possible adds armv7 too?

**Comment by jdm** [comment]
It's certainly possible, but there's not a lot of motivation to do so. You could follow the steps at https://github.com/servo/servo/wiki/Publishing-a-new-ANGLE-NuGet-version to make your own version of the package that includes it.

**Comment by palxex** [comment]
Thanks for pointing it out:) I'll take a look
