### ISSUE TITLE
Wrong Type for `ROUTER.add_route` callback?

### ISSUE THREAD

**Issue by gatoWololo** [servo/servo#23818]
## Background
I'm messing around with a typed version of the `ipc::router::add_route` method.
Original:
```rust
pub fn add_route(&self, receiver: OpaqueIpcReceiver, callback: RouterHandler)

// where
pub type RouterHandler = Box<FnMut(OpaqueIpcMessage) + Send>;
```

Mine:
```rust
pub fn add_route<T>(&self, receiver: IpcReceiver<T>,
                           mut callback: Box<FnMut(Result<T, ipc_channel::Error>) + Send>)
```

So I call the `OpaqueIpcMessage::to` message on behalf of the user, and hide all the implementations details about `Opaque*`.

When using the typed API I found two places in Servo where I couldn't get it to type check.

## Actual Problem
From the latest master unmodified code. I'm looking at the function `add_cache_listener_for_element` in `servo/components/script/dom/htmlimageelement.rs`
The relevant parts are:
```rust
fn add_cache_listener_for_element(
            ...
            let (responder_sender, responder_receiver) = ipc::channel().unwrap();
            ...
            ROUTER.add_route(responder_receiver.to_opaque(), Box::new(move |message| {
                ...
                let image = message.to().unwrap();
                ...
                            element.process_image_response_for_environment_change(image, ...);
            ...
            }));

            image_cache.add_listener(id, ImageResponder::new(responder_sender, id));
```

Notice type inference is happening at two relevant places here: The type of `channel<T>()` and the type of `to<T>()`. I explicitly add a turbofish to `channel`:
```diff
- let (responder_sender, responder_receiver) = ipc::channel().unwrap();
+ let (responder_sender, responder_receiver) = ipc::channel::<PendingImageResponse>().unwrap();
```
I know this is the correct type from the call to `ImageResponder::new(responder_sender, id));` at the bottom which takes the `responder_sender`: `pub fn new(sender: IpcSender<PendingImageResponse>, ...) -> ...`. The **compiler agrees** with me, and type checks the program.

Now I try adding the type for the call to `.to()`:
```diff
- let image = message.to().unwrap();
+ let image = message.to::<PendingImageResponse>().unwrap();
```

The message comes from the `IpcReceiver<T>` turned `OpaqueReceiver`. Which we have established has type `PendingImageResponse`. However, the way it is being using in the callback:
```rust
element.process_image_response_for_environment_change(image, ...);
```
The compiler infers:
```
    --> components/script/dom/htmlimageelement.rs:1012:83
     |
1012 |                             element.process_image_response_for_environment_change(image,
     |                                                                                   ^^^^^ expected enum `net_traits::image_cache::ImageResponse`, found struct `net_traits::image_cache::PendingImageResponse`
     |
     = note: expected type `net_traits::image_cache::ImageResponse`
                found type `net_traits::image_cache::PendingImageResponse`
``` 

This compiles fine without the added `::<PendingResponse>` to `to` since the compiler infers the type should be `ImageResponse`. I believe this is wrong, and if this code were to be executed at runtime, the call to `to().unwrap()` would fail and panic?

Unless I'm missing some implicit conversion between `ImageResponse` and `PendingImageResponse`?

**Comment by jdm** [comment]
Curious! That does look incorrect to me.

**Comment by gatoWololo** [comment]
There is a similar case in function `add_cache_listener_for_element` in `servo/components/script/image_listener.rs`.

I would be down to fix it, but I'm not exactly sure what the "correct" code would look like. Since it's not an issue now, but down the line it may block me on some RR channel stuff I'm working on.
Currently my workaround is: `let image = unimplemented!(); //message.unwrap();`

Since I don't believe this code is being executed for my current tests :stuck_out_tongue:

**Comment by gterzian** [comment]
It's a mistery. I've added some print statements at `servo/components/script/image_listener.rs`, it's pretty easy to hit that code branch, just load github.com or any page with images. 

What goes in the `send` is a `PendingImageResponse`, what comes out in the `recv` is a `ImageResponse`. 

I don't know how. 

Since a ``PendingImageResponse` contains a `ImageResponse`, could the deserialize step somehow be smart enough to take only that part?

**Comment by jdm** [comment]
This might be the problem that @gatowololo mentioned to me, where an opaque ipc channel can be used to receive an object that is smaller than what was sent (like i32 from an i64).

**Comment by gatoWololo** [comment]
See https://github.com/servo/ipc-channel/issues/239 for a minimal example of the issue.

**Comment by gatoWololo** [comment]
I and @cbrewster  think we figured it out. `PendingImageResponse` is defined in terms of `ImageResponse`:
```rust
#[derive(Debug, Deserialize, Serialize)]
pub struct PendingImageResponse {
    pub response: ImageResponse,
    pub id: PendingImageId,
}
```

So we probably got lucky that the first field is an `ImageResponse`, so the deserailziation "just happens" to be of the right type.

The good news is the solution is pretty simple:

```diff
- let image = message.to().unwrap();
+ let image = message.to::<PendingImageResponse>().unwrap().response;
```

And that should make it correct :)

**Comment by jdm** [comment]
Wow. Big yikes!
