### ISSUE TITLE
Closing the window does not terminate the program

### ISSUE THREAD

**Issue by jdm** [servo/servo#23859]
I'm pretty sure this is related to the changes from #23845. cc @paulrouget

**Comment by jdm** [comment]
It may also be coming from calling simpleservo::deinit, judging by some crash logs I received when running the WACK testing.

**Comment by paulrouget** [comment]
erf. `deinit` needs to be called in the GL thread. Moving it to OnShutdownComplete will do. But it still crashing in `deinit` for some reason. I'll look later.
