### ISSUE TITLE
Add compile-fail tests

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#2385]
As an example, [`js.rs`](https://github.com/mozilla/servo/blob/master/src/components/script/dom/bindings/js.rs) provides a guarantee that JS-managed objects are rooted when we use them from Rust.  The test suite should try to compile some invalid uses of this code and make sure they're rejected.  This guards against language changes, compiler bugs, etc.

The same goes for anywhere else in Servo that we attempt to provide static safety guarantees.

**Comment by nox** [comment]
This was done.
