### ISSUE TITLE
WPT updates are timing out

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#23907]
See for example https://tools.taskcluster.net/groups/I8L6QWFCQUWXTS_8ZyjC_A/tasks/SgqI076ARbuPzoRNXxDv8Q/runs/0/logs/public%2Flogs%2Flive.log

We can increase the time limit https://github.com/servo/servo/blob/196c511d5ebf81b3fe202c5e0c5c1972a6408ab7/etc/taskcluster/decision_task.py#L518 but it’s already 5 hours. Maybe it’s worth trying the 2018 mac minis from Macstadium?

**Comment by SimonSapin** [comment]
CC @jdm

**Comment by jdm** [comment]
I've seen this happen when there are stale wpt processes still running on the machines.
