### ISSUE TITLE
Completely garbled Czech version of google.com

### ISSUE THREAD

**Issue by mcepl** [servo/servo#2392]
With 31e36b7 (on Linux/RHEL-7/x86_64) when I run `./servo http://www.google.com` I get the attached.
![screenshot from 2014-05-10 08 22 40](https://cloud.githubusercontent.com/assets/198999/2935414/5e7ecfac-d80c-11e3-8f5c-495d91ce0895.png)

I live in Czechia, so this is most likely servo’s attempt to render Czech text. Obviously the correct rendering of that page (in the current Firefox/Nightly) is
![screenshot from 2014-05-10 08 31 14](https://cloud.githubusercontent.com/assets/198999/2935417/c2b748a0-d80c-11e3-9062-a005bb424553.png)

**Comment by nox** [comment]
This doesn't seem to be true anymore, running `./mach run http://www.google.cz`.
