### ISSUE TITLE
capi: use wide strings everywhere

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#23933]

**Comment by paulrouget** [comment]
I'm not sure:

https://github.com/servo/servo/blob/555fa75b2c7f4faa0818e86296a4ea3d5b8e4d42/ports/libsimpleservo/capi/src/lib.rs#L439

are these widestrings?

C++ side, I'm trying to properly get a std::wstring.

**Comment by jdm** [comment]
CStrings are not wide strings.

**Comment by jdm** [comment]
If wide strings are necessary, you want https://doc.servo.org/std/ffi/index.html#on-windows. Making the entire C API use wide strings feels like the wrong choice to me. This really belongs in a Windows-specific embedding instead.

**Comment by paulrouget** [comment]
Ok - I will file an issue for the widestring conversion code. In an upcoming changes, i need to convert the char* to wstring then to hstring. And I'm not sure I'm doing the right thing.
