### ISSUE TITLE
Deduplicate dependencies

### ISSUE THREAD

**Issue by Eijebong** [servo/servo#23948]
It's been a while since I haven't checked on that. Going to track progress here because my brain can only contain so much info.

- ~crossbeam-deque~:
  - [x] https://github.com/rayon-rs/rayon/commit/99706a49b478b3cbde1135401f325556f0a4d472

- ~euclid~:
  - [x] rust-webvr
  - [x] servo-media-audio

- ~gl_generator~:
  - [x] https://github.com/servo/mozangle/pull/29
    - [x] https://github.com/brendanzab/gl-rs/issues/491
      - [x] glutin
      - [x] gleam
      - [x] offscreen_gl_context
      - [x] rust-webvr
      - [x] webxr

- ~lock_api / scopeguard~:
  - parking_lot: 
    - [x] https://github.com/rust-windowing/winit/pull/1109
    - [x] https://github.com/rust-windowing/glutin/pull/1210

- ~log~:
  - mime:
    - [x] https://github.com/abonander/multipart/pull/121

- ~nix~:
  - wayland-client / wayland-commons:
    - [ ] winit
    - [ ] glutin

- ~rand~:
  - [x] servo-rand (https://github.com/servo/servo/pull/23950) 

- ~unicase~:
  - [x] mime
  - [x] phf

- ~png~ (https://github.com/servo/servo/pull/23979):
  - image:
    - [x] webrender (https://bugzilla.mozilla.org/show_bug.cgi?id=1573039)

**Comment by atouchet** [comment]
log and unicase were deduped in #24006.

**Comment by atouchet** [comment]
rayon 1.2.0 has been published.

**Comment by atouchet** [comment]
I think it should be possible to dedupe nix to 0.14 without needing winit and glutin updates.

**Comment by Eijebong** [comment]
Indeed, thanks https://github.com/servo/servo/pull/24155

**Comment by mrobinson** [comment]
I'm going to close this in favor of separate bugs for dependencies. Many things have changed since 2019.
