### ISSUE TITLE
Three.js examples broke on recent three.js releases

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#23954]
The three.js examples which used to work in Servo are now not rendering.

Bisecting using the wayback machine, Mar 31 works, https://web.archive.org/web/20190331203342/https://threejs.org/examples/#webgl_animation_cloth but May 9 doesn't https://web.archive.org/web/20190509071159/https://threejs.org/examples/#webgl_animation_cloth

This could be r104 switching off error checking for shader compilation? https://github.com/mrdoob/three.js/wiki/Migration-Guide#r103--r104

**Comment by jdm** [comment]
This is caused by the switch to use JS modules in the examples instead: see discussion at https://github.com/mrdoob/three.js/pull/16799#issuecomment-515592542 which includes workarounds.

**Comment by asajeffrey** [comment]
Ah, that explains it!

**Comment by jdm** [comment]
Closing this since the cause it known.
