### ISSUE TITLE
Create a libhlservo library

### ISSUE THREAD

**Issue by jdm** [servo/servo#23974]
There is a bunch of Hololens-specific embedding that's ending up in per-platform cfg blocks in libsimpleservo's C API crate. We should create a new Rust crate that contains the Rust-specific embedding pieces (such as stdio/stdout redirection, logging setup, and GST_LOG redirection) and reexports all of the important bits of the C API.

**Comment by paulrouget** [comment]
I'm not convinced we have to create a hl specific library.

I'm not sure it's all Hololens specific. Isn't it Windows specific? Maybe it makes sense to keep these things under `simpleservo/capi/`? As in, if someone wants to use servo in their app on windows, they will need logs and redirection as well.

And if there's something HL specific, could it be moved in support/hololens?
