### ISSUE TITLE
Unregistering from XR's destructor causes panics 

### ISSUE THREAD

**Issue by jdm** [servo/servo#23986]
Specifically, XR::unregister tries to get the webvr thread handle from the object's global, but Drop can be called during GC when there is no real global object any more. We should perform any unregistration during page teardown instead.

**Comment by gterzian** [comment]
Code would be at https://github.com/servo/servo/blob/9bba14cb438cf5ac08945bb8fbb5a0f31d43fcbe/components/script/dom/document.rs#L1850

and it seems like this would be a good fit for https://html.spec.whatwg.org/multipage/browsing-the-web.html#unloading-document-cleanup-steps as something to be defined in the webxr spec.

**Comment by gterzian** [comment]
I think that similar to what is done with websockets, you'd want to set the document salvageable state to false, if any xr is cleaned-up during unload. 

https://html.spec.whatwg.org/multipage/browsing-the-web.html#concept-document-salvageable
