### ISSUE TITLE
Generate unique ids for nodes lazily

### ISSUE THREAD

**Issue by jdm** [servo/servo#23995]
As far as I know, the the `unique_id` field in Node is only used by the webdriver code. In the common case, this id would never be used. #23951 is increasing the amount of memory that is used to track these ids, so it would make sense to make the process lazy - store an Option<UniqueId> and set it to Some(UniqueId::new()) the first time that a node's unique id is retrieved.

Code: `components/script/dom/node.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/webdriver`

**Comment by tdelacour** [comment]
@highfive assign me

looks interesting!! Any expected pitfalls?

**Comment by jdm** [comment]
No pitfalls expected!
