### ISSUE TITLE
Media controls on magicleap

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#24014]
Currently video elements on magicleap don't have controls. They should!

**Comment by asajeffrey** [comment]
cc @ferjm. Related to #22298.

**Comment by asajeffrey** [comment]
IRC chat at https://mozilla.logbot.info/servo/20190820#c16554592

**Comment by ferjm** [comment]
Even if the existing Shadow DOM based media controls introduced in #22298 work properly on Magic Leap, they probably don't provide the best experience on a Mixed Reality context. I can think of a few approaches to improve the experience:

- Tweak the styles of the existing controls to make them look and perform better on a MR context. We need to do the same thing for mobile.
- Exposing an API like the one mentioned in #22374, so we can implement native controls for ML and other platforms.
- Implementing the [Media Session API](https://w3c.github.io/mediasession) with its corresponding browser UI.

**Comment by asajeffrey** [comment]
https://github.com/servo/servo.org/pull/76 puts the block style on the rabbit video, so at least the demo has the controls, even if they're not pretty.

**Comment by ferjm** [comment]
#24499 introduced the Media Session API. With that in place we are now able to implement specific media controls for ML.

**Comment by mrobinson** [comment]
Closing this for now as we don't support MagicLeap at the moment.
