### ISSUE TITLE
A long term / sustainable plan proposal for servo and firefox

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/servo#24026]
According to [Stat counter](https://gs.statcounter.com/) Firefox has a global marketshare of 4.48% which is slowly falling.
Firefox mobile has a negligible marketshare and many sites are sub-par / almost broken on it. 
Let's not even speak of electron, installable PWAs, Cordova and webview apps where Firefox has 0 marketshare (Yes geckoview exist but is not used anywhere)

Mozilla funding are shrinking and dependant of Google (how ironic).
And browsers are too complex projects to be only driven by an open source community, it needs full time employees (a lot).

I would like to express a few points that complement each others:
1) Firstly it is factual, it must be aknowledged that there is a BIG, very BIG gap of features that blink implement and servo/gecko doesn't. And this gap is growing. 
As a consequence, if a web master wants to supports those 4% users, it will often limit the user experience of all of it's users, by not using blink only features. 
There are also some kind of websites/apps that are today only possible to create in blink. 
Thus mozilla is slowing the evolution of the web which is deeply damaging the experience and the well being of humans.

2) What is the biggest strength of open source? It is about being able to collaborate beyond our own differences for a greater good. Open source is about mutualising working force, creating together synergies and about NOT duplicating efforts and reinventing the wheel. Sadly the  [NIH syndrome](https://fr.m.wikipedia.org/wiki/Not_invented_here)  is far from being cured.
There are plenty of such examples of non duplicated efforts like the rust programming language, they whatwg specs, QT, GTK and the Linux kernel. 
Chromium hasn't always been such an exemple but it is now a beautiful exemple of collaboration from many actors, like opera and now from Microsoft. 
Microsoft is enabling an impactful synergy which will benefits by far most users of the web such as less input latency (e.g moving input handling out of the main thread), big energy consumption improvements, better OS integration, better devtools, etc and it's only the beginning. 
What Microsoft do is to bring the best strengths of edge into chromium for the benefit of everybody. 

I am not asking mozilla to drop everything, to jump on the chromium ship, to improve it through beautiful collaboration, to bring the best strengths of gecko to chromium for the benefit of everybody and to maintain a soft fork of chromium to apply patch where mozilla disagree with some political choices. 
Sadly I am not asking for such a collaboration as I believe that mozilla is not ready for that even if it is the rational choice for a greater good (user experience). 
I'm not asking it because I think there's more emotions than rationality in most humans (sadly) and mozilla is made of humans. 

Does this means that mozilla has to continue duplicating each feature in gecko? That the feature gap between blink and gecko will continue to increase until webmasters decide it's too much and ask FF users to install a browser that supports modern web standards?
And once it happen, the decades of works put into gekco will be useless for ever? 

I strongly believe there's a third way! 
A solution for making mozilla sustainable. 
Instead of a white or black strategy (let's share all the code or none) there is a continuum. 
A browser is made of many, soo many parts (you know it better than me). 
I propose that mozilla draw a roadmap for increasing code sharing between gecko and chromium. 
This is not prior art, in fact you use many things that have been directly or indirectly improved by Google or the chromium project. One of the biggest examples are Skia, ANGLE, HTTP2 and 3, Fuzzers, and a LOT of libs (freetype, harfbuzz, etc), wpt tests and even the compilers and kernel your use in dev. 
I am not aware of the reverse (chromium using mozilla libs/code) (except mozilla web specs) but maybe that's just that I lack knowledge.
You would benefit in increasing sharing in two ways:
Let's use chromium libraries that are >= to the one you uses actually. It would massively reduce the maintenance cost of mozilla allowing to better spend ressources on missing features. 
The other complementary way is to make proposals to chromium, to use one of your libraries that is arguably > on a number of metrics. They would improve it in return and thus reducing your maintenance cost. 

I was talking of "libraries" but this does apply to "browser modules" too. 
Ideally you could share you parts of your renderer or parts of stylo or parts of your DOM implementation, or your html parser, etc (there far more than that to be shared). 
If on metrics you can show that such part is superior to the chromium equivalent, I'm sure chromium devs would be happy to integrate it. Thus again reducing maintenance, security coverage and improving synergies for the greater good. 
This goes the other way too, you could use chromium modules too, giving for free features support improving massively webcompat. 
This third way is the way to go mozilla!

**Comment by jdm** [comment]
I suggest that the right place to have this conversation is the [dev-platform mailing list](https://lists.mozilla.org/listinfo/dev-platform), and not the Servo issue tracker. This is a broader issue than just a particular technical one inside Servo.

**Comment by LifeIsStrange** [comment]
Thanks @jdm
I have a question, a few years ago there was blog post from a googler that plotted on a graph the evolution of mozilla email adresses, of servo adresses, of chromium ones, etc.
That was an interesting data for seeing the gap trend between the number of employee at mozilla and at chromium. 
Do you remember the URL? I can't find it..
But I remember there was a disq.us on the blog and you posted a comment.

**Comment by jdm** [comment]
I remember seeing that but I don't remember where. Sorry!

**Comment by LifeIsStrange** [comment]
@jdm Now that the reality that I predicted has come, would you mind to share your thoughts on my proposal AKA the third way?

**Comment by nox** [comment]
You're free to do so on your own, I'm locking this issue.
