### ISSUE TITLE
Know what will be compiled before building?

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24064]
Sometimes the script crate is being built for unknown reason. On Windows this happens often. And it just happened on my Mac.

I'm not sure how to debug that.

Is there a way to tell Cargo to do a dry run? Just report what needs to be compiled. And investigate from here.

**Comment by SimonSapin** [comment]
Sounds like `cargo +nightly build --build-plan -Z unstable-options`, see https://github.com/rust-lang/cargo/issues/5579

For finding out *why* something is rebuilt, setting a `CARGO_LOG=debug` environment variable might help. It’s very verbose though, but can be filtered by module. For example `CARGO_LOG=cargo::core::compiler::fingerprint`. (This the `env_logger` crate, just with a non-default env variable name)

**Comment by paulrouget** [comment]
That's useful. Thank you.

**Comment by jdm** [comment]
Not a servo issue.
