### ISSUE TITLE
Have a minimal UI mode in hololens

### ISSUE THREAD

**Issue by jdm** [servo/servo#24077]
When a protocol activation occurs in the UWP app, we should consider hiding the 2d browser UI and only showing the actual page content. We could also consider having the embedder "is the page allowed to navigate?" query return false, or possibly allow the activator to decide if navigation is allowed by making it a special part of the URL that is used to activate Servo.

The goal here would be to streamline the experience of entering immersive content from a page that is launched from Edge, without having any unnecessary UI.

**Comment by paulrouget** [comment]
I'll look a this.
