### ISSUE TITLE
Block element with no left/top and breaks absolute positioning if it follows an inline element

### ISSUE THREAD

**Issue by kanaka** [servo/servo#24088]
I was trying to reproduce and shrink #17870 with github.com/kanaka/bartender (research project of mine, still very rough) and discovered a more fundamental issue with absolute positioning of block elements:

```html
<!DOCTYPE html>
<html>
<body>

  <div>
    <span>x</span>
    <div style="position : absolute; left: 0; top: 0">X</div>
  </div>

  <div>
    <span>z</span>
    <div style="position : absolute">Z</div>
  </div>

</body>
</html>
```

Firefox 68 (Ubuntu 16.04.2):

![image](https://user-images.githubusercontent.com/70127/63883423-c7c0ee80-c999-11e9-85f0-986d86524844.png)

Servo (built 20190814):

![image](https://user-images.githubusercontent.com/70127/63883649-3ef68280-c99a-11e9-8db5-8bb8ffa9973b.png)

The first case with left/top set has the right position. The second case without left/top has the following div position way off. Also, if the preceding span is removed it renders consistent with Firefox.

Seems like this could be related to https://github.com/servo/servo/issues/9687

**Comment by jdm** [comment]
This appears fixed in layout 2020:
<img width="195" alt="Screenshot 2024-10-05 at 10 50 50 PM" src="https://github.com/user-attachments/assets/1fb03c6f-2dfb-4d08-a5d0-9dd69751414a">
