### ISSUE TITLE
Prompt user to install openxr runtime if it's missing (hololens)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24086]

**Comment by paulrouget** [comment]
@jdm How is the openxr loader loaded?

Should we package the ServoApp with openxr? Or should we prompt the user to install the runtime?

**Comment by jdm** [comment]
There's a Teams thread which describes how we could package the OpenXR runtime in our app in the short term if it will make our testing easier. We can also detect an error in https://github.com/servo/webxr/blob/f71f85bf187fe7aa7d72b6a573b893a4a2f07e44/webxr/openxr/mod.rs#L62 or https://github.com/servo/servo/blob/9b247983902d1fca945a0caff029c42d13c846e7/components/script/dom/xr.rs#L211-L212 and add an informative alert or something.

**Comment by paulrouget** [comment]
I'd rather check that in the hololens code. There's a way to check if a package is installed. I could use that.

Or I could use the C++ openxr loader and see if it fails.
