### ISSUE TITLE
Performance instrumentation

### ISSUE THREAD

**Issue by brson** [servo/servo#241]
We need to be able to make repeatable performance measurements of various kinds. There is very minimal code for this already in servo in the form of a `time` function, but we need much more. We want servo designed for gecko-style telemetry from the beginning, so it would serve us well to do some up-front investigation into what they are doing.

Some types of metrics we care about:

* Speed of specific sections of code
* Latency between two events
* Memory usage of a task over time
* Per-type memory usage

We need a reporting infrastructure that allows measurements to be reported and recorded in a structured way. We'll want to track metrics over time. I imagine having a global metrics task that dumps them to a database at shutdown.

For memory profiling in particular we'll want to make improvements to the Rust runtime, at minimum we'll want a way to give tasks names, associate allocations with names of Rust types, and to be able to periodically interrogate the allocations of a task, maybe register for allocator events.

We'll also need a way to integrate our metrics with whatever metrics SpiderMonkey offers.

**Comment by mbrubeck** [comment]
Servo now has various infrastructure for time and memory profiling.
