### ISSUE TITLE
Replace Servo branding in UWP app with Firefox Reality

### ISSUE THREAD

**Issue by jdm** [servo/servo#24108]
We should remove references to Servo (ServoApp in title, servo:// url handler) from the app and replace them with Firefox Reality instead. We should also create some store asset icons that make use of the FxR logo.

**Comment by paulrouget** [comment]
Should we add, like in Firefox, a branding configuration file for app names and icons?

**Comment by jdm** [comment]
What would be the purpose of making it configurable?

**Comment by paulrouget** [comment]
The UWP app can also be used as a regular Windows Desktop app.

**Comment by paulrouget** [comment]
Doesn't matter for now, could be a follow-up for the day it's necessary.
