### ISSUE TITLE
WACK error for square 44x44 logo asset

### ISSUE THREAD

**Issue by jdm** [servo/servo#24156]
There is one remaining asset error reported by the Windows App Certification Kit:
```
Image file Square44x44Logo.targetsize-24_altform-unplated.png is a default image.
```

cc @paulrouget

**Comment by paulrouget** [comment]
Unplated icons are optional: https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos#unplated-assets

I'll remove them.

**Comment by paulrouget** [comment]
> I'll remove them

Never mind. Without the unplated, on Desktop, the icon has a double padding. I'll keep them and fix the logo.
