### ISSUE TITLE
Make tidy report when a rand exception is no longer needed

### ISSUE THREAD

**Issue by jdm** [servo/servo#24152]
This will avoid the need for PRs like https://github.com/servo/servo/pull/24150 when we notice that a crate no longer depends on the rand crate.

**Comment by atouchet** [comment]
It would probably make sense to include num as well, although I haven't seen any crates using it in Servo for a long time.

**Comment by SiddharthaMishra** [comment]
Hi, I'd like to work on this. Should it report just rand exceptions or files which are exceptions to any blocked packages and no longer need to be?

**Comment by jdm** [comment]
Exceptions to any blocked packages would be a great result!

**Comment by SiddharthaMishra** [comment]
Hey, I removed "goal", "servo_rand" and "ws" from the `[blocked-packages]` section of `servo-tidy.toml` and ran `./mach test-tidy` just to test things out but tidy didn't report back any errors. Am I doing something wrong?

**Comment by jdm** [comment]
Good question! I looked into it and discovered that the errors will appear if you run test-tidy with `--all`, since that will force it to look at the Cargo.lock file and run check_lock. By default test-tidy only runs on files that git reports have changed, which can be frustrating when working on test-tidy itself. There are a few options:
* make a small change to Cargo.lock (like adding an extra newline somewhere)
* add a unit test to python/tidy/servo_tidy_tests that you can run with `./mach test-tidy --self` (this is probably a good idea regardless, since I don't see one for blocked packages)
* make filter_files always yield Cargo.lock

**Comment by SiddharthaMishra** [comment]
If we want filter_files to always yield Cargo.lock is adding something like a `[always-include]` similar to the `[ignore]` in `servo-tidy.toml` all right? If not, should I hard-code a yield of Cargo.lock in filter_files or `FileList::init()`?

**Comment by jdm** [comment]
I am inclined to hardcode it for the time being.

**Comment by SiddharthaMishra** [comment]
I opened a PR for this
