### ISSUE TITLE
Run WACK and make sure no regression occurs

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24173]
It's probably possible to run the WACK validation from the command line. The same way we build the UWP app, we should also run the WACK, to avoid regressions like [this](https://github.com/servo/servo/issues/24156).

**Comment by paulrouget** [comment]
See "Validate your Windows desktop app by using the Windows App Certification Kit 3.3 from a command line" : https://docs.microsoft.com/en-us/windows/win32/win_cert/using-the-windows-app-certification-kit

**Comment by jdm** [comment]
I was able to generate a meaningful WACK report locally with the following preparation:
```
python mach build -r --uwp
python mach package --release --target=x86_64-uwp-windows-msv --uwp=x64
```
Then from a terminal with administrator privileges:
```
C:\Program Files (x86)\Windows Kits\10\App Certification Kit\appcert reset
C:\Program Files (x86)\Windows Kits\10\App Certification Kit\appcert test -appxpackagepath c:\Users\image\servo\support\hololens\AppPackages\ServoApp\ServoApp_1.1.0.0_Test\ServoApp_1.1.0.0_x64.msixbundle -reportoutputpath c:\Users\image\report.xml
```
https://gist.github.com/jdm/97674e9c83de6c8f1617a519996a379d is the resulting XML file. Here's an example of a failing result:
```
    <REQUIREMENT NUMBER="15" TITLE="Supported API test" RATIONALE="The application should only refer to the APIs allowed by the Windows SDK for Windows Store Apps.">
      <TEST INDEX="38" NAME="Supported APIs" DESCRIPTION="Windows Store App must only use supported platform APIs." EXECUTIONTIME="00h:02m:44s.10ms" OPTIONAL="FALSE">
        <MESSAGES>
          <MESSAGE TEXT="API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. openxr_loader.dll calls this API." />
          <MESSAGE TEXT="API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. ServoApp.exe calls this API." />
          <MESSAGE TEXT="API Module32FirstW in kernel32.dll is not supported for this application type. simpleservo.dll calls this API." />
          <MESSAGE TEXT="API Module32NextW in kernel32.dll is not supported for this application type. simpleservo.dll calls this API." />
          <MESSAGE TEXT="API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. simpleservo.dll calls this API." />
          <MESSAGE TEXT="API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. libGLESv2.dll calls this API." />
          <MESSAGE TEXT="API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. libEGL.dll calls this API." />
        </MESSAGES>
        <RESULT><![CDATA[FAIL]]></RESULT>
      </TEST>
    </REQUIREMENT>
```

**Comment by jdm** [comment]
In this case we would want to ignore the __CxxFrameHandler errors, because they are a known issue with the cert kit (https://github.com/microsoft/microsoft-ui-xaml/issues/1446#issuecomment-608070886). The remaining messages are instances of #27136

**Comment by jdm** [comment]
Adding `-testid [38]` to the command line runs the Supported APIs test only, which is the one that is the most likely to regress, and it doesn't involve opening any windows. This may be a useful property for CI.

**Comment by jdm** [comment]
Doing this on CI may be difficult per #27374, but we should add two new mach commands to make this process easier to run regularly:
* `./mach test-wack [--release] [path/to/report.xml]` - verify that an msixbundle is present at the expected path from `./mach package --uwp`, then run the WACK, save the report at the given path, and parse the XML to report failures
* `./mach test-wack-nightly [path/to/report.xm]` - download https://download.servo.org/nightly/uwp/servo-latest.zip, unzip it into a temp directory, run the WACK, save the report at the given path, and parse the XML to report failures
