### ISSUE TITLE
Can't find openxr_loader.dll

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24181]
Getting this error:

```
RUST: WARN - webxr_api::registry - XR device error BackendSpecific("\"The specified module could not be found. (os error 126)\"")
```

This is the part that fails: https://github.com/Ralith/openxrs/blob/71cea14e8b17eba366c579f28b11d8f135f2a398/openxr/src/entry.rs#L64

Regression started with #24140

For now, only tested on the emulator.

/cc @Manishearth

**Comment by jdm** [comment]
I cannot reproduce this in my local environment. I successfully entered immersive mode after installing the OpenXR package from the Windows Store in a debug build in the emulator.

**Comment by paulrouget** [comment]
@jdm can I ask you to clobber first?

**Comment by Manishearth** [comment]
I've been able to run xr content after a full clobber on the device.

**Comment by paulrouget** [comment]
No problem with the device.

**Comment by Manishearth** [comment]
We now use the nuget package too.

**Comment by paulrouget** [comment]
> No problem with the device.

I was wrong. I tested the 2D view only.

**Comment by paulrouget** [comment]
Reverting the nuget commit brings me further (then crash here: https://github.com/servo/webxr/issues/54).

There is something that I must be missing.

Any idea would help.

**Comment by paulrouget** [comment]
Inspecting the appx package, I see that the openxr_loader.dll is not present. While the dll of the other nuget packages are.

My bet is that the nuget package just doesn't include the DLLs. They are present in the nuget package, but they are not included in the final package.

I'm just very confused why it works for both of you.

Can you `rm -rf support/hololens` and `git checkout support/hololens`? There are plenty of build artifact in there that might mess up with a clean build.

**Comment by paulrouget** [comment]
Yeah, I'm pretty sure this is what's going on:

in support/hololens/packages/OpenXR.Loader.1.0.2/build/native/OpenXR.Loader.targets, if I change:

```xml
        <Content
            Include="$(OpenXRLoaderBinaryRoot)\bin\openxr_loader.dll"
            Link="%(Filename)%(Extension)"
            CopyToOutputDirectory="PreserveNewest" />
```

with:

```xml
        <PackagingOutputs Include="$(OpenXRLoaderBinaryRoot)\bin\openxr_loader.dll">
            <OutputGroup>OpenXRLoaderBinaries</OutputGroup>
            <ProjectName>$(ProjectName)</ProjectName>
            <TargetPath>%(Filename)%(Extension)</TargetPath>
        </PackagingOutputs>
```

It works.

**Comment by jdm** [comment]
Could you raise this with our friends in the Teams channel?

**Comment by jdm** [comment]
I can now reproduce this issue in a cleaner build than before.

**Comment by paulrouget** [comment]
> Could you raise this with our friends in the Teams channel?

I did yesterday. Fixed has been been pushed.

> I can now reproduce this issue in a cleaner build than before.

Gonna fix mach clean then.
