### ISSUE TITLE
Support inline sessions in WebXR

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#24186]
We currently only support immersive sessions.

This may be easier to do once https://github.com/servo/webxr/issues/30 is solved.

Diorama sessions are currently not supported by the spec, so this may not be that hard to support.

This also includes support for https://immersive-web.github.io/webxr/#dom-xrrenderstate-inlineverticalfieldofview

**Comment by Manishearth** [comment]
Thinking about the design, since webxr cannot support diorama sessions, perhaps the best design for now is to implement these entirely on the DOM side as a different codepath which uses the window's rAF tick?

This does mean inline sessions with spatial tracking will still not be possible, but that needs https://github.com/servo/webxr/issues/30 .


This would also just make it easier to test XR stuff.

**Comment by Manishearth** [comment]
cc @asajeffrey

**Comment by Manishearth** [comment]
Actually tbh i think we should just have a separate device for this, and deal with the issue of multiple inline sessions being slow later.

**Comment by asajeffrey** [comment]
This makes https://github.com/servo/webxr/issues/30 a higher-priority item.
