### ISSUE TITLE
regression: offscreen gl context panic

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24206]
While running: https://www.joshmatthews.net/webgl-to-webxr/webxr-ar.html

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1280`,
 right: `0`', C:\Users\paul\.cargo\registry\src\github.com-1ecc6299db9ec823\offscreen_gl_context-0.25.0\src\draw_buffer.rs:125:9
```

**Comment by paulrouget** [comment]
My fault.

**Comment by paulrouget** [comment]
I suspect 1cefae7181

**Comment by jdm** [comment]
Is this on Windows? In the HL2 emulator? On device?

**Comment by jdm** [comment]
Apparently check_framebuffer_status is causing a GL error to appear: https://github.com/servo/rust-offscreen-rendering-context/blob/317efd913e52228176155280b7d5a29d5591d1f0/src/draw_buffer.rs#L123-L126

**Comment by jdm** [comment]
I'll see if I can reproduce this today.

**Comment by jdm** [comment]
More specifically, it's coming from https://github.com/servo/rust-offscreen-rendering-context/blob/317efd913e52228176155280b7d5a29d5591d1f0/src/draw_buffer.rs#L247-L250 and I'm not yet sure why.
