### ISSUE TITLE
Implement DOMStringList

### ISSUE THREAD

**Issue by rasviitanen** [servo/servo#24208]
I think we should implement `DOMStringList`.
Spec: https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#domstringlist
Blocks: #6963 

The following warning is listed in the spec. Someone else might have more information on this.
>:warning: New APIs must use `sequence<DOMString>` or equivalent rather than `DOMStringList`

Notes on block:
DOMStringList is needed in order to implement `IndexedDB` according to the specification (both the new 3.0 draft and the W3C recommendation document).

https://www.w3.org/TR/IndexedDB-2/
https://w3c.github.io/IndexedDB/

Used in e.g. the `IDBDataBase` for the object store names. It is also used in `IDBObjectStore` and `IDBTransaction`
```
[Exposed=(Window,Worker)]
interface IDBDatabase : EventTarget {
  readonly attribute DOMString name;
  readonly attribute unsigned long long version;
  readonly attribute DOMStringList objectStoreNames;
...
```

**Comment by jdm** [comment]
If the spec calls for it for your work, I agree.

**Comment by rasviitanen** [comment]
@highfive: assign me
