### ISSUE TITLE
Missing MouseEvent attributes defined by CSSOM View

### ISSUE THREAD

**Issue by jdm** [servo/servo#24248]
https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface

In particular, the pageX/pageY attributes are used by three.js code in http://rawcdn.githack.com/mrdoob/three.js/r105/examples/js/controls/FirstPersonControls.js . This is likely to be a source of surprising web compat issues!

This will likely have an impact on #20931.

**Comment by tigleym** [comment]
I'd like to try working on this. 

@highfive assign me

**Comment by tigleym** [comment]
@jdm the above pull request addresses specifically the `pageX` and `pageY` attributes, although I realize that `offsetX` and `offsetY` are missing as well (https://drafts.csswg.org/cssom-view/#dom-mouseevent-offsetx). 

As for tests, I added a simple one in `tests/wpt/web-platform-tests/css/cssom-view/mouseEvent.html`. I'd like to also test for the existence of the attribute on the interface itself, and it's currently set to fail here: https://github.com/servo/servo/blob/b0b01b86b8e848bf29f557855a58fc1e0d2dff6e/tests/wpt/metadata/css/cssom-view/idlharness.html.ini#L32-L36

I believe I found the corresponding test at https://github.com/servo/servo/blob/b0b01b86b8e848bf29f557855a58fc1e0d2dff6e/tests/wpt/web-platform-tests/css/cssom-view/idlharness.html#L37 

Uncommenting this line still doesn't seem to run the test at all. Perhaps I'm missing something here?

**Comment by jdm** [comment]
Great question about the idlharness test! I dug into it, and it turns out the cssom-view.idl is failing the WebIDL validation tests because the partial interface for MouseEvent that it contains (https://github.com/web-platform-tests/wpt/blob/0d9fecceac869018c2b54b6251600f3d184d98c0/interfaces/cssom-view.idl#L141-L152) duplicates some properties from uievents.webidl (https://github.com/web-platform-tests/wpt/blob/0d9fecceac869018c2b54b6251600f3d184d98c0/interfaces/uievents.idl#L28-L31), and this prevents the MouseEvent interface from being tested.

**Comment by jdm** [comment]
In a delightful twist, there is a known issue in that the CSSOM View spec redefines existing members that is called out at the top of https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface.

**Comment by tigleym** [comment]
Thank you for looking into this! Glad to see the appropriate fix for testing these MouseEvent attributes was merged in: https://github.com/web-platform-tests/wpt/pull/19611

**Comment by jdm** [comment]
We should pick those changes up automatically in tomorrow's sync.

**Comment by tigleym** [comment]
@jdm for the rest of the missing attributes, would you prefer if I created another issue as a follow-up? Or can I make another PR against this same issue?

**Comment by jdm** [comment]
Another PR against this one should be fine.
