### ISSUE TITLE
RFC: Host Rust binaries and use them by default

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#2424]
Now that Rust provides nightly binary builds, it’s easy to run `make dist` and get binary tarball for any rust commit.

Servo currently builds its own Rust compiler through a git submodule pointing at a specific Rust commit. This takes a lot of time, and happens every time we upgrade to a newer Rust commit or whenever the wrong file gets touched for some reason. In particular, this makes using `git bisect` across a Rust upgrade a nightmare.

Instead, we could host binary builds of Rust for platforms Servo supports and use them by default. "Building" Rust-in-Servo would be just downloading a tarball and extracting it. This is not worse in terms of bandwidth than building Rust from source, which itself downloads a "snapshot" binary build in order to bootstrap.

The option to build Rust from source (as today) could stay, for special cases such as cross-compiling. Or maybe the existing "local rust" option is sufficient.

Bonus: keep a local download cache of the Rust tarballs, so that `git bisect` do not need to download them over and over again (only extract them.)

At least at first, we would keep hosting all old Rust builds that any Servo commit expects to be able to download. (Whereas rust-lang.org does not keep old nigthlies.)

It terms of security, we should do (at least) whatever Rust does for snapshots.

**Comment by larsbergstrom** [comment]
We do this now.
