### ISSUE TITLE
Surfman minimal viable demo

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#24256]
A meta-issue for keeping track of servo/surfman...

- [ ] Surface sharing https://github.com/servo/rust-offscreen-rendering-context/issues/133
- [ ] Surfman in webxr https://github.com/servo/webxr/issues/60
- [ ] Implement WebVR on top of webxr https://github.com/servo/servo/issues/24425

The relevant repos and branches are

- https://github.com/pcwalton/surfman
- https://github.com/asajeffrey/swap-chains
- https://github.com/asajeffrey/webxr/tree/surfman
- https://github.com/pcwalton/servo/tree/texture-sharing-iosurface

**Comment by asajeffrey** [comment]
cc @pcwalton

**Comment by asajeffrey** [comment]
We should add more issues to the list above ^

**Comment by asajeffrey** [comment]
The surfman branch of servo: https://github.com/pcwalton/servo/tree/texture-sharing-iosurface
The surfman branch of offscreen-rendering-context https://github.com/pcwalton/rust-offscreen-rendering-context/tree/io-surface-22

**Comment by asajeffrey** [comment]
Long IRC chat with @pcwalton https://mozilla.logbot.info/servo/20190920#c16631244

**Comment by jdm** [comment]
Rebased branches (with some changes mixed in to avoid panics on macOS, sadly) now exist at https://github.com/jdm/servo/tree/texture-sharing-iosurface and https://github.com/jdm/rust-offscreen-rendering-context/tree/io-surface-22.

**Comment by jdm** [comment]
I've verified that WebGL works fine in the desktop UWP build, and it also runs in the HoloLens emulator. However, _something_ is different that causes the HL runtime to put a big blue "Loading" circle over the page content that never goes away.

**Comment by jdm** [comment]
Also for ease of building servo, I'll point out that the only use of surfman in canvas-traits is in the WebGLLockMessage type, which is unused. This means that surfman can be removed from canvas-trait's dependencies and avoids having to rebuild script whenever surfman is modified. I made this change in my rebased and squashed branch.

**Comment by paulrouget** [comment]
> "Loading" circle

Only when showing webgl content?

**Comment by jdm** [comment]
I only tested webgl content, and I haven't reproduced that problem.

**Comment by jdm** [comment]
I made a mistake and didn't actually test a surfman-enabled build with UWP and the emulator. I'm panicking when D3D11CreateDevice returns an unsuccessful result right now, so I'll try to figure out what's going on there.

**Comment by jdm** [comment]
I have updated my branches (https://github.com/jdm/servo/tree/texture-sharing-iosurface and https://github.com/jdm/rust-offscreen-rendering-context/tree/io-surface-22) with changes that allow the UWP desktop app to run webgl content. The resulting rendering is really flickery and stuttery, unfortunately.

**Comment by jdm** [comment]
I've backported my UWP build fixes to pcwalton's branch in https://github.com/pcwalton/surfman/pull/5 and https://github.com/pcwalton/servo/pull/14.

**Comment by asajeffrey** [comment]
I updated the issue description to point to repos and add https://github.com/servo/servo/issues/24425.

**Comment by atouchet** [comment]
Did #24482 finish this?

**Comment by jdm** [comment]
Yep!

**Comment by asajeffrey** [comment]
We decided not to block on https://github.com/servo/servo/issues/24425
