### ISSUE TITLE
Latest UWP nightly never finishes loading

### ISSUE THREAD

**Issue by jdm** [servo/servo#24263]
Even though it's loading about:blank, it seems to go nowhere and the throbber keeps going. Trying to load another URL shows the same behaviour.

**Comment by jdm** [comment]
I'm no longer reproducing this in my local builds off of master or in the latest nightly: https://download.servo.org/nightly/uwp/servo-latest.0.0.0_x64_arm64.appxbundle

**Comment by paulrouget** [comment]
It happened to me. In my case a breakpoint was hit, even though it was not showing in VS. Clearing all the breakpoint in VS solved my problem.

**Comment by atouchet** [comment]
Is this still an issue?

**Comment by jdm** [comment]
I don't believe so.
