### ISSUE TITLE
Can't deploy to HoloLens in release mode (vclibs version mismatch)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24262]
I'm getting this error:

> Error |   | DEP0800: The required framework "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\.\AppX\Retail\ARM64\Microsoft.VCLibs.ARM64.14.00.appx" failed to install. [0x80073D06] Windows cannot install package Microsoft.VCLibs.140.00_14.0.27023.1_arm64__8wekyb3d8bbwe because it has version 14.0.27023.1. A higher version 14.0.27323.0 of this package is already installed. | ServoApp

I do not have this issue with the emulator.
I do not have this issue in debug mode.

**Comment by jdm** [comment]
This may be the same issue we faced with the other device - does it work if you build and deploy VS project from VS 2019? If so, a factory reset on the device may fix the problem and allow using 2017 like usual.

**Comment by paulrouget** [comment]
I've found another (temporary) workaround. Because I only care about Servo being in release mode, I rename target/release to target/debug, and built in debug more. MS people confirmed that using VS2019 or resetting would fix the issue.
