### ISSUE TITLE
ImageData constructors intermix logic

### ISSUE THREAD

**Issue by jdm** [servo/servo#24274]
The ImageData specification has [two constructors](https://html.spec.whatwg.org/multipage/canvas.html#dom-imagedata).  They have different logic about what arguments are valid are not. The implementation of these constructors tries to share code and ends up getting the checks a bit confused, causing some of the automated tests for the specification logic to fail.

Code: `components/script/dom/imagedata.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/2dcontext/pixel-manipulation`

In particular, see `2d.imageData.object.ctor.array.bounds.html`. Remove `tests/wpt/metadata/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.bounds.html.ini` so the test expects to pass, then run `./mach test-wpt tests/wpt/web-platform-tests/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.bounds.html` to see the failing test output in your terminal after closing the window.

**Comment by iinuwa** [comment]
I'll take a look at this.
