### ISSUE TITLE
Support features in webxr, require feature for local-floor access

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#24270]
https://immersive-web.github.io/webxr/#feature-dependencies

We need to support features, and gate the existence of local-floor on the local-floor feature (also the respective features when #24194, #24195 happen)

We should also make inline sessions not require activation if tracking isn't requested (https://github.com/servo/servo/pull/24133#discussion_r327743255)

**Comment by Manishearth** [comment]
We'll also need to require the local feature for local spaces in inline sessions.

**Comment by atouchet** [comment]
Did #25504 fix this?

**Comment by Manishearth** [comment]
Yep
