### ISSUE TITLE
Replace rustc plugins with something else

### ISSUE THREAD

**Issue by jdm** [servo/servo#24281]
The Rust team want to remove the unstable plugin feature: https://github.com/rust-lang/rust/pull/64675 . All the information I have is "I believe current consensus is that anyone using plugins today is advised to migrate to a custom rustc build (via a rustc_private dep on rustc_interface) which should be relatively fast, though not particularly stable, of course, but no less stable than plugins were/are." @Manishearth do you have more information on what this means? Can we copy anything that clippy does?

**Comment by SimonSapin** [comment]
I’ve previously filed https://github.com/rust-lang/rust/issues/62868 hoping to get suggestions about what to do.

**Comment by sagudev** [comment]
We have crown now (rustc driver like clippy but with our lints).
