### ISSUE TITLE
perform_annotated_read_operation should not enqueue a ProcessReadData task for empty blobs

### ISSUE THREAD

**Issue by jdm** [servo/servo#24289]
Test: `./mach test-wpt tests/wpt/web-platform-tests/FileAPI/reading-data-section/filereader_events.any.js`
Code: `components/script/dom/filereader.rs`

The test checks that no progress event is dispatched for a blob containing no bytes. However our implementation in `process_read_data` always dispatches a progress event, so we should check if the blob is not empty before enqueuing a FileReadingTask::ProcessReadData task.

**Comment by SiddharthaMishra** [comment]
@highfive: assign me
