### ISSUE TITLE
XHR upload timeout event should not include request progress/total values

### ISSUE THREAD

**Issue by jdm** [servo/servo#24286]
Spec: https://xhr.spec.whatwg.org/#request-error-steps
Code: `components/script/dom/xmlhttprequest.rs`
Test:
* `./mach test-wpt tests/wpt/web-platform-tests/xhr/event-timeout-order.any.js`
* `./mach test-wpt tests/wpt/web-platform-tests/xhr/send-timeout-events.htm`

`process_partial_response` calls `dispatch_upload_progress_event` and passes None as the second argument, and that method assumes that it can always use the length of the request body. This contradicts the specification, which says that upload events when errors occur should always pass 0 for both values.

**Comment by Ghosty141** [comment]
Hi I'd like to work on this. Should `dispatch_upload_progress_event` check if the partial_load is None and use 0 as length?

**Comment by jdm** [comment]
I think dispatch_upload_progress event needs another argument indicating whether the event is for an error or not.

**Comment by jdm** [comment]
Oh, even better - make the Option argument `Result<Option<..>, ()>` and pass `Err(())` for error cases.

**Comment by LesnyRumcajs** [comment]
@Ghosty141 are you working on this? If not I can grab this one.

**Comment by Asalle** [comment]
@highfive assign @LesnyRumcajs

**Comment by Asalle** [comment]
I failed :(

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/24477 was a solution that looked good but required addressing a few review comments.
