### ISSUE TITLE
XMLHttpRequest.responseXML should return null when a network error occurs

### ISSUE THREAD

**Issue by jdm** [servo/servo#24285]
Spec: https://xhr.spec.whatwg.org/#document-response step 1
Code: `components/script/dom/xmlhttprequest.rs`
Test:
* `./mach test-wpt tests/wpt/web-platform-tests/xhr/xmlhttprequest-network-error.htm`
* `./mach test-wpt tests/wpt/web-platform-tests/xhr/xmlhttprequest-network-error-sync.htm`

We fail the `assert_equals(client.responseXML, null, "responseXML")` check, because we don't check if `self.response_status` is an Err value in the `document_response` method before creating a document response to return.

**Comment by petosorus** [comment]
Hi!
I'm pretty new to rust and would like to check I'm getting it.

1. Should the check of response_status be done between the `response.is_some()` block and the `mime_type` block?
1. If the response_status matches Err, should the return be something like 
```
self.response_xml.set(null);
return self.response_xml.get();
```

Thanks for putting these tasks marked as Easy :)

**Comment by jdm** [comment]
1. Yes
2. There should not be any need to set self.response_xml, since it will be empty already. Returning None directly will be most readable.

**Comment by CYBAI** [comment]
Hi @petosorus , thanks for looking into this!

>     1. Should the check of response_status be done between the `response.is_some()` block and the `mime_type` block?

I think it might be worth mentioning that, with reading the commit of `if response.is_some() {` (347f3c15b2a), it's for caching.

So, as @jdm answered, yes, the check of response_status should be done between `response.is_some()` and `mime_type` block.

Maybe it's worth updating the comment of `response.is_some()` checking and say `Step 1` above `response_status` checking instead? (@jdm what do you think?)

Ex.

```diff
- // Step 1
+ // Caching: if we have existing response xml, redirect it directly
let response = self.response_xml.get();
...

+ // Step 1.
<!-- the response_status check -->
```

**Comment by jdm** [comment]
Yes, that would be an improvement!

**Comment by petosorus** [comment]
Ok, that's cool with me! I'll start tonight then.

@highfive: assign me

**Comment by Ghosty141** [comment]
Hi @petosorus, I also took a look at this issue and hopefully solved it in my fork ([Link](https://github.com/Ghosty141/servo/tree/document_response_fix)). Would you mind if I submit the PR? No problem if you want it though.
