### ISSUE TITLE
Document::SetBody is too strict

### ISSUE THREAD

**Issue by jdm** [servo/servo#24291]
Spec: https://html.spec.whatwg.org/multipage/dom.html#dom-document-body
Code: `components/script/dom/document.rs`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/dom/documents/dom-tree-accessors/Document.body.html`

Step 4 refers to the document element, which can be any element which is the immediate child of the document, but our implementation checks for a document element which is also an `<html>` element.

**Comment by tokarzkj** [comment]
I can take a look. I am new to the project/rust and am looking for ways to contribute.

@highfive: assign me
