### ISSUE TITLE
Integration documentation

### ISSUE THREAD

**Issue by Arteneko** [servo/servo#24305]
I wanted to use the Servo engine as a webview backend in a Qt5 project, but couldn't find any documentation or guide on how to do that.

Is there any existing doc on how to do that?

If not, how can one integrate Servo for rendering web pages in Qt?

**Comment by paulrouget** [comment]
The best way is to use libsimpleservo. It has a c wrapper.

```
./mach build -r --libsimpleservo
```

This will generate a dll/dylib/so and a .h in target/.

You can see an example here: https://github.com/servo/servo/tree/master/support/hololens/ServoApp/ServoControl
