### ISSUE TITLE
Babylonjs support: progress

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24307]
## basic demo

Using the colorpicker demo as a starting point: http://paulrouget.com/test/bbjs/

2D mode: WebGL content renders well (except floor and shadow are black)

Immersive Mode:
- in Firefox + Webxr: works  properly
- glwindow on osx: getting a GL error (1281) here: https://github.com/servo/webxr/blob/d4f585c2a331b9a1d1c7bde84b9483ec514acaae/webxr/glwindow/mod.rs#L140 - ignoring it just gives a blue screen. Missing floor. Maybe the ball is rendered above the head, but we can't pan with glwindow.
- HL device the color wheel and the ball are rendered. But not cleared on update. Leaving a trail as we move. They are also not positioned correctly (too low). The walls look like they have a depth issue.
- HL emulator: new error: `XR device error BackendSpecific("ERROR_INSTANCE_LOST")`

## advanced demos

- Mansion: https://www.babylonjs-playground.com/frame.html#JA1ND3#161
- Hill Valley: https://www.babylonjs-playground.com/frame.html#JA1ND3#163
- Espilit: https://www.babylonjs-playground.com/frame.html#JA1ND3#164

**Comment by paulrouget** [comment]
3 issues:

- black floor
- buffer not cleared
- objects are duplicated

![screencast](https://user-images.githubusercontent.com/373579/65895600-02a8ae80-e3ac-11e9-882f-23450639db37.gif)

**Comment by paulrouget** [comment]
In non immersive mode, we can see the black floor:

![Screen Shot 2019-09-30 at 18 03 10](https://user-images.githubusercontent.com/373579/65895999-a98d4a80-e3ac-11e9-9831-9ec0368cf541.png)

**Comment by jdm** [comment]
I suspect the trails come from us not supporting `preserveDrawingBuffer: false` correctly - we don't actually clear the texture anywhere right now.

**Comment by paulrouget** [comment]
The black walls are due to network errors (security errors):

```
[2019-10-01T05:03:34Z INFO  net::http_loader] request for https://assets.babylonjs.com/environments/backgroundGround.png (GET)
[2019-10-01T05:03:34Z INFO  net::http_loader]  - ("accept", "*/*")
[2019-10-01T05:03:34Z INFO  net::http_loader]  - ("accept-language", "en-US, en; q=0.5")
[2019-10-01T05:03:34Z INFO  net::http_loader]  - ("user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:63.0) Servo/1.0 Firefox/63.0")
[2019-10-01T05:03:34Z INFO  net::http_loader]  - ("host", "assets.babylonjs.com")
[2019-10-01T05:03:34Z INFO  net::http_loader]  - ("accept-encoding", "gzip, deflate, br")
[2019-10-01T05:03:36Z INFO  net::http_loader] response for https://assets.babylonjs.com/environments/backgroundGround.png
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("accept-ranges", "bytes")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("access-control-allow-origin", "*")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("cache-control", "public, max-age=0, must-revalidate")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("content-length", "227862")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("content-type", "image/png")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("date", "Mon, 30 Sep 2019 20:59:42 GMT")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("strict-transport-security", "max-age=31536000")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("etag", "\"356c7531226a49696a6b419026e2e72f-ssl\"")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("age", "29033")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("connection", "keep-alive")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("server", "Netlify")
[2019-10-01T05:03:36Z INFO  net::http_loader]  - ("x-nf-request-id", "011d27af-80c2-41fe-91bb-2d262900122d-1656866")
[2019-10-01T05:03:37Z ERROR script::dom::bindings::error] Error at :0:0 SecurityError: The operation is insecure.
```

**Comment by paulrouget** [comment]
Actually, not a network error, a canvas error: https://github.com/servo/servo/blob/cf725fc3f59bc1b94e3b35ab4cfe60b3d41559cc/components/script/dom/webglrenderingcontext.rs#L570

**Comment by paulrouget** [comment]
Filed https://github.com/servo/servo/issues/24330

**Comment by paulrouget** [comment]
Mansion demo: getting a JS error:

```
TypeError: "this.canvasContext.makeXRCompatible is not a function"
    initializeXRLayerAsync https://preview.babylonjs.com/babylon.js:16
    enterXRAsync https://preview.babylonjs.com/babylon.js:16
    promise callback*ln</e.prototype.enterXRAsync https://preview.babylonjs.com/babylon.js:16
    onclick https://preview.babylonjs.com/babylon.js:16
    s https://preview.babylonjs.com/babylon.js:16
    s https://preview.babylonjs.com/babylon.js:16
    s https://preview.babylonjs.com/babylon.js:16
    s https://preview.babylonjs.com/babylon.js:16
    onclick https://preview.babylonjs.com/babylon.js:16
    CreateAsync https://preview.babylonjs.com/babylon.js:16
    CreateAsync https://preview.babylonjs.com/babylon.js:16
    promise callback*dn</e.CreateAsync https://preview.babylonjs.com/babylon.js:16
    CreateAsync https://preview.babylonjs.com/babylon.js:16
    promise callback*qo</e.CreateAsync https://preview.babylonjs.com/babylon.js:16
    createDefaultXRExperienceAsync https://preview.babylonjs.com/babylon.js:16
    createScene https://www.babylonjs-playground.com/js/frame.js line 73 > eval:9
    f https://preview.babylonjs.com/babylon.js:16
    Append https://preview.babylonjs.com/babylon.js:16
    f https://preview.babylonjs.com/babylon.js:16
    m https://preview.babylonjs.com/babylon.js:16
    addEventListener https://preview.babylonjs.com/babylon.js:16
    s https://preview.babylonjs.com/babylon.js:16
    m https://preview.babylonjs.com/babylon.js:16
    LoadFile https://preview.babylonjs.com/babylon.js:16
    LoadFile https://preview.babylonjs.com/babylon.js:16
    g https://preview.babylonjs.com/babylon.js:16
    e https://preview.babylonjs.com/babylon.js:16
    OfflineProviderFactory https://preview.babylonjs.com/babylon.js:16
    _loadData https://preview.babylonjs.com/babylon.js:16
    Append https://preview.babylonjs.com/babylon.js:16
    createScene https://www.babylonjs-playground.com/js/frame.js line 73 > eval:7
    <anonymous> https://www.babylonjs-playground.com/js/frame.js line 82 > eval:1
    compileAndRun https://www.babylonjs-playground.com/js/frame.js:82
    onreadystatechange https://www.babylonjs-playground.com/js/frame.js:145
    checkHash https://www.babylonjs-playground.com/js/frame.js:141
    <anonymous> https://www.babylonjs-playground.com/js/frame.js:176
    <anonymous> https://www.babylonjs-playground.com/js/frame.js:178
babylon.js:16:1160473

```

Talking to babylonjs people about this.

**Comment by paulrouget** [comment]
Relevant bugzilla bug for firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1580258

**Comment by paulrouget** [comment]
After working around the CORS issue, the 4 demos load fully. But:

- in XR mode, trail issue (most like the preserveDrawingBuffer bug). Making the XR mode un-usable.
- it can take a long time to load. Demos are really heavy, but with Servo, release build, it takes longer. Needs investigation.

**Comment by paulrouget** [comment]
There are pose issues. Moving 45deg slowly and moving 45% fast does not bring the camera to the same position.

**Comment by paulrouget** [comment]
Also the loading screen doesn't show up.

**Comment by paulrouget** [comment]
> There are pose issues. Moving 45deg slowly and moving 45% fast does not bring the camera to the same position. I'll investigate once we made the demos more usable.

This appears to be an artefact. With the basic demo, we can always find the sphere at the right place after moving around.

**Comment by paulrouget** [comment]
Recent changes made the demos behave a lot better (faster).

The 2 main issues so far:
- still pretty slow
- still a trail

Waiting on surfman to investigate the trail, and hopping it will significantly improve the performance.

The demos, even though impressive, are not interactive or do not use immersive-ar. Talking to the bbjs hoping to get some new demos to test.

**Comment by paulrouget** [comment]
Babylonjs demos improvements issue: https://github.com/BabylonJS/Babylon.js/issues/6993

**Comment by paulrouget** [comment]
A new round of testing is necessary. Demos have been updated with various improvements and I've removed ([almost](https://github.com/servo/servo/issues/24363)) all the workaround.

**Comment by jdm** [comment]
https://github.com/paulrouget/paulrouget.github.com/issues/2

**Comment by paulrouget** [comment]
So with the latest improvements, we get to a point where we can load and navigate the different demos. I notice only 2 obvious issues now: the hand laser are only moving in one axis, and, when moving forward/backward the camera move too much.

@jdm is that what you mean by camera issues here https://github.com/servo/servo/issues/24494#issuecomment-551914834

**Comment by paulrouget** [comment]
I'm talking to the bbjs people to get the SVG images replaced with bitmaps when SVG is not supported. In a recent update the "Enter VR" button use a SVG icon only.

**Comment by paulrouget** [comment]
There are 2 other demos to come (see #24703).

**Comment by paulrouget** [comment]
Immersive issues:
- camera issue. Very noticeable with the Button demo.
 - The buttons do not stand still
 - The right eye and the left eye do not match. One is more skewed than the other.
- hand "rays" are not properly following the hand (any demo)
- In the Button demo, interacting with the buttons doesn't trigger the color change.
- The skulls demo triggers a JS error: `controller.vrController.gamepadController is undefined`

2D issues:
- SVG images do not render (no loading animation, Enter VR button does not show)

**Comment by jdm** [comment]
The gamepadController error comes from this JS:
```
    function WebXRControllerModelLoader(input) {
        input.onControllerAddedObservable.add(function (c) {
            if (!c.inputSource.gamepad) {
                return;
            }
```
Because of https://github.com/servo/servo/blob/eb05af27d2bc8597bb7ce54b4b545e5ec99dd84f/components/script/dom/webidls/XRInputSource.webidl#L25.

**Comment by paulrouget** [comment]
Hmm. I thought we fixed that in babylonjs a couple of weeks ago.

**Comment by jdm** [comment]
Maybe the skulls demo is assuming there is a gamepadController property when it shouldn't be, rather than babylon being responsible?

**Comment by paulrouget** [comment]
Update:
* Button demo: left eye and right eyes are not "right" (buttons are skewed weirdly)
* mansion: the hand ray seems to rotate on only one plan. I believe it's a BBJS issue. Some other demos do not have this problem.
* Button and Skull: no interaction possible. I'm not sure yet whether it's because of how bbjs is designed or we're missing an API

I'll be looking at the interaction issue.

**Comment by Manishearth** [comment]
For me the hand ray is moving along with the hand but is not facing the right way. It seems to be using the grip space.

With the camera issue, I'd suspect it's a projection matrix issue -- perhaps our math for depthNear/depthFar is incorrect? I'd be surprised, though, I investigated this pretty thoroughly when dealing with the threejs pose issues, and our projection matrices are correct for threejs. bbjs may be doing something wrong.

**Comment by paulrouget** [comment]
The babylonjs people are aware of this issue. Waiting for them to get back to me.

**Comment by paulrouget** [comment]
Babylonjs issue: https://github.com/BabylonJS/Babylon.js/issues/7236

**Comment by paulrouget** [comment]
I'm going to close this. We now use upstream BBJS code. Only lasting issue is the pointer direction, and it's being taken care of (and on my list of issues to track).
