### ISSUE TITLE
Babylon.js mansion demo doesn't load

### ISSUE THREAD

**Issue by jdm** [servo/servo#24350]
It prefetches a ton of JS scripts, but seems to stop parsing after https://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.6.2/dat.gui.min.js is executed early on during the page load. Debug output claims that the page has finished parsing at that point, but that doesn't make any sense.

**Comment by jdm** [comment]
https://www.babylonjs-playground.com/frame.html#JA1ND3#161

**Comment by jdm** [comment]
Ok, this is caused by the fetch thread for one of the JS scripts hanging in `wait_for_response` for a response that was previously cached during prefetching. Something got missed; maybe we shouldn't have a valid `done_chan` when we've got a cached response?

**Comment by jdm** [comment]
I fear we have some subtle races in the cache code because we have individual mutexes around various fields of the response and cached response objects. We seem to be hitting an issue where the cache code sees that the response body is still in progress so it adds a channel to the body awaiters, but the body finishes before the awaiter is added and so it is never notified.

**Comment by jdm** [comment]
It was not the races that I feared, but I'm still pretty nervous about that risk when I read the code.

**Comment by paulrouget** [comment]
You still get the UI? As in, the bottom bar?

**Comment by jdm** [comment]
In a debug build of Servo, without the patch in #24356 all I saw was a white screen. With #24356 I see the bottom bar.

**Comment by paulrouget** [comment]
Sometimes, I see the bottom bar. I think I had to wait a very long time (minutes?)
