### ISSUE TITLE
CacheKey constructor should take Request by reference

### ISSUE THREAD

**Issue by jdm** [servo/servo#24353]
In CacheKey's `new` method in `http_cache.rs` it takes a `Request` argument by value, but then it calls a method on it that only needs a borrowed value. We clone request objects every time we call `CacheKey::new`, and this is wasteful.

Code: `components/net/http_cache.rs`

No need to run tests; if it builds, that's good enough for a pull request.

**Comment by Tugdual** [comment]
@highfive: assign me

**Comment by PeaceRebel** [comment]
@highfive, I'm new to rust. Instead of cloning, passing a reference would get it done, right?

**Comment by jdm** [comment]
@peaceRebel Yes, that is what I suggested. It looks like @Tugdual is working on this, however.
