### ISSUE TITLE
Timing allow check should only run for cross-origin requests

### ISSUE THREAD

**Issue by jdm** [servo/servo#24367]
Right now we perform the check for every response we get and don't actually compare the current request's origin (or any of the requests in its redirect chain) against the origin of the original source of the request. This means that same-origin requests are treated as failing the timing allow check, which is incorrect.

**Comment by jdm** [comment]
Code: `components/net/http_loader.rs` in `http_network_fetch`.

**Comment by romankl** [comment]
@jdm could I take a look at this one, please?

**Comment by jdm** [comment]
@romankl Sure! The specification is at https://w3c.github.io/resource-timing/#dfn-timing-allow-check; we should be iterating through https://github.com/servo/servo/blob/dc65d825e8a27d6e5604155de7dcb01fcd871123/components/net_traits/response.rs#L91, getting the URL's origin and comparing it against the [request's origin](https://github.com/servo/servo/blob/dc65d825e8a27d6e5604155de7dcb01fcd871123/components/net_traits/request.rs#L359) to determine if they are same origin or not.

**Comment by jdm** [comment]
Of course it looks like the Response's url_list may not be initialized in that code, so we should probably copy it from the request's url list.

**Comment by shnmorimoto** [comment]
Could I grab this issue?

**Comment by shnmorimoto** [comment]
@jdm 

I think that it can check same origin as follows.

```rust
let is_same_origin = request.url_list.iter().any(|url| match request.origin {
        SpecificOrigin(ref immutable_request_origin) => {
            url.clone().into_url().origin().ascii_serialization() ==
                immutable_request_origin.ascii_serialization()
        },
        _ => false,
    });

if !(is_same_origin || req_origin_in_timing_allow || wildcard_present) {
     context.timing.lock().unwrap().mark_timing_check_failed();
}
```

Or, Should I not use `request.url_list` directry?
Should I copy `response.url_list` from `request.url_list`?
