### ISSUE TITLE
DOM Response object doesn't check for opaque filtering

### ISSUE THREAD

**Issue by jdm** [servo/servo#24372]
`FetchResponseListener::process_response` correctly checks for the kind of network response that is received (default, error, opaque, cors, etc.) and calls `Response::set_response_type` to mark the associated DOM Response object as the right kind. However, in the case of the Err and Opaque/OpaqueRedirect cases, it needs to update the members of Response as well to match [the descriptions in the specification](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque).

Code: `components/script/fetch.rs`, `components/script/dom/response.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/fetch/api/cors`

**Comment by PeaceRebel** [comment]
@highfive: assign me

**Comment by PeaceRebel** [comment]
@jdm: Is it `Response::set_response_type` or did you mean `Response::set_type` ?

**Comment by CYBAI** [comment]
> Is it `Response::set_response_type` or did you mean `Response::set_type` ?

@PeaceRebel yeah, I would guess it's a typo and @jdm meant `Response::set_type` 👀
