### ISSUE TITLE
Support gamepads in WebXR

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#24389]
Currently our Gamepad code is tied to the VR API.

It's also not live -- the Gamepad objects need to be manually updated, which is incorrect (https://github.com/servo/servo/issues/23269)

I propose we remove support for `navigator.getGamepads()` and repurpose the existing Gamepad code for WebXR only. We can re-add support for `navigator.getGamepads()` if we ever decide to support standard (like, game controller) gamepads as opposed to XR device gamepads.

**Comment by Manishearth** [comment]
cc @jdm how much do we care about the current rust-webvr gamepad support?

**Comment by jdm** [comment]
If it's holding us back, I'm not too attached to it.

**Comment by msub2** [comment]
@servo-highfive assign me

**Comment by servo-highfive** [comment]
Hey @msub2! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by msub2** [comment]
Companion issue at servo/webxr#227. The main steps required outside of the webxr crate will be:

- Exposing the gamepad attribute of XRInputSource
  - https://github.com/servo/servo/blob/main/components/script/dom/webidls/XRInputSource.webidl#L25
- Applying gamepad frame updates on the active XRSession
  - https://www.w3.org/TR/webxr-gamepads-module-1/#xrsession-interface
- Correctly initializing and mapping the gamepad for "xr-standard"
  - https://www.w3.org/TR/webxr-gamepads-module-1/#gamepad-api-integration
