### ISSUE TITLE
getInputSources API isn't spec-compliant

### ISSUE THREAD

**Issue by jdm** [servo/servo#24395]
The WebXR spec calls for XRSession to have a [inputSources](https://immersive-web.github.io/webxr/#xrsession-interface) attribute that returns a FrozenArray. We have a `getInputSources` method that returns a sequence instead, because of https://github.com/servo/servo/issues/10072. I think the best way to deal with this is make our attribute return an `any` WebIDL value, store a cached JSVal that is a frozen JS array.

**Comment by jdm** [comment]
This breaks various three.js demos.

**Comment by Manishearth** [comment]
It's not a FrozenArray, that was the change we made in the spec, it's an iterable. We support this I think.

**Comment by jdm** [comment]
Indeed!
