### ISSUE TITLE
Implement local storage infrastructure

### ISSUE THREAD

**Issue by brson** [servo/servo#244]
Servo doesn't have any local storage. This will be needed for history, bookmarks, caching and a million other things. At this time we are inclined to use LevelDB for everything, so a good place to start would be LevelDB bindings. Then move on to some of the common browser features and figure out how to integrate them into the engine.

**Comment by Manishearth** [comment]
triage: We have session storage, and a session storage object that pretends to be local storage

**Comment by jdm** [comment]
The features described here aren't related to sessionStorage. I don't see a reason to keep this open right now. We should discuss persistent storage requirements as needed.
