### ISSUE TITLE
URLSearchParams constructor interprets an array as a record

### ISSUE THREAD

**Issue by saschanaz** [servo/servo#24406]
```js
const params = new URLSearchParams(["ab"]);
document.write(params);
```

Expected: An error, because the constructor requires `sequence<sequence<USVString>>`.
Actual: Instead it interprets as a record, so the result is `0=ab&length=1`. The spec says [sequences and records are distinguishable](https://heycam.github.io/webidl/#dfn-distinguishable), so this shouldn't happen.

See also #19776 which is also a distinguishablity problem.

**Comment by saschanaz** [comment]
@highfive assign me

BTW, is it expected that the bot just adds a label without actually adding me as an assignee?

**Comment by CYBAI** [comment]
> BTW, is it expected that the bot just adds a label without actually adding me as an assignee?

Yes, `highfive` bot will only add the `C-assigned` label because GitHub didn't support assigning someone out of the organization when the bot was created.

**Comment by CYBAI** [comment]
Btw, maybe it's good to add the testcase you gave into this one 👀?

https://github.com/servo/servo/blob/1f6402465579e787e63b34b24ac46593c27c2f3d/tests/wpt/web-platform-tests/url/urlsearchparams-constructor.any.js#L150-L158

**Comment by saschanaz** [comment]
This is a general binding problem so it's possible that there already is a failing test elsewhere. I might check after implementing a fix.
