### ISSUE TITLE
Remove syn 0.15 from our crate graph

### ISSUE THREAD

**Issue by nox** [servo/servo#24421]
This is mostly done, but there are still crates relying on it:

* [x] [`glutin`](https://github.com/servo/servo/pull/24887)
* [x] [`image`](https://github.com/image-rs/image/issues/1073)
  * [x] [`tiff`](https://github.com/image-rs/image-tiff/issues/60)
* [x] [`serde`](https://github.com/servo/servo/pull/24887)
* [x] [`webrender`](https://github.com/servo/webrender/issues/3853)
* [x] `webrender_api`
  * [x] [`derive_more`](https://github.com/JelteF/derive_more/issues/91)
  * [x] [`malloc_size_of_derive`](https://github.com/servo/servo/issues/24419)

**Comment by atouchet** [comment]
malloc_size_of_derive has been updated: #24445

**Comment by JelteF** [comment]
I released a new version of `derive_more`, 0.99.1

**Comment by atouchet** [comment]
tiff 0.4.0 has been published but there isn't a release of image with the updated dependency yet.

**Comment by nox** [comment]
#24887 takes care of bumping serde, given the version we still depend on relies on syn 0.15.

**Comment by nox** [comment]
The patch to remove derivative from glutin was backported on the 0.21 branch, we now [just require a new point release of it](https://github.com/rust-windowing/glutin/issues/1241).

**Comment by nox** [comment]
glutin was released and a bump has been included in #24887 for it.

**Comment by Manishearth** [comment]
`style` and `embedder_traits` will also need their `num_derive` dependencies bumped

**Comment by HeroicKatora** [comment]
`image 0.23` was just released and is free of `syn = 0.15`.

**Comment by nox** [comment]
I filed https://github.com/servo/webrender/issues/3853 for updating image in webrender.

**Comment by atouchet** [comment]
image has now been updated in WebRender.
