### ISSUE TITLE
`warning: use of deprecated item 'std::mem::uninitialized'` in uses of cssparser

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#24446]
Since https://github.com/servo/rust-cssparser/pull/252, cssparser uses `MaybeUninit` when available so this warning should not happen. Availability is detected through the `autocfg` crate which tries to compile a test program. At the moment we used `[patch.crates-io]` to use a fork `autocfg` with https://github.com/servo/autocfg/commit/d040e25ff6c129189306011f6a0ff210e08227a0 in order to pass `$RUSTFLAGS` through.

`target/debug/build/cssparser-4f5826496fadb6e9/stderr` contains:

```
"rustc" "--crate-name" "probe0" "--crate-type=lib" "--out-dir" "/home/simon/servo2/target/debug/build/cssparser-4f5826496fadb6e9/out" "--emit=llvm-ir" "--target" "x86_64-unknown-linux-gnu" "" "-C" "link-args=-fuse-ld=gold" "-W" "unused-extern-crates"
error: multiple input filenames provided (first two filenames are `` and `-`)
```

The rustflags handling code passes an empty string as a (positional) argument, which rustc interprets as the name of a source file. `autocfg` sees that rustc errors and assumes this is because `MaybeUninit` is unavailable, so cssparser is instructed to use the deprecated `uninitialized` function instead.

https://github.com/cuviper/autocfg/pull/10 has a proper fix, which is to filter out empty strings: https://github.com/cuviper/autocfg/pull/10/files#diff-b4aea3e418ccdb71239b96952d9cddb6R165

I wanted to push that branch to https://github.com/servo/autocfg where it is less at risk of being removed, but I don’t seem to have push access. @jdm, did you create this repository?

**Comment by jdm** [comment]
I did.

**Comment by SimonSapin** [comment]
Could you make sure appropriate teams have push access? Thanks

**Comment by jdm** [comment]
Done
