### ISSUE TITLE
Some additional dependencies needed for Win10 build?

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#24457]
I was following the default setup build, and was unable to build even default debug on a clean new Win10 unless:
1) `PYTHON3` was set for the SM build (as noted for UWP builds [here](https://github.com/servo/servo/wiki/Building-for-UWP)
2) The Windows Universal Redistributable Runtime was also added to the VS10 or WinSDK installs. Otherwise, I'd get "DLL file `api-ms-win-crt-runtime-l1-1-0.dll` not found!" when attempting to Package MSVC DLLs.

Does that sound right and like some things we should add to the default readme, or particulars of my machine setup?

**Comment by jdm** [comment]
Yes, sounds like those should be present in the default readme.
