### ISSUE TITLE
Post-surfman issues

### ISSUE THREAD

**Issue by jdm** [servo/servo#24484]
Issues that aren't important enough to block merging surfman but we should make a point of coming back to investigate after the merge:

* ~simple babylon demo renders a white screen in the glwindow immersive backend (http://paulrouget.com/test/bbjs/basic/)~
* a number of threejs webvr examples don't show content in immersive mode; verify pre-surfman behaviour here (http://rawcdn.githack.com/mrdoob/three.js/r105/examples/webvr_sandbox.html)

**Comment by paulrouget** [comment]
> simple babylon demo renders a white screen in the glwindow immersive backend (http://paulrouget.com/test/bbjs/basic/)

For me, it crashes (tested on device):

```
RUST: ERROR - canvas::webgl_thread - Last GL operation failed: CreateVertexArray(WebGLSender(..))
Exception thrown at 0x00007FFEA156EAE0 (simpleservo.dll) in ServoApp.exe: 0xC000001D: Illegal Instruction.
thread 'WebGL thread' panicked at 'assertion failed: `(left == right)`
  left: `1282`,
 right: `0`: Unexpected WebGL error: 0x502 (1282) [CreateVertexArray(WebGLSender(..))]', components\canvas\webgl_thread.rs:1678:9
Unhandled exception at 0x00007FFEA156EAE0 (simpleservo.dll) in ServoApp.exe: 0xC000001D: Illegal Instruction.
```

**Comment by jdm** [comment]
These were addressed.
