### ISSUE TITLE
Rename CanvasState methods to use snake_case method names instead of UpperCamelCase, and extract it to its own module

### ISSUE THREAD

**Issue by jdm** [servo/servo#24496]
The member methods of CanvasState were largely extracted from CanvasRenderingContext2D, where they used to be members of the generated CanvasRenderContext2DMethods trait. Now that they are handwritten, it's confusing to have them keep the same naming pattern as generated code. We should rename them so GetImageData becomes get_image_data (for example).

We should also extract CanvasState into its own file in the components/script root directory.

Code: `components/script/dom/canvasrenderingcontext.rs`

**Comment by illiteratewriter** [comment]
Hi, I am just learning Rust, but looking at this issue and going through the code, this seems doable for me. Can I work on this? Also, if I am unable to do this, can I say 'I don't think I can do this' and will you reassign to someone who can do it?

**Comment by jdm** [comment]
Absolutely!

**Comment by Tugdual** [comment]
Hi, if @illiteratewriter doesn't take this issue, I'd like to take it (PS: I'm a beginner with Rust too )

**Comment by illiteratewriter** [comment]
@Tugdual I'm not working on this, so you can take this up.
