### ISSUE TITLE
Limit referer header to 4k

### ISSUE THREAD

**Issue by jdm** [servo/servo#24515]
https://github.com/w3c/webappsec-referrer-policy/pull/122 says that any potential referer header value over 4k in length should be truncated to just the origin. We should update our implementation of the [determine request's referrer](https://github.com/servo/servo/blob/5011e9c21c4c562a1e4b5380be19cef696e305ea/components/net/http_loader.rs#L212-L246) to match this change.

**Comment by teapotd** [comment]
Hi, I'd like to work on this.

@highfive assign me
