### ISSUE TITLE
Odd behaviour with LINE_LOOP in osmesa

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#24538]
With surfman, headless servo fails `/_webgl/conformance/rendering/more-than-65536-indices.html ` due to `LINE_LOOP` drawing yellow rather than green.:
```
  FAIL WebGL test #8: Should be green.
at (0, 0) expected: 0,255,0,255 was 128,128,0,255 - assert_true: Should be green.
at (0, 0) expected: 0,255,0,255 was 128,128,0,255 expected true got false
```
The test passes in x11, and passes if the tests are reordered to make the `LINE_LOOP` test first. This appears to be an odd feature of osmesa.

**Comment by SimonSapin** [comment]
OSMesa-src is no longer used since https://github.com/servo/servo/pull/25853, is this still relevant?

**Comment by jdm** [comment]
No.
