### ISSUE TITLE
CanvasState::IsPointInPath should return false for Nan/infinite values

### ISSUE THREAD

**Issue by jdm** [servo/servo#24540]
Spec: https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-ispointinpath
Implementation: `components/script/dom/canvasrenderingocontext2d.rs`
Tests: `./mach test-wpt /2dcontext/path-objects/2d.path.isPointInPath.nonfinite.html`

**Comment by teapotd** [comment]
@highfive assign me
