### ISSUE TITLE
How to replace the "ActiveX" control in WIN

### ISSUE THREAD

**Issue by LArctic** [servo/servo#24559]
Sorry, I won't program, I will only write some simple scripting languages. I often use the "ActiveX" control to simply load a web page, but it's very old and has a lot of incompatibility. I found "servo" when I was looking for an alternative to ActiveX.
Since there is no programming foundation, I can't tell if it can be used like "ActiveX".
If you can use it like this, is there a related tutorial?

**Comment by jdm** [comment]
From your description, I don't believe Servo is what you are looking for.
