### ISSUE TITLE
`./mach bootstrap` fails on my Ubuntu 18.04 LTS installation

### ISSUE THREAD

**Issue by stephengtuggy** [servo/servo#24561]
When I run `./mach bootstrap`, it errors out. At first I thought that this might be because I had `python3-virtualenv` installed on my machine, but not `python-virtualenv` (the Python 2 version). But now I have both, and I'm still getting errors.

I am running a relatively fresh install of Ubuntu 18.04 LTS, x86_64, on a UEFI-based system with legacy BIOS features turned off. I just reinstalled Ubuntu about a month ago. I have been pretty busy with development activities on it, though. I have a 6-core, 3-GHz, 8th-gen Core i5 processor, and 16 GB of DDR4-2666 SDRAM.

The error output in my terminal is as follows:

```
Traceback (most recent call last):
  File "./mach", line 103, in <module>
    main(sys.argv)
  File "./mach", line 31, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/<username>/Projects/repos/git/GitHub/servo/servo/python/mach_bootstrap.py", line 227, in bootstrap_command_only
    from servo.bootstrap import bootstrap
  File "/home/<username>/Projects/repos/git/GitHub/servo/servo/python/servo/bootstrap.py", line 11, in <module>
    import distro
ImportError: No module named distro
```

It's worth noting that I have at least three different versions of Python installed on my computer, at the Ubuntu system level: 2.7, 3.6, and 3.7.

What other information do you guys need?

Thanks!

**Comment by jdm** [comment]
Same issue as https://github.com/servo/servo/issues/24541. To work around it right now, install the `distro` pip package.

**Comment by JoshMcguigan** [comment]
@highfive: assign me

**Comment by JoshMcguigan** [comment]
I've opened PR #24567 which resolves this issue on my machine.

**Comment by stephengtuggy** [comment]
BTW, I wanted to thank you guys for jumping on this so quickly after I posted the issue. Much appreciated. It seems like there is a very healthy level of engagement among this community. Kudos!
