### ISSUE TITLE
Please release selectors crate

### ISSUE THREAD

**Issue by federicomenaquintero** [servo/servo#24574]
Could we please have a new release of the selectors crate?  I could really use the fix for #22972 in librsvg :smiley:

**Comment by jdm** [comment]
Paging @emilio. I forget whether mozilla-central or servo is considered the source of truth these days.

**Comment by emilio** [comment]
Shouldn't really matter, both should be almost in sync, if not fully in sync.

But I could do a sync and then report back.

**Comment by mashedcode** [comment]
Could we please have a new release of the selectors crate so that we can use/avoid clashes with the new cssparser version?

**Comment by atouchet** [comment]
selectors has been updated in Servo: #25330

This just needs to be published to crates.io now.

**Comment by emilio** [comment]
Ah, there's another gotcha.

```
$ cargo publish                                                                                                                                                                                                                            
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `to_shmem` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```

I'll release a version with the servo_arc / to_shmem bits stripped off, and tag it somewhere on the repo.

**Comment by emilio** [comment]
Published v.0.22.0: https://github.com/emilio/servo/releases/tag/selectors-v0.22.0

@jdm / @SimonSapin  I no longer have the right to push tags to the repo it seems, mind pushing that for me (or restoring my push access I guess? I _think_ I used to have it)

Sorry this took so long :(

**Comment by jdm** [comment]
You should now have the access that allows pushing tags.

**Comment by atouchet** [comment]
https://crates.io/crates/selectors/0.22.0

**Comment by emilio** [comment]
https://github.com/servo/servo/releases/tag/selectors-v0.22.0

Thanks @jdm

**Comment by federicomenaquintero** [comment]
Thank you!!!  This is now being used in librsvg master.
