### ISSUE TITLE
babylonjs demo crashes since Angle update

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24578]
I should have tested with the babylonjs demos as well:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1286`,
 right: `0`: Unexpected WebGL error: 0x506 (1286)', components\canvas\webgl_thread.rs:1713:9
```

/cc @jdm

**Comment by jdm** [comment]
This occurs because the new ANGLE does not like when a framebuffer's color attachment is a texture initialized with GL_RGBA and GL_FLOAT. I'm going to investigate how Firefox treats this, as well as why the old ANGLE allowed it.
