### ISSUE TITLE
Failing to parse a URL in the UWP app causes a panic

### ISSUE THREAD

**Issue by jdm** [servo/servo#24589]
Try to load an invalid URL in the UWP app and watch it panic. We should pop up an alert dialog or something, but it should really be ignored rather than bring down the browser.

**Comment by paulrouget** [comment]
I can't reproduce. An invalid URL should load duckduckgo or show an error message.
Can you share an example of an invalid URL?
Do you just type it in the url bar?

**Comment by jdm** [comment]
Hmm. I know that a panic was caught in https://github.com/servo/servo/blob/d671010e466839010ca76c1292b8dc936941a3f0/ports/libsimpleservo/capi/src/lib.rs#L434-L439 when I tried to paste a URL. I assumed what had happened was that I ended up with something like `https://mrdoob.neocities.org/018/https://mrdoob.neocities.org/019/`, but I didn't see the actual URL that I tried to load.

**Comment by paulrouget** [comment]
Right. It's better if this would not panic. But I don't see how we could end up with a non-valid URL there.

I'll investigate, and at least handle invalid URL better.
