### ISSUE TITLE
Store Option<ImageInfo> instead of making fields of ImageInfo optional

### ISSUE THREAD

**Issue by jdm** [servo/servo#24582]
The code in WebGLTexture stores an array of ImageInfo objects. Each of these objects has a `is_initialized` field, and other fields that are given default values. This makes the code harder to reason about; it would be easier to read if the array contained `Option<ImageInfo>` instead and any checks for initialization checked for `is_none()` or `is_some()` instead.

Code: `components/script/dom/webgltexture.rs`
Tests: `./mach test-wpt tests/wpt/webgl/tests/conformance/textures` (there should be no difference before and after)

**Comment by teapotd** [comment]
@highfive assign me
