### ISSUE TITLE
Implement preserveDrawingBuffe=true support for webgl

### ISSUE THREAD

**Issue by jdm** [servo/servo#24604]
#24482 adds multiple frame buffers so we don't get preserveDrawingBuffer=true support for free any more by choosing not to clear them. We need to add some code in handle_swap_buffers to copy the previous framebuffer's contents to the new framebuffer.

**Comment by asajeffrey** [comment]
The method for doing that blit can be added to `surfman-chains` (which is where the matching clear method lives). The update to servo is then just to call clear or blit.

**Comment by jdm** [comment]
This is required for https://rawcdn.githack.com/mrdoob/three.js/r105/examples/webgl_trails.html.
