### ISSUE TITLE
Implement SubmitEvent for form submit events

### ISSUE THREAD

**Issue by jdm** [servo/servo#24617]
https://github.com/whatwg/html/pull/4984

**Comment by pshaughn** [comment]
WPT html/semantics/forms/form-submission-0/SubmitEvent.window.html

**Comment by pshaughn** [comment]
In form-submission-algorthm.html it's evident that submit handlers do fire, but not with a SubmitEvent in particular, and without event.submitter.

**Comment by pshaughn** [comment]
Even though the constructor can't actually throw, I ended up having to mark it [Throws] to make codegen produce a function signature that made sense (otherwise it was passing in a &DomRoot). Is that a known problem?
