### ISSUE TITLE
Remove support for optional webgl threads

### ISSUE THREAD

**Issue by jdm** [servo/servo#24610]
The call to `create_constellation` in components/servo/lib.rs now passes a Some value for the webgl threads, so we should remove the ability to pass an Option at all. This should wait until after #24482 merges.

**Comment by kunalmohan** [comment]
I'd like to solve this, if it's not a problem :)

**Comment by jdm** [comment]
Please do!

**Comment by kunalmohan** [comment]
What should be the expected behaviour in case [`create_webgl_threads()`](https://github.com/servo/servo/blob/1a6f08f698a720022a41738f0ba072dae86cadb8/components/servo/lib.rs#L1062) returns `None`?

**Comment by jdm** [comment]
Ah, I see this code has changed since I originally filed it - we now pass the result of create_webgl_threads to create_constellation, so we can actually pass non-Some values now. Sorry for not noticing that!
