### ISSUE TITLE
fedora core prerequisites

### ISSUE THREAD

**Issue by zertyuiop** [servo/servo#2462]
servo needs fontconfig-devel, libXi-devel, libXRendr-devel and expat-devel for make

**Comment by genodeftest** [comment]
With the current status in README.md I am able to compile servo. The packages fontconfig-devel, libXi-devel and expat-devel are included. The package libXRendr-devel is not included and does not exist on Fedora 22. I think you mean libXrandr-devel which is listed in README.md too.
