### ISSUE TITLE
Response object's mime type is not updated by fetch algorithm

### ISSUE THREAD

**Issue by jdm** [servo/servo#24628]
[This code](https://github.com/servo/servo/blob/03f223663f1c0bc7432f0f47b533fb41c0226eb1/components/script/fetch.rs#L227-L251) fills in the DOM response object's headers when an HTTP response is received, but the [mime_type](https://github.com/servo/servo/blob/8e14894faeaefad84debbfa1b5363d5eea5deda0/components/script/dom/response.rs#L38) is not updated based on the Content-Type header.

Code: `components/script/dom/response.rs`, `components/script/fetch.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/fetch/api`

**Comment by glowe** [comment]
@highfive: assign me.
