### ISSUE TITLE
Make it so test-tidy with clang-format run on the CI

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24637]
If I understand correctly, test-tidy only run on Linux. We need to figure out how to run the same clang-format version on both linux and windows, so we can activate CPP formatting tests on the CI.

**Comment by jdm** [comment]
The other option is to add a test-tidy invocation to the windows CI as well.

**Comment by paulrouget** [comment]
@jdm is llvm 9 installed on the windows CI?

**Comment by jdm** [comment]
All windows builds, local and CI, use the same set of LLVM binaries that are downloaded during the build command by mach. You can check the version in python/servo/packages.py.

**Comment by paulrouget** [comment]
Fixed #24692
