### ISSUE TITLE
Figure out which exceptions we can safely ignore (uwp)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24647]
These are the default exceptions that VS will break on if they are thrown:

![Screen Shot 2019-11-04 at 15 17 38](https://user-images.githubusercontent.com/373579/68127465-41370900-ff16-11e9-83c8-6201d456ab06.png)

Selecting all the exceptions shows that we have some other exceptions occurring that we ignore. For example, breaking on all the exceptions makes it impossible to start Servo on the device.

Maybe the default configuration is enough. Maybe we should run Servo in strict mode (break on all exceptions).

**Comment by jdm** [comment]
So far the defaults appear to be working out ok.
