### ISSUE TITLE
Appveyor builds not working

### ISSUE THREAD

**Issue by 10by10pixel** [servo/servo#24650]
Right now the read me badge for Appveyor reads: ![Windows Build | Project not found or access denied.](https://user-images.githubusercontent.com/5394990/68135757-2f436f00-fef2-11e9-8414-7ac65a895490.png). Clicking on it reveals an Appveyor page with the same error.

**Comment by jdm** [comment]
Thanks. I've submitted https://github.com/servo/servo/pull/24651 to remove that badge.

**Comment by 10by10pixel** [comment]
Is Windows no longer supported?

**Comment by jdm** [comment]
It's definitely supported. We just don't rely on Appveyor for our windows CI needs any more. The CI we do use for it doesn't have badges, as far as I know.

**Comment by 10by10pixel** [comment]
Gotcha. Thanks for the quick replies.
