### ISSUE TITLE
Embedding example?

### ISSUE THREAD

**Issue by VinnyVicious** [servo/servo#24654]
Is there a small embedding example that showcases how to use Servo as a library? I'm trying to create a small window on X11 that just loads `google.com` with Servo.

**Comment by jdm** [comment]
https://github.com/servo/servo/tree/master/ports/libsimpleservo are crates that are designed to encapsulate embedding Servo in a relatively small set of traits. https://github.com/servo/servo/tree/master/support/magicleap and https://github.com/servo/servo/tree/master/support/hololens are two embeddings that make use of these crates.

**Comment by VinnyVicious** [comment]
> It is limited to only one view (no tabs, no multiple rendering area).

Does that mean that I have to implement tabs myself, or that it isn't possible at all to implement multiple rendering areas? Because I was planning to implement tabs myself.

**Comment by jdm** [comment]
@paulrouget What's the answer to the question in the previous comment?

**Comment by paulrouget** [comment]
> Does that mean that I have to implement tabs myself, or that it isn't possible at all to implement multiple rendering areas? Because I was planning to implement tabs myself.

Tabs are supported with the Rust API. It is not supported by the C API though, but it should be fairly easy to expose the feature to the C API.

Note: for now Servo supports only one compositor. That means only on GL buffer.

@VinnyVicious which toolkit and which language are you planning to use?

**Comment by VinnyVicious** [comment]
I'm willing to use anything that works better with Servo. Do you happen to have a minimal example in Rust? Since it needs GL, I'm assuming I also need glutin?

**Comment by paulrouget** [comment]
[ports/glutin](https://github.com/servo/servo/tree/master/ports/glutin) is an example of a basic browser based on top of the Rust API. The problem with Glutin is that it doesn't come with a widget toolkit. You can use any toolkit you want. The only requirement is providing GL methods and build an event loop.

What's your end goal?

**Comment by VinnyVicious** [comment]
Oh, I don't want to build a full browser. Just wanted to play around and create something for my own needs.

**Comment by paulrouget** [comment]
If you want to user Rust and Glutin (no toolkit), look at ports/glutin. If you want another language with a toolkit (GTK, AppKit, …), look at how libsimpleservo is used in supports/hololens/.

**Comment by VinnyVicious** [comment]
Thank you!
