### ISSUE TITLE
script indirectly depends on webrender

### ISSUE THREAD

**Issue by jdm** [servo/servo#24686]
Theoretically script only needs to depend on webrender_api, but we have:
script -> media -> webrender_traits -> webrender

It would be great to break this dependency. webrender_traits only uses webrender::ExternalImageHandler and webrender::ExternalImage. It seems like these should be part of the public webrender_api crate instead.

**Comment by jdm** [comment]
https://github.com/servo/webrender/pull/3796

**Comment by mrobinson** [comment]
`ExternalImage` and `ExternalImageHandler` are now part of `webrender_api` and `webrender_traits` no longer depends on `webrender`.
