### ISSUE TITLE
HoloLens and Immersive Mode: generic way to exit?

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24693]
What should be to proper way to leave the immersive mode without relying on the page calling `session.end()`? Should we provide a generic method to exit, or does HoloLens provide a way of doing that?

@Manishearth do you have any idea?

**Comment by Manishearth** [comment]
I think opening the start menu and hitting home should exit the session.

We do that already, but we also exit on STOPPING states which we aren't supposed to (https://github.com/servo/webxr/pull/78)

The openxr state stuff is somewhat broken on the hololens and we need to wait it out for some fixes.

**Comment by paulrouget** [comment]
> I think opening the start menu and hitting home should exit the session.

Right. But we do not go back to 2D mode. We have to re-activate the window. Which might be good enough.

**Comment by Manishearth** [comment]
Perhaps there is a way we can make it so that the window doesn't need to be
reactivated?
