### ISSUE TITLE
Hololens click events not working for some people

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#24698]
I first thought this was a platform issue, but some folks (including @pcwalton) are having trouble clicking links (etc) on Servo's 2D hololens port.

It might be related to https://github.com/servo/servo/pull/24547 . I haven't really investigated this since I can't easily replicate it myself, but I think these folks poke instead of tap, and that may trigger mouse events instead of touch events or something.

I _think_ the "tap shadow ripple" which happens when you click on servo is still visible for these folks. (Is that `panel.PointerPressed()`)

The DOM synthesizes events at some point and perhaps our events are in conflict with those.

I might let Patrick use the device with some logging at some point.

cc @paulrouget

**Comment by paulrouget** [comment]
Might be https://github.com/servo/servo/issues/24596 - I'll be looking at this this week.

**Comment by paulrouget** [comment]
I'm not sure how to reproduce.

The UWP port follows these guidelines: https://docs.microsoft.com/en-us/windows/uwp/design/input/handle-pointer-input

Mouse down and up are triggered on released and pressed. Click is triggered on tap.

What is a "poke"? Is it https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.holding ?

> I think the "tap shadow ripple" which happens when you click on servo is still visible for these folk

Can you explain a bit more?

**Comment by Manishearth** [comment]
By poke I mean that their fingers go through the window instead of briefly making contact.

When you click things in servo you hear a sound and a little shadow appears around the clock, that's the shadow ripple I'm talking about.

**Comment by paulrouget** [comment]
Would be interesting to see if they miss-click in IE as well.

**Comment by Yonet** [comment]
Click events works on Edge, but not on Servo.
Edge: https://youtu.be/2uv_m_VJMfU
Servo: https://youtu.be/6oYLFx3YwMQ

**Comment by Manishearth** [comment]
Hmm, this should have been fixed in https://github.com/servo/servo/pull/25076 cc @paulrouget

**Comment by paulrouget** [comment]
Back from holidays. I’ll look soon.

**Comment by pshaughn** [comment]
This is probably unrelated but I want to point it out just in case it is a part of the problem: clicks as currently implemented in Servo aren't doing a good job of bubbling upward, so for instance if you managed to target the text node inside a button with a click you wouldn't necessarily register a click on the button. #25488 is my attempt to fix that sort of thing.

**Comment by paulrouget** [comment]
> Click events works on Edge, but not on Servo.
> Edge: https://youtu.be/2uv_m_VJMfU
> Servo: https://youtu.be/6oYLFx3YwMQ

Wow, even the mouse move events are not sent.

**Comment by paulrouget** [comment]
I’m not sure @yonet issue is directly related to this click issue.

@Yonet do you mind filing another issue for your specific problem (which looks more serious that this specific click issue)? And in that new issue, can you tell me if you can click on the “reload” button in Servo’s toolbar?

**Comment by Yonet** [comment]
@paulrouget sorry for the late reply. Click works great at the moment. Thanks!
