### ISSUE TITLE
Restore macOS CI workers

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#24691]
Some of them are out of the main worker pool because of various build issues:

https://github.com/servo/taskcluster-config/blob/28983e05/config/worker-pools.yml#L13-L24

* [x] `mac1`: https://github.com/servo/servo/pull/24689#issuecomment-551422520
* [x] `mac3`: https://github.com/servo/servo/issues/24755
* [x] `mac9`: https://github.com/servo/servo/pull/24688
* [x] `mac8`: https://github.com/servo/servo/issues/23429

**Comment by SimonSapin** [comment]
CC @jdm

**Comment by jdm** [comment]
mac8 was taken out of the pool because of https://github.com/servo/servo/issues/23429.

**Comment by SimonSapin** [comment]
I think https://github.com/servo/servo/pull/24753 fixed the issues with mac1 and mac9. https://community-tc.services.mozilla.com/tasks/groups/DBt9ki9gTdWmwAk-VDorzw shows a build + full WPT run on each of them. Only one WPT chunk task has filtered unexpected test results, three of them. Which is (unfortunately) not unusual.

**Comment by SimonSapin** [comment]
I’ve moved mac1 and mac9 back to the main pool in https://github.com/servo/taskcluster-config/pull/11.

mac8 however showed a higher than usual number of errors, in two separate WPT runs:

* https://community-tc.services.mozilla.com/tasks/groups/DL4zftVfSqW3WOTC3IoFcg
* https://community-tc.services.mozilla.com/tasks/groups/EmPIwYD5TXq2VakznSgptw

**Comment by SimonSapin** [comment]
I’ve asked Macstadium to wipe mac8 which seemed to help: https://github.com/servo/taskcluster-config/pull/16

All nine workers are back in the main pool now.
