### ISSUE TITLE
sccache consistently errors on CI since Rust nightly-2019-11-07

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#24714]
https://community-tc.services.mozilla.com/tasks/NvN6U22bQ-C626hsVGu4fA

```
error: failed to execute compile
caused by: error reading compile response from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
error: could not compile `script`.
```

The error message is the same as in https://github.com/servo/servo/issues/24510, but setting `SCCACHE_IDLE_TIMEOUT` to zero does not help.

Merges in the regression range of `nightly-2019-11-06` to `nightly-2019-11-07` https://github.com/rust-lang/rust/compare/1423bec54...38048763e:

* Auto merge of https://github.com/rust-lang/rust/pull/65728 - ecstatic-morse:promotion-const-proj
* Auto merge of https://github.com/rust-lang/rust/pull/65134 - davidtwco:issue-19834-improper-ctypes-in-extern-C-fn
* Auto merge of https://github.com/rust-lang/rust/pull/65830 - Quantumplation:master
* Auto merge of https://github.com/rust-lang/rust/pull/66143 - Centril:rollup-qmzuex0
* Rollup merge of https://github.com/rust-lang/rust/pull/66139 - euclio:pluralize
* Rollup merge of https://github.com/rust-lang/rust/pull/66133 - alexcrichton:update-wasi-libc
* Rollup merge of https://github.com/rust-lang/rust/pull/66103 - smaeul:patch/thumb-musl
* Rollup merge of https://github.com/rust-lang/rust/pull/66092 - niacat:master
* Rollup merge of https://github.com/rust-lang/rust/pull/66086 - RalfJung:smallvec
* Rollup merge of https://github.com/rust-lang/rust/pull/66062 - smaeul:patch/pic-level
* Rollup merge of https://github.com/rust-lang/rust/pull/66015 - popzxc:refactor-librustc_parser
* Rollup merge of https://github.com/rust-lang/rust/pull/65973 - eddyb:caller-location-panic
* Rollup merge of https://github.com/rust-lang/rust/pull/65776 - nnethercote:rename-LocalInternedString-and-more
* Auto merge of https://github.com/rust-lang/rust/pull/66141 - Centril:rollup-n2fcvp9
* Rollup merge of https://github.com/rust-lang/rust/pull/66115 - eddyb:global-meta-what
* Rollup merge of https://github.com/rust-lang/rust/pull/66106 - JOE1994:master
* Rollup merge of https://github.com/rust-lang/rust/pull/66101 - estebank:break-tail-e0308
* Rollup merge of https://github.com/rust-lang/rust/pull/66098 - estebank:path-asciption-typo
* Rollup merge of https://github.com/rust-lang/rust/pull/66093 - estebank:fmt-ice
* Rollup merge of https://github.com/rust-lang/rust/pull/66081 - RalfJung:ptr-offset
* Rollup merge of https://github.com/rust-lang/rust/pull/66068 - euclio:null-emitter
* Rollup merge of https://github.com/rust-lang/rust/pull/66054 - petrochenkov:delspan
* Rollup merge of https://github.com/rust-lang/rust/pull/66027 - Mark-Simulacrum:panic-handler-query
* Rollup merge of https://github.com/rust-lang/rust/pull/66014 - dkadashev:47319-type-param-def-location
* Rollup merge of https://github.com/rust-lang/rust/pull/65892 - pnkfelix:trim-special-derives

**Comment by jdm** [comment]
What's the best way to tackle this? Try to reproduce this locally?

**Comment by SimonSapin** [comment]
I haven’t managed to reproduce when building on my machine with the same version of sccache.

The output shows that this errors occurs when `read_exact` fails to read 4 bytes from a `BufReader<TcpStream>`.

https://github.com/mozilla/sccache/blob/f1322dca19577310cfcfb40059ff954d2140598b/src/client.rs#L56-L59

This happens when `libc::recv` returns 0, which indicates that the TCP connection has been closed.

**Comment by jdm** [comment]
Is it worth seeing if there's any interesting compiler output on CI if we don't use sccache?

**Comment by SimonSapin** [comment]
Good idea, I’ve started https://community-tc.services.mozilla.com/tasks/Wxja6BOTQ6OYbp-79FhFtA to try that.

**Comment by SimonSapin** [comment]
By the way, my workflow for this kind of "try build" without a PR is:

* Make a local branch
* Make changes to try
* In the `try-taskcluster` list in the `by_branch_name` dict in `etc/taskcluster/decision_task.py`, add tasks to be run
* Commit
* `git push origin -f HEAD:try-taskcluster`
* Navigate to https://github.com/servo/servo/commits/try-taskcluster
* Click the orange dot on the latest commit (which should be the one you just pushed)
* Click "Community-TC (push)" to view the task group on Taskcluster

It’s mostly out of habit, I don’t know if it’s really better or worse than using `try*` Homu commands in a PR that is not destined to be merged.

**Comment by SimonSapin** [comment]
> if we don't use sccache?

https://community-tc.services.mozilla.com/tasks/Wxja6BOTQ6OYbp-79FhFtA succeeded. The only thing of note is that it generated more than 300k stderr lines worth of warnings, most of them from https://github.com/servo/servo/issues/24684. And https://github.com/rust-lang/rust/pull/65134 is in the regression range.

I’ve also started https://community-tc.services.mozilla.com/tasks/BgPRR43VTKWDVM8nY6A5Ew with `RUST_LOG=trace` into a log file for the sccache server.

**Comment by SimonSapin** [comment]
https://community-tc.services.mozilla.com/tasks/BgPRR43VTKWDVM8nY6A5Ew/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FBgPRR43VTKWDVM8nY6A5Ew%2Fruns%2F0%2Fartifacts%2Fpublic%2Fsccache.log#L321219

```
ERROR 2019-11-12T15:31:54Z: sccache::server: frame size too big
```

https://github.com/tokio-rs/tokio/blob/master/tokio-util/src/codec/length_delimited.rs

```rust
            // Default max frame length of 8MB
            max_frame_len: 8 * 1_024 * 1_024,
```

https://github.com/mozilla/sccache/issues/329 / https://github.com/mozilla/sccache/blob/master/src/server.rs

```rust
        if let Ok(max_frame_length_str) = env::var("SCCACHE_MAX_FRAME_LENGTH") {
            if let Ok(max_frame_length) = max_frame_length_str.parse::<usize>() {
                builder.max_frame_length(max_frame_length);
```

**Comment by SimonSapin** [comment]
https://community-tc.services.mozilla.com/tasks/LpLx0VqfTaqiCXEmEo-Qfw is green with `SCCACHE_MAX_FRAME_LENGTH` set to 100 MB.
