### ISSUE TITLE
Images loaded from file:// urls are not meaningfully cached

### ISSUE THREAD

**Issue by jdm** [servo/servo#24720]
`RUST_LOG=net ./mach run tests/wpt/mozilla/tests/css/background_size_zero_a.html` shows an endless stream of image loads happening because there's a new opaque origin provided every time. This is fallout from https://github.com/servo/servo/pull/24340, presumably because file:// urls generate a new opaque origin. This happens because when we create a LayoutContext in layout_thread/lib.rs, we pass `self.url.origin()` as the origin that gets used in get_or_request_image_or_meta, when we should be obtaining it from the window when kicking off reflow instead.

**Comment by nmvk** [comment]
@highfive assign me

**Comment by kunalmohan** [comment]
@nmvk are you still working on this issue? If not I'd like to give it a try.

**Comment by jdm** [comment]
@kunalmohan It's been several months with no update; I think you can start working on it :)

**Comment by kunalmohan** [comment]
Thanks @jdm! I'll get started with it right away.

**Comment by kunalmohan** [comment]
@jdm I am going to need some help here. I am trying to understand the flow of things that are happening here. Here's in brief of what I have understood-
1. The `get_or_request_image_or_meta` function calls `find_image_or_metadata` function under `net/image_cache.rs`.
2. `find_image_or_metadata` calls `get_cache` fn which should return `CacheResult::Hit` (in case of reflow) but instead returns `CacheResult::Miss` (`Miss` should be returned just for the first time).
3. This causes the image image to be listed as a pending image.

Am I right here?

**Comment by jdm** [comment]
Yes, that is correct.
