### ISSUE TITLE
Intermittent reftest failures on linux (blank rendering)

### ISSUE THREAD

**Issue by jdm** [servo/servo#24726]
I've noticed this in two different pull requests since yesterday, and I'm pretty sure we've been ignoring these intermittent failures for an indeterminate amount of time. One test result looks like:
<img width="631" alt="Screen Shot 2019-11-13 at 10 51 15 AM" src="https://user-images.githubusercontent.com/27658/68779982-8a1c4b00-0603-11ea-941a-10d05197c7ef.png">
The other test result is completely blank. This has been observed with /css/CSS2/text/text-transform-applies-to-013.xht and /css/CSS2/fonts/shand-font-002.xht so far.

**Comment by jdm** [comment]
Observed in /css/CSS2/margin-padding-clear/margin-left-103.xht, so it's not just font-related:
<img width="259" alt="Screen Shot 2019-11-13 at 3 22 29 PM" src="https://user-images.githubusercontent.com/27658/68801127-6c61dc80-0629-11ea-89fb-eb3e78dcfc66.png">

**Comment by jdm** [comment]
One theory: https://github.com/servo/servo/pull/24677 might have caused some layout or compositing code to believe that the window is incorrectly sized.

**Comment by jdm** [comment]
Seen in https://github.com/servo/servo/commit/59eca0260c9800dab52cf314b03554a061a6d733.

**Comment by jdm** [comment]
More specifically, #24700 did not merge but #24701 did which include the same changes.

**Comment by jdm** [comment]
I plan to test this theory by reverting changes since https://github.com/servo/servo/commit/e5689df6b44696bf24f8757cd1f6e14d1aabf6f0 and throwing this at try-wpt many times.

**Comment by jdm** [comment]
Attempting to find the regression range is challenging because:
* we migrated the linux try from buildbot to taskcluster in the window, so this requires cherry-picking the commits from #24753, #24768, #24785, and #24811 in that order
* any pull request for try needs to merge cleanly against master, so we can't just do a `git reset --hard` and cherry-pick the aforementioned commits
* using `git revert abcdef.. -m 1 -n` quickly encounters merge conflicts in #25280 for reason that I do not understand

**Comment by SimonSapin** [comment]
> any pull request for try needs to merge cleanly against master

We could hack something together to run try-like CI without merging to master. Would that help?

**Comment by jdm** [comment]
It would probably help a lot!

**Comment by SimonSapin** [comment]
https://github.com/servo/servo/pull/25351 does that.

**Comment by jdm** [comment]
Observed in e5689df6b44696bf24f8757cd1f6e14d1aabf6f0. Not yet observed in 7474b309b45403a031c7b69c31d99f00d3bfcfb8.

**Comment by SimonSapin** [comment]
Merges in that range:

git log --merges --oneline 7474b30...e5689df
e5689df6b4 Auto merge of #24694 - servo:rustup, r=jdm
18dae9ee8f Auto merge of #24690 - federicomenaquintero:master, r=jdm
87432c71d0 Auto merge of #24697 - servo:cleanup, r=jdm
970f7163e9 Auto merge of #24514 - imiklos:webgl_transform_feedback, r=jdm
8cb6145311 Auto merge of #24689 - servo:FLIP-THE-SWITCH, r=jdm
df9065afb6 Auto merge of #24636 - saschanaz:windowproxy, r=nox,jdm
fc7b880195 Auto merge of #24681 - servo:jdm-patch-36, r=SimonSapin
1089f8f242 Auto merge of #24683 - servo:split, r=jdm
77a5a1834b Auto merge of #24679 - servo:try-windows-ami, r=jdm
9a518cf797 Auto merge of #24677 - jdm:iframe-sizing-cleanup, r=asajeffrey
a33d493a4f Auto merge of #24672 - paulrouget:24400, r=jdm
64560ec0b6 Auto merge of #24646 - paulrouget:nocancel, r=jdm
fb9157df3b Auto merge of #24645 - servo-wpt-sync:wpt_update_04-11-2019, r=jdm

**Comment by jdm** [comment]
I'm betting on #24677 and running more tests to confirm.

**Comment by jdm** [comment]
Observed in 9a518cf7979b79b34611135d09c1dd0a96945255. Still not observed in observed in  747b30, and not yet observed in a33d493a4ff6f8a629a9b82202c49c41ecbefa49 either.

**Comment by jdm** [comment]
Observed in 91dfa354b16535f1c55c722b10cf4538f2385e0e, not observed in 38e4ae0833fbc15c8579d40bca7fc87e9d37cb03 or fd260f78c80a070727ba88d7b5f7cc40eb7efb5a. The window narrows to 7c365b0324b2723d5df2437e59555bfc1835a68f or 2aa5ddf9221b77a6144391eb37855737a9ede083.

**Comment by jdm** [comment]
Observed in a test that included a revert of 91dfa354b16535f1c55c722b10cf4538f2385e0e. Strong suspicion about 7c365b0324b2723d5df2437e59555bfc1835a68f.

**Comment by Manishearth** [comment]
Should we temporarily revert 7c365b0 and see what happens? We can also perhaps do a custom taskcluster run that involves a revert of 7c365b0 and running the WPT suite 10x

**Comment by jdm** [comment]
Yeah, I'll initiate a next step here during my 3.5 hour bus ride today.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/25474 which reverts 7c365b0 still reproduced the problem.

**Comment by jdm** [comment]
A reversion of 2aa5ddf9221b77a6144391eb37855737a9ede083 also demonstrates the problem. I feel like I should step back and verify my reasoning by reverting all of #24677.

**Comment by jdm** [comment]
Welp. Reverting all of #24677 still reproduced the issue.

**Comment by jdm** [comment]
I did 20 runs of the WPT tasks for a33d493a4ff6f8a629a9b82202c49c41ecbefa49, which is the merge commit preceding #24677, and the issue did not reproduce. I have no idea what's going on.

**Comment by Manishearth** [comment]
Perhaps some other commit after it also introduced the issue? We could
search all commits since then and see if reverting that PR fixes things for
them, and if there's a point where that stops working.

**Comment by jdm** [comment]
I feel like I must have got _something_ wrong in my testing methodology. I've now run >30 runs on a selection of commits ranging from this month through early november that all have a reversion of #24677 applied and I haven't reproduced the reftest failure. I'm going to go ahead and revert that PR.

**Comment by jdm** [comment]
I apparently didn't do enough runs, given that we hit the failure attempting to merge #25566.

**Comment by jdm** [comment]
In https://community-tc.services.mozilla.com/tasks/groups/GtFBrd7_Rf29-vIKU-Q-oA I ran almost 650 jobs across 4 revisions spanning early november through late january with #24677 reverted. The failure did not appear one in all of those runs. _I don't understand what's happening_.

**Comment by pshaughn** [comment]
Could one of the machines in the taskcluster have a hardware problem that we're hitting only when we happen to schedule that machine?

**Comment by jdm** [comment]
They're EC2 spot instances as far as I know, so that seems unlikely.

**Comment by SimonSapin** [comment]
Since migrating to community-tc.services.mozilla.com our Linux tasks run on Google Cloud, but that should be very similar to EC2.

**Comment by jdm** [comment]
I ran the WPT CSS tests under rr with the following command:
`./mach test-wpt --debugger=rr --debugger-args=record --timeout-multiplier 4 --processes 6 --log-raw wpt.log`
and removed all non-CSS directories from include.ini. The process took 22 hours to complete, but wpt.log contains at least one instance of a reftest that exhibited this failure \o/

**Comment by jdm** [comment]
I have a theory that this issue occurred before #24677 (which explains why it happens when we revert it) because of async webrender rendering, but #24677 wildly increased how frequently it occurs by reducing the number of steps before compositing occurs (previously there would be some messages about setting the viewport size that no longer occur). I'm going to get a revert merged and see if the frequency of the problem diminishes.

**Comment by jdm** [comment]
This was fixed by #25822.
