### ISSUE TITLE
HoloLens: performance issues after leaving immersive mode

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#24722]
STR:
- run one of the "advanced" bbjs demo
- go to start, press home
- active servo window
- go back to the list of demo
- notice how unresponsive scrolling is
- load a demo, see how slow it is

**Comment by paulrouget** [comment]
The session is never ended.

We should reconsider https://github.com/servo/webxr/pull/78. I think it was the right behavior. But we are not supposed to get STOPPING when opening the start menu. At least it's what I'm getting from the Team conversation.

Testing with the latest runtime, I'm still getting STOPPING when the Start menu shows, which according to MS is not supposed to happen if we handle the changing states correctly.

The only thing I think we do not do correctly is how we handle the READY change state: https://github.com/servo/webxr/blob/27c83fde49d820bc3ffd0396d9aea01a3b5c5729/webxr/openxr/mod.rs#L213

I'll see if properly initializing the session in READY instead of doing right after creating the session changes anything.

**Comment by paulrouget** [comment]
From the Team thread: we schedule openxr frames based on requestAnimationFrame. The Start menu runs at the same frame rate as servo's IM, because it is stamped within the servo app swapchain. If the app runs too slow, Windows stops servo's IM to run the start menu at a proper frame rate.

@Manishearth is suggesting to not wait for requestAnimationFrame to call xrwaitframe.

Also - why should investigate why we run at 30FPS. And probably find a way to show the FPS somewhere.

**Comment by Manishearth** [comment]
This is filed at https://github.com/servo/webxr/issues/96

**Comment by Manishearth** [comment]
> We should reconsider servo/webxr#78. I think it was the right behavior. But we are not supposed to get STOPPING when opening the start menu. At least it's what I'm getting from the Team conversation.

Right, that's a temporary patch, because the runtime was buggy and it becomes really annoying to test when you randomly get STOPPING events.

If we can manage to get STOPPING events at the right time, I'm all for this. Hopefully the start menu triggers other state events so that we can finally trigger visibilitystatechange.

**Comment by paulrouget** [comment]
@Manishearth did we manage to not get that event in the start menu?

Sounds like https://github.com/servo/webxr/pull/97 fixes https://github.com/servo/webxr/issues/96 doesn't it?

**Comment by Manishearth** [comment]
Yeah, it does.

I think we might have gotten the event, but IIRC when we get STOPPING wait_for_animation_frame no  longer runs, and we're supposed to temporarily end the session, which isn't going to fit well with the current architecture since we can't get our wakeup event if the frame loop isn't running.

That patch stops hololens from randomly ending the session completely when this happens. We should improve the situation, but it requires some tricky changes, and I'm not 100% sure if the events are happening correctly yet.

**Comment by jdm** [comment]
Is this still an issue? If so, what do we know about the nature of the problem and potential workarounds/solutions? The current status is not clear to me based on the previous discussion.

**Comment by Manishearth** [comment]
Yes, because currently leaving immersive mode doesn't end the session.

**Comment by Manishearth** [comment]
So I think what we need to do is, when we get STOPPING, we should call xrEndSession, stop waiting for frames, and instead make the loop periodically check for events until it restarts, at which point we re-call xrBeginSession

**Comment by paulrouget** [comment]
Yes, there's no point of not ending the session on STOPPING, so we should do that for sure.

> make the loop periodically check for events until it restarts

Do we still get events after ending the session?

---

If I understand correctly, the session was being stopped because servo was not running fast enough to allow the platform to render the start menu at a correct speed. Now it should not be slow anymore since https://github.com/servo/webxr/pull/97. So we are not supposed to get the STOPPING event. Last time I tried, I think we still get it though. Any idea why?

**Comment by Manishearth** [comment]
I think we're still not super fast, and also we get STOPPING when you hit the home menu as well.

**Comment by jdm** [comment]
This has been fixed and we're now getting events correctly.
