### ISSUE TITLE
mac3 can't find pip

### ISSUE THREAD

**Issue by jdm** [servo/servo#24755]
```
+ export PATH=/Users/worker/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ PATH=/Users/worker/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ export PATH=/Users/worker/tasks/task_1573855606/sccache/sccache-0.2.7-x86_64-apple-darwin:/Users/worker/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ PATH=/Users/worker/tasks/task_1573855606/sccache/sccache-0.2.7-x86_64-apple-darwin:/Users/worker/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ ls
generic-worker
sccache
+ export PATH=/Users/worker/.cargo/bin:/Users/worker/tasks/task_1573855606/sccache/sccache-0.2.7-x86_64-apple-darwin:/Users/worker/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ PATH=/Users/worker/.cargo/bin:/Users/worker/tasks/task_1573855606/sccache/sccache-0.2.7-x86_64-apple-darwin:/Users/worker/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ which rustup
/Users/worker/.cargo/bin/rustup
+ export PATH=/Users/worker/Library/Python/2.7/bin:/Users/worker/.cargo/bin:/Users/worker/tasks/task_1573855606/sccache/sccache-0.2.7-x86_64-apple-darwin:/Users/worker/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ PATH=/Users/worker/Library/Python/2.7/bin:/Users/worker/.cargo/bin:/Users/worker/tasks/task_1573855606/sccache/sccache-0.2.7-x86_64-apple-darwin:/Users/worker/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ python -m ensurepip --user
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
Requirement already satisfied (use --upgrade to upgrade): pip in /Library/Python/2.7/site-packages/pip-19.1.1-py2.7.egg
+ pip install --user virtualenv
/bin/bash: line 10: pip: command not found
```

Observed in https://github.com/servo/servo/pull/24732 (https://community-tc.services.mozilla.com/tasks/U-gcROzjRkOjYuRqL_iV3Q). Probably fallout from the recent homebrew changes?
cc @SimonSapin

**Comment by jdm** [comment]
Other machines have /Users/worker/Library/Python/2.7/bin/pip, but /Users/worker/Library/Python/2.7/bin/ is missing on mac3 (it has a /lib, though).

**Comment by SimonSapin** [comment]
I’ve disabled mac3 (https://github.com/servo/taskcluster-config/pull/5#issuecomment-554617521), reopened the tree, and started looking into this.

Running `sudo -i -u worker` then `python -m pip install --user --upgrade pip` seems to install something. I ran a task with `workerType: macos-disabled-mac3` which got past the pip failure:

https://community-tc.services.mozilla.com/tasks/IbOeuo3oShKjMQxOIfFm2A/runs/0/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FIbOeuo3oShKjMQxOIfFm2A%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L87

I cancelled that task and moved mac3 back to the main poll. I’ll be watching the next task it picks up.

**Comment by SimonSapin** [comment]
Closing as https://community-tc.services.mozilla.com/tasks/C_Uc_NKmRNCU6V3qoeh90Q/runs/0 is green on mac3. Feel free to reopen if needed.
