### ISSUE TITLE
Can't build, no clippy

### ISSUE THREAD

**Issue by saschanaz** [servo/servo#24756]
```
> ./mach build -d --features vslatestinstalled              
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.3.2
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
info: syncing channel updates for 'nightly-2019-11-15-x86_64-pc-windows-msvc'
info: latest update on 2019-11-15, rust version 1.41.0-nightly (82cf3a448 2019-11-14)
error: component 'clippy' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel nightly-2019-11-15
Build FAILED in 0:00:00
```

This happens after #24750. This is why I did 11-05 instead in #24749...

cc @SimonSapin

**Comment by SimonSapin** [comment]
I thought I’d checked https://rust-lang.github.io/rustup-components-history/ yesterday but I must have read it wrong.

But more importantly, why is clippy required? Yes it can be convenient but Servo should still build without it.

**Comment by saschanaz** [comment]
It somehow fails immediately if no clippy... Maybe it should be a warning instead.

**Comment by SimonSapin** [comment]
Does `rustup install nightly-2019-11-15-x86_64-pc-windows-msvc` say the same?

The fact that this is an error rather than a warning is a behavior of rustup (https://github.com/rust-lang/rustup), I don’t know how we can influence it.

**Comment by saschanaz** [comment]
Away from my PC for a few days, will check it when I get back.
________________________________
