### ISSUE TITLE
strange colors with Servo Developer Preview on macOS Catalina

### ISSUE THREAD

**Issue by cadeyrn** [servo/servo#24763]
The package from https://download.servo.org/ has strange colors on macOS Catalina:

<img width="1020" alt="Bildschirmfoto 2019-11-17 um 16 46 08" src="https://user-images.githubusercontent.com/1100614/69009849-e8299500-0959-11ea-8bee-e6a9b98df764.png">

It remind me on https://bugzilla.mozilla.org/show_bug.cgi?id=1558167 - Firefox with WebRender enabled looked very similar before this bug was fixed. Maybe related?

**Comment by jdm** [comment]
Yes, we're on an older version of webrender right now (see https://github.com/servo/servo/pull/24426).

**Comment by cadeyrn** [comment]
#24426 is fixed and I can verify that the color issue is gone with the latest build. Thank you!

**Comment by jdm** [comment]
Thanks for checking!
