### ISSUE TITLE
Intermittent timeouts in reftests

### ISSUE THREAD

**Issue by jdm** [servo/servo#24762]
```
  ▶ TIMEOUT [expected PASS] /FileAPI/url/url_xmlhttprequest_img.html
  │ 
  │ 
  │ 
  └ 
  ▶ TIMEOUT [expected PASS] /css/CSS2/colors/color-002.xht
  │ 
  │ 
  │ 
  └ 
  ▶ TIMEOUT [expected PASS] /css/CSS2/colors/color-004.xht
  │ 
  │ 
  │ 
  └ 
```
I'm really not sure where to start investigating here. It would be useful to know in which file that makes up a reftest the timeout actually occurs.

**Comment by jdm** [comment]
Interestingly, this exact same set of timeouts was observed in #24753 as well.

**Comment by jdm** [comment]
Seen in /css/CSS2/selectors/first-letter-punctuation-077.xht.

**Comment by jdm** [comment]
```
  ▶ TIMEOUT [expected PASS] /css/CSS2/margin-padding-clear/margin-left-008.xht
  │ 
  │ 
  │ 
  └ 
```

**Comment by jdm** [comment]
Observed in linux as well:
```
  ▶ TIMEOUT [expected FAIL] /css/css-paint-api/style-before-pseudo.https.html
  │ 
  │ 
  │ 
  └ 
```

**Comment by Manishearth** [comment]
In #25144:

```
  ▶ TIMEOUT [expected PASS] /css/CSS2/box-display/insert-inline-in-blocks-middle-002.xht
```

and 

```
  â–¶ TIMEOUT [expected PASS] /css/CSS2/linebox/border-padding-bleed-002.xht


  â–¶ TIMEOUT [expected FAIL] /css/CSS2/linebox/anonymous-inline-inherit-001.html


  â–¶ TIMEOUT [expected PASS] /css/CSS2/linebox/fractional-line-height.html


  â–¶ TIMEOUT [expected PASS] /css/CSS2/linebox/border-padding-bleed-001.xht


  â–¶ TIMEOUT [expected PASS] /css/CSS2/csswg-issues/submitted/css2.1/anonymous-boxes-001.xht


  â–¶ TIMEOUT [expected FAIL] /css/CSS2/linebox/baseline-block-with-overflow-001.html


  â–¶ TIMEOUT [expected FAIL] /css/CSS2/linebox/empty-inline-003.xht
```

**Comment by Manishearth** [comment]
Many of these tests don't include any JS at all, so we're just timing out on waiting for the page load (presumably?)

**Comment by Manishearth** [comment]
Also, I haven't checked all of these, but this may be mac-only?

**Comment by Manishearth** [comment]
Ah, no, you have a linux one

**Comment by jdm** [comment]
This got really bad all of a sudden in the past few days. I can't help wondering if #24890 had the opposite effect somehow.

**Comment by jdm** [comment]
> This got really bad all of a sudden in the past few days. I can't help wondering if #24890 had the opposite effect somehow.

In fact, there were piles of stale servo processes on every single mac machine that I have now killed.

**Comment by jdm** [comment]
In continue to see timeouts on mac machines. I'm trying disabling indexing (https://www.technipages.com/macos-sierra-enable-disable-spotlight) and following answer 2 from https://config9.com/linux/macosx/opendirectoryd-consumes-40-of-cpu/, because the mdsworker and opendirectoryd processes are taking up multiple CPUs at full capacity sometimes.

**Comment by CYBAI** [comment]
Observed in linux as well [here](https://community-tc.services.mozilla.com/tasks/AD3RcoPmSu6Xcch20Lh5wg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FAD3RcoPmSu6Xcch20Lh5wg%2Fruns%2F0%2Fartifacts%2Fpublic%2Ffiltered-wpt-errorsummary.log)

```
  ▶ TIMEOUT [expected OK] /referrer-policy/gen/top.meta/unset/xhr/same-http.swap-origin.http.html
  │ 
  │ 
  │ 
  └ 
  ▶ TIMEOUT [expected OK] /_webgl/conformance/attribs/gl-vertex-attrib-zero-issues.html
  │ 
  │ 
  │ 
  └ 
  ▶ TIMEOUT [expected OK] /workers/interfaces/WorkerUtils/navigator/002.html
  │ 
  │ 
  │ 
  └ 
  ▶ TIMEOUT [expected OK] /css/css-flexbox/getcomputedstyle/flexbox_computedstyle_align-self-baseline.html
  │ 
  │ 
  │ 
  └ 
  ▶ TIMEOUT [expected OK] /offscreen-canvas/line-styles/2d.line.join.parallel.worker.html
  │ 
  │ 
  │ 
  └ 
```

**Comment by jdm** [comment]
I don't have evidence that this still happens since we moved to github actions.
