### ISSUE TITLE
PerformanceObserverInit doesn't support absence of entryTypes member

### ISSUE THREAD

**Issue by jdm** [servo/servo#24781]
This might be an issue with the WebIDL from the spec, but the prose says:
```
entryTypes
    A list of entry types to be observed. If present, the list MUST NOT be empty and all other members MUST NOT be present. Types not recognized by the user agent MUST be ignored. 
```
The /performance-timeline/multiple-buffered-flag-observers.any.html which exercises this reports:
```
  │ [2019-11-19T04:29:53Z ERROR script::dom::bindings::error] Error at http://web-platform.test:8000/performance-timeline/multiple-buffered-flag-observers.any.js:11:10 Missing required member "entryTypes".
  │ [2019-11-19T04:29:53Z ERROR script::dom::bindings::error] Error at http://web-platform.test:8000/performance-timeline/multiple-buffered-flag-observers.any.js:11:10 Missing required member "entryTypes".
  │ [2019-11-19T04:29:53Z ERROR script::dom::bindings::error] Error at http://web-platform.test:8000/performance-timeline/multiple-buffered-flag-observers.any.js:11:10 Missing required member "entryTypes".
  └ [2019-11-19T04:29:53Z ERROR script::dom::bindings::error] Error at http://web-platform.test:8000/performance-timeline/multiple-buffered-flag-observers.any.js:25:10 Missing required member "entryTypes".
```

**Comment by jdm** [comment]
Looks like our implementation is older than the current specification text at https://w3c.github.io/performance-timeline/#observe-method. https://github.com/servo/servo/blob/f63b404e0cbf30380c4043700861110d06e548bb/components/script/dom/webidls/MutationObserver.webidl has a very different struct with members for each kind of entry.

**Comment by jdm** [comment]
Our webidl is missing the `types` field, and our [implementation](https://github.com/servo/servo/blob/f63b404e0cbf30380c4043700861110d06e548bb/components/script/dom/performanceobserver.rs#L107) is from an older version of the specification that did not include https://github.com/w3c/performance-timeline/pull/112.

**Comment by jdm** [comment]
Spec: https://w3c.github.io/performance-timeline/

**Comment by pshaughn** [comment]
I don't know much about performance observers but if this is mostly a problem about webidl dictionaries I'll take care of it.

**Comment by pshaughn** [comment]
Fixing this will cause some tests to pass but also cause some tests to crash, since we'll be able to reach the actual payloads of tests like the one I describe in #25589.

**Comment by pshaughn** [comment]
After fixing the double borrow, getting into the body of the performance observer WPT tests still opens up a lot of intermittent behavior. All the expectations in https://github.com/servo/servo/pull/25590#issuecomment-578065820 were what happened during a particular test run on my local machine; the points of timing-out are obviously not consistent. I'll see what I can figure out.

**Comment by pshaughn** [comment]
I think I've found one problem: https://github.com/servo/servo/blob/be409233fdf8d3578e0529ec150a3697788ba4c8/components/script/dom/performance.rs#L287-L302 is true that we want to copy the list so we can iterate it in case of mutation, but it's making a _deep_ copy of the list, so we're actually notifying a copy of the observer and not the original one. This is observable through the callback's second argument, which some tests call .disconnect() on: those tests never disconnect the real performance observer, and so they see a different number of marks than they expect to! I don't know if this is the cause of all the timing problems, but when this behavior is combined with tests that are using short step_timeouts, I could certainly see it getting racy...

**Comment by jdm** [comment]
Ooh, yeah. We should basically just be cloning that list instead of creating new observer objects.

**Comment by pshaughn** [comment]
https://wpt.fyi/results/performance-timeline/multiple-buffered-flag-observers.any.html?label=experimental&label=master&aligned '

I think what's happening on this test is we buffer some marks, then we add a buffered PerformanceObserver expecting it to see those already-buffered marks. However, I can't find anything in the spec that says to actually queue a notification at this time! The only instructions I can see to do so are in https://w3c.github.io/user-timing/#mark-method and https://w3c.github.io/user-timing/#measure-method , one of which has already finished about 100ms ago and the other of which isn't in this test at all. We therefore time out just like Firefox does.

**Comment by pshaughn** [comment]
Or rather, it never has a chance to happen if we're running quickly enough. Under load, we might not have finished all the other tasks within 100ms, so we might end up intermittently hitting the callback.

**Comment by pshaughn** [comment]
Filed https://github.com/w3c/performance-timeline/issues/158 about this, it seems like it could be a simple spec oversight.
