### ISSUE TITLE
Implement MediaSession.setPositionState method

### ISSUE THREAD

**Issue by ferjm** [servo/servo#24808]
https://w3c.github.io/mediasession/#dom-mediasession-setpositionstate

**Comment by jdm** [comment]
Code: `components/script/dom/webidls/MediaSession.webidl`, `components/script/dom/mediasession.rs`

**Comment by shnmorimoto** [comment]
@highfive: assign me

**Comment by ferjm** [comment]
Thanks for working on this issue @shnmorimoto. Feel free to reach out if you have any question.

In a nutshell, what I think we should do to implement this functionality is:

- Implement the DOM binding bits of the [setPositionState](https://w3c.github.io/mediasession/#dom-mediasession-setpositionstate) method. The WebIDL and implementation files to modify are the ones [mentioned above](https://github.com/servo/servo/issues/24808#issuecomment-557105524) by @jdm.
- Extend the existing [MediaSessionEvent](https://github.com/servo/servo/blob/master/components/embedder_traits/lib.rs#L245) with a new `SetPositionState` entry and the corresponding `MediaPositionState` representation.
- Extend the existing [HostTrait](https://github.com/servo/servo/blob/master/ports/libsimpleservo/api/src/lib.rs#L87) trait with a new `on_media_session_set_position_state` or such method. And implement that method for the [C](https://github.com/servo/servo/blob/master/ports/libsimpleservo/capi/src/lib.rs#L633) and [JNI](https://github.com/servo/servo/blob/master/ports/libsimpleservo/jniapi/src/lib.rs#L380) APIs
- For the Android part, extend the existing [Callbacks](https://github.com/servo/servo/blob/master/support/android/apk/servoview/src/main/java/org/mozilla/servoview/JNIServo.java#L92) and [Client](https://github.com/servo/servo/blob/master/support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java#L175) interfaces with the new `onMediaSessionSetPositionState` callback. And implement it [here](https://github.com/servo/servo/blob/master/support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java#L211) and [here](https://github.com/servo/servo/blob/master/support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java#L32).
- Bonus points if you want to tweak the [existing UI](https://github.com/servo/servo/blob/master/support/android/apk/servoapp/src/main/java/org/mozilla/servo/MediaSession.java) by adding a progress bar, and the info about the current position and total duration.

**Comment by shnmorimoto** [comment]
@ferjm Thanks for the details. I'll give it a try.

**Comment by shnmorimoto** [comment]
@ferjm 

> If the duration is not present or its value is null, throw a TypeError.

About the above specifications, I am trying to throw an error as follows.

```
throw_dom_exception(context, global, Error::Type("duration is not preset or its value is null".to_string()));
```

How can I get SafeJSContext and &GlobalScope from MediaSession?
Or, Is there any way to know the details of filed and method generated by #[dom_struct] macro?

**Comment by jdm** [comment]
Any user of dom_struct implements the DomObject trait, which has a `global()` method that returns a `DomRoot<GlobalScope>`. From a global scope, you can call the `cx()` method to get a SafeJScontext.

**Comment by ferjm** [comment]
> About the above specifications, I am trying to throw an error as follows.
throw_dom_exception(context, global, Error::Type("duration is not preset or its value is null".to_string()));

I think you don't need to use `throw_dom_exception` directly. IIUC, you are trying to implement the second step of https://w3c.github.io/mediasession/#dom-mediasession-setpositionstate If that's the case, note that the implementation of `setPositionState` should return a `Fallible<()>` (this return type is added by the DOM bindings system by adding the `[Throws]` keyword to the function definition on the WebIDL file). With that return type, you can throw the exception by returning `Err(Error::Type("duration is not preset or its value is null").to_owned())`

**Comment by shnmorimoto** [comment]
@jdm
Thanks! 

@ferjm 

> note that the implementation of setPositionState should return a Fallible <()>

I understand. I'm going to implement it that way.
Thanks!
