### ISSUE TITLE
Windows dev build + unit tests on taskcluster intermittently exceeds max run time

### ISSUE THREAD

**Issue by jdm** [servo/servo#24823]
https://community-tc.services.mozilla.com/tasks/a4yv0EwoTa2AHfneAszjvw is a task that exceeded the 1.5 hour limit in the middle of the libsimpleservo build.

**Comment by SimonSapin** [comment]
`./mach fetch` alone took 37 minutes: https://community-tc.services.mozilla.com/tasks/a4yv0EwoTa2AHfneAszjvw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2Fa4yv0EwoTa2AHfneAszjvw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L712

**Comment by SimonSapin** [comment]
Is SpiderMonkey being recompiled when running `./mach test-unit` immediately after `./mach build`? (Though fixing that would only save ~5 minutes.)

https://community-tc.services.mozilla.com/tasks/a4yv0EwoTa2AHfneAszjvw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2Fa4yv0EwoTa2AHfneAszjvw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L1746

**Comment by jdm** [comment]
Huh. I wonder if there's still some cargo dirty bits triggering that?

**Comment by SimonSapin** [comment]
> `./mach fetch` alone took 37 minutes

In another run today it finished under 4 minutes, so I’m afraid it’ll turn out to be ~random network slowness outside of our control

https://community-tc.services.mozilla.com/tasks/LwAe4Wu9RiKvJudVCs3dYw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FLwAe4Wu9RiKvJudVCs3dYw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L750
