### ISSUE TITLE
GStreamer plugin should allow GPU video encoding

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#24831]
At the moment we use readback to get each frame out of GPU memory and into main memory. We shouldn't.

**Comment by asajeffrey** [comment]
@sdroege I'm trying to work out how to get the plugin to generate frames in GLMemory. I wrote a simple version https://github.com/asajeffrey/my-gst-plugin/blob/2c346d729ce599a85e44209af1b5e8c6f12510c5/src/myglsrc.rs which casts the output buffer to `GstGLMemory` and draws on the texture. Unfortunately, running it just produces a black window, no video output :( My command line on macos was:
```
GST_PLUGIN_PATH=target/debug gst-launch-1.0 myglsrc ! video/x-raw\(memory:GLMemory\),framerate=25/1,width=1024,height=512 ! queue ! autovideosink
```
Any idea what I'm doing wrong? Can you point me to an example GStreamer source that produces GLMemory?

**Comment by asajeffrey** [comment]
PS: the real thing, which also doesn't work, is at https://github.com/asajeffrey/servo/blob/785e243f1a82818a0cad5ccc97afe1c445540a8f/ports/gstplugin/servosrc.rs

**Comment by jdm** [comment]
https://github.com/asajeffrey/my-gst-plugin/blob/2c346d729ce599a85e44209af1b5e8c6f12510c5/src/myglsrc.rs#L178 is using an alpha of 0, right?

**Comment by jdm** [comment]
Changing 0.0 to 1.0 yields a non-black screen, but it looks like random texture memory.

**Comment by asajeffrey** [comment]
Aaargh, this used to be just RGBx, not RGBA. Random video memory is still not good!

**Comment by asajeffrey** [comment]
Trying it on linux:
```
gst-launch-1.0 myglsrc ! video/x-raw\(memory:GLMemory\),width=50,height=99 ! gldownload ! ximagesink
```
produces
```
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'gldownloadelement0': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayX11\)\ gldisplayx11-0";
Setting pipeline to PLAYING ...
ERROR: from element /GstPipeline:pipeline0/MyGLSrc:myglsrc0: Internal data stream error.
Additional debug info:
../subprojects/gstreamer/libs/gst/base/gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:pipeline0/MyGLSrc:myglsrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.000034192
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by asajeffrey** [comment]
To be completely accurate, the command line set a slew of env vars, it was actually:
```
GST_GL_XINITTHREADS=1 \
GST_PLUGIN_PATH=$PWD/target:$PWD/../servo/support/linux/gstreamer/gst/lib \
GST_PLUGIN_SCANNER=$PWD/../servo/support/linux/gstreamer/gst/libexec/gstreamer-1.0/gst-plugin-scanner \
LD_LIBRARY_PATH=$PWD/../servo/support/linux/gstreamer/gst/lib \
  ../servo/support/linux/gstreamer/gst/bin/gst-launch-1.0 \
    myglsrc ! video/x-raw\(memory:GLMemory\),width=50,height=99 ! gldownload ! ximagesink
```

**Comment by asajeffrey** [comment]
Ah, the problem is the `queue` transform, if we remove that (and set the alpha to be 1.0) then `myglsrc` works! Let's see if that applies to servo too...

**Comment by asajeffrey** [comment]
OK, I got it to the point where I can generate GLMemory and feed it into glimagesink, yay! Not so yay is the flickering, which I think is caused by black frames when servo can't keep up with the window's framerate. Adding a `videorate` element just resulted in a black window.

**Comment by asajeffrey** [comment]
The WIP is https://github.com/asajeffrey/servo/blob/gstplugin-glmemory/ports/gstplugin/servosrc.rs

**Comment by asajeffrey** [comment]
Fixed the flickering. Submitted a PR.

**Comment by asajeffrey** [comment]
It's not perfect, in particular the plugin expects to be fed GLMemory, and sometimes fails due to pipelines which provide non-GL memory for some reason.

**Comment by asajeffrey** [comment]
Also there's a memory leak, sigh.

**Comment by asajeffrey** [comment]
Ah, the memory leak is probably caused by using `into_ptr()` to get at the `*mut GstGLMemory`, but this then doesn't run any drop code. I should be using `as_ptr()` instead.
