### ISSUE TITLE
Remove all uses of `transmute_mut`

### ISSUE THREAD

**Issue by zwarich** [servo/servo#2486]
Now that `transmute_mut` is deprecated (and undefined behavior), we should remove all uses from Servo. This will mean a very liberal sprinkling of `Unsafe` in some places.

**Comment by frewsxcv** [comment]
```
~/D/r/servo (master|✔) $ ./mach grep transmute_mut | wc
       0       0       0
```

and

https://github.com/servo/servo/search?utf8=%E2%9C%93&q=transmute_mut&type=Code

would suggest that this Issue has been completed.
