### ISSUE TITLE
Constellation shouldn't have to depend on canvas crate

### ISSUE THREAD

**Issue by jdm** [servo/servo#24891]
After #24875, constellation depends on canvas in order to start the canvas paint thread, and to send constellation-specific messages to the thread. If the message moves into canvas_traits and we start the thread in the code that creates the constellation in components/servo, we should be able to remove the dependency.

**Comment by kunalmohan** [comment]
I'd like to give this a try. Anything particular that I should keep in mind?

**Comment by jdm** [comment]
Not that I can think of!

**Comment by kunalmohan** [comment]
Are there any tests for these changes? or is a successful build sufficient?

**Comment by kunalmohan** [comment]
> After #24875, constellation depends on canvas in order to start the canvas paint thread, and to send constellation-specific messages to the thread. If the message moves into canvas_traits and we start the thread in the code that creates the constellation in components/servo, we should be able to remove the dependency.

After these changes, constellation still has to depend on canvas for the conditional compilation options:
https://github.com/servo/servo/blob/5f55cd5d71df9c555fbc24777168396ddd539f28/components/constellation/Cargo.toml#L13-L15
