### ISSUE TITLE
Move font handling to its own crate

### ISSUE THREAD

**Issue by brson** [servo/servo#249]
Fonts are currently dealt with in servo_gfx, but that shouldn't be necessary. To draw servo_gfx only needs a native font handle - it doesn't need to be exposed to the complexity of font libraries and text shaping.

**Comment by Yoric** [comment]
@brson, are you still working on this? Is this bug still valid?

**Comment by brson** [comment]
I'm not working on it, and whatever I was thinking at the time is certainly superseded by whatever others' are thinking now.
