### ISSUE TITLE
referrer-policy: origin-when-cross-origin in Fetch isn't working according to WPT

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24907]
fetch/api/basic/referrer fails every "origin-when-cross-origin" subtest. There's code that is supposed to be handling this referrer policy, but what it does in net/http_loader.rs doesn't match what it's supposed to do.

**Comment by jdm** [comment]
This is labelled step 5.10 in http_network_or_cache_fetch, but should be extracted into a separate routine like https://fetch.spec.whatwg.org/#append-a-request-origin-header instead, and take into account the request's referrer policy.

**Comment by jdm** [comment]
Also we should be checking the request's response tainting, rather than only the cors flag from the algorithm.

**Comment by pshaughn** [comment]
Changes to that step that I thought would do something had no apparent effect... There's a chance this is another case of Hyper doing its own header cleaning, but it's more likely I just understood what I had to change and will need to take more whacks at it.

**Comment by pshaughn** [comment]
On further inspection of standards and tests, there is something out of sync. https://w3c.github.io/webappsec-referrer-policy/#referrer-policy lists the strings "strict-origin-when-cross-origin" and "origin-when-cross-origin" as two distinct policies, and Servo does likewise. The current version of https://fetch.spec.whatwg.org literally never uses the string "origin-when-cross-origin" except with "strict-" before it, meaning whatever these tests want to do about that string is entirely unspecified!

**Comment by shanehandley** [comment]
I believe this issue is now resolved 👍 the relevant [WPT's for referrer](https://wpt.fyi/results/fetch/api/basic?label=master&product=servo) pass and associated code mentioned in https://github.com/servo/servo/issues/24907#issuecomment-566125333 was [recently brought into line](https://github.com/servo/servo/pull/33531) with the spec 👍

**Comment by jdm** [comment]
Thanks for checking!
