### ISSUE TITLE
CRASH in WPT xhr/sync-no-timeout

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24919]
This test calls a function that opens an XHR request that will be very slow to respond, then returns. The test output has the line "stack backtrace:" but doesn't go on to actually show me the backtrace, so I can't say as much as I'd like to. I imagine it could be that the XHR request is getting garbage collected early. The crash occurs whether running headlessly or with a window; I'm in Linux Mint (19.2 on a Virtualbox VM) if that could matter.

**Comment by jdm** [comment]
Running the test with `--debugger` will allow you to get a backtrace in gdb at the time of the crash.

**Comment by pshaughn** [comment]
The fact that this was a crash for me and not a fail was almost definitely #24984
