### ISSUE TITLE
Fetching about:blank works when it shouldn't

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24910]
WPT test fetch/api/basic/scheme-about tries to fetch about:blank various ways and succeeds. The test expects network errors in these cases, and other browsers pass.

**Comment by pshaughn** [comment]
xhr/send-non-same-origin.htm also succeeds at this when it's not expected to, using an XMLHttpRequest instead of a fetch.

**Comment by MDeiml** [comment]
Seems like this was solved by #25687.

**Comment by jdm** [comment]
Indeed!
