### ISSUE TITLE
window[0] is throwing an SyntaxError

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24943]
WPT xhr/open-url-multi-window-* and xhr/open-url-about-blank-window try to find an iframe as self[0], where self is window, and throw "The string did not match the expected pattern." which is defined in script/dom/domexception.rs as the SyntaxError message.

**Comment by jdm** [comment]
This is caused by the missing [indexed getter](https://heycam.github.io/webidl/#idl-indexed-properties): https://github.com/servo/servo/blob/69c7595a573db81798616ca5326457d8560a5377/components/script/dom/webidls/Window.webidl#L45

**Comment by jdm** [comment]
That being said, the spec doesn't include an indexed getter on the Window interface, and instead includes the GetOwnProperty spec text for WindowProxy: https://html.spec.whatwg.org/multipage/window-object.html#windowproxy-getownproperty

**Comment by pshaughn** [comment]
I am mistaken here; the window[0] part is getting /something/ back, and then something else goes wrong later in the same line.
