### ISSUE TITLE
Non-http iframes get a SyntaxError trying to use XHR

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24944]
WPT xhr/open-url-javascript-window-2 and xhr/open-url-about-blank-window respectively make a javascript: iframe where the src script uses XHR, and an about:blank iframe that has new .XMLHttpRequest called on its proxy. In both cases, the test output complains of a line-numberless exception matching the SyntaxError string defined in script/dom/domexceptions.rs.

**Comment by pshaughn** [comment]
#24943 was due to my misinterpretation of this error, conflating it with some other iframe errors that aren't this.

**Comment by jdm** [comment]
My money is on https://github.com/servo/servo/blob/69c7595a573db81798616ca5326457d8560a5377/components/script/dom/xmlhttprequest.rs#L386-L393, which would suggest that the globals for the new iframes are not reporting an appropriate base URL.

**Comment by pshaughn** [comment]
https://html.spec.whatwg.org/#fallback-base-url vs https://github.com/servo/servo/blob/85ad53c42b918ca836e1e97deb8582ae987b30e5/components/script/dom/document.rs#L582-L588 is certainly telling that story for at least the about:blank case!

**Comment by pshaughn** [comment]
https://html.spec.whatwg.org/#creating-browsing-contexts informs us, sort of in passing: "A browsing context has an associated creator origin (null or returns an origin), creator URL (null or returns a URL), and creator base URL (null or returns a URL). These are all initially null." This information should have been up higher in https://html.spec.whatwg.org/#browsing-context probably. 

The other things a browsing context has, like a disowned boolean, live in WindowProxy, so these should too. Populating and using them might solve both this and #25374. Most of the places that use them are obvious, but because Servo doesn't have a really discrete "create a browsing context" step the question of where to populate them might get non-obvious.

**Comment by pshaughn** [comment]
`Servo doesn't have a really discrete "create a browsing context" step` is of course another data point in the case for a big iframe navigation.
