### ISSUE TITLE
XHR .upload.onloadstart and .upload.onprogress can receive events when added to an already-in-progress XHR

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24950]
WPT xhr/event-upload-progress tries a few orders of attaching upload listeners and calling send(), and the listeners get events even if they are being added after send() is already called. 

It looks like step 5 of https://xhr.spec.whatwg.org/#the-send()-method is supposed to lock in whether there are upload listeners via the "upload listener flag", instead of every data chunk making a new check for targets; xmlhttprequest.rs doesn't have this step.

**Comment by pshaughn** [comment]
cors/late-upload-events.htm shows this happens regardless of whether the request needs preflight.

**Comment by ghostd** [comment]
Should be fixed with #27658
