### ISSUE TITLE
XHR POST to an URL that redirects is behaving badly

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24951]
WPT xhr/send-redirect-post-upload tries posts that get 301, 302, 303, and 307 redirects. It looks like Servo sends Content-Type to the 301, 302, and 303 destinations when it shouldn't, and that it's sending a Content-Length of 0 to the 307 destination when it should be resending the original Content-Length. These could be two different bugs in different places.

**Comment by pshaughn** [comment]
https://github.com/servo/servo/pull/25357 looks like it'll fix the 301/302/303 cases

**Comment by shanehandley** [comment]
I believe this one was fixed with merge of the [PR](https://github.com/servo/servo/pull/25357) mentioned above. 

WPT: https://wpt.fyi/results/xhr/send-redirect-post-upload.htm?product=servo
