### ISSUE TITLE
Implement attachInternals and ElementInternals

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24988]
WPT custom-elements/HTMLElement-attachInternals, custom-elements/ElementInternals-NotSupportedError, custom-elements/form-associated/form-disabled-callback, and all of custom-elements-form-associated/ElementInternals* expect attachInternals to exist, and to return an ElementInternals where appropriate

**Comment by pshaughn** [comment]
I'm going to draft some code toward this, although current WPT status (https://wpt.fyi/results/custom-elements/form-associated?run_id=433960003&run_id=401740001&run_id=439870002&run_id=426710002) suggests Servo shouldn't necessarily go too far out of its way to support form-associated CEs yet.

**Comment by pshaughn** [comment]
Question: does Servo currently have any sense of remembering what was in a form for when you navigate away from a page and come back to it? If so, where's that implemented? It needs to fire a custom element reaction in some cases if it exists at all, and I'm not sure whether it does.

**Comment by pshaughn** [comment]
Now making enough progress that I'm hitting spec/test holes; https://github.com/whatwg/html/issues/5263

**Comment by jdm** [comment]
We only retain form information that is reflected in the current DOM in a page in the bfcache (ie. it hasn't been evicted, so we can activate the pipeline). If the page gets reloaded then all form information is lost.

**Comment by pshaughn** [comment]
In that case one of the callbacks can be defined but has no code ever firing it; the spec only says we have to fire it _if_ we repopulate form data on a return to a page.
