### ISSUE TITLE
Implement CustomElementRegistry.upgrade

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24989]
WPT test custom-element-registry/upgrade fails on this

**Comment by jdm** [comment]
https://html.spec.whatwg.org/multipage/custom-elements.html#customelementregistry
https://html.spec.whatwg.org/multipage/custom-elements.html#dom-customelementregistry-upgrade

**Comment by pshaughn** [comment]
The underlying operation already exists; this might only need that code to get plugged into an IDL method.

**Comment by pshaughn** [comment]
Just plugging it in passes all the custom-elements/custom-element-registry/upgrade.html tests, but there's one related failure:
https://github.com/servo/servo/blob/90acd1adc3aa0300e5dea94855c595a19e718c6c/tests/wpt/web-platform-tests/custom-elements/upgrading.html#L209-L226

This seems like the reason https://html.spec.whatwg.org/multipage/custom-elements.html#upgrades specifies the element should be set to the definition before actually calling the constructor about it; I'll look into the Servo order of operations.

**Comment by pshaughn** [comment]
I think there's a spec bug! Step 3 of https://html.spec.whatwg.org/multipage/custom-elements.html#concept-upgrade-an-element sets the definition, but "is custom" links to the _custom element state_, not the _custom element definition_, and we don't set the state until step 10! At the time the constructor is called, the element has a custom element definition but isn't the adjective "custom" yet, and the infinite recursion follows from there.
