### ISSUE TITLE
Implement HTMLSlotElement

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#24991]
This is part of shadow DOM, but it's absent from the code entirely instead of behind dom.shadowdom.enabled. WPT reactions/HTMLSlotElement expects it.

**Comment by pshaughn** [comment]
This was just a more javascript-constructor-facing way of writing issue #23590

**Comment by jdm** [comment]
No need to duplicate it, in that case. It's hard to imagine a world in which we implement slots but don't expose them to JS.
