### ISSUE TITLE
Timing of custom element microtasks isn't the way WPT expects it to be

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25016]
WPT custom-elements/microtasks-and-constructors.html and perform-microtask-checkpoint-before-construction.html test many specific expectations about when the microtasks of custom elements happen, and Servo violates many of those expectations.

The microtasks-and-constructors test is a little hard to read, since it's broken up into separate script elements to make interesting event orders happen while the document is still being parsed. My reading of it is that multiple script bodies seem to be firing in a row, where the callbacks of custom elements between those scripts are expected be firing in between them. I'm not sure I understand it, though.

**Comment by jdm** [comment]
Marking this as high-value since tests that expose issues in Servo's timing/ordering of microtasks could plausibly have broader web compatibility impact.

**Comment by pshaughn** [comment]
We're missing a microtask checkpoint that should be coming from inside the parser: when a custom element constructor enqueues a microtask, that microtask should fire BEFORE the start of the element `<script>`  but instead in Servo the microtask hangs around in the queue until the checkpoint at the end of the next `<script>` block. The simplest case for this is named "Microtasks evaluate immediately when the stack is empty inside the parser.", which gives some clue where to look.

**Comment by jdm** [comment]
One question I have - given:
* https://github.com/servo/servo/blob/0131952d6d97bf904da353cec9a8fdb32307ef01/components/script/dom/htmlscriptelement.rs#L792
* https://github.com/servo/servo/blob/0131952d6d97bf904da353cec9a8fdb32307ef01/components/script/dom/globalscope.rs#L1712
* https://github.com/servo/servo/blob/0131952d6d97bf904da353cec9a8fdb32307ef01/components/script/dom/bindings/settings_stack.rs#L78-L80

Why doesn't the microtask checkpoint occur?

**Comment by pshaughn** [comment]
That one does! The microtask that was supposed to fire earlier and didn't does fire at that point.

https://github.com/servo/servo/blob/0131952d6d97bf904da353cec9a8fdb32307ef01/tests/wpt/web-platform-tests/custom-elements/microtasks-and-constructors.html#L37-L61

We get checkpoints at 43 and 60; we're also supposed to be getting a checkpoint at 45.

**Comment by pshaughn** [comment]
https://html.spec.whatwg.org/multipage/parsing.html#create-an-element-for-the-token says to perform a checkpoint, but it looks like it's saying to do it before the custom element constructor call rather than after, so it doesn't seem to be the one this test wants.

**Comment by jdm** [comment]
It probably comes from https://heycam.github.io/webidl/#invoke-a-callback-function which comes from https://html.spec.whatwg.org/multipage/custom-elements.html#invoke-custom-element-reactions which comes from step 9 in that algorithm.

**Comment by jdm** [comment]
Either that or https://heycam.github.io/webidl/#construct-a-callback-function from the Upgrade path.

**Comment by pshaughn** [comment]
I am think it's case "An end tag whose name is `<script>`" in https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-incdata actually. It looks like the INSTANT the HTML parser sees a `</script>`, before actually javascript-parsing the script itself, we are supposed to get a checkpoint.

**Comment by jdm** [comment]
Hmm, good point!

**Comment by pshaughn** [comment]
Adding a checkpoint at line 560 here: https://github.com/servo/servo/blob/904fcb4317ffd0f1ed6d0400cdb768fedacfda3d/components/script/dom/servoparser/mod.rs#L556-L561
passes some of the tests, but not all.

**Comment by pshaughn** [comment]
https://github.com/servo/servo/blob/904fcb4317ffd0f1ed6d0400cdb768fedacfda3d/tests/wpt/web-platform-tests/custom-elements/microtasks-and-constructors.html#L54-L70 I don't yet understand why this constructor is supposed to fail and leave us with an HTMLUnknownElement, but Firefox and Chrome agree that it does.

**Comment by pshaughn** [comment]
I think I've found it; it zig-zags across three specs. https://dom.spec.whatwg.org/#concept-create-element says "the result of constructing C", with a link to the WebIDL spec. https://heycam.github.io/webidl/#construct-a-callback-function includes "Clean up after running script" before returning, with a link to the HTML spec. https://html.spec.whatwg.org/multipage/webappapis.html#clean-up-after-running-script says we run a checkpoint here.

That checkpoint would thus call setAttribute while we are still on step 6.1.2 of "create an element", meaning that when we get to step 6.1.5 we have an attribute and need to throw.

**Comment by jdm** [comment]
Implementation detail that may help - the codegen for webidl callbacks is based on https://github.com/servo/servo/blob/904fcb4317ffd0f1ed6d0400cdb768fedacfda3d/components/script/dom/bindings/callback.rs#L220-L283, which is based around the same AutoEntryScript that performs a microtask checkpoint in its drop implementation.

**Comment by pshaughn** [comment]
The "result of constructing C" phrase only appears twice and both times are about custom element definitions, so I don't think this will require a codegen change.

**Comment by pshaughn** [comment]
These actually aren't going through an AutoEntryScript; they're creating a js::jsapi::JSAutoRealm then calling directly into js::rust::wrappers::Construct1. The only other piece of code doing this is PaintWorkletGlobalScope::invoke_a_paint_callback.

In the paint worklet's case, the spec says "the result of Construct(paintCtor)" and is linking to ECMAScript, not WebIDL, for the definition of "Construct", so the paint worklet doesn't need to perform a microtask checkpoint on the way out of constructing and is of no concern here.

**Comment by jdm** [comment]
Ooh, that's good to know. We should probably add an AutoEntryScript, in that case.

**Comment by pshaughn** [comment]
I don't know whether AutoEntryScript applies here. Adding a checkpoint after exiting the Construct1 call's realm, combined with the checkpoint in the tokenizer, passes every test in microtasks_and_constructors.html.

None of this has resolved the failures in perform-a-microtask-before-construction.html. The most obvious difference I can see between the tests is that where microtasks-and-checkpoints.html does everything in the content document of a normally fetched top-level window, perform-a-microtask-before-construction.html sets the srcdoc of an iframe. My first thought is that this one might involve Servo checking the wrong global's custom element registry.

**Comment by jdm** [comment]
Totally believable!

**Comment by pshaughn** [comment]
The element is upgraded to custom, so it's the right registry, but the microtask checkpoint on upgrading doesn't fire, and this is almost definitely another timing problem in HTMLIFrameElement::navigate_or_reload_child_browsing_context (#24901, #25908), since that's what assigning to srcdoc actually calls and we already know it's getting things wrong. I will dig a little more to confirm that's what's happening, then if it is I'll do a PR for just the microtasks-and-constructors.html part.

**Comment by pshaughn** [comment]
Opened #25514 for that so I can close this.
