### ISSUE TITLE
Use a package dependency instead of querying for OpenXR

### ISSUE THREAD

**Issue by jdm** [servo/servo#25012]
This will let us remove the restricted capability. cc @paulrouget 
```
Instead of using packageQuery, you can add a PackageDependency to the AppxManifest and the Store will ensure the OpenXR framework is installed:
    <PackageDependency Name="Microsoft.WindowsMixedReality.Runtime" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" MinVersion="0.0.1.0" />

    We use this mechanism to get the framework installed on desktop for Mixed Reality
```

**Comment by paulrouget** [comment]
I've tried that.

But from my testing, it doesn't work when the app is sideloaded (from Visual Studio or from the Device Portal). My guess is that it only installs the dependency when installed from the store?

Let me see what if that's true.

**Comment by paulrouget** [comment]
Updating the appxmanifest and cleaning the solution is not enough. The GeneratedFiles directory needs to be deleted too.

This, at least, make it so the dependency is properly declared in the final package.

I haven't tested yet.

**Comment by paulrouget** [comment]
@jdm can you try this on the emulator? For some reason I can't get my emulator to work anymore.

Before building, it's important to do a mach clean, or just deleted all the generated files under `support/hololens/`.

The warning prompt will likely still show up, it's normal. Do not install anything and try to run a demo.

```
diff --git a/support/hololens/ServoApp/Package.appxmanifest b/support/hololens/ServoApp/Package.appxmanifest
index c366444f8f..26c876f473 100644
--- a/support/hololens/ServoApp/Package.appxmanifest
+++ b/support/hololens/ServoApp/Package.appxmanifest
@@ -15,6 +15,7 @@
   </Properties>
   <Dependencies>
     <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.0.0" MaxVersionTested="10.0.0.0" />
+    <PackageDependency Name="Microsoft.WindowsMixedReality.Runtime" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" MinVersion="0.0.1.0" />
   </Dependencies>
   <Resources>
     <Resource Language="x-generate" />
```

**Comment by jdm** [comment]
I deleted all of support/hololens, did a `git reset --hard`, then built and ran in the emulator. When I loaded one of the demos from the homepage and pressed the Enter XR button, I got:
```
analog\input\xrruntime\dll\runtimelocator.cpp(94)\MixedRealityRuntime.dll!00007FFF3E0965DD: (caller: 00007FFF3E098760) Exception(1) tid(11e0) 80070002 The system cannot find the file specified.
    Msg:[Failed to locate runtime library] CallContext:[\LoaderNegotiate] 
Exception thrown at 0x00007FFF53EEA839 in ServoApp.exe: Microsoft C++ exception: wil::ResultException at memory location 0x0000004476DF74B0.
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : RuntimeInterface::LoadRuntime skipping manifest file C:\Windows\System32\MixedRealityRuntime.json, negotiation failed with error -6
'ServoApp.exe' (Win32): Unloaded 'C:\Windows\system32\MixedRealityRuntime.dll'
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to find a valid runtime
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : Failed loading runtime information
'ServoApp.exe' (Win32): Unloaded 'P:\WindowsApps\Microsoft.VCLibs.140.00.Debug_14.0.27323.0_x64__8wekyb3d8bbwe\vcruntime140_1_app.dll'
'ServoApp.exe' (Win32): Unloaded 'U:\USERS\DefaultAccount\AppData\Local\DevelopmentFiles\1d265729-8836-4bd3-9992-4cb111d1068bVS.Debug_x64.image\openxr_loader.dll'
RUST: WARN - webxr_api::registry - XR device error BackendSpecific("ERROR_INSTANCE_LOST")
```

**Comment by jdm** [comment]
According to our contacts, the PackageDependency doesn't trigger when installing to the emulator via Visual Studio.

**Comment by jdm** [comment]
That being said, the latest emulator image installed from https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator (10.0.18362.1034) contains an appropriate openxr runtime (although the existing warning message still appears) that allows me to enter immersive mode. I think the PackageDependency will be good for people sideloading or installing from the store, and anybody developing locally and deploying with visual studio should just be sure to update to the most recent emulator issue.
