### ISSUE TITLE
.matches(':defined') on an undefined custom element throws SyntaxError

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25010]
WPT custom-elements/Document-createElement.html sees this, in `assert_false(instance2.matches(':defined'))`

**Comment by jdm** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:defined

**Comment by jdm** [comment]
We'll need to extend https://github.com/servo/servo/blob/1dd6ad7063a5bf71a37894654a7561338c6a39bc/components/style/servo/selector_parser.rs#L273 with a new Defined variant, and that should expose various other places in the code that need to be updated to support it.

**Comment by pshaughn** [comment]
Is trying to match a bad pseudo-class name even supposed to be a SyntaxError in the first place?

**Comment by jdm** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Element/matches, yes.

**Comment by pshaughn** [comment]
So it is! I'd have thought a syntactically well-formed argument that just didn't happen to be the name of a pseudo-class would get a different exception, but the standard says SyntaxError for any failure.
