### ISSUE TITLE
Devtools story on HoloLens

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#25028]
People working on BabylonJS demos have a difficult time because there is no devtools available.

2 options:
- we can enable the remote devtools. 3 issues:
  -  Recommending Firefox Nightly might not be the best thing to do (for example, now, it's broken: https://github.com/servo/servo/issues/24092). Maybe we can recommend Firefox ESR.
  - I'm not sure if we should always start the app with the devtools port open, or find a way to start the devtools after startup.
  - as of now, I haven't managed to connect to the emulator from Firefox. See https://github.com/servo/servo/issues/24139
- redirect `console.log` to the HL Device Portal logs via [ETW logging](https://docs.microsoft.com/en-us/windows/win32/etw/about-event-tracing)

**Comment by paulrouget** [comment]
We either need to be able to start [the devtools after startup](https://github.com/servo/servo/issues/25119) or we could also start the devtools if the HoloLens is in developer mode and add a prompt on connection.

**Comment by paulrouget** [comment]
If there's a prompt before the connection is initiated (#25266), could we consider always listening for incoming connection?

**Comment by paulrouget** [comment]
We should check for any possible overhead when the devtools are running.

**Comment by jdm** [comment]
We've enabled devtools by default.
