### ISSUE TITLE
Setting a [PutForwards] attribute when the getter has been overridden doesn't seem to call the new getter 

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25038]
These are cases "Exception propagation from getter of [PutForwards] attribute" and "TypeError when getter of [PutForwards] attribute returns non-object" in WebIDL/ecmascript-binding/put-forwards.html.

In these, Element.style is overridden with a custom getter while keeping its setter the same, and then an element's style gets with a string. Because style is [PutForwards], this needs to put the set value forwards into .cssText, and WPT expects that process to call the getter; instead the getter is not being called.

Step 4.5.8 of the attribute setter in https://heycam.github.io/webidl/#es-attributes says to use Get here. I would guess Servo is instead looking under the hood directly at the original idl-defined Element.style slot in the Rust code, regardless of getter overrides.

**Comment by pshaughn** [comment]
Note distinction between overriding something on the "[PutForwards] attribute" (style here) and the "[PutForwards target attribute" (cssText here); this is not the same error as #25037 although the code fixes for the two might be adjacent.

**Comment by jdm** [comment]
Curiously, the generated code _look_ like it it does a get operation:
https://github.com/servo/servo/blob/54d88fd042d3d1d382b36bf5d53308dabc35991d/components/script/dom/bindings/codegen/CodegenRust.py#L3854-L3878

I wonder if this is particular to the style attribute, or if it's a more general problem with other PutForwards attributes.

**Comment by pshaughn** [comment]
The test isn't directly checking for the performance of the get operation itself; what would happen if the generated code's getter threw an exception or returned null? I was reading the lack of an exception in the test as an indication that the getter wasn't happening.

**Comment by pshaughn** [comment]
to do here: write a simpler test that proxies the getter with a counter to see if it's being called with bad output ignored vs. not called at all

**Comment by pshaughn** [comment]
PutForwards is actually commented out entirely in the relevant IDL and I hadn't noticed.
