### ISSUE TITLE
"Legacy platform object" getOwnPropertyDescriptor returns undefined when it should be finding dynamic properties

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25036]
WebIDL/ecmascript-binding/legacy-platform-object.html tests out various things "legacy platform objects" (https://heycam.github.io/webidl/#es-legacy-platform-objects) are expected to do, most of which involving pretending to be arrays or open-ended hashmaps in one way or another. Mutliple tests fail on getOwnPropertyDescriptor, which is not seeing the dynamic properties.

HTMLSelectElement insufficiently pretending to be an array is also in https://github.com/servo/servo/issues/25003; there is possibly overlap, if the reason getOwnPropertyDescriptor isn't working is that the property isn't even there to get.

Other failures are DOMTokenList with numeric properties and DOMStringMap with named ones.

**Comment by jdm** [comment]
Relevant to getOwnPropertyDescriptor for legacy objects: https://github.com/servo/servo/blob/54d88fd042d3d1d382b36bf5d53308dabc35991d/components/script/dom/bindings/codegen/CodegenRust.py#L5130-L5228

**Comment by pshaughn** [comment]
I don't understand that code very well. In the named getter case, where is it actually looking up the name?

**Comment by pshaughn** [comment]
https://github.com/servo/servo/blob/5c7a4db5f4e374dee287d403d90c7bc0e07ac9d0/tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/form-nameditem.html#L112-L118 this test seems to be getting back a descriptor that exists, but that has .value=undefined. Could that be related to the FIXME(#11868) not setting the real value?

**Comment by jdm** [comment]
That seems entirely plausible, yes.

**Comment by pshaughn** [comment]
Removing the .get() gets us three asserts further down in this particular test (failing on desc.enumerable); if it doesn't break anything else, it's an improvement.

**Comment by jdm** [comment]
What's the enumerable failure? The descriptor returned should be unconditionally enumerable based on the [this line](https://github.com/servo/servo/blob/54d88fd042d3d1d382b36bf5d53308dabc35991d/components/script/dom/bindings/codegen/CodegenRust.py#L5147).

**Comment by pshaughn** [comment]
The test wants it to not be enumerable: https://github.com/servo/servo/blob/5c7a4db5f4e374dee287d403d90c7bc0e07ac9d0/tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/form-nameditem.html#L121

**Comment by jdm** [comment]
Aha, that comes from step 2.8 of https://heycam.github.io/webidl/#LegacyPlatformObjectGetOwnProperty, since HTMLFormElement is listed in https://heycam.github.io/webidl/#LegacyUnenumerableNamedProperties.

**Comment by pshaughn** [comment]
I see how that happened. The build is set up to fail if that extended attribute's specified without a named getter, and HTMLFormElement didn't have one yet when the extended attribute was being handed out. Window will also need it once it gets a named getter, and HTMLAllCollection once it exists.

**Comment by pshaughn** [comment]
Updated #25446 now that I know it will fix this and not break anything else.

**Comment by pshaughn** [comment]
remaining WebIDL/ecmascript-binding/legacy-platform-object.html failures are HTMLSelectElement-specific and probably just its lack of an indexed setter, #25003
