### ISSUE TITLE
DOMException.prototype has its own toString but should only inherit from Error

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25042]
WPT WebIDL/ecmascript-binding/es-exceptions/custom-bindings.any brings us this detail, "Inherits its toString() from Error.prototype". It seems a bit academic at first glance, but if someone sets a custom toString on Error as part of some framework they're going to want their customization to apply to DOMException, not be overridden by a more specific one.

**Comment by jdm** [comment]
This is almost certainly caused by the presence of `stringifier` in DOMException's WebIDL file, which is not present in [the spec](https://heycam.github.io/webidl/#idl-DOMException).
