### ISSUE TITLE
Error.toString seems to be looking directly at IDL-defined name and message attributes, not calling getters on the instance

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25043]
This is in WPT WebIDL/ecmascript-binding/es-exceptions/DOMException-custom-bindings.any. "The default Error.prototype.toString() behavior must work on shadowed names and messages.". It's testing it by overriding the name and message with property-defining, instead of with assignment, and the properties it defines don't seem to be getting called by toString.

**Comment by jdm** [comment]
Interestingly, `stringifier` is present in our DOMException webidl, but not in [the spec](https://heycam.github.io/webidl/#idl-DOMException).

**Comment by pshaughn** [comment]
The test output was misleading; Error.toString is itself fine actually. The actual cause here is #25042.
