### ISSUE TITLE
Babylonjs demos don't have the correct pointer

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#25097]
The babylon demos on https://servo.org/hl-home/ seem to render the pointer as coming out of the hand grip, which makes it super unweildy to use the pointer (it's basically 90 degrees off). Given that we correctly render pointers with threejs, it feels like Babylon is perhaps using the grip space instead of the target ray space, but that doesn't seem to be the case from looking at the code.

**Comment by Manishearth** [comment]
cc @paulrouget

**Comment by jdm** [comment]
Sounds like https://github.com/BabylonJS/Babylon.js/issues/7236.
