### ISSUE TITLE
Is response.trailer something to implement?

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25104]
It's commented out in Servo's IDL, and it seems to be undefined in every browser, but WPT fetch/api/response/response-trailer.html tests for it. Deciding on an answer to this might be premature when more important attributes like response.body are needed.

**Comment by jdm** [comment]
Given https://github.com/web-platform-tests/wpt/pull/20720 and https://github.com/whatwg/fetch/pull/979, the answer appears to be no.
