### ISSUE TITLE
Attr does not implement interface Node

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25124]
WPT dom/nodes/Document-importNode, last test.

doc is created using document.implementation.createHTMLDocument. setAttributeNS and getAttributeNodeNS are used on it, and then the output of getAttributeNodeNS is passed to document.importNode, which doesn't believe it's a Node. Comparing Servo's IDL to https://dom.spec.whatwg.org/#interface-attr it looks like Servo has implemented Node attributes directly into attr without inheritance.

**Comment by jdm** [comment]
Several years ago the spec made changes to remove the Node parent from Attr, but I'm pretty sure it was deemed incompatible with the web and reverted since then.

**Comment by pshaughn** [comment]
What's the right style for implementing something like the polymorphism in https://dom.spec.whatwg.org/#dom-node-nodevalue ? Make NodeMethods::GetNodeValue/SetNodeValue call an internal method that Attr/Text/etc have their own overrides of? The current implementation isn't being polymorphic at all, which it's getting away with because everything other than Attr is either null or the common case that's currently the only case.

**Comment by jdm** [comment]
It's easiest to compare against the specification if the implementation in Node just performs a series of `if let Some(attr) = self.downcast::<Attr>() {` branches.
