### ISSUE TITLE
document.getElementsByName seems to be a static collection that doesn't reflect a subsequent appendChild

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25147]
WPT html/dom/documents/dom-tree-accessors/document.getElementsByName/document.getElementsByName-liveness.html tests this. I also tried changing the appended child from an embed to an input in case it was a problem with embed getting, with no change.

**Comment by pshaughn** [comment]
https://dom.spec.whatwg.org/#old-style-collections suggests that many things specced as returning an HTMLCollection or NodeList may be implicitly expected to return a "live" one.

https://html.spec.whatwg.org/multipage/dom.html#dom-document-getelementsbyname goes out of its way to specifically say this one is live.

Servo's NodeList currently is implemented to either be static or to be specifically the live children of a node; HTMLCollection has a more general concept of a filtering live collection, and copying some of that into NodeList might be a starting point for this.

**Comment by jdm** [comment]
Marking as high value because the distinction between static/live lists seems likely to cause subtle web compat problems in Servo.

**Comment by pshaughn** [comment]
I'll start working on this now; either this or #25424 will need a little merge-conflict resolution after the other one is merged, but it's just adding different cases in the same match and not semantically a conflict.
