### ISSUE TITLE
Intermittent CRASH in /css/CSS2/borders/border-bottom-color-139.xht

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#25140]
https://community-tc.services.mozilla.com/tasks/NFTSpGVsSvuMy9BdroCNUQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FNFTSpGVsSvuMy9BdroCNUQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Ffiltered-wpt-errorsummary.log

**Comment by jdm** [comment]
Logs expire. Text is forever:
```
  ▶ CRASH [expected PASS] /css/CSS2/borders/border-bottom-color-139.xht
  │ 
  │ 
  │ 
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ 
  │ 
  │ 
  └ Shutting down the Constellation after generating an output file or exit flag specified
```
