### ISSUE TITLE
worker.onmessage is seeing non-empty event.origin

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25149]
This happens in WPT workers/interfaces/DedicatedWorkerGlobalScope/postMessage/message-event.html. I don't see anything explicit in the standard saying to set origin to an empty string here, but I'm also not seeing anything in the worker or message port steps saying _to_ set it to a real origin, so the implication must be to leave it default, and browsers are passing this test.

**Comment by kunalmohan** [comment]
Hi! I want to try and solve this issue, if it's not a problem.
I see that the function to be edited is this:
https://github.com/servo/servo/blob/728133611656f37480b96103dcc1d025f7d12ba3/components/script/dom/messageevent.rs#L78-L85
Should I completely remove the origin parameter it is accepting here (and make the required changes in all of its calls) or should it be left unutilized?

**Comment by pshaughn** [comment]
MessageEvent is used in many different ways; some of them are specified as explicitly setting origin, and some of them aren't. If you click on the bolded word "origin" in https://html.spec.whatwg.org/multipage/comms.html#dom-messageevent-origin you should get a popup of all the places the HTML specification references it.

**Comment by kunalmohan** [comment]
Oh, my mistake. I was not aware of all the different specs that it supported. It will take me some time, but I'll try to understand the usage (especially the posting messages section) and the serialization of origin, and will update my status soon.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/728133611656f37480b96103dcc1d025f7d12ba3/components/script/dom/messageevent.rs#L148-L162 is the code that creates the MessageEvent that is used for worker.onmessage. Looks like we're explicitly passing a non-empty origin value there; we should always pass an empty string instead.

**Comment by jdm** [comment]
That was the wrong code link - I meant to link https://github.com/servo/servo/blob/728133611656f37480b96103dcc1d025f7d12ba3/components/script/dom/worker.rs#L158-L166, where we should pass a None value instead of the origin.

**Comment by jdm** [comment]
In fact, we should remove the origin argument from Worker::handle_message entirely.

**Comment by kunalmohan** [comment]
Thanks for pointing that out. That will save a lot of time :)

Just out of curiosity, while I was looking around, I found this:
https://github.com/servo/servo/blob/d47f0ad1f672c7f1543eb753fc87c6acdf9f16e8/components/url/origin.rs#L79-L82
I cannot understand how this works. The recursive call (I could not find any other declaration of `ascii_serialization`, so I figured it must be recursive) is confusing me a bit. Can you explain this briefly?

**Comment by jdm** [comment]
[into_url_origin](https://doc.servo.org/servo_url/origin/enum.ImmutableOrigin.html#method.into_url_origin) returns a [url::Origin](https://doc.servo.org/url/origin/enum.Origin.html), which comes from the rust-url crate (which is different than components/url).

**Comment by kunalmohan** [comment]
Oh, I see. Now I get it. Thanks:)
