### ISSUE TITLE
Consider making JS<T> nullable

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#2516]
To work around the lack of null pointer optimization and to cut DOM node size by about half, we could make `JS<T>` nullable, and to have the `.get()` method on it explicitly return an `Option` to maintain type safety.

This would let us pack quite a bit more information into the reserved slots when we get around to that, which is always cool.

**Comment by Swatinem** [comment]
Wasn’t this fixed by https://github.com/servo/servo/commit/5225442dc15497f198de08647f387e314aed3f15 ?

**Comment by jdm** [comment]
Yep!
