### ISSUE TITLE
Build servo as dependency fails

### ISSUE THREAD

**Issue by deeprobin** [servo/servo#25172]
I want to use servo as an dependency for an application like electron for chromium.
The problem is - the build fails.

Rust Toolchain: nightly-2019-11-16
Cargo Version: cargo 1.40.0-nightly (5da4b4d47 2019-10-28)
Source Code: https://github.com/DeepRobin/node-servo
Error Log on windows build: https://hasteb.in/yarotado.txt
Error Log on ubuntu github actions: https://github.com/DeepRobin/node-servo/commit/8fa8cb5f25c963c07e6d27548018962bc05b5737/checks?check_suite_id=343947727

How can I fix that?

**Comment by SimonSapin** [comment]
```
   --> C:\Users\robin\.cargo\git\checkouts\servo-12bfca331f128de3\41ff93e\components\webrender_traits\lib.rs:134:32
    |
134 |             source: webrender::ExternalImageSource::NativeTexture(texture_id),
    |                                ^^^^^^^^^^^^^^^^^^^ could not find `ExternalImageSource` in `webrender`
```

You need to use the same commit of WebRender that Servo does. You can find what it is for a given Servo commit by looking in `Cargo.lock`, near `name = "webrender"`. Then run (for example) `cargo update -p webrender --precise edac864107cf43732ec66a9d3288e869a70ce1de` and commit the resulting `Cargo.lock` file in your repository.

In fact, I don’t know if this actually works but if you copy Servo’s entire `Cargo.lock` into your project as a starting point that might help avoid other issues of this kind.

```
Package libunwind-generic was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libunwind-generic.pc\'\nto the PKG_CONFIG_PATH environment variable
```

Does your build environment have all system dependencies? https://github.com/servo/servo#user-content-other-dependencies

**Comment by paulrouget** [comment]
> if you copy Servo’s entire Cargo.lock into your project as a starting point that might help avoid other issues of this kind.

Yes. This works (also see https://github.com/rust-lang/cargo/issues/4353).

It's also necessary to copy the `rust-toolchain` file and the `resources` directory.

> I want to use servo as an dependency for an application like electron for chromium.

I would recommend to build servo as a C library (`./mach build --libsimpleservo`) and use that library in your project.
