### ISSUE TITLE
Access-Control-Allow-Credentials is incorrectly case-insensitive, should only work for lowercase "true"

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25178]
Tested in WPT cors/credentials-flag.htm, other browsers pass these cases (Safari fails others in a different way)

**Comment by Eijebong** [comment]
This is a bug in headers https://github.com/hyperium/headers/blob/f241b566318aef0874dee1598f76187d23fb1ebd/src/common/access_control_allow_credentials.rs#L45

Here's the spec: https://fetch.spec.whatwg.org/#ref-for-http-access-control-allow-credentials

Here's the PR: https://github.com/hyperium/headers/pull/56

**Comment by Eijebong** [comment]
Will be fixed once headers gets updated (which will probably require a whole hyper bumping)

**Comment by shanehandley** [comment]
I believe this is fixed and can be closed: https://wpt.fyi/results/cors/credentials-flag.htm?run_id=5153303455858688

**Comment by mrobinson** [comment]
Thank you!
