### ISSUE TITLE
Many event handler on* attributes default to undefined where WPT expects null

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25184]
html/webappapis/scripting/events/event-handlers-all-global-events.html fails many subcases like this.

**Comment by CYBAI** [comment]
I think the sub test cases are failed by the SVGElement. It should be fixed when we introduce SVGElement.

https://github.com/servo/servo/blob/f2b363b3f006c90d77c7cc04f72ef00e676fa23a/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-all-global-events.html#L33-L38

**Comment by pshaughn** [comment]
Thanks to @CYBAI's tip I can confirm this as containing only duplicate of other issues that are tracked separately and can be addressed separately. The onauxclick, onslotchange, and onsecuritypolicyviolation attributes have individual issues in #25181 #23590 #25182 and everything else is because there's no SVGElement inheriting global event handlers, which seems covered by #12973.
