### ISSUE TITLE
Setting element.onerror on a body or frameset element from a document that doesn't have a window should leave it null, not actually set it.

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25187]
This is case "Ignore setting of error window event handlers on windowless {body|frameset}" in html/webappapis/scripting/events/event-handler-attributes-windowless-body.html. Many handlers are tested, only error fails.

**Comment by jdm** [comment]
[`define_window_owned_event_handler`](https://github.com/servo/servo/blob/e8d677ad264876838d297bd6843d0b02cc488dd9/components/script/dom/macros.rs#L335-L344) checks for this case, but the onerror attribute check for HTMLBodyElement [does not](https://github.com/servo/servo/blob/e8d677ad264876838d297bd6843d0b02cc488dd9/components/script/dom/htmlbodyelement.rs#L209-L219).

**Comment by pshaughn** [comment]
I sprinkled HTMLBodyElement::attribute_mutated with warn! statements and ran the test with RUST_LOG=script::dom and I never see any of the messages I put in, not even one right at the top of attribute_mutated.

I'm wondering if this might mean something wrong in DOMParser. The test calls DOMParser to try to make a document with MIME type "text/html", but if the resulting document doesn't really know it's HTML, then its createElement could be creating a generic Element with tagName "body" instead of an HTMLBodyElement.

**Comment by jdm** [comment]
Possibilities:
* It's going through Setonerror and not calling SetAttribute at any point
* HTMLBodyElement is not included correctly in the big match in vtable_for_node so it's attrubute_mutated is never called, only a parent's method like HTMLElement::attribute_mutated

**Comment by pshaughn** [comment]
A few more details to help narrow things down:
* setAttribute("onerror") and setAttribute("onclick") do go through HTMLBodyElement::attribute_mutated
* .onclick= does not go through attribute_mutated
*  the same things happen when just using a regular document.body; creating the document from DOMParser is not relevant to whether attribute_mutated is called on it
* if I change the test to use setAttribute instead of assignment, then the situation of @jdm's earlier comment applies and copying the has_browsing_context check from define_window_owned_event_handler passes the modified test.
