### ISSUE TITLE
Can't Atomics.wait in DedicatedWorkerGlobalScope, WPT says it should be possible

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25191]
This is in html/webappapis/scripting/processing-model-2/integration-with-the-javascript-agent-formalism/requires-success-any.js, which appears when running the test as requires-success.any.worker.html.

I don't know from the test failure whether this is a narrow problem with Atomics.wait or if there's a broader issue with workers not being allowed to block; either way, it seems likely to involve mozjs code.

**Comment by jdm** [comment]
This is [part](https://tc39.es/ecma262/#sec-atomics-object) of the ECMAScript specification, specifically related to SharedArrayBuffer.

**Comment by jdm** [comment]
And more specifically, this won't exist unless we call [setSharedMemoryAndAtomicsEnabled](https://searchfox.org/mozilla-central/rev/d24696b5abaf9fb75f7985952eab50d5f4ed52ac/js/src/jsapi.cpp#1719) when creating a realm, although we actually do [set that to true](https://github.com/servo/servo/blob/605ddbecd4dfbbb67849cf63774b2d7635fc3601/components/script/dom/bindings/interface.rs#L143) which is a bit scary.

**Comment by gterzian** [comment]
I've looked into this a bit.

It seems the error encountered is [`JSMSG_ATOMICS_WAIT_NOT_ALLOWED`](https://github.com/servo/mozjs/blob/aabcc9ba889b2755f1e4e83f28323a60415a790f/mozjs/js/src/js.msg#L611), which I think is raised at https://github.com/servo/mozjs/blob/aabcc9ba889b2755f1e4e83f28323a60415a790f/mozjs/js/src/builtin/AtomicsObject.cpp#L528

I'm not sure if this is covered by the `sharedMemoryAndAtomics_` flag, looking at the mozjs code the only place where `cx->fx.setCanWait(true)` is called seemed to  be when you call [`JS_SetFutexCanWait(JSContext* cx)`](https://github.com/servo/mozjs/blob/aabcc9ba889b2755f1e4e83f28323a60415a790f/mozjs/js/src/jsapi.cpp#L389), so I think the solution might be to manually call it when creating the runtime for the window agents and dedicated worker agents(but not the service worker agents, who `CanBlock` is false, see https://html.spec.whatwg.org/multipage/webappapis.html#integration-with-the-javascript-agent-formalism)

**Comment by gterzian** [comment]
Yep Gecko also seems to do this: https://searchfox.org/mozilla-central/source/dom/workers/RuntimeService.cpp#954

**Comment by gterzian** [comment]
Ah interesting that the test is passing in the window, just not in the dedicated worker, I wonder why.

**Comment by pshaughn** [comment]
The window runs the requires-failure test, not the requires-success one, and throws the exception it expects to see.

**Comment by gterzian** [comment]
Ok thanks for pointing that out(I though `!default` in the META meant window). 

That surprises me actually, since a [similar origin window agent](https://html.spec.whatwg.org/#similar-origin-window-agent) has `[[CanBlock]]` set to true. 

In the meantime I'll try to see if I can fix the dedicated worker test.
