### ISSUE TITLE
ev.ports === ev.ports is false for a message event

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25193]
html/webappapis/scripting/events/messageevent-constructor.https.html tests this.

script/dom/messageevent.rs looks like it makes a new FrozenArray out of self.ports whenever Ports is accessed, which naturally leads to this result.

I see that Servo's IDL has commented out the part about ev.ports having to be a FrozenArray and I imagine that relates to this implementation decision. #10427 might also be related.

**Comment by jdm** [comment]
We should probably be caching this value in a field of MessageEvent so we can return it on subsequent gets instead of creating a new FrozenArray every time.

**Comment by pshaughn** [comment]
fixed in https://github.com/servo/servo/pull/25468
