### ISSUE TITLE
Dispatching an ErrorEvent to a document passes five arguments to document.onerror instead of one (it appears that only window.onerror should get five)

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25197]
This happens in WPT html/webappapis/scripting/events/event-handler-processing-algorithm-error/script-element.html and document-synthetic-errorevent.html.

An error event that occurs in Javascript execution will normally hit the listener that's on window (and should be reflected to document.body), not the listener on document. As far as I can tell, the only way to hit document.onerror is to explicitly dispatch an error event directly at the document, which is what these tests do.

**Comment by pshaughn** [comment]
https://github.com/servo/servo/blob/937efba0cd6662b4e0060e7056c52dac2896535c/components/script/dom/eventtarget.rs#L509-L516
appears to be our implementation of the decision in step 4 of https://html.spec.whatwg.org/#the-event-handler-processing-algorithm. I see nothing obviously wrong here; maybe "self" is somehow the global and not the document?

**Comment by pshaughn** [comment]
This turns out to be a little more complicated than I expected: all we know here is that object is a DomObject, not that it's Castable, so we can't directly ask it whether it's a window.

**Comment by jdm** [comment]
Using `T: DomObject + Castable` should address that.
