### ISSUE TITLE
WPT sync task reported as successful when it fails

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#25213]
See for example

* https://community-tc.services.mozilla.com/tasks/dZSbixliQ7uKGqvct7_7SA/runs/0
* https://community-tc.services.mozilla.com/tasks/dZSbixliQ7uKGqvct7_7SA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FdZSbixliQ7uKGqvct7_7SA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L401

Maybe we need to add `-o pipefail` here?

https://github.com/servo/servo/blob/013bb662cb663b2e7d252a7d47595eb279bd1eea/etc/taskcluster/decisionlib.py#L681-L682

CC @jdm

**Comment by mrobinson** [comment]
I don't think I've seen this with the GitHub Actions based sync, but we can reopen this if it reoccurs.
