### ISSUE TITLE
Fix mach bootstrap on Windows

### ISSUE THREAD

**Issue by MeFisto94** [servo/servo#25224]
According to jdm on the IRC, mach bootstrap doesn't do anything useful, because every build-related command is already triggering [windows_msvc](https://github.com/servo/servo/blob/master/python/servo/bootstrap.py#L275).

Invoking bootstrap however, is done by https://github.com/servo/servo/blob/master/python/servo/bootstrap.py#L396 which in turn is called from https://github.com/servo/servo/blob/master/python/mach_bootstrap.py#L241

The following exception happens when ./mach bootstrap is invoked:
```
$ ./mach bootstrap
Traceback (most recent call last):
  File "./mach", line 103, in <module>
    main(sys.argv)
  File "./mach", line 31, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "e:\Marc\Documents\Coding\servo\python\mach_bootstrap.py", line 245, in bootstrap_command_only
    bootstrap(context, force)
  File "e:\Marc\Documents\Coding\servo\python\servo\bootstrap.py", line 413, in bootstrap
    return bootstrapper(context, force=force)
  File "e:\Marc\Documents\Coding\servo\python\servo\bootstrap.py", line 278, in windows_msvc
    deps_dir = os.path.join(context.sharedir, "msvc-dependencies")
AttributeError: 'DummyContext' object has no attribute 'sharedir'
```
I think the solution to this is adding `context.sharedir = os.path.join(context.topdir, ".servo")` to the lastly linked code in mach_bootstrap.py, because other build tasks indeed _do_ download the dependencies to `.servo` relative to the topdir.

Note that this would affect windows and linux alike, but it seems this sharedir is only requested from salt and windows and not linux, which installs the packets globally using apt.

**Comment by MeFisto94** [comment]
According to https://github.com/servo/servo/blob/master/python/servo/command_base.py#L316
`context.sharedir = self.config["tools"]["cache-dir"]` is the correct value for the sharedir.
I assume we cannot inherit from that class, because mach bootstrap happens before mach is fully functional?

**Comment by jdm** [comment]
This might be a regression from https://github.com/servo/servo/pull/24567.
