### ISSUE TITLE
Headless mode breaks with --debug on macOS

### ISSUE THREAD

**Issue by jdm** [servo/servo#25231]
Running `./mach run --headless --debug` panics with: `Could not open dynamic library `OsMesa` (thread main, at src/libcore/option.rs:1187)`. It works if you make mach print out the environment it builds that includes GALLIUM_DRIVER and DYLD_LIBRARY_PATH and run `env GALLIUM_DRIVER=softpipe` and `env DYLD_LIBRARY_PATH=[path]` inside lldb before starting Servo.

lldb appears not to bring in the outside environment into the debuggee's environment. This may be related to https://stackoverflow.com/questions/33587130/why-doesnt-lldb-forward-my-environment-variable-anymore.

**Comment by SimonSapin** [comment]
OSMesa-src is no longer used since https://github.com/servo/servo/pull/25853, is this still relevant?

**Comment by jdm** [comment]
No.
