### ISSUE TITLE
Clicking things in the HL emulator is very difficult

### ISSUE THREAD

**Issue by jdm** [servo/servo#25238]
I suspect this is a regression from #24778, because there's lots of output like "Got a touchend event for a non-active touch point". I basically have to hammer the space bar until something changes and Servo decides to click what I'm pointing at :<

cc @paulrouget

**Comment by paulrouget** [comment]
I will look.

I'm not happy about the fact we are ignore taps now. But according to @Manishearth that's something that happens often.

I'll see if I can find a way to satisfy both problems without generating 2 click event (tap + touch).

**Comment by paulrouget** [comment]
@jdm can you share some STR and the version of the emulator you're using?

**Comment by jdm** [comment]
I'm using the 1042 emulator image. My steps to reproduce are to run Servo and attempt to launch the Color Picker demo by positioning the pointer over the button with the arrow keys. When I'm able to launch it after several clicks, I then try to position the pointer over the VR headset button to enter immersive mode and click it. This usually requires 5-10 clicks before I can trigger it.

**Comment by Manishearth** [comment]
> "Got a touchend event for a non-active touch point"

we should be logging the touch ids, if we're seeing this then there's something buggy there

**Comment by paulrouget** [comment]
> there's something buggy there

Yes. I mentioned this to MS. It might be caused by the "MR input injection into slates rather than the underlying XAML stack"

**Comment by paulrouget** [comment]
@jdm sadly I can not reproduce here. I followed your exact steps, and it clicks properly.

Do you press the alt key (right key for right hand, left key for left hand) when you press the space bar?

**Comment by jdm** [comment]
I press nothing except the space bar. Very curious! Are you using the 1042 emulator image?

**Comment by paulrouget** [comment]
> Are you using the 1042 emulator image?

Yes.

Does the behavior change if you click with the alt key pressed?

**Comment by paulrouget** [comment]
With 1044, I can not reproduce this.

I have been trying to use just head movement (just click and drag) to align the hand ray with the buttons, and press space, or use the alt key as I’m click-and-dragging the mouse just to move the hand, then press alt+enter/spacebar, and the click registers no matter what.

I’m out of ideas.

**Comment by paulrouget** [comment]
I have a theory.

@jdm do you just move the head POV until the pointer reaches the section you want to click?

If so, the pointer is not moving, then not sending the move events.

If you actually move the hand/pointer (not moving the POV), I think it will work as expected.

**Comment by jdm** [comment]
@paulrouget yes, that sounds like what I do.

**Comment by paulrouget** [comment]
FYI, something changed recently, and I can now reproduce the exact issue even with properly moving the pointer. I will investigate later.

**Comment by jdm** [comment]
I haven't observed this problem for a while.
