### ISSUE TITLE
Use ExtendableMessageEvent for messageerror in service workers

### ISSUE THREAD

**Issue by gterzian** [servo/servo#25241]
In the light of https://github.com/w3c/ServiceWorker/pull/1485

code: https://github.com/servo/servo/blob/b98a8fc57671ab83ea698fc1d2be76330fa3f374/components/script/dom/serviceworkerglobalscope.rs#L418

Also requires adding a `dispatch_error` method to https://github.com/servo/servo/blob/b98a8fc57671ab83ea698fc1d2be76330fa3f374/components/script/dom/extendablemessageevent.rs#L85

**Comment by nosark** [comment]
I'd like to work on this issue!

**Comment by gterzian** [comment]
Thanks @nosark, let me know if you have an questions.

**Comment by nosark** [comment]
@gterzian I want to clarify the necessary changes to be made. Am I adding the dispatch_error functionality to ExtendableMessageEvent and then replacing the MessageEvent::dispatch_error call in serviceworkerglobalscope.rs with the ExtendableMessageEvent::dispatch_error call? Do I need to create any new tests for the added dispatch_error function? Is there anything I'm missing? Thanks @gterzian !

**Comment by gterzian** [comment]
Yes that sounds like a correct description. 

Regarding the tests, it looks like they were already added/changed in the WPT test suite by Chromium in https://chromium-review.googlesource.com/c/chromium/src/+/1921521 although it looks we  haven't synced yet(which I believe will be done at some point semi-automatically). So I don't think you need to change anything. If your change makes a test fail, we will have to look into it, perhaps add a partial sync with the upstream test suite to your PR.

**Comment by jdm** [comment]
Those test changes were made last December, so we have definitely synced since then. That being said, we can't run most service worker tests because our implementation is very incomplete.

**Comment by nosark** [comment]
@gterzian @jdm Awesome, thank you for all of the info! Just a heads up, I was just assigned a concussion recovery protocol (hockey) so it may take me a little longer than usual, but I'll get this out asap!

**Comment by nosark** [comment]
Hey guys, I've started implementing this, but I am receiving a linking error similar to issue #20736
https://github.com/servo/servo/issues/20736. If I can't get around this, should I setup my windows machine and test and submit from that machine instead of my macbook?

**Comment by jdm** [comment]
Yes, it's important to be able to build when submitting code changes. Sorry we don't have any good suggestions for the linking error.

**Comment by nosark** [comment]
@jdm Awesome, thanks for the quick response, I'll get right on it!

**Comment by nosark** [comment]
@jdm Everything is building again on my mac, And I'm trying to test my solution. Is there a specific test I could run my solution against? I've tried running against the WPT test suite and most of the tests throw a navigator.serviceWorker.getRegistration() is not a function error. I imagine this error could be from the incomplete service worker tests implementation mentioned above. Thanks in advance!

**Comment by jdm** [comment]
Our service worker implementation is still incomplete, so I doubt there are any automated tests that run to the point where they can verify this change. @gterzian may know better than me, though.

**Comment by gterzian** [comment]
Yes so currently the SW globalscope actually doesn't run, so we can't test it with javascript but I would say if it compiles it should be good enough for now. @nosark Do you want to open a PR with your work?

**Comment by nosark** [comment]
@jdm ok. @gterzian yeah I'll put in for PR. Thanks guys!

**Comment by kootoopas** [comment]
Someone with access should add the "has open pr" label to this.
