### ISSUE TITLE
Url parser can't handle spaces for data URIs

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#2524]
[This](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/data-uri-basic.htm#L25) test (requires [this](https://github.com/mozilla/servo/pull/2521) PR) is failing with `assert_equals: expected "Hello, World!" but got "Hello,World!"`. This happens even if I inspect `response` instead of `responseText` (`response` does not run the recently-added utf8 decoder)

If I use `%20` in place of the space, it works fine. Spaces in an HTTP url throw an error with `try_parse_url()`.

I guess the HTTP url handling is correct, but I'm not quite sure what the case is for data URIs.

Blocks #2525

**Comment by mbrubeck** [comment]
This is fixed.
