### ISSUE TITLE
Nightly zip archives aren't valid

### ISSUE THREAD

**Issue by jdm** [servo/servo#25251]
This is the case for both https://download.servo.org/nightly/windows-msvc/servo-latest.zip and http://download.servo.org/nightly/uwp/servo-latest.0.0.0_Test.zip. Something in https://github.com/servo/servo/pull/24575 regressed our zip packaging routines. cc @marmeladema

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/24575/commits/267eaad4ebcc26337956ae298babb98694554a1c is the most likely candidate, but I can't figure out why it would make a difference.

**Comment by Manishearth** [comment]
`zipfile.ZipFile()` probably needs a `"wb"` as well

**Comment by jdm** [comment]
No, it only accepts "w".

**Comment by pshaughn** [comment]
I think zipfile wants either a filename to open itself, or a full Python file-like object, not a stream without the Python file-like methods. Can you use just regular Python open here, not os.fdopen(os.open)?

**Comment by marmeladema** [comment]
@jdm how can I check that the fix actually works? I reverted the code almost as it was before (just added the 'b' more for python3 compat) but I'd like to be sure :-)

**Comment by jdm** [comment]
Confirmed that https://download.servo.org/nightly/windows-msvc/servo-latest.zip and http://download.servo.org/nightly/uwp/servo-latest.0.0.0_Test.zip are now valid zip files again.
