### ISSUE TITLE
2nd CSS Transition trigger a forever animation

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#25262]
In components/layout/animation.rs, at the end of the function `update_animation_state`, add a `println` to show which animation state is sent to the constellation.

See that `AnimationsPresent` is sent repeatedly on the second animation:

STR:

```html
<style>
  div {
    width: 200px;
    height: 200px;
    margin:200px;
    background: red;
    transition: 200ms linear transform;
  }
  div:hover {
    transform:scale(1.2);
  }
</style>
<div></div>
```

- mouse hover div
- animating then not animating (good)
- move mouse outside of the div
- animating is sent (good) but `NoAnimationsPresent` is never sent after the animation is finished

**Comment by jdm** [comment]
Looks like the same problem as https://github.com/servo/servo/issues/20379 :(

**Comment by paulrouget** [comment]
Dupe  #20379
