### ISSUE TITLE
`display: inline; position: relative` as containing block for abspos descendants

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#25279]
https://drafts.csswg.org/css2/visudet.html#containing-block-details
> If the element has 'position: absolute', the containing block is established by the nearest ancestor with a 'position' of 'absolute', 'relative' or 'fixed', in the following way:
>
> In the case that the ancestor is an inline element, the containing block is **the bounding box around the padding boxes of the first and the last inline boxes generated for that element**. In CSS 2, if the inline element is split across multiple lines, the containing block is undefined. 

Even though the spec is written as though finding the containing block is an operation that involves going up the tree, as of this writing the Layout 2020 code maintains a "current containing block for `position: absolute`" while going down the box tree while creating a fragment tree.

As of https://github.com/servo/servo/pull/25273, the intent of `for_maybe_position_relative` in `components/layout_2020/positioned.rs` was that it would be called for ~every box and take care of doing that maintenance in case that box has `position: relative`.

For inline boxes however, `components/layout_2020/flow/inline.rs` contains separate `start_layout` and `finish_layout` methods (to deal with line breaking), so there isn’t a single place to easily call `for_maybe_position_relative`. Additionally the `InlineFormattingContextState` struct contains a `&mut PositioningContext` field, so we can’t easily create a new `PositioningContext` and keep it on the call stack for each nesting level, like we do in block-level layout code. Instead we should probably take/replace the `for_nearest_positioned_ancestor` Vec inside that `PositioningContext`.

https://github.com/servo/servo/pull/25273 was large enough already so I’m leaving this for later, with this issue to track.

**Comment by mrobinson** [comment]
I am working on a fix for this which I hope to put up in a pull request in the next couple days.
