### ISSUE TITLE
Problem with building mozjs on Windows

### ISSUE THREAD

**Issue by nipunG314** [servo/servo#25302]
Hi, I have been trying to build Servo on Windows machine and I have run into a few problems. By directly following the instructions, I ran into the following problem:

```
Error running mach:

    ['build', '-d']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

WindowsError: [Error 2] The system cannot find the file specified

  File "C:\Users\Nipun\servo\python\servo\build_commands.py", line 248, in build
    env = self.build_env(target=target, is_build=True, uwp=uwp, features=features)
  File "C:\Users\Nipun\servo\python\servo\command_base.py", line 773, in build_env
    'git', 'rev-parse', '--short', 'HEAD'
  File "C:\Python27\lib\subprocess.py", line 213, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 391, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 641, in _execute_child
    startupinfo)
```

I fixed this problem by setting an additional parameter in `the check_output` function in the `subprocess` module. This is the git diff for the same:

```
diff --git a/python/servo/command_base.py b/python/servo/command_base.py
index 15ec195fd5..f5abd967e9 100644
--- a/python/servo/command_base.py
+++ b/python/servo/command_base.py
@@ -771,10 +771,10 @@ install them, let us know by filing a bug!")
         if os.path.isdir('.git') and is_build:
             git_sha = subprocess.check_output([
                 'git', 'rev-parse', '--short', 'HEAD'
-            ]).strip()
+            ], shell=True).strip()
             git_is_dirty = bool(subprocess.check_output([
                 'git', 'status', '--porcelain'
-            ]).strip())
+            ], shell=True).strip())
 
             git_info.append('')
             git_info.append(six.ensure_str(git_sha))
```

But now it has a different problem when building `mozjs_sys`, which can be seen [here](https://gist.github.com/nipunG314/5c0a9ef5683f2e3f3adedd20583e97d4). The error output is similar to the problem referenced in [#22737](https://github.com/servo/servo/issues/22737). 

However, updating my `llvm `version to the latest didn't solve the problem. I'm currently building with `llvm-9.0.0` and I'm getting the same error output. I have tried building with the nightly compiler and I have gotten the same problem.

Any suggestions on where I'm going wrong? Also, should I submit a PR for the subprocess module fix?

**Comment by nox** [comment]
Why did you need the `shell=True` part in the first place?

**Comment by rasviitanen** [comment]
I think the LLVM version just recently got updated to llvm-9.0.0, you should probably try llvm 8. I had some troubles with llvm-9.0.0 a while back, but it worked with 8.

**Comment by pshaughn** [comment]
Is there a git.exe on your windows PATH?

**Comment by nipunG314** [comment]
> Why did you need the `shell=True` part in the first place?

> Is there a git.exe on your windows PATH?

I figured out what the problem was. In my git installation, there was the git.exe file and a git.bat file that redirected to the executable. The batch file was in my PATH but not the executable. That's why thought git.exe was in my PATH but actually wasn't. I'm not entirely sure why it was installed this way. Adding the executable itself to the PATH fixed the issue.

> I think the LLVM version just recently got updated to llvm-9.0.0, you should probably try llvm 8. I had some troubles with llvm-9.0.0 a while back, but it worked with 8.

Alright, I'll try that. Thanks!

**Comment by nipunG314** [comment]
Yeah, downgrading LLVM to `8.1.0` worked. The build is successful and I can load webpages.
