### ISSUE TITLE
BabylonJS demo: looks like we are below the floor

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#25318]
https://servo.org/hl-home/bbjs/#JA1ND3%23163

The camera is below the floor. The demo hasn’t changed in a while. Likely a servo regression.

**Comment by jdm** [comment]
@Manishearth Could this be https://github.com/servo/servo/pull/25025?

**Comment by Manishearth** [comment]
No, I knew this would happen but was going to fix it so didn't file. This is #25259 which made us use the floor level defined in openxr/mod.rs, which is 1 meter instead of two. The quick fix is to make it 2. I want to land the actual fix for that soon.

**Comment by jdm** [comment]
This doesn't happen any more.
