### ISSUE TITLE
Docs: Inconsistent context for crates

### ISSUE THREAD

**Issue by MeFisto94** [servo/servo#25313]
https://github.com/servo/servo/blob/master/docs/HACKING_QUICKSTART.md#working-on-a-crate
It starts with cocoa-rs and glutin and then switches to mozjs_sys.
It should probably show cocoa-rs and glutin there, otherwise it's a bit confusing.

**Comment by jdm** [comment]
Oh, indeed. That is somewhat confusing to read!

**Comment by jahielkomu** [comment]
@mrobinson @jdm and @MeFisto94  Hello there. 
I can work on this, please expound more on this.

**Comment by mrobinson** [comment]
> @mrobinson @jdm and @MeFisto94 Hello there. I can work on this, please expound more on this.

If you read the section linked above you can see that the example in the documentation starts by using the crate `cocoa-rs`, but switches to talking about `mozjs` later in the example. It should be consistent throughout.

**Comment by jahielkomu** [comment]
@mrobinson 

> > @mrobinson @jdm and @MeFisto94 Hello there. I can work on this, please expound more on this.
> 
> If you read the section linked above you can see that the example in the documentation starts by using the crate `cocoa-rs`, but switches to talking about `mozjs` later in the example. It should be consistent throughout.


I made changes based on an extensive issue investigation I did and the result of running ```cargo pkgid cocoa``` which was in the format ```https://github.com/rust-lang/crates.io-index#cocoa@0.0.0``` . The closest format to this in the document is ```https://github.com/rust-lang/crates.io-index#cocoa#0.0.0``` .  Allow me ask; is ```#cocoa@0.0.0``` same as ```#cocoa#0.0.0``` ?

@mrobinson please check out the changes in the PR. 
I will wait on your review.  
Thanks.
