### ISSUE TITLE
Nested browser contexts require a pointer to their parent context

### ISSUE THREAD

**Issue by jdm** [servo/servo#2531]
It's currently impossible for a framed document (eg. in an iframe) to interact with its framing document synchronously, since Page only has a SubpageId and thus requires returning to the event loop. This makes it impossible to implement `Window.top` and `Window.frameElement` among other things. A pointer to the parent context will solve the first, while the second may require a live list of iframes and frameset elements to be performant (which would also get us `Window.frames` for free!)

**Comment by glennw** [comment]
Covered by PR #4842
