### ISSUE TITLE
mach.bat: Remove manual Visual Studio detection and defer to command_base.py

### ISSUE THREAD

**Issue by MeFisto94** [servo/servo#25336]
Speaking of mach.bat, in my opinion, we could delete everything before https://github.com/servo/servo/blob/79408fa36bae63eef07c5bbb5c92d40d3193d808/mach.bat#L49

The reason is, that this searches for visual studio installations the old/legacy way and calls vcvars.bat. 
I *suspect* this is so that MSBUILD is on PATH.
This will, however, fail early and thus not profit from the improved detection.
At the same time it's unnecessary to double-check for Visual Studio Installations.

In my experiments, having vcvars.bat excluded didn't break anything, especially since the code already locates the path to VS and uses that one (no need to have them on PATH, wouldn't work for me anyway [path limited to 1024 chars...]).

So we could do one of two things (or leave it as it is, of course):
 - Do thorough testing and exclude the vcvars.bat and see if the build breaks under any condition for anyone in their specific environment
 - Just continue with that legacy without thinking if it's required and just execute the .bat file from the python file (short after find_highest_msvc_version).

_Originally posted by @MeFisto94 in https://github.com/servo/servo/pull/25300#issuecomment-566804761_

**Comment by jdm** [comment]
A good first start would be to see if switching to `python mach` instead of `mach` in https://github.com/servo/servo/blob/master/etc/taskcluster/decision_task.py#L487-L496 passes CI.

**Comment by atouchet** [comment]
This was done in #25365.
