### ISSUE TITLE
Add lint check for `&Dom<` and `&DomRoot<`

### ISSUE THREAD

**Issue by jdm** [servo/servo#25342]
`&Dom<T>` and `&DomRoot<T>` are strictly less expressive than `&T`, so there's no reason to use them.

Code: https://github.com/servo/servo/blob/aa36d5f657eb32b59d994d08b177a02372b4b01c/python/tidy/servo_tidy/tidy.py#L624-L625

**Comment by lberrymage** [comment]
@highfive: assign me

**Comment by jdm** [comment]
After making the change, I expect `./mach test-tidy --all` will report some existing uses that should be cleaned up.

**Comment by lberrymage** [comment]
Good to know, thanks. Would it be best to correct those uses first to ensure each commit passes tests individually?

**Comment by jdm** [comment]
Putting them in the same commit would be nice, but it also isn't a hard requirement.
