### ISSUE TITLE
Can't install UWP Nightly because of missing certificate

### ISSUE THREAD

**Issue by Darkspirit** [servo/servo#25362]
Sideloading is not possible without manually installing the certificate.
Probably regressed by #25309: https://github.com/servo/servo/commit/b3d0388d83f883954b9165ef378a46fb3226bb4f#diff-99c45e2e6d2483a397f820708c4398eeR12
(`AppxPackageSigningEnabled=false`).

last good: https://servo-builds.s3.dualstack.us-west-2.amazonaws.com/nightly/uwp/2019-12-16T09:10:08Z-ServoApp_1.0.0.0_Test.zip
first bad: https://servo-builds.s3.dualstack.us-west-2.amazonaws.com/nightly/uwp/2019-12-17T09:09:58Z-ServoApp_1.0.0.0_Test.zip

**Comment by jdm** [comment]
Bleah. That's true, and I'm not really sure what to do about it, since signing with the certificate yields binaries that can't be submitted to the store.

**Comment by jdm** [comment]
This probably also is why I can't install the nightly build on devices as well :(

**Comment by Darkspirit** [comment]
At least I've found _a way_ of installing Servo UWP without a M$ account:
1. Paste https://www.microsoft.com/en-us/p/firefox-reality/9npq78m7nb0r into https://store.rg-adguard.net/ (RP means release preview) and download  [`MozillaFoundation.FirefoxReality_*.appxbundle`](http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/62f1b414-e77a-409c-a6a2-2b28710264f7?P1=1580301338&P2=402&P3=2&P4=pmhF71EOnhJ1SafCHhtUi0AvFYwEq3q%2bPzvslK4NRDS9qdbV82l4hNIdWsNYk8BsL0Q%2beLFCGJOiDFCLYpKeaw%3d%3d) directly [from](https://lists.w3.org/Archives/Public/public-webappsec/2019Apr/0012.html) Microsoft's CDN. (eappxbundle seems to be for Xbox?)
2. Open PowerShell, `cd` to the download directory and run
`Add-AppxPackage -Path "MozillaFoundation.FirefoxReality_*.AppxBundle"`
3. A start menu entry has been added. It's also possible to view it installed in the store:
Paste `ms-windows-store://pdp/?ProductId=9npq78m7nb0r` into Firefox' address bar.
In contrast, if I open VLC with `ms-windows-store://pdp/?ProductId=9nblggh4vvnh` I can install it directly. (Get > Use across your devices, sign in: No, thanks > Install > Launch) It would be great if this would work with Servo, too! Servo only has an "Install on my devices" button and enforces a login.
