### ISSUE TITLE
Cloning a form doesn't preserve changed values of its HTMLInputElement children.

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25385]
WPT html/semantics/forms/the-input-element/clone.html has a form with `value` and `checked` content attributes on many input children. It sets .value on the children, then calls cloneNode on the form. It gets back a clone, but the clone's children's values match the original values from their content attributes, not the updated values that were set by the script.

**Comment by jdm** [comment]
Node::clone's handling of elements doesn't include the concept of ["cloning steps"](https://dom.spec.whatwg.org/#concept-node-clone) (ie. step 5 of the algorithm), which includes specific steps for input elements (https://html.spec.whatwg.org/multipage/input.html#the-input-element%3Aconcept-node-clone-ext).

 https://github.com/servo/servo/blob/8002c6bc53041c55dc1148fed008b9a229df0e9b/components/script/dom/node.rs#L2146-L2160

We should probably extend the VirtualMethods trait to incorporate cloning steps.

**Comment by teapotd** [comment]
`VirtualMethods` trait already has `cloning_steps` method and `Node::clone` includes step 5:

https://github.com/servo/servo/blob/44b3e8bb7139f9599385b348d19d4dce556c9ea8/components/script/dom/node.rs#L2196-L2197

It suffices to implement `cloning_steps` for `HTMLInputElement`. I'd like to claim this one.

@highfive assign me
