### ISSUE TITLE
Synthetic click events aren't putting checkboxes/radio buttons in the right state in some cases

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25384]
In WPT html/semantics/forms/the-input-element/checkbox-click-events.html it looks like calling preventDefault in a click listener isn't stopping .click() from toggling the box (though the listener is called), and dispatching a new MouseEvent("click") when a click listener has been defined is calling the listener but not toggling the box.

**Comment by pshaughn** [comment]
radio-input-cancel.html indicates a similar preventDefault problem for radio buttons; it doesn't test their MouseEvent("click") behavior.

**Comment by pshaughn** [comment]
The preventDefault case is https://dom.spec.whatwg.org/#eventtarget-legacy-canceled-activation-behavior, with steps spelled out a little bit down the page from https://html.spec.whatwg.org/#input-activation-behavior

**Comment by pshaughn** [comment]
It looks like Servo's code is following an older spec revision, in which these were called "pre-click activation steps" and "canceled activation steps" instead of "legacy pre-activation behavior" and "legacy canceled activation behavior", and the steps are being called at slightly different points in the code, but on a first read-through it looks like the steps should already be getting called and doing what they're supposed to do.

**Comment by pshaughn** [comment]
Both tests are triggering the pre-click activation with .click() but not the canceled activation. Dispatching a MouseEvent named "click" is not even triggering the pre-click activation.

**Comment by pshaughn** [comment]
https://html.spec.whatwg.org/#event-firing says bubbles and cancelable should be true; Servo's synthetic_click_activation is setting them to false. This would almost certainly account for preventDefault calls from the click handler doing nothing and seems like a simple fix.

I also observe that Servo's step by step breakdown of click events is out of sync with the standard's phrasing at many points and seems due for a round of cleanup.

**Comment by pshaughn** [comment]
Setting bubbles and cancelable true passes the preventDefault test cases that call the click() method.

The MouseEvent dispatch case is significantly more complicated. In spec, the click() method is supposed to construct a "click" event, fire it, and return the result of firing it. All the special things that a click does with activation behavior are supposed to happen _because it's a click event_, and the click method doesn't refer to activation behavior at all. In Servo, synthetic_click_activation and authentic_click_activation themselves choreograph the activation behavior. 

I see a comment at the top of authentic_click_behavior saying "check with @Manishearth" about the authentic/synthetic distinction. The word "authentic" no longer even appears in the HTML spec, but the comment seems like it was very important at one time; what do I need to know here before I start refactoring activations to happen via event dispatch?

**Comment by pshaughn** [comment]
https://github.com/servo/servo/blob/3f5cb0e2f5f5e76753452dfc42187cf0ce8622f1/components/script/dom/element.rs#L3211-L3221

**Comment by jdm** [comment]
Does what you've found overlap with https://github.com/servo/servo/issues/22783?

**Comment by jdm** [comment]
Marking high value since the ordering and dispatch of events is likely to have significant web compat implications.

**Comment by Manishearth** [comment]
Yeah, that stuff seems to have changed completely, my comment is no longer relevant.

The important thing to note is that events triggered by `click()` should _not_ have their trusted flag set, but other events might.

**Comment by Manishearth** [comment]
So I'd say go ahead and make it match the spec, however make sure you keep an eye on which events are and aren't trusted.

**Comment by pshaughn** [comment]
Yes, #22783 looks like a description of the same out-of-dateness.
