### ISSUE TITLE
Fix UrlHelper::is_origin_trustworthy

### ISSUE THREAD

**Issue by Darkspirit** [servo/servo#25387]
https://github.com/servo/servo/blob/8002c6bc53041c55dc1148fed008b9a229df0e9b/components/script/dom/urlhelper.rs#L74-L87
https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy
Above http should be changed to https:
> If origin’s scheme is either "https" or "wss", return "Potentially Trustworthy".

Missing:
> If origin’s host component is "localhost" or falls within ".localhost", and the user agent conforms to the name resolution rules in [let-localhost-be-localhost], return "Potentially Trustworthy".

https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06#page-4
>        If application software wishes to make security decisions based
>        upon the assumption that localhost names resolve to loopback
>        addresses (e.g. if it wishes to ensure that a context meets the
>        requirements laid out in [SECURE-CONTEXTS]), then it MUST
>        directly translate localhost names to a loopback address, and
>        MUST NOT rely upon name resolution APIs to do so.

**Comment by Darkspirit** [comment]
@highfive assign me

**Comment by ghostd** [comment]
Hi,

This issues seems fixed:
https://github.com/servo/servo/blob/8800452e347bc62d04b5678baadb39705d45503b/components/url/lib.rs#L193-L217

**Comment by CYBAI** [comment]
> This issues seems fixed:

Yes! Thanks for catching this!
