### ISSUE TITLE
Many out-of-spec behaviors associating input elements with labels

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25391]
html/semantics/forms/the-label-element/label-attributes.sub.html tests various conditions about labels and gets several different failures; for example, moving an input element in or out of a label's descendants appears not to cause it to associate or disassociate with the label.

One failure is just that we don't have Shadow DOM but the rest look like they're legitimately about things labels should do.

**Comment by pshaughn** [comment]
One problem is that .labels isn't a live list. https://html.spec.whatwg.org/multipage/forms.html#dom-lfe-labels requires "Labelable elements and all input elements have a live NodeList object associated with them that represents the list of label elements, in tree order, whose labeled control is the element in question. The labels IDL attribute of labelable elements that are not form-associated custom elements, and the labels IDL attribute of input elements, on getting, must return that NodeList object, and that same value must always be returned"

I don't think that alone accounts for all the test failures though, as many of the tests are getting input.labels directly when asserting instead of using a stale labels value.

**Comment by pshaughn** [comment]
It was a 50/50 split between the live-list problem and others.

All of these fail because the NodeList isn't live (which is not to say they'd necessarily pass if it was, but they definitely fail if it isn't):

    [The labeled control for a label element that has no 'for' attribute is the first labelable element which is a descendant of that label element.] (This test name doesn't imply moving nodes, but the test actually does move them and this failure is when it's looking at a stale list)
    [A labelable element is moved to inside of nested associated labels.]
    [A labelable element which is a descendant of non-labelable element is moved to outside of associated label.]
    [A labelable element is moved to iframe.]
    [A div element which contains labelable element is removed.]

[A non-control follows by a control with same ID.] looks like a separate problem. I would guess that we're matching on the first control with the ID, instead of looking at only the first element with the ID and failing if it's a non-control.

[A labelable element is moved to outside of nested associated labels.] looks like a separate problem, though not the one the test name describes. It's failing at "The labels for a form control should be returned in tree order." before any mutations have happened to make the list stale.

[A labelable element not in a document can label element in the same tree.] looks like a separate problem. It fails at "The first labelable descendant of a label element should be its labeled control.", which seems to imply that a label detached from its document might just be giving up instead of looking for elements to label within its detacted tree.

[A labelable element inside the shadow DOM.] naturally fails since we don't have shadow DOM.

[A form control has an implicit label.] looks like a separate problem. I haven't looked at the code yet, but possibly controls are only looking for label parents and not label grandparents.

**Comment by pshaughn** [comment]
[A form control has an implicit label.] turns out not to be a separate problem. An earlier test, [The labeled control for a label element that has no 'for' attribute is the first labelable element which is a descendant of that label element.], modifies the tree, makes some asserts, then undoes its modification. Because that test is failing in Servo (for lack of .labels liveness), its modification is never undone, so then when we get to this test, we still have the modified tree and this test isn't seeing what it expects.

**Comment by pshaughn** [comment]
[A labelable element not in a document can label element in the same tree.] is straightforward; it just needs to search the descendants of GetRootNode instead of document_from_node.

"The labels for a form control should be returned in tree order." is an accurate statement of a condition that HTMLElement::labels currently isn't meeting: it's getting all the ancestor labels with no for= in reverse tree order, followed by all the for=id labels in tree order. It seems like literally sorting that list, using CompareDocumentPosition as a comparison function, might be the best answer here; the number of labels to sort on a real page will normally be small enough that I doubt there'll be a performance concern.

[A non-control follows by a control with same ID.] is unclear me at the moment, but I'm sure I can figure it out if I jam enough log statements into HTMLElement::labels.

Ultimately, the contents of HTMLElement::labels will have to become the backing logic for a live NodeList associated with the elemetn, instead of a method allocating a new NodeList every time it's called, but I think making it correct and making it live can be done as separate changes, and right now I'm going to focus on making it correct.

**Comment by pshaughn** [comment]
[A non-control follows by a control with same ID.] fails because labelable elements are looking for label elements where the "for" attribute matches self's ID, but not confirming that the self is actually the label's labeled control, which it might not be in cases where there's more than one element of the same ID.

**Comment by pshaughn** [comment]
In https://github.com/pshaughn/servo/tree/labelfixes so far I've fixed the two subcases that can be fixed without a live NodeList or shadow DOM, and I've gotten past the "The labels for a form control should be returned in tree order." assert to another assert in that test that needs a live NodeList.

I coded for correctness rather than performance, and it could be optimized to make fewer calls to HTMLLabelElement::GetControl instead of calling it on every label in the element's tree; doing it this way was the most straightforward way to visibly match the spec and make sure everything came back in tree order with no false-positive labels.

I don't think it's worth a PR until the live list is working.

**Comment by pshaughn** [comment]
Working on liveness now. Here's the plan:
* HTMLInputElement is getting a MutNullableDom<NodeList>, because the spec requires that successive gets of .labels have to return the same node list.
* HTMLInputElement::GetLabels is using or_init on that NodeList.
* NodeList is getting a third case, for LabelsNodeList, which holds a Dom<HTMLElement> and live-accesses that element instead of holding any references to labels directly.
* HTMLElement is getting labels_vec, which returns Vec<DomRoot<Node>>.

Once I have this working for HTMLInputElement, I'll try to turn it into a macro so every labelable element can share the same labels-getting logic written in one place. HTMLElement::labels, which returns a static list, will be removed entirely once all the labelable elements have live lists.

**Comment by jdm** [comment]
A helper function (or possibly a struct that contains the new MutNullableDom) rather than a macro might be preferable, but that plan sounds sensible!
