### ISSUE TITLE
build error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable

### ISSUE THREAD

**Issue by kunalmohan** [servo/servo#25402]
`./mach build -d` (as well as `--release`) give the same error:
```
info: syncing channel updates for 'nightly-2019-12-23-x86_64-unknown-linux-gnu'
info: latest update on 2019-12-23, rust version 1.42.0-nightly (9b98af84c 2019-12-22)
error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly-2019-12-23
Build FAILED in 0:00:01
```
Environment- Ubuntu 19.04

**Comment by warren-fisher** [comment]
`info: syncing channel updates for 'nightly-2019-12-23-x86_64-unknown-linux-gnu'
info: latest update on 2019-12-23, rust version 1.42.0-nightly (9b98af84c 2019-12-22)
error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly-2019-12-23
Build FAILED in 0:00:00`

Same problem here on Kubuntu 19.10. Was previously able to build Servo ~2 weeks ago, not sure why it will not work anymore.

**Comment by jdm** [comment]
Use `rustup set profile minimal`.

**Comment by kunalmohan** [comment]
Yup, it's working now.
