### ISSUE TITLE
"If an element listed in a form element's past names map changes form owner, then its entries must be removed from that map."

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25429]
This requirement is placed in an easily missable location after the steps of https://html.spec.whatwg.org/multipage/forms.html#the-form-element:radionodelist-4 and doesn't even seem to have its own anchor to direct-link to. I think it can be satisfied by having each form-associated element's set_form_owner notify the old owner that it's leaving before changing to a new owner.

https://github.com/servo/servo/blob/2488213d18d5bc9806b41fb2756a2a82dbe933a4/components/script/dom/htmlinputelement.rs#L1688-L1690
This would first check if form_owner.get is_some and is different from form, and if so call something like form_owner.get().unwrap().remove_from_past_names_map(self), and likewise for every other element class with impl FormControls.

Another idea I had would be to just check, when getting from the map, if it's still owned, but that would be observably different in a case where it stopped being owned and then started being owned again.

**Comment by jdm** [comment]
Good catch!

**Comment by pshaughn** [comment]
The last test in html/semantics/forms/the-form-element/form-nameditem.html covers this thoroughly, associating, renaming, and disassociating elements in many ways; the first assert we fail on is when it uses .remove() on a renamed element and expects that to remove the past names map entry for its previous name.
