### ISSUE TITLE
Text input doesn't allow to delete characters if length is greater than maxlength

### ISSUE THREAD

**Issue by teapotd** [servo/servo#25420]
Servo doesn't allow to delete a character from text input that contains value longer than its maxlength. Other browsers allow it and some WPT tests depend on this behavior (e.g. `html/semantics/forms/constraints/tooLong-input-text-delete-manual.html`).

Example:
`./mach run -d 'data:text/html,<input value="123456" maxlength="3">'`
Try to use backspace in this field.

**Comment by jdm** [comment]
Looks like this case is explicitly called out in the code: https://github.com/servo/servo/blob/1e0f2e59b7fe5238e42b53099cc992ca6d2ec4d3/components/script/textinput.rs#L450-L457
We should definitely ignore any insertions that are beyond the max length, but I think we should be allowing deletions.

**Comment by teapotd** [comment]
@highfive assign me
