### ISSUE TITLE
Investigate failure of /html/semantics/scripting-1/the-script-element/module/error-type-1.html after module script landed

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#25436]
Before the IndexSet fix, we will get this failure intermittently. But, I can reproduce this failure consistently.

For merging #23545 first, marked it as FAIL in that PR and fix it separately.

```
1 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /html/semantics/scripting-1/the-script-element/module/error-type-1.html:
  │ FAIL [expected PASS] network error has higher priority than parse error
  │   → assert_equals: expected 3 but got 4
  │ 
  │ @http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/module/error-type-1.html:16:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:2025:32

```

_Originally posted by @Manishearth in https://github.com/servo/servo/pull/23545#issuecomment-571051685_

**Comment by Manishearth** [comment]
As far as I can tell the issue here is that we're triggering an onload event for a script that fails to load because of a broken dependency.

**Comment by Manishearth** [comment]
This might be due to how we use Promise.all to signal loads, even when there's a network failure?
