### ISSUE TITLE
Detached radio buttons do not propagate their checkedness

### ISSUE THREAD

**Issue by teapotd** [servo/servo#25486]
Radio buttons in subtrees detached from document do not synchronize their checkedness. Consider this example:

```html
<script>
let form = document.createElement("form");
let radios = [];

for (let i = 0; i < 3; i++) {
    let elem = document.createElement("input");
    elem.type = "radio";
    elem.name = "my_group";
    form.appendChild(elem);
    radios.push(elem);
}

for (let elem of radios) {
    elem.checked = true;
}

for (let elem of radios) {
    document.write(elem.checked + " ");
}
</script>
```

Expected result is `false false true`, Servo outputs `true true true`.

**Comment by pshaughn** [comment]
Sounds like another data point for #21495

**Comment by teapotd** [comment]
Looks like it's enough to use `GetRootNode` instead of document here:

https://github.com/servo/servo/blob/fdfc840baca427f58daaa251100c3940256e86c5/components/script/dom/htmlinputelement.rs#L891-L914

**Comment by teapotd** [comment]
@highfive assign me
