### ISSUE TITLE
In  AsyncWGPUListener, reject promise with OperationError

### ISSUE THREAD

**Issue by gterzian** [servo/servo#25492]
https://github.com/servo/servo/blob/3740754563bf9304400ccc0599e736be108a7fe5/components/script/dom/gpu.rs#L59

It looks to me like the spec always wants an `Error::OperationError` to be used, see for example https://gpuweb.github.io/gpuweb/#requestadapter

@zakorgy

**Comment by atouchet** [comment]
Did #25030 fix this?

**Comment by jdm** [comment]
Yes.
