### ISSUE TITLE
datetime-local value sanitization removes leading zeroes for seconds

### ISSUE THREAD

**Issue by teapotd** [servo/servo#25493]
```
<input type="datetime-local" value="2000-01-01T12:30:00.5">
<input type="datetime-local" value="2000-01-01T12:30:01">
<script>
    let result = '';
    for (let elem of document.querySelectorAll("input")) {
        result += elem.valueAsNumber + ' ' + elem.value + '\n';
    }
    alert(result);
</script>
```

In the above example the leading zeroes for seconds are removed during sanitization, but they are required in valid datetime-local strings. This makes valueAsNumber fail, for example.

https://html.spec.whatwg.org/multipage/#valid-normalised-local-date-and-time-string
https://html.spec.whatwg.org/multipage/#valid-time-string

https://github.com/servo/servo/blob/63cb13f5fa5f52d3574eb0da883f881b52e208ff/components/script/dom/bindings/str.rs#L469-L484

**Comment by pshaughn** [comment]
Yes, the last field there should also have {:02}, sorry I didn't catch this when I was otherwise tweaking the time string code.

**Comment by pshaughn** [comment]
I also see a second problem here: it's dropping milliseconds entirely when it should preserve them.

**Comment by pshaughn** [comment]
which is probably just {:02.*} but needs tests written for the various possible lengths

**Comment by pshaughn** [comment]
{:02} is still wrong when there are millis; I've written a test to flex the various cases and I think I can pass them all by adding a branch for 0.0<second<10.0 that adds one leading zero
