### ISSUE TITLE
Event handlers compiled from inline attributes aren't seeing properties of their current target as variables

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25517]
After #25488, the first subtest in html/webappapis/scripting/events/compile-event-handler-lexical-scopes.html does what it's supposed to do far enough to find an actual problem. A more minimal case to focus on the one problem is:

```
    <div id="log"></div>
    <input value="4" onclick="document.getElementById('log').innerText+=value">
    <script>
      document.querySelector("input").click()
    </script>
```

In Firefox, this puts 4 in the div. In Servo, this logs nothing and reports an exception that value is not defined.

I need to look at specifications more to figure out what mechanism should be exposing the properties in this way and what part of it Servo is missing; prior to this test, I was unaware this behavior existed at all.

**Comment by jdm** [comment]
It's not about exposing properties; it's that the `this` value when dispatching the event should be the HTMLInputElement, so a bareword lookup of `value` should be equivalent to `element['value']`.

**Comment by pshaughn** [comment]
That's not what `this` does in a normal function call. For example:
```
<script>
      x={a:5, b: function() { console.log(this); console.log(this.a); console.log(a); } }
      x.b();
</script>
```
In firefox this logs the object, then logs 5 once, then reports an exception that `a` is undefined.

**Comment by pshaughn** [comment]
Also, the `this` is being defined (at least on my branch for #25488); if I change my first snippet to innertext+=this, I get [object HTMLInputElement] to appear.

**Comment by pshaughn** [comment]
This is a special behavior of inline handlers defined in on* attributes, and it happens when they are compiled, as specified under "Scope" in step 3.9 of https://html.spec.whatwg.org/#internal-raw-uncompiled-handler .

**Comment by pshaughn** [comment]
https://github.com/servo/servo/blob/b52ddc52906780c3ab530446de9688729a9ee9f3/components/script/dom/eventtarget.rs#L504-L507
This is the missing piece; step numbers have changed, but looking for a scope in the document, form owner, and element is what 3.9 of https://html.spec.whatwg.org/#internal-raw-uncompiled-handler is saying to do.
Someone with more Spidermonkey knowledge than I have might want to jump in here.

**Comment by pshaughn** [comment]
It looks like we need to turn the document, the form owner if it exists, and the target if it's an element into `*mut JSObject`, and pass them into `scopechain.append`. Getting those JSObject pointers is already implemented for LayoutDom, but as this is not happening during layout, I don't know what safety considerations exist here, and there is very obviously aliasing involved since we are also continuing to use the target.

**Comment by jdm** [comment]
We can get the JSObject pointer for any DOM object by calling `dom_object.reflector().get_jsobject().get()` on it. It should be straightforward to get the scope chain correct if we only need to append them to that vector.

**Comment by pshaughn** [comment]
Ok, I'll try it!

**Comment by pshaughn** [comment]
https://github.com/pshaughn/servo/tree/compiledeventscope fixes this, but won't pass any of the existing tests until #25488 lands because the existing tests also involve capture/bubble behavior. Pushing a new test just for this would be redundant since the larger tests are already covering it thoroughly. Is this the kind of thing that the _mozilla tests are for?

**Comment by jdm** [comment]
Yep! Those don't get upstreamed by default, so they cover browser-specific behaviour or non-standard extensions.
