### ISSUE TITLE
Fix and disallow all snake_case style warnings

### ISSUE THREAD

**Issue by jdm** [servo/servo#25531]
https://github.com/servo/servo/blame/5c7a4db5f4e374dee287d403d90c7bc0e07ac9d0/components/script/lib.rs#L12 was added several years ago. We should remove it and fix the existing violations that have been added to the code in that time.

**Comment by kunalmohan** [comment]
@highfive: assign me

**Comment by kunalmohan** [comment]
How should I translate camelCase methods (of webidl) to snake_case? I found `js_name` attribute in `wasm-bindgen` (`#[wasm_bindgen(js_name = jsOftenUsesCamelCase)]`). Is there some other way, maybe specific to servo that I am missing out?

**Comment by pshaughn** [comment]
That must be why ignore_snake_case was on in the first place. Maybe we want just the autogenerated method names from the webidl to be exempt from this, somehow?

**Comment by jdm** [comment]
Yes, we can apply that attribute to specific modules or trait implementations when necessary, I suppose. We can start by making use of the `ignored_warnings` argument to `CGImports` in CodegenRust.py - try adding it to the list in https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py#L1958, and then for any generated files still causing trouble look for uses like https://github.com/servo/servo/blob/90b0a7fcc5f8c94e176c817cad75d40a82b4388a/components/script/dom/bindings/codegen/CodegenRust.py#L2465 and add it if necessary.

**Comment by kunalmohan** [comment]
Adding `'non_snake_case'` to the list 
https://github.com/servo/servo/blob/1de92906e8205e5e46ae947378dd916905fbbf7f/components/script/dom/bindings/codegen/CodegenRust.py#L1958-L1965
doesn't seem to reduce any warnings.
Adding it to 
https://github.com/servo/servo/blob/1de92906e8205e5e46ae947378dd916905fbbf7f/components/script/dom/bindings/codegen/CodegenRust.py#L2473
and
https://github.com/servo/servo/blob/1de92906e8205e5e46ae947378dd916905fbbf7f/components/script/dom/bindings/codegen/CodegenRust.py#L7564

gave the respective errors-
```
error: an inner attribute is not permitted in this context
 --> /mnt/sda1/Documents/webpages/rust/servo/target/debug/build/script-34e34b4c91111f3b/out/RegisterBindings.rs:1:1
  |
1 | #![allow(non_snake_case)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.

error: an inner attribute is not permitted in this context
 --> /mnt/sda1/Documents/webpages/rust/servo/target/debug/build/script-34e34b4c91111f3b/out/UnionTypes.rs:3:1
  |
3 | #![allow(non_snake_case)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.
```

**Comment by jdm** [comment]
Can you give a few examples of some of the warnings?

**Comment by jdm** [comment]
One other possibility is changing [this line](https://github.com/servo/servo/blob/1de92906e8205e5e46ae947378dd916905fbbf7f/components/script/dom/bindings/codegen/CodegenRust.py#L6344) to `self.cgRoot = CGList(CGGeneric('#![allow(non_snake_case)]'), cgThings)`

**Comment by kunalmohan** [comment]
```
warning: method `Constructor` should have a snake case name
  --> components/script/dom/audiobuffer.rs:93:12
   |
93 |     pub fn Constructor(
   |            ^^^^^^^^^^^ help: convert the identifier to snake case (notice the capitalization): `constructor`
```
```
warning: variable `txPower` should have a snake case name
  --> components/script/dom/bluetoothadvertisingevent.rs:59:9
   |
59 |         txPower: Option<i8>,
   |         ^^^^^^^ help: convert the identifier to snake case: `tx_power`
```

**Comment by pshaughn** [comment]
txPower actually should have a snake case name, and tx_power is the correct suggestion, if I understand Servo's style correctly. Constructor's a word the codegen is putting in a trait, so it should probably be exempt?

**Comment by kunalmohan** [comment]
Yes, I think so too. There are a large number of variables and functions that come under the warnings. I guess most of the variables` names need to be changed whereas the functions are put in by the codegen and should be exempt.

**Comment by jdm** [comment]
I can't figure out where the actual `Constructor` name comes from in the code generator, so go ahead and add `#[allow(non_snake_case)]` for each instance.

**Comment by kunalmohan** [comment]
> One other possibility is changing [this line](https://github.com/servo/servo/blob/1de92906e8205e5e46ae947378dd916905fbbf7f/components/script/dom/bindings/codegen/CodegenRust.py#L6344) to `self.cgRoot = CGList(CGGeneric('#![allow(non_snake_case)]'), cgThings)`

This isn't working: python `TypeError` (I guess, because of the if block which changes cgThings type)
https://github.com/servo/servo/blob/1de92906e8205e5e46ae947378dd916905fbbf7f/components/script/dom/bindings/codegen/CodegenRust.py#L6335-L6344

So I tried 
```
if reexports:
            reexports = ', '.join(map(lambda name: reexportedName(name), reexports))
            cgThings = CGList([CGGeneric('#![allow(non_snake_case)]'), CGGeneric('pub use self::%s::{%s};' % (toBindingNamespace(descriptor.name), reexports)),
                               cgThings], '\n')
        else:
            cgThings = CGList([CGGeneric('#![allow(non_snake_case)]'), cgThings], '\n')

        self.cgRoot = cgThings
```
which again gave the error `error: an inner attribute is not permitted in this context`

**Comment by kunalmohan** [comment]
> I can't figure out where the actual `Constructor` name comes from in the code generator, so go ahead and add `#[allow(non_snake_case)]` for each instance.

Only for the constructors? (because there are hundreds of warnings, constructors alone are more than hundred I guess :sweat_smile: )

**Comment by jdm** [comment]
For non-constructor methods of traits, you can probably add `#[allow(non_snake_case)]` right before the `impl FooMethods for Foo` to avoid lots of those warnings.
