### ISSUE TITLE
Intermittent error in /fetch/origin/assorted.window.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#25542]
```
  ▶ ERROR [expected TIMEOUT] /fetch/origin/assorted.window.html
  │   → doc is null
  │ 
  └ frame.onload@http://web-platform.test:8000/fetch/origin/assorted.window.js:63:20
```

**Comment by jdm** [comment]
Given https://github.com/web-platform-tests/wpt/blob/606da537b95e54f4f1d53774ec03634f5902bc01/fetch/origin/assorted.window.js#L62-L63 it's interesting that contentDocument is returning null in an onload handler. This should be an about:blank frame, so it's hard to imagine why this would be happening.

**Comment by pshaughn** [comment]
Was this on Linux at the same time we were getting a lot of unable to allocate memory errors? Something similar hit me around that time; possibly we're not panicking properly when a malloc fails for a document.
