### ISSUE TITLE
Root element background extents are wrong in layout_2020

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#25559]
It looks like root element background extents aren't including page margins and don't cover the page viewport.

This shows a white page:
```
<body style="background: green;"></body>
```

This shows a green page with 8 pixel white borders on the top and right:
```
<body style="background: green;">
    <div style="height: 10000px;"></div>
</body>
```

This shows a completely green page. This is what I would expect for all test cases:
```
<body style="background: green;">
    <div style="height: 10000px;"></div>
</body>
```

**Comment by SimonSapin** [comment]
The relevant spec is:

* https://drafts.csswg.org/css-backgrounds/#special-backgrounds
* https://drafts.csswg.org/css2/zindex.html

This affects the *border painting area* and painting order (position in the display list) of background layers for the root element (or in some cases HTML `<body>` element).

The painting area (mistakenly called `clipping_area` in current master) needs to be theoretically infinite, although in practice only the part that intersects with the scrollable overflow rectangle for the document can be painted.
