### ISSUE TITLE
Avoid enqueuing tree mutation record when there is no mutation

### ISSUE THREAD

**Issue by jdm** [servo/servo#25579]
https://github.com/whatwg/dom/pull/822

**Comment by tipowol** [comment]
I investigated this issue and it looks like it's already implemented:
https://github.com/servo/servo/blob/e23fbd25e65397a8f53812085edb5538f2d1ff44/components/script/dom/node.rs#L2110-L2118.

**Comment by jdm** [comment]
Agreed. Thanks for investigating!
