### ISSUE TITLE
Add PerformanceObserver.supportedEntryTypes

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25587]
https://w3c.github.io/performance-timeline/#supportedentrytypes-attribute Semantics of what it returns are simple, but it needs to be `[SameObject] static readonly attribute FrozenArray<DOMString>` which is a lot of adjectives.

**Comment by pshaughn** [comment]
FrozenArray (#10072) is the one part of this we don't seem to have; some other code is returning "any" as a workaround.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/dbba9ea453c5cb235f55b2ccaa87782b6c22a5cb/components/script/dom/bindings/utils.rs#L126-L134
