### ISSUE TITLE
Rename compartment-related terminology to use realms instead

### ISSUE THREAD

**Issue by jdm** [servo/servo#25581]
This is specifically about `components/script/compartments.rs` and names like AlreadyInCompartment. Everywhere we use the name compartment, we should use the name realm instead.

**Comment by kunalmohan** [comment]
@highfive: assign me

**Comment by kunalmohan** [comment]
@jdm should https://github.com/servo/servo/blob/d0d3aaa449d3569292ab1311a69f5162ec956412/components/config/prefs.rs#L380
be renamed too?

**Comment by jdm** [comment]
It turns out that preference can be removed; we don't actually use it anywhere in servo.

**Comment by kunalmohan** [comment]
Can you explain (or provide a resource) what role preference values play and why don't we need it anymore? I don't have any idea what it means here at this point :sweat_smile: . I see that it is being enabled here
https://github.com/servo/servo/blob/592649ba503bf79fe251cbd539f7eabd7d79135d/resources/prefs.json#L65

And in the above comment, we are talking about removing just the 'per_compartment', right?

**Comment by kunalmohan** [comment]
Ok, I think I get it. prefs.json sets the values for various limits and functionalities that servo should follow/use by default, right? (I think I have put it in a very vague manner)

**Comment by jdm** [comment]
There are no uses of `pref!(js.mem.gc.per_compartment.enabled)` in the rest of the servo code. There is a use of `pref!(js.mem.gc.per_zone.enabled)`, so I think this is just a preference that used to be valid in an older version of spidermonkey, then spidermonkey switch to per-zone garbage collection and we added a new preference for it instead of renaming the existing one.

**Comment by jdm** [comment]
And yes, the values in prefs.json are read during Servo's startup and used for configurable values in Servo's code.

**Comment by kunalmohan** [comment]
Ok. I have renamed the variables, functions, structs, etc. in `compartments.rs` and any other local variables in other files. I have removed the preference and renamed `compartment.rs` to `realm.rs`.
I found `inCompartment` descriptors in `codegen/Bindings.conf` I guess those are to be renamed too.

**Comment by jdm** [comment]
Yes please! That will require changing https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py#L3400-L3401 and https://github.com/servo/servo/blob/be409233fdf8d3578e0529ec150a3697788ba4c8/components/script/dom/bindings/codegen/Configuration.py#L223 as well.

**Comment by kunalmohan** [comment]
Yes I did that. Now the only references remaining are
![abcd](https://user-images.githubusercontent.com/44079328/73072069-4e8ede80-3eda-11ea-8aa0-848bfd5c56aa.png)
I don't think anything can be done about the first one (except renaming the imports).
I'm not sure about the others.

**Comment by jdm** [comment]
Agreed. All of those need to stay.
