### ISSUE TITLE
spirv_cross dependency broke

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25591]
https://community-tc.services.mozilla.com/tasks/F6OopgoXRricCa5Qg0rbNw/runs/1/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FF6OopgoXRricCa5Qg0rbNw%2Fruns%2F1%2Fartifacts%2Fpublic%2Flogs%2Flive.log

https://github.com/kvark/spirv_cross/tree/wgpu has been force-pushed, removing the commit we were using

**Comment by SimonSapin** [comment]
@kvark Do you still have https://github.com/kvark/spirv_cross/commit/636677bad724797789239c16e6d332e9b4d97b86 in a local tree? Could you push it to some other branch?

**Comment by kvark** [comment]
@SimonSapin my apologies! Restored the original commit in "wgpu-servo" branch - https://github.com/kvark/spirv_cross/tree/wgpu-servo

**Comment by pshaughn** [comment]
I don't think that has the same commit. https://github.com/kvark/spirv_cross/commit/636677bad724797789239c16e6d332e9b4d97b86 is the one we had locked.

**Comment by kvark** [comment]
@pshaughn indeed, eeks, fixed now

**Comment by pshaughn** [comment]
Fixed in #25592
