### ISSUE TITLE
WPT cookies/http-state tests that use Location: time out

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25604]
cookies/http-state/path-tests.html and cookies/http-state/domain-tests.html each test a list of cases (found in cookies/http-state/resources/test-files). They time out when they hit cases that use `Location:`. cookies/http-state/ordering-tests.html has just one case and does likewise.

**Comment by pshaughn** [comment]
I should mention that I haven't done a fine-toothed combing of every test case one at a time. The Location: header is the obvious thing that stood out to me about which cases were timing out, but there may be other problems, and it may be that only some Location: headers are a problem.

**Comment by pshaughn** [comment]
This is different from #25605: Servo logs receiving the response, including the Location header, and the failure happens somewhere later than that. The response is supposed to be populating an iframe which then sends a message event, and that probably isn't happening.

**Comment by pshaughn** [comment]
I tried adding a console.log to the template that cookie-setter.py uses to make the response; it gets called on the tests that work, and it doesn't get called on the ones that don't, so seeing the Location header is somehow stopping us from making the iframe work at all, not just e.g. making it work but as dissimilar-origin.

**Comment by jdm** [comment]
This was fixed by #26475.
