### ISSUE TITLE
WindowsError: [Error 5] Access is denied , this is displayed while building rust

### ISSUE THREAD

**Issue by shreyarastogi** [servo/servo#25621]
C:\Users\shrey\servo>.\mach build --dev
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.19
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Installing missing MSVC dependencies...
Resuming download of https://servo-deps.s3.amazonaws.com/msvc-deps/cmake-3.14.3.zip ...
Downloading cmake-3.14.3: 100.0%
Extracting cmake-3.14.3...done
Error running mach:

    ['build', '--dev']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

WindowsError: [Error 5] Access is denied

  File "C:\Users\shrey\servo\python\servo\build_commands.py", line 241, in build
    self.ensure_bootstrapped(target=target)
  File "C:\Users\shrey\servo\python\servo\command_base.py", line 1006, in ensure_bootstrapped
    Registrar.dispatch("bootstrap", context=self.context)
  File "C:\Users\shrey\servo\python\_virtualenv2.7\Lib\site-packages\mach\registrar.py", line 152, in dispatch
    return self._run_command_handler(handler, context=context, **kwargs)
  File "C:\Users\shrey\servo\python\_virtualenv2.7\Lib\site-packages\mach\registrar.py", line 109, in _run_command_handler
    result = fn(**kwargs)
  File "C:\Users\shrey\servo\python\servo\bootstrap_commands.py", line 47, in bootstrap
    return bootstrap.bootstrap(self.context, force=force)
  File "C:\Users\shrey\servo\python\servo\bootstrap.py", line 413, in bootstrap
    return bootstrapper(context, force=force)
  File "C:\Users\shrey\servo\python\servo\bootstrap.py", line 335, in windows_msvc
    os.rename(extracted_path, package_dir(package))

Getting this error when I build servo in windows. Installed both python 2 and 3 and other required packages.  Ran setting both python 2 and 3 as default , still it gives the same error.
What should I do?

**Comment by jdm** [comment]
What is the output of `dir /q .servo\msvc-dependencies`? The error being reported looks like a permission error when python tries to rename a directory like `.servo\msvc-dependencies\cmake-3.14.3` to `.servo\msvc-dependencies\cmake\3.14.3`, and it's surprising that it's having difficulties with that.

**Comment by jdm** [comment]
One way to get a bit more information about the paths that are triggering the issue is to add `print(extracted_path, package_dir(package))` before https://github.com/servo/servo/blob/da31405785be7af8f652205fe03cdc431280834f/python/servo/bootstrap.py#L335.

**Comment by shreyarastogi** [comment]
C:\Users\shrey\servo>dir /q .servo\msvc-dependencies
 Volume in drive C is Windows
 Volume Serial Number is 0499-3707

 Directory of C:\Users\shrey\servo\.servo\msvc-dependencies

27-01-2020  00:07    <DIR>          LAPTOP-L08HN83K\shrey  .
27-01-2020  00:07    <DIR>          LAPTOP-L08HN83K\shrey  ..
27-01-2020  00:07    <DIR>          LAPTOP-L08HN83K\shrey  3.14.3
28-01-2020  14:36    <DIR>          LAPTOP-L08HN83K\shrey  cmake
27-01-2020  00:07    <DIR>          LAPTOP-L08HN83K\shrey  cmake-3.14.3
27-01-2020  00:02    <DIR>          LAPTOP-L08HN83K\shrey  llvm
               0 File(s)              0 bytes
               6 Dir(s)  39,603,527,680 bytes free

This is the output that I am getting.

**Comment by shreyarastogi** [comment]
C:\Users\shrey\servo>print(extracted_path, package_dir(package)) .\mach build --dev
Unable to initialize device PRN
??

**Comment by shreyarastogi** [comment]
I managed to build servo:) 
Did It by uninstalling and reinstalling Visual Studio. Included some other modules while reinstalling it, that might have done it.

**Comment by jdm** [comment]
Sorry it was such a mystery!

**Comment by shreyarastogi** [comment]
It's alright, I'm just glad it got built:)
