### ISSUE TITLE
three.js examples don't render in immersive webxr (macOS)

### ISSUE THREAD

**Issue by jdm** [servo/servo#25638]
https://manishearth.github.io/webxr-three/examples/webvr_ballshooter.html works fine in a nightly build from 1/28 and doesn't work in a nightly build from 1/29.

**Comment by jdm** [comment]
I am specifically trying this on macOS by loading the URL and pressing the "enter webxr" button that appears after the balls start appearing.

**Comment by jdm** [comment]
Reproduced the problem in da31405785.

**Comment by Manishearth** [comment]
Could the issue from https://github.com/servo/servo/issues/25643 also be responsible? If so, the updated webpage should Just Work now.

**Comment by jdm** [comment]
Yep, the webpage works now.
