### ISSUE TITLE
Intermittent FAIL in /css/css-backgrounds/border-top-right-radius-005.xht

### ISSUE THREAD

**Issue by gterzian** [servo/servo#25632]
```
 ▶ FAIL [expected PASS] /css/css-backgrounds/border-top-right-radius-005.xht
  │   → /css/css-backgrounds/border-top-right-radius-005.xht 54a9df64f1476dd12020019d7cf22ac34d727bc0
  │   → /css/css-backgrounds/border-top-right-radius-005-ref.xht 23e62b1830030c9b3ab32beb3660ae487c02e7e5
  └   → Screenshot is solid color 0xFFFFFF for /css/css-backgrounds/border-top-right-radius-005.xht
```

https://community-tc.services.mozilla.com/tasks/SJ_1RKYGRNGEz3jjKn3-Jw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FSJ_1RKYGRNGEz3jjKn3-Jw%2Fruns%2F0%2Fartifacts%2Fpublic%2Ffiltered-wpt-errorsummary.log

**Comment by SimonSapin** [comment]
> Screenshot is solid color 0xFFFFFF

This suggests https://github.com/servo/servo/issues/24726 rather than anything specific to this test.

**Comment by gterzian** [comment]
thanks for pointing it out.
