### ISSUE TITLE
Allow embedders to provide user agent string

### ISSUE THREAD

**Issue by jdm** [servo/servo#25646]
It should be up to the embedder to decide what user agent to report in network requests, rather than deep in the engine in https://github.com/servo/servo/blob/8e0d037ee82da747fa9c13234d5c3677f930e690/components/config/opts.rs#L480 (and #25372 would have exacerbated this). We should add a method to the EmbedderMethods trait that returns the default user agent string, so that we can pass that to [the new network thread](https://github.com/servo/servo/blob/8e0d037ee82da747fa9c13234d5c3677f930e690/components/servo/lib.rs#L861) when we're [creating an instance of Servo](https://github.com/servo/servo/blob/8e0d037ee82da747fa9c13234d5c3677f930e690/components/servo/lib.rs#L324).

**Comment by medimatrix** [comment]
@highfive: assign me

**Comment by utsavoza** [comment]
@jdm @medimatrix Is it possible for me to take up this issue if we are not making progress currently?

**Comment by jdm** [comment]
@utsavoza If you would like to continue the work from #25672, that would be great!

**Comment by utsavoza** [comment]
Sure. I have made some changes taking into account both the reviews and changes in #25672. I can raise a PR for the issue, if that's Ok!

**Comment by jdm** [comment]
Please do!
