### ISSUE TITLE
Make background hang monitor optional

### ISSUE THREAD

**Issue by jdm** [servo/servo#25647]
In performance-sensitive situations like immersive mode on the hololens, having the background hang monitor thread running shows up in profiles. We should make it a configuration option at engine startup, and put the channels to communicate with the thread inside Option values so we don't have unnecessary channel traffic.

**Comment by gterzian** [comment]
One way, perhaps the easiest, to do this, would:

1. Set a flag using `servo_config`. 
2. In the BHM:

Here: https://github.com/servo/servo/blob/7ac4f9eec6c5208865c435505437df0f569a278a/components/background_hang_monitor/background_hang_monitor.rs#L26

You could read the flag, and if we don't want to actually start a worker:
1. Don't start one, 
2. return an implementation of `BackgroundHangMonitorRegister` that basically does nothing, where `register` would itself return an implementation of `BackgroundHangMonitor` that would also do nothing.

**Comment by CYBAI** [comment]
Maybe we can use the `features` of `cargo` and init the hang monitor like this 👀? 

https://github.com/servo/servo/blob/7ac4f9eec6c5208865c435505437df0f569a278a/components/servo/lib.rs#L58-L64

**Comment by gterzian** [comment]
Yes that could be a good idea, how would that work exactly with the BHM being a sub-crate and with the workspace setup of the repo as a whole? I'm looking around online and if you already know how it would be done, please describe it here!

**Comment by CYBAI** [comment]
@gterzian I'm not familiar with how BHM works but I imagine maybe we can do it like

For example, for the following piece of code, we will initiate the BHM if the feature is specified.

```rust
let (background_monitor_register, sampler_chan) = if cfg!(feature = "background_hang_monitor") {
    let (sampling_profiler_control, sampling_profiler_port) =
        ipc::channel().expect("ipc channel failure");

    (
        Some(HangMonitorRegister::init(
            background_hang_monitor_sender.clone(),
            sampling_profiler_port,
        )),
        vec![sampling_profiler_control],
    )
} else {
    (None, vec![])
};
```

https://github.com/servo/servo/blob/393b6768f05741717cfbaf4d077f91a73a6e3c05/components/constellation/constellation.rs#L846-L862

Maybe @jdm will have better plan though, WDYT 👀?

**Comment by CYBAI** [comment]
☝️  In this solution, I mean, if we don't specify `--features="background_hang_monitor`, then we don't start a BHM so that we might be able to avoid using it when we want?

**Comment by gterzian** [comment]
Looks like a good idea. I think what I proposed with different implementations is actually too complicated.

**Comment by jdm** [comment]
As a developer, it would be ideal if this were a runtime rather than compile-time choice. My preference would be using Options around channel's like we do with the devtools server.

**Comment by kunalmohan** [comment]
@jdm could you point out the devtools server implementation that you referred above. It would be helpful if I take a look at it first.

**Comment by jdm** [comment]
[This](https://github.com/servo/servo/blob/master/components/servo/lib.rs#L361-L363) is where the devtools server is started, and the channel to communicate with it is stored in an Option. Similarly [this](https://github.com/servo/servo/blob/7786464dad72a221e162ac56a7dba8b0223115ee/components/script/script_thread.rs#L600-L601) is client code that will communicate with the devtools server if it exists.

**Comment by kunalmohan** [comment]
If I wrap the value in background_hang_monitor_receiver inside Option, how do I handle it inside select macro?
https://github.com/servo/servo/blob/87d28b97c623abb1ec10280b06830b05c19190dc/components/constellation/constellation.rs#L1416-L1418

**Comment by gterzian** [comment]
I think the example "Optionally add a receive operation to select! using never" could be useful for this, see https://docs.rs/crossbeam-channel/0.4.0/crossbeam_channel/macro.select.html
