### ISSUE TITLE
ignore_malloc_size_of for DomRefCell<TextInput<...>> cites closed issue #7193

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25679]
https://github.com/servo/servo/blob/5f55cd5d71df9c555fbc24777168396ddd539f28/components/script/dom/htmltextareaelement.rs#L49-L50
https://github.com/servo/servo/blob/5f55cd5d71df9c555fbc24777168396ddd539f28/components/script/dom/htmlinputelement.rs#L247-L248

We actually do need an ignore_malloc_size_of either here or in TextInput, since `TextInput<T>` holds a `T` and the `T` here itself holds an IPCSender. There's just room for a little cleanup to remove a reference to #7193, a closed and only half-relevant issue.

**Comment by wulanseruniati** [comment]
Hi! I noticed that the #[ignore_malloc_size_of = "#7193"] attribute in htmltextareaelement.rs and htmlinputelement.rs refers to a closed issue (#7193) and seems no longer relevant. I’d like to clean this up by removing the outdated reference.
