### ISSUE TITLE
multi-meaning words that  should NOT exclude all results from strict search but do

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [servo/servo#25676]
If I search "ass" with adult filter set to strict or moderate, I should get tons of results for the animal that sires mules. Instead I get nothing. If I set it to off, I get 10 thousand pictures that are all very interesting but if the donkeys are there at all, they are way down in the kinky stuff on page 91. On the strict, I can enter an associated word like this "horse ass" but I get more links to etymology sites than anything. Come on, guys I should be able to search for ass without getting creative.

**Comment by CYBAI** [comment]
You might want to find other services instead of Servo here 🤔 so I closed it.
