### ISSUE TITLE
UWP: Unable to activate Windows Store App

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#25683]
For some reasons, I can’t get to start the UWP app in the emulator or on desktop:

![IMG_0004](https://user-images.githubusercontent.com/373579/73724922-587cd100-4767-11ea-85d5-5affeb218116.jpeg)

**Comment by paulrouget** [comment]
```
The program '[10584] ServoApp.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found
```

**Comment by paulrouget** [comment]
Bisected: https://github.com/servo/servo/pull/25509

**Comment by paulrouget** [comment]
The new Angle libraries are linked with this *extra* DLL: `VCRUNTIME140_1_APP.dll`. It’s still linked to `VCRUNTIME140_APP.dll`.

@jdm can you double check the angle 2.1.18 package?

**Comment by jdm** [comment]
@paulrouget It may have been caused by building with MSVC 2019. Let's revert #25509 to unbreak everybody.

**Comment by asajeffrey** [comment]
I can confirm that reverting #25509 fixes this link error.
