### ISSUE TITLE
Add "same-origin" referrer policy in Request.webidl

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25680]
https://fetch.spec.whatwg.org/#concept-request-referrer-policy points at https://w3c.github.io/webappsec-referrer-policy/#referrer-policy which we don't quite match the IDL for. Methods in request.rs are currently conflating "origin" and "same-origin" together in `Into<ReferrerPolicy> for MsgReferrerPolicy`.

A nearby comment mentions whatwg/fetch#346, which ended up closed without merging; that comment should get taken out when fixing this.

**Comment by tipowol** [comment]
@highfive assign me

**Comment by jdm** [comment]
It will be useful to run `./mach test-wpt tests/wpt/web-platform-tests/fetch/api` after fixing this.
