### ISSUE TITLE
Mac build doesn’t run: set_sigalgs_list fails 

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#25708]
Fails with:

```
could not set signature algorithms: ErrorStack([]) (thread ResourceManager, at components/net/connector.rs:97)     
```

MacOS 10.15.2

**Comment by Darkspirit** [comment]
Can this be fixed by installing fresh build dependencies?
OpenSSL 1.1.1 is required and also introduced TLS 1.3 support.
https://github.com/servo/servo#macos (https://formulae.brew.sh/formula/openssl@1.1)

**Comment by Darkspirit** [comment]
#25619 revealed that #24976 also deprecated crufty old unsupported OpenSSL versions. Linux and [Windows](https://github.com/servo/servo/blob/425328a64f37a795ce36516e495c386be27a6100/python/servo/packages.py#L11) have been using 1.1.1 already before. [MacOS](https://github.com/servo/servo/blob/c67b3d71e23f10ba2049bdd9aed822b19ed8527f/etc/taskcluster/macos/Brewfile#L10) switched to [OpenSSL 1.1.1](https://formulae.brew.sh/formula/openssl@1.1) at the end of [November 2019](https://brew.sh/2019/11/27/homebrew-2.2.0/). Reinstalling MacOS build dependencies should update your OpenSSL.

**Comment by paulrouget** [comment]
@Darkspirit, thanks for look a this:

```
brew bundle install --file=etc/taskcluster/macos/Brewfile
brew bundle install --file=etc/taskcluster/macos/Brewfile-build
./mach clean
./mach build -r
```

Does not appear to solve the problem.

**Comment by Darkspirit** [comment]
Hm. I'm not sure if packages would be upgraded this way. Would [`brew update && brew upgrade`](https://devhints.io/homebrew) help?

**Comment by paulrouget** [comment]
It was properly upgraded. The problem was that both openssl 1.0 and openssl 1.1 were installed by brew.

Uninstalling openssl 1.0 and rebuilding servo…

**Comment by paulrouget** [comment]
It worked.

I had to link `/usr/local/opt/openssl@1.1` to `/usr/local/opt/openssl` and rebuild.

**Comment by jdm** [comment]
We should add some kind of build-time check that verifies that an appropriate minimum version of openssl has been found.

**Comment by paulrouget** [comment]
@jdm do you think this should happen in our python script or in whatever crate that end up using the openssl library (which one is it btw?)

**Comment by Darkspirit** [comment]
https://docs.rs/openssl/0.10.28/openssl/version/fn.number.html
openssl::version::number() > 0x010101000

**Comment by jdm** [comment]
I think having the check in a build script for the net crate will be straightforward and reliable.

**Comment by Darkspirit** [comment]
Ok, done. Now I'll look if I can help with Android.
