### ISSUE TITLE
WebIDL codegen doesn't like ElementInternals's use of non-optional ValidityStateFlags dictionary

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25704]
https://github.com/servo/servo/blob/5ef30c67334739c52fd3e82c21ff39e058a16fe5/components/script/dom/bindings/codegen/parser/WebIDL.py#L5197-L5207

This throws an error on this construct from from https://html.spec.whatwg.org/multipage/custom-elements.html#elementinternals :
```
  void setValidity(ValidityStateFlags flags,
                   optional DOMString message,
                   optional HTMLElement anchor);
```

https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/html/custom/element_internals.idl has the same construct, and my shallow skimming of likely parts of the WebIDL specification doesn't indicate anything about this optionals-after-required-dictionary constraint.

**Comment by pshaughn** [comment]
This requirement probably comes into play because of overload resolution rules, but if that's the reason then it shouldn't happen for a name that's only being defined once.

**Comment by CYBAI** [comment]
Per spec-update in whatwg/html#5509, I think this might not be an issue anymore 👀?

**Comment by jdm** [comment]
Good memory; I agree!
