### ISSUE TITLE
Mutating the tabindex content attribute isn't changing focusability

### ISSUE THREAD

**Issue by pshaughn** [servo/servo#25713]
I'm not sure whether there's a specific test for adding tabindex, but html/interaction/focus/processing-model/focus-fixup-rule-one-no-dialogs.html case "Removing the tabindex attribute from a div" tests removing it and fails. 

Servo only checks for tabindex in HTMLElement::update_sequentially_focusable_status, which is only called from HTMLElement::bind_to_tree, so any changes to the attribute on an already-inserted node will have no effect on focusability (unless the node happens to also get inserted into a tree again).

**Comment by jdm** [comment]
This was fixed by #26902.
