### ISSUE TITLE
WebGPU IdentityHub could create the same ID when we have multiple threads

### ISSUE THREAD

**Issue by imiklos** [servo/servo#25725]
When we create an ID, we could have multiple threads that end up creating the same ID independently. Possible we need to share a single `gpu_id_hub` between all threads using `Arc` & `Mutex`

**Comment by sagudev** [comment]
I think this is still problem for workers:
we have this in script thread: https://github.com/servo/servo/blob/fe58a5f0a3bd9a20e368ed283dfcb89769f75c00/components/script/script_thread.rs#L1422
and then in worker: https://github.com/servo/servo/blob/fe58a5f0a3bd9a20e368ed283dfcb89769f75c00/components/script/dom/serviceworkerglobalscope.rs#L245
