### ISSUE TITLE
Add a basic reftest for "hidpi" (high device-pixel-ratio) rendering

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#2572]
#2549 changed the behavior of reftests to always render at 1 dppx resolution, regardless of what hardware they are running on.  This means we are no longer doing any tests of higher-resolution rendering.  We should add a way to specify resolution in the reftest manifest, and add some basic "sanity" tests to ensure that it doesn't break (including a `!=` test to ensure that the 2x resolution rendering is different from the default 1x rendering).

**Comment by mskrzypkows** [comment]
Is the task still valid? 
As I understand, I have to modify parsing of manifest files to get information about used resolution, and apply it to given test. Does resolution should be specified for every single test independently? Or once per manifest file? 
@jdm is the command line now present here: http://mxr.mozilla.org/servo/source/components/util/opts.rs#479 ?

**Comment by jdm** [comment]
We're in the process of moving all of our reftests to the WPT harness, which does not support changing the resolution as far as I know (at least not on a per-test basis).

**Comment by jdm** [comment]
@mbrubeck Can you think of a way to do this in the brave new world?

**Comment by Ms2ger** [comment]
My plan is to reimplement any missing features in wptrunner, fwiw.

**Comment by mbrubeck** [comment]
#7667 added the ability to set the resolution in Servo's custom reftest harness. We'll need to reimplement that in wptrunner in order to port `tests/ref/pixel_snapping_border_a.html` from the reftest harness to the WPT harness.
