### ISSUE TITLE
Perform openxr rendering in webgl thread

### ISSUE THREAD

**Issue by jdm** [servo/servo#25735]
Per my idea in https://github.com/servo/servo/issues/25425#issuecomment-578342472, this issue tracks figuring out how to create the openxr d3d11 device and swapchain textures in the webgl thread so that we can render directly to them without having to perform any intermediary blits.

**Comment by asajeffrey** [comment]
The thing to do is probably to update the surfman-chains crate to allow it to render to a native swap chain, and to allow the webxr device to provide the swap chain rather than being given it by servo.

**Comment by jdm** [comment]
Doing some more thinking about what's involved here:
* the openxr device code needs to acquire the current surfman device that's in use on the webgl thread
* we need to create an openxr session using the surfman device's d3d11 device
  * it's not clear to me if we need to create the session on the webgl thread, or if we can create the session on the openxr thread and pass a pointer to a d3d11 device that's from another thread
* webgl uses sparkle, openxr uses gleam.

**Comment by jdm** [comment]
https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-render-multi-thread-intro suggests that making use of the webgl thread's D3D11 device from the openxr thread should be possible.

**Comment by jdm** [comment]
I have a branch which implements successfully this and the framerate is _way better_. I'm going to clean it up for review ASAP!
