### ISSUE TITLE
Rename XR to XRSystem

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#25732]
Our `XR` interface should be named `XRSystem`, a change made in https://github.com/immersive-web/webxr/pull/948

This involves:

 - Renaming `dom/webidls/XR.webidl`
 - Renaming `dom/xr.rs`
 - Renaming `XR`, `XRBinding`, `XRMethods` to `XRSystem*` instead

https://github.com/servo/servo/blob/ba23c5afee380930bd0f2c5fd665d318443ed19f/components/script/dom/xr.rs#L41

**Comment by jsjoeio** [comment]
@highfive: assign me
