### ISSUE TITLE
Can’t run immersive mode in emulator

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#25743]
Emulator 1044.

Acts as if it couldn’t find the openxr library:

```
RUST: WARN - webxr_api::registry - XR device error BackendSpecific("\"The specified module could not be found. (os error 126)\"")
```

**Comment by jdm** [comment]
Any chance your changes from https://github.com/servo/servo/pull/25403 are interfering? Does checking for openxr updates in the store change anything?

**Comment by paulrouget** [comment]
I’m seeing that dependency again on the loader: `VCRUNTIME140_1_APP.dll `.

**Comment by paulrouget** [comment]
I managed to make it work. But I’m not sure how:

I’ve updated Windows
I’ve updated VS2017
I installed VS2019
I’ve updated the Windows 10 SDK
Something fixed it.

**Comment by jdm** [comment]
VS 2019 is believable. We're going to make that a requirement of the servo build very soon.
