### ISSUE TITLE
Use inclusive rust ranges in Fetch file code

### ISSUE THREAD

**Issue by gterzian** [servo/servo#25751]
you can use inclusive rust ranges here if we want to

_Originally posted by @Manishearth in https://github.com/servo/servo/pull/25724_

See https://github.com/servo/servo/blob/19a06d1698adcaf666aa3d2b3560335212ecd61b/components/net/filemanager_thread.rs#L203

**Comment by Manishearth** [comment]
Actually given that the other branches shouldn't use inclusive ranges, I think we can just not do this.
