### ISSUE TITLE
In immersive mode, make sure to mark the window as not visible

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#25794]
I haven't tested yet, but we should make sure, at least in the case of the HL, that the compositor pipeline is set to not visible, to avoid useless animation to run in the background.

**Comment by asajeffrey** [comment]
We may need an api for the webxr device to tell servo if entering immersive mode obscures the browser display.

**Comment by paulrouget** [comment]
The 2D window get a hidden event when entering immersive mode.
