### ISSUE TITLE
Immersive "app" menu on hololens

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#25797]
We should have an "app menu" on hololens, much like the system start menu. This will be where we place trusted UI, for example.

I think a good gesture to have would be a "hold palm facing you" one (suggested by our Microsoft friends).

Initially it would just have an "exit VR" button but we could add more things.

It's easy enough to design the code to detect the gesture and spawn the UI, but I'm not sure how best to write the actual UI code for this. I'm also not sure if Hololens lets you render additional 3D stuff (like UI menus) when in an openxr immersive session.

cc @paulrouget

**Comment by paulrouget** [comment]
Related: https://github.com/servo/servo/issues/24693

I'll look.

**Comment by paulrouget** [comment]
`TryShowAsStandaloneAsync` allows us to open any View on top of the immersive mode. I've tried and it works. See: https://github.com/servo/servo/compare/master...paulrouget:IMMenu

@Manishearth I think the gesture recognition needs to happen on the openxr backend side. We will need to send a signal to the UWP app. How would that work?

**Comment by Manishearth** [comment]
Hmmmm. So the gesture recognition itself is pretty easy, we can use some dot products on the grip space unit vectors. Sending the signal out is tricky because the API servo uses is designed generically. What we _could_ do is accept an optional struct on session creation with a `trigger_menu_display()` function, and have it contain an IPC sender. On creation, servo creates the receiver end hooks it up to the embedder.

Ideally the session would be unable to receive input during this time; what we might have to do is have this function return an `Option<Receiver>`, where the `None` case means that the menu was not opened, and the receiver is what lets us know we can resume receiving input.

Thoughts? cc @asajeffrey

**Comment by Manishearth** [comment]
The receiver would probably have two potential responses: exit immersive session, and resume working (if the menu is exited)

**Comment by paulrouget** [comment]
> Ideally the session would be unable to receive input during this time
 
Why?

**Comment by paulrouget** [comment]
I need to test, but I don't think the window is modal. If it doesn't have focus, inputs can get directed to the session.

**Comment by Manishearth** [comment]
Yeah, what I mean is that the WebXR backend should be aware that the menu is open (and when it closes) so that it can stop sending input information to JS

The idea is that JS should not be able to see interactions with this UI: we will need similar things for permissions prompts in XR as well

**Comment by paulrouget** [comment]
I'm thinking of setting up a context menu API that would work for both IM and regular mode. This will be modal, have open/close events, and have an API to insert clickable items in the menu.

**Comment by Manishearth** [comment]
@paulrouget oh, that could be nice

**Comment by paulrouget** [comment]
Using an regular 2D view doesn't seem well supported. Depending on how the view is created, the Start menu shows up, or we get a crash. I've tried using a menu flyout, but it doesn't show in IM. Asked MS what is the proper way to show menu/xaml content while in IM.

**Comment by jdm** [comment]
How much work would it be to show a single yes/no prompt that allows leaving immersive mode? Right now we can return to the home screen, but reactivating FxR re-enters immersive mode.

**Comment by paulrouget** [comment]
First part, API + UWP dialog: https://github.com/servo/servo/pull/26043

Next step is to open that context menu from whatever gesture. What would a good trigger to open that menu?

**Comment by Manishearth** [comment]
Next part is #26051
