### ISSUE TITLE
Electron-like-with-Servo

### ISSUE THREAD

**Issue by NetOperatorWibby** [servo/servo#25829]
"Starling" was apparently something being worked on in 2018 after the ending of BrowserHTML but I see no mention of it online, unless my search-fu is terrible.

I'd much prefer to use Servo than Electron but it's not as easy to get up and running as Electron. Are there public examples of a Servo-based app built with HTML/CSS/JS?

**Comment by jdm** [comment]
There are no such apps at this time. The only examples of embedding Servo right now are https://github.com/servo/servo/tree/master/ports and https://github.com/servo/servo/tree/master/support.

**Comment by pwnorbitals** [comment]
(Triage : issue can probably be closed now)

**Comment by NetOperatorWibby** [comment]
Sadness
