### ISSUE TITLE
Remove azure canvas backend

### ISSUE THREAD

**Issue by jdm** [servo/servo#25833]
Now that the [raqote backend](https://github.com/servo/servo/blob/master/components/canvas/raqote_backend.rs) has reached feature parity and been enabled by default, we should remove the unused [azure backend](https://github.com/servo/servo/blob/master/components/canvas/azure_backend.rs) entirely.

**Comment by dralley** [comment]
@highfive: assign me

**Comment by dralley** [comment]
Currently you can choose to use either the Azure backend or the Raquote backend, but at least one of them and not both.  I assume that as part of this issue, the feature flag that allows the Raquote backend to be disabled should be removed?

**Comment by jdm** [comment]
Correct!

**Comment by dralley** [comment]
PR posted
