### ISSUE TITLE
UWP app exits after immersive mode starts in emulator

### ISSUE THREAD

**Issue by jdm** [servo/servo#25836]
This looks like it might be a regression from #25799, or possibly a new base emulator image triggered it. The order of operations is that immersive mode starts, then the [app is suspended](https://github.com/servo/servo/blob/0be611188dd10a7521b0afc3a8a45d7dc9f2b595/support/hololens/ServoApp/App.cpp#L109). We happily [queue a shutdown task](https://github.com/servo/servo/blob/0be611188dd10a7521b0afc3a8a45d7dc9f2b595/support/hololens/ServoApp/ServoControl/ServoControl.cpp#L26-L35) which tells the compositor to exit, which tells the constellation to exit, which tells the script thread to exit, which tells webxr to exit, and then the app is totally shut down before any immersive content appears.

**Comment by jdm** [comment]
This continues to happen when I comment out the `Page->Shutdown()` in OnSuspend, and then none of my other breakpoints related to shutting down the compositor and constellation get hit.

**Comment by jdm** [comment]
This affects me in the HoloLens emulator, but not in a VR headset with https://github.com/servo/webxr/pull/132 applied.

**Comment by paulrouget** [comment]
I can't reproduce.

Which version of the emulator?

**Comment by jdm** [comment]
10.0.18362.1053

**Comment by paulrouget** [comment]
And does reverting #25799 help?

**Comment by jdm** [comment]
This was fixed by removing the code that shut down the browser in the suspend event handler.
