### ISSUE TITLE
Can't use --debugger=rust-gdb with test-wpt

### ISSUE THREAD

**Issue by pylbrecht** [servo/servo#25868]
Running
```shell
./mach test-wpt tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord3.html --debug-build --headless --debugger=rust-gdb
```
results in the following output:
```
ALLIUM_DRIVER=softpipe
LD_LIBRARY_PATH=/home/palbrecht/dev/servo/target/debug/build/osmesa-src-8f7785fb212058d5/out/lib/gallium
 0:02.93 INFO Using 6 client processes
 0:03.04 INFO Starting http server on 127.0.0.1:8000
 0:03.05 INFO Starting http2 server on 127.0.0.1:9000
 0:03.06 INFO Starting http server on 127.0.0.1:8001
 0:03.11 INFO Starting https server on 127.0.0.1:8443
 0:03.55 SUITE_START: web-platform-test - running 1 tests
 0:03.55 INFO Running reftest tests
 0:03.55 INFO No reftest tests to run
 0:03.55 INFO Running wdspec tests
 0:03.55 INFO No wdspec tests to run
 0:03.55 INFO Running testharness tests
 0:03.56 INFO Starting runner
 0:03.57 INFO No more tests
 0:03.58 INFO No more tests
 0:03.58 INFO No more tests
 0:03.58 TEST_START: /2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord3.html
 0:03.58 INFO No more tests
 0:03.58 INFO No more tests
 0:03.58 WARNING Got command init_succeeded in state running
 0:03.66 pid:3384327 Full command: /home/palbrecht/.cargo/bin/rust-gdb /home/palbrecht/dev/servo/target/debug/servo --hard-fail -u Servo/wptrunner -z http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord3.html -Z replace-surrogates --user-stylesheet /home/palbrecht/dev/servo/resources/ahem.css --pref dom.canvas-text.enabled=false --certificate-path /home/palbrecht/dev/servo/tests/wpt/web-platform-tests/tools/certs/cacert.pem
pid:3384327 gdb: unrecognized option '--hard-fail'
 0:03.66 pid:3384327 Use `gdb --help' for a complete list of options.
 0:03.67 TEST_END: CRASH, expected OK
 0:03.67 INFO No more tests
 0:03.69 INFO Closing logging queue
 0:03.69 INFO queue closed
 0:03.69 INFO Running crashtest tests
 0:03.69 INFO No crashtest tests to run
 0:03.69 INFO Got 1 unexpected results
 0:03.69 SUITE_END

web-platform-test
~~~~~~~~~~~~~~~~~
Ran 1 checks (1 tests)
Expected results: 0
Unexpected results: 1
  test: 1 (1 crash)

Unexpected Results
------------------
CRASH /2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord3.html
 0:03.73 INFO Closing logging queue
 0:03.74 INFO queue closed
```

This is due mozdebug 0.1 [missing the `rust-gdb` entry in `__DEBUGGER_INFO`](https://hg.mozilla.org/mozilla-central/file/tip/testing/mozbase/mozdebug/mozdebug/mozdebug.py#l43).

What worked for me was activating the virtualenv and manually upgrading mozdebug:
```shell
source python/_virtualenv2.7/bin/activate && pip install --upgrade mozdebug && deactivate
```

I'm not sure what needs to be done to perform a clean Servo wide update. I tried bumping mozdebug's version to 0.2 in [python/requirements.txt](https://github.com/servo/servo/blob/master/python/requirements.txt#L7), but this did not work as expected.

I'm happy to open a PR if anyone can provide further instructions.

**Comment by jdm** [comment]
Is there any difference if you update the python/requirements.txt and remove the virtualenv before running the command?

**Comment by pylbrecht** [comment]
That's what I did after bumping mozdebug's version in requirements.txt, to check if it works if `./mach` installs it by itself. But surprisingly this did not work and resulted in the same output. Sorry for not clarifying.. the exact steps were these:
1. `rm -f -r python/_virtualenv2.7/`
2. Bump mozdebug's version to 0.2 in python/requirements.txt
3. `./mach --help` to rebuild the virtualenv
4. `./mach test-wpt ...`

I also did a `pip freeze > python/requirements.txt` after manually upgrading mozdebug to check if any other packages are updated. The diff was not very helpful though, because Servo's python/requirements.txt is not a direct output of `pip freeze`.

**Comment by pylbrecht** [comment]
I manually created a `pip freeze` diff:
```
< mozdebug==0.2.0
---
> mozdebug==0.1.1
```
So bumping mozdebug's version in requirements.txt only upgrades mozdebug.

**Comment by jdm** [comment]
Try updating tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt as well.

**Comment by pylbrecht** [comment]
I see.. https://github.com/servo/servo/blob/master/python/mach_bootstrap.py#L184
That did the trick. I'll open a PR for this.
