### ISSUE TITLE
Support HTTP compression

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#2587]
This might be a bit in the distance for now, but we eventually should support [HTTP Compression](http://en.wikipedia.org/wiki/HTTP_compression)

Some APIs (and possibly websites) have started switching to using compression by default ([example](http://api.stackexchange.com/docs/compression)).

**Comment by mattnenterprise** [comment]
I would like to give this one a try.

**Comment by jdm** [comment]
Go for it!

**Comment by mattnenterprise** [comment]
@jdm What do you think about using [https://github.com/alexcrichton/flate2-rs](https://github.com/alexcrichton/flate2-rs)? It supports both gzip and deflate, which look like the main types of compression that are used.

**Comment by jdm** [comment]
I'm all for reusing other people's work.
