### ISSUE TITLE
Servo won't build if boostrap-android is run with just emulator-x86

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#25872]
Running `mach bootstrap-android` only installs the platform `android-28`, which causes blurdroid to fail to build, because it only checks for platforms up to 27: https://github.com/szeged/blurdroid/blob/f21e26e159cbeca4c30c3c87f097f0ece06c9d63/build.rs#L115

**Comment by jdm** [comment]
Given that there is a `--build` mode for bootstrap-android, this feels like it's working as intended.
