### ISSUE TITLE
Transitions and animations

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#25884]
I don’t know off hand the state of this in Layout 2020, but it’s worth looking at. Might be mostly about copying/porting more of `components/layout_thread` to `components/layout_thread_2020`

**Comment by atouchet** [comment]
It might be worth noting that the existing transition and animation code in Servo is quite buggy (ex. #20116). @emilio [previously suggested that most of it should probably be rewritten](https://github.com/servo/servo/pull/20757#issue-186214925).
