### ISSUE TITLE
skulls demo doesn't render anything in immersive mode

### ISSUE THREAD

**Issue by jdm** [servo/servo#25895]
I see content in the windowed mode, but nothing appears around me when I enter immersive mode.

**Comment by paulrouget** [comment]
That's a regression. This used to work.

**Comment by paulrouget** [comment]
JS error `controller.vrController.gamepadController is undefined` not in babylonjs, but in the demo itself. And the fix for the demo was made for the webvr API, not webxr. I think this used to work *before* the introduction of the point support in the demo.

I'll be talking to the bbjs people about this.

**Comment by paulrouget** [comment]
Note to self:

The BBJS demo has been updated for webvr, but not webxr. Webxr works differently (no more vr controller). It is documented here: https://doc.babylonjs.com/how_to/webxr_controllers_support.  The difference between vr and xr is documented here https://doc.babylonjs.com/how_to/introduction_to_webxr#migrating-from-webvr , not everything is up to date (like, motionController is an async operation)

**Comment by paulrouget** [comment]
Tried to make it work, but the demo was initially designed for WebVR. I talked with Raanan, and we are going to remove this demo, and I will add 3 new demos, up to date with WebXR API and the latest babylonjs version:

* https://playground.babylonjs.com/pg/CHF3KW/revision/39
* https://playground.babylonjs.com/pg/PPM311/revision/63
* https://playground.babylonjs.com/pg/B922X8/revision/19

**Comment by paulrouget** [comment]
We removed the demo.
