### ISSUE TITLE
babylon drumming demo rendering is wildly different for each eye

### ISSUE THREAD

**Issue by jdm** [servo/servo#25894]

**Comment by paulrouget** [comment]
That's a regression. This used to work.

**Comment by paulrouget** [comment]
Actually I have memories of "weirdness" with this demo. I don't remember exactly what was wrong, but maybe it's what you are seeing here.

I can't test though, emulator has only one eye :)

**Comment by jdm** [comment]
If you allow ImmersiveAR in https://github.com/servo/webxr/blob/master/webxr/glwindow/mod.rs#L98, it might be possible to reproduce it in the desktop glutin build.

**Comment by jdm** [comment]
Sadly I do not reproduce the same rendering behaviour in the glwindow backend on macOS.

**Comment by jdm** [comment]
Strangely, https://www.joshmatthews.net/20200326_170456_HoloLens.mp4 does not show the difference between the eyes; maybe it's only recording one eye's input or something? It does show that the depth and positioning is wonky, at least.

**Comment by jdm** [comment]
This got fixed at some point.
