### ISSUE TITLE
Mach bootstrap tries to install packages globally?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#25949]
Running `mach build -r` on a Mac, using python3.7 fails, due to trying to install packages into `/usr/local`. I thin what's going on is that https://github.com/servo/servo/blob/4b1bb895a30e798f3b0c293e4cf95630db692323/python/mach_bootstrap.py#L200-L213 is running in the system python rather than the virtualenv python?

**Comment by asajeffrey** [comment]
Can't cut and paste out of vnc, but here's a screenshot.
![Screenshot of administrator’s Mac mini at 2020-03-11 16:57:25](https://user-images.githubusercontent.com/403333/76468409-e3319b00-63b9-11ea-99f2-98d27030e5ee.png)

**Comment by nox** [comment]
I don't know if it's installing things in the wrong location, but it's definitely weird that you get permission denied errors for things in Homebrew's `/usr/local`, which is supposed to be owned by you. Did you maybe run `sudo brew install …` at some point?

**Comment by jdm** [comment]
I suspect the problem is that alan was using the `administrator` account, and homebrew was set up to run under the `worker` account.

**Comment by asajeffrey** [comment]
Which in this case is a good thing, I really want intending to install any software globally by running mach build.

**Comment by nox** [comment]
@asajeffrey Homebrew is supposed to be installed with the account you normally use.

**Comment by mrobinson** [comment]
I think we can close this one.
