### ISSUE TITLE
macOS installation troubles: python@2 is now gone from Homebrew

### ISSUE THREAD

**Issue by nox** [servo/servo#25951]
The python@2 formula has been removed from Homebrew, and system's Python 2 doesn't come with pip, so `pip install virtualenv` fails.

**Comment by nox** [comment]
I used this to reinstall `virtualenv` for system's Python 2.

**Comment by nox** [comment]
By "this" I meant https://gist.github.com/haircut/14705555d58432a5f01f9188006a04ed. It helps if I actually paste the link.

**Comment by jdm** [comment]
For posterity's sake: https://github.com/Homebrew/homebrew-core/pull/49796

**Comment by jdm** [comment]
We might be able to get by with https://github.com/drolando/homebrew-deadsnakes if we don't want to go all-in on python 3 yet.

**Comment by nicoabie** [comment]
For future reference: servo needs pip and virtualenv in version 2.7 of python
Without them the following error will be displayed
**Python virtualenv is not installed. Please install it prior to running mach.**

To overcome this run use easy install to get pip in version 2.7 of python
`sudo easy_install pip`
Then
`pip install virtualenv`

**Comment by mrobinson** [comment]
Servo no longer depends on Python 2.
