### ISSUE TITLE
Refactor layout of nested inline-level boxes to use recursion instead of a vector

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#25950]
Currently, the lifetimes on `InlineFormattingContextState` don't work out when we surround `InlineLevelBox` with `AtomicRefCell`. The `partial_inline_boxes_stack` of nested inline-level boxes inside `InlineFormattingContextState` ends up with different lifetimes mashed together; this works in the current setup, because the borrow checker can find a super-lifetime, but not when borrows are dynamically tracked. The simplest strategy I can think of to resolve this is to use the call stack instead of a vector. This requires some refactoring.

cc @SimonSapin @nox

**Comment by pcwalton** [comment]
This is needed for https://github.com/servo/servo/issues/25168.

**Comment by nox** [comment]
I don’t understand, what’s the problem with the lifetimes? The code is literally engineered this way to not use the wall stack.

Jeu 12 mars 2020, à 04:39, Patrick Walton a écrit :

**Comment by pcwalton** [comment]
Because if you surround all `InlineLevelBox`es with `AtomicRefCell` borrows become dynamic instead of static, which means you would have to undo the dynamic borrows as you pop the stack, which can't be expressed safely in the Rust type system.

**Comment by nox** [comment]
I don't understand what you mean.

**Comment by nox** [comment]
I don't see how your system avoids more bad things than my system.

**Comment by ferjm** [comment]
Is this still a valid issue after https://github.com/servo/servo/pull/25957#issuecomment-600403277 ?

**Comment by nox** [comment]
Nope.
