### ISSUE TITLE
Remove createTouch and createTouchList

### ISSUE THREAD

**Issue by jdm** [servo/servo#25978]
These were removed from the spec in https://github.com/w3c/touch-events/pull/96. We should delete https://github.com/servo/servo/blob/f5c086b30759e7203bb1ab412693f0e86252dafc/components/script/dom/webidls/Document.webidl#L189-L200 and https://github.com/servo/servo/blob/f5c086b30759e7203bb1ab412693f0e86252dafc/components/script/dom/document.rs#L3897-L3918.

**Comment by humancalico** [comment]
@jdm Can I work on this?

**Comment by jdm** [comment]
Please do!

**Comment by humancalico** [comment]
@jdm Does [this](https://github.com/servo/servo/blob/acd14672e186adb1a417007bcb90702a21484e83/tests/wpt/webgl/tests/deqp/temp_externs/iphone.js#L81-L94). Also needs to be removed?

**Comment by jdm** [comment]
No, that's from https://github.com/KhronosGroup/WebGL/tree/master/sdk/tests/deqp so any such changes would need to go upstream instead.
