### ISSUE TITLE
trying webcam on windows but plug in is not there

### ISSUE THREAD

**Issue by Smittie1** [servo/servo#25974]
Hello,

Because I am new to Gstreamer I am just testing some basic functions. Some extra information:
I am using windows 10 and the Gstreamer version that I use is 1.15.1 .
When I wanted to test the web cam and used:
`gst-launch-1.0 ksvideosrc ! videoconvert ! ximagesink`
and got `WARNING: erroneous pipeline: no element "ksvideosrc"`
so then I used `gst-inspect-1.0 ksvideosrc`
and got the response `No such element or plugin 'ksvideosrc'`
Can some one help me pls?

**Comment by paulrouget** [comment]
This is not the gstreamer repository. You will find more information here: https://gstreamer.freedesktop.org/ and you can ask questions there: https://gstreamer.freedesktop.org/lists/
