### ISSUE TITLE
Servo crashes when RUST_LOG=servo::layout is set

### ISSUE THREAD

**Issue by ebalint** [servo/servo#2601]
Here is the output:

https://gist.github.com/ebalint/18cc09d3c772cd37e870

It occurs on Ubuntu 13.10 (x86_64).
I tried it with about-mozilla.html, acid1.html and acid2.html

**Comment by JanZerebecki** [comment]
It seems this was fixed in the mean time. At least I can't reproduce it anymore (`$ RUST_LOG=layout ./target/debug/servo tests/html/about-mozilla.html`).

**Comment by jdm** [comment]
Thanks for checking!
