### ISSUE TITLE
Deduplicate base64

### ISSUE THREAD

**Issue by nox** [servo/servo#26013]
Latest release is 0.12, brought in crate tree through #26005.

Dependencies that already depend on 0.12 that we need to bump on our side: 
 * `headers`
   * `warp`
   * `hyper_serde`

Dependencies on 0.10 that Mozilla people maintain:
 * `webdriver` (depends on `warp`)
 * `webrender`

Dependencies on 0.10 that require upstream changes:
 * `influent`

Dependencies on 0.11 that require upstream changes:
* [`rust-argon2`](https://github.com/sru-systems/rust-argon2/issues/32)
  * [`redox_users`](https://gitlab.redox-os.org/redox-os/users/issues/30)

**Comment by Eijebong** [comment]
For info: webdriver -> https://bugzilla.mozilla.org/show_bug.cgi?id=1606281

**Comment by Eijebong** [comment]
Also I just published influent 0.5.3 with base64 0.12

**Comment by Eijebong** [comment]
Influent will also need an update for tokio. Is it really something useful for servo ? I'm currently kind of maintaining for dep updates but I don't have any real motivation to do so.

**Comment by atouchet** [comment]
base64 0.12 was de-duped in #29766.

**Comment by jdm** [comment]
https://github.com/rust-ammonia/rust-content-security-policy/pull/36

**Comment by jdm** [comment]
https://github.com/hyperium/headers/pull/140

**Comment by dvtkrlbs** [comment]
I looked at this issue for bumping to 0.21.2. The problem is this bumps MSRV and some crates are reluctant to also bump it i.e headers. Should we go with base64 or switch to data encoding. Which still uses 0.47 as MSRV and API is still very similiar to previous base64 api design.

**Comment by jdm** [comment]
I'm not sure if switching to `data-encoding` will make a big difference unless we convince all of the crates that currently depend on base64 to switch as well.

**Comment by dvtkrlbs** [comment]
Ok that makes sense I will open a pr for updating to 0.21.2. There are still a few upstream crates that are on 0.10 and 0.13 but there is nothing other than waiting for them.

**Comment by atouchet** [comment]
This was done in #30415.
