### ISSUE TITLE
Make Stylist no longer an unsafe pointer once we have fast RWArcs

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#2604]
Currently RWArcs use Sems and that is very slow. Once that is no longer the case, put Stylist in an RWArc.

**Comment by pcwalton** [comment]
@SimonSapin I believe `RWLock` is fast now, looking at Rust. We'll need to benchmark to make sure.

**Comment by mt2d2** [comment]
Took a look at this with help from @Ms2ger on IRC—an implementation moving the ```Stylist``` from ```LayoutTaskData``` to ```LayoutTask``` as an ```Arc<RwLock<Stylist>>``` panics with a deadlock. Similar deadlock seen when simply using a Mutex (albeit no panic). No luck, open to suggestions!

**Comment by Ms2ger** [comment]
That was https://github.com/servo/servo/compare/master...mt2d2:stylist_arc_rwlock

**Comment by pcwalton** [comment]
Probably needs finer-grained locking inside the Stylist then?

**Comment by Yoric** [comment]
I can try to work on this. How can I test my code?

**Comment by jdm** [comment]
I believe #7524 is taking care of this.

**Comment by Ms2ger** [comment]
I tried to just wrap it into `Arc`/`Mutex` on top of #8378; to my surprise it managed to load github: <https://github.com/servo/servo/compare/servo:master...Ms2ger:arc-stylist?expand=1>.

**Comment by eefriedman** [comment]
Sure, you can wrap it in a Mutex... but what does that do to the performance?  (That's what sent me down the path of borrowing it.)

**Comment by Ms2ger** [comment]
Alternatively, we could try to move the `Stylist` out of the `LayoutTask` entirely; then we could borrow it while there's a mutable borrow of the `LayoutTask`.

**Comment by SimonSapin** [comment]
Move it tot the document node, similar to https://github.com/servo/servo/pull/8039 ?

**Comment by Ms2ger** [comment]
I don't follow.

**Comment by SimonSapin** [comment]
You mention moving `Stylist` out of `LayoutTask`. To where? One option could be to have it owned by the document node. There is sort of a precedent in that PR, which moves ownership of stylesheets from `Stylist` to respective DOM nodes.

**Comment by eefriedman** [comment]
If we intentionally want to dynamically check the borrowing of Stylist, I think we can just stuff it into an Arc, and use `get_mut().unwrap()` when we want to mutate it.  Granted, it's stylistically terrible, but it's probably better than a raw pointer.

I don't see how changing the ownership of the Stylist helps.

**Comment by SimonSapin** [comment]
I don’t think we need dynamic checks at all if `Stylist` is in the DOM. Like the rest of DOM data, access is exclusive from the script task, and shared but read-only in the "early" phase (until flow tree construction) of layout.

**Comment by eefriedman** [comment]
Oh, right... if Stylist is in the DOM, we don't need to mutate it from layout.  Makes sense.

**Comment by jdm** [comment]
Latest attempt at #7524.

**Comment by emilio** [comment]
#10815 Should take care of this.

It uses an `Arc` plus `Arc::get_mut`, and seems to work just fine. It should not have almost any performance overhead.

**Comment by SimonSapin** [comment]
@emilio `Arc::get_mut` clones the contents if the refcount is above one. Is this really desired here? This issue originally mentions `RWLock`.

**Comment by emilio** [comment]
@SimonSapin: Stylist is not cloneable, [`Arc::get_mut`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.get_mut) returns `None` if the refcount is not one (unlike `Arc::make_mut`).

I'm using `Arc::get_mut(&mut rw_data.stylist).unwrap()` and I haven't ever got a crash.

**Comment by SimonSapin** [comment]
Oh yeah, sorry, I got confused with `make_mut`. But if the refcount really is always one, could this be a `Box`?

**Comment by emilio** [comment]
I think not since it has to be handed out to layout traversal (I mean to `SharedLayoutContext`).

The refcount is always one when we update the stylist in the layout thread, but not always.

**Comment by emilio** [comment]
This is closed by #10815
