### ISSUE TITLE
"./mach bootstrap" not working

### ISSUE THREAD

**Issue by payaljindal** [servo/servo#26045]

**Comment by jdm** [comment]
Can you provide more information about what operating system you are using and I what way the bootstrap command does not work?

**Comment by payaljindal** [comment]
I am running ubuntu virtually on windows. After filing the issue, it worked. But now, when I run ./mach build --dev it again shows me that an error occurred in code that was called by mach command and says to report the issue.

**Comment by jdm** [comment]
Can you paste the full output of the build?

**Comment by dralley** [comment]
Also, which version of Ubuntu?
