### ISSUE TITLE
Replace `fallible` boolean arguments with an enum

### ISSUE THREAD

**Issue by jdm** [servo/servo#26047]
Various methods in WebGL objects have `fallible` arguments that are used to support operations that can fail during object destruction that do not indicate a total failure. We should replace these booleans with a `enum Operation { Fallible, Infallible }` instead to make the code readable:

Code:
* https://github.com/servo/servo/blob/cf725fc3f59bc1b94e3b35ab4cfe60b3d41559cc/components/script/dom/webgltexture.rs#L192
* https://github.com/servo/servo/blob/cf725fc3f59bc1b94e3b35ab4cfe60b3d41559cc/components/script/dom/webglbuffer.rs#L94-L104
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglvertexarrayobject.rs#L44
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglvertexarrayobjectoes.rs#L44
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglsampler.rs#L93
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglsync.rs#L85
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webgltransformfeedback.rs#L101
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglquery.rs#L99
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglrenderbuffer.rs#L93
* https://github.com/servo/servo/blob/a927f1ad8a9ce211618139b2a69c8ce3b739438b/components/script/dom/vertexarrayobject.rs#L47
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglprogram.rs#L87
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglshader.rs#L306
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webgltexture.rs#L186
* https://github.com/servo/servo/blob/67b433648c79a8b397213605311011e22d707cec/components/script/dom/webglframebuffer.rs#L205

**Comment by skrzyp1** [comment]
@highfive: assign me
I'll try to do it as i seems beginner friendly.

**Comment by akshay1992kalbhor** [comment]
Where would the enum be defined? Its being used my multiple WebGL objects. Also do we need a new name for the second argument now that its an enum? Something like 'operation_fallibility' instead of 'fallible'?

**Comment by jdm** [comment]
Defining the enum in webglrenderingcontext.rs is probably fine; I think all of those files already import things from that module. Renaming it like you suggest sounds fine.

**Comment by skrzyp1** [comment]
Sorry i forgot about that ill get to work unless its already WiP by someone else

**Comment by akshay1992kalbhor** [comment]
I haven't started working on the issue yet. Just wanted to know how to solve it. I know it was assigned to you so if you still want to work on it go ahead! Sorry for the confusion.

**Comment by he4d** [comment]
@highfive: assign me
I will try this

**Comment by he4d** [comment]
Do I need to write some tests for this?

**Comment by jdm** [comment]
No - if it builds, that's good enough for a PR.
