### ISSUE TITLE
Can't build Servo on macOS 10.15.4

### ISSUE THREAD

**Issue by utsavoza** [servo/servo#26040]
On a freshly cloned repo, the error message I received after running `./mach build -d` (simply by following the steps outlined in `README.md` and `HACKING_QUICKSTART.md`) was:
```
--- stderr
ERROR: SDK version "10.15.4" is unsupported. Please downgrade to version 10.15. You may need to point to it using --with-macos-sdk=<path> in your mozconfig. Various SDK versions are available from https://github.com/phracker/MacOSX-SDKs
make: *** [maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', /Users/utsavoza/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/2392ebc/build.rs:181:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After sifting through some similar closed issues in servo (#25919) and [mozjs](https://github.com/servo/mozjs) ([#156](https://github.com/servo/mozjs/issues/156)), I was able to resolve the build error by manually downloading the macOS SDK version 10.15 from the link provided in the above error message and pointing the [`MACOS_SDK_DIR` variable needed by mozjs](https://github.com/servo/mozjs/blob/master/mozjs/build/moz.configure/toolchain.configure#L136) to the newly downloaded sdk path.

The command I eventually ended up running to successfully build servo was: 
```
$ MACOS_SDK_DIR=<path/to/the/downloaded/sdk> ./mach build -d
```

I agree with what @jdm suggested in the issue #25919, i.e. to make this step a part of mach bootstrap for macOS. But for the time being it would be helpful for newcomers like me to have some pointers to a temporary fix in the `HACKING_QUICKSTART.md` guide itself (I'd be happy to provide one) to quickly get up and running with the build - something similar to the mention of SSL issue on Macs in the [Building Servo](https://github.com/servo/servo/blob/master/docs/HACKING_QUICKSTART.md#building-servo) section.

**Comment by jdm** [comment]
This will be addressed by https://github.com/servo/mozjs/pull/238. Apple released a new SDK two days ago, unfortunately.

**Comment by utsavoza** [comment]
Great, thanks!
