### ISSUE TITLE
Embedder/Device interaction API

### ISSUE THREAD

**Issue by gterzian** [servo/servo#26057]
Follow-up on what was discussed at https://github.com/servo/servo/pull/26051, and in the light of https://github.com/servo/webxr/pull/144/

So looking how the context menu is used in WebXr, where:
1. The context menu is shown from `wait_for_animation_frame` at https://github.com/servo/webxr/pull/144/
2. The result of the context menu user interaction is polled also inside `wait_for_animation_frame` at https://github.com/servo/webxr/pull/144/files#diff-f3cfd7c22eb8b9fb4aeefdabdb68f7e4R709

So to me it appears that both the Xr device needs to have a way to interact with the embedder. This is perphaps best done like [currently](https://github.com/servo/servo/pull/26051/files#diff-e9ca1da94478b17f780dfb3ccfa2190eR787), by wrapping a `EmebdderProxy`. 

On the other hand, the embedder then needs to be able to interact with WebXr, in this case to communicate the result of the action. 

The way that is done in https://github.com/servo/servo/pull/26051 is by having the embedder send a message on a channel, whose corresponding receiver is polled by WebXr at each `wait_for_animation_frame`. 

So I think this contributes to what has been noted at https://github.com/servo/servo/issues/23899, since we're adding additional polling logic inside the nested "Xr loop" that runs inside the main-thread loop each time the compositor calls [`webxr_main_thread.run_one_frame()`](https://github.com/servo/servo/blob/e6ae93f66e724bf15e5badccc8d4046e19f04fa8/components/compositing/compositor.rs#L1502). 

I also think that tying handling the result of the menu choice to waiting on an animation frame reinforces the dependency of the system to always run animation frame even when it's not actually useful, which is something that was noted at https://github.com/servo/servo/issues/25305.

So my proposed solution to this would be for the embedder to have access to a `WebXRDeviceProxy`, which could be used to communicate the result of the context menu choice. 

I think such a proxy could internally be implemented with synchronous calls if XR is running on the main-thread, or with message passing if running off of it. 

The main-thread usecase would essentially boil-down to calling `quit` on the XR device, if the user has made that choice. 

While the off-main-thread version could send a `Quit` message, to be handled by XR on it's dedicated event-loop in a way that isn't tied to the raf loop. 

cc @paulrouget @Manishearth

**Comment by Manishearth** [comment]
> The main-thread usecase would essentially boil-down to calling quit on the XR device, if the user has made that choice.

For calling `Quit` we already have the `Quitter` object, which works exactly how you describe. I'm reluctant to make an openxr-specific concept part of the main webxr API, however, since we can't _just_ get away with `.quit()`, we also need a `.cancel_menu()`.



> So I think this contributes to what has been noted at #23899, since we're adding additional polling logic inside the nested "Xr loop" that runs inside the main-thread loop each time the compositor calls [`webxr_main_thread.run_one_frame()`](https://github.com/servo/servo/blob/e6ae93f66e724bf15e5badccc8d4046e19f04fa8/components/compositing/compositor.rs#L1502).

This isn't true, the openxr XR loop no longer runs on the main thread loop



> I also think that tying handling the result of the menu choice to waiting on an animation frame reinforces the dependency of the system to always run animation frame even when it's not actually useful, which is something that was noted at #25305.

This already has to be true, spec-wise, though. It's not possible for webxr implementations to _stop_ waiting for frames except when the session is blurred. The `wait_for_animation_frame` is just a part of the frame loop.

 #25305 is about a different kind of animation frame. The XR animation frames are more tightly scoped.

**Comment by gterzian** [comment]
> #25305 is about a different kind of animation frame. The XR animation frames are more tightly scoped.

Ah yes, forgot about the different animation frame loops...

Yes I agree on the other points too. 

Re the `Quitter`, I haven't looked into it yet. I did make a proposal in the PR for a slightly different flow that doesn't require polling for the results and instead plugs into the existing session message handling. 

Although if Xr really does need to run a frame-loop to which #25305 wouldn't apply(so there would be no reason to not tie everything into the frame loop), then you might indeed as well poll the receiver for the result as part of that loop, making my proposed restructuring not as useful as I thought.

**Comment by gterzian** [comment]
Closed by https://github.com/servo/servo/pull/26051

**Comment by CYBAI** [comment]
maybe #26051 will be merged soon though, should we close this issue when the PR is merged 👀?

**Comment by gterzian** [comment]
Yes, I just didn't want(or not sure I can) edit the PR opening comment(where you need to add FIX to close an issue, it doesn't seem to work if you do it in a comment on the PR).

**Comment by CYBAI** [comment]
I see!
