### ISSUE TITLE
Check for Background-Hang-Monitor opts in multi-process

### ISSUE THREAD

**Issue by gterzian** [servo/servo#26088]
In single-process mode, we only start a BHM if the options has been set:

https://github.com/servo/servo/blob/af1ebe79efd799498010f196983a233aa5203d64/components/constellation/pipeline.rs#L322

But we don't perform this check before starting the BHM in multi-process mode:

https://github.com/servo/servo/blob/b3c12ad9b3404d4b9df2ccbb15b7a9259a2a0322/components/servo/lib.rs#L1019

I think we should. The same `opts` is available there as well.

**Comment by qrasmont** [comment]
@highfive: assign me
Ok first ever contribution, let's have a go!
