### ISSUE TITLE
Video texture cannot be rendered on Android

### ISSUE THREAD

**Issue by yangchengjian** [servo/servo#26098]

**Comment by yangchengjian** [comment]
When I run on macos with 
```sh
python3 ./mach run --dev https://mdn.github.io/webgl-examples/tutorial/sample8/
```
I can see video, but I can't see it on Android.

**Comment by jdm** [comment]
Android builds aren't actively supported any more.

**Comment by Darkspirit** [comment]
(Background: https://github.com/servo/servo/pull/25877#issuecomment-593739198)
