### ISSUE TITLE
ServiceWorker: restructure data structure and algorithms to better match the spec

### ISSUE THREAD

**Issue by gterzian** [servo/servo#26108]
EDIT: the second comment is more accurate, still keeping this here for a basic overview of how it currently works. We need to move the Jobqueue to the constellation or service worker manager level. 

https://github.com/servo/servo/blob/f7d3d4a44762b3196c8dcbe58b628b5a23fc7833/components/script/serviceworkerjob.rs#L102

Spec: https://w3c.github.io/ServiceWorker/#dfn-job-queue

The `JobQueue` used to run algorithms for service workers seems to currently be tied to having a `ScriptThread` being available. 

See for example how a job is scheduled: https://github.com/servo/servo/blob/f7d3d4a44762b3196c8dcbe58b628b5a23fc7833/components/script/serviceworkerjob.rs#L110

Or how a job is run:

https://github.com/servo/servo/blob/f7d3d4a44762b3196c8dcbe58b628b5a23fc7833/components/script/serviceworkerjob.rs#L139

So I assume this only works in the context of a window `GlobalScope`. 

Since all the service workers IDL interfaces are also available to workers, I think we should try to make the job queue also work for a worker global. 

We could try to do something similar as what is done with the [`MicrotaskQueue `](https://github.com/servo/servo/blob/f7d3d4a44762b3196c8dcbe58b628b5a23fc7833/components/script/microtask.rs#L28),

https://github.com/servo/servo/blob/f7d3d4a44762b3196c8dcbe58b628b5a23fc7833/components/script/dom/globalscope.rs#L196

 which is available on the `GlobalScope` in addition to being available on the `ScriptThread`, so that worker event-loops can also use it. 

https://github.com/servo/servo/blob/f7d3d4a44762b3196c8dcbe58b628b5a23fc7833/components/script/dom/abstractworkerglobalscope.rs#L147

Although to prevent a problem like https://github.com/servo/servo/issues/20908 we could try to just move the job queue entirely onto the global, and remove it from the script-thread, so functions like `run_job` and `schedule_job` could be made to take a `&GlobalScope` instead of a `&ScriptThread`.

**Comment by gterzian** [comment]
Ok I've taken a closer look at this, and although I'm still figuring a few things out, it appears to me that the goal if this issue is not so much to use a `GlobalScope` versus a `ScriptThread` in the various `JobQueue` operations, it might rather be breaking up the algorithms and data structure between "what is running in a script context" and "what is not", and moving some parts to the constellation, and the other parts would probably indeed belong best on the `GlobalScope` versus the `ScriptThread`(to make it work in all scopes). 

For example the concept of a [cope-to-registration-map)](https://w3c.github.io/ServiceWorker/#dfn-scope-to-registration-map), to me it appears this should be unique across the UA, in other words if different pages running in different `ScriptThread` look something up in it, they should see the same result. 

Currently we partition this map per `ScriptThread`, see https://github.com/servo/servo/blob/7b5ec99d25be61a7a3ec2f630c31a9f02c7b849b/components/script/script_thread.rs#L534

For example:

In [Register](https://w3c.github.io/ServiceWorker/#register-algorithm), we probably want to:

1. Run steps 1 to 3 " Reject Job Promise" in the global scope calling [avigator-service-worker-register](https://w3c.github.io/ServiceWorker/#navigator-service-worker-register).
2. Then step 4 "Get Registration", that actually should probably run at the constellation level. 
3. Same thing with "Set Registration"(run if there is no existing registration), at step 6.1
4. Finally, if the algorithm goes to the "Update" step 7, that's when we actually run a new `ServiceWorkerGlobalScope`, so again that's probably where the constellation would communicate with a `ServiceWorkerManager` for that origin to actually spin-up a new worker, and then back with the "client" `GlobalScope` as part of running "Install" with the new worker up and running(this queues some tasks back on an event-loop to fire events related to the update). 

So this is I think also about making a difference between DOM concepts like `ServiceWorker` and `ServiceWorkerRegistration`, which "point" to the actual thing that is either some data at the constellation level, or something running a `ServiceWorkerGlobalScope` in a service worker process. 

So for example there can be multiple DOM objects pointing to the same "thing", like a running worker or a registration. 

This requires some more looking into, and hopefully it can be broken up cleanly in issues or PR, but it could also get a bit messy...

**Comment by CYBAI** [comment]
@gterzian is there anything I can work on for this meta issue 👀 ?

**Comment by gterzian** [comment]
@CYBAI I think there will be lots of things to do but I'm sure what yet, currently still looking at the spec and the code. 

I'm pretty sure we need to move the JobQueue operations to run on the constellation or service worker manager for an origin, and callback into script where necessary, and have a bunch of data on the constellation or sw manager that would match various DOM objects, but I'm not sure yet how to do this. 

I also don't know how to break it up into issues yet, but I'll try to do so. Perhaps I'll start with some initial restructuring that opens the way for similar work on top of it...

**Comment by CYBAI** [comment]
@gterzian Thanks! I will read the spec and code first!

**Comment by gterzian** [comment]
By the way, this sort of confirms how the Job queue should be somewhere at the constellation or service worker manager level(probably the latter) https://github.com/w3c/ServiceWorker/issues/1224

**Comment by gterzian** [comment]
Ok here is a bit of an action plan for this:

1. I'd like to try an initial refactoring that would bring the "job queue" concept in line with the spec. This will require moving it out of the script-thread, and into an IPC based workflow involving the constellation and the service worker manager, with steps running back on script in the context of a global scope, by way of IPC routes. While it's "clear" to me what needs to be done, it's not clear in the sense that I can write it down clearly in an issue, hence I'd like to simply get my hands dirty and figure out the details while implementing the change. I think that refactoring can close this issue.
2. Once that initial refactoring is in place, I would hope that the "right" structure would be in place, so that we (cc @CYBAI) we simply start chipping away at the spec and failing tests. 

@jdm could you please let me know what you think of this?

**Comment by jdm** [comment]
Sounds reasonable!

**Comment by gterzian** [comment]
This is a good write-up on the ServiceWorker architecture in Chromium: https://chromium.googlesource.com/chromium/src/+/lkgr/content/browser/service_worker/README.md#renderer-process

Where you see written the "Browser process", you can substitute with the "Constellation and the ServiceWorkerManager", while the "Renderer process" is what happens in `script`(with the exception of `serviceworker_manager.rs`), and that covers both the actual `ServiceWorkerGlobalScope` running code "inside" the worker, and also other global scopes which are "clients" of the worker and use various WebIDL interfaces like `ServiceWorkerRegistration`, ``ServiceWorkerContainer`, and ``ServiceWorker`.
