### ISSUE TITLE
Handle detached arrays in XRView

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#26153]
There are a bunch of places in the WebXR spec where arrays are returned. If you call `.transfer()` on these, their buffers are "detached", and need to be recomputed. You can check if a buffer is detached by calling `is_null()` on it.

We handle most of these cases, except for [`XRView.projectionMatrix`](https://immersive-web.github.io/webxr/#xrview-obtain-the-projection-matrix)

We need to store the projection matrix on the XRView and use a null check in `ProjectionMatrix` to recompute it if necessary:

https://github.com/servo/servo/blob/5e91e48293406cebf6fef4ed03bcae568021c348/components/script/dom/xrview.rs#L83

**Comment by daemon1024** [comment]
Hi! I wanted to get started with contributing to servo and this issue was listed on [`Servo Starters`](https://starters.servo.org/). I am familiar with rust and I want to work on this issue.

>We handle most of these cases, except for XRView.projectionMatrix

Can you link me with a example where this case is already being handled, it will help me figure out what exactly I need to implement here!

**Comment by Manishearth** [comment]
@daemon1024 in all the other cases the array is lazy initialized so fetching it when it's null after detachment just reinitializes it

https://github.com/servo/servo/blob/5e91e48293406cebf6fef4ed03bcae568021c348/components/script/dom/xrrigidtransform.rs#L118

**Comment by daemon1024** [comment]
@Manishearth Thanks for reference. Got it now, will get started to work on it.

**Comment by daemon1024** [comment]
@highfive: assign me

**Comment by daemon1024** [comment]
From what I understood I need to initialise `self.proj` using `create_typed_array` with the underlying view's projection matrix as source.

Underlying view can be referenced as `self.view` but no field of proj/projectionmatrix/projections exists in `self.view`. 

Also view field in the struct XRView is Heap here, I think it should be of the type `webxr_api::View` for me to be able to reference the property.

@Manishearth ,can you assist me with where am I going wrong?

**Comment by Manishearth** [comment]
Yes, you need to copy the projection matrix into the XRView as a new field during construction.

You still need the Heap to be able to make the array.

**Comment by daemon1024** [comment]
Logically it should be something like this i guess 

> if self.proj.get().is_null() {
            let cx = self.global().get_cx();
            let projsrc = self.view.projection;
            create_typed_array(cx, &projsrc, &self.proj);
        }

But I can't seem to figure how access the projection matrix source ( `projsrc` here ) that i need to copy.

**Comment by Manishearth** [comment]
You have `view` in `new`, you should copy out `view.projection` and store it on a field.

**Comment by daemon1024** [comment]
I added a new field as u suggested 

>pub struct XRView {
      ....
      `viewsrc: &'static [f32],`
      }

I tried to store it out from `new()` using 

> let projm = view.projection.to_row_major_array();
   let ret = reflect_dom_object(
            Box::new(XRView::new_inherited(session, &transform, eye, `&projm` )), global, );

But I am getting an error 
>borrowed value does not live long enough
   |                                                                      cast requires that `projm` is borrowed for `'static`

I am not sure how else do I copy it out.

**Comment by Manishearth** [comment]
It needs to be a `Vec<f32>`, you can't hold on to borrowed slices there

**Comment by daemon1024** [comment]
@Manishearth Thank You so much for the help, I have made the required changes and made a PR. Can you please review it?
