### ISSUE TITLE
Navigation doesn't work after leaving immersive mode

### ISSUE THREAD

**Issue by jdm** [servo/servo#26162]
STR:
1. visit any demo from the https://servo.org/hl-home/ homepage
1. enter immersive mode
1. use the context menu to leave immersive mode
1. press the home button

Something broke this recently, since I have definitely successfully gone back in history in previous builds.

**Comment by jdm** [comment]
The "Enter VR" button also doesn't change its state in a useful way. I have a suspicion that https://github.com/servo/servo/pull/26077 may be related.

**Comment by jdm** [comment]
I can't reproduce this problem on desktop using the glwindow backend.

**Comment by Manishearth** [comment]
I'm on commit e691e42d58f6b0f29aa5c09abdc6b669f53408b0, with the preview runtime disabled. It seems to be working, or at least the back button is.

**Comment by Manishearth** [comment]
oh, nope, got it to happen.

seems to be non deterministic

**Comment by Manishearth** [comment]
this looks like the main thread is asleep. the canvas dirtying could be why but that wouldn't explain embedder buttons not working

**Comment by Manishearth** [comment]
Yeah, it's that patch. Perhaps I should deliberately dirty something and trigger relayout when the session exits.

**Comment by Manishearth** [comment]
cc @asajeffrey my impression is that basically the main thread goes to sleep and nothing wakes it up. I'm surprised that the embedder buttons don't work when the main thread is asleep (cc @paulrouget?)

I guess the right fix is to forcibly dirty the canvas, we need to do that anyway

**Comment by jdm** [comment]
The embedder buttons cause events to be queued that the servo event loop will run the next time it's woken up. I guess if the page isn't animating in any way and the compositor isn't being poked by webrender submitting a new rendered frame, the event loop has nothing to prod it.

**Comment by jdm** [comment]
This would _probably_ not be an issue if we separated the compositor from the is main thread like @asajeffrey keeps wanting to do?

**Comment by asajeffrey** [comment]
I'd push harder on moving WR off the main thread, except that AFAIK it requires an extra blit.

**Comment by Manishearth** [comment]
@jdm how does tapping the page not wake up the main thread either, then?

Basically, it's unclear to me why this bug won't also occur on a page with a simple onclick handler and no other dynamic content. Should embedder events be waking up the main thread?

**Comment by asajeffrey** [comment]
> Basically, it's unclear to me why this bug won't also occur on a page with a simple onclick handler and no other dynamic content. Should embedder events be waking up the main thread?

They should. Are we not getting events from the OS when returning from immersive mode?

**Comment by Manishearth** [comment]
We get events from the OS if I mark the canvas as dirty.

**Comment by jdm** [comment]
I have found that returning to the home screen via the MS menu while in immersive mode from https://servo.org/hl-home/bbjs/#clouds.js can cause this state to occur.

**Comment by jdm** [comment]
More specifically, with #26164 applied I can reproduce the issue by:
* loading https://servo.org/hl-home/bbjs/#clouds.js
* looking at my palm and exiting the immersive mode
* reactivating the app and re-entering the immersive mode
* using the windows menu to return to the home screen

When I activate the app after the last step, it is in the mode where interacting with the UI does nothing and the content isn't being updated.

**Comment by jdm** [comment]
Setting various breakpoints, the main thread is clearly continuing to process Servo events - it receives a notification that navigation took place, and the URL should have changed. Hovering over the "Enter VR" button in this state also causes it to animate, event though the icon doesn't appear over it. I'm really not sure what to make of it.

**Comment by jdm** [comment]
I can still reproduce this in a nightly build.
