### ISSUE TITLE
Can't re-enter immersive mode from home screen after using palm gesture

### ISSUE THREAD

**Issue by jdm** [servo/servo#26179]
STR:
* Run https://threejs.org/examples/webxr_vr_ballshooter.html
* enter immersive mode
* use palm gesture to leave immersive mode
* activate app, enter immersive mode again
* use home button to return to home screen
* activate app

Expected:
* immersive mode is automatically entered

Actual:
* often, immersive mode is not entered and the page shows "Exit VR", so there's no way to re-enter immersive mode
* reloading the page via the Reload button works, but still can't enter immersive mode

**Comment by jdm** [comment]
I have also been able to reproduce this behaviour without involving the palm gesture, and just using the home button for the first time.

**Comment by jdm** [comment]
When I use the palm gesture and exit immersive mode in a debug build, I see this output:
```
RUST: WARN - webxr_api::session - Device stopped providing frames, exiting
The thread 0xaa0 has exited with code 0 (0x0).
ERROR (OpenXR) : Invalid XrSpace handle with value '24'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDF58.
ERROR (OpenXR) : Invalid XrSpace handle with value '28'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDF38.
ERROR (OpenXR) : Invalid XrAction handle with value '27'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDE18.
ERROR (OpenXR) : Invalid XrSpace handle with value '30'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDF38.
ERROR (OpenXR) : Invalid XrAction handle with value '29'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDE18.
ERROR (OpenXR) : Invalid XrAction handle with value '31'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDE58.
ERROR (OpenXR) : Invalid XrAction handle with value '32'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDE58.
ERROR (OpenXR) : Invalid XrSpace handle with value '34'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDF38.
ERROR (OpenXR) : Invalid XrAction handle with value '33'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDE18.
ERROR (OpenXR) : Invalid XrSpace handle with value '36'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDF38.
ERROR (OpenXR) : Invalid XrAction handle with value '35'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDE18.
ERROR (OpenXR) : Invalid XrAction handle with value '37'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDE58.
ERROR (OpenXR) : Invalid XrAction handle with value '38'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDE58.
ERROR (OpenXR) : Invalid XrActionSet handle with value '26'. Handle has already been destroyed.
Exception thrown at 0x00007FF98F139B4C in ServoApp.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x000000BDB1DFDD58.
```
This makes me wonder if we're brekaing something internally.

**Comment by Manishearth** [comment]
Yeah I saw those as well, it's probably because we're manually destroying the session and instance. I was told that it is okay to destroy them manually.

Might be worth trying to:

 - comment out the session destroy code in the impl of `Drop` for `OpenXRDevice`
 - comment out the entire `Drop` impl (last i checked this breaks session exiting)

**Comment by jdm** [comment]
Commenting out https://github.com/servo/webxr/blob/0d9c83f333920b98d95adf9666b0a365258990a3/webxr/openxr/mod.rs#L98 did not change either the error output, or the weird state.

**Comment by Manishearth** [comment]
What about both? if exiting works with both removed we should get rid of the Drop impl anyway

**Comment by jdm** [comment]
Actually it looks like commenting it out (or both) puts us in a weird exiting state when the content disappears, then I need to use the home button to actually get back to the home screen.

**Comment by Manishearth** [comment]
@jdm yeah that's what i expected. are the console errors still appearing?

Basically, you need to destroy the instance/session to exit. However, the instance doesn't seem to get destroyed manually (it's reference counted in openxrs, a reference is being held somewhere) so you get the weird exiting state. We're now dropping it, but we're dropping it before any of the other subfields of OpenXRDevice get dropped, which is probably what's spawning those errors. But i was told this would be okay.

Ideally we can find out why the destructor never gets called. this might involve  finding the extra references. by patching openxrs.

**Comment by jdm** [comment]
This was fixede.
