### ISSUE TITLE
Linux Nightly Build is missing libgstwebrtc-1.0.so.0

### ISSUE THREAD

**Issue by hey-i** [servo/servo#26180]
I downloaded the linux nightly build from https://download.servo.org/ and followed the instructions to run it, but got the following error:

> ./servo: error while loading shared libraries: libgstwebrtc-1.0.so.0: cannot open shared object file: No such file or directory

This problem was first mentioned here https://github.com/servo/servo/issues/21778#issuecomment-492837438 where he says that the library is only available in debian sid. Another person brought it up here https://github.com/servo/servo/issues/23684 but they were sent to another issue related to compiling. I don't really want to compile it :(

I installed libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev but it didn't help.

**Comment by jaimiewashere** [comment]
Quick note, I managed to find `libgstreamer-plugins-bad1.0-0` helpful, the `-dev` packages didn't really help me either.

**Comment by cristianovitorino** [comment]
For anyone having trouble running on Ubuntu 22.04:

```
sudo apt install libgstreamer-plugins-bad1.0-0

wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
```

Reference: [Ubuntu 22.04 | libssl.so.1.1: cannot open shared object file: No such file or directory](https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di)

**Comment by dyaskur** [comment]
correct libssl URL
```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb

sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
```

ref: https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

**Comment by pegvin** [comment]
correct libssl URL
```
https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```

**Comment by mrobinson** [comment]
I think we list runtime dependencies in the README now.
