### ISSUE TITLE
hard dependency on X11, when running on Wayland

### ISSUE THREAD

**Issue by okias** [servo/servo#26208]
after download of servo-latest.tar.gz (2020-04-17) I got:

```./servo: symbol lookup error: ./servo: undefined symbol: gst_gl_display_x11_new_with_display```

It seems that it won't run on Wayland-only stack, while Firefox has no issues and is 100% functional.

**Comment by jdm** [comment]
This is either a limitation of how we build Servo and the gstreamer backend, or an incompatibility between the version of gstreamer that we build with versus the one you have installed.

**Comment by okias** [comment]
rebuilding `media-libs/gst-plugins-base` with `X` use flag resolves issue on Gentoo.

Correct solution would be for Servo to detect on which protocol/server it does run and use appropriate **GstGLDisplayX11** or **GstGLDisplayWayland** (which isn't used currently on Wayland setups).

**Comment by jdm** [comment]
Upgrading to a gstreamer version that incorporates https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/commit/dd5f7f1b might help. However that may still require choosing x11 or wayland support at build time.

**Comment by SimonSapin** [comment]
Yes the current code does have a hard dependency on X11 *libraries* being available at build-time (and probably at run-time, `ldd target/release/servo` on my local build includes `libX11.so.6`). But a X11 *server* shouldn’t need to be running if you use Wayland.

Firefox on Gentoo seems to be the same: https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/firefox-83.0.ebuild#n136

It looks like someone went through the effort of adding conditional compilation to gstreamer to make X11-related code (and the dependency on relevant libraries) optional, but similar work hasn’t been done for Firefox or Servo.

> rebuilding `media-libs/gst-plugins-base` with `X` use flag resolves issue on Gentoo.

Closing as resolved based on this.
