### ISSUE TITLE
Automatically disable texture swizzling on incompatible graphics drivers

### ISSUE THREAD

**Issue by anohren** [servo/servo#26224]
I'm not sure what's supposed to happen when launching the nightly on macOS. This is what I see:

![Skärmavbild 2020-04-19 kl  17 58 11](https://user-images.githubusercontent.com/3519879/79692788-6078e700-8267-11ea-8fcc-0bdf520aabcf.png)

What should I expect it to look like on macOS?

MacOS 10.14.6
Macbook air 2012, intel hd 4000

**Comment by jdm** [comment]
There are supposed to be fonts and images showing up; it loads https://servo.org/ by default. That's a surprising result!

**Comment by anohren** [comment]
Thanks. It's not easy to know what to expect the first launch when you're not familiar with how far along a project is.

Sometimes I get black raindrops that I suppose text and images would look like when travelling at lightspeed:

![Skärmavbild 2020-04-19 kl  19 05 39](https://user-images.githubusercontent.com/3519879/79694537-1ac11c00-8271-11ea-8f13-e5fefc0f6328.png)

I downloaded the nightly a few minutes before creating this issue. I got the exact same result a few months ago when I downloaded the nightly build for the very first time, but dismissed it as not being prioritized for macOS.

**Comment by jdm** [comment]
Oh, I bet you're running into https://bugzilla.mozilla.org/show_bug.cgi?id=1570736#c32. If you launch the nightly with `open ServoNightly.app --args --pref gfx.texture-swizzling.enabled=false` (or whatever the .app file is called), do the fonts appear?

**Comment by anohren** [comment]
Yes, that seems to fix it. The page renders with text and images. The intel drivers are defective in this way only on macOS if I understood correctly.

**Comment by mrobinson** [comment]
I think this is fixed in upstream WebRender which we have upgraded to, so I'm going to close this one as there's no way to verify it without the right hardware. Feel free to reopen if this issue still persists.
