### ISSUE TITLE
Insert padding to find structures whose size has a large perf effect

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#2623]
Patrick and I were talking about why exactly Servo's layout is so fast. One possibility is that it's a benefit of having small structs. These will get bigger as we support more layout features.

We could experiment now with inserting varying amounts of padding into various Servo datastructures and benchmark for both space and time.  This will help guide future designs.

**Comment by nox** [comment]
@pcwalton We more or less know what must be small now, right?

**Comment by pcwalton** [comment]
Yeah, let's close this.
