### ISSUE TITLE
Rename glutin port?

### ISSUE THREAD

**Issue by atouchet** [servo/servo#26236]
Glutin was removed in #25853 but it is still used for the name of the port. Presumably this should be changed to something more accurate now?

**Comment by SimonSapin** [comment]
Winit port is probably the appropriate name now.

**Comment by Darkspirit** [comment]
Does tinyfiledialogs work on Android? Otherwise I'd suggest "desktop".

**Comment by paulrouget** [comment]
I'd rather go for winit.

The UWP port works on Desktop for example, but it doesn't use winit.
