### ISSUE TITLE
Selectors 4?

### ISSUE THREAD

**Issue by Boscop** [servo/servo#26263]
Would it be possible to add support for selectors level 4 in the `selectors` crate?
E.g.
`tr:nth-last-child(1 of :not(.table_vert_controls))`
https://www.w3.org/TR/selectors-4/#the-nth-last-child-pseudo

https://css-tricks.com/css-nth-of-class-selector/

**Comment by SimonSapin** [comment]
There are a lot of new features in Selectors Level 4, so I’ll assume this is about adding support for the `of <selector>` in `:nth-child` and `:nth-last-child`.

See also the Firefox bug for this feature: https://bugzilla.mozilla.org/show_bug.cgi?id=854148

For anyone interested in contributing to this, at least these parts of the code would need to be extended:

* Data structures:
  https://github.com/servo/servo/blob/e6b3090f38b9d324553f01449aa5c7cc69f4f53c/components/selectors/parser.rs#L932-L935
* Parsing:
  https://github.com/servo/servo/blob/e6b3090f38b9d324553f01449aa5c7cc69f4f53c/components/selectors/parser.rs#L2180-L2183
  https://github.com/servo/servo/blob/e6b3090f38b9d324553f01449aa5c7cc69f4f53c/components/selectors/parser.rs#L2201-L2211
* Serialization:
  https://github.com/servo/servo/blob/e6b3090f38b9d324553f01449aa5c7cc69f4f53c/components/selectors/parser.rs#L1438-L1448
* Matching / tree traversal:
  https://github.com/servo/servo/blob/e6b3090f38b9d324553f01449aa5c7cc69f4f53c/components/selectors/matching.rs#L832-L837
  https://github.com/servo/servo/blob/e6b3090f38b9d324553f01449aa5c7cc69f4f53c/components/selectors/matching.rs#L884

**Comment by emilio** [comment]
FWIW, `:is()` and `:where()` have patches in progress in https://bugzilla.mozilla.org/show_bug.cgi?id=1509418

**Comment by zrhoffman** [comment]
Gecko is shipping `:nth-child(An+B of <selector list>)` and `:nth-last-child(An+B of <selector list>)`.

https://groups.google.com/a/mozilla.org/g/dev-platform/c/eQeeFKYJ038

**Comment by mrobinson** [comment]
In think this issue is better tracked in Gecko.
