### ISSUE TITLE
[hololens] Objects appears inside walls and ceiling

### ISSUE THREAD

**Issue by Yonet** [servo/servo#26297]
Placement of the objects in examples seemed to be off: https://servo.org/hl-home//.
Objects appear inside walls and sizes look too big, some half my size. See the video for example.
Click events work great!
https://youtu.be/FVqw_qUG4Gc

**Comment by jdm** [comment]
That's expected behavior, unfortunately. There are no web APIs for exposing real-world geometry to web content, so all rendering and posituining decisions are effectively arbitrary.
