### ISSUE TITLE
Remove @viewport.

### ISSUE THREAD

**Issue by emilio** [servo/servo#26349]
There's a fairly complex setup to support `@viewport` rules but they were removed from the spec, see https://github.com/w3c/csswg-drafts/issues/4766.

So we should remove all that code, except for the fact that Servo uses a dummy `@viewport` rule for `<meta name="viewport">`, so that should be rewritten first.

**Comment by shubhamg13** [comment]
Are we not going to support viewport meta tag in Servo?

**Comment by mrobinson** [comment]
> Are we not going to support viewport meta tag in Servo?

Yes, that's the plan.

**Comment by shubhamg13** [comment]
Isn't it W3C standard? Is there any specific reason for not supporting it?

**Comment by kongbai1996** [comment]
The standard just removes the use of @Viewport. The viewport in the meta tag needs to be parsed and stored.
Do we have a plan to support? This may be a new issue.

**Comment by mrobinson** [comment]
Sorry. "Are we not" is also a way of asking if you are going to do something and my reply was ambitious. To clarify yes, the plan is to support viewport. This change does not affect that though. It only removed `@viewport`.
