### ISSUE TITLE
Allocate short-lived JS objects in the nursery

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#26355]
For objects that we believe will be short-lived, we should allocate them in the nursery rather than tenured.

**Comment by asajeffrey** [comment]
Spidermonkey has a `JSCLASS_SKIP_NURSERY_FINALIZE` flag for this, which is controlled by the `[ ProbablyShortLivingWrapper]` webidl attribute in gecko. https://searchfox.org/mozilla-central/rev/7fd1c1c34923ece7ad8c822bee062dd0491d64dc/dom/bindings/Codegen.py#574

**Comment by asajeffrey** [comment]
This is particularly relevant to webxr, which generates objects every rAF. (c.f. https://github.com/servo/servo/pull/26195 and https://github.com/immersive-web/webxr/issues/1010).

**Comment by jdm** [comment]
There's a bunch of information in #10418; not sure how we want to de-duplicate this.

**Comment by jdm** [comment]
Events are another good set of interfaces to consider for the extended attribute.

**Comment by asajeffrey** [comment]
Ah, let's do the conversation in #10418.
