### ISSUE TITLE
./mach bootstrap does not support Ubuntu 20.04

### ISSUE THREAD

**Issue by complexengine** [servo/servo#26350]
./mach bootstrap does not support Ubuntu 20.04
Output:

`Exception: unsupported version of Ubuntu: 20.04`

**Comment by Darkspirit** [comment]
I couldn't compile the script crate because [lex.py](https://github.com/dabeaz/ply) (used by [WebIDL.py](https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/parser/WebIDL.py)) doesn't seem to work with python3.8:
```
   Compiling gfx-backend-vulkan v0.4.0
   Completed gfx-backend-vulkan v0.4.0 in 5.0s
   Compiling gfx-backend-empty v0.4.0
   Completed gfx-backend-empty v0.4.0 in 0.4s
   Compiling rendy-descriptor v0.5.1
   Completed rendy-descriptor v0.5.1 in 1.5s
   Completed selectors v0.22.0 custom-build (run) in 0.0s
error: failed to run custom build command for `script v0.0.1 (/home/ci/actions-runner/_work/servo/servo/components/script)`

Caused by:
  process didn't exit successfully: `/home/ci/actions-runner/_work/servo/servo/target/debug/build/script-edae67a18af7c921/build-script-build` (exit code: 1)
--- stderr
./parser/WebIDL.py:5481: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  raise WebIDLError("[CrossOriginCallable] is only allowed on non-static "
Traceback (most recent call last):
  File "dom/bindings/codegen/run.py", line 119, in <module>
    main()
  File "dom/bindings/codegen/run.py", line 28, in main
    parser.parse(f.read(), filename)
  File "./parser/WebIDL.py", line 7562, in parse
    self._productions.extend(self.parser.parse(lexer=self.lexer, tracking=True))
  File "./ply/ply/yacc.py", line 263, in parse
    return self.parseopt(input,lexer,debug,tracking,tokenfunc)
  File "./ply/ply/yacc.py", line 649, in parseopt
    lookahead = get_token()     # Get the next token
  File "./ply/ply/lex.py", line 313, in token
    if lexdata[lexpos] in lexignore:
TypeError: 'in <string>' requires string as left operand, not int

warning: build failed, waiting for other jobs to finish...
   Completed webrender_api v0.61.0 in 21.4s
   Completed backtrace-sys v0.1.36 custom-build (run) in 239.6s
   Completed mozangle v0.2.7 custom-build (run) in 266.2s
error: build failed
[Warning] Could not generate notification! 
Build FAILED in 0:08:33
```

**Comment by r1walz** [comment]
@complexengine Editing [this](https://github.com/servo/servo/blob/master/python/servo/bootstrap.py#L355) line will help you at least compile servo on Ubuntu 20.4.

**Comment by complexengine** [comment]
@r1walz I did that and started building servo but the build is stuck at compiling the script crate. I gave it 3 hours and still no visible progress. Was your build stuck like mine?

**Comment by jdm** [comment]
The script crate is the largest one and consumes ~8gb of ram in my experience. Three hours is longer than I've ever seen that take, however.

**Comment by complexengine** [comment]
Finally, I got it compiled!

**Comment by CYBAI** [comment]
@complexengine it might be worth sending a PR to support compiling Ubuntu 20.04 👀?

**Comment by r1walz** [comment]
@complexengine Are you using wayland or xorg drivers? Were you able to load a page? see #26353

**Comment by complexengine** [comment]
@CYBAI My PR:- https://github.com/servo/servo/pull/26359

**Comment by complexengine** [comment]
@r1walz I was able to load pages. My Xorg driver:

`00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
	DeviceName:  Onboard IGD
	Subsystem: Lenovo Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
	Kernel driver in use: i915`

**Comment by r1walz** [comment]
@complexengine Oh! I see. But are you not using a dedicated GPU, such as from Nvidia or AMD? I'm facing problem on Nvidia's GPU using Xorg drivers. I can't disable dedicated GPU as I want to work on the graphics handling part (using webgpu or related APIs). Thanks for everything!

**Comment by Darkspirit** [comment]
I don't get a build error on my Gaming Ubuntu. However, I see #26353 as well. I don't know if it's related to proprietary Nvidia drivers.
