### ISSUE TITLE
Panic handling console message from devtools JS evaluation after navigation

### ISSUE THREAD

**Issue by jdm** [servo/servo#26367]
STR:
1. run devtools with https://servo.org/hl-home/
1. connect to devtools from firefox
1. visit particles demo
1. run console.log("hi") from JS console

No "hi" appears in the JS console, and the devtools thread panics when processing the message event.

**Comment by Taym95** [comment]
this is not happening anymore in latest main branch.

**Comment by jdm** [comment]
Thanks!
