### ISSUE TITLE
How to determine Git commit corresponding to nightly build?

### ISSUE THREAD

**Issue by atouchet** [servo/servo#26374]
This is more of a question than an issue report but how can you determine what commit corresponds to a specific Servo nightly build? I used to be able to look at the Buildbot page and see it listed there (ex. https://build.servo.org/builders/windows-msvc-nightly/builds) but I am unsure of how to find this info after the switch to Taskcluster.

**Comment by jdm** [comment]
Look for the listings in https://treeherder.allizom.org/#/jobs?repo=servo-master that have "Nightly".

**Comment by atouchet** [comment]
Alright. Just to confirm I'm reading this correctly the 2020-04-30T09:04:31Z-Servo.zip nightly build for example would be based on 3bedd440265864bc713b4f3d620b65cfc58b7381 then?

**Comment by jdm** [comment]
Yep!
