### ISSUE TITLE
Treat referrerpolicy attribute as a "relevant mutation" for image elements

### ISSUE THREAD

**Issue by jdm** [servo/servo#26388]
Spec change: https://github.com/whatwg/html/pull/5434
Tests: https://github.com/web-platform-tests/wpt/pull/23309
Code: https://github.com/servo/servo/blob/64dee1fa116870eb76c3b8b54090afce9c4d1d13/components/script/dom/htmlimageelement.rs#L1592-L1599

We should hopefully see new test results if we run `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/relevant-mutations.html` after adding the attribute to the list of attributes that cause the image data to be updated.

**Comment by PeterZhizhin** [comment]
@highfive: assign me
