### ISSUE TITLE
Write a macro to generate namespaced Ids

### ISSUE THREAD

**Issue by gterzian** [servo/servo#26380]
We have a bunch of Indexes and Ids in `components/msg/constellation_msg.rs`, see for example the `BrowsingContextIndex` and `BrowsingContextId` https://github.com/servo/servo/blob/1b4162aecbb935c8183438c3d6bc285db3932476/components/msg/constellation_msg.rs#L263

I find myself manually adding new ones regurlarly by hand, perhaps someone wants to write a macro for this? See for example the changes to this file: https://github.com/servo/servo/pull/26317/files#diff-8dc9268416cd4f037d50206e76c73cf9

I'd be great if we could just do something along the lines of `namespaced_id!(ServiceWorkerId)`.

Note that each also require implementing a method on `PipelineNamespace`, which I guess will have to be done by hand(unless someone has a better idea). 

I don't have much, if any, experience writing macros, but I'll venture ahead with a "less easy" label...

**Comment by AbhishekSharma102** [comment]
Hey @gterzian, I am new to rust and would like to work on this. Please let me know if no one else is working on this.

**Comment by gterzian** [comment]
It's not assigned to anyone, so you can do it if you like!
