### ISSUE TITLE
Add InRealm arg to Promise::append_native_handler

### ISSUE THREAD

**Issue by gterzian** [servo/servo#26392]
Calling [`Promise::append_native_handler`](https://github.com/servo/servo/blob/d08c4fff15cb5f6a8840621e848c9de22fcc3439/components/script/dom/promise.rs#L245) requires having entered a realm already, so I think we could add an explicit [`InRealm`](https://github.com/servo/servo/blob/d08c4fff15cb5f6a8840621e848c9de22fcc3439/components/script/realms.rs#L30) argument to the method.

See for example how this is done here: https://github.com/servo/servo/blob/d08c4fff15cb5f6a8840621e848c9de22fcc3439/components/script/script_runtime.rs#L247

and here(using a global):
https://github.com/servo/servo/blob/d08c4fff15cb5f6a8840621e848c9de22fcc3439/components/script/script_module.rs#L324

**Comment by gterzian** [comment]
Actually, it might be that it's an `AutoIncumbentScript` that is required. 

The failure I got was:

```
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }"
  │ stack backtrace:
  │    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  │    1: core::fmt::write
  │    2: std::io::Write::write_fmt
  │    3: servo::backtrace::print
  │    4: servo::install_crash_handler::handler
  │    5: _sigtramp
  │    6: _ZN2js29NewObjectWithClassProtoCommonEP9JSContextPK7JSClassN2JS6HandleIP8JSObjectEENS_2gc9AllocKindENS_13NewObjectKindE
  │    7: _ZN2js20NewFunctionWithProtoEP9JSContextPFbS1_jPN2JS5ValueEEj13FunctionFlagsNS2_6HandleIP8JSObjectEENS8_IP6JSAtomEESB_NS_2gc9AllocKindENS_13NewObjectKindE
  │    8: _ZN2js23NewFunctionWithReservedEP9JSContextPFbS1_jPN2JS5ValueEEjjPKc
  │    9: script::dom::promise::create_native_handler_function
  │   10: script::dom::promise::Promise::append_native_handler
  │   11: <T as script::task::TaskBox>::run_box
  │   12: script::script_thread::ScriptThread::handle_msg_from_script
  │   13: _ZN6script13script_thread12ScriptThread11handle_msgs17h02cbc886847ae83dE.llvm.7834366120276770206
  │   14: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  │   15: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │   18: std::sys::unix::thread::Thread::new::thread_start
  │   19: _pthread_body
  └   20: _pthread_start

```

**Comment by jdm** [comment]
Crashes like that usually indicate that a realm is required.

**Comment by gterzian** [comment]
Ok, then I think the suggestions in the initial comment can be followed, and it should not be super hard(tempted to re-add the "less easy" label). 

I guess the reason why this came up as part of https://github.com/servo/servo/pull/25873, is because that is the first place where a native promise handler is added to a promise, from inside a callback on a promise...
