### ISSUE TITLE
Update winit

### ISSUE THREAD

**Issue by atouchet** [servo/servo#26394]
Servo is currently using an outdated version of winit. There was a WIP PR to update Glutin/winit in #25480.

**Comment by Darkspirit** [comment]
No push was made to #26256. It was closed instead.

**Comment by atouchet** [comment]
@Eijebong appears to be doing some work on this.

https://github.com/servo/surfman/pull/179
https://github.com/Eijebong/servo/tree/winit

**Comment by jdm** [comment]
I-cleanup seems fine to me.

**Comment by nicoabie** [comment]
@highfive: assign me

**Comment by jdm** [comment]
I've resurrected eijebong's branch on https://github.com/jdm/servo/tree/winit.

Known issues:
* [ ] resizing the window deadlocks the app

**Comment by philip-lamb** [comment]
There's also a package version conflict in the current `master`. `surfman` specifies `winit<0.19.4` (https://github.com/servo/surfman/blob/master/surfman/Cargo.toml#L47) which results in Cargo selecting 0.18.1, whereas `ports/winit` specifies winit=0.19 (https://github.com/servo/servo/blob/master/ports/winit/Cargo.toml#L63) which results in Cargo selecting 0.19.5 and which bombs during linking due to the differing version numbers.

**Comment by jdm** [comment]
How does this conflict manifest? The head revision builds fine on CI and locally.

**Comment by philip-lamb** [comment]
Using `Cargo.lock` from master, both `surfman` and `ports/winit` select `winit:0.19.3`. But I think what is happening in my local branch at some point I did a `cargo update`, and so locally cargo sees `winit:0.19.5` as the most recent in the 0.19 series, and so surfman's request for `winit<0.19.4` results in it using the last in the 0.18 series. I suppose I can work around it by pinning the version for both. I guess that surfman's avoidance of winit 0.19.4 and later needs to be re-tested.

**Comment by jdm** [comment]
Yeah, surfman can use 0.19.5 just fine; it's only 0.19.4 that needs to be avoided.

**Comment by okias** [comment]
Update winit would unblock Servo on Wayland running desktop at least trough XWayland. Currently it dies even when run in legacy X11 / XWayland mode.

**Comment by jdm** [comment]
There's extremely promising progress happening in https://github.com/servo/servo/pull/28236. I think we might actually resolve this finally.
