### ISSUE TITLE
Support the babylon playground

### ISSUE THREAD

**Issue by jdm** [servo/servo#26428]
We should identify what's missing in our implementation to support the babylon playground, which is a common way for developers to experiment with new content.

**Comment by jdm** [comment]
```
[2020-05-05T16:22:31Z ERROR script::dom::bindings::error] Error at https://playground.babylonjs.com/node_modules/monaco-editor/dev/vs/editor/editor.main.js:1:1382084 document.queryCommandSupported is not a function
```
Running with a user script that adds `document.queryCommandSupported = function() { return false };` causes the webgl canvas to appear, and maximizing the window causes the full code + canvas view to render. All of the button images are missing because they are SVGs.

**Comment by jdm** [comment]
Keyboard input is hitting https://github.com/servo/servo/issues/25478:
```
[2020-05-05T16:33:03Z ERROR script::dom::bindings::error] Error at https://playground.babylonjs.com/js/main.js:146:223 event is not defined
```

**Comment by jdm** [comment]
One thing to note is that loading a playground link with `full.html` loads perfectly fine, and is probably what is actually desirable when trying out content on a device.

**Comment by RaananW** [comment]
The babylon playground is using the monaco code editor (https://www.npmjs.com/package/monaco-editor) and has every available babylon feature available. I also believe that `full.html` would be the right way to go. Having said that, maybe we can do something on our side. We could for example detect that a certain feature is not available (like the function you mentioned) and not initialize the editor.
