### ISSUE TITLE
Ability to toggle prefs on Hololens

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#26445]
It would be nice to be able to set prefs (at least, from a reduced list of prefs, if not arbitrary ones) on the Hololens. Even better if we can make the prefs persist by editing an on-disk prefs.json (which is currently [hardcoded in the binary](https://github.com/servo/servo/blob/master/ports/libsimpleservo/api/src/lib.rs#L918)).

Initially it might just be worth exposing a couple high-value prefs like `dom.webxr.hands.enabled` and `dom.webgl2.enabled`.

If we're doing a limited set of prefs we can also just persist the settings for those prefs.

cc @paulrouget

**Comment by paulrouget** [comment]
I'll look into this.
