### ISSUE TITLE
Implement referrerPolicy IDL attribute for HTMLScriptElement and HTMLLinkElement

### ISSUE THREAD

**Issue by jdm** [servo/servo#26454]
Spec:
* https://html.spec.whatwg.org/multipage/scripting.html#dom-script-referrerpolicy
* https://html.spec.whatwg.org/multipage/semantics.html#dom-link-referrerpolicy

**Comment by nosark** [comment]
I would like to work on this issue please

**Comment by jdm** [comment]
@nosark Great! This will require updating the webidl files for both interfaces to add the missing IDL attribute, then implementing the getters and setters for both HTMLScriptElement and HTMLLinkElement. For the getters you will want to extract [the first few lines](https://github.com/servo/servo/blob/79b6758cb91985245a79824fb1983fe3af4b11fb/components/script/dom/element.rs#L3700-L3702) of `referrer_policy_for_element` into a helper function, and the setters can use the `make_setter!` macro like any other string-reflecting attribute. Finally, code like [this](https://github.com/servo/servo/blob/14464e49beb98de7aaa764d84c2e2175aaf48bbb/components/script/dom/htmlscriptelement.rs#L353) for each element should call `referrer_policy_for_element` so that the proper values are used.

**Comment by nosark** [comment]
@jdm Okay, awesome! Thank you!

**Comment by nahuakang** [comment]
Per Josh's recommendation I'll take a look and attempt to work on it.

**Comment by nosark** [comment]
Sorry guys, I've been super busy with work and haven't had as much time for open source and I'm still working on #24659 currently.

**Comment by devmedoo** [comment]
Hi, I'm a beginner of Rust and Servo but I really like both projects. Hope this can help. I basically followed jdm's comment except for the last step as it seems like it may not be necessary anymore (unsure).
