### ISSUE TITLE
Rotating squares in the background in twgljs.org is not rendered

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#26459]
While checking https://twgljs.org/ on Firefox, we can see many squares rotating in the background but, in Servo, we can only see a blue background without rotating squares.

| Servo | Firefox |
| --- | --- |
| <img width="1680" alt="image" src="https://user-images.githubusercontent.com/6782666/81253090-9b01c280-9062-11ea-9b76-9f61b16a7bce.png"> | <img width="1680" alt="image" src="https://user-images.githubusercontent.com/6782666/81254328-c6d27780-9065-11ea-9313-ce7ff26e2088.png"> |

Built with latest master (5ee1a48d82) on macOS 10.14.6

**Comment by atouchet** [comment]
I am able to reproduce this issue in Windows 10 in the latest nightly build.

**Comment by jdm** [comment]
Here's a minimal testcase:
```
<div style="position: fixed; width: 100px; height: 100px; z-index: -1; background-color: green"></div>
```
If we don't use position fixed or z-index, the green box appears. In Layout 2013 this shows a blank page. In layout 2020 we see a green box, but I still don't see the background canvas on the original website.

**Comment by jdm** [comment]
Here's a minimal testcase for layout 2020:
```html
<html>
<style>
html {
  background-color: blue
}
#frame {
  background-color: rgb(0, 0, 0, 0.7);
  color: #ddd;
}
#background {
  position: fixed;
  width: 100px;
  height: 100px;
  z-index: -1;
  background-color: green;
}
</style>
<div id="background"></div>
<div id="frame">hi</div>
```

**Comment by mrobinson** [comment]
I believe that fixing this depends on #26121.

**Comment by jdm** [comment]
The background squares now appear in layout 2020, presumably because of #26414.
