### ISSUE TITLE
Layout 2020 in nightly builds

### ISSUE THREAD

**Issue by atouchet** [servo/servo#26489]
Is it possible to run Layout 2020 in Servo nightly builds? If so how do you enable it?

**Comment by jdm** [comment]
It is not, since it's a build time configuration. However it might make sense to start publishing layout 2020 nightly (or at least weekly) when we're ready for wider testing but not prepared to make it the default yet.

**Comment by atouchet** [comment]
Has the status of this changed? I saw #29950 referenced making Layout 2020 a runtime option.

**Comment by mrobinson** [comment]
For a little while now we have shipped the default nightly build with layout 2020 and one for layout 2013. Now a single binary will include both, and you can use the old layout system using the '--legacy-layout' flag.
