### ISSUE TITLE
Linux nightly builds are named incorrectly

### ISSUE THREAD

**Issue by jdm** [servo/servo#26522]
From matrix: `By the way, it seems that mach is naming the Linux .tar.gz file just .gz even though it's a tar, and the download page links to .tar.gz.`

This is almost certainly a regression from https://github.com/servo/servo/pull/26207/commits/03e6787bf912a143ba097eeb58f7be16b8337d83.

**Comment by camelid** [comment]
Can we just go back to how it was before that commit? I've tried it a bit, and I don't see any issues so far.

**Comment by jdm** [comment]
That should be ok now that the UWP nightlies don't include a version number.

**Comment by camelid** [comment]
Yeah, that's what I thought. Thanks for the confirmation! :)
