### ISSUE TITLE
Module metadata hook is missing

### ISSUE THREAD

**Issue by jdm** [servo/servo#26542]
https://mixedreality.mozilla.org/area-demo-service-task/ fails immedidately with:
```
[2020-05-15T15:03:16Z ERROR script::dom::bindings::error] Error at https://mixedreality.mozilla.org/area-demo-service-task/arosg.js:3:20 Module metadata hook not set
```
This comes from https://searchfox.org/mozilla-central/rev/4166c15e2a99a23a9b38ad62c9fdfe8e5448b354/js/src/builtin/ModuleObject.cpp#1697, which is triggered by https://github.com/servo/servo/blob/b9b569aed8d9fe82d6630de732f45c4b32108ae1/components/script/script_module.rs#L1066. We should port the [equivalent code](https://searchfox.org/mozilla-central/rev/4166c15e2a99a23a9b38ad62c9fdfe8e5448b354/dom/script/ScriptLoader.cpp#937-958) from Gecko instead.

**Comment by jdm** [comment]
@CYBAI You might be interested in this.

**Comment by CYBAI** [comment]
@jdm Thanks! I will look into it!
