### ISSUE TITLE
Anchor elements and image elements do not include a correct referrer URL

### ISSUE THREAD

**Issue by jdm** [servo/servo#26569]
https://github.com/servo/servo/blob/9cbebe29077efbb8b22631f27facc0b548faf5a3/components/script/dom/htmlanchorelement.rs#L653
https://github.com/servo/servo/blob/9cbebe29077efbb8b22631f27facc0b548faf5a3/components/script/dom/htmlimageelement.rs#L306-L309

**Comment by atouchet** [comment]
Did #26926 fix this?

**Comment by jdm** [comment]
Looks like it!
