### ISSUE TITLE
DOM fetches do not include referrer URL

### ISSUE THREAD

**Issue by jdm** [servo/servo#26570]
It's hard to follow the logic of what happens - we call Request::Constructor to construct a request object when only a fetch URL is provided, then we make a [request](https://github.com/servo/servo/blob/9cbebe29077efbb8b22631f27facc0b548faf5a3/components/script/dom/request.rs#L107) which has a default referrer/referrer-policy. We then initialize [another new net_traits::Request](https://github.com/servo/servo/blob/9cbebe29077efbb8b22631f27facc0b548faf5a3/components/script/dom/request.rs#L148-L156) with the referrer/policy of the first one, and then we sometimes [default to the Client referrer](https://github.com/servo/servo/blob/9cbebe29077efbb8b22631f27facc0b548faf5a3/components/script/dom/request.rs#L209). Finally we [initialize](https://github.com/servo/servo/blob/9cbebe29077efbb8b22631f27facc0b548faf5a3/components/script/fetch.rs#L122-L123) the referrer/policy of the RequestBuilder with whatever values were eventually selected, and that's what the network stack ends up dealing with.

I suspect in most cases we end up in [this code](https://github.com/servo/servo/blob/9cbebe29077efbb8b22631f27facc0b548faf5a3/components/net/fetch/methods.rs#L239-L243) and send no Referer header at all.

**Comment by MDeiml** [comment]
The spec (https://fetch.spec.whatwg.org/#concept-main-fetch) says that the referrer should be changed from "client" to a proper URL during fetch, which contradicts this comment:
https://github.com/servo/servo/blob/74cd81b8ce823f8ddf830ef4ef144d4416822a54/components/net/fetch/methods.rs#L241-L246
I guess this should be done in the script thread because we need a reference to the window to determine the URL?

**Comment by jdm** [comment]
I think it might be easiest if we made Referrer::Client hold a Url value that represents the client's Url. That would force us to provide meaningful values in any callers that rely on it.

**Comment by MDeiml** [comment]
Looking at [this](https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer) I guess this would mean that Referrer::Client and Referrer::ReferrerUrl would behave the same. And a quick search shows that Referrer::Client is only matched during fetching. So maybe Referrer::Client should be removed altogehter?

**Comment by jdm** [comment]
That seems like a reasonable choice.

**Comment by MDeiml** [comment]
I'll try to implement that.
