### ISSUE TITLE
mozjs::panic generates ~25% of LLVM IR lines of libscript

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#26585]
I’ve tried https://github.com/dtolnay/cargo-llvm-lines on our script crate. From their README:

> Count the number of lines of LLVM IR across all instantiations of a generic function. Based on a suggestion from **@eddyb** on how to count monomorphized functions in order to debug compiler memory usage, executable size and compile time.
>
>> **\<eddyb>** unoptimized LLVM IR
>> **\<eddyb>** first used grep '^define' to get only the lines defining function bodies
>> **\<eddyb>** then regex replace in my editor to remove everything before @ and everything after (
>> **\<eddyb>** then sort | uniq -c

This tools wants to run `cargo rustc` itself, which doesn’t play well with `mach`. To get it to run I needed to:

* Upgrade rustc, CC https://github.com/dtolnay/cargo-llvm-lines/issues/17
* Temporarily apply this diff:
  ```diff
  --- components/script/Cargo.toml
  +++ components/script/Cargo.toml
  @@ -105,3 +105,3 @@ smallvec = { version = "0.6", features = ["std", "union"] }
   sparkle = "0.1"
  -style = { path = "../style", features = ["servo"] }
  +style = { path = "../style", features = ["servo", "servo-layout-2013"] }
   style_traits = { path = "../style_traits" }
  ```
* `cd` into `components/script` (the tool does not support workspaces or a `--package` flag)
* Then run `cargo llvm-lines`

This will likely compile from scratch, since `RUSTFLAGS` config that mach sets is missing.

The output is very long, here is only functions that each contribute at least 1% of all lines of LLVM IR in libscript. The second column also shows the number of times a function is instanciated from generic parameters. Both of these numbers likely influence compile times.

```
  Lines        Copies         Function name
  -----        ------         -------------
10206761 (100%) 277692 (100%)  (TOTAL)
 762368 (7.5%)   5956 (2.1%)  mozjs::panic::wrap_panic::{{closure}}
 594917 (5.8%)   7334 (2.6%)  std::thread::local::LocalKey<T>::try_with
 572728 (5.6%)   5956 (2.1%)  mozjs::panic::wrap_panic
 332398 (3.3%)   5963 (2.1%)  std::panicking::try
 196779 (1.9%)   5963 (2.1%)  std::panicking::try::do_catch
 191026 (1.9%)  15098 (5.4%)  core::ptr::drop_in_place
 159092 (1.6%)   5963 (2.1%)  std::panicking::try::do_call
 148371 (1.5%)   6508 (2.3%)  core::ops::function::FnOnce::call_once
 127032 (1.2%)   6956 (2.5%)  core::ptr::read
 119928 (1.2%)    996 (0.4%)  <<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple::Access<R,O> as serde::de::SeqAccess>::next_element_seed
 104441 (1.0%)   6967 (2.5%)  core::intrinsics::copy_nonoverlapping
 102051 (1.0%)   7137 (2.6%)  std::thread::local::LocalKey<T>::with
```

[`mozjs::panic`](https://github.com/servo/rust-mozjs/blob/5788b56231e360b5b728ce3f96b96364190ffae4/src/panic.rs) alone accounts for 1.3 million lines, 13% of the crate. It’s instantiated 5956 times, most of them in code generated by DOM bindings codegen. Each instance calls `std::panic::catch_unwind` and methods of a `thread_local!`, which accounts of most instances of functions from `std::panicking` and `std::tread::local`. Adding those brings the number to about 2.6 million lines, or 25%!

Now, `mozjs::panic::wrap_panic` takes an `FnOnce` parameter which is usually a closure that presumably gets inlined. So those million lines are split between:

* The inlined closures, different for each call site
* `mozjs::panic` itself, effectively duplicated

It’s hard to tell how the amount is distributed, but maybe it’s worth trying to make things less generic and less inlined to reduce that duplication. Which would hopefully reduce compile times without impacting runtime perf significantly. Or maybe it’ll turn out to be mostly the different closures, which would mean that 25% of the generated code in libscript is inlined DOM API implementations, which is not particularly surprising or actionable.

**Comment by SimonSapin** [comment]
(Sorry eddyb, I didn’t realize this copy-paste would mention you!)

**Comment by jdm** [comment]
One idea that should be quick to investigate - create wrap_panic_void and wrap_panic_bool by manually monomorphizing [wrap_panic](https://github.com/servo/rust-mozjs/blob/master/src/panic.rs#L18-L33) so there's no generic return value argument, then modify [this codegen code](https://github.com/servo/servo/blob/63c11d2fa1dd505abc9a5f5f8e7ae9c26467f997/components/script/dom/bindings/codegen/CodegenRust.py#L2577-L2578) to choose the right one. This should allow the generic functions to only instantiate catch_unwind with the function type, and we can extract the code that processes the error into a separate non-generic function.

**Comment by SimonSapin** [comment]
I had something a bit more fancy in mind:

```rust
/// Generic wrapper for JS engine callbacks panic-catching
pub fn wrap_panic<F, R>(function: F, mut return_value: R) -> R
    where F: FnOnce() -> R + UnwindSafe
{
    let move_once = std::mem::MaybeUninit::new(function);
    wrap_panic_momorphic(&mut || {
        // Safety: this is valid because `wrap_panic_momorphic` only ever calls this closure once.
        // This could avoid `unsafe` be replacing `MaybeUninit::as_ptr` with `Option::take`,
        // or `&mut dyn FnMut()` with `Box<dyn FnOnce>`. However both have overhead.
        let function = unsafe { move_once.as_ptr().read() };

        return_value = function();
    });
    return return_value
}

// https://github.com/servo/servo/issues/26585
#[inline(never)]
fn wrap_panic_momorphic(call: &mut dyn FnMut()) {
    match catch_unwind(AssertUnwindSafe(call)) {
        Ok(()) => {},
        Err(payload) => {
            PANIC_PAYLOAD.with(|opt_payload| {
                let mut opt_payload = opt_payload.borrow_mut();
                assert!(opt_payload.is_none());
                *opt_payload = Some(payload);
            });
        }
    }
}
```

This does reduce the total number of lines of LLVM IR by ~18%:

```
  Lines        Copies         Function name
  -----        ------         -------------
8366027 (100%) 271699 (100%)  (TOTAL)
 315111 (3.8%)  12462 (4.6%)  core::ops::function::FnOnce::call_once
 230391 (2.8%)   5956 (2.2%)  mozjs::panic::wrap_panic
 212522 (2.5%)   5956 (2.2%)  mozjs::panic::wrap_panic::{{closure}}
 173260 (2.1%)  15104 (5.6%)  core::ptr::drop_in_place
 127032 (1.5%)   6956 (2.6%)  core::ptr::read
 117484 (1.4%)    976 (0.4%)  <<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple::Access<R,O> as serde::de::SeqAccess>::next_element_seed
 106525 (1.3%)   1378 (0.5%)  std::thread::local::LocalKey<T>::try_with
 104441 (1.2%)   6967 (2.6%)  core::intrinsics::copy_nonoverlapping
  97179 (1.2%)   1576 (0.6%)  core::option::Option<T>::map
  80276 (1.0%)   5972 (2.2%)  core::mem::maybe_uninit::MaybeUninit<T>::new
```

… But the compile time gain is marginal, if not noise. Cargo says `Completed script v0.0.1 in 168.1s`, v.s. 174.0 before. (Only one run each.)

**Comment by SimonSapin** [comment]
`wrap_panic` was still near the top in number of IR lines, so I tried completely pushing the return value handling to callers:

```rust
/// Generic wrapper for JS engine callbacks panic-catching
// https://github.com/servo/servo/issues/26585
#[inline(never)]
pub fn wrap_panic(function: &mut dyn FnMut()) {
    match catch_unwind(AssertUnwindSafe(function)) {
        Ok(()) => {},
        Err(payload) => {
            PANIC_PAYLOAD.with(|opt_payload| {
                let mut opt_payload = opt_payload.borrow_mut();
                assert!(opt_payload.is_none());
                *opt_payload = Some(payload);
            });
        }
    }
}
```

```
  Lines        Copies         Function name
  -----        ------         -------------
7200699 (100%) 182355 (100%)  (TOTAL)
 173260 (2.4%)  15104 (8.3%)  core::ptr::drop_in_place
 147593 (2.0%)   6506 (3.6%)  core::ops::function::FnOnce::call_once
 117484 (1.6%)    976 (0.5%)  <<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple::Access<R,O> as serde::de::SeqAccess>::next_element_seed
 106525 (1.5%)   1378 (0.8%)  std::thread::local::LocalKey<T>::try_with
  97179 (1.3%)   1576 (0.9%)  core::option::Option<T>::map
  78368 (1.1%)   1137 (0.6%)  core::result::Result<T,E>::map
  75818 (1.1%)   1397 (0.8%)  core::result::Result<T,E>::expect
```

This time it’s 29% fewer IR lines for all of libscript, compared to `master`.

… and `Completed script v0.0.1 in 124.1s`, 28% less time!

The cost is one extra dynamically-dispatched call every time SpiderMonkey calls into Rust. Does that sound acceptable?

**Comment by SimonSapin** [comment]
> … and `Completed script v0.0.1 in 124.1s`, 28% less time!

By the way this is in release mode, with debug assertions, after `cargo clean`.

`libscript.rlib` is also 254 MiB instead of 265 MiB, 4% smaller. Maybe the better use of the instruction cache compensates the cost of dynamic dispatch?

**Comment by jdm** [comment]
If you push a branch, I'll test the performance in the platform and configuration we care most about (webxr content on the HoloLens 2).

**Comment by SimonSapin** [comment]
https://github.com/servo/servo/pull/26642 is that branch.
