### ISSUE TITLE
 Hook up interface object proto chains as if they were ES6 classes

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#2665]
https://bugzilla.mozilla.org/show_bug.cgi?id=860841
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23133

**Comment by frewsxcv** [comment]
[Relevant comment the code](https://github.com/servo/servo/blob/84e25befdd97cf74fb00707dbe150d59d980e977/components/script/dom/bindings/codegen/CodegenRust.py#L4737)
