### ISSUE TITLE
Enforcing formatting of TOML files

### ISSUE THREAD

**Issue by atouchet** [servo/servo#26728]
Currently having consistent formatting is not enforced for TOML files and as a result they have tended to become a bit disorganized. I have manually cleaned up a number of them recently to have mostly consistent formatting but things still aren't quite perfect. Would there be any interest in enforcing formatting standards for these files or would that just be more of a nuisance?

**Comment by jdm** [comment]
If there's automatic tooling for it, I think it would be useful.

**Comment by atouchet** [comment]
This GitHub issue appears to have some related info about tooling: https://github.com/toml-lang/toml/issues/532

**Comment by SimonSapin** [comment]
This could be integrated with `./mach test-tidy` for checking and `./mach fmt` for auto-formatting. As long as the latter makes the former pass, I think it’s fine to add formatting checks.

**Comment by atouchet** [comment]
It looks like the IntelliJ Rust plugin did something similar to this. It might be worth looking at:

https://github.com/intellij-rust/intellij-rust/issues/5518
https://github.com/intellij-rust/intellij-rust/pull/5536

**Comment by atouchet** [comment]
@sagudev does #30112 accomplish this?

**Comment by sagudev** [comment]
Only partially. There is no integration in `mach test-tidy` or `mach fmt` command. So formatting is not really enforced but it exist. For integration we would need to depend on taplo being installed on host system. We could do this like we do this for C++ code, only warning that taplo is not installed and not failing. This would make taplo optional dependencies, but CI would still be allowed to enforce formatting of TOML.
