### ISSUE TITLE
<pre> shouldn't render a final trailing newline

### ISSUE THREAD

**Issue by jdm** [servo/servo#26754]
As part of the work in #26440, I discovered some surprising behaviour about `<pre>`. Given:
```html
<pre>hello</pre>

<pre>hello
</pre>

<pre>hello

</pre>
```
In other browsers, only the final example with two newlines renders an empty line below `hello`. In the initial implementation in #26447, Servo renders an empty line for the second case as well. I have not been able to find spec text in https://drafts.csswg.org/css-text-3/ that explains why other browsers behave the way they do.

I've been reading:
* https://drafts.csswg.org/css-text-3/#white-space-processing (and 4.1)
* https://drafts.csswg.org/css-text-3/#line-breaking (and 5.1)

cc @SimonSapin

**Comment by SimonSapin** [comment]
I look some more, but the first thing I tried is the same happens with `<div>` + `white-space: pre` instead of `<pre>`. This excludes anything at the HTML parser level and indicates that this is happening at the CSS layout level.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/8160

**Comment by SimonSapin** [comment]
It also happens with other kinds of forced line breaks. At most one trailing break is removed/ignored.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/8163
```html
<p>hello</p>
<p>hello<br></p>
<p>hello<br><br></p>
<style>p { border: solid

**Comment by mrobinson** [comment]
I think these examples are both working properly after recent work on proper white-space handling.
