### ISSUE TITLE
Implement SVGElement.style

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#26777]
Spec: https://drafts.csswg.org/cssom/#dom-elementcssinlinestyle-style

With implementing this, we should be able to fix #26032.

**Comment by CYBAI** [comment]
Tried to implement `style` for `SVGElement`, I found it doesn't fix #26032 and we still can't get `style` for the create svg circle element :/

```js
const x = document.createElementNS("http://www.w3.org/2000/svg", "circle");
console.log(x.style);
```

In Gecko, this will log an empty `CSS2Properties` but it will log `undefined` in Servo even `SVGElement includes ElementCSSInlineStyle`.

**Comment by jdm** [comment]
I have a suspicion that the element returned from createElementNS is a generic Element, rather than an SVGElement. It's worth checking if that is the case.

**Comment by CYBAI** [comment]
Cool! Yes! It currently returns a generic Element. 

https://github.com/servo/servo/blob/3d6fed85ffffcc289a6e0decb0dd70a2985542b0/components/script/dom/create.rs#L111-L114

Before implementing other svg elements, should we return a generic `SVGElement` here instead?

**Comment by jdm** [comment]
Yes, that should help.
