### ISSUE TITLE
Searching with duckduckgo.com/html freezes Servo

### ISSUE THREAD

**Issue by atouchet** [servo/servo#26807]
URL: https://duckduckgo.com/html

Steps to reproduce:

1. Load https://duckduckgo.com/html in Servo.
2. Search something in the DuckDuckGo search bar.
3. Servo will then freeze.

This issue first occurred in the 2020-06-04 nightly build. Tested in Windows 10.

Regression range: https://github.com/servo/servo/compare/ea491b41174edd03c3ee08fe29046c33b96b0406...8536cee72cca0f8a4d9f7a14b47a8b16ed356179

**Comment by atouchet** [comment]
Using the https://duckduckgo.com/ URL still appears to work. It's just the https://duckduckgo.com/html version that has the issue.

**Comment by CYBAI** [comment]
I tried to follow the steps and can reproduce it with a panic.

```
→ ./mach run https://duckduckgo.com/html
assertion failed: incumbent_global.is_some() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/script_runtime.rs:175)
```

**Comment by CYBAI** [comment]
Because I saw readablestream in the backtrace, @gterzian you might be interested in this?

**Comment by CYBAI** [comment]
Interesting! I think I figured out how to fix the panic but with that fix, we will get a 400 page instead of a ddg search result page.

**Comment by CYBAI** [comment]
While checking out to the commit before landing `readablestream`, I'm able to search successfully in https://duckduckgo.com/html.

**Comment by jdm** [comment]
I suspect something about the request body that ddg receives from servo is broken, given those pieces of data.

**Comment by CYBAI** [comment]
This can fix the panic and yes, looks like the request body is incorrect!

```
diff --git a/components/script/dom/readablestream.rs b/components/script/dom/readablestream.rs
index 1c6ac242e9..90e6c72da7 100644
--- a/components/script/dom/readablestream.rs
+++ b/components/script/dom/readablestream.rs
@@ -6,7 +6,7 @@ use crate::dom::bindings::conversions::{ConversionBehavior, ConversionResult};
 use crate::dom::bindings::error::Error;
 use crate::dom::bindings::reflector::{reflect_dom_object, DomObject, Reflector};
 use crate::dom::bindings::root::DomRoot;
-use crate::dom::bindings::settings_stack::AutoEntryScript;
+use crate::dom::bindings::settings_stack::{AutoEntryScript, AutoIncumbentScript};
 use crate::dom::bindings::utils::get_dictionary_property;
 use crate::dom::globalscope::GlobalScope;
 use crate::dom::promise::Promise;
@@ -118,6 +118,7 @@ impl ReadableStream {
         source: ExternalUnderlyingSource,
     ) -> DomRoot<ReadableStream> {
         let _ar = enter_realm(global);
+        let _ais = AutoIncumbentScript::new(global);
         let cx = global.get_cx();

         let source = Rc::new(ExternalUnderlyingSourceController::new(source));
```

btw, @jdm @gterzian while trying to spot the bug, I suspect this should be `AutoIncumbentScript` instead of `AutoEntryScript` ?

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/script/dom/promise.rs#L245-L247

**Comment by gterzian** [comment]
Nice catch. 

I'm not entirely sure about whether `append_native_handler` should use a `AutoEntryScript` or a `AutoIncumbentScript`, I think I chose the former because that it what they were using in Gecko, although I can't be 100% sure that the context of that use is the same as in Servo. 

I'd say for now we can focus on fixing the panic with your fix, and maybe look into `append_native_handler` if that becomes a problem? 

With regards to the request body, how does it look now? 

From the backtrace it looks like it's a form, which is entirely read into a `Vec<u8>` and then "streamed" in one chunk, but maybe something goes wrong along the way? 

The various places where would check would be:

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/script/body.rs#L478

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/script/body.rs#L250

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/net/http_loader.rs#L452

**Comment by gterzian** [comment]
Ah Ok it's not a form, it goes via `submit_entity_body`, which extracts a body from a `Vec<u8>`, just seeing we're not actually adding a content-type there, whereas in FF I can see the Post has a `application/x-www-form-urlencoded` content-type. 

Maybe try to add this to:

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/script/body.rs#L435

**Comment by CYBAI** [comment]
oh, interesting! I didn't notice we miss the content-type here (I did see it's logged from the request though 🤔)

```
[2020-06-06T14:50:08Z INFO  net::http_loader] POST request for https://duckduckgo.com/html/
[2020-06-06T14:50:08Z INFO  net::http_loader]  - ("content-type", "application/x-www-form-urlencoded")
[2020-06-06T14:50:08Z INFO  net::http_loader]  - ("accept", "text/html, application/xhtml+xml, application/xml; q=0.9, */*; q=0.8")
[2020-06-06T14:50:08Z INFO  net::http_loader]  - ("accept-language", "en-US, en; q=0.5")
[2020-06-06T14:50:08Z INFO  net::http_loader]  - ("content-length", "11")
[2020-06-06T14:50:08Z INFO  net::http_loader]  - ("origin", "https://duckduckgo.com")
[2020-06-06T14:50:08Z INFO  net::http_loader]  - ("user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Servo/1.0 Firefox/75.0")
[2020-06-06T14:50:08Z INFO  net::http_loader]  - ("accept-encoding", "gzip, deflate, br")
```

**Comment by gterzian** [comment]
Also another thing: should we not enter into a realm or a script before calling `ScriptThread::handle_mouse_event`? That happens straight from handling a constellation message? I'm guessing that's why the call to create the stream fails because there is no incumbent global, but should there not be one already before?

**Comment by gterzian** [comment]
Ah ok, so `htmlformelement` sets headers directly around https://github.com/servo/servo/pull/25873/files#diff-db2031d1f23ecf1a921fc100cfed753dR774

But since the `RequestBody` still have a `None` content-type, maybe this fails the request somewhere in the logic in net?

I think it's worth a try to add `Some(DOMString::from(format!(
            "multipart/form-data;boundary={}",
            boundary
        )));` at

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/script/body.rs#L435

**Comment by CYBAI** [comment]
> Maybe try to add this to:
> 
> https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/script/body.rs#L435

I found we've handled the content-type in `htmlformelement` while submitting the form. (I also tried to add a `Some(application/x-www-form-urlencoded)` and confirmed it didn't help)

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/script/dom/htmlformelement.rs#L772-L776

> should there not be one already before in any case since we're about to fire an event?

I'm not very sure but if I understand correctly about `AutoIncumbentScript`, it's required for things like calling JS callbacks or promises (it's kind of JS callback?). We might not always need to get into realm in the constellation? if we just get into the realm for incumbent, would we hold the incumbent for a long time which might be unnecessary? 🤔

**Comment by gterzian** [comment]
Ok so I'd say your fix at https://github.com/servo/servo/issues/26807#issuecomment-640070657

then the question is still what is wrong with the request body when it is sent...

**Comment by CYBAI** [comment]
> then the question is still what is wrong with the request body when it is sent...

one thing I also noticed is, if I set a breakpoint at this line 👇 

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/script/body.rs#L166

then I will endlessly get into it. 

Does that mean we get into an infinite loop and result in a 400 request 🤔?

**Comment by gterzian** [comment]
Yes, please add `let _ = self.control_sender.send(BodyChunkRequest::Done);` after line 167 🤣

**Comment by CYBAI** [comment]
ooooooooooooh!!!!! gooooood catch!!! let me try it 🤣🤣🤣

**Comment by CYBAI** [comment]
Interesting! With sending the `Done` message, we do stop the `bytes_sender` of request body but we then get a panic because it's `None`.

I suspect the IPC router in `obtain_response` around line 443 to 467 is also getting into an infinite loop as well 🤔 Will check it tmr!

```
No bytes sender to transmit chunk. (thread <unnamed>, at components/script/body.rs:160)
   0: backtrace::backtrace::libunwind::trace
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/mod.rs:66
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/backtrace.rs:49
   2: core::fmt::write
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/fmt/mod.rs:1069
   3: std::io::Write::write_fmt
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/io/mod.rs:1537
   4: servo::backtrace::print
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/backtrace.rs:17
   5: servo::main::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/main2.rs:150
   6: std::panicking::rust_panic_with_hook
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:481
   7: rust_begin_unwind
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:385
   8: core::panicking::panic_fmt
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/panicking.rs:89
   9: core::option::expect_failed
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/option.rs:1264
  10: core::option::Option<T>::expect
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/option.rs:349
  11: script::body::TransmitBodyConnectHandler::transmit_body_chunk
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/body.rs:160
  12: script::body::ExtractedBody::into_net_request_body::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/body.rs:351
  13: <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/boxed.rs:1041
  14: ipc_channel::router::Router::run
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.14.1/src/router.rs:198
  15: ipc_channel::router::RouterProxy::new::{{closure}}
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.14.1/src/router.rs:50
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
  17: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:318
  19: std::panicking::try::do_call
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:297
  20: ___rust_try
  21: std::panicking::try
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  22: std::panic::catch_unwind
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:394
  23: std::thread::Builder::spawn_unchecked::{{closure}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
  24: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1034
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1034
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/sys/unix/thread.rs:87
  26: __pthread_body
  27: __pthread_start
```

**Comment by CYBAI** [comment]
ok, I just tried a workaround and it fixed the issue!

In this IPC router, we will just send a `Chunk` request for step `5.1.2.3` of [concept-request-transmit-body](https://fetch.spec.whatwg.org/#concept-request-transmit-body); however, we might want to take step `5.1.3` which means, when the stream is already done, we won't send chunks anymore.

https://github.com/servo/servo/blob/0645d8c36d734d77e6a783148df593deb7cfb7ee/components/net/http_loader.rs#L461-L469

I say workaround because I wonder doing the checking in above IPC router is more straightforward? but, it seems we don't hold a RequestBody there so we might can only handle it in the following IPC router? 

```diff
diff --git a/components/script/body.rs b/components/script/body.rs
@@ -346,7 +347,11 @@ impl ExtractedBody {
                     BodyChunkRequest::Extract(receiver) => {
                         body_handler.re_extract(receiver);
                     },
-                    BodyChunkRequest::Chunk => body_handler.transmit_body_chunk(),
+                    BodyChunkRequest::Chunk => {
+                        if body_handler.bytes_sender.is_some() {
+                            body_handler.transmit_body_chunk();
+                        }
+                    },
                     // Note: this is actually sent from this process
                     // by the TransmitBodyPromiseHandler when reading stops.
                     BodyChunkRequest::Done => body_handler.stop_reading(),
```

**Comment by CYBAI** [comment]
Maybe let me send a PR and discuss there!

**Comment by CYBAI** [comment]
Also, it might be worth adding a new test for this 🤔?

**Comment by gterzian** [comment]
Ok good one, I would prefer if we return early inside the method if the sender is `None`, over at https://github.com/servo/servo/blob/0645d8c36d734d77e6a783148df593deb7cfb7ee/components/script/body.rs#L160

**Comment by CYBAI** [comment]
I see! Thanks for the clear explanation!

> as opposed to immediately dropping the sender which is "too early".

Now I can understand why it's better to be handled in `transmit_body_chunk` 👀!

> Yes I think you can add a test in the mozilla folder, I think you can get the failure by doing a POST using a Blob too(might be easier to write than a form).

Thanks! Will try to do that!

**Comment by CYBAI** [comment]
Phew! Thanks @gterzian a lot! This is my first time to play with IPC things! and it makes me wonder if I can leverage the power of IPC to make module script work better and more readable 🤔

**Comment by gterzian** [comment]
Good, let me know what you find out!
