### ISSUE TITLE
Google logo doesn't align center on google.com

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#26883]
Visit [google.com](https://google.com)

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/6782666/84477693-fe6aba00-acca-11ea-9b57-6b7d1ce70c15.png">

Built with latest master (54d2b7d) on macOS 10.14.6

**Comment by atouchet** [comment]
Duplicate of #26096.

**Comment by CYBAI** [comment]
@atouchet oh, thanks! didn't notice there's an existing one!
