### ISSUE TITLE
mio 0.7 isn't compatible with UWP

### ISSUE THREAD

**Issue by jdm** [servo/servo#26896]
https://github.com/tokio-rs/mio/issues/912#issuecomment-513472970

0.7 was released in March, and the `afd` in question is [this code](https://github.com/tokio-rs/mio/blob/0ba2ed8bb1e3af999024653d587b9c25f8d4b57c/src/sys/windows/afd.rs). It relies on the [ntapi](https://github.com/MSxDOS/ntapi) crate, and given documentation like https://docs.microsoft.com/en-us/windows/win32/devnotes/calling-internal-apis that's linked from https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile, I get very nervous.

**Comment by jdm** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-rtlntstatustodoserror is definitely not supported in UWP apps (https://github.com/tokio-rs/mio/blob/0ba2ed8bb1e3af999024653d587b9c25f8d4b57c/src/sys/windows/afd.rs#L197).

**Comment by jdm** [comment]
This affects:
* mio-extras
* mio-uds
* tokio
* tokio-reactor
* tokio-tcp
* tokio-udp
* tokio-uds
* ws

**Comment by jdm** [comment]
https://github.com/tokio-rs/mio/issues/1314 suggests that it would be worth adding a fake consumer of mio 0.7 to servo and running the WACK to see if anything shows up.

**Comment by bdbai** [comment]
I wonder if this helps https://github.com/YtFlow/mio-noafd . This is a modified version of mio 0.7 that reverts the use of wepoll strategy. `IoSource` and named pipes are not implemented. It has been used in the UWP VPN app https://github.com/YtFlow/Maple .
