### ISSUE TITLE
Virtual keyboard does not appear when text inputs are focused

### ISSUE THREAD

**Issue by jdm** [servo/servo#26898]
https://github.com/servo/servo/blob/c2a1ab163d45a8971b5ccf2a59dc0874dc047358/support/hololens/ServoApp/ServoControl/ServoControl.cpp#L442-L445

**Comment by jdm** [comment]
This will probably require #26680 to be fixed for the keyboard to be useful, too.

**Comment by jdm** [comment]
The lack of this keyboard prevents testing any content that is hidden behind user/password access.

**Comment by jdm** [comment]
We might be able to use [InputPane.GetForCurrentView().TryShow()](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.inputpane?view=winrt-19041). We may also need to rely on [CoreTextEditContext.InputPaneDisplayPolicy](https://docs.microsoft.com/en-us/uwp/api/windows.ui.text.core.coretexteditcontext.inputpanedisplaypolicy?view=winrt-19041#Windows_UI_Text_Core_CoreTextEditContext_InputPaneDisplayPolicy) and manually show the keyboard when the UI's URL bar is focused.

**Comment by jdm** [comment]
https://docs.microsoft.com/en-us/windows/uwp/design/input/respond-to-the-presence-of-the-touch-keyboard

Perhaps one option would be making the Servo control behave like a custom text input control.

**Comment by jdm** [comment]
https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/TouchKeyboard/cpp

**Comment by paulrouget** [comment]
I'm looking at this.

**Comment by paulrouget** [comment]
This will be implemented in 2 steps.

1)

I'm going to initially land a simple text controller mechanism that implements key events and also sync our IME messages with the InputPane.

But the way Servo handles text inputs is too simplistic to implement correctly a text handler. We're missing pieces to get the proper behavior (like exposing selection range, caret position, etc, which is necessary to synchronize the field within the virtual keyboard). But UWP offers some possible fallback.

I'm also wondering if we should not let the embedder handle all the text/caret/selection/range behavior. That would be easy on Windows. Not sure about the winit port and Android.

I'll see later what is the best approach.

**Comment by paulrouget** [comment]
On Desktop, no issue.

I think if we get to a point where can enter login and passwords on the device, it's a good enough first step.
