### ISSUE TITLE
Build Failed:  failed to run custom build command for `style v0.0.1

### ISSUE THREAD

**Issue by Firoda** [servo/servo#26908]
My System : Windows 

error: failed to run custom build command for `style v0.0.1 (C:\Users\Firoda\Documents\servo\components\style)`

Caused by:
  process didn't exit successfully: `C:\Users\Firoda\Documents\servo\target\debug\build\style-1a8b0960ea8ea4ad\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:out_dir=C:\Users\Firoda\Documents\servo\target\debug\build\style-2697db50e7c2ec9f\out
cargo:rerun-if-changed=properties\build.py
cargo:rerun-if-changed=properties\cascade.rs
cargo:rerun-if-changed=properties\computed_value_flags.rs
cargo:rerun-if-changed=properties\counted_unknown_properties.py
cargo:rerun-if-changed=properties\data.py
cargo:rerun-if-changed=properties\declaration_block.rs
cargo:rerun-if-changed=properties\gecko.mako.rs
cargo:rerun-if-changed=properties\helpers\animated_properties.mako.rs
cargo:rerun-if-changed=properties\helpers.mako.rs
cargo:rerun-if-changed=properties\longhands\background.mako.rs
cargo:rerun-if-changed=properties\longhands\border.mako.rs
cargo:rerun-if-changed=properties\longhands\box.mako.rs
cargo:rerun-if-changed=properties\longhands\column.mako.rs
cargo:rerun-if-changed=properties\longhands\counters.mako.rs
cargo:rerun-if-changed=properties\longhands\effects.mako.rs
cargo:rerun-if-changed=properties\longhands\font.mako.rs
cargo:rerun-if-changed=properties\longhands\inherited_box.mako.rs
cargo:rerun-if-changed=properties\longhands\inherited_svg.mako.rs
cargo:rerun-if-changed=properties\longhands\inherited_table.mako.rs
cargo:rerun-if-changed=properties\longhands\inherited_text.mako.rs
cargo:rerun-if-changed=properties\longhands\inherited_ui.mako.rs
cargo:rerun-if-changed=properties\longhands\list.mako.rs
cargo:rerun-if-changed=properties\longhands\margin.mako.rs
cargo:rerun-if-changed=properties\longhands\outline.mako.rs
cargo:rerun-if-changed=properties\longhands\padding.mako.rs
cargo:rerun-if-changed=properties\longhands\position.mako.rs
cargo:rerun-if-changed=properties\longhands\svg.mako.rs
cargo:rerun-if-changed=properties\longhands\table.mako.rs
cargo:rerun-if-changed=properties\longhands\text.mako.rs
cargo:rerun-if-changed=properties\longhands\ui.mako.rs
cargo:rerun-if-changed=properties\longhands\xul.mako.rs
cargo:rerun-if-changed=properties\properties.html.mako
cargo:rerun-if-changed=properties\properties.mako.rs
cargo:rerun-if-changed=properties\shorthands\background.mako.rs
cargo:rerun-if-changed=properties\shorthands\border.mako.rs
cargo:rerun-if-changed=properties\shorthands\box.mako.rs
cargo:rerun-if-changed=properties\shorthands\column.mako.rs
cargo:rerun-if-changed=properties\shorthands\font.mako.rs
cargo:rerun-if-changed=properties\shorthands\inherited_svg.mako.rs
cargo:rerun-if-changed=properties\shorthands\inherited_text.mako.rs
cargo:rerun-if-changed=properties\shorthands\list.mako.rs
cargo:rerun-if-changed=properties\shorthands\margin.mako.rs
cargo:rerun-if-changed=properties\shorthands\outline.mako.rs
cargo:rerun-if-changed=properties\shorthands\padding.mako.rs
cargo:rerun-if-changed=properties\shorthands\position.mako.rs
cargo:rerun-if-changed=properties\shorthands\svg.mako.rs
cargo:rerun-if-changed=properties\shorthands\text.mako.rs

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', components\style\build.rs:69:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
   Completed serde_derive v1.0.111 in 30.4s
   Completed peek-poke v0.2.0 in 0.8s
   Completed webrender v0.61.0 custom-build (run) in 5.0s
   Completed futures-util v0.3.4 in 5.8s
error: build failed
Build FAILED in 0:01:33

**Comment by Firoda** [comment]
I checked the cloned repository on my machine and it does have the file build.rs in the components\style\build.rs

**Comment by jdm** [comment]
Line 69 of that file tries to run python3 based on [this code](https://github.com/servo/servo/blob/master/components/style/build.rs#L31). That's what is breaking for you.

**Comment by nicbn** [comment]
Had the same problem yesterday, on Windows as well.

**Comment by jdm** [comment]
To be clear - both python2 and python3 are necessary right now, and if you're encountering problems running either of them you should set PYTHON2 and PYTHON3 environment variables to point at the appropriate executable.

**Comment by nicbn** [comment]
I fixed it by removing the Python3 alias to Windows Store (try running Python3 on the CMD, if store pops up then you've got to remove the alias on settings) and moving Python3 directory out of `C:\Program Files`, which fixed both the issue with the space-containing path (which can be fixed by quoting the path as well) and the permission denied.
