### ISSUE TITLE
Update Tokio and Hyper in net component

### ISSUE THREAD

**Issue by gterzian** [servo/servo#26933]
Tokio: we're on 0.1, latest is 0.2. 
Hyper: we're on 0.12, latest is 0.13. 

I think it's worth upgrading, as when running into an issue it's a bit hard navigating the legacy docs to figure it out. 

This might require code changes. 

https://github.com/servo/servo/blob/master/components/net/Cargo.toml

**Comment by jdm** [comment]
We'll need to address #26896 before we can merge the latest tokio.

**Comment by atouchet** [comment]
> We'll need to address #26896 before we can merge the latest tokio.

Tokio still depends on Mio 0.6 currently. Is this an issue if Mio doesn't need to be updated yet?

**Comment by jdm** [comment]
It is not!

**Comment by atouchet** [comment]
The latest version of Tokio requires Mio 0.6.20 and the patched version Servo is using is based off of 0.6.18 so that would need to be updated.

**Comment by atouchet** [comment]
Crates that will require updates:
- [ ] hyper
  - [ ] devtools
  - [ ] hyper_serde
  - [ ] malloc_size_of
  - [ ] net
  - [ ] net_traits
  - [ ] script
  - [ ] script_traits
  - [ ] webdriver_server
- [ ] tokio
  - [ ] net
  - [ ] webdriver

**Comment by jdm** [comment]
I have pushed a new branch of our fork of mio at https://github.com/servo/mio/tree/servo-mio-0.6.22.

**Comment by atouchet** [comment]
net now depends on Tokio 0.1 and 0.2 as of #27164.

**Comment by atouchet** [comment]
Tokio 0.3 is now out which uses Mio 0.7.
