### ISSUE TITLE
Changing DEFAULT_URL doesn't override locally-stored preference

### ISSUE THREAD

**Issue by jdm** [servo/servo#27046]
DEFAULT_URL is only used if there's no shell.homepage preference present in the local preferences in [this code](https://github.com/servo/servo/blob/ed46f00497f4bab79717b0c6a1da08d068b5cfcf/support/hololens/ServoApp/ServoControl/Servo.cpp#L143-L145). This is really confusing when modifying DEFAULT_URL during development!

**Comment by paulrouget** [comment]
(I have an upcoming fix, will be part of the text events PR)
