### ISSUE TITLE
Rename master branch on all repos?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#27089]
We shouldn't have the main branch be called `master` in 2020.

**Comment by asajeffrey** [comment]
Unfortunately, this is probably a big job, especially for repos that may have downstream consumers, since https://github.com/rust-lang/cargo/pull/8364 only just landed. We'd also need to find all the places our docs and build scripts mention `master`.

**Comment by asajeffrey** [comment]
For example hyperlinks to the main branch are currently things like `https://github.com/servo/servo/blob/master/README.md` (https://github.com/servo/servo/blob/master/README.md) and it would be nice not to break those.

**Comment by asajeffrey** [comment]
OK, I went through and renamed all the main branches in my personal repos to `main`, which took a couple of minutes per repo. The recipe is:
```
git checkout master
git pull
git branch -m main
git push -u origin main
```
Then set the default branch using the github UI https://help.github.com/en/github/administering-a-repository/setting-the-default-branch

**Comment by saschanaz** [comment]
Can we create a new branch and keep `master` just for compatibility?

**Comment by asajeffrey** [comment]
@saschanaz we could freeze the master branch, and not do updates to it.

**Comment by saschanaz** [comment]
Good idea, that will keep things working while still suggests to update to the new name.

**Comment by mrobinson** [comment]
I think this is done now!
