### ISSUE TITLE
Gstreamer deps fail to compile with bare ./mach check on systems with downloaded gstreamer

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#27090]
If your system does not have gstreamer 1.16 and uses `./mach bootstrap-gstreamer`, `./mach build` will set up the PKG_CONFIG_PATH and LIB variables for the build.

However, `./mach check` will not. This means that `./mach check` will fail to build gstreamer sys dependencies (easily tested with `./mach check   -p gstreamer-video-sys` on a fresh clone). It works in general because often you will have run `./mach build` first, and `./mach check` reuses the metadata files.

**Comment by mrobinson** [comment]
`./mach check` should be properly setting these environment variables now.
