### ISSUE TITLE
hstring2char is used in unsafe ways

### ISSUE THREAD

**Issue by jdm** [servo/servo#27115]
[hstring2char](https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L393-L400) returns a unique_ptr. This ensures that we don't end up leaking the value. However, we need to be careful about cases where we dereference it and return the inner pointer, which means we could end up deleting the pointer.

Scary:
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L124
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L155
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L169
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L196

_Probably_ safe:
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L285
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L293
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L301
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L309-L310
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L318
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.cpp#L362
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.h#L68
* https://github.com/servo/servo/blob/56e0e557a5c882af6f3860de5ab03fbed64e4bb5/support/hololens/ServoApp/ServoControl/Servo.h#L70

My _guess_ is that stuff like the pref code is safe because we don't release the unique pointer until the end of the function, but I'm honestly not sure. It would be easier to reason about if we always stored the result of hstring2char in a local variable, and then dereferenced that variable.

**Comment by paulrouget** [comment]
We allocate strings in Rust and send them to C++. We allocate strings in C++ and send them to Rust.
We should have string containers on both sides, that send "deallocate" events to the other side when it's being dropped.

You suggested that in the past. I think this would address this issue.

**Comment by jdm** [comment]
I think that issue might be independent? This one is strictly about how the underlying string buffers are stored in C++.

**Comment by paulrouget** [comment]
I understand. I'll take care of this.
