### ISSUE TITLE
UWP Windows build fails to install

### ISSUE THREAD

**Issue by atouchet** [servo/servo#27132]
I tried installing the UWP build from https://servo.org/ and after running ServoApp_1.1.0.0_x64_arm64.msixbundle I get the error message: "Either a new certificate must be installed for this app package or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain was processed but terminated in a root certificate that isn't trusted (0x800B0109)"

**Comment by jdm** [comment]
If you haven't side-loaded a UWP build before, you need to install the certificate in the zip file as a trusted root.

**Comment by atouchet** [comment]
I ran the ServoApp_1.1.0.0_x64_arm64 security certificate and followed the import instructions but I still get the same error. Is there something else I should be doing?
