### ISSUE TITLE
Minesweeper Online detects right clicks as left clicks

### ISSUE THREAD

**Issue by atouchet** [servo/servo#27155]
URL: http://minesweeperonline.com/#

Steps to reproduce:

1. Load http://minesweeperonline.com/# and start playing a game of Minesweeper.
2. Right click on a square to flag it.
3. The game detects a left click instead and will press the square instead of flagging it.

Tested using the latest nightly build in Windows 10.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/c0a582471eb25555408d467d25dffc52d81d8f8c/components/script/dom/document.rs#L1159

Oops!

**Comment by jdm** [comment]
Similarly, [this code](https://github.com/servo/servo/blob/7eacfa4f0de57bd3312e9163681b11f6c6aa3c65/components/compositing/compositor.rs#L893-L899) looks really weird. It's not clear why we're passing a `buttons` argument that gets ignored and a hardcoded `MouseButton::Left` that is used.

**Comment by jdm** [comment]
I think we should get rid of the second, hard-coded value and replace its use in [this code](https://github.com/servo/servo/blob/c0a582471eb25555408d467d25dffc52d81d8f8c/components/script/dom/document.rs#L1216) with the ignored `buttons` argument instead.

**Comment by jdm** [comment]
@PhilParisot Want to fix this one?

**Comment by PhilParisot** [comment]
For sure 100% down!

**Comment by pshaughn** [comment]
This relates to #25181, the "auxclick" event a right-click should actually be firing.

**Comment by PhilParisot** [comment]
@highfive: assign me

**Comment by PhilParisot** [comment]
@highfive unassign me

**Comment by jdm** [comment]
Unassigning by request.

**Comment by duncandean** [comment]
@highfive: assign me

**Comment by duncandean** [comment]
Working on this today. I seem to be able to get it working as expected. Will ask questions on the #servo Matrix channel if stuck.

**Comment by duncandean** [comment]
Ah yeah, as @pshaughn mentioned, I checked and we're not receiving non-primary clicks because we don't have anything to handle [auxclick](https://w3c.github.io/uievents/#event-type-auxclick) events in the glutin port.

So it looks like this issue is blocked by #25181.

I'd be happy to take that on with any necessary guidance. 🙏

**Comment by jdm** [comment]
WebDriverMouseButtonEvent is specific to the [WebDriver](https://w3c.github.io/webdriver/#element-click) automation API, so it's less important.
