### ISSUE TITLE
Protocol launcher for UWP still loads default homepage

### ISSUE THREAD

**Issue by jdm** [servo/servo#27165]
When generating a QR code with a fxr:// protocol from https://www.qr-code-generator.com/, looking at the QR code in the HL2 pops up a dialog to confirm opening the URL in FxR. However, accepting it still causes servo.org/hl-home/ to be launched instead.

**Comment by paulrouget** [comment]
https://github.com/servo/servo/commit/2ef6ba25dc053a5ff381637c71b30748b943f869#diff-21a2278a1ca7a7ea108af7a3ca6ffa3fL309-L311
