### ISSUE TITLE
Hololens : get hand points poses

### ISSUE THREAD

**Issue by Rufus31415** [servo/servo#27172]
Is there a way to get all points of the hands user ? I searched the api but I couldn't find out how to do it.
I think it's possible, we can see an example at 00:35s : https://twitter.com/mozillareality/status/1263477345521995788

**Comment by jdm** [comment]
That's the experimental hand tracking API from https://github.com/immersive-web/webxr-hands-input. You might be able to play with it right now by opening the settings panel (button to the right of the URL bar), finding the [dom.webxr.hands.enabled](https://github.com/servo/servo/blob/8916a42180a9119bf5d8710a30694b1825b97414/resources/prefs.json#L40) preference and making it true.

**Comment by Rufus31415** [comment]
Awesome
