### ISSUE TITLE
Update Servo branding

### ISSUE THREAD

**Issue by atouchet** [servo/servo#27189]
Servo now has a new logo but some resources are still using the old one. These should probably be updated.

Twitter account: https://twitter.com/servodev
bors-servo: https://github.com/bors-servo

**Comment by atouchet** [comment]
@jdm do you control the Twitter account? I think it would be a good idea to update the logo before any future updates get posted there.

**Comment by jdm** [comment]
Updated. End of an era!

**Comment by jdm** [comment]
I am not concerned about updating the bors-servo logo.

**Comment by atouchet** [comment]
Yeah, the Twitter account was the main one I was thinking of. Looks good.

**Comment by CYBAI** [comment]
> Updated. End of an era!

I believe I will miss the doge logo! 😂
