### ISSUE TITLE
Many warnings about request stream confirmations when loading pages

### ISSUE THREAD

**Issue by jdm** [servo/servo#27185]
For pages that make a bunch of network requests, if you look at the output of RUST_LOG=net::http_loader or RUST_LOG=net, you end up seeing a bunch of `WARN - net::http_loader - Failed to receive confirmation request was streamed without error.` The fact that everything appears to be working fine suggests that this is not actually a case we need to warn about. @gterzian What can we do to reduce the frequency of this message?

**Comment by gterzian** [comment]
Thanks for catching this, it's actually an omission in the logic, which currently doesn't take into account a non-existent request body.
