### ISSUE TITLE
Parallel render patch causes memory corruption in Skia

### ISSUE THREAD

**Issue by glennw** [servo/servo#2718]
The log below shows allocations and frees for the GrMemoryPool. Note that in the last release before the segfault, the memory address is being freed from a different memory pool than it was allocated in, and also from a different thread.

Pool 0x0x7f9d8836b4f0 CONSTRUCT thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b558 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8c334f80 CONSTRUCT thread 140315071608576
Pool 0x0x7f9d8c334f80 Allocate 0x0x7f9d8c334fe8 thread 140315071608576
Pool 0x0x7f9d8c334f80 Allocate 0x0x7f9d8c3350f0 thread 140315071608576
Pool 0x0x7f9d98335590 CONSTRUCT thread 140315098867456
Pool 0x0x7f9d98335590 Allocate 0x0x7f9d983355f8 thread 140315098867456
Pool 0x0x7f9d98335590 Allocate 0x0x7f9d98335700 thread 140315098867456
Pool 0x0x7f9d8c334f80 Release 0x0x7f9d8c3350f0 thread 140315071608576
Pool 0x0x7f9d98335590 Release 0x0x7f9d98335700 thread 140315098867456
Pool 0x0x7f9d8c334f80 Allocate 0x0x7f9d8c3350f0 thread 140315071608576
Pool 0x0x7f9d98335590 Allocate 0x0x7f9d98335700 thread 140315098867456
Pool 0x0x7f9d9435e2d0 CONSTRUCT thread 140315095709440
Pool 0x0x7f9d9435e2d0 Allocate 0x0x7f9d9435e338 thread 140315095709440
Pool 0x0x7f9d9435e2d0 Allocate 0x0x7f9d9435e440 thread 140315095709440
Pool 0x0x7f9d9435e2d0 Release 0x0x7f9d9435e440 thread 140315095709440
Pool 0x0x7f9d9435e2d0 Allocate 0x0x7f9d9435e440 thread 140315095709440
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b768 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b768 thread 140315094656768
Pool 0x0x7f9d8c334f80 Release 0x0x7f9d8c334fe8 thread 140315071608576
Pool 0x0x7f9d8c334f80 Release 0x0x7f9d8c3350f0 thread 140315071608576
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b768 thread 140315094656768
Pool 0x0x7f9d98335590 Release 0x0x7f9d983355f8 thread 140315098867456
Pool 0x0x7f9d98335590 Release 0x0x7f9d98335700 thread 140315098867456
Pool 0x0x7f9d9435e2d0 Release 0x0x7f9d9435e338 thread 140315095709440
Pool 0x0x7f9d9435e2d0 Release 0x0x7f9d9435e440 thread 140315095709440
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b768 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b768 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b558 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b768 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b558 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9da0450b70 CONSTRUCT thread 140315111249664
Pool 0x0x7f9da0450b70 Allocate 0x0x7f9da0450bd8 thread 140315111249664
Pool 0x0x7f9da0450b70 Allocate 0x0x7f9da0450ce0 thread 140315111249664
Pool 0x0x7f9d98335590 Allocate 0x0x7f9d983355f8 thread 140315098867456
Pool 0x0x7f9d98335590 Allocate 0x0x7f9d98335700 thread 140315098867456
Pool 0x0x7f9da0450b70 Release 0x0x7f9da0450ce0 thread 140315111249664
Pool 0x0x7f9d98335590 Release 0x0x7f9d98335700 thread 140315098867456
Pool 0x0x7f9d98335590 Allocate 0x0x7f9d98335700 thread 140315098867456
Pool 0x0x7f9d8c334f80 Allocate 0x0x7f9d8c334fe8 thread 140315071608576
Pool 0x0x7f9d8c334f80 Allocate 0x0x7f9d8c3350f0 thread 140315071608576
Pool 0x0x7f9d8c334f80 Release 0x0x7f9d8c3350f0 thread 140315071608576
Pool 0x0x7f9d8c334f80 Allocate 0x0x7f9d8c3350f0 thread 140315071608576
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b558 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d98335590 Release 0x0x7f9d983355f8 thread 140315098867456
Pool 0x0x7f9d98335590 Release 0x0x7f9d98335700 thread 140315098867456
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b558 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Allocate 0x0x7f9d8836b660 thread 140315094656768
Pool 0x0x7f9d8836b4f0 Release 0x0x7f9da0450bd8 thread 140315094656768
Segmentation fault (core dumped)

**Comment by mbrubeck** [comment]
Closing because we are not currently working on parallel painting, I believe.
