### ISSUE TITLE
Compiler Error on macOS:linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by avr1254** [servo/servo#27240]
I'm getting the error listed above, with a note listed at the end.` Undefined symbols for architecture x86_64:
            "_icudt65_dat", referenced from:
                openCommonData(char const*, int, UErrorCode*) in libmozjs_sys-13273380956a7fd9.rlib(udata.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I'm on macOS Catalina 10.15.5, and I'm confused about why I'm getting this error.

**Comment by jdm** [comment]
I believe this occurs when the wrong assembler is used to build ICU (based on [this chat log](https://chat.mozilla.org/#/room/#servo:mozilla.org/$T5tuKb4MGz7JL1fWvQIfb8hjlMs-4xDQzNz3XJFv-TQ)). Make sure you have installed `yasm` from homebrew, and delete `target/debug/build/mozjs*` (or `target/release/build/mozjs*` if you're doing a release build).

**Comment by avr1254** [comment]
Thanks! Worked like a charm!
