### ISSUE TITLE
Unable to set a MediaStream as HTMLMediaElement.srcObject

### ISSUE THREAD

**Issue by ferjm** [servo/servo#27259]
A test like:

```
<video autoplay width=320 height=240></video>
<script>
var constraints = { audio: true, video: true }; 
navigator.mediaDevices.getUserMedia(constraints)
  .then(function(mediaStream) {
      var video = document.querySelector('video');
      video.srcObject = mediaStream;
  })
  .catch(function(err) {
    console.log(err.name + ": " + err.message);
  });
</script>
```

panics with:

```
called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to sync state with parent", filename: "/Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.15.7/src/auto/element.rs", function: "gstreamer::auto::element", line: 634 } (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /Users/ferjm/.cargo/git/checkouts/media-e2c394a143641a4f/d46d87d/backends/gstreamer/media_stream_source.rs:140)
```

This used to work.

**Comment by ferjm** [comment]
The last working nightly is the one from June 30th. So the issue was likely introduced by the servo-media update from #26752

**Comment by ferjm** [comment]
It seems that https://github.com/servo/media/pull/357 introduced the regression

**Comment by atouchet** [comment]
This hasn't been updated in Servo yet.

**Comment by atouchet** [comment]
#27288 updated servo-media.

**Comment by reshab-409** [comment]
function addVideoStream(videoRef, stream) {
    const video = document.createElement('video');
    videoRef.current = video;

    video.srcObject = stream;
    video.addEventListener('loadedmetadata', () => {
      video.play();
    });
    videoGridRef.current.append(video);
  }


how to fix this code?
This code shows __Failed to set the 'srcObject' property on 'HTMLMediaElement'

**Comment by jdm** [comment]
@reshab-409 Could you open a new issue for that, please?
