### ISSUE TITLE
Implement "get element target" and "get element noopener" algorithms

### ISSUE THREAD

**Issue by jdm** [servo/servo#27253]
Spec:
* https://html.spec.whatwg.org/multipage/semantics.html#get-an-element's-target
* https://html.spec.whatwg.org/multipage/links.html#get-an-element's-noopener

We'll want to replace the places in the code that do these in an ad-hoc fashion, like [this](https://github.com/servo/servo/blob/f63b404e0cbf30380c4043700861110d06e548bb/components/script/dom/htmlanchorelement.rs#L605-L617) and [this](https://github.com/servo/servo/blob/f63b404e0cbf30380c4043700861110d06e548bb/components/script/dom/htmlformelement.rs#L390) and ensure we're following the relevant spec steps  in https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission-algorithm:get-an-element's-noopener and https://html.spec.whatwg.org/multipage/links.html#following-hyperlinks:get-an-element's-target.

**Comment by avr1254** [comment]
@highfive  I'll take this one.

**Comment by avr1254** [comment]
A question about unpacking: how do I unwrap a Document from DomRoot<Document>? I'm pretty sure it's not unwrap(), but I couldn't find a suitable function in root.rs. This unwrap would be useful for step 2 of getting an element's target.

**Comment by jdm** [comment]
`DomRoot<T>` automatically dereferences to `&T` when you use `*` or call a method on the underlying T type.

**Comment by avr1254** [comment]
Great, thanks!

**Comment by avr1254** [comment]
Another question, how do I gain access to a specific button wrapped in the enum FormSubmitter? I'm trying to check whether or not the submit button has a formtarget attribute value.

**Comment by jdm** [comment]
@avr1254 It's an enum:
```
pub enum FormSubmitter<'a> {
    FormElement(&'a HTMLFormElement),
    InputElement(&'a HTMLInputElement),
    ButtonElement(&'a HTMLButtonElement),
}
```
You can match on it (or use `if let FormSubmitter::InputElement(input) = input`) and get access to the inner pointer to the DOM object.
