### ISSUE TITLE
ScriptOrigin::text duplicates the string contents

### ISSUE THREAD

**Issue by jdm** [servo/servo#27254]
Since these scripts can be large minified scripts, if there's a way to borrow the result instead that would be preferable.

**Comment by camelid** [comment]
I don't know the context, but what about a `Cow`?

**Comment by jdm** [comment]
I don't think we ever need to mutate the contents of the string, so a straight borrow is probably all that would be required.

**Comment by camelid** [comment]
So this would just entail updating all the usages so that it works with a reference instead of an owned value then?

**Comment by jdm** [comment]
Yes, this would require investigating whether it's possible to avoid using an owned value in the code that relies on this method.

**Comment by camelid** [comment]
Is it okay to introduce a lifetime to [`ModuleTree`](https://doc.servo.org/script/script_module/struct.ModuleTree.html) so that the `text` field can be `DomRefCell<&'a DOMString>` instead of `DomRefCell<DOMString>`? Or is there a better way to do it that won't affect other code?

**Comment by jdm** [comment]
One other option would be storing `Rc<DOMString>`. I suspect introducing a lifetime might be tricky.

**Comment by camelid** [comment]
Yeah, that's kind of what I was thinking. I think I'll try that later today :)

**Comment by camelid** [comment]
@jdm I changed `ScriptOrigin.text` to be an `Rc<DOMString>`, but I'm getting this (among other) errors:

```
error[E0277]: the trait bound `std::rc::Rc<dom::bindings::str::DOMString>: malloc_size_of::MallocSizeOf` is not satisfied
   --> components/script/dom/htmlscriptelement.rs:152:23
    |
152 | #[derive(JSTraceable, MallocSizeOf)]
    |                       ^^^^^^^^^^^^ the trait `malloc_size_of::MallocSizeOf` is not implemented for `std::rc::Rc<dom::bindings::str::DOMString>`
    |
    = note: required by `malloc_size_of::MallocSizeOf::size_of`
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

What should I do?

**Comment by CYBAI** [comment]
In this case, I think you can add use `ignore_malloc_size_of`attribute to the `text` property so that compiler will ignore `MallocSizeOf` for it.

For example, the `external_underlying_source` property of `ReadableStream` 👇 

https://github.com/servo/servo/blob/12d4c0d5eb029044b347765910a57236343641d7/components/script/dom/readablestream.rs#L49-L59

**Comment by camelid** [comment]
Thanks! What reason should I put for the macro?
