### ISSUE TITLE
Support non-random devtools port

### ISSUE THREAD

**Issue by jdm** [servo/servo#27267]
A user reports that the randomized port makes the process of connecting from desktop Firefox more frustrating.

**Comment by jdm** [comment]
One possible solution:
* store the default debugger port as a preference
* if launching on that port fails, fall back to a random port
* update the preference when a new port is chosen

Another possible solution:
* store the debugger port in the UWP app settings
* when launching the embedding, if there's a port in the app settings pass the `--devtools [port]` argument

The second sounds easier.

**Comment by paulrouget** [comment]
> if launching on that port fails, fall back to a random port

Do you remember why and how often that would happen?

**Comment by paulrouget** [comment]
I'm going for solution 1.

**Comment by jdm** [comment]
> > if launching on that port fails, fall back to a random port
> 
> Do you remember why and how often that would happen?

We added the random debugger port in response to a HoloLens OS update stealing port 6000 when we had that hardcoded, which caused FxR to panic during launch.
