### ISSUE TITLE
Support setting a custom home page

### ISSUE THREAD

**Issue by jdm** [servo/servo#27278]
Rather than always requiring an fxr:// QR code to efficiently load a page, we should make it possible for an FxR installation to set a custom home page.

**Comment by paulrouget** [comment]
I'm not sure to understand. At what point would we setup that custom home page?

**Comment by jdm** [comment]
I was imagining some way of setting a homepage while running the app, so that the next time the browser starts (or the Home button is pressed), the new homepage URL is loaded. This would make developers lives easier.

**Comment by paulrouget** [comment]
They can change the preference (shell.homepage) in the pref panel. Or we can have a custom UI.

**Comment by paulrouget** [comment]
Now that we only show a subset of the preferences, we could just add shell.homepage to the promoted preference list.

**Comment by jdm** [comment]
Exposing some kind of bookmarks UI might be a more effective way of addressing the UX issue (#27416). However, depending on the UI for the homepage preference, maybe that could be a useful stepping stone? As long as the user isn't required to type it in if they're already looking at it.

**Comment by paulrouget** [comment]
How important is this now that we have bookmarks?

I can add a checkbox to the bookmark UI to set the current bookmark as homepage.
Or add the homepage preference to the promoted pref list.

**Comment by jdm** [comment]
I don't think this should be a priority until a partner expresses a particular need for changing the homepage. Let's wait and see how bookmarks are received.
