### ISSUE TITLE
Enable sessionavailable event when launching with fxr://

### ISSUE THREAD

**Issue by jdm** [servo/servo#27272]
The fxr:// handler puts FxR into a kiosk-mode kind of environment that doesn't have a URL bar. It would be good to support automatically entering immersive mode as part of that.

**Comment by paulrouget** [comment]
So we would set the pref `dom.webxr.sessionavailable` to true if the app is start from `fxr://`?

**Comment by paulrouget** [comment]
Can I have an example that would support sessionavailable to make sure this works as expected?

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/webxr/sessionavailable.html is the only content that exists right now - the `sessionavailable` event is fired at the navigator.xr object as part of the page load process, so you could modify any other content add a listener for that event and invoke navigator.xr.requestSession.
