### ISSUE TITLE
Can't open devtools panel from fxr:// kiosk mode

### ISSUE THREAD

**Issue by jdm** [servo/servo#27274]
Loading a URL with fxr:// hides the URL bar, which also hides the devtools button. We should add a separate protocol handler for kiosk mode, and allow one protocol to open the app directly to a target URL without otherwise changing the app's behaviour.

**Comment by paulrouget** [comment]
ok - so we could allow a `fxr://?XXX` handler that would allow us to send commands to servo:

We could do 2 things:
- fxr://?toggleui - open the navigation bar
- fxr://?devtools - toggle the devtools.

toggleui is more generic.

**Comment by paulrouget** [comment]
Also - what is important here, showing the console, or showing the devtools port address?

We could also enable voice command.

**Comment by paulrouget** [comment]
I'm leaning toward 2 options:

- voice command to show the navigation bar, or
- use 2 protocol handlers: `fxr://` and `fxrmin://`

**Comment by jdm** [comment]
I think two handlers makes sense.
