### ISSUE TITLE
Implement console.clear

### ISSUE THREAD

**Issue by jdm** [servo/servo#27294]
Spec: https://console.spec.whatwg.org/#clear
Code: `components/script/dom/console.rs`

We'll need some new devtools integration for this.

**Comment by mustafapc19** [comment]
Hi. I am new-comer to this. But I think I might be able to do this if I was given some additional resources and a little bit of help navigating the codebase.

**Comment by jdm** [comment]
* the WebIDL in components/script/dom/webidls/Console.webidl
* the DOM implementation in components/script/dom/console.rs
* the script->devtools integration in components/devtools_traits
* the devtools server in components/devtools/actors/console.rs

We need our devtools server code in to [send a ConsoleAPI message](https://github.com/servo/servo/blob/916d9e0e3d8574a991b1ac301e68395a8795d0bf/components/devtools/actors/console.rs#L282-L291) with a `level` value of "clear", according to https://searchfox.org/mozilla-central/rev/cf561cece0ca9aeaf0202e68699836d957d0c670/devtools/client/webconsole/utils/messages.js#134-148. That means we need to send a message to the devtools server from the console.rs code when `Console::Clear` is called.

You can test these changes following https://github.com/servo/servo/wiki/Devtools and connecting to an instance of Servo from the Firefox remote devtools.

Please ask questions if anything is unclear!

**Comment by mustafapc19** [comment]
U can assign me for this. I'll ask questions if I find some roadblocks. And thanks for your imput :).
