### ISSUE TITLE
Mach commands aren't functioning

### ISSUE THREAD

**Issue by avr1254** [servo/servo#27319]
All of a sudden it appears that none of my mach commands are working. They all revert to a similar error message: 
`$ ./mach check
error: failed to read `servo/tests/unit/.DS_Store/Cargo.toml`

Caused by:
  Not a directory (os error 20)`

**Comment by jdm** [comment]
Try removing `servo/tests/unit/.DS_Store`?

**Comment by avr1254** [comment]
Worked like a charm. Thanks!
