### ISSUE TITLE
Need libxcb-composite0-dev

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#27327]
On Ubuntu 20.04, I got a linker error with

```
  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
```

This was fixed by installing libxcb-composite0-dev

I'm not sure if this dependency is also necessary on 18.04.

**Comment by jdm** [comment]
Oh, yeah, these were added in https://github.com/servo/servo/pull/27209. We should update the bootstrap.

**Comment by Manishearth** [comment]
Ah, so this is global. Cool.
