### ISSUE TITLE
Use UTF-8 versions of Compile/Execute for scripts

### ISSUE THREAD

**Issue by jdm** [servo/servo#27331]
This will avoid having to encode them as UTF-16 first.

**Comment by avr1254** [comment]
@highfive:assignme

**Comment by avr1254** [comment]
@jdm Maybe this would be an interesting challenge to take on!

**Comment by avr1254** [comment]
@jdm Can you tell me a little more about the issue? I'm assuming you don't mean going through every script and changing the encoding to UTF-8.

**Comment by jdm** [comment]
@avr1254 In https://github.com/servo/servo/blob/5a8023dae76a22e2a86be8db5667de309785db9b/components/script/dom/htmlscriptelement.rs#L451-L456 and https://github.com/servo/servo/blob/5a8023dae76a22e2a86be8db5667de309785db9b/components/script/dom/globalscope.rs#L2606-L2610, we pass UTF-16 bytes to the Compile1 and CompileOffThread spidermonkey APIs. The original bytes we receive from the network are UTF-8 bytes, so we have to encode the bytes as UTF-16 in order to do this. I propose that we call the spidermonkey APIs that accept UTF-8 bytes instead, so we don't have to do the UTF-8->UTF-16 conversion at all.

https://doc.servo.org/mozjs/jsapi/fn.Compile1.html
https://doc.servo.org/mozjs/jsapi/fn.CompileOffThread1.html

**Comment by avr1254** [comment]
@jdm Isn't the second example already using UTF-8 instead of UTF-16?

**Comment by jdm** [comment]
You're right!

**Comment by jdm** [comment]
Aha, here's the other case that I was thinking of: https://github.com/servo/servo/blob/c7bdb1bcc0cd4985277579b7585d1abbbe489287/components/script/script_module.rs#L433-L437
