### ISSUE TITLE
Make it so that a webxr panic can be caught by the Servo/UWP panic handler

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#27344]
The panic described here https://github.com/servo/servo/issues/27270 is not caught by our panic handler (at least in simpleservo).

Before #186, when `device` was dropped here https://github.com/servo/webxr/blob/b170a86c081f762d201d3e870febc6e900ad365b/webxr-api/session.rs#L519 a panic would happen, but our [`catch_any_panic`](https://github.com/servo/servo/blob/9bbe9c837a4ce9c877c350ae556dd873e6d35924/ports/libsimpleservo/capi/src/lib.rs#L55) function would not catch it.

We want to catch such panics because we want eventually to be able to inform the user (see https://github.com/servo/servo/issues/27167).

**Comment by jdm** [comment]
I think we need to call panic::set_hook like we do for the winit port: https://github.com/servo/servo/blob/fdbecc68cf45243980efa7fee3846bf29a1f9c25/ports/winit/main2.rs#L140

**Comment by paulrouget** [comment]
Fixed by #27438
