### ISSUE TITLE
Vendor WebGPU CTS

### ISSUE THREAD

**Issue by jdm** [servo/servo#27395]
Per https://github.com/web-platform-tests/wpt/issues/24699, it's recommended that we setup our own WebGPU CTS vendoring automation like we did for the WebGL conformance tests (https://github.com/servo/servo/tree/master/tests/wpt/webgl/tools).

cc @kunalmohan

**Comment by kunalmohan** [comment]
@jdm How would I go about adding/initializing logs in the metadata directory? Are there any steps that I could refer to?

**Comment by jdm** [comment]
@kunalmohan The steps for adding a new testsuite that is part of our web-platform-tests infrastructure go something like this:
* import a copy of the test files under wpt/webgpu/tests
* add a new webgpu manifest entry in https://github.com/servo/servo/blob/master/tests/wpt/config.ini
* perform any transformations to the test files that are necessary to have them be integrate with testharness.js
* run `./mach update-manifest`
* run `./mach test-wpt tests/wpt/webgpu --log-raw webgpu.log`
* run `./mach update-wpt webgpu.log`

Steps 1 and 3 are the most fiddly - if the CTS already supports outputting WPT-compatible tests, that should make the process easier. For the WebGPU tests, we apply a series of patches to the test files that add `<script>` blocks ([eg](https://github.com/servo/servo/blob/49870f92177f556eb24f4d2c13ca67084dd0359e/tests/wpt/webgl/tools/import-conformance-tests.py#L57)) and create automated test names ([eg](https://github.com/servo/servo/blob/master/tests/wpt/webgl/tools/js-test-pre.patch)) in order to allow the WPT harness to run them successfully.

**Comment by jdm** [comment]
Making the import run automatically through a python script is best, but starting off by importing the unmodified files, making a commit, then modifying files by hand until the tests run makes it easier to turn the resulting diff into a script.

**Comment by kunalmohan** [comment]
@jdm I have added the test suite [here](https://github.com/kunalmohan/servo/tree/webgpu-cts/tests/wpt/webgpu). The changes that I had to make after importing unmodified tests are in https://github.com/kunalmohan/servo/commit/c67f68d4a60675232ac7587b18c48a61fef09fea.
What do you think?

**Comment by jdm** [comment]
We should avoid depending on third-party code that is retrieved from the network while running tests. One possible solution is to vendor that module as well. Otherwise the changes look good!

**Comment by jdm** [comment]
You will also want a `__dir__.ini` in the root meta directory that enables the webgpu preference when running the tests.
