### ISSUE TITLE
Separate pref panel for select WebXR prefs

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#27419]
It would be nice to have a separate pref panel for select WebXR prefs (or perhaps "prefs we wish users to use")

This would include `dom.webxr.hands.enabled`, `dom.webxr.layers.enabled`, `dom.webxr.sessionavailable`, and the proposed `dom.webxr.first_person_observer_view` from https://github.com/servo/servo/pull/27418 . These should have text labels and perhaps icons as opposed to pref string labels.

Some non-webxr prefs that may be useful are `dom.webgl2.enabled`, `dom.webrtc.enabled`, and `dom.webrtc.transceiver.enabled`.

cc @paulrouget @jdm

**Comment by Manishearth** [comment]
We could simply have a "preferences" tab and "all config options" tab or something like that.

**Comment by jdm** [comment]
Yeah, I'd like to have a panel that highlights the ones that will be most likely to be useful.

**Comment by paulrouget** [comment]
We will promote these prefs in a "Developer Preview Features" tab:

- dom.webxr.hands.enabled
- dom.webxr.layers.enabled
- dom.webxr.sessionavailable
- dom.webxr.first_person_observer_view
- dom.webgl2.enabled
- dom.webrtc.enabled
- dom.webrtc.transceiver.enabled

With descriptive labels.

I'll look into this.

**Comment by paulrouget** [comment]
I transformed the regular pref panel into a white listed list of preferences, with a checkbox to switch back to a regular list.

It's fairly simple to add a pref to this. I added a XML file listing the white listed pref, with their respective descriptions:

```
  <data name="dom.webxr.hands.enabled"><value>WebXR: Enable XRJointPose (hands joints positions)</value></data>
  <data name="dom.webxr.layers.enabled"><value>WebXR: Enable composition layers</value></data>
  <data name="dom.webxr.sessionavailable"><value>WebXR: Enable "sessionavailable" event</value></data>
  <data name="dom.webxr.first_person_observer_view"><value>WebXR: Enable first person observer view</value></data>
  <data name="dom.webgl2.enabled"><value>Enable WebGL2</value></data>
  <data name="dom.webrtc.enabled"><value>Enable WebRTC</value></data>
  <data name="dom.webrtc.transceiver.enabled"><value>WebRTC: Enable transceiver</value></data>
</root>
```

<img width="1079" alt="Screen Shot 2020-08-04 at 12 50 40" src="https://user-images.githubusercontent.com/373579/89285756-3e0dac80-d651-11ea-8555-28ecdd0f893d.png">

<img width="1076" alt="Screen Shot 2020-08-04 at 12 50 55" src="https://user-images.githubusercontent.com/373579/89285888-79a87680-d651-11ea-9e79-1e658791010e.png">

**Comment by Manishearth** [comment]
Can you include the hand input pref?

**Comment by paulrouget** [comment]
> Can you include the hand input pref?

It's included. See all the included prefs here: https://github.com/servo/servo/pull/27491/files#diff-4d55fbfbb42ef6218f664827cd7c29d5R120
