### ISSUE TITLE
Support bookmarks

### ISSUE THREAD

**Issue by jdm** [servo/servo#27416]
As an alternative to #27278, we should make it easy to return to a URL that you care about without having to type it in or make a QR code.

**Comment by jdm** [comment]
Here's one possible UX for this:
* add a new "bookmark this" button next to the URL bar
* add a "view bookmarks" button somewhere in the main button strip

When "view bookmarks" is pressed, pop up a scrollable list of stored bookmarks. Ideally, each entry should have a button to delete it as well.

**Comment by paulrouget** [comment]
Ok - I will experiment with a "Star" button, that would show a panel to set the current URL as bookmark or homepage. I'll see what's the best way to show the bookmark list.
