### ISSUE TITLE
Prompt user for authentication when HTTP request needs it

### ISSUE THREAD

**Issue by jdm** [servo/servo#27439]
https://github.com/servo/servo/blob/08366323ef4ac77aa812d44499037bab4bc60eeb/components/net/http_loader.rs#L1571-L1578 and https://github.com/servo/servo/blob/08366323ef4ac77aa812d44499037bab4bc60eeb/components/net/http_loader.rs#L1606-L1612 require integration with the embedding layer in order to request user/password information from the browser UI.

We will need to store an [EmbedderProxy](https://github.com/servo/servo/blob/08366323ef4ac77aa812d44499037bab4bc60eeb/components/net/resource_thread.rs#L597) in [HttpState](https://github.com/servo/servo/blob/08366323ef4ac77aa812d44499037bab4bc60eeb/components/net/http_loader.rs#L83). This will allow us to send messages to the embedder from within the HTTP fetching code linked earlier.

We can then send two [EmbedderMsg::Prompt messages](https://doc.servo.org/embedder_traits/enum.PromptDefinition.html) and wait on the responses from the channel that is sent as part of that message, which will contain the username and password values chosen by the user.

To test this, run the following code under python3:
<details>

```
import http.server
import cgi
import base64
import json
from urllib.parse import urlparse, parse_qs


class CustomServerHandler(http.server.BaseHTTPRequestHandler):

    def do_HEAD(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()

    def do_AUTHHEAD(self):
        self.send_response(401)
        self.send_header(
            'WWW-Authenticate', 'Basic realm="Demo Realm"')
        self.send_header('Content-type', 'application/json')
        self.end_headers()

    def do_GET(self):
        key = self.server.get_auth_key()

        ''' Present frontpage with user authentication. '''
        if self.headers.get('Authorization') == None:
            self.do_AUTHHEAD()

            response = {
                'success': False,
                'error': 'No auth header received'
            }

            self.wfile.write(bytes(json.dumps(response), 'utf-8'))

        elif self.headers.get('Authorization') == 'Basic ' + str(key):
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()

            getvars = self._parse_GET()

            response = {
                'path': self.path,
                'get_vars': str(getvars)
            }

            base_path = urlparse(self.path).path
            if base_path == '/path1':
                # Do some work
                pass
            elif base_path == '/path2':
                # Do some work
                pass

            self.wfile.write(bytes(json.dumps(response), 'utf-8'))
        else:
            self.do_AUTHHEAD()

            response = {
                'success': False,
                'error': 'Invalid credentials'
            }

            self.wfile.write(bytes(json.dumps(response), 'utf-8'))

    def do_POST(self):
        key = self.server.get_auth_key()

        ''' Present frontpage with user authentication. '''
        if self.headers.get('Authorization') == None:
            self.do_AUTHHEAD()

            response = {
                'success': False,
                'error': 'No auth header received'
            }

            self.wfile.write(bytes(json.dumps(response), 'utf-8'))

        elif self.headers.get('Authorization') == 'Basic ' + str(key):
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()

            postvars = self._parse_POST()
            getvars = self._parse_GET()

            response = {
                'path': self.path,
                'get_vars': str(getvars),
                'get_vars': str(postvars)
            }

            base_path = urlparse(self.path).path
            if base_path == '/path1':
                # Do some work
                pass
            elif base_path == '/path2':
                # Do some work
                pass

            self.wfile.write(bytes(json.dumps(response), 'utf-8'))
        else:
            self.do_AUTHHEAD()

            response = {
                'success': False,
                'error': 'Invalid credentials'
            }

            self.wfile.write(bytes(json.dumps(response), 'utf-8'))

        response = {
            'path': self.path,
            'get_vars': str(getvars),
            'get_vars': str(postvars)
        }

        self.wfile.write(bytes(json.dumps(response), 'utf-8'))

    def _parse_POST(self):
        ctype, pdict = cgi.parse_header(self.headers.getheader('content-type'))
        if ctype == 'multipart/form-data':
            postvars = cgi.parse_multipart(self.rfile, pdict)
        elif ctype == 'application/x-www-form-urlencoded':
            length = int(self.headers.getheader('content-length'))
            postvars = cgi.parse_qs(
                self.rfile.read(length), keep_blank_values=1)
        else:
            postvars = {}

        return postvars

    def _parse_GET(self):
        getvars = parse_qs(urlparse(self.path).query)

        return getvars


class CustomHTTPServer(http.server.HTTPServer):
    key = ''

    def __init__(self, address, handlerClass=CustomServerHandler):
        super().__init__(address, handlerClass)

    def set_auth(self, username, password):
        self.key = base64.b64encode(
            bytes('%s:%s' % (username, password), 'utf-8')).decode('ascii')

    def get_auth_key(self):
        return self.key


if __name__ == '__main__':
    server = CustomHTTPServer(('', 8888))
    server.set_auth('demo', 'demo')
    server.serve_forever()
```

</details>
Then load `http://localhost:8888` in Servo (and any other browser to verify). The username `demo` with password `demo` should successfully pass the authentication check; everything else should continue to show the authentication prompt.

**Comment by mustafapc19** [comment]
Can I try this? I might be able to do this. With your help ofcourse 🙂

**Comment by jdm** [comment]
Go for it! Please ask questions if anything is unclear!

**Comment by mustafapc19** [comment]
Yeah. Assign me 👍

**Comment by paulrouget** [comment]
> We can then send two EmbedderMsg::Prompt messages and wait on the responses from the channel that is sent as part of that message, which will contain the username and password values chosen by the user.

I think it wouldn't be too hard to also introduce a `Prompt::Credential` here: https://github.com/servo/servo/blob/9b6b7935e66647846ce4b2feaa9089f6b46b42ab/components/embedder_traits/lib.rs#L116

**Comment by jdm** [comment]
Agreed, but it will be easiest for a new contributor to use the existing messages rather than also introducing new ones.

**Comment by mustafapc19** [comment]
I'll try to implement prompt:: Credentials and if I fail to. I'll do the sending twice thingy

**Comment by ritwickdsouza** [comment]
Hey @mustafapc19, are you still working on this task? If not can I work on it?

**Comment by mustafapc19** [comment]
I kinda have the pr almost ready but then Mozilla defunded the project. Should send the pr @jdm ?

**Comment by ritwickdsouza** [comment]
Ah, i see. thanks

**Comment by jdm** [comment]
I would review it :)

**Comment by mustafapc19** [comment]
Yeah. The issue I was facing then was that I was inserting the (http:: Authentication and the required string) in the response object's header map. But in server the Authentication header for some reason is None. Sadly I still can't figure. If u feel nostalgic about servo, u can help ? 🥺

**Comment by jdm** [comment]
The header needs to be added to the request, rather than the response.

**Comment by Wowo10** [comment]
Since this looks to me like abandoned since half a year. Mind if I take over?

**Comment by mustafapc19** [comment]
> Since this looks to me like abandoned since half a year. Mind if I take over?

Yeah sure. I think I have implemented the feature but I didn't get the time to write the test for it. Go for it 🚀

**Comment by arthmis** [comment]
@jdm can I take on this issue?

**Comment by arthmis** [comment]
so I've run into an issue. It seems prompting on windows doesn't work. I get a prompt window, I enter `demo` for the username but then servo hangs/freezes. I tested the same code on my macbook and I can get through the `username` and then the `password` prompt and receive those values in the `IpcReceiver`. So I'll have to look into why it's hanging on the prompt on windows

**Comment by mukilan** [comment]
>  It seems prompting on windows doesn't work.

Just an FYI, I believe our Outreachy intern (@chickenleaf) also faced a similar issue recently. We are looking into replacing tinyfiledialog with egui-file-dialog and/or egui-modal. It is likely that the code that shows the dialog window and blocks the embedder thread will be removed soon. So I guess it should be fine to proceed with the changes for this issue, even if the problem with Windows can't be resolved and as long as it works on Linux and Mac. 

cc: @mrobinson

**Comment by chickenleaf** [comment]
@mukilan is this issue mentioned in the internship tasks? For the mini browser. I feel like I added this in my proposal?

**Comment by arthmis** [comment]
I was going to continue development on my mac for this issue then look into the windows issue afterwards so that's good to hear.
