### ISSUE TITLE
Make C++ log function use stdout

### ISSUE THREAD

**Issue by jdm** [servo/servo#27441]
Right now https://github.com/servo/servo/blob/08366323ef4ac77aa812d44499037bab4bc60eeb/support/hololens/ServoApp/strutils.h#L21 uses OutputDebugString directly. Since we have stdout redirect to OutputDebugString (as well as log to a file) in [this code](https://github.com/servo/servo/blob/08366323ef4ac77aa812d44499037bab4bc60eeb/support/hololens/ServoApp/ServoControl/Servo.cpp#L100-L115), we should be able to use printf from that log code and get more useful output in stdout.txt as a benefit.

cc @paulrouget

**Comment by camelid** [comment]
So would this just entail changing all calls of `OutputDebugString(...)` to `cout << ...`?

**Comment by jdm** [comment]
In the function that I linked, yes.
