### ISSUE TITLE
Implement table layout in 2020

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#27459]
https://drafts.csswg.org/css-tables/

I'm planning on working on at least part of this.

**Comment by Manishearth** [comment]
cc @SimonSapin @pcwalton 

So my rough plan is this:

 - Implement the HTML table construction algorithm (https://html.spec.whatwg.org/multipage/tables.html#forming-a-table)
 - Implement basic `table-layout: fixed` cell distribution, including row/colspans
 - Implement the full table cell width distribution algorithm
 - Border collapse
 - Table, group, row and colspan backgrounds

**Comment by pcwalton** [comment]
Looks good.

**Comment by mrobinson** [comment]
Tables are now enabled in Layout 2020 and we will gradually make them more feature complete.
