### ISSUE TITLE
Local android build fails

### ISSUE THREAD

**Issue by nicoabie** [servo/servo#27458]
```
error: failed to run custom build command for `gstreamer-sys v0.8.1`

Caused by:
  process didn't exit successfully: `/Users/ngallinal/Development/servo/target/android/debug/build/gstreamer-sys-d056f2c30651b8cd/build-script-build` (exit code: 1)
  --- stderr
  `"pkg-config" "--libs" "--cflags" "gstreamer-1.0 >= 1.16"` did not exit successfully: exit code: 1
  --- stderr
  Requested 'gstreamer-1.0 >= 1.16' but version of GStreamer is 1.14.3

warning: build failed, waiting for other jobs to finish...
   Completed png v0.15.3 in 2.2s
   Completed regex v1.3.9 in 10.1s
   Completed style v0.0.1 custom-build (run) in 12.8s
error: build failed
Build FAILED in 0:03:45
```

Tested in macOS 10.15.6 both builds throw same error with GStreamer:
./mach build --dev --android
./mach build --release --android

**Comment by jdm** [comment]
Yes, we dropped support for Android builds several months ago but didn't rip out the plumbing. You might be able to get around this with with `--media-stack=dummy`, but I don't know if any of the rest of will still build.

**Comment by nicoabie** [comment]
Oh ok, I though Android was supported. Was about to start plumbing old issues to see if they were still valid. That would make no sense now. Feel free to close this issue if it is not relevant.

**Comment by jdm** [comment]
Android may be a platform that we want to support in the future given https://github.com/MozillaReality/servo-unity/, but until we commit to that I'm not going to bother keeping this issue open.
