### ISSUE TITLE
Create a script for updating WebGPU CTS

### ISSUE THREAD

**Issue by jdm** [servo/servo#27508]
https://github.com/servo/servo/pull/27402 included separate commits to import the testsuite. We should automate the steps that will need to be repeated in the future in a python script.

**Comment by jdm** [comment]
@kunalmohan Could you document the manual steps you take to update the CTS?

**Comment by kunalmohan** [comment]
Steps to update WebGPU CTS-
1. Generate the tests from the `main` branch in https://github.com/gpuweb/cts (Steps mentions in the README).
2. Copy all the contents of the `out-wpt/` directory to https://github.com/servo/servo/tree/master/tests/wpt/webgpu/tests/webgpu.
3. Make the following change to the `cts.html` file-
```diff
-<script type=module src=/webgpu/common/runtime/wpt.js></script>
+<script type=module src=../webgpu/common/runtime/wpt.js></script>
```
(And optionally comment any tests that may give unexpected tests results on different backends)
4. Run `./mach update-manifest`.
5. Update test expectations.

**Comment by sagudev** [comment]
Mozilla has rust bin for it: https://searchfox.org/mozilla-central/source/dom/webgpu/tests/cts/vendor
