### ISSUE TITLE
devtools preference actor returns fake values

### ISSUE THREAD

**Issue by jdm** [servo/servo#27510]
https://github.com/servo/servo/blob/90aa0a3d41bc0ff173d061f42911bd72e0dfca6a/components/devtools/actors/preference.rs#L33-L58

This should be using the preference API to retrieve the real values and sending them in the response messages.

**Comment by femisco** [comment]
I would like to work on this issue if you don't mind

**Comment by jdm** [comment]
@femisco Great! You should know a couple things:
* https://github.com/servo/servo/wiki/Devtools describes how to connect to the devtools server from Firefox
* the preference API that I mentioned lives in [prefs.rs](https://github.com/servo/servo/blob/0573e9c60d080ab93b232c15de3cd460af43e1b8/components/config/prefs.rs). In particular, you can use the [pref_map](https://github.com/servo/servo/blob/0573e9c60d080ab93b232c15de3cd460af43e1b8/components/config/prefs.rs) api and [get](https://github.com/servo/servo/blob/0573e9c60d080ab93b232c15de3cd460af43e1b8/components/config/pref_util.rs#L213-L214) to get a preference value by a string name.

**Comment by femisco** [comment]
Thanks, I will have a look at it and get back to you asap.

**Comment by sudarshan-reddy** [comment]
@jdm : I'd like to start looking at this as well. Happy to take a backseat if @femialaka is already working on it though.

**Comment by sudarshan-reddy** [comment]
@jdm : Looked around quite a bit. Would I need to inject the preferences map as a dependency to the PreferencesActor or use this macro  (https://github.com/servo/servo/blob/0573e9c60d080ab93b232c15de3cd460af43e1b8/components/config/prefs.rs#L25) with the static path to construct it in https://github.com/servo/servo/blob/0573e9c60d080ab93b232c15de3cd460af43e1b8/components/devtools/actors/preference.rs#L22 ?

**Comment by jdm** [comment]
I believe the pref! macro can't be used with string variables, so you would need to use the preferences map directly.

**Comment by sudarshan-reddy** [comment]
@jdm : I have a PR open. I'm not sure if I translated what you wanted correctly though. Felt a PR was better to get your opinion versus back and forth questions.
