### ISSUE TITLE
Warnings from remote devtools in Firefox are confusing

### ISSUE THREAD

**Issue by jdm** [servo/servo#27528]
It complains about app version numbers and service workers and shows missing string values, and when things go wrong developers start to look for anything that looks out of the ordinary. We should figure out how to make the warnings not appear if we can.

**Comment by jdm** [comment]
![warns](https://user-images.githubusercontent.com/27658/89569881-574e5e80-d7f3-11ea-999a-3eb026d89697.png)

**Comment by oSoMoN** [comment]
It looks like I forgot to claim the issue before starting work on it. Apologies for that. Can you please assign it to me?
The linked PR is ready for review.
