### ISSUE TITLE
--angle command line argument serves no purpose

### ISSUE THREAD

**Issue by jdm** [servo/servo#27546]
There's still an `--angle` option declared at https://github.com/servo/servo/blob/60ee588c71c6bba9871efaaf0ef68ae05e3e175f/ports/winit/main2.rs#L88-L92 but it's never checked. I suspect we lost this feature as part of the surfman changes?

**Comment by jdm** [comment]
Nevermind, I see the `sm-angle-default` feature is present in components/canvas/Cargo.toml, so we might always be using it now?

**Comment by atouchet** [comment]
I tried testing this out and WebGL content now works without using `--angle` in the winit port. This change first happened in the 2020-04-19 nightly build. This is probably due to #25853 if that helps at all.
