### ISSUE TITLE
Audit Servo for dependencies on mozilla services

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#27581]
We need to audit servo for any dependencies on mozilla services, and decide what to do with each of them.

**Comment by asajeffrey** [comment]
For the moment, we can just put them in comments, then try to something more structured.

**Comment by asajeffrey** [comment]
Off the top of my head
- taskcluster
- AWS and macstadium contracts
- servo.org domain
- @mozilla.com email addresses, e.g. servo-ops

**Comment by jdm** [comment]
https://github.com/google/oss-fuzz/blob/master/projects/servo/project.yaml

**Comment by jdm** [comment]
Cloudflare

**Comment by asajeffrey** [comment]
- MS Store account
- s3 buckets on AWS

**Comment by CYBAI** [comment]
About the CI part, I'm wondering if it's possible to move them to GitHub actions 🤔?

If yes, I would be happy to help!

Also, there's a [bors GitHub app](https://github.com/apps/bors); if we need an quick alternative, it might be an option?

**Comment by jdm** [comment]
GitHub actions would be a fine choice!

**Comment by asajeffrey** [comment]
In the short term will we stick with the current infra? I don't thiiiink we have a CI fire to fight?

**Comment by SimonSapin** [comment]
Closing, let’s move to https://github.com/servo/project/issues/15 and https://github.com/servo/project/issues/25

**Comment by okias** [comment]
@SimonSapin sadly, getting 404 when trying open these.

Do I understand right, that it's not public accessible?

**Comment by jdm** [comment]
Correct. It is expected they will become public at some point in the future.
