### ISSUE TITLE
Configuring with macports + ccache fails on Snow Leopard

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#276]
The macports ccache port sets up a "gcc-4.2" symlink to ccache in /opt/local/libexec/ccache, which is in the PATH so that ccache actually works.

However there is no gcc-4.2 binary or symlink on the OS side anymore, just gcc.

At the same time, servo's configure script decides to use "gcc-4.2" as the C compiler (and "g++-4.2" as the C++ compiler), then errors out because the nonexistent compiler doesn't work...

It may be a better idea to just default to clang/clang++ on Mac; I would think any Mac recent enough that we care about supporting it has clang.

**Comment by jdm** [comment]
We've upgraded spidermonkey since this report.
