### ISSUE TITLE
Font rendering is non-existent.

### ISSUE THREAD

**Issue by daemonspudguy** [servo/servo#27615]
![Screen Shot 2020-08-25 at 18 46 24](https://user-images.githubusercontent.com/24438557/91235332-5a0de680-e703-11ea-9fa5-e1f9d50ce824.png)
I don't think this is supposed to happen.
On macOS Catalina.

**Comment by jdm** [comment]
This is a known issue on some macOS Intel graphics drivers. If you run Servo with `--pref gfx.texture-swizzling.enabled=false` then it should go away. Doing this automatically is tracked in #26224.
