### ISSUE TITLE
Update crate mozjs

### ISSUE THREAD

**Issue by sudarshan-reddy** [servo/servo#27617]
The mozjs crate has had a few updates.

1. Unsafe Handle::new() is now private.
2. NewProxyObject accepts 6 input parameters instead of 4 (new fields: classp and singleton).
3. CompileOptionsWrapper accepts &str as std::ptr.

References: https://github.com/servo/rust-mozjs/issues/518, 
https://github.com/servo/rust-mozjs/issues/519
https://github.com/servo/rust-mozjs/pull/521

**Comment by jdm** [comment]
For NewProxyObject, it should be safe to pass a null pointer and the value `false` for the new arguments for all existing uses.
