### ISSUE TITLE
The Win64 Developer Preview does not work at all!

### ISSUE THREAD

**Issue by deiviuds** [servo/servo#27632]
This is my setup:
- W10 64b Home 2004 (19041.487)
- i7-8750H
- 16GB Ram
- Intel HD 630 + 1050ti 4GB

I've downloaded two times from the website the: **Windows EXE | 2020-08-29**. Between those installations I've tried to completely remove with an uninstaller, just to make sure.

The screen appears as below. I cannot interact with it, neither close it by itself. I have to manually force "end task" on the task manager.

There is no odd ram or cpu usage, also there is no error message or anything at all. I even tried to open an HTML page with it, but the result is the same...

Sorry if I am making this post in the wrong place, or in the wrong way, but I couldn't find any other place more appropriate than this one. If there is anything that I can be helpful I'll try!

I would even try to build myself, but kinda there is no point in that if the official download link isn't working, maybe I've missed something, or the problem is real but I believe is above my skills at the moment to have a solution, but if it is need I will build it. I was really hoping to try what servo is capable off and see if the hype is real! hahaha

![image](https://user-images.githubusercontent.com/25495389/92957308-b761a180-f43e-11ea-8b98-69cd998abea8.png)

**Comment by LinusCDE** [comment]
Not sure, but maybe this is related to issue #26353. On linux it seems to be an issue with the proprietary nvidia drivers. So maybe this is also the same nvidia specific issue on Windows.

**Comment by jdm** [comment]
We have archives of nightly builds on s3: http://servo-builds.s3.amazonaws.com/?list-type=2&prefix=nightly/windows-msvc

**Comment by jdm** [comment]
In any case, this is tracked in #26820.
