### ISSUE TITLE
WebIDL's `void` type is changing to `undefined`

### ISSUE THREAD

**Issue by kunalmohan** [servo/servo#27660]
As part of efforts to finally add an 'undefined' type to WebIDL (so methods/etc don't have to generalize their type to 'any'), it was decided to actually add 'undefined' as the type name, and so the previous function return signature 'void' is being removed for redundancy.

We should update our IDL parser to support the new `undefined` type and remove the `void` type. Or maybe support both types until all specifications move over to new syntax.

Related PR https://github.com/heycam/webidl/pull/906

**Comment by CYBAI** [comment]
Here's the [Gecko bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1659158) for this issue.
