### ISSUE TITLE
¿que sucede con hiddeneye? serveo me genera una url pero no carga ademas no funciona ni ngrok ni localhost

### ISSUE THREAD

**Issue by ayelen912** [servo/servo#27687]
Alguien sabe si esta caido? intente en ubuntu 20 y termux y tengo el mismo problema. Alguien sabe alguna herramienta pishing en el que puedas seleccionar la url a donde la victima sea redirigida. gracias 
![serveo](https://user-images.githubusercontent.com/72417841/95276239-0a9df880-0821-11eb-8203-9fe5270d1402.png)

**Comment by jdm** [comment]
This doesn't look like it's an issue related to the Servo project.
