### ISSUE TITLE
Necesito Ayuda! no me funciona ningun servidor en termux y ubuntu

### ISSUE THREAD

**Issue by ayelen912** [servo/servo#27689]
instale varias herramientas pishing. y ninguno de los servidores me genera un link  (ngrok, serveo, local host) a que se puede deber mi problema. lo intente desde ubuntu y desde termux. gracias espero que me ayuden.
![ngrok](https://user-images.githubusercontent.com/72417841/95423428-706cac00-0917-11eb-8240-2bc701eb23c9.png)
![localhost](https://user-images.githubusercontent.com/72417841/95423447-78c4e700-0917-11eb-8a48-3bf8dd838bf6.png)
![serveo](https://user-images.githubusercontent.com/72417841/95423457-7cf10480-0917-11eb-9518-f036bc10e757.png)

**Comment by jdm** [comment]
This doesn't look like an issue related to the Servo project.

**Comment by ayelen912** [comment]
me podes dar alguna solucion?

**Comment by ameenross** [comment]
Aren't you supposed to post here: https://github.com/DeepSociety/AIOPhish

**Comment by ayelen912** [comment]
no no se supone por que no es un problema de la herramienta alophish. pero de igual modo intentare aver si alguien me explica. saludos virgo

**Comment by ameenross** [comment]
No need to downvote people trying to help you...

I think you misunderstood that serveousercontent.com is somehow related to the Servo browser project. It's not.
