### ISSUE TITLE
Servo launches to black screen [Arch Linux]

### ISSUE THREAD

**Issue by Bug-Reaper** [servo/servo#27681]
Tried building from source. All the following commands launch a window which is just a black screen. 
```
./mach run tests/html/about-mozilla.html --release
./mach run https://google.com --release
./mach run tests/html/about-mozilla.html --dev
./mach run https://google.com --dev
```
No stderrors or anything. Also tried the [AUR maintained servo-git](https://aur.archlinux.org/packages/servo-git/) and it also launches a black screen window.

Was fucking around with --debug but I'm not the best with gdb. Could see one thread dying when running servo. Also two threads will spawn and die immediately when using CTRL+R on the servo window, though it still only ever displays a black screen. 

I might start doing some regression testing to determine when this hit. Any debug tips also appreciated.

**Comment by CYBAI** [comment]
Hi, thanks for your report!
This is a known issue reported at https://github.com/servo/servo/issues/26353 so I'm going to close this one and let's discuss there!

**Comment by Bug-Reaper** [comment]
Thanks! @CYBAI
