### ISSUE TITLE
Unable to start build on Gentoo

### ISSUE THREAD

**Issue by kotelnik** [servo/servo#27751]
Currently gentoo is in process of dropping python2 (end-of-life, vulnerable, etc.), so there is no support of `virtualenv` module for python2. Still virtualenv package is installed and available for python3.

Therefore calling `./mach build --release` result in error:
```
Python virtualenv is not installed. Please install it prior to running mach.
```

Renaming /usr/bin/python2.7 will result in running mach with python3, but it fails on this error:
```
info: downloading installer
rustup: Unable to run interactively. Run with -y to accept defaults, --help for additional options
Error running mach:

    ['build', '--release']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

subprocess.CalledProcessError: Command '['rustup', '--version']' returned non-zero exit status 1.

  File "/home/kotelnik/PROJECT/git-projects/servo/python/servo/build_commands.py", line 243, in build
    self.ensure_bootstrapped(target=target)
  File "/home/kotelnik/PROJECT/git-projects/servo/python/servo/command_base.py", line 998, in ensure_bootstrapped
    self.ensure_rustup_version()
  File "/home/kotelnik/PROJECT/git-projects/servo/python/servo/command_base.py", line 1031, in ensure_rustup_version
    version_line = subprocess.check_output(["rustup" + BIN_SUFFIX, "--version"])
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
```

But rustup is in path and calling `rustup --version` in the same terminal session results in exit status 0 and these printed lines:
```
info: downloading installer
rustup-init 1.22.1 (b01adbbc3 2020-07-08)
```

Am I doing something wrong? Or is that because of the missing python2 support in gentoo? Thanks!

**Comment by SimonSapin** [comment]
This part looks relevant:

```
rustup: Unable to run interactively. Run with -y to accept defaults, --help for additional options
```

This might be a new behavior of rustup that CI hasn’t encountered yet because it already has an older version installed.

**Comment by SimonSapin** [comment]
So that’s likely not your immediate issue, but I’m not sure of the support status for Python 3 only. https://github.com/servo/servo/issues/23607 is still open.

**Comment by SimonSapin** [comment]
On closer look it appears that `rustup` in your `$PATH` is the [`rustup-init.sh` bootstrapping script](https://github.com/rust-lang/rustup/blob/master/rustup-init.sh) rather than rustup itself. That script is intended to only run once in order to download the appropriate binary for your platform, not be installed itself in `$PATH`. Or if you want to use [a distribution package](https://packages.gentoo.org/packages/dev-util/rustup) to install rustup, I’d expect that script not to be involved at all.

What’s the output of `which rustup`? How did you install this?

**Comment by kotelnik** [comment]
Thanks for pointing out the rustup issue. This is my bad, I actually forgot to run the rustup script in the beginning and just installed it.

So to start the build on gentoo, one just has to rename python2.7 to something non-existing so python3 kicks in - e.g. like this:
```
diff --git a/mach b/mach
index 9758e1e2ce..5657b5f5d5 100755
--- a/mach
+++ b/mach
@@ -6,7 +6,7 @@
 # The beginning of this script is both valid shell and valid python,
 # such that the script starts with the shell and is reexecuted with
 # the right python.
-''':' && if [ ! -z "$MSYSTEM" ] ; then exec python "$0" "$@" ; else which python2.7 > /dev/null 2> /dev/null && exec python2.7 "$0" "$@" || exec python "$0" "$@" ; fi
+''':' && if [ ! -z "$MSYSTEM" ] ; then exec python "$0" "$@" ; else which python2.7_ > /dev/null 2> /dev/null && exec python2.7 "$0" "$@" || exec python "$0" "$@" ; fi
 '''
 
 from __future__ import print_function, unicode_literals
```

Next problem on libressl enabled gentoo is compiling `net` component which ends up with error:
```
error: failed to run custom build command for `net v0.0.1 (/home/kotelnik/PROJECT/git-projects/servo/components/net)`

Caused by:
  process didn't exit successfully: `/home/kotelnik/PROJECT/git-projects/servo/target/release/build/net-35fdf45b58e3e1ba/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'missing DEP_OPENSSL_VERSION_NUMBER: NotPresent', components/net/build.rs:7:53
```

This can be fixed by:
```
diff --git a/components/net/Cargo.toml b/components/net/Cargo.toml
index 3a413617b7..6570f58515 100644
--- a/components/net/Cargo.toml
+++ b/components/net/Cargo.toml
@@ -44,7 +44,7 @@ mime = "0.3"
 mime_guess = "2.0.0"
 msg = { path = "../msg" }
 net_traits = { path = "../net_traits" }
-openssl = "0.10"
+openssl = { version = "0.10", features = ["vendored"] }
 openssl-sys = "0.9"
 percent-encoding = "2.0"
 pixels = { path = "../pixels" }
```

Then almost everything is compiled successfully. In the end it fails with a large error log when compiling last component - `servo`. The issue basically is related to inline namespaces: `error: undefined reference to 'std::__1::...`. Can you please tell, what should be done on my side to fix that?

Here is the full error:
[servo_error.log](https://github.com/servo/servo/files/5530554/servo_error.log)

**Comment by SimonSapin** [comment]
> one just has to rename python2.7 to something non-existing so python3 kicks in

You can also run it explicitly like `python3 ./mach build`, or set your `$PATH` such as `python` is Python 3.

> Next problem on libressl enabled gentoo is compiling `net` component which ends up with error:

Looks like you made it work by using vendored OpenSSL. We could some `mach`-level configuration to let you enable that more easily. However I don’t know if there’s a reason LibreSSL couldn’t be made to work too.

The missing `$DEP_OPENSSL_VERSION_NUMBER` environment variable is normally set by Cargo based on the output of this code: https://github.com/sfackler/rust-openssl/blob/openssl-v0.10.30/openssl-sys/build/main.rs#L233

See https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key for documentation about this mechanism for passing data around between build scripts of different crates.

In that code we can see that a different variable is set when LibreSSL is used: https://github.com/sfackler/rust-openssl/blob/openssl-v0.10.30/openssl-sys/build/main.rs#L198

Here is some code that looks at both, that could be used as an example: https://github.com/sfackler/rust-openssl/blob/openssl-v0.10.30/openssl/build.rs#L20-L67

Now, Servo’s `net` crate checks for OpenSSL >= 1.1.1 but I don’t know why. If we can find out which features are required and what LibreSSL versions have that feature, we could change `components/net/build.rs` to also look at `$DEP_OPENSSL_LIBRESSL_VERSION_NUMBER`.

> In the end it fails with a large error log when compiling last component

Those are linking errors. Those are hard to read but after removing the less-relevant details and the repetition they mean:

* Some Rust code in the `gstreamer_gl` crate has FFI bindings to a `gst_gl_display_x11_new_with_display` function that isn’t found
* Some C++ code…
  - In the `mozangle` crate
  - In the `mozjs` crate (in the `intl/icu` directory)
  - In the `fontsan` crate
  - In `/usr/include/c++/v1/`, probably included by some of the above

  … uses some C++ standard library symbols such as `std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)`, that aren’t found

That first function is apparently part of `gst-plugins-bad`, and https://packages.gentoo.org/packages/media-libs/gst-plugins-bad says there’s an `X` use flag that controls X11 support. Do you have that installed/enabled?

As for the rest, something that could explain it is if a different version of the C++ standard library is used at compilation time v.s. at link time. I don’t know how to investigate this further, though.

**Comment by jdm** [comment]
The OpenSSL build check was added in https://github.com/servo/servo/pull/25736 to ensure we didn't attempt to build with versions of openssl that were missing support for set_sigalgs_list in rust-openssl.

**Comment by Darkspirit** [comment]
> Looks like you made it work by using vendored OpenSSL. We could add some mach-level configuration to let you enable that more easily. 

#26117 would have fixed that. I assume it was mergeable although I didn't remove the custom OpenSSL build code for the disabled and broken Android target. Let's abandon that.

----

I have been asked to make a new PR for Rustls, this is my WIP: https://github.com/Darkspirit/servo/compare/master...rustls
(If my horrible concentration capability regresses again, please take it as inspiration for an own PR.)
Once ring supports UWP (which was promised to me last week and active work is going on) we could drop OpenSSL and switch to Rustls, if Servo's TSC agrees.

Let's Encrypt is also pushing it forward: https://www.abetterinternet.org/post/memory-safe-curl/

Quote from https://jbp.io:
> The Cloud Native Computing Foundation (a part of the Linux Foundation) funded this [audit](https://github.com/ctz/rustls/blob/master/audit/TLS-01-report.pdf), at the request of Buoyant who use rustls in the data plane of linkerd. So further thanks are due to Chris Aniszczyk of the Linux Foundation, and Oliver Gould of Buoyant for their support of these projects.

**Comment by kotelnik** [comment]
Thanks for directions regarding building!

> You can also run it explicitly like python3 ./mach build, or set your $PATH such as python is Python 3.

Calling ./mach with preceding python3 worked. `python` being version 3 as default wasn't enough. Also there seems to be `python2` (N/A by default in gentoo) needed as well for finishing the whole build.

Replacing openssl/libressl with rustls is IMO the best way to go, thanks for the effort! :)

> `gst-plugins`...

Sorry about that, this was mentioned here: https://github.com/servo/servo/issues/26208
Fixed with the `X` flag, thanks!

Now to the `std::__1::` errors. That puzzled me for a while! After removing `default-libcxx` flag from `sys-devel/clang` (and rebuilding it), servo binary built successfully. Although I would expect that this could also be fixed by e.g. setting `RUSTFLAGS="-C link-args=-shared-libc++"` but I'm no expert on this.

**Comment by kotelnik** [comment]
> `python2` (N/A by default in gentoo)

This was false, `python2` actually is available in standard gentoo

**Comment by mrobinson** [comment]
I think we can close this as everything should be running Python 3 now.
