### ISSUE TITLE
while downloading the nightly-build servo of macOS, it still uses the older logo, not the newer one.

### ISSUE THREAD

**Issue by Kilerd** [servo/servo#27775]
![Screen Shot 2020-11-18 at 9 25 06 AM](https://user-images.githubusercontent.com/3162379/99470628-fbfa4380-297f-11eb-81f4-e7e2d966f41e.png)

**Comment by jdm** [comment]
This appears to come from https://github.com/servo/servo/blob/16bdf9225dd979feeea1580f78041016ce41643f/resources/servo.icns based on https://github.com/servo/servo/blob/16bdf9225dd979feeea1580f78041016ce41643f/Info.plist#L10.

**Comment by atouchet** [comment]
It appears the .icns icon change got lost in #25846. I will try to fix this.

**Comment by atouchet** [comment]
I opened #27777 to update with the .icns file that @malqinneh made in #25846. I would appreciate if someone could take a look to make sure that fixes the issue as I can't easily test it myself.

**Comment by SimonSapin** [comment]
Is this a bug or a feature? :)

**Comment by Kilerd** [comment]
I think it's a bug, cause nightly-build servo did not use the new logo.
