### ISSUE TITLE
Servo hangs (100% CPU) on startup on macOS

### ISSUE THREAD

**Issue by zcorpan** [servo/servo#27778]
I downloaded the macOS installer from https://download.servo.org/ (build date 2020-11-17). Dragged Servo.app into Applications and then opened Servo.

**Actual result**

Servo hangs and uses 100% CPU. Activity Monitor says "Not Responding" after a while. Reproduces every time.

**Expected result**

Not that.

**Environment**

macOS 10.14.6 (18G95). Yes, I know it's not the latest. If it's not compatible, it could be good to say that on the downloads page. :)

**Comment by deltabeard** [comment]
I have the same problem on Windows 10 with the Windows ZIP version built on 2020-11-19. Servo hangs on startup and must be killed with task manager.

**Comment by deltabeard** [comment]
This issue does not occur on my other computer: Windows 10 20H2, Intel i5-4570, Nvidia GTX 760.
But the issue does occur on my laptop: Windows 10 1909, Intel i7-8650U, Intel UHD 620 + AMD Radeon 550.

**Comment by deltabeard** [comment]
I did some more testing on my laptop with the Windows ZIP 2020-11-20 build. I get the same white screen with this version.  However, if I override the High DPI settings for the servo executable to "Application", servo starts working.

![image](https://user-images.githubusercontent.com/3747104/99786098-fc2c4780-2b15-11eb-99b1-20df84dd0930.png)

**Comment by deltabeard** [comment]
I think my issue is actually https://github.com/servo/servo/issues/26820 and not related to the issue OP was having.

**Comment by cfvescovo** [comment]
I am experiencing the same issue on my MacBook Pro (Retina, 13-inch, Early 2015) with macOS Big Sur (11.0.1)

**Comment by MeiK2333** [comment]
MacBook Pro (16-inch, 2019) with macOS Big Sur 11.0.1 (20B50)

I downloaded the servo from <https://download.servo.org/nightly/mac/servo-latest.dmg>

![image](https://user-images.githubusercontent.com/20951666/102033643-eb11e600-3df6-11eb-9545-af1eeaf5cdef.png)

**Comment by thor468areavailable** [comment]
Yes yes

**Comment by endearingyoungcharms** [comment]
I tried launching Servo from the terminal on Big Sur 11.0.1. When executed, it returns the following error message:
`arch: /usr/local/Cellar/gstreamer/1.18.1/libexec/gstreamer-1.0/gst-plugin-scanner isn't executable`
The latest version of gstreamer, according to brew, is 1.18.1. Therefore, I think that an outdated package is the issue.
Looks like we will have to wait until a new binary is compiled.

**Comment by stalkerg** [comment]
Same on Linux, maybe not 100%, but 50-80% without any interaction on the default static page.

**Comment by zcorpan** [comment]
Works fine now on macOS 14.1.1 with a Servo build downloaded today.

I'll close since I assume enough has changed for both macOS and Servo that the original issue is either long gone or irrelevant.
