### ISSUE TITLE
UWP installer actually tries to install x64 on aarch64

### ISSUE THREAD

**Issue by soapdog** [servo/servo#27772]
There is something either wrong with the installer script or with the build artifacts for the UWP pre-built version of Servo. It attempts to install a x64 version when running on an AARCH64 machine, thus failing the installation process and leaving the computer with the dev certificate installed.

**Comment by jdm** [comment]
I'm honestly not sure what we can do about this. We run some MS tools to create the packages, and the installer script is automatically generated as part of that.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/856d18250b63063644e36b7e67afc231c10d4461/python/servo/package_commands.py#L814-L859

**Comment by soapdog** [comment]
I'll try to dig deeper during the weekend. What has tripped me before is that some scripts and tools will get confused because machines like the Surface Pro X will return that they are 64-bits and they'll assume x64. Maybe it is something like that that is happening.

**Comment by soapdog** [comment]
```
Installing app...
Found dependency package(s):
C:\Users\andre\Downloads\servo\Dependencies\x86\Microsoft.UI.Xaml.2.4.appx
C:\Users\andre\Downloads\servo\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx
C:\Users\andre\Downloads\servo\Dependencies\x64\Microsoft.UI.Xaml.2.4.appx
C:\Users\andre\Downloads\servo\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D10, The deployment operation failed because the package
targets the wrong processor architecture.

Windows cannot install package Microsoft.UI.Xaml.2.4 because the package requires architecture x64, but this computer
has architecture ARM64.

NOTE: For additional information, look for [ActivityId] 16d0299f-bcd4-0004-e3fe-d216d4bcd601 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 16d0299f-bcd4-0004-e3fe-d216d4bcd601

At C:\Users\andre\Downloads\servo\Add-AppDevPackage.ps1:441 char:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\andre\...rm64.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Error: Could not install the app.  To ensure security, please consider uninstalling the signing certificate until you can install the app.  Instructions for doing so can be found here:
http://go.microsoft.com/fwlink/?LinkId=243053

Do you want to run software from this untrusted publisher?
File C:\Users\andre\Downloads\servo\TelemetryDependencies\LogSideloadingTelemetry.ps1 is published by CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts
 from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):         
```

On further checking, it appears that it is one of the dependencies that doesn't support ARM64

**Comment by jdm** [comment]
@soapdog We successfully ran the UWP app on arm64 HoloLens 2 devices, so I'm pretty sure this is an issue limited to the Surface Pro X, rather than arm64 in general.

**Comment by soapdog** [comment]
@jdm I am sure you're right, I just thought it was worth reporting since it is not working on the current flagship Windows on ARM device from Microsoft. Chances are that it won't work on other similar machines.

**Comment by zhzy0077** [comment]
I'm now able to install servo on my Surface Pro X with build number 19042.685. Probably Microsoft.UI.Xaml has been shipped for ARM

**Comment by jdm** [comment]
Closing based on the last comment.
