### ISSUE TITLE
can't run gstplugin servowebsrc

### ISSUE THREAD

**Issue by colorhook** [servo/servo#27783]
After building `servo` and `servowebsrc`, run demo with `servowebsrc` failed:

* MacBook Pro (16-inch, 2019)
* macOS Catalina 10.15.6 (19G73)
* Darwin Kernel Version 19.6.0

```
GST_PLUGIN_PATH=target/gstplugins \
  gst-launch-1.0 -e servowebsrc \
    ! video/x-raw\(memory:GLMemory\),framerate=50/1,width=1920,height=1080,format=RGBA \
    ! glimagesink rotate-method=vertical-flip
```

output:

```
设置暂停管道 ...
管道正在使用且不需要 PREROLL ...
从组件“sink”获取上下文：gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayCocoa\)\ gldisplaycocoa0";
管道被 PREROLLED ...
设置播放管道 ...
New clock: GstSystemClock
Error initializing GStreamer: ErrorLoadingPlugins(["libgstapp.dylib", "libgstaudiobuffersplit.dylib", "libgstaudioconvert.dylib", "libgstaudiofx.dylib", "libgstaudioparsers.dylib", "libgstaudioresample.dylib", "libgstautodetect.dylib", "libgstdeinterlace.dylib", "libgstdtls.dylib", "libgstgio.dylib", "libgstid3tag.dylib", "libgstid3demux.dylib", "libgstinterleave.dylib", "libgstisomp4.dylib", "libgstlibav.dylib", "libgstmatroska.dylib", "libgstogg.dylib", "libgstopus.dylib", "libgstplayback.dylib", "libgstproxy.dylib", "libgstrtp.dylib", "libgstrtpmanager.dylib", "libgsttheora.dylib", "libgsttypefindfunctions.dylib", "libgstvideoconvert.dylib", "libgstvideofilter.dylib", "libgstvideoparsersbad.dylib", "libgstvideoscale.dylib", "libgstvorbis.dylib", "libgstvolume.dylib", "libgstvpx.dylib", "libgstwebrtc.dylib", "libgstosxaudio.dylib", "libgstosxvideo.dylib", "libgstnice.dylib"])
````

**Comment by jdm** [comment]
What version of gstreamer do you have installed?

**Comment by colorhook** [comment]
> What version of gstreamer do you have installed?

```
brew info gstreamer
```

output

```
gstreamer: stable 1.18.1 (bottled), HEAD
...
```


```
gst-inspect-1.0 app
```

output:

```
Plugin Details:
  Name                     app
  Description              Elements used to communicate with applications
  Filename                 /usr/local/lib/gstreamer-1.0/libgstapp.dylib
  Version                  1.18.1
  License                  LGPL
  Source module            gst-plugins-base
  Source release date      2020-10-26
  Binary package           GStreamer Base Plug-ins source release
  Origin URL               Unknown package origin

  appsrc: AppSrc
  appsink: AppSink

  2 features:
  +-- 2 elements

```

**Comment by jdm** [comment]
Oh, I bet this is a regression from https://github.com/servo/servo/commit/72040be69bc33b03fabe1048299bed4714616604. The code at https://github.com/servo/servo/blob/3f46bec962caea3ab2552e52492177dfb13751ae/components/servo/lib.rs#L178 expects to be running `./target/[debug,release]/servo` and sets up the plugin path accordingly. All of those missing dylibs are in `target/[debug,release]`, not target/gstplugin.

**Comment by jdm** [comment]
You could work around this by changing [this code](https://github.com/servo/servo/blob/3f46bec962caea3ab2552e52492177dfb13751ae/python/servo/build_commands.py#L739) to refer to target/gstplugin instead so the dylibs are placed in that directory.

**Comment by a-teammate** [comment]
as in #28450 one possible solution to this would be statically linking the gstreamer plugins. This became substantially easier this year, through https://blogs.igalia.com/scerveau/discover-gstreamer-full-static-mode/
bringing servo closer to being totally portable and self-contained (but not reusing the system libs anymore as trade-off)
