### ISSUE TITLE
Debian-based Linux environment setup guide doesn't work on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by 0x00A5** [servo/servo#27792]
```
sudo apt install python-virtualenv python-pip
```
The command above found in [README](https://github.com/servo/servo#on-debian-based-linuxes) doesn't work.
>Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

I have found workaround by doing the same as in #27760

**Comment by o752d** [comment]
Guessing you might swap in:
```bash
sudo apt install python3-virtualenv python3-pip
```

**Comment by seanybaggins** [comment]
@o752d I tried what you suggested. When trying to run 
```
./mach bootstrap
```
I get
```
Python virtualenv is not installed. Please install it prior to running mach.
```

I think there is a bug in the first line of the `mach` script. Its defaulting python2.7 even though python3.8 is installed.
```bash
ls -l /usr/bin | rg python
```
```
lrwxrwxrwx 1 root root           23 Aug  4 04:16 pdb2.7 -> ../lib/python2.7/pdb.py
lrwxrwxrwx 1 root root           23 Jul 28 05:59 pdb3.8 -> ../lib/python3.8/pdb.py
lrwxrwxrwx 1 root root           31 Jul 14 12:06 py3versions -> ../share/python3/py3versions.py
lrwxrwxrwx 1 root root           16 Dec  1 09:41 python -> /usr/bin/python3
-rwxr-xr-x 1 root root      3629032 Aug  4 04:16 python2.7
lrwxrwxrwx 1 root root            9 Jul 14 12:06 python3 -> python3.8
-rwxr-xr-x 1 root root      5486352 Jul 28 05:59 python3.8
lrwxrwxrwx 1 root root           33 Jul 28 05:59 python3.8-config -> x86_64-linux-gnu-python3.8-config
lrwxrwxrwx 1 root root           16 Mar 13  2020 python3-config -> python3.8-config
-rwxr-xr-x 1 root root          384 Mar 27  2020 python3-futurize
-rwxr-xr-x 1 root root          388 Mar 27  2020 python3-pasteurize
-rwxr-xr-x 1 root root         3240 Jul 28 05:59 x86_64-linux-gnu-python3.8-config
lrwxrwxrwx 1 root root           33 Mar 13  2020 x86_64-linux-gnu-python3-config -> x86_64-linux-gnu-python3.8-config

```

Managed to hack this into working by running
```bash
mv /usr/bin/python2.7 /usr/bin/python2.7.bak
```
Definitely not a long term solution.

**Comment by seanybaggins** [comment]
Does anyone understand the if statement in the first line of the `mach` file?

```bash
if [ ! -z "$MSYSTEM" ] ; then exec python "$0" "$@"
```

**Comment by lyuyuan** [comment]
@seanybaggins 
Please try these commands that worked for me,
```
curl https://bootstrap.pypa.io/get-pip.py -sSf -o get-pip.py
python2 get-pip.py
python2 -m pip install virtualenv
```
Use the docker file as reference for more details on how to set up the dev environment: https://github.com/servo/servo/blob/master/etc/taskcluster/docker/base.dockerfile

**Comment by mrobinson** [comment]
Going to close this one since I believe that mach is no longer user Python 2. Please feel free to comment if this is still an issue and we can reopen it.
