### ISSUE TITLE
Implement HTMLKeygenElement

### ISSUE THREAD

**Issue by brunoabinader** [servo/servo#2782]
Spec:
www.whatwg.org/html/#the-keygen-element

CC @Ms2ger

**Comment by nox** [comment]
https://html.spec.whatwg.org/multipage/#the-keygen-element

**Comment by frewsxcv** [comment]
Relevant: https://github.com/whatwg/html/issues/67 https://github.com/whatwg/html/pull/26

**Comment by KiChjang** [comment]
Keygen is deprecated, do we still want to do this?

**Comment by frewsxcv** [comment]
As per the spec:

> This feature is in the process of being removed from the Web platform. (This is a long process that takes many years.) Using the keygen element at this time is highly discouraged.

Doesn't seem worth our time to do anything related to it

**Comment by jdm** [comment]
Agreed.
