### ISSUE TITLE
NoCopy and other markers in smallvec.rs

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#2793]
I just noticed that the `core::slice::MutItems` iterator contains a `NoCopy` marker. We might need something similar in `servo_util::smallvec::SmallVecMutIterator`, and should double check the rest of the unsafe code in the same file.

See #2787.
CC @pcwalton

**Comment by frewsxcv** [comment]
Should this be moved to the smallvec repo?

**Comment by SimonSapin** [comment]
There is nothing to do here: `NoCopy` is not part of the language anymore, and we’re now using the slice iterators through `Deref` rather than duplicating them.
