### ISSUE TITLE
 No module named importlib_metadata

### ISSUE THREAD

**Issue by bamilab** [servo/servo#27940]
Hey Guys,

I'm trying to build Servo on Windows. However, when running `mach.bat build --release`, I run into this error:
```
C:\Python27\python.exe" "-m" "virtualenv" "-p" "C:\Python27\python.exe" "--system-site-packages" "C:\Users\lksdj\Projects\servo\python\_virtualenv2.7" failed with error code 1:
Output:
Error:
C:\Python27\python.exe: No module named importlib_metadata; 'virtualenv' is a package and cannot be directly executed
```

I've tried installing `importlib_metadata` with `pip`. I seem to be able to import it with when I open python2 in the console. So I'm not sure what this error is about.

**Comment by jdm** [comment]
As far as I know, python2.7 has been completely removed from the build. Closing this issue based on that.
