### ISSUE TITLE
macOS nightlies won't launch

### ISSUE THREAD

**Issue by jdm** [servo/servo#27957]
I tried launching Servo from the terminal on Big Sur 11.0.1. When executed, it returns the following error message:
`arch: /usr/local/Cellar/gstreamer/1.18.1/libexec/gstreamer-1.0/gst-plugin-scanner isn't executable`
The latest version of gstreamer, according to brew, is 1.18.2. Therefore, I think that an outdated package is the issue.
Looks like we will have to wait until a new binary is compiled.

_Originally posted by @endearingyoungcharms in https://github.com/servo/servo/issues/27778#issuecomment-747809474_

**Comment by endearingyoungcharms** [comment]
It's 1.18.3 now

**Comment by jdm** [comment]
I suspect the situation would be improved with #27865, which installs the latest gstreamer package each time.

**Comment by mrobinson** [comment]
I think this isn't an issue an longer.
