### ISSUE TITLE
Issue building Servo from Source with MacOS 11.1

### ISSUE THREAD

**Issue by avr1** [servo/servo#27974]
When I build Servo, I get an error referencing my SDK: 
`error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/servo/mozjs?rev=a40b829f0fefa06a743f006260c7facebcfa27aa#a40b829f)`

Caused by:
  process didn't exit successfully: `/Users/arjun/Repositories/Open-Source/github.com/Rust/The-Servo-Project/servo/target/release/build/mozjs_sys-985b842831dd7e98/build-script-build` (exit code: 101)
  --- stdout
  cargo:outdir=/Users/arjun/Repositories/Open-Source/github.com/Rust/The-Servo-Project/servo/target/release/build/mozjs_sys-fab104e4c3e93d1c/out/build
  [[ '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure -ot '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure.in ]] && touch '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure || true
  [[ '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure -ot '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure.in ]] && touch '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure || true
  ! [[ '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure.in -ot '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure ]] && touch '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure || true
  ! [[ '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure.in -ot '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure ]] && touch '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/old-configure || true
  if [[ '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure -nt config.status ]] ; then \
  	  PYTHON="python2" MOZ_TOOLS="" \
  	  CC="clang" CFLAGS="" \
  	  CPP="gcc -E" CPPFLAGS="-I/Users/arjun/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_c_mem-0.2.6/include " \
  	  CXX="clang++" CXXFLAGS="-stdlib=libc++" \
  	  AS="" AR="ar" \
  	  STLPORT_LIBS="" \
  	  '/Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs'/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake || (cat config.log && exit 1) ; \
  	fi
  Creating Python environment
  Using real prefix '/System/Library/Frameworks/Python.framework/Versions/2.7'
  New python executable in /Users/arjun/Repositories/Open-Source/github.com/Rust/The-Servo-Project/servo/target/release/build/mozjs_sys-fab104e4c3e93d1c/out/build/_virtualenvs/init/bin/python2
  Also creating executable in /Users/arjun/Repositories/Open-Source/github.com/Rust/The-Servo-Project/servo/target/release/build/mozjs_sys-fab104e4c3e93d1c/out/build/_virtualenvs/init/bin/python
  Installing setuptools, pip, wheel...done.
  running build_ext
  copying build/lib.macosx-11.1-x86_64-2.7/psutil/_psutil_osx.so -> psutil
  copying build/lib.macosx-11.1-x86_64-2.7/psutil/_psutil_posix.so -> psutil

  Error processing command. Ignoring because optional. (optional:packages.txt:comm/build/virtualenv_packages.txt)
  Reexecuting in the virtualenv
  checking for vcs source checkout... no
  checking for a shell... /bin/sh
  checking for host system type... x86_64-apple-darwin20.2.0
  checking for target system type... x86_64-apple-darwin20.2.0
  checking whether cross compiling... no
  checking for Python 3... /usr/local/bin/python3 (3.8.3)
  checking for yasm... /usr/local/bin/yasm
  checking yasm version... 1.3.0
  INFO: checking for vcs source checkout...
  INFO: no
  INFO: checking for a shell...
  INFO: /bin/sh
  INFO: checking for host system type...
  DEBUG: Executing: `/bin/sh /Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/build/moz.configure/../autoconf/config.guess`
  INFO: x86_64-apple-darwin20.2.0
  INFO: checking for target system type...
  INFO: x86_64-apple-darwin20.2.0
  INFO: checking whether cross compiling...
  INFO: no
  INFO: checking for Python 3...
  INFO: /usr/local/bin/python3 (3.8.3)
  INFO: checking for yasm...
  DEBUG: yasm: Trying yasm
  INFO: /usr/local/bin/yasm
  INFO: checking yasm version...
  DEBUG: Executing: `/usr/local/bin/yasm --version`
  INFO: 1.3.0
  DEBUG: Executing: `xcrun --show-sdk-path`
  ERROR: SDK version "11.1" is unsupported. Please downgrade to version 10.15.6. You may need to point to it using --with-macos-sdk=<path> in your mozconfig. Various SDK versions are available from https://github.com/phracker/MacOSX-SDKs

  --- stderr
  ERROR: SDK version "11.1" is unsupported. Please downgrade to version 10.15.6. You may need to point to it using --with-macos-sdk=<path> in your mozconfig. Various SDK versions are available from https://github.com/phracker/MacOSX-SDKs
  make: *** [maybe-configure] Error 1
  thread 'main' panicked at 'assertion failed: result.success()', /Users/arjun/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/build.rs:177:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Is there a way around this that doesn't involve me downgrading to Catalina? Sorry for the newbie question.

**Comment by jdm** [comment]
@avr1 You can download an older SDK from https://github.com/phracker/MacOSX-SDKs and run the build with a MACOS_SDK_PATH environment variable set that is a path to the downloaded SDK. That will trigger [this code](https://github.com/servo/mozjs/blob/a40b829f0fefa06a743f006260c7facebcfa27aa/makefile.cargo#L15) to pass the appropriate flag.

**Comment by avr1** [comment]
Thanks! Just curious, how does the process go for supporting the newer SDK's, like 11.1?

**Comment by jdm** [comment]
Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1682608, it looks like we should be safe to update [this code](https://github.com/servo/mozjs/blob/a40b829f0fefa06a743f006260c7facebcfa27aa/mozjs/build/moz.configure/toolchain.configure#L144) and then update the revision of mozjs_sys in [rust-mozjs](https://github.com/servo/rust-mozjs/blob/e9f71b6458135c1e63fee9261dabcd8c3efa6ccf/Cargo.toml#L61) and then update the version of rust-mozjs that Servo depends upon.

**Comment by avr1** [comment]
Cool, I'll try to get the ball rolling on these if that's okay.
