### ISSUE TITLE
Move away from surfman?

### ISSUE THREAD

**Issue by avr1** [servo/servo#27975]
Looking at the surfman code currently, it appears as though it hasn't been updated in a while. The code doesn't seem to be updated to the latest crates, there doesn't seem to be a lot of PR's being merged, and the code currently doesn't compile.

Are we planning on beefing up the surfman code, or should we consider moving away from the codebase?

**Comment by jdm** [comment]
In what way does the surfman code not compile? I do not anticipate moving away from it.

**Comment by avr1** [comment]
I just forked and cloned today, with the current code, and it didn't compile for me. Is it just on my end, or is it actually not compiling on the source?

**Comment by jdm** [comment]
It's definitely compiling on CI, and as part of Servo.

**Comment by avr1** [comment]
My bad then. I'll figure out what's wrong with my other version.
