### ISSUE TITLE
VCRUNTIME140_1.dll missing

### ISSUE THREAD

**Issue by yashpalgoyal1304** [servo/servo#27983]
### Summary:

On running Servo Tech Demo, the following error is shown:

```
The code execution cannot proceed because VCRUNTIME140_1.dll 
was not found. Reinstalling the program may fix this problem.
```

![vivaldi_0kaQkKIZUX](https://user-images.githubusercontent.com/19423063/103092816-83da0a00-461e-11eb-9b38-c62cb8d1443b.png)

### Reproduction:

**Frequency:** 
Always

**Steps:** 
1. Open Servo Tech Demo

### Environment:

Servo Version: 1.0.0.0 (via control panel) - 2020-12-15\
Package from: Tried with both zip and exe from www.servo.org
MSVC++ : 2015-2019 Redistributable (x86) : 14.22.27821.0
OS: Win 10 1903

### Additional Comments:

- Along with what is missing, the name of component which will have that missing thing and a link if possible shall be shown too.\
  For example, for this file, i [searched the web🡭] and seems like t'll require updating [Microsoft Visual C++] RunTime libraries (MSVC-RT, sometimes: ...C++ or ...CP). So, it would have been nice if _something like following_ was also shown in the dialog:\
"This component is a part of XYZ - which can be found at www.example.com"
- It feels like it is similar to #16422 but not duplicate since that issue was about `VCRUNTIME140.dll` - this one is about `VCRUNTIME140_1.dll`
- I tried a hack 😛 - copy pasted the existing `vcruntime140.dll` file, and renamed it to required file name. Then it showed this error:

```
The procedure entry point _CxxFrameHandler4 could not be located 
in the dynamic link library C:\Program Files\Mozilla Research\Servo 
Tech Demo\MSVCP140.dll.
```

[searched the web🡭]: https://www.ecosia.org/search?tt=0e30b125&q=vcruntime140_1.dll%20is%20missing
[Microsoft Visual C++]: https://support.microsoft.com/en-us/help/2977003/
[IR2rbjaL4m]: https://user-images.githubusercontent.com/19423063/103092740-41b0c880-461e-11eb-849c-ffe0c6feb4b3.png 

![IR2rbjaL4m]

----
Issue template inspired from: [gimp🡭](https://gitlab.gnome.org/GNOME/gimp/-/issues/new) & [inkscape🡭](https://gitlab.com/inkscape/inbox/-/issues/new)\
This issue move here from https://github.com/servo/servo/discussions/27442#discussioncomment-212072

**Comment by yashpalgoyal1304** [comment]
I installed VC_redist.x64 - latest version: 14.28.29325.2 and now, servo is working.

**Comment by philip-lamb** [comment]
Two options; either bundle the VC runtime DLL with the build (easiest) or perform a VC redist installation as part of a Servo installer.

**Comment by yashpalgoyal1304** [comment]
this app just mentions that what to do if the popup is shown: http://animeeffects.org/en/?page_id=6 - which, like i already proposed in description, seems to be a good and easy temporary fix.
[image](https://user-images.githubusercontent.com/19423063/108627043-89669b80-7479-11eb-8e9b-b07bc86e0f2b.png)

**Comment by T2Player** [comment]
Here must be noticed that this file is not exist in Visual C++ runtimes at least till 2015 bundle (inclusive). So, you must download Microsoft Visual C++ 2015-2019 Redistributable (x64), but nor 2015 or prior versions.

**Comment by yashpalgoyal1304** [comment]
this app: [Nitroshare desktop](https://github.com/nitroshare/nitroshare-desktop) has these folders in its install location preinstalled i guess. is this info of any help?

![image](https://user-images.githubusercontent.com/19423063/117197080-019bf680-ae05-11eb-82e7-9e3ff8650e68.png)
