### ISSUE TITLE
Issue compiling Servo on macOS 11.1

### ISSUE THREAD

**Issue by avr1** [servo/servo#27981]
I'm trying to compile, but I get a string of errors about having duplicate winit crates:
 Compiling servo v0.0.1 (/Users/arjun/Repositories/Open-Source/github.com/Rust/The-Servo-Project/servo/ports/winit)
error[E0308]: mismatched types
   --> ports/winit/headed_window.rs:152:56
    |
152 |         let connection = Connection::from_winit_window(&winit_window).expect("Failed to create connection");
    |                                                        ^^^^^^^^^^^^^ expected struct `winit::Window`, found a different struct `winit::Window`
    |
    = note: expected reference `&winit::Window` (struct `winit::Window`)
               found reference `&winit::Window` (struct `winit::Window`)
    = note: perhaps two different versions of crate `winit` are being used?

error[E0308]: mismatched types
   --> ports/winit/headed_window.rs:155:53
    |
155 |             .create_native_widget_from_winit_window(&winit_window)
    |                                                     ^^^^^^^^^^^^^ expected struct `winit::Window`, found a different struct `winit::Window`
    |
    = note: expected reference `&winit::Window` (struct `winit::Window`)
               found reference `&winit::Window` (struct `winit::Window`)
    = note: perhaps two different versions of crate `winit` are being used?

error[E0308]: mismatched types
   --> ports/winit/headed_window.rs:676:53
    |
676 |             .create_native_widget_from_winit_window(&self.winit_window)
    |                                                     ^^^^^^^^^^^^^^^^^^ expected struct `winit::Window`, found a different struct `winit::Window`
    |
    = note: expected reference `&winit::Window` (struct `winit::Window`)
               found reference `&winit::Window` (struct `winit::Window`)
    = note: perhaps two different versions of crate `winit` are being used?

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `servo`.

I don't believe it's my OS, any chance this is an issue on my machine only?

**Comment by jdm** [comment]
That looks like you have either updated winit in servo or have somehow updated winit in surfman.
