### ISSUE TITLE
simpleservo c-headers

### ISSUE THREAD

**Issue by simonschmeisser** [servo/servo#27995]
previously discussed in #27773 I'm trying to build the simpleservo lib and use it from c/c++

the suggested commands by @jdm doesn't work unfortunately

```
servo$ ./mach build --release --simpleservo
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.47.0-nightly (6c8927b0c 2020-07-26)`
error: Found argument '--simpleservo' which wasn't expected, or isn't valid in this context

USAGE:
    cargo build --features <FEATURES>... --manifest-path <PATH> -Z <FLAG>...

For more information try --help
Build FAILED in 0:00:00

```
I tried running the following before
```
servo$ ./mach build --release -p simpleservo
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.47.0-nightly (6c8927b0c 2020-07-26)`
    Finished release [optimized] target(s) in 3.31s
Build Completed in 0:00:03
```
but it only gives me a `libsimpleservo.rlib` in `targets/release/` but not the promised header files :(

I'll open a PR to document this once figured out

**Comment by jdm** [comment]
If you build with `./mach build --release --simpleservo`, then I would expect to find `simpleservo.h` in `target/release/` based on https://github.com/servo/servo/blob/master/ports/libsimpleservo/capi/build.rs.

**Comment by simonschmeisser** [comment]
sorry, i screwed up formatting in my initial post. That command just errors out.

using `./mach build --release -p simpleservo` I get the following output
```
servo$ ls target/release/
build  deps  examples  incremental  libscript_plugins.so  libsimpleservo.d  libsimpleservo.rlib  servo  servo.d
```

**Comment by jdm** [comment]
Sorry, I meant `--libsimpleservo`. `-p simpleservo` means something different, so it doesn't surprise me that there's no header generated for that.

**Comment by simonschmeisser** [comment]
thanks, that works :-)
