### ISSUE TITLE
Issue building servo from source, believe it's an issue with my version of winit. 

### ISSUE THREAD

**Issue by avr1** [servo/servo#28000]
When I build the project using the latest source code, I get the following errors:
error[E0308]: mismatched types
   --> ports/winit/headed_window.rs:152:56
    |
152 |         let connection = Connection::from_winit_window(&winit_window).expect("Failed to create connection");
    |                                                        ^^^^^^^^^^^^^ expected struct `winit::Window`, found a different struct `winit::Window`
    |
    = note: expected reference `&winit::Window` (struct `winit::Window`)
               found reference `&winit::Window` (struct `winit::Window`)
    = note: perhaps two different versions of crate `winit` are being used?

error[E0308]: mismatched types
   --> ports/winit/headed_window.rs:155:53
    |
155 |             .create_native_widget_from_winit_window(&winit_window)
    |                                                     ^^^^^^^^^^^^^ expected struct `winit::Window`, found a different struct `winit::Window`
    |
    = note: expected reference `&winit::Window` (struct `winit::Window`)
               found reference `&winit::Window` (struct `winit::Window`)
    = note: perhaps two different versions of crate `winit` are being used?

error[E0308]: mismatched types
   --> ports/winit/headed_window.rs:676:53
    |
676 |             .create_native_widget_from_winit_window(&self.winit_window)
    |                                                     ^^^^^^^^^^^^^^^^^^ expected struct `winit::Window`, found a different struct `winit::Window`
    |
    = note: expected reference `&winit::Window` (struct `winit::Window`)
               found reference `&winit::Window` (struct `winit::Window`)
    = note: perhaps two different versions of crate `winit` are being used?

I'm building on macOS 11.1 using mach, and when I run the git diff command, I have differences in my Cargo.lock.

Is there a good way to manage this? It seems like an issue with my cargo packages.

**Comment by jdm** [comment]
You should revert the changes to Cargo.lock.
