### ISSUE TITLE
New servo-tidy release on PyPI

### ISSUE THREAD

**Issue by mstange** [servo/servo#28034]
The last time a new servo-tidy was published was in February 2017, in #15731. Since then, many changes have gone into it.

In Firefox, we're running a servo-tidy job to check the gfx/wr directory, [using servo-tidy 0.3.0](https://searchfox.org/mozilla-central/source/gfx/wr/ci-scripts/docker-image/setup.sh#44). However, that version is now incompatible with rustfmt formatting: When an expression with a binary operator is broken into multiple lines, rustfmt puts the operator at the beginning of the second line, whereas the published version of servo-tidy want the operator at the end of the first line. This was fixed in https://github.com/servo/servo/commit/96b8f392772b360e9abd41818d33c5e0d8a94e9e#diff-891fe4b0e3de954ef611edea76ce3c2093babd456bc5b8ad7212d7c0ec4dbde0R338 . If I understand correctly, I think we need that fix to make it into a published version of servo-tidy.

Could we publish a new version of servo-tidy? cc @staktrace @saschanaz
I can write the patch to update the version number, but I'm not sure who can publish to PyPI.

**Comment by mstange** [comment]
Emilio pointed out that Servo code actually has the operator at the end of the line, using `binop_separator = "Back"`: https://github.com/servo/servo/blob/8d0e68720775addf089324a5fdfcd299dc5de097/rustfmt.toml#L2

**Comment by mstange** [comment]
Another error in the old published version of servo-tidy is "use statement spans multiple lines". This warning no longer exists in the current servo-tidy code, and it is also incompatible with rustfmt.

**Comment by jdm** [comment]
I wonder who has credentials to publish the package? 🤔

**Comment by saschanaz** [comment]
I guess the last person was @edunham per https://github.com/servo/servo/issues/10636#issuecomment-243280297 and https://github.com/servo/servo/pull/15731#issuecomment-282488033.

**Comment by jdm** [comment]
We do not expect to publish any more versions of servo-tidy at this point.
