### ISSUE TITLE
Fetching rust snapshot fails on OS X

### ISSUE THREAD

**Issue by dirkschulze** [servo/servo#2805]
Get the following error on running ../configure:

    configure: Fetching snapshot from https://servo-rust.s3.amazonaws.com/9f8d2205f0518389993a9b5de6646ba8b14e5a12/rust-0.11.0-pre-x86_64-apple-darwin.tar.gz
    configure: 
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100   354    0   354    0     0    262      0 --:--:--  0:00:01 --:--:--   262
    tar: Unrecognized archive format
    tar: Error exit delayed from previous errors.
    configure: error: No rustc found at /Users/dschulze/Downloads/servo/build/x86_64-apple-darwin//rust_snapshot/rust-0.11.0-pre-x86_64-apple-darwin/bin/rustc

**Comment by frewsxcv** [comment]
This can probably be closed due to inactivity
