### ISSUE TITLE
Demonstrate competitive performance of DOM methods when not consulting layout

### ISSUE THREAD

**Issue by brson** [servo/servo#281]
Per @bzbarsky: `A basic binding for Node that allows JS to do .firstChild without a virtual function call on arbitrary nodes would be a lot more like what I'm looking for here.'

Performance of calls to DOM methods is critical and we need to validate that we can do it competitively. First, let's prove that it can be fast when we don't need to consult layout.

Blocked on #278, #279, #280

**Comment by nox** [comment]
Dromaeo results seem good enough now.
