### ISSUE TITLE
Migrate away from the `truetype` crate

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#28101]
In PR https://github.com/servo/servo/pull/27619 which updates rustc, [a test failure](https://community-tc.services.mozilla.com/tasks/DRvKYBVxTuarPa8glF1taQ/runs/0/logs/public/logs/live.log#L2293) shows that the `truetype` has [code that calls `std::mem::zeroed`](https://github.com/bodoni/truetype/blob/6da06be224c7ddb96a31db1e8c915ca87f3fc420/src/macros.rs#L64) for at least [one struct that contains a `Vec`](https://github.com/bodoni/truetype/blob/6da06be224c7ddb96a31db1e8c915ca87f3fc420/src/naming_table.rs#L25).

This is Undefined Behavior, and [newer Rust versions prevent it by panicking at runtime](https://github.com/rust-lang/rust/pull/66059).

Unfortunately this problem is still present in the latest git commit for that crate, which is from 2017. Fixing it is likely possible but not trivial. Since we only use this crate in `components/gfx/platform/windows/font.rs` it might be easier to migrate to another crate that doesn’t have this problem. There exist several that can parse Truetype files. `stb_truetype` is already in our `Cargo.lock` (though I don’t know if we actually build it in typical configs, it might be behind a feature flag of an intermediate dependency). `ttf-parser` is under active maintenance.

**Comment by SimonSapin** [comment]
Minimized: does `fn main() { unsafe { std::mem::zeroed::<Vec<()>>(); } }` panic at runtime. The earliest I can reproduce is in nightly-2020-09-27, likely with https://github.com/rust-lang/rust/pull/71274.

**Comment by jdm** [comment]
The truetype crate has been fixed! https://github.com/bodoni/truetype/commit/018dcc840f248007a505d275a29ecb9f062c4d06

**Comment by SimonSapin** [comment]
Oh nice! I guess I should have filed an issue despite the years of inactivity
