### ISSUE TITLE
default gstreamer for Ubuntu 18.04

### ISSUE THREAD

**Issue by helvete003** [servo/servo#28117]
Hi everyone i 'am not sure if this is an issue or if i just made a mistake. 

I had problems compiling servo because of this linker error: 

```
  = note: /home/helvete/.cargo/registry/src/github.com-1ecc6299db9ec823/gstreamer-webrtc-0.15.5/src/auto/enums.rs:274: error: undefined reference to 'gst_webrtc_data_channel_state_get_type'
          collect2: error: ld returned 1 exit status
```
(There is a lot more stuff before that error. )

The linker had `"-L" "/usr/lib/x86_64-linux-gnu"` as a parameter so i thought that should check `libgstwebrtc-1.0.so` for the label 

`strings libgstwebrtc-1.0.so | grep -i "gst_webrtc_data*"` => empty result

So at this point i was confused and tried to figure out why my webrtc didn't had the function. A few hours later i realized that i haven't checked the version of my gstreamer libs 

```
$ apt-cache policy libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev

libgstreamer1.0-dev:
  Installiert:           (keine)
  Installationskandidat: 1.14.5-0ubuntu1~18.04.1
  Versionstabelle:
     1.14.5-0ubuntu1~18.04.1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.14.1-1~ubuntu18.04.2 500
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     1.14.0-1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
libgstreamer-plugins-base1.0-dev:
  Installiert:           (keine)
  Installationskandidat: 1.14.5-0ubuntu1~18.04.1
  Versionstabelle:
     1.14.5-0ubuntu1~18.04.1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
     1.14.1-1ubuntu1~ubuntu18.04.2 500
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     1.14.0-2ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
libgstreamer-plugins-bad1.0-dev:
  Installiert:           (keine)
  Installationskandidat: 1.14.5-0ubuntu1~18.04.1
  Versionstabelle:
     1.14.5-0ubuntu1~18.04.1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
     1.14.0-1ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

```

Well the default is 1.14 so i just removed the gstreamer libs (becaus of the libs in /support/linux/gstreamer/) `$ sudo apt remove libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev    libgstreamer-plugins-bad1.0-dev`, rerun the build and after that it was able to successfully build Servo.

I haven't tried a clean build at this point because i was happy that it was able to build.

Now the question is, have i done a mistake or should we remove the `'libgstreamer1.0-dev', 'libgstreamer-plugins-base1.0-dev','libgstreamer-plugins-bad1.0-dev'` from the mach bootstrap for Ubuntu 18.04?

**Comment by jdm** [comment]
[This code](https://github.com/servo/servo/blob/cabd254509a4be594cd809ea71c7928fdb040da3/python/servo/bootstrap.py#L24-L26) is already supposed to tell you if the installed version of gstreamer is too old. It's confusing that it didn't work.

**Comment by helvete003** [comment]
> [This code](https://github.com/servo/servo/blob/cabd254509a4be594cd809ea71c7928fdb040da3/python/servo/bootstrap.py#L24-L26) is already supposed to tell you if the installed version of gstreamer is too old. It's confusing that it didn't work.

Oh i haven't seen that in the bootstrap file... 

I tried the bootstrap again and it just installs the packages

```
./mach bootstrap

Die folgenden NEUEN Pakete werden installiert:
  libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer1.0-dev
0 aktualisiert, 4 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 832 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 10,6 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] 
Holen:1 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgstreamer1.0-dev amd64 1.14.5-0ubuntu1~18.04.1 [398 kB]
Holen:2 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgstreamer-plugins-base1.0-dev amd64 1.14.5-0ubuntu1~18.04.1 [312 kB]
Holen:3 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgstreamer-plugins-good1.0-dev amd64 1.14.5-0ubuntu1~18.04.1 [17,2 kB]
Holen:4 http://de.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libgstreamer-plugins-bad1.0-dev amd64 1.14.5-0ubuntu1~18.04.1 [105 kB]
Es wurden 832 kB in 0 s geholt (3.197 kB/s).             

```

That's really odd i try to debug this

**Comment by helvete003** [comment]
If i read that correctly the calls are, well not wrong but to late? 

It installs the dependencies in `install_linux_deps(context, pkgs_apt, pkgs_dnf,pkgs_xbps, force)` and after that it checks the version of gstreamer and calls the `gstreamer.sh` 

So it doesn't prevent or tell me that i have a wrong version of gstreamer installed in `/usr/lib/x86_64-linux-gnu/`


(Sorry i wasn't sure if i should have edited my last comment)

**Comment by jdm** [comment]
I believe that the check happens as part of building, not bootstrapping.

**Comment by helvete003** [comment]
> I believe that the check happens as part of building, not bootstrapping.

Thats true it does check for gstreamer [here](https://github.com/servo/servo/blob/cabd254509a4be594cd809ea71c7928fdb040da3/python/servo/command_base.py#L533)  but if i have the old version of gstreamer on my machine thats when it adds the local gstreamer path to LD_LIBRARY_PATH [here](https://github.com/servo/servo/blob/cabd254509a4be594cd809ea71c7928fdb040da3/python/servo/command_base.py#L649-L657)

But either cargo it self or a crate through rustc-link-search adds the /usr/lib/x86_64-linux-gnu path to the linker.

I just tried to compile servo on my laptop that also has Ubuntu 18.04 installed and it failed with the same "gst_webrtc_data_channel_state_get_type" error. Removing the global gstreamer libs worked again. 

Is there a way to force the local gstreamer path to be in front of in the others?

**Comment by mrobinson** [comment]
I think this should be working better after many changes to how we look for gstreamer, the version required, and newer Linux distributions. Feel free to reopen if this is still failing though.
