### ISSUE TITLE
Linux docker image build task fails

### ISSUE THREAD

**Issue by jdm** [servo/servo#28122]
https://community-tc.services.mozilla.com/tasks/KRcyWAz9T5aox8X64Hf7Ww/runs/0/logs/public/logs/live.log

```
Traceback (most recent call last):
  File "get-pip.py", line 24244, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpFEWgj6/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by jdm** [comment]
This is triggered by https://github.com/servo/servo/blob/a955ff280d252468e22082beabcc9ca35577f3d9/etc/taskcluster/docker/base.dockerfile#L41-L42. Presumably get-pip.py updated recently in a backwards-incompatible way?

**Comment by jdm** [comment]
@SimonSapin Any ideas about how we can avoid this?

**Comment by SimonSapin** [comment]
https://github.com/pypa/pip/issues/9520 recommends to use https://bootstrap.pypa.io/2.7/get-pip.py instead (though ideally we’d finish porting everything to Python 3 and not install 2.7 anymore)

**Comment by jdm** [comment]
Thanks!
