### ISSUE TITLE
Frameless Windows, remove titlebar, or recolor titlebar?

### ISSUE THREAD

**Issue by UHDBits** [servo/servo#28132]
Hello! I'm wondering if it's possible to make a frameless window with Servo, remove the titlebar, or recolor the titlebar, something like in Electron, for a good example of an app that does it, the Discord electron app.
Thanks!

**Comment by jdm** [comment]
Servo only controls the content inside of whatever region it renders into. It's up to the embedder (such as [winit](https://github.com/rust-windowing/winit/)) to set up the window management.
