### ISSUE TITLE
Servo Linux (x64)

### ISSUE THREAD

**Issue by hngts** [servo/servo#28133]
When I unpack `servo-latest.tar.gz` from servo.org .. to `/opt` .. then I symlink `ln -s /opt/servo/servo /usr/bin/servo`  ... I get the following message on screen if I try to start it:

> servo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by servo)

> servo: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by servo)

Here is the machine info (Debian Buster (stable)): 
> Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

And I have glibc_2.28 installed ...
Is there any painless way to overcome this ? 

Panless = I update to wanted libs, servo test-build works and my system remains in beautiful current condition.

**Comment by jdm** [comment]
I suspect the only ways to avoid this is for our nightlies to be statically linked or you to update glibc.

**Comment by hngts** [comment]
Yup, thanks. Previous year, I think ... I have built dev. variant of servo ... ran with `./mach .. ` and that did worked, but it was slow and buggy. I suppose that Debian unstable and sid already have needed libraries. Nevermind, I will simply wait for the first stable official version to come out, as I can't help either way. I am web-dev and rust noob, haven't made anything useful in rust yet, can't actually speed up the process.
