### ISSUE TITLE
Unable to build the binary on linux fedora33

### ISSUE THREAD

**Issue by shantanu28sharma** [servo/servo#28131]
running 
python3 ./mach build -d

gives error 
`info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.47.0-nightly (6c8927b0c 2020-07-26)`
error: -Zbuild-std requires --target
Build FAILED in 0:00:00`

so when I give --target flag x86_64-unknown-linux-gnu
It gives the following error
`info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.47.0-nightly (6c8927b0c 2020-07-26)`
   Compiling lazy_static v1.4.0
   Compiling byteorder v1.4.2
   Compiling futures v0.1.30
   Compiling hashbrown v0.9.1
   Compiling new_debug_unreachable v1.0.4
   Compiling byte-tools v0.3.1
   Compiling precomputed-hash v0.1.1
   Compiling opaque-debug v0.2.1
error: cannot find a built-in macro with name `cfg`
    --> /home/shantanu/.rustup/toolchains/nightly-2020-07-27-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:1183:5
     |
1183 | /     macro_rules! cfg {
1184 | |         ($($cfg:tt)*) => {
1185 | |             /* compiler built-in */
1186 | |         };
1187 | |     }
     | |_____^

error: duplicate lang item in crate `core` (which `std` depends on): `bool`.
  |
  = note: the lang item is first defined in crate `core` (which `lazy_static` depends on)
  = note: first definition in `core` loaded from /home/shantanu/Documents/Programming/rs/servo/target/x86_64-unknown-linux-gnu/debug/deps/libcore-4ee3d31f48259c59.rmeta
  = note: second definition in `core` loaded from /home/shantanu/.rustup/toolchains/nightly-2020-07-27-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-cd104942fda86acc.rlib

error: duplicate lang item in crate `core` (which `std` depends on): `char`.
  |
  = note: the lang item is first defined in crate `core` (which `lazy_static` depends on)
  = note: first definition in `core` loaded from /home/shantanu/Documents/Programming/rs/servo/target/x86_64-unknown-linux-gnu/debug/deps/libcore-4ee3d31f48259c59.rmeta
  = note: second definition in `core` loaded from /home/shantanu/.rustup/toolchains/nightly-2020-07-27-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-cd104942fda86acc.rlib

error: duplicate lang item in crate `core` (which `std` depends on): `str`.`

and similar errors saying duplicate lang item in crate 'core'

**Comment by jdm** [comment]
I'm confused - do you get an error about build-std in the default build command? Do you have the RUSTFLAGS variable set or something? Our build doesn'tuuse build-std as far as I'm aware.

**Comment by shantanu28sharma** [comment]
Yes I used the default command python3 ./mach build -d.

**Comment by shantanu28sharma** [comment]
I had overwritten ~/.cargo/config.toml to have 
build-std = ["core", "compiler_builtins"] earlier
this line due to which core library was getting compiled twice hence giving the error and those flags. Fixed it now.
thanks for your time.
