### ISSUE TITLE
Servo build times

### ISSUE THREAD

**Issue by pecastro** [servo/servo#28157]
Hi all,

I wanted to ask a fundamental question.
Why is it taking me the same amount of time to build servo between two consecutive builds against the same git HEAD in the same host when none of the source files have changed?
Could this be a servo related thing that by _touching_ specific files a recompilation is triggered or is it more of a cargo behaviour ?

Regards,

PECastro

**Comment by jdm** [comment]
At least one person recently discovered that their IDE was touching all of the source files and causing significant unnecessary recompilation to occur.

**Comment by pecastro** [comment]
I'm closing this.
I've realized what my shortcoming was.
The docker container I was using to perform the build wasn't mounting the home directory where the cargo packages were being checkout. :facepalm: 
All good now.
