### ISSUE TITLE
Assertion failure with exception thrown from event handler

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#2818]
```
<script>
document.addEventListener("x", function() { throw 7; })
document.dispatchEvent(new Event("x"));
</script>
```

causes `Assertion failure: !cx->isExceptionPending()` in `CallJSNative`, because it assumes that `cx->isExceptionPending()` will be false if it was before the native was called, and it returned success. We should clear the exception.

**Comment by nox** [comment]
No panic, and:
```
ERROR:js::rust: Error at none:0: uncaught exception: 7
```

**Comment by jdm** [comment]
@nox did you use a build with debug-mozjs enabled?

**Comment by nox** [comment]
Oh. No.

**Comment by Ms2ger** [comment]
Seems fixed.
