### ISSUE TITLE
Implement [Exposed]

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#2823]
Planning to put this off until <https://bugzilla.mozilla.org/show_bug.cgi?id=1017988> happens.

**Comment by jdm** [comment]
That bug happened. Try not to be intimidated by the stack of 10 patches there.

**Comment by nox** [comment]
Let me try that.

**Comment by KiChjang** [comment]
@nox sup?

**Comment by nox** [comment]
@KiChjang This needs #8954.

**Comment by nox** [comment]
And maybe even an SMUP because the code changed a lot.
