### ISSUE TITLE
unsupport macos sdk 11.3

### ISSUE THREAD

**Issue by zebozhuang** [servo/servo#28244]
I try to build it on my Macos with the following error, it seems it does not support macos sdk 11.3, but I can not downgrade to 11.0.
  
DEBUG: yasm: Trying yasm
  INFO: /usr/local/bin/yasm
  INFO: checking yasm version...
  DEBUG: Executing: `/usr/local/bin/yasm --version`
  INFO: 1.3.0
  DEBUG: Executing: `xcrun --show-sdk-path`
  ERROR: SDK version "11.3" is unsupported. Please downgrade to version 11.0. You may need to point to it using --with-macos-sdk=<path> in your mozconfig.

  --- stderr
  ERROR: SDK version "11.3" is unsupported. Please downgrade to version 11.0. You may need to point to it using --with-macos-sdk=<path> in your mozconfig.
  make: *** [maybe-configure] Error 1

**Comment by jdm** [comment]
You can work around this by cloning https://github.com/servo/mozjs/ and modifying https://github.com/servo/mozjs/blob/d0f33e89cf3881a8032dba6a109b4e42f1f1b690/mozjs/build/moz.configure/toolchain.configure#L155 to read 11.3, then [patching](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#overriding-repository-url) mozjs_sys to use the local clone.

**Comment by adamgering** [comment]
There's another work-around described here:
https://firefox-source-docs.mozilla.org/setup/macos_build.html#macos-sdk-is-unsupported

My question is, where should the mozconfig file be placed to specify the SDK path?

**Comment by jdm** [comment]
The supported workaround for servo is setting the MACOS_SDK_PATH environment variable to point to a supported SDK: https://github.com/servo/mozjs/blob/ef986b1a2c23081fe4d37aeaab5323d3dec033f3/makefile.cargo#L14 . A supported one can be acquired from https://github.com/phracker/MacOSX-SDKs.

**Comment by PhotonQuantum** [comment]
I also encountered this issue when building servo today, and was guided to https://firefox-source-docs.mozilla.org/setup/macos_build.html#macos-sdk-is-unsupported incorrectly.

Is there any plan to update the build error message to avoid misunderstanding?

**Comment by jdm** [comment]
I've filed https://github.com/servo/mozjs/issues/289 about that idea.
