### ISSUE TITLE
components/gfx: possible atomicity violation in font.rs

### ISSUE THREAD

**Issue by BurtonQin** [servo/servo#28245]
https://github.com/servo/servo/blob/4a46a476d7c22fe22214a8c368d9d54f8a7a55d2/components/gfx/font.rs#L524-L528
For `TEXT_SHAPING_PERFORMANCE_COUNTER` ,
I wonder if the result is expected when `load()` and `store()` are interleaved by another `store()` from another thread. e.g.

|T1|T2|
|---|---|
|A=C.load()||
||A=C.load()|
||C.store(0)|
|C.store(0)|
|return A|return A|

Now we have two threads returning A instead of one returning A & the other returning 0.

**Comment by jdm** [comment]
You're right, this should really be using swap instead of load/store.

**Comment by delosrogers** [comment]
Hi, I’m totally new to Servo but I’d like to try working on this.

@highfive: assign me

**Comment by delosrogers** [comment]
I was trying to run the tests for the components/gfx using `./mach test-unit components/gfx/` but it reported that no tests were run because they were all filtered out. Overall I'm a little confused on how to correctly run the tests. What is the correct way to test the changes I make to font.rs?

**Comment by jdm** [comment]
That code is only called from https://github.com/servo/servo/blob/b196bfeeeb90e87769700b52202e898da999f8da/components/layout_thread/lib.rs#L1447, so you can validate that it's still working by running `./mach run https://joshmatthews.net --profile 5` and validate that LayoutTextShaping category has the same values from a build without your change.
