### ISSUE TITLE
Run WPT tests (linux)

### ISSUE THREAD

**Issue by jdm** [servo/servo#28280]

**Comment by pecastro** [comment]
Been playing around with this one ...

There are errors almost everywhere but a mix of everything ... FAIL that should PASS, PASS that should FAIL and ERROR when they expect to TIMEOUT and OK when they should have ERROR ...
It's a mix of good and bad ?!

https://github.com/pecastro/servo/runs/2226489365?check_suite_focus=true

**Comment by pecastro** [comment]
I think I'm down the known intermittent/failures with this https://github.com/pecastro/servo/actions/runs/715275798
Is there a way of flagging intermittent tests as there doesn't seem to be a way of running the individual tasks that failed ?

**Comment by jdm** [comment]
We mark intermittent test results as ignored by filing an issue like https://github.com/servo/servo/issues/28312 that has the test path in the title and the I-intermittent label applied.

**Comment by jdm** [comment]
To make it easier, so we can just update the test expectations to match the CI requirements, let's:
* make homu gate merging on github actions succeeding
* disable the taskcluster linux WPT tests at the same time as we enable linux WPT github actions ([comment out these lines](https://github.com/servo/servo/blob/master/etc/taskcluster/decision_task.py#L40-L41))

**Comment by pecastro** [comment]
I've tidied it up and pushed a PR https://github.com/servo/servo/pull/28328 with a `linux-wpt-tests` branch target so it could run the test.
It will most likely fail on account of the intermittent tests. 
What I meant with the question regarding flagging the intermittent was, if the test suite had a way of flagging a specific test with the intermittent result and therefore be lenient whether it passed or failed in a similar fashion to declaring them as TIMEOUT or FAIL.
Otherwise, given how less flexible the Github action pipeline seems to be in comparison with TC, how will one ascertain a given PR?

**Comment by jdm** [comment]
Our testsuite only has the notion of whether a particular test file can have intermittent results - if there's an issue filed with the test path in the title and the I-intermittent label applied, the test's results will be filtered out when checking if there were unexpected test results.

**Comment by pecastro** [comment]
That's what the `filter-intermittents` does. Duhhh
And that's why there's an error because filter-intermittents is actually running and producing the verbose output.  :facepalm:  
Right, I'll check the latest failures ...

**Comment by pecastro** [comment]
Can we tag these with `I-intermittent` ? 

#28337 
#28336 
#28335 
#28334 
#28333

**Comment by pecastro** [comment]
I've got a few more ... 

#28341
#28342 
#28343

**Comment by pecastro** [comment]
@CYBAI Another set please  ...

#28346
#28345 

Distinct runs seem to be triggering distinct failures?! :confused: 
Would these be something that could be "corrected" by raising the `--timeout-multipler`  option ?

**Comment by pecastro** [comment]
I think there's something racy going on with Servo as per https://github.com/servo/servo/issues/28301#issuecomment-806249064 which apparently the Github runners seem to be triggering more often ?

**Comment by pecastro** [comment]
Another intermittent ...
https://github.com/servo/servo/issues/28351

**Comment by pecastro** [comment]
@jdm What else is missing to get https://github.com/servo/servo/pull/28328 over the line ?
