### ISSUE TITLE
Optimize layout requests

### ISSUE THREAD

**Issue by brson** [servo/servo#283]
The communication between JS and layout needs to be fast. Currently it is likely pretty slow, but we haven't measured. There are a number of potential approaches here:
- The synchronization in the multithreaded case can be reduced
- In cases where JS can see that layout is blocked waiting for a request, we can schedule layout to run on the JS thread.
- In cases where ... etc., we can context switch directly from JS to layout
- Finally, we can avoid the context switch entirely, just borrow layout's state and local heap and run the layout operation in the JS task

Some of these optimizations could have negative implications for parallelism though, so the exact conditions under which we do them would need to be considered carefully.

Blocked on #https://github.com/mozilla/rust/issues/4419

**Comment by nox** [comment]
This issue is too vague and too old to be actionable, closing.
