### ISSUE TITLE
Publish new selectors version

### ISSUE THREAD

**Issue by morr0ne** [servo/servo#28368]
The current selectors version released on crates.io still depends on cssparser 0.27, this makes it very hard if not impossible to for projects to upgrade to cssparser 0.28. Since cssparser 0.28 is already 4 months old I think would it make sense to also publish a new selectors version that uses cssparser 0.28. It looks like it just needs a version bump before being published.

**Comment by atouchet** [comment]
I believe @emilio took care of the last release but I'm not really sure what the status of this is these days.

**Comment by atouchet** [comment]
@Eijebong bumped the version in #28380. It looks like this is just waiting on @emilio to publish it.

**Comment by Eijebong** [comment]
There, published 0.23. As @emilio said, just had to remove all of the shmem stuff from it and it went great
