### ISSUE TITLE
Windows/mach complains when python2 is missing, complains when it is present

### ISSUE THREAD

**Issue by dominiccooney** [servo/servo#28379]
I'm trying to follow [these getting started instructions](https://github.com/servo/servo/blob/master/README.md#on-windows-msvc) on Windows 10.

I got to the `./mach build --dev` step, and mach complains:

```
C:\Users\coons\servo> ./mach build --dev
Installed Pythons found by py Launcher for Windows
 -3.8-64
Requested Python version (2) not installed, use -0 for available pythons
Installed Pythons found by py Launcher for Windows
 -3.9-64 *
 -3.8-64
 -3.7-64

Requested Python version (2) not installed, use -0 for available pythons
```

So I installed Python 2.7, and now this:

```
C:\Users\coons\servo> ./mach build --dev
mach does not support python 3 (< 3.5), please install python 3 (>= 3.5)
```

**Comment by jdm** [comment]
Try changing https://github.com/servo/servo/blob/3cd1121a7ddab52db3ca0c64d76460e3fd9db38f/mach.bat#L7 to use `-3` instead. We don't use python 2 any more, and we forgot to update the batch file to reflect that.

**Comment by dominiccooney** [comment]
Thanks @jdm, I worked this out. I can send you the one character patch, just jumping through some permission hoops with my employer.
