### ISSUE TITLE
Failed to run vcvarsall.

### ISSUE THREAD

**Issue by efeskucuk** [servo/servo#28393]
I am having this error when I'm trying to build servo, I'm just getting into it and haven't been able to build it yet,

```
PS C:\Users\Lyphon\Desktop\work\servo\servo> ./mach build --dev
The system cannot find the path specified.
Failed to run vcvarsall. stderr:
Error running mach:

    ['build', '--dev']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

AttributeError: 'NoneType' object has no attribute 'decode'

  File "C:\Users\Lyphon\Desktop\work\servo\servo\python\servo\build_commands.py", line 331, in build
    print(stderr.decode(encoding))
```

I have tried to strictly search it and only found a reference on #26406 but couldn't incorporate the mentioned fix into my build_script.py. The issue says the reason for the error is non-ascii username, I don't think that is the case in my situation.

Also this is what I get when I try to use `./mach busted`,

```
It looks like you are trying to run an unknown mach command: busted

Did you want to run any of these commands instead: rustc, rustup, build?

Run |mach help| to show a list of commands.
```

**Comment by efeskucuk** [comment]
I managed to get past this, the error was happening because of this code,
`vcinstalldir = os.environ.get("VCINSTALLDIR", "") or os.path.join(vsinstalldir, "VC")`

I've fixed it by adding VCINSTALLDIR path using powershell like so,
`setx VCINSTALLDIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC"`

I suspect that the reason I didn't have both VCINSTALLDIR and vsinstalldir as an environment variable was because I installed them using chocolatey but I'm not sure, maybe adding this to README FAQ for building for windows would help some people.

I'm still having some errors but I'll try to fix them myself before submitting a new issue. I didn't close this issue so that it has visibility to remind you if you'd prefer this to be added to FAQ, please close the issue if you think otherwise.

**Comment by jdm** [comment]
Visual Studio 2017 isn't supported any longer. You might have more luck with a more up to date version.

**Comment by efeskucuk** [comment]
I'm closing this as I've solved it by adding it to env variable, thanks.
