### ISSUE TITLE
background in xeredo.it is not rendered properly

### ISSUE THREAD

**Issue by mkg20001** [servo/servo#28464]
Firefox
![image](https://user-images.githubusercontent.com/7735145/120223375-ca710780-c241-11eb-8185-a13e011de551.png)
Servo d16734464567f4ccb9d04acf79e13b31a44adba3
![image](https://user-images.githubusercontent.com/7735145/120223453-eb395d00-c241-11eb-905e-8a96f13c5542.png)

layout 2020

**Comment by jdm** [comment]
From looking at the layout inspector in Firefox, it looks like Servo isn't picking up the `background` CSS property on the root `<html>` element.

**Comment by vpzomtrrfrt** [comment]
The site uses `background: rgba(0, 0, 0, 0) url("https://xeredo.it/5-light.2eb370b2.jpg") no-repeat fixed center center / cover;` as a style. Looks like servo doesn't like `fixed` here, as removing it makes the image appear.

Might be related to #19669?

**Comment by mrobinson** [comment]
This site has changed and there's no reduced test case here unfortunately, so I'm closing this one.
