### ISSUE TITLE
Support RLS or Rust-analyzer

### ISSUE THREAD

**Issue by sagudev** [servo/servo#28526]
It would be useful for newcomers and basically everyone working on servo. There are already some issues on rust-analyzer: https://github.com/rust-analyzer/rust-analyzer/issues/1805

**Comment by teymour-aldridge** [comment]
See also https://github.com/rust-analyzer/rust-analyzer/issues/8113

**Comment by Florian-Schoenherr** [comment]
these are closed, is this done?

**Comment by sagudev** [comment]
It works!
