### ISSUE TITLE
Tracking issue for Rust feature requests

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#2854]
This issue will track the longer-term feature requests that Servo currently has in Rust. It also captures some initial Gecko issues (https://github.com/servo/servo/wiki/Mozlandia-Rust-In-Gecko ). Issues created in Rust should reference this issue, and this top comment will be updated with links to those issues.

# Rust

## Arc<Flow>

We can't do this yet because we made a `get_mut` on `FlowRef` and Rust doesn't have that.

## Optimized representations
rust-lang/rfcs#317

## Cross memory-model data
rust-lang/rfcs#318

## Virtual structs
jdm's requirements: https://gist.github.com/jdm/9900569
Leading current proposal: https://github.com/rust-lang/rfcs/pull/142

## OSX cross-compile build & test

OSX cross compilation keeps / is broken without a builder to test it.

## AARCH64 cross-compile build & test

There is partner interest in ARM64, but we need a builder to keep it working.

## Expose variadic functions to C

Right now, we work around it with a manual wrapper:
https://github.com/servo/servo/blob/master/ports/gonk/src/native_window_glue.cpp#L19-L22

## Nonblocking I/O

Required for Gecko to multiplex videos (and other network I/O ) on a single thread.

## Windows debug info
Gecko, for debugging & stack track dump support.

https://github.com/rust-lang/rust/issues/19533

## Remove Windows MSYS dependency

These are the unwinding libraries and require shipping a binary. If we move to VC toolstack, it goes away.
https://github.com/rust-lang/rfcs/issues/1061

## Reduce toolchain size

110MB will hurt Gecko contributors in developing nations.

# Cargo

## Behave with artifact caching of outputs for incremental builds 

Gecko caches build outputs in S3 for ccache and other language-specific build tools.

## Work cleanly with in-tree copies of all source files

Gecko will commit copies of the full dependency tree in-tree in their single repo.

# Crates.io

## Manage package ownership

https://github.com/rust-lang/crates.io/issues/137

**Comment by metajack** [comment]
https://github.com/servo/heapsize/pull/1#discussion_r36576716

**Comment by tshepang** [comment]
https://github.com/rust-lang/rust/issues/24776 can now be removed

**Comment by larsbergstrom** [comment]
Closing and merging with #2853. There were two separate issues back pre-1.0, but that is no longer needed now.
