### ISSUE TITLE
Package not found: `rustc_ast`

### ISSUE THREAD

**Issue by Nv7-GitHub** [servo/servo#28558]
When I try to compile with
```
cargo build --release
```
I get the error
```
error[E0463]: can't find crate for `rustc_ast`
  --> components/script_plugins/lib.rs:16:1
   |
16 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by jdm** [comment]
Per the readme, you need to build with `./mach build`. This particular issue means you're missing the rustc-dev component for your toolchain, but the build will fail in other ways without mach.
