### ISSUE TITLE
Build error on Manjaro ARM

### ISSUE THREAD

**Issue by mhanberry1** [servo/servo#28562]
While building on Manjaro ARM using `./mach build --release`, compilation failed with the following error:
```
error: linker `aarch64-linux-gnu-gcc` not found
```

I was able to fix this by changing the `[target.aarch64-unknown-linux-gnu]` section in `.cargo/config` to the following:
```
[target.aarch64-unknown-linux-gnu]
linker = "gcc"
ar = "aarch64-linux-gnu-ar"
```

I'd like to make a PR for this fix, but I think my current solution would break the build pipeline when cross-compiling for aarch64.

**Comment by mhanberry1** [comment]
Perhaps a better solution would be to include a section in `README.md` for building on aarch64, which would point to this fix

**Comment by jdm** [comment]
I'm pretty sure this project only officially supports building with clang and LLVM tools at this point.

**Comment by mhanberry1** [comment]
@jdm The original configuration references `aarch64-linux-gnu-gcc` for aarch64 linux builds, though.

**Comment by jdm** [comment]
Yeah, we stopped explicitly supporting this in CI a few years ago. We never bothered cleaning out the old references to it, though.
