### ISSUE TITLE
Work on updating the version of webrender used

### ISSUE THREAD

**Issue by Bryce-MW** [servo/servo#28585]
Hi!

As I mentioned in one of my other PRs, I am working on improving Servo's gradient support. I want to eventually add easing gradients but for now I am working on adding gradient midpoints. To do both of those well (i.e. not an approximation), there needs to be support from webrender. It's probably best to make any additions to the current version of webrender but that means that Servo has to actually work with the current version of webrender. I've been working on this for the past few days [on my fork](https://github.com/Bryce-MW/servo/commits/webrendr-update). I just wanted to make this known so no one else  tries to do the same thing at the same time.

What I am doing first is just going through and doing the minimum needed to get everything to build on the newer versions. Later I will do the cleanup and fix bugs. I have so far introduced one bug which is where I can no longer scroll web-pages but they are interactive otherwise. I've done some debugging but not gotten anywhere so I am going to wait to work on fixing that until later.

Once I am done, I will make a PR but I am happy to do it earlier as a draft if that's better.

**Comment by Bryce-MW** [comment]
I just thought I would do a quick update. I am within  couple dozen commits of webrender master. I think that I will have to rebase my Servo fork and then there are just a couple things after that. There is at least one major bug being scrolling. The way that webrender handles scrolling changed so we need to change as well. Unfortunately, it's a bit of a complex change so I only did a quick but wrong patch. So I'll have to fix that. Then there's a few compiler warnings to fix, mostly because of stuff that was only partially removed. I'll probably do a cargo check over the whole project and see what I can fix. Then there's reformatting everything and getting the media, surfman, and webxr pull requests merged.

I suspect that I'll be done within about a week which is good since I am going back to school next week. Hopefully I'll have enough time in the first few weeks of class to finish actually improving gradients which was the entire point of doing this.

**Comment by Bryce-MW** [comment]
It looks like gradient interpolation is getting [closer to being approved](https://github.com/w3c/csswg-drafts/issues/1332#issuecomment-910891011)! Hopefully that should make it easier for me to get my future modifications to webrender merged there and then here further allowing us to implement gradient midpoints and the new interpolation functions.

**Comment by atouchet** [comment]
WebRender was updated in #30323. Can this issue be closed now?

**Comment by Bryce-MW** [comment]
The pull seems to indicate that it's not fully up to the latest version of Webrender. But this isn't an issue for me personally anymore so I'm happy to have the issue be closed either way

**Comment by mrobinson** [comment]
I think it's fine to close this for now and focus on individual issues that block the next WebRender upgrade. I can open issues for those.
