### ISSUE TITLE
Consider triggering WPT sync nightly job from servo-wpt-sync account

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#28594]
@jdm I found it seems it's not so easy to setup the environment to git push from `servo/servo` to `servo-wpt-sync/servo` from https://github.com/servo/servo/pull/28369.

So, I wonder if it's possible to have a repo (or just the servo repo) under `servo-wpt-sync` account; then, we setup a nightly cronjob in `servo-wpt-sync`'s repo to do this nightly sync. But, we will need a nightly branch and make it as the default branch because currently GitHub Actions only support running cronjob on **default** branch. (or, should we give `servo-wpt-sync` permission to create branches to `servo/servo`?)

Also, I'm wondering if we should create a secret for `servo-wpt-sync`'s GPG key so that we can make sure its commit is verified 🤔 

If this solution sounds plausible, I think the patch of `--always-succeed` for `python/servo/testing_commands.py` in  #28369 should be merged into this repo (`servo/servo`) so that we can avoid throwing exit 1 while executing the command in downstream.

_Originally posted by @CYBAI in https://github.com/servo/servo/issues/28592#issuecomment-914378537_

**Comment by jdm** [comment]
I just updated the WPT_SYNC_TOKEN secret with a new access token 10 minutes ago (it's a personal access token for the @servo-wpt-sync account). Would that potentially fix any issues that you've been having with pushing a branch and opening pull requests?

**Comment by CYBAI** [comment]
Sorry for long delay...

I just tried to use the `ad-m/github-push-action` for git push  in 364785d in https://github.com/servo/servo/pull/28369 but I still got same failure of permission denied 👀 

```
Push to branch 28-04-2022
To https://github.com/servo-wpt-sync/servo.git
 ! [remote rejected]       HEAD -> 28-04-2022 (permission denied)
error: failed to push some refs to 'https://github.com/servo-wpt-sync/servo.git'
```

Is it possibly the WPT_SYNC_TOKEN already expired?

**Comment by jdm** [comment]
This has been addressed by removing servo-wpt-sync from the WPT nightly job entirely.
