### ISSUE TITLE
Why? windows10 setup servo needed four seconds

### ISSUE THREAD

**Issue by zhonghuarenmingongheguo** [servo/servo#28603]
who can tell me why?

**Comment by DraftedDev** [comment]
skill issue

**Comment by atbrakhi** [comment]
I am closing this issue due to lack of details. Please feel free to open a new one with more specific information about your problem or question. You can also reach out to us on Zulip at https://servo.zulipchat.com/

**Comment by atbrakhi** [comment]
I am closing this issue due to lack of details. Please feel free to open a new one with more specific information about your problem or question. You can also reach out to us on Zulip at https://servo.zulipchat.com/
