### ISSUE TITLE
Please consider moving from github.

### ISSUE THREAD

**Issue by microsoftisevil** [servo/servo#28604]
Please consider moving from github. Now that it his in the hands of Microsoft there is no way to trust anything stored here, and we will need Servo to make a safe browser since Mozilla now outsource to Microsoft.

**Comment by jdm** [comment]
This project has no plans to move away from GitHub for the forseeable future.

**Comment by microsoftisevil** [comment]
You're talking like you don't even know about the Halloween Documents, or it is cognitive dissonance.. In any case this project is then to be avoided.
