### ISSUE TITLE
blank screen on OS X, for all websites

### ISSUE THREAD

**Issue by debamitro** [servo/servo#28620]
Here is something I have been seeing for a while with the pre-built executables. So I finally managed to build servo on my Mac, and I see the exact same behaviour. The title bar has the title, but the entire window has nothing but the background colour of the page. Some links and textbooks seem to be rendered - I found that out by moving my mouse. Any pointers for troubleshooting should be useful.

**Comment by jdm** [comment]
Highly likely that this is #26224.

**Comment by debamitro** [comment]
Yes it is the same as #26224 . I wonder if it makes sense to turn off the 'texture-swizzling' (whatever it is) if this graphics card is detected.
