### ISSUE TITLE
Bug: linux runtime deps? symbol lookup error

### ISSUE THREAD

**Issue by mrl5** [servo/servo#28657]
OS: linux
version: nightly@2012-12-31
(I can provide more info about my env just let me know what is needed)

Am I missing some runtime dependency? 
```bash
$ tar xzf servo-latest.tar.gz 
$ cd servo/
$ ./servo 
./servo: symbol lookup error: ./servo: undefined symbol: gst_webrtc_data_channel_state_get_type
```

downloaded latest nightly from https://download.servo.org/nightly/linux/servo-latest.tar.gz

BTW I couldn't find any place where compile and/or runtime dependencies are specified

**Comment by jdm** [comment]
Strange - linux builds are supposed to be using (and including dynamic libraries with) up to date GStreamer dependencies.

**Comment by jdm** [comment]
Oh, I see - https://github.com/servo/servo/blob/21bbca4609419923b02b8801c383cac877476192/python/servo/package_commands.py#L486-L507 doesn't include any special gstreamer packaging, so I guess we currently rely on users having an up to date gstreamer-1.0-plugins-bad package installed.

**Comment by mrl5** [comment]
I'm running Funtoo Linux (distro that was forked from Gentoo Linux years ago). Here are my versions:
* `media-libs/gstreamer-1.14.4`
* `media-libs/gst-plugins-bad-1.14.3`
* `sys-libs/libunwind-1.2.1-r3` (I had to install it to avoid different error `./servo: error while loading shared libraries: libunwind-x86_64.so.8: cannot open shared object file: No such file or directory`)

**Comment by jdm** [comment]
I believe Servo expects a gstreamer version >= 1.16.

**Comment by mrl5** [comment]
> I believe Servo expects a gstreamer version >= 1.16.

Indeed that was a case. Thanks @jdm :) (btw 1.14 is quite old lol...)

for the future is there any place where runtime dependencies are listed of only insiders like you know that its `>= 1.16`?

**Comment by jdm** [comment]
I don't think so! It probably belongs in the readme.

**Comment by mrl5** [comment]
anyways for me the issue is fixed thanks for help :)
