### ISSUE TITLE
The gstreamer-armeabi-v7a-1.16.0 on the s3 is not the correct version

### ISSUE THREAD

**Issue by OneeMe** [servo/servo#28718]
I tried to build the Android target of servo, but failed with error:
"Requested 'gstreamer-sdp-1.0 >= 1.16' but version of GStreamer Library is 1.14.3"
After some investigations, I found that the gstreamer-1.0.pc pkg-config file in dep url "https://servo-deps-2.s3.amazonaws.com/gstreamer/gstreamer-armeabi-v7a-1.16.0-20190517-095630.zip" is not the right version:

```
...
Name: GStreamer
Description: Streaming media framework
Version: 1.14.3
...
```

It seems like someone had deployed the wrong version of the gstreamer-armeabi-v7a-1.16.0

**Comment by jdm** [comment]
In the meantime, I recommend building with `--media-stack=dummy` to avoid dealing with gstreamer at all.

**Comment by mrobinson** [comment]
Closing this as media is currently disabled on Android and when it's enabled again we'll create new binaries.
