### ISSUE TITLE
Loading large fonts in debug builds is painful

### ISSUE THREAD

**Issue by jdm** [servo/servo#28731]
`tests/wpt/mozilla/tests/mozilla/input_value.html` times out in a debug build on macOS because the fallback font selected that contains the glyphs used in the test is Arial Unicode MS, which requires loading and serializing 23mb of font data.

* https://github.com/servo/servo/blob/ecb4f4225acf1742671927a4132ca58de69483ff/components/gfx/font_cache_thread.rs#L528-L549
* https://github.com/servo/servo/blob/ecb4f4225acf1742671927a4132ca58de69483ff/components/gfx/font_cache_thread.rs#L126
* https://github.com/servo/servo/blob/ecb4f4225acf1742671927a4132ca58de69483ff/components/gfx/font_cache_thread.rs#L36
* https://github.com/servo/servo/blob/ecb4f4225acf1742671927a4132ca58de69483ff/components/gfx/platform/macos/font_template.rs#L46

One idea I'm toying with is creating a separate serialization format for IPC font template information (rather than sending the raw FontTemplateData type), which could make use of [IpcBytesSender/IpcBytesReceiver](https://github.com/servo/ipc-channel/blob/589a62cc92d2a686769ade6ad4fa485a9904a02b/src/ipc.rs#L136-L141), which would avoid all of the serde machinery and should improve serialization performance.

**Comment by jdm** [comment]
I verified that the only values from FontTemplateData for mac/windows/linux that need to be sent over IPC is the identifier and the optional bytes. This means that we can define something like:
```rust
struct SerializedFontTemplate {
    identifier: Atom,
    bytes_receiver: IpcBytesReceiver,
}
```
which is actually sent over the wire, and there can be code to convert the platform-specific FontTemplateData to and from this type as necessary.

**Comment by s-maurice** [comment]
Hi. I've had a look and tried to implement the `SerializedFontTemplate` struct, but I am still getting a timeout.
Any guidance on exactly where the timeout is occuring?

From what I can tell, the timeout does not occur in `font_template`.
https://github.com/servo/servo/blob/ecb4f4225acf1742671927a4132ca58de69483ff/components/gfx/font_cache_thread.rs#L522-L551


Timeout message:
``` 
0:28.16 INFO Got timeout in harness
0:28.16 TEST_END: TIMEOUT, expected OK - TestRunner hit external timeout (this may indicate a hang)
```

Was the correct approach to change the trait `FontSource`'s `get_template` to return `SerializedFontTemplate`?

**Comment by jdm** [comment]
The approach I had in mind was:
* `FontSource::font_template` still returns `FontTemplateInfo`
* create a `SerializedFontTemplate` (see earlier comment)
* create a `SerializedFontTemplateInfo` which duplicates `FontTemplateInfo` but contains `SerializedFontTemplate` instead of `Arc<FontTemplateData>`
* `Reply::GetFontTemplateReply` is changed to contain `SerializedFontTemplateInfo` instead of `FonteTemplateInfo`
* Before sending the `GetFontTemplateReply`, convert the `FontTemplateInfo` into a `SerializedFontTemplateInfo` 
* After [sending](https://github.com/servo/servo/blob/ecb4f4225acf1742671927a4132ca58de69483ff/components/gfx/font_cache_thread.rs#L180) the `GetFontTemplateReply` value, send the font template's bytes over with the `IpcBytesSender` that matches the `IpcBytesReceiver` (https://docs.rs/ipc-channel/0.15.0/ipc_channel/ipc/fn.bytes_channel.html)
* In the code that receives `GetFontTemplateReply`, perform a receive on the contained `IpcBytesReceiver` and use that to construct a `FontTemplateInfo` from the serialized data, then return that

Does that make sense?

**Comment by s-maurice** [comment]
Thank you. 
I had done something similar, except that I was sending the template's bytes before sending the `GetFontTemplateReply`.
It makes a lot more sense now, I will rework the commit.

**Comment by s-maurice** [comment]
So I tried to apply the changes as closely as possible to what you have layed out, but I am am still getting the timeout issue.

What I tried is here: https://github.com/s-maurice/servo/commit/58920c755027b5c1536f3c9fde9d3a244157f815

**Comment by jdm** [comment]
Interesting! My next suggestion is to attach a profiler and see where the time goes; that's how I original discovered that the font serialization and deserialization takes 9s in a debug build.

**Comment by jdm** [comment]
When I build your branch and run `./mach test-wpt tests/wpt/mozilla/tests/mozilla/input_value.html` then close the window once the test results appear, I do not see a timeout. The way to be sure is to pass `--no-pause-after-test`; otherwise the harness can sometimes end up reporting a timeout if you look at the results screen for too long.

**Comment by jdm** [comment]
I think the unwrap is reasonable - we know the new template is valid because the data originally came from a valid template. It looks good for a PR!
