### ISSUE TITLE
Serializing webrender display lists is slow in debug builds

### ISSUE THREAD

**Issue by jdm** [servo/servo#28738]
It may be relatively slow in release builds too, but I haven't checked. I profiled https://svelte.dev/docs in a debug build, and a lot of time was spent under the layout thread in WebrenderIpcSender::send_display_list serializing the display list bytes, and a lot of time was also spent in the IPC router thread deserializing the resulting messages for passing to webrender. Like #28731, I suspect that replacing uses of `Vec<u8>` in the types that are serialized with IpcBytesSender/IpcBytesReceiver would be a significant improvement.

**Comment by jdm** [comment]
Relevant types:
* https://github.com/servo/servo/blob/cb80d51f63a24ae6094b726a7ea7c7c77c3534aa/components/script_traits/lib.rs#L1126
* https://github.com/servo/servo/blob/cb80d51f63a24ae6094b726a7ea7c7c77c3534aa/components/script_traits/lib.rs#L1141

The second one is interesting because it uses https://docs.rs/webrender_api/latest/webrender_api/enum.ImageData.html . We may need to define a SerializableImageData type like #28731.

**Comment by jdm** [comment]
The first one could also be challenging: https://docs.rs/webrender_api/0.61.0/src/webrender_api/display_list.rs.html#100-101

**Comment by wusyong** [comment]
Any test for `UpdateImages` to check if it's slow?
I pushed my try here:
https://github.com/wusyong/servo/commit/5abe5f5db17fe4cc490a1a6de9bcebb1d69313ef

For the first one, I suppose we should refactor to a `SerializedBuiltDisplayList` type right?

**Comment by jdm** [comment]
Looks like UpdateImages is only used for 2d canvases, so perhaps http://slither.io/ is a good testcase. Hopefully the webrender code for building the original `Vec<u8>` is optimized enough that we won't lose significant performance in debug builds; just replacing the `Vec<u8>` in the `SendDisplayList` message with `IpcBytesReceiver` should make a big difference.

**Comment by jdm** [comment]
Fixed by #28739
