### ISSUE TITLE
Fedora 35 container unsupported

### ISSUE THREAD

**Issue by tidux** [servo/servo#28741]
````
  File "/var/home/tidux/src/servo/python/servo/bootstrap.py", line 390, in get_linux_distribution
    raise Exception('mach bootstrap does not support %s, please file a bug' % distrib)
Exception: mach bootstrap does not support Fedora Linux, please file a bug
````

This is a Fedora 35 podman container running under Fedora 35 Kinoite (rpm-ostree based distribution).

**Comment by jdm** [comment]
You could try adding an entry of `fedora linux` to the list at https://github.com/servo/servo/blob/69aa81838d8f38fdc09aa8d3d88a5878e383d3a4/python/servo/bootstrap.py#L386 and see what happens!
