### ISSUE TITLE
Non-UWP release builds take significantly longer than UWP release builds

### ISSUE THREAD

**Issue by jdm** [servo/servo#28783]
The Windows release build on CI takes 1h53m to complete. The UWP builds take 1h12m, even though it also builds libstd from scratch and compiles the gstreamer-based media stack. They use the same linker (https://github.com/servo/servo/blob/master/.cargo/config#L25), and the same compiler (https://github.com/servo/servo/blob/c56783caa05a266dc9f8597afab4b34e0313c51c/python/servo/command_base.py#L617). Grepping the logs shows that a UWP build compiles 508 crates, while a non-UWP build compiles 524 crates.

**Comment by jdm** [comment]
Perhaps the fact that the non-UWP build compiles ANGLE is part of it.

**Comment by jdm** [comment]
Addressing #28784 would help narrow down the differences.

**Comment by jdm** [comment]
Update: UWP builds now take 30m compared to 1h50m for non-UWP. Completely wild.

**Comment by michaelgrigoryan25** [comment]
@jdm have you considered building with a different linker such as [mold](https://github.com/rui314/mold) instead of the native one? This might be one of the ways we can optimize the compilation process in CI.

**Comment by mrobinson** [comment]
I think the recent [changes to mozangle](https://github.com/servo/mozangle/pull/58) may have fixed this issue. At least Windows build times are more in line with other platforms. Here's a recent CI run:

![image](https://github.com/servo/servo/assets/13536/f96880ea-735f-42be-977a-41a7cc41e844)

Linux builds are currently a *lot* faster than both Windows and Mac, but I think the huge differences between Windows and other platforms is mostly gone now.
