### ISSUE TITLE
Timing information for dependencies is missing

### ISSUE THREAD

**Issue by jdm** [servo/servo#28784]
I believe this is a regression from the changes in https://github.com/servo/servo/commit/af5a17f94badedd9778b3aa871e4e3d55921e59d. We used to get output like `Completed jobserver v0.1.22 in 0.7s`, but now it's missing.

**Comment by jdm** [comment]
Ah, https://github.com/rust-lang/cargo/pull/10245#issuecomment-1013587498 changed how that information gets output.

**Comment by jdm** [comment]
And the in-console output has actually been removed entirely. Unfortunate. https://github.com/rust-lang/cargo/pull/10245/files

**Comment by jdm** [comment]
We could archive the HTML timing information as part of each build, allowing it to be retrieved later.

**Comment by mrobinson** [comment]
I think we do this now!
