### ISSUE TITLE
MacOS binaries are not usable in latest macOS

### ISSUE THREAD

**Issue by fgarau** [servo/servo#28879]
The macOS binary downloaded from servo.org cannot be run on latest macOS (12.3.1)

"Servo.app" cannot be opened because the developer cannot be verified.

**Comment by yvt** [comment]
It showed an option to open it on a second attempt for me.

**Comment by yvt** [comment]
May I suggest closing this issue? The macOS binary can definitely run on the latest macOS (12.4) after selecting "Open" in a context menu twice.

**Comment by kuchta** [comment]
@yvt HomeBrew will remove servo from it's repository because: `servo has been deprecated because it does not pass the macOS Gatekeeper check! It will be disabled on 2026-09-01.` Which is basically because of that unsigned binaries. Would it be somehow possible to sign it?

**Comment by jdm** [comment]
Yes, we are working out n signing the macOS binaries.
