### ISSUE TITLE
sha256 doesn't match for win prebuild snapshot

### ISSUE THREAD

**Issue by artudytu** [servo/servo#28925]
websites: https://servo.org/ and https://download.servo.org/

https://download.servo.org/nightly/windows-msvc/servo-latest.exe
https://download.servo.org/nightly/windows-msvc/servo-latest.exe.sha256 says it should be:
`2dbd5d5b266da5ea36abf41e39153fdd6fb8940f8daefcd4e816609e19c925bd`

but it is:
certUtil -hashfile Downloads/servo-latest.exe SHA256
SHA256 hash of Downloads/servo-latest.exe:
`a31591302e6d4bf592538dd5164317256e2262d1bc2bd99391bc2e0647c2dd17`

**Comment by JhonnyRice** [comment]
Windows Defender says it is a virus. Here on windows 10 lastest build from the official site

**Comment by JhonnyRice** [comment]
This might be a SERIOUS problem

**Comment by yvt** [comment]
It might be useful to submit suspicious files to [VirusTotal](https://www.virustotal.com/gui/home/upload) and share the results. E.g., I get the following results for recent downloads from <https://download.servo.org/nightly/windows-msvc/servo-latest.exe> (the last part of each URL is a SHA256 hash):
- https://www.virustotal.com/gui/file/594104c84f5f4a34c0ec53ac7a2b36dee9c9f2ae0da12b76852f0384d6cd82a8 ("No security vendors and no sandboxes flagged this file as malicious")
- https://www.virustotal.com/gui/file/11b30d1d95c8c53c6939839463b29967dc8b2467d23b3dc3a79ec2c8c6a34a20 (ditto)

**Comment by artudytu** [comment]
I think we can close this, since hashes seems to be ok now for latest builds.
