### ISSUE TITLE
Please add license files for the servo_arc crate

### ISSUE THREAD

**Issue by kalev** [servo/servo#28966]
Please include LICENSE-MIT and LICENSE-Apache in the servo_arc crate so that the license texts are included with the distributed crate.

(This was noticed in https://bugzilla.redhat.com/show_bug.cgi?id=2124361 during the package review for Fedora.)

**Comment by jdm** [comment]
This will be fixed by https://github.com/servo/servo/pull/28967.

**Comment by kalev** [comment]
Awesome, thank you very much!
