### ISSUE TITLE
SHA256 for Linux binay does not match the provided prebuilt

### ISSUE THREAD

**Issue by rice7th** [servo/servo#29034]
https://download.servo.org/nightly/linux/servo-latest.tar.gz.sha256 says: `38c60616d71397c143e626eab49112a56cae2a9c7d80ee25d64e1a6a82757e6f`

while the computed SHA256 downloaded from https://servo.org says:
`854b97dafac11953a929b67f9910adb7e6a648721326692ada101de856c0f9b8`.

This already happened before in #28925 with windows builds, and it is happening with Linux builds too.

EDIT: removed unnecessary quotes

**Comment by jdm** [comment]
This may be the same as https://github.com/servo/download.servo.org/issues/78
