### ISSUE TITLE
GlobalScope::get_blob_url_id panics when creating a slice of an existing blob

### ISSUE THREAD

**Issue by jdm** [servo/servo#29082]
It starts by borrowing `self.blob_state` for the duration of the function, then calls `self.get_blob_size(..)`, which also borrows `self.blob_state`. This ends up causing various tests that use `URL.createObjectURL` to panic (eg. `./mach test-wpt /fetch/api/basic/scheme-blob.sub.any.html`)

**Comment by mrobinson** [comment]
This seems to have been fixed by 55203d791809ed2eed473284d227c4bcb3fcc8fe.
