### ISSUE TITLE
Please make a release of selectors which already has cssparser 0.29

### ISSUE THREAD

**Issue by federicomenaquintero** [servo/servo#29105]
The cssparser crate made an API break for 0.29, with the removal of the `AtRuleType` enum.  `selectors` is already updated for this.  Could we please have a release?  I'd like to update both crates in librsvg :smiley:

**Comment by atouchet** [comment]
@emilio would you be able to do this? From what I can tell the version in the Servo repo has fallen behind what's being used in Firefox (#28632).

**Comment by jdm** [comment]
Ah, I see why it's more complicated than that: https://github.com/servo/servo/blob/master/components/selectors/Cargo.toml#L28-L31

**Comment by federicomenaquintero** [comment]
Are `to_shmem` and `to_shmem_derive` a problem for the public release?  If so, I can probably submit a PR to put them behind a feature, which Servo would enable for itself.

**Comment by delan** [comment]
I’ve released:

* selectors 0.24.0 (was 0.23.0)
* servo_arc 0.2.0 (was 0.1.1)
* to_shmem 0.0.0 (empty dummy package)
* to_shmem_derive 0.0.0 (empty dummy package)

@federicomenaquintero

**Comment by federicomenaquintero** [comment]
Thank you!!!  Let me try to update librsvg...

**Comment by federicomenaquintero** [comment]
That worked, after the `AtRuleParser` changes.  Thanks for the release!
