### ISSUE TITLE
Intermittent ERROR in /performance-timeline/tentative/include-frames-one-remote-child.sub.html

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#29136]
```
  ▶ ERROR [expected OK] b'/performance-timeline/tentative/include-frames-one-remote-child.sub.html'
  │   → uncaught exception: unknown (can't convert to string)
  │ 
  └ @http://web-platform.test:8000/performance-timeline/tentative/include-frames-one-remote-child.sub.html:24:26

  ▶ Unexpected subtest result in /performance-timeline/tentative/include-frames-one-remote-child.sub.html:
  │ TIMEOUT [expected PASS] b'GetEntries of a ParentFrame with one RemoteFrame child'
  └   → Test timed out
```

**Comment by mrobinson** [comment]
The issue here seems to be that the test is trying to load the wrong URL into a subframe (the path isn't correct) and the server is giving a 404 response with an "application/json" body. Servo does not know how to handle this mime type and gives and error. This always fails for me. I don't know why it's intermittent.

**Comment by CYBAI** [comment]
@mrobinson which platform are you using? in this case, I wonder if it could be an intermittent PASS in the sync PR instead 🤔 If this is a bogus intermittent, I think we should update the status ini files and close this issue 🙏 

(I'd like to try it on my end though, I can't build Servo successfully now so I'm trying to fix the build.)

**Comment by mrobinson** [comment]
> @mrobinson which platform are you using? in this case, I wonder if it could be an intermittent PASS in the sync PR instead thinking If this is a bogus intermittent, I think we should update the status ini files and close this issue pray

I'm on Linux. I agree that we should try to fix the issue and then see if the test is still intermittent.

> (I'd like to try it on my end though, I can't build Servo successfully now so I'm trying to fix the build.)

Sure. I'll upload a fix quite soon.
