### ISSUE TITLE
compile error: cannot transmute between types of different sizes, or dependently-sized types

### ISSUE THREAD

**Issue by sou-chon** [servo/servo#29130]
Hi, I am trying to build using `mach build --dev` but am getting this error from a dependency:

<img width="916" alt="Screenshot 2022-12-11 at 01 59 35" src="https://user-images.githubusercontent.com/35537528/206882992-df207fb9-b4e7-43a1-831c-a5a81cde62c2.png">

any way to solve /circumvent it?

**Comment by jdm** [comment]
Hm, there's no newer release of https://crates.io/crates/display_link that addresses this.

**Comment by jdm** [comment]
https://github.com/BrainiumLLC/display-link/issues/3

**Comment by jdm** [comment]
Servo doesn't actually use the broken code. We canfork the repository and remove it, the update surfman to use the fork instead.

**Comment by jdm** [comment]
https://github.com/servo/surfman/pull/240
