### ISSUE TITLE
App Crashes because wayland not gud :c

### ISSUE THREAD

**Issue by Snowiiii** [servo/servo#29149]
wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
Redirecting call to abort() to mozalloc_abort

Stack trace for thread "main"
   0: servo::backtrace::print
   1: servo::crash_handler::install::handler
   2: <unknown>
   3: _ZL22AnnotateMozCrashReasonPKc
             at /home/snowii/Downloads/servo/target/release/build/mozjs_sys-37b260a6bf2b2075/out/build/dist/include/mozilla/Assertions.h:40:19
      _ZL9MOZ_CrashPKciS0_
             at /home/snowii/Downloads/servo/target/release/build/mozjs_sys-37b260a6bf2b2075/out/build/dist/include/mozilla/Assertions.h:260:3
      mozalloc_abort
             at /home/snowii/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/mozjs/memory/mozalloc/mozalloc_abort.cpp:35:3
   4: abort
             at /home/snowii/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/mozjs/memory/mozalloc/mozalloc_abort.cpp:88:3
   5: wayland_client::imp::proxy::proxy_dispatcher
   6: <unknown>
   7: wl_display_dispatch_queue_pending
   8: wl_display_roundtrip_queue
   9: scoped_tls::ScopedKey<T>::set
  10: smithay_client_toolkit::environment::Environment<E>::new
  11: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new
  12: winit::platform_impl::platform::EventLoop<T>::new
  13: servo::app::App::run
  14: servo::main
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: std::rt::lang_start::{{closure}}
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/core/src/ops/function.rs:606:13
      std::panicking::try::do_call
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library/std/src/rt.rs:148:20
  18: main
  19: <unknown>
  20: __libc_start_main
  21: _start
             at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
Servo exited with return value 11

Please fix had compile 45 Min to get this

**Comment by jdm** [comment]
It's possible that upgrading the winit version in servo might fix this. We're on [version 0.24](https://github.com/servo/servo/blob/master/ports/winit/Cargo.toml#L63), the latest is 0.27.5, and that's where the wayland integration lives.

**Comment by jdm** [comment]
That would also require updating surfman to the same version, like https://github.com/servo/surfman/pull/236.

**Comment by Snowiiii** [comment]
I've been thinking about working on a PR since yesterday :)
