### ISSUE TITLE
failed to select a version for `yeslogic-fontconfig-sys`

### ISSUE THREAD

**Issue by Snowiiii** [servo/servo#29157]
[snowii@archlinux servo]$ ./mach build --release
info: component 'llvm-tools' for target 'x86_64-unknown-linux-gnu' is up to date
    Updating crates.io index
error: failed to select a version for `yeslogic-fontconfig-sys`.
    ... required by package `gfx v0.0.1 (/home/snowii/Documents/rust/servo/components/gfx)`
    ... which satisfies path dependency `gfx` (locked to 0.0.1) of package `canvas v0.0.1 (/home/snowii/Documents/rust/servo/components/canvas)`
    ... which satisfies path dependency `canvas` (locked to 0.0.1) of package `compositing v0.0.1 (/home/snowii/Documents/rust/servo/components/compositing)`
    ... which satisfies path dependency `compositing` (locked to 0.0.1) of package `constellation v0.0.1 (/home/snowii/Documents/rust/servo/components/constellation)`
    ... which satisfies path dependency `constellation` (locked to 0.0.1) of package `libservo v0.0.1 (/home/snowii/Documents/rust/servo/components/servo)`
    ... which satisfies path dependency `libservo` (locked to 0.0.1) of package `libmlservo v0.0.1 (/home/snowii/Documents/rust/servo/ports/libmlservo)`
versions that meet the requirements `^3.0.0` are: 3.0.1, 3.2.0, 3.1.0, 3.0.0

the package `yeslogic-fontconfig-sys` links to the native library `fontconfig`, but it conflicts with a previous package which links to `fontconfig` as well:
package `servo-fontconfig-sys v5.1.0`
    ... which satisfies dependency `servo-fontconfig-sys = "^5.1.0"` of package `servo-fontconfig v0.5.1`
    ... which satisfies dependency `servo-fontconfig = "^0.5.1"` of package `crossfont v0.5.0`
    ... which satisfies dependency `crossfont = "^0.5.0"` of package `sctk-adwaita v0.4.1`
    ... which satisfies dependency `sctk-adwaita = "^0.4.1"` of package `winit v0.27.5`
    ... which satisfies dependency `winit = "^0.27.5"` of package `servo v0.0.1 (/home/snowii/Documents/rust/servo/ports/winit)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='yeslogic-fontconfig-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `yeslogic-fontconfig-sys` which could resolve this conflict

what must i change ?

**Comment by jdm** [comment]
I don't exactly understand what's going wrong, but you could try reverting the changes from https://github.com/servo/servo/commit/f4271e9f3f0fd4c40131d90fa9c4fadc0bad0e1e and see if that helps.

**Comment by jdm** [comment]
I think the issue here is that winit added a dependency that uses servo-fontconfig-sys, but we were trying to migrate away from that package to yeslogic-fontconfig-sys instead.
