### ISSUE TITLE
rustc: Command not found on Ubuntu 12.10 x64

### ISSUE THREAD

**Issue by ffreling** [servo/servo#292]
When trying to build servo on Ubuntu 12.10 x64, the build fails with the following message: 

```shell
make[1]: Entering directory `/home/fabien/servo/build/src/rust-freetype'
/home/fabien/servo/build/src/rust/x86_64-unknown-linux-gnu/stage2/bin/rustc -A default_methods -O  /home/fabien/servo/src/rust-freetype/freetype.rc -o librustfreetype.dummy
make[1]: /home/fabien/servo/build/src/rust/x86_64-unknown-linux-gnu/stage2/bin/rustc: Command not found
make[1]: *** [librustfreetype.dummy] Error 127
```

It appears that servo is looking for rust in **build/src/rust/x86_64-unknown-linux-gnu/** whereas the actual rust build is in **build/src/i686-unknown-linux-gnu/**

**Comment by jdm** [comment]
Haven't heard about this in a very long time.
