### ISSUE TITLE
Is Travis CI still used for Servo?

### ISSUE THREAD

**Issue by atouchet** [servo/servo#29268]
The Travis CI badge in the Readme leads to a 404 page and .travis.yml only includes branches: only: none. Can any of this be removed/replaced?

**Comment by jdm** [comment]
Anything travisCI-related can be removed.

**Comment by atouchet** [comment]
Should the Travis CI badges be replaced with GitHub Actions?

**Comment by jdm** [comment]
I guess that depends if anybody actually finds the ades useful. I personally don't even notice that they exist!

**Comment by jdm** [comment]
I guess that depends if anybody actually finds the badges useful. I personally don't even notice that they exist!

**Comment by atouchet** [comment]
https://github.com/servo/servo/blob/master/python/tidy/Makefile#L4

Should any of this be removed?
