### ISSUE TITLE
Reftests should retry themselves

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#2929]
Ever since #2904, we've been getting quite a few intermittent failures on Linux, mostly with `check-ref-cpu`. There also are some other intermittent failures (like the border or position overflow test) that have been occurring before the Linux thing.

If a reftest fails, can it be retried ~twice?

This could also be done in the travis conf itself, re-run reftest suites a couple of times until they pass.

We could also use the Travis deploy settings to maintain stats of intermittent failures.

Retrying a 22 minute build multiple times isn't really a great way to handle such failures.

**Comment by frewsxcv** [comment]
reftests are no longer a thing. not sure if this issue is still valid for wpt tests
