### ISSUE TITLE
Servo fails to launch on Linux Mint 21.1 with "error while loading shared libraries: libssl.so.1.1"

### ISSUE THREAD

**Issue by 1bcb** [servo/servo#29291]
Operating system: Linux Mint 21.1 Cinnamon
Steps to reproduce:
1)Download and extract servo-latest.tar.gz.
2)Open the servo directory in the terminal.
3)Run `./servo`.
Expected results: Servo launches
Actual results: Nothing happens, and the terminal outputs
`./servo 
./servo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by romulasry** [comment]
Same on Fedora Rawhide.

**Comment by romulasry** [comment]
It should just load the latest ssl on the system. No?

**Comment by mukilan** [comment]
The nightlies are built on Ubuntu 20.04, which [has only v1.1.1 of OpenSSL](https://packages.ubuntu.com/search?keywords=openssl&searchon=all&suite=focal,focal-updates,focal-backports&section=all) so the binary can only link against libssl.so.1.1 
 
Seems like newer releases of Ubuntu and most other distros  do not have v1.1 installed by default and instead use v3 of OpenSSL, which is not fully backwards compatible and requires servo to be compiled and linked against that version.

 If openssl v1.1 package is available via the package manager, then it can be manually installed  (e.g `pacman -S  openssl-1.1 on Arch or Manjaro linux`) along side existing openssl v3 to fix this issue on the user end.

**Comment by 1bcb** [comment]
I don't think libssl.so.1.1 is available in the Ubuntu 22.04 repository.

**Comment by romulasry** [comment]
It would be nice if it would link to any openssl lib.

**Comment by Darkspirit** [comment]
Temporary workaround could be changing
https://github.com/servo/servo/blob/623e7418856892d4bf7c2baca9b0fbfc595231ca/components/net/Cargo.toml#L48
to `openssl = { version = "0.10", features = ["vendored"] }`.

Next rustls release (0.21.0) supports IP SAN. Then we can finally rip out OpenSSL (#7888). I will update my patch.

**Comment by sagudev** [comment]
[Rustls 0.21.0 is released!](https://www.memorysafety.org/blog/rustls-new-features/) 🎉

**Comment by aral** [comment]
Ditto on latest Fedora Silverblue 37
