### ISSUE TITLE
Servo fails to launch on Windows 11

### ISSUE THREAD

**Issue by ensup** [servo/servo#29302]
Operating system: Linux Mint 21.1 Cinnamon
Steps to reproduce:
1)Download and extract servo-latest.zip
2)Open the servo directory
3)Run servo.exe
Expected results: Servo launches
Actual results: Servo launches a while. then just disappeared

**Comment by ensup** [comment]
Same problem on https://github.com/servo/servo/issues/29214

**Comment by mrego** [comment]
Thanks. Let's close this one as duplicated of https://github.com/servo/servo/issues/29214
