### ISSUE TITLE
Unable to launch the Servo minibrowser

### ISSUE THREAD

**Issue by kdwk** [servo/servo#29553]
Having downloaded the latest development snapshot from the website and running the ./servo executable, no window was created and the following appeared in the console instead: `./servo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

This happened in Gnome 44 (Wayland), Fedora Silverblue 38

**Comment by sagudev** [comment]
Did you install openssl? It is usually named something like `openssl1.1`.
