### ISSUE TITLE
White space is not preserved between atomic inlines

### ISSUE THREAD

**Issue by delan** [servo/servo#29590]
https://bucket.daz.cat/work/igalia/servo/0.html

```html
<!doctype html><meta charset="utf-8"
><span>.</span> <span>.</span><br
><div></div> <div></div><br
><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
> <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
><style>
    span, div { background: black; }
    div, img { width: 1em; height: 1em; }
    div { display: inline-block; }
</style>
```

| layout 2020 | layout 2013 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/465303/230285516-306d2a7d-af55-42c3-b712-bcc06972b322.png) | ![image](https://user-images.githubusercontent.com/465303/230285563-a0b28003-3e31-46a8-a391-62ffd79b1a4f.png) |

**Comment by delan** [comment]
Block­Container­Builder­::handle­_text returns early, because Block­Container­Builder­::handle­_leading­_whitespace (which has a FIXME) returns (false, "") when passed an input containing white space only.

**Comment by atbrakhi** [comment]
Would below steps be enough to solve this issue? 

- check if text is consists of white space only
- if true, return the original text as-is

So I guess I am trying to say something like:
```
let text = text.trim_start_matches(|c: char| c.is_ascii_whitespace());

if trimmed_text.is_empty() {
    // Return the original text as-is if it consists of whitespace only.
    return (false, text);
}
```


This seems to fix the issue but I am not sure if this is the right approach according to specification.

**Comment by Loirooriol** [comment]
The proposal above doesn't collapse the spaces if they belong to different nodes:

```html
<script>
let div = document.querySelector("div");
for (let i = 0; i < 10; ++i) {
  div.after(new Text(" "));
}
</script>
```

**Comment by Loirooriol** [comment]
BTW, the spec text is https://drafts.csswg.org/css-text-3/#white-space-rules

**Comment by atbrakhi** [comment]
> ```
> <script>
> let div = document.querySelector("div");
> for (let i = 0; i < 10; ++i) {
>   div.after(new Text(" "));
> }
> </script>
> ```
Are you referring to this FIXME comment here in the [code](https://github.com/servo/servo/blob/e48cfb2ebee7c4b39e13c60253cfc53311f4d8cb/components/layout_2020/flow/construct.rs#L55).  Because I think `handle_leading_whitespace` function is not suppose to handle `collapsing`, but only return a boolean value as the comment on fn suggests.

btw thanks for the link to specs :)

**Comment by Loirooriol** [comment]
Just pointing out that right now no space is preserved, with the patch too many spaces may be preserved. Not sure if this should be addressed here or in that FIXME.
