### ISSUE TITLE
Use `same-origin` as default credential mode for RequestInit

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#29633]
In https://github.com/whatwg/fetch/pull/1153, the default credential mode is changed from `omit` to `same-origin` so we need to fix the default value at

https://github.com/servo/servo/blob/4251159513dc2c7d25f2926baf500f76beec8947/components/net_traits/request.rs#L272

also, with fixing the default value, we can remove the `fallback_credentials` logic in the constructor at

https://github.com/servo/servo/blob/4251159513dc2c7d25f2926baf500f76beec8947/components/script/dom/request.rs#L82-L85

**Comment by AnthonyJ3** [comment]
Hello, I can take responsibility for these changes.

**Comment by CYBAI** [comment]
Thank you! Please feel free to ask questions if you need any helps.

**Comment by AnthonyJ3** [comment]
Sorry for the delay, had some issues with compiling. I'm not the most familiar with this codebase yet so please let me know if there are any glaring issues.

PR: https://github.com/servo/servo/pull/29637
