### ISSUE TITLE
Store debug options in their original data structure

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#29678]
`DebugOptions` is used to store options set in the `servo` binary with `-Z`, but then they are copied into the main data structure. Keeping them in `DebugOptions` would remove a lot of extra code and allow cloning the data structure to avoid passing individual options into the layout thread.

**Comment by jdm** [comment]
I believe the motivation here was about reducing dependencies on the the config crate, which made building very slow  after changing it.

**Comment by mrobinson** [comment]
Thank you for the context, @jdm. I suppose at this point everything is depending on `servo_config` already so there is no harm in removing it for now until we can find a better design.
