### ISSUE TITLE
mozangle does not build on Fedora 38

### ISSUE THREAD

**Issue by paricbat** [servo/servo#29674]
Feel free to ask me any follow-up questions!

**Comment by mrobinson** [comment]
@paricbat Can you paste the command execution and output as part of this bug?

**Comment by mrobinson** [comment]
This seems to be the error

```
  cargo:warning=gfx/angle/checkout/src/common/angleutils.h:41:14: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
  cargo:warning=extern const uintptr_t DirtyPointer;
  cargo:warning=             ^~~~~~~~~
  cargo:warning=             __intptr_t
  cargo:warning=/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
```
This does not look like a missing dependency, but a build error in the mozangle crate.

**Comment by paricbat** [comment]
Adding an `#include <cstdint>` line to two headers seems to fix the problem in mozangle, what should I do?

**Comment by sagudev** [comment]
Try latest version from [servo/mozangle](https://github.com/servo/mozangle).

**Comment by paricbat** [comment]
> Try latest version from [servo/mozangle](https://github.com/servo/mozangle).

@sagudev That's what I did in my previous comment, maybe updating it could help?

**Comment by sagudev** [comment]
Servo is still using mozangle 0.2 while github repo has version 0.3.3. So what you are saying is that you get the same failure on 0.2 and 0.3.3?

**Comment by paricbat** [comment]
Yes, it complains about a missing `#include <cstdint>` on both versions

**Comment by sagudev** [comment]
This should probably go to [upstream mozangle](https://github.com/mozilla/angle/blob/master/src/common/angleutils.cpp) first, as it probably has the same problem. If not then mozangle build script is not working right.

**Comment by paricbat** [comment]
It seems to be fixed in `mozilla/angle`, but not in mozangle's checkout.

**Comment by sagudev** [comment]
Looking through the web it looks like it is [common problem for fedora 38](https://www.spinics.net/lists/fedora-devel/msg309294.html), probably due to gcc 13.

**Comment by VitalyAnkh** [comment]
Arch Linux also updates to GCC 13 and I can't build servo for this error now. Is there anything we can do about this?

**Comment by sagudev** [comment]
@VitalyAnkh Add a patch to [patches direcotry](https://github.com/servo/mozangle/tree/master/patches) that patches [ANGLE](https://github.com/servo/mozangle/tree/master/gfx/angle).

**Comment by VitalyAnkh** [comment]
@sagudev Could we update mozangle to the lastest `mozilla/angle` since mozangle's latest update is on 03/11/2021 (largely falling behind)? This seems a huge update and needs more work, but it's necessary for servo to keep updated and relevant.

**Comment by sagudev** [comment]
Actually last update to [mozilla/angle was in 2019](https://github.com/servo/mozangle/commits/master/gfx/angle), but I find it to cumbersome to do it myself. Either way it also very slow to compiler (especially on windows builds which are notoriously slow), so ideally we could replace it with wgpu(-hal) or something https://github.com/servo/servo/issues/21320.

That's why I think patching is right way for now.

**Comment by VitalyAnkh** [comment]
> so ideally we could replace it with wgpu(-hal) or something https://github.com/servo/servo/issues/21320

It sounds interesting and I'm glad to implement this. In fact, I'm trying to build Servo recently for WebGPU support in Servo.  Why not build WebGL and WebGPU in Servo and fix this build error together? But I'm relatively new here, could you give me some guidance? I have read [the initial WebGPU implementation blog](https://servo.org/blog/2020/08/30/gsoc-webgpu/) and read the relevant code.

**Comment by paricbat** [comment]
I made a pull request with a patch, it's this one https://github.com/servo/mozangle/pull/54

**Comment by andreubotella** [comment]
This issue should be reopened, since #29849 was reverted.
