### ISSUE TITLE
‘transition-property’ should expand shorthands

### ISSUE THREAD

**Issue by delan** [servo/servo#29705]
Toggling the checkbox should transition ‘left’ but does not in Layout 2020 (mach build --with-layout-2020):

```html
<!doctype html><meta charset="utf-8">
<style>
    input {
        position: relative;
        left: 0;
        transition: inset 0.5s;
    }
    input:checked {
        left: 1em;
    }
</style>
<input type="checkbox">
```

https://drafts.csswg.org/css-transitions/#transition-property-property

> For the keyword [all](https://w3c.github.io/csswg-drafts/css-transitions/#valdef-transition-property-all), or if one of the identifiers listed is a shorthand property, implementations must start transitions for all its longhand sub-properties (or, for all, all properties), using the duration, delay, and timing function at the index corresponding to the shorthand.

**Comment by MendyBerger** [comment]
I'm interested in trying to get my hands dirty with this. I don't know if I'll be able to solve it, and I have limited time, but I do have professional Rust experience, so hopefully that will come in handy.

Any useful pointers before I start?

**Comment by jdm** [comment]
Some pointers that might be useful:
* I suspect that https://github.com/servo/servo/blob/a4f936cd726ee4671d1544355a57d36eb2b31f4e/components/style/animation.rs#L1315 is the code that gets triggered when we apply the new the `:checked` style
* We could probably write a unit test for https://github.com/servo/servo/blob/a4f936cd726ee4671d1544355a57d36eb2b31f4e/components/style/properties/helpers/animated_properties.mako.rs#L797 that verifies the transitionable properties that result from https://github.com/servo/servo/blob/a4f936cd726ee4671d1544355a57d36eb2b31f4e/components/style/properties/helpers/animated_properties.mako.rs#L819
* there are existing unit tests of the style code in https://github.com/servo/servo/tree/master/tests/unit/style/

**Comment by MendyBerger** [comment]
@delan seems to be transitioning just fine. An I missing something?
[Screencast from 05-23-2023 11:19:29 PM.webm](https://github.com/servo/servo/assets/12537668/4362c0df-9e1a-4c84-b9ea-e61cf7bc0ac7)

**Comment by delan** [comment]
Sorry, my mistake, it looks like the bug affects Layout 2020, but not Layout 2013.

**Comment by MendyBerger** [comment]
But it needs fixing, right?

**Comment by delan** [comment]
Yes please! Layout 2020 bugs are just as valuable as Layout 2013 bugs.

**Comment by MendyBerger** [comment]
Note: shorthand properties seem to be working fine with transitions.
The issue here seems to be that `inset` is not working correctly, even without transitions.

**Comment by MendyBerger** [comment]
Seems like just adding `servo-2020` here solves the problem.
https://github.com/servo/servo/blob/7d50362c72b86eaface602cfa52827c84b8f9bdd/components/style/properties/shorthands/position.mako.rs#L842


Can it be just that? Should I open a PR?

**Comment by mrobinson** [comment]
@MendyBerger That looks like it might be the culprit. Feel free to open a PR. Thanks for the investigation!
