### ISSUE TITLE
MacOS builds are broken due to different homebrew prefix

### ISSUE THREAD

**Issue by atbrakhi** [servo/servo#29732]
Even after running `bash etc/install_macos_gstreamer.sh`, It gives the same error showing that it is looking for the lzma dependency

<img width="1510" alt="image" src="https://github.com/servo/servo/assets/94557773/fa83d5b5-c5fd-4766-b28a-d4bef4a09d89">

We have come to this conclusion but need to investigate more:
- Currently Dependency exists on following path: `ls -l /usr/local/opt/xz/lib`
- But on MacOS(13.2.1) M2, Homebrew prefix is different then `/usr/local` and dependency exists on `ls -l /opt/homebrew/Cellar/xz/5.4.3/lib/` path.

Since homebrew prefix is different on latest MacOS, it is unable to find it at that path even after installing xz that is resulting in build failure.

**Comment by mukilan** [comment]
Thanks for reporting this @atbrakhi ! I'm trying to figure out which binary is introducing the dependency on  'liblzma.dylib'. If it is gstreamer, then that would be a bug in gstreamer packaging.  Looks like our CI environment and the MacOS environment I used for development both had 'xz' installed via brew, so this didn't show up during my testing and CI runs.

The short term fix could be to bring back 'etc/homebrew/Brewfile' with 'xz' , which should fix it at least for the Intel Macs which use the '/usr/local/' homebrew prefix.

**Comment by mukilan** [comment]
The `liblzma.dylib` dependency is indeed introduced from gstreamer:

```
mukilan@macpro-intel-01 servo % otool -L /Library/Frameworks/GStreamer.framework/Versions/1.0/lib/libavcodec.59.dylib 
/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/libavcodec.59.dylib:
        @rpath/libavcodec.59.18.100.dylib (compatibility version 59.0.0, current version 59.18.100)
        @rpath/lib/libswresample.4.dylib (compatibility version 4.0.0, current version 4.3.100)
        @rpath/lib/libavutil.57.dylib (compatibility version 57.0.0, current version 57.17.100)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
        /usr/local/opt/xz/lib/liblzma.5.dylib (compatibility version 10.0.0, current version 10.0.0)
        @rpath/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1953.255.0)
        /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
        /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
```

I'll report this issue upstream. In the meantime, I'll see if we can have ad-hoc logic  in the packaging code to handle this path.
