### ISSUE TITLE
Implement the rest of the DOMTokenList interface

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#2973]
<http://dom.spec.whatwg.org/#interface-domtokenlist>. Code is at `src/components/script/dom/domtokenlist.rs` and `src/components/script/dom/webidls/DOMTokenList.webidl`.

Requires #1986.

Blocks #2968.

html/dom/elements/global-attributes/classlist-nonstring.html

**Comment by jdm** [comment]
Looks like yes.
