### ISSUE TITLE
Upgrade the webdriver crate to version 0.48

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#29742]
Upgrading this crate will help us to gradually move to using only mio 0.8 and no longer rely on the forked version of mio in `Cargo.toml`. This requires updating all of the references in Cargo.toml and then fixing the build errors including adding Wheel event support to `WebDriverCommandMsg`.

**Comment by atouchet** [comment]
In conjunction with this merging the tungstenite update in #29422 would let us get rid of the tokio 0.2 dependency.

**Comment by michaelgrigoryan25** [comment]
Can I help in any way with fixing this? Let me know.

**Comment by mrobinson** [comment]
@michaelgrigoryan25 Sure! You more or less have to follow the approach outlined above:

1. Update the version in the Cargo.toml file in the repository.
2. Fix the compilation errors.
3. Probably add support for simulating wheel events via `WebDriverCommandMsg`.

**Comment by michaelgrigoryan25** [comment]
Awesome. I will try opening a PR today. Thanks for your input!
