### ISSUE TITLE
A panic in a `./mach smoketest` causes the GitHub Action runner to time out

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#29749]
See https://github.com/servo/servo/actions/runs/4991108054/jobs/8937165682 (PR #29374)

After a panic in `./mach smoketest` the workflow did not terminate and GitHub Actions had to terminate the runner after six hours. This shouldn't happen, instead the job should fail immediately. This may be related to how `./mach smoketest` is wrapped in xvfb.

**Comment by sagudev** [comment]
Running smoketest without xvfb (by passing `--headless` to mach) also [timeouts](https://github.com/sagudev/servo/actions/runs/5005811615/jobs/8970272796).

**Comment by mrobinson** [comment]
It looks like the issue is that the script thread is panicking, but the process is not terminating.
