### ISSUE TITLE
copy_dependencies makes macOS build slow and confusing

### ISSUE THREAD

**Issue by jdm** [servo/servo#29764]
The changes to copy all dependencies and rewrite them to relative paths causes my build to take an extra minute beyond what the build claims it took (`Finished dev [unoptimized + debuginfo] target(s) in 2m 49s`), and it displays no output while that happens.

**Comment by jdm** [comment]
```
godot:servo jdm$ PYTHON3=$(which python3.9) time ./mach build --dev
info: component 'llvm-tools' for target 'x86_64-apple-darwin' is up to date
      Timing report saved to /Users/jdm/src/servo/target/cargo-timings/cargo-timing-20230520T180622Z.html
    Finished dev [unoptimized + debuginfo] target(s) in 4.87s
Succeeded in 0:00:04
       70.88 real        12.89 user        21.05 sys
```

**Comment by mrobinson** [comment]
I wonder if we could:

 - Move the download into `./mach boostrap-gstreamer`
 - Package the libraries only when running `./mach upload-nightly`
