### ISSUE TITLE
Remove all magic leap embedding and support code

### ISSUE THREAD

**Issue by jdm** [servo/servo#29773]
This includes:
* ports/libmlservo
* https://github.com/servo/servo/blob/4339b3bab494e477b502f82137bd360a963ec2be/python/servo/command_base.py#L813
* any python code using a `magicleap` argument
* https://github.com/servo/servo/tree/4339b3bab494e477b502f82137bd360a963ec2be/support/magicleap

**Comment by michaelgrigoryan25** [comment]
On it.

**Comment by michaelgrigoryan25** [comment]
@jdm, should https://github.com/servo/servo/tree/4339b3bab494e477b502f82137bd360a963ec2be/support/magicleap be removed completely?

**Comment by jdm** [comment]
Yep!

**Comment by michaelgrigoryan25** [comment]
Sourcegraph reports 226 instances of magicleap: <https://sourcegraph.com/search?q=context%3Aglobal+repo%3Agithub.com%2Fservo%2Fservo+magicleap&patternType=standard&sm=1&groupBy=repo>. Should we remove them all?

**Comment by jdm** [comment]
Yep!
