### ISSUE TITLE
Cannot extend WebIDL classes

### ISSUE THREAD

**Issue by sagudev** [servo/servo#29770]
Minimal example:
```js
class Klass extends EventTarget {
        meth() {
            return true
        }
}
let a = new Klass();
a.meth(); // Fails with a.meth is not a function
```
In Firefox it runs as expected.

Live testcase is available here: https://sagudev.github.io/test-cases/extendEventTarget

**Comment by jdm** [comment]
My first guess here would be that upgrading spidermonkey would help.

**Comment by sagudev** [comment]
I checked Firefox ESR 78 and ESR 102 and both were working so it must be Servo.

**Comment by sagudev** [comment]
There are failing wpt tests for this: https://github.com/servo/servo/blob/b7674fcec021e89f9b9c2bc52832fdbdd16ec8df/tests/wpt/metadata/dom/events/EventTarget-constructible.any.js.ini#L7-L10
This is important because this functionality is required by some other wpt test that use: https://github.com/servo/servo/blob/b7674fcec021e89f9b9c2bc52832fdbdd16ec8df/tests/wpt/web-platform-tests/speculation-rules/prerender/resources/utils.js#L25

There is approx. 200 wpt test using it and it is also used by newer webgpu cts.

**Comment by fabricedesre** [comment]
Note that this is not specific to `EventTarget`, this looks like we fail the same way for all webidl defined interfaces.

For instance, this will throw in Servo but pass in Gecko:

```javascript
class MyRect extends DOMRectReadOnly {
    constructor(x = 0, y = 0, width = 0, height = 0) {
      super(x, y, width, height);
      console.log(`In MyRect constructor`);
    }

    surface() {
      return this.width * this.height;
    }
  }

  console.log("=== Start MyRect ===");
  let rect = new MyRect(0, 0, 10, 10);
  console.log(`prototype is ${MyRect.prototype}`);
  try {
    console.log(`PASS: ${rect.surface()}`);
  } catch (e) {
    console.error(e);
  }
```

Servo output:
```
=== Start MyRect ===
In MyRect constructor
prototype is [object DOMRectReadOnly]
MyRect.toJSON
MyRect.x
MyRect.y
MyRect.width
MyRect.height
MyRect.top
MyRect.right
MyRect.bottom
MyRect.left
TypeError: rect.surface is not a function
```

Firefox output:
```
=== Start MyRect ===
In MyRect constructor
prototype is [object DOMRectReadOnly]
MyRect.toJSON
MyRect.x
MyRect.y
MyRect.width
MyRect.height
MyRect.top
MyRect.right
MyRect.bottom
MyRect.left
PASS: 100
``` 

Looks like DOM bindings are not hooking up properly with spidermonkey?

**Comment by jdm** [comment]
This might be because we don't create constructor objects like Gecko does:
* https://searchfox.org/mozilla-central/rev/065102493dfc49234120c37fc6a334a5b1d86d9e/dom/bindings/BindingUtils.cpp#1108-1112
* https://github.com/servo/servo/blob/d733abfca02cdb9fd2af4f0d82ff050e25f71829/components/script/dom/bindings/codegen/CodegenRust.py#L3301-L3309

**Comment by jdm** [comment]
Or it may be because we're missing call and construct hooks from https://github.com/servo/servo/blob/d733abfca02cdb9fd2af4f0d82ff050e25f71829/components/script/dom/bindings/codegen/CodegenRust.py#L2344-L2346

**Comment by jdm** [comment]
The Firefox devs suggested that relevant Gecko code is https://searchfox.org/mozilla-central/rev/2d678a843ceab81e43f7ffb83212197dc10e944a/dom/bindings/BindingUtils.cpp#3667

**Comment by jdm** [comment]
I think I see how to put the pieces together here. It requires some codegen changes and a PR to mozjs.

**Comment by jdm** [comment]
I have a branch that makes https://sagudev.github.io/test-cases/extendEventTarget pass. Now I just need to generalize the code to work with other DOM interfaces than EventTarget.
