### ISSUE TITLE
Can't bootstrap on Ubuntu

### ISSUE THREAD

**Issue by MendyBerger** [servo/servo#29783]
From the README
> If ./mach bootstrap doesn't work, file a bug

`./mach bootstrap` throwing the following error:

```
Traceback (most recent call last):
  File "[path]/servo/./mach", line 47, in <module>
    main(sys.argv)
  File "[path]/servo/./mach", line 27, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "[path]/servo/python/mach_bootstrap.py", line 242, in bootstrap_command_only
    _activate_virtualenv(topdir, is_firefox_checkout(topdir))
  File "[path]/servo/python/mach_bootstrap.py", line 179, in _activate_virtualenv
    exec(compile(open(activate_path).read(), activate_path, 'exec'), dict(__file__=activate_path))
FileNotFoundError: [Errno 2] No such file or directory: '[path]/servo/python/_virtualenv3.10/bin/activate_this.py'
```

**Comment by MendyBerger** [comment]
Seems like `/python/_virtualenv3.10/local/bin/activate_this.py` does exist. So I changed the following to `local/bin`. Hope I didn't bootstrap the wrong thing...

https://github.com/servo/servo/blob/ec4d90d5729c84337bb3546fb24b13b5942c49fe/python/mach_bootstrap.py#L98

**Comment by mrobinson** [comment]
Huh. It shouldn't even get to line 179 if `...python/_virtualenv3.10/local/bin/activate_this.py` doesn't exist. See line 167.

**Comment by MendyBerger** [comment]
Yeah, that's weird :shrug:

**Comment by mrobinson** [comment]
Can you run the following python script in the same shell and comment with the output here?

```python
import sysconfig
print(sysconfig.get_default_scheme())
```

**Comment by mrobinson** [comment]
Looks like you are hitting this issue: https://askubuntu.com/questions/1406304/virtualenv-installs-envs-into-local-bin-instead-of-bin

**Comment by MendyBerger** [comment]
Oh wow! Thanks so much!
