### ISSUE TITLE
Runing mach try fails with missing GStreamer.

### ISSUE THREAD

**Issue by sagudev** [servo/servo#29797]
There is no need for GStreamer in mach try. There may be other commands effected by this.
```console
>mach try windows
Error running mach:

    ['try', 'windows']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

FileNotFoundError: GStreamer libraries not found (>= version 1.16).Please see installation instructions in README.md

  File "C:\Users\user\servo\python\servo\devenv_commands.py", line 327, in try_jobs
    res = call(["git", "push", remote, "--force", f"HEAD:{b}"], env=self.build_env())
  File "C:\Users\user\servo\python\servo\command_base.py", line 524, in build_env
    servo.platform.get().set_gstreamer_environment_variables_if_necessary(env, cross_compilation_target=target)
  File "C:\Users\user\servo\python\servo\platform\base.py", line 64, in set_gstreamer_environment_variables_if_necessary
    raise FileNotFoundError(
```

**Comment by sagudev** [comment]
This is probably caused by https://github.com/servo/servo/pull/29781.

I believe the causing prablem is `call(..., env=self.build_env())`.

**Comment by sagudev** [comment]
Okay so commands that use `self.build_env()` for unknown reason are:
- `mach grep`
- `mach try`

Then there are others that might need build_env, but not Gstreamer:
- `mach fmt`
- `mach test-tidy`

I believe in that case it is also not possible to build servo without gstreamer even with `media-dummy`.

**Comment by sagudev** [comment]
Hm, thats not on master: https://github.com/servo/servo/blob/e9a7787a4d7e3a836853fd8b319951f20879fc83/python/servo/command_base.py#L523-L524

Also shouldn't we only check for media-gstreamer rather than not media-dummy.

**Comment by mrobinson** [comment]
Oh yeah, I mean this could be a change we could make to the call. I'm not sure if it's safe to check for "media-gstreamer" in features here, since it isn't always passed to the function. Maybe this would work if we checked `self.features` instead.
