### ISSUE TITLE
Investigate windows unit-tests

### ISSUE THREAD

**Issue by sagudev** [servo/servo#29815]
Unit-tests step in windows is currently running ~1h (like normal build); while linux and mac are runnig only ~15 min. This was caused by switching to resolver 2 in https://github.com/servo/servo/commit/6a8ba164395574e31179d8ccb79fd903bb75ddb5. I suspect there may be wrong features selected on mozangle; which could cause a rebuild.

**Comment by dvtkrlbs** [comment]
It also seems linke the mozangle build is really poorly parallilized or it spends some time by doing nothing. Looking at the resource usage it spends up to 5 minutes on the mozangle step with non noticable cpu usage.

**Comment by sagudev** [comment]
A while back I tried to separate windows workflow for build and unit-test so that they could run in parallel, but look like unit-testing depends upon building (only on windows), which is a bug in my opinion.

Relevant code is here: https://github.com/servo/servo/blob/master/python/servo/command_base.py#L619

My plan is to remove this dirty hack so unit-test could be run standalone and then split the workflow.

**Comment by mrobinson** [comment]
The unit test step in Windows is now something like 15 minutes in comparison to 10 minutes for Linux. There's improvements to be made, but I think this can be closed.
