### ISSUE TITLE
Run flaky tests as a separate test run

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#2982]
Depends on  #2981 

We have a couple of flaky reftests and wpt tests. As time passes, more might crop up.

It might be worthwhile to not run these as part of the main test run, and instead have a separate run (`$FLAKY=1` or something), where we run all the flaky tests.

This way we can configure the built matrix to [allow failures](http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail) for those tests.

@larsbergstrom thoughts?

**Comment by cyplo** [comment]
It's been a while, are tests now run separately ?

**Comment by jdm** [comment]
Nope. Instead we have a result filtering step that ignores tests that are known to have intermittent failures.

**Comment by cyplo** [comment]
@Manishearth Do you think this can be closed now ?
