### ISSUE TITLE
Replace callargs_is_constructing with a method on CallArgs

### ISSUE THREAD

**Issue by jdm** [servo/servo#29821]
I added it as a function in utils.rs for expediency, but it belongs in https://github.com/servo/mozjs/blob/b9edc816b6662a5986e190cdf53ae295049acb92/mozjs/src/jsimpls.rs#L221 instead.

**Comment by saito828koki** [comment]
I would like to work on this issue. Let me confirm what we would like to do before starting to work on it.

What we need to do is,

1. Add a new method `is_constructing` that is equivalent to `callargs_is_constructing` to `JS::CallArgs` https://github.com/servo/mozjs/blob/573f19426041ec6e1c166da71c0320257d1bd660/mozjs-sys/src/jsimpls.rs#L304
2. Replace all the usage of `callargs_is_constructing` in servo/servo  like `callargs_is_constructing(args)` -> `args.is_constructing()`

Do I understand correctly?

**Comment by jdm** [comment]
Correct!

**Comment by saito828koki** [comment]
Thank you! Made a PR in mozjs repo.
