### ISSUE TITLE
Devtools support is broken

### ISSUE THREAD

**Issue by delan** [servo/servo#29831]
[Devtools](https://github.com/servo/servo/wiki/Devtools) support seems to be broken as of Firefox 110.

The connection prompt works, and there are no messages afterwards under RUST_LOG=trace,

![image](https://github.com/servo/servo/assets/465303/f5e2c6c1-686d-4df9-803c-4310b90f9bd9)

but in about:debugging, there are no tabs:

![image](https://github.com/servo/servo/assets/465303/2157c7e8-7386-400e-ac2b-08984c875927)

**Comment by sagudev** [comment]
https://servo.zulipchat.com/#narrow/stream/263398-general/topic/devtools

**Comment by fabricedesre** [comment]
I started to look at that, and have WIP fixes: runtime info, tabs and process list are working. Still need to fix tab inspection.

![image](https://github.com/servo/servo/assets/984767/04d4a731-3f70-4532-b16d-20983f4a7bf9)

**Comment by fabricedesre** [comment]
I'm following up my debuggin with Gecko devtools team in https://bugzilla.mozilla.org/show_bug.cgi?id=1836856

**Comment by sagudev** [comment]
Any progress?

I would really like to use it for console.

**Comment by fabricedesre** [comment]
Sorry I didn't have time to look at it more yet. My current changes are here: https://github.com/fabricedesre/servo/tree/devtools

Next step is to implement the frame watcher actor afaict.

**Comment by ochameau** [comment]
FYI, I provided some up-to-date documentation about firefox protocol:
https://firefox-source-docs.mozilla.org/devtools/backend/actor-hierarchy.html
This isn't necessarily complete, but should cover most high level actors.

And also some unit tests which highlights the typical JSON packets transfered to debug a page:
https://hg.mozilla.org/integration/autoland/file/aceb5aaeb650bdd368d51487444ae2eeb497f028/devtools/server/tests/browser/browser_document_rdp_basics.js

Hopefully all this would help replicate a rust implementation for servo.

**Comment by spookyvision** [comment]
suggestion: update the [devtools wiki page](https://github.com/servo/servo/wiki/Devtools) to clarify that devtools support is currently broken

**Comment by oSoMoN** [comment]
Following up on #32227, I'm interested in working on this. Can someone please assign to me?

**Comment by sagudev** [comment]
> Following up on #32227, I'm interested in working on this. Can someone please assign to me?

I think Devtools support is part of outreachy, so someone might already be assigned. @mrobinson?

**Comment by delan** [comment]
(see #32404)
