### ISSUE TITLE
New crates.io release of selectors?

### ISSUE THREAD

**Issue by novedevo** [servo/servo#29842]
Hi, the released version of `selectors` (0.24.0) uses an outdated version of `phf` (0.8.0) that, ultimately, depends on an outdated version of `getrandom` (0.1.16) that causes a build error on Alpine Linux 3.16+ and other musl-based distros. This has already been fixed by 11b7a75, which updated the `phf` dependency to 0.10.0, but the crates.io version is still broken. A patch release (e.g. 0.24.1) would fix this, and no new code needs to be written. 

note: I'm unfamiliar with servo's releasing guidelines, so forgive my ignorance if this isn't as easy as I think.

Thank you for all your work!

**Comment by mcatanzaro** [comment]
Hi there @emilio @mrobinson, any idea who to talk to about getting a new selectors release?

**Comment by emilio** [comment]
I published servo-arc 0.3.0 / selectors 0.25.0 with the code from:

  https://hg.mozilla.org/mozilla-central/rev/07613976379f96a9416021b138ba21870fe2065d

Plus the attached patch, removing the to_shmem dependency: https://gist.github.com/emilio/17f456ee432be330ee196b839ee54e3c
