### ISSUE TITLE
Infinite loop with flexbox in layout-2020

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#29852]
This causes an infinite loop:

```html
<div style="display: flex; width: 0px">
  <div style="flex: 1 1 0px; margin: 1px"></div>
</div>
```

The reason is that the spec is not avoiding a `0 / 0` division, so servo ends up with NaN lengths and the algorithm doesn't advance as expected. See https://github.com/w3c/csswg-drafts/issues/8928

**Comment by fabricedesre** [comment]
Gecko ends up with a 0x2 outer div:
![image](https://github.com/servo/servo/assets/984767/1fc66cf9-d8ca-4f74-bd6a-4edbc5f95fd3)

and the inner one:
![image](https://github.com/servo/servo/assets/984767/99a47eb1-81c9-434f-8644-999d65b31004)
