### ISSUE TITLE
De-dupe itoa crate

### ISSUE THREAD

**Issue by atouchet** [servo/servo#29941]
The only remaining usage of itoa 0.4 is in the style crate. This update was apparently already done in Gecko https://github.com/mozilla/gecko-dev/commit/a211cd2aeae38881504f3f1576d60546ae11dbbb but I do not know the process for keeping Servo's version in sync.

**Comment by mrobinson** [comment]
@Loirooriol is in the process of updating the style crate. This is going to take a while, but it's moving forward steadily.

**Comment by atouchet** [comment]
This was done in #30421.
