### ISSUE TITLE
Use `padding_border_sums` when possible

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#29972]
These could use `pbm.padding_border_sums.block`:

https://github.com/servo/servo/blob/041d95e0f4ef08dddab22e0276204240682cdf79/components/layout_2020/flow/mod.rs#L816

https://github.com/servo/servo/blob/041d95e0f4ef08dddab22e0276204240682cdf79/components/layout_2020/flow/mod.rs#L880-L881

There is also the similar

https://github.com/servo/servo/blob/041d95e0f4ef08dddab22e0276204240682cdf79/components/layout_2020/flow/mod.rs#L1045-L1046

but `BoxFragment` stores the padding, border and margin separately instead of using a `PaddingBorderMargin`.

**Comment by mrobinson** [comment]
@Loirooriol Should we close this now that #29977 has landed or do you think there's more work to do here?

**Comment by Loirooriol** [comment]
Yeah it's fine
