### ISSUE TITLE
Empty inline formatting contexts are not collapsing through

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#29994]
```html
<body style="margin-top: 50px;">
    <div><span></span></div>
    <p style="background: green; margin-top: 50px;">Content</p>
</body>
```

Layout 2020:

![Layout 2020](https://github.com/servo/servo/assets/13536/c3d3d2fb-71d3-4de4-ac48-cc5289ef9355)

Layout 2013 and Gecko:

![Layout 2013 and Gecko](https://github.com/servo/servo/assets/13536/c8d5b640-c58c-4568-98d3-137f2087dc4b)

**Comment by Loirooriol** [comment]
Relevant spec: https://drafts.csswg.org/css-inline/#invisible-line-boxes
