### ISSUE TITLE
Make layout-2020 meta files the default for `./mach test-wpt`

### ISSUE THREAD

**Issue by ohno418** [servo/servo#30036]
Currently, `./mach test-wpt` defaults to using a meta file in `tests/wpt/meta-legacy-layout` (layout-2013). To use the layout-2020 meta file, we must specify the `--layout-2020` option.

Given that Servo is now built with layout 2020, it seems more natural for the layout-2020 meta files to be used by default.

**Comment by Loirooriol** [comment]
Also, to test legacy layout, it would probably be better to use `--legacy-layout` to align with `./mach run`.
