### ISSUE TITLE
Try builds are created for issue comments

### ISSUE THREAD

**Issue by jdm** [servo/servo#30044]
See the list of builds at https://github.com/servo/servo/actions/workflows/try.yml and corresponding comments in https://github.com/servo/servo/issues/30043#issuecomment-1656768211 . It's very confusing!

**Comment by mrobinson** [comment]
Unfortunately this is a limitation of the GitHub Actions API. Previously all these comments would have also triggered webhook calls as well AFAIK. I wonder if we should think about a different way of triggering try builds now...

**Comment by mukilan** [comment]
The try comment builds also consume available runners when they execute, slowing down the normal builds. Perhaps we can switch back to Webhook for issue comments and have AWS Lambda handlers to trigger the actual workflows?
