### ISSUE TITLE
AddressSanitizer Handling Code in build_command.py

### ISSUE THREAD

**Issue by MJUCOM** [servo/servo#30051]
Hi all!

I'm currently facing an issue while trying to use AddressSanitizer in the Servo program. I made modifications to the .servobuild file and added the rustflag command to enable AddressSanitizer as shown below:

```
# Any optional flags that will be added to $RUSTFLAGS
rustflags = "-Zsanitizer=address"
```

However, during the build process of the Servo program, I encountered some errors. Upon investigating the 'build_commands.py' code, I noticed that it doesn't handle the AddressSanitizer flag, which might be the root cause of the issue with using AddressSanitizer.

To address this, I attempted to add code in build_commands.py to handle the AddressSanitizer flag as follows:

```
  #Servo with address Sanitizer
  if "-Zsanitizer" in env.get("RUSTFLAGS",""):
      opts = ["-Zbuild-std" , "--target", host or target] + opts
```

Despite this addition, I'm still encountering errors. I am wondering if I need a specific code snippet or modification in build_commands.py to properly handle the rust AddressSanitizer flag for the Servo program.

Any help or guidance on this matter would be greatly appreciated! Thank you and have a nice day!

**Comment by mrobinson** [comment]
Can you paste the error you encounter when you add `-Zsantizer=address` to rustflags? You shouldn't need to do anything else.

**Comment by MJUCOM** [comment]
Thank you for your comment! I handle the issue right now!!
