### ISSUE TITLE
linebreak_simple_*.html fails often on OS X

### ISSUE THREAD

**Issue by metajack** [servo/servo#3008]
It was added to the flaky ref tests, but appears to be mostly-fail not sometimes fail. This seems to happen only on OS X.

If you look at the output of _a and _b versions, there is a real difference in that one version the third line starts flush with the left edge and the other has some whitespace there.

**Comment by frewsxcv** [comment]
This hasn't been reported in a year and half, closing for now. Reopen if you encounter it again
