### ISSUE TITLE
servo rustc version

### ISSUE THREAD

**Issue by MJUCOM** [servo/servo#30087]
Hello everyone!

I'm facing an issue building the Servo program. I'm trying to build Servo using rustc version 1.64.0. However, I believe that the current Servo program is configured for rustc version 1.65. I'd like to revert to the version of the Servo program that uses rustc 1.64 by using the git reset command, but I can't find the git log entry for when Servo was using rustc 1.64.

Does anyone know the git log entry corresponding to Servo's usage of rustc version 1.64?

Thank you and have a great day! :)

**Comment by mrobinson** [comment]
You can find this information by running:

```sh
git log -- rust-toolchain
```

You simply need to find the version of the nightly that corresponds to the version of rust you'd like to use. In general, you should always try to use the latest version of Servo though.

**Comment by mrobinson** [comment]
By the way, for these types of issues which are merely asking questions, it's better to open a discussion at https://github.com/servo/servo/discussions. The issue tracker is used to track bugs and features.
