### ISSUE TITLE
Multiple url's sent to the same Constelation

### ISSUE THREAD

**Issue by jxs** [servo/servo#3010]
if you run servo without an url, servo outputs: `servo asks that you provide 1 or more URLs`
but if you provide more than url, that url is sent to the same constellation and servo crashes:
`task '<main>' failed at 'compositor received SetLayerClipRect for nonexistent layer', /Volumes/data/dev/jxs/servo/src/components/compositing/compositor.rs:532`

`task '<main>' failed at 'dropping a M:N scheduler pool that wasn't shut down', /Users/jack/src/rust/src/libgreen/lib.rs:575`
Also there's this comment on [handle_request](https://github.com/servo/servo/blob/master/src/components/compositing/constellation.rs#L347)

**Comment by nox** [comment]
This doesn't seem to be true anymore.
