### ISSUE TITLE
Test results can ping random users

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#30103]
For example, https://github.com/servo/servo/pull/30099#issuecomment-1678463732 has results like

```
- OK /css/css-values/viewport-units-media-queries.html
  - PASS [expected FAIL] subtest: @media(width:100vi) applies 
```

where Github treats `@media` as a ping to a user, which may not be great for that user.

This can be avoided by using `@<!---->media`, which is the shown as: @media

**Comment by sagudev** [comment]
Didn't we used to put results in code brackets?

**Comment by Loirooriol** [comment]
I don't know, but code blocks may be best to also also avoid `<` or `&` being parsed as HTML, or `*`, `_` etc. being parsed as markdown.
