### ISSUE TITLE
Allow testing webgpu (but not by default)

### ISSUE THREAD

**Issue by sagudev** [servo/servo#30144]
Currently webgpu is not tested by main workflow.

We can either:
1. test webgpu by default (not recommended as webgpu is still not finalized spec & it's slow)
2. add wpt-string to runners so we can trigger wpt runs only on specific tests (this would require reviewers to manually trigger run with _webgpu string)

While we could plug second option into workflow, I suggest we start encoding info in commits like its done on mozilla try.

cc @mrobinson

**Comment by sagudev** [comment]
Here is quick JSON schema sketch: 
```jsonc
{
    ["linux", "mac", "windows"]: {
            "wpt": { // default: null; so no wpt run
                    layout: ["none", "2013", "2020", "all"], // default: "all"
                    test-list: string, // default: ""
             }
            "unit-tests": boolean, // default: false
            // always: "upload": true
    }
}
```

**Comment by mrobinson** [comment]
This seems like a reasonable approach, though we should take a holistic look at how we trigger try runs. Maybe this is a conversation to start in Zulip.

**Comment by sagudev** [comment]
This was done as we have `T-webgpu` label now.
