### ISSUE TITLE
Running tests in `ports/winit/prefs` leads to `libservo` compilation failure.

### ISSUE THREAD

**Issue by atbrakhi** [servo/servo#30189]
Running any of the tests in `ports/winit/prefs.rs` results in compilation failure. Error:
 
```
error[E0433]: failed to resolve: use of undeclared crate or module `media_platform`
   --> components/servo/lib.rs:271:13
    |
271 |             media_platform::init();
    |             ^^^^^^^^^^^^^^ use of undeclared crate or module `media_platform`

error[E0433]: failed to resolve: use of undeclared crate or module `media_platform`
    --> components/servo/lib.rs:1033:13
     |
1033 |             media_platform::init();
     |             ^^^^^^^^^^^^^^ use of undeclared crate or module `media_platform`

For more information about this error, try `rustc --explain E0433`.
warning: `libservo` (lib) generated 1 warning
error: could not compile `libservo` due to 2 previous errors; 1 warning emitted
```

While passing `features=["media-gstreamer"]`  with  `libservo = { path = "../../components/servo", features=["media-gstreamer"] }` in `cargo.toml` fixes the compilation error, I am not sure if this is the best approach.

**Comment by jdm** [comment]
How are you running the tests?

**Comment by atbrakhi** [comment]
I used vscode `Run test` for running the test.

I am also able to see this failure if I go to my branch `rename_winit_package`(see [PR](https://github.com/servo/servo/pull/30163)) and add "servoshell" to [this](https://github.com/servo/servo/blob/acf7fdb90c65f6d00ec147d2f12d5dae95eeff10/python/servo/testing_commands.py#L199) in addition to the changes already made

**Comment by sagudev** [comment]
You must choose one of media backends (dummy or GStreamer): https://github.com/servo/servo/blob/70f00889860ff12feb7ffec45cf383094c1cac88/components/servo/lib.rs#L174

It might make more sense to make media-dummy default and use GStreamer only if requested so we would use something like:
`#[cfg(not(feature = "media-gstreamer"))]`

But that would require to always depend on `servo-media-dummy` which IMO is the way to go as that would also help mach-less cargo commands.

**Comment by sagudev** [comment]
> It might make more sense to make media-dummy default and use GStreamer only if requested so we would use something like: `#[cfg(not(feature = "media-gstreamer"))]`
> 
> But that would require to always depend on `servo-media-dummy` which IMO is the way to go as that would also help mach-less cargo commands.

I did quick PR for this: https://github.com/servo/servo/pull/30240

**Comment by mrobinson** [comment]
@atbrakhi does @sagudev's PR fix the issue here?

**Comment by atbrakhi** [comment]
yes, it has fixed the issue. thanks @sagudev
