### ISSUE TITLE
Handle type attribute for module script in case-insensitive

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#30205]
Currently, we always check the `type` attribute in case-sensitive way for `"module"`.

https://github.com/servo/servo/blob/66dd68a210566f3604195ea306ebc350aa3984d5/components/script/dom/htmlscriptelement.rs#L1189

However, based on Step 10 of https://html.spec.whatwg.org/multipage/#prepare-a-script, browsers should always check the attribute in case-insensitive way. Also, in Step 8 of https://html.spec.whatwg.org/multipage/#prepare-a-script, it mentions that the type string should be trimmed with leading and trailing ASCII whitespaces.

Thus, we need to fix the checking in the above line; then, we should be able to fix the failing tests in https://github.com/servo/servo/blob/master/tests/wpt/tests/html/semantics/scripting-1/the-script-element/module/type.html

**Comment by ss77995ss** [comment]
Hi may I try this one?

**Comment by CYBAI** [comment]
Yes, please feel free to ask any questions if it's unclear 🙏

**Comment by CYBAI** [comment]
> Therefore, I can use `to_ascii_lowercase()` to check

yes, and I also noticed that, in Step 8 of https://html.spec.whatwg.org/multipage/#prepare-a-script, it says

> Otherwise, if el has a [type](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-type) attribute, then let the script block's type string be the value of that attribute with [leading and trailing ASCII whitespace stripped](https://infra.spec.whatwg.org/#strip-leading-and-trailing-ascii-whitespace).

so I wonder you can reuse 👇 as a variable so that it will trim the leading and trailing ASCII whitespaces:

https://github.com/servo/servo/blob/66dd68a210566f3604195ea306ebc350aa3984d5/components/script/dom/htmlscriptelement.rs#L1194

**Comment by ss77995ss** [comment]
Oh OK! Thanks! I did not consider the whitespaces situation.

**Comment by CYBAI** [comment]
I just added the whitespaces case into the issue description 🙏

**Comment by ss77995ss** [comment]
@CYBAI I created a PR for this issue. Please have a look.

It looks like the whitespaces cases are already pass. Do we still need to handle them?
