### ISSUE TITLE
Sanitize web fonts

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#3030]
For security purposes we should do that. (Or long-term rewrite the parser in Rust.)

**Comment by kmcallister** [comment]
I can do the OTS bindings.

**Comment by kmcallister** [comment]
[The bindings](https://github.com/servo/fontsan) work, now I'll wire it up to Servo.

**Comment by frewsxcv** [comment]
Although I haven't tested it, someone wrote an OpenType parser in Rust

https://github.com/bodoni/opentype

**Comment by jdm** [comment]
Latest attempt in #7634.

**Comment by talklittle** [comment]
I'd like to try this issue. My attempt will be essentially to rebase #7634 to current master and ensure it builds for Android, since it appears that was the blocker last time.

I noticed the webfont loading became async since that previous PR, so I'll do the font sanitizing on that worker thread.

**Comment by jdm** [comment]
@talklittle Seems like it's worth a shot!
