### ISSUE TITLE
Add more derivables in Bindings.conf

### ISSUE THREAD

**Issue by sagudev** [servo/servo#30356]
Something like:
```
'GPUFeatureName': {
    'addDerive': ['Eq', 'Hash'],
},
```

**Comment by sagudev** [comment]
This is hard because Bindings.conf is only for interfaces meaning that we either need to interpret conf differently or do it differently. Small experimentation in https://github.com/sagudev/servo/commit/5d7f5e70d394e1a7c7d1de386ddfbfe78c8e6875

**Comment by jdm** [comment]
I have a branch that implements this.
