### ISSUE TITLE
Inline elements with <br> have bigger width than expected

### ISSUE THREAD

**Issue by mrego** [servo/servo#30350]
See this simple example:
```html
<div style="border: solid thick magenta; float: left;">Just some text <br> in two lines</div>
<div>floatting</div>
```

![Screenshot where the floated element is too wide](https://github.com/servo/servo/assets/11602/931ec8dd-9d34-4aa6-829a-07cbc8b3e54d)

The width of the floated element should be smaller, there are some extra space that is not needed.

**Comment by mrobinson** [comment]
I'm happy to look at this one.
