### ISSUE TITLE
Nightly not display right chinese fonts

### ISSUE THREAD

**Issue by cnmade** [servo/servo#30431]
[](url![Snipaste_2023-09-26_16-53-14](https://github.com/servo/servo/assets/278153/87606bb5-e7d7-4f8d-9714-1995b4883297)

Visit chinese website, like https://www.baidu.com

it display none right chinese fonts

**Comment by mrobinson** [comment]
I believe this is the same issue as #25883. We hope to fix this soon.

**Comment by cnmade** [comment]
ok, i will try when you finish that fixed
