### ISSUE TITLE
Released servo_arc 0.3.0 crate not published on github

### ISSUE THREAD

**Issue by kalev** [servo/servo#30455]
I'm looking at https://crates.io/crates/servo_arc where the latest release is 0.3.0 and can't find matching source in the github repo. In https://github.com/servo/servo/blob/master/components/servo_arc/Cargo.toml the latest version is 0.2.0. Any ideas what's going on?

Additionally, servo_arc-0.3.0.crate contains a hidden .cargo_vcs_info.json with the following contents:

```
{
  "git": {
    "sha1": "518560b4e06ad9aa1a407d9f27293a2d20dcd804"
  },
  "path_in_vcs": "servo/components/servo_arc"
}
```

The referenced git commit https://github.com/servo/servo/commit/518560b4e06ad9aa1a407d9f27293a2d20dcd804 doesn't seem to be in the published git repo.

**Comment by atouchet** [comment]
According to https://github.com/servo/servo/issues/29842#issuecomment-1601672003 the code is from mozilla-central.

**Comment by mrobinson** [comment]
It's possible that at some point servo_arc was published from the Gecko upstream. In any case it the latest version of it can be found at http://github.com/servo/stylo. We haven't released new cargo packages yet, but hopefully we can soon. This will likely happen after we've synchronized with upstream again.
