### ISSUE TITLE
Running servo main branch kills X on arch linux

### ISSUE THREAD

**Issue by iankronquist** [servo/servo#3062]
Running arch linux, checked out the servo main branch. Using i3 window manager, and nouveau graphics drivers on a late 2013 macbook pro retina running on the discrete graphics card . (I'm not sure what specs will be useful.)
Steps to reproduce:
Compile servo, commit f2b2f484
Run servo and visit http://google.com

``` sh
$ ./build/servo http://google.com
```

The page successfully loads. Then X is unresponsive to keyboard input, but the mouse still moves.
After waiting a few seconds, X dies.
Running `startx` again starts x, but it's stuck in a failed state.
I could find no logs related to the incident in `~/.local/share/xorg/`.
How do I debug this problem? If I can  help contribute, that would be awesome.

**Comment by dralley** [comment]
This should probably be closed as outdated.
