### ISSUE TITLE
build failed!

### ISSUE THREAD

**Issue by andrewpedia** [servo/servo#30695]
error: failed to run custom build command for `ring v0.17.5`

Caused by:
  process didn't exit successfully: `/code/servo/target/release/build/ring-2c8a0bf268092603/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
  cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_5_
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("clang")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-unknown-linux-gnu" "-I" "include" "-I" "/code/servo/target/release/build/ring-28cf487e95ca223e/out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-pedantic" "-Wall" "-Wextra" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-g3" "-DNDEBUG" "-o" "/code/servo/target/release/build/ring-28cf487e95ca223e/out/crypto/curve25519/curve25519.o" "-c" "crypto/curve25519/curve25519.c"

  --- stderr

  error occurred: Failed to find tool. Is `clang` installed?

**Comment by mrobinson** [comment]
Is `clang` installed on your system?

**Comment by andrewpedia** [comment]
which version of clang should work ?
clang-13 just report many errors:
  --- stderr
  /usr/lib/llvm-13/lib/clang/13.0.1/include/emmintrin.h:2374:19: error: use of undeclared identifier '__builtin_ia32_pmaxsw128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/emmintrin.h:2394:19: error: use of undeclared identifier '__builtin_ia32_pmaxub128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/emmintrin.h:2414:19: error: use of undeclared identifier '__builtin_ia32_pminsw128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/emmintrin.h:2434:19: error: use of undeclared identifier '__builtin_ia32_pminub128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/tmmintrin.h:52:21: error: use of undeclared identifier '__builtin_ia32_pabsb128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/tmmintrin.h:88:21: error: use of undeclared identifier '__builtin_ia32_pabsw128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/tmmintrin.h:124:21: error: use of undeclared identifier '__builtin_ia32_pabsd128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/smmintrin.h:667:20: error: use of undeclared identifier '__builtin_ia32_pminsb128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/smmintrin.h:686:20: error: use of undeclared identifier '__builtin_ia32_pmaxsb128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/smmintrin.h:705:20: error: use of undeclared identifier '__builtin_ia32_pminuw128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/smmintrin.h:724:20: error: use of undeclared identifier '__builtin_ia32_pmaxuw128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/smmintrin.h:743:20: error: use of undeclared identifier '__builtin_ia32_pminsd128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/smmintrin.h:762:20: error: use of undeclared identifier '__builtin_ia32_pmaxsd128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/smmintrin.h:781:20: error: use of undeclared identifier '__builtin_ia32_pminud128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/smmintrin.h:800:20: error: use of undeclared identifier '__builtin_ia32_pmaxud128'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/avx2intrin.h:29:21: error: use of undeclared identifier '__builtin_ia32_pabsb256'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/avx2intrin.h:35:21: error: use of undeclared identifier '__builtin_ia32_pabsw256'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/avx2intrin.h:41:21: error: use of undeclared identifier '__builtin_ia32_pabsd256'
  /usr/lib/llvm-13/lib/clang/13.0.1/include/avx2intrin.h:256:19: error: use of undeclared identifier '__builtin_ia32_pmaxsb256'

**Comment by andrewpedia** [comment]
clang-14 works!
