### ISSUE TITLE
Error Servo build with rust 1.65.0 version

### ISSUE THREAD

**Issue by hjshin21** [servo/servo#30725]
Hi all,

I'm looking for a version of Servo that is compatible with Rust 1.65.0.

I'm currently using the version with the commit: b1341f77f5d356906377ef401dfa1100e82d6f14, but I'm encountering an error.

![image](https://github.com/servo/servo/assets/104689024/bef186e6-3051-457d-8df4-dcd256d0c29d)

How can I resolve this issue?

Thank you.

**Comment by mrobinson** [comment]
Servo is currently incompatible with non-nightly rust. It simply will not compile until we depend on stable rust. There is not version of Servo that will compile on stable rust right now. We'd like to do this, but it requires adapting Servo to no longer use nightly-only features.
