### ISSUE TITLE
Nightly stopped updating on November 3rd

### ISSUE THREAD

**Issue by kibwen** [servo/servo#30722]
https://servo.org/download/ hasn't been updated since Nov 3rd.

![Servo](https://github.com/servo/servo/assets/150562199/df28f141-1c1b-4923-8e9e-0bbc97b4117b)

**Comment by kibwen** [comment]
https://github.com/servo/servo/actions/runs/6832345256/job/18582936278

the "upload nightly" step got error?

**Comment by sagudev** [comment]
Most suspicious are b268936308177c5cbe4d58d26f7aa1a87b2841c8 and https://github.com/servo/servo/commit/fd5f04c18ee0c78ddaccf95caae2912329e8fab0

**Comment by sagudev** [comment]
But it would be nice if we could solve the issue directly: `AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'` that might be related to https://github.com/pyca/cryptography/issues/7959

**Comment by kibwen** [comment]
not directly related to [b268936](https://github.com/servo/servo/commit/b268936308177c5cbe4d58d26f7aa1a87b2841c8)
