### ISSUE TITLE
Add `T-linux-wpt` label

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#30749]
To run WPT both in 2013 and 2020.

Right now I either need to
 - Use `T-full`, which tests all linux, windows and mac, and includes unit tests. Sometimes I don't care about that.
 - Use both `T-linux-wpt-2013` and `T-linux-wpt-2020`, which triggers 2 different actions, and compiles twice.

**Comment by sagudev** [comment]
https://github.com/servo/servo/pull/30694 already has logic for it, only GH label is missing.

**Comment by mrobinson** [comment]
> To run WPT both in 2013 and 2020.
>     * Use both `T-linux-wpt-2013` and `T-linux-wpt-2020`, which triggers 2 different actions, and compiles twice.

This doesn't actually compile twice depending on timing of the GitHub Actions. I've noticed that most of the time, this only does one build. I think we can make this work even more consistently with https://docs.github.com/en/actions/using-jobs/using-concurrency. This should allow us to make sure that labels applied at the same time are combined into the same job.

**Comment by mrobinson** [comment]
The benefit of using concurrency is that it should allow any combination of jobs without having to add a bunch of extra labels, if we can get it working properly. See #30756.

**Comment by sagudev** [comment]
Merging of wpt runs was done in https://github.com/servo/servo/pull/31347. Also try-parser already supports `linux-wpt` and `wpt` so it's just matter of adding new tags to github if we really needed to: https://github.com/servo/servo/blob/06aeeeb1f3574706e6992426063306a3f10716d8/python/servo/try_parser.py#L84-L85
