### ISSUE TITLE
`./mach build` broken on NixOS after moving to `crown`

### ISSUE THREAD

**Issue by mukilan** [servo/servo#30813]
` ./mach build` seem broken on NixOS after #30508 landed
```
~/dev/servo ‹master› 
$ ./mach build -r
NOTE: Entering nix-shell etc/shell.nix
error: could not execute process `crown -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
Failed in 0:00:00
```

Since NixOS doesn't execute bootstrap commands like other linux distros, crown is not installed by mach.
Adding installation step to `etc/shell.nix` under shellHook also fails because nix considers the path to be impure
i.e 
in etc/shell.nix
```
  shellHook = ''
    CARGO_BUILD_RUSTC=rustc cargo install --path support/crown
  '';
```

results in 
```
  = note: impure path `/home/mukilan/dev/servo/target/release/deps/crown-3d1116308c10f300' used in link
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

I suppose we'll need to import crown as a derivation somehow. Note: installing crown manually using the same command above from inside the nix-shell environment does work and allows subsequent `./mach build` to also work.

**Comment by delan** [comment]
This works but is probably not ideal:

```nix
shellHook = ''
  NIX_ENFORCE_PURITY=0 CARGO_BUILD_RUSTC=rustc cargo install --path support/crown
'';
```

This doesn’t work yet, because crown is part of the main workspace, so its Cargo.lock is outside the src directory, so buildRustPackage can’t find it:

```nix
buildInputs = [
  (rustPlatform.buildRustPackage rec {
    pname = "crown";
    version = "0.1.0";
    src = ../support/crown;
    cargoHash = lib.fakeHash;
  })
];
```

Excluding crown from the main workspace is not really an option, because mach test-unit needs to be able to run tests against the -p(ackage). We also don’t want to make src just pull in the whole repo, because that will waste space in the nix store and cause unnecessary cache misses.

I think we will need to make src point to the whole repo, with some aggressive [filtering](https://discourse.nixos.org/t/filtering-source-trees-with-nix-and-nixpkgs/19148) to only include Cargo.lock and support/crown.

**Comment by Loirooriol** [comment]
I'm getting the same problem in Ubuntu 23.04

**Comment by sagudev** [comment]
> I'm getting the same problem in Ubuntu 23.04

Maybe you need to run `./mach bootstrap` to rebuild crown for new rust version.

**Comment by Loirooriol** [comment]
Already tried, it fails

```
$ ./mach bootstrap
WARNING: unsupported version of Ubuntu: 23.04
Traceback (most recent call last):
  File "/home/oriol/src/servo/./mach", line 46, in <module>
    main(sys.argv)
  File "/home/oriol/src/servo/./mach", line 25, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oriol/src/servo/python/mach_bootstrap.py", line 210, in bootstrap_command_only
    servo.platform.get().bootstrap('-f' in sys.argv or '--force' in sys.argv)
  File "/home/oriol/src/servo/python/servo/platform/base.py", line 97, in bootstrap
    installed_something |= self.install_crown(force)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oriol/src/servo/python/servo/platform/base.py", line 119, in install_crown
    raise EnvironmentError("Installation of crown failed.")
OSError: Installation of crown failed.
```

Looking at the source code, it tries to install crown with `cargo install --path support/crown`, which fails with the same error as this issue

```
$ cargo install --path support/crown
error: could not execute process `crown -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
```

**Comment by sagudev** [comment]
When running cargo install for crown you need to override RUSTC from .cargo/config to rustc so `RUSTC=rustc cargo install --path support/crown` should work.

**Comment by Loirooriol** [comment]
Oh thanks, but I managed to make it work by reinstalling: `rustup self uninstall`, `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`, `./mach bootstrap`, `./mach build -r`
