### ISSUE TITLE
Windows try jobs fail when installing crown on older pull requests

### ISSUE THREAD

**Issue by delan** [servo/servo#30828]
On pull requests older than #30508, your Windows Build jobs may fail with:

```
error: `D:\a\servo\servo\support\crown` is not a directory. --path must point to a directory containing a Cargo.toml file.
```

You can work around this by merging from or rebasing onto main.

> ⚠️ Try run ([#7112225827](https://github.com/servo/servo/actions/runs/7112225827)) failed.
> _Originally posted by @github-actions[bot] in https://github.com/servo/servo/issues/30767#issuecomment-1842520903_

(cc @sagudev)

**Comment by sagudev** [comment]
When bors was doing try builds it did merge automatically, so this would be non problem with old try architecture. Given how trivial is fix and I do not expect to have a lot PR with this problems in the future, so this is WONTFIX.

**Comment by delan** [comment]
No worries! At least we have it documented here, in case someone else runs into it.
