### ISSUE TITLE
Failed to execute compile

### ISSUE THREAD

**Issue by Sebbito** [servo/servo#30850]
mach does not start compiling the project. After running `./mach check` it exits with the following error:
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/user/.cargo/bin/sccache crown - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 2)
  --- stderr
  sccache: error: failed to execute compile
  sccache: caused by: Compiler not supported: "error: Unrecognized option: \'E\'\n\n"
```

Steps i took before trying to execute mach:
1. I already hat the rust tool chain installed and thus didn't download and execute the rustup script. (The required rust tool chain was installed once i navigated into the directory as you would expect)
2. I ran `sudo dnf install python3 python3-pip python3-devel` since I'm on Fedora 39
3. I ran `./mach bootstrap` which installed all needed programs without error.

- I tried running the script with all shells available (sh, bash and fish) though it resulted in the same error every time.
- I checked all shells for the programs required (sccache, rustc, cargo, python). All of them report the same versions

```bash
$ cargo -V && rustc -V && sccache -V && python --version
cargo 1.74.1 (ecb9851af 2023-10-18)
rustc 1.74.1 (a28077b28 2023-12-04)
sccache 0.7.4
Python 3.12.0
```

Any other suggestions?

**Comment by Loirooriol** [comment]
I can reproduce the problem if I enable sccache. So try disabling it.

**Comment by Loirooriol** [comment]
https://github.com/mozilla/sccache/issues/1000

**Comment by sagudev** [comment]
Sccache currently does not support other rustc drivers other than clippy (we use crown), there already [is PR for it in sccache](https://github.com/mozilla/sccache/pull/1897). In the mean time I recommend setting `CCACHE` env var to `sccache`, which should be help with caching of mozjs (which is the slowest anyway).

**Comment by Sebbito** [comment]
Yes removing sccache from my `~/.cargo/config.toml` did fix this issue so this can be closed. Thanks a lot :heart:
