### ISSUE TITLE
./mach build --release No module named pip . But in the virtualenv: pip 22.02 is installed

### ISSUE THREAD

**Issue by raphael10-collab** [servo/servo#30885]
(servo_venv) raphy@raohy:~/servo$ ./mach build --release
    "/home/raphy/servo/python/_venv3.10/bin/python" "-m" "pip" "install" "-I" "-r" "/home/raphy/servo/python/requirements.txt" failed with error code 1:
    Output:
    Error:
    /home/raphy/servo/python/_venv3.10/bin/python: No module named pip
    (servo_venv) raphy@raohy:~/servo$ 
    (servo_venv) raphy@raohy:~/servo$ pip -V
    pip 22.0.2 from /home/raphy/servo_venv/lib/python3.10/site-packages/pip (python 3.10)

OS: Ubuntu 22.04

**Comment by fedgrant** [comment]
How did you solve this?

**Comment by pgerber** [comment]
On Debian this helped:

```
sudo apt install python3-pip python3-venv
rm -f /home/user/src/servo/python/_venv3.11
./mach ...
```
