### ISSUE TITLE
could not execute process `crown -vV`  - Ubuntu 22.04

### ISSUE THREAD

**Issue by raphael10-collab** [servo/servo#30886]
(servo) raphy@raohy:~/servo$ source "$HOME/.cargo/env"
    (servo) raphy@raohy:~/servo$ ./mach build --release
    info: syncing channel updates for 'nightly-2023-12-18-x86_64-unknown-linux-gnu'
    info: latest update on 2023-12-18, rust version 1.76.0-nightly (6a6287132 2023-12-17)
    info: downloading component 'cargo'
    info: downloading component 'llvm-tools'
    info: downloading component 'rust-docs'
    info: downloading component 'rust-std'
    info: downloading component 'rustc'
    info: downloading component 'rustc-dev'
    info: downloading component 'rustfmt'
    info: installing component 'cargo'
    info: installing component 'llvm-tools'
    info: installing component 'rust-docs'
    info: installing component 'rust-std'
    info: installing component 'rustc'
    info: installing component 'rustc-dev'
    info: installing component 'rustfmt'
    error: could not execute process `crown -vV` (never executed)
    
    Caused by:
      Permission denied (os error 13)
    Failed in 0:00:20
    [Warning] Could not generate notification: No module named 'dbus'

I tried also to execute `./mach bootstrap` but got also "Installation of taplo failed"  : 

    (servo) raphy@raohy:~/servo$ ./mach bootstrap
    Installing missing dependencies...
    [sudo] password for raphy: 
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    build-essential is already the newest version (12.9ubuntu3).
    g++ is already the newest version (4:11.2.0-1ubuntu1).
    liblzma-dev is already the newest version (5.2.5-2ubuntu1).
    liblzma-dev set to manually installed.
    libvulkan1 is already the newest version (1.3.204.1-2).
    libvulkan1 set to manually installed.
    libxcb-render0-dev is already the newest version (1.14-3ubuntu3).
    libxcb-render0-dev set to manually installed.
    libxcb-shape0-dev is already the newest version (1.14-3ubuntu3).
    libxcb-xfixes0-dev is already the newest version (1.14-3ubuntu3).
    libxmu6 is already the newest version (2:1.1.3-3).
    libxmu6 set to manually installed.
    m4 is already the newest version (1.4.18-5ubuntu2).
    m4 set to manually installed.
    ccache is already the newest version (4.5.1-1).
    gperf is already the newest version (3.1-1build1).
    cmake is already the newest version (3.22.1-1ubuntu1.22.04.1).
    curl is already the newest version (7.81.0-1ubuntu1.15).
    git is already the newest version (1:2.34.1-1ubuntu1.10).
    libdbus-1-dev is already the newest version (1.12.20-2ubuntu4.1).
    libdbus-1-dev set to manually installed.
    libegl1-mesa-dev is already the newest version (23.0.4-0ubuntu1~22.04.1).
    libegl1-mesa-dev set to manually installed.
    libfreetype6-dev is already the newest version (2.11.1+dfsg-1ubuntu0.2).
    libfreetype6-dev set to manually installed.
    libgl1-mesa-dri is already the newest version (23.0.4-0ubuntu1~22.04.1).
    libgl1-mesa-dri set to manually installed.
    libglib2.0-dev is already the newest version (2.72.4-0ubuntu2.2).
    libglib2.0-dev set to manually installed.
    libgstreamer-plugins-base1.0-dev is already the newest version (1.20.1-1ubuntu0.1).
    libgstreamer1.0-dev is already the newest version (1.20.3-0ubuntu1).
    libharfbuzz-dev is already the newest version (2.7.4-1ubuntu3.1).
    libharfbuzz-dev set to manually installed.
    libunwind-dev is already the newest version (1.3.2-2build2.1).
    libunwind-dev set to manually installed.
    libx11-dev is already the newest version (2:1.7.5-1ubuntu0.3).
    libx11-dev set to manually installed.
    libgstreamer-plugins-bad1.0-dev is already the newest version (1.20.3-0ubuntu1.1).
    The following additional packages will be installed:
      libdmx-dev libdmx1 libfontenc-dev libfs-dev libfs6 libxaw7-dev libxcvt-dev libxfont-dev libxkbfile-dev libxmu-headers libxmuu-dev libxpm-dev libxres-dev libxv-dev libxvmc-dev libxxf86dga-dev libxxf86vm-dev llvm llvm-runtime xserver-xorg-dev
    Suggested packages:
      libxaw-doc
    The following NEW packages will be installed:
      clang libdmx-dev libdmx1 libfontenc-dev libfs-dev libfs6 libgles2-mesa-dev libxaw7-dev libxcvt-dev libxfont-dev libxkbfile-dev libxmu-dev libxmu-headers libxmuu-dev libxpm-dev libxres-dev libxv-dev libxvmc-dev libxxf86dga-dev libxxf86vm-dev llvm llvm-dev llvm-runtime xorg-dev xserver-xorg-dev
    0 upgraded, 25 newly installed, 0 to remove and 2 not upgraded.
    Need to get 1.110 kB of archives.
    After this operation, 5.214 kB of additional disk space will be used.
    Do you want to continue? [Y/n] Y
    Get:1 http://it.archive.ubuntu.com/ubuntu jammy/universe amd64 clang amd64 1:14.0-55~exp2 [3.558 B]
    Get:2 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libdmx1 amd64 1:1.1.4-2build2 [9.372 B]
    Get:3 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libdmx-dev amd64 1:1.1.4-2build2 [33,5 kB]
    Get:4 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libfontenc-dev amd64 1:1.1.4-1build3 [15,4 kB]
    Get:5 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libfs6 amd64 2:1.0.8-1build2 [22,9 kB]
    Get:6 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libfs-dev amd64 2:1.0.8-1build2 [29,1 kB]
    Get:7 http://it.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgles2-mesa-dev amd64 23.0.4-0ubuntu1~22.04.1 [6.504 B]
    Get:8 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxmu-headers all 2:1.1.3-3 [54,1 kB]
    Get:9 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxmu-dev amd64 2:1.1.3-3 [54,6 kB]
    Get:10 http://it.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libxpm-dev amd64 1:3.5.12-1ubuntu0.22.04.2 [90,7 kB]
    Get:11 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxaw7-dev amd64 2:1.0.14-1 [253 kB]
    Get:12 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxcvt-dev amd64 0.1.1-3 [3.242 B]
    Get:13 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxfont-dev amd64 1:2.0.5-1build1 [128 kB]
    Get:14 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxkbfile-dev amd64 1:1.1.0-1build3 [85,0 kB]
    Get:15 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxmuu-dev amd64 2:1.1.3-3 [7.926 B]
    Get:16 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxres-dev amd64 2:1.2.1-1 [8.538 B]
    Get:17 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxv-dev amd64 2:1.0.11-1build2 [33,4 kB]
    Get:18 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxvmc-dev amd64 2:1.0.12-2build2 [24,2 kB]
    Get:19 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga-dev amd64 2:1.1.5-0ubuntu3 [16,5 kB]
    Get:20 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86vm-dev amd64 1:1.1.4-1build3 [13,9 kB]
    Get:21 http://it.archive.ubuntu.com/ubuntu jammy/universe amd64 llvm-runtime amd64 1:14.0-55~exp2 [3.204 B]
    Get:22 http://it.archive.ubuntu.com/ubuntu jammy/universe amd64 llvm amd64 1:14.0-55~exp2 [3.758 B]
    Get:23 http://it.archive.ubuntu.com/ubuntu jammy/universe amd64 llvm-dev amd64 1:14.0-55~exp2 [1.656 B]
    Get:24 http://it.archive.ubuntu.com/ubuntu jammy-updates/main amd64 xserver-xorg-dev amd64 2:21.1.4-2ubuntu1.7~22.04.5 [203 kB]
    Get:25 http://it.archive.ubuntu.com/ubuntu jammy/main amd64 xorg-dev all 1:7.7+23ubuntu2 [4.262 B]
    Fetched 1.110 kB in 0s (2.860 kB/s)   
    Selecting previously unselected package clang.
    (Reading database ... 273252 files and directories currently installed.)
    Preparing to unpack .../00-clang_1%3a14.0-55~exp2_amd64.deb ...
    Unpacking clang (1:14.0-55~exp2) ...
    Selecting previously unselected package libdmx1:amd64.
    Preparing to unpack .../01-libdmx1_1%3a1.1.4-2build2_amd64.deb ...
    Unpacking libdmx1:amd64 (1:1.1.4-2build2) ...
    Selecting previously unselected package libdmx-dev:amd64.
    Preparing to unpack .../02-libdmx-dev_1%3a1.1.4-2build2_amd64.deb ...
    Unpacking libdmx-dev:amd64 (1:1.1.4-2build2) ...
    Selecting previously unselected package libfontenc-dev:amd64.
    Preparing to unpack .../03-libfontenc-dev_1%3a1.1.4-1build3_amd64.deb ...
    Unpacking libfontenc-dev:amd64 (1:1.1.4-1build3) ...
    Selecting previously unselected package libfs6:amd64.
    Preparing to unpack .../04-libfs6_2%3a1.0.8-1build2_amd64.deb ...
    Unpacking libfs6:amd64 (2:1.0.8-1build2) ...
    Selecting previously unselected package libfs-dev:amd64.
    Preparing to unpack .../05-libfs-dev_2%3a1.0.8-1build2_amd64.deb ...
    Unpacking libfs-dev:amd64 (2:1.0.8-1build2) ...
    Selecting previously unselected package libgles2-mesa-dev:amd64.
    Preparing to unpack .../06-libgles2-mesa-dev_23.0.4-0ubuntu1~22.04.1_amd64.deb ...
    Unpacking libgles2-mesa-dev:amd64 (23.0.4-0ubuntu1~22.04.1) ...
    Selecting previously unselected package libxmu-headers.
    Preparing to unpack .../07-libxmu-headers_2%3a1.1.3-3_all.deb ...
    Unpacking libxmu-headers (2:1.1.3-3) ...
    Selecting previously unselected package libxmu-dev:amd64.
    Preparing to unpack .../08-libxmu-dev_2%3a1.1.3-3_amd64.deb ...
    Unpacking libxmu-dev:amd64 (2:1.1.3-3) ...
    Selecting previously unselected package libxpm-dev:amd64.
    Preparing to unpack .../09-libxpm-dev_1%3a3.5.12-1ubuntu0.22.04.2_amd64.deb ...
    Unpacking libxpm-dev:amd64 (1:3.5.12-1ubuntu0.22.04.2) ...
    Selecting previously unselected package libxaw7-dev:amd64.
    Preparing to unpack .../10-libxaw7-dev_2%3a1.0.14-1_amd64.deb ...
    Unpacking libxaw7-dev:amd64 (2:1.0.14-1) ...
    Selecting previously unselected package libxcvt-dev:amd64.
    Preparing to unpack .../11-libxcvt-dev_0.1.1-3_amd64.deb ...
    Unpacking libxcvt-dev:amd64 (0.1.1-3) ...
    Selecting previously unselected package libxfont-dev.
    Preparing to unpack .../12-libxfont-dev_1%3a2.0.5-1build1_amd64.deb ...
    Unpacking libxfont-dev (1:2.0.5-1build1) ...
    Selecting previously unselected package libxkbfile-dev:amd64.
    Preparing to unpack .../13-libxkbfile-dev_1%3a1.1.0-1build3_amd64.deb ...
    Unpacking libxkbfile-dev:amd64 (1:1.1.0-1build3) ...
    Selecting previously unselected package libxmuu-dev:amd64.
    Preparing to unpack .../14-libxmuu-dev_2%3a1.1.3-3_amd64.deb ...
    Unpacking libxmuu-dev:amd64 (2:1.1.3-3) ...
    Selecting previously unselected package libxres-dev:amd64.
    Preparing to unpack .../15-libxres-dev_2%3a1.2.1-1_amd64.deb ...
    Unpacking libxres-dev:amd64 (2:1.2.1-1) ...
    Selecting previously unselected package libxv-dev:amd64.
    Preparing to unpack .../16-libxv-dev_2%3a1.0.11-1build2_amd64.deb ...
    Unpacking libxv-dev:amd64 (2:1.0.11-1build2) ...
    Selecting previously unselected package libxvmc-dev:amd64.
    Preparing to unpack .../17-libxvmc-dev_2%3a1.0.12-2build2_amd64.deb ...
    Unpacking libxvmc-dev:amd64 (2:1.0.12-2build2) ...
    Selecting previously unselected package libxxf86dga-dev:amd64.
    Preparing to unpack .../18-libxxf86dga-dev_2%3a1.1.5-0ubuntu3_amd64.deb ...
    Unpacking libxxf86dga-dev:amd64 (2:1.1.5-0ubuntu3) ...
    Selecting previously unselected package libxxf86vm-dev:amd64.
    Preparing to unpack .../19-libxxf86vm-dev_1%3a1.1.4-1build3_amd64.deb ...
    Unpacking libxxf86vm-dev:amd64 (1:1.1.4-1build3) ...
    Selecting previously unselected package llvm-runtime:amd64.
    Preparing to unpack .../20-llvm-runtime_1%3a14.0-55~exp2_amd64.deb ...
    Unpacking llvm-runtime:amd64 (1:14.0-55~exp2) ...
    Selecting previously unselected package llvm.
    Preparing to unpack .../21-llvm_1%3a14.0-55~exp2_amd64.deb ...
    Unpacking llvm (1:14.0-55~exp2) ...
    Selecting previously unselected package llvm-dev.
    Preparing to unpack .../22-llvm-dev_1%3a14.0-55~exp2_amd64.deb ...
    Unpacking llvm-dev (1:14.0-55~exp2) ...
    Selecting previously unselected package xserver-xorg-dev.
    Preparing to unpack .../23-xserver-xorg-dev_2%3a21.1.4-2ubuntu1.7~22.04.5_amd64.deb ...
    Unpacking xserver-xorg-dev (2:21.1.4-2ubuntu1.7~22.04.5) ...
    Selecting previously unselected package xorg-dev.
    Preparing to unpack .../24-xorg-dev_1%3a7.7+23ubuntu2_all.deb ...
    Unpacking xorg-dev (1:7.7+23ubuntu2) ...
    Setting up libgles2-mesa-dev:amd64 (23.0.4-0ubuntu1~22.04.1) ...
    Setting up libxmu-headers (2:1.1.3-3) ...
    Setting up libxcvt-dev:amd64 (0.1.1-3) ...
    Setting up libxxf86dga-dev:amd64 (2:1.1.5-0ubuntu3) ...
    Setting up libxxf86vm-dev:amd64 (1:1.1.4-1build3) ...
    Setting up libfontenc-dev:amd64 (1:1.1.4-1build3) ...
    Setting up libxmu-dev:amd64 (2:1.1.3-3) ...
    Setting up libxv-dev:amd64 (2:1.0.11-1build2) ...
    Setting up libdmx1:amd64 (1:1.1.4-2build2) ...
    Setting up libdmx-dev:amd64 (1:1.1.4-2build2) ...
    Setting up clang (1:14.0-55~exp2) ...
    Setting up llvm-runtime:amd64 (1:14.0-55~exp2) ...
    Setting up libxpm-dev:amd64 (1:3.5.12-1ubuntu0.22.04.2) ...
    Setting up llvm (1:14.0-55~exp2) ...
    Setting up libfs6:amd64 (2:1.0.8-1build2) ...
    Setting up libxaw7-dev:amd64 (2:1.0.14-1) ...
    Setting up libxres-dev:amd64 (2:1.2.1-1) ...
    Setting up libxmuu-dev:amd64 (2:1.1.3-3) ...
    Setting up libxvmc-dev:amd64 (2:1.0.12-2build2) ...
    Setting up libxkbfile-dev:amd64 (1:1.1.0-1build3) ...
    Setting up llvm-dev (1:14.0-55~exp2) ...
    Setting up libxfont-dev (1:2.0.5-1build1) ...
    Setting up libfs-dev:amd64 (2:1.0.8-1build2) ...
    Setting up xserver-xorg-dev (2:21.1.4-2ubuntu1.7~22.04.5) ...
    Setting up xorg-dev (1:7.7+23ubuntu2) ...
    Processing triggers for libc-bin (2.35-0ubuntu3.5) ...
    Processing triggers for man-db (2.10.2-1) ...
    Traceback (most recent call last):
      File "/home/raphy/servo/./mach", line 46, in <module>
        main(sys.argv)
      File "/home/raphy/servo/./mach", line 25, in main
        sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
      File "/home/raphy/servo/python/mach_bootstrap.py", line 210, in bootstrap_command_only
        servo.platform.get().bootstrap('-f' in sys.argv or '--force' in sys.argv)
      File "/home/raphy/servo/python/servo/platform/base.py", line 96, in bootstrap
        installed_something |= self.install_taplo(force)
      File "/home/raphy/servo/python/servo/platform/base.py", line 107, in install_taplo
        raise EnvironmentError("Installation of taplo failed.")
    OSError: Installation of taplo failed.
    (servo) raphy@raohy:~/servo$ 
    (servo) raphy@raohy:~/servo$ 
    (servo) raphy@raohy:~/servo$ ./mach build --release
    error: could not execute process `crown -vV` (never executed)
    
    Caused by:
      Permission denied (os error 13)
    Failed in 0:00:00
    [Warning] Could not generate notification: No module named 'dbus'

O.S. : Ubuntu 22.04

**Comment by ThatOneCalculator** [comment]
What was the fix?

**Comment by JanMH** [comment]
Running `./mach bootstrap` resolved the issue for me
