### ISSUE TITLE
WebIDL impl: remove unsafe JSObject from return value of Document::NamedGetter

### ISSUE THREAD

**Issue by gterzian** [servo/servo#30890]
Part of https://github.com/servo/servo/issues/30862

Same as https://github.com/servo/servo/issues/30889

https://github.com/servo/servo/blob/8bbcf0abafc22cd840cd03f36b5b3b7d2d815493/components/script/dom/document.rs#L4829

Should return an enum of specific types. See https://html.spec.whatwg.org/multipage/dom.html#dom-tree-accessors%3Adom-document-nameditem-filter

**Comment by eerii** [comment]
I'd like to try to tackle this if that's ok!

**Comment by gterzian** [comment]
Great! There have been quite a few related PR's merged in recently, and they can server as a guide(although this one is a bit different). See https://github.com/servo/servo/pulls?q=is%3Apr+is%3Aclosed+WebIDL

Let me know if you have other questions. For how to create an enum-like structure, see for example https://github.com/servo/servo/blob/5febb3031337f7ee989fe3be80a4f3fdf0bf933c/components/script/dom/webidls/BluetoothUUID.webidl#L19

**Comment by eerii** [comment]
Thank you so much for the references! I'll get to it

**Comment by eerii** [comment]
I am sorry for the delay, I was trying to understand how WebIDL worked so I took other projects related to codegen first. Hopefully the pr does the necessary modifications, but I would appreciate any corrections since this is my first time modifying WebIDL.
