### ISSUE TITLE
WebGPU: fail request for adapter when not available. 

### ISSUE THREAD

**Issue by gterzian** [servo/servo#30895]
Depends on https://github.com/servo/servo/pull/30888

See the changes at https://github.com/servo/servo/pull/30888/files/4bec9ef169f51c91f616b854e231484bbd983366#diff-95aa2eb890fe794918afdadfb6a89e026ec80222ceb8e5a21768d528e9ce036cR2066

This will simply leave the async handler in script waiting forever, instead we should send a message back and properly handle the case where WebGPU is not available(re "properly", look at the [spec](https://gpuweb.github.io/gpuweb/#dom-gpu-requestadapter) .

See https://github.com/servo/servo/blob/8bbcf0abafc22cd840cd03f36b5b3b7d2d815493/components/script/dom/gpu.rs#L108

**Comment by gterzian** [comment]
cc @lucasMontenegro

**Comment by Taym95** [comment]
@gterzian @lucasMontenegro  can I pick this one?

**Comment by lucasMontenegro** [comment]
Hello @gterzian and @Taym95. I'm sorry I somehow missed this thread. Thanks to your comment it finally came to my attention @Taym95 .

I'm unable to contribute now since I just installed a new OS that I'm unfamiliar with. Maybe tomorrow I'll be ready to contribute again. I'm okay with someone else taking over, of course.

**Comment by gterzian** [comment]
Ok, there is no rush. @lucasMontenegro please let us know if you prefer that @Taym95 takes it...

**Comment by lucasMontenegro** [comment]
Yeah, I'm okay with it

**Comment by gterzian** [comment]
cc @Taym95

**Comment by Taym95** [comment]
@servo-highfive: assign me

**Comment by beaufortfrancois** [comment]
@Taym95 Did you have a chance to look at it?

**Comment by Taym95** [comment]
> @Taym95 Did you have a chance to look at it?

Yes, I am working on it and have some questions. I am seeking responses from the team before submitting the pull request
