### ISSUE TITLE
MAC: ./mach run stops at EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by gterzian** [servo/servo#30904]
```
(lldb) run
Process 831 launched: '/Users/Gregory/Projects/servo/target/debug/servo' (x86_64)
Process 831 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x10a0d7350)
    frame #0: 0x0000000103b27b1f servo`atomic_store_p(a=0x000000010a0d7350, val="3|??W?", mo=atomic_memory_order_release) at atomic.h:55:1
   52  	#  define JEMALLOC_ATOMIC_U64
   53  	#endif
   54  	
-> 55  	JEMALLOC_GENERATE_ATOMICS(void *, p, LG_SIZEOF_PTR)
   56  	
   57  	/*
   58  	 * There's no actual guarantee that sizeof(bool) == 1, but it's true on the only
Target 0: (servo) stopped.
```

Without debugger
```
./mach run
No build type specified so assuming `--dev`.
Servo was terminated by signal 10
```

This is on a Mac M2

**Comment by sagudev** [comment]
It's jemalloc fault: https://github.com/tikv/jemallocator/issues/17

**Comment by gterzian** [comment]
It now works for me, after un-installing rustup and re-installing it(which defaults to `aarch64`). Also did a `./mach clean` and `/mach boostrap` for good measure.

I think the problem was my rustup was from a previous mac, and I boostrapped the M2 off of a time capsule of the older one, with rustup with default target as x84_64(translated by rosetta I guess). Manually adding the `aarch64` target did not fix the issue, but re-installing rust did.
