### ISSUE TITLE
Improve formatting of Python files

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#30910]
Several directories and Python files do not pass flake8 with our configuration. These files should be fixed and the exception removed from the `.flake8` file.

Here's the list of things to fix:
 - [ ] etc/ci
 - [ ] ./python/wpt/run.py
 - [ ] ./python/tidy/tidy.py
 - [ ] ./etc/servo_automation_screenshot.py
 - [ ] ./etc/memory_reports_over_time.py

**Comment by servo-highfive** [comment]
Hi! If you have any questions regarding this issue, feel free to make a comment here, or ask it in [Zulip](https://servo.zulipchat.com/).

If you intend to work on this issue, then add `@servo-highfive: assign me` to your comment, and I'll assign this to you. :smile:

**Comment by Taym95** [comment]
@servo-highfive: assign me

**Comment by servo-highfive** [comment]
Hey @Taym95! Thanks for your interest in working on this issue. It's now assigned to you!
