### ISSUE TITLE
Implement Event.composedPath

### ISSUE THREAD

**Issue by gterzian** [servo/servo#31007]
Needed for https://github.com/servo/servo/issues/30822

See https://dom.spec.whatwg.org/#ref-for-dom-event-composedpath%E2%91%A0

Method should be added to the [WebIDL](https://github.com/servo/servo/blob/c219204084b8f8a747ebd37ec75472c1b7e97411/components/script/dom/webidls/Event.webidl), and the generated method implemented on [`Event`](https://github.com/servo/servo/blob/c219204084b8f8a747ebd37ec75472c1b7e97411/components/script/dom/event.rs)

For a starting point, look at https://github.com/servo/servo/blob/c219204084b8f8a747ebd37ec75472c1b7e97411/components/script/dom/event.rs#L147, and see https://dom.spec.whatwg.org/#event-path-invocation-target

**Comment by Taym95** [comment]
@servo-highfive: assign me

**Comment by servo-highfive** [comment]
Hey @Taym95! Thanks for your interest in working on this issue. It's now assigned to you!
