### ISSUE TITLE
WebIDL: use FLoat32Array in GamePad

### ISSUE THREAD

**Issue by gterzian** [servo/servo#31049]
Depends on https://github.com/servo/servo/pull/30990

How to do it:

 1.   In [CodegenRust.py](https://github.com/servo/servo/blob/main/components/script/dom/bindings/codegen/CodegenRust.py) remove GamePad from the list in todo_switch_float_32.
 2.   Replace [axes](https://github.com/servo/servo/blob/355567186400d0531657d0eedda7625de9d0e93a/components/script/dom/gamepad.rs#L34) with HeapFloat32Array.
3.    Replace [Axes](https://github.com/servo/servo/blob/355567186400d0531657d0eedda7625de9d0e93a/components/script/dom/gamepad.rs#L99) to return a Float32Array, by doing the same as in [AudioBuffer::GetChannelData](https://github.com/servo/servo/pull/30990/files#diff-88b03ac9bcc2650883607d41bc374d7f3976567cfbee702cc124f14ce2fbc79bR231)

Any questions, ask here or in https://servo.zulipchat.com/

**Comment by gterzian** [comment]
part of https://github.com/servo/servo/issues/30862

**Comment by Taym95** [comment]
@gterzian  I think you meant GamepadPose
