### ISSUE TITLE
Remove create_typed_array from dom/bindings

### ISSUE THREAD

**Issue by gterzian** [servo/servo#31050]
Depends on:

https://github.com/servo/servo/issues/31049
https://github.com/servo/servo/issues/31048
https://github.com/servo/servo/issues/31047
https://github.com/servo/servo/issues/31046

and https://github.com/servo/servo/pull/30990

https://github.com/servo/servo/blob/355567186400d0531657d0eedda7625de9d0e93a/components/script/dom/bindings/utils.rs#L137

**Comment by gterzian** [comment]
part of https://github.com/servo/servo/issues/30862

**Comment by servo-highfive** [comment]
Hi! If you have any questions regarding this issue, feel free to make a comment here, or ask it in [Zulip](https://servo.zulipchat.com/).

If you intend to work on this issue, then add `@servo-highfive: assign me` to your comment, and I'll assign this to you. :smile:

**Comment by paguedem** [comment]
@servo-highfive: assign me

**Comment by servo-highfive** [comment]
Hey @paguedem! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by gterzian** [comment]
@paguedem I'm sorry we're going to have to do this one as part of https://github.com/servo/servo/pull/31106 to fix build warnings, I'll will ping you next time I open a good first issue!
