### ISSUE TITLE
Incorrect Schedule in Nightly Rust Workflow

### ISSUE THREAD

**Issue by Diwakar-Gupta** [servo/servo#31051]
https://github.com/servo/servo/blob/355567186400d0531657d0eedda7625de9d0e93a/.github/workflows/nightly-rust.yml#L5-L6

## Description:
The comment in the [`nightly-rust.yml`](https://github.com/servo/servo/blob/355567186400d0531657d0eedda7625de9d0e93a/.github/workflows/nightly-rust.yml) file indicates that the workflow is scheduled to run at `5:30 am` daily. However, upon reviewing the actual cron schedule, it appears to be set for `5:15 am` ('15 5 * * *'). To ensure accurate execution timing, could you please clarify which timing is intended?

## Proposed Correction:

1. If the intended schedule is 5:30 am, the cron expression should be adjusted to reflect this ('30 5 * * *').
2. If the intended schedule is 5:15 am, update the comment in the workflow file accordingly to avoid confusion.

**Comment by mrobinson** [comment]
I don't think the time matters too much, so updating the comment sounds fine to me.

**Comment by Diwakar-Gupta** [comment]
Thanks for clarification will update
