### ISSUE TITLE
 Build error : failed to run custom build command for `style v0.0.1 (servo\components\style)`

### ISSUE THREAD

**Issue by paguedem** [servo/servo#31074]
Hello i'm new to servo

Os : Windows 10
I'm following this [Windows](https://github.com/servo/servo?tab=readme-ov-file#windows) 

I did all the process, now i'm building with `match.bat run --dev` but it failed with this error : 

![servo1](https://github.com/servo/servo/assets/122303400/f74baf4f-39c8-4dd2-8afe-b397a2e6ba11)

The error message is here 

![servo2](https://github.com/servo/servo/assets/122303400/63fa4e91-247f-4e9b-afa3-a9e1e2f66bd9)

I need help.

**Comment by mrobinson** [comment]
Please paste more output from your terminal. There isn't enough here to know what is going wrong.

**Comment by paguedem** [comment]
Yeah

When i run the build command


![servo init](https://github.com/servo/servo/assets/122303400/c902e7df-89fe-4c88-98af-5ae346331573)

it failed here

![servo3](https://github.com/servo/servo/assets/122303400/42755b6e-9246-4e71-9af7-57bae0d24a29)



![servo3 PN](https://github.com/servo/servo/assets/122303400/090f9a0c-c695-4afa-ac48-1437fb374a41)

**Comment by mrobinson** [comment]
It looks like the issue might be that Python isn't installed. Can you execute `python.exe` or `python3.exe` from your terminal? Did you first install Python before trying to compile?

**Comment by paguedem** [comment]
@mrobinson  Yes exact it was the python issue. I had python2 installed in the home directory. I fixed it, it build and run now.
Thanks.
