### ISSUE TITLE
Docs building still failing on gstreamer-gl-x11

### ISSUE THREAD

**Issue by sagudev** [servo/servo#31109]
```
Documenting gstreamer-gl-x11 v0.21.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gstreamer-gl-x11-0.21.1/src/lib.rs:9:37
  |
9 | #![cfg_attr(all(not(doctest), doc), feature(doc_cfg))]
  |                                     ^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not document `gstreamer-gl-x11`
```

We can either disable documenting gstreamer-gl-x11, use nightly for documenting or RUSTC_BOOTSTRAP on gstreamer-gl-x11 for docs building.

**Comment by mrobinson** [comment]
I think it'd be better to simply disable documentation for `gstreamer-gl`. This seems like an upstream bug and we should stop relying on nightly to do formatting as soon as we can. Ultimately, Servo should only require a single toolchain per build target.

**Comment by sagudev** [comment]
`--keep-going` didn't do the trick, but upstream got fixed and we got it in https://github.com/servo/servo/pull/31465, so docs build are green now.
