### ISSUE TITLE
`./mach test --all` fails with `KeyError: 'dev'`

### ISSUE THREAD

**Issue by oSoMoN** [servo/servo#31129]
When I run `./mach test` without additional parameters, I get the following output:

    $ ./mach test 
     * Python requirements up to date.
    Specify a test path or suite name, or pass --all to run all test suites.
    
    Available suites:
        wpt
        unit

When I run `./mach test --all`, as suggested by the above, I get the following traceback:

    $ ./mach test --all
     * Python requirements up to date.
    Error running mach:
    
        ['test', '--all']
    
    The error occurred in code that was called by the mach command. This is either
    a bug in the called code itself or in the way that mach is calling it.
    You can invoke |./mach busted| to check if this issue is already on file. If it
    isn't, please use |./mach busted file| to report it. If |./mach busted| is
    misbehaving, you can also inspect the dependencies of bug 1543241.
    
    If filing a bug, please include the full output of mach, including this error
    message.
    
    The details of the failure are as follows:
    
    KeyError: 'dev'
    
      File "/home/osomon/build/servo/python/servo/testing_commands.py", line 130, in test
        Registrar.dispatch("test-%s" % suite, context=self.context, **kwargs)
      File "/home/osomon/build/servo/python/mach/mach/registrar.py", line 152, in dispatch
        return self._run_command_handler(handler, context=context, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/osomon/build/servo/python/mach/mach/registrar.py", line 109, in _run_command_handler
        result = fn(**kwargs)
                 ^^^^^^^^^^^^
      File "/home/osomon/build/servo/python/servo/command_base.py", line 780, in configuration_decorator
        kwargs['release'], kwargs['dev'], kwargs['prod'], kwargs['profile'],
                           ~~~~~~^^^^^^^

**Comment by atbrakhi** [comment]
Which test are you trying to run? 

To run unit-tests you need to do `./mach test-unit` and to run wpt `./mach test-wpt`

**Comment by oSoMoN** [comment]
See the output of `./mach test` without any additional arguments:

    Specify a test path or suite name, or pass --all to run all test suites.

So I'm running `./mach test --all`, as suggested.

**Comment by mrobinson** [comment]
Now that `./mach test` only runs unit tests and WPT, it might be worth simply removing it.

**Comment by oSoMoN** [comment]
> Now that `./mach test` only runs unit tests and WPT, it might be worth simply removing it.

Sure, I can do that. Is it okay to simply remove the `--all` parameter, or should it somehow be marked deprecated?

**Comment by oSoMoN** [comment]
Note that merely removing the `--all` parameter won't fix the problem, the command will fail in the same way when run like this: `./mach test unit` (as opposed to `./mach test-unit`). So [your suggestion](https://github.com/servo/servo/pull/31130#pullrequestreview-1830422041) to pass the required arguments when calling `Registrar.dispatch` seems correct.

**Comment by mrobinson** [comment]
Sorry, I meant to remove the `./mach test` command entirely. Before when it supported more kinds of tests, it made more sense. Nowadays it just runs two types of tests.

**Comment by oSoMoN** [comment]
Got it! I'll take a stab at it.

**Comment by oSoMoN** [comment]
Note: https://github.com/servo/servo/wiki/Testing is going to need a facelift, it's quite outdated.

**Comment by oSoMoN** [comment]
> Note: https://github.com/servo/servo/wiki/Testing is going to need a facelift, it's quite outdated.

Unfortunately the wiki doesn't accept pull requests, so here is my proposal:

```diff
diff --git a/Testing.md b/Testing.md
index 322a7e0..46fcf02 100644
--- a/Testing.md
+++ b/Testing.md
@@ -2,14 +2,12 @@ Servo has a test suite which runs on every reviewed pull request, via [bors-serv
 
 You can run the test suite yourself through these `./mach` commands:
 
-* `./mach test`: Runs all the Servo tests. 
 * `./mach test-unit`: Runs unit tests (functions tagged with `#[test]`) inside Servo and its dependencies.  May also run ref or content tests depending on your platform.
 * `./mach test-wpt`: Runs the [web platform tests](https://github.com/w3c/web-platform-tests) on Servo.
-* `./mach test-css` Runs a subset of the [CSS WG tests](http://www.w3.org/Style/CSS/Test/) (mostly reftests) on Servo. Uses the same harnesses as the web-platform-tests and the further information there still applies.
 
-## Writing test
+## Writing tests
 * [Write wpt/css tests](https://github.com/servo/servo/blob/master/tests/wpt/README.md)
-* Write unit tests: These are common Rust programs under `tests/unit`, and is organized to reflect the `components` tree. You can follow the existing structure and [Rust testing guide](https://doc.rust-lang.org/book/testing.html).
+* Write unit tests: these are common Rust programs under `tests/unit`, and are organized to reflect the `components` tree. You can follow the existing structure and [Rust testing guide](https://doc.rust-lang.org/book/testing.html)
 
 ## Assign a Temporary Hostfile for Testing
   In some tests (e.g. wpt tests), you need to use a hostfile to translate testing domain names to real IPs. For example, translating `wpt1.testserver.com` to `127.0.0.1`. But you may not have the permission to change the system hostfile in a shared server. Instead, you can assign a temporary hostfile using the `HOST_FILE` environment variable.
@@ -23,4 +21,4 @@ Then, set the `HOST_FILE` environment variable as the absolute path to the hostf
 ~~~bash
 export HOST_FILE=/tmp/hostfile.txt
 ~~~
-Now, if you open http://wpt1.testserver.com in servo, you will go to http://127.0.0.1 directly.
\ No newline at end of file
+Now, if you open http://wpt1.testserver.com in servo, you will go to http://127.0.0.1 directly.
```

**Comment by oSoMoN** [comment]
Thanks @mrobinson. May I ask if you'd mind applying my suggested changes to the [Testing](https://github.com/servo/servo/wiki/Testing) wiki page (because I assume edit rights are not granted without more significant contributions)?

**Comment by atbrakhi** [comment]
@oSoMoN thanks for the changes. I have updated the [wiki](https://github.com/servo/servo/wiki/Testing)
