### ISSUE TITLE
egl function was not loaded

### ISSUE THREAD

**Issue by nnnbuu** [servo/servo#31173]
I got this error when running [the latest nightly build](https://download.servo.org/nightly/linux/servo-latest.tar.gz):

```bash
$ ./servo
egl function was not loaded (thread main, at /home/runner/work/servo/servo/target/production/build/surfman-fd50a66ba16975f8/out/egl_bindings.rs:284)
```

**Comment by sagudev** [comment]
Works normally on my linux machine. You might need to install runtime dependencies: https://github.com/servo/servo#linux-1

**Comment by nnnbuu** [comment]
I did it, but the error still persists.

**Comment by sagudev** [comment]
Maybe some stuff is still missing like `mesa-utils-extra` and `libegl1-mesa` check https://github.com/servo/servo/wiki/Building#debian-based-distributions for all packages.

**Comment by nnnbuu** [comment]
Can we bundle all required libraries into a `servo` build?

**Comment by sagudev** [comment]
I was thinking to introduce AppImage for servo, although I think those dependencies are more system/gpu specific, so it might not help for all cases.

Did you resolve your issue?

**Comment by nnnbuu** [comment]
I installed all stuff listed in https://github.com/servo/servo/wiki/Building#debian-based-distributions, but no luck.

**Comment by nnnbuu** [comment]
The `2024-01-11` build (which I can recall) was the last one that I could run without encountering any errors or needing to install additional dependencies.

**Comment by sagudev** [comment]
> The `2024-01-11` build (which I can recall) was the last one that I could run without encountering any errors or needing to install additional dependencies.

Can you verify that 2024-01-11 is last working and 2024-01-12 first bad?

Also did you also install recommended packages? You can try `libglfw3-dev libgles2-mesa-dev libosmesa6-dev freeglut3-dev`.

**Comment by arpu** [comment]
will try find what packages are missing on fedora 

```
➜  servo dnf list installed | grep mesa
mesa-dri-drivers.x86_64                              23.3.3-1.fc39                       @updates              
mesa-filesystem.x86_64                               23.3.3-1.fc39                       @updates              
mesa-libEGL.x86_64                                   23.3.3-1.fc39                       @updates              
mesa-libGL.x86_64                                    23.3.3-1.fc39                       @updates              
mesa-libGLU.x86_64                                   9.0.3-1.fc39                        @fedora               
mesa-libgbm.x86_64                                   23.3.3-1.fc39                       @updates              
mesa-libglapi.x86_64                                 23.3.3-1.fc39                       @updates              
mesa-libxatracker.x86_64                             23.3.3-1.fc39                       @updates              
mesa-va-drivers.x86_64                               23.3.3-1.fc39                       @updates              
mesa-vulkan-drivers.x86_64                           23.3.3-1.fc39                       @updates              
➜  servo ldd ./servo 
	linux-vdso.so.1 (0x00007ffd501a3000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc74fc00000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc75601b000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007fc755fc6000)
	libunwind-x86_64.so.8 => /lib64/libunwind-x86_64.so.8 (0x00007fc755faa000)
	libunwind.so.8 => /lib64/libunwind.so.8 (0x00007fc755f90000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007fc74feb9000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc755f89000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007fc74faf2000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007fc755f3a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc755f35000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc74feb4000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc74fa11000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc74f82f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc75604c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc74fe8e000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007fc74f73c000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fc74fe63000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fc74f5f2000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fc74f522000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007fc74f501000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007fc74f38d000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007fc74fe57000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007fc74f36b000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fc74f338000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007fc74f27c000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007fc74f276000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fc74f1db000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fc74f1c7000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007fc74f18e000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007fc74f17e000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007fc74f15b000)
```

**Comment by arpu** [comment]
```
sudo dnf install mesa-libEGL-devel
```

starts servo now on fedora 39

**Comment by nnnbuu** [comment]
Hi @sagudev,

I have just downloaded and tried to launch the 30 most recent builds from [servo/servo-nightly-builds](https://github.com/servo/servo-nightly-builds/releases).

[2024-01-05](https://github.com/servo/servo-nightly-builds/releases/tag/2024-01-05) is the last working and [2024-01-08](https://github.com/servo/servo-nightly-builds/releases/tag/2024-01-08) is the first bad.

Surprisingly, I could run the `2024-01-05` build without needing to install any dependencies listed above.

**Comment by nnnbuu** [comment]
Hi @sagudev,

I have just downloaded and tried to launch the 30 most recent builds from [servo/servo-nightly-builds](https://github.com/servo/servo-nightly-builds/releases).

I am sure to tell you that [2024-01-05](https://github.com/servo/servo-nightly-builds/releases/tag/2024-01-05) is the last working and [2024-01-08](https://github.com/servo/servo-nightly-builds/releases/tag/2024-01-08) is the first bad.

Surprisingly, I could run the `2024-01-05` build **without needing to install any dependencies** listed above.

**Comment by mrobinson** [comment]
This is quite likely the result of https://github.com/servo/servo/commit/7fa4ea9740edccc93672d8cc428f6e9d4575a036.

**Comment by nnnbuu** [comment]
> This is quite likely the result of [7fa4ea9](https://github.com/servo/servo/commit/7fa4ea9740edccc93672d8cc428f6e9d4575a036).

That means users should install some required dependencies. Should the [troubleshooting](https://servo.org/download/#troubleshooting) section be updated now?

**Comment by nnnbuu** [comment]
> This is quite likely the result of [7fa4ea9](https://github.com/servo/servo/commit/7fa4ea9740edccc93672d8cc428f6e9d4575a036).

Should the [troubleshooting section](https://servo.org/download/#troubleshooting) be updated now?

**Comment by mrobinson** [comment]
There is a section of Linux runtime dependencies listed at https://github.com/servo/servo/#runtime-dependencies. Ideally, if there is a new runtime dependency it should be added there. Unfortunately, it looks like the current list are essentially Ubuntu package names though, so it's unclear what to do about Fedora.

**Comment by mukilan** [comment]
Looks like this issue is [failing](https://github.com/web-platform-tests/wpt/runs/20952937974) Servo's webdriver tests on WPT.fyi. WPT.fyi docker image is based on Ubuntu 20.04 - do we know which dependency needs to be installed [here](https://github.com/web-platform-tests/wpt/blob/master/tools/docker/Dockerfile#L8)?

**Comment by mrobinson** [comment]
> Looks like this issue is [failing](https://github.com/web-platform-tests/wpt/runs/20952937974) Servo's webdriver tests on WPT.fyi. WPT.fyi docker image is based on Ubuntu 20.04 - do we know which dependency needs to be installed [here](https://github.com/web-platform-tests/wpt/blob/master/tools/docker/Dockerfile#L8)?

Hrm. Unusual, I understood that on Ubuntu 20.04 we had disabled media completely?

**Comment by nnnbuu** [comment]
> Hrm. Unusual, I understood that on Ubuntu 20.04 we had disabled media completely?

No, we hadn't.

**Comment by nnnbuu** [comment]
Could you kindly provide any recent updates on this issue?

**Comment by sagudev** [comment]
> Could you kindly provide any recent updates on this issue?

There has been some more investigation in https://github.com/servo/servo/issues/31271 as this issue was not available for a week or so: https://servo.zulipchat.com/#narrow/stream/263398-general/topic/.E2.9C.94.20Missing.20issue
