### ISSUE TITLE
Implement non-XR gamepad discovery and input

### ISSUE THREAD

**Issue by msub2** [servo/servo#31179]
Recently I've been doing some work on Servo's WebXR crate, but while doing that I noticed that the Gamepad API wasn't supported for regular controllers and thought it would be a fun project to take on!

Spec: https://www.w3.org/TR/gamepad/

There is some existing code in Servo already for Gamepads, but it was added for use with WebVR/WebXR and as such doesn't support discovery/communication with regular game controllers. My plan is to utilize [GilRs (Game Input Library for Rust)](https://gitlab.com/gilrs-project/gilrs) as the backend for gamepad discovery/communication. From my understanding this will also involve creating a new task source for communication with Constellation and handling polling and such on the embedder's event loop.

**Comment by matlu** [comment]
Great idea and efforts!
Once more things have landed it would be good to add the WPT tests for Gamepad to https://wpt.servo.org/
Here is current status for Servo based on WPT. https://wpt.fyi/results/gamepad?label=master&label=experimental&product=chrome&product=servo&product=edge&product=safari&aligned

![image](https://github.com/servo/servo/assets/6307430/5f50827e-56bc-4b37-86ef-1f640b3b5865)
