### ISSUE TITLE
Skip unit tests for T-linux-wpt-2020 and T-linux-wpt-2013

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31174]
Previously, `try=wpt` and `try=wpt-2020` didn't include unit tests:

https://github.com/servo/servo/blob/66e169cc71741bb4c7a16651955e98cf6a261741/.github/workflows/try.yml#L40-L43

But now the `T-linux-wpt-2020` and `T-linux-wpt-2013` labels do:

https://github.com/servo/servo/blob/bb04c97f15728d14a146f29fa1bc4d23ee96ec49/.github/workflows/try.yml#L68-L70

I don't expect unit tests if there is wpt in the name.

**Comment by sagudev** [comment]
Good point, I will resolve this within https://github.com/servo/servo/pull/31141

**Comment by atouchet** [comment]
@sagudev is this done now?

**Comment by sagudev** [comment]
It's done.
