### ISSUE TITLE
Security Vulnerablity Report

### ISSUE THREAD

**Issue by RandomDhiraj** [servo/servo#31193]
Team, just reaching out to see if I have to report a security related vulnerabilities against "Servo" where should I send it? Thanks!

**Comment by jdm** [comment]
I am seeking input from the Technical Steering Committee on how to answer this and will get back to you!

**Comment by RandomDhiraj** [comment]
Thanks, if you come across any existing process please do let me know, if not GitHub has a capability of creating "Security Policy" for a repository. (https://github.com/servo/servo/security) .

**Comment by jdm** [comment]
Given that Servo does not yet have customers or products, we're comfortable accepting the report as a GitHub issue for now.
