### ISSUE TITLE
Build failed: error: failed to run custom build command for `mozangle v0.5.0`

### ISSUE THREAD

**Issue by rathod-sahaab** [servo/servo#31197]
[RESOLVED]

Following https://github.com/servo/servo/blob/main/docs/HACKING_QUICKSTART.md#building-servo

servo on  master via 🦀 v1.74.1 
sh ./mach build -d
error: `rustc -vV` didn't have a line for `host:`, got:

Error running mach:

    ['build', '-d']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

servo.command_base.BuildNotFound: No Servo binary found. Perhaps you forgot to run `./mach build`?

  File "/home/rathod-sahaab/projects/open-source/servo/python/servo/command_base.py", line 739, in configuration_decorator
    return original_function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rathod-sahaab/projects/open-source/servo/python/servo/build_commands.py", line 107, in build
    built_binary = self.get_binary_path(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rathod-sahaab/projects/open-source/servo/python/servo/command_base.py", line 354, in get_binary_path
    raise BuildNotFound('No Servo binary found. Perhaps you forgot to run `./mach build`?')

servo on  master via 🦀 v1.74.1 
err rustc -vV
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: x86_64-unknown-linux-gnu
release: 1.74.1
LLVM version: 17.0.4

**Comment by rathod-sahaab** [comment]
Running ./mach bootstrap
```
sh ./mach bootstrap
mach bootstrap does not support Manjaro Linux, please file a bug

**Comment by rathod-sahaab** [comment]
While running ./mach build -d

```
warning: clang-16: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]

error: failed to run custom build command for `mozangle v0.5.0`
```

**Comment by jdm** [comment]
See https://servo.zulipchat.com/#narrow/stream/263398-general/topic/Build.20Issues/near/412070499 for how you can resolve that issue.

**Comment by rathod-sahaab** [comment]
Thanks worked like a charm!
