### ISSUE TITLE
clientWidth may not force layout when style has changed

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31195]
```html
<!DOCTYPE html>
<div id="target"></div>
<div id="log" style="white-space: pre"></div>
<script>
target.style.cssText = "width: 5px";
log.append(target.clientWidth + "\n");

target.style.cssText = "width: 15px";
log.append(target.clientWidth + "\n");
</script>
```

Expected:
```
5
15
```

Actual:
```
5
5
```

**Comment by gterzian** [comment]
There appears to be some caching, which I guess should be invalidated in that case

https://github.com/servo/servo/blob/091653417a35229439277285e19abfaf6f9d7383/components/script/dom/element.rs#L3348

A good place to investigate invalidated that cache is I think: 

https://github.com/servo/servo/blob/091653417a35229439277285e19abfaf6f9d7383/components/script/dom/cssstyledeclaration.rs#L56
