### ISSUE TITLE
Cannot install libgstreamer in debian 12

### ISSUE THREAD

**Issue by jcoonrod** [servo/servo#31220]
There seems to be an error in bootstrap that refuses to install the latest version of libgstreamer. It seems to search for and fails to find an old one. I get this:  Unable to locate package libgstreamer-plugins-good1.0-dev -

I can manually install libgstreamer-plugins-base1.0-0 but bootstrap doesn't like it.

Any way around this? Or is there a "please ignore gstreamer" option in mach?

**Comment by paricbat** [comment]
`libgstreamer-plugins-good1.0-dev` is packaged in Ubuntu, but not in Debian, not sure why.
Removing it from the package list in `python/servo/platform/linux.py` seems to work.
