### ISSUE TITLE
`selectors::OpaqueElement::new` is unsound

### ISSUE THREAD

**Issue by GuillaumeGomez** [servo/servo#31304]
When building librsvg with the GCC backend, we got a warning about returning a pointer to a local variable [here](https://gitlab.gnome.org/GNOME/librsvg/-/blob/main/rsvg/src/css.rs#L574). The problem comes from `OpaqueElement::new` doing a reference to pointer conversion.

EDIT: The bug might be coming from the rust GCC backend, just opening this issue in case it is not wrong. Don't hesitate to close it if there is no issue.

**Comment by GuillaumeGomez** [comment]
It seems that the issue is in fact how this API is used rather than the API itself. Closing then and opening an issue on the relevant repository.

**Comment by sdroege** [comment]
AFAICS this here is all fine, but librsvg is probably wrong here. It's passing the `&Ref<Node>` into `new()`, and that's indeed an address to a local variable that is then stored in the `OpaqueElement`. That's not really a problem as it can only be used for comparison purposes AFAIU, but probably not the intended behaviour in librsvg.

For reference, the compiler warning from @GuillaumeGomez here is

```
libgccjit.so: warning: : function may return address of local variable [-Wreturn-local-addr]
libgccjit.so: note: : declared here
```

**Comment by federicomenaquintero** [comment]
[Permalink for the offending source code in librsvg](https://gitlab.gnome.org/GNOME/librsvg/-/blob/ee52be670eac436f213c9e3fb8f1587da38bb7e1/rsvg/src/css.rs#L574) - I've fixed this by not returning a `&Ref<...>`, which is clearly ephemeral, but rather a reference to the actual element data.

**Comment by federicomenaquintero** [comment]
[Bug in librsvg where this was originally reported](https://gitlab.gnome.org/GNOME/librsvg/-/issues/1055); [merge request with fix](https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/923).
