### ISSUE TITLE
Servo Fails Acid2 Test on the Latest Version

### ISSUE THREAD

**Issue by indprtech** [servo/servo#31316]
![image](https://github.com/servo/servo/assets/129782436/4a66e54c-bf90-4d42-9f1e-33c54ff8e6fa)
It does not seems to be right and an "Error" mark, it's not even rendering properly

Servo Version : Servo 0.0.1-19667e1
On Ubuntu 22.04
Hardware Information
HP Notebook 15-ac040tu
Processor : Intel Pentium 3825U

**Comment by stalkerg** [comment]
Currently, on Linux+Wayland+intel it's looks like this:
![image](https://github.com/servo/servo/assets/1853716/8c4371d5-b051-41a2-9d25-9eb7aa9e6057)

**Comment by mrego** [comment]
![Acid2 Test passing on Servo 25th April 2024 - commit 1440406e91684771bb810ead6ac5ae710f55f3ea](https://github.com/servo/servo/assets/11602/26b26137-6c3c-4e72-8524-10917a926319)

:tada:
