### ISSUE TITLE
Seems that the download link for Linux is missing

### ISSUE THREAD

**Issue by MirtoBusico** [servo/servo#31373]
Hi all,
trying to download servo for Linux at
[Linux (X64)](https://download.servo.org/nightly/linux/servo-latest.tar.gz)
I receive a file not found error

There is some problem with downloads?

**Comment by mukilan** [comment]
Looks like there are two issues:
1. The nightly build job is [failing](https://github.com/servo/servo/actions/runs/7946836240/job/21694994623). 
2. Ideally the GH Release should have been a pre-release so the links trying to fetch latest builds continue to work. Perhaps there is an issue with #31348

I'm looking into these issues, but for now you can download yesterday's linux build from [here](https://github.com/servo/servo-nightly-builds/releases/tag/2024-02-17).

cc @delan

**Comment by mukilan** [comment]
For the issue with nightly build, these are the relevant logs.

```
 --- stderr
  thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libudev-sys-0.1.4/build.rs:38:41:
  called `Result::unwrap()` on an `Err` value: "\npkg-config exited with status code 1\n> PKG_CONFIG_PATH=/opt/hostedtoolcache/Python/3.10.13/x64/lib/pkgconfig PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags libudev\n\nThe system library `libudev` required by crate `libudev-sys` was not found.\nThe file `libudev.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.\nPKG_CONFIG_PATH contains the following:\n    - /opt/hostedtoolcache/Python/3.10.13/x64/lib/pkgconfig\n\nHINT: you may need to install a package such as libudev, libudev-dev or libudev-devel.\n"
```

So looks like #31200 has introduced a dependency on `libudev-sys` which is failing to locate the relevant libraries on the build system. I suspect we'll need to install [libudev-dev](https://packages.ubuntu.com/focal/libudev-dev) during bootstrap now. Let me try that, but I'm not sure if this passed merge checks because it is somehow available already on 22.04 runners but not 20.04 (which is used for just the nightly builds).

cc @msub2

**Comment by MirtoBusico** [comment]
> Looks like there are two issues:
> 
>     1. The nightly build job is [failing](https://github.com/servo/servo/actions/runs/7946836240/job/21694994623).
> 
>     2. Ideally the GH Release should have been a pre-release so the links trying to fetch latest builds continue to work. Perhaps there is an issue with [Bury failed nightly releases as prereleases #31348](https://github.com/servo/servo/pull/31348)
> 
> 
> I'm looking into these issues, but for now you can download yesterday's linux build from [here](https://github.com/servo/servo-nightly-builds/releases/tag/2024-02-17).
> 
> **EDIT: I've manually marked the release for [today](https://github.com/servo/servo-nightly-builds/releases/tag/2024-02-18) as a pre-release, so the download links should work now.** cc @delan

Thanks
I'll use the yesterday link

**Comment by MirtoBusico** [comment]
Sorry @mukilan but I'm particularly dumb.

I'm using Debian testing updated daily. When I try to launch the yesterday build, I receive an error:
```
mirto@bianco500:~/Scaricati$ cd servo/
mirto@bianco500:~/Scaricati/servo$ ls -lh
totale 435M
drwxr-xr-x 4 mirto mirto 4,0K 18 feb 12.38 resources
-rwxr-xr-x 1 mirto mirto 435M  1 gen  1970 servo
mirto@bianco500:~/Scaricati/servo$ ./servo
egl function was not loaded (thread main, at /home/runner/work/servo/servo/target/production/build/surfman-4d98480c7267738a/out/egl_bindings.rs:284)
mirto@bianco500:~/Scaricati/servo$ 
```
Have I to install something?

**Comment by sagudev** [comment]
I think you need `libegl1-mesa-dev`.

**Comment by MirtoBusico** [comment]
Seems it is not sufficient:
```
mirto@bianco500:~/Scaricati/servo$ ./servo
egl function was not loaded (thread main, at /home/runner/work/servo/servo/target/production/build/surfman-4d98480c7267738a/out/egl_bindings.rs:284)
mirto@bianco500:~/Scaricati/servo$ sudo nala show libegl1-mesa-dev
Package: libegl1-mesa-dev
Version: 23.3.5-1
Architecture: amd64
Installed: no
Priority: optional
Essential: no
Section: libdevel
Source: mesa
Origin: Debian
Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Installed-Size: 61 KB
Depends: libegl-dev, libglvnd-dev
Homepage: https://mesa3d.org/
Download-Size: 20 KB
APT-Sources: http://deb.debian.org/debian/ testing/main amd64 Packages
Description: free implementation of the EGL API -- development files
 This package contains the development environment required for compiling
 programs against EGL native platform graphics interface library.
 EGL provides a platform-agnostic mechanism for creating rendering surfaces
 for use with other graphics libraries, such as OpenGL|ES.
 .
 This package provides the development environment for compiling programs
 against the EGL library.
mirto@bianco500:~/Scaricati/servo$ 
```

**Comment by sagudev** [comment]
You posted that `libegl1-mesa-dev` is not installed, so you need to install it:
```
mirto@bianco500:~/Scaricati/servo$ sudo nala show libegl1-mesa-dev
Package: libegl1-mesa-dev
Version: 23.3.5-1
Architecture: amd64
Installed: no
```

**Comment by MirtoBusico** [comment]
You are right!
The previous installation was unsuccessful.
After installin it the program starts correctly.

Thanks
