### ISSUE TITLE
`taplo` is very slow on MacOS

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#31440]
Taplo seems to have an issue on MacOS with processing speed. This is what I see when I run `./mach fmt`

```shell
$ time ./mach fmt

real	0m19.056s
user	0m2.091s
sys	0m7.640s
```

If I comment out taplo formatting, I see:

```shell
$ time ./mach fmt

real	0m1.622s
user	0m1.320s
sys	0m0.145s
```

**Comment by nicoburns** [comment]
I suspect a filesystem issue: that's usually the cause of perf differences between linux and macos. I notice taplo-cli is using the `glob` crate which is known to be slow and suggests that its doing custom filesystem walking logic. I bet this could be sped up by converting it to use the `walkdir`/`ignore` crates.
