### ISSUE TITLE
Fix inheritance.sub.html WPT to work on Servo

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31518]
https://wpt.fyi/results/css/css-backgrounds/inheritance.sub.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&product=servo&aligned

There are some subtests that are broken on Servo, e.g. "Property border-top-width has initial value 3px" becomes "Property border-top-width has initial value undefined" and fails.

The reason is that the test uses `mediumWidth` as the initial value, which is defined as https://github.com/servo/servo/blob/3a3e76a935f92ce84c24496cfc46207cd46088f6/tests/wpt/tests/css/css-backgrounds/inheritance.sub.html#L34

Servo doesn't support `column-rule-width`, so that's undefined. But referring to `column-rule-width` is weird in the 1st place, and https://github.com/w3c/csswg-drafts/commit/075522eb7269273709eda0037c8848879f87ac02 simply defined `medium` as `3px`.

So the test could be fixed to just use `3px` as the initial border width value, and then update the expectations for both the new and the legacy layout engines.

See https://github.com/servo/servo/blob/main/tests/wpt/README.md for details about running WPT and updating the expectations.

**Comment by servo-highfive** [comment]
Hi! If you have any questions regarding this issue, feel free to make a comment here, or ask it in [Zulip](https://servo.zulipchat.com/).

If you intend to work on this issue, then add `@servo-highfive: assign me` to your comment, and I'll assign this to you. :smile:

**Comment by azharcodeit** [comment]
Hi! 
@servo-highfive: assign me

**Comment by servo-highfive** [comment]
Hey @azharcodeit! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by onyiipaula** [comment]
hi outreachy intern here. Please assignme

**Comment by Loirooriol** [comment]
Sorry, already taken. Maybe you can contribute to #31500, since several people can work on it simultaneously?
