### ISSUE TITLE
 flow::BlockContainer.contains_floats() unconditionally returns true for IFCs

### ISSUE THREAD

**Issue by jschwe** [servo/servo#31540]
[flow::BlockContainer.contains_floats()](https://github.com/servo/servo/blob/096bd2977a7e322336bd885d68c7e722a47bfeaf/components/layout_2020/flow/mod.rs#L67) always returns true in the `InlineFormattingContext` case.

I asked on zulip https://servo.zulipchat.com/#narrow/stream/263398-general/topic/BlockContainer and was told this is likely a bug, so I'm opening an issue for it.

**Comment by ayushichoudhary-19** [comment]
I would like to work on this issue. Please assign it to me!

So, I assume we need a fix that ensures that contains_floats only returns true for BlockLevelBoxes where floats might be present and false for other variants, including InlineFormattingContext.

I am a beginner, an Outreacy applicant, so I need a little guidance before I proceed.
Thankyou

**Comment by ayushichoudhary-19** [comment]
@mrobinson, I'm looking through the open issues, but many seem a bit complex for someone new to the project.  I'm really interested in contributing!  Are there any upcoming requirements or tasks that could be good first issues for beginners that might not yet be posted in the issues tab?
