### ISSUE TITLE
Update outdated comment

### ISSUE THREAD

**Issue by atouchet** [servo/servo#31558]
https://github.com/servo/servo/blob/5ba29c20ac3d048efb2ae266d6f876829f0d632e/components/shared/script_layout/lib.rs#L216-L218

layout_traits was removed in #31346. This comment should be updated.

**Comment by atouchet** [comment]
Is `script_layout_traits` the correct change? I don't see any other references to that in the code and the package name in Cargo.toml is `script_layout_interface`.

**Comment by mrobinson** [comment]
Sorry, yes! The correct change is to modify this to `script_layout_interface`.

**Comment by jahielkomu** [comment]
@atouchet are you working on this or can I go ahead. 
Hello there.

**Comment by atouchet** [comment]
@jahielkomu you can go ahead.
