### ISSUE TITLE
Fix as many rustdoc errors as possible

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#31575]
1. Get Servo building and running on your system
2. Run `./mach doc`
3. Note the variety of documentation errors that show up during execution
4. Pick one or more of those errors. For instance:

```
warning: this URL is not a hyperlink
   --> components/shared/net/request.rs:189:20
    |
189 |     /// Step 12 of https://fetch.spec.whatwg.org/#concept-http-redirect-fetch
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://fetch.spec.whatwg.org/#concept-http-redirect-fetch>`
    |
    = note: bare URLs are not automatically turned into clickable links
    = note: `#[warn(rustdoc::bare_urls)]` on by default
```

In this case the line should be:

```rust
     /// Step 12 of <https://fetch.spec.whatwg.org/#concept-http-redirect-fetch>
```

**Comment by servo-highfive** [comment]
Hi! If you have any questions regarding this issue, feel free to make a comment here, or ask it in [Zulip](https://servo.zulipchat.com/).

If you intend to work on this issue, then add `@servo-highfive: assign me` to your comment, and I'll assign this to you. :smile:

**Comment by Aaryakhandelwal** [comment]
Hi, can be work with this issue. 
@servo-highfiv:assign me

**Comment by maureenblack** [comment]
Hi, I'll love to work on this issue.
@servo-highfive: assign me

**Comment by servo-highfive** [comment]
Hey @maureenblack! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by Aaryakhandelwal** [comment]
I am an Outreachy applicant, can I also proceed to work with this issue?

**Comment by jahielkomu** [comment]
> Yes, multiple people can work on this issue. Please just fix one or two errors and try to make sure that someone else hasn't opened a PR that fix the same ones.

Okay, thank you @mrobinson

**Comment by kleenpulse** [comment]
Please, can I work on this issue.
@mrobinson

**Comment by ssemanich** [comment]
Can I also work on this issue

**Comment by ssemanich** [comment]
@servo-highfive: assign me

**Comment by servo-highfive** [comment]
Hey @ssemanich! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by oluwatobiss** [comment]
Hi,

servo-highfive: assign me

**Comment by richarddushime** [comment]
@servo-highfive : assign me

**Comment by servo-highfive** [comment]
Hey @richarddushime! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by mrobinson** [comment]
There is no need to assign this issue to yourself. Simply look to see what PRs are waiting for review and try to fix errors that no one else has addressed yet.

**Comment by ektuu** [comment]
@servo-highfive : assign me

**Comment by servo-highfive** [comment]
Hey @ektuu! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by Loirooriol** [comment]
@ektuu Please read the comment that precedes yours.

**Comment by g3w** [comment]
Hi @mrobinson please my name is Abigail, kindly assign this task to me. I am willing to work on it.

**Comment by azharcodeit** [comment]
> Hi @mrobinson please my name is Abigail, kindly assign this task to me. I am willing to work on it.

Hey Abigail, everyone is welcome to work on this issue simultaneously

**Comment by VictoriaAjala** [comment]
Hi, I'd love to work on this issue as an Outreachy applicant.
@servo-highfive : assign me
