### ISSUE TITLE
Extract generated class constructor hook into handwritten functions

### ISSUE THREAD

**Issue by jdm** [servo/servo#31571]
The output of CGClassConstructHook is [difficult to read](https://github.com/servo/servo/blob/main/components/script/dom/bindings/codegen/CodegenRust.py#L6174-L6217). By following the model of #31569 and creating two generic helper functions that cover both cases (isHTMLConstructor is true/false), it will be easier to read and modify this code in the future. 

Part of #31570.

**Comment by rohansx** [comment]
@jdm would like to take on this task

**Comment by jdm** [comment]
@rohansx Ok! Take a look at the model PR in #31569 and ask any questions about the task here!

**Comment by MunishMummadi** [comment]
@jdm @mbrodesser-Igalia . I have got a basic idea. I formed the skeleton for the code. If you think it's correct. I can push a PR. 
```
class CGThing:
    pass

class CGSpecializedMethod:
    @method
    def makeNativeName(descriptor, m):
        pass

class CGSpecializedGetter:
    @method
    def makeNativeName(descriptor, m):
        pass

class DOMClass:
    def __init__(self, descriptor):
        pass

class CGInterfaceTrait(CGThing):
    def __init__(self, descriptor):
        CGThing.__init__(self)
        self.descriptor = descriptor

    def attribute_arguments(self, needCx, argument=None, inRealm=False):
        # Implementation
        pass

    def members(self):
        # IImplementation
        pass

    def method_arguments(self, rettype, arguments, inRealm=False):
        # Implementation
        pass

    def argument_type(self, arg_type):
        # Implementation
        pass

    def return_type(self, ret_type, infallible):
        # Implementation
        pass

class CGDOMJSProxyHandlerDOMClass(CGThing):
    def __init__(self, descriptor):
        CGThing.__init__(self)
        self.descriptor = descriptor

    def define(self):
        return "static Class: DOMClass = " + DOMClass(self.descriptor) + ";\n"

```

**Comment by MunishMummadi** [comment]
@servo-highfive assign me

**Comment by servo-highfive** [comment]
Hey @MunishMummadi! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by MunishMummadi** [comment]
Hey @jdm . I would love to work on this issue. Can you mentor me for this issue. I understood what to do. But it seems little overwhelming.

**Comment by jdm** [comment]
Yes, I'm happy to answer questions about it

**Comment by MunishMummadi** [comment]
Yeah!!. I constructed a basic skeleton for the code. I will follow up the details as I make progress.

**Comment by MunishMummadi** [comment]
@jdm . I am sorry to say this. I tried my best. But I failed. Thank you for the heads up.

**Comment by MunishMummadi** [comment]
hey @servo-highfive unassign me

**Comment by rohansx** [comment]
@jdm Went through the issue and need a few clarifications:
The PR states 
output of CGClassConstructHook (Present on Line 6111) 
Does this class code needs to be changed for better readability ?

Because the highlighted code section in (difficult to read) shows code line numbers from 6175-6212

**Comment by jdm** [comment]
Thanks for checking! https://github.com/servo/servo/blob/5d518ca8dc25157aa19aec3d2dacef21ef0c0294/components/script/dom/bindings/codegen/CodegenRust.py#L6111-L6172 is the intended class.

**Comment by rohansx** [comment]
@jdm Just one more additional help needed here. I have performed some code changes for this PR.
However can you guide me as to how do I test this function while running this application in local setup? (For debugging purpose)

![Screenshot from 2024-03-29 16-35-31](https://github.com/servo/servo/assets/33249782/2399f9d9-ce80-4dc2-9577-89cf4baadb48)

**Comment by jdm** [comment]
If the page loads like it did before, I would expect that's good enough for a PR. We can run the full automated test suite to verify the changes.

**Comment by rohansx** [comment]
Hello @jdm attempted this issue and created PR #31949 but would like a litte guidance .
I'm struggling with interop (running rust code within python file codegenrust.py)
My rust code is in a separate file called [construct_hook.rs](http://construct_hook.rs/)
Added the necessary import of crate in [import.rs](http://import.rs/)
Facing the below interop errors: 
`
error[E0424]: expected value, found module 'self'
 --> /home/rsx/Desktop/outreachy/servo/target/debug/build/script-30067a5bb009356d/out/Bindings/FileReaderSyncBinding.rs:515:93
    |
512 | unsafe extern fn _constructor(cx: *mut JSContext, argc: u32, vp: *mut JSVal) -> bool {
    |                  ------------ this function can't have a `self` parameter
...
515 |         let global = get_global_scope(cx, vp, argc);handle_constructor(cx, &argc, &global, &self.descriptor, &self.constructor);
    |                                                                                             ^^^^ `self` value is a keyword only available in methods with a `self` parameter`

**Comment by sagudev** [comment]
`self.constructor` is only available in python, rust cannot use python's variables.

**Comment by rohansx** [comment]
Hello Thank you for the guidance made a bit more changes can you help me with this one last query
I noticed I can't find use crate import statements mentioned in PR https://github.com/servo/servo/pull/31569/files
I need to add this similar line to make my code work. Has the location been changed to `import.rs`

`use crate::construct_hook::construct_if_block;`

![Screenshot 2024-03-31 at 5 07 29 PM](https://github.com/servo/servo/assets/33249782/f36c50fd-31a5-44b6-8b81-0cbbebb793ab)

**Comment by sagudev** [comment]
There were some changes to how importing is done. All you need to to is add proper use statements to `import.rs`. https://github.com/servo/servo/pull/31569 was made before this was introduced in https://github.com/servo/servo/pull/31711.

**Comment by rohansx** [comment]
Hello @sagudev a bit more help please, struggling to make build here . In my rust code (which I have separated in `construct_hook.rs` facing the below error for ` PrototypeList::ID::"%s"`
Do I have to explicitly define the type?
`error: expected identifier, found `"%s"`
  --> components/script/dom/bindings/construct_hook.rs:18:28
   |
18 |         PrototypeList: id: "%s", // Adjust as needed
   |                            ^^^^ expected identifier
    Building [=======================> ] 762/768: script`

**Comment by sagudev** [comment]
I am not sure if I understand error, it better to use \``` blocks when having code of multiple lines. From what I see in PR you need to be more careful what is python and what is rust. Codegen (python code) generates rust code (this is usually done with strings manipulation).

**Comment by meltq** [comment]
@rohansx are you still working on this?

**Comment by rohansx** [comment]
No

**Comment by meltq** [comment]
In that case I'll be working on this

**Comment by rohansx** [comment]
Go ahead @meltq

**Comment by meltq** [comment]
sorry bout that. not doing this

**Comment by Gae24** [comment]
Hi @jdm, how should I handle this inside the constructor? https://github.com/servo/servo/blob/05ecb8eddb3989ffcee51df5c2c86887fee8b7e8/components/script/dom/bindings/codegen/CodegenRust.py#L6206-L6209
Looking at the generated code the downcast is always added if `isHTMLConstructor` is true, but if it is false not always is done

**Comment by sagudev** [comment]
you can pass `isHTMLConstructor` as bool arg to function or use generic constants like it was done in https://github.com/servo/servo/commit/68f4b359c53b241e0ef82b640e84d8de70cfb805#diff-501f82b025ccf77a47ba693a8e1e56bacd4629b134c6206271de0dea1f857505L1983

**Comment by Gae24** [comment]
Maybe the cast could be moved inside CGMethodCall, since global is actually used inside it.
