### ISSUE TITLE
The minibrowser has a few pixels of unrendered space underneath the URL bar

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#31577]
On my system (Ubuntu), the minibrowser has a few pixels of unrendered space underneath the URL bar. This often flashes likely due to texture reuse. Unfortunately, I'm not able to do a screen recording of this behavior.

cc @delan @atbrakhi

**Comment by mrego** [comment]
I've been seeing this issue for a while, I've recorded it in the following video: 
https://github.com/servo/servo/assets/11602/67cf4a73-7ab9-45ca-8fda-0ba957782b20

**Comment by sagudev** [comment]
I observed the same behavior.

**Comment by atbrakhi** [comment]
I couldn't reproduce this on mac.
