### ISSUE TITLE
unused import: `mem`, in components/net/image_cache.rs

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31607]
When compiling I get

```
warning: unused import: `mem`
 --> components/net/image_cache.rs:9:11
  |
9 | use std::{mem, thread};
  |           ^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

#31564 used `std::mem::take(own_bytes)` instead of `mem::take(own_bytes)`. So it's a matter of either changing the consumer into `mem::take(own_bytes)`, or removing the import of `mem`.

**Comment by servo-highfive** [comment]
Hi! If you have any questions regarding this issue, feel free to make a comment here, or ask it in [Zulip](https://servo.zulipchat.com/).

If you intend to work on this issue, then add `@servo-highfive: assign me` to your comment, and I'll assign this to you. :smile:
