### ISSUE TITLE
vertical-align breaks the alignment of text at the very top of the independent FC

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31604]
```html
<!DOCTYPE html>
<style>
  .wrapper { border: 1px solid; white-space: nowrap; vertical-align: bottom }
  .ib-content { display: inline-block; height: 50px; width: 50px; background: cyan }
</style>
<div class="wrapper" style="display: inline-block">
  foo
  <span>bar</span>
  <div class="ib-content"></div>
</div>
<div class="wrapper" style="display: inline-table">
  foo
  <span>bar</span>
  <div class="ib-content"></div>
</div>
```

| Firefox | Servo |
| - | - |
| ![](https://github.com/servo/servo/assets/7477678/8635295e-9e83-4810-a5a1-0c64737d969e) | ![](https://github.com/servo/servo/assets/7477678/6e5ce6ca-49a5-4f56-9b70-8253a720b506) |

It happens for `vertical-align: top` and `bottom`, `middle`  is fine.

The text that is wrapped inside a `<span>` is also fine.

It also works well when the wrapper is not inline-level.

**Comment by mrobinson** [comment]
`vertical-align: top` and `vertical-align: bottom` are supposed to create [aligned subtrees](https://drafts.csswg.org/css2/#aligned-subtree) and Servo doesn't have support for those yet. This could be what is going on here.
