### ISSUE TITLE
Networking: fold websocket and http tokio runtime into one. 

### ISSUE THREAD

**Issue by gterzian** [servo/servo#31648]
We use two separate Tokio runtimes:

One for HTTP requests:

https://github.com/servo/servo/blob/525fc58ed9816d1cf43971c48f65266de9bd424e/components/net/http_loader.rs#L74

And another one for Websockets: 

https://github.com/servo/servo/blob/525fc58ed9816d1cf43971c48f65266de9bd424e/components/net/websocket_loader.rs#L52

The rationale is:

 https://github.com/servo/servo/blob/525fc58ed9816d1cf43971c48f65266de9bd424e/components/net/websocket_loader.rs#L48-L50

I think it's doubtful that a large amount of websockets could really starve HTTP request, since the whole point of tokio is to run a large amount a tasks onto a single runtime. 

We should investigate using one runtime for all networking tasks.

**Comment by wusyong** [comment]
I saw your [comment ](https://servo.zulipchat.com/#narrow/stream/416779-Performance/topic/High.20memory.20usage/near/426427838)in zulip mentioned there's another [PR](https://github.com/servo/servo/pull/31517) dealing with thread spawning too. But it seems it [created](https://github.com/servo/servo/pull/31517#discussion_r1516598262) even more threads. I'm wondering if we could make whole `net` crate to share the same tokio runtime without manually spawning threads and thread pool.

**Comment by gterzian** [comment]
> But it seems it https://github.com/servo/servo/pull/31517#discussion_r1516598262 even more threads.

Yes that's correct, it uses a threadpool which will see threads created upfront, instead of spawning one thread for each image that is decoded. 

> I'm wondering if we could make whole net crate to share the same tokio runtime without manually spawning threads and thread pool.

We can use a single runtime for all async task, and a single core resource threadpool for the other non-async bacground work.

**Comment by wusyong** [comment]
@gterzian Could you add some good-first-issue or E-candidate-for-mentoring label?
This issue seems like a good chance for anyone who want to contribute.

**Comment by tannal** [comment]
I would like to take this up.

**Comment by MunishMummadi** [comment]
Hey @tannal what is your status with the issue. Can I join

**Comment by tannal** [comment]
@MunishMummadi Yes you can.
The quick fix for this issue is done.

> We can use a single runtime for all async task, and a single core resource threadpool for the other non-async bacground work.

You can open another pr to do this part if you are interested in this issue.

**Comment by gterzian** [comment]
> a single core resource threadpool for the other non-async bacground work.

Yes indeed, this part would be good for a new PR @MunishMummadi 

The idea is to use a single `CoreResourceThreadPool` in `components/net`, see for guidance this issue, which added a second one. You could make changes to have a single pool used where now two are used.

**Comment by MunishMummadi** [comment]
Yes I would love to work on it @gterzian @tannal . Can I ask the bot to "assign me"!!!

**Comment by gterzian** [comment]
Actually, because the image cache runs in the script thread, not in the core resource thread, this is quite complicated and perhaps not a good idea. I withdraw my earlier conclusion.
