### ISSUE TITLE
Rename cache_total_advance_and_word_seperators to cache_total_advance_and_word_separators

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31653]
It's in `components/gfx/text/glyph.rs`. The right word is "sep**a**rator", not "sep**e**rator".

**Comment by servo-highfive** [comment]
Hi! If you have any questions regarding this issue, feel free to make a comment here, or ask it in [Zulip](https://servo.zulipchat.com/).

If you intend to work on this issue, then add `@servo-highfive: assign me` to your comment, and I'll assign this to you. :smile:

**Comment by Pazil24** [comment]
@servo-highfive: assign me

**Comment by servo-highfive** [comment]
Hey @Pazil24! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by richarddushime** [comment]
@servo-highfive : assign me

**Comment by servo-highfive** [comment]
It looks like this has already been assigned to someone. I'll leave the decision to a core contributor.

**Comment by Pazil24** [comment]
I am already working on this and found the lines in the code to edit this.
