### ISSUE TITLE
servoshell: make the mouse thumb buttons go back and forward

### ISSUE THREAD

**Issue by delan** [servo/servo#31655]
The lower thumb button should go back, and the upper thumb button should go forward. These buttons are sometimes known as “mouse4” and “mouse5”, “X1” and “X2”, or buttons 8 and 9.

The code that handles mouse input is in [Minibrowser::on_event](https://github.com/servo/servo/blob/f3a73dbed39c38c6581fc356d3d4f2d38c906e93/ports/servoshell/minibrowser.rs#L89-L111).

This may be a good [newcomer issue](https://github.com/servo/servo/labels/B-newcomer) once winit is upgraded to 0.29 (#31278).

**Comment by MunishMummadi** [comment]
I would like to work on this @servo-highfive assign me

**Comment by servo-highfive** [comment]
Hey @MunishMummadi! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by delan** [comment]
Hi @MunishMummadi, that would be great, but I would recommend waiting for the winit upgrade, otherwise we’ll have to deal with the platform-dependent button numbers for the thumb buttons.

**Comment by MunishMummadi** [comment]
Hi @delan I already came up with a solution. I will add some code snippets by tomorrow mrng. Could u please guide me . Gud night.

**Comment by MunishMummadi** [comment]
Hey

Hey @delan . My plan of action is do the changes to the following parts. And I am aware of the #31278 and I plan to wait until then.
1.Added MouseButton Import
2.Modified on_event Method
3.Added `trigger_back_action` and `trigger_forward_action` Methods
4.Adjusted `queue_embedder_events_for_minibrowser_events` Method

**Comment by MunishMummadi** [comment]
Hey @delan winit is upgraded to 0.29 . I would like to add the following implementation
```rust
pub fn on_event(&mut self, event: &winit::event::WindowEvent<'_>) -> EventResponse {
    let mut result = self.context.on_event(event);
    result.consumed &= match event {
        winit::event::WindowEvent::CursorMoved { position, .. } => {
            let scale = Scale::<_, DeviceIndependentPixel, _>::new(
                self.context.egui_ctx.pixels_per_point(),
            );
            self.last_mouse_position =
                Some(winit_position_to_euclid_point(*position).to_f32() / scale);
            self.last_mouse_position
                .map_or(false, |p| self.is_in_browser_rect(p))
        },
        winit::event::WindowEvent::MouseWheel { .. } => self
            .last_mouse_position
            .map_or(false, |p| self.is_in_browser_rect(p)),
        winit::event::WindowEvent::MouseInput { state, button, .. } => {
            // Check for button presses
            match button {
                winit::event::MouseButton::Other(code) => match (state, code) {
                    (winit::event::ElementState::Pressed, 8) => {
                        // Assuming "Other(8)" corresponds to "mouse4" or the back button
                        self.event_queue.borrow_mut().push(MinibrowserEvent::Back);
                        false // Event is consumed
                    },
                    (winit::event::ElementState::Pressed, 9) => {
                        // Assuming "Other(9)" corresponds to "mouse5" or the forward button
                        self.event_queue.borrow_mut().push(MinibrowserEvent::Forward);
                        false // Event is consumed
                    },
                    _ => true, // Other button presses are not consumed
                },
                _ => true, // Non-Other button events are not consumed
            }
        },
        _ => true, // All other events are not specifically handled here
    };
    result
}


```

**Comment by Nopey** [comment]
> MunishMummadi commented:
> Nopey, Should I wait for the merge to push a PR to the issue #31655

I think waiting makes sense, as it shouldn't take too long for #31278 to be unblocked.

I ran a build with the on_event impl you provided, and found it makes left click not follow links.
Could you check that MouseInput events are still handled correctly?

**Comment by MunishMummadi** [comment]
I get it now. It seems that the above `on_event` is consuming all `MouseInput` events, which is causing the issue where left clicks are not following links. To fix this, we need to modify the `MouseInput `event handling to only consume the specific button events we want to handle (in this case, the back and forward buttons) and let the other events pass through.
```rust
pub fn on_event(&mut self, event: &winit::event::WindowEvent<'_>) -> EventResponse {
    let mut result = self.context.on_event(event);

    result.consumed &= match event {
        winit::event::WindowEvent::CursorMoved { position, .. } => {
            let scale = Scale::<_, DeviceIndependentPixel, _>::new(
                self.context.egui_ctx.pixels_per_point(),
            );
            self.last_mouse_position =
                Some(winit_position_to_euclid_point(*position).to_f32() / scale);
            self.last_mouse_position
                .map_or(false, |p| self.is_in_browser_rect(p))
        },
        winit::event::WindowEvent::MouseWheel { .. } => self
            .last_mouse_position
            .map_or(false, |p| self.is_in_browser_rect(p)),
        winit::event::WindowEvent::MouseInput { state, button, .. } => 

            match button {
                winit::event::MouseButton::Other(code) => match (state, code) {
                    (winit::event::ElementState::Pressed, 8) => {
                        // Assuming "Other(8)" corresponds to "mouse4" or the back button
                        self.event_queue.borrow_mut().push(MinibrowserEvent::Back);
                        true 
                    },
                    (winit::event::ElementState::Pressed, 9) => {
                        // Assuming "Other(9)" corresponds to "mouse5" or the forward button
                        self.event_queue.borrow_mut().push(MinibrowserEvent::Forward);
                        true 
                    },
                    _ => false,
                },
                _ => false,
            }
        },
        _ => false,
    };

    result
}
```

**Comment by MunishMummadi** [comment]
Hey @delan as the #31278 got merged. I started working on this issue and I implemented the following code and I am not able to get the functionality. But my implementation see good to me. Can u share any insights on where I am going wrong.
```rust
use winit::event::{ElementState, MouseButton, WindowEvent};

    pub fn on_window_event(
        &mut self,
        window: &winit::window::Window,
        event: &winit::event::WindowEvent,
    ) -> EventResponse {
        let mut result = self.context.on_window_event(window, event);

        result.consumed &= match event {
            WindowEvent::CursorMoved { position, .. } => {
                let scale = Scale::<_, DeviceIndependentPixel, _>::new(
                    self.context.egui_ctx.pixels_per_point(),
                );

                self.last_mouse_position =
                    Some(winit_position_to_euclid_point(*position).to_f32() / scale);

                self.last_mouse_position
                    .map_or(false, |p| self.is_in_browser_rect(p))
            },
            WindowEvent::MouseWheel { .. } => self
                .last_mouse_position
                .map_or(false, |p| self.is_in_browser_rect(p)),
            WindowEvent::MouseInput { state, button, .. } => match (*state, *button) {
                (ElementState::Pressed, MouseButton::Other(8)) => {
                    self.event_queue.borrow_mut().push(MinibrowserEvent::Back);
                    true
                },
                (ElementState::Pressed, MouseButton::Other(9)) => {
                    self.event_queue
                        .borrow_mut()
                        .push(MinibrowserEvent::Forward);
                    true
                },
                _ => self
                    .last_mouse_position
                    .map_or(false, |p| self.is_in_browser_rect(p)),
            },
            _ => true,
        };

        result
    }
```

**Comment by Nopey** [comment]
I did a debug print of every window event that passed through that function, and it looks like winit doesn't report those mouse buttons as Other(8) and Other(9) anymore:
```
[ports\servoshell\minibrowser.rs:101] event = MouseInput {
    device_id: DeviceId(
        DeviceId(
            0,
        ),
    ),
    state: Pressed,
    button: Back,
}
```
Hope this helps.
p.s. Is it a good time to open a PR for your work on this?

**Comment by MunishMummadi** [comment]
thanks for the info. Give me some time, I will work on the issue. If I am unable to get functionality. I will tell you.

**Comment by Nopey** [comment]
The method `is_in_browser_rect` returns true if the position is inside the toolbar. This may be a bug, or may be a misnomer.
```rs
    /// Return true iff the given position is in the Servo browser rect.
    fn is_in_browser_rect(&self, position: Point2D<f32, DeviceIndependentPixel>) -> bool {
        position.y < self.toolbar_height.get()
    }
```

Circling back to the issue of mouse buttons Forward/Back, however-- I don't think we care where the mouse is when the event goes off. For precedent, both Firefox and Edge (the only two i checked) navigate when forward or back is pressed anywhere on the window! Both inside and outside the web viewport.

@MunishMummadi

**Comment by MunishMummadi** [comment]
based on your suggestion. we can change it to something like this and by fetching the window_size in the beginning of the function and using it in `is_in_browser_rect` 
```rust
    fn is_in_browser_rect(
        &self,
        position: Point2D<f32, DeviceIndependentPixel>,
        window_size: LogicalSize<f32>,
    ) -> bool {
        position.y < self.toolbar_height.get()
            && position.x >= 0.0
            && position.x <= window_size.width
    }
```
Is my understanding correct or you are suggesting something else. even the above change I am not able to get the functionality @Nopey

**Comment by Nopey** [comment]
My suggestion above is that we can entirely avoid calling is_in_browser_rect in the `MouseInput { button: MouseButton::Forward }` handling, leaving the current usage and behavior intact.

I'm opening an issue for the is_in_browser_rect stuff, will mention you there.
