### ISSUE TITLE
On Linux, add Noto fonts to fallback list for other languages

### ISSUE THREAD

**Issue by delan** [servo/servo#31664]
When a character isn’t supported by any of the fonts chosen by the page, some browsers search through all of the installed fonts to find one that supports text in that language (e.g. [Firefox](https://searchfox.org/mozilla-central/rev/109bb25545f0d2df31954dc0a9afbf30d900b6bb/gfx/thebes/gfxPlatformFontList.cpp#1086-1101)). Servo can’t do that yet, but we currently have hardcoded lists of “fallback fonts” that we try in those situations. There are separate lists for each platform, and on Linux, we use the list in [freetype/font_list.rs](https://github.com/servo/servo/blob/f3a73dbed39c38c6581fc356d3d4f2d38c906e93/components/gfx/platform/freetype/font_list.rs#L155-L169).

[Noto fonts](https://fonts.google.com/noto/use) are often installed by default on Linux distros like Ubuntu. We can use [char::script()](https://docs.rs/ucd/0.1.1/ucd/trait.Codepoint.html#tymethod.script) to check what [script](https://en.wikipedia.org/wiki/Script_(Unicode)) (language) the character is in.

1. Find an enum variant in [Script](https://docs.rs/ucd/0.1.1/ucd/tables/scripts/enum.Script.html) that also has a Noto font [according to this page](https://notofonts.github.io/)
2. In [this function](https://github.com/servo/servo/blob/f3a73dbed39c38c6581fc356d3d4f2d38c906e93/components/gfx/platform/freetype/font_list.rs#L155-L169), check if `codepoint` is in that script
3. If so, add the Noto Sans font name to the fallback list

For example, for [`Script::Adlam`](https://docs.rs/ucd/0.1.1/ucd/tables/scripts/enum.Script.html#Adlam.v) we can add “Noto Sans Adlam” to the fallback list:

![image](https://github.com/servo/servo/assets/465303/f287dc19-af7b-4357-a5d4-530e384f9dfa)

**Comment by richarddushime** [comment]
Hi @delan 
i would like to work on this 
can you assign it to me ?

**Comment by sandeepB3** [comment]
Hey @delan, I think none of the variants in [script](https://docs.rs/ucd/0.1.1/ucd/tables/scripts/enum.Script.html) fall into unicode plane 2, besides the function `is_cjk` primarily matches unicode blocks containing CJK Unified Ideographs Extension characters only.

**Comment by delan** [comment]
> Hey @delan, I think none of the variants in [script](https://docs.rs/ucd/0.1.1/ucd/tables/scripts/enum.Script.html) fall into unicode plane 2, besides the function `is_cjk` primarily matches unicode blocks containing CJK Unified Ideographs Extension characters.

I would expect most of those scripts to be in plane 0 (BMP) or plane 1 (SMP), but yeah, this would be separate to the is_cjk() check (if the character is CJK, add the CJK fonts, if the character is Adlam, add Noto Sans Adlam, and so on).

**Comment by jahielkomu** [comment]
Hello @delan , has this been addressed or I can have a go at it?
I see more fonts added to the list.
