### ISSUE TITLE
servoshell: add a spinner that indicates when the page is loading

### ISSUE THREAD

**Issue by delan** [servo/servo#31689]
When the minibrowser is enabled, add an [egui spinner](https://docs.rs/egui/0.22.0/egui/struct.Ui.html#method.spinner) to the location bar when the page is loading.

Watch for `EmbedderMsg::LoadStart`, `EmbedderMsg::HeadParsed`, and `EmbedderMsg::LoadComplete` events, and keep track of whether the page is currently loading in `Minibrowser`.

This may be a good [newcomer issue](https://github.com/servo/servo/labels/B-newcomer) once #31688 is fixed.

![image](https://github.com/servo/servo/assets/465303/43972751-7e99-43b5-90e6-5aa51bfc1024)

**Comment by frereit** [comment]
Darn, I forgot to leave a comment here that I started work on this, sorry. I hope this didn't lead to doubled work but I've done some work in #31713. If anyone else also worked on this, maybe let me know and we can discuss the issue in more detail 😄
