### ISSUE TITLE
servoshell: show a status bar tooltip when hovering over links

### ISSUE THREAD

**Issue by delan** [servo/servo#31690]
When the minibrowser is enabled, add an [egui tooltip](https://docs.rs/egui/0.22.0/egui/containers/popup/fn.show_tooltip_at.html) to the bottom left corner when the page has status text.

Watch for `EmbedderMsg::Status` events, and keep track of the current status value (including `None`) in `Minibrowser`. To get the y coordinate of the bottom edge, use `ui.cursor().max.y` in a block that has `ui`, such as [the TopBottomPanel show routine](https://github.com/servo/servo/blob/68b82e6d6133c8213cdad09b240d7a69227cc82a/ports/servoshell/minibrowser.rs#L146-L190).

![image](https://github.com/servo/servo/assets/465303/2b4ed3ac-ac59-4d01-b612-95317045db0f)

**Comment by rohansx** [comment]
hi @delan would like to take on this task

**Comment by delan** [comment]
Great! Feel free to add me as a reviewer if you open a pull request.

**Comment by MunishMummadi** [comment]
Hey i Have been working on this issue for a while. Sorry for not mentioning here. I propose the following change @delan . Correct me if I am wrong.

`TopBottomPanel::top("toolbar").show(ctx, |ui| {
    ui.allocate_ui_with_layout(
        ui.available_size(),
        egui::Layout::left_to_right(egui::Align::Center),
        |ui| {
            // Check if there is status text to show a tooltip for
            if let Some(status_text) = &minibrowser.status {
                // Calculate position for the tooltip at the bottom left corner
                let tooltip_position = ui
                    .cursor()
                    .set(egui::Pos2::new(ui.layout().screen_rect().left(), ui.layout().screen_rect().bottom()));

                // Show tooltip for status text
                egui::containers::popup::show_tooltip_at(&ctx, Id::new("status_tooltip"), Some(tooltip_position), |ui| {
                    ui.label(status_text);
                });
            }

            if ui.button("back").clicked() {
                event_queue.borrow_mut().push(MinibrowserEvent::Back);
            }
            if ui.button("forward").clicked() {
                event_queue.borrow_mut().push(MinibrowserEvent::Forward);
            }
            ui.allocate_ui_with_layout(
                ui.available_size(),
                egui::Layout::right_to_left(egui::Align::Center),
                |ui| {
                    if ui.button("go").clicked() {
                        event_queue.borrow_mut().push(MinibrowserEvent::Go);
                        location_dirty.set(false);
                    }

                    let location_field = ui.add_sized(
                        ui.available_size(),
                        egui::TextEdit::singleline(&mut *location.borrow_mut()),
                    );

                    if location_field.changed() {
                        location_dirty.set(true);
                    }
                    if ui.input(|i| {
                        i.clone().consume_key(Modifiers::COMMAND, Key::L)
                    }) {
                        location_field.request_focus();
                    }
                    if location_field.lost_focus() &&
                        ui.input(|i| i.clone().key_pressed(Key::Enter))
                    {
                        event_queue.borrow_mut().push(MinibrowserEvent::Go);
                        location_dirty.set(false);
                    }
                },
            );
        },
    );
    ui.cursor().min.y
});
`

**Comment by MunishMummadi** [comment]
Hey i Have been working on this issue for a while. Sorry for not mentioning here. I propose the following change @delan . Correct me if I am wrong.
```
TopBottomPanel::top("toolbar").show(ctx, |ui| {
    ui.allocate_ui_with_layout(
        ui.available_size(),
        egui::Layout::left_to_right(egui::Align::Center),
        |ui| {
            // Check if there is status text to show a tooltip for
            if let Some(status_text) = &minibrowser.status {
                // Calculate position for the tooltip at the bottom left corner
                let tooltip_position = ui
                    .cursor()
                    .set(egui::Pos2::new(ui.layout().screen_rect().left(), ui.layout().screen_rect().bottom()));

                // Show tooltip for status text
                egui::containers::popup::show_tooltip_at(&ctx, Id::new("status_tooltip"), Some(tooltip_position), |ui| {
                    ui.label(status_text);
                });
            }

            if ui.button("back").clicked() {
                event_queue.borrow_mut().push(MinibrowserEvent::Back);
            }
            if ui.button("forward").clicked() {
                event_queue.borrow_mut().push(MinibrowserEvent::Forward);
            }
            ui.allocate_ui_with_layout(
                ui.available_size(),
                egui::Layout::right_to_left(egui::Align::Center),
                |ui| {
                    if ui.button("go").clicked() {
                        event_queue.borrow_mut().push(MinibrowserEvent::Go);
                        location_dirty.set(false);
                    }

                    let location_field = ui.add_sized(
                        ui.available_size(),
                        egui::TextEdit::singleline(&mut *location.borrow_mut()),
                    );

                    if location_field.changed() {
                        location_dirty.set(true);
                    }
                    if ui.input(|i| {
                        i.clone().consume_key(Modifiers::COMMAND, Key::L)
                    }) {
                        location_field.request_focus();
                    }
                    if location_field.lost_focus() &&
                        ui.input(|i| i.clone().key_pressed(Key::Enter))
                    {
                        event_queue.borrow_mut().push(MinibrowserEvent::Go);
                        location_dirty.set(false);
                    }
                },
            );
        },
    );
    ui.cursor().min.y
});

```

**Comment by sandeepB3** [comment]
Hey @delan , I've drafted a PR outlining my approach and the changes I've made to the files. Although `./mach build -d` and `./mach test-tidy` don't report any errors, the expected functionality to display a status bar tooltip when hovering over links doesn't seem to work when the minibrowser is enabled to run any website. Could you please review my draft?

**Comment by rohansx** [comment]
Hi @delan so should i work on this issue or not?

**Comment by MunishMummadi** [comment]
hey  @delan @rohansx . I have spent significant amount of time for refactoring and debugging my approach. Can you provide me more time to resolve the issue.

**Comment by rohansx** [comment]
@MunishMummadi Please let me know how long will it take for you to raise the PR

**Comment by MunishMummadi** [comment]
Hey @rohansx . I am struggling with the issue. If you want to help me. I would really appreciate it.

**Comment by MunishMummadi** [comment]
Hey @rohansx . I raised a PR . There are issues in it. I would love to collaborate and work.

**Comment by MunishMummadi** [comment]
I am nearly done.

**Comment by iterminatorheart** [comment]
@delan since it has passed 2 weeks, can i work on this issue

**Comment by iterminatorheart** [comment]
now i have complete this problem, please have a look @delan  https://github.com/servo/servo/pull/32011，and looking forward to any feedback
