### ISSUE TITLE
Unable to build servo as vendored dependency

### ISSUE THREAD

**Issue by happybeing** [servo/servo#31812]
**Describe the bug:**
I need to build offline and have been trying to build vendored versions of first the wry servo demo, then verso (which supersedes that) and now servo as I suspect the issue is really with servo.

**To Reproduce:**
I opened an issue with verso [here](https://github.com/european-browser/verso/issues/17), which has more detail than I can provide in this issue about exactly what I'm doing and how to reproduce this. To reproduce with servo, follow the steps I documented there but with servo rather than verso, but in a nutshell...

- First, clone to a cloud server, install servo dependencies (`./mach bootstrap`) although on my server (Ubuntu 20.04) some of that fails so I can't try building there.

- Use `cargo vendor` to generate vendored sources and changes for `config.toml`

- Use `rsync` to copy the servo repo and vendored sources to my laptop (Ubuntu 22.04.04 LTS).

- Edit `servo/.cargo/config.toml` to use vendored sources and prevent `cargo` from going online to update anything.

- Finally `./mach build`

With `verso` I hit and fix some different errors that are to do with servo (noted in the issue linked above), but may only be happening because I'm trying to build a different project than servo itself.

With `servo` the vendored build seems to be hitting an unrelated issue, that is currently being discussed on the zulip chat [here](https://servo.zulipchat.com/#narrow/stream/263398-general/topic/Build.20Issues/near/427922798). That reports a failure to find `stdc++`. As that isn't to do with vendoring I can't say for sure that a vendored build of servo will fail if that is fixed, but I can't test it until that and any follow on build issues are working ok. Perhaps I'll try again in a while, but for now I need to move forward and look for an alternative to using servo to make a simple browser.

servo is a great project but unwieldy and not something I can work with in my off-grid/mobile broadband connection, as with such a large repo, it proves impossible to do the remote git operations I can and do routinely everywhere else so far. BTW I did a lot of investigating to try and fix those issues before trying the vendored approach, so don't worry about suggesting ways around that!

**Platform:**
Cloud server (used only to clone and vendor): Ubuntu 20.04
Laptop (for vendored build): Ubuntu 22.04.04 LTS
cargo 1.74.1 (ecb9851af 2023-10-18)
rustc 1.74.1 (a28077b28 2023-12-04)

**Comment by sagudev** [comment]
I used `cargo vendor`, then copied output in `.cargo/config.toml` and it worked normally. Maybe this happens when it's out of servo's tree (like verso), so I will test verso now.

**Comment by sagudev** [comment]
I hit `embedder_traits` error as you described in verso issue.

**Comment by sagudev** [comment]
I think general pattern of issues is that we use files that are not available in directory of crate, `cargo vendor` does only get crates folders so all `..`* path are invalid in this case. Soft links to such folders/files ensure that vendoring will include those folders too (so all `..`* paths are replaced with `.`).

**Comment by sagudev** [comment]
This would require symlinks to solve this nicely, and we do not want them yet. So this will be wontfix.

But it should be still possible to clone servo separately, then run `cargo vendor` in servo's tree, then in verso use servo by path in Cargo.toml.

**Comment by sagudev** [comment]
> Thanks for looking into this.
> 
> > But it should be still possible to clone servo separately, then run cargo vendor in servo's tree, then in verso use servo by path in Cargo.toml.
> 
> Do you mean you plan to make that work, or that it should already work?

That should already work, but I did not test it.

**Comment by happybeing** [comment]
OK. The issue is still open (https://github.com/european-browser/verso/issues/17) so I'll leave it for now.
