### ISSUE TITLE
Consistent string formatting in `CodegenRust.py`

### ISSUE THREAD

**Issue by eerii** [servo/servo#31846]
**Describe the new feature:**
`CodegenRust.py` currently uses all types of python [string formatting](https://docs.python.org/3/tutorial/inputoutput.html) (`+`, `%`, `.format`, `f""`...) as a result of many years of development. It would be nice to make the code consistent and have a guideline for which method to use in each case. Per the discussion [here](https://github.com/servo/servo/pull/31844#issuecomment-2016769923), both @sagudev and I think that [f strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) are a good candidate since they are similar to rust and python is moving in that direction. What does everyone else think?

**Comment by sagudev** [comment]
cc @jdm @mrobinson
