### ISSUE TITLE
Handle HTTP Error 413: Request Entity Too Large more gracefully.

### ISSUE THREAD

**Issue by sagudev** [servo/servo#31845]
WPT import currently fails because of it: https://github.com/servo/servo/actions/runs/8405500156/job/23018617126#step:8:14419 and I've hit this when doing webgpu tests too. Ideally if too large we should split it into multiple request.

**Comment by mrobinson** [comment]
It seems this is an issue when sending the output to the intermittent dashboard. I think a simple solution here would be to truncate the output.

**Comment by nishchay-veer** [comment]
Is this issue still there? If yes, I would like to work on this. Can you please assign this to me @sagudev

**Comment by sagudev** [comment]
While this issue is not blocking WPT imports anymore, it's still present although in more edge cases now with #31895. I think more adaptive solution would be better (ideally filtering should never fail) in worst case we couldd fallback to sending empty result.message. How does that sound @mrobinson?

**Comment by mrobinson** [comment]
I think the first step is getting to bottom of what part of the filtering process is hitting the limits and then going from there. It's quite likely that we just need to limit the data that we send to the server or between GitHub Actions jobs.

**Comment by sagudev** [comment]
Somehow related, I use https://github.com/servo/servo/commit/4a8ef8bd5d1fb52dc37b6216d04de09aceea9568 for webgpu runs to make output shorter to actually get results (webgpu test are very very verbose)

**Comment by sagudev** [comment]
This is happening again in WPT imports: https://github.com/servo/servo/actions/runs/10127480976/job/28008249936#step:8:13250

**Comment by sagudev** [comment]
> fallback to sending empty result.message

I think we should do this (as they are not needed for ident, right?).
