### ISSUE TITLE
Script task should maintain a consistent view of layout

### ISSUE THREAD

**Issue by zwarich** [servo/servo#3187]
As discussed on [dev-servo](https://groups.google.com/d/msg/mozilla.dev.servo/fpY49KCQ_64/0Mq7fnn4OMIJ), the script task needs to maintain a consistent view of layout. The suggestion from the discussion is that the script task hold a layout lock until the turn of the script task's event loop.

**Comment by mrobinson** [comment]
I think this isn't relevant any longer now that script and layout run in the same thread.
