### ISSUE TITLE
`--timeout-multiplier` does not affect test harness timeout

### ISSUE THREAD

**Issue by sagudev** [servo/servo#31919]
As noted in https://github.com/servo/servo/pull/31772#issuecomment-2022523518, I also got conformation on WPT's matrix chat room.

**Comment by sagudev** [comment]
I think timeout-multiplier is completely broken. I used `--timeout-multiplier 10` and did console.log for every timeout_multiplier and I always got `1` instead of `10`.

**Comment by sagudev** [comment]
I believe our `testharnessreport-servo.js` needs update:
```patch
diff --git a/tests/wpt/tests/tools/wptrunner/wptrunner/testharnessreport-servo.js b/tests/wpt/tests/tools/wptrunner/wptrunner/testharnessreport-servo.js
index 4a27dc27ef..d6616739e6 100644
--- a/tests/wpt/tests/tools/wptrunner/wptrunner/testharnessreport-servo.js
+++ b/tests/wpt/tests/tools/wptrunner/wptrunner/testharnessreport-servo.js
@@ -1,4 +1,9 @@
-var props = {output:%(output)d, debug: %(debug)s};
+var props = {
+    output:%(output)d,
+    timeout_multiplier: %(timeout_multiplier)s,
+    explicit_timeout: %(explicit_timeout)s,
+    debug: %(debug)s
+};
 var start_loc = document.createElement('a');
 start_loc.href = location.href;
 setup(props);
```

@jdm do you remember why exactly we we override testharnessreport with our own?

**Comment by jdm** [comment]
I'm pretty sure it was some kind of unsupported feature that prevented running tests correctly when we first got wor set up?
