### ISSUE TITLE
Update the rendering: fix ordering of documents

### ISSUE THREAD

**Issue by gterzian** [servo/servo#32004]
Follow-up to https://github.com/servo/servo/pull/31505

See step two of [spec](https://html.spec.whatwg.org/multipage/#update-the-rendering), and https://github.com/servo/servo/pull/31505/files#diff-2c5948584719622eef023c56cdf90e8278971f2f2eda26e7fd0485a24c32be3cR1735

I've tried doing this in https://github.com/servo/servo/pull/31505/commits/fa48454f64f01ceff17a6959c170914d46586da4, but this resulted in various unexpected test results(which I didn't note, sorry), and so it will require some further investigation. Note that our current implementation does not order docs in any way, since it usually simply handles a message immediately when received by the script-thread.

**Comment by gterzian** [comment]
There is a very good test for this: https://github.com/servo/servo/blob/cbc9304c2002fb0d5c8cdade39eddfe117b12053/tests/wpt/tests/html/webappapis/update-rendering/child-document-raf-order.html#L4

**Comment by gterzian** [comment]
And the fix consists of ordering the list of documents at https://github.com/servo/servo/blob/cbc9304c2002fb0d5c8cdade39eddfe117b12053/components/script/script_thread.rs#L1646

This could be achieved I think using two steps:

1. First filter all the top-level docs, using `document.window().is_top_level()`. 
2. For each top-level, properly order the nested iframes using https://github.com/servo/servo/blob/cbc9304c2002fb0d5c8cdade39eddfe117b12053/components/script/dom/document.rs#L2668

The parents can be ordered in any way, but the iframes need to be order with respect to their parent, and each other.

**Comment by gterzian** [comment]
Finally, when the test passes, the META file for the FAIL can be removed from: https://github.com/servo/servo/blob/cbc9304c2002fb0d5c8cdade39eddfe117b12053/tests/wpt/meta/html/webappapis/update-rendering/child-document-raf-order.html.ini

**Comment by Taym95** [comment]
@gterzian 

I tried this but the test is timing out

```
        let pipeline_and_docs: Vec<(PipelineId, DomRoot<Document>)> = self
            .documents
            .borrow()
            .iter()
            .filter(|(_, document)| document.window().is_top_level())
            .map(|(id, document)| (id, DomRoot::from_ref(&*document)))
            .flat_map(|(id, document)| {
                document.iter_iframes().map(move |iframe| (id, document_from_node(&*iframe)))
            })
            .collect();
  ```

**Comment by mrobinson** [comment]
It seems `/html/webappapis/update-rendering/child-document-raf-order.html` is now a flaky test.

**Comment by gterzian** [comment]
Thanks for the note @mrobinson, I assume this will be investigated as part of https://github.com/servo/servo/issues/33010
