### ISSUE TITLE
Implement Page Visibility

### ISSUE THREAD

**Issue by gterzian** [servo/servo#32062]
Spec: https://html.spec.whatwg.org/multipage/interaction.html#page-visibility

There are at least two places where we could run the [`update-the-visibility-state`](https://html.spec.whatwg.org/multipage/interaction.html#update-the-visibility-state) steps:

When the document loads: 

https://github.com/servo/servo/blob/10ec8565eaa0e9e86d3a6506ab1e83d5a41f51c8/components/script/dom/document.rs#L695

Which would match: https://html.spec.whatwg.org/multipage/browsing-the-web.html#updating-the-document:update-the-visibility-state

And when the document unloads:

https://github.com/servo/servo/blob/10ec8565eaa0e9e86d3a6506ab1e83d5a41f51c8/components/script/dom/document.rs#L2221

which would match: https://html.spec.whatwg.org/multipage/document-lifecycle.html#unloading-documents:update-the-visibility-state

**Comment by wusyong** [comment]
I tried to see how firefox does and it seems it has a lot [consideration ](https://searchfox.org/mozilla-central/source/dom/base/Document.cpp#7935)on this step. Do we need to keep these things in ming as well.
Also, the spec has a confusing description in step 6, I'm not sure how to implement it actually.
