### ISSUE TITLE
(Bug) The Soundcloud website crash the renderer

### ISSUE THREAD

**Issue by hardBSDk** [servo/servo#32072]
## How to reproduce:

- Access the `https://soundcloud.com` website

## Information

- Binary date - 13-04-2024
- OS - Fedora 39

**Comment by mrobinson** [comment]
Can you post a stack trace for the renderer crash?

**Comment by hardBSDk** [comment]
@mrobinson How to obtain that?

**Comment by jdm** [comment]
It seems like the page content has changed since this was filed; I don't see a crash on macOS, but 95% of the page content is missing in Servo. I'm going to go ahead and close this issue, since this lacks any additional detail.
