### ISSUE TITLE
(Bug) Clark Moody Bitcoin Dashboard is not completely rendered

### ISSUE THREAD

**Issue by hardBSDk** [servo/servo#32076]
![image](https://github.com/servo/servo/assets/55782009/4e6bc8b2-843b-41e7-8eef-6b60fb131101)

## How to reproduce

- Access the `https://bitcoin.clarkmoody.com/dashboard/` website

## Information

- Binary date - 13-04-2024
- OS - Fedora 39

**Comment by mrobinson** [comment]
Thanks for filing this bug, but it isn't super useful without a minimized test case or screenshots. Servo is still lacking many features (fully implemented flexbox, grid, etc), so it's natural that the layout of some sites is broken. If you are interested in digging into this failure a bit and adding debugging information we could reopen this issue and start working on things -- but many sites are broken and we can't have a bug for every broken site at the moment.
