### ISSUE TITLE
WPT Import fails

### ISSUE THREAD

**Issue by sagudev** [servo/servo#32168]
https://github.com/servo/servo/actions/runs/8865818832/job/24343044922#step:8:2419

I suspect it's from https://github.com/web-platform-tests/wpt/pull/45848

> ▶ TIMEOUT [expected OK] /fetch/api/crashtests/huge-fetch.any.html

but it only happens when doing flaky detection (could be that python does not run GC and when we run [huge-response.py](https://github.com/web-platform-tests/wpt/pull/45848/files#diff-9e54b6b9e7d378d95a21ed28dc1b545a3133fba9f73d7052ded0b7e104737eaf) for the second time we get OOM).

Temporary solution could be to just disable running this test.

**Comment by mrobinson** [comment]
> Temporary solution could be to just disable running this test.

This seems reasonable to me.
