### ISSUE TITLE
Page load failure in security_location_0.sub.htm

### ISSUE THREAD

**Issue by jdm** [servo/servo#3219]
```
3:50.02 TEST_START: Thread-TestrunnerManager-1 /html/browsers/history/the-location-interface/security_location_0.sub.htm

3:50.56 PROCESS_OUTPUT: Thread-TestrunnerManager-1 "task 'ScriptTask' failed at 'Failed to load page URL http://www.localhost:8000/, error: unknown error', /Users/travis/build/servo/servo/src/components/script/dom/htmlbuttonelement.rs:53" (pid:23025 command:/Users/travis/build/servo/servo/build/servo --hard-fail http://localhost:8000/html/browsers/history/the-location-interface/security_location_0.sub.htm)

3:50.56 PROCESS_OUTPUT: Thread-TestrunnerManager-1 "Pipeline failed in hard-fail mode. Crashing!" (pid:23025 command:/Users/travis/build/servo/servo/build/servo --hard-fail http://localhost:8000/html/browsers/history/the-location-interface/security_location_0.sub.htm)
```

I'm not sure what result is expected with the odd URL `www.localhost:8000`. This deserves investigating what the test is actually trying to do; perhaps we're just too eager to fail everything when something goes wrong.

**Comment by shinglyu** [comment]
Hmm, I made it compiled. But I don't know where I should write the tests. It involves the following step to test it:
1. Create a hostfile with entries like `localhost 127.0.0.1`.
2. Create a environment variable `HOST_FILE` to point to the hostfile.
3. Open http://localhost to see if it goes to http://127.0.0.1

I don't know in which part of the testing harness can I use to test this.  Thanks.

**Comment by shinglyu** [comment]
I tried manually test this, by replacing http://web1.localhost.test to http://www.google.com. However, I encounter the following error:
https://gist.github.com/shinglyu/3335a8db8dead142e651
Notice that the host seems to be replaced. But there is a `HttpIoError(Name or service not known)`. Can you help me identify the problem? Thanks.

**Comment by shinglyu** [comment]
Ignore my second question. I forgot to trim the tailing newline.

**Comment by jdm** [comment]
Here's one way to do the test - separate the code that reads the host file into a function that stores the result in a mutable global, and call that when Servo is initializing at app startup. In the test, call the method with the required test host, start a TCP server on the right port, and make an HTTP request to 127.0.0.1. When the server receives a connection, that is the success case for the test. Does that make sense?

**Comment by shinglyu** [comment]
Yes that makes sense, but does it fit into any existing test? Or should I write one myself and put it in the `tests` dir? 

And what do you mean by "app startup"? I don't really know where is the entry point of the servo code. Do you suggest that I load the hostfile at startup, and replace the host by referencing the mutable global?

**Comment by jdm** [comment]
I think this should just be a function annotated #[test] in resource_task.rs; I don't believe we have any similarly complicated ones (the other loaders have some tests for their specific behaviour). Our other app initialization bits live in http://mxr.mozilla.org/servo/source/components/servo/lib.rs#69 . And yes, I think initializing the hostfile at startup would be better than doing it for every request.

**Comment by shinglyu** [comment]
OK. So let me clarify this. What I am gonna do is:
1. Split the hostfile code into [load and parse hostfile] + [replace the host if possible]
2. I'll create a #[test] to test the [replace the host if possible] part in `resouce_task.rs`
3. Move the [load and parse hostfile] part to `components/servo/lib.rs#69`
4. I test the [load and parse hostfile] part with a local TCP server (this part doesn't go into the codebase)
5. File another issue to add this `HOST_FILE` configuration into the `security_location_0.sub.htm` test, so it can run on the CI machines without editing the actual hostfile in use.

**Comment by jdm** [comment]
We should be able to have an automated test for step 4; we can write a function marked #[test] that calls the function to load the hostfile, starts the resource task, starts a local TCP server on port 4000, and makes a request for http://127.0.0.1:4000. If the server sees a connection, the test can finish by stopping the server.

**Comment by shinglyu** [comment]
I thought those are unit tests, should we do a file system access in an unit test?

**Comment by jdm** [comment]
No need for filesystem access. We can have a method that takes a string in the hostfile format and parses it, which can be used by the unit test, and the app initialization code can read a file and call the method with the contents.

**Comment by shinglyu** [comment]
Ah I see, thanks.

**Comment by shinglyu** [comment]
Hmm... I found this error, but I can't figure out why.
Code is here: https://github.com/shinglyu/servo/blob/bug3219/components/net/resource_task.rs#L233
And the error message:
```
   Compiling net v0.0.1 (file:///home/shinglyu/workspace/servo/components/servo)
resource_task.rs:233:44: 233:57 error: `load_data.url` does not live long enough
resource_task.rs:233         if let Some(ip) = host_table.get(&(load_data.url.domain().unwrap())) {
                                                                ^~~~~~~~~~~~~
resource_task.rs:225:92: 238:2 note: reference must be valid for the anonymous lifetime #1 defined on the block at 225:91...
resource_task.rs:225 pub fn replace_hosts(mut load_data: LoadData, host_table: HashMap<&str, &str>) -> LoadData {
resource_task.rs:226     /* TODO: move this to init code
resource_task.rs:227     let path = Path::new(host_file_path);
resource_task.rs:228     let mut file = BufferedReader::new(File::open(&path));
resource_task.rs:229     let lines: Vec<String> = file.lines().map(|x| x.unwrap()).collect();
resource_task.rs:230     */
                     ...
resource_task.rs:225:92: 238:2 note: ...but borrowed value is only valid for the block at 225:91
resource_task.rs:225 pub fn replace_hosts(mut load_data: LoadData, host_table: HashMap<&str, &str>) -> LoadData {
resource_task.rs:226     /* TODO: move this to init code
resource_task.rs:227     let path = Path::new(host_file_path);
resource_task.rs:228     let mut file = BufferedReader::new(File::open(&path));
resource_task.rs:229     let lines: Vec<String> = file.lines().map(|x| x.unwrap()).collect();
resource_task.rs:230     */
                     ...
error: aborting due to previous error
```
Many thanks in advance.

**Comment by jdm** [comment]
It's probably because unwrap takes self by value. Try moving load_data.url into a let binding on the previous line.

**Comment by jdm** [comment]
Alternatively, maybe `host_table.get(load_data.url.domain().as_ref().unwrap())` would work.

**Comment by shinglyu** [comment]
No luck. Both method still complains that `load_data.url` doesn't live long enough. Maybe I take `url: String` as input and return a `String`, and do the replacement in the `load()` function?

**Comment by shinglyu** [comment]
Doesn't work either :(, seems like `host_table.get()` doesn't work well with it.

**Comment by jdm** [comment]
Actually, for the code you linked, could you do:
```rust
if let Some(ref h) = load_data.url.domain_mut() {
    if let Some(ip) = host_table.get(h) {
```

**Comment by shinglyu** [comment]
It says
```
resource_task.rs:233:42: 233:43 error: mismatched types: expected `&&str`, found `&mut &mut collections::string::String` (values differ in mutability)
resource_task.rs:233         if let Some(ip) = host_table.get(h) {
                                                              ^
```
So I tried 
```
232     if let Some(ref mut h) = load_data.url.domain_mut() {
233     ¦   if let Some(ip) = host_table.get(&h.as_slice()) {
234     ¦   ¦   **h = ip.into_string();
235     ¦   }
236     }
```
And I bumped into the `load_data.url` (line 232) not live long enough error again.

**Comment by shinglyu** [comment]
I tried to change the `HashMap` to `HashMap<String, String>`, and get something that look more promising:

```
232     if let Some(h) = load_data.url.domain_mut() {
233     ¦   if let Some(ip) = host_table.get(h) {
234     ¦   ¦   h = ip;
235     ¦   }   
236     }   
```

```
resource_task.rs:234:17: 234:19 error: mismatched types: expected `&mut collections::string::String`, found `&collections::string::String` (values differ in mutability)
resource_task.rs:234             h = ip;
                                     ^~
```

**Comment by jdm** [comment]
Yes, that does look more useful. Try `*h = ip.clone()` perhaps?

**Comment by shinglyu** [comment]
Yeah, finally get it compiled. But I can't figure out how to expose global mut from `main` to `resource_tasks.rs`. I am thinking about adding a `static mut host_table = HashMap::new()` to the `components/servo/main.rs` file and use it in `resource_task.rs` by `extern crate servo`, but the comiler complains it can't find `servo` crate. Am I missing anything here?

**Comment by jdm** [comment]
Yes, the `servo` crate depends on the `net` crate, so that won't work. I would just add a public api like `global_init()` to the `net` crate, then use `net::global_init()` from `main`.

**Comment by shinglyu** [comment]
I get it compiled. But when I run with HOST_FILE env variable set, servo crashed with return value -4. I guess this line breaks it:
https://github.com/shinglyu/servo/blob/bug3219/components/net/resource_task.rs#L277

Something must have went wrong when I set the global in the `global_init()` at line 38. But I can't figure out how to debug it with gdb. I checked the Debugging page in the wiki but the instruction is too brief for me to understand. Can you kindly help? Thanks.

**Comment by jdm** [comment]
You can use `./mach run --debug file.html`, I believe, or `gdb --args components/servo/target/servo page.html`.

**Comment by jdm** [comment]
Instead of storing a pointer to a HashMap, why not store the HashMap directly?

**Comment by jdm** [comment]
Rather, I mean Option<HashMap>, which will allow you to initialize it with None.

**Comment by shinglyu** [comment]
I did tried to use a HashMap directly, but there was an error saying "mutable statics are not allowed to have destructors". 

Using `Option<HashMap>` gives the same error: 

```
resource_task.rs:36:58: 36:62 error: mutable statics are not allowed to have destructors
resource_task.rs:36 static mut HOST_TABLE: Option<HashMap<String, String>> = None;
                                                                             ^~~~
```

Or maybe I save the file content as string in the global, and parse it everytime I needs it. I guess the overhead is marginal for a typical hostfile.

**Comment by jdm** [comment]
@shinglyu Darn. Here's my next suggestion, then - `Option<*mut HashTable<String, String>>`, and have `global_init` make a `Box<HashTable<String, String>>` and transmute it to `*mut HashTable<String, String>`. That should fix the lifetime problems you saw, since the Box will ensure that the value never disappears.

**Comment by shinglyu** [comment]
Oh cool! Thank you for all the suggestions, there are so many tips and tricks!

**Comment by kmcallister** [comment]
Sounds like a use case for [lazy-static](https://github.com/Kimundi/lazy-static.rs).

**Comment by shinglyu** [comment]
Cool! Let's see if I can use lazy-static and refactor the code at the same
time.

**Comment by nox** [comment]
Can't find security_location_0.sub.htm anymore.
