### ISSUE TITLE
[Pushed Submodule] - A submodule was pushed to remote

### ISSUE THREAD

**Issue by sandramsc** [servo/servo#32219]
**Describe the bug:**
Not too clear if this was intentional, however a submodule was pushed to the remote main branch (folder with an arrow unable to open and navigate in remote). If one were to navigate to the directory with the arrow and tried to view hidden files, you'd see a **. git** folder, indicating that it is a repository. This means that it is a repository contained inside the outer repository that had pushed to GitHub. 

**To Reproduce:**
1. Navigate to the main repository [servo/servo](https://github.com/servo/servo)
2. Locate the directory **shell.nix**

**Desired Solution:**
If the shell.nix directory is one that contributors should be able to navigate in the remote repo, then the **.git** folder should be removed.

**Sugested steps to fix:**

1. git clone --depth 100 https://github.com/servo/servo.git
2. cd servo
3. cd shell.nix
4. git rm -rf .git
5. git rm --cached path_to_submodule

**Screenshots:**
![servo issue](https://github.com/servo/servo/assets/19821445/970e9635-99cf-4855-bbfc-c760a9db6d8c)

**Comment by syvb** [comment]
`shell.nix` isn't a submodule, it's a symlink (GitHub shows them similarly in the UI). It's there so you can do `nix-shell` in the root directory.

**Comment by mrobinson** [comment]
I think I'm going to close this one as `shell.nix` is indeed a symlink and I'm pretty sure that is intentional.
