### ISSUE TITLE
open space calibrator  openvr error: hmd  not found

### ISSUE THREAD

**Issue by tracylrds** [servo/servo#32221]
**Describe the bug:**
A clear and concise description of the bug.

**To Reproduce:**
Steps to reproduce the behavior.

**Platform:**
Specify OS, distribution, and hardware platform.

**Comment by tracylrds** [comment]
windows 11 pro

**Comment by tracylrds** [comment]
im trying to connect my vive trackers to my quest 2 thru steam vr but i am getting this runtime error that the openvr  error hmd not found (108) is the error message

**Comment by jdm** [comment]
Can you be more specific about how this is related to Servo? Is there a webpage involved somehow?

**Comment by jdm** [comment]
No response.
