### ISSUE TITLE
Add pref for wgpu backend

### ISSUE THREAD

**Issue by sagudev** [servo/servo#32390]
WGPU has env vars: https://github.com/gfx-rs/wgpu?tab=readme-ov-file#environment-variables

Firefox has these prefs:
![slika](https://github.com/servo/servo/assets/16504129/0a20e5da-6b4f-4325-9873-f81ba1ca5e6b)

We need at least one for backend selection.

Steps:
Add `dom.webgpu.wgpu-backend` pref to https://github.com/servo/servo/blob/42061ccafe67ac0440886e48e17a02f8b60525bc/components/config/prefs.rs#L206
Use https://docs.rs/wgpu-core/latest/wgpu_core/instance/fn.parse_backends_from_comma_list.html to parse pref value and put it in https://github.com/servo/servo/blob/42061ccafe67ac0440886e48e17a02f8b60525bc/components/webgpu/wgpu_thread.rs#L94

Testing:
Testing can be done by enabling logging in wgpu with `RUST_LOG=wgpu` and requested adapter should match backend that is set by the pref.

Here is demo webgpu site: https://demo.servo.org/experiments/webgpu-game-of-life/

`dom.webgpu.enabled` should also be enabled when testing.

**Comment by hieudo-dev** [comment]
Hi @sagudev, i'm a newcomer here looking to make my first contribution to servo. I'd love to give this one a try if it's not assigned already😁

**Comment by sagudev** [comment]
> Hi @sagudev, i'm a newcomer here looking to make my first contribution to servo. I'd love to give this one a try if it's not assigned already😁

Sure, I've assigned you.
