### ISSUE TITLE
Docs are not built for libservo

### ISSUE THREAD

**Issue by delan** [servo/servo#32412]
[The docs for libservo](https://doc.servo.org/servo/) are shadowed by the docs for servoshell’s bin crate, because they both have the crate name “servo”, and cargo currently has no way of disambiguating this (rust-lang/cargo#6313). We could:

- Rename libservo from `servo` to `libservo` (#29878)
- Rename servoshell(bin) from `servo` to `servoshell`, accepting that the binary name will change
  - servoshell is probably a well-enough-known name at this point
  - This is not unusual among our peers (e.g. [content_shell](https://chromium.googlesource.com/chromium/src/+/028b6a9755c6428424d2a43323c23604aa4c9218/docs/testing/web_tests_in_content_shell.md#As-a-simple-browser), [minibrowser](https://trac.webkit.org/wiki/BuildingGtk?version=145#Runningfromgit))
- Rename servoshell(bin) from `servo` to `servoshell`, while keeping the binary name as `servo`
  - This either requires a post-build step in mach, or RUSTC_BOOTSTRAP=1 + [different-binary-name](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#different-binary-name)
- Disable doc output for servoshell(bin) somehow?
  - No docs would be lost by doing this, because servoshell(bin) is just a stub ([#31439](https://github.com/servo/servo/pull/31439))

**Comment by wusyong** [comment]
I'm actually fine with any option as long as we can fix the conflict.
Last time I opened the PR, it seems we don't want to change the name of core servo library crate.
Renaming bin also brought some issues like you mentioned.
I think disabling the doc of Servoshell is probably the best. And we can add an option for `./mach doc` to build it.

**Comment by wusyong** [comment]
Looks like we just need to add `--lib`. Both `servoshell` and `libservo` will be documented.
