### ISSUE TITLE
mach doc hangs and eventually crashes on wgpu-core(doc)

### ISSUE THREAD

**Issue by delan** [servo/servo#32413]
The hang also happens locally, not sure about the crash.

- Last good build: <https://github.com/servo/servo/actions/runs/8837709219>
- First bad build: <https://github.com/servo/servo/actions/runs/8845098367>

**Comment by delan** [comment]
Looks like there’s currently no way to skip a dependency in cargo doc (rust-lang/cargo#4049).

**Comment by delan** [comment]
First bad build is the bump to 0.19.0 (#31995). No obvious related issues in upstream repo, but I found a [comment in gfx-rs/wgpu#3626](https://github.com/gfx-rs/wgpu/pull/3626#issuecomment-1679877134) and associated rustdoc issue (rust-lang/rust#114891) that may explain it.

**Comment by sagudev** [comment]
I am aware of the issue for quiet some time (but forgot to open issue), but new rust version helps (it's slow but at least it doesn't hang), so this is basically waiting for https://github.com/servo/servo/pull/32217 to be resolved.

**Comment by sagudev** [comment]
It works: https://github.com/servo/servo/actions/runs/9328694891/job/25680171607

**Comment by mrobinson** [comment]
Ideally, we wouldn't need to build rustdoc for dependencies and those links would just go to docs.rs.
