### ISSUE TITLE
Absorb run.sh/run.py into  mach

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#3241]
Once #3230 lands, we should run wpt directly from the mach code in `python/` instead of from `run.sh` and `run.py`

**Comment by Ms2ger** [comment]
glandium pointed me at <https://mxr.mozilla.org/mozilla-central/source/python/mach_commands.py#27>.

**Comment by Manishearth** [comment]
That sounds useful, thanks!

**Comment by frewsxcv** [comment]
I don't think these files exist anymore, so this can probably be closed
