### ISSUE TITLE
Enable gl(es) backend in wgpu

### ISSUE THREAD

**Issue by sagudev** [servo/servo#32421]
Enable [`gles`](https://github.com/gfx-rs/wgpu/blob/c7458638d14921c7562e4197ddeefa17be413587/wgpu-core/Cargo.toml#L92) feature on wgpu-core for linux and windows in https://github.com/servo/servo/blob/main/components/webgpu/Cargo.toml

Add `gl_hub` to https://github.com/servo/servo/blob/dc0ba03d6816a3a2f2d9eff55c67af3daf3e96e6/components/script/dom/identityhub.rs#L58 and make sure all methods in this file also account for gl_hub (take look at vk_hub that has same cfgs).

Test with `RUST_LOG=wgpu ./mach run --release --pref dom.webgpu.enabled --pref dom.webgpu.wgpu_backend="gl" https://demo.servo.org/experiments/webgpu-game-of-life/`

**Comment by hieudo-dev** [comment]
Hey @sagudev, do you mind if I give this a try ? 
I feel like this will require a bit of research since I'm not very experienced with graphics API yet but I think it should be doable. Let me know what you think

**Comment by sagudev** [comment]
> Hey @sagudev, do you mind if I give this a try ? I feel like this will require a bit of research since I'm not very experienced with graphics API yet but I think it should be doable. Let me know what you think

Sure, although I think this should be pretty easy job with some rust knowledge, just enabling feature and following pattern of vk_hub in identityhub.rs

**Comment by hieudo-dev** [comment]
> Sure, although I think this should be pretty easy job with some rust knowledge, just enabling feature and following pattern of vk_hub in identityhub.rs

Oh gotcha, should be relatively simple then. Still I'd like to dig around a little big while i'm working on it because I'd love to learn more about the topic. It can take me some extra time to close this issue so I hope that's ok.

**Comment by sagudev** [comment]
> > Sure, although I think this should be pretty easy job with some rust knowledge, just enabling feature and following pattern of vk_hub in identityhub.rs
> 
> Oh gotcha, should be relatively simple then. Still I'd like to dig around a little big while i'm working on it because I'd love to learn more about the topic. It can take me some extra time to close this issue so I hope that's ok.

Ok, here is some docs about wgpu ids/hubs: https://github.com/gfx-rs/wgpu/blob/e7a528b62b20f0036721237715a8f7f74c11f401/wgpu-core/src/hub.rs#L1
