### ISSUE TITLE
Text rendering issue in servo.org footer

### ISSUE THREAD

**Issue by atouchet** [servo/servo#32459]
**Describe the bug:**
Text in the servo.org footer isn't rendered correctly.

Image:
![Untitled-2](https://github.com/servo/servo/assets/26315797/00533393-90a6-4f67-97a8-fb8cf2dfb51e)

**To Reproduce:**
Load https://servo.org/ and scroll to the bottom of the page.

**Platform:**
Windows 10 x86-64

**Comment by atouchet** [comment]
After some more testing I've found that the issue doesn't occur 100% of the time on new page loads. Also as far as I can tell the first build I've been able to reproduce the issue is 2024-04-23.

Regression range: https://github.com/servo/servo/compare/025a98773223412edd8a0032a44c60ee84d69eee...7ca920927c7e5f25e59557f825c4774381750e01

**Comment by atouchet** [comment]
There is a font initialization PR in that range that may be related: #32127

cc @mukilan

**Comment by atouchet** [comment]
I am not sure what triggers it but I just tried the latest nightly build and the text looked fine on the initial load. However if I closed Servo and relaunched it the text issues would show up on every subsequent page load.

**Comment by mrobinson** [comment]
@atouchet Can you try running Servo with the fix from #32499 applied and report on your results?

**Comment by mrobinson** [comment]
Update, #32499 is now merged, so maybe you can just try on the latest from main @atouchet? Thankyou!

**Comment by atouchet** [comment]
I just tested the lightest nightly build (2024-06-18) which includes 982a6d33818ceb5f19d9baf94f32f0607ca979ed and unfortunately the problem doesn't appear to be fixed. It took a few page reloads to run into the issue this time but the text rendering problem is still there.

**Comment by atouchet** [comment]
I've found another instance of weird text rendering on https://duckduckgo.com/ I'm not 100% sure if this is the exact same issue or not.

![Untitled-1](https://github.com/servo/servo/assets/26315797/d50d5871-7f13-4777-a3c7-f7c7e92b7335)

There appears to be problems with the subpixel rendering. Bright red and teal colours show up in certain words and letters. Strangely only some of them are displayed like this.

**Comment by mukilan** [comment]
Is [this](https://github.com/servo/servo/pull/33045) PR a potential fix for this issue?

**Comment by crbrz** [comment]
Without the change in https://github.com/servo/servo/pull/33045 I can reproduce consistently the rendering issue in https://servo.org footer when testing with a local copy (I used https://addons.mozilla.org/en-US/firefox/addon/single-file/ in Firefox to save the page). When testing with the online version of the page the issue occurs intermittently. The text in footer is rendered correctly after applying the change in https://github.com/servo/servo/pull/33045.

For https://duckduckgo.com the rendering issue persists with https://github.com/servo/servo/pull/33045 change.

**Comment by atouchet** [comment]
I can confirm that the footer text issue appears to be fixed. I will open a separate issue for the DuckDuckGo text problem.
