### ISSUE TITLE
Strange log when using servo-media in android

### ISSUE THREAD

**Issue by cxg666** [servo/servo#32450]
**Describe the bug:**
A clear and concise description of the bug.
I have posted here.
https://github.com/servo/media/issues/422

**To Reproduce:**
Steps to reproduce the behavior.
set_input_size -> push_data

**Platform:**
Specify OS, distribution, and hardware platform.
Android

**Comment by jdm** [comment]
Closing this, since there's no additional information over the original issue in the media repo.
