### ISSUE TITLE
CI: Enforce DCO "Signed-off-by:" for all PRs

### ISSUE THREAD

**Issue by jschwe** [servo/servo#32496]
[Servos contributing guideline](https://github.com/servo/servo/blob/main/CONTRIBUTING.md#pull-request-checklist) requires all commits to be signed off: 

> Commits should be accompanied by a Developer Certificate of Origin (http://developercertificate.org/) sign-off, which indicates that you (and your employer if applicable) agree to be bound by the terms of the [project license](https://github.com/servo/servo/blob/main/LICENSE). In git, this is the -s option to git commit.

However this is currently not enforced and not all commits / PRs are actually signed off (For example I recently forgot to sign-off). I'm not a lawyer, but I imagine that this might enable problematic situations in the future, so to be safe we should add a CI job which checks that all commits are signed off - Maybe even requiring that the signed-off-by name / email matches the PR author.

**Comment by mrobinson** [comment]
I think this should be possible, but we should ensure that the WPT import job is also signing it's commits.

**Comment by sagudev** [comment]
This was also discussed in https://github.com/servo/project/issues/18

**Comment by mrobinson** [comment]
This is done now. Thanks!

**Comment by jschwe** [comment]
> This is done now. Thanks!

I'm a bit confused - How exactly is this signing off enforced now? I don't see anything related in the last 3 commits on main (of which none are signed off)

**Comment by mrobinson** [comment]
@jschwe No worries! I missed that the DCO Bot wasn't discussed in this issue. For the sake of clarity the Servo repository now enforces signing off commits via the [DCO Bot](https://github.com/apps/dco).
