### ISSUE TITLE
enable grouping-ol tests

### ISSUE THREAD

**Issue by metajack** [servo/servo#3250]
The `/html/semantics/grouping-content/the-ol-element/grouping-ol.html` is currently disabled since it times out on Travis for unknown reasons. It should be turned back on.

**Comment by frewsxcv** [comment]
It no longer looks like this test is disabled

https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/semantics/grouping-content/the-ol-element/grouping-ol.html.ini
