### ISSUE TITLE
enable grouping-li tests

### ISSUE THREAD

**Issue by metajack** [servo/servo#3251]
The `/html/semantics/grouping-content/the-ol-element/grouping-ol.html` test is currently disabled due to timeouts on Travis for unknown reasons. It should be reenabled.

**Comment by frewsxcv** [comment]
It no longer looks like this test is disabled

https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/semantics/grouping-content/the-ol-element/grouping-ol.html.ini
