### ISSUE TITLE
Replace constant fixed-length u8 vectors with byte strings

### ISSUE THREAD

**Issue by jdm** [servo/servo#3257]
http://mxr.mozilla.org/servo/search?string=[u8%2C

For example,
```rust
static FC_FAMILY: [u8, ..7] = ['f' as u8, 'a' as u8, 'm' as u8, 'i' as u8, 'l' as u8, 'y' as u8, 0 as u8];
some_fn_taking_char_ptr(&FC_FAMILY as *const u8 as *const libc::c_char);
```
should become
```rust
static FC_FAMILY: &'static [u8] = b"family\0";
some_fn_taking_char_ptr(FC_FAMILY.as_ptr() as *const libc::c_char)
```

**Comment by jdm** [comment]
This looks like it's worth trying again after the next upgrade, since the blocking bug was fixed.

**Comment by AopicieR** [comment]
@ProgramFOX Are you still planning to work on this? If not I'd love to give this a shot.

**Comment by ProgramFOX** [comment]
@AopicieR I don't have plans to continue working on this issue, so feel free to take it.
