### ISSUE TITLE
Separate build/run time deps

### ISSUE THREAD

**Issue by sagudev** [servo/servo#32582]
When running WPT tests we spend 6min on `mach bootstrap` installing build deps and utils (crown, taplo, cargo-deny, ...) that will not be used. Instead  we should provide `--runtime-only` flag that would only install runtime deps.

**Comment by mrobinson** [comment]
The distinction isn't build / run exactly. It's more like run / build / lint. Maybe we can be a bit clever about how we express that or install those tools. In particular, it would be better to use python based tools when there are alternatives. I think taplo is the main culprit there. I agree the bots shouldn't be compiling a lot of extra rust code when unnecessary.

**Comment by jschwe** [comment]
Most of the CI jobs ([example](https://github.com/servo/servo/blob/8121c9883477cf4350e8dd8abdc3776548c11ea3/.github/workflows/linux.yml#L95)) use a dedicated `cargo-install` step to install taplo / cargo-deny, which has the benefit of using the github actions cache to cache the binary, at the cost of making the CI yaml files more verbose. Skipping would of course be the better solution, but as a quick fix, we could also use the cache for the wpt tests.
