### ISSUE TITLE
script: Safe way to create `Function`

### ISSUE THREAD

**Issue by wusyong** [servo/servo#32601]
**Describe the new feature:**
In #32572, we still need to use unsafe code to create `Funtion`. The `FunctionBinging` doesn't provide a safe way to create one. And considering many dom types don't really want `Function`. Instead, they just want the `*mut JSObject` from `*mut JSFunction`:
- https://github.com/servo/servo/blob/main/components/script/dom/bindings/interface.rs#L341
- https://github.com/servo/servo/blob/main/components/script/dom/promise.rs

We should propose a safe wrapper function(s) for `JS_NewFunction` and `JS_GetFunctionObject`. Here are the method I think we could add:

- [ ] `Function::new_native`: Create a `Rc<Function>` using `JS_NewFunction`, `JS_GetFunctionObject` and `Function::new`
- [ ] `Function::new_raw_obj`: Create a `*mut JSObject`(or handle?) using `JS_NewFunction` and `JS_GetFunctionObject`

**Comment by Taym95** [comment]
@servo-highfive assign me

**Comment by servo-highfive** [comment]
Hey @Taym95! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by Taym95** [comment]
This can be closed.
