### ISSUE TITLE
Replace null-byte terminated string literals with C-string literals

### ISSUE THREAD

**Issue by sagudev** [servo/servo#32628]
They are available from rust 1.77: https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#c-string-literals, most occurrences should be found by searching for `\0` in source tree.

This is generally just mechanical work, but it mostly touches unsafe code.

Does it sounds reasonable @mrobinson?

**Comment by mrobinson** [comment]
This seems reasonable to me!

**Comment by ada2k** [comment]
Why has this been reopened?

**Comment by sagudev** [comment]
Because there is more such patterns in the code, for example: https://github.com/servo/servo/blob/e2e7476404e407caa3e6625f4cf4bd6aed9ded6b/components/script/dom/eventtarget.rs#L524

**Comment by abumsoo** [comment]
Hi! I can work on this if nobody else is working on it yet

**Comment by sagudev** [comment]
> Hi! I can work on this if nobody else is working on it yet

Sure

**Comment by sagudev** [comment]
There are still more that can be replaced like https://github.com/servo/servo/blob/141a594e236201acb44ca7cc42e2e653f4d55e7b/components/script/dom/window.rs#L735 and there is also some stuff in codegen: https://github.com/servo/servo/blob/141a594e236201acb44ca7cc42e2e653f4d55e7b/components/script/dom/bindings/codegen/CodegenRust.py#L2470

**Comment by abumsoo** [comment]
> There are still more that can be replaced like
> 
> https://github.com/servo/servo/blob/141a594e236201acb44ca7cc42e2e653f4d55e7b/components/script/dom/window.rs#L735
> and there is also some stuff in codegen:
> 
> https://github.com/servo/servo/blob/141a594e236201acb44ca7cc42e2e653f4d55e7b/components/script/dom/bindings/codegen/CodegenRust.py#L2470

Good catch. The one in `window.rs` is a simple fix, but I'm having trouble with `CodegenRust.py` and I think I need some assistance on it.

When I change `return "b\"%s\\0\"" % s` to `return "c\"%s\".as_ptr()" % s`, I get the following error:
```
    = note: expected reference `&'static [u8]`
               found raw pointer `*const i8`
```
However, when I change it to `return "c\"%s\".to_bytes_with_nul()" % s`, I get an error where it expects something different:
```
    = note: expected raw pointer `*const i8`
                 found reference `&[u8]`
```
It's hard to debug since it's python code for generating rust code. I would appreciate any help.

**Comment by sagudev** [comment]
The codegen one might require more changes (maybe check usages of `str_to_const_array`). When dealing with codegen I usually check generated files, to see what's wrong.

**Comment by abumsoo** [comment]
Are there tests for codegen?

**Comment by sagudev** [comment]
> Are there tests for codegenRust?

No.

> And/or should there be?

Probably, but I do not expect you write them.
