### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by romulasry** [servo/servo#32640]
For this: https://release-monitoring.org/project/370873/

**Comment by jdm** [comment]
What is that? How does it work? What are you asking for?

**Comment by romulasry** [comment]
Like 1.2.0 version for example for servo.

**Comment by jdm** [comment]
Ok, but what is that supposed to represent? Who is using this data? The Servo project doesn't maintain official releases, only nightly downloads on download.servo.org.

**Comment by mrobinson** [comment]
I'm not sure if we have any plans to release numbered versions any time soon and we likely won't make a tag for every nightly, so I'm not sure this makes sense currently. If we are missing information here though, free free to leave a comment @romulasry and maybe we can reopen this one.

**Comment by xuhcc** [comment]
@mrobinson Hello, what's your current position on releasing numbered versions? That would help with packaging.

**Comment by mrobinson** [comment]
Servo isn't ready to be packaged as it does not expose a stable C-compatible API nor is it prepared to be a Cargo crate due to #26275.

**Comment by jschwe** [comment]
> @mrobinson Hello, what's your current position on releasing numbered versions? That would help with packaging.

@xuhcc FYI, we do have tagged versions now, but it is still pre-1.0. Any packaging attempts would likely need to closely monitor upstream for breaking changes.

**Comment by xuhcc** [comment]
@jschwe I know, it has already been packaged for my distribution. Thank you for your work!
