### ISSUE TITLE
First time `mach bootstrap` fails if the `$PATH` has not been updated after rustup installation

### ISSUE THREAD

**Issue by diegoe** [servo/servo#32670]
**Describe the bug:**
While following the README to setup a servo dev env, right after installing rust with the rustup script, the `mach bootstrap` command will fail because `cargo` (the whole rust, for that matter) is not in `$PATH`.

Evidently, if it's your first time setting up with `rustup`, and you are still on the same exact shell where you ran the rustup installation, you haven't sourced your new bash/profile/etc script with the rustup added PATH.

This is not really a big deal, but I wonder if the `mach` setup could trigger an env reload, or even just fallback to the known rustup install path (?). On the other hand, the line has to be drawn somewhere, so maybe assuming one should have reloaded the shell could be the bare minimum competency expected (?).

```
 * Installing taplo...
Traceback (most recent call last):
  File "/Users/diego/hack/servo/./mach", line 48, in <module>
    main(sys.argv)
  File "/Users/diego/hack/servo/./mach", line 25, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diego/hack/servo/python/mach_bootstrap.py", line 204, in bootstrap_command_only
    servo.platform.get().bootstrap(force, skip_platform, skip_lints)
  File "/Users/diego/hack/servo/python/servo/platform/base.py", line 62, in bootstrap
    installed_something |= self.install_taplo(force)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diego/hack/servo/python/servo/platform/base.py", line 74, in install_taplo
    if subprocess.call(["cargo", "install", "taplo-cli", "--locked"]) != 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cargo'
```

**To Reproduce:**
* Follow README instructions to setup a servo env
* Install rustup on a rust-free env
* Immediately follow the next step and run `mach bootstrap`
* `bootstrap` fails midway because the env has not been reloaded, so `cargo` is not in `$PATH` yet

**Platform:**
* macOS `14.3.1 (23D60)`
* Building current `HEAD`: fe58a5f0a3bd9a20e368ed283dfcb89769f75c00

**Comment by mukilan** [comment]
I believe `rustup` will print a [message](https://github.com/rust-lang/rustup/blob/efa576d8fbb4b98cf6dc8770afebc9b1e647f00b/src/cli/self_update.rs#L392) after cargo installation to reload the shell so that the updated PATH is used.

**Comment by diegoe** [comment]
@mukilan I probably missed it since I just let that run while I did something else, I guess I had already "focused" on the next step and did not paid much attention to the previous output other than "no errors".

FWIW I try to report first-time dev-setup issues in projects since they can be easy barriers to new contributors. Even experienced folks frequently fall in these gotchas, so it never hurts to examine them.

Feel free to close if the suggestion does not really fit anywhere in the current process and style for the README/setup process.

**Comment by mrobinson** [comment]
@diegoe Thanks for the report. I think the solution here might be to improve our documentation so that's it's more obvious that you need to refresh your environment after running rustup.

**Comment by diegoe** [comment]
👋 Martin! 😄 

Perhaps something like this?

```md
- Run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`<br/>
  *Note: You need to restart your shell to have the rustup toolchain available for the bootstrap process.*
```

Or "available in your `$PATH`"?

(I'm not precisely a wordsmith, let's be real 🪶 )
