### ISSUE TITLE
webgpu: Rename kill_*_id methods to free_*_id

### ISSUE THREAD

**Issue by sagudev** [servo/servo#32685]
All kill_*_id methods are here:
https://github.com/servo/servo/blob/650af7db926e9cc070e136f21a56bd47d566d10a/components/script/dom/identityhub.rs#L120-L122

Historically, wgpu also have kill method but renamed them into free as the inner mechanic changed.

Hint: Rust-Analyzer offers rename symbol feature in vscode that will automatically rename all occurrences.

**Comment by newmoneybigbucks** [comment]
I can get this done.

**Comment by sagudev** [comment]
> I can get this done.

I assigned you to the issue.
