### ISSUE TITLE
Less nesting on WebGPUResponse

### ISSUE THREAD

**Issue by sagudev** [servo/servo#32766]
Currently response sender has this type: `IpcSender<Option<WebGPUResponseResult>>`, where
https://github.com/servo/servo/blob/91ca727eb9412012d2a38c1a9c870415b34d989b/components/webgpu/ipc_messages/to_dom.rs#L78-L78

`Option` is `None` only when dom.webgpu.enabled is disabled (introduced in https://github.com/servo/servo/pull/31002), instead we can pack `None` value into as `WebGPUResponse::NoWebGPU` variant.

`Result` errors only in `RequestDevice` or `RequestAdapter` in other cases we already use result in variant (we need limited errors and it's nice know which request are we resolving): https://github.com/servo/servo/blob/91ca727eb9412012d2a38c1a9c870415b34d989b/components/webgpu/ipc_messages/to_dom.rs#L74 (or not have result/error at all). So we can remove outer `Result` and replacing it with results in variants (this will require named struct for all data inside: https://github.com/servo/servo/blob/91ca727eb9412012d2a38c1a9c870415b34d989b/components/webgpu/ipc_messages/to_dom.rs#L60-L66).

Does that sounds reasonable @gterzian?

**Comment by gterzian** [comment]
> Does that sounds reasonable
Yes
