### ISSUE TITLE
Modify Cargo.tomls with custom build scripts to use NUM_JOBS

### ISSUE THREAD

**Issue by metajack** [servo/servo#3277]
Cargo now passes the `-j` parallelism level as the `NUM_JOBS` environment variable. We should use this in the dependencies instead of hardcoding `-j 4`.

**Comment by mskrzypkows** [comment]
How about: https://github.com/servo/servo/blob/master/python/servo/build_commands.py#L91
Do NUM_JOBS has to be used here?

**Comment by jdm** [comment]
Yes, that seems like a useful change to make.

**Comment by mskrzypkows** [comment]
OK, I'll prepare patch for this.

**Comment by metajack** [comment]
@mskrzypkows The other examples are probably in the dependencies. Many of them have a build step that runs a Makefile from Cargo, and that make invocation has a hardcoded `-j4`. Probably the biggest two of these would be mozjs and skia.

**Comment by mskrzypkows** [comment]
@metajack As I see in build_commands.py, the number of jobs is passed by ```--jobs``` or ```-j``` flag. How it has to be done in skia and mozjs scripts, should I use ```NUM_JOBS``` environment variable or pass flag to ```cargo build``` command?

**Comment by metajack** [comment]
See https://github.com/servo/skia/blob/master/Cargo.toml#L7 for an example. You can replace the `4` with `$NUM_JOBS` I believe, since Cargo sets that environment variable for use by the build scripts.

Alternatively you could use the new Cargo feature and gcc-rs like some of the more recently introduced submodules.

**Comment by gilles-leblanc** [comment]
This issue can be closed.

**Comment by jdm** [comment]
Well, the dependencies still have hardcoded numbers. It's easier to track that here than one issue in each.

**Comment by jdm** [comment]
This happened.
