### ISSUE TITLE
structuredClone is not available

### ISSUE THREAD

**Issue by koteisaev** [servo/servo#32770]
**Describe the bug:**
Following message in servo output:
```
[script::dom::bindings::error] Error at https://www.selfcad.com/deployments/20240709030454802/modern-scripts/startup-bundle.js.gzip:17:143088 structuredClone is not defined
```
Well, it is not that kind of error like scripts not working at all, but this specific function is not available.
Function in question: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

**To Reproduce:**
I suppose that even minimal page with script like 
```
console.info(structuredClone({ some: "value", other: 1, test: true, values: [1, NaN, null] }))
```
will fail with such error.

**Platform:**
Ubuntu 24.04, DELL Inspiron PC with Nvidia GeForce GTX 16XX series.

**Comment by sagudev** [comment]
We have algo implemented for [`postMessage()`](https://html.spec.whatwg.org/multipage/web-messaging.html#dom-broadcastchannel-postmessage), but we do not expose it directly.

Webidl: `any structuredClone(any value, optional StructuredSerializeOptions options = {});` (in mozilla: https://searchfox.org/mozilla-central/rev/9dd09bebbff975e6b0fdabe0032753fcc3176e4f/dom/webidl/WindowOrWorkerGlobalScope.webidl#56) need to add somewhere here: https://github.com/servo/servo/blob/cd394af018c1816f5d504e49b37af9258ce052e6/components/script/dom/webidls/WindowOrWorkerGlobalScope.webidl#L30-L31

here is impl in FF: [StructuredSerializeOptions](https://searchfox.org/mozilla-central/rev/9dd09bebbff975e6b0fdabe0032753fcc3176e4f/dom/workers/WorkerScope.cpp#804), that calls: https://searchfox.org/mozilla-central/rev/9dd09bebbff975e6b0fdabe0032753fcc3176e4f/dom/base/nsContentUtils.cpp#10685

**Comment by gterzian** [comment]
I think this may not be so complicated actually, seems like you can:

1. Add the function via webidl as explained by @sagudev, and inside it:
 3. call [`structuredclone::write` ](https://github.com/servo/servo/blob/d5171c068cd3a00dafb70e0d4f10dff42a8888a5/components/script/dom/bindings/structuredclone.rs#L285) passing the handle value that was recived as the value to the function call. 
 4. followed by a call to `structuredclone::read` on the data and using a rooted mutable handle value(see for example https://github.com/servo/servo/blob/d5171c068cd3a00dafb70e0d4f10dff42a8888a5/components/script/dom/window.rs#L2775)
 5. Then you can just return the handle that was passed to `read`, or throw an error.
