### ISSUE TITLE
Use Cargo features instead of cfg gating whole crates

### ISSUE THREAD

**Issue by metajack** [servo/servo#3278]
Currently we add `#[cfg(target_os=...)]` lines to crates that are platform specific so they compile on every platform. We should instead use Cargo's new feature support.

**Comment by Mylainos** [comment]
It look like `features` is implemented now.

**Comment by frewsxcv** [comment]
This is possibly related to #5973

**Comment by faineance** [comment]
Anyone mind if I pick this up?

**Comment by frewsxcv** [comment]
Go for it!

**Comment by schuster** [comment]
A brief glance through some of the Cargo files suggests the problem was already fixed by making various dependencies target-specific. Is there anything left to do?

**Comment by mbrubeck** [comment]
No, I think this is done.
