### ISSUE TITLE
IDLharness test failures on operations that return promises

### ISSUE THREAD

**Issue by msub2** [servo/servo#32816]
When there is an IDL harness test on an operation that returns a promise (such as `playEffect()` and `reset()` on GamepadHapticActuator, `getAvailability()` on Bluetooth, etc) the subtest for checking promise rejection when `this` is null/undefined fails. Relevant spots:

https://github.com/servo/servo/blob/8b3c9b744ab41f52f01ee624228e655b981824eb/tests/wpt/tests/resources/idlharness.js#L113
https://github.com/servo/servo/blob/8b3c9b744ab41f52f01ee624228e655b981824eb/tests/wpt/tests/resources/idlharness.js#L2395

**Comment by jdm** [comment]
We're missing equivalent codegen to https://searchfox.org/mozilla-central/rev/b220e40ff2ee3d10ce68e07d8a8a577d5558e2a2/dom/bindings/Codegen.py#10655-10684

**Comment by msub2** [comment]
Would this just require changes to `components/script/dom/bindings/codegen/CodegenRust.py`?

**Comment by jdm** [comment]
Not quite—that code is fine, we're just missing a wrapper function that converts any thrown exception into a promise rejection.

https://github.com/servo/servo/blob/main/components/script/dom/bindings/codegen/CodegenRust.py#L4392 corresponds to https://searchfox.org/mozilla-central/source/dom/bindings/Codegen.py#12059 and needs a change for oromise-specufic logic. 

https://github.com/servo/servo/blob/main/components/script/dom/bindings/codegen/CodegenRust.py#L6348 corresponds to https://searchfox.org/mozilla-central/source/dom/bindings/Codegen.py#16849 and also needs oromise-specufic logic.

Then we're missing the specific logic that I linked in my previous comment that these two references use.

**Comment by sagudev** [comment]
@msub2 are you actively working on this? If not, I would gladly work on it, as I need this for webgpu.

**Comment by msub2** [comment]
> @msub2 are you actively working on this? If not, I would gladly work on it, as I need this for webgpu.

I am not, feel free to work on this

**Comment by sagudev** [comment]
Relevant bug in mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=983300

**Comment by sagudev** [comment]
@msub2 which test are having this? Can you try them with #32923.

**Comment by sagudev** [comment]
There are still some problems, https://servo.zulipchat.com/#narrow/stream/263398-general/topic/Support.20for.20the.20Gamepad.20API because sMethods_specs has:
```
const sMethods_specs: &[&[JSFunctionSpec]] = &[
&[
    JSFunctionSpec {
        name: JSPropertySpec_Name { string_: c"playEffect".as_ptr() },
        call: JSNativeWrapper { op: Some(generic_method), info: &playEffect_methodinfo as *const _ as *const JSJitInfo },
        nargs: 1,
        flags: (JSPROP_ENUMERATE) as u16,
        selfHostedName: 0 as *const libc::c_char
    },
```
and generic_method calls (basically we need exception policy on generic methods).
