### ISSUE TITLE
Poor performance when rendering Danmaku over videos

### ISSUE THREAD

**Issue by VeleSila** [servo/servo#32872]
**Describe the bug:**
The GPU will overload easier than Chrome when playing videos with Danmaku. 

**To Reproduce:**
Play the video at https://www.bilibili.com/video/BV1cs411s7LY/

**Platform:**
Firefox 128 on Windows 10/11, and Ubuntu 24.04

**Comment by jdm** [comment]
Why is Firefox mentioned here if you're comparing Servo against Chrome?

**Comment by VeleSila** [comment]
> Why is Firefox mentioned here if you're comparing Servo against Chrome?

My apologies, it may cause by my poor understanding of the relationship between Servo: I though Servo is the engine of the Firefox. 

Could you let me know where should I create the issue if this is not the correct location?

**Comment by mukilan** [comment]
Firefox issues can be reported at https://bugzilla.mozilla.org/. I'll close this issue.
