### ISSUE TITLE
Incorrent documentation for DomRefCell

### ISSUE THREAD

**Issue by Wuelle** [servo/servo#33099]
The documentation for `DomRefCell::borrow/borrow_mut` states that the method will panic when being called from outside the script thread.
That is not true, since it only calls `RefCell::borrow` (from `std`) and therefore enforces no such guarantee:
https://github.com/servo/servo/blob/20273b062af969152635306c3df2a3a1364ac4d1/components/script/dom/bindings/cell.rs#L84-L96

The documentation was originally written in 7ec11b22b445f32ab7db2db11f889731e25cc4c1. At the time, the code called `try_borrow` like this:
https://github.com/servo/servo/blob/7ec11b22b445f32ab7db2db11f889731e25cc4c1/components/script/dom/bindings/cell.rs#L111-L116
`try_borrow` then calls `assert_in_script`. Later, the method was refactored multiple times, with the interesting commit being da3b3e3985621ffd2f6d9b65583f4f498190402c (this removes the call to `try_borrow`).

Who is in the wrong here? Should `DomRefCell::borrow` panic when being called from outside the script thread? Should the documentation be updated instead?

**Comment by mrobinson** [comment]
I suspect the documentation is wrong. The other methods which have this documentation has a debug assertion guaranteeing that the borrow happened on the script thread. Furthermore, this is less important now that script and layout share the same thread. This documentation can likely simply be removed.
