### ISSUE TITLE
Text rendering issue on duckduckgo.com

### ISSUE THREAD

**Issue by atouchet** [servo/servo#33094]
**Describe the bug:**
Text that appears on duckduckgo.com exhibits rendering issues on some page loads. The issue does not reproduce 100% of the time.

Image:

![Untitled-1](https://github.com/user-attachments/assets/7773ef8c-3d03-4ff3-8b4c-3f603501075e)

**To Reproduce:**
1. Load duckduckgo.com.
2. Scroll down to where it says Desktop & Mobile Browser Desktop Browser Extension.
3. Notice that there are sometimes issues with the text.

**Platform:**
Windows 10

**Comment by mrobinson** [comment]
@atouchet Would you mind testing this now that #33177 has landed. It's quite possibly related.

**Comment by atouchet** [comment]
I tried the latest nightly build and haven't been able to reproduce the text issue so this may be fixed now. I was also having issues consistently displaying the problem in an earlier build too however so hopefully I'm not just having issues running into the right conditions. I will re-open the report if I run into it again.
