### ISSUE TITLE
Implement ErrorEvent, Window/Worker.onerror, and proper JS error reporters

### ISSUE THREAD

**Issue by jdm** [servo/servo#3311]
**Background information**: SpiderMonkey (the JavaScript engine) exposes a user-specifiable callback executing JS that throws an exception that is not caught. At the moment, the `rust-mozjs` library (which wraps the C-based `mozjs` aka SpiderMonkey) sets this callback to a simple function that logs the exception to the terminal. We want to replace this in Servo with a method that implements the error reporting specification for web browsers as described below.

Spec: http://www.whatwg.org/specs/web-apps/current-work/multipage/webappapis.html#runtime-script-errors
ErrorEvent interface: http://www.whatwg.org/specs/web-apps/current-work/multipage/webappapis.html#errorevent
OnError algorithm: http://www.whatwg.org/specs/web-apps/current-work/multipage/webappapis.html#the-event-handler-processing-algorithm

This will require fixing an `XXXjdm` comment in `set_event_handler_uncompiled`, too, and implementing a new [SpiderMonkey error reporter](https://github.com/servo/rust-mozjs/blob/master/src/rust.rs#L128) that invokes the actual ErrorEvent dispatch to the window/worker.

**Comment by jwilm** [comment]
@jdm is this still being worked on by students? There's a bunch of easy wins in the web-platform-tests if we can finish this. I would be happy to complete this if it's not being worked on.

**Comment by jdm** [comment]
Nope, it's available!

**Comment by jwilm** [comment]
Sweet. I'll get on it tonight.

**Comment by nox** [comment]
Blocks #2185.

**Comment by nox** [comment]
@jdm I have some questions:

* Should `EventTarget` get a new flag for ["in error reporting mode"](https://html.spec.whatwg.org/multipage/#in-error-reporting-mode)?
* Should `ErrorEvent` get a new flag for ["handled"](https://html.spec.whatwg.org/multipage/#concept-error-handled)/["not handled"](https://html.spec.whatwg.org/multipage/#concept-error-nothandled)?
* How and where should we handle ["muted errors"](https://html.spec.whatwg.org/multipage/#muted-errors)?
* Does `JSErrorReport::filename` correspond to the absolute URL mentioned in step 5 of [the spec](https://html.spec.whatwg.org/multipage/#report-the-error)?
* Do we actually need the ["report the error"](https://html.spec.whatwg.org/multipage/#report-the-error) algorithm, or should we implement only the ["report the exception"](https://html.spec.whatwg.org/multipage/#report-the-exception) one used on the global object?
