### ISSUE TITLE
Rendering issue on wikipedia.org

### ISSUE THREAD

**Issue by crbrz** [servo/servo#33170]
**Describe the bug:**
Top logo/image and text at bottom left don't render correctly (main branch 2db9032e72bda6108b4eb5988eaf164141a61d64):
![wikipedia](https://github.com/user-attachments/assets/1237ae81-6d26-4d2b-b506-cfe39dc7de85)

**To Reproduce:**
`servo https://wikipedia.org`

**Platform:**
Windows 11, x86_64

I tracked down the issue to `webrender`. Servo uses default texture upload method `UploadMethod::PixelBuffer`. In this mode `webrender` uses a single `TextureUploader` (https://github.com/servo/webrender/blob/c0bcdd024adac1297ceb2f34a2de46731243c970/webrender/src/renderer/upload.rs#L79-L83) to upload glyphs and images to GPU. The uploads are staged in one or more buffers before data is sent to GPU (https://github.com/servo/webrender/blob/c0bcdd024adac1297ceb2f34a2de46731243c970/webrender/src/device/gl.rs#L4561-L4598). On Windows if the staged textures are not aligned at bytes per pixel boundary in upload buffer the GPU will read the wrong data.

Using this patch (https://github.com/crbrz/webrender/commit/f88b451e77390283e7bbed9646853f44949ab6e9) for `webrender` fixes the issue on wikipedia:
![wiki_good](https://github.com/user-attachments/assets/4d7194d1-deba-428d-9ee8-e95279e7e6f4)
This issue https://github.com/servo/servo/issues/33094 seems to be fixed as well.

**Comment by mrobinson** [comment]
@crbrz Thanks for the investigation! Do you have any idea what Gecko is doing here?

**Comment by crbrz** [comment]
Gecko uses `UploadMethod::Immediate`: https://searchfox.org/mozilla-central/source/gfx/webrender_bindings/src/bindings.rs#1215-1218. If I understand correctly in this mode small textures are batched per destination texture, for example it doesn't mix `R8` with `BGRA8` in same buffer as `UploadMethod::PixelBuffer` does.

I checked and using `UploadMethod::Immediate` upload mode in Servo fixes the issue without needing a `webrender` patch.

**Comment by mrobinson** [comment]
We probably want code very much like what Gecko has:

```rust
    let upload_method = if unsafe { is_glcontext_angle(gl_context) } {
        UploadMethod::Immediate
    } else {
        UploadMethod::PixelBuffer(ONE_TIME_USAGE_HINT)
    };
```
