### ISSUE TITLE
Implement an XML parser

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#3319]
Stuff like parsing fetched `XMLDocument`s and SVG/MathML need an XML parser.

You may be able to be able to re-use some of the stuff from our [HTML parser (incomplete)](https://github.com/kmcallister/html5ever).

**Comment by jdm** [comment]
With regards to existing non-XML5 parsers, the ones for consideration are [xml-rs](https://github.com/netvl/xml-rs), [RustyXML](https://github.com/Florob/RustyXML), and [Rust bindings to libxml2](https://github.com/uzytkownik/xml-rs) (which are quite out of date).

**Comment by hsivonen** [comment]
Using Rust bindings for a parser implemented in a memory-unsafe language, e.g. libxml2, seems contrary to the safety goals related to using Rust in the first place.

**Comment by Ms2ger** [comment]
#8278
