### ISSUE TITLE
Impl PartialEq and Eq for `DomObject`

### ISSUE THREAD

**Issue by sagudev** [servo/servo#33191]
> Note: I think this a candidate for something "higher-up", maybe `DomObject`?

_Originally posted by @gterzian in https://github.com/servo/servo/pull/33154#discussion_r1731315031_

**Comment by sagudev** [comment]
Something like
```rust
impl<T: DomObject> PartialEq for T {
    fn eq(&self, other: &Self) -> bool {
        self.reflector() == other.reflector()
    }
}
```
in https://github.com/servo/servo/blob/7b7020a8d429d4b58bcaf09615cdc246becfcfe5/components/script/dom/bindings/reflector.rs and I think we can also do `Eq` implementation.

**Comment by Taym95** [comment]
> Eq

I don't think this is possible because of:
```
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)
```

**Comment by sagudev** [comment]
We should do actual impl in `#[dom_struct]` instead of using generic impl I wrote.
