### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Darxus** [servo/servo#332]
http://wayland.freedesktop.org/

Most people seem to believe this will eventually replace X on linux.  It's being developed by X.org developers.  

01:18PM < jack> Darxus: i believe the plan is to switch to skia-gl, so it should be all opengles 2 shortly.

I believe GLES2 output should make it pretty easy to provide wayland support, but I'm not familiar enough with it to say how.

This probably depends on switching to skia-gl:  https://github.com/mozilla/servo/issues/331

**Comment by strelec** [comment]
So, gnome 3.16 is out with official Wayland support, so maybe we should make this feature request a higher priority.

**Comment by SimonSapin** [comment]
Does Gnome-with-Wayland not support X apps at all?

**Comment by SimonSapin** [comment]
This probably depends on https://github.com/tomaka/glutin/issues/3

**Comment by FireDart** [comment]
> Does Gnome-with-Wayland not support X apps at all?

From my understanding Gnome on Wayland has XWayland, which is a fall-back for X and it works just as well as plain old X (maybe a **very** slight performance hit).

http://wayland.freedesktop.org/xserver.html

**Comment by strelec** [comment]
Yes, it works with Xwayland, but glitches are present.

1. Copy-paste doesn't work.
2. Resize and fulscreen glitches.
3. Non-smooth resizing.

**Comment by genodeftest** [comment]
Note that Fedora 22 (to be released in ~2 weeks) does not run with wayland enabled for user session by default. It just runs the login (display manager) gdm on wayland. It ships a optional package providing a gnome session on wayland. In this case X applications will be run inside xwayland.
Still copy and paste, resize, drag-and-drop and some other things are broken for both XWayland and native wayland clients.
Support for X applications won't be dropped soon but X applications suffer some limitations (e.g. for touch events).
You might ask Martin Stránský (Red Hat, @stransky ) is working on some firefox/wayland related things, you might want to contact him for details.

**Comment by tomaka** [comment]
Glutin now has support for Wayland.
There may be some bugs though.

cc @vberger

**Comment by vberger** [comment]
To be more precise, there is *experimental* wayland support (for now it is disabled here https://github.com/tomaka/glutin/blob/master/src/platform/linux/api_dispatch.rs#L27-L28 ).

For now, a glutin wayland window is decoration-less (if the compositor does not provide decorations, such as with Weston), thus cannot be moved, resized or closed via user-input. But creation of EGL surfaces and drawing on them, as well as keyboard (keystrokes and utf8 input) and pointer input are mostly functional.

Copy-pasting (and more generally the wayland `data_offer` protocol) is not implemented either.

**Comment by stransky** [comment]
Firefox(Gtk3) on wayland is on my ToDo list. The mail patch has been checked in (https://bugzilla.mozilla.org/show_bug.cgi?id=635134) and there's some remaining issue with rendering (https://bugzilla.redhat.com/show_bug.cgi?id=1054334#c5). Not sure how it's related to the Servo project.

**Comment by csziacobus** [comment]
The X limitations on XWayland will be ironed out for Gnome 3.18. A fix for copy & paste across clients was already pushed out for 3.17.2.

**Comment by SirCmpwn** [comment]
:+1: easier to do this in servo than in Firefox.

**Comment by vberger** [comment]
For reference, here are the features still missing from the wayland backend of glutin: https://github.com/tomaka/glutin/issues/577

It's not yet activated, I tend to think the absence of a 'close' button on the window decoration is a rather bad point that should be fixed before activation wayland by default.

But my work on my set of wayland libs and their integration on glutin is still done on my spare time, so if anybody feels motivated enough, any help would be much appreciated. :wink: (and it would help me test more properly these crates)

**Comment by jdm** [comment]
I don't think there's any reason to track this in Servo's tracker, since the work seems to be happening at the level of the libraries we rely on for windowing-related code.

**Comment by gdamjan** [comment]
It would still be good to link the upstream issues here, so people searching for servo on wayland can track them :)

**Comment by vberger** [comment]
FYI, I'm working on a complete rewrite of the glutin wayland backend (see https://github.com/tomaka/glutin/pull/674 ), to match the new, more rusty structure I chose for my `wayland-client` lib.

Hopefully it should be finished during the next days.

I don't know what would be the next steps for servo to be able to use it, though.

**Comment by gdamjan** [comment]
Some people did a [wayland port of servo](http://blogs.s-osg.org/community-driven-wayland-support-servo/), part of it:
* [EGL support in rust-layers](https://github.com/servo/rust-layers/pull/220)
they avoided glutin at the time, and used EFL though.
