### ISSUE TITLE
Flickering at first launch when not using the minibrowser

### ISSUE THREAD

**Issue by webbeef** [servo/servo#33255]
**Describe the bug:**
When starting Servo, the display area flickers before stabilizing to the rendered page content. Sometimes it's clear that the content displayed is some other graphics buffer (ie. content displayed in another app...).

**To Reproduce:**
- Launch Servo without the minibrowser: `/mach run --no-minibrowser`

**Platform:**
Tested on Linux / Ubuntu 24.04

**Comment by Taym95** [comment]
Same for this, I guess we can close it after we removed `no minibrowser `.
