### ISSUE TITLE
CI: “Canceling since a higher priority waiting request for 'servo-reserve-self-hosted-runner' exists”

### ISSUE THREAD

**Issue by sagudev** [servo/servo#33276]
Problem discovered in https://github.com/servo/servo/pull/33269#issuecomment-2323172917.

`cancel-in-progress: false` still cancels runs per https://github.com/orgs/community/discussions/41518

cc @delan

**Comment by sagudev** [comment]
@delan Our runner is running one instance of https://github.com/servo/ci-runners/tree/main/monitor outside VM, right? 

We can then use it to set API endpoint that would atomically assign runners (just simple mutex so we serve only one request at time). Select runner jobs could be run concurrently, but will be served sequentially (the rest would remain the same). In case API endpoint is down we fallback to GitHub runners. The only downside to this approach is that it would work if we got more machines to host runners (we would need always available main server).

If we do API endpoint as request-response (response is returning assigned runner), we can also simplify select-runner job (as logic is in monitor). I suggest doing this with https://github.com/actions/github-script as it should be easier to parse response. We would not need github token for labeling (as it would be done in monitor), but we would still need to secure monitor API access somehow (probably with new API token).

**Comment by delan** [comment]
Good idea. This is one of the caveats I mentioned in #33081:

> all decision jobs need to be serialised with [job concurrency](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs), which could fail under contention because [there can only be](https://stackoverflow.com/a/77505633) [one pending job](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#using-concurrency-in-different-scenarios) in a concurrency group (in addition to one running job)

I can work on it later this week, but if it keeps happening, ping me again and disable the runners by [creating a repository variable](https://github.com/servo/servo/settings/variables/actions) named NO_SELF_HOSTED_RUNNERS with any non-empty value.

**Comment by sagudev** [comment]
another issue https://github.com/servo/servo/actions/runs/10664217365/job/29555053891#step:3:27

**Comment by delan** [comment]
> another issue https://github.com/servo/servo/actions/runs/10664217365/job/29555053891#step:3:27

Is that the same issue? I couldn’t find the “higher priority waiting request” error in that build.

**Comment by sagudev** [comment]
no, its different one

**Comment by delan** [comment]
Example with dependabot builds:

- <https://github.com/servo/servo/actions/runs/10636522620>
- <https://github.com/servo/servo/actions/runs/10636522669>
- <https://github.com/servo/servo/actions/runs/10636523237>

Setting NO_SELF_HOSTED_RUNNERS for now.

**Comment by delan** [comment]
> Could you report “Timeout waiting for runner assignment!” without “higher priority waiting request” as a separate issue? That way people can find it more easily. I’ll add some logging in the monitor to help diagnose.

#33296

**Comment by sagudev** [comment]
More of https://github.com/servo/servo/actions/runs/10693962111 that causes complete stop of MQ, `NO_SELF_HOSTED_RUNNERS` does not help because this got canceled due to concurrency (I think it was caused by on PR failing out MQ forcing all CIs to be restarted => starting at same time).
