### ISSUE TITLE
Transform `convert_*` functions in gpuconvert.rs to `From`/`TryFrom` implementations

### ISSUE THREAD

**Issue by sagudev** [servo/servo#33298]
See https://github.com/servo/servo/pull/33291/commits/5b582fca7355ee9dea094d6e254eab4a922e643b?diff=unified&w=1 for example

**Comment by sagudev** [comment]
We can still

**Comment by sagudev** [comment]
As for others, I think we will need to create own `Into` traits so we can bypass orphan rules, especially if we go with #1799 (but let's wait with that).

**Comment by Taym95** [comment]
> We can still move `convert_label` to `Into` implementation:
> 
> ```rust
> impl<'a> Into<Option<Cow<'a, str>>> for &GPUObjectDescriptorBase {
>     fn into(self) -> Option<Cow<'a, str>> {
>         if self.label.is_empty() {
>             None
>         } else {
>             Some(Cow::Owned(self.label.to_string()))
>         }
>     }
> }
> ```

I will pick it
