### ISSUE TITLE
jsstring_to_str should accept a NonNull argument for the js string

### ISSUE THREAD

**Issue by jdm** [servo/servo#33292]
It already asserts that the argument is not null, so we should force callers to handle that case by making the compiler verify it for us.

**Comment by last-genius** [comment]
Going to try to take this as my first issue. To make sure I understand this (and the project's attitude to this in general) correctly - judging by the assert in `jsstring_to_str` - null pointers shouldn't really be expected there already, therefore it would be alright for the callers to use `NonNull::new_unchecked()`? Or should the `panic` shift from the assertion into an `unwrap` on `::new()` in the callers?

Thank you in advance!

**Comment by jdm** [comment]
We should definitely require callers to make an explicit choice. Using unwrap in the callers as a first step would be great!

**Comment by jdm** [comment]
For context, I filed this based on the stack trace in #33288 where the assertion fired due to a null pointer being passed in.

**Comment by last-genius** [comment]
Is there anything I could read on the correct usage of the `rooted!` macro? A bit struggling with the following code, wondering if the diff would still work or if I should register something as a GC root. `NonNull` is a bit awkward for a simple translation here:

```diff
diff --git a/components/script/dom/console.rs b/components/script/dom/console.rs
index ae041dfa7d..dd902d26fc 100644
--- a/components/script/dom/console.rs
+++ b/components/script/dom/console.rs
@@ -71,12 +71,10 @@ where
 
 #[allow(unsafe_code)]
 unsafe fn handle_value_to_string(cx: *mut jsapi::JSContext, value: HandleValue) -> DOMString {
-    rooted!(in(cx) let mut js_string = std::ptr::null_mut::<jsapi::JSString>());
-    js_string.set(JS_ValueToSource(cx, value));
-    if js_string.is_null() {
-        return "<error converting value to string>".into();
+    match std::ptr::NonNull::new(JS_ValueToSource(cx, value)) {
+        Some(js_str) => jsstring_to_str(cx, *js_str),
+        None => "<error converting value to string>".into(),
     }
-    jsstring_to_str(cx, *js_string)
 }
```

**Comment by jdm** [comment]
In that particular case, you should be able to keep the rooted! use where it is, then call set in the some branch and follow it with jsstring_to_str.

**Comment by jschwe** [comment]
the associated PR is merged, so is this issue fixed now, or is there more work remaining?

**Comment by jdm** [comment]
Nope, that was all.
