### ISSUE TITLE
Sluggish resize behaviour on slow pages 

### ISSUE THREAD

**Issue by Wuelle** [servo/servo#33293]
**Describe the bug:**
When resizing a complex page (tested on  https://servo.zulipchat.com/, see https://html.spec.whatwg.org for a more extreme example) the resize events get queued up and the page continues to move around even after the window size stops changing.

https://github.com/user-attachments/assets/eb6ecc1d-aeaf-40cc-8b51-678335fc75d3

This happens because, in `update_the_rendering`, we process *each* resize event that occurred since the last `update_the_rendering` call:
https://github.com/servo/servo/blob/6c0394bc80963163f36dd273f8e6ed64b177dfa0/components/script/script_thread.rs#L1691-L1703

Is this necessary? From what I can see, the spec doesn't tell us to handle outdated resize events:

> 8. For each doc of docs, [run the resize steps](https://drafts.csswg.org/cssom-view/#document-run-the-resize-steps) for doc.
(https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering)

Here is what it would look like if all but the most recent resize event was thrown away:

https://github.com/user-attachments/assets/18694e53-c88e-404d-bfda-c5bf0aa1b634

I can PR this change, but I would like to first make sure that I'm not missing some important reason for why we need those events, since it seems like an intentional feature.

**Comment by jdm** [comment]
I believe the implementation from before gterzian's changes explicitly only ran the most- recently received resize event.

**Comment by Wuelle** [comment]
Apparently some tests want more resize events (https://github.com/servo/servo/pull/31505#discussion_r1592802909)
That seems odd. Is there some way for me to run a wpt try run on my fork without opening a PR?
