### ISSUE TITLE
Minibrowser: Removing URL from new tab also clears urls in other tabs

### ISSUE THREAD

**Issue by atbrakhi** [servo/servo#33311]
**Describe the bug:**
Removing URL from new tab also clears urls in other tabs

**To Reproduce:**
- open minibrowser
- open a new tab
- delete `servo:newtab`
- check the url of previously opened tabs

**Platform:**
Tested on MacOS. Not sure if happening on other platform as well

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/c6e5869b-3b9a-451f-8ca3-df3af3a60092">

**Comment by mrego** [comment]
JFYI, it happens on Linux too.
