### ISSUE TITLE
Wrong min-content size for `white-space: nowrap`

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#33335]
```html
<!DOCTYPE html>
<div style="width: 0">
  <div style="display: inline-block; border: solid; white-space: nowrap">
    A B C D E F G H I J K L M N O P Q R S T U V W X Y Z</td>
  </div>
</div>
```

| | |
| - | - |
| Expected | ![](https://github.com/user-attachments/assets/41febdda-1c39-4e32-ba39-f50c75829b89) |
| Actual | ![](https://github.com/user-attachments/assets/eb91ace1-fae0-45ad-9ce3-183801dec7b4) |

https://github.com/servo/servo/blob/7e493ba865ef7e748ce3b14d59117315a0ec8aee/components/layout_2020/flow/inline/mod.rs#L2344

**Comment by Taym95** [comment]
@Loirooriol, can I pick this up? I haven't worked on layout before, but I will debug it. It might take me some time, though

**Comment by Loirooriol** [comment]
@Taym95 Some months ago I already started a patch, so let me try if what I have works well, if not you can maybe finish the work.
