### ISSUE TITLE
Crash when loading https://finsandfoamfreediving.com/

### ISSUE THREAD

**Issue by webbeef** [servo/servo#33340]
**Describe the bug:**
Kaboom!

**To Reproduce:**
- Run  `./mach run https://finsandfoamfreediving.com/`

Expected:
- web site loads properly.

Observed:
- crash

Relevant errors:
```
overflow when subtracting durations (thread tokio-runtime-worker, at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/time.rs:1150)

  10: net::http_cache::get_response_expiry
             at /home/webbeef/servo/components/net/http_cache.rs:224:29
  11: net::http_cache::HttpCache::store
             at /home/webbeef/servo/components/net/http_cache.rs:860:22
  12: net::http_loader::http_network_or_cache_fetch::{{closure}}
             at /home/webbeef/servo/components/net/http_loader.rs:1478:21

```

**Platform:**
Linux Ubuntu 24.04

**Comment by jdm** [comment]
We calculate a response's age by looking at the Age header or default to zero (https://github.com/servo/servo/blob/main/components/net/http_cache.rs#L178-L187) then subtract that from 24 hours (https://github.com/servo/servo/blob/main/components/net/http_cache.rs#L224). If the Age header contains a value greater than 24 hours we panic, which obviously isn't great!

**Comment by jdm** [comment]
From skimming the code I think using [saturating_sub](https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.saturating_sub) should give us acceptable behaviour instead.
