### ISSUE TITLE
CanGc should derive Copy and Clone

### ISSUE THREAD

**Issue by jdm** [servo/servo#33404]
There are a bunch of uses of CanGc::note that could be replaced with existing values in the same function if the values can be trivially copied. Most uses of CanGc::note inside of a loop or following another call that used can_gc as an argument can be replaced with can_gc.

**Comment by last-genius** [comment]
Thanks for opening this one! I will be propagating canGc further if that's alright, would you prefer smaller PRs that wouldn't get stale with less chance of conflicts or could I do larger-scale changes?

**Comment by jdm** [comment]
I think whatever works best for you is ok!
