### ISSUE TITLE
Dependabot failures

### ISSUE THREAD

**Issue by atouchet** [servo/servo#33402]
Dependabot has stopped working the last few days with the message:

"Dependabot encountered an unknown error

Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details."

Ex: https://github.com/servo/servo/network/updates/882177380

**Comment by jdm** [comment]
```

updater | 2024/09/10 16:32:08 ERROR <job_882177380> Error during file fetching; aborting: Could not resolve workspace root for path dependency /components/shared/background_hang_monitor/Cargo.toml of /Cargo.toml
updater | 2024/09/10 16:32:08 ERROR <job_882177380> Could not resolve workspace root for path dependency /components/shared/background_hang_monitor/Cargo.toml of /Cargo.toml
```

Weird. I can't think of anything we changed on our side recently.

**Comment by jdm** [comment]
This looks like a regression from https://github.com/dependabot/dependabot-core/pull/10550.

**Comment by atouchet** [comment]
This appears to have been fixed.
