### ISSUE TITLE
Servoshell tabs don't show non-latin characters

### ISSUE THREAD

**Issue by mrego** [servo/servo#33419]
**Describe the bug:**
If you visit a page like Japanese or Arabic wikipedia the window title shows the characters properly, but the tab shows just squares.

![Screenshot of the issue, Servo opening ar.wikipedia.org and showing properly the title on the Window bar, but not on the tab title](https://github.com/user-attachments/assets/74c98cea-3d7f-471e-9f26-6bedeb8f5916)

**To Reproduce:**
Just visit one page with a title with non-latin characters, e.g. https://ar.wikipedia.org/

**Platform:**
Linux. Not sure if this happens in other platforms though.

**Comment by Taym95** [comment]
I this think this is egui issues:

https://github.com/emilk/egui/issues/56

**Comment by Melchizedek6809** [comment]
I've been wondering, wouldn't it simplify things if the Minibrowser were implemented as a special webpage instead of egui? Or are there any reasons that make this undesirable?

**Comment by Taym95** [comment]
> > I've been wondering, wouldn't it simplify things if the Minibrowser were implemented as a special webpage instead of egui? Or are there any reasons that make this undesirable?
> 
> 
> 
> For that you'll need a `<webview>` element to load documents in subframes as top level browsing contexts. I've been (very slowly) working on that but no ETA yet.

Isn’t that what Verso is doing? We can inspire from that!?

**Comment by mrego** [comment]
I didn't realize this was a egui issue, in that case I guess we can close this bug report as it's not a Servo issue.

About re-doing the servoshell that's a different discussion, and I guess that can happens in zulip or a TSC call or something like that. Probably not the top priority for the project anyway.

**Comment by Taym95** [comment]
> > > For that you'll need a `<webview>` element to load documents in subframes as top level browsing contexts. I've been (very slowly) working on that but no ETA yet.
> > 
> > 
> > Isn’t that what Verso is doing? We can inspire from that!?
> 
> No, Verso is using some "hybrid" approach. We discussed it in [versotile-org/verso#79](https://github.com/versotile-org/verso/issues/79) and #32883

Got it, I am ready to help if you are making special webpage, I was also playing around with the idea.
