### ISSUE TITLE
feature `max_log_level` in servoshell does not work 

### ISSUE THREAD

**Issue by jschwe** [servo/servo#33455]
**Describe the bug:**
servoshell sets the `release_max_level_info` feature on the `log` crate, but `debug` messages still appear in the log at runtime, even though they should not even be present in the binary. 
`log` apparently uses [`debug_assertions`](https://github.com/rust-lang/log/blob/96dbf58ec05e844ec55aa2282f32f612372fbced/src/lib.rs#L1528) to check if we are in release mode, but the problem is also present when compiling servo with the production profile where debug_assertions are disabled. 

Setting `max_level_info` and friends works as expected.

**To Reproduce:**
Compile in production mode, or change release mode to disable debug_assertions, and view the log output (disabling all runtime filters).

**Platform:**
Tested on OpenHarmony, but this should be completely platform indepedent.

**Comment by mukilan** [comment]
I don't seem to be able to reproduce the issue in production profile on linux. This is what I tried:
```
 ./mach build --prod
RUST_LOG=debug ./mach run --prod
```

I don't see any log messages unless I change the feature to be `release_max_level_debug`

**Comment by jschwe** [comment]
On macos I tried adding the following to `ports/servoshell/lib.rs`: 
```rust 
const _LOG_LEVEL: () = assert!(log::STATIC_MAX_LEVEL as usize <= log::Level::Info as usize);

```

and received
```
❯ ./mach build --profile=production
[...]
   Compiling servoshell v0.0.1 (/Users/jschwender/Dev/servo/ports/servoshell)
error[E0080]: evaluation of constant value failed
  --> ports/servoshell/lib.rs:39:24
   |
39 | const _LOG_LEVEL: () = assert!(log::STATIC_MAX_LEVEL as usize <= log::Level::Info as usize);
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: log::STATIC_MAX_LEVEL as usize <= log::Level::Info as usize', ports/servoshell/lib.rs:39:24
   |
   = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `servoshell` (lib) due to 1 previous error
```

**Comment by mukilan** [comment]
It seems `./mach build` has not failed on any of the [platforms](https://github.com/jschwe/servo/actions/runs/10917306507/job/30300385626). Some of individual jobs have failed due to various reasons (unit tests, android not supporting production profile etc.)

**Comment by jschwe** [comment]
Huh, I guess I'll need to investigate my environment. Maybe I have some config.toml I forgot about. Sorry about the noise
