### ISSUE TITLE
Documentation: Wrong return type listed on embedder_traits::EventLoopWaker.clone_box 

### ISSUE THREAD

**Issue by mcclure** [servo/servo#33465]
https://doc.servo.org/embedder_traits/trait.EventLoopWaker.html

Gives the type of 

fn [clone_box](https://doc.servo.org/embedder_traits/trait.EventLoopWaker.html#tymethod.clone_box)(&self) -> [Box](https://doc.rust-lang.org/1.80.1/alloc/boxed/struct.Box.html)<dyn [MainThreadWaker](https://doc.servo.org/embedder_traits/trait.EventLoopWaker.html)>;

for the clone_box method of the embedder_traits::EventLoopWaker trait.

This is not correct. In my testing with the actual code, the return type is `Box<EventLoopWaker>`. Oddly, the link in the documentation links to the correct page.

I am struggling to find embedder_traits in the servo codebase, somehow. This might actually be a bug with Cargo and/or the documentation generator. If I can be given enough information to identify what the documentation generator is doing wrong, I would be willing to go file a separate bug on them.

**Comment by jdm** [comment]
Since it's a re-export that's renamed, I don't see an issue here. Feel free to file an issue with rustic about ways to make this less confusing, however!
