### ISSUE TITLE
Move `unmultiply_inplace` to pixels crate and optimize it

### ISSUE THREAD

**Issue by sagudev** [servo/servo#33552]
https://github.com/servo/servo/blob/7fdaccde5501283708503e9a64efa578ac9ae7f7/components/canvas/webgl_thread.rs#L2841-L2848
while more performant (not tested just assumed because no fp operations) is in wrench:
https://github.com/servo/webrender/blob/bd7704a7091c51593cef9a3fe2ba86eb7e26359e/wrench/src/premultiply.rs#L21

we should move function to components/pixels, write benchmark and see if wrench version performs better.

**Comment by sagudev** [comment]
we still do not have optimized version

**Comment by nack098** [comment]
I think instead of using chunk_mut we can use the skip instead that might be a bit quicker.
and I have a question on do type casting necessary?

**Comment by nack098** [comment]
Ah I just see that someone did it.
But let me share my solution.
