### ISSUE TITLE
`fetch()` calls to custom protocols don't appear to work as expected

### ISSUE THREAD

**Issue by msub2** [servo/servo#33564]
While working on my own Servo-based browser I wanted to add the ability to change prefs at runtime. My initial attempt at this was to create an HTML page that would make fetch calls to an embedder-specific route with its own handler (in my example it was `moto:pref`) whenever a user clicked a button, but it seems the fetch calls to the embedder route just never seemed to happen. I could see in JS that the button onclick was working, and I don't recall seeing any errors when making the fetch call either.

In essence, to reproduce:
- In a custom protocol, add a route that does a println before sending the response
- Create a page that calls `fetch()` to that route
- Observe that println never occurs even when `fetch()` is called

**Comment by wusyong** [comment]
doing some quick check I found `servo:newtab` would call `scheme_fetch` in `net/fetch/methods.rs` but any `fetch` inside the page couldn't call it. However, they will all call `main_fetch` though.

**Comment by jdm** [comment]
Did you check if the fetch promise error handler is invoked?
