### ISSUE TITLE
Google sign in page takes forever to layout and is mostly unresponsive 

### ISSUE THREAD

**Issue by jdm** [servo/servo#33567]
Steps to reproduce:
1. Visit docs.google.com in a release build
2. Wait for a long time (10 seconds?) before the page contents appear
3. Try to type your email into the input
4. Watch characters appear at a rate of 1 every 5-10 seconds

I made a profiling build and ran it under Instruments on macOS, and it showed all of the time being spent inside flexbox layout code.

**Comment by mrobinson** [comment]
After adding instrumentation (#33647), it's obvious that the main issue here is block content size calculation during column flex layout. Caching should help and maybe we can avoid extra layouts entirely in some cases.

![image](https://github.com/user-attachments/assets/5e4ebc82-8472-47bd-b544-055a22be27f0)

(the greenish brown is block content size computation)
