### ISSUE TITLE
sanity check that Cargo.lock and ports/cef/Cargo.lock are consistent

### ISSUE THREAD

**Issue by metajack** [servo/servo#3360]
It would be nice if tidy (or something like it) could check this. Right now it's too easy to forget to update in both places.

**Comment by jdm** [comment]
Code: python/tidy.py

**Comment by SimonSapin** [comment]
Re my earlier comment, see https://github.com/servo/servo/issues/5973

**Comment by artiom** [comment]
1. Is this still relevant?
2. Let's say they are different, do you want to see the diff output or just a message saying that they are different?

I just checked and a difference between ```./components/servo/Cargo.lock``` and ```./ports/cef/Cargo.lock``` is quite large.

**Comment by metajack** [comment]
I think this better fixed by checking that the lock files don't change before and after build, which @Manishearth is trying to do with https://github.com/servo/saltfs/pull/119
