### ISSUE TITLE
Drop support for '--no-minibrowser' mode in servoshell

### ISSUE THREAD

**Issue by mukilan** [servo/servo#33626]
The `--no-minibrowser` mode was added as fallback option when we first added the mini-browser mode, to be used in case the mini-browser broke servoshell.

It is currently not very well tested and has few issues that remain open ([#33254](https://github.com/servo/servo/issues/33254) and [33255](https://github.com/servo/servo/issues/33255)). 

Supporting both modes in servoshell also makes it harder to extend and maintain. For example, one of the planned tasks for our Outreachy project is to move away from 'tinyfiledialog-rs' to something modern like [egui_modal](https://crates.io/crates/egui-modal). However, `egui_modal` requires an egui `Context` to work, which is not available in --no-minibrowser mode.

Given these reasons, it seems like a good time to drop support for `--no-minibrowser` mode from servoshell.

This will involve removing:
1. The CLI argument in https://github.com/servo/servo/blob/c7a4e4f627f0bf331cedc1700ddeb92ffcba4e78/components/config/opts.rs#L567 and config option in https://github.com/servo/servo/blob/c7a4e4f627f0bf331cedc1700ddeb92ffcba4e78/components/config/opts.rs#L133
2. Remove or update the conditional logic under `ports/servoshell/desktop` folder that uses the `opts::get().minibrowser`.

**Comment by danielap44** [comment]
I would like to be assigned this

**Comment by yomex96** [comment]
I'd like to work on this issue. Please assign it to me.
