### ISSUE TITLE
Avoid double negation in `is_empty_for_empty_cells()`

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#33678]
https://github.com/servo/servo/blob/f8933a57353aeca14a6cbc60b3cb0cf98cab6c5d/components/layout_2020/table/layout.rs#L76-L82

Could avoid the double negation by using `all()` instead of `any()`: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.all

**Comment by yemmyharry** [comment]
@jdm i would like to take this.

**Comment by mrobinson** [comment]
@yemmyharry This is addressed by #33688.
