### ISSUE TITLE
Add CanGc argument to reflect_dom_object

### ISSUE THREAD

**Issue by jdm** [servo/servo#33684]
This is a special case of #33683, because it requires a lot of repetitive work that all has to happen at once.

Code: https://github.com/servo/servo/blob/f8933a57353aeca14a6cbc60b3cb0cf98cab6c5d/components/script/dom/bindings/reflector.rs#L34

There are many callers of this function, so the resulting change will look very similar to #33144. There is no way to do this work incrementally or in chunks, unfortunately. You just add `CanGc::note()` in a lot of files.

**Comment by yemmyharry** [comment]
@jdm pls assign me to this?

**Comment by jdm** [comment]
Done! Please let me know if any of the description is unclear!

**Comment by jdm** [comment]
@yemmyharry Are you still working on this?

**Comment by taniishkaaa** [comment]
I can take this up if there's no update

**Comment by yemmyharry** [comment]
> @yemmyharry Are you still working on this?

@jdm yes i am

**Comment by willypuzzle** [comment]
This seems staling, could I grab this issue?

**Comment by jdm** [comment]
Please do!

**Comment by willypuzzle** [comment]
@jdm I haven't got very clear what this issue is about, I'm new to your ecosystem, please, could you gimme some explanation more?

**Comment by jdm** [comment]
@willypuzzle Start by reading https://github.com/servo/servo/issues/33140, which explains what the CanGc type is used for. The point of this issue is to take one specific function that currently breaks the chain of CanGc arguments by calling CanGc::note(), and making it take a CanGc argument instead.

**Comment by willypuzzle** [comment]
@jdm my PR is ready

**Comment by willypuzzle** [comment]
@jdm after my was merge, could we close this issue? Or it needs more work?

**Comment by jdm** [comment]
This one's complete; thanks! Now there's just followup work to propagate the new CanGc arguments up through callers.
