### ISSUE TITLE
XRWebGLBinding constructor is missing steps

### ISSUE THREAD

**Issue by jdm** [servo/servo#33682]
Specification: https://immersive-web.github.io/layers/#dom-xrwebglbinding-xrwebglbinding
Code: https://github.com/servo/servo/blob/05ecb8eddb3989ffcee51df5c2c86887fee8b7e8/components/script/dom/xrwebglbinding.rs#L64

Test; https://github.com/servo/servo/blob/main/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
Current failures: https://github.com/servo/servo/blob/main/tests/wpt/meta/webxr/layers/xrWebGLBinding_constructor.https.html.ini

Useful reference code: https://github.com/servo/servo/blob/05ecb8eddb3989ffcee51df5c2c86887fee8b7e8/components/script/dom/xrwebgllayer.rs#L107

**Comment by chickenleaf** [comment]
can i get this assigned? or is it to be closed?
