### ISSUE TITLE
Replace CanGc::note() calls with arguments passed by callers

### ISSUE THREAD

**Issue by jdm** [servo/servo#33683]
There are a lot of CanGc::note() calls in components/script: https://github.com/search?q=repo%3Aservo%2Fservo%20CanGc%3A%3Anote&type=code

This was introduced in #33144, but in general any use of CanGc::note() is an opportunity to make the code more precise by adding a CanGc argument that is passed by the caller instead (see #33386 for an example). This is a task that will take a very, very long time to do all at once, so it's fine to just focus on one caller at a time and propagate it upwards until it becomes too much work!

If you want to work on this task, just leave a comment linking to the specific call sites that you are going to focus on.

There is no need to write or run tests for changes related to this issue; it is strictly about making garbage collection hazards more visible when reading code, and if the code compiles then everything works!

**Comment by taniishkaaa** [comment]
Hey, I'd like to start with the calls in [ParseFromString](https://github.com/servo/servo/blob/2642f3ce338f5750c5cbc8878a29f8dffe832921/components/script/dom/domparser.rs#L93) and [DOMRect](https://github.com/servo/servo/blob/2642f3ce338f5750c5cbc8878a29f8dffe832921/components/script/dom/domrect.rs#L30)

**Comment by jdm** [comment]
We can ignore those for right now. One option might be to have two variants of each method, one with the argument and one without, but I would need to think more about if that's feasible.

**Comment by Otom-obhazi** [comment]
@mrobinson Please I will love to work on this task

**Comment by jdm** [comment]
@Otom-obhazi Ok! Please list the files that you will be addressing, like https://github.com/servo/servo/issues/33683#issuecomment-2397099840.

**Comment by chickenleaf** [comment]
I'd like to go ahead w these https://github.com/servo/servo/blob/c430645606396a300b57a4d9c909db959486ca4c/components/script/dom/imagedata.rs#L57

https://github.com/servo/servo/blob/c430645606396a300b57a4d9c909db959486ca4c/components/script/dom/blob.rs#L165

**Comment by jdm** [comment]
Some rules to follow when making processing each `CanGc::note()`, based on reading the surrounding code:
* if it's within a bare function or a method in a non-trait `impl` block, add the `CanGc` argument to the existing arguments and replace the `CanGc::note()` call
* if it's within a `task!` closure, keep the `CanGc::note()` call and do not add the `CanGc` argument to the existing arguments
* if it's within a trait method and the trait is defined outside of the script crate (eg. the `Drop` trait), keep the `CanGc::note()` argument and do not modify the method arguments
* if it's within a trait method and the trait is defined inside of the script crate and is one of the following traits, keep the `CanGc::note()` argument and do not modify the method arguments:
  * `VirtualMethods`
  * `FetchResponseListener`
* if it's within a trait method and the trait is defined inside of the script crate, add the `CanGc` argument to the list of arguments for the method in the original trait definition and replace the `CanGc::note()` call

**Comment by taniishkaaa** [comment]
I'd like to work on these next:
https://github.com/servo/servo/blob/8843a0e400745787faf4a23213cbfdf7e2158c73/components/script/fetch.rs#L161
https://github.com/servo/servo/blob/8843a0e400745787faf4a23213cbfdf7e2158c73/components/script/script_module.rs#L1096

**Comment by chickenleaf** [comment]
in this case: 
```
error[E0308]: mismatched types
   --> components\script\dom\bindings\structuredclone.rs:251:16
    |
251 |     read: Some(read_callback),
    |           ---- ^^^^^^^^^^^^^ incorrect number of function parameters
    |           |
    |           arguments to this enum variant are incorrect
    |
    = note: expected fn pointer `unsafe extern "C" fn(*mut js::jsapi::JSContext, *mut js::jsapi::JSStructuredCloneReader, *const js::jsapi::CloneDataPolicy, u32, u32, *mut libc::c_void) -> _`
                  found fn item `unsafe extern "C" fn(*mut JSContext, *mut JSStructuredCloneReader, ..., ..., ..., ..., ...) -> ... {read_callback}`
help: the type constructed contains `unsafe extern "C" fn(*mut js::jsapi::JSContext, *mut js::jsapi::JSStructuredCloneReader, *const js::jsapi::CloneDataPolicy, u32, u32, *mut libc::c_void, script_runtime::CanGc) -> *mut js::jsapi::JSObject {dom::bindings::structuredclone::read_callback}` due to the type of the argument passed
   --> components\script\dom\bindings\structuredclone.rs:251:11
    |
251 |     read: Some(read_callback),
    |           ^^^^^-------------^
    |                |
    |                this argument influences the type of `Some`
note: tuple variant defined here
   --> /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\option.rs:582:5
```

do I create a wrapper?

**Comment by chickenleaf** [comment]
i will be working on this next:
https://github.com/servo/servo/blob/27b25e869bc6d8d1b42da655895c27dc3c08f211/components/script/dom/mediastream.rs#L37

**Comment by chickenleaf** [comment]
working on `components/script/dom/custom_event.rs` now

**Comment by chickenleaf** [comment]
working on `components/script/dom/dommatrix.rs` next

**Comment by chickenleaf** [comment]
taking up `components/script/dom/xrsession.rs` next

**Comment by chickenleaf** [comment]
taking up `components/script/dom/testbinding.rs` next

**Comment by chickenleaf** [comment]
will be working on `components/script/dom/focusevent.rs` next.

1) the ones in `components/script/dom/xrsession.rs` and `components/script/dom/window.rs` are within a `!task` closure.

2) and the ones in `components/script/dom/servoparser/html.rs` lead you down a chain that requires modifying `std::iter::Iterator::next` and `xml5ever::serialize::Serialize`

**Comment by taniishkaaa** [comment]
I'm taking up these https://github.com/servo/servo/blob/92f12ff7cda3d3da667d2358ab3867b1dcc5b9a2/components/script/dom/gamepadevent.rs#L56
https://github.com/servo/servo/blob/92f12ff7cda3d3da667d2358ab3867b1dcc5b9a2/components/script/dom/stereopannernode.rs#L82

**Comment by Otom-obhazi** [comment]
@jdm [components/script/dom/gamepadevent.rs](https://github.com/servo/servo/pull/33828/files/c5674fd68b2622e54b176103cb934757ebacfcde#diff-66d7b1840cc8caa6e3aa972bf350e269aa20f2554eae53dfdcffe2e9dc1f83a3)

**Comment by chickenleaf** [comment]
working on `components/script/dom/fontfaceset.rs`, `components/script/dom/securitypolicyviolationevent.rs` and `components/script/dom/storageevent.rs` next

**Comment by jdm** [comment]
> @jdm [components/script/dom/gamepadevent.rs](https://github.com/servo/servo/pull/33828/files/c5674fd68b2622e54b176103cb934757ebacfcde#diff-66d7b1840cc8caa6e3aa972bf350e269aa20f2554eae53dfdcffe2e9dc1f83a3)

I believe that's already been covered by #33828

**Comment by taniishkaaa** [comment]
I will be working on these next
https://github.com/servo/servo/blob/b9ed45942d7b22d658955e9bcdd3db0bad1bba99/components/script/dom/xmlhttprequest.rs#L257
These two only require changes at one place
https://github.com/servo/servo/blob/b9ed45942d7b22d658955e9bcdd3db0bad1bba99/components/script/dom/wheelevent.rs#L77
https://github.com/servo/servo/blob/b9ed45942d7b22d658955e9bcdd3db0bad1bba99/components/script/dom/gpupipelineerror.rs#L53

**Comment by chickenleaf** [comment]
working on :
components/script/dom/htmltemplateelement.rs
components/script/dom/gainnode.rs

**Comment by taniishkaaa** [comment]
I'm starting with these https://github.com/servo/servo/blob/0a71c736f08fafb68d453133379dcc458fe4ac85/components/script/dom/htmltemplateelement.rs#L82
https://github.com/servo/servo/blob/0a71c736f08fafb68d453133379dcc458fe4ac85/components/script/dom/iirfilternode.rs#L76

**Comment by jahielkomu** [comment]
I will take up these 
``` components/script/dom/constantsourcenode.rs ```
``` components/script/dom/url.rs ```

**Comment by chickenleaf** [comment]
picking up these next:
components/script/dom/htmlscriptelement.rs
components/script/dom/gpuuncapturederrorevent.rs
components/script/dom/biquadfilternode.rs
components/script/serviceworker_manager.rs
components/script/dom/audiobuffersourcenode.rs

**Comment by taniishkaaa** [comment]
I'll be working on the following:
https://github.com/servo/servo/blob/066d3103bb82c75d6a50138aa5564e1ff9aca468/components/script/dom/promiserejectionevent.rs#L63
https://github.com/servo/servo/blob/066d3103bb82c75d6a50138aa5564e1ff9aca468/components/script/dom/rtcpeerconnectioniceevent.rs#L50
https://github.com/servo/servo/blob/066d3103bb82c75d6a50138aa5564e1ff9aca468/components/script/dom/websocket.rs#L581
https://github.com/servo/servo/blob/066d3103bb82c75d6a50138aa5564e1ff9aca468/components/script/dom/xrsessionevent.rs#L51

**Comment by taniishkaaa** [comment]
I'm going ahead w these:
https://github.com/servo/servo/blob/4a58616770214ead82da015f375fc5df59ad648c/components/script/dom/pannernode.rs#L188
https://github.com/servo/servo/blob/4a58616770214ead82da015f375fc5df59ad648c/components/script/dom/performanceobserver.rs#L74
https://github.com/servo/servo/blob/4a58616770214ead82da015f375fc5df59ad648c/components/script/dom/extendablemessageevent.rs#L89

**Comment by chickenleaf** [comment]
im picking these next:

components/script/dom/urlsearchparams.rs
components/script/dom/htmlsourceelement.rs
components/script/dom/globalscope.rs
components/script/dom/submitevent.rs
components/script/dom/webglcontextevent.rs
components/script/dom/rtcdatachannelevent.rs
components/script/dom/rtcicecandidate.rs
components/script/dom/htmlmediaelement.rs

**Comment by taniishkaaa** [comment]
Next Up:
components/script/dom/bindings/codegen/CodegenRust.py
components/script/dom/rtctrackevent.rs
components/script/dom/gpu.rs
components/script/dom/keyboardevent.rs
components/script/script_thread.rs
components/script/stylesheet_loader.rs

**Comment by wulanseruniati** [comment]
Hi, I'd like to work on this issue. My name is Wulan Seruniati Salim, and I'm an Outreachy internship applicant. I'd like to begin by working on the following components:
- components/script/body.rs
- components/script/dom/bindings/reflector.rs

**Comment by chickenleaf** [comment]
rechecking these:

components/script/dom/fontfaceset.rs
components/script/dom/servoparser/html.rs
components/script/dom/securitypolicyviolationevent.rs
components/script/dom/trackevent.rs
components/script/dom/htmlformelement.rs
components/script/dom/response.rs
components/script/dom/progressevent.rs
components/script/dom/gamepad.rs
components/script/dom/file.rs

**Comment by taniishkaaa** [comment]
I'll go through these next:
components/script/dom/eventtarget.rs
components/script/dom/focusevent.rs
components/script/dom/hashchangeevent.rs
components/script/dom/promiserejectionevent.rs
components/script/dom/audiobuffer.rs
components/script/dom/blob.rs
components/script/dom/errorevent.rs
components/script/dom/mouseevent.rs
components/script/dom/constantsourcenode.rs

**Comment by wulanseruniati** [comment]
I would now like to extend my focus to the following files for further improvements:
- components/script/body.rs
- components/script/dom/window.rs
- components/script/dom/xrsession.rs
