### ISSUE TITLE
Page's join_layout can report incorrect results

### ISSUE THREAD

**Issue by jdm** [servo/servo#3370]
As described in https://github.com/servo/servo/pull/3358#discussion_r17609526, the handle_reflow_complete logic in ScriptTask looks like it properly handles the case of waiting for the last-known script-initiated reflow to complete, but Page's join_layout does not. We should either make join_layout aware of this (by storing a page's last reflow ID in the Page itself and migrating the logic) or force the compositor to send reflow commands via the script task.

**Comment by mrobinson** [comment]
`join_layout` is gone now, I think.
