### ISSUE TITLE
Organize Bindings.conf alphabetically 

### ISSUE THREAD

**Issue by jdm** [servo/servo#33710]
There is currently no order in https://github.com/servo/servo/blob/028026bebe992431ede7c57b7e3065616d859026/components/script/dom/bindings/codegen/Bindings.conf and it's hard to see at a glance if there's already an entry for a particular interface. Let's organize it alphabetically!

**Comment by DileepReddyP** [comment]
Could I work on this, and is the procedure to fork the repo and open a pull request when I am done?

**Comment by jdm** [comment]
That's correct!
