### ISSUE TITLE
OpenHarmony CI is busted

### ISSUE THREAD

**Issue by jdm** [servo/servo#33712]
I have seen multiple dependabot PRs fail to.merhf with this error: https://github.com/servo/servo/actions/runs/11223221073/job/31197375341

**Comment by mukilan** [comment]
Could be caused by the [recent release](https://github.com/openharmony-rs/setup-ohos-sdk/releases/tag/v0.1.3) of the setup-ohos-sdk Github Action.

**Comment by mukilan** [comment]
I've created https://github.com/servo/servo/pull/33719 to pin the version of the action we use so that the merge queue can be unblocked. I guess we should merge this manually.
