### ISSUE TITLE
Throw NotSupported error instead of Type in XRSession::UpdateRenderState

### ISSUE THREAD

**Issue by jdm** [servo/servo#33714]
Code: https://github.com/servo/servo/blob/ffccc5c88b8d47efc777b0bc9d2620bed4bc84d7/components/script/dom/xrsession.rs#L619-L622
Specification: Step 1 of https://immersive-web.github.io/layers/#updaterenderstatechanges
Test: https://github.com/servo/servo/blob/main/tests/wpt/tests/webxr/layers/xrSession_updateRenderState.https.html
Expected results: https://github.com/servo/servo/blob/main/tests/wpt/meta/webxr/layers/xrSession_updateRenderState.https.html.ini

After changing the code, run `./mach test-wpt tests/wpt/tests/webxr/layers/xrSession_updateRenderState.https.html` to verify that the test now passes, then [update the expected results](https://book.servo.org/hacking/testing.html#updating-web-test-expectations).

**Comment by jdm** [comment]
We will need to enable the dom.webxr.layers.enabled pref in the webxr tests as well: https://github.com/servo/servo/blob/main/tests/wpt/meta/webxr/__dir__.ini

**Comment by chickenleaf** [comment]
hello! I'd like to work on this.

**Comment by chickenleaf** [comment]
I keep bumping into one of these when i test after the implementing the change:
```
 0:05.77 WARNING Got command init_succeeded in state running
 0:30.77 INFO Got timeout in harness
 0:30.77 TEST_END: TIMEOUT, expected OK - TestRunner hit external timeout (this may indicate a hang)
 0:30.77 INFO Pausing until the browser exits
```

```
 0:05.67 TEST_START: /webxr/layers/xrSession_updateRenderState.https.html
 0:05.67 WARNING Got command init_succeeded in state running
 0:28.54 INFO Pausing until the browser exits
 0:28.55 TEST_END: Test OK. Subtests passed 0/4. Unexpected 0
 0:28.55 INFO Pausing until the browser exits
 0:28.55 INFO No more tests
 0:28.55 INFO Closing logging queue
 0:28.55 INFO queue closed
 0:28.60 SUITE_END

web-platform-test
~~~~~~~~~~~~~~~~~
Ran 5 checks (4 subtests, 1 tests)
Expected results: 5
Unexpected results: 0
OK
0:28.60 INFO Got 0 unexpected results, with 0 unexpected passes
```
things I have tried:
- increasing the timeout of the test
- changing the logic to explicitly implement statement 1: If both newState’s [baseLayer] and newState’s [layers] are set, throw a [NotSupportedError] and abort these steps.
- used explicit `Error::DOM(DOMErrorName::NotSupportedError)`
- rebuilt everything on a fresh copy, ending tasks that are heavy on RAM.
- enabling both of these: `dom.webxr.layers.enabled:true`, `dom.webxr.enabled:true`
- random fiddling around with the test file. 

![image](https://github.com/user-attachments/assets/470ae470-fbcb-4370-960d-8780ad6a2022)

**Comment by Taym95** [comment]
> I keep bumping into one of these when i test after the implementing the change:
> 
> ```
>  0:05.77 WARNING Got command init_succeeded in state running
>  0:30.77 INFO Got timeout in harness
>  0:30.77 TEST_END: TIMEOUT, expected OK - TestRunner hit external timeout (this may indicate a hang)
>  0:30.77 INFO Pausing until the browser exits
> ```
> 
> ```
>  0:05.67 TEST_START: /webxr/layers/xrSession_updateRenderState.https.html
>  0:05.67 WARNING Got command init_succeeded in state running
>  0:28.54 INFO Pausing until the browser exits
>  0:28.55 TEST_END: Test OK. Subtests passed 0/4. Unexpected 0
>  0:28.55 INFO Pausing until the browser exits
>  0:28.55 INFO No more tests
>  0:28.55 INFO Closing logging queue
>  0:28.55 INFO queue closed
>  0:28.60 SUITE_END
> 
> web-platform-test
> ~~~~~~~~~~~~~~~~~
> Ran 5 checks (4 subtests, 1 tests)
> Expected results: 5
> Unexpected results: 0
> OK
> 0:28.60 INFO Got 0 unexpected results, with 0 unexpected passes
> ```
> 
> things I have tried:
> 
> * increasing the timeout of the test
> * changing the logic to explicitly implement statement 1: If both newState’s [baseLayer] and newState’s [layers] are set, throw a [NotSupportedError] and abort these steps.
> * used explicit `Error::DOM(DOMErrorName::NotSupportedError)`
> * rebuilt everything on a fresh copy, ending tasks that are heavy on RAM.
> * enabling both of these: `dom.webxr.layers.enabled:true`, `dom.webxr.enabled:true`
> * random fiddling around with the test file.
> 
> ![image](https://private-user-images.githubusercontent.com/56913210/374913295-470ae470-fbcb-4370-960d-8780ad6a2022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzA5OTQsIm5iZiI6MTcyODQ3MDY5NCwicGF0aCI6Ii81NjkxMzIxMC8zNzQ5MTMyOTUtNDcwYWU0NzAtZmJjYi00MzcwLTk2MGQtODc4MGFkNmEyMDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEwNDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZDBlNTg1MTkzN2IyYTE0MTU4YzlhZjIxNjFlNGRhODQ0Yjk2OTU4NTQ3MTI4Y2Q1ZDk5NzU3ZmUyNTQzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XuzBng_yNKUuTDWf1TCy6nbERu22W4SjK7EI66w3cHU)

This looks like the same result as shown in the main branch, can you share your patch?

**Comment by chickenleaf** [comment]
@Taym95 the change is in `fn UpdateRenderState(&self, init: &XRRenderStateInit, _: InRealm)` around line 677

```
// https://immersive-web.github.io/layers/#updaterenderstatechanges
// Step 1.
if init.baseLayer.is_some() {
    if self.has_layers_feature() {
        return Err(Error::NotSupported);
    }
    // https://github.com/immersive-web/layers/issues/189
    if init.layers.is_some() {
        return Err(Error::Type(String::from(
            "Cannot set WebXR layers and baseLayer",
        )));
    }
}
```

```
// https://immersive-web.github.io/layers/#updaterenderstatechanges
// Step 1.
if init.baseLayer.is_some() {
    if self.has_layers_feature() {
        return Err(Error::NotSupported);
    }
    // https://github.com/immersive-web/layers/issues/189
    if init.layers.is_some() {
        return Err(Error::NotSupported);
    }
}
```

**Comment by jdm** [comment]
Can you show the output of `git diff`? Have you tried adding a println! to the code you're changing to verify that it's executing when you run the test?

**Comment by chickenleaf** [comment]
git diff: 

```
diff --git a/components/script/dom/xrsession.rs b/components/script/dom/xrsession.rs
index 43ed08df3d..6b94cb9b2e 100644
--- a/components/script/dom/xrsession.rs
+++ b/components/script/dom/xrsession.rs
@@ -680,9 +680,7 @@ impl XRSessionMethods for XRSession {
             }
             // https://github.com/immersive-web/layers/issues/189
             if init.layers.is_some() {
-                return Err(Error::Type(String::from(
-                    "Cannot set WebXR layers and baseLayer",
-                )));
+                return Err(Error::NotSupported);
             }
         }

diff --git a/tests/wpt/meta/webxr/__dir__.ini b/tests/wpt/meta/webxr/__dir__.ini
index fd78c99e33..d387459e57 100644
--- a/tests/wpt/meta/webxr/__dir__.ini
+++ b/tests/wpt/meta/webxr/__dir__.ini
@@ -1 +1 @@
-prefs: [dom.webxr.test: true, dom.webgl2.enabled: true]
\ No newline at end of file
+prefs: [dom.webxr.test: true, dom.webgl2.enabled: true, dom.webxr.layers.enabled:true]
\ No newline at end of file
(END)
```

added println! as well turns out it is not being executed:
```
if init.baseLayer.is_some() {
    println!("Base layer is present.");
    if self.has_layers_feature() {
        return Err(Error::NotSupported);
    }
    // https://github.com/immersive-web/layers/issues/189
    if init.layers.is_some() {
        println!("Layers are present.");
        return Err(Error::NotSupported);
    }
}
```
should i be adding another test case to the test file? I thought the second `xr_session_promise_test` with the layers on had this case covered i am not sure...

**Comment by jdm** [comment]
I recommend adding log lines to the test file to determine which subtest is failing right now, and then figuring out if we can address that failure in our implementation!

**Comment by chickenleaf** [comment]
yes that makes sense 😭

**Comment by chickenleaf** [comment]
logs for before and after the implementation are the same: 

```
pid:26320 Starting test: without layers feature enabled
 0:08.19 pid:26320 Starting test: with layers feature enabled
 0:08.77 pid:26320 Starting subtest: baseLayer and singleLayer
 0:08.78 pid:26320 Starting subtest: multipleLayers
 0:08.78 pid:26320 Starting subtest: otherSessionLayer
 0:08.96 pid:26320 Starting subtest: baseLayer and singleLayer
 0:08.96 pid:26320 Starting subtest: multipleLayers
 0:08.97 pid:26320 Starting subtest: otherSessionLayer
 0:09.06 pid:26320 Starting subtest: baseLayer and singleLayer
 0:09.06 pid:26320 Starting subtest: multipleLayers
 0:09.06 pid:26320 Starting subtest: duplicateLayers
 0:09.06 pid:26320 Starting subtest: otherSessionLayer
 0:09.34 pid:26320 Starting subtest: baseLayer and singleLayer
 0:09.35 pid:26320 Starting subtest: multipleLayers
 0:09.35 pid:26320 Starting subtest: duplicateLayers
 0:09.35 pid:26320 Starting subtest: otherSessionLayer
 0:31.44 INFO Got timeout in harness
 0:31.44 TEST_END: TIMEOUT, expected OK - TestRunner hit external timeout (this may indicate a hang)
```

**Comment by chickenleaf** [comment]
by the way just thinking out loud cant we use a hashset instead of filter and count when we check for duplicate layers?

**Comment by chickenleaf** [comment]
could also use clamping for FOV values, clamping was a common clippy warning:
```
if fov < 0. {
    fov = 0.0001;
} else if fov > PI {
    fov = PI - 0.0001;
}
```

**Comment by jdm** [comment]
I keep being confused by the screenshot you took earlier which shows the TypeError is still being used. Are you running the tests using the same build? Is it possible that you have an older release build that bring used instead or something?

**Comment by chickenleaf** [comment]
i updated my local repository and did the whole ./mach bootstrap ./mach build again before i posted the screenshot. i am equally confused about the TypeError still being shown which is why i was trying to fiddle around with the tests and at one point expected results as well.

i do not see this being printed anywhere when i run the test:
```
fn UpdateRenderState(&self, init: &XRRenderStateInit, _: InRealm) -> ErrorResult {
    println!("Starting UpdateRenderState");
```

**Comment by jdm** [comment]
When I make the same change from https://github.com/servo/servo/issues/33714#issuecomment-2402218129 I get:
```
Unexpected Results
------------------
/webxr/layers/xrSession_updateRenderState.https.html
  UNEXPECTED-PASS Ensure XRSession throws appropriate errors when updating render state with layers feature enabled - webgl
  UNEXPECTED-PASS Ensure XRSession throws appropriate errors when updating render state with layers feature enabled - webgl2
```
This makes me strongly suspect that you are somehow not running the binary that contains the changes you have made to the source code.

**Comment by chickenleaf** [comment]
i shall recheck everything and get back soon. thank you so much!

**Comment by chickenleaf** [comment]
attemped everything again: 	
- Cleared temporary files using `cleanmgr`
- Cleared my visual studio `ComponentModelCache`
- Cleared `.vscode` directory, deleted target folder and then deleted the whole folder.
- Cloned my fork, cargo clean, cargo update and rebuilt with mach (did both the steps) (all in admin powershell)
- Checked env variables
	- `Get-ChildItem Env:RUST*` :
		- `RUSTUP_HOME                    C:\Users\<USERNAME>\.rustup`
	- ` Get-ChildItem Env:CARGO*` :
		- `CARGO_HOME                     C:\Users\<USERNAME>\.cargo`
- Ensured I have write permissions - ls -l components/script/dom/xrsession.rs
- Checked my disk space and memory usage (didnt seem like a concern)
	- These are my laptop specs:
		- Processor: AMD Ryzen 5 5600H with Radeon Graphics 3.30 GHz
		- RAM: 8.00 GB (7.34 GB usable)
		- 64-bit operating system, x64-based processor
		- 500gb SSD
- Checked my build stamp:
	- `source\repos\servo\target\debug> ls`
	- LastWriteTime was exactly the time I freshly built everything again.
		- d-----        10-10-2024  10:43 AM                build
		- -a----        10-10-2024  10:39 AM      193102336 servo.exe
- Modified the NotSupport return in visual studio and saved and on powershell checked the file (cat), the file seemed modified:
- 
![Screenshot (389)](https://github.com/user-attachments/assets/cd1ab258-4521-4ead-b9b0-30ea75cf85dc)

- Ran the test: 
![Screenshot (388)](https://github.com/user-attachments/assets/a5cae4d9-b244-4933-8b10-46ccfd402705)

- Ran the test in powershell with a timeout multiplier:
**0:50.45 TEST_END: TIMEOUT, expected OK - TestRunner hit external timeout (this may indicate a hang)**
 ```
0:03.62 wptserve INFO Starting http server on http://127.0.0.1:8000                              
0:03.71 wptserve INFO Starting http server on http://127.0.0.1:8001                              
0:03.81 wptserve INFO Starting http server on http://127.0.0.1:8002                              
0:03.90 wptserve INFO Starting http server on http://127.0.0.1:8003                              
0:03.98 wptserve INFO Starting https server on https://127.0.0.1:8443                            
0:04.06 wptserve INFO Starting https server on https://127.0.0.1:8444                            
0:04.15 wptserve INFO Starting https server on https://127.0.0.1:8445                            
0:04.22 wptserve INFO Starting https server on https://127.0.0.1:8446                            
0:04.41 wptserve INFO Starting http2 server on https://127.0.0.1:9000                            
0:04.54 SUITE_START: web-platform-test - running 1 tests                                         
0:04.54 INFO Using 1 child processes                                                             
0:04.54 INFO Starting runner              
0:05.44 TEST_START: /webxr/layers/xrSession_updateRenderState.https.html                         
0:05.44 WARNING Got command init_succeeded in state running                                      
0:50.45 INFO Got timeout in harness                                                              
0:50.45 TEST_END: TIMEOUT, expected OK - TestRunner hit external timeout (this may indicate a hang)  
0:50.45 INFO Pausing until the browser exits
```

**Comment by chickenleaf** [comment]
I do not quite want to give up, but I also dont know what else there is to do. And I dont want to have this issue hanging so if you'd like to unassign me and have someone who can work on it quick I'm all fine with that.

**Comment by chickenleaf** [comment]
@jdm  this is what i am supposed to get right? I think i might have finally figured out what i was doing wrong,,, 
![image](https://github.com/user-attachments/assets/6b1d6db4-3880-495f-804c-c92278d22c1f)

while i was working on CanGc I recieved this error:
```
method `Slice` has 5 parameters but the declaration in trait `dom::bindings::codegen::Bindings::BlobBinding::Blob_Binding::BlobMethods::Slice` has 4
```
and realised i need to ./mach build AFTER i make the NotSupport change, since i guess the test runs the target build files? I thought it just ran the file i directly changed.

**Comment by jdm** [comment]
Aha! Yes, that is correct. Yeah, the tests run the servo binary from the target directory, and the binary is made by compiling the source files.
