### ISSUE TITLE
Use `content_box_sizes_and_padding_border_margin_deprecated()` in `FlexItem::new()`

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#33736]
We can replace this: https://github.com/servo/servo/blob/c1b744b2b2c37cdb119a3d3f761822d22f938339/components/layout_2020/flexbox/layout.rs#L1026-L1038

with a single `content_box_sizes_and_padding_border_margin_deprecated()` call, like we are already doing in https://github.com/servo/servo/blob/c1b744b2b2c37cdb119a3d3f761822d22f938339/components/layout_2020/flexbox/layout.rs#L2021-L2022

**Comment by taniishkaaa** [comment]
I'd like to work on this!

**Comment by Otom-obhazi** [comment]
i will like to work on this
