### ISSUE TITLE
Handle inline margins in `layout_for_block_content_size()`

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#33779]
This is missing the inline margins:

https://github.com/servo/servo/blob/61a930402d5ac1f03530d7506960b8a04cfb974a/components/layout_2020/flexbox/layout.rs#L2523-L2525

We are correctly handling the block ones:

https://github.com/servo/servo/blob/61a930402d5ac1f03530d7506960b8a04cfb974a/components/layout_2020/flexbox/layout.rs#L2563-L2566

**Comment by taniishkaaa** [comment]
I'd like to work on this
