### ISSUE TITLE
Implement DOMRectList interface and switch Element.getClientRects to use it

### ISSUE THREAD

**Issue by jdm** [servo/servo#33799]
DOMRectList specification: https://drafts.fxtf.org/geometry/#DOMRectList
getClientRects specification: https://drafts.csswg.org/cssom-view/#dom-element-getclientrects 
Instructions for adding a new interface to Servo: https://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface

The CSSOM specification must have been updated since we first added getClientRects: https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface
There's a bunch of history for why it used to be `sequence<DOMRect>` in https://www.w3.org/Bugs/Public/show_bug.cgi?id=26200 and https://github.com/w3c/csswg-drafts/issues/1479.

**Comment by chickenleaf** [comment]
will this require writing tests as well?

**Comment by jdm** [comment]
It should already be covered by existing tests under the tests/wpt/test/css/cssom-view directory, I believe.

**Comment by jdm** [comment]
There are also tests under css/geometry which should start to pass.

**Comment by simonwuelker** [comment]
@chickenleaf are you working on this? I have an existing (unfinished) branch at https://github.com/simonwuelker/servo/tree/domrectlist, you can look at that if you want - just tell me if you do, so we don't duplicate our work (:

**Comment by chickenleaf** [comment]
> @chickenleaf are you working on this? I have an existing (unfinished) branch at https://github.com/simonwuelker/servo/tree/domrectlist, you can look at that if you want - just tell me if you do, so we don't duplicate our work (:

this is great!! i've been meaning to work on it, i shall see how i could build on your work and keep you posted.

**Comment by chickenleaf** [comment]
@simonwuelker hellooo! could you please update the branch with the latest changes, so i could add your fork as a remote and start out with some changes i have in mind or please let me know if you'd like me to do that bit and get started!!

**Comment by simonwuelker** [comment]
> could you please update the domrectlist branch with the latest changes

Done (:

> please let me know if you'd like me to do that bit

you can do whatever you want, I just felt like I should tell you that I already started to work a bit on this. You don't have to use anything i wrote.

FYI my current code compiles (even with crown) but panics when loading http://wpt.live/css/geometry/DOMRectList.html.
I didn't look into this much yet.
```
 assertion failed: !obj.is_null() (thread Script(1,1), at components/script/dom/bindings/conversions.rs:351)
   0: servoshell::backtrace::print
             at /home/alaska/servo/ports/servoshell/backtrace.rs:18:5
   1: servoshell::panic_hook::panic_hook
             at /home/alaska/servo/ports/servoshell/panic_hook.rs:40:17
   2: core::ops::function::Fn::call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:79:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2077:9
      std::panicking::rust_panic_with_hook
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:799:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:656:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
   6: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   7: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   8: core::panicking::panic
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:146:5
   9: script::dom::bindings::conversions::<impl mozjs::conversions::ToJSValConvertible for script::dom::bindings::reflector::Reflector>::to_jsval
             at /home/alaska/servo/components/script/dom/bindings/conversions.rs:351:9
  10: script::dom::bindings::conversions::<impl mozjs::conversions::ToJSValConvertible for script::dom::bindings::root::Root<script::dom::bindings::root::Dom<T>>>::to_jsval
             at /home/alaska/servo/components/script/dom/bindings/conversions.rs:560:9
  11: script::dom::bindings::codegen::Bindings::DOMRectListBinding::DOMRectList_Binding::get::{{closure}}::{{closure}}
             at /home/alaska/servo/target/debug/build/script-22ebd888a0c786bf/out/Bindings/DOMRectListBinding.rs:275:17
  12: script::dom::bindings::codegen::Bindings::DOMRectListBinding::DOMRectList_Binding::get::{{closure}}
             at /home/alaska/servo/target/debug/build/script-22ebd888a0c786bf/out/Bindings/DOMRectListBinding.rs:254:33
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:305:13
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panic/unwind_safe.rs:272:9
  15: std::panicking::try::do_call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
  16: __rust_try
 ```

**Comment by jdm** [comment]
The issue with the panic is caused by using new_inherited rather than a new method that returns a rooted value using DomRoot.

**Comment by chickenleaf** [comment]
@jdm this is to just give an update on what i've figured out (just started off with this today). so @simonwuelker has already created domrectlist.rs and its related struct and kind of all of its methods. I am thinking of adding a method called empty to it since in step 1 we have this :

> return an empty DOMRectList object

`mod.rs` also has been updated to contain the new module.

`DOMRectList.webidl` also has been created and webidl definition for DOMRectList has been added.

now under the `getClientRects` in `element.rs` going through the steps in the docs u provided, i think i am to find these helper methods to finish the 3 steps. ive found 2 helper methods as of now (i am assuming all the functions already exist within the files somewhere i only have to comb through them and find them). 
 1) `has_css_layout_box()`
  >  If the element on which it was invoked does not have an associated [box](https://drafts.csswg.org/css-display-4/#box) 
      
  2) `is_svg_element()`
  > If the element has an associated [SVG layout box](https://drafts.csswg.org/cssom-view/#svg-layout-box)

  3) cant quite find this am i to define a `getBBox()`? (looking through `svg.idl` line 30)
  > describes the bounding box of the element as defined by the SVG specification

  4) cant find the definitions for `getCTM()` and `getScreenCTM()` i think these are relevant to this step. am i to define them?
  > applying the [transforms](https://drafts.csswg.org/cssom-view/#transforms) that apply to the element and its ancestors

 5) is the relevant method to be defined in one of the svg .rs files?
  > If the element on which the method was invoked has a computed value for the [display](https://drafts.csswg.org/css-display-4/#propdef-display) property of [table](https://drafts.csswg.org/css-display-4/#valdef-display-table) or [inline-table](https://drafts.csswg.org/css-display-4/#valdef-display-inline-table)

 6) i have to define a method for this as well? 
  > include both the table box and the caption box, if any, but not the anonymous container box.

  >Replace each [anonymous](https://drafts.csswg.org/css-display-4/#anonymous) [block box](https://drafts.csswg.org/css-display-4/#block-box) with its child box(es) and repeat this until no anonymous block boxes are left in the final list.

**Comment by jdm** [comment]
Since we don't have any support for SVG in Servo beyond a couple IDL interfaces, all of the SVG-related functionality in that list is just a big TODO comment. However, since the implementation for getClientRects already exists, I don't think we should attempt to modify the actual rect calculation in this PR. It's not clear to me at this point whether the steps you listed are already implemented in the layout code, but we shouldn't mix behaviour changes with this interface change.

**Comment by chickenleaf** [comment]
![image](https://github.com/user-attachments/assets/e2aea386-afe7-4818-8f33-846cd1c5dd95)

will this do for this PR? range.rs as of now does not have any `getClientRects` method

**Comment by jdm** [comment]
Yep, that looks reasonable!

**Comment by chickenleaf** [comment]
> Yep, that looks reasonable!

What about the SVG related functionalities? Is that a priority right now? Are people working on it?

**Comment by jdm** [comment]
That's under discussion in #33310.

**Comment by chickenleaf** [comment]
> That's under discussion in #33310.

tysmmmm!!
