### ISSUE TITLE
Replace uses of downcast+is_some/is_none with is

### ISSUE THREAD

**Issue by jdm** [servo/servo#33797]
Code like this is unnecessary:
https://github.com/servo/servo/blob/3d4996402f86e4abbbaa0a390114a92999d147be/components/script/dom/dommatrix.rs#L79
We're performing a downcast operation, then throwing away the actual object and just checking if it succeeded or not. We should replace code like that with the [is](https://doc.servo.org/script/dom/bindings/inheritance/trait.Castable.html#method.is) API instead: https://github.com/servo/servo/blob/b178a2b6e2312a74f4a72781789c45a31ac164a7/components/script/dom/customelementregistry.rs#L746

Code to fix:
* https://github.com/servo/servo/blob/3d4996402f86e4abbbaa0a390114a92999d147be/components/script/dom/dommatrix.rs#L79
* https://github.com/servo/servo/blob/3d4996402f86e4abbbaa0a390114a92999d147be/components/script/dom/dommatrixreadonly.rs#L447
* https://github.com/servo/servo/blob/3d4996402f86e4abbbaa0a390114a92999d147be/components/script/fetch.rs#L184
* https://github.com/servo/servo/blob/3d4996402f86e4abbbaa0a390114a92999d147be/components/script/dom/globalscope.rs#L2929
* https://github.com/servo/servo/blob/3d4996402f86e4abbbaa0a390114a92999d147be/components/script/dom/htmlformelement.rs#L1107

No need to run any tests. If it compiles successfully, that's enough for a PR.

**Comment by taniishkaaa** [comment]
I'll get this done! :)
