### ISSUE TITLE
Ordered and unordered lists don't render correctly

### ISSUE THREAD

**Issue by cgaebel** [servo/servo#3380]
txti.es/how as rendered in firefox: https://www.dropbox.com/s/j0f3gb4l8s1b1w6/Screenshot%202014-09-16%2015.37.46.png?dl=0

as rendered in servo: https://www.dropbox.com/s/wf06hespndn5l1c/Screenshot%202014-09-16%2015.38.43.png?dl=0

Apologies if there's already a bug open for this.

**Comment by mbrubeck** [comment]
This seems to be fixed.
