### ISSUE TITLE
GC borrow hazard in ResizeObserver::broadcast_active_resize_observations

### ISSUE THREAD

**Issue by jdm** [servo/servo#33864]
We mutably borrow a member field in https://github.com/servo/servo/pull/33862/files#diff-2a44f61a5e5b7cf6b7a47e74a04dbec244b81507f0517bdc92484ba58e6e90c6R99 to iterate over them, the we allocate create new DOM objects in https://github.com/servo/servo/pull/33862/files#diff-2a44f61a5e5b7cf6b7a47e74a04dbec244b81507f0517bdc92484ba58e6e90c6R111 while that borrow is still active.

I see two possible solutions here:
1. change the borrow_mut() to a borrow() and wrap the members of ResizeObservation in Cell/RefCell (this delays the need for a mutable borrow until it's actually necessary to update a value)
2. instead of iterating over the values of self.observation_targets, loop over the indexes 0..self.observation_targets.borrow().len() and and then borrow to obtain the element at that index as necessary 

I think option 1 will result in more clear code.

**Comment by taniishkaaa** [comment]
I can work on this
