### ISSUE TITLE
GC borrow hazard in HTMLImageElement::finish_reacting_to_environment_change

### ISSUE THREAD

**Issue by jdm** [servo/servo#33903]
We hold a mutable borrow of a field of HTMLImageElement at https://github.com/servo/servo/blob/main/components/script/dom/htmlimageelement.rs#L1272, then call a method that can trigger a GC at https://github.com/servo/servo/blob/main/components/script/dom/htmlimageelement.rs#L1283 while the borrow is still outstanding. We should move the abort_request call outside of the `{}` block that already exists to limit how long the borrow is active.

**Comment by chickenleaf** [comment]
id like to be assigned this!

**Comment by jdm** [comment]
Fixed by #33904.
