### ISSUE TITLE
CryptoKey.algorithm should return a cached object

### ISSUE THREAD

**Issue by jdm** [servo/servo#33908]
From https://w3c.github.io/webcrypto/#cryptokey-interface-members:
>Returns the [cached ECMAScript object](https://w3c.github.io/webcrypto/#concept-cached-object) associated with the [[[algorithm]]](https://w3c.github.io/webcrypto/#dfn-CryptoKey-slot-algorithm) internal slot.

Meanwhile, the implementation creates a new instance each time it's called: https://github.com/servo/servo/blob/main/components/script/dom/cryptokey.rs#L106-L127

**Comment by jahielkomu** [comment]
@jdm perhaps we can can introduce a way to cache the created object and checking it's existence before creating another one. We perhaps could first store the object associated with the ``` [[algorithm]]``` internal slot privately and return it whenever Algorithm is called. I am just thinking out loud, you can direct on this issue differently.

**Comment by sagudev** [comment]
Actually specs clearly defines that for caching we use `_cached` slots: https://w3c.github.io/webcrypto/#concept-cached-object; and [cryptokey already contains such slots:  ..., [[algorithm]], [[algorithm_cached]] ,...](https://w3c.github.io/webcrypto/#dfn-CryptoKey-slot-algorithm).

**Comment by jdm** [comment]
As far as I know, the slots terminology is just way to represent a persistent value associated with a JS object. It doesn't imply a particular implementation strategy.

**Comment by jdm** [comment]
> @jdm perhaps we can can introduce a way to cache the created object and checking it's existence before creating another one. We perhaps could first store the object associated with the ` [[algorithm]]` internal slot privately and return it whenever Algorithm is called. I am just thinking out loud, you can direct on this issue differently.

Yes, this is similar to the MutNullableDom type we use in many places, that allows returning a previously created value or initializing it with a new one.

**Comment by sagudev** [comment]
> As far as I know, the slots terminology is just way to represent a persistent value associated with a JS object. It doesn't imply a particular implementation strategy.

Indeed, but I usually follow spec exactly.
