### ISSUE TITLE
GC borrow hazard in ModuleTree::append_handler

### ISSUE THREAD

**Issue by jdm** [servo/servo#33926]
We mutably borrow `self.promise` then immediately create a new promise object, which is an operation that can trigger a GC. The same hazard is present in ModuleTree::append_dynamic_module_handler as well.

**Comment by chickenleaf** [comment]
and this as well!

**Comment by jdm** [comment]
Use ./mach test-wpt tests/wpt/tests/html/semantics/scripting-1/the-script-element/module to verify that the implementation still works.

**Comment by taniishkaaa** [comment]
oop, i was going to work on this next :eyes:

**Comment by jdm** [comment]
To reproduce the actual GC panic:
1. `./mach build -d --debug-mozjs`
2. `./mach test-wpt /html/semantics/scripting-1/the-script-element/module/compilation-error-1.html --pref js.mem.gc.zeal.level=2 --pref js.mem.gc.zeal.frequency=1 --headless --timeout-multiplier=10`

**Comment by chickenleaf** [comment]
I've made all the changes to the ModuleTree functions, 

now when i run: 
`./mach test-wpt /html/semantics/scripting-1/the-script-element/module/compilation-error-1.html --pref js.mem.gc.zeal.level=2 --pref js.mem.gc.zeal.frequency=1 --headless --timeout-multiplier=10`

i get these, they seem to not be related to GC borrow hazards but should i be worried about these?:
```
PS C:\Users\USERNAME\source\repos\servo> ./mach test-wpt tests/wpt/tests/html/semantics/scripting-1/the-script-element/module
No build type specified so assuming `--dev`.
Running WPT tests with C:\Users\USERNAME\source\repos\servo\target\debug\servo.exe
GroupingFormatter: Could not get terminal control characters: No module named '_curses'
Running 123 tests in web-platform-tests

  ▶ TIMEOUT [expected OK] /html/semantics/scripting-1/the-script-element/module/dynamic-import/microtasks/basic.any.html

  ▶ OK /html/semantics/scripting-1/the-script-element/module/dynamic-import/blob-url.any.worker.html
  │   ▶ FAIL [expected PASS] Revoking a blob URL immediately after calling import will not fail
  └   └   → promise_test: Unhandled rejection with value: object "TypeError: Dynamic import failed"

  ▶ TIMEOUT [expected OK] /html/semantics/scripting-1/the-script-element/module/dynamic-import/microtasks/basic.any.worker.html
  │   ▶ TIMEOUT [expected PASS] import() should drain the microtask queue when fetching a new module
  └   └   → Test timed out

Ran 123 tests finished in 64.9 seconds.
  • 8 ran as expected.
  • 2 tests timed out unexpectedly
  • 2 tests had unexpected subtest results
```

**Comment by chickenleaf** [comment]
and this `./mach test-wpt /html/semantics/scripting-1/the-script-element/module/compilation-error-1.html --pref js.mem.gc.zeal.level=2 --pref js.mem.gc.zeal.frequency=1 --headless --timeout-multiplier=10` no longer crashes btw

**Comment by jdm** [comment]
Yep!
