### ISSUE TITLE
GC borrow hazard in ModuleTree::fetch_module_descendants

### ISSUE THREAD

**Issue by jdm** [servo/servo#33927]
We borrow `self.visited_urls` mutably, then later call `fetch_single_module_script` which might trigger a GC operation.

**Comment by chickenleaf** [comment]
id like to work on this!

**Comment by jdm** [comment]
Use `./mach test-wpt tests/wpt/tests/html/semantics/scripting-1/the-script-element/module` to verify that the implementation still works.

**Comment by jdm** [comment]
Fixed by #33942.
