### ISSUE TITLE
F-Droid release for Android

### ISSUE THREAD

**Issue by wrenix** [servo/servo#33934]
**Describe the new feature:**
It would be nice, to receive updates per [F-Droid](https://f-droid.org/en/about/) App (with an own Repo / nightly-repo or in the official Repo)

**Comment by mrobinson** [comment]
There are no plans currently to release the nightly builds in any app stores. They aren't really meant for consumption by end users.

**Comment by jdm** [comment]
Closing since this is not work we are planning on doing for the foreseeable future.

**Comment by ghost** [comment]
The app can be gotten through Obtainium in case you did not know. F-Droid has some security and practicality issues so Obtainium is often recommended over F-Droid. If you want you can even add F-Droid apps in there.

**Comment by wrenix** [comment]
With reproducible Build, F-Droid is more secure then Obtainium ...

Yes there was an security issues, but which are still there?

**Comment by ghost** [comment]
https://privsec.dev/posts/android/f-droid-security-issues/

All of these still stand. I do disagree that the inclusion policy is a negative since I am a big proponent of free software
