### ISSUE TITLE
Prefer `mem::take` over `mem::replace` with default value

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#33945]
https://github.com/servo/servo/blob/66695d2f7ee25782d3edfca32b74ff14bc9faa84/components/layout_2020/positioned.rs#L869

`Au::zero()` is the default value, so this could just use `mem::take`: https://doc.rust-lang.org/std/mem/fn.take.html

https://github.com/servo/servo/blob/66695d2f7ee25782d3edfca32b74ff14bc9faa84/components/layout_2020/positioned.rs#L870

Here it's an option so `Option::take` is even better: https://doc.rust-lang.org/std/option/enum.Option.html#method.take
But this is already about to land in #33941, so no need to handle it.

**Comment by chickenleaf** [comment]
should i leave `let old_max_size = self.computed_max_size.take();` in with my changes or wait for #33941 to merge and pull then send in a PR for this?

**Comment by Loirooriol** [comment]
You can post the PR now, but then you will need to resolve the merge conflict. Or you can wait.

**Comment by Loirooriol** [comment]
#33941 has landed
