### ISSUE TITLE
Intermittent failure in /XMLHttpRequest/event-timeout.htm

### ISSUE THREAD

**Issue by jdm** [servo/servo#3396]
This one's fun - the test sets a 5ms timeout on the XHR, and calls setTimeout with a delay of 10ms. The test asserts that the setTimeout is never reached, because the ontimeout handler ends the test. Our timer implementation is messy, in that both the XHR and setTimeout timers have their own tasks which send a message to the script task when they expire. That means that scheduling-wise we have no guarantees that lower timer values will expire and notify the script task before the timers with higher values.

**Comment by jdm** [comment]
Here's how I want to go about fixing this:
* create a new timer thread that controls all timers for a constellation
* internally, it has an event loop that selects on two input receivers
  * one watches for messages that add/remove a timer
  * the other is a timer that waits until the next web content timer should fire
* when a timer is added:
  * store its creation time and expiry time in a vector sorted by expiry date
  * if the new timer is in the head position (ie. it will expire soonest), reset the event loop timer to the new timer's expiration time
* when a timer is removed:
  * remove it from the sorted vector
  * if the new timer is in the head position (ie. it will expire soonest), reset the event loop timer to the new head timer's expiration time, or the maximum timer value if there is none
* when the event loop timer fires:
  * send a message to the script task associated with the head timer in the sorted vector
  * run the steps for removing a timer
  * if the timer should repeat, add it to the sorted vector and run the steps for adding a timer

**Comment by pgonda** [comment]
I am interested in working on this but I have a few questions.  Where would I implement a new thread?  And where would it be started?  Also vector and not a heap/priorityqueue?

**Comment by jdm** [comment]
@pgonda I think adding a `create_thread` function in `components/script/timer.rs` would make sense; it could return a `Sender` value that could be in the `Constellation` and passed to each new `ScriptTask` that is created. We could call the new function from `create_constellation` in `components/servo/lib.rs`.

**Comment by pgonda** [comment]
I have been building this out (slowly) but I have run into a wall.  I have this code [here](https://github.com/pgonda/servo/blob/timeout-event-loop-thread/components/script/timers.rs#L277) and I am trying to figure out how to switch the handlers this select item is listening for.  I can't overwrite ```timeout_port``` because it is borrowed.  All I can think of is adding these to a list but that seems like a bad idea.  Any tips? or I am going about this completely wrong?

**Comment by jdm** [comment]
I think the problem you face is that the code is trying to reuse the Select value (and the handles). I think the loop should recreate that every time instead; you can probably also use a pattern like this:
```rust
let mut timer_source = Some(horribly_inefficient_timers::oneshot(timeout));
loop {
    let timeout_port = timer_source.take().unwrap();
    let timeout_handle = select.handle(&timeout_port)
    let sel = Select::new();
    unsafe {
        timeout_handle.add();
    }
    let id = select.wait();
    if id == timeout_handle.id() {
        ...
        timer_source = Some(horribly_inefficient_timers::oneshot(new_timeout));
    }
}
````
Does that make sense? That should avoid overwriting timeout_port while it's still borrowed.

**Comment by pgonda** [comment]
That makes a lot of sense thanks!

**Comment by pgonda** [comment]
How does this look for the event loop? @jdm

**Comment by jdm** [comment]
That looks pretty solid!

**Comment by pgonda** [comment]
@jdm this is a silly question but I have been trying to figure out how to import the functions/structs into ```components/servo/lib.rs``` and ```components/compositing/constellation.rs```.  I have changed ```components/script/lib.rs:  68 mod timers;``` to ```components/script/lib.rs:  68 pub mod timers;```.  But when I try adding ```extern crate script;``` or ```extern crate timers``` I get an error.  What am I doing wrong?

**Comment by Manishearth** [comment]
`extern crate timers` won't work, you want to `use timers` (from within script) or `use script::timers` from a different crate.

`extern crate script` will only work in the compositing `lib.rs`

However, it might be worth keeping the dependency separate by moving this to `script_traits`

(I'm not sure what you need to use in `constellation.rs`)

**Comment by pgonda** [comment]
Thanks!! That works for the ```servo/lib.rs``` but I am still working on the ```compositing/constellation.rs``` know anyone that would be able to help?

**Comment by jdm** [comment]
compositing doesn't depend on the script crate, it depends on script_traits instead. Why does constellation.rs need something from the timers module? Can that something move into the script_traits crate instead?

**Comment by pgonda** [comment]
Alright, so I will move all the new timer code into ```script_traits::timer.rs```?  So that the ```Constellation``` can hold the sender to the thread, and pass it to newly created ScriptTasks.

**Comment by jdm** [comment]
I don't believe all of the code needs to move. You might be able to just move the TimerRequest enum to script_traits, if that's all that the Constellation code needs to reference.

**Comment by benschulz** [comment]
Are you still working on this, @pgonda? If not, I'd like to try my hand at it.

**Comment by jdm** [comment]
According to the conversation at the bottom of https://github.com/servo/servo/compare/master...pgonda:timeout-event-loop-thread you are welcome to tackle this, @benschulz. You should definitely at least look through the prior art there, if not steal it entirely :)
