### ISSUE TITLE
mach try: remove wpt-2013 from full and wpt

### ISSUE THREAD

**Issue by sagudev** [servo/servo#34023]
Currently `full` expands to `linux-wpt` which expands to `linux-wpt-2013` and `linux-wpt-2020`, but given the current state of layout 2013 I think we should make `linux-wpt` an `wpt` be an alias for `linux-wpt-2020` instead of both layout engines (this would match main/MQ which does `full`-`linux-wpt-2013`). Is that ok @mrobinson?

Remove:
https://github.com/servo/servo/blob/5d4b5514aa339d115d0ac9e1131eb7bef1d99a0b/python/servo/try_parser.py#L86-L87

Add `"wpt", "linux-wpt"` to
https://github.com/servo/servo/blob/5d4b5514aa339d115d0ac9e1131eb7bef1d99a0b/python/servo/try_parser.py#L90-L91

update expectations like https://github.com/servo/servo/blob/5d4b5514aa339d115d0ac9e1131eb7bef1d99a0b/python/servo/try_parser.py#L192

`mach test-scripts` runs try_parser tests

**Comment by taniishkaaa** [comment]
I'd like to work on this :)

**Comment by sagudev** [comment]
let's wait for approval of plan from @mrobinson

**Comment by Loirooriol** [comment]
Yeah, when I update Stylo I use T-full to cover all unit tests and such, but it also includes wpt-2013 which fails because the expectations aren't kept updated. So it's kind of useless to include that.

**Comment by mrobinson** [comment]
Yes, I think this it's a good idea to:
- Make `full` run all tests except layout 2013 WPT tests
- Make `wpt` default to mean `wpt-2020`
- Allow running 2013 tests, but only when explicitly triggering them / updating WPT results for the weekly import

**Comment by sagudev** [comment]
I've assigned you @taniishkaaa to the issue, if you have any questions feel free to ping me. Also ping me on PR, so I will notice it.
