### ISSUE TITLE
Create CachedFrozenArray abstraction

### ISSUE THREAD

**Issue by jdm** [servo/servo#34049]
There are a number of pieces of code that have the following patterns:
* a member field like `DomRefCell<Option<Heap<JSVal>>>`
* an implementation that first checks if there is a cached value present in the member field and returns it
* if there is no cached value present, compute a list of values, call to_frozen_array, and store the result in the member field, then return the value

There's always a comment about performing the operation in a particular order to maintain the safety invariants of the JS engine integration. This makes it a very good candidate for abstracting it into a type that each of these pieces of code can use instead! I'm imagining that the DomRefCell field moves into the new CachedFrozenArray type, and that type has one interface:
```rust
fn get_or_init<F: FnOnce() -> Vec<T>, T: ToJSValConvertible>(&self, f: F) -> JSVal;
```
It will accept a closure very similar to [MutNullableDom::or_init](https://doc.servo.org/script/dom/bindings/root/struct.MutNullableDom.html#method.or_init), allowing callers to provide the unique initialization logic while avoiding repeating the caching and JS engine safety logic.

* https://github.com/servo/servo/blob/a501572971d7ec6761aeab1f8f5dba00158bc1a6/components/script/dom/messageevent.rs#L305
* https://github.com/servo/servo/blob/a501572971d7ec6761aeab1f8f5dba00158bc1a6/components/script/dom/extendablemessageevent.rs#L210
* https://github.com/servo/servo/blob/a501572971d7ec6761aeab1f8f5dba00158bc1a6/components/script/dom/globalscope.rs#L3074

**Comment by mrobinson** [comment]
This sounds a lot like [`LazyCell`](https://doc.rust-lang.org/std/cell/struct.LazyCell.html). I wonder if the API could be modeled on that.

**Comment by Gae24** [comment]
I would like to look into this, since I need it for DataTransfer.
Where the abstraction should be added? I was thinking maybe in utils.rs?

**Comment by jdm** [comment]
Let's make a new frozenarray.rs under dom/bindings.

**Comment by Gae24** [comment]
Regarding its api design, I guess it should have a new fn that set it to None, or it has sense to accept a Heap<JSVal>?

**Comment by jdm** [comment]
If some caller requires that feature, then I think.an API to reset the value to undefined would make sense.
