### ISSUE TITLE
XRInputSourcesChangeEvent.added/.removed should store frozen array values

### ISSUE THREAD

**Issue by jdm** [servo/servo#34050]
Spec: https://immersive-web.github.io/webxr/#xrinputsourceschangeevent-interface
Implementation: https://github.com/servo/servo/blob/main/components/script/dom/xrinputsourceschangeevent.rs#L90-L97

Instead of converting a Rust array to an equivalent JS value, we should use the [to_frozen_array](https://doc.servo.org/script/dom/bindings/utils/fn.to_frozen_array.html) helper.

I hope we will see some new tests passing in `./mach test-wpt tests/wpt/tests/webxr/events_input_sources_change.https.html`.

**Comment by msub2** [comment]
Hmm, this will good for correctness but I think the only failing subtests remaining there have to do with the actual events being fired off, which I don't think will change from this.

Sidenote, whoever picks this up, make sure to update the rustdoc comment for `to_frozen_array` as well. The "array of ports" it refers to doesn't make much sense anymore as this helper is used in multiple files now.

**Comment by chickenleaf** [comment]
Can I be assigned this?

**Comment by chickenleaf** [comment]
when i use `to_frozen_array`, i get this clippy warning:

```
error[E0423]: cannot initialize a tuple struct which contains private fields
   --> components\script\dom\xrinputsourceschangeevent.rs:91:58
    |
91  | ...n_array(added, JSContext(*cx)));
    |                   ^^^^^^^^^
    |
note: constructor is not visible here due to private fields
   --> components\script\script_runtime.rs:882:22
    |
882 | pub struct JSContext(*mut RawJSContext);
    |                      ^^^^^^^^^^^^^^^^^ private field
help: consider making the field publicly accessible
   --> components\script\script_runtime.rs:882:22
    |
882 | pub struct JSContext(pub *mut RawJSContext);
    |                      +++
```

Is it advisable to follow its recommendation?

**Comment by jdm** [comment]
Use the public constructor instead: https://doc.servo.org/script/script_runtime/struct.JSContext.html#method.from_ptr

**Comment by chickenleaf** [comment]
@jdm i am not seeing any changes in the status of the tests :(
