### ISSUE TITLE
Scrolling is slow

### ISSUE THREAD

**Issue by nicoburns** [servo/servo#34051]
**Describe the bug:**
Go to any website that is has a reasonably long. For example https://en.wikipedia.org/wiki/Internet. Scrolling that page is very slow, and that makes Servo seem slow in general.

**To Reproduce:**
Scroll the page. Compare the scrolling speed with scrolling the same page in Chrome

**Platform:**
Tested on macOS 14.6.1, but I suspect this affects all platforms (although it may be particularly obvious when scrolling with a trackpad)

**Comment by nicoburns** [comment]
> This perception is mostly likely due to the lack of scroll acceleration.

That seems possible. Is Servo doing something special here? Because other winit-based apps seem to get this out of the box.

**Comment by mrobinson** [comment]
It's possible that Servo is not interpreting all of the data from winit events properly, but more investigation is necessary here.

**Comment by nicoburns** [comment]
Hmm... so it looks like Servo is dividing the pixel delta it gets from Winit by the hidpi scale factor. This somewhat makes sense as the delta is provided as `PhysicalPosition` and you might expect to apply a scroll delta in logical coordinates. But scroll speed seems to match that of other apps if this step is not performed and the provided delta is used without conversion.

Interestingly the unit typing is lost as soon as the conversion step occurs (we end up with plain `f32`s), so it's unclear which unit the Embedder API is expecting. It's possible that the scale conversion is happening twice.
