### ISSUE TITLE
HTMX library doesn't work because XPathEvaluator is not defined

### ISSUE THREAD

**Issue by AlexVasiluta** [servo/servo#34060]
**Describe the bug:**
Hello! I was experimenting with the [htmx](https://htmx.org) javascript library and wanted to see how my website looks on servo. The short answer is, it doesn't work, since [`XPathEvaluator`](https://developer.mozilla.org/en-US/docs/Web/API/XPathEvaluator) seems to not be defined. I could not find any existing issues pointing to this, so I decided to file a bug report.

**To Reproduce:**
- Using Servo nightly, go to https://htmx.org
- Look in the console, `XPathEvaluator` is not defined which makes it fail to properly load. Now, given that `htmx` is built to offer progressive enhancement for noscript users, it tries to work as well as it can, but it's still an issue in Servo.

**Platform:**
- Fedora Linux 40, x64, KDE

**Comment by jdm** [comment]
Huh, somehow I've never come across this part of the DOM specification before:
* https://dom.spec.whatwg.org/#interface-xpathevaluator
* https://dom.spec.whatwg.org/#xpathevaluatorbase

**Comment by vlindhol** [comment]
I'm slowly working on an XPath parser and evaluator written in pure Rust for Servo, happy to have this ticket assigned to me!
