### ISSUE TITLE
LoadBlocker::terminate is a common trigger for GC borrow hazards 

### ISSUE THREAD

**Issue by jdm** [servo/servo#34108]
The load blocker API requires a mutable borrow, which usually means the caller needs to mutably borrow a RefCell to obtain it. Since terminate also can trigger a GC in certain infrequent cases, this is both risky and over-cautious.

**Comment by jdm** [comment]
I think we need to change [LoadBlocker::terminate](https://github.com/servo/servo/blob/a3fda3893f1c48ba857e1fa9da0102632db66119/components/script/document_loader.rs#L52) from accepting `&mut Option<LoadBlocker>` to `&DomRefCell<Option<LoadBlocker>>`. This will allow us to extract the actual load blocker value before using it to call [finish_load](https://github.com/servo/servo/blob/a3fda3893f1c48ba857e1fa9da0102632db66119/components/script/document_loader.rs#L54), avoiding the need to keep the mutable borrow active during that call.

**Comment by jdm** [comment]
An alternative: add a Cell wrapper to https://github.com/servo/servo/blob/main/components/script/document_loader.rs#L38 so that we no longer need a mutable borrow at all in LoadBlocker::terminate. I think I still prefer the previous solution, though.

**Comment by taniishkaaa** [comment]
I can work on this!

**Comment by taniishkaaa** [comment]
are there any tests for this?

**Comment by jdm** [comment]
`./mach test-wpt tests/wpt/tests/html/semantics/embedded-content/the-img-element` should be good!
