### ISSUE TITLE
Builds with latest mozjs are failing

### ISSUE THREAD

**Issue by jdm** [servo/servo#34126]
From an attempted merge in #34087 (https://github.com/servo/servo/actions/runs/11657106102/job/32454174801):
```
error[E0432]: unresolved imports `js::glue::CreateReadableStreamUnderlyingSource`, `js::glue::DeleteReadableStreamUnderlyingSource`, `js::glue::ReadableStreamUnderlyingSourceTraps`
  --> components\script\dom\readablestream.rs:13:5
   |
13 |     CreateReadableStreamUnderlyingSource, DeleteReadableStreamUnderlyingSource,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `DeleteReadableStreamUnderlyingSource` in `glue`
   |     |
   |     no `CreateReadableStreamUnderlyingSource` in `glue`
14 |     ReadableStreamUnderlyingSourceTraps,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ReadableStreamUnderlyingSourceTraps` in `glue`
```
Presumably this is a regression from https://github.com/servo/mozjs/commit/2087c357972e7cb432437e50866907ad09274378, but I'm having trouble figuring out why. It only affects the code compiled from jsglue.cpp in mozjs-sys, and we include the js-confdefs.h file [as part of the build](https://github.com/servo/mozjs/blob/3a0a5f01ad3d497724828781ae7261853b02c29f/mozjs-sys/build.rs#L705-L726) so the MOZ_JS_STREAMS define _should_ be visible, as far as I can see.

**Comment by jdm** [comment]
cc @sagudev

**Comment by jdm** [comment]
It's also weird that this apparently only affects Windows, not other platforms.

**Comment by sagudev** [comment]
I'm able to reproduce it in mozjs repo https://github.com/servo/mozjs/actions/runs/11658582439/job/32457848379?pr=521

**Comment by sagudev** [comment]
try run running: https://github.com/sagudev/servo/actions/runs/11659638946
