### ISSUE TITLE
webgpu: Replace (Try)From (Try)Into with custom trait

### ISSUE THREAD

**Issue by sagudev** [servo/servo#34159]
As I already said in https://github.com/servo/servo/issues/33298#issuecomment-2331013056 we will need to roll our own trait for https://github.com/servo/servo/pull/33416 to work around orphan rules. One trait should be enough to handle all cases (Try variants will simply have T = Result<WGT, _>):

```rust
pub trait Into<T> {
    fn into_wgt(self) -> T;
}
```

**Comment by chickenleaf** [comment]
I could help with the refactoring!
