### ISSUE TITLE
Support `justify-self` on absolutely positioned elements

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#34226]
We obey `align-self` but not `justify-self`:
https://github.com/servo/servo/blob/4f4b7b1abf8919ff045da0295a45111a890a75e5/components/layout_2020/positioned.rs#L494-L497
https://github.com/servo/servo/blob/4f4b7b1abf8919ff045da0295a45111a890a75e5/components/layout_2020/positioned.rs#L522-L525

```html
<!DOCTYPE html>
<div style="position: relative; width: 100px; height: 100px; border: 3px solid">
  <div style="position: absolute; align-self: center; justify-self: center; background: cyan; height: 50px; width: 50px"></div>
</div>
<div style="position: relative; width: 100px; height: 100px; border: 3px solid">
  <div style="position: absolute; align-self: center; justify-self: center; background: cyan; height: 50px; width: 50px; inset: 0"></div>
</div>
<div style="position: relative; width: 100px; height: 100px; border: 3px solid">
  <div style="position: absolute; align-self: center; justify-self: center; background: cyan; height: 25px; width: 25px; inset: 25px 0 0 25px"></div>
</div>
```

| Servo | Blink |
| - | - |
| ![](https://github.com/user-attachments/assets/9f4a9858-8e6e-4b1d-9ad0-b4ec54339427) | ![](https://github.com/user-attachments/assets/31a02097-e86d-49f1-a9e3-b4d8aa51c6a9) |

**Comment by chickenleaf** [comment]
I'd like to try this out

**Comment by chickenleaf** [comment]
![image](https://github.com/user-attachments/assets/7b4fc21e-fe0f-4672-ae8c-0dd315e1be5b)

i dont have to send in the test file as well right?

**Comment by Loirooriol** [comment]
No, as long as there are existing tests.
