### ISSUE TITLE
ScriptParseHTML trace events are not a good measure of parsing time

### ISSUE THREAD

**Issue by delan** [servo/servo#34253]
We need a way to measure time actually spent in the parser, as opposed to the script thread’s other work (script, layout, building display lists, …). ScriptParseHTML seems to count the time spent executing scripts during the initial parse:

```html
<!doctype html><meta charset="utf-8">
<pre><script>
    function blockForOneSecond() {
        const tStart = performance.now();
        while (performance.now() - tStart < 1000);
    }
    document.writeln("start");
    blockForOneSecond();
    document.writeln("DOMContentLoaded");
    addEventListener("DOMContentLoaded", () => {
        blockForOneSecond();
        document.body.append("done");
    });
</script></pre>
```

![image](https://github.com/user-attachments/assets/dc60cc0f-f41a-4250-9098-b4e85291a80d)

[servo.pftrace.zip](https://github.com/user-attachments/files/17770280/servo.pftrace.zip)

**Comment by jdm** [comment]
The only way I can imagine doing this is to measure time spent evaluating scripts while parsing as a separate unit and subtract that once parsing is complete.
