### ISSUE TITLE
Make PropertyDeclarationBlock store a single vector of declarations

### ISSUE THREAD

**Issue by jdm** [servo/servo#3426]
For some of the CSSOM stuff, it would be nice to be able to iterate over all of the declarations without having to dip into each field. There are [some examples](http://mxr.mozilla.org/servo/search?string=impl%2Biterator%3C) of other iterator implementations for reference.

**Comment by frewsxcv** [comment]
Still working on this @gilles-leblanc ?

**Comment by gilles-leblanc** [comment]
@frewsxcv No. Someone else can take it. Good find.
