### ISSUE TITLE
Missing support for some alignment keywords on absolutely positioned elements

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#34282]
https://github.com/servo/servo/blob/11dfbd6f90bc7bc8b8d7485695548b5ad685d0e1/components/layout_2020/positioned.rs#L934-L943

This has some problems:
 - It handles `space-around` and `space-evenly`, which are content distribution keywords, even though here we can only have a self-alignment value
 - It's missing some values

The syntax is for `align-self` is:

```
auto | normal | stretch | <baseline-position> | <overflow-position>? <self-position>
<baseline-position> = [ first | last ]? && baseline
<overflow-position> = unsafe | safe
<self-position> = center | start | end | self-start | self-end | flex-start | flex-end
```

The syntax for `justify-self` also includes `left` and `right`.

So we need to handle:
 - `self-start`: like `start` in the block axis (because we lack `writing-mode`), but in the inline axis we need to check the`direction` of the abspos.
 - `self-end`: like `end` in the block axis (because we lack `writing-mode`), but in the inline axis we need to check the `direction` of the abspos.
 - `left`: we need to check the `direction` of the containing block
 - `right`: we need to check the `direction` of the containing block

`WritingMode` has some methods that can be useful, e.g. if `line_left_is_inline_start()` then `left` should be like `start`. See https://github.com/servo/stylo/blob/main/style/logical_geometry.rs

I think leaving the rest as `start` is fine (I should double-check at some point).

Testcase:

```html
<!DOCTYPE html>
<style>
.wrapper { display: inline-block; position: relative; width: 30px; height: 30px; border: 1px solid; }
.abspos { position: absolute; height: 15px; width: 15px; inset: 0; background: cyan; }
.ltr { direction: ltr }
.rtl { direction: rtl }
</style>
<div class="wrapper ltr"><div class="abspos ltr" style="justify-self: left"></div></div>
<div class="wrapper ltr"><div class="abspos ltr" style="justify-self: right"></div></div>
<div class="wrapper ltr"><div class="abspos rtl" style="justify-self: left"></div></div>
<div class="wrapper ltr"><div class="abspos rtl" style="justify-self: right"></div></div>
<br>
<div class="wrapper rtl"><div class="abspos ltr" style="justify-self: left"></div></div>
<div class="wrapper rtl"><div class="abspos ltr" style="justify-self: right"></div></div>
<div class="wrapper rtl"><div class="abspos rtl" style="justify-self: left"></div></div>
<div class="wrapper rtl"><div class="abspos rtl" style="justify-self: right"></div></div>
<br>
<div class="wrapper ltr"><div class="abspos ltr" style="place-self: self-start"></div></div>
<div class="wrapper ltr"><div class="abspos ltr" style="place-self: self-end"></div></div>
<div class="wrapper ltr"><div class="abspos rtl" style="place-self: self-start"></div></div>
<div class="wrapper ltr"><div class="abspos rtl" style="place-self: self-end"></div></div>
<br>
<div class="wrapper rtl"><div class="abspos ltr" style="place-self: self-start"></div></div>
<div class="wrapper rtl"><div class="abspos ltr" style="place-self: self-end"></div></div>
<div class="wrapper rtl"><div class="abspos rtl" style="place-self: self-start"></div></div>
<div class="wrapper rtl"><div class="abspos rtl" style="place-self: self-end"></div></div>
```

| Expected | Actual |
| - | - |
| ![](https://github.com/user-attachments/assets/66b0c29c-35dd-4ff2-bb03-a4ea01cfb684) | ![](https://github.com/user-attachments/assets/e88380a8-7682-4d7b-a169-200f2e0900dc) |

**Comment by taniishkaaa** [comment]
I'd like to work on this
