### ISSUE TITLE
Migrate duplicate version checks to cargo-deny

### ISSUE THREAD

**Issue by sagudev** [servo/servo#34393]
We just need to move entries from servo-tidy.toml to deny.toml and remove python code.

**Comment by chickenleaf** [comment]
Is there any particular order to be considered when shifting things to deny.toml?

**Comment by mrobinson** [comment]
I have already done this locally but there is an issue. Currently, we detect when a duplicate is allowed, but unnecessary so that we can keep the list clean. `cargo-deny` does not do this.

**Comment by sagudev** [comment]
I does issue warnings last time I checked. It might be possible to set them as errors.

**Comment by mrobinson** [comment]
Great, I will see if it is possible to make this work with my branch then.

**Comment by sagudev** [comment]
I've opened https://github.com/EmbarkStudios/cargo-deny/issues/725.

**Comment by sagudev** [comment]
Wow, that was fast, this issue is now fixed, but it might take some time to get it released.

Also cargo-deny supports [exact version specifiers](https://github.com/EmbarkStudios/cargo-deny/blob/0c8cb9e89ff31ca8c696851d2329c1c983439caa/deny.toml#L34) per https://github.com/EmbarkStudios/cargo-deny/issues/725#issuecomment-2506128781, which should already warn/error.
