### ISSUE TITLE
Taffy misses margin when calling `used_size_as_if_inline_element_from_content_box_sizes()`

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#34417]
Taffy is calling `used_size_as_if_inline_element_from_content_box_sizes()` with the padding&border sums:

https://github.com/servo/servo/blob/d2d3407501b83d03db522b5dde5e159073fd9e4b/components/layout_2020/taffy/layout.rs#L171

However, this method expects the padding&border&margin sums:

https://github.com/servo/servo/blob/d2d3407501b83d03db522b5dde5e159073fd9e4b/components/layout_2020/replaced.rs#L502

So Taffy should do something like

https://github.com/servo/servo/blob/d2d3407501b83d03db522b5dde5e159073fd9e4b/components/layout_2020/replaced.rs#L456

**Comment by taniishkaaa** [comment]
I'll get this done :)
