### ISSUE TITLE
OpenHarmony CI builds are broken due to missing license acceptance 

### ISSUE THREAD

**Issue by jdm** [servo/servo#34411]
Eg https://github.com/servo/servo/actions/runs/12055188494/job/33614998083

cc @jschwe

**Comment by jschwe** [comment]
Hotfixed by yanking the 5.0.1 release from the github mirror https://github.com/openharmony-rs/ohos-sdk/releases.

This should be sufficient to get CI working again, and I will investigate a more proper tommorow.

**Comment by jschwe** [comment]
I think the issue is resolved for now - Please re-open if it turns out to be not fixed
