### ISSUE TITLE
Make it easy to debug wpt tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#3451]
We have `mach test-wpt --include subdir/test.html` which is a good start, but when you want to run a test under gdb, you need to run the webserver manually in the web-platform-test directory and run Servo yourself. It would be nice to add a flag to test-wpt (or a separate command) that would do all that for you, presumably loading it up in your favourite debugger.

**Comment by daoshengmu** [comment]
Is there any update for this? I am solving WPT for the WebGL function implementation. For some tests, I have no idea why is not pass. So, I need a debug method to help me. Previously, I use ```println!``` to print the debug log to help me. But just two days ago, it didn't work... I don't know why I can't see the log on my console. Any suggestion?

**Comment by jdm** [comment]
`./mach test-wpt path/to/test.html --debugger=[lldb|gdb]` works fine. For seeing stdout from tests, you need to use `./mach test-wpt path/to/test.html --log-mach -`.

**Comment by mrobinson** [comment]
@jdm So is there more work to be done here or can this issue be closed?
