### ISSUE TITLE
CI: Self hosted Windows github runner can't compile mozjs from source

### ISSUE THREAD

**Issue by jschwe** [servo/servo#34603]
**Describe the bug:**

See https://github.com/servo/servo/actions/runs/12303074454/job/34337398349?pr=34601
For some reason the mozjs build system can't find python / python3 on self hosted runners.

**To Reproduce:**

See https://github.com/servo/servo/pull/34601, which forces a build of mozjs from source by bumping the mozjs version, which means that there is no prebuilt mozjs artifact available.

**Platform:**
Windows self hosted CI runner

**Comment by mukilan** [comment]
On a related note, I noticed that we are always doing a [ `debug` build of mozjs](https://github.com/servo/mozjs/blob/d6c3bd9a9a86a53c627355241b015fa7768ed688/.github/workflows/build.yml#L79) to generate the pre-built mozjs binaries.  

Shouldn't our nightly builds, which use `production` profile with LTO enabled always build from source to take advantage of LTO? Also, do we need to create separate pre-built binaries for "release" builds of mozjs that passes the[ `--enable-optimize` flag](https://github.com/servo/mozjs/blob/d6c3bd9a9a86a53c627355241b015fa7768ed688/mozjs-sys/mozjs/build/moz.configure/toolchain.configure#L13) when configuring?

**Comment by jschwe** [comment]
The matrix means that two different jobs are spawned, one with debu-mozjs and one with the streams feature. We only upload the streams feature artifacts.

**Comment by jschwe** [comment]
To enable cross-language lto, there are some more requirements that need to be fulfilled, namely passing the linker-plugin-lto options to both rust and C, and ensuring that the tool chains with the same LLVM version is used for both rust and C compilation

**Comment by mukilan** [comment]
> The matrix means that two different jobs are spawned, one with debu-mozjs and one with the streams feature. We only upload the streams feature artifacts.

I didn't mean 'debug' as equivalent to DEBUG_MOZJS. I mean we trigger the cargo build with rust's "debug" profile. My though was we should also do build a "release" cargo build, which would then tell the build.rs script to pass `--enable-optimize` when configuring the SM build.

**Comment by sagudev** [comment]
Actually, I think default SM builds have optimize enabled, but it is disabled when debugmozjs feature is true: https://github.com/servo/mozjs/blob/d6c3bd9a9a86a53c627355241b015fa7768ed688/mozjs-sys/makefile.cargo#L22-L24

**Comment by sagudev** [comment]
> ensuring that the tool chains with the same LLVM version is used for both rust and C compilation

clang/llvm binaries are chaotic, official repo provides binaries on best effort basis (there is a lot of missing).

**Comment by mukilan** [comment]
I believe #34632 should fix the issue with Python not being found. But as mentioned in https://github.com/servo/servo/pull/34601#issuecomment-2544607275, we probably need to install `ccache` in the runner image.

In any case, it seems like it would be  a good idea to always build from source in nightly jobs, given the only run once per day.
