### ISSUE TITLE
Make Promise::new_resolved/new_rejected accept any ToJSValConvertible value

### ISSUE THREAD

**Issue by jdm** [servo/servo#34614]
There's a lot of code in #34064 that returns rejected/resolved promises that is made less clear by requiring the caller to explicitly root a value, stash the JS conversion in it, then pass the handle.

**Comment by jdm** [comment]
@willypuzzle You could work on this issue. The methods are https://github.com/servo/servo/blob/main/components/script/dom/promise.rs#L150 and https://github.com/servo/servo/blob/main/components/script/dom/promise.rs#L162, and you could use https://github.com/servo/servo/blob/a37a9f68b810e0e7d2a2d4cce4b9e5706288c434/components/script/dom/bindings/utils.rs#L157-L160 as a model for how to take a generic ToJSValConvertible argument instead of HandleValue and convert it into a handle.

**Comment by willypuzzle** [comment]
> @willypuzzle You could work on this issue.

Sure! Let me dig down the meaning of it and I'll let you know if I need more explanations.

**Comment by willypuzzle** [comment]
@jdm I have got that I need to change the interface of both methods like:

```
pub fn new_resolved(
        global: &GlobalScope,
        cx: SafeJSContext,
        value: Box<dyn ToJSValConvertible>,
) -> Fallible<Rc<Promise>>
```

is it correct?

**Comment by jdm** [comment]
@willypuzzle We'll want to use a generic type like `impl ToJsValConvertible` instead of a boxed trait object, but yes.

**Comment by willypuzzle** [comment]
@jdm I issued the PR, please, would you take a look.

**Comment by simonwuelker** [comment]
This was completed in https://github.com/servo/servo/pull/34658
