### ISSUE TITLE
Protocol conversion in websocket constructor is missing

### ISSUE THREAD

**Issue by jdm** [servo/servo#34633]
https://websockets.spec.whatwg.org/#dom-websocket-websocket has steps 4 & 5 that accept http and https URLs and convert them internally to ws and wss URLs. Servo's implementation in https://github.com/servo/servo/blob/a37a9f68b810e0e7d2a2d4cce4b9e5706288c434/components/script/dom/websocket.rs#L196 is missing those steps.

Tests: `./mach test-wpt tests/wpt/tests/websockets/Create-http-urls.any.js`, see https://book.servo.org/hacking/testing.html#updating-a-test about updating our expected results.

**Comment by longvatrong111** [comment]
Can I try this one?

**Comment by jdm** [comment]
Please do!
