### ISSUE TITLE
webgpu runs are busted

### ISSUE THREAD

**Issue by sagudev** [servo/servo#34700]
try run: https://github.com/sagudev/servo/actions/runs/12408438566 where not a single CTS job reached end, all were killed.
last known good: ~~a37a9f68b810e0e7d2a2d4cce4b9e5706288c434~~, f757fa46acc865f42205d152dd06e381a674f788: https://github.com/sagudev/servo/actions/runs/12411376884
first bad: ~~e2a0ac07ff2aeece5485f491210e77ebc2af127c, 026d3717177def1b77e8790f3f045feea66df872, b7e528d2ff~~88a35b3cc99b6bf47099f1551b6a2349bba76c15: https://github.com/sagudev/servo/actions/runs/12412241615

=> This is regression of #34632.

**Comment by sagudev** [comment]
This is caused by https://github.com/servo/servo/pull/34632 cc @mukilan.

**Comment by mukilan** [comment]
I'm seeing some errors now in my local run:

```
STDERR: Queue <multiprocessing.queues.Queue object at 0x7f1201f313d0> is closed
STDERR:
STDERR: raise ValueError(f"Queue {self!r} is closed")
STDERR: ValueError
STDERR: :
STDERR: Queue <multiprocessing.queues.Queue object at 0x7f1201ed99d0> is closed
STDERR:
STDERR: self.send_message("init_failed")
STDERR:   File "/home/mukilan/dev/servo.git/review/tests/wpt/tests/tools/wptrunner/wptrunner/testrunner.py", line 275, in send_message
STDERR:
STDERR: self.command_queue.put((command, args))
STDERR:   File "/nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/multiprocessing/queues.py", line 88, in put
STDERR:
STDERR: raise ValueError(f"Queue {self!r} is closed")
STDERR: ValueError
STDERR: :
STDERR: Queue <multiprocessing.queues.Queue object at 0x7f1201e94e30> is closed
```

I guess it is probably the python version that is the problem. I'll try with Python 3.10.

**Comment by sagudev** [comment]
I suspect that they get killed due to OOM or smth like that. I never really run full suite on my pc because it's to slow.

**Comment by sagudev** [comment]
try run with py 3.10 in progress: https://github.com/sagudev/servo/actions/runs/12414105447

**Comment by sagudev** [comment]
Python 3.10 works, testing python 3.11: https://github.com/sagudev/servo/actions/runs/12416294819
