### ISSUE TITLE
same mutex is locked twice sequentially 

### ISSUE THREAD

**Issue by sagudev** [servo/servo#34734]
https://github.com/servo/servo/blob/1157fa28b39ee6e80c763f6929ebbb313aac6040/components/net/fetch/methods.rs#L104-L113

instead we should just lock it once, store mutexguard in scoped var and do set_attribute on that var.

**Comment by wulanseruniati** [comment]
Hello. I'd like to take this issue and work on refactoring the code to lock the mutex only once. Let me know if there are any specific guidelines or considerations I should keep in mind while working on this.

**Comment by sagudev** [comment]
Just make sure that mutexguard is stored in scoped var so it get dropped as soon as possible and ping me on PR.
