### ISSUE TITLE
cloneNode on a ShadowRoot should always throw an error

### ISSUE THREAD

**Issue by jdm** [servo/servo#34739]
Spec: https://dom.spec.whatwg.org/#dom-node-clonenode
Test: `tests/wpt/tests/shadow-dom/Node-prototype-cloneNode.html`
Code: https://github.com/servo/servo/blob/ffccc5c88b8d47efc777b0bc9d2620bed4bc84d7/components/script/dom/node.rs#L2799-L2801

**Comment by willypuzzle** [comment]
can I grab this?

**Comment by jdm** [comment]
Yep!
