### ISSUE TITLE
Element::attach_shadow is missing check for valid custom element name

### ISSUE THREAD

**Issue by jdm** [servo/servo#34743]
Step 2 of https://dom.spec.whatwg.org/#concept-attach-a-shadow-root says to check for a [valid shadow host name](https://dom.spec.whatwg.org/#valid-shadow-host-name), but the [implementation](https://github.com/servo/servo/blob/ffccc5c88b8d47efc777b0bc9d2620bed4bc84d7/components/script/dom/element.rs#L490-L513) only looks at the valid built-in element names.

Test: `./mach test-wpt tests/wpt/tests/custom-elements/CustomElementRegistry.html`

**Comment by stevennovaryo** [comment]
Hi! I would like to do this one.

**Comment by jdm** [comment]
Go for it!
