### ISSUE TITLE
Document should get encoding charset from HTMLMetaElement.charset

### ISSUE THREAD

**Issue by jdm** [servo/servo#34768]
Spec: https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-charset
Code: `components/script/dom/htmlmetaelement.rs`
Tests: `./mach test-wpt tests/wpt/tests/encoding/big5-encoder.html` (many more tests in tests/wpt/tests/encoding/ should also pass)

We should add logic to the `attribute_mutated` method to check if a charset attribute is modified, then use [encoding_from_whatwg_label](https://docs.rs/encoding/latest/encoding/label/fn.encoding_from_whatwg_label.html) to obtain a value that we can pass to `Document::set_encoding`.

**Comment by Loirooriol** [comment]
But mutating the attribute value doesn't change the encoding of the document, right? This logs `Big5` twice:

`data:text/html,<DOCTYPE html><meta charset="big5"><script>console.log(document.characterSet); document.querySelector("meta").setAttribute("charset", "utf-8"); console.log(document.characterSet);</script>`

Also, I guess encountering `<meta charset>` means that all the HTML until that point needs to be re-decoded?

Is this really E-less-complex? If so, it affects gazillions of tests, so it would be good to prioritize it.

Seems basically the same as #24898, though.

**Comment by simonwuelker** [comment]
> Also, I guess encountering `<meta charset>` means that all the HTML until that point needs to be re-decoded?

Yes, that's Step 5 & 6 from https://html.spec.whatwg.org/#change-the-encoding.
(Called from https://html.spec.whatwg.org/#parsing-main-inhead)

There is an existing TODO in html5ever about handling meta-charset: https://github.com/servo/html5ever/blob/8415d500150d3232036bd2fb9681e7820fd7ecea/html5ever/src/tree_builder/rules.rs#L117

**Comment by jdm** [comment]
Oof, ok, definitely more complexity here than I believed.

**Comment by jdm** [comment]
To try to keep information about solving this consolidated in one place, I'm going to close this issue. We can keep tracking #24898.
