### ISSUE TITLE
`lint_unrooted_ty` should be able to check for non-script stuff containing JS<T>

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#3484]
Currently, [`lint_unrooted_ty`](https://github.com/servo/servo/blob/master/components/plugins/lints.rs#L50) won't throw a fuss if the type is a `Vec<JS<T>>` or `Option<JS<T>>`. This isn't a major problem at the moment, but it does create some loopholes. A check should be added that either traverses the tree (ignoring `JSRef<T>` and friends) or has explicit checks which unwrap `Option` and `Vec` (and any other constructs which we can expect to ever contain a `JS<T>`).

Also, we can perhaps restrict usage of [`from_rooted`](http://doc.servo.org/script/dom/bindings/js/struct.JS.html#method.from_rooted) to `new_inherited()` and `new()`

**Comment by nox** [comment]
It complains about `Vec<JS<T>>` and friends now.
