### ISSUE TITLE
bors: reduce amount of github messages

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#3502]
For a successful build like #3499 bors typically sends five github comments:

1. Saw approval
2. Merging
3. Merge ok
4. All tests pass
5. Fast-forwarding master

For people with github email notification enabled, this is a lot of email noise. The first three messages generally happen within seconds of each other and could be combined into one. The last two are sometimes a few minutes apart (why, btw?) but can probably still be combined.

Or, we could get rid of these comments entirely (except one, only when the build fails), and rely on GitHub’s [Status API](https://developer.github.com/v3/repos/statuses/)?

CC: @metajack, @larsbergstrom

**Comment by edunham** [comment]
Today Homu leaves only 3 messages: approval, status, and result. There [appears](https://github.com/servo/homu/blob/master/cfg.sample.toml#L77) to be Homu support for using the status API, but we aren't currently using it in production. 

@SimonSapin are Homu's current comments still too spammy?

**Comment by SimonSapin** [comment]
Yes, it’s better now. Thanks for triaging :)

**Comment by SimonSapin** [comment]
We do have homu using the status API. For example in https://github.com/servo/servo/pull/10546 click "View details" at the bottom and see

> ✓ homu  Test successful  [Details](http://build.servo.org/builders/arm64/builds/254)

The only thing is that the Details link is missing while the build is running (when the status is yellow).
