### ISSUE TITLE
Inline absolute hypothetical boxes don't work

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#3507]
Minimal test case:

    <!DOCTYPE html>
    <html>
    <body>
    Hello<span style="position: absolute; top: 32px;">world!</span>
    </body>
    </html>

Per the spec, "world!" should have the inline position it would have had if it were not absolutely positioned, but it doesn't. I think we only support block hypothetical boxes at the moment. This is kinda annoying because now we'll need to have the concept of a hypothetical *fragment*, not just a hypothetical *flow*, but c'est la vie.

Breaks Reddit /r/rust.

**Comment by nox** [comment]
Ain't that fixed?

**Comment by pcwalton** [comment]
Yes.
