### ISSUE TITLE
ctr+l is broken on mac

### ISSUE THREAD

**Issue by jdm** [servo/servo#3510]
`2014-09-28 14:45:01.058 servo[9448:d07] +[NSAlert alertWithMessageText:defaultButton:alternateButton:otherButton:informativeTextWithFormat:NSTextFieldallocinitWithFrame:]: unrecognized selector sent to class 0x7fff78958da8`

**Comment by frewsxcv** [comment]
I just tried this and am unable to reproduce the crash. Are you able to reproduce this @jdm?

**Comment by jdm** [comment]
It was never a crash. We just stopped being able to pop up a simple alert box that could take input.

**Comment by frewsxcv** [comment]
If anyone in the future reads this and wants clarification:

I assume there is some feature of Servo that allows `Ctrl - L` to be pressed and a web address input box appears. This is currently broken on OSX.

**Comment by tyoc213** [comment]
Yeah, I just build it in release and I can't do https://github.com/servo/servo#keyboard-shortcuts ```Ctrl+L``` nor ```Cmd+L```on a page.

**Comment by jdm** [comment]
This disappeared as part of the switch from GLFW to Glutin, I believe. We have no handling for ctr/cmd+l present in http://mxr.mozilla.org/servo/source/ports/glutin/window.rs#640 .

**Comment by jdm** [comment]
Oh, looks like this was very intentional: https://github.com/servo/servo/commit/c39852a3f4829ac6e0fd4e303600ca8e880fa412
