### ISSUE TITLE
Stuck at 'Loading' if page includes ™ in Droid Serif 

### ISSUE THREAD

**Issue by duckinator** [servo/servo#3578]
Expected outcome: http://marie.codes finishes rendering.

Actual outcome: ![screenshot-loading servo](https://cloud.githubusercontent.com/assets/39698/4521591/b8ea55d2-4d15-11e4-8b45-df01d49991a0.png)

Google [finishes loading and rendering](https://i.imgur.com/b4WEevV.png).

Test case: https://gist.github.com/duckinator/d0b03e1aa5277f1cdf59

In the test case, `DroidSerif-Bold-webfont.ttf` is the unaltered TTF file, and `DroidSerif-Bold-webfont-modified.ttf` has all glyphs except M and T removed (removing either of those caused it to render a blank page — the expected output).

System information:

* Linux Mint 13 Maya (based on Ubuntu 12.04 LTS)
* Compiled GLFW3 from source (git; "latest" branch)

**Comment by mbrubeck** [comment]
Works correctly in the latest master.
