### ISSUE TITLE
300ms lag between the compositor sending a RenderMsg and the render task painting

### ISSUE THREAD

**Issue by jdm** [servo/servo#3583]
This can be easily seen in action when running `tests/html/test-inputs.html`. There's a noticeable lag between clicking one of the checkboxes/radio buttons and seeing the corresponding update. I've timed each stage of the process, and the period between GLFW reporting the click event and the resulting reflow completing is only 5ms; all subsequent perceived lag occurs because no paint occurs for another 300ms. Running with RUST_LOG=gfx::render_task, the render task doesn't report any missing paint permission, so I'm not sure where all that time is going.

cc @zwarich @mrobinson

**Comment by narfg** [comment]
Has this been fixed? I don't notice a significant lag anymore.

**Comment by jdm** [comment]
Yes, I recall noticing that this no longer happened a few weeks after filing it.
