### ISSUE TITLE
Fetch margins, padding, and borders for layout inspector

### ISSUE THREAD

**Issue by jdm** [servo/servo#3598]
See the "getLayout" message in `components/devtools/actors/inspector.rs`. Currently we only fetch the width and height; instead we want to adjust the code in `handle_get_layout` to query the layout properties using LayoutRPC, rather than just calling `getBoundingClientRect`.

**Comment by jdm** [comment]
getComputedStyle exists now!

**Comment by benschulz** [comment]
Determining `autoMargins` is gonna be tricky. I hope to take a look at that over the next couple of days.

Perhaps someone can look at my [progress](https://github.com/benschulz/servo/commit/9328300f3ee2a786b813cf2d50a91b37d2408da0) in the meantime. I have one question in particular: Should I stick with rustc_serialize or is it alright to use serde_json?
From a readability point of view I'm very much in favor of serde. It allows for JSON property names such as `"margin-top"` without having to manually construct `HashMap`s. However, I'll gladly rewrite that part if other factors outweigh the readibility argument.

**Comment by jdm** [comment]
If serde makes it easier, go right ahead. You can also file an issue to convert the existing code that uses rustc_serialize, or do the work yourself.

**Comment by jdm** [comment]
Current progress looks great to me!

**Comment by benschulz** [comment]
I've added the missing implementation for `autoMargins`. However, I can't say that I like it. It is based on a new `ReflowQueryType` just for the `autoMargins`; essentially devtools UI specific code in the layout and script components.

Firefox's devtools base `autoMargins` on `DOMUtils.getCSSStyleRules`, on which most of the style inspector is based anyways. I'm wondering if it would not be better to defer implementation of `autoMargins` until similar functionality is available in servo.

For reference:
 - [my commit](https://github.com/benschulz/servo/commit/46269e10c2fb2413f8fc9f4f0d9a0c084e16825b)
 - [firefox's `autoMargins` implementation](http://mxr.mozilla.org/mozilla-central/source/toolkit/devtools/server/actors/styles.js#841)

**Comment by jdm** [comment]
I don't think it's worth deferring. These things happen, and we can refactor it if there's a need for similar functionality at some other point in the future.

**Comment by jdm** [comment]
That being said, if we're only checking the computed style values, we might be able to directly access them from script/ using http://mxr.mozilla.org/servo/source/components/script/dom/node.rs#214 (from http://mxr.mozilla.org/servo/source/components/script/dom/node.rs#120).

**Comment by KiChjang** [comment]
@benschulz what's the status of this?

**Comment by benschulz** [comment]
Sorry, I didn't properly link this issue with PR #7267.
