### ISSUE TITLE
Load events triggered during page load cause failures

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#3628]
I came across this while testing form submission (`form.submit()`, not in a state to PR yet), but it's an issue for links as well.

The following will cause a task failure:

```
<html>
<head></head>
<body>
<body>
<a href="http://www.google.com" id="foo">google</a>
<script>
var event = document.createEvent("MouseEvents");
event.initMouseEvent("click", true, true, window,
    0, 0, 0, 0, 0,
    false, false, false, false,
    0, null);
document.getElementById("foo").dispatchEvent(event)
</script>
</body>
</html>
```

The failure is at an `unwrap()` in [`constellation::handle_load_url_msg`](https://github.com/servo/servo/blob/master/components/compositing/constellation.rs#L611).

If I add a timeout of five seconds to the `dispatchEvent()` and it worked fine (in both the form submission and link cases)

My guess is that the `NavigationContext`'s `current` frame tree isn't initialized until the page finishes loading, but scripts can run before that, and if a script triggers navigation, stuff breaks.

**Comment by dralley** [comment]
I cannot reproduce this failure, although since it sounds timing-dependent, it's hard to say whether it's actually fixed.
