### ISSUE TITLE
Intermittent failure in link_style_dynamic_addition reftest

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#3636]
`tests/ref/link_style_dynamic_addition.html` (added by #3432) fails frequently on Linux.  The failure seems to be a timing-sensitive race, but I've been able to reproduce the failure both in and out of the reftest harness, especially with #3563 applied.  The page is rendered white, presumably because it is rendered before the stylesheet is loaded.  We need to make sure we re-layout and repaint after all scripts have run (and before writing any PNG output).

**Comment by nox** [comment]
@mbrubeck Was that fixed?

**Comment by nox** [comment]
This was ported to a WPT test and isn't disabled anymore.
