### ISSUE TITLE
Implement text-transform CSS property

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#3660]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

The hard part here is the locale-aware case conversions. [Here](http://dxr.mozilla.org/mozilla-central/source/layout/generic/nsTextRunTransformations.cpp#227)'s the relevant Gecko code

**Comment by frewsxcv** [comment]
a lot of this was implemented in 877f02f1d1c391f2b57002d88fa8e0a0e4d4d46d

**Comment by nox** [comment]
This was done.
