### ISSUE TITLE
Use signed distance fields for instant pinch-zoom on text

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#3717]
Essentially, split rendering & compositing into a raster part and a text / "likely vector" part.  Zoom on raster tiles works as usual, zoom on text tiles uses signed distance fields.

cc @glennw

**Comment by cmr** [comment]
Would this only use SDFs to render text while the new glyphs are being rasterized (which can take a noticable amount of time mobile)? Maybe also past a certain zoom factor.

It seems that not all fonts would be suitable for use with SDFs, especially at small sizes. I think I remember seeing something in IRC float by, perhaps @pcwalton way playing with it?

**Comment by mrobinson** [comment]
I think we can close bug in favor of solutions like Pathfnder.
