### ISSUE TITLE
inline-block with non-default overflow next to an inline element laid out incorrectly

### ISSUE THREAD

**Issue by jdm** [servo/servo#3725]
```a<span style="display: inline-block; overflow: hidden">b</span>```
The b should be positioned adjacent to the a, but instead it's mostly hidden behind it. The overflow is what makes the difference here.

**Comment by bjwbell** [comment]
@jdm This appears to be fixed on latest master.

**Comment by jdm** [comment]
Perhaps a reftest is in order.

**Comment by bjwbell** [comment]
@jdm Added

**Comment by bjwbell** [comment]
@jdm can you close?
