### ISSUE TITLE
Initialize trusted-ness of DOM events properly

### ISSUE THREAD

**Issue by jdm** [servo/servo#3740]
* DispatchEvent needs to set trusted to false (https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent)
* Internal code that creates events needs to ensure that they're trusted by default (https://dom.spec.whatwg.org/#concept-event-fire) (ie. load event, click events, etc.)
* EventTarget needs a helper method that can dispatch an event without modifying its trusted-ness which can be called by dispatch_event_with_target
* Events created by script should be untrusted by default (https://dom.spec.whatwg.org/#dom-event-istrusted and https://dom.spec.whatwg.org/#concept-event-initialize)
* Any initialization by internal code needs to make sure that it doesn't call methods that force trustedness to false

**Comment by gilles-leblanc** [comment]
I'd like to have a look at this. 
I might have some questions along the way though.

**Comment by gilles-leblanc** [comment]
- [ ] Set DispatchEvent trusted to false
- [ ] Check internal code that creates events to make sure they are trusted by default
- [ ] Create helper method for EventTarget
- [ ] Events created by script should be untrusted by default
- [ ] Check initialization by internal code to make sure doesn't call methods that forces trustedness to false

**Comment by gilles-leblanc** [comment]
> Events created by script should be untrusted by default (https://dom.spec.whatwg.org/#dom-event-istrusted and https://dom.spec.whatwg.org/#concept-event-initialize)

Right now Event::new_inherited sets trusted to false. Event::Constructor calls Event::new and Event::new calls InitEvent. InitEvent sets trusted to false as per the spec (https://dom.spec.whatwg.org/#concept-event-initialize).

So it seems that trusted will always be false so this point would already be done and I would only to set it for this case:

>Internal code that creates events needs to ensure that they're trusted by default (https://dom.spec.whatwg.org/#concept-event-fire) (ie. load event, click events, etc.)

As for:

> EventTarget needs a helper method that can dispatch an event without modifying its trusted-ness which can be called by dispatch_event_with_target

I do not understand the need for this helper method. Right now both of EventTarget's dispatch methods call EventDispatcher::dispatch_event which doesn't seem to modify the trustedness.

**Comment by jdm** [comment]
Step 2 of https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent is what caused me to suggest a helper method.

**Comment by jdm** [comment]
The reason it's important is that the web content code could take an event with isTrusted=true and re-dispatch it using dispatchEvent. In that case the event needs to no longer be trusted, since the user agent is no longer the one dispatching it.

**Comment by jdm** [comment]
Bear in mind that I filed this issue before we had any trusted/untrusted distinction for events. We have since gained methods like set_trusted, but we need to make sure we adhere to the spec. We don't necessarily need to follow every step I laid out in the original comment.

**Comment by gilles-leblanc** [comment]
Thanks for the clarifications.
