### ISSUE TITLE
HTMLIFrameElement should use token list instead of manual string splitting for sandbox attribute

### ISSUE THREAD

**Issue by jdm** [servo/servo#3758]
The manual setters and getters should be replaced with the appropriate macros, and after_set_attr can use attr.value().tokens() instead of dealing with the string manually. There's no make_tokenlist_setter macro yet in http://mxr.mozilla.org/servo/source/components/script/dom/macros.rs, so that should be added too.

**Comment by jdm** [comment]
The ultimate goal is to follow the spec, so we do want DOMSettableTokenList eventually (see #1717). If you feel like tackling that, that would be great and I'm happy to provide guidance. All I had in mind for this issue in particular was making use of tokens(); I think using a DOMTokenList internally and serializing that to a string would be acceptable, but it probably isn't worth creating a make_tokenlist_getter macro in that case.

**Comment by jimrhoskins** [comment]
Ok, cool. I think I'll start with just doing an internal DOMTokenList and serialization, I think I can handle that. After that, I'll try to figure out if DOMSettableTokenList is something I can take on.
