### ISSUE TITLE
Reduce name duplication in event_handler! invocations

### ISSUE THREAD

**Issue by saneyuki** [servo/servo#3777]
In #3755, we add the macro to define a event handler's getter & setter. This macro have some rests which can cut needless parameters with using `concat_idents!`.

But at this moment, by https://github.com/rust-lang/rust/issues/12249, we cannot `concat_idents!` to resolve the above.

**Comment by jdm** [comment]
I don't believe we have any ideas for how to implement this. We can reopen this if there's any concrete suggestions.
