### ISSUE TITLE
Deleting textures can make us miss frames

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#3779]
Sadly `delete_textures` for unused tiles can take like 4-20 (!!) ms even on my fast MBP. There are a couple of ways we could mitigate the pain:
1. Make sure buffer requests get sent to the painting task _before_ we drop the textures, so that at least the painting task can use that time to get painting done and maybe it'll get the buffers in in time before we checkerboard; or
2. Delete textures slowly, a few per frame, instead of all at once.

Yuck.

**Comment by mrobinson** [comment]
I'm going to close this since it refers to a bug in the long-removed non-WebRender compositor.
