### ISSUE TITLE
Slow layout performance in hello_rust

### ISSUE THREAD

**Issue by steveklabnik** [servo/servo#3786]
Sorry for the terrible title, I'm not sure what a good one is here.

Basically, https://steveklabnik.github.io/hello_rust/ loaded in firefox works pretty awesome. the same page loaded in servo (after applying https://github.com/servo/servo/pull/3585 ) is very, very, very slow. With only a few slides, it's fast, but it gets slower the more you add. It feels O(n^2) but i haven't done any formal benchmarking. 

It also happens when you build with `--release`.

**Comment by nox** [comment]
That doesn't seem to be true anymore.
