### ISSUE TITLE
Support Mesa off-screen software rendering with minimal platform deps

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#3789]
Mesa supports [a mode](http://www.mesa3d.org/osmesa.html) where OpenGL renders to an off-screen buffer in main memory. This is pure computation in userspace; there's no window system or OS dependencies.  There are several ways we could use this in Servo:

* Headless ref tests without `Xfvb`
* Headless embedders that want to save raster output.  (For the vector part of this see #3788.)
* Extreme portability.  In this mode you can use Servo on any platform that has a framebuffer, e.g. EFI, Linux fbdev, game console homebrew
* High-security mode where all of Servo is heavily sandboxed, except a minimal UI task that communicates with the engine over a well-defined IPC protocol and receives bitmaps to display.  At this point it really *is* a VM and an OS that you can VNC into :D

We can enable this in desktop Servo if we switch to glutin (#3579). But maybe we should only think of it as a feature for other embedders.

**Comment by glennw** [comment]
This happened.
