### ISSUE TITLE
Update "ACID2 Status" in Wiki

### ISSUE THREAD

**Issue by 0b10011** [servo/servo#3818]
https://github.com/servo/servo/wiki/ACID2-Status

According to [this Mozilla blog post](https://blog.mozilla.org/research/2014/04/17/another-big-milestone-for-servo-acid2/), Servo passes Acid2. However, [the list of open issues](https://github.com/servo/servo/issues?q=is%3Aissue+is%3Aopen+acid2) tells a different story.

Could someone update that page (even if "updating" means removing it) with up-to-date information? And perhaps add an "Acid3 Status" page? :)

**Comment by mrobinson** [comment]
I've removed this page, because it's pretty out of date now!
