### ISSUE TITLE
Acid2 start page broken

### ISSUE THREAD

**Issue by nwin** [servo/servo#3825]
As you can see from the attached picture some parts of the smiley are leaking through before clicking on the link.

```
$ uname -a
Linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

![acid2 start page bug](https://cloud.githubusercontent.com/assets/949560/4804844/94facd22-5e73-11e4-9749-f6f82e0b4458.png)

**Comment by frewsxcv** [comment]
Just tried this page with the latest Servo. No apparent changes:

![screen shot 2015-04-26 at 3 22 44 pm](https://cloud.githubusercontent.com/assets/416575/7338878/2448ed28-ec28-11e4-9bb4-0823fa6b555d.png)

**Comment by frewsxcv** [comment]
For the sake of linking related issues: https://github.com/servo/servo/issues/1366

**Comment by nwin** [comment]
Seems to have improved slightly.

![screenshot](https://cloud.githubusercontent.com/assets/949560/17052715/f0837404-4ffe-11e6-99d0-2c9cb2bb47c8.png)

**Comment by sviter** [comment]
Start page looks good now
