### ISSUE TITLE
Off-main-thread, speculative HTML parsing

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#3847]
By running the HTML parser in a separate task from script, we could allow tokenization and speculative tree building to continue while content scripts are fetched and executed.

References on HTML parser threading in Gecko and WebKit:
- https://hsivonen.fi/speculative-html5-parsing/
- https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/HTML_parser_threading
- https://bugs.webkit.org/show_bug.cgi?id=106127

**Comment by psdh** [comment]
I am trying to implement this!

**Comment by psdh** [comment]
^^ Should I implement TreeSink on top of [existing implementation], implementing the missing functions and adding the sending a message part.
Can you also, elaborate on the sending a message part

[existing implementation]: http://mxr.mozilla.org/servo/source/components/script/parse/html.rs#58

**Comment by jdm** [comment]
You can learn more about message passing in Rust at http://doc.rust-lang.org/book/concurrency.html

**Comment by psdh** [comment]
Okay, After irc discussions with kmc, and jdm, I have understood that I need to
Add one more implementation of TreeSink that would implement each of these methods by sending a enum to a channel(say message), this enum would have information about
     i) target
     ii) arguments
And then I queue these dom manipulations as enum vairants( in a vec?) and flush them from time to time
When do we make the actual changes(to the dom) though?
Is it when we flush them, we can check which enum variant has been stored and make changes according to that?

**Comment by jdm** [comment]
As you say, the DOM changes would occur when flushing them in the main script task. There would need to be a synchronization point - when the script task is going to execute a newly-parsed script element, it needs to operate on the up-to-date DOM tree. Does that make sense?

**Comment by kmcallister** [comment]
> I queue these dom manipulations as enum vairants(in a vec?)

And/or in the message channel itself.

You'll need a cross-thread way for tree ops to refer to nodes that haven't been constructed yet, but will be constructed by a previous tree op.  Gecko uses `nsIContent**` for this: a pointer to a slot which will eventually hold a pointer to the node, when the main thread gets around to constructing it.

This approach seems pretty unsafe, and anyway will be impossible without `unsafe` code in Rust. So for Servo's parser, I'd like to try using simple integer IDs, and then figure out what the performance cost is.

> When do we make the actual changes(to the dom) though?

I think this depends on why you're doing the parse.

If you're speculatively parsing characters after `</script>` while the main thread is running the script, then you can't commit any DOM manipulations until the script finishes and you check whether it did anything to invalidate your speculative assumptions. The Gecko link above has more to say about this.

You can speculatively fetch any URLs you've discovered in the parse, even if the DOM manipulations are discarded. I think there's no need to coordinate that with the main thread at all.

We can also do the initial page load parse off-main-thread, which allows parallelism between the parser and the actual DOM manipulations (a bottleneck today for whatever reason). In that case I think you'd execute the tree ops as soon as possible, until you see a `</script>`.

Naturally, `<script defer>` and `<script async>` don't block parsing in the same way. I'm not sure about the details; you'll have to consult the spec. It's not necessary to implement these right away, but we should keep them in mind.

**Comment by LifeIsStrange** [comment]
Just for say that some blockers addons like uBlock Origin or noscript will need to disable this feature.

**Comment by mbrubeck** [comment]
> Just for say that some blockers addons like uBlock Origin or noscript will need to disable this feature.

Can you explain why?  This feature does not cause any additional fetches or script executions.  uBlock and NoScript work fine in Firefox and other browsers that do off-thread parsing.

**Comment by saneyuki** [comment]
@LifeIsStrange

uBlock blocks the network traffic which is in a blacklist, and NoScript just disable to execution script without in the whitelist. This would not prevent them

**Comment by LifeIsStrange** [comment]
Sorry,  I expressed myself badly,I Just speaked about prefetching.

UBlock Origin do this: " Disable "Prefetch resources to load pages more quickly"

    This will ensure no TCP connection is opened at all for blocked requests: It's for your own protection privacy-wise.[1]
    For pages with lots for blocked requests, this will actually remove overhead from page load (if you did not have the setting already disabled).
    When uBlock blocks a network request, the expectation is that it blocks completely the connection, hence the new permission is necessary for uBlock to do truthfully what it says it does."

**Comment by Syrcon** [comment]
I'll try to implement this as my master's thesis.

As @jdm said, there is some timeline needed. 
So the main period of work is February - April 2016.

**Comment by frewsxcv** [comment]
Did you make any progress on this @Syrcon?

**Comment by Syrcon** [comment]
Well, @jdm helped with making a parser work asynchronously, and I'm working right now on executing parser in its own thread. So there will be some commits by the weekend.

You'd like to work on this?

**Comment by frewsxcv** [comment]
No, no rush at all! If it was the cause that nothing had been done for this, I was going to remove the `C-assigned` label so someone else could work on it. Keep up the great work :)

**Comment by jdm** [comment]
My experimental branch that tried to make the parser asynchronous is https://github.com/jdm/servo/tree/asyncparse.

**Comment by mrmiywj** [comment]
@jdm, hi jdm, I'm going to use this idea as my GSoC 2017 project idea. Is there anyone working on this? I will try to explore the working flows about this idea recently. Is there any related suggested issue to work on?

**Comment by jdm** [comment]
I don't think there are any other issues related to this.

**Comment by LifeIsStrange** [comment]
@mrmiywj actually there is this
https://github.com/servo/html5ever/issues/25

**Comment by dudelson** [comment]
@jdm I'd also like to take a cursory look into this project, if you don't mind multiple people investigating it at once.

**Comment by jdm** [comment]
It's intended as a GSoC project, so it's probably best suited for people intending to apply for that.

**Comment by dudelson** [comment]
Sorry for not being clear. I am also a prospective GSoC student.

**Comment by nox** [comment]
Cc @cynicaldevil
