### ISSUE TITLE
Per-tile display list construction

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#3852]
roc has suggested that we do display list construction on a per-tile basis to improve its performance when small modifications to the page are made. The basic idea is as follows:
- In layout, when a flow's (or fragment's) overflow rect (in _page-relative_ coordinates†) and/or contents change, we make a note of the tiles that it potentially invalidated by taking the union of the old and new regions and expanding to tile boundaries. (Note that this is a quick conservative approximation of the invalid region and may not _actually_ invalidate those tiles; DLBI in the painting thread may later optimize out the display list down to nothing, but this will allow us to skip display list building for the most common cases.)
- We only build display lists in layout for the region encompassing the tiles that may have changed. We still build only one display list for the entire region; this is important because we don't want to traverse the tree multiple times or build display lists over and over for display items that span multiple tiles.
- On the painting task side, rather than having one display list per `RenderLayer`, we have a map from tile index to the display list that's appropriate for that tile. (Multiple tiles can, and usually will, correspond to the same display list, so they should be atomically reference counted.) If there are too many display lists, we can throw out the least-recently-used ones.
- When new buffer requests come in from the compositor, we just consult the tile index to tell us which display list to use for each tile.

roc would like us to push on this soon in order to gauge its feasibility for Gecko. I imagine that, if it works, it will be a _large_ performance win on display-list-construction-bound workloads like the maze solver.

cc @mrobinson

† Note that the overflow rect may change in page-relative coordinates even if it didn't change in parent-flow-relative coordinates, if the flow moves around!

**Comment by glennw** [comment]
No longer relevant.
