### ISSUE TITLE
Python crashes when running mach test

### ISSUE THREAD

**Issue by TileHalo** [servo/servo#3854]
Hi!
When i run <code>$ ./mach run tests/html/about-mozilla.html</code> It prints following

<code>  
ERROR:script::parse::html: Parse error: Unexpected token
Error running mach:

    ['run', 'tests/html/about-mozilla.html']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'target/servo', 'tests/html/about-mozilla.html']' returned non-zero exit status -11

  File "/home/leo/code/job/mozilla/servo/python/servo/post_build_commands.py", line 26, in run
    env=self.build_env())
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

</code>
(edit) I pulled and now it says this. It was also the original message, but it printed the odd one once

**Comment by agilob** [comment]
It works here.

**Comment by jdm** [comment]
Great!
