### ISSUE TITLE
Root::deref is broken

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#3868]
We have
```rust
impl<'b, 'a: 'b, T: Reflectable> Deref<JSRef<'b, T>> for Root<'a, 'b, T> {
    fn deref<'c>(&'c self) -> &'c JSRef<'b, T> {
```
with the intention that `'c: 'b`, but I haven't found a way to encode that in the type system. Because the pointer is initialized from a raw pointer (in a `JS<T>`) by `&*ptr`, `'b` effectively becomes arbitrarily long. This blows a huge hole in the safety of our DOM code.

**Comment by nox** [comment]
`JSRef<T>` is dead, I believe this can be closed.
