### ISSUE TITLE
Vectors of stack roots are bad

### ISSUE THREAD

**Issue by jdm** [servo/servo#3874]
eventdispatcher.rs uses `Vec<Root<T>>`, which is bad because the values inside of Vec are not actually on the stack. We should forbid collections of types which are must_root, and import the RootedVec code from https://github.com/jdm/servo/commit/65c1cca07522bcc81fe49a3548896e66eb60cb2f.

cc @cgaebel, @kmcallister

**Comment by nox** [comment]
eventdispatcher.rs uses RootedVec.
