### ISSUE TITLE
Elements that become display: none don't disappear

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#3885]
This breaks my slideshow at the moment :/

```html
<!DOCTYPE html>
<head>
<style>
.hidden {
    display: none;
}
</style>
<script>
window.addEventListener('load', function () {
    window.setTimeout(function () {
        var divs = document.getElementsByTagName('div');
        divs[0].className = 'hidden';
        divs[1].className = '';
    }, 1000);
});
</script>
</head>
<body>
<div>foo</div>
<div class="hidden">bar</div>
</body>
```

Expected behavior: after one second, "foo" disappears, "bar" appears.  This is what happens in Chrome and Firefox.

In Servo, "bar" appears but "foo" does not disappear.  On master the repaint only happens when I move the mouse.  On the [text input branch](https://github.com/kmcallister/servo/commits/input) it happens immediately (due to "Flush layout after executing timers", I suspect), but either way the result is the same.

I think this is a recent regression.  @pcwalton thinks it has to do with incremental layout.

When we fix this we should make a reftest too.

**Comment by kmcallister** [comment]
Still broken as of ff8cbff81016c157373c1675f3eee69dd70ae544

**Comment by glennw** [comment]
Likely to be fixed by https://github.com/servo/servo/pull/5064
