### ISSUE TITLE
Slow-motion resizing on Linux/GLFW

### ISSUE THREAD

**Issue by bill-myers** [servo/servo#3888]
On Linux/GLFW, resizing the window usually results in "slow-motion resizing", where the browser repaints the window for every single pixel between the old and new sizes.

Of course this is disastrous especially with vsync, since for instance resizing a 640x480 window to 1920x1080 will take 21 seconds at 60 hz refresh rate.

The problem might have been introduced by 10f7b49cf7dc8f77cf70750927a2c85650312033 by @pcwalton, since the resize events are delivered via the "nested loop handler".

EDIT: no, the problem is there even with e483a189a3c24d0fe475cf2a8dedb11821f7ee21

Of course, the way this should work is that rendering should be done with whatever size the window has at the start of the frame, rather than rendering for each resize event.

I'm not sure whether HTML/the web requires to send resize events for each pixel difference in size; if not, not doing so and instead sending an event for each frame will of course be faster.

I'm using Ubuntu 14.10 with Xorg and the default Mesa/Intel driver on an Haswell Intel GPU.

**Comment by mbrubeck** [comment]
Servo no longer uses GLFW, though we're still working on improving resize performance on various platforms.  Closing this old issue; new issues can be filed for current resize bugs.
