### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by VAS** [servo/servo#3893]
On the comments following the talk by Lars Bergstrom [here](https://air.mozilla.org/an-introduction-to-servo/), it was mentioned that proposals for a servo logo were welcome.

Below is an inception (in two variants). The logotype is in Mozilla's open typeface Fira (extra bold italic, slightly modified for harmonious cohesion between letters). Please keep in mind it is a very rough prototype, without color. Rather than spend hours on it, early feedback is appreciated to steer it to completion collectively. If received positively, it will be worked on in detail. Contributions/suggestions are welcome.

![Logo proposal 1](http://i.imgur.com/99vhJfq.png)

**Comment by kud1ing** [comment]
@raphaelbastide I like the round version. It looks like something is spinning fast.

**Comment by kud1ing** [comment]
A sketch of something speed-blurry http://imgur.com/Ogoc1Ib

**Comment by Nercury** [comment]
When looking at all the ideas, I just had this funny thought to combine spiny things, rotating spikes, hedgehog and the modified Fira font:

![Hedgehog servo logo](https://raw.githubusercontent.com/Nercury/Nercury.github.io/master/artwork/servo/logo_v1.png)

**Comment by FireDart** [comment]
I really like @raphaelbastide circle logo. Throwing some more ideas out there, maybe something that incorporates the theme of "parallel" into the logo? Since Servo describes its self as a fast **parallel** browser?

Also were does the origin of the hedge hog come from?

**Comment by Manishearth** [comment]
It seems like it's just a play on the fox.

Also, it just occurred to me, Whimsycorn makes a fun logo:

![](https://pbs.twimg.com/media/B92WR2JCYAAs3qs.png:large)

(If you've never seen that before, use Firefox's customization feature to remove everything from the panel menu and see what happens)

**Comment by zslayton** [comment]
I love @VAS's Tom-Servo-from-above! It's great that it's only an MST3K reference if you know what you're looking for.

**Comment by kevincannon** [comment]
Hey all, some really nice ideas in here. I tried to distill them down to what I think is key:

* Represents the parallel nature of the browser - see @FireDart's comment.
* Has some connection to Rust. (I'm not sure of the IP of Rust's logo though)
* Feels like a project logo, rather than finished product logo/icon.

Based on that, I built on ideas above by @raphaelbastide - but tried to do two things. Change the lines to represent the parallel nature of the project, and also position those lines to be in a subtle S shape.

Here's a rough sketch:

![servo_ideas_01](https://cloud.githubusercontent.com/assets/5065238/6524767/ab208796-c3fd-11e4-9fc5-becdf495e542.png)

**Comment by raphaelbastide** [comment]
Hey, as there is an interesting activity on this subject, I am wondering where those graphic researches lead. Are we doing all that for a precise purpose? Does Servo needs a logo, if yes, who will decide and how? Logo design needs real constraints to be efficient and smart. From now we just draw nice images and it can continue like that ∞ . So what next?

**Comment by larsbergstrom** [comment]
@raphaelbastide We do need a new logo and the contributions in this thread have been awesome (I particularly like the one from @VAS !).

The logo decision will be made by @metajack and myself, in consultation with the team. We do not currently have a timeframe for making this decision, but we'll chat about it at a meeting next week and try to comment soon.

**Comment by raphaelbastide** [comment]
Bump
![export4](https://cloud.githubusercontent.com/assets/193122/7441455/d4eeb742-f0e8-11e4-8300-8927f2ce4447.png)

**Comment by notriddle** [comment]
Messing with the @VAS idea, with the Firefox logo layout and colors.

![servo](https://cloud.githubusercontent.com/assets/1593513/9419997/c245ccd2-4815-11e5-9b58-53b4bc86bc04.png)

**Comment by geleto** [comment]
![servo1](https://cloud.githubusercontent.com/assets/3138391/9661531/c75850b6-5263-11e5-8cc0-bf1827b7f6f1.png)
![servo2](https://cloud.githubusercontent.com/assets/3138391/9661534/c9d5a05a-5263-11e5-9086-11d01ab38465.png)

**Comment by webmaven** [comment]
@metajack do you still have someone working on a logo, or is it possible to throw my hat into the ring?

**Comment by elioqoshi** [comment]
I'd be happy to work on a logo as well. I have done some logos for Mozilla in the past:
https://elioqoshi.me/en/mozilla-logos/

**Comment by metajack** [comment]
@webmaven We've had a few false starts trying to hire someone to finish this. Our plan is still to do so.

I'm happy for people to continue submitting ideas. We're using them as input into the process, but if someone lands on something great perhaps we'll be finished early.

There are plenty of good ideas in this thread, but of the things posted here so far the work from @VAS has been my personal favorite.

**Comment by notriddle** [comment]
Thinking about @mbrubeck's idea, came up with a "two globes" idea. Looks about like someone's lower face with way-too-big noserings.

![servo_proposal_2](https://cloud.githubusercontent.com/assets/1593513/16751772/c6f92654-4790-11e6-8814-cac0cafdeb39.png)

**Comment by notriddle** [comment]
Even more simplified (and I really like symmetrical logos like circles and squares better anyway).

![servo_proposal_3](https://cloud.githubusercontent.com/assets/1593513/16773188/c48afcaa-480b-11e6-99d1-1a393077fa71.png)

[SVG version](https://github.com/servo/servo/files/359718/servo_proposal_3.svg.zip)

**Comment by elioqoshi** [comment]
@notriddle Love the last version! This is what I came up with, with your icon and a lightly muted red (Rust, but not that ugly)
![1](https://cloud.githubusercontent.com/assets/5436686/16946193/9e5ee3aa-4da8-11e6-9f67-3672c03305d1.png)

**Comment by Coder206** [comment]
I think these last few proposals remind of Apple's app store logo. See here: https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTNJYh4FWVbTPJ7nFMDaHv_JnZrb0yVkbdj9fjUx1aIZacUgYa0

**Comment by fbender** [comment]
That could be rectified by making the straight lines less thick

**Comment by Coder206** [comment]
@fbender I like your suggestion!

**Comment by bkerensa** [comment]
If someone does not know what a centrifugal governor is the more modern iterations might look like male anatomy to most folks.

Just a thought

**Comment by nox** [comment]
This doesn't make me think about a browser engine, this makes me think of [Git's logo](https://git-scm.com/images/logo@2x.png).

**Comment by mmatyas** [comment]
How about putting mst3k on that nice red color:

![redservologo1](https://cloud.githubusercontent.com/assets/4354863/19760528/6ed8cb04-9c32-11e6-876d-ecae99b81ce9.png)


Or with black border:

![redservologo2](https://cloud.githubusercontent.com/assets/4354863/19760534/7194ff98-9c32-11e6-85d5-873b5ef3a1da.png)

**Comment by webmaven** [comment]
@metajack et al,

Will it be important for the servo logo to work with the new Mozilla branding being developed?:

https://blog.mozilla.org/opendesign/

**Comment by larsbergstrom** [comment]
@webmaven No. Servo is sponsored in part by Mozilla, but is governed as an independent project and does not need to have any shared branding elements with whatever Mozilla decides to go with.

**Comment by elioqoshi** [comment]
I like where this is going! Will make a proposal sometime next week

**Comment by sr229** [comment]
I got a suggestion, why not we base from the firefox logo, combine the above proposal then have a Shibe "hug" the logo

**Comment by metajack** [comment]
Firefox designers already did this as a spoof icon for Firefox. http://i.imgur.com/7Ih60Gu.png

We'd like to keep our branding (such as it is) separate from Firefox.

**Comment by paulrouget** [comment]
FYI, we use this logo for [ServoShell](github.com/paulrouget/servoshell):

![128x128-x2](https://user-images.githubusercontent.com/373579/31113722-db08785c-a81a-11e7-866e-5d29f225e658.png)

**Comment by dsamarin** [comment]
Not involved with this project but I thought there were some great ideas here. Love the mst3k reference with the red color from @mmatyas and the lowercase font styling used by @raphaelbastide where the shape of the 'v' cuts into the end of the 'r'. Also loved the idea to add a visual effect of motion as noted by @kud1ing.

![iconartboard 1](https://user-images.githubusercontent.com/110829/37017357-46733e4c-20c5-11e8-839b-5b8f4610afb3.png)

**Comment by jdm** [comment]
Hi everyone! Building on some of the logo designs that were proposed earlier in this issue (in particular, the motor visual idea), we asked a designer to iterate on a few possibilities. The core team really liked one design in particular that came with a couple different colour palette options:

Palette 1:
![Servo - Option 1](https://user-images.githubusercontent.com/27658/72731063-cd0e1800-3b8a-11ea-88d3-9bf0548dbc5f.jpg)

Palette 2:
![Servo - Option 2](https://user-images.githubusercontent.com/27658/72731074-d0a19f00-3b8a-11ea-86e0-18200b13c872.jpg)

Do you prefer one palette over the other? Is there any cultural reason (either global or internet) to avoid this design? We would hate to settle on a logo that has an unintended meaning to some groups.

**Comment by pshaughn** [comment]
To my eye, the blue/green looks more like a unified letter O and the red/orange/purple looks like a disconnected symbol that's not necessarily a letter. If that's generally true and not just me, then the blue/green would do a better job of conveying the word "servo".

**Comment by CYBAI** [comment]
I love both design though, the `#5101bc` color in palette 2 for dark mode might be too close to the black background which might be difficult to see 👀?

**Comment by SimonSapin** [comment]
@pshaughn makes a good point, but I also like that the second palette is similar (or is it the same?) as various Firefox logos:

https://mozilla.design/firefox/logos-usage/

<img width=50% src=https://user-images.githubusercontent.com/291359/72737474-f1c0ba80-3b9f-11ea-9728-9683b513abcd.png><img width=50% src=https://user-images.githubusercontent.com/291359/72737485-f4231480-3b9f-11ea-867e-8397b6a9da2b.png>

**Comment by Manishearth** [comment]
I like the first one aesthetically but as Simon said the second one does feel more "Firefoxy".

**Comment by elioqoshi** [comment]
I'd discourage from replacing letters with a symbol because of readability issues:
https://www.jessicajonesdesign.com/logos-that-replace-a-letter-with-a-picture/
https://jimanov.com/en/articles/the-principle-of-replacing-letter-in-a-logo/

It's not impossible to make it work, though the 'o' here has a very different style from the rather standard letters in 'serv'.

Further, it is very not in the style of Mozilla of doing this replacement strategy of letters so it might be worth refraining from it, unless it should be independent from Mozilla (which makes the 2nd Firefox-y palette a bit paradoxal). This is just my 2 cents as someone who was involved at the Mozilla brand team in the past though.

**Comment by sr229** [comment]
I do like having the old logo's elements still incorporated in the new logos.

It kinda shows as well how wacky and creative Mozilla can be with logos. We don't need to be overly professional with it as well, since Google's LuCI project is literally just a cute hamster.

**Comment by Manishearth** [comment]
Oh, also, the blue-green pallette matches _Edge_ :)

**Comment by larsbergstrom** [comment]
FWIW, I'm not personally concerned about adhering to either a Mozilla or non-Mozilla style or color palettes. We should pick what works well for the brand.

I'm also quite fine with keeping around the Doge as the _mascot_, which I love - @zmike made it while he and I were riffing on ideas one evening, and the quest to determine "who has the rights for that Doge and can we use it?" was one of my more epic legal journeys. Unfortunately, as we've been looking to get more partners, investments, and contributors, the current logo tends to make it difficult for people to take the project seriously.

**Comment by metajack** [comment]
I like the design, and I prefer the first palette. The second one is also nice, but I'm imagining trying to find the icon alone amongst the multi-color-pieces logos of Google things and Slack and I'll probably have to hunt a bit even if the colors aren't the same primary ones.

@elioqoshi 
> Further, it is very not in the style of Mozilla of doing this replacement strategy of letters
Mozilla designed a font that replaced the interior `ill` with `://`. That still seems to be the current brand identity.

**Comment by pshaughn** [comment]
Would outlining the wheel in the text color make it a better O, or would adding strokes to it make it overdetailed?

**Comment by pcwalton** [comment]
All of the ideas look great to me. :)

**Comment by sr229** [comment]
> FWIW, I'm not personally concerned about adhering to either a Mozilla or non-Mozilla style or color palettes. We should pick what works well for the brand.
> 
> I'm also quite fine with keeping around the Doge as the _mascot_, which I love - @zmike made it while he and I were riffing on ideas one evening, and the quest to determine "who has the rights for that Doge and can we use it?" was one of my more epic legal journeys. Unfortunately, as we've been looking to get more partners, investments, and contributors, the current logo tends to make it difficult for people to take the project seriously.

Love your input on this. If Doge would remain our mascot, we should incorporate it to our logo instead of outright replacing it.

After all, while we're aiming for a more professional looking logo, we should keep in mind its not every time we have to make it look overly professional.

I'd prefer a nod to the old logo with the new one if possible.

**Comment by nox** [comment]
An idea of a logo that wouldn't dismiss the doge heritage is a vectorised version of just the doge's nose.

**Comment by zmike** [comment]
Since I was summoned, I'll say explicitly that I have no hard feelings about the logo being replaced/modified/whatever, and we should always try to do what's best for the project and community.

**Comment by atouchet** [comment]
My thoughts on the proposed logo concepts:

- I like the designs that were posted by @jdm and would be happy with either of those or some variant of them. I agree with @pshaughn that the blue/green version looks a bit more like a unified image but I think that has more to do with the range of colours used. I think an orange version would be fine with a more cohesive looking colour palette.

- I don't mind lighthearted designs or keeping some humour around but I don't think the doge should be used in official branding. I was always under the assumption that was a bit of a goofy placeholder while something official was being finalized. In general I think using outdated internet memes in an official logo is a fundamentally bad idea for a number of reasons.

As an aside, is that Firefox Reality logo that was posted final? I don't think that low poly look is working too well and it doesn't even match the current Firefox branding.

**Comment by solarane** [comment]
Just my two cents:
1. A logo should remain 100% visible in small sizes. In those regards, I really like @raphaelbastide 's circular logo above.
2. Flat/material design would probably work best, because it's 2020 and those are pretty.
3. I personally much prefer the warm color palette compared to the cool one. In fact, I don't really like the cool color one at all.

Maybe that's because in the realm of browsers, cool colors are most commonly associated with IE and Safari OwO

**Comment by larsbergstrom** [comment]
@atouchet re: Firefox Reality, that's the current logo. The low poly work has resonated well with the industry and consumers in the VR/AR space, but agree it's not for everyone! It will eventually be updated again to the new branding scheme, but due to a combination of partner agreements (e.g., putting the logo on product boxes or in booths) and budget constraints (having to remake and revise a huge number of store listings and widespread online presence), I can't afford to change our product logo as often or quickly as other teams can. That would be the third logo change in ~18 months.

**Comment by jdm** [comment]
We've had a variety of constructive feedback here, so thanks everyone who contributed!

Since this is a platform logo rather than a full product logo, we're not as tied to the overall brand identity of the Firefox product family as we otherwise might be. Given that fact and the positive feedback around the blue/green logo variant, we're going to move ahead with that one. Keep an eye out for it in various public-facing places in the future!

**Comment by paulrouget** [comment]
@jdm could we get the HD non-jpg version of the banner in https://github.com/servo/servo/issues/3893#issuecomment-576283252 ?

**Comment by jdm** [comment]
I'm checking if the original designer still has access to them, since I do not.

**Comment by SimonSapin** [comment]
Ideally SVG, since this looks extremely vector-friendly.

**Comment by jdm** [comment]
https://gist.github.com/jdm/850deb728d66677e3557df61f66182b2
