### ISSUE TITLE
Upload 32 bit rust snapshots

### ISSUE THREAD

**Issue by jdm** [servo/servo#3899]
This is a tracking issue for enabling 32 bit builds without local Rust builds.

**Comment by larsbergstrom** [comment]
We're publishing 32-bit Linux Rust binaries in our snapshots now.

**Comment by claisan** [comment]
Why I've got this warning?
$ ./mach build -r
Downloading Rust snapshot...
Download failed (404): Not Found - https://servo-rust.s3.amazonaws.com/fddfd089b75379f1d25f81541572d69a93f95c4f/rustc-1.3.0-dev-i686-unknown-linux-gnu.tar.gz
Note: Servo does not currently bootstrap 32bit snapshots of Rust
See https://github.com/servo/servo/issues/3899

**Comment by jdm** [comment]
@larsbergstrom Did we consciously decide to stop publishing 32 bit snapshots?

**Comment by claisan** [comment]
OK. Just now I've seen that "it is currently developed on 64bit OS X, 64bit Linux, Android, and Gonk". Sorry and thanks for your reply.

**Comment by claisan** [comment]
OK. Just now I've seen that Servo "is currently developed on 64bit OS X, 64bit Linux, Android, and Gonk". Sorry and thanks for your reply.

**Comment by larsbergstrom** [comment]
Hrm, it looks like I just don't have the Linux snap builder set up correctly. I was wondering why they were only taking 4 hours instead of the usual 6 - that's probably it! I'll re-add them.

**Comment by claisan** [comment]
Ok, I'll wait for.
Thanks.

**Comment by SimonSapin** [comment]
I case @claisan is still waiting: we now use rust-lang.org nightly builds rather than our own builds, so 32-bit should be available.

**Comment by claisan** [comment]
@SimonSapin, yes, I was waiting. Thanks for your reply.
