### ISSUE TITLE
Color space issue

### ISSUE THREAD

**Issue by aydinkim** [servo/servo#391]
Hello co-workers,

I'm working on the Servo with linux and android.
It seems that current version of servo's rendering scheme obey the BGR color space rules.
Are there any reasons for using BGR internally? (because of hardware acceleration? or mac?)
If you have it, please let me know.

In OpenGLES(for android), there is no BGR flags in gl header, so that we have to add some kind of color space conversion codes(BGR -> RGB) into somewhere like rust-opengles or rust-layer.
Considering expansion to another platforms like android, It will be better to use the RGB space.
If there is no specific reason for using that BGR,
How about our suggestion below

https://gist.github.com/aydinkim/5432005

Thank you

**Comment by nox** [comment]
This issue isn't really actionable, closing.
