### ISSUE TITLE
Cache response types in XHR

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#3919]
See https://xhr.spec.whatwg.org/#response-json-object -- the parsed responses should be cached once calculated.

Should make `/XMLHttpRequest/response-json.htm` pass.

**Comment by Ms2ger** [comment]
Blocks #2525.

**Comment by KiChjang** [comment]
I'll see if I can fix this up.

**Comment by KiChjang** [comment]
Blocks #9489.

**Comment by KiChjang** [comment]
@Ms2ger So I suppose that we still have text responses to cache?

**Comment by Ms2ger** [comment]
I need to double check we got them all

**Comment by KiChjang** [comment]
@Ms2ger What's left to do here?

**Comment by Ms2ger** [comment]
ArrayBuffer is not implemented, and the rest is cached.
