### ISSUE TITLE
iframes should load about:blank by default

### ISSUE THREAD

**Issue by jdm** [servo/servo#3924]
https://html.spec.whatwg.org/multipage/embedded-content.html#process-the-iframe-attributes

In particular, this load must cause contentWindow to be non-null. https://hsivonen.fi/about-blank/ is good reading.

**Comment by Ms2ger** [comment]
https://github.com/jdm/servo/commit/e8aa1e10c3be1de6aeaee7c5a4ddb50e94f97b81
https://github.com/servo/servo/compare/master...Ms2ger:empty-iframe-load

**Comment by jdm** [comment]
Blocks #5236.

**Comment by jdm** [comment]
We fixed this in #13996.
