### ISSUE TITLE
Intermittent reftest failure in vertical-lr-blocks.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#3926]
From http://build.servo.org/builders/linux/builds/567/steps/shell_3/logs/stdio .

**Comment by nox** [comment]
This now apparently always fail with completely different results.

![capture d ecran 2016-01-02 a 19 46 32](https://cloud.githubusercontent.com/assets/123095/12075706/8b6b118a-b189-11e5-9d2a-17d5e38aa41f.png)

**Comment by nox** [comment]
Never mind… I didn't set `layout.writing-mode.enabled`.

**Comment by nox** [comment]
`./mach run --pref layout.writing-mode.enabled tests/wpt/mozilla/tests/css/vertical-lr-blocks.html` shows a blank page.

**Comment by jdm** [comment]
Hasn't been seen in months, not disabled => close.
