### ISSUE TITLE
Elements with display: table collapse if all children are floated

### ISSUE THREAD

**Issue by emersonveenstra** [servo/servo#3927]
Testcase is here for quick reference: http://tests.emersonveenstra.net/servo/servo-display-table-bug.html

Relevant snippet:

``` 
<style>
ul {
    display: table;
    margin: 0 auto;
    border: 1px solid red;
}
li {
    float: left;
}
</style>

<ul>
   <li>Menu 1</li>
   <li>Menu 2</li>
   <li>Menu 3</li>
</ul>
```

Actual behavior: When a element is styled with `display: table` and all its children are floated, the element collapses as if it is a block element.

Expected behavior: the parent should wrap around the children, because `display: table` creates a new block formatting context

**Comment by mrobinson** [comment]
Rendering of the above test case looks similar in legacy / non-legacy layout and also Firefox.
