### ISSUE TITLE
mach test-unit removes target/servo, which breaks other tests

### ISSUE THREAD

**Issue by andrewguertin** [servo/servo#3928]
When I run the tests by calling `./mach test`, the last lines of output are

```
Running cpu reftests...
Running gpu reftests...
Reference tests completed in 0.00s
Content tests completed in 0.00s
Binary path /home/andrew/local/src/servo/target/servo does not exist
```

This is the output of `test-ref`, `test-content`, and `test-wpt` failing to run. However, running `./mach build` and then any of those commands individually works.

What's happening is that `./mach test-unit` (which is the test that runs before them) removes `target/servo`, and that is the result of them trying to run without it. Indeed, at this point even `./mach run <url>` fails, because `target/servo` doesn't exist.

There's more to this though: `test-ref` and `test-content` both call `ensure_built_tests()`, which should (I think?) guarantee that `target/servo` exists. When running `./mach build; ./mach test-ref` the `ensure_built_tests()` call actually recompiles servo. So my guess is that `ensure_built_tests()` isn't actually checking what it needs to (that the outputs of building tests exist), but rather checking some cached value that says whether the last build was building tests.

**Comment by nox** [comment]
This is not true anymore, right?

**Comment by jdm** [comment]
Correct.
