### ISSUE TITLE
contentWindow always null for cross origin iframe

### ISSUE THREAD

**Issue by neojski** [servo/servo#3939]
Working on #3808, I've found the following issue:

```html
<html>
  <body>
    <iframe src="http://example.com" id="iframe"></iframe>
    <script>
    var iframe = document.getElementById('iframe');
    var intervalId = setInterval(function() {
      if (iframe.contentWindow) {
        clearInterval(intervalId);
        console.log('done');
        return;
      }
      console.log('will try contentWindow again in a sec')
    }, 1000);
    </script>
  </body>
</html>
```
It should just work (I'm using ugly setInteval because servo does not support load events on iframe). However, it does not as the iframe is cross origin.

I dug into this problem a little more and here's what I've found (thanks @jdm and @mrobinson):

In `htmliframeelement.rs` there's `GetContentWindow` which fails because `child` is `None`.

Why:
1. `process_the_iframe_attributes` sends a `LoadIframeUrlMsg` message to constellation
2. it is handled in `constellation.rs` by `handle_load_iframe_url_msg`
3. in our case (cross origin) `new_pipeline` is `None`
4. `self.new_pipeline` calls then `Pipeline::create` with `script_pipeline` set to `None`
5. `pipeline.rs` matches `script_pipeline` with `None` and does not send a `AttachLayoutMsg` to `ScriptControlChan` that normally then calls `handle_new_layout` which adds `new_page` to `parent_page`'s `children` (and so `GetContentWindow` fails)

As I'm new to the project I'm not really sure as how to fix it. In particular I don't know how do we make scripts in frames having different global contexts. I'd welcome some references as what should I read to understand it.

**Comment by jdm** [comment]
Relevant work:
* https://github.com/Ms2ger/servo/tree/xows
* https://github.com/jdm/servo/tree/postmessage (includes a super hacky implementation of cross-origin window.parent to support cross-origin postMessage; merely for investigative/exploratory purposes)

**Comment by jdm** [comment]
Actually, this work is being tracked in #2382 so no need to keep this open.
