### ISSUE TITLE
add css support list in tree

### ISSUE THREAD

**Issue by metajack** [servo/servo#3954]
We should move the data for https://docs.google.com/spreadsheets/d/1CxLS8w8GwK-2euVErrqpUUb76PiZa6w5h5EnGsL9KFs/edit?usp=sharing to an in tree list, and then generate a nice html display like we do doc generation. This will allow us to keep it up to date as new PRs land.

Additionally, element.style things only exist for things we actually support, but it would be nice not to maintain the list of supported features in two places. We should come up with a way to generate one from the other.

**Comment by mbrubeck** [comment]
Fixed by #10208.
