### ISSUE TITLE
Remove force_relayout calls from HTMLInputElement attribute handler methods

### ISSUE THREAD

**Issue by jdm** [servo/servo#3959]
Given that Element::after_set_attr and Element::before_remove_attr call Element::notify_content_changed, I believe that force_layout is extraneous and should be removed.

**Comment by jdm** [comment]
@ienzam Still planning to work on this?

**Comment by ienzam** [comment]
I am extremely sorry for not following up.
I will send a patch in one/two days.

**Comment by ienzam** [comment]
Hi jdm, created the patch again.
Sorry for the delay.
