### ISSUE TITLE
Rust upgrade for https://github.com/servo/servo/pull/3948 changed the results of the CORS WPT tests

### ISSUE THREAD

**Issue by glennw** [servo/servo#3965]
Investigate further to find out what changed and see if they can be re-enabled.

**Comment by frewsxcv** [comment]
Tests were reenabled in d4f6cf3f6b77bc8a1fdde9fc82907b0f2d58f243 and [are still enabled](https://github.com/servo/servo/blob/37c4051d21f5baacdf843510c8b111202ac2e876/tests/wpt/include.ini#L8-L9)
