### ISSUE TITLE
Redesign page loading

### ISSUE THREAD

**Issue by jdm** [servo/servo#3974]
`ScriptTask::load` and `parse_html` are weirdly tied up in each other. We can achieve a much cleaner separation of concerns in the following way:
* move all explicit networking out of parse_html and into callers. parse_html can take an iterator and parse chunks incrementally from it (we can use `load_bytes_iter` or something similar for network case)
* don't create a document until HTTP headers are received, at which point we can properly set the final page URL as well
* most of the contents of `ScriptTask::load` should probably migrate to a method on `Page` instead

**Comment by psdh** [comment]
I want to help fix this.

**Comment by jdm** [comment]
I think most of this has been accomplished since I filed this, and #4967 implements part of it as well. I'll file new bugs for anything specific that can be done.
