### ISSUE TITLE
'mach clean' does not clean cef target

### ISSUE THREAD

**Issue by zmike** [servo/servo#3975]
I assume it should?

**Comment by edunham** [comment]
It looks like `mach clean` currently nukes the entire `target` directory, but cef lives in `ports/`  along with geckolib, glutin, and gonk. @larsbergstrom, should `mach clean` remove all ports as well as targets?

**Comment by jdm** [comment]
`ports` is a source directory; I would be surprised if any build artifacts end up there.

**Comment by jdm** [comment]
Yeah, I just did a `./mach build-cef -v` and verified that all of the artifacts end up under `target`.
