### ISSUE TITLE
Loading fails on Android: cannot locate symbol "__tls_get_addr"

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#3988]
Since the last rust upgrade, the Android binary fails at startup during library loading:

> android_dlopen: Error from dlopen(/data/data/com.example.ServoAndroid/lib/libservo.so): dlopen failed: cannot locate symbol "__tls_get_addr" referenced by "libservo.so"...

Similar to old bug rust-lang/rust#10686.

**Comment by frewsxcv** [comment]
Is this still an issue / can this be closed?

**Comment by mbrubeck** [comment]
This is fixed since we stopped using libgreen.
