### ISSUE TITLE
Casting traits should  impl on JSRefs, not bare elements

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4001]
Currently, [`ElementBase`](http://doc.servo.org/script/dom/bindings/codegen/InheritTypes/trait.ElementBase.html), etc etc are ll implemented on the bare types.

This makes them hard to use beyond the in built traits like [`ElementCast`](http://doc.servo.org/script/dom/bindings/codegen/InheritTypes/trait.HTMLElementCast.html)

For example, I can't usefully define a trait which derives from `ElementBase` since we impl traits on JSRefs in the DOM code, and `ElementBase` isn't on JSRef.

It would be nice if the code was tweaked so that _all_ DOM traits (except perhaps `Reflectable`) were impld on `JSRef`s.

**Comment by nox** [comment]
JSRef is dead.
