### ISSUE TITLE
embedding: test integration is hard

### ISSUE THREAD

**Issue by zmike** [servo/servo#4024]
Here's an extremely trivial test example: https://gist.github.com/zmike/d09c7f76d9547dcaf304

It can be compiled with a simple `cc -o cef_test_alloc{,.c}` and will need to be run with `LD_PRELOAD=/absolute/path/to/libembedding-<githash>.so LD_LIBRARY_PATH=/absolute/path/to/ports/cef/target/dep ./cef_test_alloc` on linux and equivalent vars on osx.

@metajack

**Comment by larsbergstrom** [comment]
cc me
