### ISSUE TITLE
ACID 2 renders incompletely without mouse movement

### ISSUE THREAD

**Issue by nwin** [servo/servo#4033]
Currently acid 2 only renders completely if I move the mouse after clicking on the link. Otherwise it looks like this:

![acid2](https://cloud.githubusercontent.com/assets/949560/5094466/7c463290-6f61-11e4-9b8b-d40912821cf7.png)

on OSX 10.10

**Comment by Croydon** [comment]
Related to #7722?

**Comment by nwin** [comment]
Seems to be fixed now, #7722 is still persistent though.
