### ISSUE TITLE
Don't block script task while fetching external scripts

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#4088]
When fetching the source for a `<script>` element, `HTMLScriptElementHelpers::prepare` [calls `load_whole_resource`](https://github.com/servo/servo/blob/51aa2fde10daa8c98f5407e35b8abf01bd364788/components/script/dom/htmlscriptelement.rs#L186), which blocks the script task until the resource is fully loaded.  Instead we should fetch asynchronously, so the script event loop can spin while the network task fetches the script.

See also step 15 of the [prepare a script](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element:prepare-a-script) algorithm.

**Comment by nox** [comment]
This hasn't been true for a long time, AFAIK.
