### ISSUE TITLE
Missing steps from the "prepare a script" algorithm

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#4089]
Some parts of the [prepare a script](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element:prepare-a-script) algorithm from the HTML specification are not yet implemented.  See the "TODO" items in [`HTMLScriptElementHelpers::prepare`](https://github.com/servo/servo/blob/51aa2fde10daa8c98f5407e35b8abf01bd364788/components/script/dom/htmlscriptelement.rs#L113-L208).

* [ ]  Step 10. If the element is flagged as "parser-inserted", but the element's node document is not the Document of the parser that created the element, then abort these steps.
* [ ] Step 11. If scripting is disabled for the script element, then the user agent must abort these steps at this point. The script is not executed.
* [x] Step 12. If the script element has an `event` attribute and a `for` attribute, then run these substeps... (#4176).
* [ ] Step 13. If the script element has a `charset` attribute, then let the script block's character encoding for this script element be the result of getting an encoding from the value of the `charset` attribute.
* [ ] Step 14 and 15. Add support for the `defer` and `async` attributes. (For now, we fetch all scripts synchronously and execute them immediately.)  See also #4088.

**Comment by psdh** [comment]
I want to fix this, but I want some help with the second part of step 10.

**Comment by jdm** [comment]
The easiest way to implement that right now is to store the document associated with the window in the constructor, then compare that against the result of `document_from_node` later.
