### ISSUE TITLE
mach test-foo breaks when the test harness doesn't compile

### ISSUE THREAD

**Issue by jdm** [servo/servo#4103]
When I'm actively improving the test harness code (like contenttest.rs), it would be nice if when the harness code doesn't finish building the `mach test-content` command didn't spew out:
```
To learn more, run the command again with --verbose.
Error running mach:

    ['test-content']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 13] Permission denied

  File "/Users/jdm/src/servo-pristine/python/servo/testing_commands.py", line 131, in test_content
    ret = self.run_test("contenttest", test_args)
  File "/Users/jdm/src/servo-pristine/python/servo/testing_commands.py", line 43, in run_test
    return subprocess.call([t] + args, env=self.build_env())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
```

**Comment by awlnx** [comment]
So What is the Desired Behavior? Catch the Exception and then?

**Comment by Manishearth** [comment]
Just error early "The test harness did not compile".

**Comment by awlnx** [comment]
does test-content build the tests?

**Comment by Manishearth** [comment]
It builds the test runner, yes. Also `test-ref`

**Comment by awlnx** [comment]
alright. I will get working on this

**Comment by awlnx** [comment]
do you know what file I should edit to make building fail?

**Comment by jdm** [comment]
Either reftest.rs or contenttest.rs.

**Comment by awlnx** [comment]
I Couldn't replicate the output @jdm posted. On My System it would print the rustc output and continue to attempt to test: (test result: ok. 78 passed; 0 failed; 0 ignored; 0 measured). I made the function ensure_built_tests() exit with the return code of the subprocess call to build the tests if it is nonzero. Now the output reaches the rustc error and exits.

**Comment by awlnx** [comment]
The commit was accepted. Is there more to be done?

**Comment by Manishearth** [comment]
Nope, thanks!
