### ISSUE TITLE
Find a better place for tracking click_in_progress

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4105]
Depends on #4002 

Currently we store `click_in_progress` in each `Element`. 

Instead, perhaps we can store pointers to click--in-progress elements in `Document`?

**Comment by pshaughn** [comment]
https://critic.hoppipolla.co.uk/showcomment?chain=8873 no longer exists so I might not understand the full issue.

If this is about only caring about it on activateable elements, it's clear from the current spec that's not true: any HTMLElement can have .click() called on it, which will fire a bubbling MouseEvent named click. It doesn't have to be activateable, or even have a click listener directly on itself, for this to be observable, and for the re-entry protection of https://html.spec.whatwg.org/#dom-click to likewise be observable.

If this is about using as little space as possible, NodeFlags is a great place to put it; we still have unused bits there, and there's no bitfield on HTMLElement itself we could use.

I think the comment referring to this issue in node.rs could be removed and we could just close it, but maybe there's some other angle I'm not seeing.

**Comment by Manishearth** [comment]
Yeah this refers to a much older version of the spec, we should probably stick it in NodeFlags and close this issue.

**Comment by pshaughn** [comment]
It has been there. https://github.com/servo/servo/blob/master/components/script/dom/node.rs#L171-L173
