### ISSUE TITLE
Mixed integers and percentages in rgba() (css-color-4)

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#4106]
According to @pcwalton: https://critic.hoppipolla.co.uk/showcomment?chain=8797

We definitely have parsing code for it, so there might be a bug in gfx code.

**Comment by dralley** [comment]
I'm guessing this is fixed by now?

**Comment by SimonSapin** [comment]
This color parsing code is now shared with Firefox. I think as part of that Color Level 4 was implemented.
