### ISSUE TITLE
Mach should be able to display rustc/cargo --help

### ISSUE THREAD

**Issue by mttr** [servo/servo#4111]
Currently, we don't have a convenient way to get --help output from rustc/cargo. It would be nice if we could do it through mach. I'm not sure the best way to do this, but these are the ideas I've had so far:

`./mach [cargo/rustc]-help` -- though maybe a dedicated command is too much?
`--help-cargo` for any command that passes down arguments to cargo.

**Comment by mrobinson** [comment]
I think maybe `rustc --help` and `cargo --help` might be enough here. We are gradually moving toward being able to  build servo with cargo only.
