### ISSUE TITLE
Support non-circular border-radius

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#4126]
That is, a different horizontal and vertical radius in the same corner. #4020 only parses one value per corner because the gfx code only support drawing circular arcs.

**Comment by bjwbell** [comment]
Implemented with PR https://github.com/servo/servo/pull/7502 "Add elliptical border radius" and PR https://github.com/servo/servo/pull/7642 "Add elliptical border-radius shorthand parsing".
