### ISSUE TITLE
Text input is hard-wired to QWERTY

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#4144]
It seems that Servo receives keyboard event based on physical keys, and has its own interpretation of how to map they to text which assumes a QWERTY keyboard.

The fix is **not** to add support for more keyboard layouts. Servo should not be in the business of maintaining a repository of all keyboard layouts in the world, this is the job of the operating system. Servo should have the operating system give it Unicode text in a way that supports whatever [input method (a.k.a. IME)](https://en.wikipedia.org/wiki/Input_method) the operating system may or may not have.

CC @jdm

**Comment by metajack** [comment]
@glennw Now that glutin is default, perhaps the time has come to at least document here what we should be doing.

**Comment by adrianheine** [comment]
This also applies to for example zooming. With a German keyboard layout, I cannot zoom out, since my `=` is actually `SHIFT | CONTROL Num0`.

**Comment by paulrouget** [comment]
Can someone explain what needs to be done here?

**Comment by SimonSapin** [comment]
@paulrouget I think we want to handle `Event::ReceivedCharacter(char)` events from glutin as well as `Event::KeyboardInput(ElementState, ScanCode, Option<VirtualKeyCode>)`, but there’s probably a number of places in Servo to change.

@glennw You said you wanted to do this? :)

**Comment by paulrouget** [comment]
@SimonSapin can we save the character received in `Event::ReceivedCharacter`, and in `Event::KeyboardInput`, use the saved character to build the `Key` instead of `key_code` (via `glutin_key_to_script_key`)?

We could probably reuse `key_from_string`: https://github.com/servo/servo/blob/fb3fe3d784c24cdfd8040af0282e5c2182ee2051/components/script/dom/keyboardevent.rs#L325

**Comment by SimonSapin** [comment]
@paulrouget I think this would only work for ASCII at best. Most Unicode characters don’t have a corresponding key code.

**Comment by paulrouget** [comment]
Right.

`ReceivedCharacter` doesn't work for many characters apparently (at least on mac). For example the `é` key or `` `+e `` -> `é` doesn't trigger a `ReceivedCharacter` event. I'm wondering if that works on Linux and Windows.

Then, the `KeyEvent` should have a `char_code` on `KeyState::Released`, based on the `ReceivedCharacter` event.

Then the input can be fed with the charcode.

**Comment by SimonSapin** [comment]
I was just speculating about `ReceivedCharacter`. I’ve filed https://github.com/tomaka/glutin/issues/719

**Comment by SimonSapin** [comment]
@paul, it sounds like you’re hitting glutin bugs. Could you file steps to reproduce on https://github.com/tomaka/glutin/issues ?

**Comment by paulrouget** [comment]
https://github.com/tomaka/glutin/issues/721

**Comment by paulrouget** [comment]
So we need to bring the character down to textinput.rs.

It should be enough to initialize the keyboard event with this character + virtual keycode.

Keyboard events are initialized with the help of the `key_properties` function: https://github.com/servo/servo/blob/4c4df37a128d2848f13fc2e5ebd4d69a4db8c483/components/script/dom/keyboardevent.rs#L114

Here, relevant properties are set.

From what I understand:
* `key_string`: it should use the character. If there's no character, this should be derived from the virtual keycode. This will be used in textinput.rs to print the apropriate character
* `code`: it should use the virtual keycode
* `location`: it should use the virtual keycode
* `char_code`: it should use the character
* `key_code`: if character is an *ascii* character, it should use the character, otherwise, the keycode

I managed to bring the character value to this function (see https://gist.github.com/paulrouget/668c3dcdb7dbfed7909a). But then I'm having troubles with strings.

`from_string` is a static str. We need a string (because it's not always a character).

What is the appropriate type? `String`?

Can someone tell me if all of that makes sense?

**Comment by SimonSapin** [comment]
> So we need to bring the character down to textinput.rs.
>
> It should be enough to initialize the keyboard event with this character + virtual keycode.

How would this be done? `Event::ReceivedCharacter` is separate from `Event::KeyboardInput` in glutin, and as far as I know they don’t map 1 to 1: a single character sometimes requires more than one key press to type, and a key press sequence could overall result in more than one `char` at once e.g. in complex input methods like Japanese.

Shouldn’t we rather bring both kinds of events separately to `textinput.rs`?

**Comment by jdm** [comment]
@paul I don't understand your questions about `from_string` and `String`, unfortunately. At least, I don't understand how they're related to the gist.

**Comment by paulrouget** [comment]
Erf, I meant `key_string`, not `from_string`. My comment is not clear. I'll come back with more specific questions.

**Comment by paulrouget** [comment]
> Shouldn’t we rather bring both kinds of events separately to textinput.rs?

We could.

I am assuming that there's always a `KeyboardInput` event for a `ReceivedCharacter` event (the inverse is not true). So attaching the character to the keyboard event might be enough.

> How would this be done? Event::ReceivedCharacter is separate from Event::KeyboardInput in glutin, and as far as I know they don’t map 1 to 1: a single character sometimes requires more than one key press to type, and a key press sequence could overall result in more than one char at once e.g. in complex input methods like Japanese.

I'm not sure glutin supports that. ReceivedCharacter is only one char.

If we want to support complex input methods (IME), we need to support [composition events](https://w3c.github.io/uievents/#events-compositionevents).

My approach is just a quick-and-dirty way to support azerty layout (we have developers who use this layout, and the hardcoded qwerty-layout is a bit annoying for them :) ).

IME and composition events support is a lot of work I imagine. Is that a thing we are willing to work on soon? If not, is it ok to implement my suggested approach of forwarding the character to `textinput.rs` via the keyboard event?

**Comment by paulrouget** [comment]
Apparently, this is a osx-specific issue.

**Comment by adrianheine** [comment]
It was for me on January, 2nd.

**Comment by paulrouget** [comment]
> It was for me on January, 2nd.

Oh, I thought @mbrubeck could type with dvorak on Linux.

**Comment by mbrubeck** [comment]
Yes, everything seems fine on my Linux laptop using X11 with a Dvorak keymap.

**Comment by adamncasey** [comment]
On Windows, quite a few ASCII key events (e.g. :~@;'# ) aren't assigned virtual key codes in glutin. Servo currently ignores all key events which don't have a virtual key code.
https://github.com/servo/servo/blob/84d3ba075977c55d226bd6b70d695a292b2329c9/ports/glutin/window.rs#L199

Should I file a separate bug for this problem, or will the work here address this?

**Comment by adamncasey** [comment]
Also, from glancing at the glutin code, X11 virtual key codes are much more specific than Windows / OS X / Wayland(?) - which might explain why some keymaps are OK and some aren't.

X11: https://github.com/tomaka/glutin/blob/master/src/api/x11/events.rs#L5
Cocao: https://github.com/tomaka/glutin/blob/master/src/api/cocoa/event.rs
Windows: https://github.com/tomaka/glutin/blob/master/src/api/win32/event.rs

**Comment by tdaede** [comment]
Yes, X11 and Wayland both use libxcbcommon now, which has "keycodes" which are independent of the labels on the keyboard, and "keysyms" that take the layout into account. The glutin code uses keysyms for its key events.

This is still not sufficient for a fully featured text field though - IME's currently don't work at all, meaning no CJK text input.

**Comment by metajack** [comment]
@SimonSapin mentioned he might have a look at this.

**Comment by paulrouget** [comment]
If we ever want to release a developer review of servo+bhtml, we need to do something about this issue.
Getting IME and composition events to work will require a lot of time and is not something we can get done in time.

But there's probably a way to improve the situation, like using `ReceivedCharacter` with `KeyboardInput` to at least try to get the right mono-key characters.

P3 -> P1
