### ISSUE TITLE
Investigate /workers/interfaces/WorkerGlobalScope/location/redirect.html

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4146]
The wpt test fails, I'm not yet sure why (#4065 moves it from a timeout to a failure)

 - How to run it: `./mach test-wpt --include=/workers/interfaces/WorkerGlobalScope/location/redirect.html`
- Test location: `tests/wpt/web-platform-tests/workers/interfaces/WorkerGlobalScope/location/redirect.html`

If you would like to run the test with a debugger attached, instructions on setting up the WPT server can be found in `tests/wpt/README.md`

**Comment by psdh** [comment]
I'll take a shot at this

**Comment by jdm** [comment]
@psdh Did you discover anything?

**Comment by psdh** [comment]
@jdm, This seems to have slipped off my mind. I am not sure if I can attack this very early. Is this urgent?

**Comment by jdm** [comment]
Nope!

**Comment by psdh** [comment]
I have looked at the debugger output, but I am not really sure how to proceed.

**Comment by jdm** [comment]
First step is identify the particular failing assertion. Second step is to figure out what part of the test is failing. Third step is to figure out what Rust code is executing. Fourth step is to figure out what should be happening instead :)

**Comment by mintern** [comment]
Thank you very much for your patient and helpful review!
