### ISSUE TITLE
Ungate and use `if let` everywhere

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4153]
Similar to https://github.com/rust-lang/rust/pull/19405/files

Use `if let` to reduce match statements of the form 

```
match foo {
 (some pattern here) => {....}
 _ => ()

}
```

with 

```
if let (pattern) = foo {
...
}
```

(This can be handled as smaller easy bugs, one for each crate)

We also might want to consider replacing `Option::map` with an `if let`; `map` is slightly inefficient  (though perhaps it will become better post unboxed closures)

**Comment by zslayton** [comment]
This seems like it might be a good first bug; would it be alright if I took a crack at it?

**Comment by Manishearth** [comment]
Sure! I'm not sure how many cases of matches of this type are left, but you can surely try! :)

**Comment by jdm** [comment]
The other PR never merged, so there are a bunch that can be changed.

**Comment by payload** [comment]
You can use the pcregrep above to quickly count and find the usual cases.

**Comment by zslayton** [comment]
Thanks all, I'm hoping to find some time to look at this in the next couple of nights.
