### ISSUE TITLE
Consider combining the constellation and compositor tasks

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#4154]
When implementing some basic features of the `CefFrame` API, I found it necessary for the compositor thread to block on the constellation thread. This led me to wonder whether we're better served by just combining the two tasks, to avoid the memory overhead of multiple threads and to reduce complexity by eliminating the requirement that algorithms that involve the two be distributed algorithms.

Both the constellation and the compositor both live in `compositing`, suggesting their natural connection, and most other browser engines combine the two threads as well. This should not be a performance issue since the constellation doesn't do any heavy computation—it's purely coordination.

**Comment by KiChjang** [comment]
Is this still desired, given that we have a different model?
