### ISSUE TITLE
Make l20n work in Servo

### ISSUE THREAD

**Issue by zbraniecki** [servo/servo#4159]
Servo is very close to have everything needed to support l20n.js in its current form. Let's track what's missing.

**Comment by zbraniecki** [comment]
Depends on #4282

**Comment by jdm** [comment]
These dependencies seem to belie the original assertion of "very close" :)

**Comment by zbraniecki** [comment]
We didn't use Promise at the time when I tested and dataset was about to land. Now we have MutationObserver and Promise missing - it's a bit further, but both depend on the same issue (microtasks) which is progressing.

**Comment by zbraniecki** [comment]
Also, pending #4283

**Comment by zbraniecki** [comment]
As of today, l20n is only blocked by #1980

**Comment by fabricedesre** [comment]
@zbraniecki Now that https://github.com/servo/servo/pull/20740 has landed I think we are in a much better shape. Do you have a test suite we can run on Servo?

**Comment by zbraniecki** [comment]
www.projectfluent.org uses Fluent (which is the new incarnation of L20n). If it doesn't work, I'll have to dig deeper to find what breaks.
You can also try a simple example - https://github.com/projectfluent/fluent.js/blob/master/fluent-web/examples/simple.html

**Comment by zbraniecki** [comment]
Ok, the website seems to work! The exampl doesn't because servo uses old SpiderMonkey(?) - async functions don't work, `const` in for loops etc. I think once we get an update of SM we should be good! :)

**Comment by zbraniecki** [comment]
I believe that means we're only blocked by #20585 now.

**Comment by fabricedesre** [comment]
Right now we can run in "compat" mode, but yes we need https://github.com/servo/servo/issues/20585 to get all the goodies.

**Comment by atouchet** [comment]
#20585 has now been done.

**Comment by zbraniecki** [comment]
Yay! Confirmed that latest servo works with FluentDOM and FluentWeb! It properly displays https://www.projectfluent.org as well :)
