### ISSUE TITLE
Step 12 of the "prepare a script" algorithm

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#4176]
Implement step 12 of the [prepare a script](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element:prepare-a-script) algorithm from the HTML specification, by adding code to [`HTMLScriptElementHelpers::prepare`](https://github.com/servo/servo/blob/51aa2fde10daa8c98f5407e35b8abf01bd364788/components/script/dom/htmlscriptelement.rs#L113-L208).

> 12\. If the script element has an `event` attribute and a `for` attribute, then run these substeps:
>
> 1. Let `for` be the value of the `for` attribute.
> 1. Let `event` be the value of the `event` attribute.
> 1. Strip leading and trailing whitespace from `event` and `for`.
> 1. If `for` is not an ASCII case-insensitive match for the string `"window"`, then the user agent must abort these steps at this point. The script is not executed.
> 1. If `event` is not an ASCII case-insensitive match for either the string `"onload"` or the string `"onload()"`, then the user agent must abort these steps at this point. The script is not executed.

This is part of #4089.

**Comment by psdh** [comment]
Assuming that @th0114nd isn't still working on this(are you?). 
I will try and fix this :)

**Comment by psdh** [comment]
@mbrubeck needed some help here: 
I am new to servo and rust and am facing a tough time finding how to access say the 'for' attribute, 
element.get_attribute(ns!(""), &atom("for")).root() ?
I was thinking something like http://pastebin.mozilla.org/8584728

Thanks :)

**Comment by mbrubeck** [comment]
> `element.get_attribute(ns!(""), &atom("for")).root()` ?

Yes, this looks correct.  After you unwrap the resulting Option, you'll need to call `.r().Value()` to convert it to a string, like in [this example code](https://github.com/servo/servo/blob/master/components/script/dom/htmlscriptelement.rs#L189-L191).  (If you're curious why, [this page](https://github.com/servo/servo/wiki/Using-DOM-types) has some explanations.)

**Comment by psdh** [comment]
please check this, http://pastebin.mozilla.org/8585585
I have pasted my changes and the build error that I am getting.

**Comment by jdm** [comment]
Ah, that happens when the string isn't in a list in https://github.com/servo/string-cache/ somewhere. In that case, you can use `Atom::from_slice("event")` instead of `atom!("event")`.

**Comment by psdh** [comment]
@mbrubeck: I think this can be closed, now that the PR has merged
