### ISSUE TITLE
Change functional instantiation of MIMECheckers to constants

### ISSUE THREAD

**Issue by IdeaHat** [servo/servo#4182]
Follow on issue to #3144

The functional ByteMatcher instantiations (~line 470), the GroupedByteMatcher, and the MIMEClassifier should all be instantiated as static constants rather than as instances. The scope of the composite type members (such as the byte_matchers member of GroupedByteMatcher) should be changed from a owned scope to a static scope to support this.

This could not be implemented (and will be blocked by) the following issue with the rust compiler:

https://github.com/rust-lang/rust/issues/19380

**Comment by nox** [comment]
I'm pretty sure this is not applicable anymore.
