### ISSUE TITLE
Add context-based MIME sniffing

### ISSUE THREAD

**Issue by IdeaHat** [servo/servo#4183]
Follow on issue to #3144

Context based mime sniffing is described in https://mimesniff.spec.whatwg.org/#context-specific-sniffing. Certain types (such as fonts) can only be sniffed from a context. However, this will require more metadata to be handed to the sniffer task.

**Comment by jdm** [comment]
We should add a `Context` enum and require it to be passed to the `LoadData` constructor. We can then use this in `start_sending_sniffed_opt` (pass it as an argument) and have special rules for each of the contexts described in the spec.

**Comment by jdm** [comment]
Code: components/net_traits/lib.rs

**Comment by Yoric** [comment]
I can try to work on that. @jdm, do I understand correctly that the `Context` enum would be one of `Browsing`/`Image`/`AudioVideo`/`Plugin`/`Style`/`Script`/`Font`/`Text Track`/`Cache Manifest`?

**Comment by jdm** [comment]
That looks fine for a first pass. We'll probably end up mapping those to the values for initiator, type, and destination in [the fetch specification](https://fetch.spec.whatwg.org/#concept-request-initiator) at some point, but let's focus on the MIME sniffing spec for now.

**Comment by Yoric** [comment]
I'll do that. Any suggestion how I can test it?

**Comment by jdm** [comment]
Using a local web server and running Servo with `--sniff-mime-types` will allow the snifing code to actually execute.

**Comment by jdm** [comment]
A straightforward testcase to use will be loading a URL which has a non-text/html MIME type but returns HTML content.

**Comment by Yoric** [comment]
Testing in progress. Do you think it would be possible to put something in the testsuite?

**Comment by Yoric** [comment]
So, I configured Apache to associate mp4 to `application/video` and I ran the following:

````
./mach run --sniff-mime-types http://localhost/~david/test/text_html_content_with_non_text_html_mime_type.mp4
````
where my file is actually html content.

Servo renders it as html, regardless of `--sniff-mime-types`, I'm not sure how I should interpret the result.

**Comment by jdm** [comment]
Oh right, #7706 is about changing our HTML parser to actually care about the MIME type. If you use a type like `image/jpeg` instead, that should show a difference with `--sniff-mime-types`.

**Comment by Yoric** [comment]
How so? Won't Servo attempt to sniff it in a Browser context regardless of my patch?

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/components/script/dom/servohtmlparser.rs#115 looks at the computed mime type and creates an image document if we think we have an image. If we sniff the response first and discover HTML content, the result should be a non-image document with sniffing enabled.

**Comment by Yoric** [comment]
I still don't follow. Unless I misunderstand the specs, by default, Servo will be in `Browser` context, so it will sniff exactly the same thing regardless of my patch, right?
