### ISSUE TITLE
Implement parsing of no-sniff and check-for-apache-bug in header Resource handlers

### ISSUE THREAD

**Issue by IdeaHat** [servo/servo#4184]
Follow on issue to #3144

no-sniff and check-for-apache-bug (described in Section 5, https://mimesniff.spec.whatwg.org/#handling-a-resource )should be parsed and passed as part of the HeaderCollection and parsed in the Loaders. 

These flags should be passed to the mime sniffing algorithm via the SnifferTask (they are currently hard coded).

**Comment by jdm** [comment]
Note: #3144 still has not been merged, so this can't be worked on yet.

**Comment by jdm** [comment]
Now waiting on #5005 instead.

**Comment by jdm** [comment]
Relevant code: components/net/http_loader.rs, components/net/mime_classifier.rs

**Comment by Wafflespeanut** [comment]
@jdm Let's close this :)
