### ISSUE TITLE
Show the new page sooner during navigation

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#4201]
I'm told by @bzbarsky that this is roughly what Gecko does:

We start reflowing:
- After the `<body>` open tag is parsed; _and_
- All the CSS style sheets that were encountered _before_ the open `<body>` tag have loaded.

We then show the new page 200ms after the first reflow starts.

**Comment by Adenilson** [comment]
I would like to work on this one if is still available.

**Comment by jdm** [comment]
It is available.

**Comment by nox** [comment]
This was done in #6028.
