### ISSUE TITLE
Servo should create a headers object in file_loader

### ISSUE THREAD

**Issue by djzager** [servo/servo#4212]
Follow on issue to #3144 

Currently when a file from the filesystem is loaded in servo, no response headers are generated. This prevents testing via XMLHttpRequest.

For reference:
http://pastebin.com/k3kyci7m

**Comment by jdm** [comment]
For determining a Content-Type header, we could use https://github.com/cybergeek94/mime_guess .

**Comment by Darktori** [comment]
I'll see what I can do!

**Comment by Ms2ger** [comment]
For future reference, jdm's test uses a test harness that no longer exists. Since the replacement (`tests/wpt`) runs from a http server, it's not trivial to translate the test.

An alternative could be a unit test (`tests/unit/net/`); I'm not sure what that would look like, though.

**Comment by KiChjang** [comment]
I'll take this one.

**Comment by KiChjang** [comment]
I've gotten to the part where I've set `content_type` for `metadata`, yet `metadata` is still missing an appropriate `Header`. What should be included in a `Header`?

**Comment by jdm** [comment]
Plausibly we don't actually want a headers object, since that's very HTTP specific. If we just make the content_type value available, that should be enough.

**Comment by eefriedman** [comment]
We need to fake up some actual headers for XMLHTTPRequest... see https://fetch.spec.whatwg.org/#concept-basic-fetch .  Granted, it would be reasonable to argue that we don't need to do that in the network layer, and we should construct the fake headers in `script/` where necessary.

For reference, the HTTP unit-tests manipulate Header objects in various ways: https://github.com/servo/servo/blob/master/tests/unit/net/http_loader.rs#L358 .
