### ISSUE TITLE
bindings codegen dependencies are broken

### ISSUE THREAD

**Issue by froydnj** [servo/servo#4239]
The dependencies for the generated files in the bindings codegen are incomplete (`Bindings/mod.rs`, `UnionTypes.rs`, `RegisterBindings.rs`, etc.).  This is not normally a problem, but it does result in a weird failure mode one can encounter when building Servo:
- Generate bindings bits
- Run out of disk space whilst generating bindings, so the generated binding files are incomplete
- Blow away everything underneath the `Bindings` directory, and the generated `.rs` files
- Become very confused when the build complains that it can't find the `Bindings` module, because `make` didn't realize that it needed to re-run `GlobalGen.py`

**Comment by dralley** [comment]
I'm guessing this is resolved by now?

**Comment by jdm** [comment]
I think the switch to cmake improved the situation.
