### ISSUE TITLE
Support status codes >599

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4246]
[Related commit](https://github.com/Manishearth/servo/commit/642e76668809f6b5a201bc8eb6fea7a4ccca9172), [related hyper issue](https://github.com/hyperium/hyper/issues/177)

Hyper doesn't seem to do this properly (yet), filing this issue to track it.

**Comment by pyfisch** [comment]
@Manishearth This is fixed on hypers side.

**Comment by frewsxcv** [comment]
This might be fixed, though I haven't done any testing

**Comment by frewsxcv** [comment]
Hyper was bumped in https://github.com/servo/servo/commit/5f15eb5fbfb7a8649132cc8b3a07314389836714#diff-56f2ed33851545b8cf36528f7c0781c7 which [removed these test failures](https://github.com/Manishearth/servo/commit/642e76668809f6b5a201bc8eb6fea7a4ccca9172).

I also just wrote a small server and tested it can handle status code >599.
