### ISSUE TITLE
Implement URLUtils

### ISSUE THREAD

**Issue by Zirak** [servo/servo#4250]
Spec: https://url.spec.whatwg.org/#urlutils-and-urlutilsreadonly-members

It's an interface used in several places, for instance [HTMLAnchorElement](https://html.spec.whatwg.org/multipage/semantics.html#htmlanchorelement) and [Location](https://html.spec.whatwg.org/multipage/browsers.html#the-location-interface).

I'd like to try and take it on myself.

**Comment by frewsxcv** [comment]
Is there anything else actionable here? I think this interface is gone https://github.com/whatwg/url/issues/62

**Comment by jdm** [comment]
Yeah, we now have HTMLHyperlinkUtils instead, iirc. Nothing to be done here.
