### ISSUE TITLE
Click event should be a MouseEvent, not a plain Event

### ISSUE THREAD

**Issue by jdm** [servo/servo#4260]
The `handle_click_event` method in `script_task.rs` creates a plain Event. According to https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3-Events.html#event-type-click we should be using a MouseEvent instead. We don't have information like the current modifier keys available right now, so we can assume false for them.

**Comment by jdm** [comment]
@liamzdenek it looks like you had a fix for this but never made a PR :( Want to do that? :)

**Comment by liamzdenek** [comment]
Sorry about that, must have gotten distracted and forgot. The PR is here: https://github.com/servo/servo/pull/4718
