### ISSUE TITLE
<center> should not propagate centered text alignment down into tables

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#4276]
So I can't interpret https://html.spec.whatwg.org/multipage/rendering.html#the-css-user-agent-style-sheet-and-presentational-hints to determine what it says to do here, but what Servo does breaks Hacker News. `<center>` should not propagate centered text alignment down into `<table>`.

cc @SimonSapin @Ms2ger

**Comment by nox** [comment]
Restoring quirks-mode.css to the initial quirks table rules that @Ms2ger pasted fixes the problem on HN.

**Comment by dralley** [comment]
This looks like it works now

![Screenshot from 2020-04-20 19-49-31](https://user-images.githubusercontent.com/2751996/79810046-16176900-8340-11ea-9aea-ba3be26f5069.png)
