### ISSUE TITLE
Implement Promise in Servo

### ISSUE THREAD

**Issue by saneyuki** [servo/servo#4282]
We need ES6 `Promise` implementation to support some APIs and dogfooding. However,  SpiderMonkey has not been implemented it yet because there are a web standards problems with how the JS virtual machine's event loop should interact with the event loop of the web browser itself.

Therefore, we need to implement `Promise` in Servo until SM gets `Promise` in itself.

See also:  https://github.com/servo/servo/wiki/Mozlandia-JS#promises

**Comment by farodin91** [comment]
I like to do this.

**Comment by jdm** [comment]
At least #4283 needs to be completed first, and we probably need to run any proposed design by the more-experienced Gecko developers first to make sure we don't do anything silly.

**Comment by farodin91** [comment]
Okay

**Comment by Ms2ger** [comment]
Something happened: https://bugzilla.mozilla.org/show_bug.cgi?id=1185106

**Comment by larsbergstrom** [comment]
@tschneidereit is planning to work on this in Q1.

**Comment by tschneidereit** [comment]
Indeed. I am working on it right now in that I'm implementing Promises in
SpiderMonkey. Once that's landed, I'll start working on the Servo
integration.

**Comment by larsbergstrom** [comment]
It looks like @nox landed the SpiderMonkey update with your work!

@tschneidereit do you know what the timeline is for promises in Servo?

The WebBluetooth folks (cc @loki04) were wondering. Thanks!

**Comment by nox** [comment]
IIRC they can't enable SM promises yet in Gecko itself because of win32 issues, but @tschneidereit knows all there is to know about them so let's wait for his reply.

**Comment by jdm** [comment]
```
10:01 <till> jdm: we can prototype it right now. For actually enabling it we *need* bug 1272887 and bug 1280789, and *want* half of the patches pending review in bug 911216
10:01 <firebot> https://bugzil.la/1272887 — FIXED, sphink — win32 crash during GC when using PersistentRooted<GCVector>
10:01 <firebot> https://bugzil.la/1280789 — FIXED — unbreak mingw builds after 1272887
10:01 <firebot> https://bugzil.la/911216 — ASSIGNED, till — Implement promises in the JavaScript engine
10:01 <jdm> till: ok, so an SM upgrade right now won't even get us to the point we'll need to be at?
10:01 <till> jdm: in other words, a smup beginning next week :)
```
I'm going to start prototyping codegen integration.

**Comment by jdm** [comment]
https://github.com/servo/servo/compare/master...jdm:promise-binding is what I've got so far. The rooting story for the JS promise values is not great yet, but it's probably no worse than how we deal with EventTarget and other callbacks?

**Comment by jdm** [comment]
Blocks #11894.
