### ISSUE TITLE
Incorrect layout of element following a float, involving margins

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#4307]
Servo lays out the following test case incorrectly.  The text in `#lower` is completely clear of the float, so it should not be impacted.  However, in Servo it is.  The problem is triggered if the float extends below the border box of `#upper` but not its margin box.

``` html
<html>
  <head>
    <style>
      * { margin: 0; padding: 0; }
      div { border: 1px solid black; }
      #float { float: left; height: 100px; width: 100px; }
      #upper { height: 85px; margin-bottom: 20px; }
    </style>
  </head>
  <body>
    <div id="float"></div>
    <div id="upper"></div>
    <div id="lower">This should be left-aligned.</div>
  </body>
</html>
```

(This is a minimal test case based [my home page](http://limpet.net/mbrubeck/), which triggers the bug in the wild.)

**Comment by mrobinson** [comment]
This is broken in legacy layout, but working in non-legacy layout, so I'm going to go ahead and close it as part of our effort to close legacy layout bugs.
