### ISSUE TITLE
Servo can't render OpenType ligatures in 'mort' or 'morx' format, only in 'GSUB'

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#4320]
So there are at least three ways to specify ligatures in TrueType/OpenType fonts: `mort`, `morx`, and `GSUB`. `GSUB` is the newest. However, all of my fonts only have `mort` or `morx`. So ligatures don't render in most fonts.

I guess we have to convert from `mort` or `morx` to `GSUB`.

**Comment by mbrubeck** [comment]
If someone wants to enable this on Mac OS, they can clone the servo/rust-harfbuzz repo and edit the [makefile.cargo](https://github.com/servo/rust-harfbuzz/blob/ed6531a7de68fd4b9d7d4fb285dd807bc30eab11/harfbuzz-sys/makefile.cargo) to add `--with-coretext` to the configure arguments if `$TARGET` contains `"apple-darwin"`.

(Cross-platform support is outside of the Servo scope; we'll just wait for it to be implemented in Harfbuzz.)

**Comment by behdad** [comment]
sgtm

**Comment by jdm** [comment]
All that's left here is upgrading the version of harfbuzz that Servo uses: `./mach cargo-update -p harfbuzz-sys`

**Comment by mbrubeck** [comment]
#11591 includes the harfbuzz-sys update.
