### ISSUE TITLE
Implement rooted vectors for DOM objects and SpiderMonkey primitives

### ISSUE THREAD

**Issue by jdm** [servo/servo#4334]
We currently make use of stack constructs like `Vec<Rooted<T>>`. This is totally unsafe since the values are not actually on the stack; they live on the heap instead. We need to build a replacement that stores a pointer to itself in TLS, and create a GC hook that will trace all known stack collections at any given point in time.

**Comment by frewsxcv** [comment]
@mukilan Still working on this?

**Comment by jdm** [comment]
RootedVec exists now.
