### ISSUE TITLE
Write plugins to keep check on performance

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4348]
This is more of a meta bug, ideas for heuristics which can be used to avoid unnecessary allocations (etc) go here.

Some initial ones that I'm working on:
- Disallow `&x.clone()`
- Check for unused clones. This can be done via the same heuristics as `unused_must_use` or `unused_variable`, with the tweak that we don't count a `.clone()` as a "usage"

Ideas welcome!

**Comment by mrobinson** [comment]
I think this is something that should handled by clippy now.
