### ISSUE TITLE
Implement Window#parent correctly.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4351]
Right now, we always return the window itself; this probably will meet the same issues as #4350.

Blocks #2968.

* Spec: <https://html.spec.whatwg.org/multipage/#dom-parent>.
* Code: `components/script/dom/window.rs`.
* Test: `html/browsers/windows/browsing-context-first-created.xhtml`, `html/browsers/origin/cross-origin-objects/cross-origin-objects.html`, `webmessaging/event.source.xorigin.sub.htm`.

**Comment by jdm** [comment]
#4811
