### ISSUE TITLE
Support FIDO Universal 2nd Factor (U2F)

### ISSUE THREAD

**Issue by l0kod** [servo/servo#4364]
As explain in an [Air Mozilla presentation](https://air.mozilla.org/fido-u2f/), Universal 2nd Factor (U2F) is a new, open authentication standard focused on adding public-key cryptography to existing password authentication mechanisms, offering high security with friction-less user experience.

The final 1.0 [specifications](https://fidoalliance.org/specifications/download/) have been published this week.

**Comment by bzbarsky** [comment]
Please note that Firefox is planning to NOT implement this API and to implement https://w3c.github.io/webauthn/ once that's ready instead.  See the intent to implement/ship threads for this stuff, where people pointed out that the FIDO specs range somewhere between "terrible" and "broken".
