### ISSUE TITLE
HarfBuzz shaping?

### ISSUE THREAD

**Issue by ebraminio** [servo/servo#4382]
When I run `./mach run http://fa.wikipedia.org` I get:
![a](https://cloud.githubusercontent.com/assets/833473/5442797/9d7b4648-84b1-11e4-8a81-2d4647fdb14d.png)
With comparing to Firefox or Chrome, you can see a lot issues like lack of BiDi or applying border-radius style and these are completely understandable for work in progress project. . . however the thing I don't expect is lack of shaping (joining Arabic characters) while you do link against HarfBuzz already and using HarfBuzz for shaping. Is there something I am missing like command line run-time flag to enable shaping and HarfBuzz or it is just linked but not used yet?

**Comment by mbrubeck** [comment]
Fixed by #7786.

**Comment by behdad** [comment]
> @behdad, should it be based on the Unicode Script property?

Yes.
