### ISSUE TITLE
Build fails in Arch Linux

### ISSUE THREAD

**Issue by ogarcia** [servo/servo#4391]
Build fails in Arch Linux

Executing ./mach build in Arch clean machine gives the error:
```
Failed to run custom build command for `glfw-sys v3.0.4 (https://github.com/servo/glfw?ref=cargo-3.0.4#765dace7)`
Process didn't exit successfully: `make -f makefile.cargo` (status=2)
...
CMake Error at CMakeLists.txt:213 (message):
  The XInput library and headers were not found
```

This is because libxi is not installed. It must be a dependency:
`pacman -S libxi`

When you fix this error new error appears:
```
Failed to run custom build command for `skia-sys v0.0.20130412 (https://github.com/servo/skia?ref=upstream-2014-06-16#35649d0c)`
Process didn't exit successfully: `make -f makefile.cargo -j4` (status=2)
...
src/gpu/gl/unix/SkNativeGLContext_unix.cpp:10:20: fatal error: GL/glu.h: No such file or directory
 #include <GL/glu.h>
```

Other dependency unsatisfied, glu:
`pacman -S glu`

Please, include **libxi** and **glu** as dependencies.

**Comment by larsbergstrom** [comment]
We no longer use GLFW in Servo. Please re-open an issue (or a PR with fixes to the readme!) if the new toolchain does not work on your Arch Linux installation with the provided instructions.
