### ISSUE TITLE
Jiggly list items on wikipedia

### ISSUE THREAD

**Issue by jdm** [servo/servo#4395]
`./mach run http://en.wikipedia.org`

Watch the list items jiggle around ceaselessly. I suspect incorrect style sharing is occurring. cc @pcwalton

**Comment by frewsxcv** [comment]
Upon loading `en.wikipedia.org`, text is not jiggly for me, but if I move the mouse, certain sections jiggle. So I guess this issue is still valid ¯\_(ツ)_/¯

**Comment by frewsxcv** [comment]
GIF displaying jiggly text in wikipedia (as per my previous comment)

![](https://cloud.githubusercontent.com/assets/416575/7900324/58ab57d0-071d-11e5-9a84-364bc720f5b4.gif)

**Comment by atouchet** [comment]
Is this still an issue? I am not able to reproduce the behaviour in @frewsxcv's post in the latest nightly build.

**Comment by jdm** [comment]
Nope!
