### ISSUE TITLE
Implement Worker.terminate

### ISSUE THREAD

**Issue by jdm** [servo/servo#4427]
Spec: https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-worker-interface:dom-worker-terminate
Tests: workers/Worker_terminate_event_queue.htm, workers/constructors/Worker/terminate.html 
Code: components/script/dom/worker.rs

**Comment by jwilm** [comment]
@jdm I'll sign up for this one. I tried running the tests for this, but the test comes back as skipped. Any suggestions?

```
./mach test-wpt tests/wpt/web-platform-tests/workers/Worker_terminate_event_queue.htm
```

**Comment by jwilm** [comment]
It looks like there's an .ini for each test suite - can now run test.

**Comment by jdm** [comment]
Yep, I was just about to paste the link :)

**Comment by jwilm** [comment]
The real trick is getting that test to stop running!

**Comment by jwilm** [comment]
The spec talks about setting a closing flag on `WorkerGlobalScope` for the terminating worker. Aside from not having such a flag, all the references in both `DedicatedWorkerGlobalScope` and `Worker` are immutable. I considered adding another `ScriptMsg` to notify of termination, but that only lets the worker/script task channel close. It does not prevent additional messages from being posted from the script task - again a limitation of immutability.

@jdm any guidance on this? Also trying to reconcile differences from the worker spec.

Thanks!

**Comment by jwilm** [comment]
Must have glanced over this the first read through the script component docs..

> In particular, any mutable fields use Cell or DOMRefCell to manage their mutability.

I think I have a path forward with that.

**Comment by Ms2ger** [comment]
See https://github.com/servo/servo/pull/6652 for an unfinished attempt to fix this.

**Comment by KiChjang** [comment]
I'm assigning this to myself so that we don't forget about it.
