### ISSUE TITLE
The result of CreateProxyHandler is leaked

### ISSUE THREAD

**Issue by jdm** [servo/servo#443]
This equates to one leaked object per DOM element type that uses a proxy, I believe. We'll need some global teardown at program termination if we want to silence Valgrind about this.

**Comment by KiChjang** [comment]
@jdm does this still occur?

**Comment by jdm** [comment]
Yes.

**Comment by nox** [comment]
@jdm Still? :)

**Comment by jdm** [comment]
Yes.

**Comment by rhetenor** [comment]
While browsing issues, this seems related to our recently merged pull requests https://github.com/servo/servo/pull/32773 and leaksanitizer does not report this anymore. So this might be closed?

**Comment by jdm** [comment]
Agreed!
