### ISSUE TITLE
Implement CSSStyleDeclaration.getPropertyPriority

### ISSUE THREAD

**Issue by jdm** [servo/servo#4432]
Spec: http://dev.w3.org/csswg/cssom/#dom-cssstyledeclaration-getpropertypriority
Code: components/script/dom/cssstyledeclaration.rs, components/script/dom/webidls/CSSStyleDeclaration.webidl

Look to the existing getProperty method for inspiration. We just want to determine if the matching property is in the important or normal list.

No tests until #4085 merges.

**Comment by dmarcos** [comment]
I'm just looking for an easy bug for my first servo patch and I've seen a few issues still opened with a merged PR. @jdm Should we close this one?

**Comment by jdm** [comment]
Yep, thanks!
