### ISSUE TITLE
Remove (parts of) FlowRef

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4445]
``` rust
/// Reference-counted pointers to flows.
///
/// Eventually, with dynamically sized types in Rust, much of this code will be superfluous.
```

@pcwalton knows more.

**Comment by saneyuki** [comment]
I'll take this.

@pcwalton please account for the details?

**Comment by pcwalton** [comment]
Sadly we can't do this yet. Rust doesn't have the dynamically sized type support we need.

**Comment by notriddle** [comment]
This issue can be closed now,right?
