### ISSUE TITLE
Support all CSS units

### ISSUE THREAD

**Issue by brson** [servo/servo#445]
I think we only really us px at the moment. Make pt, em and other units work correctly everywhere.
- Distance Units: the ‘&lt;length>’ type
  - Relative lengths
    - Font-relative lengths:
      - [x] `em`
      - [x] `ex` (as 0.5em)
      - [x] `ch` (as 0.5em)
      - [x] `rem`
    - Viewport-percentage lengths:
      - [x] `vw`
      - [x] `vh`
      - [x] `vmin`
      - [x] `vmax`
  - Absolute lengths:
    - [x] `cm`
    - [x] `mm`
    - [x] `in`
    - [x] `pt`
    - [x] `pc`
    - [x] `px`
- Other Units
  - Angles: the ‘&lt;angle>’ type and:
    - [x] `deg`
    - [x] `grad`
    - [x] `rad`
    - [x] `turn`
  - Times: the ‘&lt;time>’ type and:
    - [x] `s`
    - [x] `ms`
  - Frequencies: the ‘&lt;frequency>’ type and:
    - [ ] `Hz`
    - [ ] `kHz`
  - Resolutions: the &lt;resolution> type and:
    - [ ] `dpi`
    - [ ] `dpcm`
    - [ ] `dppx`

**Comment by nox** [comment]
@SimonSapin Can this be closed?

**Comment by SimonSapin** [comment]
Yes.
