### ISSUE TITLE
Add support for img's natural{Width,Height}

### ISSUE THREAD

**Issue by brunoabinader** [servo/servo#4468]
Spec:
https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-naturalwidth

Relevant Tests:
html/semantics/embedded-content/the-img-element/current-pixel-density/basic.html

**Comment by jdm** [comment]
Any news, @liamzdenek?

**Comment by mschroeder** [comment]
Please, can you assign me this issue?

**Comment by jdm** [comment]
There was someone on IRC who was looking into this today, so I'm hesitant to hand it off right now.

**Comment by jdm** [comment]
@mschroeder I haven't heard anything further, so you would be welcome to tackle this if you're still interested.

**Comment by mschroeder** [comment]
@jdm I'm still interested, so please assign it to me.

**Comment by mschroeder** [comment]
@jdm To return the naturalWidth/naturalHeight, I need to calculate the density-corrected intrinsic width and height, which needs the hidpi_factor from the window or compositor in HTMLImageElement. Can you give me a hint for the best approach to get the hidpi_factor in the HTMLImageElement? Maybe this is not necessary at all.

**Comment by jdm** [comment]
@mschroeder Good point. That's something we could send as part of the WindowSizeData structure, I expect (http://mxr.mozilla.org/servo/source/components/msg/constellation_msg.rs#43), and store that in the image's owning Window object.

**Comment by jdm** [comment]
In fact, that structure already contains a device_pixel_ratio field, so it should be even less work than I anticipated.

**Comment by jdm** [comment]
Fixed by #5767.
