### ISSUE TITLE
Design data structures to support streaming content in display list

### ISSUE THREAD

**Issue by brson** [servo/servo#448]
At the moment images in the display list are represented as something like `Option<ARC<~Image>>`. This is an immutable type that implies that an image must be completely loaded by the time layout generates the display list. This has some big limitations:
- There is no opportunity to decode images in parallel during the time between layout and rendering.
- There is no way to support progressive loading of images.
- This sort of solution can't work for streaming media like video

The way media is represented in the display list needs to be redesigned.

**Comment by nox** [comment]
@nical Ain't that not true anymore?

**Comment by nical** [comment]
These days the image display items refer to an `ImageKey` which is just an Id. There needs to be at least a placeholder image available to webrender by the time the display list is submitted, but the image can then be updated with new content (and new size if need be). I think that servo now does decode images in parallel but I could be wrong. For the media use case there is another system called "external image" that lets the renderer borrow access to image data that isn't owned by webrender (and isn't necessarily mapped on CPU memory) to avoid copies and select the video frame with the best timestamp at the last moment.
I think this issue can be closed now.

**Comment by nox** [comment]
Closing is good. Thanks for the quick reply @nical.
