### ISSUE TITLE
Implement WebSocket support

### ISSUE THREAD

**Issue by jdm** [servo/servo#4492]
There are some PRs that begin to attempt this, but I also just came across https://github.com/cyderize/rust-websocket which also relies on hyper.

**Comment by boghison** [comment]
Can I take this? I love this library and would like to work a bit on servo :)

**Comment by jdm** [comment]
There's a student group from NCSU working on this as a project this term; I think the status of the work remaining will be clear by the end of May.

**Comment by boghison** [comment]
I won't work on it then

**Comment by Ms2ger** [comment]
The basics work now.
