### ISSUE TITLE
Convert WorkerPostMessage into a Runnable object

### ISSUE THREAD

**Issue by jdm** [servo/servo#4497]
In the same way that https://github.com/servo/servo/commit/271aa277e90ffeb1e060a2aac6f05429ded55c38 converted a ScriptMsg variant for XMLHttpRequest progress notifications into a Runnable, we should convert the WorkerPostMessage variant.

Code: components/script/script_task.rs, components/script/dom/dedicatedworkerglobalscope.rs

The changes can be tested by running `./mach test tests/wpt/web-platform-tests/workers --processes=4` and `./mach test tests/wpt/web-platform-tests/XMLHttpRequest --processes=4`.

**Comment by catchmrbharath** [comment]
This has been fixed in #4533. The issue can be closed
