### ISSUE TITLE
Extend Runnables to allow for external state

### ISSUE THREAD

**Issue by jdm** [servo/servo#4500]
There are a number of ScriptMsg variants that could theoretically become Runnables, except that they rely upon state present in the executing ScriptTask or WorkerGlobalScope. Some of these could be resolved by creating separate Runnable and WorkerRunnable traits that provide the necessary state as arguments to the `handler` method (such as `&ScriptTask` and `JSRef<WorkerGlobalScope>`), but other (such as `FireTimer`) should be shared between both kinds of event loops. We need a solution that minimizes duplication.

**Comment by jdm** [comment]
```
<jdm> in the future we'll probably split the Runnable type into MainThreadRunnable, WorkerRunnable, and CommonRunnable
<jga> jdm: and hand the ScriptTask struct to the runners?
<jdm> for the main thread ones, yes
<jdm> workers would get the DedicatedWorkerGlobal, and the common ones get nothing
```

cc @snf

**Comment by snf** [comment]
#5360

**Comment by nox** [comment]
I went the complete opposite way with my recent changes.
