### ISSUE TITLE
Use NonZero in our smart pointers.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4502]
See <https://github.com/rust-lang/rust/pull/19765>. This should be able to drop our DOM memory footprint by quite a bit.

Depends on a rust upgrade past today.

**Comment by KiChjang** [comment]
I think I can try this one. I will need to know what you mean by smart pointers though, do you mean boxed pointers or simple references (&)? I could try this one source file at a time first.

**Comment by Ms2ger** [comment]
You can't; we're still on an early-November rust snapshot.
