### ISSUE TITLE
"called `Result::unwrap()` on an `Err` value: ()" in `font_context::FontContext::create_layout_font`

### ISSUE THREAD

**Issue by Swatinem** [servo/servo#4503]
Simply running `mach run https://github.com/` crashes my servo like so:

```
task 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: ()'
[…]
   7:     0x7f5d8143dd50 - result::Result<T, E>::unwrap::h7782367496213046714
   8:     0x7f5d8143da10 - font_context::FontContext::create_layout_font::h915aa1b5df088897o4d
   9:     0x7f5d8143f4d0 - font_context::FontContext::get_layout_font_group_for_style::hf6eb9a02541ec932x5d
  10:     0x7f5d809f8640 - text::TextRunScanner::flush_clump_to_list::h52ad07a8eaf50336PPq
  11:     0x7f5d808795f0 - text::TextRunScanner::scan_for_runs::h5f2c7fe8318300b1mLq
[…]
```

The offending line seems to be this: https://github.com/servo/servo/blob/master/components/gfx/font_context.rs#L108

Since I’m on linux, I suspect one of these are the source:
https://github.com/servo/servo/blob/master/components/gfx/platform/freetype/font.rs#L106
https://github.com/servo/servo/blob/master/components/gfx/platform/freetype/font.rs#L112

I’m on arch with infinality, so the relevant library versions are these:
* fontconfig-infinality-ultimate 2.11.1-24
* freetype2-infinality-ultimate 2.5.4-2

Please tell me how I can further diagnose this problem.

**Comment by jdm** [comment]
I'm seeing this on OS X on github's home page now.

**Comment by Swatinem** [comment]
Haven’t seen this in quite some time, closing WFM.
