### ISSUE TITLE
Load errors for worker resources should dispatch an error event at the worker

### ISSUE THREAD

**Issue by jdm** [servo/servo#4511]
According to https://html.spec.whatwg.org/multipage/workers.html#processing-model-11:
```
Attempt to fetch the resource identified by url, from the origin specified by settings object, using parent referrer source as the referrer source (not using the referrer source specified by settings object!), and with the blocking flag set and the force same-origin flag set.

If the attempt fails, then for each Worker or SharedWorker object associated with worker global scope, queue a task to fire a simple event named error at that object. Abort these steps.
```

This should be a Runnable object containing a TrustedWorkerAddress field.

**Comment by KiChjang** [comment]
Found the relevant code under `DedicatedWorkerGlobalScope::run_worker_scope`. The entire URL fetching functionality is handled by `net::resource_task::load_whole_resource`.

I can try handling this.
