### ISSUE TITLE
servo panics on loading cat-v.org

### ISSUE THREAD

**Issue by suhr** [servo/servo#4531]
task 'LayoutTask' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/larsberg/rust/src/libcore/result.rs:789

Crash report: https://gist.github.com/suhr/05cb73379f1bd9eab2a6

**Comment by jdm** [comment]
Same symptom as #4503. What operating system are you using?

**Comment by suhr** [comment]
``` 
% uname -a
Linux localhost 3.18.1-gentoo #2 SMP PREEMPT Thu Dec 25 05:02:57 MSK 2014 x86_64 AMD Athlon(tm) 64 X2 Dual Core Processor 5000+ AuthenticAMD GNU/Linux
```

**Comment by frewsxcv** [comment]
`cat-v.org` also panics for me https://gist.github.com/frewsxcv/273cd7cf0e2e7c0a79b5 I am on OSX 10.10, so it might not be only a linux issue

**Comment by jdm** [comment]
That's a different panic than the one described above.

**Comment by suhr** [comment]
Can't reproduce anymore.
