### ISSUE TITLE
Implement form submission for button elements

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4534]
We need to implement `Activatable` for `HTMLButtonElement`, something similar to [the way it's done for `<input>`](https://github.com/servo/servo/blob/master/components/script/dom/htmlinputelement.rs#L602) except only for `<button type=submit>`

You'll also need to provide an implementation of `FormControl` (similar to [the one for `<input>`](https://github.com/servo/servo/blob/master/components/script/dom/htmlinputelement.rs#L573)).

Spec: https://html.spec.whatwg.org/multipage/forms.html#the-button-element:activation-behavior

**Comment by yodalee** [comment]
Allow me handle this.

**Comment by jdm** [comment]
Go for it!

**Comment by yodalee** [comment]
To make sure I didn't think it wrong, let me write my thought here:
I need to add `impl<'a> Activatable for JSRef<'a, HTMLButtonElement>

**Comment by Manishearth** [comment]
Yep, as well as `FormControl`

The "canceled activation steps" and "pre-click activation steps" should probably be empty (unless the spec says something)


(Btw, feel free to ping me in IRC or here, I'm willing to mentor this bug)

**Comment by yodalee** [comment]
Are there tests for this feature, or tests for `InputElement` so I can modify them to `ButtonElement`

**Comment by Manishearth** [comment]
Well, the form submission tests in `tests/html` let you test some of this manually. The rest of the test must be buried somewhere in wpt.
