### ISSUE TITLE
D-Bus interface for navigation control and more

### ISSUE THREAD

**Issue by l0kod** [servo/servo#4559]
As the Servo GUI toolbar control is not there yet, it would be interesting to be able to control the browsing commands from a D-Bus client. This way, splitting GUI from user control, we will be able to easily extend the browser with external tools, shortcuts… I guess a control API is needed anyway for the Android and iOS version.

A more advanced interface would allow to simulate user inputs which is really convenient for (headless) testing (cf. [Selenium](http://seleniumhq.org/) or [PhantomJS](http://phantomjs.org/)).

cc #3982

**Comment by l0kod** [comment]
cc #3778

**Comment by metajack** [comment]
Is there a specific advantage to D-Bus on Linux? I think we are planning to have some control protocol, but I think we've been thinking it would be based on simple serialization of normal Rust messages.

**Comment by jdm** [comment]
There's definitely interest in exposing the ability to remotely control Servo via the WebDriver protocol.

**Comment by l0kod** [comment]
D-Bus is becoming the Linux IPC (especially with kdbus). It is great for interoperability across applications.

The Servo CLI does not need to be burdened with all browsing commands (e.g. open, open in a new window, open in a new tab, open in this browser specific window/profile, refresh this tab…) but can delegate to a D-Bus interface.

For testing purpose the WebDriver protocol is clearly a win but it may miss some browser-specific controls (e.g. browser instance/window/profile management…).

**Comment by saneyuki** [comment]
> For testing purpose the WebDriver protocol is clearly a win but it may miss some browser-specific controls (e.g. browser instance/window/profile management…).

I seem that to implement the extended/browser-specified protocol set over the WebDriver protocol will solve.

**Comment by l0kod** [comment]
It would also probably be useful to be able to control your favorite music streaming website like a real media desktop application. A browser high-level control could add commands like play, pause, mute, next…
So it could means more integration for web applications with the desktop.

**Comment by l0kod** [comment]
Well, more generally, D-Bus interfaces could be used to control and get notifications from some Servo's components (browsing, extensions…).

Maybe the WebDriver protocol could be used/connected through a D-Bus service like an extension could as well? This would avoid the TCP/IP listening server and use a much proper/secure link layer (for a local service). I have no idea if a WebDriver using D-Bus is possible but this will at least fix the [TCP port exhaustion](https://code.google.com/p/selenium/issues/detail?id=710).

**Comment by mrobinson** [comment]
I think this unlikely to happen in Servo itself. I could see this being part of an application that embeds Servo. We now have a GUI (Minibrowser) as well as webdriver support.
