### ISSUE TITLE
Stop using JS<T> in layout.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4571]
Create a `LayoutJS<T>` (or whatever) and use it where we now use `JS<T>` under `components/layout`. The `Layout*Helpers` traits should also be implemented on those instead.

**Comment by jdm** [comment]
Additionally, we'll want a to_layout method on `JS<T>` which can be called by the methods in `Layout*Helpers` traits.

**Comment by saneyuki** [comment]
I'm working on.

This change just intends to prevent to call `Layout*Helpers` methods from non `layout` crate, doesn't it?

**Comment by Ms2ger** [comment]
That's definitely one of the advantages.
