### ISSUE TITLE
Interface members for global objects should reside on the object, not the interface prototype

### ISSUE THREAD

**Issue by jdm** [servo/servo#4593]
According to the second item in http://heycam.github.io/webidl/#Global, we're doing this wrong right now.

**Comment by nox** [comment]
Blocked by #8954.

**Comment by nox** [comment]
#8954 fixed this.

**Comment by jdm** [comment]
This was not fixed.

**Comment by jdm** [comment]
According to https://github.com/servo/servo/issues/12979#issuecomment-241959407 this is hurting our performance, too!

**Comment by nox** [comment]
Oh, looking.
