### ISSUE TITLE
Parse the sandbox attribute on iframe elements.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4601]
Right now, if you use `setAttribute("sandbox", "...")`, the `iframe` won't be sandboxed because we don't implement `parse_plain_attribute`.

**Comment by sodhi95** [comment]
I'd like to take a shot at this

**Comment by sodhi95** [comment]
Continuing from the irc discussion to add a parse_plain_attribute function, how should I figure out where all must this function be called in htmliframeelement.rs
Can someone help me understand the flow of code here :)

**Comment by jdm** [comment]
@sodhi95 parse_plain_attribute gets called automatically by Element::parse_attribute (http://mxr.mozilla.org/servo/source/components/script/dom/element.rs#694) if is implemented by a derived type (and that type is present in the list at http://mxr.mozilla.org/servo/source/components/script/dom/virtualmethods.rs#144. It's like a C++ virtual function in this case. Does that answer your question?
