### ISSUE TITLE
getElementsByClassName should be case-insensitive in quirks mode.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4604]
Blocks #2185.

* Spec: <https://dom.spec.whatwg.org/#concept-getelementsbyclassname>.
* Code: `components/script/dom/htmlcollection.rs`.
* Test: `dom/nodes/getElementsByClassName-14.htm`.

**Comment by Ms2ger** [comment]
Since someone noted on IRC yesterday that `./mach test-wpt tests/wpt/web-platform-tests/dom/nodes/getElementsByClassName-14.htm` passes: that's because we have annotations of which tests are expected to fail under `tests/wpt/meta`; the goal is to be able to drop the failure expectation.

**Comment by brunoabinader** [comment]
I'm investigating this. Issue lies on ```HTMLCollection::by_class_name``` not using ```quirks_mode``` information provided by ```Document```.
