### ISSUE TITLE
Implement the stringifier on URLUtils (Location).

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4605]
Before #1986 lands, we might wish to use `DOMString toString();` instead.

Blocks #2185, #2968.

* Spec: <https://url.spec.whatwg.org/#urlutils>.
* Code: `components/script/dom/location.rs`.
* Test: `dom/nodes/Node-properties.html`, `html/browsers/history/the-location-interface/location-stringifier.html`.

**Comment by dmarcos** [comment]
@jdm Do we have to close this one too?

**Comment by jdm** [comment]
No, since @chmanchester never made a PR for that.

**Comment by srlakhe** [comment]
@jdm 
Hi,

I would like to get started on contributing to servo and would like to work on this bug as my first bug. 
How should I proceed forward?

Thanks
shreyas

**Comment by jdm** [comment]
Sorry @srlakhe, @chmanchester has already submitted a PR to solve this issue.
