### ISSUE TITLE
Stick to Windows-friendly filenames

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#4627]
e.g. The question mark in [`hello_a?foo#bar.html`](https://github.com/servo/servo/blob/master/tests/ref/hello_a%3Ffoo%23bar.html) is reported to cause problems.  We also had issues with `aux.rs` in the past.

We should figure out the exact rules, then enforce them in `tidy.py`.

**Comment by jdm** [comment]
Hmm. The question mark is useful because it allows for an automated test using a query string. Maybe we just need a test harness annotation instead.

**Comment by Dexterp37** [comment]
This makes git clone on Windows report the following error when checking out:

*error: Invalid path 'tests/ref/hello_a?foo#bar.html'*

The following article talks about allowed characters in Windows paths: [link](https://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29).

To recap:

* < > : " / \ | ? *
* Integer value zero, sometimes referred to as the ASCII NUL character.
* Characters whose integer representations are 1-31 (less than ASCII space)
* Any other character that the target file system does not allow (leading and trailing periods or spaces)
* Any of the DOS names: CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9 (and avoid AUX.txt, etc)
* The file name is all periods

Fixing this will also fix issue #3911.

**Comment by jdm** [comment]
I guess we should just take the "#bar" out of the filename and update the entry in basic.lit to match.

**Comment by Dexterp37** [comment]
Well, the whole "?foo#bar.html" needs to be taken out because of the question mark.

**Comment by jdm** [comment]
Ah right. I guess we don't get to have an automated test for #3340 :(

**Comment by Manishearth** [comment]
We can have mach create the file based on your OS :)

**Comment by Manishearth** [comment]
Wait, we'd still need special harness code to make that work. Hmm.

**Comment by Dexterp37** [comment]
I just noticed "%" is allowed on Windows. If that's possible on other platforms as well, maybe we could encode special characters like done with the URLs? Like %3F for "?"?

**Comment by Manishearth** [comment]
But the test is explicitly for testing the opening of a file with a ? in its name :)

**Comment by Dexterp37** [comment]
Ouch! Then I guess conditionally creating it depending on the OS is the best bet :)

**Comment by SimonSapin** [comment]
Though it’s not great, I’d say it’s acceptable to remove `?` and name the file `hello_a#foo.html` or something, as long as it includes `#`. Both `?` and `#` are special in URLs, and this tests is about testing that a command line argument is *not* treated as an URL if it looks relative. So it’s unlikely we’d have this bug for one of the two characters but not both.

**Comment by frewsxcv** [comment]
I don't know how the  `basic.list` parsing works, but what about creating a way to have only certain tests run on unix or windows?

**Comment by Manishearth** [comment]
You could perhaps filter filenames for `nowindows`, but it still makes the repo uncloneable (? not sure)

**Comment by akavel** [comment]
Sorry, didn't explore thoroughly and don't know the test harness, but @Manishearth do you mean it would be hard to generate the file for a test only on `nowindows` OS? Could you possibly give some hints for a noob what work it could require and how to try starting to do it?

**Comment by jdm** [comment]
Fixed by #7610.
