### ISSUE TITLE
Reddit subscribe button becomes separate [sub][scribe] buttons

### ISSUE THREAD

**Issue by jdm** [servo/servo#4645]
As seen in [this screenshot](https://i.imgur.com/ybgUQIr.png).

**Comment by renato-zannon** [comment]
FYI, this was taken on Linux x86_64, on servo commit e7d79842a85dfa8eaee8c2f441977edbf061bbed

**Comment by atouchet** [comment]
Are you still seeing this issue? I am unable to reproduce.

**Comment by jdm** [comment]
I do not.
