### ISSUE TITLE
Give the user control

### ISSUE THREAD

**Issue by maxwell5** [servo/servo#4653]
How about a browser that, for once, empowers their users?
Per-site/per-domain/per-path settings for security and privacy; a UI that doesn't treat users like idiots by hiding everything; total control over JS execution environment and rendered page contents; choose what plugins you want to run on which pages, and what they can do.

**Comment by jdm** [comment]
Could you take topics like this to the [mailing list](https://www.mozilla.org/en-US/about/forums/#dev-servo), or file individual issues about particular implementation ideas? It will be easier to respond to your suggestions in those venues.
