### ISSUE TITLE
Border renders incorrectly on `<code>` tag with escape characters

### ISSUE THREAD

**Issue by blucoat** [servo/servo#4658]
Code I used to test:
```html
<html>
<head>
<style>
code {
	border-radius:3px;
	border: 1px solid #ccc;
}
</style>
</head>
<body>
<code>
I like green eggs &amp; ham.
</code>
</body>
</html>
```

This is the output:
![2015-01-18-214947_1440x900_scrot](https://cloud.githubusercontent.com/assets/5714640/5795407/763b334c-9f5d-11e4-9dac-6c4212621f12.png)

The same problem happens with other escape codes, and if you replace `<code>` with an invalid tag, like `<dummy>`.

**Comment by bjwbell** [comment]
Borders for `display: inline` elements don't correctly render across multiple text nodes. Which is why the bug appears when using the `<code>` element. The `<code>` element by default is `display:inline`.

You verify the same bug with `<div>` elements by setting their style to `display:inline`.
