### ISSUE TITLE
Intermittent crash in test_img_width_height.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#4659]
```
---- /Users/servo/buildbot/slave/mac2/build/tests/content/test_img_width_height.html stdout ----
	ALERT: TEST-PASS | 500 === 500: 
ALERT: TEST-PASS | 378 === 378: 
ALERT: TEST-PASS | 200 === 200: 
ALERT: TEST-PASS | 100 === 100: 
task '/Users/servo/buildbot/slave/mac2/build/tests/content/test_img_width_height.html' panicked at 'Servo exited with non-zero status Ok(signal: 4)', ../../tests/contenttest.rs:138
```

**Comment by chotchki** [comment]
Works fine for me on OSX

test /Users/chotchki/servo-mine/tests/content/test_node_insertBefore.html ... ok
test /Users/chotchki/servo-mine/tests/content/test_node_cloneNode.html ... ok
test /Users/chotchki/servo-mine/tests/content/test_img_width_height.html ... ok
test /Users/chotchki/servo-mine/tests/content/test_node_replaceChild.html ... ok
test /Users/chotchki/servo-mine/tests/content/test_node_isEqualNode.html ... ok

**Comment by nox** [comment]
There is no test_img_width_height.html in the tree anymore.
