### ISSUE TITLE
When mach updates cargo or rust, it should also clean the tree

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#4663]
If either Cargo or Rust are updated, either due to a `bootstrap-*` command or because the hash or nightly date have changed, mach should also clean the tree.

Cargo does not understand when its own or the compiler version has changed between execution runs, and has a large number of issues with left-over build outputs from mixed toolchain versions.

**Comment by SimonSapin** [comment]
I *believe* Cargo is supposed to do this already. Shouldn’t we file Cargo bugs rather than patch on top of it?

**Comment by metajack** [comment]
@SimonSapin is correct I think. I suspect we will need more info in order to figure out what's happening and ask @alexcrichton about it.

**Comment by Ms2ger** [comment]
I haven't had issues with this; reopen if someone hits it?

**Comment by SimonSapin** [comment]
I suspect @larsbergstrom was hitting Cargo bugs that may have been fixed since.
