### ISSUE TITLE
Throw as necessary when setting XHR.withCredentials.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4665]
Blocks #2525.

* Spec: <https://xhr.spec.whatwg.org/#dom-xmlhttprequest-withcredentials>.
* Code: `components/script/dom/xmlhttprequest.rs`.
* Test: `XMLHttpRequest/XMLHttpRequest-withCredentials.html`, `XMLHttpRequest/XMLHttpRequest-withCredentials.worker`.

**Comment by Manishearth** [comment]
Note: We don't support fetch credentials yet (though I will be putting them in as I write fetch)

**Comment by KiChjang** [comment]
This looks easy enough, I think I'll have a go at it, but do I need to wait for the fetch credentials functionality to be implemented first?

**Comment by Manishearth** [comment]
Nah, we just want to throw the error here

**Comment by KiChjang** [comment]
I just noticed that ther are someother methods in the class (e.g. setTimeout) that does not have an appropriate checking mechanism for the JS global environment.

I think I shouldn't change those, but I just want to know whether there actually is an appropriate method to check whether the current environment is document or not.

**Comment by Manishearth** [comment]
Check if the global is a Window or Worker object, maybe?

**Comment by KiChjang** [comment]
Yes, that sounds good. I just want to make sure that checking whether the global is a Window is equivalent to checking whether the global is a document.
