### ISSUE TITLE
Notify devtools about new worker globals

### ISSUE THREAD

**Issue by jdm** [servo/servo#4704]
This would be marked as easy, except I have no idea how to identify workers in the devtools task. I need to check out how this is done in Firefox for inspiration.

**Comment by jdm** [comment]
To clarify, non-worker globals are identified by their PipelineId. There's no such mechanism for workers at the moment.

**Comment by jdm** [comment]
Maybe we can have a WorkerId and pass around `(PipelineId, Option<WorkerId>)` in the places where it matters.

**Comment by thiagopnts** [comment]
I'll start to dig into this.

**Comment by jdm** [comment]
Great!

**Comment by thiagopnts** [comment]
By non-worker globals, you mean the ones passed by script_task's `load` method in `DevtoolsControlMsg::NewGlobal` message?

**Comment by jdm** [comment]
Correct. Those are all globals that come from top-level page loads or iframe loads.

**Comment by thiagopnts** [comment]
I did some work on this https://github.com/thiagopnts/servo/commit/4f3f9176f6ac2a4f5b6d2a877fb43093a8fce558
A couple questions came up: Should I just pass the workerIds to the devtools actors? Currently I'm just generating the worker id on worker constructor but I'm not associating it with anything because I don't know how it will be used. Any thoughts?

**Comment by jdm** [comment]
I think the NewGlobal message can take a PipelineId and an optional WorkerId. This will be enough to differentiate workers from different script globals. Does that answer your question? We'll probably need to create a WorkerActor type and have a hashtable from `(PipelineId, WorkerId)` to actor names in the devtools crate as well.

**Comment by thiagopnts** [comment]
Got it, the WorkerActor was the missing piece :)
I should send a PR with this soon.
