### ISSUE TITLE
Make FooCast methods not require so many type annotations.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4724]
Something in #4719 made us require even more type annotations than before. This seems like it should be solvable.

**Comment by jdm** [comment]
It has to do with returning Self; the rules related to that got stricter. I think if we transition to using associated types instead we can make it much better.

**Comment by Ms2ger** [comment]
Fixed by 0e11178d663c44baaf5bde9b9470ad6ac142d5a7.
