### ISSUE TITLE
Implement DumpRenderTree-like in servo

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#4731]
WebKit/Blink both allow developers to dump the page RenderTree formatted as text using a console. Generally, while debugging rendering/layout bugs, this the first step to be done (i.e. inspect the elements in the render tree).

Speaking with pcwalton, DisplayList should have some code to dump its contents and it should be a matter of having a new CLI option passed to servo to print the tree to console.

This bug is to track implementing this feature.

**Comment by metajack** [comment]
Just to be clear, you want a display list dumper, not a flow tree dumper? The latter we already have, but that is what corresponds to Gecko's frame tree and WebKit's render tree as I recall.

**Comment by Adenilson** [comment]
@pcwalton: besides DisplayList::all_display_items() any other noteworthy method?

**Comment by Adenilson** [comment]
@metajack: yep!

**Comment by Adenilson** [comment]
Ok, first step was done on: https://github.com/servo/servo/pull/5062

What is missing now would be more information (e.g. geometry, etc).

**Comment by Adenilson** [comment]
The missing step is implemented on #5209.

**Comment by Adenilson** [comment]
As #5209 has landed (and considering that -Z dump-flow-tree is implemented), I think we can close this issue.
