### ISSUE TITLE
Incorrectly positioned text in a transparent div

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#4733]
Basically, if I set the CSS opacity property in a div (that has a span inside and an anonymous text), it will fail to render the text in the correct position after the span content.

**Comment by Adenilson** [comment]
Test case: https://gist.github.com/Adenilson/2f7d9e4c26fdde930449

**Comment by Adenilson** [comment]
Since dumping the FlowTree has landed (https://github.com/servo/servo/pull/4995), I was able to inspect the flow tree of a test case that fails X one that works.

a) Incorrectly positioned text element (div has opacity set) FlowTree:
+ Block - 12142fc80: frag=(10 SpecificFragmentInfo::Generic bp
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px) m
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px))
(@ LogicalRect(H LTR, i800px×b608px, @ (i0px,b0px)), CC 1, ADC 0) |

+ Block - 12142fa00: frag=(5 SpecificFragmentInfo::Generic bp
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px) m
LogicalMargin(H LTR, inline: 8px..8px block: 8px..8px))
(@ LogicalRect(H LTR, i800px×b202px, @ (i0px,b8px)), CC 1, ADC 0) | |

+ Block - 12142f280: frag=(3 SpecificFragmentInfo::Generic bp
LogicalMargin(H LTR, inline: 1px..1px block: 1px..1px) m
LogicalMargin(H LTR, inline: 5px..627px block: 5px..5px))
(@ LogicalRect(H LTR, i784px×b202px, @ (i8px,b0px)), CC 1, ADC 0) | | |

+ Inline - 12143b1c0 - [(1 SpecificFragmentInfo::ScannedText bp
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px) m
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px)),
(0 SpecificFragmentInfo::ScannedText bp
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px) m
LogicalMargin(H LTR, inline: 5px..5px block: 5px..5px))]

b) Same thing without opacity:
+ Block - 11b02fc80: frag=(10 SpecificFragmentInfo::Generic bp
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px) m
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px))
(@ LogicalRect(H LTR, i800px×b608px, @ (i0px,b0px)), CC 1, ADC 0) |

+ Block - 11b02fa00: frag=(5 SpecificFragmentInfo::Generic bp
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px) m
LogicalMargin(H LTR, inline: 8px..8px block: 8px..8px))
(@ LogicalRect(H LTR, i800px×b202px, @ (i0px,b8px)), CC 1, ADC 0) | |

+ Block - 11b02f280: frag=(3 SpecificFragmentInfo::Generic bp
LogicalMargin(H LTR, inline: 1px..1px block: 1px..1px) m
LogicalMargin(H LTR, inline: 5px..627px block: 5px..5px))
(@ LogicalRect(H LTR, i784px×b202px, @ (i8px,b0px)), CC 1, ADC 0) | | |

+ Inline - 11b03b1c0 - [(1 SpecificFragmentInfo::ScannedText bp
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px) m
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px)),
(0 SpecificFragmentInfo::ScannedText bp
LogicalMargin(H LTR, inline: 0px..0px block: 0px..0px) m
LogicalMargin(H LTR, inline: 5px..5px block: 5px..5px))]


It seems that the flow tree (or at least what was dumped into the console) it is pretty much the same. That points to that the rendering issue would be at the display list creation.

**Comment by Adenilson** [comment]
Continuing digging, I was able to simplify the test case a bit (removing the span element). It can be seen here: http://codepen.io/Savago/pen/GgGyWY

 I tried the parameter that will verify if the display list is valid (i.e. --debug validate-display-list-geometry) and it will print this:

a.cavalcanti$ ./components/servo/target/servo --debug validate-display-list-geometry,dump-display-list file:///Users/a.cavalcanti/Desktop/servo/stackingContext/min-min-final.html

ERROR:layout::flow: DisplayList item SolidColor @ Rect(150px×200px at (0px,0px)) (11730a520) outside of Flow overflow (ClippingRegion { main: Rect(150px×200px at (0px,0px)), complex: [] })
ERROR:layout::flow: DisplayList item Text @ Rect(61.716667px×15.983333px at (0px,0px)) (11730a550) outside of Flow overflow (ClippingRegion { main: Rect(61.716667px×15.983333px at (0px,0px)), complex: [] })
#### start printing display list.
#### Children stacking contexts list length: 1
#### SolidColor.
#### TextClass.

So I'm planning to investigate display_list_builder.rs::build_display_list() and flow.rs::validate_display_list_geometry().

**Comment by Adenilson** [comment]
@SimonSapin and @pcwalton any suggestions?

**Comment by mrobinson** [comment]
@Adenilson I cannot seem to reproduce this issue any longer. Can you confirm that it is still an issue? It may have been fixed in the layerization rework from last year.

**Comment by Adenilson** [comment]
@mrobinson sure thing, let me try to build it.

**Comment by Adenilson** [comment]
Yep, it seems to be fixed (closing the issue).
