### ISSUE TITLE
XMLHttpRequest/send-accept.htm doesn't like the presence of a quality value in the header

### ISSUE THREAD

**Issue by jdm** [servo/servo#4734]
```
XMLHttpRequest: send() - Accept
-------------------------------
Expected PASS, got FAIL
assert_equals: expected "*/*" but got "*/*; q=1"
```
Hyper recently started requiring quality values; maybe we should just not print it out if it's 1? I need to read up on what these actually mean.

**Comment by jdm** [comment]
cc @seanmonstar

**Comment by seanmonstar** [comment]
:panda_face:

**Comment by seanmonstar** [comment]
@jdm for your reading enjoyment: https://tools.ietf.org/html/rfc7231#section-5.3.1

> If no "q" parameter is present, the default weight is 1.

Perhaps we should take that to mean print nothing in hyper...

**Comment by seanmonstar** [comment]
@jdm we've fixed this over on hyper.

**Comment by seanmonstar** [comment]
I assume fixed?

**Comment by jdm** [comment]
Yep!
