### ISSUE TITLE
mach doc is broken.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4742]
Looks like the docs no longer end up in `~/.servo/rust/`. CC @larsbergstrom

**Comment by frewsxcv** [comment]
The docs now get generated to a different location:

https://github.com/servo/servo/blob/1389be37823fccf4108f4e79d0a3a793f0bbe93e/python/servo/post_build_commands.py#L174

The `./mach doc` command works for me; I think this can be closed.
