### ISSUE TITLE
Audit send()/recv() calls.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4744]
We lost a lot of error handling in #4719. We should restore it.

**Comment by jdm** [comment]
Did we actually lose error handling? I thought we have a bunch of places that won't panic now since they're missing unwrap calls, whereas before they would panic automatically if the send/recv failed.

**Comment by Ms2ger** [comment]
Yes, that.

**Comment by xojoc** [comment]
So how should one proceed? Should we add `unwrap` to each call of `send` and `recv`, or there's something else to do? I would like to help, instructions are welcomed.

**Comment by jdm** [comment]
Yes, the places that warn about unused results when calling send or recv should have unwrap added to them to restore the previous behaviour.

**Comment by xojoc** [comment]
Ok, I'll do it.

**Comment by gereeter** [comment]
Should this be closed since #4820 landed?

**Comment by jdm** [comment]
Yep!
