### ISSUE TITLE
Audit int/uint usage.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4745]
Needs to be done manually; most should probably become sized integers.

**Comment by xojoc** [comment]
What to use for pixels: `usize` or `u16`?

**Comment by jdm** [comment]
Can you be more specific? :)

**Comment by xojoc** [comment]
Usually in games one uses `u16` integers when specifying a length in pixels.  I saw in `components/util/opts.rs`:
       /// The maximum size of each tile in pixels (`-s`).
       pub tile_size: uint,
so I was wondering if encountering other pixel lengths I should use `usize` or `u16`? (Sorry for not being clear in the first message.)

**Comment by jdm** [comment]
It makes the most sense to trace how the value is used. In this case, it appears to eventually be used as an argument to Layer::new from rust-layer, which still uses uint. I would keep it as usize for now.
