### ISSUE TITLE
Review get_jemalloc_stat memory management.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4749]
It's not clear to me if `je_mallctl` takes ownership of the string. If it doesn't, we leak.

**Comment by jdm** [comment]
je_mallctl does not appear to take ownership of it, from my reading of http://osxr.org/redis/source/deps/jemalloc/src/jemalloc.c#1335, http://osxr.org/redis/source/deps/jemalloc/src/ctl.c#0812, and http://osxr.org/redis/source/deps/jemalloc/src/ctl.c#0715.

**Comment by nox** [comment]
AFAIK we don't leak them anymore given we use a `CString` value on the stack and call `as_ptr` on them.
