### ISSUE TITLE
No rendering on Linux + NVidia after rustup 

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#4754]
Using CPU rasterization I get a series of glutin error messages:
```
[glutin] x error code=97 major=0 minor=0!
[glutin] x error code=98 major=0 minor=0!
[glutin] x error code=0 major=0 minor=0!
[glutin] x error code=99 major=0 minor=0!
[glutin] x error code=100 major=0 minor=0!
[glutin] x error code=101 major=0 minor=0!
[glutin] x error code=0 major=0 minor=0!
[glutin] x error code=102 major=0 minor=0!
[glutin] x error code=103 major=0 minor=0!
[glutin] x error code=104 major=0 minor=0!
[glutin] x error code=0 major=0 minor=0!
[glutin] x error code=105 major=0 minor=0!
```

Using GPU rasterization, there are no error messages, but I see blank white output.

**Comment by mrobinson** [comment]
@glennw Any idea?

**Comment by glennw** [comment]
No immediate ideas, but I will look into it today. Unfortunately I don't have any nvidia hardware here to test with.

**Comment by glennw** [comment]
@mrobinson Was the glutin build definitely working for you on nvidia hardware pre-rustup?

**Comment by glennw** [comment]
@mrobinson Are you using the proprietary driver or nouveau?

**Comment by mrobinson** [comment]
@glennw I can confirm that it's working for me at ff8cbff81016c157373c1675f3eee69dd70ae544. If you have any ideas for debugging this, I can try them locally. I did not notice any unusual errors in apitrace.

**Comment by mrobinson** [comment]
I'm using the proprietary driver.

**Comment by glennw** [comment]
@mrobinson OK, well that is a good thing at least (working pre-rustup) I'll take a look at the diffs soon and let you know of anything I can think of to try.

**Comment by glennw** [comment]
@mrobinson One thing you could do is clone glutin locally, comment out the call to XSetErrorHandler, and then paste the exact X error logs you get on the terminal into here?

**Comment by mrobinson** [comment]
Here is the X error:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  22 (X_GLXCreatePixmap)
  Serial number of failed request:  98
  Current serial number in output stream:  99
```
