### ISSUE TITLE
Click on disabled control should not trigger onclick event

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4765]
[tests/wpt/web-platform-tests/html/semantics/forms/attributes-common-to-form-controls/disabled-elements-01.html](https://github.com/w3c/web-platform-tests/blob/master/html/semantics/forms/attributes-common-to-form-controls/disabled-elements-01.html), among other things, calls `click()` and checks if onclick is e dispatched on that element -- it shouldn't, but we do dispatch it currently.

I believe this is due to our lack of graniness in determining if an element is "activatable", currently we just have a list of element types which are activatable. However, elements like `input` do not have activation behavior when [they are not mutable](https://html.spec.whatwg.org/multipage/forms.html#submit-button-state-%28type=submit%29:concept-fe-mutable-2). In their case the synthetic activation should be suppressed.

@Ms2ger, since you wrote that test, is this guess correct?

One way to fix this is to add a `is_currently_activatable()` method to `Activatable` and call it from the synthetic/authentic activation hooks when finding the nearest activatable element and activating it.

**Comment by Ms2ger** [comment]
<https://html.spec.whatwg.org/multipage/#dom-click> says:

1. If the element is a form control that is disabled, abort these steps.

**Comment by Manishearth** [comment]
Oh wow. Bah. Though I think we still need the grainier activation behavior.

**Comment by jdm** [comment]
We could probably fix this by calling `node.get_disabled_state` instead of `HTMLInputElement.Disabled` in https://github.com/servo/servo/blob/master/components/script/dom/htmlelement.rs#L127, but that's a bit counterintuitive.
