### ISSUE TITLE
Implement TextEncoder.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4768]
Spec: <https://encoding.spec.whatwg.org/#interface-textencoder>.

This includes enabling the relevant tests by adding
```ini
[encoding]
  skip: false
```
to `tests/wpt/include.ini`.

This may also include updating the `mozjs` and `rust-mozjs` dependencies to ensure we can work with typed arrays.

**Comment by yodalee** [comment]
Allow me try this if you permit. I'm afraid that I may take long time to complete.

**Comment by SimonSapin** [comment]
Go ahead!

This is mostly about plugging things together between JavaScript and Rust. The rust-encoding library, which we already use in Servo, implements the encodings themselves as well as the label lookup.

http://doc.servo.org/encoding/index.html

**Comment by yodalee** [comment]
There is a problem: the codegen python cannot recognize `USVString` in webidls, or should I leave the encode method comment out now?

**Comment by jdm** [comment]
Just use DOMString instead and leave a FIXME comment.

**Comment by yodalee** [comment]
I'm stuck at `Encoding` method, which should find encoding name by `utfLabel`. I'm not sure how to implement these function.
Using a large `match` seems not a good idea. Using an `Hashmap` as a member of `TextEncoder` will require runtime initialization. I found there is a compile time Rust static map, but not sure I can use it.
https://github.com/sfackler/rust-phf
Any suggestion about this?

**Comment by Ms2ger** [comment]
Is this <http://doc.servo.org/encoding/types/trait.Encoding.html#method.whatwg_name>?

**Comment by yodalee** [comment]
OH! my fault (: P)

**Comment by SimonSapin** [comment]
Also http://doc.servo.org/encoding/label/fn.encoding_from_whatwg_label.html

**Comment by yodalee** [comment]
The spec said the `TextEncoder` should throw a `RangeError` if input label is not a UTF type. However, the `RangeError` is not defined in `domexception`. Should I add an new exception or is there alternative exception? Since I saw the link in `DOMException.webidl`
https://dom.spec.whatwg.org/#domexception
There it says 
```
RangeException has been removed.
```

**Comment by Ms2ger** [comment]
Using `RangeError` won't work right now; throw something sensible and file a followup for now.
