### ISSUE TITLE
Implement TextDecoder.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#4769]
Spec: <https://encoding.spec.whatwg.org/#interface-textdecoder>.

Most of the actual decoding infrastructure should already be implemented in `rust-encoding`.

This includes enabling the relevant tests by adding
```ini
[encoding]
  skip: false
```
to `tests/wpt/include.ini`.

This may also include updating the `mozjs` and `rust-mozjs` dependencies to ensure we can work with typed arrays.

**Comment by KiChjang** [comment]
Alright, time to actually move from easy to less easy, lemme try and flex my muscles on this one.

**Comment by jdm** [comment]
Yep! See https://github.com/servo/servo/wiki/Adding-a-new-WebIDL-binding for reference.

**Comment by KiChjang** [comment]
Question... in the HTML spec it says that the `TextDecoder::decode` function must accept an optional  `BufferSource`. What would the be the equivalent of `BufferSource` in rust-speak?

**Comment by jdm** [comment]
Good question! I've filed a spec bug about that: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27979 . Googling around, I found http://heycam.github.io/webidl/#common-BufferSource, so I suggest adding that definition to the file for now.

**Comment by KiChjang** [comment]
Okay, so the question becomes "what is an `ArrayBuffer` in rust?"
Looking at the Servo documentation, I found [`std::io::Buffer`](http://doc.servo.org/std/io/trait.Buffer.html). Would that suffice as an `ArrayBuffer`?

**Comment by jdm** [comment]
Nope - ArrayBuffer actually corresponds to a `*mut JSObject`, as it's a type that the JS engine provides. See https://github.com/servo/servo/pull/4639 for another example of a DOM implementation that uses them.

**Comment by jdm** [comment]
Well, it's uses Uint8ClampedArray, but that's just a a specialized form of ArrayBuffer.

**Comment by KiChjang** [comment]
Oh, big problem - the python script that generates the bindings threw an exception saying `TypeError:: Can't handle SpiderMonkey Interface arguments yet` whenever I tried to use `ArrayBuffer` or `ArrayBufferView`.

**Comment by KiChjang** [comment]
When JavaScript does `new TextDecoder()`, Rust throws a `SyntaxError`. The default `label` argument to the constructor is `utf-8`, but `encoding_from_whatwg_label`doesn't like the default `utf-8` string generated by the python bindings. Instead, if you do `new TextDecoder('utf-8')` in JavaScript, then `encoding_from_whatwg_label` doesn't complain.

**Comment by Ms2ger** [comment]
Pre-existing bug; I'll deal with it.

**Comment by KiChjang** [comment]
Is there an issue number that tracks the bug that @Ms2ger mentioned? The `SpiderMonkey` interface arguments for the WebIDL also needs to be implemented (`Uint8Array`, `ArrayBuffer`, ...).

**Comment by yodalee** [comment]
I see the the sample code posted by jdm using `Uint8ClampedArray`, I try to add 
```
use js::jsfriendapi::bindgen::{JS_NewArrayBuffer, JS_GetUint8ClampedArrayData};
```
as depict in file: `components/bindings/codegen/TypedArray.h`
But compiler cannot resolve this include.

**Comment by Ms2ger** [comment]
You'll need changes like <https://github.com/servo/mozjs/pull/25> and <https://github.com/servo/rust-mozjs/pull/128>, and then use `./mach update-cargo -p js` to pull in those changes.

**Comment by yodalee** [comment]
See, I will do the changes to servo/mozjs first.

**Comment by yodalee** [comment]
@KiChjang Thanks Ms2ger, now we can use all TypedArray.

**Comment by jdm** [comment]
Oh, https://github.com/servo/servo/pull/4998 only updated rust-mozjs, not mozjs. Use `-p js-sys` for that one.

**Comment by yodalee** [comment]
It says `js-sys matched no packages`

**Comment by yodalee** [comment]
OK I found, use `-p mozjs-sys`

**Comment by KiChjang** [comment]
I'm not entirely sure how to use these yet... I did `./mach update-cargo -p js` and `./mach update-cargo -p mozjs-sys`, but it still gave me `TypeError: Can't handle SpiderMonkey interface arguments yet`

**Comment by Ms2ger** [comment]
I would suggest using `object` in the IDL for now.

**Comment by KiChjang** [comment]
That wouldn't work either; it would just tell me `TypeError: Can't handle object arguments yet`. I think this issue is going to be blocked until `CodegenRust.py` can generate either `Uint8Array`/`ArrayBuffer`/`BufferSource` arguments or `object` arguments
