### ISSUE TITLE
Don't use * versions in crates.io dependencies

### ISSUE THREAD

**Issue by jdm** [servo/servo#4780]
Right now any clone that checks for rust-url updates won't build, because there's a new release that uses derive(Debug).

**Comment by SimonSapin** [comment]
That’s only when you run `cargo update` or `mach update-cargo`, though, right? `Cargo.lock` should take care of having everyone use the same version.

I don’t think we should rely on dependency versions for this. Locking to a specific micro version is what `Cargo.lock` does already, and relying on SemVer doesn’t work for Rust upgrade: the convention in the ecosystem seems to be to only bump the micro version component for Rust upgrades, even though that’s breaking. “It sucks but it’ll hopefully get better after 1.0” is the idea.

**Comment by jdm** [comment]
I don't think it's that simple. Switching between branches (that previously compiled) for my local clone caused Cargo to fetch rust-url for some reason, and that's when I found that 0.2.17 didn't build with the 1.0 nightly. I also couldn't find a way to force a downgrade.

**Comment by jdm** [comment]
We now forbid this.
