### ISSUE TITLE
Unify color types in rust-azure/servo

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#4786]
Currently we have near 3 color objects: rust-azure (AzColor, Color) and servo (Color as a AzColor).

It may be interesting to streamline the color types. I see at least 2 approaches:

a) Have a single Color type (probably AzColor) with all the methods;

b) Have just 2 Color types: 1 being a lower level implementation and other with helper functions (and keeping compatibility between the struct fields).

There is also a CSSColor and RGBAColor in components/style/values. I wonder if we could have this CSS types based in a common type?

**Comment by Adenilson** [comment]
We got YACT (Yet Another Color Type) in rust-layers: https://github.com/servo/rust-layers/blob/master/src/color.rs

**Comment by Adenilson** [comment]
First step here:
https://github.com/servo/rust-azure/pull/141

And:
https://github.com/servo/servo/pull/4879

**Comment by nox** [comment]
I think this can be closed, we shouldn't merge the fancy colour types from style with other ones that are more lower-level.
