### ISSUE TITLE
Make the Constellation key event handler deal with missing current frames

### ISSUE THREAD

**Issue by jdm** [servo/servo#4795]
`Constellation::handle_key_msg` gets the current frame if it exists and forwards the key event to it. This causes a problem if there is no current frame, since the compositor relies on the script task being able to send unconsumed key events back to it. When this doesn't occur, we get problems like the escape key no longer closing the main Servo window. We should make the `Constellation` send the key event back to the `Compositor` if there's no frame in order to avoid this. See the relevant code at the end of  `ScriptTask::dispatch_key_event` for the gist of how this should occur.

**Comment by jdm** [comment]
A good way to test this is run an HTML file containing `<script>window.close()</script>`.

**Comment by KiChjang** [comment]
I can take this one, however a few clarifications are needed.
1. Do the following test files test accurately for this behaviour? `tests/html/test_close.html`, `tests/html/test_hammer_layout.html`, `tests/html/test_slam_layout.html`
2. By relevant code in `ScriptTask::dispatch_key_event`, do you mean the following code:
```rust
if !prevented {
    self.compositor.borrow_mut().send_key_event(key, state, modifiers);
}
```

**Comment by jdm** [comment]
test_close.html does not, since it's in a timeout and therefore asynchronous. I can't tell if it occurs for test_hammer_layout.html since it takes too long to run, but test_slam_layout.html does demonstrate it. Personally, I would just create a new HTML file that contains exactly what my previous comment said :) And yes, that is the code to which I was referring. Thanks for taking this on!

**Comment by KiChjang** [comment]
Hmph. I am having trouble with `DOMRefCell<T>`... I am getting an error message when I run the following HTML file (before and after I did some code changes to `compositing/constellation.rs`):

```html
<html>
<script>
window.close();
</script>
</html>
```
The error message it spat out was this:
```
thread 'ScriptTask' panicked at 'DOMRefCell<T> already mutably borrowed', dom/bindings/cell.rs:119
stack backtrace:
   1:     0x7f7bc80c2000 - sys::backtrace::write::h2d33c3c7ed646e34Czt
   2:     0x7f7bc80d7110 - failure::on_fail::h973a98f343057a4eaPz
   3:     0x7f7bc80a5500 - rt::unwind::begin_unwind_inner::h1ff3dff6fb4b069d2tz
   4:     0x7f7bc6d0fb60 - rt::unwind::begin_unwind::h3443816228659440728
   5:     0x7f7bc72a9f00 - dom::bindings::cell::DOMRefCell<T>::borrow::h13762614245670599939
   6:     0x7f7bc72a9ca0 - dom::bindings::cell::DOMRefCell<T>.JSTraceable::trace::h16953224405167611802
   7:     0x7f7bc71a0390 - page::Page...dom..bindings..trace..JSTraceable::trace::h1c4e3703be9b67d437C
   8:     0x7f7bc71a0300 - dom::bindings::trace::Rc<T>.JSTraceable::trace::h10486235814487352919
   9:     0x7f7bc703ff30 - dom::window::Window...dom..bindings..trace..JSTraceable::trace::hd6947906eaf3ae58s8y
  10:     0x7f7bc703fec0 - dom::bindings::codegen::Bindings::WindowBinding::_trace::__rust_abi
  11:     0x7f7bc703fe70 - dom::bindings::codegen::Bindings::WindowBinding::_trace::h9b4fe3291fb23fc6k1Q
...
```
Does that mean my code change did not work, or is it simply an entirely different issue altogether?

**Comment by jdm** [comment]
No, that's exactly what is intended to happen :) The panic is the script task dying, and when that occurs you should just see a white screen that does not respond to key events any more.

**Comment by jdm** [comment]
Huh, I just tried the snippet myself and don't see the ScriptTask panic error anymore :(

**Comment by KiChjang** [comment]
That's weird... I just did a clean on my servo and rebuilt everything from scratch, yet I am still getting the ScriptTask panic. The HTML that I've used to test is the same as above, and I've also used code changes that are in my PR.

**Comment by jdm** [comment]
Nevermind, I mistyped it.

**Comment by KiChjang** [comment]
This should be closed.
