### ISSUE TITLE
Port Gecko's JSToNativeConversionInfo changes to Servo's codegen

### ISSUE THREAD

**Issue by jdm** [servo/servo#4800]
This will make porting other changes from Gecko easier, rather than returning tuple types from `getJSToNativeConversionTemplate` (to be renamed `getJSToNativeConversionInfo`).

https://mxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py#4764
https://mxr.mozilla.org/servo/source/components/script/dom/bindings/codegen/CodegenRust.py#648

**Comment by psdh** [comment]
I can try fixing this :)

**Comment by jdm** [comment]
@psdh That would be great! Shout if anything is confusing :)

**Comment by psdh** [comment]
@jdm, as far as I have understood, I will have to rename the `getJSToNativeConversionTemplate` and then add the code that you have marked. I did not get the returning tuples part. It is returning tuples right now, what do we want it now to do?

**Comment by jdm** [comment]
@psdh In Gecko, they return a structure. That's much better for code readability in this case, so we want to return a structure too.

**Comment by psdh** [comment]
How should I go about returning the `needsRooting` (4th element of the tuple which is being returned). The first three are part of the `JSToNativeConversionInfo' class.
I tried referring to [1] but could not comprehend it very well.
[1]: https://mxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py#4180

**Comment by jdm** [comment]
`needsRooting` is a Servo addition, so you should add it to `JSToNativeConversionInfo`.
