### ISSUE TITLE
Support documents without browsing contexts

### ISSUE THREAD

**Issue by jdm** [servo/servo#4806]
This has a number of practical implications:
* `defaultView` should return null if the document doesn't have a browsing context
* we need to be less cavalier about using the `window` member of `Document`, since that's only there for internal purposes (basically "give me a global object related to this node")
* we'll need to have the browser context status be mutable, to allow attaching/detaching iframes from documents
* we need to carefully screen how `window_from_node` is used

I'm sure there are more that elude me at this moment.

**Comment by Ms2ger** [comment]
Fixed in #9603.
