### ISSUE TITLE
Make MouseEvent and UIEvent constructors take EventBubbles and EventCancelable enum arguments

### ISSUE THREAD

**Issue by jdm** [servo/servo#4807]
Boolean arguments are bad. Using the enums as arguments will make for more readable code.

Code: components/script/dom/uievent.rs and components/script/dom/mouseevent.rs

**Comment by muscar** [comment]
I can do that

**Comment by jdm** [comment]
Great!

**Comment by jdm** [comment]
Any update @muscar?

**Comment by wenderen** [comment]
I have a patch ready to go. If this is not being actively worked on, may I PR?

**Comment by muscar** [comment]
@wenderen please make the PR. Unfortunately I didn't have time to work on this. Sorry for the trouble :(

**Comment by wenderen** [comment]
Sure, thanks.
