### ISSUE TITLE
sliderust doesn't work with incremental layout

### ISSUE THREAD

**Issue by jdm** [servo/servo#4833]
```
<huon> hm, it seems servo no longer works correctly with 'sliderust'
http://kmcallister.github.io/sliderust/ I'm seeing any additional slides appended
at the end of the document without hiding older ones when I press right, and
nothing happens when I press left to try to go back. Can anyone else reproduce?
```
I remember jack hit the same problem when prepping for LCA in January, too.

**Comment by metajack** [comment]
As a workaround, you can run servo with `-i` to disable incremental layout.

**Comment by shinglyu** [comment]
Let me take this one.

**Comment by shinglyu** [comment]
Loaded ![2015-02-10 23 24 39](https://cloud.githubusercontent.com/assets/3250983/6129865/3c5ed56c-b17c-11e4-810a-2d1975903e6f.png)
After clicking "->" ![2015-02-10 23 25 11](https://cloud.githubusercontent.com/assets/3250983/6129863/3c57dfe6-b17c-11e4-8f89-1bc08e5ade48.png)

**Comment by jdm** [comment]
It looks like we're not noticing that the original slide contents should be hidden when restyling.

**Comment by shinglyu** [comment]
I got different results (fonts and layout) by running `./mach run` and `targets/servo` directly, is there any parameter in `./mach run` that affects the layout?

**Comment by jdm** [comment]
Huh, I wouldn't expect that. http://mxr.mozilla.org/servo/source/python/servo/post_build_commands.py#33 defines the arguments passed to it.

**Comment by shinglyu** [comment]
Sorry, problem solved now. I got the wrong binary from an old build.

**Comment by shinglyu** [comment]
Still studying how layout works by reading the code and wiki. Is there any guide on logging or using the debugger? I can only find [this](https://github.com/servo/servo/wiki/Debugging) but I am having some trouble understand it.

**Comment by jdm** [comment]
For logging you can use RUST_LOG=layout to see _all_ possible output, or RUST_LOG=layout::module::sub_module to restrict the output. For using the debugger, any general tutorial for LLDB or GDB should suffice.

**Comment by shinglyu** [comment]
Just to let you know I'm still studying how layout works, here is my note: http://shinglyu.gitbooks.io/the-servo-browser-engine-a-learner-s-notebook/content/layout.html

**Comment by jdm** [comment]
For what it's worth, this might be handled by #5064.

**Comment by shinglyu** [comment]
OK. I'll verify if it's fixed.

I'll try to go through the layout module anyway, can you suggest me other easy bug in layout? Thanks!

**Comment by shinglyu** [comment]
Verified fixed on today's build. We can close this issue.

**Comment by jdm** [comment]
Thanks!
