### ISSUE TITLE
Add a --release flag to mach run command

### ISSUE THREAD

**Issue by jdm** [servo/servo#4834]
Source: `python/servo/post_build_commands.py`

The path we use to run servo should get an extra `release` directory in which the servo binary resides when this flag is present. This allows running release builds after using `./mach build release`.

**Comment by psdh** [comment]
I would like to help fix this :)

**Comment by jdm** [comment]
Great! I suggest taking a look at our other python commands that use a --release flag: http://mxr.mozilla.org/servo/search?string=--release

**Comment by psdh** [comment]
I did take a look and made some changes. 
according to what I have understood I would just have to append ['--release'] to args if release is true.
But I do not clearly understand the meaning of running releases. I also feel that I am missing something.
Thanks :)

**Comment by jdm** [comment]
Normally the binary ends up in `components/targets/servo` for non-release builds. When you use `build --release`, it is placed in `components/targets/release/servo`. `./mach run` doesn't know about this.

**Comment by gilles-leblanc** [comment]
This one can be closed.
