### ISSUE TITLE
Pressing a number key doesn't send an event to the DOM

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#4839]
STR:

 - Run tests/html/form_submission.html
 - Try typing a number (it doesn't appear). Letters work fine

I set a breakpoint on `dispatch_key_event` in script_task, and it seems like for these keys it doesn't reach there at all. Looks like a compositor (or glutin?) problem

cc @glennw @jdm

**Comment by jdm** [comment]
I see numbers on OS X.

**Comment by jdm** [comment]
I guess this should be filed upstream in glutin, in that case?

**Comment by Manishearth** [comment]
Sounds like it.

**Comment by glennw** [comment]
Yep, I think I know what the issue will be. File it in glutin and I'll take a look today.

**Comment by Manishearth** [comment]
Filed.
