### ISSUE TITLE
Implement Location.assign

### ISSUE THREAD

**Issue by jdm** [servo/servo#4841]
Spec: https://html.spec.whatwg.org/multipage/browsers.html#the-location-interface
Code: components/script/dom/location.rs

This can use the Window::load_url method.

**Comment by KiChjang** [comment]
Let me have a go at this, please.

**Comment by KiChjang** [comment]
How am I able to refer back to an instance of a `window` object within `Location`?

**Comment by KiChjang** [comment]
I was playing around with `location.rs` for a while, and I figured that there's no way to refer to a `window` object within `Location`. Should we add a new attribute for `Location` that stores an instance of `window`?

**Comment by jdm** [comment]
Yep!

**Comment by jdm** [comment]
Oh, I lied - you can get a Window from the stored Page member via `page.frame().unwrap().window`.
