### ISSUE TITLE
Scrolling behaviour inverted on OSX.

### ISSUE THREAD

**Issue by nwin** [servo/servo#4846]
The scrolling wheel behavior is inverted compared to the system setting (e.g. its “natural” in servo if the system is set to “normal” and vice versa).

It might be a bug it glutin because the scrolling wheel delta is deliberately set to it’s negative value for OSX but I have nothing to test glutin alone.

**Comment by jdm** [comment]
It's definitely something that changed recently. @glennw, did we upgrade glutin?

**Comment by glennw** [comment]
We upgraded during the last rustup - nothing (intentional) since then. Is that around when it started happening? I can't see anything obvious in the glutin history that would cause this to change (although it may be from a glutin dependency like rust-cocoa).

**Comment by jdm** [comment]
Maybe I just haven't scrolled since we switched to Glutin. I know that I don't see this behaviour in the CEF embedding.

**Comment by glennw** [comment]
Yep, I suspect it's always been that way in glutin then - I'll flip the behaviour in upstream glutin so we get it in the next rustup.

**Comment by pcwalton** [comment]
@glennw I can confirm this.

**Comment by glennw** [comment]
Added a single character glutin PR for this (https://github.com/tomaka/glutin/pull/261)

**Comment by frewsxcv** [comment]
Scrolling is working correctly for me on OSX, can anyone else confirm?

**Comment by nwin** [comment]
It is correct now.
