### ISSUE TITLE
Make trigger_fragment take a String argument instead of a Url

### ISSUE THREAD

**Issue by jdm** [servo/servo#4863]
Instead of assuming that the Url contains a fragment, let's make callers pass the fragment as an argument instead.

Code: components/script/script_task.rs

**Comment by KiChjang** [comment]
I can give this a try. This means that we should send in a string argument containing only the substring after the # sign in the URL, yes?

**Comment by jdm** [comment]
Yes. There is an API to extra that from a Url already - http://doc.servo.org/url/struct.Url.html#structfield.fragment
