### ISSUE TITLE
mach run should produce a better error when the binary is missing

### ISSUE THREAD

**Issue by jdm** [servo/servo#4874]
```
godot2:servo jdm$ ./mach run http://google.com
Error running mach:

    ['run', 'http://google.com']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory

  File "/Users/jdm/src/servo/python/servo/post_build_commands.py", line 78, in run
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
```
This is really unintelligible. What it means is that `subprocess.check_call` threw an exception because it couldn't find the servo binary, so let's catch that exception in `post_build_commands.py`.

**Comment by psdh** [comment]
I will fix this

**Comment by jdm** [comment]
Thanks!

**Comment by SimonSapin** [comment]
Or shouldn’t `mach run` start with `mach build`? This would trigger a compile not only if the binary is missing, but also if it’s out of date. This is how `cargo run` works.

**Comment by Manishearth** [comment]
I'd prefer if it didn't; I want to be able to test things without triggering a build.

That's the makefile way of doing things; mark build as a dep for run/test and rebuild every time you need to. Except that this can trigger large rebuilds when all you wanted was to test it. The Firefox/mach way of doing it is to have builds be explicit, and tests will run on binaries if they exist (if not, trigger a build)

**Comment by SimonSapin** [comment]
Ok, that makes sense.

**Comment by rmabhatia** [comment]
can any one help me....... i got error "No Servo Binary Found"  when i entered ./mach run command...

**Comment by Manishearth** [comment]
@rmabhatia Please run `./mach build` first :smile:

**Comment by rmabhatia** [comment]
did that but still got the error

**Comment by Manishearth** [comment]
Did the build exit successfully? What are the contents of `target/` and `target/debug`?

Perhaps run `./mach build -d` instead.

**Comment by rmabhatia** [comment]
The details of the failure are as follows:

CalledProcessError: Command '[u'git', u'submodule', u'status']' returned non-zero exit status 128

  File "/home/rama/Downloads/servo-master/python/servo/build_commands.py", line 196, in build
    self.ensure_bootstrapped()
  File "./python/servo/command_base.py", line 401, in ensure_bootstrapped
    Registrar.dispatch("update-submodules", context=self.context)
  File "/home/rama/Downloads/servo-master/python/mach/mach/registrar.py", line 115, in dispatch
    return self._run_command_handler(handler, context=context, **kwargs)
  File "/home/rama/Downloads/servo-master/python/mach/mach/registrar.py", line 90, in _run_command_handler
    result = fn(**kwargs)
  File "/home/rama/Downloads/servo-master/python/servo/bootstrap_commands.py", line 278, in update_submodules
    submodules = subprocess.check_output(["git", "submodule", "status"])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)

**Comment by rmabhatia** [comment]
i did the ./mach build -d

**Comment by Manishearth** [comment]
Ah, Please update to the latest version of `git`

**Comment by rmabhatia** [comment]
please guide me this......

**Comment by rmabhatia** [comment]
rama@ubuntu:~/Downloads/servo-master$ git --version
git version 1.9.1
rama@ubuntu:~/Downloads/servo-master$ apt-get install git
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
rama@ubuntu:~/Downloads/servo-master$

**Comment by rmabhatia** [comment]
getting this error while installing git

**Comment by Manishearth** [comment]
You need to use `sudo apt-get install git`.

(Might want to join the #servo IRC channel on irc.mozilla.net, using IRCCloud or Mibbit to join to discuss further)

**Comment by rmabhatia** [comment]
rama@ubuntu:~/Downloads/servo-master$ git --version
git version 1.9.1
rama@ubuntu:~/Downloads/servo-master$ apt-get install git
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
rama@ubuntu:~/Downloads/servo-master$

**Comment by rmabhatia** [comment]
rama@ubuntu:~/Downloads/servo-master/etc$ sudo apt-get install git
[sudo] password for rama: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 265 not upgraded.
rama@ubuntu:~/Downloads/servo-master/etc$

**Comment by rmabhatia** [comment]
this is saying already new version
