### ISSUE TITLE
Allow mach clean to take an optional package argument

### ISSUE THREAD

**Issue by jdm** [servo/servo#4898]
`./mach clean` does a full clean of everything. Sometimes you just want to clean a particular crate or dependency, which is possible via `cd components/servo && ../../mach cargo clean -p package`. We can improve this by adding an optional argument that causes the previous command to be run if it's present. Use the `update-cargo` implementation for reference: http://mxr.mozilla.org/servo/source/python/servo/devenv_commands.py#29

**Comment by awlnx** [comment]
I can get working on this.
can you clarify "we can improve this by adding an optional argument that causes the previous command to be run if it's present.". With an example.

**Comment by jdm** [comment]
@awlnx I would like `./mach clean -p compositing` to be the equivalent of `pushd components/servo; ./mach cargo clean -p compositing; popd;`. I might be enough to simply allow passing any arguments to `./mach clean` through to the underlying `cargo clean` that gets executed. See how commands like `./mach run` handle this in post_build_commands.py.
