### ISSUE TITLE
CPU remains at 100% for a super simple page

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#4899]
I run `./mach run /tmp/test.html`, where `/tmp/test.html` is just 

```
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <h1 id="hello_world">Hello World</h1>
</body>
</html>
```

But the CPU remains 100% even if I left the window idle for a long time. Is this normal?
![2015-02-11 23 36 59](https://cloud.githubusercontent.com/assets/3250983/6149963/5edb1904-b247-11e4-9c6f-231bc2d1e3b4.png)

My OS is Linux Mint 17 Qiana

**Comment by jdm** [comment]
We should profile this. Want to try running it under `perf`?

**Comment by glennw** [comment]
This is a known bug in glutin's event handling loop - it will be sorted next time we update.
