### ISSUE TITLE
CharacterData::SubstringData slices incorrectly

### ISSUE THREAD

**Issue by jdm** [servo/servo#4906]
The slicing should be from offset to offset + count, but it just slices from offset to count instead.

**Comment by yodalee** [comment]
I think I can do this.

**Comment by jdm** [comment]
I believe so. Testing the behaviour would be great - we can add one easily to tests/content/ and run it using `./mach test path/to/test.html`, but it would also be a good idea to submit one to https://github.com/w3c/web-platform-tests/, since https://github.com/w3c/web-platform-tests/search?utf8=%E2%9C%93&q=substringdata&type=Code shows very little usage.
