### ISSUE TITLE
Mach bootstrapping should sync/update submodules

### ISSUE THREAD

**Issue by gilles-leblanc** [servo/servo#4916]
Following the latest rustup, I ran into an error when trying to ```mach clean``` or ```mach build``` relating to the sub modules. 

Mach's bootstrapping should run either ```git submodule sync``` or ```mach update-submodules``` to automate this and prevent this from happening.

**Comment by jdm** [comment]
Relevant code: http://mxr.mozilla.org/servo/source/python/servo/build_commands.py

**Comment by psdh** [comment]
Should mach build sync at everytime it is invoked, 
If not, How should I test?

**Comment by SimonSapin** [comment]
This should happen in [`ensure_bootstrapped`](https://github.com/servo/servo/blob/3e7dc576934acb935fd67b6b3d909aca216c5dec/python/servo/command_base.py#L165), which is called at the beginning of most commands. Currently it runs `git submodule status` and based on the output conditionally runs `git submodule update <something>`.

**Comment by psdh** [comment]
@SimonSapin ^ is what I was asking, do we want to sync every time?

**Comment by SimonSapin** [comment]
To be honest I’m not sure. I think makes sense to run `submodule sync` every time we run `submodule update` but the former doesn’t accept `--recursive`. Also we’ll need to make sure that the script works for both a new servo clone and an existing clone.
