### ISSUE TITLE
Intermittent failure in pages with timers

### ISSUE THREAD

**Issue by jdm** [servo/servo#4923]
I see one new failure [here](http://build.servo.org/builders/mac2/builds/962/steps/shell/logs/stdio):
```
thread 'Window:SetTimeout' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:        0x10b091927 - sys::backtrace::write::h084c3267f5afd4a3hvy
   2:        0x10b0a7893 - failure::on_fail::hc5ca3b9ac2e803f33NF
   3:        0x10b074b58 - rt::unwind::begin_unwind_inner::h6a7a87805596eb8avvF
   4:        0x10b0752c1 - rt::unwind::begin_unwind_fmt::h1fd6919e00fae1f31tF
   5:        0x10b0a728e - rust_begin_unwind
   6:        0x10b0c9f97 - panicking::panic_fmt::hd22743a6fa1fac27zow
   7:        0x10a4deadc - result::Result<T, E>::unwrap::h14384637977615199039
   8:        0x10a4de8bd - script_task::NonWorkerScriptChan.ScriptChan::send::h7a77ad0a9e7dcfe07rD
   9:        0x10a537d97 - timers::TimerManager::set_timeout_or_interval::closure.88350
  10:        0x10a537691 - task::spawn_named::closure.88343
  11:        0x10a537564 - thunk::Thunk<(), R>::new::closure.88339
  12:        0x10a53742d - thunk::F.Invoke<A, R>::invoke::h9755239712050321226
  13:        0x10a2d2ac1 - thunk::Thunk<A, R>::invoke::h11641617110891784916
  14:        0x10a2d37fa - thread::Builder::spawn_inner::closure.81789
  15:        0x10a2d377f - rt::unwind::try::try_fn::__rust_abi::h13345969517191097717
  16:        0x10a2d371a - rt::unwind::try::try_fn::h13345969517191097717
  17:        0x10b0a9279 - rust_try_inner
  18:        0x10b0a9266 - rust_try
  19:        0x10a2d2c0c - rt::unwind::try::h5213795867344952062
  20:        0x10a2d194f - thread::Builder::spawn_inner::closure.81687
  21:        0x10a2d47d9 - thunk::Thunk<(), R>::new::closure.81810
  22:        0x10a2d46c1 - thunk::F.Invoke<A, R>::invoke::h11315143147767302084
  23:        0x10b095353 - sys::thread::thread_start::h8d91e5be653c10c05CB
  24:     0x7fff8e0db772 - _pthread_start
```
This should just be a silent failure; there's no need to unwrap the result, we can just check for failure and shut the task down gently. Relevant code is in `components/script/timers.rs`.

**Comment by psdh** [comment]
I need some help understanding this ^

**Comment by jdm** [comment]
When the timer thread in `timers.rs` sends messages to the script task, it calls `unwrap` on the result. This causes a panic if the send failed, but we don't actually need to care about this, so we should just discard the result instead of calling unwrap.

**Comment by KiChjang** [comment]
By "discard the result", do you mean do nothing, or `break` out of the loop? In your first message, you said "shut the task down gently".

**Comment by jdm** [comment]
Yes, breaking out of the loop would be appropriate.

**Comment by tomjakubowski** [comment]
The problematic unwrap appears to be inside the `send` method of the `ScriptChan` impl for `NonWorkerScriptChan`, and not directly in the timer loop as I initially read from the issue description. The solution then, it seems to me, would be to change `send`'s signature to return a `Result<_, Something>`  and checking its return type in the loop (and wherever else the `ScriptChan::send` method is called).

**Comment by jdm** [comment]
I agree with @tomjakubowski!
