### ISSUE TITLE
Support navigating session history in subframes

### ISSUE THREAD

**Issue by jdm** [servo/servo#4926]
The compositor really shouldn't be the one issuing backwards and forwards navigation instructions based on keypresses; that task belongs to the script task, which has some concept of document focus. Accordingly, this will allow focusing on an iframe and pressing backspace to move backwards in history for that iframe alone.

**Comment by ConnorGBrewster** [comment]
With the joint session history, we shouldn't be just traversing the history of the focused iframe back when a backward/forward traversal is issued but rather we should traverse the joint session history of the top-level browsing context.

**Comment by nox** [comment]
Cc @asajeffrey

**Comment by asajeffrey** [comment]
@jdm: is this still an issue?

**Comment by jdm** [comment]
I think not.
