### ISSUE TITLE
Compositor layers for fixed rectangles are drawn incorrectly.

### ISSUE THREAD

**Issue by glennw** [servo/servo#4944]
In the following example, the layer is drawn at (-3,-3) meaning that the rectangle does not stretch to the right edge of the window correctly. This is something to do with how layer origins + overflow interacts, but I haven't dug further than that.

```
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
            div {
                background-color: red;
                top: 0;
                left: 0;
                width: 100%;
                height: 100px;
                position: fixed;
            }
        </style>
    </head>
    <body>
        <div id="header"></div>
    </body>
</html>
```

**Comment by glennw** [comment]
@mrobinson Any ideas?

**Comment by mrobinson** [comment]
Hrm. Do you know if the error is originating in the compositor or in layout?

**Comment by mrobinson** [comment]
Hrm. I think with the retirement of the old compositor this isn't an issue any longer. @glennw, do you mind confirming if we can close this?
