### ISSUE TITLE
Certificate check failed for URL in "Certificate Subject Alt Name"

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#4953]
Certificate checked failed for https://tw.yahoo.com .

The certificate's CN is `www.yahoo.com`, while `tw.yahoo.com` is in the "Certificate Subject Alt Name" field.

@Manishearth may be interested in this.
![2015-02-18 23 37 11](https://cloud.githubusercontent.com/assets/3250983/6250994/437654b4-b7cc-11e4-8944-d8410b0b5179.png)

**Comment by Manishearth** [comment]
The relevant root cert is in our certfile.

I suspect we're not setting some verify option that openssl requires.

I might take some time going through this as it involves either:

 - Going through tons of openssl code
 - Creating fake certs and testing this to get a minimal example.

**Comment by Manishearth** [comment]
Possible issues:

https://wiki.mozilla.org/CA:FAQ#Can_I_use_Mozilla.27s_set_of_CA_certificates.3F  https://groups.google.com/forum/#!msg/mozilla.dev.security.policy/FYIBEF_AVMI/2KYQrWirsiQJ

Apparently we're not supposed to use Mozilla's root store without using NSS too. The main issue seems to be the trust bit (which we check), but this might need looking in to.

**Comment by mbrubeck** [comment]
I don't think the SAN is the problem, since apparently we don't check hostnames (#4954).

**Comment by nox** [comment]
This works now.
