### ISSUE TITLE
Verify hostnames in SSL certificates

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#4954]
When visiting a site whose certificate is invalid because of a hostname mismatch (such as https://en.irfanview-forum.de/), Servo does not display any error.

OpenSSL does not automatically verify that the hostname in the URL matches the subject name or SAN (subject alternate name) in the certificate.  The application must do this.  It might make sense to put some of this functionality into Hyper.

Documentation:

* http://wiki.openssl.org/index.php/Hostname_validation
* https://crypto.stanford.edu/~dabo/pubs/abstracts/ssl-client-bugs.html

**Comment by Manishearth** [comment]
I guess we'll need to `set_verify` and all?

**Comment by mbrubeck** [comment]
We can use `X509_VERIFY_PARAM_set1_host` and `set_verify` if we require OpenSSL 1.0.2 or later.

If we need to support older versions (currently we use 1.0.1 on Android, for example), we need to include code like [this sample code](https://github.com/iSECPartners/ssl-conservatory/blob/1449f3ae918623699947e24f388c531b30ad2c87/openssl/openssl_hostname_validation.c).

**Comment by frewsxcv** [comment]
Worth noting this is also an issue in Hyper: https://github.com/hyperium/hyper/issues/472

**Comment by Manishearth** [comment]
Not exactly, `hyper` provides the right hooks, we just don't use them to their full extents.

**Comment by tarcieri** [comment]
I just started an RFC6125 hostname verification library for Rust:

https://github.com/tarcieri/pkixnames

I plan on modeling its behavior off of both Chrome and Firefox

**Comment by Manishearth** [comment]
cool!

I'm pretty sure you just need to set the right flags in rust-openssl and it will do the verification for you.

[this](https://github.com/servo/servo/blob/master/components/net/http_loader.rs#L116) is what we do (using [these](https://github.com/servo/servo/blob/master/resources/certs) certificates obtained from Firefox via [this](https://github.com/servo/servo/blob/master/etc/cert_generator.js) script), but we need to set some more openssl flags manually there (I forgot which ones, but [the functions here](http://sfackler.github.io/rust-openssl/doc/src/openssl/ssl/mod.rs.html#386-466) should give you some idea)

**Comment by tarcieri** [comment]
@Manishearth does rust-openssl implement RFC6125 itself? Prior to openssl "1.1.0" (i.e. unreleased), OpenSSL provided no native support for hostname verification.

**Comment by Manishearth** [comment]
No idea, you probably should check openssl-sys

-----Original Message-----

**Comment by tarcieri** [comment]
Basically what I'm saying is no released version of OpenSSL has native support for hostname verification, so if something is doing it, it's some code someone wrote in Rust themselves.

**Comment by Manishearth** [comment]
Ah, I see.

An alternative is to bind to nss or pkix from the Mozilla tree, IIRC both are independent libraries. I recommend using pkix.

-----Original Message-----

**Comment by tarcieri** [comment]
@Manishearth I'm basically planning on reimplementing the hostname verification part of pkix in pure Rust, FWIW

**Comment by Manishearth** [comment]
Alternatively, could you structure this so that it uses openssl for the cert checking, and then has its own verification method that operates on the cert and URL? Something that can be fed to the verification method of sslcontext.

-----Original Message-----

**Comment by tarcieri** [comment]
Yep, that's exactly what my library vaporware library would allow you to do :wink:

**Comment by Manishearth** [comment]
@tarcieri What's the status on this? Does it mostly work now, and is it ready for (experimental?) integration in Servo?

**Comment by tarcieri** [comment]
@Manishearth nope, I got distracted by other things, but I'd like to pick it up and finish it soon

**Comment by frewsxcv** [comment]
Since it hasn't been explicitly stated in here, here's a relevant project: https://github.com/briansmith/webpki

**Comment by brson** [comment]
[Here's the PR where I'm fixing this in rustup](https://github.com/rust-lang-nursery/rustup.rs/pull/400).

**Comment by frewsxcv** [comment]
Latest version of Hyper now does hostname validation.

https://github.com/hyperium/hyper/pull/784/files

Might be good to create a unit test exemplifying the hostname validation.

**Comment by paulrouget** [comment]
What happens now if there's an invalid certificate? Does Servo display a special page? Blank page? Is there a `mozbrowsererror` event triggered?

**Comment by jdm** [comment]
My assumption is that it manifests as a network error inside Servo, and each network response consumer can choose how to handle those independently. For top-level page loads, we display about:neterror at the moment.

**Comment by mbrubeck** [comment]
Note: We haven't updated to hyper 0.9.4, so Hyper's hostname verification is not in Servo master yet.

I just built with hyper 0.9.4 locally, and https://blog.rust-lang.org/ loaded with no errors in Servo.  (It should trigger a certificate verification error.)  I'm not sure yet whether this is a bug in Servo or in Hyper...

**Comment by jdm** [comment]
I believe only the default client has hostname validation enabled by the changes in #784. We'll need to adapt them for our own code (see `create_http_connector` in `http_loader.rs`).

**Comment by jdm** [comment]
Although I guess we could verify it by seeing if `wrap_client` gets called in hyper.

**Comment by mbrubeck** [comment]
Indeed, we are using `hyper::net::Openssl` instead of `hyper::net::OpensslClient`, and `Openssl::wrap_client` does not do `set_verify_callback`.

**Comment by mbrubeck** [comment]
When I add a `set_verify_callback`, Servo just displays a blank page when I try to load a page with an invalid certificate.  (This is the same thing it does for me on other network errors, like a hostname that doesn't resolve.)
