### ISSUE TITLE
Use hosts file for WPT test runs

### ISSUE THREAD

**Issue by jdm** [servo/servo#4968]
We need to set up one as described at https://github.com/servo/web-platform-tests/#running-the-tests, and set the HOST_FILE environment variable as part of the `test-wpt` command in http://mxr.mozilla.org/servo/source/python/servo/testing_commands.py#214

**Comment by jdm** [comment]
Assuming it's set up correctly, I would expect the output from `./mach test tests/wpt/web-platform-tests/html/browsers/history/the-location-interface/security_location_0.sub.htm` to change from what was reported in #3219.

**Comment by srlakhe** [comment]
@jdm 
Hi,
I would like to work on this bug.  How should I proceed ?

**Comment by jdm** [comment]
@srlakhe Great! Is anything unclear in the first comment? We probably want to create the new hosts file in the resources directory and make the HOST_FILE environment variable point to that path. This will just require Python code changes.

**Comment by shinglyu** [comment]
@srlakhe: You can also see [this wiki page](https://github.com/servo/servo/wiki/Testing#assign-a-temporary-hostfile-for-testing) to understand how to use the HOST_FILE environment variable.

**Comment by jdm** [comment]
Any update @srlakhe?

**Comment by srlakhe** [comment]
@jdm , sorry won't be able to work on it for a while
