### ISSUE TITLE
Relative positioned div rendered behind other elements in the flow

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#4973]
Setting a div to be relative will make servo render it behind the following element. It can be seen here:
http://codepen.io/Savago/pen/JoLmMP

And the test case: http://codepen.io/Savago/pen/yyKRzq

**Comment by SimonSapin** [comment]
Relevant spec is http://dev.w3.org/csswg/css2/zindex.html

In this test case, the element with ID `two` is *positioned* (`position: relative`) and has `z-index: auto` (the initial value).

> 8- All positioned descendants with 'z-index: auto' or 'z-index: 0', in tree order. For those with 'z-index: auto', treat the element as if it created a new stacking context, but any positioned descendants and descendants which actually create a new stacking context should be considered part of the parent stacking context, not this new one. For those with 'z-index: 0', treat the stacking context generated atomically.

**Comment by mrobinson** [comment]
This is working for me now. I suspect this was fixed when I did all the work to fix stacking order.
