### ISSUE TITLE
Make network requests cancelable

### ISSUE THREAD

**Issue by jdm** [servo/servo#4974]
Right now it is possible to "cancel" a network request by freeing the Receiver that corresponds to the network response (ie. when the Receiver goes out of scope), since that causes the network thread to panic when it tries to send on the closed channel. This won't be enough when we move to an event-based system instead of using channels - the network thread will just keep sending events to the target thread, and the target thread has no way to inform the network thread that the response is not wanted.

I propose the following:
* create a new `ResourceId` type that wraps an integer
* add a new optional `Sender<ResourceId>` argument to the `Load` message in `ControlMsg` in `resource_task.rs`
* in the load handler for `ResourceTask`, generate a new resource id for each load that requires it, and send it on the provided `Sender` if it exists
* for loads with a resource id, create a new channel and store the sender in a vector in `ResourceTask`, and pass the receiver to the loader factory
* in each loader implementation, use the new optional receiver to check if a load is supposed to be cancelled at key points (after headers are received and before each read of the response) 
* add a new `Cancel` message to `ControlMsg` in `resource_task.rs` which takes a `ResourceId`, finds the corresponding entry in the vector and sends a message on corresponding termination sender

**Comment by Manishearth** [comment]
Yeah, the Receiver hack was supposed to be a way to easily get request termination without resorting to a duplex channel or something. Now that we're moving to an event based system, we should probably not do this anymore.

**Comment by KiChjang** [comment]
How do we generate a unique integer for `ResourceId`?

**Comment by jdm** [comment]
It only needs to be unique in the resource task, so just store a next_resource_id field and increment it.

**Comment by marcusklaas** [comment]
I will give this a try.

**Comment by jdm** [comment]
Excellent!

**Comment by marcusklaas** [comment]
> in the load handler for ResourceTask, generate a new resource id for each load that requires it

How can one tell whether a load requires a resource id? When it passed `Some(Sender<ResourceId>)`?

**Comment by jdm** [comment]
Precisely.
