### ISSUE TITLE
Add optional Headers argument to Document constructor

### ISSUE THREAD

**Issue by jdm** [servo/servo#4981]
There are lots of information that documents can and should extract from HTTP headers. Right now the script task explicitly parses the Last-Modified header and calls `Document::set_last_modified`, but that should really be the responsibility of code in `document.rs` instead. We can get rid of `set_last_modified` and make the `last_modified` field immutable if we do that in the constructor itself.

**Comment by KiChjang** [comment]
I think it would be better if we pass the entire `load_response` object to the `Document` constructor. We may need to parse additional headers in the near future, and doing so would save us from parsing headers in `script_task.rs`and passing another parameter to the `Document` constructor.

**Comment by jdm** [comment]
The LoadResponse doesn't contain any other useful fields, so I don't see the benefit of that.

**Comment by mschroeder** [comment]
I would like to have a go at this issue.

**Comment by jdm** [comment]
@mschroeder Go for it!
