### ISSUE TITLE
Move body of ScriptTask::handle_mouse_move_event into a method on Document

### ISSUE THREAD

**Issue by jdm** [servo/servo#4984]
Most of this method has nothing to do with the script task, and everything to do with the document that is the target of the event. The one tricky bit is the list of mouse over targets that lives in ScriptTask; we'll probably want to pass a `RefMut<Option<Vec<JS<Node>>>>` argument to the new method.

**Comment by KiChjang** [comment]
This issue seems to be resolved. Please close.

**Comment by saneyuki** [comment]
Fixed by #4984
