### ISSUE TITLE
Support High Resolution Screens

### ISSUE THREAD

**Issue by JamieKnight** [servo/servo#500]
User Story:

As a user of a device with a high resolution display, i would expect Servo to render text sharply respecting my device density settings. For example, rendering content at 2x resolution on a Mac with HiDPI enabled.

Summery:
Support for high resolution displays is essential on mobile and increasingly on desktop operating systems. I wonder if this has been considered and if the the performance would scale in a linear or exponential fashion.

If there is some low level tasks to investigate i am happy to take a look.

Cheers,

Jamie

**Comment by lygstate** [comment]
Does this have been fixed?
It's seems that servo are using GLFW

**Comment by mbrubeck** [comment]
Yes, this is fixed.
