### ISSUE TITLE
Use opts::default_opts() in cef/core.rs

### ISSUE THREAD

**Issue by jdm** [servo/servo#5002]
We always forget to update core.rs when we add new command line options, and we shouldn't have to. core.rs should use default_opts and modify the result to make any non-default changes it requires.

**Comment by psdh** [comment]
@jdm Can you please elaborate more!

**Comment by jdm** [comment]
@psdh When we add new fields to the Opts struct in http://mxr.mozilla.org/servo/source/components/util/opts.rs, we also need to update cef/core.rs because it creates an Opts value manually. We should use the default_opts function from opts.rs instead.
