### ISSUE TITLE
Implement bindings for WebIDL typed arrays

### ISSUE THREAD

**Issue by jdm** [servo/servo#5014]
Relevant code is the `type.isSpiderMonkeyInterface()` branch in `getJSToNativeConversionInfo` in mozilla-central's Codegen.py.

**Comment by KiChjang** [comment]
I really would like to work on this because #4769 requires SpiderMonkey interface arguments, however my python is rusty and I am unsure of what the equivalent Rust code would look like when ported from Gecko's C++.

**Comment by jdm** [comment]
I looked into this with the intention of suggestion where to start, but I don't really understand what the Python code or the generated C++ for TextDecoderBinding.cpp is doing. My suggestion is to add a method to Gecko's TextDecoder.webidl that matches the method you're looking into in Servo and see what it output, then match that against the Python code in Codegen.py.

**Comment by KiChjang** [comment]
This might be useful:
https://developer.mozilla.org/en-US/docs/Mozilla/WebIDL_bindings

**Comment by KiChjang** [comment]
It is looking like that we should convert the existing structs and typedefs in `TypedArrays.h` into Rust objects. That way, we would not need to do complex FFI and have Rust compiler's ownership safety.

**Comment by KiChjang** [comment]
Fixed by #5569.

**Comment by jdm** [comment]
That's different, I'm pretty sure. `isSpiderMonkeyInterface` covers a wider set of types.

**Comment by KiChjang** [comment]
Ahh, I see what it requires now. Essentially we need to implement `ArrayBuffer`, `ArrayBufferView`, `SharedArrayBuffer`, `SharedArrayBufferView`, `TypedArray` and `SharedTypedArray`.

**Comment by KiChjang** [comment]
Gecko also has a `TypedArray.h` file, which we should port over as well. Perhaps name it `typedarray.rs` and put it under `components/script/dom/bindings`?

**Comment by jdm** [comment]
See #6779 for an attempt.

**Comment by izgzhen** [comment]
So the trouble-maker is only typed-array now or we also have some other JS object not ported yet?

I have [a personal note](https://github.com/izgzhen/gsoc-file-support/blob/master/notes/typed_array.md) on typed array's status but not knowing if this thread topic is proper for posting its content and discuss possible solutions.

**Comment by izgzhen** [comment]
One thing is that typed array blocks the progress of #10911 greatly, and I am also interested to learn how to work on it.

**Comment by izgzhen** [comment]
How about changing title to "Support bindings of typed array"?

**Comment by marmistrz** [comment]
me, @taki-jaro, @mrowqa and @xanewok will work on this issue as a student project
cc @KiChjang

**Comment by jdm** [comment]
@marmistrz I don't think that's a wise idea, as there's not a clear design that makes sense to implement yet. For #10209 you should continue to use `object` or `any` WebIDL arguments and use the the [typed array APIs](https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs) to convert the SpiderMonkey types into usable Rust types.

**Comment by Xanewok** [comment]
Yeah, we definitely intend to continue using the `object` approach for now for the functions using SpiderMonkey types.
I briefly talked about the bindings in context with the remaining WebGL functions with @KiChjang on IRC and that it'd require some work and it seemed like a nice self-contained project that'd not only help rustify the API here but in other parts, hence why we wanted to also work on that.

Do you think that's possible for us to work on, even as an exploratory work?

**Comment by KiChjang** [comment]
May I recommend trying #16678 instead? That issue is somewhat similar to this one, and @jdm has been kind enough to leave notes on how to implement/fix it.

**Comment by jdm** [comment]
The problem with doing this as exploratory work is that it really requires one of the core team members to provide a recommended implementation path, and I don't think any of us have the time that that requires right now.

**Comment by Xanewok** [comment]
Yeah, sure! Thanks for pointing it out, we'll get back when we have something :+1:

**Comment by jdm** [comment]
The infrastructure created for #16678 should make solving this issue much easier. If your group would like to add it to your thesis, that's fine by me.

**Comment by jdm** [comment]
Gecko's current support for typed array bindings relies on https://dxr.mozilla.org/mozilla-central/source/dom/bindings/SpiderMonkeyInterface.h in types like `RootedSpiderMonkeyInterface<ArrayBufferView>`. This is based on the CustomAutoRooter type from SpiderMonkey.

**Comment by Xanewok** [comment]
@jdm since `TypedArray` currently [internally holds a root guard](https://github.com/servo/rust-mozjs/blob/72d8dec5891199d3dcb20baa5d0672134eae555a/src/typedarray.rs#L69), is it necessary to also track it via CustomAutoRooter?

Would the changes needed to resolve this issue limit to generating the bindings using the already-existing rust-mozjs' `TypedArray` inside `type.isSpiderMonkeyInterface()` branch in CodegenRust.py?

**Comment by jdm** [comment]
Yes, those codegen changes to use [these types](https://github.com/servo/rust-mozjs/blob/101c6b6b58e0b7c5ed1ef2b6b676a7497f90df2f/src/typedarray.rs#L300-L320) would be enough to resolve this issue. Alternatively, it may make sense to modify the TypedArray implementation to use the CustomAutoRooter infrastructure (rather than a separate macro, for example) which may make the code generation changes more similar to the ones needed in #19644.

**Comment by Xanewok** [comment]
I believe https://github.com/servo/servo/pull/20267 fixes this issue! (Yes, I forgot to enter the fixed issue number in PR 😞 )

**Comment by jdm** [comment]
Can't wait for all of the WebIDL improvements we can make a result of that improvement!

**Comment by pshaughn** [comment]
Some code comments such as still refer to this issue, such as:
https://github.com/servo/servo/blob/5f55cd5d71df9c555fbc24777168396ddd539f28/components/script/dom/bluetoothremotegattcharacteristic.rs#L313-L314
https://github.com/servo/servo/issues/20849 is the relevant open issue for those comments.
