### ISSUE TITLE
Split kitchen-sink "dom channel" into finer-grained channels

### ISSUE THREAD

**Issue by jdm** [servo/servo#503]
Gecko suffers from a catch-all event loop that cause spec compatibility issues (such as web-visible things like `alert` and sync XHR spinning up nested event loops). We can avoid this in Servo by providing multiple channels to the script task that the event loop will prioritize in some fashion when polling for an event to handle. We will also require the ability to freeze individual channels, to enable things like sync XHR blocking page-visible events (similarly, `alert` should block page-visible changes but not block the user from interacting with the dialog). With separate channels, we can also investigate prioritization of certain types of events over others, such as user input over setTimeout. The easiest selection algorithm to start with is likely round-robin, of course.

**Comment by jdm** [comment]
This is an important step to enable synchronous, blocking operations that require nested events loops (sync XHR, alert, etc.) in order for the browser to remain responsive. See https://groups.google.com/forum/#!topic/mozilla.dev.servo/unG9GxZnpcU for more information.

**Comment by jdm** [comment]
Additionally, I think we're going to have to write our networking consumer code to always process events by enqueuing a runnable, otherwise we'll break the illusion that nested event loops are supposed to provide.

**Comment by jdm** [comment]
I envision having the following:
* a channel for events from Constellation/Compositor
* a channel for devtools communication
* one channel per HTML5 task source (DOM manipulation, user interaction, networking, timers, history traversal, etc.)

We should add APIs for dispatching events to each of these sources as necessary, rather than have users send messages directly on the Sender object.

**Comment by nox** [comment]
@jdm Ain't that done already?

**Comment by jdm** [comment]
I suppose it is. I'll file a separate issue specifically for HTML5 task sources.
