### ISSUE TITLE
RootCollection doesn't check if its SmallVec has spilled

### ISSUE THREAD

**Issue by jdm** [servo/servo#5037]
This is unsafe; RootCollection only works because it stores values on the stack, and if that silently changes we lose the safety guarantees the conservative stack scanner requires.

**Comment by JIoJIaJIu** [comment]
I'll do it

**Comment by JIoJIaJIu** [comment]
Correct me, please, if i misunderstand - On some trigger i should scan raw stack memory, try to find all rooted varialbles and raise panic! if i don't find some one?
I create
```rust
StackScanner {
    root_collection: RefCell<RootCollection>
}
```
then i should get raw pointer
```rust
&vec as * const _
```

iterate through memory and trying to cast it JSObject?
Also questions:
* I should trigger scan on root/unroot any value?
* Or i can understand that some piece of code(GC) trying to get *mut JSObject, how

Thank you

**Comment by jdm** [comment]
Sorry for the confusion - the stack scanning already occurs during GC, since it is the way that GC is implemented in SpiderMonkey. What we want to do here is figure out if adding a new root to the `RootCollection` causes the number of roots to exceed the capacity of the on-stack storage for the `SmallVec` that is in the `RootCollection`.

**Comment by SimonSapin** [comment]
Note that SmallVec has moved to https://github.com/servo/rust-selectors/blob/master/src/smallvec.rs , and might moved again into an independent library.

**Comment by JIoJIaJIu** [comment]
Is it just
```rust
 assert!(!(*roots).spilled());
```

**Comment by jdm** [comment]
Huh, I didn't realize that the spilled method was public, so that's very convenient :)

**Comment by frewsxcv** [comment]
Completed in #5166
