### ISSUE TITLE
Implement a crashtest harness

### ISSUE THREAD

**Issue by jdm** [servo/servo#5038]
Occasionally we have tests like https://github.com/servo/servo/blob/bb7621f5dc33dd5068a3a4de7cdfe3af8b3d4130/tests/content/test_trace_null.html or https://github.com/servo/servo/pull/5035#issuecomment-75608408 that don't need a reference or any other checks; we just want to make sure that they haven't crashed by the time onload occurs.

**Comment by jdm** [comment]
#5038 is another example of a crashtest-worthy test.

**Comment by jdm** [comment]
To implement this, I would just duplicate most of contenttest.rs, but take the bits of reftest.rs that turn on picture output, which will cause the tests to close on their own. Then we also need a new mach command in testing_commands.py.

**Comment by jdm** [comment]
#5482 is another example of a good test.

**Comment by ehsan** [comment]
I am (well, will be) working on this!

**Comment by Ms2ger** [comment]
I'm somewhat skeptical, fwiw. Usually (like in #5482), it'd be better to test for the expected behaviour rather than just "didn't crash".

**Comment by jdm** [comment]
#5482 is the exception here, IMO. Tests like #5472 don't have any value as reftests.

**Comment by jdm** [comment]
Unclear value here.
