### ISSUE TITLE
spurious downloading lines in mach output from builders

### ISSUE THREAD

**Issue by metajack** [servo/servo#5043]
See http://build.servo.org/builders/gonk/builds/29/steps/compile/logs/stdio for an example. Can we detect that we're not on a real terminal and then not do overwrites in that case?

**Comment by SimonSapin** [comment]
Do you mean the `Downloading Rust snapshot:` lines? We already have [such a switch](https://github.com/servo/servo/blob/a3ea3eed47713a4a6faa86c575bc2ac95c5fe135/python/servo/bootstrap_commands.py#L41-L42). They can be disabled with a `TERM=dumb` environment variable.

This switch could probably be smarter, maybe using `sys.stdout.isatty()`

**Comment by SimonSapin** [comment]
This was probably fixed in #5043, but I didn’t manage to find a newer builder log that downloads Rust. Do the builders cache Rust snapshots?

**Comment by jdm** [comment]
@larsbergstrom Do you know the answer?

**Comment by larsbergstrom** [comment]
Sadly, I believe we do not cache the Rust snapshots - they are in the build/.servo directory, and the build/ directory is blown away every time. We may want to do something similar to @Manishearth's changes to keep the .cargo directory global (https://github.com/servo/saltfs/pull/19 ) to avoid this problem.

**Comment by jdm** [comment]
```
Downloading Rust snapshot...
Extracting Rust snapshot...
Snapshot Rust ready.
```
from http://build.servo.org/builders/linux1/builds/989/steps/compile/logs/stdio

**Comment by mbrubeck** [comment]
Filed #5200 for caching Rust snapshots outside of the working dir.
