### ISSUE TITLE
Add tests for the static suite

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#5050]
It's behind a permission wall for the general public (because of copyright), but we should test on the builders that we do not break the loading of our static page suite: https://github.com/mozilla/servo-static-suite

**Comment by Ms2ger** [comment]
We shouldn't gate checkins on something you can't test unless you've got access to the secret stuff

**Comment by larsbergstrom** [comment]
@Ms2ger How is this handled on Gecko? I'm a little tired of regressing cnn/reddit/etc. Though maybe Gecko just has a large enough test suite that there is coverage for all of the features on most major sites.

**Comment by Ms2ger** [comment]
Only performance tests use copyrighted sites, and regressing those isn't reason for immediate backout.

**Comment by mrobinson** [comment]
I think it's pretty unlikely that we will be able to do this since Servo is no longer part of Mozilla.
