### ISSUE TITLE
Test-wpt should take a --release argument

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5056]
This requires changes to [run.sh](https://github.com/servo/servo/blob/master/tests/wpt/run.sh).

In case the first argument is  `--release`, instead of passing `--binary $wpt_root/../../components/servo/target/servo `, pass `--binary $wpt_root/../../components/servo/target/release/servo` to `run.py`. Use `shift` to remove the argument from the list after reading it.

To test this out, run `./mach build --release`, followed by `./mach test-wpt --release`. You can cancel it after you see a couple of Servo windows pop up.

**Comment by psdh** [comment]
fixing this :)

**Comment by Manishearth** [comment]
Oh, sorry, `acgtyrant_` is already working on this

**Comment by psdh** [comment]
oh!, was just testing it
Haha! no worries :)
