### ISSUE TITLE
Implement Document#currentScript

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5057]
Blocks #2968.

* Spec: <https://html.spec.whatwg.org/multipage/#dom-document-currentscript>, <https://html.spec.whatwg.org/multipage/#execute-the-script-block>
* Code: `components/script/dom/htmlscriptelement.rs`, `components/script/dom/document.rs`.
* Test: `html/dom/documents/dom-tree-accessors/Document.currentScript.html`.

**Comment by psdh** [comment]
I will try to fix this.

**Comment by jdm** [comment]
Looks like @luniv's got a solution.
