### ISSUE TITLE
Add more robust hostsfile parsing

### ISSUE THREAD

**Issue by gilles-leblanc** [servo/servo#5063]
Hostsfile support has been added as part of #3219. Two TODOs have also been added:

http://lxr.mozilla.org/servo/source/components/net/resource_task.rs#42
http://lxr.mozilla.org/servo/source/components/net/resource_task.rs#400

These relate to bad file path and contents. 

Additionally, other conditions should be checked for:
* comments
* mutliple hostnames for a single address

**Comment by gilles-leblanc** [comment]
I'd like to work on this.

My reasoning is that we should ignore malformed content rather than throw a panic or something similar. I would rather a browser not crash with an exception because of a single error in a hostfile. Unless all panics are caught and handled by default?

**Comment by jdm** [comment]
In this case the panics would probably take down everything. Please do work on this :)

**Comment by gilles-leblanc** [comment]
There are a lot of new tests but the cases I have added unit tests for were cases where we were throwing panics (end of line spaces, comments (whether whole line comments or end of line comments), malformed files) or lacked support (host name aliases).
