### ISSUE TITLE
test-ref should take a --release argument

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5075]
We can pass this down to the test binary which can look for the Servo binary elsewhere.

*might* be blocked on https://github.com/rust-lang/cargo/issues/691. I don't think it is.

I'm not yet sure if this is an easy bug (haven't really looked into it, since we use `cargo test` to invoke the tests, it might get complicated), but this has the potential to become one.

**Comment by psdh** [comment]
Hey!
If we want to run tests with optimizations on, then it would be blocked at rust-lang/cargo#691, won't it?
I don't quite understand this in and out, so I can't be sure.

**Comment by Manishearth** [comment]
Might want to chat with acrichto on IRC how easy that feature would be to add, or if there's a way to work around it.
