### ISSUE TITLE
scrolling broken on mac

### ISSUE THREAD

**Issue by metajack** [servo/servo#5077]
No matter which way I drag on the touch pad, no scrolling happens. I actually got one page to scroll to the bottom but it happened instantaneously and I couldn't go back.

**Comment by saneyuki** [comment]
I keep it in my mind that this has been caused when we switch to gultin for osx port.

**Comment by jdm** [comment]
I've done lots of scrolling on OS X since switching to glutin, so I'm not sure what you mean.

**Comment by saneyuki** [comment]
I commented under what @metajack says that scrolling on OSX don't take care of the behavior that is inverted since OSX 10.7 compared to other platforms.

**Comment by metajack** [comment]
The scrolling is not inverted in some way. The scrolling doesn't work *at all* in any direction. This is not "natural scrolling" or lack of same, but *no* scrolling.

**Comment by metajack** [comment]
This was fixed by #5170.
