### ISSUE TITLE
add relayout debugging

### ISSUE THREAD

**Issue by metajack** [servo/servo#5079]
We should have a debug mode which prints out a notice whenever something forces a relayout and prints the reason.

Right now if you turn on `-Z show-parallel-layout` you can see that we are re-running layout many times on page load.

**Comment by jdm** [comment]
We should add an argument to ScriptTask::force_reflow and Page::reflow, and define an enum that lists the possible reasons for initiating a reflow.

**Comment by Adenilson** [comment]
If this one is available, I would like to do it.

**Comment by jdm** [comment]
Go ahead!

**Comment by Adenilson** [comment]
There is a known issue that when you start servo, it will have reflow done 3x (I'm going to open an issue about it). It is probable it has to do with window resize events, but it got to be fixed.

**Comment by Adenilson** [comment]
For the repeated reflows #5093.

**Comment by Adenilson** [comment]
Loading a wikipedia page will point to a 'reflow storm', while resize events only happens 2x. An example: https://gist.github.com/Adenilson/19476a8b8fcc162136ce

Do you guys know why those events are being sent to ScriptTask?
