### ISSUE TITLE
mach commands should warn when it's ambiguous which binary to run

### ISSUE THREAD

**Issue by metajack** [servo/servo#5080]
There are three ways to invoke mach commands that run built binaries: no flags, `--release` given, or `--debug` given.

I think when no flags are given, we should run whichever binary actually exists. If both release and debug builds exist, we should print a warning or just show an error and halt.

Right now it is far to easy to forget and run the wrong code if you've been going back and forth between different types of builds.

**Comment by jdm** [comment]
Code: python/servo/post_build_commands.py
