### ISSUE TITLE
title slide jitter with sliderust

### ISSUE THREAD

**Issue by metajack** [servo/servo#5083]
When loading a deck with lots of images, the title slide will jitter around during page load, after everything is painted. The more images you add, the longer it will jitter.

You can reproduce this by loading https://github.com/metajack/sliderust/blob/master/applicative2015.html

**Comment by metajack** [comment]
This can also be reproduced by holding left arrow (which the JS uses to go backwards a slide).

**Comment by mrobinson** [comment]
I'm not seeing this one.
