### ISSUE TITLE
Organize reftest list alphabetically and make the tidy script check it

### ISSUE THREAD

**Issue by jdm** [servo/servo#5092]
http://mxr.mozilla.org/servo/source/tests/ref/basic.list
http://mxr.mozilla.org/servo/source/python/tidy.py

**Comment by jdm** [comment]
```
12:49 <SimonSapin> crowbot: ping pcwalton PRs seem to routinely conflict with each other because they add reftests at the end of the list. Should we keep the list alphebatically ordered or something to mitigate?
12:52 <jack> SimonSapin: that sounds quite reasonable.
12:54 <jdm> agreed
12:54 <jdm> we can even make the tidy script check it
```

**Comment by SimonSapin** [comment]
:+1:

**Comment by SimonSapin** [comment]
Is it better to have tidy or reftest.rs check this?

**Comment by Ms2ger** [comment]
tidy, IMO

**Comment by gilles-leblanc** [comment]
I'd like to do this one.

**Comment by bvleur** [comment]
Maybe merge conflicts can be avoided with `.gitattributes` file and an entry like:
```
basic.list merge=union
```

(based on [a tip I've read on the GitLab blog comments](https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/#comment-1846082669))
