### ISSUE TITLE
Constellation creates a new script task for same-origin navigations

### ISSUE THREAD

**Issue by jdm** [servo/servo#5095]
I suspect we want to be conservative here and use the same script task instead. Upside is fewer distinct JSRuntime instantiations, which will be a memory win. If we correctly freeze pages in the session history, I don't think the extra pressure on the event loop will be a big deal. This might also be necessary to correctly model the semantics of same-origin navigation in iframes, which would need to be part of the parent's script task. I'm not sure if we handle that correctly at the moment.

**Comment by asajeffrey** [comment]
Closed by #14211.
