### ISSUE TITLE
Implement a generic LRU cache, use in ResourceTask.

### ISSUE THREAD

**Issue by brson** [servo/servo#51]
ResourceTask doesn't do any caching, but it should. Both in-memory and on-disk caches should use the LRU-SP algorithm.

**Comment by Yoric** [comment]
Is this bug still valid? If so, what needs to be done? Use `util::cache::LRU` in `ResourceTask`?

**Comment by jdm** [comment]
A generic cache in ResourceTask is not desirable right now. I have a branch that implements an HTTP cache; when that ends up merging, we can look into particular caching strategies for it.

**Comment by doraemon96** [comment]
What is the status of this issue? What has been done and what has to be done?

**Comment by jdm** [comment]
As filed, this issue does not really make any sense at this time.
