### ISSUE TITLE
Implement float attribute in CSSStyleDeclaration

### ISSUE THREAD

**Issue by jdm** [servo/servo#5101]
The comment at http://mxr.mozilla.org/servo/source/components/script/dom/webidls/CSSStyleDeclaration.webidl#83 says it needs BinaryName, which we just got support for in #5094.

**Comment by nox** [comment]
float is a type in WebIDL so there is a parse error. Isn't BinaryName for the name in the bindings' code and not for the name in the WebIDL interface?

**Comment by jdm** [comment]
We can call it something other othat `float` and add a BinaryName annotation to make it match.
