### ISSUE TITLE
Replace uses of accumulating fold with sum

### ISSUE THREAD

**Issue by jdm** [servo/servo#5109]
There are several callers of `fold` today that start with an initial value of 0 then add all the elements of a vector to get the total. This would be much easier to read if it used [AdditiveIterator::sum](http://doc.servo.org/std/iter/trait.AdditiveIterator.html#tymethod.sum) instead. We may need to implement that trait for the `Au` type for some of the callers.

**Comment by SimonSapin** [comment]
I’m not convinced that slightly nicer code with `sum` instead of `fold` is worth implementing `AdditiveIterator` for random types like `LogicalMargin<Au>`.

**Comment by SimonSapin** [comment]
See http://logs.glob.uno/?c=mozilla%23servo#c179291
