### ISSUE TITLE
Fill in default type parameter for PartialEq on JSRef

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5112]
Currently, out [implementaion of `PartialEq` for `JSRef`](https://github.com/servo/servo/blob/master/components/script/dom/bindings/js.rs#L730) is:

```
impl<'a, T> PartialEq for JSRef<'a, T> {
  fn eq(&self, other: &JSRef<T>) -> bool {
    self.ptr == other.ptr
  }
}
```

Here, the type parameter to `PartialEq` [defaults to `Self`](http://doc.servo.org/core/cmp/trait.PartialEq.html). This means that we cannot compare two `JSRef` objects with different lifetimes.

We need to change this so that it implements `PartialEq<JSRef<'b, T>>` instead, and audit cases where we've `.clone()`d `JSRef` objects to circumvent this.

**Comment by Manishearth** [comment]
@KiChjang want to work on this?

**Comment by KiChjang** [comment]
Oh! So this is where the black magic happened. I can try, but I'll need some time to go through the whole concepts of lifetimes. Some literature would be helpful.

**Comment by Manishearth** [comment]
http://doc.rust-lang.org/nightly/book/ownership.html

**Comment by KiChjang** [comment]
I'm encountering #3960 while browsing through the code. Is it the same issue that we have here?

**Comment by jdm** [comment]
That seems likely.
