### ISSUE TITLE
rename layout::util to something more sensible

### ISSUE THREAD

**Issue by metajack** [servo/servo#5120]
It's causing us to import the util crate as servo_util, which is ugly.

Really they should probably both be renamed, but let's start with the easier case.

**Comment by Adenilson** [comment]
It seems that there is also another util module in gfx/text.

**Comment by jdm** [comment]
I propose splitting it into `data.rs`, `node.rs`, and moving the ToGfxColor trait and impl to `display_list_builder.rs`.

**Comment by iamdanfox** [comment]
Can I have a stab at this? It sounds like splitting up a file and renaming stuff around the codebase should be straightforward!
