### ISSUE TITLE
reddit toolbars overflowing in static suite

### ISSUE THREAD

**Issue by metajack** [servo/servo#5148]
![blink vs. servo](https://cloud.githubusercontent.com/assets/28357/6494560/ddb584a6-c27f-11e4-9a0a-42d6ff0798d7.png)

**Comment by jdm** [comment]
Looks like the `overflow: hidden` on `#sr-header-area .sr-list` isn't working right.

**Comment by frewsxcv** [comment]
![](https://cloud.githubusercontent.com/assets/416575/7338375/d69c820c-ec17-11e4-8076-59809dce645a.gif)

This is no longer an issue
