### ISSUE TITLE
Fix warnings in tests/reftests.rs

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#5158]
E.g. use indexing with ranges instead of `slice_from`, etc.

**Comment by jdm** [comment]
`touch tests/reftest.rs && ./mach test-ref` will cause the warnings to appear.

**Comment by wldcordeiro** [comment]
I'll take this issue.

**Comment by saneyuki** [comment]
@wldcordeiro this already has been taken by @PeterReid.
