### ISSUE TITLE
Fix warnings in contenttest.rs

### ISSUE THREAD

**Issue by jdm** [servo/servo#5159]
`touch tests/contenttest.rs && ./mach test-content` will cause the warnings to appear.

**Comment by ehegnes** [comment]
I'd like to contribute to this, if I may.

Many of the warnings can be squelched by specifying compiler features. Warnings produced by the use of some deprecated functions from `std::os` can be squelched by explicitly allowing deprecated code. I am unsure, however, if this is what you mean by 'fix warnings'. It seems as though much of the code would need to be rewritten if one is to prefer the use of the `std::env` functions over their deprecated `std::os` counterparts.

Is it suitable to simply squelch the warnings by allowing deprecated code, or would the use of `std::env` be preferred?

**Comment by metajack** [comment]
We prefer you update the code if it's a deprecated feature and the alternative exists.

Also, contribute away! Lots of these warnings appear after a rust upgrade as it is pretty tedious to do this warning free. Cleaning up is much, much appreciated!

**Comment by ehegnes** [comment]
Great! I'll start on updating the deprecated code and post here if I have any further concerns.

**Comment by ehegnes** [comment]
Although I believe this will fix the issue currently, the alpha docs specify changes to functions and types in `std::env` that will eventually require this code to be changed. Specifically, the conversion from OsString to String will be unnecessary (and thus wrong), as `std::env::args()` will contain String types already. I suppose there isn't much to do about that for now, but I felt compelled to document this concern.
