### ISSUE TITLE
Display lists should contain glyph buffers rather than text runs

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#5162]
We should move the logic in `ScaledFontExtensionMethods::draw_text()` farther up the pipeline and store `AzGlyphBuffer`s in the display list instead of `TextRun` instances. This would make serialization of display lists much easier, because then text runs would be entirely local to the layout thread/process. The layout thread would do the serialization during display list building and all the paint threads would have to do would be to pass the buffer straight to Azure.

**Comment by pyfisch** [comment]
they do now
