### ISSUE TITLE
Display lists shouldn't contain Images directly

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#5163]
We're going to be sending display lists in multiprocess Servo, and serializing `Image`s over the wire is going to be too slow. Instead of putting `Image` objects directly into display lists, they should instead have some sort of identifier (perhaps a URL?) whereby the display list can reference an image and the paint context can simply fetch it from the image cache task.

**Comment by Adenilson** [comment]
If this one is available, I would like to do it.

**Comment by pcwalton** [comment]
I've got a patch to do this already. Will post later today/tomorrow.

**Comment by Adenilson** [comment]
Coolio.

**Comment by nox** [comment]
@pcwalton The bytes are now in an `IpcSharedMemory` thing, is that enough?

**Comment by pcwalton** [comment]
Let's consider this closed.
