### ISSUE TITLE
Implement blur filter in Servo

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#5186]
Test case: https://gist.github.com/Adenilson/5edd7c45e5f33ac48924

**Comment by yodalee** [comment]
May I try this?

**Comment by jdm** [comment]
I think @Adenilson was planning to work on this.

**Comment by yodalee** [comment]
QAQ

**Comment by Adenilson** [comment]
Yep, I'm working on it.

**Comment by Adenilson** [comment]
We can close this, as #5546 has landed.
