### ISSUE TITLE
Image tag won't respect size attributes

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#5191]
Using the following  `<img width="100px" height="100px" src="rust.png">` the image won't be resized (the image original size is 1024x1024).

**Comment by jdm** [comment]
It looks to me like the layout code should be obtaining the content attributes on the element either before or after processing the related CSS properties (presumably the spec makes clear which order is correct).

**Comment by Adenilson** [comment]
![screen shot 2015-03-10 at 5 48 19 pm](https://cloud.githubusercontent.com/assets/959744/6588356/ceb85492-c74d-11e4-9cf1-ef88fb087e74.png)
![screen shot 2015-03-10 at 5 49 10 pm](https://cloud.githubusercontent.com/assets/959744/6588357/cec1f4e8-c74d-11e4-88b6-6f50aa680c54.png)

**Comment by jdm** [comment]
ie. we're missing width and height getters for LayoutHTMLImageElementHelpers.

**Comment by Adenilson** [comment]
It would be nice to work on this, as it touches DOM and Layout. :-)

**Comment by jdm** [comment]
Go for it.

**Comment by eefriedman** [comment]
This works... sort of.  Specifying an explicit width works in general... but the original testcase in this bug still doesn't work because https://github.com/servo/servo/blob/2091aafcfb32dffba836fde2ccddf4a183e88302/components/layout/fragment.rs#L355 uses the wrong algorithm to parse the length.

**Comment by nox** [comment]
This was fixed.
