### ISSUE TITLE
querySelectorAll doesn't work on elements populated via innerHTML assignment

### ISSUE THREAD

**Issue by dmarcos** [servo/servo#5199]
@jdm Is this a known problem?

I added a test that illustrates the problem in the branch below:

https://github.com/dmarcos/servo/tree/query-selector-all-issue

querySelectorAll returns 0 elements when it should return 2.

To run the test you can do:

`./mach run ./tests/content/test_parentNode_querySelectorAll.html`

A stand alone example can be found below. Gecko returns the result I expect.

https://dl.dropboxusercontent.com/u/4710867/v3brainstorming/servo/qseltest.html

Everything comes down to the following code:

```js
var docfrag = document.createDocumentFragment();
var div = document.createElement("div");
div.id = "foo";
div.className = "myClass";
div.innerHTML = '<canvas></canvas>' +
                '<canvas></canvas>';
docfrag.appendChild(div);
console.log("Should select 2 canvas elements, querySelectorAll returns: " +
            docfrag.querySelectorAll("canvas").length); 
```

**Comment by jdm** [comment]
The innerHTML setter is not implemented right now, so this is expected behaviour: #849
