### ISSUE TITLE
Improve thread name for page load task

### ISSUE THREAD

**Issue by jdm** [servo/servo#5215]
We get output in the logs like ` 0:19.53 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:45115) "thread 'fetch for Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("localhost"), port: Some(8000), default_port: Some(80), path: ["encoding", "resources", "single-byte-raw.py"] }), query: Some("label=asmo-708"), fragment: None }' panicked`. We really need to change the name in ScriptTask::start_page_load to use `url.serialize()` instead, which will make the result much more reasonable.

**Comment by mattnenterprise** [comment]
I would like to take this one. How do I reproduce the output you have above?

**Comment by jdm** [comment]
@mattnenterprise An easy way to make it reproduce is to add a `panic!()` inside the block at http://mxr.mozilla.org/servo/source/components/script/script_task.rs#1203 .
