### ISSUE TITLE
FTBFS: Build failed on Ubuntu 14.04 64bit

### ISSUE THREAD

**Issue by BlueT** [servo/servo#5216]
compiling servo with command `./mach build` and got lots of 'undefined reference' error in GrGLPath.cpp and ld error with collec2.

/home/matthew/workspace/servo/components/servo/target/deps/libazure-cc187b961189251d.rlib(r-skia-GrGLProgram.o): In function `GrGLProgram::GrGLProgram(GrGpuGL*, GrGLProgramDesc const&, GrGLUniformManager*, GrGLShaderBuilder::GenProgramOutput const&)':
GrGLProgram.cpp:(.text+0x263): undefined reference to `SkMatrix::InvalidMatrix()'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `servo`.

To learn more, run the command again with --verbose.
Build completed in 34.74s

**Comment by BlueT** [comment]
Full log with the command
matthew@0xB1uE7:~/workspace/servo$ LANG=C ./mach build|tee build.log

https://gist.github.com/BlueT/efc526ec40d9cba14419

**Comment by jdm** [comment]
Huh, I have a VM with Ubuntu 14.04 64bit and don't see this :/

**Comment by BlueT** [comment]
Any info I can provide to help on debugging this?

BTW, it starts with a
error: linking with `cc` failed: exit code: 1
which seems familiar with this issue? https://github.com/servo/servo/issues/3330

**Comment by BlueT** [comment]
this is the verbose version of build log
https://gist.github.com/BlueT/1cecd916ba28c9bb7566

**Comment by jdm** [comment]
Yeah, I just set up a VM from scratch and saw no errors. I guess I'd suggest making sure that you've installed the prerequisites from README.md, and try `./mach clobber && ./mach build` if that makes no difference?

**Comment by BlueT** [comment]
prerequisites are all installed, ./mach doesn't have a command called 'clobber'.

matthew@0xB1uE7:~/workspace/servo$ LANG=C sudo apt-get install curl freeglut3-dev \
>     libfreetype6-dev libgl1-mesa-dri libglib2.0-dev xorg-dev \
>     msttcorefonts gperf g++ cmake python-virtualenv \
>     libssl-dev libbz2-dev libosmesa6-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'ttf-mscorefonts-installer' instead of 'msttcorefonts'
cmake is already the newest version.
freeglut3-dev is already the newest version.
g++ is already the newest version.
gperf is already the newest version.
libbz2-dev is already the newest version.
python-virtualenv is already the newest version.
ttf-mscorefonts-installer is already the newest version.
curl is already the newest version.
libfreetype6-dev is already the newest version.
libglib2.0-dev is already the newest version.
libssl-dev is already the newest version.
xorg-dev is already the newest version.
libgl1-mesa-dri is already the newest version.
libosmesa6-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

matthew@0xB1uE7:~/workspace/servo$ git rev-parse HEAD
389338c28f75808e68cd635211687718362f8e7d

matthew@0xB1uE7:~/workspace/servo$ git pull
Already up-to-date.

matthew@0xB1uE7:~/workspace/servo$ ./mach clobber
It looks like you are trying to run an unknown mach command: clobber

Did you want to run any of these commands instead: clean?

Run |mach help| to show a list of commands.

matthew@0xB1uE7:~/workspace/servo$ cat ./rust-snapshot-hash 
80627cd3cc4099b76cb2fb26ebe2f2f8a6c2335e/rustc-1.0.0-dev

matthew@0xB1uE7:~/workspace/servo$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

matthew@0xB1uE7:~/workspace/servo$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by BlueT** [comment]
I did a `./mach clean` and build it again, now it build completed. But many functions seems broken.
ex, Ctrl--, Backspace, Shift-Backspace, Esc

Trying to rm -rf, clone, and rebuild again

**Comment by jdm** [comment]
Interesting. I wouldn't expect a rebuild to make a different in terms of key input handling, though.

**Comment by BlueT** [comment]
Seems works now, except Ctrl--.
Characters are square blocks, but that's another bug. thanks.
