### ISSUE TITLE
Canvas not rendered as a block level element

### ISSUE THREAD

**Issue by dmarcos** [servo/servo#5224]
@jdm If we set the display attribute to ```block``` the canvas elements are not rendered:

```css
canvas {
  display: block;
}
```
I have a PR that seems to fix the issue: https://github.com/servo/servo/pull/5220

This simple test case illustrates the problem:

https://dl.dropboxusercontent.com/u/4710867/v3brainstorming/servo/buggetcontext.html

The canvas is not rendered on servo but displayed as you would expect on gecko. I investigated the bug by following the reflow, sizing and display list creation of Image and Canvas elements set as block level elements. In the following point the code paths diverge:

https://github.com/servo/servo/blob/master/components/layout/block.rs#L1142

Image elements pass the ```is_replaced_content``` test and canvases don't so the function ```assign_replaced_block_size_if_necessary``` that calculates the size of the fragment is never called. The canvas holds a 0 size and never displayed. Considering canvas in the implementation of ```is_replaced_content``` function solves the issue:

https://github.com/servo/servo/pull/5220/files#diff-f488bae1b885cd00ad5abe2ebb8631a0R739

My understanding of the reflow and display list build process is pretty slim. I don't know if my approach is a appropriate and but the patch makes the [test case] (https://dl.dropboxusercontent.com/u/4710867/v3brainstorming/servo/buggetcontext.html) work as you expect

**Comment by mbrubeck** [comment]
Fixed by #5220
