### ISSUE TITLE
Support more console information log levels

### ISSUE THREAD

**Issue by jdm** [servo/servo#5232]
Currently we support sending Console::Log messages to the attached developer tools. We should send the messages from the other methods in Console as well - http://mxr.mozilla.org/servo/source/components/script/dom/console.rs#34 . Additionally, we can refactor the `ConsoleMsg` type to be a structure containing the extra fields, and add a new enum for just the logging level - this will avoid duplicating that data in each variant.

cc @hsvalava - is this something your group would like to work on? It's a small, related task that will help you get used to writing more Rust code.

**Comment by hsvalava** [comment]
I see what you're saying, I had the same idea when we added fields to LogMessage. Sure, we can take this up. Thanks!

**Comment by jdm** [comment]
Fantastic :)
