### ISSUE TITLE
Content frame tree architecture improvements

### ISSUE THREAD

**Issue by jdm** [servo/servo#5236]
This is the metabug to aggregate potential avenues for improving the content tree architecture (ie. Page, browser contexts, navigation in script/; FrameTree, PipelineId in compositing/).

**Comment by KiChjang** [comment]
Relevant explanation of pipelines and frame trees: `https://air.mozilla.org/2013-intern-kuehn/`

**Comment by asajeffrey** [comment]
IRC conversation: http://logs.glob.uno/?c=mozilla%23servo&s=27+May+2016&e=27+May+2016#c442625

**Comment by nox** [comment]
Can this be closed?

**Comment by jdm** [comment]
Yep.
