### ISSUE TITLE
Consolidate all concepts of loading/navigating in top-level and child contexts

### ISSUE THREAD

**Issue by jdm** [servo/servo#5237]
I think there's value in implementing page navigation in a browsing context-agnostic fashion. I want the script task to be notified of a navigation for a particular pipeline, and hide all the details of whether it's an iframe being navigated. 

Blocks #5236.

**Comment by nox** [comment]
Cc @asajeffrey

**Comment by asajeffrey** [comment]
@jdm: I think we can close this now?

**Comment by jdm** [comment]
Yeah, there's nothing particularly specific here.
