### ISSUE TITLE
Make BrowserContext spec-compliant

### ISSUE THREAD

**Issue by jdm** [servo/servo#5238]
In practical terms, this means the frame tree on the script side should consist of BrowserContext values, with navigations causing the active document to be replaced. Any concept of a bfcache in the script task should store Document pointers.

Blocks #5236.

**Comment by benschulz** [comment]
I read "make `BrowserContext` spec-compliant" as "make `BrowserContext`s persist across document loads within them". I.e. `HTMLFrameElement` and `HTMLIFrameElement` each own an unchanging `BrowserContext`, which points to the document it's currently displaying.

How is that supposed to work w.r.t. cross-origin/different eTLD frames though? As far as I understand `Document`s should not escape their script task. Therefore the `BrowserContext` of a frame with a cross-origin `src` can't point to the document it's displaying.

What am I missing/misunderstanding?

**Comment by jdm** [comment]
Yes, we need to introduce a concept of opaque, proxy browsing contexts for cross-origin documents per #5242.

**Comment by KiChjang** [comment]
I believe we have since renamed the struct as `BrowsingContext`.

**Comment by jdm** [comment]
Much of this is addressed by #15120.

**Comment by KiChjang** [comment]
Should this be closed then?

**Comment by jdm** [comment]
I guess so!
