### ISSUE TITLE
Support synchronous loads of about:blank

### ISSUE THREAD

**Issue by jdm** [servo/servo#5240]
The way this interacts with the general architecture improvement for content navigation is unclear, but building this is from the ground up would be valuable.

Blocks #5236.

**Comment by Ms2ger** [comment]
FWIW: <https://github.com/servo/servo/compare/master...Ms2ger:empty-iframe-load>

**Comment by jdm** [comment]
My related exploratory work was https://github.com/jdm/servo/commit/e8aa1e10c3be1de6aeaee7c5a4ddb50e94f97b81.

**Comment by Ms2ger** [comment]
#3924
