### ISSUE TITLE
Add references to cross-origin script tasks to the page tree

### ISSUE THREAD

**Issue by jdm** [servo/servo#5242]
When we have a cross-origin iframe, the page tree should contain a reference to its event loop, along with uniquely-identifying features. This will allow the implementation of APIs like postMessage, and set the stage for the implementation of #3939.

Blocks #5236.

**Comment by KiChjang** [comment]
Does this mean that a page should have ways of getting child script tasks? Or is it the other way around - we eliminate child script tasks and only refer to the parent page's script task?

**Comment by jdm** [comment]
Basically, yes. This ties in a bit with the changes in #8658 which add a concept of local vs. remote windows/documents. It's not yet totally clear to me how this should interact with the tree of Page objects. It's possible that Page should become nothing more than a wrapper around a `BrowsingContext` object.

**Comment by jdm** [comment]
#10630 is the design I had in mind for this. It's not really worth merging until we actually create instances of the Remote ones.

**Comment by KiChjang** [comment]
Do we already have this?

**Comment by jdm** [comment]
No.

**Comment by asajeffrey** [comment]
We have part of this in #15358.

**Comment by nox** [comment]
@asajeffrey What's missing?

**Comment by jdm** [comment]
Actual communication with the cross-origin script threads.

**Comment by asajeffrey** [comment]
@jdm: we have postMessage, is there other communication you had in mind?

**Comment by jdm** [comment]
Whoops, I guess not.
