### ISSUE TITLE
Can't click buttons on Facebook

### ISSUE THREAD

**Issue by jdm** [servo/servo#5279]
STR:
1) visit facebook.com or m.facebook.com
2) type in login credentials
3) try to click log in button or press enter

We should figure out what's going wrong here.

**Comment by jdm** [comment]
At least on m.facebook.com it's an `<input type="submit">`.

**Comment by glennw** [comment]
This *might* be caused by https://github.com/servo/servo/pull/5270

**Comment by nox** [comment]
Is this still true?

**Comment by jdm** [comment]
Nope.
