### ISSUE TITLE
Move the profilers into their own crate and rename lots of related things

### ISSUE THREAD

**Issue by nnethercote** [servo/servo#5283]
The time and memory profilers are currently in the `util` crate, which isn't a great place for them, both logically and w.r.t. compile times. I'm proposing a crate/module rearrangement, and also a bunch of renamings for names that are currently annoyingly long. I'm putting it up for comment before I go to the effort of making all the changes.

Basically...

- Add a new crate, `prof`, which has two modules, `time` and `mem`.
  - _Rationale_: these things aren't very `util`-like. It seems reasonable to
    put them together. The names are all short, as is Rust style.

- The existing `util::memory` crate remains, but it renamed `util::mem` and it only holds the `SizeOf` trait and related stuff.
  - _Rationale_: The new name is consistent with other module names, in Rust and Servo. And `SizeOf` is separate from the memory profiler, and is
    `util`-like (e.g. hopefully it'll end up as a built-in trait in Rust
    eventually).
  - _Optional_: rename as `util::mem` for more consistency?

- `SizeOf` renamed as `HeapSizeOf`, and `size_of_excluding_self` as `heap_size_of_children`.
  - _Rationale_: `SizeOf` is too close to Rust's `size_of`; `HeapSizeOf` makes
    it clearer that it's about measuring the heap memory usage. And
    `heap_size_of_children` because it's better to describe what should be
    measured, rather than what shouldn't be measured.
  - _Note_: is `children` the best word? Does it make it sound like it's only
    relevant for trees?

- All the things called `MemoryReport*` become `Report*`.
  - _Rationale_: the `Memory` is implicit, because they're in the `prof::mem`
    module, and there is no other kind of report.

- All the things called `MemoryProfiler*` become `Prof*`, and `TimeProfiler*` become `Prof*`.
  - _Rationale_: current names are too long, and including `Time` and `Mem` in
    the new names would be redundant w.r.t. the module name.
  - _Note_: this might cause name conflicts in some modules (e.g.
    if they use both `prof::time::Prof` and `prof::mem::Prof`). They could be imported as `TimeProf`
    and `MemProf` where necessary, or just module-qualified.

- The `SystemMemoryReporter` also moves into the `prof::mem` crate, possibly in a `system_reporter` submodule.
  - _Rationale_: It is related to the memory profiler but also distinct from
    the main profiler code.

The following table summarizes the changes.
```
-----------------------------------------------------------------------------
BEFORE                              AFTER
-----------------------------------------------------------------------------
util::memory                        util::mem
- heap_size_of                      - heap_size_of
- SizeOf                            - HeapSizeOf
  - size_of_excluding_self            - heap_size_of_children

util::memory                        prof::mem
- MemoryProfilerChan                - ProfChan
- MemoryReport                      - Report
- MemoryReportsChan                 - ReportsChan
- MemoryReporter                    - Reporter
- MemoryProfilerMsg                 - ProfMsg
  - {R,UnR}egisterMemoryReporter      - {R,UnR}egisterReporter 
- MemoryProfiler                    - Prof
- ReportsForest                     - ReportsForest (unchanged)
- ReportsTree                       - ReportsTree   (unchanged)

util::memory                        prof::mem::system_reporter[?]
- SystemMemoryReporter              - SystemReporter

util::time                          prof::time
- TimeProfilerChan                  - ProfChan
- TimerMetadata                     - TimerMetadata (unchanged)
- Formatable                        - Formattable [spelling!]
- TimeProfilerMsg                   - ProfMsg
- TimeProfilerCategory              - ProfCategory
- TimeProfilerBuckets               - ProfBuckets
- TimeProfiler                      - Prof
- TimerMetadataFrameType            - TimerMetadataFrameType (unchanged)
- TimerMetadataReflowType           - TimerMetadataReflowType (unchanged)
- ProfilerMetadata                  - ProfMetadata
```
Let the bikeshedding commence!

**Comment by jdm** [comment]
I'd prefer the longer `profile` crate name, and probably the full word in the type names too. `heap_size_of_reachable`, perhaps? `heap_size_of_owned`?
