### ISSUE TITLE
Implement CanvasRenderingContext2d.drawImage fo HTMLImage as ImageSource

### ISSUE THREAD

**Issue by dmarcos** [servo/servo#5290]
@jdm Is it ok if I work on this as a follow up of https://github.com/servo/servo/issues/4784?

**Comment by jdm** [comment]
Of course!

**Comment by dmarcos** [comment]
@jdm Hi there! I'm back with more newbie rust code. Slowly getting into the groove :)

https://github.com/servo/servo/pull/5433

Special attention has to be paid to the part where retrieve the image data from cache:

https://github.com/servo/servo/pull/5433/files#diff-73749ed78090d6d7ef64586d558e0850R226

**Comment by jdm** [comment]
Fixed by #5433.
