### ISSUE TITLE
Move unit tests to dedicated crates

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#5291]
Running `rustc --test` on a large crate (which is what `mach test-unit` currently does, through `cargo test`) often takes as much time or more as building the crate in the first place. This is especially silly for crates that happen to not have any unit tests.

By moving the unit tests we do have and disabling `rustc --test` on "normal" crates, we should be able to reduce the build+test time significantly.

Cargo has `test = false` and `doctest = false` [configuration keys](http://doc.crates.io/manifest.html#configuring-a-target) that can be set in the `[lib]` section of a `Cargo.toml` file.

**Comment by plasmachannel** [comment]
Can I take this one?  I have almost no understanding of Cargo so I figure this bug might force me to get familiar with cargo and become familiar with good testing in servo

**Comment by SimonSapin** [comment]
Go ahead! Cargo documentation is at http://doc.crates.io/ , but feel free to ask questions here or on IRC.

**Comment by SimonSapin** [comment]
@plasmachannel are you still working on this?

**Comment by plasmachannel** [comment]
Probably won't get to look at it for a while, the amount of free time I have ha a shrunk significantly.  

So the answer is no until further notice
