### ISSUE TITLE
Add a devtools_chan method to GlobalRef

### ISSUE THREAD

**Issue by jdm** [servo/servo#5309]
We want to make it possible to retrieve the appropriate sender for the devtools task from any window or worker global. This should remove the need to match on the specific global type in the worker constructor.

cc @thiagopnts

**Comment by thiagopnts** [comment]
Any ideas on how to get the PipelineId in the nested worker scenario?

**Comment by jdm** [comment]
Pass the pipeline in from the global in the constructor?

**Comment by jdm** [comment]
By which I mean, we should start storing the related pipeline in the DedicatedWorkerGlobal, and add a method to GlobalRef to retrieve the pipeline.

**Comment by jwilm** [comment]
@jdm should this issue be closed?

**Comment by jdm** [comment]
Yep!
