### ISSUE TITLE
Document::Title and Document::SetTitle do not yet support root SVG Namespace

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#5315]
There are specific rules for how to handle these methods when working with a root SVG namespace. From what I understand of this code, it doesn't look like we currently do the right thing.

[Relevant code](https://github.com/servo/servo/blob/5e4d80fa3a291c77879c9798329410eb87b4a344/components/script/dom/document.rs#L1108-L1165)

[Relevant portion of the spec](https://html.spec.whatwg.org/#document.title)

**Comment by nox** [comment]
I fixed that in #5768.

**Comment by frewsxcv** [comment]
@nox Thanks!
