### ISSUE TITLE
OSX trackpad scrolling is too sensitive

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#5320]
When browsing on OSX and scrolling with the trackpad via two-finger scrolling, I've noticed the sensitivity feels way to high and it only takes me a few millimeters of finger-trackpad movement to take me flying across the page. From what I've seen, it looks like there's no central way to change the sensitivity of the trackpad scrolling for apps in OSX, so this might just require a change to a constant somewhere.

:apple: + :point_down: :point_down: + :arrow_right: = :racehorse: :dash:

**Comment by jdm** [comment]
Agreed. This is almost certainly something that requires changing in glutin: https://github.com/tomaka/glutin/blob/master/src/cocoa/mod.rs#L303

**Comment by jdm** [comment]
I wonder if this text from [the docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSEvent_Class/#//apple_ref/occ/instm/NSEvent/scrollingDeltaY) is relevant:
```
This is the preferred method for accessing NSScrollWheel delta values. When hasPreciseScrollingDeltas returns NO, multiply the value returned by this method by the line or row height. Otherwise scroll by the returned amount. 
```
I also can't figure out the relationship between scrollingDeltaY and deltaY: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSEvent_Class/#//apple_ref/occ/instm/NSEvent/deltaY

**Comment by jdm** [comment]
Then again, perhaps it's just our code in http://mxr.mozilla.org/servo/source/ports/glutin/window.rs#183 that needs to change.

**Comment by frewsxcv** [comment]
Should this issue have the `P-mac` label instead of the `A-mach` label? :P

**Comment by jdm** [comment]
Ha, yes.

**Comment by frewsxcv** [comment]
This is not an issue for me anymore.
