### ISSUE TITLE
Consider attempting to rerasterize when pinch zooming

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#5325]
Seems to me that there's little harm in attempting to rerasterize when pinch zooming, since it happens in a background thread pool. It might be too slow, depending on how complex the page is, but if it is then we can just fall back to rendering a blurry page. We already have similar code that attempts to rasterize when scrolling and only renders checkerboards if it's too slow, so we could just adopt that to zooming. This would allow us to have non-blurry pinch zooming, which would be neat.

**Comment by mrobinson** [comment]
Going to close this since we no longer use a tiling compositor.
