### ISSUE TITLE
Document why calls to methods like force_relayout are required

### ISSUE THREAD

**Issue by jdm** [servo/servo#5329]
For htmltextareaelement.rs and htmlinputelement.rs, it's not always clear at first glance why we need to explicitly mark the node as dirty and force a reflow to take place. We should document these reasons.

**Comment by saneyuki** [comment]
@jdm Josh, is this a your reminder? (implicitly assigned to you?)

**Comment by jdm** [comment]
Yes, unless anybody else wants to.

**Comment by mrobinson** [comment]
We no longer call `force_reflow` in these files after #34599.
