### ISSUE TITLE
Add profiling to the script event loop

### ISSUE THREAD

**Issue by jdm** [servo/servo#5331]
Sometimes there are really big backlogs for the script event loop, according to @nnethercote. It would be valuable to have some kind of script task profiler that categorizes events and can show where the time is being spent.

**Comment by jdm** [comment]
Here's my plan:
* make an enum in ScriptTask with all of the possible classifications
* add the enum as an argument for RunnableMsg, to force any Runnable users to categorize their runnables
* pass each about-to-be-processed event to a categorization function
* store the category and current time in locals
* processing the event, then get the difference between the stored time and the current time
* store the duration in a profiling map in ScriptTask
* every time it's time to report, iterate through the map, print out the total time spent in each category, then reset the map to empty

The script task can store the last time the profiling data was reported, and check if it's been long enough that a new report should be generated. No need to use another task here.

**Comment by jdm** [comment]
This should also be gated behind a debug command line arg: http://mxr.mozilla.org/servo/source/components/util/opts.rs#134

**Comment by pkondzior** [comment]
I have two questions:
1. Is HashMap with categorization value as Key and total profile time spent as Value appropriate here ?
2. How often profiler should report informations stored in ScriptTask profiler data ?

**Comment by jdm** [comment]
Yes, I think a hashmap makes sense, and having it report every 10 seconds sounds sensible to me.

**Comment by pkondzior** [comment]
Ok, I will take this task.

**Comment by jdm** [comment]
Fantastic :)

**Comment by jdm** [comment]
@pkondzior Are you still working on this?

**Comment by benschulz** [comment]
If this is still of interest, I'd take it.

**Comment by jdm** [comment]
@benschulz Absolutely!

**Comment by benschulz** [comment]
Beyond categorizing runnables, I've singled out SendEvent which – at least in debug builds – takes up a significant amount of time. Other than that I'm lumping events together by source (Constellation, Devtools, etc). Were you looking for any more categories than that? Or should I leave that up to whomever ends up profiling?

**Comment by jdm** [comment]
That seems like a reasonable starting point!

**Comment by benschulz** [comment]
Sorry, I forgot to use an issue closing commit message in #7341.
