### ISSUE TITLE
ReplaceChild in DOM misses mutation records when replacement is a DocumentFragment

### ISSUE THREAD

**Issue by ChrisParis** [servo/servo#5336]
ReplaceChild doesn't handle DocumentFragments right. If we replaceChild where the new node is a DocumentFragment containing `<div id="foo"></div>`, then a subsequent getElementById("foo") will not find the node. The spec looks wrong to me. In http://dom.spec.whatwg.org/#concept-node-replace, Steps 12-13 queue mutation records for the children of the DocumentFragment, but the insert in Step 11 would have already removed the children of the DocumentFragment (per https://dom.spec.whatwg.org/#concept-node-insert, Step 5). The servo code appears to be faithful to the spec, but the spec looks wrong.

**Comment by annevk** [comment]
Could you file an issue against the DOM standard? It seems like those steps need to be reversed.

**Comment by ChrisParis** [comment]
Issue filed. https://www.w3.org/Bugs/Public/show_bug.cgi?id=28330

**Comment by annevk** [comment]
Excellent, I recommend just going ahead and patching servo as it might take a little while before I get to that. We're in the process of changing the source format of the specification.
