### ISSUE TITLE
Make the MozBrowserEvent message take an enum instead of String + Option<String>

### ISSUE THREAD

**Issue by jdm** [servo/servo#5352]
This is both the one in ConstellationControlMsg and the other in constellation_msg::Msg. Type-safe interfaces are always preferable; the dispatch_mozbrowser_event method in htmliframeelement.rs can convert from the enum to the appropriate string values.

**Comment by aweinstock314** [comment]
I'm working on this.

**Comment by jdm** [comment]
@aweinstock314 I suggest building on top of #5339.
