### ISSUE TITLE
Move devtools to std::net.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5355]
* [x] #5294 Move devtools TCP acceptor into a separate thread
* [ ] rust-lang/rust#23696 TcpStream::duplicate

**Comment by Ms2ger** [comment]
WIP: https://github.com/servo/servo/compare/devtools

**Comment by aweinstock314** [comment]
I'm working on this.

**Comment by jdm** [comment]
Sorry for the confusion, @aweinstock314. I just approved merging #5356 :(

**Comment by aweinstock314** [comment]
Acknowledged. Should I close #5357?

**Comment by jdm** [comment]
I think so.
