### ISSUE TITLE
Servo leaks pages when traversing links

### ISSUE THREAD

**Issue by aweinstock314** [servo/servo#5364]
To reproduce: start servo with `./mach run http://xkcd.com --devtools 6000`, click the previous link several times, and connect devtools from a firefox instance to servo (Tools -> Web Developer -> Connect...). The entire history of pages traversed show up as seperate tabs to devtools, and if one is attached to it's possible to inspect the DOM tree, indicating that servo still has those structures active.

**Comment by jdm** [comment]
It's not really a leak, per se. It's the way that we support going backwards and forwards in history instantly - Firefox has a similar thing called the bfcache. This issue is more about keeping the devtools notified about page navigations that occur in the script task.

**Comment by jgraham** [comment]
So, do you want a new issue for the fact that our bfcache has unlimited size (which is somewhat less viable ;)

**Comment by jdm** [comment]
Filed #6160.

**Comment by asajeffrey** [comment]
Closed by #14312
