### ISSUE TITLE
servo panics while trying to load a non existent file.

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#5365]
== Steps ==

1) run: ./mach run ~/this-file-doesnt-exists.html

2) Watch servo crash and burn e.g. https://gist.github.com/Adenilson/4a539ca73039f092e347

== What is the expected output ==

It should load a "not found page" or at least not crash.

**Comment by jdm** [comment]
Relevant problem code is in parse_progress in script/parse/html.rs.

**Comment by Adenilson** [comment]
Coolio, will do this next.
