### ISSUE TITLE
Pressing ` crashes

### ISSUE THREAD

**Issue by jruderman** [servo/servo#5367]
thread 'ScriptTask' panicked at 'unknown char code for GraveAccent', /Users/jruderman/code/servo/components/script/dom/keyboardevent.rs:354

(testing with servo-shell)

**Comment by jdm** [comment]
This should be BackQuote, according to https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3Events-code.html#key-alphanumeric-writing-system.

**Comment by leavengood** [comment]
Do you want to change the constellation message constant from GraveAccent to Backquote, or just map it to the right keys in keyboardevent.rs?

**Comment by jdm** [comment]
Let's just map it for now.

**Comment by leavengood** [comment]
OK, I'll work on this.
