### ISSUE TITLE
Cursor movements causes text to move up and down

### ISSUE THREAD

**Issue by jruderman** [servo/servo#5369]
1. https://en.wikipedia.org/wiki/Spin_isomers_of_hydrogen.
2. Move the mouse cursor over the page

Result: everything below the table of contents repeatedly shifts up and down by a pixel or two

**Comment by frewsxcv** [comment]
A GIF of the issue described above

![untitle2](https://cloud.githubusercontent.com/assets/416575/7900315/b19825e0-071c-11e5-8aef-a934e57bd574.gif)

**Comment by sviter** [comment]
No such issue for me on latest servo nightly
