### ISSUE TITLE
Use Content-Type in image decoding

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#5371]

**Comment by kmcallister** [comment]
See also #3144.

**Comment by jdm** [comment]
You're going to need to provide a bit more information here if the E-easy label is going to remain.

**Comment by kmcallister** [comment]
I'll add more info when my image decoding PR lands :) I was just reserving a number for a FIXME.

**Comment by Ms2ger** [comment]
Spec?

**Comment by jinankjain** [comment]
Could someone help me out to fix this bug or some more details about the bug how to fix it

**Comment by jdm** [comment]
@jinankjain It's not possible to work on this until another @kmcallister creates and merges a forthcoming PR, unfortunately.

**Comment by mt2d2** [comment]
@kmcallister did the blocking pr ever merge? Is this still a valid issue to help out with?

**Comment by nox** [comment]
Closing for lack of details.
