### ISSUE TITLE
code_value values for alphabetic characters are wrong

### ISSUE THREAD

**Issue by jdm** [servo/servo#5374]
According to https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3Events-code.html#key-alphanumeric-writing-system they should be KeyN, not Key::N.

code: components/script/dom/keyboardevent.rs

**Comment by leavengood** [comment]
Since I'm already familiar with that file I can do this too.

**Comment by jdm** [comment]
Go for it!
