### ISSUE TITLE
Implement platform-specific clipboard support

### ISSUE THREAD

**Issue by jdm** [servo/servo#5376]
Typing in URLs for https://github.com/glennw/servo-shell is a pain. We should implement support for pasting from the clipboard.

**Comment by jdm** [comment]
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/PasteboardGuide106/Introduction/Introduction.html#//apple_ref/doc/uid/TP40008099

**Comment by jdm** [comment]
http://sourceforge.net/p/xclip/code/HEAD/tree/trunk/xclip.c

**Comment by aweinstock314** [comment]
I'm working on the X11 part of this.
