### ISSUE TITLE
assertion failed: glyph_count <= char_max in harfbuzz.rs

### ISSUE THREAD

**Issue by rillian** [servo/servo#5391]
$ ./mach run --release https://xiph.org/
thread 'LayoutWorker worker 1/6' panicked at 'assertion failed: glyph_count <= char_max', /home/giles/mozilla/servo/components/gfx/text/shaping/harfbuzz.rs:283
stack backtrace:
   1:     0x7ff1940b4162 - sys::backtrace::write::h754dbf5d2d3172ebPBA
   2:     0x7ff1940c7042 - panicking::on_panic::hdb9e837ac064f8afiHJ
   3:     0x7ff1940976a9 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ
   4:     0x7ff193b6a07c - rt::unwind::begin_unwind::h6541087076354549683
   5:     0x7ff193b9f939 - text::shaping::harfbuzz::Shaper.ShaperMethods::shape_text::ha79e67cf062b808aEAh
   6:     0x7ff193b9c82f - font::Font::shape_text::h67bde3e196ac97b3d5d
   7:     0x7ff193bc98f2 - text::text_run::TextRun::break_and_shape::h9586a28f98855547Npi
   8:     0x7ff193ba0a9b - text::text_run::TextRun::new::hb07c694b8eb48c554oi
   9:     0x7ff1933e0477 - text::TextRunScanner::scan_for_runs::h339c5b6f028f409bams
  10:     0x7ff1933eb5ae - construct::FlowConstructor<'a>::build_flow_for_block_starting_with_fragments::h8369ee25223871b2sed
  11:     0x7ff1933f5f91 - construct::FlowConstructor<'a>::build_flow_for_block::hc4260ae76d12618edhd
  12:     0x7ff1933f70d2 - construct::FlowConstructor<'a>::build_flow_for_nonfloated_block::haa0693ed5a97040dokd
  13:     0x7ff1933ef1b4 - construct::FlowConstructor<'a>.PostorderNodeMutTraversal::process::h037c65cd45061d0eKNd
  14:     0x7ff19348ffa3 - traversal::ConstructFlows<'a>.PostorderDomTraversal::process::ha4ee257d65e4042aoWs
  15:     0x7ff19348f91a - parallel::RecalcStyleForNode<'a>.ParallelPreorderDomTraversal::run_parallel::hbf90a39fb64511da7Ep
  16:     0x7ff19348fee5 - parallel::recalc_style::h4331c27923f68991xFp
  17:     0x7ff19347044f - thunk::F.Invoke<A, R>::invoke::h13175084191170610560
  18:     0x7ff1934284c0 - rt::unwind::try::try_fn::h5594514527973537586
  19:     0x7ff1940d0e78 - rust_try_inner
  20:     0x7ff1940d0e65 - rust_try
  21:     0x7ff193428c4f - thunk::F.Invoke<A, R>::invoke::h9836903258989347247
  22:     0x7ff1940b7135 - sys::thread::thread_start::h04d056c6180f4496s8E
  23:     0x7ff192d8b529 - start_thread
  24:     0x7ff19187b22c - clone
  25:                0x0 - <unknown>

**Comment by jdm** [comment]
Sounds like #5230 and #2704.

**Comment by rillian** [comment]
Indeed. closing as a dup.
