### ISSUE TITLE
Implement Location.pathname

### ISSUE THREAD

**Issue by jdm** [servo/servo#5397]
Spec: https://url.spec.whatwg.org/#dom-urlutils-pathname
Code: components/script/dom/location.rs, components/script/dom/webidls/Location.webidl

Needed for #5395.

**Comment by yodalee** [comment]
Can I take this. Write a easy issue to gain confidence OAO.

**Comment by jdm** [comment]
Go for it :)

**Comment by frewsxcv** [comment]
This was fixed in #5423 

Thanks for your contribution @yodalee :sparkles:
