### ISSUE TITLE
"Not Acceptable" error when fetching ReactJS test server

### ISSUE THREAD

**Issue by jdm** [servo/servo#5399]
After running `grunt test --debug` and watching the server start, I see:
```
Error: Not Acceptable
    at Object.exports.error (/Users/jdm/src/react/node_modules/grunt-contrib-connect/node_modules/connect/lib/utils.js:63:13)
    at /Users/jdm/src/react/node_modules/grunt-contrib-connect/node_modules/connect/lib/middleware/directory.js:112:38
    at ReaddirReq.Req.done (/Users/jdm/src/react/node_modules/populist/node_modules/graceful-fs/graceful-fs.js:143:5)
    at ReaddirReq.done (/Users/jdm/src/react/node_modules/populist/node_modules/graceful-fs/graceful-fs.js:90:22)
    at Object.oncomplete (fs.js:108:15)
```
Something about our HTTP fetch is disliked by the server.

Blocks #5398

**Comment by jdm** [comment]
This appears to be the `connect` middleware complaining that our preferred media type is unacceptable, which is based on our Accept header.

**Comment by jdm** [comment]
Probably because we don't have one!

**Comment by jdm** [comment]
By contrast, Firefox sends an Accept header like `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`

**Comment by jdm** [comment]
We should add one in the HTTP loader for now (just asking for `text/html;q=0.9,*/*;q=0.8`,

**Comment by jdm** [comment]
Code: components/net/http_loader.rs

**Comment by bdero** [comment]
I'm currently working on this.

**Comment by bdero** [comment]
Looks like it works!
![](http://i.imgur.com/TQ8rcTe.png)

**Comment by jdm** [comment]
Hooray!
