### ISSUE TITLE
Implement Navigator.appVersion

### ISSUE THREAD

**Issue by jdm** [servo/servo#5409]
Spec: https://html.spec.whatwg.org/multipage/webappapis.html#dom-navigator-appversion
Code: components/script/dom/navigator.rs, components/script/dom/webidls/Navigator.webidl

Blocks #5406. It's used in the v8-raytrace.html test.

**Comment by jdm** [comment]
Alternatively we could try to get it removed from the test.

**Comment by deokjinkim** [comment]
I want to work on this stuff. I have a question about it. ^^
When I check "navigator.appVersion" on firefox, it returns "5.0 (X11)".
Servo also returns same string with firefox? or returns "4.0" according to spec? or servo has another application version?

**Comment by jdm** [comment]
I would go with 4.0.

**Comment by Ms2ger** [comment]
Follow the spec
