### ISSUE TITLE
Only try to scan text runs for block flows that contain inline child flows

### ISSUE THREAD

**Issue by sethfowler** [servo/servo#543]
Once we have shifted text run scanning into the box building phase, we will be walking the children of every block flow to check if any are inline flows that need scanning. This is unnecessary; we only need to do this for block flows that contain inline child flows. However, there's no quick way to check that at the moment.

**Comment by mbrubeck** [comment]
Text scanning is now done only when flushing a non-empty set of inline fragments to a flow.
