### ISSUE TITLE
Implement WebIDL sequences

### ISSUE THREAD

**Issue by jdm** [servo/servo#544]
It looks like these can just be vectors; nothing really special here.

**Comment by boghison** [comment]
Isn't this already implemented?

**Comment by Ms2ger** [comment]
No; variadic arguments are implemented, but not sequences. The correct implementation requires a SpiderMonkey upgrade, though.

**Comment by boghison** [comment]
@Ms2ger why does it show up in the bindings table then?

**Comment by Ms2ger** [comment]
I added that row pre-emptively

**Comment by ecoal95** [comment]
I think I'm going to take this soon since I need sequence return values in order to implement `WebGLRenderingContext#getSupportedExtensions`

**Comment by Ms2ger** [comment]
Feel free to start on sequence return values, but sequence arguments are blocked on #6150 .

**Comment by frewsxcv** [comment]
Update on this: #6150 (the SpiderMonkey upgrade) landed a little over a month ago so this should be ready to be worked on

**Comment by Ms2ger** [comment]
Sequence arguments in Gecko use `JS::ForOfIterator`. We need something equivalent, but I'm not quite sure what the best design is.

**Comment by Ms2ger** [comment]
We have http://doc.servo.org/js/jsapi/struct.ForOfIterator.html now.

@wenderen, want to try your hand at this?

**Comment by wenderen** [comment]
sure!

**Comment by ecoal95** [comment]
I could implement return values (sorry, I saw the issue in my email and remembered about it, didn't see it was assigned).
I won't have the time to implement sequence arguments though.

I can close the PR if you want, maybe you find it useful @wenderen.
Sorry again :/

**Comment by wenderen** [comment]
no problem! I think you should continue with the PR. I can implement sequence arguments if you won't have the time.
