### ISSUE TITLE
Implement named access to NamedNodeMap

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5454]
Blocks #5395.

* Spec: <https://dom.spec.whatwg.org/#interface-namednodemap>.
* Code: `components/script/dom/namednodemap.rs`, `components/script/dom/webidls/NamedNodeMap.webidl`.
* Test: to be written.

**Comment by Ms2ger** [comment]
This is the real cause of the exception in #5396.

**Comment by Manishearth** [comment]
(@nox is working on this)
