### ISSUE TITLE
Layout tasks should know their URL and iframe-ness instead of having the script task pass it in on every reflow

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#5466]
Because reflow might happen without the script task knowing.

**Comment by ChimeraCoder** [comment]
Is there a spec for this? @kenpratt and I were looking for low-hanging fruit, and this seemed do-able.

**Comment by jdm** [comment]
@ChimeraCoder The Reflow struct currently contains this information (http://mxr.mozilla.org/servo/source/components/script/layout_interface.rs#102). We want to move that information into the LayoutTask constructor instead. Does that make sense?

**Comment by ChimeraCoder** [comment]
Oh yeah - sure, we'll take a stab at this!
