### ISSUE TITLE
Re-enable tests that require an iframe load event

### ISSUE THREAD

**Issue by jdm** [servo/servo#5468]
http://mxr.mozilla.org/servo/search?string=disabled%3A%20iframe

This will require getting rid of the "disabled" lines and adding text expectations that match the output of running the re-enabled tests (see virtually any other .ini file for example, such as http://mxr.mozilla.org/servo/source/tests/wpt/metadata/dom/nodes/Document-getElementsByTagName.html.ini?force=1).

**Comment by zerokarmaleft** [comment]
Hi, taking a stab at this.

**Comment by jdm** [comment]
Thanks!
