### ISSUE TITLE
Can't log in to Bugzilla

### ISSUE THREAD

**Issue by jdm** [servo/servo#5473]
I get a

```
The password must contain at least one:
* UPPERCASE letter
* lowercase letter
* digit
You must request a new password in order to log in again.
```

error, which is pretty weird.

**Comment by Manishearth** [comment]
Glutin might be munching a special character there. Type your password in a usual text input field and check if something is missing.

**Comment by dralley** [comment]
Can it still be reproduced?

**Comment by jdm** [comment]
No.
