### ISSUE TITLE
Use std::process::exit in constellation.rs.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5478]
Added in https://github.com/rust-lang/rust/pull/23907

**Comment by wenderen** [comment]
Apart from the [exit via unsafe](https://github.com/servo/servo/blob/master/components/compositing/constellation.rs#L414), are there any other parts of constellation.rs that could use `std::process::exit`?

**Comment by Ms2ger** [comment]
I was referring to that one call, yes

**Comment by wenderen** [comment]
Ah, OK. Thanks. I'm leaving this then. It would make for a good entry bug for someone else.

**Comment by frewsxcv** [comment]
Here's an updated link to the line that needs to be changed:

https://github.com/servo/servo/blob/2df88ee4b97fbc347dc99869b6989605760b662e/components/compositing/constellation.rs#L539

**Comment by Wafflespeanut** [comment]
@Ms2ger That commit has been merged. You might wanna update that comment of yours :)

**Comment by Yoric** [comment]
Is this bug still open?

**Comment by frewsxcv** [comment]
@Yoric Yep! The line I linked to in my last comment still needs to be updated

**Comment by Yoric** [comment]
Ok, then I'll try and do it.
