### ISSUE TITLE
Support multiple root pages in a script task

### ISSUE THREAD

**Issue by jdm** [servo/servo#5481]
This would be required to properly support multiple tabs viewing pages that are same-origin - in order to support things like spec-compliant StorageEvent dispatch, the pages would need to be part of the same script task, but they don't have a hierarchical relationship like same-origin iframes.

Blocks #5236.

**Comment by jdm** [comment]
@bholley suggests that this isn't necessary, as only frames which are part of the same tree require synchronous access. Any two toplevel browsing contexts that are same origin can still be run in parallel and in isolation, and any two frames that are same-origin to each other but with a cross-origin frame interposed between them (ie. a.com contains b.com contains a.com) can also be run in isolation.

**Comment by bholley** [comment]
This isn't quite true, due to window.open etc. The spec lays it out nicely here: https://html.spec.whatwg.org/#groupings-of-browsing-contexts

**Comment by asajeffrey** [comment]
Closed by #14211 and the PRs which led up to it.
