### ISSUE TITLE
Make all applicable supported properties animatable

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#5494]
Many of these are easy. See the list of properties here: http://dev.w3.org/csswg/css-transitions/#animatable-css

Notice how `animation.rs` handles `top`, `right`, `bottom`, and `left`, and add cases for the missing properties. New length properties should be trivial to handle; the trickiest property to handle will be transitions on `transform`.

**Comment by jseaton** [comment]
Anyone mind if I nab at least the easy cases for this? Good chance to get my feet wet.

**Comment by jdm** [comment]
Go for it!

**Comment by jdm** [comment]
@pcwalton Could you make a list of the properties that still remain, and decide if this still classifies as an easy issue?

**Comment by jooert** [comment]
I'm not @pcwalton, but I think @jseaton has implemented animations for all properties listed in the spec, as far as I can tell from #5704; so this should be closed? :smiley:

**Comment by jdm** [comment]
Yeah, we'll open new issues for anything that's missing.
