### ISSUE TITLE
console.log should print all its arguments

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#5495]
There's no spec, but I think it's what [all other browsers do](https://developer.mozilla.org/en-US/docs/Web/API/Console/log).

**Comment by jdm** [comment]
This will require addressing the note at http://mxr.mozilla.org/servo/source/components/script/dom/webidls/Console.webidl#14 and updating the implementation in `components/script/dom/console.rs`.

**Comment by aneeshusa** [comment]
Hey, I'd love to give this a try! I'm new to Rust, though, and I don't see any way to do varargs in Rust; how would we handle an arbitrary number of arguments?

**Comment by jabbrass** [comment]
I also was interested in taking a crack at this, when I asked in IRC what it would take to use an arbitrary number of args, all I got was that I could try a slice. Not much in the documentation makes reference to slices except that you can create them from arrays... so not much to go on there...

I'm assuming that the solution is not something manual/limited like:
16   void debug(DOMString message1, DOMString message2, DOMString message3, DOMString message4);
17   void info(DOMString message1, DOMString message2, DOMString message3, DOMString message4);
18   void warn(DOMString message1, DOMString message2, DOMString message3, DOMString message4);
19   void error(DOMString message1, DOMString message2, DOMString message3, DOMString message4);

**Comment by aneeshusa** [comment]
Yeah, I figured in the Rust code you'd need to take some sort of collection as the only arg. In that case, I would appreciate some pointers on how to handle the webidl, because in javascript we still want to use varargs, and I assume we'll need to specify exactly how to do the transform.

**Comment by jdm** [comment]
Sorry I wasn't clear - WebIDL variadic arguments are expressed like so: http://mxr.mozilla.org/servo/source/components/script/dom/webidls/TestBinding.webidl#305 . The corresponding Rust method is passed a vector, like so: http://mxr.mozilla.org/servo/source/components/script/dom/testbinding.rs#326

**Comment by Ms2ger** [comment]
This is now documented: <http://doc.servo.org/script/dom/bindings/index.html#rust-reflections-of-webidl-types>.
