### ISSUE TITLE
Make tidy complain if the Cargo.lock files are incompatible

### ISSUE THREAD

**Issue by jdm** [servo/servo#5497]
I'm having trouble articulating the things in particular we want to check, but I want to prevent problems like https://github.com/servo/servo/pull/5433#issuecomment-89082407 upfront. If you could look at commits and see if there was a change to a Cargo.lock file but no change to the other ones, that would be useful.

**Comment by kmcallister** [comment]
This can also check for multiple versions of a library within a single build.

It should be easy to use the same TOML parser as Cargo itself.

**Comment by Ms2ger** [comment]
#3360
