### ISSUE TITLE
Rapid resizing leads to a laggy, bouncing, animation

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5499]
STR:

(Happens on both dev and release builds)
- Open about-mozilla.html on Servo (I'm on Linux)
- Use the gripper on the corner of the window to resize it. Resize in and out multiple times, in fast succession. The content should start bouncing in and out with a lag to your resizing

Expected:

Once you stop, the animation should converge monotonically to the size of the window; quickly

Observed:

The content continues to bounce/pulsate for quite a while before settling down.

It seems like we're stacking up reflow events or something?

Copying @zmike's testcase over from #6090

> - Load http://s27.postimg.org/vqbtrolyr/servo.jpg
> - Grab window edge to engage resize mode
> - Wildly flail mouse arm for 10-15 seconds
> - Release mouse button
> 
> At this point, Servo will continue to perform each resize action triggered during step 3 on the contents despite the window no longer being resized.

**Comment by Manishearth** [comment]
cc @glennw @pcwalton

**Comment by Manishearth** [comment]
This is still happening, apparently.

**Comment by cmr** [comment]
Can still repro: https://files.octayn.net/servo-resize.ogv

**Comment by nox** [comment]
This doesn't seem to be true anymore.
