### ISSUE TITLE
Iframe.contentWindow always returns null

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5500]
Testcase:

```
<html>
<head>
</head>
<body>
<iframe src='bar.html' id='foo'></iframe>

(bar.html is just an empty file on the same domain)
<script>
var ifr = document.getElementById('foo')
alert(ifr.contentWindow)
</script>
</body>
```

On running through `gdb` it seems like `children` [here](https://github.com/servo/servo/blob/master/components/script/dom/htmliframeelement.rs#L219) is an empty vector.

This happens to iframes created from source, from `innerHTML`, and from `createElement()`

cc @glennw @mbrubeck

**Comment by Manishearth** [comment]
Update: this turns out to be because iframe loading is async, apparently

However, `i = document.createElement('iframe'); document.body.appendChild(i); i.contentWindow` works in Firefox, but not in Servo (still gives null)

**Comment by magcius** [comment]
Right. It seems that the creation of the frame's document and window is deferred until the content is fetched -- and if no src is ever set, no content is ever fetched.

If we set src to blank.html and instead fetch the contentWindow after a timeout, then it works fine.

According to https://html.spec.whatwg.org/multipage/embedded-content.html#the-iframe-element , iframes without a src should have the src "about:blank", which is an immediately-available resource that can never asynchronously load.

**Comment by jdm** [comment]
Yes, sync about:blank is tracked at #5240.

**Comment by Manishearth** [comment]
@sole has a nice example on #7162.

Perhaps we should make the contentwindow getter block until the subpage exists? Have some sort of mutexy thing on the iframe that is locked when the fetch starts, and `.contentWindow` will block until it finishes.

**Comment by jdm** [comment]
No, we should just implement synchronous about:blank rather than hacking around the lack of it. That's #5240.

**Comment by Manishearth** [comment]
That's only for iframes without a src. What about iframes with a src that haven't loaded yet?

**Comment by jdm** [comment]
Same deal. All iframes start with about:blank and then navigate to the src url.

**Comment by Ms2ger** [comment]
#3924
