### ISSUE TITLE
Remove the ability to provide multiple URLs to Servo

### ISSUE THREAD

**Issue by jdm** [servo/servo#5520]
It's just confusing and it usually doesn't work (it triggers assertions in the constellation). Why would you want to load a succession of pages without waiting for them to complete loading? It's pretty silly.

Code: http://mxr.mozilla.org/servo/source/components/util/opts.rs, http://mxr.mozilla.org/servo/search?string=opts.urls

**Comment by Manishearth** [comment]
I didn't even know this was possible. Kill it with fire!

**Comment by jagtalon** [comment]
@jdm I'm pretty new to this but I was wondering if that meant changing `pub urls: Vec<String>` to `pub url: String`, etc.?

**Comment by jagtalon** [comment]
I'd like to give this a shot.
