### ISSUE TITLE
dom::bindings::error::Error constructors are not consistently named

### ISSUE THREAD

**Issue by nox** [servo/servo#5521]
Some constructors (NamespaceError, NoModificationAllowedError, TypeError) include the word "Error" while all others don't.

**Comment by Manishearth** [comment]
Relevant code: https://github.com/servo/servo/blob/master/components/script/dom/domexception.rs#L18

I would lean on removing the `Error`, since enums are namespaced.

**Comment by ehegnes** [comment]
Should the `Error` suffix only be removed from the inconsistent contents of `enum Error` in `dom::bindings::error`, as the issue indicates, or should the `Error` suffix also be removed from the contents of `enum DOMErrorName` in `dom::domexception`?

**Comment by jdm** [comment]
According to http://heycam.github.io/webidl/#dfn-DOMException and the implementation of DOMException::Name, the names of the DOMErrorName variants should not be changed.

**Comment by Manishearth** [comment]
My bad, I meant https://github.com/servo/servo/blob/master/components/script/dom/bindings/error.rs#L26
