### ISSUE TITLE
Consider opting-out of safety assertions when a thread is panicking

### ISSUE THREAD

**Issue by jdm** [servo/servo#5537]
There are a number of places in the script crate where there are assertions inside destructors that relate to rooting or cleaning up memory. In the case where the thread is already panicking and the invariants don't necessarily hold, these assertions just cause a double panic and make the output more confusing. It might be worth checking `thread::panicking()` before performing them.

**Comment by nox** [comment]
We fixed many of these on a per-assertion basis whenever double panics were found in practice, and no one is tracking this. Closing.
