### ISSUE TITLE
Make `Metadata.content_type` use hyper's ContentType

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5538]
[`Metadata`](http://doc.servo.org/net_traits/struct.Metadata.html) has a ContentType field, which is currently an `Option<(String, String)>`. We should probably be using an [`Option<ContentType>`](http://hyperium.github.io/hyper/hyper/header/struct.ContentType.html).

Relevant code: https://github.com/servo/servo/blob/master/components/net_traits/lib.rs#L107 (changing it will probably throw up a couple of compile errors elsewhere which will need to be updated too)

**Comment by boghison** [comment]
I want to take this!

**Comment by Manishearth** [comment]
Sure! Let me know here or in IRC if you need help!

**Comment by boghison** [comment]
@Manishearth What should I do with the content_type in document?

**Comment by Manishearth** [comment]
It's an `Option<DOMString>`, seems like we want a preparsed value there. That seems okay.
