### ISSUE TITLE
Make mouse_over_targets a RootedVec

### ISSUE THREAD

**Issue by jdm** [servo/servo#5539]
`Vec<JS<T>>` is unsafe, and we can do better now.

Code: components/script/dom/document.rs

**Comment by boghison** [comment]
Hmm, I am not quite familiar with the custom types that servo uses. How would one go about using iterators with RootedVec (since the current code uses iterators)?

**Comment by jdm** [comment]
RootedVec is just a wrapper for Vec, and it dereferences to the underlying vector. That means that all of the regular methods for vector objects should continue to work.

**Comment by boghison** [comment]
@jdm Can I give it a try?

**Comment by jdm** [comment]
Absolutely!
