### ISSUE TITLE
Make Temporary::root take &self

### ISSUE THREAD

**Issue by jdm** [servo/servo#5540]
Right now calling `root` on a value of `Temporary<T>` consumes it. There are times when this is undesirable, and it makes the code more complex to work around it.

Code: components/script/dom/bindings/js.rs

**Comment by aneeshusa** [comment]
I'd love to give this a try.

**Comment by jdm** [comment]
Go for it!

**Comment by frewsxcv** [comment]
This can be closed now that #5550 has merged
