### ISSUE TITLE
Process NewSession and DeleteSession commands

### ISSUE THREAD

**Issue by jdm** [servo/servo#5554]
https://github.com/jgraham/webdriver-rust/blob/master/src/command.rs#L13

This is how every new webdriver connection will begin. The proper response should be returned (https://github.com/jgraham/webdriver-rust/blob/master/src/response.rs#L7) with a unique session id, and we should store a hashtable of known sessions in the `Handler` struct in `components/webdriver_server/lib.rs`. When a session is deleted, it should be removed from the table.

**Comment by jdm** [comment]
@jgraham, what's the json value in the NewSessionReponse supposed to be?

**Comment by jgraham** [comment]
It's a capabilities dictionary. Unfortunately the spec doesn't (yet!) actually say what's supposed to be in that dictionary. This is something that will be fixed soon. For now I think it's a reasonable start to just return an empty dictionary.

FWIW I started working on this issue a bit, but if someone comes along and takes it I'm very happy to build on their work instead :)

**Comment by jgraham** [comment]
Oh and fwiw, I think only allowing one session per servo instance is quite acceptable to begin with (and maybe always). The whole "session" concept is really aimed at cases where you have a single proxy controlling a pool of browser instances, rather than at the browsers themselves.

**Comment by jdm** [comment]
Covered by #5610.
