### ISSUE TITLE
Process the Get command

### ISSUE THREAD

**Issue by jdm** [servo/servo#5556]
This either requires direct access to a script task or the constellation. I'm inclined to use the latter for now - the webdriver initialization will need to wait until there's a constellation available (just slightly later in `components/servo/lib.rs`), and then the ConstellationChan can be passed to start_server. I suggest adding a `GetRootPipeline` message to `constellation_msg::Msg` that can return the pipeline that controls the root frame for the constellation, so the webdriver server can then send a `LoadUrl` message for that pipeline.

**Comment by boghison** [comment]
I might take this, the webdriver crate's code is pretty straightforward :)

**Comment by jdm** [comment]
Go for it!

**Comment by boghison** [comment]
How can I test my code?

**Comment by jgraham** [comment]
So I had already made a bit of a start on this, which is now pushed to https://github.com/jgraham/servo/commit/aeef1cc79c4194565c77f6e019f10684a8d535d4

It may need a bit of an adjustment to use the latest rev of webdriver-rust (I had a local override so I guess my Cargo.toml is wrong).

**Comment by jgraham** [comment]
OK, so I added the code above as a PR in #5610

**Comment by jdm** [comment]
Let's open new issues for anything remaining here.
