### ISSUE TITLE
Element::get_attribute_by_name should call parsed_name itself.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5561]
That's what <https://dom.spec.whatwg.org/#concept-element-attributes-get-by-name> does. It's better to match the spec's API's more closely.

Please also add that spec link to the doc comment for `get_attribute_by_name`.

#5490 adds a new caller, so please wait until that lands.

**Comment by Ms2ger** [comment]
And remove the spec link above the implementation of `get_attributes`; it shouldn't be there.

**Comment by mskrzypkows** [comment]
I'd like to take this.

**Comment by nox** [comment]
The same should probably be done for remove_attribute_by_name.

**Comment by mskrzypkows** [comment]
In spec (https://dom.spec.whatwg.org/#concept-element-attributes-remove-by-name) is written, we should use ```get_attribute_by_name``` in ```remove_attribute_by_name```, I think it's another issue.
