### ISSUE TITLE
Error building for the first time [wheezy, rustc 1.0.0-beta (9854143cb 2015-04-02)]

### ISSUE THREAD

**Issue by soul268** [servo/servo#5565]
Steps:
1. Installed prerequisites 
sudo apt-get install curl freeglut3-dev \
>     libfreetype6-dev libgl1-mesa-dri libglib2.0-dev xorg-dev \
>     msttcorefonts gperf g++ cmake python-virtualenv \
>     libssl-dev libbz2-dev libosmesa6-dev

2. git clone https://github.com/servo/servo
3. cd servo
4. Runnig ./mach build produces error:
Usage: git submodule [--quiet] add [-b branch] [-f|--force] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] update [--init] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--] [<path>...]
Error running mach:

    ['build']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '['git', 'submodule', '--quiet', 'sync', '--recursive']' returned non-zero exit status 1

  File "xxx/servo/python/servo/build_commands.py", line 48, in build
    self.ensure_bootstrapped()
  File "./python/servo/command_base.py", line 227, in ensure_bootstrapped
    subprocess.check_call(["git", "submodule", "--quiet", "sync", "--recursive"])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by Ms2ger** [comment]
Update your git install.

**Comment by soul268** [comment]
Installing git from wheezy-backports solved this issue
replace git 1:1.7.10.4-1+wheezy1 (using .../git_1%3a1.9.1-1~bpo70+2_amd64.deb)

Thanks!
