### ISSUE TITLE
Reenable /dom/nodes/getElementsByClassName-31.htm

### ISSUE THREAD

**Issue by jdm** [servo/servo#5580]
It was disabled before we support iframe load events. Now that we support them, we should run the test.

http://mxr.mozilla.org/servo/source/tests/wpt/metadata/dom/nodes/getElementsByClassName-31.htm.ini will need to be updated the with the expected test results after removing the `disabled:` line.

**Comment by josiahdaniels** [comment]
I'll do this one.

**Comment by jdm** [comment]
Great!

**Comment by josiahdaniels** [comment]
@jdm Sorry, but I'm kinda new to git. Now that the change has been merged into master what happens to this issue? Do I close it?

**Comment by jdm** [comment]
Yep! In the future you can add "Fixes #NNN" to the commit message and it will be closed automatically.
