### ISSUE TITLE
Add a command-line option to disable style sharing

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#5581]
The style sharing cache is an important but fragile optimization. Bugs in style sharing are often the cause of layout issues. It can be useful to disable style sharing to test whether this is the case.

We should add an option in [`util::opts`](https://github.com/servo/servo/blob/3fb666cf606f835a9ab9165339e34023ab83a358/components/util/opts.rs) to disable style sharing.  Then add code in [`share_style_if_possible`](https://github.com/servo/servo/blob/3fb666cf606f835a9ab9165339e34023ab83a358/components/layout/css/matching.rs#L562) (or related code) to make it never share styles when this option is set.

**Comment by pgonda** [comment]
What should the command-line option be?  I assume probably a flag so what character?

**Comment by jdm** [comment]
I suggest adding it as an option to the -Z flags, which are for enabling or disabling features that aid in debugging.

**Comment by metajack** [comment]
Should we move -i to a -Z flag too?

**Comment by pgonda** [comment]
I'll be working on this feature! Thanks for tip jdm

**Comment by pgonda** [comment]
I think I got this working, how can I put this up for review/push?  Thanks!
