### ISSUE TITLE
Display a notification after a long `mach build` command

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#5582]
The Firefox build system has [this code](https://hg.mozilla.org/mozilla-central/file/ab0490972e1e/python/mozbuild/mozbuild/mach_commands.py#l424) to display a system notification popup when the build finishes (if the duration was greater than some threshold).  It'd be great to copy/adapt this for our own [build command](https://github.com/servo/servo/blob/master/python/servo/build_commands.py) and other long-running commands.

**Comment by boghison** [comment]
+1, for those who are wondering how: notify osd on linux and display notification on mac. I'll work on this if I have time :)

**Comment by dhananjay92** [comment]
I am working on it. I am currently trying to implement simple this functionality for Linux. Will add support for other platforms once it's done for Linux.

*Note: Newbie here. So bear with me, please!*

**Comment by jdm** [comment]
Great!

**Comment by dhananjay92** [comment]
[Here](https://github.com/dhananjay92/servo/commit/25d0dd897eef8ca845ec3ef2a41eca23416640b3) is what I am doing.

It works fine for Linux.

Please let me know if I am going in the right direction.
*Note that the printing is currently for debugging only. In the final PR, I will remove all such debugging codes.*

**Comment by jdm** [comment]
@dhananjay92 Seems sensible to me! The other choice for linux would probably be invoking the `notify-send` process.

**Comment by dhananjay92** [comment]
@jdm I just took that notification code from Mozilla's script (`mach_commands.py`) that mbrubeck mentioned. Should I change it to invoking `notify-send` process?

**Comment by jdm** [comment]
Nope, using prior art is totally fine.

**Comment by dhananjay92** [comment]
Okay. So, I will add Notifications code for Windows and then create a PR. Since I don't have Mac, I can't implement Notifications for it. I am hoping someone with a Mac would add it later hopefully!

**Comment by dhananjay92** [comment]
Done for windows as well. I followed the same `FLASHWINDOW` code from Mozilla's `mach_commands.py` script.

Once the build is finished the Terminal blinks in the taskbar as shown below in screenshot.
![screenshot_windowflash](https://cloud.githubusercontent.com/assets/6269279/7119929/682787ee-e1be-11e4-9fbe-443c88794d07.png)

Is this okay? If so, I will create a PR.

**Comment by dhananjay92** [comment]
Created Pull #5664. Please let me know if any changes are needed in it!
