### ISSUE TITLE
Incorrect `namespaceURI`.

### ISSUE THREAD

**Issue by neojski** [servo/servo#5585]
Trying to fix the simple #1745 issue I've found that the following

```html
<html xmlns="http://www.w3.org/1999/xhtml">
  <body>
    <svg id="svg" xmlns="http://www.w3.org/2000/svg"></svg>
    <script>
console.log(document.getElementById('svg').namespaceURI)
    </script>
  </body>
</html>
```
returns `http://www.w3.org/1999/xhtml`. Firefox, chrome and `tests/wpt/web-platform-tests/html/dom/documents/dom-tree-accessors/document.getElementsByName/document.getElementsByName-namespace.xhtml` show/want `http://www.w3.org/2000/svg`.

**Comment by jdm** [comment]
Right now the namespace for each element in provided in the constructor and is immutable. @kmcallister is this something that h5e should be providing, or should the DOM be watching for setting the xmlns attribute and updating the associated namespace?

**Comment by Ms2ger** [comment]
https://github.com/servo/html5ever/pull/120 should fix this.

**Comment by neojski** [comment]
By the way, how does changing namespace work? I mean, one can modify xmlns attribute of a node and this information is propagated to the whole subtree. Which operation is slow: setting xmlns or getting xmlns? I can imagine either setting xmlns traverses the whole subtree or getting namespace traverses the tree up to the first parent that has its namespace set (via xmlns or prefix).

**Comment by neojski** [comment]
Oh, apparently namespace is not modifiable. See: https://developer.mozilla.org/en-US/docs/Web/API/Node/namespaceURI:

> This is not a computed value that is the result of a namespace lookup based on an examination of the namespace declarations in scope. The namespace URI of a node is frozen at the node creation time.

**Comment by eefriedman** [comment]
This appears to work correctly on master.  Am I missing anything?
