### ISSUE TITLE
Implement attribute getter of Location

### ISSUE THREAD

**Issue by yodalee** [servo/servo#5591]
Follow up #5397
Currently only getter of `Href`, `Pathname`, `Search`, `Hash` are implemented. The rest getter can be implemented too, includes:
- [ ] protocol
- [ ] username
- [ ] password
- [ ] host
- [ ] hostname
- [ ] port

**Comment by shinglyu** [comment]
Got stuck on #5187, will work on this one to feel some momentum.

**Comment by frewsxcv** [comment]
This appears to be done.
