### ISSUE TITLE
Implement TextDecoder#ignoreBOM.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5600]
Blocks #5601.
- Spec: https://encoding.spec.whatwg.org/#dom-textdecoder-ignorebom.
- Code: `components/script/dom/textdecoder.rs`, `components/script/dom/webidls/TextDecoder.webidl`.
- Test: `/encoding/textdecoder-ignorebom.html`, `/encoding/idlharness.html`.

**Comment by yodalee** [comment]
I think I can handle this

**Comment by jdm** [comment]
I don't believe @Ms2ger is working on this.

**Comment by Ms2ger** [comment]
I'm not, go for it.

**Comment by shinglyu** [comment]
Sorry for being too busy before Whistler WW, I'll start working on this.

**Comment by talklittle** [comment]
I think I'll be implementing this as part of the work on #13234.
