### ISSUE TITLE
Support the `tabindex` focus flag

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#5603]
https://html.spec.whatwg.org/multipage/interaction.html#the-tabindex-attribute

The `tabindex` attribute should be parsed by the [`VirtualMethods::after_set_attr` implementation](https://github.com/servo/servo/blob/a745dda8635aa3f84fba19c62911edc64faa1281/components/script/dom/htmlelement.rs#L222) for `HTMLElement` (and also in a `bind_to_tree` method in the same impl?).  Parsing the attribute should result in setting a "tabindex focus flag," which perhaps should be added to `script::dom::node::NodeFlags`.  This flag should be used in the code that determines whether an element is focusable (see #5592).  The default value of the flag should be set according to the spec link above.

This is also a first step toward implementing [sequential focus navigation](https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation).

**Comment by pgonda** [comment]
This spec says that this attribute's value is an int, and the int helps determine the ordering for sequential focus navigation.  So should the "tabindex focus flag" be set and the int value stored else where?

**Comment by mbrubeck** [comment]
Yes, that's correct.  The `tabindex` attribute should be parsed as an integer, but the "tabindex focus flag" is a boolean flag that is either set or not.

The [`tabIndex` IDL field](https://github.com/servo/servo/blob/51dd6984f7cc292d77b2330d404ffcff34981214/components/script/dom/webidls/HTMLElement.webidl#L27) should reflect the integer value of the attribute.  The existing `make_uint_getter!` and `make_uint_setter!` macros are an example of how to do this for unsigned integers; we'll need to add similar macros and helper functions for signed integer attributes.

**Comment by pgonda** [comment]
How does this look?  The spec says some of the Elements should only be defaulted with the tabindex flag if they have certain attributes with them, but I could not find away to derive this with only the type_id to work with.

**Comment by mbrubeck** [comment]
You can can [cast the HTMLElement reference to `JSRef<Element>`](https://github.com/servo/servo/blob/a745dda8635aa3f84fba19c62911edc64faa1281/components/script/dom/htmlelement.rs#L193-L194) and then call methods like `get_attribute` on it.  (You can also cast to other interfaces as appropriate.)

Also, I forgot to mention that you should base your work on #5592 which hasn't landed yet but adds a helper trait to the `JSRef<Element>` type where you can add more focus-related code if needed.

**Comment by pgonda** [comment]
Thanks!  I'll get started off that branch then.

**Comment by pgonda** [comment]
Hi sorry for another question but did you mean for the default to be set in NodeFlags::new or in after_set_attr function?  You mentioned the casting the HTMLElement which is in the after_set_attr, but this would not be called if the attribute was not listed, so if the default is to be set here how would that work?  Or would after_set_attr be called on tabindex regardless of whether it was specified?

**Comment by mbrubeck** [comment]
I think the default should be set in a `VirtualMethods::bind_to_tree` implementation on `JSRef<HTMLElement>`.  By the way, I am going to be on vacation for the next week, but other Servo developers like @jdm can continue answering questions here or on the #servo channel on irc.mozilla.org.

**Comment by pgonda** [comment]
The spec mentions Editing hosts, Browsing context containers, Sorting interface th elements I am not sure how to check for these inside bind_to_tree, any tips?

**Comment by jdm** [comment]
Browsing context containers are iframes, so you can just check the node type id or try casting it to HTMLIFrameElement. We don't implement anything related to editing hosts right now, so I would leave a TODO for that, along with the "sorting interface th elements" which have [pretty complicated rules](https://html.spec.whatwg.org/multipage/tables.html#sorting-interface-th-element).

**Comment by pgonda** [comment]
what would be a good way to go about adding testing to this?

**Comment by jdm** [comment]
I am having trouble thinking of ways to test this that do not rely on implementing sequential navigation and checking the currently-focused element :/

**Comment by mbrubeck** [comment]
You can test this using the `element.focus()` method.  There are some existing WPT tests that should be affected by this change, like `html/semantics/disabled-elements/disabledElement.html` and `html/semantics/selectors/pseudo-classes/focus.html`.

**Comment by pgonda** [comment]
I am getting this error when I try to test wpt
```rust
Error running mach:

    ['test-wpt']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory

  File "/Users/peter/workspace/opensource/servo/python/servo/testing_commands.py", line 206, in test_wpt
    self.ensure_wpt_virtualenv()
  File "/Users/peter/workspace/opensource/servo/python/servo/testing_commands.py", line 262, in ensure_wpt_virtualenv
    subprocess.check_call([virtualenv, "-p", python, virtualenv_path])
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
```

**Comment by jdm** [comment]
Try `rm -rf tests/wpt/_virtualenv` and try again?

**Comment by pgonda** [comment]
same error

**Comment by jdm** [comment]
@pgonda Oh, you seem to be missing the virtualenv binary.

**Comment by pgonda** [comment]
that was it, thanks!
