### ISSUE TITLE
[Reverse]NodeChildrenIterator is poorly named

### ISSUE THREAD

**Issue by jdm** [servo/servo#5616]
It actually iterates over the node's siblings, and never looks at any children. We should rename it to NodeSiblingIterator.

**Comment by pgonda** [comment]
Should the NodeHelpers function Children be renamed because it just returns a NodeSublingIterator?

**Comment by jdm** [comment]
No, since that is returning a sibling iterator for the first child of the node in question, which is equivalent to the children of the node.
