### ISSUE TITLE
Run our reftests with wptrunner.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5618]
Move tests from `tests/ref/` to `tests/wpt/mozilla/tests/css/`, as in #5687. You can use `./mach test-wpt --include _mozilla/css --manifest-update` to run the moved tests and update the manifest at once.

**Comment by s142857** [comment]
i moved the files and it is working. 
![test0](https://cloud.githubusercontent.com/assets/13268492/9025251/b7b48484-391a-11e5-8105-69fa6dc969ae.png)
![test1](https://cloud.githubusercontent.com/assets/13268492/9025250/b7b12b2c-391a-11e5-8cc8-ddcd83480eaf.png)

**Comment by s142857** [comment]
if this is what you wanted, i can push it

**Comment by Wafflespeanut** [comment]
@s142857 You can't push it. Just submit a PR and someone will review it :)

**Comment by s142857** [comment]
im having a problem hope you can help me, it says my fork is up to date, when i say git push upstream. is there any way to force it

**Comment by Wafflespeanut** [comment]
@s142857 Like I said, you don't have the privileges to push it directly to the upstream. You just make the changes, `git checkout` into a new `branch`, `git push` your `newbranch` and submit a pull request. [Here's a brief reading on that](https://gun.io/blog/how-to-github-fork-branch-and-pull-request/) :)

**Comment by Wafflespeanut** [comment]
@s142857 Hmm, looks like [you've already submitted a PR](https://github.com/servo/servo/pull/6755) a few days back. Why should this be any different? :)

**Comment by s142857** [comment]
that was with the help of my friend

**Comment by s142857** [comment]
#6897

**Comment by s142857** [comment]
even if showing how stupid I am if you want to vouch for me
https://mozillians.org/en-US/u/s142857/

**Comment by Wafflespeanut** [comment]
@s142857 Are you sure #6897 is for this issue?

**Comment by s142857** [comment]
yup, is there any problem

**Comment by s142857** [comment]
I dont know what to do
$git push upstream
..
...
To https://www.github.com/s142857/servo
 ! [rejected]        tests -> tests (non-fast-forward)
error: failed to push some refs to 'https://www.github.com/s142857/servo'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by s142857** [comment]
and when i pull
sanketh@sanketh:~/servo$ git pull upstream
Already up-to-date!

**Comment by s142857** [comment]
Yay I finaly did it

**Comment by frewsxcv** [comment]
Just started working on this. Here's a script I'm using:

```sh
#!/bin/sh

echo "<link rel='match' href='$3'>" | pbcopy

vim "tests/ref/$2"

vim -c "/$2" tests/ref/basic.list

git mv tests/ref/$2 tests/wpt/mozilla/tests/css
git mv tests/ref/$3 tests/wpt/mozilla/tests/css

./mach test-wpt --include _mozilla/css --manifest-update

git add tests/
git commit -m "Move $2 to wpt reftests."
```

**Comment by frewsxcv** [comment]
https://github.com/servo/servo/pull/9293
