### ISSUE TITLE
Set defaults for sub tests when running all tests

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#5626]
Issue reproduction:
1) Fresh clone of servo/servo.
2) Run './mach build'.
3 - Optional) Run './mach test-wpt' and watch the tests run.
4) Run './mach test' and watch the tidy, ref and content tests run, but then see it bail out with a KeyError: 'product' when it gets to set_defaults in the wpt tests. Be sad because you can't run tests :(

Thoughts on root cause/diagnosis:
When 'mach test-wpt' is run, it looks like wptcommandline.create_parser is used to create a subparser for the command, which sets sane initial defaults for many values.
When 'mach test' is run, there doesn't seem to be a special subparser for the Command, hence the regular Mach parser is used, and no defaults are set for the wpt tests.
Both code paths eventually call run_tests in tests/wpt/run.py, which calls set_defaults. However, this function is expecting initial defaults already to be set for many values (i.e. the wpt subparser sets the 'product' key to None, then set_defaults checks for None and sets the default product to 'servo'). Hence, it directly accesses many keys in the kwargs, i.e. kwargs["product"], leading to key errors when these values are not set.

I'm not really familiar with Mach, so what would be a good way to make sure these sub parsers are called when 'test' is called, or at least ensure the initial set of defaults set? I'd love to write a PR for this and be able to run all the tests :)

I believe this also affects the update-wpt, test-css, and update-css targets as they also use custom sub parsers.

**Comment by jdm** [comment]
Paging @jgraham.

**Comment by jgraham** [comment]
Bah. Yeah. I came across the same issue in gecko the other day. I consider this to be brokenness in mach, but I guess I'll look at it soon.

**Comment by jgraham** [comment]
I think this is fixed by #6526
