### ISSUE TITLE
Prime4commit and similar

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo#5638]
After one of my PRs just got merged, I received an email from contact@prime4commit.com telling me I got a primecoin tip for my commits. I don't find this to be in good taste or behavior - if you agree, could you [open an issue with them](https://github.com/sigmike/peer4commit/issues/new) to disable the [servo "project page"](http://prime4commit.com/projects/190)? Prime4commit is run alongside peer4commit, and both are forks of tip4commit.

**Comment by jdm** [comment]
FWIW it's possible to disable it per user, regardless if we decide to disable the tips for the project.

**Comment by nox** [comment]
@jdm Ping?

**Comment by jdm** [comment]
I haven't seen any similar notifications in years.
