### ISSUE TITLE
Create unit test framework for DOM safety

### ISSUE THREAD

**Issue by jdm** [servo/servo#5646]
We want to add tests to tests/unit that rely on the `script` crate and integrate https://github.com/laumann/compiletest-rs, such that we can test that our [safety-related compiler plugins](http://mxr.mozilla.org/servo/source/components/plugins/lints/unrooted_must_root.rs) (and [more](http://mxr.mozilla.org/servo/source/components/plugins/lints/ban.rs)) actually prevent the problems we think they do.

I imagine this looking like a new file in `tests/unit/script` that contains code like https://github.com/laumann/compiletest-rs/blob/master/test-project/tests/tests.rs.

**Comment by chmanchester** [comment]
compiletest-rs is having trouble compiling with servo's rustc, failing on something added on April 1st.

**Comment by kmcallister** [comment]
See also #2385.

**Comment by fhahn** [comment]
I've started working on this. Seems like `compiletest-rs` just works, we just have to set the right `-L` flags. So far I've only added a compile-fail test for the ban lint (https://github.com/fhahn/servo/commit/f3398bbc67fd93c7d5a1c95441e01a461b7224b8#diff-9e746db0a92361cae1b011f632bb4202R2), which I included in `tests/unit/plugin`.

Before I add more tests I wanted to check where the best place to put those tests would be. From the two relevant tickets I found (this one and  #2385), I gathered that ideally we want to have compile-fail tests for various crates. Should we add a `compiletest.rs` to each test crate or create a separate compiletest crate, which contains all compile tests?

**Comment by jdm** [comment]
I would be tempted to organize it like `tests/unit/` where we end up with a different crate for each crate we want to test, but they're still all gathered together.

**Comment by jdm** [comment]
Also thank you thank you thank you for taking this on :dancer:

**Comment by fhahn** [comment]
@jdm I've pushed a new [commit](https://github.com/fhahn/servo/commit/234df8d3921a3dd4b022a2d5d921f529b15ee9a4) which should contain some groundwork following your suggestion. It basically adds a `tests/compiletest/` directory which contains a `helper` crate, which just sets up and runs some tests using `compiletest_rs` and crates for the tests (at the moment there's only a single plugin test however). I also kind of integrated it into mach, but currently `test_compiletest` is basically `test_unit` with some path changes. I'll refactor that later.

**Comment by jdm** [comment]
We'll likely need to choose between target/debug/ and target/release/ as appropriate, but it's looking good so far!
