### ISSUE TITLE
Page::window_for_script_dealloation is unused

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5654]
@jdm: should we be using this in `shut_down_layout`? (Also, "dealloation" is not a word.)

**Comment by jdm** [comment]
No, those are only for use in ScriptMemoryFailsafe. It guess we should replace http://mxr.mozilla.org/servo/source/components/script/script_task.rs#320 with it; it makes no difference right now, but will matter after the SM upgrade.

**Comment by jdm** [comment]
This should also cover renaming it to use "deallo*c*ation" in the name.

**Comment by josiahdaniels** [comment]
If I understand correctly, this is as simple as replacing
    `let window = Unrooted::from_temporary(page.window());`
with
   `let window = page.window_for_script_deallocation()`

And of course fixing the typo. If that is correct then I'd like to take this.

**Comment by boghison** [comment]
This is fixed now, right?

**Comment by metajack** [comment]
Appears that way.
