### ISSUE TITLE
Implement HTMLMetaElement.{name,content}

### ISSUE THREAD

**Issue by jdm** [servo/servo#5663]
Spec: https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element
Code: components/script/dom/webidls/HTMLMetaElement.webidl, components/script/dom/htmlmetaelement.rs

These should just be simple string setters/getters that use the `make_getter` and `make_setter` macros. Be sure to run `./mach test-wpt` and see if there are any changes to the test outputs reported.

**Comment by dhananjay92** [comment]
I am working on this one as well!

**Comment by dhananjay92** [comment]
[Here](https://github.com/dhananjay92/servo/commit/651e490c2b9eda8d6fd20149e61128c1a7b4e7d2) is what I have done so far. With these changes, project builds successfully.
I am now running the tests using `./mach test-wpt`.

Please let me know if I missed anything!

**Comment by jdm** [comment]
That looks like what I expected :)
