### ISSUE TITLE
Send high resolution millisecond timestamps in timeline markers

### ISSUE THREAD

**Issue by jdm** [servo/servo#5665]
We should convert the nanosecond timestamps into fractional milliseconds like the output of https://developer.mozilla.org/en-US/docs/Web/API/Performance/now . This doesn't mean we need to communicate with the script task; I think we can just do some simple division.

cc @JIoJIaJiu

**Comment by JIoJIaJIu** [comment]
@jdm Is it ok or I should implement saving start stamp?

**Comment by jdm** [comment]
That makes sense to me. Does the timeline code still work?

**Comment by jdm** [comment]
Pleause use http://w3c.github.io/hr-time/ as the reference instead of the TR/ spec, though.
