### ISSUE TITLE
Move mime classifier unit tests into unit test crate

### ISSUE THREAD

**Issue by jdm** [servo/servo#5667]
They got lost in the shuffle, it appears: http://mxr.mozilla.org/servo/source/components/net/mime_classifier.rs#983 . They should be in http://mxr.mozilla.org/servo/source/tests/unit/net/ instead.

**Comment by jdm** [comment]
`./mach test-unit` is the way to check they they actually build and run after being moved.

**Comment by zerokarmaleft** [comment]
I'll give this one a go.

**Comment by jdm** [comment]
Great!
