### ISSUE TITLE
Incorrect size on filtered element

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#5668]
A filtered element (e.g. opacity) will be displayed smaller than it should. Investigating if the issue is incorrect translate matrix or with clipping.

Confirmed for: opacity, grayscale.

**Comment by Adenilson** [comment]
Screenshots.
![opacity_filter_ff](https://cloud.githubusercontent.com/assets/959744/7123574/f20518e6-e1d7-11e4-84f6-f8ac11abdc06.png)
![opacity_filter_servo](https://cloud.githubusercontent.com/assets/959744/7123573/f2011f3e-e1d7-11e4-8d10-40614ccf5ced.png)

**Comment by Adenilson** [comment]
Test case: https://gist.github.com/Adenilson/fcdf16c8cd1911a1245e

**Comment by Adenilson** [comment]
@pcwalton @larsbergstrom

**Comment by sviter** [comment]
Fixed for me in latest servo nightly
