### ISSUE TITLE
No support for History APIs

### ISSUE THREAD

**Issue by boghison** [servo/servo#5669]

**Comment by jdm** [comment]
Presumably you mean https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface ?

**Comment by boghison** [comment]
@jdm Yes, feel free to edit the content of the issue to help contributors :)

**Comment by jdm** [comment]
Ok! I think it's worth splitting this up into various issues, since some parts of it are significantly more complicated than others.

**Comment by asajeffrey** [comment]
Thanks to @cbrewster we have #12552 and #12685.
