### ISSUE TITLE
Implement History's back/forward APIs

### ISSUE THREAD

**Issue by jdm** [servo/servo#5670]
Spec: https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface, https://html.spec.whatwg.org/multipage/browsers.html#dom-history-back, 
Code: https://github.com/servo/servo/wiki/Adding-a-new-WebIDL-binding

This will just end up mimicing the behaviour of the GoForward/GoBack APIs of HTMLIFrameElement (see components/script/dom/element/htmliframelement.rs)

**Comment by jdm** [comment]
cc #5669

**Comment by aneeshusa** [comment]
I'd like to try this one out for size.

**Comment by jdm** [comment]
It's yours!

**Comment by jinankjain** [comment]
Hi,  could someone help me out where I could find the code relevant to fix this bug.

**Comment by jdm** [comment]
@jinankjain are the links in the original comment unclear? This task requires creating a new webidl interface and a new Rust implementation of the interface, but there are also existing methods in htmliframeelement.rs that can be used as models.

**Comment by snf** [comment]
Browser context needs some work and there are tons of TODO(handle browsing context) out there in the dom files so I think we should start there.

And wouldn't this struct keep alive all the Document, Window, etc context from the browsing history creating a little memory leak?:
```
// This isn't a DOM struct, just a convenience struct
// without a reflector, so we don't mark this as #[dom_struct]
#[must_root]
#[privatize]
#[jstraceable]
pub struct SessionHistoryEntry {
    document: JS<Document>,
    children: Vec<BrowserContext>
}
```

Also, should we add something else in the script_task/constellation?

**Comment by jdm** [comment]
It technically won't be a leak, since it will be removed when the script task shuts down. We should also add logic to prune the actual cached document at some point, but that will require extra logic to reload it if we end up trying to retrieve it from history later.

**Comment by snf** [comment]
@aneeshusa or @jinankjain still working on this one?

**Comment by vectorijk** [comment]
@snf are you also working on this one?
@jdm I would like to try this one.

**Comment by snf** [comment]
@vectorijk no, devs don't let me work in e-easy bugs anymore :'( . So all yours if no one is working on it.

**Comment by jdm** [comment]
Yes, go for it :)

**Comment by boghison** [comment]
@vectorijk Excuse me, are you still working on this?

**Comment by vectorijk** [comment]
Yes,I am still working on it. Cause I am a newbie, I am doing some research
on how to implement this api and also digged into how WebKit and gecko
wrote on this api.

**Comment by jdm** [comment]
Made any progress @vectorijk? Any questions I can answer?

**Comment by tomjakubowski** [comment]
I'd like to take this on!

**Comment by vectorijk** [comment]
@tomjakubowski I am off~.

**Comment by jdm** [comment]
Sounds like it's all yours, @tomjakubowski.

**Comment by jdm** [comment]
#7520 was proposed to implement this. It got stuck on the requirement to write tests; I'm not comfortable leaving this marked as E-easy until we come up with suggestions for how to write tests for it.

**Comment by ConnorGBrewster** [comment]
I am picking this one back up. I am implementing `pushState` so the history tests can be enabled
