### ISSUE TITLE
window.performance.now values are way too big

### ISSUE THREAD

**Issue by jdm** [servo/servo#5690]
The implementation at http://mxr.mozilla.org/servo/source/components/script/dom/performance.rs#54 multiples a nanosecond value by 1 million and calls that a high-precision millisecond value. That seems obviously wrong to me; we should be dividing in order to return fractional milliseconds.

**Comment by jagtalon** [comment]
@jdm I'd like to try this out.

**Comment by Wafflespeanut** [comment]
@jdm I've created a pull request for this issue.

**Comment by Wafflespeanut** [comment]
And, ignore the first one. I accidentally pushed to master :)

**Comment by jdm** [comment]
Closed by #6292.
