### ISSUE TITLE
DOM methods taking Vec<UnionContainingDOMType> aren't safe

### ISSUE THREAD

**Issue by jdm** [servo/servo#5702]
We probably end up with `Vec<UnionType>` where UnionType is a type containing `JS<T>` (see #2661). We should actually make them take a RootedVec in this case.

**Comment by nox** [comment]
Want this one.

**Comment by sviter** [comment]
Is it still valid issue?

**Comment by nox** [comment]
No it's not, the generated union types now use `Root<T>` internally.
