### ISSUE TITLE
Images won't be filtered

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#5703]
Unlike text and divs that will be correctly filtered, image elements are not.

Test case: https://gist.github.com/Adenilson/c485803bf1e144963e55

**Comment by Adenilson** [comment]
![img_opacity_filter_ff](https://cloud.githubusercontent.com/assets/959744/7165750/726f71ac-e35e-11e4-9468-1a934e53c065.png)
![img_opacity_filter_servo](https://cloud.githubusercontent.com/assets/959744/7165749/726bf55e-e35e-11e4-9eed-ae32a1d4c5ce.png)

**Comment by Adenilson** [comment]
Related issue #5668

**Comment by Adenilson** [comment]
@pcwalton @larsbergstrom

**Comment by pcwalton** [comment]
The problem here is that we build up the filter pipeline in `BlockFlow`, but these are inline fragments. We should move that code to be shared between both (and, in general, support inline stacking contexts).

**Comment by Adenilson** [comment]
Confirmed: setting the property display: block in the above example will make it work.

I'm reading display_list_builder code to understand how to share StackingContext object creation for both Blocks and Inlines.
![screen shot 2015-04-17 at 4 23 52 pm](https://cloud.githubusercontent.com/assets/959744/7212569/351adbea-e51e-11e4-9dd2-0faa800ea992.png)

**Comment by Adenilson** [comment]
We can also close this, as #5782 has landed.
