### ISSUE TITLE
Dispatch mousedown and mouseup events

### ISSUE THREAD

**Issue by jdm** [servo/servo#5705]
We currently dispatch click events, but not the mousedown and mouseup events that precede them.

Spec: https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3-Events.html#event-type-mousedown
Code: components/script/script_task.rs (see empty branches in handle_event), components/script/dom/document.rs (see handle_click_event)

**Comment by pgonda** [comment]
I'd like to try this out!

**Comment by jdm** [comment]
Go for it!

**Comment by pgonda** [comment]
any suggestions on how to add testing for these new events?

**Comment by jdm** [comment]
I don't know of any way to do automated testing right now (since we can't inject arbitrary mouse events), but you can create a manual test in tests/html that has event listeners that report success.

**Comment by jdm** [comment]
Specifically you'll want to check the the mousedown/mouseup/click events occur in the right order, and that all the properties of the event objects are as the spec defines, and that no handler is invoked more than once.

**Comment by Manishearth** [comment]
@pgonda In case you're stuck, you might be able to take some pointers from #5723 :smile:

**Comment by pgonda** [comment]
I am still having the issue of event order (mousedown->click->mouseup).  I didnt see anything in the other commit that would fix that, did I miss something?

**Comment by jdm** [comment]
@pgonda It's entirely possible that our input library (glutin) is providing us events in the order of MouseDown, Click, MouseUp, which means that we'll need to move the existing click event code so that it runs based on the MouseUp event instead.
