### ISSUE TITLE
Unnecessary clone in Document constructor

### ISSUE THREAD

**Issue by jdm** [servo/servo#5719]
We match against an `Option<DOMString>` named content_type, but there's no need to clone the string in the `Some` case.

Code: components/script/dom/document.rs

**Comment by dhananjay92** [comment]
So, on [Line#766](https://github.com/servo/servo/blob/master/components/script/dom/document.rs#L766) just replace `Some(string) => string.clone(),` with `Some(string) => string,`.

That's it?!

**Comment by jdm** [comment]
Yep :) It's a nice simple issue to ease new contributors into the project.

**Comment by neojski** [comment]
@dhananjay92, @jdm, this should get closed because of #5733.
