### ISSUE TITLE
actor_workers hashmap is not used

### ISSUE THREAD

**Issue by jdm** [servo/servo#5735]
I don't remember precisely what its intended for, but it really should live outside of handle_new_global and be passed in as an `&mut HashMap` argument, rather than be created inside that function.

Code: components/devtools/lib.rs

**Comment by dhananjay92** [comment]
So far, I have done [this](https://github.com/dhananjay92/servo/commit/ab53b9d1df90924b453b6d1e6abd4387a2043948).
No build errors.

What tests should I run for these changes?

**Comment by jdm** [comment]
Given that nobody reads from it, there's no way the behaviour of the code that uses it can change. That being said, https://github.com/servo/servo/wiki/More-developer-tools-student-project describes how to run the devtools server and connect to it from Firefox.

**Comment by dhananjay92** [comment]
@jdm I read it. But it seems for these changes, it's not necessary to do it (mainly because these changes aren't going to affect anything.) So I am going to go ahead and do a PR.

**Comment by carlosdp** [comment]
It looks like this issue was solved by #5758 but was not auto-closed.

**Comment by jdm** [comment]
Yep, thanks!
