### ISSUE TITLE
Make parse_progress take the JSRef by value, not reference

### ISSUE THREAD

**Issue by jdm** [servo/servo#5738]
`&JSRef<T>` is inefficient, since `JSRef<T>` is essentially a smart-pointer already that is trivially copyable so passing by reference doesn't give any benefit.

Code: components/script/parse/html.rs

**Comment by dhananjay92** [comment]
I am working on it!

**Comment by dhananjay92** [comment]
[Here](https://github.com/dhananjay92/servo/commit/0e6ec74ee60d6ab8354b6c30f09e703772c5e9b3) is what I have done.
Builds fine. Any tests to run for this?

**Comment by jdm** [comment]
If pages load, then that's enough to demonstrate that it still works.

**Comment by dhananjay92** [comment]
Checked. Page Loads!

**Comment by Manishearth** [comment]
Fixed in #5744
