### ISSUE TITLE
rustdoc source links aren't working

### ISSUE THREAD

**Issue by jdm** [servo/servo#5746]
Click `[src]` on http://doc.servo.org/script/dom/bindings/codegen/Bindings/XMLHttpRequestBinding/trait.XMLHttpRequestMethods.html for example, and it's a 404. I guess the same response for any page I try.

**Comment by Manishearth** [comment]
This is a rustdoc issue iirc, a few months ago rustdoc had broken src links (it got fixed, but we haven't updated our rustc)

**Comment by nathanross** [comment]
No longer 404'ing for me. Tried another few pages too. Guessing this is fixed.

**Comment by Manishearth** [comment]
Yeah this was fixed a while back and we picked it up in the rustup.
