### ISSUE TITLE
Add test for createDocument to node_cloneNode.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#5754]
There's a FIXME pointing at #1509 which was missing at the time the test was created. We should probably check the contentType property of the cloned document, since it should be "application/xml".

**Comment by dhananjay92** [comment]
Working on it.

**Comment by dhananjay92** [comment]
@jdm I understand that I have to write test case on [Line#185](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/node_cloneNode.html#L185). But I have problem running the test. When I run the test using `./mach test-wpt /tests/wpt/mozilla/tests/mozilla/node_cloneNode.html` command, it says `Ran 0 tests` in the Summary. Is there any other way of running this test?

**Comment by jdm** [comment]
Yes, sorry. `./mach test-wpt /_mozilla/mozilla/tests/mozilla/node_cloneNode.html` should do the trick.

**Comment by dhananjay92** [comment]
@jdm Oh okay. So the mozilla-tests need to run like that!
I think it makes sense to put this in [`/tests/wpt/README.md`](https://github.com/servo/servo/blob/master/tests/wpt/README.md), so that it can help others too.
If you agree, I'll go ahead and do it.

**Comment by dhananjay92** [comment]
Nope. `./mach test-wpt /_mozilla/mozilla/tests/mozilla/node_cloneNode.html` isn't running it.
After poking for a while, it seems this is happening because of wrong path. Even if I give some complete gibberish path, it gives same output.
Where is `_mozilla` directory? I couldn't find it!

**Comment by jdm** [comment]
Oh, the tests/mozilla bit is wrong. https://github.com/servo/servo/issues/1826#issuecomment-94292331 describes how to do it properly.

**Comment by dhananjay92** [comment]
Yep. That worked. I will write the test case shortly.

**Comment by frewsxcv** [comment]
Was this completed im #5761?
