### ISSUE TITLE
Upstream our tests.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5756]
Where possible, we should upstream our tests to the relevant standard's test suite. This allows other browsers to benefit from our work, and makes it more likely that any mistakes or spec changes affecting the tests are found.

**Comment by nox** [comment]
Can't we just dump all our tests in a subdirectory of WPT, like the Opera tests?

**Comment by nox** [comment]
Cc @jgraham

**Comment by jgraham** [comment]
They get upstreamed every time there's a downstream sync. There is a separate issue that that got too hard.
