### ISSUE TITLE
Create benchmarks to measure DOM binding performance

### ISSUE THREAD

**Issue by jdm** [servo/servo#5760]
We should make it really easy to demonstrate improvements or regressions in basic performance of our DOM bindings. This can start with a single page in tests/html that executes a series of measurements and prints out the results; this should be many iterations of the same action, with the total time divided by the number of iterations. Measurements that we care about include:

* simple string getter
* simple string setter
* method invocation without return value
* method invocation with return value
* Event object creation

**Comment by mskrzypkows** [comment]
I'd like to take this issue, but it could take me about month to do it (I have little time for open source per week), is it OK? Should I use some specified library to create those tests in JS?

**Comment by jdm** [comment]
Not a problem! I don't think a library will add anything here; we just want to report numbers about basic parts of our DOM implementation.

**Comment by mskrzypkows** [comment]
OK, I'll propose some tests.

**Comment by jdm** [comment]
Fixed by #6146.
