### ISSUE TITLE
Jumpy layout on mouse movement in simple page with multiple font sizes

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#5766]
In the following test case, the layout changes when the mouse moves from one element to another.  Looking at flow tree dumps, it looks like maybe the first `<p>` sometimes gets the line height of the second one, and sometimes vice-versa.  Disabling style sharing and the font cache does *not* change the behavior.

```html
<!DOCTYPE html>
<html  lang="en" >
  <head>
    <meta charset="utf-8"/>
    <style>
      .test {
        font-size: 150%;
      }
    </style>
  </head>
  <body>
    <p>Foo</p>
    <div class="test"><p>Bar</p></div>
  </body>
</html>
```

**Comment by metajack** [comment]
cc @pcwalton

**Comment by metajack** [comment]
cc @glennw

**Comment by mbrubeck** [comment]
I can no longer reproduce this bug.
