### ISSUE TITLE
Return an Atom from Element::parsed_name.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5774]
All callers immediately call `Atom::from_slice` anyway.

**Comment by dhananjay92** [comment]
[Here](https://github.com/dhananjay92/servo/commit/09fbd69910be6dac10accb8abfb1d3a643914a87) is what I have done so far. Builds fine.
How do I check if my changes are correct or not? Any tests to run?

**Comment by mskrzypkows** [comment]
check ```./mach test-wpt ```

**Comment by mskrzypkows** [comment]
Is the issue free to take? @dhananjay92 solution looks good.

**Comment by jdm** [comment]
Go for it.

**Comment by mskrzypkows** [comment]
The task may be closed

**Comment by saneyuki** [comment]
Fixed by #6405
