### ISSUE TITLE
Fix up the x11 hack for getting stuck in XInitThreads

### ISSUE THREAD

**Issue by glennw** [servo/servo#5780]
PR https://github.com/servo/servo/pull/5748 stops us blocking on input events on Linux, due to an apparent issue with how we are using X11 from paint threads in Servo.

Find the root cause and change how we use X11 from threads to allow us to re-enable XPeekEvent.

**Comment by mrobinson** [comment]
I'm fairly certain this was made obsolete by: #13711.
