### ISSUE TITLE
Extend 'make tidy' to check licenses of dependencies

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#5786]
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1155181, acceptable licenses for code that is referenced by Servo are: MIT, BSD, Apache, and MPL 2.

1) For Rust dependencies, check the Cargo.lock file and access the info for the crate online to verify the license (suggested by @alexcrichton at https://github.com/rust-lang/meeting-minutes/blob/master/weekly-meetings/2015-04-21.md#servo-licensing-info).

2) For C dependencies that are linked in statically, we should verify the license in whatever way Gecko currently does.

**Comment by larsbergstrom** [comment]
Note that we are currently in good shape - `find . -name '*.toml' | xargs grep license` shows that all of the licensed dependencies are fine.

I also did a pass through `find . -name '*.toml' | xargs grep -L license` and the files without licenses are either sub-toml files or are in dependencies we wrote on the Servo team and can correct.

**Comment by dralley** [comment]
It could be a bit too heavyweight for the CI, but this is a nice tool for checking things like this: https://github.com/onur/cargo-license

![Screenshot from 2020-03-25 15-49-05](https://user-images.githubusercontent.com/2751996/77579151-34f51d80-6eb0-11ea-8701-96595f3e4090.png)

**Comment by dralley** [comment]
Actually, this is being done already, so I think the issue can be closed.

https://github.com/servo/servo/commit/536314be79ba0ee4a45e3afd027c7bdd4200d95c
