### ISSUE TITLE
Frequent deadlocks browsing on Linux

### ISSUE THREAD

**Issue by tdaede** [servo/servo#5789]
When using Servo and browsing around websites like Github or Wikipedia, eventually with enough draws Servo will deadlock. This generally happens 5-60 seconds into a browsing session. No errors are displayed and no CPU is used. Closing the window does not work, however killing with Ctrl-C does.

Resizing seems to make the problem happen faster.

**Comment by tdaede** [comment]
This is caused by this Mesa bug:

https://bugs.freedesktop.org/show_bug.cgi?id=84252

**Comment by zmike** [comment]
Confirming, though as the ticket points out it can be worked around with LIBGL_DRI3_DISABLE=1

**Comment by tdaede** [comment]
Fixed in libxcb commit: http://cgit.freedesktop.org/xcb/libxcb/commit/?id=5b40681c887192307f3ae147d2158870aa79c05f

When the next libxcb release happens, we should add a configure check for that version and close this bug.

**Comment by dralley** [comment]
Since it's 5 years later, can this be closed?
