### ISSUE TITLE
Make test-wpt deal with full paths to mozilla/ tests correctly

### ISSUE THREAD

**Issue by jdm** [servo/servo#5791]
Right now you can tab-complete to a test file under `tests/wpt/web-platform-tests/` and the WPT harness will run it correctly, but the same is not true for tests that live in `tests/wpt/mozilla/tests/`. The `test-wpt` command in `testing_commands.py` should notice the `tests/wpt/mozilla/tests` path and replace it with `/_mozilla/` internally before executing the harness.

**Comment by jdm** [comment]
Specifically, `./mach test-wpt tests/wpt/mozilla/tests/mozilla/documentElement.html` does not work right now, but `./mach test-wpt /_mozilla/mozilla/documentelement.html` does.

**Comment by dguenther** [comment]
I opened a PR at #5797. This is my first Servo PR, so I'm still getting used to the project, but hopefully I didn't mess anything up too bad.

**Comment by jdm** [comment]
It sounds like I might have been hasty in filing this without talking to @jgraham. My apologies!

**Comment by dguenther** [comment]
No problem, it was still fun to take a look at it. :)

**Comment by jdm** [comment]
Should be fixed when #5799 merges.
