### ISSUE TITLE
Write a lint for bad Root temporary values

### ISSUE THREAD

**Issue by jdm** [servo/servo#5807]
Code like `let new_node = node.owner_doc().root().r().CreateTextNode(new_data).root();` is easy to write. Unfortunately it causes an assertion when executed, due to the ordering of the Root values that are created - the first one is a temporary value which is destroyed after the statement is executed, but by then another Root has been created. It would be nice to stop this from being written in the first place, for the benefit of authors.

**Comment by nox** [comment]
According to @aatch, the dataflow infrastructure can be used to check the order in which Root values are freed. My guess is that there should be no overlapping between lifetimes of values of type Root<T>.

**Comment by nox** [comment]
For an example of such lint making use of CFG, look at the unconditional recursion one.

**Comment by Manishearth** [comment]
Can anyone think of a situation *other* than `let foo = temporary.root()......something.root()` where the ordering is messed up? We can easily catch chained exprs like that with a simple lint. I think, but the more general problem of broken FILO might be harder to catch.

**Comment by jdm** [comment]
I'm having trouble thingking of ones that are meaningful.

**Comment by nox** [comment]
I found many occurrences when making the iterators safe.

**Comment by Manishearth** [comment]
Alright. I'll work on this next then, unless @nox wants to try his hand at it.

**Comment by Manishearth** [comment]
@nox Many occurrences of what? `let foo = temporary.root()......something.root()`, or something else?

**Comment by nox** [comment]
Nah, of ordering issues. Like [there](https://github.com/servo/servo/blob/07aa6306f58b5d575a65ebaf5c71f510423ed8ca/components/script/dom/node.rs#L2124-L2130):

``` rust
        let child_next_sibling = child.next_sibling().root();
        let node_next_sibling = node.next_sibling().root();
        let reference_child = if child_next_sibling.r() == Some(node) {
            node_next_sibling.r()
        } else {
            child_next_sibling.r()
        };
```

I had to root everything first or Servo panicked.

**Comment by nox** [comment]
I first tried to write this without needing to compute node_next_sibling in the case it's not needed, but I couldn't find how to achieve this without panicking.

**Comment by nox** [comment]
Cf. [the previous version](https://github.com/nox/servo/blob/f7b124b290156d76559bf8b57887e52a8b603a09/components/script/dom/node.rs#L2041-L2046) of that snippet that made Servo panic:

``` rust
        let reference_child = match child.next_sibling().root() {
            Some(ref sibling) if sibling.r() == node => {
                node.next_sibling().root()
            },
            next_sibling => next_sibling,
        };
```

**Comment by nox** [comment]
Roots are movable now.
