### ISSUE TITLE
Glutin has diverged from upstream (blocks rustup)

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#5811]
https://github.com/servo/glutin has a `servo` branch that has diverged from upstream. A simple `git merge` has conflicts, and I don’t know how to fix them.

@glennw, could you confirm if I can just take upstream and ignore the `servo` branch (maybe the same changes have been cherry-picked?) or if what’s in the `servo` branch needs to be preserved? If the latter, shouln’t these changes be sent upstream? Could you do that or do a merge and resolve the conflicts?

**Comment by tomaka** [comment]
Glutin has extracted its X11 ffi into an external crate, so that's one problem.

**Comment by glennw** [comment]
@SimonSapin I have opened PRs to upstream the two changes we have in servo/glutin (https://github.com/tomaka/glutin/pull/390 and https://github.com/tomaka/glutin/pull/391). Once those two have merged, you *should* be able to just take the upstream tomaka/glutin.

**Comment by glennw** [comment]
@SimonSapin Both of the PRs above have been merged now.

**Comment by SimonSapin** [comment]
I’ve pushed a `servo_20150129` branch with the previous content of the `servo` branch, and reset the the `servo` branch to `upstream/master`.
