### ISSUE TITLE
Add unit tests for validate_and_extract

### ISSUE THREAD

**Issue by jdm** [servo/servo#5813]
There is uncertainty in #5778 about whether this function is working as advertized right now. We should put together a comprehensive set of tests for it.

**Comment by jdm** [comment]
Marked assigned to allow @donaldpipowitch to claim it if desired.

**Comment by jdm** [comment]
note: tests belong in tests/unit/script now.

**Comment by donaldpipowitch** [comment]
Thank you, I'll try to solve this!

**Comment by Ms2ger** [comment]
We have plenty in wpt.

**Comment by donaldpipowitch** [comment]
What is wpt? You closed this issue, is this solved now?

**Comment by jdm** [comment]
@donaldpipowitch WPT is a large testsuite of the HTML spec: http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/, which does cover this code in question among many other things.

**Comment by tamird** [comment]
I must be dense - I can't find where this function is tested.
All the callers to `script::dom::bindings::utils::validate_and_extract` seem to be:
- [`SetAttributeNS `](https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L1094) which is not itself called anywhere.
- [`CreateAttributeNS`](https://github.com/servo/servo/blob/master/components/script/dom/document.rs#L1046) which is not itself called anywhere.
- [`CreateElementNS`](https://github.com/servo/servo/blob/master/components/script/dom/document.rs#L1020) which is called from:
  - [`CreateDocument`](https://github.com/servo/servo/blob/master/components/script/dom/domimplementation.rs#L62) which is not itself called anywhere.

What did I miss?

**Comment by donaldpipowitch** [comment]
Can I add other unit tests for Servo or Servo-related Crates in the meantime?

**Comment by Ms2ger** [comment]
You missed that all those functions are called from JavaScript. Do feel free to add tests for other code, though!
