### ISSUE TITLE
Skip the dom/ranges/ test directory, rather than disabling each test

### ISSUE THREAD

**Issue by jdm** [servo/servo#5825]
The results at http://mxr.mozilla.org/servo/search?string=disabled%3A&find=dom%2Franges&findi=&filter=^[^\0]*%24&hitlimit=&tree=servo are silly. We should modify http://mxr.mozilla.org/servo/source/tests/wpt/include.ini to skip the directory instead, and remove all of those ini files.

**Comment by dhananjay92** [comment]
I am trying to do this.
So, on [Line#5](https://github.com/servo/servo/blob/master/tests/wpt/include.ini#L5), I need to add 
```
    [ranges]
      skip: true
```

I am getting the same error as in #5822 (*I also did the debug run and it shows that exact same backtrace*). So, I won't be able to run the tests till that issue has been resolved.

**Comment by jdm** [comment]
Apparently this will make rebasing @nox's work on ranges much harder, so let's leave it as is.
