### ISSUE TITLE
Join adjacent text nodes in tree sink while appending

### ISSUE THREAD

**Issue by jdm** [servo/servo#5828]
The "html5 tokenizer" tests at html5test demonstrate that `e.innerHTML = "&lang;&rang;";` produces two text nodes in Servo, not one.

Relevant source at https://github.com/NielsLeenheer/html5test/blob/ce8268b2ec71ebdfa6fc6cefc989ba8e6ce544e5/scripts/6/engine.js#L412-L480 .

**Comment by mbrubeck** [comment]
This is part of #3701.

**Comment by nox** [comment]
This was done.
