### ISSUE TITLE
Generate WebIDL traits that use type parameters bounded by FooBase instead of just Foo

### ISSUE THREAD

**Issue by jdm** [servo/servo#5830]
This would allow us to pass derived types of any argument type to all WebIDL interface methods. That would get rid of a lot of papercuts...

`fn AppendChild(self, node: JSRef<Node>)`
vs.
`fn AppendChild<A: NodeBase+Reflectable>(self, node: JSRef<A>)`

**Comment by nox** [comment]
Wouldn't the NodeMethods impl itself change too?

``` rust
impl<'a, A: NodeBase + Reflectable> NodeMethods for JSRef<'a, A>
```

**Comment by jdm** [comment]
That wouldn't allow manipulating fields of the concrete type or using helper methods, unfortunately.

**Comment by jdm** [comment]
No, I'm wrong, it would just require the same addition that AppendChild would, for example: `let node = NodeCast::from(node);`

**Comment by jdm** [comment]
That would probably eliminate the vast majority of explicit casts!

**Comment by jdm** [comment]
In fact, to avoid the code-bloat possible from monomorphizing these traits against all derived types, we could do this:
```
impl<'a, A: NodeBase + Reflectable> NodeMethods for JSRef<'a, A> {
    fn AppendChild<B: NodeBase+Reflectable>(self, node: JSRef<B>) {
        let this = NodeCast::from_ref(self);
        let node = NodeCast::from_ref(node);
        this.AppendChild(node);
    }
}
```
This could be automatically generated and not require us to change any of the existing code, except that it uses the same NodeMethods trait. We could generate two traits (one using concrete types, the other using bounded generics) and just change which one gets imported in most file...

**Comment by nox** [comment]
Why would it be bad to use a single trait?

**Comment by jdm** [comment]
It would cause every monomorphized method  to contain the full implementation, rather than just the stub that calls through to the concrete one as in my previous comment. We already have problems with the amount of code generated by the script crate...

**Comment by nox** [comment]
IMO this is a bad idea, closing.
