### ISSUE TITLE
Space Jam links don't work

### ISSUE THREAD

**Issue by jdm** [servo/servo#5833]
They're clickable, but they take you to a blank page with the right title. Not sure what's going on there.

http://www2.warnerbros.com/spacejam/movie/jam.htm

**Comment by jdm** [comment]
Actually, it looks like the ones that don't work link to pages that use a lot of `<frame>` elements.

**Comment by kammitama5** [comment]
they updated the link https://www.warnerbros.com/space-jam.

**Comment by nox** [comment]
Links seem to be followed now.
