### ISSUE TITLE
Add a `./mach grep` command

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5838]
`git grep` is slow since it searches the wpt dir now.

We want a `./mach grep` that proxies to `git grep $args -- components/ ports/` or something. (perhaps include `tests/` except for `tests/wpt`

**Comment by Manishearth** [comment]
You probably want to do something similar to [`./mach cargo`](https://github.com/servo/servo/blob/master/python/servo/devenv_commands.py#L17), however instead of `cd`ing, just append `--` followed by absolute paths to `components/`, `ports/` and other folders (obtain the absolute path via `self.context.topdir`)

**Comment by jdm** [comment]
Code: python/devenv_commands.py

**Comment by dhananjay92** [comment]
I would like to work on it.

**Comment by Manishearth** [comment]
Go ahead! :smile:

**Comment by dhananjay92** [comment]
Done. See [Commit 27943c0e](https://github.com/dhananjay92/servo/commit/27943c0ea57381d32a29874bf4ae7509440de45a) Tested and works fine.

Currently, it greps in `components/` and `ports/` directories only. Please let me know what other directories you want to include. I will add them and create a pull. :smile:

**Comment by Manishearth** [comment]
@dhananjay92 Everything in `tests/` except `tests/wpt`, everything in `python/`, everything in `etc/` and `resources/`

**Comment by dhananjay92** [comment]
Done. Created Pull #5842.

**Comment by Manishearth** [comment]
Fixed by #5842
