### ISSUE TITLE
Remove #[jstraceable] annotation for RootedVec

### ISSUE THREAD

**Issue by jdm** [servo/servo#5849]
The annotation is only used for types which we expect to store in other heap-allocated structures. Storing a `RootedVec<JS<Node>>` rather than `Vec<JS<Node>>` in such a structure will cause assertion failures, so we really don't want to encourage this behaviour.

Code: component/script/dom/bindings/trace.rs

**Comment by GlassAndOneHalf** [comment]
I'll have a go at this!

**Comment by psdh** [comment]
Can be closed, right?
