### ISSUE TITLE
Fix moving of Roots in codegen

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5853]
Depends on #5724 and #2661

Dictionaries that contain interface types (eg `MouseEventInit` in `MouseEventBinding`) have a `Root<T>` or `Option<Root<T>>` contained in them.

These values should not be moved, however they get moved [here](https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py#L876).

We should use a solution via `RootedArena` or similar (from #2661) to fix this, and then take out the `#[allow(moved_no_move)]` on `dom::bindings::codegen::Bindings` in `bindings/mod.rs`

**Comment by nox** [comment]
`Root<T>` can move now.
