### ISSUE TITLE
Hover state never disappears on rustbyexample.com

### ISSUE THREAD

**Issue by jdm** [servo/servo#5861]
Mouse over any of the non-text links on the pages, and you'll see them switch to the darker hover state but never leave it.

**Comment by mskrzypkows** [comment]
It seems that CSS hover selector is not properly handled. Test html page (style taken from rustbyexample.com):

```
<!DOCTYPE html>
<html>
<head>
<style>
	.btn{
		color:#ccc;
	}

	.btn:hover{
		color:#444;
	}
</style>
</head>
<body>
<div class="btn">
	Test text
</div>
</body>
</html>
```

**Comment by jdm** [comment]
This works now.
