### ISSUE TITLE
NodeTypeId should include CharacterData variant

### ISSUE THREAD

**Issue by jdm** [servo/servo#5869]
NodeTypeId is supposed to reflect the WebIDL inheritance hierarchy. All of Text/ProcessingInstruction/Comment inherit from CharacterData, which inherits from Node. There should be a CharacterDataTypeId value that differentiates between those, instead.

**Comment by Jinwoo-Song** [comment]
I'd like to try this one!

**Comment by Jinwoo-Song** [comment]
Uploaded a patch. https://github.com/Jinwoo-Song/servo/commit/0acf9f4126bbe2ecde88373419148b7006682cec

**Comment by nox** [comment]
Fixed by https://github.com/servo/servo/pull/5879.
