### ISSUE TITLE
Fix defineProperty after SM upgrade

### ISSUE THREAD

**Issue by snf** [servo/servo#5876]
We are mostly waiting for the next SpiderMonkey upgrade (https://github.com/servo/rust-mozjs/pull/144)

1. `defineProperty` should be able to convert `id` to a string
2. match the code in Gecko, use `js::IsInNonStrictPropertySet` to decide on NamedGetter
3. other changes probably

**Comment by frewsxcv** [comment]
Updates:

* SpiderMonkey upgrade has finished
* While it is around right now, `IsInNonStrictPropertySet` has been removed upstream
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1135993

**Comment by jdm** [comment]
Note: relevant Gecko code is now https://dxr.mozilla.org/mozilla-central/rev/b1156b0eb96fcb49966b20e5fcf6a01f634ea2ee/dom/bindings/Codegen.py#11045

**Comment by jdm** [comment]
Since that code delegates to CGProxyNamedPresenceChecker, which in turn delegates to CGProxyNamedGetter, it looks like we're almost doing the right thing. We just need to return the right value instead of `succeed()`.

**Comment by emilio** [comment]
I assume this can be closed now #13333 has landed?

**Comment by splav** [comment]
I will grep for the links to this bug in the code. If there is nothing left, this can be closed. I'll clean up the remaining comments in the next PR in order to save another useless CI round.

**Comment by splav** [comment]
I've found only one link and it was fixed by linked PR. So this can be closed. I'll remove the link in my next PR. (Should have done it in that PR...)
