### ISSUE TITLE
Add a `./mach check`

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5893]
Rustc has a neat flag, `-Z no-trans`, which runs everything except translation. If https://github.com/rust-lang/cargo/issues/595 happens, we could make great use of this to just typecheck code. Basically, `./mach check script` would typecheck script and then exit by internally calling `cd components/script; cargo rustc lib.rs -Z no-trans` or something.

**Comment by Manishearth** [comment]
(Might be a bit harder than that since Cargo is bad at just building deps)

**Comment by jdm** [comment]
Code: python/servo/devenv_commands.py

**Comment by Manishearth** [comment]
Not E-Easy, `cargo rustc` doesn't yet exist :)

**Comment by SimonSapin** [comment]
Maybe pick another name? (I don’t have a suggestion, sorry.) `check` and `test` sound kinda synonymous in my head. (I think `make check` was how we ran Servo’s tests at some point.)

**Comment by Manishearth** [comment]
`./mach typecheck` or something

**Comment by frewsxcv** [comment]
Update:

* [`cargo rustc` has landed](https://github.com/rust-lang/cargo/pull/1568)
* [cargo-check](https://github.com/rsolomo/cargo-check) is a relevant project

**Comment by SimonSapin** [comment]
I’ve been using e.g. `./mach cargo check -p script`, with cargo-check somewhere in my `$PATH`.

**Comment by SimonSapin** [comment]
That said, integrating in mach is easier to use than "go mess with your $PATH and install cargo-check yourself"

**Comment by frewsxcv** [comment]
Another idea for this: add it to the Travis script so everything gets typechecked upon opening a PR

**Comment by Manishearth** [comment]
It can't transitively typecheck, though. If you do it on travis it will build the whole thing except `servo` and typecheck the last one -- it can't use metadata from a previous `-Z no-trans` to work on the next one, it needs all deps to be fully built.

**Comment by nox** [comment]
This was done.
