### ISSUE TITLE
TextEncoder::Constructor should not trim whitespace / lowercase its label

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5900]
`encoding_from_whatwg_label` already does that correctly.

Blocks #5601.

* Spec: <https://encoding.spec.whatwg.org/#dom-textencoder>.
* Code: `components/script/dom/textdecoder.rs`.
* Test: `/encoding/api-invalid-label.html`.

**Comment by SimonSapin** [comment]
I’m pretty sure I did that in passing at some point of the current rustup. It must have been lost if a rebase.

**Comment by Ms2ger** [comment]
Yeah, I removed it; I don't believe it belongs there
