### ISSUE TITLE
Inline stacked elements are not visible within another stacking context

### ISSUE THREAD

**Issue by Adenilson** [servo/servo#5910]
An inline element that has its own stacking context (SC) will not be displayed if it is within the flow of another element that also creates a stacking context.

In display_list_builder, currently we only create a SC if an element has a filter. By removing this check and running a simple test case as: http://codepen.io/pen/

The dumped display list (DL) is: https://gist.github.com/Adenilson/f70ca9249a5002a16d4c

By not creating a SC for inline elements, the DL is instead: https://gist.github.com/Adenilson/f1211796b449157fe4a5

While this issue is not investigated and fixed, we can't have the right behavior that would be to create a SC for inline elements not mattering if it has a filter or not (as it would cause regressions, currently 69 failing tests).

**Comment by Adenilson** [comment]
This probably affects block level elements too.

**Comment by mrobinson** [comment]
@Adenilson The test case for this didn't seem to link properly. Do you happen to still have it somewhere?

**Comment by Adenilson** [comment]
@mrobinson I can have a look on my old backups, but that is going to take a few days.

Can't you recreate the test case based on the display list dump + description of the bug?

Back in the day (2 years ago), Servo would create a SC for a filtered element (e.g. blur).

If that still holds true, I would start with a simple div with a z-index defined together with a filtered image (e.g. blur) as that should prompt the reported scenario (i.e. inline element with its own SC if within the flow of another element that also has a SC).

**Comment by mrobinson** [comment]
Okay. This seems to be working now, so I'm going to just close this issue. Thanks for the quick response!
