### ISSUE TITLE
Cannot Build: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by sneakyness** [servo/servo#5917]
Got pre-reqs via port, cloned the git repo, tried `./mach build` and got the following error:

https://gist.githubusercontent.com/sneakyness/291546375a0cd17fab78/raw/97541beb685b97c3a7a745bda3038fad670da6e4/gistfile1.sh

I joined #servo on moz irc, apparently they've never seen this before. 

I tried manually printing out the s3 urls for cargo and rust, and extracting them to the correct location, then removing those steps from the build script, but this only created more errors.

**Comment by jdm** [comment]
What version of python are you using?

**Comment by jdm** [comment]
`15:05 <sneakyness> I've got OpenSSL 1.0.2a 19 Mar 2015`

**Comment by sneakyness** [comment]
I'm using the version that port asked me to install. `python27`

**Comment by jdm** [comment]
What's the output of `python27 --version`? Also `python --version`.

**Comment by onodera-punpun** [comment]
I'm having the exact same problem. I'm using CRUX linux with openssl (I don't know if that matters).

``
~ python --version
Python 2.7.9
``
Also ``python27`` doesn't exist for me, ``python2`` and ``python2.7`` do though.

**Comment by jdm** [comment]
Which version of openssl is installed for you @onodera-punpun?

**Comment by onodera-punpun** [comment]
@jdm 

``
~ openssl
OpenSSL> version
OpenSSL 1.0.2a 19 Mar 2015
``

**Comment by jdm** [comment]
By the way, http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error should be a usable workaround for this problem while it's blocking people. It just requires a small addition to bootstrap_commands.py.

**Comment by jdm** [comment]
Specifically:
```
import ssl

# This restores the same behavior as before.
context = ssl._create_unverified_context()
urllib.urlopen("https://no-valid-cert", context=context)
```

**Comment by onodera-punpun** [comment]
After patching `servo/python/servo/bootstrap_commands.py`` I get:

```
~/usr/src/git/servo ./mach --release
Traceback (most recent call last):
  File "./mach", line 25, in <module>
    main(sys.argv)
  File "./mach", line 21, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "./python/mach_bootstrap.py", line 103, in bootstrap
    mach.load_commands_from_file(os.path.join(topdir, path))
  File "/home/onodera/usr/src/git/servo/python/mach/mach/main.py", line 266, in load_commands_from_file
    imp.load_source(module_name, path)
  File "/home/onodera/usr/src/git/servo/python/servo/bootstrap_commands.py", line 17, in <module>
    from servo.command_base import CommandBase, cd, host_triple
  File "./python/servo/command_base.py", line 11, in <module>
    urllib.urlopen("https://no-valid-cert", context=context)
NameError: name 'urllib' is not defined
```

Patch used:
```
--- servo/python/servo/bootstrap_commands.py.orig	2015-05-02 18:03:45.348993015 +0200
+++ servo/python/servo/bootstrap_commands.py	2015-05-02 19:12:18.268750275 +0200
@@ -7,6 +7,10 @@
 import sys
 import tarfile
 import urllib2
+import ssl
+
+context = ssl._create_unverified_context()
+urllib.urlopen("https://no-valid-cert", context=context)
 
 from mach.decorators import (
     CommandArgument,
```

**Comment by jdm** [comment]
Huh, very interesting. The original reporter was on a mac, so my suspicion is that something changed in OpenSSL...

**Comment by onodera-punpun** [comment]
Just to clarify, downgrading to python 2.7.8 solves the initial ``SSL: CERTIFICATE_VERIFY_FAILED`` eror, but not the ``Peer certificate cannot be authenticated with given CA certificates`` error I mentioned above.

**Comment by learnopengles** [comment]
I had a problem with this one too, but it was fixed after I added this:

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

I was lucky and didn't have the problem with curl afterwards.

**Comment by sneakyness** [comment]
@learnopengles would you mind sharing your `bootstrap_commands.py`? Also did you downgrade python to 2.7.8 too?? Thanks

**Comment by onodera-punpun** [comment]
@sneakyness either downgrade to 2.7.8 OR simple add these two lines to your ``bootstrap_commands.py``.

**Comment by learnopengles** [comment]
My python is 2.7.6, otherwise the only change I did was adding those two lines, so as follows:

import sys
import tarfile
import urllib2
+import ssl
+ssl._create_default_https_context = ssl._create_unverified_context

**Comment by skade** [comment]
For me, this was a python installation through ports that was accidentally picked up by the system python installation.

**Comment by larsbergstrom** [comment]
The resolution for this issue is: upgrade python.

**Comment by smizon** [comment]
So monkey patching the https protocol for temp fix is ok, 

`try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context  `


But how would you globally change the path to the CA cert?

Setup is:
 Current using python3.4 on Centos7, using Flask, noticed importing SSL and certifi changes the bundle to pre-installed CAs, but would like to change this to the default server ones.
