### ISSUE TITLE
Fedora 22 incompatible libOSMesa.so while building

### ISSUE THREAD

**Issue by csoriano1618** [servo/servo#5922]
Hi,
I installed libOSMesa devel 32 bits, but seems the version in Fedora is too new and this error appears while doing ./mach build:
note: /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/5.0.1/../../../libOSMesa.so when searching for -lOSMesa

Package: mesa-libOSMesa-devel-10.5.1-1.20150314.fc22.i686
Name        : mesa-libOSMesa-devel
Arch        : i686
Epoch       : 0
Version     : 10.5.1
Release     : 1.20150314.fc22

**Comment by jdm** [comment]
cc @glennw

**Comment by nox** [comment]
Is this still true?

**Comment by dralley** [comment]
I was able to build Servo on Fedora 29 a year ago, so this can definitely be closed.
