### ISSUE TITLE
Ensure DOM types have their base type as the first field

### ISSUE THREAD

**Issue by jdm** [servo/servo#5927]
#5926 fixed an instance where the first field of various derived DOM types was a Reflector, instead of the inline parent type. It would be best to prevent this at compile time, but could be challenging as the WebIDL inheritance information isn't available anywhere in Rust code except in the hierarchy of up/downcasting traits.

**Comment by ecoal95** [comment]
Maybe a DOM test like the exposed interfaces test (`tests/wpt/mozilla/tests/mozilla/interfaces.html`), but testing JS `__proto__` could be the easiest way to go.

I'm not too much into rustc plugins, but I think it'd be really difficult to make this work as a compiler plugin, at least automatically (thought of passing the parent type as argument, but that has the same problem...).

The problem with the DOM test would be having the inheritance map duplicated, but the check should be easy enough, and we can have the whole map from the beginning and just report the error if the interface is implemented...

**Comment by kmcallister** [comment]
> the WebIDL inheritance information isn't available anywhere in Rust code except in the hierarchy of up/downcasting traits

But those traits are generated by a Python script we control, so it could also generate whatever metadata we need for the checks.

**Comment by kmcallister** [comment]
cc @Manishearth

**Comment by Manishearth** [comment]
We could simply whitelist our pure inteerfaces and span another lint whenever we see `Reflector`. Easy change to the existing inheritance lint.

We could also generate a bunch of dead code that tries to access the correct first field. Type safety ftw.

**Comment by jdm** [comment]
@Ms2ger Why'd you close this?

**Comment by Ms2ger** [comment]
It's fixed and linted, last I heard. (Last I heard, you were on vacation, though :))

**Comment by Manishearth** [comment]
https://github.com/servo/servo/blob/master/components/plugins/lints/inheritance_integrity.rs

**Comment by ecoal95** [comment]
I don't think it's fixed, the lint as of right now (if I'm not wrong) just ensures that a dom struct is correctly formed, but does not check for inheritance (if the dom struct corresponds to the correct parent, or there's only a reflector but the struct should inherit from another struct), which is the point of this issue.

**Comment by Manishearth** [comment]
Oh, yeah, it doesn't do that. We *could* read the webidl during expansion time but that might get hackish.

**Comment by ecoal95** [comment]
Yes, I agree with @Manishearth about that: parsing the webidl there might not be a good option.

Another option I thought about was passing the parent structure (if any) as argument to the marker (I suppose it's possible, correct me if I'm wrong), but you won't forgot the dom struct field if you remember to use the argument.

I made a little experiment about this modifying the exposed interfaces test (https://github.com/ecoal95/servo/commit/8521beb33b1d3f3392210b4b4a090fafa71d0697). Actually it can detect that the specified inheritance is correct, via instanceof checking, but fails to detect if the structure has inheritance and it has not been specified.

That's because our bindings doesn't seem to "fill" the `__proto__.name` field, but I believe it can be modified to do that, and it could even be fixed automatically with the SM upgrade, so I'll wait till it lands and check after.

**Comment by Manishearth** [comment]
Why not just generate a rust unit test for this? `fn foo(x:  $type) { let _ : $parenttype = x.$parenttype}`?

**Comment by jdm** [comment]
The parent field is private, which makes it impossible to automatically generate afaict.

**Comment by Manishearth** [comment]
Oh, right. Bummer. I could autogenerate a `_parent()` hidden method for the tests.

**Comment by drbo** [comment]
Why is this I-safety? It seems that the SpiderMonkey bindings should be designed so that this can't cause memory unsafety.

**Comment by Manishearth** [comment]
That's not possible without severely impacting usability. Spidermonkey's API was not designed with Rust safety in mind, and it's really hard to create bindings which are 100% sound. We use lints and other things to fill up the gap.

**Comment by jdm** [comment]
This isn't something that our SpiderMonkey bindings can enforce. This is a hole in our implementation of inheritance, which is orthogonal.

**Comment by pshaughn** [comment]
Is this still a problem? If so has handling it with a lint, instead of in the compile as such, been considered?

**Comment by pshaughn** [comment]
Is this still a potential problem? Has anything in the language itself changed in a way that'd make it easier now?

**Comment by jdm** [comment]
We have static assertions that this is the case, iirc: https://github.com/servo/servo/blob/66aebfdbee6ae10fe7ea65224bf202f53b2efceb/components/script/dom/bindings/codegen/CodegenRust.py#L2213-L2253
