### ISSUE TITLE
Rename ScriptTask to Page(?)

### ISSUE THREAD

**Issue by Munksgaard** [servo/servo#5930]
I was going through the code in src/components/script/ and saw the following note[0]:

```rust
/// Information for an entire page. Pages are top-level browsing contexts and can contain multiple
/// frames.
///
/// FIXME: Rename to `Page`, following WebKit?
#[jstraceable]
pub struct ScriptTask {
```

0: https://github.com/servo/servo/blob/master/components/script/script_task.rs#L270

Should we do this? Otherwise we should probably remove the FIXME.

**Comment by Ms2ger** [comment]
That sounds overly confusing, IMO

**Comment by jdm** [comment]
Yeah, a ScriptTask encompasses more than a single page. Let's remove the FIXME.
