### ISSUE TITLE
Print a warning about performance after a debug build completes

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#5933]
When running `mach build` without the `--release` flag, print a message to the user about performance.  Something like:

> Warning: This is an un-optimized debug build. For performance testing, use `./mach build --release` to enable compiler optimizations.

The goal is to prevent users from unknowingly doing benchmarking or perf comparisons on debug builds.  The message can be printed at the end of the `build` function here:

https://github.com/servo/servo/blob/master/python/servo/build_commands.py

**Comment by jabbrass** [comment]
Thanks for the low hanging fruit. Hopefully I can submit a PR involving Rust next time... :)
