### ISSUE TITLE
util::geometry::Au uses wrapping arithmetic

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#5948]
The implementations of `Add`, `Sub`, and `Mul` for `util::geometry::Au` are based on `i32::wrapping_{add,sub,mul}`. Is this really the desired behavior?

CC @pcwalton

**Comment by pcwalton** [comment]
I think so, yes. It's quite possible for layout calculations to overflow and that is not a bug that's worth fixing, since there's no correct thing to do on a layout overflow other than fall back to bignums, which is obviously impractical from a performance POV.

**Comment by SimonSapin** [comment]
So it’s not that we rely on wrapping behavior, it’s an error case. So why not just "normal" arithmetic operations, which panic on overflow but only in debug builds?

**Comment by pcwalton** [comment]
Because fuzzing Servo would cause spurious crashes in debug builds.

**Comment by nox** [comment]
Seems like this can be closed.
