### ISSUE TITLE
Intermittent reftest failure in iframe/hide_layers1.htm

### ISSUE THREAD

**Issue by jdm** [servo/servo#5950]
We saw this on the original upgrade merge attempt, and on a subsequent PR merge as well.

```
---- iframe/hide_layers1.html == iframe/hide_layers_ref.html stdout ----
	thread 'iframe/hide_layers1.html == iframe/hide_layers_ref.html' panicked at 'rendering difference: /tmp/servo-reftest-000098-diff.png', ../../tests/reftest.rs:336
```

**Comment by glennw** [comment]
This is due to https://github.com/servo/servo/issues/5243.

For a while it didn't seem to be affecting the build machines, but since it is now, we should probably disable the affected reftests until the bug above is resolved.

**Comment by glennw** [comment]
Fixed by https://github.com/servo/servo/pull/6031
