### ISSUE TITLE
Nodes that are not attached to the Document are still accessible through getElementById

### ISSUE THREAD

**Issue by mukilan** [servo/servo#5963]
```
<!doctype html>
<meta charset=utf-8>
<title>Document.getElementById must not return nodes not present in document</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<body>
    <div id="log"></div>
    <div id="outer">
        <div id="middle">
            <div id="inner"></div>
        </div>
    </div>
</body>
<script>
  test(function () {
    var outer = document.getElementById("outer");
    var middle = document.getElementById("middle");
    var inner = document.getElementById("inner");
    outer.removeChild(middle);

    var new_el = document.createElement("h1");
    new_el.id = "heading";
    inner.appendChild(new_el);
    // the new element is not part of the document since
    // "middle" element was removed previously
    assert_equals(document.getElementById("heading"), null);
  }, "Document.getElementById must not return nodes not present in document");
</script>

```

Adding the above test to the MANIFEST and running it produces the following output:
```
Expected PASS, got FAIL
assert_equals: expected null but got Element node <h1 id="heading"></h1>
```

The incorrect behaviour arises due to the fact that when we remove a node [we clear the ```IS_IN_DOC``` flag only for the node removed](https://github.com/servo/servo/blob/16a7c792b564a6eab48391865a7060b8dba38284/components/script/dom/node.rs#L1669) but not for its descendants (in the test above, "inner" div still has the flag set). When a new [node is inserted](https://github.com/servo/servo/blob/16a7c792b564a6eab48391865a7060b8dba38284/components/script/dom/node.rs#L1532),  the parent node's ```IS_IN_DOC``` flag is used to determine the flag for the newly inserted node, and when the [bind_to_tree overload](https://github.com/servo/servo/blob/16a7c792b564a6eab48391865a7060b8dba38284/components/script/dom/element.rs#L1466) is called, we [register](https://github.com/servo/servo/blob/16a7c792b564a6eab48391865a7060b8dba38284/components/script/dom/element.rs#L1473) the newly created element with its ID

**Comment by pgonda** [comment]
so is the task here to add functionality to Node::remove to remove set all the children IS_IN_DOC flags to false?  Does anything need to be changed in bind_to_tree?

**Comment by jdm** [comment]
Yes, as well as add the new test to http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/dom/nodes/Document-getElementById.html . bind_to_tree should not need to be changed.

**Comment by pgonda** [comment]
I'll take this one!

**Comment by pgonda** [comment]
I am getting this warning, how can I fix it?
```   Compiling script v0.0.1 (file:///Users/peter/workspace/opensource/servo/components/servo)
servo/components/script/dom/node.rs:1808:13: 1808:18 warning: #[no_move] type `dom::bindings::js::Root<dom::node::Node>` moved, #[warn(moved_no_move)] on by default
servo/components/script/dom/node.rs:1808         for child in node.children().map(|c| c.root()) {
                                                                                       ^~~~~
servo/components/script/dom/node.rs:1808:13: 1808:18 warning: #[no_move] type `core::option::Option<dom::bindings::js::Root<dom::node::Node>>` moved, #[warn(moved_no_move)] on by default
servo/components/script/dom/node.rs:1808         for child in node.children().map(|c| c.root()) {```

**Comment by jdm** [comment]
Use
```rust
for child in node.children() {
    let child = child.root();
}
```

**Comment by mukilan** [comment]
Please note that ```node.children()``` will return only the immediate children of the node to be removed and not all descendants, so I think we should use ```node.traverse_preorder()```. Since ```traverse_preorder``` will also visit the ```node``` itself, we don't have to clear the flag for it seperately. i.e the only change that needs to be made is to replace the line
```
node.set_flag(IS_IN_DOC, false);
```
with 

```
for child in node.traverse_preorder() {
     let child = child.root();
     child.set_flag(IS_IN_DOC, false);
}
```

**Comment by pgonda** [comment]
I did not see that method, thanks!
