### ISSUE TITLE
Styles not loaded for http://benjamin.smedbergs.us/blog/

### ISSUE THREAD

**Issue by bsmedberg** [servo/servo#5975]
./mach run http://benjamin.smedbergs.us/blog/

My website shows up without any styling. This is apparently unusual according to jdm, so I should file it. I'm going to try and do some debugging to see if there's an obvious reason like CSS parsing errors.

**Comment by jdm** [comment]
For parse errors, you'll want to run with RUST_LOG=style::parser

**Comment by bsmedberg** [comment]
INFO:style::parser: 7:1 Invalid rule: '@import url("/bdstyle.css")'
So perhaps this is CSS @import isn't implemented yet?

**Comment by jdm** [comment]
That seems likely to me.

**Comment by SimonSapin** [comment]
That’s correct. The parsing isn’t hard, but it’s unclear to me how a network fetch should be triggered from the CSS parser. Though maybe as a first step it could just be block and fetch/parse sequentially.

**Comment by bsmedberg** [comment]
I'm not completely familiar with how @import works with the CSS priority order. If it's possible to represent them as entirely separate style sheets, that sounds much preferable to blocking the parser.

**Comment by jdm** [comment]
This works now.
