### ISSUE TITLE
embedding: provide better main loop integration than cef

### ISSUE THREAD

**Issue by zmike** [servo/servo#5977]
CEF has two methods for main loop integration: running the main loop and iterating the main loop.

This is not ideal for embedding applications since it requires them to either run the CEF main loop in another thread/process (eek) or run a timer that constantly polls on the main loop iteration function (starving the app for cpu time).

Servo could improve upon this in a number of ways, such as by providing a function which iterates the main loop and returns the time until the main loop should be iterated again.

Ideally, an app should only iterate the browser main loop as necessary.

Commence neckbearding!

@glennw @pcwalton @larsbergstrom

**Comment by pcwalton** [comment]
Ideally CEF should be calling callbacks to let you know when you need to call `CefDoMessageLoopWork()`. Does that not work?

**Comment by zmike** [comment]
CEF has no concept of things like this because it has no actual main loop; these functions are just a wrapper around the Chromium/Blink main loop, which provides no mechanism for determining when to call or not call it. According to one comment I found on the topic, "it's too hard".

**Comment by pcwalton** [comment]
Interesting. Perhaps we should provide a callback that tells the hosting app "hey, please call the event loop".

**Comment by zmike** [comment]
How would you schedule this callback when the event loop is not being processed?

**Comment by pcwalton** [comment]
Call it on a separate thread. Then the.embedder can kick its main loop awake from that thread via the normal OS mechanisms for that.

**Comment by zmike** [comment]
I have a patchset which implements this, PR is pending.
