### ISSUE TITLE
Split servo tests to a separate brach

### ISSUE THREAD

**Issue by Rezonansowy** [servo/servo#5983]
The `servo/test` folder contents are growing. When you click the color bar on the project's main page you see that 92.2% is HTML. It would be good to create a branch called `servo-tests` for it, I think. It also decrease the size of downloaded code.

**Comment by Ms2ger** [comment]
I don't see how that would work.

**Comment by Rezonansowy** [comment]
@Ms2ger Why do you close it so fast? It could be achieved very simply, just like other branches: `rust-png` or `rust-core-graphics`. No reason to keep such big thing together.

**Comment by larsbergstrom** [comment]
@Rezonansowy The majority of those tests are already external and are imported from the web platform tests repository. The few that are not (our ref and content tests) will hopefully be upstreamed into WPT, so are not worth breaking out for now.
