### ISSUE TITLE
CORS check compares strings, not URL components

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#6020]
https://fetch.spec.whatwg.org/#cors-check includes:
> Let *origin* be the result of parsing `Access-Control-Allow-Origin` in response's header list. 
> …
> If request's origin, serialized and utf-8 encoded, is not *origin*, return failure. 

The corresponding code in Servo is in `script::cors::allow_cross_origin_request`:
```rust
        Some(&AccessControlAllowOrigin::Value(ref url)) =>
            url.scheme == req.origin.scheme &&
            url.host() == req.origin.host() &&
            url.port() == req.origin.port(),
```

But comparing (scheme, host, port) components of parsed URL is not necessarily the same as comparing a serialized URL to a string. Maybe `AccessControlAllowOrigin::Value`’s value should be a `String` rather than a parsed `Url`?

**Comment by Manishearth** [comment]
cc me

**Comment by snf** [comment]
Btw, we have this UrlHelper http://doc.servo.org/script/dom/urlhelper/struct.UrlHelper.html#method.SameOrigin

**Comment by SimonSapin** [comment]
I don’t know if that either is equivalent to what the spec says.

**Comment by Manishearth** [comment]
That uses https://html.spec.whatwg.org/multipage/browsers.html#same-origin, which treats origins as structured urls, not strings.

**Comment by SimonSapin** [comment]
https://github.com/hyperium/hyper/issues/526 was fixed in https://github.com/hyperium/hyper/commit/ed458628e54bd241b45f50fb0cf55a84ffb12205 , which we’re picking up in https://github.com/servo/servo/pull/6591.
