### ISSUE TITLE
Overflow in /script/dom/characterdata.rs::ReplaceData

### ISSUE THREAD

**Issue by jgraham** [servo/servo#6040]
(pid:25369) "thread 'ScriptTask' panicked at 'arithmetic operation overflowed',
    /home/jgraham/develop/servo/components/script/dom/characterdata.rs:107"
 
The offending code:

    let count = if offset + count > length {

**Comment by aneeshusa** [comment]
Looks like this got fixed in #6064.

**Comment by jdm** [comment]
Yep!
