### ISSUE TITLE
Line-length-limit bikeshed

### ISSUE THREAD

**Issue by waddlesplash** [servo/servo#6041]
from IRC:
```
<@mbrubeck> pcwalton: That's interesting - I thought `mach test-tidy` would reject >100char lines.
<@pcwalton> it doesn't, because of the codegen in script IIRC
<@mbrubeck> Oh, it only rejects at 160.
<@pcwalton> it only rejects *really* long ones
<@mbrubeck> generated bindings are excluded from tidy completely.
<@pcwalton> oh, hmm
<@pcwalton> I wonder why we didn't go for 100 across the board then
<@mbrubeck> We have 1620 lines to fix before we can enforce a 100-char limit. :/
```

CC @mbrubeck @pcwalton @jdm @Ms2ger -- hopefully I didn't miss anyone...

**Comment by Ms2ger** [comment]
I limited to 160 because that was about the smallest number that didn't require me fixing a million cases; I'd definitely like to reduce that to 100 or even 80.

**Comment by larsbergstrom** [comment]
I'm a little worried about trying to get to even 100 with Rust. There's a lot of rightward drift from nested `match`, closures, etc. I suspect that if we try to go to 80, when we find that's very hard for lots of code we'll start contorting the code (e.g., lifting things into functions just so they get left-dented) and switching from 4 spaces to 2 just to meet a standard that is mainly motivated by small, narrow screens/terminals/or in-browser UIs trying to do side-by-side diffs with a ton of extra HTML doogadgetry inbetween.

I'd probably want to sit down with the 1620 lines and make sure that truncating them is just a matter of indenting function calls or parameter lists across multiple lines and not changing the expression nesting.

**Comment by frewsxcv** [comment]
'bikeshed' is my middle name! Right now, we throw an error if it rejects more than 150 characters on a line. Even though people here are talking about 80 or 100 characters, for the sake of sanity, I am going to reduce that to 120 and see how it goes.

**Comment by frewsxcv** [comment]
Just opened #6174 reducing line length from 150 to 120 characters

**Comment by nox** [comment]
The long lines that infuriate me the most are the patterns for EventTargetTypeId. Maybe we could also generate one value per leaf type? For example, generate a const TextTypeId equal to `EventTargetTypeId::Node(NodeTypeId::CharacterData(CharacterDataTypeId::Text))`.
