### ISSUE TITLE
"mach build" should default to building with the previously-built profile

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#6048]
This is a follow-up to #6038.  If no build mode (`--dev` or `--release`) is specified, and exactly one of `components/servo/target/debug` or `components/servo/target/release` exists, then `mach build` should set a default mode to match that previously-built target.

This means that you only need to pass `--dev` or `--release` the first time you build, and subsequent builds would inherit the setting automatically (unless you explicitly build both profiles in the same repo).

This could share code with the [get_binary_path](https://github.com/servo/servo/blob/master/python/servo/post_build_commands.py) function used by `mach run` for similar purposes.

**Comment by jinankjain** [comment]
In this just need to check that if release or debug exist then choose that as default build mode if both exist then through error am I correct ?

**Comment by mbrubeck** [comment]
Right.  And we should only check this if the existing checks (command-line options, .servobuild file) fail to set either `dev` or `release`.

**Comment by jinankjain** [comment]
Check PR @mbrubeck
