### ISSUE TITLE
Implement canvas pattern

### ISSUE THREAD

**Issue by hyowon** [servo/servo#6056]
I'm trying to write a patch for this issue.
This is a draft which only works with patterns created from HTMLImageElement and 'no-repeat'.
hyowon@e392cd7
I want to confirm that this patch is going to the right path.
It depends on servo/rust-azure#156

**Comment by jdm** [comment]
That certainly appears like the right path to me.

**Comment by frewsxcv** [comment]
Was this completed in #6157 ?

**Comment by jdm** [comment]
Yes, we can file more specific issues about any pieces that are still unimplemented.
