### ISSUE TITLE
Throw a SyntaxError if the WebSocket URL can't be parsed.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6061]
Blocks #6060.

* Spec: <https://html.spec.whatwg.org/multipage/#dom-websocket>, <https://html.spec.whatwg.org/multipage/#parse-a-websocket-url%27s-components>.
* Code: `components/script/dom/websocket.rs`.
* Test: `/websockets/Create-invalid-urls.htm`.

**Comment by Nashenas88** [comment]
The second url is incorrect. It should be: https://html.spec.whatwg.org/multipage/#parse-a-websocket-url's-components

**Comment by Nashenas88** [comment]
Working on a fix.

**Comment by Nashenas88** [comment]
Discussed some of my confusion with KiChjang on irc, and he discovered that websocket::Client::connect does not conform to rfc6455 section-4.1. I won't be able to code this completely to spec (namely step 12 will need to return an additional Url object), but I'll add TODO and FIXME comments. Bug filed with rust-websocket here https://github.com/cyderize/rust-websocket/issues/38

**Comment by jdm** [comment]
Good detective work. Thanks @Nashenas88!

**Comment by Nashenas88** [comment]
Did I do the fixups properly?
