### ISSUE TITLE
Radio button does not become de-selected when I click another one

### ISSUE THREAD

**Issue by jruderman** [servo/servo#6073]
Servo on Mac

./mach run --release "https://en.wikipedia.org/w/index.php?title=2015_Philadelphia_train_derailment&action=history"

Click the left radio button on the fourth history entry. The previously selected radio button in the same column should be un-selected, but isn't. (But it does become un-selected if I hover over it!)

**Comment by jdm** [comment]
Ooh, I bet we're not marking the radio button dirty when deselecting it. We should call `force_relayout` from `update_checked_state` in `components/script/dom/update_checked_state.rs`.

**Comment by Manishearth** [comment]
That seems correct. Forcing a relayout by resizing the window brings them to the correct state.

**Comment by WriterOfAlicrow** [comment]
Thanks for the easy bug! Finally a chance to contribute to an open source project!

There's no file called ```components/script/dom/update_checked_state.rs```, but I found ```update_checked_state``` in ```components/script/dom/htmlinputelement.rs```, and made the change jdm mentioned. Works fine now, so I'll go ahead and create a pull request.

**Comment by Manishearth** [comment]
Awesome, thanks!

(yes, the wrong file was mentioned)

**Comment by larsbergstrom** [comment]
This has been fixed.
