### ISSUE TITLE
thread 'LayoutWorker worker 1/6' panicked at 'Link to containing block not established; perhaps you forgot to call `set_absolute_descendants`?'

### ISSUE THREAD

**Issue by jruderman** [servo/servo#6078]
Servo on Mac

./mach run --release "http://www.washingtonpost.com/blogs/innovations/wp/2015/05/04/google-patents-a-way-for-self-driving-cars-to-understand-a-cyclists-hand-signals/"

    thread 'LayoutWorker worker 1/6' panicked at 'Link to containing block not established; perhaps you forgot to call `set_absolute_descendants`?', /Users/jruderman/code/servo/components/layout/flow.rs:1378
    stack backtrace:
       1:        0x110f3b64f - sys::backtrace::write::h6990067d88907b48zVr
       2:        0x110f3f024 - panicking::on_panic::he976cdbadffd9e1bEVv
       3:        0x110f2ac55 - rt::unwind::begin_unwind_inner::ha519446d83876aa8nDv
       4:        0x1100ac9af - rt::unwind::begin_unwind::h14101999349767858264
       5:        0x1100f914b - table_row::TableRowFlow.Flow::assign_inline_sizes::h501453bfdea82163MKs
       6:        0x1101b7d5d - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::h9124fed2689a05ccG8p
       7:        0x1101b808d - parallel::assign_inline_sizes::hd0aa988704d3dca3Mbq
       8:        0x11018e911 - boxed::F.FnBox<A>::call_box::h14263597929771609667
       9:        0x1101770f7 - rt::unwind::try::try_fn::h11132619767978337967
      10:        0x110f40d18 - rust_try_inner
      11:        0x110f40d05 - rust_try
      12:        0x1101773e2 - boxed::F.FnBox<A>::call_box::h10100730613896979925
      13:        0x110f3d9ad - sys::thread::Thread::new::thread_start::h5fcf8fe12ec3c274mYu
      14:     0x7fff8e43e267 - _pthread_body
      15:     0x7fff8e43e1e4 - _pthread_start

**Comment by suhr** [comment]
Can confirm the same issue on linux.
