### ISSUE TITLE
servo should not depend on msttcorefonts

### ISSUE THREAD

**Issue by genodeftest** [servo/servo#6080]
msttcorefonts (or, as microsoft calls them: Core fonts for the Web) are proprietary and thus not suitable for an open source project.
Instead servo could use the liberation fonts [1] published under a free license and with source code available.

[1] https://fedorahosted.org/liberation-fonts/

**Comment by glennw** [comment]
I haven't checked this, but I believe we shouldn't need any dependency on fonts now. I changed the font cache to fall back to system default fonts (on Linux at least). If someone without those fonts installed is able to test successfully, we could probably just remove that from the documentation.

**Comment by genodeftest** [comment]
you are right, servo compiles and runs without msttcorefonts installed. Why is it noted as requirement on Readme.md?

**Comment by jdm** [comment]
We used to fall back to those fonts and panic if they were unavailable.
