### ISSUE TITLE
Can't log in to Github

### ISSUE THREAD

**Issue by jdm** [servo/servo#6085]
This used to work, and now it just returns to github.com/session/ with empty login fields.

**Comment by fbau123** [comment]
It worked for me on development build.
I found some problems:
- It didn't let me publish a comment, the Comment button did nothing.
- Hitting back while on the comments `<textarea>` actually went back in history

**Comment by KiChjang** [comment]
@jdm is this still occurring?

**Comment by jdm** [comment]
Nope!
