### ISSUE TITLE
Replace /usr/bin/find hacks in dependency makefiles with Cargo variables

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#6088]
Some of our dependencies makefiles have hacks like this:

https://github.com/servo/rust-azure/blob/11d7292919a365c55ca6204c465c5eeefcabfe05/makefile.cargo#L62
```Makefile
SKIA_OUTDIR = $(shell find $(OUT_DIR)/../.. -name 'skia-*' -type d)/out
```
… which break when e.g. there is more then one directory matching `skia-*` (multiple versions have been built without `cargo clean`).

Instead, we should be using Cargo’s metadata and `DEP_*` environment variables: http://doc.crates.io/build-script.html#the-links-manifest-key

**Comment by SimonSapin** [comment]
This should fix issues like this:

http://logs.glob.uno/?c=mozilla%23servo#c213053
> 07:38	KiChjang	i'm having trouble building servo now
> 07:38	KiChjang	using mach build, it tells me that there's an error in skia-c.h
> 07:39	KiChjang	i mean, an error in azure-c.cpp
> 07:39	KiChjang	says it cannot find skia-c.h
> 11:30	Manishearth	crowbot: ping KiChjang delete all azure and skia thingies from your target/debug dir. rm -rf components/servo/target/debug/*/*azure* and same for skia

**Comment by SimonSapin** [comment]
Based on `cargo-home/git/checkouts$ grep -Rl 'shell find'|cut -d/ -f1|sort -u`:

* [ ] libfontconfig
* [ ] mozjs
* [ ] rust-azure
* [ ] rust-core-foundation
* [ ] rust-core-graphics
* [ ] rust-core-text
* [ ] rust-egl
* [ ] rust-fontconfig
* [ ] rust-freetype
* [ ] rust-io-surface
* [ ] rust-layers
* [ ] rust-mozjs
* [ ] rust-stb-image
* [ ] rust-xlib
* [ ] skia

**Comment by mbrubeck** [comment]
It looks like the rust-freetype one is innocent (it's just running `find -name *.rs` within its source directory).

**Comment by mbrubeck** [comment]
If anyone would like to help out with the remaining packages, see the various pull requests linked above for examples of how to fix this.

**Comment by asbaker** [comment]
These are also all innocently finding within their source directories:
rust-core-graphics
rust-core-foundation 
rust-core-text
rust-egl
rust-io-surface
rust-layers
rust-stb-image
rust-xlib

That should just leave **rust-mozjs** as the only offender.

I'll take a look and open a PR tomorrow evening.
