### ISSUE TITLE
frequent window resizes on linux create massive resize queue

### ISSUE THREAD

**Issue by zmike** [servo/servo#6090]
* Load http://s27.postimg.org/vqbtrolyr/servo.jpg
* Grab window edge to engage resize mode
* Wildly flail mouse arm for 10-15 seconds
* Release mouse button

At this point, Servo will continue to perform each resize action triggered during step 3 on the contents despite the window no longer being resized.

**Comment by zmike** [comment]
This does not occur in embedded applications, so it may just be related to the glutin port?

**Comment by ben0x539** [comment]
This is pretty noticable for me even on reasonable resize operations, on any page. Resizing a window once at "normal" speed makes it so I can watch the window contents catch up to the new dimensions after letting go of the mouse over the next second or two. Made me think I must have been using a debug build by accident.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/issues/5499
