### ISSUE TITLE
Incorrect layout for inline-block elements in RTL flows

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#6092]
In this test case, the div should appear at the top right of the page.  In Servo it does not appear anywhere on-screen:

``` html
<html>
  <head>
    <style>
      body { direction: rtl; }
      div {
        display: inline-block;
        border: 1px solid red;
        width: 100px;
        height: 100px;
      }
    </style>
  </head>
  <body>
    <div></div>
  </body>
</html>
```

This is probably caused by similar issues to #6006.

**Comment by nhirata** [comment]
Not sure if this deserves a separate bug or not, the date is incorrect as well (something from bug 459035; https://bugzilla.mozilla.org/show_bug.cgi?id=459035 ) 

Firefox doesn't get it right either, and we're not consistent:
I compared servo to firefox : 
1) ./mach run http://people.mozilla.org/~nhirata/html_tp/bug459035.html
<img width="536" alt="screen shot 2016-02-16 at 6 23 24 pm" src="https://cloud.githubusercontent.com/assets/1091409/13097965/b4eb1bb2-d4da-11e5-8ff7-2b4faa69382d.png">

**Comment by mbrubeck** [comment]
I don't know exactly where this is going wrong, but it's probably something like this:  In various places we need to translate logical sizes or coordinates from a parent box's coordinate system to a child's coordinate system, or vice-versa.  For example, if the parent is RTL but the child is LTR, then to determine the child's inline-start (left) position, we need to look at the parent's inline-end (left) padding.

Sometimes this means we change logic based on whether the parent and child writing modes have the same inline direction or opposite directions.  Examples:

https://github.com/servo/servo/blob/50e4171958d4ff7f1c76d133a8f89e7d5995376f/components/layout/block.rs#L1396

https://github.com/servo/servo/blob/50e4171958d4ff7f1c76d133a8f89e7d5995376f/components/layout/block.rs#L2477

I believe my theory when I wrote the initial comment above was that we were looking at the wrong parent.  In the test case, everything under `body` should inherit inherit `direction: rtl`, but the root `html` element has `direction: ltr`.  Maybe this code is propagating the direction of the parent's parent, so that the fragments within the `div` end up looking at the grandparent's writing mode?

https://github.com/servo/servo/blob/75f39b42abc88a2597186fe845d2deaa15bdb6da/components/layout/inline.rs#L1425

**Comment by Loirooriol** [comment]
Fixed in layout 2020:

- Layout 2013:
  ![](https://github.com/user-attachments/assets/7c97db9a-8e6e-470e-adbb-a4840d2d4968)
- Layout 2020:
  ![](https://github.com/user-attachments/assets/8b1cf7d9-0e7f-4644-937c-60d9fa9d533f)
- Firefox:
  ![](https://github.com/user-attachments/assets/0a60bdf3-1cc8-4c50-8882-f7e76b46952c)
