### ISSUE TITLE
Get Shumway working in Servo

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#6097]
https://github.com/mozilla/shumway

**Comment by Ms2ger** [comment]
@tschneidereit is running point here.

From #8448:

> Shumway support is blocked by many small things, not any major missing feature. Instead of hacking Shumway to get it working *somehow*, I'm slowly working through the blockers as I encounter them. Right now, that means some small CSSOM stuff. #7979 and #8039 were results of that, and I'm making good progress on building on those to actually support some CSSOM APIs.
>
> Then there's the issue of `SVGMatrix` not being supported. I *think* we might actually get away with never implementing that, and going with `DOMMatrix` instead. Implementing that isn't trivial, either, though. #7415 and #6683 were preparatory work.
>
> Once the DOM API blockers are all out of the way, it's going to be all about Canvas2D. From what I was told, various issues should be expected, because the implementation has major holes, apparently. I haven't looked into that part at all, though.

**Comment by atouchet** [comment]
Is this worth keeping open now that Shumway development has ceased?

**Comment by jdm** [comment]
Nope!
