### ISSUE TITLE
The WebSocket open event should not be cancelable.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6101]
Blocks #6060.

* Spec: <https://html.spec.whatwg.org/multipage/#feedback-from-the-protocol:concept-websocket-established>, <https://html.spec.whatwg.org/multipage/#fire-a-simple-event>.
* Code: `components/script/dom/websocket.rs`.
* Test: `/websockets/interfaces/WebSocket/events/018.html`.

**Comment by KiChjang** [comment]
Let me take a look at this one.
