### ISSUE TITLE
JavaScript errors are not reported

### ISSUE THREAD

**Issue by klusark** [servo/servo#6103]
Open a page that should give a JavaScript error.

Expected behavior:
An error is shown on the console and the script stops executing

Actual behavior:
The script stops executing

**Comment by jdm** [comment]
Ack, you're right. We really need to implement that properly; I'll be writing up a plan for how to do that soon, based on Gecko's [AutoJSAPI design](http://mxr.mozilla.org/mozilla-central/source/dom/base/ScriptSettings.h#179).

**Comment by klusark** [comment]
I bisected this. It's caused by ef8edd4e87aeb3cc71dfd9da2f69437080f5410e

**Comment by glennw** [comment]
Yep, just found that too. Something appears to have changed in the log crate during the rustup that means error!() is no longer printed by default.

**Comment by Manishearth** [comment]
The `RUST_LOG` invocation changed, but I was trying with the new one and it still wasn't working.

But yeah, I suspect this too.

**Comment by glennw** [comment]
https://github.com/rust-lang/log/pull/40 seems related.

**Comment by glennw** [comment]
Discussed with sfackler in irc. He will change rust-log to previous behaviour so that error!() is printed by default. The current master of rust-log compiles on the servo rustc, so we should be able to just update rust-log once that change is made.

**Comment by glennw** [comment]
https://github.com/rust-lang/log/pull/41
