### ISSUE TITLE
Support cert pinning via DANE

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#6104]
[DNS-based Authentication of Named Entities](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities).

This may require having our own DNSSEC resolver.

**Comment by hsivonen** [comment]
Considering that more established browsers are rejecting this feature due to the latency of querying DNS and due to DNSSEC using the sort of legacy crypto that's being unsupported for normal CAs, it's probably not a good idea to spend time on this in Servo.

**Comment by nox** [comment]
Assigning to @avadacatavra to decide whether we should pursue this.

**Comment by TerraX-net** [comment]
If we think of the growing DNSSEC with (the smaller) ECDSA like Cloudflare, we would have to expect a even smaller latency than the small ones in the past.
[DNSSEC with Ed25519 an Ed448](https://tools.ietf.org/html/rfc8080) has been standardized.
ring has Ed25519 support and it is to expect that https://github.com/briansmith/ring/issues/463 will follow. As you are planning to use [briansmith/webpki](https://github.com/briansmith/webpki) and [briansmith/ring](https://github.com/briansmith/ring) in Servo, you would ideally find a dns resolver built on top of them to avoid to ship multiple crypto libraries.

**Comment by hsivonen** [comment]
I see that my comment from 2015 has gotten two thumbs down. It helps to consider DNSSEC as a CA system replacement with legacy crypto practices and with structurally unimpeachable root and intermediates.

Legacy crypto practices: Remember that DNSSEC had a 1024-bit RSA root at a time when Mozilla had decided to distrust 1024-bit RSA Web PKI roots.

From time to time, there's "whoa! how can it be this bad?" news about a particular CA or its delegates. Taking action against BR violations in Web PKI is hard but possible. In DNSSEC, if your TLD misbehaves in terms of what it signs, there's no remedy without everyone under that TLD changing to a different TLD, which is prohibitively disruptive. Authorities in DNSSEC are even less impeachable in case of bad behavior than in Web PKI.

Furthermore, I haven't seen any update refuting Chrome's finding that a substantial portion of browser users are behind middleboxes that drop DNSSEC-sized DNS responses.

**Comment by TerraX-net** [comment]
This issue suggests "cert pinning via DANE" as an addition to HPKP and Preloaded-HPKP and not as an alternative trust anchor (even it would be great and wouldn't have negative security impacts).
Today, your TLD (Registry) could change NS/Glue Records and then read all of your new Email, without any CA.
Your TLD could even then apply for a Let's Encrypt Certificate and would get it.
If you don't trust your TLD, you have a problem - in every sense.
An EV certificate couldn't protect you. There would be some less green, but the website/email service would still work with a new DV certificate.
So in theory, we could trust DANE as trust anchor (TLD>DS>KSK>ZSK>DANE>Certificate) like we trust DV certificate CAs (TLD>(fake) NS>AAAA>DV cert), even it wasn't requested here.

The only way to secure you against a fake Glue Record (leading to a fake DV cert) would be [HPKP Pinning](https://community.qualys.com/thread/17152-what-is-static-public-key-pinning), but I don't think Google or Mozilla verify any person's identity and do only trust "the current website containing a hidden verification file". They should only offer HPKP Pinning for Websites with EV Certificate or NameConstraints-CA and only pin the public key of the EV Cert or include a [NameConstraints CA which is only valid for my domain(s)](https://wiki.mozilla.org/CA:NameConstraints).

Middleboxes: This is a feature that could be activated by default for common users and should be opt-in for enterprise users. It's very funny that private households are more protected today than some companies/public administration. Note that middleboxes even prevented TLS 1.3, so Chrome had to disable it for now! Middleboxes are not a valid argument to lower the security for common users. Enterprise Users shouldn't block security features and then complain that something does not work. If this would find it's way into Firefox, it should be disabled in Firefox ESR by default at first.

**Comment by avadacatavra** [comment]
There's no cross-browser consensus on the tradeoffs with DANE, and I don't think this is a current priority for Servo.

We can reopen/revisit this in the future if things change in the browser ecosystem.
