### ISSUE TITLE
Implement HSTS

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#6105]
[HTTP Strict Transport Security](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security).

For now we may not want Servo to persist any state to disk. In that case we can support just HSTS preloads and not the `Strict-Transport-Security` header.

**Comment by jdm** [comment]
@kmcallister This is going to need further elaboration if the easy tag is going to be reinstated.

**Comment by kmcallister** [comment]
I linked to the MDN document that explains the whole feature. If we're only doing preloads then we just need to get that file from Google and bake it into Servo.

**Comment by jdm** [comment]
This will require adding additional Servo initialization code (like the hostfile processing) and checks in the HTTP loader. I think we should support an in-memory list of any domains for which we have seen a Strict-Transport-Security header, too. 
Code: components/net/resource_task.rs, components/net/http_loader.rs

**Comment by samfoo** [comment]
I'm keen to give this a go as a first task. It seems like doing only preloads first should be fairly straightforward. Finding a suitable preload list doesn't not appear to be as straightforward.

Chromium [packages theirs with the build](https://src.chromium.org/viewvc/chrome/trunk/src/net/http/transport_security_state_static.json), as does [gecko](https://github.com/mozilla/gecko-dev/blob/b6ea902b969546b6ae6c2d43e68b193bfb48716e/security/manager/ssl/nsSTSPreloadList.inc). I assume the gecko list is to be preferred?

**Comment by jdm** [comment]
We could add a mach command to fetch the latest version. That would live somewhere in http://mxr.mozilla.org/servo/source/python/servo/; it's not clear to me which of those files makes the most sense, but the bootstrap_commands.py has a bunch of "download this file" logic.
