### ISSUE TITLE
Support cert pinning via HPKP

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#6106]
A [mechanism](https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning) very similar to HSTS (#6105).

**Comment by nox** [comment]
Assigning to @avadacatavra to decide whether we should pursue this.

**Comment by avadacatavra** [comment]
i'd like to revisit this after we do some work on our certificate infrastructure

**Comment by frewsxcv** [comment]
Chromium just announced they're removing HPKP

https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ

**Comment by avadacatavra** [comment]
I don't think this is something we should pursue--there are a number of unintended consequences that can happen as a result of HPKP. Since other browsers who have shipped it are reversing course, this doesn't seem like something we should implement
