### ISSUE TITLE
The WebSocket close event should not be Cancelable

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#6111]
Blocks #6060.

* Spec: https://html.spec.whatwg.org/multipage/comms.html#feedback-from-the-protocol:concept-websocket-closed
* Code: `components/script/dom/websocket.rs`

**Comment by KiChjang** [comment]
@Ms2ger I had to make this issue because there was a newcomer who wanted to work on easy bugs

**Comment by jdm** [comment]
Excellent work, @KiChjang :)
