### ISSUE TITLE
Stop using regex! macro for hostfile parsing

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#6114]
According to [this reddit thread](https://www.reddit.com/r/rust/comments/35dh3e/servos_dependency_graph/cr3et2n), `regex_macros` is not at all optimized, and also can lead to a lot of generated code bloat.  Converting [these two lines](https://github.com/servo/servo/blob/49b73c0bfe50366e767525f9f90c5aa348f68f18/components/net/resource_task.rs#L151-L152) to use [Regex::new](http://doc.rust-lang.org/regex/regex/index.html#first-example:-find-a-date) would allow us to get rid of our `regex_macros` dependency, which might improve compile times and code size without any noticeable performance hit.

**Comment by awestroke** [comment]
I'd like to work on this issue

**Comment by awestroke** [comment]
Let's close this?
