### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by joeblew99** [servo/servo#6117]
I am doing my final year project i.e making an online web based 3D Designing solution that help user to make or to design a 3D Model using drag and drop feature in more user friendly environment.
Therefore i need some help to start this project it will be so help full if you can provide me some guidelines.

I need to run the application as a web browser, but also as a non web browser. 

So, I am wondering if i can retarget webGL calls to openGL ?
I would like to use Servo as a FAT client, but program as if it was a web app, and in this case get a perf increase by retargeting direct to openGL.

**Comment by jdm** [comment]
It sounds to me like you may want to write a regular web application, then add a manifest to make it installable. See https://developer.mozilla.org/en-US/Apps for more information about it.

**Comment by joeblew99** [comment]
i dont want to do this.

I want to have webgl and opengl agnostic factory pattern.

**Comment by jdm** [comment]
I don't think Servo will be able to help you here, unfortunately.
