### ISSUE TITLE
Don't let Corgo depend on android-rs-glue unless running "mach build --android"

### ISSUE THREAD

**Issue by benbucksch** [servo/servo#6123]
Reproduction:
1. Try to compile Servo on Linux for Linux

Actual result:
Downloading Cargo nightly
...
Cargo ready.
Could not find `Cargo.toml` in `.../servo/support/android-rs-glue/glue'

Expected result:
Android build dependencies are active only when building for Android (which I should specifically specify, should not be the default when building on Linux).

**Comment by larsbergstrom** [comment]
We've cleaned up a lot of the build system since then - no more submodules! Moved to Cargo!
