### ISSUE TITLE
Support multiple layers per stacking context

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#6142]
We should change stacking contexts and layers to be 1:N instead of 1:1/1:0 as they are today in order to match the CSS spec. Possibly the best way to do this would be to add layer IDs to every display item; after flattening and shuffling the items into the proper order, we'd instantiate the layers, creating front and back layers as necessary. For example, if display items have layer IDs 1, 1, 1, 1, 2, 2, 1, 1, 1 we'd create three layers for layer IDs as follows: 1, 2, 1.

This would in effect be a _very_ simple version of Gecko's `FrameLayerBuilder`.

cc @rocallahan

**Comment by mrobinson** [comment]
This should be supported now with https://github.com/servo/servo/commit/9d72e89ce3502cb58147375c8ecc4e9e9356b1ee and  https://github.com/servo/servo/pull/16073!
