### ISSUE TITLE
Make Location methods writable

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#6144]
Followup #6135 
Most the attributes here are read-only: http://mxr.mozilla.org/servo/source/components/script/dom/webidls/URLUtils.webidl

Make the writeable based on https://url.spec.whatwg.org/#urlutils-and-urlutilsreadonly-members

**Comment by snf** [comment]
I'm working on it, waiting for https://github.com/servo/servo/pull/6135

**Comment by frewsxcv** [comment]
Update: #6135 has been completed

**Comment by nox** [comment]
#7228
