### ISSUE TITLE
Null-check in location getters

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#6145]
Followup #6135 
Implement the null-check in https://url.spec.whatwg.org/#urlutils-and-urlutilsreadonly-members

**Comment by pikzen** [comment]
Hey, I'd love to give this a shot. The related file is https://github.com/servo/servo/blob/1389be37823fccf4108f4e79d0a3a793f0bbe93e/components/script/dom/urlhelper.rs, right ?

**Comment by shinglyu** [comment]
Yep!

**Comment by pikzen** [comment]
OK, now that I am actually able to get to work on this, I'm having a bit of a trouble understanding how to resolve the problem (or is there is even one) Could someone clarify a few things ?

 1. nulls are hard to come by in Rust, especially on `&Url`.
 2. `url` is not an `Option<&Url>` so doing pattern matching is out of the way
 3. https://github.com/servo/servo/tests/wpt/web-platform-tests/url/url-constructor.html seems to be handling null urls fine (as in, throws an error on creating a null URL)

The way I see it, the two possible solutions are
 1. I could create an Option<&Url> from `url`, but that seems a bit overkill to do a simple None-check. 
 2. I could change the parameter from an &Url to an Option<&Url> but that also seems a bit much and not consistent with the rest of the methods.

Am I missing something ?

**Comment by jdm** [comment]
I think you are right and there is not anything we need to do here. You could remove the comments pointing at this issue, though!

**Comment by pikzen** [comment]
Should I also commit my patch to url-constructor.html to test null URLs ?  It's basically

```
// Attempt to use a NULL pathname. This should not be allowed
  test(function() {
    if (urltests.length <= 0)
      return;

    var url = bURL(null, urltests[0].base);
    assert_equals(url.pathname, "", "pathname with null");
  }, "Ensuring nulls do not pass through");
```

However, I don't know how to expect the test to throw an error.

**Comment by jdm** [comment]
http://testthewebforward.org/docs/testharness-library.html#assert_throws-code-func-description-
