### ISSUE TITLE
PendingLoadGuard should not assert if panic in process

### ISSUE THREAD

**Issue by jdm** [servo/servo#6148]
The destructor for `PendingLoadGuard` in `components/net_traits/lib.rs` asserts if the pending load is never initiated. Unfortunately, if there's ever a pending load that exists when a panic occurs, this assertion fails but is meaningless. We should use the [panicking](http://doc.servo.org/std/thread/fn.panicking.html) function to check this.

**Comment by r0e** [comment]
Hi jdm, I'd like to give this a shot.

**Comment by jdm** [comment]
Please do!
