### ISSUE TITLE
The build prerequisites for Debian based Linux does not quite apply for Ubuntu 14.04.2/64 bit

### ISSUE THREAD

**Issue by mattias-ostergren** [servo/servo#6158]
The prerequisites for Debian based Linuxes on servo main project page (https://github.com/servo/servo) seems not quite applicable for Ubuntu 14.04.2/64 bit.

On my setup running the command 

sudo apt-get install curl freeglut3-dev \
    libfreetype6-dev libgl1-mesa-dri libglib2.0-dev xorg-dev \
    gperf g++ cmake python-virtualenv \
    libssl-dev libbz2-dev libosmesa6-dev libxmu6 libxmu-dev

Fails on some unresolbable dependancy to "libcheese".

This could be mended /work-around by running the following:

sudo apt-get install  libglew-dev libcheese7 libcheese-gtk23 libclutter-gst-2.0-0 libcogl15 libclutter-gtk-1.0-0 libclutter-1.0-0  xserver-xorg-input-all

Please note: this work-around was taken from here. And found with some creative googling (but with shallow insight): 

http://askubuntu.com/questions/588695/cant-install-libglew-dev-because-libcheese-and-libclutter-dont-have-the-requir

So likely there is some more elegant and insightful solution.

**Comment by Jayflux** [comment]
Maybe someone should update the readme?

**Comment by Ms2ger** [comment]
That someone could be you :)

**Comment by xiaochuanyu** [comment]
Added a PR (above) to update README.
It's actually just 1 commit. Sorry about the random Github references above, I was editing the commit message, messed up and did some rebase which confused github it seems.

**Comment by frewsxcv** [comment]
Completed in #7506

**Comment by zeusintuivo** [comment]
For better instructions on how to compile in Ubuntu 14.04.04 32 and 64 bits as well as Widows 7 32 and 64 bits see https://github.com/servo/servo/issues/12356
