### ISSUE TITLE
Prune cached pipelines

### ISSUE THREAD

**Issue by jdm** [servo/servo#6160]
We stash previous documents in an ever-growing list. We need a way to retain that history, but closing the actual pipeline to reduce memory usage and recreating it if we choose to go back in history.

**Comment by jgraham** [comment]
This is a blocker if we want to run tests without constantly restarting the process.

**Comment by jdm** [comment]
Things to keep in mind:
* the session history storage in constellation will need to track the state of each pipeline and manage navigating the session history accordingly
* when recreating, it's not yet clear to me whether it's a good idea to use the exact same pipeline ID as before or make a new one
* if we use a message in the regular event loop for a given script thread, there could be quite a backlog before the instruction to close a pipeline is executed. Probably not a big concern for the initial deliverable for this work?

cc @Ms2ger

**Comment by asajeffrey** [comment]
Closed by #14312
