### ISSUE TITLE
embedding: add hook for display_handler::on_favicon_urlchange

### ISSUE THREAD

**Issue by zmike** [servo/servo#6166]
@mbrubeck

**Comment by mbrubeck** [comment]
For handling `<link rel="icon">` we will need code in [HTMLLinkElement](https://github.com/servo/servo/blob/df2f8d0636922a7e89895fa61fdba30099cec9ea/components/script/dom/htmllinkelement.rs) that checks the `rel` and `href` attributes in `after_set_attr` and `bind_to_tree`.  See the existing `handle_stylesheet_url` for example.  If a favicon URL is found, it could then call a method on the window or document which then passed the URL to the embedding code somehow.

(For sites that don't use the `link` element for this, there's a fallback to `favicon.ico`.  I'm not sure how or where that should be implemented.)

**Comment by jdm** [comment]
That would usually be the responsibility of the embedding application, I assume.

**Comment by jdm** [comment]
Gecko does this in `useDefaultIcon`: http://mxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#946
