### ISSUE TITLE
Chinese characters charset gb2312 can not show properly.

### ISSUE THREAD

**Issue by cloudtrends** [servo/servo#6167]
Chinese characters charset gb2312 can not show properly.

./mach run http://sohu.com

![bildschirmfoto 2015-05-24 um 01 57 18](https://cloud.githubusercontent.com/assets/2282880/7785223/853ecb2a-01b8-11e5-8284-8049de93c1f8.png)

**Comment by nox** [comment]
<img width="1136" alt="capture d ecran 2017-09-30 a 10 32 29" src="https://user-images.githubusercontent.com/123095/31044179-af1e8f9e-a5ca-11e7-8437-366372ea49a2.png">
