### ISSUE TITLE
Implement FileReader

### ISSUE THREAD

**Issue by snf** [servo/servo#6172]
https://w3c.github.io/FileAPI/#APIASynch , probably E-Easy

**Comment by KiChjang** [comment]
Implementation of the async algorithm isn't as easy, I vote for less easy instead

**Comment by farodin91** [comment]
I like to work on it. To start work on Project. Are there any design standards for creating an API.

**Comment by snf** [comment]
This is a pretty good documentation on how to do it: http://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface . You may also want to look at the other implementations in dom/

**Comment by farodin91** [comment]
Thank you!
I think DOMError isn't implement at this moment, right?

**Comment by snf** [comment]
Looks like DOMError will be replaced with DOMException: http://www.w3.org/TR/domcore/#interface-domerror .

**Comment by Ms2ger** [comment]
Right now, you could simply return `DOMException` where the spec says `DOMError`.

**Comment by farodin91** [comment]
I started working on the FileReader, but currently i have a problem with converting JSRef<Blob> to Blob. 

At this time isn't ArrayBuffer implemented or?

**Comment by jdm** [comment]
Can you be more specific about the JSRef problem you're having? As for dealing with ArrayBuffer, you likely need to do something like TextDecoder::Decode - http://mxr.mozilla.org/servo/source/components/script/dom/textdecoder.rs#85 and http://mxr.mozilla.org/servo/source/components/script/dom/webidls/TextDecoder.webidl#20

**Comment by farodin91** [comment]
How to convert a JSRef<Blob> object to Blob. You get in this function: https://github.com/farodin91/servo/blob/cdf1370014b9278a17f432c4a7cc9ccac4752805/components/script/dom/filereader.rs#L73 .
This is posible extrem easy, but that are my first lines in Rust.

**Comment by jdm** [comment]
Oh, `JSRef<Blob>` automatically dereferences to a `&Blob` pointer. That means that you can use `some_jsref_blob.member_variable` to access a field of `Blob` named `member_variable`, and almost non-static methods for `Blob` should be defined on `JSRef<Blob>`, not `Blob`. Does that make sense?

**Comment by farodin91** [comment]
I have no idea to transfer to blob to "FileReaderTaskHandler". 
```rust
let global_root = self.global.root();
let addr: Trusted<FileReader> = Trusted::new(global_root.r().get_cx(), self, global_root.r().script_chan().clone());
let open_task = box FileReaderTaskHandler::new(addr.clone(), FileReaderTask::Open, blob);
global_root.r().script_chan().send(ScriptMsg::RunnableMsg(open_task)).unwrap();//4. ReadAsText
``` 
After this to read out the field bytes.

**Comment by jdm** [comment]
Ok, so there are two parts here. One is that the FileReaderTaskHandler should not need a reference to the blob; its role is to notify the main thread when it's time to dispatch the DOM events, which don't reference the blob at all (step 5/6/7 of https://w3c.github.io/FileAPI/#dfn-readAsText). Before that, the code should extract the buffer from the blob and move that into a new thread that does that actual reading (step 4 of https://w3c.github.io/FileAPI/#dfn-readAsText), and there should be no need to reference the `JSRef<Blob>` after that point. Does that make sense?

**Comment by farodin91** [comment]
Yes.
how i can get the logs of servo during the test runs?
for example: ./mach test-wpt FileAPI

**Comment by snf** [comment]
This is a comprehensive guide: https://github.com/servo/servo/blob/master/tests/wpt/README.md

```
./mach test-wpt FileAPI --log-raw=/tmp/servo.log
./mach update-wpt /tmp/servo.log
```

Afaik, the updated tests are commited automatically with update-wpt

**Comment by farodin91** [comment]
I finished a part of readAsText, but Blob doesn't support Uint8Array correct.

As the next part start to working on readAsDataUrl and clean up the code.

**Comment by snf** [comment]
Great!

**Comment by farodin91** [comment]
#6205
