### ISSUE TITLE
Broken test for Blob.slice

### ISSUE THREAD

**Issue by snf** [servo/servo#6173]
Most of the items in the list presented at https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/FileAPI/blob/Blob-slice.html#L163  match the specification of Blob.slice https://w3c.github.io/FileAPI/#slice-method-algo

```
The optional contentType parameter is used to set the ASCII-encoded string in lower case representing the media type of the Blob. User agents must process the slice with contentType normalized according to the following:

    If the contentType parameter is not provided, let relativeContentType be set to the empty string .

    Else let relativeContentType be set to contentType and run the substeps below:
        If relativeContentType contains any characters outside the range of U+0020 to U+007E, then set relativeContentType to the empty string and return from these substeps.
        Convert every character in relativeContentType to lower case using the "Converting a string to ASCII lowercase" algorithm.
```

Or am I missing something?

**Comment by snf** [comment]
I assume that it has to be a parseable MIME type but I'm not sure the specification is explicit enough.

**Comment by Manishearth** [comment]
Firefox also fails these tests.

`)` and all are part of the range defined in the spec. Perhaps the test is wrong?

cc @Ms2ger

**Comment by Ms2ger** [comment]
https://github.com/w3c/web-platform-tests/pull/2841
