### ISSUE TITLE
run over EGL

### ISSUE THREAD

**Issue by piranna** [servo/servo#6176]
Is it possible to compile Servo to run it on an (embedded) x86 platform directly on top of fullscreen EGL? The idea is to use it as basis to develop a GUI desktop environment for NodeOS.

**Comment by cyplo** [comment]
Hi ! Were you able to do so eventually, or is this still unknown ?

**Comment by piranna** [comment]
This is still unknown, sorry.

**Comment by zmike** [comment]
There's a PR open to add EGL support, though I'm not sure what the exact status is.

@glennw

**Comment by mbrubeck** [comment]
I think this was fixed by #9781.
