### ISSUE TITLE
Review our usage of iterators in the DOM

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#6177]
Since our DOM uses interior mutability, our iterators are in danger of invalidation (or causing a refcell crash)

A lot of the changes in #6140 use iterators; with generics mixed in (e.g. `callback`). For the safety of the iterators we need to ensure that there is no DOM manipulation going on there. For 
example, if there was DOM manipulation going on [here](https://github.com/servo/servo/pull/6140/files#diff-30a18e04d7e0b66aafdf192e416cad44R1034), we might get some infinite loops or worse.

We should review the way our iterators are currently used; and perhaps mark them all `unsafe`, additionally documenting methods that take in generic callbacks to ensure that DOM manipulation is not done in the callbacks.

cc @jdm @Ms2ger

**Comment by Manishearth** [comment]
cc @nox

**Comment by nox** [comment]
Closing.
