### ISSUE TITLE
links should send status message with url to constellation/compositor on mouseover

### ISSUE THREAD

**Issue by zmike** [servo/servo#6178]
handle_mouse_move_event() in dom/document.rs seems to be the place for it

@Ms2ger @Manishearth

**Comment by Manishearth** [comment]
Why not `handle_event` on `htmlanchorelement.rs`, filtered on mouseover and mouseout?

**Comment by jdm** [comment]
For one, we don't implement mouseenter and mouseleave :)

**Comment by Manishearth** [comment]
....oh

:D

**Comment by brunoabinader** [comment]
Willing to take this if anyone else has started it already :-)

**Comment by zmike** [comment]
I have https://gist.github.com/zmike/65bb83ee0bdad5e90691 so far, but it doesn't compile yet.
