### ISSUE TITLE
Should use FT_Done_Library() instead of FT_Done_FreeType()

### ISSUE THREAD

**Issue by nnethercote** [servo/servo#6191]
There are two pairs of functions for creating/destroying FreeType libraries:
- `FT_Init_FreeType()` and `FT_Done_FreeType()`, and
- `FT_New_Library()` and `FT_Done_Library()`.

You aren't supposed to mix them, e.g. the [docs for `FT_New_Library()`](http://www.freetype.org/freetype2/docs/reference/ft2-module_management.html#FT_New_Library) say "Don't use FT_Done_FreeType but FT_Done_Library to destroy a library instance."

In `components/gfx/platform/freetype/font_context.rs` a library is created with `FT_New_Library()` and destroyed with `FT_Done_Freetype()`. I don't know what the effect of this is, but it clearly violates the documented API.

Fixing it would be trivial except that rust-freetype doesn't provide a binding for `FT_Done_Library`.

**Comment by Jinwoo-Song** [comment]
I made a PR for adding FT_Done_Library. (Jinwoo-Song/rust-freetype@ff569b8)
I'll upload a follow up patch after this PR is landed.

**Comment by nnethercote** [comment]
Thank you, Jinwoo-Song!
