### ISSUE TITLE
Fix the failed tests after #6157.

### ISSUE THREAD

**Issue by hyowon** [servo/servo#6194]
The below tests to check the invalid parameters in CreatePattern are failed after #6157.

2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html
2dcontext/fill-and-stroke-styles/2d.pattern.image.string.html
2dcontext/fill-and-stroke-styles/2d.pattern.image.undefined.html

**Comment by nox** [comment]
throw_not_in_union() throws Error instead of TypeError.

**Comment by nox** [comment]
throw_not_in_union() should probably be a wrapper around throw_type_error().
