### ISSUE TITLE
Failures in css-tests because of missing Ahem font

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#6195]
Many of the reftests in `tests/wpt/css-tests` require the Ahem font, but this font is not installed on our test machines, so these tests are failing.

Possible solutions:
* Install Ahem.ttf on our test machines (and anywhere else we want to run these tests).
* Change the tests to load Ahem.ttf as a web font, like many of Servo's reftests do. (Might not be acceptable upstream because web fonts are not part of CSS 2.)
* Add code to Servo to load additional fonts from a path specified by the test harness.

**Comment by SimonSapin** [comment]
Perhaps another option is adding support for [user stylesheets](http://dev.w3.org/csswg/css-cascade/#origin) and have one for reftests with an `@font-face` rule for Ahem.
