### ISSUE TITLE
Width of spaces in justified text changes upon mouse move

### ISSUE THREAD

**Issue by hsivonen** [servo/servo#6203]
Steps to reproduce:

    ./mach build --release
    ./mach run --release https://hsivonen.fi/doctype/

Move the mouse over the window.

Actual results:
On some lines of text, the spaces between words grow and shrink as the mouse moves. When the spaces grow, the text doesn't rewrap but extends beyond the right edge of the block.

Expected results:
No change in text location due to mouse move.

**Comment by hsivonen** [comment]
Oh, and this was on Ubuntu 14.04 with llvmpipe.

**Comment by hsivonen** [comment]
Also happens on http://squarefree.com/

**Comment by jdm** [comment]
cc @pcwalton

**Comment by frewsxcv** [comment]
For archival purposes, GIFs of the issues for the websites listed above

### https://hsivonen.fi/doctype/

![untitled2](https://cloud.githubusercontent.com/assets/416575/7900305/2861be3a-071c-11e5-9f71-0d8d4f7394d2.gif)

### http://squarefree.com/

![untitle2](https://cloud.githubusercontent.com/assets/416575/7900306/2c8969ea-071c-11e5-8d64-4c50803de376.gif)

**Comment by mbrubeck** [comment]
Also filed as #10499. Closing this bug because the other one has some existing discussion.
