### ISSUE TITLE
Designated fonts not used for some text without obvious reason

### ISSUE THREAD

**Issue by hsivonen** [servo/servo#6204]
Steps to reproduce:

```
./mach build --release
./mach run --release https://hsivonen.fi/doctype/
```

Scroll down to the botton of the page.

Actual results:
Text in the section "Appendix: IE8's mode selection" and the word "copyright" in the page footer appear using default fonts instead of the ones designated in CSS.

Additional info:
I have the CSS-designated fonts installed locally, so I don't know if Servo uses the local fonts or the Web fonts for the rest of the text that appears with the right fonts.

**Comment by mrobinson** [comment]
I'm not seeing this one any longer -- a lot has changed in the last decade.
