### ISSUE TITLE
Integrate Khronos' WebGL conformance test suite

### ISSUE THREAD

**Issue by nox** [servo/servo#6207]
Follow-up of #6183, as per suggested by @ecoal95.

https://github.com/KhronosGroup/WebGL

**Comment by ecoal95** [comment]
cc @Ms2ger, could it be integrated in wpt?

**Comment by Ms2ger** [comment]
It definitely should, but I don't really want to deal with Khronos politics (which is also why there are a handful of webgl tests in wpt already).

**Comment by Ms2ger** [comment]
https://github.com/KhronosGroup/WebGL/issues/1105
