### ISSUE TITLE
Running the jquery test suite intermittently makes the resource task panic.

### ISSUE THREAD

**Issue by glennw** [servo/servo#6210]
This hangs the test runner as hard fail mode doesn't exit when the resource task panics.

./mach test-jquery -r

**Comment by jdm** [comment]
Any chance you can catch the panic backtrace?

**Comment by glennw** [comment]
Unfortunately I couldn't get it to panic with RUST_BACKTRACE=1 (it's intermittent), but I do plan to investigate it and provide more info when I can.

**Comment by dralley** [comment]
Is this still happening?

**Comment by jdm** [comment]
Odds are that it doesn't, and we usually break the jquery test harness in a new way every year.
