### ISSUE TITLE
Testing under headless mode

### ISSUE THREAD

**Issue by cloudtrends** [servo/servo#6215]
https://github.com/servo/servo/wiki/Testing

I want run servo under headless mode , by command:

./mach test-content 

but error message output is :

Content tests have been replaced by web-platform-tests under tests/wpt/moilla/.

what shoud I do to repair the command ?

**Comment by Manishearth** [comment]
The wiki page is old.

Build servo with `SERVO_HEADLESS=1` ( `SERVO_HEADLESS=1 ./mach build`) and then run it

**Comment by jdm** [comment]
I removed the command from the wiki page.
