### ISSUE TITLE
Remove unnecessary calls to node_removed and change semantics of node_inserted

### ISSUE THREAD

**Issue by mukilan** [servo/servo#6229]
PR #5972 has changed the semantics of ```node_removed``` so that it now corresponds to the ["removal steps"](https://dom.spec.whatwg.org/#concept-node-remove-ext) in the spec and doesn't perform any steps related to "mutation observers". Hence,
as explained [here](https://github.com/servo/servo/pull/5972#issuecomment-107122353), the calls to node_removed from [Node::ReplaceChild](https://github.com/servo/servo/blob/master/components/script/dom/node.rs#L2263) and [Node::replace_all ](https://github.com/servo/servo/blob/master/components/script/dom/node.rs#L1762-L1765) should be removed.

Additionally to keep things symmetric, ```node_inserted``` can also be called unconditionally from [```insert``` ](https://github.com/servo/servo/blob/master/components/script/dom/node.rs#L1655)
and the calls from [replace_all](https://github.com/servo/servo/blob/master/components/script/dom/node.rs#L1767-L1769) and [ReplaceChild](https://github.com/servo/servo/blob/master/components/script/dom/node.rs#L2264-L2266) can be removed as well, so that node_inserted will correspond to the ["insertion steps"](https://dom.spec.whatwg.org/#concept-node-insert-ext) in the spec.

**Comment by gaye** [comment]
I'd like to take!

**Comment by jdm** [comment]
Go for it!

**Comment by nick-thompson** [comment]
@gaye are you working on this one? I'd like to take a stab at it if not.

**Comment by gaye** [comment]
@nick-thompson Be my guest! I got caught up in some other work.

**Comment by nox** [comment]
I think I'm already covering this in #6660, you might want to work on something else. Sorry I didn't notice this ticket.

**Comment by nick-thompson** [comment]
Yep, looks like your commit covers all of the code I was about to change. Thanks for the heads up, I'll look for something else.

I'll leave this for a more senior contributor to verify and close out ;)
