### ISSUE TITLE
Run flake8 on Python files as part of the tidy process

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#6236]
Would help find things like unused variables, unused imports, etc.

If someone could point me at where to include the `flake8` requirement, I'd be happy to make all the necessary changes to make flake8 happy

Initially at least, I imagine we can ignore most of the whitespace and line-length errors

#### Backstory:

https://github.com/servo/servo/pull/6235#issuecomment-107256558

https://github.com/servo/servo/pull/6235#issuecomment-107257052

**Comment by SimonSapin** [comment]
If possible, I’d rather not make flake8 a servo dependency that users have to install (and deal with the joys of Python packaging). One option is to have in a ZIP file and run python with the `PYTHONPATH` environment variable set to a path to that file.

See https://github.com/servo/servo/blob/master/components/style/build.rs and https://github.com/servo/servo/blob/master/components/style/Mako-0.9.1.zip for an example where we do this already.

**Comment by metajack** [comment]
So far we have directly imported small python modules into python/foo. I'm also fine with the zipfile idea. perhaps We should have been doing that from the beginning for imports, which also makes it extremely clear when we are not planning to modify upstream drops as well as maintaining version information.

**Comment by frewsxcv** [comment]
I was about to ask why we are using zip files instead of [wheels](http://pythonwheels.com/), but then I noticed the [mako](https://pypi.python.org/pypi/Mako/1.0.1) package does not offer wheels :cry:

**Comment by frewsxcv** [comment]
[A relevant discussion about ignoring third party libraries from flake8](https://github.com/servo/servo/pull/6260#issuecomment-107973816)

**Comment by SimonSapin** [comment]
ZIP files can be put in the "path" to be imported directly, whereas wheels (AFAIK) have to be installed. To install something in isolation, we need a virtualenv. It’s doable (we do it for wptrunner), but it’s just many more moving parts.

Dumping some Python files is fine as well, but flake8 has three dependencies so I don’t know how many files that is in total.
