### ISSUE TITLE
Add special operations to TestBinding.webidl

### ISSUE THREAD

**Issue by jdm** [servo/servo#6242]
http://heycam.github.io/webidl/#idl-special-operations

TestBinding.webidl is supposed to exercise all of the different parts of our WebIDL binding code generation, but it doesn't generate any code related to special operations. It needs named getters/setters, indexed getters/setters, a stringifier, and a deleter. There are examples of these in other WebIDL files (search for strings like "getter", "setter", "deleter", etc.)

code: components/script/dom/webidls/TestBinding.webidl

**Comment by Ms2ger** [comment]
Note that named getters/setters, indexed getters/setters and deleters turn the binding into a proxy; we probably want to keep a non-proxy in there too.

**Comment by nox** [comment]
We need multiple interfaces anyway if we want to test both attribute stringifiers and standalone stringifiers (same problem with named and indexed getters).

**Comment by jdm** [comment]
I guess we need a new TestBindingProxy.webidl file, since we can't have multiple interfaces in the same file.

**Comment by fbau123** [comment]
Im working on this

**Comment by fbau123** [comment]
I keep getting this error when i try to compile
`/home/fbs/opensource_contrib/servo/components/script/dom/bindings/codegen/Bindings/TestBindingProxyBinding.rs:47:5: 47:33 error: unresolved import `dom::types::TestBindingProxy`. There is no `TestBindingProxy` in `dom::types`
/home/fbs/opensource_contrib/servo/components/script/dom/bindings/codegen/Bindings/TestBindingProxyBinding.rs:47 use dom::types::TestBindingProxy;
`

Files I created are here

https://github.com/servo/servo/compare/master...fbau123:6242-testbinding-add-specialoperations?expand=1

**Comment by jdm** [comment]
You're missing the `mod testbindingproxy;` line that belongs in `components/script/dom/mod.rs`.

**Comment by jdm** [comment]
Also, there's no need to inherit from TestBinding.

**Comment by nox** [comment]
Do we have a test binding for inheritance though?

**Comment by jdm** [comment]
That's... a good point! Ignore my last comment!

**Comment by fbau123** [comment]
Ok I finally got it compiled without errors or warning, I made a pull

**Comment by nox** [comment]
#6284
