### ISSUE TITLE
Intermittent reftest failure in viewport_percentage_vw_vh.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#6252]
```
---- viewport_percentage_vw_vh.html == viewport_percentage_vw_vh_b.html stdout ----
	thread 'viewport_percentage_vw_vh.html == viewport_percentage_vw_vh_b.html' panicked at 'assertion failed: `(left == right)` (left: `782`, right: `775`)', ../../tests/reftest.rs:301
```

**Comment by glennw** [comment]
@jdm I've seen this failure before. I believe what occurs is that under some conditions on the mac builders, the servo window is placed partially offscreen (this is more likely to happen when lots of tests are run in parallel). When this occurs, the offscreen part of the window isn't painted by the GL driver, resulting in a reftest failure.

**Comment by nox** [comment]
Did our build machines change since then? This doesn't seem to occur anymore.

**Comment by nox** [comment]
No response, closing.
