### ISSUE TITLE
rustc snapshot no longer runs on Ubuntu 12.04

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6256]
```rustc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by ~/.servo/rust/474c6e0ae47578b3e608c893e18bc83798b565aa/rustc-1.2.0-dev-x86_64-unknown-linux-gnu/rustc/lib/libstd-d8ace771.so)```

Looks like I'm stuck with 2.15 for now.

**Comment by jdm** [comment]
cc @larsbergstrom

**Comment by larsbergstrom** [comment]
Gah, this is my fault - I did an `apt-get upgrade` on my "special snapshot VM" to support a newer version of the android toolchain and must have broken it.

CC @edunham that list of packages is probably wrong, given this error. Sorry!

I'll try to figure out a fix and rebuild the image.

**Comment by larsbergstrom** [comment]
Just installed a 12.04 LTS VM and it does appear to be on EGLIBC version 2.15, so I should be able to build a compatible snapshot once I get all the prereqs installed into it.

cc @edunham

**Comment by larsbergstrom** [comment]
@Ms2ger Can you try again? I've created a new snapshot on that machine.

**Comment by Ms2ger** [comment]
Thanks!
