### ISSUE TITLE
Font-style(italic) doesn't work.

### ISSUE THREAD

**Issue by deokjinkim** [servo/servo#6262]
When I tested with below command, "font-style: italic" doesn't work.
./mach run --release tests/ref/font_style.html

I think rust-azure doesn't support italic style.
- Callstack : 
  1. draw_text(paint_context.rs)
  2. get_paint_font_from_template(font_context.rs)
  3. create_scaled_font(font_context.rs)
- File : https://github.com/servo/rust-azure/blob/master/src/scaled_font.rs
- Line : 92
- Content:
                        FontInfo::FontData(bytes) => {
                            let azure_scaled_font =
                                AzCreateScaledFontForTrueTypeData(bytes.as_ptr(),
                                                                  bytes.len() as u32,
                                                                  0,
                                                                  size,
                                                                  AZ_NATIVE_FONT_SKIA_FONT_FACE);

Does anyone have opinion on this issue?

**Comment by mbrubeck** [comment]
This works for me. If this is still broken can you provide an HTML test case?
