### ISSUE TITLE
LocalLayoutContexts leaked via LOCAL_CONTEXT_KEY

### ISSUE THREAD

**Issue by nnethercote** [servo/servo#6282]
`LOCAL_CONTEXT_KEY` is defined like this:
```
thread_local!(static LOCAL_CONTEXT_KEY: Cell<*mut LocalLayoutContext> = Cell::new(ptr::null_mut()
```
Because it uses raw pointers the LocalLayoutContext doesn't get dropped when the thread dies. This causes us to leak FreeType instances (and possibly some other stuff).

@glennw thought that maybe the use of raw pointers here is related to an old restriction on thread-local storage that no longer holds. I played around with trying to make it `RefCell<Option<LocalLayoutContext>>` but failed.

**Comment by jdm** [comment]
I think the pattern for TLS might be `Rc<RefCell<Option<LocalLayoutContext>`.
