### ISSUE TITLE
heap_size_of is unsafe

### ISSUE THREAD

**Issue by jruderman** [servo/servo#6298]
`heap_size_of` usually crashes if it's given a borrowed pointer to a stack location.

It could be marked as unsafe, but I think that would mean also marking `HeapSizeOf for Vec<T>` as unsafe, since std::vec::as_vec lets you "forge" a &Vec<T> that doesn't refer to a heap location. And that would be sad.

It would be better if it could somehow ask jemalloc whether the pointer is a valid pointer to the beginning of an actual heap allocation. That would also catch most bugs where someone asks for the HeapSizeOf an interior field: as long as it's not the first field, the address of the field won't correspond to an actual heap allocation.

https://play.rust-lang.org/?gist=ca4ec039aeb5d6eac660&version=nightly

**Comment by nox** [comment]
`as_vec` is gone, and `heap_size_of` stuff has been marked unsafe anyway.
