### ISSUE TITLE
Use a MutableHandleValue outparam for calls returning GCThings

### ISSUE THREAD

**Issue by michaelwu** [servo/servo#6307]
This is a followup to https://github.com/servo/servo/pull/6150 .

DOM methods that return JSVal or JSObjects are better served by taking a MutableHandleValue to dump the return value into.

**Comment by nox** [comment]
Cc @asajeffrey, because linjs would make this issue obsolete.

**Comment by jdm** [comment]
I'm working on this in https://github.com/jdm/servo/tree/no-jsval-return. It builds and many tests pass, but it looks like there's something funky happening either with structured cloning or frozen arrays.
