### ISSUE TITLE
`./mach test` and `./mach test-ref` should run just the CPU tests by default

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#6315]
The GPU-based reftests are not currently being supported or tested on our builders, and cause confusion when people accidentally run them.

I suspect something around here will need to be changed:
https://github.com/servo/servo/blob/master/python/servo/testing_commands.py#L137

**Comment by fbau123** [comment]
Can I have it?
Should `./mach test` have an option to choose which render mode you want? I ask this because the description of `./mach test` is to run ALL tests, once the GPU tests are supported it should run both again by default.

**Comment by metajack** [comment]
You're welcome to tackle this bug. I think ./mach test (and prehaps the related subcommands) should get --cpu-paint and --gpu-paint flgas which enable cpu and gpu painting. The default (if neither flag is specified) should be --cpu-paint.

@larsbergstrom Does that sound reasonable?

We can change the default once gpu painting becomes more reliable.

**Comment by larsbergstrom** [comment]
I agree with @metajack on the additional flags.

I think the default for `./mach test` should just be to use the default value of `./mach test-ref`, if possible, since then if we fix up gpu painting we can just change the default for `test-ref` and everything that uses it will also get fixed to do both.

**Comment by frewsxcv** [comment]
Can this be closed now that #6360 has merged?
