### ISSUE TITLE
Implement the URL object.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6322]
Blocks #6321.

* Spec: <https://url.spec.whatwg.org/#api>.
* Code: `components/script/dom/url.rs`, `components/script/dom/webidls/URL.webidl` (to be created).
* Test: `/url/url-constructor.html`, `/url/interfaces.html`.

See also http://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface.

**Comment by nox** [comment]
I had begun implementing this, so I'm assigning it to myself.

**Comment by SimonSapin** [comment]
Some of the relevant stuff is already implement in https://github.com/servo/rust-url/blob/master/src/urlutils.rs
