### ISSUE TITLE
Add ARM cross compile support

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#6327]
This is a meta issue, after applying the following set of patches, it should be possible to cross compile servo for ARM devices by simply calling `mach --target=arm-unknown-linux-gnueabihf`

- servo/rust-azure#169
- servo/glutin#32
- servo/skia#50
- servo/mozjs#39
- servo/rust-mozjs#154
- servo/libfreetype2#11
- servo/libfontconfig#8
- servo/rust-harfbuzz#45
- servo/rust-png#72
- servo/rust-stb-image#70
- servo/rust-layers#175
- #6324 
- #6421 
- ecoal95/rust-offscreen-rendering-context#10
- aweinstock314/rust-clipboard#6

[more will come]

**Comment by mmatyas** [comment]
With the last set of patches, it is now possible to cross compile Servo to ARM. I've wrote a guide for that here: https://mmatyas.github.io/blog/cross-compiling-servo-to-arm/

@pcwalton, @Adenilson: could you check if this guide works for you too?

**Comment by Adenilson** [comment]
Matyas

Quite funny that I wrote something similar for OSG Blog but didn't
published it yet.
:-)

I will be back from vacations on 14th July and then can test the
instructions.


Cheers


Adenilson

**Comment by mmatyas** [comment]
Now that the patches landed and most dependencies work fine, I've updated the guide again: https://mmatyas.github.io/blog/cross-compiling-servo-to-arm/

In short, if you've set up the ARM and Rust libs, you can now build by simply calling

```
PKG_CONFIG_ALLOW_CROSS=1 \
PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig \
EXPAT_NO_PKG_CONFIG=1 \
CC=arm-linux-gnueabihf-gcc \
CXX=arm-linux-gnueabihf-g++ \
CPP="arm-linux-gnueabihf-gcc -E" \
LD=arm-linux-gnueabihf-ld \
AR=arm-linux-gnueabihf-ar \
RANLIB=arm-linux-gnueabihf-ranlib \
./mach build --target=arm-unknown-linux-gnueabihf --dev
```

The only bug left is in [libexpat](https://github.com/servo/libexpat) which causes compile error for me (`DEP_EXPAT_OUTDIR` doesn't get defined, so the build fails at libfontconfig), This can be avoided by defining `EXPAT_NO_PKG_CONFIG`.

**Comment by mmatyas** [comment]
So now that we have automatic ARM32/ARM64 builds (servo/saltfs#239), I guess it's safe to close this.
