### ISSUE TITLE
Consider appeasing Github's Linguist so that it does not categorize Servo as a web browser written entirely in HTML

### ISSUE THREAD

**Issue by bstrie** [servo/servo#6332]
Currently Github considers Servo to be 92% HTML, 3% Python, and 3% Rust. These statistics are skewed because tests/wpt contains 40 zillion HTML files. It's only a papercut, but considering that Servo is supposed to be Rust's flagship project it's annoying (and perhaps somewhat harms discoverability).

Repository language categorization is handled by Github's Linguist project: https://github.com/github/linguist . Linguist has a feature whereby it assumes that certain hardcoded directories contain code that repo owners do not want counted as part of their language statistics: https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml . We would either need to add a new hardcoded path to this file (which seems kind of gross, but that file already contains hardcoded project-specific paths for Node, PhoneGap, etc. so perhaps they don't mind), or we would need to move the WPT tests into a directory matching one of the directories that Linguist already ignores.

**Comment by larsbergstrom** [comment]
Ours is under the "tests" directory, which I thought would be excluded via the line https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L232-L233 in the file you mentioned...

**Comment by bstrie** [comment]
@larsbergstrom The "fixtures" part of that path doesn't look optional, which is why it's not matching (though I could always be reading this incorrectly).

**Comment by larsbergstrom** [comment]
@bstrie aha! That's an additional path separator; I assumed it was "yet another regexp syntax" for alternating patterns :-)

**Comment by larsbergstrom** [comment]
Hrm. I guess I wouldn't be upset by "external/" (https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L72), but I'm not super excited about any of the options in that file.

**Comment by larsbergstrom** [comment]
Oh, another alternative is "manual overrides": https://github.com/github/linguist#overrides 

I like that much better; would r+.

**Comment by SimonSapin** [comment]
Fixed in #6336. Thanks @nerith !

![screenshot from 2015-06-11 07-55-24](https://cloud.githubusercontent.com/assets/291359/8100668/3fb000aa-100f-11e5-98ca-6a179ddece99.png)

**Comment by bstrie** [comment]
Ah! I should have read further into the README, clearly. :)

**Comment by vectorijk** [comment]
linguist disappear

**Comment by vectorijk** [comment]
@larsbergstrom @nerith @SimonSapin linguist disappear

**Comment by jdm** [comment]
Seems like that's under Github's control; not much we can do about it.
