### ISSUE TITLE
More informative information at the beginning of `./mach build`?

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#6333]
Random idea I've thought about for the past week:

It seems like when one runs `./mach build`, it takes 20 - 30 seconds before any text appears in stdout (even with the verbose flag enabled). It might be more informative if there were a few messages describing what happens before the compilation process. Thoughts?

**Comment by frewsxcv** [comment]
Brief discussion with @mbrubeck on IRC:

> 8:58 PM <•mbrubeck> frewsxcv: RETICULATING SPLINES
> 8:58 PM <frewsxcv> I understood that reference ;)
> 8:59 PM <•mbrubeck> frewsxcv: Seriously though, good idea... I think a big chunk of the time is cargo parsing its config file, but at least we could print "Running cargo build <whatever>" before launching it.
> 8:59 PM <•mbrubeck> frewsxcv: I also hear that a major speedup for that is coming to Cargo soon.
> 8:59 PM <•mbrubeck> s/config file/manifest files/

**Comment by metajack** [comment]
Part of this was a bug in Cargo that @alexcrichton has recently fixed. We'll pick it up when we get #6306 landed.

**Comment by frewsxcv** [comment]
> it takes 20 - 30 seconds before any text appears in stdout

This is no longer the case. It only takes a couple seconds now for me.
