### ISSUE TITLE
Unstable CSS test /css21_dev/html4/absolute-replaced-height-014.htm on macOS

### ISSUE THREAD

**Issue by jgraham** [servo/servo#6342]

**Comment by frewsxcv** [comment]
Relevant to #6266

**Comment by mrobinson** [comment]
Closing this as we don't run MacOS tests and we haven't seen this one recently.

**Comment by mrobinson** [comment]
Re-opening, because it seems this test is disabled.

**Comment by mrobinson** [comment]
This is not disabled on Layout 2020, so I'm going to close this one.
