### ISSUE TITLE
Cache the ID in a field on Element to optimize selectors::Element::get_id

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6359]
Right now, we loop over all the attributes, which is probably too slow.

Code is in `components/script/dom/element.rs`.

**Comment by SimonSapin** [comment]
Should we also/instead make attribute access O(1) with something like a hashmap?

**Comment by SimonSapin** [comment]
Assuming we want to preserve iteration order, https://github.com/contain-rs/linked-hash-map could be relevant.

**Comment by Ms2ger** [comment]
Keyed on what? Attributes are retrieved in a number of ways.

**Comment by SimonSapin** [comment]
Keyed one the qualified name. Is that not enough to make most access O(1)?

**Comment by vinpkjn** [comment]
can someone give me a background of how this ID thing works or point me to relevant documentation?

**Comment by jdm** [comment]
Whenever a page has `<foo id="bar">`, we add an element to the vector of attributes in `Element`. When evaluating CSS selectors like `#bar`, we need to quickly retrieve any id attribute from each element that is checked. Currently we perform a linear search over the attributes (see http://mxr.mozilla.org/servo/source/components/layout/wrapper.rs#587 and http://mxr.mozilla.org/servo/source/components/script/dom/element.rs#234).

**Comment by qvacua** [comment]
Hey, guys. I've got yet no experience in Rust, but I'd like to try this one. Can you assign it to me when no one is actively working on it?

**Comment by jdm** [comment]
@vinpkjn Are you still interested in working on this?

**Comment by vinpkjn** [comment]
I'll do this @jdm

**Comment by vinpkjn** [comment]
I'll give it a try @jdm

**Comment by vinpkjn** [comment]
I'll give it a try.

**Comment by Ms2ger** [comment]
@vinpkjn: hey, are you still working on this?
