### ISSUE TITLE
Entries in the servobuild.example file that are not defaults should be commented out

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#6361]
In the file https://github.com/servo/servo/blob/master/servobuild.example, we should have at least all of the paths commented out. Otherwise, it's easy to accidentally copy this file over to change one setting and end up leaving these broken entries around and causing trouble, especially with cross-compile builds.

**Comment by Sumith1896** [comment]
Is this open to work on? I'd like to tackle this.

**Comment by larsbergstrom** [comment]
@Sumith1896 That would be excellent - thanks much!

**Comment by Sumith1896** [comment]
@larsbergstrom I have sent in a PR
