### ISSUE TITLE
When '--verbose' is passed to mach, it should print out the commands it invokes

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#6363]
This mainly applies to the file https://github.com/servo/servo/blob/master/python/servo/build_commands.py

For example, many of the `subprocess.call` lines like the one at https://github.com/servo/servo/blob/master/python/servo/build_commands.py#L298 should have an additional `print` statement that shows the full command being run.

**Comment by Sumith1896** [comment]
I'll give this a shot. I might take some time figuring it out though.

**Comment by NateBrune** [comment]
I think I did what you want.

**Comment by Sumith1896** [comment]
Cool, go ahead. I was very busy with my project :smile:

**Comment by NateBrune** [comment]
xD I'm sure I wasn't trying to undercut you or anything @Sumith1896 
I was trying to pick something super easy for me to do as my first contribution.

**Comment by Sumith1896** [comment]
Yes, I know. Np :+1:
