### ISSUE TITLE
Remove unsafe around make_unique()

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#6376]
The recent rustup (temporarily) added `unsafe{}` blocks around `Arc::make_unique()`. This is safe because the API was made unsafe in https://github.com/rust-lang/rust/issues/24880 due to bad interactions with weak pointers, but we don't use weak pointers.

Nevertheless, we should remove these unsafe blocks when that API gets fixed.

**Comment by Manishearth** [comment]
Running git revert on https://github.com/servo/servo/commit/94fa868d2b498107d769c889766fbdcf963207d5 should fix this when the library is back to being safe.

**Comment by frewsxcv** [comment]
Fixed in https://github.com/servo/servo/pull/6548
