### ISSUE TITLE
Should send an Origin header.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6379]
Blocks #6060.

At least `websockets/security/001.html` seems to rely on it. Not sure where the spec is. This probably needs to be fixed in https://github.com/cyderize/rust-websocket, though.

**Comment by jdm** [comment]
See https://github.com/cyderize/rust-websocket/issues/10 for how to fix it in Servo, but if the spec requires it...

**Comment by boghison** [comment]
Could you guys point me to where the websocket code is?

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/components/script/dom/websocket.rs , specifically WebSocket::new where it creates a Request object.

**Comment by boghison** [comment]
OK, I guess I could take a stab at this

**Comment by jdm** [comment]
From https://tools.ietf.org/html/rfc6455#section-1.3:
```
The |Origin| header field [RFC6454] is used to protect against
   unauthorized cross-origin use of a WebSocket server by scripts using
   the WebSocket API in a web browser.  The server is informed of the
   script origin generating the WebSocket connection request.  If the
   server does not wish to accept connections from this origin, it can
   choose to reject the connection by sending an appropriate HTTP error
   code.  This header field is sent by browser clients; for non-browser
   clients, this header field may be sent if it makes sense in the
   context of those clients.
```
Sounds like doing it in Servo makes more sense than rust-websocket.

**Comment by boghison** [comment]
@jdm There is a problem I encountered. The Request object is generated by Client::connect (basically the easiest way to do so) and it's immutable, meaning it's not possible to set a header afterwards, so I am stuck.

**Comment by jdm** [comment]
You can make it mutable and call http://doc.servo.org/websocket/client/request/struct.Request.html#method.origin_mut .

**Comment by boghison** [comment]
@jdm I completely forgot you can make it mutable (sorry, I haven't written anything in rust for a while now). But I think I am gonna use set_raw(), because origin wasn't previously set.

**Comment by jdm** [comment]
@Ms2ger Why do you say that security/001.html relies on Origin?

**Comment by Ms2ger** [comment]
I don't remember what I did exactly, but I believe I may have worked around another failure first.
