### ISSUE TITLE
Android nightly's busted.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6384]
http://build.servo.org/builders/android-nightly

**Comment by Manishearth** [comment]
cc @mbrubeck

**Comment by mbrubeck** [comment]
```
/usr/include/freetype2/config/ftheader.h:15:59: fatal error: arm-linux-gnueabi/freetype2/config/ftheader.h: No such file or directory
compilation terminated.
make: *** [/home/servo/buildbot/slave/android-nightly/build/components/servo/target/arm-linux-androideabi/release/build/azure-cc187b961189251d/out/src/azure-c.o] Error 1
thread '<main>' panicked at 'assertion failed: Command::new("make").args(&["-f",
                            "makefile.cargo"]).status().unwrap().success()', /home/servo/.cargo/git/checkouts/rust-azure-03a3575c638f374d/master/build.rs:10
```

**Comment by mbrubeck** [comment]
As far as I can tell, the only differences between the `android` and `android-nightly` builds are that the nightly build uses `--release` and is built on the `servo-head` slave, while the non-nightly builds use `--dev` and are built on `servo-linux-android1`.

Perhaps the difference is related to the version of libfreetype6-dev installed on `servo-head`.

**Comment by mbrubeck** [comment]
Both slaves have the same version of libfreetype6-dev.

**Comment by mbrubeck** [comment]
The `/home/servo/ndk-toolchain` directory on `servo-head` has an older version of GCC (4.6 instead of 4.8).  The newer version is required for the latest mozjs-sys to build.  This might not be related to the current issue though, since @mrobinson is seeing this issue even when building with the 4.8 toolchain.

**Comment by mbrubeck** [comment]
> Both slaves have the same version of libfreetype6-dev.

Oops!  I was wrong here.  The working builder has:

    2.5.2-1ubuntu2

While the failing builder has a newer version:

    2.5.2-2ubuntu1

The new (failing) version includes this change:

```
freetype (2.5.2-1ubuntu5) utopic; urgency=medium

  * Make libfreetype6-dev M-A: same.
  * Error out on the use of the freetype-config --libtool option.
  * Don't add multiarch libdirs for freetype-config --libs.
  * Install the freetype2/config headers into the multiarch include path
    and provide symlinks in /usr/include.
```
