### ISSUE TITLE
Use JS_FNSPEC style macros to improve CodegenRust output

### ISSUE THREAD

**Issue by michaelwu** [servo/servo#6391]
This is another followup to https://github.com/servo/servo/pull/6150 .

Gecko uses JS_FNSPEC macros to specify JSFunctionSpec entries. We should do something similar to clean up the output of CodegenRust.

**Comment by nox** [comment]
There are various ways to make the output of `CodegenRust.py` better, but these ways don't need to follow exactly what Gecko does, nor do we need to file an issue for each one of its idiosyncrasies. Closing.
