### ISSUE TITLE
Compress WPT logs during automated builds

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#6399]
Today, we log the raw Web Platform and CSS tests logs on the server on Linux:
https://github.com/servo/saltfs/blob/master/buildbot/master/master.cfg#L130-L133
https://github.com/servo/saltfs/blob/master/buildbot/master/master.cfg#L139-L142
and OSX:
https://github.com/servo/saltfs/blob/master/buildbot/master/master.cfg#L153-L156
https://github.com/servo/saltfs/blob/master/buildbot/master/master.cfg#L169-L172

Adding an extra step to 'gzip' the output file and then having buildbot use those as the logfiles would dramatically reduce disk usage (the raw logs are around 100MB; gzip'd they are around 3MB!).

**Comment by Yomi0** [comment]
I would like to try this, but I've never touched a .cfg file before. 

It seems I might be able to do pass ```logfiles``` to gzip and save myself a few keystrokes. 

Something like, ```["gzip", logfiles,]``` or, if I can't do that, then, ```["gzip", "wpt_raw.log"]```.

**Comment by larsbergstrom** [comment]
@Yomi0 Thanks for looking at it! I believe that the second option will work. I confirmed that `gzip` should be available on all of our build machines.

**Comment by Wafflespeanut** [comment]
@larsbergstrom As this isn't much active for a while, I've opened a PR for this here (https://github.com/servo/saltfs/pull/77)
