### ISSUE TITLE
about:blank doesn't fire load event

### ISSUE THREAD

**Issue by metajack** [servo/servo#6400]
Starting Servo with webdriver preloaded to about:blank and then creating a session and then loading about:blank doesn't do anything. It basically just waits forever to get the load event.

Start servo with: `target/release/servo --cpu --hard-fail --webdriver 4444 about:blank`
Create a session with: `curl -X POST http://127.0.0.1:4444/session -d "{}"`
Load a URL with: `curl -v -X POST http://127.0.0.1:4444/session/some_session_id/url -d '{"url":"about:blank"}'`

You won't get a response as it's hanging here:
https://github.com/servo/servo/blob/master/components/webdriver_server/lib.rs#L179

**Comment by metajack** [comment]
cc @jgraham

**Comment by simartin** [comment]
I think it might have been fixed (by https://github.com/servo/servo/pull/8558 ?)

lyton:servo simon$ target/debug/servo --cpu --hard-fail --webdriver 4444 about:blank &
[1] 4493
lyton:servo simon$ curl -X POST http://127.0.0.1:4444/session -d "{}"
{"sessionId":"8dbe5739-8531-43da-b0aa-0dcc1fd2c8b1","value":{"acceptSslCerts":false,"browserName":"servo","browserVersion":"0.0.1","takeElementScreenshot":false,"takeScreenshot":true}}
lyton:servo simon$ curl -v -X POST http://127.0.0.1:4444/session/8dbe5739-8531-43da-b0aa-0dcc1fd2c8b1/url -d '{"url":"about:blank"}'
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4444 (#0)
> POST /session/8dbe5739-8531-43da-b0aa-0dcc1fd2c8b1/url HTTP/1.1
> Host: 127.0.0.1:4444
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 21
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 21 out of 21 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 2
< Date: Wed, 02 Dec 2015 23:00:12 GMT
<
* Connection #0 to host 127.0.0.1 left intact

Or am I misunderstanding the description?

**Comment by nox** [comment]
Wasn't this fix, @jdm? When you improved initial loading of `about:blank` etc.

**Comment by jdm** [comment]
We overcompensated and made `<iframe src="about:blank">` fire two load events instead.
