### ISSUE TITLE
Implement mouseover event

### ISSUE THREAD

**Issue by glennw** [servo/servo#6404]
This would be super useful for demos.

https://developer.mozilla.org/en-US/docs/Web/Events/mouseover
https://html.spec.whatwg.org/multipage/infrastructure.html#event-mouseover

**Comment by pcwalton** [comment]
+1, I just had to change `mouseover` to `mousemove` in my demo to get things working in Servo.

**Comment by pcwalton** [comment]
Adding E-easy since I don't think this will be hard.

**Comment by yoava333** [comment]
Hi,
Could you assign this to me?
I'd like to try to implement this

**Comment by glennw** [comment]
@yoava333 We can't assign it to you at the moment due to how our github permissions are set up, but please feel free to start working on it!

**Comment by jdm** [comment]
https://w3c.github.io/uievents/#event-type-mouseover is a more useful link for the relevant spec.
