### ISSUE TITLE
Canvas remains dirty during animations

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#6418]
The canvas doesn't get cleared, and the frames continue to draw on top of each other during animations, like [this](https://mmatyas.github.io/canvas_anim.html) and [this](https://mmatyas.github.io/canvas_clock.html). These use clearRect to clear the canvas, but that seems to work correctly, at least I don't have problems with the [example code](http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_canvas_clearrect). Dirtiness for the canvas was introduced in #5949, but unfortunately I can't bisect this issue due to half of the commits are affected with the X11 colorspace bug which was fixed some weeks ago. The problem might be in one of the dependencies too, maybe in azure.

![kepernyokep errol 2015-06-18 18 03 44](https://cloud.githubusercontent.com/assets/4354863/8235810/6dadc818-15e4-11e5-8915-c26a610cb190.png)

**Comment by mmatyas** [comment]
I've managed to bisect this by applying the X11 fixes manually, it seems this broke first in 3350522306ee087f892108ee82aeb9d58ee2363d, aka #6083 ...which touches quite a few files.

I wonder if @pcwalton or @ecoal95 could take a look on this?

**Comment by ecoal95** [comment]
The way we render into the canvas didn't change in that PR (we keep sending pixels and transforming it into an image display item.

At first I thought it was due a problem in `clear_rect` but I've just taken a look at it, and not forcing the canvas to get a layer (applying [this diff](https://gist.github.com/ecoal95/8b3fc0d73e7e7c6dbab0) on the commit you mentioned) makes the animation work again.

Basically having the canvas in its own paint layer makes it to remain dirty under certain conditions... But I don't really know why.

It happens just in a few cases (I think it's just when it's `display: inline` (the default) and `position` not `fixed` or `absolute`), so this is a deeper problem I think.

A canvas layer with `display: block;` or `display: inline-block` will animate nicely right now (just replacing `<canvas` with `<canvas style="display: block"` in your example). 

It will also animate correctly without changing the default `display` property if you use `position: absolute` or `position: fixed`.

I guess @pcwalton or @glennw could give a bit of insight on this.

**Comment by mmatyas** [comment]
Looks like this was fixed, or at least doesn't happen to me. Anyone else still experiencing this bug?
