### ISSUE TITLE
Send an error to the parent when there is an exception in the worker

### ISSUE THREAD

**Issue by michaelwu** [servo/servo#6422]
This is somewhat of a followup to https://github.com/servo/servo/pull/6150 .

Per https://html.spec.whatwg.org/multipage/#runtime-script-errors-2 , when there's an error in the worker, it needs to be reported to the parent. At the moment the exception is just thrown inside the worker when the evaluate_script call in dedicatedworkerglobalscope.rs throws an exception.

**Comment by nox** [comment]
We do that now.

**Comment by jdm** [comment]
I don't see where this happens. There's still a TODO pointing at this issue.

**Comment by jdm** [comment]
Nevermind, I see the forwarding code in GlobalScope::report_an_error.
