### ISSUE TITLE
Heap should not have a drop flag.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6428]
This should block the smup from landing, but since everyone is hell-bent on landing it over my objections, I'll just file it.

CC @michaelwu

**Comment by SimonSapin** [comment]
Is this more involved than adding `#[unsafe_no_drop_flag]` somewhere?

**Comment by Ms2ger** [comment]
Might need to have the dtor check for drop glue too? I haven't been following it all.

**Comment by SimonSapin** [comment]
If `#[unsafe_no_drop_flag]` is used and the destructor is not "naturally idempotent", it should check for `std::mem::dropped()` patterns… I think.

If you want to inhibit the implicit destruction of struct fields https://crates.io/crates/nodrop can do it until https://github.com/rust-lang/rfcs/pull/197 is added to the language.

**Comment by metajack** [comment]
If this fix works, can we just include it and land it? That seems like it would be expedient *and* satisfy ms2ger's objections.

**Comment by nox** [comment]
Drop flags are no more.
