### ISSUE TITLE
Use automatic bindings for rust-egl

### ISSUE THREAD

**Issue by emilio** [servo/servo#6430]
`rust-egl` is unmaintained, and not all the possible bindings are there, using automatic bindings could be a good option to make it more consistent with other repos like `rust-glx`.

It will require to update:
- [ ] layers
- [ ] ports/gonk
- [ ] ports/glutin

Most of the refactoring will just be `unsafe {}` wrappers and changing constants from `egl::EGL_XX` to `egl::XX`, so won't be such an amount of work.

cc @glennw

**Comment by dralley** [comment]
I think the only thing still using this is ```libmlservo```

**Comment by mrobinson** [comment]
I think this isn't an issue any longer.
