### ISSUE TITLE
thread 'http_loader' panicked at 'called `Result::unwrap()` on an `Err` value: ()'

### ISSUE THREAD

**Issue by yoava333** [servo/servo#6442]
I tried to use servo to run "http://play.typeracer.com"

I'm getting a panic:

thread 'http_loader' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/larsberg/rust/src/libcore/result.rs:731

stack backtrace:

    1:        0x112152345 - sys::backtrace::write::h0f775b94d5ab846csas
    2:        0x112155c04 - panicking::on_panic::h2c2da1880263a4ecOtw
    3:        0x112142638 - rt::unwind::begin_unwind_inner::h4859292dfbc160e26bw
    4:        0x112142cfc - rt::unwind::begin_unwind_fmt::h96f92c9348b5a966cbw
    5:        0x1121554bc - rust_begin_unwind
    6:        0x11217d875 - panicking::panic_fmt::h8dfe66741ed7f9d7i5B
    7:        0x1102da96b - result::Result<T, E>::unwrap::h7379346008122980928
    8:        0x110c11e70 - network_listener::NetworkListener<T>.AsyncResponseTarget::invoke_with_listener::h3773454481418489070
    9:        0x11144fa65 - resource_task::start_sending_opt::h12d681e7861123174od
    10:        0x11149c0b6 - resource_task::start_sending_sniffed_opt::ha8a7d5cec70e46787kd
    11:        0x11149952a - http_loader::send_data::h5597924369967142072
    12:        0x11144ec3c - http_loader::load::h56b1c263f2bf66c06la
    13:        0x111447d13 - http_loader::factory::closure.18118
    14:        0x111447a4e - task::spawn_named::closure.18112
    15:        0x111447964 - boxed::F.FnBox<A>::call_box::h15085865637376503080
    16:        0x1113f41ab - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h5109187854690115640
    17:        0x1113f3c3b - thread::Builder::spawn_inner::closure.16345
    18:        0x1113f3bbe - rt::unwind::try::try_fn::__rust_abi::h4166549616951838587
    19:        0x1113f3b59 - rt::unwind::try::try_fn::h4166549616951838587
    20:        0x1121577b8 - rust_try_inner
    21:        0x1121577a5 - rust_try
    22:        0x112150535 - rt::unwind::try::inner_try::h27133e9e14aca845Z7v
    23:        0x1113f3abf - rt::unwind::try::h10901007630266712321
    24:        0x1113f38f4 - thread::Builder::spawn_inner::closure.16294
    25:        0x1113f455d - boxed::F.FnBox<A>::call_box::h2073976662700341941
    26:        0x11215454d - sys::thread::Thread::new::thread_start::hd4ea41c9b4c4555dywv
    27:     0x7fff892c7267 - _pthread_body
    28:     0x7fff892c71e4 - _pthread_start

I tried debug this, and I got from this flow
https://github.com/servo/servo/blob/master/components/net/resource_task.rs#L149
https://github.com/servo/servo/blob/master/components/script/network_listener.rs#L18
and finally this:
https://github.com/servo/servo/blob/master/components/script/script_task.rs#L235

I've added debug prints to map_err to make sure that that's the faulting path.
I read the documentation that the reason send would fail is because the receiving end is closed. 
I got all the way back to ResourceManager and It seems that someone is sending a ControlMessage::Load message.
from there to ScriptTask.start_load_page, for some reason the self.chan seems to be closed.

The offending url is http://typeracer.com/dynamic_content/typing_game_as_728x90.html?t=1409059323
when I try to load it with servo directly it's all ok.

**Comment by yoava333** [comment]
@jdm I've tested again and this issue doesn't exists anymore, I suggest closing this issue.

**Comment by jdm** [comment]
Yes, I would expect this to be fixed by 61e3a9545ecd3b93e275af6dfa425a7fdd42f9db. Thanks!
