### ISSUE TITLE
Implement document.hasFocus

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#6475]
http://www.whatwg.org/specs/web-apps/current-work/#focus-management

cc #5394

**Comment by mskrzypkows** [comment]
I can try this task.

**Comment by mskrzypkows** [comment]
I'm trying to implement point 4. form: https://html.spec.whatwg.org/multipage/interaction.html#dom-document-hasfocus. How can I check if document has a dialog group, then how to check if document has a non-empty control group? I haven't found any method returning it, is it available in servo?

**Comment by mbrubeck** [comment]
> How can I check if document has a dialog group, then how to check if document has a non-empty control group?

I believe Servo does not yet support these features.  You can just skip this step for now, and put a "TODO" comment in the code.
