### ISSUE TITLE
Use more elements and less nodes in layout/css/matching.rs

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#6476]
rust-selectors changed some APIs to work on elements rather than arbitrary nodes: #6468

Some methods like `share_style_with_candidate_if_possible` and `match_node` now start with `let element = self.as_element().unwrap();`, and should probably also be changed to have element parameters instead.

**Comment by nox** [comment]
Is this still something we want to do?

**Comment by SimonSapin** [comment]
`selectors` is now elements all the way.
