### ISSUE TITLE
[Warning] Could not generate notification!No module named Foundation

### ISSUE THREAD

**Issue by jruderman** [servo/servo#6479]
At the end of my build, I get:

    [Warning] Could not generate notification!No module named Foundation

Looks like `python/servo/build_commands.py` is trying to generate a desktop notification (to tell me the build is finished), but it's doing so in a way that requires a module I don't have, so it's getting an ImportError.

**Comment by metajack** [comment]
Just for anyone else that wants to install this, `pip install pyobjc` will fix it. But we should trap the import error.

**Comment by mt2d2** [comment]
If possible, I'd like to take a stab at this.

**Comment by dwins** [comment]
Looks like this can be closed.  I am building on OS X without `pyobjc` and I get an error message that says so.
