### ISSUE TITLE
Graphical corruption when resizing on www.emscripten.org

### ISSUE THREAD

**Issue by kripken** [servo/servo#6486]
I see this on Ubuntu on Servo built from github master. STR:
1. Run `./mach run -r http://www.emscripten.org`
2. Resize the window quickly, holding down the mouse on the lower-right corner and just moving the mouse around.

Every second or so I see a frame or two of what looks like corrupt data. @pcwalton says the compositor thread might be running out of sync with the rendered data somehow.

**Comment by nox** [comment]
I don't see corrupted frames anymore.
