### ISSUE TITLE
segfault in sm when running servo-shell on linux

### ISSUE THREAD

**Issue by glennw** [servo/servo#6515]
Run servo-shell on linux (e.g: ./target/debug/servo -e ../servo-shell/index.html).

CC @michaelwu 

    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fffcf3ff700 (LWP 6657)]
    js::Allocate<JSString, (js::AllowGC)1> (cx=cx@entry=0x7fffb80270b0)
        at /home/gw/code/work/servo_main/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/gc/Allocator.cpp:225
    225         return GCRuntime::tryNewTenuredThing<T, allowGC>(cx, kind, thingSize);
    (gdb) bt
    #0  js::Allocate<JSString, (js::AllowGC)1> (cx=cx@entry=0x7fffb80270b0)
        at /home/gw/code/work/servo_main/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/gc/Allocator.cpp:225
    #1  0x000055555739e450 in new_<(js::AllowGC)1> (cx=<optimised out>)
        at /home/gw/code/work/servo_main/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/String-inl.h:250
    #2  AllocateInlineString<(js::AllowGC)1, unsigned char> (chars=<synthetic pointer>, len=<optimised out>, cx=0x7fffb80270b0)
        at /home/gw/code/work/servo_main/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/String-inl.h:30
    #3  NewInlineStringDeflated<(js::AllowGC)1> (chars=..., cx=0x7fffb80270b0)
        at /home/gw/code/work/servo_main/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/String.cpp:987
    #4  NewStringDeflated<(js::AllowGC)1> (cx=0x7fffb80270b0, s=0x7fffce423720 u"about:blank", n=<optimised out>)
        at /home/gw/code/work/servo_main/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/String.cpp:1004
    #5  0x00005555571f888d in js::jsapi::JS_NewUCStringCopyN (cx=0x7fffb80270b0, s=0x7fffce423720, n=11)
        at /home/gw/code/work/servo_main/servo/.cargo/git/checkouts/rust-mozjs-ebb4917e843c0a11/master/src/jsapi.rs:9517
    #6  0x00005555571f881a in jsapi::JS_NewUCStringCopyN::h16ac17d5a8c84a62CPi ()
    #7  0x00005555569303d9 in script::dom::bindings::conversions::str.ToJSValConvertible::to_jsval (self=..., cx=0x7fffb80270b0, rval=...)
        at /home/gw/code/work/servo_main/servo/components/script/dom/bindings/conversions.rs:301
    #8  0x00005555569322ef in script::dom::bindings::conversions::DOMString.ToJSValConvertible::to_jsval (self=0x7fffcf3fafd8,
        cx=0x7fffb80270b0, rval=...) at /home/gw/code/work/servo_main/servo/components/script/dom/bindings/conversions.rs:313
    #9  0x000055555693d8ec in script::dom::bindings::conversions::Option<T>.ToJSValConvertible::to_jsval (self=0x7fffcf3fafd8,
        cx=0x7fffb80270b0, rval=...) at /home/gw/code/work/servo_main/servo/components/script/dom/bindings/conversions.rs:630
    #10 0x0000555556eeba38 in script::dom::htmliframeelement::&'a HTMLIFrameElement.HTMLIFrameElementHelpers::dispatch_mozbrowser_event (
        self=0x7fffa71cfa80, event=...) at /home/gw/code/work/servo_main/servo/components/script/dom/htmliframeelement.rs:159
    #11 0x00005555570dc9cb in script::script_task::ScriptTask::handle_mozbrowser_event_msg (self=0x7fffcf3fe050, parent_pipeline_id=...,
        subpage_id=..., event=...) at /home/gw/code/work/servo_main/servo/components/script/script_task.rs:1030
    #12 0x00005555570d9dd7 in script::script_task::ScriptTask::handle_msg_from_constellation (self=0x7fffcf3fe050, msg=...)
        at /home/gw/code/work/servo_main/servo/components/script/script_task.rs:740
    #13 0x00005555570b2e80 in script::script_task::ScriptTask::handle_msgs (self=0x7fffcf3fe050)
        at /home/gw/code/work/servo_main/servo/components/script/script_task.rs:687
    #14 0x00005555570b1462 in script::script_task::ScriptTask::start (self=0x7fffcf3fe050)
        at /home/gw/code/work/servo_main/servo/components/script/script_task.rs:555
    #15 0x0000555555b35f2a in fnfn () at /home/gw/code/work/servo_main/servo/components/script/script_task.rs:420
    #16 0x0000555555b35695 in fnfn () at /home/gw/code/work/servo_main/servo/components/util/task.rs:31
    #17 0x0000555555b355b5 in servo::boxed::F.FnBox<A>::call_box (self=0x7fffcfc3f280, args=0) at src/liballoc/boxed.rs:398
    #18 0x0000555555a665e5 in servo::boxed::Box<FnBox<A, Output = R>+ Send + 'a>.FnOnce<A>::call_once (self=..., args=0)
        at src/liballoc/boxed.rs:414
    #19 0x0000555555a66093 in fnfn () at src/libstd/thread/mod.rs:349
    #20 0x0000555555a6600f in servo::rt::unwind::try::try_fn<closure> (opt_closure=0x7fffcf3fe9e0) at src/libstd/rt/unwind/mod.rs:158
    #21 0x0000555555a65faa in rt::unwind::try::try_fn::h958475009669932557 ()
    #22 0x0000555558162839 in rust_try_inner ()
    #23 0x0000555558162826 in rust_try ()
    #24 0x0000555558157a18 in rt::unwind::try::inner_try::ha8590c29f21017bcrJw ()
    #25 0x0000555555a65f19 in servo::rt::unwind::try<closure> (f={void (())} 0x7fffcf3fea00) at src/libstd/rt/unwind/mod.rs:130
    #26 0x0000555555a65d84 in fnfn () at src/libstd/thread/mod.rs:349
    #27 0x0000555555a668ee in servo::boxed::F.FnBox<A>::call_box (self=0x7fffcfc30150, args=0) at src/liballoc/boxed.rs:398
    #28 0x000055555815c3d2 in sys::thread::Thread::new::thread_start::h63af462716e59b66oTv ()
    #29 0x00007ffff79bc182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
    #30 0x00007ffff71cc47d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by michaelwu** [comment]
Looks like something is missing a JSAutoRequest.
