### ISSUE TITLE
Change Servo to use the high level freetype-rs bindings.

### ISSUE THREAD

**Issue by glennw** [servo/servo#6534]
We currently use a low level FFI wrapper: https://github.com/servo/rust-freetype

We should change to use the high level wrapper here: https://github.com/PistonDevelopers/freetype-rs

However, this is slightly complicated because the servo wrapper contains the native freetype code in tree, so that it can be built for android. The high level wrapper doesn't include the native freetype code, it just links to the system freetype library.

**Comment by HarryLovesCode** [comment]
Is something preventing us from forking `PistonDevelopers/freetype-rs` and modifying it to link against `servo/freetype-sys` (repository is named `servo/libfreetype2`)?

**Comment by glennw** [comment]
I *think* the Piston version isn't set up to build the native lib (which is required for our android build).

**Comment by jdm** [comment]
Oh, I missed when this was filed. There's a bunch of prior discussion in #3369 about how this is more complicated than it first appears.
