### ISSUE TITLE
Update freetype and investigate sharing FT_Library instances

### ISSUE THREAD

**Issue by glennw** [servo/servo#6535]
As noted in http://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html

`In multi-threaded applications it is easiest to use one ‘FT_Library’ object per thread. In case this is too cumbersome, a single ‘FT_Library’ object across threads is possible also (since FreeType version 2.5.6), as long as a mutex lock is used around FT_New_Face and FT_Done_Face.`

This may save a large amount of memory since we could share the library object between the multiple layout and paint threads.

**Comment by nical** [comment]
Note that you still can't use the same FT_Face object from multiple threads.
