### ISSUE TITLE
Integrate xml5ever

### ISSUE THREAD

**Issue by jdm** [servo/servo#6539]
https://github.com/Ygg01/xml5ever is an XML parser with a very similar interface to html5ever. We should integrate it into http://mxr.mozilla.org/servo/source/components/script/parse/ using html.rs as a model, and adapt ServoHTMLParser to use either the html5ever types or xml5ever types as necessary: http://mxr.mozilla.org/servo/source/components/script/dom/servohtmlparser.rs . The first direct user can be http://mxr.mozilla.org/servo/source/components/script/dom/domparser.rs#72 .

**Comment by SimonSapin** [comment]
https://tools.ietf.org/html/rfc7303 is relevant, though I haven’t looked into the details yet.

**Comment by yati-sagade** [comment]
I would like to have a go at this one. I kind of understand what needs to be done here, but could use some help.

**Comment by jdm** [comment]
@yati-sagade You're welcome to it, and I'll attempt to explain anything that is confusing!

**Comment by mattnenterprise** [comment]
I would like to do this if it is still available.

**Comment by jdm** [comment]
@mattnenterprise Sorry to keep turning you down :( This is listed as a potential project for a group of students right now; I'll let you know once I hear back whether it's claimed or not.

**Comment by jdm** [comment]
To the best of my knowledge there are students working on this right now.

**Comment by KiChjang** [comment]
Has this been already fully integrated by the students at NCSU?

**Comment by jdm** [comment]
Yeah, I'll file new issues for things that are still missing.
