### ISSUE TITLE
Click doesn't walk up the tree

### ISSUE THREAD

**Issue by jdm** [servo/servo#6544]
```js
var a = document.body.appendChild(document.createElement("a"));
a.textContent = "bar ";
a.setAttribute("href", "http://www.yahoo.com");
var b = a.appendChild(document.createElement("a"));
b.textContent = "baz";
```
In about:blank in Firefox, calling `b.click()` causes yahoo.ca to load, but after the changes in #6543 this doesn't work in Servo. We should figure out the part of the spec that calls for this.

**Comment by Ms2ger** [comment]
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3556
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27430
https://html.spec.whatwg.org/multipage/#dom-click

**Comment by Ms2ger** [comment]
And I don't think this worked before #6543 in Servo

**Comment by jdm** [comment]
Yes, my wording was ambiguous.

**Comment by jdm** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1180670, https://code.google.com/p/chromium/issues/detail?id=507267&thanks=507267&ts=1436188111, and https://bugs.webkit.org/show_bug.cgi?id=146637.
