### ISSUE TITLE
Passing 'undefined' explicitly to a JS function should utilize default parameter value

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#6558]
I was looking into why [this WPT test](https://github.com/servo/servo/blob/0fb6604cb37da0ca0f4852328def21100a38fd63/tests/wpt/web-platform-tests/dom/traversal/TreeWalker-basic.html#L92-L97) is failing. We specify a [default value in the webidl](https://github.com/servo/servo/blob/0fb6604cb37da0ca0f4852328def21100a38fd63/components/script/dom/webidls/Document.webidl#L64). Currently, if we pass in `undefined` explicitly into the `createTreeWalker` function, it does *not* use the default parameter value (`0xFFFFFFFF`) and instead, it converts `undefined` to `0`. If `undefined` gets passed in, we should use the default parameter value.

**Comment by mt2d2** [comment]
I [took a stab](https://github.com/mt2d2/servo/commit/2ce77bf58a06a646398ea57bac271873aea6cd71) at this with the help of mwu on IRC. We think that the value being converted by the spidermonkey long path is coming out as 0 without error, and established that neither the conversion routine nor spidermonkey has access to the default value. Thus, I think it's the responsibility of the caller to handle the the undefined case, which, here, is the binding code.

I'm not sure if this is the best way to do this. I would really appreciate input, since I don't understand the whole impact of changing the binding generator. Also would appreciate guidance on what tests should run.

./mach test-wpt using master:
```
Summary
=======

Ran 206865 tests (2488 parents, 204377 subtests)
Expected results: 206782
Unexpected results: 1 (CRASH: 1)
Skipped: 82

Unexpected Results
==================

/websockets/constructor/004.html
--------------------------------
```

undefined_conversion_binding
```
Summary
=======

Ran 206865 tests (2488 parents, 204377 subtests)
Expected results: 206781
Unexpected results: 2 (CRASH: 1, PASS: 1)
Skipped: 82

Unexpected Results
==================

/dom/traversal/TreeWalker-basic.html
------------------------------------
PASS expected FAIL Construct a TreeWalker by document.createTreeWalker(root, undefined, undefined).
/websockets/constructor/004.html
--------------------------------
```

**Comment by jdm** [comment]
FWIW I suspect the code that handles this in Gecko is http://mxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py#5460 .

**Comment by frewsxcv** [comment]
> Also would appreciate guidance on what tests should run.

`./mach test-wpt tests/wpt/web-platform-tests/dom/traversal/TreeWalker-basic.html`

In particular, [this test](https://github.com/servo/servo/blob/0fb6604cb37da0ca0f4852328def21100a38fd63/tests/wpt/web-platform-tests/dom/traversal/TreeWalker-basic.html#L92-L97). The result of `document.createTreeWalker(root, undefined, undefined)` should be the same as `document.createTreeWalker(root)`, but this is apparently not the case.

**Comment by frewsxcv** [comment]
Ignore my previous comment.

@mt2d2 I think the code you pasted above does the right thing, no?

Also, I updated it to work with the latest changes:

```diff
diff --git a/components/script/dom/bindings/codegen/CodegenRust.py b/components/script/dom/bindings/codegen/CodegenRust.py
index a46c58f..760ebcd 100644
--- a/components/script/dom/bindings/codegen/CodegenRust.py
+++ b/components/script/dom/bindings/codegen/CodegenRust.py
@@ -1066,12 +1066,6 @@ def getJSToNativeConversionInfo(type, descriptorProvider, failureCode=None,
     if type.nullable():
         declType = CGWrapper(declType, pre="Option<", post=">")

-    template = (
-        "match FromJSValConvertible::from_jsval(cx, ${val}, %s) {\n"
-        "    Ok(v) => v,\n"
-        "    Err(_) => { %s }\n"
-        "}" % (conversionBehavior, exceptionCode))
-
     if defaultValue is not None:
         if isinstance(defaultValue, IDLNullValue):
             assert type.nullable()
@@ -1089,6 +1083,27 @@ def getJSToNativeConversionInfo(type, descriptorProvider, failureCode=None,
     else:
         defaultStr = None

+    if defaultStr is not None and defaultStr != "None":
+        # If null or undefined is explicitly passed into a parameter that has a
+        # default value specified in the WebIDL (and the default value is not
+        # None), we should ignore the null or undefined and use the default
+        # value.
+        template = (
+            "if ${val}.get().is_null_or_undefined() {\n"
+            "    %s\n"
+            "} else {\n"
+            "    match FromJSValConvertible::from_jsval(cx, ${val}, %s) {\n"
+            "        Ok(v) => v,\n"
+            "        Err(_) => { %s }\n"
+            "    }\n"
+            "}" % (defaultStr, conversionBehavior, exceptionCode))
+    else:
+        template = (
+            "match FromJSValConvertible::from_jsval(cx, ${val}, %s) {\n"
+            "    Ok(v) => v,\n"
+            "    Err(_) => { %s }\n"
+            "}" % (conversionBehavior, exceptionCode))
+
     return handleOptional(template, declType, defaultStr)
```

**Comment by mt2d2** [comment]
@frewsxcv yes, the key was use the default string if the value is 'undefined'. It did make this test pass, but I was worried about possible regressions. ./mach test-wpt came back clean (aside from a crash that happened on master, too). Changing the generator just seemed far-reaching to me. I'll happily bring the patch up-to-date if you guys agree with this approach. Thanks!

**Comment by Ms2ger** [comment]
The `null` part of
```diff
+        # If null or undefined is explicitly passed into a parameter that has a
+        # default value specified in the WebIDL (and the default value is not
+        # None), we should ignore the null or undefined and use the default
+        # value.
```
is not true. I'd be very concerned if that didn't cause any tests to fail.

**Comment by frewsxcv** [comment]
I was thinking that, but forgot to test it. I can create a regression test for it in web-platform-tests, unless we want to include it with the PR for this issue

**Comment by frewsxcv** [comment]
Regression test added in https://github.com/w3c/web-platform-tests/issues/2058

**Comment by mt2d2** [comment]
@Ms2ger thank you for the insight! I can confirm that the previous implementation causes a failure on @frewsxcv new regression tests. I've taken both your input on commenting and null checking to produce a new patch that passes the target as well as the new regression tests. 

I have a [new spin](https://github.com/servo/servo/compare/master...mt2d2:undefined_conversion_binding) that I'm working on validating against master.  The important bit follows. If you think this is the correct approach, I can continue working on it toward final submission. 
```python
if defaultStr is not None and defaultStr != "None":
    # If undefined is explicitly passed into a parameter that has a default
    # value specified in the WebIDL (and the default value is not None), we
    # should ignore undefined and use the default value. The same does not
    # apply to null.
    template = (
        "if ${val}.get().is_undefined() {\n"
        "    %s\n"
        "} else {\n"
        "    match FromJSValConvertible::from_jsval(cx, ${val}, %s) {\n"
        "        Ok(v) => v,\n"
        "        Err(_) => { %s }\n"
        "    }\n"
        "}" % (defaultStr, conversionBehavior, exceptionCode))
```

**Comment by frewsxcv** [comment]
For me at least, it looks alright

**Comment by Ms2ger** [comment]
I'm very skeptical about anything that reads `defaultStr`.
