### ISSUE TITLE
--exit flag not working

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#6587]
The load-after-exit flag (`-x, --exit`) doesn't seem to be exiting even for the simplest pages.

**Comment by connorimes** [comment]
@LalehB this affects the PowerMeasure script

**Comment by connorimes** [comment]
This appears to have been removed in 898c1ecc8fb885e1ed90d148cfadbb30d337ea49 but is a capability we still need for some types automated testing (e.g. power/energy profiling).

**Comment by connorimes** [comment]
CC @glennw as author of aforementioned commit.

**Comment by frewsxcv** [comment]
This was presumably fixed by #6666 (😈) and it works for me with the latest master
