### ISSUE TITLE
Setting the value of input type=button doesn't update its rendering

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6599]
``` html
<!DOCTYPE html>
<p><input type=button value=Loading>
<script>
setTimeout(function() {
  document.querySelector("input").value = "Run";
  document.body.appendChild(new Text("run"))
}, 500)
</script>
```

(reduced from dromaeo)

**Comment by jdm** [comment]
Odd, http://mxr.mozilla.org/servo/source/components/script/dom/htmlinputelement.rs#273 includes a force_relayout call that I would expect to be working here.

**Comment by Ms2ger** [comment]
`-i` doesn't help, fwiw.

CC @pcwalton @SimonSapin

**Comment by jdm** [comment]
This works now.
