### ISSUE TITLE
Assertion failure: (int32_t) tarr->type() == Scalar::Float32 with bufferData

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6602]
```html
<!DOCTYPE html>
<canvas></canvas>
<script>
var c = document.querySelector("canvas");
var ctx = c.getContext("webgl");
var buffer = new Uint8Array([0, 1, 2]);
ctx.bufferData(0, buffer, 0);
</script>
```

**Comment by pcwalton** [comment]
Same comment as before. This code is the culprit: https://github.com/servo/servo/blob/master/components/script/dom/webglrenderingcontext.rs#L261

If it was not necessary to drop down to unsafe code here, then I suggest writing a wrapper that actually checks the types before calling the JSAPI and returns a `Result`.

**Comment by simartin** [comment]
I believe this issue can be closed; the reported case is tested at least through https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/webgl/bufferData.html
