### ISSUE TITLE
Display-list-based invalidation

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#661]
Like Gecko does, we should do display-list based invalidation in Servo to avoid rendering more tiles than necessary.

Each layer should keep a pointer to its previous display list. (This should be done already because of the tiled rendering.) Then, when a new display list comes in, the two display lists should be diffed to determine an invalid region. Only the invalid tiles should be repainted.

The relevant Gecko bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=dlbi

**Comment by glennw** [comment]
I think we can close this as irrelevant now :)
