### ISSUE TITLE
Make tidy check for "*" dependencies in Cargo.toml files

### ISSUE THREAD

**Issue by jdm** [servo/servo#6623]
I believe (and @SimonSapin can confirm) that we're moving towards requiring specific versions for all Crates.io dependencies instead of just "*" (meaning any version is allowed). We should enforce that in pre-commit hooks by having the tidy.py script check this.

Code: python/tidy.py

**Comment by Ms2ger** [comment]
I feel this is solving a problem we don't really have right now, and it will cause us to depend on multiple versions of the same crate a lot more often.

**Comment by metajack** [comment]
I think a reasonable compromise is to use one digit only. If we need a second digit, add it. We should probably never need all three digits.

Is there a reason not to use that? That should minimize dupes.

**Comment by SimonSapin** [comment]
> @SimonSapin can confirm

I argued for it, and only @Manishearth responded: https://www.mail-archive.com/dev-servo@lists.mozilla.org/msg01332.html

**Comment by metajack** [comment]
Ah, so we've all misunderstood what the "0.1.3" meant. So precise verions sound just fine then.

**Comment by SimonSapin** [comment]
TOML parser for Python: https://pypi.python.org/pypi/toml/ (i.e don’t do it by hand)

**Comment by boghison** [comment]
I'm sorry if this is a stupid question, but is it mandatory to use the toml parser, because I think it would be simpler to just check for an asterisk in the file, this would also allow to see on which line this is happening (that can't be done through the parser AFAIK)

**Comment by jdm** [comment]
That solution sounds ok to me.

**Comment by boghison** [comment]
@jdm I am gonna file a PR then
