### ISSUE TITLE
Implement mutation observers

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#6633]
I've started some patches for this.

**Comment by jdm** [comment]
cc @nox

**Comment by nox** [comment]
Colour me interested. Why do you think mutation observers are the way to go for DOM ranges?

**Comment by dzbarsky** [comment]
Note that these aren't the DOM mutation observers, just an internal servo thing that lets ranges register a callback for when the document changes. It's similar to nsIMutationObserver in Gecko.

**Comment by jdm** [comment]
That sounds confusingly named, in that case :)

**Comment by dzbarsky** [comment]
True it could use a different name. MutationWatcher or something.

**Comment by nox** [comment]
@dzbarsky Would #6660 help?

**Comment by dzbarsky** [comment]
I'm not sure how that PR helps here.  There's not really a great way for nodes to know that they're the start or end of some range.

**Comment by nox** [comment]
I made `Rc<RangeInner>` in Range because I intended to store a `Vec<Weak<RangeInner>>` in each node. I guess that's the wrong way to go at it?

**Comment by dzbarsky** [comment]
That's a lot of storage.  I think it's better to store that Vec on the document itself, that's basically what I'm doing in #6639

**Comment by nox** [comment]
With a Vec on the document itself, children_changed() could still be used in the VirtualMethods implementation of Node to update any range associated to the context object, couldn't it?

**Comment by dzbarsky** [comment]
I can see children_changed being used for some of the notifications, but I'm not sure how you'd handle some other cases.  For example, there are steps to run when calling CharacterData#replaceData, or Node#normalize.
But yes, I think it would be cleaner to just do the steps directly in insert and remove methods.

As for the MutationObserver thing...
In Gecko, other things than just range hook into nsIMutationObserver but perhaps we don't care about those for now.

One thing to keep in mind is that NodeIterator also defines "removing steps" (https://dom.spec.whatwg.org/#nodeiterator).
So we would also need to store a Vec of NodeIterators.  I was hoping to combine those but it looks like they need different notifications so it doesn't really make things any cleaner.

Having played around with it some I think the MutationObserver abstraction isn't necessary yet and just makes things more complicated for now so I'm tempted to drop it.

I'm going to try that one the other range patches land.

**Comment by nox** [comment]
I'm on the Range part.

**Comment by zbraniecki** [comment]
This depends on #4283

**Comment by jdm** [comment]
#1980 also covers this. We should close one of them.

**Comment by krishnakarthick1993** [comment]
Question regarding test cases : We have completed the initial steps and we are now moving to the subsequent steps.
I would like to know if we need any new test cases to be added to test our subsequent steps (or) is the previous test cases present in tests/wpt/web-platform-tests/dom/nodes good enough. Please let us know. Thanks.

**Comment by jdm** [comment]
I expect that the existing tests should provide enough coverage; my only worry is if they also require features that your project will not implement. It would be useful to create a simple test case that only uses the features that you are implementing in your project.

**Comment by srivassumit** [comment]
Hi,

I am implementing the subsequent steps of the Mutation Observer API as described here: https://github.com/servo/servo/wiki/Mutation-observer-project

I am stuck at the step 3 of the [notify mutation observers](https://dom.spec.whatwg.org/#notify-mutation-observers) algorithm. I am not sure how to get the "copy of unit of related similar-origin browsing contexts' signal slot list. "

This is what I have implemented in the impl MicrotaskQueue of microtask.rs file so far:

    ```
    /// https://dom.spec.whatwg.org/#notify-mutation-observers
    /// Notify Mutation Observers.
    pub fn notifyMutationObservers() {
    	SCRIPT_THREAD_ROOT.with(|root| {
            let script_thread = unsafe { &*root.get().unwrap() };
            // Step 1
            script_thread.mutation_observer_compound_microtask_queued.borrow_mut() = false;
            // Step 2
            let notifyList = script_thread.mutation_observers.borrow_mut();
            // Step 3
            let signalList = ""; // Stuck;
            // Step 4
            // ??
        });
    	
    }
```

Can you please point us in the right direction?

Thanks.

**Comment by jdm** [comment]
Servo doesn't implement anything related to slots, so you can leave `// TODO: step 3 (signal slot list)` there.

**Comment by srivassumit** [comment]
While implementing the [MutationObserver.observe](https://dom.spec.whatwg.org/#dom-mutationobserver-observe) method, In steps 3-6 it says that we need to throw a TypeError, but I could not find any specification for 'TypeError'.
I found 'TypeError' referenced in [addEventListener](https://dom.spec.whatwg.org/#dom-eventtarget-addeventlistener) and [removeEventListener](https://dom.spec.whatwg.org/#dom-eventtarget-removeeventlistener) methods of EventTarget specification, but in the eventtarget.rs file I could not find and TypeError being thrown.
can you please suggest which error needs to be thrown here and/or some file where it is already thrown so that I can use that as a reference?

**Comment by jdm** [comment]
Unfortunately we don't implement step 1 of those APIs in Servo yet, or that would have been a good idea! Throwing exceptions occurs automatically when returning an Err value from DOM APIs, but also requires that the WebIDL method be marked `[Throw]`. The result looks like this: https://dxr.mozilla.org/servo/rev/7f825d2119a480a64b103e1d60a2d469af98d3de/components/script/dom/crypto.rs#53

**Comment by gosavipooja** [comment]
Hi,

I am trying to implement the subsequent steps of the Mutation Observer API as described here: https://github.com/servo/servo/wiki/Mutation-observer-project.

I am a bit confused regarding - make changing/appending/removing/replacing an attribute queue a mutation record via Attr::set_value, Element::push_attribute, and Element::remove_first_matching_attribute.

In order to change or append or remove or replace an attribute, I am unsure if I need to modify the existing methods like setAttribute or removeAttribute as seen in the element.rs file? Or I need to implement any such related methods in some other file?

Can you please help me? Thanks!

**Comment by jdm** [comment]
The algorithms at https://dom.spec.whatwg.org/#concept-element-attributes-change all involve queuing a mutation record as the first step before actually modifying the element's attribute. You'll want to modify the existing methods to add that behaviour, since they are the fundamental building blocks that other APIs like setAttribute and removeAttribute are built upon. Does that make sense?

**Comment by krishnakarthick1993** [comment]
Hi Josh,

Since we have to implement queuing a mutation record algorithm " while ignoring the steps that do not relate to queueing a record for attribute mutations in particular".  

Does it mean I can ignore Step 4 of https://dom.spec.whatwg.org/#queue-a-mutation-record
since my function queue_a_muration_record takes only target: &Node and type: Mutation as arguments.

Please let us know. Thank you.

**Comment by jdm** [comment]
You will need steps 4.1, 4.2, and maybe 4.7, since they are relevant to mutation records for attribute mutations.

**Comment by krishnakarthick1993** [comment]
Since 4.2 says " if If name and namespace are given, set .." - This means that we should include name and namespace as well in the argument list of our queue_a_muration_record function.
It should take name, namespace apart from target and Mutation as arguments. Please correct me if I am wrong.

**Comment by jdm** [comment]
I believe the mutation record can contain an instance of the Mutation enum that I previously described, since it already contains those values if I recall correctly

**Comment by gosavipooja** [comment]
Hi,

While trying to queue a mutation record of "attributes" for element with name attribute’s local name, namespace attribute’s namespace, and oldValue attribute’s value, do I pass the local name, namespace and oldValue related to "attr: &Attr" or I need use functions like Attr::Value() or something else? 

Also, since I need to pass an enum which has for values - name, namespace, oldValue, newValue, what should I pass in the newValue? 

And, the name has the type called "Atom" in the enum and I couldn't figure out in attr.rs something that has got to do with 'Atom'. Can you please guide me?

**Comment by krishnakarthick1993** [comment]
Hello Josh,

I was trying to compile Step 1 of Queuing a mutation record i.e "Let interested observers be an initially empty set of MutationObserver objects optionally paired with a string".

The following is the code I wrote for the same:
```
let interestedObservers: Vec<MutationObserver> = vec![];
let pairedStrings: Vec<DOMString> = vec![];

```
On compilation, it shows error: Expression of type std::vec::Vec<dom::mutationobserver::MutationObserver> must be rooted.

I tried to use let interestedObservers: Vec<MutationObserver> =Rooted::new_unrooted();  by like how it is done in components/script/dom/webglrenderingcontext.rs and tried to use let interestedObservers: RootableVec<MutationObserver> =vec![]; by including appropriate bindings. Both of them failed in compilation.

Please let us know on how to root interestedObservers and pairedStrings.

Thanks,
Krishna

**Comment by jdm** [comment]
For the vector, you want `Vec<Root<MutationObserver>>`. I'll answer the previous question when I'm in front of a computer.

**Comment by jdm** [comment]
@gosavipooja An [Atom](http://doc.servo.org/string_cache/atom/struct.Atom.html) value is effectively a [hashed string](https://en.wikipedia.org/wiki/String_interning). You can turn any string into an Atom value via `Atom::from(str)`. The queued mutation record will want to use string representations of the attribute's name, namespace, and value. The new value will be whichever value is replacing the existing one; for example, from `Attr::set_value` the argument `value` is the new value that is being set. Does that answer your questions?

**Comment by srivassumit** [comment]
Hi Josh,

I am facing some problems understanding mutability in rust.

While implementing the MutationObserver.observe method, I am trying to assign the value true to the options.attributes but It says that I cannot "mutably borrow immutable field":
```
error: cannot assign to immutable field
  --> /home/sumit/Dropbox/NCSU/OODD/FinalProject/servo/components/script/dom/mutationobserver.rs:87:13
   |
87 |             options.borrow_mut().attributes = Some(true);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot mutably borrow immutable field

error: cannot borrow immutable argument `options` as mutable
```
Also, for setting the mutation_observer_compound_microtask_queued flag in script_thread.rs, I have created the following method in script_thread (I will be calling this from the mutation_observer.rs to set the valueof the flag in script_thread):

```
pub fn set_mutation_observer_compound_microtask_queued(value: bool) {
    SCRIPT_THREAD_ROOT.with(|root| {
        let mut script_thread = unsafe { &*root.get().unwrap() };
        script_thread.mutation_observer_compound_microtask_queued = value;
    })
}
```
But, it gives the following error:

```
error: cannot assign to immutable field `script_thread.mutation_observer_compound_microtask_queued`
   --> /home/sumit/Dropbox/NCSU/OODD/FinalProject/servo/components/script/script_thread.rs:583:13
    |
583 |             script_thread.mutation_observer_compound_microtask_queued = value;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot mutably borrow immutable field
```
Can you please help me figure out how to change these immutable values?

**Comment by KiChjang** [comment]
I suspect that in both cases, you have a __mutable reference__ to an __immutable value__. Take your `ScriptThread` code for example:

```rust
pub fn set_mutation_observer_compound_microtask_queued(value: bool) {
    SCRIPT_THREAD_ROOT.with(|root| {
        let mut script_thread = unsafe { &*root.get().unwrap() };
        script_thread.mutation_observer_compound_microtask_queued = value;
    })
}
```

Note that the type of `script_thread` is `&ScriptThread`. When you add a `mut` keyword in your let binding, this simply means you're free to change which `ScriptThread` you're referencing, but you're not free to mutate the field members of the referenced `ScriptThread`.

The simple fix here would just be to change the type of `script_thread` to `&mut ScriptThread`:

```rust
pub fn set_mutation_observer_compound_microtask_queued(value: bool) {
    SCRIPT_THREAD_ROOT.with(|root| {
        let mut script_thread = unsafe { &mut *root.get().unwrap() };
        script_thread.mutation_observer_compound_microtask_queued = value;
    })
}
```

**Comment by srivassumit** [comment]
I tried making it mutable in both the cases, but it says
for script_thread, I cannot borrow it as mutable:

```
error: cannot borrow immutable dereference of raw pointer as mutable
   --> /home/sumit/Dropbox/NCSU/OODD/FinalProject/servo/components/script/script_thread.rs:582:51
    |
582 |             let mut script_thread = unsafe { &mut *root.get().unwrap() };
    |                                                   ^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
``` 

and in case of the observe method, If it change it to Mutable, it says that it expects it to be non mutable in the Method signature as defined in the trait:

```
error[E0053]: method `Observe` has an incompatible type for trait
   --> /home/sumit/Dropbox/NCSU/OODD/FinalProject/servo/components/script/dom/mutationobserver.rs:83:47
    |
83  |     fn Observe(&self, target: &Node, options: &mut MutationObserverInit) -> Fallible<()> {
    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
    | 
   ::: /home/sumit/Dropbox/NCSU/OODD/FinalProject/servo/target/debug/build/script-9cf1e34119ea7ecd/out/Bindings/MutationObserverBinding.rs
    |
928 |     fn Observe(&self, target: &Node, options: &dom::bindings::codegen::Bindings::MutationObserverBinding::MutationObserverInit) -> Fallible<()>;
    |                                               -------------------------------------------------------------------------------- type in trait
    |
    = note: expected type `fn(&dom::mutationobserver::MutationObserver, &dom::node::Node, &dom::bindings::codegen::Bindings::MutationObserverBinding::MutationObserverInit) -> core::result::Result<(), dom::bindings::error::Error>`
               found type `fn(&dom::mutationobserver::MutationObserver, &dom::node::Node, &mut dom::bindings::codegen::Bindings::MutationObserverBinding::MutationObserverInit) -> core::result::Result<(), dom::bindings::error::Error>`
```

**Comment by gosavipooja** [comment]
Hi Josh,
While trying to use the  Atom::From::from, it is somehow unable to identify a trait. Where will I find traits used for this? Also, for the newValue, initially while queuing the MutationRecord, will I still have the newValue with me? It wouldn't be defined right? 
Few of the errors thrown were -

`let name = Atom::From::from(attr.name());
     |                    ^^^^^^^^^^^^^^^^ ambiguous associated type
`
`as Trait>::From::from(attr.name());
     |                                                                             ^^^^^^^^^^^^^^^^^^ Use of undeclared type or module `Trait`
`
Also, I went through the next few steps and tried to understand them. 
1.The state of the element will be determined from the 'state' in the element is what I figured out. While obtaining the custom element definition, do I need to implement the steps mentioned in https://html.spec.whatwg.org/multipage/scripting.html#look-up-a-custom-element-definition ? 
2.The variables mentioned in those steps like document and registry are not defined in Element.rs or attr.rs or mutationobserver.rs . Do I need to explore few others for the same? Same with the lifecycle callback which should be a part of the definition. 
3.And I need to enqueue this data in the same queue as the one in queue_a_mutation_record?

**Comment by KiChjang** [comment]
@srivassumit Oh, tough luck. `SCRIPT_THREAD_ROOT` contains a `*const ScriptThread` pointer, so you definitely cannot borrow it as mutable. We will need to use [`std::cell::Cell`](https://doc.rust-lang.org/stable/std/cell/struct.Cell.html) to represent `mutation_observer_compound_microtask_queued`.

In other words, the field type of `mutation_observer_compound_microtask_queued` should be changed from being just a `bool` to a `Cell<bool>` instead. Then you will be able to do the following:

```rust
pub fn set_mutation_observer_compound_microtask_queued(value: bool) {
    SCRIPT_THREAD_ROOT.with(|root| {
        let script_thread = unsafe { &*root.get().unwrap() };
        script_thread.mutation_observer_compound_microtask_queued.set(value);
    })
}
```

**Comment by KiChjang** [comment]
@srivassumit For your observe method, I'm actually quite surprised that you need to mutate the `MutationObserverInit` parameter. Could you show more context in what you're trying to do?

**Comment by srivassumit** [comment]
@KiChjang For the Observe Method this is my code:

```
/// https://dom.spec.whatwg.org/#dom-mutationobserver-observe
    /// MutationObserver.observe method
    fn Observe(&self, target: &Node, options: &MutationObserverInit) -> Fallible<()> {
        // Step 1: If either options’ attributeOldValue or attributeFilter is present and
        // options’ attributes is omitted, set options’ attributes to true.
        if (options.attributeOldValue.is_some() || options.attributeFilter.is_some()) && options.attributes.is_none() {
            options.borrow_mut().attributes = Some(true);
        }
        // Step2: If options’ characterDataOldValue is present and options’ characterData is omitted,
        // set options’ characterData to true.
        if options.characterDataOldValue.is_some() && options.characterData.is_some() {
            options.borrow_mut().characterData = Some(true);
        }
        // Step3: If none of options’ childList, attributes, and characterData is true, throw a TypeError.
        if !options.childList && !options.attributes.unwrap() && !options.characterData.unwrap() {
            return Err(Error::Type("childList, attributes, and characterData not true".to_owned()));
        }
        // Step4: If options’ attributeOldValue is true and options’ attributes is false, throw a TypeError.
        if options.attributeOldValue.unwrap() && !options.attributes.unwrap() {
            return Err(Error::Type("attributeOldValue is true but attributes is false".to_owned()));
        }
        // Step5: If options’ attributeFilter is present and options’ attributes is false, throw a TypeError.
        if options.attributeFilter.is_some() && !options.attributes.unwrap() {
            return Err(Error::Type("attributeFilter is present but attributes is false".to_owned()));
        }
        // Step6: If options’ characterDataOldValue is true and options’ characterData is false, throw a TypeError.
        if options.characterDataOldValue.unwrap() && !options.characterData.unwrap() {
            return Err(Error::Type("characterDataOldValue is true but characterData is false".to_owned()));
        }
        // TODO: Step 7
        // TODO: Step 8
        Ok(())
    }
```

the same error is there for both of the following lines:
`options.borrow_mut().attributes = Some(true);`
and 
`options.borrow_mut().characterData = Some(true);`

I was trying to set the value for attributes using this first:
`options.attributes = Some(true)`
but it gave error "cannot mutably borrow immutable field" so I tried using borrow_mut() instead.

**Comment by KiChjang** [comment]
Unfortunately, you cannot mutate the value of `options` at all. The best you can do here is to create a new `MutationObserverInit` struct and have it inherit all the field members of `options`. As for step 1 and 2, you may have to create let bindings to store those variables that the spec says to set.

**Comment by gosavipooja** [comment]
Hi,

In the step 7 and 8 of MutationObserver's observe, 

> For each registered observer registered in target’s list of registered observers whose observer is the context object:
>     Remove all transient registered observers whose source is registered.
>     Replace registered’s options with options. 

So, here, the list of registered observers will be : 
`mutation_observers: DOMRefCell<Vec<JS<MutationObserver>>>,`

How do I determine the transient registered observer. As per my understanding, I need to check if the source of the 'registered observer' exists in this vector. But how do I obtain the source? Correct me if I am wrong.

Thanks!

**Comment by jdm** [comment]
The link in the spec for [registered observer](https://dom.spec.whatwg.org/#registered-observer) points out that a registered observer's observer is just the `MutationObserver` object, so you don't need to do anything special besides this comparison: `&*observer as *const MutationObserver == self as * const MutationObserver`.

As for the transient observers, just leave a TODO like `// TODO: remove matching transient registered observers`. They require additional handling that is not relevant to this project's work right now.

**Comment by gosavipooja** [comment]
Hi,

I have some doubts in the usage of traits. I have encountered issues related to it at 2 places - 
`error: expected expression, found keyword `as`
     let name = Atom<<servo_atoms::AtomStaticSet> as Trait>::From::from(attr.local_name().to_string());`
and in this as well :
`for registered in &target.registered_mutation_observers_for_type() {
           if &*registered as *const MutationObserver == self as *const MutationObserver{
          //TODO: 
         }
  the trait `core::iter::Iterator` is not implemented for `&&dom::bindings::cell::DOMRefCell<std::vec::Vec<dom::bindings::js::JS<dom::mutationobserver::MutationObserver>>>``

Can you point me in the right direction w.r.t traits?

Thanks!

**Comment by jdm** [comment]
For the second, you want:
`for registered in target.registered_mutation_observers_for_type().borrow().iter()`, since you can't iterate over the DOMRefCell that encapsulates the actual vector. For the first, I think you might have been misled by some error messages? Try `Atom::from(attr.local_name().to_string())` instead.

**Comment by krishnakarthick1993** [comment]
Hello Josh, I am trying to iterate over  node’s list of registered observers ( for Step 3 of Queuing a mutation record) .

The following is my code:
pub fn queue_a_mutation_record(target: &Node,attr_type: Mutation) {
    //https://dom.spec.whatwg.org/#queueing-a-mutation-record
    // Step 1 :Let interested observers be an initially empty set of MutationObserver objects optionally paired with a string
    let mut interestedObservers: Vec<Root<MutationObserver>> = vec![];
    let mut pairedStrings: Vec<DOMString> = vec![];
    // Step 2: Let nodes be the inclusive ancestors of target.
    let mut nodes: Vec<Root<Node>> = vec![];
    for ancestor in target.inclusive_ancestors() {
        nodes.push(ancestor);
    }
    // Step 3: For each node in nodes
    for node in &nodes {
        for registered_observer in node.registered_mutation_observers_for_type().borrow_mut().iter() {
        }
    }
}

I tried using the above approach by using `for registered in node.registered_mutation_observers_for_type().borrow().iter()` like `for registered in target.registered_mutation_observers_for_type().borrow().iter()`

On compilation, I get the following error
error: cannot borrow immutable borrowed content as mutable
  --> /home/kbalaji/Moz/servo/components/script/dom/mutationobserver.rs:45:36
   |
45 |         for registered_observer in node.registered_mutation_observers_for_type().borrow().iter() {
   |                                    ^^^^ cannot borrow as mutable

Even on replacing node with target ( just to check if target works) by replacing line `for registered_observer in node.registered_mutation_observers_for_type().borrow_mut().iter() {` with 
`for registered_observer in target.registered_mutation_observers_for_type().borrow_mut().iter() {`

Compiler shows the following error:
error: cannot borrow immutable borrowed content `*target` as mutable
  --> /home/kbalaji/Moz/servo/components/script/dom/mutationobserver.rs:45:36
   |
33 | pub fn queue_a_mutation_record(target: &Node,attr_type: Mutation) {
   |                                        ----- use `&mut Node` here to make mutable
...
45 |         for registered_observer in target.registered_mutation_observers_for_type().borrow_mut().iter() {
   |                                    ^^^^^^ cannot borrow as mutable
.

Please let us know on how to approach this problem. Thank you.

**Comment by jdm** [comment]
You wrote `borrow_mut()`, not `borrow()`.

**Comment by jdm** [comment]
Although it sounds like maybe your `registered_mutation_observers_for_type()` method is `&mut self` instead of `&self`? It's hard to be sure without being able to see the actual code you have.

**Comment by gosavipooja** [comment]
Hi,

Is there any way to access the registered's options (MutationObserverInit) via the MutationObserver object? I thought I will need it for this step - 
> Replace registered’s options with options. 

Thanks!

**Comment by jdm** [comment]
I recommend adding members to MutationObserver that you initialize to the values present in the MutationObserverInit argument in the constructor.

**Comment by jdm** [comment]
(they will need to be wrapped in Cell or DOMRefCell types to allow mutating them later)

**Comment by gosavipooja** [comment]
Hi,

There is no MutationObserverInit argument in the constructor currently and if we add it, it shoots an error in the Bindings file: 
```
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
    --> servo/target/debug/build/script-9cf1e34119ea7ecd/out/Bindings/MutationObserverBinding.rs:1002:91
     |
1002 |           let result: Result<Root<MutationObserver>, Error> = MutationObserver::Constructor(&global, arg0);
     |                                                                                             ^^^^^^^^^^^^^ expected 3 parameters
     | 
    ::: /home/sumit/Dropbox/NCSU/OODD/FinalProject/servo/components/script/dom/mutationobserver.rs
     |
53   | /     pub fn Constructor(global: &Window, callback: Rc<MutationCallback>, options: DOMRefCell<MutationObserverInit>) -> Fallible<Root<MutationObserver>> {
54   | |         let observer = MutationObserver::new(global, callback);
55   | |         ScriptThread::add_mutation_observer(&*observer);
56   | |         Ok(observer)
57   | |     }
     | |___- defined here
```
Should we create another overridden constructor which also has MutationObserverInit argument? Or what way should we follow?
Thanks!

**Comment by krishnakarthick1993** [comment]
Hi Josh,
I am  trying to implement Step 4.2 of Queuing a mutation record (If name and namespace are given, set record’s attributeName to name, and record’s attributeNamespace to namespace.)

My enum is
```rust
pub enum Mutation {
    Attribute { name: Atom, namespace: Namespace, oldValue: DOMString, newValue: DOMString}
}
```
Since I need name and namespace of Attribute of Mutation enum which is passed as an argument to my function , I tried using the match function like (http://rustbyexample.com/custom_types/enum.html)

My function is
```rust
    //Queuing a mutation record
    pub fn queue_a_mutation_record(target: &Node, attr_type: Mutation) {
        // Step 1
        let mut interestedObservers: Vec<Root<MutationObserver>> = vec![];
        let mut pairedStrings: Vec<DOMString> = vec![];
        // Step 2
        let mut nodes: Vec<Root<Node>> = vec![];
        for ancestor in target.inclusive_ancestors() {
            nodes.push(ancestor);
        }
        // Step 3
        for node in &nodes {
            for registered_observer in node.registered_mutation_observers_for_type().borrow().iter() {
               //let bool condition1 = (node!=target);
            }
        }
        // Step 4
        for observer in &interestedObservers {
            //Step 4.1
            let mut record= MutationRecord::new(target);
            //Step 4.2
            match attr_type {
                 Mutation::Attribute {name,namespace,oldValue,newValue} => { let mut given_name = name;let mut given_namespace = namespace;
               },
            }

        }
        }
```

On compilation I get 
```
error[E0382]: use of partially moved value: `attr_type`
   --> /home/kbalaji/Moz/servo/components/script/dom/mutationobserver.rs:103:19
    |
103 |             match attr_type {
    |                   ^^^^^^^^^ value used here after move
104 |                Mutation::Attribute {name,namespace,oldValue,newValue} => { let mut given_name = name;let mut given_namespace = namespace;
    |                                     ---- value moved here
    |
    = note: move occurs because `attr_type.name` has type `string_cache::atom::Atom<servo_atoms::AtomStaticSet>`, which does not implement the `Copy` trait

error[E0382]: use of moved value: `attr_type.name`
   --> /home/kbalaji/Moz/servo/components/script/dom/mutationobserver.rs:104:37
    |
104 |                Mutation::Attribute {name,namespace,oldValue,newValue} => { let mut given_name = name;let mut given_namespace = namespace;
    |                                     ^^^^ value moved here in previous iteration of loop
    |
    = note: move occurs because `attr_type.name` has type `string_cache::atom::Atom<servo_atoms::AtomStaticSet>`, which does not implement the `Copy` trait
```
(similar errors for namespace,oldValue and newValue).

I tried including #[derive(Clone,Copy)] before my mutation and the following code 
```rust
impl Copy for Mutation {}
impl Clone for Mutation { fn clone(&self) -> Self { *self } }
```
Compiler still throws 
```
error[E0119]: conflicting implementations of trait `core::marker::Copy` for type `dom::mutationobserver::Mutation`:
  --> /home/kbalaji/Moz/servo/components/script/dom/mutationobserver.rs:35:1
   |
31 | #[derive(Clone,Copy)]
   |                ---- first implementation here
...
35 | impl Copy for Mutation {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `dom::mutationobserver::Mutation`

error[E0204]: the trait `Copy` may not be implemented for this type
  --> /home/kbalaji/Moz/servo/components/script/dom/mutationobserver.rs:31:16
   |
31 | #[derive(Clone,Copy)]
   |                ^^^^
32 | pub enum Mutation {
33 |     Attribute { name: Atom, namespace: Namespace, oldValue: DOMString, newValue: DOMString}
   |                 ---------- this field does not implement `Copy`

error[E0204]: the trait `Copy` may not be implemented for this type
  --> /home/kbalaji/Moz/servo/components/script/dom/mutationobserver.rs:35:6
   |
33 |     Attribute { name: Atom, namespace: Namespace, oldValue: DOMString, newValue: DOMString}
   |                 ---------- this field does not implement `Copy`
34 | }
35 | impl Copy for Mutation {}
   |      ^^^^

error[E0119]: conflicting implementations of trait `core::clone::Clone` for type `dom::mutationobserver::Mutation`:
  --> /home/kbalaji/Moz/servo/components/script/dom/mutationobserver.rs:36:1
   |
31 | #[derive(Clone,Copy)]
   |          ----- first implementation here
...
36 | impl Clone for Mutation { fn clone(&self) -> Self { *self } }
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `dom::mutationobserver::Mutation`
```
Please let us know on how to reference name and namespace of attr_type ( function argument).
Thank you.

**Comment by KiChjang** [comment]
I'm very confused why you have
```rust
pub enum Mutation {
    Attribute { name: Atom, namespace: Namespace, oldValue: DOMString, newValue: DOMString}
}
```
Can `Attribute` not be a struct of its own?

**Comment by krishnakarthick1993** [comment]
Hi,
Separately, I am not clear on what "type" means in "To queue a mutation record of **type** for target with one or more of (depends on **type**) " .

In Step 3 of Queuing a mutation record , type is supposed to be compared with "attributes", "characterData" and "childList". 
Does type refer to record_type of a mutation record object ?. If so , should I pass a mutation record object as well as an argument to my function queue_a_mutation_record along with target and enum.
Please let us know. Thank you.

**Comment by jdm** [comment]
The "type" in the spec is equivalent to matching against the enum that we're using. To avoid the errors about partially moved values, you will want to use `ref` binding in the matches, and clone those values like `let mut given_name = name.clone()`.

**Comment by jdm** [comment]
As for the question about MutationObserverInit, my mistake. I guess you will want sensible defaults for the new members in the constructor, and then set them to the real values in MutationObserver::Observe.

**Comment by Xanewok** [comment]
@jdm just want to make sure what's the status of this issue - it seems that effectively almost all of the listed work in https://github.com/servo/servo/wiki/Mutation-observer-project is done (I tried to go over them and [mark done items](https://gist.github.com/Xanewok/50017531ab81bcb69acd80d7c7193efa), excuse the crude format), mostly by #16883?

It seems that what's left is:
* to implement [`void disconnect()`](https://github.com/servo/servo/blob/1282e0d8080ae15307ac8d35941754f9d60f0d76/components/script/dom/webidls/MutationObserver.webidl#L14), [`sequence<MutationRecord> takeRecords()`](https://github.com/servo/servo/blob/1282e0d8080ae15307ac8d35941754f9d60f0d76/components/script/dom/webidls/MutationObserver.webidl#L15)
* remove transient observers ([here](https://github.com/servo/servo/blob/1282e0d8080ae15307ac8d35941754f9d60f0d76/components/script/dom/mutationobserver.rs#L98) and [here](https://github.com/servo/servo/blob/1282e0d8080ae15307ac8d35941754f9d60f0d76/components/script/dom/mutationobserver.rs#L233))
* implement [signal slots](https://github.com/servo/servo/blob/1282e0d8080ae15307ac8d35941754f9d60f0d76/components/script/dom/mutationobserver.rs#L93)?

Asking because we planned to take this on as a team as a part of our university thesis project
cc @mrowqa @marmistrz

**Comment by marmistrz** [comment]
cc @taki-jaro

**Comment by jdm** [comment]
@Xanewok Signal slots are part of a standard that we don't implement, so those can be ignored. We're also missing character data notifications, and all of the [failing tests](https://github.com/servo/servo/tree/1282e0d8080ae15307ac8d35941754f9d60f0d76/tests/wpt/metadata/dom/nodes) that are named MutationObserver.

**Comment by jdm** [comment]
We have implemented mutation observers. If anything is missing or not working, we should open new issues for those items.
