### ISSUE TITLE
`list-style-image` grabs width/height attributes off the element

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6649]
That shouldn't happen. The issue is in (using) `ImageFragmentInfo::new()`.

``` html
<!DOCTYPE html>
<style>
li {
  list-style-image: url("list.png")
}
</style>
<ol>
  <li>AAA<br>AAA<br>AAA
  <li width=50 height=50>BBB<br>BBB<br>BBB
</ol>
```

**Comment by pwnorbitals** [comment]
Is this still the case on latest releases ?

**Comment by jdm** [comment]
Given:
* https://github.com/servo/servo/blob/d42fbfb315ae82875c1d8536ba8058271638d85b/components/layout/construct.rs#L1510
* https://github.com/servo/servo/blob/d42fbfb315ae82875c1d8536ba8058271638d85b/components/layout/fragment.rs#L416-L479
* https://github.com/servo/servo/blob/d42fbfb315ae82875c1d8536ba8058271638d85b/components/script/dom/node.rs#L1551-L1553

It appears the answer is no.
