### ISSUE TITLE
Optimise Node.normalize()

### ISSUE THREAD

**Issue by nox** [servo/servo#6658]
When multiple consecutive text nodes are merged together, the contents of the discarded nodes are copied instead of borrowed when they are appended to the first Text. This should create and make use of new methods in CharacterDataMethods to avoid unnecessary allocations.

**Comment by jdm** [comment]
Presumably you mean CharacterDataHelpers, rather than CharacterDataMethods?

**Comment by nox** [comment]
Yes, yes I do.

**Comment by felipesere** [comment]
How would test for this look like? Sorry if it sounds obvious, its the first time I'm trying to contribute to Servo.

**Comment by nox** [comment]
```
./mach test-wpt /dom/nodes/Node-normalize.html
```

**Comment by notriddle** [comment]
Is @felipesere taking this one?

**Comment by felipesere** [comment]
I'd like to try :smile: 
If you want to take it @notriddle, go for it! I'll look at the PR.
