### ISSUE TITLE
Make virtual methods take self

### ISSUE THREAD

**Issue by nox** [servo/servo#6659]
The methods in the trait VirtualMethods take &self and are implemented on &T. This is useless and inconsistent with the other *Methods and *Helpers traits. All the methods should be changed to take self instead of &self.

**Comment by nox** [comment]
Apparently it can't be done this way because VirtualMethods comes from default implementations. Can someone confirm?

**Comment by jdm** [comment]
I don't recall the reason precisely, but it certainly did not appear possible when we introduced the trait.

**Comment by mukilan** [comment]
[Confirmation](https://play.rust-lang.org/?gist=675b1f3510dafebfb9dc&version=nightly).  As you can see, having a default method that takes ```self``` requires the ```Sized``` bound on the trait. But then the trait will be not be object-safe any more and no trait objects can be created.

**Comment by nox** [comment]
@mukilan Thanks.
