### ISSUE TITLE
ParentNode-querySelector-All WPT test not working?

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#6663]
Sorry for the brevity of this Issue, I am currently on mobile. From IRC:

```
03:00	frewsxcv	is anyone familiar with tests/wpt/web-platform-tests/dom/nodes/selectors.js? it appears to be used by tests/wpt/web-platform-tests/dom/nodes/ParentNode-querySelector-All.html but if I try to intentionally make selectors.js fail, ParentNode-querySelector-All.html still passes, so I'm a little confused by that. If anyone has ideas, let me know
03:35	jdm	frewsxcv: used how?
03:35	* jdm doesn't see it in http://mxr.mozilla.org/servo/sourc...de_querySelectorAll.html?force=1
03:35	jdm	oh, whoops wrong fiel
03:35	frewsxcv	See what?
03:36	jdm	frewsxcv: what are you changing that should make it fail?
03:36	frewsxcv	It's selectors.js is included in that html test
03:36	frewsxcv	Just making a valid selector invalid
03:38	jdm	hmm
03:38	jdm	we don't have an ini file for that test, so in theory it should be entirely passing right now
03:38	jdm	so that's strange
03:43	frewsxcv	Yeah, I doubt it entirely passes
03:43	frewsxcv	Because :empty hasn't merged yet
03:50	jdm	frewsxcv: hmm, it completes in .5 seconds with 1/1 subtests passed according to http://build.servo.org/builders/m...s/2561/steps/shell_2/logs/stdio
03:50	jdm	waffles: go for it!
03:51	frewsxcv	Indicating it is probably not working correctly, right?
03:51	frewsxcv	Maybe we should open an issue?
03:51	jdm	frewsxcv: mhm
03:51	jdm	yes please
```

**Comment by jdm** [comment]
Aha, the test loads an iframe and all of the expected tests run off of the iframe load event. However, the main document load event never fires, so the overall test is never considered finished, yet that doesn't get treated as a timeout for some reason.

**Comment by Ms2ger** [comment]
CC @jgraham

**Comment by Ms2ger** [comment]
https://github.com/w3c/web-platform-tests/pull/2019

**Comment by frewsxcv** [comment]
w3c/web-platform-tests#2019 merged. Maybe time for a WPT upgrade

**Comment by Ms2ger** [comment]
I can do that, but that won't really help; it'll just make that test be recognized as timing out.

**Comment by jdm** [comment]
The way to fix the timeout here is probably to add a methods to document_loader.rs that pushes a new element to blocking_loads without setting up any new request, and call that and finish_load from http://mxr.mozilla.org/servo/source/components/script/dom/htmliframeelement.rs#125 and http://mxr.mozilla.org/servo/source/components/script/dom/document.rs#1891 respectively.

**Comment by jdm** [comment]
Yeah, my mistake: the load event does fire, but it fires before everything else hence why the test "finishes" so quickly.
