### ISSUE TITLE
Exclude minified JS files from `./mach grep` 

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#6670]
`etc/layout_viewer/js` contains some `*.min.js` files with very long lines. Since `grep` shows matching line entirely, any match in those files make the rest of the output difficult to read. Try `./mach grep offsetTop` for example. It’d be nice to exclude minified files from `./mach grep`.

`./mach grep` is based on `git grep` which unfortunately does not a parameter like `--exclude` in GNU grep. So I don’t know how to do this, but ideas are welcome.

CC @dhananjay92, @Manishearth

**Comment by boghison** [comment]
[This](http://stackoverflow.com/a/10423194/4743424) seems like a reasonable workaround.

**Comment by SimonSapin** [comment]
Listing these files in `.gitignore` would also cause them to be ignored for the purpose of `git commit`. That seems undesirable?

**Comment by boghison** [comment]
Can't we just remove the line afterwards? :)

**Comment by Manishearth** [comment]
We could use `grep -Hrn` with `--exclude` and prefill `--exclude` with the submodules/support/target dirs

**Comment by dhananjay92** [comment]
Sorry, was busy with my internship. So couldn't reply! 
I will try out @Manishearth's suggestion (passing `-Hrn --exclude`).

**Comment by dhananjay92** [comment]
I found a simpler way. See commit-[964cd3](https://github.com/dhananjay92/servo/commit/964cd3). It works only for git >= 1.9. Should I send a pull for it?

Do we want to exclude some other generated files too?

**Comment by Manishearth** [comment]
Exclude minified JS, and everything in `tests/wpt` (perhaps all of `tests/`?) I guess.

**Comment by dhananjay92** [comment]
I think in the original issue#[5838](https://github.com/servo/servo/issues/5838#issuecomment-96238528) we wanted to include everything in `tests` except `test/wpt`. Can you confirm that it has changed now? I am just making sure, I understand the requirements correctly. :smile:

**Comment by Manishearth** [comment]
Everything in `tests/` except for `wpt` and `jquery` sounds good  to me.

**Comment by frewsxcv** [comment]
Completed in #7394
