### ISSUE TITLE
Cross origin iframes don't trigger a load event in the parent frame element

### ISSUE THREAD

**Issue by jdm** [servo/servo#6672]
This happens because BrowsingContext::frame_element called by Document::dispatch_load can't handle cross-origin parent frames.

Probably requires #5242.

**Comment by jdm** [comment]
```
<iframe src="http://www.joshmatthews.net"></iframe>
<script>
document.addEventListener('load', function() { console.log("load") }, true);
document.getElementsByTagName('iframe')[0].addEventListener('load', function() { console.log("frame load") }, true);
</script>
```

**Comment by Ms2ger** [comment]
Technically, this is allowed by the spec:
> This, in conjunction with scripting, can be used to probe the URL space of the local network's HTTP servers. User agents may implement cross-origin access control policies that are stricter than those described above to mitigate this attack, but unfortunately such policies are typically not compatible with existing Web content.
