### ISSUE TITLE
Add a JS-accessible method on Window that triggers a breakpoint trap

### ISSUE THREAD

**Issue by jdm** [servo/servo#6673]
This should go in a `partial interface` declaration in Window.webidl, and just be a call to http://doc.servo.org/util/fn.breakpoint.html . This is useful for adding inside JS in a test or a local page for quick and easy debugging in gdb.

Code: components/script/dom/window.rs, components/script/dom/webidls/Window.webidl

**Comment by saneyuki** [comment]
@jdm what name is suitable? `Window.setBreakpoint`?

**Comment by jdm** [comment]
I like window.trap.

**Comment by saneyuki** [comment]
okay, I'll take this as rehabilitation working.
