### ISSUE TITLE
MutHeap/MutNullableHeap should return safe, rooted values

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#6684]
`MutHeap<JS<T>>`, for example, returns a `JS<T>`, which isn't safe. We should be returning a `Root<T>`

This can be achieved by adding a `SafeOutput` associated type to `HeapGCValue`, however some special casing needs to be done for `MutHeap<Heap<JSVal>>` to work. (We also need to figure out what a "safe" value is for `JSVal`)

Follow up for #6651

**Comment by eefriedman** [comment]
Fixed in #8026.
