### ISSUE TITLE
Split actual document object out of content frame tree

### ISSUE THREAD

**Issue by jdm** [servo/servo#6687]
I've been thinking of doing this as part of #5236, but it's been pointed out that `Frame` contains JS pointers, and `Page` contains `Frame`, and we use `Rc<Page>` objects all over the place without any stack roots.

I propose moving all JS pointers into a hashmap in ScriptTask keyed on the PipelineId, and have the content tree just bee a tree of PipelineId values instead.

**Comment by Manishearth** [comment]
cc moi

**Comment by jdm** [comment]
This happened long ago.
