### ISSUE TITLE
Panic in http_loader using -x flag

### ISSUE THREAD

**Issue by connorimes** [servo/servo#6697]
PR #6666 fixed issue #6587, but on some pages there is a panic.  This example uses http://www.google.com.  Some pages like http://www.example.com do not panic.

CC @glennw 

<pre>
#0  0x0000555558231f80 in rust_panic ()
#1  0x000055555821f81e in rt::unwind::begin_unwind_inner::h0544b2c664549c40gQw
    ()
#2  0x000055555822017d in rt::unwind::begin_unwind_fmt::h5a900a56c2bf32ccmPw ()
#3  0x0000555558232017 in rust_begin_unwind ()
#4  0x0000555558264235 in panicking::panic_fmt::h205f328075c6fc3cneC ()
#5  0x000055555690bbaf in script::result::Result<T, E>::unwrap (self=...)
    at src/libcore/result.rs:28
#6  0x0000555556f5f97e in script::network_listener::NetworkListener<T>.AsyncResponseTarget::invoke_with_listener (self=0x7fffee82cd00, action=...)
    at /local/servo/components/script/network_listener.rs:18
#7  0x000055555644c2da in net::resource_task::ProgressSender::send (
    self=0x7fffc1bf50e0, msg=...)
    at /local/servo/components/net/resource_task.rs:76
#8  0x0000555556500273 in net::http_loader::send_data<hyper::client::response::Response> (reader=0x7fffc1bf8790, start_chan=..., metadata=..., classifier=...)
    at /local/servo/components/net/http_loader.rs:399
#9  0x00005555564aaf53 in net::http_loader::load (load_data=..., 
    start_chan=..., classifier=..., cookies_chan=..., devtools_chan=...)
    at /local/servo/components/net/http_loader.rs:373
#10 0x00005555564a3f25 in fnfn ()
    at /local/servo/components/net/http_loader.rs:40
#11 0x00005555564a3cdd in fnfn () at /local/servo/components/util/task.rs:16
#12 0x00005555564a3c05 in net::boxed::F.FnBox<A>::call_box (
    self=0x7fffed835280, args=0) at src/liballoc/boxed.rs:396
#13 0x0000555556452921 in net::boxed::Box<FnBox<A, Output = R>+ Send + 'a>.FnOnce<A>::call_once (self=..., args=0) at src/liballoc/boxed.rs:412
#14 0x00005555564523d3 in fnfn () at src/libstd/thread/mod.rs:349
#15 0x000055555645234f in net::rt::unwind::try::try_fn<closure> (
    opt_closure=0x7fffc1bfc9a0) at src/libstd/rt/unwind/mod.rs:158
#16 0x00005555564522ea in rt::unwind::try::try_fn::h4737620853587692877 ()
#17 0x00005555582375d9 in rust_try_inner ()
#18 0x00005555582375c6 in rust_try ()
#19 0x000055555822c9e8 in rt::unwind::try::inner_try::h63857c7efe7ef4ac9Lw ()
#20 0x0000555556452249 in net::rt::unwind::try<closure> (
    f={void (())} 0x7fffc1bfc9c0) at src/libstd/rt/unwind/mod.rs:130
#21 0x00005555564520a4 in fnfn () at src/libstd/thread/mod.rs:349
#22 0x0000555556452c9e in net::boxed::F.FnBox<A>::call_box (
    self=0x7fffee0364b0, args=0) at src/liballoc/boxed.rs:396
#23 0x0000555558231162 in sys::thread::Thread::new::thread_start::hb94dd6e8abd80527WVv ()
#24 0x00007ffff79ba6aa in start_thread (arg=0x7fffc1bfd700)
    at pthread_create.c:333
#25 0x00007ffff5432eed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
</pre>

**Comment by jdm** [comment]
This is a symptom of an ongoing network connection after the document load event fires. Our networking code is very unwrap happy when errors occur (such as the script task no longer existing).

**Comment by nox** [comment]
I'm pretty sure this was fixed a long time ago.
