### ISSUE TITLE
Process Strict-Transport-Security header in HTTPS responses

### ISSUE THREAD

**Issue by jdm** [servo/servo#6703]
There's support for the header in hyper, so we should go ahead and follow the spec at http://tools.ietf.org/html/rfc6797#section-8.1 . @samfoo was this something you were interested in tackling?

Relevant code: components/net/http_loader.rs

**Comment by samfoo** [comment]
Yep, I'll take this up over the weekend. The client API for hyper has changed pretty substantially (SSL is totally different), so it will likely be non-trivial.

**Comment by samfoo** [comment]
Yay! Someone already did the work of upgrading hyper, so this was easy. I'm very concerned about the lack of testing around the load function, but it seems like that's a much bigger problem than is worth tackling in this commit.

The other bit I'm not sure about is how to persist the HSTS list between runs. There's no `write_resource_file` counterpart, and I'm not even sure that would be the right way to do it. Is there another mechanism for persisting state across sessions right now?

**Comment by jdm** [comment]
There's no persistence mechanism in Servo for the time being. Just add a TODO.
