### ISSUE TITLE
FileList is not defined

### ISSUE THREAD

**Issue by boghison** [servo/servo#6708]

**Comment by jdm** [comment]
Spec: https://w3c.github.io/FileAPI/#dfn-filelist

Also relevant is https://html.spec.whatwg.org/multipage/forms.html#dom-input-files and https://html.spec.whatwg.org/multipage/forms.html#the-input-element:dom-input-files

**Comment by boghison** [comment]
@jdm Can I work on implementing this? :3

**Comment by jdm** [comment]
Sure!

**Comment by boghison** [comment]
@jdm I've implemented FileList, but did not edit the input element (because things like dialogs need to be created). Is this enough?

**Comment by jdm** [comment]
Yep.
