### ISSUE TITLE
thread 'LayoutWorker worker 3/3' panicked at 'Link to containing block not established; perhaps you forgot to call `set_absolute_descendants`?'

### ISSUE THREAD

**Issue by boghison** [servo/servo#6709]
Probably related to #6078.
stack backtrace:
   1:     0x7f33bcd02a4e - sys::backtrace::write::hfe027f56cae344aapps
   2:     0x7f33bcd06125 - panicking::on_panic::hcd0100c6199f27b1Cax
   3:     0x7f33bccf328e - rt::unwind::begin_unwind_inner::h0544b2c664549c40gQw
   4:     0x7f33ba6aff0c - rt::unwind::begin_unwind::h6058373089137628800
                        at src/libstd/rt/unwind/mod.rs:226
   5:     0x7f33ba760f23 - flow::ContainingBlockLink::generated_containing_block_size::h4e70c635b1e9d16cM0i
                        at /home/boghison/Projects/servo/components/servo/<std macros>:3
   6:     0x7f33ba760bab - block::BlockFlow::containing_block_size::h8272708aaf825308Ygb
                        at /home/boghison/Projects/servo/components/layout/block.rs:710
   7:     0x7f33ba78b585 - table_row::TableRowFlow.Flow::assign_inline_sizes::h29eda3847b19c01e3ru
                        at /home/boghison/Projects/servo/components/layout/block.rs:1275
                        at /home/boghison/Projects/servo/components/layout/table_row.rs:377
   8:     0x7f33baa143d0 - traversal::AssignISizes<'a>.PreorderFlowTraversal::process::hf4c1222c61220ebe3xw
                        at /home/boghison/Projects/servo/components/layout/traversal.rs:347
   9:     0x7f33baa134f8 - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::h900de12c6edfcd44NLr
                        at /home/boghison/Projects/servo/components/layout/parallel.rs:314
                        at /home/boghison/Projects/servo/components/layout/parallel.rs:345
  10:     0x7f33baa19943 - parallel::assign_inline_sizes::hafc90b58a93f64e5HOr
                        at /home/boghison/Projects/servo/components/layout/parallel.rs:412
  11:     0x7f33ba8fa92d - workqueue::WorkerThread<QueueData, WorkData>::start::h16418421395268502212
                        at /home/boghison/Projects/servo/components/util/workqueue.rs:177
  12:     0x7f33ba8f9fb3 - workqueue::WorkQueue<QueueData, WorkData>::new::closure.42686
                        at /home/boghison/Projects/servo/components/util/workqueue.rs:280
  13:     0x7f33ba8f9df3 - task::spawn_named::closure.42680
                        at /home/boghison/Projects/servo/components/util/task.rs:16
  14:     0x7f33ba8f9ce0 - boxed::F.FnBox<A>::call_box::h8702928423805192753
                        at src/liballoc/boxed.rs:396
  15:     0x7f33ba8964a0 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h3927606606177635819
                        at src/liballoc/boxed.rs:412
  16:     0x7f33ba895f52 - thread::Builder::spawn_inner::closure.40750
                        at src/libstd/thread/mod.rs:349
  17:     0x7f33ba895ece - rt::unwind::try::try_fn::__rust_abi::h11895128796606423641
                        at src/libstd/rt/unwind/mod.rs:158
  18:     0x7f33ba895e69 - rt::unwind::try::try_fn::h11895128796606423641
  19:     0x7f33bcd0b0d8 - rust_try_inner
  20:     0x7f33bcd0b0c5 - rust_try
  21:     0x7f33bcd004e7 - rt::unwind::try::inner_try::h63857c7efe7ef4ac9Lw
  22:     0x7f33ba895dc8 - rt::unwind::try::h10233579225505780220
                        at src/libstd/rt/unwind/mod.rs:130
  23:     0x7f33ba895c23 - thread::Builder::spawn_inner::closure.40703
                        at src/libstd/thread/mod.rs:349
  24:     0x7f33ba8967ad - boxed::F.FnBox<A>::call_box::h10793031556886145188
                        at src/liballoc/boxed.rs:396
  25:     0x7f33bcd04c61 - sys::thread::Thread::new::thread_start::hb94dd6e8abd80527WVv
  26:     0x7f33b9a62353 - start_thread
  27:     0x7f33b8efabfc - __clone
  28:                0x0 - <unknown>

**Comment by jdm** [comment]
What site did you visit that triggered this?

**Comment by boghison** [comment]
@jdm http://boghison.github.io/pixelmusic
