### ISSUE TITLE
Implement the Web Audio API

### ISSUE THREAD

**Issue by boghison** [servo/servo#6710]
The spec is [here](http://webaudio.github.io/web-audio-api/). A Google search reveals these audio libraries written in Rust:
- [RustAudio](https://github.com/RustAudio)
- [oxcable](https://github.com/thenyeguy/oxcable)

or write one.

**Comment by jdm** [comment]
http://mxr.mozilla.org/mozilla-central/source/dom/media/webaudio/ is a good reference here for Firefox's implementation. I'm pretty sure we wrote an audio library for this purpose, too: http://mxr.mozilla.org/mozilla-central/source/media/libcubeb/

**Comment by SimonSapin** [comment]
People interested in this should definitely talk to @padenot, who works on Web Audio in Firefox.

**Comment by padenot** [comment]
The Web Audio API has little to do with cubeb, and RustAudio or oxcable are not going to be very useful to implement it (they implement similar effect, but having something that is spec-compliant is a completely different story, while having something that is not spec compliant is not very useful).

That said, it would be appropriate to use cubeb as a system abstraction for audio output (and in fact I've written a wrapper in rust that does that), but that's a tiny fraction of what needs to be doing.

If someone want to have a go at it, feel free to ask me anything you need, but I kind of feel that having HTMLMediaElement would be more logical in terms of priorities.

**Comment by frewsxcv** [comment]
Since it has not been explicitly stated yet, there are tests for the Web Audio API available in web-platform-tests:

https://github.com/w3c/web-platform-tests/tree/master/webaudio

**Comment by jdm** [comment]
Dropping https://github.com/servo/servo/compare/master...dmarcos:webaudio-kickoff here so I don't forget about it.

**Comment by Ms2ger** [comment]
@rocallahan:
> Before you run ahead and implement WebAudio, I suggest talking to Paul Adenot or me about your design. We learned a lot from our implementation.

**Comment by padenot** [comment]
Yes, please feel free to ping me anytime on irc if you want/need to chat about the matter.

**Comment by rtbo** [comment]
@nox, @padenot as briefly discussed in this [cult PR](https://github.com/padenot/cult/pull/2), I'd like to contribute to web audio implementation. 
Has there been some code written on the topic since [master...dmarcos:webaudio-kickoff](https://github.com/servo/servo/compare/master...dmarcos:webaudio-kickoff)? Is it available somewhere on github?

**Comment by jdm** [comment]
No, but @ferjm has spent a bunch of time looking into how to implement this in servo and may be able to provide input before he goes on parental leave :)

**Comment by ferjm** [comment]
The implementation of WebAudio in Servo is now part of a bigger plan for bringing Gecko's media capabilities to Servo. The plan is a bit different to what @dmarcos started with https://github.com/servo/servo/compare/master...dmarcos:webaudio-kickoff. The basic idea is to make use of as much of Gecko's media stack as possible in a way that "only" the DOM facing code and its corresponding bindings will be Servo specific.

The current efforts are focused on moving Gecko's media code into an standalone library that can be statically linked into Servo. This work is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1388605 and there's already some code in https://github.com/cpearce/gecko-media. @cpearce and @nox are the right persons to ask if you want some pointers about how to contribute to this initial piece of work.

I believe @nox has already started cleaning up some existing media code and writing some DOM stubs for the MSE APIs that will be the first users of this media library. For WebAudio the required work will be similar. The first pieces to implement for WebAudio are probably AudioContext, AudioNode and AudioDestinationNode. With that in place, the implementation of the other nodes can probably be done in parallel.

My plan is to focus on this implementation as soon as I return from my leave (in ~6 to ~8 weeks from now, depending on when it starts and how it goes :)). Feel free to start working on this, please. Any help is highly appreciated! I'll do my best to help with what's left on my return.

**Comment by rtbo** [comment]
Does that mean that there is no more plan to use `rust-media` in servo?
Although Web audio is a though task to implement, I'd thought native rust implementation would have been preferred over bindings. (not mentionning so much coding and debugging fun will be missed!)

**Comment by jdm** [comment]
Correct; rust-media was an experiment that was never actually used. It makes more sense to rely on battle-hardened libraries in this case.

**Comment by ferjm** [comment]
I'm back, but I'm finally not focusing on this right away, as other [gecko-media](https://github.com/servo/gecko-media) work has higher priority. I have started some DOM stubs at https://github.com/ferjm/servo/tree/webaudio in case anyone wants to follow up. It's not much, but it's a start.
