### ISSUE TITLE
Adding for support Blob.{close,isClose}

### ISSUE THREAD

**Issue by farodin91** [servo/servo#6723]
Spec: https://w3c.github.io/FileAPI/#dfn-Blob

**Comment by farodin91** [comment]
Ilike to do this

**Comment by jdm** [comment]
Go for it :)

**Comment by waddlesplash** [comment]
Wait, wasn't this merged? Why didn't it auto-close?

**Comment by metajack** [comment]
There was no fixes line in the PR.
