### ISSUE TITLE
Remove FIXME comment in handle_evaluate_js

### ISSUE THREAD

**Issue by jdm** [servo/servo#6728]
As of #6726 the FIXME in the final branch of handle_evaluate_js is no longer correct. Let's remove it.

Relevant code: components/script/devtools.rs

**Comment by s142857** [comment]
I think i can do it

**Comment by jdm** [comment]
I think so as well!

**Comment by s142857** [comment]
one question, you only want me to remove the comments

**Comment by s142857** [comment]
https://github.com/servo/servo/pull/6755

**Comment by Wafflespeanut** [comment]
will be fixed by #6920

**Comment by Wafflespeanut** [comment]
has been fixed by #6920 (/cc @jdm)
