### ISSUE TITLE
FileReader::read doesn't need to return anything

### ISSUE THREAD

**Issue by jdm** [servo/servo#6751]
It can't fail, so it doesn't need to return a `Result` value.

Code: components/script/dom/filereader.rs

**Comment by s142857** [comment]
components/script/dom/filereader.rs dosent exist

**Comment by jdm** [comment]
Are you using a recent version of the Servo code? http://mxr.mozilla.org/servo/source/components/script/dom/filereader.rs suggests that it does :)

**Comment by s142857** [comment]
sorry, could you explain what you want me to do

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/components/script/dom/filereader.rs#393 can't fail; it only returns `Ok(())`. That means that we can change the declared return type to void and update any callers.

**Comment by s142857** [comment]
l'll do it

**Comment by farodin91** [comment]
Is merged!
