### ISSUE TITLE
Combine the Process enum and FileReaderEvent struct

### ISSUE THREAD

**Issue by jdm** [servo/servo#6752]
These types are always used together, but in an indirect manner. I propose renaming `Process` as `FileReaderEvent` and implementing `Runnable` on it. The body of the `handler` method can be the body of `Process::handle`.

Code: components/script/dom/filereader.rs

**Comment by jdm** [comment]
Additionally, making `perform_annotated_read_operation` use the `Sender` directly will be easier to understand, I think.

**Comment by frewsxcv** [comment]
@Wafflespeanut did part of this in https://github.com/servo/servo/pull/6761 and mentioned they are going to make the `perform_annotated_read_operation` changes as well, so marking this as assigned for now

**Comment by Wafflespeanut** [comment]
@frewsxcv Actually, this has been fixed in my PR. So, we can close this :)

**Comment by frewsxcv** [comment]
:sparkles:
