### ISSUE TITLE
Dispose of layout data for every node removed from the tree

### ISSUE THREAD

**Issue by jdm** [servo/servo#6754]
When we remove nodes from the DOM tree, we want to free up any layout resources associated with those nodes. The code in `node_removed` only does this for the root node of a tree that is removed from the DOM, though. We should move the call into the loop over all of the nodes in the tree, instead. 

Code: components/script/dom/node.rs

**Comment by nick-thompson** [comment]
Looks like 7b40cc9fd7ea4dcc3816be0cb1ad6543bb5c88e0 removed the `node_removed` function in favor of a `children_changed` function. To my eye, it seems to address disposing layout data for each child removed as well, but someone with a little more Rust/Servo experience should check that.

**Comment by jdm** [comment]
I don't believe the situation has changed - we still only dispose of the layout data for the root child node that is being removed from a parent.

**Comment by nick-thompson** [comment]
Ok! I'll dig in.
