### ISSUE TITLE
Use jsstring_to_str in handle_evaluate_js

### ISSUE THREAD

**Issue by jdm** [servo/servo#6756]
The FIXME in `handle_evaluate_js` about using `jsstring_to_str` is now possible to fix, since [to_string](https://github.com/servo/rust-mozjs/blob/master/src/jsval.rs#L348) now exists.

Code: components/script/devtools.js

**Comment by nick-thompson** [comment]
Sounds simple enough. Mind if I take it?

**Comment by nick-thompson** [comment]
Oops, didn't realize the PR for it. I'll find something else :)

**Comment by khflab** [comment]
to_string() returns JSString and EvaluateJSReply::StringValue is expecting String.

I tried to find the answer inside FromJSValConvertible looking how works but without success

How to fix it?

**Comment by jdm** [comment]
The missing link is `jsstring_to_str` which takes a `*mut JSString` and returns `String` :)

**Comment by khflab** [comment]
oh boy, It's the topic, sorry!

I'll try.
