### ISSUE TITLE
Make Blob::read_out_buffer take a Sender argument instead of returning a Receiver

### ISSUE THREAD

**Issue by jdm** [servo/servo#6763]
Right now Blob::read_out_buffer is in charge of creating a sender/receiver pair. We should put the caller in charge of this instead, by passing a Sender argument for the Blob code to use.

Code: components/script/dom/blob.rs

**Comment by farodin91** [comment]
I take it. Okay?

**Comment by jdm** [comment]
Yep!

**Comment by farodin91** [comment]
Is merged!

**Comment by jdm** [comment]
For future reference, if you put "Fixes #NNNN" in the commit message then the issue will be closed automatically when the PR is merged.
