### ISSUE TITLE
Can't upgrade hyper, "cookie" depends on itself

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#6765]
`mach cargo-update -p hyper` fails because `cookie` depends on itself.

I guess it's because of the `secure` Cargo feature that we're using `cookie` with.

**Comment by pcwalton** [comment]
cc @alexcrichton -- this may well be a Cargo bug.

**Comment by pcwalton** [comment]
This blocks e10s, incidentally.

**Comment by pcwalton** [comment]
Here's the complete tree of dependencies starting at `cookie`.

    cookie
        openssl
            bitflags
            lazy_static
            libc
            openssl-sys
                gcc
                libc
                libressl-pnacl-sys
                    pnacl-build-helper
                        tempdir
                            rand
                                libc
                pkg-config
        rustc-serialize
        time
            gcc
            libc
        url
            encoding
                encoding-index-japanese
                encoding-index-korean
                encoding-index-simpchinese
                encoding-index-singlebyte
                encoding-index-tradchinese
            matches
            rustc-serialize
            serde
                num
                    rand
                        ...
                    rustc-serialize
    
No cyclic dependencies. Seems like a Cargo bug of some kind.

**Comment by frewsxcv** [comment]
Should a bug be opened in rust-lang/cargo to track this?

**Comment by pcwalton** [comment]
I worked around this by updating all dependencies at once and then manually trimming down Cargo.lock.

**Comment by alexcrichton** [comment]
I tried to look into this over the weekend but didn't come up with much. I definitely think this is a Cargo bug though so I've opened https://github.com/rust-lang/cargo/issues/1841

**Comment by frewsxcv** [comment]
Update: https://github.com/rust-lang/cargo/issues/1841 has been closed
