### ISSUE TITLE
Clean up redundant matches in perform_readastext

### ISSUE THREAD

**Issue by jdm** [servo/servo#6766]
For the implementation of step 4, there's a match with a `Some(e) => Some(e)` arm. That's redundant, so we can clean up the code by using a simple `if encoding.is_none()` instead of a match.

Code: components/script/dom/filereader.rs

**Comment by jdm** [comment]
For the implementation of steps 1, 2, and 3, we can just use `blob_body.label.map(` instead of a `match` that has a `None => None` arm.

**Comment by notriddle** [comment]
:hand:

**Comment by jdm** [comment]
It's yours!
