### ISSUE TITLE
Allow devtools to communicate with workers

### ISSUE THREAD

**Issue by jdm** [servo/servo#6767]
Right now we create a channel that the devtools can send things to, but we ignore the receiver and the worker does not watch for messages: http://mxr.mozilla.org/servo/source/components/script/dom/worker.rs#81

We should store the receiver in the new WorkerGlobalScope that gets created, and have DedicatedWorkerGlobalScope::run_worker_scope change from matching on a single receiver to selecting over two of them (using ScriptTask::handle_msgs as inspiration: http://mxr.mozilla.org/servo/source/components/script/script_task.rs#635).

The ultimate end goal here is to be able to evaluate JS in the worker scope by processing the message appropriately like http://mxr.mozilla.org/servo/source/components/script/devtools.rs#28 .

**Comment by Wafflespeanut** [comment]
@jdm Let's close this :)
