### ISSUE TITLE
Merge common fields of BlobBody and ReadData into a new struct

### ISSUE THREAD

**Issue by jdm** [servo/servo#6768]
There's a bunch of overlap between the two structs and the common data just gets passed around a bunch. We should create a ReadMetadata struct, remove BlobData and ReadData, and replace them like so:
`fn foo(data: ReadData)` becomes `fn foo(data: ReadMetadata, blob_contents: Sender<Option<Vec<u8>>>)`, while `fn foo(data: BlobData)` becomes `fn foo(data: ReadMetadata, blob_contents: Option<Vec<u8>>)`.

Code: components/script/dom/filereader.rs

**Comment by r0e** [comment]
Hi Jdm, I'd like to give this a go.

**Comment by jdm** [comment]
Go for it!

**Comment by jdm** [comment]
Any progress, @r0e?

**Comment by r0e** [comment]
Yes, sorry, I'm working on it now. Been busy the last few days.
