### ISSUE TITLE
Check if HTMLImageElement.naturalWidth/naturalHeight respect the device pixel ratio

### ISSUE THREAD

**Issue by jdm** [servo/servo#6769]
This should be easy to figure out by using the "device-pixels-ratio" commandline argument: http://mxr.mozilla.org/servo/source/components/util/opts.rs#278 . If the values for a fully loaded image are not different using two different DPRs, we don't support it yet.

**Comment by jdm** [comment]
Specifically, this requires creating a webpage that contains an image, waiting until the image is loaded and using JS to display the values of the naturalWidth/naturalHeight properties of that image element.

**Comment by notriddle** [comment]
Should this go into the test suite, or do you just want an informational report?

**Comment by jdm** [comment]
I don't believe there's a convenient way to test this, since the DPR is not something that can be set programmatically in a cross-browser fashion (which is what the web-platform-tests are designed to be).
