### ISSUE TITLE
Extract layout query code into a separate file

### ISSUE THREAD

**Issue by jdm** [servo/servo#6787]
layout_task.rs is becoming unwieldy, and will only continue to grow. I propose extracting `LayoutRPCImpl`, `UnioningFragmentBorderBoxIterator`, `CollectingFragmentBorderBoxIterator`, `process_content_box_request`, and `process_content_boxes_request` (these two don't use the `self` argument) into a new file in `layout` called `query.rs`.

Code: components/layout/layout_task.rs

**Comment by Wafflespeanut** [comment]
@jdm This can be closed :)
