### ISSUE TITLE
Allow using bufferData with more than just float32 arrays

### ISSUE THREAD

**Issue by jdm** [servo/servo#6791]
bufferData is allowed to take any kind of array, and we should just extract the underlying bytes and pass them on as far as I can tell.

**Comment by simartin** [comment]
I propose to take it; it looks to me one should "just" change a call to JS_GetFloat32ArrayData into one to JS_GetUint8ArrayData, correct?

**Comment by jdm** [comment]
Sounds good! This is BufferData in `canvas_traits/lib.rs`.
