### ISSUE TITLE
getBoundingClientRect does not account for transform or margin

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#6799]
Following testcase shows 5 in Servo, 106 in Firefox/Chrome.

```
<html>
<head>
<style>
#foo {
margin: 0px 0px 0px 1px;
transform: translate(100px, 200px);
position: fixed;
left: 5px;
}
</style>
</head>
<body>
<div id="foo"> FOO </div>
<script>
var foo = document.getElementById('foo');
alert(foo.getBoundingClientRect().left);
</script>
</body>
</html>
```

**Comment by jdm** [comment]
Relevant code is the UnioningFragmentBorderBoxIterator.

**Comment by dzbarsky** [comment]
The transform should be accounted for in UnioningFragmentBorderBoxIterator, but the border_box that's passed in is already wrong because it doesn't account for margin.  I have a fix for that but I want to discuss with @pcwalton .
