### ISSUE TITLE
Earlier revisions should not show comments from later revisions

### ISSUE THREAD

**Issue by jdm** [servo/servo#6832]
In https://reviewable.io/reviews/servo/servo/6741 Ms2ger left three comments on one line in separate revisions, but they all show up when viewing the very first revision and it is quite confusing.

**Comment by jdm** [comment]
(First comment in CSSStyleDeclaration.rs)

**Comment by Ms2ger** [comment]
Related https://github.com/Reviewable/Reviewable/issues/136

**Comment by jdm** [comment]
Whoops, wrong repository.
