### ISSUE TITLE
Write a reftest for the background attribute on the body element

### ISSUE THREAD

**Issue by jdm** [servo/servo#6838]
#5851 merged without any tests. We should add one - have a reference page that uses CSS to set the background image for a page, and a test page that sets the attribute on the body element instead. See the documentation at http://testthewebforward.org/docs/reftests.html and examples at http://mxr.mozilla.org/servo/source/tests/wpt/mozilla/tests/css/ . You'll need to run `./mach test-wpt --manifest-update tests/wpt/mozilla/tests/css/[new_test.html]` the first time after creating the test in order to update the MANIFEST.json that contains information about known tests.

**Comment by Ms2ger** [comment]
Also include a test that uses the `base` element (which would fail for now).

**Comment by s142857** [comment]
i can do it, this is more up my alley

**Comment by jdm** [comment]
Ok!

**Comment by s142857** [comment]
can you assign to me
