### ISSUE TITLE
Crash - no layout data on jquery.com

### ISSUE THREAD

**Issue by farodin91** [servo/servo#6848]
https://gist.github.com/farodin91/cc5cd2a3882fd9e43dbb

**Comment by jdm** [comment]
@dzbarsky This looks like a problem with trying to use getComputedStyle before the first layout operation has occurred. Are we flushing any outstanding layout first?

**Comment by jdm** [comment]
Or perhaps it's getComputedStyle on a node not in the document?

**Comment by dzbarsky** [comment]
Bingo, the node's parent is null. Checking what we should be doing here...

**Comment by dzbarsky** [comment]
Fixed.
