### ISSUE TITLE
Hidden iframes sometimes don't get recomposited properly

### ISSUE THREAD

**Issue by jdm** [servo/servo#6849]
iframe1.html
```
<iframe src="iframe2.html"></iframe>
<script>
var iframe = document.getElementsByTagName('iframe')[0];
iframe.onload = function() {
  iframe.style.display = "none";
}
</script>
```
iframe2.html
`Iframe content`

The iframe border disappears, but the content sticks around consistently for me.

**Comment by jdm** [comment]
Blocks #6677

**Comment by jdm** [comment]
@glennw @mrobinson As far as I've been able to trace this, we correctly remove the compositor layer when we set a construction result of None. The constellation code correctly sees the pipeline in the current frame in the resulting FrameRect message, and sends the compositor a SetLayerRect message. The compositor finds the layer and updates the bounds, but `send_buffer_requests_for_all_layers` ends up with an empty `layers_and_requests` vector and returns without requesting new data from the pipelines.

**Comment by mrobinson** [comment]
I think this is a regression from https://github.com/servo/rust-layers/pull/182. Layers can either mask their children or not and iframe containers always masking their children. Now, it seems that the property is only respected for layers that create a new RenderContext3D.

**Comment by glennw** [comment]
In theory, iframe root layers *should* always create a new RenderContext3D, which should handle that situation correctly. But perhaps there's a bug and iframe root layers don't result in a RenderContext3D being created?

**Comment by mrobinson** [comment]
Okay. After some investigation I have a fix lined up for rust-layers (https://github.com/servo/rust-layers/pull/201). Once that lands I'll do a PR for servo with a test.

**Comment by mrobinson** [comment]
An update on this one. I think the rust-layers PR fixes the bug, but I'm having a bit of trouble writing a non-flaky reference test for this issue. It is very sensitive to timing. :/

**Comment by mrobinson** [comment]
@jdm @gw r?
