### ISSUE TITLE
update and re-enable CSS tests that use 4 digit colors

### ISSUE THREAD

**Issue by metajack** [servo/servo#6856]
After landing https://github.com/servo/rust-cssparser/pull/80 the following tests started failing incorrectly:

/css21_dev/html4/border-bottom-color-030.htm
/css21_dev/html4/border-left-color-030.htm
/css21_dev/html4/border-right-color-030.htm
/css21_dev/html4/border-top-color-030.htm

These tests need to be updated upstream. Then Servo needs to update the CSS tests and re-enable these.

**Comment by metajack** [comment]
Upstream pull request to update tests: https://github.com/w3c/csswg-test/pull/814

**Comment by jinank94** [comment]
Hi, I would like to work on this bug could someone help me out ?

**Comment by metajack** [comment]
I already submitted a patch https://github.com/w3c/csswg-test/pull/814 but looks like it won't be accepted. I'm not sure what the next steps are.

@Ms2ger @jgraham thoughts?

**Comment by SimonSapin** [comment]
Tests should allow either behavior: https://github.com/w3c/csswg-test/pull/831#issuecomment-134562768

**Comment by nox** [comment]
These tests don't seem disabled to me anymore.
