### ISSUE TITLE
getComputedStyle on an element not in a document returns nothing

### ISSUE THREAD

**Issue by jdm** [servo/servo#6860]
According to the spec, we should resolve the style against the window's rules. Firefox is the only browser that implements this behaviour.

**Comment by mrobinson** [comment]
See also: https://github.com/w3c/csswg-drafts/issues/1548

**Comment by mrobinson** [comment]
According to @emilio, the [spec](https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle) now says that no style should be returned for an element that is not connected.
