### ISSUE TITLE
Implement console log reporting for workers

### ISSUE THREAD

**Issue by jdm** [servo/servo#6866]
There's a TODO about workers in `propagate_console_msg`. The easiest way forward is:
* modify the `SendConsoleMsg` enum to include an `Option<WorkerId>` field
* add a `worker_id` field to `WorkerGlobalScope` that is passed in as an argument in the constructor (`new` and `new_inherited`)
* add a `worker_id` method to `GlobalRef` that returns `None` for a non-worker and the new field for a worker
* modify `propagate_console_msg` to use the required `GlobalRef` methods instead of matching on the specific type

After these changes, it should be possible to connect to a worker from the devtools, execute a `console.log("hi")` and see it appear in the devtools console log.

**Comment by HarryLovesCode** [comment]
@jdm I'd like to give this a shot, but I might need some help if you don't mind.

**Comment by jdm** [comment]
@HarryLovesCode of course! Note that you won't be able to test changes until #6829 merges.

**Comment by HarryLovesCode** [comment]
@jdm As a clarification, you mean "anything except a worker" for the third point? Or do you mean a non-worker as in a window?

**Comment by jdm** [comment]
Well, there are only Workers and Windows in GlobalRef, so the difference is only a semantic one :)

**Comment by jdm** [comment]
Oh, the other part of this work is to modify `handle_console_message` (http://mxr.mozilla.org/servo/source/components/devtools/lib.rs#256) to use the new WorkerId information to find the appropriate ConsoleActor that is associated with a worker.

For that, I recommend:
* adding a `console_actor` field to `WorkerActor` and filling it appropriately in `handle_new_global`
* in `handle_console_msg`, pass in the `actor_workers` hashmap and use it to find the `WorkerActor` for the given `WorkerId` and `PipelineId`, and fetch the console actor based on the field added in the previous step

**Comment by HarryLovesCode** [comment]
@jdm Just making sure :). Also I don't see `WorkerGlobalScope::new()` only `WorkerGlobalScope::new_inherited()`. Did you mean `DedicatedWorkerGlobalScope`?

**Comment by jdm** [comment]
I did and I didn't. The field should be added to WorkerGlobalScope, which is inherited by DedicatedWorkerGlobalScope (for all practical purposes), so it should be passed in through the constructor of both DedicatedWorkerGlobalScope and WorkerGlobalScope.

Also, if you need to do any testing of the devtools stuff, https://github.com/servo/servo/wiki/Devtools should have you covered.

**Comment by HarryLovesCode** [comment]
@jdm I appreciate you helping me out as I'm new to Rust. Two more things:

1. Should the `propagate_console_msg` behave any differently if it matches to a worker?
2. Do you mind to explain your second point? I see what you're talking about, but I don't understand when we should find the `WorkerActor` unless we check for that and then get its `ConsoleActor` accordingly.

**Comment by jdm** [comment]
1. The code in propagate_console_msg should not behave any differently; there should be no match at all and it should get the values it requires directly from the GlobalRef methods.
2. in `handle_console_message`, if there's a non-`None` value for the worker id then we should search for a `WorkerActor` instead of a `TabActor` (using the worker id and pipeline id present in the message we received), and get the name of the appropriate `ConsoleActor` from this result. Does that make sense?

**Comment by HarryLovesCode** [comment]
It makes sense, but I'm not sure how to pattern match that... Sorry :/

**Comment by jdm** [comment]
Assuming something like
```rust
     fn find_console_actor(actors: Arc<Mutex<ActorRegistry>>,
                           id: PipelineId,
                           worker_id: Option<WorkerId>,
                           worker_actors: &HashMap<(PipelineId, WorkerId), String>,
                           actor_pipelines: &HashMap<PipelineId, String>) -> Option<String> {
```
We can do this:
```rust
if let Some(worker_id) = worker_id {
    let worker_actor_name = match worker_actors.get(&(id, worker_id)) {
        Some(name) => name,
        None => return,
    };
    // find the worker actor, fetch the console_actor name from it, return the name
}
```
Is that more clear?

**Comment by Wafflespeanut** [comment]
@HarryLovesCode If you're new to Rust, I suggest going through the [issues labeled E-easy](https://github.com/servo/servo/labels/E-easy) before you can get into E-less-easy ones, though the choice entirely up to you :)

**Comment by HarryLovesCode** [comment]
@Wafflespeanut Yeah, I probably should have started with those. However, I'd like to try to finish this if that's ok. 

@jdm Final thing, I tried to start servo and it panicked due to the output of this method being unwrapped...

```rust
// components/dom/binding/global.rs
pub fn get_worker_id(&self) -> Option<WorkerId> {
    match *self {
        GlobalRef::Window(ref window) => None, // <- Problem is here
        GlobalRef::Worker(ref worker) => Some(worker.get_worker_id()),
    }
}
```

Any idea why?

**Comment by jdm** [comment]
Well, the problem isn't that get_worker_id returns None - the problem is that some caller is calling `unwrap`, rather than passing around an `Option<WorkerId>` value as necessary.

**Comment by jdm** [comment]
In theory there should be a backtrace of the failure showing up when that happens, and it should show who's calling unwrap.

**Comment by HarryLovesCode** [comment]
@jdm Got it. Logging works from web workers (at least to the console), but devtools causes a crash. I assume #6829 will fix the issue with devtools?

**Comment by jdm** [comment]
It might! We should be able to find out soon.

**Comment by jdm** [comment]
It merged, so it should be possible to test this manually by connecting to a page with a worker (`<script>new Worker('worker.js')</script>`) and executing `console.log('hi')` in the web console that appears.

**Comment by Wafflespeanut** [comment]
@HarryLovesCode @jdm It's been merged. Sorry for letting this sit around for a while - so many unanticipated, (but interesting) results along the way

**Comment by HarryLovesCode** [comment]
@jdm I'm trying to use the web console, but no logging appears at all (even a simple `console.log("TEST")` from outside of a worker). All I get it this:

```text
page error test <unknown>
"console error test"
```

**Comment by Wafflespeanut** [comment]
@HarryLovesCode The logging occurs in your terminal (where you run the servo instance). For instance, input something on the console and see if you get it in the command-line. It won't appear on the console for now because that's the sole purpose of this issue :)

**Comment by HarryLovesCode** [comment]
@Wafflespeanut ? If I input something in the devtools console I see it on the command-line **and** in the console. I thought the issue was for getting logging to work *inside* of a worker.

**Comment by Wafflespeanut** [comment]
@HarryLovesCode Right, all that I've said above assumes that you're running everything inside a worker (sorry I didn't mention that). While running a worker, the devtools console can be used to send messages (whose output will be displayed in the command-line, but not on your devtools console - [it looks like this](http://i.imgur.com/82dSEBr.png)).

So, the console (which usually logs in the absence of a worker) doesn't log when inside a worker. The aim of this issue is to fix that. Once we fix it, we'll be able to get the output just like the usual `console.log` outputs. Does that help?

**Comment by HarryLovesCode** [comment]
@Wafflespeanut That helps a lot. I'll commit the changes in a few minutes. I've got it working properly now. Sorry about the confusion.

**Comment by Wafflespeanut** [comment]
@HarryLovesCode No problem. And, please ensure that your local build succeeds (to make sure that your changes haven't actually broken something).

**Comment by frewsxcv** [comment]
We should probably create a regression test for this before closing

**Comment by jdm** [comment]
We can't without #5971, unfortunately.
