### ISSUE TITLE
Layout memory reporter uses pre-redirect url

### ISSUE THREAD

**Issue by jdm** [servo/servo#6872]
For example, if I look at the output for http://google.com the script reporter says "url(https://www.google.ca/?gfe_rd=cr&ei=kqK7Va3eD-eM8Qeyo4PwBQ)" while layout says "url(http://google.com/)".

**Comment by jdm** [comment]
We could either delay creating the layout task until the document is created (ie. we've received the headers for the HTTP request), or we could just make LayoutTask's `url` field mutable. I propose using a `RefCell<Option<Url>>`, starting with None and having the script task send a message to update it when the final url is determined in `ScriptTask::load`.

To test this, use `./mach run -m 1 http://google.com`.

Relevant code: components/layout/layout_task.rs, components/script/script_task.rs

**Comment by pcwalton** [comment]
I like the idea of making the URL mutable: the document's URL is a changeable thing after all.

**Comment by jdm** [comment]
No; a layout task only services a single document so I would not expect the url to change.
