### ISSUE TITLE
Panic in 'script_task::ScriptTask::handle_msg_from_script' using -x option

### ISSUE THREAD

**Issue by connorimes** [servo/servo#6877]
Running 'reddit_ the front page of the internet.html' from the servo static suite using the -x option in servo.

In release build:

<pre>
#0  0x0000555556de04a0 in rust_panic ()
#1  0x0000555556dcd2ce in rt::unwind::begin_unwind_inner::hb561d488e4095b19o3w
    ()
#2  0x0000555556dcdc96 in rt::unwind::begin_unwind_fmt::hcfdd98fa08198219u2w ()
#3  0x0000555556de0537 in rust_begin_unwind ()
#4  0x0000555556e11f25 in panicking::panic_fmt::h18e94a0fe8bc1992MhC ()
#5  0x0000555555e5340d in script_task::ScriptTask::handle_msg_from_script::hb9927abfc568898e2L3 ()
#6  0x0000555555e7db84 in script_task::ScriptTask::handle_msgs::h5e2ed18eeac055a4tz3 ()
#7  0x0000555555e466b8 in boxed::F.FnBox$LT$A$GT$::call_box::h8531507202088554875 ()
#8  0x0000555555a3a7ca in rt::unwind::try::try_fn::h10659772558487664251 ()
#9  0x0000555556de0460 in __rust_try_inner ()
#10 0x0000555556de049b in __rust_try ()
#11 0x0000555556ddad08 in rt::unwind::try::inner_try::h2721e05d3675a507hZw ()
#12 0x0000555555a3a9df in boxed::F.FnBox$LT$A$GT$::call_box::h13977558701962522708 ()
#13 0x0000555556ddf612 in sys::thread::Thread::new::thread_start::h3e0fc9f59f3e6025X8v ()
#14 0x00007ffff79ba6aa in start_thread (arg=0x7fffaffff700)
    at pthread_create.c:333
#15 0x00007ffff71c5eed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
</pre>

Reproduced in debug build:

<pre>
#0  0x00005555584f39c0 in rust_panic ()
#1  0x00005555584e07ee in rt::unwind::begin_unwind_inner::hb561d488e4095b19o3w
    ()
#2  0x00005555584e11b6 in rt::unwind::begin_unwind_fmt::hcfdd98fa08198219u2w ()
#3  0x00005555584f3a57 in rust_begin_unwind ()
#4  0x0000555558525445 in panicking::panic_fmt::h18e94a0fe8bc1992MhC ()
#5  0x0000555556adc6c8 in script::option::Option<T>::expect (self=..., msg=...)
    at src/libcore/macros.rs:28
#6  0x0000555556ad5215 in script::script_task::ScriptTask::handle_fire_timer_msg (self=0x7fffe45fd020, id=..., timer_id=...)
    at /local/servo/components/script/script_task.rs:1110
#7  0x0000555556a3f64a in script::script_task::ScriptTask::handle_msg_from_script (self=0x7fffe45fd020, msg=...)
    at /local/servo/components/script/script_task.rs:822
#8  0x0000555556a9cb34 in script::script_task::ScriptTask::handle_msgs (
    self=0x7fffe45fd020) at /local/servo/components/script/script_task.rs:739
#9  0x0000555556a3d446 in script::script_task::ScriptTask::start (
    self=0x7fffe45fd020) at /local/servo/components/script/script_task.rs:598
#10 0x0000555556a296c4 in fnfn ()
    at /local/servo/components/script/script_task.rs:450
#11 0x0000555556a28415 in fnfn () at /local/servo/components/util/task.rs:31
#12 0x0000555556a28335 in script::boxed::F.FnBox<A>::call_box (
    self=0x7fffe7448280, args=0) at src/liballoc/boxed.rs:514
#13 0x0000555556153c51 in script::boxed::Box<FnBox<A, Output = R>+ Send + 'a>.FnOnce<A>::call_once (self=..., args=0) at src/liballoc/boxed.rs:530
#14 0x0000555556153703 in fnfn () at src/libstd/thread/mod.rs:322
#15 0x000055555615367f in script::rt::unwind::try::try_fn<closure> (
    opt_closure=0x7fffe45fd910 "") at src/libstd/rt/unwind/mod.rs:157
#16 0x00005555584f3980 in __rust_try_inner ()
#17 0x00005555584f39bb in __rust_try ()
#18 0x00005555584ee228 in rt::unwind::try::inner_try::h2721e05d3675a507hZw ()
#19 0x00005555561535c9 in script::rt::unwind::try<closure> (f=...)
    at src/libstd/rt/unwind/mod.rs:129
#20 0x000055555615342f in fnfn () at src/libstd/thread/mod.rs:322
#21 0x0000555556153fce in script::boxed::F.FnBox<A>::call_box (
    self=0x7fffe742f450, args=0) at src/liballoc/boxed.rs:514
#22 0x00005555584f2b32 in sys::thread::Thread::new::thread_start::h3e0fc9f59f3e6025X8v ()
#23 0x00007ffff79ba6aa in start_thread (arg=0x7fffe45fe700)
    at pthread_create.c:333
#24 0x00007ffff71c5eed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
</pre>

**Comment by mrobinson** [comment]
Does seem to be an issue any longer.
