### ISSUE TITLE
Panic (in tick_animations_for_pipeline?) on vsynctester.com

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#6878]
ERROR:js::rust: Error at http://www.vsynctester.com/:0: TypeError: document.writeln is not a function

www.vsynctester.com - Copyright (c) 2014-2015 Jerry Jongerius
performance.now=yes
ERROR:js::rust: Error at http://www.vsynctester.com/:179: TypeError: ctx.fillText is not a function

thread 'ScriptTask PipelineId(0)' panicked at 'called `Result::unwrap()` on an `Err` value: JSFailed', src/libcore/result.rs:731
stack backtrace:
   1:        0x10aebf1f5 - sys::backtrace::write::hde88a3e3a343e9f8zms
   2:        0x10aec27e5 - panicking::on_panic::h8c73c8f1e33f6d60hIw
   3:        0x10aeb02d2 - rt::unwind::begin_unwind_inner::h781ff1cd39e7f47etqw
   4:        0x10aeb0939 - rt::unwind::begin_unwind_fmt::h9c0f8818a5804071zpw
   5:        0x10aec21bc - rust_begin_unwind
   6:        0x10aeeb0e5 - panicking::panic_fmt::h205f328075c6fc3cneC
   7:        0x109940cf8 - result::Result<T, E>::unwrap::h7505263579469650260
   8:        0x109c6c987 - dom::window::_&'a Window.WindowMethods::RequestAnimationFrame::closure.131127
   9:        0x1099cee18 - extern $u22$rust.call$u22$$u20$fn$LP$$RF$core..ops..Fn$LP$f64$RP$$u20$$u2b$$u20$$u27$static$C$$u20$$LP$f64$C$$RP$$RP$::object_shim.122007::h4db0e8f2737f9077
  10:        0x1099cb9b7 - dom::document::_&'a Document.DocumentHelpers<'a>::invoke_animation_callbacks::h69b727b6fd18ad2fmby
  11:        0x109d8f0fb - script_task::ScriptTask::handle_tick_all_animations::hcdb3a72f20e80815Bu4
  12:        0x109d8b3d2 - script_task::ScriptTask::handle_msg_from_constellation::h65acdbdbbb24b5cdrQ3
  13:        0x109d5985f - script_task::ScriptTask::handle_msgs::h1af760511b88b096eH3
  14:        0x109cf26c1 - script_task::ScriptTask::start::h36cdd2a10add55354G3
  15:        0x109cdebb1 - script_task::ScriptTask.ScriptTaskFactory::create::closure.132608
  16:        0x109cddba4 - task::spawn_named_with_send_on_failure::closure.132602
  17:        0x109cddac4 - boxed::F.FnBox<A>::call_box::h9967051184662937863
  18:        0x109406230 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h17926986257602689816
  19:        0x109405ca2 - thread::Builder::spawn_inner::closure.99154
  20:        0x109405c1e - rt::unwind::try::try_fn::__rust_abi::h6460765356877904912
  21:        0x109405bb9 - rt::unwind::try::try_fn::h6460765356877904912
  22:        0x10aec41e8 - rust_try_inner
  23:        0x10aec41d5 - rust_try
  24:        0x10aebd795 - rt::unwind::try::inner_try::h9e58480e93edc0cdmmw
  25:        0x109405b18 - rt::unwind::try::h16776379909104437777
  26:        0x109405951 - thread::Builder::spawn_inner::closure.99103
  27:        0x1094065bd - boxed::F.FnBox<A>::call_box::h11018110284466146359
  28:        0x10aec11ad - sys::thread::Thread::new::thread_start::hf153915745363fa7wKv
  29:     0x7fff98f0d267 - _pthread_body
  30:     0x7fff98f0d1e4 - _pthread_start
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:731
stack backtrace:
   1:        0x10aebf1f5 - sys::backtrace::write::hde88a3e3a343e9f8zms
   2:        0x10aec27e5 - panicking::on_panic::h8c73c8f1e33f6d60hIw
   3:        0x10aeb02d2 - rt::unwind::begin_unwind_inner::h781ff1cd39e7f47etqw
   4:        0x10aeb0939 - rt::unwind::begin_unwind_fmt::h9c0f8818a5804071zpw
   5:        0x10aec21bc - rust_begin_unwind
   6:        0x10aeeb0e5 - panicking::panic_fmt::h205f328075c6fc3cneC
   7:        0x1090d7b4b - result::Result<T, E>::unwrap::h10639205249171761698
   8:        0x1090d7d3e - pipeline::Pipeline::force_exit::hb33e4c1401ce74b8brd
   9:        0x10840e765 - constellation::Constellation<LTF, STF>::close_pipeline::h15774521592946311010
  10:        0x10840ca8d - constellation::Constellation<LTF, STF>::handle_failure_msg::h11828554546516856413
  11:        0x1083ee311 - constellation::Constellation<LTF, STF>::handle_request::h2590647020652941008
  12:        0x1083e8658 - constellation::Constellation<LTF, STF>::run::h14450661793364244333
  13:        0x1083af0a5 - constellation::Constellation<LTF, STF>::start::closure.7556
  14:        0x1083adfa4 - task::spawn_named::closure.7549
  15:        0x1083aded4 - boxed::F.FnBox<A>::call_box::h1194060180463228324
  16:        0x1083ad940 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h18231194623863148110
  17:        0x1083ad3b2 - thread::Builder::spawn_inner::closure.7521
  18:        0x1083ad32e - rt::unwind::try::try_fn::__rust_abi::h1956619081265734080
  19:        0x1083ad2c9 - rt::unwind::try::try_fn::h1956619081265734080
  20:        0x10aec41e8 - rust_try_inner
  21:        0x10aec41d5 - rust_try
  22:        0x10aebd795 - rt::unwind::try::inner_try::h9e58480e93edc0cdmmw
  23:        0x1083ad228 - rt::unwind::try::h2193560941804901220
  24:        0x1083ad061 - thread::Builder::spawn_inner::closure.7470
  25:        0x1083adc5d - boxed::F.FnBox<A>::call_box::h17680867185145209345
  26:        0x10aec11ad - sys::thread::Thread::new::thread_start::hf153915745363fa7wKv
  27:     0x7fff98f0d267 - _pthread_body
  28:     0x7fff98f0d1e4 - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:731
stack backtrace:
   1:        0x10aebf1f5 - sys::backtrace::write::hde88a3e3a343e9f8zms
   2:        0x10aec27e5 - panicking::on_panic::h8c73c8f1e33f6d60hIw
   3:        0x10aeb02d2 - rt::unwind::begin_unwind_inner::h781ff1cd39e7f47etqw
   4:        0x10aeb0939 - rt::unwind::begin_unwind_fmt::h9c0f8818a5804071zpw
   5:        0x10aec21bc - rust_begin_unwind
   6:        0x10aeeb0e5 - panicking::panic_fmt::h205f328075c6fc3cneC
   7:        0x1082cb6db - result::Result<T, E>::unwrap::h10901601740050735895
   8:        0x1082e8119 - compositor::IOCompositor<Window>::tick_animations_for_pipeline::h8724684443541947267
   9:        0x10833b9ec - compositor::IOCompositor<Window>::process_animations::h4051538041673735513
  10:        0x1083246a3 - compositor::IOCompositor<Window>::composite_specific_target::h14272929851462782445
  11:        0x108348551 - compositor::IOCompositor<Window>::composite::h14822960370269633091
  12:        0x1082ce739 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h3954131798539678627
  13:        0x108350401 - Browser::handle_events::h05c1b798ef852b8a0ca
  14:        0x108255c6a - main::hb166559cbb3a3110qaa
  15:        0x10aec41e8 - rust_try_inner
  16:        0x10aec41d5 - rust_try
  17:        0x10aec3143 - rt::lang_start::h037f7e0f45d9aee3eDw
  18:        0x10834ef3e - main
thread 'LayoutTask PipelineId(0)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:731
stack backtrace:
   1:        0x10aebf1f5 - sys::backtrace::write::hde88a3e3a343e9f8zms
Servo exited with return value 101

**Comment by jdm** [comment]
Oh yeah, this is just incorrect. We call `unwrap` on the result of `callback.Call__`, when we really want to just discard the result with `let _ = ` instead.

**Comment by dzbarsky** [comment]
Sorry, forgot to post. I have a PR fixing this and adding tests: https://github.com/servo/servo/pull/6880

**Comment by dzbarsky** [comment]
Fixed.
