### ISSUE TITLE
Don't unwrap errors in the devtools TCP protocol

### ISSUE THREAD

**Issue by jdm** [servo/servo#6879]
The code in `read_json_packet` is unwrap happy. We should be using `try!` instead, or `match`, or `map_err` to return errors to the caller instead of dying horribly. This can be exercised by [running the devtools server](https://github.com/servo/servo/wiki/Devtools) and connecting to it from a web browser or curl or something and providing input that is unexpected.

Code: components/devtools/protocol.rs

**Comment by HarryLikesCode** [comment]
@jdm Should all of the unwraps be handled? Or just the one that causes a panic when curl connects (`u64::from_str_radix` on the packet length I believe)?

**Comment by jdm** [comment]
We can try changing all of the unwraps in `read_json_packet`!
