### ISSUE TITLE
Use the standard std::default::Default trait instead of new() functions

### ISSUE THREAD

**Issue by boghison** [servo/servo#6887]
IMHO, since this is the standard approach, it would be nicer to use it, instead of T::new()

**Comment by jdm** [comment]
That's only true for situations when the constructor method takes no arguments, right? I think the project preference is generally for explicit constructor methods.

**Comment by jdm** [comment]
However, are there any examples you think would be better expressed with Default?

**Comment by boghison** [comment]
@jdm Yes, that is true. Example: (where I thought of this) Response. And, of course, if all fields implement Default, adding it is as easy as derive(Default).

**Comment by Ms2ger** [comment]
This seems like something that should be discussed on a case-by-case basis, rather than in a widely-scoped issue like this.
