### ISSUE TITLE
Add a tool for comparing Dromaeo outputs

### ISSUE THREAD

**Issue by jdm** [servo/servo#6888]
`./mach test-dromaeo` yields output like https://gist.github.com/notriddle/e59c854002ddbf5a88bf . We should run a tool that takes two saved results, ignores all output before the actual test timings, then prints out a chart showing how much (+/- % and actual value) each test result differed. This will be useful to evaluating how a change to some implementation code actually affects the timing results. This tool can live in `testing/dromaeo` and a command to invoke it can be added to `python/servo/testing_commands.py`.

**Comment by boghison** [comment]
By chart do you mean another table? My understanding is that (assuming the first test), this would look something like this:
`blue[dromaeo-object-regexp/Compiled Variable Object 12 Char Replace Function]   |  yellow[Diff]: green[-20%] yellow[Time 1]: red[x] yellow[Time 2]: green[y]`

(With colors for readability) :)

**Comment by notriddle** [comment]
I should mention that the output was actually slightly changed after the gist was made. The only difference is line 965, which now has a pipe in it that lines up with the rest of them (this way, the table would be rendered as one in GitHub-flavored Markdown).

**Comment by jdm** [comment]
@boghison Basically yes. I'm not sure I understand the `yellow[Time 1]: red[x] yellow[Time 2]: green[y]` bit though.

**Comment by boghison** [comment]
@jdm Time 1 is from the first file, it is red because it's longer by 20%.

**Comment by jdm** [comment]
Ah, that makes more sense.

**Comment by johntyree** [comment]
Aren't there quite a few benchmarking tools out there that can be used to consume these results? Python has airspeed velocity (asv) for example. I'm not sure that one in particular is a good fit, but surely there are others?

**Comment by notriddle** [comment]
Then fix the test harness to output results that the tools can read, and the job is done.

**Comment by jdm** [comment]
Well, as long as it's easy to acquire those tools on all platforms. The advantage of a simple custom script is that it will work everywhere.

**Comment by jdramani** [comment]
@jdm I think i can write the necessary python script. But I will need some guidance to put pieces into right places as i am new to the codebase..

**Comment by jdm** [comment]
@jdramani Welcome :) I think adding it to `python/testing_commands.py` as a new command named `compare-dromaeo` would make sense.

**Comment by jdm** [comment]
How's it going, @jdramani? Any problems I can help resolve?

**Comment by jdramani** [comment]
@jdm I am sorry i got stuck in my work but i will  finish the script by tomorrow. I will give you an update regarding this.

**Comment by jdm** [comment]
No hurry! I just wanted to make sure that you weren't stuck on something :)

**Comment by jdramani** [comment]
Currently, for color outputs (green: when time taken decreases and red: when time taken increases) I am making my own class. So if there already exists such class then can you point me to it so that i do not have to define again.
Secondly, the command will operate like this, right? : ./mach compare-dromaeo filepath1 filepath2 
So we do not have to worry about where the both files are stored.
Thirdly, below is the image of the output. Should I make any changes? As an example i have manually edited first two fields to show the green and red color.

![screenshot from 2015-09-23 11 56 07](https://cloud.githubusercontent.com/assets/9928270/10055297/3cefe39e-61ea-11e5-8975-f24046d9b772.png)

**Comment by jdm** [comment]
First: all colour code is manual right now; a class would probably allow us to improve the other code that modifies the terminal output right now.
Secondly: Correct.
Third: That looks great! Perhaps call the second column "First run" and the third "Second run" for clarity.

**Comment by nox** [comment]
#7759
