### ISSUE TITLE
Intermittent timeout /css21_dev/html4/z-index-012.htm

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#6892]
https://github.com/servo/servo/pull/6741#issuecomment-126955540
http://build.servo.org/builders/mac3/builds/730

**Comment by jdm** [comment]
```
18:37.88 TEST_START: Thread-TestrunnerManager-6 /css21_dev/html4/z-index-012.htm
18:53.92 TEST_END: Thread-TestrunnerManager-6 TIMEOUT, expected FAIL
```
Build logs aren't permanent, so it's best to stash the known output in github issues.

**Comment by nox** [comment]
Happened only once.
