### ISSUE TITLE
HTMLCollection::create should cache results

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#6901]
Other browsers do this and it's killing Dromaeo query performance.

I tried to make CollectionFilter derive Hash, but the Hash trait defines hash_slice which means CollectionFilter won't be object-safe, and therefore we can't pass Box<CollectionFilter> into HTMLCollection::create.

I'm trying some other things, but hashing a trait seems pretty tricky in general.

**Comment by pcwalton** [comment]
You could wrap the trait object in a wrapper struct which implements Hash by forwarding to a hashing method on the trait object.

**Comment by dzbarsky** [comment]
I tried http://is.gd/HqMVqQ but that involves implementing Eq/Hash on CollectionFilter, and I don't think we want to do that. Trying @pcwalton's suggestion now...

**Comment by dzbarsky** [comment]
@pcwalton is http://is.gd/DW2rFf what you meant? @jdm and I couldn't figure out how to get this to actually work because the Self type differs in the actual CollectionFilter implementations.  It seems like you would need to pass down the params as CollectionFilter, and then you'd need to be able to differentiate different types of filters.  At that point, it would be simpler to just have an enum of all possible filters.

**Comment by KiChjang** [comment]
Fixed by #8227.
