### ISSUE TITLE
Use JSTypedMethodJitInfo and the [Pure] annotation to allow SpiderMonkey to LICM getAttribute()

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#6904]
Not having this is the reason we're thousands of times slower on some Dromaeo benchmarks; e.g. `getAttribute()`.

cc @metajack @bzbarsky

**Comment by pcwalton** [comment]
cf https://bugzilla.mozilla.org/show_bug.cgi?id=938294

**Comment by jdm** [comment]
We may need to look patch 3 in https://bugzilla.mozilla.org/show_bug.cgi?id=939581 too.

**Comment by jdm** [comment]
I also note this difference between our CGMemberJSJitInfo and Gecko's:
Gecko:
```
8601                 if (len(sig[1]) != 0 or
8602                     not infallibleForMember(self.member, sig[0], self.descriptor)):
8603                     # We have arguments or our return-value boxing can fail
8604                     methodInfal = False
```
Servo:
```
3154                 if (len(sig[1]) != 0):
3155                     # We have arguments or our return-value boxing can fail
3156                     methodInfal = False
```

**Comment by jdm** [comment]
I think this is just something that was left out of the SM upgrade; I'm pretty sure I remember seeing it commented out at one point.

**Comment by bzbarsky** [comment]
Yeah, claiming infallible if your return-value boxing can fail is bad: it can cause SpiderMonkey to run JS on a context with an already-thrown exception and hijinks will ensue....

**Comment by Ms2ger** [comment]
Return-value boxing panics on failure, so this shouldn't be an issue.

**Comment by froydnj** [comment]
I will look at doing this.
