### ISSUE TITLE
Measure the memory usage of HashSet

### ISSUE THREAD

**Issue by jdm** [servo/servo#6909]
There's at least one in Window that is not contributing to the count of heap allocations.

**Comment by jdm** [comment]
https://github.com/servo/heapsize/blob/2163ab990795b4b9ae150b0cbb2c57b088f530e1/src/lib.rs#L241 exists.

**Comment by nox** [comment]
https://github.com/servo/servo/blob/1ed3521dcfdf573dd68afe18148e785a8af2389a/components/script/dom/window.rs#L194

**Comment by jdm** [comment]
Specifically, we need to get rid of that line that was linked in the previous comment, because that member is not being measured right now.

**Comment by wldcordeiro** [comment]
I'm interested in trying to get this issue. :hand:

**Comment by KiChjang** [comment]
Awesome!

**Comment by wldcordeiro** [comment]
To confirm the only thing that needs to be done is a line deletion? I'm not sure the description made it entirely clear.

**Comment by jdm** [comment]
Correct.

**Comment by wldcordeiro** [comment]
👍 Doing so now and running a build and test suite. PR incoming shortly.
