### ISSUE TITLE
Measure the heap usage of Url

### ISSUE THREAD

**Issue by jdm** [servo/servo#6912]
There are a lot of them, and they're stubbed out as 0 in mem.rs right now.

**Comment by SimonSapin** [comment]
rust-url being an external crate makes it hard to derive `HeapSizeOf`, but implementing manually in `mem.rs` should be doable as all `Url` fields are public. To make sure this impl is and stays correct, use struct patterns rather than `foo.bar` field access:

```rust
let &Url { ref scheme, ref scheme_data, ref query, ref fragment } = url;
scheme.heap_size_of_children() +
    scheme_data.heap_size_of_children() +
    query.heap_size_of_children() +
    fragment.heap_size_of_children()

**Comment by metajack** [comment]
Why do struct patterns ensure forward compatability here? Also what if more public fields are added? Won't the struct pattern then fail but direct field access have been fine?

**Comment by SimonSapin** [comment]
That’s the point: if a future rust-url version adds a new field, an exhaustive struct pattern (without `..`) will fail to build rather then silently fail to measure some data. This build failure will force us to update the measuring code to make it correct again.

**Comment by nnethercote** [comment]
> use struct patterns rather than foo.bar field access

That's a neat trick.

**Comment by nnethercote** [comment]
...and a trick that arguably deserves a comment so some eager beaver doesn't rewrite the code in the future?
