### ISSUE TITLE
HTTPS tests break in WPT with certification validation error

### ISSUE THREAD

**Issue by jdm** [servo/servo#6919]
I assume we need to set up Servo to load certificates from a different location than usual; @jgraham ?

**Comment by SimonSapin** [comment]
`./mach test-wpt` output shows that a certificate is created. I suppose it should be added to the set of trusted roots. (Only for the purpose of running tests of course.)

**Comment by jgraham** [comment]
Yes, that's what Firefox does (using certutil; see https://dxr.mozilla.org/mozilla-central/source/testing/web-platform/harness/wptrunner/browsers/firefox.py#177 ). I don't know how to do the same for Servo however.

**Comment by SimonSapin** [comment]
`net::http_loader::load` calls `openssl::ssl::SslContext::set_CA_file`. Maybe have a command-line option to use an alternative CA file? Or should this be more obscure, to avoid tempting users?

By the way, @Manishearth, where does `resources/certs` come from? It’s rather opaque.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/blob/master/etc/cert_generator.js run in Firefox's browser debugger shell (Ctrl-Shift-J if enabled)

**Comment by Manishearth** [comment]
We can create a new resources dir for testing and pass it via `--resources-path`

**Comment by jdm** [comment]
That _would_ also allow us to get rid of a bunch of the guessing at http://mxr.mozilla.org/servo/source/components/util/resource_files.rs#20...

**Comment by SimonSapin** [comment]
@jdm do you mean making `--resources-path` mandatory?

**Comment by jdm** [comment]
Well, we could default to assuming a path like target/mode/servo I suppose?

**Comment by jdm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1025066 was the similar implementation for Gecko.
