### ISSUE TITLE
Write a WPT test for STS headers

### ISSUE THREAD

**Issue by jdm** [servo/servo#6921]
I've got one I'm working on but it runs afoul of Firefox's mixed content blocking. My idea is that the test is run in an HTTPS window, loads an HTTPS iframe that has an STS header, then loads an HTTP iframe that should be upgraded.

cc @samfoo

**Comment by nox** [comment]
@jdm STS as in HSTS? That's fixed right?

**Comment by jdm** [comment]
This is not fixed, since we don't have a WPT test.

**Comment by Darkspirit** [comment]
It's currently tested in [components/net/tests/fetch.rs](https://github.com/servo/servo/blob/b7aaff499501e0f1f0d411db5059f59e4828419d/components/net/tests/fetch.rs#L639).
Upstream issue: https://github.com/web-platform-tests/wpt/issues/4880

**Comment by jdm** [comment]
No real point in tracking it here, given the upstream issue.
