### ISSUE TITLE
Improve the names for devtools-related channels in workers.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6924]
`WorkerGlobalScope` has fields

```rust
    devtools_chan: Option<IpcSender<ScriptToDevtoolsControlMsg>>,

    /// Optional `IpcSender` for sending the `DevtoolScriptControlMsg`
    /// to the server from within the worker
    devtools_sender: Option<IpcSender<DevtoolScriptControlMsg>>,

    /// This `Receiver` will be ignored later if the corresponding
    /// `IpcSender` doesn't exist
    devtools_receiver: Receiver<DevtoolScriptControlMsg>,
```

This is confusing because `chan` and `sender` are usually used interchangeably.

`DedicatedWorkerGlobalScope::run_worker_scope` has arguments

```rust
                            devtools_chan: Option<IpcSender<ScriptToDevtoolsControlMsg>>,
                            devtools_ipc_chan: Option<IpcSender<DevtoolScriptControlMsg>>,
                            devtools_ipc_port: IpcReceiver<DevtoolScriptControlMsg>,
```

which is no less confusing, as the two senders are `IpcSender`s.

To fix this issue, figure out the distinction between these channels, and invent names for them that explain the distinction. None of those names should use the outdated terms "chan" or "port".

**Comment by Wafflespeanut** [comment]
I don't think this is a E-less-easy issue now. In fact, I should've given nice names when I added those fields...

**Comment by Wafflespeanut** [comment]
#7238 closes this.
