### ISSUE TITLE
Restarting too quickly causes hang with Linux i915 graphics driver

### ISSUE THREAD

**Issue by connorimes** [servo/servo#6933]
Restarting servo too quickly sometimes results in a system UI freeze when opening a new Servo window, requiring a hard reboot.  Issue filed with Linux kernel [1].  My restart with was approximately 1 second.  Increasing the sleep time seems to work around the problem, but slows down collecting benchmark results.

[1] https://bugzilla.kernel.org/show_bug.cgi?id=102161

The system is a Lenovo Thinkpad X1 Carbon 3rd Gen, running Ubuntu 15.04 with upstream kernel 4.2.0-040200rc4-generic.

Servo hangs here:

<pre>
#0  0x00007f837af3d0b7 in ioctl () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f8378a177e8 in drmIoctl ()
   from /usr/lib/x86_64-linux-gnu/libdrm.so.2
#2  0x00007f837664de9c in drm_intel_gem_bo_start_gtt_access ()
   from /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1
#3  0x00005634d7de5183 in window::Window::new::haba041c2f46fbd05Rxa ()
#4  0x00005634d7cecb52 in main::h0c62f9eb269d2dd5raa ()
#5  0x00005634d9266ff9 in rust_try_inner ()
#6  0x00005634d9266fe6 in rust_try ()
#7  0x00005634d9263b79 in rt::lang_start::h6c59a9adbeceea29z5w ()
#8  0x00007f837ae60a40 in __libc_start_main (main=0x5634d7d4db90 <main>, 
    argc=6, argv=0x7ffe6b853658, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe6b853648) at libc-start.c:289
#9  0x00005634d7cec649 in _start ()
</pre>

**Comment by dralley** [comment]
Kernel fixed, this should be closed.

**Comment by jdm** [comment]
Thanks!
