### ISSUE TITLE
Implement AbstractWorker onerror event handler

### ISSUE THREAD

**Issue by jdm** [servo/servo#6934]
This needs some uncommenting in a WebIDL file and judicial use of the `event_handler!` macro in the Rust implementation. We should then run the appropriate tests using `./mach test-wpt tests/wpt/web-platform-tests/workers` and see what changes.

Relevant code: components/script/dom/webidls/Worker.webidl, components/script/dom/worker.rs

**Comment by JoshTheGoldfish** [comment]
@jdm, I'd like to check this one out. This would be my first time contributing to an open source project, and my first time using Rust for anything non-trivial. So far, I've cloned the repo, did a build, and ran those tests with the following results:

 ```
Joshuas-MBP:servo JoshuaErney$ ./mach test-wpt tests/wpt/web-platform-tests/workers
Error running mach:

    ['test-wpt', 'tests/wpt/web-platform-tests/workers']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory

  File "/Users/JoshuaErney/Documents/Projects/servo/servo/python/servo/testing_commands.py", line 240, in test_wpt
    self.ensure_wpt_virtualenv()
  File "/Users/JoshuaErney/Documents/Projects/servo/servo/python/servo/testing_commands.py", line 329, in ensure_wpt_virtualenv
    subprocess.check_call([virtualenv, "-p", python, virtualenv_path])
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
```

Is this expected? Any guidance would be appreciated.

**Comment by jdm** [comment]
It looks like you're missing a virtualenv installation. See the list of prerequisites at https://github.com/servo/servo/#prerequisites!

**Comment by wilmoz** [comment]
Can I take this?

**Comment by JoshTheGoldfish** [comment]
I guess it's up to @jdm. I've been doing research on this one for the past week, though.

**Comment by jdm** [comment]
@JoshTheGoldfish got here first; if they're still working on it, then I'm happy to encourage that. Sorry @wilmoz!

**Comment by wilmoz** [comment]
Ok, no problem, i'll search for other

**Comment by jdm** [comment]
Still working on this, @JoshTheGoldfish?

**Comment by JoshTheGoldfish** [comment]
@jdm: Yes, though I have quite a few questions. What's the best way to get in touch with you? Here, or the IRC?

**Comment by Ms2ger** [comment]
Either will work, though IRC might be faster.
