### ISSUE TITLE
Use is_int32/is_number in handle_evaluate_js

### ISSUE THREAD

**Issue by khflab** [servo/servo#6941]
Working on #6756 I saw that we already have [is_int32](https://github.com/servo/rust-mozjs/blob/master/src/jsval.rs#L238) and [is_number](https://github.com/servo/rust-mozjs/blob/master/src/jsval.rs#L258).

Is the case to implement another else if?

**Comment by jdm** [comment]
This is being addressed already in #6920, but thanks!
