### ISSUE TITLE
Browsing for a while eventually crashes in IOSurface

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#6952]
STR: Start up Servo, browse for a while, click links, etc. You will eventually crash with an IOSurface error. Sometimes tiles get switched around before the crash.

I suspect an IOSurface leak or race.

cc @mrobinson

**Comment by pcwalton** [comment]
Here's another symptom: `thread 'PaintWorker' panicked at 'assertion failed: dst.len() >= len_src', src/libcore/slice.rs:1474`

**Comment by pcwalton** [comment]
Another symptom:

```
Application Specific Information:
*** CFRelease() called with NULL ***

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff926b8208 CFRelease + 40
1   servo                         	0x00000001105f267d platform::macos::surface::IOSurfaceNativeSurface::bind_to_texture::hf4d373bc962f61ccFcc + 205
2   servo                         	0x00000001105f0143 tiling::TileGrid::create_textures::h27e9169979dec40dMSb + 659
3   servo                         	0x000000010f321a52 rendergl::RenderContext::render_3d_context::h6966608047983215034 + 2194
```

**Comment by mrobinson** [comment]
I'm going to take a look at this one today (sorry for the delay, I was out-of-office). I suspect that this might be caused by attempting to reuse framebuffers on OS X. I'll revert that specific change if so.

**Comment by mrobinson** [comment]
@pcwalton, I'm having trouble reproducing this one. Is there a particular page that produces this error more than others? Are you using GPU rasterizaton or CPU rasterization.

**Comment by frewsxcv** [comment]
More info and a concrete example (with GIF) can be found info #7266

**Comment by mrobinson** [comment]
Looks like the issue is that the destination IOSurface of an upload is invalid. During the io-surface-rs upload method, ```IOSurfaceGetBaseAddress``` is returning null.

**Comment by jdm** [comment]
Can't reproduce any more.
