### ISSUE TITLE
Build servo on travis

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#6962]
Right now, [travis just executes `mach make-tidy`](https://github.com/servo/servo/blob/master/.travis.yml)

Is there any reason we don't have travis also build servo? It seems like that could reduce some of the churn for pull requests that fail to compile immediately after they get r+'d.

[rust-lang/rust recently updated their travis config to compile stage1](https://github.com/rust-lang/rust/pull/27028)

**Comment by metajack** [comment]
Travis can't reliably build mozjs. It doesn't have enough memory.

**Comment by frewsxcv** [comment]
Ah, that's unfortunate. I didn't know building mozjs consumed >3GB of memory :(

The only solution I can think of would be to publish servo/mozjs to crates.io, which might not be desirable? If publishing it isn ot desirable, and you don't think this issue can be completed realistically, then this issue can be closed.

**Comment by metajack** [comment]
How does crates.io help here? It does not store binary packages just metadata.

**Comment by frewsxcv** [comment]
Blah, sorry, you're right (I blame my jet lag). Never mind that then

**Comment by frewsxcv** [comment]
For what it's worth, I was curious if anyone in `#jsapi` on Mozilla IRC had any suggestions on reducing memory during compilation:

> 2:25 PM <ehoogeveen> frewsxcv: I'd suggest reducing NUM_JOBS first then
> 2:26 PM <ehoogeveen> frewsxcv: Another thing that might work is to reduce MOZ_FILES_PER_UNIFIED_FILE, though you might get compilation errors if any non-unified bustage has slipped in
> 2:31 PM <ehoogeveen> frewsxcv: Other than using less optimizations, that is (-O1 or -Os probably use a lot less memory during compilation)

**Comment by frewsxcv** [comment]
Now that https://github.com/servo/mozjs/pull/57 has merged, I'll look into this later today

**Comment by metajack** [comment]
rust-mozjs would be the logically next step :)

**Comment by frewsxcv** [comment]
There's currently already a Travis config file, though it appears it might be turned off (considering it hasn't built in a while)?

https://github.com/servo/rust-mozjs/blob/master/.travis.yml

https://travis-ci.org/servo/rust-mozjs/branches

**Comment by jdm** [comment]
Yes, the travis webhook is turned off. If you have the power to do so, feel free to enable it, or let one of us know when it's the right time.

**Comment by frewsxcv** [comment]
Opened a PR: #7915
