### ISSUE TITLE
Track GC pauses somehow.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6968]
For Gecko's code, see the `nsIConsoleService` usage in <https://mxr.mozilla.org/mozilla-central/source/dom/base/nsJSEnvironment.cpp?rev=60b5a53aeb8f#2227>. It'd probably be useful to log this on request.

**Comment by notriddle** [comment]
:hand: I'd like this one.

**Comment by jdm** [comment]
Go for it!
