### ISSUE TITLE
Check if worker threads keep running after devtools client disconnects

### ISSUE THREAD

**Issue by jdm** [servo/servo#6973]
Easy test to see if there's currently a problem:
```html
<script>var w = new Worker('worker.js')</script>
```
```
setInterval(function() { console.log('still alive') }, 1000);
```
Then [connect to the worker global](https://github.com/servo/servo/wiki/Devtools) in FF's devtools, and close the devtools and see if the worker continues logging messages.

**Comment by wilmoz** [comment]
The output of the thread works https://pastebin.mozilla.org/8841718 but apparently there's a problem with the output in the remote console
![captura de pantalla de 2015-08-05 10-15-04](https://cloud.githubusercontent.com/assets/7908418/9089721/3620161a-3b5c-11e5-921a-57bd45631d23.png)

**Comment by jdm** [comment]
Those are just test values; there's no actual problem.

**Comment by jdm** [comment]
That linked output doesn't seem to include closing the devtools connection, does it?

**Comment by wilmoz** [comment]
I've update the message

**Comment by jdm** [comment]
Perfect! I guess this is not a problem like I thought it would be.
