### ISSUE TITLE
Address XXX comment about JS_GetPropertyDescriptorById in getOwnPropertyDescriptor

### ISSUE THREAD

**Issue by jdm** [servo/servo#6984]
JS_GetOwnPropertyDescriptorById [exists](https://github.com/servo/rust-mozjs/blob/master/src/jsapi.rs#L8401) now, so we should make use of it.

Code: components/script/dom/browsercontext.rs

**Comment by Ms2ger** [comment]
Because of this code in `browsercontext.rs`:
```rust
    if (*desc.ptr).obj != target.ptr {
        // Not an own property
        (*desc.ptr).obj = ptr::null_mut();
```
and this code in SpiderMonkey:
```cpp
js::FromPropertyDescriptor(JSContext* cx, Handle<PropertyDescriptor> desc, MutableHandleValue vp)
{
    // Step 1.
    if (!desc.object()) {
        vp.setUndefined();
        return true;
    }
```

… I believe this should be purely refactoring, so I won't be able to ask for a test :)
