### ISSUE TITLE
pyflakes is not being registered into flake8

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#6999]
Steps to reproduce:

1. Add unused Python import
2. Make sure `flake8` and `pyflakes` are not installed locally (to keep things simple)
3. Run `./mach test-tidy` and notice that the unused import does not cause a warning

A little background: Flake8 does not require pyflakes to be installed, and can be run without it. If pyflakes is installed, flake8 will run the checks it provides (like finding unused imports).

It's not working because flake8 utilizes [this](https://gitlab.com/pycqa/flake8/blob/f2b0bb52e5dc94da2d0dbdbbe655956228bf1f22/setup.py#L60) to register pyflakes into its system. Since setup.py doesn't get run on flake8 (since we're doing the hacky method of just adding .whl's to `sys.path`), pyflakes never gets registered into flake8.

The former issues is much more trivial than the latter. I looked into this briefly and couldn't think of an easy solution. Considering the benefits aren't that significant, I'm going to punt on this for now. I'll assign it to myself for now and look into it later. Maybe I'll get proper Python dependency management set up in Servo some day...

**Comment by Ms2ger** [comment]
Maybe the easiest solution would be to run pyflakes manually?

**Comment by frewsxcv** [comment]
That is possibly an option. If we decide to go that route, we might be able to scrap flake8 altogether and just run pyflakes and pep8 separately.

I don't think automating setting a virtual environment with proper installation of Python dependencies should be too difficult. I think that would be the proper solution here, so I'd like to explore that before resorting to expanding the current hacks.
