### ISSUE TITLE
Implement some of the IDL attributes for input

### ISSUE THREAD

**Issue by farodin91** [servo/servo#7004]
Spec: https://www.whatwg.org/html/#htmlinputelement
Code: components/script/dom/webidls/HTMLInputElement.webidl, components/script/dom/htmlinputelement.rs

**Comment by farodin91** [comment]
Are there any Important attributes that aren't implemented if not will look into validations

**Comment by farodin91** [comment]
@jdm ?

**Comment by jdm** [comment]
I apologize for the long wait here. I was hoping to use form validation as a project for some students at NCSU this semester, but it's fine if you've already started working on it; I can find another.

**Comment by farodin91** [comment]
Currently I working on other things. If you want use this as a student project, I can find other issues.

**Comment by nox** [comment]
Most attributes are implemented now.
