### ISSUE TITLE
Tile display list optimization issue on github.com on Retina Mac

### ISSUE THREAD

**Issue by HarryLovesCode** [servo/servo#7018]
Here is Github as of f570da28c29e2cd762fd7743f11b711c18055aac (on Mac OS X 10.10.4)...

<img width="1392" alt="screen shot 2015-08-05 at 9 32 46 pm" src="https://cloud.githubusercontent.com/assets/12660259/9102491/0063a478-3bc1-11e5-8be6-994cb2fcae29.png">

Here is Github as of 11acfbc29fd3412c18b6bf62e51faef5c2435fd3 (also on Mac OS X 10.10.4)...

<img width="1392" alt="screen shot 2015-08-05 at 9 32 20 pm" src="https://cloud.githubusercontent.com/assets/12660259/9102504/35d8694a-3bc1-11e5-808a-21d360b4344e.png">

I apologize since I've not gotten a chance to look at the commits between these two. I'll attempt to track down where this was introduced tomorrow.

**Comment by glennw** [comment]
I suspect https://github.com/servo/servo/pull/6983 - it looks like something being clipped at a tile boundary perhaps.

**Comment by glennw** [comment]
Although, I just checked on my Linux machine with master on github, and it looks fine. If that commit above is the cause, it might be a bug related to retina display scale factors.

**Comment by pcwalton** [comment]
Confirmed on Retina Mac, and confirmed to be tile-based (`-s 2048` makes other things disappear).

**Comment by glennw** [comment]
@pcwalton Thanks - PR referenced above that fixes it, if you have a moment to review.
