### ISSUE TITLE
`mach test-ref` displays warnings

### ISSUE THREAD

**Issue by Yoric** [servo/servo#7031]
As suggested by @SimonSapin, I'm working on this.

**Comment by Yoric** [comment]
I get the following warning:

````
../../tests/reftest.rs:46:26: 46:32 warning: use of deprecated item: superseded by split_first, #[warn(deprecated)] on by default
../../tests/reftest.rs:46     let mut parts = args.tail().split(|e| &**e == "--");
                                                   ^~~~~~
````

I see two solutions here, I don't know which is preferred:
- I can keep `tail` and allow deprecated code;
- or I can switch to `split_first`, which is unstable, and requires me to allow the feature with `#![feature(slice_splits)]`.

I suspect that the latter is better, but I'd like confirmation.

**Comment by metajack** [comment]
@Yoric Yes, we prefer the latter, at least in the servo repo. In dependencies where there is some possibility to keep the crate compiling on stable Rust, we try to do it, but for Servo, we use all the unstable features.
