### ISSUE TITLE
Vertical margin for position=fixed elements is missing

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7035]
Relevant to #782
# Code

``` html
<html>
  <head>
    <style>
    .container {
      display: block;
    }
    #fixed {
      background: green;
      position: fixed;
      height: 10px;
      width: 10px;
    }
    </style>
  </head>
  <body>
    <div class="container">
      <div id="fixed"></div>
    </div>
    <script>
      var element = document.getElementById("fixed");
      console.log(element.getBoundingClientRect().top);
      console.log(element.getBoundingClientRect().bottom);
    </script>
  </body>
</html>
```
# Gecko

![screen shot 2015-08-06 at 9 55 36 am](https://cloud.githubusercontent.com/assets/416575/9113224/5c0581ec-3c21-11e5-9c77-9ca628bc1a3e.png)
## Log

```
8
18
```
# Servo

![screen shot 2015-08-06 at 9 55 45 am](https://cloud.githubusercontent.com/assets/416575/9113240/70876a22-3c21-11e5-95e7-dfda436ab117.png)
## Log

```
0
10
```

**Comment by frewsxcv** [comment]
I am (attempting) to figure this out

**Comment by pcwalton** [comment]
The problem here is likely either that the hypothetical box is wrong or that we aren't taking it into account for position:fixed. You can see which one it is by changing to position:absolute and seeing if the bug persists.

For more info, search for "hypothetical box" in the CSS 2.1 spec.

**Comment by frewsxcv** [comment]
Bug persists with absolute, so I assume the hypothetical box is wrong

**Comment by frewsxcv** [comment]
With respect to the colored box, should all the values for its fragment.margin be 0?

**Comment by frewsxcv** [comment]
Okay, I have been at this long enough. I guess take a break from it and hopefully it is on the right track.

By definition, "hypothetical box" for the green square should be at 8px,8px because that is where it would be placed if it were static.

One potential problem is the parent `Fragment` (presumably for `<body>`) of the green square's `Fragment`has its vertical margin collapsed  (I think), so its box position is at 0px. If the green square is position=static, the parent `Fragment` has box position at 8px. 

So right now, my best guesses. Either:

1. Somethings is wrong with the collapsed margin algorithm and the margin of the `<body>` fragment should have collapsed (relevant areas of code: [here](https://github.com/servo/servo/blob/3ad49fc689ceb6067cd6dea1aa0d004321704b8e/components/layout/block.rs#L880-L882) and [here](https://github.com/servo/servo/blob/3ad49fc689ceb6067cd6dea1aa0d004321704b8e/components/layout/block.rs#L910-L913))
2. Something needs to happen [here](https://github.com/servo/servo/blob/3ad49fc689ceb6067cd6dea1aa0d004321704b8e/components/layout/block.rs#L826-L828) to set the start position for the green square lower to counter the collapsed vertical margins

If anyone has hints/tips, let me know

**Comment by mrobinson** [comment]
I attempted to fix this bug last year in https://github.com/mrobinson/servo/tree/margin-collapse, but couldn't manage to do it without introducing other regressions. Perhaps my half-done work will be useful for fixing this.

**Comment by mrobinson** [comment]
I think this describes the bug:

```
When an absolutely positioned element has a static position in an
element with margins collapsed-through, the CSS spec says its position
should be defined by top margin (and not the collapsed top and bottom
margin) of the outermost collapsed-through ancestor.
```

**Comment by eefriedman** [comment]
Yes, that looks right.

**Comment by nox** [comment]
This was fixed.

**Comment by nox** [comment]
The latter.
