### ISSUE TITLE
Report memory usage of Stylist in LayoutTaskData

### ISSUE THREAD

**Issue by jdm** [servo/servo#7038]
As part of `collect_reports` in `layout_task.rs`, we should measure the heap usage of the `stylist` member of `LayoutTaskData`. This involves adding `#[derive(HeapSizeOf)]` to `Stylist` in `components/style/selector_matching.rs`, calling `heap_size_of` on the member in `collect_reports`, and fixing any compile errors that result.

**Comment by notriddle** [comment]
:hand: Can I take this one?

**Comment by jdm** [comment]
You bet!

**Comment by notriddle** [comment]
Is this how I'm supposed to be measuring the stuff in rust-selectors (the code in `components/util/mem.rs`)? SelectorMap is a real problem, since it's members are private I can't measure them.

**Comment by SimonSapin** [comment]
If necessary we can always make private fields public, but maybe `HeapSizeOf` and its derive plugin should move to external crates? What do you think @jdm?

**Comment by SimonSapin** [comment]
Note that so far we’ve moved things to separate source repositories when publishing then to crates.io, but we don’t need to.

(Though I think servo users should still get the crate form crates.io rather than through a `path` dependency, to force us to keep the crates.io version up to date.)

**Comment by jdm** [comment]
Yes, I think at this point it makes sense to move the definition of HeapSizeOf, heap_size_of, the plugin, and implementations for the various types from std into an external crate.

**Comment by notriddle** [comment]
So, should I do that? The repo really belongs in the Servo organization.

**Comment by jdm** [comment]
Like @SimonSapin said, it doesn't need to be in a separate repository.

**Comment by jdm** [comment]
I propose a new `components/heapsize`.

**Comment by notriddle** [comment]
So you're suggesting that `components/heapsize` be in the Servo repo, but be published to crates.io?

**Comment by jdm** [comment]
Yep.

**Comment by notriddle** [comment]
If it's to be built as part of Servo, wouldn't that result in two copies of the same crate? One pulled in by rust-selectors from crates.io, and the other from the checked-out repository?

**Comment by SimonSapin** [comment]
That’s why everything should be using it from crates.io, with none of the `Cargo.toml` files having something like `path = "../heapsize"`.

Thinking a bit more about this, this would make CI tricky: to make and use changes to `heapsize` you need to first make a servo/servo PR with the changes, have it go through CI running the entire Servo test suite, then publish it, then make another PR to use it. So maybe it’s not such a good idea after all :)

**Comment by jdm** [comment]
Well, I've made https://github.com/servo/heapsize so we can make PRs against it now.

**Comment by edunham** [comment]
@notriddle Thank you for all the hard work on this PR! 

Since the PR is merged, this issue can probably be closed now.

**Comment by jdm** [comment]
The PR mentioned was separate but related. The work here merely exists in a branch of notriddle/servo so far.

**Comment by KiChjang** [comment]
Is this being worked on by @notriddle or is it actually open to other contributors?

**Comment by notriddle** [comment]
I'm not working on it right now.

**Comment by jdm** [comment]
Fixed by #10088.

**Comment by SimonSapin** [comment]
There are still a couple instances of `#[ignore_heap_size_of = "#7038"]` in `components/style/properties/properties.mako.rs`. @jdm, can these be fixed now?

**Comment by jdm** [comment]
I would expect so.

**Comment by jdm** [comment]
It would be worth filing issues for any in particular that cannot be removed.

**Comment by jdm** [comment]
Unfortunately those cannot be removed because we don't know how to measure Arc values effectively.
