### ISSUE TITLE
Remove support for static HTMLCollection values

### ISSUE THREAD

**Issue by jdm** [servo/servo#7042]
The spec describes [static collections](https://dom.spec.whatwg.org/#concept-collection-static), but in practice those only are required for NodeList values, not HTMLCollection. We should remove the support for static HTMLCollections, since it's unused.

Code: components/script/dom/htmlcollection.rs

**Comment by Wafflespeanut** [comment]
Let's close this :)

**Comment by saneyuki** [comment]
Fixed by #7219
