### ISSUE TITLE
Animation callbacks processed together should receive the same timestamp

### ISSUE THREAD

**Issue by jdm** [servo/servo#7044]
In `Document::run_the_animation_frame_callbacks` we call `Performance::Now()` each time we invoke a callback. This contradicts [the specification](https://html.spec.whatwg.org/multipage/webappapis.html#run-the-animation-frame-callbacks). We can even write a test for this by adding two callbacks with `requestAnimationFrame` and asserting that the timestamp is equal. Use http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/animation-timing/ as a model.

Code: components/script/dom/document.rs

**Comment by HarryLikesCode** [comment]
@jdm I'll take this one. Should the test be added to `tests/wpt/web-platform-tests/animation-timing/callback-invoked.html` or should a separate file be created?

**Comment by jdm** [comment]
A separate file makes sense to me.
