### ISSUE TITLE
Implement DOM-related properties for PerformanceTiming

### ISSUE THREAD

**Issue by jdm** [servo/servo#7045]
There are properties in the [PerformanceTiming spec](https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/NavigationTiming/Overview.html#dom-performancetiming-domloading) that relate to the timing of the document load process. We should store the time at which the relevant operations occur, and make the getters for PerformanceTiming fetch those values from the document (which should be stored as a `JS<Document>` field in `PerformanceTiming` for convenience). See `DocumentProgressHandler` for a useful place to start timing these things.

Code: components/script/dom/webidls/PerformanceTiming.webidl, components/script/dom/performancetiming.rs, components/script/document.rs

**Comment by g-k** [comment]
![image](https://cloud.githubusercontent.com/assets/226605/9215853/684f8c48-407e-11e5-921b-52b7449b7b77.png)

**Comment by jdm** [comment]
Yours!

**Comment by g-k** [comment]
Questions!

Is https://github.com/servo/servo/compare/master...g-k:perf-timing-dom-props going in the right direction?

Should I store `domLoading` etc. in `PerformanceTiming` with type `JS<Document>` or `u64` or something else?

Should those properties be args to the `PerformanceTiming` constructor? If so, what should they default to until they're set?

**Comment by jdm** [comment]
Yes, that looks like the right direction. However, it doesn't make sense to store them in values in PerformanceTiming; the values may not be available at the time it's created, and we would need to store them somewhere anyways in case PerformanceTiming is created sometime after they become available. Therefore, storing them in Document makes the most sense to me, as I originally described in the first comment.

**Comment by KiChjang** [comment]
Fixed by #7242.
