### ISSUE TITLE
Unnecessary mutability in window.rs

### ISSUE THREAD

**Issue by jdm** [servo/servo#7048]
From our gonk build:
```
src/window.rs:653:13: 653:27 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
src/window.rs:653         let mut hwc_device: *mut hwc_composer_device;
                              ^~~~~~~~~~~~~~
src/window.rs:678:13: 678:26 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
src/window.rs:678         let mut alloc_dev: *mut alloc_device;
                              ^~~~~~~~~~~~~
```
Code: ports/gonk/src/window.rs

**Comment by fitzgen** [comment]
I think this is a rustc bug. Both variables are reassigned in the blacks following their declaration.

As a reduced test case, remove `mut` here and compilation fails: http://is.gd/qep4FT

**Comment by jdm** [comment]
As a counterpoint, I submit the following program which compiles without the use of mut:
```rust
fn main() {
    let x;
    unsafe {
        x = 2;
    }
    println!("Hello, world! {}", x);
}
```

**Comment by jdm** [comment]
In both of the cases that are warned about, the variables aren't reassigned - they are merely assigned an initial value separately from when they are declared.

**Comment by fitzgen** [comment]
I was totally misreading error messages. Nevermind!

**Comment by fitzgen** [comment]
I have a fix coming up.
