### ISSUE TITLE
Stop calling `handleEvent` on event handlers.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7065]
Note: this affects only `on*` properties, not `addEventListener`.

The issue seems to be the `EventListener::new` call in `set_event_handler_common`.

- Code: `components/script/dom/eventtarget.rs`.
- Test: `tests/wpt/web-platform-tests/websockets/interfaces/WebSocket/events/013.html` and hopefully others.

**Comment by Ms2ger** [comment]
Currently, we have an `EventListenerType` enum that distinguishes between the two kinds of event listeners:
* `Additive` for those added by `addEventListener`, which takes an `EventListener?` argument;
* `Inline` for those added by setting `onfoo` attributes, which are of type `EventHandler` (a typedef for `EventHandlerNonNull?`).

In JavaScript, both of those kinds are represented by an object or null, and we use that knowledge to represent them both as `Option<Rc<EventListener>>` internally. When an event is dispatched, we invoke either kind by calling `EventListener::HandleEvent_` (this is done in `components/script/dom/eventdispatcher.rs`).

However, those two kinds of event listeners should be invoked differently. In the case of an `EventListener`, an object `{ handleEvent: function() {} }` should have its `handleEvent` method called, while such an object would simply be ignored in the case of an `EventHandler`.

I believe the best way to solve this issue would be to change the value in the `Inline` variant of the `EventListenerType` enum from `Rc<EventListener>` to `Rc<EventHandler>`, and implement a method on `EventListenerType` that calls `EventListener::HandleEvent_` or `EventHandler::Call_`, depending on its variant.

**Comment by Wafflespeanut** [comment]
Let's close this :)
