### ISSUE TITLE
Absolutely positioned elements should only be stacking contexts if z-index is not auto

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7069]
```
<!DOCTYPE html>

<html>
  <body>
      <div style="background: red;   position: absolute; height: 40px; width: 40px; top: 10px; left: 10px;"></div>
      <div style="background: green; position: relative; height: 40px; width: 40px; top: 20px; left: 20px;"></div>
  </body>
</html>
```

Difference between Gecko and Servo:

<img width="501" alt="screen shot 2015-08-07 at 12 52 28" src="https://cloud.githubusercontent.com/assets/373579/9134316/502e2db4-3d03-11e5-8f30-08c3554ea898.png">

**Comment by pcwalton** [comment]
Yeah, this is because we unconditionally make stacking contexts out of absolutely positioned elements.

**Comment by pcwalton** [comment]
I have a fix for this that I'm testing now.
