### ISSUE TITLE
Painting issue: missing text and half a div

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7074]
Using `servo -o img.png` with the following code, I get the expected rendering. But with the regular glutin window (osx), painting is messed up:

<img width="775" alt="screen shot 2015-08-07 at 15 19 46" src="https://cloud.githubusercontent.com/assets/373579/9136730/3737acc0-3d19-11e5-93bf-1314d861a5a2.png">

```
<!DOCTYPE html>

<html>

  <style>
    body > div {
      position: absolute;
      top: 0;
      background: #EEE;
      padding: 0 30px
    }
  </style>

  <body style="margin:0">
    <div style="left: 0;"> 
      <div>0</div>
      <div>1</div>
      <div>2</div>
      <div>3</div>
      <div>4</div>
      <div>5</div>
      <div>6</div>
      <div>7</div>
      <div>8</div>
      <div>9</div>
    </div>
    <div style="left: 100px;"> 
      <div>0</div>
      <div>1</div>
      <div>2</div>
      <div>3</div>
      <div>4</div>
      <div>5</div>
      <div>6</div>
      <div>7</div>
      <div>8</div>
      <div>9</div>
    </div>
    <div style="left: 200px;"> 
      <div>0</div>
      <div>1</div>
      <div>2</div>
      <div>3</div>
      <div>4</div>
      <div>5</div>
      <div>6</div>
      <div>7</div>
      <div>8</div>
      <div>9</div>
    </div>

  </body>

</html>

```

**Comment by HarryLovesCode** [comment]
Looks like a duplicate of this: #7018 which was supposed to have been resolved by this: #7021.

Try running Servo with the `-s` flag set to...

- 128
- 256
- 512

and see if the output changes each time. If so, then that would confirm the issue was not resolved. I'll test your example in a few minutes after master builds on my Mac.

**Comment by HarryLovesCode** [comment]
@paulrouget You must be using an outdated version of Servo. The issue was indeed fixed ~8 hours ago. 
<img width="912" alt="screen shot 2015-08-07 at 10 28 39 am" src="https://cloud.githubusercontent.com/assets/12660259/9137954/1ea78f4c-3cef-11e5-89a9-6b88337ed26e.png">

**Comment by paulrouget** [comment]
Updated. It's indeed fixed. Thanks.
