### ISSUE TITLE
Some reftests aren't being run

### ISSUE THREAD

**Issue by jdm** [servo/servo#7077]
We have a reftest for CSS background images, for example, but it's not in basic.list.

* background_image_a.html/background_image_ref.html
* canvas_linear_gradient_a.html/canvas_linear_gradient_ref.html
* canvas_radial_gradient_a.html/canvas_radial_gradient_ref.html
* overflow_position_abs_inside_normal_a.html/overflow_position_abs_inside_normal_b.html
* verflow_position_abs_simple_a.html/overflow_position_abs_simple_b.html
* style_is_in_doc.html/style_is_in_doc_ref.html
* table_specified_width_a.html/table_specified_width_ref.html
* text_shadow_multiple_shadows_a.html/text_shadow_multiple_shadows_ref.html
* white_space_intrinsic_sizes_a.html/white_space_intrinsic_sizes_ref.html

Code: tests/ref/basic.list

**Comment by frewsxcv** [comment]
> background_image_a.html/background_image_ref.html aren't being tested

Related to https://github.com/servo/servo/issues/1516

I was going to complete it, but it is partially not working due to https://github.com/servo/servo/issues/7035

**Comment by jdm** [comment]
I would like to make sure all of these are added to basic.list; if the tests pass, that's great. If they don't, then let's file issues and leave them commented out.

**Comment by frewsxcv** [comment]
So right now, we use two binary operators to indicate passing status. `==` indicates expected success. `!=` indicates expected failure. It might be helpful to have another binary operator that indicates it should be successful, but currently fails (something like `~~` or `--` ?). This might allow us to complete #7078/#7118 sooner. Thoughts?

**Comment by frewsxcv** [comment]
...or use `!=` and add a comment indicating it should pass

**Comment by jdm** [comment]
That's what flaky_cpu means, I'm pretty sure.

**Comment by jdm** [comment]
Sorry, that's not actually true. I think rather than adding a new operator I would prefer to port failing tests to the WPT framework (eg. #7126) where we can mark them as expected fails.

**Comment by Ms2ger** [comment]
In the interest of having this finished quickly, adding it with the wrong operator and a TODO comment seems the way to go.
