### ISSUE TITLE
to_owned() should be used instead of to_string() in hosts.rs

### ISSUE THREAD

**Issue by boghison** [servo/servo#7093]
/home/boghison/Projects/servo/components/net_traits/hosts.rs:54:35: 54:63 error: str.to_owned() is more efficient than str.to_string(), please use it instead, #[deny(str_to_string)] on by default
/home/boghison/Projects/servo/components/net_traits/hosts.rs:54                 host_table.insert(token.to_owned().to_string(), address.clone());

**Comment by jdm** [comment]
Does this happen on master for you?

**Comment by boghison** [comment]
@jdm Yes.

**Comment by boghison** [comment]
@jdm I just recompiled with the original code. For some reason, it doesn't print that anymore. Any idea why? This is really weird.

**Comment by boghison** [comment]
[Still](https://github.com/servo/servo/blob/master/components/plugins/lints/str_to_string.rs)

**Comment by jdm** [comment]
I can only reproduce this with the following diff:
```
diff --git a/components/net_traits/Cargo.toml b/components/net_traits/Cargo.toml
index c88b130..6a0fc69 100644
--- a/components/net_traits/Cargo.toml
+++ b/components/net_traits/Cargo.toml
@@ -14,6 +14,9 @@ features = [ "serde-serialization" ]
 [dependencies.util]
 path = "../util"

+[dependencies.plugins]
+path = "../plugins"
+
 [dependencies.msg]
 path = "../msg"

diff --git a/components/net_traits/lib.rs b/components/net_traits/lib.rs
index e4cdb25..61bd8d3 100644
--- a/components/net_traits/lib.rs
+++ b/components/net_traits/lib.rs
@@ -10,7 +10,7 @@
 #![feature(step_by)]
 #![feature(vec_push_all)]
 #![plugin(serde_macros)]
-
+#![plugin(plugins)]
 #![plugin(regex_macros)]

 extern crate euclid;
diff --git a/components/servo/Cargo.lock b/components/servo/Cargo.lock
index 82c9e66..1903739 100644
--- a/components/servo/Cargo.lock
+++ b/components/servo/Cargo.lock
@@ -951,6 +951,7 @@ dependencies = [
  "ipc-channel 0.1.0 (git+https://github.com/pcwalton/ipc-channel)",
  "log 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)",
  "msg 0.0.1",
+ "plugins 0.0.1",
  "png 0.1.0 (git+https://github.com/servo/rust-png)",
  "regex 0.1.41 (registry+https://github.com/rust-lang/crates.io-index)",
  "regex_macros 0.1.21 (registry+https://github.com/rust-lang/crates.io-index)",
```

**Comment by boghison** [comment]
@jdm Oh yes, you're right. I cloned my servo fork again, but didn't notice I was doing it in the same directory. The issue is still valid though, because to_owned() should be used instead of to_string(), shouldn't it?

**Comment by boghison** [comment]
OK, closing this as it was caused by my changes, so I'll just fix this with a PR
