### ISSUE TITLE
Handle 'currentColor' CSS color value when setting Canvas2D fillstyle/strokestyle

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#7106]
https://drafts.csswg.org/css-color/#currentcolor-color

The problem is that it should return the value of the color property at used value time, which the CSS parser doesn't know. We also don't want to pass it in, since computing used values involves flushing layout.  The other obvious option is that the parser should just signal that it was currentColor with an enum and let servo handle it. Thoughts? @SimonSapin

**Comment by SimonSapin** [comment]
http://doc.servo.org/style/properties/struct.ComputedValues.html#method.resolve_color already deals with this. What’s missing?

**Comment by SimonSapin** [comment]
> since computing used values involves flushing layout

"Used value" is kind of a fuzzy concept. In the case of `currentColor`, it’s mostly used as “not the thing that’s inherited in e.g. `border-top-color: inherit`”. (The thing that’s inherited is the computed value.) For some properties and values like `height: auto`, yes, determining the used value requires doing some layout. But for `<color>` specifically, the `ComputedValues` struct has all the information it needs to determine the used value. (Perhaps `ComputedValues::resolve_color` should be renamed `get_used_color_value` or something.)

**Comment by jdm** [comment]
The reason behind this filing is three tests in 2dcontext/fill-and-stroke-styles/ that use currentColor as fillStyle and currently fail to pass.

**Comment by dzbarsky** [comment]
Yep, jdm is right. Style handles this correctly, but canvas just invokes the css parser.  That's why I want the parser to tell it the value is `currentColor`, so it can go check the `ComputedValues`.

**Comment by dzbarsky** [comment]
Ah, I see the parser already does what I suggested, the issue is that http://mxr.mozilla.org/servo/source/components/script/dom/canvasrenderingcontext2d.rs#1149 doesn't handle it.  I'll fix that.

**Comment by SimonSapin** [comment]
Thank jdm, I was missing some context. Which tests are these specifically? What’s their expected results? Do they pass in other browsers?

https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-fillstyle links to https://html.spec.whatwg.org/multipage/infrastructure.html#parsed-as-a-css-color-value , which doesn’t mention `currentColor` at all.

https://drafts.csswg.org/css-color/#currentcolor-color says "The keyword currentcolor
takes its value from the value of the color property on the same element.", but I’m pretty sure the spec editor had in mind the keyword currentcolor used in a CSS property declaration (that applies to a (pseudo-)element). When the HTML spec says a string is "parsed as a CSS <color> value", there is no associated element.

**Comment by dzbarsky** [comment]
The spec assumes that the associated element is the canvas element.
From tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.basic.html:
```
canvas.setAttribute('style', 'color: #0f0');
ctx.fillStyle = '#f00';
ctx.fillStyle = 'currentColor';
ctx.fillRect(0, 0, 100, 50);
```
This draws a green rect in firefox, chrome, and safari.

**Comment by dzbarsky** [comment]
There's also tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.gradient.object.current.html, which does 
```
canvas.setAttribute('style', 'color: #f00');
var g = ctx.createLinearGradient(0, 0, 100, 0);
g.addColorStop(0, 'currentColor');
 g.addColorStop(1, 'currentColor');
 ctx.fillStyle = g;
 ctx.fillRect(0, 0, 100, 50);
```
This draws a black rectangle in Safari and Chrome (so it gets the current color from the canvas), and throws an error in Firefox.

**Comment by SimonSapin** [comment]
Alright, I found the bit of spec that defines this. It doesn’t have a more specific anchor, so search for "Whenever the CSS value currentColor is used as a colour in the CanvasRenderingContext2D API" in https://html.spec.whatwg.org/multipage/scripting.html#2dcontext

**Comment by SimonSapin** [comment]
Closer anchor: https://html.spec.whatwg.org/multipage/scripting.html#2dcontext:canvasrenderingcontext2d-22

**Comment by dzbarsky** [comment]
Thanks for tracking this down, I will update the PR.

**Comment by dzbarsky** [comment]
Fixed.
