### ISSUE TITLE
Actor::handle_message should return an enum instad of a boolean

### ISSUE THREAD

**Issue by jdm** [servo/servo#7110]
Boolean constants (true/false) are always harder to understand than two-variant enums with meaningful names. In this case, we want `Processed` and `Ignored` (true and false respectively).

Code: components/devtools/actor.rs

**Comment by oppenlander** [comment]
I can try doing this.

Should the interface stay the same? 
It doesn't seem like the `Err` part of the `Result` is being used anywhere.

**Comment by HarryLovesCode** [comment]
@jdm correct me if I misunderstood

---

@oppenlander, I believe what we want is something like this:

```rust
fn handle_message(&self,
                  _: &ActorRegistry,
                  _: &str,
                  _: &json::Object,
                  _: &mut TcpStream) -> Result<bool, ()> {
    // This is probably a bad example since we do nothing
    // to process the message, but we return `true` anyways.
    // This definitely illustrates what jdm is saying here.
    Ok(true)
}
```

to be replaced with this:

```rust
fn handle_message(&self,
                  _: &ActorRegistry,
                  _: &str,
                  _: &json::Object,
                  _: &mut TcpStream) -> MessageHandled {
    MessageHandled::Ignored
}
```

most likely to align with [this](https://wiki.mozilla.org/Remote_Debugging_Protocol#Packets) which says...

> Clients should silently ignore packet properties they do not recognize. We expect that, as the protocol evolves, we will specify new properties that can appear in existing packets, and experimental implementations will do the same.

This tripped me up yesterday which is why I totally agree with this change.

**Comment by oppenlander** [comment]
@HarryLovesCode Wouldn't ignored package properties be referencing properties on the message payload? 
That portion of the documentation seems orthogonal to this task.

@jdm To be more clear, I was asking if you want:
```rust
fn handle_message(&self,
                  _: &ActorRegistry,
                  _: &str,
                  _: &json::Object,
                  _: &mut TcpStream) -> MessageHandled {
    MessageHandled::Ignored
}
```
or
```rust
fn handle_message(&self,
                  _: &ActorRegistry,
                  _: &str,
                  _: &json::Object,
                  _: &mut TcpStream) -> Result<MessageHandled, ()> {
    Ok(MessageHandled::Ignored)
}
```
I can see merits to keeping the return type a `Result`, so in the future a `MessageError` type can be created, which `Actor`s can return. 
Refactoring `Result<MessageHandled, ()>` to `Result<MessageHandled, MessageError>` seems a lot easier than `MessageHandled` to `Result<MessageHandled, MessageError>`.

**Comment by jdm** [comment]
Agreed. I'm looking for `Result<MessageHandled, ()>`.

**Comment by jdm** [comment]
Oh, sorry, looks like there's already a PR in #7119.

**Comment by jdm** [comment]
Thanks for fixing this @fabricedesre!
