### ISSUE TITLE
Check for simple Rust style nits in tidy.py

### ISSUE THREAD

**Issue by jdm** [servo/servo#7111]
As an example, we should be able to easily report instances of:
* `,[A-Za-z0-9]` (there should be a space following a comma)
* `[A-Za-z0-9][+-/*%=]` (there should be a space preceding an operator)
* `[+-/*%=][A-Za-z0-9]` (there should be a space following an operator)
* `)->` (there should be a space before `->` in a function return type)
* `->[A-Za-z]` (there should be a space after `->` in a function return type)

Code: python/tidy.py

**Comment by Ms2ger** [comment]
* There should not be a space preceding a colon

**Comment by jdm** [comment]
* `[A-Za-z0-9)]{` (there should be a space before an open brace)

**Comment by jdm** [comment]
* any line with a `use` statement that contains a `{` but does not contain a `}` (we don't like multiline use statements)

**Comment by metajack** [comment]
Before/after operators and `->` it might be a newline.

**Comment by metajack** [comment]
Well, some subset of those could be a newline.

**Comment by jdm** [comment]
The prevailing style I've seen is that -> goes on the same line as the return type.

**Comment by jdm** [comment]
Also note that I've only given patterns that we want to flag as incorrect, so I don't think newlines are a problem.

**Comment by wilmoz** [comment]
I take this

**Comment by jdm** [comment]
Great!

**Comment by wilmoz** [comment]
@jdm for the case "there should be } in the same line", the output message could be "there should be } in the same line"?

**Comment by jdm** [comment]
"use statements should not span more than one line" is probably more clear.
