### ISSUE TITLE
Check that consecutive use statements in Rust files are in alphabetical order

### ISSUE THREAD

**Issue by jdm** [servo/servo#7112]
I propose the following rule:
* for each Rust source file, look at every line
* if the whitespace-stripped line starts with `use `, append the path up to any `{` to _imports_
* if the line is empty
  * let _sorted_ be _imports_ sorted alphabetically
  * if _sorted_ and _imports_ differ, report the first import that does not match
  * reset _imports_ to the empty list

This allows us to retain our sorted lists that are separated by whitespace that currently exist today.

Code: python/tidy.py

**Comment by tafia** [comment]
Tried to address it in #7265

This is my first python, so it may not be very standard.

I didn't search for empty line, rather checked the *imports* length (works if there something else than use).

One area where may need to reconsider: if the very last import is supposed to be at the first place, all other imports being ordered then the entire block yields warning.

**Comment by jdm** [comment]
Thank you so much, @tafia!

**Comment by tafia** [comment]
You're welcome!
