### ISSUE TITLE
servo includes serde_macros twice

### ISSUE THREAD

**Issue by metajack** [servo/servo#7130]
Versions 0.5.0 and 0.4.4.

We need to find where the dupe is coming from and fix it. Probably an inconsistent dependency line in some Cargo.toml.

**Comment by g-k** [comment]
`mach update-cargo -a` normalized serde_macros to 0.5.1 for me.

**Comment by jdm** [comment]
Want to submit a PR for that? :)

**Comment by g-k** [comment]
Sure, I didn't know if something updated them periodically.

**Comment by frewsxcv** [comment]
Fixed in #7164
