### ISSUE TITLE
Add a flexible target configuration for B2S/Gonk

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#7138]
Rust has support for flexible target configurations:
https://doc.rust-lang.org/stable/reference.html#conditional-compilation
https://github.com/rust-lang/rfcs/pull/131

These are also supported in Cargo:
https://github.com/rust-lang/cargo/pull/1396

I'd like to use a specific configuration for Gonk here, instead of just piggybacking on the Android one. This would enable the use of `#[cfg(target_os="gonk")]` where today we rely on putting any Gonk-specific code in Gonk-only modules.

**Comment by nox** [comment]
I'm *pretty* sure we can close this.

**Comment by larsbergstrom** [comment]
Done.
