### ISSUE TITLE
Passing unknown debug option (-Z) should cause error

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7142]
How rustc behaves:

```
> rustc -Z helloworld
error: unknown debugging option: `helloworld`
```

How servo behaves:

```
./mach run -d -Z helloworld /tmp/hi.html
<no error here, window appears>
```

Relevant file: [components/util/opts.rs](https://github.com/servo/servo/blob/master/components/util/opts.rs)

**Comment by jdm** [comment]
I suspect the best way to deal with this is to create a DebugOptions struct with boolean members for each option, create a function which takes the string of debug options (https://github.com/servo/servo/blob/master/components/util/opts.rs#L325) and returns `Result<DebugOptions, String>`, and reports any Err value returned as an unrecognized option.

**Comment by g-k** [comment]
dibs?

**Comment by jdm** [comment]
It's yours!

**Comment by Wafflespeanut** [comment]
#7165 closes this.

**Comment by frewsxcv** [comment]
Yep. Thanks @g-k! :sparkles:
