### ISSUE TITLE
Items in scrollable layers can be clipped incorrectly.

### ISSUE THREAD

**Issue by glennw** [servo/servo#7153]
The code that clips items is here:

https://github.com/servo/servo/blob/master/components/layout/display_list_builder.rs#L925

An example of what happens:

* A scroll layer has height 2000, with visible height of 768.
* The first tile paints at 512x512 correctly.
* The second tile paints at 512x512 and correctly clips items in the code above that are outside the 768 pixel enclosing rect.
* When you scroll, the compositor doesn't ask for the 2nd tile to be repainted, as it hasn't changed.

This means that items clipped during the first render never get added to the display list as you scroll.

We could potentially force a repaint, but isn't this what the display port code should be handling? Perhaps we should just remove the clipping above and rely on the display port clipping?

cc @pcwalton

**Comment by pcwalton** [comment]
I think that for display items that belong to an overflow:scroll layer, we should just remove that clipping "optimization", since we will need them if the scroll happens.
