### ISSUE TITLE
position:absolute are not stacked properly if another elements is position:fixed

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7166]
```html
<div style="position:absolute;z-index:2;width:100px;height:100px;background:red"></div>
<div style="position:absolute;z-index:1;top:50px;left:50px;height:100px;width:100px;height:100px;background:green"></div>
<div style="position:fixed;"></div>
```

Without the last div, the 2 first divs are stacked according to their `z-index`. Whit the last div, the 2 first divs are stacked according to their position in the DOM.

<img width="440" alt="screen shot 2015-08-12 at 11 38 11" src="https://cloud.githubusercontent.com/assets/373579/9221065/8a2d297e-40e7-11e5-966f-8335deaa45b7.png">

**Comment by waddlesplash** [comment]
@jdm: Shouldn't this also have `I-wrong` too?

**Comment by pcwalton** [comment]
Yeah, this is because we're too layer-happy with our `LAYERS_NEEDED_FOR_POSITIONED_DESCENDANTS` infrastructure. See #2006

**Comment by pcwalton** [comment]
I have a fix for this that I'm testing now.
