### ISSUE TITLE
Implement the WebSocket close event.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7168]
Blocks #6060 

* Spec: <https://html.spec.whatwg.org/multipage/#feedback-from-the-protocol> ("When the WebSocket connection is closed…").
* Code: `components/script/dom/websocket.rs`.
* Test: various under `tests/wpt/web-platform-tests/websockets/`.

**Comment by fabricedesre** [comment]
Isn't it done at https://github.com/servo/servo/blob/master/components/script/dom/websocket.rs#L205 and https://github.com/servo/servo/blob/master/components/script/dom/websocket.rs#L357

This seems to follow the spec.

**Comment by Ms2ger** [comment]
Indeed so. Not sure what convinced me otherwise.
