### ISSUE TITLE
`load_url` ignores the URL if it has a fragment

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7169]
```html
<a href="http://www.example.com/#foo">test</a>
<div style="height: 1000px"></div>
<p id=foo>Blah</p>
<div style="height: 1000px"></div>
```
Clicking the link goes straight to the `p` element rather than visiting `example.com`.

**Comment by notriddle** [comment]
Can I take this one?

**Comment by SimonSapin** [comment]
@notriddle Sure!

This probably involves something like `link_url.scheme == document_url.scheme && link_url.scheme_data == document.url.scheme_data && link_url.query == document_url.query` (compare every component but the fragment).
