### ISSUE TITLE
need easy way to change number of particles on physics demo

### ISSUE THREAD

**Issue by metajack** [servo/servo#7173]
Maybe a slider?

cc @gordonbrander

**Comment by gordonbrander** [comment]
I've implemented this a couple of ways, but am running into problems with Servo that are preventing me from moving ahead:

- Implemented with `<input type="range">`, but we don't support that yet.
- Implemented by binding `click` event handlers to a number of `<a>` elements, each with a workload size. Clicking them will set that workload size. Unfortunately, Servo ignores the click handler.

@pcwalton could you advise on the best approach here?

**Comment by jdm** [comment]
Other elements besides `<a>` should work.

**Comment by gordonbrander** [comment]
I tried a span. It did not work. Note that these elements are positioned absolute. Should that make a difference?

**Comment by jdm** [comment]
```html
<span id="s">hi there</span>
<span id="s2">hi there</span><br>
<span id="s4" onclick="alert('clicked')">hi there</span>
<span style="position: absolute" id="s3">hi there</span>
<script>document.getElementById('s').addEventListener('click', function() { alert('hi') }, false);</script>
<script>document.getElementById('s2').onclick = function() { alert('hi') }</script>
<script>document.getElementById('s3').addEventListener('click', function() { alert('hi') }, false);</script>
```
All of these triggered for me in Servo when I clicked on them.

**Comment by metajack** [comment]
We're going to defer this for the demo deadline since no suitable easy solutions were found. Workarounds exist so that I'll have what I need next week.

**Comment by nox** [comment]
@metajack Do we still need this?

**Comment by metajack** [comment]
Nah
