### ISSUE TITLE
Can't derive HeapSizeOf for types with type arguments that don't derive HeapSizeOf

### ISSUE THREAD

**Issue by boghison** [servo/servo#7193]
Ex. TextInput

**Comment by notriddle** [comment]
I don't think that's a bug; if the subtype doesn't implement HeapSizeOf, then there's no way to be sure it's an exhaustive heap size.

**Comment by boghison** [comment]
We have ignore_heap_size_of that doesn't work

**Comment by jdm** [comment]
@notriddle: Yes, the derive should only be operating on the actual fields of a type, not looking at all of the type arguments just in case.

**Comment by notriddle** [comment]
I understand.

**Comment by frewsxcv** [comment]
This compiles fine:

```rust
#![feature(custom_derive, plugin, custom_attribute)]
#![plugin(heapsize_plugin)]

extern crate heapsize;

use heapsize::HeapSizeOf;
use std::marker::PhantomData;

#[derive(HeapSizeOf)]
struct SomeStruct<T>{
    _a: PhantomData<T>,
}
```

Is this issue still valid?

**Comment by boghison** [comment]
Idk

**Comment by nox** [comment]
@frewsxcv https://github.com/servo/heapsize/pull/22

**Comment by frewsxcv** [comment]
@nox So this can be closed?

**Comment by nox** [comment]
I think so.
