### ISSUE TITLE
Replace uses of `for foo in bar.iter()` and `for foo in bar.iter_mut()`

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7197]
`for foo in bar.iter()` can always be replaced with `for foo in &bar`, often even `for foo in bar`. With `iter_mut` we should use `&mut bar`

We do this a lot throughout Servo, see https://manishearth.pastebin.mozilla.org/8842698

It's advisable to do this with `sed` or some other tool, but manually fixing them works too (that way you can check if the `for foo in bar` method will work)

**Comment by jxs** [comment]
i can also take this one if no one else is on it

**Comment by jdm** [comment]
It's yours!
