### ISSUE TITLE
Use `is_empty()` instead of `.len() == 0`

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7198]
`foo.len() == 0` can usually be replaced by `foo.is_empty()`.

https://manishearth.pastebin.mozilla.org/8842704 is a list of all the uses grep could find

It's advisable to do this with sed or some other tool.

**Comment by jxs** [comment]
can i do this one?

**Comment by Manishearth** [comment]
Sure!

**Comment by Manishearth** [comment]
(oh, you already did it :smile: )
