### ISSUE TITLE
*.cargo files should get linted

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7201]
Steps to complete this:

1. Add it to the `filetype_to_check` list [in here](https://github.com/servo/servo/blob/master/python/tidy.py)
2. Make the appropriate changes to make it pass the tidy checker (`./mach test-tidy`)
 If it complains about a license, just copy and paste [this](https://github.com/servo/servo/blob/2e1ca10eeaf6a62326c1b864345f624ed2974a52/python/tidy.py#L1-L8)

**Comment by frewsxcv** [comment]
So I just learned that Makefiles require tab characters on certain lines, which makes this not as trivial as I thought. It might be best just to close this, unless we just want to ignore tab characters on certain filetypes

**Comment by jdm** [comment]
Yeah, I don't think the effort involved here is worth the benefit.
