### ISSUE TITLE
files in `ports/cef/` should get linted

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7202]
It is marked as being 'upstream' (which is not the case as far as I know) so we currently don't lint it

Steps to complete this:

1. Delete [this line](https://github.com/servo/servo/blob/2e1ca10eeaf6a62326c1b864345f624ed2974a52/python/tidy.py#L43)
2. Clean up all tidy issues brought up by `./mach test-tidy`

**Comment by jdm** [comment]
The vast majority of the code is automatically generated, and we can't just replace the license because it's generated from the CEF C++ header. I don't think this is worth the effort.

**Comment by frewsxcv** [comment]
Sounds good. Just for my own knowledge, the only code that is autogenerated lives in `ports/cef/interfaces/`, right? As opposed to all the `*.rs` files in `ports/cef/`

**Comment by jdm** [comment]
That does seem to be the case, from my brief poking around.

**Comment by zmike** [comment]
That's correct.

**Comment by SimonSapin** [comment]
When changing the ignored pattern from ports/cef/* to ports/cef/interfaces/*, mach test-tidy currently gives 365 lines of output. Most of it is about whitespace. An extract:

```
./ports/cef/types.rs:31: missing space before =
./ports/cef/types.rs:31: missing space after =
./ports/cef/types.rs:772: missing space before =
./ports/cef/types.rs:772: missing space after =
./ports/cef/types.rs:810: missing space before =
./ports/cef/types.rs:810: missing space after =
./ports/cef/wrappers.rs:15: Line is longer than 120 characters
./ports/cef/wrappers.rs:36: encountered whitespace following a use statement
./ports/cef/wrappers.rs:196: missing space after ,
./ports/cef/wrappers.rs:197: missing space after ,
