### ISSUE TITLE
Make EventTypeId reflect DOM inheritance hierarchy

### ISSUE THREAD

**Issue by jdm** [servo/servo#7205]
Right now MouseEvent and UIEvent are listed separately, which means that some_mouse_event.is_uievent() will return false. We should make EventTypeId reflect the proper DOM hierarchy, just like EventTargetTypeId/NodeTypeId/ElementTypeId, etc.

Code: components/script/dom/event.rs, components/script/dom/uievent.rs

**Comment by wilmoz** [comment]
I'd like to try this.

**Comment by Ms2ger** [comment]
@wilmoz the `UIEventTypeId` argument should be passed to `new_inherited` only, not to `new`.

**Comment by wilmoz** [comment]
@jdm thanks now everything work, put i assumed "new_uninitialized" use "MouseEvent". here the code https://pastebin.mozilla.org/8843070

**Comment by Ms2ger** [comment]
You'll need to add `UIEvent` as another variant to `UIEventTypeId`, since `UIEvent` can be the most-derived class of an object. There's some documentation at <http://doc.servo.org/script/dom/index.html>, but nothing about the type ids, I'm afraid.

**Comment by wilmoz** [comment]
@Ms2ger ready :). Could I make a pull request in the documentation?

**Comment by Ms2ger** [comment]
That would be great, yes. Probably in `components/script/dom/mod.rs`?
