### ISSUE TITLE
Generated WebIDL binding code fails for default `double` values in dictionaries

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#7217]
This WebIDL snippet (part of [Touch Events][2]):

```webidl
dictionary TouchInit {
    required long        identifier;
    required EventTarget target;
             double      clientX = 0;
             double      clientY = 0;
             double      screenX = 0;
             double      screenY = 0;
};
```

Causes the following build error:

```
/home/mbrubeck/src/servo/target/debug/build/script-0edb9bcce900a4fc/out/Bindings/TouchBinding.rs:129:21: 129:24 error: mismatched types:
 expected `dom::bindings::num::Finite<f64>`,
    found `_`
(expected struct `dom::bindings::num::Finite`,
    found floating-point variable) [E0308]
/home/mbrubeck/src/servo/target/debug/build/script-0edb9bcce900a4fc/out/Bindings/TouchBinding.rs:129                     0.0
                                                                                                                         ^~~
```

The default value should be `Finite::wrap(0.0)` instead of just `0.0`.

[2]: http://w3c.github.io/touch-events/#touch-interface

**Comment by Ms2ger** [comment]
The code is in `components/script/dom/bindings/codegen/CodegenRust.py`, at the end of `getJSToNativeConversionInfo` in the `if tag in numericTags:` branch. This branch will instead need to be limited to integers, and branches should be added for unrestricted float/double, where the default is used literally, and for restricted float/double, where the default is wrapped in `Finite::wrap()`.

To test, uncomment the relevant `TestDictionaryDefaults` members in `components/script/dom/webidls/TestBinding.webidl`.
