### ISSUE TITLE
Remove the DOMRefCell wrapper around Window::compositor.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7239]
It should be possible to store an `IpcSender<ScriptToCompositorMsg>` directly, rather than a `DOMRefCell<IpcSender<ScriptToCompositorMsg>>`, since we never need an `&mut IpcSender<T>`.

The `Window::compositor()` could then return `&IpcSender<ScriptToCompositorMsg>` rather than `RefMut<'a, IpcSender<ScriptToCompositorMsg>>`.

Code: `components/script/dom/window.rs`

**Comment by nox** [comment]
@wartman4404 did it in #7244.

**Comment by wartman4404** [comment]
Sorry, I would have posted here asking to work on it, but I wanted to take a look at it first and it turned out to be tiny and self-contained enough to do then and there :/

**Comment by nox** [comment]
@wartman4404 No problem. :)
