### ISSUE TITLE
Can't build on Mac anymore (regression)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7247]
Since fb7a53c6cfc8bc2985423a55834507c930537bfc, I can't build on Mac (osx 10.11) anymore.

I get:

```
Process didn't exit successfully: `/Users/paul/github/servo/etc/rustc-with-gold -vV` (exit code: 133)
--- stderr
dyld: Library not loaded: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-a5fc0d6c.dylib
  Referenced from: /Users/paul/github/servo/.servo/rust/7b7fc67dd453c470a48dbdcf64693a93293c9ab0/rustc-1.4.0-dev-x86_64-apple-darwin/rustc/bin/rustc
  Reason: image not found
/Users/paul/github/servo/etc/rustc-with-gold: line 4: 76700 Trace/BPT trap: 5       rustc $EXTRA_ARGS "$@"
```

The script `rustc-with-gold` doesn't include the `DYLD_LIBRARY_PATH` variable for some reason I don't understand. But it is included by `build_env()`. And the other variables are present too.

If I understand correctly, `python` start `cargo` which start `rustc-with-gold` which starts `rustc`.
It used to be `python > cargo > rust`, and it worked. Not sure why we lose the `DYLD_LIBRARY_PATH` variable with the shell script.

Removing `env['RUSTC'] = path.join(self.context.topdir, 'etc', 'rustc-with-gold')` from `python/servo/command_base.py` solves this issue for me.

**Comment by paulrouget** [comment]
Here is a good description of what's going on: https://github.com/rust-lang/cargo/issues/1816

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/cargo/issues/1816#issuecomment-130478526 is probably the reason:
> This is due to a security "feature" in El Capitan. You can no longer export DYLD_LIBRARY_PATH to childprocesses

… but our CI is on older OS X versions.
