### ISSUE TITLE
iframe contentWindow returns null if content hasn't been fully loaded

### ISSUE THREAD

**Issue by samfoo** [servo/servo#7261]
`HTMLIFrameElement` doesn't respond correctly to `contentWindow` until after the resource task signals that a load has finished.

While the [spec](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-iframe-contentWindow) appears somewhat ambiguous on this to me, both Gecko and WebKit return a window object once the node is added to the DOM.

To reproduce:

```html
<html>
<body>
<iframe id="ifr"></iframe>
<script>
console.log(document.getElementById("ifr").contentWindow);
console.log(document.getElementById("ifr").contentDocument);

setTimeout(function() {
    console.log(document.getElementById("ifr").contentWindow);
    console.log(document.getElementById("ifr").contentDocument);
}, 5000);
</script>
</body>
</html>
```

**Comment by Ms2ger** [comment]
#3924
