### ISSUE TITLE
`getComputedStyle` should take `Element`, not `HTMLElement`.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7268]
Code:
 - `components/script/dom/webidls/Window.webidl` (use the commented-out line, keep the `[NewObject]` annotation)
 - `components/script/dom/window.rs` (update the `GetComputedStyle` implementation)
 - `components/script/dom/cssstyledeclaration.rs` (change the `owner` field to `JS<Element>` and fallout, including removing `PrivateCSSStyleDeclarationHelpers`)

I suspect there's no test yet. You'll have to write one that creates a non-HTML element (such as with `document.createElementNS("http://www.example.com/", "a")`), pass it to `window.getComputedStyle()` and check that it works. Add the file under `tests/wpt/mozilla/tests/css/`, and then run `./mach test-wpt _mozilla/css --manifest-update` to update the manifest. There's documentation at <http://testthewebforward.org/docs/> to help with writing the test.

**Comment by g-k** [comment]
OK if I pick this up?

**Comment by frewsxcv** [comment]
Marking as assigned. @mdibaiee is working on this
