### ISSUE TITLE
Servo shows grey screen instead of the monsterproof page

### ISSUE THREAD

**Issue by suhr** [servo/servo#7269]
Now to reproduce: `% ./mach run --release -e https://monsterproof.verigames.com/`
OS: Linux x86_64

**Comment by mdinger** [comment]
I'm seeing this for every page now including the `tests/html/about-mozilla.html`. Not sure what the issue is. Tested with commit a9147275413a1a83ab737f0188a283b2a7dedb85

**Comment by mdinger** [comment]
Bisecting:

Works with 0d1dfb9c43a998046ef032e67fc25f98020022bf (after PR https://github.com/servo/servo/pull/9210)

**Comment by mdinger** [comment]
Works with e684a20a1a814397f42d2dc11a43c1567e1c3191 (after PR https://github.com/servo/servo/pull/9282)

**Comment by mdinger** [comment]
Works with 1ca2073979a6223d97a6e8f5d5ebe03a00a7e249 (after PR https://github.com/servo/servo/pull/9348)

**Comment by mdinger** [comment]
Fails with ff0992401eacdc6a1eca638e2bf7f61642c95c13 (after PR https://github.com/servo/servo/pull/9366)

**Comment by mdinger** [comment]
Works with d9c643167fd4351e86e825bd03d67919f9c743d1 (after PR https://github.com/servo/servo/pull/9359)

**Comment by mdinger** [comment]
Works with 9d2eacf039532c5d2d3be549751c205b895f1c3c (after PR https://github.com/servo/servo/pull/9363)

**Comment by mdinger** [comment]
Fails with 74d75c40f975ad7fca76814cd6b53add17fe1b12 (after PR https://github.com/servo/servo/pull/9364).

The problem started with https://github.com/servo/servo/pull/9364

**Comment by jdm** [comment]
...huh. That's a very peculiar result. Could double check that a clobber build (ie. `./mach clean`) on 74d75c4 and the revision right before it show the bad/good behaviour respectively?

**Comment by mdinger** [comment]
What I was doing was:

```cmd
cd servo
git checkout -b new_name hash
sudo rm -r *
git reset --hard
./mach build --dev
```

The delete was with a gui because I wasn't sure if the command line would also remove the hidden files but that is basically what I did. Seems like that would be just as good as what you're suggesting.

**Comment by jdm** [comment]
I agree. Wow.

**Comment by jdm** [comment]
@glennw @mrobinson Any suggestions for investigating how a libc update caused servo to stop rendering anything?

**Comment by glennw** [comment]
Does using -o mode to output an image work?

**Comment by mdinger** [comment]
You mean like `./mach run -o www.google.com` or like something else?

**Comment by glennw** [comment]
Try ./mach run https://google.com -o output.png

**Comment by glennw** [comment]
(Or, perhaps try that with tests/html/about-mozilla.html first)

**Comment by mdinger** [comment]
`-o output.png` works properly with both tests/html/about-mozilla.html and google.com but normal running just generates a blank grey screen

**Comment by mbrubeck** [comment]
> Works with 9d2eacf (after PR #9363)
> Fails with 74d75c4 (after PR #9364).
>
> The problem started with 74d75c4 (PR #9364)

[That regression range][1] also includes PR #9339.  My testing shows that the first bad revision is actually f5c6c607c283f3ce61a504812d11575361797603 (#9339).

[1]: https://github.com/servo/servo/compare/9d2eacf...74d75c4

**Comment by mbrubeck** [comment]
Filed #9451 for this recent Linux-specific regression.

**Comment by suhr** [comment]
I guess this can be closed in favour of https://github.com/servo/servo/issues/9451?

**Comment by jdm** [comment]
Seems reasonable.

**Comment by mdinger** [comment]
Thanks @mbrubeck. I was actually trying to follow the bors PR merge order but apparently I failed. I did manually compare the branches and they appeared to only be a single commit apart. Comparing the servo tree is actually quite tricky because of the volume of commits and merges which occur. I'm glad you pointed out that trick!
