### ISSUE TITLE
Implement SupportedPropertyNames methods

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7273]
https://github.com/servo/servo/pull/7254 introduces a method on some DOM types called `SupportedPropertyNames` that returns all the ['supported property names'](https://heycam.github.io/webidl/#idl-named-properties) as per their respective interface. That PR only implements `HTMLCollectionMethods::SupportedPropertyNames` (I didn't have enough time to complete the rest). The other ones need to be implemented.

**Comment by frewsxcv** [comment]
At the time of writing, there is one `impl` remaining to be implemented:

https://github.com/servo/servo/blob/53aca4b80eef2890c43dd2d0e905b25588651191/components/script/dom/document.rs#L2529-L2533

**Comment by pshaughn** [comment]
A few years later, the above comment continues to be effectively true. (Plugin and PluginArray also have stubs, but that's correct for a plugin-less world.)
