### ISSUE TITLE
Using `overflow:auto` changes the stacking order

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7281]
```html
      <style>
        div {
          width: 100px;
          height: 100px;
          position: absolute;
          top: 0;
          left: 0;
        }
      </style>

      <div style="background:red;    overflow:auto;"></div>
      <div style="background:green;  top:10px;left:10px"> </div>
```

With `overflow:auto`, the red div is on top of the green div.

<img width="656" alt="screen shot 2015-08-19 at 09 28 00" src="https://cloud.githubusercontent.com/assets/373579/9350877/a34766c8-4654-11e5-9cd9-cc6515a61c5f.png">

**Comment by pcwalton** [comment]
This is because we don't use the `LAYERS_NEEDED_FOR_POSITIONED_DESCENDANTS` infrastructure in enough cases. I have what I believe to be a fix ready.
