### ISSUE TITLE
iframe content not painted at the right coordinates if the iframe forms a stacking context

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7282]
`iframe` + `absolute:position` + `z-index`: iframe content is painted as if iframe's coordinates were `top:0;left:0`.

```html
    <style>
    body {
      background: green;
    }
    iframe {
      top: 100px;
      left: 100px;
      border: 50px solid red;
      width: 400px;
      height: 400px;
      position:absolute;
      z-index:1;
    }
    </style>
    <iframe src="http://example.com"></iframe>
```

<img width="912" alt="screen shot 2015-08-19 at 09 53 54" src="https://cloud.githubusercontent.com/assets/373579/9351308/8b8eedd6-4658-11e5-9a47-7cc74dc9adb1.png">

**Comment by pcwalton** [comment]
I wonder if this is what's breaking eBay as well!

**Comment by pcwalton** [comment]
Also reproduces with `transform: translateX(0px)` instead of `z-index`, indicating that it's related to forming stacking contexts.
