### ISSUE TITLE
Interpolation of Calc values is broken

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#7284]
In components/style/animation.rs, we have code for interpolating lengths.

The Interpolate impl for LengthOrPercentage and LengthOrPercentageOrAuto (and possibly others, wherever Calc is an enum option) should handle LengthOrPercentage::Calc by interpolating the absolute component and the percentage and then combining them.

E-easy? Happy to mentor.

**Comment by dzbarsky** [comment]
(This will be an issue after #7185 lands)

**Comment by notriddle** [comment]
I'd be happy to take this one.

**Comment by dzbarsky** [comment]
Great, I'll let you know when that PR lands.

**Comment by dzbarsky** [comment]
@notriddle you can work on this now if you're still interested

**Comment by notriddle** [comment]
Yup, still interested.

**Comment by notriddle** [comment]
I added something that I think will work (manual testing bears this out), but how should I add it to the test suite?

**Comment by dzbarsky** [comment]
I guess we don't have transitionend events yet but you could do a 0s-length transition and check that the final value matches a reference?  Might need to rAF to get it to paint the end state.
