### ISSUE TITLE
Links for results don't show up when searching Google

### ISSUE THREAD

**Issue by FreeFull** [servo/servo#7298]
![servo bug](https://cloud.githubusercontent.com/assets/1496908/9393799/263f52ca-477c-11e5-9143-36a6ce4ae03b.png)

**Comment by pcwalton** [comment]
Yeah, I looked briefly into this and it looks like a DOM problem.

**Comment by jdm** [comment]
Is there any interesting output from stdout/stderr?

**Comment by FreeFull** [comment]
No interesting output, just a few javascript errors.

**Comment by jdm** [comment]
The JS errors are the interesting part.

**Comment by FreeFull** [comment]
I believe those were there back when the google results page was working, too.
