### ISSUE TITLE
Bloomberg.com locks out Servo due to UA sniffing

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#7300]
Going to http://www.bloomberg.com/news/articles/2015-08-20/twitter-falls-below-ipo-price-as-concerns-mount-over-ceo-growth displays a message that Servo is an "out of date browser".

**Comment by frewsxcv** [comment]
Discourse does as well

![screen shot 2015-08-21 at 1 34 45 pm](https://cloud.githubusercontent.com/assets/416575/9414841/78129d18-4809-11e5-9e70-a65de6586eda.png)

**Comment by mbrubeck** [comment]
I can no longer reproduce this.
