### ISSUE TITLE
Google logo floats left in non-US Google

### ISSUE THREAD

**Issue by tgkokk** [servo/servo#7301]
For example, [Google UK](https://www.google.co.uk):

![screen shot 2015-08-21 at 01 07 04](https://cloud.githubusercontent.com/assets/801854/9396952/0a1c3f8e-47a1-11e5-8336-252193390ddc.png)

**Comment by s142857** [comment]
I wanna work on it, could you guide me @jdm

**Comment by mskrzypkows** [comment]
I've found the root cause of floating left. Google uses ```<center>``` tag, inside there is ```<div>``` with ```align="left"``` attribute which causes logo to float left. Here is example html which shows the difference:
```
<html>
<body> 
    <center>            
        Test  <br><br>    
        <div style="background-color: #b0c4de; background-size:272px 92px;height:92px;width:272px"></div>
        <br><br>
        <div style="background-color: #b0c4de; background-size:272px 92px;height:92px;width:272px" align="left"></div>
    </center>
</html>
</body>
```

**Comment by jdm** [comment]
That's triggered by this CSS rule: http://mxr.mozilla.org/servo/source/resources/presentational-hints.css#14

**Comment by jdm** [comment]
Then again, it may also be interacting with http://mxr.mozilla.org/servo/source/resources/servo.css#27 ?

**Comment by mskrzypkows** [comment]
Here: http://mxr.mozilla.org/servo/source/components/layout/block.rs#2473 we have a check for ```<center>``` tag, if ```<div>``` has ```align="left"``` than ```input.text_align``` is not ```text_align::T::servo_center``` so there should be check for parent align or in other part, where ```input.text_align``` is set, there should be check for parent tag.
What do you think? Is it right direction?

**Comment by jdm** [comment]
That makes sense to me, but I will defer layout questions to people like @mbrubeck.

**Comment by jdm** [comment]
Perhaps we need a flag on nodes that are children of a `<center>` element, rather than a special text-align value.

**Comment by pcwalton** [comment]
@jdm Other browsers do use a special text-align value here though (-webkit-center and -moz-center).
