### ISSUE TITLE
Support <br clear="foo">

### ISSUE THREAD

**Issue by mdinger** [servo/servo#7311]
[Testcase](https://mdinger.github.io/servo_7311/testcase.html):

``` html
<html><head>
<style>
.test { float:left; }
</style>
</head>

<body>
<div><img class="test" src="https://www.google.com/images/srpr/logo11w.png" height="90" width="90"></div>
<br clear="left">
</div>

<div class="test"><img src="https://www.google.com/images/srpr/logo11w.png" height="90" width="90"></div>
</body></html>
```

causes:
![misalign](https://cloud.githubusercontent.com/assets/4156987/9417251/b1480992-4818-11e5-87bc-fe7296823a02.png)

[EDIT]
Problematic in http://www.dota2.com/hero/Earthshaker/ . These pages look pretty messy in general

**Comment by mdinger** [comment]
Updated OP with a linked testcase.

**Comment by pcwalton** [comment]
Thanks for the test! Updated the title with the problem.

**Comment by pcwalton** [comment]
Unfortunately I don't see a spec for this attribute.

**Comment by mdinger** [comment]
Would it be [this](https://developer.mozilla.org/en-US/docs/Web/CSS/clear#Specifications)?

**Comment by Ms2ger** [comment]
https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3

**Comment by mdinger** [comment]
Oh, this is problematic for a website like http://www.dota2.com/hero/Earthshaker/ which renders pretty badly in general.

**Comment by mdinger** [comment]
Still a problem with commit 31657811d33f23c79eae49dea171718562b031c5

**Comment by jdm** [comment]
resources/presentational-hints.css includes the `br` rules from https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3, so this is the layout code implementing clear behaviour not working correctly.
