### ISSUE TITLE
Flexbox: Link to containing block not established; perhaps you forgot to call `set_absolute_descendants`

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7317]
```
thread 'LayoutWorker worker 3/3' panicked at 'Link to containing block not established; perhaps you forgot to call `set_absolute_descendants`?', /Users/paul/github/servo/components/layout/flow.rs:1411
```

```html
<div style="display:flex;position:absolute">
  abc
</div>
```

Requires https://github.com/servo/servo/pull/7331.

**Comment by paulrouget** [comment]
Happens when `position:absolute/relative` is used inside a flex element.

**Comment by pcwalton** [comment]
Should be fairly easy to fix; the fix is right in the error message :)

**Comment by aidanhs** [comment]
Can't reproduce with provided testcase, but http://maps.google.com in release mode does do it.
(UK gmaps crashes servo with a different error in dev mode).

**Comment by jdm** [comment]
@aidanhs: You likely need to run with `--pref layout.flex.enabled` to reproduce the crash.

**Comment by shinglyu** [comment]
I can't reproduce the crash by running `./mach run -d --pref layout.flex.enabled --pref layout.flex-direction.enabled `, also tried `--release`. Is this solved by some previous patch?

**Comment by jdm** [comment]
Seems likely!
