### ISSUE TITLE
Cast to Element in PrivateCSSStyleDeclarationHelpers::get_declaration is useless

### ISSUE THREAD

**Issue by jdm** [servo/servo#7319]
The self value is already &Element, so ElementCast::from_ref is a no-op.

Code: components/script/dom/cssstyledeclaration.rs

**Comment by Ms2ger** [comment]
In fact, `PrivateCSSStyleDeclarationHelpers` can be removed entirely, and the calls to `get_inline_style_declaration` and `get_important_inline_style_declaration` can be inlined.

**Comment by jxs** [comment]
i can take this one
