### ISSUE TITLE
Make it possible to run tests with the experimental flag

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7335]
Some features are only available when Servo runs with the `-e` option.

**Comment by jdm** [comment]
One option we have is to run all tests with `-e`: https://github.com/w3c/wptrunner/blob/master/wptrunner/executors/executorservo.py#L195 and https://github.com/w3c/wptrunner/blob/master/wptrunner/executors/executorservo.py#L65

**Comment by paulrouget** [comment]
So running all the test with `-e` won't work. See https://github.com/servo/servo/pull/7385#issuecomment-135057940 and following comment.

**Comment by paulrouget** [comment]
Fixed. https://github.com/w3c/wptrunner/pull/141
