### ISSUE TITLE
Mismatched types error compiling for android: expected api::android::HeadlessContext, found api::egl::Context

### ISSUE THREAD

**Issue by connorimes** [servo/servo#7339]
Some recent changes appear to have broken the android build:

<pre>
/local/servo/./.cargo/git/checkouts/glutin-266ef3a474e2d7ce/servo/src/api/android/mod.rs:260:12: 260:19 error: mismatched types:
 expected `api::android::HeadlessContext`,
    found `api::egl::Context`
(expected struct `api::android::HeadlessContext`,
    found struct `api::egl::Context`) [E0308]
/local/servo/./.cargo/git/checkouts/glutin-266ef3a474e2d7ce/servo/src/api/android/mod.rs:260         Ok(context)
                                                                                                        ^~~~~~~
/local/servo/./.cargo/git/checkouts/glutin-266ef3a474e2d7ce/servo/src/api/android/mod.rs:260:12: 260:19 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
</pre>

**Comment by larsbergstrom** [comment]
@metajack This also points to a builder issue - this build error is in master, but is reporting 'success' in the waterfall! 
http://build.servo.org/builders/android/builds/2876/
http://build.servo.org/builders/android/builds/2876/steps/compile/logs/stdio

**Comment by metajack** [comment]
```
Build completed in 385.35s
program finished with exit code 0
```

Looks like a compiler bug that it didn't exit with non-zero? Or did someone trap for non-zero exits in mach and ignore them?

**Comment by jdm** [comment]
@Ms2ger fixed this yesterday, but we left a hack in for the android build so it didn't stop us landing other PRs.

**Comment by jdm** [comment]
And by _this_ I mean the silent builder errors.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/7359

**Comment by jdm** [comment]
See #7324 for the related problem.

**Comment by glennw** [comment]
I've submitted https://github.com/tomaka/glutin/pull/584 upstream to fix the android build (although it may need some changes depending on how tomaka wants to handle android using static binding generators for egl). Once that is merged, I'll update our glutin.

**Comment by nox** [comment]
Pretty sure this ultimately landed in Servo.
