### ISSUE TITLE
Make style nit check for space after a comma more thorough

### ISSUE THREAD

**Issue by jdm** [servo/servo#7345]
Right now it only flags a small number of things that follow a comma: http://mxr.mozilla.org/servo/source/python/tidy.py#206 . Instead, we should check for `,[^\s]`.

Code: python/tidy.py

**Comment by wilmoz** [comment]
I'll take this.

**Comment by jdm** [comment]
@wilmoz: Unfortunately @nerith already submitted a PR in #7351.
