### ISSUE TITLE
Add a style_traits crate to improve crate separation

### ISSUE THREAD

**Issue by jdm** [servo/servo#7353]
There are cases where some crates (eg. `compositing` and `msg`) that rely on very few public types from the style crate (such as `viewport::ViewportConstraints`). We should be able to extract these into a separate `style_traits` crate and make `style` depend on that, to reduce the number of crates that need to be rebuilt when making changes to `style`.

**Comment by jdm** [comment]
See components/script_traits/ and components/devtools_traits for good examples of this.

**Comment by jxs** [comment]
can i take this one?

**Comment by Ms2ger** [comment]
Go for it!
