### ISSUE TITLE
Forbid multiline imports

### ISSUE THREAD

**Issue by jdm** [servo/servo#7356]
tidy.py already checks for `use` statements with an opening `{` but no `}` on the same line, but we miss ones like http://mxr.mozilla.org/servo/source/components/script/dom/webglrenderingcontext.rs#5 . Let's fix that by looking for `use` statements with no `;` instead.

Code: python/tidy.py

**Comment by wilmoz** [comment]
I try this.

**Comment by jdm** [comment]
Thanks!

**Comment by Wafflespeanut** [comment]
fixed by #7362
