### ISSUE TITLE
Make dom_struct derive HeapSizeOf

### ISSUE THREAD

**Issue by jdm** [servo/servo#7357]
Currently all of our DOM types have `#[dom_struct]` and `#[derive(HeapSizeOf)]`. We should make `#[dom_struct]` add that annotation automatically instead.

Code: `expand_dom_struct` in components/plugins/jstraceable.rs

**Comment by jxs** [comment]
i can take this one

**Comment by jdm** [comment]
Ok!

**Comment by boghison** [comment]
Are you kidding me?
