### ISSUE TITLE
Make handle_potential_webgl_error more ergonomic

### ISSUE THREAD

**Issue by jdm** [servo/servo#7358]
We have a macro called `handle_potential_webgl_error` which takes a return value as the third argument. In the case where a caller has a void return type, we use it like `handle_potential_webgl_error(a, b, ())` which I find ugly. We can extend the macro to have a second variant that only takes two arguments and passes the `()` argument internally, like http://mxr.mozilla.org/servo/source/components/script/dom/macros.rs#6 .

Code: components/script/dom/webglrenderingcontext.rs

**Comment by wilmoz** [comment]
I take this :).

**Comment by jdm** [comment]
Great!

**Comment by wilmoz** [comment]
When you pass None as the third argument do you not mean it's () ?

**Comment by jdm** [comment]
No, None is used for methods that return `Option<T>`. The () is used for methods that have no return type at all.
