### ISSUE TITLE
Servo crash after open an URL

### ISSUE THREAD

**Issue by wilmoz** [servo/servo#7363]
```
./mach run --dev https://google.com

[glutin] x error code=42 major=0 minor=0!
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("GL context creation failed")', src/libcore/result.rs:732
stack backtrace:
   1:     0x7f128cfb3e89 - sys::backtrace::write::h29675241e432c301Pws
   2:     0x7f128cfb7899 - panicking::on_panic::h1e1c334783ff2a38jzx
   3:     0x7f128cfa4f6e - rt::unwind::begin_unwind_inner::hb529041d76c2c802L1w
   4:     0x7f128cfa5881 - rt::unwind::begin_unwind_fmt::h027d2621615b5dcfR0w
   5:     0x7f128cfb7291 - rust_begin_unwind
   6:     0x7f128cfe747f - panicking::panic_fmt::ha8483564b9ba8c9c47D
   7:     0x7f128bb814f0 - result::Result<T, E>::unwrap::h5155181630381788108
                        at src/libcore/macros.rs:28
   8:     0x7f128bb80e2c - window::Window::new::h7b5c79d209d6e099Sxa
                        at /home/william/Rust/servo/ports/glutin/window.rs:92
   9:     0x7f128bc148a0 - create_window::h480eb49bb2d732f0S6a
                        at /home/william/Rust/servo/ports/glutin/lib.rs:48
  10:     0x7f128abb5c6e - main::hb17248e397dad26braa
                        at /home/william/Rust/servo/components/servo/main.rs:61
  11:     0x7f128cfb9694 - rt::unwind::try::try_fn::h3003174718172809157
  12:     0x7f128cfb7238 - __rust_try
  13:     0x7f128cfb934b - rt::lang_start::h87c02d054d1dd9c0nvx
  14:     0x7f128ac6b546 - main
  15:     0x7f128a377b44 - __libc_start_main
  16:     0x7f128abb5a28 - <unknown>
  17:                0x0 - <unknown>
Servo exited with return value 101
```

OS: debian
freeglut3-dev: 2.8.1-2
libfreetype6-dev: 2.5.2-4
libgl1-mesa-dri: 10.6.3.1
libglib2.0-dev: 2.44.1-1.1
xorg-dev: 2:1.17.2-1.1
libglu1-mesa-dev: 9.0.0-2
libosmesa6-dev: 10.6.3-1

**Comment by SimonSapin** [comment]
> OsError("GL context creation failed")

Do you have an X server running? Is the `DISPLAY` environment variable set accordingly? What’s your graphics hardware? What drivers are you using for it?

**Comment by wilmoz** [comment]
Yes, x server is running,
Hardware: VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046]
Graphics driver: xserver-xorg-video-intel. 
I don't know how to set DISPLAY environment

**Comment by wilmoz** [comment]
@SimonSapin i found that this commit the commit "Update glutin window port after glutin update" is the origin of my problem. 
https://github.com/servo/servo/commit/0209bf11991a2d66a63019643674dea54c1ac992

**Comment by SimonSapin** [comment]
@glennw, any idea?

**Comment by glennw** [comment]
@wilmoz Could you paste the output of glxinfo here? I'm also planning to update glutin again today, so it would be worth testing again after that lands.

**Comment by pcwalton** [comment]
@glennw I'm also seeing this on my VM. Here's my `glxinfo`: https://gist.github.com/anonymous/15d5b40e5d9f8c14ea5

**Comment by glennw** [comment]
@pcwalton Ah, glxinfo reports that the vbox driver only supports 2.1 - so it's probably failing as we try to create a 3.0 context on desktop.

**Comment by wilmoz** [comment]
@glennw Here the output of glxinfo:
https://pastebin.mozilla.org/8844625

**Comment by glennw** [comment]
@wilmoz Thanks. Looks like the same issue as @pcwalton has - the glxinfo reports that only GL 2.1 is supported, while we (currently) require a 3.0 context.

We don't really use any 3.0 specific features that are vital (yet), so it's probably possible to switch to creating a 2.1 context - but we'd have to try that and see what breaks, and what workarounds are possible.

**Comment by wilmoz** [comment]
@glennw 
1. maybe it would be better to create a wrapper to manage the 2 version of opengl, but i don't know if this is a big task.
2. how to easily switch to 2.1 context only for my development enviroment?

**Comment by wilmoz** [comment]
Thanks to @eefriedman (c82401f213c469f880433077401ebfefffdf3b39) this bug should be closed
