### ISSUE TITLE
Write tests for TextInput when clearing a selection

### ISSUE THREAD

**Issue by jdm** [servo/servo#7365]
#6854 originally changed the behaviour of the input caret when clearing a selection due to moving the caret, but no tests broke. We should write tests that ensure that when the selection is cleared, the caret position is either at the start of the previous selection when pressing left, or at the end of the previous selection when pressing right.

Code: tests/unit/script/textinput.rs

**Comment by s142857** [comment]
could you please expand on the test, and what language should i use and how should i run it.(any tools)

**Comment by jdm** [comment]
@s142857 There are already similar tests that exist in tests/unit/script/textinput.rs . We want to add some more tests for the cursor behaviour when there is a selection present and an arrow key is pressed that causes the selection to be cleared. Does that make sense?

**Comment by jdm** [comment]
The tests can be run with `./mach test-unit -p script`.

**Comment by Mylainos** [comment]
@jdm for sumarize the job is to create a new test with something like that ?
```rust
    textinput.adjust_horizontal(0, Selection::NotSelected);
    textinput.adjust_horizontal(3, Selection::Selected);
    textinput.adjust_horizontal(1, Selection::NotSelected);
    assert_eq!(textinput.edit_point.index, 3);

    textinput.adjust_horizontal(0, Selection::NotSelected);
    textinput.adjust_horizontal(3, Selection::Selected);
    textinput.adjust_horizontal_by_one(Direction::Forward, Selection::NotSelected);
    assert_eq!(textinput.edit_point.index, 3);
```

**Comment by jdm** [comment]
Precisely!

**Comment by Mylainos** [comment]
Ok I think it's done but how should I call the function ? I don't find good name...

**Comment by jdm** [comment]
cursor_position_correct_after_clearing_selection?

**Comment by Mylainos** [comment]
I don't understand why there is three commits but the final is the good one.
