### ISSUE TITLE
Glutin errors using -g option - page does not render

### ISSUE THREAD

**Issue by connorimes** [servo/servo#7366]
Trying to run with the -g option to use GPU rendering.  Glutin is spitting out some errors and I'm left with a white page.

Hardware is a Thinkpad X1 Carbon 3rd Gen running Ubuntu 15.04 with kernel `4.2.0-040200rc6-generic`.

<pre>
/local/servo$ ./mach run -r -g 'tests/html/perf-rainbow.html'
[glutin] x error code=87 major=0 minor=0!
[glutin] x error code=91 major=0 minor=0!
[glutin] x error code=95 major=0 minor=0!
[glutin] x error code=99 major=0 minor=0!
[glutin] x error code=140 major=0 minor=0!
[glutin] x error code=144 major=0 minor=0!
[glutin] x error code=148 major=0 minor=0!
[glutin] x error code=152 major=0 minor=0!
[glutin] x error code=188 major=0 minor=0!
[glutin] x error code=191 major=0 minor=0!
[glutin] x error code=194 major=0 minor=0!
[glutin] x error code=197 major=0 minor=0!
</pre>

**Comment by wartman4404** [comment]
Ubuntu seems to have a nonstandard layout for XErrorEvent, which messes with Glutin's error handler.

From `man xerrorevent` (`x11-rs` is the same)

    typedef struct {
         int type;
         Display *display;   /* Display the event was read from */
         unsigned long serial;/* serial number of failed request */
         unsigned char error_code;/* error code of failed request */
         unsigned char request_code;/* Major op-code of failed request */
         unsigned char minor_code;/* Minor op-code of failed request */
         XID resourceid;     /* resource id */
    } XErrorEvent;

From Xlib.h on my system, running Ubuntu 12.04:

    typedef struct {
         int type;
         Display *display;	/* Display the event was read from */
         XID resourceid;		/* resource id */
         unsigned long serial;	/* serial number of failed request */
         unsigned char error_code;	/* error code of failed request */
         unsigned char request_code;	/* Major op-code of failed request */
         unsigned char minor_code;	/* Minor op-code of failed request */
    } XErrorEvent;

As a consequence, `code`, `major`, and `minor` are all pulled from `serial`.

I threw together a quick and dirty [fix](https://github.com/wartman4404/glutin/commit/a06cc75df6dc3e3d0127c5cd5f44f89e0502b9b7), and get the following errors:

    [glutin] x error code=8 (BadMatch (invalid parameter attributes)) major=62 (X_CopyArea) minor=0 serial=77!
    [glutin] x error code=8 (BadMatch (invalid parameter attributes)) major=62 (X_CopyArea) minor=0 serial=81!
    [glutin] x error code=8 (BadMatch (invalid parameter attributes)) major=62 (X_CopyArea) minor=0 serial=85!
    [glutin] x error code=8 (BadMatch (invalid parameter attributes)) major=62 (X_CopyArea) minor=0 serial=89!
    [glutin] x error code=8 (BadMatch (invalid parameter attributes)) major=62 (X_CopyArea) minor=0 serial=128!
    [glutin] x error code=8 (BadMatch (invalid parameter attributes)) major=62 (X_CopyArea) minor=0 serial=132!
    [glutin] x error code=8 (BadMatch (invalid parameter attributes)) major=62 (X_CopyArea) minor=0 serial=136!

**Comment by jdm** [comment]
Thanks @wartman4404!

**Comment by connorimes** [comment]
Nice.  Any idea why Ubuntu is using the different layout?  If there's no reason, we may want to file a bug with Ubuntu on Launchpad.

**Comment by wartman4404** [comment]
It turns out Ubuntu didn't change it, and neither did Debian.  I'm starting to think the documentation is wrong: http://cgit.freedesktop.org/xorg/lib/libX11/tree/include/X11/Xlib.h#n924
