### ISSUE TITLE
relative inline-block div gets cut off if a position:fixed element is present

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7372]
```html
<style>
  #d1 {
    width: 100px;
    height: 100px;
    position: absolute;
    background: green;
  }
  #d2 {
    display: inline-block;
    width: 100px;
    background: red;
    height: 100px;
    position: relative;
    top: 20px;
    left: 20px
  }
</style>

<div style="position:fixed"></div>
<div id="d1">
  <div id="d2"></div>
</div>
```

Removing the `position:fixed` element fixes the problem.

<img width="521" alt="screen shot 2015-08-26 at 09 03 35" src="https://cloud.githubusercontent.com/assets/373579/9487381/5c211c30-4bd1-11e5-91ec-4c3e095cbfcb.png">

**Comment by paulrouget** [comment]
cc @pcwalton

**Comment by pcwalton** [comment]
Probably an overflow calculation problem for layers. Actually I just fixed one of those.

**Comment by notriddle** [comment]
Shouldn't this be tagged I-wrong?
