### ISSUE TITLE
Check for multiple import blocks separated by whitespace

### ISSUE THREAD

**Issue by jdm** [servo/servo#7381]
Following the recommendation in https://groups.google.com/forum/#!topic/mozilla.dev.servo/FoiIS5zWujE , we'd like to merge all of our import blocks together and report any unmerged ones as errors. This should be possible if we store a boolean values for "last line was a use statement", "encountered whitespace following a use statement", and when encountering a use statement we can report an error if the last boolean is true.

Code: python/tidy.py

**Comment by nerith** [comment]
I'd like to take this.

**Comment by jdm** [comment]
@nerith Please do!

**Comment by jdm** [comment]
@nerith Still working on this?
