### ISSUE TITLE
Use descriptive enums instead of booleans for MIMEClassifier::classifer

### ISSUE THREAD

**Issue by jdm** [servo/servo#7382]
Enums are self-documenting in a way that true/false in function arguments are not.

Code: components/net/mime_classifier.rs

**Comment by ddrmanxbxfr** [comment]
I've attached a PR regarding the refactor.

Thanks for looking into it.

**Comment by edunham** [comment]
@ddrmanxbxfr Thank you for the PR! Can this issue be closed now?

**Comment by jdm** [comment]
Yep!
