### ISSUE TITLE
Ensure lists of modules are in alphabetical order

### ISSUE THREAD

**Issue by jdm** [servo/servo#7390]
For lists like
```rust
mod foo;
pub mod bar;
mod zap;
```
We should verify that they are sorted alphabetically by module name and report an error if not.

Code: python/tidy.py

**Comment by jdm** [comment]
See the code for checking sorted-ness of `use` statements for inspiration: http://mxr.mozilla.org/servo/source/python/tidy.py#246

**Comment by Mylainos** [comment]
I'd like to work on this please. But if something like this happen :
```
mod Foo {

}
mod Bar {

}
```
we don't report an error because they are not sorted alphabetically, right ?

**Comment by Wafflespeanut** [comment]
@Mylainos Go ahead and take it! And, I guess we could just neglect inline modules for now :)

**Comment by Mylainos** [comment]
I think it's done but there is a problem with this line http://mxr.mozilla.org/servo/source/components/style/lib.rs#48. For me the lint should be at the upper line but what do you think ?

**Comment by Wafflespeanut** [comment]
@Mylainos Yep, you're right. That's a bit ugly, put that `pub mod foo` in a new line :)

**Comment by Ms2ger** [comment]
I think it's cleaner in this case to keep it all on one line.

**Comment by jdm** [comment]
We should be able to strip any attributes that are used by using the same code as http://mxr.mozilla.org/servo/source/python/tidy.py#194 .

**Comment by Mylainos** [comment]
The regex at http://mxr.mozilla.org/servo/source/python/tidy.py#195 delete the whole line. This regex `line = re.sub('//.*?$|/\*.*?$|^\*.*?$|^#!?\[.*?]\s', '', line)` delete just the attribute.
Now everything work except inline mod. Should I do a PR ?

**Comment by Wafflespeanut** [comment]
@Mylainos Yes, you should! (also, [add a keyword](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) like "fixes #7390")

**Comment by SimonSapin** [comment]
This might be better as a compiler lint (which uses the existing parser that already knows how to deal with attributes) rather than hack it with string manipulation and regexes.

**Comment by Mylainos** [comment]
The regex that I changed ```line = re.sub('//.*?$|/\*.*?$|^\*.*?$|^#!?\[.*?]\s', '', line)``` only report the attributes with whitespace after (due to the ```\s```). That was for http://mxr.mozilla.org/servo/source/components/style/lib.rs#48.

But now tidy report that ```./components/gfx/font.rs:104: missing space before =``` http://mxr.mozilla.org/servo/source/components/gfx/font.rs#104.

And this could conflict with #7460.
