### ISSUE TITLE
Fix spacing errors in MIME classifier for feeds

### ISSUE THREAD

**Issue by jdm** [servo/servo#7393]
The steps at https://mimesniff.spec.whatwg.org/#rules-for-distinguishing-if-a-resource-is-a-feed-or-html don't include spaces in strings like "rdf: RDF" and "http:// purl.org", whereas our implementation does. We should walk through it carefully and correct them. Adding comments indicating which step is being executed would also be valuable.

Code: components/net/mime_classifier.rs

**Comment by jdm** [comment]
We should also ensure that we have tests for these broken classifiers!

**Comment by jdm** [comment]
It looks like there are only basic tests for feeds in http://mxr.mozilla.org/servo/source/tests/unit/net/mime_classifier.rs#436

**Comment by simartin** [comment]
Hi! I'd like to try this one.

**Comment by Ms2ger** [comment]
Go for it!
