### ISSUE TITLE
Don't renegotiate SSL sessions on every resource load

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#7398]
Go to http://en.wikipedia.org/wiki/Servo and notice that SSL is dominating the CPU usage. We really need to reuse SSL sessions!

**Comment by jdm** [comment]
Will connection pooling help here?

**Comment by pcwalton** [comment]
I'm not familiar enough with the internals of Hyper to answer that, unfortunately.

**Comment by nox** [comment]
We reuse SSL sessions now, AFAICT.
