### ISSUE TITLE
serialize_list should not append a space at the end of the list

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#7404]
for example, element.style['border-width'] should return |0px 0px 0px 0px| not |0px 0px 0px 0px |
The code to blame is serialize_list in cssstyledeclaration.rs (http://mxr.mozilla.org/servo/source/components/script/dom/cssstyledeclaration.rs#54) and the problem is that it folds over the list and adds a space after every list element. Instead, it should join the declaration values with a space.

**Comment by frewsxcv** [comment]
We should utilize [this utility function](https://github.com/servo/servo/blob/7a6d8a30d316fb65c2c846d3d6d0d5e33b29bc5c/components/util/str.rs#L331-L337)

**Comment by frewsxcv** [comment]
Though, that utility function might only work if the in the slice can `AsRef` to `str`, so it might not be appropriate in this case (unless the utility gets altered to take an `Iterator` instead of a slice)

**Comment by dzbarsky** [comment]
I think we may be able to just call vec.join(" ") (after mapping the declarations to the values)

**Comment by GyrosOfWar** [comment]
I'd like to do this one.
