### ISSUE TITLE
Support setting the window dragging region with CSS

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7408]
Glutin allows [decoration-less windows](http://tomaka.github.io/glutin/glutin/struct.WindowBuilder.html#method.with_decorations). We can paint where the titlebar is supposed to be displayed by the OS, and then build our own titlebar (thinking of browser.html here).

But we need to be able to tell the OS what region of the UI is draggable.

The equivalent of `-webkit-app-region: drag` and `-moz-window-dragging: drag;`. See [gecko implementation](https://dxr.mozilla.org/mozilla-central/source/layout/base/nsDisplayList.cpp#1116).

**Comment by SimonSapin** [comment]
Such CSS properties should be prefixed with `-servo-` (to avoid name collisions with possible future standard properties) and not exposed to content, possibly by checking `style::parser::ParserContext::stylesheet_origin` in the parsing code. Or perhaps we need another mechanism for "internal" properties.

**Comment by paulrouget** [comment]
Relevant gecko patches (haven't landed in m-c): https://bugzilla.mozilla.org/show_bug.cgi?id=1070710

**Comment by paulrouget** [comment]
This is what I tried to do:

- `window.setMovableByWindowBackground_(YES)`
- add `NSView`s where the window is not draggable
- these views are subclasses of `NSView` where `mouseDownCanMoveWindow` returns `NO`

But `mouseDownCanMoveWindow` is never called. I don't know why.

**Comment by paulrouget** [comment]
Failing code: https://github.com/paulrouget/glutin/commit/5b922d1e19723c16b55a2eb9241c2cc69d60e4b1

**Comment by paulrouget** [comment]
This is not standard and not necessary anymore. Closing.
