### ISSUE TITLE
can servo be a clean and modern reference platform for developers?

### ISSUE THREAD

**Issue by timkuijsten** [servo/servo#7409]
As a web developer I'm confronted with an ever increasing stack of portability hacks and complexity. The latest tool I heard of to workaround this issue is [cssnext.io](http://cssnext.io/) but many already exist. It would be nice to have some sort of minimal reference platform that only implements the latest standards but doesn't care as much about backwards compatibility as all current browsers do. In the past Opera fulfilled this role, but since they've moved to Blink this is no longer the case.

If you think about all the hours that are lost because engine-implementors have to build workarounds to work with all legacy sites that exists on the web, and then web developers that have to build workarounds for all the different browser behavior and workarounds. It seems like we're at the point where **both parties are creating workarounds for the workarounds of the other party**. An enormous waste of time.

I like how OpenSSH[1], LibreSSL[2][3] and OpenSMTPD[4] are developed. They take one clean platform, and only afterwards add all the portability hacks in order to be compatible with different systems and legacy behavior.

I wonder if Servo has this separation of a clean core versus compatibility hacks to make it work with big and popular websites. I think both Servo developers and web developers could benefit a lot from this.

ps. I was inspired by this after finding out that currently Servo is being made compatible with all major sites and quirks: https://news.ycombinator.com/item?id=10085700. Personally I would prefer to have a less complex (and hopefully more secure) engine, over a monolithic blob of code that is compatible with a lot of websites but will end up to be utterly complex (as a NoScript/RequestPolicy user I don't mind sites to break a bit).

[1] "OpenSSH is developed by two teams. One team does strictly OpenBSD-based development, aiming to produce code that is as clean, simple, and secure as possible. We believe that simplicity without the portability "goop" allows for better code quality control and easier review. The other team then takes the clean version and makes it portable (adding the "goop") to make it run on many operating systems -- the so-called -p releases, ie "OpenSSH 4.0p1"." http://www.openssh.com/
[2] http://www.openbsd.org/papers/bsdcan14-libressl/mgp00011.html
[3] http://www.openbsd.org/papers/bsdcan14-libressl/mgp00012.html
[4] https://www.opensmtpd.org/portable.html

**Comment by SimonSapin** [comment]
The web is messed up, and many (most?) sites don’t get updated. As much as a pain this is, such is life. Even Presto Opera had to deal with it and implement quirks mode and all the other weird things that can’t be changed without breaking the web.

> I wonder if Servo has this separation of a clean core versus compatibility hacks to make it work with big and popular websites. I think both Servo developers and web developers could benefit a lot from this.

I think this is absolutely not true. For us Servo developers, this separation (if it’s even possible) sounds like a bunch of additional work with no benefit.

For web developers, Servo doing anything unilaterally is not gonna help them make sites that work across browsers. The way to improve the web is to build consensus in standard bodies, so that hopefully all browsers will implement the same thing.

**Comment by Ms2ger** [comment]
> implements the latest standards but doesn't care as much about backwards compatibility

Those two things are diametrically opposed. Modern standards go to great lengths to specify handling of all input, and making sure that handling is compatible with existing browsers.

**Comment by timkuijsten** [comment]
> Modern standards go to great lengths to specify handling of all input, and making sure that handling is compatible with existing browsers.

Interesting point. That does mean the system only expands and becomes more complex over time. Not sure if this will explode (or implode) some day.
