### ISSUE TITLE
Scrolling is slow

### ISSUE THREAD

**Issue by mdinger** [servo/servo#7410]
Scrolling speed is slow again. It was previously fixed for https://github.com/servo/servo/issues/5660 but now isn't anymore.

**Comment by jdm** [comment]
Which platform do you see this on?

**Comment by vbuell** [comment]
I can confirm that the scrolling is 1px per mouse wheel rotation. Linux

**Comment by jdm** [comment]
I suspect this will be fixed by https://github.com/tomaka/glutin/pull/580.

**Comment by mdinger** [comment]
Yeah, same for me. Ubuntu 14.04

**Comment by mdinger** [comment]
Is this testable? It seems like a good idea if it is.

**Comment by mdinger** [comment]
Fixed by https://github.com/servo/servo/pull/7543
