### ISSUE TITLE
Import ordering tidy check confused by multiple use statements from same module

### ISSUE THREAD

**Issue by nox** [servo/servo#7412]
```rust
use url::{Url, UrlParser, SchemeData};
use url::urlutils::{UrlUtils, UrlUtilsWrapper};
```
```
./components/script/dom/urlhelper.rs:7: use statement is not in alphabetical order
./components/script/dom/urlhelper.rs:8: use statement is not in alphabetical order
```
<hr>
```rust
use url::{Url, UrlParser};
use url::SchemeData;
```
```
./components/script/dom/urlhelper.rs:9: use statement is not in alphabetical order
./components/script/dom/urlhelper.rs:10: use statement is not in alphabetical order
```

**Comment by jdm** [comment]
Can this be fixed by reordering the `url::{` entries after the others? That would imply that `{` comes after `a-z` in alphabetical order.

**Comment by nox** [comment]
Well, that's why I opened the issue, I don't want to reorder it like this.

**Comment by SimonSapin** [comment]
We could have a different sorting function, but I’m not sure that it’s worth it.

**Comment by nox** [comment]
Whether or not it's worth it, I'm not sure a tidy check that is wrong is a good idea.

**Comment by SimonSapin** [comment]
Is it wrong?

**Comment by nox** [comment]
```rust
use mod::{foo, bar};
use mod::qux;
```

I don't see why `qux` should come before `{foo, bar}`, it makes no sense.

**Comment by tafia** [comment]
> I don't see why qux should come before {foo, bar}, it makes no sense.

It doesn't look that wrong to me.
I'd say simpler first for readability. And a `{...}` does look less simple than one element.
But I don't have any strong opinion on that matter.

**Comment by nox** [comment]
```rust
use dom::bindings::codegen::InheritTypes::ProcessingInstructionCast;
use dom::bindings::codegen::InheritTypes::{CharacterDataCast, DocumentTypeCast};
use dom::bindings::codegen::InheritTypes::{ElementCast, HTMLScriptElementCast};
use dom::bindings::codegen::InheritTypes::{HTMLFormElementDerived, NodeCast};
```

ProcessingInstructionCast is at an unexpected place.

**Comment by nox** [comment]
@tafia The lint is about alphabetic order of imports, not about simplicity first or whatever.

**Comment by nox** [comment]
qux is after foo and bar in alphabetic order, and thus should come after them, whether there are braces or not.

**Comment by nox** [comment]
Mmmmh… I can't order foo and bar apparently, good thing I find a real-world example.

**Comment by bholley** [comment]
Yeah, this is super confusing.

**Comment by jdm** [comment]
One idea from IRC: lowercase the lines before comparing them so `use something::a` vs `use something::A` isn't so confusing.

**Comment by nox** [comment]
@jdm First time I hear someone complain about this specific part. I'm more annoyed by how braces should come after not-braces.
