### ISSUE TITLE
Make test-tidy check that braces have spaces before or after them

### ISSUE THREAD

**Issue by jdm** [servo/servo#7413]
We should be able to catch and report style violations like `Foo {a: 5, b: 6}` by finding `{[^s]` and `[^s]}`. Let's see how many violations that finds and whether we need to be more specific.

Code: python/tidy.py

**Comment by frewsxcv** [comment]
Interesting, I've never met anyone who prefers `Foo { a: 5, b: 6 }` over `Foo {a: 5, b: 6}`, but so be it

**Comment by nox** [comment]
I prefer the former.

**Comment by frewsxcv** [comment]
Should this apply to functions as well? e.g. `add( 1, 2 )`

[I think it looks weird to me because I'm used to Python which specifically calls out this](https://www.python.org/dev/peps/pep-0008/#pet-peeves)

**Comment by frewsxcv** [comment]
Just checked rustfmt and it looks like it does what you suggest, so SGTM

https://github.com/nrc/rustfmt/blob/25650c2a8bc2873cd0eb13a4511aeee7e2f94f25/tests/target/struct_lits.rs#L7

**Comment by nox** [comment]
@frewsxcv It's also the usual style in OCaml, and probably other languages I am forgetting right now or just don't know about.

**Comment by frewsxcv** [comment]
(though not for imports)

https://github.com/nrc/rustfmt/blob/25650c2a8bc2873cd0eb13a4511aeee7e2f94f25/tests/target/imports.rs

**Comment by jdm** [comment]
We're definitely going to have to ignore lines with `::{` in them.

**Comment by Ms2ger** [comment]
I prefer `Foo {a: 5, b: 6}` spanned over four lines :)

**Comment by Wafflespeanut** [comment]
Hah! My kind! :hand:

**Comment by wilmoz** [comment]
I'd like to take this

**Comment by wilmoz** [comment]
this case should be ignored?
_ => {},

**Comment by jdm** [comment]
Yes; thanks for checking!

**Comment by wilmoz** [comment]
It's great to collaborate :)

**Comment by Wafflespeanut** [comment]
fixed by #7475.
