### ISSUE TITLE
testcase: input box improperly located

### ISSUE THREAD

**Issue by mdinger** [servo/servo#7425]
This doesn't locate the input box properly. This is from a teardown of an [lol site](http://gameinfo.na.leagueoflegends.com/en/game-info/items/). Testcases:

* [testcase1](https://mdinger.github.io/servo_7425/testcase1.html) (the original)
* [testcase2](https://mdinger.github.io/servo_7425/testcase2.html)
* [testcase3](https://mdinger.github.io/servo_7425/testcase3.html)

```html
<html><head>
<style>
    header nav{position:absolute;top:0;right:20px;display:table}
</style>
</head>
<body>
  <header>
      <h2>Item Filters</h2>
      <nav> <input> </nav>
  </header>
</body> </html>
```

A picture of it:

![capture](https://cloud.githubusercontent.com/assets/4156987/9538206/d378638a-4d0f-11e5-8c14-5637f7c60575.png)

**Comment by mdinger** [comment]
Updated with linked testcase and a picture

**Comment by notriddle** [comment]
```html
<html>
<head>
<style>
    header nav{background:red;position:absolute;top:0;right:20px;display:table}
</style>
</head>
<body>
  <header>
      <h2>Item Filters</h2>
      <nav> XX </nav>
  </header>
</body>
</html>
```

Actually, this shows up even without the `<input>`. It's actually a bug in table layout.

**Comment by mdinger** [comment]
Updated the op to include that testcase as testcase 2.

**Comment by notriddle** [comment]
More information on this bug: Servo will happily absolutely position a table (either a normal table element or another element with `display:table` on it) on the Y axis, but will not absolutely position it on the X axis. It always acts as if `left:0` was set on the element, no matter what `left` or `right` are set to. Try this test case, for example:

```html
<!DOCTYPE html>
<style>
nav { display:table;position:absolute;bottom:40px;right:40px }
</style>
<nav>
XXX
</nav>
```

**Comment by mdinger** [comment]
updated op with testcase 3
