### ISSUE TITLE
Can't use --debugger=rust-lldb with test-wpt

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7440]
CC @jgraham

**Comment by jdm** [comment]
Specifically the debugger does not appear to get launched and the test proceeds without any interruption. This is different than what happens with --debugger=nonexistent, when there's a python backtrace and the mach command fails.

**Comment by jgraham** [comment]
I suspect we need to teach mozdebug about it https://dxr.mozilla.org/mozilla-central/source/testing/mozbase/mozdebug/mozdebug/mozdebug.py#23

**Comment by nox** [comment]
This is still not supported, I think.

**Comment by jdm** [comment]
No, I use it all the time.

**Comment by jdm** [comment]
Whoops, misread the title. Nevermind.
