### ISSUE TITLE
Ensure `extern crate`s are in alphabetical order

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#7441]
We should educate tidy to check for lines such as

``` rust
extern crate foo;
#[macro_use]
extern crate bar;
```
which should be changed to,

``` rust
#[macro_use] extern crate bar;
extern crate foo;
```
The code lives at `python/tidy.py`. Also, take a look at #7390 for a similar approach (and #7265 for information about sorting).

**Comment by Mylainos** [comment]
What if the `#[macro_use]` is follow by another attribute ?

**Comment by Ms2ger** [comment]
Such as?

**Comment by Wafflespeanut** [comment]
probably

``` rust
#[macro_use]
#[cfg(feature = "foo")]
```

**Comment by Mylainos** [comment]
Yes or this one : http://mxr.mozilla.org/servo/source/components/layout/lib.rs#31
```rust
#[macro_use]
#[no_link]
extern crate plugins as servo_plugins;
```

**Comment by Wafflespeanut** [comment]
@Mylainos I say just leave the double attributes and compare it with `servo_plugins`.

**Comment by Ms2ger** [comment]
@Wafflespeanut is this free to be taken?

**Comment by stratact** [comment]
I would be interested in alphabetizing the `extern crate` lines if this isn't already worked on.

**Comment by Wafflespeanut** [comment]
Yep, it's free :)

@stratact Go ahead and take it! :)

**Comment by stratact** [comment]
@Wafflespeanut just so there is no confusion, I was planning on manually alphabetizing the `extern crates` lines in the Servo source code. Does this conflict with your goals with fixing `tidy.py`?

**Comment by Wafflespeanut** [comment]
Well, my PR has already landed, and so you shouldn't be having any problem :)

I'd also like to add that declarations with `#[macro_use]` should be sorted and moved to the top - I mean,

``` rust
extern crate foobar;
#[macro_use]
extern crate foo;
extern crate bar;
```

... should be sorted as,

``` rust
#[macro_use]
extern crate foo;
extern crate bar;
extern crate foobar;
```

**Comment by stratact** [comment]
What if there were multiple `#[macro_use]` lines embedded in between?

Such as:
```rust
extern crate foo;
#[macro_use]
extern crate bar;
#[macro_use]
extern crate foobar;
```

**Comment by Wafflespeanut** [comment]
@stratact Have a look at [`gfx/lib.rs`](https://mxr.mozilla.org/servo/source/components/gfx/lib.rs) for inspiration. The `app_units` crate was recently added it seems (so, don't let that confuse you!), it should actually follow `util`, because `util` has `#[macro_use]`. Does that help?

**Comment by Wafflespeanut** [comment]
@stratact Any news on progress?

**Comment by GuillaumeGomez** [comment]
I'll take this one over too.

**Comment by Wafflespeanut** [comment]
Please, go ahead! This has been around for a long time :)
