### ISSUE TITLE
Hand over the alphabetical checking to lints!

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#7451]
If you have a look at #7441, #7390, and #7112, the alphabetical checking for `extern crate`, `use` and `mod` statements are done by tidy. @SimonSapin just told me that all those could be done better with Rust's lints. We already have some lints written by dear @Manishearth, but we need more!

The future code will live at `components/plugins/lints` along with the other lints.

**Comment by SimonSapin** [comment]
I’ve been arguing that it may be easier to let rustc’s parser deal with attributes and line breaks rather than do this with string parsing in Python.

**Comment by Manishearth** [comment]
Willing to mentor this; this just involves writing a [`check_mod`](http://manishearth.github.io/rust-internals-docs/rustc/lint/trait.LintPass.html#method.check_mod) and `check_crate` which checks that the list of `use` items  is in order, ignoring `pub use` and `#[macro_use]` items.

**Comment by Wafflespeanut** [comment]
@Manishearth I'll go for it :)

**Comment by Wafflespeanut** [comment]
Alright, after having some discussion with others, I've realized that this lint won't be very helpful for servo. So, let's close this (I did have fun time though)...
