### ISSUE TITLE
Make test-tidy check that = have space after them

### ISSUE THREAD

**Issue by Mylainos** [servo/servo#7460]
I've found code like this `#[cfg(target_os ="linux")]`. It's a bit ugly and sometimes there is space after the =.

Code : python/tidy.py

**Comment by SimonSapin** [comment]
Should we try and go full [rustfmt](https://github.com/nrc/rustfmt) instead?

**Comment by jdm** [comment]
Ah, http://mxr.mozilla.org/servo/source/python/tidy.py#217 is not strict enough.

**Comment by jdm** [comment]
@SimonSapin Nope; there are outstanding blockers last I checked.

**Comment by JoshTheGoldfish** [comment]
Mind if take this one?

**Comment by jdm** [comment]
Go for it!

**Comment by JoshTheGoldfish** [comment]
While it's true that the regex isn't accounting for a cases like  `#[cfg(target_os ="linux")]`, it looks like attributes in .rs files are being ignored anyway. See http://mxr.mozilla.org/servo/source/python/tidy.py#195.

**Comment by jdm** [comment]
The answer is "kinda". The attributes get in the way of some of the tidy checks, but it would be beneficial to perform some checks (like this one) on them.

**Comment by JoshTheGoldfish** [comment]
Ok, my local code now checks to make sure attributes like the one above (or any attribute with an = character) get checked for a space before and after the =. Other attributes like `#[derive(Copy, Clone, PartialEq)]` will be ignored.

There are quite a few files that violate the rule. Should I change these now?

**Comment by JoshTheGoldfish** [comment]
Like @Mylainos warned in #7390, the code I wrote will conflict with his change for line http://mxr.mozilla.org/servo/source/python/tidy.py#195.

```python
# get rid of comments
line = re.sub('//.*?$|/\*.*?$|^\*.*?$', '', line)

# get rid of attributes that do not contain =
line = re.sub('^#[A-Za-z0-9\(\)_\[\]_]*?$', '', line)
```

**Comment by jdm** [comment]
Yeah, I didn't think about things like `#[doc="foo"]`. I think I'm fine making it `#[doc = "foo"]` in service of the greater good.

**Comment by JoshTheGoldfish** [comment]
Can this be closed?

**Comment by jdm** [comment]
Yep!
