### ISSUE TITLE
IDL attributes reflecting non-negative integer content attributes should throw IndexSizeError when set to a negative number

### ISSUE THREAD

**Issue by jdm** [servo/servo#7461]
An example is `document.createElement('input').size = -5`. Firefox throws an exception; Servo silently sets it to -1. https://html.spec.whatwg.org/multipage/infrastructure.html#limited-to-only-non-negative-numbers says that Firefox is right.

We need to modify `parse_plain_attribute` to return a `Result<AttrValue, Error>`, and take an argument indicating whether the attribute is being set by the parser or not. If it is, the default value should be used; if it's not, an `Err(IndexSizeError)` value should be returned instead.

Code: components/script/dom/element.rs, components/script/dom/virtualmethods.rs

**Comment by jdm** [comment]
I was reading the code wrong. This is accomplished by make_limited_uint_getter.

**Comment by jdm** [comment]
Actually a real problem:
```
<input id="foo" size=-5>
<script>alert(document.getElementById('foo').size); var i = document.createElement('input'); i.size = -5; alert(i.size)</script>
```
```
ALERT: 20
ALERT: 20
```

**Comment by jdm** [comment]
The first correctly fails silently and yields the default value. The second should throw an IndexSizeError exception.

**Comment by nox** [comment]
Your link is for `long` attributes:
> If a reflecting IDL attribute has a signed integer type (long) that is limited to only non-negative numbers then, (…)

HTMLInputElement.size is actually [`unsigned long`](https://html.spec.whatwg.org/multipage/infrastructure.html#limited-to-only-non-negative-numbers-greater-than-zero):
> If a reflecting IDL attribute has an unsigned integer type (unsigned long) then, on the other hand, it fails or returns an out of range value, or if the attribute is absent, the default value must be returned instead, or 1 if there is no default value.

See #5923, https://github.com/w3c/web-platform-tests/pull/1802, AFAICT the attribute you mention is already covered in WPT, with all its associated edge cases.

**Comment by jdm** [comment]
And the testcase from above?

**Comment by nox** [comment]
This is the intended behaviour AFAIK. Let me try to reread the tests code and see where the hell that's actually tested.

**Comment by jdm** [comment]
Oh right, my mistake. Firefox behaves the same as Servo. This is more relevant for #7323.

**Comment by nox** [comment]
https://github.com/servo/servo/blob/576aad5a1453c850f78c4cba8df9f0e0c6c8f13a/tests/wpt/web-platform-tests/html/dom/reflection.js#L422-L462 for the reference, and because I don't want to believe I looked around for that for nothing. :P
