### ISSUE TITLE
Implement ex and ch correctly from font metrics

### ISSUE THREAD

**Issue by nox** [servo/servo#7462]
ex is currently defined as 0.5em, this is conformant but we could do better and properly get the height of the x in the current font. ch is supposed to be the width of 0, but the spec says that it can also be defined as 0.5em.

Blocks #445.

https://drafts.csswg.org/css-values-3/#font-relative-lengths

**Comment by emilio** [comment]
Probably blocking stylo too. cc @bholley

**Comment by nox** [comment]
Closing as duplicate of #14079.
