### ISSUE TITLE
Write automated tests for devtools integration with network requests/responses

### ISSUE THREAD

**Issue by jdm** [servo/servo#7473]
We have code in `http_loader.rs` that sends notifications when a network request is sent as well as when a response is received. We now have the ability to write tests that check this since #7139 was merged. These should pass a real Sender value to `new_resource_task`, and compare the properties of the [NetworkEvent](http://mxr.mozilla.org/servo/source/components/devtools_traits/lib.rs#68) messages that should be received (on the corresponding Receiver) against the properties of the request and response objects.

Code: tests/unit/net/http_loader.rs

**Comment by psdh** [comment]
Working on this!

**Comment by jdm** [comment]
Yay!
