### ISSUE TITLE
Make AttrValue's tokens() and atom() return or panic

### ISSUE THREAD

**Issue by nox** [servo/servo#7479]
There is no reason an AttrValue should change variant once set, so we should refactor the API accordingly. This allows us to have better consistent panic messages in such cases.

**Comment by psdh** [comment]
Is this what you intend 
```
match *self {`
    AttrValue::Atom(ref value) => Some(value),
    _ => panic!(),
}
```

**Comment by nox** [comment]
@psdh Yes.

**Comment by nox** [comment]
Actually no, without the Some(_). And with a message passed to panic!().

**Comment by tafia** [comment]
What is the reason to prefer `panic` over `Result` ?
