### ISSUE TITLE
Add a mach command to upgrade wptrunner

### ISSUE THREAD

**Issue by jdm** [servo/servo#7491]
We should have a command to automate the steps at https://github.com/servo/servo/wiki/Upgrading-wptrunner . Additionally, it should skip the `git remote add` if it already exists (or just not abort if the command fails).

Code: python/servo/devenv_commands.py

**Comment by wilmoz** [comment]
I'd like to take this.

**Comment by jdm** [comment]
Ok!

**Comment by edunham** [comment]
@wilmoz thank you for the PR! Can this issue be closed now?

**Comment by jdm** [comment]
Yep!
