### ISSUE TITLE
Remove unused time function in time module of profile crate

### ISSUE THREAD

**Issue by connorimes** [servo/servo#7501]
The function `pub fn time<T, F>(msg: &str, callback: F) -> T` in the `time` module of the `profile` crate appears to be unused.  Perhaps left over from before there was a `profile` function in the `profile_traits` crate?
It should be removed to prevent confusion with the `profile` function.

**Comment by ddrmanxbxfr** [comment]
Good find !

Opening PR for it.

**Comment by frewsxcv** [comment]
Completed in #7504
