### ISSUE TITLE
Move setting UserAgent header into http_loader::load

### ISSUE THREAD

**Issue by jdm** [servo/servo#7541]
Headers have no meaning for protocols other than HTTP/HTTPS. This will make it easier to implement the [fetch spec](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch) in the future too, if we keep all of our HTTP-related code in one place.

Code: components/net/resource_task.rs, components/net/http_loader.rs

**Comment by jxs** [comment]
i can look into this one

**Comment by jdm** [comment]
@jxs You can; I could also help you find something more challenging, if you'd like :)
