### ISSUE TITLE
Add support for multipart/form-data

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7553]
This lets files be submitted via XHR or forms.

There's a parser [here](https://github.com/mikedilger/formdata), which we can use. I believe we already have enough Blob/File support for this, we just need to wire things up.

We should just mirror URLSearchParams and implement a [`serialize()`](https://github.com/servo/servo/blob/71b277d5675556e61a82ae9dbf3105449c3a8275/components/script/dom/urlsearchparams.rs#L129) on `FormData`, the rest of the plumbing for XHR should mostly be done already.

For forms, we'll need form upload control support, which we can try later.

**Comment by Manishearth** [comment]
I'm willing to mentor anyone who wants to try their hand at this.

**Comment by psdh** [comment]
I can take a shot at this!

**Comment by Ms2ger** [comment]
By default, I don't trust libraries that don't say if they conform to any spec.

**Comment by nox** [comment]
By default, I would rather fix things than reinvent the wheel. We should contact its authors and ask if they are interested working with us on spec-compliance, IMO.

**Comment by Wafflespeanut** [comment]
@psdh are you still working on this?

**Comment by mikedilger** [comment]
`formdata` is meant to comply with RFC 7578 and be backwards compatible with some of RFC 2388 but I can't guarantee that and in fact I haven't sat down and rigorously ensured anything at this point.

Also, `formdata` was written for server-side parsing of browser submitted forms, not client-side generation.  Some of the data structures could be shared, but at present I fail to see how to use it client-side in its current form.

I'm happy to consider restructuring and having support for both client and server in the same library... and in that vain, to grant push access and ownership to any servo folks who will be making significant contributions.

**Comment by KiChjang** [comment]
@psdh any progress on this?

**Comment by psdh** [comment]
@KiChjang I had started out with going through the mikedilger/formdata, adding links to the spec. I'll be able to devote time to only after the 14th (exams till then). I don't want to block it. Take it up if you want to!

**Comment by jdm** [comment]
Let us know if/when you start working on it again, in that case :)

**Comment by psdh** [comment]
mikedilger/formdata#20

**Comment by KiChjang** [comment]
This is part of #3649.

**Comment by jdm** [comment]
This is being implemented in #9198 if I'm not mistaken.

**Comment by jdm** [comment]
#9198 stalled, so anybody taking on this task should focus on rebasing the changes and addressing the [most recent review comments](https://github.com/servo/servo/pull/9198#issuecomment-191449218). Note, I rebased it locally and discovered that the `mime` crate needs to be updated to 0.2 for compilation to succeed.
