### ISSUE TITLE
Inline elements with padding show unexpected height changes when they're near a line-break

### ISSUE THREAD

**Issue by emilio** [servo/servo#7554]
Reduced test-case:

``` html
<!doctype html>
<meta charset="utf-8">
<style>em { padding: 3px; background: #ccc; }</style>
<p>Lorem ipsum dolor sit <em>amet</em>, consectetur adipiscing elit. Donec <em>condimentum</em> nisi vitae dolor sollicitudin vehicula.</p>
```

When resizing near the second `<em>` (making the line break and going back again, sometimes a few resizes are needed) the background starts growing and I get an output similar to the following:

![servo-inline-padding](https://cloud.githubusercontent.com/assets/1323194/9719356/cce4cd0c-5583-11e5-828b-2a001cf9aad1.png)

This doesn't happen with `display: inline-block`, so I guess the problem is in `layout/inline`, but I'm not sure where exactly... If @pcwalton gives me some details about where to start looking at, I can try to track it down and fix it :)

**Comment by stshine** [comment]
Looks like this is fixed?

**Comment by emilio** [comment]
Yup! Works for me :)
