### ISSUE TITLE
rust-clipboard is GPL

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7578]
At the time of writing, rust-clipboard is licensed GPL, and servo depends on rust-clipboard.

/cc @meh @aweinstock314

**Comment by metajack** [comment]
Ack.

We'll have to remove it unless the license is changed I think. Servo dependencies must be MPL compatible. @aweinstock314 are you interested in changing the license?

**Comment by meh** [comment]
@metajack me and @aweinstock314 already talked about it, I'm going to rewrite the X11 side and improve the API a little, and change the license to MPL.

For the record it's GPL because the X11 code was basically taken out from xclip, while the code I have was written from scratch.

**Comment by frewsxcv** [comment]
https://github.com/conradkleinespel/rustastic-clip/blob/master/src/lib.rs might be another option here

**Comment by jdm** [comment]
`rclip works exclusively on UNIX with the X server.` is sad-making.

**Comment by mbrubeck** [comment]
Fixed by https://github.com/aweinstock314/rust-clipboard/commit/241c3f0fc5843db861bc0b44d682bf501e651e9b

**Comment by frewsxcv** [comment]
rust-clipboard is still GPLv2

https://github.com/aweinstock314/rust-clipboard#license

https://github.com/aweinstock314/rust-clipboard/blob/f4c5c1d3c1759f0a167091405d11af1f9584fb1f/Cargo.toml#L8

**Comment by larsbergstrom** [comment]
We are now shipping Servo Nightly builds. I think we need to get this fixed or remove this dependency ASAP.

**Comment by frewsxcv** [comment]
A short term alternative would be to strip the GPL parts for now (leaving copy + paste broken on Linux) and shipping that.

**Comment by larsbergstrom** [comment]
That would be fine to me. We absolutely cannot be linking GPL code into Servo.

cc @metajack

**Comment by metajack** [comment]
@frewsxcv Are you going to do this work? It seems like it would be acceptable to put the GPL code behind a non-default feature gate. Alternatively we could not call that code so that it's not linked in. But I'm wary of solutions that may regress without us watching if the code is not excised from rust-clipboard.

**Comment by frewsxcv** [comment]
My `$DAYJOB` and `$FOSS` queues are pretty long right now, so I wouldn't be able to get to it soon. Wish I could, but it's not feasible for me right now.

**Comment by jrmuizel** [comment]
rust-clipboard has now been re-licensed as Apache-2.0 so clipboard support can be re-added.
