### ISSUE TITLE
keyboard events should be dispatched to the window object

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7579]
`keyup`, `keydown` and `keypress` events are not dispatched to the window object.

Related issue: https://github.com/servo/servo/issues/6733

**Comment by jdm** [comment]
Ah, the code at http://mxr.mozilla.org/servo/source/components/script/dom/document.rs#744 defaults to dispatching the event at the body element if it exists and there is no focused element.

**Comment by paulrouget** [comment]
The problem I run into is that the event is not dispatched to the window during the capture or the bubbling phase.

This code is about the target, right?

**Comment by paulrouget** [comment]
```html
<body></body>

<input type="text">

<script>

  window.addEventListener('keyup', () => {
    console.log(1);
  });

  document.body.addEventListener('keyup', () => {
    console.log(2);
  });

</script>
```

I focus the text input. Type some text.

I see only "2" in the console, not "1".

**Comment by jdm** [comment]
Ah, my mistake. You're right that #6733 will solve this too.
