### ISSUE TITLE
Strange CSSWG reftest comparing two -ref files

### ISSUE THREAD

**Issue by jdm** [servo/servo#7585]
/css21_dev/html4/reference/block-in-inline-insert-006-nosplit-ref.htm and /css21_dev/html4/reference/reference/block-in-inline-insert-006-ref.htm are compared, and the reftest harness can't find the second file. Very confusing. There's also an ini file for /css21_dev/html4/reference/reference/block-in-inline-insert-006-ref.htm in http://mxr.mozilla.org/servo/source/tests/wpt/metadata-css/css21_dev/html4/reference/block-in-inline-insert-006-ref.htm.ini?force=1 .

**Comment by jdm** [comment]
This is true for all of the `block-in-inline` tests that I can see. The reftest analyzer shows a bunch of failures for test files in the `/reference` subdirectory.

**Comment by Ms2ger** [comment]
CC @jgraham.

I believe the csswg uses a reference for a reference in case they want to check that a test matches two references.

**Comment by nox** [comment]
@jgraham Can you confirm that there is no actual issue here?

**Comment by jgraham** [comment]
Yeah, this is an actual thing.
