### ISSUE TITLE
Support for WebIDL stringifier attributes

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7590]
[Related Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=824857)

[Spec link](https://heycam.github.io/webidl/#idl-stringifiers) - Starting with "The stringifier keyword can also be placed on an attribute."

[Example in URLUtils.webidl](https://github.com/servo/servo/blob/347e9b6ef45fb8b0e5a824944e4b1c7338d15554/components/script/dom/webidls/URLUtils.webidl#L9)

**Comment by jdm** [comment]
We support them already: http://mxr.mozilla.org/servo/source/components/script/dom/webidls/URLSearchParams.webidl#18 and http://mxr.mozilla.org/servo/source/components/script/dom/urlsearchparams.rs#121 are an example of existing usage. See #1986.

**Comment by nox** [comment]
We support stringifiers, not stringifier **attributes**.
