### ISSUE TITLE
Write tests for cookie behaviour with HTTP redirects

### ISSUE THREAD

**Issue by jdm** [servo/servo#7604]
I am interested in tests that ensure that:
* when a redirect from a.com to b.com is processed, the request to b.com contains cookies for b.com
* when a redirect from a.com to a.com is processed, any cookies set in the redirected response are sent in the second request

The existing `test_load_sets_cookies_in_the_resource_manager_when_it_get_set_cookie_header_in_response` and `test_load_sets_requests_cookies_header_for_url_by_getting_cookies_from_the_resource_manager` tests are good ones to model this work off of.

Code: tests/unit/net/http_loader.rs

**Comment by jdm** [comment]
`test_load_follows_a_redirect` is one of many that demonstrates how to model redirects in automated tests.

Also, the tests can be run with `./mach test-unit -p net`, if I recall correctly.

**Comment by askalski** [comment]
I gave it a try, and I feel I have the first one:
https://github.com/askalski/servo/commit/a41e9375dfdc2786fc1c5ee54a9c6b67a1485a8e

If you this is any good, please assign me to this bug.

**Comment by askalski** [comment]
btw, I am a total noob in Rust, so if there are some semantical upgrades to make, please attach a link to tutorial/examples describing this language feature.

**Comment by jdm** [comment]
That looks great to me :)

**Comment by askalski** [comment]
submitted pull request:
https://github.com/servo/servo/pull/7617

**Comment by askalski** [comment]
is it submitted correctly, or should I send a patch to some website like at Bugzilla?

**Comment by jdm** [comment]
Nope, you did the right thing :)

**Comment by askalski** [comment]
I think it's ready for review.

**Comment by askalski** [comment]
can you assign the bug again to me for another several days? I am working on this.

**Comment by jdm** [comment]
It's already marked assigned; see the C-assigned label.

**Comment by askalski** [comment]
I made another PR for this, and closed the previous one. Please review:
https://github.com/servo/servo/pull/9039

**Comment by KiChjang** [comment]
Fixed by #9039.
