### ISSUE TITLE
Enable Pattern variant of CanvasFillOrStrokeStyle

### ISSUE THREAD

**Issue by jdm** [servo/servo#7608]
There's a commented out variant for dealing with patterns as part of the canvas fill/stroke APIs. It was waiting on #6157, which is now complete. Completing this task likely involves looking at what the surrounding code does for each piece of code that deals with the CanvasFillOrStrokeStyle enum and making smart choices (or asking questions if stumped!).

Code: components/script/dom/canvasrenderingcontext2d.rs

**Comment by mattnenterprise** [comment]
I would like to do this

**Comment by jdm** [comment]
@mattnenterprise I actually have a student that is intending to work on this; sorry. I appreciate that you asked first!

**Comment by 0X1A** [comment]
@jdm I'm up for this
