### ISSUE TITLE
Make `mach test` work with Rust unit tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#7618]
We should enable `./mach test tests/unit/net/http_loader.rs` to make it really easy for people to execute unit tests. This would be converted internally to `./mach test-unit -p net`; if there's some way to only execute the tests for the `http_loader` module, that would be even better.

Code: python/servo/testing_commands.rs

**Comment by SimonSapin** [comment]
Regarding the latter part, from `cargo test --help`:

> All of the trailing arguments are passed to the test binaries generated for
filtering tests and generally providing options configuring how they run. For
example, this will run all tests with the name `foo` in their name:
>
>     cargo test foo

In the default unit test harness, I believe "positional" arguments are interpreted as substring patterns that apply to test "names", which are paths from the crate root like `http_loader::test_load_sets_content_length_to_length_of_request_body`.

**Comment by askalski** [comment]
well, I just called `./mach test-unit -p net http_loader::` and it seems like it gave me results filtered to "http_loader". So what you are asking is that we translate a filename to some "test-unit" suffix? If so, I have two questions:
1) are the prefixes unique to the file
2) where I can find docs about how these name get generated :)

**Comment by jdm** [comment]
The names match precisely with the filenames of the modules and crates, so `./mach test-unit -p style` will run the tests under the `style` crate, which lives in `tests/unit/style`.

**Comment by jdm** [comment]
The prefixes are not necessarily unique, as there could be a `mod http_loader` in some other file in net, but I think this is a good enough approximation to be useful.
