### ISSUE TITLE
Write unit tests for cookie isolation

### ISSUE THREAD

**Issue by jdm** [servo/servo#7624]
We are missing tests for the following functionality:
* when a cookie is set for domain a.com with CookieSource::NonHttp, it should not be included in a subsequent request for a.com
* when a cookie is received that is marked httpsOnly, it is ignored if the request was for an http connection (instead of https)
* when a cookie is set for a.com and is marked httpsOnly, it is not sent as part of requests that are for http://a.com

Code: tests/unit/net/http_loader.rs

**Comment by jxs** [comment]
can i take this one?

**Comment by jdm** [comment]
@jxs Sure!

**Comment by jxs** [comment]
this should be 3 different tests right?

**Comment by jdm** [comment]
Yes please!

**Comment by jdm** [comment]
My mistake; the property we care about for cookies is called `secure`, not `httpsOnly`: https://github.com/alexcrichton/cookie-rs/blob/master/src/lib.rs#L64 . The cookie string should look something like this: https://github.com/alexcrichton/cookie-rs/blob/master/src/lib.rs#L234
