### ISSUE TITLE
Misalignment of comment number thing on deviantart

### ISSUE THREAD

**Issue by mdinger** [servo/servo#7636]
[Testcase1](https://mdinger.github.io/servo_7636/testcase1.html):

``` html
<html>
<head>
<style>
    body {float:right;}
    .outer{margin-left:10px}
    .inner{ display:inline-block; }
</style>
</head>
<body>
    <span class="outer">
        <span class="inner"> text</span>
        <span>text</span>
    </span>
</body>
</html>
```

Shows up on deviantart:
![servo](https://cloud.githubusercontent.com/assets/4156987/9867157/6c42cd40-5b38-11e5-974e-dcc034fb5b6e.png)

**Comment by mdinger** [comment]
Updated with linked testcase

**Comment by jdm** [comment]
Thanks for the testcase @mdinger!

**Comment by pcwalton** [comment]
cc-ing myself, @pcwalton

**Comment by notriddle** [comment]
I think this is #2261.

**Comment by mdinger** [comment]
Still a problem with 31657811d33f23c79eae49dea171718562b031c5
