### ISSUE TITLE
Report usages of &Vec<T> in function arguments

### ISSUE THREAD

**Issue by jdm** [servo/servo#7640]
There's no reason for a function to accept a `&Vec<T>` argument instead of `&[T]`, since they allow the same operations and the first is an extra pointer dereference. We should check for the string `: &Vec<` in Rust source files and report any instances found.

Code: python/tidy.py

**Comment by jdramani** [comment]
I think I can do it.

**Comment by jdm** [comment]
Great!

**Comment by wilfreddenton** [comment]
I'm new to Rust so I just need some clarification. I thought that vectors allow for adding and removing elements whereas arrays do not. A function needing to manipulate a collection parameter's items would need the parameter to be a vector, no?

**Comment by jdm** [comment]
Those would need to be mutable, ie. &mut Vec. Immutable references provide no additional functionality over slices.

**Comment by wilfreddenton** [comment]
Oh right. thanks for the help!

**Comment by sinistersnare** [comment]
It seems clippy has [this lint](https://github.com/Manishearth/rust-clippy/wiki#ptr_arg)

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/7643
