### ISSUE TITLE
AssertRequestMustHaveHeaders doesn't work with empty headers

### ISSUE THREAD

**Issue by jdm** [servo/servo#7647]
Specifically, `AssertRequestMustHaveHeaders` is only asserting the presence of any headers passed in. It cannot be used to assert the absence of headers right now, which is confusing given the name. I suggest renaming `AssertRequestMustHaveHeaders` to `AssertRequestMustIncludeHeaders`, asserting that the provided headers are not empty, and adding a new `AssertRequestMustHaveHeaders` that checks that the request headers exactly match the expected headers - ie. any keys present in one set of headers but not the other must cause a test failure.

Code: test/unit/net/http_loader.rs

**Comment by psdh** [comment]
@jdm I'll work on this immediately after hyperium/hyper#656 lands.

**Comment by jdm** [comment]
Great!
