### ISSUE TITLE
Redirect to an error page when a local file or URL cannot be loaded.

### ISSUE THREAD

**Issue by glennw** [servo/servo#7658]

**Comment by glennw** [comment]
It can be confusing that running with an incorrect file path results in a blank white screen, we should show some kind of error page.

**Comment by jdm** [comment]
Agreed. I'll write up how to fix this.

**Comment by jdm** [comment]
The most likely place to handle this is in ScriptTask::handle_page_fetch_complete; if we notice that the provided metadata's status is 404, we could probably go ahead and remove the pending load, but start another one for the same pipeline that requests a 404.html from the local resources instead.

**Comment by Mylainos** [comment]
I would like to work on this issue !

How would it handle the status 404 if a page is return ? Like this one http://doc.servo.org/script/script_task/struct.InProgressLoad.htmlqsg

**Comment by jdm** [comment]
The `status` field of `Metadata` contains that information: http://doc.servo.org/hyper/http/struct.RawStatus.html

**Comment by Mylainos** [comment]
I know but how could I know if there is a page return by the server. We don't want to load the about:404 page if there is a special page return by the server.

**Comment by jdm** [comment]
Oh, I see what you mean. That's a good point; I'll need to think about it.

**Comment by jdm** [comment]
You could check if the body is empty, I suppose?

**Comment by Mylainos** [comment]
I report this error #7684. I can't continue this one before it's fixed

**Comment by Wafflespeanut** [comment]
I'll take this.
