### ISSUE TITLE
Add support for @keyframe animation

### ISSUE THREAD

**Issue by glennw** [servo/servo#7663]
Most of the support for animation is in place (since transitions are supported). The majority of the work for this task is likely to be parsing the @keyframe information correctly.

**Comment by SimonSapin** [comment]
Would it be a good idea to implement [Web Animations](https://w3c.github.io/web-animations/) first, and then `@keyframes` on top of it?

**Comment by dzbarsky** [comment]
I think the spec for how Animations are represented in terms of Web Animations hasn't settled down yet, but it's probably still worth doing

**Comment by pcwalton** [comment]
I think there's not going to be a bad interaction with WebRender animations as long as we keep everything nice and unified under the current setup.

**Comment by jdm** [comment]
We support this.
