### ISSUE TITLE
Implement Storage::SupportedPropertyNames

### ISSUE THREAD

**Issue by jdm** [servo/servo#7670]
This should return the list of all keys for this storage: https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface:supported-property-names

**Comment by jdm** [comment]
Code: components/script/dom/storage.rs

**Comment by jdm** [comment]
This should make `sessionStorage['foo']` equivalent to `sessionStorage.foo`; I would expect the former to be undefined right now.

**Comment by jdm** [comment]
Note: this was filed proactively as a task for a particular contributor to work on, so please talk with me before working on it if I have not directly suggested you should work on it.

**Comment by Ms2ger** [comment]
> This should make sessionStorage['foo'] equivalent to sessionStorage.foo; I would expect the former to be undefined right now.

This isn't correct; it should help with `Object.getOwnPropertyNames(storage)`, though.

**Comment by frewsxcv** [comment]
Related to https://github.com/servo/servo/issues/7273

**Comment by ddrmanxbxfr** [comment]
I've opened a PR for it. Implemented and done some unit test on it like @frewsxcv did for htmlproperties.

If it looks ok, I'll keep on working implementing more :).

Thanks.

**Comment by ddrmanxbxfr** [comment]
Oh oops @jdm I didn't read the comment of warning you before. I saw the issue as unassigned. :\

Anyways, feel free to take my pr on it if you want.

**Comment by jdm** [comment]
Ack. :( I'll figure out what to do here.

**Comment by ddrmanxbxfr** [comment]
There's still plenty SupportedPropertyNames to implement from here, do you want me to open issues on those before working on them @jdm ?

**Comment by jdm** [comment]
I'll claim #7695 as a replacement.

**Comment by ddrmanxbxfr** [comment]
@jdm Ok not touching at those then :).

**Comment by frewsxcv** [comment]
Completed in #7693 by @ddrmanxbxfr
