### ISSUE TITLE
Implement overscroll

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7671]
Safari and Chrome have an "elastic" overscroll effect. Both on desktop and mobile.

Is that something we could get with Servo?

**Comment by notriddle** [comment]
Spelling nit: s/Imlement/Implement/

**Comment by paulrouget** [comment]
This is not a blocker, but I was wondering how hard it would be to implement such feature?

Cocoa equivalent: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSScrollView_Class/#//apple_ref/c/tdef/NSScrollElasticity
