### ISSUE TITLE
Implement scrollgrab

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7672]
When scrolling, we want to be able to give a parent layer the priority.

Relevant bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=912666

**Comment by paulrouget** [comment]
In this test, we want to div to scroll before the iframe:

```html
<style>
  div {
    height: 400px;
    width: 400px;
    overflow: scroll;
    border: 20px solid red;
  }

  h1 {
    height: 20px;
  }

  iframe {
    background: white;
    height: 400px;
    width: 400px;
    border: none;
  }

</style>

<div mozscrollgrab="true">
  <h1>foo</h1>
  <iframe src="http://paulrouget.com" mozbrowser="true"></iframe>
</div>
```

**Comment by paulrouget** [comment]
@glennw / @pcwalton could you describe what would need to be done to implement this?

**Comment by pcwalton** [comment]
Probably just have a flag on the scroll layer, propagate that down through all the layers of WebRender data structures, and use that to determine which layer should scroll when dispatching scroll events in WR.

**Comment by paulrouget** [comment]
This was relevant for Firefox OS, and for browserhtml when we were building scrollout toolbar based on scrollgrab and snappoints. It is not the case anymore, and scrollgrab is not part of any spec.

Closing.
