### ISSUE TITLE
Implement CustomAutoRooter/AutoGCRooter equivalent

### ISSUE THREAD

**Issue by jdm** [servo/servo#7676]
Potential vtable-based replica solution: https://gist.githubusercontent.com/michaelwu/a9525f07112a8224a540/raw/5d440e2f3b6cb4b1305bee2a8873a54e7c740aa4/jsapi.rs

https://dxr.mozilla.org/mozilla-central/source/js/src/jsapi.h?from=customautorooter#467
https://dxr.mozilla.org/mozilla-central/source/js/src/jspubtd.h#189

I'll push a branch I started and discuss some of the problems I encountered.

cc @michaelwu

**Comment by nox** [comment]
Any news on this?

**Comment by jdm** [comment]
https://groups.google.com/forum/#!topic/mozilla.dev.servo/tqqwgAmhp8o
