### ISSUE TITLE
Wrong http status when opening a file which doesn't exist

### ISSUE THREAD

**Issue by Mylainos** [servo/servo#7684]
When opening a file which doesn't exist, the 404 status is expected. Instead it's the 200 which is given.

**Comment by Mylainos** [comment]
If you want to test, add this at the 1402 line of `components/script/script_task.rs` :
```rust
println!("{:?}", metadata.status);
```

**Comment by Mylainos** [comment]
These attributes are not set when it's a local file:
```
content_type : None
charset : None
headers : None
```
Should I create a new issue ?

**Comment by jdm** [comment]
Yeah, this should be fixed along with #4212. Want to try fixing that one?

**Comment by Mylainos** [comment]
Ok ! I lose here http://mxr.mozilla.org/servo/source/components/script/network_listener.rs#48 where Metadata come from and it's not modified before.

**Comment by jdm** [comment]
Look at ResponseAction in net_traits/lib.rs; that's where it is stored, and then you can find the code that creates the HeadersAvailable value in net/resource_task.rs if I recall correctly (apologies, I'm on a phone).

**Comment by Wafflespeanut** [comment]
As of #8650, the metadata won't reach `script_task`, and so I guess this can be closed :)
