### ISSUE TITLE
Tidy has an off-by-one error

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#7686]
[This commit](https://github.com/servo/servo/commit/07cde59535b1148c149cc026529d608ad60ed8d7) has missed something. It doesn't actually check for 120 chars, but [119 chars](https://travis-ci.org/servo/servo/builds/81230487#L116) ([here's the line](https://github.com/Wafflespeanut/servo/blob/alpha_lints/components/plugins/lints/sorter.rs#L162) which breaks tidy, whose [length is 119](http://is.gd/0p1pat)). So, educate tidy to break only for more than 120 chars...

<small> Code: `python/tidy.py` </small>

**Comment by ddrmanxbxfr** [comment]
Just opened a PR for it to raise error at over than 120.

Makes sense.

**Comment by Wafflespeanut** [comment]
fixed by #7692
