### ISSUE TITLE
Integrate plugins into the remaining crates and check for `to_strings`...

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#7699]
[We have a lint](https://github.com/servo/servo/blob/master/components/plugins/lints/str_to_string.rs) which forbids the usage of `to_string` (as it's less efficient compared to the `to_owned` alternative). The `plugins` crate has been integrated into most of the crates and the `to_string` methods lurking there have already been destroyed.

But, [compositing](https://mxr.mozilla.org/servo/source/components/compositing/lib.rs) and [net](https://mxr.mozilla.org/servo/source/components/net/lib.rs) crates don't make use of `plugins` and so, they still have the leftover `to_string` methods. Let's destroy them too! :)

<small>Note: All the other crates which have `plugins` can serve as an example...</small>

**Comment by mskrzypkows** [comment]
I'd like to take this.

**Comment by Wafflespeanut** [comment]
fixed by #7707
