### ISSUE TITLE
border-radius > 0 between horizontal border with width > 0 and vertical border with width == 0 causes panic in intersect_ellipse_linein combination with 

### ISSUE THREAD

**Issue by tschneidereit** [servo/servo#7700]
The following code causes the crash:

```html
<html>
<head>
</head>
<body>
<div style="border-top: 30px solid black; border-radius: 15px"></div>
<div style="border-right: 30px solid black; border-radius: 15px; height: 30px"></div>
<div style="border-bottom: 30px solid black; border-radius: 15px"></div>
<div style="border-left: 30px solid black; border-radius: 15px; height: 30px"></div>
</body>
```

The issue is caused by `draw_corner` not dealing correctly with 0-width borders [here](https://github.com/servo/servo/blob/master/components/gfx/paint_context.rs#L675-L678).

Replacing the `if inner_border.x >= outer_border.x {` with the following conditions fixes the crash, but I'm not sure it's the right solution:

```rust
if inner_border.x == outer_border.x {
  0f32
} else if inner_border.x > outer_border.x {
...
```

**Comment by jdm** [comment]
cc @bjwbell

**Comment by bjwbell** [comment]
@tschneidereit @jdm sorry! I should have been more thorough in my testing.

Looking at the code...
