### ISSUE TITLE
Make it possible to set the coordinates of the window controls

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7705]
In Browser.html, the default position of the window controls (close,max,min buttons) is wrong:

<img width="382" alt="screen shot 2015-09-22 at 10 41 31" src="https://cloud.githubusercontent.com/assets/373579/10014190/e1f07bca-6117-11e5-830d-a0d66348787f.png">

We at least need a glutin method to set the window controls coordinates.

Then, maybe we can hardcode the position in Servo, or, like in Gecko, let the document define the position of the controls (gecko uses `-moz-appearance: -moz-window-titlebar`).

**Comment by waddlesplash** [comment]
Why does the URL bar say 'HTTP' not 'HTTPS' here? Is that a miscommunication between Servo and Browser.html?

**Comment by jdm** [comment]
Presumably we don't implement the appropriate events to inform the embedding about redirects.

**Comment by paulrouget** [comment]
> Why does the URL bar say 'HTTP' not 'HTTPS' here? Is that a miscommunication between Servo and Browser.html?

Oh, ignore the content of the screenshot. It's a prototype. The URL is hardcoded.

**Comment by paulrouget** [comment]
I've been trying to use `button.setFrame` and `button.setFrameOrigin`, but for some reason, I can only change the size of the buttons, not their position.

**Comment by paulrouget** [comment]
That's up to the embedder now. In the case of winit-based windows, one can use `WindowExt::get_nswindow()` to access the buttons and move them around.
