### ISSUE TITLE
layout::wrapper::as_element allows the creation of unbounded lifetimes

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7715]
https://github.com/servo/servo/blob/master/components/layout/wrapper.rs#L369

``` rust
fn as_element<'le>(node: LayoutJS<Node>) -> Option<LayoutElement<'le>> {
    ElementCast::to_layout_js(&node).map(|element| {
        LayoutElement {
            element: element,
            chain: PhantomData,
        }
    })
}
```

If used in the wrong context, this might end up creating a `LayoutElement<'static>` or something else that has a lifetime longer than its actual lifetime.

I'm not really familiar with the invariants being maintained for the unsafe code here, but this function doesn't look right to me.

Perhaps it should be `unsafe`? [`LayoutNode::new_with_this_lifetime()`](https://github.com/servo/servo/blob/master/components/layout/wrapper.rs#L98), which does something similar, is `unsafe`.

cc @pcwalton @mbrubeck

**Comment by Ms2ger** [comment]
Yeah, probably. It's only called in two places, and those are both "safe". This entire file is a house of cards, though.

**Comment by Manishearth** [comment]
It seems like LayoutJS should have a lifetime, with unsafe methods for transmuting the lifetime when needed.

Still a house of cards, but at least stuff would be explicit.

**Comment by Ms2ger** [comment]
I've been thinking about that. Unfortunately we'd need to implement a similar unbounded cast in `LayoutJS::from_trusted_node_address`.

**Comment by Manishearth** [comment]
Sure, but that can be unsafe. It makes sense for that to be unsafe.

**Comment by nox** [comment]
That method is dead.
