### ISSUE TITLE
Implement Document#charset.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7718]
Blocks #2185.

* Spec: <https://dom.spec.whatwg.org/#dom-document-charset>.
* Code: `components/script/dom/document.rs`, `components/script/dom/webidls/Document.webidl`.
* Test: `dom/interfaces.html`, `dom/nodes/DOMImplementation-createDocument.html`, `dom/nodes/DOMImplementation-createHTMLDocument.html`, `dom/nodes/Document-characterSet-normalization.html`, `dom/nodes/Document-constructor.html`, `dom/nodes/Node-properties.html`, `domparsing/DOMParser-parseFromString-html.html`, `domparsing/DOMParser-parseFromString-xml.html`, `html/dom/interfaces.html`, (possibly) `dom/historical.html`                                                  .

**Comment by g-k** [comment]
I can take a shot at this.

**Comment by jdm** [comment]
Please do!

**Comment by vectorijk** [comment]
So sorry to steal your task. ref #7966

**Comment by g-k** [comment]
No worries, I never started it.
