### ISSUE TITLE
Add support for :target pseudo-selector

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7720]
See https://github.com/servo/servo/issues/7720#issuecomment-224279985 for instructions on how to solve this.

Relevant spec: https://html.spec.whatwg.org/multipage/scripting.html#selector-target

**Comment by Manishearth** [comment]
For efficiency, _first_ check if the fragment matches the elements id or name, and then proceed with doing a document traversal.

@SimonSapin It occurs to me that pseudo-selectors that depend on a property of the _document_, rather than a direct property of the element (e.g. `:target`, `:current`, etc) are quite inefficient with `querySelector()`, since for each element, one must access the document, fetch some properties, and possibly do a tree traversal. This is in contrast with other selectors where it's always a local check.

I'm not sure how Servo's style updates happen, but there's also a chance for inefficiency there. Would these selectors cause a lot of churn on DOM manipulations?

**Comment by mbrubeck** [comment]
For what it's worth, Gecko and Blink do not seem to recalculate `:target` matching when the DOM changes, as seen in this test case:

```
<html>
  <head>
    <style>
      :target { color: red; }
    </style>
  </head>
  <body>
    <ul><li id="foo">hello</li></ul>
    <script>
      document.querySelector("ul").addEventListener("click", function() {
        this.insertBefore(this.firstChild.cloneNode(true), this.firstChild);
      });
    </script>
  </body>
</html>
```

**Comment by SimonSapin** [comment]
Yeah, we probably don’t want to traverse the document every time `:target` is matched on a given element. Could we maintain a "targeted" flag on every element? These flags would need to be updated (at least) when an element is inserted or removed, when an `id` or `name` attribute is added/removed/modified, or when the fragment identifier of the document’s URL changes.

**Comment by Manishearth** [comment]
Using NodeFlags? That sounds like a good idea. I don't like stuffing lots of flags into NodeFlags, but for now that seems okay.

This still requires a full dom traversal whenever a node is moved. We can improve it so that it first does a traversal of the moved node though.

**Comment by Wafflespeanut** [comment]
I'll gladly take it :)

**Comment by gilles-leblanc** [comment]
I'd like to take a look at this one. Will be the hardest thing I have tackled on Servo as of yet.

**Comment by Manishearth** [comment]
This really depends on that spec issue being resolved. We could do a correct but somewhat inefficient implementation now, though.

**Comment by gilles-leblanc** [comment]
@Manishearth Ok, I'll look for another one then. I hadn't realized it was waiting on the spec being resolved.

**Comment by jdm** [comment]
@Manishearth What's the specification status here? If this isn't ready for someone to work on it, we should remove the less easy tag.

**Comment by Manishearth** [comment]
I plan to fix the spec issue, but detagged for now

**Comment by SimonSapin** [comment]
The spec was changed in https://github.com/whatwg/html/pull/1370

**Comment by Manishearth** [comment]
The specification has been updated.

To solve this bug, you need to:

 - Undo https://github.com/servo/rust-selectors/pull/54, get a new version published
 - Add a `target_element` field to the document (https://html.spec.whatwg.org/multipage/browsers.html#target-element)
 - Set/reset it whenever the document scrolls to the indicated part of the document (https://html.spec.whatwg.org/multipage/browsers.html#the-indicated-part-of-the-document), in `handle_navigate` in `script_thread`

**Comment by SimonSapin** [comment]
> Undo servo/rust-selectors#54, get a new version published (until the changes are published, use a local cargo override)

That is not needed: since then, the handling of pseudo-classes other than "tree structural" ones has been made generic and left to users of rust-selectors to implement themselves. In Servo, that happens in `components/style/selector_impl.rs` where you’ll need to add a variant to the `NonTSPseudoClass` enum and parse it in `parse_non_ts_pseudo_class`.

**Comment by sjmelia** [comment]
I'd like to pick this up, i've made some progress already but have a few questions, do I open a pull request?

**Comment by Manishearth** [comment]
Sure, feel free to open a pull request and ask any questions you have.

What flag?

**Comment by sjmelia** [comment]
Great! R.e. flag, sorry - I meant the "i-spec-unclear" label, I read your comment above as indicating that the spec was clarified and the selected element is not affected by dom changes.

**Comment by Manishearth** [comment]
oh, yeah, that label can be removed
