### ISSUE TITLE
Eyes don't always load in Acid2

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#7722]
Currently `tests/html/acid2.html` looks like this for me:

![bug](https://cloud.githubusercontent.com/assets/13536/10060917/7c8c310a-6209-11e5-8051-36317f676fe8.png)

I have bisected the issue to https://github.com/servo/servo/commit/040c09fbc51ac282b7224799851d62cd3a60ee7f .

cc @mbrubeck

**Comment by glennw** [comment]
@mrobinson Does it become correct if you hover your mouse over the browser window?

**Comment by mrobinson** [comment]
@glennw Hovering and clicking don't seem to improve things.

**Comment by mrobinson** [comment]
I have noticed that scrolling to the eyes instead of using the anchor link prevents this from happening.

**Comment by Croydon** [comment]
This could be added to the Layout: Acid2 milestone.

**Comment by jdm** [comment]
It could, but that milestone is meaningless at this point.

**Comment by kubrickfr** [comment]
Linux x86_64, GeForce GTX 960, scrolling up and down screencast:

https://drive.google.com/file/d/0ByPjAhK7ObclS29ucE91RVRZM28/view?usp=sharing

**Comment by pcwalton** [comment]
That's not a bug. Or, rather, if it is, the bug is that Acid2 is scrollable. If you were to hack Acid2 to be scrollable on other browsers, you'd see the same thing.

**Comment by cmr** [comment]
@pcwalton loading the servo acid2.html in firefox does not have the red strip demonstrated.

(The issue isn't the blocks when scrolling)

**Comment by cmr** [comment]
![2016-03-15-104627_803x754_scrot](https://cloud.githubusercontent.com/assets/704250/13763573/33cb116e-ea9b-11e5-83a5-d3e6eb5c246b.png)

**Comment by pcwalton** [comment]
In that case it's that the image didn't load.

**Comment by bvdeenen** [comment]
I have the same bug on servo e551ea73226404152e02c3445f4f91e639bf66ce

My software

    Ubuntu 14.04.4 LTS
    VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)

What else would you like to know?

**Comment by woshilapin** [comment]
I'm having the bug on servo 0fa10df.

```
./mach run -d -- "http://www.webstandards.org/files/acid2/test.html#top"
```

My hardware and software

```
Debian GNU/Linux 8 (jessie)
Linux myhostname 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV710/M92 [Mobility Radeon HD 4530/4570/545v]
```

For more information about graphic driver, I've used the command explained [here](http://askubuntu.com/a/28036).

```
lspci | grep VGA ; lsmod | grep "kms\|drm" ; find /dev -group video ; \
cat /proc/cmdline ; find /etc/modprobe.d/; cat /etc/modprobe.d/*kms* ; \
ls /etc/X11/xorg.conf ; glxinfo | grep -i "vendor\|rendering" ; \
grep LoadModule /var/log/Xorg.0.log
```

Here is the result.
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV710/M92 [Mobility Radeon HD 4530/4570/545v]
drm_kms_helper         49210  1 radeon
drm                   249998  6 ttm,drm_kms_helper,radeon
i2c_core               46012  7 drm,i2c_i801,drm_kms_helper,i2c_algo_bit,v4l2_common,radeon,videodev
/dev/video0
/dev/fb0
/dev/dri/card0
/dev/dri/controlD64
BOOT_IMAGE=/vmlinuz-3.16.0-4-amd64 root=UUID=cf985b84-080d-4319-8d80-d9419518d1a7 ro initrd=/install/initrd.gz quiet
/etc/modprobe.d/
/etc/modprobe.d/dkms.conf
/etc/modprobe.d/fbdev-blacklist.conf
/etc/modprobe.d/modesetting.conf
/etc/modprobe.d/open-vm-tools-dkms.conf
# modprobe information used for DKMS modules
#
# This is a stub file, should be edited when needed,
# used by default by DKMS.
install pcnet32 /sbin/modprobe -q --ignore-install vmxnet; /sbin/modprobe -q --ignore-install pcnet32 $CMDLINE_OPTS; /bin/true;
ls: impossible d'accéder à /etc/X11/xorg.conf: Aucun fichier ou dossier de ce type
direct rendering: Yes
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: X.Org
[    20.063] (II) LoadModule: "glx"
[    20.463] (II) LoadModule: "ati"
[    20.477] (II) LoadModule: "radeon"
[    20.530] (II) LoadModule: "modesetting"
[    20.550] (II) LoadModule: "fbdev"
[    20.551] (II) LoadModule: "vesa"
[    20.573] (II) LoadModule: "fbdevhw"
[    20.589] (II) LoadModule: "dri2"
[    20.589] (II) LoadModule: "exa"
[    20.663] (II) LoadModule: "fb"
[    20.743] (II) LoadModule: "ramdac"
[    23.211] (II) LoadModule: "evdev"
[    23.396] (II) LoadModule: "synaptics"
```

**Comment by nwin** [comment]
Looks exactly the same here with the latest version of Servo. OSX 10.11 @ Intel HD 4000. 

Beside that the acid page does not seem to load at all, had to use the local version (`tests/html/acid2.html`)

**Comment by woshilapin** [comment]
Interesting, I indeed used `http://www.webstandards.org/files/acid2/test.html#top` which was loading in a few seconds (but with the eye problem).  However, when I used `http://acid2.acidtests.org/#top`, I thought it was not loading at all and I had to kill it from terminal.  I tested another time.  In the end, it loads but it's very very long to load (a few minutes).

**Comment by pcwalton** [comment]
Renamed to be more specific.

**Comment by mrobinson** [comment]
Acid2 is now broken for me in a different, but the eyes are loading. I'm going to close this bug since it's likely that the current issues are unrelated to the original one.
