### ISSUE TITLE
Servo keeps sending requests if Server doesn't respond!

### ISSUE THREAD

**Issue by dhananjay92** [servo/servo#7725]
If the web server doesn't send any response, servo just keeps sending requests.
Steps to reproduce this scenario:
1. Start this [responseless server](https://gist.github.com/dhananjay92/2be236dfd77536835292)
2. Try to load this in servo (i.e. `servo http://127.0.0.1:8888/`)
3. You will see infinite many `do_GET()...` printed by server.

**Comment by jdm** [comment]
This seems like the connection pooling code is hitting an edge case, @seanmonstar.

**Comment by seanmonstar** [comment]
le sadface

**Comment by nox** [comment]
Pretty sure this was fixed a long time ago.
