### ISSUE TITLE
Add Form getter for all other form elements which we support

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7726]
There are [many elements](https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/semantics/forms/form-control-infrastructure/form.html.ini#L3) with the `form` getter which we support (label, object, textarea)

This needs a simple implementation of `FormControl`, like [so](https://github.com/servo/servo/blob/2623f58a4b2b302c354257632e3ff67d1dfa72d9/components/script/dom/htmlbuttonelement.rs#L194). Then, make changes similar to https://github.com/servo/servo/commit/b677f0f4ae718c9c6953134bbed27656a6aeb48d

**Comment by aopicier** [comment]
I'd like to take a look at this.

**Comment by aopicier** [comment]
I have opened #7760 which deals with fieldset, label, object, output, select and
textarea elements.

keygen elements do not seem to be implemented yet, see https://github.com/servo/servo/issues/2782.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/7760
