### ISSUE TITLE
Implement @import

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#7739]
See the TODO comment in `components/style/stylesheets.rs`.

I don't know what the status of our networking code is right now. @jdm, would it make sense to fix this now, or wait for upcoming networking changes?

**Comment by jdm** [comment]
I don't think there's any need to wait. As long as stylesheet network loads remain synchronous from the point of view of the layout task, this should be relatively straightforward. I suggest we
* add a `StylesheetFetcher` trait to `style_traits` with a method that initiates a request for an imported stylesheet URL
* add an instance of this trait to `ParserContext`
* define an implementation of this trait in the layout script which mimics the existing code in LayoutTask::handle_load_stylesheet, and pass it to any CSS parser calls that end up creating a ParserContext value

**Comment by vramana** [comment]
@jdm Can I work on this??

**Comment by jdm** [comment]
Yes! Ask questions about anything that's unclear!

**Comment by vramana** [comment]
1. Should network request performed using `fetch` ?
2. Should the `StylesheetFetcher` trait live in it's own file or can it live in `style_traits/lib.rs` ??

**Comment by jdm** [comment]
We should use the non-fetch network stack for the time being, and `style_traits/lib.rs` is fine. Now the best code to mimic is probably `handle_stylesheet_url` in `htmllinkelement.rs`.

**Comment by jdm** [comment]
We support import rules now.
