### ISSUE TITLE
Evaluate need for ANGLES dependency

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7740]
Currently we depend on ANGLES for webgl shader validation.

```
            let validator = ShaderValidator::for_webgl(self.gl_type,
                                                       SHADER_OUTPUT_FORMAT,
                                                       &BuiltInResources::default()).unwrap();
            match validator.compile_and_translate(&[source.as_bytes()]) {
                Ok(translated_source) => {
```

I'm not sure if this is necessary -- we might be able to get the same effect by invoking certain OpenGL/GLES apis.

@ecoal95 thoughts?

**Comment by ecoal95** [comment]
I think it's definitely needed, the WebGL spec specifies not only the GLES language to use, but also multiple constraints that can only be verified parsing and analyzing the shader before compiling:
* Reserved identifiers
* Max number of varyings and uniforms used
* Initial value for `gl_Position`
* Disallowing some constructs, like user-defined functions in global variable initializations, but allowing initializations without `const` qualifier, etc...
* Checked array access
* ...

Most of them are specified in [section 4.3 and following](https://www.khronos.org/registry/webgl/specs/latest/1.0/#4.3), the others are mostly in [section 6](https://www.khronos.org/registry/webgl/specs/latest/1.0/#6) of the spec.

I think we cannot avoid depending on Angle (except creating our own compiler of course), doing so could have important security implications.

**Comment by emilio** [comment]
I'm closing this since for now angle is a required part of our WebGL dependencies.
