### ISSUE TITLE
HTMLSelectElement::add comments need to be updated

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7744]
https://github.com/servo/servo/blob/d39c8546b6bf03c69b1cde925c72722dfd61e588/components/script/dom/htmlselectelement.rs#L65

https://github.com/servo/servo/blob/d39c8546b6bf03c69b1cde925c72722dfd61e588/components/script/dom/webidls/HTMLSelectElement.webidl#L22

That test no longer exists. Not sure which test it is now; possibly [this one](https://github.com/servo/servo/blob/09f2977cc945850a35f7a5ef1ed014bc42cb265a/tests/wpt/mozilla/tests/mozilla/union.html)

**Comment by jdm** [comment]
Yes, that's the one.
