### ISSUE TITLE
Only display text caret in text inputs

### ISSUE THREAD

**Issue by jdm** [servo/servo#7756]
`tests/html/test-inputs.html` shows text carets in `<input type="submit">` for example :) We should adjust the code added in [this PR that implemented the caret](https://github.com/servo/servo/pull/7644/files#diff-4d6c0efe7ab0163225d32cf90c47bc81R948) to handle this case, by making `get_insertion_point_for_layout` return an Option value.

Code: components/script/dom/htmlinputelement.rs

**Comment by j3parker** [comment]
I'll grab this

**Comment by Wafflespeanut** [comment]
#7757 closes this.
