### ISSUE TITLE
Display input caret for textarea

### ISSUE THREAD

**Issue by jdm** [servo/servo#7758]
Right now it only shows up for `<input>`, as can be seen in `tests/html/test-inputs.html` vs `tests/html/test_textarea_input.html`. We should improve `ThreadsafeLayoutNode::insertion_point` to handle `<textarea>` too, and duplicate the machinery from htmlinputelement.rs to support it.

Code: components/script/dom/htmlinputelement.rs, components/layout/wrapper.rs

**Comment by fiji-flo** [comment]
I'd like to give this a try.
