### ISSUE TITLE
Unable to download rust snapshot

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#7763]
If you do:
```
./mach bootstrap-rust --force
```
After a long time, it times out and fails. Additionally,
```
wget https://servo-rust.s3.amazonaws.com/f93ab64d4a1a7ee91759a1594ab2a426b6cc657e/rustc-1.5.0-dev-x86_64-apple-darwin.tar.gz
```

Seems to work about half the time.

@metajack @edunham, any ideas? Just random s3 wonkiness? It's been hitting people on #servo, too.

**Comment by ddrmanxbxfr** [comment]
Seems indeed related to some s3 wonkiness.

Not sure if Cross Region Replication is enabled on this s3 bucket. If not it could help for times that routing is wonky for certain regions

**Comment by edunham** [comment]
There have been some intermittent failures reported on large files served from another S3 bucket in Rust's account as well. I'm enabling logging on both affected buckets to give us some better insight into what's happening.

**Comment by jdm** [comment]
Hasn't reoccurred. Not worth leaving this open I think.
