### ISSUE TITLE
Stacking context issue with CSS transforms

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7779]
This code:

```html
<style>
  body {
    margin: 0;
  }

  div {
    position: absolute;
    width: 100px;
    height: 100px;
  }

  #a {
    top: 40px;
    background: red;
    transform: translateX(1px);
  }

  #b {
    top: 50px;
    left: 10px;
    background: blue;
  }
</style>

<body>
  <div id='a'></div>
  <div id='b'></div>
</body>
```

Servo vs. Firefox:

<img width="319" alt="screen shot 2015-09-29 at 09 56 57" src="https://cloud.githubusercontent.com/assets/373579/10158224/d31e439c-6690-11e5-99df-65b5a61a425e.png">

**Comment by paulrouget** [comment]
@mrobinson have you made any progress? If you can point me to the right direction, maybe I could take a look.

**Comment by mrobinson** [comment]
@paulrouget Yes, actually. This issue is the same as https://github.com/servo/servo/issues/7983. I have a patch that fixes it, but the PR is waiting on https://github.com/servo/servo/pull/7950 to land. Hopefully today or tomorrow I'll have the PR ready.

**Comment by metajack** [comment]
#7950 has landed. What's the status of #7983 @mrobinson ?

**Comment by metajack** [comment]
Note: this is now blocking @paulrouget on browser.html work.

**Comment by mrobinson** [comment]
The fix for this one is at https://github.com/servo/servo/pull/8266. I just double-checked that it fixes the issue @paulrouget filed.
