### ISSUE TITLE
inline element with a transform property are not positioned correctly

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7780]
```html
<span>O</span>
<span>X</span>

<style>
span {
  display: inline;
  transform: scale(1);
  font-size: 44px;
}
</style>
```

<img width="368" alt="screen shot 2015-09-29 at 10 07 53" src="https://cloud.githubusercontent.com/assets/373579/10158397/16992424-6692-11e5-9747-cb0628701b3f.png">

**Comment by notriddle** [comment]
This was fixed in d572f1ca05ca4ae96ca0a7955ab6c05521b5d6d5 (yay `git bisect`!)

Should we add this test case to the test suite, or is it already being tested?

**Comment by jdm** [comment]
cc @mrobinson for the previous question.

**Comment by notriddle** [comment]
`tests/wpt/mozilla/tests/css/inline_stacking_context.html` looks pretty much the same as this issue's test case, except it uses images instead of text.

**Comment by mrobinson** [comment]
@notriddle I don't think we test this behavior explicitly, so it may be worth adding it to https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/css/inline_stacking_context.html.

**Comment by notriddle** [comment]
Close this, please.
