### ISSUE TITLE
CSS transitions of transforms are not smooth

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7783]
We are trying to build a sidebar that moves from the right of the window (offscreen) to cover the content, with a CSS transition, but it's very choppy.

Here is a slowed down screencast (had to use my camera, the screencast software doesn't show the progressive painting):

![enormouscircularkillifish](https://cloud.githubusercontent.com/assets/373579/10160797/1cab716a-66a0-11e5-9ebd-8b45d4b9f4d7.gif)

```html
<style>
  div {
    position: absolute;
    top: 0;
    right: 0;
    width: 400px;
    height: 100vh;
    background: rgba(255,0,0,1);
    transform: translateX(500px);
    transition: transform 400ms linear;
  }

  .show div {
    transform: translateX(1px);
  }
</style>

<p>
  Hey, what kinda party is this? There's no booze and only one hooker. This is the worst part. The calm before the battle. What's with you kids? Every other day it's food, food, food. Alright, I'll get you some stupid food. Hey, you add a one and two zeros to that or we walk! We're rescuing ya. And then the battle's not so bad?
</p>

<div>
</div>


<script>
  document.body.addEventListener('keypress', e => {
    if (e.charCode == 97) { // a
      document.body.classList.toggle('show');
    }
  });
</script>
```

**Comment by paulrouget** [comment]
Is this a regression or transition on transforms are not properly optimized yet?

**Comment by pcwalton** [comment]
They should be working. We'll need to dive into what exactly the problem is here.

**Comment by notriddle** [comment]
What's DLBI?

**Comment by metajack** [comment]
[Display List Based Invalidation](https://wiki.mozilla.org/Gecko:DisplayListBasedInvalidation)

**Comment by pcwalton** [comment]
Also WebRender might just fix this issue for good

**Comment by paulrouget** [comment]
Tried with WebRender. Animation is not smoother.

**Comment by glennw** [comment]
We looked into this and (at least for the webrender case) it's just that vsync wasn't enabled and it was tearing. I imagine that would fix the normal renderer case too, since it's such a simple transition it shouldn't take long to paint that.

**Comment by paulrouget** [comment]
@glennw figured it was because vsync was not used on osx. Adding `with_vsync()` to the glutin window improves the performance quiet a lot. PR: https://github.com/servo/servo/pull/7812
