### ISSUE TITLE
Intermittent test-wpt timeout in 2dcontext/drawing-images-to-the-canvas/* and mozilla/canvas/*

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#7787]
Seen in #7778.

**Comment by mbrubeck** [comment]
Two other drawimage tests also timed out in that run.

```

/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_10.html
----------------------------------------------------------------
TIMEOUT [Parent]
/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_11.html
----------------------------------------------------------------
TIMEOUT [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_10.html
-----------------------------------------------------
TIMEOUT [Parent]
```

**Comment by frewsxcv** [comment]
```
Unexpected Results
==================

/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_5.html
---------------------------------------------------------------
TIMEOUT [Parent]
```

**Comment by mbrubeck** [comment]
```
/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_3.html
---------------------------------------------------------------
TIMEOUT [Parent]
```

**Comment by jdm** [comment]
I fear there's a recent regression behind this sudden spurt of new intermittent timeouts, if we haven't modified our build machine environments recently.

**Comment by Manishearth** [comment]
Getting a _lot_ of drawimage failures

**Comment by jdm** [comment]
According to the log in http://build.servo.org/builders/mac-rel-wpt/builds/208/steps/shell_2/logs/stdio, on the first attempt to composite we notify the constellation that we're ready, then we sit waiting on the constellation until the end of time.

**Comment by jdm** [comment]
The most recent log showed that we're calling `composite_if_necessary` early on and setting `composition_request` (presumably to `Headless`, but I forgot to print the value). I looked, and we call `composite_if_necessary` with the `Headless` argument in two locations, despite the code suggesting that there's only one. I suspect we're getting the `LoadComplete` message in the compositor and this is throwing off the timing.

**Comment by jdm** [comment]
According to the log in http://build.servo.org/builders/mac-rel-wpt/builds/281/steps/shell_2/logs/stdio the constellation never processes the query from the compositor. Fascinating.

**Comment by jdm** [comment]
Most intriguingly, `chan.send(ConstellationMsg::IsReadyToSaveImage(pipeline_epochs)).unwrap();` doesn't return an error value, so apparently the constellation gets into a mode where it just stops pumping its event loop.

**Comment by jdm** [comment]
http://build.servo.org/builders/mac-rel-wpt/builds/304/steps/shell_2/logs/stdio shows zero output from constellation even with RUST_LOG=compositing::constellation ostensibly turned on, which is extremely confusing.

**Comment by jdm** [comment]
Running the appropriate tests locally does show the `DEBUG compositing::constellation` output in the full WPT log (which is not present in the full log on the builder), which either suggests that somehow RUST_LOG is present in the execution environment (which doesn't not appear to be the case according to saltfs) or the constellation doesn't even finish starting when these tests time out :<

**Comment by jdm** [comment]
Hasn't been seen in months, not disabled => close.
