### ISSUE TITLE
Intermittent test-css failure in /css21_dev/html4/c62-percent-000.htm

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#7791]
First seen in #7786.

**Comment by jdm** [comment]
From the reftest analyzer:
<img width="680" alt="screen shot 2015-09-30 at 11 46 44 pm" src="https://cloud.githubusercontent.com/assets/27658/10212457/8bcf97fa-67cd-11e5-9653-0cdda06a7988.png">

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/tests/wpt/css-tests/css21_dev/html4/c62-percent-000.htm?force=1

**Comment by mbrubeck** [comment]
Looks like an incremental layout bug: the test file jumps between correct and buggy layouts on mouse move.

**Comment by KiChjang** [comment]
Disabled in #9716

**Comment by nox** [comment]
This one is still quite broken but I can't reproduce what @mbrubeck said, nor I can ever get a successful PASS.
