### ISSUE TITLE
3D transform: using `perspective` makes element  disappear

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7797]
Not sure what's the status of 3D transforms, but using `perspective` makes inner elements disappear.

```html
<style>

  body {
    perspective: 1000px;
  }

  div {
    position: absolute;
    top: 25vh;
    left: 25vw;
    width: 50vw;
    height: 50vh;
    background-color: red;
  }

</style>

<div></div>
```

**Comment by paulrouget** [comment]
@glennw could you take a quick look at this?

**Comment by glennw** [comment]
OK, this seems to be unrelated to transforms - it appears to be a general layout bug.

If I remove the perspective line from your test, and add opacity: 0.5 or mix-blend-mode: difference, those also make the element disappear.

When a new stacking context is created in any of those situations, it gets a height of 0px for the stacking context bounding rectangle, which will be the cause of it not displaying. Looking further into into now...

**Comment by glennw** [comment]
Any ideas @pcwalton  ?

**Comment by pcwalton** [comment]
Not sure off the top of my head. I don't recall explicitly setting zero height for any of those situations in layout.

**Comment by metajack** [comment]
@glennw Could you spare some time to look into this? This is blocking browser.html progress.

**Comment by glennw** [comment]
@metajack Sure, I'll look into this one today.
