### ISSUE TITLE
`data:` URI without mimetype is interpreted as HTML not plaintext

### ISSUE THREAD

**Issue by waddlesplash** [servo/servo#7803]
As seen in #7796. Testcase (extracted from the one there):
```
<body>
  <iframe src='data:,foo'></iframe>
</body>
```

**Comment by jdm** [comment]
Given the code in data_loader that produces `None` when parsing an empty MIME type, we could either interpret that as plaintext in `ParserContext::headers_available` in `servohtmlparser.rs` or explicitly set it to `text/plain` in `data_loader.rs`. I think the latter option is the better one.

**Comment by eefriedman** [comment]
Looks like https://github.com/servo/servo/blob/3e377bb24e53fde8f7a786cb73caf3aefdcd3699/components/net/data_loader.rs#L59 is the issue.  From https://www.ietf.org/rfc/rfc2397.txt:

> If `<mediatype>` is omitted, it defaults to `text/plain;charset=US-ASCII`.  As a shorthand, `text/plain` can be omitted but the charset parameter supplied.

The edge cases are underspecified, and not consistent across browsers.  If an invalid mimetype is supplied (something without a "/"), Firefox sniffs the content (!) to determine the mimetype.  For example `data:a,<b>bold` is HTML, but `data:a,plain` is plaintext.  (Chrome apparently forces `text/plain` instead.) If `text/plain` is specified with a parameter list that doesn't include a known charset, Firefox sniffs the charset; Chrome only sniffs the charset for a valid parameter list with an unknown charset is specified.
