### ISSUE TITLE
stacking issue with float and position absolute

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7828]
```html
<style>
  div {
    width: 100px;
    height: 100px;
  }

  #a {
    position: absolute;
    top: 20px;
    left: 20px;
    background: red;
  }

  #b {
    float: left;
    position: relative;
    background: green;
  }
</style>

<body>
  <div id="a"></div>
  <div id="b"></div>
</body>
```

<img width="580" alt="screen shot 2015-10-02 at 11 47 10" src="https://cloud.githubusercontent.com/assets/373579/10243790/7858094e-68fb-11e5-86c6-13894b0b2fbc.png">

**Comment by mrobinson** [comment]
This could possibly be another issue with content being promoted to stacking contexts in order to get a layer.
