### ISSUE TITLE
Running `./mach test-wpt` doesn't ensure project is built

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7839]
Steps to reproduce:
1. Change a file
2. Run `./mach test-wpt`

`test-wpt` does not attempt to build the project before running tests. This is inconsistent with `test-unit` and `test`

**Comment by jdm** [comment]
To be honest I'm surprised that `./mach test` has this behaviour. I have found it to my advantage not to have the test commands force a rebuild of Servo in the past; `test-unit` has to because it's running Rust tests that rely on existing Rust code.

**Comment by frewsxcv** [comment]
I don't have any strong opinions about what it should do, but at the very least it should be consistent

**Comment by nox** [comment]
Was this ultimately done?

**Comment by jdm** [comment]
`./mach test` with a wpt file and `./mach test-wpt` appear to behave consistently by not rebuilding.
