### ISSUE TITLE
Warning message about OSX notifications is unclear

### ISSUE THREAD

**Issue by TyOverby** [servo/servo#7840]
Which can be installed via `pip install -U pyobjc`

**Comment by frewsxcv** [comment]
What makes you think pyobjc is required to build Servo?

**Comment by frewsxcv** [comment]
Build notifications requires pyobjc, but not Servo itself. Even if we wanted everyone to have notification support, one issue is that pyobjc takes *forever* to build and could deter new users

**Comment by TyOverby** [comment]
Running "mach build --release" failed with the error message "Could not generate notification! Please make sure that the Python pyobjc module is installed!"

**Comment by frewsxcv** [comment]
That's not an error, that's just a warning message. Servo was still successfully built. If you have suggestions for how to improve the user experience with that message, let us know.

**Comment by TyOverby** [comment]
Ahh, wow I didn't catch that.  Maybe something like "Warning: The optional Python pyobjc module is not installed".

**Comment by jdm** [comment]
That's a good idea, except that the message apparently already includes "[Warning]": http://mxr.mozilla.org/servo/source/python/servo/build_commands.py#112

**Comment by TyOverby** [comment]
Now that I know that it's optional, that makes sense, but the wordage "Please make sure" tells me that it's pretty important.

**Comment by jdm** [comment]
Please feel free to submit a pull request with changes that would make the warning more clear!

**Comment by tareqak** [comment]
This issue can be closed once https://github.com/servo/servo/pull/8024 is merged.

**Comment by TyOverby** [comment]
@tareqak: :+1:
