### ISSUE TITLE
Implement form submission for <select>

### ISSUE THREAD

**Issue by jdm** [servo/servo#7849]
According to https://html.spec.whatwg.org/multipage/forms.html#constructing-the-form-data-set we're supposed to include the selected `<option>` values from `<select>` (see step 3.5). We should implemented the `//Unimplemented` piece in `get_form_dataset` related to `HTMLSelectElement`, by adding a method to `HTMLSelectElement` that fetches the required values in a vector of DOMString, and appends a `FormDatum` value for each one according to the specification in 3.5.

code: components/script/dom/htmlselecteelement.rs, components/script/dom/htmlformelement.rs

**Comment by 6112** [comment]
I would like to work on this, along with #7850.

**Comment by jdm** [comment]
Ok!
