### ISSUE TITLE
Document the specification steps in get_form_dataset

### ISSUE THREAD

**Issue by jdm** [servo/servo#7852]
`get_form_dataset` in `HTMLFormElement.rs` is implementing [this algorithm](https://html.spec.whatwg.org/multipage/forms.html#constructing-the-form-data-set) from the HTML specification, but we lack comments labeling each being implemented. We should label this method like we do [other ones](http://mxr.mozilla.org/servo/source/components/script/dom/document.rs#1333) for clarity.

Code: components/script/dom/htmlformelement.rs

**Comment by martiansideofthemoon** [comment]
@jdm Hey jdm, could I work on this bug as a starter?

**Comment by jdm** [comment]
@martiansideofthemoon Absolutely!

**Comment by jdm** [comment]
@martiansideofthemoon Are you still working on this, or did you want to leave it for somebody else to help them get started?

**Comment by martiansideofthemoon** [comment]
Well I'm sorry, I didn't know I'd been assigned. I won't be able to do the bug this week definitely, so in case someone else is interested he can get started with this one :smile: In case not, I'll work on it from Sunday
