### ISSUE TITLE
Implement port blocking for WebSocket connection algorithm

### ISSUE THREAD

**Issue by jdm** [servo/servo#7855]
The [connection algorithm](https://html.spec.whatwg.org/multipage/comms.html#dom-websocket) contains a step 4 that says we should throw an exception if the port is blacklisted. This is currently missing from our implementation, which causes `./mach test-wpt tests/wpt/web-platform-tests/websockets/Create-Secure-blocked-port.htm` to fail (hence `tests/wpt/metadata/websockets/Create-Secure-blocked-port.htm.ini` contains an expected failure). Let's copy Gecko's [list of blacklisted ports](http://mxr.mozilla.org/mozilla-central/source/netwerk/base/nsIOService.cpp#85) and fix the test failure!

Code: components/script/dom/websocket.rs

**Comment by vectorijk** [comment]
I may try it~

**Comment by jdm** [comment]
Ok!
