### ISSUE TITLE
Implement Websocket.bufferedAmount

### ISSUE THREAD

**Issue by jdm** [servo/servo#7856]
There are a bunch of websocket tests that fail due to `bufferedAmount` being missing, and that's making it harder to figure out the incorrect parts of our implementation. `bufferedAmount` has [rather particular](https://html.spec.whatwg.org/multipage/comms.html#dom-websocket-bufferedamount) requirements - basically, we want to increase the counter in `send`, and dispatch a [runnable](http://doc.servo.org/servo/script/script_task/trait.Runnable.html) (see `WebSocketEvent` for an example) to the script event loop that will reset the counter to 0 when it is processed. We should also set a flag that there's a runnable outstanding, so that multiple `send` calls during the same turn of the event loop only enqueue a single runnable.

Code: components/script/dom/websocket.rs

**Comment by jdm** [comment]
Tests include `./mach test-wpt tests/wpt/web-platform-tests/Send-data.htm`, as well as `Send-0byte-data.htm` and `Send-65k-data.htm`.

**Comment by jimberlage** [comment]
I'll give this a shot, if no one has their eye on it.

**Comment by jdm** [comment]
Please do!

**Comment by jimberlage** [comment]
Any thoughts on a sane buffer size?  The [spec](https://html.spec.whatwg.org/multipage/comms.html#websocket) has bufferedAmount being an unsigned long where each digit represents a byte.  If we used the full unsigned long we would wind up with a 4 GB buffer, so I'm guessing we want to go lower than that.

**Comment by jdm** [comment]
I would store a u32, since that's what the `unsigned long` attribute needs to return according to [the chart](http://doc.servo.org/servo/script/dom/bindings/conversions/index.html).

**Comment by jimberlage** [comment]
True, but what about the buffer itself?  I may be overthinking this.

**Comment by jdm** [comment]
I was not suggesting adding an actual buffer, since our implementation hands off each piece of data directly to the websocket sender. We just need our implementation of `bufferedAmount` to conform to the somewhat odd restrictions imposed by the specication.

**Comment by jimberlage** [comment]
Ah, this makes a lot more sense now.
