### ISSUE TITLE
Implement HTMLHyperlinkElementUtils for HTMLAnchorElement

### ISSUE THREAD

**Issue by jdm** [servo/servo#7857]
We need to uncomment the `implements` line in `HTMLAnchorElement.webidl`, and then add the missing methods to the `HTMLAnchorMethods` implementation in `htmlanchorelement.rs`. Use `WorkerLocation` as a model for this; each time a method from `URLUtils` is called (via `UrlHelper`), we should fetch the current value of the `href` attribute, then adjust the relevant property if necessary, then set the `href` attribute to the new value if necessary.

Code: components/script/dom/webidls/HTMLAnchorElement.webidl, components/script/dom/htmlanchorelement.rs
Test: `./mach test-wpt tests/wpt/web-platform-tests/websockets/constructor/006.html`

**Comment by nox** [comment]
Note that the URL spec is currently under heavy change.

**Comment by jdramani** [comment]
I would like to give it a try :)

**Comment by nox** [comment]
Great!

**Comment by nox** [comment]
#8008

**Comment by frewsxcv** [comment]
The spec changed for `URLUtils`: https://github.com/whatwg/html/pull/219

**Comment by jdm** [comment]
Latest attempt was in #9292 which was a work-in-progress. Further efforts should be based on that.

**Comment by schuster** [comment]
I can try to wrap this up if no one else is working on it.

**Comment by frewsxcv** [comment]
Go for it @schuster !

**Comment by schuster** [comment]
I saw in [1] that the URL API might change. Does it make sense to hold off on submitting any changes until that's done, or should I submit something and then it can get updated with everything else later?

[1] https://github.com/servo/rust-url/pull/176

**Comment by SimonSapin** [comment]
If you’re implementing anything from https://url.spec.whatwg.org/#api yes, since servo/rust-url#176 does as well.
