### ISSUE TITLE
websocket.send(null) causes Servo to panic

### ISSUE THREAD

**Issue by jdm** [servo/servo#7858]
We call `unwrap` on the argument passed to `WebSocket::Send` which is an `Option<String>`, but that brings Servo down if the argument is `null` in JavaScript which corresponds to `None` in Rust. We should use `unwrap_or_else` and create an empty string instead.

Code: components/script/dom/websocket.rs

**Comment by jimberlage** [comment]
I'd like to take this on, if that's cool.

**Comment by jdm** [comment]
Please do!

**Comment by nox** [comment]
@jdm Why is null converted to None for an optional argument though? Isn't null not the same thing as a missing argument? Shouldn't thus the null value be converted to an empty string in codegen directly?

**Comment by jdm** [comment]
My reading of the WebIDL spec suggests that for methods with optional arguments with no default value, an `undefined` value is converted to a "missing" value, which I presume is equivalent to `None` for Servo's implementation.

**Comment by jdm** [comment]
@jimberlage Want to test what happens without your change in #7885 when passing either `null` or `undefined` to the `send` method? I suggest modifying an existing test in `tests/wpt/web-platform-tests/websockets/` for quick experimentation, then running with `./mach test-wpt path/to/test.html`.

**Comment by Ms2ger** [comment]
The spec says
```
  void send(USVString data);
  void send(Blob data);
  void send(ArrayBuffer data);
  void send(ArrayBufferView data);
```
so the argument should not be optional or nullable, which means `null` should be mapped to the string `"null"`, and `undefined` to the string `"undefined"`.

Fixing this should make some tests in `html/dom/interfaces.html` and `websockets/interfaces.html`, as well as `websockets/interfaces/WebSocket/send/001.html`, pass.

**Comment by jdm** [comment]
Huh, I feel a bit silly now. Want to get rid of the `optional` in WebSocket.webidl, @jimberlage ?

**Comment by jimberlage** [comment]
Sure thing.
