### ISSUE TITLE
Send the reason in the WebSocket close handshake

### ISSUE THREAD

**Issue by jdm** [servo/servo#7862]
Websites are allowed to specify a freeform UTF-8 string as a reason for closing the connection, but we don't send that reason in the message to the server right now [contrary to the specification](https://tools.ietf.org/html/rfc6455#section-7.1.6). We should adjust the code in `WebSocket::Close` (inside `send_close`) to send the string stored in `WebSocket::reason` instead of `None`.

Code: components/script/dom/websocket.rs

**Comment by psdh** [comment]
Will work on this! :)
