### ISSUE TITLE
Consistently use the Error enum instead of its constructors

### ISSUE THREAD

**Issue by nox** [servo/servo#7869]
Instead of:

```rust
use dom::bindings::error::Error::HierarchyRequest;
```

We want:

```rust
use dom::bindings::error::Error;
```

The places where the constructors are used unqualified obviously need to be fixed.

**Comment by anthgur** [comment]
I'll do this! Just so I understand, the goal is to change all of the unqualified names of the `Error` enum like `HierarchyRequest` to `Error::HierarchyRequest`?

**Comment by jdm** [comment]
Yep!
