### ISSUE TITLE
SERVO_HEADLESS=1 doesn't build on non-linux

### ISSUE THREAD

**Issue by jdm** [servo/servo#7905]
Granted, since trying this I've realized that it's not needed. However, it's super confusing to run into a build error in the implementation of `WindowMethods` in `glutin/window.rs`, since the `native_display` function is linux-only in the implementation but not in the trait declaration.

I propose adding the appropriate `#[cfg(..)]` stuff in `components/compositing/windowing.rs`.

**Comment by simartin** [comment]
I'll give this one a try.
