### ISSUE TITLE
Use the `cloned` method instead of manually cloning each iterator value

### ISSUE THREAD

**Issue by jdm** [servo/servo#7906]
In `reftest.rs`, there's a `servo_args.iter().map(|x| x.clone()).collect()` which could be written as `servo_args.iter().cloned().collect()` instead.

**Comment by frewsxcv** [comment]
Ideally, this is something clippy would catch ([opened an issue upstream](https://github.com/Manishearth/rust-clippy/issues/367))

**Comment by Ms2ger** [comment]
`servo_args.to_owned()` might work too.

**Comment by craftytrickster** [comment]
I am interested in learning Rust and would like to start contributing to servo in the near future. You already wrote out the required solution here, so I really wouldn't be doing anything, but it in case it helps, I can open up a pull request for the change.

**Comment by frewsxcv** [comment]
Go for it @craftytrickster! Let us know if you need any help :information_desk_person:

**Comment by pierrechevalier83** [comment]
Oops! I got this one wrong... 
https://github.com/servo/servo/pull/7946
I saw the other ticket (367 from rust-clippy) that was tagged E-medium and thought it was about replacing the instances of this pattern...
Turns out I fixed this one instead by mistake...
Sorry guys (especially craftytrickster). I promise I'll move away from the E-easy ones now.

**Comment by pierrechevalier83** [comment]
feel free to reject my PR (if it's possible at this point) so that craftytrickster can give it a go

**Comment by pierrechevalier83** [comment]
Small recap of the situation: jdm rejected my PR and I deleted the branch... Go for it craftytrickster! This issue is yours :)

**Comment by craftytrickster** [comment]
I had heard that the Rust community was very nice, looks like the rumors were true. 

Ultimately, my pull request was just the same as pierre's, thanks for giving me the chance to do it. I thought I found a few more instances, but they were cargo dependencies and not part of the actual project.

**Comment by craftytrickster** [comment]
I've noticed several uses of the method .unwrap() in the code, such as in one of the changed files 
```rs
.cloned()).unwrap();
```
I was under the impression that it was dangerous, since a missing value can crash the program. Is there a reason why it is in use?

**Comment by jdm** [comment]
Sometimes it's used because the author of the code knows that there will always be a value (for example, they checked is_some() earlier). Other times it's incorrect, like you said :)

**Comment by jdm** [comment]
Fixed by #7949.
