### ISSUE TITLE
Fix rendering for documentation that contains unescaped string "<iframe>"

### ISSUE THREAD

**Issue by jdm** [servo/servo#7907]
This is the result of such unescaped HTML: http://doc.servo.org/servo/msg/constellation_msg/enum.MozBrowserEvent.html#variant.OpenWindow
We should modify it to use `<iframe>` in all cases instead.

Code: components/msg/constellation_msg.rs

**Comment by Qeole** [comment]
Hi, I would like to take this one.

**Comment by jdm** [comment]
Please do :)
