### ISSUE TITLE
'script' becomes dirty when alternating between building release and debug

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7908]
```
./mach build -d
(servo builds)
./mach build -r
(servo builds)
./mach build -d
('script' component builds)
./mach build -r
('script' component builds)
./mach build -d
('script' component builds)
./mach build -r
('script' component builds)
...
```

This might be the issue @glennw mentioned a couple weeks ago in the meeting

**Comment by jdm** [comment]
Could you gist the output of `RUST_LOG=cargo::ops::cargo_rustc::fingerprint ./mach build -d --verbose` (or `-r` as appropriate)?

**Comment by frewsxcv** [comment]
Yep, one sec

**Comment by frewsxcv** [comment]
I can't reproduce my original issue anymore :-/   I'll try to capture it with `RUST_LOG` if it happens again
