### ISSUE TITLE
Use typed headers API instead of set_raw

### ISSUE THREAD

**Issue by jdm** [servo/servo#7924]
The HTTP network tests contain a lot of calls to `headers.set_raw` which set HTTP headers. These would be easier to read if they were using the strongly-typed [set](http://doc.servo.org/hyper/header/struct.Headers.html#method.set) API instead, like the code in `components/script/net/http_loader.rs`.

Code: tests/unit/net/http_loader.rs

**Comment by iawaknahc** [comment]
I would like to work on this
