### ISSUE TITLE
Event State flags should live on Element, rather than Node

### ISSUE THREAD

**Issue by bholley** [servo/servo#7934]
We should fix this sooner rather than later, since using them on non-element nodes would be a bug, and storing them there adds unnecessary memory overhead to non-element nodes.

I have patches.

**Comment by bholley** [comment]
CC @pcwalton @jdm

**Comment by Ms2ger** [comment]
The memory overhead is somewhat overstated; we can increase `NodeFlags` to 32 bits without changing the size of `Node`.

**Comment by jdm** [comment]
Ironically this change increases memory usage since all elements now contain an extra field.

**Comment by bholley** [comment]
Making NodeFlags u8 seems to fix this.
