### ISSUE TITLE
Implement HTML5 task sources

### ISSUE THREAD

**Issue by jdm** [servo/servo#7959]
Currently there's a generic script event loop sender for all non-specialized script events (ie. those that do not come from devtools, constellation, etc.) Like #503 we should add additional senders for each task source the spec defines and provide convenient APIs to allow people implementing DOM specs to do the right thing.

Note that this will likely be more complex than the generic select mechanism we currently use in the script event loop, due to ordering concerns about queued events in multiple task sources.

**Comment by jdm** [comment]
https://html.spec.whatwg.org/multipage/webappapis.html#generic-task-sources
Then again, the spec says:
"Select the oldest task on one of the event loop's task queues, if any, ignoring, in the case of a browsing context event loop, tasks whose associated Documents are not fully active. The user agent may pick any task queue."
Which suggests that only ordering inside of any given queue matters.

**Comment by KiChjang** [comment]
Sounds interesting, I'm taking a look into this.

**Comment by jdm** [comment]
This would be super valuable!

**Comment by jdm** [comment]
I recommend we start by defining methods on Window/ScriptTask/GlobalRef for specific task sources (DOM, network, user input, etc.) and making them return the existing script channel, then finding callers of `script_chan()` that should be using those specific task sources and having them call the methods to get their channel.

**Comment by KiChjang** [comment]
Yes, that sounds like a good first PR with a lot of elbow-grease.

After that, I was thinking that we may want to create new message enums (similar to the style for the constellation) for each individual task source. Does that sound good to you?

**Comment by jdm** [comment]
Yep!

**Comment by KiChjang** [comment]
I think this is essentially done except for HistoryTraversalTaskSource (which is still currently a stub using the ScriptChan trait) which is tracked in #10994 and other various small task sources littered around the spec.
