### ISSUE TITLE
Support `javascript:` URLs

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#796]
We have no support for `javascript:` URLs at present. These are tricky.

Brendan says:

"Beware the 'referrer' or 'origin' trust-label constraint for these, somewhat broken in most browsers these days."

"The issue in a nutshell: I type `javascript:` into my URL bar and I'm probably being tricked by a FB fraudster. This led to disabling such a gesture. But from links and `src=` attributes, `javascript:` must work and ideally should inherit the origin of the referring page. "

**Comment by nox** [comment]
We support these now.
