### ISSUE TITLE
Only pass user agent to HTTP loader factory

### ISSUE THREAD

**Issue by jdm** [servo/servo#7968]
The user agent string is only useful for HTTP requests, but we're passing it to every resource loader factory. We can treat it like the other HTTP-only data (hsts_list, cookie_storage, etc.) in `ResourceManager::load` and clean up the other resources loaders that don't use it (see the `_user_agent` argument in the `from_factory` function.

Code: components/net/resource_task.rs

**Comment by craftytrickster** [comment]
I think I may have an idea on how to do this, I can give it a try.
