### ISSUE TITLE
unicode-table.com loads very very slowly

### ISSUE THREAD

**Issue by mdinger** [servo/servo#7975]
http://unicode-table.com/ takes a really long time to load; about 130 seconds. Scrolling to the bottom also doesn't continue loading more icons.

**Comment by mdinger** [comment]
The slow load time isn't reproducible when I save the page locally.

**Comment by froydnj** [comment]
Profiling this with `perf` (admittedly on a dev build, so take this with a grain of salt) says that the major stack is:

```
-   74.23%     0.00%            servo  servo                        [.]
ec::from_elem::from_elem::h13635233637910016915
vec::from_elem::from_elem::h13635233637910016915
platform::linux::_$LT$impl$GT$::new::h4e85e301166b57b9Dyb
platform::linux::recv::hf066c142547080cbdnb
platform::linux::_$LT$impl$GT$::select::h855f3118a832d56eE3a
ipc::_$LT$impl$GT$::select::hc72937f42b7a678eyna
router::_$LT$impl$GT$::run::hb8a6233f599bca21pNb
router::_$LT$impl$GT$::new::_$LT$closure$GT$::closure.17337
boxed::_$LT$impl$GT$::call_once::call_once::h18263532043532240257
std::thread::_$LT$impl$GT$::spawn_inner::_$LT$closure$GT$::_$LT$closure$GT$::closure.17307
__rust_try
std::thread::_$LT$impl$GT$::spawn_inner::_$LT$closure$GT$::closure.17284
sys::thread::_$LT$impl$GT$::new::thread_start::h89508aa1f401717d8Dw
```

Guess we're doing a lot of IPC?

**Comment by jdm** [comment]
IPC serialization is known to perform very poorly in dev builds, so a release build would be more meaningful.

**Comment by froydnj** [comment]
That stack doesn't look like it has anything to do with serialization; that looks like part of the normal send/recv procedure.  Or is that just my servo ignorance shining through?

**Comment by jdm** [comment]
We're using IPC channels in a single process setup, so all messages sent get serialized and deserialized.

**Comment by froydnj** [comment]
Hm, building servo with profiling-appropriate settings in a release build gives stacks that are significantly less helpful.  Profiling without callstacks says that we're spending a lot of time in the kernel; 5 of the top 7 entries (or about 50% of all the samples taken) are in the kernel: `sock_poll`, `unix_dgram_poll`, `_raw_spin_lock_irqsave`, `__fget`, and `_fput`.  The only bit from servo itself (~8%) is from `font_cache_task`.

**Comment by pyfisch** [comment]
The page loads fast now (on release) but new icons are still not loaded.

There is a single error printed: `ERROR:script::dom::bindings::error: Error at https://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dcb9d002b0b7052:2:47554 can't assign to properties of (new String("")): not an object`

Is this issue still relevant?

**Comment by jdm** [comment]
Filing a new issue about the icons not loading would be good. We can close this one.
