### ISSUE TITLE
Dispatch focusin/focusout/blur/focus events as appropriate

### ISSUE THREAD

**Issue by jdm** [servo/servo#7981]
https://w3c.github.io/uievents/#h-events-focusevent-event-order

https://html.spec.whatwg.org/multipage/interaction.html#focus-update-steps defines when the `blur` and `focus` events should be dispatched. We should at least define functions that encompass the [focusing steps](https://html.spec.whatwg.org/multipage/interaction.html#focusing-steps) and [unfocusing steps](https://html.spec.whatwg.org/multipage/interaction.html#unfocusing-steps), as well as the [focus update steps](https://html.spec.whatwg.org/multipage/interaction.html#focus-update-steps) and [fire a focus event](https://html.spec.whatwg.org/multipage/interaction.html#fire-a-focus-event) concepts. These don't need to be complete, but they'll allow us to verify our implementation against the spec text more conveniently since this stuff is surprisingly complex.

**Comment by jdm** [comment]
All relevant prior art exists in document.rs in commit_focus_transaction and request_focus.

**Comment by j3parker** [comment]
If it's cool I'm going to look into this so I can unblock the other issue

**Comment by jdm** [comment]
Yes please!

**Comment by frewsxcv** [comment]
A previous attempt at this was done in https://github.com/servo/servo/pull/7985, but it went unfinished

**Comment by paulrouget** [comment]
I'm going to give it a try.

**Comment by KiChjang** [comment]
Much obliged!
