### ISSUE TITLE
Stacking contexts should more often be drawn in tree order

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#7983]
According to [CSS 2.1 Appendix E: Elaborate description of Stacking Contexts](http://www.w3.org/TR/CSS21/zindex.html) E.2.8, stacking contexts with a z-index of 0 or auto and positioned element should be drawn in tree order. Currently these two types of descendents are split into two display list sections `positioned_content` and `children.` In order to preserve tree order, at least some of the stacking contexts will need to be in the same list as the positioned content or carry a tree order number.

My proposal is that `positioned_content` and `children` be replaced with `positioned_content_and_stacking_contexts` that holds an enums carrying either a DisplayItem or a StackingContext. 

cc @pcwalton

**Comment by pcwalton** [comment]
I agree.
