### ISSUE TITLE
Add onstorage handler to WindowEventHandlers

### ISSUE THREAD

**Issue by jdm** [servo/servo#7994]
We dispatch the storage event when localStorage or sessionStorage is modified, but only pages that use `addEventListener` can receive it right now. We should hook up the `window.onstorage` mechanism too: https://html.spec.whatwg.org/multipage/webappapis.html#idl-definitions:handler-window-onstorage . This will probably make some tests in `./mach test-wpt webstorage` pass!

Code: components/script/dom/webidls/EventHandler.webidl, components/script/dom/window.rs

**Comment by martiansideofthemoon** [comment]
Hey @jdm could I work on this one?

**Comment by martiansideofthemoon** [comment]
#7999

**Comment by martiansideofthemoon** [comment]
#7999

**Comment by martiansideofthemoon** [comment]
@jdm The issue can be closed right? Or some work remains?

**Comment by jdm** [comment]
Yep! In future you can add "Resolves #NNNN" to the commit message or PR description and github will automatically close it.
