### ISSUE TITLE
<xmp> and <plaintext> DOM nodes should have type HTMLPreElement

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#7995]
They're missing from the list at https://github.com/servo/servo/blob/b34b82537acfb7cd9bd8bcecd5eb49528020b1ab/components/script/dom/create.rs#L103 .

There are already wpt tests for this; see `tests/wpt/metadata/html/dom/interfaces.html.ini` .

Spec references: https://html.spec.whatwg.org/multipage/obsolete.html#other-elements,-attributes-and-apis:plaintext and https://html.spec.whatwg.org/multipage/obsolete.html#other-elements,-attributes-and-apis:xmp .

**Comment by s142857** [comment]
Can I work on this. (I'm sorry I messed up my last PR.  I was having tests)

**Comment by jdm** [comment]
Sorry, #8017 has already been submitted to solve this.

**Comment by s142857** [comment]
Ok, I'll finish Mr.Robot and then I'll look for an issue later.
cheers @jdm

On Sun, Oct 18, 2015 at 6:58 PM, Josh Matthews <notifications@github.com>
wrote:

> Sorry, #8017 <https://github.com/servo/servo/pull/8017> has already been
> submitted to solve this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servo/servo/issues/7995#issuecomment-149016382>.
>



-- 
Regards,
Sanketh

**Comment by jdm** [comment]
@s142857 You're welcome to work on this!
