### ISSUE TITLE
Add onresize handler to GlobalEventHandlers

### ISSUE THREAD

**Issue by jdm** [servo/servo#7996]
We dispatch the resize event when when the window is resized, but only pages that use `addEventListener` can receive it right now. We should hook up the `document.onresize` mechanism too: https://html.spec.whatwg.org/multipage/webappapis.html#idl-definitions:handler-onresize . This will probably change the output of `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.html` pass!

Code: components/script/dom/webidls/EventHandler.webidl, components/script/dom/document.rs, components/script/dom/window.rs, components/script/dom/htmlelement.rs

**Comment by His-name-is-Joof** [comment]
I'd like this one.

**Comment by jdm** [comment]
@His-name-is-Joof Please do :)

**Comment by Wafflespeanut** [comment]
@His-name-is-Joof any news on progress?

**Comment by His-name-is-Joof** [comment]
it should be done, but awaiting merge. Upstream changes made it unmergable
today.

**Comment by Wafflespeanut** [comment]
@His-name-is-Joof Yeah, sorry, I didn't check your PR at first :)

**Comment by eefriedman** [comment]
(For reference, this is #8006.)

**Comment by Wafflespeanut** [comment]
(unassigned based on inactivity)

**Comment by frewsxcv** [comment]
To the next person who tries their hand at completing this issue, here is a previous attempt: https://github.com/servo/servo/pull/8006

**Comment by g-k** [comment]
dibs?

**Comment by KiChjang** [comment]
Alright!
