### ISSUE TITLE
createDocument method of DOMImplementation should return an XMLDocument

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8000]
Currently, it returns a Document, which isn't precisely correct according to the spec.

DOMImplementation interface: https://dom.spec.whatwg.org/#domimplementation .

XMLDocument interface: https://dom.spec.whatwg.org/#xmldocument plus https://html.spec.whatwg.org/multipage/dom.html#dom-xmldocument-load .

Fixing this should be straightforward, just a bunch of boilerplate.

**Comment by jdm** [comment]
Note, I'm expecting this to be solved as part of [this project](https://github.com/servo/servo/wiki/Integrate-xml5ever) that is being worked on by a group of students at NCSU.

**Comment by nox** [comment]
@jdm For the scope of this ticket though, it's just a matter of creating a dummy XMLDocument interface, students could then fill the holes.

**Comment by jdm** [comment]
That's fair!

**Comment by jdm** [comment]
Claiming this for a potential contributor; please don't work on this unless you talk to me first!

**Comment by KMBrothern** [comment]
I am new to this project and currently working on this item. I have started reading the docs listed above for context and clarification.

**Comment by jdm** [comment]
The relevant places for modification would be `components/script/dom/webidls/DOMImplementation.webidl`, `components/script/dom/webidls/XMLDocument.webidl`, `components/script/dom/domimplementation.rs`, and `components/script/dom/xmldocument.rs` (as well as `components/script/dom/mod.rs` to add the new `xmldocument` module).

The results of tests like `./mach test-wpt tests/wpt/web-platform-tests/dom/interfaces.html` and `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.html` should change after making these changes.

**Comment by jdm** [comment]
@KMBrothern let me know privately that they're no longer working on this.

**Comment by GuillaumeGomez** [comment]
If there is no one on this issue anymore, I'd like to give it a try.
