### ISSUE TITLE
Computed style for "float" doesn't respect position or display

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8002]
Testcase:

```html
<!DOCTYPE html>
<html>
<body>
<div style="position: fixed; float: left">fop</div>
<script>
document.body.innerHTML = getComputedStyle(document.querySelector("div"))["float"];
</script>
</body>
</html>
```

Should show "none", currently shows "left".

Specification text: https://drafts.csswg.org/css2/visuren.html#dis-pos-flo .

Tips for fixing: the relevant code is in `components/style/properties.mako.rs`; the `single_keyword_computed` template will probably be useful.

**Comment by gilles-leblanc** [comment]
I'd like to look into this issue if it's available !

I'm thinking of adding a reftest before fixing. 

As I understand the reason this should be displaying ```none``` is because of:

```
Otherwise, if 'position' has the value 'absolute' or 'fixed', the box is absolutely positioned, the computed value of 'float' is 'none', and display is set according to the table below.
```

**Comment by eefriedman** [comment]
I don't think anyone else is working on this.

Yes, you're understanding the testcase correctly.

**Comment by gilles-leblanc** [comment]
It took me a while to figure out what to do (which wasn't much once I understood how properties.mako.rs works). 

Now I have to run all the test suite and make sure I haven't broken anything or need to change any tests. 

Running the full test suite is taking a long time. I will try running it again tomorrow when I have more time.
