### ISSUE TITLE
Servo WPT readme should mention building with release mode

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8007]
Running all the WPT tests with debug mode results in a ton of timeouts. We should at least mention somewhere that if one wants to run all the tests, build with `mach build -r` and test with `mach test-wpt --release`

File: https://github.com/servo/servo/blob/master/tests/wpt/README.md

**Comment by creativcoder** [comment]
This is merged already e0d82556f7e27b5d13513cd08fbfce56bcc63b2d  so its ok to close it.
