### ISSUE TITLE
Move the `app_units` crate into a repository of its own

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8012]
The files in there should live directly in `components/app_units/`.

**Comment by jdm** [comment]
This doesn't seem like the right solution to me, since it makes it impossible to publish changes to cargo.

**Comment by Manishearth** [comment]
@jdm You can set a path in the Cargo.toml, Cargo packages don't need to have a src dir

**Comment by Ms2ger** [comment]
You're right, this isn't the correct solution. This crate should get its own repo, so that it gets tested and published in isolation.

**Comment by frewsxcv** [comment]
Opened a PR https://github.com/servo/app_units/pull/1 . I have no preferences whatsover for the repository name. I just chose 'app_units' because that's what the Cargo.toml already has specified.

**Comment by frewsxcv** [comment]
Also opened a PR to remove it from the tree https://github.com/servo/servo/issues/8025

**Comment by frewsxcv** [comment]
Update: https://github.com/servo/app_units/pull/1 has merged. Just waiting on #8025 to get reviewed before this issue can be closed.

**Comment by frewsxcv** [comment]
https://github.com/servo/app_units/pull/1 and https://github.com/servo/servo/pull/8025 have merged. This is finished.
