### ISSUE TITLE
Allow requesting data URLs from XMLHttpRequest

### ISSUE THREAD

**Issue by jdm** [servo/servo#8015]
Step 5 of https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send explicitly sets the `same-origin data-URL flag` to true. We have a TODO about this in `CORSRequest::maybe_new`; I propose creating a new enum representing this flag, and passing it as an argument to `CORSRequest::maybe_new`. This should cause the output of `./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest/data-uri.htm` to improve.

Note: this is reserved for a potential Outreachy contributor who I am in contact with.

Code: `components/script/cors.rs`, `components/script/dom/xmlhttprequest.rs`

**Comment by Mylainos** [comment]
`same-origin data-URL flag` isn't here https://mxr.mozilla.org/servo/source/components/net/fetch/request.rs#52 ?

**Comment by jdm** [comment]
No. The spec concept linked to by the comment above it is different.

**Comment by askalski** [comment]
I am wondering if the ticket is still reserved.

**Comment by eefriedman** [comment]
This is in progress; see #8807.

**Comment by jdm** [comment]
#8807 stalled for reasons unrelated to the actual change. Any further attempt to solve this should build on the changes in that PR and address the most recent comments there.

**Comment by dagnir** [comment]
I'd like to work on this if that's okay.

**Comment by KiChjang** [comment]
Definitely!
