### ISSUE TITLE
Add comments with spec links for JS conversion code

### ISSUE THREAD

**Issue by jdm** [servo/servo#8019]
There's a lot of code for converting JS values to Rust values that are implementing steps from http://heycam.github.io/webidl/ but they're not linked. For example, the FromJSValConvertible impl for ByteString would be http://heycam.github.io/webidl/#es-ByteString . We should add these references to allow for easier verification in the future.

Code: components/script/dom/bindings/conversions.rs

**Comment by creativcoder** [comment]
Ill do that.
Does ToJSValConvertible needs to be commented as well with the same spec link ?

**Comment by jdm** [comment]
Yes; that corresponds to the text like "The result of converting an IDL ByteString value to an ECMAScript value".

**Comment by creativcoder** [comment]
https://github.com/creativcoder/servo/commit/1141f00212533b3bb5d97945aa7ca8d30f0484b3

**Comment by jdm** [comment]
Addressed by #8031.
