### ISSUE TITLE
SIGILL in libcrypto.so.1.0.0 on ARM

### ISSUE THREAD

**Issue by connorimes** [servo/servo#8033]
Prior patches have allowed me to compile Servo on some ARM systems.  On an ODROID-XU3, when I run and try to load a test html file, I get an `Illegal instruction` in `libcrypto.so.1.0.0`.  I ran into this while trying to debug another problem (#8034). When executing normally outside of gdb, I don't see this - it either doesn't happen or fails silently.

<pre>
Starting program: /local/git-ckimes/servo/target/debug/servo tests/html/perf-rainbow.html
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/arm-linux-gnueabihf/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Cannot access memory at address 0x0

Program received signal SIGILL, Illegal instruction.
0xb6db7208 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
#0  0xb6db7208 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
#1  0xb6db4eb0 in OPENSSL_cpuid_setup ()
   from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
#2  0xb6fea20e in call_init (l=<optimized out>, argc=2, argv=0xbefff0f4, 
    env=0xbefff100) at dl-init.c:78
#3  0xb6fea2a0 in _dl_init (main_map=0xb6fff958, argc=2, argv=0xbefff0f4, 
    env=0xbefff100) at dl-init.c:126
#4  0xb6fdfbf2 in _dl_start_user () from /lib/ld-linux-armhf.so.3
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
</pre>

**Comment by connorimes** [comment]
Further investigation hints that this is normal behavior for openssl.  Apparently, it expects to be able to trap SIGILL while determining CPU capabilities.  This is why we only see the error when running in gdb, and not in normal runtime.

**Comment by AlekseyShi** [comment]
Program received signal SIGILL /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
You can tell gdb to not stop on signals.
(gdb) handle SIGILL nostop noprint
will allow your program to continue, gdb will just tell you that the signal was received.

**Comment by rzr** [comment]
https://www.openssl.org/docs/faq.html#PROG17
