### ISSUE TITLE
position:fixed element should fixed on CSS viewport when magnify zooming?

### ISSUE THREAD

**Issue by tetsuharuohzeki** [servo/servo#8058]
if we try magnify zooming, position:fixed element is fixed on CSS viewport. But some browsers don't fixed it on an actual window viewport if they do magnify zooming. Should we do it?
## other implementations

Gecko:  https://bugzilla.mozilla.org/show_bug.cgi?id=656036 (looks not any progress)
Blink's design doc: https://docs.google.com/document/d/1WZBy5JnwgHNQKbqsGMpgCEsiS2t5VaHFZ47xfX8VYiU/edit
- https://developers.google.com/web/updates/2015/01/virtual-viewport
- https://groups.google.com/a/chromium.org/d/topic/blink-dev/mt1uciFuvWQ/discussion
## spec

CSSOM View spec [says](https://drafts.csswg.org/cssom-view/#zooming) this behavior is defined in device adaptation specs, but [CSS Device Adaptation Module Level 1 (Editor’s Draft, 29 May 2015)](https://drafts.csswg.org/css-device-adapt/) don't define anythings about magnify zooming...

**Comment by saneyuki** [comment]
cc?: @SimonSapin @mbrubeck

**Comment by mbrubeck** [comment]
Yes, fixed-position elements should be fixed to the CSS (layout) viewport during pinch zoom.  Blink, WebKit, and Edge all agree on this behavior now, and I still hope that Gecko will match them someday.
