### ISSUE TITLE
<button> should be `display: inline-block`

### ISSUE THREAD

**Issue by jdm** [servo/servo#8064]
https://html.spec.whatwg.org/multipage/rendering.html#the-button-element-2

**Comment by jdm** [comment]
This change should probably be applied in one of our stylesheets in `resources/`.

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/resources/servo.css#1

**Comment by Manishearth** [comment]
In addition to tweaking the linked line above, we should probably move it to `user-agent.css`

**Comment by Manishearth** [comment]
cc @badboy

**Comment by badboy** [comment]
On it!
