### ISSUE TITLE
Implement Element.getAttributeNode() and friends

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#8066]
https://dom.spec.whatwg.org/#dom-element-getattributenode (both `getAttributeNode` and `getAttributeNodeNS`)

The implementation would be similar to [`getAttribute()`](https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L1152) and `getAttributeNS()`. You probably can make `getAttribute()` just call `getAttributeNode()` (same for NS) as code reuse.

If you want, implement the other three `*AttributeNode()` methods. Note that `setAttributeNode()` is not the same as `setAttribute()`, it can emit different errors and follows different steps.

Code: https://github.com/servo/servo/blob/master/components/script/dom/element.rs

**Comment by nox** [comment]
We have to be careful about resetting the attribute value according to the new owner's parse_plain_attribute function.

**Comment by martiansideofthemoon** [comment]
Hey @Manishearth could I try my hand at this bug?

**Comment by Manishearth** [comment]
Sure
