### ISSUE TITLE
Remove explicit lifetimes which can be elided

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8069]
Along the lines of `fn<'a>(&'a self) {}` into `fn (&self) {}`.  Some places where this can be done:

- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/devtools/protocol.rs#L17
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/devtools/protocol.rs#L22
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/devtools/protocol.rs#L28
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/gfx/font.rs#L161
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/gfx/font_cache_task.rs#L39
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/gfx/font_cache_task.rs#L212
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/gfx/font_cache_task.rs#L240
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/layout/flow.rs#L392
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/layout/flow.rs#L406
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/layout/flow_list.rs#L27
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/layout/flow_list.rs#L34
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/layout/flow_list.rs#L40
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/layout/flow_list.rs#L47
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/layout/fragment.rs#L2385
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/script/dom/document.rs#L265
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/script/dom/document.rs#L270
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/script/dom/htmlcollection.rs#L20
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/style/viewport.rs#L41
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/style/viewport.rs#L66
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/style/viewport.rs#L279
- https://github.com/servo/servo/blob/b847e4dd778e49ba60c786da4aa77813dee8b553/components/util/str.rs#L44

I think rust-clippy is supposed to have a lint which catches this; not sure how good it is.

**Comment by Darktori** [comment]
I would like to take this.

**Comment by jdm** [comment]
Please do!

**Comment by Darktori** [comment]
I have removed all instances of "needless_lifetimes" show by clippy except for these 3:

servo/components/layout/flow.rs:392
servo/components/layout/flow.rs:406
servo/components/layout/flow_ref.rs:23

I believe those are connected, but I don't have enough knowledge how to fix those (or if it's even possible). I could submit what I have done so far though.

**Comment by eefriedman** [comment]
Pretty sure those are impossible to fix; see also https://github.com/rust-lang/rfcs/issues/1302 .
