### ISSUE TITLE
Weird list bullet positioning with "position: absolute; overflow: hidden"

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8074]
``` html
<!DOCTYPE html>
<html>
<body>
<ul>
<li style="position: absolute; overflow: hidden">x
</ul>
</body>
</html>
```

The list bullet somehow ends up on top of the x.  It should be hidden.

**Comment by jdm** [comment]
The only code I see that deals with clipping for overflow is in http://mxr.mozilla.org/servo/source/components/layout/display_list_builder.rs#1365 (clipping_region_for_children).

**Comment by eefriedman** [comment]
There are some other places affected by `overflow: hidden` which don't explicitly check for it; http://mxr.mozilla.org/servo/source/components/layout/fragment.rs#2144, http://mxr.mozilla.org/servo/source/components/layout/block.rs#1499 .

**Comment by eefriedman** [comment]
Another related testcase:

```html
<!DOCTYPE html>
<html>
<body>
<ul>
<li style="opacity: 0.99">x
</ul>
</body>
</html>
```

Same issue: the bullet ends up on top of the x.
