### ISSUE TITLE
Implement Highlight Pseudo-elements (::selection)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8077]
I'm not sure we can select text yet in a regular element, but it's possible in an `<input>` tag.The selection is not highlighted though.

See: https://drafts.csswg.org/css-pseudo-4/#selectordef-selection

**Comment by nox** [comment]
This will require changes in rust-selectors.

**Comment by paulrouget** [comment]
Bumping to bhtml P2. Now we have an awesomebar, we need to be able to highlight the selected text in an `<input>`.

**Comment by mbrubeck** [comment]
See also #4410 and #4409.

**Comment by paulrouget** [comment]
@SimonSapin - can you confirm you're working on this issue?

**Comment by SimonSapin** [comment]
@paulrouget As we’ve discussed in person I think #9993 can be separated from styling support. I haven’t started on this yet as I’d like to wrap up https://github.com/servo/rust-url/pull/176 and its fallout first.

With a recent change to rust-selectors, parsing a new pseudo-element can be done in `components/style/selector_impl.rs` without changing rust-selectors.

**Comment by mbrubeck** [comment]
Fixed by #10252.
