### ISSUE TITLE
`query_selector_iter` no longer needs to be unsafe

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8078]
At least, I don't think so. CCing @Manishearth to confirm.

**Comment by Manishearth** [comment]
This is correct.

**Comment by TileHalo** [comment]
I'd like to fix this if its ok.

**Comment by Manishearth** [comment]
Sure!

**Comment by TileHalo** [comment]
Should I also delete comments that tells block using 'query_selector_iter' is safe?

**Comment by Manishearth** [comment]
Yep!

**Comment by nox** [comment]
#8095
