### ISSUE TITLE
iframe hit test is wrong

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8080]
In the following example, the content of the iframe turns blue on `:hover`. But moving the mouse at the top or the bottom of the iframe, the content of the iframe is considered not `:hover` (so staying red). I guess it's a hit test issue. This makes clicking on links impossible in a more complex layout.

a.html:

```html
<style>
  body {
    margin: 0;
  }

  div {
    width: 10px;
    height: 160px;
    background: green;
  }

  iframe {
    display: block;
    width: 200px;
    height: 200px;
    border: 0;
  }

</style>

<div></div>

<iframe src="b.html" mozbrowser="true"></iframe>
```

b.html:
```html
<style>
  html { background: red }
  html:hover { background: blue }
</style>
```

**Comment by jdm** [comment]
I didn't expect b.html to work outside of an iframe, but it did. Interesting.
