### ISSUE TITLE
iframe not painted anymore after navigation (regression c72d0c2)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8081]
Since commit c72d0c2ed04f6c5f9fa22a3f576e1df5878f941d, clicking a link in a iframe turns the iframe white.

I believe the iframe is loaded but not painted (we get load events).

**Comment by glennw** [comment]
I'm almost certain this will be the same as the iframe flickering.

**Comment by paulrouget** [comment]
> I'm almost certain this will be the same as the iframe flickering.

Apparently not.

**Comment by glennw** [comment]
:( OK, I'll take a look at this tomorrow if @pcwalton doesn't get to it first.

**Comment by glennw** [comment]
I had a brief look at this but didn't really get anywhere - after navigation it seems to get the main pipeline listed twice in the layer tree, and the iframe layers are not present. @pcwalton are you able to take a look at this one? It seems to have started happening after https://github.com/servo/servo/commit/c72d0c2ed04f6c5f9fa22a3f576e1df5878f941d.

**Comment by metajack** [comment]
@pcwalton @glennw It's a month later now. Can you both discuss and figure out who can tackle this?

**Comment by glennw** [comment]
@pcwalton said he'll look into it this week :)
