### ISSUE TITLE
Implement <table> 'rows' attribute

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8084]
https://html.spec.whatwg.org/multipage/tables.html#dom-table-rows

This requires `HTMLCollection` to be updated to support more flexible custom iterators than just a simple filter

I started refactoring `HTMLCollection` and implementing `<table>` `rows` in [this branch](https://github.com/servo/servo/compare/master...frewsxcv:traversal-htmlcollection?expand=1), but I'm going to hold off on contributing more to it for the time being incase anyone thinks of a better system. If anyone wants to give this a shot, feel free to steal my existing work

**Comment by KiChjang** [comment]
Blocks #9270.

**Comment by MonsieurLanza** [comment]
I'd like to take this. 
But it may take some time, as I can only spend about 1-2h/day on servo, atm.

**Comment by nox** [comment]
@MonsieurLanza Go for it!

**Comment by KiChjang** [comment]
@MonsieurLanza Are you still working on this?

**Comment by MonsieurLanza** [comment]
Yes, but i won't have time to get back on it until monday. 
--
Damien BRUN

**Comment by KiChjang** [comment]
@MonsieurLanza Still working?

**Comment by MonsieurLanza** [comment]
I m'm sorry I cannot free enough time to work efficiently on servo ATM (about 1h/week). So geek free to re-assign this, if you cannot wait. 

--
Damien BRUN

**Comment by KiChjang** [comment]
No worries! If you have time to work on Servo again, ferl free to drop me a message and I'll look for an easy issue for you :)
