### ISSUE TITLE
Implement PartialEq for MutHeap<JS<T>> and friends

### ISSUE THREAD

**Issue by nox** [servo/servo#8090]
The types `MutHeap` and `MutNullableHeap` should implement the `PartialEq` trait for `JS<T>`, in the file `components/script/dom/bindings/js.rs`. Our code base should then use this implementation to avoid unnecessary rooting.

**Comment by wenderen** [comment]
Can I take this up?

**Comment by jdm** [comment]
Yep!

**Comment by nox** [comment]
That was done in #8097.
