### ISSUE TITLE
Can't submit Github 2FA verification

### ISSUE THREAD

**Issue by jdm** [servo/servo#8101]
STR:
Visit https://github.com and click "sign in". Enter username and password for 2FA-enabled account. See verification page for authentication code. Click "Verify".

Actual:
Nothing happens.

Expected:
Logged in.

**Comment by jdm** [comment]
It's a `<button class="btn" type="submit">`.

**Comment by jdm** [comment]
Sounds like #4837.

**Comment by frewsxcv** [comment]
FWIW, this how far I get when I attempt (ignore the slow loading, my internet is slow at the moment)

![](https://cloud.githubusercontent.com/assets/416575/10625443/489a0994-7771-11e5-8c45-87b6416712d2.gif)

**Comment by jdm** [comment]
That's #8100.
