### ISSUE TITLE
Form submission to file:// and about: URLs silently fails

### ISSUE THREAD

**Issue by jdm** [servo/servo#8113]
```html
<form action="other.html">
<input type="submit" value="submit">
</form>
```
This form navigates correctly to other.html if it's run under an HTTP server (such as `python -m SimpleHTTPServer`), but does nothing if it's run from the local filesystem. We should correct this by fixing the "Step 18" implementation in `HTMLFormElement::submit` by adding a handler for the "file" scheme along with "ftp", etc.

Unfortunately it's not clear to me that it's possible to write an automated test for this, since our tests run under an HTTP webserver.

Interesting background reading: https://html.spec.whatwg.org/multipage/forms.html#form-submission-algorithm and step 18 in particular, which says "If scheme is not one of those listed in this table, then the behaviour is not defined by this specification. User agents should, in the absence of another specification defining this, act in a manner analogous to that defined in this specification for similar schemes."

Code: components/script/dom/htmlformelement.rs

**Comment by jdm** [comment]
This should also add a similar handler for `about:` URLs.

**Comment by eefriedman** [comment]
It should be possible to write an automated test using a iframe which checks the behavior of form submission to `about:blank`, I think.  (Like you said, it's probably not possible to write tests for `file://` URLs using the wpt test framework.)

**Comment by simartin** [comment]
I'll give this one a try.

**Comment by jdm** [comment]
@simartin That would be great!

**Comment by simartin** [comment]
Patch is ready; now working on an automated test using the suggestion eefriedman did.

**Comment by simartin** [comment]
I finally came up with a way of testing the fix with about:blank; I have to go for the "test != ref" scheme because otherwise, since both are blank, the test would have to be marked as flaky (and therefore not test anything really...). I hope it makes sense.
