### ISSUE TITLE
Text disappears with certain rotateY settings

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8116]
The following shows nothing:

``` html
<!DOCTYPE html>
<html>
<body>
<div style="transform: rotateY(-41deg);">xxxxxxxxxx</div>
</body>
</html>
```

The following shows text:

``` html
<!DOCTYPE html>
<html>
<body>
<div style="transform: rotateY(-40deg);">xxxxxxxxxx</div>
</body>
</html>
```

This is on Ubuntu 14.04 in a virtual machine, if that makes a difference.

**Comment by craftytrickster** [comment]
I'm using 14.04 as well (as my desktop), except that I do not see anything even with -40. I only start to see something with -38.

**Comment by nox** [comment]
Both show text now.
