### ISSUE TITLE
Remove unnecessary rooting from `CSSStyleDeclaration`

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8126]
Most methods on `CSSStyleDeclaration` start with

```rust
        let owner = self.owner.root();
```

This is no longer necessary; the code below can use `self.owner` directly.

Code: `components/script/dom/cssstyledeclaration.rs`

**Comment by romankl** [comment]
Could I take a look at this one?

**Comment by frewsxcv** [comment]
Go for it!

**Comment by romankl** [comment]
PR #8137 landed and fixed this issue
