### ISSUE TITLE
Intermittent failure of /_mozilla/css/jumpiness_a.html

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8127]
The failure shows that it lacks the underline.

**Comment by jdm** [comment]
<img width="822" alt="screen shot 2016-01-02 at 11 08 40 am" src="https://cloud.githubusercontent.com/assets/27658/12075060/34923bce-b141-11e5-8a84-36262d07a885.png">

**Comment by KiChjang** [comment]
Disabled in #9716

**Comment by nox** [comment]
Is there any patch that landed since then that could have fixed that?

**Comment by mrobinson** [comment]
This is no longer disabled in layout 2020, so I'm going to close this one.
