### ISSUE TITLE
Define allow_wrap, preserve_newlines, preserve_spaces methods on style::computed_values::white_space::T

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8128]
Currently, we have `white_space_allow_wrap`, `white_space_preserve_newlines`, and `white_space_preserve_spaces` methods on `Fragment` (`components/layout/fragment.rs`). It would be nicer to have those methods on `white_space::T` instead, replacing the existing calls with `white_space().allow_wrap()`, etc, and using the method in `components/layout/wrapper.rs` as well.

Calling @SimonSapin since I don't know in what file these implementations should live.

**Comment by SimonSapin** [comment]
This sounds like layout behavior on a type that’s defined on the style crate. If you really want a method on that type, it’d have to be in an extension trait. Whitespace is text and text is inline, so `inline.rs` sounds relevant.

**Comment by KiChjang** [comment]
If I read this correctly, this means that the new functions should be located in a new file `components/script_trait/inline.rs`?
