### ISSUE TITLE
Reorganise some DOM modules

### ISSUE THREAD

**Issue by nox** [servo/servo#8130]
We could improve our DOM code base by moving things around. For example, the `Castable` trait could be moved from `dom::bindings::conversions` to a new module `dom::bindings::inheritance`, and the various functions related to XML names in `dom::bindings::utils` could be moved to a separate module too. In general, we should try to remove the need for "utils" or "misc" modules and find a proper place for their contents.

**Comment by Ms2ger** [comment]
Ref #433

**Comment by nox** [comment]
The module `dom::bindings::inheritance` could also re-export the `TypeId` enums found in `dom::bindings::codegen::InheritTypes`.

**Comment by nox** [comment]
A new module `dom::bindings::reflector` could hold onto `Reflector`, `reflect_dom_object`, etc.

**Comment by wenderen** [comment]
I can work on this.

**Comment by wenderen** [comment]
I have patches for everything except the `TypeId` enums bit. Can you clarify what needs to be done there? Do we need all instances of `use script::dom::bindings::codegen::InheritTypes::[...]` to be replaced by `use script::dom::bindings::codegen::inheritance::[...]`?

**Comment by nox** [comment]
By `use script::dom::bindings::inheritance::…;` yes.

**Comment by wenderen** [comment]
Sorry, typo. Thanks.

**Comment by nox** [comment]
That was done in #8221.
