### ISSUE TITLE
Add notification when EC2 is not spinning up

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#8131]
According to:
http://docs.buildbot.net/latest/manual/cfg-buildslaves-ec2.html#configure-the-master-with-an-ec2latentbuildslave

We should be able to add some notification stuffs to:
https://github.com/servo/saltfs/blob/master/buildbot/master/master.cfg#L57

An e-mail address seems... awkward, though. Any ideas on how to maybe have it ping `#servo` instead?

cc @metajack @edunham

**Comment by jdm** [comment]
`fennectbot` could log into a mail account every N minutes and report new failures!

**Comment by edunham** [comment]
It's pretty easy to make a Buildbot notify a given IRC channel on preset status events: 

https://github.com/rust-lang/rust-buildbot/blob/master/master/master.cfg#L1791

However, the notifications can get kind of spammy. Do you think the benefits of keeping `#servo` a mostly-humans environment would outweigh the inconvenience of having everyone who cares join a `#servo-bots` channel?
