### ISSUE TITLE
Add `./mach clippy`

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#8134]
Currently, to run clippy you have to run `./mach cargo build --features="script/plugins/clippy"`.

We should add a `./mach clippy` which calls `cargo build --features="script/plugins/clippy` under the hood.

Code: https://github.com/servo/servo/blob/master/python/servo/devenv_commands.py

See https://github.com/servo/servo/blob/master/python/servo/devenv_commands.py for reference, though this doesn't need any arguments aside from perhaps the "params" one

**Comment by nerith** [comment]
I'm working on this.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/issues/8144
