### ISSUE TITLE
Accept Brotli-compressed HTTP responses

### ISSUE THREAD

**Issue by jdm** [servo/servo#8156]
There's a new [library](https://github.com/ende76/compression) to decompress Brotli data which we can use. This requires adding a new value to the Accept-Encoding header that we send (`set_default_accept_encoding`) and setting up the appropriate decoder when we encounter the `Content-Encoding` header in `StreamedResponse::from_http_response`. We'll also need to update Cargo.toml with the new dependency.

Code: components/net/http_loader.rs

**Comment by LifeIsStrange** [comment]
Hi ! In the issue that I have referenced, https://github.com/eustas say that Firefox 44 already support brotli but why Firefox not use this rust library https://github.com/ende76/compression as a common library shared with servo instead of duplicate the work ?

**Comment by jdm** [comment]
I assume Firefox is using a battle-tested implementation that's shared with Blink and the work started before Firefox got the ability to integrate Rust code in the build. This library was literally released today :)

**Comment by LifeIsStrange** [comment]
Oh okay ^^ thanks !

**Comment by nxnfufunezn** [comment]
I'll take this on if you want.

**Comment by jdm** [comment]
@nxnfufunezn Please do :)

**Comment by ende76** [comment]
@nxnfufunezn @jdm GitHub should forward automatically, but in case it doesn't:
I have renamed the repo to https://github.com/ende76/brotli-rs and implemented a whole bunch of changes to simplify the code and usage over the last couple of days.
Also, it's now actually feature-complete.
Let me know if it would make your lives easier if I put it on crates.io. I do plan on doing that, but have held off for now to make up my mind about names and such, to avoid too much moving around once it's somehow public.

**Comment by jdm** [comment]
crates.io vs. github makes no difference to us at the moment, since we're not trying to publish servo on crates.io.

**Comment by Ms2ger** [comment]
Is this something that would make sense to implement in hyper?

**Comment by jdm** [comment]
Possibly, but right now all our content decoding work is done in Servo.

**Comment by LifeIsStrange** [comment]
Maybe this demo can be useful for you ? 

http://replete.github.io/brotli-experiments/
