### ISSUE TITLE
Implement document.createEvent("TouchEvent")

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#8160]
This is a follow-up to issue #7204.

In the [Document::CreateEvent](https://github.com/servo/servo/blob/e05999ea9f4883c85939b209f811ae20e9e9e89c/components/script/dom/document.rs#L1325) method, add a case for `"touchevent"` that creates and returns a new TouchEvent.

The TouchEvent constructor takes three TouchList arguments.  You can create an empty TouchList by calling `TouchList::new` with an empty array, then pass this TouchList to the TouchEvent constructor.

After this change, the following tests should pass.  You can `git rm` the metadata files marking them as failing: [Document-createEvent.html.ini](https://github.com/servo/servo/blob/e05999ea9f4883c85939b209f811ae20e9e9e89c/tests/wpt/metadata/dom/nodes/Document-createEvent.html.ini) and [EventTarget-dispatchEvent.html.ini](https://github.com/servo/servo/blob/e05999ea9f4883c85939b209f811ae20e9e9e89c/tests/wpt/metadata/dom/events/EventTarget-dispatchEvent.html.ini).  Then run these commands to verify that both tests pass:
```
./mach test tests/wpt/web-platform-tests/dom/nodes/Document-createEvent.html
./mach test tests/wpt/web-platform-tests/dom/events/EventTarget-dispatchEvent.html
```

**Comment by ax3lst** [comment]
I can do this one

**Comment by Wafflespeanut** [comment]
I guess #8169 closes this?
