### ISSUE TITLE
Subpixel positioning fails since ac5525a

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8166]
When an iframe is present in the document, `top:0.5px` is drawn at `1px`.

It's started with ac5525a.

```html
<style>

  div {
    position: absolute;
    left: 0;
    top: 10.5px;
    width: 200px;
    height: 200px;
    background: red;
  }

  iframe {
    border: none;
  }

  .foo { display: none; }

</style>

<script>
  setInterval(() => {
    document.querySelector('iframe').classList.toggle('foo');
  }, 1000);
</script>

<body>
  <div></div>
  <iframe></iframe>
</body>
```

**Comment by paulrouget** [comment]
Using `to_nearest_pixel` instead of `to_nearest_px` in `components/gfx/paint_task.rs` appears to solve the issue. I'll submit a PR.

**Comment by paulrouget** [comment]
I don't know how to get the pixel density in `build_layer_properties`. Usually, we use `page_rect` and `screen_screen`, but here, I don't know how to get this info.

**Comment by mrobinson** [comment]
I think one issue here is that the layer boundaries are rounded instead of expanded to pixel boundaries. I have a fix for this which depends on https://github.com/servo/app_units/pull/3 (though I don't have a readily accessible hidpi screen to test it on).

**Comment by glennw** [comment]
@mrobinson Depending on what you're testing, you may be able to use --device-pixel-ratio=2 even on a non-hidpi monitor to test with.
