### ISSUE TITLE
Implement 'activation behavior' for <label> elements

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8179]
https://html.spec.whatwg.org/multipage/#the-label-element:the-label-element-10

**Comment by martiansideofthemoon** [comment]
@frewsxcv I would like to do try my hand at this issue. Where do I start?

**Comment by frewsxcv** [comment]
@Manishearth knows more about this than I do. For starters though, we might want to wait until https://github.com/servo/servo/pull/8178 merges since it implements the `control` attribute logic which will presumably be used by the 'activation behavior'.

**Comment by martiansideofthemoon** [comment]
Alright, do let me know :smile:

**Comment by Manishearth** [comment]
This isn't an easy issue (or even less easy), not until we figure out exactly what needs to be done here. The spec tells us to "do whatever the platform does", but that doesn't instruct us on how to handle mutation of the `for` attr in event handlers.

The main issue is that during the execution of one of the event handlers during activation, the `for` attribute might be mutated, so the post activation or canceled activation steps may not behave as expected. I suspect we should be caching the `for` element when the element is activated and using that later, but I'd like to see what other browsers do first.

We also don't know if we should be proxying the activation or doing something else. 

@martiansideofthemoon  If you'd like to help, test out cases in existing browsers where:

 - a label associated with a checkbox is clicked, with click handlers on both the label and the checkbox
 - same situation as above, but where one of the event handlers mutates the label's `for` attribute to a different, already checked, checkbox (for both event handlers)
 - same situation as above, but where one of the event handlers cancels the event
 - same situation, one of them cancels the event but also mutates the `for` attribute

**Comment by Manishearth** [comment]
Actually, the spec also mentions

> For example, on platforms where clicking a checkbox label checks the checkbox, clicking the label in the following snippet could trigger the user agent to run synthetic click activation steps on the input element, as if the element itself had been triggered by the user


I'm okay with doing that. In this case, add an impl of `Activatable` to HTMLLabelElement (make sure to add an entry in `as_maybe_activatable`), similar to that in htmlanchorelement.rs, htmlinputelement.rs, and htmlbuttonelement.rs.

The instance is only activatable if `GetControl()` exists (I think? perhaps it is activatable in all cases -- we'll have to verify this later), has no pre-click or canceled activation behavior, and its activation behavior just delegates to `synthetic_click_activation` on the associated control. `implicit_submission` should also probably forward to the associated control (Perhaps? We need to verify this too)

**Comment by frewsxcv** [comment]
Update: https://github.com/servo/servo/pull/8178 has merged

**Comment by Manishearth** [comment]
@martiansideofthemoon Do you intend to work on this?

**Comment by martiansideofthemoon** [comment]
@Manishearth :- Sorry for the delay. I tested the things you told me to on Google Chrome.
Here are the results :- 

>  a label associated with a checkbox is clicked, with click handlers on both the label and the checkbox

Here I observed both the onclick handlers being executed on pressing the label. Only the checkbox onclick handler was executed on clicking the checkbox
>   same situation as above, but where one of the event handlers mutates the label's for attribute to a different, already checked, checkbox (for both event handlers)

Assuming you meant both the handlers, (of the checkbox and of the label) mutate the `for` attribute,
I observed that both handlers were executed everytime I clicked the label, irrespective of whether the second checkbox was checked or unchecked. However if the mutation was to a non existent checkbox id, **only the label checkbox event handler executed**.

Adding the others too soon.

**Comment by Manishearth** [comment]
Cool. You can start work on the implementation now if you want -- given that the example recommendation of the spec seems to match these results.

**Comment by martiansideofthemoon** [comment]
Could you tell me the relevant files? I wasn't clear about what you meant by "same situation as above" in the third and fourth test case you mentioned. Were you referring to the situation in the first case ?

**Comment by Manishearth** [comment]
> Were you referring to the situation in the first case ?

Yep!

Relevant files are htmllabelelement.rs, and `as_maybe_activatable` in element.rs.

**Comment by martiansideofthemoon** [comment]
@Manishearth do I need to write [1] inside the `as_element` function or do I need to implement it like in [2] ? Also do I have to code all the `Activatable` functions like in htmlinputelement.rs?
[1] - https://github.com/servo/servo/blob/af8a1cb8a03e661f27c738512254a8f31915f3ba/components/script/dom/htmlelement.rs#L177-L179
[2] - 
https://github.com/servo/servo/blob/674589c370d978f543e71f995d58c5b28e6e9842/components/script/dom/htmlbuttonelement.rs#L233

**Comment by Manishearth** [comment]
Like [1]

Most of the Activatable functions should be blank. as_element should have a regular impl, `is_instance_activatable` should return true (though this is a grey area), leave implicit_submission blank for now (we need to check if it's possible to select labels, and if so, submit using them.), and activation_behavior should run synthetic click on the target if possible. The others should be empty.
