### ISSUE TITLE
Make test-wpt run with RUST_BACKTRACE=1 by default

### ISSUE THREAD

**Issue by jdm** [servo/servo#8194]
This is a particularly bad problem because the script task usually double-panics if a panic occurs, and rust always prints out the backtrace for the second one. This makes people focus on the wrong panic.

Code: python/servo/testing_commands.py

**Comment by nxnfufunezn** [comment]
I am taking this one!

**Comment by jdm** [comment]
@nxnfufunezn Any progress?
