### ISSUE TITLE
Support running test-css with the webrender backend.

### ISSUE THREAD

**Issue by glennw** [servo/servo#8198]
cc @jgraham as requested :)

The webrender code currently lives in https://github.com/glennw/servo/tree/webrender - so it would probably make sense to make a PR there, and then that can be merged when the whole webrender integration lands.

It is currently enabled by passing -w on the command line to servo, although that may change in the future (we should perhaps clean up the whole -c, -g, -g options and have a --backend=... option).

**Comment by jgraham** [comment]
I have a patch that provides the framework for this in wptrunner.

**Comment by jgraham** [comment]
https://github.com/w3c/wptrunner/pull/151

**Comment by glennw** [comment]
@jgraham Thanks. What is the next step in making this usable in the webrender branch?

**Comment by jgraham** [comment]
Update the version of wptrunner in the servo repo from upstream.  I can make a PR.

**Comment by jgraham** [comment]
Oh and to be clear you'll still need to update the wptrunner code more to actually allow webrender as a backend, but do that on your branch and upstreaming the change should be easy.

**Comment by jgraham** [comment]
#8230

**Comment by mrobinson** [comment]
This is supported now, isn't it? I run CSS tests with webrender by passing --servo-backend=webrender.
