### ISSUE TITLE
Add wpt-test for brotli compression

### ISSUE THREAD

**Issue by nxnfufunezn** [servo/servo#8207]
Python library which can be used [brotlipy](https://github.com/python-hyper/brotlipy/)
Tests has to be implemented like this [gzip.py](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/XMLHttpRequest/resources/gzip.py)
For more info see here : https://github.com/servo/servo/pull/8192

**Comment by jdm** [comment]
Our policy is to require tests for all new features, so #8192 will need one before merging.

**Comment by nxnfufunezn** [comment]
As jgraham pointed out that brotlipy has some third party components that requires compilation and currently there is no wpt that has this issue.
So what should we do here ?

**Comment by eefriedman** [comment]
For a one-off test, maybe you could just stick a binary file into the testsuite?

**Comment by nxnfufunezn** [comment]
yeah..we can do that..
