### ISSUE TITLE
Is Window::force_reflow racey?

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8209]
From `Window::force_reflow`:
```rust
        // FIXME(cgaebel): this is racey. What if the compositor triggers a
        // reflow between the "join complete" message and returning from this
        // function?
```

This was added in <https://github.com/servo/servo/commit/dafd0b652d8b5452e485a8430c8e120029fcdbbd> (<https://github.com/servo/servo/pull/3164>).

@cgaebel, what's up here?

**Comment by cgaebel** [comment]
Uhhh I don't remember, sorry! Feel free to remove the comment.
