### ISSUE TITLE
Implement Blob variant of WebSocket.send

### ISSUE THREAD

**Issue by jdm** [servo/servo#8213]
Spec: https://html.spec.whatwg.org/multipage/comms.html#dom-websocket-send and https://html.spec.whatwg.org/multipage/comms.html#the-websocket-interface:dom-websocket-send

We only support sending strings right now. We should refactor the websocket code to have a `send_impl` method that contains the common behaviour for all variants, and add one for dealing with Blobs that extracts the blob contents implements the specification. 

Code: components/script/dom/webidls/WebSocket.webidl, components/script/dom/websocket.rs
Tests: `./mach test-wpt tests/wpt/web-platform-tests/websockets/`

**Comment by jdm** [comment]
This is claimed for a potential contributor; please talk to me before working on it.

**Comment by nikkisquared** [comment]
I'm working on this here https://github.com/servo/servo/pull/8218!
