### ISSUE TITLE
Implement `:lang` CSS pseudo-class

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8219]
Spec: http://www.w3.org/TR/selectors/#lang-pseudo .  Information about how to actually determine the language of an element in HTML: https://html.spec.whatwg.org/multipage/dom.html#language .  The XML specification has similar language: http://www.w3.org/TR/2008/PER-xml-20080205/#sec-lang-tag .

Requires some changes to https://github.com/servo/rust-selectors so it can parse `:lang`.

Should be straightforward to implement.

**Comment by wenderen** [comment]
Can I take this?

**Comment by eefriedman** [comment]
Sure.  Feel free to ask if you need help.

**Comment by SimonSapin** [comment]
To avoid walking up the tree during selector matching we’ll want to cache the element’s language on every element’s DOM node, and update it on DOM tree changes.

**Comment by SimonSapin** [comment]
Now that https://github.com/servo/rust-selectors/pull/75 has landed, the parsing support for `:lang` can be implemented in `components/style/selector_impl.rs` by adding a `parse_non_ts_functional_pseudo_class` method like in tests for https://github.com/servo/rust-selectors/pull/75

**Comment by SimonSapin** [comment]
The algorithm described in https://html.spec.whatwg.org/multipage/dom.html#language to determine the language of an element involves traversing the tree to look at ancestors. Since that can be expensive and might be used repeatedly during selector matching, we likely want to cache the result of that algorithm on each element nodes. (And take care to update it when e.g. a `lang` attribute is changed through the DOM.)

**Comment by SimonSapin** [comment]
Looks like Gecko does do any such caching. I’m slightly surprised, but then the above was based only on guessing.

http://searchfox.org/mozilla-central/rev/f5077ad52f8b90183e73038869f6140f0afbf427/layout/style/nsCSSRuleProcessor.cpp#1803
http://searchfox.org/mozilla-central/rev/f5077ad52f8b90183e73038869f6140f0afbf427/dom/base/nsIContent.h#952

**Comment by Manishearth** [comment]
This doesn't seem to handle inheritance of the lang attr?

Gecko implements some of the lang stuff as if it were a pres attr setting a secret internal inherit property.

**Comment by SimonSapin** [comment]
> Gecko implements some of the lang stuff as if it were a pres attr setting a secret internal inherit property

That’s what what I understand is going on…

`SelectorMatches()`, when encountering `CSSPseudoClassType::lang`, calls `aElement->GetLang()` which looks for a `lang` attribute and calls `GetParent` in a loop. As far as I can tell, there is no caching at all.

http://searchfox.org/mozilla-central/rev/cac6cb6a10afb8ebb2ecfbeeedaff7c66f57dd75/layout/style/nsCSSRuleProcessor.cpp#1803
http://searchfox.org/mozilla-central/rev/cac6cb6a10afb8ebb2ecfbeeedaff7c66f57dd75/dom/base/nsIContent.h#940
