### ISSUE TITLE
Implement Document.createTouchList

### ISSUE THREAD

**Issue by jdm** [servo/servo#8225]
Spec: https://w3c.github.io/touch-events/#widl-Document-createTouchList-TouchList-Touch-touches and https://w3c.github.io/touch-events/#idl-def-Document

We started implementing support for touch events on websites recently, and some websites want to use an API that we don't implement yet. We need to add the declaration to the WebIDL (next to `createTouchEvent`), and add the corresponding Rust method to the `Document` implementation that returns a new `TouchList` object. There's an example of doing this in `handle_touch_event`.

Code: components/script/dom/webidls/Document.webidl, components/script/dom/document.rs
Test: `./mach test-wpt tests/wpt/web-platform-tests/touch-events/create-touch-touchlist.html`

**Comment by jdm** [comment]
This is reserved for a potential new contributor, so please talk to me before starting to work on this.

**Comment by jdm** [comment]
This is available for anybody :)

**Comment by k-cross** [comment]
Maybe I'll give it a shot.

**Comment by jdm** [comment]
Great!

**Comment by k-cross** [comment]
just committed in a PR, i hope it's everything that's needed.
