### ISSUE TITLE
layout_interface::Msg::Reflow should store ScriptReflow rather than Box<ScriptReflow>

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8238]
This dates back to <https://github.com/servo/servo/commit/1b030480abdf9c7a36a5dc0bea59e6f6aae63082>; there doesn't seem to be an explanation given there.

@pcwalton, any reason not to do this?

**Comment by pcwalton** [comment]
No reason not to do this.

**Comment by Ms2ger** [comment]
The code is in `components/script/layout_interface.rs` and `components/script/dom/window.rs`.

**Comment by itsmeolivia** [comment]
I can take a look at this!

**Comment by eefriedman** [comment]
If you have any questions, feel free to ask here or on IRC (#servo on irc.mozilla.org).

**Comment by jdm** [comment]
Fixed by #8290.
