### ISSUE TITLE
Tidy check to make sure manifest items are in order

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8269]
To prevent us from having to do things like this: https://github.com/servo/servo/pull/8268

**Comment by Wafflespeanut** [comment]
This just involves writing another function (`check_manifest`) that checks those `MANIFEST.json` files. I'm thinking of something like this (though I'm happy with a better idea):

- travel through the file contents and parse the stuff in "items" - have separate lists for "manual", "reftest", "stub", etc.
- sort all those lists with respect to their "path" (or "url"), and include the indexes (we need to show the line numbers if an error occurs)
- check whether the lines in the file contents match with our sorted lists - if not, boom!

Code: `python/tidy.py`

**Comment by GuillaumeGomez** [comment]
If no one's on it, I'll take it.

**Comment by eefriedman** [comment]
This was fixed in #8601, I think?

**Comment by Wafflespeanut** [comment]
@eefriedman Ah, whoops! In that case, checking stuff in tidy is probably useless :/

**Comment by Wafflespeanut** [comment]
Closing this issue...

@GuillaumeGomez Sorry I didn't notice this at first :/
