### ISSUE TITLE
Run the wpt lint

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8285]
wpt has a lint script that checks for formatting errors such as using tabs; we should run it to avoid autolanding code upstream that makes it fail, as we did in https://github.com/w3c/web-platform-tests/commit/3d92a107fe33a9a0b315814271264f37c4c732c8.

**Comment by jdm** [comment]
I recommend doing this as part of `test-tidy`.

**Comment by jmr0** [comment]
I started looking at this issue and noticed that running `./lint` under our repo resulted in 3000 or so errors. It seems like the lint tool determines what files to check by running `git ls-tree`, and in our repo's case this command recursively expands wpt submodules `tools` and `resources`, producing these errors. These submodule directories are ignored when the same command is run under w3c/wpt's repo. Unfortunately the lint tool does not accept any command line arguments to ignore directories, just entries to the `lint.whitelist` file. 

@Ms2ger do you have any suggestions as to how we should proceed with this one? Not sure if it's a matter of git hackery on our part.

**Comment by Ms2ger** [comment]
Thanks for looking into it! I'll leave the final decision to @jgraham, but I think it would be fine to add the submodules to `lint.whitelist`.

**Comment by jgraham** [comment]
Yeah that's fine.
