### ISSUE TITLE
Make test-tidy check that reftests contain a <link> specifying the reference file

### ISSUE THREAD

**Issue by jdm** [servo/servo#8297]
This is a recurring issue, and I often forget to check for this as long as the manifest changes look appropriate. I propose:
* we move all reference files from `tests/wpt/mozilla/tests/css` into a `ref` subdirectory (ie. the files that don't contain `<link`)
* we make `test-tidy` check all of the html files in `tests/wpt/mozilla/tests/css` (but not subdirectories) for the presence of a `<link` string

code: python/tidy.py

**Comment by nerith** [comment]
I'd like to take this.

**Comment by eefriedman** [comment]
Hmm... looking at this again, I'm not sure the proposed solution is the best way to solve this.  Could we do something like make a buildbot regenerate the manifest, then error if that introduces any changes?

**Comment by jdm** [comment]
That's an interesting idea. We've certainly talked about doing that for Cargo.lock files in the past.

**Comment by jdm** [comment]
Filed #8587 for that suggestion.
