### ISSUE TITLE
iframe content does not resize when iframe element is resized

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8301]
```html
<style>
  iframe {
    border: 1px solid black;
    height: 200px;
  }
</style>

<iframe width='200' src="data:text/html,<style>html{background:red}</style>"></iframe>

<script>
  setTimeout(() => {
    document.querySelector('iframe').width = 400;
  }, 2000);
</script>
```

**Comment by eefriedman** [comment]
(This works correctly from the perspective of content; it just doesn't get drawn on the screen correctly.)

I thought this was a duplicate, but I can't seem to find it.

**Comment by paulrouget** [comment]
It's a regression. Started with 1a494b1a73e0f1336c07100e8c6c2f444212fecb.

/cc @mrobinson

**Comment by paulrouget** [comment]
> I thought this was a duplicate, but I can't seem to find it.

Maybe you were thinking of issue https://github.com/servo/servo/issues/8081 where iframe content is not drawn after navigation.

**Comment by mrobinson** [comment]
@paulrouget I've confirmed this and have a fix locally. I think the actual culprit is https://github.com/servo/servo/pull/7423. That would not be too surprising because it was a major rework to fix an architectural flaw. I'll try to get a PR ready today.
