### ISSUE TITLE
Intermittent timeout in canvas_over_area.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#8311]
I suspect this may be related to #7787? I thought that was mac-only, though.

```
/_mozilla/css/canvas_over_area.html
-----------------------------------
TIMEOUT [Parent]
```

**Comment by nox** [comment]
@jdm If you are correct that it is related to #7787, maybe we should enable this one again, given that other ticket got fixed for unknown reasons?

**Comment by jdm** [comment]
Worth a shot!
