### ISSUE TITLE
CSS 3D transforms cut along the compositor borders

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8329]
![s](https://cloud.githubusercontent.com/assets/373579/10934663/82578668-82e1-11e5-890a-6f0168820509.gif)

```html
<style>
  div {
    background: #f06;
    top: calc(50vh - 100px);
    left: calc(50vw - 100px);
    height: 200px;
    width: 200px;
    position: absolute;
  }
</style>

<body>
  <div></div>
</body>

<script>

  const cssGimbal = (x, y, z, rx, ry, rz) => `translate3d(${x}px, ${y}px, ${z}px) rotateX(${rx}deg) rotateY(${ry}deg) rotateZ(${rz}deg)`;

  var div = document.querySelector('div');
  var t = 0;
  setInterval(() => {
    t += 0.05;
    x = 1000 * Math.cos(t);
    y = 1000 * Math.sin(t);
    div.style.transform = cssGimbal(
      (x * -0.02),
      (y * -0.07),
      -400,
      (-1 * (y * 0.02)),
      (x * 0.02),
      0
    );
  }, 20);
</script>
```

**Comment by glennw** [comment]
This only seems to occur when device-pixel-ratio=2 (which is set automatically when running on a retina screen on mac) so hopefully it's something fairly simple - I'll look into it further tomorrow. This test also runs correctly on the webrender branch with a much better frame rate too :)

**Comment by glennw** [comment]
It seems that the device pixel ratio is a red herring - it happens to make it work in this case, but only by chance. The main issue appears to be how the DL optimizer handles intersecting tiles with transformed stacking contexts. Still looking into it.
