### ISSUE TITLE
Add servo-starters to the contributing.md

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/servo#8338]
http://servo.github.io/servo-starters/ should replace the https://github.com/servo/servo/labels/E-easy of contributing.md. 
Thanks !

**Comment by saneyuki** [comment]
> http://servo.github.io/servo-starters/ should replace the https://github.com/servo/servo/labels/E-easy of contributing.md. 

replace is nice :)

By the way, will https://github.com/servo/servo/labels/E-easy be removed?

**Comment by eefriedman** [comment]
Probably not worth keeping both around.

**Comment by eefriedman** [comment]
(I mean the links; obviously the label itself will still exist.)

**Comment by jdm** [comment]
I'm in favour of giving people links to familiar things, too.
