### ISSUE TITLE
Support mozbrowsericonchange event (Browser API)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8347]

**Comment by paulrouget** [comment]
I'm giving it a try: https://github.com/paulrouget/servo/commit/97cee8b8157134384afdb2d39132be2ee6b4ce87

At the moment, we are limited by the `event.detail` property. It only supports strings (see https://github.com/servo/servo/blob/master/components/script/dom/htmliframeelement.rs#L133).

@glennw what would you recommend here? `MozBrowserEvent::detail()` returns a string. Maybe it should return a json-like data structure (hashmap?) that would be converted to jsval in  `HTMLIframeElement::dispatch_mozbrowser_event()` ? But I'm not sure a hashmap is good enough. Do we have a generic JSON-like structure in Rust/Servo? Or should we translate to a jsval directly in `MozBrowserEvent::detail()`?

**Comment by jdm** [comment]
We have two JSON representations ([first](http://doc.servo.org/serde_json/value/enum.Value.html), [second](http://doc.servo.org/rustc_serialize/json/enum.Json.html)), but I propose making `detail()` take a `MutHandleValue` argument and directly converting the values rather than having a rust-typed common return.

**Comment by paulrouget** [comment]
@jdm I'm trying to use `to_jsval` in `msg/constellation_msg.rs`, so I guess I need `use script::dom::bindings::conversions::{ToJSValConvertible};` which requires the `script` crate. Adding the script dependency in msg end up with a cyclic package dependency:

```
cyclic package dependency: package `devtools_traits v0.0.1 (file:///Users/paul/git/servo/components/servo)` depends on itself
```

What's the right approach in this case?

**Comment by eefriedman** [comment]
> I'm trying to use to_jsval in msg/constellation_msg.rs

Don't do that.  You shouldn't be handling a JSContext outside of the script crate/thread.

**Comment by jdm** [comment]
The right approach is to make 'detail' a method of a trait that's defined in the script crate.

**Comment by paulrouget** [comment]
moving `detail` into the script crate works, but I'm having difficulties building the JS object.

- Should I build the object manually with `RootedObject::new` and `JS_DefineProperty` (or `define_properties`)?
- Should I build the object via `to_jsval`? This might require adding a new conversion method `conversions.rs`
- Would creating a `BrowserIconChangeEventDetail` interface in `BrowserElement.webidl` help in any way?

**Comment by jdm** [comment]
Creating a `BrowserIconChangeEventDetail` dictionary is probably the way to go, rather than an interface. That should allow us to fill out the properties of the corresponding Rust object and then calling `to_jsval`.

**Comment by paulrouget** [comment]
feedback? https://github.com/paulrouget/servo/commit/2f5fa1be560ae8f022975d58fb2c7492f5ffc448

Does this look like the right approach?

Still need to do some clean-up, address the fixme, and write some tests

**Comment by jdm** [comment]
It does!
