### ISSUE TITLE
Reduce duplication of the "android-18" property in the Android build

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#8348]
If you look at:
https://github.com/servo/servo/search?utf8=%E2%9C%93&q=android-18

You'll see that we have copies of the string "android-18" in a project properties file, a .mk file, and some Rust code. This can probably be broken out into an environment variable set in the Mach/python driver that is expanded in the appropriate ways for the .mk file and Rust code, and gets generated into the properties file by passing the correct flags to the `android project update` command.

Instructions for building to target Android are available here:
https://github.com/servo/servo/wiki/Building-for-Android

**Comment by jdm** [comment]
#8519 was proposed to solve this issue. It requires further investigation to figure out precisely why it doesn't work on the build machines. There are comments explaining how to reproduce the issue locally.

**Comment by mitchhentges** [comment]
I think I got this, fam
