### ISSUE TITLE
Ensure that there are no unexpected undefined symbols in the Android binary

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#8351]
Unlike on our other platforms, on Android, the loader ensures that all symbols can be loaded immediately at load-time. Unfortunately, this feature causes the Android build to frequently break when people add a reference to a symbol that might never be called (e.g., a stub with a mistyped binding in a -sys package).

This task is to add some code to the Android package build rules (https://github.com/servo/servo/blob/master/support/android/build-apk/src/main.rs) to ensure that the `libservo.so` file has no unexpected undefined & unresolved symbols. One way to do this from the commandline is the following:

```
[larsberg servo]$ ~/ndk-standalone/bin/arm-linux-androideabi-objdump -T ~/servo/target/arm-linux-androideabi/debug/libservo.so  | grep -e "D " | grep -e "*UND*"
00000000      D  *UND*	00000000 malloc_usable_size
```

Note that `malloc_usable_size` is the only acceptable exception - anything else that occurs in this output is more than likely an error (or at least would require review!).

For this issue, you will need to be able to build for Android: https://github.com/servo/servo/wiki/Building-for-Android

**Comment by asajeffrey** [comment]
We hit this issue over at https://github.com/servo/mozjs/pull/60#issuecomment-153894198 - it would be nice if the CI could catch this!

**Comment by askalski** [comment]
OK, and suppose I write this: how to warn CI for such occurence? Write something to stderr? Is there some warn! macro? Or make some sub-program exit with nonzero code?

**Comment by jdm** [comment]
The last one, and then add it to the buildbot config in servo/saltfs.

**Comment by cengizIO** [comment]
Hello. I'm new to Rust and Servo. 

I'm comfortable with cross compiling, tooling etc.

I'd like to take this issue if nobody else is claiming it.

**Comment by larsbergstrom** [comment]
@cengizIO Great! Please feel free to ask any questions here if you need any clarifications.

**Comment by larsbergstrom** [comment]
@cengizIO Sorry I missed you on IRC! Can you ask any questions that you have here?

**Comment by larsbergstrom** [comment]
We had a chat on IRC, and I confirmed that `unshare` (seen in the output below) should also be safe... since Servo is currently running just fine on Android :-)

```
3:47 PM <cengizIO> $ arm-linux-androideabi-objdump -T libservo.so | grep "D "
3:47 PM <cengizIO> 00000000      D  *UND*	00000000 unshare
3:47 PM <cengizIO> 00000000      D  *UND*	00000000 malloc_usable_size
```
