### ISSUE TITLE
Dispatch mozbrowsershowmodalprompt event for alert()

### ISSUE THREAD

**Issue by jdm** [servo/servo#8352]
When [browser.html](https://github.com/mozilla/browser.html/) is using servo, it wants to intercept calls like `window.alert('foo')` and show its own prompt, instead of relying on Servo's default behaviour. We need to implement the [part of the Browsing API](https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowsershowmodalprompt) related to this, by creating a `CustomEvent` that matches the specification and dispatching that in `Window::Alert`. `dispatch_mozbrowser_event` in `htmliframeelement.rs` is a good model for this.

Code: components/script/dom/window.rs

**Comment by jdm** [comment]
Actually, my initial suggestion for solving this isn't what we're looking for. We should add any required information to the `ShowModalPrompt` enum variant in `constellation_msg.rs`, then use the `trigger_mozbrowser_event` API on `Document` to ensure we dispatch the DOM event at the right place.

**Comment by simartin** [comment]
I'd like to give it a try; I guess I should use JSObject to represent the "detail" property, correct?

**Comment by jdm** [comment]
For that, we should build on the changes in #8347.
