### ISSUE TITLE
Split global constellation receiver into two (script and compositor)

### ISSUE THREAD

**Issue by jdm** [servo/servo#8356]
There are a couple parts to this:
* replace the single receiver with two separate ones
  * make the constellation event loop (`Constellation::run`) select over the two receivers (see `layout_task.rs` for a similar model)
  * provide the appropriate sender when creating new script tasks (probably requires returning a second sender from `Constellation::start`)
* split the `constellation_msg::Msg` enum into `constellation_msg::ScriptMsg` and `constellation_msg::CompositorMsg` enums that only contain the messages that are appropriate for each sender, and update the types of the various senders and receivers involved, and update all users of the newly-typed senders

Code: components/compositing/constellation.rs, components/msg/constellation_msg.rs

**Comment by jdm** [comment]
After this change it will be easier to tell if there are risks of deadlocks between the constellation and the script tasks.

**Comment by KiChjang** [comment]
We might want to add an additional `constellation_msg::NetworkMsg` for all the flavors of fetch as described by #4576. I'll take a look at this over the weekend and see what I can do.

**Comment by KiChjang** [comment]
Quick question: will I run into type incompatibilities if I split `constellation_msg::Msg` into `constellation_msg::ScriptMsg` and `constellation_msg::CompositorMsg` while I am receiving messages from the channel? We currently now have the following:
```rust
    fn run(&mut self) {
        loop {
            let request = {
                let receiver_from_script = &self.script_receiver;
                let receiver_from_compositor = &self.compositor_receiver;
                select! {
                    msg = receiver_from_script.recv() => msg.unwrap(),
                    msg = receiver_from_compositor.recv() => msg.unwrap()
                }
            };
            if !self.handle_request(request) {
                break;
            }
        }
    }
```
and receiver_from_script has the type of `Receiver<ScriptMsg>` and receiver_from_compositor has the type of `Receiver<CompositorMsg>`.

**Comment by jdm** [comment]
Yep! This is why we we stuff like http://mxr.mozilla.org/servo/source/components/layout/layout_task.rs#482 in other places.
