### ISSUE TITLE
Investigate reducing the size of Node::unique_id

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8360]
The size of `Node::unique_id` is currently four pointers (256 bits); that seems a bit excessive for a unique ID.

**Comment by jdm** [comment]
Note that they're intended to be globally-unique values, not just within a page.

**Comment by vegayours** [comment]
I have done a little investigation into this question.
I'm not very experienced in rust, correct me if I wrong.

Currently Node::unique_id is DomRefCell\<String>, which is lazily initialized to string value of Uuid on first access to get_unique_id.
Empty string costs 8 bytes * 3 as Vec<u8> (size, data ptr, capacity)  + 8 bytes for RefCell overhead = 32 bytes.
When uuid is initialized it costs  32 bytes + 16 bytes (uuid size) * 2 (converted to hex string) = 64 bytes.

We can easily change this to DomRefCell\<Option\<Box\<Uuid>>> internally.
Assuming that Option is optimized out we will have:
Empty - 8 (ptr size) + 8 (RefCell overhead)  = 16 bytes.
Initialized - 16 + 16 (uuid size) = 32 bytes.
And this change won't be visible for outside code as get_unique_id will return String.

These all really looks like microptimisization (but there are a lot of nodes on typical page, so we can save a few bytes). I'm not shure if we really need DomRefCell here.

I can make PR if it matters.

**Comment by jdm** [comment]
That sounds like a good choice to me!

**Comment by jdm** [comment]
Fixed by #8589.
