### ISSUE TITLE
Check if lock files change after build on Travis

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8363]
Use this script: https://github.com/servo/servo/pull/8361

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/8361/files#diff-354f30a63fb0907d4ad57269548329e3R12 ?

**Comment by frewsxcv** [comment]
Yep. Was going to close this once that merges

**Comment by frewsxcv** [comment]
Fixes in #8361
