### ISSUE TITLE
Create landing page for servo.org

### ISSUE THREAD

**Issue by edunham** [servo/servo#8365]
https://github.com/servo/servo.org should contain a web page rather than just a redirect. Requirements: 

* Summarize Servo project's purpose (modern, performant browser engine appropriate for applications including embedded use)
* Link to GitHub org
* Link to blog.servo.org
* Link to http://servo.github.io/servo-starters/
* Look nice (could start with the CSS from https://github.com/rust-lang/rust-www)
* Able to be rendered with Servo

**Comment by nerith** [comment]
I'd like to work on this.

**Comment by edunham** [comment]
@nerith thank you! It's probably best to enable github pages on a personal fork of https://github.com/servo/servo.org to test changes, then make a PR once you're happy with the page.

**Comment by lucywyman** [comment]
Staging landing page at http://lucywyman.github.com/servo.org

PR #4

**Comment by metajack** [comment]
Wow! Nice work!

**Comment by nerith** [comment]
My prototype of the landing page is at http://nerith.github.io/servo.org
The page is able to be rendered with Servo as well.

**Comment by edunham** [comment]
@lucywyman Has your prototype been tested in Servo?

**Comment by lucywyman** [comment]
@edunham Yeah -- I built the latest release version from github:

![selection_007](https://cloud.githubusercontent.com/assets/5055819/11005307/d8804926-8471-11e5-8a7c-088bb97fde15.png)

**Comment by edunham** [comment]
@nerith, @lucywyman Thank you both for the site prototypes! We just talked about them in the Servo meeting and the team's consensus is that we love the content completeness and GitHub, blog, and contributing icons of @lucywyman's prototype, yet feel that the visual style of @nerith's is more consistent with Rust's themes and portrays the more serious, researchy (as opposed to playful, start-up-like) tone that we'd prefer going forward. 

In my opinion, the easiest way to combine the best of both prototypes will be to merge @nerith's PR, then ask @lucywyman to PR against the repo to update the site's content and icons. Does this sound good to both of you? 

Thank you both again for the speedy, awesome work -- choosing between the two prototype sites has been a surprising and wonderful problem to have.

**Comment by lucywyman** [comment]
Sounds good :)

**Comment by nerith** [comment]
@edunham Sounds good.

**Comment by edunham** [comment]
Thank you both again for all the hard work!
