### ISSUE TITLE
github.com doesn't fill up the browser window

### ISSUE THREAD

**Issue by skeuomorf** [servo/servo#8373]
OS: Arch Linux 
Kernel: GNU/Linux 4.2.5-1 x86_64
Window Manager: Awesome

![servo](https://cloud.githubusercontent.com/assets/1059260/10997894/943ef122-8499-11e5-8657-a0841dd6da41.png)

**Comment by notriddle** [comment]
Well, it isn't the window manager that did it:

![image](https://cloud.githubusercontent.com/assets/1593513/11004920/2069a902-8478-11e5-94ad-aadf242abfcc.png)

**Comment by skeuomorf** [comment]
@notriddle Hmm, it appears so, that's gnome, right?

**Comment by notriddle** [comment]
Right.

**Comment by notriddle** [comment]
This is a regression introduced by d0ace58452c704a3888b3a32a8242a5217b44274.

**Comment by notriddle** [comment]
A test case:

```html
<div><iframe src="data:text/html,&lt;meta name='viewport' content='width=100'&gt;&lt;p style='border: solid'&gt;Test" width=200></iframe></div>
<div><iframe src="data:text/html,&lt;p style='border: solid'&gt;Test" width=200></iframe></div>
```

![screenshot](https://cloud.githubusercontent.com/assets/1593513/11171439/c9ab4b9c-8bad-11e5-8950-b6b9411aebe8.png)
