### ISSUE TITLE
Arrow keys in a focused text box scroll the page

### ISSUE THREAD

**Issue by jdm** [servo/servo#8379]
We need to call `preventDefault` on the event that we process in `handle_event` for both `HTMLTextAreaElement` and `HTMLInputElement` (but only in the cases that we redraw the selection or dispatch input). If the default action for the event isn't prevented, we end up telling the compositor that the key wasn't handled so it can perform its default actions (like scrolling the page).

Testcase: https://hire.jobvite.com/CompanyJobs/Careers.aspx?c=qpX9Vfwa&k=Apply&j=ozy21fwU&utm_source=careers.mozilla.org&s=PDN&utm_medium=referral (press up and down in the textbox)
Code: `components/script/dom/htmlinputelement.rs`, `components/script/dom/htmltextareaelement.rs`

**Comment by Ms2ger** [comment]
No test?

**Comment by jdm** [comment]
What sort of automated test are you thinking of?

**Comment by jdm** [comment]
Fixed by #8400.
