### ISSUE TITLE
'loop { match { .. }}' could be turned into 'while let { .. }'

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8384]
https://github.com/servo/servo/blob/a0221b91268307b1c2690241a4d24816471c915e/components/compositing/compositor.rs#L2130-L2139

https://github.com/servo/servo/blob/faf2f34772fe06396a7b8542b00f0566832bc7ef/components/compositing/scrolling.rs#L57-L67

**Comment by rnestler** [comment]
I tried to fix this issue in PR #8393 is that what you had in mind? I haven't tested it yet though.

**Comment by frewsxcv** [comment]
@rnestler Looks great! Can you also take care of the other case in the description above? Should be very similar

**Comment by rnestler** [comment]
@frewsxcv Thanks for the fast feedback :smiley: I'll also look at the other case.
