### ISSUE TITLE
Do not attempt to execute JS from 404 responses

### ISSUE THREAD

**Issue by catrope** [servo/servo#8391]
Load the following file in Servo:
```
<!doctype html>
<html>
<head>
	<script src="http://example.org/urlthat404s" onerror="alert('fail');"></script>
	<script src="http://domainthatdoesntexistfdjklajgdklgjfkgjf.org/blah" onerror="alert('fail2');"></script>
	<script>alert('success');</script>
</head>
<body>
<h1>Hello</h1>
</body>
</html>

```
and you'll get
```
ERROR:js::rust: Error at http://example.org/urlthat404s:0:0: expected expression, got '<'

ERROR:script::dom::htmlscriptelement: error loading script failed to lookup address information: Name or service not known
ALERT: fail2
ALERT: success
```
The 404 response contains HTML, and servo attempts to execute this HTML as JS.

In both Firefox and Chrome, 404 responses are not executed, and instead the error event is emitted, as specified by http://www.w3.org/TR/html5/scripting-1.html#execute-the-script-block . In these browsers, three alerts (fail, fail2 and success) are shown.

(BTW, it would be nice if the DNS error message specified the domain that it failed to lookup)

**Comment by jdm** [comment]
Good find @catrope! The code that requires modifications lives in `components/script/dom/htmlscriptelement.rs` in the `headers_available` method - we should check the `status_code` field of the metadata received and ignore further notifications if it's not a success code.

**Comment by jdm** [comment]
I guess we'll also need to modify how `response_complete` deals with the situations as well, since we need to store an `Err` value to get the error event dispatch like the second entry in the testcase.

**Comment by catrope** [comment]
Thanks for pointing me to the code. I'm busy today but I'll try to write a
patch later.

And yes, ignoring notifications isn't enough, because the error event needs
to be fired.

**Comment by Wafflespeanut** [comment]
Unassigning this on inactivity

**Comment by frewsxcv** [comment]
To the next person who tries their hand at completing this issue, here is a previous attempt: https://github.com/servo/servo/pull/8422

**Comment by mattkuo** [comment]
I'd like to try to tackle this one

**Comment by Wafflespeanut** [comment]
Okay! :)

**Comment by Ms2ger** [comment]
https://html.spec.whatwg.org/multipage/#execute-the-script-block

This is specified pretty poorly though. I'd like to see some tests and their results in various browsers, and a spec bug.

Cc @Domenic

**Comment by domenic** [comment]
This is specified much better in the rewrite: https://dl.dropboxusercontent.com/u/20140634/script-type-module/index.html#fetch-a-classic-script step 5. (Asynchronously completing that algorithm with null will eventually go to https://dl.dropboxusercontent.com/u/20140634/script-type-module/index.html#execute-the-script-block step 2, firing an error event on the script element.) But I admit I didn't test various browsers.

**Comment by Ms2ger** [comment]
That means we're checking for https://fetch.spec.whatwg.org/#ok-status ; thanks for the response!

**Comment by KiChjang** [comment]
@mattkuo What's the status?

**Comment by Shiroy** [comment]
I'd like to fix this issue.

**Comment by jdm** [comment]
Please do!
