### ISSUE TITLE
Add support for the new, free and fast FLIF image format. 

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/servo#8392]
See: http://flif.info/
The github : https://github.com/FLIF-hub/FLIF

**Comment by jdm** [comment]
This is probably better filed against https://github.com/PistonDevelopers/image, which is the image decoding library that we use.

**Comment by LifeIsStrange** [comment]
Oh sorry this issue already exist on image ! 
https://github.com/PistonDevelopers/image/issues/469
