### ISSUE TITLE
Run webgl tests in web-platform-tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#8413]
http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/webgl/ exists, but it's skipped because it's not explicitly enabled in http://mxr.mozilla.org/servo/source/tests/wpt/include.ini . We should enable it and [update the expectations](http://mxr.mozilla.org/servo/source/tests/wpt/README.md#80).

**Comment by simartin** [comment]
@jdm I propose to take it

**Comment by eefriedman** [comment]
Sure!  Please ask if you have any questions.

**Comment by simartin** [comment]
I'm getting "is not a function" errors for gl.bufferSubData and gl.compressedTexSubImage2D that I don't manage to catch. I had a quick look and it seems to me we would need to amend (at least) CanvasWebGLMsg and WebGLRenderingContextMethods.
Does it make sense, at least on the diagnosis part?
I don't believe we have mechanisms to catch and PASS such "is not a function" errors, do we?

**Comment by jdm** [comment]
First and foremost we should enable the tests and mark the ones that currently fail (via the "update the expectations" link earlier). If you'd like to try to implement those WebGL operations in subsequent commits (or separate PRs), you're welcome to do so!
