### ISSUE TITLE
Add Dimension member to AttrValue, and fix related attribute parsing

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8417]
Misc places call `str::parse_length` on the value of an attribute; we should store the parsed result in Attr.

Relevant properties: https://html.spec.whatwg.org/multipage/#dimRendering , and everything else in the rendering section marked "maps to the dimension property" or "maps to the dimension property (ignoring zero)".  Probably everything needs to be reviewed so it actually matches the spec; for example, we currently parse `width` and `height` on `<img>` as an integer, which is wrong.

**Comment by frewsxcv** [comment]
I just implemented this without even noticing this issue. I'll take this.

**Comment by frewsxcv** [comment]
> and fix related attribute parsing

I agree some of these implementations are definitely wrong, but I want to wait for #8424 to merge before addressing that
