### ISSUE TITLE
refactor util::str::parse_length to return Result<LengthOrPercentage, &str>

### ISSUE THREAD

**Issue by ajnirp** [servo/servo#8425]
Follow up to #8423, depends on #8424

Code: `components/util/str.rs`
Test: `tests/unit/util/str.rs`

Currently, we return `LengthOrPercentageOrAuto::Auto` in places where we should be returning an `Err`.

**Comment by frewsxcv** [comment]
I'd have to look at the spec again, but maybe we should reconsider renaming this enum from `LengthOrPercentageOrAuto`/`LengthOrPercentage` into `Dimension`?

**Comment by nox** [comment]
It seems ok to me to continue to return a `LengthOrPercentageOrAuto`. The `AttrValue` variant is now named `Dimension`.
