### ISSUE TITLE
HTMLHRElement 'color' setter should use macro

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8433]
[This code](https://github.com/servo/servo/blob/f39faaf99471f5419710e1a3d434e5d5fab0d221/components/script/dom/htmlhrelement.rs#L43-L47) should use [this macro](https://github.com/servo/servo/blob/f39faaf99471f5419710e1a3d434e5d5fab0d221/components/script/dom/macros.rs#L218-L231)

**Comment by frewsxcv** [comment]
[an example](https://github.com/servo/servo/blob/f39faaf99471f5419710e1a3d434e5d5fab0d221/components/script/dom/htmlbodyelement.rs#L61)

**Comment by rilut** [comment]
@frewsxcv Can I take this too? Thanks.

**Comment by frewsxcv** [comment]
Sure!
