### ISSUE TITLE
Intermittent failure on /_mozilla/css/hide_after_create.html

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8435]
Seen in #8378.

I'm looking at this; my preliminary assessment is that it's possible to end up in a situation where the constellation takes a screenshot while there's a pending reflow... although I could be wrong.

**Comment by eefriedman** [comment]
My investigation unfortunately didn't turn up anything relevant... although it did reveal some unnecessary reflow messages from script to layout.

**Comment by jdm** [comment]
Hasn't been seen in months. Let's close.
