### ISSUE TITLE
Dimension properties being parsed incorrectly

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8445]
Continued from [this issue](https://github.com/servo/servo/issues/8417),

For example, [this section in the spec](https://html.spec.whatwg.org/multipage/rendering.html#tables-2:the-table-element-6) says that the height attribute be parsed as a **non-zero** dimension property. We are currently parsing using `util::str::parse_length`, which allows zero values. We should create a new function like `util::str::parse_length_nonzero` and use it where appropriate.

**Comment by frewsxcv** [comment]
Also, regression WPT tests would be great

**Comment by sylvesterwillis** [comment]
Would it be okay if an error is returned for `util::str::parse_length` based upon https://html.spec.whatwg.org/multipage/infrastructure.html#rules-for-parsing-non-zero-dimension-values if the value is empty or is zero?

**Comment by eefriedman** [comment]
Marked as assigned, so we don't duplicate work.  (Watch out for #8424, which has some relevant changes.)

Making parse_length return an error on zero doesn't make sense; it's not an error.

It might be possible to add a Zero member to LengthOrPercentageOrAuto... but I don't think that's the right approach; all of the other users of parse_length don't really care about zero vs. non-zero.

It's probably best to keep the existing signature of parse_length, and branch based on the result.

**Comment by frewsxcv** [comment]
#8526 has merged (the successor to #8242)

**Comment by frewsxcv** [comment]
@sylvesterwillis You make any progress on this?

**Comment by sylvesterwillis** [comment]
No, I haven't looked at this issue.

**Comment by frewsxcv** [comment]
I'll take this
