### ISSUE TITLE
'for' loop should be converted into a 'while let' loop

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8455]
https://github.com/servo/servo/blob/6772461002637cf4ae174a1c49d4418487f48cb9/components/script/dom/element.rs#L777-L800

**Comment by Ms2ger** [comment]
Why? Maybe it would be better to add `filter_map(Node::downcast::<Element>)`.

**Comment by frewsxcv** [comment]
I'll just take care of it right now
