### ISSUE TITLE
Website: Add navigation menu

### ISSUE THREAD

**Issue by edunham** [servo/servo#8458]
We need a navigation menu with links to the major sections of the page. Please test the menu with narrow window sizes or on a phone/tablet to make sure it still looks ok. Please test the menu using Servo to make sure it can still render the page correctly.

**Comment by rilut** [comment]
I'd like to work on this

**Comment by rilut** [comment]
@edunham Is Wikipedia-like Table of Contents ok? https://en.wikipedia.org/wiki/Aegean_cat#toc

**Comment by edunham** [comment]
@rilut Yeah, I think with a style that's visually consistent with the rest of the page, that type of TOC would be fine. Thank you for working on this!

**Comment by rilut** [comment]
@edunham so, now http://servo.org/ is tidy and concise, do you think it still need the TOC?

**Comment by KiChjang** [comment]
What's the status of this?

**Comment by rilut** [comment]
@KiChjang should we close this? I was thinking that TOC is no longer relevant anymore since Servo website is tidy and concise as per Nov 18, 2015. (It was even more concise than today). Or no? I'm happy to help if it still needed.

**Comment by rilut** [comment]
*mistaken* @KiChjang I'll contact you on IRC

**Comment by KiChjang** [comment]
servo/servo.org#19 has landed, should this issue be closed?
