### ISSUE TITLE
Navigating back and forth leads to a panic

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8461]
Similar to #8324

1. `./mach run -d http://news.ycombinator.com`
2. Click a link
3. `<backspace>`
4. Click a link
5. :boom:

[log](https://gist.githubusercontent.com/frewsxcv/2cbfa3e118bcaf568bbd/raw/85312cc36c77365baf00663b9bcf57ef6e6c8b20/gistfile1.txt)

**Comment by Manishearth** [comment]
Seems to be a timer issue?

**Comment by frewsxcv** [comment]
Related: #2574
