### ISSUE TITLE
Disabled webgl tests in web-platform-tests due to unimplemented APIs

### ISSUE THREAD

**Issue by simartin** [servo/servo#8462]
Fixing https://github.com/servo/servo/issues/8413 highlighted that the following APIs are missing in our WebGL implementation: compressedTexImage2D, compressedTexSubImage2D and bufferSubData. A good basis for adding them can be found in https://github.com/servo/servo/pull/5820

I'm willing to work on this

**Comment by jdm** [comment]
cc @ecoal95 to make sure that you're not already working on these ones.

**Comment by ecoal95** [comment]
No, I'm not, take it please!

Feel free to ask me for any info you might need @simartin :)

**Comment by simartin** [comment]
Grrr, it looks like I should not have referenced this issue in my patch to gleam... Is there any way to reopen this issue (it's not finished) or do I need to open a separate one?

**Comment by glennw** [comment]
@simartin Reopened :)

**Comment by dzbarsky** [comment]
Well that's annoying.
