### ISSUE TITLE
Node::remove algorithm doesn't match spec

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8465]
https://dom.spec.whatwg.org/#concept-node-remove

https://github.com/servo/servo/blob/aa105d89b4031d98376ac804e31e287f3bf21bb8/components/script/dom/node.rs#L1574-L1591

For example, our 'step 6' comment corresponds with 'step 7' of the spec

**Comment by frewsxcv** [comment]
Also, the spec has 11 steps, the Servo algorithm has 9

**Comment by nox** [comment]
I rewrote it in my range branch, I could make a separate PR I guess.

**Comment by frewsxcv** [comment]
Did your range branch ever get merged?

**Comment by nox** [comment]
Nope, it's an open PR.

**Comment by frewsxcv** [comment]
For reference https://github.com/servo/servo/pull/8506

**Comment by nox** [comment]
Unassigning myself, because I don't want to bitrot my own Range PR. Anyone is free to fix this though, this should be easy.

**Comment by schuster** [comment]
Anyone mind if I take this one?

**Comment by nox** [comment]
@schuster Not at all, go ahead!

**Comment by schuster** [comment]
A few questions now that I've come back to this issue and had a chance to look over it:

1. How can I get all node iterators associated with the node's document? Step 6 in the DOM requires running the pre-remove steps for those iterators
2. Step 10 of the spec says to do the removing steps, which seems to be something that might exist for certain kinds of nodes. Is this something Servo implements currently?
3. Step 11 of the spec mentions doing something with the registered observers for ancestor nodes, which I admittedly don't completely understand yet. I didn't see anything in my brief search through the code about this kind of observer. Does Servo implement registered observers?
4. Finally, could someone please point me in the direction of the relevant tests?

Thanks in advance - this is a first Servo bug for me, so I'm spending some time getting up to speed.

**Comment by frewsxcv** [comment]
I don't have time right now to look into all your questions, but at least for your fourth question:

https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/dom/nodes/ChildNode-remove.js

https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/dom/nodes/Element-remove.html

both of those tests are (possibly redundantly?) testing [this](https://dom.spec.whatwg.org/#dom-childnode-remove), which references the Node "remove" concept

**Comment by schuster** [comment]
Sorry for the long delay - I've been trying to look at this here and there as I've had time during a busy work period for me.

I submitted a pull request, but right now it looks like the only thing that can be done without significant feature additions is making the comments reflect the actual steps of the spec. Here's what's missing:

Step 6: There's currently no way to get the collection of all node iterators for the current document. I could look into implementing that, but that's a more involved process and I'd probably need guidance from a more experienced Servo dev.

Step 10: This appears to be special removing steps that are specific to the type of node removed. For now I don't see any nodes in the codebase that use something like this, but perhaps a stub method call of some kind could be added.

Step 11: This kind of registered observer doesn't appear to exist in Servo right now, but if there's already another issue out there to add them, it should probably reference this issue.

Happy to answer any questions/comments.

**Comment by schuster** [comment]
Should this issue be closed now that the PR is merged, or does more work need to be done for steps 6 and 11?

**Comment by nox** [comment]
Seems like this can be closed.
