### ISSUE TITLE
Move some LayoutTask methods to query.rs.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8470]
We started this in #6836.

Move the `LayoutTask` methods `process_node_geometry_request`, `process_resolved_style_request`, and `process_offset_parent_query` from `components/layout/layout_task.rs` to `components/layout/query.rs`.

In the process, the `&self` argument should be removed.

**Comment by rilut** [comment]
Can I try this?

**Comment by jdm** [comment]
Yes!

**Comment by rilut** [comment]
@jdm What to do if I'm stuck in "checking mergeability"?

**Comment by eefriedman** [comment]
"checking mergeability"... on the GitHub pull request page? Try reloading the page.

**Comment by rilut** [comment]
@eefriedman my bad, hard reload fixes this. Thanks.
