### ISSUE TITLE
Make all LayoutTask fields private.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8471]
Code: `components/layout/layout_task.rs`.

This will require inlining `tick_all_animations` from `components/layout/animation.rs` into its caller in `components/layout/layout_task.rs` first.

**Comment by hfaulds** [comment]
I'd be happy to give this a go!

**Comment by jdm** [comment]
Please do!

**Comment by staabm** [comment]
@jdm should be closed as #8485 was merged.
