### ISSUE TITLE
Use atom!("sizes") instead of Atom::from_slice("sizes")

### ISSUE THREAD

**Issue by jdm** [servo/servo#8488]
After #8449 merges, we can update the `string-cache` crate to 0.1.17 (using `./mach cargo-update -p string-cache`) and replace the instances of `Atom::from_slice("sizes")` with `atom!("sizes")` instead, since it's more efficient.

Code: components/script/

**Comment by romankl** [comment]
Could I take a look at this one?

**Comment by eefriedman** [comment]
Okay; marked assigned.

**Comment by paulrouget** [comment]
#8449 has merged.
