### ISSUE TITLE
Use the return value of invoking event handlers to cancel the value

### ISSUE THREAD

**Issue by jdm** [servo/servo#8490]
Specifically, we are missing step 4 in the [event handler processing algorithm](https://html.spec.whatwg.org/multipage/webappapis.html#the-event-handler-processing-algorithm) in `EventListenerType::call_or_handle_event`.

Code: components/script/dom/eventtarget.rs

**Comment by jdm** [comment]
Note that cancelling the event per the spec means calling `PreventDefault` on the event.

**Comment by jxs** [comment]
can i take this one?

**Comment by jdm** [comment]
@jxs Please do!

**Comment by frewsxcv** [comment]
@jxs Go for it!
