### ISSUE TITLE
Implement DOMMatrix.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8509]
Blocks #6097, #8822.

- Spec: https://drafts.fxtf.org/geometry/#DOMMatrix
- Code would be in new files (`components/script/dom/dommatrix.rs`, `components/script/dom/webidls/DOMMatrix.webidl`) and a `mod dommatrix;` in `components/script/dom/mod.rs`.
- Test: `./tests/wpt/css-tests/geometry-1_dev/html/DOMMatrix-001.htm` (metadata: `./tests/wpt/metadata-css/geometry-1_dev/html/DOMMatrix-001.htm.ini`; see `tests/wpt/README.md` for more information).

**Comment by wenderen** [comment]
can i work on this?

**Comment by jdm** [comment]
Yep!

**Comment by frewsxcv** [comment]
Still working on this @wenderen?

**Comment by KiChjang** [comment]
@wenderen Let us know if you want to pick this up again. In the meantime, I'm unassigning this issue.

**Comment by peterjoel** [comment]
I would like to pick this one up please.

**Comment by frewsxcv** [comment]
Go for it! Let us know if you run into any issues

**Comment by peterjoel** [comment]
@frewsxcv I'm sure I will! 
For starters, are there existing matrix operations, used internally by servo, that can be bound to?

**Comment by jdm** [comment]
The euclid library has matrix implementations: http://doc.servo.org/servo/euclid/struct.Matrix2D.html and http://doc.servo.org/servo/euclid/struct.Matrix4.html . The DOMQuads PR looks like a valid reference.

**Comment by peterjoel** [comment]
@jdm Is it a problem that euclid matrices use `f32`, while the webidl generated traits use `f64`?

**Comment by jdm** [comment]
Probably!

**Comment by peterjoel** [comment]
Perhaps it would be better to make generic versions of the euclid objects and then make the existing ones aliases for those?

**Comment by jdm** [comment]
Seems reasonable to me!

**Comment by peterjoel** [comment]
I get an error when implementing a method that uses a Float32Array or Float64Array: "Can't handle SpiderMonkey interface arguments yet".  This is coming from [here](https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py#L787). 

Is it something I can fix easily, or should I just skip these for now?

**Comment by KiChjang** [comment]
We currently don't support any sort of `ArrayBuffer`s with our codegen. Tracking issue is #5014. Skip those for now.

**Comment by peterjoel** [comment]
I have a query about the existing test:
https://github.com/servo/servo/blob/master/tests/wpt/css-tests/geometry-1_dev/html/DOMMatrix-001.htm#L138

The test is failing because I don't throw a TypeError here. But this looks to be correct according to the spec. A 6 element sequence as the argument should represent a 2D array, and there is no mention of throwing errors based on the values themselves:
https://drafts.fxtf.org/geometry/#dom-dommatrixreadonly-dommatrixreadonly-numbersequence

**Comment by Ms2ger** [comment]
It seems to test that you can't construct a DOMMatrixReadOnly at all, which seems wrong. Feel free to ignore those tests.

**Comment by stjepang** [comment]
Any updates on this issue? :)
In case it got forgotten or abandoned, I'd be willing to implement it.

**Comment by jdm** [comment]
Nope, @peterjoel is actively working on it. There are just a bunch of moving pieces in other repositories which have ended up being necessary.

**Comment by jdm** [comment]
@peterjoel How's this progressing? Anything we can help with?

**Comment by peterjoel** [comment]
@jdm I've been busy with my job. But the feature is mostly done. Outstanding is just tests and the CSS-style initialisers. There is a 3-day weekend coming up this weekend, and I should get the PR in.
