### ISSUE TITLE
Update our implementation of DOMTokenList and DOMSettableTokenList

### ISSUE THREAD

**Issue by nox** [servo/servo#8511]
The specification changed:

https://github.com/whatwg/dom/issues/28
https://github.com/whatwg/dom/issues/91
https://github.com/whatwg/dom/issues/105

**Comment by nox** [comment]
https://github.com/whatwg/dom/commit/63a030265fc3dac400a99f729fd5874490ae335c

**Comment by Ms2ger** [comment]
This might involve writing or updating tests.

**Comment by frewsxcv** [comment]
Relevant: https://github.com/w3c/web-platform-tests/issues/2323
