### ISSUE TITLE
Avoid the term "task".

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8512]
We use it in about a thousand places, but it would be better to use "thread" instead.

(Don't try to do this all at once.)

**Comment by wenderen** [comment]
#9201 @frewsxcv done

**Comment by frewsxcv** [comment]
This seems to be mostly done after #9201?

**Comment by KiChjang** [comment]
Yeah, I'd say it's fixed by #9201. We can open up inidividual PRs for the ones that it didn't catch.
