### ISSUE TITLE
Implement CSS animations/keyframes

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8541]
https://drafts.csswg.org/css-animations/

**Comment by dzbarsky** [comment]
It would be nice to do this on top of WebAnimations because retrofitting transition and animations later will be a lot of work

**Comment by larsbergstrom** [comment]
I believe that's the approach @birtles recommended based on his experiences in gecko (https://github.com/servo/servo/wiki/Meeting-2015-05-11#animations).

**Comment by jdm** [comment]
We support these.
