### ISSUE TITLE
text input: draw caret even if there's no text

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8543]
I think caret is only drawn if there's a text fragment.

**Comment by frewsxcv** [comment]
Just encountered this. Gif of the interaction:

![](https://cloud.githubusercontent.com/assets/416575/11518527/31148514-9860-11e5-8d38-74d8b8273316.gif)

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/7644

> The caret doesn't show up if there's no text present, because we don't create text runs in that case. This should be a followup.

**Comment by pcwalton** [comment]
Maybe just create a dummy scanned text fragment?

**Comment by paulrouget** [comment]
> Maybe just create a dummy scanned text fragment?

Where should this be done?

**Comment by paulrouget** [comment]
This works now.
