### ISSUE TITLE
Browser API: implement iframe.zoom()

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8547]
So I believe the right way to implement that is, from the iframe, send a constellation message with the subpage id, from constellation, get the scrip chan, send a zoom message, and in script_task.rs, handle the zoom message.

Then, I'm not sure when to perform the actual zooming. Should we append an event to the window and handle it `ScriptTask::handle_msgs`?

If so, could we imagine instead using the resize event (which uses the same path) and add an extra parameter for the zoom value?

/cc @glennw

**Comment by paulrouget** [comment]
https://github.com/paulrouget/mozBrowserAPI/blob/master/BrowserAPI.md#the-zoom-method

**Comment by mbrubeck** [comment]
This will also need new code in the compositor to set the zoom of an iframe.  Currently it only knows how to zoom the top-level window.

**Comment by paulrouget** [comment]
@mbrubeck any update on this?

**Comment by mbrubeck** [comment]
No, sorry. Unassigning myself for now, but I'll try to get back to this soon if someone else doesn't fix it in the meantime.

**Comment by mason-larobina** [comment]
Zooming the top-level window has unexpected results on my machine (though it could be a poor interaction with my window manager).

![2016-07-02-140011_3200x1800_scrot](https://cloud.githubusercontent.com/assets/98076/16541834/9d5bf1f8-405d-11e6-96d0-1d2f840a6b00.png)

**Comment by jdm** [comment]
@mason-larobina Could you file a new issue for that? This one is tracking a DOM API for use in browser.html that has not been implemented yet.

**Comment by mason-larobina** [comment]
Done https://github.com/servo/servo/issues/12187 

(Just to check, did you mean a servo or bhtml issue?)

**Comment by jdm** [comment]
I meant servo. Thanks!

**Comment by paulrouget** [comment]
We shipped the first alpha of browserhtml we are planning to move away from the Browser API. Closing.
