### ISSUE TITLE
Make Node::remove_child more idiomatic

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8554]
https://github.com/servo/servo/blob/db94fda10e3351c96a0df61099d2fdfa481cc62b/components/script/dom/node.rs#L302-L310

Instead of writing:

```rust
        let prev_sibling = child.GetPreviousSibling();
        match prev_sibling {
            None => {
                self.first_child.set(child.next_sibling.get().r());
            }
            Some(ref prev_sibling) => {
                prev_sibling.next_sibling.set(child.next_sibling.get().r());
            }
        }
```

it could probably be written something like

```rust
child.GetPreviousSibling()
     .map_or(self.first_child, |ref prev_sibling| prev_sibling.next_sibling)
     .set(child.next_sibling.get().r());
```

which reduces a little bit of the duplicated `set` logic.

This could also be applied to the following `match` block

**Comment by Ms2ger** [comment]
I doubt this will work; you'd at least need `&self.first_child` and `&prev_sibling.next_sibling`.

**Comment by frewsxcv** [comment]
In retrospect, I think you're right
