### ISSUE TITLE
Make Node::is_parent_of more idiomatic

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8555]
https://github.com/servo/servo/blob/db94fda10e3351c96a0df61099d2fdfa481cc62b/components/script/dom/node.rs#L601-L606

Could use `Option::map_or`

https://doc.rust-lang.org/nightly/core/option/enum.Option.html#method.map_or

**Comment by frewsxcv** [comment]
Same thing here

https://github.com/servo/servo/blob/20d26853e145e275695463662b6cee334cd27085/components/style/stylesheets.rs#L150

**Comment by nerith** [comment]
I'd like to work on this.

**Comment by frewsxcv** [comment]
Go for it!
