### ISSUE TITLE
the text-shadow property shouldn't be in the Effects struct

### ISSUE THREAD

**Issue by heycam** [servo/servo#8556]
The Effects style struct contains non-inherited properties, except for text-shadow, which is inherited. I guess it should move somewhere else.

**Comment by wenderen** [comment]
[image-rendering](https://developer.mozilla.org/en/docs/Web/CSS/image-rendering) is also inherited

**Comment by nox** [comment]
Is this still true?

**Comment by nox** [comment]
Nope, it's in `inherited_text` now. Closing.
