### ISSUE TITLE
Move OpenSSL Android build to the target directory

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#8568]
Right now, OpenSSL is downloaded and built for Android in the support/android directory instead of in the target/arm-linux-androideabi/FLAVOR directory. See:
https://github.com/servo/servo/blob/master/support/android/openssl.makefile

This task would involve having our python code that calls the makefile set or pass in the proper target directory location:
https://github.com/servo/servo/blob/d16ba51b4722a84f69976ca8679af672495248c8/python/servo/build_commands.py#L219

Then, the new makefile would instead download the .tar.gz file into that location, unpack it there, and also build it there.

For this issue, you will need to be able to build for Android: https://github.com/servo/servo/wiki/Building-for-Android

**Comment by mskrzypkows** [comment]
I'd like to take this task.

**Comment by larsbergstrom** [comment]
Fantastic, @mskrzypkows! If you have any questions, please feel free to ask here or on irc.mozilla.org in the #servo channel.

**Comment by mskrzypkows** [comment]
Please check above draft and tell if it's good direction.

**Comment by mskrzypkows** [comment]
@larsbergstrom One question: when I want to build openssl in servo/target/arm-linux-androideabi/debug I have to move there openssl.makefile and openssl.sh files. I don't know if we'll build debug or release. Should I create two copy of these files or copy them while building from servo/support/android to proper directory (debug or release)?

**Comment by larsbergstrom** [comment]
@mskrzypkows I think that the easiest path is to copy the openssl.makefile and openssl.sh files in the Python code. So, before the `make` call here: 
https://github.com/servo/servo/blob/d16ba51b4722a84f69976ca8679af672495248c8/python/servo/build_commands.py#L223

Instead:
1) If the file does not already exist in the target location or is different, copy the two files from support/android to a folder such as target/arm-linux-androideabi/FLAVOR/openssl-native. That target path should be available from the python code.
2) Instead of doing the build in the support/android directory, perform it in that openssl-native directory made above.

Hope this helps!

**Comment by mskrzypkows** [comment]
Updated. I copy openssl.makefile and openssl.sh to target/arm-linux-androideabi/FLAVOR/native/openssl. Is it OK? I assumed that it's better to use existing 'native' directory.
