### ISSUE TITLE
Allow different test expectations in wpt based on rendering backend.

### ISSUE THREAD

**Issue by glennw** [servo/servo#8574]
cc @jgraham 

(We only briefly discussed this - so I'm just entering this so we have a place to discuss implementation details).

**Comment by jgraham** [comment]
This is a wptrunner bug rather than a servo bug, but I think I can just implement this either way; all the machinery already exists but I want to make a small refactor so that servo-only options don't apply to gecko and so on.

**Comment by mrobinson** [comment]
Going to close this bug since the old rendering backend doesn't exist any longer.
