### ISSUE TITLE
`Touch::new` should maybe take some kind of `Point2D` arguments.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8577]
Or `TypedPoint2D`?

**Comment by jinwooahn** [comment]
Could you explain more detail? Why new arguments are needed?

**Comment by faineance** [comment]
Is this up for grabs?

**Comment by Ms2ger** [comment]
The function currently takes pairs of x/y arguments; it would be nicer to use a struct to encapsulate that. However, I'm not sure what the best type is. @mbrubeck, do you have thoughts?

**Comment by nox** [comment]
That sounds gratuitous, let's just keep the fields separate like they are specified.
