### ISSUE TITLE
TLS connections should disallow handshakes which use small DH groups

### ISSUE THREAD

**Issue by alex** [servo/servo#8581]
See for example:
- https://dh480.badssl.com/
- https://dh512.badssl.com/

which should be blocked. (https://dh1024.badssl.com/ should also be blocked eventually IMO, but is not yet in many major browsers)

**Comment by nox** [comment]
The first two are now blocked, but https://dh1024.badssl.com/ isn't. Assigning to @avadacatavra to decide.

**Comment by avadacatavra** [comment]
@nox I think we should block it

**Comment by avadacatavra** [comment]
Once I've blocked it, I think it would be good to make a more usable error message ("obsolete/insecure cipher--handshake failed" maybe). Currently, when we block these, the only message displayed is 'the handshake failed'

**Comment by avadacatavra** [comment]
Also, how do we feel about switching to the modern cipher list (less backward compatibility) in https://wiki.mozilla.org/Security/Server_Side_TLS?

Major differences:
* Sha1 removed (yay!)
* DHE removed (slower than ECDHE)

Based on my recent-ish cipherscan [results](https://pastebin.com/aCazxpAq), it looks like we shouldn't take too much of a hit on web compat

**Comment by alex** [comment]
Modern also drops non-AEAD suites, which probably breaks substantial portions of the web :-(

+1 on removing DHE though, Chrome has already done this, and because the TLS handshake doesn't negotiate FFDH-params, there's probably no way to bump the minimum DH without also breaking stuff.

**Comment by nox** [comment]
"HTTPS state" in the Fetch spec can be either "modern" or "deprecated", so we can have two lists, one  for the ones we prefer, and one for the ones which are bad but which we need to support for webcompat.

**Comment by nox** [comment]
See #16357.

**Comment by metajack** [comment]
@avadacatavra if you want to switch modern on, you'll probably need to provide data on how bad the breakage is so we can make a decision. Feel free to remove DHE though, since it seems like other browsers are doing that.

**Comment by avadacatavra** [comment]
@metajack @nox in #16535 i changed our default to modern with a switch for intermediate (which does keep DHE). does that sound like it will solve this?

**Comment by Darkspirit** [comment]
This can be closed. Support for DHE has been removed with #22243.
