### ISSUE TITLE
Prototype JSClasses may not need the slot they reserve.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8588]
CC @jdm @nox.

```
static PrototypeClass: JSClass = JSClass {
    flags: (1 & JSCLASS_RESERVED_SLOTS_MASK) << JSCLASS_RESERVED_SLOTS_SHIFT, //JSCLASS_HAS_RESERVED_SLOTS(1)
```

while I don't think we use that slot for anything. <https://mxr.mozilla.org/mozilla-central/source/dom/bindings/JSSlots.h#32> suggests one may be used for something to do with unforgeable.

**Comment by jdm** [comment]
What about the use of DOM_PROTO_INSTANCE_CLASS_SLOT in do_create_interface_objects?

**Comment by Ms2ger** [comment]
Aha. That should be documented somewhere, and we should use readable constants.

**Comment by jdm** [comment]
That being said, it's not clear to me that we ever read the value from that slot.

**Comment by nox** [comment]
Will look into it in my Unforgeable branch.
