### ISSUE TITLE
Split ScriptMsg messages only sent from paint tasks into a separate PaintMsg enum

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#8592]
#8530  introduced different message types that the constellation can receive. Currently there are two message types: `CompositorMsg` and `ScriptMsg`. We would like to add a new message type called `PaintMsg`, which will be used exclusively for paint messages sent by `paint_task.rs`.

Code: `components/msg/constellation_msg.rs`, `components/compositing/constellation.rs`, `components/gfx/paint_task.rs`

**Comment by wldcordeiro** [comment]
I'd be interested in trying to tackle this issue.

**Comment by KiChjang** [comment]
Sorry, but a PR has been submitted by @g-k.

**Comment by Wafflespeanut** [comment]
fixed by #8598
