### ISSUE TITLE
'loop..match' should be 'while let'

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8593]
[This](https://github.com/servo/servo/blob/d11442bdcccf4002cdb84e85fe726130047a2b07/components/style/values.rs#L527-L540) should become something like `while let Ok(token) = input.next() { .. }`

**Comment by r0e** [comment]
I'd like to give this a go.

**Comment by frewsxcv** [comment]
Go for it!

**Comment by Wafflespeanut** [comment]
We could also utilize clippy here. One of its lints detect such `while let` rewritable `loop ... match`es :)

**Comment by jdm** [comment]
See also `./mach clippy`.

**Comment by r0e** [comment]
For clarification, you'd like me to use `./mach clippy` to find all instances of the above issue and submit them as a single patch?

**Comment by jdm** [comment]
@r0e If you're up for it, sure :)

**Comment by r0e** [comment]
I'm down. :)

**Comment by frewsxcv** [comment]
Fixed in #8597
