### ISSUE TITLE
*** glibc detected *** ./servo: double free or corruption (!prev): 0x0000000002851920 ***

### ISSUE THREAD

**Issue by mulander** [servo/servo#860]
./servo ../src/test/html/about-mozilla.html - fails to find glx display
optirun ./servo ../src/test/html/about-mozilla.html - works correctly 
optirun ./servo http://google.com - crash with double free
optirun ./servo http://news.ycombinator.com - crash with double free

Terminal transcript including all the above interactions:
https://gist.github.com/mulander/6428843

**Comment by mbrubeck** [comment]
This was fixed long ago but we forgot to close this issue.  Sorry!
