### ISSUE TITLE
Remove 'Node::is_anchor_element'

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8631]
https://github.com/servo/servo/blob/c19b01c2f4acdccf140e65145c8915acc6fbe59c/components/script/dom/node.rs#L437-L440

**Comment by frewsxcv** [comment]
Could callers of this just use `node.is::<HTMLAnchorElement>()` instead? If so, we can remove the question mark in the title and mark as E-Easy

**Comment by eefriedman** [comment]
In the context where it's used, I think we want to handle anything which is semantically an anchor... which probably includes HTML `<area>` and SVG `<a>`.  That said, we can just ignore that for now; the abstraction isn't helping at the moment.

**Comment by rilut** [comment]
@eefriedman so, is this issue open?

**Comment by eefriedman** [comment]
Yes.

**Comment by rilut** [comment]
@eefriedman thanks!
