### ISSUE TITLE
Moderninzing the default UI/UX - Enhancement

### ISSUE THREAD

**Issue by dumindu** [servo/servo#8643]
Hi, 
From time to time, we saw revolutionary UI designs on IT world

2006
Looking Glass : https://www.youtube.com/watch?v=SIaNKB_eakM
2007
iPhone : https://www.youtube.com/watch?v=c_m2F_ph_uU
2008
Aurora Concept Browser : https://www.youtube.com/watch?v=FZ-zvx1QCcA
2010 
Rockmelt : https://www.youtube.com/watch?v=pCpLn12rQsA
Firefox Panorama : https://www.youtube.com/watch?v=5r0TQJ-gGi0
2011
Windows 8 : https://www.youtube.com/watch?v=KyAj_H_SCvs
Gnome3 : https://afaikblog.wordpress.com/2011/01/19/gnome3-org-is-live/

I might missed some best products, However at early days Mozilla tried to reinvent the browser UIs via Aurora, Panorama, Prospector, Webian Shell and etc. But now a days we didn't see any revolutionary UIs from Mozilla. 

Before launching Servo officially, why we can't build a revolutionary user experience for Servo, something modernize, responsive like on Aurora?

**Comment by Manishearth** [comment]
Servo isn't a browser, it's a browser engine -- UI is out of scope at the moment.
