### ISSUE TITLE
Servo presentation doesn't render webfonts anymore

### ISSUE THREAD

**Issue by tschneidereit** [servo/servo#8657]
Specifically, [this presentation](https://c508726212d59fb7e25519c4c09d78a43ecae845.googledrive.com/secure/AH8CU7HG3Gzrfs8mfwA9x7x6RSLD225KZTwAFjPZaWcJR2TDXpBlF55oxw_epr6h_g0lJDwPfl3K6KODirrUp9V73e5r0hqMeRY3FZ5pMyZRuTch8U6XCRKojP575o8MkbnIvXv9-dvcCh982B4Y6m8dSZTZNxBHKlTsguCyp0vBX4TXlZM327L-fxqFU7x7soAb1UkWC-el-mwQl-Zy9EHC-GBArTJF6kSeysxKFKcMSG3KSVKy7KOjSBYEvcwtJ4hI8LqIekJpN0g5K8-gkZz2k7m8U9QRxR_WyV8eq27myDZxwVUIi3q5_2IwEqC85A3CzwrKupY_6JynmXW_Y3khybiLivjrbfPXpsEIgT5ezNySgzfk_2UvNU4_WtFuSwHCn7ypEMXq-mPHpmTMMcIVO7pzNNRDHBZ1cYWjG7EcxPZFPLJdNsEWHspOhn9SiuNmVWQ5frio6Eidi_q5WiIdsqmZSxtFiMgllbJH0Q8DVJtvWJ4epbwwtoY0Iru798dnl9Up4NgMD61wIMAtvgvLrjkrWPOIb4cAH3Nf-bi9ZZtl88QbCCM8v8Dy-7DBe9uFMYBxNNVe/host/0B7rVe7KlPrhHMGdUT3pGU2NZamc/servo.html). The fonts are rendered briefly right after startup, but then vanish immediately, not to return. It seems prudent to fix this before fixing #8654.

Bisection says this is a regression caused by #6815.

**Comment by tschneidereit** [comment]
The link worked for a moment, but now I get a 404. I [uploaded the presentation to my people.mozilla.org account](http://people.mozilla.org/~tschneidereit/servo/talk-lca2015/) for the time being.

**Comment by tschneidereit** [comment]
Oh, one further note: reverting #6815 makes things better, but not quite right: it does show text, but not reliably in all tiles. These two screenshots are examples of rendering caused by mouse moves: http://imgur.com/a/jwajd.

**Comment by atouchet** [comment]
Those links no longer work.

**Comment by jdm** [comment]
Closing since the test cases can't be checked any more.
