### ISSUE TITLE
After navigating to a new page in an iframe, previous page is not destroyed/frozen

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8673]
I believe this happens only with documents in iframes.

index.html:
```html
<iframe src="a.html"></iframe>
```

a.html:
```html
<script>
  setInterval(() => {
    console.log("a");
  }, 1000);

</script>

<a href="./b.html">b</a>
```

b.html:
```
<h1>b</h1>
```

Running `index.html`, logs are printed in the console. Then navigating to `b.html`, `a.html` is not displayed anymore, but its JS code is still running.

**Comment by Ms2ger** [comment]
#8426

**Comment by paulrouget** [comment]
This happens because the pipelines in iframes are never frozen.
