### ISSUE TITLE
Consider using the parentRuntime argument to JS_NewRuntime.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8677]
Per https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_Reference/JS_NewRuntime, this should reduce memory bloat.

**Comment by tschneidereit** [comment]
We should definitely do this: there aren't any downsides, and it reduces memory usage and initialization time. The latter because the self-hosting compartment is shared instead of initialized for each thread, so it avoids parsing and executing 170k of JS.

**Comment by jdm** [comment]
We do this now.
