### ISSUE TITLE
Move error handling out of the network loader

### ISSUE THREAD

**Issue by jdm** [servo/servo#8678]
There are a couple steps here:
* replace the free-form string in the `Result` that network listeners receive with the LoadError type from `http_loader.rs`
* propagate the errors from `load_for_consumer` to the network receiver instead of sending a string
* convert the other network loaders to use the LoadError values
* move the SSL validation error handling into the HTML parser network listener (`servohtmlparser.rs`)
* make `headers_available` take a `Result<Metadata, LoadError>` value to reflect the possibility of early errors (such as SSL validation failure)

**Comment by jdm** [comment]
This will both fix problems like `<script src="http://some_invalid_ssl.com">` causing our error page to be interpreted as JS, and allow us to handle DNS failure properly in the HTML parser network listener (while other consumers will just see an early error).

**Comment by Wafflespeanut** [comment]
I'll take this :)
