### ISSUE TITLE
Build fails on Debian unstable

### ISSUE THREAD

**Issue by tmatth** [servo/servo#8680]
Since SSLv3_\* has been removed in Debian:
`/home/tristan/servo/.cargo/registry/src/github.com-0a35038f75765ae4/openssl-0.6.7/src/ssl/mod.rs:153: error: undefined reference to 'SSLv3_method'`
`collect2: error: ld returned 1 exit status`
`error: aborting due to previous error`
`Could not compile servo.`

This might need to be fixed upstream.
Also see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804603
Refs #7888

**Comment by frewsxcv** [comment]
As of https://github.com/servo/servo/pull/8637, we have SSLv2 and SSLv3 disabled.

[It looks like there are cargo features on rust-openssl](https://github.com/sfackler/rust-openssl/blob/6bb3d8f1b5827ff27216d4219e08467b2461c071/openssl/src/ssl/mod.rs#L137-L140) that would allow us to stop relying on these methods. Maybe we should disable those features?

/cc @alex

**Comment by alex** [comment]
Disabling the `sslv3` in `openssl-sys` by default seems reasonable to me.

**Comment by Darkspirit** [comment]
This can be closed. Build does not fail on Debian Testing.
