### ISSUE TITLE
Warn on the presence of &String

### ISSUE THREAD

**Issue by jdm** [servo/servo#8681]
Like we warn on code like `: &Vec<`, we should also warn for `: &String`, since it has no benefit over using `&str`. This can be tested using `./mach test-tidy`.

Code: python/tidy.py

**Comment by frewsxcv** [comment]
Why not use rust-clippy for things like this?

**Comment by jdm** [comment]
Because we can catch this easily in travis.

**Comment by jmr0** [comment]
I can give this a shot, if that's alright. Should we refactor any existing instances of &String as well?

**Comment by jdm** [comment]
Yes please!
