### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by iqualfragile** [servo/servo#8683]
commit 5e7306bf1965988551cafe6a27baab13eb927bbe
url https://i.imgur.com/snbejvV.gifv

What i did
call servo http://google.de
enter reddit\n
click first result (reddit)
click most trending post
enter a backspace, thereby returning to reddit
click the same post again

what i expected:
either servo showing the website with embedded webm or an error about not supporting webm, possibly with some layout issues

what happened instead:
on the second time visiting i got a crash:
<blockquote>
ERROR:js::rust: Error at https://www.redditmedia.com/ads/display/300x250#{"keywords": "-reddit.com,loggedout", "origin": "https://www.reddit.com"}:6:0: window.parent.frames[frame] is undefined

ERROR:js::rust: Error at https://www.redditmedia.com/ads/display/300x250#{"keywords": "-reddit.com,loggedout", "origin": "https://www.reddit.com"}:6:0: window.parent.frames[frame] is undefined

ERROR:js::rust: Error at https://www.redditmedia.com/ads/display/300x250#{"keywords": "-reddit.com,loggedout", "origin": "https://www.reddit.com"}:6:0: window.parent.frames[frame] is undefined

ERROR:js::rust: Error at https://www.redditmedia.com/ads/display/300x250#{"keywords": "-reddit.com,loggedout", "origin": "https://www.reddit.com"}:6:0: window.parent.frames[frame] is undefined

ERROR:js::rust: Error at https://www.redditmedia.com/ads/display/300x250#{"keywords": "-reddit.com,loggedout", "origin": "https://www.reddit.com"}:6:0: window.parent.frames[frame] is undefined

thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }' panicked at 'assertion failed: self.suspended_since.get().is_none()', /build/servo/components/script/timers.rs:342
thread 'Constellation' panicked at 'thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', src/libcore/result.rs:736
unable to find pipeline - this is a bug', src/libcore/option.rs:333
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', src/libcore/result.rs:736
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(6), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }', src/libcore/result.rs:736
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(6), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:thread 'LayoutWorker worker 2/3' panicked at 'thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
736
736
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
736
736
736
736
736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }', src/libcore/result.rs:736
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(4) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', src/libcore/result.rs:736
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(4) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread '<main>' panicked at 'Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }).', /build/servo/components/compositing/compositor.rs:687
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /build/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:166
stack backtrace:
thread 'thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }thread '' panicked at '' panicked at 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(3) }called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError' panicked at '', ', called `Result::unwrap()` on an `Err` value: RecvErrorsrc/libcore/result.rssrc/libcore/result.rs', ::src/libcore/result.rs736736
:
736
   1:     0x561c5ec06090 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x561c5ec08de5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x561c5ec08831 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
thread 'LayoutWorker worker 1/3  ' panicked at ' called `Result::unwrap()` on an `Err` value: RecvError4', : src/libcore/result.rs : 736 
 0x561c5ebf1a08 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x561c5e95c80f - sys_common::unwind::begin_unwind::begin_unwind::h482723599667555474
thread '  PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) } ' panicked at '6called `Result::unwrap()` on an `Err` value: RecvError: ',  src/libcore/result.rs : 736 
0x561c5e95c910 - platform::linux::surface::_<impl>::drop::hf661bf1588160e62xfc
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
   7:     0x561c5d499127 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28369::h3e4c778c7de593ce
   8:     0x561c5d499275 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28381thread '::hcd042c4fde3574d6PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError',   src/libcore/result.rs :9736: 
    0x561c5d499004 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28369::h3e4c778c7de593ce
  10:     0x561c5d499275 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28381::hcd042c4fde3574d6
  11:     0x561c5d499004 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28369::h3e4c778c7de593ce
  12:     0x561c5d49b0c1 - compositing..compositor..IOCompositor<app..window..Window>::drop.28747::h9821c741db1dd828
  13:     0x561c5d48981f - main::h5d36c985f91f4eb6Laa
  14:     0x561c5ec08574 - sys_common::unwind::try::try_fn::h10604132475359592391
  15:   thread ' PaintWorker ' panicked at '0xcalled `Result::unwrap()` on an `Err` value: RecvError561c5ec055c8',  - src/libcore/result.rs__rust_try:
736
  16:     0x561c5ec0820f - thread 'rtLayoutWorker worker 1/3::' panicked at 'lang_startcalled `Result::unwrap()` on an `Err` value: RecvError::', hd74bfb7a606308914ixsrc/libcore/result.rs
:736
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rsthread ':PaintWorker736' panicked at '
called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
  17:     0x7f4db6ce360f - __libc_start_main
  18:     0x561c5d47d078 - thread '_start
PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(3) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
  19:                0x0 - <unknown>
thread panicked while panicking. aborting.thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
Ungültiger Maschinenbefehl (Speicherabzug geschrieben)
</blockquote>

**Comment by frewsxcv** [comment]
Might be a duplicate of #8461

**Comment by iqualfragile** [comment]
#8461 has a better backtrace and is the same issue, closing.
