### ISSUE TITLE
Remove warnings on using deprecated std::thread::sleep_ms

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#8694]
When building servo now, there is a lot of warning messages in the following form:
```
/home/keith/Workspace/servo/ports/glutin/window.rs:301:13: 301:34 warning: use of deprecated item: replaced by `std::thread::sleep`, #[warn(deprecated)] on by default
/home/keith/Workspace/servo/ports/glutin/window.rs:301         use std::thread::sleep_ms;
                                                                   ^~~~~~~~~~~~~~~~~~~~~
```
We'll have to update our definitions to use the new `std::thread::sleep`, which takes a `Duration` struct instead of a `u32`.

Code: `components/profile/mem.rs`, `components/profile/time.rs`, `components/webdriver_server/lib.rs`, `components/devtools/actors/timeline.rs`, `components/compositing/scrolling.rs`, `ports/glutin/window.rs`
Documentation: https://doc.rust-lang.org/nightly/std/thread/fn.sleep.html, https://doc.rust-lang.org/nightly/std/time/struct.Duration.html

**Comment by GuillaumeGomez** [comment]
I'll take this one.

**Comment by jsanders** [comment]
@GuillaumeGomez: D'oh, must have started this right before you commented – was just coming here to comment after taking a look. I have a PR almost ready to submit.

**Comment by GuillaumeGomez** [comment]
Arf. Well, then, it's all yours. Next time please comment before starting.

**Comment by jsanders** [comment]
Yeah, real sorry about that, just thought I'd look into it a bit, and got carried away before coming back.
