### ISSUE TITLE
Remove warnings on using deprecated std::slice::ref_slice

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#8695]
Recent versions of Rust have moved the `std::slice` module out of the standard library and instead put them into a new crate called [`ref_slice`](https://crates.io/crates/ref_slice). As a consequence, when building servo now, we get a lot of warning messages of the following form:
```
/home/keith/Workspace/servo/components/script/dom/node.rs:64:5: 64:26 warning: use of deprecated item: unclear whether belongs in libstd, #[warn(deprecated)] on by default
/home/keith/Workspace/servo/components/script/dom/node.rs:64 use std::slice::ref_slice;
                                                                 ^~~~~~~~~~~~~~~~~~~~~
```

Code: `components/script/dom/node.rs`, `components/script/dom/websocket.rs`
Documentation/crate-to-use: https://github.com/steveklabnik/ref_slice

**Comment by Jayflux** [comment]
@KiChjang I will try and take this

**Comment by jdm** [comment]
Great!
