### ISSUE TITLE
Remove warnings on using deprecated std::thread::park_timeout_ms

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#8704]
We still have compiler warnings about using a deprecated feature. The new `std::thread::park_timeout` function receives a `Duration` struct instead of `u32`.

Code: `components/compositing/timer_scheduler.rs`
Documentation: https://doc.rust-lang.org/nightly/std/thread/fn.park_timeout.html, https://doc.rust-lang.org/nightly/std/time/struct.Duration.html

cc @GuillaumeGomez if you're interested in tackling this ;)

**Comment by GuillaumeGomez** [comment]
Absolutely. Thanks ! :)

**Comment by KiChjang** [comment]
#8705 seems to have fixed this issue, closing.

**Comment by jsanders** [comment]
@KiChjang / @GuillaumeGomez: Sorry, came across this deprecation while working on #8705 and thought it was similar enough to wrap into the same PR.
