### ISSUE TITLE
Remove compiler warnings on attributes gating stable features

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#8706]
When building servo using the latest rust version, we have compiler warnings about unnecessary `#![feature]` attributes because they have since been stabilized in rust 1.6.

Code: `components/profile/lib.rs` (slice_splits), `components/net/lib.rs` (path_ext)

**Comment by GuillaumeGomez** [comment]
I take this one !

**Comment by Wafflespeanut** [comment]
@GuillaumeGomez Let this be here for newcomers. Why don't you go for #8691, if that's okay? :)
