### ISSUE TITLE
"unused attribute" warnings from Serialize/Deserialize derivation.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8709]

**Comment by GuillaumeGomez** [comment]
I take this one too.

**Comment by Ms2ger** [comment]
Do you know how to fix them correctly? I don't.

**Comment by GuillaumeGomez** [comment]
The only issue here is because rustc considers these attributes as unused. So we can just add a macro which derive them to make rustc happy. But if you have something else in mind...

**Comment by Ms2ger** [comment]
I'm pretty sure they actually are used, or at least part of the public APIs of these libraries, so the warning is probably caused by a bug in serde.
