### ISSUE TITLE
Make OnErrorEventHandlerNonNull return `any` instead of `boolean`

### ISSUE THREAD

**Issue by jdm** [servo/servo#8710]
I think the specification must have changed since this was first added to Servo: https://html.spec.whatwg.org/multipage/webappapis.html#onerroreventhandler

Code: components/script/dom/webidls/EventHandler.webidl

**Comment by echochamber** [comment]
@jdm Mind if I give this one a shot?

**Comment by Wafflespeanut** [comment]
@echochamber Go ahead! :)
