### ISSUE TITLE
Support for CSS :active selector

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8719]
https://html.spec.whatwg.org/multipage/#concept-selector-active

https://drafts.csswg.org/selectors/#the-active-pseudo

**Comment by sjmelia** [comment]
This is referenced in PR #11726, the active state already exists for the selector.

So either the element itself or perhaps the "Activatable" trait could be extended to deal with the "formal activation state" and call element.set_active_state.

In document.handle_mouse_event; I could hook mousedown and mouseup (as done for a click, which hooks to element.authentic_click_activation) to trigger this.

Does this sound about right? I'm not sure whether it's correct to consider activation as synonymous with mousedown.

**Comment by jdm** [comment]
cc @Manishearth for the previous comment.
