### ISSUE TITLE
Intermittent failure on /_mozilla/css/text_transform_capitalize_a.html

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8726]
```
Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/text_transform_capitalize_a.html
  └   → /_mozilla/css/text_transform_capitalize_a.html 0c9bebebd539178423c0db83fb2c83cd8800c90d
/_mozilla/css/text_transform_capitalize_ref.html 76b83bf90ad78d16f9d9fdc21ab369e61754fca1
Testing 0c9bebebd539178423c0db83fb2c83cd8800c90d == 76b83bf90ad78d16f9d9fdc21ab369e61754fca1
```

First seen in #8722.

**Comment by jdm** [comment]
<img width="692" alt="screen shot 2015-11-28 at 9 46 59 pm" src="https://cloud.githubusercontent.com/assets/27658/11455097/9b1dc3f6-9619-11e5-86f9-da65c4ae97c2.png">

**Comment by echochamber** [comment]
Its possible I will be out of my depth, but I'd like to give this one a shot.

**Comment by KiChjang** [comment]
It's yours!

**Comment by echochamber** [comment]
I think I am out of my depth here. I built servo with --dev, and have run that specific test 1000 times to see if I could get it to fail but so far it keeps passing. After digging around a little I think there are too many pieces I don't understand to tackle this bug. I'll give another one a shot. @KiChjang can you remove the assigned tag from this? Thanks!

**Comment by jdm** [comment]
Hasn't been seen in months. Closing.
