### ISSUE TITLE
Cleanup the repeated code in tidy!

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#8733]
I'm specifically interested in cleaning up the regex matching lines in `check_rust` function. For example, [these lines](https://github.com/servo/servo/blob/6e7de62b38a04e614c60e864c8d100bf3e72304f/python/tidy.py#L301-L313) are doing the same thing. Only the regex expression, the yielding message and the condition varies. So, if we make use of some inner functions for the job, we'd have a series of lines that do more or less the same thing, but then (I think) the code would be a lot more compact and readable. Note that this is just my approach. If you're thinking of any other way to improve tidy's code, I'd be very happy :)

Code: `python/tidy.py`

**Comment by Mylainos** [comment]
I would like to take this one !

**Comment by Wafflespeanut** [comment]
Great! :)

**Comment by Mylainos** [comment]
I think add a fonction which return the error and then yield this error if it's not None isn't efficient for clean up the code.
```python
def if_match(regex, error_msg, line, idx):
    match = re.search(regex, line)
    if match:
        return (idx + 1, error_msg)

...

    tmp = if_match(r"\)->", "missing space before ->", line, idx)
    if tmp != None:
        yield tmp
```
Any suggestion ? I don't know how to do it differently.

**Comment by srinivasreddy** [comment]
I think you can use this regex with out going for another function.
```
>>> matched = re.match(r"(?P<start_space>\s+)?\)->(?P<last_space>\s+)?", ")->")
>>> matched.groupdict()
{'start_space': None, 'last_space': None}
```

**Comment by Wafflespeanut** [comment]
Alright, let's drop the idea of having functions, and change the plan (because some cleanup's already going on at #8750).

So, we've got unwanted nested `if`s, like... 
``` python
if blah:
    if not bleh:
        return thing
```

which could be grouped into,
``` python
if blah and not bleh:
    return thing
```

Simlarly, there are some unwanted variable bindings, like `match`. It does something like,

``` python
match  = re.search(...)
if match:
    yield ...
```
In this case, we don't need this binding at all! It could just check the search and yield whatever it wants to yield. Basically, if any line of code that has an unnecessary form which doesn't aid readability, then it can be modified. Both of these are examples of such cases.

**Comment by dsprenkels** [comment]
I would like to take a look at this. :)

**Comment by jdm** [comment]
@dsprenkels Go for it!
