### ISSUE TITLE
Ensure that tidy follows the same procedure for sorting

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#8734]
#8692 introduced a new way to sort the `crate` declarations (thanks to @GuillaumeGomez). The current procedure for sorting `mod` and `use` declarations [makes use of the `sorted` function](https://github.com/servo/servo/blob/6e7de62b38a04e614c60e864c8d100bf3e72304f/python/tidy.py#L345). This means that every time tidy encounters a declaration, it's appended to the collected list of declarations and sorts them again. I think that's inefficient (and may consume time, given the abundance of files in Servo). So, let's modify both the procedures to stick to the one followed for crate declarations :)

Code: `python/tidy.py`

**Comment by GuillaumeGomez** [comment]
We already talked about it, so I'll take it of course ! :)
