### ISSUE TITLE
Range code uses Vec<Root<T>>

### ISSUE THREAD

**Issue by jdm** [servo/servo#8737]
This certainly used to be something that wasn't allowed back in the stack-scanning days because the vector elements weren't on the stack. Is this now valid with the new design for `Root`, or should we lint more strongly for this and rewrite the code?

http://mxr.mozilla.org/servo/search?string=vec%3Croot

cc @michaelwu @nox @Ms2ger

**Comment by nox** [comment]
This can probably return a RootedVec through `RootedVec::with_destination_address`.

**Comment by jdm** [comment]
If this turns out to be unsafe, we need to update the bindings generation to disallow `sequence<Interface>` return types until we have a solution.

**Comment by nox** [comment]
Err no it can't. We could pass a `&mut RootedVec`. Using Root here seems to be safe, but not very efficient, I guess.

**Comment by dzbarsky** [comment]
That code should probably return an iterator instead of calling collect, but I didn't know how to make the lifetimes compile when I wrote it.

**Comment by michaelwu** [comment]
An iterator seems more appropriate here, for performance/memory reasons.

**Comment by jdm** [comment]
The code isn't unsafe, so this is fine.
