### ISSUE TITLE
Mimic other browser vendors when passing unexpected null values to WebGL methods

### ISSUE THREAD

**Issue by emilio** [servo/servo#8753]
Other browser engines generate an `INVALID_VALUE` error when, for example, a `null` shader argument is passed to `getShaderInfoLog`. Similar calls are `getProgramParameter`, `getParameter`, ...

**Comment by Ms2ger** [comment]
Should find where the spec says this; if it doesn't say that, we should get it fixed.

**Comment by emilio** [comment]
Yeah, the problem is the spec is unclearish with this, because of the huge amount of things that delegates to the GLES2 spec.

A lot of GLES2 functions have a line like:

> ## Errors
>  * `GL_INVALID_VALUE` is generated if [var_name] is not an object generated by OpenGL.

Other browsers (and Khronos, given the test suite) interpret (correctly IMHO) passing null to a WebGL function as a case of this.

**Comment by emilio** [comment]
Dropping this link here in order to read it more deeply when I'm in front of a computer, since this null == value not generated by gl thing is mentioned here:

https://www.khronos.org/webgl/public-mailing-list/archives/1204/msg00214.php

**Comment by nox** [comment]
Latest specs don't take `WebGLShader?` anymore, but `WebGLShader`.
