### ISSUE TITLE
vh and vw units are not recalculated after window resize

### ISSUE THREAD

**Issue by gordonbrander** [servo/servo#8754]
`vh` and `vw` units are not recalculated after a window resize. Here's a [minimal test case](https://gordonbrander.github.io/servo-testcases/resize-vw-vh/).

<img width="1099" alt="screen shot 2015-11-30 at 11 49 40" src="https://cloud.githubusercontent.com/assets/58421/11482649/d96b6600-9758-11e5-9578-2f7e6edece5a.png">

- This issue is present in both normal and "browser.html" modes.
- This issue is **not** present with percentage-based sizes ([test case](https://gordonbrander.github.io/servo-testcases/resize-percent/))

**Comment by gordonbrander** [comment]
As might be expected, this is also affecting the positioning of child elements ([testcase](https://gordonbrander.github.io/servo-testcases/resize-vw-vh/centered-child.html)).

<img width="656" alt="screen shot 2015-11-30 at 12 40 23" src="https://cloud.githubusercontent.com/assets/58421/11483831/97e0c2d2-975f-11e5-883b-21988d60a449.png">

**Comment by mbrubeck** [comment]
Currently [Stylist::set_device][1] sets its `is_device_dirty` flag on resize if any stylesheet contains an `@media` query that is affected by the resize.  We could fix this by also checking  if any stylesheet contains a rule with a `vh` or `vw` value, and setting the same dirty flag.

This `is_device_dirty` flag causes all stylesheets to be re-added to the document and all nodes to be dirtied by the layout task.  We could possibly do something smarter to dirty only the nodes affected by the rule containing the `vh` or `vw` value.

[1]: https://github.com/servo/servo/blob/b4906aa008325963348b6cc13bbcf8d2a4c9d694/components/style/selector_matching.rs#L246-L248

**Comment by mbrubeck** [comment]
Alternately we could change the types like computed::LengthOrPercentageOrAuto preserve the viewport units, so they can be converted to an absolute length at layout time (like percentages are) rather than at cascade time (like they are currently).

**Comment by SimonSapin** [comment]
I’d rather not do that. It would add significant complexity everywhere in the layout code: when accessing any length from the style system, any piece of layout code would need to also have access to the viewport size and call something to resolve to an absolute length.

**Comment by mbrubeck** [comment]
> It would add significant complexity everywhere in the layout code: when accessing any length from the style system, any piece of layout code would need to also have access to the viewport size…

Layout code can access the viewport size pretty easily because it's part of the LayoutContext, which we already thread through all of the layout traversals.

> …and call something to resolve to an absolute length.

We need to do this anyway because of percentage lengths.

**Comment by SimonSapin** [comment]
Not every `<length>` can be a `<percentage>` (for example border width) but every length can have viewport units.

This also deviates from the spec, and although I haven’t managed to come up with a case where the difference is observable I don’t know if they don’t exist. (The computed value is what’s inherited, and any property can take the value `inherit`).
