### ISSUE TITLE
Add extensive cookie tests to wpt

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#8756]
Our cookie code was rather broken. https://github.com/servo/servo/pull/8752 fixed it and added some unit tests, but there should be wpt tests for cookie setting behavior as well.

I'm envisioning something which uses a custom python server (see XMLHttpRequest/resources or cors/resources in wpt for examples of these) that sets various cookies based on its parameters, and write tests around that.

These tests would set cookies (via the server using `Set-Cookie`, not via `document.cookie`) with various paths, and ensure that they're sent back to the server later when on a matching path. There should also be false positive tests.

cc @jgraham @Wafflespeanut

**Comment by Ms2ger** [comment]
Relevant: https://github.com/w3c/web-platform-tests/pull/2385

**Comment by askalski** [comment]
this sounds interesting to me. Where I can read about wpt tests?

**Comment by jdm** [comment]
http://testthewebforward.org/docs/writing-tests.html and http://testthewebforward.org/docs/testharness.html would be relevant.

**Comment by jdm** [comment]
As would http://mxr.mozilla.org/servo/source/tests/wpt/README.md .

**Comment by askalski** [comment]
Hi, I attempted to work on this, and got blocked very fast: I copied "cors" directory to new one "set-cookie", added "[set-cookie]\n  skip:false" to include.ini, and tried to run
```
$./mach test-wpt set-cookie
```
and got 
```
Running tests in web-platform-tests

Ran 0 tests finished in 0.0 seconds.
  • 0 ran as expected. 0 tests skipped.
```
as if I tried
```
$./mach test-wpt something_undefined
```

**Comment by jdm** [comment]
The tests also need to be present in MANIFEST.json to be run.

**Comment by askalski** [comment]
ok, then I will come back with some initial tests, and we'll talk whether I am competent to do it all.

**Comment by askalski** [comment]
I feel I can get assigned to this, after writing tests to 9185

**Comment by Manishearth** [comment]
Cool, let me, jdm, or Wafflespeanut know if you need help!

**Comment by g-k** [comment]
Can I pick this up?

**Comment by Manishearth** [comment]
Sure! Let us know if you need help.

**Comment by g-k** [comment]
Should these be more like the [secure cookie tests](https://github.com/w3c/web-platform-tests/pull/2385) or only in python like the [functional cookie tests](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/tools/wptserve/tests/functional/test_cookies.py)?

**Comment by jdm** [comment]
The secure cookie tests.

**Comment by KiChjang** [comment]
@g-k Are you still working on this?
