### ISSUE TITLE
hit test issue: 2 absolute divs create an opaque region for mouse events

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8759]
```html
<iframe src="http://paulrouget.com" mozbrowser="true" style="display: block; width: 500px; height: 500px; border: 0"></iframe>
<div style="position: absolute; top: 200px; height: 2px; width: 500px; background: #0F0;"></div>
<div style="position: absolute; top: 400px; height: 2px; width: 500px; background: #0F0;"></div>
```

![screenflow](https://cloud.githubusercontent.com/assets/373579/11490979/e1ce8d88-97dd-11e5-93b6-ffbb1199f880.gif)

**Comment by mbrubeck** [comment]
The two positioned divs are layerized into the same layer, so `IOCompositor::find_topmost_layer_at_point` correctly returns this layer.  However, we don't actually want the topmost layer; we want the topmost element. If the point is in a region of the layer that contains no element, the hit test should fail.  I'm not sure yet how to implement this without a round trip to the script task...  cc @pcwalton and @mrobinson

**Comment by mbrubeck** [comment]
Note that this is only a problem when the layer is on top of an iframe, because that causes the compositor to send the mouse event message to the wrong document.  Perhaps if this happens, the script task could detect it and forward the message to the child document.
