### ISSUE TITLE
Some CSS transitions test intermittently fail/crash

### ISSUE THREAD

**Issue by gsnedders** [servo/servo#8764]
These will be disabled even after #8565.

```
tests/wpt/css-tests/css-transitions-1_dev/html/properties-value-001.htm
tests/wpt/css-tests/css-transitions-1_dev/html/properties-value-inherit-002.htm
tests/wpt/css-tests/css-transitions-1_dev/html/properties-value-inherit-003.htm
tests/wpt/css-tests/css-transitions-1_dev/html/transitions-animatable-properties-01.htm
```

I believe all subtests for these randomly fail at varying frequencies, occasionally crashing the browser.

**Comment by mrobinson** [comment]
I think that these tests are no longer disabled and the remaining intermittent tests are tracked by individual bugs. If that's the case, I suppose this issue can be closed?

**Comment by jdm** [comment]
Yep, that sounds reasonable.

**Comment by mrobinson** [comment]
Thanks!
