### ISSUE TITLE
browser.html takes 100% cpu

### ISSUE THREAD

**Issue by metajack** [servo/servo#8765]
Follow instructions here:
https://github.com/mozilla/browser.html/tree/perspective-ui#running-in-servo

I tested on OS X, but I'm not sure if this is platform specific or not. You don't need to do anything bug load the blank ui. It consumes all the cycles as soon as servo starts and seems to never stop.

**Comment by metajack** [comment]
cc @glennw @paulrouget

**Comment by metajack** [comment]
After some investigation from @glennw this doesn't seem to happen on linux nor does it seem related to requestionAnimationFrame.

I suspect Mac OS X event handling :(

**Comment by metajack** [comment]
Handing this to @pcwalton since he's on a mac.

**Comment by paulrouget** [comment]
No issue here. Tested with and without webrender.

**Comment by paulrouget** [comment]
> nor does it seem related to requestionAnimationFrame.

How did you rule out RAF? Could it be related to https://github.com/servo/servo/issues/7782 ?

**Comment by metajack** [comment]
I added logging (a suggestion from @glennw) to tick_animations_for_pipeline and ti was only called 5 times on the initial load and never again while I let it sit idle eating my CPU.

**Comment by pcwalton** [comment]
Can't reproduce this.

**Comment by atouchet** [comment]
Is this issue still relevant?

**Comment by jdm** [comment]
Unreproducible.
