### ISSUE TITLE
Keyboard events & input elements ignore OS keyboard layout 

### ISSUE THREAD

**Issue by Gozala** [servo/servo#8767]
I use Dvorak keyboard layout on OSX 10.11.2 and typing into input element seems to type as if I was typing in QUERTY. Also all keyboard events seem to ignore keyboard layout.

**Comment by metajack** [comment]
That's odd. You'd think the OS would translate the events before sending them. Maybe this is a bug in Glutin?

**Comment by jdm** [comment]
Duplicate of #4144.
