### ISSUE TITLE
Multiple spaces don't get rendered in input fields

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8772]
Caret issue:  #8543

Steps to reproduce:

1. go to a text field
2. press space five times
3. press a letter
4. notice that *visually* it looks like only one space was pressed

![untitled](https://cloud.githubusercontent.com/assets/416575/11518999/4d3ed70e-9864-11e5-85de-cac6cae20d3e.gif)

**Comment by frewsxcv** [comment]
test case:

```
<input value="foo     bar">
```

```
<input value="foo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bar">
```

**Comment by jdm** [comment]
I bet this is the layout code doing its whitespace collapsing on the generated text.

**Comment by TheKK** [comment]
Hi, can I take this one :)

**Comment by KiChjang** [comment]
Yes, please do :)

**Comment by frewsxcv** [comment]
@TheKK: I think @Manishearth already has this completed in https://github.com/servo/servo/pull/8983, though it hasn't merged yet

**Comment by TheKK** [comment]
Yup, this was fixed. I'll find something else I can work on.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/8983
