### ISSUE TITLE
<input> with no specified value or size has incorrect width

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8773]
```
$ cat /tmp/hi.html
<input>
```

Chrome (and Firefox):

![screen shot 2015-12-01 at 8 07 30 pm](https://cloud.githubusercontent.com/assets/416575/11519333/56b1992c-9867-11e5-8afe-790955025f3d.png)

Servo:

<img width="635" alt="screen shot 2015-12-01 at 8 07 36 pm" src="https://cloud.githubusercontent.com/assets/416575/11519335/5e6efeca-9867-11e5-81a8-848a85996926.png">

[Relevant section of spec](https://html.spec.whatwg.org/multipage/#the-input-element-as-a-text-entry-widget:the-input-element-5)

**Comment by frewsxcv** [comment]
On a similar note:

```
$ cat /tmp/hi.html
<input size=50>
```

Chrome (and Firefox):

![screen shot 2015-12-01 at 8 14 18 pm](https://cloud.githubusercontent.com/assets/416575/11519439/36e2e3ac-9868-11e5-95d1-bbe4fa547dcd.png)

Servo:

<img width="642" alt="screen shot 2015-12-01 at 8 14 01 pm" src="https://cloud.githubusercontent.com/assets/416575/11519442/3a18fb24-9868-11e5-924e-035ade75c04c.png">

**Comment by frewsxcv** [comment]
Possibly related to  #4378

**Comment by SimonSapin** [comment]
The `size` attribute does have an effect in:

```html
<input type=text size=50>
```

So I’m guessing that where we’re implementing this (emphasis added):

https://html.spec.whatwg.org/multipage/rendering.html#the-input-element-as-a-text-entry-widget:the-input-element
> **If an input element whose type attribute is in one of the above states** has a size attribute, and parsing that attribute's value using the rules for parsing non-negative integers doesn't generate an error, then the user agent is expected to use the attribute as a presentational hint for the 'width' property on the element, with the value obtained from applying the converting a character width to pixels algorithm to the value of the attribute.

… we’re not accounting for the default state of the `type` attribute:

https://html.spec.whatwg.org/multipage/forms.html#attr-input-type
> The missing value default is the Text state.

**Comment by SimonSapin** [comment]
Relevant code is `synthesize_presentational_hints_for_legacy_attributes` in `components/script/dom/element.rs`

**Comment by TheKK** [comment]
Hi!
This issue looks like a nice place for me to start, can I take this one?

**Comment by Ms2ger** [comment]
It's yours! Look for "nonsense" in `components/script/dom/element.rs`.

**Comment by TheKK** [comment]
Here my modification TheKK@d03ad31. I compare the rendering result with Firefox and has no difference. Could you help me checking the commit, thanks.

**Comment by SimonSapin** [comment]
Hi @TheKK. Thanks for your contribution! Please open a pull request so that we can use the usual tooling for code review.
