### ISSUE TITLE
Remove the cx/sender arguments to Trusted::new()?

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8779]
It seems like we could get those from the reflector with `global_root_from_reflector`.

**Comment by jdm** [comment]
If we can do this, we should. Creating Trusted values is higher-effort than I'd prefer right now.

**Comment by Ms2ger** [comment]
Turns out @michaelwu already removed the dependency on the `JSContext` during the smup. (Would have been nice if we'd filed a followup about it then…)

Anyway, this involves removing the `_cx` and `script_chan` arguments from `Trusted::new()` in `components/script/dom/bindings/refcounted.rs`. The `script_chan.clone()` can be replaced by `global_root_from_reflector(ptr).script_chan()`.

**Comment by KiChjang** [comment]
I was confused why `Trusted::new()` needed a `JSContext` argument since `_cx` was never used within the function itself.

**Comment by askobara** [comment]
Someone works on this task? If not then I'll try

**Comment by askobara** [comment]
But if I understand correctly after 8d90034 removing the `script_chan` from arguments no need anymore?

**Comment by jdm** [comment]
Yes, that may be the case, so go ahead and focus on the cx argument for now.
