### ISSUE TITLE
build.servo.org DNS entry missing

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#8782]
@edunham Can you please add back a DNS entry for build.servo.org to 96.126.125.232?

Right now, we have to get homu / the waterfall / etc. from manual IP hacking :-)
http://96.126.125.232/homu/queue/servo

Thanks!

**Comment by edunham** [comment]
Added A record. Sorry about that!

**Comment by edunham** [comment]
And build.servo.org now resolves.
