### ISSUE TITLE
Use the type system to ensure that methods are not called on the wrong threads

### ISSUE THREAD

**Issue by DemiMarie** [servo/servo#8789]
Servo currently uses `debug_assert!` in many places where the thread must be in a certain state, but dynamic checking would be too slow.  This should be avoided by passing a zero-sized type around as compile-time proof that the code is in the correct state.

**Comment by nox** [comment]
The only way to make these assertions fail is by sending things like `Trusted<T>` to a different thread and converting that back to `Root<T>` on the wrong thread. The proof token would need to be sent too so it wouldn't change anything. Closing.
