### ISSUE TITLE
Replace ZERO_RECT with Rect::zero and ZERO_POINT with Point2D::zero

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8792]
http://doc.servo.org/servo/util/geometry/static.ZERO_RECT.html

⬇️

http://doc.servo.org/servo/euclid/struct.Rect.html#method.zero

--------

http://doc.servo.org/servo/util/geometry/static.ZERO_POINT.html

⬇️

http://doc.servo.org/euclid/point/struct.Point2D.html#method.zero

**Comment by rilut** [comment]
May I?
