### ISSUE TITLE
Make Blob store an Arc<Vec<u8>>

### ISSUE THREAD

**Issue by jdm** [servo/servo#8801]
The point of Blob values is that they're immutable buffers, and sometimes they're even slices of immutable buffers, and they're often used as sources of data that will be sent between threads internally. We should support this properly by making the underlying buffer threadsafe, allowing us to pass around references to it rather than cloning it. This will allow us to:
* remove the `read_out_buffer` method, and rename `clone_bytes` to `get_bytes`
* make Blob slices (ie. the result of calling `Blob::Slice`) share the original buffer, by storing the offset and length of the slice in the new Blob object

Code: components/script/dom/blob.rs

**Comment by craftytrickster** [comment]
I'd like to take this one.

**Comment by jdm** [comment]
Go for it!

**Comment by asajeffrey** [comment]
Should this be Arc<Vec<u8>> or Arc<[u8]>?

**Comment by jdm** [comment]
I'm not sure how to create the `Arc<[u8]>` value from the various Blob constructors, so I'm going to go with `Arc<Vec<u8>>` for the purposes of this issue.
