### ISSUE TITLE
PartialEq for DOM objects

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8804]
There's a number of places that do things like
```rust
impl PartialEq for Attr {
    fn eq(&self, other: &Attr) -> bool {
        self as *const Attr == &*other
    }
}
```

It would be nice to have that handled centrally.

**Comment by nox** [comment]
Would you be ok with just generating the impl in codegen?

**Comment by Ms2ger** [comment]
Sure.

**Comment by GuillaumeGomez** [comment]
I'd like to take it.
