### ISSUE TITLE
Treat 'undefined' passed to an optional argument as "missing"

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8813]
* [Failing test](https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/dom/documents/dom-tree-accessors/document.title-07.html.ini)
* https://people.mozilla.org/~jorendorff/es6-draft.html#sec-tostring
* https://dom.spec.whatwg.org/#dom-domimplementation-createhtmldocument

Servo:

```
> document.implementation.createHTMLDocument(undefined).title
"undefined"
```

Firefox:

```
> document.implementation.createHTMLDocument(undefined).title
""
```

Chrome:

```
> document.implementation.createHTMLDocument(undefined).title
""
```

Is this a spec issue?

**Comment by eefriedman** [comment]
The spec is perfectly clear; the interface is "[NewObject] Document createHTMLDocument(optional DOMString title);", and the Web IDL spec says that if `undefined` is specified as an argument, it gets converted to the string `"undefined"`.  Servo's behavior matches the spec.

It's possible the spec needs to be changed to reflect reality.

**Comment by frewsxcv** [comment]
https://github.com/whatwg/dom/issues/124

**Comment by Ms2ger** [comment]
@eefriedman is incorrect. Passing `undefined` to an `optional` argument is the same as not passing it at all. This behaviour is hidden in <https://heycam.github.io/webidl/#dfn-overload-resolution-algorithm> (currently step 10.4).

**Comment by Ms2ger** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=882541

**Comment by frewsxcv** [comment]
Related to #6558

**Comment by eefriedman** [comment]
Oops, I was looking at the wrong version of the WebIDL specification.  Sorry about that.

**Comment by frewsxcv** [comment]
Consider this example:

1. Navigate to http://meow.com
2. Enter `location.replace(undefined)` in the JS console

In Firefox, Chrome, and Safari, this redirects to `http://meow.com/undefined`. According to the spec, should `location.replace(undefined)` be treated identical to `location.replace()`? If so, this seems like it goes against what the norm already do, and I imagine having the major vendors transition could cause quite a bit of pain for people.

**Comment by frewsxcv** [comment]
Nevermind. I missed the part about "optional" argument. I think that clears things up for me.
