### ISSUE TITLE
Support this website : html5test.com 

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/servo#8823]
This website could be very useful for know what servo currently support in the html5 spec and if it support good. 
The website : https://html5test.com/
The source code : 
https://github.com/NielsLeenheer/html5test
Thanks :)

**Comment by Ms2ger** [comment]
html5test has never been a good indicator of what we should prioritize, if it is even correct, so I would take any suggestions based on it with a grain of salt.

**Comment by LifeIsStrange** [comment]
Ok thanks !
