### ISSUE TITLE
Move CompositorMsg enum into compositing crate

### ISSUE THREAD

**Issue by jdm** [servo/servo#8832]
It's a message type for messages sent between the compositor and the constellation, which both live in `components/compositing`. There should be no need for it to be declared in the `msg` crate. We should try moving it!

Code: `components/msg/constellation_msg.rs`, `components/compositing/lib.rs`

**Comment by vwvww** [comment]
I would like to take this one.

**Comment by KiChjang** [comment]
You got it!
