### ISSUE TITLE
Move ScriptMsg enum into script_traits crate

### ISSUE THREAD

**Issue by jdm** [servo/servo#8833]
This message type is only sent between script threads and the constellation, which are respectively defined in the `script/` crate and the `compositing/` crate. We should be able to move the type into `script_traits/lib.rs`, which will allow for further simplification of our compilation graph in the future.

Code: `components/msg/constellation_msg.rs`, `components/script_traits/lib.rs`, `components/compositing/constellation.rs`

**Comment by cnaj** [comment]
This seems to be straightforward, I'll give it a go in the evening (CET). Do you want the type to be exported as `script_traits::ScriptMsg`?

**Comment by Wafflespeanut** [comment]
Yep!
