### ISSUE TITLE
Move ScriptToCompositorMsg enum to script_traits

### ISSUE THREAD

**Issue by jdm** [servo/servo#8835]
`ScriptToCompositorMsg` is a message type that is only sent between script threads and the compositor, so it's a good candidate to move to the `script_traits` crate.

Code: `components/script_traits/lib.rs`, `components/msg/compositor_msg.rs`, and other files listed in http://mxr.mozilla.org/servo/search?string=scripttocompositormsg

**Comment by jdm** [comment]
We could move the `EventResult` enum along with it.

**Comment by vwvww** [comment]
I was working on this issue, but ScriptToCompositorMsg enum and EventResult enum had no doc comment, resulting build error. Does it needed to be skipped by some way, or need to write doc comment? I don't know what description has to be on doc comment.

**Comment by jdm** [comment]
I suggest `/// Messages sent from the script thread to the compositor` and `/// Whether a DOM event was prevented by web content` respectively.

**Comment by KiChjang** [comment]
Fixed by #9027.
