### ISSUE TITLE
Move LayerKind and ScrollPolicy enums to gfx_traits

### ISSUE THREAD

**Issue by jdm** [servo/servo#8836]
These are only used by code in `layout/`, `gfx/`, and `compositing/`, so they're good candidates to move out of the grab-bag `msg/` crate.

Code: `components/msg/compositor_msg.rs`, `components/gfx_traits/lib.rs`, and other files in http://mxr.mozilla.org/servo/search?string=scrollpolicy and http://mxr.mozilla.org/servo/search?string=layerkind

**Comment by nerith** [comment]
I'm working on this.
