### ISSUE TITLE
Write unit test for reporting CSS errors 

### ISSUE THREAD

**Issue by jdm** [servo/servo#8842]
The interface in #8210 allows us to create custom instances of CSS parse error reporters. We should write a test in `tests/unit/style/stylesheets.rs` that tries to parse invalid CSS and have a custom reporter that asserts the errors that are reported.

Code: `tests/unit/style/stylesheets.rs`, http://doc.servo.org/style_traits/trait.ParseErrorReporter.html

**Comment by iszak** [comment]
I have started to implement in the branch iszak/servo@f9533109aae1c3cf5066c00816285d88dd9447a0 do we want to test that the error reporter is picking up CSS errors? or that the error reporter is returning valid values? or simply that the error reporter is invalid. If we want to test CSS errors, what's the convention? multiple tests per different type of error.

This is my first rust pull request, so any feedback is welcome.

**Comment by jdm** [comment]
@iszak I think we should test that two separate errors are reported in one piece of CSS containing two errors, and that the error that is reported matches the expected line/column/etc. We can do that in a single test, I think.

**Comment by iszak** [comment]
@jdm I'm not sure that's possible without having index based conditions inside the report_error method. Even if I were able to store the reported errors on the structure via say an Arc, the error reporter is cloned upon pass to `Stylesheet::from_str` so I would not have access to the error_reporter properties. Any suggestions on how else to approach this?

**Comment by jdm** [comment]
The error reporter can store a vector of errors reported (inside `Arc<Mutex<>>`) that we compare against the expected values once parsing is complete. Does that make sense?

**Comment by iszak** [comment]
@jdm I tried that but because the error reporter is cloned inside Stylesheet::from_str() I won't have the same error reporter used to check for errors after invocation, it gives me an error saying it's moved.

**Comment by jdm** [comment]
@iszak Could you push some code so I can understand the problem better? It should be possible to clone the Arc value to avoid that.

**Comment by iszak** [comment]
@jdm I believe this is ready to create a PR https://github.com/servo/servo/compare/master...iszak:issue-8842 any feedback before I create it?
