### ISSUE TITLE
Separate script and layout messages that are sent to the constellation

### ISSUE THREAD

**Issue by jdm** [servo/servo#8843]
They're both mixed in the ScriptMsg enum defined in `components/msg/constellation_msg.rs`. We should:
* make two separate enums (ScriptMsg and LayoutMsg)
* update the use of `ScriptMsg` in `components/layout/`
* add a new channel in `Constellation` (like the script, paint, and compositor ones) for the new `LayoutMsg`
* use the new channel in the event loop for `Constellation`
* move `LayoutMsg` from `msg/` to `layout_traits/lib.rs`

**Comment by jdm** [comment]
This will be similar to #8598, which is a good model.

**Comment by jkachmar** [comment]
I'd like to work on this, if it's still available.

**Comment by KiChjang** [comment]
Alright!

**Comment by KiChjang** [comment]
Fixed in #8958.
