### ISSUE TITLE
Move WorkerId type to devtools_traits

### ISSUE THREAD

**Issue by jdm** [servo/servo#8846]
It's defined in `components/msg/constellation_msg.rs` but only used by `components/script/` and `components/devtools`. We can do better!

Code: `components/msg/constellation_msg.rs`, `components/devtools_traits/lib.rs`

**Comment by KiChjang** [comment]
I'm guessing that `WorkerId` should be moved to `components/devtools_traits/lib.rs` instead?

**Comment by jdm** [comment]
I think that's what I wrote, yes.

**Comment by fstr** [comment]
@jdm I'd like to take this one
