### ISSUE TITLE
CodegenRust.py docstrings/comments are wrong

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8847]
https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py

There are many docstrings that refer to C++ code generation, even though we're generating Rust

**Comment by frewsxcv** [comment]
In an attempt to make this more concrete, at the very least `s/C++/Rust/g` for the most part

**Comment by apopiak** [comment]
So it's a simple find and replace?

**Comment by nox** [comment]
I'm pretty sure all C++ references are gone by now.
