### ISSUE TITLE
Build release mode on Travis?

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8859]
At the time of writing on Travis:
- 29 minutes to `./mach build -d`
- 36 minutes to `./mach build -r` (https://github.com/servo/servo/pull/8858)

As we venture into running tests on Travis (https://github.com/servo/servo/issues/8856 and maybe in the future WPT tests), it might be worth it to switch to building with `-r`

**Comment by metajack** [comment]
The main benefit of the debug build (aside from better debug info in crashes and faster compile times) is that we get integer overflow checking.

These numbers seem suspicious though. My personal build times differ by a much larger factor.

**Comment by larsbergstrom** [comment]
Why not both, using the matrix? :-)
