### ISSUE TITLE
Overload constructor for DOMPoint WebIDL

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#8864]
It is **not** as simple as adding `Constructor(optional DOMPointInit point)` to `DOMPoint.webidl`, as that would cause a compiler error in `WebIDL.py`, with the following message:

```
WebIDL.WebIDLError: error: Signatures with 0 arguments for method 'constructor' are not distinguishable, /home/keith/Workspace/servo/components/script/dom/webidls/DOMPoint.webidl line 18:0
interface DOMPoint : DOMPointReadOnly {
^
/home/keith/Workspace/servo/components/script/dom/webidls/DOMPoint.webidl line 18:0          
interface DOMPoint : DOMPointReadOnly {
^
```

We will need to figure out how to either turn off this check just for this overloaded constructor, or think of a more generalized way of handling overloaded constructors.

Spec: http://www.w3.org/TR/geometry-1/#dom-dompoint
Code: `components/script/dom/webidls/DOMPoint.webidl`, `components/script/dom/bindings/codegen/CodegenRust.py`, `components/script/dom/bindings/codegen/parser/WebIDL.py`
Test: `tests/wpt/css-tests/geometry-1_dev/html/DOMPoint-001.htm`

Blocks #8822.

**Comment by Ms2ger** [comment]
Also, this overload has been removed from the ED: https://drafts.fxtf.org/geometry/#DOMPoint

**Comment by nox** [comment]
This is dead.
