### ISSUE TITLE
manifest_changed.sh is slow

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8878]
On Travis, it takes ~250s. It's probably going to be hard to improve, but we should look into it.

**Comment by Ms2ger** [comment]
@Manishearth is going to move it out of the main travis build

**Comment by edunham** [comment]
@Manishearth any update on this? Looks like it's still in the Travis matrix, but only took 37.54s on the latest build (https://travis-ci.org/servo/servo/jobs/121502799#L1430)

**Comment by jdm** [comment]
It doesn't sound like it's slow anymore, so I'm inclined to leave it as is :) It's saved us numerous times by running as part of the TravisCI checks.

**Comment by edunham** [comment]
@Ms2ger do you think this issue is currently resolved?

**Comment by Ms2ger** [comment]
Sure
