### ISSUE TITLE
embedding: shared library is no longer linkable

### ISSUE THREAD

**Issue by zmike** [servo/servo#8883]
When attempting now (95e6b1d101ca1a1019b8fea1a13a5ef37430901f):

./libcef.so: undefined reference to `CreateARGBImageEncoder()'
./libcef.so: undefined reference to`gluCheckExtension'

@larsbergstrom @alexcrichton 

I did some grep work and it looks like these are be coming from skia.

**Comment by zmike** [comment]
Broken again:

./libcef.so: undefined reference to `MemProfiler::SampleTenured(void*, unsigned int)'
./libcef.so: undefined reference to `JS::CallbackTracer::contextName() const'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::invisibleToDebugger() const'
./libcef.so: undefined reference to `JS::StringInfo::sizeOfLiveGCThings() const'
./libcef.so: undefined reference to `JSPropertySpec::isSelfHosted() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::toggleExtraWarnings()'
./libcef.so: undefined reference to `JS::RuntimeSizes::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `JSPrincipals::dump()'
./libcef.so: undefined reference to `JS::CompartmentStats::sizeOfLiveGCThings() const'
./libcef.so: undefined reference to `js::ClassSpec::createPrototypeHook() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::setIon(bool)'
./libcef.so: undefined reference to `js::AutoStableStringChars::maybeGiveOwnershipToCaller()'
./libcef.so: undefined reference to `JS::CompartmentStats::addSizes(JS::CompartmentStats const&)'
./libcef.so: undefined reference to `JS::RuntimeOptions::toggleStrictMode()'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::addonIdOrNull() const'
./libcef.so: undefined reference to `JSTracer::isTenuringTracer() const'
./libcef.so: undefined reference to `JS::Value::isSymbol() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::setDumpStackOnDebuggeeWouldRun(bool)'
./libcef.so: undefined reference to `JS::StringInfo::addToTabSizes(JS::TabSizes*) const'
./libcef.so: undefined reference to `JS::ObjectOpResult::fail(unsigned int)'
./libcef.so: undefined reference to `JS::RuntimeOptions::wasm() const'
./libcef.so: undefined reference to `js::ContextFriendFields::get(JSContext*)'
./libcef.so: undefined reference to `JS::Value::isGCThing() const'
./libcef.so: undefined reference to `JS::PropertyDescriptor::trace(JS::PropertyDescriptor*, JSTracer*)'
./libcef.so: undefined reference to `mozilla::MallocAllocPolicy::checkSimulatedOOM() const'
./libcef.so: undefined reference to `JS::ObjectOpResult::checkStrict(JSContext*, JS::Handle<JSObject*>, JS::Handle<jsid>)'
./libcef.so: undefined reference to `js::ExpandoAndGeneration::offsetOfExpando()'
./libcef.so: undefined reference to `JS::Value::isInt32(int) const'
./libcef.so: undefined reference to `JS::ScriptSourceInfo::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `JS::ZoneStats::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `JS::UnusedGCThingSizes::addSizes(JS::UnusedGCThingSizes const&)'
./libcef.so: undefined reference to `JSJitMethodCallArgs::length() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::throwOnDebuggeeWouldRun() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::toggleBaseline()'
./libcef.so: undefined reference to `JS::AutoSaveExceptionState::drop()'
./libcef.so: undefined reference to `JS::CompartmentOptions::creationOptions() const'
./libcef.so: undefined reference to `js::shadow::Object::numFixedSlots() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::strictMode() const'
./libcef.so: undefined reference to `MemProfiler::SampleNative(void*, unsigned int)'
./libcef.so: undefined reference to `JS::GCCellPtr::asCell() const'
./libcef.so: undefined reference to `JS::Value::isDouble() const'
./libcef.so: undefined reference to `JS::shadow::Runtime::isHeapCollecting() const'
./libcef.so: undefined reference to `JS::ObjectOpResult::succeed()'
./libcef.so: undefined reference to `js::ExpandoAndGeneration::Unlink()'
./libcef.so: undefined reference to `JS::Value::setInt32(int)'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(JSString**)'
./libcef.so: undefined reference to `JSJitMethodCallArgs::hasDefined(unsigned int) const'
./libcef.so: undefined reference to `JS::shadow::Zone::barrierTracer()'
./libcef.so: undefined reference to `JS::shadow::Runtime::setGCStoreBufferPtr(js::gc::StoreBuffer*)'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::setCloneSingletons(bool)'
./libcef.so: undefined reference to `js::ClassSpec::shouldDefineConstructor() const'
./libcef.so: undefined reference to `JSErrorReport::linebufLength() const'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::setAddonId(JSAddonId*)'
./libcef.so: undefined reference to `JS::ZoneStats::sizeOfLiveGCThings() const'
./libcef.so: undefined reference to `JS::Value::toUnmarkedPtr() const'
./libcef.so: undefined reference to `JSJitInfo::returnType() const'
./libcef.so: undefined reference to `JS::Value::isTrue() const'
./libcef.so: undefined reference to `JS::ContextOptions::togglePrivateIsNSISupports()'
./libcef.so: undefined reference to `JS::Value::swap(JS::Value&)'
./libcef.so: undefined reference to `JS::Value::toPrivateUint32() const'
./libcef.so: undefined reference to `JS::ScriptSourceInfo::add(JS::ScriptSourceInfo const&)'
./libcef.so: undefined reference to `JS::ForOfIterator::valueIsIterable() const'
./libcef.so: undefined reference to `mozilla::MallocAllocPolicy::free_(void*)'
./libcef.so: undefined reference to `js::Class::nonProxyCallable() const'
./libcef.so: undefined reference to `MemProfiler::MarkTenuredStart(JSRuntime*)'
./libcef.so: undefined reference to `JS::ZoneStats::addSizes(JS::ZoneStats const&)'
./libcef.so: undefined reference to `js::ClassSpec::defined() const'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::Override::reset()'
./libcef.so: undefined reference to `JS::ContextOptions::setAutoJSAPIOwnsErrorReporting(bool)'
./libcef.so: undefined reference to `js::shadow::Object::slotRef(unsigned long) const'
./libcef.so: undefined reference to `JS::RuntimeOptions::asyncStack() const'
./libcef.so: undefined reference to `JS::UnusedGCThingSizes::totalSize() const'
./libcef.so: undefined reference to `js::ErrorReport::report()'
./libcef.so: undefined reference to `js::PerThreadDataFriendFields::getMainThread(JSRuntime const*)'
./libcef.so: undefined reference to `JS::RuntimeOptions::nativeRegExp() const'
./libcef.so: undefined reference to `JSTracer::isWeakMarkingTracer() const'
./libcef.so: undefined reference to `JS::Value::toObjectOrNull() const'
./libcef.so: undefined reference to `JSAutoByteString::length() const'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::getTrace() const'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::setVersion(JSVersion)'
./libcef.so: undefined reference to `JS::Value::toNumber() const'
./libcef.so: undefined reference to `JS::GCCellPtr::unsafeAsInteger() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::asmJS() const'
./libcef.so: undefined reference to `JS::ZoneStats::addToTabSizes(JS::TabSizes*) const'
./libcef.so: undefined reference to `JSErrorReport::linebuf() const'
./libcef.so: undefined reference to `mozilla::MallocAllocPolicy::reportAllocOverflow() const'
./libcef.so: undefined reference to `JS::CodeSizes::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `JS::TransitiveCompileOptions::introducerFilename() const'
./libcef.so: undefined reference to `JS::AutoAssertOnGC::VerifyIsSafeToGC(JSRuntime*)'
./libcef.so: undefined reference to `JS::Value::isFalse() const'
./libcef.so: undefined reference to `js::ClassSpec::dependent() const'
./libcef.so: undefined reference to `js::AutoStableStringChars::isTwoByte() const'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::setSingletonsAsValues()'
./libcef.so: undefined reference to `JS::RuntimeOptions::setAsmJS(bool)'
./libcef.so: undefined reference to `JS::Value::toBoolean() const'
./libcef.so: undefined reference to `sh::OutputHLSL::canWriteAsHLSLLiteral(TIntermTyped*)'
./libcef.so: undefined reference to `JSJitInfo::isTypedMethodJitInfo() const'
./libcef.so: undefined reference to `JS::ObjectOpResult::reportError(JSContext*, JS::Handle<JSObject*>, JS::Handle<jsid>)'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(JSScript**)'
./libcef.so: undefined reference to `js::ContextFriendFields::get(JSContext const*)'
./libcef.so: undefined reference to `JS::ContextOptions::autoJSAPIOwnsErrorReporting() const'
./libcef.so: undefined reference to `JSJitInfo::type() const'
./libcef.so: undefined reference to `js::ClassSpec::constructorProperties() const'
./libcef.so: undefined reference to `MemProfiler::SweepTenured(JSRuntime*)'
./libcef.so: undefined reference to `JS::shadow::Zone::asShadowZone(JS::Zone*)'
./libcef.so: undefined reference to `JSJitMethodCallArgs::rval() const'
./libcef.so: undefined reference to `js::ClassSpec::delegatedClassSpec() const'
./libcef.so: undefined reference to `JS::UnusedGCThingSizes::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `JS::Value::setBoolean(bool)'
./libcef.so: undefined reference to `JSPrincipals::setDebugToken(unsigned int)'
./libcef.so: undefined reference to `MemProfiler::enabled()'
./libcef.so: undefined reference to `JS::CompartmentOptions::behaviors() const'
./libcef.so: undefined reference to `js::CStringHasher::hash(char const*)'
./libcef.so: undefined reference to `JS::ContextOptions::dontReportUncaught() const'
./libcef.so: undefined reference to `JS::Value::setObject(JSObject&)'
./libcef.so: undefined reference to `js::PerThreadDataFriendFields::getMainThread(JSRuntime*)'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::zonePointer() const'
./libcef.so: undefined reference to `JS::ClassInfo::subtract(JS::ClassInfo const&)'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::setDisableLazyParsing(bool)'
./libcef.so: undefined reference to `js::ClassSpec::parentKey() const'
./libcef.so: undefined reference to `JS::ObjectOpResult::reportError(JSContext*, JS::Handle<JSObject*>)'
./libcef.so: undefined reference to `JSAutoStructuredCloneBuffer::data() const'
./libcef.so: undefined reference to `JS::ContextOptions::toggleAutoJSAPIOwnsErrorReporting()'
./libcef.so: undefined reference to `JS::HandleValueArray::empty()'
./libcef.so: undefined reference to `JS::RuntimeOptions::setWasm(bool)'
./libcef.so: undefined reference to `JS::Value::asRawBits() const'
./libcef.so: undefined reference to `JS::AutoGCRooter::trace(JSTracer*)'
./libcef.so: undefined reference to `JS::RuntimeOptions::extraWarnings() const'
./libcef.so: undefined reference to `JS::shadow::Runtime::asShadowRuntime(JSRuntime*)'
./libcef.so: undefined reference to `JSTracer::isCallbackTracer() const'
./libcef.so: undefined reference to `JSAutoStructuredCloneBuffer::nbytes() const'
./libcef.so: undefined reference to `JS::shadow::Zone::runtimeFromMainThread() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::baseline() const'
./libcef.so: undefined reference to `js::ClassSpec::finishInitHook() const'
./libcef.so: undefined reference to `MemProfiler::MarkTenured(void*)'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(JS::Symbol**)'
./libcef.so: undefined reference to `MemProfiler::MoveNurseryToTenured(void*, void*)'
./libcef.so: undefined reference to `JS::Value::isPrimitive() const'
./libcef.so: undefined reference to `JS::ClassInfo::addToTabSizes(JS::TabSizes*) const'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::zoneSpecifier() const'
./libcef.so: undefined reference to `js::ExpandoAndGeneration::offsetOfGeneration()'
./libcef.so: undefined reference to `JS::RuntimeOptions::toggleIon()'
./libcef.so: undefined reference to `js::SystemAllocPolicy::reportAllocOverflow() const'
./libcef.so: undefined reference to `JSJitMethodCallArgs::callee() const'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(js::jit::JitCode**)'
./libcef.so: undefined reference to `JS::RuntimeOptions::setMatchFlagArgument(bool)'
./libcef.so: undefined reference to `js::Class::isNative() const'
./libcef.so: undefined reference to `JS::HandleValueArray::subarray(JS::HandleValueArray const&, unsigned long, unsigned long)'
./libcef.so: undefined reference to `JS::shadow::Runtime::isHeapMajorCollecting() const'
./libcef.so: undefined reference to `JS::CompartmentStats::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `JS::Value::isObjectOrNull() const'
./libcef.so: undefined reference to `js::ClassSpec::prototypeProperties() const'
./libcef.so: undefined reference to `js::Class::emulatesUndefined() const'
./libcef.so: undefined reference to `JS::ObjectOpResult::checkStrictErrorOrWarning(JSContext*, JS::Handle<JSObject*>, JS::Handle<jsid>, bool)'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::Override::set(bool)'
./libcef.so: undefined reference to `JS::shadow::Zone::runtimeFromAnyThread() const'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(js::BaseShape**)'
./libcef.so: undefined reference to `js::AutoCTypesActivityCallback::DoEndCallback()'
./libcef.so: undefined reference to `JS::ClassInfo::sizeOfAllThings() const'
./libcef.so: undefined reference to `js::Class::offsetOfFlags()'
./libcef.so: undefined reference to `JS::Value::traceKind() const'
./libcef.so: undefined reference to `JS::SourceBufferHolder::length() const'
./libcef.so: undefined reference to `JSTracer::asCallbackTracer()'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::setMergeable(bool)'
./libcef.so: undefined reference to `JS::Value::setUnmarkedPtr(void*)'
./libcef.so: undefined reference to `JS::Value::toGCThing() const'
./libcef.so: undefined reference to `JS::SourceBufferHolder::take()'
./libcef.so: undefined reference to `JS::UnusedGCThingSizes::addToTabSizes(JS::TabSizes*) const'
./libcef.so: undefined reference to `JS::Value::setString(JSString*)'
./libcef.so: undefined reference to `JS::StringInfo::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `js::ClassSpec::delegated() const'
./libcef.so: undefined reference to `js::ElementAdder::getBehavior() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::setThrowOnDebuggeeWouldRun(bool)'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(js::ObjectGroup**)'
./libcef.so: undefined reference to `JS::RuntimeOptions::ion() const'
./libcef.so: undefined reference to `JS::Value::setNull()'
./libcef.so: undefined reference to `js::AutoStableStringChars::twoByteChars() const'
./libcef.so: undefined reference to `JS::ScriptSourceInfo::isNotable() const'
./libcef.so: undefined reference to `JS::shadow::Runtime::isHeapMinorCollecting() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::toggleWerror()'
./libcef.so: undefined reference to `MemProfiler::SampleNursery(void*, unsigned int)'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::mergeable() const'
./libcef.so: undefined reference to `js::Class::isDOMClass() const'
./libcef.so: undefined reference to `JS::ContextOptions::setPrivateIsNSISupports(bool)'
./libcef.so: undefined reference to `JS::Value::isMagic() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::dumpStackOnDebuggeeWouldRun() const'
./libcef.so: undefined reference to `JSFreeOp::runtime() const'
./libcef.so: undefined reference to `JS::ContextOptions::privateIsNSISupports() const'
./libcef.so: undefined reference to `js::ClassSpec::constructorFunctions() const'
./libcef.so: undefined reference to `JS::CallbackTracer::contextIndex() const'
./libcef.so: undefined reference to `JS::ObjectOpResult::failureCode() const'
./libcef.so: undefined reference to `JSJitMethodCallArgs::get(unsigned int) const'
./libcef.so: undefined reference to `js::ClassSpec::createConstructorHook() const'
./libcef.so: undefined reference to `JS::Value::payloadUIntPtr() const'
./libcef.so: undefined reference to `JS::Value::isNullOrUndefined() const'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::preserveJitCode() const'
./libcef.so: undefined reference to `JS::Value::setUndefined()'
./libcef.so: undefined reference to `MemProfiler::SetNativeProfiler(NativeProfiler*)'
./libcef.so: undefined reference to `JS::GCCellPtr::unsafeAsUIntPtr() const'
./libcef.so: undefined reference to `JS::Value::isNull() const'
./libcef.so: undefined reference to `JSAutoByteString::clear()'
./libcef.so: undefined reference to `JS::ScriptSourceInfo::subtract(JS::ScriptSourceInfo const&)'
./libcef.so: undefined reference to `JS::RuntimeOptions::unboxedArrays() const'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::version() const'
./libcef.so: undefined reference to `JSTracer::weakMapAction() const'
./libcef.so: undefined reference to `JS::Value::getInt32Ref()'
./libcef.so: undefined reference to `JS::ClassInfo::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::disableLazyParsing() const'
./libcef.so: undefined reference to `JS::CompartmentOptions::behaviors()'
./libcef.so: undefined reference to `JS::StringInfo::add(JS::StringInfo const&)'
./libcef.so: undefined reference to `JS::Value::setSymbol(JS::Symbol*)'
./libcef.so: undefined reference to `JS::RuntimeOptions::setExtraWarnings(bool)'
./libcef.so: undefined reference to `js::Class::shouldDelayMetadataCallback() const'
./libcef.so: undefined reference to `JS::Value::getDoubleRef()'
./libcef.so: undefined reference to `JS::Value::setMagicUint32(unsigned int)'
./libcef.so: undefined reference to `JS::ContextOptions::toggleDontReportUncaught()'
./libcef.so: undefined reference to `JS::RuntimeOptions::matchFlagArgument() const'
./libcef.so: undefined reference to `js::CStringHasher::match(char const*, char const*)'
./libcef.so: undefined reference to `JS::ClassInfo::sizeOfLiveGCThings() const'
./libcef.so: undefined reference to `JS::Value::isInt32() const'
./libcef.so: undefined reference to `JS::CompartmentOptions::creationOptions()'
./libcef.so: undefined reference to `MemProfiler::getGCHeapProfiler() const'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::setInvisibleToDebugger(bool)'
./libcef.so: undefined reference to `JSAutoByteString::encodeLatin1(JSContext*, JSString*)'
./libcef.so: undefined reference to `js::AutoStableStringChars::isLatin1() const'
./libcef.so: undefined reference to `JSTracer::isMarkingTracer() const'
./libcef.so: undefined reference to `JS::AutoAssertNoAlloc::disallowAlloc(JSRuntime*)'
./libcef.so: undefined reference to `JS::Value::isString() const'
./libcef.so: undefined reference to `JS::ClassInfo::isNotable() const'
./libcef.so: undefined reference to `JS::TransitiveCompileOptions::mutedErrors() const'
./libcef.so: undefined reference to `JSErrorReport::tokenOffset() const'
./libcef.so: undefined reference to `JSAutoStructuredCloneBuffer::abandon()'
./libcef.so: undefined reference to `JS::Value::isUndefined() const'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::getSingletonsAsTemplates() const'
./libcef.so: undefined reference to `JSTracer::runtime() const'
./libcef.so: undefined reference to `js::AutoStableStringChars::twoByteRange() const'
./libcef.so: undefined reference to `JS::Value::isObject() const'
./libcef.so: undefined reference to `JS::StringInfo::subtract(JS::StringInfo const&)'
./libcef.so: undefined reference to `JS::Value::setPrivateUint32(unsigned int)'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::experimentalDateTimeFormatFormatToPartsEnabled() const'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::extraWarningsOverride()'
./libcef.so: undefined reference to `JS::RuntimeOptions::setThrowOnAsmJSValidationFailure(bool)'
./libcef.so: undefined reference to `js::shadow::Object::fixedSlots() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::werror() const'
./libcef.so: undefined reference to `JS::shadow::Runtime::gcStoreBufferPtr()'
./libcef.so: undefined reference to `JS::ObjectPtr::writeBarrierPre(JSRuntime*)'
./libcef.so: undefined reference to `JS::Value::toGCCellPtr() const'
./libcef.so: undefined reference to `JS::ObjectOpResult::checkStrictErrorOrWarning(JSContext*, JS::Handle<JSObject*>, bool)'
./libcef.so: undefined reference to `JS::RuntimeOptions::toggleAsmJS()'
./libcef.so: undefined reference to `JS::TabSizes::add(JS::TabSizes::Kind, unsigned long)'
./libcef.so: undefined reference to `JS::Value::setObjectOrNull(JSObject*)'
./libcef.so: undefined reference to `JS::Value::payloadWord() const'
./libcef.so: undefined reference to `JS::ObjectPtr::finalize(JSRuntime*)'
./libcef.so: undefined reference to `JS::Value::extractNonDoubleType() const'
./libcef.so: undefined reference to `js::ClassSpec::prototypeFunctions() const'
./libcef.so: undefined reference to `JS::StringInfo::isNotable() const'
./libcef.so: undefined reference to `js::AutoStableStringChars::latin1Range() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::toggleWasm()'
./libcef.so: undefined reference to `JS::shadow::Runtime::isHeapBusy() const'
./libcef.so: undefined reference to `JS::ObjectPtr::get() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::setWerror(bool)'
./libcef.so: undefined reference to `MemProfiler::SweepNursery(JSRuntime*)'
./libcef.so: undefined reference to `js::Class::hasPrivate() const'
./libcef.so: undefined reference to `JS::HandleValueArray::length() const'
./libcef.so: undefined reference to `JS::SourceBufferHolder::ownsChars() const'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::setTrace(void (*)(JSTracer*, JSObject*))'
./libcef.so: undefined reference to `JSJitSetterCallArgs::length() const'
./libcef.so: undefined reference to `JS::Value::isBoolean() const'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::setDiscardSource(bool)'
./libcef.so: undefined reference to `JS::AutoGCRooter::GetTag(JS::Value const&)'
./libcef.so: undefined reference to `JSJitInfo::aliasSet() const'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::setExperimentalDateTimeFormatFormatToPartsEnabled(bool)'
./libcef.so: undefined reference to `JSJitGetterCallArgs::rval()'
./libcef.so: undefined reference to `JS::GCSizes::addToServoSizes(JS::ServoSizes*) const'
./libcef.so: undefined reference to `JS::RuntimeOptions::setUnboxedArrays(bool)'
./libcef.so: undefined reference to `JS::Value::setNumber(unsigned int)'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::setPreserveJitCode(bool)'
./libcef.so: undefined reference to `JS::ObjectOpResult::ok() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::toggleThrowOnAsmJSValidationFailure()'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::discardSource() const'
./libcef.so: undefined reference to `JS::CompartmentStats::addToTabSizes(JS::TabSizes*) const'
./libcef.so: undefined reference to `JS::Value::setMagic(JSWhyMagic)'
./libcef.so: undefined reference to `JS::Value::whyMagic() const'
./libcef.so: undefined reference to `JS::Value::setPrivate(void*)'
./libcef.so: undefined reference to `JS::RuntimeOptions::setAsyncStack(bool)'
./libcef.so: undefined reference to `JS::HandleValueArray::fromMarkedLocation(unsigned long, JS::Value const*)'
./libcef.so: undefined reference to `js::ErrorReport::message()'
./libcef.so: undefined reference to `JS::CompartmentCreationOptions::cloneSingletons() const'
./libcef.so: undefined reference to `JS::SourceBufferHolder::get() const'
./libcef.so: undefined reference to `JS::ContextOptions::setDontReportUncaught(bool)'
./libcef.so: undefined reference to `JS::Value::toString() const'
./libcef.so: undefined reference to `JS::Value::toDouble() const'
./libcef.so: undefined reference to `JS::TransitiveCompileOptions::filename() const'
./libcef.so: undefined reference to `JS::Value::toPrivate() const'
./libcef.so: undefined reference to `JS::shadow::Zone::needsIncrementalBarrier() const'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(JSObject**)'
./libcef.so: undefined reference to `JS::TransitiveCompileOptions::sourceMapURL() const'
./libcef.so: undefined reference to `JS::HandleValueArray::begin() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::setBaseline(bool)'
./libcef.so: undefined reference to `JS::ObjectOpResult::checkStrict(JSContext*, JS::Handle<JSObject*>)'
./libcef.so: undefined reference to `JS::Value::toInt32() const'
./libcef.so: undefined reference to `MemProfiler::RemoveNative(void*)'
./libcef.so: undefined reference to `JS::RuntimeOptions::setStrictMode(bool)'
./libcef.so: undefined reference to `JS::ServoSizes::add(JS::ServoSizes::Kind, unsigned long)'
./libcef.so: undefined reference to `JS::AutoGCRooter::GetTag(jsid const&)'
./libcef.so: undefined reference to `js::Class::isJSFunction() const'
./libcef.so: undefined reference to `JSAutoByteString::encodeUtf8(JSContext*, JS::Handle<JSString*>)'
./libcef.so: undefined reference to `JSJitInfo::needsOuterizedThisObject() const'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(js::LazyScript**)'
./libcef.so: undefined reference to `JS::Value::payloadAsRawUint32() const'
./libcef.so: undefined reference to `JS::Value::magicUint32() const'
./libcef.so: undefined reference to `js::PerThreadDataFriendFields::get(js::PerThreadData*)'
./libcef.so: undefined reference to `JSAutoByteString::initBytes(char*)'
./libcef.so: undefined reference to `JS::CompartmentBehaviors::Override::get(bool) const'
./libcef.so: undefined reference to `JS::CallbackTracer::dispatchToOnEdge(js::Shape**)'
./libcef.so: undefined reference to `js::SystemAllocPolicy::free_(void*)'
./libcef.so: undefined reference to `js::SystemAllocPolicy::checkSimulatedOOM() const'
./libcef.so: undefined reference to `JS::Value::toSymbol() const'
./libcef.so: undefined reference to `JS::RuntimeOptions::setNativeRegExp(bool)'
./libcef.so: undefined reference to `JS::Value::isNumber() const'
./libcef.so: undefined reference to `JS::Value::setNaN()'
./libcef.so: undefined reference to `JSAutoByteString::ptr() const'
./libcef.so: undefined reference to `JS::GCCellPtr::kind() const'
./libcef.so: undefined reference to `JS::ObjectPtr::init(JSObject*)'
./libcef.so: undefined reference to `JS::RuntimeOptions::throwOnAsmJSValidationFailure() const'
collect2: error: ld returned 1 exit status

**Comment by nox** [comment]
@zmike On which commit was that?

**Comment by nox** [comment]
@emilio Just realised we never updated the Linux 64 bindings once I removed the inline symbols from bindgen. ^^'

**Comment by emilio** [comment]
Ohh true, do you want me to do that?

**Comment by nox** [comment]
@emilio So @metajack is trying to regenerate them himself, so that would increase bus factor.

**Comment by nox** [comment]
@zmike Is this solved?

**Comment by zmike** [comment]
It worked last time I tried it, so yes.
