### ISSUE TITLE
console output: document.write is not a function

### ISSUE THREAD

**Issue by manfredbrandl** [servo/servo#8892]
When i visit http://www.orf.at/ i encounter some console output with "document.write" ist not a function.
I think this may be a javascript error, but i am not shure.
See here:
aaa@bbb:~/.../servo$ ./mach run http://www.orf.at/
[glutin] x error code=8 major=42 minor=0!
ERROR:js::rust: Error at http://www.orf.at/:14:3: document.write is not a function

ERROR:js::rust: Error at http://www.orf.at/:8:0: document.write is not a function

ERROR:js::rust: Error at http://www.orf.at/mojo/1_3/storyserver//news/news/html/banner.html?v=1.3&cat=chr&orfcat=Nachrichten:31:9: document.write is not a function

ERROR:js::rust: Error at http://www.orf.at/mojo/1_3/storyserver//news/news/html/banner.html?v=1.3&cat=chr&orfcat=Nachrichten:31:9: document.write is not a function

ERROR:js::rust: Error at http://www.orf.at/mojo/1_3/storyserver//news/news/html/banner.html?v=1.3&cat=wis&orfcat=Wissenschaft:31:9: document.write is not a function

ERROR:js::rust: Error at http://orf.at/stories/2313544/:15:3: document.write is not a function

ERROR:js::rust: Error at http://orf.at/stories/2313544/:14:0: document.write is not a function

**Comment by frewsxcv** [comment]
`document.write` is not implemented yet: https://github.com/servo/servo/issues/3704

Thanks for filing the issue though!
