### ISSUE TITLE
Remove HeapSizeOf trait from util::mem.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8894]
We should use it from crates.io heapsize instead.

**Comment by romankl** [comment]
Could I take a look at this one, please?

**Comment by Wafflespeanut** [comment]
You bet! :)

**Comment by Ms2ger** [comment]
I believe this will allow us to drop the dependencies of util on azure and layers.

**Comment by Ms2ger** [comment]
wip https://github.com/Ms2ger/servo/tree/heapsize-crate

**Comment by aneeshusa** [comment]
I was going to work on this, but it looks like it happened in #9532, so this can be closed.
