### ISSUE TITLE
Replace push_all with extend_from_slice (and other compiler warnings fixes)

### ISSUE THREAD

**Issue by craftytrickster** [servo/servo#8913]
Compiling the latest version of servo produces several compiler warnings of the following type:

    `push_all`. (several locations) This experimental fetaure has been finalized as `extend_from_slice`.
    warning: use of deprecated item: renamed to extend_from_slice, #[warn(deprecated)]

    canvas_traits/lib.rs:7:12: 7:16 warning: this feature is stable. attribute no longer needed, #[warn(stable_features)] on by default
    canvas_traits/lib.rs:7 #![feature(core

    webdriver_server/lib.rs:65:23: 65:38 warning: use of deprecated item: ip type too small a type to pull its weight, #[warn(deprecated)] on by default
    webdriver_server/lib.rs:65         server::start(SocketAddr::new("0.0.0.0".parse().unwrap(), port), handler,

    canvas/lib.rs:5:12: 5:16 warning: this feature is stable. attribute no longer needed, #[warn(stable_features)] on by default
    canvas/lib.rs:5 #![feature(core)]

    webgl_paint_task.rs:16:5: 16:35 warning: use of deprecated item: unidiomatic functions not pulling their weight, #[warn(deprecated)] on by default
    webgl_paint_task.rs:16 use std::slice::bytes::copy_memory;
                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    webgl_paint_task.rs:368:13: 368:24 warning: use of deprecated item: unidiomatic functions not pulling their weight, #[warn(deprecated)] on by default
    webgl_paint_task.rs:368             copy_memory(&src_slice[..stride], &mut pixels[dst_start .. dst_start + stride]);
                                                          
    layout/lib.rs:8:12: 8:17 warning: this feature is stable. attribute no longer needed, #[warn(stable_features)] on by default
    layout/lib.rs:8 #![feature(drain)]

    surface_map.rs:114:43: 114:74 warning: use of deprecated item: renamed to min_by_key, #[warn(deprecated)] on by default
    surface_map.rs:114                     match self.map.iter().min_by(|&(_, x)| x.last_action) {

    compositing/compositor.rs:47:5: 47:35 warning: use of deprecated item: unidiomatic functions not pulling their weight, #[warn(deprecated)] on by default
    compositing/compositor.rs:47 use std::slice::bytes::copy_memory;

**Comment by alex** [comment]
These look to be all done.

**Comment by frewsxcv** [comment]
Yep! https://github.com/servo/servo/pull/8922

**Comment by frewsxcv** [comment]
Also, https://github.com/servo/servo/pull/8923
