### ISSUE TITLE
@font-face text is flashing/changing during rendering 

### ISSUE THREAD

**Issue by yurydelendik** [servo/servo#8917]
See http://people.mozilla.org/~ydelendik/tmp/servo-pdfjs/index.html

This is screenshot of rendering but it's changing multiple times per second:

<img width="785" alt="screen shot 2015-12-10 at 11 14 42 am" src="https://cloud.githubusercontent.com/assets/1523410/11720874/47c87042-9f2f-11e5-9fbe-5e18eeba9b78.png">

(Notice that it's modified svgviewer example, which replaces text/tspan with divs and disables worker)

**Comment by atouchet** [comment]
The link just goes to a login page now.
