### ISSUE TITLE
Support 'server-sent events' (SSE)

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8925]
https://en.wikipedia.org/wiki/Server-sent_events

https://html.spec.whatwg.org/multipage/#server-sent-events

**Comment by KiChjang** [comment]
Do we have wpt tests for this?

**Comment by KiChjang** [comment]
Found them: `tests/wpt/web-platform-tests/eventsource`

**Comment by KiChjang** [comment]
This requires a semi-complete implementation of Fetch, which we currently don't yet.

**Comment by KiChjang** [comment]
I believe this requires an implementation of the Fetch API.
