### ISSUE TITLE
Implement 'JavaScript global environments' concept

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8927]
https://html.spec.whatwg.org/multipage/#javascript-global-environment

https://html.spec.whatwg.org/multipage/webappapis.html#definitions-2

https://github.com/servo/servo/blob/996c0a60b81e7d7e0fbfea81a546771ea9327df6/components/script/dom/xmlhttprequest.rs#L334

https://github.com/servo/servo/blob/996c0a60b81e7d7e0fbfea81a546771ea9327df6/components/script/dom/xmlhttprequest.rs#L426

**Comment by frewsxcv** [comment]
If this is indeed not implemented yet, I'll add tracking issues for those two comments back to here

**Comment by KiChjang** [comment]
Don't we already use `GlobalRef` to encapsulate this concept?

**Comment by frewsxcv** [comment]
It's possible, I'm not familiar with `GlobalRef` so I'm not sure

**Comment by Ms2ger** [comment]
Relevant: https://github.com/whatwg/html/issues/380

**Comment by frewsxcv** [comment]
Update: https://github.com/whatwg/html/issues/380 has been closed

I haven't read what their solution was, but it might be the case this can be closed.

**Comment by Ms2ger** [comment]
This is `GlobalRef`.
