### ISSUE TITLE
preflight_fetch steps comments out of date with spec

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8941]
https://github.com/servo/servo/blob/d6708a2fea41f3078b33e1297a29aac192f5765d/components/script/cors.rs#L180-L181

Busy right now so I can't go too specific, but the steps in the code don't seem to match the spec

**Comment by jinwooahn** [comment]
You're right. The comments do not match the spec.
Can I work for it?

**Comment by frewsxcv** [comment]
Sure!
