### ISSUE TITLE
In case of vertical-align:text-top, font size of parent element is not correctly calculated.

### ISSUE THREAD

**Issue by june0cho** [servo/servo#895]
```html
<span style="line-height: 12pt;">6. 
    <a style="font-size: 200%; vertical-align: text-top;">anchor</a> some angy text
</span>
```
In this case, the top of 'anchor' box should align with the top of the parent's content area.
Currently, the font size of parent element is not being calcutated correctly.

**Comment by mbrubeck** [comment]
I think this is fixed.
