### ISSUE TITLE
Make Event's isTrusted attribute unforgeable

### ISSUE THREAD

**Issue by jdm** [servo/servo#8956]
#7988 added support for the `[Unforgeable]` WebIDL attribute. We should use this in `Event.webidl`, according to the [specification](https://dom.spec.whatwg.org/#event). This should fix some [tests](https://github.com/servo/servo/blob/master/tests/wpt/metadata/dom/interfaces.html.ini) that currently fail.

Code: `components/script/dom/webidls/Event.webidl`
Test: `./mach test-wpt tests/wpt/web-platform-tests/dom/interfaces.html`

The tests that show up as newly passing should be removed from the ini file linked earlier.

**Comment by Aesthetikx** [comment]
I made a change to my commit, it's here now: https://github.com/Aesthetikx/servo/commit/f244a7075c2a296d725d7acad0c043cc002a7f0b and the pr is here: https://github.com/servo/servo/pull/8963
