### ISSUE TITLE
Update CSS.escape to specification changes

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8957]
https://drafts.csswg.org/cssom/#the-css.escape()-method

Code is in `components/script/dom/css.rs`

I believe it is probably sufficient to remove the check for null bytes in the implementation.

There is a test at `tests/wpt/css-tests/cssom-1_dev/html/escape.htm`, but it crashes for unrelated reasons right now.

**Comment by nox** [comment]
@SimonSapin serialize_identifier doesn't replace NUL bytes by U+FFFD, right?

**Comment by jdm** [comment]
The only test in escape.htm that we don't pass right now is the surrogates one, so I think this is fixed.
