### ISSUE TITLE
Rendering bug on SSL Labs

### ISSUE THREAD

**Issue by alex** [servo/servo#8960]
**URL**: https://ssllabs.com/ssltest/viewMyClient.html

**Chrome:**
![screen shot 2015-12-13 at 2 40 35 pm](https://cloud.githubusercontent.com/assets/772/11768854/99834c5c-a1a7-11e5-9b2c-05d869541bb8.png)

**Servo:**
![screen shot 2015-12-13 at 2 40 37 pm](https://cloud.githubusercontent.com/assets/772/11768855/998b3976-a1a7-11e5-89bc-1009404419e9.png)

**Comment by eefriedman** [comment]
It looks like the title is supposed to be separated from the first box by a `<br clear=all>`; not sure why it isn't working.

**Comment by frewsxcv** [comment]
> It looks like the title is supposed to be separated from the first box by a <br clear=all>; not sure why it isn't working.

Might not be supported? #7311
