### ISSUE TITLE
test-tidy is slow

### ISSUE THREAD

**Issue by jdm** [servo/servo#8969]
It takes me 41s to get any output from `./mach test-tidy` on master. We should improve this. @frewsxcv what's the state of the art in profiling python code?

**Comment by frewsxcv** [comment]
I'll assign this to myself and look at it later

**Comment by frewsxcv** [comment]
The [WPT lint we call](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/tools/lint/lint.py) takes 35-40 seconds for my machine to run. I haven't actually looked what's happening in there, just a quick answer for now.

I also opened https://github.com/servo/servo/pull/8977 which is related to this issue

**Comment by frewsxcv** [comment]
I don't have time right now to look into the WPT lint performance so I'm going to unassign for now. I'm not really familiar with any particular Python profiling tool. I usually ended up timing things with `time.time()`

**Comment by Wafflespeanut** [comment]
For what it's worth, the [output](https://gist.github.com/Wafflespeanut/f549bca14078eef042d7) from the [built-in profiler](https://docs.python.org/2/library/profile.html) shows that the WPT lint consumes most of the time.

<small>And yep, my machine takes a hell lot of time for the tidy check!</small>

**Comment by vegayours** [comment]
I investigated into this problem and it seems there are no reason to check wpt lint against web-platform-tests dir at all. This should be checked by web-platform-tests owners and commiters. I think web-platform-tests directory is supposed to be updated only on sync with upstream.

Instead we should run that lint against tests/wpt/mozilla/tests directory. I've already prototyped it and close to submit PR. For my hardware it reduced test-tidy time from 32 to 9 seconds.

We could improve running time further by parallelizing different lint stages in different processes and finally combining their results. Right now they are just executed sequentally.

**Comment by frewsxcv** [comment]
cc @jgraham since this is related to WPT tooling

**Comment by jdm** [comment]
We have bidirectional sync, so we can make changes locally that are merged upstream without any further review. We had several tests that were added this way and did not pass the linter, which caused problems, so we started running it locally. Disabling it is not an option, unfortunately.

**Comment by jmr0** [comment]
For past issues, see https://github.com/servo/servo/issues/8285

**Comment by vegayours** [comment]
ok, bidirectional sync is bad news :(

Do we need to run wpt lint tool for tests/wpt/mozila/test dir?

**Comment by jdm** [comment]
Yes.

**Comment by Ms2ger** [comment]
WIP: https://github.com/servo/servo/compare/wpt-lint?expand=1

**Comment by Wafflespeanut** [comment]
#8977, #9088 and #9649 have improved tidy in many ways. Now, tidy's slow only because of the WPT lint (I guess) - do we still need this issue?

**Comment by jdm** [comment]
Doesn't seem like it.
