### ISSUE TITLE
Remove GenerateCSS2PropertiesWebIDL.py?

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#8998]
`components/script/dom/bindings/codegen/GenerateCSS2PropertiesWebIDL.py`

https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/GenerateCSS2PropertiesWebIDL.py

Doesn't seem like it's used anywhere. Any value in keeping around?

**Comment by Ms2ger** [comment]
I'm fine with removing it. @jdm?

**Comment by jdm** [comment]
Go ahead.
