### ISSUE TITLE
Make use of Url::join

### ISSUE THREAD

**Issue by nox** [servo/servo#9002]
The common idiom `UrlParser::new().base_url(base_url).parse(input)` can now be written as <strike>`base_url.parse(input)`</strike> `base_url.join(input)`.

**Comment by SimonSapin** [comment]
… and `UrlParser` is going away in rust-url 1.0, so upgrading now will make things easier later :)

**Comment by nox** [comment]
Hah, nice. Could you open an issue with what you have in mind for UrlParser?

**Comment by SimonSapin** [comment]
I have a branch, but everything is broken in it right now. I’ll write something up when it’s presentable.

**Comment by magopian** [comment]
Discussing that with @nox and @SimonSapin on irc, it's `base_url.join(input)` that should be used.

**Comment by nox** [comment]
Yeah, most confusing typo ever.

**Comment by magopian** [comment]
Do you want to assign this PR so it doesn't stay in the [servo starters](http://servo.github.io/servo-starters/)?

**Comment by jdm** [comment]
Done!
