### ISSUE TITLE
Intermittent failure in /_mozilla/css/position_fixed_overflow_a.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#9012]
Actual:
<img width="871" alt="screen shot 2015-12-17 at 3 23 37 pm" src="https://cloud.githubusercontent.com/assets/27658/11881016/3308f3d6-a4d2-11e5-85d1-c75d567b66e0.png">
Expected:
<img width="865" alt="screen shot 2015-12-17 at 3 23 47 pm" src="https://cloud.githubusercontent.com/assets/27658/11881015/3308ab38-a4d2-11e5-89c3-c0089587711e.png">

**Comment by emilio** [comment]
I'm trying to reproduce this.

**Comment by nox** [comment]
@emilio Did you manage to reproduce it?

**Comment by mrobinson** [comment]
I don't think we've seen this recently.
