### ISSUE TITLE
A logical operator does not match the spec (cors-preflight-fetch)

### ISSUE THREAD

**Issue by jinwooahn** [servo/servo#9016]
It seems like a logical operator does not match the spec.

https://github.com/servo/servo/blob/master/components/script/cors.rs#L238

https://fetch.spec.whatwg.org/#cors-preflight-fetch

Please review the Substep 4,
thanks!

**Comment by jinwooahn** [comment]
FYI, @jdm  @frewsxcv 
thank you.

**Comment by frewsxcv** [comment]
Fixed in #9017
