### ISSUE TITLE
Ensure Websocket subprotocol argument meets the spec

### ISSUE THREAD

**Issue by jmr0** [servo/servo#9034]
Left as a TODO. We currently don't check that the subprotocol argument received by WebSocket from the client fully conforms to the spec (see /subprotocol/ [here](https://tools.ietf.org/html/rfc6455#section-4.2.2))

(I'm not sure if we already have a util function somewhere to validate a `token` as described by [RFC 2616](https://tools.ietf.org/html/rfc2616))

Relevant code: `components/script/dom/websocket.rs`

**Comment by timvandermeij** [comment]
Can this be closed after #9400?

**Comment by jdm** [comment]
Looks like it!
