### ISSUE TITLE
Style checker: report instances of multiple spaces after a =>

### ISSUE THREAD

**Issue by jdm** [servo/servo#9042]
I've seen this in a couple PRs, and it's an easy thing to check for (`"=>  "`) (note: markdown collapses two spaces into one in the previous code fragment). We should add it to our syntax lints and fix any instances reported by `./mach test-tidy`.

Code: python/tidy.py

**Comment by simartin** [comment]
I propose to take this one.

**Comment by jdm** [comment]
Ok!

**Comment by simartin** [comment]
Cool :-) Should I also check that we have a whitespace before and after => while I'm at it?

**Comment by jdm** [comment]
I'm surprised we don't already, so please do!
