### ISSUE TITLE
Support empty strings as the repeat argument to CanvasRenderingContext2D.createPattern

### ISSUE THREAD

**Issue by jdm** [servo/servo#9079]
See step 3 of https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-createpattern . We currently ignore this and throw a SyntaxError exception instead, according to `CanvasRenderContext2D::CreatePattern` and `RepetitionStyle::from_str`.

Code: `components/script/dom/canvasrenderingcontext2d.rs`, `components/canvas_traits/lib.rs`
Tests:
* `./mach test-wpt tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.empty.html`
* `./mach test-wpt tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.null.html`

**Comment by nerith** [comment]
I'd like to work on this.

**Comment by jdm** [comment]
Sure!
