### ISSUE TITLE
Panic loading http://people.mozilla.org/~sicking/webgl/ray.html

### ISSUE THREAD

**Issue by simartin** [servo/servo#9097]
This is to track the case reported by @dzbarsky in https://github.com/servo/servo/issues/8741, a different issue from the initial one

I've started to work on it and I believe the issue is we might not implement the "Automatic assignment" part of https://www.opengl.org/wiki/Vertex_Shader#Inputs

I'll continue to investigate, so feel free to assign the issue directly to me.

**Comment by simartin** [comment]
The issue is not linked to the missing "Automatic assignment" as I thought (I checked and Chrome does not do it...), but rather to the fact that we were blindly calling *VertexAttrib* without checking the index we passed. This will generate a InvalidValue GL error if it's above MAX_VERTEX_ATTRIBS, in particular when it's -1, coming from a call to getAttribLocation for some unbound attribute.

**Comment by jdm** [comment]
Fixed by #10224.
