### ISSUE TITLE
Intermittent failure of /_mozilla/css/position_fixed_a.html

### ISSUE THREAD

**Issue by nox** [servo/servo#9106]

**Comment by jdm** [comment]
<img width="823" alt="screen shot 2015-12-31 at 7 21 29 am" src="https://cloud.githubusercontent.com/assets/27658/12064359/25fa58c0-af8f-11e5-8c6c-269ad3d539e2.png">
The vertical overflow text for the red block is not clipped in the non-reference screenshot.

**Comment by frewsxcv** [comment]
Disabled in #9527
