### ISSUE TITLE
Trait resolution errors with incremental build

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#911]
I sometimes get

    error: failed to find an implementation of trait layers::layers::TextureManager for azure::azure_hl::DrawTarget

in `compositor_layer.rs` even though it imports `layers::layers::TextureManager` and `azure::azure_hl::DrawTarget`, and the latter module also contains the needed impl.

A clean rebuild from scratch fixes the problem, but `make clean-rust-layers clean-servo` did not.

**Comment by SimonSapin** [comment]
I *think* it’s safe to close this now.
