### ISSUE TITLE
Intermittent failure in /_mozilla/css/stacking_context_overflow_a.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#9120]
<img width="928" alt="screen shot 2016-01-02 at 9 08 36 am" src="https://cloud.githubusercontent.com/assets/27658/12074710/72138252-b130-11e5-9b4b-862df3c5b38e.png">

The overflow text is being clipped erroneously.

**Comment by KiChjang** [comment]
Disabled in #9716

**Comment by mbrubeck** [comment]
Probably the same underlying issue as #9106.  (Both have text incorrectly clipped in an absolute/fixed element.)

**Comment by mrobinson** [comment]
This is no longer disabled in layout 2020, so I'm going to close this one.
