### ISSUE TITLE
Is CEF working now?

### ISSUE THREAD

**Issue by jinwooahn** [servo/servo#9147]
1. I can build cef, but cannot see it running with CEF 3.2556 (dev branch)
2. ports/cef/README.md is quite old. It was updated on 7 May 2015. It is currently wrong, because build.sh is deprecated.
3. The README was updated on 7 May, so I guessed that CEF was working on 7 May.
4. I tried CEF Branch 2171 with old Servo(7 May 2015), but it does not work. (I used git reset --hard)
5. Is Servo CEF working now?
6. Please inform the stable Servo commit with proper cefbuilds Branch. I'd like to see Servo CEF running.

Thank you in advance.

**Comment by jdm** [comment]
@zmike has been working with CEF recently, so he presumably has the most up-to-date instructions.

**Comment by bgrins** [comment]
I can `./mach build-cef` with success but I don't see any libcef.so or libembedding-*.so files in target (at least on OSX).   Also curious if CEF is working, and/or if docs need updating.

**Comment by zmike** [comment]
I posted another ticket about this being broken 3-4 months ago. I haven't had time to test since, but I haven't had a functioning cef build since last year (pre-WR). I suspect that the WR merge is what broke it.

I'm unable to examine this further at the moment, and I'm not sure when I'll be able to, but I'll try to update the readme doc since it's currently unrelated to the process of running cef.

**Comment by bgrins** [comment]
@zmike Thanks for the info.  Any ideas what would need to be done to get it working?  Is it a process of doing the steps at https://github.com/zmike/cef-rebase#cef-binding-generator-for-servo?

**Comment by zmike** [comment]
No, something broke the gl render output. It's potentially a trivial fix, but it's in a nontrivial area.

**Comment by Boscop** [comment]
Can servo be embedded as a CEF compatible lib right now (on windows)?

**Comment by jdm** [comment]
Fundamentally there is no reason that should not work, but since we rarely try the actual embedding it's probably broken at the moment.

**Comment by Boscop** [comment]
But it's part of the tests, so it should build, right?

**Comment by jdm** [comment]
The library builds as part of CI. There is no automated test that it works correctly.

**Comment by Croydon** [comment]
`ports/cef/` doesn't exist anymore, why?

**Comment by atouchet** [comment]
@Croydon see: https://groups.google.com/forum/#!topic/mozilla.dev.servo/5MHDnfMya3s

**Comment by Croydon** [comment]
@atouchet Thanks for the link.

I hope that CEF support comes back down the road. I would love to see it as a drop in replacement for Chromium.

If CEF support is coming back I would also like to try to package it for the C/C++ package manager (and build tool) [Conan](http://conan.io)

**Comment by jdm** [comment]
Since CEF support was removed, there's no reason to keep this issue open.
