### ISSUE TITLE
Create a testsuite for tidy.py

### ISSUE THREAD

**Issue by jdm** [servo/servo#9152]
When we add new error checks to tidy.py or refactor parts of it, we never have any guarantees that it continues to function as expected. We should create a simple test harness that runs our style checks against simple Rust source files that are otherwise ignored during compilation and reports the expected errors.

Code: `python/tidy.py`, `python/testing_commands.py`, `.travis.yml`

**Comment by mskrzypkows** [comment]
I'd like to take this one. Where should be new tests added? ```servo/tests/scripts/test_tidy/test_tidy.py``` would be fine?

**Comment by Wafflespeanut** [comment]
No, `tests` are specific to Servo itself. Since tidy isn't a part of it, I think it'd be fine to have `python/tidy` where the future script and the tests would reside.

**Comment by mskrzypkows** [comment]
OK, so these test will be called manually, not by ./mach test... as other do. Right?

**Comment by Wafflespeanut** [comment]
You're right. This is specifically for the CI builder, which (on every change made to tidy) would check its functionality and ensures that it works as expected.

**Comment by jdm** [comment]
@mskrzypkows Have you made any progress with this? Any questions?

**Comment by mskrzypkows** [comment]
Sorry for the delay. My son born recently :-) and that took me some time to adopt to new situation. I've created one commit: https://github.com/mskrzypkows/servo/commit/17f84b8f48b851767dd06e957fb870977232e43a I still work on it. I want to finish and upload more changes.

**Comment by Wafflespeanut** [comment]
Oh, no worries, that's good to know :)

**Comment by mskrzypkows** [comment]
I think it could be closed.

**Comment by Wafflespeanut** [comment]
fixed by #9835, #10563, #10775
