### ISSUE TITLE
Don’t generate transparent display items

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#9166]
The debug output I’m looking at shows lots of display items like:

```
SolidColor rgba(0, 0, 0, 0) @ Rect(360.8px×132.26666666666668px at (24px,345.2px))
```

… which if I’m reading correctly, is a transparent black rectangle. I think there’s one for the background of every element. (`background-color: transparent` is the initial value.)

There’s probably a few places in `components/layout/display_list_builder.rs` where we can add `if some_color.alpha > 0 { … }` to avoid building and painting transparent display items.

CC @glennw @pcwalton

**Comment by GuillaumeGomez** [comment]
I'd like to take it if no one is on it.

**Comment by glennw** [comment]
@SimonSapin @GuillaumeGomez I believe these are (currently) required for hit testing to work correctly for mouse click events etc. It's not ideal and we do need a better solution, but it's probably not E-Easy.

**Comment by SimonSapin** [comment]
Alright, I’ll just close this as it’s not clear to me what’s required for hit testing. Feel free to open another issue about improving that.
