### ISSUE TITLE
Use self::MixedMessage for handle_msgs in script_task.rs

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9169]
The `handle_msgs` function under `script_task.rs` contains a lot of references to variants of `MixedMessage`. We should make use of a `use` statement in the function so that we can directly reference the variants instead of prepending `MixedMessage::`.

Code: `components/script/script_task.rs`

**Comment by Ms2ger** [comment]
Do you mean `use MixedMessage::*`? That's poor style, IMO.

**Comment by KiChjang** [comment]
Yes, that's what I meant.

**Comment by jdm** [comment]
I'm ok with glob imports in non-global scopes that improve the readability of the resulting code.

**Comment by nerith** [comment]
I'd like to take this.

**Comment by Wafflespeanut** [comment]
It's yours! :)
