### ISSUE TITLE
<input> and <textarea> text not getting clipped on overflow

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#9175]
```html
<input type="text" size=5 value="Hello world!">
<hr>
<textarea>&#13;&#10;&#13;&#10;Hello world!</textarea>
```

![screen shot 2016-01-06 at 8 56 18 pm](https://cloud.githubusercontent.com/assets/416575/12160259/3b8cd374-b4b8-11e5-97d6-36679a1030d5.png)
<img width="754" alt="screen shot 2016-01-06 at 8 56 36 pm" src="https://cloud.githubusercontent.com/assets/416575/12160260/3e4f9344-b4b8-11e5-9509-586b8fad2ea6.png">
<img width="654" alt="screen shot 2016-01-06 at 8 56 48 pm" src="https://cloud.githubusercontent.com/assets/416575/12160261/3f97d36a-b4b8-11e5-86d4-d1bfba8d3134.png">

**Comment by mskrzypkows** [comment]
Is the issue valid? It seems  to be fixed.

**Comment by paulrouget** [comment]
closed by https://github.com/servo/servo/issues/9875
