### ISSUE TITLE
Document/Refactor steps for dispatch_event in eventdispatcher.rs

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9178]
The spec may have changed after it was last modified, so refactoring may be necessary

Code: `components/script/dom/eventdispatcher.rs`
Spec: https://dom.spec.whatwg.org/#concept-event-dispatch

**Comment by iszak** [comment]
I would like to give this a try

**Comment by KiChjang** [comment]
@iszak any updates on this?

**Comment by iszak** [comment]
@KiChjang I have made what I think are the correct changes locally, just need to rebase and push and will create a new pull request in the next week.
