### ISSUE TITLE
Rename fire_simple_event_params to fire_event in eventtarget.rs

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9180]
`fire_simple_event` implements an algorithm [defined in the HTML spec](https://html.spec.whatwg.org/multipage/webappapis.html#fire-a-simple-event). However, there is also `fire_event` which is [defined in the DOM spec](https://dom.spec.whatwg.org/#concept-event-fire), and it is currently named `fire_simple_event_params`. We should instead rename it appropriately.

Also, the WebIDL definition for `Event` needs a spec link.

Code: `components/script/dom/eventtarget.rs`, `components/script/dom/webidls/Event.webidl`
Spec: https://dom.spec.whatwg.org/#concept-event-fire

**Comment by nerith** [comment]
I'd like to take this.

**Comment by KiChjang** [comment]
Alright!
