### ISSUE TITLE
Implement encoding determination for external scripts.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9185]
* Spec: <https://html.spec.whatwg.org/multipage/scripting.html#establish-script-block-source>.
* Code: `components/script/dom/htmlscriptelement.rs`, `fn execute`.
* Tests: none that I know of, so I'll be expecting quite a few tests to be written as part of this issue. These should probably live in (a subdir of) `tests/wpt/web-platform-tests/html/semantics/scripting-1/the-script-element`.

**Comment by askalski** [comment]
I attempted to do something here, but I am not sure if I get steps 3 and 4 right.

https://github.com/askalski/servo/tree/issue9185

**Comment by askalski** [comment]
I was unable to locate "script block's fallback character encoding", and I don't know which one is "character encoding"

should any of these mimic this:
https://developer.mozilla.org/en-US/docs/Web/Guide/Localizations_and_character_encodings#Specifying_the_fallback_encoding
?

**Comment by askalski** [comment]
From what I understand fromhttps://html.spec.whatwg.org/multipage/scripting.html#establish-script-block-source , I should deduce "script block's fallback character encoding" from document's one.

I added two "HELPME" comments, with specific questions. I would appreciate some suggestions.

**Comment by Ms2ger** [comment]
First, in Servo right now, "the script block's fallback character encoding" will always be UTF-8, so feel free to read "UTF-8" where that is written.

Second, I think we'll need to change the type of `block_character_encoding`. Rather than having it be `DOMRefCell<EncodingRef>` and initializing to `DOMRefCell::new(UTF_8 as EncodingRef)`, I think we should make it a `DOMRefCell<None>` and initialize it to `DOMRefCell::new(None)`. This will allow you to implement the "If the algorithm above set the script block's character encoding" check.

**Comment by askalski** [comment]
I implemented suggested changes, now I am going to open a pull request (even though I haven't add the tests yet) to see what travis CI says.

**Comment by jdm** [comment]
Fixed by #10079.
