### ISSUE TITLE
Use the fetch infrastructure for external script elements.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9186]
Depends on #4576.

* Spec: <https://html.spec.whatwg.org/multipage/#script-processing-src-prepare>.
* Code: `components/script/dom/htmlscriptelement.rs`, `fn execute`.
* Test: not yet sure what web-visible effects this would have, but I imagine there will be some tests that would be useful to write.

**Comment by KiChjang** [comment]
Should this use the Fetch DOM API or the native Rust fetch?

**Comment by jdm** [comment]
Native Rust.
