### ISSUE TITLE
Tidy should stop calling the WPT lint using subprocess

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#9189]
Instead of the subprocess call (in `check_wpt_lint_errors`), we should change the working directory to `tests/wpt/web-platform-tests`, so that we can just import the lint's `main` function, and do the checks directly. This will be very helpful for a future plan to improve tidy's performace (once w3c/wpt-tools#45 is fixed)

Code: `python/tidy.py` and `tests/wpt/web-platform-tests/tools/lint/lint.py`

**Comment by PythonNut** [comment]
I'll grab this, if you don't mind. :)

**Comment by KiChjang** [comment]
Sure thing!

**Comment by PythonNut** [comment]
> We should change the working directory to `tests/wpt/web-platform-tests`, so that we can just import the lint's main function, and do the checks directly.

Why not add the directory with `sys.path.insert(0, ...)`  and import it that way?

**Comment by Wafflespeanut** [comment]
Well, I'm okay with any solution that works as expected :)

**Comment by PythonNut** [comment]
@Wafflespeanut what would you like to do with the exit error codes?
