### ISSUE TITLE
Intermittent failure of /_mozilla/css/mix_blend_mode_a.html

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9205]
```
  ▶ FAIL [expected PASS] /_mozilla/css/mix_blend_mode_a.html
  └   → /_mozilla/css/mix_blend_mode_a.html d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c
/_mozilla/css/mix_blend_mode_ref.html cab28df3ff5ab6f04e34b81019bde496e05d8965
Testing d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c == cab28df3ff5ab6f04e34b81019bde496e05d8965
```

**Comment by jdm** [comment]
The non-reference output is a white page.

**Comment by nox** [comment]
![capture d ecran 2016-02-20 a 00 49 06](https://cloud.githubusercontent.com/assets/123095/13192405/c7175f10-d76b-11e5-9f94-5a231f28c3bf.png)

**Comment by nox** [comment]
The non-reference file is just blank.

**Comment by nox** [comment]
Oh sorry, I guess I should go to sleep…

**Comment by mrobinson** [comment]
This is no longer disabled in layout 2020, so I'm going to close this one.
