### ISSUE TITLE
Intermittent timeout in /css-backgrounds-3_dev/html4/background-intrinsic-006.htm (constellation panicked at `Result::unwrap`)

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#9215]
▶ TIMEOUT [expected FAIL] /css-backgrounds-3_dev/html4/background-intrinsic-006.htm
    │ 
    │ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 104, message: "Connection reset by peer" } }', ../src/libcore/result.rs:741
    │ stack backtrace:
    │    1:     0x7f53819f7100 - sys::backtrace::tracing::imp::write::h92808652e552bec0MZt
    │    2:     0x7f53819f9f65 - panicking::log_panic::_<closure>::closure.41184
    │    3:     0x7f53819f99e0 - panicking::log_panic::hc4038fe8a2a609d626x
    │    4:     0x7f53819e33d3 - sys_common::unwind::begin_unwind_inner::hd5a3cc6e3320d6b8lSs
    │    5:     0x7f53819e3a88 - sys_common::unwind::begin_unwind_fmt::h7eec50b09af6e91crRs
    │    6:     0x7f53819f6761 - rust_begin_unwind
    │    7:     0x7f5381a27e9f - panicking::panic_fmt::h871c0ef100fda9e9LFK
    │    8:     0x7f5380327789 - constellation::_<impl>::handle_request::handle_request::h7837806850911603131
    │    9:     0x7f5380311997 - export::compositing::constellation::_<impl>::start::_<closure>::closure.23225
    │   10:     0x7f53803111f3 - sys_common::unwind::try::try_fn::try_fn::h16915514916487452209
    │   11:     0x7f53819f65a8 - __rust_try
    │   12:     0x7f53819f297b - sys_common::unwind::try::inner_try::h3990fffe7b775df5TOs
    │   13:     0x7f53803131da - boxed::_<impl>::call_box::call_box::h14416964104727431377
    │   14:     0x7f53819f88c3 - sys::thread::_<impl>::new::thread_start::h05427eb97025f9aae9w
    │   15:     0x7f537d8cf181 - start_thread
    │   16:     0x7f537fae647c - __clone
    └   17:                0x0 - <unknown>

**Comment by jdm** [comment]
#8815.
