### ISSUE TITLE
Implement HTMLDetailsElement

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9216]
This requires an implementation of the `attribute_mutated` function in `VirtualMethods` for `HTMLDetailsElement`, when attempting to implement the [details notification task steps](https://html.spec.whatwg.org/multipage/#details-notification-task-steps). It also requires the usage of the DOM manipulation task source.

Code: `components/script/dom/htmldetailselement.rs` (new file), `components/script/dom/webidls/HTMLDetailsElement.webidl` (new file)
Tests: `tests/wpt/web-platform-tests/html/semantics/interactive-elements/the-details-element/details.html`
Spec: https://html.spec.whatwg.org/multipage/#htmldetailselement

Requires #9217.

**Comment by MonsieurLanza** [comment]
This one is appealing me. May I give it a try ?

I understand (#9217)[https://github.com/servo/servo/pull/9217] is blocking it, but I expect it to be reviewed before I even get rid of 

    servo/components/script/dom/virtualmethods.rs:20:5: 20:48 error: unresolved import `dom::htmldetailselement::HTMLDetailsElement`. Could not find `htmldetailselement` in `dom` [E0432]

while trying to build.
;)

**Comment by jdm** [comment]
I think it's possible to work on this without waiting for #9217. Either this work will need to be rebased after it merges, or #9217 will need to be updated to account for this. Either way, I would say go for it :)

**Comment by jdm** [comment]
As for that error, take a look at components/script/dom/mod.rs :)

**Comment by nox** [comment]
This module screams "have mercy and codegen the hell out of myself" to me.

**Comment by MonsieurLanza** [comment]
Thanks. :)

**Comment by MonsieurLanza** [comment]
The details element should hide non "first-child <summary>" children. 

I was wondering how this is supposed to be implemented, and if it is in the scope of the issue ?
My understanding is that could be done in user-agent.css, as this would allow overriding by a user stylesheet. Not sure what to do about this.

Also, user agent should provide a way to toggle the details element, but this is a design decision and goes way beyond just implementing the HTMLDetailsElement interface. ATM, on my working copy, the only way is setting the open attribute via JS.

**Comment by jdm** [comment]
Yes, we should file a separate issue about exposing a UI for `<details>`. As for hiding the children, doing that via CSS makes sense to me.
