### ISSUE TITLE
Move AnimationState to script_traits

### ISSUE THREAD

**Issue by jdm** [servo/servo#9223]
This is defined in msg but used by code that depends on script_traits.

Code: `components/msg/constellation_msg.rs`, `components/script_traits/lib.rs`

**Comment by shssoichiro** [comment]
I'd like to take this one. @jdm would you be willing to mentor if needed? (Familiar with Rust but new to Servo)

**Comment by Wafflespeanut** [comment]
@shssoichiro Cool! Feel free to ask! (or ping us at the IRC)

**Comment by jdm** [comment]
Yep! Anybody should be able to answer questions about this :)

**Comment by shssoichiro** [comment]
In script_traits, `#![deny(missing_docs)]` is enabled--however I'm unsure how to document the enum that was moved over:

    #[derive(Clone, Eq, PartialEq, Deserialize, Serialize, Debug)]
    pub enum AnimationState {
        AnimationsPresent,
        AnimationCallbacksPresent,
        NoAnimationsPresent,
        NoAnimationCallbacksPresent,
    }

**Comment by Ms2ger** [comment]
Feel free to add `#[allow(missing_docs)]` unless someone comes up with docs.

**Comment by jdm** [comment]
`/// For a given pipeline, whether any animations are current running and if any animation callbacks are queued`

**Comment by jdm** [comment]
```rust
/// Animations are active but no callbacks are queued
/// Animations are active and callbacks are queued
/// No animations are active and no callbacks are queued
/// No animations are active but callbacks are queued
```

**Comment by shssoichiro** [comment]
Is it expected to have failing tests? I have a number of tests that are failing against the code in master (without this refactoring applied):

    Ran 3833 tests finished in 568.0 seconds.
      • 3812 ran as expected. 700 tests skipped.
      • 1 tests crashed unexpectedly
      • 19 tests failed unexpectedly
      • 1 tests timed out unexpectedly
      • 1 tests had unexpected subtest results

**Comment by jdm** [comment]
Unfortunately we have a large number of intermittent failures right now (see the I-intermittent label in the issue tracker). For changes that are literally just moving code between crates, there's no need to run tests - if it compiles, that's as much test as is required to demonstrate correctness.

**Comment by shssoichiro** [comment]
Great, then I'll go ahead and submit a PR.
