### ISSUE TITLE
Move MozBrowserEvent to script_traits

### ISSUE THREAD

**Issue by jdm** [servo/servo#9225]
It's defined in `msg` but only used by `compositing`, `script`, and `script_traits`. It belongs in `script_traits`.

Code: `components/msg/constellation_msg.rs`, `components/script_traits/lib.rs`

**Comment by apopiak** [comment]
I'd like to grab this one.
@jdm would you be willing to mentor? (newbie here ;-) )

**Comment by KiChjang** [comment]
Again, look for us in the IRC channel :)

**Comment by jdm** [comment]
@apopiak Absolutely!

**Comment by apopiak** [comment]
claiming this one then :-)

**Comment by apopiak** [comment]
so @bholley 
this one is still open? ;-)

**Comment by bholley** [comment]
As far as I know yes! Double-check with @jdm or @KiChjang or @nox on IRC to be sure.

**Comment by nox** [comment]
@apopiak Yes it is.
