### ISSUE TITLE
Remove GlobalField

### ISSUE THREAD

**Issue by nox** [servo/servo#9227]
`GlobalField` is used to store a reference to the global associated with a given DOM object. This is pointless because all DOM objects implements `Reflectable`, and we can just use `global_root_from_reflector` on it.

Fields on DOM structs of type `GlobalField` should be removed and the aforementioned function should be used instead.

Finally, the function should probably be made a default method on the `Reflectable` trait.

Files:
 * components/script/dom/bindings/global.rs
 * components/script/dom/blob.rs
 * components/script/dom/canvasrenderingcontext2d.rs
 * components/script/dom/filereader.rs
 * components/script/dom/formdata.rs
 * components/script/dom/storage.rs
 * components/script/dom/webglrenderingcontext.rs
 * components/script/dom/websocket.rs
 * components/script/dom/worker.rs
 * components/script/dom/xmlhttprequest.rs

**Comment by nox** [comment]
As an example of what to do, see [this commit](https://github.com/nox/servo/commit/0e3f066e8a971b1d90a07b4448e12a57c34b114c).

**Comment by nox** [comment]
@Ms2ger Do you think the function or method could return `GlobalRef` instead of `GlobalRoot`, btw?

**Comment by fmmartins** [comment]
Hello. I will be working on it!

**Comment by ckimes89** [comment]
I'd like to try this one.

**Comment by KiChjang** [comment]
Okay!

**Comment by ckimes89** [comment]
For a default method on the `Reflectable` trait, would the function name `root` get the meaning across, or should it be `global_root`?

**Comment by nox** [comment]
I would call it get_global or something like that.

**Comment by Ms2ger** [comment]
I'm not entirely sure about this. Having the global in a field avoids a bunch of pointer-chasing through the JS engine. Will leave the decision to @jdm.

**Comment by nox** [comment]
@Ms2ger There are few GlobalField users, and I don't think any of them are on a hot path.

**Comment by jdm** [comment]
Yeah, I'm inclined to remove these until we find ones that are performance-sensitive.
