### ISSUE TITLE
Support WebAssembly (wasm)

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#9232]
https://en.wikipedia.org/wiki/WebAssembly

https://github.com/WebAssembly/design

https://www.w3.org/community/webassembly/

**Comment by frewsxcv** [comment]
V8 just announced their intentions to support WASM:
* https://groups.google.com/forum/#!topic/v8-users/PInzACvS5I4

@asajeffrey is currently experimenting with a pure-Rust implementation of the WASM runtime:
* https://github.com/asajeffrey/wasm

**Comment by frewsxcv** [comment]
If it weren't for asajeffrey's experimenting efforts, I probably wouldn't have opened this since this would otherwise be a SpiderMonkey tracking issue. So if people think this tracking issue is not appropriate in Servo, feel free to close this, but it might be nice to have it to follow along on the progress.

**Comment by frewsxcv** [comment]
Chromium tracking issue:
* https://code.google.com/p/chromium/issues/detail?id=575167

**Comment by asajeffrey** [comment]
I'm happy to have a Servo issue for this. Issues with the Rust wasm implementation should be tracked at https://github.com/asajeffrey/wasm.

**Comment by LifeIsStrange** [comment]
Hello I have a good news =) , Microsoft has opensourced their JavaScript chakra engine !! 
Here there is their webassembly prototype : 
https://github.com/Microsoft/ChakraCore/pull/63

**Comment by frewsxcv** [comment]
Gecko metabug: https://bugzilla.mozilla.org/show_bug.cgi?id=1188259

**Comment by frewsxcv** [comment]
Another wasm in Rust project appears: https://gitlab.com/DanielKeep/wasm

**Comment by cvan** [comment]
> Another wasm in Rust project appears: https://gitlab.com/DanielKeep/wasm

I haven't been keeping up on the WASM mailing lists. Do people know of any projects or modules that people have made to support this in Servo or Rust land?

**Comment by atouchet** [comment]
Is this done now?

**Comment by jdm** [comment]
Yep!
