### ISSUE TITLE
Switch output interval to output type?

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#9238]
Memory and time profiling currently take a time interval and print their profiling data to stdout at that interval. IIRC, that's because shutdown used to be more unreliable & crashy than it is today.

I'd like to change these arguments to instead take an optional argument (filename). If the filename is present, it'll write out a CSV file with the data at the end of the run. If it's not present, then the output will be printed to stdout.

Any opinions? Am I misremembering the scenario for needing the time interval?

CC: @pcwalton @mbrubeck @nnethercote

**Comment by nnethercote** [comment]
The ability to correlate measurements to user actions is useful. With your suggestion this ability would be mostly lost -- it's hard to correlate even timestamped measurements in that fashion.

Also, how do you plan to process and present the data? The memory profiling data is presented in a tree structure. To not lose functionality you'll need a way to present that information nicely.

For comparison, here's how Firefox works. In about:memory you can do the following: (1) take and view memory measurements immediately; (2) take and save memory measurements in a file (the format is JSON based); load a view saved memory measurements.

I know much less about the time profiling measurements but it seems like there was at least some structure there too, i.e. not just a flat list of measurements.

**Comment by metajack** [comment]
I definitely used profiling on a timer for memory stuff back when I fixed the flow tree memory leak, so I think it is very useful there. I'm not sure the normal profiler needs that mode, although I could see it having instead one where it spits out a profile for every page load or something.

**Comment by larsbergstrom** [comment]
Sounds good; I just did something one-off in a branch for the paper we're working on.

I do think that long-term it would be nice to separate out the commandline argument as something for headless / automated profiling runs vs. having the devtools or automation-based sampling APIs that would enable the live testing/profiling scenarios mentioned.
