### ISSUE TITLE
Move ParseErrorReporter to style.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9246]
It's defined in `msg` but only used by `style`, `script`, and `layout`. It belongs in `style`.

Code: `components/msg/lib.rs`, `components/style/parser.rs`.

**Comment by Ms2ger** [comment]
This also involves removing the dependency on the `cssparser` crate from `components/msg/Cargo.toml` and `components/msg/lib.rs`.

**Comment by apopiak** [comment]
I think I'd like to grab this one.
@Ms2ger would you be willing to mentor? (newbie here ;-) )

**Comment by KiChjang** [comment]
@apopiak You can join the #servo channel at `irc.mozilla.org`. Simply ask any questions there, and either I, @Ms2ger or someone else will gladly help you!

**Comment by apopiak** [comment]
great see you there

**Comment by bholley** [comment]
I already had a patch for this one - please CC me on style-related refactoring issues and PRs if you can so that we avoid duplicated work. :-)

**Comment by KiChjang** [comment]
Fixed by #9261.

**Comment by apopiak** [comment]
@bholley sure, I just thought is was still open because it didn't have the flag and there was no assignee ;-)
can you update the other issues so I know what's still open?

**Comment by bholley** [comment]
Yeah, you totally did the right thing. The problem was just that @Ms2ger filed an issue for something I had already written a PR for, and neither of us noticed what the other was doing. That's a pretty rare thing to happen, and in general open issues should be open!
