### ISSUE TITLE
Move MouseButton to script_traits

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9250]
This is defined in `msg` but used by code that depends on `script_traits`.

Code: `components/msg/constellation_msg.rs`, `components/script_traits/lib.rs`.

**Comment by DarinM223** [comment]
Could I try to do this? Thanks!

**Comment by KiChjang** [comment]
Yes, certainly! If you need directions, the folks at #servo at `irc.mozilla.org` are always happy to help!
