### ISSUE TITLE
Argument to createAttribute should be lowercased in HTML documents

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9252]
Blocks #2185.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createattribute>, step 2.
* Code: `components/script/dom/document.rs`, `fn CreateAttribute`.
* Test: `dom/nodes/Document-createAttribute.html`.

Similar code exists in the `CreateElement` function.

**Comment by mattnenterprise** [comment]
I will take this one

**Comment by KiChjang** [comment]
Sure thing!
