### ISSUE TITLE
Write a tool that reports unnecessary crate dependencies

### ISSUE THREAD

**Issue by jdm** [servo/servo#9256]
There are two kinds of unnecessary dependencies that are easy to miss:
* libraries listed in a `Cargo.toml` file for which there is no corresponding `extern crate` statement in the source code
* uses of `extern crate foo` in source files for which there are no corresponding import statements (ie. `use foo[::]`)

Removing these will make our dependency graph more clear, and having a tool that reports useless ones will allow us to keep it clear. I propose doing this in Python, where we have a library for parsing TOML files already (see `python/tidy.py`).

**Comment by Jayflux** [comment]
I might be tempted to pick this up

**Comment by jdm** [comment]
Ok! Let us know if you start working on it and we'll mark it assigned, in that case.

**Comment by dbrgn** [comment]
Doesn't `#[warn(unused-extern-crates)]` do at least part of this already?

And if not, wouldn't it be better to add these as lints to rust-clippy and use clippy in Servo?

**Comment by jdm** [comment]
Does that lint warn by default? If so, we could ignore the second bullet in my original comment.

**Comment by dbrgn** [comment]
> Does that lint warn by default?

No. You can check with `rustc -W help`:

                      name  default  meaning
                      ----  -------  -------
      unused-extern-crates  allow    extern crates that are never used

It can be turned on easily crate-wide though, with:

    #![deny(unused_extern_crates)]

**Comment by jdm** [comment]
Unfortunately, we have a _lot_ of crates. :) I'm fine with duplicating the lint's work so that we get it by default everywhere.

**Comment by Ms2ger** [comment]
Also note https://github.com/rust-lang/rust/issues/30849

**Comment by Jayflux** [comment]
@jdm  i have started writing, i will put up a first draft later

**Comment by Jayflux** [comment]
@jdm https://github.com/Jayflux/servo/blob/dependenciesReporter/python/dependency_checker.py
first draft here for you to try

However, i am having some trouble.. the toml python module fails to parse half of the cargo.toml files, so im unable to check them all.
Is this a problem with the files or the toml library?
My editor also shows some highlighting on the inline tables (where the toml library fails)
http://imgur.com/KPoSgu0

**Comment by Jayflux** [comment]
@jdm  So this could be harder than it looks.
I have it all working, however some dependancies are not loaded in via the 'use' statement and are instead just used directly within rust code.

So checking extern crate against whats actually being used may be a little harder.

I have carg.toml being checked against 'extern crate' and 'plugin' working however..

**Comment by jdm** [comment]
@Jayflux do you have an example of what you're describing?

**Comment by dbrgn** [comment]
I think @Jayflux means something like this:

```rust
extern crate spaceapi;

use spaceapi::Icon;

fn main() {
    println!("Hello, world!");
    println!("{:?}", Icon {
        open: "open.png".into(),
        close: "close.png".into(),
    });
}
```

vs

```rust
extern crate spaceapi;

fn main() {
    println!("Hello, world!");
    println!("{:?}", spaceapi::Icon {
        open: "open.png".into(),
        close: "close.png".into(),
    });
}
```

**Comment by jdm** [comment]
Ah, that's a good point. I guess we can scan the files for `use foo;` and `foo::` for each `extern crate foo;` that is encountered.

**Comment by Jayflux** [comment]
@jdm I was thinking the same, i will give it a try this evening.
This ticket is also dependant the on this PR to TOML

**Comment by dbrgn** [comment]
@jdm that won't do either, this works too:

main.rs

```rust
extern crate spaceapi;

mod sub;

fn main() {
    println!("Hello, world!");
    sub::printer();
}
```

sub.rs

```rust
pub fn printer() {
    println!("{:?}", super::spaceapi::Icon {
        open: "open.png".into(),
        close: "close.png".into(),
    });
}
```

As well as this one (a bit less realistic):

```rust
extern crate spaceapi;

fn main() {
    println!("Hello, world!");
    println!("{:?}", self::spaceapi::Icon {
        open: "open.png".into(),
        close: "close.png".into(),
    });
}
```

**Comment by jdm** [comment]
The commented one doesn't bother me, and I think the others are addressed by looking for "foo::" and not caring about false positives generated by "prefixedfoo::".

**Comment by autrilla** [comment]
I'd like to take this one if it's still needed.

**Comment by jdm** [comment]
I suspect the work that @Jayflux was doing stalled due to the unmerged PR to the TOML library that we're using. I'm not sure what are options are to get around that :/

**Comment by autrilla** [comment]
I guess we could use our own fork instead of the original one?

**Comment by zwn** [comment]
`unused-extern-crates` can be turn on with cmdline too. To quickly test it try `export RUSTFLAGS="-w unused-extern-crates"`. Building with it set reports about 20 warnings. I could add this flag to mach.

@jdm  Would that qualify as "being on by default"?

**Comment by jdm** [comment]
I guess so!

**Comment by Ms2ger** [comment]
Last I checked, there was an issue with `macro_use` crates, so I'm not sure if it should be on by default.

**Comment by zwn** [comment]
What kind of issue? How can I check it? Well, I'll do PR anyway. We can drop it if that turns out to be better.

**Comment by Ms2ger** [comment]
Fixed in #10706.

**Comment by RReverser** [comment]
This is a pretty old issue but I found it while searching for a tool that reports unused dependencies myself.

While the last comment states this issue was fixed, the attached PR solves only the second half of the issue as described (detecting unused `extern crate` statements) but it looks like Cargo.toml part is still not fixed and such tool doesn't exist.

**Comment by jonhoo** [comment]
This was discussed [on Twitter](https://twitter.com/Jonhoo/status/1085602115119181825) recently too in the context of the 2018 edition mostly getting rid of `extern crate`. See also the discussion in https://github.com/rust-lang/rust/issues/57274#issuecomment-454884915.

**Comment by RReverser** [comment]
Ha, good timing. Thanks for the pointers!

**Comment by teohhanhui** [comment]
For those ending up here from a Google search, there's https://crates.io/crates/cargo-udeps
