### ISSUE TITLE
Improve test-tidy output for mis-ordered stuff

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9259]
This never seems to have terribly useful output.

**Comment by Wafflespeanut** [comment]
What if tidy (whenever it encounters something unordered) shows the rest of the output in orderly form? I did [a similar thing](https://github.com/Wafflespeanut/rust-sorty/blob/master/EXAMPLE.md) for my sorting lint.

**Comment by nox** [comment]
The current output seems ok to me.
