### ISSUE TITLE
Make sure it's possible to use style without depending on js.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9260]
The crate that defines `DOMString` needs to depend on js, because it has to implement `FromJSConvertible` and `ToJSConvertible` for use in `script`. However, style has to depend on `DOMString` for `AttrValue`. It might be possible to have a cargo feature so that util can implement those traits when used within Servo, but not Gecko.

CC @Manishearth @jdm @bholley

**Comment by asajeffrey** [comment]
Rather than use a feature, we could keep DOMString in util, but move the conversions to/from JSString into script.

**Comment by bholley** [comment]
I think @Ms2ger's feature idea should work. Trying it out.

**Comment by Ms2ger** [comment]
> Rather than use a feature, we could keep DOMString in util, but move the conversions to/from JSString into script.

FTR, we can't, because of orphan rules.

**Comment by asajeffrey** [comment]
Good point.
