### ISSUE TITLE
Unable to build in Ubuntu 12.04

### ISSUE THREAD

**Issue by waterlink** [servo/servo#9262]
Great thanks for this great project!

While running command:

```bash
./mach build -r
```

After some time receiving this error output:

```
Build failed, waiting for other jobs to finish...
failed to run custom build command for `angle v0.1.0 (https://github.com/ecoal95/angle?branch=servo#2c14c35c)`
Process didn't exit successfully: `/home/oleksii/code/src/github.com/waterlink/servo/target/debug/build/angle-ee9dc8911de0d6f3/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:741
```

Searching on the Internet does not yield too much results, and it looks like it is related to Android. So I thought, maybe it tries to build all targets or something like that, and tried to specify target explicitly:

```bash
./mach build --target=x86_64-unknown-linux-gnu --dev
```

Result stays the same. I am out of clues.

--
Kind Regards,
Oleksii

**Comment by jdm** [comment]
@waterlink So apparently https://github.com/ecoal95/angle/blob/servo/build.rs had trouble executing. Do you have `make` installed?

**Comment by waterlink** [comment]
Ah, yep, `make` is missing.

**Comment by waterlink** [comment]
I will try adding `build-essentials` to the VM. Should contain most of the dependencies that might be needed for building.

**Comment by waterlink** [comment]
Ok, now I am getting problems with outdated `g++`. Will try to upgrade to `g++-4.8` from PPA.

**Comment by waterlink** [comment]
@jdm Thank you for your help. I think this concrete issue is resolved.

Do you think it is worth mentioning in the `README.md` that for Debian-based Linuxes you need `build-essential` (in the `apt-get` command) ?

**Comment by jdm** [comment]
Sounds like it!

**Comment by waterlink** [comment]
Additionally, looks like `python-dev` is required too: It was literally telling me that my Python environment is not sane ( :D ), until I have installed `python-dev` and wiped out `python/_virtualenv`.

**Comment by waterlink** [comment]
It was from `mozjs_sys` package

**Comment by waterlink** [comment]
No, I am mistaken, it is something very different. Will try to figure out.

**Comment by waterlink** [comment]
Oh, now I nailed it. In my minimalistic environment there is no `SHELL` environment variable. And `/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mach/mach/mixin/process.py` raises in this case.

**Comment by jdm** [comment]
That's a new one for me :D

**Comment by waterlink** [comment]
Injecting `SHELL=bash` from outside of course helped:

`Build completed in 2524.62s`

(my linux box doesn't have enough RAM apparently, on some packages it was swapping like crazy).

**Comment by waterlink** [comment]
Lets see if `build --release` will work, and how much longer it would be :)
