### ISSUE TITLE
Implement HTMLTableElement.insertRow()

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9269]
Note that the WebIDL definition for the `HTMLTableElement` has changed, so an edit of the WebIDL file is necessary.

Code: `components/script/dom/htmltableelement.rs`, `components/script/dom/webidls/HTMLTableElement.webidl`
Tests: `tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/insertRow-method-01.html`,  `tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/insertRow-method-02.html`
Spec: https://html.spec.whatwg.org/multipage/#dom-table-insertrow, https://html.spec.whatwg.org/multipage/#htmltableelement

Blocks #2968.

**Comment by wenderen** [comment]
This is tagged as blocked-on-external; which PR/issue is it blocked on?

**Comment by KiChjang** [comment]
This requires `HTMLTableElement` to be implemented first. That said, are you interested in implementing that?

**Comment by frewsxcv** [comment]
https://github.com/servo/servo/issues/8084

**Comment by wenderen** [comment]
Interested, yes, available, no :)

**Comment by frewsxcv** [comment]
This is now available since https://github.com/servo/servo/issues/8084 is done.

**Comment by g-k** [comment]
I can give this a shot.

**Comment by jdm** [comment]
Go for it!
