### ISSUE TITLE
Implement console.group() / console.groupEnd() / console.groupCollapsed()

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9274]
Calling `console.group()` and an indentation level to further logs.

For example:

``` js
console.log(1);
console.group()
console.log(2);
console.log(3);
console.group();
console.log(4);
console.log(5);
console.groupEnd();
console.log(6);
console.groupEnd();
console.log(7);
```

will output:

```
1
..2
..3
....4
....5
..6
7
```

See:
- https://developer.mozilla.org/en-US/docs/Web/API/Console/group
- https://developer.mozilla.org/en-US/docs/Web/API/Console/groupEnd
- https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed

**Comment by paulrouget** [comment]
I think this should not be too hard to implement.

Relevant code in: components/script/dom/console.rs (where the `println` call happen).
For the actor code: components/devtools/lib.rs
If I'm not mistaken, the devtools protocol expect just special level values called `group` and `groupEnd`.

**Comment by KiChjang** [comment]
#9276 is an unfinished attempt at this issue.

**Comment by jdm** [comment]
https://console.spec.whatwg.org/#groupcollapsed

This shows up as a source of JS errors in cables.gl content.
