### ISSUE TITLE
Make all interface objects share the same funToString in codegen

### ISSUE THREAD

**Issue by nox** [servo/servo#9280]
We should add a `&'static [u8]` field to the `NonCallbackInterfaceObjectClass` struct and find that at run-time to convert the interface objects to strings.

Files:
 * components/script/dom/bindings/codegen/CodegenRust.py
 * components/script/dom/bindings/interface.rs

**Comment by jdm** [comment]
Any pointers for where to look in CodegenRust? It's a pretty big file :)

**Comment by nox** [comment]
That hook governs how `Node`, `Element`, etc are represented as strings. In our case, it returns something similar to `"function Node() { [ native code ] }"`.

So currently, `CodegenRust.py` generates a different `funToString` hook for every interface we define in `CGClassFunToStringHook`. This needs to go away and instead a single function should be defined in `interface.rs`. We should then refer to it directly in `NonCallbackInterfaceObjectClass::new`.

From that new function of signature `fn(cx: *mut JSContext, obj: HandleObject, _indent: u32) -> *mut JSString`, we need retrieve the `NonCallbackInterfaceObjectClass` associated with `obj` and extract the string representation from a new field on that.

**Comment by vwvww** [comment]
Can I work on this issue?

**Comment by KiChjang** [comment]
Of course!

**Comment by vwvww** [comment]
I started to work on this issue these 2 days(sorry for late) and started my first step with removing FunToStringHook, changing flag funToString have None value. It has to be Some(fun_to_string) which has processed from FunToStringHook, thus now has to be processed from the new function in NonCallbackInterfaceObjectClass.

Am I on the right way?

**Comment by jdm** [comment]
@vwvww That sounds right to me!

**Comment by vwvww** [comment]
@jdm Thanks for the comment! I was busy doing my own work these days, but I think I can work on this issue after a couple of days.

**Comment by nox** [comment]
@vwvww Are you still working on this?

**Comment by nox** [comment]
Unassigning because I got no answer.

**Comment by GuillaumeGomez** [comment]
I take it then. :)

**Comment by GuillaumeGomez** [comment]
> From that new function of signature `fn(cx: *mut JSContext, obj: HandleObject, _indent: u32) -> *mut JSString`, we need retrieve the `NonCallbackInterfaceObjectClass` associated with obj and extract the string representation from a new field on that.

The new field is for the string representation or to find the associated `NonCallbackInterfaceObjectClass`?

**Comment by Ms2ger** [comment]
The new field is for the string representation.
