### ISSUE TITLE
Make all interface objects share the same hasInstance hook in codegen

### ISSUE THREAD

**Issue by nox** [servo/servo#9281]
We should add two `PrototypeList::ID` and `u15` fields to the `NonCallbackInterfaceObjectClass` struct and find that at run-time to check whether a given value is an instance of an interface.

Files:
 * components/script/dom/bindings/codegen/CodegenRust.py
 * components/script/dom/bindings/interface.rs

**Comment by nox** [comment]
@GuillaumeGomez claimed it on IRC.

**Comment by GuillaumeGomez** [comment]
I didn't but I take it. Thanks @nox ;)

**Comment by nox** [comment]
https://github.com/servo/servo/issues/9280#issuecomment-171090820

**Comment by jdm** [comment]
@GuillaumeGomez Is this something you're actively working on or should we return it to the pool?

**Comment by GuillaumeGomez** [comment]
@jdm: Sorry, I wanted to do it the next week-end. However, if this is really urgent, let's return it to the pool.

**Comment by jdm** [comment]
Not urgent! I was just browsing through assigned issues that hadn't been touched in several weeks.

**Comment by nox** [comment]
#9633 landed.
