### ISSUE TITLE
clip: rect(...) only works if the values are comma separated

### ISSUE THREAD

**Issue by glennw** [servo/servo#9283]
But according to https://developer.mozilla.org/en-US/docs/Web/CSS/clip there is a valid syntax without commas.

**Comment by shssoichiro** [comment]
It seems there is a test for this at /css-masking-1_dev/xhtml1print/clip-rect-comma-001.xht, although it fails. The parsing code is around https://github.com/servo/servo/blob/master/components/style/properties.mako.rs#L3162. I don't have any more time to spend on it tonight, especially with my unfamiliarity with servo internals, but this should help point someone in the right direction.

**Comment by mbrubeck** [comment]
Updated source code link:

https://github.com/servo/servo/blob/e4fe0db8fd5f0b5431ba3856b4931613a96e924e/components/style/properties/longhand/effects.mako.rs#L342-L372

Spec: https://www.w3.org/TR/CSS2/visufx.html#value-def-shape

> Authors should separate offset values with commas. User agents must support separation with commas, but may also support separation without commas (but not a combination), because a previous revision of this specification was ambiguous in this respect.

Fixing this will require changing the parse function above to try parsing four whitespace-separated values, if four comma-separated values are not found.

**Comment by SimonSapin** [comment]
I commented in https://github.com/servo/rust-cssparser/issues/105 about how to fix the parsing code for this.

**Comment by mitchhentges** [comment]
Perfect, thanks Simon. I think I can do this one, but no guarantees
