### ISSUE TITLE
Implement NonCallbackInterfaceObjectClass::as_class()

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9287]
The goal here is to encapsulate the `&*(class as *const _ as *const JSClass)` in `create_noncallback_interface_object` into its own method.

Code: `components/script/dom/bindings/interface.rs`

**Comment by nox** [comment]
Good idea.

**Comment by apopiak** [comment]
I'd like to try this one.

**Comment by apopiak** [comment]
The idea is to have a `as_class(ClassType T) --> JSClass` method on `NonCallbackInterfaceObjectClass` ?
