### ISSUE TITLE
Implement WebIDL sequence arguments correctly

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9290]
We do something silly right now with arrays rather than with `Symbol.iterator`, as the spec says.

See https://github.com/servo/rust-mozjs/pull/226, https://github.com/servo/servo/issues/544, https://github.com/servo/servo/pull/9056.

**Comment by frewsxcv** [comment]
cc @ecoal95

**Comment by nox** [comment]
@emilio @frewsxcv Was this fixed in the end?

**Comment by jdm** [comment]
I don't believe so: https://github.com/servo/rust-mozjs/blob/3de4ff3d52361a47a17e3b4fcb02c779b99d93d4/src/conversions.rs#L611-L625 vs. https://heycam.github.io/webidl/#es-sequence

**Comment by saschanaz** [comment]
> I don't believe so: https://github.com/servo/rust-mozjs/blob/3de4ff3d52361a47a17e3b4fcb02c779b99d93d4/src/conversions.rs#L611-L625 vs. https://heycam.github.io/webidl/#es-sequence

That code seems to [internally use `Symbole.iterator`](https://searchfox.org/mozilla-central/rev/171109434c6f2fe086af3b2322839b346a112a99/js/src/vm/ForOfIterator.cpp#54) and also match [the corresponding Gecko code](https://searchfox.org/mozilla-central/rev/171109434c6f2fe086af3b2322839b346a112a99/dom/bindings/Codegen.py#4947-4953).

**Comment by jdm** [comment]
I guess we're done here!
