### ISSUE TITLE
Update XMLHTTPRequest FetchBodyInit

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9291]
The type is actually defined by the Fetch spec [here](https://fetch.spec.whatwg.org/#bodyinit). We'll also potentially have to update the `extract` method implementation as well.

Code: `components/script/dom/xmlhttprequest.rs`, `components/script/dom/webidls/XMLHttpRequest.webidl`
Spec: https://fetch.spec.whatwg.org/#bodyinit, https://fetch.spec.whatwg.org/#concept-bodyinit-extract

**Comment by stspyder** [comment]
Hi, I'd like to try this.

**Comment by KiChjang** [comment]
Yes, feel free to take it! Join us on #servo @ `irc.mozilla.org` if you need any clarafications :)
