### ISSUE TITLE
Profiler doesn't include processing time after reflow.

### ISSUE THREAD

**Issue by sammykim** [servo/servo#930]
I don't think the profiler include time after reflow in every category. I think they are just done profile before reflow. If something is changed and do layout or render again, profiler must include that time.I am sure if profiler caculate each layout and render time again after reflow, it would be much better. 
I guess repaint will be also same situation.

**Comment by mbrubeck** [comment]
This is fixed; the profiler currently tracks ongoing reflows, layouts, paints, etc.
