### ISSUE TITLE
Intermittent failure in /css-transforms-1_dev/html/transform-stacking-003.htm

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#9303]
▶ FAIL [expected PASS] /css-transforms-1_dev/html/transform-stacking-003.htm
      └   → /css-transforms-1_dev/html/transform-stacking-003.htm bc6db1b08c3f157731ed547202681f2337254b8b
    /css-transforms-1_dev/html/reference/transform-lime-square-ref.htm 5da83da5d05208132294353cab921c7cb6923f27
    Testing bc6db1b08c3f157731ed547202681f2337254b8b == 5da83da5d05208132294353cab921c7cb6923f27

**Comment by jdm** [comment]
Could someone look at the the reftest result in http://hoppipolla.co.uk/410/reftest-analyser-structured.xhtml and screenshot it if it's interesting? My internet isn't strong enough to open http://build.servo.org/builders/linux-rel/builds/1455/steps/shell_3/logs/test-css.log/text right now.

**Comment by KiChjang** [comment]
![reftest](https://cloud.githubusercontent.com/assets/3248587/12370325/1d433d66-bbdb-11e5-9286-fab58b61b8d3.png)

**Comment by KiChjang** [comment]
![reftest](https://cloud.githubusercontent.com/assets/3248587/12370376/8f85b7f4-bbdc-11e5-8821-28efec028c19.png)

**Comment by KiChjang** [comment]
Disabled in #9524.
