### ISSUE TITLE
Intermittent failure in /_mozilla/css/iframe/multiple_external.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#9305]

**Comment by jdm** [comment]
My internet can't realistically open http://build.servo.org/builders/mac-rel-wpt/builds/1349/steps/shell_2/logs/test-wpt.log/text right now, so if someone could download the log, open it in http://hoppipolla.co.uk/410/reftest-analyser-structured.xhtml and screenshot the result if it's interesting, that would be useful.

**Comment by ecoal95** [comment]
White image, the reference renders correctly:

![multiple-external](https://cloud.githubusercontent.com/assets/1323194/12315566/a4fc36f0-ba7c-11e5-8237-4a2f5823692d.png)

**Comment by jdm** [comment]
Hasn't been seen in months, not disabled => close.
