### ISSUE TITLE
html style attribute not updated

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9307]
```html
<div style="width:10px">
</div>
<script>
  var div = document.querySelector('div');
  div.style.backgroundColor = "red";
  console.log(div.getAttribute("style"));
</script>
```

This prints `width:10px` instead of `width: 10px; background-color: red;`.

**Comment by paulrouget** [comment]
Supporting this would help a lot debugging browser.html.

**Comment by Ms2ger** [comment]
https://drafts.csswg.org/cssom/#the-elementcssinlinestyle-interface

> Mutating the declarations must set the style content attribute on the context object to the serialization of the declarations.

**Comment by craftytrickster** [comment]
Some observations:

The setting of the styles appears to occur in the `servo/components/script/dom/element.rs` file.

The initial setting of the width `<div style="width:10px">` appears to occur in the `set_attribute_from_parser` method, and the second setting `div.style.backgroundColor = "red";` appears to occur in the `update_inline_style` method.

**Comment by craftytrickster** [comment]
On the **element** struct, why is there `style_attribute` field in addition to the `attrs` field? Is a `style_attribute` not just a type of attr?

I am not sure if this is "robust", but could this be solved by adding a check in the  `get_attribute_by_name` method, by making a special check for name === style, and then appending the inline style attributes to the result as well?

**Comment by Ms2ger** [comment]
I think we'll probably want to update the string any time the style is changed.

**Comment by craftytrickster** [comment]
I have noticed further incorrect results with the implementation of `console.log(div.getAttribute("style"));`.

If you change the original code to include the background declaration twice.
```html
 <div style="width:10px; width: 10px;">
```
In Firefox it will print out the width with only one instance of width. However, in servo, it will actually print out `width:100px; width: 100px;` for the console.log style. 

I suspect that this is due to the fact that `push_new_attribute` is blindly called from `set_attribute_from_parser`. It seems to me that there should be a check to see if the attribute exists, and if it does, it should simply be updated. If there is any recommended way of doing so, it would be good to know.

As for the original problem:
If I comment out the following [code](https://github.com/servo/servo/blob/master/components/script/dom/element.rs#L876) - `self.attrs.borrow_mut().push(JS::from_rooted(&attr));` the style changes on the screen seem to be fine, but the style string returned by `div.getAttribute("style")` is null instead of `width: 10px;`. 

In `update_inline_style` (which is called by `div.style.backgroundColor = "red";`), there is no code that appends the self.attrs. It seems that this is why the string is not being updated in OP's example. But, given the problem of blindingly appending the string above, I feel reluctant to append self.attrs, every time this is called. If the same inline style is updated multiple times, doing so would needless bloat self.atrrs. That is why I suggested doing my special check of `special check for name === style` on get_attribute_by_name, in order to avoid the inline update. 

@Ms2ger Please let me know what you think.

**Comment by nox** [comment]
I'm 99% sure the spec requires the actual attribute value to be preserved when getting it, with duplicate entries and whatnot.

**Comment by paulrouget** [comment]
> In Firefox it will print out the width with only one instance of width. However, in servo, it will actually print out width:100px; width: 100px; for the console.log style

Servo just doesn't update the attribute. Ever. So it just doesn't change the original string.
Firefox applies the property, and pretty print it as `width: 100px`.

**Comment by paulrouget** [comment]
This is needed to fix #9377. @craftytrickster, are you planning to work on a PR?

**Comment by nox** [comment]
> In Firefox it will print out the width with only one instance of width. However, in servo, it will actually print out width:100px; width: 100px; for the console.log style.

I think you are wrong.

```js
var div = document.createElement('div');
div.setAttribute("style", "width: 100px; width: 100px; ");
console.log(div.getAttribute("style"));
```

**Comment by nox** [comment]
Oh, I just now understood thanks to @paulrouget that you were still referring to the original snippet where we change properties on CSSStyleDeclaration. Never mind me.

The method `set_attribute_from_parser` is still irrelevant to the problem we have here, though.

**Comment by craftytrickster** [comment]
I would like to work on a PR, maybe tonight if I have some time. I am not sure what the correct thing to do here is, my initial guess would be to edit the update_inline_style method, perhaps converting the PropertyDeclaration field to an Attr, and then do something like `self.attrs.push(convertedPropertyDeclaration)`. As mentioned in my example above where I commented out code, the self.attrs seems to be what drives the result string from `console.log(div.getAttribute("style"))`.
The complication here is that I do not see any easy way to do the PropertyDeclaration -> Attr conversion offhand, but I am definitely open to suggestions.

**Comment by nox** [comment]
@craftytrickster Of course self.attrs is what drives the result of getAttribute. The attribute should be appropriately updated when the corresponding CSSStyleDeclaration value is changed, as the spec mandates.

**Comment by nox** [comment]
https://drafts.csswg.org/cssom/#the-elementcssinlinestyle-interface

> declarations: The result of parsing the style content attribute, in specified order. If the style content attribute is absent, the object represents an empty list of CSS declarations. Mutating the declarations must set the style content attribute on the context object to the serialization of the declarations. If the style content attribute is set, changed or removed, the declarations must be updated as appropriate.

**Comment by craftytrickster** [comment]
@nox Thanks for the information.

**Comment by craftytrickster** [comment]
Sorry if I am taking a while on this, I'm still unfamiliar with a lot of this code. I wanted to know if the below approach to setting the attrs from the `update_inline_style` is marginally correct:

```rust
pub fn update_inline_style(&self,
                               property_decl: PropertyDeclaration,
                               style_priority: StylePriority) {
     // new code below
      let style_to_append = format!("{}: {};", property_decl.name(), property_decl.value());
       match self.attrs.borrow().iter().find(|a| a.name() == &atom!("style")) {
           Some(attr) =>  {
               // how do I get the old value so I can append the new value to it?
               let new_value = AttrValue::String(DOMString::from(style_to_append));
               attr.set_value(new_value, self);
           }
           None => {
               // append new style object to attrs with Attr::new(....)
           }
       }

```

If it is correct, I have been stuck trying to figure out how to get the old value of the existing style object. Even if I do get it, is it really the right thing to do to use AttrValue::String, as opposed to its other enum forms? Any advice would be helpful, thanks.

**Comment by nox** [comment]
I'm not sure I understand what you want to append. Just serialise the declarations and set the `style` attribute on the element with the result of the serialisation, no?

**Comment by craftytrickster** [comment]
If I just serialize the declarations and set the style, wouldn't  it wipe out the style created from parsing the initial html?

`set_attribute_from_parser` already sets the style attribute to `width:10px;` before the updating inline style occurs. Therefore, if I just try to set the style attribute within `update_inline_style`, it will clobber the `width: 10px;`, leaving only `background-color: red;`.

**Comment by paulrouget** [comment]
Doesn't `update_inline_style` just append styles or update existing value? You won't lose the `width:10px` declaration, right?

I'm not sure, but here is how I would do it: in `remove_inline_style_property`, `update_inline_style` and `set_inline_style_property_priority`, call a function that sync `style_attribute` with the actual style attribute (in `attrs`), and remove the calls to `document.content_changed` in `cssstyledeclaration.rs` (DOM mutations will take care of that).

Does it make sense?

**Comment by craftytrickster** [comment]
I guess my confusion stems from the fact that the inline_style functions have their own separate `self.style_attribute` field which is different from the normal `self.attrs` which also contains its own style attribute instance (being pushed by `set_attribute_from_parser`). 

When you say *sync*, I'm assuming that you mean take the value from style_attribute and then use it to modify the instance in `self.attrs`, to reflect the changes, is that correct? I was trying to demonstrate something like that in my pseudo-code above, but I was having trouble implementing it.

**Comment by paulrouget** [comment]
> is that correct

Yes.

**Comment by craftytrickster** [comment]
I've taken an initial pass (WIP) at this in my branch [here](https://github.com/craftytrickster/servo/commit/2ac7708947da0011fd7c768c2b382237e5243e66), and superficially it seems to work, as it is able to append the style names as expected. However, the else branch of my if statement always causes a panic (reachable if you delete the style attribute in the html directly, 
div **style="width:10px"**). 

I have included the text of the panic as a comment on the branch. I have so far been unable to determine the cause, if I eventually do, I can clean up the code and also take into account `remove_inline_style_property`. In the meantime, if someone sees a clear reason for the panic, it would be helpful to know.

**Comment by nox** [comment]
@craftytrickster Your code panics because you try to mutably-borrow `self.attrs` while you have already borrowed it.

On another note, as stated earlier, you should not append anything to the style attribute, you should instead set it to the serialised CSSStyleDeclaration instance.

**Comment by craftytrickster** [comment]
I was able to achieve the results of this issue using regex to modify the existing attrs style instance, but it is was just a temporary approach to see if it would work. @nox, as suggested, I will try to replace the unstructured regex approach with using the CSSStyleDeclaration methods.

**Comment by craftytrickster** [comment]
@nox, after taking a look, I do not see anything on the cssstyledeclaration.rs file that would help with this issue, which is to synchronize `element.style_attribute` with the *style-attr* from`element.attrs`.
