### ISSUE TITLE
unexpected overflow with display:inline-block + margin

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9308]
![rggdhwjnub](https://cloud.githubusercontent.com/assets/373579/12318298/943e6f14-ba99-11e5-85c6-b427a37067b9.gif)

The following example makes the body element scrollable. The extra area is apparently directly related to the margin value.

Note: using `block` instead of `inline-block` reduces the scrollable area, but it's still possible to scroll.

```html
<div style="left: 0px; bottom: 0px; position: absolute;">
  <div style="margin: 200px; display: inline-block; background: red">foobar</div>
</div>
```

**Comment by pcwalton** [comment]
Smaller test case:

    <!DOCTYPE html>
    hello

Shouldn't scroll.

The problem goes away if margins on the document element are set to zero.
