### ISSUE TITLE
(WebRender) Resizing Browser.html window creates artefacts

### ISSUE THREAD

**Issue by gordonbrander** [servo/servo#9324]
**Edit:** see https://github.com/servo/servo/issues/9324#issuecomment-176019795

Resizing the window will crash Servo when running a WebRender build in Browser.html mode (`-w -b --pref dom.mozbrowser.enabled http://localhost:6060`).

cc @metajack

**Comment by frewsxcv** [comment]
https://github.com/glennw/servo/pull/21

**Comment by paulrouget** [comment]
Resizing doesn't crash anymore, but the resized area looks funny.

<img width="300" alt="screen shot 2016-01-28 at 07 53 17" src="https://cloud.githubusercontent.com/assets/373579/12637278/3987c0c4-c594-11e5-8496-8f3792fd8e17.png">

**Comment by glennw** [comment]
Fixed by https://github.com/glennw/webrender/commit/b21317a8fb69d43c00e14f7d1503919aef78abbb
