### ISSUE TITLE
Implement console#time and console#timeEnd methods

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#9325]
https://developer.mozilla.org/en-US/docs/Web/API/Console#Timers

An effort to implement this was started in https://github.com/servo/servo/pull/6646, but wasn't completed

**Comment by shssoichiro** [comment]
I'd like to work on this, since no one has claimed it yet.

**Comment by KiChjang** [comment]
Alright!

**Comment by shssoichiro** [comment]
Are there tests implemented for the other console methods? (And if so, where are they located?)

**Comment by paulrouget** [comment]
> Are there tests implemented for the other console methods?

I don't think so.

**Comment by paulrouget** [comment]
Maybe you can create a new directory: tests/wpt/mozilla/tests/mozilla/console or tests/wpt/mozilla/tests/mozilla/devtools

**Comment by jdm** [comment]
There is no way to write a WPT test for console methods, unfortunately. We also can't write tests for the console integration with the devtools server until #5971 is complete, so only manual testing is possible right now.

**Comment by shssoichiro** [comment]
All right. I didn't worry about writing WPT tests for now and just did manual testing.

In the early return cases, I was unsure if we wanted to log this with `println!` or display any sort of message to the user (behavior in these cases is undocumented). I left these cases empty for now.
