### ISSUE TITLE
(WebRender) scrolling iframe results in all other tiles being moved

### ISSUE THREAD

**Issue by gordonbrander** [servo/servo#9326]
Here's a video: https://gfycat.com/FaintGrotesqueDegus. This was recorded in Browser.html on a WebRender build.

Some things to know about this webapp:

- The iframe is scrollable. The body is not.
- The window title bar at the top that scrolls offscreen is not attached to the iframe in any way. It's an absolutely positioned element pinned to the top of the `body`.
- The `+` button in the corner is part of the UI and is supposed to stay fixed in the corner as the iframe scrolls.
- Likewise, the sidebar that appears midway through the video is an element that has been translated out of the viewport.

**Comment by glennw** [comment]
The new iframe scrolling code doesn't have support for picking which is the right layer to scroll yet - I'll be adding this in the next couple of days which will sort this problem.

**Comment by glennw** [comment]
@gordonbrander I've added a quick fix for position: fixed layers (which may well be enough for this bug?). I'll be working on a proper fix for when there are multiple valid scroll roots present next.

**Comment by glennw** [comment]
@gordonbrander I believe this is fixed now - could you close if it's all working fine next time you build against WR?

**Comment by paulrouget** [comment]
This is not webrender specific afaik.

The UI moving with the iframe is a set of bugs. See the "scrolling the page scrolls the UI" bugs in https://github.com/mozilla/browser.html/issues/562.

- servo/servo#9306
- servo/servo#9308
- servo/servo#9309

There is one more I haven't identified yet.

You can close this issue.
