### ISSUE TITLE
DOMContentLoaded event should be trusted

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9332]
Blocks #2968.

* Spec: <https://html.spec.whatwg.org/multipage/#the-end>.
* Code: `components/script/dom/document.rs`.
* Test: `html/syntax/parsing/the-end.html`.

**Comment by KiChjang** [comment]
This means instead of calling `DispatchEvent` directly, we should use `fire_event` by upcasting the document into an `EventTarget`.
