### ISSUE TITLE
Implement document.domain 

### ISSUE THREAD

**Issue by DavidBruant** [servo/servo#934]
This is related to #633.
document.domain changes the origin of a document. Any current and coming optimizations based on the assumption that the origin of a document not changing over time like the recent [Make sandboxed iframes run with different script tasks](https://github.com/mozilla/servo/commit/96403247218ce628a39b954c361d0707d0d0f97d) may require removing these optimizations later.

For that reason, I feel it'd be important to implement document.domain early and start using it in Servo tests to make sure Servo is actually running the web and not an idealized version

For the specific case of sandbox iframes and document.domain, it's been discussed [in standards](https://www.w3.org/Bugs/Public/show_bug.cgi?id=23040), there was agreement among the few who participated in the discussion and a solution has been [implemented in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=907892) (poison document.domain setter in sandboxed iframes regardless of `allow-same-origin`).
Assuming this sticks, this particular optimization will remain.

**Comment by frewsxcv** [comment]
Visiting for triage: as of today, this is still not done

https://github.com/servo/servo/blob/a1cd27e6a3b961129fd4710513cc29e4f7c9cc67/components/script/dom/webidls/Document.webidl#L78

**Comment by mbrubeck** [comment]
Fixed by #8655.

**Comment by samlh** [comment]
I think the document.domain setter is still missing.

**Comment by asajeffrey** [comment]
Some discussion on IRC with @bzbarsky that's relevant to mutating `document.domain`: http://logs.glob.uno/?c=mozilla%23servo&s=6+Jan+2017&e=6+Jan+2017#c588833. See #14892.

**Comment by asajeffrey** [comment]
A first-cut implementation for the setter: https://github.com/asajeffrey/servo/commit/7aaa5c634fb87afcbc7f7122649203c17650e3ef

**Comment by asajeffrey** [comment]
A PR for the setter: #15536.
