### ISSUE TITLE
Change some of the private types to public

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#9347]
There are a few public methods in `components/compositing/compositor.rs`, `components/gfx/platform/freetype/font_context.rs` and `components/devtools` which return a private type, and so they show warnings during the build. We should make such types public.

**Comment by mattkuo** [comment]
I'd like to take a shot at this

**Comment by Wafflespeanut** [comment]
Go ahead!

**Comment by mattkuo** [comment]
By the way, `components/gfx/platform/freetype/font_context.rs` did not generate any warnings for me. Let me know if you are still getting warnings from that file.
