### ISSUE TITLE
Document the need to fix up virtualenv after upgrading Python

### ISSUE THREAD

**Issue by jsanders** [servo/servo#9356]
I was unable to build servo after upgrading my version of Python using homebrew. This was the error:

```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/james/Code/servo/python/_virtualenv/bin/python2.7
  Reason: image not found
```

([full output](https://gist.github.com/jsanders/8e443f4c0b83b80d276e))

After going down a couple rabbit holes, the solution that worked for me was to delete servo's `python/_virtualenv` directory. This wasn't very obvious, so I think it would make sense to document it somewhere. I started adding it to the Prerequisites section of the readme, but I wasn't sure that was the right place, so I'm filing this issue instead. If someone has a good idea for where this should go, I can write it up.

**Comment by mrobinson** [comment]
I think that the virtual environment is specific to the Python version now, so hopefully this shouldn't be an issue any longer.
