### ISSUE TITLE
Add tests for exercising XHR.send(data) method

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9357]
New tests should live under `tests/wpt/mozilla/tests/mozilla`. We'll need to feed in the `.send()` method with different types of data that we currently support, namely `USVString`s, `URLSearchParams` and `Blob`s.

Spec: https://xhr.spec.whatwg.org/#the-send%28%29-method

**Comment by jdm** [comment]
There's a bunch of test coverage already:
tests/wpt/web-platform-tests/XMLHttpRequest/send-data-(arraybuffer|blob|es-object|formdata|unexected-string).htm
What in particular are we looking to expand here?

**Comment by KiChjang** [comment]
It's to test data we feed into the `send()` method, particularly the ones that fit into `BodyInit`.

**Comment by jdm** [comment]
I believe the blob test that already exists fails because it also relies on support for the blob response type.

**Comment by KiChjang** [comment]
In that case, let's close this issue since it's not applicable anymore.

**Comment by Ms2ger** [comment]
Even if so, we don't have CI coverage.

**Comment by jdm** [comment]
I propose we duplicate the tests listed above into `tests/wpt/mozilla/tests/mozilla/` and modify them to not set the responseType property, then compare the resulting response against a string.

**Comment by danlrobertson** [comment]
I'll take a crack at this

**Comment by KiChjang** [comment]
That'd be super nice!
