### ISSUE TITLE
Catch segfaults on builders and report backtraces with symbols

### ISSUE THREAD

**Issue by jdm** [servo/servo#9371]
Firefox does this, but I'm not certain what it entails. Maybe it's via the breakpad signal handler that writes out minidumps and then the test harness reads that? Our debugging info with RUST_BACKTRACE=1 is great, but we have zero visibility into actual crashes.

cc @metajack @larsbergstrom

**Comment by Ms2ger** [comment]
CC @luser

**Comment by luser** [comment]
Yes, we use Breakpad to write minidumps, and test harnesses look for minidumps and print out stacks using the mozcrash module + a minidump_stackwalk binary.

This is what the harness bit of that looks like in Mochitest:
https://dxr.mozilla.org/mozilla-central/rev/8cb42e7a16b42162c9930f37b9e1f820c2eb126b/testing/mochitest/runtests.py#2019

**Comment by jdm** [comment]
I wonder how well signal handlers work with Rust programs? I just stumbled across http://neugierig.org/software/blog/2012/06/backtraces.html and it might be enough to get us useful information without having to deal with the whole breakpad situation.
