### ISSUE TITLE
Add support for mozbrowserconnected

### ISSUE THREAD

**Issue by gordonbrander** [servo/servo#9382]
cc @paulrouget 

Filing this for reference. It's not a high-priority problem for us at the moment, but in order to support an accurate progress bar in Browser.html, we'll need to add the `MozBrowserLoadProgressChange` event to Servo. This event is part of the [MozBrowser](https://developer.mozilla.org/en-US/docs/Web/API/Using_the_Browser_API) API.

Edit: we want to support `mozbrowserconnected`. See https://github.com/servo/servo/issues/9382#issuecomment-174144068.

**Comment by shssoichiro** [comment]
I began looking into this. Is `MozBrowserLoadProgressChange` an entirely new event in the MozBrowser API? It doesn't appear to be documented.

If it is new, I presume there should be a progress percentage accessible via `event.details.progress` or similar?

**Comment by paulrouget** [comment]
This has been backed out from Gecko. You can find the details here: https://bugzilla.mozilla.org/show_bug.cgi?id=1125713

Firing a `mozbrowserprogresschange` event might be too expensive though.

What we actually want is a new event (`mozbrowserconnected`?) between `mozbrowserloadstart` and `mozbrowserloadend` that tells us when the server has been successfully reached.

Maybe something fired in `ScriptThread::load`.

@gordonbrander Can you confirm? Or if we really want a `mozbrowserprogresschange` event, maybe we can find a way to send this information in a more efficient way.

**Comment by gordonbrander** [comment]
> What we actually want is a new event (mozbrowserconnected?) between mozbrowserloadstart and mozbrowserloadend that tells us when the server has been successfully reached.
> 
> Maybe something fired in ScriptThread::load.
> 

@paulrouget I think mozbrowserconnected is enough. What info would progress event actually be giving us? My understanding is the browser doesn't know the actual payload size so any percentage must be faked?

**Comment by paulrouget** [comment]
> My understanding is the browser doesn't know the actual payload size so any percentage must be faked?

Right.

So let's go for `mozbrowserconnected`.
