### ISSUE TITLE
Name BodyInit is not preserved

### ISSUE THREAD

**Issue by psdh** [servo/servo#9384]
[`BodyInit`](https://github.com/servo/servo/blob/master/components/script/dom/webidls/XMLHttpRequest.webidl#L17) should be usable as `use dom::bindings::codegen::UnionTypes::BodyInit;`

**Comment by KiChjang** [comment]
@psdh is working on this.

**Comment by psdh** [comment]
Could someone please check if I am headed the correct way ^. I have facing issues with `EventHandlerNonNullOrNull`
