### ISSUE TITLE
Implement WebBluetooth in Servo

### ISSUE THREAD

**Issue by dati91** [servo/servo#9392]
The WebBluetooth API ( https://webbluetoothcg.github.io/web-bluetooth/ ) is currently missing,
so I started working on it. It is very experimental, but the chromium folks already working on it as well.
The current implementation status of WebBluetooth can be found here: https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md
( Servo is not listed yet. )

The first blocker issue is #4282 (missing the Promise)

**Comment by Ms2ger** [comment]
I am not certain we should accept code for this API.

**Comment by jdm** [comment]
@Ms2ger Please elaborate.

**Comment by larsbergstrom** [comment]
FYI, we have a team at the University of Szeged who are planning to work on this. We've been collaborating with the Firefox Bluetooth team on which spec(s) to implement, how to hook up to the underlying bluetooth libraries, etc.

**Comment by dati91** [comment]
Yes, we will constantly update our progress. And there will be a link to our branch soon.

**Comment by larsbergstrom** [comment]
@dati91 Sorry I didn't recognize your username, Attila! I've only talked with @akiss77 and @loki04 to date :-)

**Comment by dati91** [comment]
We will use this repository: https://github.com/szeged/servo

**Comment by Jayflux** [comment]
Should this be marked as assigned then?

**Comment by jdm** [comment]
@Jayflux Generally it's less important to mark issues that aren't in the categories with high-visibility (and/or surfaced by tools like http://servo.github.io/servo-starters/).

**Comment by Ms2ger** [comment]
Given that this api is full of promises, I'm somewhat confused how that's going to be dealt with.

**Comment by larsbergstrom** [comment]
@Ms2ger This work depends on https://bugzilla.mozilla.org/show_bug.cgi?id=911216 landing and then picking up an smup. We are coordinating with the people working on that :-)

**Comment by dati91** [comment]
A quick update:
The first part of the implementation landed: https://github.com/servo/servo/commit/e7d70cfabf5ad412045fd4088379afd1bedfaece

The low level bluetooth api code can be found here: https://github.com/servo/devices

Currently working on the middle layer (ipc_channel) communication which will connect the two: https://github.com/szeged/servo/tree/bluetooth-ipc

**Comment by dati91** [comment]
Depends on: https://github.com/servo/servo/issues/10072 ( https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothdevice-uuids )

**Comment by larsbergstrom** [comment]
Note that #10081 will make this feature not web-visible by default and will require passing a commandline argument to enable it.

**Comment by g-ortuno** [comment]
dati91: I don't think it's necessarily a blocker. Chromium doesn't implement it yet either so we just use an [array](
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/modules/bluetooth/BluetoothDevice.idl&sq=package:chromium&type=cs&l=32).

**Comment by nox** [comment]
NEWS AT 11: WAS DONE MONTHS AGO YAY
