### ISSUE TITLE
HTML5 Details element UI

### ISSUE THREAD

**Issue by MonsieurLanza** [servo/servo#9395]
HTMLDetailsElement interface is here but we have no UI for it. 

spec : https://html.spec.whatwg.org/multipage/forms.html#the-details-element

I first thought implement the "show/hide" behavior with CSS but this won't permit to pass the details test on https://html5test.com/ as it relies on hiding a text node, and AFAIK, CSS selectors cannot target text nodes.

Also we have to provide a way to let the user toggle the element (and let him know that there is something to toggle).

**Comment by notriddle** [comment]
:hand: I'd like to take it.

**Comment by KiChjang** [comment]
Sure thing!

**Comment by jdm** [comment]
Fixed by #73.
