### ISSUE TITLE
Use .find().map() instead of .filter_map().next() in URLSearchParams::Get

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9403]
There really isn't any reason to use `.filter_map().next()` when there is `.find()`

Code: `components/script/dom/urlsearchparams.rs`
Documentation: https://doc.rust-lang.org/nightly/core/iter/trait.Iterator.html#method.find

**Comment by nox** [comment]
`filter_map().next()` takes a `FnMut(Self::Item) -> Option<U>` and returns an `Option<U>`, `find()` takes a `FnMut(&Self::Item) -> bool` and returns an `Option<&Self::Item>`. Not the same thing at all.

**Comment by Ms2ger** [comment]
We'll need a `.map(...)` after it, but this still seems like an improvement.

**Comment by nox** [comment]
Still need to unpack the key/value tuple by hand, so not *that* nicer.

**Comment by nox** [comment]
I would rather abstract the filter_map call out of Get and GetAll in a private method and use that in both.

**Comment by KiChjang** [comment]
I prefer seeing a one-line `.find( |stuff| stuff.0 == cond).map( |stuff| stuff.1 )` over what we currently have right now, which spans multiple lines and is unnecessarily bloated.

**Comment by nox** [comment]
@KiChjang I concede that.

**Comment by fstr** [comment]
I would like to do this

**Comment by jdm** [comment]
Go for it! Let us know if you have any questions!

**Comment by fstr** [comment]
I hope I got it correct with the double reference.

Not sure about the beauty of the resulting code and if anything can be omitted.

**Comment by KiChjang** [comment]
Fixed in #9436
