### ISSUE TITLE
Don't generate empty FooConstants modules

### ISSUE THREAD

**Issue by nox** [servo/servo#9411]
For each `WebIDL` interface `Foo`, a module `FooConstants` is generated in their corresponding `FooBinding` module, even if there were no constants defined in that interface.

It should be generated only if needed.

The relevant code is in `CGDescriptor.__init__` in components/script/dom/bindings/codegen/CodegenRust.py. Look for the `CGConstant` call in that function.

**Comment by timvandermeij** [comment]
I think this can be closed thanks to #9430.
