### ISSUE TITLE
Move ConstantSpec, NonNullJSNative and define_constants from utils to interface

### ISSUE THREAD

**Issue by nox** [servo/servo#9412]
These are only used in `script::dom::bindings::interface`.

Files:
 * components/script/dom/bindings/interface.rs
 * components/script/dom/bindings/utils.rs

**Comment by nxnfufunezn** [comment]
taking this...

**Comment by nxnfufunezn** [comment]
@nox What about this file https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py#L5361

**Comment by nxnfufunezn** [comment]
I updated that file..
