### ISSUE TITLE
Replace SendParam with BodyInit

### ISSUE THREAD

**Issue by psdh** [servo/servo#9433]
Once #9419 lands, we'll generate typedefs correctly (from webidls)
Thus we can use `BodyInit` (type: `BlobOrStringOrURLSearchParams`) instead of `SendParam` 

relevant code: `components/script/dom/xmlhttprequest.rs`

**Comment by KiChjang** [comment]
#9419 has landed.

**Comment by Jayflux** [comment]
@psdh this can be marked as assigned

**Comment by KiChjang** [comment]
See #9433 for an unfinished attempt.

**Comment by canaltinova** [comment]
Is someone working on this issue? If no, I would like to work on this.

**Comment by jdm** [comment]
Please do!
