### ISSUE TITLE
Mach path setup is broken for environments with multirust installed

### ISSUE THREAD

**Issue by jdm** [servo/servo#9437]
https://github.com/servo/servo/pull/9415 changed the PATH modifications to append instead of prepend, and multirust installs /usr/local/bin/cargo. I can't build Servo locally on OS X because the wrong binaries get used now.

cc @adamncasey

**Comment by jdm** [comment]
Was this an intentional change? Why?

**Comment by larsbergstrom** [comment]
Sorry I missed this change in the review!

**Comment by adamncasey** [comment]
Sorry! It was an intentional change, appending was causing problems. But I didn't know it would cause problems for other setups.

I'll look into it now, there must be a better solution.

I'll put in a PR to fix this for multirust, then I can look into the other problems separately.

**Comment by timvandermeij** [comment]
This can be closed after #9440.
