### ISSUE TITLE
Synchronous image loading in -x and -o arguments destroys performance

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#9441]
In components/layout/context.rs, we currently switch to synchronous image loading if the `-x` or `-o` flags have been passed. Unfortunately, this not only blocks selector matching, but causes a huge set of overall performance regressions, including destroying any parallel speedups.

Ideally, what we'd do instead is:
- Always do async loading, as normal
- If we're doing shutdown after load, ensure that page load also checks that all images have been loaded, the restyle has happened, and any required graphics changes have been composited.

**Comment by Ms2ger** [comment]
The correct way to fix is this is implementing the spec's requirement:
> Fetching the image must delay the load event of the element's node document until the task that is queued by the networking task source once the resource has been fetched (defined below) has been run. 

Not sure how hard it'd be to do that right now. CC @jdm.

**Comment by jdm** [comment]
My strategy for solving that is to implement the plans in https://github.com/servo/servo/wiki/Image-load-conformance-student-project . Basically, move the network load from the image cache and into the script thread where it belongs.

**Comment by jdm** [comment]
We no longer do synchronous image loading.
