### ISSUE TITLE
Windows build fails with a space in the pathname

### ISSUE THREAD

**Issue by UK992** [servo/servo#9442]
I can't build Servo on Windows 10, keep throwing this error:

``` 
unable to get packages from source

Caused by:
  Failed to unpack package `servo-skia v0.20130412.3`

Caused by:
  The system cannot find the path specified. (os error 3)
```

**Comment by larsbergstrom** [comment]
@UK992 Hrm, I haven't seen this before! Are you running `./mach build` from within a MINGW64 window, as described in the readme?

CC'ing @Jayflux and @adamncasey in case they've seen this before.

**Comment by jdm** [comment]
@larsbergstrom Any chance you have a local cargo override for skia that didn't end up getting published?

**Comment by larsbergstrom** [comment]
@jdm Nope, everything's clean & committed and we've verified on multiple other machines (jay, adam, and vlad).

**Comment by UK992** [comment]
@larsbergstrom yes, i used MINGW64.
This error is present when i try to build Servo in `C:\msys64\home\<username>\servo`.
Now I'm building Servo in `C:\servo` and no error in skia package. Weird.

**Comment by adamncasey** [comment]
I haven't seen that error before.

Strange. I'm building in `C:\msys64\home\<username>\servo`

**Comment by larsbergstrom** [comment]
@UK992 does `<username>` have any spaces or other "interesting" characters in it?

**Comment by UK992** [comment]
@larsbergstrom It have spaces.

**Comment by adamncasey** [comment]
Just tried building servo in a directory with spaces and an error as well, though a different error.

```
$ pwd
/home/Adam/test test/servo

$ ./mach build -d
New python executable in C:/msys64/home/Adam/test test/servo/python/_virtualenv/bin/python2.7.exe
Not overwriting existing python script C:/msys64/home/Adam/test test/servo/python/_virtualenv/bin/python.exe (you must use C:/msys64/home/Adam/test test/servo/python/_virtualenv/bin/python2.7.exe)
ERROR: The executable "C:/msys64/home/Adam/test test/servo/python/_virtualenv/bin/python2.7.exe" could not be run: [Error 5] Access is denied
Running virtualenv with interpreter C:\msys64\mingw64\bin/python2.7.exe
Python virtualenv failed to execute properly.
```

**Comment by larsbergstrom** [comment]
I think we should probably have `mach` ensure the directory doesn't have a space in it, at least on Windows :-)

**Comment by UK992** [comment]
I removed spaces from username and is now a successfully build Servo in `C:\msys64\home\`. :)

**Comment by KiChjang** [comment]
Can this issue be closed? Or do we still need a patch for `mach` to make sure we don't have spaces in a directory?

**Comment by larsbergstrom** [comment]
@KiChjang Yeah, I'd like to see a patch that fixes that issue. I've edited the issue.

The work here is to have `mach` check the path to see if there are any spaces in the pathname and generate an error if so.

**Comment by jdm** [comment]
Relevant code: `python/servo/build_commands.py` in the `build` method

**Comment by drbo** [comment]
Relying on access to a path with spaces is not a good idea on Windows, where usernames often have spaces.  I think that `mach` should be able to build & execute Servo in a path containing spaces.

**Comment by larsbergstrom** [comment]
@drbo Certainly, I'd be open to another (definitely *not* `E-easy`) issue to get paths with spaces working on Windows. However, for this issue, since we do not currently support paths with spaces, I'd like to have a clear error message in place until someone has time to look at paths with spaces.

**Comment by vishy1618** [comment]
I'd like to give this a try, if no one else is working on this.

**Comment by KiChjang** [comment]
Go for it!

**Comment by JohnAlexCO** [comment]
By default, at least to my understanding, usernames on Win10 are just firstname + space + lastname, so "just hope there's not space in the username" doesn't seem like a reasonable approach to this problem.
