### ISSUE TITLE
Update the canvas webidl to match the spec

### ISSUE THREAD

**Issue by jdm** [servo/servo#9443]
Our `CanvasRenderingContext2D.webidl` is based on an older revision before the spec started grouping related APIs together in different interfaces. We should update it to match [the spec](https://html.spec.whatwg.org/multipage/scripting.html#2dcontext) more closely. There should be no functional change and everything should keep compiling exactly as it does today. Some features like `Exposed=(Window,Worker)` will need to be commented out because we don't support them yet.

Code: `components/script/dom/webidls/CanvasRenderingContext2D.webidl`
Spec: https://html.spec.whatwg.org/multipage/scripting.html#2dcontext

**Comment by J2R5M3** [comment]
Looking to get involved, this would be my first contribution to open source anything,ever.

Don't really know where to start so a welcome shove off the correct cliff would be appreciated, I'll find a parachute on the way down.

On a side note I've been have some issues compiling the source : 
`error: linking with `cc` failed: exit code: 1`
"lots of noise"
then 
``` 
note: /usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
```
Done a fair bit of googling but haven't really been able to find much.

**Comment by jdm** [comment]
@J2R5M3 Welcome! It appears you're missing a dependency, and presumably you're not on a debian-based linux as that would be covered by the "libegl1-mesa-dev" in README.md. You may want to try installing "mesa-libEGL-devel" if you're on Fedora? Hard to give better suggestions without more information.

As for how to get started, this is really about cleaning up the contents of the webidl file I linked in the original description to match the [WebIDL](http://heycam.github.io/webidl/) interfaces that are present in the specification that's also linked previously. Does that help at all?

**Comment by J2R5M3** [comment]
mostly, just was wondering about any sources I could reference regarding which features are supported and which aren't

**Comment by jdm** [comment]
All I can recommend is to use the existing webidl files as reference (ie. note what is already commented out).

**Comment by gmalecha** [comment]
Has this bug been claimed?

**Comment by nox** [comment]
@gmalecha It seems @J2R5M3 started looking at it.

@J2R5M3 Do you need help with this?

**Comment by J2R5M3** [comment]
@gmalecha I've been kinda swamped with a wave of assignments for school and work, if you want to lend a hand or even take over that's perfectly fine with me, I had hoped to get involved but it is the case that my current schedule can't handle anything additional right now at least for the next 4-5 days, priorities and such.

**Comment by gmalecha** [comment]
@J2R5M3 I'm happy to let you take care of it. Should it be marked assigned?

**Comment by KiChjang** [comment]
Okay, just let us know of any updates!

**Comment by krstoff** [comment]
This has been left idle for about a month and I would like to try fixing it. Any objections?

**Comment by KiChjang** [comment]
Since @J2R5M3 doesn't seem to be active lately, I think you can go ahead and work on this issue @krstoff.

**Comment by gmalecha** [comment]
I believe that I already have an implementation of it (though it is about a month old now). I can update it to the latest code and see if it still works.

**Comment by krstoff** [comment]
Okay, never mind then. :) Let me know if anything changes @gmalecha

**Comment by KiChjang** [comment]
@gmalecha Are you planning to make a PR for this issue? If not, then @krstoff can go ahead and work on this.
