### ISSUE TITLE
Blank gray or white window, and flickering on resize (on Linux)

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#9451]
#9339 (glutin upgrade) caused a regression on Linux/X11.  The Servo window always shows only gray or white on startup.  During resizing, the page content may briefly flicker into view, but then the window usually goes blank again after resizing.

Reverting tomaka/glutin#690 fixes this issue.

**Comment by KiChjang** [comment]
I also noticed that when the page content does go into view, pausing your mouse actions actually make the page content stay, but moving the cursor causes flickering again.

**Comment by KiChjang** [comment]
Also, this only happens when Linux is booted up from bare metal - having Linux in a VM doesn't seem to cause this issue.

**Comment by glennw** [comment]
I suspect this is because the default pixel format looks to have changed from double -> single buffering. Let's try init glutin with double buffering enabled in Servo and see if it fixes the problem.
