### ISSUE TITLE
Ensure the value attribute for HTMLInputElement matches the spec

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9455]
#9407 uncovered the fact that our current implementation does not match the behaviour outlined by the spec. It also discovered that whenever the value attribute is removed by the `RemoveAttribute` method on an `HTMLElement`, the `HTMLInputElement` is not notified of the changes, since there are actually two containers for the value attribute - one is the `attrs` field in the `Element` struct, and the other `textinput` field in the `HTMLInputElement` struct. This may or may not be intentional, as the spec defines different modes that the value attribute can be in, yet currently our implementation does not implement the concept of these modes.

Code: `components/script/dom/htmlinputelement.rs`
Spec: https://html.spec.whatwg.org/multipage/forms.html#dom-input-value
Test: `tests/wpt/web-platform-tests/html/infrastructure/common-dom-interfaces/collections/radionodelist.html` (and many more, but this is a good indicator whether the issue is fixed)

**Comment by g-k** [comment]
I can give this a shot.

**Comment by KiChjang** [comment]
Ok, be mindful that I expect this to be more difficult than the E-Easy issues that you've handled before. If you're stuck and require clarifications, please don't hesistate to ping us at #servo on irc.mozilla.org!

**Comment by g-k** [comment]
OK, I pushed a branch that sets and gets `value` on Element and the last radio node list test passing: https://github.com/servo/servo/compare/master...g-k:html-input-value?expand=1

I'll run the rest of the wpt tests later, but I'm not sure if this is a good approach or what to do about `RemoveAttribute` and syncing `attrs.value` and `textinput` in HTMLInputElement.

**Comment by KiChjang** [comment]
@g-k I left some comments on your commit, nice work so far!
