### ISSUE TITLE
Incomplete rendering on 2ch.hk/fl/

### ISSUE THREAD

**Issue by suhr** [servo/servo#9461]
Also elements of the page start to disappear after some scrolling.
There's screencast: https://d.maxfile.ro/xnuzcdouhv.webm

**Comment by jdm** [comment]
What do you mean by "incomplete rendering"?

**Comment by suhr** [comment]
A lot of page elements are not rendered at all. See the screencast.

**Comment by KiChjang** [comment]
I'm sorry, but it's not immediately obvious which elements are not being rendered. It'd be nice if you have a reference of what the actual page looks like side-by-side.

**Comment by suhr** [comment]
Sure.

![fl_mozilla](https://cloud.githubusercontent.com/assets/65870/12686009/9b104808-c6d8-11e5-8000-661724694932.png)
![fl_servo](https://cloud.githubusercontent.com/assets/65870/12686016/a491fb74-c6d8-11e5-8d1d-7ac68d2a660c.png)

**Comment by suhr** [comment]
Looks like it's fixed now.
