### ISSUE TITLE
Replace multiple formdata (string or blob) definitions with FormDataEntryValue

### ISSUE THREAD

**Issue by psdh** [servo/servo#9462]
Use `FormDataEntryValue` or `BlobOrUSVString` instead of FormDatum (in `dom/formdata.rs`)

**Comment by KiChjang** [comment]
We really should use `FormDataEntryValue` instead of `BlobOrUSVString` since the latter is typedef'd as the former.

**Comment by psdh** [comment]
We cannot use the FormDataEntryValue (the autogenerated typedef to BlobOrUSVString) since one of its field is a Rooted reference to Blob. As of now we'll just rename the `FormDatum` enum in `dom/formdata.rs` to `FormDataEntryValue`

**Comment by nox** [comment]
Our `FormDatum` type isn't even similar anymore to the mentioned union type. Closing.
