### ISSUE TITLE
Error 127 when running servo on Windows

### ISSUE THREAD

**Issue by codec-abc** [servo/servo#9465]
Hi,

I have a return code with a value of 127 when running servo on Windows 10 (it both on my personal and work computer)

`
$ ./mach run --dev http://www.google.com
`
`
Servo exited with return value 127
`

Strangely enough when I run it in debug mode 
`$ ./mach run --dev --debug http://www.google.com`
it works fine.

Am I missing something ?

**Comment by codec-abc** [comment]
I made some progress on it. The problem is that the servo executable is not finding the dlls and the font configuration (in etc/fonts) when launched from the command line. So I guess I did not follow exactly the instruction to build and run servo and windows or we need to modify the path system' s variable.

**Comment by larsbergstrom** [comment]
Does it work when run from the mingw commandline? It should not work from a CMD.EXE window, PowerShell, or MSYS window. Sorry about this - many of the dependencies (fontconfig, etc. ) are installed as packages in mingw64, and in order to find them they must be in the `PATH` for Servo.

**Comment by larsbergstrom** [comment]
Also, if you run it as `target/debug/servo.exe tests/html/about-mozilla.html`, you will get more info about the error rather than just "Error 127." That Error can come up for multiple reasons if Servo crashes during the startup steps.

**Comment by codec-abc** [comment]
I was indeed using the mingw command line all the time. It does not even build when using a msys command line (or cmd and PowerShell). To make further tests I deleted the target directory and built again. 
The result are the following :
- It run fine from an mingw command line (ie when using target/debug/servo.exe url)
- It does NOT run when using mach expect when debugging (ie using the --debug argument).

So, could it be possible that the mach tool is modifying the PATH variable ? And do you recommend it usage on Windows ?

**Comment by jdm** [comment]
Yes, mach definitely modifies PATH: http://mxr.mozilla.org/servo/source/python/servo/command_base.py#276 . You can see the changes via `./mach env`.

**Comment by codec-abc** [comment]
Thanks for the tips. After more investigation I start to understand what is going on. 

Like jdm said mach changes the `PATH` system's variable. In particular, it adds the path to the rust compiler that servo need for compiling the source code. So on my computer it adds the path 
`C:\Soft\msys64\home\codec\servo\.servo\rust\2015-12-27\rustc-nightly-x86_64-pc-windows-gnu\rustc\bin` to `PATH`.

In this directory I have a `libstdc++-6.dll` which is different that the one used by the dependencies that is located in `C:\Soft\msys64\mingw64\bin`. The problem is that the two dlls don't seem compatible and since the one provided with the rust compiler is loaded first it makes servo crash at startup.

**Comment by pix64** [comment]
Starting the executable directly from the MinGW64 shell also works fine. This is a problem with mach.

Removing the **kwargs arguments from this check_call call: http://mxr.mozilla.org/servo/source/python/servo/command_base.py#108 allows mach to run Servo.

If mach is ran with debug flag, it works fine. Mach is running [u'/mingw64/bin/gdb', '-q', '--args', '/e/code/servo/target/release/servo'] rather than ['/e/code/servo/target/release/servo'] but the environment variables are the exact same.

**Comment by ignacio-ca** [comment]
Hello, I'm having the same results on windows.

A) ` $./mach run www.github.com   Servo exited with return value 127 `

B) `$ ./mach run --dev --debug http://www.github.com`
Shows something of the page. With www.google.com or www.duckduckgo.com nothing is rendered.

C) `$ target/debug/servo.exe https://www.github.com` 
Same result than B
