### ISSUE TITLE
Support scrolling to a fragment identifier

### ISSUE THREAD

**Issue by peterjoel** [servo/servo#9474]
This is not (yet) specified by WHATWG, but it will be here:
https://html.spec.whatwg.org/multipage/browsers.html#scroll-to-the-fragment-identifier
when this issue is resolved:
https://github.com/whatwg/html/issues/94

Issue split from existing issue #1716. 

This issue is concerned with scrolling to the correct location, given the correct fragment has been identified, while #1716 is concerned with identifying the fragment.

**Comment by KiChjang** [comment]
Is this dependent on #1716?

**Comment by peterjoel** [comment]
@KiChjang They can be implemented independently. 

The complication will be that this issue will be easier to test (once the specification is complete). #1716 will be tricky to test properly on its own, as it will involve checking that an element is scrolled into view, without having a proper definition of what that means.

**Comment by nox** [comment]
Wasn't this implemented?

**Comment by jdm** [comment]
https://dxr.mozilla.org/servo/rev/81044e001941ee3b4eef598125c327c73e993b5d/components/script/dom/document.rs#691 looks like yes.
