### ISSUE TITLE
CSS rule ignored if unkown pseudo class is used

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9476]
```html
<style>
  body, :focus, :xxx {
    border: 4px solid red;
  }
</style>
```

Because of `.xxx`, body doesn't have a red border.

**Comment by Ms2ger** [comment]
Per spec.

**Comment by paulrouget** [comment]
TIL: http://stackoverflow.com/questions/13816764/invalid-css-selector-causes-rule-to-be-dropped-what-is-the-rationale/13831877#13831877
