### ISSUE TITLE
Unexpected overflow

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9484]
STR:
1) place mouse over the green div
2) scroll horizontally and/or vertically

The page will start moving, even though the parent div is `100%` and `overflow:hidden`.

Scrolling doesn't alway happen. Repeat step (2).

The  behavior is not exactly the same with Webrender. But both regular Servo and Webrender have this overflow.

```html
<style>
  body {
    margin: 0;
  }

  .red {
    background: red;
    position: absolute;
    width: 100%;
    height: 100%;
    overflow: hidden;
  }

  .green {
    background: green;
    position: absolute;
    width: 500px;
    height: 100%;
    right: 0px;

    width: 500px;
    transform: translateX(250px);
    box-shadow: 0px 0px 200px black;
  }
</style>

<div class="red">
  <div class="green"></div>
</div>
```

<img src="http://g.recordit.co/ZvpcaPFOAr.gif">

**Comment by pcwalton** [comment]
This will not be an easy fix. The problem is that now we need two different notions of overflow—overflow including box-shadow and overflow not including box-shadow. :(

**Comment by jgraham** [comment]
Is it possible to script this test so that it could be turned into a reftest?

**Comment by pcwalton** [comment]
We don't really have the ability to scroll from script, I don't think.
