### ISSUE TITLE
On OSX, fonts are lighter than gecko and webkit

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9487]
<img width="361" alt="screen shot 2016-02-01 at 12 07 54" src="https://cloud.githubusercontent.com/assets/373579/12715792/9eb02bc6-c8dc-11e5-98bb-59454b142523.png">

```html
<span>FOOBAR</span>
<style>
  span {
    font-size: 14px;
    font-family: sans-serif;
  }
</style>
```

I haven't tested on other platforms.

**Comment by paulrouget** [comment]
Attempt to bump the priority of this.

Do we know what's going on? Is it hard to fix?
If it's easy, I'd love to get that done by June. It would make our UI look exactly like gecko and webkit (and I haven't found any CSS workaround to fix that)

If it's too much work - let's flag it back to P3.

**Comment by glennw** [comment]
@paulrouget I believe there's two issues here - one is our actual font selection matching is different than Gecko, and two is the lack of subpixel AA. I'm hoping to have a solution for the 2nd issue before June. The first issue should be (relatively) trivial to implement - if someone with mac experience has time to look into it.

**Comment by glennw** [comment]
Of course, getting the font selection to exactly match gecko is far from trivial, but fixing the common case shouldn't be too difficult hopefully.
