### ISSUE TITLE
Implement XMLHttpRequest.send(Document)

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9490]
Blocks #9489.
- Spec: https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send-document.
- Code: `components/script/dom/xmlhttprequest.rs`, `components/script/dom/webidls/XMLHttpRequest.webidl`.
- Test: `XMLHttpRequest/send-entity-body-document.htm`, and probably more.

**Comment by fhahn** [comment]
Is it OK if I take a stab at this issue?

**Comment by KiChjang** [comment]
Of course!

**Comment by KiChjang** [comment]
@fhahn Are you still working on this?

**Comment by jdm** [comment]
If you forgot about it, may I ask that it remain forgotten? I filed #9963 yesterday without realizing it was a duplicate and I'm hoping some students will start working on it soon.

**Comment by fhahn** [comment]
Sorry for taking so long to respond. Unfortunately I did not have time to work on this in the last weeks and I won't for a few more weeks. So feel free to give this issue to somebody else :)

**Comment by jdm** [comment]
For implementing the serialization of the document, we should be able to use the existing HTML serialization code. See serialize in components/script/dom/element.rs for an example!

**Comment by jaysonsantos** [comment]
Hey guys, I was wondering how to do this.
I saw a function named `Open` on `impl XMLHttpRequestMethods for XMLHttpRequest`, this would be to implement a Send version?

**Comment by KiChjang** [comment]
@jaysonsantos I'm pretty sure that there's also a `Send` fn. Can you confirm that you are currently working on this?

**Comment by jaysonsantos** [comment]
@KiChjang Ah, I saw it but I don't know what to do. Is there something missing on it?
Also don't put as me doing because I don't know if I am able to do it because I know nothing about servo code.

**Comment by KiChjang** [comment]
[The specification](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send-document) points to step 4 of the XMLHttpRequest.send method, which is [this code](https://github.com/servo/servo/blob/ea97c8905580e67e96ae00572d1c4e7af3d58736/components/script/dom/xmlhttprequest.rs#L542-L544). Right now, it assumes that the `data` parameter is of `BodyInit` type; we'll need to check whether it's a `Document` as well and handle it accordingly. [The WebIDL file generating our Rust bindings](https://github.com/servo/servo/blob/ea97c8905580e67e96ae00572d1c4e7af3d58736/components/script/dom/webidls/XMLHttpRequest.rs#L58) will also be need to updated, so that `data` objects of `Document` type gets properly sent in as a parameter to XHR.send.

**Comment by jaysonsantos** [comment]
@KiChjang Thanks I will try to take a look

**Comment by jaysonsantos** [comment]
Do you guys have any tip on how to do this? Send is already inside a trait, how could I accept Option<BodyInit> or Option<Document> without using traits?

**Comment by jdm** [comment]
If you make the change to the WebIDL file and rebuild, the resulting Rust build errors should inform how you need to modify the Rust code to accommodate the change.

**Comment by jaysonsantos** [comment]
Hey guys I started doing some stuff on my branch in https://github.com/servo/servo/compare/master...jaysonsantos:xhr-send?expand=1 but somehow the Document which is being sent to `Send` is always a HTML document https://github.com/jaysonsantos/servo/blob/xhr-send/components/script/dom/xmlhttprequest.rs#L1428 despite the test setting the header properly https://github.com/jaysonsantos/servo/blob/xhr-send/tests/wpt/web-platform-tests/XMLHttpRequest/resources/win-1252-xml.py
My question is: is this an issue that should be investigated or am I just missing something?

**Comment by jdm** [comment]
That's probably our XML parser not being invoked properly when parsing the document, which is being tracked in #10581, so you can leave that as an expected failure for the purposes of this PR.

**Comment by jaysonsantos** [comment]
Probably that is happening everywhere because for all tests `document.CharacterSet()` returns `UTF-8`.
I put some debug messages here https://github.com/servo/servo/compare/master...jaysonsantos:xhr-send?expand=1#diff-016eef304e69674de212b7fbcd9330fdR1433
And the response is always this:
```
DEBUG:script::dom::xmlhttprequest: Document is already utf-8, skipping conversion Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("web-platform.test"), port: Some(8000), default_port: Some(80), path: ["XMLHttpRequest", "resources", "win-1252-xml.py"] }), query: None, fragment: None }
DEBUG:script::dom::xmlhttprequest: request_headers = Headers { Referer: http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm, }
DEBUG:script::dom::xmlhttprequest: Document is already utf-8, skipping conversion Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("web-platform.test"), port: Some(8000), default_port: Some(80), path: ["XMLHttpRequest", "resources", "invalid-utf8-html.py"] }), query: None, fragment: None }
DEBUG:script::dom::xmlhttprequest: request_headers = Headers { Referer: http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm, }
DEBUG:script::dom::xmlhttprequest: Document is already utf-8, skipping conversion Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("web-platform.test"), port: Some(8000), default_port: Some(80), path: ["XMLHttpRequest", "resources", "shift-jis-html.py"] }), query: None, fragment: None }
DEBUG:script::dom::xmlhttprequest: request_headers = Headers { Referer: http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm, }
DEBUG:script::dom::xmlhttprequest: Document is already utf-8, skipping conversion Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("web-platform.test"), port: Some(8000), default_port: Some(80), path: ["XMLHttpRequest", "folder.txt"] }), query: None, fragment: None }
DEBUG:script::dom::xmlhttprequest: request_headers = Headers { Referer: http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm, }
DEBUG:script::dom::xmlhttprequest: Document is already utf-8, skipping conversion Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("web-platform.test"), port: Some(8000), default_port: Some(80), path: ["XMLHttpRequest", "resources", "img-utf8-html.py"] }), query: None, fragment: None }
DEBUG:script::dom::xmlhttprequest: request_headers = Headers { Referer: http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm, }
DEBUG:script::dom::xmlhttprequest: Document is already utf-8, skipping conversion Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("web-platform.test"), port: Some(8000), default_port: Some(80), path: ["XMLHttpRequest", "resources", "empty-div-utf8-html.py"] }), query: None, fragment: None }
DEBUG:script::dom::xmlhttprequest: request_headers = Headers { Referer: http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm, }
DEBUG:script::dom::xmlhttprequest: Document is already utf-8, skipping conversion Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("web-platform.test"), port: Some(8000), default_port: Some(80), path: ["XMLHttpRequest", "resources", "image.gif"] }), query: None, fragment: None }
DEBUG:script::dom::xmlhttprequest: request_headers = Headers { Referer: http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm, }
```

**Comment by jaysonsantos** [comment]
Should I also disable those tests?

**Comment by jdm** [comment]
Well, it's not disabling the tests, it's just marking them as not passing, presumably.

**Comment by jaysonsantos** [comment]
Yes, what I mean is, should I submit the PR  with non utf8 tests marked as failed? As I saw `Document::new` is always creating it with UTF-8.

**Comment by jdm** [comment]
Yes, that sounds reasonable to me.

**Comment by KiChjang** [comment]
Most recent attempt at #10604.

**Comment by KiChjang** [comment]
@cynicaldevil is currently working on this.
