### ISSUE TITLE
The gold linker should not be used on Windows

### ISSUE THREAD

**Issue by UK992** [servo/servo#9499]
After https://github.com/servo/servo/pull/9449 building on Windows failed:
```
$ ./mach build -r
Could not execute process `C:/msys64/home/Urban/servo/etc/rustc-with-gold -vV` (never executed)

Caused by:
  %1 is not a valid Win32 application. (os error 193)
Build completed in 0.14s
```

**Comment by jdm** [comment]
@larsbergstrom This seems difficult to get right!

**Comment by larsbergstrom** [comment]
@jdm Agreed :-) 

Though a large part of it is also that we don't have CI up yet for all of our platforms. While I can say I should certainly know better, as we expand our platform matrix, it's pretty unreasonable to expect every reviewer to know the impact of small python changes on, say, the AARCH64 cross-build.

**Comment by larsbergstrom** [comment]
The change required here is that the python code that chooses to use the gold linker:
https://github.com/servo/servo/blob/220ead14b16c8965335a6d54e037f2e30fc634ea/python/servo/command_base.py#L382

Should not do so if the `sys.platform == 'win32'`.

**Comment by UK992** [comment]
@larsbergstrom in MINGW64 shell, sys.platform return 'msys', not 'win32'.

**Comment by Jayflux** [comment]
So would we check both msys and win32?
In the long term it would be good not to be relying so heavily on the mingw64 stuff at all
