### ISSUE TITLE
Scrolling doesn't take pixel density into account

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9502]
I realized that scrolling is slow on my mac.

When moving my fingers across the trackpad, the scrolling distance is twice shorter than with gecko.

This solves the issue:

```patch
diff --git a/ports/glutin/window.rs b/ports/glutin/window.rs
index 076ace8..a9787cd 100644
--- a/ports/glutin/window.rs
+++ b/ports/glutin/window.rs
@@ -209,7 +209,7 @@ impl Window {
                     MouseScrollDelta::LineDelta(dx, dy) => (dx, dy * LINE_HEIGHT),
                     MouseScrollDelta::PixelDelta(dx, dy) => (dx, dy),
                 };
-                self.scroll_window(dx, dy);
+                self.scroll_window(self.window.hidpi_factor() * dx, self.window.hidpi_factor() * dy);
             },
             Event::Touch(touch) => {
                 use glutin::TouchPhase;
```

But I don't know if this needs to be fixed in glutin or servo.

Can someone test with linux + hidpi display?

**Comment by glennw** [comment]
@mbrubeck Any opinions on whether this should be in glutin or servo?

**Comment by paulrouget** [comment]
I'd like to know if Linux and Windows behave the same way. If not, it needs to be fixed at the glutin level. If they do behave the same way, I guess it doesn't matter much if it happens in glutin or servo.

**Comment by mbrubeck** [comment]
I think it's reasonable to do this conversion (from "px" to device pixels) in Servo.  I don't have a high-dpi machine right now where I can test whether Linux and Windows behave the same as Mac OS X (and at least for X11 the documentation does not specify), but if not then we can fix that in glutin.

**Comment by paulrouget** [comment]
Looking at Glutin's code, I see that for mousemove events, the coordinates are multiplied by hidpi_factor, but not for wheel events.

I think this should be fixed in glutin.

I'll submit a PR.

**Comment by frewsxcv** [comment]
This should be fixed by https://github.com/servo/servo/pull/9517
