### ISSUE TITLE
Mac builders fails to compile harfbuzz

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9504]
It's the autoconf failure, but now it happens on our mac build machines as well.
```
--- stderr
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.15 is not found.
make[1]: warning: -jN forced in submake: disabling jobserver mode.
/Users/servo/.cargo/registry/src/github.com-0a35038f75765ae4/harfbuzz-sys-0.1.2/harfbuzz/missing: line 81: autoheader: command not found
WARNING: 'autoheader' is missing on your system.
         You should only need it if you modified 'acconfig.h' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'autoheader' program is part of the GNU Autoconf package:
         <http://www.gnu.org/software/autoconf/>
         It also requires GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[1]: *** [/Users/servo/.cargo/registry/src/github.com-0a35038f75765ae4/harfbuzz-sys-0.1.2/harfbuzz/config.h.in] Error 127
make: *** [all] Error 2
thread '<main>' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f", "makefile.cargo",
                            &format!("-j{}" , env:: var ( "NUM_JOBS" ) .
                                     unwrap (
                                     ))]).status().unwrap().success()', /Users/servo/.cargo/registry/src/github.com-0a35038f75765ae4/harfbuzz-sys-0.1.2/build.rs:14
stack backtrace:
   1:        0x10735a038 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x10735dbb5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x10735d7b6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10734b956 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x1073461c7 - sys_common::unwind::begin_unwind::h6740538633853985845
   6:        0x10734129a - main::h4996c082ce17a6c8iaa
   7:        0x10735d3e2 - sys_common::unwind::try::try_fn::h9072539541001871658
   8:        0x1073595db - __rust_try
   9:        0x10735d291 - rt::lang_start::hacfbaccc148e05fdU4x
  10:        0x107346b29 - main
```

cc @larsbergstrom

**Comment by paulrouget** [comment]
Isn't it just a matter of linking autoconf?

**Comment by nox** [comment]
@paulrouget What do you mean here by linking?

**Comment by paulrouget** [comment]
Install and `brew link` autoconf (`brew link autoconf`)

**Comment by larsbergstrom** [comment]
Yes, it looks like our saltstack rules are not properly installing autoconf. I just brought a builder back online from scratch, and the auto-provisioning did not work correctly.

cc @edunham @aneeshusa

**Comment by larsbergstrom** [comment]
OK, it looks like autoconf213 got linked first (instead?) and this caused autoconf to not get linked and thus autoheader was not available. Maybe an ordering issue in our salt config files? I manually fixed servo-mac1 so we should be able to proceed.

```
administrators-Mac-mini:~ root# su - administrator
administrators-Mac-mini:~ administrator$ brew link autoconf
Linking /usr/local/Cellar/autoconf/2.69... 
Error: Could not symlink share/info/autoconf.info
Target /usr/local/share/info/autoconf.info
is a symlink belonging to autoconf213. You can unlink it:
  brew unlink autoconf213

To force the link and overwrite all conflicting files:
  brew link --overwrite autoconf

To list all files that would be deleted:
  brew link --overwrite --dry-run autoconf
administrators-Mac-mini:~ administrator$ brew link --overwrite autoconf
Linking /usr/local/Cellar/autoconf/2.69... 19 symlinks created
administrators-Mac-mini:~ administrator$ which autoheader
/usr/local/bin/autoheader
```

**Comment by aneeshusa** [comment]
I don't think the config is running the 'brew link' on autoconf, so I'll investigate adding that. Does automake need to be installed before autoconf, or can they be installed together (i.e. in the same command?)

**Comment by larsbergstrom** [comment]
@aneeshusa I think they can be installed together - the conflict seemed to be with autoconf vs. autoconf213 (in particular, autoconf213 being installed first and blocking the link of autoconf).

Thanks a ton for all your help with this!

**Comment by aneeshusa** [comment]
Do we need to install both autoconf and autoconf213? Based on [the current master](https://github.com/servo/saltfs/blob/272445d43b92df1043d61bb9d12a46f073bc65b9/servo-dependencies.sls#L28), it looks like we're only installing autoconf213.

**Comment by larsbergstrom** [comment]
I thought that we needed both. autoconf213 is required for the SpiderMonkey JS engine; everything else (like harfbuzz) uses normal autoconf.

They are definitely both installed on all our machines.

Maybe autoconf is a dependency of automake?

**Comment by aneeshusa** [comment]
Yes, it seems you're right: [automake depends on autoconf](https://github.com/Homebrew/homebrew/blob/0c6cfa6584f0e5f8dffe30e032fa00c882de002e/Library/Formula/automake.rb#L19)

**Comment by aneeshusa** [comment]
Do you know if there is a way to query if a homebrew package is linked? I couldn't find anything like that in the docs.

**Comment by larsbergstrom** [comment]
Hrm, I don't see anything, either. `brew info` and the others don't seem to show it.

**Comment by aneeshusa** [comment]
Ok, I should have a PR shortly then, but it'll have to be a bit hacky.

**Comment by aneeshusa** [comment]
Actually, can we just check the symlink manually?

**Comment by larsbergstrom** [comment]
Aha, that sounds like a great plan :-)

**Comment by aneeshusa** [comment]
I have to go to my first class of the semester, but I should have a quick fix for this today, and a better fix in the next few days.

**Comment by larsbergstrom** [comment]
That's fantastic! Thanks again for all your help, and good luck with classes :-)

**Comment by aneeshusa** [comment]
I'm trying to understand ```brew link```'s behavior better in the case of updates. Is there a spare Mac builder that I can ssh into and mess around on (i.e. one that's not being used for builds)?

**Comment by larsbergstrom** [comment]
Unfortunately, they're all pretty slammed right now. I requested a new one from macstadium this morning, though, and as soon as I have it provisioned enough for you to ssh in, I'll let you know! I don't know how long it will take for them to bring it online.

**Comment by aneeshusa** [comment]
Ok, thank you! We should also use it for some manual testing when reviewing the PR.

**Comment by larsbergstrom** [comment]
@aneeshusa You should be able to ssh as root into servo-macpro1.servo.org. I'm doing some basic timing runs, but feel free to do whatever you need to the box! It's not hooked up to our CI yet.

**Comment by larsbergstrom** [comment]
@aneeshusa Did you have a chance to do some manual testing of these rules? Or is there something that you'd like me to manually test?

Thanks!

**Comment by aneeshusa** [comment]
I got caught up in school the last two days - I should be able to poke around today.

How can I run servo builds manually on the Mac (to ensure that the builds using autoconf and autoconf213 work properly)?

**Comment by larsbergstrom** [comment]
No worries at all! You can test the build by doing:
```
su - servo
source ~/exports
cd ~/servo
rm -rf target
./mach build -d
```

Also, we may need to coordinate a bit with @mbrubeck, as he's also doing some testing of intermittent test failures. Let me know how you were going to do the tests if your classes get a bit overwhelming - I'm happy to help out! I just don't really know how to run salt "standalone" w/o the master to test pending changes.

**Comment by aneeshusa** [comment]
@larsbergstrom I updated the wiki page with instructions on how to run Salt remotely and locally - let me know if that helps.

@mbrubeck, let me know if/when you hop on the machine for some testing; I'll also make sure to check the output of ```w``` to see if anyone else is logged in.

**Comment by aneeshusa** [comment]
FYI: This is my fault for not updating the documentation earlier, but @larsbergstrom we should be using the install_salt script from the repo to install salt, instead of just ```brew install saltstack```. The install script keeps the Salt version pinned, which is helpful because sometimes there are compatibility problems between versions (see [this commit](https://github.com/aneeshusa/servo-saltfs/commit/81d9e63688df36777879e69d4f2b3cc30c5dcfc4) for an example) so installing the latest from brew isn't a good idea. I've changed to the right Salt version on servo-macpro1 and updated the wiki page.

**Comment by aneeshusa** [comment]
@larsbergstrom I can't seem to build successfully - I'm getting a lot of errors that say ```error: couldn't create a temp dir: No such file or directory (os error 2)```. It looks like the TMPDIR variable that's being set in ~/exports points to a nonexistent directory.

**Comment by larsbergstrom** [comment]
Gah! Just `unset TMPDIR`. Sorry about that!

**Comment by larsbergstrom** [comment]
@aneeshusa Thanks a ton for fixing up the wiki instructions! I'm sorry - I had seen the "warning, this needs an update" comment there, but when I ran through and fixed up the worst of the bits that were wrong, I assumed that was it. Thanks again for all your help with our infra!
