### ISSUE TITLE
Switch to the deque crate from crates.io

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#9539]
It may have better performance via more precise memory ordering semantics, and it would let us remove about 400 lines of highly unsafe code from the tree.

**Comment by nox** [comment]
@pcwalton Where?

**Comment by mbrubeck** [comment]
@nox [util::deque](https://github.com/servo/servo/blob/d574b78313be75f3388123d11354b897598877a3/components/util/deque/mod.rs)

**Comment by pcwalton** [comment]
@nox Specifically: Replace https://github.com/servo/servo/blob/eb7039d04d4c83800ba9d92dc251222f79b83040/components/util/deque/mod.rs with https://crates.io/crates/deque/
