### ISSUE TITLE
Set request and response cookies for websocket connections

### ISSUE THREAD

**Issue by jdm** [servo/servo#9540]
We have code that sets up a network connection to a websocket server in `components/net/websocket_loader.rs`. This is initially an HTTP connection, so it should include things like HTTP cookies, but it currently doesn't. We should make the `set_request_cookies` function in `components/net/http_loader.rs` public and call it from `establish_a_websocket_connection`, which should change some test results in `./mach test-wpt tests/wpt/web-platform-tests/websockets`.

@rebstar6 might be interested in working on this, so please don't anybody else start working on this without talking to me first.

**Comment by jdm** [comment]
Note that we'll need to pass the required CookieJar data as an argument to `establish_a_websocket_connection` in order to facilitate this.

**Comment by jdm** [comment]
Additionally, we should support setting cookies that are present in the HTTP response too. We should modify `set_cookies_from_response` to take a `&Headers` argument instead of `&HttpResponse`, then we can call that from `establish_a_websocket_connection` as well and pass even more tests.

**Comment by rebstar6** [comment]
Sounds good, I'll take it!

**Comment by rebstar6** [comment]
@jdm - do you mean [CookieJar](http://cyderize.github.io/rust-websocket/doc/cookie/struct.CookieJar.html) or the cookie_jar: &Arc<RwLock<CookieStorage>> that's used in http_loader's set_request_cookies? I assume the latter given that the plan is to use that function, but just checking.

Also I'll need some help on this later - should I just post questions here or ping everyone in IRC?

**Comment by jdm** [comment]
Yes, the latter is the one I meant. If you have questions and don't need to dash off immediately, IRC is great for questions. If you don't get a response or don't have time to wait for answers, right here is fine. It's up to you!

**Comment by rebstar6** [comment]
Ok, so far I've changed the method signatures and tried just passing the cookie_jar along - 
https://github.com/rebstar6/servo/commit/98055b4bff6d46d9cdb20b03ffc76e19ac99f7b9

Just to confirm, is passing self.cookie_storage.clone() from resource_thread the right approach (read: by the time the websocket_loader::init call is made, are the cookies already in this object)? That, or does some other work have to be done before this call?

**Comment by jdm** [comment]
Yes, cloning the `self.cookie_storage` value will yield a pointer to the storage for all cookies. The `Arc<Rwlock<CookieStorage>>` means that it's a value that is shared between multiple threads, so every consumer has the ability to update it and see others' updates automatically.

**Comment by rebstar6** [comment]
So there's one cookie_jar object for the browser for any cookies that it may have stored at any given point in time (?)

**Comment by jdm** [comment]
Yes, the cookie jar is shared globally among all network connections. And your understanding is correct.

**Comment by rebstar6** [comment]
Ok, added the call in https://github.com/rebstar6/servo/commit/4879f0812dc183600c5134c5e643a6ea005340c8 so 2 more tests pass. That said, in http_loader, there is a check 1st on the load_data credentials flag (see http://mxr.mozilla.org/servo/source/components/net/http_loader.rs#530) 

Is there an equivalent for websocket_loader, or is the call for everyone ok?

**Comment by jdm** [comment]
I don't believe there's a way for websockets to specify that they don't want credentials, so that's fine.

**Comment by jdm** [comment]
I was wrong about dealing with cookies from the response, unfortunately. https://html.spec.whatwg.org/multipage/comms.html#feedback-from-the-protocol means that we need to extract the value of the Set-Cookie header from the response, send it to the child as part of the `ConnectionEstablished` message, and have the child set the cookies before dispatching the "open" event. This can be accomplished the same way that `Document::SetCookie` is implemented.

**Comment by rebstar6** [comment]
Is this in addition to or instead of the set_cookies_from_response call?

**Comment by jdm** [comment]
Instead of.

**Comment by rebstar6** [comment]
Backing up for a second, why did that call make 002/004 pass but not this? Specifically comparing 002 and 007, what's happening in 007 that's failing because we've set the cookie?

Looking at the spec and the test itself, I think I just don't get what 007 is testing

**Comment by jdm** [comment]
007 is testing when the cookies from the response are stored in the shared cookie storage. Specifically, the specification mandates that that operation should not occur until right before the "open" event is dispatched. 007 is making a websocket connection, then making another network connection that takes at least two seconds, then checks to see whether the cookie that the websocket response includes has already been stored or not.

**Comment by rebstar6** [comment]
So the cookie is just being stored too early, and we instead want it to happen within this:
 ```
while let Ok(event) = dom_event_receiver.recv() {
                match event {
                   WebSocketNetworkEvent::ConnectionEstablished(headers, protocols) => {
                        let open_thread = box ConnectionEstablishedTask {
                            addr: moved_address.clone(),
                            headers: headers,
                            protocols: protocols,
                        };
                        sender.send(CommonScriptMsg::RunnableMsg(WebSocketEvent, open_thread)).unwrap();
                    },
```
Is that right?

**Comment by jdm** [comment]
Take a look at the implementation of ConnectionEstablishedTask and it should be clear where it slots in.

**Comment by rebstar6** [comment]
Hah, the // Step 5: Cookies. Yeah, I guess that's clear.

My 1st thought is that we should have the cookie to be set at this point because we have all of the headers, so it's not immediately clear that we would need to pull set-cookie headers out in websocket_loader to be fed into the ConnectionEstablished call. Could we not just pull it out of the self.headers when we get to step 5?

This all said, I still feel like I have a super weak handle on all of this :/ - I'll try to figure more out tomorrow.

**Comment by jdm** [comment]
No, you're right - the headers are already available there.

**Comment by rebstar6** [comment]
Moved the response stuff to the right place in: https://github.com/rebstar6/servo/commit/e717cabdba7f846611edc5c6ac3d05b22b382a9c?diff=unified
The tests all pass (woot!!) though I have a few questions still on some of the specifics. Will discuss this week.
