### ISSUE TITLE
./mach test is broken

### ISSUE THREAD

**Issue by jdm** [servo/servo#9544]
It tries to invoke the old reftest harness which no longer exists:
```
$ ./mach test
tidy reported no errors.
Error running mach:

    ['test']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

TypeError: test_ref() got an unexpected keyword argument 'kind'

  File "/home/sbar/git/servo/python/servo/testing_commands.py", line 152, in test
    Registrar.dispatch("test-%s" % suite, context=self.context, **kwargs)
  File "/home/sbar/git/servo/python/mach/mach/registrar.py", line 115, in dispatch
    return self._run_command_handler(handler, context=context, **kwargs)
  File "/home/sbar/git/servo/python/mach/mach/registrar.py", line 90, in _run_command_handler
    result = fn(**kwargs)
```

That being said, I think we should change the default behaviour of `./mach test` to suggest something better, rather than assume the user actually wants to invoke every test harness possible.

**Comment by jdm** [comment]
I would love if mach could look at the changed files in the git branch and recommend a test suite to run. I'd love it even more if it could recommend subdirectories somehow.

**Comment by talklittle** [comment]
I'd like to propose a quick fix (I have a PR ready) for `./mach test`, since the `faster` parameter passed to `test_tidy()` is not recognized and causes the same error as reported.

I also introduce `--all` to run all test suites. If `./mach test` is run without params, it prints out:

```
Specify a test path or suite name, or pass --all to run all test suites.

Available suites:
    tidy
    wpt
    css
    unit
    compiletest
```

So nothing clever about suggesting which suite to run.
