### ISSUE TITLE
Implement Step 9 of the Open method for XHR

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9547]
This is the part that deals with setting the username and password on a URL. Can be easily done using the convenience methods provided in rust-url [here](http://servo.github.io/rust-url/url/struct.Url.html#method.username_mut).

Code: `components/script/dom/xmlhttprequest.rs`
Spec: https://xhr.spec.whatwg.org/#dom-xmlhttprequest-open

**Comment by danlrobertson** [comment]
I'd like to take a crack at this!

**Comment by KiChjang** [comment]
Sure thing!
