### ISSUE TITLE
Implement Step 3 of the SetRequestHeader method in XHR

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9548]
This is where we should normalize the value being passed in as a `ByteString` paramemter.

Code: `components/script/dom/xmlhttprequest.rs`
Spec: https://xhr.spec.whatwg.org/#dom-xmlhttprequest-setrequestheader, https://fetch.spec.whatwg.org/#concept-header-value-normalize

**Comment by TimNN** [comment]
If this is not yet taken, I would like to give fixing this a shot.

**Comment by Ms2ger** [comment]
@timvandermeij: since you were asking, are you working on this or is it free for @TimNN?

**Comment by timvandermeij** [comment]
@Ms2ger Sorry, I should have mentioned here too that I'm working on this! I almost have a patch for this, but I'm pretty sure it can be improved. I'll have a PR in a bit, but any feedback is greatly appreciated, so I'd love to hear @TimNN's ideas on my approach too!
