### ISSUE TITLE
Rename *_thread_source to *_task_source

### ISSUE THREAD

**Issue by jdm** [servo/servo#9561]
These were incorrectly renamed as part of #8522. These are terms from the specification which should refer to the concepts of "tasks", rather than the native concept of threads.

Code: `components/script/dom/window.rs`

**Comment by kmuszyn** [comment]
Hello, I think this looks like a good task for a complete newbie here, can I work on it?

**Comment by KiChjang** [comment]
Yes, definitely!

**Comment by timvandermeij** [comment]
This can be closed now that #9576 has been merged.

**Comment by KiChjang** [comment]
Sorry, this isn't done yet - `git grep _thread_source` still exposes a few instances where this isn't renamed.

cc @kmuszyn

**Comment by jdm** [comment]
Ah, I forgot to mention global.rs in the original comment.

**Comment by kmuszyn** [comment]
Sorry, I missed that one. I will prepare a fix.

**Comment by KiChjang** [comment]
Fixed in #9683.
