### ISSUE TITLE
properties.mako.rs truncating parsing error - template references 

### ISSUE THREAD

**Issue by craftytrickster** [servo/servo#9564]
properties.mako.rs refuses to compile when using references inside a generic parameter.

For example, the following code is valid rust, as tested in element.rs:

```rust
let thing: Vec<&PropertyDeclaration> = Vec::new();
```

However, if you try to use that same code inside properties.mako.rs, the following error occurs:

```
/home/divad/Rust/servo/target/debug/build/style-f9fb073aea07cada/out/properties.rs:28494:23:
 28494:24 error: expected one of `!`, `(`, `+`, `::`, `;`, `<`, or `=`, found `&`
/home/divad/Rust/servo/target/debug/build/style-f9fb073aea07cada/out/properties.rs:28494         
let thing: Vec&PropertyDeclaration> = Vec::new();
```
Notice how the opening bracket after Vec**<** is removed.

This is causing several issues in the code I am trying to write for my PR, forcing me to needlessly clone elements - https://github.com/servo/servo/pull/9410#issuecomment-178914587

**Comment by Manishearth** [comment]
Could you paste the entire code that causes this (better yet, push it up to a branch)? I suspect there should be a way to escape the `<&`. Also, there should be a way to avoid the type annotations entirely.

**Comment by craftytrickster** [comment]
Here is an example of the failure:
https://github.com/craftytrickster/servo/commit/fb989ecb932b314b799a023e9a3fa3d819575a9f

Sometimes type annotations are necessary, for example, when performing collect on an iterator. Necessary or not though, such a common language should definitely be allowed in the properties.mako.rs file.

**Comment by Ms2ger** [comment]
Fwiw, using `Vec<_>` might work as a workaround.

**Comment by craftytrickster** [comment]
Vec<_> does actually does help as a workaround thank you. 

Either way, something should be done here, because this can be very confusing for someone who is not expecting this. This was extremely frustrating for me because when syntax errors occur, I assume I did something wrong (especially since I am fairly new to Rust), the last thing I would ever consider is a compilation step error. 

in the worst case scenario the code generator should at least warn that it doesn't support <& in the Rust code. In the absolute worst case, it should at least be documented/comment somewhere.

**Comment by Manishearth** [comment]
Couple of points:

The reason type annotations are required there are because `thing` isn't being used. Once you try pushing things to it the annotation would become unnecessary. I understand that collect often needs an annotation (underscore works well though), but it is rare that a let statement needs a full annotation.

Secondly, I think you are misunderstanding what properties.mako.rs is. It is a Mako template, which _generates_ a Rust file. Mako is an independent Python utility which is not authored by Servo. Its not aware of Rust syntax, and has its own templating syntax. It is the clash between the two syntaxes that is causing this error. I suspect that the solution here would simply be to escape the ampersand or something. It is not Mako's job to understand Rust, so solutions involving changes to Mako are out of scope.

**Comment by craftytrickster** [comment]
I do understand that Mako is used for templating, in fact, I mixed python into my code as well in one of my commits here - https://github.com/craftytrickster/servo/commit/a1de4299781ac9dc62ac7022eea2c52fc43e755a. 

What I did not expect was that it would cause valid Rust to be considered invalid. But I do agree with what you are saying, it is not Mako's job to understand Rust, so we cannot modify it. 

However, one (perhaps unnecessary) suggestion is to perhaps do some kind of pattern search inside rust curly bracket code to look for `<&`, and to at least warn of possible issues before running the code gen step.

Another suggestion would be to at least note this as a potential issue at the top of the properties.mako.rs file in a comment block or maybe mention it in the HACKING_QUICKSTART file.

**Comment by craftytrickster** [comment]
If you agree, I can make a PR adding the following to the comments at the top of properties.mako.rs. If not, I will close the issue.

```rust
// Please note that the Rust sequence "<&" inside this template will be rendered as "&".
// When defining function arguments and return types in Rust, if a generic reference is needed,
// write it as follows: fn foo(Vec<<&Bar>)
```

**Comment by Manishearth** [comment]
It's a more general; that's likely only one of the many syntaxes that won't work. Instead, mention that valid Rust syntax may get mangled by the Mako parser, and the workaround is to escape it.

**Comment by craftytrickster** [comment]
@Manishearth, as suggested, I changed the message to be more general, instead of focusing specifically on the issue I was having. However, since generic references are a pretty important use case (needed to define function params, return types and lifetimes), I kept it as an example in the PR.
