### ISSUE TITLE
Browser API: implement setVisible

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9566]
… along with `mozbrowservisibilitychange` and `getVisible`: https://github.com/paulrouget/mozBrowserAPI/blob/master/BrowserAPI.md#the-setvisible-method

I guess it's just a matter of freezing/thawing the pipeline.

**Comment by paulrouget** [comment]
> I guess it's just a matter of freezing/thawing the pipeline.

That's too aggressive. We need a notion of non visible pipeline: https://github.com/servo/servo/issues/9751

**Comment by paulrouget** [comment]
This will most likely be fixed within https://github.com/servo/servo/issues/9751

**Comment by timvandermeij** [comment]
Fixed by #10225?

**Comment by jdm** [comment]
Yep.
