### ISSUE TITLE
`input.parentNode.oninput` is never called

### ISSUE THREAD

**Issue by Gozala** [servo/servo#9574]
It looks like `input` events do not propagate as they are expected. Here is an example that illustrates the issue:

```html
<html>
<body>
<input id='input' type=text />
<pre id='output'></pre>
</body>
<script>
const input = document.querySelector('#input')
const output = document.querySelector('#output')
const body = document.body

const onEvent =
  event =>
  output.textContent += `${event.currentTarget.tagName} : ${event.type} - ${event.key}\n`

body.onkeydown = onEvent
body.onkeypress = onEvent
body.onkeyup = onEvent
body.oninput = onEvent
input.onkeydown = onEvent
input.onkeypress = onEvent
input.onkeyup = onEvent
input.oninput = onEvent
</script>
</html>
```

Typing `s` into input should produce following output:

```
INPUT : keydown - s
BODY : keydown - s
INPUT : keypress - s
BODY : keypress - s
INPUT : input - undefined
BODY : input - undefined
INPUT : keyup - s
BODY : keyup - s
```

On servo it produces following instead:

```
INPUT : keydown - s
BODY : keydown - s
INPUT : input - undefined
INPUT : keyup - s
BODY : keyup - s
```

**Comment by jdm** [comment]
The radio/checkbox input event [bubbles](http://mxr.mozilla.org/servo/source/components/script/dom/htmlinputelement.rs#872), but the text input event [does not](http://mxr.mozilla.org/servo/source/components/script/dom/htmlinputelement.rs#959).

**Comment by jdm** [comment]
This is a straightforward fix to improve conformance with the [specification](https://html.spec.whatwg.org/multipage/forms.html#text-%28type=text%29-state-and-search-state-%28type=search%29:event-input-input).

**Comment by jdm** [comment]
Unfortunately I don't know that there's a way to write an automated test for this, since the input event should only be dispatched based on explicit user input.
