### ISSUE TITLE
Support XMLHttpRequest({mozSystem:true}) (or something similar)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9582]
In Browser.html, we need to do some XHR calls that ignore CORS.

In Gecko, it's possible to force this by create a XHR like this:

```js
var xhr = new XMLHttpRequest({mozSystem:true}) 
```

See http://mxr.mozilla.org/mozilla-central/source/dom/webidl/XMLHttpRequest.webidl#31

In Servo, we would just need to support this optional JSON parameter in the constructor, and add a `mozSystem` property that would be checked [here](https://github.com/servo/servo/blob/3d63f09361afa80b9d5c4f6b192c9bd8936094b7/components/script/dom/xmlhttprequest.rs#L794).

This property would be only allowed if the mozbrowser pref is set to true.

Would a PR that implements that would be accepted?

Or maybe there is a better would to support this. And ideally, we would use fetch in favor of xhr.

**Comment by Ms2ger** [comment]
I would be very skeptical of supporting this.

**Comment by paulrouget** [comment]
I'm not really happy about polluting existing standards like this.

But this is what Gecko does.

Maybe we should re-think the way we give privileges and add APIs to privileged pages.

We can work around this issue for now in browser.html.

**Comment by metajack** [comment]
Let's step back and discuss why you need to disable CORS in the first place. Maybe an alternate solution can be thought of.

**Comment by Gozala** [comment]
> Let's step back and discuss why you need to disable CORS in the first place. Maybe an alternate solution can be thought of.

One use case we currently have is to query search engines (like api.duckduckgo.com) to provide suggestions in the address bar. Since they don't provide CORS headers we are either left with JSONP option (which arguably is even less secure).

I also do not necessarily like `{mozSystem:true}` API extension, but to implement browser we do need extra things that are not available through standard web APIs just like mozbrowser iframes. Probably better approach would be to figure out a a way (or borrow what fx os APPS defined) to request extra privileges.

**Comment by paulrouget** [comment]
In the meantime, our builds disable cross-origin checks.

**Comment by paulrouget** [comment]
Ideally, such XHR should be done outside of browserhtml, in privileged code ([runtime](https://github.com/servo/servo/issues/7379)]), but that's not going to happen soon.

2 options:
- we could rely on duckduckgo allowing any origins CORS, but that makes us depend on 3rd party.
- we could implement the Chrome option `disable-web-security`. We would start Servo like this: `servo --pref websecurity.disabled`

**Comment by hallvors** [comment]
Presumably there needs to be a mechanism to only allow this for privileged code anyway? Just adding mozSystem:true support without limitations would give Servo a rather big security hole..?

If you already have that concept of privileged threads, perhaps you could just allow cross-origin usage from such threads?

**Comment by paulrouget** [comment]
> If you already have that concept of privileged threads

We don't. The [runtime](https://github.com/servo/servo/issues/7379) is where privilege code will lie. But we don't have it yet.

**Comment by hallvors** [comment]
So as of right now, the request "implement mozSystem:true for XHR" is pretty much equivalent to the request "disable web security"? Ahem..
Early days yet, I suppose.

**Comment by jdm** [comment]
It's possible to restrict it to frames that have the mozbrowser attribute present.

**Comment by paulrouget** [comment]
> It's possible to restrict it to frames that have the mozbrowser attribute present.

Not really. The content of these frames do not require any special privilege. Only their parent document do.
