### ISSUE TITLE
GL context creation failed error on ThinkPad X41 running (L)Ubuntu 15.10

### ISSUE THREAD

**Issue by hallvors** [servo/servo#9585]
Checked out Servo just for fun, to see if it compiled on this computer (it does). However, it doesn't run.. 

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("GL context creation failed")', ../src/libcore/result.rs:746 
```

This computer is a few years old, but it would be fun to see Servo run on it.

https://github.com/tomaka/glutin/issues/314 seemed somewhat relevant, but it's closed (and it's a different project..)

**Comment by genodeftest** [comment]
Same issue here. Intel iGPU on Fedora 23 Linux with X server 1.18.1 running.

tomaka/glutin#314 might be related, there are thoughts/plans to unfork glutin from servo.

**Comment by danieltroger** [comment]
Same issue here too. Standard ubuntu 14.04 desktop install on a MacBook2,1.
#223 seems to be the same issue (?)
Any workaround/fix yet?

**Comment by angyalp** [comment]
Servo requires at least Open GL version 2.1 (the webrenderer requires 3.2). This error could arise, when your GPU does not support it. One workaround is to lower this enforcement to 1.4, which should be supported by old integrated Intel GPUs (check your supported Open GL version by the glxinfo command).
Please note that I've checked out Servo first a few hours ago, so I don't know the codebase, and maybe this is a dirty hack, but it works for me. 

Here is the patch:
```
diff --git a/ports/glutin/window.rs b/ports/glutin/window.rs
index 09a7639..8f426fa 100644
--- a/ports/glutin/window.rs
+++ b/ports/glutin/window.rs
@@ -183,7 +183,8 @@ impl Window {
         }
         match opts::get().render_api {
             RenderApi::GL => {
-                GlRequest::Specific(Api::OpenGl, (2, 1))
+               // GlRequest::Specific(Api::OpenGl, (2, 1))
+                GlRequest::Specific(Api::OpenGl, (1, 4))
             }
             RenderApi::ES2 => {
                 GlRequest::Specific(Api::OpenGlEs, (2, 0))
```

**Comment by angyalp** [comment]
To run servo on machines with older graphics card, one can use llvmpipe (http://www.mesa3d.org/llvmpipe.html) as a software renderer. Llvmpipe uses the CPU for rendering, so the performance will be far from ideal, but even the new webrenderer will work (it requires Open GL 3.2) and you don't need to touch the source code of servo.
I have Kubuntu 15.10 installed with Mesa 11.0.2. To force software rendering, set the   LIBGL_ALWAYS_SOFTWARE environment variable to 1 before starting servo:
`LIBGL_ALWAYS_SOFTWARE=1 ./mach run -r -- http://www.mozilla.com`

**Comment by nox** [comment]
@pcwalton @glennw Can we do something about that? Or is this still fixed?

**Comment by dralley** [comment]
Probably fixed by now?

**Comment by jdm** [comment]
We still have minimum GL requirements, but I don't see a good reason to keep this open.
