### ISSUE TITLE
Use Python's uname and not the external uname

### ISSUE THREAD

**Issue by Jayflux** [servo/servo#9597]
On Windows when running outside of mingw64 i get told my machine is 32Bit and it also cannot find a version of Rust to download.
I've narrowed the problem down to uname -m returning the wrong result in here https://github.com/servo/servo/blob/master/python/servo/command_base.py: 
```
PS C:\Users\Jason> python -c 'import platform; print platform.uname() '
('Windows', 'DESKTOP-P2J3G0V', '8', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel')
PS C:\Users\Jason> uname -m
i686
PS C:\Users\Jason> uname -s
MINGW32_NT-6.2
PS C:\Users\Jason>
```

It looks like it would make sense if we just used the built in platform.uname() function within python, which means we would get more accurate results and support  for windows machines which don't have the uname executable on the PATH.

@vvuk @larsbergstrom  any ideas why this happens? and your thoughts

**Comment by Ms2ger** [comment]
Interestingly, I found this in the `configure` we had before we used cargo:
```sh
OSTYPE=$(uname -s)
CPUTYPE=$(uname -m)

if [ $OSTYPE = Darwin -a $CPUTYPE = i386 ]
then
    # Darwin's `uname -m` lies and always returns i386. We have to use sysctl
    # instead.
    if sysctl hw.optional.x86_64 | grep -q ': 1'
    then
        CPUTYPE=x86_64
    fi
fi

os_type CFG_BUILD_OSTYPE ${OSTYPE}
cpu_type CFG_BUILD_CPUTYPE ${CPUTYPE}

DEFAULT_TARGET="${CFG_BUILD_CPUTYPE}-${CFG_BUILD_OSTYPE}"
```

**Comment by larsbergstrom** [comment]
Regardless of why it happens, it seems like using the built-in `platform.uname()` function in python is the right way to go instead of relying on whatever random `uname` binary happens to be installed and first in the `PATH`.

But no, I don't know why it happens offhand :-)

Thanks for investigating this! Would you be interested in doing a PR to fix it? Or should I open up an `E-Easy` bug for it?

**Comment by Jayflux** [comment]
@larsbergstrom I'm happy to work on this, I just think it's going to be difficult to know/emulate all the possible results it could spit out. As i only have 2 machines
