### ISSUE TITLE
Do not use lookup tables for put_image_data operations

### ISSUE THREAD

**Issue by michaelwu** [servo/servo#9599]
https://github.com/servo/servo/pull/8086 is pretty sketchy. If floating point math is a bottleneck here, then we can switch to fixed point math. Using a 64kbyte lookup table to avoid floating point multiplication isn't worth it. For really fast CPU results, use integer SIMD instructions to handle more than one pixel at a time.

```rust
let alpha = imagedata[src_offset + 3] as u16;
dest.push((imagedata[src_offset + 2] as u16 * alpha / 256) as u8);
// etc
```

128 can be added before dividing to round more accurately.

cc @glennw @jdm

**Comment by magni-** [comment]
I'd like to claim this one if it's still free

**Comment by jdm** [comment]
Go for it!

**Comment by MichaelRFairhurst** [comment]
Is there an existing performance benchmark to compare results, or should I create one?

**Comment by michaelwu** [comment]
Renamed this because unpremultiplying for GetImageData is a harder problem.
