### ISSUE TITLE
should document that pyobjc needs to be installed as well.

### ISSUE THREAD

**Issue by nhirata** [servo/servo#9612]
At least on a fresh install, found out that in order to compile, you need to install pyobjc for the dev version:

pip install -U pyobjc

**Comment by KiChjang** [comment]
What steps have you taken to compile?

**Comment by jdm** [comment]
@nhirata Is based on the message at the end of a build on OS X that says that notifications can't be displayed without installing pyobjc?

**Comment by nhirata** [comment]
The steps I took were using the brew path on Mac 10.10.5:
1) brew install automake pkg-config python cmake
2) pip install virtualenv
3) git clone https://github.com/servo/servo
4) cd servo
5) ./mach build --dev
6) ./mach run tests/html/about-mozilla.html

Is there any other steps I missed from the front page of installing?  Or is there a different page I should be referring to?

Yes, jdm, there was an error similar to the one stating gtk-doc was missing.  (see below).

Also to note : gtk-doc was also missing.
Error message : 
" You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.15 is not found."

Resolution : brew install gtk-doc

**Comment by nhirata** [comment]
To note, after following the above and fixing my link issue with autoconf, I was able to successfully build.

**Comment by jdm** [comment]
@nhirata So what in those steps suggested that pyobjc is necessary?

**Comment by nhirata** [comment]
Oh. hrm.  Maybe it's not necessary; it's needed for notification.  I see that in that error you pointed me to.  

Regardless, I installed both and I was able to compile.

**Comment by maherbeg** [comment]
I had to run the following to ensure I could build/install.

```
  brew install homebrew/versions/autoconf213
  install xcode
  sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
  pip install -U pyobjc
```

**Comment by frewsxcv** [comment]
From what I can tell, there's no actionable item here, so I'm going to close this. pyobjc is not required to run Servo.
