### ISSUE TITLE
Update various canvas properties to use enums instead of DOMString

### ISSUE THREAD

**Issue by jdm** [servo/servo#9617]
https://github.com/whatwg/html/commit/a4b9eef6ff40c394cf6ec9247ce6286795348f3f was merged into the HTML spec, so we should update our Canvas WebIDL declarations to match it.

Spec: https://html.spec.whatwg.org/multipage/scripting.html#canvaslinecap
Code: `components/script/dom/webidls/Canvas2dRenderingContext.webidl`, `components/script/dom/canvasrenderingcontext2d.rs`

**Comment by saurvs** [comment]
I'd like to give this a try.

**Comment by jdm** [comment]
@saurvs Go for it!
