### ISSUE TITLE
Implement Blob response for XHR

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9623]
We currently have document responses implemented and a PR for caching JSON responses (#9621). We'd also like to support Blob responses and caching them correctly as well.

Code: `components/script/dom/xmlhttprequest.rs`
Spec: https://xhr.spec.whatwg.org/#blob-response, https://xhr.spec.whatwg.org/#the-response-attribute
Test: `tests/wpt/web-platform-tests/XMLHttpRequest/response-data-blob.htm`

Blocks #9489.

**Comment by danlrobertson** [comment]
Looks interesting. I'd like to take a crack at this!

**Comment by KiChjang** [comment]
Yes, please do!
