### ISSUE TITLE
mac build error (hbs-pow-sys v0.2.0)

### ISSUE THREAD

**Issue by jongheeyun** [servo/servo#9628]
I got this build error on mac.

>  Compiling hbs-pow-sys v0.2.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#9ae3875a)
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling hbs-common-sys v0.2.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#9ae3875a)
   Compiling harfbuzz-sys v0.1.2
Build failed, waiting for other jobs to finish...
failed to run custom build command for `hbs-pow-sys v0.2.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#9ae3875a)`
Process didn't exit successfully: `/Users/steve/Workspace/servo/target/debug/build/hbs-pow-sys-cf8ae81d4cf55502/build-script-build` (exit code: 101)
--- stderr

It is similar to these issues.
https://github.com/servo/servo/issues/8850
https://github.com/servo/servo/issues/7328

Thanks.

**Comment by larsbergstrom** [comment]
Can you please include the output from the build log to stderr? Without seeing the logs, I would suspect that it is either:
1) Need to `brew install cmake`
2) Need to `brew link --force autoconf`

**Comment by jongheeyun** [comment]
This is a full log.

servo> ./mach build `RUST_BACKTRACE=1` --dev
   Compiling unicode-bidi v0.2.3
   Compiling leaky-cow v0.1.1
   Compiling servo v0.0.1 (file:///Users/steve/Workspace/servo/components/servo)
   Compiling core-foundation-sys v0.2.0
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling serde_codegen v0.6.9
   Compiling advapi32-sys v0.1.2
   Compiling openssl-sys v0.7.1
   Compiling hbs-pow-sys v0.2.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#9ae3875a)
   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#5ac99916)
Build failed, waiting for other jobs to finish...



failed to run custom build command for `hbs-pow-sys v0.2.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#9ae3875a)`
Process didn't exit successfully: `/Users/steve/Workspace/servo/target/debug/build/hbs-pow-sys-cf8ae81d4cf55502/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'Unable to execute "cmake" "" "" "/Users/steve/Workspace/servo/.cargo/git/checkouts/heartbeats-simple-sys-203def3c271a26ee/master/heartbeats-simple"! No such file or directory (os error 2)', /Users/steve/Workspace/servo/.cargo/git/checkouts/heartbeats-simple-sys-203def3c271a26ee/master/hbs-pow-sys/build.rs:45
note: Run with `RUST_BACKTRACE=1` for a backtrace.

[Warning] Could not generate notification! Optional Python module 'pyobjc' is not installed.
Build completed in 177.67s

**Comment by jdm** [comment]
Yep, you're missing cmake according to the stderr output.

**Comment by larsbergstrom** [comment]
You should be able to install it via `brew install cmake`. After that, I would expect the build to go through cleanly, but if not you can do `./mach clean -p hbs-pow-sys`, which will clean out any cached build information during the previous builds.

**Comment by jongheeyun** [comment]
The root cause was cmake.
Cmake already was installed but not linked.

> servo> brew install cmake
Warning: cmake-3.3.2 already installed, it's just not linked

Issue was solved with "brew link cmake"
And I'm surfing the web with THE SERVO :D
Thanks.

**Comment by KiChjang** [comment]
Can we close this issue now?

**Comment by larsbergstrom** [comment]
@jongheeyun Thanks for following up with us and letting us know what the problem was!
