### ISSUE TITLE
Move util::str::is_token to script::dom::bindings::str

### ISSUE THREAD

**Issue by nox** [servo/servo#9640]
Files:
 * components/util/str.rs
 * components/script/dom/bindings/str.rs

**Comment by peterjoel** [comment]
I can take this one.

**Comment by nox** [comment]
Sure!

**Comment by peterjoel** [comment]
@nox These few (moving everything out of util::str) are actually much easier than I anticipated. I've done this one now, but is it better to leave the rest for newcomers, or should I just take the others now too?

**Comment by nox** [comment]
If you feel like this is too easy for you, feel free to let the others available and find something more difficult.

**Comment by KiChjang** [comment]
Fixed in #9642.
