### ISSUE TITLE
Implement error attribute for HTMLMediaElement

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9644]
Code: `components/script/dom/htmlmediaelement.rs`, `components/script/dom/webidls/HTMLMediaElement.webidl`, `components/script/dom/mediaerror.rs` (new file), `components/script/dom/webidls/MediaError.webidl` (new file)
Spec: https://html.spec.whatwg.org/multipage/#dom-media-error
Test: `tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/error-codes/error.html`

Note that the entire test directory for `tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements` is disabled.

**Comment by jdm** [comment]
This is already present in #8454.
