### ISSUE TITLE
mach update-wpt shouldn't commit its changes to git

### ISSUE THREAD

**Issue by peterjoel** [servo/servo#9666]
More likely than not, a user will have other changes (new tests) and will want to combine the commits anyway. 

In my case, I wasted a lot of time not realising that the command would commit to git, and presumed it hadn't changed any files (`git status` said it hadn't!). It's much less confusing if the command just updates files and leaves it to the user to commit the changes.

**Comment by TimNN** [comment]
I totally agree! I just ran into this situation.

**Comment by danlrobertson** [comment]
After looking at `./mach update-wpt --help` I found

```
  --no-patch    Don't create an mq or git commit containing the changes
```

`tests/wpt/harness/wptrunner/commandline.py` defines the argument in `create_parser_update` as

```
    parser.add_argument("--no-patch", action="store_true"...
```

so theoretically we could change this to `--patch`, swap every usage of `no_patch` to `patch`, and `not` every conditional it is used in, but i could be wrong.

```
$ git grep -n no_patch
tests/wpt/harness/wptrunner/update/metadata.py:47:  if state.no_patch:
tests/wpt/harness/wptrunner/update/sync.py:158:     if state.no_patch:
tests/wpt/harness/wptrunner/update/update.py:75:    state.no_patch = kwargs["no_patch"]
tests/wpt/harness/wptrunner/update/update.py:92:    state.no_patch = kwargs["no_patch"]
```

**Comment by jdm** [comment]
Since wptrunner is actually https://github.com/w3c/wptrunner we could theoretically just reverse the argument for our mach invoker, too.

**Comment by danlrobertson** [comment]
@jdm even better :smile: I'll submit a PR in a few
