### ISSUE TITLE
Mach does not build/install new Android apk after initial install

### ISSUE THREAD

**Issue by connorimes** [servo/servo#9674]
Doing an incremental android build after making some changes does not appear to build/deploy a new apk when running:

```
./mach install --release
```

if you've already installed android without deleting the android target directory and rebuilding everything.

**Comment by larsbergstrom** [comment]
Did you do `./mach package --release` after the incremental build but before doing `install` again?

**Comment by connorimes** [comment]
Ah, I seemed to have missed that step in the instructions.  Running the install target appears to have done this automatically the first time so I never knew I missed it.  It would have been nice to see a warning message or some indication from mach that a new build wasn't being installed.

**Comment by nox** [comment]
Seems like this can be closed.
