### ISSUE TITLE
inline + absolute element wrongly positioned

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9687]
``` html
<span style="position: absolute">foo</span><span>bar</span>
```

<img width="226" alt="screen shot 2016-02-18 at 09 08 12" src="https://cloud.githubusercontent.com/assets/373579/13137128/2acde22a-d61f-11e5-8150-8c4b26a8eb48.png">

If `top` is specified, there's no issue.

**Comment by jdm** [comment]
This displays as expected in a recent build.
