### ISSUE TITLE
Remove util::split_off_head

### ISSUE THREAD

**Issue by nox** [servo/servo#9692]
A combination of [`LinkedList::pop_front`](http://doc.rust-lang.org/nightly/std/collections/linked_list/struct.LinkedList.html#method.pop_front) and [`LinkedList::push_back`](http://doc.rust-lang.org/nightly/std/collections/linked_list/struct.LinkedList.html#method.push_back) can be used to replace all call sites of `util::split_off_head`.

Instead of:

```rust
a.append(&mut split_off_head(&mut b))
```

Do:

```rust
a.push_back(b.pop_front().unwrap())
```

Files:
 * components/layout/text.rs
 * components/util/linked_list.rs

**Comment by GuillaumeGomez** [comment]
I take it.

**Comment by frewsxcv** [comment]
Did you check how the performance compares?

**Comment by nox** [comment]
Mmmh, right. I forgot that split_off_head reuses the front linked list cell indeed. I'm closing this, sorry @GuillaumeGomez.
