### ISSUE TITLE
Move util::range to gfx

### ISSUE THREAD

**Issue by nox** [servo/servo#9695]
Files:
 * components/gfx/display_list/mod.rs
 * components/gfx/paint_context.rs
 * components/gfx/lib.rs
 * components/gfx/text/glyph.rs
 * components/gfx/text/shaping/harfbuzz.rs
 * components/gfx/text/text_run.rs
 * components/layout/display_list_builder.rs
 * components/layout/fragment.rs
 * components/layout/inline.rs
 * components/layout/lib.rs
 * components/layout/text.rs
 * components/util/lib.rs
 * components/util/range.rs

**Comment by schuster** [comment]
I'd like to work on this if no one else is.

**Comment by jdm** [comment]
Go for it!

**Comment by SimonSapin** [comment]
I’d rather move it to a new separate crate instead, so that it can be compiled in parallel with other crates, and not rebuilt when touching unrelated code.

**Comment by schuster** [comment]
@SimonSapin So, just a separate crate called "range", then?

**Comment by Ms2ger** [comment]
Yep, that would work.

**Comment by KiChjang** [comment]
Do we want to make it as a separate library instead? Is it useful enough for other projects?

**Comment by SimonSapin** [comment]
Let’s not unless someone asks for it. And even then, it might be better replaced with `std::ops::Range`. Our `Range` pre-dates it, and might pre-date `std::iter::Iterator` as well.
