### ISSUE TITLE
Remove util::vec::Comparator

### ISSUE THREAD

**Issue by nox** [servo/servo#9696]
This fixes the following FIXME from @pcwalton:

```rust
/// FIXME(pcwalton): Workaround for lack of unboxed closures. This is called in
/// performance-critical code, so a closure is insufficient.
```

Unboxed closures landed a long time ago, so we can just use [`Vec::binary_search`](http://doc.rust-lang.org/std/vec/struct.Vec.html#method.binary_search) and [`Vec::binary_search_by`](http://doc.rust-lang.org/std/vec/struct.Vec.html#method.binary_search_by).

The following items need to go away from the module:
 * `Comparator`
 * `BinarySearchMethods`
 * `FullBinarySearchMethods`
 * `DefaultComparator`

In module `gfx::text::glyph`, calls to `binary_search_index` need to be replaced by calls to `Vec::binary_search` in `DetailedGlyphStore::detailed_glyphs_for_entry` and `DetailedGlyphStore::detailed_glyph_with_index`.

In module `gfx::text::text_run`, struct `CharIndexComparator` needs to be replaced by a closure passed to `Vec::binary_search_by` in `TextRun::index_of_first_glyph_run_containing`.

Files:
 * components/gfx/text/glyph.rs
 * components/gfx/text/text_run.rs
 * components/util/vec.rs

**Comment by GuillaumeGomez** [comment]
I take it.
