### ISSUE TITLE
Change most instances of `let foo(bar) = *self;` into self.0

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9698]
`git grep "let \S\+(.\+) = \*self;"` tells me a few locations:
* `components/compositing/surface_map.rs` (ignore this one; the `self.0` syntax doesn't add readability)
* `components/gfx_traits/lib.rs`
* `components/layout/block.rs`
* `components/layout/opaque_node.rs`
* `components/net/fetch/cors_cache.rs`
* `components/profile_traits/mem.rs`
* `components/profile_traits/time.rs`
* `components/script/cors.rs`
* `components/script/dom/bindings/str.rs`
* `components/script/script_thread.rs`
* `components/style/dom.rs`
* `components/style/properties.mako.rs`
* `components/style/value.rs`

cc @danlrobertson

**Comment by frewsxcv** [comment]
How is this an improvement?

**Comment by nox** [comment]
Less verbose.

**Comment by frewsxcv** [comment]
I don't think we have any issues with verbosity in these scenarios though, but that's just my opinion.

A slightly nuanced example, but if a `struct` changes from `struct A(b: u32)` to `struct A(a: u32, b: u32)`, using `.0` as a getter could cause subtle bugs to occur, whereas the current syntax will result in a compile error.

**Comment by KiChjang** [comment]
We do have issues in verbosity in fact. Consider the following taken from `window.rs`:
```rust
    pub fn main_thread_script_chan(&self) -> &Sender<MainThreadScriptMsg> {
        let MainThreadScriptChan(ref sender) = self.script_chan;
        sender
    }
```
There really isn't any need to destructure `self.script_chan` just to get the inner sender in this case. `self.script_chan.0` would be sufficient.

**Comment by malayaleecoder** [comment]
@KiChjang : I would like to take this as my first issue in Servo.

**Comment by frewsxcv** [comment]
Go for it @malayaleecoder!

**Comment by frewsxcv** [comment]
Let us know if you need any help

**Comment by jdm** [comment]
@malayaleecoder Did you end up working on this?

**Comment by faineance** [comment]
I don't mind picking this up.

**Comment by frewsxcv** [comment]
Go for it @faineance

**Comment by malayaleecoder** [comment]
@jdm : I was almost half way through this. Since I guess @faineance has started, will pick it up if it is still not closed.
