### ISSUE TITLE
onclick called twice (webrender)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9702]
```html
<div style="width:20px;height:20px;background:red"></div>
<script>
  var div = document.querySelector("div");
  div.addEventListener("click", function() {
    console.log("click");
  });
</script>
```

`console.log` is called twice.

**Comment by paulrouget** [comment]
https://github.com/servo/servo/blob/267630779316d2291b10ed8e60d0f9f5f2100ab1/components/compositing/compositor.rs#L1294

@glennw can you explain why this is required? 

When this line is commented out, the listener is called only once.

**Comment by glennw** [comment]
That looks like a bug that slipped through when tidying up the WR branch - it should have a return straight after that linked line.

If you want to make a PR for that I'll r+ it, otherwise I'll fix it up when I can.
