### ISSUE TITLE
Webrender breaks the documentation build

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#9704]
See: http://build.servo.org/builders/doc/builds/804

```
 Documenting webrender v0.1.0 (https://github.com/glennw/webrender#463d6e36)
<stdin>:1:1: 1:2 error: unknown start of token: \u{256d}
<stdin>:1 ╭─
          ^~
thread '<unnamed>' panicked at 'Box<Any>', ../src/libsyntax/parse/lexer/mod.rs:1437
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Build failed, waiting for other jobs to finish...
Could not document `webrender`.
```

cc @glennw @pcwalton

**Comment by SimonSapin** [comment]
A code block in a doc-comment probably needs ```` ```notrust ```` or something.

**Comment by glennw** [comment]
It's caused by the artwork by @pcwalton here - https://github.com/glennw/webrender/blob/master/src/batch_builder.rs#L1171

What should I change in the code to make the doc build not panic? (Or is it just a straight bug in the doc tool?).

**Comment by larsbergstrom** [comment]
Ha! That's awesome. 

@alexcrichton @brson Who owns rustdoc and could help us determine if the use of an interesting unicode character in a comment is a compiler/tool bug or not?

**Comment by SimonSapin** [comment]
@glennw @larsbergstrom It’s not a bug, and no Unicode character is more "interesting" than another :) Things indented by 4 spaces or more are code blocks in Markdown, and code blocks in rustdoc default to being doctests that are compiled as rust programs.

This doc-comment need to be changed to use the triple-backtick syntax with a language specifier that is present but not `rust`, like https://github.com/servo/servo/blob/c68fbee03/components/layout/construct.rs#L136-L148

**Comment by glennw** [comment]
@SimonSapin Thanks for the info, I'll add those specifiers. It seems like a bug / missing feature that it causes a panic inside libsyntax without a nice error message detailing where the parse failure occurred though?

**Comment by SimonSapin** [comment]
Fair enough, the error message could be better :)

**Comment by alexcrichton** [comment]
@SimonSapin's diagnostic is correct, and the issue for the error message is https://github.com/rust-lang/rust/issues/12834
