### ISSUE TITLE
a:hover doesn't catch hovers of <label> element inside <a>

### ISSUE THREAD

**Issue by sp3d** [servo/servo#9705]
The following (fairly simple) web page differs in behavior in Servo vs. all the other browsers I tried:
```
<style>
a:hover {
	color: red;
}
</style>
<a href="data:,">link with <label>(label)</label> inside</a>
<p>hovering "(label)" reds link in Gecko and WebKit but not Servo</p>
```
Specifically, hovering any part of the link turns it red in Gecko and WebKit, while in Servo hovering the outer parts of the link turn it red, but hovering the text "(label)" leaves the link blue.

**Comment by ecoal95** [comment]
Thanks for reporting this!

It seems that the hover state isn't propagated to the parent elements.

I'm giving this a shot, even though I'm not know the code involved in that very well.
