### ISSUE TITLE
failed build on arch linux due to miniz-sys

### ISSUE THREAD

**Issue by armistace** [servo/servo#9711]
don't know if this belongs here or at miniz-sys but I can't compile servo on arch as the default build.rs for miniz-sys seems to fail with the default gcc::compile_library options.

Please see [pastebin](http://pastebin.com/JHNTGthJ) for terminal error message

**Comment by paulrouget** [comment]
```
miniz.c:3386:22: error: implicit declaration of function 'ftello' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  mz_int64 cur_ofs = MZ_FTELL64(pZip->m_pState->m_pFile);
```

**Comment by armistace** [comment]
I believe I fixed this by clearing my system level CFLAGS with export CFLAGS="", but should we be able to compile without -Werror?

**Comment by nox** [comment]
I assume this can be closed now, given the lack of new reports.
