### ISSUE TITLE
Incorrect rendering of display: table

### ISSUE THREAD

**Issue by Zirro** [servo/servo#9732]
<img width="703" alt="display-table-testcase" src="https://cloud.githubusercontent.com/assets/3169418/13263207/e9fd4166-da68-11e5-8a43-91121f5ee70f.png">

Comparison between Servo and Firefox on OS X 10.11. Chrome and Safari produce the same result as Firefox. 

Testcase:

``` HTML
<!DOCTYPE html>

<html>

  <head>

    <meta charset="utf-8">

    <title>Testcase</title>

    <style type="text/css">

      div {
        background: rgba(0, 0, 0, 0.7);
        color: rgb(255, 255, 255);
        font-size: 1.3em;
        margin: 5px 0;
        padding: 30px;
        width: 120px;
      }

      .block {
        display: block;
      }

      .table {
        display: table;
      }

    </style>

  </head>

  <body>

    <div class="block">display: block</div>
    <div class="table">display: table</div>

  </body>

</html>
```

**Comment by nox** [comment]
This is still wrong.

**Comment by Tau5** [comment]
I've checked on the latest version and this is FIXED

Tested under Linux x64 (Fedora 40)
Servo version `Servo 0.0.1-fa05214`

![i9732](https://github.com/user-attachments/assets/ae89dd98-9554-42c1-b0fc-6b92c38b616e)
