### ISSUE TITLE
Add a lint to mach to check the MANIFEST.json files are valid JSON 

### ISSUE THREAD

**Issue by ecoal95** [servo/servo#9745]
We have a few `MANIFEST.json` files in `tests/wpt` that could be checked, in order to detect format errors in travis instead of spinning up all the CI infrastructure.

**Comment by Wafflespeanut** [comment]
So, let's parse the JSON files whenever we encounter one, and check whether it's a valid JSON. The new method will live in `python/tidy.py`, and it should be one of those `checking_functions`

**Comment by magni-** [comment]
I'll claim this, just one question: are there tests for `tidy.py` ? Not finding any at first glance

**Comment by jdm** [comment]
There are none. That is #9152.

**Comment by magni-** [comment]
Ahh gotcha. Searched the code, docs, and wiki, but not the issues :+1:
