### ISSUE TITLE
Support Safari's content blocker JSON format

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9749]
We want to be able to block ads. I'd suggest to support Safari's JSON format.

Relevant doc:
- https://webkit.org/blog/3476/content-blockers-first-look/
- https://developer.apple.com/library/ios/documentation/Extensions/Conceptual/ContentBlockingRules/CreatingRules/CreatingRules.html

**Comment by larsbergstrom** [comment]
@metajack and I have discussed this in the past and agree that this is a good way forward. We probably should start with separate bugs for adding support to each of the different components where filtering will need to occur (network stack, style system, etc.).

**Comment by saneyuki** [comment]
As my memory, this is WebKit's implementation dir: https://github.com/WebKit/webkit/tree/master/Source/WebCore/contentextensions

**Comment by paulrouget** [comment]
https://www.opera.com/blogs/desktop/2016/03/native-ad-blocking-feature-opera-for-computers/

**Comment by metajack** [comment]
@jdm has said he'd like to work on this.

**Comment by jdm** [comment]
I've published https://github.com/jdm/content-blocker/ on crates.io. Next steps:
* [ ] read a resource file on startup
* [ ] integrate the request blocking and cookie stripping actions into the network stack 
* [ ] integrate the element hiding action into layout
* [ ] figure out where [Focus'](https://github.com/mozilla/focus) official lists come from

**Comment by jdm** [comment]
Focus' list comes from a transformation of the Tracking Protections lists that Firefox uses. There's a [script](https://github.com/mozilla/focus/blob/master/build-disconnect.py) that turns [them](https://github.com/mozilla/focus/tree/master/shavar-prod-lists) into the JSON files that Safari expects.

**Comment by jdm** [comment]
Work can be seen at https://github.com/servo/servo/compare/master...jdm:content-blocker?expand=1 . Still need to rebase and investigate the performance effects of large lists.

**Comment by nox** [comment]
@metajack Is there any licensing issue if we version Focus' lists in the `resources` directory for now?

**Comment by jdm** [comment]
@cpeterso it was suggested that you might know the answer to the previous question.

**Comment by cpeterso** [comment]
@nox and I spoke on IRC and I referred him to the right people. We definitely need to clear the lists with Product and Policy people before merging.

**Comment by metajack** [comment]
@cpeterso What do you mean "clear the lists"?

**Comment by metajack** [comment]
Oh, just making sure the license is such that it can be distributed?

**Comment by cpeterso** [comment]
The Tracking Protection and Focus lists, which are derived from Disconnect's lists, have been reviewed and approved for specific uses in specific products. If we're using these lists in a different context or product, we should get Mozilla Product and Policy people to sign off again. I shared the contacts with @nox, but let me know if you have any questions.

**Comment by paulrouget** [comment]
Would it be hard to have a way to toggle content blocking for mozbrowser iframes?

Like - maybe via a DOM attribute on the mozbrowser iframe. And ideally, add a property to the `mozbrowserloadevent` to tell how many elements were blocked.

That would be hell of cool to have a "toggle-ad-blocking" button in browserhtml, that also shows the number of blocked elements.

**Comment by nox** [comment]
So what is the actual scope of this if #11500 is only P2? I'm confused. Should we implement toggle right now or not?

**Comment by metajack** [comment]
@nox I think we can land this without a list included and without the ability to turn on and off except from the commandline and then land those other two things separately.

**Comment by paulrouget** [comment]
P2 means "good to have for the June demo". We can demo content blocker without the toggle. But it would require a restart.

**Comment by nox** [comment]
Perfect, consider this landed then. #11413.
