### ISSUE TITLE
Incomplete styles on Wikipedia pages

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#975]
Servo doesn't load the full set of style rules for e.g. http://en.wikipedia.org/wiki/Rust_%28programming_language%29.  From the Firefox debug tools I see that the DOM contains a number of `<style>` elements not present in the static HTML; presumably they are created by scripts.

We currently fail to run some of the scripts on the page (#974) but even when that's fixed, I'm not sure dynamic creation of `<style>` elements will work.

For near-term demo purposes, perhaps we can find a no-JavaScript mode for Wikipedia.

**Comment by frewsxcv** [comment]
Meta-Issue for Wikipedia problems: https://github.com/servo/servo/issues/2554

**Comment by nox** [comment]
This doesn't seem true to me anymore.
