### ISSUE TITLE
Implement visibility API and the notion of non-visible pipeline

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9751]
Spec: https://w3c.github.io/page-visibility/
MDN: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

When a document is not visible (usually a background tab), the document is in "slow mode". `setTimeout` and `setInterval` are called less often, `requestAnimationFrame` is not called and there's probably a lot more things that can slowed down, or stopped.

We can't just use `pipeline.freeze()` / `pipeline.thaw()` as we still need events to occur.

Related issue: https://github.com/servo/servo/issues/9566

**Comment by jmr0** [comment]
I could probably take a stab at this with a little guidance. Let me know if you have any other thoughts I could use as a starting point or any places in the codebase off the top of your head where you'd expect to see some major changes.

**Comment by jdm** [comment]
This has several parts:
* adding the APIs to the Document interface per the specification (Document.webidl, document.rs)
* adding the notion of visibility to Pipeline (pipeline.rs)
* making the Document APIs communicate with the constellation to update the pipeline visibility
* using the pipeline visibility to inhibit animation callbacks (compositor.rs?)
* changing the behaviour of timers based on visibility (maybe timers.rs and timer_scheduler.rs?)

**Comment by paulrouget** [comment]
And I'll add:
- add iframe visibility-related methods and events: https://github.com/servo/servo/issues/9566

This is needed to make a pipeline non visible.

**Comment by paulrouget** [comment]
Re starting point:

I built a fake `setVisible` method that freeze the pipeline: https://github.com/paulrouget/servo/commit/fe29671519c19aaf2ab5b587bd854f209616bc4a

This is wrong because it uses `thaw/freeze` which is too aggressive, but it gives you an idea how to expose an iframe method that would call a pipeline method.

You need to start Servo with `--pref dom.mozbrowser.enabled` and use a `<iframe mozbrowser="true">` to make the `setVisible` method callable.

Hope that helps.

**Comment by jmr0** [comment]
Thanks guys -- I'll start looking at adapting the pipeline and preparing the Document API changes and circle back with any questions. Feel free to assign.

**Comment by jdm** [comment]
@jmr0 Any progress? Any questions?

**Comment by jmr0** [comment]
Hey @jdm, I caught up with Paul over on IRC yesterday and decided I'd focus on the iframe part, since it seems we currently don't support the events necessary to hook to the Document API (e.g. OS lock screen, screen minimized). Ongoing work is here https://github.com/jmr0/servo/commits/visibility_api -- hope to have something deliverable over the weekend. Thanks!

**Comment by jmr0** [comment]
Almost there with this one. Ended up implementing set/getVisible (Browser API) and some of the timer/compositor reactions to Pipeline visibility changes. Need to take a closer look at requestAnimationFrame and add some tests but all the other parts are pretty much complete.

https://github.com/servo/servo/compare/master...jmr0:visibility_api?expand=1

**Comment by paulrouget** [comment]
@jmr0 is it possible to set the iframe visibility property in `ScriptThread::handle_visible_msg`? Then you won't have to do it in `iframe::SetVisible`. 

`GetVisibility` is usually called after the event [`mozbrowservisibilitychange`](https://github.com/paulrouget/mozBrowserAPI/blob/master/BrowserAPI.md#mozbrowservisibilitychange) is received (which will happen in `handle_visible_msg`), so we don't really care about the intermediate stage between when SetVisible is called and when the actually visibility changed.

Does that make sense?

Also - the fact that 1) there is an event and 2) getVisibility() is async, doesn't make a lot of sense. It's a consequence of how it was built in Gecko. I think getVisibility() should not be async.

**Comment by jmr0** [comment]
@paulrouget Yeah that makes perfect sense, I had added that hack to `SetVisible` for now but there's no need to do that if we stick to a sync `GetVisible`. I'll go ahead and make that change.

**Comment by jmr0** [comment]
@paulrouget @jdm We can probably close this and https://github.com/servo/servo/issues/9566, and possibly open a new related issue with the caveats and parts that weren't covered in https://github.com/servo/servo/pull/10225 (as per my PR comment) and include anything else you folks can think of. Happy to file that if you agree!

**Comment by jdm** [comment]
That's reasonable. Please do!
