### ISSUE TITLE
persistent storage

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9752]
IndexedDB, localStorage, File API, whatever, … we need something to store settings and sessions in Browser.html.

Apparently, localStorage is implemented, but it's not persistent across sessions.

Maybe it's easier to make it persistent than implement other APIs.

**Comment by jdm** [comment]
This is a student project this quarter: https://github.com/servo/servo/wiki/Persistent-sessions-student-project

**Comment by paulrouget** [comment]
This works now.
