### ISSUE TITLE
Slow with browser.html

### ISSUE THREAD

**Issue by thekidfrankensteinthrewinapond** [servo/servo#9758]
I created a release build as instructed here: https://github.com/servo/servo#normal-build

Then I ran with browser.html as instructed here: https://github.com/browserhtml/browserhtml#running-in-servo

It is very slow. Here are my specs:

```
MacBook Pro (Retina, 15-inch, Early 2013)
Processor: 2.7 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 4000 1024 MB
```

Tried a few sights, duckduckgo.com, espn.com, cnn.com, all very slow.  Actually made my entire computer slow if that helps.

**Comment by thekidfrankensteinthrewinapond** [comment]
I should add that I added the `-w` flag. So I ran:

```
./mach run -r -w -- -b --pref dom.mozbrowser.enabled http://localhost:6060
```

**Comment by paulrouget** [comment]
> ./mach run -r -w -- -b --pref dom.mozbrowser.enabled http://localhost:6060

That won't work. The `-w` option is for servo, not mach.

You want to run it that way:

> ./mach run -r -- -b -w --pref dom.mozbrowser.enabled http://localhost:6060

**Comment by paulrouget** [comment]
@thekidfrankensteinthrewinapond Using WebRender should fix it. I'm closing this issue. Please let me know if it's still slow after using `-w`.

**Comment by thekidfrankensteinthrewinapond** [comment]
That didn't help as far as I can tell, still very slow.  I had also run `npm run servo` in the browserhtml project which uses the `-w` and same result.  Some sites, like duckduckgo.com don't show up at all.

**Comment by paulrouget** [comment]
> That didn't help as far as I can tell, still very slow.

What is slow?

> Some sites, like duckduckgo.com don't show up at all.

Known, but this is unrelated.

**Comment by thekidfrankensteinthrewinapond** [comment]
Scrolling. Going to a couple of sites; cnn.com and sciencedaily.com and scrolling, there is quite a daily between scrolling on the touchpad and the browser scrolling. It's also very choppy. Some times it causes my fan to turn on.

**Comment by paulrouget** [comment]
Can you try without the `-b` option?

**Comment by thekidfrankensteinthrewinapond** [comment]
That feels a lot better. Not as good as Firefox but I don't know if that is to be expected at this point or not. Is there a site where I can run benchmarks?

**Comment by paulrouget** [comment]
> That feels a lot better.

Ok. So that's a known issue then.

**Comment by paulrouget** [comment]
This should get better once https://github.com/servo/glutin/pull/68 lands.

**Comment by thekidfrankensteinthrewinapond** [comment]
Great, thanks! Is there a site where I can run benchmarks?
