### ISSUE TITLE
Incorporate Windows-based CI (AppVeyor et al)

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#9767]
Previous attempt https://github.com/servo/servo/pull/9406

**Comment by larsbergstrom** [comment]
I've been working on this more here:
https://github.com/larsbergstrom/servo/tree/appveyor

**Comment by UK992** [comment]
I've been playing around Appveyor lately again and it work now.
Took 1 hour and 10 minutes to build, about half of this time only mozjs stuff.

https://ci.appveyor.com/project/UK992/servo-hga0y/build/1.0.130
https://github.com/UK992/servo/commit/1cb6952b350120d5ba39b020a932dc5c62cbf991

**Comment by larsbergstrom** [comment]
@UK992 OMG, that's awesome! Fantastic work :-)

The nice thing about mozjs is that we should have `CCACHE` support, so we may be able to have that be a one-time (or once per-upgrade per-machine) deal.

**Comment by larsbergstrom** [comment]
Hrm, it looks like heapsize is still failing with:
```
note: C:\Users\appveyor\AppData\Local\Temp\1\rustc.YtB1bF5ggNNd\libheapsize-da165bc9088f0d78.rlib(heapsize-da165bc9088f0d78.0.o): In function `heapsize::heap_size_of':
C:/projects/servo/.cargo\registry\src\github.com-88ac128001ac3a9a\heapsize-0.2.5\src/lib.rs:41: undefined reference to `je_malloc_usable_size'
collect2.exe: error: ld returned 1 exit status
 
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
```

cc @Jayflux

**Comment by nox** [comment]
> heapsize-0.2.5

You need to update that.

**Comment by UK992** [comment]
And also need this patch https://github.com/UK992/servo/commit/bf43c1c1ed010a3cc2fbc00e0f6090f386bcebf8 to solve alloc_jemalloc crate problem

**Comment by UK992** [comment]
And just for information, if building took more than 1 hour will hit build timeout, in that case, contact Appveyor support team for extend build timeout to 2 hours. I did this too.

**Comment by larsbergstrom** [comment]
@UK992 I went ahead and contacted them, too, and they let me try the premium/2CPU machines. They took the build down to 52 minutes. I'm looking into possibly getting a premium contract for the Servo GH org :-)
