### ISSUE TITLE
Implement HTML table section attributes

### ISSUE THREAD

**Issue by jdm** [servo/servo#9769]
A previous attempt was #8745.
Spec: https://html.spec.whatwg.org/multipage/tables.html#dom-table-thead

**Comment by jdm** [comment]
Any further work should build on the previous effort by addressing review comments and adding tests.

**Comment by yoava333** [comment]
I'd like to give it a try

**Comment by jdm** [comment]
Please do!

**Comment by KiChjang** [comment]
Fixed by #9980.
