### ISSUE TITLE
FOUC (flash of unstyled content) on pages with external stylesheets

### ISSUE THREAD

**Issue by mbrubeck** [servo/servo#9771]
When I open https://servo.org/ in Servo, I initially see the content without any author styles applied. Then about a second later the page is re-rendered with all the styles.

**Comment by gkbrk** [comment]
This happens to me on other websites as well.

**Comment by mbrubeck** [comment]
Now that #9832 has loaded, this should work as soon as `<link rel="stylesheet">` elements delay the load event (part of #1416).

**Comment by nox** [comment]
This has been done.
