### ISSUE TITLE
Failed building servo on windows 7 64-bit

### ISSUE THREAD

**Issue by officer** [servo/servo#9775]
Building is failed with [E0463] on windows 7 64-bit.
Here is the verbose error message.

> $ ./mach build --dev --verbose
> cargo build -v
>        Fresh inflate v0.1.0
>        Fresh pkg-config v0.3.5
>        Fresh heapsize_plugin v0.1.3
>        Fresh cfg-if v0.1.0
>        Fresh regex-syntax v0.2.3
>        Fresh utf8-ranges v0.1.3
>        Fresh typeable v0.1.2
>        Fresh semver v0.1.20
>        Fresh libc v0.2.4
>        Fresh brotli v0.3.20 (https://github.com/ende76/brotli-rs#c243045b)
>        Fresh rustc_version v0.1.6
>        Fresh memchr v0.1.10
>        Fresh getopts v0.2.14
>        Fresh httparse v1.1.0
>        Fresh void v0.0.5
>        Fresh freetype v0.1.0 (https://github.com/servo/rust-freetype#d564ff90)
>        Fresh unreachable v0.0.2
>        Fresh bitflags v0.3.3
>        Fresh matches v0.1.2
>        Fresh make-cmd v0.1.0
>        Fresh language-tags v0.2.0
>        Fresh unicode-normalization v0.1.2
>        Fresh unicode-bidi v0.2.3
>        Fresh winapi v0.2.5
>        Fresh smallvec v0.1.5
>        Fresh traitobject v0.0.1
>        Fresh debug_unreachable v0.0.6
>        Fresh stb_image v0.2.1
>        Fresh tenacious v0.0.15 (https://github.com/Manishearth/rust-tenacious#ea664e2d)
>        Fresh gdi32-sys v0.1.1
>        Fresh log v0.3.4
>        Fresh simd v0.1.0 (https://github.com/huonw/simd#03de1cd0)
>        Fresh aho-corasick v0.5.1
>        Fresh hpack v0.2.0
>        Fresh aster v0.13.1
>        Fresh regex v0.1.51
>    Compiling script v0.0.1 (file:///C:/msys64/home/user/servo/components/servo)
>      Running `C:/msys64/home/user/servo/target\debug\build\script-e152bbb56ce3a99f\build-script-build`
>        Fresh phf_shared v0.7.12
>        Fresh xml-rs v0.2.2
>        Fresh phf v0.7.12
>        Fresh expat-sys v2.1.2
>        Fresh caseless v0.1.1
>        Fresh mime v0.1.0
>        Fresh fnv v1.0.0
>        Fresh encoding_index_tests v0.1.4
>        Fresh lazy_static v0.1.15
>        Fresh color_quant v1.0.0
>        Fresh encoding-index-korean v1.20141219.5
>        Fresh encoding-index-simpchinese v1.20141219.5
>        Fresh encoding-index-tradchinese v1.20141219.5
>        Fresh shared_library v0.1.2
>        Fresh ref_slice v0.1.0
>        Fresh solicit v0.4.4
>        Fresh angle v0.1.0 (https://github.com/ecoal95/angle?branch=servo#b31e70ef)
>        Fresh quasi v0.7.0
>        Fresh quasi_codegen v0.7.0
>        Fresh env_logger v0.3.1
>        Fresh quasi_macros v0.7.0
>        Fresh khronos_api v1.0.0
>        Fresh serde_codegen v0.6.14
>        Fresh openssl-sys v0.7.1
>        Fresh glob v0.2.10
>        Fresh serde_macros v0.6.14
>        Fresh encoding-index-singlebyte v1.20141219.5
>        Fresh byteorder v0.4.2
>        Fresh hbs-common-sys v0.2.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#9ae3875a)
>        Fresh mime_guess v1.3.0
>        Fresh rustc-serialize v0.3.16
>        Fresh gl_generator v0.4.2
>        Fresh unicase v1.0.1
>        Fresh gleam v0.2.5
>        Fresh servo-freetype-sys v2.4.11
>        Fresh mac v0.0.2
>        Fresh servo-fontconfig-sys v2.11.3
>        Fresh futf v0.1.1
>        Fresh servo-fontconfig v0.2.0
>        Fresh lzw v0.9.0
>        Fresh hbs-pow-sys v0.2.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#9ae3875a)
>        Fresh gif v0.6.0
>        Fresh winapi-build v0.1.1
>        Fresh hbs-pow v0.2.0 (https://github.com/libheartbeats/heartbeats-simple-rust.git#0f46659b)
>        Fresh encoding-index-japanese v1.20141219.5
>        Fresh advapi32-sys v0.1.2
>        Fresh encoding v0.2.32
>        Fresh rand v0.3.12
>        Fresh gcc v0.3.17
>        Fresh uuid v0.1.18
>        Fresh phf_generator v0.7.12
>        Fresh num v0.1.28
>        Fresh enum_primitive v0.1.0
>        Fresh quickersort v1.0.1
>        Fresh serde v0.6.15
>        Fresh serde_json v0.6.0
>        Fresh bincode v0.4.0 (https://github.com/TyOverby/bincode#590a862b)
>        Fresh openssl-sys-extras v0.7.1
>        Fresh ipc-channel v0.2.0 (https://github.com/servo/ipc-channel#1a1f4c97)
>        Fresh openssl v0.7.1
>        Fresh miniz-sys v0.1.7
>        Fresh ws2_32-sys v0.2.0
>        Fresh immeta v0.3.1
>        Fresh flate2 v0.2.11
>        Fresh dwmapi-sys v0.1.0
>        Fresh png v0.4.0
>        Fresh shell32-sys v0.1.1
>        Fresh image v0.5.4
>        Fresh deque v0.3.1
>        Fresh kernel32-sys v0.2.1
>        Fresh phf_codegen v0.7.12
>        Fresh harfbuzz-sys v0.1.2
>        Fresh heapsize v0.3.3
>        Fresh cssparser v0.5.3
>        Fresh string_cache v0.2.10
>        Fresh unicode-script v0.1.1
>        Fresh url v0.5.5
>        Fresh selectors v0.5.1
>        Fresh num_cpus v0.2.10
>        Fresh net2 v0.2.19
>        Fresh euclid v0.6.2
>        Fresh plugins v0.0.1 (file:///C:/msys64/home/user/servo/components/servo)
>        Fresh time v0.1.34
>        Fresh user32-sys v0.1.2
>        Fresh offscreen_gl_context v0.1.0 (https://github.com/ecoal95/rust-offscreen-rendering-context#aa899f18)
>        Fresh cookie v0.2.2
>        Fresh clipboard-win v1.6.2
>        Fresh servo-glutin v0.4.9
>        Fresh hyper v0.7.0
>        Fresh clipboard v0.1.0 (https://github.com/aweinstock314/rust-clipboard#241deb1b)
>        Fresh servo-skia v0.20130412.6
>        Fresh webdriver v0.4.0 (https://github.com/jgraham/webdriver-rust.git#9dffcbe4)
>        Fresh websocket v0.15.0
>        Fresh azure v0.4.1 (https://github.com/servo/rust-azure#d318e2d8)
>        Fresh profile_traits v0.0.1 (file:///C:/msys64/home/user/servo/components/servo)
>        Fresh app_units v0.2.1
>        Fresh layers v0.2.2 (https://github.com/servo/rust-layers#dd28dbee)
>        Fresh webrender_traits v0.1.0 (https://github.com/servo/webrender_traits#8ccc1608)
>        Fresh scoped_threadpool v0.1.6
>        Fresh utf-8 v0.6.0
>    Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#5ac99916)
>      Running `C:/msys64/home/user/servo/target\debug\build\mozjs_sys-e411d274df144795\build-script-build`
>    Compiling webrender v0.1.0 (https://github.com/servo/webrender#c23d3cfe)
>      Running `rustc C:/msys64/home/user/servo/.cargo\\git\\checkouts\\webrender-ec406de34643a7ef\\master\\src\\lib.rs --crate-name webrender --crate-type lib -g -C metadata=0c5aaf72580d6356 -C extra-filename=-0c5aaf72580d6356 --out-dir C:/msys64/home/user/servo/target\\debug\\deps --emit=dep-info,link -L dependency=C:/msys64/home/user/servo/target\\debug\\deps -L dependency=C:/msys64/home/user/servo/target\\debug\\deps --extern time=C:/msys64/home/user/servo/target\\debug\\deps\\libtime-22c21fe32894ddad.rlib --extern webrender_traits=C:/msys64/home/user/servo/target\\debug\\deps\\libwebrender_traits-7eb44edd2512281d.rlib --extern scoped_threadpool=C:/msys64/home/user/servo/target\\debug\\deps\\libscoped_threadpool-65f1199f4eef3265.rlib --extern num=C:/msys64/home/user/servo/target\\debug\\deps\\libnum-3075d01c27559791.rlib --extern offscreen_gl_context=C:/msys64/home/user/servo/target\\debug\\deps\\liboffscreen_gl_context-cc3be91171f9cf84.rlib --extern lazy_static=C:/msys64/home/user/servo/target\\debug\\deps\\liblazy_static-007034d2ad8108ce.rlib --extern ipc_channel=C:/msys64/home/user/servo/target\\debug\\deps\\libipc_channel-43fb51f8ea3e2695.rlib --extern gleam=C:/msys64/home/user/servo/target\\debug\\deps\\libgleam-41c567775505c2ff.rlib --extern euclid=C:/msys64/home/user/servo/target\\debug\\deps\\libeuclid-524c3cbc67a4eca3.rlib --extern fnv=C:/msys64/home/user/servo/target\\debug\\deps\\libfnv-9239b2edf57ebfa1.rlib --extern app_units=C:/msys64/home/user/servo/target\\debug\\deps\\libapp_units-61d2fde34a5e4053.rlib --cap-lints allow`
>        Fresh tendril v0.2.1
>        Fresh html5ever v0.5.1
>        Fresh xml5ever v0.1.1 (https://github.com/Ygg01/xml5ever#6c701706)
>        Fresh libz-sys v1.0.0
> C:/msys64/home/user/servo/.cargo\git\checkouts\webrender-ec406de34643a7ef\master\src\lib.rs:57:1: 57:23 **error: can't find crate for `freetype` [E0463]**
> C:/msys64/home/user/servo/.cargo\git\checkouts\webrender-ec406de34643a7ef\master\src\lib.rs:57 extern crate freetype;
>                                                                                                ^~~~~~~~~~~~~~~~~~~~~~
> error: aborting due to previous error
> Build failed, waiting for other jobs to finish...
> Could not compile `webrender`.
> 
> Caused by:
>   Process didn't exit successfully: `rustc C:/msys64/home/user/servo/.cargo\git\checkouts\webrender-ec406de34643a7ef\master\src\lib.rs --crate-name webrender --crate-type lib -g -C metadata=0c5aaf72580d6356 -C extra-filename=-0c5aaf72580d6356 --out-dir C:/msys64/home/user/servo/target\debug\deps --emit=dep-info,link -L dependency=C:/msys64/home/user/servo/target\debug\deps -L dependency=C:/msys64/home/user/servo/target\debug\deps --extern time=C:/msys64/home/user/servo/target\debug\deps\libtime-22c21fe32894ddad.rlib --extern webrender_traits=C:/msys64/home/user/servo/target\debug\deps\libwebrender_traits-7eb44edd2512281d.rlib --extern scoped_threadpool=C:/msys64/home/user/servo/target\debug\deps\libscoped_threadpool-65f1199f4eef3265.rlib --extern num=C:/msys64/home/user/servo/target\debug\deps\libnum-3075d01c27559791.rlib --extern offscreen_gl_context=C:/msys64/home/user/servo/target\debug\deps\liboffscreen_gl_context-cc3be91171f9cf84.rlib --extern lazy_static=C:/msys64/home/user/servo/target\debug\deps\liblazy_static-007034d2ad8108ce.rlib --extern ipc_channel=C:/msys64/home/user/servo/target\debug\deps\libipc_channel-43fb51f8ea3e2695.rlib --extern gleam=C:/msys64/home/user/servo/target\debug\deps\libgleam-41c567775505c2ff.rlib --extern euclid=C:/msys64/home/user/servo/target\debug\deps\libeuclid-524c3cbc67a4eca3.rlib --extern fnv=C:/msys64/home/user/servo/target\debug\deps\libfnv-9239b2edf57ebfa1.rlib --extern app_units=C:/msys64/home/user/servo/target\debug\deps\libapp_units-61d2fde34a5e4053.rlib --cap-lints allow` (exit code: 101)
> Build completed in 16.04s

Of course, I installed freetype for mingw.

**Comment by AgentFries** [comment]
I have found the exact same issue on windows 10 and windows 8.1

**Comment by lygstate** [comment]
I think the problems comes from the appveyor.xml doesn't calling the method
`update-core`
That's the difference between the servo README.md & appveryor.xml,
so we may need to fill the gap between README.md & appveryor.xml, or 
we need creating a mirror version of msys2

**Comment by zeusintuivo** [comment]
I have researched and documented an effective way to have windows environments set up for 32 and 64 bits in Windows 7. I assume this will work in all windowses. 
Please see documentation I posted in this ticket. #12356

**Comment by nox** [comment]
I don't think we have this particular kind of build error anymore.
