### ISSUE TITLE
Compute or provide inter- and intra-word spacing data to layout and rendering

### ISSUE THREAD

**Issue by burg** [servo/servo#98]
CSS properties 'word-spacing' and 'letter-spacing' can induce extra spacing between individual letters (glyphs?) or words. Gecko implements this, depending on situation, by either providing an object that can compute spacing for a run of text (`PropertyProvider`), or a `Spacing` array that maps char offsets to extra spacing.

For Servo, it seems that we will want to recompute this information for layout, and memoize it when putting it into a DisplayItem.

**Comment by mbrubeck** [comment]
This is done.
