### ISSUE TITLE
clear previous stored values onClick

### ISSUE THREAD

**Issue by ketanpawar** [servo/servo#9802]
i want to clear the previous stored values. it gives me the list of already entered values onClick.
so i want to use this code in pqgrid:
" readonly onfocus="$(this).removeAttr('readonly');"  "
how to use this line in pqgrid while adding and editing
kindly help me.

**Comment by jdm** [comment]
@ketanpawar I think this is filed in the wrong repository. This doesn't appear to be a bug related to Servo.

**Comment by jdm** [comment]
That being said, if this is a website issue you have encountered while using Servo, please provide more information to help us understand it (such as the website in question and the steps to reproduce the problem).
