### ISSUE TITLE
Reenable the `CaretPosition-001.htm` css-test

### ISSUE THREAD

**Issue by rilut** [servo/servo#9805]
css-test against `cssom-view-1_dev/html/CaretPosition-001.htm`  causes an intermittent error in https://github.com/servo/servo/pull/8932#issuecomment-190291224 while doing homu `mac-rel-css` test, thus should be disabled.

**Comment by KiChjang** [comment]
This should be done in your PR.

**Comment by jdm** [comment]
Once https://github.com/w3c/csswg-test/pull/1058/ is merged and we have updated our local copy of csswg-test, we should reenable the test.

**Comment by rilut** [comment]
@KiChjang of course, but... https://github.com/servo/servo/pull/8932#issuecomment-190291224 


> disabled: \<URL of the issue that you have to file about the disabling>

**Comment by KiChjang** [comment]
@rilut See #9804 for reference.
