### ISSUE TITLE
tidy checks must be different for quoted text

### ISSUE THREAD

**Issue by psdh** [servo/servo#9806]
As of now tidy will report a problem in `a = "foo=bar";` as well due to the missing spaces around `=`

**Comment by Wafflespeanut** [comment]
Code: `python/tidy.py`

**Comment by jdm** [comment]
I'm not certain that the solution here is clear, given the intricacies of the tidy rules.

**Comment by Wafflespeanut** [comment]
Yeah, I now realize that modifying the regex stuff is probably a bad idea. Maybe we can explicitly check for (single or double) quotes, split the line, and [pass the stuff](https://github.com/servo/servo/blob/a9c8f592a9521376678187c6917449e3dd48c373/python/tidy.py#L345) surrounding the quotes for regex matching.

**Comment by MichaelRFairhurst** [comment]
See PR

it actually already tries to strip strings first, it just couldn't handle escapes. The correct repro steps are

    a = "\"foo=bar"

but no longer an issue!
