### ISSUE TITLE
Refactor CSS transform parsing so it can be reused for DOMMatrix

### ISSUE THREAD

**Issue by peterjoel** [servo/servo#9807]
The [w3c Geometry specification](https://drafts.fxtf.org/geometry) specifies a constructor for DOMMatrix and DOMMatrixReadOnly as well as the method [`setMatrixValue`](https://drafts.fxtf.org/geometry/#dom-dommatrix-setmatrixvalue) which use the same syntax as [CSS transforms](https://www.w3.org/TR/css-transforms-1/#svg-syntax), which is also used for SVG.

In its current form, this code cannot be re-used for DOMMatrix.

The relevant file is https://github.com/servo/servo/blob/b3b6f092062eed2f323da88991553d0285da6a16/components/style/properties.mako.rs#L3771

**Comment by jdm** [comment]
Is it not usable if you create a ParserContext value and Parser object, then invoke transform::parse directly?

**Comment by jdm** [comment]
See `parse_color` in `canvasrenderingcontext2d.rs` for an example. The code in properties.rs could even be delegated to a parse function that doesn't need a ParserContext argument, since it's unused.

**Comment by peterjoel** [comment]
@jdm Thanks. I'll take a look

**Comment by peterjoel** [comment]
@jdm There are different matrix implementations floating around there though, which could be unified using euclid.

**Comment by mrobinson** [comment]
Stylo is now part of Gecko.
