### ISSUE TITLE
Invalidate window drop shadow on window move

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9812]
With https://github.com/servo/servo/pull/9809, window drop shadow are not updated after window resize/move.

See: https://developer.apple.com/library/mac/samplecode/RoundTransparentWindow/Listings/Classes_CustomView_m.html#//apple_ref/doc/uid/DTS10000401-Classes_CustomView_m-DontLinkElementID_6

**Comment by nox** [comment]
@paulrouget Is that only on OS X?

**Comment by paulrouget** [comment]
> Is that only on OS X?

Yes.

**Comment by paulrouget** [comment]
Requires: https://github.com/servo/glutin/pull/75

**Comment by paulrouget** [comment]
Works now.
