### ISSUE TITLE
Pauses during animation of frames in servo (particularly the summit.html demo)

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#982]
While I have been unable to reproduce the permanent pauses reported by @jdm and @metajack, servo will pause the animation for between 1 and 10 seconds for either the rust logo, the longcat, or both. At the moment the pause begins, the rest of the user interface for the computer also momentarily freezes up, and some first-order inspection leads me to believe that servo is in the middle of several graphics API calls simultaneously.

I'm going to keep debugging, but my initial suspicion is that there's a race condition associated with making some of these graphics calls and one of the threads gets temporarily blocked.

**Comment by mrobinson** [comment]
longcat is looking super smooth for me and this bug was likely fixed, at least by the switch to WebRender. Feel free to reopen if this is still an issue though.
