### ISSUE TITLE
Remove the constructor of XMLDocument

### ISSUE THREAD

**Issue by nox** [servo/servo#9820]
There is no constructor on XMLDocument in the spec.

Files:
 * components/script/dom/xmldocument.rs
 * components/script/dom/webidls/XMLDocument.webidl

**Comment by Ms2ger** [comment]
Also remove `tests/wpt/metadata/dom/nodes/XMLDocument-constructor.html.ini`

**Comment by KiChjang** [comment]
@creativcoder claimed in IRC.

**Comment by KiChjang** [comment]
#9825

**Comment by Hywan** [comment]
Should be closed since #9825 has been merged.

**Comment by paulrouget** [comment]
> Should be closed since #9825 has been merged.

Yes. Thanks.
