### ISSUE TITLE
CSS: `transform: rotate(-45deg)` is broken.

### ISSUE THREAD

**Issue by pygy** [servo/servo#9847]
No idea what happens but [this simple page](http://pygy.github.io/servo-rendering-bugs/rotated-text.html) should not look like this (webrender):
![screen shot 2016-03-03 at 00 33 25](https://cloud.githubusercontent.com/assets/54515/13479546/fb50b842-e0d7-11e5-825e-a3ec2987d9a1.png)

nor like this (no webrender):
![screen shot 2016-03-03 at 00 33 41](https://cloud.githubusercontent.com/assets/54515/13479559/124e6760-e0d8-11e5-9e4c-fb265dc88d27.png)

More likely like this (Chrome):
![screen shot 2016-03-03 at 00 35 39](https://cloud.githubusercontent.com/assets/54515/13479570/25cca59a-e0d8-11e5-8e83-066a3921be18.png)

Or like this (Firefox), assuming Servo has the same pixel snapping issue:
![screen shot 2016-03-03 at 00 35 53](https://cloud.githubusercontent.com/assets/54515/13479598/654838b0-e0d8-11e5-9da2-e5dd7d69876d.png)

**Comment by paulrouget** [comment]
(For the record)

```html
<!doctype html>
<title>rotated text—wavy baseline</title>
<style>
div{
  line-height:1.9em;
  font-size:0.7em;
  transform:rotate(-45deg);
  width:200px;
}
 body{
  padding-top:4em;
  font-family: sans-serif;
}
</style>
<div>IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII</div>
<div>IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII</div>
<div>ooooooooooooooooooooooooooooooooo</div>
<div>ooooooooooooooooooooooooooooooooo</div>
```

**Comment by pygy** [comment]
That repo is here to stay ;-)

**Comment by jdm** [comment]
This works now.
