### ISSUE TITLE
Text pixel snapping issues on low DPI display.

### ISSUE THREAD

**Issue by pygy** [servo/servo#9848]
Hello again, as discussed on IRC, Servo shares with Firefox issues when rendering text on low DPI displays (1:1 ratio).

They are most likely related so I grouped them all in the same issue. If my assumption turns out to be false, I'll split it if necessary.

---

The first issue is an the fact that `text-shadow` offsets are inconsistent. I used 8 shadows to simulate `text-stroke`. The effect doesn't look bad in Chrome or Safari (or FF on a high DPI Windows machine), but on my dev Macbook Air, the outline bulges on either side depending on factors I ignore.

Live: http://pygy.github.io/servo-rendering-bugs/text-shadow-alignment.html

Servo (without webRender, with it I get a blank page):
![screen shot 2016-03-02 at 23 23 14](https://cloud.githubusercontent.com/assets/54515/13479018/6b18378a-e0d4-11e5-86d2-1804f4d63846.png)

Chrome:
![screen shot 2016-03-02 at 23 24 19](https://cloud.githubusercontent.com/assets/54515/13479082/d4316c64-e0d4-11e5-8f38-b6fdda5a9d45.png)

---

The second issue is about jiggly kerning when the text is centered and you slowly resize the container (or the window).

Live: http://pygy.github.io/servo-rendering-bugs/jiggly-kerning.html

No need for screen caps, it has to be experienced live while resizing the width of the window. It happens with and without webrender.

---

The last one is trickier because I get it [in the github ribbon of this complex page](http://pygy.github.io/servo-rendering-bugs/j2c/j2c/index.html), but the [reduced test case](http://pygy.github.io/servo-rendering-bugs/rotated-text.html) breaks in other ways in Servo (#9847). Once the rotation issues are corrected, though I'd expect the baseline to be as jiggly as it is in FF (since the GitHub ribbon is likewise subtly broken in FF).

That page is badly broken in many ways, please focus on the wavy baseline of the rotated GitHub ribbon:
![screen shot 2016-03-03 at 00 43 45](https://cloud.githubusercontent.com/assets/54515/13479698/126c89a6-e0d9-11e5-8408-556f664a3e4e.png)

**Comment by pygy** [comment]
Oh, yes, I forgot, and it may not make much sense unless you looked at the source or tried to interact with the last example: the GitHub ribbon is not an image, it's made with HTML+CSS.

**Comment by nox** [comment]
Not true anymor.
