### ISSUE TITLE
Infinite reflow

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9855]
Some website never stop reflowing.

I don't have example or STR just yet, but I want this to be tracked.

**Comment by paulrouget** [comment]
It happens with http://robert.ocallahan.org/

**Comment by paulrouget** [comment]
I'm under the impression this is not happening anymore.

@pcwalton can you confirm?

**Comment by pcwalton** [comment]
I'm pretty sure I still see this a lot.

**Comment by pcwalton** [comment]
I think this bug is not really actionable anymore. Can we remove the browserhtml-P1 tag?

**Comment by pcwalton** [comment]
Or, even if actionable, this is kind of a vague metabug that we'll never really know if we've solved 100%.

**Comment by pcwalton** [comment]
Removing browserhtml-P1 in the absence of comments. Please feel free to add back if it's necessary.

**Comment by nox** [comment]
Let's close this.
