### ISSUE TITLE
Can't drag titlebar-less windows (osx)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9856]
This started with https://github.com/servo/glutin/pull/68

Related: https://github.com/servo/servo/issues/7408

**Comment by paulrouget** [comment]
We have 2 options here:

1. just set an arbitrary region of 28 css pixels that is draggable from within Glutin. This might be good enough for the June release;
2. expose a Glutin API to set the region programmatically. From Servo, this could be bound to a CSS property (see https://github.com/servo/servo/issues/7408)

**Comment by pcwalton** [comment]
Blocked on https://github.com/servo/glutin/pull/79.

**Comment by pcwalton** [comment]
#10037 should fix this
