### ISSUE TITLE
Implement input.setSelectionRange

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9862]

**Comment by KiChjang** [comment]
Spec: https://html.spec.whatwg.org/multipage/forms.html#dom-textarea/input-setselectionrange
Code: `components/script/dom/htmlinputelement.rs`, `components/script/dom/webidls/HTMLInputElement.webidl`

**Comment by saurvs** [comment]
I'd like to work on this.

**Comment by KiChjang** [comment]
Sure thing!
