### ISSUE TITLE
Disable tidy length check for single import statements

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9864]
If we have something like the following:
```rust
use dom::bindings::HorrendouslyLongClassNameThatWasMandatedByTheWHATWGSpec::HorrendouslyLongClassNameThatWasMandatedByTheWHATWGSpecBindings;
```

./mach test-tidy currently will fail because the line is longer than 120 characters. We should instead check whether the line is a use statement, and if so, only do a length check when there are braces detected in the use statement (otherwise don't perform any checks at all).

Code: `python/tidy.py`

**Comment by creativcoder** [comment]
I'm working on it.

**Comment by SimonSapin** [comment]
I don’t think it’s necessary to change tidy here. Whitespace is ignored between tokens so this line can be broken into multiple lines smaller than 120 chars each:

```rust
use dom::bindings::HorrendouslyLongClassNameThatWasMandatedByTheWHATWGSpec::
    HorrendouslyLongClassNameThatWasMandatedByTheWHATWGSpecBindings;
```

**Comment by nox** [comment]
@SimonSapin You end up with "use statement spans multiple lines".

**Comment by SimonSapin** [comment]
I think we should relax *that* instead of the line length limit.

**Comment by Wafflespeanut** [comment]
rustfmt does the latter (I guess). Maybe we can allow tidy to ignore multiple line `use` statements if it doesn't have curly braces (i.e., multiple imports),
