### ISSUE TITLE
Doesn't scroll at 60 FPS

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9879]
`servo -w https://www.rust-lang.org/documentation.html`

Got fullscreen. It probably scrolls at ~40 FPS.

**Comment by paulrouget** [comment]
(osx, retina display)

**Comment by pcwalton** [comment]
Probably overdraw, testing now.

**Comment by pcwalton** [comment]
May not be overdraw related. I get 2-3 ms for a draw.

**Comment by pcwalton** [comment]
A debug build feels better than a release build (!)

**Comment by glennw** [comment]
I'll profile this when I can. If it's overdraw, there are a few simple optimizations we can make that should sort that out. There's also several easy wins to be had in the current vertex shader complexity. However, it's possible that it's more related to event queue spamming or something similar if a release build feels worse than debug!

**Comment by glennw** [comment]
@pcwalton I'm fairly certain there is a resource leak occurring somewhere. On this page, and on many other demos, I see the CPU compositor time increasing linearly with every frame that gets rendered. That might explain the issue reported here.

**Comment by pcwalton** [comment]
After a lot of investigation, my current theory is that it's a scroll event issue on Mac. We batch up all scroll events on each frame that occurred during the composite. If the composite is running too fast it might be that the scroll event bucketing becomes unbalanced: frame 1 processes a small number of scroll events, frame 2 processes a bunch, frame 3 processes a small number, frame 4 processes a whole bunch, etc. That makes it feel like it "pops".

Apparently Gecko limits the scroll event queue to a small fixed number, like 5. If so, we should do the same.

**Comment by paulrouget** [comment]
> Apparently Gecko limits the scroll event queue to a small fixed number, like 5. If so, we should do the same.

I'm not sure this is true. Any idea where this would be happening in Gecko?

**Comment by paulrouget** [comment]
Talked to Nikal. We do have scroll events interpolation code.

Relevant blog posts: http://www.masonchang.com/blog/2014/8/11/smooth-scrolling-frame-uniformity-touch-interpolation-and-touch-responsiveness , http://www.masonchang.com/blog/2014/8/25/androids-touch-resampling-algorithm

**Comment by mstange** [comment]
On OS X we process all scroll events immediately as they come in. They change the scroll offset on the scroll frame and trigger a composite, and that composite will make use of the most recent scroll position that has been set.
We do have a velocity queue that is limited to 5, which is only used for averaging the velocity of the most recent scroll events. The velocity is used for adjusting the displayport placement and for scroll snapping (for finding the best snap point).

**Comment by paulrouget** [comment]
@pcwalton is that a thing you are planning to work on?

**Comment by pcwalton** [comment]
Here's something interesting I found:

Put on a YouTube video on in Firefox in the background and start a release Servo with WebRender pointing to https://www.rust-lang.org/documentation.html. *Without clicking anywhere*, notice that the scrolling feels laggy. Now click on Firefox and click back to Servo. (Click; do not use cmd+Tab.) Servo feels responsive again!

Another thing to try: Click on a Terminal window and scroll in Servo without activating it. Laggy again. Now click on Servo. Responsive!

I am wondering whether some part of the system (WindowServer? Kernel?) is throttling Servo due to mistakenly thinking it's in the background. Servo is not a normal .app, so it could easily confuse the system…
