### ISSUE TITLE
Tidy doesn't scan `support/android/build-apk/src/main.rs`

### ISSUE THREAD

**Issue by ecoal95** [servo/servo#9893]
In #9891, a lot of trailing white-space was removed, that wasn't caught by tidy.

It should be easy to make it scan that file too.

cc: @Wafflespeanut

**Comment by jdm** [comment]
Code: `python/tidy.py`

**Comment by UK992** [comment]
I would like to take this.

**Comment by ecoal95** [comment]
It's yours then! :)

**Comment by UK992** [comment]
it will be ok to scan entire directory ``support/android/build-apk/`` ?
