### ISSUE TITLE
Loading http://twitter.com yields a white screen and a maxed-out CPU in a debug build

### ISSUE THREAD

**Issue by jdm** [servo/servo#9897]
And this is the only terminal output:
```
ERROR:js::rust: Error at http://twitter.com/:2:187: invalid range in character class
```

**Comment by jdm** [comment]
Instruments.app claims that lots of the execution time is spent under `Parser::source_location` which is called from `parser::log_css_error` via `CSSErrorReporter::report_error`.

**Comment by jdm** [comment]
```
Running Time	Self		Symbol Name
29841.0ms   30.2%	0.0	 	                            script::parser::Parser<'i, 't>::source_location
29841.0ms   30.2%	0.0	 	                             tokenizer::Tokenizer$LT$$u27$a$GT$::source_location::h3222111610f8e47dcdb
29841.0ms   30.2%	0.0	 	                              cssparser::str::str::find<&[char]>
29841.0ms   30.2%	0.0	 	                               cssparser::str::str.StrExt::find<&[char]>
29840.0ms   30.2%	0.0	 	                                cssparser::str::pattern::CharSliceSearcher<'a, 'b>.Searcher<'a>::next_match
29836.0ms   30.2%	183.0	 	                                 cssparser::str::pattern::Searcher::next_match<core::str::pattern::CharEqSearcher<&[char]>>
29639.0ms   30.0%	1397.0	 	                                  cssparser::str::pattern::CharEqSearcher<'a, C>.Searcher<'a>::next
```

**Comment by jdm** [comment]
When I let Servo run for multiple minutes, I eventually get actual page content!

**Comment by jdm** [comment]
Note: optimized builds perform significantly better (ie. seconds instead of minutes).

**Comment by RichardlL** [comment]
Just notifying that I got this figured out, I'll do a write up shortly.

**Comment by RichardlL** [comment]
After looking over this for a few hours, I couldn't determine any major performance problems.

What is happening is that for every parsing error, `source_location()`takes the position, and counts the number of new lines `(\n, \r, \r\n)` , to give a row and column. It also keeps the last position and line number, so it doesn't lose count between errors.

Twitter has a few ~10k css files, and it discovers a few errors.

The problem is that the logging shouldn't be turned on by default. I'm not even sure if you can get Firefox to source location css files warnings.

What Firefox outputs is just `1:Position` 
(Note, if it already knows the line number, it might give it relative to that line numbers position, but it usually doesnt)

![image](https://cloud.githubusercontent.com/assets/6051772/13618353/ac872bf0-e551-11e5-8b58-d89252703149.png) 

This file has it behaves like Firefox does, and `source_location()` is disabled, unless 'LogLevel::Info' is on

https://github.com/servo/servo/blob/3680e82cab766a412a969a21c0cdff0c7f97d7bc/components/style/error_reporting.rs,

I think this one may be accidental, since it finds it, but it doesn't log it, but does report it. https://github.com/servo/servo/blob/b870aa90878acf97074fa55260beb8acfd125f22/components/script/reporter.rs#L25

I'm make pull request to change the latter, so it logs like Firefox normally, but when 'LogLevel::Info` it uses 'source_location()'

(I believe Firefox's version is  called `source_map()`)

**Comment by jdm** [comment]
Note that the one in reporter.rs isn't accidental - it's unnecessary for the case when the developer tools aren't enabled (since ReportCSSError should be ignored in that case), but if running with devtools then we want to be able to store logged CSS errors, including position/column. Although this only _seriously_ affects debug builds, I'm hoping that we can find a way to not ruin the experience of using debug builds with developer tools turned on.

**Comment by jdm** [comment]
When I make the following change to rust-cssparser, I no longer see any evidence of source_location in the profiles:
```diff
diff --git a/src/tokenizer.rs b/src/tokenizer.rs
index a2ba721..b6124a4 100644
--- a/src/tokenizer.rs
+++ b/src/tokenizer.rs
@@ -290,6 +290,7 @@ impl<'a> Tokenizer<'a> {
             line_number = 1;
         }
         let mut source = &self.input[position..target];
+        let mut found_any = false;
         while let Some(newline_position) = source.find(&['\n', '\r', '\x0C'][..]) {
             let offset = newline_position +
             if source[newline_position..].starts_with("\r\n") {
@@ -300,6 +301,10 @@ impl<'a> Tokenizer<'a> {
             source = &source[offset..];
             position += offset;
             line_number += 1;
+            found_any = true;
+        }
+        if !found_any {
+            position = target;
         }
         debug_assert!(position <= target);
         self.last_known_line_break.set((line_number, position));
```
Instead, layout::matching::matches_compound_selector is hogging 77% of the profile. 75% is layout::matching::can_fast_reject, with 68% in Element::has_class.

**Comment by jdm** [comment]
cc @SimonSapin for thoughts on the previous diff.

**Comment by jdm** [comment]
Profile for the curious:
```
Running Time	Self		Symbol Name
89849.0ms   99.9%	0.0	 	layout::layout_thread::LayoutThread::handle_request  0x16932c
89849.0ms   99.9%	0.0	 	 0xd400008902
89849.0ms   99.9%	0.0	 	  fnfn
89849.0ms   99.9%	0.0	 	   fnfn
89849.0ms   99.9%	0.0	 	    layout::layout_thread::LayoutThread::start
89849.0ms   99.9%	0.0	 	     layout::layout_thread::LayoutThread::handle_request
89849.0ms   99.9%	0.0	 	      layout::layout_thread::LayoutThread::handle_request_helper
89849.0ms   99.9%	0.0	 	       fnfn
89849.0ms   99.9%	2.0	 	        layout::layout_thread::LayoutThread::handle_reflow
89721.0ms   99.8%	0.0	 	         layout::selector_matching::Stylist<Impl>::compute_restyle_hint<layout::wrapper::ServoLayoutElement>
89689.0ms   99.7%	655.0	 	          layout::restyle_hints::DependencySet<Impl>::compute_hint<layout::wrapper::ServoLayoutElement>
69711.0ms   77.5%	250.0	 	           layout::matching::matches_compound_selector<layout::wrapper::ServoLayoutElement>
69461.0ms   77.2%	429.0	 	            layout::matching::matches_compound_selector_internal<layout::wrapper::ServoLayoutElement>
67846.0ms   75.4%	420.0	 	             layout::matching::can_fast_reject<layout::wrapper::ServoLayoutElement>
65410.0ms   72.7%	0.0	 	              fnfn
65409.0ms   72.7%	248.0	 	               layout::matching::matches_simple_selector<layout::wrapper::ServoLayoutElement>
61675.0ms   68.6%	34.0	 	                wrapper::ServoLayoutElement$LT$$u27$le$GT$...selectors..Element::has_class::h6a17c97a42053985SCy
61458.0ms   68.3%	108.0	 	                 layout::dom::element::LayoutJS<Element>.LayoutElementHelpers::has_class_for_layout
38379.0ms   42.7%	87.0	 	                  layout::dom::element::get_attr_for_layout
23035.0ms   25.6%	0.0	 	                   fnfn
8027.0ms    8.9%	91.0	 	                    layout::dom::bindings::js::JS<T>::to_layout
7483.0ms    8.3%	124.0	 	                     thread_state::imp::get::hda1f16dcf7d522d5n5e
397.0ms    0.4%	31.0	 	                     thread_state::ThreadState::is_layout::h9bf00174e2aa609dK2e
54.0ms    0.0%	39.0	 	                     layout::nonzero::NonZero<T>.::clone::Clone::clone
1.0ms    0.0%	0.0	 	                     <Unknown Address>
1.0ms    0.0%	1.0	 	                     DYLD-STUB$$memset
8008.0ms    8.9%	83.0	 	                    layout::dom::attr::LayoutJS<Attr>.AttrHelpersForLayout::local_name_atom_forever
6352.0ms    7.0%	92.0	 	                    layout::dom::bindings::js::LayoutJS<T>::unsafe_get
449.0ms    0.4%	44.0	 	                    layout::cmp::impls::&'a A.PartialEq<&'b B>::eq
155.0ms    0.1%	155.0	 	                    layout::atom::Atom.::std::cmp::PartialEq::eq
28.0ms    0.0%	0.0	 	                    <Unknown Address>
16.0ms    0.0%	16.0	 	                    layout::dom::attr::Attr::namespace
6532.0ms    7.2%	84.0	 	                   layout::dom::bindings::cell::DOMRefCell<T>::borrow_for_layout
6502.0ms    7.2%	0.0	 	                   fnfn
770.0ms    0.8%	217.0	 	                   layout::iter::Iterator::find<core::slice::Iter<script::dom::bindings::js::JS<script::dom::attr::Attr>>,closure>
578.0ms    0.6%	39.0	 	                   layout::slice::[T]::iter
470.0ms    0.5%	0.0	 	                   <Unknown Address>
252.0ms    0.2%	58.0	 	                   layout::vec::Vec<T>.ops::Deref::deref
91.0ms    0.1%	0.0	 	                   string_cache..atom..Atom::drop.48652::h5499a075e56603a6
56.0ms    0.0%	56.0	 	                   layout::option::Option<T>::map<script::dom::bindings::js::LayoutJS<script::dom::attr::Attr>,closure>
6.0ms    0.0%	6.0	 	                   DYLD-STUB$$memset
16105.0ms   17.9%	0.0	 	                  fnfn
13637.0ms   15.1%	86.0	 	                   layout::dom::attr::LayoutJS<Attr>.AttrHelpersForLayout::value_tokens_forever
13187.0ms   14.6%	23.0	 	                    layout::dom::attr::LayoutJS<Attr>.AttrHelpersForLayout::value_forever
6649.0ms    7.3%	76.0	 	                     layout::dom::bindings::js::LayoutJS<T>::unsafe_get
6493.0ms    7.2%	92.0	 	                     layout::dom::bindings::cell::DOMRefCell<T>::borrow_for_layout
22.0ms    0.0%	0.0	 	                     <Unknown Address>
352.0ms    0.3%	64.0	 	                    layout::vec::Vec<T>.ops::Deref::deref
12.0ms    0.0%	0.0	 	                    <Unknown Address>
1208.0ms    1.3%	465.0	 	                   layout::iter::Iterator::any<core::slice::Iter<string_cache::atom::Atom>,closure>
519.0ms    0.5%	32.0	 	                   layout::slice::[T]::iter
485.0ms    0.5%	0.0	 	                   fnfn
168.0ms    0.1%	168.0	 	                   layout::option::Option<T>::unwrap
82.0ms    0.0%	0.0	 	                   <Unknown Address>
6.0ms    0.0%	6.0	 	                   DYLD-STUB$$memset
6687.0ms    7.4%	75.0	 	                  layout::dom::bindings::js::LayoutJS<T>::unsafe_get
100.0ms    0.1%	0.0	 	                  <Unknown Address>
76.0ms    0.0%	73.0	 	                  layout::option::Option<T>::map_or<bool,closure>
3.0ms    0.0%	3.0	 	                  string_cache..namespace..Namespace::drop.50433::ha407c22a4da16824
110.0ms    0.1%	0.0	 	                 string_cache..atom..Atom::drop.48652::h5499a075e56603a6
64.0ms    0.0%	0.0	 	                 <Unknown Address>
9.0ms    0.0%	0.0	 	                 string_cache..namespace..Namespace::drop.50433::ha407c22a4da16824
2667.0ms    2.9%	4.0	 	                wrapper::ServoLayoutElement$LT$$u27$le$GT$...selectors..Element::is_html_element_in_html_document::h7df62ab6e503b4faPEy
```

**Comment by RichardlL** [comment]
I meant accidental as in it was not under `if LogLevel::Info` s block

Does devtools set Loglevel::info, or should I check for another flag?

**Comment by RichardlL** [comment]
I looked up that error code earlier, its from spidermonkey, The furthest I got was finding out it was for when the start of a range was greater than the end of it.

**Comment by jdm** [comment]
@RichardlL How would the source location be contained under the `if LogLevel::Info`? We send the column and line number as part of the ReportCSSError message. As for detecting if devtools are in use, that's the `devtools_port` field of the `Opts` struct in `utils/opts.rs`.

With regards to the JS error from the first comment, it's a red herring. The JS that's being parsed when it occurs won't execute in Servo.

**Comment by SimonSapin** [comment]
@jdm Very interesting! I think your diff above causes the method to return incorrect results, but it illustrates the problem: between calls, only the position (and line number) of the last line break is saved, so calling the method for many positions within a single very long line can take O(n²) time overall. A proper fix is to save the entire result of the last call, with a column number as well a line number. I’m working on this now.

68% of the time in `Element::has_class` may also be an opportunity for optimization. Inside that is 42.7% in `element::get_attr_for_layout`, which iterates over a `Vec` of attributes to find `class`. We could cache a vector or set of atoms on `Element` to avoid that iteration.

**Comment by SimonSapin** [comment]
https://github.com/servo/rust-cssparser/pull/102 should fix the performance of `Tokenizer::source_location` on long lines.

**Comment by jdm** [comment]
Fixed by the rust-cssparser changes.
