### ISSUE TITLE
Intermediate optimization level?

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#9904]
Release builds take forever to make, and debug build take forever to run. Browser.html in particular is almost unusable (at least for me) in debug mode: wait multiple seconds or so between hitting the keyboard and a letter showing up in the URL bar, multiple seconds to bring up the "tab" list with only one intermediate frame of the animation showing up…

Can we do something in-between? Maybe `-O1`, or only optimizing some crates?

**Comment by nox** [comment]
@SimonSapin Did we ever take a decision on this?
