### ISSUE TITLE
Ban DOMRefCell until proven safe

### ISSUE THREAD

**Issue by jdm** [servo/servo#9924]
#We ban `Cell<JS<T>>` and require the use of `MutHeap<JS<T>>` instead. We should extend the ban to `DOMRefCell` as well.

Code: `components/plugins/lints/ban.rs`, `tests/compiletest/plugin/compile-fail/ban.rs`

**Comment by yoava333** [comment]
I'd like to give a try

**Comment by jdm** [comment]
@yoava333 Go for it!
