### ISSUE TITLE
HTMLLabelElement activation behavior should call on descendants

### ISSUE THREAD

**Issue by rebstar6** [servo/servo#9928]
See https://html.spec.whatwg.org/multipage/forms.html#the-label-element

Right now, the activation_behavior implementation in HTMLLabelElement calls synthetic click activation steps on the current element, which in turn calls activation_behavior (recursive mess!). This should be called on the descendants of the element.

A HTMLLabelElement click test should also be added.

**Comment by jdm** [comment]
I wrote an [interesting testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Clabel%20id%3D%22first%22%3Ehi%20%3Cinput%20type%3D%22checkbox%22%3E%3Cinput%20type%3D%22checkbox%22%3E%3C%2Flabel%3E%3Cbr%3E%0A%3Cscript%3Edocument.getElementById(%22first%22).click()%3C%2Fscript%3E%0A%0A%3Clabel%20id%3D%22second%22%3Ehi%20%3Cinput%20type%3D%22checkbox%22%20disabled%3E%3Cinput%20type%3D%22checkbox%22%3E%3C%2Flabel%3E%3Cbr%3E%0A%3Cscript%3Edocument.getElementById(%22second%22).click()%3C%2Fscript%3E%0A%0A%3Clabel%20id%3D%22third%22%3Ehi%20%3Ca%20href%3D%22about%3Ablank%22%3Efoo%3C%2Fa%3E%3Cinput%20type%3D%22checkbox%22%3E%3C%2Flabel%3E%3Cbr%3E%0A%3Cscript%3Edocument.getElementById(%22third%22).click()%3C%2Fscript%3E%0A%0A%3Clabel%20id%3D%22fourth%22%3Ehi%20%3Cinput%20type%3D%22radio%22%3E%3Cinput%20type%3D%22checkbox%22%3E%3C%2Flabel%3E%3Cbr%3E%0A%3Cscript%3Edocument.getElementById(%22fourth%22).click()%3C%2Fscript%3E%0A%0A%3Clabel%20id%3D%22fifth%22%3Ehi%20%3Cinput%20type%3D%22radio%22%20disabled%3E%3Cinput%20type%3D%22checkbox%22%3E%3C%2Flabel%3E%3Cbr%3E%0A%3Cscript%3Edocument.getElementById(%22fifth%22).click()%3C%2Fscript%3E%0A%0A%3Clabel%20id%3D%22sixth%22%3Ehi%20%3Cinput%20type%3D%22submit%22%3E%3Cinput%20type%3D%22checkbox%22%3E%3C%2Flabel%3E%3Cbr%3E%0A%3Cscript%3Edocument.getElementById(%22sixth%22).click()%3C%2Fscript%3E%0A%0A%3Clabel%20id%3D%22seventh%22%3Ehi%20%3Cinput%20type%3D%22submit%22%20disabled%3E%3Cinput%20type%3D%22checkbox%22%3E%3C%2Flabel%3E%3Cbr%3E%0A%3Cscript%3Edocument.getElementById(%22seventh%22).click()%3C%2Fscript%3E%0A%0A%3C!--%20The%20following%20testcase%20submits%20the%20form%20when%20click()%20is%20invoked%2C%20affirming%20the%20behaviour%20of%20the%20sixth%20testcase%20--%3E%0A%3C!--%3Clabel%20id%3D%22eighth%22%3Ehi%20%3Cform%20action%3D%22about%3Ablank%22%3E%3Cinput%20type%3D%22submit%22%3E%3C%2Fform%3E%3Cinput%20type%3D%22checkbox%22%3E%3C%2Flabel%3E%3Cbr%3E%0A%3Cscript%3Edocument.getElementById(%22eighth%22).click()%3C%2Fscript%3E--%3E%0A) to attempt to how labels behave in other browsers.

**Comment by rebstar6** [comment]
(awaiting https://github.com/servo/servo/issues/6542 completion/merge - will conflict)

**Comment by rebstar6** [comment]
Viewing the testcase - I assume what we want is the same as how this opens in firefox, yes?
<img width="130" alt="firefox version of test case" src="https://cloud.githubusercontent.com/assets/4467125/13792131/c437625e-eac6-11e5-86c2-5641cc433bb3.png">

**Comment by rebstar6** [comment]
Actually, never mind, I think that makes sense:

In [labeled control](https://html.spec.whatwg.org/multipage/forms.html#labeled-control): "If the for attribute is not specified, but the label element has a labelable element descendant, then the first such descendant in tree order is the label element's labeled control." The labeled control element seems to be what receives the label click action.

[Labelable elements](https://html.spec.whatwg.org/multipage/forms.html#category-label) don't include links, thus the skip.

We also, I assume, don't handle the 'for' attribute (?). Look at what happens if you add this case:

<label for="c2" id="ninth">ForLabel 
<input type="checkbox" id="c1">
<input type="checkbox" id="c2"></label>
<script>document.getElementById("ninth").click()</script>

If 'for' is specified, the click should happen on the item with that id. They dont even have to be nested!

<label for="c4" id="tenth">ForLabel</label>
<input type="checkbox" id="c3">
<input type="checkbox" id="c4">
<script>document.getElementById("tenth").click()</script>

**Comment by jdm** [comment]
Good catch! Yes, matching Firefox here makes sense, and implementing the text you quote is what we should do here. We could add support for the `for` attribute as part of this change, too.

**Comment by rebstar6** [comment]
There is something going on in GetControl() identifying the 'for' item (or 1st labelable) as @Manishearth noted in the previous issue. I'll look into it.

**Comment by rebstar6** [comment]
Yeah, logic was in there. Small change - see PR at https://github.com/servo/servo/pull/10019

**Comment by timvandermeij** [comment]
Fixed by #10019?

**Comment by jdm** [comment]
Yep. Thanks!
