### ISSUE TITLE
requestAnimationFrame doesn't work on Android

### ISSUE THREAD

**Issue by glennw** [servo/servo#9933]
It only seems to animate if you keep a touch event pressed down - I've only tested this with WR.

This _might_ be related to https://github.com/servo/glutin/blob/servo/src/api/android/mod.rs#L302 although I suspect there's at least one other issue before that - as the unimplemented!() macro panic is not occurring in my tests.

cc @larsbergstrom

**Comment by paulrouget** [comment]
It works with the new Android port.
