### ISSUE TITLE
Bare CRs in doc-comment on Windows 10 x86-64

### ISSUE THREAD

**Issue by Zarathustra30** [servo/servo#9935]
Servo fails to compile on Windows 10 x86-64 due to 79 `bare CR not allowed in doc-comment` errors.

[Here is a gist of all of the errors.](https://gist.github.com/Zarathustra30/e54a6fe0fbf8893b2c62)

**Comment by UK992** [comment]
I have the same problem, its caused by Github Desktop app, which change line endings to CRLF, i solved it with this tip: http://stackoverflow.com/a/13154031 to force use of LF endings.

**Comment by Zarathustra30** [comment]
So, I was able to build after re-cloning without ever touching it with the desktop app. The build still seems a bit fragile on Windows, but it's not exactly an issue with Servo itself. Closed.
