### ISSUE TITLE
Failing to build on Windows 10

### ISSUE THREAD

**Issue by sorpaas** [servo/servo#9939]
I'm having trouble building servo on Windows 10. It complains missing `glslang` for `angle`.

```
error: could not find native static library `glslang`, perhaps an -L flag is missing?
Build failed, waiting for other jobs to finish...
Could not compile `angle`.
```

**Comment by larsbergstrom** [comment]
Is this from within the cygwin environment instead of using the carefully-crafted MSYS2 environment as described in the readme? I would not expect Servo to build in any environment that is not identical to the setup described in those steps, unfortunately.

**Comment by sorpaas** [comment]
@larsbergstrom This is in MSYS2.

**Comment by Jayflux** [comment]
@sorpaas are you still having this problem?

**Comment by perlun** [comment]
@metajack - this is the issue I mentioned on IRC some day I ago. I get the same error, also on Windows 10:

```
$ ./mach build -d
   Compiling threadpool v1.3.0
   Compiling glob v0.2.11
   Compiling miniz-sys v0.1.7
   Compiling freetype v0.1.0 (https://github.com/servo/rust-freetype#d564ff90)
   Compiling angle v0.1.0 (https://github.com/servo/angle?branch=servo#eefe3506)
   Compiling num_cpus v0.2.12
   Compiling rand v0.3.14
error: could not find native static library `glslang`, perhaps an -L flag is missing?
Build failed, waiting for other jobs to finish...
error: Could not compile `angle`.

To learn more, run the command again with --verbose.
Build completed in 0:00:24
```

This is in MSYS2, carefully-crafted like you suggest @larsbergstrom. A bunch of other crates did manage to compile correctly (or so I think), so would suspect that this is "something" that is missing on mine and @sorpaas machines.

What is `glslang` in the first place? Where does it come from?

**Comment by emilio** [comment]
@perlun: it comes from servo/angle, can you build it standalone?

**Comment by zeusintuivo** [comment]
I have researched and documented an effective way to have windows environments set up for 32 and 64 bits in Windows 7. I assume this will work in all windowses. 
Please see documentation I posted in this ticket. #12356

**Comment by VidushiVashishth** [comment]
@zeusintuivo : I followed your documentation on issue #12356. Got the following error:
```
mach.bat build --dev
looking for rustc at C:\Users\Vidushi\servo\.servo\rust\13d94d5fa8129a34f5c77a1bcd76983f5aed2434-alt\rustc-nightly-unknown-pc-windows-msvc\rustc\bin\rustc.exe
Downloading Rust compiler...
Download failed (404): Not Found - https://s3.amazonaws.com/rust-lang-ci/rustc-builds-alt/13d94d5fa8129a34f5c77a1bcd76983f5aed2434/rustc-nightly-unknown-pc-windows-msvc.tar.gz
```
I m using windows 10.

**Comment by tigercosmos** [comment]
@VidushiVashishth  `unknown` is solved by #18145

**Comment by dralley** [comment]
This should be closed.

**Comment by jdm** [comment]
We have regular working windows builds at this point.
