### ISSUE TITLE
Update WebSocket blocked ports to match the spec.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9949]
Spec: https://fetch.spec.whatwg.org/#port-blocking
File: `components/script/dom/websocket.rs`
Test: to be written

**Comment by annevk** [comment]
Note that this is not restricted to WebSocket. E.g., this applies to `<a href="https://example.com:21/">test</a>` too.

**Comment by Ms2ger** [comment]
Filed https://github.com/servo/servo/issues/9950 for that.

**Comment by saurvs** [comment]
I'd like to work on this.

**Comment by Ms2ger** [comment]
Go for it!

**Comment by timvandermeij** [comment]
Fixed by #10014?
