### ISSUE TITLE
Implement some or all of HTMLHyperlinkElementUtils

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#9952]
There's a mixin called [HTMLHyperlinkElementUtils](https://html.spec.whatwg.org/multipage/semantics.html#htmlhyperlinkelementutils) which applies to `a` elements among other things.

Here, we will implement the `href` attribute for `<a>`. This is done by:

 - Uncommenting the [interface definition as well as the line for `href`](https://github.com/servo/servo/blob/95883dcbcfe10104c7a78ac532cb9aeb4bda855f/components/script/dom/webidls/HTMLHyperlinkElementUtils.webidl#L6)
 - Uncommenting the [interface implementation](https://github.com/servo/servo/blob/95883dcbcfe10104c7a78ac532cb9aeb4bda855f/components/script/dom/webidls/HTMLAnchorElement.webidl#L29)
 - Adding a `url` field to [htmlanchorelement](https://github.com/servo/servo/blob/95883dcbcfe10104c7a78ac532cb9aeb4bda855f/components/script/dom/htmlanchorelement.rs#L31) of type `Option<Url>`
 - Implementing the [set the url](https://html.spec.whatwg.org/multipage/semantics.html#concept-hyperlink-url-set) function on HTMLAnchorElement somewhere such that it sets the inner `Url`. It should also be called in the `parse_plain_attribute` function as mentioned in the spec.
 - Implementing the [reinitialize the url](https://html.spec.whatwg.org/multipage/semantics.html#reinitialise-url) function using the above
 - Implementing the [href getter](https://html.spec.whatwg.org/multipage/semantics.html#dom-hyperlink-href) and setter on HTMLAnchorElement. These will turn out to be `Href()` and `SetHref` functions.

Optionally implement the rest of the getters.

Tests: `/tests/wpt/web-platform-tests/html/dom/interfaces.html`, `/tests/wpt/web-platform-tests/url/a-element.html`

**Comment by Manishearth** [comment]
@ogeagla is working on this

**Comment by jdm** [comment]
@Manishearth isn't this #9887?

**Comment by Manishearth** [comment]
Yeah. Didn't notice the PR.

@ogeagla You can work on trait-ifying that PR when it lands. I'll also look for something else to work on

**Comment by ogeagla** [comment]
@Manishearth sounds good, thanks

**Comment by jdm** [comment]
Fixed by #9887.
