### ISSUE TITLE
Disable builds on the master branch for AppVeyor

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#9953]
Currently, AppVeyor builds the master branch every time that something is merged into it (see: https://ci.appveyor.com/project/servo/servo/history). However, that's not entirely useful, since it has already built exactly that commit on the `auto` branch in order to land it!

We'd like to either disable or no-op the builds on master... but hopefully without breaking AppVeyor builds on PR branches.

**Comment by UK992** [comment]
May i suggest to enable [Rolling builds](http://www.appveyor.com/docs/build-configuration#rolling-builds) option, to shorten the build queue. Especially for unnecessary double builds on ```auto``` branch.

**Comment by larsbergstrom** [comment]
The last time we turned it on, it just seemed to be randomly canceling tons of builds. Though maybe that was actually https://github.com/servo/homu/issues/23?

@Manishearth @edunham Do you remember what was happening when we last tried Rolling Builds and had so little success? If it was indeed just the `try`-related madness, turning it on would save a *ton* of effort :-)

**Comment by Manishearth** [comment]
I don't recall the reason behind rolling builds failing.

The easy way to make this work is to dynamically check if it's on the master branch and not a PR in the appveyor script and skip the build in that case. There's no configuration to do this.

**Comment by UK992** [comment]
@larsbergstrom Now that Windows builds building on dedicated buildbot machine, should be ``auto`` and ``try`` removed from appveyor.yml to reduce queue?

**Comment by larsbergstrom** [comment]
@UK992 Good call! I've excluded them from the AppVeyor settings :-) But yes, we could remove them from the appveyor.yml.
