### ISSUE TITLE
Show a URL rather than "untitled" in the title bar

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#9960]
![screenshot from 2016-03-10 21-39-30](https://cloud.githubusercontent.com/assets/291359/13683734/9dc84ece-e708-11e5-900a-a70cb50df82a.png)

Currently the "title" of a Servo window is `{} - Servo`, where `{}` is (I think) the contents of the `<title>` element, or `untitled` if that is missing or empty.

Using the document’s URL would be a more useful default than `untitled`.

**Comment by F3real** [comment]
I am interested in trying to do this.

**Comment by jdm** [comment]
Go ahead!

**Comment by frewsxcv** [comment]
@F3real Still working on this? Need any help?

**Comment by jrasanen** [comment]
I can try this as my first issue, if its available.

**Comment by frewsxcv** [comment]
Go for it @jrasanen!

**Comment by jdm** [comment]
Fixed by #10195.
