### ISSUE TITLE
Properly use [PutForwards] like we should in WebIDL interfaces

### ISSUE THREAD

**Issue by nox** [servo/servo#9990]
See #9350.

**Comment by jdm** [comment]
Specifically, the PR looks good but is missing tests that the attributes using PutForwards do what they're supposed to.

**Comment by tbu-** [comment]
I'd like to try this.

**Comment by jdm** [comment]
@tbu- Please do! Ask questions here if anything's unclear :)

**Comment by nox** [comment]
This still hasn't been done.

**Comment by pshaughn** [comment]
#25037 and #25038 were me not realizing that ElementCSSInlineStyle.webidl has the PutForwards part of HTMLElement.style commented out entirely.

**Comment by nox** [comment]
Oops, misclick.

**Comment by jdm** [comment]
Marking this as high-value because code like `foo.style = "display: none"` just silently does not work in Servo right now, which likely leads to web compat issues.

**Comment by pshaughn** [comment]
I've tried to find every location that defines a PutForwards and note its current status. The only implemented attributes with a missing PutForwards appear to be ElementCSSInlineStyle.cssText and multiple instances of .relList, although it's possible I missed a relevant spec.

from WHATWG HTML:
* Document.location - already PutForwards in Servo
* Window.location - already PutForwards in Servo
* HTMLIFrameElement.sandbox - already PutForwards in Servo
* HTMLAnchorElement.relList - attribute exists in Servo without PutForwards
* HTMLAreaElement.relList - attribute exists in Servo without PutForwards
* HTMLLinkElement.relList - attribute exists in Servo without PutForwards
* HTMLFormElement.relList - attribute is entirely absent in Servo
* HTMLLinkElement.sizes - attribute is commented out in Servo
* HTMLOutputElement.htmlFor - attribute is commented out in Servo

From CSSOM:
* CSSStyleRule.cssText - already PutForwards in Servo
* ElementCSSInlineStyle.cssText - attribute exists in Servo with commented-out PutForwards
* CSSImportRule.mediaText - attribute is commented out in Servo
* Stylesheet.mediaText - attribute is commented out in Servo
* CSSPageRule.cssText - no IDL in servo
* CSSMarginRule.cssText - no IDL in servo

From CSS Fonts Module:
* CSSFontFaceRule.style - not PutForwards in spec, attribute with PutForwards is commented out in Servo (probably just cut and paste from other CSS*Rule IDL)

**Comment by pshaughn** [comment]
The ElementCSSInlineStyle.cssText case has tests for it (and pass when the PutForwards is included); the .relList cases seem to be missing test coverage for PutForwards behavior.

**Comment by pshaughn** [comment]
As far as I can tell, assuming the above PR merges, we will be up-to-date on [PutForwards] with respect to attributes that currently exist in Servo's IDL, and remaining lack of PutForwards behavior is because the entire attribute is unimplemented.

**Comment by jdm** [comment]
This should be fixed now!
