### ISSUE TITLE
Implement stub for NavigatorPlugins

### ISSUE THREAD

**Issue by jdm** [servo/servo#9991]
Servo has no support for traditional browser plugins, so the actual implementation should be fairly straightforward (ie. returning None/0/false, etc.).

Spec: https://html.spec.whatwg.org/multipage/webappapis.html#plugins-2 (and add `Navigator implements NavigatorPlugins;`)
Code:
* in `components/script/dom/webidls/`:
  * `Navigator.webidl`, `PluginArray.webidl`, `Plugin.webidl`, `MimeTypeArray.webidl`, `MimeType.webidl`
* in `components/script/dom/`:
  * `navigator.rs`, `pluginarray.rs`, `plugin.rs`, `mimetypearray.rs`, `mimetype.rs`
Tests:
* `./mach test-wpt tests/wpt/mozilla/tests/mozilla/interfaces.html` (modify this test to pass)
* `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.html` (update the `interfaces.html.ini` file to accommodate the new passing tests)

See [the documentation](http://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface) for steps to follow when adding new WebIDL interfaces.

This work is important because when `navigator.plugins` is missing, clicking links on Twitter is broken (see #9870).

**Comment by jdm** [comment]
Claiming this temporarily for potential RGSoC applicants. Please contact me before starting to work on this.

**Comment by jdm** [comment]
This is available for anyone to work on.

**Comment by ConnorGBrewster** [comment]
I would like to work on this one.

**Comment by jdm** [comment]
Go ahead!

**Comment by ConnorGBrewster** [comment]
Implemented in #10485
