### ISSUE TITLE
Implement NavigatorLanguage

### ISSUE THREAD

**Issue by jdm** [servo/servo#9992]
Spec: https://html.spec.whatwg.org/multipage/webappapis.html#navigatorlanguage (and add `Navigator implements NavigatorLanguage;`)
Code: `components/script/dom/webidls/Navigator.webidl`, `components/script/dom/navigator.rs`
Tests:
* `./mach test-wpt tests/wpt/html/dom/interfaces.html`
* `./mach test-wpt tests/wpt/web-platform-tests/html/webappapis/system-state-and-capabilities/the-navigator-object/navigatorlanguage.html`
* Follow [the documentation](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) to adjust for tests that now pass.

The lack of this feature is makes clicking links on Twitter break (see #9870). Let's just hardcode this as `en-US` right now.

**Comment by creativcoder** [comment]
I'll take that, will help me get familiar with dom parts.

**Comment by jdm** [comment]
Great!

**Comment by creativcoder** [comment]
I am getting an error from the `CodegenRust.py`for the `languages` attribute, which returns a StringArray.
Maybe CodegenRust.py does not have type declarations for `DOMString[]` types:
Here's some stack trace:
`  File "/home/creativcoder/Desktop/github/servo/components/script/dom/bindings/codegen/CodegenRust.py", line 1310, in getRetvalDeclarationForType                                               
    returnType)                                                                                                                                                                                 
TypeError: Don't know how to declare return value for StringArray`

**Comment by Ms2ger** [comment]
Start with just `language` for now; we can do `languages` later when https://github.com/whatwg/html/pull/863 is fixed and we support `FrozenArray`.
