### ISSUE TITLE
Implement HTMLTextArea.setSelectionRange

### ISSUE THREAD

**Issue by jdm** [servo/servo#9994]
Spec: https://html.spec.whatwg.org/multipage/forms.html#textFieldSelection
Code: `components/script/dom/htmtextareaelement.rs`, `components/script/dom/webidls/HTMLTextAreaElement.webidl`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/forms/textfieldselection/textfieldselection-setSelectionRange.html`

This will be very similar to #9905 which implemented this API for `<input>` elements.

**Comment by 0X1A** [comment]
@jdm I'm up for grabbing this one

**Comment by jdm** [comment]
Great!

**Comment by 0X1A** [comment]
@jdm I've written the methods required for `setSelectionRange` and edited the `webidl`. When I run the tests they all pass but the output reads
```
Ran 1 tests finished in 18.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 1 tests had unexpected subtest results
```
Is this expected?

**Comment by paulrouget** [comment]
>   1 tests had unexpected subtest results

It means that one test was expected to NOT pass, and now it passes.

See tests/wpt/metadata/html/semantics/forms/textfieldselection/textfieldselection-setSelectionRange.html.ini

You want to update the test expectations: https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations

**Comment by 0X1A** [comment]
@paulrouget Thank you, these are all expected to run as PASS given the correct `setSelectionRange` implementation?

**Comment by paulrouget** [comment]
This test apparently tests `selectionStart`, `selectionEnd` and `setSelectionRange`.
So if all of these are properly implemented, I would expect all of these tests to pass.

**Comment by slayerjain** [comment]
What does the C-assigned tag mean?  Does it mean it's assigned to someone and i can't do it?

**Comment by jdm** [comment]
@slayerjain Yes, that is what it means.

**Comment by slayerjain** [comment]
I guess have to look elsewhere for my first contribution, @jdm any suggestions?

**Comment by jdm** [comment]
I've pushed a rebased and squashed version of #10007 to https://github.com/jdm/servo/tree/textdir. Whoever decides to pick this task up should address the test failures (and newly passing tests) mentioned in https://github.com/servo/servo/pull/10007#issuecomment-202065579.

**Comment by KiChjang** [comment]
@autrilla claimed in IRC.
