### ISSUE TITLE
Support SVG content and images

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#9998]
It seems inline svg ( <svg> <path/> </svg> ) is not rendered at the moment causing the github ( #9914 ) logo in the top left corner to be missing.

Code samples can be found here http://www.w3schools.com/svg/svg_path.asp
![logo](https://cloud.githubusercontent.com/assets/476013/13770676/08b2d6ae-ea89-11e5-8f95-c71bedab9911.png)

**Comment by jdm** [comment]
I strongly suspect we won't implement inline SVG before the June release.

**Comment by jdm** [comment]
#12973 has more information in it.
