### ISSUE TITLE
high CPU usage while moving mouse (~125% CPU)

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9999]
At least on OSX.

STR:
- ./mach run -r -- http://example.com
- move mouse hover the window

125% CPU usage without webrender. 55% with webrender.

**Comment by pcwalton** [comment]
Profiler suggests it's because we're rebuilding the display list when we don't need to. I'll take this one.

**Comment by pcwalton** [comment]
@paulrouget Please check this one again.

**Comment by paulrouget** [comment]
It's a lot better now.

Before: 125% without webrender. 55% with webrender
After:  60% without webrender. 16% with webrender

Thank you!
